### ISSUE TITLE
`get_latest_app_store_version` Returns Old Versions – Possibly Due to Recent API Changes

### ISSUE THREAD

**Issue by canhth** [fastlane/fastlane#26626]
### New Issue Checklist
- [ x ] Updated fastlane to the latest version
- [ x ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ x ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ x ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
My CI jobs have been working normally since this morning, all the `get_live_app_store_version` and `get_latest_app_store_version` from Fastlane returning the value from 2022, not the latest version anymore.

I tried to fork Fastlane and modify the filter and other stuff but not helping at all. Log the response of the request `/v1/apps/{id}/appStoreVersions`, it contains a very old versions.
I think we need support from experts who can help to by-pass or fix this issue.

Seems it may be related to changes in the App Store Connect API. Only happen this morning.

##### Command executed
```
        app = Spaceship::ConnectAPI::App.find(params[:bundle_id])
        latest_version = app.get_latest_app_store_version
        
        UI.message "latest_version: #{latest_version.version_string}"
```

**Comment by ThrowJojo** [comment]
I'm seeing something that I think is the same issue. I'm trying to add new localisations for an app and upload the metadata and I'm getting this error:

```
"The provided entity includes a relationship with an invalid value - Cannot create localization after the app version has been submitted for review."
```

I tried checking out a branch without the new localisations and running deliver again it still gave me the same error. I used deliver 2 days ago to add some new localisations and everything worked without any issues.

**Comment by ivan-gaydamakin** [comment]
I almost have the same issue, but got error:
```
fastlane-2.225.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:60:in `get_build_info': [!] undefined method `version' for nil (NoMethodError)
```

**Comment by ralphcode** [comment]
I think this is related to my [question here](https://github.com/fastlane/fastlane/discussions/26605)

In our case it seems that the `https://appstoreconnect.apple.com/iris/v1/apps/1073341917/appStoreVersions` API does not return paging links and if you have >50 results, you only see the first 50.

**Comment by himamis** [comment]
Might be relevant, but we started to receive `[!] An attribute value is not acceptable for the current resource state. - The attribute 'versionString' can not be modified. - /data/attributes/versionString` just recently for the `deliver` method.

**Comment by xuzheng94** [comment]
> Might be relevant, but we started to receive `[!] An attribute value is not acceptable for the current resource state. - The attribute 'versionString' can not be modified. - /data/attributes/versionString` just recently for the `deliver` method.

I have the same issue~~~~

**Comment by morrowyn** [comment]
> Might be relevant, but we started to receive `[!] An attribute value is not acceptable for the current resource state. - The attribute 'versionString' can not be modified. - /data/attributes/versionString` just recently for the `deliver` method.

I'm seeing the same error with `version 2.225.0`

Permissions weren't changed, so the mentioned fix: https://github.com/fastlane/fastlane/issues/20475 doesn't resolve it.

**Comment by Kondamon** [comment]
Maybe it's related: When I specify an app version like `fastlane deliver download_metadata --app_version "3.0.8"`then I receive an error: `Neither the current nor live version match specified app_version "3.0.8"`. This has worked before the latest update.

**Comment by Kondamon** [comment]
Another bug related to the release version: `An attribute value is not acceptable for the current resource state. - The attribute 'releaseType' can not be modified. - /data/attributes/releaseType`

This can be reproduced by:
```
   deliver(
      submit_for_review: false,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true
    )
```

**Comment by SkylimiTY** [comment]
I have the same issue:
`deliver(  
    release_notes: {
      'default': File.read(“/Users/XXXX/release_notes.txt”),
      'en-US': File.read(“/Users/XXXX/release_notes.txt”)
    },
    submission_information: { add_id_info_uses_idfa: false },   
    submit_for_review: true,
    automatic_release: true,
    ipa: sh("curl -sL URL --output /Users/XXXX"),
    ipa: "/Users/XXXX",
    app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
    team_id: CredentialsManager::AppfileConfig.try_fetch_value(:itc_team_id),
    run_precheck_before_submit: false,
    precheck_include_in_app_purchases: false,
    app_review_attachment_file: "/Users/XXXX",
    force: true,
    skip_metadata: false,
    skip_screenshots: true,
    skip_binary_upload: false,
)`

**Comment by x0000ff** [comment]
Event worse, the last published and approved versions are not event listed in the App Store Connect webpage 🫠 
<img width="963" alt="SCR-20241022-jqpg-2" src="https://github.com/user-attachments/assets/55cd4c4c-0b9f-425c-af6d-cd29bc4262ab">

**Comment by Kondamon** [comment]
> Event worse, the last published and approved versions are not event listed in the App Store Connect webpage 🫠
> 
> <img alt="SCR-20241022-jqpg-2" width="963" src="https://private-user-images.githubusercontent.com/1062240/378756248-55cd4c4c-0b9f-425c-af6d-cd29bc4262ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1ODcyMzMsIm5iZiI6MTcyOTU4NjkzMywicGF0aCI6Ii8xMDYyMjQwLzM3ODc1NjI0OC01NWNkNGM0Yy0wYjlmLTQyNWMtYWY2ZC1jZDI5YmM0MjYyYWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMDg0ODUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBmOWUwYWIyM2IzNGY2OWRhNTA2ZWI1ZGEzODY5ZmQyMmZmYjQ4ZWQ1YzlmN2IzY2VmMDY5MTAwODY1MDFlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GFxwFAftI-xK81CFFhl51jcE04AvcTfJPnrL2rkWsuc">

For me all versions are still there but they are listed randomly. Maybe this is causing the issue.

**Comment by lucapirolo** [comment]
Also seeing this issue

**Comment by rogerluan** [comment]
> So, is it an Apple-related bug that is expected to be resolved soon?

This seems to be the case: a bug on Apple's end. Not sure yet if there's anything we can do about this.

Whenever this happens they usually fix it within a few hours, or a couple days the latest. 

Let's be patient and hope for the former 🙏🙏

**Comment by kitallis** [comment]
Seeing this issue right now, even the history tab on ASC itself is all in the wrong order.

**Comment by stephsadim-npi** [comment]
Seeing this error as well.

**Comment by bvirlet** [comment]
I can confirm the same issue when trying to upload screenshots, and noticed that the version history on Apple's side is completely wrong.

**Comment by douzal34** [comment]
Same issue on my side, can't publish new version on the store.
`Spaceship::UnexpectedResponse: [!] An attribute value is not acceptable for the current resource state. - The attribute 'versionString' can not be modified. - /data/attributes/versionString`

**Comment by nid90** [comment]
> An attribute value is not acceptable for the current resource state. - The attribute 'versionString' can not be modified

This is related to the app store versions API returning things out of order and not respecting filters. Due to this, the latest inflight store version being returned is very likely an old one that can not be edited.

We have started seeing some really old versions returned for most of the fastlane/spaceship `get_<x>_app_store_version` functions.

Waiting for Apple devs to wake up and fix this.

**Comment by rosajsx** [comment]
Same here. It was started yesterday in some apps, it's funny because some apps could be deployed normally :/

**Comment by rogerluan** [comment]
I found out about this issue through one of the customers over at [Statused](https://statused.com): apparently their app status is being reported wrong since last night:

![1](https://github.com/user-attachments/assets/6067b6dd-57da-4193-a4c8-d0150b30b123)

I also saw that Apple released App Store Connect API v3.6 Beta 1 (not sure when): https://developer.apple.com/documentation/appstoreconnectapi/ — this might be related.

I'll keep a close eye on this issue and hope that Apple fixes it soon.

**Comment by rosajsx** [comment]
Guys i found a workaround. 

If i create the desired version in apple connect without any build and trigger the pipeline again, it works!

**Comment by donatoaguirre24** [comment]
> Guys i found a workaround.
> 
> If i create the desired version in apple connect without any build and trigger the pipeline again, it works!
> 
> For example: My build to deploy in CI it's 2.0.0 then i have created a 2.0.0 version in AppleConnect app and trigger again the pipeline.
> 
> It's a manual process but if you need to do this faster, it's the way.

I tried this, but unfortunately it didn't work of us

**Comment by frankiesimon** [comment]
Experiencing this as well!

**Comment by tastydev** [comment]
Same here, for sure Apple noticed this already since this affects every Dev/App Companies

**Comment by solinvictus1313** [comment]
> Guys i found a **workaround**.
> 
> If i create the desired version in apple connect without any build and trigger the pipeline again, it works!

Can confirm, works fine for me. Thanks for sharing!

**Comment by jarekb123** [comment]
We found a workaround - publish app to the testflight and do manual release from testflight.

**Comment by cherpake** [comment]
Same issue, tried creating new version in ASC manually, nothing works.
Can't even upload metadata.

**Comment by CaptainJeff** [comment]
@jarekb123 i get the same error while trying to uplaod to testflight

**Comment by foureight84** [comment]
> Guys i found a **workaround**.
> 
> If i create the desired version in apple connect without any build and trigger the pipeline again, it works!
> 
> For example: My build to deploy in CI it's 2.0.0 then i have created a 2.0.0 version in AppleConnect app and trigger again the pipeline.
> 
> It's a manual process but if you need to do this faster, it's the way.

Confirmed working!

**Comment by JovannyEspinal** [comment]
> > Guys i found a **workaround**.
> > If i create the desired version in apple connect without any build and trigger the pipeline again, it works!
> > For example: My build to deploy in CI it's 2.0.0 then i have created a 2.0.0 version in AppleConnect app and trigger again the pipeline.
> > It's a manual process but if you need to do this faster, it's the way.
> 
> Confirmed working!

Before I submit build 2.0, I should create 2.0 version in ASC?

If so, not working on my end. :(

**Comment by cherpake** [comment]
> > > Guys i found a **workaround**.
> > > If i create the desired version in apple connect without any build and trigger the pipeline again, it works!
> > > For example: My build to deploy in CI it's 2.0.0 then i have created a 2.0.0 version in AppleConnect app and trigger again the pipeline.
> > > It's a manual process but if you need to do this faster, it's the way.
> > 
> > 
> > Confirmed working!
> 
> Before I submit build 2.0, I should create 2.0 version in ASC?
> 
> If so, not working on my end. :(

same here... created new version in ASC tried uploading - doesn't work. Seems it not for everyone

**Comment by pyby** [comment]
I contacted Apple "distribution" topic.
https://developer.apple.com/contact/topic/select

**Comment by Kondamon** [comment]
> > > > Guys i found a **workaround**.
> > > > If i create the desired version in apple connect without any build and trigger the pipeline again, it works!
> > > > For example: My build to deploy in CI it's 2.0.0 then i have created a 2.0.0 version in AppleConnect app and trigger again the pipeline.
> > > > It's a manual process but if you need to do this faster, it's the way.
> > > 
> > > 
> > > Confirmed working!
> > 
> > 
> > Before I submit build 2.0, I should create 2.0 version in ASC?
> > If so, not working on my end. :(
> 
> same here... created new version in ASC tried uploading - doesn't work. Seems it not for everyone

In my case the upload also worked. But you should not upload meta_data, screenshots or any other related stuff regarding versions. I just do `build_app()` and then `upload` in fastlane.

**Comment by JovannyEspinal** [comment]
> > > > > Guys i found a **workaround**.
> > > > > If i create the desired version in apple connect without any build and trigger the pipeline again, it works!
> > > > > For example: My build to deploy in CI it's 2.0.0 then i have created a 2.0.0 version in AppleConnect app and trigger again the pipeline.
> > > > > It's a manual process but if you need to do this faster, it's the way.
> > > > 
> > > > 
> > > > Confirmed working!
> > > 
> > > 
> > > Before I submit build 2.0, I should create 2.0 version in ASC?
> > > If so, not working on my end. :(
> > 
> > 
> > same here... created new version in ASC tried uploading - doesn't work. Seems it not for everyone
> 
> In my case the upload also worked. But you should not upload meta_data, screenshots or any other related stuff regarding versions. I just do `build_app()` and then `upload` in fastlane.

Ah. Perfect.

This ended up working for me. Here's what I ended up doing to get my build uploaded for those reading:

1. Create app version (same as the one that will be submitted via fastlane) in App Store Connect
2. Edit deliver to include skip_metadata and skip_screenshots set to true
3. Removed anything related to versions.
```
deliver(
      username: ENV['APPSTORE_USERNAME'],
      force: true,
      skip_metadata: true,
      skip_screenshots: true,
      phased_release: true,
      submit_for_review: false,
      precheck_include_in_app_purchases: false
    )
```

Ended up working for me. Thanks @Kondamon!

**Comment by x0000ff** [comment]
It looks like Apple has fixed the API 🥳

**Comment by nid90** [comment]
Yes, seems to be working fine now.

**Comment by CaptainJeff** [comment]
Yup. Fixed now for me too!

**Comment by rogerluan** [comment]
> I found out about this issue through one of the customers over at [Statused](https://statused.com): apparently their app status is being reported wrong since last night:
> 
> ![1](https://private-user-images.githubusercontent.com/8419048/378851840-6067b6dd-57da-4193-a4c8-d0150b30b123.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjgyMzAsIm5iZiI6MTcyOTYyNzkzMCwicGF0aCI6Ii84NDE5MDQ4LzM3ODg1MTg0MC02MDY3YjZkZC01N2RhLTQxOTMtYTRjOC1kMDE1MGIzMGIxMjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMjAxMjEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRhMDY4MjIyY2RmNWIwZGYwY2U3MmMyZWFhNTFmOTc4MmYwNTJiYjU1ZTA2OGU1YTVjNWZhZGZlOTUxZGVlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AYqOjlaycKGL0rhRBJtIC0080R-cVortOeAe0XhvVTs)
> 
> I also saw that Apple released App Store Connect API v3.6 Beta 1 (not sure when): https://developer.apple.com/documentation/appstoreconnectapi/ — this might be related.
> 
> I'll keep a close eye on this issue and hope that Apple fixes it soon.

+1, it seems to be working here, including for the specific use case that powers Statused 🙏

**Comment by canhth** [comment]
It works again mostly. But I still having one issue:
```
{:id=>"xxxx", :name=>"My App name, :bundle_id=>"com.xxx.xxx", :version=>"2.9.1", :state=>"ACTIVE", :current_day=>7, :percent=>100}
```

The Phase Release is 100, The state should be COMPLETED instead. Not sure if Apple changed the rule 😢 

Does anyone have similar/other problem still?

**Comment by canhth** [comment]
Seems everything is fixed now. I'm closing this issue, thanks everyone 🥂

**Comment by kitallis** [comment]
> It works again mostly. But I still having one issue:
> 
> ```
> {:id=>"xxxx", :name=>"My App name, :bundle_id=>"com.xxx.xxx", :version=>"2.9.1", :state=>"ACTIVE", :current_day=>7, :percent=>100}
> ```
> 
> The Phase Release is 100, The state should be COMPLETED instead. Not sure if Apple changed the rule 😢
> 
> Does anyone have similar/other problem still?

@canhth I figure this was resolved for you. But just for posterity, the state takes 24 hours to update, even on the 7th day. So 100% + `COMPLETED` are not necessarily congruent states. Hope that helps.

**Comment by LeonardoRosaa** [comment]
I still have this issue 😢

**Comment by diegoveloper** [comment]
> I still have this issue 😢

same here

**Comment by canhth** [comment]
This issue is from Apple's side, not from Fastlane. I'll reopen the issue only if anyone has a similar issue with Fastlane
