### ISSUE TITLE
xcarchive and xcexport actions don't seem to sign ipa correctly

### ISSUE THREAD

**Issue by robwithhair** [fastlane/fastlane#272]
Tried moving over to xcarchive and xcexport to create builds after ipa started triggering watchkit warnings on upload.  The builds I generated did not seem to be signed correctly with the deployment identity created using actions produce, cert, sigh, update_project_code_signing, xcarchive, xcexport.  Got the following error from itunes connect.

ERROR ITMS-90035: "Invalid Signature. A sealed resource is missing or invalid. The binary at path [Framework.app/Framework] contains an invalid signature. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"

Never managed to get this working despite setting the correct signing identiy in xcode and running again.  Ended up downgrading fastlane and shenzhen and now it's working again.

**Comment by aafa** [comment]
+1 to this.  I'm using xcarchive and xcexport to create ipa and send to iTC with `deliver`. 
But in my case I haven't got any errors - everything seems green but no one can install an app from iTC TestFlight.  
Seems like signing issue to me.

**Comment by fabiomassimo** [comment]
+1

**Comment by robertjpayne** [comment]
Looks like this is caused because `xcodebuild` exporting from the CLI doesn't archive in the `archived-expanded-entitlements.xcent` file that Xcode itself does. 

I'm looking at solutions but a build action running this seems to do a better job of not touching the package.

`/usr/bin/xcrun -sdk iphoneos PackageApplication -v /Path/To/Archive/name.xcarchive/Products/Applications/name.app -o /Path/To/Archive/DiplomatStaples.ipa`

**Comment by fabiomassimo** [comment]
nice catch @robertjpayne .
I've found this interesting too: http://stackoverflow.com/questions/23682083/xcodebuild-not-copying-file-from-app

The winning answer cleared up my mind a little bit.

**Comment by KrauseFx** [comment]
As you know I've been working on [gym](https://github.com/fastlane/gym) which uses the latest API to build and sign your app. Please give it a try by passing a valid provisioning profile and let me know if that works for you.

**Comment by fabiomassimo** [comment]
In case someone is interested I'm currently implementing the `xcrun` export command on my `gym` fork.
It's currently under test with my projects but in case you want to give it a spin: https://github.com/fabiomassimo/gym

**Comment by JaviSoto** [comment]
I'm gonna go ahead and close this since now there's the awesome `gym`!
