### ISSUE TITLE
When building with ipa there is no xcarchive and the dsym file has a wrong name

### ISSUE THREAD

**Issue by rolandleth** [fastlane/fastlane#277]
```
xcclean
xcarchive(
  scheme: "Beta",
  archive_path: "build/Beta.xcarchive",
  output_style: :standard
)
xcexport
dsym_zip(
  archive_path: "build/Beta.xcarchive",
  dsym_path: "build/Beta.app.dSYM.zip"
)

resign(
  signing_identity: "iPhone Distribution: Roland leth (123456)",
  provisioning_profile: "fastlane/adhoc.mobileprovision"
)

hockey(
  api_token: "123456",
  notify: "1",
  ipa: "build/Beta.ipa",
  dsym: "build/Beta.app.dSYM.zip",
  tags: "alpha"
)
```
Properly works: .ipa, .xcarchive and dsym.zip are all present, named properly.

```
ipa(
  configuration: "Beta",
  scheme: "Beta",
  ipa: "Beta.ipa",
  destination: "build",
  clean: true,
  archive: true
)

resign(
  signing_identity: "iPhone Distribution: Roland leth (123456)",
  provisioning_profile: "fastlane/adhoc.mobileprovision"
)

hockey(
  api_token: "123456",
  notify: "1",
  ipa: "build/Beta.ipa",
  dsym: "build/Beta.app.dSYM.zip",
  tags: "alpha"
)
```
Does not work properly: there is no .xcarchive, the .ipa is named correctly, but the dsym.zip is named `MyAppName.app.dSYM.zip`. Then, of course, this error is raised: `Symbols on path 'project-path/build/Beta.app.dSYM.zip' not found`.

**Comment by KrauseFx** [comment]
How is the `dsym` wrongly named? It's working fine for me. What's not as expected?

And yes, the `ipa` action doesn't generate a `xcarchive`. The `ipa` action uses [shenzhen](https://github.com/nomad/shenzhen) to build and sign your app.

**Comment by rolandleth** [comment]
For me the `ipa` is named `Beta.ipa`, while my `dsym` is named `MyApp.app.dSYM.zip` and that error is taken from terminal - it appears it's trying to read the name I gave it, `Beta`.

**Comment by joshdholtz** [comment]
@rolandleth What is the `Product Name` in your build settings? Is that set to "MyApp"?

**Comment by joshdholtz** [comment]
@rolandleth @KrauseFx I actually ran into this myself last night. I thought I was doing something stupid but maybe this is something that a newer version of Xcode caused?

**Comment by rolandleth** [comment]
Yes, it is. I didn't name them beta/debug/etc. But still, I name it beta inside the dsym command 😔

**Comment by joshdholtz** [comment]
@rolandleth Can you drop a sample of what your dsym command looks like? I can take a look at this today (as I know I can duplicate the issue) and see if I can get a fix in for you? :wink:

**Comment by KrauseFx** [comment]
Thanks @joshdholtz for fixing this :+1: :rocket:

**Comment by joshdholtz** [comment]
@KrauseFx I haven't fixed it yet :wink: But I think I should be able to fix this :stuck_out_tongue_winking_eye:

**Comment by joshdholtz** [comment]
So much wink today I guess - I got some good sleep :zzz: :rocket:

**Comment by rolandleth** [comment]
Hmm, doesn't the ipa command create the dsym? :S

**Comment by joshdholtz** [comment]
It does 😊 I was using the IPA command myself but there is also a dsym command so wasn't sure if you were also using that. I am on this!

**Comment by rolandleth** [comment]
Awesome! 

While we're on this, I did manage to finish the process with xc commands, the build ended up on hockey, it said it's built with the proper identity/profile, but no one can download it. Any idea what's happening?

**Comment by JaviSoto** [comment]
Hi @rolandleth! Are you still running into these issues? You've probably seen the new `gym`, are you using that one now? :)

**Comment by rolandleth** [comment]
Hey, yes I'm using gym and don't have any problems with it 😁 Sorry for not updating 😞

**Comment by KrauseFx** [comment]
No problem, thanks for the response @rolandleth :+1:
