### ISSUE TITLE
Upload to play store triggers google api error UploadException TOS_NOT_ACCEPTED

### ISSUE THREAD

**Issue by blackholegalaxy** [fastlane/fastlane#29185]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After having setup our app in Google Play Console and Google Cloud Developper console (Play API activation, service account creation, JSON key obtained), the JSON key successfuly pass `fastlane run validate_play_store_json_key`.

We followed the documentation on fastlane to setup our service account and Play Console. Brand new project.

We published manually a first version of our app to Internal testing channel. So we get rid of "unknown application" error. It got reviewed and accepted.

But now we face, when sending app to playstore internal sharing a **TOS_NOT_ACCEPTED** error when trying to upload through fastlane.
```
Google Api Error: Invalid request - UploadException: TOS_NOT_ACCEPTED [[]] (com.example.app)
```

Please not we were NEVER able to do anything about publishing in fastlane for google play. iOs works like a charm.

**Has the service account, when added to a Play Store Console account, to receive an actual email and approve terms and services?? If yes it seems impossible since service account is somehow... not real email address we can access **

##### Command executed
```
upload_to_play_store_internal_app_sharing(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
```

- Our AAB is signed properly (we use flutter) with our keystore.
- When puting aab manually on play store it works
- the google service account is a valid service account with all privileges linked to the project owner
- projet Play Service API  is activated but 100% error rate for uploads

<img width="1105" alt="Screenshot 2024-12-27 at 4 00 15 PM" src="https://github.com/user-attachments/assets/d12d9a5e-51b5-45f6-a51c-078eb7a044e8" />

Service account as access as "owner" for project (we set this to ensure it's not a permission problem). We also tried a brand new service account like stated in the doc.

<img width="774" alt="Screenshot 2024-12-27 at 4 01 31 PM" src="https://github.com/user-attachments/assets/41e90c01-4b0c-40e8-9556-5587a8c9dfd6" />

- Service account is added properly in our Play Console.

<img width="871" alt="Screenshot 2024-12-27 at 4 05 15 PM" src="https://github.com/user-attachments/assets/6cb8dc2a-509d-4a3a-97c5-23cc790c0b88" />

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
bundle exec fastlane beta
[✔] 🚀 
[16:07:57]: -----------------------------
[16:07:57]: --- Step: update_fastlane ---
[16:07:57]: -----------------------------
[16:07:57]: Looking for updates for fastlane...
[16:08:08]: Nothing to update ✅
[16:08:08]: ---------------------------
[16:08:08]: --- Step: opt_out_usage ---
[16:08:08]: ---------------------------
[16:08:08]: Disabled upload of used actions
[16:08:08]: ------------------------------
[16:08:08]: --- Step: default_platform ---
[16:08:08]: ------------------------------
[16:08:08]: Driving the lane 'android beta' 🚀
[16:08:08]: -------------------------------------------------------
[16:08:08]: --- Step: upload_to_play_store_internal_app_sharing ---
[16:08:08]: -------------------------------------------------------
+---------------------------------+
|          Lane Context           |
+------------------+--------------+
| DEFAULT_PLATFORM | android      |
| PLATFORM_NAME    | android      |
| LANE_NAME        | android beta |
+------------------+--------------+
[16:08:29]: Called from Fastfile at line 14
[16:08:29]: ```
[16:08:29]:     12:       desc "Deploy internal beta android app on play store"
[16:08:29]:     13:       lane :beta do
[16:08:29]:  => 14:         upload_to_play_store_internal_app_sharing(
[16:08:29]:     15:           aab: '../build/app/outputs/bundle/release/app-release.aab',
[16:08:29]:     16:         )
[16:08:29]: ```
[16:08:29]: Google Api Error: Invalid request - UploadException: TOS_NOT_ACCEPTED [[]] (com.example.app)

+----------------------------------------------------------------+
|                        fastlane summary                        |
+------+-------------------------------------------+-------------+
| Step | Action                                    | Time (in s) |
+------+-------------------------------------------+-------------+
| 1    | update_fastlane                           | 11          |
| 2    | opt_out_usage                             | 0           |
| 3    | default_platform                          | 0           |
| 💥   | upload_to_play_store_internal_app_sharing | 21          |
+------+-------------------------------------------+-------------+

[16:08:29]: fastlane finished with errors

[!] Google Api Error: Invalid request - UploadException: TOS_NOT_ACCEPTED [[]] (com.example.app)
</pre>
</details>

### Environment

<details>
  <pre><details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                 |
| --------------------------- | --------------------------------------------------------------------- |
| OS                          | 15.2                                                                  |
| Ruby                        | 3.3.6                                                                 |
| Bundler?                    | true                                                                  |
| Git                         | git version 2.39.5 (Apple Git-154)                                    |
| Installation Source         | ~/dev/my-app/android/vendor/ruby/3.3.0/bin/fastlane |
| Host                        | macOS 15.2 (24C101)                                                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/3.3.6/lib                                      |
| OpenSSL Version             | OpenSSL 3.4.0 22 Oct 2024                                             |
| Is contained                | false                                                                 |
| Is homebrew                 | false                                                                 |
| Is installed via Fabric.app | false                                                                 |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                           |
| Xcode Version               | 16.2                                                                  |
| Swift Version               | 6.0.3                                                                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane
opt_out_usage

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy internal beta android app on play store"
  lane :beta do
    upload_to_play_store_internal_app_sharing(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :crashlytics do
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "fastlane/keys/google-service-account.json"
package_name("com.example.app")

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.226.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.7.0        |
| did_you_mean                    | 2.0.0        |
| syntax_suggest                  | 2.0.2        |
| bundler                         | 2.6.1        |
| pathname                        | 0.4.0        |
| rake                            | 13.2.1       |
| base64                          | 0.2.0        |
| nkf                             | 0.2.0        |
| rexml                           | 3.4.0        |
| CFPropertyList                  | 3.0.7        |
| public_suffix                   | 6.0.1        |
| addressable                     | 2.8.7        |
| artifactory                     | 3.0.17       |
| atomos                          | 0.1.3        |
| aws-eventstream                 | 1.3.0        |
| aws-partitions                  | 1.1028.0     |
| aws-sigv4                       | 1.10.1       |
| jmespath                        | 1.6.2        |
| aws-sdk-core                    | 3.214.0      |
| aws-sdk-kms                     | 1.96.0       |
| aws-sdk-s3                      | 1.176.1      |
| babosa                          | 1.0.4        |
| claide                          | 1.1.0        |
| colored                         | 1.2          |
| colored2                        | 3.1.2        |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| declarative                     | 0.0.20       |
| digest-crc                      | 0.6.5        |
| domain_name                     | 0.6.20240107 |
| dotenv                          | 2.8.1        |
| emoji_regex                     | 3.2.3        |
| excon                           | 0.112.0      |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| multipart-post                  | 2.4.1        |
| faraday-multipart               | 1.1.0        |
| faraday-net_http                | 1.0.2        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.4       |
| http-cookie                     | 1.0.8        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.1        |
| fastimage                       | 2.3.1        |
| sysrandom                       | 1.0.5        |
| fastlane-sirp                   | 1.0.0        |
| gh_inspector                    | 1.1.3        |
| jwt                             | 2.9.3        |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.19.0       |
| googleauth                      | 1.8.1        |
| httpclient                      | 2.8.3        |
| mini_mime                       | 1.1.5        |
| trailblazer-option              | 0.1.2        |
| uber                            | 0.1.0        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| google-apis-core                | 0.11.3       |
| google-apis-androidpublisher_v3 | 0.54.0       |
| google-apis-playcustomapp_v1    | 0.13.0       |
| google-cloud-env                | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.17.0       |
| google-apis-storage_v1          | 0.31.0       |
| google-cloud-errors             | 1.4.0        |
| google-cloud-core               | 1.7.1        |
| google-cloud-storage            | 1.47.0       |
| json                            | 2.9.1        |
| mini_magick                     | 4.13.2       |
| naturally                       | 2.2.1        |
| optparse                        | 0.6.0        |
| plist                           | 3.7.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.5        |
| simctl                          | 1.6.10       |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 2.6.0        |
| terminal-table                  | 3.0.2        |
| tty-screen                      | 0.8.2        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| word_wrap                       | 1.0.0        |
| nanaimo                         | 0.4.0        |
| xcodeproj                       | 1.27.0       |
| rouge                           | 3.28.0       |
| xcpretty                        | 0.4.0        |
| xcpretty-travis-formatter       | 1.0.1        |
</details>

*generated on:* **2024-12-27**
</details> </pre>
</details>

**Comment by blackholegalaxy** [comment]
For reference, this was solved after a call to a Google Expert. I will do a PR to adapt documentation.

To accept internal sharing TOS, you must go to Play Console > select your app > Test and Publish > Tests > Internal App Sharing

Here you will have to accept TOS and select a diffusion list.

**Comment by arbyruns** [comment]
Thanks @blackholegalaxy!
