### ISSUE TITLE
[Feature] Action for creating a new Release on GitHub

### ISSUE THREAD

**Issue by czechboy0** [fastlane/fastlane#292]
For people distributing apps just through GitHub releases, it would be nice to have a way to grab the .app, create a new release on GitHub with title, description, tag and upload the asset. [GitHub API docs for releases](https://developer.github.com/v3/repos/releases/#create-a-release).

(I might tackle this myself, but I thought it's still worth keeping in here in case someone else is having the same thoughts.)

**Comment by KrauseFx** [comment]
@czechboy0 thanks for your feedback. Yes, this would be really cool, agreed :+1: 

Right now, you can already create tags and push them to GitHub, so only the text needs to be set on GitHub.com.

**Comment by czechboy0** [comment]
Yeah the release metadata and asset uploading.

**Comment by JaviSoto** [comment]
Closing this since this is now possible :D
Thanks @czechboy0!
