### ISSUE TITLE
commit_version_bump problem with the .plist paths

### ISSUE THREAD

**Issue by dallasjohnson** [fastlane/fastlane#301]
When running the commit_version_bump command the check on the current Git status appears to be working and the expected file(s) are updated with the expected version details but the expected changed file paths don't match actual changed paths which appears to be due to the path expansion around $(PROJECT_DIR). I'm not sure how to fix this in the fastlane files or if it's something wrong with by Xcode Project.

Otherwise I'm very impressed with Fastlane.

```ruby
desc "Release a new beta version on Hockey"
  desc "This action does the following:"
  desc ""
  desc "- Ensures a clean git status"
  desc "- Increment the build number"
  desc "- Build and sign the app"
  desc "- Upload the ipa file to hockey"
  desc "- Post a message to slack containing the download link"
  desc "- Commit and push the version bump"
  lane :deployHockey do 
  # Make sure we start off with a clean slate   
  ensure_git_status_clean

  increment_build_number

 # Set version number to the one at the top of the CHANGELOG
  readme = File.read("../docs/CHANGELOG.md")
  latest_version = readme.split("\n## ").first
  first_line = latest_version.split("\n").first
  version_number = first_line.split(" ")[1]

  build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]

  increment_version_number version_number: version_number
  puts "The Version after increment  is #{version_number} Build: #{build_number}"

  # Generate release notes from CHANGELOG
  release_notes = latest_version.split("\n")[1..-1].join("\n")

  # Build
  ipa(
    configuration: "Debug",
    destination: "./fastlane/builds",
    scheme: "Bookatable - TestFlight Debug (Code Signed)",
    embed: "./fastlane/profiles/Distribution_com.bookatable.apps.iphonebookings.debug.mobileprovision",
    identity: "xxx",
    clean: false,
    )

  version_number = Actions.lane_context[Actions::SharedValues::VERSION_NUMBER]
    puts "The NEWVersion is #{version_number} Build: #{build_number}"
  # Push to Hockey
  hockey(
    api_token: ENV['HOCKEY_API_TOKEN'],
    # notes_type: markdown_type,
    notes: release_notes,
    )
  
  # Make sure our directory is clean, except for changes Fastlane has made
  # clean_build_artifacts
  puts "finished with the hockey output"

  # Tag release and push to Git

  puts "before testing"
  commit_version_bump( {xcodeproj: "Bookatable.xcodeproj", message: "Deploying version #{version_number}.",force: true
})
  puts "after testingf"
  add_git_tag tag: version_number
  push_to_git_remote
end
```

**Comment by KrauseFx** [comment]
Sorry it's hard to tell out of the top of my head. The source code of `commit_version_bump` is available [here](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/commit_version_bump.rb).

Maybe @lmirosevic has an idea? Was this introduced by my recent change? 

@dallasjohnson did it work before for you or is it the first time you tried it?

**Comment by lmirosevic** [comment]
@dallasjohnson To add to Felix's question, could please also paste the output of the fastlane run to see what exactly the action says?

**Comment by dallasjohnson** [comment]
This is my first use so I can't isolate it to a recent change. I've had a bit of a look at the source but nothing is obvious to me that might fix this problem. 

Sorry, I forgot to include this before but I suspect it has to do with substituting Xcode Variables (eg $(PROJECT_DIR))  into the Paths. I'm not experienced enough with Ruby to track down the problem here. I thought it maybe around line 43: ` info_plist_files = project.objects.select { |object| object.isa == 'XCBuildConfiguration' }.map(&:to_hash).map { |object_hash| object_hash['buildSettings'] }.select { |build_settings| build_settings.key?('INFOPLIST_FILE') }.map { |build_settings| build_settings['INFOPLIST_FILE'] }.uniq.map { |info_plist_path| Pathname.new(File.expand_path(File.join(xcodeproj_path, '..', info_plist_path))).relative_path_from(repo_pathname).to_s }
`


Here is the Fastlane output:

``` {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>nil, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deployHockey", :GIT_REPO_WAS_CLEAN_ON_START=>true, :BUILD_NUMBER=>23, :VERSION_NUMBER=>"4.0.0", :IPA_OUTPUT_PATH=>"/Users/dallasjohnson/Documents/Repos/mobile/BAT_App_v4/fastlane/builds/Development.ipa", :DSYM_OUTPUT_PATH=>"/Users/dallasjohnson/Documents/Repos/mobile/BAT_App_v4/fastlane/builds/Development.app.dSYM.zip", :HOCKEY_DOWNLOAD_LINK=>"https://rink.hockeyapp.net/apps/b30b23a87fff423f65d4efe76df92d16", :HOCKEY_BUILD_INFORMATION=>{"title"=>"Bookatable - Development", "bundle_identifier"=>"com.bookatable.apps.iphonebookings.debug", "public_identifier"=>"b30b23a87fff423f65d4efe76df92d16", "platform"=>"iOS", "release_type"=>0, "custom_release_type"=>"", "created_at"=>"2014-10-29T12:51:27Z", "updated_at"=>"2015-05-20T11:07:52Z", "featured"=>false, "role"=>0, "id"=>115021, "config_url"=>"https://rink.hockeyapp.net/manage/apps/115021/app_versions/212", "public_url"=>"https://rink.hockeyapp.net/apps/b30b23a87fff423f65d4efe76df92d16", "minimum_os_version"=>"8.3", "device_family"=>"iPhone/iPod", "status"=>2, "visibility"=>"private", "owner"=>"Bookatable", "owner_token"=>"3ef92625ef765a1395fae47aef0a6951ab7cb028", "company"=>"Bookatable"}}
[12:07:56]: Exit status of command 'git add /Users/dallasjohnson/Documents/Repos/mobile/BAT_App_v4/Bookatable.xcodeproj/project.pbxproj /Users/dallasjohnson/Documents/Repos/mobile/BAT_App_v4/\$\(PROJECT_DIR\)/Bookatable/Bookatable-Info.plist /Users/dallasjohnson/Documents/Repos/mobile/BAT_App_v4/BookatableTests/BookatableTests-Info.plist' was 32768 instead of 0. 
fatal: pathspec '/Users/dallasjohnson/Documents/Repos/mobile/BAT_App_v4/$(PROJECT_DIR)/Bookatable/Bookatable-Info.plist' did not match any files```

**Comment by lmirosevic** [comment]
It seems that one of your targets has a project configuration option for the plist path which references the `project_dir` env variable, which is not available outside of the xcodebuild build process. The obvious fix would be to go to your target's `build settings` in Xcode and find the `INFOPLIST_FILE` key (or "Info.plist file") and set a relative path to the plist like `myProject/Info.plist`.

**Comment by JaviSoto** [comment]
Is this still an issue @dallasjohnson? :)

**Comment by zwang** [comment]
@lmirosevic 's solution fixed my issue. I had one target's file in a group that not matching the actual folder structure, and it is referencing the `$(PROJECT_DIR)` env variable. After I fix the path issue and double checked the `$(PROJECT_DIR)` is no longer referenced, `commit_version_bump` works well for me again. 

Thanks @lmirosevic

**Comment by JaviSoto** [comment]
Awesome! Thanks for the detailed description. I'm sure it will be useful to somebody in the future :) 👍
