### ISSUE TITLE
HipChat Action URI

### ISSUE THREAD

**Issue by parkej60** [fastlane/fastlane#302]
The Hipchat Action doesn't format the channel into a valid URI. For instance if you had a room name with spaces in it you need to set 'Room%20Name' as the channel instead of 'Room Name'.

**Comment by KrauseFx** [comment]
I'm not using the Hipchat action myself, you can take a look at the source file [here](https://github.com/KrauseFx/fastlane/blob/master/lib/fastlane/actions/hipchat.rb). If you have some time a know a little Ruby, I'd happily merge a pull request fixing this behaviour.

**Comment by ohwutup** [comment]
Hey @parkej60, I am going to close the issue as it's been inactive for a while. Please feel free to continue discussion and/or reopen if necessary! :octopus:
