### ISSUE TITLE
Using Fastlane with Xamarin

### ISSUE THREAD

**Issue by Darkreaper101** [fastlane/fastlane#314]
Hi there,

I want to know if there is anybody that has got fastlane to integrate and work with Xamarin.
It seems I cannot integrate my Xamarin project with fastlane.

If there is maybe someone that wants to code a Xamarin Build action. That would be awesome. :D

Regards

**Comment by KrauseFx** [comment]
I don't use Xamarin myself, but `snapshot` already supports Xamarin: https://github.com/KrauseFx/snapshot#xamarin
Maybe you can port it to be a `fastlane` action?

**Comment by Darkreaper101** [comment]
I will try my best, but my ruby isn't really up to standard. I'm actually a .NET developer.

**Comment by pkl728** [comment]
I'm using it as is in my Team City CI server to deploy our Xamarin iOS application.  What do you need help with?  What have you tried?

**Comment by JaviSoto** [comment]
I'm closing this issue for now since it's been inactive for a while. If you guys still want to chat about Xamarin support, feel free to reply and we'll reopen it!

**Comment by voydz** [comment]
@JaviSoto Hey, we are also working with a plain Xamarin stack. Previously using a custom Rake build to streamline our basic CI stuff (beta testing and so on), we are desperately looking for a tool like fastlane. 

We would really appreciate further consideration on this topic. For now I will peak through fastlane's source and see how this may be done, tinkering around myself.

**Comment by TKBurner** [comment]
@voydz Thanks for following up. We are aware of Xamarin support as a feature request. However, any steps you'd normally take care of in Xcode should still work on your Xamarin app. Thanks!

**Comment by voydz** [comment]
@TKBurner @JaviSoto Hi, I just want to give a short status feedback. 

I wrote myself a gem which abstracts the whole msbuild/xbuild project intelligence and compile stuff. (Designed like `gym` or the `gradle` action respectively.) 

Hooking everything into the `lane_context` I noticed that those implementation and much of its functionality are tied close to `fastlane` itself. This makes some deeper integration kinda rough. But as Android support seems to be in its early stages, I am ok with this. Who knows if there will be further thoughts put into a more flexible plugin system? 😉 

All in all it seems quite simple to get basic things up and running. I migrated a former Rake-based build for an Android and iOS app (containing building, feature testing with Calabash, submitting to xamarin test-cloud, deployment to HockeyApp) to fastlane in 2 days, **and I am very happy with `fastlane` already**.

Keep up the good work guys!

**Comment by TKBurner** [comment]
@voydz Thanks for the note. Without going into too much detail yet, I think you are going to be really happy with what we turn out over the next few months. Thanks!

**Comment by voydz** [comment]
Just for reference, I decided to make my little build helper open source, maybe it can actually help someone else. You'll find it here: https://github.com/voydz/souyuz

Greetings

**Comment by TKBurner** [comment]
@voydz Awesome! Really glad to see this. Have you thought about adding it to our new extensions system? Thanks 👍

**Comment by voydz** [comment]
@TKBurner I will definitely take a look into this as soon as I can. 😉

**Comment by ghuntley** [comment]
Reference for others whom may stumble upon this GitHub issue.

Snapshot _used_ to work with Xamarin projects but no longer does. 

https://twitter.com/KrauseFx/status/585869719875395584
