### ISSUE TITLE
Is it possible to completely disable color output?

### ISSUE THREAD

**Issue by keatongreve** [fastlane/fastlane#316]
I've been messing with it and it seems like it all depends on the tools you use. For example, in order to remove color output from `ipa`, I had to make a custom patch here: (https://github.com/keatongreve/fastlane/commit/1ac86703c24a1f56c9b6a017e902d308e6fc8394)

It changed my build output slightly, the `>` symbols indicate that the output of `ipa` is no longer styled, but the fastlane output still has color codes at the beginning. Here's a sample of output from TeamCity:
```
[20:17:57] [37m[15:17:57]:  [0m [32m----------------- [0m
[20:17:57] [37m[15:17:57]:  [0m [32m---  [0m [32mStep: ipa [0m [32m --- [0m
[20:17:57] [37m[15:17:57]:  [0m [32m----------------- [0m
[20:17:57] [37m[15:17:57]:  [0m[SHELL COMMAND]:  [33mset -o pipefail && krausefx-ipa build -w "MyApp.xcworkspace" -s "Scheme" -c "Adhoc" --verbose | xcpretty --no-utf [0m
[20:18:24] [37m[15:18:10]:  [0m[SHELL]: > Cleaning Pods/Pods-CocoaAsyncSocket [Test]
[20:18:24] [37m[15:18:10]:  [0m[SHELL]: > Cleaning Pods/Pods-Appsee [Test]
[20:18:24] [37m[15:18:10]:  [0m[SHELL]: > Cleaning Pods/Pods-CocoaLumberjack [Test]
[20:18:24] [37m[15:18:10]:  [0m[SHELL]: > Cleaning Pods/Pods-AFNetworking [Test]
[20:18:24] [37m[15:18:10]:  [0m[SHELL]: > Cleaning Pods/Pods-FLKAutoLayout [Test]
[20:18:24] [37m[15:18:10]:  [0m[SHELL]: > Cleaning Pods/Pods-DDURLParser [Test]
[20:18:24] [37m[15:18:10]:  [0m[SHELL]: > Cleaning Pods/Pods-Block-KVO [Test]
```

I love the color feature otherwise, unfortunately I'm stuck with TeamCity which doesn't support it.

**Comment by KrauseFx** [comment]
Isn't there a plugin for TeamCity that enables the standard terminal colours? I don't think it's easily possible to get rid of colours in `fastlane`. How do you solve that in CocoaPods?

**Comment by keatongreve** [comment]
1. I did a bit of searching and I couldn't find anything. If you've found something I would appreciate a link!
2. I agree, the only way I could think of is writing wrapper methods around `red`/`yellow`/etc. Or piping all final output through `sed`.
3. Good point, I didn't think about one like CocoaPods since I don't run it in my lanes. We can't control the output of every action. I got lucky that the `xcpretty` call in the `ipa` action was added in `fastlane` instead of in `shenzhen` itself. I guess you could starting forking everything :stuck_out_tongue_closed_eyes:. `sed` is starting to sound like a better option.

You can close this if you want, I just wanted to share my thoughts. Thanks for the response!

**Comment by KrauseFx** [comment]
To be honest, I don't think it's a huge problem to have a `[0m` in front of every line. But you're right, monkey patching the colour methods would probably be the way to go.

**Comment by jeanregisser** [comment]
CocoaPods has `--no-ansi` option.
In that cases they indeed just monkey patch `String.colorize`.
See https://github.com/CocoaPods/CocoaPods/blob/84e84ad5159a618af4e9f253d56f99b1469300a3/lib/cocoapods/command.rb#L82-L84

**Comment by jeanregisser** [comment]
@KrauseFx how would you like this feature to work?
A `--no-ansi` option to the `fastlane` command? Or a directive in the Fastfile?
I'd be happy to send a PR with what you prefer.

**Comment by jeanregisser** [comment]
@keatongreve I'm also using TeamCity and was having the same issue.
Until there's a builtin way to disable colors, you can simply add this `String.send(:define_method, :colorize) { |string, _| string }` to the top of your Fastfile.

**Comment by keatongreve** [comment]
@jeanregisser Perfect. :+1:

**Comment by KrauseFx** [comment]
@jeanregisser I'd have to further look into it, but probably adding an option to `/bin/fastlane` should do the job.

**Comment by jeanregisser** [comment]
FYI, TeamCity 9.1 now supports ansi colors! https://confluence.jetbrains.com/display/TCD9/Build+Log#BuildLog-ANSIstyleColoringinBuildLog

**Comment by jaylyerly** [comment]
Just for the record, using Xcode & Xcode Server, colorized output seems to be a problem.  Viewing the log files from the build server through Xcode causes Xcode to hang.  Also, downloading the log files and viewing them in Finder, the QuickLook preview hangs Finder as well.  In this instance, I'm calling sigh from some python scripts.  (They python scripts handle the integration with Xcode Server.)  If I strip all the colorizing characters from sigh's output in python and then send the text to stdout, all of these problems go away.  

So, looks like Xcode, Xcode Server, and Finder have weird issues.  I've got a workaround for now, but a flag to disable that would be great. 

Xcode 7.0.1, Xcode Server (OSX Server 5.0.4), El Capitan (OSX 10.11.0)

**Comment by armadsen** [comment]
:+1: 

I'd also like to disable xcpretty altogether (maybe that's already possible?).

**Comment by xfreebird** [comment]
@armadsen right now that is not possible. But there is MR #626 that can do that. If it is merged, that will be possible to do.

**Comment by jcampbell05** [comment]
@KrauseFx  I think has just added both of these features.

**Comment by KrauseFx** [comment]
Yeah, this will be possible with the new `UI` abstraction layer, which will be rolled out over the next few weeks to all tools. Right now it's already used in [match](https://github.com/fastlane/match)

All you have to do is set the `FASTLANE_DISABLE_COLORS` environment variable :rocket:

**Comment by KrauseFx** [comment]
This now works across all tools. Make sure to install the latest version of `fastlane` and set the environment variable using 

```
export FASTLANE_DISABLE_COLORS=1
```

**Comment by tomassliz** [comment]
@KrauseFx The environment variable does not work. I have Fastlane version 1.48.0 and output is still colorized. Where exactly should I put this variable please?

**Comment by KrauseFx** [comment]
@tomassliz This will be updated to all tools over the next weeks :+1:

**Comment by tomassliz** [comment]
@KrauseFx Amazing 👍 It will be nice for feature release notes mention this behaviour, but anyway thank you for amazing commitment!

**Comment by KrauseFx** [comment]
@tomassliz You mean something like here? https://github.com/fastlane/fastlane/releases/tag/1.48.0

**Comment by tomassliz** [comment]
Yes. I was blind, sorry for my stupid note...

**Comment by KrauseFx** [comment]
For people coming from Google, use the `FASTLANE_DISABLE_COLORS` ENV variable 👍
