### ISSUE TITLE
commit_version_bump expecting changes to "."

### ISSUE THREAD

**Issue by Spencevail** [fastlane/fastlane#321]
I'm getting this error while running `commit_version_bump`:

>Found unexpected uncommited changes in the working directory. Expected these files to have changed: ["Inspirato.xcodeproj/project.pbxproj", "Inspirato/Info.plist", "InspiratoTests/Info.plist", "."]. But found these actual changes: ["Inspirato.xcodeproj/project.pbxproj", "Inspirato/Info.plist", "InspiratoTests/Info.plist"]. Make sure you have cleaned up the build artifacts and are only left with the changed version files at this stage in your lane, and don't touch the working directory while your lane is running. You can also use the :force option to bypass this check, and always commit a version bump regardless of the state of the working directory.

My `git status` is:
```shell
On branch feature/AIR-2055-configure_fastlane
Your branch is ahead of 'origin/feature/AIR-2055-configure_fastlane' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   Project.xcodeproj/project.pbxproj
	modified:   Project/Info.plist
	modified:   ProjectTests/Info.plist

no changes added to commit (use "git add" and/or "git commit -a")
```

I'm a bit confused how `"."` would be one of the expected changes? Any advice on this one?

**Comment by lmirosevic** [comment]
The script looks inside your project configuration to find possible places where a version number might be stored. There are 2 places it looks: a) the project.pbxproj file and b) any Info.plist files.

I would check your project configuration to make sure that there aren't any targets which have a `Info.plist File` (in Xcode) value set to `.` Alternatively you can open the .pbxproj file with your favourite text editor and search for `INFOPLIST_FILE`.

**Comment by kevboh** [comment]
Seeing the same thing:

```
Found unexpected uncommited changes in the working directory. Expected these files to have 
changed: 
MyProject.xcodeproj/project.pbxproj
MyProject/Info.plist
MyProjectKit/Info.plist
MyProjectShare/Info.plist
MyProjectTests/Info.plist
MyProjectKitTests/Info.plist.
But found these actual changes: 
MyProject.xcodeproj/project.pbxproj
MyProject/Info.plist
MyProjectKit/Info.plist
MyProjectKitTests/Info.plist
MyProjectShare/Info.plist
MyProjectTests/Info.plist
.
```

The `pbxproj` and `plist` files are correct. If I run `git diff --name-only HEAD` I get:

```
MyProject.xcodeproj/project.pbxproj
MyProject/Info.plist
MyProjectKit/Info.plist
MyProjectKitTests/Info.plist
MyProjectShare/Info.plist
MyProjectTests/Info.plist
```

And `git ls-files --other --exclude-standard` is empty, so I don't see where `.` is coming from.

**Comment by kevboh** [comment]
Wait... looking at the source, I think the `.` is just part of the error message. So I'm not sure where the difference is.

**Comment by JaviSoto** [comment]
Hi @kevboh, I'm going through some old issues. Is this still an issue for you? Let us know!

**Comment by kevboh** [comment]
Hey @JaviSoto—I no longer have access to the code where that was happening (changed jobs), so you should treat this as not reproing unless someone else chimes in.

**Comment by JaviSoto** [comment]
Thanks for the update 👍
