### ISSUE TITLE
Feature - MailGun should support smtp

### ISSUE THREAD

**Issue by thiagolioy** [fastlane/fastlane#356]
mailgun action should allow  sending mail using smtp . The api supports that behave . =)

**Comment by ohwutup** [comment]
Hey @thiagolioy! Great idea! I will share this with the team and see what we can do in a future release. I’ll reopen this ticket and keep you updated when we get a chance to revisit this, stay tuned :+1: If you want to tackle this yourself, check out the [countdown](https://github.com/fastlane/countdown) repo to learn how to contribute to `fastlane`. :rocket: :guitar:
