### ISSUE TITLE
fail fast when not specifying a team id

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#3604]
### Issue Description

As seen in #2012 and #1407 fastlane might not be able to find a certificate if the wrong team is selected. One issue is that it implicitly try to select the team. This is unreliable.

I recommend that the above code should https://github.com/fastlane/fastlane/blob/0.22.0/spaceship/lib/spaceship/portal/portal_client.rb#L71 should fail fast instead.

Or there should be a way to identify the proper team for a given certificate.

**Comment by KrauseFx** [comment]
Agree, we should fail as early as we can with a clear error message on what went wrong. However the link is broken?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (457/400 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:40998 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKsx-002lUL-Fz
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:25 +0200
Date: Sat, 18 Jun 2016 11:21:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274095;
	bh=OWQRSFBvlzIgC6Pk5ghkIDAFdXki0hlq4lsJa4fNHNc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1NS1mmuEy/yaduvv48s/sIQOfJkIENR7twEs5JveLYJos2ve9isrqIeEG+B3PSfP7
	 MkhFwafuqhK9xRG/2ncEnF1MH0XM/rPZCghAbnXGST05yzeldIcbc8YoVdgFg3ybQW
	 ZZK1jigAHsGyCEArLXGwZH3akG4r4Uv6j0vKXNoY=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (459/400 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:8544)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKt1-002lUn-9m
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:32 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=tRLd6/RdsY3jDNYMYEljUEhM1QU=; b=uR32dUbdhp5zLGR7
	PhQMYEizV06/xzFCSPHpS40cp5Z+2ldCpViXfvzeE3EuoBiB5S08yHN0R5Pgv3Pj
	rkI8ci8kvXMec09QvwDdJlM5x3+x/zaT97xhPu+vBCWXSJf2nj4CG69sJj5dxPXM
	nMRwHKS+azfGq89obIxHLiH83+0=
Received: by filter0905p1mdw1.sendgrid.net with SMTP id filter0905p1mdw1.6267.5765913622
        2016-06-18 18:21:42.271487076 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id kIr9rlqZRvS-cCC_rAuLXw
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:42.308 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:34 -0700
