### ISSUE TITLE
Feature request - Pilot - test latest build

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#3607]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [ Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It would be nice to have an option to submit the latest build to testflight.

e.g. 
1) Run deliver (upload metadata, upload build, create new version, etc - don't submit)
2) Run pilot (submit the most recent build to test-flight)
--after testing is succesfull--
3) Run deliver (don't upload anything, just submit)

that way, I know that the tested build is the one which is being submitted.

**Comment by pedro380085** [comment]
+1

**Comment by TKBurner** [comment]
Thanks for sending this over @ConfusedVorlon! The team here is going to look this over. Hope that you have a great week!

**Comment by negebauer** [comment]
It would be nice to have something like `deliver`s `skip_binary_upload`

**Comment by negebauer** [comment]
Looking at other issues this isn't the first time this is mentioned
(some related issues) #1922 #1905 #1887

**Comment by TKBurner** [comment]
@negebauer Thanks for +1-ing this. I'm going to mark it as help wanted in case anyone wants to submit a PR. 👍
