### ISSUE TITLE
Is there a ENV Variable for ITC Password for pilot

### ISSUE THREAD

**Issue by dreyhomedev** [fastlane/fastlane#3619]
Hey,

I'm looking for an Env variable to tell pilot the password for ITC.
We building our lanes with Jenkins on a slave machine. In order to provide needed passwords for fastlane we inject the password with the appropriate Env variables in the Jenkins job.
Since we have different accounts for Apple dev center and ITC we also need to specify the password for ITC to upload the ipa file to Apple TestFlight.

Is pilot using a Variable of an other tool maybe?

Best
Andreas

**Comment by KrauseFx** [comment]
Sure, you can use `FASTLANE_PASSWORD` for all tools

**Comment by i2amsam** [comment]
:+1: does that answer your question @dreyhomedev ?

**Comment by dreyhomedev** [comment]
Hey,

we already using FASTLANE_PASSWORD in our jobs.
I'm litte bit confused right now. Is gym or match using this variable somehow for login in into the dev center? If not I just need to reset the password to the ITC account and I'm done.

If it does I'll need an other way to also inject the ITC-password wit an ENV variable

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (460/400 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:24414)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKt2-002lVL-6C
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:35 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=QOZF5pzFTuVkcs1ies7ES+x4h4Q=; b=MAkMdeX/dm+HyOol
	R4LR3MAPRKJ8Uqb2/DJvP/uGnaXGtK/uiQVLRHHNmEmKoY+Qr4bHd6fxKM1rFuUJ
	gq1YAonIR/TTbVOzY+2P6Iyo4p551/9ipkzxw1D/iboDvcPZ/6M5wKpsZHOiuJ5x
	KU7hsQKr0QTxUfRCgTciUwruPA8=
Received: by filter0825p1mdw1.sendgrid.net with SMTP id filter0825p1mdw1.9683.576591379
        2016-06-18 18:21:43.083520677 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id UZ7rW4NrSv6CCaKRm5cJMA
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:43.126 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:40 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (463/400 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:45609)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKt2-002lV8-LB
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:39 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=NKWat3yd+ou8+qp2C9kANsZjnWg=; b=JXlBRrUj4WCbwitI
	By13JYxg8bOg6MdJxJEoL9tlF6KuCUz8lnk27blFfz4o7RbfeW/2njALIT0rH+9C
	CMrgd3MH64C7OK2eykijgxeRcLe863HPVlHLRR3u24tBnQkwcskOWS95QfPTRoSA
	2bCxZbnZgH89eK02an+qBVPG2a0=
Received: by filter0420p1mdw1.sendgrid.net with SMTP id filter0420p1mdw1.4659.5765913641
        2016-06-18 18:21:42.882389035 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id Hri0mu5gTxuqKHNI5C2kaQ
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:42.845 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:40 -0700
