### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by ReadmeCritic** [fastlane/fastlane#3622]
Updated March 11, see below https://github.com/fastlane/fastlane/issues/3622#issuecomment-195503365 
---
Just reporting some broken links in docs (markdown files), part 2 of #3618 

Issues found with https://github.com/dkhamsing/frankenstein :sweat_smile:

**Comment by dkhamsing** [comment]
Verified today, checked have no 404s

- [x] cert/ManualSteps.md
- [x] cert/README.md
- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md
- [x] countdown/README.md
- [x] credentials_manager/README.md
- [x] deliver/Deliverfile.md
- [x] deliver/MigrationGuide.md
- [x] deliver/README.md
- [x] deliver/Reference.md
- [ ] fastlane/docs/Actions.md
- [x] fastlane/docs/Advanced.md
- [x] fastlane/docs/Android.md
- [x] fastlane/docs/Appfile.md
- [x] fastlane/docs/Bamboo.md
- [x] fastlane/docs/CodeSigning.md
- [x] fastlane/docs/FAQs.md
- [x] fastlane/docs/Gitignore.md
- [x] fastlane/docs/Guide.md
- [x] fastlane/docs/Jenkins.md
- [x] fastlane/docs/Platforms.md
- [x] fastlane/docs/README.md
- [ ] fastlane/fastlane/actions/README.md
- [ ] fastlane/fastlane/README.md
- [x] fastlane/ISSUE_TEMPLATE.md
- [x] fastlane/lib/fastlane/actions/README.md
- [x] fastlane/lib/fastlane/helper/README.md
- [x] fastlane/README.md
- [x] fastlane/spec/actions_md_spec.rb
- [x] fastlane_core/README.md
- [x] frameit/README.md
- [x] gym/examples/cocoapods/Pods/HexColors/README.md
- [x] gym/fastlane/README.md
- [x] gym/lib/assets/package_application_patches/PackageApplication_MD5
- [x] gym/lib/gym/generators/README.md
- [x] gym/lib/gym/xcodebuild_fixes/README.md
- [x] gym/README.md
- [x] ISSUE_TEMPLATE.md
- [x] match/lib/assets/READMETemplate.md
- [x] match/README.md
- [x] pem/README.md
- [x] pilot/README.md
- [x] produce/README.md
- [x] README.md
- [x] scan/fastlane/README.md
- [x] scan/README.md
- [x] screengrab/README.md
- [x] sigh/README.md
- [x] snapshot/lib/snapshot/fixes/README.md
- [x] snapshot/MigrationGuide.md
- [x] snapshot/README.md
- [ ] spaceship/docs/DeveloperPortal.md
- [x] spaceship/docs/iTunesConnect.md
- [x] spaceship/README.md
- [x] supply/README.md
- [x] watchbuild/README.md

Summary: these have broken links

- [ ] fastlane/docs/Actions.md

🔴  404 https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
🔴  404 https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
🔴  404 https://example.com/path/MyApp
🔴  404 https://example.com/display
🔴  404 https://example.com/fullSize
🔴  404 https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
🔴  404 https://example.com/your/zipped/app.zip
🔴  404 https://github.com/fastlane/fastlane/tree/master/PEM
🔴  404 http://example.com/path/to/thumb.png
🔴  404 https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/testmunk.rb
🔴  404 https://github.com/MyGithubPage/Specs

- [ ] fastlane/fastlane/actions/README.md

🔴  404 https://github.com/fastlane/fastlane/tree/master/docs
🔴  404 https://github.com/fastlane/fastlane/tree/master/lib
🔴  404 https://github.com/fastlane/fastlane/tree/master/lib/fastlane/actions

- [ ] fastlane/fastlane/README.md

🔴  404 https://github.com/fastlane/fastlane/tree/master/docs
🔴  404 https://github.com/fastlane/fastlane/tree/master/lib

- [ ] spaceship/docs/DeveloperPortal.md 

🔴  404 https://github.com/fastlane/spaceship/blob/master/lib/spaceship/portal/provisioning_profile.rb

**Comment by dkhamsing** [comment]
@KrauseFx :eyes:

**Comment by ReadmeCritic** [comment]
Verified today, checked have no 404s

- [x] cert/ManualSteps.md
- [x] cert/README.md
- [x] CODE_OF_CONDUCT.md
- [x] CONTRIBUTING.md
- [x] countdown/README.md
- [x] credentials_manager/README.md
- [x] deliver/Deliverfile.md
- [x] deliver/MigrationGuide.md
- [x] deliver/README.md
- [x] deliver/Reference.md
- [ ] fastlane/docs/Actions.md
- [x] fastlane/docs/Advanced.md
- [x] fastlane/docs/Android.md
- [x] fastlane/docs/Appfile.md
- [x] fastlane/docs/Bamboo.md
- [x] fastlane/docs/CodeSigning.md
- [x] fastlane/docs/FAQs.md
- [x] fastlane/docs/Gitignore.md
- [x] fastlane/docs/Guide.md
- [x] fastlane/docs/Jenkins.md
- [x] fastlane/docs/Platforms.md
- [x] fastlane/docs/README.md
- [ ] fastlane/fastlane/actions/README.md
- [ ] fastlane/fastlane/README.md
- [x] fastlane/ISSUE_TEMPLATE.md
- [x] fastlane/lib/fastlane/actions/README.md
- [x] fastlane/lib/fastlane/helper/README.md
- [x] fastlane/README.md
- [x] fastlane/spec/actions_md_spec.rb
- [x] fastlane_core/README.md
- [x] frameit/README.md
- [x] gym/examples/cocoapods/Pods/HexColors/README.md
- [x] gym/fastlane/README.md
- [x] gym/lib/assets/package_application_patches/PackageApplication_MD5
- [x] gym/lib/gym/generators/README.md
- [x] gym/lib/gym/xcodebuild_fixes/README.md
- [x] gym/README.md
- [x] ISSUE_TEMPLATE.md
- [x] match/lib/assets/READMETemplate.md
- [x] match/README.md
- [x] pem/README.md
- [x] pilot/README.md
- [x] produce/README.md
- [x] README.md
- [x] scan/fastlane/README.md
- [x] scan/README.md
- [x] screengrab/README.md
- [x] sigh/README.md
- [x] snapshot/lib/snapshot/fixes/README.md
- [x] snapshot/MigrationGuide.md
- [x] snapshot/README.md
- [ ] spaceship/docs/DeveloperPortal.md
- [x] spaceship/docs/iTunesConnect.md
- [x] spaceship/README.md
- [x] supply/README.md
- [x] watchbuild/README.md

Summary: these have broken links

- [ ] fastlane/docs/Actions.md

🔴  404 https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
🔴  404 https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
🔴  404 https://example.com/path/MyApp
🔴  404 https://example.com/display
🔴  404 https://example.com/fullSize
🔴  404 https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md
🔴  404 https://example.com/your/zipped/app.zip
🔴  404 https://github.com/fastlane/fastlane/tree/master/PEM
🔴  404 http://example.com/path/to/thumb.png
🔴  404 https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/testmunk.rb
🔴  404 https://github.com/MyGithubPage/Specs

- [ ] fastlane/fastlane/actions/README.md

🔴  404 https://github.com/fastlane/fastlane/tree/master/docs
🔴  404 https://github.com/fastlane/fastlane/tree/master/lib
🔴  404 https://github.com/fastlane/fastlane/tree/master/lib/fastlane/actions

- [ ] fastlane/fastlane/README.md

🔴  404 https://github.com/fastlane/fastlane/tree/master/docs
🔴  404 https://github.com/fastlane/fastlane/tree/master/lib

- [ ] spaceship/docs/DeveloperPortal.md 

🔴  404 https://github.com/fastlane/spaceship/blob/master/lib/spaceship/portal/provisioning_profile.rb

**Comment by ohwutup** [comment]
I believe a good number of these have been taken care of. Going to close this issue for now, but feel free to run the bot again!
