### ISSUE TITLE
Running spaceship from a server side script

### ISSUE THREAD

**Issue by sandorhadasdig** [fastlane/fastlane#3629]
Hello There,

I am not sure if that this is a Spaceship issue or not, and I would appreciate any idea on this one.
I have two scripts, a ruby script and a php script.
The ruby script looks about like:

    #!/usr/bin/env ruby
    $LOAD_PATH.push File.expand_path("spaceship/lib")
    require "spaceship"
    begin
        puts "DEBUG: This is printed"
        Spaceship.login(ARGV[0], ARGV[1])
        puts "DEBUG: This is not via http, nor an error message like errr"
        Spaceship.client.team_id = ARGV[2]
        puts Spaceship.device.find_by_udid(ARGV[3])
    rescue StandardError => errr
            print "Error running script: " + errr
    end

My php script looks something like below.

    require_once "rubyenvvars.php"
    $Result = shell_exec("ruby spacescript.rb user password team udid");
    printf("%s", $Result);

So, command line:

    $ php myscript.php

works fine from the bash, Spaceship does the login and prints Spaceship::Portal::Device .... nicely.

I figured that the apache requires ruby environment variables, so all environment variables are set in the "rubyenvvars.php" matching the bash "env" command (that makes ruby require "spaceship" successful). Working directory is the same too. Still, http://host/myscript.php returns an empty string, no error caught.

Is it a bug or I am doing something obviously wrong?

Thanks a lot. :)
Sandor

**Comment by sandorhadasdig** [comment]
Further investigation shows that this is the chain of execution:
lib/spaceship/client.rb : function login =>
lib/spaceship/client.rb : function send_login_request =>
lib/spaceship/portal/portal_client.rb

    response = request(:post, "https://idmsa.apple.com/IDMSWebAuth/authenticate", {

=>
lib/spaceship/client.rb : function request

And that "request" function is never actually called (even a print at the very beginning, just right after

    def request(method, url_or_path = nil, params = nil, headers = {}, &block)

does not run.  If I do it from the command line, it runs.

**Comment by jcampbell05** [comment]
Could you provide the environmental variables you use, that *may* help.

**Comment by sandorhadasdig** [comment]
These are all the environment variables (printed from php before shell_exec("ruby spacescript.rb"), printed by shell_exec("env"):

    LESSOPEN=|
    /usr/bin/lesspipe %s 
    SSH_CLIENT=10.232.60.50 49961 22
    _system_version=14.04
    SHLVL=1
    OLDPWD=/var/www/html/mypage
    SSH_TTY=/dev/pts/1
    APACHE_RUN_DIR=/var/run/apache2
    APACHE_PID_FILE=/var/run/apache2/apache2.pid
    rvm_bin_path=/usr/local/rvm/bin
    _=/usr/bin/env
    IRBRC=/usr/local/rvm/rubies/ruby-2.3.0/.irbrc
    RUBY_VERSION=ruby-2.3.0
    XDG_SESSION_ID=35
    TERM=xterm-256color
    PATH=/usr/local/rvm/gems/ruby-2.3.0/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/rvm/bin
    XDG_RUNTIME_DIR=/run/user/0
    APACHE_LOCK_DIR=/var/lock/apache2
    MY_RUBY_HOME=/usr/local/rvm/rubies/ruby-2.3.0
    LANG=en_US.UTF-8
    LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
    SHELL=/bin/bash
    APACHE_RUN_USER=www-data
    APACHE_RUN_GROUP=www-data
    rvm_prefix=/usr/local
    GEM_HOME=/usr/local/rvm/gems/ruby-2.3.0
    _system_type=Linux
    LESSCLOSE=/usr/bin/lesspipe %s %s
    APACHE_LOG_DIR=/var/log/apache2
    rvm_version=1.26.11 (latest)
    _system_arch=x86_64
    PWD=/var/www/html/mypage
    GEM_PATH=/usr/local/rvm/gems/ruby-2.3.0:/usr/local/rvm/gems/ruby-2.3.0@global
    _system_name=Ubuntu
    rvm_path=/usr/local/rvm

**Comment by sandorhadasdig** [comment]
What else I clearly see that logging is not helping here.  I set the log path to a path owned by www-data, however the first log line is produced after "request" is called, not before.  So, from the command line I get what is below, for browser call the file is not even there:

    [11:30:48]: >> POST: https://idmsa.apple.com/IDMSWebAuth/authenticate {appleId: example@example.com}, {appIdKey: AVERYLONGKEY}

**Comment by sandorhadasdig** [comment]
It looks the problem has been isolated.
It comes down to file lib/spaceship/portal/portal_client.rb

    def send_login_request(user, password)
        print " user: " + user
        print " password: " + password
        print " api_key: " + api_key

I added those prints. user and password are printed but the execution stops on print api_key.

So, what might be the reason why api_key is missing?  Is it stored somewhere in a file and might it need write access for www-data somewhere?

**Comment by sandorhadasdig** [comment]
Hard coded paths look to make it fail like:

    ./lib/spaceship/portal/portal_client.rb:13:      cache_path = File.expand_path("~/Library/Caches/spaceship_api_key.txt")
    ./spec/portal/portal_client_spec.rb:10:    let(:path) { File.expand_path("~/Library/Caches/spaceship_api_key.txt") }
    ./spec/spec_helper.rb:38:  File.expand_path("~/Library/Caches/spaceship_api_key.txt"),

It means that if you run by a user which has no access to directory ~/Library/Caches then it fails.
There is no rescue in the ruby script to enclose expand_path so it fails silently.

I suggest a fix where:
1) begin - rescue - end is around the File.expand_path, so in case of this kind of error a proper error message is printed
2) Location of the "api_key" is configurable

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (458/400 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:42218 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKt0-002lVQ-Vd
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:31 +0200
Date: Sat, 18 Jun 2016 11:21:45 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274105;
	bh=liL6pWDtHmUrUT2Y95g2drq7JV2bub2jvugsU/RAB7c=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=oSMmyYA6zkLR05/ZjpC156zVkH2zNaVuHikExX7tRyusqy18RYk1RFHX0BMbDxt9p
	 w01B7xGu4p5TaQmAHqVokGvMADq3rXWuxkTAJAzKIKEGjfaRH4fEvyI7Nz2lWqM8IM
	 RtJRzXuJS1o1lvetIGMKjGaYMtSgIP55Mh0W7MEQ=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (461/400 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:10121)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKt4-002lVj-MR
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:36 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=sTBVj/d8KjBt3QMtC1+dQGxtlOI=; b=UyKw40LrXOJcFB5s
	HSi/HojmZ1HhdkbhqbcmN0a/KzLh3JRMbiQIebc+CnEmJTwNOyqWxN0aruhSZscr
	4PMnWKbylhvUHLswEC2BRFGkcgP3HYgEea0vBPXadIMSrAtPd3JVFeAwPHdl6r4T
	cA6Xet+OJ6qyz56d7IyVXnNCuPA=
Received: by filter0837p1mdw1.sendgrid.net with SMTP id filter0837p1mdw1.7366.5765913A7
        2016-06-18 18:21:46.183659547 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id O0tO8wweTG6NMr68YyFHjw
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:46.292 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:46 -0700
