### ISSUE TITLE
gym/scan xcodebuild log

### ISSUE THREAD

**Issue by joshuafinch** [fastlane/fastlane#3630]
Hi there,

I'm using Jenkins and fastlane tools for our CI setup.

As a part of that, we'd like to get the xcodebuild output when running the gym action so that we can use the LLVM/Clang parser to find any errors or warnings when building the code.

In our previous non-fastlane setup we'd do this directly on the result of the console log after its run xcodebuild. (Un)fortunately the fastlane gym (and scan) output is formatted with xcpretty and therefore we can't use the LLVM/Clang parser on the output of that.

Is there any way to get the xcodebuild log currently and have it redirected to a file in the workspace, or have it placed in the ./outputs/ directory as a part of the setup_jenkins action?

Found a bunch of logs related to our builds here, but unable to target the specific log we need at the end of the build:
~/Library/Logs/gym

Thanks,
Joshua

**Comment by vpolouchkine** [comment]
I don't think so, but fwiw there is an `xcodebuild` action, see https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#xcodebuild
