### ISSUE TITLE
UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#3636]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}

##### Complete output when running fastlane, including the stack trace and command used

```
✗ testSnapshot, UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}


FlagshipSnapshotUITests.FlagshipScreenshotsUITests
testSnapshot, UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=9 "Error getting main window -25204" UserInfo={NSLocalizedDescription=Error getting main window -25204}
<unknown>:0


	 Executed 1 test, with 1 failure (0 unexpected) in 6.026 (6.030) seconds

[19:27:53]: Exit status: 65
[19:27:53]: Tests failed - check out the log above
```

Note that the UITest target runs fine manually from Xcode and xcodebuild.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:

```
# A list of devices you want to take the screenshots from
devices([
  "iPhone 6s"
])

languages([
  'de-DE',
  'en-AU',
  'en-CA',
  'en-GB',
  'en-US',
  'fr-CA',
  'fr-FR',
  'nl-NL',
  'zh_CN'
])

# The name of the scheme which contains the UI Tests
scheme "SomeScheme"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "SomeProject.xcworkspace"
```

### Environment

fastlane version (fastlane -v): 1.66.0
Do you use bundler, rbenv or rvm? No

**Comment by tsafrir** [comment]
I had the same today. I found it was because the app crashed during the snapshot and thus the error received is "Error getting main window -25204" since the app window already gone.

In my case the reason I didn't had that crash during development is because during snapshot there is different content that doesn't cause the crash.

**Comment by TKBurner** [comment]
@tsafrir Thanks for letting us know! So after you fixed the content issue were you able to get up and running?

Thanks!

**Comment by postmechanical** [comment]
In the case for which the issue was originally created the app under test was running just fine and had not crashed.

**Comment by TKBurner** [comment]
Hi @postmechanical! Can you let me know if you get this error when you run your tests via Xcode?

Thanks!

**Comment by postmechanical** [comment]
@TKBurner No, the error does not occur when running test target from Xcode.

**Comment by tsafrir** [comment]
@TKBurner yes, after I fixed the content issue, it got back to normal and was able to take snapshots.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (462/400 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:43289 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKt6-002lXD-S1
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:37 +0200
Date: Sat, 18 Jun 2016 11:21:51 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274111;
	bh=2h45Wre0e2SneWjc5P0UKzkItVSYWh+SDKNKO0NfngU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Ayip4P1He6vFpMvVi5yR74Su1tUOfQsyeYNkd9ANmacmgEjwkH8teEfdP3Y8mc4ub
	 b9dlfYI/iF6cJ31tEBSjuzZOq9O2w3cOZYKwKglCj92fbCPvARq9MLumIo4PZJ+9Pp
	 uVAXjvemRe8/g/gCvoiFQINfaC05g4/ULfpJTKKU=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (464/400 (115%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o3.sgmail.github.com ([192.254.112.98]:63465)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKtA-002lXd-8S
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:41 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=bd3//hZHuwtwN2ZvEJp/5vuUNvU=; b=GXfYJR3Xok05kZAL
	furTrseg1FJgVM5++1D+e0pbQi4feVThUbGzm2ydFexhJb/6Qg0qZhVVqqmS35pf
	47sJvH6T+IG/QtVSSyKon9q9WuLicH9IAwcajDta0GY7uOs1NfFtDRC0HRTUntDF
	fsPYARLOLp7R+5pCw8JlyVtQiBA=
Received: by filter0629p1mdw1.sendgrid.net with SMTP id filter0629p1mdw1.4989.5765913F21
        2016-06-18 18:21:51.617291279 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id dZiYHpxRR7K0wiUTS3c9DA
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:51.494 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:51 -0700
