### ISSUE TITLE
UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=12 "Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)" UserInfo={NSLocalizedDescription=Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)}

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#3638]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
✗ testSnapshot, UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=12 "Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)" UserInfo={NSLocalizedDescription=Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)}


FlagshipSnapshotUITests.FlagshipScreenshotsUITests
testSnapshot, UI Testing Failure - Failure getting refresh snapshot Error Domain=XCTestManagerErrorDomain Code=12 "Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)" UserInfo={NSLocalizedDescription=Failed to get main window after 30 retries: kAXErrorServerNotFound (see <rdar://problem/15530121>)}
<unknown>:0


	 Executed 1 test, with 1 failure (0 unexpected) in 12.638 (12.642) seconds

[19:28:53]: Exit status: 65
[19:28:53]: Tests failed - check out the log above
```

Note that the UITest target runs fine manually from Xcode and xcodebuild.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:

```
# A list of devices you want to take the screenshots from
devices([
  "iPhone 6s"
])

languages([
  'de-DE',
  'en-AU',
  'en-CA',
  'en-GB',
  'en-US',
  'fr-CA',
  'fr-FR',
  'nl-NL',
  'zh_CN'
])

# The name of the scheme which contains the UI Tests
scheme "SomeScheme"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

# clear_previous_screenshots # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "SomeProject.xcworkspace"
```

### Environment

fastlane version (fastlane -v): 1.66.0
Do you use bundler, rbenv or rvm? No

**Comment by i2amsam** [comment]
@postmechanical I have not seen this one before, anything useful from that Radar link?  What steps have you tried?

**Comment by postmechanical** [comment]
@i2amsam Nothing useful. I gave up. I didn't have time to deal with the problem.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (465/400 (116%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:44311 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtC-002lZ8-LM
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:43 +0200
Date: Sat, 18 Jun 2016 11:21:57 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274117;
	bh=AwD1U35TWvGY4H6/raPy4dauSGz/AKSDlEy/T9jX0LU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=jQl1ARcjfnoAGizr9pOzeweTHFY+YuqLtD56gku8uITKRDCauDvcRuRiPSEUsS2fs
	 zzhKc2rQesSGspFHJPKrIFyug2Y38KoeKEt5F2cn+M7+Q6y8EYfu4QE8XTyTZssUzf
	 RVk3vwqlomq+hLgGMYTHArsb9RJZS2goLmZt8WjI=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (468/400 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:25115)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKtJ-002lbS-6u
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:52 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=BdOpLVYWndWFxUmFWyfZBZVqwVI=; b=r6wKuE40wXgIcB9g
	56Jkgkp7CaS669twyA62l5YtOBqhDABcCErnZThRiXwqfEQJU7OuzwhM2CIxz9lk
	Ainzj6X63AGMval9vv2mISbqt3cgS57UFFUcINj7SpLNquQdYVOYMH9zI3MUip/X
	fh/kTpdX4E2fgmHn5yo8GV8O0is=
Received: by filter0414p1mdw1.sendgrid.net with SMTP id filter0414p1mdw1.9619.5765914439
        2016-06-18 18:21:56.927954281 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id bSDrckV3Qz2hLuVFZmELcQ
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:21:56.939 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:21:56 -0700
