### ISSUE TITLE
Making Changelog file from git log

### ISSUE THREAD

**Issue by yuriy-tolstoguzov** [fastlane/fastlane#3672]
### New Issue Checklist

- [ :white_check_mark: ] Updated fastlane to the latest version
- [ :white_check_mark: ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
🔑

### Issue Description
I see fastlane has action to pull changelog from jenkins, but not from GIT, I've searched issues and pull requests but have not found that functionality either. I am going to implemented by myself though. What I am going to do is simple action that uses `git log --pretty=format:"SomeFormat" -#SomeNumberOfLines` to pull logs and write them in some file that can be sent further, for example, to Crashlytics when uploading build.
Your advices are welcomed!
I am going to create pull request soon.

**Comment by mfurtak** [comment]
Hi @yuriy-tolstoguzov - thanks for checking in with us, and for going through the guidelines so carefully! :+1: :100: 

Are you aware of the `changelog_from_git_commits` action? Please let us know if it works for your needs! :dart:

**Comment by yuriy-tolstoguzov** [comment]
@mfurtak, Somehow I have not seen it. I am limited in time now, but I will check it out later and probably change my PR to enhance existing action, rather than add new one.

**Comment by mfurtak** [comment]
Great! When you're considering extending the action, please keep in mind that it gets used by iOS developers, Android developers, and others. We'll need to keep it general enough to work for everyone :apple: :peach: :pear: 

I will close this for now, but we can always reopen if desired later. :+1:

**Comment by mfurtak** [comment]
Oh, and if you want to produce an action that is more tightly aligned with your workflow, check out the documentation on creating and using [local actions](https://github.com/fastlane/fastlane/tree/master/fastlane/docs#extensions) :tada:
