### ISSUE TITLE
SnapshotHelper.swift doesn't compile for apps targeting iOS 8 and under

### ISSUE THREAD

**Issue by OllenDev** [fastlane/fastlane#3679]
To use snapshot one must add the SnapshotHelper.swift file to your project. SnapshotHelper.swift is currently missing some @available declarations that would enable it to compile for apps that target iOS 8 and under.

**Comment by ohwutup** [comment]
Hey @OllenDev! Thanks for raising the issue and submitting that PR. I am trying to reproduce the problem but am not able to. Are you running snapshot on simulators with older versions of iOS installed?
