### ISSUE TITLE
Match: Single repository, multiple Apps

### ISSUE THREAD

**Issue by txaidw** [fastlane/fastlane#3685]
Can I use Match with a single repository for a company with multiple Apps?

I think match is messing with old profiles on the same repository.

**Comment by vpolouchkine** [comment]
Sure, take a look https://github.com/fastlane/fastlane/tree/master/match#handle-multiple-targets

**Comment by txaidw** [comment]
This is for targets, but im going to assume it works with different apps too! So Issue closed, thank you very much!

**Comment by freesuraj** [comment]
The certs are being overwritten. Please have a look.

**Comment by TKBurner** [comment]
@freesuraj If you are running into an issue, can you please submit a new thread? Thanks so much!
