### ISSUE TITLE
APK support on the S3 action

### ISSUE THREAD

**Issue by truth3** [fastlane/fastlane#3696]
@joshdholtz 

Just logging the feature request we talked about for supporting .apk files on the S3 action. Thanks for a great action, and looking forward to this improvement!

**Comment by joshdholtz** [comment]
I will tackle this next week :confetti_ball: :tada:

**Comment by truth3** [comment]
Hump day bump :)

**Comment by joshdholtz** [comment]
@truth3 OMG, I am the worst... I have to get a Swift presentation today at my alma mater but I am adding this to my to do list so I don't forget :grimacing:

**Comment by truth3** [comment]
@joshdholtz On the contrary, you are the man! No worries, just a friendly reminder that I am still looking forward  to this

**Comment by truth3** [comment]
Monday bump.. no pressure, just letting you know this is still of interest :beers:

**Comment by truth3** [comment]
Draft day bump 🏈
