### ISSUE TITLE
Fastlane takes long time to start and consumes 100% during this period

### ISSUE THREAD

**Issue by anton-matosov** [fastlane/fastlane#3704]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Any action by fastlane, e.g. `fastlane --help` takes at least 2 minutes until first line is printed. During this period ruby process is eating 100% of single CPU core.
Independent tools like `gym` or `sigh` work fast.

##### Complete output when running fastlane, including the stack trace and command used
```  fastlane

  CLI for 'fastlane' - Connect all iOS deployment tools into one streamlined workflow.

        Run using `fastlane [platform] [lane_name]`
        To pass values to the lanes use `fastlane [platform] [lane_name] key:value key2:value2`

  Commands:
    action                  Shows more information for a specific command
    actions                 Lists all available fastlane actions
    disable_crash_reporting Disable crash reporting
    docs                    Generate a markdown based documentation based on the Fastfile
    enable_crash_reporting  Enable crash reporting to improve fastlane
    help                    Display global or [command] help documentation
    init                    Helps you with your initial fastlane setup
    lanes                   Lists all available lanes and shows their description
    list                    Lists all available lanes without description
    new_action              Create a new custom action for fastlane.
    run                     Run a fastlane one-off action without a full lane
    trigger                 Drive the fastlane for a specific environment. Pass the lane name and optionally the platform first

  Global Options:
    --verbose             
    -h, --help           Display help documentation 
    -v, --version        Display version information 
  
  Author:
    Felix Krause <fastlane@krausefx.com>
  
  Website:
    https://fastlane.tools
  
  GitHub:
    https://github.com/fastlane/fastlane
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
<nothing here>
```

### Environment
default 

fastlane version (fastlane -v):
fastlane 1.66.0

Do you use bundler, rbenv or rvm?
rbenv 1.0.0
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
gem -v
2.4.5.1

**Comment by KrauseFx** [comment]
Did you run `gem cleanup`?

**Comment by anton-matosov** [comment]
yes, it didn't help.
I have removed ~/.rbenv and reinstalled everything. it works fine now.
