### ISSUE TITLE
on licenses with lots of Devices this command takes to long profile.update!

### ISSUE THREAD

**Issue by sfransen** [fastlane/fastlane#3706]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
on licenses with lots of Devices this command takes to long between 15-20 minutes  
 so if I try to added all Devices to each Provision Profiles.
I have hundreds of Provision profiles and it will take 150 hours to do this just to add one new device to each provision profiles. There has to be a better way. Cupertino code could do this in less then 20 minutes. What can I do to fix this so It is faster. I really need to to work.

 in the function  def update!
        profile = **Spaceship::ProvisioningProfile.all(mac: mac?)**.find do |p|  
          p.name == self.name # we can use the name as it's valid
        end
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v):
fastlane 1.66.0
Do you use bundler, rbenv or rvm?

**Comment by sfransen** [comment]
I fine if I command these lines out of spaceship update! function
 if you are going to add devices to more then 1 provision profiles 
it will speed things up lot. as this call takes 10 -1 5 minutes each time.
 
 so it I have a for loop to add to each provision profiles   then I do another 
 for loop to download all the provision profiles  after I make this call ONCE
 I saved  many Hours
 I did a test and it I do it your way with as many devices in my license it will take me 150 hours  to add 1 devices to all my provision profiles and download them all
 if I removes those extra calls I can do as thing in 43 minutes 

 should I create a different function for large Licenses for other people to use?

 I still like to know how to speed up this call.
**Spaceship::ProvisioningProfile.all(mac: mac?).find**

these are the calls you don't want on large license in update!
profile = Spaceship::ProvisioningProfile.all(mac: mac?).find do |p|
  p.name == self.name # we can use the name as it's valid
end profile
 return profile

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (469/400 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:40497 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtN-002lci-6O
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:54 +0200
Date: Sat, 18 Jun 2016 11:22:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274127;
	bh=RMhRssMpm/sNXpOYImxD8mURArzLU9x4r5mRi4NERfs=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=PQBrqiHqg1pUEXA+49FdD+k4JBLx5xN44a8igyLf4gZChrf/vizhQi/v34G8M78e9
	 SFXfQdNG+6cnTd5KVic+hY7N99B/FAgNBLcY2kLcMAKT1qxAsvX6x4w2yvheMTslkD
	 66Eq6kDBgdI2mAzrE8GscgwS7bPMx++z3RpWqKK0=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (470/400 (117%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:46227 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtN-002lcq-C4
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:56 +0200
Date: Sat, 18 Jun 2016 11:22:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274128;
	bh=AsIhnV0o9e/Ya6QLwZCHSrxdxekSvXfaU5nIk9XM5oQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=j5fb73XN41Am5ckqdFwFnCC+cf01qCVtn052iccyzkPRPs9VaGoUmGey3Sj3yuBlO
	 eDGhpY5/aXN2mVtpjHqLFaQflfHnl+QQrucW2PeKNIwPajwq8EltG0MBNE0DwGV3MJ
	 9p6wjPcrkPSDiANcv8vxQTCfvb09Waj6CaEMQ/eg=
