### ISSUE TITLE
Ability to use signing identity SHA-1 in `resign`

### ISSUE THREAD

**Issue by somedev** [fastlane/fastlane#3708]
### Issue Description
I'm using `resigh` to resign .ipa with our enterprise distribution certificate. We have 2 distribution certificates in dev portal for enterprise builds. If both certificates are installed in my keychain, it is not possible to use them with `resigh`, because they have the same names. `security find-identity -v -p codesigning` returns something like that:
```
1) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX "iPhone Distribution: My Company, LLC"
2) YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY "iPhone Distribution: My Company, LLC"

     2 valid identities found
```
They have the same names, but SHA-1 for each of them is different. According to `codesign` manual, this SHA-1 could also be used as signing identity parameter (instead of certificat name).

```
...If identity consists of exactly forty hexadecimal digits, it is instead interpreted as the SHA-1 hash of the
certificate part of the desired identity.  In this case, the identity's subject name is not considered...
```
##### Complete output when running fastlane, including the stack trace and command used

```
[14:34:54]: Couldn't find signing identity 'iPhone Distribution: My Company, LLC'.
[14:34:54]: Available identities:
	iPhone Distribution: My Company, LLC
        iPhone Distribution: My Company, LLC
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :build do |options|
 gym options

 if options[:some_flag] == false
    puts "resigning".green
    resign(ipa: "path/to/build.ipa",
    signing_identity: "iPhone Distribution: My Company, LLC",
    provisioning_profile: "path/to/provision")
    puts "resigning finished".green
  end

end
```
### Environment
ruby 2.2.0p0
fastlane version: 1.66.0
sigh version: 1.4.1
Do you use bundler, rbenv or rvm: rvm

**Comment by asfalcone** [comment]
This change has been merged. It will go out in a future release of `sigh`! 👍

**Comment by somedev** [comment]
@asfalcone @KrauseFx  do you have any thoughts when new `sigh` version with this fix (#4898) would be released?

**Comment by asfalcone** [comment]
@somedev Whoops, sorry for the delay on the release! I'll try to get it out on Monday! I didn't realize we had unreleased changes for so long.

**Comment by somedev** [comment]
@asfalcone Happy to hear that! Thanks.

**Comment by asfalcone** [comment]
[`sigh` 1.9.0](https://github.com/fastlane/fastlane/releases/tag/sigh%2F1.9.0) has been released 🚀

**Comment by somedev** [comment]
Cool 👍
