### ISSUE TITLE
Enhancement: When passing a name to new_action, fastlane still prompts you for a name.

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#3710]
`fastlane new_action react_bundle`

Still causes fastlane to output the following

```
Must be lower case, and use a '_' between words. Do not use '.'
examples: 'testflight', 'upload_to_s3'
```

I exepected it to grab the `react_bundle` passed in as the first argument and use it as the name

**Comment by KrauseFx** [comment]
Right now the args are unused: https://github.com/fastlane/fastlane/blob/master/fastlane/bin/fastlane#L59-L61, it should be easy to add this :+1:

**Comment by hemal** [comment]
Just merged this: https://github.com/fastlane/fastlane/pull/4041

It will be available in the next release, closing this but let me know on Slack how it works out for you!
