### ISSUE TITLE
Pilot is not using team_id from Appfile

### ISSUE THREAD

**Issue by txaidw** [fastlane/fastlane#3711]
Pilot is not using team_id from Appfile
Is this by design? Or should be added in a next release? Thanks

**Comment by vpolouchkine** [comment]
"Pilot is not using team_id from Apple" 

What do you mean?

**Comment by txaidw** [comment]
Ohh, sorry for the terrible typo, it's supposed to be Appfile not Apple..

**Comment by KrauseFx** [comment]
@txaidw You forgot to share your Appfile. I assume you used `team_name` instead of `itc_team_name`

**Comment by txaidw** [comment]
I thought 'team_id' was the same thing that 'itc_team_name'. 
Thanks you very much!
