### ISSUE TITLE
Improve Error Reporting in Fastlane

### ISSUE THREAD

**Issue by orta** [fastlane/fastlane#3712]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) :key: 

A mirror of https://github.com/CocoaPods/CocoaPods/issues/4817 - because it could be used in many different places.

(edit: hah - at that original title)

**Comment by ohwutup** [comment]
Taken care of by https://github.com/fastlane/fastlane/pull/5162 🎉
