### ISSUE TITLE
Update app Error: "You must detail what's new in this version in English"

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#3715]
Using the latest ```Deliver``` version (1.10.3)
When update application, how can I provide the what's new text? iTunes connect refuse to submit the application to review because no "what's new" added.

This is the ```fastlane``` error I get: 

```
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response': [!] You must detail what's new in this version in English. (Spaceship::TunesClient::ITunesConnectError)
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/tunes_client.rb:681:in `prepare_app_submissions'
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/app_submission.rb:117:in `create'
~/vendor/bundle/ruby/2.0.0/gems/spaceship-0.22.0/lib/spaceship/tunes/application.rb:269:in `create_submission'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/submit_for_review.rb:8:in `submit!'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:87:in `submit_for_review'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/runner.rb:30:in `run'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
~/vendor/bundle/ruby/2.0.0/gems/fastlane_core-0.37.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
~/vendor/bundle/ruby/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:132:in `run'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/lib/deliver/commands_generator.rb:12:in `start'
~/vendor/bundle/ruby/2.0.0/gems/deliver-1.10.3/bin/deliver:5:in `<top (required)>'
~/vendor/bundle/ruby/2.0.0/bin/deliver:23:in `load'
~/vendor/bundle/ruby/2.0.0/bin/deliver:23:in `<main>'
```

**Comment by vpolouchkine** [comment]
Can you please share your Deliverfile?

**Comment by chezzdev** [comment]
Looks very similar to my issue https://github.com/fastlane/fastlane/issues/3716 where I was launching `deliver` with ```--skip_metadata``` flag. Try to run `deliver` without it if that's the case.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (472/400 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:47036 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtS-002leS-Hd
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:22:59 +0200
Date: Sat, 18 Jun 2016 11:22:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274133;
	bh=VTWBELDuHpczcE0GbMr0DbzOVPxuEwywLMsSgEC9N7E=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=BXc9d7DzL2rAS4rBTiTMoD2mM/SM8DKRorfy87tIRvCKjQF6NYgU7rguOk3GeKTC9
	 X0pY+tfYYGHaqCze6cUSvAtmRbMcIo1tZk4zCZInzR6w4u+2JCVa9qBiVefuBjniey
	 WHy4v5cB9zmTv+dHvj2Kr6QgqYW/m3RxB/uLyWDU=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (473/400 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:41359 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtS-002leU-Tj
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:00 +0200
Date: Sat, 18 Jun 2016 11:22:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274133;
	bh=1Ot9u4V2r2hjfotFPaWZQz0ZtOE8sT8XjXcYCnseZsc=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Elr8GNEKb6mnuZC56XDSnvh6w++LbqK4K1REtUJQn7Is0VXYTIgYbnmAMjH7RmhO5
	 H7zffwibmo3g4hLfKfaa30Q/s76G85t+YxM6yFe+yrSndA3OE1aCQvs+/4gu2JYYZ+
	 Ly1cxcQX0S68y2Qi0BhlJXguBM0GgiqisQ0mZ5Vc=
