### ISSUE TITLE
https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

### ISSUE THREAD

**Issue by pavm035** [fastlane/fastlane#3717]
Looks is this link is broken?

**Comment by SpacyRicochet** [comment]
Could you point out where you found the broken link? 

Even better, submit a pull request with the correct link: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md (or directly to the RAW: https://raw.githubusercontent.com/fastlane/fastlane/master/fastlane/docs/Actions.md)

**Comment by KrauseFx** [comment]
Thanks @SpacyRicochet :+1:

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (414/400 (103%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:52951 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMW-000aiH-Gl
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:12 +0100
Date: Sun, 13 Mar 2016 22:18:53 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457932733;
	bh=Ggr6CNdYjjmvW84ctwsEB7N1cUI/cT0VS9DBx3s4CIA=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=YVoSbkCYJH7KZ4DMf3HInEf8nZsFPYNGAbnV7jS6QL22QixuUws0pOkmvRRZBZ9vu
	 4OhLCcDdP191qKrbGB2yBqzR8AiVCsS5y1Lu+C3lcn3yT8AouvB59B7lgKlWQ6jd42
	 35ljCMWgk+2Mv1Mt85+OjnlRaORjzPwzThYqggOM=

**Comment by pavm035** [comment]
Now it's working

Thanks
