### ISSUE TITLE
What's the available values for `export_method` option in gym?

### ISSUE THREAD

**Issue by xilin** [fastlane/fastlane#3718]
Currently I found ad-hoc/app-store/enterprise from github search.
What's the other available values for `export_method` option in gym? And how it goes with code signing and provisioning profile?
Thanks.

**Comment by iONsky** [comment]
You can execute `xcodebuild -help`to see all export options.

Here the output for the `method` or in gym `export_method` option:

> method : String
Describes how Xcode should export the archive. Available options: app-store, ad-hoc, package, enterprise, development, and developer-id. The list of options varies based on the type of archive. Defaults to development.

**Comment by xilin** [comment]
@iONsky Thanks! Didn't notice these commands are wrapper of `xcodebuild`.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (424/400 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:54380 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMk-000alX-BX
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:38:31 +0100
Date: Sun, 13 Mar 2016 23:31:21 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457937081;
	bh=U50WIPMo0gI0bN9hkAPPSEah09Ypx9IeKYwmMaYKlhk=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LX+gzX0+20Wu0BcD4h3310c9n0E/LecgLwOXlpwqPZEWJou5oy4W6u1P5CO/AUaPa
	 XVgAZQHGQKKRb6AXsOlGD2n9K7Z8bK23jp9BKrdGWM9H5Ee0FpvZmRu1zmyTRLfN85
	 IYMk/kh625/eqQ3XX8Ui9Cn30ENfWi4rNozie3cs=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (450/400 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:33175 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmQU-000bho-2A
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:42:19 +0100
Date: Sun, 13 Mar 2016 23:34:01 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457937241;
	bh=wjoi4IDO5GiD/PwiAxOse1C4oT1nS4WUG9+5PFP+XMg=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=akv2IhjM+PKhGGWMTOJ1pzkyT4RN1gKHy/CW9Qb3h0eX5A9nvs3boozwHpaIqkO1m
	 s/hkOfKCCGiiB2AsbTMzJrZqv1nA2X2gpmVxYBWocKZOicKFg287yKgZ6TTqoGrJkB
	 nnDzUjxs9s/A6vCaiVcjp5eYPCrN1iG2fePMXIAE=
