### ISSUE TITLE
Deliver stuck on "Saving changes"

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#3721]
`Deliver` stuck one step before finish upload screenshots:
```
Uploading ... 
Uploading ... 
Uploading ... 
Uploading ... 
Uploading ... 
Uploading ... 
Uploading ... 
Saving changes
```

And wait forever.

Any timeout for the action? Any retry to save changes action?

**Comment by vpolouchkine** [comment]
Please format the issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md
Thanks!

**Comment by lacostej** [comment]
@gran33 please follow @vpolouchkine  advice 

do not forget to tell info about your version of deliver/spaceship

note that
* saving changes is notoriously slow.
* deliver implement retries and take time. A request is waited upon for 5 min (because in many cases, ITC take 3/4 min to accept the data). Sometimes it fails, and logs out the user, meaning that deliver will log in again and try again, for up to 5 times. Seldomly it can thus take ~20 min before deliver finally delivers.

Note that we are implementing syncing / caching soon which will make deliver much faster when few screenshots have changed. See #3755.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (475/400 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:46088)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKtb-002lgD-29
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:07 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=wOx3qvIwm1d0atJcc2pmsPW/uL8=; b=PANPBepK6Z3gD1+T
	B3CjYT9d0ZkfL+HQook9wqIXFtgmlfVBg+32A9uTjvvB6dbB6Mg2/y+Je0FNacFa
	xNbCAtHAtS6oxkwM8WSLTJVpIejT0r9yzpNMTUQejTBAoicQEa9w3o1VCQD1TXmX
	MOtDRUBFCdZwV2NmjspCQ46vDVY=
Received: by filter0604p1mdw1.sendgrid.net with SMTP id filter0604p1mdw1.24746.5765915A33
        2016-06-18 18:22:18.888719939 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id 1-qUj_LqSValx2V8TJdemw
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:22:19.047 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:22:18 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (474/400 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:47974 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtY-002lg5-4r
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:05 +0200
Date: Sat, 18 Jun 2016 11:22:18 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274138;
	bh=gM2B5U+tsFOwYWGTgaVi9FDxyF+SmlYQefft6l+LdAE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=MZNlFAT10m3Z5T43254i3wit88CxbHfI2fQj85GAIne7i1tVPKj2tmiXzk1OGXbzd
	 vj6WjaSEK5f2Cnofi7Mih3K2EJN46zK/S324GX149X20p76cY2so+/GESuOLzPw6cV
	 X5zBVaBsWS8WlR9RgO3dolH1a/vHCEcTf3zhZxSM=
