### ISSUE TITLE
Add support for second_curtain

### ISSUE THREAD

**Issue by orta** [fastlane/fastlane#373]
In eigen we do:

```
set -o pipefail && xcodebuild -workspace $(WORKSPACE) -scheme $(SCHEME) -configuration Debug test -sdk iphonesimulator -destination $(DEVICE_HOST) | bundle exec second_curtain
```

So that [second_curtain](https://github.com/ashfurrow/second_curtain) can parse the logs. We're using the native fastlane apis for testing in [eidolon](https://github.com/artsy/eidolon/blob/master/fastlane/Fastfile#L5) but ideally would want to pipe the logs through second_curtain.

**Comment by bgerstle** [comment]
what about reading the raw `xcodebuild` output from a log file? for example (use at own risk, not tested!):

``` ruby
lane :test do
  scan(
    # ...
    buildlog_path: "build/reports"
  )
  sh "cat ../build/reports/xcodebuild.log | second_curtain" 
  # or use second_curtain Ruby API to read the file
end
```

**Comment by orta** [comment]
Yeah, that could probably work!
