### ISSUE TITLE
Messing launch image??

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#3730]
I'm running _fastlane beta_ on a react-native app and am getting an error about missing launch images.  The app has a launch screen, provided by react-native so didn't think it needed a launch image.  

Is the error correct and do I need to provide a 320x568 launch image?  Even those dimensions don't seem right according to [this](http://www.idev101.com/code/User_Interface/launchImages.html) and [this](https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html#//apple_ref/doc/uid/TP40006556-CH27-SW2). 

This is the error:

> [18:15:16]: [Transporter Error Output]: ERROR : "Your binary is not optimized for iPhone 5 - New iPhone apps and app updates submitted must support the 4-inch display on iPhone 5 and must include a launch image referenced in the Info.plist under UILaunchImages with a UILaunchImageSize value set to {320, 568}. Launch images must be PNG files and located at the top-level of your bundle, or provided within each .lproj folder if you localize your launch images. Learn more about iPhone 5 support and app launch images by reviewing the 'iOS Human Interface Guidelines' at 'https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconsImages/IconsImages.html#//apple_ref/doc/uid/TP40006556-CH14-SW5' and the 'iOS App Programming Guide' at 'https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/App-RelatedResources/App-RelatedResources.html#//apple_ref/doc/uid/TP40007072-CH6-SW12'."

**Comment by KrauseFx** [comment]
This is not a fastlane issue, but has something to do with your project. Make sure to provide all necessary launch images before building and uploading your application
