### ISSUE TITLE
match: documentation request: where does the repo get GIT_AUTHOR_EMAIL from?

### ISSUE THREAD

**Issue by cbowns** [fastlane/fastlane#3736]
### New Issue Checklist

- [√] Updated fastlane to the latest version
- [√] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Me and my other team developer are looking at our `match` repo on github.com, and seeing that my GitHub user is set as the committing author for all commits in the repo, even for `match` commands run on our other developer's machine:

```
commit cd60a948fc2680a503a8cbd091f64edab880b3fb
Author: Christopher Bowns <github@cbowns.com>
Date:   Mon Mar 14 12:48:44 2016 -0700
…
```
##### Complete output when running fastlane, including the stack trace and command used

N/A

### Configuration Files

N/A

### Environment

fastlane version (fastlane -v): `fastlane 1.66.0`

Do you use bundler, rbenv or rvm?
`chruby` and `bundler`.

**Comment by vpolouchkine** [comment]
What is shown when your colleague runs `git config user.email`?

**Comment by KrauseFx** [comment]
@cbowns Any updates on this?

**Comment by cbowns** [comment]
They get their expected user, when run in the repo which contains our project which uses `match`.

```
$ git config user.email
dominic@linebreak.co
```

**Comment by cbowns** [comment]
This appears to be fixed, or my original bug wasn't actually a thing.

An FYI, though: y'all's tagging/response tracking is broken. I replied back on March 17th, but no one from the org came back with anything.
