### ISSUE TITLE
Create Google Play apps using API

### ISSUE THREAD

**Issue by marcomorain** [fastlane/fastlane#3740]
I don't see a way to create Google Play apps using `Fastlane`. Is there an Android equivalent to [Produce](https://github.com/fastlane/fastlane/tree/master/produce)?

I think I'm going to have to build something if there is no way to automate the process at present.

Does anyone else have any pointers on how to create new apps without doing it through the browser?

**Comment by vpolouchkine** [comment]
There is currently no equivalent.

**Comment by KrauseFx** [comment]
This is unfortunately not possible due to the API limitations of Google Play.
