### ISSUE TITLE
gym, match and probably all fastlane tools does not respect data privacy

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#3744]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I use Travis-CI for project building, and fastlane makes me really-really sad as it prints out a lot of secret sensible data in build log: passwords, environment variables, secret urls etc. with just plain text. I already mentioned in #3423 that match prints the git url with credentials in plain, which is highly unacceptable! 
I can put up with it in my private repositories build, but I definetly will not trust fastlane in building for my open-sorce projects today 😐
Setting an encrypted environment variables in Travis makes no sense: fastlane just print it out.
The last straw that enforced me to create this issue was when I noticed today a new debug output strings from `PackageApplication4Gym` tool, that printed out all of Travis environment variables in plain text:
* CRASHLYTICS_BUILD_SECRET
* CRASHLYTICS_API_TOKEN
* **ALL** the passwords: itunesconnect, developer.apple.com, my internal services
* **ALL** the usernames

Dear fastlane team! You've made an incredible, outstanding toolset, and I really appreciate you for such a time-saving project! But could you **please!** be more attentive to privacy? Especially when running in cloud-based CI?

### Environment

Travis-CI

fastlane version (fastlane -v): 
1.66.0
Do you use bundler, rbenv or rvm? 
bundler

**Comment by KrauseFx** [comment]
Hey @Sega-Zero, thanks for raising this issue, that are valid points! 

**To go into detail:**

1. Git: You can authenticate to Git using public/private keys or your application specific git password in your keychain
1. The crashlytics concern is perfectly valid, I'll provide a fix :+1: 
1. I don't understand the username part: If you're talking about an open source project, your usernames are all stored in your `Appfile` / `Fastfile` anyway, right? Or do you provide them using environment variables? 
1. Could you clarify what you mean by the `PackageApplication4Gym`?
1. Having "secure" environment variables doesn't really mean they're secure: If it's an open source project, everybody can just submit a PR to your project and replace your test script with just a script that dumps all environment variables.

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/3746 for the Crashlytics point

**Comment by Sega-Zero** [comment]
1. Does match supports that kind of authentication? Couldn't get it working because of #3423, only specifying username:password in git url works for me. Also, I use secure ENV to download binary from Github Releases, by storing the url, containing auth token.
3. I do not store any credentials in Appfile/Fastfile. I provide them via secure environment variables.
4. The last step of gym action contains some patch applying with this log:
```shell
INFO [2016-03-15 11:49:36.85]: Successfully stored the archive. You can find it in the Xcode Organizer.
DEBUG [2016-03-15 11:49:36.85]: Stored the archive in: /Users/travis/Library/Developer/Xcode/Archives/2016-03-15/Project 2016-03-15 11.37.55.xcarchive
DEBUG [2016-03-15 11:49:36.94]: Applying Package Application patch: 0001_codesign_args_patch.diff
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
|                                                                            Applying Package Application patch: 0001_codesign_args_patch.diff                                                                            |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| Option                                                                                                                                                                                | Value                           |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
| patch '/tmp/PackageApplication4Gym' < '/Users/travis/build/company/iOS/vendor/bundle/ruby/2.0.0/gems/gym-1.6.2/lib/assets/package_application_patches/0001_codesign_args_patch.diff' |                                 |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------------------+
INFO [2016-03-15 11:49:37.00]: $ patch '/tmp/PackageApplication4Gym' < '/Users/travis/build/company/iOS/vendor/bundle/ruby/2.0.0/gems/gym-1.6.2/lib/assets/package_application_patches/0001_codesign_args_patch.diff'
INFO [2016-03-15 11:49:37.08]: ▸ patching file /tmp/PackageApplication4Gym
DEBUG [2016-03-15 11:49:37.08]: Applying Package Application patch: 0002_no_strict_parameter_patch.diff
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+
|                                                                             Applying Package Application patch: 0002_no_strict_parameter_patch.diff                                                                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+
| Option                                                                                                                                                                                      | Value                              |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+
| patch '/tmp/PackageApplication4Gym' < '/Users/travis/build/company/iOS/vendor/bundle/ruby/2.0.0/gems/gym-1.6.2/lib/assets/package_application_patches/0002_no_strict_parameter_patch.diff' |                                    |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------+
INFO [2016-03-15 11:49:37.13]: $ patch '/tmp/PackageApplication4Gym' < '/Users/travis/build/company/iOS/vendor/bundle/ruby/2.0.0/gems/gym-1.6.2/lib/assets/package_application_patches/0002_no_strict_parameter_patch.diff'
INFO [2016-03-15 11:49:37.17]: ▸ patching file /tmp/PackageApplication4Gym
+--------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
|                                                                                          Generated Package Command                                                                                           |
+--------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| Option                                                                                                                               | Value                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
| /usr/bin/xcrun /tmp/PackageApplication4Gym -v                                                                                        |                                                                       |
| /Users/travis/Library/Developer/Xcode/Archives/2016-03-15/Project\ 2016-03-15\ 11.37.55.xcarchive/Products/Applications/Project.app |                                                                       |
| -o                                                                                                                                   | /Users/travis/Library/Developer/Xcode/Archives/2016-03-15/Project.ipa |
| exportFormat ipa                                                                                                                     |                                                                       |
+--------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------+
INFO [2016-03-15 11:49:37.49]: $ /usr/bin/xcrun /tmp/PackageApplication4Gym -v /Users/travis/Library/Developer/Xcode/Archives/2016-03-15/Project\ 2016-03-15\ 11.37.55.xcarchive/Products/Applications/Project.app -o '/Users/travis/Library/Developer/Xcode/Archives/2016-03-15/Project.ipa' exportFormat ipa 
INFO [2016-03-15 11:49:39.19]: ▸ Packaging application: '/Users/travis/Library/Developer/Xcode/Archives/2016-03-15/Project 2016-03-15 11.37.55.xcarchive/Products/Applications/Project.app'
INFO [2016-03-15 11:49:39.23]: ▸ Arguments: verbose=1  output=/Users/travis/Library/Developer/Xcode/Archives/2016-03-15/Project.ipa
INFO [2016-03-15 11:49:39.24]: ▸ Environment variables:
INFO [2016-03-15 11:49:39.26]: ▸ SHELL = /bin/bash
**A WHOLE BUNCH OF PLAIN ENVIRONMENT VARIABLES**
```
5) Completly wrong opinion, Travis-CI [protects](https://docs.travis-ci.com/user/pull-requests#sts=Security%20Restrictions%20when%20testing%20Pull%20Requests) from this kind of attack. Only the owner of the repo may expose this variables:
> For the protection of secure data, Travis CI makes it available only on pull requests coming from the same repository. These are considered trustworthy, as only members with write access to the repository can send them.

**Comment by KrauseFx** [comment]
- It looks like you're using the verbose mode for `gym`, you shouldn't do that if you don't want commands to be printed out.
- The next release of fastlane won't print out the `crashlytics` command.
- `match` supports that kind of authentication, it just uses `git clone`, so whether you use public private keys, or passwords in the Keychain, it's supported. You shouldn't provide the password in the URL
- `PackageApplication4Gym` is just the `Platforms/iPhoneOS.platform/Developer/usr/bin/PackageApplication` file, bundled in Xcode, which is provided by Apple. fastlane doesn't do the environment variable dumping here

**Comment by Sega-Zero** [comment]
* I don't use verbose for gym. Here is a gym action I use:
```ruby
gym(
	workspace: 'Project.xcworkspace',
	scheme: scheme,
	clean: true, 
	output_directory: ".",
	output_name: "Project.ipa",
	use_legacy_build_api: true
)
```
I use `verbose: true` for `match` only. Does it affects gym action too? `PackageApplication4Gym` output in build log looks like a bug to me.

* `match` prints out a git url, which is supposed to be secret even without any usernames/passwords. Is there any chance to skip logging it?
* could you add some info about storing public/private keys in keychain when using match in CI environment to match documentation? I coudln't get it working any other way that specifying username and password for github private repository url.

**Comment by Sega-Zero** [comment]
adding
```ruby
silent:true,
suppress_xcode_output: true
```

to gym action does not affect the verbosity, but turning off `verbose` for match actually **did** turned it off. shouldn't `verbose` option affect only a tool where it is specified?

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (476/400 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:42980 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtd-002liH-Jm
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:11 +0200
Date: Sat, 18 Jun 2016 11:22:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274144;
	bh=hOWhk9Z1zkOlhI3rMeI1K0/3YdGbN95n4fxwc0r0WNo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aQLD+mqehS9p9B6JMApjL8yOVPpkhmmTpoLSUpuIavqgbdXYNs5hoPCLEifH8SKEb
	 2xmP5F5WzXVjy/3mtJU5X4UWPT9X7evpw/rJnZ37Yc1UIuiWnG9epKEPvHqABEY6iv
	 2vDCy6WuUTeKdKsIIalB91wFGfGErU7oO58w76l0=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (477/400 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:43010 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtd-002liN-So
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:12 +0200
Date: Sat, 18 Jun 2016 11:22:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274144;
	bh=EbzdSunbaXkjzZJR5wZatTGwr54yxXV7zkvZWP0AyUA=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=pPKftPph/l4yE6g/HN7Eo//4ZDxIXXbNiprjjTapVTB12YRKx/ow2t6e5Q7pKBA4s
	 ngHFClcj7stGlrlvnZJSdc93AGlQdE6Cg7LqOhEvypBiovShR53rTNK6LPZYBgr1xW
	 dtlJ/ZMWKki9ltz9noKsmnVL0KFXaJsLOpJMxID8=
