### ISSUE TITLE
Add options to resume screenshot downloads and uploads

### ISSUE THREAD

**Issue by jfresen** [fastlane/fastlane#3747]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When downloading or uploading large amounts of screenshots, it is beneficial to have an option to 'resume' said download or upload, for example if your network connection is unreliable or if iTunes Connect suffers from stability problems. A particular use case in which I needed this (and added it ad hoc to my installed ruby gem) was when I was uploading over 600 screenshots and iTunes Connect was having stability problems. Using the proposed resume upload feature, I was able to skip all languages that were already successfully uploaded.

Important aspects of this feature:

* Must be configurable using command line options
* Not supplying any of the new options must result in unchanged behavior
* Use separate options for skipping downloaded screenshots and skipping of finished screenshot uploads

I will submit a pull request with a proposed implementation

**Comment by lacostej** [comment]
@jfresen we ve implemented syncing of the screenshots some days ago: see #3755

**Comment by lacostej** [comment]
@jfresen did you by any chance have a look at #3755 ? Is this something you would find useful ?

**Comment by jfresen** [comment]
Hi, thx for reminding me. #3755 certainly looks useful. If I understand correctly, it will check for each screenshot to be uploaded if it is not already on that position in ITC, and will not upload it if the check passes. That means that if I would upload, say, 500 new screenshots and 8 of them fail (e.g., due to connection problems), the next time I run deliver, it will only upload only the remaining 8, right?

I would still like to have add the --skip_downloaded option though, or implement a similar sync mechanism for screenshot downloads. The last option sounds better, and looking at your commits I think that is not so hard to accomplish now you laid out the basics. Do you think you have time to implement this download sync?

**Comment by TKBurner** [comment]
@jfresen Thanks for following up. We are going to track this over at #3755. Please feel free to update that ticket with details :+1: 

**FR: Skip screenshot download**
