### ISSUE TITLE
How to setup Matchfile for both Enterprise and Standard account in same project?

### ISSUE THREAD

**Issue by Sajjon** [fastlane/fastlane#3748]
Hey all! Thanks for amazing fastlane and amazing match! I recently changed from sigh to match in a project and the transition was very smooth. 

Now I am about to go over to match in a project using both a "standard" Apple Dev team AND an Enterprise team (I am admin for both teams using the same account, but the owner of the company has two different Apple Ids/accounts acting as agent for both teams).

I am confused and have some questions regarding this, and yes I have read the great README for match and the codesigning guide, thanks! :)

So even though @KrauseFx say that [match doesn't support Enterprise profiles](https://github.com/fastlane/match/issues/8#issuecomment-163751671) he also says that it is [possible](https://github.com/fastlane/match/issues/8#issuecomment-166168427), great - I guess ;)

So I guess I have the same setup as @romk1n described in the [thread](https://github.com/fastlane/match/issues/8) referred to above. 

I have an iOS project where we use an Apple Enterprise dev team for distributing beta versions of the app using Twitter Fabric's Crashlytics (using the Crashlytics fastlane action :+1: ) having an App Id similar to:
com.mycompany.ios.myapp.beta

Our app is released on App Store thus we have a "standard" Apple Dev account as well, and an App Id similar to:
com.mycompany.ios.myapp

Our Fastfile have one lane for the beta builds using the enterprise account and one lane for the App Store builds (using the Pilot fastlane action :+1: )

What I do not understand is how to make use of both Enterprise and Standard in the same project. Running 
```
match init
```
Asks me for the URL to my git repo for hosting the certs and provisioning profiles. But how do I enable support for Enterprise account as well? We should use one git repo per Apple team right? 

But how can I enter the url for the git repo for the enterprise team and the url for the git repo for the "standard team"? I guess multiple Matchfiles is not the way to go.

This setup can't be a rare corner case, I am not alone in wanting support for enterprise distribution (@Elaz [writes about it](https://github.com/fastlane/match/issues/8#issuecomment-166130605), @AdamSwinden [too](https://github.com/fastlane/match/issues/12) @nicolasbraun [as well](https://github.com/fastlane/match/issues/57) )

Any help at all would be much appreciated! Maybe it would be cool with a matchfile taking two urls for the two different git repos (standard/enterprise) as argument? 

**If I wanna contribute to the Match project with support for this, can you help me in any direction?** Thanks!

**Comment by Panajev** [comment]
Very interested in this as we have a pretty similar setup actually.

**Comment by nicolasbraun** [comment]
Hello @Sajjon,

I will not go deeply into details of our implementation here at at Applidium which has become quite complicated but basically the `match init` command only creates a Matchfile with default settings using the CLI `match` command.

In our case the only solution I found was to use fastlane to invoke match and override match settings for each of your lane. For example your lanes might look a bit like this 

```ruby

lane :store do |options|
    match(
      git_url: 'THE_GIT_URL_FOR_YOUR_STANDARD_ACCOUNT',
      type: 'appstore',
      username: 'YOUR_APPLE_ID_FOR_THE_STANDARD_ACCOUNT',
      team_id: 'YOUR_APPLE_TEAM_ID_FOR_THE_STANDARD_ACCOUNT',
      team_name: 'YOUR_APPLE_TEAM_NAME_FOR_THE_STANDARD_ACCOUNT',
      app_identifier: 'com.mycompany.ios.myapp',
      shallow_clone: false,
      readonly: true
    )
    # do some other stuff here
end

lane :inhouse do |options|
    match(
      git_url: 'THE_GIT_URL_FOR_YOUR_ENTREPRISE_ACCOUNT',
      type: 'enterprise',
      username: 'YOUR_APPLE_ID_FOR_THE_ENTERPRISE_ACCOUNT',
      team_id: 'YOUR_APPLE_TEAM_ID_FOR_THE_ENTERPRISE_ACCOUNT',
      team_name: 'YOUR_APPLE_TEAM_NAME_FOR_THE_ENTERPRISE_ACCOUNT',
      app_identifier: 'com.mycompany.ios.myapp.beta',
      shallow_clone: false,
      readonly: true
    )
    # do some other stuff here
end
```

*Attention*
Match does not officially support enterprise certificates but this solution work to READ the entreprise certificate. You still will have to manually use match in CLI to create the Distribution (enterprise) certificate and mobileprovision

`MATCH_FORCE_ENTERPRISE="1" match enterprise --app_identifier '$identifer'` (add other parameters if you like). Note that you can use the Matchfile in the repositories of your Match assets and the Fastfile in your project code repo.

Hope this helps,

Nicolas

**Comment by YayConnolly** [comment]
@nicolasbraun that was incredibly helpful, thank you.

**Comment by Sajjon** [comment]
@nicolasbraun you are the hero of the week!

Thank you very much!

I added ENV[MATCH_FORCE_ENTERPRISE] = "1" 
In the lane before match for enterprise :)

Enterprise distribution now works perfectly, but I have yet to try release builds to App Store via Pilot. But I experienced major issues yesterday, first two Builds got the status "missing compliance" - I don't know why. So I tried a third build which says ready to test, but all three builds are stuck on "Processing". I am almost certain this has nothing to do with fastlane though. I saw @KrauseFx had the same problem. I called Apple but they weren't much help :P

**Comment by sfransen** [comment]
I had one app that built with Xcode was struck for 1 week I had to call Apple to fix the problem

**Comment by Sajjon** [comment]
Thank you all for your help, especially @nicolasbraun ! :+1: Apple fixed the issue with stuck builds in iTunes connect during the weekend and I have put the app up for review, the first build ever to be signed using match, exciting indeed!

It think settting up fastlane with match will be the first thing I will do for all future iOS projects! Thanks a lot! :)
