### ISSUE TITLE
Process Multiple Apps in Single Account with Single Login

### ISSUE THREAD

**Issue by NikhilRyan** [fastlane/fastlane#3751]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi, actually it's not an Issue. fastlane is working absolutely fine. 
Just Need to know, is there any way by which we can login into a single account and process all apps in it instead of login multiple times for the same account for all it's apps.

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v): 
Do you use bundler, rbenv or rvm?
No

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (456/400 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:60080)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.86_1)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1afmgP-000ewu-D9
	for yann.dupuy@zyapps.com; Tue, 15 Mar 2016 11:58:42 +0100
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=IiXxgeCY6Oy3/Q6AVIzuU7y4kFM=; b=XNNfUhvANTIyygvl
	JCandvoB4fDSC/jklbrp9CWHsdtFTt7YJDvoa1unhu7xGpEKz/5QrwTXKHL47sk+
	bk95NuV0EnYfcWQabnFVlv8VaQ3IWMGsRR5YHX35ztq4ElNYvRrXCBwn9MA+Zv9h
	gUHQdDGtb+dYLupJXbzPKwshXcY=
Received: by filter0469p1mdw1.sendgrid.net with SMTP id filter0469p1mdw1.14009.56E7EAAF5A
        2016-03-15 10:57:51.674430982 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0001p1iad1.sendgrid.net (SG) with ESMTP id QMN1eckrQP65rO4ucxTXzw
	for <yann.dupuy@zyapps.com>; Tue, 15 Mar 2016 10:57:51.623 +0000 (UTC)
Date: Tue, 15 Mar 2016 03:57:51 -0700

**Comment by KrauseFx** [comment]
@NikhilRyan Sure thing, what tool are you talking about? You can always build something more efficient using [spaceship](https://spaceship.airforce) :+1:

**Comment by NikhilRyan** [comment]
@KrauseFx Hi, Spaceship is an awesome tool. Liked it a lot.
Please correct me if i'm wrong, what i found while going through spaceship is i can only upload metadata and set things like Category, Ratings etc. but not the IPA and Screenshots. 
Is there any way to do that ?
