### ISSUE TITLE
Supply does not publish emoji to Google Play

### ISSUE THREAD

**Issue by appfamily** [fastlane/fastlane#3752]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Supply will successfully publish a field containing emoji (e.g. title), but the emoji is incorrectly replaced by some other character representation.

Why is this important? Because titles and short descriptions containing Emoji can increase installs by 5 - 10%.

Using Cygwin with Supply.

For example:

**Desired title, in title.txt:** Hry Puzzle Auta a Vlaky 🚗

**Actual title shown on Google Play:** Hry Puzzle Auta a Vlaky ­ƒÜù

c:\cygwin64\bin\bash.exe -c "export PATH=$PATH:/usr/bin/;cd a_staged/se.appfamily.puzzle.vehicles.free;~/.gem/ruby/gems/supply-0.5.2/bin/supply -p se.appfamily.puzzle.vehicles.free -j ~/asdf.json --skip_upload_apk 1 --skip_upload_images 1 --skip_upload_screenshots 1"

`
+-------------------------+------------------------------------------------------------------------+
|                                     Summary for supply 0.5.2                                     |
+-------------------------+------------------------------------------------------------------------+
| package_name            | se.appfamily.puzzle.vehicles.free                                      |
| json_key                | /home/Per/dropbox/General/Keys/GooglePlayAndroidDeveloper-374b0d3dd... |
| skip_upload_apk         | true                                                                   |
| skip_upload_images      | true                                                                   |
| skip_upload_screenshots | true                                                                   |
| track                   | production                                                             |
| rollout                 | 1.0                                                                    |
| metadata_path           | ./metadata                                                             |
| skip_upload_metadata    | false                                                                  |
+-------------------------+------------------------------------------------------------------------+

[13:22:38]: Fetching a new access token from Google...
[13:22:39]: Preparing to upload for language 'cs-CZ'...
[13:22:40]: Uploading all changes to Google Play...
[13:22:44]: Successfully finished the upload to Google Play
`

### Configuration Files

No such file, I just use Supply

### Environment

fastlane version (fastlane -v): supply 0.5.2
Do you use bundler, rbenv or rvm? No

**Comment by appfamily** [comment]
The string is encoded as UTF-8, as far as I can tell from some extra logging in the Supply files. And it prints correctly to the console.

When using a Java tool built around the Google Play Publisher API it works as expected, writing the emoji correctly..

**Comment by asfalcone** [comment]
@appfamily Can you give this a try with `supply` 0.6.1? We made some encoding fixes! Let me know!

**Comment by appfamily** [comment]
Works now, thank you!
