### ISSUE TITLE
operation_failed error when submitting for beta review or distributing external [spaceship]

### ISSUE THREAD

**Issue by revile** [fastlane/fastlane#3768]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When attempting to submit a build for beta review via Spaceship I get an error. This also occurs when trying to distribute an approved build to TestFlight external

##### Complete output when running fastlane, including the stack trace and command used

I'm generally using this from fastlane, but the same issue happens using the spaceship playground, so that is where this output is from:
```ruby
[38] pry(main)> train = app.build_trains["2.3.0"]
=> <Spaceship::Tunes::BuildTrain
	application=<Spaceship::Tunes::Application
		apple_id="xxx",
		name="xxx",
		vendor_id="xxx",
		bundle_id="x.x.x.x",
		last_modified=1458018255000,
		issues_count=0,
		app_icon_preview_url="http://blah">>
[39] pry(main)> build = train.latest_build
=> <Spaceship::Tunes::Build
	build_train=<Spaceship::Tunes::BuildTrain
		application=<Spaceship::Tunes::Application
			apple_id="xxx",
			name="xxx",
			vendor_id="xxx",
			bundle_id="xxx",
			last_modified=1458018255000,
			issues_count=0,
			app_icon_preview_url="xxx">>,
	id=xxx,
	valid=true,
	build_version="26",
	train_version="2.3.0",
	processing=false,
	upload_date=1458021117000,
	icon_url="xxx",
	app_name="xxx",
	platform="ios",
	internal_expiry_date=1463205197000,
	external_expiry_date=0,
	watch_kit_enabled=false,
	ready_to_install=true,
	install_count=3,
	internal_install_count=3,
	external_install_count=0,
	session_count=3,
	crash_count=0>
[41] pry(main)> build.testing_status
=> "Internal"
[42] pry(main)> train.update_testing_status!(true, 'external')
Spaceship::TunesClient::ITunesConnectError: operation_failed
from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/tunes/tunes_client.rb:219:in `handle_itc_response'
```

Interestingly, I get this error when submitting for beta review, but the submission actually works. However, I also get the error when attempting to distribute externally (as shown above), but the action does not work.

### Environment

spaceship version 0.23.0
Do you use bundler, rbenv or rvm?
No

**Comment by calebhicks** [comment]
I _believe_ I am seeing the same thing using Deliver.

```
[15:42:30]: iTunes Transporter successfully finished its job
[15:42:30]: [Transporter]: DBG-X: Returning 0
[15:42:30]: ------------------------------------------------------------------------------------------------------
[15:42:30]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[15:42:30]: ------------------------------------------------------------------------------------------------------
[15:42:32]: Upload binary failed
[15:42:32]: fastlane finished with errors

[!] Upload binary failed
```

Then my `error do |lane, exception|` block executes.

**Comment by revile** [comment]
This doesn't work for distributing internal builds anymore either (it worked yesterday). I'm wondering if there is something I'm missing and my builds/trains are not in the correct state somehow? Although logging in to the iTC website and doing the same action manually works without issues.

**Comment by RocketPop** [comment]
I literally just updated to deliver 1.10.4 and now I get the same error as @calebhicks where the build works, upload succeeds then I get:
```
[17:47:36]: [Transporter]: INFO: The package: /tmp/1083717043.itmsp has been successfully uploaded.
[17:47:37]: iTunes Transporter successfully finished its job
[17:47:37]: [Transporter]: DBG-X: Returning 0
[17:47:37]: ------------------------------------------------------------------------------------------------------
[17:47:37]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[17:47:37]: ------------------------------------------------------------------------------------------------------
[snip]
[17:47:39]: Upload binary failed
[17:47:39]: fastlane finished with errors

[!] Upload binary failed

**Comment by revile** [comment]
Ok I've done a lot more digging, by comparing the request sent via the website and the one sent by spaceship.

I found that spaceship submits a whole bunch more data than the website did to distribute an app internally.

The following keys appear in the data hash passed to `TunesClient::update_build_trains!` but are missing from the website equivalent:
```
sectionErrorKeys
sectionInfoKeys
sectionWarningKeys
processingBuilds
availableExportCompliances
currentTestingApps
maxTestingApps
isBetaDataAvailable
dailySubmissionCount
dailySubmissionCountByPlatform
```

I tested removing these and eventually found that just removing `dailySubmissionCountByPlatform` fixed my issue and the build was distributed internally.

**Comment by revile** [comment]
I've now tested this for all the actions I had issues with (internal distribution, submitting for beta review and external distribution) and the fix mentioned above works for all of them.

**Comment by Philluxx** [comment]
I can confirm this. The build is uploaded to ITC successfully, but could not been selected. Deliver stops with "Upload binary failed"

**Comment by asfalcone** [comment]
deliver 1.10.5 should fix the erroneous `[!] Upload binary failed` problem! :rocket:

**Comment by revile** [comment]
The fix is not the same issue I am having

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (478/400 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:50943 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKto-002llJ-8f
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:20 +0200
Date: Sat, 18 Jun 2016 11:22:35 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274155;
	bh=RcVDjRAW/U8SUyvC5wOEgKkEAsMSw800aTX6JbmpJUg=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=hENFyM5heeNG5Igk442DxlluzEwT56rVWKVuhSNIm3gs987TApTRDNv4nzwmUG8wl
	 +Rj8oExsa/H/Nm/LzdYkV0HnXusyCxo0ItPFO2n4vVAgC0ki2VRBE6zgdyTaSQRrML
	 jWFnkzsUiUd3XNWMvwuxHjxlClqQneV6Odb0PPXk=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (479/400 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:19611)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKtr-002llv-20
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:24 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=RlnjghwO3ga6b5yefSoycUDE0E8=; b=I3eEfa2IwdzzSjZx
	tAs8VKOfejaPz3tjKA8Q4YiZh4aNuonRA08MQQgMheFoqO79MMMnjTt/a8nQKD/p
	T593ZeflspP1k3y6wSM4r+l31y3IyPLDnBA9wn1Q19wBZe9VLqK0F1tGqL8auJiF
	l0gAnp/mhwV5YvzeQWXj2lqtSEo=
Received: by filter0843p1mdw1.sendgrid.net with SMTP id filter0843p1mdw1.22258.5765916B29
        2016-06-18 18:22:35.593614893 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id I6by77VJQEyupMg--rOtCg
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:22:35.479 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:22:35 -0700
