### ISSUE TITLE
submit_for_beta_review! submits the placeholder information if none is specified [spaceship]

### ISSUE THREAD

**Issue by revile** [fastlane/fastlane#3771]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`Build::submit_for_beta_review!` in spaceship submits the placeholder information if none is specified.

```ruby
def submit_for_beta_review!(metadata)
        parameters = {
          app_id: self.apple_id,
          train: self.train_version,
          build_number: self.build_version,
          platform: self.platform,

          # Required Metadata:
          changelog: "No changelog provided",
          description: "No app description provided",
          feedback_email: "contact@company.com",
          marketing_url: "http://marketing.com",
          first_name: "Felix",
          last_name: "Krause",
          review_email: "contact@company.com",
          phone_number: "0123456789",
          significant_change: false,

          # Optional Metadata:
          privacy_policy_url: nil,
          review_user_name: nil,
          review_password: nil,
          encryption: false
        }.merge(metadata)

        client.submit_testflight_build_for_review!(parameters)

        # Last, enable beta testing for this train (per iTC requirement). This will fail until the app has been approved for beta testing
        self.build_train.update_testing_status!(true, 'external', self)

        return parameters
      end
```

These fields don't _seem_ to be required. My understanding is this data is mostly pulled through from the store submission and pre-filled for you. I commented most of these out (except the top 4, obviously) and started getting an error: `Review Notes are required`

I added the option to specify review notes (with a placeholder) and now everything seems to work fine. 

I am confused by the comment and code at the bottom of this function though, can someone explain why we attempt to submit the build for external testing when we just submitted it for review? Won't this always fail? Is this some kind of special handling for when we specify no significant changes and the build is immediately available?

### Environment

spaceship 0.23.0

**Comment by revile** [comment]
Looking in to this a bit further, with my fix for #3768, I now always get the `Review Notes are required` error, whereas previously I would get `operation_failed`

**Comment by kikolobo** [comment]
I am using Pilot to deliver for beta testing to TestFlight. What do I need to add to my Fastfile to submit for beta review, and if possible select as beta for testing?

Any help would be great! Or point me in the right direction.

**Comment by vpolouchkine** [comment]
@kikolobo This looks like a different problem, would you mind creating a new Issue? Thanks!

**Comment by revile** [comment]
@vpolouchkine my PR for this has been merged, this can be closed now :+1:

**Comment by revile** [comment]
FYI this is fixed in #3789, which AFAIK is ready for merge.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (480/400 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:45372 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtt-002lnJ-Rt
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:26 +0200
Date: Sat, 18 Jun 2016 11:22:40 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274160;
	bh=xKnAdanGResUHqGOKXqWZUBqslcJ4CoiuDoxHQpETQE=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LqFaY5uqPknONFpmxuxXI+eTj0Gr6oK8f8PxZpxTGER4tskFnV9y1KlZKNymRAXnh
	 2kOClQvlWu2NSfEzdT2wygQcPMbz6yS5eJIgvW5ghKe5qNsxTPNT+p6XpYdOQjrU6d
	 UD0whGBKpZ8jRYfGn4x4/Cwomaq8W/h95bQ8Hbhc=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (481/400 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:51829 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtu-002lnT-3e
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:28 +0200
Date: Sat, 18 Jun 2016 11:22:40 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274160;
	bh=5zWYBlgrEZwwKnWObPcGZg3Mfih+kbbW5L7xmt3G974=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=MNJcoWdug+oV0xDVZ32hei1B/jTNywuC1WwTD4fnQ9ANHT7IdAWU7CKKXd/Pqv8Mm
	 o9wFr55V23SKrDG9gjNvi0oWvxPhIfekVYAhpjQfBXy8M+FFFjuTQR0H0QFgen1/zn
	 DFxUJc2Vt1YxNGnhjKXJgla3m4OAguSOx457eQ9M=
