### ISSUE TITLE
Add the possibility of specifying a reporter for the swiftlint action

### ISSUE THREAD

**Issue by vittoriom** [fastlane/fastlane#3773]
### Issue Description

I'm using the swiftlint action to generate a violations report. The `.swiftlint.yml` config already contains all the rules (that I don't want to duplicate) but is setup with a "xcode" reporter so that it's nicely integrated in Xcode during the development phase. 

I now want to setup a lint lane that outputs a "checkstyle"-like report to display the results in Jenkins.

My `Fastfile` excerpt is the following:

```
swiftlint(
      mode: :lint,
      output_file: 'swiftlint.result.json',
      reporter: 'checkstyle'
)
```

##### Complete output when running fastlane, including the stack trace and command used

The obvious output is:

```
fastlane finished with errors

[!] Could not find option 'reporter' in the list of available options: mode, output_file, config_file, strict, files
```

### Environment

fastlane version (fastlane -v): **1.66.0**
Do you use bundler, rbenv or rvm? **Bundler**

### Conclusion

It would be nice if the `swiftlint` action could accept a `reporter` option to override the reporter (it's [already supported](https://github.com/realm/SwiftLint/pull/495) by `swiftlint`

**Comment by ohwutup** [comment]
Hey @vittoriom, this would be a great addition to the `swiftlint` feature. We would be happy to review a pull request with this added functionality if you want to give it a go? I am going to close this issue for now and will reopen it when we can get around to adding this option, but please feel free to reopen it yourself and submit a PR with the changes! That would be 💯 !
