### ISSUE TITLE
Keep fastlane Up to Date on travis

### ISSUE THREAD

**Issue by PoissonBallon** [fastlane/fastlane#3775]
### Issue Description

Hi guys, I search a way to keep up to date fastlane on Travis Builder but without make update at every build.

For example, by default the Fastlane version on Travis is 1.53 but if i want update to 1.66 my build make a very long time (+20min) 

Thx for your help.

ps : maybe it's a question for Travis team ? :s

**Comment by KrauseFx** [comment]
Yeah, please contact Travis to include the latest fastlane version. Also, make sure to use the latest osx image on Travis :+1:
