### ISSUE TITLE
Deliver: add preview upload

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#3779]
# Description:

spaceship supports uploading preview video, a feature only available on safari right now.

We want to integrate this into deliver.

Related to #2251 (cc @Ged2323).
See also #1690

Spaceship supports 2 modes:
- with a given preview image
- without. In this case it will generate one using ffmpeg tools.

At start we want to only support the use case of the user specifying the preview image. Because we assume ffmpeg might not be present. 

Care needs to be taken to support the new sync infra (using MD5). Take care of looking how that affects the preview image upload as well.
# Questions:
- should the preview video have its own skip parameter ?
# Scenarios:

if we are not skipping videos:
- preview video and image are available and not yet . Automatically upload them
- preview video has already been uploaded, but image has changed. Update the image.
- preview video and images have already been uploaded. Do nothing.
- one of 2 preview video and image is missing. UI.user_error! (before we start uploading anything)
- preview.html should contain the preview image in a new video section (unless skip_preview_video I guess ? check how other section are filled in or not).
  *\* BONUS would be to use some CSS magic to show a player button but that's not necessary or link to the local video using HTML5 :) 
# Future ideas:
- we might expose the extraction of the image through deliver. We could add to spaceship `Utilities.can_extract_video_preview?` or something like that to detect the feature and fail up front.
- We could also provide the extraction of the video preview as a fastlane action. I don't personally need that.
# Notes:

we're starting on this.

**Comment by marat00** [comment]
Are there any updates on this issue? Maybe you could corner the Apple guys during WWDC and ask them if they plan to add support for this? I was trying to implement this using SafariDriver, but I am not sure if it possible.

**Comment by lacostej** [comment]
@marat00 it s implemented. We are finalizing the PR.

**Comment by KrauseFx** [comment]
@marat00 Please don't corner anyone at Apple for this. There is no public API, and Apple doesn't plan on adding one. @lacostej already found out how to use the underlying API, so we're good 👍

**Comment by marat00** [comment]
@lacostej, @KrauseFx, thanks guys. I was thinking of trying to use the DUClient interface to do that, but did not have time to test it. Look forward to full support of video upload functionality.

**Comment by KrauseFx** [comment]
@marat00 As far as I know, you can already upload app videos using spaceship directly, you might want to check out the code base 👍

**Comment by marat00** [comment]
@KrauseFx, I was trying to do that, but the underlying code is not simple, and it would take some effort to integrate it with Jenkins and the HTML generator that you use for deliver. Plus, there is very limited documentation or code examples on video uploads if any.

**Comment by TKBurner** [comment]
@marat00 Thanks for following up. I'll mark this as help wanted to see if anyone wants to step in. Thanks!

**Comment by teffi** [comment]
Has this been integrated already? So far I can't find any official document that mentioned this.

**Comment by teffi** [comment]
After digging deeply, I was able to figure this one out by using Spaceship 'upload_trailer!' method.

**Comment by srudoi** [comment]
When using 'upload_trailer!' method, I have the following error:

`RuntimeError: iTunes Connect error: Unexpected state: missing device details for iphone6Plus
from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/tunes/app_version.rb:546:in `rescue in container_data_for_language_and_device'`

I am of course specifying device types correctly; what is more, it works perfectly when uploading screenshots, and the problem seems to be restricted to uploading app trailers.

**Comment by TKBurner** [comment]
@srudoi Thanks for following up on this. We don't currently directly support trailer upload, but we'd love to see a pull request to improve support. Thanks!
