### ISSUE TITLE
add_photos / add_videos (add_media) enhancement suggestion

### ISSUE THREAD

**Issue by ddilley** [fastlane/fastlane#3784]
First of all, thank you so much for your quality work. I may be missing something obvious here (This is my first time giving feedback on GitHub). When using add_photos and/or add_videos within my tests I noticed that if there are multiple tests per language that run on the same device, add_media adds the media for every test that is ran due to the simulator being restarted for each test. I could simply reduce my tests to a single test function to remedy this, but best practices prefer modularized tests that can run independently of each other. This remedy would not address test Failures that are ran again per number_of_retries_due_to_failing_simulator as for every time the test fails where the media is added again for every retry.

**Comment by ohwutup** [comment]
Hey @ddilley! Apologies for the slow response here, thanks for submitting the feedback. Are you still having this issue? Are there any other ways around this that you can think of? Would you mind sharing your Fastfile and Snapfile so I can get a bit of a better understanding of what you are working with?
