### ISSUE TITLE
How to use Fastlane to setup and publish an iOS app from an online form / a web app ? 

### ISSUE THREAD

**Issue by batistomorrow** [fastlane/fastlane#3795]
Hi,
First time here ! I am really interesting by the fastlane tools suite, and I would like to know if it can fit my specific needs. I am a quite a newbie when it comes to something else than iOS/Android, so I apologize if I am asking a silly question. Here it goes : 

I’ve developed a native app on both iOS and Android. I sell the app to gym facilities. For every new client (that is, every new gym) I (re)use the same source code. I just create the app entity in iTunesConnect, Google Dev Console, change the bundleID etc. in the code, and I publish the app. So basically I have the same project, and I juste change the bare minimum before publishing each new app. Once the app is published, its gets customized in real-time thanks to my server hosted on heroku. 

I had like to automate as much as possible this process. Ideally, I would like to create a web app with a single front-end that a non-developer could use to setup a new app from scratch. That is, this non-developer person would fill fields like the name of the club, upload its picture, etc. and using the same approach as you did, a script would take everything and publish the app. In short, centralize in one place, one moment, all I use to do in order to publish a new app from the same source code. 

If I am not mistaken, the tools suite you’ve developed is more geared towards managing several different apps, but what if in my case I have like +70 apps online ? Does it stil make sense to maintain local repositories on my mac for each app ? 
I guess the best approach would be to use Spaceship, the Ruby tool you’ve designed, as the ‘engine’ behind a front-end that I would develop. Am I on the right track ? I am completely new to Ruby.

Any advice would be greatly appreciated !

Thanks

**Comment by vpolouchkine** [comment]
"I had like to automate as much as possible this process." This is pretty straightforward with `produce` and `deliver`. 

"If I am not mistaken, the tools suite you’ve developed is more geared towards managing several different apps, but what if in my case I have like +70 apps online ?" No, fastlane can support any number of apps.

"Does it stil make sense to maintain local repositories on my mac for each app ? " You should probably keep the same structure you're using right now. 

"I guess the best approach would be to use Spaceship, the Ruby tool you’ve designed, as the ‘engine’ behind a front-end that I would develop. Am I on the right track ?" No, you probably should call `produce` and `deliver`.

**Comment by calebhicks** [comment]
I do something similar with a combination of an API call, environment variables, `produce`, `pilot`, and `deliver`. I use the update_info_plist action and some custom Ruby code to set up the project file before setting up the build.

Definitely doable with Fastlane and the other tools, as @vpolouchkine suggests.

**Comment by KrauseFx** [comment]
Also, make sure to check out https://github.com/fastlane/examples
