### ISSUE TITLE
Avoid updating README.md with Match and match --force 

### ISSUE THREAD

**Issue by cepages** [fastlane/fastlane#3796]
I'm using match to update my provisioning profile.

Because someone added a new device in the Dev Center, I would like to update my provisioning profiles, so I'm using:

```
match --force adhoc
```

But this reset the README.md file in my repository.

I found I can skip when fastlane create the documentation with the action [skip_docs](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#skip_docs).
So I created this lane:

```
lane :force_provisioning_update do

     skip_docs
     match(type: "adhoc", app_identifier: "app_identifier", force: true)
end
```

Probably in this case I wouldn't need ```force``` so I can do it with ```force_for_new_devices```

But if I need to regenerate the provisioning profile because it's missing I will need ```force```

The problem is this still resets my README.md, is there a way to avoid updating this file but keep updating the provisioning profile and/or certificates in my repo?

Thanks

**Comment by mfurtak** [comment]
Hi @cepages - thanks for the report! :+1: 

Can you try placing `skip_docs` at the top of your `Fastfile` like:

```ruby
skip_docs

lane :force_provisioning_update do
     match(type: "adhoc", app_identifier: "com.incuna.ePatientDiabetesCoach", force: true)
end
```

and let me know if that works?

**Comment by cepages** [comment]
Hi @mfurtak 

I tried with:

```
skip_docs
lane :force_provisioning_update do
    match(type: "adhoc", app_identifier: "app_identifier", force: true)
end
```
It does the skip_docs but the README file in the certificate repo is replaced. 

```
[14:56:37]: -------------------------------------------------
[14:56:37]: --- Step: Verifying required fastlane version ---
[14:56:37]: -------------------------------------------------
[14:56:37]: fastlane version valid
[14:56:37]: ------------------------------
[14:56:37]: --- Step: default_platform ---
[14:56:37]: ------------------------------
[14:56:37]: -----------------------
[14:56:37]: --- Step: skip_docs ---
[14:56:37]: -----------------------
[14:56:37]: Driving the lane 'ios force_provisioning_update' 🚀
[14:56:37]: -------------------
[14:56:37]: --- Step: match ---
[14:56:37]: -------------------
```

**Comment by mfurtak** [comment]
Oh! I think I'm finally understanding... It's the README in the git repo used by `match` that is getting affected, is that right?

**Comment by cepages** [comment]
@mfurtak Yeah, that's it. Sorry, my bad.

**Comment by mfurtak** [comment]
No problem at all. 😀  Thanks for the report :+1:

**Comment by KrauseFx** [comment]
Correct! `skip_docs` is just for the `fastlane` docs. Why do you not want the `match` README in your repo?

**Comment by cepages** [comment]
@KrauseFx when I run ```match --force``` ( and when I run match the first time) match adds a README.md in my certificate repository which describes how to use match.

I've edited that README.md with extra information, but each time I run again ```match --force``` my custom README.md is replaced with the default one

I would like to keep my custom README.md

I guess I was expecting a ```skip_docs``` parameter in match or something like that, do you know what I mean?

**Comment by mfurtak** [comment]
@cepages Good idea! I hope to have happy news soon! :gift:

**Comment by cepages** [comment]
@mfurtak Thanks!! :)

**Comment by KrauseFx** [comment]
Merged with https://github.com/fastlane/fastlane/pull/3811, this will be in the next fastlane release :+1:
