### ISSUE TITLE
Hanging build in iTunes Connect blocks TestFlight uploading flow

### ISSUE THREAD

**Issue by daanporon** [fastlane/fastlane#3800]
### New Issue Checklist

- [V ] Updated fastlane to the latest version
- [V ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Uploading of the ipa file to iTunes connect keeps waiting for the build to be processed. The reason for this is that we have an older build that hangs in iTunes Connect and there is no way of cancelling/removing this build (it's already being processed for a week now). I already sent an email to Apple to discuss this problem but until now they didn't respond. I think i'm not the only one that has this problem, isn't it possible to make Fastlane (Pilot) smarter? Right now it keeps waiting until all builds are processed (https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L74), maybe we can only wait until the build that we just uploaded is processed. I already looked at the code but i have no idea how i can find the Version / Build number that was currently uploaded? If anyone can put me in the right direction maybe i can create a PR for this.

**Comment by pesterhazy** [comment]
Seeing the same issue @daanporon: we have a bunch of TestFlight builds in the queue that are all marked as "processing", blocking a new submission. In the past bumping the marketing version worked, but that doesn't seem to help this time. I don't actually see a problem with pilot (I'm using `skip_submission`, which may be relevant).

Could the submission failure be a result of the way pilot uploads the build? I'm using this setting

```
ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
```

The underlying issue is clearly on Apple's side, but it'd be interesting how other fastlane users get around this deficiency.

**Comment by KrauseFx** [comment]
The last few days Apple's processing time was much slower than usually, there is not much we can do unfortunately. 
You can always skip the submission so that fastlane tools don't wait for the build to be finished processing.

**Comment by daanporon** [comment]
Wouldn't it be better to just wait for all processing builds with the same version number and build number? In stead of waiting for all the builds to be completed ... 

But for this to work we need to export the build number and version number in an earlier action i suppose ... maybe the gym action? I think this will be more stable at least ..

**Comment by gabek** [comment]
I was seeing this same thing, and it waiting for old, failed, builds explains things.  But it is a bummer, since these old builds will never complete processing.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (482/400 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:52695 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKtz-002lox-HH
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:31 +0200
Date: Sat, 18 Jun 2016 11:22:46 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274166;
	bh=ASYMOM0NT0Aa97KscGMBrh3ejOu8OMhiZXZ2pIo4Acw=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Q8V4xPcPvvGWhGj6By8vuI8xjZyr4YFI5UEWT3YhKMsH3AKhJdU+FxoC4M3LYirBR
	 W8+WFftIJVrFYOEn8xrxtuytMozDo1Z/kmLUF4B1VzMxJWyB/U1DSy6/vvKrEP053Q
	 P5Jmxdfbqi/oye5noAR3FfVMjqLY5+yewqTZ3O3E=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (483/400 (120%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:28902)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKu2-002lp8-2n
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:32 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=M3WWFUMaPijkOyl/3beUAhaYtbo=; b=Sd+XwhQaUYQDAGKj
	gVhIaUW/oxlsalPwcXiTqHCcAHAW6DyuaFpgmGj74AzkiPgH7kqO5be0Y6o3TJOK
	PnPNpR91cyg1ceR/V001aHCmuy66meKfFYDL1uQ1W3e9aEnCnRozbC3ymXetY6YX
	OfEh7O3Wh7TG5m/P0AVZZ5BfON4=
Received: by filter0843p1mdw1.sendgrid.net with SMTP id filter0843p1mdw1.22258.576591761A
        2016-06-18 18:22:46.353999491 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id Hxt6Laq7SvuBr5aKH62-5Q
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:22:46.314 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:22:46 -0700
