### ISSUE TITLE
How to list all existing certificates (by id)?

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#3802]
Hi guys,

Is there a command available in `cert` that lets me see the id's of all my available certificates on iTC?

Thanks,

**Comment by mfurtak** [comment]
Hi @pedro380085 - great question! :+1: 

`cert` doesn't provide a way to do this directly. You probably want to have a look at [spaceship](https://github.com/fastlane/fastlane/tree/master/spaceship), which is the API that powers `cert` for talking to iTC.

Some Ruby like:

```ruby
require 'spaceship'

Spaceship.login('your@email.addr')
puts Spaceship.certificate.production.all
```

might get you on the right track. Happy coding! :tada:

**Comment by pedro380085** [comment]
thanks @mfurtak !
