### ISSUE TITLE
ipa build command add option to return .app file

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#381]
I am trying to use ipa to build the app and use it with xcrun simctl for som custom scripting to preload the app with data by running the app and copy data from the installed location. Most of it works but I am left with one problem that it is not possible to get an .app file from the ipa command that I need for this command: 
xcrun simctl install booted path/to/app.app

Is it possible to add an option to the ipa command to exportApp and then add an app file name?

(And I guess I am not the only one that could use that feature)

**Comment by KrauseFx** [comment]
You can use the `xcodebuild` action instead to have full control. Let me know if that helps.

**Comment by 7mllm7** [comment]
Yeah but wouldn't it be useful to have a separate action to for running in simulator?
It can either be as independent action or as a parameter to ipa().
What do you say? worth featuring?

**Comment by KrauseFx** [comment]
@7mllm7 is this relevant to @mortenholmgaard's issue?

**Comment by 7mllm7** [comment]
It does as he's trying to get .app file in order to run in simulator.
So if it's not already straight forward with `xcodebuild` like @mortenholmgaard is trying, then I can happily start a new feature.

**Comment by KrauseFx** [comment]
Oh, right, sorry I misunderstood that part. That's basically what `snapshot` does already. @7mllm7 feel free to add a new option and submit a pull request :+1:

**Comment by KrauseFx** [comment]
Keep in mind, the `ipa` action generates a build for distribution (= real device) which can't be run on the simulator.

**Comment by mortenholmgaard** [comment]
@KrauseFx could you add an argument to gym to export an .app?

**Comment by KrauseFx** [comment]
I recommend you use the new `gym` action instead of the `ipa` one. 

@mortenholmgaard Sorry, that feature is not planned. You can easily unzip a `ipa` file and get the containing `.app`

**Comment by mortenholmgaard** [comment]
Okay - I didn't know - I will look into that.

**Comment by ohwutup** [comment]
looks like there hasn't been any activity on this issue in quite some time. I'm going to close it for now, but please feel free to reopen if there are still problems! :+1:
