### ISSUE TITLE
Installation problem on windows10 : EINVAL

### ISSUE THREAD

**Issue by kooroshh** [fastlane/fastlane#3829]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
GET https://api.rubygems.org/api/v1/dependencies?gems=unf_ext
200 OK
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gym-1.6.2/LICENSE
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gym-1.6.2/README.md
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gym-1.6.2/bin/gym
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument - C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/gym-1.6.2/bin/p*
```

### Environment
ruby 2.0.0p0 (2013-02-24) [x64-mingw32]

**Comment by vpolouchkine** [comment]
Unfortunately, as of today, Windows is not officially supported.
