### ISSUE TITLE
 How to use the match to synchronize all certificates

### ISSUE THREAD

**Issue by elianfish** [fastlane/fastlane#3833]
### Issue Description
New machine

To set up the certificates and provisioning profiles on a new machine, you just run the same command using:

match development

---------------------------
Only synchronize a certificate in accordance with the above command is executed. I have multiple Git repository, for each repository there are multiple bundle identifie, my how time synchronization of all?

### Environment
match 0.3.0

**Comment by vpolouchkine** [comment]
I believe you can pass `--app_identifier`.

**Comment by elianfish** [comment]
There are multiple app identifier. Be sure to specify the right one?

**Comment by nicolasbraun** [comment]
You can use fastlane to invoque `match`many time.
A very simple Fastfile might look like this

```ruby

lane :get_all_codesign_stuff do |options|
  bundles = ["com.app.one", "com.app.two", "com.app.three"]
  bundles.each do |bundle|
    match(
      app_identifier: bundle,
      username: "YOUR_USERNAME",
      git_url: "GIT_URL"
      type: "development"
    )
  end
end
```

**Comment by KrauseFx** [comment]
Thanks for jumping in @nicolasbraun, I'll close this issue for now 👍
