### ISSUE TITLE
User should be able to define languages he wants to deliver

### ISSUE THREAD

**Issue by SebastianBoldt** [fastlane/fastlane#3834]
### Issue Description
One thing that is really annoying is that the ITC Api frequently responses with the following message. 
`ITC temporary save error received: 'We're temporarily unable to save your changes. Please try again later.'. Retrying after 60 seconds (remaining: 4)...` when uploading a lot of localized screenshots

This will cause the deliver process to cancel and you need to start it again.
To skip the languages you already uploaded, you need to remove them from the screenshots folder.

An option which lets you define the languages you want to upload would be the perfect solution to prevent this aggravation.

For example : `deliver en-US`

##### Output

```ITC temporary save error received: 'We're temporarily unable to save your changes. Please try again later.'. Retrying after 60 seconds (remaining: 4)```

### Configuration Files
Fastfile:
```ruby
default_platform :ios

platform :ios do
  before_all do
    ENV["FRAMEIT_WHITE_FRAME"] = "white"
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # increment_build_number
    # xctool # run the tests of your app
  end

  desc "Runs all the tests, makes screenshots and frames them"
  lane :ffx_appstore do
    cocoapods
    snapshot
    frameit(white: true)
    deliver
  end
  
  lane :ffx_framed_snapshots do
    cocoapods
    snapshot
    frameit(white: true)
  end

  lane :ffx_frameit do
    frameit(white: true)
  end

  lane :ffx_deliver do
    deliver
  end
  
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cocoapods
    sigh
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    cocoapods
    snapshot
    sigh
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```

### Environment
fastlane 1.66.0

**Comment by KrauseFx** [comment]
Which version of `spaceship` do you use? `gem list --local | grep "spaceship"` or in your `Gemfile.lock` if you use bundler. Make sure to update to the latest version. @lacostej has worked on some great improvements the last weeks :+1:

**Comment by SebastianBoldt** [comment]
This is the related output to the command you posted:
`spaceship (0.21.0, 0.19.3, 0.18.0)` .. so I think i am on 0.21.0

**Comment by jfresen** [comment]
I recently submitted a pull request precisely to remedy this problem, but with a more automated approach. Instead of manually having to submit which languages you want to upload (actually: retry), the upload process keeps track of the successful uploads and if you supply the option `--skip_uploaded_screenshots` it will skip all previously successfully uploaded languages. See #3747

**Comment by SebastianBoldt** [comment]
@jfresen Sounds great :+1:

**Comment by fulldecent** [comment]
Perhaps this can be improved further:

 * `snapshot` will save the sha1 sum into the filename
 * `deliver` will check if iTC already has that filename
 * By *DEFAULT* `deliver` will skip files that iTC already has
