### ISSUE TITLE
Snapshot: waitForLoadingIndicatorToDisappear() hangs if an alarm is on

### ISSUE THREAD

**Issue by elimelec** [fastlane/fastlane#3837]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm running the UI Tests from Xcode, on a real device. If I turn on an alarm, a new icon appears on status bar and when it tries to snapshot, it will hang on waitForLoadingIndicatorToDisappear(). If I turn off the alarm, it works fine.

I created a simple test project: https://github.com/elimelec/snapshot-hang 

Direct link to the UI Test file: https://github.com/elimelec/snapshot-hang/blob/master/SnapshotHangUITests/SnapshotHangUITests.swift

##### Complete output when running UI Tests from Xcode (cmd + u) with an alarm turned on:

		2016-03-21 14:48:59.407 XCTRunner[3762:1356326] Running tests...
		2016-03-21 14:48:59.410 XCTRunner[3762:1356326] Looking for test bundles in /var/mobile/Containers/Bundle/Application/8260F325-78AF-4802-97D7-3030AF8E3B17/SnapshotHangUITests-Runner.app/PlugIns
		2016-03-21 14:48:59.412 XCTRunner[3762:1356326] Found test bundle at /var/mobile/Containers/Bundle/Application/8260F325-78AF-4802-97D7-3030AF8E3B17/SnapshotHangUITests-Runner.app/PlugIns/SnapshotHangUITests.xctest
		2016-03-21 14:48:59.415 XCTRunner[3762:1356326] Looking for configurations in /var/mobile/Containers/Bundle/Application/8260F325-78AF-4802-97D7-3030AF8E3B17/SnapshotHangUITests-Runner.app/PlugIns/SnapshotHangUITests.xctest
		2016-03-21 14:48:59.421 XCTRunner[3762:1356326] Found configuration <XCTestConfiguration: 0x136d1c5f0>
							  testBundleURL:file:///Users/keepcalling/Library/Developer/Xcode/DerivedData/SnapshotHang-follyqchmwwgpxgjknxjjaycbuqu/Build/Products/Debug-iphoneos/SnapshotHangUITests-Runner.app/PlugIns/SnapshotHangUITests.xctest/
						  productModuleName:SnapshotHangUITests
								testsToSkip:(null)
								 testsToRun:(null)
						 reportResultsToIDE:YES
						  sessionIdentifier:<__NSConcreteUUID 0x136d03660> 3324E7C2-8AAB-4DE4-8654-E584C88203BB
				 pathToXcodeReportingSocket:(null)
				  disablePerformanceMetrics:no
			treatMissingBaselinesAsFailures:no
							baselineFileURL:(null)
					  targetApplicationPath:/Users/keepcalling/Library/Developer/Xcode/DerivedData/SnapshotHang-follyqchmwwgpxgjknxjjaycbuqu/Build/Products/Debug-iphoneos/SnapshotHang.app
				  targetApplicationBundleID:com.example.SnapshotHang
						   reportActivities:YES
				   testsMustRunOnMainThread:YES
		14:49:00.551 XCTRunner[3762:1356341] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
		14:49:00.665 XCTRunner[3762:1356341] _IDE_startExecutingTestPlanWithProtocolVersion:16
		Test Suite 'All tests' started at 2016-03-21 14:49:00.704
		Test Suite 'SnapshotHangUITests.xctest' started at 2016-03-21 14:49:00.707
		Test Suite 'SnapshotHangUITests' started at 2016-03-21 14:49:00.709
		Test Case '-[SnapshotHangUITests.SnapshotHangUITests testExample]' started.
			t =     0.00s     Start Test
			t =     0.01s     Set Up
		2016-03-21 14:49:01.281 XCTRunner[3762:1356326] Continuing to run tests in the background with task ID 1
		Couldn't find Snapshot configuration files at ~/Library/Caches/tools.fastlane
		Couldn't find Snapshot configuration files at ~/Library/Caches/tools.fastlane
		Couldn't find Snapshot configuration files at ~/Library/Caches/tools.fastlane
			t =     1.30s         Launch com.example.SnapshotHang
			t =     1.56s             Terminate <XCUIApplicationProcess: 0x136dcc7b0 com.example.SnapshotHang (3748)>
			t =     2.02s             Waiting for accessibility to load
			t =     5.89s             Wait for app to idle
			t =     6.40s     Get number of matches for: Children matching type Other
			t =     6.52s         Snapshot accessibility hierarchy for com.example.SnapshotHang
			t =     6.59s         Find: Descendants matching type StatusBar
			t =     6.60s         Find: Children matching type Other
			t =     6.61s         Find: Element at index 1
			t =     6.62s         Find: Children matching type Other
			t =     6.63s     Find the Other
			t =     6.63s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     6.64s         Find: Descendants matching type StatusBar
			t =     6.65s         Find: Children matching type Other
			t =     6.66s         Find: Element at index 1
			t =     6.67s         Find: Children matching type Other
			t =     6.68s         Find: Element at index 0
			t =     6.68s     Find the Other
			t =     6.68s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     6.70s         Find: Descendants matching type StatusBar
			t =     6.70s         Find: Children matching type Other
			t =     6.71s         Find: Element at index 1
			t =     6.72s         Find: Children matching type Other
			t =     6.73s         Find: Element at index 1
			t =     6.74s     Find the Other
			t =     6.74s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     6.75s         Find: Descendants matching type StatusBar
			t =     6.76s         Find: Children matching type Other
			t =     6.77s         Find: Element at index 1
			t =     6.78s         Find: Children matching type Other
			t =     6.79s         Find: Element at index 2
			t =     6.79s     Find the Other
			t =     6.80s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     6.81s         Find: Descendants matching type StatusBar
			t =     6.82s         Find: Children matching type Other
			t =     6.83s         Find: Element at index 1
			t =     6.84s         Find: Children matching type Other
			t =     6.85s         Find: Element at index 3
			t =     6.85s     Find the Other
			t =     6.86s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     6.87s         Find: Descendants matching type StatusBar
			t =     6.88s         Find: Children matching type Other
			t =     6.88s         Find: Element at index 1
			t =     6.89s         Find: Children matching type Other
			t =     6.90s         Find: Element at index 4
			t =     6.91s     Find the Other
			t =     6.91s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     6.92s         Find: Descendants matching type StatusBar
			t =     6.93s         Find: Children matching type Other
			t =     6.94s         Find: Element at index 1
			t =     6.95s         Find: Children matching type Other
			t =     6.96s         Find: Element at index 5
		Waiting for loading indicator to disappear...
			t =     7.98s     Get number of matches for: Children matching type Other
			t =     8.08s         Snapshot accessibility hierarchy for com.example.SnapshotHang
			t =     8.13s         Find: Descendants matching type StatusBar
			t =     8.14s         Find: Children matching type Other
			t =     8.14s         Find: Element at index 1
			t =     8.15s         Find: Children matching type Other
			t =     8.16s     Find the Other
			t =     8.16s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     8.17s         Find: Descendants matching type StatusBar
			t =     8.18s         Find: Children matching type Other
			t =     8.19s         Find: Element at index 1
			t =     8.20s         Find: Children matching type Other
			t =     8.21s         Find: Element at index 0
			t =     8.21s     Find the Other
			t =     8.21s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     8.22s         Find: Descendants matching type StatusBar
			t =     8.23s         Find: Children matching type Other
			t =     8.24s         Find: Element at index 1
			t =     8.25s         Find: Children matching type Other
			t =     8.26s         Find: Element at index 1
			t =     8.26s     Find the Other
			t =     8.26s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     8.28s         Find: Descendants matching type StatusBar
			t =     8.29s         Find: Children matching type Other
			t =     8.29s         Find: Element at index 1
			t =     8.30s         Find: Children matching type Other
			t =     8.31s         Find: Element at index 2
			t =     8.32s     Find the Other
			t =     8.32s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     8.33s         Find: Descendants matching type StatusBar
			t =     8.34s         Find: Children matching type Other
			t =     8.35s         Find: Element at index 1
			t =     8.35s         Find: Children matching type Other
			t =     8.36s         Find: Element at index 3
			t =     8.37s     Find the Other
			t =     8.37s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     8.38s         Find: Descendants matching type StatusBar
			t =     8.39s         Find: Children matching type Other
			t =     8.40s         Find: Element at index 1
			t =     8.40s         Find: Children matching type Other
			t =     8.41s         Find: Element at index 4
			t =     8.42s     Find the Other
			t =     8.42s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     8.44s         Find: Descendants matching type StatusBar
			t =     8.44s         Find: Children matching type Other
			t =     8.45s         Find: Element at index 1
			t =     8.46s         Find: Children matching type Other
			t =     8.47s         Find: Element at index 5
		Waiting for loading indicator to disappear...
			t =     9.48s     Get number of matches for: Children matching type Other
			t =     9.59s         Snapshot accessibility hierarchy for com.example.SnapshotHang
			t =     9.63s         Find: Descendants matching type StatusBar
			t =     9.63s         Find: Children matching type Other
			t =     9.64s         Find: Element at index 1
			t =     9.65s         Find: Children matching type Other
			t =     9.66s     Find the Other
			t =     9.66s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     9.67s         Find: Descendants matching type StatusBar
			t =     9.68s         Find: Children matching type Other
			t =     9.69s         Find: Element at index 1
			t =     9.70s         Find: Children matching type Other
			t =     9.71s         Find: Element at index 0
			t =     9.71s     Find the Other
			t =     9.72s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     9.73s         Find: Descendants matching type StatusBar
			t =     9.74s         Find: Children matching type Other
			t =     9.74s         Find: Element at index 1
			t =     9.75s         Find: Children matching type Other
			t =     9.76s         Find: Element at index 1
			t =     9.77s     Find the Other
			t =     9.77s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     9.78s         Find: Descendants matching type StatusBar
			t =     9.79s         Find: Children matching type Other
			t =     9.80s         Find: Element at index 1
			t =     9.80s         Find: Children matching type Other
			t =     9.81s         Find: Element at index 2
			t =     9.82s     Find the Other
			t =     9.82s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     9.83s         Find: Descendants matching type StatusBar
			t =     9.84s         Find: Children matching type Other
			t =     9.85s         Find: Element at index 1
			t =     9.85s         Find: Children matching type Other
			t =     9.86s         Find: Element at index 3
			t =     9.87s     Find the Other
			t =     9.87s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     9.88s         Find: Descendants matching type StatusBar
			t =     9.89s         Find: Children matching type Other
			t =     9.89s         Find: Element at index 1
			t =     9.90s         Find: Children matching type Other
			t =     9.91s         Find: Element at index 4
			t =     9.91s     Find the Other
			t =     9.92s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =     9.93s         Find: Descendants matching type StatusBar
			t =     9.93s         Find: Children matching type Other
			t =     9.94s         Find: Element at index 1
			t =     9.95s         Find: Children matching type Other
			t =     9.96s         Find: Element at index 5
		Waiting for loading indicator to disappear...
			t =    10.97s     Get number of matches for: Children matching type Other
			t =    11.09s         Snapshot accessibility hierarchy for com.example.SnapshotHang
			t =    11.13s         Find: Descendants matching type StatusBar
			t =    11.14s         Find: Children matching type Other
			t =    11.15s         Find: Element at index 1
			t =    11.15s         Find: Children matching type Other
			t =    11.16s     Find the Other
			t =    11.17s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    11.18s         Find: Descendants matching type StatusBar
			t =    11.19s         Find: Children matching type Other
			t =    11.19s         Find: Element at index 1
			t =    11.20s         Find: Children matching type Other
			t =    11.21s         Find: Element at index 0
			t =    11.21s     Find the Other
			t =    11.22s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    11.23s         Find: Descendants matching type StatusBar
			t =    11.24s         Find: Children matching type Other
			t =    11.25s         Find: Element at index 1
			t =    11.25s         Find: Children matching type Other
			t =    11.26s         Find: Element at index 1
			t =    11.27s     Find the Other
			t =    11.27s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    11.28s         Find: Descendants matching type StatusBar
			t =    11.29s         Find: Children matching type Other
			t =    11.30s         Find: Element at index 1
			t =    11.31s         Find: Children matching type Other
			t =    11.32s         Find: Element at index 2
			t =    11.32s     Find the Other
			t =    11.33s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    11.34s         Find: Descendants matching type StatusBar
			t =    11.35s         Find: Children matching type Other
			t =    11.35s         Find: Element at index 1
			t =    11.36s         Find: Children matching type Other
			t =    11.37s         Find: Element at index 3
			t =    11.38s     Find the Other
			t =    11.38s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    11.40s         Find: Descendants matching type StatusBar
			t =    11.40s         Find: Children matching type Other
			t =    11.41s         Find: Element at index 1
			t =    11.42s         Find: Children matching type Other
			t =    11.43s         Find: Element at index 4
			t =    11.44s     Find the Other
			t =    11.44s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    11.45s         Find: Descendants matching type StatusBar
			t =    11.46s         Find: Children matching type Other
			t =    11.47s         Find: Element at index 1
			t =    11.47s         Find: Children matching type Other
			t =    11.48s         Find: Element at index 5
		Waiting for loading indicator to disappear...
			t =    12.50s     Get number of matches for: Children matching type Other
			t =    12.61s         Snapshot accessibility hierarchy for com.example.SnapshotHang
			t =    12.65s         Find: Descendants matching type StatusBar
			t =    12.65s         Find: Children matching type Other
			t =    12.66s         Find: Element at index 1
			t =    12.67s         Find: Children matching type Other
			t =    12.68s     Find the Other
			t =    12.68s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    12.70s         Find: Descendants matching type StatusBar
			t =    12.70s         Find: Children matching type Other
			t =    12.71s         Find: Element at index 1
			t =    12.72s         Find: Children matching type Other
			t =    12.73s         Find: Element at index 0
			t =    12.73s     Find the Other
			t =    12.73s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    12.75s         Find: Descendants matching type StatusBar
			t =    12.75s         Find: Children matching type Other
			t =    12.76s         Find: Element at index 1
			t =    12.77s         Find: Children matching type Other
			t =    12.78s         Find: Element at index 1
			t =    12.78s     Find the Other
			t =    12.78s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    12.79s         Find: Descendants matching type StatusBar
			t =    12.80s         Find: Children matching type Other
			t =    12.81s         Find: Element at index 1
			t =    12.82s         Find: Children matching type Other
			t =    12.83s         Find: Element at index 2
			t =    12.83s     Find the Other
			t =    12.84s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    12.85s         Find: Descendants matching type StatusBar
			t =    12.86s         Find: Children matching type Other
			t =    12.86s         Find: Element at index 1
			t =    12.87s         Find: Children matching type Other
			t =    12.88s         Find: Element at index 3
			t =    12.88s     Find the Other
			t =    12.89s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    12.90s         Find: Descendants matching type StatusBar
			t =    12.91s         Find: Children matching type Other
			t =    12.92s         Find: Element at index 1
			t =    12.92s         Find: Children matching type Other
			t =    12.93s         Find: Element at index 4
			t =    12.94s     Find the Other
			t =    12.94s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    12.95s         Find: Descendants matching type StatusBar
			t =    12.96s         Find: Children matching type Other
			t =    12.97s         Find: Element at index 1
			t =    12.97s         Find: Children matching type Other
			t =    12.98s         Find: Element at index 5
		Waiting for loading indicator to disappear...
			t =    13.99s     Get number of matches for: Children matching type Other
			t =    14.09s         Snapshot accessibility hierarchy for com.example.SnapshotHang
			t =    14.13s         Find: Descendants matching type StatusBar
			t =    14.14s         Find: Children matching type Other
			t =    14.15s         Find: Element at index 1
			t =    14.15s         Find: Children matching type Other
			t =    14.16s     Find the Other
			t =    14.17s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    14.18s         Find: Descendants matching type StatusBar
			t =    14.19s         Find: Children matching type Other
			t =    14.19s         Find: Element at index 1
			t =    14.20s         Find: Children matching type Other
			t =    14.21s         Find: Element at index 0
			t =    14.21s     Find the Other
			t =    14.22s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    14.23s         Find: Descendants matching type StatusBar
			t =    14.24s         Find: Children matching type Other
			t =    14.24s         Find: Element at index 1
			t =    14.25s         Find: Children matching type Other
			t =    14.26s         Find: Element at index 1
			t =    14.27s     Find the Other
			t =    14.27s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    14.28s         Find: Descendants matching type StatusBar
			t =    14.29s         Find: Children matching type Other
			t =    14.29s         Find: Element at index 1
			t =    14.30s         Find: Children matching type Other
			t =    14.31s         Find: Element at index 2
			t =    14.31s     Find the Other
			t =    14.32s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    14.33s         Find: Descendants matching type StatusBar
			t =    14.34s         Find: Children matching type Other
			t =    14.34s         Find: Element at index 1
			t =    14.35s         Find: Children matching type Other
			t =    14.36s         Find: Element at index 3
			t =    14.36s     Find the Other
			t =    14.37s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    14.38s         Find: Descendants matching type StatusBar
			t =    14.39s         Find: Children matching type Other
			t =    14.39s         Find: Element at index 1
			t =    14.40s         Find: Children matching type Other
			t =    14.41s         Find: Element at index 4
			t =    14.42s     Find the Other
			t =    14.42s         Use cached accessibility hierarchy for com.example.SnapshotHang
			t =    14.43s         Find: Descendants matching type StatusBar
			t =    14.44s         Find: Children matching type Other
			t =    14.45s         Find: Element at index 1
			t =    14.45s         Find: Children matching type Other
			t =    14.46s         Find: Element at index 5
		Waiting for loading indicator to disappear...

		*** Test operation was canceled. If you believe this error represents a bug, please attach the log file at /var/folders/rc/8wcjk1890rg0htytb81pb2y80000gn/T/com.apple.dt.XCTest-status/Session-2016-03-21_14:48:44-PmrHE8.log

### Configuration Files

Snapfile:
```ruby
devices([
  "iPhone 5"
])

languages([
  "en-US"
])

```

### Environment

fastlane version (fastlane -v): 1.66.0
snapshot version (snapshot -v): 1.12.0
SnapshotHelperVersion [1.2]

**Comment by vpolouchkine** [comment]
Please format the issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md. Thanks!

**Comment by KrauseFx** [comment]
Also make sure to completely post your UI Test files

**Comment by elimelec** [comment]
Updated issue

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (487/400 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:60863)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKuF-002ltG-Dg
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:49 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=C1D5/7p6WJQnf6CU0Vwg7pVfjyg=; b=voeMx8HqswjDhvj+
	JCbU7XAL6/anuKDTvSude3GaDsSavrgIvT3uvCi6yPqvhFBAPaNC+nkaA6vzXZe8
	RZqCtms/K0J1R/2AcY4IwicIPCZFr8jE5+rAhAKcm6fj7Fr9lChGH5YY4CU8V6lI
	L6+32m48n60TGmClTOjJugfpz+E=
Received: by filter0846p1mdw1.sendgrid.net with SMTP id filter0846p1mdw1.30772.5765918247
        2016-06-18 18:22:58.828780861 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0005p1iad1.sendgrid.net (SG) with ESMTP id FM2Mn3d5TXuIdCt_Ouj2kg
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:22:58.744 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:22:58 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (486/400 (121%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o6.sgmail.github.com ([192.254.113.101]:37072)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKuC-002lsZ-Ek
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:44 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=RMl2Uv/G2+s5QsAH+YsAVK93ZxY=; b=Asp5ZnACGHAtDFPq
	9al5Lb/ETzxi/wvR+SF/oej8Nzax+IGAzrRJGkSCdUVqFPobaIDBmG7Ann9/7+7s
	ZNf8t0+HgBJZGEjfRSb681NIVCnYx5XDmsFLr9lQEcvHJa2j69noW1yUszL9O/PI
	BzZGGmBWq6T7DivhAdfgakE/9Js=
Received: by filter0523p1mdw1.sendgrid.net with SMTP id filter0523p1mdw1.23997.576591818
        2016-06-18 18:22:57.100035491 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0006p1iad1.sendgrid.net (SG) with ESMTP id ag0LXO5_TbyhA0poywy7eQ
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:22:57.108 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:22:56 -0700
