### ISSUE TITLE
Enhancement request for Deliver (or other action) to developer reject builds in review

### ISSUE THREAD

**Issue by calebhicks** [fastlane/fastlane#3841]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Would like to use Deliver to reject a current build for App Review if I am trying to submit a newer build. Perhaps with a `--reject_build_in_review` flag.

As always, thanks to the entire community here for a great tool.

**Comment by KrauseFx** [comment]
Mh, the right way to do that would be 
```
deliver reject_binary --app_version 1.4
```

Currently not planned, as this would have to be implemented in `spaceship` as well

**Comment by calebhicks** [comment]
Agreed, much better syntax. No rush, but if/when someone would like to take a crack at it, would be useful. 👍

**Comment by pedro380085** [comment]
+1

**Comment by fluidpixel** [comment]
I've been looking at bit at this, as I recently had to reject ~30 builds manually before I could use fastlane to successfully re-submit a new build of each app. 

Here's the call iTunes connect uses to reject an app that's waiting for submission:
`$http.post(global_itc_path + '/ra/apps/' + adamId + '/versions/' + versionId + '/reject')`

Excuse my ignorance as I've only been playing with the project in the last week, but would this need to be added to `fastlane/spaceship/lib/spaceship/tunes/tunes_client.rb`, something like this?

	def reject_build!(app_id, version_number)
		r = request(:post) do |req|
			req.url "ra/apps/#{app_id}/versions/#{version_number}/reject"
			req.body = {}.to_json
			req.headers['Content-Type'] = 'application/json'
		end
		handle_itc_response(r.body)
	end

**Comment by TKBurner** [comment]
@fluidpixel Thanks for following up. Have you had a chance to test out this change?

Thanks!

**Comment by fluidpixel** [comment]
@TKBurner Afraid not, I wasn't certain it was the correct approach, so that's as far as I got.

**Comment by taijizhu** [comment]
@fluidpixel is this working for you now?

**Comment by TKBurner** [comment]
@taijizhu This hasn't been implemented. However, we'll keep tracking this as a FR in both Deliver and Spaceship. Thanks!
