### ISSUE TITLE
Improve CI speed by properly caching gems

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#3851]
Currently we try to cache use the Circle cache to cache the installed gems on `/tmp/vendor/bundle`, but it doesn't seem to work. 

We could save **2 minutes** on every build if we do this right! :rocket: - no more :snail:

**Comment by lacostej** [comment]
@KrauseFx you fixed that one right ?

**Comment by KrauseFx** [comment]
Yeah, thanks @lacostej :+1:
