### ISSUE TITLE
frameit options not shared between action and stand-alone tool

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#3856]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

**frameit** standalone doesn't seem to have a **path** option, whereas running inside of fastlane it does:

Standalone docs:  `frameit help`

```
  Quickly put your screenshots into the right device frames

  Commands:
    black  Adds a black frame around all screenshots.
    help   Display global or [command] help documentation
    setup  Helps you adding new frames.
    silver Adds a silver frame around all screenshots.

  Aliases:
    white silver

  Global Options:
    --verbose
    -h, --help           Display help documentation
    -v, --version        Display version information

  Author:
    Felix Krause <frameit@krausefx.com>

  Website:
    https://fastlane.tools

  GitHub:
    https://github.com/fastlane/frameit
```

Loading documentation for frame:

`fastlane action frameit`

```
+---------------------------------------------------------+
|                         frameit                         |
+---------------------------------------------------------+
| Adds device frames around the screenshots using frameit |
|                                                         |
| Created by KrauseFx                                     |
+---------------------------------------------------------+

+---------------------+-------------------------------------------------------------------------------+---------------------------+
|                                                             frameit                                                             |
+---------------------+-------------------------------------------------------------------------------+---------------------------+
| Key                 | Description                                                                   | Env Var                   |
+---------------------+-------------------------------------------------------------------------------+---------------------------+
|   white             | Use white device frames                                                       | FRAMEIT_WHITE_FRAME       |
|   silver            | Use white device frames. Alias for :white                                     |                           |
| * path              | The path to the directory containing the screenshots (default: './fastlane/') | FRAMEIT_SCREENSHOTS_PATH  |
|   force_device_type | Forces a given device type, useful for Mac screenshots, as their sizes vary   | FRAMEIT_FORCE_DEVICE_TYPE |
+---------------------+-------------------------------------------------------------------------------+---------------------------+
1 of the available parameters are required
They are marked with an asterisk *

More information can be found on https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

```
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v):
Do you use bundler, rbenv or rvm?

**Comment by mfurtak** [comment]
Unlike other actions, `frameit` does not seem to get its options from a shared set defined by the stand-alone tool. Perhaps it predates this pattern?

Here's how this works for `deliver`:

* https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/options.rb
* https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/deliver.rb#L31
* https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/commands_generator.rb#L27

I'd be happy to review a PR that makes `frameit` adopt this pattern! :+1:

**Comment by mfurtak** [comment]
@KrauseFx I'd be curious whether you agree

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (489/400 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext8.iad.github.net ([192.30.252.199]:55591 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKuG-002lv1-4P
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:52 +0200
Date: Sat, 18 Jun 2016 11:23:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274182;
	bh=0nipJHpeFgIpC52CKD3sk60+uF2+IIAdnRT2UTvp81k=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tGsvXnRTWAivXM/msjpvOqnDgETdSq2nP9RyrpFN3hc1uHjd2v51vGNvEFhj34T8y
	 IJ7ZSyVRa3I1/ADzK+nyUx7+eNzC5mlCULO0IDmZ4zuZJPFM2Hk+HWvoEiLj+QCAJO
	 LB3IcsmcbLAemjHpOjWDum1223pszAxZt688eCDo=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (488/400 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:55579 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKuG-002luz-24
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:50 +0200
Date: Sat, 18 Jun 2016 11:23:02 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274182;
	bh=VRHSeII1+3Bli0LbYqbSirdIQ0i/gZZabINU0KZ3fmo=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=L0MlQ4HBzqIKNNPvYVCQ7g84gquLlwajq/fQz1IJLiWxAZq9UaTsQYGamd1yD1MC9
	 U8Iy7pmdYgso5zgQHCA1CXWJN2gPjgsAfcr5QLJ4TXr+/KhuGtqq8OA10qSgD7B2wD
	 LA1ETGHSOXZWhkn6gSdlKZtyecCaeK+DKoDpFDzk=

**Comment by KrauseFx** [comment]
@mfurtak Sorry for not coming back earlier. Yeah, frameit is the only and last tool that doesn't use the fastlane configuration manager. We should migrate sooner or later
