### ISSUE TITLE
Help with pilot to submit for review app to TestFlight external testers

### ISSUE THREAD

**Issue by kikolobo** [fastlane/fastlane#3857]
What parameters should I send to pilot in Fastfile to request submit the app for review for external testers after the app has been delivered to iTunes?

Any info would be appreciated!

**Comment by vpolouchkine** [comment]
You can set the `--distribute_external` flag. Also, you can run `pilot help` to get a list of all possible arguments.

**Comment by kikolobo** [comment]
I tried the distribute to external command, however I need to set some required fields, like changes and what to test before submitting.

**Comment by TKBurner** [comment]
Hi @kikolobo 
Thanks for following up. Can you send over the output with the error message you get?
It'll help if you can send over the information in this template. https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md

Thanks!

**Comment by bolom** [comment]
@kikolobo did you find a solution?

**Comment by kikolobo** [comment]
@bolom  Yes I did!

I just added some text to the what to test parameter to the pilot command and set the flag to distribute to externals to true.

Here's the fastFile :  

```
pilot(distribute_external: true, 
        changelog: 'Misc. bug fixes and improvements throughout the app.'
    ) 
```

**Comment by TKBurner** [comment]
@kikolobo Awesome! Glad to hear you are up and running. Feel free to ping this issue if you have any questions. Closing for housekeeping :+1:
