### ISSUE TITLE
Make sure "Slow Animations" is turned off

### ISSUE THREAD

**Issue by paxtonhare** [fastlane/fastlane#3860]
### Issue Description
For anyone who is seeing timeouts or strange errors when running Snapshot, make sure you didn't accidentally turn on "Slow Animations" in the IOS simulator. It's under the debug menu.

I was seeing this message:
```
 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds

[09:32:57]: Exit status: 65
[09:32:57]: Tests failed - check out the log above
```

I'm filing this issue just for the benefit of others who might run into this.

**Comment by mfurtak** [comment]
Thanks for posting this! :+1:
