### ISSUE TITLE
Fastlane "increment_build_number" not working after update Fastlane or xcode...

### ISSUE THREAD

**Issue by mcactive** [fastlane/fastlane#3877]
Hi!

Just updated both Fastlane and Xcode to the latest version and both increment_build_number and increment_version_number are not working anymore... It doesn't throw an error, it just doesn't update.

The xcode project hasn't been changed at all... The code is pretty straight forward:

```increment_build_number build_number: $appJson['version_no']
increment_version_number version_number: $build_number```

### Complete fastfile:

```ruby
platform :ios do


	desc "Test!"
	lane :test do
		
		# This doesn't require any thing, because it is all done in the "Before all lane"
		set_info_plist_value(path: './Roadmap-Info.plist', key: 'CFBundleIdentifier', value: "$(PRODUCT_BUNDLE_IDENTIFIER)")

		# Set identifier
		update_app_identifier(
		  xcodeproj: 'Roadmap.xcodeproj', # Optional path to xcodeproj, will use the first .xcodeproj if not set
		  plist_path: 'Roadmap-Info.plist', # Path to info plist file, relative to xcodeproj
		  app_identifier: 'com.demo.test' # The App Identifier
		)

        increment_build_number build_number: '6.1.2'
    
        increment_version_number version_number: '20160322'
	end

    # After no errors!
    after_all do |lane|

		p "We finished succesfuly!"

    end

    # Error!
    error do |lane, exception|
	    puts "We crashed.... Send me an e-mail!"
        # Do something!
    end
end

```

### Output: 
```
[15:05:18]: ------------------------------------
[15:05:18]: --- Step: increment_build_number ---
[15:05:18]: ------------------------------------
[15:05:18]: $ cd /Users/roadmap/Documents/MobiPoweriOS && agvtool new-version -all 6.1.2
[15:05:18]: ▸ Setting version of project Roadmap to:
[15:05:18]: ▸ 6.1.2.
[15:05:19]: ▸ Also setting CFBundleVersion key (assuming it exists)
[15:05:19]: ▸ Updating CFBundleVersion in Info.plist(s)...
[15:05:19]: ▸ Cannot find "Roadmap.xcodeproj/../				<key>INFOPLIST_FILE</key>"
[15:05:19]: --------------------------------------
[15:05:19]: --- Step: increment_version_number ---
[15:05:19]: --------------------------------------
[15:05:19]: $ cd /Users/roadmap/Documents/MobiPoweriOS && agvtool new-marketing-version 20160323
[15:05:20]: ▸ Setting CFBundleShortVersionString of project Roadmap to:
[15:05:20]: ▸ 20160323.
[15:05:20]: ▸ Updating CFBundleShortVersionString in Info.plist(s)...
[15:05:20]: ▸ Cannot find "Roadmap.xcodeproj/../				<key>INFOPLIST_FILE</key>"
```

### Environment

fastlane version (fastlane -v): 1.67.0
xcode version: 7.3
Do you use bundler, rbenv or rvm? RVM

**Comment by TKBurner** [comment]
Hi @mcactive. Thanks for letting us know. Can you edit to include your fast file?

Follow the template here: https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md

Also, what version of Xcode are you using?

Thanks!

**Comment by mcactive** [comment]
Hi! 

Yeah, I've stripped the Fastfile to exclude all the errors and even the simplest doesn't work. I've edited the post! 

Xcode version is the latest, 7.3

**Comment by i2amsam** [comment]
@mcactive I found a similar issue from a long time ago about a bug with cocapods. Are you using cocapods?  Could you check your `agvtool` https://github.com/CocoaPods/CocoaPods/issues/613?

**Comment by mcactive** [comment]
@i2amsam Hi Sam, yes, we are using cocoapods and using the cocoapods action in Fastlane as well.

The file appears to be XML instead of the OpenStep format.. Is there an easy way to fix it?

**Comment by i2amsam** [comment]
@mcactive does this solution work? https://github.com/CocoaPods/CocoaPods/issues/613#issuecomment-9695254 it seems like a cocapods issue rather than a fastlane issue.

**Comment by mcactive** [comment]
@i2amsam you're right... Saving something in xcode and running only 
`cd /Users/mcactive/Documents/Project && agvtool new-version -all 6.1.2` 
works...

But it's weird if it is a cocoapods issue as it always worked and after updating fastlane and xcode it broke... Should I make an issue at CocoaPods?

**Comment by i2amsam** [comment]
@mcactive I agree, super weird.  I don't see anything in the fastlane release that seems suspicious, and we didn't run into it with an updated xCode, let's see if anyone else reports it.

**Comment by mcactive** [comment]
@i2amsam updating to the beta version of cocoapods fixed the issue. This also installs "xcodeproj" beta which fixes a bug in Xcode 7.3:

```
1.0.0.beta.3
@segiddins segiddins released this 29 days ago · 3 commits to master since this release

Bug Fixes

Fix ASCII .xcodeproj serialization with Xcode 7.3.
```

**Comment by vfog** [comment]
Ran into the same issue. We're using Cocoapods as well, but it isn't part of our fastlane flow. However, I do have a custom action that use the `Xcodeproj` gem that is used internally by Cocoapods in order to modify the project to swap out app icons, fonts, etc.

Based on your current finding I would suspect that a change in the xcodeproj structure in Xcode 7.3 has caused an incompatibility with the `Xcodeproj` gem.

For now I'm working around the issue by having the `increment_build_number` and `increment_version_number` actions be executed first in my lane. I had initially tried to get around the issue by running my custom action after those above two actions, but was still running into conflicts. Once I moved the two increment actions above `update_project_team`, `update_info_plist`, and `update_app_identifier` then things begun to work fine.

**Comment by kcharwood** [comment]
@vfog I think you are exactly right. I'm seeing the same, and not using cocoapods.

**Comment by kcharwood** [comment]
@mcactive @vfog I've verified updating to xcodeproj 1.0.0 beta 3 fixes this for me. I am _not_ using cocoapods.

Fastlane may need to bump the minimum version of xcodeproj to resolve this.

**Comment by kcharwood** [comment]
@mcactive I believe this one should be reopened until its resolved.

**Comment by mcactive** [comment]
Didn't know fastlane also used Xcodeproj gem. Will reopen it until further notice.

**Comment by kcharwood** [comment]
You can see a few requires here:

`https://github.com/fastlane/fastlane/search?p=1&q=xcodeproj&utf8=%E2%9C%93`

**Comment by kcharwood** [comment]
Look like its defined [here](https://github.com/fastlane/fastlane/blob/1e8762d842713407a21cc3d1abacd822a0a83141/fastlane/fastlane.gemspec#L26).

I think this needs to be bumped to minimum 1.0.0-beta3

**Comment by i2amsam** [comment]
@mcactive and @kcharwood Thanks! :+1: I put a [comment](https://github.com/fastlane/fastlane/issues/3945#issuecomment-202529688) over in #3945, it appears we won't be able to bump our min version because that would put `fastlane` in conflict with `cocoapods 0.39` which is still working ok for Xcode 7.2 users. Eek.  I'd like to close this and track it in the other issue if that sounds right to you folks.

**Comment by TKBurner** [comment]
@kcharwood I'm closing this issue out so we can track on the other ticket. Thanks for working with us!

**Comment by StrangeDays** [comment]
You can put the Fastfile in a subdir =>  Dir_where_xcodeproj/Fastlane/Fastfile
