### ISSUE TITLE
Inconsistent parameter names for update_project_team

### ISSUE THREAD

**Issue by fisch0920** [fastlane/fastlane#3878]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The naming of `path` and `teamid` are inconsistent for update_project_team with respect to other actions that use `xcodeproj` and `team_id` respectively.  All actions should use consistent naming conventions for common parameters.

**Comment by TKBurner** [comment]
@fisch0920 Hey Travis! Great to hear from you, hope all is well in Bangkok. I saw Ernesto last week!

I'll let the team here know! :+1:

**Comment by KrauseFx** [comment]
Thanks for pointing this out, however we could only change that while keeping backwards compatible, so we'd have to have aliases. This was caused due to user contributions: Almost all built-in actions were submitted by users from all over the world :+1:
