### ISSUE TITLE
Use gym without apple account?

### ISSUE THREAD

**Issue by pavm035** [fastlane/fastlane#3879]
Hi,

Just curious to know is it possible to initialize fasten without apple account, i have plan to use few tools of fastlane where they do not need apple account say "gym"?

Thanks
Pavan

**Comment by TKBurner** [comment]
Hi @pavm035! Great question. You can use gym without an Apple Developer account. However, to build with the right code signing identity and provisioning profile for distribution you'll need an Apple account.

Thanks!

**Comment by pavm035** [comment]
@TKBurner  Thank you for quick response, but still if i manage "code signing identity and provisioning profile manually" what is the option to use gym without apple account?

Thanks
Pavan

**Comment by TKBurner** [comment]
@pavm035 Thanks for following up. Do you get a specific error when you cd into your project directory and run the command 'gym'?

**Comment by pavm035** [comment]
@TKBurner again thanks for quick reponse, no I did not get any error but during initialising fast lane it asks apple account so that's what I have to avoid ? And continue without providing an account?

**Comment by TKBurner** [comment]
@pavm035 Thanks for following up. You shouldn't need to run Fastlane init to get up and running. Is that what you are trying to do when you run into this error?

Thanks!

**Comment by pavm035** [comment]
@TKBurner  Thanks for the response, can you elaborate with details steps what i suppose to do here to use fastlane actions alone without calling "fastlane init" 

Thanks in advance!

**Comment by TKBurner** [comment]
@pavm035 Thanks for following up. Correct. You can run our tools by running their name directly in your project directory in a terminal window. In this case that'll allow you to bypass the steps that won't work because you don't have an Apple Developer account.

So cd into your project directory and then run 'gym'

Thanks!

**Comment by pavm035** [comment]
@TKBurner Thanks for the response, that looks like promising, if I use tool alone is it possible to have fast file in order to write my own lanes, I believe to have fast file I should call fastlane init, if I call that then it will prompt apple account, all I need here is to build this on my CI

Thanks

**Comment by TKBurner** [comment]
Hi @pavm035 you should be able to run 'fastlane init' to generate the scaffolding. I just enter in a placeholder for the email and passwords and when it fails you will be passed onto manual setup.

Thanks!

**Comment by pavm035** [comment]
@TKBurner  That's true Thank you so much :)
