### ISSUE TITLE
get_build_number_repository contains newline

### ISSUE THREAD

**Issue by fisch0920** [fastlane/fastlane#3883]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`get_build_number_repository` in a git repo returns a string with a trailing newline forcing me to use:

```ruby
def gen_build_number()
  return get_build_number_repository().strip
end
```

Note that the inverse `set_build_number_repository` does not suffer from this issue.

### Environment

fastlane version (fastlane -v): fastlane 1.67.0
Do you use bundler, rbenv or rvm? bundler

**Comment by KrauseFx** [comment]
Thanks @fisch0920, I just pushed https://github.com/fastlane/fastlane/pull/3894 :+1:

**Comment by fisch0920** [comment]
Awesome thanks for the fast turnaround!

**Comment by KrauseFx** [comment]
This will be in the next fastlane release :+1:
