### ISSUE TITLE
Option to disable fastlane/README.md file autogeneration

### ISSUE THREAD

**Issue by anton-matosov** [fastlane/fastlane#3887]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Everytime fastlane changes something in the README.md file format I get all my builds failed because of the detected changes in the file.
I still want to have this file under source control, but I want to update it manually only.

Please provide an option to disable fastlane/README.md file autogeneration.

##### Complete output when running fastlane, including the stack trace and command used
Git repository is dirty! Please ensure the repo is in a clean state by commiting/stashing/discarding all changes first.

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v): fastlane 1.66.0
Do you use bundler, rbenv or rvm? rbenv

**Comment by asfalcone** [comment]
@anton-matosov Take a look at [skip_docs](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#skip_docs) and let me know if that does what you need! :gift:

**Comment by KrauseFx** [comment]
I wonder how we can make this easier for the user. Should we add it to the default Fastfile? Or maybe in the `ensure_git_status_clean` action? @anton-matosov, @asfalcone

**Comment by anton-matosov** [comment]
Having it excluded for ensure_git_status_clean sounds like a good idea for me

**Comment by ohwutup** [comment]
We’re going to close this issue for now since we don’t have plans to implement it, but we’d be happy to review a PR that made this workflow easier for users!

**Comment by KrauseFx** [comment]
There is actually an action for that available, sorry I forgot to update the issue. You can use `skip_docs`, just put it on top of your `Fastfile` 🚀
