### ISSUE TITLE
Match keeps adding profiles to `~/Library/MobileDevice/Provisioning Profiles` instead of overriding existing and that breaks provisioing

### ISSUE THREAD

**Issue by anton-matosov** [fastlane/fastlane#3896]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Match keeps adding new profiles on the build server to `~/Library/MobileDevice/Provisioning Profiles` every time I add new devices. But Xcode doesn't pick the correct one (latest by date), it seems that it picks first by name. As a result, devices list changes are not reflected in the created ipa.

### Possible solution
Remove all previously installed provisioning profiles and install new if there are changes. The easiest way to do it is to put real profiles in the dedicated folder and symlink them to `~/Library/MobileDevice/Provisioning Profiles`. During the update remove all the symlinks pointing to this folder and create new profiles.

##### Complete output when running fastlane, including the stack trace and command used

```
can't share this
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile that updates prov profiles (refresh_adhoc_provision):
```ruby
  before_all do
    ENV["MATCH_READONLY"] = "true"
    ....
  end

  private_lane :refresh_devices do
    register_devices(
      devices_file: "fastlane/devices.txt"
    )
  end

  lane :refresh_adhoc_provision do
    refresh_devices

    ENV["MATCH_READONLY"] = "false"
    ENV["MATCH_FORCE_FOR_NEW_DEVICES"] = "true"

    match(type: "adhoc")
  end
```

Lane that builds
```
  before_all do
    ENV["MATCH_READONLY"] = "true"
    ....
  end


  private_lane :prv_testflight do
    ensure_git_status_clean
    
    if ENV["BRANCH_BUILD"]
      puts "
      TestFlight build can be created only from 'master', 'develop' or 'release/**' branches
      "
    else
      match(type: "appstore")
    ...
```

### Environment

fastlane version (fastlane -v):
Do you use bundler, rbenv or rvm?

**Comment by TKBurner** [comment]
@anton-matosov Thanks for reporting this. I'm going to have @mfurtak take a look!

**Comment by KrauseFx** [comment]
Uninstalling old profiles sounds nice, but might result in new issues. Have you followed the [Xcode Setup Guide](https://github.com/fastlane/fastlane/tree/master/match#setup-xcode-project) on how to set a provisioning profile using environment variables?

**Comment by anton-matosov** [comment]
Sure I did. Otherwise it will not work.

<img width="643" alt="sigh" src="https://cloud.githubusercontent.com/assets/3339485/14055837/59dc4b52-f2a2-11e5-8427-eb4f36835eb5.png">

@KrauseFx what issues do you expect with uninstalling old profiles?

**Comment by KrauseFx** [comment]
@anton-matosov If you have set the provisioning profile by a static UUID it won't reference to it properly any more and fail the build

**Comment by KrauseFx** [comment]
In general, we're trying to avoid to do any destructive actions with fastlane, as we don't want anyone to lose anything important

**Comment by TKBurner** [comment]
@anton-matosov I'm going to close out this feature request. Always feel free to reach out with other ideas or questions :+1:

**Comment by anton-matosov** [comment]
can we add a custom action to match to delete old profiles related to that account?
Because for me `match` experience is completely broken for AdHoc provisioning.
