### ISSUE TITLE
crashlytics crash if passed nonexistent group

### ISSUE THREAD

**Issue by fisch0920** [fastlane/fastlane#3902]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If you run the *crashlytics* action and specify a group which doesn't exist, fastlane will crash without a sensible error message after ~10 seconds.  I ran into this when using the human-readable group names before realizing that crashlytics provides slugified group aliases for exactly this reason.

```
fastlane run crashlytics ipa_path:test.ipa api_token:xxx build_secret:xxx groups:test-group1,test-group2
```

Fastlane should be robust against this type of error and ideally the crashlytics action docs would be updated to note that you should use group aliases.

### Environment

fastlane version (fastlane -v): 1.67.0
Do you use bundler, rbenv or rvm? bundler

**Comment by asfalcone** [comment]
@fisch0920 Thanks for the report. Can you please include the stack trace from the crash?

**Comment by fisch0920** [comment]
No stack trace is given as I believe it's a problem with Crashlytics.framework/submit as opposed to Fastlane itself, though Fastlane should be able to catch the error.

**Comment by TKBurner** [comment]
Hi @fisch0920! Can you send over the full output when your run 'fastlane run crashlytics'?

Thanks!

**Comment by fisch0920** [comment]
This was a problem in that the crashlytics submit shell action swallows stdout because it just appeared to be crashing until I ran the submit function directly and realized the submit was failing.

```
2016-04-18 16:54:52.462 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (16)
2016-04-18 16:54:52.469 submit Crashlytics: Path to IPA manually provided: fastlane/build/eko.ipa
2016-04-18 16:54:53.004 submit Crashlytics: Path To App: /var/folders/5_/6s453vvn2vn75t4r4xjvgy600000gn/T/eko/Payload/eko.app
2016-04-18 16:55:00.148 submit Crashlytics: Unable to add testers: Project ekogreen is inactive
2016-04-18 16:55:00.148 submit Crashlytics: Failed to add testers/groups to the release
```

This was failing because of the issue described [here](https://twittercommunity.com/t/add-new-ios-app-to-crashlytics-beta-via-command-line/56620), specifically that the project I was trying to upload was "inactive" e.g., hadn't sent any events yet by running the app.  This was very important to my use case for automatically building & uploading hundreds of white-labeled apps.

**Comment by vpolouchkine** [comment]
@fisch0920 Good job tracking this down! 👍

**Comment by TKBurner** [comment]
@fisch0920 Thanks for following up. Have you tried the steps at fabric.io/kits followed by a build and run prior to running this on a bundle ID?

Thanks!

**Comment by fisch0920** [comment]
@TKBurner yes, that works.. BUT the entire point of fastlane is to automate this process and when we're working with hundreds of white-labeled enterprise apps that are auto-generated, manually running each new client build before uploading to crashlytics is a PITA.

Fabric.io doesn't help with this.

**Comment by TKBurner** [comment]
Thanks @fisch0920! This is actually a limitation on the Fabric side that has been longstanding.  The recent Cocoapods addition, /kits/ and some upcoming Unity work have all been moving toward this automated onboarding you are looking for. I'll bring this up with the Crashlytics team. Thanks!
