### ISSUE TITLE
Rocket action looks a little phallic 

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#3903]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I checked out the new `fastlane run rocket` action and it looks a little less like a rocket than something else.  

Since when do rockets have "heads" bigger than their "shafts"?

![screen shot 2016-03-23 at 5 27 20 am](https://cloud.githubusercontent.com/assets/6491743/13981028/fbd4280e-f0b7-11e5-8ea8-16b7a44211c3.png)

Maybe a rocket like these is better??

```



        |
       / \
      / _ \
     |.o '.|
     |'._.'|
     |     |
   ,'|  |  |`.
  /  |  |  |  \
  |,-'--|--'-.| 





         /\
        |==|
        |  |
        |  |
        |  |
       /____\
       |    |
       |    |
       |    |
       |    |
      /| |  |\
     / | |  | \
    /__|_|__|__\
       /_\/_\
       ######
      ########
       ######
        ####
        ####
         ##
         ##   
         ##
         ##


       !
       !
       ^
      / \
     /___\
    |=   =|
    |     |
    |     |
    |     |
    |     |
    |     |
    |     |
    |     |
    |     |
    |     |
   /|##!##|\
  / |##!##| \
 /  |##!##|  \
|  / ^ | ^ \  |
| /  ( | )  \ |
|/   ( | )   \|
    ((   ))
   ((  :  ))
   ((  :  ))
    ((   ))
     (( ))
      ( )
       .
       .
       .


```

**Comment by colmdoyle** [comment]
No objection to changing them to a more "traditional" rocket, but it looks like a [SpaceX Falcon9](http://www.spacex.com/about/capabilities) to me.

![screen shot 2016-03-23 at 10 10 20](https://cloud.githubusercontent.com/assets/406463/13982027/927138a2-f0df-11e5-975d-8edbc2b80853.png)

**Comment by TKBurner** [comment]
@jeeftor Thanks for the feedback! I'll make sure Felix and team have a look :+1:
