### ISSUE TITLE
Fastlane gym should force signing with profile from sigh

### ISSUE THREAD

**Issue by fisch0920** [fastlane/fastlane#3906]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This is a follow-up to #1393.  For my use case, manually setting the provisioning profile in the code signing section to an env variable including the app_identifier won't work because I'm working on a white-label app where the app_identifier is selected at build time from hundreds of potential app_identifiers.

I don't see any reason why fastlane couldn't update the pbxproj settings directly as `update_app_identifier` does.  This is what fastlane's all about, using the suite of tools and having it "just work".  So if sigh generates a provisioning profile, gym should automatically use it and currently that's not the case even though it finds `lane_context[Actions::SharedValues::SIGH_PROFILE_PATH]` it's not actually used if the corresponding UDIDs aren't updated in the xcodeproj's pbxproj.

I'm currently using this custom action to definitively set the provisioning profile.

```ruby
def set_provisioning_profile(params)
  info_plist_key = 'INFOPLIST_FILE'
  identifier_key = 'PROVISIONING_PROFILE'

  path = File.expand_path(File.join(ENV['PWD'], params[:xcodeproj]))
  project = Xcodeproj::Project.open(path)

  # Fetch the build configuration objects
  configs = project.objects.select { |obj| obj.isa == 'XCBuildConfiguration' && !obj.build_settings[identifier_key].nil? }
  raise "Info plist uses $(#{identifier_key}), but xcodeproj does not".red unless configs.count > 0

  configs = configs.select { |obj| obj.build_settings[info_plist_key] == params[:plist_path] }
  raise "Xcodeproj doesn't have configuration with info plist #{params[:plist_path]}.".red unless configs.count > 0

  # For each of the build configurations, set app identifier
  configs.each do |c|
    puts c.build_settings[identifier_key].blue
    c.build_settings[identifier_key] = params[:udid]
  end

  # Write changes to the file
  project.save

  UI.success("Updated #{params[:xcodeproj]} 💾.")
end
```

@KrauseFx perhaps this could be added as another action or integrated more tightly into sigh / gym?

### Environment

fastlane version (fastlane -v): 1.67.0
Do you use bundler, rbenv or rvm? bundler

**Comment by TKBurner** [comment]
@fisch0920 Thanks for working through this. Gym should be taking the provisioning profile generated by Sigh. I'll make sure @mpirri takes a look.

Thanks!

**Comment by fisch0920** [comment]
Thanks man; this is an important one imho, though it's at least easy to work around with the logic I provided above.

**Comment by KrauseFx** [comment]
> I don't see any reason why fastlane couldn't update the pbxproj settings directly as update_app_identifier does.

There are a few very big reasons on why `sigh` doesn't do that: 

- When the Xcode project is modified, the git status gets dirty
- Many people don't use Xcode projects, but still code sign (e.g. Xamarin projects)
- Some companies don't even use Xcode projects like we do (e.g. Facebook)
- People would be really mad if we modified their Xcode projects, and they already had changes there before, and we add even more changes, making it impossible to revert just the code signing part.
- `sigh` is responsible for **downloading** and **installing** provisioning profiles and has no connection to Xcode projects at all. That's the responsibility of `gym` and `fastlane`
