### ISSUE TITLE
Unexpected Response error when Running 'Spaceship::Tunes::Application.all'

### ISSUE THREAD

**Issue by nurne** [fastlane/fastlane#3908]
Followed the spaceship readme to the word.

Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"}
from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.24.0/lib/spaceship/client.rb:328:in `parse_response'

**Comment by TKBurner** [comment]
Hi @nurne! Great to hear from you. I definitely want to dig into this. Can you update your post with this template:  https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md 

Thanks!
