### ISSUE TITLE
sigh resign feature request

### ISSUE THREAD

**Issue by tychop** [fastlane/fastlane#3910]
I would like to be able to change the bundle-id upon resigning.
Would that be possible in one of the future versions?

P.s. the "sigh resign --help" output is out of date....

**Comment by kcharwood** [comment]
Yep. I've requested that as well:

https://github.com/fastlane/fastlane/issues/1758

**Comment by TKBurner** [comment]
@tychop You can track this at #1758 Closing this ticket out. Thanks for your great suggestion :+1:
