### ISSUE TITLE
Action for resetting git branch to remote

### ISSUE THREAD

**Issue by 7mllm7** [fastlane/fastlane#3911]
I got the requirement to reset the git repository to the most recent code from the remote.
Now, in most circumstances, you can achieve it with the [git_pull](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#git_pull) action.

However, when using rebase as a merging technique, fetching & pulling might cause conflicts that will stop the build process.

What I'd love to see is an option to run `git reset --hard origin/some-branch` in a fastlane action.
It can then use [gir_branch](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#git_branch) and maybe `git rev-parse --abbrev-ref --symbolic-full-name @{u}'` or any of [these suggestions](http://stackoverflow.com/questions/171550/find-out-which-remote-branch-a-local-branch-is-tracking) (which can potentially be an independent `git_tracking_remote_branch` action) to reset the current tracked branch in any variable remote.

What do you think?

**Comment by 7mllm7** [comment]
Just to clarify, my usage is when I want my build machine to get the most recent codebase of a certain release branch from the remote by using fastlane, hence without needing to add a step in the build.

**Comment by TKBurner** [comment]
Thanks for your suggestion @7mllm7! I've added this to our feature request list so we can prioritize. You can do a git pull using the steps here, https://github.com/fastlane/fastlane/blob/ad585bce69ef5a24dd01b8f6f4bce1e90ecb6046/fastlane/lib/fastlane/actions/git_pull.rb.

Thanks!

**Comment by ohwutup** [comment]
Thanks @7mllm7! I am going to close this issue for now as we are working on other features at the moment. But we will definitely reopen this issue if/when we get a chance to make it happen. For now would shelling out to run your own git command do the trick?

**Comment by 7mllm7** [comment]
It would, I've created a custom action for it in my project... Thanks
