### ISSUE TITLE
Not able to work "Titles and Background" for the screenshots generated by Frameit

### ISSUE THREAD

**Issue by kNeerajPro** [fastlane/fastlane#3914]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to use frameit and deliver to push screenshots to iTunesConnect. Unfortunately I am not able to get titles on the frameit generated screenshot.
Here is my Framefile but I am not able to understand it properly.  How does it chose the title? What does data mean? Does the filter key should match with the screenshot file name? Please add the explanation of this file and the title.strings file. After running the command successfully I am not seeing any titles added.
{
  "default": {
    "keyword": {
      "font": "./fonts/helvetica-regular.otf"
    },
    "title": {
      "font": "./fonts/helvetica-regular.otf",
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 50
  },

  "data": [
    {
      "filter": "Login-Screen_framed",
      "keyword": {
        "color": "#d21559"
      }
    },
  ]
}
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.48.0"

default_platform :ios


platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cert
    sigh
    gym(scheme: "tsc") # Build your app - more options available
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    snapshot
    sigh
    gym(scheme: "tsc") # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

```

### Environment

fastlane version (fastlane -v): fastlane 1.67.0
Do you use bundler, rbenv or rvm? rvm

**Comment by TKBurner** [comment]
Hi @kNeerajPro! Great to hear from you. Can you take a look at this example project and let me know if you have any specific questions? I think it's going to help a lot :+1:  https://github.com/fastlane/examples/tree/master/MindNode/screenshots

**Comment by kNeerajPro** [comment]
@TKBurner I have already looked at that project. I am unfortunately not able to understand the Framefile and title.strings. Could you explain what that json file and its element means? I am not able to add titles to the screenshots nor the screenshot file has the correct size. 
Also the project linked above should have had some sample screenshots. That would have probably helped to understand.
Apologies for probably not able to understand something basic :(

**Comment by TKBurner** [comment]
Hi,

{
  "default": {
    "keyword": {
      "fonts": [
        {

describes the font of the second half of the 'title' in your screenshot 

 "title": {
      "fonts": [
        {

describes the font of the Title in your screenshot

  "data": [
    {
      "filter": "Brainstorming",
      "keyword": {

filter's are the overlay. They are applied to once each to each screenshot.

In keyword.strings you set the text after the title in your screenshot by associating a filter with a given 'keyword string'

In title.strings you set the text of the title in the screenshot by associating a filter with a given 'title string'


![image](https://cloud.githubusercontent.com/assets/1987108/13999137/316aa89a-f111-11e5-8fe4-fd77fb6ba245.png)

In this image Brainstorming is the 'title' and 'Let your ideas grow' is the keyword. As it's set here, https://github.com/fastlane/examples/blob/master/MindNode/screenshots/en-US/title.strings.

Thanks!

**Comment by kNeerajPro** [comment]
Thank you for the comment I certainly understood much more. Please add this information somewhere in the Git page so other people can also understand it faster.
Unfortunately I am still not able to get this to work.


Here is my** Framefile.json** -
{
  "default": {
    "keyword": {
      "fonts": [
        {
          "font": "./fonts/helvetica-regular.otf",
          "supported": ["en-US"]
        }
      ]
    },
    "title": {
      "fonts": [
        {
          "font": "./fonts/AlwynNewRd-Rg.otf",
          "supported": ["en-US"]
        }
      ],
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 50
  },


  "data": [
    {
      "filter": "Login",
      "keyword": {
        "color": "#d21559"
      }
    }
  ]
}
**
keyword.strings**
"Login" = "LOGIN"

**title.strings**
"Login" = "This is the Login Screen";

My screenshot folder apart from the above strings file contains screenshot images named - 
iPadRetina-Login-Screen_framed.png, iPhone6-Login-Screen_framed.png, iPhone6Plus-LoginScreen_framed.png. There are no titles even after running the command - frameit.

Could you please tell where I am wrong?
Sorry for the trouble!!

**Comment by t4ec** [comment]
I am having the same issue: configs are really confusing and there is no error or anything to see the reason for missing headings. I get just framed screenshots without any text, no messages or warnings.

**Comment by TKBurner** [comment]
@kNeerajPro What happens if you use the exact framefile from the example project? Are you able to get those titles to show?

Thanks!

**Comment by kNeerajPro** [comment]
@TKBurner  unfortunately I am working on some other project while simultaneously figuring this out. I will get back to you when I start working on this again.
I apologise for any delays from my side.
