### ISSUE TITLE
Screenshot title works for "frameit white" not "frameit silver"

### ISSUE THREAD

**Issue by kNeerajPro** [fastlane/fastlane#3917]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Title for screenshot is working for frameit white but not for frameit silver.
<img width="450" alt="screen shot 2016-03-24 at 10 10 30 am" src="https://cloud.githubusercontent.com/assets/7275348/14008597/b37aba5e-f1a8-11e5-8510-ce6ab7512e5a.png">
<img width="458" alt="screen shot 2016-03-24 at 10 10 39 am" src="https://cloud.githubusercontent.com/assets/7275348/14008598/b640fb4a-f1a8-11e5-8e71-da74026f376f.png">

##### Complete output when running fastlane, including the stack trace and command used
when I run frameit silver I don't get any error.
<img width="820" alt="screen shot 2016-03-24 at 10 11 57 am" src="https://cloud.githubusercontent.com/assets/7275348/14008606/debf3352-f1a8-11e5-892f-a0f46e846635.png">

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.48.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    cert
    sigh
    gym(scheme: "tsc") # Build your app - more options available
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    snapshot
    sigh
    gym(scheme: "tsc") # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v): fastlane 1.67.0
Do you use bundler, rbenv or rvm? rvm

**Comment by TKBurner** [comment]
Hi @kNeerajPro! Great to hear from you. Can you send over your title.strings and your Framefile?

Thanks!

**Comment by kNeerajPro** [comment]
title.strings file - 
"Login" = "This is the Login Screen";

Framefile.json -

{
  "default": {
    "keyword": {
      "fonts": [
        {
          "font": "./fonts/OpenSans-Regular.ttf",
          "supported": ["en-US"]
        }
      ]
    },
    "title": {
      "fonts": [
        {
          "font": "./fonts/OpenSans-Regular.ttf",
          "supported": ["en-US"]
        }
      ],
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 50
  },


  "data": [
    {
      "filter": "Login",
      "keyword": {
        "color": "#d21559"
      },
      "title": {
        "text" : "Login Screen"
      }
    }
  ]
}

**Comment by TKBurner** [comment]
Hi @kNeerajPro! Thanks for following up. It's important to note that, some stock images provided by Apple still have a white background instead of a transparent one. You'll have to edit the Photoshop file to remove the white background, delete the generated .png file and run frameit again. Also, we only officially support black and silver.

Let me know how it's going on your end :+1:

**Comment by kNeerajPro** [comment]
I am sorry you didn't understand my question. Its not working with the black one but works with other. I don't understand why. Please see the above screenshots attached. Any ideas about it?

**Comment by TKBurner** [comment]
Hi @kNeerajPro! Thanks for following up. Can you send me the full text output when your run frameit silver?

Thanks!

**Comment by kNeerajPro** [comment]
I will get back to you on this after couple of days.
