### ISSUE TITLE
[Feature/Discussion] Have Match Store Android JKS & Service Account JSON

### ISSUE THREAD

**Issue by bassrock** [fastlane/fastlane#3918]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Recently I started setting up Fastlane with my Android applications and noticed some items that I wonder if they would be a good fit to store in an organization's match repository.

To build for iOS you currently need and store in Match:
* Team Development/Distribution Profile
* Provisioning Profiles

These can also be regenerated without causing much headache with match and sigh, while maintaining the ability to push new versions to the store.

For Android apps you have jks with a key and certificate inside of it. You can also have one keystore for an entire organization and then use the same keyAlias or create another inside of it for each app. You also have a service-account json key that gives fastlane the ability to upload apps (or allowed apps) to your organizations play account.

Then on top of that, if you lose the jks keystore that you used to sign the apk for submission to the app store, you will not be able to submit updates to any app that used that jks.

Since the JKS is highly important to keep and control I am recommending that Match also have the ability to store the JKS, add key aliases to it, and somehow set variables for gradle to be able to point to it. 

I can start work on a pull request for this with some basic direction on if this is something wanted for Match or if it belongs spread out among a few tools.

The main reason I am recommending it for match is because Match uses an encrypted repo to store the main distribution certificates currently for iOS and I see these as the distribution certificates for Android. Since Match is used to encrypt certificates, I also think it is a good idea to put the service-account.json in the repo as well.

So should this receive the go ahead there are a few items that would need to be answered by the community:

1. Does match hold 1 service-account.json for each app. Or is it 1 per organization?
2. Does match hold 1 JKS per app. Or is it 1 per organization.
3. What is the preferred directory structure?
4. What is the preferred way to store information about what is in the JKS and how it maps to what app?
    - Do we use the keyStoreAlias as the package identifier?
5. How do those with existing apps import their existing keystores? (looks like its possible to import and change aliases: http://stackoverflow.com/questions/19912067/merge-2-jks-truststore-files)
    - What does this workflow look like?

Let me know all your thoughts as I think this would be a great addition, especially because as of now my service-account.json and jks are just sitting in my android git repo.

**Comment by asfalcone** [comment]
@bassrock thanks for opening an issue for discussion on this! As mentioned in #3457 and https://github.com/fastlane/match/pull/88 we're not quite ready to get started (or have contributors get started) on this work, but we love hearing from you and others about what features you think are important for Android developement!

**Comment by bassrock** [comment]
Whoops didn't even see that one when I searched to see if it already existed. Sounds good!

**Comment by TKBurner** [comment]
No problem @bassrock! You can follow along in those threads :+1:
