### ISSUE TITLE
Passing variable from Environment variables in CI to 

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#3920]
### Environment
fastlane version (fastlane -v): 1.68.0 (the latest version in the present)

##### I setup a CI to process for my iOS App. Because I have many App with different bundle Id to publish to store, I save the information an properties file:

```
BUNDLE_IDENTIFIER="my.bundle.id"
MYAPP_NAME="MyApp"
```
After that I add it as an environment variables of CI. 
As I read on https://github.com/fastlane/fastlane/issues/457
or 
https://medium.com/mitoo-insider/how-to-set-up-continuous-delivery-for-ios-with-fastlane-and-circleci-c7dae19df2ed#.awikkzc5v

I do as below:

- First, in Appfile file, I add those lines:
```
app_identifier ENV[“APP_IDENTIFIER”] 
apple_id ENV[“APPLE_ID”]
```
Then, in Fastfile file, I try to add those lines:
```
 ENV["APP_IDENTIFIER"] = ${BUNDLE_IDENTIFIER}
ENV["APP_NAME"] = ${MYAPP_NAME}
```
so that  I can use this variable to produce it:

```
lane :adhocprovision do
     produce( 
        app_name:  ENV["APP_NAME”],
        sku: ENV["APP_IDENTIFIER”],
        skip_itc: 'true'
        )
      cert
      sigh(adhoc: true)
  end
```
But it does not assign the value to variable and returned the error:

```
[!] Syntax error in your Fastfile on line 27: Fastfile:27: `${' is not allowed as a global variable name
Fastfile:27: syntax error, unexpected end-of-input
    ENV["APP_IDENTIFIER"] = ${BUNDLE_IDENTIFIER}
                              ^[0m
```

I tried to add ``` puts``` as https://github.com/fastlane/fastlane/issues/457, but it does not help.

So, how I can let fastlane use my variable?

**Comment by aln787** [comment]
@biolinh did you add both of your variables (`BUNDLE_IDENTIFIER` and `MYAPP_NAME`) in an `Appfile` as [your medium example](https://medium.com/mitoo-insider/how-to-set-up-continuous-delivery-for-ios-with-fastlane-and-circleci-c7dae19df2ed#.xs7ls237z) does?  [Here is a more complete example to follow that may answer your question.](https://github.com/fastlane/examples/blob/master/Acast/Appfile)

**Comment by biolinh** [comment]
Maybe  I wrote  unclearly. I want to use a valuable from the environment that is assigned from .properties file.

Then, in all file, I set the variable and it can automatic got the value to using.

You can see that, as I wrote above. 
> in Appfile file, I add those lines:
app_identifier ENV[“APP_IDENTIFIER”] 
apple_id ENV[“APPLE_ID”]

It means that, app_identifier will get the value from variable APP_IDENTIFIER.

In addition that, in Fastfile, I donn't want to hard code the value of ENV[“APP_IDENTIFIER”]. In stead of that, I want the ENV[“APP_IDENTIFIER”] will get value from ${BUNDLE_IDENTIFIER} that is as a environment variable used by CI. 

Hence, when I change bundle id, i only need change it in CI then it automatic change it in all file using it under fastfile folder.

**Comment by aln787** [comment]
@biolinh instead of adding the values to the Appfile, export them as environment variables.  Here is an example:

```
#set env vars
export PRODUCE_USERNAME="<email address you use for ITC and the dev portal>"
export PRODUCE_APP_IDENTIFIER="com.<your apps bundle id>"
export PRODUCE_SKU="<your SKU>"
export CERT_USERNAME=$PRODUCE_USERNAME
export SIGH_APP_IDENTIFIER=$PRODUCE_APP_IDENTIFIER
export SIGH_USERNAME=$PRODUCE_USERNAME

#Execute Fastlane actions
fastlane ios adhocprovision 
```



```
lane :adhocprovision do
     produce(skip_itc: true)
      cert
      sigh(adhoc: true)
  end
```

**Comment by biolinh** [comment]
Hi @aln787,

As I said that, I use a properties file to store the value of per
variables. When I want to build a app with specific Bundle ID, I will pick
the file corespondent with it.

And in CI, I also add an option: Inject environment variables and specific
the properties file then it add all values I need to environment. When I
check Environment variables (injectedEnvVars) in CI, it shows something
like that:
PRODUCT_NAME    MyApp
APPLE_ACCOUNT  MyAccount

It means that values are export as environment variables.



2016-04-04 2:09 GMT+07:00 aln787 <notifications@github.com>:

> @biolinh <https://github.com/biolinh> instead of adding the values to the
> Appfile, export them as environment variables. Here is an example:
>
> #set env vars
> export PRODUCE_USERNAME="<email address you use for ITC and the dev portal>"
> export PRODUCE_APP_IDENTIFIER="com.<your apps bundle id>"
> export PRODUCE_SKU="<your SKU>"
> export CERT_USERNAME=$PRODUCE_USERNAME
> export SIGH_APP_IDENTIFIER=$PRODUCE_APP_IDENTIFIER
> export SIGH_USERNAME=$PRODUCE_USERNAME
>
> #Execute Fastlane actions
> fastlane ios adhocprovision
>
> lane :adhocprovision do
>      produce(skip_itc: true)
>       cert
>       sigh(adhoc: true)
>   end
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/fastlane/fastlane/issues/3920#issuecomment-205036358>
>



-- 
Linh Nguyễn

Phone: 090 346 0989
Skype: linh.bio

**Comment by biolinh** [comment]
Finally, after reading Fastlane's documentations (Advanced.md), I found the solution. I thought that Fastlane might get  environment  variable but it only get variables in a .env or .env.default file in the same directory as your Fastfile. So I copy my properties file to fastlane/.env and Fastlane can pass my value.
And now, I am facing another issues. What interesting it is when trying a new tools as fastlane.
``` No value found for 'username'[0m ```

**Comment by TKBurner** [comment]
@biolinh Glad to hear you got up and running! Always feel free to reach out to our community. Closing this issue for housekeeping :+1: Have a great week!

**Comment by samskiter** [comment]
Fastlane doesn't seem to be reading from my .env or .env.default files. But will read from .env.test if I specify --env test. Any chance this behaviour has regressed?

**Comment by TKBurner** [comment]
@samskiter Great to hear from you! This behavior should not have changed. Can you submit a new issue if you are still running into this? Thanks!

**Comment by samskiter** [comment]
@TKBurner it was actually related to my other problem which is env variables not persisting into child processes properly. Something weird is going on with unicode (raising bug as you asked :) )

**Comment by TKBurner** [comment]
Hi @samskiter Sorry for the delay in following up. As a workaround can you run `export ENV_NAME="123" `or add the action `sh export ENV_NAME="123"`?
