### ISSUE TITLE
Screengrab: how to screenshot a WebView?

### ISSUE THREAD

**Issue by lvh1** [fastlane/fastlane#3922]
Is it possible to make a screenshot of a WebView that is displayed on top of the current activity? 
Right now this results in just the current activity being shown on the picture, while ignoring the webview that's displayed on top of it.
Using the latest version of Screengrab (0.3.1).

### New Issue Checklist
- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

**Comment by TKBurner** [comment]
Thanks for reaching out. I want to loop in a few people. Can you let me know if this is consistent for all web views or only initial ones? I want to figure out if this is because the screenshot is happening before the view loads or if it's the way the screenshot is taken.

Thanks!

**Comment by lvh1** [comment]
I'm fairly sure it is because of the way the screenshot is being taken. Even after letting the thread sleep for 5 seconds  just to be sure the webview is fully loaded, it always resulted in a picture of the activity in the background.
Tested it with webviews on 2 different places.

**Comment by asfalcone** [comment]
Likely related to https://github.com/fastlane/fastlane/issues/2080

**Comment by TKBurner** [comment]
@lvh1 Can you track this issue on that thread? I'm closing this one out :+1: 

Thanks!
