### ISSUE TITLE
`fastlane init` fails to properly escape filenames

### ISSUE THREAD

**Issue by Drarok** [fastlane/fastlane#3924]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running `fastlane init` in a project directory where the Xcode workspace as a single quote (`'`) in it, fastlane fails due to improper/no escaping of input.

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane init --verbose
INFO [2016-03-24 16:00:04.99]: Detected iOS/Mac project in current directory...
INFO [2016-03-24 16:00:04.99]: This setup will help you get up and running in no time.
INFO [2016-03-24 16:00:04.99]: fastlane will check what tools you're already using and set up
INFO [2016-03-24 16:00:04.99]: the tool automatically for you. Have fun!
INFO [2016-03-24 16:00:04.99]: Created new folder './fastlane'.
INFO [2016-03-24 16:00:04.99]: xcrun xcodebuild -list -workspace './Let's Test Fastlane.xcworkspace'
sh: -c: line 0: unexpected EOF while looking for matching `''
sh: -c: line 1: syntax error: unexpected end of file
ERROR [2016-03-24 16:00:05.00]: Error parsing xcode file using `xcrun xcodebuild -list -workspace './Let's Test Fastlane.xcworkspace'`
ERROR [2016-03-24 16:00:05.00]: An error occured during the setup process. Falling back to manual setup!
App Identifier (com.krausefx.app):
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile: none

### Environment

fastlane version (fastlane -v): fastlane 1.68.0
Do you use bundler, rbenv or rvm? rvm

**Comment by Drarok** [comment]
Escaping in shells isn't very nice. You end the string with `'`, then add a literal quote with `\'`, then open a string again with `'`, resulting in this:
```sh-3.2$ echo 'Let'\''s Test Escaping'
Let's Test Escaping```

**Comment by TKBurner** [comment]
Hi @Drarok! Thanks for pointing this out. I was able to reproduce over here. I'll have the team take a look and prioritize it.

Thanks!

**Comment by ohwutup** [comment]
Hey @Drarok! This is going to be interpreted differently by different shells and escaping can lead to some pretty weird edge cases. For now I think the best way to handle this is to use double quotes to surround the whole string like so:
```bash
> echo "Let's test escaping"
Let's test escaping
```
Let us know if this works out for you! 🐙 🚀

**Comment by Drarok** [comment]
The problem isn't that I can't _type in_ my project name somewhere, it's that `fastlane init` doesn't escape it, and I can do nothing from outside to control that. It's working out my project name and then building an invalid command line, shown above as

```
xcrun xcodebuild -list -workspace './Let's Test Fastlane.xcworkspace'
```

**Comment by ohwutup** [comment]
Ahhh! Apologies! I misunderstood the initial report. Thanks for filing this, I will look into a fix now!

**Comment by ohwutup** [comment]
https://github.com/fastlane/fastlane/pull/5032/files This PR should fix up this issue!

**Comment by ohwutup** [comment]
Hey @Drarok, feel free to reopen the issue if the fix we just merged doesn't help! 🚀
