### ISSUE TITLE
Remove app from simulator after snapshot is complete

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#3935]
Is there a way to delete the app after snapshot has successfully completed?

SNAPSHOT_REINSTALL_APP runs before the build, what about after?

The reason for this is intensive app delivery; on a given day my CoreSimulator/Devices folder can go up to 8gb in data.

As always, thanks!

**Comment by TKBurner** [comment]
Hi @pedro380085! Great idea. It's not possible right now, but if you want to submit an action as a pull request the team will look into it! :+1:

**Comment by KrauseFx** [comment]
If you use `fastlane` check out the `reset_simulators` action to completely reset all your simulators :+1:
