### ISSUE TITLE
Change a variable in the code

### ISSUE THREAD

**Issue by cyril94440** [fastlane/fastlane#3941]
Hey!

I have a DEBUG variable, and I'd like gym to build a version with True and then a version with False. Any idea about the way I can do it with fastlane?

Thank you!

**Comment by TKBurner** [comment]
Hi @cyril94440! Thanks for reaching out. You can run gym multiple times in the same lane. Run fastlane actions gym to see the parameters you can add to your run.

Thanks!

**Comment by cyril94440** [comment]
That's the thing. I don't know how to pass a variable from gym to my Xcode so that I can do a IF in my code.

**Comment by TKBurner** [comment]
@cyril94440 Thanks for following up. It's a ruby do block if that helps you understand the syntax. However, it sounds like you don't need an if statement so much as to run gym twice in a row exporting different ipa files.

Thanks!

**Comment by KrauseFx** [comment]
@cyril94440 are you talking about having an `if` in your iOS code? If so, how about you use preprocessor macros? You can set them using `gym` :+1:

**Comment by cyril94440** [comment]
That is exactly what I am looking for.
Could you help me to setup that?

Thank you so much.

**Comment by KrauseFx** [comment]
Maybe this issue helps? https://github.com/fastlane/fastlane/issues/2660

**Comment by cyril94440** [comment]
unfortunately  custom_build_args is not available with gym.

**Comment by KrauseFx** [comment]
Of course
```
gym --help
```

```
    -x, --xcargs STRING  Pass additional arguments to xcodebuild. Be sure to quote the setting names and values
e.g. OTHER_LDFLAGS="-ObjC -lstdc++" (GYM_XCARGS)
    -y, --xcconfig STRING Use an extra XCCONFIG file to build your app (GYM_XCCONFIG)
```
