### ISSUE TITLE
Watchbuild Error: This user is not allowed access to the window system right now

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#3950]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

What is this Error?! ```watchbuild``` has no access ?! :/

##### Complete output when running fastlane, including the stack trace and command used

```
<Error>: Set a breakpoint at CGSLogError to catch errors as they are logged.
<Error>: This user is not allowed access to the window system right now.
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: Invalid Connection ID 0
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID.
<Warning>: CGSConnectionByID: 0 is not a valid connection ID
```

### Configuration Files

No fastlane file, using ```watchbuild```

Fastfile:
```ruby
No fastlane file
```

### Environment

watchbuild version (watchbuild -v):
```watchbuild 0.1.3```
Do you use bundler, rbenv or rvm?
```Bundler version 1.11.2```

**Comment by TKBurner** [comment]
@gran33 Thanks for reaching out! This seems like it's related to a notification setting locally on your machine. Regardless I'm going to have the team here look into this. Thanks!

**Comment by i2amsam** [comment]
@gran33 Hrm, odd.  Could you post the full output from running `watchbuild -v`?

Also, what version of terminal-notifier are you using (what is the output of `terminal-notifier --help | head -n 2`?

Also, what OS version are you running (what is the output of `sw_vers -productVersion`)?

Had this been working previously or has it never worked?  If it was working before, anything you think may have changed recently?
Thanks!

**Comment by KrauseFx** [comment]
Hey @gran33, is this still an issue? 👍

**Comment by gran33** [comment]
Not for me @KrauseFx , 10x!
