### ISSUE TITLE
Problem upload app with share extension

### ISSUE THREAD

**Issue by sarunw** [fastlane/fastlane#3955]
I just added app extension to my app and now I got error when try to submit to TestFlight

here is my fastfile

```
lane :staging do
    import_certificates
    sigh
    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

    gym(scheme: "my_scheme") # Build your app - more options available
    pilot(skip_submission: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
```

Error 
```
error: Embedded binary is not signed with the same certificate as the parent app. Verify the embedded binary target's code sign settings match the parent app's.
```

I guess its because provision profile, but don't sure about the proper way to fix this.

**Comment by TKBurner** [comment]
@sarunw Thanks for reaching out. It looks like your extension is not being signed with the same provisioning profile as your app. You'll need to configure this in Xcode. Let me know how it goes :+1: 

Closing this out for now, feel free to follow up.
