### ISSUE TITLE
[Feature Request] Pilot should truncate the changelog to 4000 characters

### ISSUE THREAD

**Issue by kcharwood** [fastlane/fastlane#3956]
### New Issue Checklist

- [Check] Updated fastlane to the latest version
- [Check ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Apple throws an error if your changelog is over 4000 characters. I found this out _after_ waiting 35 minutes for my build to process. It would be helpful if pilot truncated the changelog for me.

**Comment by TKBurner** [comment]
@kcharwood Thanks for reaching out! Interesting idea. The team here will look this over :+1:

**Comment by kcharwood** [comment]
Here is the error for reference:

`What to Test can't exceed 4000 characters.`

**Comment by kcharwood** [comment]
Something like this should do the trick, I just don't know where to put it :)

```Ruby
      max_changelog_length = 4000
      if whats_new && whats_new.length > max_changelog_length
        original_length = whats_new.length
        bottom_message = "...\n\nRelease notes have been truncated due to Apple's #{max_changelog_length} character limit"
        changelog = "#{whats_new[0...max-bottom_message.length]}#{bottom_message}"
        UI.important "Changelog has been truncated since it exceeds Apple's #{max_changelog_length} character limit. It currently contains #{original_length} characters."
      end   
```

**Comment by TKBurner** [comment]
Thanks @kcharwood! We'll look this over.

**Comment by ssuchanowski** [comment]
+1

**Comment by hjanuschka** [comment]
PR is here: https://github.com/fastlane/fastlane/pull/7187
