### ISSUE TITLE
Match: Certificate has either expired or has been revoked error

### ISSUE THREAD

**Issue by dpettit** [fastlane/fastlane#3968]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### I am now receiving "Unable to install "app" error whenever I attempt to run the app on my iPhone.  This device has been used successfully in the past without any problem.  The complete error is:

Unable to install "tsbook"
The certificate used to sign "tsbook" has either expired or has been revoked.  An updated certificate is required to sign and install the application.

I receive this error after running fast lane to build my app.  Not sure how to resolve the error.  Am I missing an extra step?  I've used fast lane for a couple of months now, and have submitted over 40 apps with it so far, but have never before encountered this issue.  Any ideas?

It was running just fine prior to updating to xCode 7.3.

##### Complete output when running fastlane, including the stack trace and command used

```
[22:54:03]: --- Step: Verifying required fastlane version ---
[22:54:03]: -------------------------------------------------
[22:54:03]: fastlane version valid
[22:54:03]: ------------------------------
[22:54:03]: --- Step: default_platform ---
[22:54:03]: ------------------------------
[22:54:03]: Driving the lane 'ios xcode' 🚀
[22:54:03]: ----------------------------------
[22:54:03]: --- Step: install_xcode_plugin ---
[22:54:03]: ----------------------------------
[22:54:03]: $ curl -Lso /var/folders/zl/vcygmmg97fbgyfzhqww098jc0000gx/T/plugin.zip https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip
[22:54:05]: $ unzip -qo '/var/folders/zl/vcygmmg97fbgyfzhqww098jc0000gx/T/plugin.zip' -d '/Users/tsdev/Library/Application Support/Developer/Shared/Xcode/Plug-ins'
[22:54:05]: Plugin FixCode.xcplugin installed successfully
[22:54:05]: Please restart Xcode to use the newly installed plugin

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | install_xcode_plugin                | 1           |
+------+-------------------------------------+-------------+

[22:54:05]: fastlane.tools finished successfully 🎉
[22:54:05]: -------------------------------------------------
[22:54:05]: --- Step: Verifying required fastlane version ---
[22:54:05]: -------------------------------------------------
[22:54:05]: fastlane version valid
[22:54:05]: ------------------------------
[22:54:05]: --- Step: default_platform ---
[22:54:05]: ------------------------------
[22:54:05]: Driving the lane 'ios development' 🚀
[22:54:05]: -------------------
[22:54:05]: --- Step: match ---
[22:54:05]: -------------------

+-----------------------+--------------------------------------------+
|                      Summary for match 0.4.0                       |
+-----------------------+--------------------------------------------+
| git_url               | git@github.com:talespring/certificates.git |
| type                  | development                                |
| app_identifier        | com.talespring.plessis.babe                |
| username              | <my.username>                |
| keychain_name         | login.keychain                             |
| readonly              | false                                      |
| team_id               | YNAERBDEVX                                 |
| team_name             | TaleSpring LLC                             |
| verbose               | false                                      |
| force                 | false                                      |
| shallow_clone         | false                                      |
| force_for_new_devices | false                                      |
| skip_docs             | false                                      |
+-----------------------+--------------------------------------------+

[22:54:05]: Cloning remote git repo...
[22:54:24]: 🔓  Successfully decrypted certificates repo
[22:54:24]: Verifying that the certificate and profile are still valid on the Dev Portal...
[22:54:26]: Installing certificate...
[22:54:27]: Installing provisioning profile...

+----------------------+----------------------------------------------+
|                   Installed Provisioning Profile                    |
+----------------------+----------------------------------------------+
| App Identifier       | com.talespring.plessis.babe                  |
| Type                 | development                                  |
| UUID                 | f1fa9018-0e39-4fbb-b17d-4f5d4207cd92         |
| Environment Variable | sigh_com.talespring.plessis.babe_development |
+----------------------+----------------------------------------------+

[22:54:29]: All required keys, certificates and provisioning profiles are installed 🙌
[22:54:29]: 🔒  Successfully encrypted certificates repo
[22:54:29]: Setting Provisioning Profile type to 'development'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 23          |
+------+-------------------------------------+-------------+

[22:54:29]: fastlane.tools finished successfully 🎉
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.52.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "tsbook") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
  	#increment_build_number
    match(type: "appstore")
    #snapshot
    gym
    produce(
    	username: '<my.username>',
    	app_identifier: 'com.talespring.plessis.babe',
    	app_name: 'Babe',
    	language: 'English',
    	app_version: '1.10',
    	sku: "791_1013_Babe"
    )
    deliver(
    submit_for_review: false,
    force: false
    )
    #frameit
  end
  
  desc "Install FixCode xcode plugin to disable Xcode 'Fix Issue' button"
  lane :xcode do
      install_xcode_plugin(
                           url: "https://github.com/fastlane/FixCode/releases/download/0.2.0/FixCode.xcplugin.zip"
                           )
  end
  
  desc "Create/retrieve certificates/provisioning profiles for development"
  lane :development do
      # Call match to retrieve development certificates/profiles.
      match(git_url: "git@github.com:talespring/certificates.git",
            type: "development")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

```
Matchfile:

git_url "git@github.com:talespring/certificates.git"	# One .git repo per team

type "appstore" 	# The default type, can be: appstore, adhoc or development

app_identifier "com.talespring.plessis.babe"      # The bundle id of the app
username "<my.username>"      # The Developer Portal Apple ID

# For all available options run `match --help`

---

### Environment

fastlane version (fastlane -v): 1.68.0
Do you use bundler, rbenv or ram? No.

iMac running El Capitan: version 10.11.4.
iOS device: iPhone 6 running iOS 9.2.1 and 9.3.

**Comment by TKBurner** [comment]
Hi @dpettit! Great to hear from you. Can you let me know what command you run to get this error? Also send over the full output when you get the error.

Thanks :+1:

**Comment by dpettit** [comment]
Thank you for responding!

I receive this error after fast lane has successfully run, when I attempt to use Xcode to load the app onto an actual device for testing.  I connect my iPhone to my iMac, then select my iPhone as the run device (instead of a simulator), and then click the play button (which builds and then runs the current scheme).

That's when I receive the message.  Here are screenshots, in case they help.

![screen shot 2016-03-29 at 10 00 06 am](https://cloud.githubusercontent.com/assets/403463/14114906/2db48dcc-f596-11e5-928a-7f9d94275758.png)

![screen shot 2016-03-29 at 10 03 04 am](https://cloud.githubusercontent.com/assets/403463/14114934/4d1939ec-f596-11e5-92ad-d46714fed44c.png)

**Comment by dpettit** [comment]
Do you have everything you need from me, or did you need additional information?  I suppose I could just "Nuke" all existing profiles again, and start over, but that seems a bit extreme to me.  

I've tried adding Match --force but that didn't change anything.  Is there a time limit on how long the provisioning profiles are good for?  If so, should the call to Match take care of renewing them, or does that require another step?

Sorry for all the questions, I'm just trying to understand what is hapenning.  I sincerely appreciate your help!  You have an AMAZING product: thank you for making it available to us!

**Comment by dpettit** [comment]
Sorry to bother you with this, but I was able to figure this out on my own.  Apparently, when I started working with Match, it created new certificates (as it should have).  The problem was, that I neglected to clear out my old certificates, which were revoked (by Match, I presume).  The conflict between certificates in my keychain access was causing the Xcode issue.

The first time around, Xcode did not issue the "multiple developer profiles" warning.  But when I checked it just now (for the nth time), the Xcode error actually surfaced, and I was able to trace the cause back to the fact that I now had multiple developer certificates in my keychain access.  Once I removed the revoked certificates, everything worked again.

Thank you for being willing to look into it, but it looks like were now good to go again.

As a suggestion, you may want to add something to the documentation that explains that when you use the match "Nuke" option, you should probably go into keychain access and remove your previously existing (but now revoked) certificates.

You guys are awesome!  Thank you again for FastLane!!!

**Comment by TKBurner** [comment]
Thanks for following up @dpettit! I'll make sure we make this more clear in the documentation. Hope that you have a great day! :+1:

**Comment by alper** [comment]
@dpettit I'm having the same issue as you and I'm trying to remove everything relevant from my keychain but it doesn't work. Do you have more information?

**Comment by TKBurner** [comment]
@alper I've followed up with you on #4203. Thanks!

**Comment by rmato** [comment]
I have this exact same problem.

I followed the steps. Match nuke development and Distribution, then re generated all certificates and profiles with Match appstore and development. And I CAN actually run my app in my computer.
But when I try to do this same thing in any other computer of my team, the error appears, and the other developer cannot run in Xcode.

I do the same steps: match appstore/development -read_only=true, then try to run in Xcode but it gives me the same error.

Maybe the p12 file is not correctly installed in the other machines? `match` command is not installing them?

**Comment by TKBurner** [comment]
@rmato Can you submit a new issue for this? Thanks!
