### ISSUE TITLE
Individual tool changelog?

### ISSUE THREAD

**Issue by doapp-ryanp** [fastlane/fastlane#3971]
Now that all tooling has been merged into the single fastlane repo, we have lost individual tool changelogs.  Is there a way to get at the individual tooling changelog or do you have to go through the release chain on the main repo?

For example, if I would like to see the version history and changelog for `pem` currently I have to keep clicking `next` on the [releases page](https://github.com/fastlane/fastlane/releases) until I find `pem`.  This makes it very difficult and time consuming to just find changes for a specific tool.

It would be cool if each tool had its own `changelog.md` file inside the tool sub directory

**Comment by mfurtak** [comment]
Hi @doapp-ryanp - thanks for the suggestion! :+1: 

We may transition to doing as you describe, but in the meantime, we're actually cross-posting release changelogs to all the tools' old repos as well! You can check out the `pem` releases' info over here: https://github.com/fastlane/pem/releases
