### ISSUE TITLE
Uploading Android builds to Crashlytics Beta using Fastlane crashes Fastlane

### ISSUE THREAD

**Issue by rinal6366** [fastlane/fastlane#3973]
### Issue Description
Trying to upload an apk file to Crashlytics Beta using fastlane crashes Fastlane.
##### Complete output when running fastlane, including the stack trace and command used
**Command Used:**
fastlane platform(android) lane(upload)

**Output**
```
[37m[11:25:26]: [0m[32m-------------------------------------------------[0m
[37m[11:25:26]: [0m[32m--- Step: Verifying required fastlane version ---[0m
[37m[11:25:26]: [0m[32m-------------------------------------------------[0m
[11:25:26]: fastlane version valid
[37m[11:25:26]: [0m[32m------------------------------[0m
[37m[11:25:26]: [0m[32m--- Step: default_platform ---[0m
[37m[11:25:26]: [0m[32m------------------------------[0m
[11:25:26]: [32mDriving the lane 'android upload' 🚀[0m
[37m[11:25:26]: [0m[32m-------------------------[0m
[37m[11:25:26]: [0m[32m--- Step: crashlytics ---[0m
[37m[11:25:26]: [0m[32m-------------------------[0m
[11:25:26]: [32mUploading the build to Crashlytics Beta. Time for some ☕️.[0m
[11:25:27]: [33m[33mVariable Dump:[0m[0m
[11:25:27]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android upload"}
[11:25:27]: [31mShell command exited with exit status 1 instead of 0.[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | crashlytics                         | 1           |
+------+-------------------------------------+-------------+

[11:25:27]: [31mfastlane finished with errors[0m
[33m-------------------------------------------------------------------------------------------[0m
[33m😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.[0m
[33m👍  This makes resolving issues much easier and helps improve fastlane.[0m
[33m🔒  The reports will be stored securely on getsentry.com.[0m
[33m🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3[0m
[33m-------------------------------------------------------------------------------------------[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/interface.rb:120:in `crash!': [31m[!] Shell command exited with exit status 1 instead of 0.[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/crashlytics.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
```

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
fastlane_version "1.68.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end
desc "Distribute a new Beta via Crashlytics"
  lane :upload do
    crashlytics(
      crashlytics_path: "project_path/fastlane/crashlytics-devtools.jar",
      apk_path: "apk_name", 
      groups: "newbuild",
      api_token: "token",
      build_secret: "build-secret"
      )
end

### Environment
Mac Os, using Unity 5.3.3p3 to build the apk.
fastlane version (fastlane -v):1.68.0
Do you use bundler, rbenv or rvm? No

**Comment by asfalcone** [comment]
@rinal6366 Thanks for the report.

Can you add `--verbose` to your `fastlane upload` command and paste the output? It looks like the command that we generate to call crashlytics is returning unexpected results.

**Comment by rinal6366** [comment]
@asfalcone here is the output of the verbose command.
Not much of a difference.

fastlane android upload --verbose
INFO [2016-03-29 10:40:00.75]: -------------------------------------------------
INFO [2016-03-29 10:40:00.75]: --- Step: Verifying required fastlane version ---
INFO [2016-03-29 10:40:00.75]: -------------------------------------------------
INFO [2016-03-29 10:40:00.75]: fastlane version valid
INFO [2016-03-29 10:40:00.75]: ------------------------------
INFO [2016-03-29 10:40:00.75]: --- Step: default_platform ---
INFO [2016-03-29 10:40:00.75]: ------------------------------
INFO [2016-03-29 10:40:02.31]: Driving the lane 'android upload' 🚀
INFO [2016-03-29 10:40:02.31]: -------------------------
INFO [2016-03-29 10:40:02.31]: --- Step: crashlytics ---
INFO [2016-03-29 10:40:02.31]: -------------------------
INFO [2016-03-29 10:40:02.50]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2016-03-29 10:40:02.50]: java -jar {Workspace}/fastlane/crashlytics-devtools.jar -androidRes . -apiKey "Apikey" 
  -apiSecret"ApiSecret"  
  -uploadDist 'apk_path' 
  -androidManifest '/var/folders/19/bxyf24g953q89x1s3hbqgkc80000gp/T/xml20160329-13450-1i4k9ld'              -betaDistributionGroupAliases 'newbuild' 
  -betaDistributionNotifications true
WARN [2016-03-29 10:40:04.05]: Variable Dump:
INFO [2016-03-29 10:40:04.05]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android upload"}
ERROR [2016-03-29 10:40:04.05]: Shell command exited with exit status 1 instead of 0.
INFO [2016-03-29 10:40:04.05]: Successfully generated documentation to path 'Workspace/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | crashlytics                         | 1           |
+------+-------------------------------------+-------------+

ERROR [2016-03-29 10:40:04.06]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'e4d4eddeb218ebec146ffc7965ad5903'
The crash report has been stored locally '/tmp/sentry_e4d4eddeb218ebec146ffc7965ad5903.json'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/interface.rb:120:in `crash!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/crashlytics.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.39.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by asfalcone** [comment]
Can you try running the Java command front this output directly and paste
the output here?

**Comment by rinal6366** [comment]
@asfalcone here is the output. Hope this helps.
ERROR - Crashlytics Developer Tools error.
com.crashlytics.tools.android.project.ManifestData$ManifestIOException: Crashlytics could not find the manifest. Not found at /var/folders/19/bxyf24g953q89x1s3hbqgkc80000gp/T/xml20160329-17261-1tyho9s
	at com.crashlytics.tools.android.project.ManifestFileProvider.getManifestStream(ManifestFileProvider.java:32)
	at com.crashlytics.tools.android.project.DefaultManifestData.createManifest(DefaultManifestData.java:124)
	at com.crashlytics.tools.android.project.StandardAndroidProjectFactory.createTypedProject(StandardAndroidProjectFactory.java:174)
	at com.crashlytics.tools.android.project.StandardAndroidProjectFactory.create(StandardAndroidProjectFactory.java:118)
	at com.crashlytics.tools.android.project.StandardAndroidProjectFactory.create(StandardAndroidProjectFactory.java:93)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:434)
	at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Crashlytics Developer Tools error.
	at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:307)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
Caused by: com.crashlytics.tools.android.project.ManifestData$ManifestIOException: Crashlytics could not find the manifest. Not found at /var/folders/19/bxyf24g953q89x1s3hbqgkc80000gp/T/xml20160329-17261-1tyho9s
	at com.crashlytics.tools.android.project.ManifestFileProvider.getManifestStream(ManifestFileProvider.java:32)
	at com.crashlytics.tools.android.project.DefaultManifestData.createManifest(DefaultManifestData.java:124)
	at com.crashlytics.tools.android.project.StandardAndroidProjectFactory.createTypedProject(StandardAndroidProjectFactory.java:174)
	at com.crashlytics.tools.android.project.StandardAndroidProjectFactory.create(StandardAndroidProjectFactory.java:118)
	at com.crashlytics.tools.android.project.StandardAndroidProjectFactory.create(StandardAndroidProjectFactory.java:93)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:434)
	at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
	... 1 more

**Comment by asfalcone** [comment]
@rinal6366 The error is 
```
Crashlytics could not find the manifest. Not found at /var/folders/19/bxyf24g953q89x1s3hbqgkc80000gp/T/xml20160329-17261-1tyho9s
```

This action [creates a temp file](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/crashlytics_helper.rb#L27) to represent the manifest to pass to the crashlytics.jar (then deletes it). When you call the jar manually you'll need to change the `androidManifest` to be a real file on disk. Doing that should give us the *real* underlying error! Let me know.

**Comment by rinal6366** [comment]
@asfalcone  is this androidManifest file something specific?

What information do I need to include in the manifest file?

Or it could just be a blank file?

**Comment by asfalcone** [comment]
@rinal6366 Just an empty xml file will satisfy the requirement!

**Comment by rinal6366** [comment]
@asfalcone 
Output:
WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /Users/autobuild/build-archives/RVM_Dev/RaceView-Development-RB-1709.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:617)
	at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /apk_Path/1709.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:615)
	... 2 more

**Comment by rinal6366** [comment]
@asfalcone 
Output
WARN - Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: /apk_path/1709.apk
Exception in thread "main" com.crashlytics.tools.android.exception.PluginException: Distribution upload failed.
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:617)
	at com.crashlytics.tools.android.DeveloperTools.processArgs(DeveloperTools.java:299)
	at com.crashlytics.tools.android.DeveloperTools.main(DeveloperTools.java:270)
Caused by: com.crashlytics.tools.android.exception.DistributionException: Crashlytics halted compilation because it can't extract Crashlytics build info from the APK: apk_path/1709.apk
	at com.crashlytics.tools.android.DistributionTasks.uploadDistribution(DistributionTasks.java:64)
	at com.crashlytics.tools.android.DeveloperTools.processProperties(DeveloperTools.java:615)
	... 2 more

**Comment by asfalcone** [comment]
@rinal6366 ah ok! now we're getting somewhere. 

If you open that apk you're trying to upload, in the assets directory you should be able to find a crashlytics-build.properties file that contains some build specific information. Can you verify if the file is there?

The error here is saying that this file isn't present (or couldn't be parsed) This file is generated via the Fabric gradle plugin. Can you confirm that you're using the Crashlytics SDK and building with the Fabric plugin?

**Comment by rinal6366** [comment]
Under the assets folder I do not see any crashlytics-build.properties.

Thanks @asfalcone.
Found some issues with my repo and now I am able to upload via fastlane.

You can close this issue.

**Comment by asfalcone** [comment]
:+1: Glad you're up and running!

**Comment by anback** [comment]
@rinal6366 , hello, i am having the exakt same issue and i cant solve it, can you briefly tell me what your issue was ?!?!

**Comment by rinal6366** [comment]
@anback 

I was missing the crashlytics-build.properties in my apk.

Just had to include them while building the apk package.
