### ISSUE TITLE
Some documentation that configuration files strip curly quotes would be nice

### ISSUE THREAD

**Issue by puls** [fastlane/fastlane#3976]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

While Fastlane's documentation doesn't—so far as I can tell—say that the configuration file language is plain Ruby, it's not such a stretch to assume that it is, especially given how many Rubyisms are peppered throughout the examples.

An examination of the source code reveals that the configuration file language is not plain Ruby but rather [Ruby with curly quotes replaced by straight quotes](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/configuration/configuration_file.rb#L15). And while I may personally disagree with this choice and the assumption that Fastlane's users can't figure out how text editors work, that's beside the point.

I'm just asking for some documentation of this feature so I could have avoided a bunch of extra work replacing all of my curly quotes with Unicode escapes. Judging by #1289, I'm not the first one who's been bitten by this, either.

Maybe the error message below could be changed to the following:
```
Your {filename} includes smart quotes, which may not be what you meant.
If you're sure you want smart quotes, you'll need to replace them with the
Unicode escape sequences \u2018, \u2019, \u201C, and \u201D;
otherwise, you should turn off smart quotes in your editor.
```

##### Complete output when running fastlane, including the stack trace and command used

```
[16:29:19]: Your Deliverfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Deliverfile:
```ruby
ipa "build/My App’s Name.ipa"
```

### Environment

fastlane version (fastlane -v): 1.68.0
Do you use bundler, rbenv or rvm? no

**Comment by KrauseFx** [comment]
Thanks for raising this concern, I can see that this results in unexpected side effects which we should fix. This was actually taken over from `danger` (https://github.com/danger/danger/blob/355ad2d2d40f3a171de35d1c18bfc18f9cdb7320/lib/danger/dangerfile.rb#L67).

We've had dozens of users that tried using smart quotes, since they opened the configuration files using TextEdit.

Your proposed message looks great to me, could you submit this change as a PR? :+1:

**Comment by RocketPop** [comment]
Or the smart quote removal could just be removed :wink:

**Comment by TKBurner** [comment]
@puls Let me know if you are interested in submitting a PR about this so we can expose your suggested error message. Thanks!

**Comment by ohwutup** [comment]
Going to close this issue for now as it has been quiet for a while. Please feel free to reopen it when a PR is ready!

**Comment by KrauseFx** [comment]
@RocketPop We had it turned off in the beginning and you can't imagine how many users ran into this problem. A majority of users use TextEdit to edit text files...
