### ISSUE TITLE
Error with Match and Xcode Server

### ISSUE THREAD

**Issue by aengel12** [fastlane/fastlane#3979]
### Error while using match, pilot and Xcode Server
i use a bot to trigger my fastlane. 
in my fastfile there is under beta

- match (type appstore)
- gym
- pilot

at first i start with these settings and the answer was, that there is no valid code signing. so i switched gym to type development and it worked great. the app is pushed to iTunes connect and everything was good. after the second run, i get the same error. so i switched back to type appstore.
until now it works great. but have anyone an idea why this is happen?

**Comment by asfalcone** [comment]
@aengel12 Can you provide additional information as requested in the issue template? https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md Thanks

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (491/400 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:50644 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKuQ-002ly1-V9
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:23:59 +0200
Date: Sat, 18 Jun 2016 11:23:13 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274193;
	bh=EzUEpymTh2DLZhmwoic2u6jr2Ywx8raFVpG0C5jXz7A=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=NIBKHsVV+gcAKHvfD6dca8Qk2rZzCUtk5DynHAm4dxjvNwZfY8vGbuqphoHJteYxy
	 qg4BKNSjgj8QtXgGutak0aIY3qeI+y5lIegzeB4beAmpXeSIitqenMlnYHrkS21fvb
	 u3ek+Fjgbef7UhuyIKODxtMZN4klRGE6ZrD8Vdcg=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (492/400 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o5.sgmail.github.com ([192.254.113.10]:22015)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKuU-002lyS-Qe
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:24:03 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=yNAT4OFG2wZu3z3djU+41AqH18c=; b=a7FtGcsrLvOW2KmV
	VL5j+eGSNJ2kteoHBI5ofgdTf2XFWbR/7MT/DngRiHOmgmW4LkYB2bvpZ/V+rMKd
	ELcdrmuO3OOqgqaI0whtkO4ZU5usMV6n0j0A9eKSkrfP9Iblr6zLTMwTdwU3q5W7
	di+7sUhKMDabRanBx3pvkTeMoQA=
Received: by filter0465p1mdw1.sendgrid.net with SMTP id filter0465p1mdw1.27772.5765919144
        2016-06-18 18:23:13.948135783 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0004p1iad1.sendgrid.net (SG) with ESMTP id bJX8HGaLSgSOxDY1WyZsQw
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:23:13.970 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:23:13 -0700
