### ISSUE TITLE
S3 action's ACL option does not apply to plist and html

### ISSUE THREAD

**Issue by alexspark** [fastlane/fastlane#398]
Given that I am working under the enterprise program,

If I specify the S3 action to upload the ipa under a ```private``` acl, then the plist and html are still publicly readable. Despite the ipa being inaccessible it might worry some security people the fact that there is an html and a plist acknowledging the existence of an ipa.

I suggest making the acl argument for the s3 action apply to all artifacts of the s3 action.
I'm open to discussion if some think the whole acknowledging ipa existence is a non-issue.

**Comment by ohwutup** [comment]
hey @alexspark this is a great idea IMO. i am going to mark this as an enhancement and we will see what we can do in a future release. we will reopen the issue to update it when we get a chance to come back to this. if you want to tackle this yourself, we would love it if you could submit a PR! checkout  [countdown](https://github.com/fastlane/countdown) to learn how to contribute to `fastlane`.
thanks! :100:
