### ISSUE TITLE
Pilot doesn't have submission_information option to accept Export Compliance for TestFlight Internal testing build distribution

### ISSUE THREAD

**Issue by CsabaSzabo** [fastlane/fastlane#3982]
### Issue Description

I cannot distribute builds with Pilot to TestFlight Internal testers as iTunes Connect introduced a new  Export Compliance page for TestFlight Internal tester distribution too and there's no `submission_information` option in pilot to handle it.

![testflight-internaltesting-notstarted](https://cloud.githubusercontent.com/assets/3639032/14140756/3d9a0dee-f67b-11e5-82e3-b6805c0ea7f9.png)

Deliver has a `submission_information` option: https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/options.rb#L114

Is there any workaround for that or should the `submission_information` be implemented for pilot too?

##### Output when running pilot

```
[37m[11:27:52]: [0mWaiting for iTunes Connect to process the new build
[37m[11:27:55]: [0mWaiting for iTunes Connect to process the new build
[37m[11:27:57]: [0mWaiting for iTunes Connect to process the new build
[37m[11:28:00]: [0mWaiting for iTunes Connect to process the new build
[37m[11:28:03]: [0mWaiting for iTunes Connect to process the new build
[37m[11:28:06]: [0mWaiting for iTunes Connect to process the new build
[37m[11:28:09]: [0mWaiting for iTunes Connect to process the new build
[37m[11:28:11]: [0mWaiting for iTunes Connect to process the new build
[37m[11:28:16]: [0mWaiting for iTunes Connect to finish processing the new build (xx.xx - xxxxxxxx)
[37m[11:28:16]: [0m[32mSuccessfully finished processing the build[0m
[37m[11:28:16]: [0mYou can now tweet: 
[37m[11:28:16]: [0m[33miTunes Connect #iosprocessingtime 23 minutes[0m
[37m[11:28:16]: [0mDistributing new build to testers
[31m
[!] The request could not be completed because:
	You must provide an answer for this question. You must provide an answer for this question.[0m
```

### Commands

Bash commands:
```bash
pilot upload \
	--username "xxx@xxx.xxx" \
	--ipa "$(path bin)/$SCHEME-$TAG.ipa"
```

### Environment

fastlane 1.67.0
pilot 1.4.1

**Comment by aln787** [comment]
@CsabaSzabo you need to add this flag to your project.

```
#Adding the encryption flag
/usr/libexec/PlistBuddy -c "Add :ITSAppUsesNonExemptEncryption bool false" $PROJECT_NAME-Info.plist
```

[This SO post](http://stackoverflow.com/questions/35739361/itsappusesnonexemptencryption-export-compliance-while-internal-testing) goes into greater detail around what this flag indicates.

**Comment by TKBurner** [comment]
@CsabaSzabo Thanks for reaching out. Can you try the fix mentioned by @aln787? Thanks! Closing this issue out until you update.

**Comment by CsabaSzabo** [comment]
Thanks @aln787 and @TKBurner, it resolved the issue.

**Comment by TKBurner** [comment]
@CsabaSzabo Awesome! Glad to hear you are up and running :+1:
