### ISSUE TITLE
Is there a way to get the seller name, before doing Produce?

### ISSUE THREAD

**Issue by nAviram** [fastlane/fastlane#3983]
Hi!
Is there a way to get the seller name, before doing Produce?
I saw in case of multiple teams on the same account - it gives you a list of seller names to choose from.
Is there a way to do it, even when there's no multiple teams?
Thanks!

**Comment by TKBurner** [comment]
Hi @nAviram Thanks for reaching out. Right now it's not possible to get this print out when you run produce if you have only one seller. We are going to look at this as a feature request. Let me know if you have any other questions :+1:
