### ISSUE TITLE
exception while verifying: undefined method `size' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by i-phil** [fastlane/fastlane#3985]
ERROR:  Error installing fastlane:
	invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /usr/local/lib/ruby/gems/2.3.0/cache/fastlane-1.64.0.gem

**Comment by asfalcone** [comment]
@i-phil Can you provide additional information as requested in the issue template? https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md

**Comment by KrauseFx** [comment]
Closing this issue for now, please submit a new one
