### ISSUE TITLE
Frameit multiline interline spacing

### ISSUE THREAD

**Issue by jvanzummeren** [fastlane/fastlane#3987]
I'm trying to use frame-it for my screenshots which is working out pretty well since you added the multi-line support. For me there's just one point missing; being able to add spacing between lines.
I managed to edit my own editor.rb file for now, but i think it would be great if it this was added to the library

This change will allow a new config in the Framefile.json
```  "interline_spacing": 24 ```

https://github.com/fastlane/fastlane/pull/3989/commits/44b4a45d5a56f327cadc7b75041706aaea137878

Thanks!

**Comment by TKBurner** [comment]
@jvanzummeren Thanks for this feature request. the team will review it :+1:
