### ISSUE TITLE
I couldn't find the latest version on gems .  Only find the version 1.64

### ISSUE THREAD

**Issue by FlyingNoob** [fastlane/fastlane#3991]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v):
Do you use bundler, rbenv or rvm?

**Comment by TKBurner** [comment]
@FlyingNoob Thanks for reaching out. What happens if you run 'gem update fastlane'?

Thanks!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (493/400 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:51441 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKuW-002lzF-Hj
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:24:04 +0200
Date: Sat, 18 Jun 2016 11:23:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274199;
	bh=x8zImciotdJMbZb8ViFKxBirdF33oihnW+w/wvMt4hQ=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LXzoujXG8U3ETgIXcUFRmlyXQKOEXqMlD8yRkSSVlkYJybMW4VxCs9PXpMBaU8juK
	 CQ2rg9al4oAZ6fLJxGGZt85R9KmDYUBpTNRwBWrtQ2bvNQAJHEB4yZ1g/RuulVZ3Gl
	 5xms4m8Zpt1pIRlMGso8sDoWLxemd/eZAZFri8uc=
