### ISSUE TITLE
fastlane doesn't fetch version from ipa

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#401]
Here is my lane:

      desc "Deploy w/o screenshots"
      lane :just_deploy do
        deliver(skip_deploy: true)
      end

after successful building I got a message:

[15:58:00]: ---------------------
[15:58:00]: --- Step: deliver ---
[15:58:00]: ---------------------
[15:58:01]: Skipping submission of app update
[15:58:01]: Got all information needed to deploy a new update ('') for app 'myapp'

And here is empty version string. Thus it fails in next step, by trying create new version with empty string.

    fastlane_version "1.7.0"

**Comment by KrauseFx** [comment]
I'm using the following code to detect the version information:

```ruby
# Fetches the app version from the given ipa file.
    def self.fetch_app_version(path)
      plist = IpaFileAnalyser.fetch_info_plist_file(path)
      return plist['CFBundleShortVersionString'] if plist
      return nil
    end

    def self.fetch_info_plist_file(path)
      Zip::File.open(path) do |zipfile|
        zipfile.each do |file|
          if file.name.include?'.plist' and not ['.bundle', '.framework'].any? { |a| file.name.include?a }
            # We can not be completely sure, that's the correct plist file, so we have to try
            begin
              # The XML file has to be properly unpacked first
              tmp_path = "/tmp/deploytmp.plist"
              File.write(tmp_path, zipfile.read(file))
              system("plutil -convert xml1 #{tmp_path}")
              result = Plist::parse_xml(tmp_path)
              File.delete(tmp_path)

              if result['CFBundleIdentifier'] or result['CFBundleVersion']
                return result
              end
            rescue
              # We don't really care, look for another XML file
            end
          end
        end
      end
```

It seems like it can't find your `plist` file for some reason. Can you take a look inside your `ipa` file if you have multiple `plist` files or your `plist` file is inside some folder?

**Comment by skywinder** [comment]
Here is my steps: 

- Unarchive ipa file
- go into and run `find . -name "*.plist"`

Here is output:

>./Payload/AppName.app/ApptentiveResources.bundle/ATDataModel.momd/VersionInfo.plist
./Payload/AppName.app/ApptentiveResources.bundle/Info.plist
./Payload/AppName.app/Base.lproj/MainStoryboard~ipad.storyboardc/Info-8.0+.plist
./Payload/AppName.app/Base.lproj/MainStoryboard~ipad.storyboardc/Info.plist
./Payload/AppName.app/Base.lproj/MainStoryboard~iphone.storyboardc/Info-8.0+.plist
./Payload/AppName.app/Base.lproj/MainStoryboard~iphone.storyboardc/Info.plist
./Payload/AppName.app/Info.plist

I believe you need to use `./Payload/AppName.app/Info.plist`

And it's contents version as expected.

**Comment by KrauseFx** [comment]
How should `deliver` know which `plist` to use?

**Comment by KrauseFx** [comment]
I haven't found the best way for it yet.

**Comment by skywinder** [comment]
So, what the solution for that case?
It seems that `./Payload/AppName.app/` should be default path to get proper plist file.

**Comment by skywinder** [comment]
@KrauseFx Just test `deliver` separately, and it's works correctly! So the problem somewhere in `fastlane`

**Comment by skywinder** [comment]
Let me know, if I can provide some useful information to debug this case.

**Comment by pzbyszynski** [comment]
+1

Here is my output:
./PerfectGymGo.app/Base.lproj/MainStoryboard.storyboardc/Info.plist
./PerfectGymGo.app/Info.plist
./PerfectGymGo.app/NBPhoneNumberMetadata.plist
./PerfectGymGo.app/PerfectMe.momd/VersionInfo.plist

**Comment by jondot** [comment]
@KrauseFx wouldn't the path with the least number of segments be the one to pick, always?

**Comment by KrauseFx** [comment]
@jondot doesn't sound like a good solution. Currently `deliver` iterates through all available plist files and uses the one with the values that we're looking for. I don't know why it's not working on all setups yet.

**Comment by skywinder** [comment]
try to workaround it by using  `sh("cd .. && deliver")` instead of `deliver` command, but it's hang on.

**Comment by simoncoulton** [comment]
Also coming here to mention this is affecting me as well, building from Xcode works fine however. I can submit new builds to TestFlight in my `fastlane ios beta` command, but `fastlane ios deploy` seems to give the original issue that @skywinder mentioned. `agvtool what-marketing-version` does return the correct version number as well.

```ruby
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    cert(
      output_path: "../certificates"
    )
    sigh(
      output_path: "certificates",
      filename: "beta.mobileprovision",
      force: true
    )
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    increment_build_number
    ipa
    deliver(beta: true)
  end
```

```ruby
  desc "Deploy a new version to the App Store"
  lane :deploy do
    sigh(
      output_path: "certificates",
      filename: "prod.mobileprovision",
      force: true
    )
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    ipa
    deliver(skip_deploy: true, force: true)
  end
```

Using @skywinder's workaround above does seem to work though.

On a side note, the differing output_path for cert and sigh is a little odd, should the way these work be consistent?

**Comment by KrauseFx** [comment]
@simoncoulton 
> On a side note, the differing output_path for cert and sigh is a little odd, should the way these work be consistent?
Could you clarify? What's different?

**Comment by simoncoulton** [comment]
The output_path's are different, `certificates` vs `../certificates` in the `beta` lane. If I made them the same, I got an error about one of the directories not existing (it would create the cert one within /fastlane/certificates, where as sigh would create it in the parent of /fastlane).

@skywinder's original issue is occurring with the latest fastlane and deliver.

**Comment by JaviSoto** [comment]
Hi!
I'm going through some old issues to check up on them. Is this still an issue? Thanks! :)

**Comment by skywinder** [comment]
Still an issue.
To reproduce `'2b7e001cb0521d8257f084bcbd5f7a83'`

```
fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '2b7e001cb0521d8257f084bcbd5f7a83'
The crash report has been stored locally '/tmp/sentry_2b7e001cb0521d8257f084bcbd5f7a83.json'
```

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
