### ISSUE TITLE
crashlytics action fails when setup_jenkins enabled

### ISSUE THREAD

**Issue by dodikk** [fastlane/fastlane#4022]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The job fails when `setup_jenkins` is enabled.
Otherwise it succeeds but I want all artefacts stored in a single directory.

##### Complete output when running fastlane, including the stack trace and command used
```
/usr/local/bin/fastlane build_deploy --verbose
```
https://gist.github.com/dodikk/aefa4db8a5532cb220027cb7b29c3f54

### Environment
```
fastlane --version
fastlane 1.70.0
```

> Do you use bundler, rbenv or rvm?

No

**Comment by TKBurner** [comment]
Hi @dodikk hope you are doing well! Can you try setting the parameters, output_directory and derived_data_path?

That should let you get up and running :+1:

**Comment by dodikk** [comment]
> Can you try setting the parameters,  `output_directory` and `derived_data_path`?

@TKBurner , thanks for the reply.
Which action are you referring to? Which line of my fast file should I look at?

**Comment by TKBurner** [comment]
@dodikk This is on the setup_jenkins action. Let me know how it goes :+1:

**Comment by asfalcone** [comment]
@dodikk  The underlying error seems to be coming from `gym`, in the `move_ipa` method
```
ArgumentError: same file: /Users/Shared/Jenkins/jenkins_fastlaneworkspace/OlaCabs_ios_app/output/OlaCabs-Debug.ipa and /Users/Shared/Jenkins/jenkins_fastlaneworkspace/OlaCabs_ios_app/output/OlaCabs-Debug.ipa
```
It is trying to move the generated ipa to `Gym.config[:output_directory]` but they're the same.

Hope this helps!

**Comment by TKBurner** [comment]
@dodikk Let me know if you got up and running! Thanks 👍

**Comment by dodikk** [comment]
>> It is trying to move the generated ipa to Gym.config[:output_directory] but they're the same.

@asfalcone , not sure how I can apply this information.


>> @dodikk Let me know if you got up and running! 

We used `copy_artifacts` action to achieve the results.
`setup_jenkins` is no more used in our builds.

Sorry for replying this much late.

**Comment by asfalcone** [comment]
You need to add `output_directory` param to `setup_jenkins` [here](https://gist.github.com/dodikk/aefa4db8a5532cb220027cb7b29c3f54#file-fastfile-rb-L7) and set it to something other than "./output" which is where gym is already putting the .ipa. Let me know if setting that changes the behavior. 👍  Thanks.

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
