### ISSUE TITLE
nexus_upload action requires specific classifier

### ISSUE THREAD

**Issue by alexeychirkov** [fastlane/fastlane#4023]
It would be good to have a possibility to pass custom classifier when uploading a file using `nexus_upload` action.
I guess its a `c` [parameter name](https://repository.sonatype.org/nexus-restlet1x-plugin/default/docs/path__artifact_maven_content.html)

**Comment by alper** [comment]
I implemented this parameter ([API documentation](https://support.sonatype.com/hc/en-us/articles/213465818-How-can-I-programatically-upload-an-artifact-into-Nexus-)).

**Comment by TKBurner** [comment]
@alexeychirkov Thanks for reaching out. We'll review this as a feature request and follow up on this thread. In the meantime you should check out @alper's solution!

@alper Thanks for stepping in 👍
