### ISSUE TITLE
nil token for current process reference

### ISSUE THREAD

**Issue by PeterWong2015** [fastlane/fastlane#4039]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```
▸ Touching xxxxxxxxxx.xctest
** TEST FAILED **

testExample, UI Testing Failure - Failure attempting to launch XCUIApplicationImpl: 0x7f9a540432e0  xxxxxxxxxx at /var/folders/fq/w918t4gx1ml9254rk4nn5qkc0000gn/T/snapshot_derived20160403-60672-5vckqu/Build/Products/Debug-iphonesimulator/ xxxxxxxxxx.app, nil token for current process reference XCUIApplicationProcess: 0x7f9a54003dd0  xxxxxxxxxx (64407)

/Library/Ruby/Gems/2.0.0/gems/snapshot-1.12.1/lib/snapshot/runner.rb:52:in `work': [!] Tests failed - check out the log above (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/actions/snapshot.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:39:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.70.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

### Configuration Files

 scheme "xxxxxxxxxx"

 devices([
   "iPhone 6"
 ])

languages([
  "en-US"
])

ios_version '9.0'
### Environment
xCode 7.3
snapshot 1.12.1
fastlane version (fastlane -v):1.70.0
Do you use bundler, rbenv or ram?

**Comment by TKBurner** [comment]
Hi @PeterWong2015! Great to hear from you. Can you let me know if you can run these tests from Xcode? That'll let us know if it is an issue wit snapshot or with your project config.

Thanks!

**Comment by PeterWong2015** [comment]
Hi, it cannot pass the test in Xcode.


- (void)setUp {
    [super setUp];
    
    // Put setup code here. This method is called before the invocation of each test method in the class.
    
    // In UI tests it is usually best to stop immediately when a failure occurs.
    self.continueAfterFailure = NO;
    // UI tests must launch the application that they test. Doing this in setup will make sure it happens for each test method.
    XCUIApplication *app = [[XCUIApplication alloc] init];
    [Snapshot setLanguage:app];
    [app launch];
    // In UI tests it’s important to set the initial state - such as interface orientation - required for your tests before they run. The setUp method is a good place to do this.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testExample {
    // Use recording to get started writing UI tests.
    // Use XCTAssert and related functions to verify your tests produce the correct results.
    [Snapshot snapshot:@"0" waitForLoadingIndicator:NO];
    
}

**Comment by TKBurner** [comment]
Hi @PeterWong2015! Thanks for following up. These tests need to pass in Xcode before you can run snapshot. Can you edit the tests to make them pass and try again?

Thanks!

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (494/400 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:52312 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKub-002m1c-NY
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:24:10 +0200
Date: Sat, 18 Jun 2016 11:23:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274204;
	bh=rlf/FywaCTrqtGo66g5lY9kk6tkv9hc0FSTl6cAZ0lk=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tYjcZDLrg5pnlOlah3Qlk4DQJqexmgvYp4mUTk+hlY8z2koRL+OvCvxkl+S6bNFQZ
	 ZVrudEV49s81EAgJj4L2mpu9HX3N1p5YIJGERPT3c75hwB7ilah0SceT6DW7/esT6Q
	 Jnd4lIjCm1RjcHDrd/nLr2PP+YPRW8GkdWYCYS+4=

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (495/400 (123%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:52333 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1bEKub-002m1e-My
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:24:11 +0200
Date: Sat, 18 Jun 2016 11:23:24 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1466274204;
	bh=0JOIfNrE63sBn4MbBDoLRlI8LRIYex8on3UYn/QqPbU=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=lA0SVVwmr//T8A4mdX/CgmmbQB7mXe7uPQ3DF+wUQdyvwDykShW3QFLeoxliZoDBc
	 f3z/xDNuimDMKD+p2vPs0YvfMJwqDAzmRKZcBvlo4eArU5q2utLVI9Sni5nWvodRKB
	 rOteexyqEwWXzQfePAnP8mPWMmcEFJTNzaQo8I3A=
