### ISSUE TITLE
ScreenGrab Android -Failed to sync gradle project - could not find tools.fastlane:screengrab:0.3.0

### ISSUE THREAD

**Issue by GarrettStrobel** [fastlane/fastlane#4046]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hello I am attempting to integrate ScreenGrab into an existing android project for capturing localization screenshots.  
When I add  androidTestCompile 'tools.fastlane:screengrab:0.3.0' 
to gradle build and attempt to sync I get the error: 
Failed to sync Gradle project 'xyz'
could not find tools.fastlane:screengrab:0.3.0

I have even tried dropping my appCompat library versions down to 23.1.1

I have tested integrating ScreenGrab into a new blank test project with appCompat libraries at version 23.1.1 and gradle built successfully. Wondering if there could be a problem with another dependency.

##### Complete output when running fastlane, including the stack trace and command used
```
Error:Could not find tools.fastlane:screengrab:0.3.0.
Required by:
    XYZAndroid:xyz:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

here are some other snippets of my gradle configuration:
```
compileSdkVersion 23
buildToolsVersion "23.0.3"
minSdkVersion 18
targetSdkVersion 22


dependencies {
    apt "org.androidannotations:androidannotations:3.3.2"
    androidTestCompile 'junit:junit:4.+'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    androidTestCompile 'tools.fastlane:screengrab:0.3.0'
    compile 'org.androidannotations:androidannotations-api:3.3.2'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'org.springframework.android:spring-android-rest-template:1.0.1.RELEASE'
    compile 'org.springframework.android:spring-android-auth:1.0.1.RELEASE'
    compile 'org.springframework.android:spring-android-core:1.0.1.RELEASE'
    compile('com.crashlytics.sdk.android:crashlytics:2.2.1@aar') {
        transitive = true;
    }

```
### Environment
Android
Gradle plugin version 
1.5.0
android-apt plugin 
classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'

**Comment by GarrettStrobel** [comment]
The issue was obvious in retrospect.  The existing project was not using jcenter repository, only mavenCentral.  adding jcenter to the build script fixed the issue. This can be closed.

**Comment by mfurtak** [comment]
Glad you're up and running! :+1:

**Comment by vikram1234** [comment]
@GarrettStrobel - how it worked, i have below config in gradle build and still have same issue

 repositories {
        mavenCentral()
        jcenter()
    }

Could you suggest what fix you did?

**Comment by GarrettStrobel** [comment]
Try including it in
allprojects {
       repositories {

In your project level gradle file.

**Comment by vikram1234** [comment]
@GarrettStrobel thanks for your reply, Its not finding screengrab jar file, its not in android tools too, not sure why it not loading jar or i have to manually
@RunWith(JUnit4.class)
 ^
  symbol: class RunWith
JUnit4StyleTests.java:9: error: cannot find symbol
    public static final LocaleTestRule localeTestRule = new LocaleTestRule();
                        ^
  symbol:   class LocaleTestRule
  location: class JUnit4StyleTests
JUnit4StyleTests.java:12: error: cannot find symbol

**Comment by TKBurner** [comment]
@vikram1234 Thanks for following up. Did you add the jcenter repo?

**Comment by vikram1234** [comment]
Thanks @TKBurner for the reply, i am able to fix that by adding this repo but keep getting another error. 

03:36:03]: ▸ INSTRUMENTATION_STATUS: id=ActivityManagerService
[03:36:03]: ▸ INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.pap.pkg.test/android.support.test.runner.AndroidJUnitRunner}
[03:36:03]: ▸ INSTRUMENTATION_STATUS_CODE: -1
[03:36:03]: ▸ android.util.AndroidException: INSTRUMENTATION_FAILED: com.pap.pkg.test/android.support.test.runner.AndroidJUnitRunner
[03:36:03]: ▸ at com.android.commands.am.Am.runInstrument(Am.java:977)
[03:36:03]: ▸ at com.android.commands.am.Am.onRun(Am.java:317)
[03:36:03]: ▸ at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
[03:36:03]: ▸ at com.android.commands.am.Am.main(Am.java:97)
[03:36:03]: ▸ at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
[03:36:03]: ▸ at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

Also test apk is only in KB's, is that how it works? 

Thanks for all your help.

**Comment by vikram1234** [comment]
All set now.... thanks @TKBurner
