### ISSUE TITLE
spaceship on master: sigh doesn't work without iTunes Connect account

### ISSUE THREAD

**Issue by bartoszj** [fastlane/fastlane#4049]
Hi,

Shortly:
Sine `sigh` 1.6.x it is not possible to download provisioning profile using Apple ID which doesn't have access to iTines Connect.

If the Apple ID has access to the iTunes Connect it is possible to download or create provisioning profile using `sigh`, this is normal behaviour. But in my case, I've special user (Apple ID) which has only access to Member Center / Developer Program which is used to download provisioning profiles and use them in the Jenkins node. With this account I'm not able to download any provisioning profile. This issue doesn't occur on the `sigh` 1.5.x and it is probably related to the new `spaceship` which can handle "two factor authentication". As I saw in the code, `spaceship`/`sigh` tries to login to the iTunes Connect which in my case always fails.

Console log:
```
/lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/client.rb:407:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
	authentication.failed
	Your session has expired.  Please log in.
	from /lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/portal/portal_client.rb:41:in `teams'
	from /lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/portal/portal_client.rb:57:in `select_team'
	from /lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:16:in `run'
	from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/manager.rb:7:in `start'
	from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:35:in `block (2 levels) in run'
	from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:93:in `run'
	from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:111:in `<top (required)>'
	from /bin/sigh:23:in `load'
	from /bin/sigh:23:in `<main>'
```

Spaceship log:
[spaceship1459794302_34489.txt](https://github.com/fastlane/fastlane/files/203166/spaceship1459794302_34489.txt)

**Comment by asfalcone** [comment]
@bartoszj can you uninstall the `sigh` 1.6.1, install 1.5.0 and try again? There **shouldn't** have been any changes to `sigh` in these versions that should change authentication, so I'm intereted to see results. The changes for [2 step](https://github.com/fastlane/fastlane/pull/3854) were merged 6 days ago but haven't been released yet (spaceship 0.24.1 was released [12 days ago](https://github.com/fastlane/fastlane/releases/tag/spaceship%2F0.24.1)) but you could also roll back the spaceship version and see if you get different output!

**Comment by TKBurner** [comment]
Thanks for reaching out @bartoszj! I'm going to have the team here look this over. :+1:

**Comment by bartoszj** [comment]
After my tests this my summary:

`sigh` | `spaceship` | Results
---|---|---
`1.6.1` | `0.24.1` | Fails, but with different error `[1]`
`1.5.0` | `0.24.1` | Fails, but with different error `[1]`
`master` | `0.24.1` | Fails, but with different error `[1]`
`1.6.1` | `master` | Fails with original error
`1.5.0` | `master` | Fails with original error
`master` | `master` | Fails with original error

The issue comes from `spaceship`, not from the `sigh` and it is related to the version on the `master` branch, not to the released version. So, I'm really sorry that I didn't check it more precisely. I'll change the issue name.

The error marked as `[1]` is something new and it is related to the changes on the "developer portal" and keychain configuration. I'll create separate task for it but you can check stack trace below:

Error `[1]`:
```
/lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/portal/portal_client.rb:311:in `download_certificate': [!] Couldn't download certificate, got this instead: {"responseId"=>"abcea721-85af-4dd3-9536-fd44627ec39b", "resultCode"=>1200, "resultString"=>"webservice.certificate.downloadNotAllowed", "userString"=>"You are not permitted to download this certificate.", "creationTimestamp"=>"2016-04-05T19:48:46Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/downloadCertificateContent.action", "httpCode"=>200} (Spaceship::Client::UnexpectedResponse)
    from /lib/ruby/gems/2.2.0/gems/spaceship-0.24.1/lib/spaceship/portal/certificate.rb:309:in `download_raw'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:87:in `block (2 levels) in fetch_profiles'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:85:in `each'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:85:in `block in fetch_profiles'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:82:in `each'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:82:in `find_all'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:82:in `fetch_profiles'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:20:in `run'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/manager.rb:7:in `start'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:35:in `block (2 levels) in run'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:93:in `run'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:111:in `<top (required)>'
    from /bin/sigh:23:in `load'
    from /bin/sigh:23:in `<main>'
```

**Comment by asfalcone** [comment]
Thank you for the updated and precise reporting @bartoszj!!

**Comment by KrauseFx** [comment]
I just worked on https://github.com/fastlane/fastlane/pull/4091, would you mind giving it a try?

**Comment by bartoszj** [comment]
Hi,

Unfortunately it didn't help. I'm still getting this issue using `spaceship` **0.25.0**.

Stack trace:
```
/lib/ruby/gems/2.2.0/gems/spaceship-0.25.0/lib/spaceship/client.rb:427:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
    authentication.failed
    Your session has expired.  Please log in.
    from /lib/ruby/gems/2.2.0/gems/spaceship-0.25.0/lib/spaceship/portal/portal_client.rb:51:in `teams'
    from /lib/ruby/gems/2.2.0/gems/spaceship-0.25.0/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
    from /lib/ruby/gems/2.2.0/gems/spaceship-0.25.0/lib/spaceship/portal/portal_client.rb:67:in `select_team'
    from /lib/ruby/gems/2.2.0/gems/spaceship-0.25.0/lib/spaceship/portal/spaceship.rb:37:in `select_team'
    from /lib/ruby/gems/2.2.0/gems/spaceship-0.25.0/lib/spaceship/portal/spaceship.rb:81:in `select_team'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/runner.rb:16:in `run'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/lib/sigh/manager.rb:7:in `start'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:35:in `block (2 levels) in run'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
    from /lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:93:in `run'
    from /lib/ruby/gems/2.2.0/gems/sigh-1.6.1/bin/sigh:111:in `<top (required)>'
    from /bin/sigh:23:in `load'
    from /bin/sigh:23:in `<main>'
```

**Comment by TKBurner** [comment]
@bartoszj Thanks so much for following up. We are going to look into this!

**Comment by KrauseFx** [comment]
@bartoszj Can you try yesterday's `spaceship` and clear your cache by restarting your Mac?

**Comment by bartoszj** [comment]
Hi,

I've removed `~/.spaceship`, `~/Library/Caches/spaceship_api_key.txt` and restarted my Mac, and it didn't help. I've tested this scenario on three different Macs with the same result.

This Apple ID which I'm using is added to two developer portals and it was never added to iTunes Connect. I don't know what I can write more to help you with this issue.

**Comment by mindrunner** [comment]
I am facing a similar issue here. I do not really know weather its related or not. My developer account is part of a big organization and in more than one teams. The Account does not have Admin rights, but permissions to manage the apps it is supposed to manage. Downloading provisioning profiles manually seems to  work. Also I can login to Itunes Connect AND developer portal. Though, sigh is always failing with the following error:

````
[14:08:43]: Successfully logged in
[14:08:43]: Fetching profiles...
[14:08:50]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[14:08:53]: Variable Dump:
[14:08:53]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios continuous", :XCODE_INSTALL_XCODE_PATH=>#<Pathname:/Applications/Xcode.app>}
[14:08:53]: Couldn't download certificate, got this instead: {"responseId"=>"265f3fe4-67b9-4250-b1f5-3c32bd104b50", "resultCode"=>1200, "resultString"=>"webservice.certificate.downloadNotAllowed", "userString"=>"You are not permitted to download this certificate.", "creationTimestamp"=>"2016-04-11T12:08:53Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/downloadCertificateContent.action", "httpCode"=>200}
````

**Comment by bartoszj** [comment]
Hi @mindrunner 
I've figure out what is the problem with "You are not permitted to download this certificate.". You, as a member on developer portal, are not able to download Distribution Certificate and validate provisioning profile. To make this working use `skip_certificate_verification: true` in the Fastfile or `--skip_certificate_verification` from the command line.

**Comment by KrauseFx** [comment]
@bartoszj @mindrunner This is not related to the new 2 step verification process, right?

**Comment by bartoszj** [comment]
Yes, this is another issue, not related to my original report with:
```
authentication.failed
Your session has expired.  Please log in.
```

**Comment by mindrunner** [comment]
@KrauseFx No 2-Factor activated here!
@bartoszj Cheers! Will check that one out!

**Comment by TKBurner** [comment]
@mindrunner Thanks for working with us. The team is still looking into this but we hope to have an update for you soon. Thanks for using Fastlane!

**Comment by i2amsam** [comment]
@bartoszj could you try the steps from here?  https://github.com/fastlane/fastlane/issues/4157#issuecomment-208559847 sounds like logging in once fixed the problem.

**Comment by bartoszj** [comment]
Hi,
I had to add my "Jenkins" Apple ID to the iTunes Connect to fix this issue. Right now I'm not able to reproduce this issue anymore, so lets assume that #4157 fixes my problem. If I have this issue once again I'll just reopen or create new task.

Thanks for your time and help ;)

**Comment by TKBurner** [comment]
@bartoszj Thanks!

**Comment by mindrunner** [comment]
Looks like my problem (at least this one) is gone.
