### ISSUE TITLE
Unable to create tester user with role App Manager

### ISSUE THREAD

**Issue by hzalaz** [fastlane/fastlane#4052]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When the iTunes Connect user has App Manager role, it can't create a user using `spaceship` but you can create one using the web interface.

##### Complete output when running fastlane, including the stack trace and command used

```
[3] pry(#<PryNav::Tracer>)> Spaceship::Tunes::Tester::External.create!(email: "mail@domain.com",
[3] pry(#<PryNav::Tracer>)*   first_name: John",                                      
[3] pry(#<PryNav::Tracer>)* last_name: "Doer")                                         
Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"}
from /Users/<username>/.gem/ruby/2.1.2/gems/spaceship-0.24.1/lib/spaceship/client.rb:328:in `parse_response'
```

### Environment

fastlane version (fastlane -v):
fastlane 1.70.0
Do you use bundler, rbenv or rvm?
yes

**Comment by samrobbins** [comment]
Hey @hzalaz! When I sign in with an account that is only an App Manager I don’t have an option to add an account wide TestFlight Beta Tester. I can add an external tester to an app though. Have you tried this? I'm going to confirm that works for me via spaceship.

**Comment by hzalaz** [comment]
Hi @samrobbins, yeah that makes sense. I was actually checking why I boarding failed with a user of this role and I ended up trying this in spaceship to see what was wrong and since boarding creates the user without the app, didn't try specifying an app. Will try that today.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (496/400 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o1.sgmail.github.com ([192.254.114.176]:63027)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKuj-002m3Q-Bh
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:24:17 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=sk9fbWYXFfJyhEZQbNZ11rzOE6c=; b=UvSjJG2SkkF8iYOB
	Tqt5d0IiZBeawssozqu1M29I9nc5rXNPsT7DWdkKY/MnUW3TLXbxII8SqPDVtq6g
	A2BbTYOApCEqMxnZT7JwGwLcz8Ra1oq2uy0w/+7ODsHno0bd9ISwBqXpmVKbxK18
	2BCNFktpaHSeYrmgFlLjBgCKBUE=
Received: by filter0569p1mdw1.sendgrid.net with SMTP id filter0569p1mdw1.19259.576591A13D
        2016-06-18 18:23:29.722289158 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd0002p1iad1.sendgrid.net (SG) with ESMTP id oaIvKjZFTgW0GPD80yUWpA
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:23:29.618 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:23:29 -0700

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (497/400 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:1895)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <bounces+848413-8f06-yann.dupuy=zyapps.com@sgmail.github.com>)
	id 1bEKuj-002m3N-4W
	for yann.dupuy@zyapps.com; Sat, 18 Jun 2016 20:24:17 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:cc:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=Sq2qnBmHnUXbHs+xYMOXnJuXbhI=; b=dNVWersvAUmF2vcf
	Ros+emfKOK3csTLX3age8I2r/AuUip+qzOVNu9IRiN+5wjpR9CNB0dZkl8oC31Ia
	lhOuM/thKkV20MntVE0u8gWInWWO6ICMEuTI2UnDVCfR9sddluVnAAebyrhGO4Dy
	qhBRIyZv2iu8Z6rh0VB63HyJmQ8=
Received: by filter0919p1mdw1.sendgrid.net with SMTP id filter0919p1mdw1.15846.576591A23
        2016-06-18 18:23:30.034455315 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0003p1iad1.sendgrid.net (SG) with ESMTP id XXb7dQLOS0O8RMMvj1X9JA
	for <yann.dupuy@zyapps.com>; Sat, 18 Jun 2016 18:23:29.993 +0000 (UTC)
Date: Sat, 18 Jun 2016 11:23:29 -0700

**Comment by HolySamosa** [comment]
@hzalaz Did you ever make any progress with determining why fastlane/boarding is failing?  I was about to experiment with this myself. 

@samrobbins There are a bunch of folks looking for a solution to this for the boarding project.  If you might be able to assist, please check out this issue: https://github.com/fastlane/boarding/issues/65

Thanks!
