### ISSUE TITLE
[Fastlane] Cocoapods Repo Update

### ISSUE THREAD

**Issue by bassrock** [fastlane/fastlane#4064]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It looks like cocoapods has changed the default behavior of the install commands in the latest betas due to the Github Meta Issue. The repo-update parameter must now be included if you want to update the specs repo:

From Cocoapods Changelog
```
Running pod install doesn't imply an automatic spec repo update.
The old behavior can be achieved by passing in the option --repo-update or running pod repo update.
Marius Rackwitz #5004

Remove the configuration variable skip_repo_update as the default behavior varies now between pod install and pod (update|outdated).
Marius Rackwitz #5017
```

**Comment by TKBurner** [comment]
Thanks for reaching out @bassrock! I'm going to forward this along to more of the team so we can prioritize. :+1:

**Comment by ohwutup** [comment]
This was fixed in a PR that was merged yesterday. Cant find the link at the moment though sorry!

**Comment by TKBurner** [comment]
@bassrock Thanks again for always being on top of things! 💯
