### ISSUE TITLE
How does snapshot work?

### ISSUE THREAD

**Issue by onmyway133** [fastlane/fastlane#4065]
I am reading [Run Xcode 7 UI Tests from the command line](https://krausefx.com/blog/run-xcode-7-ui-tests-from-the-command-line)

> No extra work needed, you get screenshots for free. By appending the derivedDataPath option to your command, you tell Xcode where to store the test results including the generated screenshots.
> Xcode will automatically generate screenshots for each test action

What do you mean by "test action"?

Also the generated `SnapshotHelper.swift` `snapshot` function

```swift
class func snapshot(name: String, waitForLoadingIndicator: Bool = true) {
        if waitForLoadingIndicator {
            waitForLoadingIndicatorToDisappear()
        }

        print("snapshot: \(name)") // more information about this, check out https://github.com/fastlane/snapshot

        sleep(1) // Waiting for the animation to be finished (kind of)
        XCUIDevice.sharedDevice().orientation = .Unknown
    }
```

It seems to do nothing, how does the snapshots get generated and collected?

Thanks :smile:

**Comment by TKBurner** [comment]
Hi @onmyway133! We have a readme here, https://github.com/fastlane/fastlane/tree/master/snapshot. We use UI tests to navigate through your app, for each UI test case we take a screenshot. 

Thanks!

**Comment by onmyway133** [comment]
@TKBurner thanks for your reply

I already read that

> To take a snapshot, call the following between interactions
Swift: snapshot("01LoginScreen")
Objective C: [Snapshot snapshot:@"01LoginScreen" waitForLoadingIndicator:YES];

But you see, the `snapshot` function just `print`. And besides, the snapshots that UITests generates is in Logs/Tests/Attachments and it has name like `Screenshot_CD797F4D-AF31-47CB-8A2F-74D315099BB1`, how does `snapshot` knows which is right

**Comment by TKBurner** [comment]
Thanks for following up @onmyway133! You can define the output dir by adding the parameter. Run fastlane action snapshot to see the full list of parameters.

Thanks!
