### ISSUE TITLE
[fastlane] Update addressable dependency

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#4069]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

[Addressable](https://rubygems.org/gems/addressable/versions/2.4.0) latest version (2.4.0) can't be used because fastlane locks its version to `~> 2.3.8` (https://github.com/fastlane/fastlane/blob/master/fastlane/fastlane.gemspec#L31).

### Environment

fastlane version (fastlane -v): fastlane 1.80.0
Do you use bundler, rbenv or rvm? rvm and bundler

**Comment by TKBurner** [comment]
Thanks for letting us know. I'm going to have the team here look into this dependency issue. Thanks! :+1:
