### ISSUE TITLE
Automatically remove Preview.html

### ISSUE THREAD

**Issue by sprint84** [fastlane/fastlane#4074]
Hi,

this seems a pretty simple, but can you add an option to:
- delete the Preview.html after completion
and/or
- specify the Preview.html destination folder in the Deliverfile

Thanks

**Comment by TKBurner** [comment]
Hi @sprint84! Hope you are doing well. Interesting idea. I'll be sure the team here reads this over. Thanks! :+1:

**Comment by KrauseFx** [comment]
Or you can add the `Preview.html` to your `.gitignore`

**Comment by sprint84** [comment]
@KrauseFx of course that was the first thing I did. Regardless, the file is still sitting there in the project root folder.

**Comment by KrauseFx** [comment]
@sprint84 I'd recommend you create a `fastlane` directory and just put everything inside there. Also you should start using fastlane using `fastlane init` to get started quickly :+1:

**Comment by sprint84** [comment]
@KrauseFx Thanks, I do have a fastlane subdirectory, where all fastlane inputs and outputs are located. However, I didn't find an option on deliver to specify the output directory for the Preview.html, so it keeps been generated outside my fastlane directory.
Maybe I'm missing something in the documentation, or the documentation for deliver is missing this piece of information. Either way, I'd be happy to know how to do it.

**Comment by KrauseFx** [comment]
Mh, that's weird, it should be created in your `fastlane` directory. This will need some further investigating

**Comment by TKBurner** [comment]
Thanks for following up @sprint84. We are going to look into this over here. Hope you are having a nice week 👍

**Comment by evilDave** [comment]
Can I just tag on here: I'd also like the option to specify the filename of the preview file. I would like to generate the preview.html for different targets (and then push them up to our wiki for checking).
Additionally, I'd like to be able to call generate_summary from a lane, I can't seem to find a way to do that. (Sorry for tagging that on here, I'll open another issue if you would prefer.)
