### ISSUE TITLE
[supply] unable to gradually roll out a new build

### ISSUE THREAD

**Issue by hm1113** [fastlane/fastlane#4079]
### Issue Description
When I run supply --apk path/app.apk --track rollout --rollout 0.5, I get an error "undefined local variable or method `apk_version_code' " in supply/uploader.rb:136:in `update_track'.

##### Complete output when running fastlane, including the stack trace and command used

/Library/Ruby/Gems/2.0.0/gems/supply-0.6.1/lib/supply/uploader.rb:136:in `update_track': [!] undefined local variable or method `apk_version_code' for #<Supply::Uploader:0x007fb4c4d0d768> (NameError)
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.1/lib/supply/uploader.rb:100:in `upload_binaries'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.1/lib/supply/uploader.rb:26:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.1/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.1/lib/supply/commands_generator.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.1/lib/supply/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.1/bin/supply:6:in `<top (required)>'
	from /usr/bin/supply:23:in `load'
	from /usr/bin/supply:23:in `<main>'

fastlane version (fastlane -v): 1.80.0
Do you use bundler, rbenv or rvm? no

**Comment by asfalcone** [comment]
Just did a release of `supply` 0.6.2 with this fix! Thanks @hm1113 :+1:

**Comment by hm1113** [comment]
Thank you! @asfalcone
