### ISSUE TITLE
update_app_identifier is saving the Project.xcodeproj/project.pbxproj in XML format

### ISSUE THREAD

**Issue by gbejarano01** [fastlane/fastlane#4088]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After upgrading to Xcode 7.3, when running fastlane and trying to get the new build number by executing `increment_build_number` action we started getting the error below.

After some research we've found that after running `update_app_identifier` action the format of the `project.pbxproj` changed to XML while the one supported by agvtool it seems to be some sort for Json format now, so running `increment_build_number` or `get_version_number` won't no longer work as they are wrappers of agvtool.

This issue has appeared after migrating to Xcode 7.3, it seems before that was not an issue for agvtool or something.

So even if you try to run `agvtool next-version -all`or even `agvtool what-version -terse` manually, after a `update_app_identifier` action, they won't work as it's changing the format of the `project.pbxproj` file and `avgtool`is not able to read it and returns 6.

After further look at `update_app_identifier.rb` it seems that it's parsing the `project.pbxproj` as XML, therefore when it saves it back it's saving it as XML (not 100% sure here).

##### Complete output when running fastlane, including the stack trace and command used

```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.4****.2/lib/fastlane_core/ui/interface.rb:****27:in `crash!': [3****m[!] Exit status of command 'cd /Users/jenkins/.jenkins/jobs/orange_ios_alpha/workspace && agvtool next-version -all' was 6 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.


	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.4****.2/lib/fastlane_core/ui/ui.rb:****4:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/actions/increment_build_number.rb:36:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:****43:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:****29:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:****28:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:****28:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/fast_file.rb:****49:in `method_missing'
	from Fastfile:69:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:********0:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/fast_file.rb:****4****:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/fast_file.rb:****36:in `method_missing'
	from Fastfile:27:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:****78:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:****78:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:****53:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.4****.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:****5:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/bin/fastlane:****58:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-****.80.0/bin/fastlane:****64:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
.......
#Download all the certificates and provisioning profiles
    match(
      git_url: "git@xxxxxxx/certificates.git",
      type: "enterprise",
      app_identifier: "com.xxxxx.Project-" + options[:distribution]
    )

    #Increments the build number
    build_number = increment_build_number

    #Gets current version number
    version_number = get_version_number

    #Updates the BundleID to get the proper app
    update_app_identifier(
      xcodeproj: 'Project.xcodeproj',
      plist_path: "Project-iOS/Info.plist",
      app_identifier: "com.xxxxx.Project-" + options[:distribution],
    )

    #Signs the app with the given identity
    gym(
      codesigning_identity: "iPhone Distribution: XXXXX, LLC",
      use_legacy_build_api: true
    )

    #Delivers to HockeyApp
    hockey(
      api_token: ENV["HOCKEY_API_TOKEN"],
        public_identifier: options[:hockey_app_id],
      notify: "0"
    )

    #Resets the App Identifier
    update_app_identifier(
      xcodeproj: 'Project.xcodeproj',
      plist_path: "Project-iOS/Info.plist",
      app_identifier: "com.xxxxxx.Project",
    )
......
```

### Environment

fastlane version (fastlane -v): fastlane 1.80.0

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll look into this.

**Comment by gbejarano01** [comment]
Thanks @vpolouchkine, looking forward to it, as this is blocking our CI process.

**Comment by s0mmer** [comment]
@gbejarano01 I had a similar problem and after realising that `fastlane` depends on `xcodeproj` I noticed when installing `cocoapods 1.0.0.beta.x` (which I assume ships with a newer version of `xcodeproj`) it started working again.

**Comment by iamramin** [comment]
We're suffering from the same issue. `update_app_identifier` turns the `project.pbxproj` into XML and then `increment_build_number` stops working.

We've swapped the order of these two steps to work around the issue (so now we increment the version number before we update the app id) but would be nice to have this fixed as it really messes up the pbxproj file.

**Comment by gbejarano01** [comment]
@iamramin @s0mmer Only solution here, at least temporarily, we created different schemes and configurations and set a different bundle id for each one of those.

Instead of changing the bundle id through fastlane we have it there.

**Comment by TKBurner** [comment]
Thanks for following up. We are still looking into this over here and will update on this thread. 👍

**Comment by asfalcone** [comment]
As @s0mmer mentioned, this is related to the `xcodeproj` version. Please follow check out resolution [in this issue ](https://github.com/fastlane/fastlane/issues/3945#issuecomment-202529688). 

Thanks for the detailed report. I'm going to close this one as a duplicate.

**Comment by gbejarano01** [comment]
@asfalcone I don't use and I don't have a `Gemfile`, not sure if that's the solution for my problem.

The issue you're referring us to is about the ìncremene_build_number`while the issue I was referring to is on the `update_app_identifier` action.

Does that make any sense?

**Comment by asfalcone** [comment]
@gbejarano01 Yes sorry I wasn't more clear. I believe the underlying problem to be with the `xcodeproj` [gem](https://rubygems.org/gems/xcodeproj/). Both issues relate to that gem and using xcode 7.3 (and there is a detailed description of why we can't up the minimum version of xcodeproj required by fastlane in that issue).

Can you try updating to the beta version with `gem update xcodeproj --pre`.
Then try running `update_app_identifier` again. Please let me know if this helps!

**Comment by asfalcone** [comment]
@gbejarano01 Let me know if you get a chance to try out my suggestion from above! Thanks! 👍

**Comment by gbejarano01** [comment]
@asfalcone Unfortunately we didn't have time to try, since we've found a workaround this is second priority now.

If it happens that we try, I'll let you know.

Thanks for helping us!

**Comment by iamramin** [comment]
Updating the xcodeporj gem using `gem update xcodeproj --pre` does indeed fix this issue (the `update_app_identifier` no longer turns `project.pbxproj` into XML), but now we've got the versioning issue with cocoapods 😞

**Comment by TKBurner** [comment]
Hi @iamramin Thanks for letting us know. Can you file a different ticket for this Cocoapods issue if you haven't found a solution. Thanks
