### ISSUE TITLE
[Hockey] doesn't return the proper download link

### ISSUE THREAD

**Issue by rolandleth** [fastlane/fastlane#409]
Both `Actions.lane_context[Actions::SharedValues::HOCKEY_DOWNLOAD_LINK]` and `Actions.lane_context[Actions::SharedValues::HOCKEY_BUILD_INFORMATION]['public_url']` return a download link of a previously submitted build. All other info appears to be correct.

**Comment by rolandleth** [comment]
Update: on version `1.8.0` the print in the CLI 'Public download URL: xxx' is also the same, old, wrong one.

**Comment by JaviSoto** [comment]
Hi @rolandleth!
Is this still an issue?

**Comment by rolandleth** [comment]
Hey, I updated @KrauseFx after I talked to the guys at Hockey, but forgot to update the issue. The public url is always the same, but by design - it redirects you to the latest available build for the user you are logged in with :)

For a version based url, I just created it manually by adding `/version{version_id}` (I think that's the correct field) to the public one.
