### ISSUE TITLE
[idea] strategy selection mechanism or implementation guideline in fastlane_core

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#4095]
This is a spin off of https://github.com/fastlane/fastlane/pull/4048#issuecomment-205461192

Sometimes a feature requires multiple implementations. This is generally solved using the Strategy design pattern. Fastlane defines a default strategy and provides a mechanism for selecting others.

WRT to defining a default strategy and the selection mechanism, we sometimes go for boolean in APIs and an environment variable for on/off mechanisms. This is brittle. A mechanism based on naming strategies in both parameters and environment variables might be a better option.

This issue is about turning this idea into either a mechanism in fastlane_core or at least some general guidelines for implementation and coding reviews.

Reworked code example from the above issue:
````
FASTLANE_TRANSPORTER=shell_script or 
FASTLANE_TRANSPORTER=direct_invocation
````
and API
````
def initialize(user = nil, password = nil, transporter_executor: nil)
  transporter_executor ||= ENV['FASTLANE_TRANSPORTER'] || 'direct_invocation'

  UI.user_error!("Unknown transporter_executor strategy #{transporter_executor]")  unless ['direct_invocation', 'shell_script'].include?(transporter_executor) 
````

Note: I would probably use symbols instead of strings.

Proposed API:
````
ss = FastlaneCore::StrategySelector.new(env_key: 'FASTLANE_TRANSPORTER',
                                        valid_keys: [:direct_invocation, :shell_script],
                                        default_strategy: :direct_invocation)

def initialize(user = nil, password = nil, transporter_executor: nil)
    transporter_executor = ss.select(transporter_executor)
````

**Comment by TKBurner** [comment]
Thanks for this feature request @lacostej! I'm going to circulate this with the team so we can provide some feedback. Really to happy to have you as part of the Fastlane community :+1:

**Comment by KrauseFx** [comment]
That sounds great, I love the idea. We might want a cooler name for the class though. Sometimes related to lanes maybe? :car:

**Comment by lacostej** [comment]
Now that I think about it, it might be supported using ConfigItem under the hood. They already have some of the features required (validator, environment variable), and you might need to have more logic to instantiate the proper selector.

**Comment by mfurtak** [comment]
Besides the `ItunesTransporter` case, do we have other places the codebase that would benefit from this right now?

It would be great if there were three places where we wanted to use this (just my own rule of thumb for when an abstraction is worth creating) so that we can gather the right requirements for it to be broadly useful.

**Comment by lacostej** [comment]
@mfurtak if that had existed, I would have used it 
* here: https://github.com/fastlane/fastlane_core/pull/73/files#diff-1a17eb102986ec3ba794ae32a5e5241bR11 (which is something that might be reimplemented one day)
* here https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/package_command_generator.rb#L49 
* in your implementation of the transporter selector

Now those cases are either implemented or in stand-by.

Maybe it's too early to implement ? Hence the reason I also proposed to think about it in terms of coding guidelines instead.

**Comment by mfurtak** [comment]
Great, I think calling out the potential places where it might help is useful for discussion, and helps to focus on the requirements. It can also helpful to describe things that are outside of what we want to solve...

For example, these sorts of feature switches are good for changing behavior in a way that is explicitly not a part of the "public API" of the tool as exposed by the actions, commands, and their options. So, for things that should be exposed to developers as a first-class choice, a `ConfigItem` exposed through `available_options` is still the right way to go. Conversely, anything we want to control in the background, or give "hidden" control to the user for, should be kept out of the `available_options`.

Do folks agree with that as a design principle?

**Comment by lacostej** [comment]
For the sake of clarity, in https://github.com/fastlane/fastlane/issues/4095#issuecomment-207445906 I meant that the proposed StrategySlector API could be implemented using a `ConfigItem` **not exposed** through `available_options`. That's at least one alternative option.

**Comment by mfurtak** [comment]
Yup, I'm following what you're saying there. :+1:

Outside of discussion about ways to implement a solution, I'm still curious if the design principle I outlined above feels right to folks?
