### ISSUE TITLE
download_metaData triggers uploading of local metaData

### ISSUE THREAD

**Issue by BObereder** [fastlane/fastlane#4098]
+--------------------+---------------------------+
|             deliver 1.11.0 Summary             |
+--------------------+---------------------------+
| screenshots_path   | ./fastlane/screenshots    |
| metadata_path      | ./fastlane/metadata       |
| username           | fastlane.ios@stylight.com |
| app_identifier     | com.stylight.Stylight     |
| skip_binary_upload | false                     |
| skip_screenshots   | false                     |
| skip_metadata      | false                     |
| force              | false                     |
| submit_for_review  | false                     |
| automatic_release  | false                     |
+--------------------+---------------------------+

Loading xxx.txt
....
[11:23:43]: Verifying the upload via the HTML file can be disabled by either adding
[11:23:43]: `force true` to your Deliverfile or using `deliver --force`
Does the Preview on path './Preview.html' look okay for you? (y/n)

### Environment

fastlane version (fastlane -v): 1.80.0
rbenv

**Comment by TKBurner** [comment]
Hi @BObereder! Thanks for reaching out. Can you send over the full output from running 'deliver'? I want  to have a look and see what's going on. Also, can you send your Deliverfile and Fastfile if you are running a lane.


Thanks!

**Comment by fluidpixel** [comment]
I believe I might have had the same issue and seems to be linked to when you pass in the type into the match() call from fastlane with the latest version (1.80). I've now moved the type into the Matchfile and this doesn't happen.

**Comment by TKBurner** [comment]
@BObereder Can you check and see if @fluidpixel work around solves your issue? Thanks!

**Comment by BObereder** [comment]
@TKBurner I was using the command right in the console
@fluidpixel I am not using match at all

I updated fastlane today to the newest version and it seems it fixed that issue. everything is working again.
Thanks for your help.

**Comment by TKBurner** [comment]
@BObereder awesome! Glad to hear you are up and running. I'm going to close out this issue, but feel free to ping if you see this again 👍
