### ISSUE TITLE
iPad Pro offsets off with current Apple assets (and non-transparent corners)

### ISSUE THREAD

**Issue by loufranco** [fastlane/fastlane#4108]
### New Issue Checklist
- [x - frameit 2.5.1 ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I downloaded the iPadPro images today (4/7/2016). When I run frameit, the screenshots are misaligned (Horizontal / Silver) 

I updated my offsets.rb (for landscape) to 

```
when size::IOS_IPAD_PRO
          return {
            'offset' => '+120+61',
            'width' => 1075
          }
```

Which looks about right to me.

Also, I just noticed that the corners around the device aren't transparent -- they are white and cover my background jpg. (I just edited the PNG in device_frames to work-around)
##### Complete output when running fastlane, including the stack trace and command used

Command: `frameit silver`

```
[12:49:21]: Added frame: '/Users/lou/src/frameit-bug/iPadPro-10-home_framed.png'
```
### Configuration Files

Framefile.json:

``` javascript
{
  "default": {
  },

  "data": [
  ]
}
```
### Environment

fastlane version (fastlane -v): `frameit 2.5.1` / `fastlane 1.81.0`
Do you use bundler, rbenv or rvm? NO

**Comment by vpolouchkine** [comment]
Can you please format the issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by loufranco** [comment]
@vpolouchkine: Done

**Comment by TKBurner** [comment]
@loufranco Thanks for pointing this out. Can you send over some screenshots? I'm going to have the team take a look at this. Thanks for working with me 👍

**Comment by loufranco** [comment]
Screenshot:
![ipadpro-10-home](https://cloud.githubusercontent.com/assets/534999/14471976/13f017d8-00bf-11e6-9d59-d9d24e1fa6e6.png)

Framed:
![ipadpro-10-home_framed](https://cloud.githubusercontent.com/assets/534999/14471975/13efe222-00bf-11e6-907d-de7d47c9569f.png)

**Comment by TKBurner** [comment]
@loufranco Thanks for sharing! We are going to have a look over here and will update this thread. Hope that you have a great day! 👍

**Comment by FelixII** [comment]
There is also an issue with vertical iPad Pro screenshots:

![frameit_ipad_pro](https://cloud.githubusercontent.com/assets/5102728/14747919/5457a2fa-08b7-11e6-8f59-81b8e32cbe3a.png)

**Comment by i2amsam** [comment]
Possibly related to https://github.com/fastlane/fastlane/pull/3845

**Comment by L1bre** [comment]
Just to complement @loufranco's answer:
The offsets for portrait that worked in the offsets.rb for me are:

```
      when Orientation::PORTRAIT
        case screenshot.screen_size
        when size::IOS_55
          return {
            'offset' => '+42+146',
            'width' => 540
          }
        when size::IOS_47
          return {
            'offset' => "+44+155",
            'width' => 529
          }
        when size::IOS_40
          return {
            'offset' => "+48+177",
            'width' => 485
          }
        when size::IOS_35
          return {
            'offset' => "+60+260",
            'width' => 647
          }
        when size::IOS_IPAD
          return {
            'offset' => '+47+135',
            'width' => 737
          }
        when size::IOS_IPAD_PRO
          return {
            'offset' => '+71+132',
            'width' => 897
          }
        end

```
I used the iPhone SE screen for the iPhone 5s, just renamed the files.
Additionally I also had to delete the white corners but now it's looking as expected.

**Comment by TKBurner** [comment]
@L1bre Thanks for following up with that info. I circled back with the team to see if we can update this 👍

**Comment by i2amsam** [comment]
Thanks for this report. 👍 

Looks like there are two issues with the new iPad screenshots:
1. They have white backgrounds.  I added a fix to the iPhone SE's backgrounds in https://github.com/fastlane/fastlane/pull/4411 but the same solution didn't work for these iPad ones, so that needs to be improved to work in more cases. 
2. They have different offsets than before, this is the same issue as https://github.com/fastlane/fastlane/pull/3845 and we probably need a way to handle different "versions" of the same frame with different offsets.  I'm not actively working on that but would be happy to discuss or review if someone wants to take a crack at it.

**Comment by TKBurner** [comment]
Going to mark this help wanted to see if we can get some help from the community in the form of a PR. Thanks! 👍

**Comment by walsht** [comment]
I am having this same issue, where on my Mac can I change the offsets.rb file?

Thank you,
Tim

**Comment by FelixII** [comment]
@walsht If you are using RubyGems, the file should be located at /Library/Ruby/Gems/2.0.0/gems/frameit-<version>/lib/frameit

**Comment by aral** [comment]
I’m not sure if the Apple template has changed or whether it is a version difference, but on the latest farmeit 2.6.2, with latest iPad pro template from Apple (SHA1=9a4db30fde49938c9fda39f9a714bb02996acaaa), the following portrait offsets work for me in ~/.rvm/gems/ruby-2.2.3/gems/frameit-2.6.2/lib/frameit/offsets.rb:

```
 when size::IOS_IPAD_PRO
          return {
            'offset' => '+88+150',
            'width' => 897
          }
        end
```

**Comment by walsht** [comment]
@FelixII Thank you.

I am trying to use Landscape for the iPad Pro and offsets are not correct.  Does anyone know the correct offsets?

Thank you,
Tim

**Comment by guywithabeard** [comment]
**The asset provided by Apple is the 9.7" model, not the 12" model:**

![screen shot 2016-05-17 at 12 21 19](https://cloud.githubusercontent.com/assets/4975808/15319212/08b3fa34-1c2a-11e6-863f-c3feb4e8eacb.png)

Current Apple assets provided for the iPad Pro are the **9.7"** model, which has a screen resolution of 2048*1536 vs. the iPad Pro 12" model which has a screen resolution of 2732*2048.

Since `frameit` tries to cram a 2732*2048 into a 2048*1536 container, alignment goes out of whack.

So, seeing as Apple doesn't provide a 12" frame for now, we seem to be stuck using 2048*1536 screenshots...

**Comment by TKBurner** [comment]
@guywithabeard Really happy to see people investigating this in the community. Is anyone interested in submitting a PR? Thanks!

**Comment by aral** [comment]
Just a quick note that I just updated to the latest Fastlane and the issue is still there. Going to reimplement my patches (see above) again.

**Comment by TKBurner** [comment]
@aral Awesome! We'll work with you over there 👍

**Comment by Danbana** [comment]
@nickpodratz 's offsets were correct in my case:

```
when size::IOS_IPAD_PRO
          return {
            'offset' => '+71+132',
            'width' => 897
          }
```

**Comment by Danbana** [comment]
of course I also had to use Photoshop to remove the white corners from the generated PNG

**Comment by Techprimate** [comment]
@Danbana don't remove the white corners from the PNG but disable the layer 'White Background' in the downloaded PSD file. When using frameit, it will create PNG files without the white corners

**Comment by TKBurner** [comment]
@Techprimate Thanks for the workaround, have you tried the PR to see if it helps?

Thanks!

**Comment by Techprimate** [comment]
I did not try the PR but I tried the following offset values with success:

```
when Orientation::PORTRAIT
        ...
        when size::IOS_IPAD_PRO
          return {
            'offset' => '+88+150',
            'width' => 897
          }
        end
when Orientation::LANDSCAPE
       ...
        when size::IOS_IPAD_PRO
          return {
            'offset' => '+120+61',
            'width' => 1076
          }
        end
end
```

**Comment by digitalprecision** [comment]
Can confirm that @Danbana offsets worked. Thanks!
