### ISSUE TITLE
Action 'testfairy' doesn't support required operating system 'android'

### ISSUE THREAD

**Issue by hyphenbash** [fastlane/fastlane#4111]
Hi,

I know that at the moment there's no android support for Testfairy action, or at least that's what I understood. I was wondering if there's any plan on supporting android for this?

Thanks

**Comment by vpolouchkine** [comment]
We'll see what we can do in a future release. If you (or anyone else) want to tackle this, check out the [contributing](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) doc.

**Comment by hyphenbash** [comment]
Thanks @vpolouchkine

**Comment by Monomachus** [comment]
:+1:

**Comment by hyphenbash** [comment]
I haven't been able to test it out nor to contribute on it as I have been busy with other projects, but from the documentation I still cannot see action testfairy for Android.

**Comment by TKBurner** [comment]
@hyphenbash No problem! We'll keep this open 👍
