### ISSUE TITLE
Different position of padded frame due to title's character height

### ISSUE THREAD

**Issue by winkelsdorf** [fastlane/fastlane#4114]
**Example Situation**
Having two titles for two screenshots (same device, same resolution). One title contains characters with descenders extending the baseline (g, p, j, q, y). The other title does not.

Example titles to reproduce the issue:
"Product" <- no descenders below baseline at all
"Catalog" <- descender to the baseline due to "g"

See https://en.wikipedia.org/wiki/X-height for details about that part of typography.

Used Font is: Open Sans

**Expected**
Use the padding as "offset" and always start at the same position to create a homogeneous layout ready for the Apple App Store ;)

**Actual**
The position is shifted. Seeing the screenshots in the store would be unbalanced, as they are presented in a scrollview side-by-side.

**framefile.json**
```
{
    "default": {
        "keyword": {
            "font": "./fonts/Open_Sans/OpenSans-Bold.ttf",
            "color": "#df0a25"
        },
        "title": {
            "font": "./fonts/Open_Sans/OpenSans-Light.ttf",
            "color": "#515151"
        },
        "background": "./background.jpg",
        "padding": 70
    },

    "data": []
}
```

**title.strings**
```
"Products" = "Product catalog";
"Selector" = "Product selector"; 
```

**Environment**
frameit 2.5.1

**Screenshots**
<img width="239" alt="pixel winch image 1" src="https://cloud.githubusercontent.com/assets/1413291/14372803/76976b3a-fd44-11e5-8a8d-890fde439064.png">
<img width="206" alt="pixel winch image 2" src="https://cloud.githubusercontent.com/assets/1413291/14372804/76c08b3c-fd44-11e5-8c23-efe24df4e47e.png">

**Source of the Problem**
~~In ```editor.rb``` line 246 ImageMagick's (better MiniMagick's) .gravity property is used to position the text. From: http://www.imagemagick.org/Usage/annotating/#gravity_text~~
> ~~There is one very important difference between positioning images and text. If you draw a text string, without defining any form of "-gravity", the string will be drawn relative to the 'baseline' of the font.~~

~~In turn, using gravity will fight with the baseline as seen in the screenshots and leading to unbalanced text heights returned.~~

The logic of trimming of the title in ```editor.rb``` line 251 is the source of the problem. Probably take the notes regarding .gravity from above into account.

Looking forward to discuss this.

**Comment by TKBurner** [comment]
@winkelsdorf Thanks for reporting this. The team over here is going to have a look. We'll update this thread. Thanks! :+1:

**Comment by winkelsdorf** [comment]
@TKBurner You're welcome! I hope this doesn't sound like being too pedantic about..

Please let me know, if I may be of any help.

**Comment by i2amsam** [comment]
@winkelsdorf Thanks for the detailed report, super useful 💯 !  I can verify that the text sizing is different with descenders than without, I expect the difference is in this [trim](https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/editor.rb#L251) call.  I don't see a obvious quick-fix right now but I'll keep this in mind for the next `frameit` update.  In the meantime I'm adding the help wanted tag in case someone else wants to take a stab at a more robust solution.

**Comment by winkelsdorf** [comment]
@i2amsam Thank you very much, you're welcome! I agree with your expectation regarding ```trim```. 

Regarding the logic, it should not fall below a minimum line-height based on a test string containing e.g. ```Ag```. Total height is ```number of lines * minimum line height```. If actual trim result is below that, use the minimum total height. 

But that needs more work as we obviously don't handle line breaks on our own..

As @i2amsam said: If anyone is able to take up on this, feel free to comment.

**Comment by TKBurner** [comment]
Hi @JonathanBouaziz Thanks for following up on this. We are still waiting on someone from the community to submit a PR. Thanks!
