### ISSUE TITLE
Slather: teamcity option

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#4125]
Slather has added --teamcity option:
https://github.com/SlatherOrg/slather/commit/697f5ac5246119c4055517ece38b9e9efadc66f4

Would be nice to have in fastlane slather wrapper.

**Comment by vpolouchkine** [comment]
We'll see what we can do in a future release. If you (or anyone else) want to tackle this, check out the [contributing](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) doc.
