### ISSUE TITLE
fastlane1.70.0 doesn't support XCode7.3 and ios9.3.1

### ISSUE THREAD

**Issue by qingjie** [fastlane/fastlane#4132]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
snapshot can not do screenshots with XCode7.3 and IOS9.3.1

##### Complete output when running fastlane, including the stack trace and command used

```
It only show black screent, and it doesn't have any response.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Ruby2.3
```

### Environment

fastlane version (fastlane -v):1.70.0
Do you use bundler, rbenv or rvm? rvm

**Comment by TKBurner** [comment]
Hi @qingjie, thanks for reaching out. Can you send over the full output when you run 'snapshot' on your project dir? Can you also send over your Snapfile?

Thanks!

**Comment by qzhao-retrieve** [comment]
Sorry, I have downgrade my xcode7.3 to 7.2.1
I do not have that right now.

**Comment by qzhao-retrieve** [comment]
I have Xcode7.2.1 and 7.3 right now.
it works great, I am going to close this issue.

**Comment by rolandkakonyi** [comment]
For me the switching back to iOS 9.2 simulator solved the problem

**Comment by TKBurner** [comment]
@qzhao-retrieve and @rolandkakonyi Thanks for your reports! Glad to hear you are both up and running. Going to go ahead and close this issue out 👊
