### ISSUE TITLE
Typo in Provisioning Profile UUID keys (from sigh)

### ISSUE THREAD

**Issue by cbowns** [fastlane/fastlane#4134]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`fastlane` contains a typo for environment variables and references to provisioning profile UUIDs.

Several places in the docs, this appears ([for example, in the old codesigning guide](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/CodeSigning.md#deprecated-using-environment-variables)):

> To fill the profile in using environment variables use

```
PROVISIONING_PROFILE = "$(PROFILE_UUID)";
```

> This allows the Xcode project to use Automatic provisioning profiles and enables fastlane to set a custom profile.

> In your Fastfile, add the following between your sigh and gym call:

```
sigh

# use the UDID of the newly created provisioning profile
ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

gym(scheme: "Release")
```

My `fastfile`, as seen below, instead references:

```
ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
```

A quick search of the `fastlane` repo still turns up several instances of "`UDID`":

```
fastlane/docs/Advanced.md
177:lane_context[SharedValues::SIGH_UDID]                 # The UDID of the generated provisioning profile

fastlane/docs/CodeSigning.md
43:ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]

fastlane/lib/fastlane/actions/sigh.rb
6:      SIGH_UDID = :SIGH_UDID
25:          Actions.lane_context[SharedValues::SIGH_UDID] = ENV["SIGH_UDID"] if ENV["SIGH_UDID"] # The UDID of the new profile
29:          return ENV["SIGH_UDID"] # return the UDID of the new profile

fastlane/lib/fastlane/actions/update_project_code_signing.rb
43:                                       default_value: ENV["SIGH_UDID"])

fastlane/spec/actions_specs/sigh_spec.rb
12:        ENV["SIGH_UDID"] = "udid"

sigh/lib/sigh/local_manage.rb
18:      profile_filename = ENV["SIGH_UDID"] + ".mobileprovision"

sigh/lib/sigh/manager.rb
39:      ENV["SIGH_UDID"] = udid if udid
```

Should this be UUID?

##### Complete output when running fastlane, including the stack trace and command used

N/A

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

```ruby
lane :build_app do |options|
  # Fetch the latest ad-hoc profile:
  # For more information: https://codesigning.guide
  match(type: options.fetch(:match_profile_type, "adhoc"))
  # use the UDID of the newly created provisioning profile
  ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

  # build the app.
  gym(
    use_legacy_build_api: true,
  )
end

```

### Environment

fastlane version (fastlane -v): `fastlane 1.81.0`

Do you use bundler, rbenv or rvm?

I use `chruby`.

**Comment by TKBurner** [comment]
@cbowns Thanks for pointing this out. The team here is going to look over the references. UUID usually refers to a given build and UDID is a device identifier. Thanks!

**Comment by KrauseFx** [comment]
Thanks for letting us know. I know I made this mistake back in the days, and it's all across the code base. Things like the SIGH_UDID are actually aliases already as far as I know. I'm unsure about how important it is to change this, since it has to stay backwards compatible, to not break any existing setups. I don't think it's worth spending the time on changing this.

**Comment by cbowns** [comment]
I'll track doc updates in a new issue (stemming off of #1999). thanks!
