### ISSUE TITLE
Can I find the name of the certificate managed by match using command line?

### ISSUE THREAD

**Issue by zhengbuqian** [fastlane/fastlane#4140]
Hi awesome authors, fastlane is a wonderful tool!

#### Short version of my question:

Can `match` tell me the name of the certificate it manages? Name such as "iPhone Distribution: My Name".

#### Long version of my question:

When I am using this tool I ran into a problem so I hope that I can get some help from you, thank you!
What I want is to use command line to archive `.ipa` out of source codes without opening Xcode or Keychain Access or any other GUI programs. 

Here is where I've achieved: 

I've used `match appstore` on another Mac (say it's Mac A) to generate certificate and provisioning profile and pushing them to my private git repo. 

In the new Mac(Mac B)'s Keychain Access there are only Apple's root certificates. After cloning a new project onto Mac B, I `cd`, `match init` and connect this project to my private git repo. Then I `match appstore` so `match` can download and install my certificate (only one) and provisioning profile on Mac B. 

Here I try using `gym` to archive `.ipa` but it failed saying `No coding signing identities found`. I think the reason is that I didn't use Xcode to open this project and select a team(so it could be none), in the Build Settings the Code signing property is also default(could be iOS Developer). So I add a parameter: `gym -i "iPhone Distribution: My Name"` and this time it succeeded. 

So here is my question: on Mac B almost all steps are proceeded in command line so I can write some scripts or something to finished all the work. But now in the last step I have to check this name `"iPhone Distribution: My Name"` in Keychain Access, remembered and typed it into the command line. Is there a way to let `match` to tell me this name so I can turn the whole process to an automatic process?

PS: I can use `security find-identity -p codesigning -s Keyword -v` to find some certificates whose name is matched with the keywords. But there could be many Apple IDs so I can't specify a keyword. And I need the name of the very certificate managed by `match` to make sure `gym` won't failed. So this is not my solution.

Hope that you can help me, thank you~

**Comment by TKBurner** [comment]
Hi @zhengbuqian Thanks for reaching out. Can you send over your fastfile for this lane? You should be able to add the parameters there. Thanks! 👍
