### ISSUE TITLE
Support for building to simulator/device 

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [fastlane/fastlane#4144]
It would be really nice to have a tool, where QA testers could build to a device / simulator without having to open Xcode or Android studio. What I was thinking if someone managed to create a wrapper for the PhoneGap tool /Gradle tool this would speed up the time to build and test code.   

https://github.com/phonegap/ios-deploy
https://github.com/phonegap/ios-sim

This is the current command am using to build and depoly on android.
````
gradle clean -q; gradle uninstallAll -q; gradle installProductionDebug -q && adb shell am start -n "com.example.test/com.example.test.splash.SplashActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
````

**Comment by TKBurner** [comment]
@Ashraf-Ali-aa Great idea! I'll be sure to bring this up with the team. We will follow up after that.

Thanks!

**Comment by ohwutup** [comment]
hey @Ashraf-Ali-aa! this would be really awesome. We are currently working on a plugin system to enable actions like this to be developed without needing to merge into the main fastlane repo. If the is something that you would be interested in building we would love to see this as a plugin! I am going to close the issue for now, but please let us know if this is something you would want to make happen! 🐙 😄
