### ISSUE TITLE
Question: How to declare some variables in APPFILE

### ISSUE THREAD

**Issue by RahulKatariya** [fastlane/fastlane#4145]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I was trying to declare all the constants in the APPFILE by using environments.

```ruby
ENV['PROJECT_DIRECTORY'] = "TapHeal"
ENV['APP_VERSION'] = "1.0.0"
ENV['XCODE_VERSION'] = "7.3"

```
The force variable is giving me error no implicit conversion of true into String
```ruby
ENV['FORCE'] = true 
```

Is there another way. I am not really familiar with how Ruby works.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
project_directory = ENV['PROJECT_DIRECTORY']
app_version = ENV['APP_VERSION']
app_name = ENV['APP_NAME']
app_sku = ENV['APP_SKU']
xcode_version = ENV['XCODE_VERSION']
build_number = Time.now.strftime('%Y%m%d')
p12_password = ENV['P12_PASSWORD']
```

### Environment

fastlane version (fastlane -v): 1.80.0
Do you use bundler, rbenv or ram? no

**Comment by fluidpixel** [comment]
Have you tried ENV['FORCE'] = "true" ?

**Comment by RahulKatariya** [comment]
Strings are working but what will happen in the fastfile - force = ENV['FORCE'] and i use it in pem(force: force).

**Comment by TKBurner** [comment]
@RahulKatariya Thanks for following up. Were you able to use @fluidpixel's workaround?

Thanks!

**Comment by RahulKatariya** [comment]
I think my question is misunderstood. My Fastfile is on git https://github.com/RahulKatariya/fastlane. So in local projects i import Fastfile from git. In AppFile i declare all the constants for my workflow. Somehow i am not able to set a Boolean value in the ENV in AppFile.

**Comment by TKBurner** [comment]
@RahulKatariya Thanks for following up. I'm going to look into this a little more. We'll update this thread. Thanks! 👍
