### ISSUE TITLE
[gym] Archiving fails via SSH

### ISSUE THREAD

**Issue by girishnair12345** [fastlane/fastlane#4147]
When I create and archive using terminal running the following command

`gym --silent -s <TARGET_NAME> -p <XCODEPROJ_PATH> -q Debug --clean`

The build runs fine and creates an archive, but when i try to run it via an SSH the archive always fails

`ssh <USER_NAME>@<IP_ADDRESS> gym --silent -s <TARGET_NAME> -p <XCODEPROJ_PATH> -q Debug --clean`

Is there a way i can run this successfully or am I doing it in a wrong way 

Also note that archiving fails when code signing comes, is there any way i can tie it with sigh ?

**Comment by TKBurner** [comment]
Hi @girishnair12345 Thanks for reaching out. Can you send over the full output when you run gym via ssh? Thanks!

**Comment by girishnair12345** [comment]
Hi,

Here is the drop box link, I have created a small Hello World project and attached both the logs
https://www.dropbox.com/s/342mz5li5pi4na5/Executed%20Files.zip?dl=0

My most probable guess is that terminal is not able to access the key chain, hence its not able to access the certificates. 
But if that is the case then can i use sigh with gym to automatically create or download provisioning profile associated with that bundle ID ?
So that it downloads it and signs it without trying to access the keychain 
(This is just my guess not sure on this)

**Comment by TKBurner** [comment]
@girishnair12345 Thanks for following up. What happens if you run cert and sigh before you run gym here? It seems like you having issues with your codesigning identity on your remote computer.

**Comment by girishnair12345** [comment]
I can't save type the password as it shows
`stty: stdin isn't a terminal`
and I have already mentioned I don't think its the availability of certificates or provisioning profile but the access limitation that is being placed to access private stuff it seems. Can you put an extra argument as` --auto` so that it should automatically download the required certificates or provisioning profiles without trying to access the keychain

**Comment by TKBurner** [comment]
Hi @girishnair12345. Can you make sure that your SSH user has access to the keychain on your remote computer? Thanks!

**Comment by girishnair12345** [comment]
It has all the access
Its the admin, even while using sigh for the first time it showed a pop up box for Allowing access to keychain and even that is kept at *Always Allow*. It doesn't ask anything with respect to keychain even if i run in terminal directly or via remote

**Comment by TKBurner** [comment]
@girishnair12345 Thanks for following up. It sounds like your config is correct. We are going to take a look into this over here and update you! Thanks 👍

**Comment by zhangzhibin** [comment]
@TKBurner I got same issue here. Same command run successfully from local but not from remote via ssh.

Here is the log for your reference:

> ▸ Running script 'Run Script'
▸ Touching cubeninja.app
▸ Signing /Users/admin/Library/Developer/Xcode/DerivedData/Unity-iPhone-gnjhgtocmxshergzkwhekxxigccw/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/cubeninja.app
** ARCHIVE FAILED **


>The following build commands failed:
CodeSign /Users/admin/Library/Developer/Xcode/DerivedData/Unity-iPhone-gnjhgtocmxshergzkwhekxxigccw/Build/Intermediates/ArchiveIntermediates/Unity-iPhone/InstallationBuildProductsLocation/Applications/cubeninja.app
(1 failure)
[09:58:53]: Exit status: 65

Looking forward to a fix.

Let me know if you need more information to investigate.

Thank.

**Comment by zhangzhibin** [comment]
@TKBurner @girishnair12345 I found a workaround after searching. 
unlock keychain with below command just before gym:

> security -v unlock-keychain -p "<password>" "/Users/<username>/Library/Keychains/login.keychain"

**Comment by TKBurner** [comment]
@zhangzhibin Awesome! Glad to hear you are up and running. Is anyone still affected by this issue?

Thanks! 👍
