### ISSUE TITLE
Fastlane spaceship is inefficient when fetching app statuses

### ISSUE THREAD

**Issue by programmin1** [fastlane/fastlane#4148]
When using spaceship as described here: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/iTunesConnect.md

I can list apps just fine:
all_apps = Spaceship::Tunes::Application.all
all_apps.find_all{|app| app.name == "Name of app"}

However, if I try to filter which apps have an edit_version:
 all_apps.find_all{|app| app.edit_version }

It takes a looong time, and I have to cancel, ctrl+c, giving this stack trace:
^CIRB::Abort: abort then interrupt!
	from /usr/lib/ruby/2.0.0/net/protocol.rb:155:in `call'
	from /usr/lib/ruby/2.0.0/net/protocol.rb:155:in `select'
	from /usr/lib/ruby/2.0.0/net/protocol.rb:155:in `rescue in rbuf_fill'
	from /usr/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
	from /usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
	from /usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
	from /usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
	from /usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /usr/lib/ruby/2.0.0/net/http.rb:1126:in `get'
... 7 levels...
	from /var/lib/gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /var/lib/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /var/lib/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /var/lib/gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /var/lib/gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/client.rb:404:in `block in send_request'
	from /var/lib/gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/client.rb:322:in `with_retry'
	from /var/lib/gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/client.rb:403:in `send_request'
	from /var/lib/gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/client.rb:379:in `request'
	from /var/lib/gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/tunes/tunes_client.rb:279:in `app_version'
	from /var/lib/gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/tunes/app_version.rb:168:in `find'
	from /var/lib/gems/2.0.0/gems/spaceship-0.25.1/lib/spaceship/tunes/application.rb:102:in `edit_version'
	from (irb):35:in `block in irb_binding'
	from (irb):35:in `each'
	from (irb):35:in `find_all'
	from (irb):35

It does not need to make multiple requests to see which have edit_version of a particular status. Look at https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/manageyourapps/summary/v2 and write the file to v2.json, then run:

python -m json.tool ./v2.json
to pretty-print the data they give for the app listing. As you can see, it should be able to get the  "stateGroup": "readyForSale",
from that request, along with a bunch of other information. Ideally it should go through those and not have to take a long time making different requests.

**Comment by TKBurner** [comment]
Thanks for pointing this out @programmin1! We are going to have a look and treat this as a feature request. We will update this ticket once we have more info 👍

**Comment by RocketPop** [comment]
I'd like to add that if you're reviewing that area of the code - it would be very helpful to expose the app states:
 waiting for review, in review, rejected, available for sale, removed from sale... whatever the canonical list is
