### ISSUE TITLE
Snapshot: Device not in list of available simulators

### ISSUE THREAD

**Issue by love4soul** [fastlane/fastlane#4153]
Hi,

I have an error `Device 'iPhone 5s' not in list of available simulators ''`. I have reset simulators several times and it didn't help, simulators list is always empty.

**Comment by TKBurner** [comment]
Hi @love4soul! Were you able to get up and running? Definitely want to help you out if you are still running into any issues. Thanks!

**Comment by love4soul** [comment]
Hi @TKBurner! 
It's working now. I have restarted my Mac and error message disappeared.

**Comment by TKBurner** [comment]
@love4soul So glad to hear you are up and running 👍 Have a great day!
