### ISSUE TITLE
match entitlement error

### ISSUE THREAD

**Issue by TienNM** [fastlane/fastlane#4154]
Step to produce the error :
1. Audio app support IAA.
2. Use match development.
3. Math does not enable IAA automatically on App ID. I have an error about the entitlement everytime i run my app.

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v):
Do you use bundler, rbenv or rvm?

**Comment by TKBurner** [comment]
@TienNM Great to hear from you! Can you send over the output of when you run match? Thanks for working with me! 👍
