### ISSUE TITLE
meta-issue with the new issue checklist: add "chruby" to ruby env managers, clarify ruby Q&A

### ISSUE THREAD

**Issue by cbowns** [fastlane/fastlane#4164]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The issue template for `fastlane` asks:
"Do you use bundler, rbenv or rvm?"

This should be split into two questions:
- "Do you use bundler? y/n"
- "Do you use chruby, rbenv, or rvm to manage your ruby versions?"

**Comment by mfurtak** [comment]
Agreed. What do you think about the following language:

* Do you use `bundler` to execute `fastlane` (i.e. `bundle exec fastlane`)?
* Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by cbowns** [comment]
👍  seems good!
