### ISSUE TITLE
Unable to slather with Xcode 7.3 using cocoapods

### ISSUE THREAD

**Issue by jschneier** [fastlane/fastlane#4165]
Hi.

I use a workspace and Xcode 7.3 on one of my apps and use fastlane to run slather for code coverage. The most recent version of Xcode broke this workspace support so Slather grew a `--workspace` option as of 2.1.0 (released recently). I have opened a pull request to support this option at #4109.

Let me know if I have missed anything.

**Comment by TKBurner** [comment]
@jschneier Thanks for reaching out and for following the steps for a pull request. We'll have a look as a team and provide some feedback. Hope that you have a great week 👍

**Comment by asfalcone** [comment]
I just merged #4109! This will be in the next release of fastlane.
