### ISSUE TITLE
Fastlane doesn't fetch version number

### ISSUE THREAD

**Issue by linkrjr** [fastlane/fastlane#4166]
### Issue Description

I have been trying to get my app version with the get_version_number action but it keeps returning a blank string

##### Complete output when running fastlane, including the stack trace and command used

```
[15:00:19]: --------------------------------
[15:00:19]: --- Step: get_version_number ---
[15:00:19]: --------------------------------
[15:00:19]: $ cd /Users/rongomes/Documents/projects/frontfoot/wizard_of_odds_iphone && agvtool what-marketing-version -terse
[15:00:20]: ▸ $(($buildNumber + 1))n/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${PROJECT_DIR}/${INFOPLIST_FILE}"
[15:00:20]: ▸ "wizard-of-odds.xcodeproj/../wizard-of-odds/wizard-of-odds-Info.plist"=2.0.14
[15:00:20]: Version: 
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby

# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Download/Create certificates and profiles"
  lane :provisioning do

    cert(development: true, output_path: "provisioning")
    cert(output_path: "provisioning")

    sigh(development: true, output_path: "provisioning")
    sigh(adhoc: true, output_path: "provisioning")
    sigh(output_path: "provisioning")

  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # ensure_git_status_clean

    increment_build_number
    increment_version_number

    puts "Version: #{get_version_number}"
    puts "Build: #{get_build_number}"

  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "wizard-of-odds") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```

### Environment

fastlane version (fastlane -v): 1.81.0
Do you use bundler, rbenv or rvm?
Yes, I am using bundler and rbenv

### Some investigation

After some debugging I found that the issue is in the get_version_number.rb line 41

```ruby

line = results.first unless results.first.nil?

```

The results array contains the following entries

```
["$(($buildNumber + 1))n/usr/libexec/PlistBuddy -c \"Set :CFBundleVersion $buildNumber\" \"${PROJECT_DIR}/${INFOPLIST_FILE}\"", "\"wizard-of-odds.xcodeproj/../wizard-of-odds/wizard-of-odds-Info.plist\"=2.0.15"]
```

We are interested in the last entry but the code on line 41 grabs the first item in that array.

Is anyone having the same issue?

**Comment by tabuchid** [comment]
I think I'm hitting this also. Working on verifying but I get the version to create a tag and that started failing today.

**Comment by TKBurner** [comment]
Thanks for reaching out @linkrjr  and @tabuchid. We are going to look into this over here. Can you provide the full output @tabuchid? @linkrjr Do you get an error after that line you shared of output?

**Comment by tabuchid** [comment]
I get a crash report number of `34267786b3db6c9ad61252f82634b1e0`
```
/Users/doug/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Exit status of command 'git tag -am 'v$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${plist}" | awk 'BEGIN { FS = "." } ; { print $1"."$2"."$3 }')nMARKETING_BUILDNUMBER="$MARKETING_BUILDNUMBER.$(git rev-parse --abbrev-ref HEAD).$(git rev-parse --short HEAD).$(date -u +%Y%m%d%H%M%S)"n/usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $MARKETING_BUILDNUMBER" "${plist}"necho "Setting version string to $MARKETING_BUILDNUMBER"nelsenecho $CONFIGURATION " Not setting build number or version string."nfi(1460491905)-submit-RETRACTED_BUNDLE_ID (fastlane)' 'v$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${plist}" | awk 'BEGIN { FS = "." } ; { print $1"."$2"."$3 }')nMARKETING_BUILDNUMBER="$MARKETING_BUILDNUMBER.$(git rev-parse --abbrev-ref HEAD).$(git rev-parse --short HEAD).$(date -u +%Y%m%d%H%M%S)"n/usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $MARKETING_BUILDNUMBER" "${plist}"necho "Setting version string to $MARKETING_BUILDNUMBER"nelsenecho $CONFIGURATION " Not setting build number or version string."nfi(1460491905)-RETRACTED_BUNDLE_ID'' was 2 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
sh: -c: line 1: syntax error: unexpected end of file
```

**Comment by tabuchid** [comment]
Verified that my issue doesn't occur in version 1.80 but does in 1.81
Potentially related to https://github.com/fastlane/fastlane/commit/d95adbc306f0fd214795f4827e372c8e36143793 which changes `get_version_number` to take in a scheme.

**Comment by asfalcone** [comment]
@tabuchid The stacktrace associated with that crash report blames `add_git_tag`. Can you include your Fastfile for reference? Also, try running the full generated command that you pasted, in your terminal and see if that helps reveal the error!

**Comment by tabuchid** [comment]
@asfalcone `add_git_tag` crashes because I'm passing forward the bad value I'm getting out of `get_version_number` 
Was able to get at 80 vs 81 comparison hitting the action from the command line

v81 output
```
$ bundle exec fastlane run get_version_number app/App.xcodeproj
[17:32:05]: --------------------------------
[17:32:05]: --- Step: get_version_number ---
[17:32:05]: --------------------------------
[17:32:05]: $ cd /Users/doug/app && agvtool what-marketing-version -terse
[17:32:06]: ▸ $(date +%s)n    /usr/libexec/Plistbuddy -c "Set CFBundleVersion $buildnum" "${plist}"n    echo "Setting build number to $buildnum"nn    MARKETING_BUILDNUMBER=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${plist}" | awk 'BEGIN { FS = "." } ; { print $1"."$2"."$3 }')n    MARKETING_BUILDNUMBER="$MARKETING_BUILDNUMBER.$(git rev-parse --abbrev-ref HEAD).$(git rev-parse --short HEAD).$(date -u +%Y%m%d%H%M%S)"n    /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $MARKETING_BUILDNUMBER" "${plist}"n    echo "Setting version string to $MARKETING_BUILDNUMBER"nelsen    echo $CONFIGURATION " Not setting build number or version string."nfi
[17:32:06]: ▸ "App.xcodeproj/../supporting_files/app_info.plist"=2.6.2
[17:32:06]: ▸ "App.xcodeproj/../supporting_files/app_internal_info.plist"=2.6.2
[17:32:06]: ▸ "App.xcodeproj/../tests/info.plist"=2.6.2
[17:32:06]: Result: $(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${plist}" | awk 'BEGIN { FS = "." } ; { print $1"."$2"."$3 }')n    MARKETING_BUILDNUMBER="$MARKETING_BUILDNUMBER.$(git rev-parse --abbrev-ref HEAD).$(git rev-parse --short HEAD).$(date -u +%Y%m%d%H%M%S)"n    /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $MARKETING_BUILDNUMBER" "${plist}"n    echo "Setting version string to $MARKETING_BUILDNUMBER"nelsen    echo $CONFIGURATION " Not setting build number or version string."nfi
```


v80 output
```
$ bundle exec fastlane run get_version_number xcodeproj:app/App.xcodeproj
[17:32:55]: --------------------------------
[17:32:55]: --- Step: get_version_number ---
[17:32:55]: --------------------------------
[17:32:55]: $ cd /Users/doug/app && agvtool what-marketing-version -terse1
[17:32:56]: ▸ $(date +%s)n    /usr/libexec/Plistbuddy -c "Set CFBundleVersion $buildnum" "${plist}"n    echo "Setting build number to $buildnum"nn    MARKETING_BUILDNUMBER=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${plist}" | awk 'BEGIN { FS = "." } ; { print $1"."$2"."$3 }')n    MARKETING_BUILDNUMBER="$MARKETING_BUILDNUMBER.$(git rev-parse --abbrev-ref HEAD).$(git rev-parse --short HEAD).$(date -u +%Y%m%d%H%M%S)"n    /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $MARKETING_BUILDNUMBER" "${plist}"n    echo "Setting version string to $MARKETING_BUILDNUMBER"nelsen    echo $CONFIGURATION " Not setting build number or version string."nfi
[17:32:56]: ▸ 2.6.2
[17:32:56]: Result: 2.6.2
```

**Comment by tabuchid** [comment]
One more example
v81 passing scheme as well
```
bundle exec fastlane run get_version_number xcodeproj:app/App.xcodeproj scheme:app_production
[17:41:19]: --------------------------------
[17:41:19]: --- Step: get_version_number ---
[17:41:19]: --------------------------------
[17:41:19]: $ cd /Users/doug/app && agvtool what-marketing-version -terse
[17:41:20]: ▸ $(date +%s)n    /usr/libexec/Plistbuddy -c "Set CFBundleVersion $buildnum" "${plist}"n    echo "Setting build number to $buildnum"nn    MARKETING_BUILDNUMBER=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" "${plist}" | awk 'BEGIN { FS = "." } ; { print $1"."$2"."$3 }')n    MARKETING_BUILDNUMBER="$MARKETING_BUILDNUMBER.$(git rev-parse --abbrev-ref HEAD).$(git rev-parse --short HEAD).$(date -u +%Y%m%d%H%M%S)"n    /usr/libexec/Plistbuddy -c "Set CFBundleShortVersionString $MARKETING_BUILDNUMBER" "${plist}"n    echo "Setting version string to $MARKETING_BUILDNUMBER"nelsen    echo $CONFIGURATION " Not setting build number or version string."nfi
[17:41:20]: ▸ "App.xcodeproj/../supporting_files/app_info.plist"=2.6.2
[17:41:20]: ▸ "App.xcodeproj/../supporting_files/app_internal_info.plist"=2.6.2
[17:41:20]: ▸ "App.xcodeproj/../tests/info.plist"=2.6.2
[17:41:20]: Result:
```

**Comment by asfalcone** [comment]
Thanks @tabuchid for the deets! :+1:

**Comment by linkrjr** [comment]
@TKBurner,

I don't get an error per se, I just don't get any value out of that method.

**Comment by pauldowman** [comment]
+1

**Comment by KrauseFx** [comment]
I took a closer look at this with @asfalcone, and we need some more information from you: 

Please share the **complete** output with the variable dump and the stack trace, so we can take a closer look at that! 
In particular, I'd like you to also share the output when running the command with `-terse` and once with `-terse1`

**Comment by tabuchid** [comment]
Any update on this? @KrauseFx Is there more information I can share too?
Sent what I get from running the action directly.

**Comment by TKBurner** [comment]
@tabuchid Thanks for following up. Can you share the output that Felix asked for above? Thanks!

**Comment by tabuchid** [comment]
@TKBurner @KrauseFx 
```
 ios ツ bundle exec fastlane run get_version_number xcodeproj:percolate/percolate.xcodeproj scheme:percolate_production
[17:13:37]: --------------------------------
[17:13:37]: --- Step: get_version_number ---
[17:13:37]: --------------------------------
[17:13:37]: $ cd /Users/doug/Development/Percolate/mobile/ios/percolate && agvtool what-marketing-version -terse
[17:13:38]: ▸ "percolate.xcodeproj/../percolate/supporting_files/percolate_internal-Info.plist"=1.0
[17:13:38]: ▸ "percolate.xcodeproj/../percolate/supporting_files/percolate_production-Info.plist"=1.0
[17:13:38]: ▸ "percolate.xcodeproj/../percolate_tests/Info.plist"=1.0
[17:13:38]: Result:
(save ±) ios ツ bundle exec fastlane --verbose run get_version_number xcodeproj:percolate/percolate.xcodeproj scheme:percolate_production
DEBUG [2016-04-22 17:13:42.59]: Using xcodeproj: percolate/percolate.xcodeproj
DEBUG [2016-04-22 17:13:42.59]: Using scheme: percolate_production
INFO [2016-04-22 17:13:42.59]: --------------------------------
INFO [2016-04-22 17:13:42.59]: --- Step: get_version_number ---
INFO [2016-04-22 17:13:42.59]: --------------------------------
INFO [2016-04-22 17:13:42.59]: $ cd /Users/doug/Development/Percolate/mobile/ios/percolate && agvtool what-marketing-version -terse
INFO [2016-04-22 17:13:43.38]: ▸ "percolate.xcodeproj/../percolate/supporting_files/percolate_internal-Info.plist"=1.0
INFO [2016-04-22 17:13:43.39]: ▸ "percolate.xcodeproj/../percolate/supporting_files/percolate_production-Info.plist"=1.0
INFO [2016-04-22 17:13:43.40]: ▸ "percolate.xcodeproj/../percolate_tests/Info.plist"=1.0
INFO [2016-04-22 17:13:43.40]: Result:
(save ±) ios ツ cd /Users/doug/Development/Percolate/mobile/ios/percolate && agvtool what-marketing-version -terse1
1.0
(save ±) percolate ツ cd /Users/doug/Development/Percolate/mobile/ios/percolate && agvtool what-marketing-version -terse
"percolate.xcodeproj/../percolate/supporting_files/percolate_internal-Info.plist"=1.0
"percolate.xcodeproj/../percolate/supporting_files/percolate_production-Info.plist"=1.0
"percolate.xcodeproj/../percolate_tests/Info.plist"=1.0
```

**Comment by markcarroll** [comment]
I've been looking into this too. It seems that if you replace `-terse` with `-terse1` it works as expected.

**Comment by TKBurner** [comment]
@tabuchid Thanks for following up with that. We are going to look into this a little more 👍

**Comment by yeradis** [comment]
I´m experiencing the same problem, `get_version_number` does not return anything

At the CLI i can see : agvtool what-marketing-version -terse
with multiple lines as output, different .plist with its versions

On the other hand : agvtool what-marketing-version -terse1
return just one .plist and the version

Extra info: The current project i´m working on has two schemes.

**Comment by TKBurner** [comment]
@yeradis Thanks for additional info. 👍 Does it work on other projects?

**Comment by Nailer** [comment]
Having this same issue since the unit test target has a version number as well.

It seems to me, even though the [initial feature request here](https://github.com/fastlane/fastlane/issues/501) correctly used -terse1, the final implementation does not. 
Is this something that was lost in copy-pastery?

**Comment by tabuchid** [comment]
It seems to me like `-terse1` only works if the version is the same for all of your targets. For me thats usually the case but I'm sure others have more complex workspaces.
Setup a test comparing the output of agvtool with different flags. I think the most robust solution would involve figuring out which plist to use by inspecting the scheme and then using parsing the correct version from the `-terse` variation.

```
ツ agvtool what-marketing-version
No marketing version number (CFBundleShortVersionString) found for Jambase targets.

Looking for marketing version in native targets...
Looking for marketing version (CFBundleShortVersionString) in native targets...

Found CFBundleShortVersionString of "1.0.1" in "percolate.xcodeproj/../percolate/supporting_files/percolate_internal-Info.plist"
Found CFBundleShortVersionString of "1.0" in "percolate.xcodeproj/../percolate/supporting_files/percolate_production-Info.plist"
Found CFBundleShortVersionString of "1.0" in "percolate.xcodeproj/../percolate_tests/Info.plist"

ツ agvtool what-marketing-version -terse
"percolate.xcodeproj/../percolate/supporting_files/percolate_internal-Info.plist"=1.0.1
"percolate.xcodeproj/../percolate/supporting_files/percolate_production-Info.plist"=1.0
"percolate.xcodeproj/../percolate_tests/Info.plist"=1.0

ツ agvtool what-marketing-version -terse1
1.0.1
```

**Comment by asfalcone** [comment]
This code recently [changed](https://github.com/fastlane/fastlane/commit/d95adbc306f0fd214795f4827e372c8e36143793). I'd love to get @rs17b's take on this issue to see if we can figure out a way to support all cases!

**Comment by alexeychirkov** [comment]
I have the same problem

Default scheme:
```
➜  myproject git:(master) ✗ fastlane run get_version_number scheme:myproject --verbose 
DEBUG [2016-04-29 10:09:30.19]: Using scheme: myproject
INFO [2016-04-29 10:09:30.19]: --------------------------------
INFO [2016-04-29 10:09:30.19]: --- Step: get_version_number ---
INFO [2016-04-29 10:09:30.19]: --------------------------------
INFO [2016-04-29 10:09:30.19]: $ cd /Users/me/projects/myproject && agvtool what-marketing-version -terse
INFO [2016-04-29 10:09:30.50]: ▸ "myproject.xcodeproj/../myproject/Info.plist"=0.7.0
INFO [2016-04-29 10:09:30.51]: ▸ "myproject.xcodeproj/../myprojectTests/Info.plist"=0.7.0
INFO [2016-04-29 10:09:30.51]: Result: 0.7.0
```

Beta scheme
```
➜  myproject git:(master) ✗ fastlane run get_version_number scheme:myproject-beta --verbose
DEBUG [2016-04-29 10:08:08.74]: Using scheme: myproject-beta
INFO [2016-04-29 10:08:08.74]: --------------------------------
INFO [2016-04-29 10:08:08.74]: --- Step: get_version_number ---
INFO [2016-04-29 10:08:08.74]: --------------------------------
INFO [2016-04-29 10:08:08.74]: $ cd /Users/me/projects/myproject && agvtool what-marketing-version -terse
INFO [2016-04-29 10:08:09.06]: ▸ "myproject.xcodeproj/../myproject/Info.plist"=0.7.0
INFO [2016-04-29 10:08:09.07]: ▸ "myproject.xcodeproj/../myprojectTests/Info.plist"=0.7.0
INFO [2016-04-29 10:08:09.07]: Result: 
```

**Comment by rs17b** [comment]
After reading through this issue, I think the first problem is using the term ```scheme``` as opposed to ```target``` @alexeychirkov and @tabuchid problems should be solved by passing in a ```target``` name instead of a ```scheme``` name. Schemes can obviously be different from targets and that escaped me when authoring this breaking change. 

So I propose changing ```scheme``` to ```target```. It seems to me the parsing code can stay the same as we are just checking for the existence of a substring. 

For what it's worth, we could also revert to the original behavior of this action and use ```terse1``` flag when no ```scheme``` or ```target``` is specified and continuing to use ```terse``` when one is specified. That should fix the other weirdness happening here -- which I haven't looked at in depth yet at this point. 

Thanks for alerting me to this @asfalcone!

**Comment by asfalcone** [comment]
Thank you @rs17b for taking a look. 👍 

We'd love for someone to submit a PR to fix this (including tests for cases that have been missed) and for a few others to help out with the review and testing to make sure we're handling all of the use cases! Let me know who is up for it! 😎

**Comment by rs17b** [comment]
@asfalcone  I can create the PR.

@tabuchid can you explain the architecture of your project a bit?

Are ```percolate_internal``` and ```percolate_production``` different targets in your project? Is ```percolate``` a project name or target name or something else?

```
"percolate.xcodeproj/../percolate/supporting_files/percolate_internal-Info.plist"=1.0.1
"percolate.xcodeproj/../percolate/supporting_files/percolate_production-Info.plist"=1.0
"percolate.xcodeproj/../percolate_tests/Info.plist"=1.0
```

Thanks!

**Comment by tabuchid** [comment]
@rs17b We actually have multiple projects in a workspace. A bunch of internal libraries, and the main app project. The main app project has three targets. Prod, internal, and tests. Generally we keep their versions in sync using the `increment_version_number` action but I changed the internal one in the above example to showcase the difference of `--terse` and `--terse1`

**Comment by rs17b** [comment]
@tabuchid So when you want to get a version number, you would want to request based on a target, correct? As in, when you're building, you would want the ```percolate_production``` target's version number to be returned, correct?

In the example, ```terse1``` would return the ```percolate_internal``` version number. I'd image this probably isn't ideal for you, as I assume you want ```percolate_production.```

And just to be clear, the target names are ```percolate_internal```, ```percolate_production```, and ```percolate_tests```, correct?

**Comment by tabuchid** [comment]
@rs17b Yes those are the target names. I'm not sure what all you can get from target vs the scheme. In my case the scheme and the target names are the same. 
The plist is specified in the target per build configuration so that is the source of truth for that info but if its more convenient for people to specify the scheme, then it looks like you can get the build configuration and the target from the scheme and then go from there.

**Comment by ashanawebb** [comment]
Thank you,

**Comment by ashanawebb** [comment]
native targets...
Looking for marketing version (CFBundleShortVersionString) in native targets...

Found CFBundleShortVersionString of "1.0.1" in "percolate.xcodeproj/../percolate/supporting_files/percolate_internal-Info.plist"
Found CFBundleShortVersionString of "1.0" in "percolate.xcodeproj/../percolate/supporting_files/percolate_production-Info.plist"
Found CFBundleShortVersionString of "1.0" in "percolate.xcodeproj/../percolate_tests/Info.plist"

ツ agvtool what-marketing-version -terse
"percolate.xcodeproj/../percolate/support-there.

**Comment by ashanawebb** [comment]
Schemes can obviously be different from targets and that escaped me when authoring this breaking change.

So I propose changing scheme to target. It seems to me the parsing code can stay the same as we are just checking for the existence of a substring.

For what it's worth, we could also revert to the--...?

**Comment by TKBurner** [comment]
@rs17b Thanks for stepping in on this! We'll work with you on your pull request 👍

**Comment by rs17b** [comment]
1.87.0 has PR #4463 included so everyone should update and hopefully all your problems are taken care of.

Specifying no ```scheme``` or ```target``` should now work as it did before the initial change occurred. And if you're using the ```scheme``` option, please use the ```target``` option instead.

**Comment by asfalcone** [comment]
Thanks @rs17b for the fix and updating this issue. 

I'm going to close it out now but feel free to let us know if this doesn't solve the original problem 👍
