### ISSUE TITLE
Can we remove app using Spaceship from iTunes

### ISSUE THREAD

**Issue by NikhilRyan** [fastlane/fastlane#4167]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I was trying to remove the app from iTunes using Spaceship and I found that we can't edit app status i.e. "attr_reader :app_status" . 
Is this possible to remove the app from sale using Spaceship ?

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (fastlane -v):
Do you use bundler, rbenv or rvm?

**Comment by TKBurner** [comment]
@NikhilRyan Thanks for reaching out. Right now it's not possible, but the team here will review this as a feature request and provide feedback. Thanks!
