### ISSUE TITLE
Put show_update_message behind a flag to reduce noise

### ISSUE THREAD

**Issue by alper** [fastlane/fastlane#4168]
The fastlane update message displayed by this function is causing way too much noise: https://github.com/fastlane/fastlane/blob/fa5fc3ef7ef22c9e6b760f0e15b7f2498beb151e/fastlane_core/lib/fastlane_core/update_checker/update_checker.rb#L50

Please allow for an option to mute these messages completely. We know that there is a new version.

**Comment by vpolouchkine** [comment]
Thanks for your feedback, we'll take a look.

**Comment by KrauseFx** [comment]
You can use the `FASTLANE_SKIP_UPDATE_CHECK` environment variable for this 👍
