### ISSUE TITLE
slather: --ignore option is multivalued

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#4169]
slather has --ignore option and it is multivalued:
https://github.com/SlatherOrg/slather/blob/885bb4a8a39b6007ce1128726b183fbd9263f4f8/lib/slather/command/coverage_command.rb

Can we have the same for fastlane action?

**Comment by TKBurner** [comment]
Thanks for reaching out @yakimant. The team here will have a look at this idea and decide on next steps. Hope that you have a wonderful day 👍

**Comment by brockboland** [comment]
@yakimant if you pass an array, this works as expected. I'm using it like this:

```ruby
coverage_files_to_ignore = [
    'R.generated.swift',
    'ClientName/Utilities/*.swift',
    'Pods/*',
]

slather(
    cobertura_xml: true,
    proj: project_file,
    input_format: 'profdata',
    scheme: scheme,
    ignore: coverage_files_to_ignore,
)
```

**Comment by yakimant** [comment]
Thanks, @brockboland! It's working!

**Comment by TKBurner** [comment]
Thanks @brockboland for posting this solution 👍 Glad to hear you are up and running @yakimant. I'm closing this issue out.

**Comment by niranjani23** [comment]
I gave the following in my slather.yml file but I still see references to those ignored files in my cobertura.xml:

# .slather.yml

coverage_files_to_ignore = [
    'Pods/*',

]

slather(
    cobertura_xml: true,
    xcodeproj: /ios/abcd.xcodeproj,
    scheme: scheme,
    source_directory: /ios/project,
    output_directory: /reports,
    ignore: coverage_files_to_ignore,
)

Any thoughts as to why this is happening?

**Comment by brockboland** [comment]
@niranjani23 the sample code I posted was for use in `Fastfile`, not `.slather.yml`. If you look closely at the fastlane output, there's probably an error about having an invalid or unreadable `.slather.yml`, since that isn't valid YAML. If you'd like to include the configuration for ignored files there, take a look at the sample `.slather.yml` in the Slather readme: https://github.com/SlatherOrg/slather#usage-with-codecov

**Comment by niranjani23** [comment]
@brockboland Thanks for the follow up. I did try with the slather readme and my slather.yaml file is as follows:

# .slather.yml


coverage_service: cobertura_xml
xcodeproj: /ios/abcd.xcodeproj
scheme: scheme
source_directory: /ios/project
output_directory: /reports
ignore:
- AsyncDisplayKit/*
- Pods/*

The **command** I use for slathering is:
slather coverage -x --output-directory /reports --workspace project.xcworkspace --scheme "scheme" /ios/project.xcodeproj 

But still see references to the Pods/ files in my cobertura.xml. The cobertura.xml file report doesn't seem to ignore the files mentioned in the slather.yaml. Am I still missing something?

**Comment by brockboland** [comment]
Since you're running `slather` directly, this is not a fastlane issue. I'd recommend you open a support issue on the slather repo.

That said: you could try changing `Pods/*` to `ios/Pods/*`. Since your project file is inside an `ios` directory, I'm guessing that's where your Pods directory is too.

**Comment by niranjani23** [comment]
Sure, thanks @brockboland. But changing to ios/Pods/* also doesn't help. I posted in the slather repo as well.
