### ISSUE TITLE
Added support for carthage `--derived-data`

### ISSUE THREAD

**Issue by bartoszj** [fastlane/fastlane#4173]
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,
Since `carthage 0.16` there is a new option, `--derived-data`. I've added support for this option to the `carthage` and `setup_jenkins` actions.

There is already support for derived data folder in the `gym`, `scan`, `xcodebuild` so I think is would be nice to have it in the `carthage`.

Related PR: #4163

### Configuration Files

Fastfile:
```ruby
carthage(
  derived_data: "path/to/derivedData"
)
```

**Comment by TKBurner** [comment]
@bartoszj Great to hear from you! We are going to review this as a feature request and then update this thread. Hope you have a great day!

**Comment by KrauseFx** [comment]
Thanks again @bartoszj 👍
