### ISSUE TITLE
`scan` support for multiple device / destination

### ISSUE THREAD

**Issue by bartoszj** [fastlane/fastlane#4174]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,

Currently `scan` tool is able to execute tests only on one device / simulator. It would be nice to provide list of `device`s and/or list of `destination`s. `xcodebuild` already provides such functionality by providing multiple `-destination` options in the command line:
```
xcodebuild -workspace MyApp.xcworkspace -scheme "MyScheme" -destination "platform=iOS Simulator,name=iPhone 6s,OS=9.3" -destination "platform=iOS Simulator,name=iPhone 5s,OS=9.3" test
```

I want to implement this so that the `device` (and `destination`) option from `scan` would handle both a string with device description, or list (array) of strings. So there should be no problem with backward compatibility.

### Configuration Files

Fastfile:

```ruby
scan(
  device: [
    "iPhone 6s (9.3)",
    "iPhone 5s (9.3)"
  ]
)
```

I don't have yet working version, but it should be ready this week.

**Comment by TKBurner** [comment]
@bartoszj Thanks for sharing this. I'll let the team know what you are thinking about and we'll discuss here before giving you the go ahead to create a PR. Thanks!

**Comment by dholdaway** [comment]
any update on this ? 

would be a really handy feature.

**Comment by TKBurner** [comment]
@bartoszj If you are interested in a PR, we'd be happy to take a look. 👍

**Comment by bartoszj** [comment]
Hi,
Yes, I'll prepare pull requests, but it will take me some time. I hope to finish it next week, so please be patient.

**Comment by TKBurner** [comment]
@bartoszj No problem! I'll leave this open for the time being 👍

**Comment by KrauseFx** [comment]
Awesome, thanks @bartoszj 🚀

**Comment by lukewar** [comment]
I started working on this feature myself. Here is work-in-progress [banch](https://github.com/lukewar/fastlane/commit/f3d5d653dd93846e9c3269542abbea10372cdfdf).
There may be some code style issue, while I am not fluent in Ruby.
This implementation is not backward compatible.

While I have initial version setup I discovered one downside of using multiple `-destination` parameters. If run on multiple simulator, test are multiplied by number of simulators and aggregated in one test report file.
I think that reports should be separate for each device. What do you think?

**Comment by TKBurner** [comment]
@lukewar Thanks for reaching out. Can you and @bartoszj see if you can combine efforts? It looks like @bartoszj was already going to take a look at this and I want to make sure we don't end up with two conflicting PRs. 

Really glad to have both of you interested in working on this as it'll help out a bunch of our developers!

Thanks! 👍

**Comment by lukewar** [comment]
Sure, I think that @bartoszj already incorporated my changes in his [pull request](https://github.com/fastlane/fastlane/pull/4683).
But I think we didn't find a solution for reporting issue. On the other hand I start to think that it may be desired behaviour that report as combined output for all devices.

**Comment by TKBurner** [comment]
@lukewar Thanks for following up. Glad to hear that you managed to coordinate. I think one output makes sense. Hope you have a great day!

**Comment by bartoszj** [comment]
I'll link this issue to the new PR: #4758

**Comment by Goles** [comment]
@lukewar @bartoszj Do you guys have any link to actual docs on how this ended up working?

It seems that I passed `device: [ .... ]` instead of `devices:` to `scan` and that failed.

**Comment by bartoszj** [comment]
Hi,

In the `Scanfile` you can use:
```
devices [
  "iPhone 6s (9.2)",
  "iPhone 6s (9.3)"
]
```

In the `Fastfile`:
```
scan(
  devices: [
    "iPhone 6s (9.2)",
    "iPhone 6s (9.3)"
  ]
)
```

You can also find usage in the *Scan* `README.md` file: https://github.com/fastlane/fastlane/tree/master/scan#usage

I hope it will be helpful ;)

**Comment by TKBurner** [comment]
@bartoszj Thanks!
