### ISSUE TITLE
Unhelpful error when setting ENV to true.

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#4176]
When setting an ENV to `true` I get this ruby error in the sentry log:

```json
"type": "TypeError",
        "value": "no implicit conversion of true into String
```

Fastlane spits out a huge stack trace instead of giving a nicer error for this, in this case it would be nice if it was shown like this:

```
[!]  TypeError: no implicit conversion of true into String (Fastfile:Line 12)
```

**Comment by KrauseFx** [comment]
Please share your configuration file (e.g. `Fastfile`) and command you used to execute this. I don't know where there error comes from.

**Comment by jcampbell05** [comment]
@KrauseFx  I'll open a new more helpful issue!

**Comment by KrauseFx** [comment]
Thanks :+1:
