### ISSUE TITLE
deliver init affected by spaceship change: file name contain prefix and md5

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#4177]
deliver init is affected by 6accb69b638a4423c69a77040f00182b51ccb050.

The change causes downloaded screenshots to contain the prefix and hash added by spaceship. E.g. of downloaded file name

1_ipadPro_1.ftl_68d4c4b643e9d15a00b716efXXXXXXXX_original_file_name

The problem is here:

https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/deliver/lib/deliver/download_screenshots.rb#L18-L19

This will be solved while completing #3755

**Comment by TKBurner** [comment]
@lacostej Always great to hear from you! We'll review this thread before going forward with your pull request. Let us know if you have any other details you want us to think about before approving the discussion of the pull request. 👍 

Thanks!
