### ISSUE TITLE
Upload zip files to S3?

### ISSUE THREAD

**Issue by justin** [fastlane/fastlane#4178]
As part of our deployment process, we upload and archive the xcarchive generated by Xcode as a zip file to S3. I don't believe this is possible currently with the S3 action. It'd be great if there was a file path option of some sort that we could use to provide what we want to upload and where in the bucket it should go.

**Comment by TKBurner** [comment]
@justin Thanks for reaching out. We'll review this as a feature request and update this thread as relevant. Hope that you have a great day! 👍

**Comment by KrauseFx** [comment]
@justin Thanks for submitting this issue. You're right, currently the `s3` action is limited to `ipa` files with their `plist` files, which will not change in the future. I'd recommend taking a look at the `aws-sdk` provided by Amazon and building your own script to fit your needs. 
You should be up and running in no time. I'd recommend building this as its own action using `fastlane new_action`, so it's better reusable and properly structured. Once that's done, you can submit to fastlane via a PR if you want to share it with the rest of the community 👍 

Let me know if we can help you with this
