### ISSUE TITLE
Using gym with the profile and certificate created with match in a lane

### ISSUE THREAD

**Issue by akaralar** [fastlane/fastlane#4179]
I have these two lines in my Fastfile as part of a lane:

    match(type: "appstore", app_identifier: identifier)
    gym(scheme: "VindePass", configuration: "Release", clean: true, include_symbols: true, output_directory: "./build") 

For this to work properly I have to select the correct profiles and certificates in the Xcode project settings. Another option is to pass the provisioning profile and certificate to `gym` via parameters, but in this case I have to hardcode them. Is there a way to get the name of the certificate and path of profile that is created from `match` and use them while building in `gym`?

**Comment by KrauseFx** [comment]
Sure, check out the docs here https://github.com/fastlane/fastlane/tree/master/match#setup-xcode-project

**Comment by TKBurner** [comment]
@akaralar Let us know if you have any other questions. Closing out this issue for now. 👍
