### ISSUE TITLE
Feature request: match nuke adhoc

### ISSUE THREAD

**Issue by niklassaers** [fastlane/fastlane#4186]
At the moment, "match nuke" can choose between development and distribution. Match handles adhoc distribution fine separately from app store distribution, so it'd be really nice if it could also handle this in "match nuke", for instance as "match nuke adhoc"

**Comment by KrauseFx** [comment]
This is by design, since the distribution certificate is shared between Ad Hoc and App Store

**Comment by richsage** [comment]
Bit late to this issue, but it would probably be useful to mention this in the output. I've just looked at a failing Fastlane deploy which has "adhoc" listed as the type when I use `match` as part of the deploy process... but then `match nuke adhoc` just tells me I can only use development or distribution. Would you accept a PR for a tweak to the output? :)

**Comment by TKBurner** [comment]
Hi @richsage! Yes, if you want to clarify this in the output we'll be happy to review a PR. Thanks!
