### ISSUE TITLE
Run android instrumented tests[new feature]

### ISSUE THREAD

**Issue by joshrlesch** [fastlane/fastlane#4190]
In our CI work flow for our Android app, we have a couple different types of automated tests. Unit tests, instrumented unit tests and integration tests. The instrumented unit tests and integration tests rely on an actually emulator to be running in order for them to run as they run against the app and not just in the jvm.

I already created a custom action that we use that creates a new avd, boots it, runs tests, shuts down the avd and then deletes it so that you get a clean testing environments on every run. This also helps keep the build agents clean with not leaving expensive android emulators running.

I feel this could be a good feature to include into fastlane so others could do something similar if they wanted. What do you all think?

**Comment by TKBurner** [comment]
@joshrlesch Great to hear from you! Are you proposing that you could implement this? It's an interesting idea. I'd love to get some community feedback before we consider it here. I'm going to mark this as help wanted so some of our frequent contributors can cruise in and have a look. Thanks! 👍

**Comment by joshrlesch** [comment]
I am. I have the PR ready, just wanted to reach out to the peeps before opening it.
