### ISSUE TITLE
Best Practice for exporting Frameworks

### ISSUE THREAD

**Issue by mindrunner** [fastlane/fastlane#4192]
I have a fastlane Project containing only an iOS Framework. No executable app. I want to export this framework for distributing the binary without the source code. What is the best practice here? I am calling 

> sigh

 with 

> development: true

 and 

> gym

 with 

> export_method: development

Gym seems to always create an ipa-file, but I think this is not what I want. I think I just need some kind of zip-archive. Is fastlane/gym supporting this?

**Comment by TKBurner** [comment]
Hi @mindrunner! Great to hear from you. Right now gym is not built to export this type of file. Let me know if you have any other questions. Closing this out for housekeeping purposes. Thanks!

**Comment by mindrunner** [comment]
Cool, thanks for the answer. Our workaround now is to call 

> carthage archive

instead of 

> gym


Cheers
