### ISSUE TITLE
git_last_tag returns tag from any branch!

### ISSUE THREAD

**Issue by pavm035** [fastlane/fastlane#4193]
Hi,

When I was checking change log from the current branch it was giving wrong logs, later found that change log computed based on last tag irrespective branch you are on, say I have branch A and B, on A there is tag 1,2 on B tag is 3,4. Next switch to branch A and ask for git_last_tag which should return 2 but it returns 4 which is wrong.

**Comment by asfalcone** [comment]
Dupe of #4194
