### ISSUE TITLE
git_last_tag returns from any branch!

### ISSUE THREAD

**Issue by pavm035** [fastlane/fastlane#4194]
Hi,

When I was checking change log from the current branch it was giving wrong logs, later found that change log computed based on last tag irrespective branch you are on, say I have branch A and B, on A there is tag 1,2 on B tag is 3,4. Next switch to branch A and ask for git_last_tag which should return 2 but it returns 4 which is wrong.

**Comment by TKBurner** [comment]
Hi @pavm035! Great to hear from you. Can you send over the exact repro steps with the commands you are entering. Also, send over the output of the results so I can have a look. Thanks!

**Comment by pavm035** [comment]
Hi @TKBurner  Thank you so much for your quick response, Sorry for not updating reproducible steps before, Please find below of execution phase

SampleXcodeBot kumar.pavan$ fastlane beta
[20:33:05]: -------------------------------------------------
[20:33:05]: --- Step: Verifying required fastlane version ---
[20:33:05]: -------------------------------------------------
[20:33:05]: fastlane version valid
[20:33:05]: ------------------------------
[20:33:05]: --- Step: default_platform ---
[20:33:05]: ------------------------------
[20:33:05]: Driving the lane 'ios beta' 🚀
[20:33:05]: ----------------------------------------
[20:33:05]: --- Step: changelog_from_git_commits ---
[20:33:05]: ----------------------------------------
[20:33:05]: Collecting Git commits between M2 and HEAD
[20:33:05]: release_notes: -develop -> commit 1

[20:33:05]: --------------------------
[20:33:05]: --- Step: last_git_tag ---
[20:33:05]: --------------------------
[20:33:05]: last_git_tag: M2

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | changelog_from_git_commits          | 0           |
| 4    | last_git_tag                        | 0           |
+------+-------------------------------------+-------------+

[20:33:05]: fastlane.tools finished successfully 🎉


Here is the link of source tree screenshot, From the above executions steps it prints tag M2 but that tag is on develop branch, What it supposed to print here is M1 which is on master branch

[Link:](http://screenshot.net/xvedmtm.jpg)

**Comment by TKBurner** [comment]
@pavm035 Thanks for following up. We are going to take a look at this as a team and will follow up on this thread with our findings. Thanks! 👍

**Comment by mfurtak** [comment]
Hi @pavm035 - thanks for the report!

This action and its behavior has seen a number of changes due to people's different expectations about how it should work. That may be because the description, **"Get the most recent git tag"** is pretty broad. Because of that history, we would prefer not to make another change to its behavior right now.

If the current behavior is not working out for your needs, please see if substituting
```ruby
tag_name = `git describe --tags --abbrev=0`
```
gives you what you want! 🎯 

Once you have that tag name, did you know that `changelog_from_git_commits` allows you to specify the commit range you'd like to use? Try using this option

``` ruby
between: [tag_name, 'HEAD']
```
when calling `changelog_from_git_commits` 📖

**Comment by pavm035** [comment]
@mfurtak @TKBurner  Looks like promising workaround will give a try. 👍
