### ISSUE TITLE
Configure Scan with Slack username / icon

### ISSUE THREAD

**Issue by martinohman** [fastlane/fastlane#4195]
Feature request for more configuration options relating to Slack output from Scan.

I am currently trying to setup an environment where I want to make it so that:
- Messages use the current app's icon as the slack icon
- Messages use a username prefixed by the current app's name / other unique string

This isn't possible currently since both the username and icon are hardcoded for Scan (unless I'm missing something obvious, I am well rusty with Ruby and a new Fastlane user).

I made a quick solution for this here: https://github.com/martinohman/fastlane/commit/e07da9de91706858cdad8c44a3bdb70a0eca9aac

**Comment by TKBurner** [comment]
@martinohman Thanks for reaching out. We are going to review this as a feature request and update on this thread. Hope that you have a great day! 👍

**Comment by martinohman** [comment]
I think it would make sense to make the username completely optional since you configure name/icon when you setup a webhook integration in Slack's interface. If you decide you want to have some form of dynamic naming, you could have the option to set a name and override the Slack integration setting.

**Comment by KrauseFx** [comment]
Hey @martinohman , great news, the plugin system is ready to be used, This would be the perfect opportunity to build and use your customized slack action (under a different name), and offer it to everyone who needs it: [Get started with plugins](https://github.com/fastlane/fastlane/issues/4873)  🚀
