### ISSUE TITLE
Issue retrieving API KEY (portal_client.rb:31:in `api_key')

### ISSUE THREAD

**Issue by sovithia** [fastlane/fastlane#4198]
Had that : 

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.23.0/lib/spaceship/portal/portal_client.rb:31:in `api_key': [!] Could not find latest API Key from the Dev Portal - the server might be slow right now (RuntimeError)

I figured out apple moved the location of its file and give a 302 redirect on url :
https://developer.apple.com/membercenter/index.action used in portal_client.rb line 20.
Had the replace that line by : 
landing_url = "https://developer.apple.com/account/"

Wanted to share it.

**Comment by TKBurner** [comment]
@sovithia Thanks for sharing. I'll make sure the team has a look at this 👍

**Comment by mfurtak** [comment]
Hi @sovithia - thanks for the report :+1: 

This change has been made in the latest `spaceship` code, so please make sure you're running the most recent version of `fastlane` and `spaceship`, and you should be all set :+1:
