### ISSUE TITLE
Slow to launch on 10.11

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#420]
Is anyone else experiencing very slow launch times for fastlane on El Capitan?

**Comment by KrauseFx** [comment]
If you want full control I'd recommend using `rvm` to manage and update your Ruby installation.

**Comment by KrauseFx** [comment]
I haven't yet updated, so I can't tell.

**Comment by milch** [comment]
It'd be interesting to know which ruby version El Capitan runs. Can you show us the output of `ruby --version` ? 

Also check the output of `gem list --local`, the more gems you have, the slower starting up each of them gets. You can do `gem cleanup` to uninstall outdated versions of gems.

**Comment by postmechanical** [comment]
`ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]`

**Comment by KrauseFx** [comment]
`2.0.0` :disappointed:

**Comment by milch** [comment]
In that case I'd recommend you follow the small guide I put together [here](https://github.com/KrauseFx/deliver/issues/266#issuecomment-121647784) to upgrade your ruby version to the most current one using `rbenv`.

**Comment by postmechanical** [comment]
Ran `gem cleanup` and got only a slight improvement. `fastlane help` takes `8s` to run. Will live with the pain for now @milch. Every time I try `rbenv` or `rvm` I end up reverting in frustration when everything eventually blows up on me.

**Comment by milch** [comment]
It was the same for me when I tried `rvm`, but `rbenv` seems to work very well. 

There's one last thing you could try if you want: installing `stackprof` and creating a dump of `fastlane`'s startup.  

You'd have to check out this repository, go into `bin/fastlane.rb` and wrap the whole thing (except for the `#!/usr/bin/env ruby` line, you can leave that as-is) in the following block:

```
require 'stackprof'
StackProf.run(mode: :cpu, out: 'prof-cpu-fastlane.dump') do
    # contents 
end
```

You should then be able to run `bin/fastlane --help`. If you send us the resulting `prof-cpu-fastlane.dump` file, we could analyse wether there are any additional performance issues with `fastlane` on El Capitan.

**Comment by alextud** [comment]
gem cleanup did the trick for me.

**Comment by ChrisRicca** [comment]
`gem cleanup` took `fastlane --version` from 2 minutes down to 6 seconds for me.

**Comment by KrauseFx** [comment]
I added a note to the README: https://github.com/KrauseFx/fastlane/commit/80a88600531f5d5013584e3195c961f9b50cae04 :+1:

**Comment by kdawgwilk** [comment]
I'm also experiencing slowness and `gem cleanup` didn't solve it for me ;(

**Comment by JaviSoto** [comment]
Hi @kdawgwilk!, is this still an issue for you?

**Comment by icyleaf** [comment]
`gem cleanup` is also works for me, what happen :sob:

**Comment by KrauseFx** [comment]
We can close this for now, as the update manager tells people to run `gem cleanup` from time to time :+1:

**Comment by powtac** [comment]
fastlane is also slow for me at startup. Only after an fastlane upgrade after the first launch it's fast.

**Comment by TKBurner** [comment]
@powtac Are you using RVM? Can you run ruby -v and send me the output? Thanks!
