### ISSUE TITLE
Passing array of launch arguments to snapshot command line does not work

### ISSUE THREAD

**Issue by MattCheetham** [fastlane/fastlane#4202]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to pass launch arguments to the command line tool as an array. This is so that the snapshots will be run with each of the objects separately as detailed in the documentation. I tried doing this with a snapfile and it worked fine but for this use case I need to use the command line arguments. The problem I have is that passing a command like ```snapshot -m -_SNAPSHOT_LANGUAGE can_en,-_SNAPSHOT_LANGUAGE can_fr -w "ios/GDPC First Aid Workspace.xcworkspace"``` the command line interprets ```-_SNAPSHOT_LANGUAGE``` as another input parameter like ```-m```. I've tried wrapping it in quotes, escaping etc. I can't see how this would work as I need to pass the dash before the key name for it to work. I'm sure I'm missing something obvious but would appreciate guidance on where I'm going wrong.

##### Complete output when running fastlane, including the stack trace and command used

```
snapshot -m -_SNAPSHOT_LANGUAGE can_en,-_SNAPSHOT_LANGUAGE can_fr -w "ios/GDPC First Aid Workspace.xcworkspace"

invalid option: -_SNAPSHOT_LANGUAGE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile (Which I don't want to use eventually):
```ruby
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6",
])

languages([
  "en-US"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
launch_arguments([
  "-_SNAPSHOT_LANGUAGE can_en",
  "-_SNAPSHOT_LANGUAGE can_fr"
])

# The name of the scheme which contains the UI Tests
scheme "GDPC First Aid"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help

```

### Environment

fastlane version (fastlane 1.81.0):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

Current running ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]

### Note
It's worth noting that if I run the command as  ```snapshot -m "_SNAPSHOT_LANGUAGE can_en,_SNAPSHOT_LANGUAGE can_fr" -w "ios/GDPC First Aid Workspace.xcworkspace"``` which has the dashes on the key values removes, I get the following output which is *almost* correct.

```+----------------------------+---------------------------------------------------------------------+
|                                   Summary for snapshot 1.12.1                                    |
+----------------------------+---------------------------------------------------------------------+
| launch_arguments           | ["_SNAPSHOT_LANGUAGE can_en", "_SNAPSHOT_LANGUAGE can_fr"]          |
| workspace                  | ios/GDPC First Aid Workspace.xcworkspace                            |
| devices                    | ["iPhone 6"]                                                        |
| languages                  | ["en-US"]                                                           |
| scheme                     | GDPC First Aid                                                      |
| clear_previous_screenshots | true                                                                |
| output_directory           | /Users/matthewcheetham/Local iOS/GDPC Screenshotter/GDPC Screens... |
| ios_version                | 9.3                                                                 |
| skip_open_summary          | false                                                               |
| reinstall_app              | false                                                               |
| erase_simulator            | false                                                               |
| buildlog_path              | ~/Library/Logs/snapshot                                             |
| clean                      | false                                                               |
| number_of_retries          | 0                                                                   |
| stop_after_first_error     | false                                                               |
+----------------------------+---------------------------------------------------------------------+```

**Comment by TKBurner** [comment]
@MattCheetham Have you tried passing it as -languages?

**Comment by MattCheetham** [comment]
@TKBurner Hey, I realise it looks like I'm trying to set the languages, that's not actually what I want. It's actually an internal value that I need to set via user defaults in our app. The language as en-US is fine.

**Comment by markltownsend** [comment]
I am having the same issue.  Here is an example of my command line

snapshot -m "[-emailAddress email@home.com -password password123]".

Here is what the Summary says:
launch_arguments           | ["[-emailAddress email@home.com -password password123]"]

And here is what I am using in my XCUITest:
`guard let emailAddress = NSUserDefaults.standardUserDefaults().stringForKey("emailAddress") else {
  XCAssert(false)
  return
}
`

and emailAddress is nil and my guard statement fails.

**Comment by TKBurner** [comment]
@markltownsend Thanks for following up. I just reached out to the core team for some clarity on this. We'll update on this thread 👍

**Comment by TKBurner** [comment]
HI @markltownsend Thanks for working with me on this. Unfortunately there isn't a way to pass an array from the command line for this. In order to get it working you'll need to use the snapfile. Hope that you have a wonderful week 👍

**Comment by MattCheetham** [comment]
Thanks for clarifying
