### ISSUE TITLE
Match/sigh question how to set build setings for adhoc and appstore

### ISSUE THREAD

**Issue by freynolds** [fastlane/fastlane#4204]
Hi, I'm having to change provisioning profile release from $(sigh_<bundle_identifier>_adhoc) to $(sigh_<bundle_identifier>_appstore) in several apps we use this two ways so I can send an update to a client (without any delay) and upload to the appstore in the same process.
Is there any way to change this so I can have just one variable in the Release field and fastlane use one or the other?

My regards
Francis.

**Comment by TKBurner** [comment]
Hi @freynolds! Great to hear from you. You can use two different lanes for these two different build types. Let me know if you have any questions about getting up and running, I'd love to help. 👍
