### ISSUE TITLE
No ability to define specific tester groups for TestFairy action

### ISSUE THREAD

**Issue by jgreubel** [fastlane/fastlane#4212]
### Issue Description

There is no way to define the list of tester groups for an upload of a TestFairy build to notify too.  This is useful so that the correct people are notified instead of none. Specifically we have multiple apps that we build and push to TestFairy, this allows us to only send updates to the correct testers for only the apps they should get notifications from.

Currently the 'testers_groups' option does not exist for the TestFairy action used below.

### Configuration Files
Fastfile:
```ruby
lane :testfairy do
    ENV["MATCH_FORCE_ENTERPRISE"] = "1"
    match(type: "enterprise")
    
    gym(scheme: "MyScheme")

    testfairy(api_key: ".......", comment: "I like turtles", testers_groups: "people-i-like-to-spam")
  end
```

### Environment
fastlane version (run `fastlane -v`): fastlane 1.81.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

#4210

**Comment by TKBurner** [comment]
Thanks for opening up this proposal for a pull request. I'm going to mark this as 'help wanted' so people can take a look. I'm also going to add this to our internal review so we can let you know what we think.

Thanks! 👍
