### ISSUE TITLE
unsupportedListingLanguage: Language not supported.

### ISSUE THREAD

**Issue by vikram1234** [fastlane/fastlane#4214]
Fatlane supply team, i am getting following error while submitting APK to google store. 
supply version - 0.6.2   

I took metadata from existing app which is downloaded by "supply init" and while putting back apk, i getting this error. 

/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:202:in `check_status': [!] unsupportedListingLanguage: Language not supported. (Google::Apis::ClientError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/api_command.rb:103:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:170:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:275:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/base_service.rb:267:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/generated/google/apis/androidpublisher_v2/service.rb:1300:in `get_listing'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/client.rb:127:in `listing_for_language'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/uploader.rb:17:in `block in perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/uploader.rb:13:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/uploader.rb:13:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/actions/supply.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:47:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.64.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by vikram1234** [comment]
Issue Description
[01:00:53]: Variable Dump:
[01:00:53]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android deploy"}
[01:00:53]: unsupportedListingLanguage: Language not supported.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | supply                              | 5           |
+------+-------------------------------------+-------------+

[01:00:54]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '67e716898ad3d8740e2afc6c563a6c1e'
The crash report has been stored locally '/tmp/sentry_67e716898ad3d8740e2afc6c563a6c1e.json'
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:202:in `check_status': [!] unsupportedListingLanguage: Language not supported. (Google::Apis::ClientError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/api_command.rb:103:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:170:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:275:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/base_service.rb:267:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/generated/google/apis/androidpublisher_v2/service.rb:1300:in `get_listing'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/client.rb:127:in `listing_for_language'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/uploader.rb:17:in `block in perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/uploader.rb:13:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.6.2/lib/supply/uploader.rb:13:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/supply.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:47:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
INSERT OUTPUT HERE

Configuration Files

lane :deploy do
  supply(
      apk: "./build/outputs/apk/app_release.apk",
      metadata_path: "./fastlane/metadata/"
    )

end
Fastfile:

supply(
    apk: "./build/outputs/apk/app_release.apk",
    metadata_path: "./fastlane/metadata/"
  )
Environment

fastlane 1.81.0

**Comment by vpolouchkine** [comment]
What languages do you have under ./metadata?

**Comment by vikram1234** [comment]
de-DE
en-US
fr-FR
it-IT
nl-NL
pl-PL

**Comment by TKBurner** [comment]
@vikram1234 Thanks for following up. We are going to look over this here and see what could be causing this. Thanks! 👍

**Comment by vikram1234** [comment]
@TKBurner - could you please update if were able to find something? or anything i should look on...

**Comment by TKBurner** [comment]
Hi @vikram1234 Thanks for following up. Do you still see this issue if you only have en-US as a listed language? The error messaging is suggesting that one of your language codes isn't working. Thanks!

**Comment by vikram1234** [comment]
Hi @TKBurner - thanks for your reply, i have removed all folders except "en-US" from fastlane/metadata folder and still getting same issue, do i have to change something else to reflect only "en-US??

**Comment by TKBurner** [comment]
Hi @vikram1234 Thanks for following up and testing that. I'm going to send this around to see what could be causing this 👍 Have a great day.

**Comment by asfalcone** [comment]
@vikram1234 have you tried to not specify the `metadata_path` to `supply`? That shouldn't be neccessary unless the metadata is in an unusual directory.

Can you also share a screenshot of your directory structure? Just like this please:
![image](https://cloud.githubusercontent.com/assets/1848683/14859465/3d18f968-0c72-11e6-9d7e-48f2cc6866f6.png)

**Comment by vikram1234** [comment]
![photo on 25-04-16 at 3 11 am 2](https://cloud.githubusercontent.com/assets/11531441/14860401/44fcf842-0cc6-11e6-8252-5e414354b2a9.jpg)

**Comment by vikram1234** [comment]
![screen shot 2016-04-27 at 10 19 45 pm](https://cloud.githubusercontent.com/assets/11531441/14860413/5ab0daa0-0cc6-11e6-9070-5b338c08c12b.png)

**Comment by asfalcone** [comment]
@vikram1234 Thanks, that all looks fine. Curious though, what do the different colors mean in your output?

Were you able to give it a try without the `metadata_path` param?

**Comment by vikram1234** [comment]
thanks a lot @asfalcone, if i comment "#metadata_path: "./fastlane/metadata/" it worked to me and i can see all en-US metadata too. Is that right way? 
Different colors are just Atom editor... 

My lane code - 

  lane :deploy do
    #gradle(task: "assembleRelease")
    #supply --apk "./build/outputs/apk/proapp.apk" --track

    supply(
        apk: "./build/outputs/apk/app_release.apk",
        #metadata_path: "./fastlane/metadata/"
      )

  end

**Comment by asfalcone** [comment]
@vikram1234 yes, it looks like "./fastlane/metadata/" is not the correct path to your metadata relative to where fastlane is being run from. Glad you're up and running. 👍

**Comment by vikram1234** [comment]
@asfalcone @TKBurner .. thanks a lot you guys.
