### ISSUE TITLE
Create new app account with Supply

### ISSUE THREAD

**Issue by vikram1234** [fastlane/fastlane#4215]
Team,

I am trying to create new App account with Supply and i could not find a way to doing it?

Is this supported or does not?

Regards,
Vikram

**Comment by asfalcone** [comment]
@vikram1234 you can only update existing Apps in Google Play with supply, due to the Google Play api limitation. You need to manually upload an APK via the web UI to start the process. :+1:

**Comment by vikram1234** [comment]
Thanks a lot @asfalcone for confirming and quick reply too.
