### ISSUE TITLE
Spaceship ruby docs point to the wrong repo

### ISSUE THREAD

**Issue by RocketPop** [fastlane/fastlane#4217]
The Spaceship pages point you to RubyDoc for the details of the API ( see https://github.com/fastlane/fastlane/tree/master/spaceship#full-documentation )

However these pages links all point to the old repo, so [View on GitHub] links are broken. For example: http://www.rubydoc.info/github/fastlane/spaceship/Spaceship.app and try the [View on GitHub] link

**Comment by vpolouchkine** [comment]
Thanks for the report!

**Comment by RocketPop** [comment]
Hello, bot. This is a documentation issue :)

**Comment by KrauseFx** [comment]
It seems like we don't link to RubyDoc any more, right? Is this issue resolved?
