### ISSUE TITLE
Scan not working when used with cocoapods

### ISSUE THREAD

**Issue by jakunico** [fastlane/fastlane#4218]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Whenever execute `cocoapods` and `scan` in the same lane, tests fail.

```ruby
lane cocoapodsandtest do
  cocoapods
  scan(scheme: "Stage", clean: true, code_coverage: false)
end
```

BUT! If I remove cocoapods step, everything works perfectly:

```ruby
lane cocoapodsandtest do
  #cocoapods
  scan(scheme: "Stage", clean: true, code_coverage: false)
end
```

EVEN MORE, if I run the following everything runs correctly:

```
$ fastlane run cocoapods
(cocoapods run OK)
$ fastlane run scan scheme:Stage clean:true code_coverage:false
(scan runs OK!)
```

##### Complete output when running fastlane, including the stack trace and command used

My tests actually run correctly, but when scan is compiling one of my dependencies (Alamofire), I see these errors:

```
Compiling Validation.swift
[15:22:28]: ▸ ❌  /Users/(redacted)/Library/Developer/Xcode/DerivedData/redacted-fmskyfgnfiaypmezztmlroedukre/Build/Intermediates/Pods.build/Stage Debug-iphonesimulator/Alamofire.build/unextended-module.modulemap:2:19: umbrella header 'Alamofire-umbrella.h' not found
[15:22:28]: ▸ umbrella header "Alamofire-umbrella.h"
[15:22:28]: ▸                   ^
```

And, at the end of running scan

```
Testing failed:
Umbrella header 'Alamofire-umbrella.h' not found
Underlying Objective-C module 'Alamofire' not found
** TEST FAILED **
[15:22:57]: Exit status: 65
```

### Configuration Files

Fastfile:
```ruby
fastlane_version "1.80.0"
default_platform :ios

platform :ios do

  lane cocoapodsandtest do
    cocoapods
    scan(scheme: "Stage", clean: true, code_coverage: false)
  end

end
```

Podfile:

```
platform :ios, '9.0'
use_frameworks!

target 'Redacted' do
pod 'Alamofire', '~> 3.3.1'
pod 'Fabric', '~> 1.6.7'
pod 'Crashlytics', '~> 3.7.0'
pod 'CocoaLumberjack/Swift', '~> 2.2.0'
end

target 'RedactedTests' do
pod 'FBSnapshotTestCase', '~> 2.1.0'
end

target 'RedactedUITests' do
end
```

### Environment

`fastlane 1.81.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

`NO`

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

`NO`

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by TKBurner** [comment]
Hi @jakunico Thanks for reporting this can you let me know if this is the same behavior described in #3886

**Comment by jakunico** [comment]
Hi @TKBurner, it doesn't seem to be the same issue.

If I run `scan` alone, tests pass correctly:

```
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 2     |
| Number of failures | 0     |
+--------------------+-------+
````

This issue arises when I have `cocoapods` *and* `scan` actions together in a lane.

**Comment by TKBurner** [comment]
@jakunico Thanks for following up. I'm going to circle back with the team here so we can look into this. Hope that you have a great day! 👍

**Comment by jakunico** [comment]
It seems to be working now! Not sure if it's because of updating fastlane or maybe it's a false positive, but I'll re-open this if I see this issue again.

**Comment by KrauseFx** [comment]
Cool, thanks 👍

**Comment by nickjwallin** [comment]
Sorry if this is simply an annoying notification on an old issue, but I was having this exact same issue, and updating to the latest `fastlane` did solve the issue. It was happening to me 100% of the time.

**Comment by TKBurner** [comment]
@nickjwallin Awesome Nick! Thanks for letting us know. 👍 💯
