### ISSUE TITLE
Import problem trying to configure my first project

### ISSUE THREAD

**Issue by halbano** [fastlane/fastlane#4224]
Hi all, 

I'm having a problem using this. The second line fails and doesn't compile. 

>     XCUIApplication *app = [[XCUIApplication alloc] init];
>     [Snapshot setupSnapshot:app];
>     [app launch];

Maybe I'm missing something regarding the instructions to get it working: 
**(Objective C only) add the bridging header to your test class.
#import "MYUITests-Swift.h"
The bridging header is named after your test target with -Swift.h appended.**

Any help is really appreciated.

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
