### ISSUE TITLE
How to build project without scheme?

### ISSUE THREAD

**Issue by DevellMen** [fastlane/fastlane#4226]
How to build project without scheme? Using Targets and Build Configurations.
Now i do it like this:

```
xcodebuild install -sdk iphoneos -project "${PROJECTFILE}" -target "${TARGET}" -configuration "${CONFIGURATION}" ... 
```
But how  can i do it using fastlane?

**Comment by vpolouchkine** [comment]
I believe you can do so by passing `--xcargs` to `gym`.

**Comment by TKBurner** [comment]
@DevellMen Let us know if you had any problems getting up and running. Closing this out for now 👍
