### ISSUE TITLE
fastlane not work

### ISSUE THREAD

**Issue by goodcyg** [fastlane/fastlane#4229]
Driving the lane 'ios AdHoc' 🚀
[00:06:29]: ---------------------------------------------------------------------------------------------------------
[00:06:29]: --- Step: /usr/libexec/PlistBuddy -c "set :ChannelID AdHoc" ./../fastlanedemo/fastlanedemo/Info.plist ---
[00:06:29]: ---------------------------------------------------------------------------------------------------------
[00:06:29]: $ /usr/libexec/PlistBuddy -c "set :ChannelID AdHoc" ./../fastlanedemo/fastlanedemo/Info.plist
[00:06:29]: ▸ Set: Entry, ":ChannelID", Does Not Exist
[00:06:29]: ▸ File Doesn't Exist, Will Create: ./../fastlanedemo/fastlanedemo/Info.plist
[00:06:29]: Variable Dump:
[00:06:29]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios AdHoc"}
[00:06:29]: Exit status of command '/usr/libexec/PlistBuddy -c "set :ChannelID AdHoc" ./../fastlanedemo/fastlanedemo/Info.plist' was 1 instead of 0.
Set: Entry, ":ChannelID", Does Not Exist
File Doesn't Exist, Will Create: ./../fastlanedemo/fastlanedemo/Info.plist

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | /usr/libexec/PlistBuddy -c "set :ChannelID AdHoc" ./../fastla | 0           |
+------+---------------------------------------------------------------+-------------+

[00:06:29]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Exit status of command '/usr/libexec/PlistBuddy -c "set :ChannelID AdHoc" ./../fastlanedemo/fastlanedemo/Info.plist' was 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
Set: Entry, ":ChannelID", Does Not Exist
File Doesn't Exist, Will Create: ./../fastlanedemo/fastlanedemo/Info.plist

	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:182:in `block in sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:181:in `sh'
	from Fastfile:85:in `set_info_plist_value'
	from Fastfile:89:in `set_channel_id'
	from Fastfile:134:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
get a eorror ?
  updage gem : gem update --system   not working,help me?

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by goodcyg** [comment]
Error as follows：
zhongxingzhinengdeMacBook-Air:fastlanedemo Jackson$ sh build.sh 1.1.1 10
[14:47:57]: -------------------------------------------------
[14:47:57]: --- Step: Verifying required fastlane version ---
[14:47:57]: -------------------------------------------------
[14:47:57]: fastlane version valid
[14:47:57]: ------------------------------
[14:47:57]: --- Step: default_platform ---
[14:47:57]: ------------------------------
[14:47:57]: Driving the lane 'ios Develop' 🚀
[14:47:57]: -------------------------------------------------------------------------------------------
[14:47:57]: --- Step: /usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlanedemo/Info.plist ---
[14:47:57]: -------------------------------------------------------------------------------------------
[14:47:57]: $ /usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlanedemo/Info.plist
[14:47:57]: ▸ Set: Entry, ":ChannelID", Does Not Exist
[14:47:57]: ▸ File Doesn't Exist, Will Create: ./fastlanedemo/Info.plist
[14:47:57]: Variable Dump:
[14:47:57]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios Develop"}
[14:47:57]: Exit status of command '/usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlanedemo/Info.plist' was 1 instead of 0.
Set: Entry, ":ChannelID", Does Not Exist
File Doesn't Exist, Will Create: ./fastlanedemo/Info.plist


[14:47:57]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '1b3fa5dac0bded72e7f397e8e293d1c5'
The crash report has been stored locally '/tmp/sentry_1b3fa5dac0bded72e7f397e8e293d1c5.json'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Exit status of command '/usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlanedemo/Info.plist' was 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
Set: Entry, ":ChannelID", Does Not Exist
File Doesn't Exist, Will Create: ./fastlanedemo/Info.plist

	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:182:in `block in sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:181:in `sh'
	from Fastfile:85:in `set_info_plist_value'
	from Fastfile:89:in `set_channel_id'
	from Fastfile:167:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by goodcyg** [comment]
$ /usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlanedemo/Info.plist
[16:04:54]: ▸ Set: Entry, ":ChannelID", Does Not Exist
[16:04:54]: ▸ File Doesn't Exist, Will Create: ./fastlanedemo/Info.plist
[16:04:54]: Variable Dump:
[16:04:54]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios Develop"}
[16:04:54]: Exit status of command '/usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlanedemo/Info.plist' was 1 instead of 0.
Set: Entry, ":ChannelID", Does Not Exist
File Doesn't Exist, Will Create: ./fastlanedemo/Info.plist


+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | /usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlan | 0           |
+------+---------------------------------------------------------------+-------------+

[16:04:54]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'b8342908902fbdc8154d2ad3852b59c6'
The crash report has been stored locally '/tmp/sentry_b8342908902fbdc8154d2ad3852b59c6.json'
/Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Exit status of command '/usr/libexec/PlistBuddy -c "set :ChannelID Develop" ./fastlanedemo/Info.plist' was 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
Set: Entry, ":ChannelID", Does Not Exist
File Doesn't Exist, Will Create: ./fastlanedemo/Info.plist

	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:182:in `block in sh'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:181:in `sh'
	from Fastfile:85:in `set_info_plist_value'
	from Fastfile:89:in `set_channel_id'
	from Fastfile:167:in `block (2 levels) in parsing_binding'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /Users/Jackson/.rvm/rubies/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/Jackson/.rvm/rubies/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Jackson/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
update ruby  Still can not work

**Comment by goodcyg** [comment]
Environment:
fastlane 1.81.0
rvm 1.27.0
xcode 7.2.1
gem 2.5.1
ruby 2.3.0

**Comment by goodcyg** [comment]
bundle install

Could not locate Gemfile or .bundle/ directory

**Comment by vpolouchkine** [comment]
Can you post your Fastfile please?

**Comment by TKBurner** [comment]
@goodcyg Great to hear from you! Does the info.plist file exist at fastlanedemo/info.plist? Let me know! Thanks 👍

**Comment by goodcyg** [comment]
Directory structure is like this
/Users/xxx/Desktop/iOSMake/ios_ci_fastlane_demo-master/fastlanedemo/fastlanedemo/Info.plist 
 /Users/xxx/Desktop/iOSMake/ios_ci_fastlane_demo-master/fastlanedemo/build.sh 
I changed this way
../fastlanedemo/Info.plist replace ./fastlanedemo/Info.plist 
it is work.
../  Isn't it back to the top? Don't understand???

**Comment by TKBurner** [comment]
Hi @goodcyg Thanks for following up. It looks like you are actually missing an entry in your info.plist

Set: Entry, ":ChannelID", Does Not Exist 

Do you use Urban Airship?

**Comment by goodcyg** [comment]
Hi  @TKBurner Thanks. I modified the a problem.（Set: Entry, ":ChannelID", Does Not Exist）
mac book air OS X EI Captian 10.11.14

**Comment by TKBurner** [comment]
Hi @goodcyg! Awesome, are you did that resolve this error?

**Comment by goodcyg** [comment]
Hi @TKBurner  resolve this error thanks。

**Comment by TKBurner** [comment]
Closing this out! 👍
