### ISSUE TITLE
Specify Xcode scheme for `fastlane init` command

### ISSUE THREAD

**Issue by tadija** [fastlane/fastlane#4236]
### New Issue Checklist

- [✓] Updated fastlane to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have an existing iOS project with multiple Xcode schemes (develop, stage, production) and each scheme builds different bundle ID (ad hoc, in house, app store).

I wanted to do `fastlane init` with scheme for production in order to create initial version of config files and to pull all existing data from iTunes Connect.

Problem is that `fastlane init` command does not let me choose scheme, but it goes with **develop** scheme by default. That bundle ID does not exist on iTunes Connect so it asks me to create new App on iTC and I have to cancel there.

So, I end up without having any initial config files and/or resources in order to continue using fastlane.

Is there a way to specify which scheme will be used for `fastlane init` command?
Do you have any other suggestions for this case?

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane init
[17:57:49]: Detected iOS/Mac project in current directory...
[17:57:49]: This setup will help you get up and running in no time.
[17:57:49]: fastlane will check what tools you're already using and set up
[17:57:49]: the tool automatically for you. Have fun! 
[17:57:49]: Created new folder './fastlane'.
[17:57:49]: xcrun xcodebuild -list -workspace './ProjectName.xcworkspace'
Your Apple ID (e.g. fastlane@krausefx.com): user@domain.com
[17:58:05]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[17:58:05]: Starting login with user 'user@domain.com'

+----------------+---------------------------------------------------------------------------------------+
|                                            Detected Values                                             |
+----------------+---------------------------------------------------------------------------------------+
| Apple ID       | user@domain.com                                                                |
| App Name       | ProjectName Develop                                                                    |
| App Identifier | com.domain.appName-Develop                                               |
| Workspace      | /Users/username/Dropbox/Developer/company/ProjectDir/ProjectName.xcworkspace |
+----------------+---------------------------------------------------------------------------------------+

[17:58:12]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
Please confirm the above values (y/n)
n
App Identifier (com.krausefx.app): 
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

I don't have any configuration file yet. I was hoping that `fastlane init` would make one.

### Environment

fastlane version (run `fastlane -v`): 1.81.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
Hi @tadija! Thanks for reaching out. Fastlane init is not built around a specific app scheme. Can you share the full output if you say yes to the command?

Thanks!

**Comment by tadija** [comment]
Hi @TKBurner, thanks for looking into this.

I don't quite understand how is init not related to any scheme when output data in "Detected Values" is definitely coming from one of my shared schemes, but just not the right one (I can't stop thinking that command line argument for choosing specific scheme on init would solve all problems of this kind, something like `fastlane init --scheme "Production"`).

Back to your question, I will share my full output if said yes to the command, even if I know that I don't want to create new app record on client's iTC and ADP with non-production environment data which is detected.

Here it is:
```
$ fastlane init
[17:17:47]: Detected iOS/Mac project in current directory...
[17:17:47]: This setup will help you get up and running in no time.
[17:17:47]: fastlane will check what tools you're already using and set up
[17:17:47]: the tool automatically for you. Have fun! 
[17:17:47]: Created new folder './fastlane'.
Your Apple ID (e.g. fastlane@krausefx.com): user@domain.com
[17:18:03]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[17:18:03]: Starting login with user 'user@domain.com'

+----------------+------------------------------------------------------------------------+
|                                     Detected Values                                     |
+----------------+------------------------------------------------------------------------+
| Apple ID       | user@domain.com
| App Name       | AppName Stage                                                          |
| App Identifier | com.domain.appname-stage                                               |
| Project        | /Users/username/Dropbox/Developer/company/ProjectDir/ProjectName.xcodeproj  |
+----------------+------------------------------------------------------------------------+

[17:18:11]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[17:18:11]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
Please confirm the above values (y/n)
y
[17:21:12]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[17:21:12]: Creating the app on iTunes Connect and the Apple Developer Portal

+----------------+-----------------------------+
|          Summary for produce 1.1.1           |
+----------------+-----------------------------+
| app_name       | AppName Stage               |
| app_identifier | com.domain.appname-stage    |
| username       | user@domain.com             |
| sku            | 1234567890                  |
| language       | English                     |
| skip_itc       | false                       |
| skip_devcenter | false                       |
| team_id        | AABBCCDDEE                  |
+----------------+-----------------------------+

[17:21:19]: Creating new app 'AppName Stage' on the Apple Dev Center
[17:21:20]: Loading up 'deliver', this might take a few seconds
[17:21:20]: Login to iTunes Connect (user@domain.com)
[17:21:23]: Login successful
[17:21:23]: Could not find app with app identifier 'com.domain.appname-stage' in your iTunes Connect account (user@domain.com - Team: 1234567)
[17:21:23]: An error occured during the setup process. Falling back to manual setup!
App Identifier (com.krausefx.app): 
```

As you may notice, I tried it on different project also, this time it detected "Stage" scheme instead of "Develop" but again not "Production" scheme (which would probably pass because it would find app identifier in used iTC account). 

After confirming detected values, this time I got a little further - **Appfile** was created, but the other steps after that one actually didn't make any changes on iTC and ADP (which was good for me as I didn't even want that, but...).

Also, is it necessary for `init` command to require complete connection to iTC and ADP, can't it just read data that is there locally and generate config files which are needed. Is there any argument that I could pass to `init` command?

Thanks for helping!

**Comment by TKBurner** [comment]
Hi @tadija! Thanks for following up. Fastlane init runs the development scheme. However, I'm going to have the team look into this as a feature request. Thanks for working with us. We'll provide any updates here. Thanks! 👍
