### ISSUE TITLE
Match + CloudKit

### ISSUE THREAD

**Issue by giinnga** [fastlane/fastlane#4237]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

While using match, I enabled CloudKit and, after that, updated the provisioning profiles using `match development --force`. Now Xcode says that I don't have valid provisioning profiles.

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  # Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    
  end

  desc "Setup the project for usage"
  lane :setup do
    match
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "chamada") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "chamada") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

```

### Environment

fastlane version (run `fastlane -v`): 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by giinnga** [comment]
Anyone here?

**Comment by vpolouchkine** [comment]
How did you enable CloudKit?

**Comment by giinnga** [comment]
hey @vpolouchkine, so I first created the project without enabling CloudKit and used `match development`. After data, it was decided to use CloudKit to the project, and i enabled it just like the Apple site recommends it (https://developer.apple.com/library/ios/documentation/DataManagement/Conceptual/CloudKitQuickStart/EnablingiCloudandConfiguringCloudKit/EnablingiCloudandConfiguringCloudKit.html#//apple_ref/doc/uid/TP40014987-CH2-SW1). Then it said that it showed two erros at the capabilities screen:

**Comment by giinnga** [comment]
I just saw that I forgot to enable `key-value storage`. But even with it enable I have the following error in the capabilities screen:

![image](https://cloud.githubusercontent.com/assets/7843637/14660387/4cf7d19e-067b-11e6-9146-b7ab99105650.png)

**Comment by TKBurner** [comment]
@giinnga Thanks for following up. Are you able to refresh your provisioning profiles with match nuke? Thanks!

**Comment by giinnga** [comment]
@TKBurner I avoid using nuke, I will try a manual approach at the Apple developers website later, and post here if I can find / fix the situation. But I don't think this is a match problem.

**Comment by giinnga** [comment]
@TKBurner after manually configuring the container in the Apple Developer Center Website, deleting the existing provisioning profiles and running `match development --force`, it doesn't show any more errors.

**Comment by giinnga** [comment]
@TKBurner sorry, I don't know if this whole process should have been taken care by match, so I will leave it open until an answer.

**Comment by TKBurner** [comment]
@giinnga Thanks for following up. It sounds like someone clicked 'fix issue' which causes Match to fail. Glad to hear you got up and running! 👍
