### ISSUE TITLE
Deliver change "Version Release" to "Manually release this version"

### ISSUE THREAD

**Issue by mywander** [fastlane/fastlane#4239]
### New Issue Checklist

I set the "version release" in itunesconnect to "Automatically release this version". But after I run "deliver run --skip_screenshots" the "version release" changed to "Manually release this version".
Please fix the bug.

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
Hi @mywander! Thanks for reaching out. I'm pretty sure this is expected behavior since deliver sets some preferences. I'm going to have someone take a second look to make sure. 👍
