### ISSUE TITLE
Create too many certificates for each provisioning profile

### ISSUE THREAD

**Issue by xareelee** [fastlane/fastlane#4244]
I have multiple `app id` in a Apple Dev account. For each provisioning profile (`adhoc`/`appstore`/`enterprise`), match create multiple certificates for those provisioning profiles. And if I use `match` to manage multiple `app id`, it will create too many certificates, and it will fail to create a new one (exceed the maximum numbers of the certificates).

Can make `match` use the same type certificate (`development` or `distribution`)?

**Comment by fabioknoedt** [comment]
@xareelee remember that `match` does NOT work with `enterprise` profiles.

> Enterprise Profiles
> 
> Attackers could use an In-House profile to distribute signed application to a potentially unlimited number of devices. All this would run under your company name and it could eventually lead to Apple revoking your In-House account. However it is very easy to revoke a certificate to remotely break the app on all devices.
> 
> Because of the potentially dangerous nature of In-House profiles we decided to not allow the use of match with enterprise accounts.

Reference: https://codesigning.guide

**Comment by vpolouchkine** [comment]
`match` creates a single pair (cert + provisioning profile).
