### ISSUE TITLE
Framefile not being read in

### ISSUE THREAD

**Issue by justin** [fastlane/fastlane#4248]
### Issue Description

I spent some time trying to get our app running up on frameit, but was unsuccessful beyond just getting a border wrapped around my images. I punted on even trying to get text showing up for now. I'd just like to get it to accept my background image to start.

When I run `frameit silver --verbose` I don't get any output about a Framefile being read, not found, or anything. It just generates the bordered images at full-res.

### Configuration Files

Framefile.json:
```json
{
  "default": {
    "title": {
      "color": "#ffffff",
      "font": "./fonts/SF-UI-Display-Light.otf"
    },
    "background": "./background.jpg"
  }
}
```

My directory structure is situated as:

```
./fastlane/
./fastlane/screenshots/
./fastlane/screenshots/Framefile.json
./fastlane/screenshots/background.jpg
./fastlane/screenshots/fonts/*.otf
./fastlane/screenshots/en-US/*.png [Raw Screenshots] + the framed ones generated
```

### Environment

frameit version 2.5.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **NO**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **NO**

**Comment by vpolouchkine** [comment]
What happens when you run `frameit setup`?

**Comment by KrauseFx** [comment]
Could you try moving the `Framefile.json` to `./fastlane/`?

**Comment by justin** [comment]
@vpolouchkine every time i run `frameit setup` in my fastlane folder it acts like I don't have the `~/.frameit` set up, even though I have all the device frames in that folder.

![screen shot 2016-04-22 at 12 33 32 pm](https://cloud.githubusercontent.com/assets/1384/14751297/6f4e3a82-0886-11e6-9180-5fee31deb48b.png)


@KrauseFx tried moving the `Framefile.json` to `./fastlane/` and still the same output as before. No change.

**Comment by TKBurner** [comment]
Hi @justin, thanks for following up. We're going to look into this and I'm also going to mark it help wanted in case anyone from the community wants to chime in. Thanks 👍

**Comment by i2amsam** [comment]
@justin the prompts in `frameit setup` always indicated you were setting up the first time, even if you already had frames in `~/.frameit`.  Could you try lowercasing `Framefile.json` to `framefile.json`?

**Comment by KrauseFx** [comment]
@justin First off, really sorry you run into these issues. Unfortunately we're a bit behind with `frameit` compared to the other tools.

The documentation of this is not clear right now, sorry about this. Running `frameit setup` will launch the assistant that tells you how to download and use the latest device frames from Apple => `frameit setup` is just for setting up your machine, not your app for `frameit`

If you want to use `frameit`, just running `frameit` directly is enough. 

I see that for some reason your `Framefile.json` is not properly parsed (capitalized is correct). Using `frameit --verbose` it should print out the following:

```
Parsing config file './Framefile.json'
```

Unfortunately I can't reproduce this error locally. Would you mind sending your zipped directory of some sample screenshots inside their folders, with your `Framefile` to us? You can either attach it to this issue, or send it to us via email to github@krausefx.com
