### ISSUE TITLE
build randomly fails with error code 65

### ISSUE THREAD

**Issue by saruye** [fastlane/fastlane#4249]
### Issue Description

I migrated our manual buildscript to fastlane some time ago and I am very happy in general. The only problem I have left, is random build failures. In average every second build fails with error code 65 without any more information. Before using fastlane, I didn't have these errors.
I googled a lot, but couldn't find anything that helped me. My experience with ios is limited. So I am stuck on how to debug this. There is nothing in the logs that indicates an error. I don't think its a configuration problem, otherwise it should always fail. Is there something I can run differently to get more information what fails? Any documentation that I can read that might help me? Or some other place I should rather ask? 

##### Complete output when running fastlane, including the stack trace and command used
I run:  fastlane staging
....
build	18-Apr-2016 08:19:31	[33mâ–¸[0m [39;1mRunning script[0m 'Copy Pods Resources'
build	18-Apr-2016 08:19:31	[33mâ–¸[0m [39;1mRunning script[0m 'Upload dSYM File'
build	18-Apr-2016 08:19:31	[33mâ–¸[0m [39;1mRunning script[0m 'Increase Build Number'
build	18-Apr-2016 08:19:31	[33mâ–¸[0m [39;1mRunning script[0m 'Embed Pods Frameworks'
build	18-Apr-2016 08:19:31	[33mâ–¸[0m [39;1mTouching[0m our.app
build	18-Apr-2016 08:19:31	[33mâ–¸[0m [39;1mSigning[0m /Users/marketing/Library/Developer/Xcode/DerivedData/our-dmeacgssaqxzojagsftlykfuymct/Build/Intermediates/ArchiveIntermediates/..../some.app
build	18-Apr-2016 08:19:31	[33mâ–¸[0m [39;1mTouching[0m some.app.dSYM
build	18-Apr-2016 08:19:31	** ARCHIVE FAILED **
build	18-Apr-2016 08:19:31	[08:19:32]: [31mExit status: 65[0m
build	18-Apr-2016 08:19:31	[08:19:32]: [32m-------------------[0m
build	18-Apr-2016 08:19:31	[08:19:32]: [32m--- Step: slack ---[0m
build	18-Apr-2016 08:19:31	[08:19:32]: [32m-------------------[0m

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/x"
    cocoapods
    unlock_keychain(
      path: "",
      password: "password",
      set_default: true
   )
  end

  private_lane :build do |options| 
    
   appId = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

   update_info_plist(
    app_identifier: appId,
    plist_path: "path/to/plist.plist"
  )
   update_app_identifier(
     app_identifier: appId,
     plist_path: "path/to/plist.plist"
   )

   increment_build_number({
     build_number: latest_testflight_build_number + 1
   })
   cert(keychain_path:"keychain/path/")
   sigh


   if options.key?(:family) 
     gym(scheme: "our Release",
        xcargs: "TARGETED_DEVICE_FAMILY=\"#{options[:family]}\""
        )
   else 
     gym(scheme: "our Release")
   end

 end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build for stating"
  lane :staging do

   update_info_plist(
   plist_path: 'path/to/plist.plist', 
   display_name: 'our alpha' 
   )
   badge(alpha: true)

   build
   pilot(skip_submission: true)

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

     slack(
       message: "Successfully uploaded a testversion for #{lane}."
     )
  end

  error do |lane, exception|
     slack(
       message: "error on lane #{lane}: " + exception.message,
       success: false
     )
  end
end
```

### Environment
fastlane version fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by hardikdevios** [comment]
For me too
Here is the same thing
![screen shot 2016-04-18 at 11 12 25 pm](https://cloud.githubusercontent.com/assets/6657591/14613688/36e94be6-05bb-11e6-87d8-28316e4b3cf6.png)

So i was thinking where i am wrong so i started scrolling on top and see this

> ** CLEAN FAILED **

The following build commands failed:
Clean.Remove clean **path of that file or framework**

**Now i have two questions**

1) If CLEAN FAILED than can we stop the process of Archiving ?
2) can we change the color of FAILED messages like its currently in pink which is the same as warning message of the compiler so wasn't able to get notice i am attaching the screens below for better idea?

![screen shot 2016-04-18 at 11 23 09 pm](https://cloud.githubusercontent.com/assets/6657591/14614015/cece58d8-05bc-11e6-998f-2720d5b31729.png)

![screen shot 2016-04-18 at 11 23 24 pm](https://cloud.githubusercontent.com/assets/6657591/14614018/d073f684-05bc-11e6-9133-4db9f98c68d0.png)

![screen shot 2016-04-18 at 11 23 55 pm](https://cloud.githubusercontent.com/assets/6657591/14614019/d081b13e-05bc-11e6-8551-287cacf31ec7.png)

**Comment by vpolouchkine** [comment]
@saruye Can you please post the full log? Thanks.

**Comment by saruye** [comment]
Hi I uploaded the outputs of a successful build and a failing one. I don't see much difference between the 2 logs :/ 
When I was researching the error I found that some people had a problem with a failing script. I checked some of them and I don't think that they fail. I also checked the build log (/Users/marketing/Library/Logs/gym/coolApp-coolApp\ Release.log) for more detailed information and they also liked quite similar and I couldn't find any errors there either. 
Is there anything else I can run to get more detailed information about why this error is occurring? 
Thanks for you help already!

[fastlane_staging_20160421_0726_success.txt](https://github.com/fastlane/fastlane/files/229290/fastlane_staging_20160421_0726_success.txt)
[fastlane_staging_20160421_error.txt](https://github.com/fastlane/fastlane/files/229291/fastlane_staging_20160421_error.txt)

**Comment by vpolouchkine** [comment]
@saruye Thanks for the logs. Can you isolate the `gym` call and confirm if you still see the issue? If so, can you try building your app using `xcodebuild`? Do you see the same behavior?

**Comment by saruye** [comment]
I extracted the `set -o pipefail && xcodebuild -workspace './fileee.xcworkspace' -scheme 'fileee Release' -destination 'generic/platform=iOS' -archivePath '/Users/marketing/Library/Developer/Xcode/Archives/2016-04-22/fileee 2016-04-22 06.40.09.xcarchive' archive | tee /Users/marketing/Library/Logs/gym/fileee-fileee\ Release.log | xcpretty`
and did run it for a couple of times. I did see the same behavior. Sometimes it suceeds, sometimes it fails. I also did run it without the pipefail and still saw failures sometimes. Do you want me to provide some logs without |xcpretty?

**Comment by TKBurner** [comment]
Hi @saruye! Thanks for following up. If your build fails when you use xcodebuild it isn't an issue with Fastlane. Are you able to build your app in Xcode itself? Thanks!

**Comment by saruye** [comment]
hi, 
building with Xcode doesn't produce these issues. I suspected it might not be fastlane directly. I posted it here since I didn't have the issue before migrating to fastlane and I am totally stuck and don't know where else to look for the cause of these random failures. Can you hint me at some other place where to look? Or some command to run? 
Thanks!

**Comment by TKBurner** [comment]
@saruye Thanks for following up. I'm going to close out this issue, because it looks like you are seeing the same problem as #4197. We are going to work through this over there. Thanks!

**Comment by saruye** [comment]
Thanks for looking into this! If I can test something or be of any help, let me know. Looking forward to this issue being resolved :)
