### ISSUE TITLE
Use match to sync OS X "Developer ID Application" certificate?

### ISSUE THREAD

**Issue by bgerstle** [fastlane/fastlane#4252]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Is it possible to manage "Developer ID" certificates for OS X applications with match?  Seems like there are a couple things potentially complicating this:

- Under OS X section of the account
- Not tied to a bundle identifier or provisioning profile
- Conventionally created [via Xcode](https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html#//apple_ref/doc/uid/TP40012582-CH31-SW6)

**Comment by vpolouchkine** [comment]
I don't believe it's possible.

**Comment by TKBurner** [comment]
@bgerstle I'm going to mark this as a feature request for our team to review. Thanks!
