### ISSUE TITLE
Lane alias or Hidden lanes

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/fastlane#4253]
I want to rename a lane, but create an alias for the old name so CI keeps going without creating a failure on this change.

Some way to define lane aliases would need to be added, or a variant of the existing `private_lane` could be made.

We have `private_lane`s, but this makes lanes only callable from other lanes.
I want to hide a lane from commands like `lanes`, `list`, and `docs`, but still be able to call it if you know the name. 

---

Sorry I don't know how to label my own issue

**Comment by KrauseFx** [comment]
Sorry, that's currently not possible and not something I plan on implementing, as it's a really advanced feature.
