### ISSUE TITLE
Newsstand App

### ISSUE THREAD

**Issue by elhachmi-walid** [fastlane/fastlane#4256]
i would like to use Fastlane tools to add Newsstand app in my app store and issues to this my Newsstand app. How can i do it ?

**Comment by vpolouchkine** [comment]
I believe a vanilla fastlane installation would work: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Guide.md

**Comment by elhachmi-walid** [comment]
Thanks for your answer. but i didn't find how to submit Newsstand app category or how to add issues in my newsstand app in itunes connect automatically. can you help me to do it?

**Comment by TKBurner** [comment]
Hi @elhachmi-walid! Thanks for following up. Is this not set in your metadata? Can you give me the output of when you run 'deliver submit_build latest'? Thanks 👍
