### ISSUE TITLE
Match: Configure repository branch

### ISSUE THREAD

**Issue by adri** [fastlane/fastlane#4258]
Would it be advisable to not create a new repository when using `match` but reusing an existing repository? One where the app is in for example?

If that would be possible, I think the [branch should be configurable](https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/match/lib/match/git_helper.rb#L60) so that a branch like `certificates` can be passed in.

**Comment by vpolouchkine** [comment]
We recommend creating a separate repo.
