### ISSUE TITLE
Spaceship is unable to add_external_tester!

### ISSUE THREAD

**Issue by chappejw** [fastlane/fastlane#4265]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`Spaceship::Tunes.login(userName, userPassword)`
After successfully logging in with spaceship, we find the app we want to work with
`app = Spaceship::Tunes::Application.find("com.company.appname")`

Invite an external tester to the build and this method fails with the message below.
`app.add_external_tester!(email: "user@domain.com", first_name: "FirstName", last_name: "LlastName")`

##### Complete output when running fastlane, including the stack trace and command used

```
[11:46:01]: [user@domain.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"}

[!] Some operations failed: ["user@domain.com"]
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# not using a Fastfile, this is happening in Spaceship using the code above
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.81.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no, I'm using #!/usr/bin/ruby

**Comment by vpolouchkine** [comment]
What's the role of the user you're logging in with?

**Comment by chappejw** [comment]
The user's role is Technical

**Comment by vpolouchkine** [comment]
What happens if you login as an Admin?

**Comment by chappejw** [comment]
I will check and post back here.

**Comment by TKBurner** [comment]
Thanks @chappejw! We look forward to hearing back  👍

**Comment by chappejw** [comment]
Ok, I am confirming that using the account with App Manager role the Pilot tool and Spaceship ( which I believe is used by Pilot ) are able to invite external testers. Admin role also works.

**Comment by vpolouchkine** [comment]
Glad to hear you're up and running.
