### ISSUE TITLE
New Action: JIRA Comments

### ISSUE THREAD

**Issue by jstart** [fastlane/fastlane#4269]
Simple action to allow adding a comment to JIRA tickets. We use this to attach build URLs, test reports, etc. to specific bug tickets.
https://github.com/fastlane/fastlane/pull/4268

**Comment by TKBurner** [comment]
@jstart Thanks for reaching out. This is an interesting idea. We are going to take a look at it as a feature request and follow up on this thread if we have any updates. Hope that you have a wonderful week! 👍

**Comment by SiarheiFedartsou** [comment]
@jstart Hi! I have a problem with this action. I've installed `jira` gem and I have a crash during jira action work:
```/Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira/cli.rb:28: warning: else without rescue is useless
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': /Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira/cli.rb:24: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
/Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira/cli.rb:65: syntax error, unexpected keyword_end, expecting end-of-input
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/lib/jira.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/jira-0.1.0/bin/jira:6:in `<top (required)>'
	from /usr/local/bin/jira:23:in `load'
	from /usr/local/bin/jira:23:in `<main>'```

Lane code(most totally the same as in example) is:
```ruby
jira(
  url: "XXX",
  username: "XXX",
  password: "XXX",
  ticket_id: "XXX-NNN",
  comment_text: "Text to post as a comment"
)
```

**Comment by jstart** [comment]
@SiarheiFedartsou ya this is a bit of a problem, there are two ruby gems named jira.  I believe this is the one you should have installed instead https://github.com/sumoheavy/jira-ruby

**Comment by SiarheiFedartsou** [comment]
@jstart Thanks! I've already found out it. I've made a PR to verify correct gem (jira-ruby). https://github.com/fastlane/fastlane/pull/4719

**Comment by TKBurner** [comment]
@jstart Thanks for the PR. We'll review it and will update you. Thanks!

**Comment by jcampbell05** [comment]
@TKBurner  This should probably be a plugin.

**Comment by jcampbell05** [comment]
@TKBurner  this should be closed :)

**Comment by KrauseFx** [comment]
Thanks @jcampbell05 👍
