### ISSUE TITLE
Invalid provisional profile error after using `ipa build` and `deliver`.

### ISSUE THREAD

**Issue by Srthk** [fastlane/fastlane#427]
I've been using the fastlane tool provided at: https://fastlane.tools to generate provisional profiles and submit apps to iTunes connect.

Sequence of commands:

`$fastlane init`
`$cert`
`$produce`
`$sigh`

Following this the provisional profile corresponding to distribution on App store is automatically downloaded. After which the deliver command is executed and as per the guide this statement was added in the deliverfile -

`ipa do`
      `system("ipa build --verbose")` 
    `  "./AppName.ipa" ` 
`end`

It successfully generates the `.ipa` file but fails to submit the app to iTunes connect. The following error is generated -

>[15:57:54]: [Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.razeware.ScaryBugsZo [Payload/ScaryBugsZo.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."

Although on using the same provisional profile generate by fastlane I'm able to upload the build using xCode. My final goal is to automate submission of multiple apps on iTunes connect from a single apple ID. For this, sigh is successfully generating provisional profiles. I need to a way to automate uploading the build either by using deliver or some other method.

I believe the error is in using `ipa build` because it doesn't receive the certificate generated by `sigh`. Because manually generating a .ipa build from xCode by installing `sigh` provisional profile is working with `deliver`.

**Comment by KrauseFx** [comment]
Check out this guide on code signing: https://github.com/KrauseFx/fastlane/blob/master/docs/CodeSigning.md

You'll need to pass the provisioning profile using environment variables to your Xcode project file

**Comment by Srthk** [comment]
On using the method in `codesigning.md`, i added the following in the `fastfile`, 

```sigh

# use the UDID of the newly created provisioning profile
ENV["PROFILE_UDID"] = Actions.lane_context[Actions::SharedValues::SIGH_UDID]

ipa(scheme: "Release")
```
But following error is generated -

![screen shot 2015-07-20 at 6 10 30 pm](https://cloud.githubusercontent.com/assets/7152922/8775946/c0631178-2f0a-11e5-936d-ae54b4ac5311.png)

Basically, there's an issue between `sigh` and `ipa` (building the project) and `deliver`.

**Comment by KrauseFx** [comment]
@Srthk Please manually run the command that is shown to you and share the full output :+1:

**Comment by Srthk** [comment]
How can I manually run such a command on shell-
`ENV["PROFILE_UDID"] = Actions.lane_context[Actions::SharedValues::SIGH_UDID]`

I added them in the fast file as suggested in the guide and it gave the error shown in the image in my previous comment.

**Comment by Srthk** [comment]
I think I might have resolved the issue. It worked when using `ipa(configuration: "Release")` instead of `ipa(scheme: "Release")`. Retesting it for a different app just to be sure.

**Comment by KrauseFx** [comment]
Okay, let me know how it works out.

**Comment by Srthk** [comment]
The above worked when uploading an updated build for an app but failed when uploading a brand new app on iTunes connect. The same error is coming again on using the Environment variable method. Is there a lane example of using code signing to generate `.ipa` file from scratch.

Error image: https://cloud.githubusercontent.com/assets/7152922/8775946/c0631178-2f0a-11e5-936d-ae54b4ac5311.png

**Comment by JaviSoto** [comment]
Hi @Srthk!
Is this still an issue? I'm sure you've seen the new awesome `gym` tool. Did you give that a try? Is it working better for you?
Thanks!

**Comment by asfalcone** [comment]
Going to close this issue since it has been open for a while without comment.
