### ISSUE TITLE
PLEASE HELP!!! So as of Aprile 18, 2016 I am getting a timeout now in the Spaceship.provisioning_profile.all.each do |profile|

### ISSUE THREAD

**Issue by sfransen** [fastlane/fastlane#4270]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
 Can someone please guide me how to all Add Devices to all Provision Profiles  without calling this command as it doesn't work.
 I can run my code on a small license and I have no problem.
PLEASE HELP!!!!!!
Spaceship.provisioning_profile.all.each do |profile|
 is causing a timeout.
 I have about 1000 provision Profiles and 5000 Devices. in each and  I am getting a timeout 
I  even changed the 
 def with_retry(tries = 3, &_block)
 to 
    def with_retry(tries = 10, &_block)
 it now just take longer to timeout. I am at almost 1 hour for it to fail.

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': [!] Net::ReadTimeout (Faraday::TimeoutError)

##### Complete output when running fastlane, including the stack trace and command used
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill': [!] Net::ReadTimeout (Faraday::TimeoutError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1406:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1403:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1376:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1369:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.9.1/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.0/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.0/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.0/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.0/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.0/lib/spaceship/portal/portal_client.rb:317:in `provisioning_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.0/lib/spaceship/portal/provisioning_profile.rb:246:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.6.1/lib/sigh/download_all.rb:24:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.6.1/lib/sigh/manager.rb:34:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.6.1/bin/sigh:45:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.6.1/bin/sigh:93:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.6.1/bin/sigh:111:in `<top (required)>'
	from /usr/bin/sigh:23:in `load'
	from /usr/bin/sigh:23:in `<main>'

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
@sfransen Great to hear from you! Sorry to hear that you are running into this issue. Can you share the full output including the commands you entered? It'll help our team identify what's causing this. If you can provide exact repro steps, we'll be able to prioritize this better 👍

**Comment by sfransen** [comment]
any command all fails with time
if you look at my branch of the code.
 you will see you are doing the Spaceship.provisioning_profile.all.each do |profile| way too many times.
  
my way is better of not doing the Spaceship.provisioning_profile.all.each do |profile| for each provision profile you download . but still if timing out now. As mine license size has gotten to large with devices and provison profiles

 I have a large account 5000 devices and 863 provision profiles  236 AppID
 almost all the devices are in each provision profile ( Note they all would be in each provision profile but my code is no longer working )
here is fastest example
 clean OS 10.11.4
sudo gem install fastlane
sudo gem install pry
1. spaceship --username foo@xxxx.com
2. filtered_profiles = Spaceship.provisioning_profile.app_store.find_by_bundle_id("com.foo.foo")
the results is this after 25 minutes
Faraday::TimeoutError: Net::ReadTimeout
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:158:in `rescue in rbuf_fill'

 note here is my branch of the your code that handle large account better
https://github.com/sfransen/fastlane
any call that make this call will timeout.
Spaceship.provisioning_profile.

I could do a debug session with someone if needed to if someone could help. I am in San Jose, Ca

I am really blocked
 Thanks
Steven Fransen

**Comment by sfransen** [comment]
# Logfile created on 2016-04-21 10:59:18 -0700 by logger.rb/41954
[10:59:18]: >> POST:  
[10:59:18]: >> GET: https://itunesconnect.apple.com/itc/static-resources/controllers/login_cntrl.js 
[10:59:18]: << GET: https://itunesconnect.apple.com/itc/static-resources/controllers/login_cntrl.js: 'use strict';

define(['app'], function (staticApp) {
    var loginController = function($scope, $rootScope, $location, $stateParams, staticServices) {
        
        $scope.parentScopeLoaded = false;
        $scope.pageLoaded = false;
        $scope.showLearnMorePanel = true;
        $scope.normalLogin = true;
        $scope.appleMusicLogin = false;
        $scope.podcastLogin = false;
        $scope.errorKey = false;
        window.scope = $scope;

        $scope.$parent.$watch('parentScopeLoaded',function(val) {
            if (val) {
                $rootScope.currentPage = 'login';
                $scope.parentScopeLoaded = true;
                $scope.setupDSiFrame();
                $scope.setisReady();
            }
        });

        $scope.setisReady = function() {
            if ($scope.parentScopeLoaded && $scope.pageLoaded) {
                $rootScope.isReady = true;
            } else {
                $rootScope.isReady = false;
            }
        }

        $scope.checkForLocalStorage = function() {
            var mod = 'itc';
            try {
                localStorage.setItem(mod, mod);
                localStorage.removeItem(mod);
                return true;
            } catch(e) {
                return false;
            }
        }

        $scope.checkLoginType = function() {

            // 6 = artist
            // if ($stateParams.view == '6' || ($scope.localStorageEnabled && localStorage.getItem('itcLoginCt') == '6')) {
            if ($stateParams.view == '6') {
                $scope.normalLogin = false;
                $scope.appleMusicLogin = true;
                $scope.podcastLogin = false;
                $rootScope.loginType = 'artist';
            }
            // 5 = podcast
            // else if ($stateParams.view == '5' || ($scope.localStorageEnabled && localStorage.getItem('itcLoginCt') == '5')) {
            else if ($stateParams.view == '5') {
                $scope.normalLogin = false;
                $scope.appleMusicLogin = false;
                $scope.podcastLogin = true;
                $rootScope.loginType = 'podcast';
            }
            // 1 = normal itc
            else if ($stateParams.view == '1') {
                $scope.normalLogin = true;
                $scope.appleMusicLogin = false;
                $scope.podcastLogin = false;
            }
            
            $rootScope.loginType = $rootScope.loginType;
        }

        $scope.checkForErrors = function() {
            if (!$stateParams.errorKey) return;
            $scope.errorKey = $stateParams.errorKey;
        }

        $scope.getStorage = function() {
            if (!$scope.localStorageEnabled) return;
            if (localStorage.getItem('itcLoginVisitedBefore') == 'true') {
                $scope.showLearnMorePanel = false;  
                $rootScope.darkFooter = false;
            }
            else {
                $rootScope.darkFooter = true;
            }
        }

        $scope.setStorage = function() {
            if (!$scope.localStorageEnabled) return;
            localStorage.setItem('itcLoginVisitedBefore','true');
            // if ($stateParams && $stateParams.view && localStorage.getItem('itcLoginCt') == null) localStorage.setItem('itcLoginCt', $stateParams.view);
        }

        var getEnv = function(host) {
            var seperator = '-';
            if (host.indexOf(seperator) < 0) return null;
            else return host.split(seperator)[0];
        }

        var getSubdomain = function(host) {
            var seperator = '.';
            if (host.indexOf(seperator) < 0) return null;
            else return host.split(seperator)[0];
        }

        $scope.setupDSiFrame = function() {
            var itcProdUrl = 'itunesconnect.apple.com';
            var itcServiceUrl = 'https://idmsa.apple.com/appleauth';
            var itcServiceUrlStable = 'https://idmsauth-stable.corp.apple.com/appleauth';
            var itcServiceUrlUat = 'https://idmsauth-uat.corp.apple.com/appleauth';
            var itcServiceKey = '22d448248055bab0dc197c6271d738c3'; // for itunesconnect.apple.com
            var itcServiceKeyDevItms8 = 'dd9cea41f269008e7f1403a24cfbafe2';
            var currentHost = $location.host();

            if (!$stateParams.path || ($stateParams.path && !$stateParams.path.match('^/') && !$stateParams.path.match('^%2F'))) { 
                $stateParams.path = '/WebObjects/iTunesConnect.woa/?';
            }
            var itcAppUrl =  $location.protocol() + "://" + currentHost + $stateParams.path;
            if ($rootScope.loginType) itcAppUrl = itcAppUrl + 'ct=' + $rootScope.loginType;

            var environment = getEnv(currentHost);
            if (environment != null) {
                var envNum = environment.match(/\d+/); 
                if (envNum != null) {
                    envNum = envNum[0];
                    switch (envNum) {
                        case '5':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = 'e8d70ccc118e009722ffde066269dcfd';
                            break;
                        case '6':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '70a6ee3acccc2f883bf9c45ea3ed71c3';
                            break;
                        case '7':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '0c4530ccf7a70bbcd7b8f4734482b65a';
                            break;
                        case '8':
                            itcServiceUrl = itcServiceUrlStable;
                            itcServiceKey = itcServiceKeyDevItms8;
                            break;
                        case '9':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '9249bf5e254fc633460e3cbfd8171daf';
                            break;
                        case '11':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '076c502588fa5f0a4b2424dbe98ac943d451d5859488a40904a56b12141dda33';
                            break;    
                    }
                }
                else if (environment == 'origin') itcServiceKey = '0bcc3499e16ee45d885d118869dbad57';
            }

            var loginHeaderText = $scope.l10n.interpolate('ITC.Login.iTunesConnect');
            if ($rootScope.loginType == 'artist') loginHeaderText = $scope.l10n.interpolate('ITC.Login.AppleMusic');
            else if ($rootScope.loginType == 'podcast') loginHeaderText = $scope.l10n.interpolate('ITC.Login.Podcast');

            var initOptions = {
                serviceKey: itcServiceKey,
                serviceURL: itcServiceUrl,
                containerId: 'idms-auth-container',
                signInLabel: loginHeaderText,
                theme: 'lite',
                features: {
                    rememberMe: true
                },
                callbacks: {
                    onAuthSuccess: function (result) {
                        window.location = itcAppUrl;
                    }, 
                    onAuthFailure: function (result) {
                        console.log('Auth failure.', result);
                    },
                    onPasswordAuthDone: function (isSuccess) {
                        if (!isSuccess) {
                            $scope.$apply(function(){
                                $scope.errorKey = null;
                            })
                        }
                    }
                }
            };

            if (!envNum && environment != 'origin' && currentHost != itcProdUrl) {
                initOptions.devAppDomain = $location.protocol() + "://" + currentHost;;
                initOptions.serviceKey = itcServiceKeyDevItms8;
                initOptions.serviceURL = itcServiceUrlStable;
            }

            window.AppleID.service.auth.init(initOptions);
        }

        $scope.loadEnvInfo = function() {
            staticServices.loadEnvironmentInfo().then(function(data) {
                $scope.environmentInfo = data.data;
            });
        }

        $scope.loadPage = function() {
            $scope.localStorageEnabled = $scope.checkForLocalStorage();
            $scope.checkForErrors();
            $scope.getStorage();
            $scope.checkLoginType();
            $scope.pageLoaded = true;
            $scope.setisReady();
            $scope.setStorage();
            $scope.loadEnvInfo();
        }

        // $scope.setisReady();
        $scope.loadPage();

    }
    staticApp.register.controller('loginController', ['$scope', '$rootScope', '$location', '$stateParams', 'staticServices', loginController]);
});

[10:59:19]: Auth lost

**Comment by sfransen** [comment]
# Logfile created on 2016-04-21 12:45:57 -0700 by logger.rb/41954
[12:45:57]: >> POST:  
[12:45:57]: >> GET: https://itunesconnect.apple.com/itc/static-resources/controllers/login_cntrl.js 
[12:45:57]: << GET: https://itunesconnect.apple.com/itc/static-resources/controllers/login_cntrl.js: 'use strict';

define(['app'], function (staticApp) {
    var loginController = function($scope, $rootScope, $location, $stateParams, staticServices) {
        
        $scope.parentScopeLoaded = false;
        $scope.pageLoaded = false;
        $scope.showLearnMorePanel = true;
        $scope.normalLogin = true;
        $scope.appleMusicLogin = false;
        $scope.podcastLogin = false;
        $scope.errorKey = false;
        window.scope = $scope;

        $scope.$parent.$watch('parentScopeLoaded',function(val) {
            if (val) {
                $rootScope.currentPage = 'login';
                $scope.parentScopeLoaded = true;
                $scope.setupDSiFrame();
                $scope.setisReady();
            }
        });

        $scope.setisReady = function() {
            if ($scope.parentScopeLoaded && $scope.pageLoaded) {
                $rootScope.isReady = true;
            } else {
                $rootScope.isReady = false;
            }
        }

        $scope.checkForLocalStorage = function() {
            var mod = 'itc';
            try {
                localStorage.setItem(mod, mod);
                localStorage.removeItem(mod);
                return true;
            } catch(e) {
                return false;
            }
        }

        $scope.checkLoginType = function() {

            // 6 = artist
            // if ($stateParams.view == '6' || ($scope.localStorageEnabled && localStorage.getItem('itcLoginCt') == '6')) {
            if ($stateParams.view == '6') {
                $scope.normalLogin = false;
                $scope.appleMusicLogin = true;
                $scope.podcastLogin = false;
                $rootScope.loginType = 'artist';
            }
            // 5 = podcast
            // else if ($stateParams.view == '5' || ($scope.localStorageEnabled && localStorage.getItem('itcLoginCt') == '5')) {
            else if ($stateParams.view == '5') {
                $scope.normalLogin = false;
                $scope.appleMusicLogin = false;
                $scope.podcastLogin = true;
                $rootScope.loginType = 'podcast';
            }
            // 1 = normal itc
            else if ($stateParams.view == '1') {
                $scope.normalLogin = true;
                $scope.appleMusicLogin = false;
                $scope.podcastLogin = false;
            }
            
            $rootScope.loginType = $rootScope.loginType;
        }

        $scope.checkForErrors = function() {
            if (!$stateParams.errorKey) return;
            $scope.errorKey = $stateParams.errorKey;
        }

        $scope.getStorage = function() {
            if (!$scope.localStorageEnabled) return;
            if (localStorage.getItem('itcLoginVisitedBefore') == 'true') {
                $scope.showLearnMorePanel = false;  
                $rootScope.darkFooter = false;
            }
            else {
                $rootScope.darkFooter = true;
            }
        }

        $scope.setStorage = function() {
            if (!$scope.localStorageEnabled) return;
            localStorage.setItem('itcLoginVisitedBefore','true');
            // if ($stateParams && $stateParams.view && localStorage.getItem('itcLoginCt') == null) localStorage.setItem('itcLoginCt', $stateParams.view);
        }

        var getEnv = function(host) {
            var seperator = '-';
            if (host.indexOf(seperator) < 0) return null;
            else return host.split(seperator)[0];
        }

        var getSubdomain = function(host) {
            var seperator = '.';
            if (host.indexOf(seperator) < 0) return null;
            else return host.split(seperator)[0];
        }

        $scope.setupDSiFrame = function() {
            var itcProdUrl = 'itunesconnect.apple.com';
            var itcServiceUrl = 'https://idmsa.apple.com/appleauth';
            var itcServiceUrlStable = 'https://idmsauth-stable.corp.apple.com/appleauth';
            var itcServiceUrlUat = 'https://idmsauth-uat.corp.apple.com/appleauth';
            var itcServiceKey = '22d448248055bab0dc197c6271d738c3'; // for itunesconnect.apple.com
            var itcServiceKeyDevItms8 = 'dd9cea41f269008e7f1403a24cfbafe2';
            var currentHost = $location.host();

            if (!$stateParams.path || ($stateParams.path && !$stateParams.path.match('^/') && !$stateParams.path.match('^%2F'))) { 
                $stateParams.path = '/WebObjects/iTunesConnect.woa/?';
            }
            var itcAppUrl =  $location.protocol() + "://" + currentHost + $stateParams.path;
            if ($rootScope.loginType) itcAppUrl = itcAppUrl + 'ct=' + $rootScope.loginType;

            var environment = getEnv(currentHost);
            if (environment != null) {
                var envNum = environment.match(/\d+/); 
                if (envNum != null) {
                    envNum = envNum[0];
                    switch (envNum) {
                        case '5':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = 'e8d70ccc118e009722ffde066269dcfd';
                            break;
                        case '6':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '70a6ee3acccc2f883bf9c45ea3ed71c3';
                            break;
                        case '7':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '0c4530ccf7a70bbcd7b8f4734482b65a';
                            break;
                        case '8':
                            itcServiceUrl = itcServiceUrlStable;
                            itcServiceKey = itcServiceKeyDevItms8;
                            break;
                        case '9':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '9249bf5e254fc633460e3cbfd8171daf';
                            break;
                        case '11':
                            itcServiceUrl = itcServiceUrlUat;
                            itcServiceKey = '076c502588fa5f0a4b2424dbe98ac943d451d5859488a40904a56b12141dda33';
                            break;    
                    }
                }
                else if (environment == 'origin') itcServiceKey = '0bcc3499e16ee45d885d118869dbad57';
            }

            var loginHeaderText = $scope.l10n.interpolate('ITC.Login.iTunesConnect');
            if ($rootScope.loginType == 'artist') loginHeaderText = $scope.l10n.interpolate('ITC.Login.AppleMusic');
            else if ($rootScope.loginType == 'podcast') loginHeaderText = $scope.l10n.interpolate('ITC.Login.Podcast');

            var initOptions = {
                serviceKey: itcServiceKey,
                serviceURL: itcServiceUrl,
                containerId: 'idms-auth-container',
                signInLabel: loginHeaderText,
                theme: 'lite',
                features: {
                    rememberMe: true
                },
                callbacks: {
                    onAuthSuccess: function (result) {
                        window.location = itcAppUrl;
                    }, 
                    onAuthFailure: function (result) {
                        console.log('Auth failure.', result);
                    },
                    onPasswordAuthDone: function (isSuccess) {
                        if (!isSuccess) {
                            $scope.$apply(function(){
                                $scope.errorKey = null;
                            })
                        }
                    }
                }
            };

            if (!envNum && environment != 'origin' && currentHost != itcProdUrl) {
                initOptions.devAppDomain = $location.protocol() + "://" + currentHost;;
                initOptions.serviceKey = itcServiceKeyDevItms8;
                initOptions.serviceURL = itcServiceUrlStable;
            }

            window.AppleID.service.auth.init(initOptions);
        }

        $scope.loadEnvInfo = function() {
            staticServices.loadEnvironmentInfo().then(function(data) {
                $scope.environmentInfo = data.data;
            });
        }

        $scope.loadPage = function() {
            $scope.localStorageEnabled = $scope.checkForLocalStorage();
            $scope.checkForErrors();
            $scope.getStorage();
            $scope.checkLoginType();
            $scope.pageLoaded = true;
            $scope.setisReady();
            $scope.setStorage();
            $scope.loadEnvInfo();
        }

        // $scope.setisReady();
        $scope.loadPage();

    }
    staticApp.register.controller('loginController', ['$scope', '$rootScope', '$location', '$stateParams', 'staticServices', loginController]);
});

[12:45:57]: << POST: : {}
[12:45:57]: >> GET: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa/route?noext 
[12:45:58]: << GET: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/wa/route?noext: 
[12:45:58]: >> GET: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa 
[12:45:58]: << GET: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa: 
[12:45:58]: >> POST: https://developerservices2.apple.com/services/QH65B2/listTeams.action 
[12:45:58]: << POST: https://developerservices2.apple.com/services/QH65B2/listTeams.action: {"teams"=>[{"status"=>"active", "name"=>"foo, Inc.", "teamId"=>"444444", "type"=>"Company/Organization", "extendedTeamAttributes"=>{}, "teamAgent"=>{"teamMemberId"=>"4444444", "personId"=>444444, "firstName"=>"4444", "lastName"=>"4444", "email"=>"foo@foo.com", "developerStatus"=>"active"}, "memberships"=>[{"membershipId"=>"44444444", "membershipProductId"=>"ds1", "name"=>"iOS Developer Program", "status"=>"active", "inIosDeviceResetWindow"=>false, "inRenewalWindow"=>false, "dateStart"=>#<DateTime: 2016-03-10T07:59:00+00:00 ((2457458j,28740s,0n),+0s,2299161j)>, "dateExpire"=>#<DateTime: 2017-02-10T23:59:00+00:00 ((2457795j,86340s,0n),+0s,2299161j)>, "platform"=>"ios"}, {"membershipId"=>"444444", "membershipProductId"=>"mc6", "name"=>"Mac Developer Program", "status"=>"active", "inIosDeviceResetWindow"=>false, "inRenewalWindow"=>false, "dateStart"=>#<DateTime: 2016-03-10T07:59:00+00:00 ((2457458j,28740s,0n),+0s,2299161j)>, "dateExpire"=>#<DateTime: 2017-02-10T23:59:00+00:00 ((2457795j,86340s,0n),+0s,2299161j)>, "platform"=>"ios"}, {"membershipId"=>"444444444", "membershipProductId"=>"ps8", "name"=>"Safari Developer Program", "status"=>"active", "inIosDeviceResetWindow"=>false, "inRenewalWindow"=>false, "dateStart"=>#<DateTime: 2016-03-10T07:59:00+00:00 ((2457458j,28740s,0n),+0s,2299161j)>, "dateExpire"=>#<DateTime: 2017-02-10T23:59:00+00:00 ((2457795j,86340s,0n),+0s,2299161j)>, "platform"=>"ios"}], "currentTeamMember"=>{"teamMemberId"=>"4444444", "personId"=>444444444, "firstName"=>"foo", "lastName"=>"foo", "developerStatus"=>"active", "privileges"=>{}, "roles"=>["TEAM_ADMIN", "MAC_PROGRAM_TEAM_ADMIN"]}}], "creationTimestamp"=>"2016-04-21T19:45:58Z", "resultCode"=>0, "userLocale"=>"en_US", "protocolVersion"=>"QH65B2", "requestUrl"=>"https://developerservices2.apple.com:443/services/444444/listTeams.action", "responseId"=>"0c259a1d-cbe7-476c-ad65-89b9106b23b8"}
[12:45:58]: >> POST:  
[12:50:58]: Timeout received: 'Net::ReadTimeout'.  Retrying after 3 seconds (remaining: 4)...
[12:56:02]: Timeout received: 'Net::ReadTimeout'.  Retrying after 3 seconds (remaining: 3)...
[13:01:05]: Timeout received: 'Net::ReadTimeout'.  Retrying after 3 seconds (remaining: 2)...
[13:06:08]: Timeout received: 'Net::ReadTimeout'.  Retrying after 3 seconds (remaining: 1)...

**Comment by sfransen** [comment]
I hope this helps.
