### ISSUE TITLE
My team 'match nuke's each other's certificates every few days to resolve errors. What are we doing wrong?

### ISSUE THREAD

**Issue by sirhans** [fastlane/fastlane#4271]
### Issue Description

**Here's what I'm doing:**
   I have five apps using match.  All five apps are sharing profiles and certs on a single git repo. Each one has its own Matchfile in its XCode project folder.  When I want to make sure the certs are up to date, I cd to the app project folder and type 'match development'.  I have a team of five people, all sharing that same git repo for certs and profiles.

**Here's the problem:**
Every few days I get a warning from xcode saying that the certificate I am using for an app is expired or has been revoked.  I cd to the project directory and type "match development" and match tells me that the certificate in my repository is not available on the developer portal.  (Set the output copied below.)  I run "match nuke" and all is well for a few days and then I get the error again.  I think this happens because other people in my team are also getting the same error and also solving it by nuking the certificates, so we are going around in circles nuking each other's certs every few days.

So I feel like we are missing something about the way match is supposed to be used.  Am I not supposed to put the certs for all apps into a single git repo?  Or do I need to do something different when managing 5 apps that I don't have to do when it's just one?

##### Complete output when running fastlane, including the stack trace and command used

```
Hanss-MacBook-Pro:MFCCDemo hans$ match development

+-----------------------+----------------------------------------------------------+
|                             Summary for match 0.4.0                              |
+-----------------------+----------------------------------------------------------+
| git_url               | http://sirhans@fpt.com:7990/scm/PROF/profiles.git |
| type                  | development                                              |
| app_identifier        | edu.sutd.MFCCDemo                                        |
| username              | sirhans@fpt.com                                |
| keychain_name         | login.keychain                                           |
| readonly              | false                                                    |
| verbose               | false                                                    |
| force                 | false                                                    |
| shallow_clone         | false                                                    |
| force_for_new_devices | false                                                    |
| skip_docs             | false                                                    |
+-----------------------+----------------------------------------------------------+

[16:04:17]: Cloning remote git repo...
[16:04:22]: 🔓  Successfully decrypted certificates repo
[16:04:22]: Verifying that the certificate and profile are still valid on the Dev Portal...
[16:04:28]: Installing certificate...
[16:04:30]: Certificate 'JUVNSL6MRP' (stored in your git repo) is not available on the Developer Portal
[16:04:30]: for the user sirhans@fpt.com
[16:04:30]: Make sure to use the same user and team every time you run 'match' for this
[16:04:30]: Git repository. This might be caused by revoking the certificate on the Dev Portal
[16:04:30]: 🔒  Successfully encrypted certificates repo

[!] To reset the certificates of your Apple account, you can use the `match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Matchfile:
```ruby
git_url "http://sirhans@fpt.com:7990/scm/PROF/profiles.git"

type "development" # The default type, can be: appstore, adhoc or development

app_identifier "edu.sutd.MFCCDemo"
username "sirhans@fpt.com" # Your Apple Developer Portal username
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.66.0; match 0.4.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by KrauseFx** [comment]
Does anybody in your team still click the `Fix Issue` button in Xcode? You could try changing the credentials and only accessing the Dev Portal using `match`.

**Comment by sirhans** [comment]
Felix, you are right.  One member of the team was using that Fix Issue button.  Thank you.  Match is a great tool.  I was waiting four years for apple to make something like it.

**Comment by neonichu** [comment]
Always click "Fix Issue" 👍

**Comment by KrauseFx** [comment]
To never run into this in the future, I can recommend using [FixCode](https://github.com/neonichu/FixCode). 
In particular, add this to your `Fastfile`
```ruby
before_all do
  install_xcode_plugin(
    url: "https://github.com/fastlane/FixCode/releases/download/0.4.0/FixCode.xcplugin.zip"
  )
end
```
so that never happens again 👍

**Comment by sirhans** [comment]
Thank you.
