### ISSUE TITLE
Doc path is wrong for CodeSigning.md and Platforms.md

### ISSUE THREAD

**Issue by jschoolcraft** [fastlane/fastlane#4277]
Needs a /fastlane/ in the path.  PR #4235

**Comment by TKBurner** [comment]
@jschoolcraft Thanks for being part of our community and keeping us updated! Hope that you have a wonderful weekend coming up 👍 Going to close this out. Let me know if you have a new PR.

**Comment by TKBurner** [comment]
Hey @jschoolcraft! We'd love to see you contribute to our repo, let me know if you still need any help making your docs commit 👍 ❤️

**Comment by KrauseFx** [comment]
This can be closed, right?
