### ISSUE TITLE
sigh is using old app id

### ISSUE THREAD

**Issue by henriklundstedt** [fastlane/fastlane#4278]
### Issue Description

I'm running fastlane on a Jenkins build server. The intial setup was made with an app id which is no longer used. I've deleted it from the App Dev Center and created a new one. I've set the new app id as "app_identifier" in Appfile, and I've have even tried to pass it as a parameter to sigh in my Fastfile, but still sigh picks upp the old app id:

+-------------------------------------+----------------------------+
|                      [32mSummary for sigh 1.6.1[0m                      |
+-------------------------------------+----------------------------+
| adhoc                               | true                       |
| skip_install                        | false                      |
| development                         | false                      |
| force                               | false                      |
| app_identifier                      | old_app_id |
| username                            | my_username  |
| team_id                             | 929N68FKLV                 |
| ignore_profiles_with_different_name | false                      |
| cert_id                             | BF38HPR8YL                 |
| skip_fetch_profiles                 | false                      |
| skip_certificate_verification       | false                      |
+-------------------------------------+----------------------------+

**Comment by TKBurner** [comment]
Hi @henriklundstedt! Thanks for reaching out. You should be able to set the App identifier manually as a parameter. Can you try that? Thanks!

**Comment by asfalcone** [comment]
@henriklundstedt Were you able to get this working with @TKBurner's suggestion? Thanks.

**Comment by henriklundstedt** [comment]
After deleting the jenkins build and creating a new one, the new app id was picked up.

**Comment by TKBurner** [comment]
@henriklundstedt Nice! Glad to hear you got up and running 👍
