### ISSUE TITLE
Lane examples.

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#428]
Hi. I would like to purpose to create separate page with useful lane examples. It becomes more relevant with latest update, when you can use one lane in other!

For example:

Add tag according `xcodeproj` file:
```
lane :tag do
    fetched_tag = sh("cd .. && agvtool what-marketing-version -terse1 | tr -d '\n'")
    add_git_tag(tag: fetched_tag)
end
```

Or bumping:

```
  desc "Bump patch"
  lane :bump do
    increment_build_number
    increment_version_number(bump_type:"patch")
    commit_version_bump
  end

  desc "Bump minor"
  lane :bump_minor do
    increment_build_number
    increment_version_number(bump_type:"minor")
    commit_version_bump
  end

  desc "Bump major"
  lane :bump_major do
    increment_build_number
    increment_version_number(bump_type:"major")
    commit_version_bump
  end
```

**Comment by KrauseFx** [comment]
Nice idea. Do you know about https://github.com/fastlane/examples already?

**Comment by skywinder** [comment]
Yes, of course. The most useful examples for me there: 

https://github.com/fastlane/examples/blob/master/BeMyEyes/Deliverfile

So, you don't have to put CHANGELOG, KEYWORDS and so on manually. it's really nice!

But it's not convenient, that you have to collect different things from different resources.

p.s.
And there is also empty file, that doesn't make any sense:
https://github.com/fastlane/examples/blob/master/ProductHunt/Deliverfile

**Comment by KrauseFx** [comment]
Okay, so this could be either in the `fastlane` repo or the `examples` repo, right? 

Something like `Nice Fastfile snippets` that might be useful for you?

**Comment by skywinder** [comment]
Yep. I think it will be nice! 
Collection snippets in one place will be very useful for beginners!
