### ISSUE TITLE
[New feature] Provisioning profiles searching

### ISSUE THREAD

**Issue by MaximSt** [fastlane/fastlane#4280]
Hey guys. 
The account I am working with has almost 2000 provisioning profiles. So method `Spaceship::Portal::ProvisioningProfile.find_by_bundle_id` working so long for me.
The apple developers portal supports searching capabilities. In case of provisioning profiles, it is just one additional parameter in `Spaceship::PortalClient#provisioning_profiles`
something like 
```ruby
module Spaceship
  class PortalClient < Spaceship::Client
    def search_provisioning_profiles(query, mac: false)
      req = request(:post) do |r|
        r.url "https://developerservices2.apple.com/services/#{PROTOCOL_VERSION}/#{platform_slug(mac)}/listProvisioningProfiles.action"
        r.params = {
          teamId: team_id,
          includeInactiveProfiles: true,
          onlyCountLists: true,
          search: "name=#{query}&type=#{query}&appId=#{query}&status=#{query}"
        }
      end

      parse_response(req, 'provisioningProfiles')
    end
  end
  module Portal
    class ProvisioningProfile < PortalBase
      class << self
        def search_provisioning_profiles(query, mac: false)
          profiles = client.search_provisioning_profiles(query, mac: mac).map do |profile|
            self.factory(profile)
          end

          # filter out the profiles managed by xcode
          profiles.delete_if(&:managed_by_xcode?)

          return profiles if self == ProvisioningProfile

          # only return the profiles that match the class
          profiles.select do |profile|
            profile.class == self
          end
        end
      end
    end
  end
end
```

This works faster than `Spaceship::Portal::ProvisioningProfile.all` and takes less memory
What do you think?

**Comment by vitalyp** [comment]
Nice work, bro!

**Comment by TKBurner** [comment]
@MaximSt Thanks for sharing! We are going to take a look at this and see about integrating it directly into Spaceship. Hope that you have a wonderful week! 👍

**Comment by sfransen** [comment]
@MaximS how to I add this to my code so I can try it out I keep getting timeout errors right now.
I am hoping this will solve my problems. I have a huge account also.
thanks

**Comment by MaximSt** [comment]
@sfransen you can add cde above to initializer like spaceship.rb

**Comment by MaximSt** [comment]
Thank you @TKBurner

**Comment by tsafrir** [comment]
@MaximSt  I have the same situation as you do - this is great, thank you!
In the account that I manage, I have deleted tons of profiles managed by Xcode (with fastlane spaceship) and that speed up things. I also avoid configuring that account in Xcode so it won't create that managed profiles again.

**Comment by sfransen** [comment]
Problem is that I have hundreds of developers and I have no control over their system
I didn't have a change to test this yet
I hope to find time today to test this

Where do I place this code by the way
Thanks

**Comment by orff** [comment]
While search might be a better option, this change, to enable pagination on the profiles works for our team, we have > 1000 profiles and well and our devs are adding more all the time:

```Ruby
def provisioning_profiles(include_invalid_profiles=true, mac: false)
      @page_size = 200
      paging do |page_number|
        req = request(:post) do |r|
          r.url "https://developerservices2.apple.com/services/#{PROTOCOL_VERSION}/#{platform_slug(mac)}/listProvisio..."
          r.params = {
            teamId: team_id,
            includeInactiveProfiles: include_invalid_profiles,
            onlyCountLists: true,
            pageSize:page_size,
            pageNumber:page_number,
            sidx: "name",
            sort: "name=dasc"
          }
        end

      parse_response(req, 'provisioningProfiles')
    end
  end
```

**Comment by summera** [comment]
@MaximSt search still working for you? I started to run into 403 errors.
