### ISSUE TITLE
Enhancement: Option to skip unsupported frames

### ISSUE THREAD

**Issue by tternes** [fastlane/fastlane#4283]
**Enhancement:** Add an option to skip unsupported device frames (such as 3.5" devices).

The current behavior of `frameit` for unsupported device frames is to produce images that are clipped and potentially less desirable than plain screenshots, sans frame and title.

It would be helpful if `frameit` could be instructed to skip unsupported device frames (or just copy the plain files to "framed" variants for use with `deliver`.

**Comment by TKBurner** [comment]
@tternes Interesting idea! I'm going to mark this as a feature request so we can look it over as a team. Glad to have you using Fastlane. Hope you have a great day! 👍
