### ISSUE TITLE
[sigh] AppIdentifierPrefix entry not updated by resign command

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4287]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

While resigning `.ipa` file with `resign` command and underlying `resign.sh` bash script, the `AppIdnetifierPrefix` entry in the resigned app's `Info.plist` is not updated.

As a result, after resigning Enterprise build for App Store distribution, the `AppIdentifierPrefix` is not updated and App Store build contains Enterprise app ID prefix.

### Reproduction Steps

1. Use Enterprise distribution credentials to build `.ipa` file
  - Enterprise app identifier prefix: `12345678`
  - Enterprise team ID: `12345678`
2. The `Info.plist` of built `.ipa` has `ApplicationIdentifierPrefix` entry set to `12345678`
3. Resign enterprise `.ipa` using `sigh` for App Store distribution using new provisioning profile
  - App Store app identifier prefix in new profile: `ABCDEFGH`
  - App Store team ID in new profile: `ABCDEFGH`
4. Check `Info.plist` of resigned `.ipa`

Expected `ApplicationIdentifierPrefix` value: `ABCDEFGH`
Actual `ApplicationIdentifierPrefix` value: `12345678`

`resign.sh` did not update `ApplicationIdentifierPrefix` entry.
The script reads new `ApplicationIdentifierPrefix` from provisioning profile on line `363`, but never writes it back to the app `Info.plist`.

Just like `CFBundleIdentifier` and other keys, the `ApplicationIdentifierPrefix` has to be updated to new value.

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by TKBurner** [comment]
@mgrebenets Thanks for reaching out. Can you share the full reproduction steps? I want to send this over to the team as a bug, but we'll need exact repro steps to start work! Thanks! 👍

**Comment by mgrebenets** [comment]
@TKBurner OK, I'll try to come up with some sample project.
The original project where we observe this issue is something I can't share.

**Comment by mgrebenets** [comment]
@TKBurner I have added `Reproduction Steps` section to the issue description. It outlines the problem in details.

**Comment by asfalcone** [comment]
PR is merged. Will go out in the next `sigh` release! 💯
