### ISSUE TITLE
[sigh] Inconsistent shell syntax in resigh.sh script

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4288]
### New Issue Checklist

- [x] Updated sigh to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Current version of `resign.sh` script is using `=` to pass entitlements path to `codesign` command.

```bash
--entitlements="$ENTITLEMENTS"
```

This is inconsistent with the rest of the shell script.
It doesn't match the `codesign` man page either:

```shell
--entitlements path
          When signing, take the file at the given path and embed its contents in the signature as entitlement
          data. If the data at path does not already begin with a suitable binary ("blob") header, one is
          attached automatically
```

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by TKBurner** [comment]
@mgrebenets Thanks for pointing this out. We'll take a look and provide feedback on this thread before going ahead with the PR. Thanks!

**Comment by asfalcone** [comment]
Thanks! Merged. 👍
