### ISSUE TITLE
Why gym build the ipa file with SwiftSupport folder in it but my app does not using any swift code?

### ISSUE THREAD

**Issue by jianpx** [fastlane/fastlane#4290]
### Issue Description

I am using gym (version is 1.6.2) to build my app, my app is using only objective c code, not using any swift code, but gym build an ipa file with an empty “SwiftSupport” folder on the same level of folder “Payload”.
I think the “SwiftSupport” folder is not necessary, but I can not find an option to specify my app is an objective c app. 
And when I use another command to build debug ad-hoc app, the ipa file does not contain the empty  "SwiftSupport" folder. 

At last , I want to know how gym check my app is a swift app or not ?

### Unzip ipa file content:
NIESpider.ipa
|---Payload
|---SwiftSupport

### Configuration Files
Fastfile with Release config:
```ruby
 lane :build_release_ipa do
   config = "Release"
   ipafilename = 'NIESpider.ipa'
   gym({
     workspace: 'NIESpider',
     scheme: 'NIESpider',
     configuration: config,
     clean: true,
     export_method: 'app-store'
     use_legacy_build_api: true,
     output_name: ipafilename
   })
   notify "build Release #{ipafilename} successfully, have fun!"
 
 end
```

Fastfile with Debug config:
```ruby
 lane :build_release_ipa do
   config = "Debug"
   ipafilename = 'NIESpider.ipa'
   gym({
     workspace: 'NIESpider',
     scheme: 'NIESpider',
     configuration: config,
     clean: true,
     export_method: 'ad-hoc'
     output_name: ipafilename
   })
   notify "build Release #{ipafilename} successfully, have fun!"
 
 end
```

### Environment
* fastlane version is :1.81.0
* gym version is :1.6.2

**Comment by TKBurner** [comment]
@jianpx Thanks for reaching out. We are going to look into this over here, however it'd be helpful to know if there are any contents to the SwiftSupport folder.

Thanks!

**Comment by jianpx** [comment]
@TKBurner the SwiftSupport folder is empty.

**Comment by TKBurner** [comment]
Hi @jianpx! Thanks for following up. Right now this is expected behavior. I'm going to mark this as a feature request and we'll review it. Thanks!

**Comment by jianpx** [comment]
hi， @TKBurner , I am wondering if the empty SwiftSupport folder has side effect on the submit to App Store .

**Comment by TKBurner** [comment]
@jianpx Thanks for following up. Since it's an artifact of using the Xcode APIs it's unlikely it'd affect your app review. Let me know if you find out otherwise! Thanks 👍
