### ISSUE TITLE
frameit not working with current iPad Air 2 simulator and screenshots

### ISSUE THREAD

**Issue by fdstevex** [fastlane/fastlane#4291]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Screenshot taken with current (Xcode 7.3) simulator not matching with the downloaded device frames.  

##### Complete output when running fastlane, including the stack trace and command used

```
$ frameit
[22:35:19]: Unsupported screen size [1536, 1152] for path './Simulator Screen Shot Apr 20, 2016, 10.06.47 PM.png'
```

The screenshot in question is saved from the simulator simulating an iPad Air 2, file info:

$ file Simulator\ Screen\ Shot\ Apr\ 20\,\ 2016\,\ 10.06.47\ PM.png 
Simulator Screen Shot Apr 20, 2016, 10.06.47 PM.png: PNG image data, 1536 x 1152, 8-bit/color RGB, non-interlaced

Contents of ~/.frameit

.frameit
.frameit/.DS_Store
.frameit/devices_frames
.frameit/devices_frames/.DS_Store
.frameit/devices_frames/iPad Air 2
.frameit/devices_frames/iPad Air 2/.DS_Store
.frameit/devices_frames/iPad Air 2/App Store Marketing Getting Started Guide.pdf
.frameit/devices_frames/iPad Air 2/iPad Air 2 Silver
.frameit/devices_frames/iPad Air 2/iPad Air 2 Silver/.DS_Store
.frameit/devices_frames/iPad Air 2/iPad Air 2 Silver/iPad_Air_2_H_Slvr_sRGB.png
.frameit/devices_frames/iPad Air 2/iPad Air 2 Silver/iPad_Air_2_H_Slvr_sRGB.psd
.frameit/devices_frames/iPad Air 2/iPad Air 2 Silver/iPad_Air_2_V_Slvr_sRGB.png
.frameit/devices_frames/iPad Air 2/iPad Air 2 Silver/iPad_Air_2_V_Slvr_sRGB.psd
.frameit/devices_frames/iPad Air 2/iPad Air 2 Space Gray
.frameit/devices_frames/iPad Air 2/iPad Air 2 Space Gray/iPad_Air_2_H_SpcGr_sRGB.png
.frameit/devices_frames/iPad Air 2/iPad Air 2 Space Gray/iPad_Air_2_H_SpcGr_sRGB.psd
.frameit/devices_frames/iPad Air 2/iPad Air 2 Space Gray/iPad_Air_2_V_SpcGr_sRGB.png
.frameit/devices_frames/iPad Air 2/iPad Air 2 Space Gray/iPad_Air_2_V_SpcGr_sRGB.psd
.frameit/devices_frames/iPad Pro
.frameit/devices_frames/iPad Pro/.DS_Store
.frameit/devices_frames/iPad Pro/App Store Marketing Getting Started Guide.pdf
.frameit/devices_frames/iPad Pro/iPad-Pro-Silver-horizontal.png
.frameit/devices_frames/iPad Pro/iPad-Pro-Silver-horizontal.psd
.frameit/devices_frames/iPad Pro/iPad-Pro-Silver.png
.frameit/devices_frames/iPad Pro/iPad-Pro-Silver.psd
.frameit/devices_frames/iPad Pro/iPad-Pro-Space-Gray-horizontal.png
.frameit/devices_frames/iPad Pro/iPad-Pro-Space-Gray-horizontal.psd
.frameit/devices_frames/iPad Pro/iPad-Pro-Space-Gray.png
.frameit/devices_frames/iPad Pro/iPad-Pro-Space-Gray.psd
.frameit/devices_frames/iPad-mini-4
.frameit/devices_frames/iPad-mini-4/.DS_Store
.frameit/devices_frames/iPad-mini-4/App Store Marketing Getting Started Guide.pdf
.frameit/devices_frames/iPad-mini-4/iPad mini Silver
.frameit/devices_frames/iPad-mini-4/iPad mini Silver/.DS_Store
.frameit/devices_frames/iPad-mini-4/iPad mini Silver/iPad-mini-Silver-horizontal.png
.frameit/devices_frames/iPad-mini-4/iPad mini Silver/iPad-mini-Silver-horizontal.psd
.frameit/devices_frames/iPad-mini-4/iPad mini Silver/iPad-mini-Silver-vertical.png
.frameit/devices_frames/iPad-mini-4/iPad mini Silver/iPad-mini-Silver-vertical.psd
.frameit/devices_frames/iPad-mini-4/iPad mini Space Gray
.frameit/devices_frames/iPad-mini-4/iPad mini Space Gray/.DS_Store
.frameit/devices_frames/iPad-mini-4/iPad mini Space Gray/iPad-mini-Space-Gray-horizontal.png
.frameit/devices_frames/iPad-mini-4/iPad mini Space Gray/iPad-mini-Space-Gray-horizontal.psd
.frameit/devices_frames/iPad-mini-4/iPad mini Space Gray/iPad-mini-Space-Gray-vertical.png
.frameit/devices_frames/iPad-mini-4/iPad mini Space Gray/iPad-mini-Space-Gray-vertical.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/.DS_Store
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/App Store Marketing Getting Started Guide.pdf
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/.DS_Store
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-horizontal-iPhone-6s-Silver-horizontal.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-horizontal-iPhone-6s-Silver-horizontal.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-horizontal-iPhone-6s-Silver-vertical.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-horizontal-iPhone-6s-Silver-vertical.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-vertical-iPhone-6s-Silver-horizontal.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-vertical-iPhone-6s-Silver-horizontal.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-vertical-iPhone-6s-Silver-vertical.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Silver/iPad-Pro-Silver-vertical-iPhone-6s-Silver-vertical.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/.DS_Store
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-horizontal-iPhone-6s-Space-Gray-horizontal.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-horizontal-iPhone-6s-Space-Gray-horizontal.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-horizontal-iPhone-6s-Space-Gray-vertical.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-horizontal-iPhone-6s-Space-Gray-vertical.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-vertical-iPhone-6s-Space-Gray-horizontal.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-vertical-iPhone-6s-Space-Gray-horizontal.psd
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-vertical-iPhone-6s-Space-Gray-vertical.png
.frameit/devices_frames/iPad-Pro-and-iPhone-6s/Space Gray/iPad-Pro-Space-Gray-vertical-iPhone-6s-Space-Gray-vertical.psd
.frameit/devices_frames/iPhone SE
.frameit/devices_frames/iPhone SE/.DS_Store
.frameit/devices_frames/iPhone SE/App Store Marketing Getting Started Guide.pdf
.frameit/devices_frames/iPhone SE/iPhone-SE-Silver-horizontal.png
.frameit/devices_frames/iPhone SE/iPhone-SE-Silver-horizontal.psd
.frameit/devices_frames/iPhone SE/iPhone-SE-Silver.png
.frameit/devices_frames/iPhone SE/iPhone-SE-Silver.psd
.frameit/devices_frames/iPhone SE/iPhone-SE-Space-Gray-horizontal.png
.frameit/devices_frames/iPhone SE/iPhone-SE-Space-Gray-horizontal.psd
.frameit/devices_frames/iPhone SE/iPhone-SE-Space-Gray.png
.frameit/devices_frames/iPhone SE/iPhone-SE-Space-Gray.psd
.frameit/devices_frames/iPhone-6s
.frameit/devices_frames/iPhone-6s/.DS_Store
.frameit/devices_frames/iPhone-6s/App Store Marketing Getting Started Guide.pdf
.frameit/devices_frames/iPhone-6s/iPhone 6s - Silver
.frameit/devices_frames/iPhone-6s/iPhone 6s - Silver/.DS_Store
.frameit/devices_frames/iPhone-6s/iPhone 6s - Silver/iPhone-6s-Silver-horizontal.png
.frameit/devices_frames/iPhone-6s/iPhone 6s - Silver/iPhone-6s-Silver-horizontal.psd
.frameit/devices_frames/iPhone-6s/iPhone 6s - Silver/iPhone-6s-Silver-vertical.png
.frameit/devices_frames/iPhone-6s/iPhone 6s - Silver/iPhone-6s-Silver-vertical.psd
.frameit/devices_frames/iPhone-6s/iPhone 6s - Space Gray
.frameit/devices_frames/iPhone-6s/iPhone 6s - Space Gray/.DS_Store
.frameit/devices_frames/iPhone-6s/iPhone 6s - Space Gray/iPhone-6s-Space-Gray-horizontal.png
.frameit/devices_frames/iPhone-6s/iPhone 6s - Space Gray/iPhone-6s-Space-Gray-horizontal.psd
.frameit/devices_frames/iPhone-6s/iPhone 6s - Space Gray/iPhone-6s-Space-Gray-vertical.png
.frameit/devices_frames/iPhone-6s/iPhone 6s - Space Gray/iPhone-6s-Space-Gray-vertical.psd
.frameit/devices_frames/iPhone-6s-Plus
.frameit/devices_frames/iPhone-6s-Plus/.DS_Store
.frameit/devices_frames/iPhone-6s-Plus/App Store Marketing Getting Started Guide.pdf
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Silver
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Silver/.DS_Store
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Silver/iPhone-6s-Plus-Silver-horizontal.png
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Silver/iPhone-6s-Plus-Silver-horizontal.psd
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Silver/iPhone-6s-Plus-Silver-vertical.png
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Silver/iPhone-6s-Plus-Silver-vertical.psd
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Space Gray
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Space Gray/.DS_Store
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Space Gray/iPhone-6s-Plus-Space-Gray-horizontal.png
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Space Gray/iPhone-6s-Plus-Space-Gray-horizontal.psd
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Space Gray/iPhone-6s-Plus-Space-Gray-vertical.png
.frameit/devices_frames/iPhone-6s-Plus/iPhone 6s Plus - Space Gray/iPhone-6s-Plus-Space-Gray-vertical.psd

### Configuration Files

Fastfile:
```ruby
No Fastfile, I'm just using frameit.
```

### Environment

fastlane version (run `fastlane -v`):

$ frameit -v
frameit 2.5.1
$ fastlane -v
fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

no

**Comment by fdstevex** [comment]
Oops.  Had saved a screenshot at 75% resolution. Would be nice if frameit supported this but it's not a bug, or even worth keeping as an enhancement request.  Closing this.

**Comment by TKBurner** [comment]
@fdstevex Thanks for following up and letting us know. Hope that you have a wonderful week! 👍
