### ISSUE TITLE
Help on taking screenshot(Snapshot) using other then UI test

### ISSUE THREAD

**Issue by cbcadmin** [fastlane/fastlane#4293]
Hi, 

We have apps which are being generated from XML using an exporting server, so in order to take screenshot for these apps we need to parse the XML and generate the output file that snapshot framework needs to make the right screenshot of the app. So could you please help us here to find the solution.

Thanks

**Comment by TKBurner** [comment]
HI @cbcadmin Great to hear from you! You are going to need to generate a snapfile, which you can read about here, https://github.com/fastlane/fastlane/tree/master/snapshot#snapfile. Let me know how it goes 👍

**Comment by cbcadmin** [comment]
Hi @TKBurner, Thanks for coming back on this, but what i meant was I am able to take screenshots for an app but we have multiple Xcode projects being generated for similar kind of apps and for each project we have to add UI test target and write the test-case for each of these apps, so we wanted to generalise this and wanted help on how can we achieve this.

**Comment by TKBurner** [comment]
@cbcadmin Thanks for following up. Right now this isn't possible directly through our tools but if you wire something up please do share! Thanks!

**Comment by cbcadmin** [comment]
@TKBurner Thanks for the Info, will let you know if i find something.
