### ISSUE TITLE
9cc436abbbbe11c78811ffd6727b11a2

### ISSUE THREAD

**Issue by sopig** [fastlane/fastlane#4294]
[sentry_9cc436abbbbe11c78811ffd6727b11a2.json.zip](https://github.com/fastlane/fastlane/files/229477/sentry_9cc436abbbbe11c78811ffd6727b11a2.json.zip)

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
Hi @sopig! Great to hear that you are using Fastlane. Can you provide more details about the issue you are experiencing so we can look into it. Fill in each part of the template above.

Thanks!
