### ISSUE TITLE
Executing match development if you have multiple targets will stuck

### ISSUE THREAD

**Issue by mladjan** [fastlane/fastlane#4296]
### Issue Description
Until you specify exact target, it will stuck and user will not know what to do.

##### Complete output when running fastlane, including the stack trace and command used

```
+-----------------------+---------------------------------------------------------+
|                             Summary for match 0.4.0                             |
+-----------------------+---------------------------------------------------------+
| verbose               | true                                                    |
| git_url               | git@bitbucket.org:mladjan/somerepo.git |
| type                  | development                                             |
| app_identifier        | com.stellup.mobile                                      |
| username              | tech@stellup.com                                        |
| keychain_name         | login.keychain                                          |
| readonly              | false                                                   |
| force                 | false                                                   |
| shallow_clone         | false                                                   |
| force_for_new_devices | false                                                   |
| skip_docs             | false                                                   |
+-----------------------+---------------------------------------------------------+

INFO [2016-04-21 09:24:20.81]: Cloning remote git repo...
INFO [2016-04-21 09:24:20.81]: $ git clone 'git@bitbucket.org:mladjan/somerepo.git' '/var/folders/4d/dnsb54tn54v3_2yls89j4h_c0000gn/T/d20160421-63486-itnz1'
INFO [2016-04-21 09:24:20.81]: ▸ Cloning into '/var/folders/4d/dnsb54tn54v3_2yls89j4h_c0000gn/T/d20160421-63486-itnz1'...
INFO [2016-04-21 09:24:21.72]: ▸ The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
INFO [2016-04-21 09:24:21.72]: ▸ RSA key fingerprint is somekey
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile: It's not used.

### Environment

fastlane 1.81.0
match 0.4.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by TKBurner** [comment]
Hi @mladjan Thanks for reaching out. Can you format your issue per this template? https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md 

Also, make sure to include exact repro steps if you think this is a bug.

We'd love to take a look 👍

**Comment by mladjan** [comment]
Updated

**Comment by TKBurner** [comment]
Hi @mladjan! Thanks for following up. It looks like there might be something wrong with the cert you are using to access bitbucket. See the error: INFO [2016-04-21 09:24:21.72]: ▸ The authenticity of host 'bitbucket.org (104.192.143.3)' can't be established.
INFO [2016-04-21 09:24:21.72]: ▸ RSA key fingerprint is somekey

Thanks!

**Comment by mladjan** [comment]
But it works without any problem when you add -a com.stellup.mobile

**Comment by mfurtak** [comment]
Hi @mladjan - thanks for the report! 👍 

From the same machine in the same directory, what happens if you just run the git command:

```
git clone git@bitbucket.org:mladjan/somerepo.git somerepo
```

Does it prompt you for username/password credentials, perhaps?
