### ISSUE TITLE
Creation of apps of this type is not available

### ISSUE THREAD

**Issue by ssteinerx** [fastlane/fastlane#4298]
497d538665f7812ecb4e49cc588ecaae

### Issue Description

I have one Apple ID belonging to two different teams.

One team is set up to create IOS apps, the other is a personal, expired, development account.

Even though I've given the team_id of the active team, I am always getting the "Creation of apps of this type is not available"

The app was successfully created in the correct account, 

Which is really odd since the output is this:
```

[07:08:56]: [DevCenter] App 'com.<omitted>' already exists, nothing to do on the Dev Center
[07:08:57]: Creating new app '<omitted>' on iTunes Connect
[07:08:57]: -------------------
[07:08:57]: --- Step: slack ---
[07:08:57]: -------------------
[07:08:58]: Successfully sent Slack notification
[07:08:58]: Variable Dump:
[07:08:58]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios provision"}
[07:08:58]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Creation of apps of this type is not available"]}, "statusCode"=>"ERROR"}

```

### Configuration
Straight out of the doc:

```
 # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    produce(
      app_name: '<omitted>',
      language: 'English',
      app_version: '1.0',
      sku: '<omitted>'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end
```

### Environment

fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No, using system (OS X 10.10.5) ruby.
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

**Comment by TKBurner** [comment]
Hi @ssteinerx Thanks for reaching out. Can you share the full output with all the commands that were entered? It looks like we only see the Slack action here which won't give a ton of useful information. Also, I don't see Slack in your Fastfile. Thanks! 👍

**Comment by ssteinerx** [comment]
I have left out all proprietary information (like the slack link with embedded API).

I figured out that my account didn't have access to iTunes Connect on the account on which I was publishing.

Some sort of output around this area (when running with --verbose), letting me know where exactly fastlane failed would have saved me a couple of hours of digging around.  Printing out the API return code didn't really help as I wasn't sure from which operation that came, exactly.

**Comment by TKBurner** [comment]
@ssteinerx Thanks for following up. I'm glad to hear you figured out what was causing this. We'll work on the error messaging. Hope that you have a great weekend 👍
