### ISSUE TITLE
[sigh] Missing support for long options in resign.sh script

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4302]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The `resign.sh` script used by `sigh` has great value and can be used on its own. However, the use of `getopts` utility limits all argument options to be short (`-p`, `-e`, etc.).

New options when added have to take strange letters and become more and more cryptic.

I have more fixes planned for the future, and those will require adding new arguments to `resign.sh`, so using long options will save the pain for those future updates.

Also, the usage message of the script does not list all the options and documentation for them.

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by TKBurner** [comment]
@mgrebenets Thanks for reaching out. We'll review this as a feature request and update this thread as releveant. Hope you have a great weekend 👍

**Comment by mgrebenets** [comment]
The PR is merged, closing this one. Thanks 👍
