### ISSUE TITLE
Download P12 certs using PEM action in every build. 

### ISSUE THREAD

**Issue by marcomorain** [fastlane/fastlane#4309]
I'd love to be able to download exiting P12 certs using `pem`. 

Currently we use PEM to create new certs, and we upload the cert to our server when a new cert is created. If the upload fails for any reason, the cert is created, but we don't have a copy on our server. I then have to manually download the cert from the developer portal. 

This would be awesome if PEM would download the cert if it doesn't create one, so that I can upload the cert to our server on every build. 

This would allow me to build a self-healing system whereby if a build fails and I don't get the cert uploaded, I can be confident that the next time I push I will get the cert. 

Essentially I want the new_profile callback to fire on each invocation of the PEM action.

**Comment by TKBurner** [comment]
@marcomorain Thanks for reaching out. I'll let the team know about this idea. Hope that you have a great weekend 👍

**Comment by marcomorain** [comment]
👍👍😎
 
--
Marc O'Morain
marc@marcomorain.com
 
 
 
On Fri, 22 Apr 2016, at 21:44, Todd Burner wrote:
> @marcomorain[1] Thanks for reaching out. I'll let the team know about
> this idea. Hope that you have a great weekend 👍
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[2]
>

Links:

  1. https://github.com/marcomorain
  2. https://github.com/fastlane/fastlane/issues/4309#issuecomment-213582705

**Comment by KrauseFx** [comment]
Hey @marcelofabri, sorry for the late reply. That's actually not possible, since the certificate is private and not stored on Apple's server. There is no way to retrieve an existing push certificate (p12 file) from Apple. If there is, please let me know 👍
