### ISSUE TITLE
Can Spaceship determine somehow if a build is Newsstand ?

### ISSUE THREAD

**Issue by chappejw** [fastlane/fastlane#4311]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Can Spaceship be used to determine if a build is Newsstand ? Unfortunately, I need to support at least one backwards compatible version in this case iOS 8, which still supports Newsstand. I need a way to check programmatically whether an existing build on iTunesconnect is Newsstand since these builds require a different set of assets & config options. Any suggestions? Using Spaceship, I accessed the <Spaceship::Tunes::Application> as well as the <Spaceship::Tunes::Build> objects, but I did not see any attributes within these which would indicate that I am looking at a Newsstand build.

##### Complete output when running fastlane, including the stack trace and command used

```
No output as this is just a question to devs if this is possible
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# no Fastfile in use
```

### Environment

fastlane version (run `fastlane -v`):
1.81.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by TKBurner** [comment]
Hi @chappejw Thanks for reaching out. I think this is set in the app metadata so you should look there.

Thanks!

**Comment by chappejw** [comment]
I have foregone this requirement now since Apple has dropped Newsstand in iOS 9. I only needed this in order to support 1 previous version ( iOS 8 ) which still requires the Newsstand plist setting and icon images etc. iOS 10 will be released soon so it will no longer be necessary.
