### ISSUE TITLE
Show the default value when running fastlane action [tool_name]

### ISSUE THREAD

**Issue by serluca** [fastlane/fastlane#4319]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Some actions have required parameters marked with the `*` but they also have the default value.
Would be nice to know the default value of the parameters when executing  fastlane action [tool_name].

i.e.
Match has the `force_for_new_devices` parameter that is required and by default is `false` as we can see [here](https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/match/lib/match/options.rb#L95-L99) but `fastlane action match` doesn't say it.

```
fastlane action match

| * force_for_new_devices | Renew the provisioning profiles if the device count on the developer portal has changed | MATCH_FORCE_FOR_NEW_DEVICES |
```

### Environment

fastlane version:  1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by TKBurner** [comment]
Hi @serluca Great to hear from you. We are going to evaluate this as a feature request and will follow up on this thread as relevant. Thanks for working with us! 👍

**Comment by serluca** [comment]
Hi @TKBurner thanks to get back to me, I know that when the command runs I can see the parameters but doesn't help when writing the fastfile.

**Comment by mfurtak** [comment]
Accepted in #4331 🚀
