### ISSUE TITLE
krausefx-ipa breaks on 0.14.4 from 0.14.3

### ISSUE THREAD

**Issue by dbachrach** [fastlane/fastlane#433]
I can't seem to find the source repository for krausefx-shenzhen, but I've been able to track down a failure today in our fastlane builds. I upgraded to fastlane 1.11.0, and an ipa-based build failed. I tracked it down to this individual command:

```
krausefx-ipa build -w "Leaps.xcworkspace" -c "Release" -s "MediaGame" -m "Leaps_Enterprise_Profile.mobileprovision" --clean --archive --verbose 
````

If I run this above command on krausefx-ipa 0.14.3, then everything succeeds. Running the same command on 0.14.4, I get the following error at the end of the build:

```
Touch /Users/dustin/Library/Developer/Xcode/DerivedData/Leaps-dzuvqexiqrdedqgcovzvngymcizk/Build/Intermediates/ArchiveIntermediates/MediaGame/BuildProductsPath/Release-iphoneos/Leaps.app.dSYM
    cd /Users/dustin/projects/mediahound/dev/leaps
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/dustin/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin:/Users/dustin/.rbenv/versions/2.2.2/bin:/usr/local/Cellar/rbenv/0.4.0/libexec:/Users/dustin/.rbenv/plugins/rbenv-binstubs/bin:/Users/dustin/projects/mediahound/dev/leaps/bin:/usr/local/heroku/bin:/Users/dustin/.rbenv/shims:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/dustin/bin"
    /usr/bin/touch -c /Users/dustin/Library/Developer/Xcode/DerivedData/Leaps-dzuvqexiqrdedqgcovzvngymcizk/Build/Intermediates/ArchiveIntermediates/MediaGame/BuildProductsPath/Release-iphoneos/Leaps.app.dSYM

** ARCHIVE SUCCEEDED **

          xcrun  PackageApplication
xcrun -sdk iphoneos PackageApplication -v "/Users/dustin/Library/Developer/Xcode/DerivedData/Leaps-dzuvqexiqrdedqgcovzvngymcizk/Build/Products/Release-iphoneos/Leaps.app" -o "/Users/dustin/projects/mediahound/dev/leaps/Leaps.ipa" --embed "Leaps_Enterprise_Profile.mobileprovision"  --verbose 
error: Specified application doesn't exist or isn't a bundle directory : '/Users/dustin/Library/Developer/Xcode/DerivedData/Leaps-dzuvqexiqrdedqgcovzvngymcizk/Build/Products/Release-iphoneos/Leaps.app'
```

Any pointers to where krausef-shenzhen is so I can take a look at the source, or any ideas for a fix are welcome. Thanks!

**Comment by KrauseFx** [comment]
Sure, the code is hosted here: https://github.com/fastlane/shenzhen

**Comment by dbachrach** [comment]
So the only notable change in 0.14.4 was the double build for archive:

```ruby
actions << :build unless options.archive == true
```

If I remove my --archive flag when I invoke krausefx-ipa, the build succeeds. So it's definitely related to this double build on archive.

**Comment by KrauseFx** [comment]
So not having the `:build` always set breaks it for you?

**Comment by KrauseFx** [comment]
What needs to be changed?

**Comment by dbachrach** [comment]
Seems to be that removing `:build` causes this to not work. I'm not familiar enough with shenzhen to know if the correct fix is to revert or something else?

**Comment by staminajim** [comment]
Chiming in that I just tried and got something similar.  I was hoping to speed up beta release times by using the `-archive` option, but the build fails at the last step with:

```
▸ Touching SeatGeek.app
▸ Signing /Users/james/Library/Developer/Xcode/DerivedData/SeatGeek-bllkhnznsrxpgsbqfwchkfyihoqp/Build/Intermediates/ArchiveIntermediates/SeatGeek\ BETA\ RELEASE/InstallationBuildProductsLocation/Applications/SeatGeek.app
▸ Touching SeatGeek.app.dSYM
error: Specified application doesn't exist or isn't a bundle directory : '/Users/james/Library/Developer/Xcode/DerivedData/SeatGeek-bllkhnznsrxpgsbqfwchkfyihoqp/Build/Products/BetaTest-iphoneos/SeatGeek.app'
```

I haven't looked for a solution in the shenzhen source yet.

**Comment by dbachrach** [comment]
It may be wise to revert the double build change in krausefx-shenzhen and release a new fastlane with that until we get more clarification from shenzhen on why the double build is needed?

**Comment by KrauseFx** [comment]
@dbachrach sounds like a plan. So I'll just remove the patch that caused longer build times and release a new version?

**Comment by dbachrach** [comment]
Excellent. Let's do that for now, and revisit the double build problem.

**Comment by JaviLorbada** [comment]
This PR (https://github.com/nomad/shenzhen/pull/287) might solve this issue, but it would be wise to rollback for now 🙏

**Comment by KrauseFx** [comment]
Here we go: https://github.com/fastlane/shenzhen/commit/0f027322b6b963698d816a1d206e85eab8437cb2

This will be in the next fastlane release :+1: 

You can already update using `sudo gem update krausefx-shenzhen`

**Comment by dbachrach** [comment]
Thanks :+1:

**Comment by JaviLorbada** [comment]
Thanks Felix! :+1:

**Comment by ds29** [comment]
@KrauseFx For those of us using bundler (e.g. Gemfile), the 0.14.5 fix can't be installed properly because fastlane.gemspec specifies `=` instead of `>=`.

`  spec.add_dependency 'krausefx-shenzhen', '= 0.14.4' # to upload to Hockey and Crashlytics`

**Comment by KrauseFx** [comment]
Sorry about this @ds29, I updated it. This will be available on the next update.

**Comment by dbachrach** [comment]
Thanks Felix. I'll keep an eye out for the new fastlane release and close this issue then.

**Comment by staminajim** [comment]
@KrauseFx The latest version is building again with the `--archive` option, but it's still building everything twice with or without the archive flag.  Is there some trick we need to do to have everything only compile once with the new shenzhen?

**Comment by KrauseFx** [comment]
Yes, as discussed with @dbachrach we decided to rollback to have the double building to not run into the issue described above.

I actually want to get rid of `shenzhen` and replace it with a tool focused on building and nothing else. I plan on working on it over the next few weeks.

**Comment by staminajim** [comment]
OK thanks @KrauseFx :+1: Looking forward to the replacement compile tool which will drastically speed up build times for us ;)

So that's a `fixed` from me, can wait to hear from @dbachrach to double confirm if you like.

**Comment by JaviSoto** [comment]
Hi @staminajim! I'm sure you've seen the awesome new `gym` tool. I'm going to go ahead and close this issue since it may not be relevant. If you'd still like help with this though, feel free to comment and we'll reopen it!
