### ISSUE TITLE
Error uploading to TestFlight - CFBundleShortVersionString - Info.plist file must contain a higher version than that of the previously approved version

### ISSUE THREAD

**Issue by JoeFerrucci** [fastlane/fastlane#4332]
I had successfully uploaded my app version 2.0.2 build **33** to TestFlight.
I had to make a change, now I'm trying to upload version 2.0.2 build **34** to TestFlight, but I'm getting this error: 

` [Transporter Error Output]: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.0.2] in the Info.plist file must contain a higher version than that of the previously approved version [2.0.2]." `

` ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.0.2] in the Info.plist file must contain a higher version than that of the previously approved version [2.0.2]." `

` ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.0.2] in the Info.plist file must contain a higher version than that of the previously approved version [2.0.2]."
Return status of iTunes Transporter was 1: ERROR ITMS-90062: "This bundle is invalid. The value for key CFBundleShortVersionString [2.0.2] in the Info.plist file must contain a higher version than that of the previously approved version [2.0.2]." `

` Could not download/upload from iTunes Connect! It's probably related to your password or your internet connection. `

` Error uploading ipa file, more information see above `

Why can I not upload the same version with a higher build??

**Comment by truth3** [comment]
@JoeFerrucci You haven't released version 2.0.2 of your application yet have you?

**Comment by JoeFerrucci** [comment]
No, its not released yet.

**Comment by truth3** [comment]
Thats odd, as the message back from Apple seems to say that your current public version is 2.0.2 Do you get the same error if you build and push through Xcode?

**Comment by JoeFerrucci** [comment]
2.0.2 is Pending Developer Release. That's likely the problem then?

**Comment by truth3** [comment]
@JoeFerrucci Yep.. I think that would be the case.. if you bump the version to 2.0.3 I bet it will go through just fine.

**Comment by JoeFerrucci** [comment]
I'm sure you're correct. I'll probably just pull 2.0.2 and resubmit it when ready. Thanks for helping me resolve this issue.

**Comment by TKBurner** [comment]
@truth3 Thanks so much for stepping in! Yup @JoeFerrucci that seems to be the reason you are seeing this. Really glad to have you using Fastlane 👍
