### ISSUE TITLE
Improve `actions_list.rb`

### ISSUE THREAD

**Issue by mfurtak** [fastlane/fastlane#4335]
I'd like to make some improvements to `actions_list.rb`:

1. Refactor the code a bit to improve readability and remove the need for rubocop violation suppressions
2. Improve the handling of "broken" actions

----

Currently `actions_list.rb` gives good feedback to action creators if they create a class in the `Fastlane::Actions` namespace but forget to have it subclass `Action`. It does this by listing the action in the output of `fastlane actions`, but calling out the problem in red.

<img width="998" alt="screen shot 2016-04-23 at 2 24 52 pm" src="https://cloud.githubusercontent.com/assets/343134/14763342/be692b24-0960-11e6-9baf-3c10d0439096.png">

However, if the developer instead calls `fastlane action broken` to look at the info for their action, they will get an error:

<img width="1280" alt="screen shot 2016-04-23 at 2 16 24 pm" src="https://cloud.githubusercontent.com/assets/343134/14763341/a51371c0-0960-11e6-97a6-742e011e99cc.png">

**Comment by KrauseFx** [comment]
This is great!

**Comment by asfalcone** [comment]
Closing as the PR was merged and released! 🚗
