### ISSUE TITLE
Fastlane [supply] - how to auto create new app in Google Play like Procedure module 

### ISSUE THREAD

**Issue by TechGuyVN** [fastlane/fastlane#4338]
Hi,

Thanks for the best auto build framework in IOS,
But in Android how to auto create new app in Google Play like Procedure module ,
Thanks for supporting :)

**Comment by TKBurner** [comment]
@TechGuyVN Thanks for reaching out. Check out Supply here https://github.com/fastlane/fastlane/tree/master/supply for our Android tools 👍
