### ISSUE TITLE
Small inconsistency in selecting app/SYMs

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#4340]
See conversation on #4325

We sometimes to `.last` and sometimes `.first`

https://github.com/fastlane/fastlane/blob/6c4472beb5f3597dea6b0eaff7009d64ff8bec99/gym/lib/gym/generators/package_command_generator_legacy.rb#L48-L63

**Comment by TKBurner** [comment]
Hi @lacostej Thanks for pointing this out. We are going to use this ticket to track reports of issues related to this. For now, no action necessary. Thanks!
