### ISSUE TITLE
Frameit. Replace iPhone 5S images with iPhone SE

### ISSUE THREAD

**Issue by win2l** [fastlane/fastlane#4342]
Hi, team. Thank your for your great products.

After iPhone SE came to the world, Apple replaced iPhone 5S images with images of SE on their [App Store Marketing](https://developer.apple.com/app-store/marketing/guidelines/#images) page.

We need a little update of *frameit* to use these new resources.

**Comment by TKBurner** [comment]
Hi @win2l Thanks for reaching out about this. We are working on this and you should see these changes soon 👍

**Comment by i2amsam** [comment]
@win2l done with https://github.com/fastlane/fastlane/pull/4411 check it out and let me know what you think!
