### ISSUE TITLE
[sigh] entitlements option is missing in resign action help message

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4344]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`resign` action supports `entitlements:` option but it's not listed in the help message.

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by asfalcone** [comment]
PR is merged. Will go out in the next `sigh` release! 💯
