### ISSUE TITLE
[sigh] Ask user for entitlements file path if more than one option is available

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4346]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If entitlements path was not explicitly specified, `sigh` will attempt to find entitlements file automatically.

When there's more than one `.entitlements` file in the project, `sigh` will pick up the most recently modified file. This logic is a bit obscure for users. I personally had no idea `sigh` was automatically picking up `.entitlements` files, then I thought it's done in alphabetical order, finally I discovered it's using last modified date for sorting.

So in my case, I have `AppProd.entitlements` and `AppTest.entitlements` and `Test` version was automatically picked up, while I was resigning with `Prod` provisioning profiles. This was tricky to detect until the moment I examined verbose logs output very close.

I see two solutions to this:

1. Do not pick up `.entitlements` files automatically, let the users specify explicitly what they want to do (https://github.com/fastlane/fastlane/pull/3866).
2. If there's more than one `.entitlements` file found, prompt users to specify which one to use.

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by TKBurner** [comment]
@mgrebenets Thanks for filling out the PR proposal. It looks like we went ahead with your PR. I'm going to close this out for housekeeping 👍
