### ISSUE TITLE
Shell command exited with exit status 1 instead of 0. with crashlytics

### ISSUE THREAD

**Issue by evercry** [fastlane/fastlane#4347]
### New Issue Checklist

- [V] Updated fastlane to the latest version
- [] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

14:33:34]: -------------------------
[14:33:34]: --- Step: crashlytics ---
[14:33:34]: -------------------------
[14:33:34]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[14:33:43]: Variable Dump:
[14:33:43]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios crashlytics_beta", :IPA_OUTPUT_PATH=>"/Projects/XXX/xxx_ios_appstore-arc/CrashlyticsBetaBuilds/XXX-debug.ipa", :DSYM_OUTPUT_PATH=>"/Projects/XXX/xxx_ios_appstore-arc/CrashlyticsBetaBuilds/XXX-debug.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/xxx/Library/Developer/Xcode/Archives/2016-04-25/XXX-debug 2016-04-25 14.31.37.xcarchive"}
[14:33:43]: Shell command exited with exit status 1 instead of 0.

##### Complete output when running fastlane, including the stack trace and command used

```
[14:33:43]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '291eb2b006c8624dbdda101b69568fd4'
The crash report has been stored locally '/tmp/sentry_291eb2b006c8624dbdda101b69568fd4.json'
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.3/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:44:in `sh_no_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/crashlytics.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:65:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.3/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.81.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  desc "Submit a new Crashlytics Beta and send a notification to Slack."
  lane :crashlytics_beta do
  #increment_version_number
  gym(
  	use_legacy_build_api: true,
  	workspace: "XXX.xcworkspace",
  	configuration: "Release",
  	scheme: "XXX",
  	silent: true,
  	clean: true,
  	output_directory: "CrashlyticsBetaBuilds", # Destination directory. Defaults to current directory.
  	output_name: "XXX-debug.ipa", # specify the name of the .ipa file to generate (including file extension)
  	include_bitcode: false,
  )
  crashlytics(
  	crashlytics_path: 'Crashlytics.framework', # path to your 'Crashlytics.framework'
  	api_token: '',
  	build_secret: '',
  	ipa_path: 'CrashlyticsBetaBuilds/XXX-debug.ipa',
  	notes: 'Latest Beta build',
  	groups: ["XXX_testers"]
  )
  slack(
  	message: "Beta App successfully released!"
  )
  end
```

### Environment

fastlane version (run `fastlane -v`):
1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
Hi @evercry! Great to hear from you. Are you sure you are using the distribution group slug in your Fastfile and not the long name for the group?

Thanks!

**Comment by asfalcone** [comment]
Can you also try running your lane again with `--verbose`? Thanks @evercry!

**Comment by kordziu** [comment]
Hi,
I have the same issue. Realized there is a problem with "notes" variable. When I get rid of it in crashlytics action call uploading works well.

best,
pawel

**Comment by ben-lings-tessella** [comment]
We are seeing the same problem:

```
Shell command exited with exit status 1 instead of 0.
```

when running the `crashlytics` action:

```
crashlytics(
          crashlytics_path: './Frameworks/Crashlytics.framework',
          api_token: api_token,
          build_secret: build_secret,
          emails: '...@gmail.com'
        )
```

We run fastlane with `bundler`. Have updated to Fastlane v1.81 . This has only started happening in the last day or so.

**Comment by TKBurner** [comment]
@ben-lings-tessella Thanks for reaching out about this. Can you share the output of your lane if you add the --verbose flag to it? It'll help us look under the hood 👍

**Comment by asfalcone** [comment]
Hey folks, anyone who was running into problems just in the last 6 hours or so, I know that there was a problem with the Crashlytics backend and some uploads were impacted. You can see http://status.fabric.io/ for more details, but definitely give another try to see if that resolves the issue for you!

**Comment by ben-lings-tessella** [comment]
Thanks @asfalcone - looks like it was a problem with the Crashlytics backend service. I've re-run the build (without changing anything) and it's working for me now.

**Comment by TKBurner** [comment]
@ben-lings-tessella Thanks for following up. I'm going to go ahead and close this out. Hope you have a wonderful day!

**Comment by etolstoy** [comment]
I'm still experiencing the same issue, even after multiple retries. :(

```
  crashlytics(
      crashlytics_path: "Pods/Crashlytics",
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      notifications: "NO",
      notes: "123123",
      ipa_path: "Conferences.ipa"
    )
```

**Comment by TKBurner** [comment]
Hi @etolstoy! Thanks for reaching out. Can you share the full output of your attempt at running this action  with the --verbose flag on?

Thanks!

**Comment by ipapamagic** [comment]
Hi
I have the same issue

here is my output with --verbose flag on

INFO [2016-05-05 13:11:42.07]: -------------------------
INFO [2016-05-05 13:11:42.07]: --- Step: crashlytics ---
INFO [2016-05-05 13:11:42.07]: -------------------------
INFO [2016-05-05 13:11:42.08]: Uploading the build to Crashlytics Beta. Time for some ☕️.
DEBUG [2016-05-05 13:11:42.08]: ./Pods/Crashlytics/iOS/Crashlytics.framework/submit b58885e894536770c862af5a31d657c816817b3a 3610e256d44256c37ac2a8a08bca2b712fb27d2a64e574332ec9c1e511cb4de9 -ipaPath '/Users/IPaPa/Documents/EXJob/V5Viewer/V5Viewer.ipa' -notesPath '/var/folders/yc/1xrcr5494rd1dxf5bc1w_g1h0000gn/T/changelog20160505-51240-t4ha3m' -groupAliases 'V5' -notifications YES -debug NO
WARN [2016-05-05 13:11:48.80]: Variable Dump:
INFO [2016-05-05 13:11:48.80]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios Fabric", :BUILD_NUMBER=>"3", :FL_CHANGELOG=>"edit player feature\n", :IPA_OUTPUT_PATH=>"/Users/IPaPa/Documents/EXJob/V5Viewer/V5Viewer.ipa", :DSYM_OUTPUT_PATH=>"/Users/IPaPa/Documents/EXJob/V5Viewer/V5Viewer.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/IPaPa/Library/Developer/Xcode/Archives/2016-05-05/V5Viewer 2016-05-05 13.11.06.xcarchive"}
ERROR [2016-05-05 13:11:48.80]: Shell command exited with exit status 1 instead of 0.
INFO [2016-05-05 13:11:48.80]: Successfully generated documentation to path '/Users/IPaPa/Documents/EXJob/V5Viewer/fastlane/README.md'

+------+----------------------------------------+-------------+
|                      fastlane summary                       |
+------+----------------------------------------+-------------+
| Step | Action                                 | Time (in s) |
+------+----------------------------------------+-------------+
| 1    | Verifying required fastlane version    | 0           |
| 2    | default_platform                       | 0           |
| 3    | increment_build_number                 | 0           |
| 4    | git describe --match "build/v*" | wc -l | 0           |
| 5    | changelog_from_git_commits             | 0           |
| 6    | gym                                    | 37          |
| 7    | crashlytics                            | 6           |
+------+----------------------------------------+-------------+

ERROR [2016-05-05 13:11:48.82]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Shell command exited with exit status 1 instead of 0. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/helper/sh_helper.rb:47:in `sh_control_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/actions/crashlytics.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from ../../../MyWork/iOSLibrary/Fastfile:43:in `block in distributeFabric'
	from ../../../MyWork/iOSLibrary/Fastfile:40:in `each'
	from ../../../MyWork/iOSLibrary/Fastfile:40:in `distributeFabric'
	from ../../../MyWork/iOSLibrary/Fastfile:82:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/commands_generator.rb:171:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/lib/fastlane/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.85.0/bin/fastlane:6:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by mogui** [comment]
I'm still having this issue too :(

**Comment by phantomis** [comment]
same issue here!

**Comment by TKBurner** [comment]
Hi @phantomis and @mogui! Hope you are doing well! Can you let me know if it succeeds if you remove the group parameter from the upload? Can you share your full command so I can take a look. (Make sure to remove API key and build secret) Thanks!

**Comment by tsheaff** [comment]
I solved this issue for myself by wrapping `groups:` in an array after updating fastlane.

Previously was `groups: "Everyone",` but became `groups: ["Everyone"],`

**Comment by TKBurner** [comment]
@phantomis @mogui Did you have a chance to check out @tsheaff's comment. I think it could be helpful 👍
