### ISSUE TITLE
[sigh] Resign action 'version number' option is not fully documented and is too limiting

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4350]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The `version number` option to resign action changes both `CFBundleShortVersionString` and `CFBundleVersion`, while the description says `Version number to force resigned ipa to use`.

`Version number` term is too general. Having the same short version string and bundle version is not the best practice either, as far as I can tell. The `CBFBundleVersion` is commonly used to differentiate builds (`ipa`s) with the same `CFBundleShortVersionString`.

### Suggested Solution

While I personally think the `version` (`-n`) option should be either removed or changed, I also acknowledge backwards compatibility concerns.

The `-n` option of `resign.sh` script (`version` option of `resign` action) should be kept as it is now, but the action description should state explicitly that both `CFBundleShortVersionString` and `CFBundleVersion` will be changed to the same value.

The proper solution would be to introduce two more options: `short_version` and `bundle_version` for `resign` action (`--short-version` and `--bundle-version` for `resign.sh`). These 2 new options will be changing `CFBundleShortVersionString` and `CFBundleVersion` correspondingly.

Additionally `version` used with `short_version` or `bundle_version` (`-n` used with `--short-version` or `--bundle-version`) should result into an error message.

The solution is straightforward, but requires support for long options in `resign.sh` script, otherwise there would be more really cryptic one-letter short options added to the script. Long options support is implemented in this PR: https://github.com/fastlane/fastlane/pull/4303. 

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by TKBurner** [comment]
@mgrebenets Thanks for reaching out. Since we are already helping you merge this PR I'm going to close this ticket out 👍
