### ISSUE TITLE
Gym exporting the wrong app to ipa

### ISSUE THREAD

**Issue by Luke-SF** [fastlane/fastlane#4358]
I have updated to the latest version of gym, on Mac OS 10.11.4, and I'm noticing a serious error where it would export the wrong .ipa file. When I went to Application Loader to upload an ipa, I saw it had the logo of another app.

Looking through all the open terminals, I found something interesting - the one that was overwritten happened to be started the same minute that another started. In one terminal

[13:34:06]: xcrun xcodebuild -list -project ......

In another:

[13:34:45]: xcrun xcodebuild -list -project ......

so apparently it's just taking the last built file, and you cannot run multiple builds at the same time?

### Configuration Files
N/A

### Environment

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by TKBurner** [comment]
Hi @Luke-SF! Great to hear from you. You can set the parameters manually and that should allow you to act with duplicates. Run fastlane actions gym to see the list of parameters.

Thanks!
