### ISSUE TITLE
Code signing error even when enterprise certificate is in login.keychain

### ISSUE THREAD

**Issue by flexaddicted** [fastlane/fastlane#4359]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane fails when I try to export an ipa using an enterprise certificate. The enterprise cert is correctly installed in the **login.keychain**. If I move the enterprise certificate into the **System.keychain** the ipa is exported correctly.

Related issue: #1066.

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane release

Code Sign error: No matching codesigning identity found: No codesigning identities (i.e. certificate and private key pairs) matching "iPhone Distribution: **********" were found.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
default_platform :ios

platform :ios do

  before_all do

  end

  desc "Executing release lane"
  lane :release do

    gym(
        scheme: ENV['XCODE_SCHEME'],
        project: ENV['PROJECT'],
        sdk: ENV['SDK'],
        codesigning_identity: ENV['CODE_SIGN'],
        use_legacy_build_api: true,
        output_directory: ENV['OUTPUT_DIRECTORY'],
        configuration: 'Release'
    )

  end

  after_all do |lane|

    notify "Fastlane succeeded '#{lane}'"

  end

  error do |lane, exception|

    notify "Fastlane failed '#{lane}'"

  end

end
```

Xcode:

<img width="592" alt="xcode" src="https://cloud.githubusercontent.com/assets/1482350/14800962/8f4afc3a-0b3d-11e6-99cf-29095138ffa9.png">

### Environment

fastlane version (run `fastlane -v`): fastlane 1.81.0

**Comment by flexaddicted** [comment]
@TKBurner and @KrauseFx Using the command generated by `gym`

```
set -o pipefail && xcodebuild -scheme 'Scheme' -project 'PathToProject.xcodeproj' -configuration 'Release' -sdk 'iphoneos9.3' -destination 'generic/platform=iOS' -archivePath 'PathToArchive.xcarchive' archive CODE_SIGN_IDENTITY='iPhone Distribution: ******' | tee PathToLog.log | xcpretty
```

The archive and the app are generated correctly.

```
▸ Touching Scheme.app
▸ Signing PathToApp.app
▸ Touching Scheme.app.dSYM
▸ Archive Succeeded
```
Any suggestions?

**Comment by TKBurner** [comment]
Hi @flexaddicted! Great to hear from you. Can you share where you set your ENV codesigning_identity? What happens if you don't set it manually?

**Comment by flexaddicted** [comment]
@TKBurner I tried also manually but it does not work. I tried to set up a mini project and it seems working in the correct. Since I'm using also React Native the problem could rely on that. But not sure. I will back to you with when I will set up React Native in that dummy project. Anyway, using `xcodebuild` directly it works.

**Comment by TKBurner** [comment]
Hi @flexaddicted Thanks for following up. Can you add the --verbose flag to your lane and share the full output? It could be react related, but if your project is able to build in Xcode Fastlane should handle it.

**Comment by flexaddicted** [comment]
@TKBurner Sorry for the delay. I'll close the issue since I started a new branch from scratch and the problem is not there anymore. I can confirm there was something wrong with my build settings (but I did not investigate about it). I can also confirm that the `gym` configuration I am using is correct.

**Comment by TKBurner** [comment]
Thanks for letting us know @flexaddicted! Glad to hear you are back up and running 👍
