### ISSUE TITLE
[sigh] Feature request: add resign action options to modify short version string and bundle version

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4361]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Feature Request

Current version of sigh supports only `version` option (`-x|--version_number `in `sigh resign` executable, `-n|--version-number` in `resign.sh`).

This option, however, changes both `CFBundleShortVersionString` and `CFBundleVersion` to the same value, which is quite often undesirable.

The request is to provide 2 separate options, one for changing `CFBundleShortVersionString` and one for changing `CFBundleVersion`.

So one could, for example, resign the same build and just bump bundle version (often used as build number) by 1.

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by TKBurner** [comment]
@mgrebenets Thanks for filing this issue for your PR. We'll leave this thread open for discussion about the value of this feature. Thanks!

**Comment by asfalcone** [comment]
This PR has been accepted. Just waiting to merge since it requires a coupled `sigh` and `fastlane` release.

**Comment by TKBurner** [comment]
@mgrebenets Thanks again for all the work you do with us. I'm going to close this out since we accepted your PR 👍
