### ISSUE TITLE
How can I do 'snapshot --configuration "Debug"' from Fastfile?

### ISSUE THREAD

**Issue by funkenstrahlen** [fastlane/fastlane#4364]
I would like to add `snapshot` to my Fastfile as a task.

How can I use `snapshot --configuration "Debug"` in my Fastfile task? Like this?

```ruby
lane :screenshots do 
  snapshot(configuration: "Debug")
end
```

**Comment by TKBurner** [comment]
Hi @funkenstrahlen Thanks for reaching out. Yup this is the way you'd set up a lane called screenshots. You might want to use single quotes on your scheme name. Thanks!

**Comment by funkenstrahlen** [comment]
Thank you.
