### ISSUE TITLE
Make it easier to call another action from a custom action

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#4371]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to call an action (`cocoapods`) from a custom action I've created. 

In order to do it, this is what I had to do:

```ruby
values = ConfigurationHelper.parse(Fastlane::Actions::CocoapodsAction, {})
Fastlane::Actions::CocoapodsAction.run(values)
```

This seems quite complex and required some knowledge on how fastlane works under the hood: I inspected `runner.rb` to see how fastlane calls actions.

It'd be awesome to be able to call actions as I'd do in a `Fastfile`:

```ruby
cocoapods
```

Another option would be to use the `Actions` module:

```ruby
Actions.cocoapods
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.82.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? `rvm`

**Comment by TKBurner** [comment]
@marcelofabri Great suggestion, though this is obviously a serious task. We'll mark this as a feature request and see if it gets any traction 👍

**Comment by kunalbalani** [comment]
+1 for the feature
