### ISSUE TITLE
Make it possible to use .slather.yml on slather action

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#4372]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The [slather action](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/slather.rb) requires a `:proj` key. However, it's possible to define a project in a `.slather.yml`. 

The action could read the configuration file and check if there's a project defined instead of requiring it always.

This is a low priority issue though, since it's easy to call `slather` with `sh` or even pass the project name.

### Environment

fastlane version (run `fastlane -v`): fastlane 1.82.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by Ashton-W** [comment]
`slather` looks for the config file in the working dir, which in the built-in action can be `fastlane/` instead of your project root.

**Comment by TKBurner** [comment]
@marcelofabri Thanks for the idea. Let's see if we get any +1's 👍

**Comment by marcelofabri** [comment]
@Ashton-W The problem is that the `:proj` key is required (and not that the configuration file is not found). It should be easy do to something like `cocoapods` action: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/cocoapods.rb#L8

@TKBurner I'll try to create a PR in the next few days.

**Comment by TKBurner** [comment]
@marcelofabri Awesome! Thanks for stepping in :) Since there is a PR now I'm going to go ahead and close this issue out 👍
