### ISSUE TITLE
Danger action should support DANGER_GITHUB_API_TOKEN and --verbose

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#4373]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The new `danger` action should support sending `--verbose` flag to `danger`. It also should be possible to send a token that should be set to the `DANGER_GITHUB_API_TOKEN` env var that danger uses.

### Environment

fastlane version (run `fastlane -v`): fastlane 1.82.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by TKBurner** [comment]
@marcelofabri Great suggestion! We'll mark this as a feature request and see if it gets any traction. Hope that you have a great day and thanks for using Fastlane 😃
