### ISSUE TITLE
Add `message` option to the `add_git_tag` action

### ISSUE THREAD

**Issue by rpowelll** [fastlane/fastlane#4377]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'd like to propose that the `add_git_tag` should accept a `message` option to specify a custom tag message. Right now, this action uses the tag's name with _(fastlane)_ appended. So if the tag was `0.1.0-beta.4`, the tag message would read "0.1.0-beta.4 (fastlane)".

With an added `message` option, users could, for example, include release notes in the tag description. Whether this should replace the existing tag message or simply be appended to it is something I'm happy to put up for discussion.

As far as implementing this, I'd be happy to do it myself.

**Comment by TKBurner** [comment]
@rpowelll Thanks for the idea. I'm going to mark this as a feature request and also ping the team so they know you are proposing a PR. We can discuss the idea here. Thanks! 👍

**Comment by rpowelll** [comment]
Closing this as it's resolved by #4398
