### ISSUE TITLE
How can I only upload metadata with deliver in a Fastfile?

### ISSUE THREAD

**Issue by funkenstrahlen** [fastlane/fastlane#4379]
I want to call deliver in a Fastfile lane. However **it should only update the metadata**. I do not want to upload the `ipa` again as I want to use the `ipa` I already tested via Testflight. So it's already uploaded to iTC.

```ruby
  desc "Deploy a new version to the App Store"
  lane :appstore do
    ensure_git_status_clean
    deliver(submit_for_review: false, automatic_release: false)
  end
```

I found out the only way to prevent `ipa` uploading is to **not define the path to the ipa** when calling deliver. However when using `fastlane` **it automatically detects the `ipa` in my project directory**.

Do I have to use `deliver(ipa: "")`?

**Comment by funkenstrahlen** [comment]
Is it just `skip_binary_upload: true`? Why is this so hard to find?

**Comment by TKBurner** [comment]
Hi @funkenstrahlen! Thanks for following up. Yup, that's how you do it. To see the options available for an action just type fastlane action 'action name'. For example: fastlane action deliver

Thanks!
