### ISSUE TITLE
My name from app_review_information in Deliverfile is displayed outside boxes in ITC

### ISSUE THREAD

**Issue by funkenstrahlen** [fastlane/fastlane#4381]
### New Issue Checklist

- [done] Updated fastlane to the latest version
- [done] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have added this to my `Deliverfile`:

```ruby
app_review_information(
  first_name: "Stefan",
  last_name: "Trauth",
  ...
)
```

After running `fastlane deliver` I see this in ITC:

![screen shot 2016-04-27 at 11 38 13](https://cloud.githubusercontent.com/assets/144173/14848173/d0da079c-0c6c-11e6-93ff-c9482cac4dd3.png)

I expected **the name to be inside the boxes**.

**Comment by TKBurner** [comment]
@funkenstrahlen Thanks for reaching out. This seems like it is related to the way the page is rendering an not a Fastlane issue. Does it work on an app that you haven't used Fastlane for? Thanks!

**Comment by funkenstrahlen** [comment]
I am sorry I can not test that. I only have this app in ITC at the moment.

**Comment by TKBurner** [comment]
@funkenstrahlen Thanks for following up. Can you let me know if it affects other browsers? If it doesn't can you let me know what browser you are using. Thanks!

**Comment by funkenstrahlen** [comment]
I just checked. It happens both in Safari (Version 9.1 (11601.5.17.1)) and Chrome(50.0.2661.86).

**Comment by TKBurner** [comment]
@funkenstrahlen Thanks for following up. If this isn't reproducible on our end it's going to be hard to investigate. Can you test again with a blank app? You can always remove it from iTC later.

Thanks!
