### ISSUE TITLE
Snapshot isn't always waiting for loading indicator to disappear

### ISSUE THREAD

**Issue by crazyjooe** [fastlane/fastlane#4384]
After generating snaps with Snapshot 1.12.1, I found out that sometimes it randomly skips waiting for loading indicator in status bar to disappear, which leads to screenshots with placeholders, not the desired images.
I'm using SnapshotHelper's snapshot method, which by default should wait for indicator to disappear.
Most confusing part is that there is no pattern for that, it happened randomly on the same screen for different language/device combinations.
Never had issues like this before.

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!
