### ISSUE TITLE
Build on travis broke without changes

### ISSUE THREAD

**Issue by MP0w** [fastlane/fastlane#4390]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Not sure if it's a fastlane bug, the build broke at some point without changes. Works when using iOS 8.3 but not on iOS 9.3.
I tested on my local machine and works perfectly but on travis the build is failing. I enabled crash reports as suggested and I'm not able to identify the cause

##### Complete output when running fastlane, including the stack trace and command used

https://travis-ci.org/devlucky/Kakapo/jobs/126174356

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
default_platform :ios

platform :ios do

  desc "Build and Test"
  lane :ci_commit do
    scan(
      code_coverage: ENV["KKP_CODECOV"]
    )
  end

end

```

### Environment

See travis link

**Comment by vpolouchkine** [comment]
Can you repro this with a vanilla project?

**Comment by MP0w** [comment]
Actually is working again now... No idea what was going wrong

**Comment by vpolouchkine** [comment]
Alright, feel free to re-open if you run into this again and we'll dig some more.

**Comment by MP0w** [comment]
Hi, I'm still experiencing fails sometimes (mostly tvOS in the past days but I'm pretty sure it happened on iOS as well) -> https://travis-ci.org/devlucky/Kakapo/jobs/142811285

```
▸ Running script '[CP] Copy Pods Resources'
▸ Touching Kakapo\ tvOSTests.xctest
** TEST FAILED **
[16:48:35]: Exit status: 65
```

**Comment by MP0w** [comment]
@vpolouchkine I cannot re-open the issue myself
