### ISSUE TITLE
[sigh] Resigning without explicit entitlements looses keychain access group information

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4397]
### New Issue Checklist

- [x] Updated sigh to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

#### Scenario 1: Resigning Expired Enterprise IPA

Input:
- Expired IPA built for Enterprise distribution (provisioning profile has expired)
  - IPA was codesigned with entitlements that included `keychain-access-group` value like this:
  
![image](https://cloud.githubusercontent.com/assets/350654/14873115/36007cb8-0d36-11e6-9505-0e12c44882a7.png)

- New provisioning profile
  - New provisioning profile has `keychain-access-group` value as follows:
![image](https://cloud.githubusercontent.com/assets/350654/14873120/4ae6a83c-0d36-11e6-9fa3-96187e8cc260.png)
  - This is standard for provisioning profiles to look like this
- **No original entitlements file**
  - Why this is the case is another question, let's assume this is the situation we have to deal with.

When resigning with `sigh resign`, the `resign.sh` script doesn't find entitlements and extracts them from provided provisioning profile. The resigned IPA then contains keychain access group value different from the original IPA.

As a result, new IPA will not be able to access shared keychain values created by previous IPA. This is serious issue and will show up while testing upgrade scenario.

Detailed picture:
![slide2](https://cloud.githubusercontent.com/assets/350654/14873158/c6e35fe8-0d36-11e6-9764-680ec7a06e74.png)

#### Scenario 2: Resigning Enterprise IPA for App Store distribution

This scenario is similar to Scenario 1. The only difference is that IPA is now resigned for App Store distribution, changing bundle identifier, app prefix, team ID and other values in the process.

Here again, the new IPA will have keychain access group like `APPSTORETEAMID.*` and will be incompatible with previous App Store version, which was resigned by another script, not `sigh`.
![slide3](https://cloud.githubusercontent.com/assets/350654/14873188/2a2873c2-0d37-11e6-9b8b-bbe9a9ca7c45.png)

### Proposed Fix

The proposed fix is to extract entitlements both from new provisioning profile and from current app.
Extracting entitlements form the app is possible with command like this:
 `/usr/bin/codesign -d --entitlements entitlements.plist Payload/MyApp.app`.

The provisioning profile entitlements `keychain-access-group` entry should then be replaced with the value from the app's entitlements.

Next, the app identifier prefix in keychain access group needs to be replaced with value from provisioning profile's entitlements. This is important when resigning from Enterprise to App Store.

Overview:
![slide4](https://cloud.githubusercontent.com/assets/350654/14873254/ca41b436-0d37-11e6-84c2-fddedcb2f7c6.png)

### Environment

sigh version: `1.6.1`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by vpolouchkine** [comment]
Thanks for the detailed writeup, we'll take a look.

**Comment by asfalcone** [comment]
@mgrebenets This explanation is 💯 ! It would be awesome if you put up a PR for this. 

Getting some input on the proposed solution (as well as the PR) from @baarde, @lacostej, or @zats would be great, as they have some history with this code.

**Comment by mgrebenets** [comment]
I'm trying to put up a PR together. Will share after testing it internally with our app.

**Comment by mgrebenets** [comment]
So to recap there’s a mismatch between entitlements extracted from provisioning profile (left) and entitlements from the app (right)

![entitlementsdiff](https://cloud.githubusercontent.com/assets/350654/15032040/de4ed134-12a0-11e6-812c-2a8a991ab75e.png)

As seen in the diff, entitlements from profile have nothing but wildcards, while the app has concrete values.

To avoid this issue a developer should provide entitlements file explicitly whenever possible.

In case that’s not possible, sigh should extract entitlements from the app and combine them with entitlements from profile.

The solution is to transfer all key-value pairs from app to profile entitlements.

<img width="1147" alt="entitlementstransfrer" src="https://cloud.githubusercontent.com/assets/350654/15031990/8a8dd40a-12a0-11e6-8b27-f86f3b43c896.png">

Just copying over plist entries is not enough though. We have to account for situations when the app is resigned from Enterprise to App Store distribution, that means all or any of the following can change:

- Bundle ID
- App ID (and App Identifier Prefix)
- Team ID

The solution in #4512 will patch either app identifier prefix or team identifier for each entitlement.
We can’t just copy over first, then replace old app ID and old team ID with new values.
The reason is that for the original IPA the app ID and team ID might be the same, e.g. `ABCD`.
But for the App Store profile, the app ID can be different from team ID, in fact, I am working with apps like that right now.

So we have to say something like this:

- “for keychain-access-group key replace old APP ID with new APP ID"
- “for com.apple.developer.ubiquity-kvstore-identifier replace old TEAM ID with new TEAM ID"

If a certain entitlement uses both app ID and team ID (e.g. `$(TeamIdentifierPrefix)$(AppIdentifierPrefix)$(CFBundleIdentifier)` - the setup is too complex for sigh to handle at the moment and developers should provide these tricky entitlements explicitly when resigning.

Anyway, to implement this replacement logic the `|APP_ID` and `|TEAM_ID` “rules” are used in the script.

After all the entitlements have been transferred over and patched, the last fix is to replace old bundle ID with new bundle ID.

Finally, the new patched entitlements are used for code signing.

**Comment by TKBurner** [comment]
@mgrebenets Thanks so much for working on this! Let us know when you are ready for a PR review 👍

**Comment by asfalcone** [comment]
PR is in review #4512 👍

**Comment by mgrebenets** [comment]
I guess I need to leave a comment to keep it alive :)
A new PR #5130 was raised. The changes are additive and non-breaking this time.

**Comment by asfalcone** [comment]
Yep, sorry for the delay. This one is on my radar!

**Comment by mgrebenets** [comment]
Fixed in #5130.

**Comment by TKBurner** [comment]
@mgrebenets As always thanks! Hope you have a great weekend 👍 💯 💯
