### ISSUE TITLE
Environmental Variables with Jenkins Slave

### ISSUE THREAD

**Issue by aengel12** [fastlane/fastlane#4399]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When i start fastlane with jenkins on an jenkins slave, it doesn't find the env variables. If i start the same command on the server, there is no problem.
If i write "export XXX=abc" in the jenkins terminal, fastlane found XXX, but when i write it in the .bash_profile, the script doesn't found it.
The script can't find the variables also when i write a script at the server and start the script with jenkins.
Did anyone know the problem and has a solution?!

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.82.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by TKBurner** [comment]
Hi @aengel12! Great to hear from you. Can you share the full output when you run a command that you'd expect these variables to be inherited. Also can you share your your .env file or are you only using a .bashrc file?

**Comment by aengel12** [comment]
The output is configured by myself, if there is no var it prints "set the var XYZ"
I have no .env file, i use the ~/.bash_profile
and there is only
export XYZ=test
thanks a lot

**Comment by TKBurner** [comment]
Hi @aengel12! Thanks for following up. I'd suggest using an .env file as it's more reliable and will definitely suit your use case. Can you try that out and let me know how it goes?

**Comment by aengel12** [comment]
it works great, thanks
also i found a way to use the .bash_profile
i have t run the command
source ~/.bash_profile 
this also run
thanks a lot for the help

**Comment by TKBurner** [comment]
@aengel12 Awesome! So glad to hear you are up and running. Thanks for checking out Fastlane!
