### ISSUE TITLE
Fetch data from Itunes Connect Analytics

### ISSUE THREAD

**Issue by botmane** [fastlane/fastlane#4406]
Hello,

Is it possible to use Spaceship to query Itunes connect Analytics Data: For example "Daily Number of downloads"?

Thank you,

Otmane

**Comment by TKBurner** [comment]
Hi @botmane Thanks for reaching out. You can see all fields available by running this command:

![image](https://cloud.githubusercontent.com/assets/1987108/14919705/0583cbf4-0df8-11e6-9fef-7e25051d0089.png)

**Comment by KrauseFx** [comment]
Hey, jumping in here, it seems like some contributors already started working on this, I replied over here https://github.com/fastlane/fastlane/issues/4801#issuecomment-221126006
