### ISSUE TITLE
Create a `set_pod_key` action

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#4408]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

There's already a `verify_pod_keys` action today, but no `set_pod_key` one. We should fix that! 🔑 

If this is a wanted addition to fastlane, I can work on this on the next few days. 

### Environment

fastlane version (run `fastlane -v`): fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yep

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by TKBurner** [comment]
@marcelofabri Thanks for suggesting this! I'm going to send it out to the team as a PR proposal 👍

**Comment by KrauseFx** [comment]
@marcelofabri Are you working on this? If so we can remove the `help wanted` tag, so that nobody works on it on the same time

**Comment by marcelofabri** [comment]
@KrauseFx Yes, I'm working on this 👍 

Expect a PR soon!

**Comment by TKBurner** [comment]
@marcelofabri Thanks for letting us know and for working on this 👍 We'll work with you on the PR!
