### ISSUE TITLE
import lane not works with absolute and relative paths

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#441]
I tried to use fastfile as I described in  #439:
I added `import "~/.fastlane/UserFastfile"`

But this syntax not works (fastlane try to append it to current path):

`/Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.12.0/lib/fastlane/fast_file.rb:26:in `eval': Could not find Fastfile at path '/Users/username/repo/appname/fastlane/~/.fastlane/UserFastfile' (RuntimeError)`

**Comment by skywinder** [comment]
Hmmm.
`import "../../../.fastlane/UserFastfile"` syntax also not works.

Got error:

`/Users/user/.rvm/gems/ruby-2.1.5@global/gems/fastlane-1.12.0/lib/fastlane/fast_file.rb:26:in \`eval\': Could not find Fastfile at path '/Users/username/repo/appname/fastlane/../../../.fastlane/UserFastfile' (RuntimeError)`

**Comment by KrauseFx** [comment]
Oh, it looks like `~` is not properly resolved to your home directory. I'll work on a fix.

**Comment by skywinder** [comment]
@KrauseFx As comment after `../../../.fastlane/UserFastfile` syntax also not works.

**Comment by KrauseFx** [comment]
Oh yes, it is working: https://github.com/KrauseFx/snapshot/blob/master/fastlane/Fastfile. Keep in mind `.` is the directory of the `Fastfile` itself, not the folder you're currently in.

**Comment by KrauseFx** [comment]
That's why the error message should print out the absolute path

**Comment by skywinder** [comment]
Yes, I remember it.

Seems like it just append to path:
`/Users/username/repo/appname/fastlane/../../../.fastlane/UserFastfile' (RuntimeError)`

but command

`open /Users/username/repo/appname/fastlane/../../../.fastlane/UserFastfile` opens file correctly. 

So, the path is correct.

**Comment by JaviSoto** [comment]
I'm going to go ahead and close this issue for now since it's been inactive for a long time. Feel free to reply if you'd still like to get some help with this and we'll reopen it!

**Comment by mgrilloteravisiongames** [comment]
Hi all!! first of all, thank you for this wonderful tool, It has allowed me to save a lot of time building our applications. I'm trying to use pilot to upload into testflight a currently baked ipa, so I tried using:

pilot(ipa:"~/Builds/Project/project.ipa")

And it failed with:

Could not find ipa file at path '~/Builds/Project/project.ipa'

Same thing happened with the testflight lane. I'm using a CI server which handles this, and the ~ helped me a lot in setting up much of the directions withing our system, it would be very tricky to change that into absolute paths, how do you suggest to handle this?

**Comment by vpolouchkine** [comment]
@mgrilloteravisiongames Please open a new issue and format it per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md. Thanks.
