### ISSUE TITLE
exportArchive: Symbols tool failed

### ISSUE THREAD

**Issue by maximkhatskevich** [fastlane/fastlane#4413]
When I use "gym", it archives my build, says "Archive Succeeded", but then I'm getting an error and lane stops execution. See screenshot attached. Archive on it's own seems to be fine, it appears to be full-size in Finder.

![screen shot 2016-04-28 at 19 01 36](https://cloud.githubusercontent.com/assets/2624646/14906746/02665fba-0d74-11e6-878b-cbbdff121e94.png)

Any ideas what happens? I never had such problems, looks like it started to happen after I updated to latest version (1.82.0-1.83.0).

**Comment by TKBurner** [comment]
Hi @maximkhatskevich Thanks for reaching out. Can you add the --verbose flag to your lane and share the output? That'll help looking into this 👍

**Comment by maximkhatskevich** [comment]
Okay, will do that shortly. Small note: the archive is available in Xcode Organizer, but gym does not export it target folder (I specified custom path to export dSYM and ipa).

**Comment by maximkhatskevich** [comment]
It looks like "gym_output" failes, not "gym" core. Here is the part of output that contains error description.

`
INFO [2016-04-29 12:07:26.07]: $ /usr/bin/xcrun /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1vsm7vd_config.plist' -archivePath '/Users/maxim/Library/Developer/Xcode/Archives/2016-04-29/Vango-Staging_6.2.2.3 2016-04-29 12.03.20.xcarchive' -exportPath '/var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1pve2c7.gym_output' 
INFO [2016-04-29 12:07:26.26]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1vsm7vd_config.plist -archivePath '/Users/maxim/Library/Developer/Xcode/Archives/2016-04-29/Vango-Staging_6.2.2.3 2016-04-29 12.03.20.xcarchive' -exportPath /var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1pve2c7.gym_output
INFO [2016-04-29 12:07:26.55]: ▸ 2016-04-29 12:07:26.555 xcodebuild[14374:147565] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/Vango-Staging_2016-04-29_12-07-26.554.xcdistributionlogs'.
INFO [2016-04-29 12:07:26.58]: ▸ 2016-04-29 12:07:26.586 xcodebuild[14374:147565] [MT] DeveloperPortal: Using pre-existing current store at URL (file:///Users/maxim/Library/Developer/Xcode/DeveloperPortal%207.3.db).
INFO [2016-04-29 12:08:02.37]: ▸ 2016-04-29 12:08:02.378 xcodebuild[14374:147565] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7f9a1e4133c0>: Error Domain=IDEFoundationErrorDomain Code=1 "Symbols tool failed" UserInfo={NSLocalizedDescription=Symbols tool failed}
INFO [2016-04-29 12:08:02.37]: ▸ error: exportArchive: Symbols tool failed
INFO [2016-04-29 12:08:02.37]: ▸ Error Domain=IDEFoundationErrorDomain Code=1 "Symbols tool failed" UserInfo={NSLocalizedDescription=Symbols tool failed}
INFO [2016-04-29 12:08:02.38]: ▸ ** EXPORT FAILED **
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1vsm7vd_config.plist -archivePath '/Users/maxim/Library/Developer/Xcode/Archives/2016-04-29/Vango-Staging_6.2.2.3 2016-04-29 12.03.20.xcarchive' -exportPath /var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1pve2c7.gym_output
2016-04-29 12:07:26.555 xcodebuild[14374:147565] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/Vango-Staging_2016-04-29_12-07-26.554.xcdistributionlogs'.
2016-04-29 12:07:26.586 xcodebuild[14374:147565] [MT] DeveloperPortal: Using pre-existing current store at URL (file:///Users/maxim/Library/Developer/Xcode/DeveloperPortal%207.3.db).
2016-04-29 12:08:02.378 xcodebuild[14374:147565] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7f9a1e4133c0>: Error Domain=IDEFoundationErrorDomain Code=1 "Symbols tool failed" UserInfo={NSLocalizedDescription=Symbols tool failed}
error: exportArchive: Symbols tool failed

Error Domain=IDEFoundationErrorDomain Code=1 "Symbols tool failed" UserInfo={NSLocalizedDescription=Symbols tool failed}

** EXPORT FAILED **
ERROR [2016-04-29 12:08:02.40]: Exit status: 70
WARN [2016-04-29 12:08:02.42]: Variable Dump:
INFO [2016-04-29 12:08:02.42]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios staging", :GIT_REPO_WAS_CLEAN_ON_START=>true, :BUILD_NUMBER=>"6.2.2.3", :VERSION_NUMBER=>"6.2.2-alpha.3"}
ERROR [2016-04-29 12:08:02.42]: Error packaging up the application
INFO [2016-04-29 12:08:02.42]: Successfully generated documentation to path '/Users/maxim/Dropbox (Personal)/dev/Vango-iOS/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | ensure_git_status_clean             | 0           |
| 4    | get_build_number                    | 1           |
| 5    | get_version_number                  | 0           |
| 6    | prompt                              | 7           |
| 7    | prompt                              | 5           |
| 8    | ensure_git_status_clean             | 0           |
| 9    | increment_version_number            | 0           |
| 10   | increment_build_number              | 0           |
| 11   | commit_version_bump                 | 0           |
| 12   | gym                                 | 287         |
+------+-------------------------------------+-------------+

ERROR [2016-04-29 12:08:02.43]: fastlane finished with errors
/Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Error packaging up the application (FastlaneCore::Interface::FastlaneError)
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/gym/error_handler.rb:93:in `handle_package_error'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/gym/runner.rb:119:in `block in package_app'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.42.1/lib/fastlane_core/command_executor.rb:85:in `call'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.42.1/lib/fastlane_core/command_executor.rb:85:in `execute'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/gym/runner.rb:115:in `package_app'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/gym/runner.rb:19:in `run'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/gym/manager.rb:10:in `work'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/actions/gym.rb:22:in `run'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:131:in `block (2 levels) in parsing_binding'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.42.1/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/bin/fastlane:168:in `run'
	from /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane-1.83.0/bin/fastlane:174:in `<top (required)>'
	from /Users/maxim/.rbenv/versions/2.2.4/bin/fastlane:23:in `load'
	from /Users/maxim/.rbenv/versions/2.2.4/bin/fastlane:23:in `<main>'
`

**Comment by maximkhatskevich** [comment]
Any updates on this please?

**Comment by TKBurner** [comment]
Hi @maximkhatskevich! Thanks for following up. Can you run 

` /usr/bin/xcrun /Users/maxim/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/gym-1.6.2/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1vsm7vd_config.plist' -archivePath '/Users/maxim/Library/Developer/Xcode/Archives/2016-04-29/Vango-Staging_6.2.2.3 2016-04-29 12.03.20.xcarchive' -exportPath '/var/folders/74/mqryd6310bn_tzwy1jh_9sb80000gn/T/gym20160429-2263-1pve2c7.gym_output' `

Let me know if that succeeds. Thanks!
