### ISSUE TITLE
Allow xcode_select to use a version requirement

### ISSUE THREAD

**Issue by oysta** [fastlane/fastlane#4414]
### Issue Description

At Atlassian we have build agents that have multiple versions of Xcode installed and projects that build on these agents that have different Xcode version requirements. There's a single reference in the existing Fastlane documentation that refers to using a `version` parameter with `xcode_select`, however that action does not support such a parameter (the `xcode_install` action does of course).

We've been using a patch internally that allows us to use a `Gem::Requirement` syntax for specifying acceptable versions of Xcode.  We locate all installed versions via the `xcode-install` gem and find the best match for the requirement.

```ruby
xcode_select version: '~> 7.2.0'
```

I wonder whether this would be useful to include in the main Fastlane distribution?

I have an implementation at 722626f642aaa1f01a527e647bb956f6183ad286

**Comment by TKBurner** [comment]
@oysta Thanks for reaching out. I think we'd be happy to see a PR on this 👍 I'm going to circulate it to see if there is any other feedback from the internal team. Have a great weekend!

**Comment by KrauseFx** [comment]
Being worked on with https://github.com/fastlane/fastlane/pull/4421, thanks @oysta 👍

**Comment by oysta** [comment]
This was implemented in #4421

**Comment by TKBurner** [comment]
@oysta Thanks for updating! Really glad to hear it got merged. Thanks for contributing and have an awesome week!
