### ISSUE TITLE
Add action for writing 'properties' files

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/fastlane#4415]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Needed an action to output a Java properties file for consumption by external tools and Jenkins.

Here's one I prepared earlier #4380

**Comment by TKBurner** [comment]
Hi @Ashton-W! Thanks for reaching out. I'm going to circulate this with the internal team and then we'll update on this thread. We really appreciate you being part of our community 👍

**Comment by jcampbell05** [comment]
This could maybe be a plugin

**Comment by TKBurner** [comment]
Thanks @jcampbell05! We'll close this out, but if someone wants to work on a plugin we'd be happy to see it! 👍
