### ISSUE TITLE
[Pilot] Multiple Platform Build Support/tvOS Universal Apps

### ISSUE THREAD

**Issue by bassrock** [fastlane/fastlane#4427]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When uploading builds to a universal tvOS app, I constantly run into the issue: 
```ruby
pilot/lib/pilot/build_manager.rb:91:in `wait_for_processing_build': [!] undefined method `train_version' for nil:NilClass (NoMethodError)
```

When traced down I believe a contributing factor is I can submit two ipas, with the same build number, version and app id in order for it to be a universal app on the App Store. Currently Pilot only filters for processing builds with the App Version, Build Number and App Id, but it should also be filtering builds by platform, which is available in each respective build data.

Another contributing issue to this could be that when I run:
```shell
bundle exec pilot builds
```
Not all of my builds show. For example here is the iTunes Connect Data and the respective pilot output:
![screen shot 2016-05-01 at 2 37 27 am](https://cloud.githubusercontent.com/assets/1010384/14941120/ad31e054-0f45-11e6-90cc-9049dc34e52d.png)
![screen shot 2016-05-01 at 2 38 03 am](https://cloud.githubusercontent.com/assets/1010384/14941122/c07f204a-0f45-11e6-908f-2d5cb04df713.png)

It looks as though the ```pilot list``` command is only showing one of the build trains which in this case is the tvOS one. When I currently encounter the above issue it is when I try to upload the iOS version so I am wondering if it is because pilot is only recognizing the tvOS build train.

**Comment by bassrock** [comment]
Ok so I think I found the line that is causing the issue:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/build_train.rb#L54

In my app I like to keep the Major, Minor version the same on iOS and on tvOS so the above line is overriding the selected app train, not taking into account the applications platform.

**Comment by bassrock** [comment]
And actually I think it goes down to adding a platform attribute to the tunes/application.rb

**Comment by TKBurner** [comment]
@bassrock Always great to hear from you. Thanks for the PRs we'll work on them with you to get them merged 👍

**Comment by vfog** [comment]
Just want to add that the issue with Spaceship is having impacts elsewhere as well. For example after uploading a tvOS build to test flight any calls to the `latest_testflight_build_number` action are now returning the latest tvOS build rather than the latest iOS build.

**Comment by bassrock** [comment]
@TKBurner sounds good! Let me know what I need to do to get these merged!!

**Comment by bassrock** [comment]
@KrauseFx looks like this got closed by #4448, however that didn't actually resolve this as it requires 3 pull requests dude to modifying 3 of the fastlane gems.

**Comment by TKBurner** [comment]
@bassrock Great to hear from you again! Thanks for pointing this out. Reopened until your two other PRs get merged. Really glad to have you working with us 👍

**Comment by bassrock** [comment]
Thanks @TKBurner! What needs to be done to get the rest of this in?

**Comment by TKBurner** [comment]
@bassrock Thanks for following up. I sent a message out to the core team so we can keep these moving. We are always really happy to work with you! (You've become a hero of sorts among the core team 👍 )

**Comment by bassrock** [comment]
@TKBurner thanks! Brightens my day to hear that!! Can't wait to hear back on the PRs

**Comment by bassrock** [comment]
This can be tested by pointing your gems to use: https://github.com/bassrock/fastlane/tree/platform-support  I have all my open pull requests for platform support merged into there.

**Comment by TKBurner** [comment]
@bassrock Thanks for sharing this branch. I'm working with the team to get your PRs merged 👍

**Comment by bassrock** [comment]
Wanted to add here that I have successfully submitted a universal tvOS and iOS app that uses the same versioning with these fixes.

**Comment by TKBurner** [comment]
@bassrock Awesome! I'm going to ping this over to the core team. Thanks 👍
