### ISSUE TITLE
only set default crashlytics_path value for ios

### ISSUE THREAD

**Issue by TaopaiC** [fastlane/fastlane#4430]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]
(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a react-native project for both android and ios apps.
The default value of `crashlytics_path` always got "ios/Crashlytics.framework" even if I build for android platform.
Another issue is submitting ios ipa if I run android build task after ios build task.

The root cause are:
* the default value of `crashlytics_path` is trying to find "./**/Crashlytics.framework"
* the default value of `ipa_path` is trying to find "*.ipa"

I made a PR #4429 try to
* finding "./**/Crashlytics.framework" for `crashlytics_path` in `generate_ios_command` since it only runs for ios platform.
* set default `apk_path` value only for android and default `ipa_path` value only for ios/null in crashlytics action

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.83.0"

default_platform :ios

platform :android do
  lane :beta do
    gradle(
      project_dir: './android',
      task: "assembleRelease"
    )
    crashlytics(
      apk_path: 'android/app/build/outputs/apk/app-release.apk'
    )
  end
end

platform :ios do
  lane :beta do
    increment_build_number(
      xcodeproj: './ios/news.xcodeproj'
    )
    gym(
      scheme: 'news',
      project: './ios/news.xcodeproj'
    )
    crashlytics()
  end
end

```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`): use `bundle exec fastlane`

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?: use `rbenv`

**Comment by TKBurner** [comment]
Hi @TaopaiC! Thanks for reaching out. We'll work with you on your pull request! 👍

**Comment by KrauseFx** [comment]
Fixed with https://github.com/fastlane/fastlane/pull/4429
