### ISSUE TITLE
Deliver - submit for review

### ISSUE THREAD

**Issue by nAviram** [fastlane/fastlane#4431]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

I just tried to deliver with --submit_for_review parameter - which didn't work.
I tried it with different variations:
deliver --submit_for_review
deliver --skip_metadata --skip_screenshots --ipa fileToUpload.ipa --submit_for_review
deliver --ipa fileToUplaod.ipa --submit_for_review

in all cases - I get:
_[17:12:16]: Submitting the app for review...
[17:12:24]: Successfully submitted the app for review!
_

but when I get in to iTuneConnect - the app is still in "Prepare for Submission" status.

Another thing I noticed - there is no parameters for "What's New in This Version" and also parameters regarding submission: *Export Compliance, **Advertising Identifier
 
Or did I miss something?

Thanks.

### Environment

deliver version: deliver 1.11.2
fastlane version (run `fastlane -v`): fastlane 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no.
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no.

**Comment by TKBurner** [comment]
@nAviram Great to hear from you again. Can you try setting this parameter to true rather than just including it as a flag? That should get you up and running 👍

**Comment by nAviram** [comment]
@TKBurner  - I just tried now again, added this line with the flag to the Deliverfile:
**_submit_for_review true
_**

I run the **deliver** command - and the deliver started to run, all looking good (screenshots, metadata, etc') and even wrote the submission succeeded:
**_[18:07:28]: Saving changes
[18:07:42]: Successfully uploaded screenshots to iTunes Connect
[18:07:42]: Price Tier unchanged (tier 0)
[18:07:48]: Uploading app icon...
[18:07:56]: Finished the upload to iTunes Connect
[18:07:57]: Selecting the latest build...
[18:07:58]: Selecting build 1.6.3 (2)...
[18:07:59]: Successfully selected build
[18:07:59]: Submitting the app for review...
[18:08:06]: Successfully submitted the app for review!_**

BUT, than I go to the iTunesConnect - and the App is still on **"Prepare for Submission"** status :(

**Comment by TKBurner** [comment]
@nAviram Thanks for working with me. Can you add the --verbose flag on to the end of your command. I want to see what could be causing this issue. Thanks!

**Comment by nAviram** [comment]
I tried it again with --verbose.
log is attached:
[Log-submit_for_review.txt](https://github.com/fastlane/fastlane/files/257340/Log-submit_for_review.txt)

And I want to rise my question once again - there is no parameters for "What's New in This Version" and also parameters regarding submission: Export Compliance, *Advertising Identifier...

I also noticed that there are 'missing beta entitlements' on the external testing status ([I've opened another issue about it - regarding gym](https://github.com/fastlane/fastlane/issues/4434#issuecomment-217981289))

**Comment by TKBurner** [comment]
Hi @nAviram! Thanks for working with me. Have you tried deliver --submit_for review true?

**Comment by nAviram** [comment]
still not working.

I run the command:
deliver --verbose --ipa /path/to/app/app.ipa --submit_for_review true

![screen shot 2016-05-16 at 3 43 14 pm](https://cloud.githubusercontent.com/assets/6167894/15291332/f92b0d86-1b85-11e6-8e1f-a778c5ff577d.png)

when I log in to iTunesConnect - it's still on "Prepare for Submission" status.

**Comment by TKBurner** [comment]
Hi @nAviram Thanks for following up. Can you run fastlane run update_fastlane? Also can you set force parameter to true? 

Thanks! 👍

**Comment by hjanuschka** [comment]
@nAviram 
i had the same issue and it was because of missing `submission_information`

```
deliver(submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    });
```



and/or in deliverfile

```
submission_information({
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    });
```


you have to change the variables to fit your application ;).


the documentation about submission_information is here https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md#submission_information

**Comment by nAviram** [comment]
OHHH!!!! THANK YOU!!!! how did I miss that?!
and I already asked **twice** about it (hmmm hmmm @TKBurner ) - because it makes no sense that this information is missing...
I'll try it out and update. THANKS again!

**Comment by TKBurner** [comment]
@nAviram Glad to hear you got up and running!

@hjanuschka Thanks for stepping in here. I really appreciate it 👍

**Comment by owurman** [comment]
Updating my submission_information seemed to fix the same issue for me, too. What I had was slightly outdated. So if you are hitting this and thinking to yourself "but I have my submission information set up already!"... double check.

**Comment by TKBurner** [comment]
@owurman Awesome! Really glad to hear you got up and running! 👍
