### ISSUE TITLE
GYM - Conflict with the provisioning profiles

### ISSUE THREAD

**Issue by nAviram** [fastlane/fastlane#4434]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

I've found out there is a conflict with the existing provisioning profiles.

when I used the command:
 gym --clean --scheme scheme --output_directory /Users/aviram/projects/myProject --output_name fileToUpload.ipa --provisioning_profile_path /Users/aviram/projects/myProject/myProvisioningProfile.mobileprovision

It created the ipa file, but after I upload the file and go to the activity section in iTunesConnect - the "External Testing Status" is: **"Missing Beta Entitlement"**
And not surprisingly - once you download it - it doesn't install properly.

I've found out that if I **delete** those provisioning profiles from the iPhone Configuration Utility, and only keep them on the HD - it works just fine, and there is no Missing Beta Entitlement status...

### Environment

gym version: 1.6.2
fastlane version (run `fastlane -v`): 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no.

**Comment by TKBurner** [comment]
Hi @nAviram! Great to hear from you. It looks like you must be setting your provisioning profile path incorrectly. Are you sure the path you provided is the right one?

Thanks!

**Comment by nAviram** [comment]
Hi @TKBurner ! 
I doubled checked - and the provisioning profile path is set correctly. 
but I noticed 2 things: 
1. The gym is building the app even if the distribution certificates weren't open into the keychain resulting  its unable to install it after downloading the app from TestFairy
2. (and this I still didn't figured out) - I think that for accounts with several apps, it still creates this conflict - even though I wrote the gym command explicitly --provisioning_profile_path ...

I'm still investigating trying to figure out exactly when or what causes it.

**Comment by TKBurner** [comment]
Hi @nAviram Thanks for following up. Are you using cert and sigh OR match before this? That'll help make sure the right provisioning profile is bundled. Let me know how it goes!

**Comment by nAviram** [comment]
No, I don't use cert Or sigh.

**Comment by KrauseFx** [comment]
Passing the provisioning profile path is deprecated (it should say so in the terminal output. So please define the provisioning profile in your Xcode project instead, as Xcode will pick the wrong one by default.

**Comment by KrauseFx** [comment]
Also, please share a screenshot of your code signing settings of your project

**Comment by nAviram** [comment]
Oh no!!  :P

Hi Felix! Thanks for your answer! 
passing the provisioning profile path was one of main reasons for us to use fastlane - it reduced the need to open xcode, so we could pass it on to our QA department for creating new apps (while us developers are pretending working on new features... :)
therefore our setup for code signing settings are on Automatic: (screenshot attached)
![screen shot 2016-05-17 at 10 16 33](https://cloud.githubusercontent.com/assets/6167894/15314099/78acb2e8-1c18-11e6-898b-c136b02e2330.png)

To our understanding after building several apps, we had success building apps with accounts that had only 1 app - so the xcode picked the only provisioning profile exists for the specific bundle ID (it does goes by bundle ID, right?)
And with those who had several - we had to choose the provisioning profiles explicitly. (how annoying)
I just checked again the output and didn't see it mentioned its deprecated. what I did see is the line:
"installing provisioning profile..." right after it.

so just to make things clear -
1. gym command actually ignores the provisioning profile path and picks up the provisioning profile by the bundle ID?
2. Does it takes the first certificate it finds?

**Comment by TKBurner** [comment]
@nAviram Thanks for following up. I'm circling back with the team to see about the matching in your second question and to get clarification about your first. We'll update this thread.

Thanks!

**Comment by KrauseFx** [comment]
If you look at the build output, it should tell you that the provisioning profile path is deprecated. The reason for that is that your app might have multiple targets, and `xcodebuild` can't know which target what profile it should use. 
So instead what you should do follow the [match guide](https://github.com/fastlane/fastlane/tree/master/match#setup-xcode-project) on how to setup your Xcode project to use environment variable. You can then either use [match](https://fastlane.tools/match) or pass your own provisioning profile UUIDs using environment variables.
This way you're explicit about what profile to use, and your build is reproducible 👍 

Let me know if that works for you

**Comment by nAviram** [comment]
Hi @KrauseFx ! Thanks for your reply.
our problem is we have multiple accounts, and I saw in Match guide that it said:
**_Support for multiple Apple accounts_**

but I didn't see any explanation or example of how it's done...

**Comment by KrauseFx** [comment]
@nAviram You can just run `match` and pass different Apple IDs. Make sure to pass a separate branch for each of your Apple IDs
