### ISSUE TITLE
Upload limit, and broken build isn't handled well by deliver command.

### ISSUE THREAD

**Issue by programmin1** [fastlane/fastlane#4443]
It seems Fastlane Deliver not only does not give an appropriate message where it hits the upload limit (try again in 1 day message). Furthermore it fails, continually trying again when later trying to submit-for-review a version that was uploaded, hit the upload limit, and requires a new version number because the current version is "duplicate" when uploaded, yet never shows up in the builds activity in iTunes-connect.

Similarly, if the build is stuck at "There was an error importing this build. View all builds in Activity." in the activity/ios/builds url screen, the Deliver command just continually says:
```
[16:59:00]: You can tweet: "iTunes Connect #iosprocessingtime x minutes"
[16:59:32]: Waiting iTunes Connect processing for build (versionnumber)... this might take a while...
[16:59:32]: 
[16:59:32]: You can tweet: "iTunes Connect #iosprocessingtime (x+1) minutes"
[17:00:04]: Waiting iTunes Connect processing for build (versionnumber)... this might take a while...
....
```
continually.

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by TKBurner** [comment]
Hi @programmin1! Thanks for reaching out. Can you run deliver --verbose and send the full output. Definitely want to take a look 👍

**Comment by programmin1** [comment]
Here are the steps - 
1) Upload a build that happens to trigger the "Upload limit reached". Let's say it were some version "1.2.3". Now the build 1.2.3 shows nowhere on iTunes Connect yet you can't upload that version ("Redundant Binary Upload").
2) Run:
```
deliver submit_build --verbose -u username@somewhere --skip_metadata --skip_binary_upload --skip_screenshots --submit_for_review -a IDoftheapp
```

Instead of detecting that this isn't even showing up on iTunesConnect, and showing that you have to create a new version number, deliver would endlessly wait after login and summary:

INFO [2016-05-04 14:27:41.70]: [32mFinished the upload to iTunes Connect[0m
INFO [2016-05-04 14:27:42.42]: Selecting the latest build...
INFO [2016-05-04 14:27:43.51]: Waiting iTunes Connect processing for build 1.2.3 (1.2.3)... this might take a while...
(message repeated again and again)
