### ISSUE TITLE
Fix session token header for 2fa

### ISSUE THREAD

**Issue by iltempo** [fastlane/fastlane#4453]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Apple renamed the session headers from `X-Apple-Web-Session-Token` to `X-Apple-Id-Session-Id` for two factor authentication requests. 2FA is broken as mentioned in #4391 and #4330.
PR:  #4452

### Environment

fastlane version (run `fastlane -v`): 

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
@iltempo Awesome! Thanks so much 👍 Really happy to see this fix come through. We'll work with you on the PR. Have a great day!
