### ISSUE TITLE
xcbuild-safe needs support for rbenv/bundler

### ISSUE THREAD

**Issue by robertjpayne** [fastlane/fastlane#4458]
🔑
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The xcbuild-safe wrapper adds vital wrapping support for users using rvm but not rbenv. Furthermore it doesn't undo the environment variable setup damage from Bundler.

##### Complete output when running fastlane, including the stack trace and command used

Related to #3193 depending on configuration various outputs but always failing after the compile is complete and when it tries to generate the ipa.

Fails mostly when xcodebuild is attempting to use `ipatool`

### Configuration Files

None, using `bundle exec gym` with various assortments of config but always doing an Enterprise export.

```
Subprocess.check_call([
      'bundle',
      'exec',
      'gym',
      '--clean',
      'false',
      '--include_symbols',
      'false',
      '--include_bitcode',
      'false',
      '--export_method',
      'enterprise',
      '--export_team_id',
      'REDACTED',
      '--codesigning_identity',
      'iPhone Distribution: REDACTED',
      '--scheme',
      'REDACTED',
      '--configuration',
      'Debug',
      '--output_directory',
      File.join(SRCROOT, 'Build/REDACTED'),
      '--output_name',
      'REDACTED.ipa',
      '--derived_data_path',
      File.join(SRCROOT, 'Build/REDACTED/DerivedData'),
])
```

### Environment

fastlane version (run `fastlane -v`): 
1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? 
rbenv

**Comment by robertjpayne** [comment]
#4456 resolves this issue

**Comment by TKBurner** [comment]
Hi @robertjpayne! Thanks for doing this work! We'll work with you on the PR. 👍

**Comment by KrauseFx** [comment]
Thanks, we also just pushed this:

---

Hey everyone, we just pushed a new _gym_ release with [gym 1.11.1](https://github.com/fastlane-old/gym/releases/tag/1.11.1), that should fix an error in `xcodebuild`. Xcode depends on system Ruby being used, and sometimes can't find the system gems. The new release should fix that error. Please disable the `use_legacy_build_api` flag, update to the latest version of _gym_ and give it a try. More information about the fixed error can be found here: https://github.com/fastlane/fastlane/issues/6495

Let us know if that fixes the issue for you. If it doesn't work still, please share the complete output with the latest version of _gym_ so we can further investigate the problem 👍 

Thanks everybody for helping resolve this issue  🚀
