### ISSUE TITLE
Unlock_keychain results in exit status 36 when running through jenkins

### ISSUE THREAD

**Issue by mkaiser30** [fastlane/fastlane#4460]
### Issue Description

I run fastlane on a jenins node. If I log in as user jenkins via ssh, fastlane does the job and builds the app. If the jenkins server logs in through ssh, the job fails and reports that unlock keychain fails with exit code 36. Does anyone has an idea how to solve this issue?

##### Complete output when running fastlane, including the stack trace and command used

[ios_continouos_dev] $ /bin/bash -l /var/folders/sx/9xfzmlzn4vj3bwf09frhfjb00000gq/T/hudson5912009002333101612.sh
[13:34:01]: [32m-------------------------------------------------[0m
[13:34:01]: [32m--- Step: Verifying required fastlane version ---[0m
[13:34:01]: [32m-------------------------------------------------[0m
[13:34:01]: fastlane version valid
[13:34:01]: [32m------------------------------[0m
[13:34:01]: [32m--- Step: default_platform ---[0m
[13:34:01]: [32m------------------------------[0m
[13:34:01]: [32mDriving the lane 'ios my_app_continuous' 🚀[0m
[13:34:01]: [32m-----------------------------[0m
[13:34:01]: [32m--- Step: unlock_keychain ---[0m
[13:34:01]: [32m-----------------------------[0m
[13:34:01]: [33m[33mVariable Dump:[0m[0m
[13:34:01]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios my_app_continuous"}
[13:34:01]: [31mShell command exited with exit status 36 instead of 0.[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | unlock_keychain                     | 0           |
+------+-------------------------------------+-------------+

[13:34:01]: [31mfastlane finished with errors[0m
[31m
[!] Shell command exited with exit status 36 instead of 0.[0m
Build step 'Shell ausführen' marked build as failure
Finished: FAILURE

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.66.0"

default_platform :ios

platform :ios do
  before_all do
#    git_status_clean
#    cocoapods
  end

  desc("Continuous Build for my app")
  lane :my_app_continuous do
    ENV['APP'] = "ch.my.app.name"
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '600'
    ENV['FL_UNLOCK_KEYCHAIN_PATH'] = 'login.keychain'
    ENV['FL_UNLOCK_KEYCHAIN_PASSWORD'] = 'password' 
    unlock_keychain
  end


  after_all do |lane|
  end

  error do |lane, exception|
  end
end
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
Hi @mkaiser30! Great to hear from you. Sorry to hear that you are running into this issue. Can you share the full output when you run this lane with the --verbose flag? I want to take a look and see what could be causing this. Thanks!

**Comment by mkaiser30** [comment]
Hi @TKBurner! Thanks for your response. Here is the output generated by executing this lane through jenkins.

INFO [2016-05-03 16:20:11.84]: [32m-------------------------------------------------[0m
INFO [2016-05-03 16:20:11.84]: [32m--- Step: Verifying required fastlane version ---[0m
INFO [2016-05-03 16:20:11.84]: [32m-------------------------------------------------[0m
INFO [2016-05-03 16:20:11.84]: fastlane version valid
INFO [2016-05-03 16:20:11.84]: [32m------------------------------[0m
INFO [2016-05-03 16:20:11.84]: [32m--- Step: default_platform ---[0m
INFO [2016-05-03 16:20:11.84]: [32m------------------------------[0m
INFO [2016-05-03 16:20:12.03]: [32mDriving the lane 'ios my_app_continuous' 🚀[0m
INFO [2016-05-03 16:20:12.03]: [32m-----------------------------[0m
INFO [2016-05-03 16:20:12.03]: [32m--- Step: unlock_keychain ---[0m
INFO [2016-05-03 16:20:12.03]: [32m-----------------------------[0m
WARN [2016-05-03 16:20:12.13]: [33m[33mVariable Dump:[0m[0m
INFO [2016-05-03 16:20:12.13]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios my_app_continuous"}
ERROR [2016-05-03 16:20:12.13]: [31mShell command exited with exit status 36 instead of 0.[0m
INFO [2016-05-03 16:20:12.13]: [32mSuccessfully generated documentation to path '/Users/jenkins/ci/workspace/customer/myApp/ios_continouos_dev/fastlane/README.md'[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | unlock_keychain                     | 0           |
+------+-------------------------------------+-------------+

ERROR [2016-05-03 16:20:12.17]: [31mfastlane finished with errors[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.0/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [31m[!] Shell command exited with exit status 36 instead of 0.[0m (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/helper/sh_helper.rb:47:in `sh_control_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/helper/sh_helper.rb:9:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/actions/unlock_keychain.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:17:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:168:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.83.0/bin/fastlane:174:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Shell ausführen' marked build as failure
Finished: FAILURE

**Comment by TKBurner** [comment]
Hi @mkaiser30! Thanks for following up. Can you let me know if you still run into this issue when you set the parameters manually in the unlock keychain action rather than using env? Thanks!

**Comment by mkaiser30** [comment]
Hi @TKBurner,

yes, unfortunately I get still the same error.

**Comment by TKBurner** [comment]
Hi @mkaiser30! Thanks for working with me. Can you share the output if you run fastlane run unlock_keychain? I want to see if this action fails on it's own or if it's due to context. Thanks!

**Comment by mkaiser30** [comment]
Hi @TKBurner,

thanks for helping me with this issue.

Here's the output, it's not too different from the above:
```shell
+ fastlane --verbose run unlock_keychain
INFO [2016-05-10 08:46:45.90]: [32m-----------------------------[0m
INFO [2016-05-10 08:46:45.90]: [32m--- Step: unlock_keychain ---[0m
INFO [2016-05-10 08:46:45.90]: [32m-----------------------------[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [31m[!] Shell command exited with exit status 36 instead of 0.[0m (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/helper/sh_helper.rb:54:in `sh_control_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/helper/sh_helper.rb:10:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/unlock_keychain.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:173:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:158:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/one_off.rb:36:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/one_off.rb:22:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Shell ausführen' marked build as failure
Finished: FAILURE
```

Again, the output if executed on an interactive shell session is different: 
```sh
fastlane --verbose run unlock_keychain
INFO [2016-05-10 09:05:52.05]: -----------------------------
INFO [2016-05-10 09:05:52.05]: --- Step: unlock_keychain ---
INFO [2016-05-10 09:05:52.05]: -----------------------------
INFO [2016-05-10 09:05:52.25]: Result: [nil, "", ""]
```

**Comment by mkaiser30** [comment]
I enabled log in unlock_keychain method for line 27. Now the output is the following (shortened):

```shell
INFO [2016-05-10 11:05:16.23]: [32m-----------------------------[0m
INFO [2016-05-10 11:05:16.23]: [32m--- Step: unlock_keychain ---[0m
INFO [2016-05-10 11:05:16.23]: [32m-----------------------------[0m
INFO [2016-05-10 11:05:16.26]: [4m[36m$ security unlock-keychain -p password /Users/jenkins/Library/Keychains/login.keychain[0m[0m
INFO [2016-05-10 11:05:16.30]: [4m[36m$ security set-keychain-settings /Users/jenkins/Library/Keychains/login.keychain[0m[0m
INFO [2016-05-10 11:05:16.40]: ▸ [35msecurity: SecKeychainSetSettings /Users/jenkins/Library/Keychains/login.keychain: User interaction is not allowed.[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [31m[!] Exit status of command 'security set-keychain-settings /Users/jenkins/Library/Keychains/login.keychain' was 36 instead of 0. (FastlaneCore::Interface::FastlaneError)
security: SecKeychainSetSettings /Users/jenkins/Library/Keychains/login.keychain: User interaction is not allowed.

...

```

So it seems that security set-keychain-settings is failing.

**Comment by mkaiser30** [comment]
If I try to unlock other keychains than login.keychain, unlock_keychain does not fail. So it must be something special with login.keychain.

I tried with a newly created keychain (jenkins.keychain), and it went throu, but then gym didn't found the identity. 

I also recreated login.keychain from scratch, but then it failed again with the same error.

**Comment by TKBurner** [comment]
Hi @mkaiser30! Thanks for following up. Are you accessing the keychain from the right account on your system? It looks like the permissions on your keychain might not be letting us read. Let me know what you find out! 👍

**Comment by mkaiser30** [comment]
So here is what I did (and it works, more or less)

I now use create_keychain to create a new keychain, then I import the certificates using import_certificate and when the build has finished I delete the keychain again. 

My certificates are all checked in into my repo and the passwords for the keys are set by environment variables.

I found a useful blog of Natan Rolnik (https://natanrolnik.me/2015/10/21/introduction-to-fastlane-and-integrating-it-with-circleci-to-deploy-beta-with-crashlytics-fabric/) from which I copied the Idea to automate this.

```ruby
  def import_certificates_temp_keychain
    return unless Helper.is_ci? # As in my local machine I don't need to import the certificates, only run if it's in the CI

    create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: ENV["KEYCHAIN_PASSWORD"]
    )

    import_certificate(
      certificate_path: ENV['CERT_PATH'],
      certificate_password: ENV['CERT_PASSWORD'],
      keychain_name: ENV["KEYCHAIN_NAME"]
    )

  end

  def delete_temp_keychain
    return unless Helper.is_ci?

    delete_keychain(
      name: ENV["KEYCHAIN_NAME"]
    )
  end
```

**Comment by TKBurner** [comment]
@mkaiser30 Very cool! That's a pretty awesome setup. I'm glad you found a solution. I'm going to go ahead and close this issue out. Hope that you have a wonderful week!
