### ISSUE TITLE
Unable to use fastlane init without an Apple Developer id

### ISSUE THREAD

**Issue by Palleas** [fastlane/fastlane#4462]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
It is not possible to use `fastlane init` without an Apple Developer id. As we don't use match or any of 
the magic tools to generate provisioning profiles and signing certificates, it would be cool to be able to use a flag or simply quit the setup when we don't enter an id.

Right now if we don't enter a developer email, the setup will keep asking for the username.

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane init
[10:36:23]: Detected iOS/Mac project in current directory...
[10:36:23]: This setup will help you get up and running in no time.
[10:36:23]: fastlane will check what tools you're already using and set up
[10:36:23]: the tool automatically for you. Have fun!
[10:36:23]: Created new folder './fastlane'.
[10:36:23]: xcrun xcodebuild -list -workspace './Show.xcworkspace'
Your Apple ID (e.g. fastlane@krausefx.com):
[11:42:59]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[11:42:59]: Starting login with user ''
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Username:
Username:
Username:
Username:
Username:
Username:
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
No.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv.

**Comment by TKBurner** [comment]
Hi @Palleas! Thanks for reaching out. Have you tried entering any string in that field and proceeding? You should be able to get up and running without this account. Thanks!

**Comment by Palleas** [comment]
Indeed, but that seems like a weird hack, I'd rather have a flag or be able to enter an empty string.

**Comment by ohwutup** [comment]
Hey @Palleas. thanks for raising this issue after our little discussion in Slack! For right now, we are going to keep this working as-is. You can definitely get fastlane up and running without running `init` by manually creating the necessary files. We will update this issue as soon as we get a chance to make the enhancement to accept a flag to skip the step or an empty string there. Thanks !!

**Comment by SandyChapman** [comment]
@ohwutup : Seems strange to close this issue without a resolution. I'd also like to see this implemented as I've just wasted 3 minutes out of my day finding this ticket in Git and writing a reply that could have been saved has this been had this simple change been implemented.

**Comment by TKBurner** [comment]
Hi @SandyChapman Thanks for following up on this. I've marked this as help wanted in case anyone from the community wants to submit a PR to clear up this behavior. Thanks!

**Comment by SandyChapman** [comment]
@TKBurner : Thanks. If I find some time and don't forget about this, I just may be the one to do it.

**Comment by TKBurner** [comment]
Awesome @SandyChapman!
