### ISSUE TITLE
Custom sections for the resulting HTML

### ISSUE THREAD

**Issue by dkk** [fastlane/fastlane#4465]
### Feature Description

There already is a nice distinction for different settings, such as languages and devices, but I think it would be nice to be able to define your own sections. 

I was thinking about extending the snapshot function in SnapshotHelper.swift from 
`snapshot(name: String, waitForLoadingIndicator: Bool = true)` 
to something like
`snapshot(name: String, waitForLoadingIndicator: Bool = true, htmlSection: String? = nil)`

then, all Screenshots with the same `htmlSection` value would get into the same section in the resulting html (as a subsection to the setting related sections).

Is this something that would be wanted?

**Comment by TKBurner** [comment]
Hi @dkk! Great to hear from you again. I'm going to mark this as help wanted to see if anyone else in the community is interested in this feature. If there is enough interest we will work with you on this thread.

Thanks! 👍

**Comment by ohwutup** [comment]
Going to close this issue for now as we decided not to merge the associated PR due to increased complexity in the Swift code. https://github.com/fastlane/fastlane/pull/5335#issuecomment-230799038
