### ISSUE TITLE
`deliver` action uses the same apple id as the previous action

### ISSUE THREAD

**Issue by kommen** [fastlane/fastlane#447]
I'm having this lane:

```ruby
lane :testflight do
  cert
  sigh
  deliver skip_deploy: true, beta: true, force: true
end
```

With no apple id provided to any of those actions via a setting or environment variable, I would expect to be asked for an apple id to use for each of the actions. However, it only asks to times: for `cert` and `sigh`. `deliver` then uses the apple id I provided for `sigh`. But I would need a different apple id to be used there.

When using the `deliver` action without the preceding `cert` and `sigh`, it asks for the apple id for `deliver` as I would expect.

I think this has to do with this: https://github.com/KrauseFx/fastlane/commit/7b5ceb45d7463d78e5506434fa0fae3912fb0168

The logout happens after `Deliverer` is initialized (which starts the upload), so `deliver` will use the apple id currently held by the `CredentialsManager`. The comment in the commit suggests the logout should happen before, so that `deliver` doesn't use the apple id from the previous action. Am I missing something?

**Comment by KrauseFx** [comment]
Unfortunately I've made the huge mistake to use a singleton as the `credentials_manager` back then when `deliver` was just `deliver` with no `fastlane`, `sigh`, etc.

I haven't yet found the time to rip it apart to clean this up. 

Is there a use case where you don't want to provide an Apple ID? Or is it just a concern you raise for new users who somehow forgot to provide an Apple ID

**Comment by kommen** [comment]
My use case would have been to specify the used Apple IDs via a `.env` file only, but when it is not present just ask for them. I can live with the current behavior, as I can work around it. But it is confusing I think.

**Comment by JaviSoto** [comment]
This is now possible :) Check out this doc! :D https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
