### ISSUE TITLE
Snapshot: know which language is being used?

### ISSUE THREAD

**Issue by JamaicanRumCream** [fastlane/fastlane#4471]
Is it possible to know what language is being used in each Snapshot run instance easily? I could try to query the app instance's NSLocale setting via HSTestingBackchannel but that seems unnecessarily complicated.
I really need to do a lot of switching on languages for every screenshot and other data.
would be nice:
let currentLanguage = snapshot.currentLanguage()

**Comment by TKBurner** [comment]
Hi @JamaicanRumCream! Great to hear from you. The language's parameter should be printed to your output when snapshot runs. Let me see the full output if you are still running into any issues.

**Comment by samwize** [comment]
You can use `deviceLanguage` as per [documented](https://github.com/fastlane/fastlane/tree/master/snapshot#determine-language).
