### ISSUE TITLE
The Crashlytics Actions path should be to submit and not necesarily to Crashlytics.framework

### ISSUE THREAD

**Issue by onato** [fastlane/fastlane#4475]
I followed the documentation to get the Crashlytics action to upload my binary. It failed (with a success message). 

After adding --verbose I could see the command that was generated. I tried this directly and got the following message:

> error: The submit binary delivered by cocoapods is in a new location, under '${PODS_ROOT}/Crashlytics/submit'. This script was put in place for backwards compatibility, but it relies on PODS_ROOT, which does not have a value in your current setup. Please update the path to the submit binary to fix this issue.

The documentation is currently misleading. The path is specified so that the action can find the submit binary. As the error above states this is no longer in the Crashlytics.framework.

I submitted a pull request to change this: https://github.com/fastlane/fastlane/pull/4474

**Comment by TKBurner** [comment]
Thanks for your pull request @onato! I see Felix is working with you on it. Can you investigate a little bit more about the path and update on the PR? Thanks!
