### ISSUE TITLE
app_identifier  can't change

### ISSUE THREAD

**Issue by goodcyg** [fastlane/fastlane#4476]
build.sh

#!/bin/sh
versionNumber=$1 # 1.0.0
buildNumber=$2 # 2000

rm -rf build

basicLanes="InHouse"
for laneName in $basicLanes
do
    fastlane $laneName version:$versionNumber build:$buildNumber
done

appfile.h

app_identifier "org.test.the1111111111"
apple_id "jack@126.com"
team_id "Q2CBPJ58CA"

# 1.inhouse
for_lane :InHouse do
    app_identifier "org.test.apple"
    apple_id "tom@126.com"
end

I want a to be equal to app_identifier "org.test.apple"
Post execution  app_identifier "org.test.the1111111111"
why？

**Comment by goodcyg** [comment]
help help help?

**Comment by TKBurner** [comment]
Hi @goodcyg! Great to hear from you. Can you post the full output as well as any error messages you are getting? I'm not quite sure I understand what issue you are hitting, but I'd love to help. Thanks! 👍

**Comment by goodcyg** [comment]
appfile

app_identifier "org.test.the1111111111"
apple_id "jack@126.com"
team_id "Q2CBPJ58CA"

#1.inhouse
for_lane :InHouse do
app_identifier "org.test.apple"
apple_id "tom@126.com"
end

fastfile
def update_app_bundle_id(app_id)

    update_info_plist(
        xcodeproj:PROJECT_FILE_PATH ,
        app_identifier:app_id,
        plist_path:"#{PLIST_FILE_PATH}"
    )
     update_app_identifier(
        xcodeproj:PROJECT_FILE_PATH ,
        app_identifier:app_id,
        plist_path:"#{PLIST_FILE_PATH}"
    )
    
    update_info_plist(
        xcodeproj:PROJECT_FILE_PATH ,
        app_identifier:app_id,
        plist_path:"#{UNITTEST_PLIST_FILE_PATH}"
    )
    
     update_app_identifier(
        xcodeproj:PROJECT_FILE_PATH ,
        app_identifier:app_id,
        plist_path:"#{UNITTEST_PLIST_FILE_PATH}"
    )
  
end
============================
After executing this code，info.plist  File in CFBundleIdentifier="org.test.the1111111111"
And I want  that info.plist  File in CFBundleIdentifier="org.test.apple"，app_identifier can't change？

**Comment by TKBurner** [comment]
Hi @goodcyg! Thanks for working with me on this. You should be able to set up your app with multiple targets using env. Check out the help on this page for more info, https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/fastlane/docs/FAQs.md.

Thanks!

**Comment by KrauseFx** [comment]
For some reason the link was to a version from a specific commit, here's the latest one from master: [FAQs.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/FAQs.md)
