### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bgannin** [fastlane/fastlane#4477]
### Issue Description

🔑 

The README.md file does not have listings for the scan and supply tools. A bit of sorting/organization might be nice as well for iOS/Android pairings. The issue(s) call to action isn't linked.

### Environment

fastlane 1.83.0

_Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?_ no
_Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?_ no

**Comment by bgannin** [comment]
Working on this currently in a fork for a PR. Will submit once I've completed a thorough pass.

**Comment by KrauseFx** [comment]
Nice catch, thanks for submitting a PR 👍
