### ISSUE TITLE
Frameit has invalid mini_magick dependency in gemfile

### ISSUE THREAD

**Issue by ekolesnikov** [fastlane/fastlane#4479]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

There seems to be invalid mini_magick dependency declaration ('~> 4.0.2').
frameit attempts to use 'details' attribute of MiniMagick::Image class which is not present in 4.0.x.

After updating requirement to "~> 4.0" in gemspec, frameit accepts mini_magick 4.5.1 which fixes the issue

UPD: Note that this only affects the "convert PSD to PNG" step, you need to remove all .png files from ~/.frameit/devices_frames to reproduce.

UPD2: Note that this only happens with "April 2016 iPhone SE" frame that has multiple layers.

UPD3: Seems to be this commit:
https://github.com/fastlane/fastlane/commit/6ced4138f23056e7fe84b5a36afda9b1e9da0326
that forgot to include mini_magick version bump.

##### Complete output when running fastlane, including the stack trace and command used

 egorkolesnikov@FL-2015-003  ~/work/projects/minfit-ios   feature/apr16update  frameit
[17:48:32]: Converting PSD file '/Users/egorkolesnikov/.frameit/devices_frames/iPhone SE/iPhone-SE-Silver-horizontal.psd'
[17:48:32]: Removing white background 🚫 ⬜️
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '3abad13f4d98cc995d291ea61b06ce5b'
The crash report has been stored locally '/tmp/sentry_3abad13f4d98cc995d291ea61b06ce5b.json'
/Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:382:in `block in method_missing': [!] undefined method `details' for #<MiniMagick::Image:0x007ffadb8e7690> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:499:in `block in mogrify'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/tool.rb:52:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:492:in `mogrify'
	from /Library/Ruby/Gems/2.0.0/gems/mini_magick-4.0.4/lib/mini_magick/image.rb:378:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:76:in `block (2 levels) in convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:75:in `reject'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:75:in `block in convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:61:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/frame_converter.rb:61:in `convert_frames'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/lib/frameit/runner.rb:10:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:32:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:32:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/frameit-2.6.0/bin/frameit:72:in `<top (required)>'
	from /usr/local/bin/frameit:23:in `load'
	from /usr/local/bin/frameit:23:in `<main>'

### Configuration Files

N/A

### Environment

fastlane 1.83.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by ekolesnikov** [comment]
Added pull request for your convenience.
https://github.com/fastlane/fastlane/pull/4480

**Comment by i2amsam** [comment]
Thanks for the report @ekolesnikov !  This will go out in the next release.

**Comment by i2amsam** [comment]
@ekolesnikov I just shipped this fix out this with `frameit` 2.6.1, could you give it a try and let me know?

**Comment by ekolesnikov** [comment]
@i2amsam Tested 2.6.1, confirmed the issue to be resolved.
I believe there may be an issue with badge now that still depends on 4.0.x - bundler may complain about two incompatible versions of the same dependency.
