### ISSUE TITLE
frameit picks up mock frames if fastlane cloned on the same level with ios project

### ISSUE THREAD

**Issue by ekolesnikov** [fastlane/fastlane#4482]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
If fastlane is cloned at the same level with iOS project, i.e.:
/Users/me/projects/fastlane
/Users/me/projects/my_ios_project

then frameit will pick mock frames from fastlane/frameit/spec/fixtures/mock_frames instead of ~/.frameit/devices_frames

https://github.com/fastlane/fastlane/blob/master/frameit/lib/frameit/template_finder.rb#L62

As far as I understand, this code requests frameit to search for templates on one level above the project folder.

fastlane 1.83.0
frameit 2.6.0

**Comment by ekolesnikov** [comment]
FYI: there's new file name convention in latest Apple mockups:

iPhone_6_Vert_Slvr_sRGB_0914.png
iPhone_6_Plus_Vert_SpaceGray_sRGB_0914.png

etc

**Comment by TKBurner** [comment]
Hi @ekolesnikov! Great to hear from you. The fastlane folder is expected to be within the project directory. Is there a reason you are storing it one folder up? Thanks!

**Comment by ekolesnikov** [comment]
Hi @TKBurner 

Apologies for the confusion. In this case "fastlane folder" is a git clone of fastlane repository (as in 'git clone https://github.com/fastlane/fastlane.git'), as opposed to fastlane configuration folder within the project directory.

I was chasing an issue in frameit, cloned fastlane repo to investigate and suddenly started seeing screenshots framed in mock frames (green rectangles) instead of actual templates stored in ~/.frameit/devices_frames.

**Comment by TKBurner** [comment]
@ekolesnikov Thanks for following up. We are going to try and repro this over here and will update on this thread. I hope that you have a wonderful day! 👍

**Comment by KrauseFx** [comment]
Yeah, that's because instead of storing your frames in `~/.device_frames`, you can also store it in your git repo, this way it works on any machine. The only thing I can say is that you shouldn't close the fastlane repo inside your project

**Comment by ekolesnikov** [comment]
@KrauseFx @TKBurner 
Apologies for reopening this, but I would like to emphasise the fact that fastlane repo was NOT inside the project.

I would really appeciate it if you could have a closer look into this - I believe this is unintended side-effect.

As per the original report:

**~/work/my-ios-project** -- this is the main project folder

**~/work/my-ios-project/fastlane** -- this is fastlane configuration 

**~/work/fastlane-tools** -- this is cloned fastlane repository. As you can see it sits in "work" folder, outside the project.

Core issue here is that it goes one level up above 'my-ios-project', scans the whole ~/work folder and picks up the first (alphabetically) folder that contains compatible frames.

Attaching two frameit results - one with fastlane-tools sitting in ~/work folder, another with it moved to ~/tmp.

![iphone6-a3third_framed](https://cloud.githubusercontent.com/assets/2346217/15130927/57af287a-168f-11e6-9070-d1c043cd0c34.png)

![iphone6-a3third_framed](https://cloud.githubusercontent.com/assets/2346217/15131002/cd968d44-168f-11e6-94b1-72540eeaba6c.png)

**Comment by TKBurner** [comment]
@ekolesnikov Thanks for following up. What directory level are you running frameit from? It was meant to be run from at the project level. (One above Fastlane dir) Thanks! 👍

**Comment by ekolesnikov** [comment]
Hi @TKBurner 

I can confirm that frameit is executed from the project folder:
>/Users/ekolesnikov/work/my-ios-project$ frameit

**Comment by TKBurner** [comment]
@ekolesnikov Thanks for following up. I bumped this with the core team to get more eyes on it. I still haven't been able to reproduce this behavior. We will follow up on this thread. Thanks!

**Comment by ekolesnikov** [comment]
Hi @TKBurner 

Attaching minimal test case.
Steps to reproduce:
1. unzip the file
2. cd fastlane-issue-4482/my-ios-project
3. run frameit

Note that it is essential to reproduce that your project name is alphabetically below "fastlane-tools" (i.e. starts with any letter after "f").

For instance, renaming fastlane-issue-4482/fastlane-tools folder to fastlane-issue-4482/zfastlane-tools will cause the issue to disappear and frameit to work properly.

[fastlane-issue-4482.zip](https://github.com/fastlane/fastlane/files/262414/fastlane-issue-4482.zip)
