### ISSUE TITLE
appetize action does not support android platform

### ISSUE THREAD

**Issue by louislarry** [fastlane/fastlane#4486]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Appetize action does not support android platform.

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.84.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
Hi @louislarry! Thanks for working with us on your pull request. Because we are already working with you there, I'm going to go ahead and close this ticket out. Thanks!
