### ISSUE TITLE
Update READMEs to include screengrab and supply

### ISSUE THREAD

**Issue by corydolphin** [fastlane/fastlane#4495]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

1. Fastlane README.md does not contain references to screengrab and supply.
2. The banner on all tools' readmes listing all of the fastlane tools also omit them. 

##### Complete output when running fastlane, including the stack trace and command used
N/A
### Configuration Files

N/A

Fastfile:
N/A

### Environment

fastlane version (run `fastlane -v`): N/A

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? N/A

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? N/A

**Comment by TKBurner** [comment]
Thanks @corydolphin! Hope you are enjoying SF! 👍
