### ISSUE TITLE
[Proposed] Cocoapods self healing repo update

### ISSUE THREAD

**Issue by tommeier** [fastlane/fastlane#4497]
With Cocoapods 1.x very close [(RC1 available now)](https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#100rc1-2016-04-30) the new pattern is for `pod install` to _not_ run `pod repo update` for performance reasons.

I've implemented a self-healing pattern in my `Fastfile` to automatically update and retry if the error message matches, this way CI and everything else continues to work.

Not sure if you'd be interested in a PR for it before I went and did tests for it?

It would look something like this: https://github.com/fastlane/fastlane/compare/master...tommeier:cocoapods-1-0

Would also continue to work with older versions.

**Comment by TKBurner** [comment]
Hi @tommeier! Thanks for reaching out. I marked this as help wanted so we can see if anyone in the community is also interested in this PR. I'll send it out to the internal team too as a PR proposal. Thanks! 👍

**Comment by jshier** [comment]
Self healing is nice, but the current `cocoapods` action defines a `repo_update` flag that says: `Run `pod repo update` before install`. This doesn't currently work. So the self healing would be great, but I think a manual flag should be there as well.

**Comment by tommeier** [comment]
@jshier absolutely, the current action would need to be updated to remove the unused actions in 1.x, this is more for the future one when released, and could have a `release_candidate: true` to enable in the interim. I agree a manual forced flag should definitely be there too, now it's 2 seperate steps anyway.

**Comment by staminajim** [comment]
FYI all in here that CocoaPods 1.0 final has been released, so the pod install command is currently broken.  Looks like @dstranz 's PR above should fix it.

**Comment by TKBurner** [comment]
@staminajim Thanks for following up on this. I'll reach out to the core team. Thanks 👍

**Comment by ohwutup** [comment]
Per @orta's comment on the PR https://github.com/fastlane/fastlane/pull/4843#issuecomment-221877115 I don't think that we want to merge that change as it stands.

**Comment by KrauseFx** [comment]
Yeah, thanks everybody, closing this issue now 👍
