### ISSUE TITLE
SSH will not show console logs in runtime

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#4504]
### Issue Description

Using ssh will work fine, but instead of showing the console logs in runtime it will show them only when job is done. You cannot see the progress of the ssh through logs.
Using regular ssh to that machine using terminal do show the console logs with the progress.

##### Complete output when running fastlane, including the stack trace and command used

Command used: ssh

```
ssh(
    	host: "10.8.1.29",
    	username: "local",
	    password: "password",
		commands:
			[
				"cd /Users/local/Desktop/Shared/automation_mobile ; python flow.py \"" + build_info['build_url'] + "\" ios"
			],
    )
```

As you can see in the next output, only after the process finished (15 min later) and successfully executed, only then it will show the terminal logs:

```
[11:41:46]: [SSH COMMAND]: cd /Users/local/Desktop/Shared/automation_mobile ; python flow.py "https://rink.hockeyapp.net/api/2/apps/92d18ec4382b424eb2a2/app_versions/73?format=ipa&pltoken=b34hy535bhe5hy&avtoken=erth356h236h356hy6" ios
[11:55:50]: Succesfully executed 1 commands on host: 10.8.1.29
[11:55:50]: 
########### 
 File class object
File class object
File class object
File class object
File class object
start test
device connected
...
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
ssh(
    	host: "10.8.1.29",
    	username: "local",
	    password: "password",
		commands:
			[
				"cd /Users/local/Desktop/Shared/automation_mobile ; python flow.py \"" + build_info['build_url'] + "\" ios"
			],
    )
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.81.0 (also tried on 1.84.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? n

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? n

**Comment by TKBurner** [comment]
Hi @nmayafit! Great to hear from you. Can you add the --verbose flag to your lane and see the output? I think that'll solve your issue. Thanks!

**Comment by nmayafit** [comment]
How do I add it to the fastfile?

**Comment by TKBurner** [comment]
Hi @nmayafit Thanks for following up. You can just add the --verbose flag at the end of the command you are using to run the lane. Let me know how it goes and the output. Thanks!

**Comment by nmayafit** [comment]
Its still the same.
This is my command: "fastlane test username:user --verbose"
Also added verbose:true into the ssh params in fastfile (in case it can help).

**Comment by TKBurner** [comment]
Hi @nmayafit! Thanks for following up. Right now this is by design.

You can access the output via the output variables.

`+------------------+-------------------------------------------+
|                     ssh Output Variables                     |
+------------------+-------------------------------------------+
| Key              | Description                               |
+------------------+-------------------------------------------+
| SSH_STDOUT_VALUE | Holds the standard-output of all commands |
| SSH_STDERR_VALUE | Holds the standard-error of all commands  |
+------------------+-------------------------------------------+
Access the output values using `lane_context[SharedValues::VARIABLE_NAME]`

More information can be found on https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md`

**Comment by nmayafit** [comment]
Sorry, but when you state that this is by design you mean that I should receive all the console output only when ssh is finished and not while its in the process? So its not a bug or anything wrong I'm doing? If I cannot see the console logs in runtime for a process taking me 20 min on a remote machine I really cannot use this action.
Please approve so I know if to remove ssh from my fastfile and use something else.
Thanks.

**Comment by TKBurner** [comment]
@nmayafit Thanks for following up. I'm going to mark this as help wanted since it's currently not a supported use case but I can see multiple users taking value. If you are interested in submitting a PR let me know, otherwise hopefully someone from the community takes a look at making this an option.

Thanks! 👍

**Comment by ravron** [comment]
@nmayafit I've submitted PR #4662 to fix this issue. Please take a look and see if it satisfies your use case, and leave any comments there. Thanks!

**Comment by nmayafit** [comment]
@ravron it looks ok to me. THANKS!

**Comment by TKBurner** [comment]
@ravron Thanks for stepping in here. We'll review your PR soon 👍 

@nmayafit Were you able to get up and running?

**Comment by nmayafit** [comment]
up and running? before the PR?

**Comment by ravron** [comment]
@nmayafit you can check out the PR locally [by doing something like this][1]. Then run the `fastlane` binary in that new, checked out copy. See [the contributing instructions][2] for details. If you do that, you can confirm for us that this PR does what you need.

[1]: http://blog.scottlowe.org/2015/09/04/checking-out-github-pull-requests-locally/
[2]: https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md#developing

**Comment by nmayafit** [comment]
this branch (ssh-action-squashed) gives me version 1.81.0 and not 1.89.0 (the latest one I have).
Is this on purpose?

**Comment by nmayafit** [comment]
As stated in the PR [#4662](https://github.com/fastlane/fastlane/pull/4662) the results are the same. Still can't see the logs while connection is open.

**Comment by TKBurner** [comment]
@nmayafit Glad to see you got up and running on the PR. We'll work to merge this as soon as we can. Hope you have a great week! 👍 

@ravron Thanks again for making this PR! We are prioritizing bug fixes over feature work right now, but will make sure to review and work with you on it 👍
