### ISSUE TITLE
Metadata

### ISSUE THREAD

**Issue by vikram1234** [fastlane/fastlane#4511]
Supply Team, need one small clarification if there is way to specify following details though metadata?

I can not find that in documentation. 
-----------------
You need to add a feature graphic. [English (United States) – en-US]
You need to select a category.
You need to select a content rating.
You need to acknowledge that this application meets the Content Guidelines.
You need to acknowledge that this application complies with US export laws.
You need to target at least one country.
You need to enter a privacy policy URL.
You need to make your application free or set a price for it.
You need to declare whether or not your application contains ads.
Your app is missing a required content rating. Go to your app's Content Rating page and complete a rating questionnaire.
----------

**Comment by asfalcone** [comment]
@vikram1234 Thanks for the question. Of the things you listed [supply](https://github.com/fastlane/fastlane/tree/master/supply) is able to handle the feature graphic. 👍

**Comment by vikram1234** [comment]
Thanks a lot @asfalcone for reply, so i would not able to upload all that info using supply? 

Also, how to Publish the app, do i have to do that manually?

**Comment by asfalcone** [comment]
Yes only metadata and images are uploaded by supply at this time.

You can select the [track](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb#L13) to uplaod to, but the publishing happens via the Google Play console directly.

**Comment by vikram1234** [comment]
Thanks @asfalcone, just one more small clarification, the other metadata is not supported by Supply or no way with google play store api's?

**Comment by asfalcone** [comment]
The other metadata is not supported by supply. Check out the [google-api-ruby-client](https://github.com/google/google-api-ruby-client) to see what else is available in the api 👍

**Comment by ravinggenius** [comment]
I investigated `google-api-ruby-client` and was disappointed to find it doesn't support (much?) more than `supply` does. See #4699.

**Comment by KrauseFx** [comment]
Yeah, we wish we could support more metadata, but we can only do as much as the `google-api-ruby-client` offers.

**Comment by vikram1234** [comment]
@KrauseFx thanks for your reply, is there any future updates you have if "google-api-ruby-client" api can support all metadata and auto submit apps for review? 

Please let us know if you have any updates, it would help us a lot.

**Comment by ravinggenius** [comment]
@vikram1234 I investigated `google-api-ruby-client` and saw that `supply` is already making (more or less) full use of it. I opened an issue (https://github.com/google/google-api-ruby-client/issues/412), but it was closed pretty quickly, as the library is auto-generated based on what @google exposes in their API.

I believe Google will have to make some changes before we can get any traction. I looked around for some contact information but came up empty-handed. If anyone from Google happens to see this, we'd really like to be able to access/edit via the API more (all?) data which we can access over the Play Store Android developer web interface.

**Comment by TKBurner** [comment]
@ravinggenius Thanks for following up on this. We will make changes as google-api-ruby-client gets updated. Thanks!

**Comment by vikram1234** [comment]
@TKBurner thanks for reply, would it going to support all metadata and auto publish or you could please point me to what is new could be supported?

**Comment by TKBurner** [comment]
@vikram1234 Thanks for following up. We only can support what is accessible via the API. Can you let me know what specifically you are running into an issue with. Thanks! 👍

**Comment by vikram1234** [comment]
@TKBurner - Thanks for reply, i have been following for below issues on android. 

You need to add a feature graphic. [English (United States) – en-US]
You need to select a category.
You need to select a content rating.
You need to acknowledge that this application meets the Content Guidelines.
You need to acknowledge that this application complies with US export laws.
You need to target at least one country.
You need to enter a privacy policy URL.
You need to make your application free or set a price for it.
You need to declare whether or not your application contains ads.

These all parameters not supported by Supply, and i wanted to auto submit for review once APK is uploaded to store like it does for IOS.

**Comment by TKBurner** [comment]
Hi @vikram1234! Thanks for following up. I'm going to mark this as a blocked feature as we are limited by the official Google ruby gem for the play store. Thanks!
