### ISSUE TITLE
Tagging github releases with Version.Build number.

### ISSUE THREAD

**Issue by dholdaway** [fastlane/fastlane#4513]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

its not really an issue, i was just looking for an answer / point in the right direction.

i have looked at all the fastlane examples.

my number versioning is working

so my release part looks like 

github_release = set_github_release(
        repository_name: "xxx/xxx",
        api_token: ENV["GITHUB_API_TOKEN"],
        name: "Build",
        tag_name: VERSION_NUMBER.BUILD_NUMBER,
        description: File.read("../../xxx/release_note.txt"),
        commitish: "master",
        upload_assets: ["../xxx/xxx.ipa"]
      )  

everything works as it should i assume i just need to correct the line 

tag_name: VERSION_NUMBER.BUILD_NUMBER

thanks for creating fastlane! its really good.

**Comment by TKBurner** [comment]
Hi @dholdaway! Have tried something like:

build   = get_build_number()
version = get_version_number()

Thanks!

**Comment by dholdaway** [comment]
after i have incremented the number how do i get it to save at the moment i seem to be going around in circles with version numbers 

the project is set to 1 > travis ci > fastlane > version set to 2 

do i need to do a git commit on the project? to remember the version?

**Comment by TKBurner** [comment]
Hi @dholdaway! Thanks for following up. Can you share the full set of commands you are using. We also have a command increment_version_number. You shouldn't need to make the commit unless you are pushing up to Travis. In that case you'll need to add the new files and commit, but this isn't related to Fastlane. Let me know how it goes 👍
