### ISSUE TITLE
Installing xcode command line tools on Linux server

### ISSUE THREAD

**Issue by designzoo-peter** [fastlane/fastlane#4520]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I want to use _sigh_ on a linux server, but I don't know how to install the xcode command line tools on a centos linux server. I know this isn't an issue with fastlane itself, but I think here might be the best chance of getting help (and it falls under the category of 'Need Help?'  :frowning: ).

I see the requirements are OSX or Linux, and that the command is provided in the setup section on how to install the command line tools on OSX, but I was wondering if anyone had any experience in installing it for Linux? Can someone please explain how I might be able to use the pkg file for installing their command line tools (https://developer.apple.com/downloads/) on OSX, and install it on a Linux server? Or is there another way?

##### Complete output when running fastlane, including the stack trace and command used

N/A

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

N/A

### Environment

fastlane version (run `fastlane -v`): fastlane 1.85.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
Sorry, `sigh` requires Mac OS X, you can use `spaceship` on Linux to download provisioning profiles 👍 
What do you want to do with it on Linux?

**Comment by designzoo-peter** [comment]
That's ok, thanks for the reply! I wanted to resign an ipa file.

**Comment by TKBurner** [comment]
@designzoo-peter Thanks for following up. You should be able to accomplish this still using Spaceship, you'll need to look through the codebase to get the exact commands etc. 👍

**Comment by KrauseFx** [comment]
@designzoo-peter Resigning an `ipa` file doesn't work with `spaceship`, but with `resign.sh` instead: https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh
I don't know if it works on Linux
