### ISSUE TITLE
[Transporter Error Output]: Could not start delivery: all transports failed diagnostics

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#4523]
Since yesterday, all calls to deliver to upload the binary are failing. Is there something new or iTC just slow?

```
[13:29:43]: This might take a few minutes, please don't interrupt the script
[13:31:14]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[13:31:14]: Transporter transfer failed.
[13:31:14]: 
[13:31:14]: Could not start delivery: all transports failed diagnostics
[13:31:14]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by xylone** [comment]
I can confirm the same issue.

Updated fastlane to the latest version    CHECK
I have read the Contribution Guidelines CHECK

[11:45:04]: Activating language nl-NL...
[11:45:06]: Uploading metadata to iTunes Connect
[11:45:07]: Successfully uploaded initial set of metadata to iTunes Connect
[11:45:08]: Price Tier unchanged (tier 0)
[11:45:08]: Uploading app icon...
[11:45:17]: Uploading binary to iTunes Connect
[11:45:17]: Going to upload updated app to iTunes Connect
[11:45:17]: This might take a few minutes, please don't interrupt the script
[11:48:06]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[11:48:07]: Transporter transfer failed.
[11:48:07]: 
[11:48:07]: Could not start delivery: all transports failed diagnostics
[11:48:07]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

[!] Could not upload binary to iTunes Connect. Check out the error above

gem list fastlane
*** LOCAL GEMS ***
fastlane (1.86.1, 1.81.0, 1.80.0, 1.70.0, 1.68.0, 1.66.0, 1.64.0)
fastlane_core (0.43.1, 0.41.2, 0.41.0, 0.40.0)

**Comment by xylone** [comment]
And it looks like a problem with the servers, because it is working again. So it is not a bug or problem and can be closed.

**Comment by pedro380085** [comment]
Yes, it started working again now. I thought it was weird, because it took so many hours to come back online.

**Comment by esetnik** [comment]
I had the same issue and it resolved after a few hours. I guess the moral of the story when it comes to iTunes Connect is "just keep trying".

**Comment by TKBurner** [comment]
@esetnik Glad you got up and running! Let me know if you see this again consistently. Thanks 👍

**Comment by kcharwood** [comment]
Seeing this error this morning for the last hour+

**Comment by badeleux** [comment]
Same for me.

**Comment by kcharwood** [comment]
After another hour, it started working for me again

**Comment by kcharwood** [comment]
And its failing again

**Comment by morgz** [comment]
Failing for me too with:
[Transporter Error Output]: Could not start delivery: all transports failed diagnostics

**Comment by jonnyijapan** [comment]
Failing for me now. Same error. Was working just some hour ago. Now repeatedly fails.

**Comment by vpolouchkine** [comment]
Can you peeps try the suggestion in https://github.com/fastlane/fastlane/issues/4544#issuecomment-217519255?

**Comment by AymenFarrah** [comment]
Same issue for me

Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

**Comment by vpolouchkine** [comment]
@AymenFarrah Does https://github.com/fastlane/fastlane/issues/4544#issuecomment-217519255 help?

**Comment by xylone** [comment]
Yes it works now everytime! Issue can be closed now.

**Comment by TKBurner** [comment]
@xylone Awesome! Really glad to hear you got up and running. Hope that you have a great weekend coming up 👍

**Comment by siamak-haschemi** [comment]
I made the same experience since 3-4 days. Still happens to I almost all cases. But withtout changing code, _sometimes_ it works, without any specific pattern.

**Comment by TKBurner** [comment]
Hi @siamak-haschemi Thanks for reaching out about this. Can you run fastlane run update_fastlane? After that share the output with the error so I can have a look.

Thanks!

**Comment by prgnshptlklp** [comment]
Faced this issue many times, Most of times it worked second time when i just rerun script immediately after getting error. Sometimes it generates error 3 to 4 times. 

So as workaround, pilot can have option of retry like snapshot.

**Comment by cagataycali** [comment]
Return status of iTunes Transporter was 1: 
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

I'm getting same one

**Comment by TKBurner** [comment]
@cagataycali Can you open a new issue for this? Make sure to share your full input and output. Thanks!
