### ISSUE TITLE
Improve error output for fastlane

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#4533]
# Tasks

- [ ] Wrap Ruby Standard Error with Fastlane Error.

# Description

This is an umbrella task for improving the user friendliness of the output of Fastlane. Currently fastlane has the current issues when there is an error:

- If an error occurs you need to re-run it in `verbose` mode in order to get all the steps, for some builds this means a 30 minute turnaround time.
- Some trivial errors have a verbose and unhelpful output and force you to look into the sentry file to find out what the error actually was. 
- The path to the sentry file is buried by the output of the environment variables, lane table and new update prompt.

#Example Pseudo-Output 1 - The User sets an ENV to a boolean instead of a string

```
fastlane lane
< Lane Output >
Error "Ruby::JumpError"
< Really long stack trace to do with the jump error but doesn't help you know what the error is >
< Environment Variable Dump - Very long especially if you use the change log action >
< Lane Table >
< Sentry file link >
< Really long stack trace to do with the jump error but doesn't help you know what the error is > 
< Fastlane update prompt including really long change log >
```

If you open the sentry file, the actual error isn't even at the top of the file, once you figure out the format of the log it's easy to see that `ENV["MY_VAR"] = true` should be `ENV["MY_VAR"] = "1"

In this case I would have preferred:

```
fastlane lane
< Lane Output >
Error "Cannot convert true to String"
< For more debug information go to this file - link to sentry file - on CI we could echo the contents of this file in a way thats obvious its the error  > 
< Your fastlane is out of date, no change log >
```

#Example Pseudo-Output 2 - A tool fails for some reason

```
fastlane lane
< Lane Output >
< Command line error >
Error "Ruby::JumpError"
< Really long stack trace to do with the jump error but not useful at all >
< Environment Variable Dump - Very long especially if you use the change log action >
< Lane Table >
< Sentry file link >
< Really long stack trace to do with the jump error but not useful at all >
< Fastlane update prompt including really long change log >
```

Again way too much information and we then have to run verbose to get the important information which isn't in the sentry file.

1. It would be awesome if Fastlane in non verbose mode could log the commands to a external file for debugging.
2. When there is an error with the command it would be great if we just saw what failed and then had the link to the sentry log, nothing more, nothing less.

#Overview

Steps:

1. Log commands to a special log file when not in `verbose` mode so user doesn't have to re-run lane just to get what was done.
2. Only dump lane table and environmental variable on an error into the sentry log.
3. Only dump stack trace in sentry log.
4. When there is an error, print the descriptive error in the sentry log not the "Ruby::JumpError" message. Ideally we could have some helpful hints on how to fix it for the user.
5. Don't print the whole change log for the new version of fasltane, just letting us know there is a new version is enough when there is an error.
6. Ran under CI the contents of the sentry file could be echoed out followed by the friendly error message, so the user can look at their CI logs to see the issue and simply copy over to here.
7. [Bonus] Fastlane could output a template for a github issue, (See how CocoaPods does this).

**Comment by KrauseFx** [comment]
I'm a bit unsure about how much value we get with Sentry, I'm thinking about just removing it, since we usually tell users to post their stack trace anyway.

**Comment by jcampbell05** [comment]
@KrauseFx we should probably look into pre-filling a template like CocoaPods does and perhaps copying to to the clipboard so users can post directly into an issue.

Maybe @orta from that team can point to how they did that.

**Comment by orta** [comment]
We use the same thing in Danger, where we wrap the standard error [with our own](https://github.com/danger/danger/blob/master/lib/danger/standard_error.rb#L63) - also [gh-issues-inspector](https://github.com/orta/gh-issues-inspector) can improve that experience

**Comment by KrauseFx** [comment]
We actually already wrap all of our exceptions in our own classes (https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/interface.rb#L114-L120), but don't have custom printing yet. 

We don't do that for actual Ruby crashes though, only when we raise one

**Comment by jcampbell05** [comment]
@KrauseFx As a first step maybe wrap the standard error ?

**Comment by jcampbell05** [comment]
https://github.com/fastlane/fastlane/pull/4756 Should help with this.
