### ISSUE TITLE
[sigh] Invalid options --short-version and --bundle-version, should use underscore

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#4539]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The options `--short-version` and `--bundle-version` are invalid, appratently dashes in the middle of the option name are not supported. It must be underscore: `--bundle_version` and `--short_version`.

### Environment

sigh version: `1.7.0`
Do you use bundler to execute sigh: `yes`
Do you use a Ruby environment manager: `rvm`

**Comment by asfalcone** [comment]
@mgrebenets Thanks! What is the current behavior for people using `sigh` does this only fail if they try to use these options? Trying to decide is if I should do a hotfix right now! 👍

**Comment by mgrebenets** [comment]
Yes, it only fails when trying to use one of these new options, so it doesn't break any existing scripts.

**Comment by TKBurner** [comment]
Hey @mgrebenets! Just wanted to let you know that Andrea merged a fix for this and it'll be released soon 👍  Closing this out, feel free to ping and I'll reopen if you still see it after a new version of sigh has been released. Thanks!
