### ISSUE TITLE
Failed to submit for review with spaceship, but no error.

### ISSUE THREAD

**Issue by kviatkowsky** [fastlane/fastlane#4541]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Submitting the app for review with ruby script using spaceship has no effect, although there is no error. App has still `Prepare for Submission` status. I tried it on 2 apps. Here is what the script looks like:

	submission = app.create_submission

	if submission == nil
	  puts "#{app.name} - no submission created".red
	  exit 1
	end

	if submission.submitted_for_review then
	  puts "#{app.name} already submitted".yellow
	  exit 0
	end

	submission.content_rights_contains_third_party_content = false
	submission.content_rights_has_rights = false
	submission.export_compliance_encryption_updated = false

	submission.add_id_info_uses_idfa = true
	submission.add_id_info_limits_tracking = true
	submission.add_id_info_serves_ads = true
	submission.add_id_info_tracks_action = true
	submission.add_id_info_tracks_install = true

	puts ('Submitting for review "' + app.name + '"').green

	submission.complete!

##### Complete output when running fastlane, including the stack trace and command used
No output, however when I log http body of the response in `tunes_client.send_app_submission` I can see that response seems to be correct 
```
[...]
"messages"=>{"warn"=>nil, "error"=>nil, "info"=>["Successful POST"]},
"statusCode"=>"SUCCESS"}
```

### Environment

spaceship version: spaceship (0.26.2)

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

**Comment by kviatkowsky** [comment]
OK, it's a new app, so Export Compliance needs to be set too. 
`Adding submission.export_compliance_uses_encryption = false` solved the issue.
@KrauseFx is it possible to detect if some fields that are obligatory are not set?

Anyway, issue can be closed.

**Comment by TKBurner** [comment]
@kviatkowsky Thanks for following up on this. We'll continue to improve our error messaging, if you are interested in submitting a PR for this that'd be great 👍
