### ISSUE TITLE
Incorrect time in summary when using other_action

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#4546]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When calling an action from another action using `other_action` (https://github.com/fastlane/fastlane/pull/4441), the inner action shows in the summary, in a way that you'd think that it took the time of the inner action + the action itself (see example).

I see two ways of solving it:
1. Don't show actions called from another action in the summary. When an action needs to call another, that's an implementation detail and the user of the action shouldn't need to know about it.
2. Change the summary to allow nested levels of actions. Something like this:

```
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | is_ci                               | 0           |
| 5    | bundle_install                      | 0           |
| 6    | is_ci                               | 0           |
| 7    | cocoapods_if_needed                 | 62          |
|      |    > cocoapods                      | 51          |
+------+-------------------------------------+-------------+
```

However this could become ugly, as you could have several levels of actions calling others (although not usual).

I think option 1 is the way to go.
##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane pod_install

...
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | is_ci                               | 0           |
| 5    | bundle_install                      | 0           |
| 6    | is_ci                               | 0           |
| 7    | cocoapods                           | 51          |
| 8    | cocoapods_if_needed                 | 62          |
+------+-------------------------------------+-------------+
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
fastlane_version "1.86.1"

default_platform :ios

platform :ios do
  desc "Runs pod install if needed"
  lane :pod_install do
    cocoapods_if_needed
  end
end
```

`cocoapods_if_needed.rb`:

``` ruby
module Fastlane
  module Actions
    class CocoapodsIfNeededAction < Action

      def self.needs_to_run_pod_install
        begin
          !FileUtils.compare_file('Podfile.lock', 'Pods/Manifest.lock')
        rescue  Exception => e
          true
        end
      end

      def self.run(params)
        if needs_to_run_pod_install
          sh 'bundle exec pod repo update'

          other_action.cocoapods
        else
          UI.message "🍫  Skipping pod install because Pods seems updated".blue
        end
      end

      #####################################################
      # @!group Documentation
      #####################################################

      def self.description
        "Runs pod repo update and pod install if needed"
      end

      def self.details
        "Checks if the sandbox is in sync with the Podfile.lock. If not, runs pod repo " \
        "update and then pod install"
      end

      def self.available_options
        []
      end

      def self.authors
        ["marcelofabri"]
      end

      def self.is_supported?(platform)
        true
      end
    end
  end
end
```
### Environment

fastlane version (run `fastlane -v`): fastlane 1.86.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yep

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by KrauseFx** [comment]
Great report, thanks. I'll take a look at this

**Comment by marcelofabri** [comment]
This is still an issue (a small one) with the latest fastlane.

**Comment by KrauseFx** [comment]
Thanks for commenting @marcelofabri, I can confirm this is not ideal, however it would require a lot of work to actually implement this properly. Feel free to prepare a PR if you feel like it 👍

**Comment by marcelofabri** [comment]
Couldn't we add another parameter to `trigger_action_by_name` which would be passed when calling from `other_action`? Then we could pass `nil` to `execute_action` in `trigger_action_by_name` which should hide the "inner" action to appear in the summary.

**Comment by TKBurner** [comment]
@marcelofabri Thanks for the PR we'll work with you there. 👍
