### ISSUE TITLE
hockey says complete, gives me a download url that doesn't work. 

### ISSUE THREAD

**Issue by jpmcglone** [fastlane/fastlane#4547]
```
hockey(
      notify: "0",
      api_token: "REDACTED",
      public_identifier: "REDACTED",
      notes_type: "1"
    )
```

I get a download url... its an older version?  
Also, if I take the generated ipa and upload it manually, it works, so Idk what is wrong.

**Comment by jpmcglone** [comment]
I upped my build number from 1 to something larger, and it started working. /shrug

**Comment by TKBurner** [comment]
@jpmcglone Awesome! Really glad to hear you got up and runnign 👍
