### ISSUE TITLE
Support custom entitlements

### ISSUE THREAD

**Issue by wilrnh** [fastlane/fastlane#4548]
### New Issue Checklist
- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

This is probably more of a feature request. Really, I'd like match to be able to create profiles with custom entitlements.

However, I'd be OK with being able to force match to download profiles, without re-generating them. That way, I'd be able to create profiles in the apple dev console, with custom entitlements, myself. Then run match, which would simply download the new profile, and commit it to git for distribution. Is there anyway this may be possible? Or maybe a different work-around?

Thanks!
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by wilrnh** [comment]
#3471

**Comment by wilrnh** [comment]
Does match do a full delete and create of the profile when re-generating a profile? If not, I could probably create my own profile with custom entitlements, using the naming format that match uses (match Adhoc com.myappid) and from then on, match would only ever use that profile, regenerating off of it when new devices are added, or a cert is regenerated.

possible?

**Comment by wilrnh** [comment]
Seems like match actually checks if the profile it currently has is in the dev console, and if it isn't creates a new one. Also, if a profile already exsists with the format match uses (match AdHoc com.myappid) it just creates a new one with a unix-timestamp appended :(

So, no-go on that workaround...

**Comment by wilrnh** [comment]
Went down the rabbithole on this one:

Seems that match uses sigh to create the profiles, and sigh uses spaceship to interact with the dev console. So this feature would require changes across spaceship, sigh, and match.

https://github.com/fastlane/fastlane/blob/master/match/lib/match/generator.rb#L43
https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb#L113
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/portal_client.rb#L329

And the form element is called `template` which passes a human readable name of the entitlement - not the name saved to the `.mobileprovision` file.

**Comment by TKBurner** [comment]
Hi @wilrnh Thanks for doing this work. I think this will get very complicated and is not in the spirit of match at this time. Have you tried using sigh and cert directly? Thanks 👍

**Comment by wilrnh** [comment]
@TKBurner I'm currently using sigh to distribute profiles, but then again, loosing all the goodies that match provides. It's currently not able to create profiles with custom entitlements either (ultimately due to spaceship's lack of support.)

Just curious, but why do you think this feature would be too complicated to implement? I get that custom entitlements needs to be implemented in spaceship first, then supported in sigh and match, but it seems like a relatively small addition. I also feel like this is essential for match is it's gonna be the `central place where your code signing identity and profiles are kept`.

**Comment by TKBurner** [comment]
Thanks for following up @wilrnh! I'll leave this as help wanted in case anyone wants to fork us and take a shot. We'll look at it, but can't guarantee that we can merge it. 👍

**Comment by esetnik** [comment]
I'm looking for the same thing. I was using match and now need to add `Network Extensions` entitlements to my profiles. Hopefully we can come up with something.

**Comment by esetnik** [comment]
@wilrnh I found a workaround. You can sign your custom entitlement profiles using the same algorithm that `match` uses and then manually push it to your match directory. This works well if you don't frequently change your match profiles, but it's not an ideal solution by any means.

```
openssl aes-256-cbc -k MATCH_PASSWORD -in match_PROVISIONING_PROFILE.mobileprovision -out match_PROVISIONING_PROFILE.mobileprovision.encrypted -a
```

**Comment by TKBurner** [comment]
@esetnik Thanks for the workaround! I'm going to leave this open as help wanted in case anyone wants to add support 👍

**Comment by esetnik** [comment]
Also it should be mentioned that you actually have to create a new profile from scratch in order to add custom entitlements. It's not possible afaik to add custom entitlements to an existing profile even though there is an option for doing so in the developer console. When I attempted to add entitlements to an existing profile everything seemed fine except the generated profile did not actually contain the entitlements. I had to delete that profile and regenerate a new one with the same `match` name format.

**Comment by JacobJT** [comment]
@esetnik do you mind providing some more info on the steps for this workaround? We've expanded our iOS team and have run into a lot of struggles managing provisioning profiles / signing identities, and match seemed so promising  until our builds kept failing due to entitlements. If not for creation, I'd love to use match for provision profile distribution.

**Comment by esetnik** [comment]
@JacobJT no problem.

**Comment by JacobJT** [comment]
My app requires the following entitlements:

*Push Notifications
*Wallet
*Apple Pay
*In-App Purchase
*Maps
*Background Modes
**Location Updates
**Remote notifications

**Comment by esetnik** [comment]
Those are not the same sort of custom entitlements. #4548 is specifically referring to entitlements like `NetworkExtension` API that you need special permission from Apple to enable.

For example:
<img width="708" alt="screen shot 2016-09-09 at 3 07 19 pm" src="https://cloud.githubusercontent.com/assets/664434/18400528/590949a6-76a4-11e6-9606-d7e4424b1099.png">

https://developer.apple.com/library/ios/documentation/NetworkExtension/Reference/NEHotspotHelperClassRef/

For what you're trying to accomplish I believe you can just enable those capabilities in the Capabilities section of your app target in Xcode.

**Comment by JacobJT** [comment]
I see. I got the error saying that the entitlements did not match my provisioning profile, and compared the list of Capabilities and the stuff listen under Enabled Services on the provisioning profile, which appeared to correlate. My apologies for mixing up the issue! I'll do some more googling.  Should I delete these last few comments, then, as they're unrelated to the original issue?

**Comment by esetnik** [comment]
The best thing to do is run `match nuke` and make sure everything is synced up. Also ensure that if you're using Xcode 8 GM that you have reconfigured Xcode to use manual signing in the General tab for your app target.

**Comment by JacobJT** [comment]
Nuking was one of the first things I did. I still had all profiles from when I had first started development, many were stale, and push notifications weren't added until later, so I still had all the certs without the APNS cert attached. 

Cleaning, then turning off one of my capabilities and back on fixed the issue, though I'd be lying if I told you I understood why.
