### ISSUE TITLE
commits_count key for changelog_from_git_commits action

### ISSUE THREAD

**Issue by SiarheiFedartsou** [fastlane/fastlane#4554]
#4555 Hi! There is very useful changelog_from_git_commits action. But sometimes I need just a changelog from last N commits(for example in some of my cases I don't know what commits should I use for :between key). So, I've added new key to changelog_from_git_commits called :commits_count.

**Comment by TKBurner** [comment]
@SiarheiFedartsou Thanks for working with us. I see we've already engaged you on the PR. I hope you continue to work with us there. Thanks!
