### ISSUE TITLE
deliver not using bundle ID from Appfile

### ISSUE THREAD

**Issue by kylejm** [fastlane/fastlane#456]
I'm making a lane for the Beta target of our app. The only difference between the Beta target and the target that will hit the App Store is the Bundle ID. This is so that we can run both App Store and Beta builds on our iPhones at any one time.

Beta lane in Fastfile looks like this:

```ruby
platform :ios do
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    ipa(scheme: "App Beta")
    deliver(beta: true, skip_deploy: true)
  end
end
```

Appfile looks like this:

```ruby
app_identifier "com.app.store"
apple_id "my@sweet.email"

for_lane "ios beta" do
  app_identifier "com.app.beta"
end
```

`ipa` builds the correct scheme (App Beta) with correct Bundle ID (com.app.beta) but when deliver takes over, this gets printed:
```
Got all information needed to deploy a new update ('') for app 'com.app.store'
```

Any ideas what I have configured wrong? Or if I've missed something?

**Comment by KrauseFx** [comment]
Where do you change the bundle identifier of your app? Setting the `app_identifier` only tells the `fastlane` tools what bundle identifier to expect. It seems like you build it always the same way. You'll need to actually update your project file to use a different bundle identifier.

**Comment by kylejm** [comment]
The `App Beta` scheme/target has a different Info.plist to the `App Store` target/scheme, so it should pick up the correct Bundle ID from there?

**Comment by kylejm** [comment]
I've also noticed that `sigh` is not picking up the information for the `beta` lane from the Appfile

**Comment by kylejm** [comment]
Any more thoughts on this @KrauseFx?  :smile:

**Comment by KrauseFx** [comment]
It seems like something is wrong with the `for_lane`, I'll update this issue as soon as I know more.

**Comment by Intellicode** [comment]
@kylejm, @KrauseFx  I found a solution

Instead of 
```
for_lane "ios beta" do
  app_identifier "com.app.beta"
end
```

Use 
```
for_platform "ios" do
  for_lane "beta" do
    app_identifier "com.app.beta"
  end
end
```

It seems that the blocks are not properly separated into platform/lane when they are defined in the way as described in the documentation. Unfortunately I don't know enough about the project so I wouldn't know where to look how these blocks are used and why the documented method doesn't work.

https://github.com/fastlane/credentials_manager/blob/master/lib/credentials_manager/appfile_config.rb

**Comment by fabiomassimo** [comment]
@Intellicode thanks for your feedback. 

I'll look into this. Since last time I've worked on it version 0.7.0 has been released I just time to have an heads up about the changes and I'll figure out what is going wrong asap.

I'll keep you post.

**Comment by kylejm** [comment]
Thanks @Intellicode, I can confirm that this has fixed the problem. 

And thanks @fabiomassimo for looking in to it further 😁

**Comment by KrauseFx** [comment]
Was the some documentation still using the old syntax

```ruby
for_lane "ios beta" do
  app_identifier "com.app.beta"
end
```

or where do you have this code from?

**Comment by KrauseFx** [comment]
Oh, it's right [here](https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#the-appfile). @fabiomassimo is this an easy thing to fix or do we update the documentation?

**Comment by fabiomassimo** [comment]
@KrauseFx I'm going work on this in a couple of hours. Aiming to deliver later this evening.
I'll do my best to make this fix in next release (__1.14.2__)

**Comment by KrauseFx** [comment]
This should be resolved when updating `sudo gem update credentials_manager` :+1:

**Comment by kylejm** [comment]
This fixes it! \o/

**Comment by fabiomassimo** [comment]
🚀

**Comment by KrauseFx** [comment]
Yeah, so great to hear this is resolved! Thanks again @fabiomassimo :+1:

**Comment by Intellicode** [comment]
Unfortunately, the fix broke the other method of specifying the lane/platform specific configs in app files.

```
14:17:35]: fastlane finished with errors
/usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.7.1/lib/credentials_manager/appfile_config.rb:10:in `rescue in try_fetch_value': uninitialized constant CredentialsManager::AppfileConfig::Helper (NameError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/credentials_manager-0.7.1/lib/credentials_manager/appfile_config.rb:7:in `try_fetch_value'
    from /usr/local/lib/ruby/gems/2.2.0/gems/sigh-0.10.3/lib/sigh/options.rb:33:in `available_options'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/actions/sigh.rb:42:in `available_options'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/configuration_helper.rb:17:in `parse'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:134:in `block (2 levels) in execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/actions/actions_helper.rb:62:in `execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:128:in `block in execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:127:in `chdir'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:127:in `execute_action'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/fast_file.rb:120:in `method_missing'
    from (eval):46:in `block (3 levels) in parse'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/lane.rb:32:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/lane.rb:32:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:50:in `block in execute'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:44:in `chdir'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/runner.rb:44:in `execute'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/lane_manager.rb:36:in `cruise_lane'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/lib/fastlane/command_line_handler.rb:31:in `handle'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/bin/fastlane:35:in `block (2 levels) in run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/bin/fastlane:124:in `run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-1.15.0/bin/fastlane:130:in `<top (required)>'
    from /usr/local/bin/fastlane:23:in `load'
    from /usr/local/bin/fastlane:23:in `<main>’
```

When using the following construct with version `0.7.1`:

```
for_platform "ios" do
  for_lane "beta" do
    app_identifier ".."
  end
end
```

The following worked:
```
  for_lane "ios beta" do
    app_identifier ".."
  end
```

**Comment by fabiomassimo** [comment]
Interesting.
Could you try to use 

```
for_platform :ios do
  for_lane :beta do
    app_identifier ".."
  end
end
```

**Comment by Intellicode** [comment]
That seems to work too, thanks!

**Comment by fabiomassimo** [comment]
I wonder how this bug passed the internal tests.
I'll take care to look up what is going wrong with your configuration.
Thanks for your feedback.

**Comment by KrauseFx** [comment]
@fabiomassimo do you want to add a test and a fix for it or should I do it?

**Comment by fabiomassimo** [comment]
In the official docs https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
We discourage that kind of syntax, therefore I do not see this as a major issue.
I'd like to take care of this but I won't work on it before tomorrow evening.

**Comment by KrauseFx** [comment]
The problem is that we previously had this in the documentation so existing setups still use this kind of syntax. I'll work on a fix today

**Comment by Intellicode** [comment]
Actually, when we tested (on 0.7.1)
```
for_platform :ios do
  for_lane :beta do
    app_identifier ".."
  end
end
``` 
it ignored the app_identifier, instead we use `for_lane "ios beta" ` now for my coworker who is on 0.7.1

**Comment by simoncoulton** [comment]
Currently failing for me too (on the latest fastlane), and doesn't give me the correct app identifier.

```ruby
for_platform :ios do
    for_lane :deploy do
        app_identifier "com.app.prod"
    end
    for_lane :beta do
        app_identifier "com.app.beta"
    end
end
```

Each of those lanes does use a private lane as well

```ruby
lane :beta do
        build(release: false)
end
lane :deploy do
        build(release: true)
end
private_lane :build do |options|
end
```

Wondering if the private lane is somehow overriding it? Is what I'm doing a bit of an edge case?

**Comment by KrauseFx** [comment]
@simoncoulton You are specifying the `for_platform` block but seem to not have a platform in your `Fastfile`? Could you try to wrap the lanes in a `platform` block?

**Comment by simoncoulton** [comment]
Apologies, it's already in a for_platform block, I should have been clearer in that respect. Also using default_platform.

**Comment by KrauseFx** [comment]
I just pushed a new version that should fix those issues, please update using `sudo gem update credentials_manager` :+1:

**Comment by JaviSoto** [comment]
Hi @simoncoulton! Is this still an issue for you? :)

**Comment by KrauseFx** [comment]
This should be solved in the latest releases. Please feel free to reopen if you're still experiencing issues :+1:
