### ISSUE TITLE
Spaceship::Tunes::AppVersion#url uses hard-coded app id

### ISSUE THREAD

**Issue by ravinggenius** [fastlane/fastlane#4565]
### New Issue Checklist

- [✓] Updated fastlane to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`Spaceship::Tunes::AppVersion#url` uses a hard-coded app ID. I looked at the diff, and it used to use `application.apple_id` until last September. See https://github.com/fastlane/fastlane/blob/b7b8b5f960a330e1f0d514da958d6ecf918d5789/lib/spaceship/tunes/app_version.rb#L205.

### Environment

I'm using Spaceship programmatically to build a private gem for internal use. I have `spec.add_runtime_dependency 'spaceship'` in my `*.gemspec`, which Bundler resolves to version `0.26.2`.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
@ravinggenius Thanks for pointing this out and working with us on the PR! Hope you have a great week 👍
