### ISSUE TITLE
update_info_plist does not update CFBundleName

### ISSUE THREAD

**Issue by sainttail** [fastlane/fastlane#4570]
When I use `update_info_plist` like this

```
update_info_plist(
    display_name: app_name,
    plist_path: plist_path,
    xcodeproj: xcodeproj
)
```

Only `CFBundleDisplayName` is updated as in the code [here](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/update_info_plist.rb#L27)
Shouldn't it update both `CFBundleDisplayName` and `CFBundleName`?
or can just expose `name` params passing to `update_info_plist`

I know this maybe a little bit off and we can manually do it in other way but I thinks those 3 properties (`CFBundleIdentifier `, `CFBundleDisplayName `, `CFBundleName`) are the common ones we always change.

Thanks.

**Comment by TKBurner** [comment]
Hi @sainttail! Great to hear from you. Right now CFBundleName is handled via your language support.

CFBundleName (String - iOS, OS X) identifies the short name of the bundle. This name should be less than 16 characters long and be suitable for displaying in the menu bar and the app’s Info window. You can include this key in the InfoPlist.strings file of an appropriate .lproj subdirectory to provide localized values for it. If you localize this key, you should also include the key “CFBundleDisplayName.”
