### ISSUE TITLE
IPA Submit issue

### ISSUE THREAD

**Issue by vikram1234** [fastlane/fastlane#4581]
### New Issue Checklist

- [ fastlane 1.81.0] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Keep giving ratings error, even rathings.json is in fastlane/metadata/ratings.json as below

[
  { "comment": "Cartoon or Fantasy Violence", "level": 1 },
  { "comment": "Realistic Voilence", "level": 1 },
  { "comment": "Prolonged Graphic or Sadistic Realistic", "level": 0 },
  { "comment": "Profanity or Crude Humor", "level": 1 },
  { "comment": "Mature/Suggestive Themes", "level": 1 },
  { "comment": "Horror/Fear Themes", "level": 0 },
  { "comment": "Medical/Treatment Information", "level": 1 },
  { "comment": "Alcohol, Tobacco, or Drug Use or References", "level": 1 },
  { "comment": "Simulated Gambling", "level": 0 },
  { "comment": "Sexual Content or Nudity", "level": 1 },
  { "comment": "Graphic Sexual Content and Nudity", "level": 0 },
  { "type": "boolean", "comment": "Unrestricted Web Access", "level": 0 },
  { "type": "boolean", "comment": "Gambling and Contests", "level": 0 },
  { "comment": "Made for Kids; 1 = Age < 5; 2 = Ages 6-8; 3 = Ages 9 - 11", "level": 0 }
]

Also tried this Format - 
{
  "CARTOON_FANTASY_VIOLENCE": 0,
  "REALISTIC_VIOLENCE": 0,
  "PROLONGED_GRAPHIC_SADISTIC_REALISTIC_VIOLENCE": 0,
  "PROFANITY_CRUDE_HUMOR": 0,
  "MATURE_SUGGESTIVE": 0,
  "HORROR": 0,
  "MEDICAL_TREATMENT_INFO": 0,
  "ALCOHOL_TOBACCO_DRUGS": 0,
  "GAMBLING": 0,
  "SEXUAL_CONTENT_NUDITY": 0,
  "GRAPHIC_SEXUAL_CONTENT_NUDITY": 0,
  "UNRESTRICTED_WEB_ACCESS": 0,
  "GAMBLING_CONTESTS": 0
}

Keep giving following Error...

```
INSERT OUTPUT HERE
[03:37:02]: You must select the level of frequency for each Apple content description in the Ratings section.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 1           |
| 4    | increment_version_number            | 1           |

| 5    | update_info_plist                   | 0           |
| 6    | cert                                | 5           |
| 7    | sigh                                | 7           |
| 8    | pem                                 | 2           |
| 9    | update_project_provisioning         | 1           |
| 10   | gym                                 | 64          |
| 11   | deliver                             | 821         |
+------+-------------------------------------+-------------+

[03:37:02]: fastlane finished with errors

[!] The request could not be completed because:
        You must select the level of frequency for each Apple content description in the Ratings section.


### Configuration Files

{
  "CARTOON_FANTASY_VIOLENCE": 0,
  "REALISTIC_VIOLENCE": 0,
  "PROLONGED_GRAPHIC_SADISTIC_REALISTIC_VIOLENCE": 0,
  "PROFANITY_CRUDE_HUMOR": 0,
  "MATURE_SUGGESTIVE": 0,
  "HORROR": 0,
  "MEDICAL_TREATMENT_INFO": 0,
  "ALCOHOL_TOBACCO_DRUGS": 0,
  "GAMBLING": 0,
  "SEXUAL_CONTENT_NUDITY": 0,
  "GRAPHIC_SEXUAL_CONTENT_NUDITY": 0,
  "UNRESTRICTED_WEB_ACCESS": 0,
  "GAMBLING_CONTESTS": 0
}


Fastfile:
```ruby
# INSERT CONTENT HERE
  deliver(
        force: true,
        app_identifier: ENV["identifer"],
        app_icon: "./fastlane/metadata/deliveryicon.png",
        ipa: "./util/"+ENV["ipaname"],
        submit_for_review: true,
        automatic_release: true,
        force: true,
        metadata_path: "./fastlane/metadata/",
        app_review_information: ({
        first_name: "test",
        last_name: "test",
        phone_number: "+43 4444",
        email_address: "abc@abc.com",
        demo_user: "demoUser",
        notes: "This is app release notes",
        demo_password: "demoPass"
      })
    )

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by vikram1234** [comment]
Able to move over but other issue..

**Comment by TKBurner** [comment]
@vikram1234 Thanks for following up. I updated your other thread. 👍
