### ISSUE TITLE
Crash report '12a1c09307721d0e83740014b50fef37' when "deliver run --skip_screenshots -f" response.rb:357:in `finish': [!] buffer error (Zlib::BufError)

### ISSUE THREAD

**Issue by mywander** [fastlane/fastlane#4586]
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '12a1c09307721d0e83740014b50fef37'
The crash report has been stored locally '/tmp/sentry_12a1c09307721d0e83740014b50fef37.json'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish': [!] buffer error (Zlib::BufError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1132:in `block in get'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1131:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/tunes/tunes_client.rb:121:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/runner.rb:14:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/runner.rb:7:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/commands_generator.rb:49:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/commands_generator.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by liuyuanming** [comment]
[16:05:03]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'cf233aaa441f0aa835033fc5bab621bf'
The crash report has been stored locally '/tmp/sentry_cf233aaa441f0aa835033fc5bab621bf.json'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish': [!] buffer error (Zlib::BufError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1132:in `block in get'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1131:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/runner.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/sigh.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:173:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:158:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:157:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:111:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/fast_file.rb:130:in `method_missing'
	from Fastfile:35:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.87.0/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

as the same as 1f.

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by rpplusplus** [comment]
I have same problem. My Crash Report id is: f63e7c56090f8786b8bf82bf58cd4fbb

**Comment by asfalcone** [comment]
Same error as #4610. Possibly related.

**Comment by TKBurner** [comment]
@rpplusplus @mywander  We are going to track this on #4610. Thanks so much for reporting, it really helps to know when something is affecting multiple users! 👍
