### ISSUE TITLE
Pem not using updated username and app_identifier from Appfile(Updated using ENV variable) when creating pem for 2 different accounts in same lane

### ISSUE THREAD

**Issue by prgnshptlklp** [fastlane/fastlane#4588]
I am using produce, pem and sigh actions for 2 different accounts in same lane.
I am using ENV variables to update apple_id and app_identifier in AppFile
All other actions(produce, sigh) are using new AppFile settings while pem is using old settings of Appfile.

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by KrauseFx** [comment]
Please share all configuration files, output and how you run fastlane. I'll close this issue for now, feel free to re-open once you updated the issue 👍 Thanks helping us resolving this issue
