### ISSUE TITLE
Feature [Spaceship] : App primary language

### ISSUE THREAD

**Issue by Wojcik** [fastlane/fastlane#4592]
Hi. We have 100+ apps in the app store and that apps delivered with 4+ languages. All of them have different primary languages. It would be great if the Spaceship will be able to retrieve which language is set as primary so fastlane will set it on app update.

**Comment by KrauseFx** [comment]
Thanks for the suggestion. This is not something we plan on working, however feel free to extend spaceship to expose this value, and submit a pull request. We're more than happy to merge this into the `fastlane` repository 👍

**Comment by bolom** [comment]
i have needed me too for my currenct project i have extended spaceship to add 

- available_primary_locale_codes
- primary_locale_code

**Comment by TKBurner** [comment]
@bolom Awesome! We'll check out your PR. Thanks for including tests 👍

**Comment by bolom** [comment]
@TKBurner tks but my tests are pretty bad. not sure how to fix them

https://github.com/fastlane/fastlane/pull/4754

**Comment by TKBurner** [comment]
@bolom Thanks for working with us on your pull request. Don't worry we'll keep working with you on the test coverage 👍

**Comment by bolom** [comment]
@TKBurner tks a lot !
