### ISSUE TITLE
Someone help me with this error when trying to send app for testflight via pilot?

### ISSUE THREAD

**Issue by douglasalexandre** [fastlane/fastlane#4593]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

pilot upload        
[09:42:36]: Login to iTunes Connect (Myappleid@xxxxxx.com.br)
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
🙊  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:923:in `connect'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/tunes/tunes_client.rb:121:in `send_login_request'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/spaceship-0.26.2/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/pilot-1.5.1/lib/pilot/manager.rb:15:in `login'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/pilot-1.5.1/lib/pilot/manager.rb:8:in `start'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/pilot-1.5.1/lib/pilot/build_manager.rb:4:in `upload'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/pilot-1.5.1/lib/pilot/commands_generator.rb:60:in `block (2 levels) in run'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/pilot-1.5.1/lib/pilot/commands_generator.rb:126:in `run'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/pilot-1.5.1/lib/pilot/commands_generator.rb:16:in `start'
	from /Users/Sense/.rvm/gems/ruby-2.2.2@global/gems/pilot-1.5.1/bin/pilot:6:in `<top (required)>'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/bin/pilot:23:in `load'
	from /Users/Sense/.rvm/rubies/ruby-2.2.2/bin/pilot:23:in `<main>'
	from /Users/Sense/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Sense/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by vpolouchkine** [comment]
Does this help? https://github.com/fastlane/fastlane/blob/master/fastlane/docs/FAQs.md#im-getting-an-ssl-error

**Comment by KrauseFx** [comment]
@douglasalexandre any updates on this? I'll close this issue for now, feel free to re-open if you're still experiencing it 👍

**Comment by douglasalexandre** [comment]
Hi @KrauseFx , @vpolouchkine 
The problem still remains, did the steps of link, but has not yet been resolved.

**Comment by douglasalexandre** [comment]
@KrauseFx @vpolouchkine I'm verify. I think that i know what the problem is.
I gonna check, and see if it fix it. I will let you know my progress.

**Comment by TKBurner** [comment]
@douglasalexandre Thanks for letting us know. Please do let me know how it turns out 👍

**Comment by douglasalexandre** [comment]
@KrauseFx @TKBurner @vpolouchkine I had configured an openssh certificate, but in time of to build, my system did not use the current version, but the oldest. Problem solved. 👍 Very thanks for help me. :) Now i will configure Pilot. This is my first time using pilot. Some trick?

**Comment by TKBurner** [comment]
@douglasalexandre Glad to hear you got up and running. Let me know if you run into any specific issues getting up and running. Thanks!
