### ISSUE TITLE
Adding pagination to "sigh download_all" to enable downloading large accounts

### ISSUE THREAD

**Issue by LizCira** [fastlane/fastlane#4605]
Issue discussed here: https://github.com/fastlane/fastlane/issues/4280

The problem is that for accounts with 300+ profiles, Apple's pagination kills the connection and "sigh download_all" fails. 

Works successfully with this commit, which modifies both spaceship and sigh: 
https://github.com/LizCira/fastlane/commit/2cead22aebb108955e36e1e7d479b3f3919a494f
(That commit also adds a flag to keep original profile names instead of using Fastlane's names, and it unlocks the security keychain in fastlane core to allow it to work with multi-executor CI systems. I'd separate these features and some logging would be removed for a pull request.)

Our use case is syncing profiles across several build servers for use by a large team across many apps, and sigh is a great tool! Formerly we used the cupertino gem but it's broken. 

This is the error sigh hits when trying to download profiles from an account with over 1000 profiles: 

```
usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:158:in `rescue in rbuf_fill': [!] Net::ReadTimeout (Faraday::TimeoutError)
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:152:in `rbuf_fill'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:134:in `readuntil'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/protocol.rb:144:in `readline'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:39:in `read_status_line'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http/response.rb:28:in `read_new'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1408:in `block in transport_request'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `catch'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1405:in `transport_request'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1378:in `request'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1371:in `block in request'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:853:in `start'
	from /usr/local/rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:1369:in `request'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.26.1/lib/spaceship/client.rb:404:in `block in send_request'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.26.1/lib/spaceship/client.rb:322:in `with_retry'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.26.1/lib/spaceship/client.rb:403:in `send_request'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.26.1/lib/spaceship/client.rb:379:in `request'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.26.1/lib/spaceship/portal/portal_client.rb:317:in `provisioning_profiles'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/spaceship-0.26.1/lib/spaceship/portal/provisioning_profile.rb:246:in `all'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/sigh-1.6.1/lib/sigh/download_all.rb:10:in `download_all'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/sigh-1.6.1/lib/sigh/manager.rb:34:in `download_all'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/sigh-1.6.1/bin/sigh:45:in `block (2 levels) in run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/fastlane_core-0.41.2/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/sigh-1.6.1/bin/sigh:93:in `run'
	from /usr/local/rvm/gems/ruby-2.1.2/gems/sigh-1.6.1/bin/sigh:111:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/sigh:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/sigh:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by TKBurner** [comment]
@LizCira Thanks for pointing this out. So to be clear does your commit fix this or do you still get the error? I looped in the core team so we can take a look 👍

**Comment by LizCira** [comment]
@TKBurner yes that commit fixes it for us, we're happily using it to sync profiles on our production build servers now--if you clone the fork and run "sigh download_all" on a 1k+ profile account, it will still work. Previous behavior was the " Net::ReadTimeout (Faraday::TimeoutError)"  error in the original comment. 

It sets the pagination count to 30 per page and loops through (the pagination count is set on line 332 here: spaceship/lib/spaceship/portal/portal_client.rb) One question I had was weather changing that variable from it's default 500 would affect any other features, but so far everything I've tested works. We also use it to download much smaller accounts with no change in behavior. 

I'd love to clean up some of the logging and make a proper pull request. :smile:

That fork also ads a "-p" flag in sigh to keep original profile names, so running "sigh download_all -p" downloads all profiles with their original Apple dev portal names instead of the Sigh generated names, but these are two separate features and I can split them up.

**Comment by TKBurner** [comment]
Hi @LizCira Thanks for following up. I think it'd be great if you can put together a pull request. I'm not sure how fast we'll be able to provide feedback but we will get to it! Hope you have a great weekend 👍

**Comment by LizCira** [comment]
I submitted one here, hope you had a great weekend too!
https://github.com/fastlane/fastlane/pull/4670

**Comment by TKBurner** [comment]
@LizCira I see Felix had a chance to follow up on your PR. If you can take care of those changes, we'd love to continue to work with you. Thanks!

**Comment by sfransen** [comment]
Thank you so much this solved my problem. There is one thing more need to make it fast is tho split the download to a different loop as it really slow to update the ID on each provision profile to download them
 so I just remove the code from the def update! 
        # We need to fetch the provisioning profile again, as the ID changes
#         profile = Spaceship::ProvisioningProfile.all(mac: mac?).find do |p|
#           p.name == self.name # we can use the name as it's valid
#         end
# 
#         return profile
 and then add a extra step at the end of download all to really download the profiles after I update all devices in each profile. I now have a working setup thanks again.

**Comment by LizCira** [comment]
@sfransen glad it helped you too! Is the code above to search for a specific profile? It seems to me that would be a different, also useful feature (not "sigh download_all")
