### ISSUE TITLE
Character languages showing ??? for screenshot

### ISSUE THREAD

**Issue by LoganWright** [fastlane/fastlane#4606]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

On character languages, for this specific screenshot, I can't get anything but question marks (screen redacted for client)

![iphone6-3-firmwareupdate_framed](https://cloud.githubusercontent.com/assets/5750489/15162307/32341470-16d0-11e6-8b3c-1fdb93811980.png)

I don't really know where to begin debugging this one, I've been doing standard restarts, fresh installs, and guess n check.

If there's not a good resolution, maybe some direction that might help me track down the problem would be helpful.

Thanks for the great tools!

- Logan

### Languages Affected

- ja, ko, th, zh-Hans, zh-Hant

### Is your font correct?

Yes, I have appropriate font packs setup. 3 of the 4 screenshots work perfectly.

### Is it the title?

No, if I change the title to something that is working on other frames, it still shows question marks.

##### Complete output when running fastlane, including the stack trace and command used

I'm calling `frameit`, I can't list output because the files are named in a way that would implicate my client. 

I'm seeing nothing out of the ordinary, no errors, no output aside from:

```
Added frame: `path/to/new/frame`
```

### Configuration Files

Framefile.json:
```ruby
{
  "default": {
    "keyword": {
      "fonts": [
        {
          "font": "./fonts/GothamSSm-Bold.otf",
          "supported": ["da", "de-DE", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "it", "nl-NL", "no", "pt-BR", "pt-PT", "ru", "sv"]
        },
        {
          "font": "./fonts/NotoSansThai-Bold.ttf",
          "supported": ["th"]
        },
        {
          "font": "./fonts/NotoSansCJKjp-Bold.otf",
          "supported": ["ja"]
        },
        {
          "font": "./fonts/NotoSansCJKkr-Bold.otf",
          "supported": ["ko"]
        },
        {
          "font": "./fonts/NotoSansCJKsc-Bold.otf",
          "supported": ["zh-Hans"]
        },
        {
          "font": "./fonts/NotoSansCJKtc-Bold.otf",
          "supported": ["zh-Hant"]
        }
      ]
    },
    "title": {
      "fonts": [
        {
          "font": "./fonts/GothamSSm-Bold.otf",
          "supported": ["da", "de-DE", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "es-MX", "fi", "fr-CA", "fr-FR", "it", "nl-NL", "no", "pt-BR", "pt-PT", "ru", "sv"]
        },
        {
          "font": "./fonts/NotoSansThai-Bold.ttf",
          "supported": ["th"]
        },
        {
          "font": "./fonts/NotoSansCJKjp-Bold.otf",
          "supported": ["ja"]
        },
        {
          "font": "./fonts/NotoSansCJKkr-Bold.otf",
          "supported": ["ko"]
        },
        {
          "font": "./fonts/NotoSansCJKsc-Bold.otf",
          "supported": ["zh-Hans"]
        },
        {
          "font": "./fonts/NotoSansCJKtc-Bold.otf",
          "supported": ["zh-Hant"]
        }
      ],
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 50
  },

  "data": [
    {
      "filter": "0-Home",
      "keyword": {
        "color": "#d21559"
      }
    },
    {
      "filter": "1",
      "keyword": {
        "color": "#feb909"
      }
    },
    {
      "filter": "2",
      "keyword": {
        "color": "#aa4dbc"
      }
    },
    {
      "filter": "3",
      "keyword": {
        "color": "#aa4dbc"
      }
    }
  ]
}
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
I'm pretty sure this has something to with your font `"font": "./fonts/GothamSSm-Bold.otf"`, can you try removing the custom font from your Framefile and see if that works

**Comment by LoganWright** [comment]
@KrauseFx Removing that font seems to have fixed the problem, but now the standard alphabetic frames are not in the desired font.

Is there a workaround where I could have both? If not, I can check w/ design about whether or not the alternative default font is acceptable.

**Comment by TKBurner** [comment]
@LoganWright Thanks for letting us know. It looks like there might be something unexpected with the font file. We'll keep this on our radar but it's going to be hard to fix until we get more reports. Really glad you are using Fastlane and always feel free to reach out with any questions 👍

**Comment by LoganWright** [comment]
@TKBurner @KrauseFx 

I appreciate the support, and was able to get to the desired effect by setting my framefile fonts section as such:

```
    "title": {
      "fonts": [
        {
          "font": "./fonts/NotoSansThai-Bold.ttf",
          "supported": ["th"]
        },
        {
          "font": "./fonts/NotoSansCJKjp-Bold.otf",
          "supported": ["ja"]
        },
        {
          "font": "./fonts/NotoSansCJKkr-Bold.otf",
          "supported": ["ko"]
        },
        {
          "font": "./fonts/NotoSansCJKsc-Bold.otf",
          "supported": ["zh-Hans"]
        },
        {
          "font": "./fonts/NotoSansCJKtc-Bold.otf",
          "supported": ["zh-Hant"]
        },
        {
          "font": "./fonts/GothamSSm-Bold.otf"
        }
      ],
      "color": "#FFFFFF"
    }
```

Something about putting the default font on the bottom _without_ specifying supported languages explicitly seems to make it work.

Hopefully that gives the devs some direction towards the problem, or helps others in a similar boat.

**Comment by TKBurner** [comment]
@LoganWright Thanks for sharing that solution. It'll help other Fastlane developers 👍

**Comment by JosephDuffy** [comment]
I am having the same issue here, but neither solution worked for me. I've got my Framefile.json as follows:

```
{
    "default": {
        "title": {
            "fonts": [
                {
                    "font": "./fonts/NotoSansCJKjp-Bold.otf",
                    "supported": ["ja"]
                },
                {
                    "font": "./fonts/NotoSansCJKjp-Bold.otf",
                    "supported": ["ko"]
                },
                {
                    "font": "./fonts/NotoSansCJKjp-Bold.otf",
                    "supported": ["zh-Hans"]
                },
                {
                    "font": "fonts/SF-UI-Display-Medium.otf"
                }
            ],
            "color": "#000033"
        },
        "background": "./background.jpg",
        "padding": 50,
        "show_complete_frame": false
    },

    "data": []
}
```

I have also tried removing the `fonts` block:

```
{
    "default": {
        "title": {
            "color": "#000033"
        },
        "background": "./background.jpg",
        "padding": 50,
        "show_complete_frame": false
    },

    "data": []
}
```

However, I still get question marks for Japanese, Korean, and Chinese (simplified). I have also tried multiple fonts, including Arial Unicode, PingFang, SF-UI-Display-Medium, and SFNSText-Medium.

**Comment by TKBurner** [comment]
Hi @JosephDuffy Thanks for reaching out. What happens when you remove the font name completely and let the default take over?
