### ISSUE TITLE
[Question] Are there any drawback installing fastlane without sudo?

### ISSUE THREAD

**Issue by wuaschtikus** [fastlane/fastlane#4607]
Hi guys,

I am using fastlane at home without any problems using a sudo installation. Coming to my workplace it is a NOGO to install command line tools with sudo. I am working in a high security environment without any chance to get sudo / elevated rights on my CI. This is definitely a DEV OPS topic, but it also addresses security specific issues.

My question is - does anyone has experience using a non sudo installation of fastlane in combination with jenkins?

Many organizations have enforced segregation of duties or least privilege principles. I also would find it a great idea to strip sudo from the docs of fastlane. What is your opinion?

Cheers!

**Comment by vpolouchkine** [comment]
I'm not super familiar with jenkins, but it's certainly possible to use fastlane without sudo.

**Comment by KrauseFx** [comment]
It's all fine, depends on what works best for your setup 👍
