### ISSUE TITLE
Missing enableAddressSanitizer option

### ISSUE THREAD

**Issue by mauriciomeirelles** [fastlane/fastlane#4616]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm migrating the shell script that we use today at the company to Fastlane (YAY!). But we use `enableAddressSanitizer` when testing and scan don't have this option yet.

**Comment by mfurtak** [comment]
Accepted in https://github.com/fastlane/fastlane/pull/4615 - thanks very much! 🎊
