### ISSUE TITLE
Refresh dsyms without Crashlytics beta

### ISSUE THREAD

**Issue by williamsjj** [fastlane/fastlane#4618]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

How can I set my Crashlytics API key without uploading to Crashlytics beta? All I want to do is refresh bitcode dsyms.

**Comment by KrauseFx** [comment]
Please share your `Fastfile`. You can upload files without providing an api key
