### ISSUE TITLE
missing '-n, --disable-notify' option from deploygate action

### ISSUE THREAD

**Issue by toshi0383** [fastlane/fastlane#462]
It would be really nice if `deploygate` action has `--desable-notify` option.

```-n, --disable_notify disable notification```

I'm using my shell as a workaround for now.
https://gist.github.com/toshi0383/9a56c6f3c627c4f9ffc7

**Comment by ohwutup** [comment]
hey @toshi0383! thanks for the feature request, i am going to close this for now and share the idea with the team. we will reopen the issue as we get a chance to revisit this. feel free to checkout [countdown](https://github.com/fastlane/countdown) if you would like to tackle this in a pull request! thanks!

**Comment by toshi0383** [comment]
@ohwutup Thanks. What is countdown for ??

**Comment by ohwutup** [comment]
@toshi0383 it is just the repo that contains references to all the sub tools so you can do all your editing under one directory structure!
