### ISSUE TITLE
Snapshot runs multiple (6) times, produces many copies of same screenshot

### ISSUE THREAD

**Issue by Drarok** [fastlane/fastlane#4620]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm attempting to use Snapshot, but for some reason it takes my screenshots multiple times. Seemingly 6 times currently – I've gone as far as commenting out all but one screenshot in order for it to complete quickly enough for me to get a result.

The filename formats are like this:

     iPhone6-0-MyScreenshot
     iPhone6-1-MyScreenshot
     iPhone6-2-MyScreenshot
     iPhone6-3-MyScreenshot
     iPhone6-4-MyScreenshot
     iPhone6-5-MyScreenshot

##### Complete output when running fastlane, including the stack trace and command used

I used a gist since the output is so long: https://gist.github.com/Drarok/debe742ad20882fed8320649b4de0136

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:
```ruby
devices([
  # "iPhone 4s",
  # "iPhone 5",
  "iPhone 6",
  # "iPhone 6 Plus",
  # "iPad Retina",
  # "iPad Pro"
])

languages([
  "en-US"
])

launch_arguments([
  "-com.UITesting.username", "snapshot@example.tld",
  "-com.UITesting.password", "password"
])

scheme "Snapshot"

output_directory "./screenshots"
```

### Environment

fastlane version (run `fastlane -v`): `fastlane 1.88.0` `snapshot 1.12.2`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by KrauseFx** [comment]
You didn't share your actual UI tests

**Comment by Drarok** [comment]
```obj-c
#import <XCTest/XCTest.h>

#import "ProjectNameUITests-Bridging-Header.h"
#import "Snapshot-Swift.h"

@interface ProjectNameUITests : XCTestCase

@end

@implementation BlokStopUITests

- (void)setUp {
    [super setUp];

    self.continueAfterFailure = NO;

    XCUIApplication *app = [[XCUIApplication alloc] init];
    app.launchArguments = @[
        @"-uk.co.pojectname.UITesting.username", @"snapshot@example.tld",
        @"-uk.co.projectname.UITesting.password", @"password",
    ];
    [Snapshot setupSnapshot:app];
    [app launch];
}


- (void)testSnapshotVehicleList {
    [Snapshot snapshot:@"01 Vehicle List" waitForLoadingIndicator:YES];
}
```

**Comment by Drarok** [comment]
I've tried `snapshot reset_simulators`, which removed a lot of sims, but hasn't fixed the issue.

**Comment by Drarok** [comment]
Ah _ha!_

```Ruby
launch_arguments([
  "-uk.co.projectname.UITesting.username", "snapshot@example.tld",
  "-uk.co.projectname.UITesting.password", "password"
])
```

```Ruby
 def config_launch_arguments
      launch_arguments = Array(Snapshot.config[:launch_arguments])
      # if more than 1 set of arguments, use a tuple with an index
      if launch_arguments.count == 1
        [launch_arguments]
      else
        launch_arguments.map.with_index { |e, i| [i, e] }
      end
    end
```

This is [treated as a set](https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/runner.rb#L36), resulting in the following calls:

```
run_for_device_and_language(en-US, , iPhone 4s, [0, "-uk.co.projectname.UITesting.username"])
run_for_device_and_language(en-US, , iPhone 4s, [1, "snapshot@example.tld"])
run_for_device_and_language(en-US, , iPhone 4s, [2, "-uk.co.projectname.UITesting.password"])
run_for_device_and_language(en-US, , iPhone 4s, [3, "password"])
```

This fixes it, but should launch_arguments cause multiple launches, or is that a bug?

```Ruby
launch_arguments([
  [
    "-uk.co.projectname.UITesting.username", "snapshot@example.tld",
    "-uk.co.projectname.UITesting.password", "password"
  ]
])
```

**Comment by Drarok** [comment]
Furthermore, the filename has the launch arguments in when using the above workaround. I've moved all my launch arguments into my UITest launch code instead.

**Comment by TKBurner** [comment]
@Drarok Thanks for following up. I'm glad you were able to figure this out. Hope you have a wonderful weekend!

**Comment by Drarok** [comment]
I'm not sure this issue should be closed though? I've worked around it by _not using a documented feature._

**Comment by KrauseFx** [comment]
https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments

> Specify multiple argument strings and snapshot will generate screenshots for each combination of arguments, devices, and languages

That's by design, when passing 2 arguments, `snapshot` will iterate over them 👍

**Comment by Drarok** [comment]
Ah, somehow I totally missed that, sorry.

Thanks again.

**Comment by KrauseFx** [comment]
Happy to help 👍
