### ISSUE TITLE
 Provisioning profile 'xxxxxxx' is not available on the Developer Portal

### ISSUE THREAD

**Issue by luisrodrigo** [fastlane/fastlane#4621]
### New Issue Checklist
- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I'm develop one app in iOS and I have a problem with the match option, when I put the "match development" this show me a error: (I send you an image with this error)

I do not know which is the reason or what I have doing for resolve that.

I hope that you can help me or give me a way to clear this issue.
##### Complete output when running fastlane, including the stack trace and command used

```
[17:39:55]: Provisioning profile '7336147a-257c-4a3d-b9be-087a67b8cee9' is not available on the Developer Portal
[17:39:55]: for the user dev@chatloud.com
[17:39:55]: Make sure to use the same user and team every time you run 'match' for this
[17:39:55]: Git repository. This might be caused by deleting the provisioning profile on the Dev Portal
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by mfurtak** [comment]
Hi @luisrodrigo 👋 

One possible explanation is that you're using a different account or team than was used when originally setting up this app with `match`. Please confirm that you have the right account info! 👍 

Another possibility is that the provisioning profile that `match` created for you was deleted from the developer portal. This could happen if someone used the Fix Issue button in Xcode.

If that is the case, then it would be best to allow `match` to start over again. You can run

```
match nuke development
```

to reset things, and then run

```
match development
```

to set them back up again. Then, make sure your code signing settings are correct in Xcode. Let me know what you find! 🔍

**Comment by sainttail** [comment]
In my case, I think it is probably because the `fix issue` button.

Is there a way to to only renew that specific provisioning profile instead of `nuke` all `distribution` because we also have some distribution profile that we don't want to remove them.

I don't know `nuke` all will cause a problem for us or not because all the our distribution profile is `enterprise` distribution and it may cause the app to be unable to install for current app version if we `nuke` all the profile (Someone please correct me if I'm wrong)

Thanks.

**Comment by davideme** [comment]
Any new solution about this ? I have the same problem, and I can't nuke all ours distribution profile, because only one project is using match. And I only want to nuke this distribution profile.

**Comment by philipshurpik** [comment]
@davideme You can manually delete profiles (dev and appstore) from your certs repo and then recreate it with 
`match development -a com.company.appname`

**Comment by davideme** [comment]
I ran in the same issue
```
[10:43:20]: Installing provisioning profile...
[10:43:21]: Provisioning profile 'REDACTED' is not available on the Developer Portal
[10:43:21]: for the user redacted@gokarumi.com
```

This is a blocker for my usage of fastlane, I can't use it anymore, and `nuke distribution` is not an option.

**Comment by TKBurner** [comment]
@davideme What happens if you delete the profile on ADP? It seems like if you delete it in the repo and there you'll be able to get up and running.

**Comment by pernilla** [comment]
I have also this issue. Very weird. In my case it says: 

`Provisioning profile 'a8c3c555-796e-4c36-ae58-963f9b1e3655' is not available on the Developer Portal`

My fastlane script does the following: 

`desc "Submits a new Beta Build to Apple TestFlight"
  lane :beta do

    match(type: "appstore")
    gym(scheme: "Beta") 
    pilot(app_identifier: "com.myapp.beta") 
  end`

In the log when I run fastlane ios beta --verbose I see: 

`Setting environment variable 'sigh_com.nexusgroup.personal_appstore' to 'a8c3c555-796e-4c36-ae58-963f9b1e3655'`

I don't know where this comes from. I've nuked everything and recreated. That doesn't change anything.

**Comment by TKBurner** [comment]
@pernilla Thanks for updating this. Have you run match development for this app previously since the nuke?

**Comment by KrauseFx** [comment]
Has everyone clicked the `Fix Issue` button or is this is different error?

**Comment by pernilla** [comment]
I did run match nuke and match development twice, the second time it worked! Weird.  will look at the fix me, not sure yet.

**Comment by pernilla** [comment]
We haven't run fis issue button and yesterday I ran match nuke again and match development/appstore/adhoc and it worked as long I was in the same repo. This morning when I check out the source code in a new folder and try to run it (even my colleague) we receive 

```
"Provisioning profile 'db214085-69ab-4ebe-8c4c-87dd51dbee74' is not available on the Developer Portal". I don't understand what we're doing wrong. 
```

Also, trying the source that worked yesterday resulted in: 

```
"An error occured while verifying your certificates and profiles with the Apple Developer Portal.
[09:59:39]: If you already have your certificates stored in git, you can run `match` in readonly mode
[09:59:39]: to just install the certificates and profiles without accessing the Dev Portal."
```
Full log: 

```
fastlane ios build
[09:59:24]: -------------------------------------------------
[09:59:24]: --- Step: Verifying required fastlane version ---
[09:59:24]: -------------------------------------------------
[09:59:24]: fastlane version valid
[09:59:24]: ------------------------------
[09:59:24]: --- Step: default_platform ---
[09:59:24]: ------------------------------
[09:59:25]: Driving the lane 'ios build' 🚀
[09:59:25]: -------------------
[09:59:25]: --- Step: match ---
[09:59:25]: -------------------

+-----------------------+------------------------------------------------------------+
|                              Summary for match 0.7.0                               |
+-----------------------+------------------------------------------------------------+
| app_identifier        | com.myapp.personal                                    |
| type                  | development                                                |
| git_url               | ssh://source_server/git/repo.git |
| username              | user@apple.com                               |
| git_branch            | master                                                     |
| keychain_name         | login.keychain                                             |
| readonly              | false                                                      |
| team_id               | ZFTYUIJSTS                                                 |
| verbose               | false                                                      |
| force                 | false                                                      |
| shallow_clone         | false                                                      |
| force_for_new_devices | false                                                      |
| skip_docs             | false                                                      |
+-----------------------+------------------------------------------------------------+

[09:59:25]: Cloning remote git repo...
[09:59:26]: 🔓  Successfully decrypted certificates repo
[09:59:26]: Verifying that the certificate and profile are still valid on the Dev Portal...
[09:59:30]: Installing certificate...
[09:59:31]: Installing provisioning profile...
[09:59:39]: An error occured while verifying your certificates and profiles with the Apple Developer Portal.
[09:59:39]: If you already have your certificates stored in git, you can run `match` in readonly mode
[09:59:39]: to just install the certificates and profiles without accessing the Dev Portal.
[09:59:39]: To do so, just pass `readonly: true` to your match call.
[09:59:39]: 🔒  Successfully encrypted certificates repo

#######################################################################
# match 0.8.0 is available. You are on 0.7.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update match'.
#######################################################################

0.8.0 Updated for new API
- Update _match_ to lazy load certificates and devices to fix performance issues with the new API 🚀
- Update _match_ to work with the latest release of _sigh_

Update using 'sudo gem update match'
[09:59:40]: Variable Dump:
[09:59:40]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build"}
[09:59:40]: {"responseId"=>"81deebf4-9ccb-4586-a3c2-30cbf785cf94", "resultCode"=>8100, "resultString"=>"webservice.provprofile.NotFoundById", "userString"=>"There is no provisioning profile with ID &#x27;36N5Y79XGP&#x27; on this team.", "creationTimestamp"=>"2016-09-21T07:57:13Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/getProvisioningProfile.action", "httpCode"=>200}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 15          |
+------+-------------------------------------+-------------+

[09:59:40]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new

[!] Apple provided the following error info:
	webservice.provprofile.NotFoundById
	There is no provisioning profile with ID &#x27;36N5Y79XGP&#x27; on this team.
```

**Comment by pernilla** [comment]
Our fastfile: 

```
fastlane_version "1.102.0"

default_platform :ios

platform :ios do

  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(app_identifier: "com.myapp.personal", type: "development")
    match(app_identifier: "com.myapp.personal", type: "adhoc")
    match(app_identifier: "com.myapp.personal", type: "appstore")
  end

  lane :build do
    match(app_identifier: "com.myapp.personal", type: "development") 
    gym(scheme: "release") 
  end

end
```

**Comment by KrauseFx** [comment]
@pernilla You're using an old version of _match_, could you update to the latest one?

**Comment by pernilla** [comment]
Yes, I've updated match. After many if´s and but´s we managed to fix fastlane to work via command line. But we do not manage to get the other developers to get a valid signature in XCode. This is really frustrating. I've followed the guides for XCode https://docs.fastlane.tools/codesigning/XcodeProject/  and https://docs.fastlane.tools/codesigning/Troubleshooting/. We've removed the certificates in key chain, cleaned everyhing out, even removed the account in XCode, restarted computer, added the account again but still my colleagues can't publish or deploy in XCode. For me I get following in [XCode](https://www.dropbox.com/s/5qqmxbwvhneftyt/fastlane_2.png?dl=0) and my colleague get the [this](https://www.dropbox.com/s/gyhroojkxk3ucz0/fastlane_1.png?dl=0). I don't know how to solve this. 

Can we somehow reset the repo and certificates for a user? I thought if we also forced fastlane to download everything from scratch again it might work so we deleted the key in the keychain. But fastlane still works and doesn't ask for credentials. Which I find weird. 

Also, the match provisioning profiles becomes invalid pretty much once a day. I can't figure that out either.

**Comment by alibasta** [comment]
I can reproduce the behavior that the provisioning profile becomes invalid pretty often a day. Any idea? I'm using latest fastlane / match version.

By the way: shouldn't this issues be reopened?

**Comment by sebasbad** [comment]
Id you've deleted a development provisioning profile that was in the match repo, you can update the match repo using the following options: match development -a com.myapp.personal --force

**Comment by TKBurner** [comment]
@pernilla @alibasta Have you tried using `read_only: true` for computers that don't need to directly login to iTC? Thanks!

**Comment by alibasta** [comment]
@TKBurner I'm currently the only person on that project. So no other computers.

I've got the problem since Xcode 8.

**Comment by mdsb100** [comment]
Why close??? I have same issues

**Comment by mdsb100** [comment]
@fastlane-bot please reopen

**Comment by pernilla** [comment]
@TKBurner No, but how should that work? Should I configure fastlane for different computers? It's enough with one person having these problems in the team and he/her sets automatically signing to true to solve the problem, then he/her automatically invalidates the profiles for the rest of us. So it you can elaborate how we could set `read_only: true` for only some users that would be nice. 

For us, we managed to work it out with a lane for certs (the documentation could be clearer about all the necessary steps): 

```
  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
any time a new device is added in the Apple Developer Portal.
  lane :certs do
    match(app_identifier: "yourapp", type: “development”, force_for_new_devices:true)
  end
```

**Comment by TKBurner** [comment]
Hi @pernilla Thanks for following up. When they run `match` to pull your profiles down just add that read_only parameter. So one developer will be able to connect to iTC without the read_only: true set, but the rest run

```
lane :certs do
    match(app_identifier: "yourapp", type: “development”, force_for_new_devices:true, read_only:true)
  end
```

or

`match development --readonly`

**Comment by hlung** [comment]
@philipshurpik omg your suggestion works! delete pp and recreate

**Comment by TKBurner** [comment]
@hlung Awesome! Glad to hear you got up and running. Thanks @philipshurpik 👍 👍 💯

**Comment by hlung** [comment]
But I think `match` should be able to ask to recreate if the provisioning if not found on dev portal (y/n). The first thing that came to my mind at that time was to nuke everything (recreate the certs) :(.

**Comment by jaroslavas** [comment]
Confirm, that manually deleting everything from a git repo, fixes the problem. Maybe we should have a possibility to do it via match itself?

**Comment by pernilla** [comment]
I'm still kind of confused of this. I've set match to readonly: true, but now when I run it and I don't have the profiles on my machine I get: 

```
No matching provisioning profiles found and can not create a new one because you enabled `readonly`. Check the output above for more information.
```

Isn't this the whole idea that you should be able to run this command for other team members to retrieve the certificates easily? Otherwise I don't understand this command and what I should use it for? Or should other team members install them from repository via command-line? 

Which, when trying to install cert by clicking it in finder, it says "An error occurred. Unable to import item". What is the correct way to get your team members to download the profiles?

**Comment by hjanuschka** [comment]
@pernilla 
in the first run you need match to generate 1 signing identiy (per git repo)
once one is generated, which in your case fails because of readonly, the signing identity will be placed crypted in the git repo. and other developers doing the same `match` call, with same git-repo - will retreive the signing identity from the git repo.


does that help you

**Comment by pernilla** [comment]
Yes, it does. But it still confusing. Because if I understand it right I will have to distribute the account I used to set up apple certificates with which means that people need to have access to that account. Which means they have access to that account and if they have some problems they can in xcode press "Automatically manage signing" and invalidate the certs again. It would be nicer if I could differentiate between the accounts; one that is used to create certificates and profiles, and one with less privileges to only retrieve the certificates. But maybe that's not possible? And what is the recommended way if you have multiple apps using the same certificate? Or is it recommended to use different certificates?

**Comment by pernilla** [comment]
Also, if following this codesigning guide [here](https://codesigning.guide/) we're trying to import the keys in keychain. And keychain says the format is unknown.

**Comment by colinramsay** [comment]
I see this issue too. We can use `readonly` to do a build but if we add a device to the provisioning profile obviously we need to update everything and that's when we see the issue described here.

**Comment by pernilla** [comment]
OK, after reinstalling a new computer from scratch to try it all out I think I understand how it works. With following in fastfile: 

```
 lane :certs do
    match(app_identifier: "myapp", type: "development", force_for_new_devices:true, readonly: true)
  end
```

It will not ask for password for apple portal using already know devices. But if you add a device @colinramsay is right; it will ask to the account, so what does force_for_new_devices:true really do?

Then we're back to square one. How do we add devices without giving out the password? Our developers are not even in the same country so we cannot ask someone to drop by with the phone to add provisioning profiles. Should we ask for UUID?

**Comment by hjanuschka** [comment]
@pernilla i can only talk for my team. we do not use manual codesigning on developers machine.
we only use manual codesigning (with match for sure) - on CI and release builds.


on local dev machines we toggle "Automatic Code Signing" in xcode.

on CI we do it with (using fastlane plugin here: https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning):

```
lane :release_app do

    update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: false) 
    gym(include_bitcode: false, clean: true)
    update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: true) 

end

```

**Comment by pernilla** [comment]
We have had problems with that setup invalidating the provisioning files. But maybe we did it wrong.

**Comment by mfurtak** [comment]
This issue has gotten a lot of people associated with it, some finding success and some not. To prevent more future noise for a large group, I'm going to close and lock this issue.

Please create a new issue to discuss any further problems! Thanks for your understanding 🙏
