### ISSUE TITLE
fastlane 1.88.0 crash when executed without parameters

### ISSUE THREAD

**Issue by sebasbad** [fastlane/fastlane#4626]
### Issue Description
Crash when running fastlane without parameters
##### Complete output when running fastlane, including the stack trace and command used
```
$ fastlane
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/lib/fastlane/cli_tools_distributor.rb:17:in `take_off': undefined method `downcase' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.88.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile: not relevant

### Environment

fastlane version (run `fastlane -v`): fastlane 1.88.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by asfalcone** [comment]
@sebasbad Thanks for the report! I've been able to reproduce and will work on a fix!

**Comment by asfalcone** [comment]
This will be in `fastlane 1.89.0`

**Comment by sebasbad** [comment]
Thank you ! 👍
