### ISSUE TITLE
admin: would be great if you could set some expectations around pull request timing

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#4628]
### Issue Description

what is the expectation for a response from the fastlane team to a pull request?

to take my own example, I sent a pretty simple and (I think) non-controversial pull request nearly two weeks ago.

other than somebody adding a label to show which project it hits (frameit), I haven't had any communication at all.

I don't know whether this is a perfectly normal timeline and I should just sit tight, or whether this is an abnormal delay.

I do know that it is discouraging in the least, and at the worst leads to stale pull requests. (I actually submitted a less good request to do a similar job - many months ago, but by the time anyone really looked at it, it was not able to merge).

It would be great if you had some kind of guidelines on what we should expect in the contributing doc

e.g.

```
1) we'll generally get someone to have a look and comment on the general idea in xxx 
2) we'll aim to have a first code review and feedback in yyy
etc...
```

**Comment by jcampbell05** [comment]
Would adding a dynamic badge that looked at the average response times help?
http://issuestats.com/github/fastlane/fastlane

**Comment by ConfusedVorlon** [comment]
that would certainly give some indication - but it only really shows that some pull requests take many months to close, rather than showing anything about expected time to get some engagement.

if the fastlane team were willing to post an expectation (we try to comment in x days), then that is more actionable.

at x*2 days, I can know that something is amiss and bump/prod/give up/ appropriately.

**Comment by vpolouchkine** [comment]
Hey @ConfusedVorlon,

Thanks for raising this up – it's super important to set the right expectations. The points you raise are completely valid; we haven’t been providing feedback on all pull requests right away as we're consciously focusing on improving fastlane (and its tools) stability. Our goal is to make sure that anyone can be successful with fastlane anytime they use it. Having said that, we recognize that fastlane would not be where it is today without all of the community contributions. While we currently cannot provide timeline expectations as it relates to pull requests, we will work to have something to that effect in the near future. Furthermore, to streamline the process, we kindly ask that folks check out and follow the Contributing guide, specifically, to first open a new Issue to discuss the proposed change, and once given the green light, to create a pull request. 

Really appreciate your excitement & energy to make fastlane a powerful tool for mobile developers everywhere!

**Comment by ConfusedVorlon** [comment]
It has been a month now since I submitted what is essentially a 4-line pull request.
The only feedback I have had is that essentially you're focussing elsewhere at the moment.

Pull requests don't stay fresh. The exact thing I submitted is a rehash of a pull request that I submitted long ago, and where it became un-mergable due to changes to master. My current pull request will no doubt become stale before too long.

The message I'm getting is that submitting a pull request is a waste of my time.

To be clear - I totally understand that you are focussing on your own efforts to make fastlane stable, and that is an entirely reasonable choice. I use fastlane all the time, and stability is something I value.

However - it would be polite to post a notice in the contribution guidelines to say that pull requests are only being looked under <insert details here> circumstances at the moment.

**Comment by vpolouchkine** [comment]
Thanks for the feedback, I understand where you're coming from.

As you said, we're focused on making `fastlane` stable, which means being rigorous on inbound PRs that extend functionality and add complexity. It looks like your change is straightforward, so I'm going to work with the team to see if we can get some visibility on this.

As you know, PRs can take a long time to review: time spent on feedback, testing, and future maintenance considerations must be balanced with bug fixes and feature work. We’ve recently updated the [Contributing Guide](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md#pull-requests-prs): we ask that everyone who wishes to contribute a new feature, opens an Issue to discuss the change first. If there's a green light based on the discussion, we then recommend creating the PR with the code changes. Let us know if you have feedback on ways we can make this process better.

I'll see what we can do about updating the Contributors Guide with a more clear and deterministic process. Community contributions are a large part of what make `fastlane` special, so I really appreciate your desire to make it a better tool and working with us as we grow and scale. Happy coding! :)

**Comment by ConfusedVorlon** [comment]
> Let us know if you have feedback on ways we can make this process better.

fwiw - here is my feedback. Decide how much you want community contribution, then commit to your process.

If the process is that all pull requests have to be greenlit through an issue before consideration, then go through and close all pull requests that don't meet this requirement (copy/paste an explanation and link to the contribution guide). That should be a quick job.

Update the contribution guide to say **'we do not accept pull requests unless they have been greenlit through an issue'.** Create a 'green light' tag which can be applied to issues. (If this was your process, then you might exempt documentation PRs from the requirement)

If pull requests are not closed, then you need to find a way of providing timely feedback. This can be 'no', 'not now' or whatever. It also needs to cover feedback related to the actual PR process. 

To take my recent example:  https://github.com/fastlane/fastlane/pull/4418 - it was failing a test. I _think_ that the test was failing from existing code (so the fail didn't indicate a problem with my PR) and asked a question about whether it was important. I never did get an answer to that. 

It would be fine to get a response that you didn't want my PR - The dispiriting thing is being left in limbo.

To be clear: It is entirely understandable for you to be very picky about accepting PRs. Feedback, testing, maintenance etc are all real issues that we understand.

However, this is intrinsically at odds with a broad approach that encourages contributions from the community.

There is a scale, which broadly runs from 'all welcome, feedback/help/nurturing provided rapidly and willingly' to 'tightly controlled process with limited acceptance/involvement'.

My suggestion is to decide where you want to be on that scale. Communicate it and commit to it.
