### ISSUE TITLE
Trying to `nuke` provisioning fails to remove in Apple Dev Portal

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/fastlane#4638]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `match nuke distribution` to clear out provisioning profiles but they still exist in Apple Dev portal

##### Complete output when running fastlane, including the stack trace and command used
When running `match nuke distribution` I see 
```
...
13:51:02]: --------------------------------------------
[13:51:02]: --- Deleting 11 provisioning profiles... ---
[13:51:02]: --------------------------------------------
[13:51:02]: Deleting profile 'match AppStore com.mycompany.myapp' (XXXXXXXXXX)...
[13:51:04]: 757: unexpected token at 'Bad Request'
[13:51:04]: Successfully deleted profile
...
```

### Environment

match version (run `match -v`):
`match 0.5.0`

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
`rvm`

**Comment by vpolouchkine** [comment]
Can you try deleting the profile manually using `spaceship`?

**Comment by kdawgwilk** [comment]
I ended up deleting them all myself in the Dev Portal and restarting fresh with `match` but I still believe its a bug the `match nuke` subcommand

**Comment by KrauseFx** [comment]
Thanks for submitting this issue, however there is not enough information to help us fix this problem. Feel free to re-open with more information, stack trace and ways to reproduce 👍
