### ISSUE TITLE
Does Fastlane support projects with multiple targets (for multiple apps of small variation)?

### ISSUE THREAD

**Issue by BigSauce** [fastlane/fastlane#4641]
I have an Xcode project, and I'm wondering how one might handle generating snapshots for a specific target within a project, where there are multiple targets within that project.  For example, if I have two targets (one for each app within the project)--**targetA** and **targetB**--how might I generate snapshots for both of those apps?

Should I have a lane for each app or perhaps a separate snap file for each app target?  Some advice would be greatly appreciated.  I'm new to Fastlane.

Fastlane is awesome, by the way.  I can't wait to use it!

**Comment by vpolouchkine** [comment]
Take a look at https://github.com/fastlane/fastlane/blob/master/fastlane/docs/FAQs.md#multiple-targets-of-the-same-underlying-app

**Comment by ConfusedVorlon** [comment]
I wrote the section of the docs with ```desc "Deploy both versions````

At that time, it worked very well, but unfortunately something changed, and fastlane no longer lets you call itself if you need any user input.

in my case, I like to see the html preview as part of deliver - so I have had to delete the ```deploy both versions```lane, and just do it manually.

env files are still great and get you a lot of the way there, but not quite as far as they used to!

**Comment by TKBurner** [comment]
@ConfusedVorlon Thanks for following up on this. Is there anything you think we should change in the docs there? I'd love to get your input. Thanks!

**Comment by ConfusedVorlon** [comment]
a note that fastlane calling fastlane will only work properly in non-interactive cases wouldn't go amiss.

**Comment by BigSauce** [comment]
Thanks for the prompt responses.  I consider my question answered and the issue resolved.

**Comment by KrauseFx** [comment]
For people coming from Google, check out the [Guide to use fastlane for apps with multiple targets](https://docs.fastlane.tools/faqs/#multiple-targets-of-the-same-underlying-app).
