### ISSUE TITLE
Specific order of profiles required in some cases when resigning binary with extension

### ISSUE THREAD

**Issue by Jugale** [fastlane/fastlane#4642]
This issue resides within [resign.sh](https://github.com/fastlane/fastlane/blob/master/sigh/lib/assets/resign.sh). 

Let's say I have a binary `Experiments.ipa` with the bundle identifier `com.company.experiments`. Within this app I have an extension called `AudioPlugin`, which has the bundle identifier `com.company.experiments.AudioPlugin`. I also have a profile `Experiments.mobileprovision` that has a wildcard bundle identifier, and a profile for the extension called `AudioPlugin.mobileprovision` with a bundle identifier that is the same as the extension.

In order to resign `Experiments.ipa`, I run the following:
```
sigh resign --signing_identity "iPhone Distribution: Company Pty Ltd" --provisioning_profile Experiments.mobileprovision --provisioning_profile com.company.experiments.AudioPlugin=AudioPlugin.mobileprovision
```
This doesn't work: the extension is signed with `Experiments.mobileprovision` because somewhere within `resign.sh` the wildcard identifier is matched to the extension.

However, changing the order of the two `--provisioning_profile` flags values works as expected.

I feel that this should either be fixed so that a profile that exactly matched a bundle identifier will be used even if there is a wildcard profile available. 

Or, this issue should be clearly documented so other developers are aware that the profile order determines precedence

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by asfalcone** [comment]
@Jugale For the "iPhone Distribution: Company Pty Ltd" profile, is that the filename?

**Comment by Jugale** [comment]
@asfalcone That's the name of the certificate I'm signing with, as it appears in the keychain

**Comment by asfalcone** [comment]
@Jugale the values passed to [`--provisioning_profile` must be file names](https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/commands_generator.rb#L65). I'm not actually sure of the behavior when passing a name as opposed to the file name but it could explain the strange behavior.

**Comment by Jugale** [comment]
@asfalcone I'm actually passing the path to each `.mobileprovision` to the `--provisioning_profile` - your previous question was asking about `--signing_identity`

**Comment by TKBurner** [comment]
Hi @Jugale! Have you tried setting:

--ignore_profiles_with_different_name true

 | Use in combination with :provisioning_name - when true only profiles matching this exact name will be downloaded

This should force exact matching. Let me know how it goes!

**Comment by Jugale** [comment]
@TKBurner that didn't help - from the documentation it sounds like that flag is not for the `resign` command as it works in conjunction with `provisioning_name`.

**Comment by TKBurner** [comment]
@Jugale Thanks for following up. It sounds like this is something we should improve in our documentation. I'm glad to hear you got up and running. I'm going to mark this so we update our docs 👍
