### ISSUE TITLE
[frameit] Cannot frame screenshot when title contains single quote

### ISSUE THREAD

**Issue by pylebecq** [fastlane/fastlane#4647]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello there,

When I'm running frameit to add frames on my screenshots, if a title contains a single quote, it will prevent the framing to happen.

##### Complete output when running fastlane, including the stack trace and command used

```
$ frameit
[17:38:11]: Unsupported screen size [744, 1392] for path './background.png'
[17:38:13]: `mogrify -font /space/products/app-iphone-v3/fastlane/screenshots/./fonts/Arial.ttf -gravity Center -pointsize 65 -draw text 0,0 'C'est génial' -fill #ffffff /var/folders/hz/rjytjdvx10l94rp8_hmrfd280000gp/T/mini_magick20160513-89389-1orri5f.png` failed with error:
mogrify: non-conforming drawing primitive definition `est' @ error/draw.c/DrawImage/3169.
```

### Configuration Files

Framefile.json:
```json
{
  "default": {
    "keyword": {
      "font": "./fonts/Arial.ttf"
    },
    "title": {
      "font": "./fonts/Arial.ttf",
      "color": "#ffffff"
    },
    "background": "./background.png",
    "padding": 50
  },
  "data": []
}
```

title.strings:
```
/* Title of the Profile screen */
"profile_screen" = "C'est génial";
```

screenshot filename:
```
iPhone6-01-profile_screen.png
```

### Environment

frameit version (run `frameit -v`): 2.6.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no, standalone frameit

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? yes, rvm

**Comment by TKBurner** [comment]
Hi @pylebecq! Great to hear from you. What happens if you escape the single quote?

"profile_screen" = "C\'est génial";

Thanks!

**Comment by pylebecq** [comment]
Hello,
Sorry for the late reply.
You're right, if I escape the single quote it works fine.
Could/Should it be done in frameit code ? We use a third party service to handle all our content localization, and we are able to download files from it directly. With this solution I need to tell the people handling translations to include the `\` in these specific translations, I'm pretty sure they will always forget to do this, or they will start putting `\` everywhere. Not very confident to rely on people to do this corectly. ^^

**Comment by TKBurner** [comment]
@pylebecq Thanks for following up. We are always working on improving string handling. I'll let the frameit team know.
