### ISSUE TITLE
Copy Artifacts uses artisanally built bash commands

### ISSUE THREAD

**Issue by jules2689** [fastlane/fastlane#4653]
This is not the best situation. Let's use Ruby's Fileutils.
Also, it has no tests 👎 👎 
This issue is to appease robot overlords.

**Comment by KrauseFx** [comment]
Hey @jules2689, the action was contributed by one of the fastlane users. You can find the implementation here: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/copy_artifacts.rb
Feel free to update the action to use `FileUtils` and add tests, I'm more than happy to review and merge the changes 👍

**Comment by jules2689** [comment]
Ah @KrauseFx , I forgot to tag this issue in the PR: https://github.com/fastlane/fastlane/pull/4654

**Comment by KrauseFx** [comment]
Hey, that's awesome, thanks! I should have seen the GitHub reference, sorry. We'll take a look 👍
