### ISSUE TITLE
Curl api for iTunes Connect app status?

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#4656]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Does `spaceship` provide any `curl` API for `iTunes Connect` app status? with/without authentication?

**Comment by KrauseFx** [comment]
Sorry I'm not sure I understand what you mean. What do you want to do?

**Comment by MickeyHub** [comment]
these days, we use cert or sigh,  both failed, the outputs indicate it's attributed to login to member center or iTunes Connect, so is spaceship now available?

**Comment by gran33** [comment]
I would like to have the app status in `iTunes Connect` (Ready for sale/Waiting for review/...) via curl, is it possible via `spaceship`?

**Comment by KrauseFx** [comment]
@gran33 You could do that, you can easily access the login cookie from `spaceship`, but it requires a lot of knowledge around http requests and cookie handling 👍
