### ISSUE TITLE
tvOS support in Produce and Deliver?

### ISSUE THREAD

**Issue by thekeshavgoel** [fastlane/fastlane#4657]
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

Does Produce support creation of tvOS apps on iTunes yet? (I just use it to register Identifier on Apple dev portal for now though, and create app on iTunes manually and create Provisioning profiles for it manually).

if yes, how to what parameter to pass in command line?

And does Deliver supports metadata transfer support for tvOS apps? If yes guide me through it please.

**Comment by KrauseFx** [comment]
Sorry, currently `produce` doesn't support tvOS. `deliver` already supports tvOS, the best way to get started is to run `deliver init` on a project that already has tvOS metadata.
