### ISSUE TITLE
Add action for reading sections from CHANGELOG.md

### ISSUE THREAD

**Issue by pprochazka72** [fastlane/fastlane#4658]
## Idea
🔑  This action is inspired by [Keep a CHANGELOG](http://keepachangelog.com/) project. [Keep a CHANGELOG](http://keepachangelog.com/) proposes a standardised format for keeping change log of your project repository in CHANGELOG.md file. This file contains a curated, chronologically ordered list of notable changes for each version of a project in human readable format.

Since [Keep a CHANGELOG](http://keepachangelog.com/) project proposes a well-defined structure with _sections_ (e.g.: `[Unreleased]`, `0.3.0]`) and _subsections_ (`Added`, `Changed`, `Deprecated`, `Removed`, `Fixed`, `Security`) it would be convenient to have Fastlane action, which can read the content of a _section_ from CHANGELOG.md. Pull request (#4659) implementing this functionality has been submitted.

## Example of using `read_changelog` during development:
1. your project includes CHANGELOG.md file, which follows the [proposed format](http://keepachangelog.com/)
2. developers add new user stories, bug fixes and other relevant changes under `[Unreleased]` section
3. your deployment lane uses `read_changelog` action to read the content of `[Unreleased]` (default) section
4. the output can then be used in conjunction with for example [`pilot`](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#pilot) (to upload change log to TestFlight) or [`set_github_release`](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#github-releases) (to append change log to Github release).

## Future development:
Ideally, there will be also `mark_changelog`/`set_changelog`/`stamp_unreleased_chagelog` (something along those lines) action which will "stamp" the `[Unreleased]` section with build/version number and date. Moreover, it would create an empty placeholder `[Unreleased]` section after for further development.

**Comment by TKBurner** [comment]
@pprochazka72 Thanks for reaching out about this. It seems like a reasonable new action to add. I noticed that you don't have any test coverage for your PR. Can you add tests? We'll be able to work with you after that. 

I'm going to close out this issue and we can follow up on the PR.

Thanks!
