### ISSUE TITLE
proposal: allow frameit to show whole frame

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#4660]
### New Issue Checklist

- [ y] Updated fastlane to the latest version
- [y ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

for some apps, the bottom edge of the screen is important - yet frameit frequently chops off the bottom of the screen. I'm proposing a developer option where you will always see the full screen as well as the whole of the device frame.

it doesn't use any more space, but simply shrinks the screenshot to fit in the allocated space such that the whole device is visible.

so you get this:

![ipadpro-01zoomscreen_framed](https://cloud.githubusercontent.com/assets/586910/14919793/5ae35e46-0e22-11e6-9332-ad90da628616.png)

instead of this:

![ipadpro-01zoomscreen_framed](https://cloud.githubusercontent.com/assets/586910/14919782/4c610d64-0e22-11e6-8107-8055325fc225.png)

It seems you prefer a new issue to discuss a pull request. The pull request is here:

https://github.com/fastlane/fastlane/pull/4418

**Comment by TKBurner** [comment]
@ConfusedVorlon Followed up with you on your PR. This is a reasonable feature and it's great you did the work. We can't prioritize it right now, but will make sure to review your PR. Can you add test coverage to it so we can merge faster?

Thanks!

**Comment by ConfusedVorlon** [comment]
I'm afraid I haven't the faintest idea how I would test this. My ruby is not up to that.

I guess you could test actual image outputs, but that would be pretty brittle; every frame change would break the test (and I don't know how to do even that!)

**Comment by TKBurner** [comment]
@ConfusedVorlon Thanks for following up. You can ask what functionality we'd like to see tested on the PR so when Felix takes a look he can point you in the right direction.

Thanks!
