### ISSUE TITLE
Add action to check if there are changes to a file or directory

### ISSUE THREAD

**Issue by 4brunu** [fastlane/fastlane#4661]
### Problem
The action `git_commit` throws an exception if the file or directory don't have any changes, but sometime it's hard to predict if there will be changes, or the changes may occur only sometimes.

### Solution
I need a way to check if there are any changes in a one or multiple directories or files, like a git status action.

### Future development
Use the git_status action to prevent git commit if there aren't any changes.
https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/git_commit.rb#L11

**Comment by TKBurner** [comment]
@4brunu Glad to see you working on a new action! We'll work with you on your PR, however we can't guarantee an ETA. Is this working well for your locally?

**Comment by 4brunu** [comment]
@TKBurner The action is working great.
Right now I use the `git_status` action to check if there are any file changes before making a commit, so I don't have an exception in the `git_commit` action.
Do you think this should verification should be inside the `git_commit` action so it doesn't crash?

**Comment by TKBurner** [comment]
Hi @4brunu Thanks for following up. I think it's better separate for now, but I can see how it would be useful to improve the error messaging in git_commit. Thanks!

**Comment by Kumuluzz** [comment]
Has there been any progress towards such an action or such I try to come up with something?

**Comment by 4brunu** [comment]
@Kumuluzz I've published a fastlane plugin that solves this issue.
https://github.com/4brunu/fastlane-plugin-git_status
If you have any issues, let me know.

**Comment by Kumuluzz** [comment]
@4brunu:
Thanks for the heads-up! 

I've tried to implement it in my flow, but it's not clear to me from the documentation what type `path` has to be. I'd love for the `path` parameter to have an optional value of `.` to make it cleaner to read in the `Fastfile` unless something custom is required

**Comment by Kumuluzz** [comment]
For now I've simply done the following in my `Fastfile` which works fine:

````
repo_clean = `git status --porcelain`.empty?
if !repo_clean  
  magic 🎉
end
```

**Comment by 4brunu** [comment]
@Kumuluzz In case you are interested I released version 0.1.1 with your suggestion 👍

**Comment by Kumuluzz** [comment]
@4brunu looks great! However I think I'll stick to my simply setup for now since I'll only need a simple boolean value, not the whole status history. My use case is quite simply:

> I have a lane called `dev` which automatically builds and distributes a new debug build. I also have a lane called `translations` that pulls the latest localizations used in the app. My problem is that I always forget to pull the newest localizations before making a new build, so I want to call `translations` in my `dev` lane.
> However, my `translations` calls `git_commit` before wrapping up and unfortunately `git_commit` throws an exception if there are no changes, which means my `dev` lane would only work if I update the translations.
> That's why I've now added the `repo_clean = `git status --porcelain`.empty?` and only call `git_commit` if this is false :)

**Comment by 4brunu** [comment]
@Kumuluzz Thanks for the feedback 👍
