### ISSUE TITLE
Feature request: activate languages

### ISSUE THREAD

**Issue by hryamzik** [fastlane/fastlane#4665]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/tunes/app_version.rb:529:in `container_data_for_language_and_device': [!] da isn't an activated language (RuntimeError)
```

Is it possible to activate languages if they are not turned on yet?

**Comment by KrauseFx** [comment]
`deliver` should actually automatically create the new language. One question: Do you have the `da` language only in your screenshots, but not for metadata?

**Comment by hryamzik** [comment]
I do, in fact the goal was to upload screenshots only.

**Comment by KrauseFx** [comment]
So if you add metadata to the folder everything works?

**Comment by hryamzik** [comment]
I can't check this yet as other team members are busy with metadata and I don't want to override there edits.

**Comment by TKBurner** [comment]
@hryamzik Thanks for following up. Let us know when you get a chance to test it out. 👍

**Comment by hryamzik** [comment]
I don't expect any issues with metadata filled in. But can't test this as my colleagues already initialised all the localisations with web UI. I would still mark this as a bug.

**Comment by TKBurner** [comment]
@hryamzik Closing this out. Feel free to update and I'll reopen if you continue to see any issues 👍
