### ISSUE TITLE
Feature request: Upload a folder to S3

### ISSUE THREAD

**Issue by teriiehina** [fastlane/fastlane#4671]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It would be great to have an action all the content of a folder so S3.

The current S3 action is great for a specific workflow. For others, maybe it's not optimal, e.g. uploading anything else than the pre-defined settings (https://github.com/fastlane/fastlane/issues/3696)

Also, S3 is great in most of the cases. For some specific cases, there may be some tweaks to do, e.g. having a subdomain with dots in it (https://github.com/aws/aws-sdk-ruby/issues/510)

So having a generic "upload folder to S3" could be useful to use S3 with nearly any workflow, e.g. uploading a deployment folder identified with the bundle version but also uploading the same deployment folder to a `/latest` URL. For OTA webpages, this simplify the upload of resources (css, images) that can change on a per-build basis (e.g. badging the icon)

btw, I'm preparing a PR for this issue :)

**Comment by TKBurner** [comment]
HI @teriiehina Thanks for reaching out. We have already addressed this FR in #4178

"Thanks for submitting this issue. You're right, currently the s3 action is limited to ipa files with their plist files, which will not change in the future. I'd recommend taking a look at the aws-sdk provided by Amazon and building your own script to fit your needs. 
You should be up and running in no time. I'd recommend building this as its own action using fastlane new_action, so it's better reusable and properly structured. Once that's done, you can submit to fastlane via a PR if you want to share it with the rest of the community 👍

Let me know if we can help you with this"

Can you make sure you follow this approach in your PR, as a new action?

Thanks! 👍

**Comment by teriiehina** [comment]
Hi @TKBurner,

Using the aws-sdk, creating a new action using `fastlane new_action` and trying to make the action as generic as possible is what I did in https://github.com/fastlane/fastlane/pull/4672.

Did I miss something out ? Should I refer to https://github.com/fastlane/fastlane/issues/4178 in the PR as well ?

Regards

**Comment by TKBurner** [comment]
Thanks for following up. Didn't realize #4672 was a PR. We'll work with you on this PR but can't guarantee how fast we'll be able to prioritize it. The most successful PRs have good test coverage and update our docs.

Thanks! 👍

**Comment by teriiehina** [comment]
no problem. Thank you.

**Comment by teriiehina** [comment]
Hi @TKBurner,

just updated the PR https://github.com/fastlane/fastlane/pull/4672 with some specs, based on what the already existing S3 action is doing.

IMHO, documentation should be fine as the action in itself is very simple.

Finally, sorry for the `push -f` as I pulled `fastlane/master` and rebase my branch on it to prevent any merge conflict.

Please let me know if I can do anything else to help this PR to be accepted. We are already using this action internally, we think it could be useful to other people too.

**Comment by TKBurner** [comment]
@teriiehina Really happy to have you working with us on the new plugin system. I'm going to close this issue out but we'll be working with you on your PR. Hope that you have a great week! 👍
