### ISSUE TITLE
Deliver has issues handling filenames with multiple seperators.

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#4674]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver has issues parsing certain filenames with multiple file separators.

One example of a file name it can't understand is this:
`1_watch_1.Slack for iOS Upload-1.png.jpeg`

It instead interprets this as:
`1_watch_1.Slack`

This means it can't find the file and throws an error due to not being able to figure out the MIME type.

Usually your screenshots would be named better than this however when deliver was set up it downloaded the existing iTunes screenshots with their original filenames which caused more issues.

As a workaround I simply removed the original filename from the file name however Fastlane didn't understand the "jpeg" file extension, upon renaming it to "jpg" it worked.

So to recap:
- Deliver should be able to handle complex file names like "1_watch_1.Slack for iOS Upload-1.png.jpeg"
- Deliver should be able to understand the "jpeg" file extension.
- Perhaps another issue could be opened to make deliver download existing screenshots with sensible names "1_watch_1.jpeg" rather than "1_watch_1.Slack for iOS Upload-1.png.jpeg"

##### Complete output when running fastlane, including the stack trace and command used

```
Unknown content-type for file ./fastlane/screenshots/en-au/1_watch_1.slack for ios upload-1.png.jpeg
```

### Configuration Files

Isn't a issue with the Fastfile

### Environment

fastlane version (run `fastlane -v`): 1..87.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? RVM

**Comment by TKBurner** [comment]
@jcampbell05 Thanks for reporting this with repro steps. It seems like it's pretty reliably reproducible right now so the team will be able to take a look. I'm going to send this out to the core team and we'll track our progress on this thread. Thanks! 👍

**Comment by mfurtak** [comment]
While the file name is rather complex, I don't yet see any indication that the spaces or extra dots are the source of the problem. I'm inclined to lay this at the feet of `spaceship` and https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/du/utilities.rb#L10-L19

Based on the error message, `spaceship` is aware of the full file path, it just doesn't have a look-up entry for `'jpeg'`.

Was there another error message that implied that something was losing the part of the file path after `1_watch_1.Slack`?

**Comment by jcampbell05** [comment]
@mfurtak  yes, originally the filename was being truncated up to the `.Slack` bit in the error message, upon tidying it up it still didn't work but it at least printed out the filename up to the `.jpeg` section.

**Comment by mfurtak** [comment]
@jcampbell05 Can you provide output for the 'pre-tidy' state for when the filename is being resolved badly?

**Comment by mfurtak** [comment]
In a quick local test, `deliver` didn't have any trouble handling screenshots with spaces and extra dots in them.

```
[10:36:54]: HTML file confirmed...
[10:36:56]: Uploading metadata to iTunes Connect
[10:36:58]: Successfully uploaded initial set of metadata to iTunes Connect
[10:36:59]: Starting with the upload of screenshots...
[10:36:59]: Uploading 4 screenshots for language en-US
[10:36:59]: Uploading './fastlane/screenshots/en-US/iPad2 01HelloWorld.Vertical.png'...
[10:37:01]: Uploading './fastlane/screenshots/en-US/iPad2 02HelloWorld.Horizontal.png'...
[10:37:02]: Uploading './fastlane/screenshots/en-US/iPhone4s 01HelloWorld.Vertical.png'...
[10:37:04]: Uploading './fastlane/screenshots/en-US/iPhone4s 02HelloWorld.Horizontal.png'...
[10:37:05]: Saving changes
[10:37:24]: Successfully uploaded screenshots to iTunes Connect
```

However, once I change their extension to be .jpeg, I get:

```
[10:39:16]: Uploading metadata to iTunes Connect
[10:39:17]: Successfully uploaded initial set of metadata to iTunes Connect
[10:39:18]: Starting with the upload of screenshots...
[10:39:18]: Uploading 4 screenshots for language en-US
[10:39:18]: Uploading './fastlane/screenshots/en-US/iPad2 01HelloWorld.Vertical.jpeg'...
/Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.27.1/lib/spaceship/du/utilities.rb:18:in `content_type': [!] Unknown content-type for file ./fastlane/screenshots/en-us/ipad2 01helloworld.vertical.jpeg (RuntimeError)
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.27.1/lib/spaceship/du/upload_file.rb:20:in `from_path'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spaceship-0.27.1/lib/spaceship/tunes/app_version.rb:363:in `upload_screenshot!'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/upload_screenshots.rb:42:in `block (2 levels) in upload'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/upload_screenshots.rb:29:in `each'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/upload_screenshots.rb:29:in `block in upload'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/upload_screenshots.rb:27:in `each'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/upload_screenshots.rb:27:in `upload'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/runner.rb:59:in `upload_metadata'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/runner.rb:21:in `run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.45.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/commands_generator.rb:132:in `run'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/mfurtak/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/deliver-1.12.0/bin/deliver:5:in `<top (required)>'
	from /Users/mfurtak/.rbenv/versions/2.2.3/bin/deliver:23:in `load'
	from /Users/mfurtak/.rbenv/versions/2.2.3/bin/deliver:23:in `<main>'
```

I'll make that `spaceship` adjustment and see where that leaves us!

**Comment by jcampbell05** [comment]
@mfurtak  I'll try to recreate the pre-tidy state.
