### ISSUE TITLE
Is there a simulation mode?

### ISSUE THREAD

**Issue by dmfrey** [fastlane/fastlane#4685]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Is there a simulation mode? It would be nice to be able see what supply is going to change before actually committing those changes to the Google Play Store.

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment
Ubuntu 15.10
Ruby 2.3.0
rbenv 1.0.0-21-g9fdce5d

fastlane version (run `fastlane -v`):
supply 0.7.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by asfalcone** [comment]
@dmfrey Thanks for the question. No there is not currently a way to see a preview of what would be uploaded.
