### ISSUE TITLE
Supply dynamic metadata

### ISSUE THREAD

**Issue by ravinggenius** [fastlane/fastlane#4688]
### New Issue Checklist

- [✓] Updated fastlane to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am fetching metadata from an in-house API, and I need to pass it along to Google and iTunes. I was able to work out how to do so with iTunes using `produce` and `deliver`, but I'm struggling with Google Play. `supply` wants a path to a directory filled with metadata files, which I do not have. I *could* construct the directory dynamically before calling `supply`, but it seems much more straightforward to just pass the data to `supply` when calling it.

Is it possible to pass dynamic data to Google Play? Will there be a way soon? If not I guess I'll have to use Google's API client directly.

### Configuration Files

Fastfile (see below):
```ruby
platform :android do
  desc 'Push metadata to Google Play Store'
  desc 'Metadata will be pulled from the CMS'
  lane :decorate do |options|
    # `CMS` is a network client that fetches app information from a remote server
    details = CMS.play_store_details(options[:app_id])

    # `ROOT` is a Pathname pointing to the project root directory
    metadata = ROOT.join("fastlane/metadata/android/#{details.package_identifier}.json")

    metadata.dirname.mkpath
    metadata.write({
      language: details.locale,
      title: details.name,
      short_description: details.summary,
      full_description: details.description,
      video: nil
    }.to_json)

    supply(
      package_name: details.package_identifier,
      json_key: ROOT.join('fastlane/assets/json_key.json').to_s,

      # doesn't work. `:metadata_path` expects a directory
      metadata_path: metadata.path,

      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
```

Fastfile I'd like to use:
```ruby
platform :android do
  desc 'Push metadata to Google Play Store'
  desc 'Metadata will be pulled from the CMS'
  lane :decorate do |options|
    # `CMS` is a network client that fetches app information from a remote server
    details = CMS.play_store_details(options[:app_id])

    supply(
      package_name: details.package_identifier,
      # `ROOT` is a Pathname pointing to the project root directory
      json_key: ROOT.join('fastlane/assets/json_key.json').to_s,

      metadata: {
        language: details.locale,
        title: details.name,
        short_description: details.summary,
        full_description: details.description,
        video: nil
      },

      skip_upload_apk: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
```

### Environment

fastlane version (run `fastlane -v`): 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by asfalcone** [comment]
Hi @ravinggenius, it isn't currently possible to provide the metadata directly to `supply` as you requested. At this time we don't have a plan to make that change, so for your use case, using the google api might be easier 👍

**Comment by ravinggenius** [comment]
I poked around in `Supply::Uploader`, and it looks like it would be pretty easy to add support for a `:metadata` option. Would you be open to a pull request?

**Comment by asfalcone** [comment]
@ravinggenius Thanks for the suggestion. At this time we're not open to extending the functionality of `supply` in this way. Feel free to create a fork and add your desired behavior there. If there is a lot of interest from the community we could consider merging that behavior in the future 👍

**Comment by ravinggenius** [comment]
Follow up: What about adding support for other data to `supply`? For instance synchronizing Content Ratings would be very useful for us.

**Comment by asfalcone** [comment]
@ravinggenius Please open a new PR to discuss 😄  I believe that content rating, if synchronized in the same manner as existing metadata, would be a valuable addition to `supply` 👍
