### ISSUE TITLE
appfile location if only using sigh

### ISSUE THREAD

**Issue by ChaseFlorell** [fastlane/fastlane#4689]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm only using `sigh` and nothing else within the fastlane toolkit. I can execute my command successfully from my remote machine, but am required to pass in `FASTLANE_PASSWORD` which I'm not fond of (for obvious reasons).

>   FASTLANE_PASSWORD='4U2P@$$' sigh -a "$APP_ID" -u "myemail@host.tld" -o ~/Desktop -q "$PROVISIONING_PROFILE" --force

What I'd rather do is have an `appfile` sitting on the Mac that knows what the password is (as this is my developer password and I don't want to share it with the team). Unfortunately I cannot find any documentation as to where that appfile should live.

I'm simply copying the deployable artifacts from my Windows machine to the Mac, and then kicking off a bash script to re-sign the application.

**Comment by asfalcone** [comment]
@ChaseFlorell Can you try putting `fastlane/Appfile` under your project's root directory and see if that works? Other things you can try are setting `FASTLANE_PASSWORD` as an environment variable or putting the password for that apple id into your keychain. Let me know how those work out for you! 👍

**Comment by ChaseFlorell** [comment]
@asfalcone I've already added it to the keychain, it's "name" is `deliver.myemail@host.tld`

I took a look at the **Access Control** and it was limited to `security`. By changing the access control to "All", it appears to be working now.
