### ISSUE TITLE
Error when running fastlane_update action

### ISSUE THREAD

**Issue by thoughtcroft** [fastlane/fastlane#469]
fastlane_update action generated an exception "undefined method `version' for nil:NilClass"

See gist: https://gist.github.com/thoughtcroft/d00f88b628401f78d5b7

**Comment by KrauseFx** [comment]
Thanks for reporting @thoughtcroft 

The issue is caused by 
```ruby
        all_updated_tools = updater.installer.installed_gems.select do |updated_tool|
          updated_tool.version > highest_versions[updated_tool.name].version
        end
```

Maybe @milch could take a quick look at this?

**Comment by milch** [comment]
Unless some tool changed its name with an update, I don't really see how this could cause a problem. `updated_tool` can't be nil, and the information from `highest_versions` is used to update in the first place.

**Comment by JaviSoto** [comment]
Hi @thoughtcroft! is this still an issue? :)

**Comment by asfalcone** [comment]
Going to close this issue since it hasn't been updated in some time.
