### ISSUE TITLE
Gymfile documentation is very confusing

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/fastlane#4691]
### Issue Description
The documentation about how to use a gymfile is deeply lacking. Creating a new gymfile via `gym init` created a file that seemingly only allows for the definition of a single plist file attached to a single scheme. As well, the link embedded in the default file points to the old documentation page.

1. The gymfile allows for a "scheme" parameter, but does this equate to the Xcode scheme that we would pass to the gym command directly (i.e. when not using a gymfile)? Or is this adding a gymfile "scheme" that should then be referenced in my fastfile when running gym?
2. How is the file organized to allow for alternate parameters for different build schemes? As a simple example, setting different export_options on my ad-hoc development build vs. my app store release build does not seem to be possible.
3. Can export_options be passed directly to the gym command in my fastfile without the use of a gymfile? It doesn't seem possible, even though gym itself clearly understands that parameter when passed via the gymfile. 
4. Why would I want a gymfile that just points to a plist file, rather than including that information in the gymfile itself? What is the benefit of each usage of gym?
  * Calling gym and passing parameters directly in the fastfile
  * Using gym to call its gymfile
  * Using gym to call a gymfile which simply loads a plist
5. The documentation says, "Since Xcode 7, gym is using new Xcode API which allows us to specify export options using plist file. By default gym creates this file for you". Where is this file? Is it temporary? Am I supposed to capture it somehow and modify for future purposes? `gym init` seemed not to create such a thing. Do I need a separate plist for each Xcode build scheme, or does one plist handle them all?

**Comment by vpolouchkine** [comment]
1. That parameter references the project's scheme that you set in Xcode.
2. You would need to use `fastlane` for that, eg. setup multiple lanes to pass different schemes to `gym`.
3. Yes, you can pass it using `--export_options [VALUE]`. You can run `gym help` to get the full list of parameters that you can pass.
4. Because not all parameters of `xcodebuild` are mapped 1:1 in `gym`. You would use a Gymfile if you have a "basic" setup, eg. one app/scheme. You would use `fastlane` if you want to fine tune the tool to support multiple targets, etc. 
5. Hm, looks like the plist is not created by default. I'll look into that. It depends if the options you set in the plist are different from one to scheme to the other. If yes, you would need multiple plists.

**Comment by ChristopherDrum** [comment]
Thank you for your prompt response.
1. Gotcha
2. Passing different schemes to gym doesn't help if the gymfile only supports a single scheme (as you allude to in #4)
3. It seems that the only export_options value is `(the) path to export options plist`. So, I guess this just means to forget the gymfile and only use plists.
4. Yep, got it.
5. Aha, that certainly explains the last part of my confusion! 😉

**Comment by KrauseFx** [comment]
Thank you so much for your feedback @ChristopherDrum, we should definitely improve the onboarding experience and documentation for the `Gymfile`

**Comment by ChristopherDrum** [comment]
It would be a big help, thanks.

**Comment by vpolouchkine** [comment]
The plist is created by default in a temporary directory unless using the legacy build API.

**Comment by ChristopherDrum** [comment]
I see. I believe many of us are using the legacy build API for the bug noted in the gym console logs.

**Comment by ejebleed** [comment]
The bug of missing ExportOptions.plist file is still present. No file is been created.

**Comment by KrauseFx** [comment]
@ejebleed Can you create a separate issue with the steps to reproduce? 👍

**Comment by ejebleed** [comment]
This is the gym command line I'm using.

`gym --clean --scheme ${XCODE_PROJECT_TARGET_NAME} --configuration Release --include_bitcode false --archive_path ${BUILDS_DIR}${PACKAGE_NAME}.xcarchive --output_directory $BUILDS_DIR --output_name "${PACKAGE_NAME}.ipa" --xcargs PROVISIONING_PROFILE=$APP_PROVISION_UUID`

As I read from @ChristopherDrum initial issue (5.) then that File should be created by running any(?) gym command. But it does not. Maybe I misunderstood something.

**Comment by ejebleed** [comment]
ok i've created this issue: https://github.com/fastlane/fastlane/issues/5907
I hope it helps.
