### ISSUE TITLE
Supply: "This app does not have any APKs in any tracks"

### ISSUE THREAD

**Issue by chrisoshea** [fastlane/fastlane#4693]
Are you able to update just the meta data to Google Play without an APK?

When I do supply run with just metadata and no apk, getting back:
"/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.6/lib/google/apis/core/http_command.rb:211:in `check_status': [!] noActiveApks: This app does not have any APKs in any tracks. (Google::Apis::ClientError)"

<img width="1449" alt="screen shot 2016-05-17 at 09 50 23" src="https://cloud.githubusercontent.com/assets/104786/15316419/d2d9ef64-1c14-11e6-96ea-857e4b3eba15.png">

### Environment

fastlane version (run `fastlane -v`):

No fastlane installed
supply v 0.7.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by asfalcone** [comment]
@chrisoshea try adding the [`skip_upload_apk`](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb#L92) param if you want to update metadata without an APK. Also make sure that you have an app that is active in Google Play before trying to make changes to it! 👍

**Comment by asfalcone** [comment]
Going to close this for now. 👍
