### ISSUE TITLE
match git_branch option not found

### ISSUE THREAD

**Issue by NikoTung** [fastlane/fastlane#4695]
I used Match to manager our certifications . And I need to use different git branch for each team .I find the following note in the readme file.

>match was designed to use a separate git branch per Apple account. If you work in multiple teams, make sure to set the git_branch parameter to a unique value per team. From there, match will automatically create and use the specified branch for you. More information on codesigning.guide
 

So I added a option `git_branch` in my Matchfile 
 
    git_url "git@privategit.com:client/certifications.git" 
    git_branch "v-client"

    type "development" # The default type, can be: appstore, adhoc or development

     force_for_new_devices true

But when I ran `match development` ,I got the following error:

      Could not find option 'git_branch' in the list of available options: 
      git_url, type, app_identifier, username,keychain_name, readonly, team_id, 
      team_name, verbose, force, shallow_clone, workspace,   force_for_new_devices, skip_docs

my environment : 

##### match version : 0.5.0

So how can I make the `git_branch` option to work.

**Comment by TKBurner** [comment]
@NikoTung Thanks for reaching out. The change that enables this has been merged into master but not yet shipped. Expect it to work later today if you update fastlane after we make our release. 👍

**Comment by KrauseFx** [comment]
The release is almost done, stay tuned https://github.com/fastlane/fastlane/pull/4701
