### ISSUE TITLE
How to share fastlane config files between users

### ISSUE THREAD

**Issue by lucasfeliciano** [fastlane/fastlane#4696]
So, I have fastlane configured in my local machine and I want to commit the config files to the repo but they have my username for applestore saved there.

Is this the normal behavior?

**Comment by TKBurner** [comment]
Hi @lucasfeliciano Great to hear from you! If you'd like to avoid this you can use ENV files and put them in your .gitignore. Otherwise you can always not include them in your project and just get prompted at runtime. 

Hope that you have a great day!

**Comment by KrauseFx** [comment]
So in the `Appfile` you can do the following:
```ruby
apple_id ENV["APPLE_ID"]
```
and then run `fastlane` using 
```
APPLE_ID=email@email.com fastlane beta
```

In general you can also pass your Apple ID username using
```
FASTLANE_USER="something@gmail.com" fastlane lane
```
and don't specify it in the `Appfile` 👍
