### ISSUE TITLE
[Action improvement] Add scheme support to update_info_plist

### ISSUE THREAD

**Issue by dtorres** [fastlane/fastlane#4698]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a project with multiple targets and to prevent having yet another string to manage in the .env files, it would be useful to use the powers of the xcodeproj gem to obtain the path based on the scheme to build.

### Example usage

Fastfile:
```ruby
update_info_plist(
		scheme: "MyAppDev",
		block: lambda {|plist| 
			plist["CFBundleVersion"] = (latest_testflight_build_number(app_identifier: plist["CFBundleIdentifier"], version: plist["CFBundleShortVersionString"]) + 1).to_s
		}
	)
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
nope

**Comment by TKBurner** [comment]
@dtorres Thanks for this and the PR. We'll wait until you have test coverage to review. Hope that you have a wonderful day! 👍

**Comment by dtorres** [comment]
@TKBurner FYI, I've added tests for this

**Comment by TKBurner** [comment]
@dtorres Thanks! We'll work with you on the PR once we are ready! Hope you have a wonderful weekend 👍 Closing this out in favor of the PR.
