### ISSUE TITLE
Synchronize extended metadata with supply

### ISSUE THREAD

**Issue by ravinggenius** [fastlane/fastlane#4699]
### New Issue Checklist

- [✓] Updated fastlane to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

*This is a follow up to #4688.*

I find myself needing to automate metadata synching with the Play Store. I'm using `supply`, but it only handles some basics. I propose extending it to support (among other things) Content Ratings[1]. Content Ratings are more complex data than simple strings, so instead of plain text files, we could use some kind of structured data format. I personally favor [TOML](https://github.com/toml-lang/toml), but would rather not bike shed on it too long.

Please discuss.

---

[1] I actually want to synch "all the things", but I am just getting started, and I don't know everything that the Play Store exposes.

**Comment by TKBurner** [comment]
@ravinggenius Great idea! Are you considering a PR for this? Would love to hear what other people think too 👍

**Comment by ravinggenius** [comment]
I wanted to do this as an extension to `supply`, but I really need programatic access, as the file structure just doesn't work for me. To that end I started working on a custom action (I'm calling it `super_slide`) to handle everything, including extended metadata. Hopefully it can be merged into `fastlane` when I'm done.

**Comment by ravinggenius** [comment]
As it happens `google-api-client` itself doesn't expose a way to update much more than what `supply` covers. If anybody knows of a work-around, please let me know. I'm closing this for now though.

**Comment by TKBurner** [comment]
@ravinggenius Thanks for doing this research. Feel free to update this thread if you find out a workaround from Google. 👍
