### ISSUE TITLE
Gradle Action - Properties with special characters not supported

### ISSUE THREAD

**Issue by JulienArzul** [fastlane/fastlane#4700]
### Issue Description
When using the properties attributes in the gradle actions, we can not have properties that contains special characters like spaces or quotes.
My use case is a property that is filled with a user-specified text : the release notes of the build. The user can enter any character including spaces, \n and quotes. Those should all be accepted.

##### Complete output when running fastlane, including the stack trace and command used
Fastlane line : 
`fastlane beta release_note:'Release note test'`

Last command executed : 
`gradlew app:crashlyticsUploadDistributionRelease -p . -PRELEASE_NOTE=Release note test`

> Output : 
> FAILURE: Build failed with an exception.
> * What went wrong:
> Task 'note' not found in root project ''.
> 

### Configuration Files
```
desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |options|
    gradle(
        task: 'clean'
      )
      gradle(
        task: 'assemble',
        build_type: 'Release'
      )
      gradle(
        task: 'app:crashlyticsUploadDistribution',
        build_type: 'Release',
        properties: {
          'RELEASE_NOTE' => options[:release_note]
        },
      )
  end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

### Proposed Fix
Usually, when using Gradle directly with properties, they are surrounded with double quotes to prevent those kind of errors.

Example : 
`gradlew "-PRELEASE_NOTE=Release note test" clean app:assembleRelease app:crashlyticsUploadDistributionRelease
`
Quick fix : 
Line 38 of https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/gradle.rb
`flags << params[:properties].map { |k, v| "-P#{k}=#{v}" }.join(' ') unless params[:properties].nil?`
should become
`flags << params[:properties].map { |k, v| "'-P#{k}=#{v}'" }.join(' ') unless params[:properties].nil?`

Ideally, we should also unescape single quotes in k and v to prevent any errors.

**Comment by asfalcone** [comment]
@JulienArzul Thanks for reporting this! We'd be happy to accept a PR that had proper shell escaping using [`shellwords`](http://ruby-doc.org/stdlib-2.0.0/libdoc/shellwords/rdoc/Shellwords.html). Search the fastlane codebase for `.shellescape` for an example if you need one 👍

**Comment by bgannin** [comment]
If this still needs to be done I'm happy to do so in the next day or two and submit a PR.

**Comment by JulienArzul** [comment]
I haven't taken the time to work on it yet, you're welcome to do so.

**Comment by TKBurner** [comment]
@bgannin Sounds like you have the go ahead! Look forward to seeing your work 👍

**Comment by asfalcone** [comment]
The fix for this has been merged and will be released in the next `fastlane` version 🚀
