### ISSUE TITLE
Gradle Action - Proposed Improvements

### ISSUE THREAD

**Issue by JulienArzul** [fastlane/fastlane#4702]
### Issue Description

I just started using fastlane for Android and I have a couple of suggestions regarding the use of the Gradle action.
##### Module attribute

Most of recent Android projects are composed of a root Gradle project and several modules. The gradle tasks are then executed per module. It would be a plus to add a module attribute to the task we're executing, something like : 

```
gradle(
  task: 'assemble',
  module: 'app',
  build_type: 'Release'
)
```

Right now, this is supported by doing the following : 

```
gradle(
  task: 'app:assemble',
  build_type: 'Release'
)
```
##### Execute multiple tasks at once

Gradle is meant to execute an set of tasks linearly like so : 
gradlew clean assembleRelease testReleaseUnitTest

This example executes the three tasks 'clean', 'assembleRelease' and 'testReleaseUnitTest' one after the other. It would be nice to be able to do the same with Fastlane.

Currently, we have to declare three tasks : 

```
gradle(
  task: 'clean'
)
gradle(
  task: 'assemble',
  build_type: 'Release'
)
gradle(
  task: 'testReleaseUnitTest'
)
```

Those three tasks are then executed by three separate gradle commands, which adds an overhead each time as Gradle needs to re-parse the whole build file to configure it before actually building + the process creation if we're not using a daemon.

It would be cool to be able to define a set of tasks to execute instead of one task. 
Something like : 

```
gradle(
  tasks: [
    {
      task: 'clean'
    },
    {
      task: 'assemble',
      build_type: 'Release'
    },
    {
      task: 'testReleaseUnitTest'
    }
  ]
)
```

I still can do that currently but it's kind of a hack and doesn't work with flavors and build types : 

```
gradle(
  task: 'clean assembleRelease testReleaseUnitTest'
)
```

I don't know if those were in your roadmap but it'd be great to have them in the future to support Android builds further.

Thanks

**Comment by vpolouchkine** [comment]
Thanks for the feedback, we'll take a look.

**Comment by nmayafit** [comment]
+1 for that!

**Comment by dkpalmer** [comment]
+1. Clean is pretty common. Also have some that combine tasks like Jacoco reporting.

**Comment by tomachi** [comment]
Still have this issue.

**Comment by TKBurner** [comment]
@tomachi Thanks for up voting. We'll leave this feature request open. Hope you have a great day!
