### ISSUE TITLE
Latest android screengrab showing gray square for embedded mediaPlayer video

### ISSUE THREAD

**Issue by LovesBruins** [fastlane/fastlane#4706]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I run screengrab on my Android emulator,  the embedded video using android media player object shows only a grey rectangle.
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):
1.87.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by vpolouchkine** [comment]
Are you saying previous versions of `screengrab` did not exhibit this behavior?

**Comment by LovesBruins** [comment]
I was only saying I'm using the latest version.  This is my first foray into this cool product, so I have nothing to compare it to.

**Comment by LovesBruins** [comment]
Coincidently, the android native application 'screencap' works correctly.  Here is the source code:
https://github.com/android/platform_frameworks_base/blob/master/cmds/screencap/screencap.cpp

**Comment by vpolouchkine** [comment]
I don't believe this was ever supported, eg. it's a feature request.

**Comment by LovesBruins** [comment]
Okay.  So can you add this feature :)

**Comment by TKBurner** [comment]
Hi @LovesBruins Thanks for following up. We'll track this as a feature request. Hope you have a great day! 👍

**Comment by HugoGresse** [comment]
I also have the same issue using ExoPlayer. And as my app use a lot of video, the screenshots is not very useful :/

**Comment by TKBurner** [comment]
@HugoGresse Thanks for letting us know. I'm going to mark this as help wanted to get it a little more attention. Thanks!

**Comment by mfurtak** [comment]
Hi folks, I'm taking another pass at screenshot capture with #5621, so I'd be interested to know whether the code therein does double-duty of allowing video player screens to be captured.

If you have a minute to give that a try before I release it, that would be a huge help. Thanks! 🙌

**Comment by mfurtak** [comment]
Hi all, the changes from #5621 are now on master. If you have time to give it a try, that would be amazing.

The [README](https://github.com/fastlane/fastlane/tree/master/screengrab#improved-screenshot-capture-with-ui-automator) has more info about how enable the UiAutomator strategy, but note that v0.5.0 hasn't been released yet.
