### ISSUE TITLE
Invoking Fastlane::Actions::GradleAction not working

### ISSUE THREAD

**Issue by nomisRev** [fastlane/fastlane#4707]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I was trying out Fastlane and I wanted to write a action for generating Jacoco reports with my specific gradle script that runs Jacoco reports since doing the actual Jacoco report generation in ruby was a little out of my league atm. Everything seems to be setup okay except I have some problems invoking the GradleAction from my action script.

##### Complete output when running fastlane, including the stack trace and command used

This is the JacocoGradleAction run script:

```ruby
 def self.run(params)
        flavor = params[:flavor]
        build_type = params[:build_type]

        gradle_task = ["test", flavor, build_type, "UnitTestCoverage"].join

        Fastlane::Actions::GradleAction.run(task: gradle_task)

        Actions.lane_context[SharedValues::JACOCO_BUILD_TYPE] = build_type if build_type
        Actions.lane_context[SharedValues::JACOCO_FLAVOR] = flavor if flavor
      end
```

And the action script is invoked by

```ruby
desc "Generate reports"
  lane :reports do
    #gradle(task: "testReleaseUnitTestCoverage")
    jacoco_gradle(build_type: "Release")
  end
```
```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/gradle.rb:29:in `join': [!] no implicit conversion of nil into String (TypeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/gradle.rb:29:in `run'
	from /Users/simonvergauwen/appfoundry/Android-Fastlane/fastlane/actions/jacoco_gradle.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:109:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:60:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

```

**Comment by nomisRev** [comment]
I've located the problem a little more.

When calling `Fastlane::Actions::GradleAction.run(task: gradle_task)` the default values don't seem to be working so `project_dir` is not '.' but nil and thus `File.join(File.join(project_dir, gradle_path_param))` fails.

If I add `project_dir = params[:project_dir] || '.' ` to `gradle.rb` this problem is solved. I will fix this and create a pull request. :)

**Comment by vpolouchkine** [comment]
Thanks for tracking this down!

**Comment by nomisRev** [comment]
@vpolouchkine pull request can be found here
https://github.com/fastlane/fastlane/pull/4710

**Comment by TKBurner** [comment]
@nomisRev Thanks for sharing that. We'll review and update the PR. Hope you have a great weekend coming up 👍

**Comment by asfalcone** [comment]
@nomisRev I merged the PR but then we realized that '.' is [already the default value](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/gradle.rb#L113-L116) for `project_dir` so I reverted it because that code shouldn't be neccessary. 

I believe when `GradleAction.run` is called directly this way the default value code isn't applied.

I have 2 suggestions:
1) Call the `gradle` action with the new syntax: `other_action.gradle(task: gradle_task)`
2) Why not pull the `JacocoGradleAction` code into the lane directly? Is there a reason to keep this separate?

Thanks 👍

**Comment by nomisRev** [comment]
> '.' is already the default value for project_dir so I reverted it because that code shouldn't be neccessary.

While that is true, the change was necessary in order for it to work. (Not tested with OtherAction)

1) Logs didn't suggest OtherAction like I've seen it do. I will test when I have the cahnce and report back.

2) Because JacocoGradleAction in my eyes is an action and not a lane. Creating a private_lane with 1 action inside it to simulate an action seems incorrect to me. Correct me if I'm wrong.

**Comment by KrauseFx** [comment]
@nomisRev 

> While that is true, the change was necessary in order for it to work. (Not tested with OtherAction)

Please do use `other_action`, since that will take care of input validation and setting default values: https://github.com/fastlane/fastlane/tree/master/fastlane/docs#extensions 👍

**Comment by asfalcone** [comment]
Going to close this for now since `other_action` is the right solution here 💯
