### ISSUE TITLE
GYM ** ARCHIVE FAILED ** - Exit status: 65 [!] Error building the application

### ISSUE THREAD

**Issue by nAviram** [fastlane/fastlane#4712]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We've recently moved to Xcode 7.3, and now the gym build fails. (it worked on Xcode 6.4)
when building & running in Xcode 7.3 - it works.

### Checks I've done:
* Targets > Select Your Target > Build Settings > Apple LLVM 7.0 - Warning Policies > Treat Warnings as Errors > Release > Chang to NO (as suggested [here](https://github.com/fastlane-old/gym/issues/133) )

* verifying right permissions as suggested [here](http://stackoverflow.com/questions/22329005/mac-terminal-pointer-being-freed-was-not-allocated-error-when-opening-termin)

#####  command used
gym --clean --use_legacy_build_api --verbose --scheme schemeName --output_directory /path/to/outputFolder/IPA --output_name app_v3.2.0.ipa

##### output when running gym, including the stack trace
...
(1 failure)
ERROR [2016-05-18 11:29:59.50]: Exit status: 65
`/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/interface.rb:139:in 'user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/ui.rb:14:in 'method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/error_handler.rb:53:in 'handle_build_error'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:101:in 'block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/command_executor.rb:88:in 'call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/command_executor.rb:88:in 'execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:97:in 'build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/runner.rb:12:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/manager.rb:10:in 'work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:42:in 'block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in 'call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in 'call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in 'run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in 'run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in 'run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:61:in 'run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/gym/commands_generator.rb:15:in 'start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/bin/gym:6:in '<top (required)>'
	from /usr/local/bin/gym:23:in 'load'
	from /usr/local/bin/gym:23:in '<main>'`

### Gym Log File (last lines)
GenerateDSYMFile /Users/aviramn/Library/Developer/Xcode/DerivedData/ABCD-gwhqzwouggxlraaxikypfxzcfdbu/Build/Intermediates/ArchiveIntermediates/SpotSchemeAdHoc/BuildProductsPath/Ad\ Hoc\ dist-iphoneos/ABCDProduct.app.dSYM /Users/aviramn/Library/Developer/Xcode/DerivedData/ABCD-gwhqzwouggxlraaxikypfxzcfdbu/Build/Intermediates/ArchiveIntermediates/SpotSchemeAdHoc/InstallationBuildProductsLocation/Applications/ABCDProduct.app/ABCDProduct
    cd /Users/aviramn/Documents/MainProject/SpotApp
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/aviramn/Library/Developer/Xcode/DerivedData/ABCD-gwhqzwouggxlraaxikypfxzcfdbu/Build/Intermediates/ArchiveIntermediates/SpotSchemeAdHoc/InstallationBuildProductsLocation/Applications/SpotoptionProduct.app/SpotoptionProduct -o /Users/aviramn/Library/Developer/Xcode/DerivedData/ABCD-gwhqzwouggxlraaxikypfxzcfdbu/Build/Intermediates/ArchiveIntermediates/SpotSchemeAdHoc/BuildProductsPath/Ad\ Hoc\ dist-iphoneos/SpotoptionProduct.app.dSYM
dsymutil(25286,0x7fff73d9b000) malloc: *** error for object 0x600000182220: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil failed with exit code 6

### Environment

fastlane version (run `fastlane -v`): 1.89.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no.

**Comment by nAviram** [comment]
I've found a solution [here](https://software.intel.com/en-us/forums/embree-photo-realistic-ray-tracing-kernels/topic/584117)  , suggesting it's the environment variable "MallocNanoZone".
after I changed it to 0:

> export MallocNanoZone=0 

 Build was successfully completed.

**Comment by vpolouchkine** [comment]
Glad to hear you're up and running!

**Comment by sashakid** [comment]
Sorry, in what place should I add the line `export MallocNanoZone=0`?

**Comment by ToroLiu** [comment]
I encounter this error too. `Exit status: 65.`
When I run `archive` in Xcode, it works success. But it report something like the following..
```
Command /Applications/Xcode.app/Contents/Developer/usr/bin/copypng emitted errors 
but did not return a nonzero exit code to indicate failure
```
It has errors, but finally, it product a archive in the `Xcode -> Window -> Organizer`.
In my cases, the error is ```pngcrush caught libpng error:```. Failed to copy png file resource.

**Comment by KrauseFx** [comment]
@ToroLiu Please submit a separate issue for this, since it doesn't seem to be related to this one

**Comment by MarcPilgaard** [comment]
@ToroLiu Thank you, this did the trick for me. My archives consistently failed, but build was succesefully archived in the organizer. Apparently a third-party plugin we are using had some libpng crush error, which was not apparent in the console.
