### ISSUE TITLE
xcarchive file size is zero byte

### ISSUE THREAD

**Issue by FlyingNoob** [fastlane/fastlane#4713]
### New Issue Checklist
Updated fastlane to the latest version
I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

When fastlane build success. I get the ipa success. But the xcarchive file size is zero byte. There is not any error information .

Fastfile:
lane :beta_release do

      outputName = outputName()
      ipaPath = ipaPath()
      gym(
        workspace: XCODE_WORKSPACE,
        configuration: "Release",
        scheme: XCODE_SCHEME,
        build_path: XCODE_BUILD_PATH,
        silent: true,
        clean: true,
        export_method:"ad-hoc",
        output_directory: XCODE_BUILD_PATH, # Destination directory. Defaults to current directory.
        output_name: outputName,)
   
  end

### Environment

fastlane version 1.89.0:

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by vpolouchkine** [comment]
Can you please share the full log? Also, are you able to build the ipa using xcodebuild?

**Comment by FlyingNoob** [comment]
@vpolouchkine maybe it's a misunderstanding 。now is already fine

**Comment by FlyingNoob** [comment]
@vpolouchkine Thanks your attention by this issue
