### ISSUE TITLE
'scan' runs tests for different targets

### ISSUE THREAD

**Issue by wolffan** [fastlane/fastlane#4714]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When using scan to launch tests, tests for different test targets are launched on a random way:
Given tests in multiple targets and schemes (in order to separate UI and unit tests for example) scan will sometimes run just the tests for a scheme and sometimes all the tests of the project. Seems random.
There's no way to specify the target of scan (probably a feature request).
But that doesn't mean scan should be consistent on it's different launches :/

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
    scan(
      destination: "OS=9.2,name=iPhone 4s",
      workspace:"name.xcworkspace",
      scheme:"name.OS",
      clean: true,
      output_types:"junit",
      configuration: "Debug")
```

### Environment

fastlane version (run `fastlane -v`): 1.81.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? don't know

**Comment by vpolouchkine** [comment]
Can you provide a sample project which repro's this issue?
