### ISSUE TITLE
Actions go down the rabbit hole journey towards root (/)

### ISSUE THREAD

**Issue by dtorres** [fastlane/fastlane#4715]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When an action is run, the current directory is changed to the previous one, and although this gets the desired effect for actions called directly by the Fastfile, this leads to a bad environment when invoked in a nested fashion.

I created an action whose sole purpose is to print the current directory and call a block 

```ruby
module Fastlane
  module Actions
	  
    class PrintPwdAction < Action
      def self.run(params)
	      UI.important(Dir.pwd)
		  params[:block].call()
      end

      def self.description
        "A short description with <= 80 characters of what this action does"
      end
      
      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :block,
                                       is_string: false,
                                       description: 'A block to process plist with custom logic',
                                       optional: true)
        ]
      end

      def self.output
        [
          ['PRINT_PWD_CUSTOM_VALUE', 'A description of what this value contains']
        ]
      end

      def self.return_value
      end

      def self.authors
        ["Your GitHub/Twitter Name"]
      end

      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end
```

Here is the output of 3 nested calls
```
INFO [2016-05-18 16:21:03.42]: -----------------------
INFO [2016-05-18 16:21:03.42]: --- Step: print_pwd ---
INFO [2016-05-18 16:21:03.42]: -----------------------
WARN [2016-05-18 16:21:03.42]: /Users/dtorres/Projects/MyProject
INFO [2016-05-18 16:21:03.42]: -----------------------
INFO [2016-05-18 16:21:03.42]: --- Step: print_pwd ---
INFO [2016-05-18 16:21:03.42]: -----------------------
WARN [2016-05-18 16:21:03.42]: /Users/dtorres/Projects
INFO [2016-05-18 16:21:03.43]: -----------------------
INFO [2016-05-18 16:21:03.43]: --- Step: print_pwd ---
INFO [2016-05-18 16:21:03.43]: -----------------------
WARN [2016-05-18 16:21:03.43]: /Users/dtorres
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

I'm looking into this.

**Comment by dtorres** [comment]
The problem is in #[Line 155 in Runner.rb](https://github.com/fastlane/fastlane/blob/c73403e217f21dd77e72a32a1f345ccd02b579d5/fastlane/lib/fastlane/runner.rb#L155)

**Comment by TKBurner** [comment]
@dtorres Thanks for sharing this change. We'll work with you here and on your PR as relevant. Hope that you have a great day! 👍
