### ISSUE TITLE
Required gems in development

### ISSUE THREAD

**Issue by patoroco** [fastlane/fastlane#4725]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to execute `bundle exec rake test_all`, but it returns some errors due to dependencies.

I'm thinking in to add these lines to root `Gemfile`:

```ruby
...
gem "danger", "~> 0.6"
gem 'diff_matcher', :group => [:development, :test]
gem 'webmock', :group => [:development, :test]
```

What do you think? It's OK? Do you miss anything?

### Environment

- fastlane version (run `fastlane -v`):  
master

- Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?  
true

- Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?  
rvm

**Comment by KrauseFx** [comment]
Do you want to run all tests of all fastlane tools? If so, make sure to run `bundle install` in the root of the `fastlane` project

**Comment by patoroco** [comment]
Thanks for your reply @KrauseFx, yesterday was too much late...

I just found references to these gems for example in https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/cert/cert.gemspec#L35, so I go to close this issue, thanks and sorry! 🎱
