### ISSUE TITLE
How to use Supply on iOS?

### ISSUE THREAD

**Issue by AndreyNikiforov** [fastlane/fastlane#4727]
Trying to run Supply on ios platform and getting 

`Action 'supply' doesn't support required operating system 'ios'`

fastlane 1.89.0

I am using fastlane for react native (RN) project that produces both android and ios builds in one lane. What is the best approach for RN projects with fastlane? I can see modifying supply as simplest option...

**Comment by hjanuschka** [comment]
i think you should read the docs about `pilot` and `deliver`
wich are the way on how to deliver apps on ios platform.

best way i think would be to make a lane, wich has an if and either runs `supply` for android, and `deliver` for ios.

**Comment by TKBurner** [comment]
@hjanuschka Thanks for stepping in here too. @AndreyNikiforov pilot and deliver will be really helpful for your use case. Hope you have a great day!

**Comment by AndreyNikiforov** [comment]
@hjanuschka thanks for suggestion. During the build phase I do the following today:

1. get keys (match + similar custom code for android)
2. build binaries (android + ios)
3. upload (hockey, crashlytics, iTunes, Google Play, CodePush) -- varies based on branch; implemented using lanes today 

In my opinion, it is important to upload binaries only after both android and ios binaries compiled successfully. As an option, I can run fastlane 6 times from my circleci.yml. I was hoping to incorporate all build steps inside fastlane though.

**Comment by hjanuschka** [comment]
ok so you wann build ios and android at the same time.

pseudo code:

```
lane :publish do
	build
	android_publish
	ios_publish
end

lane :build do
		before_build
		build_android
		build_ios
end

lane :before_build do
		match...
		#custom android key fetching code
end

lane :build_android do
	gradle.....
end

lane :build_ios
	gym
end

lane :android_publish do
	supply...
end

lane :ios_publish do
	deliver
end


```

**Comment by AndreyNikiforov** [comment]
@hjanuschka, thanks for pseudo code. Can you please explain or better update code to show how platforms can be switched? If I run `fastlane publish` from my circleci.yml, ios_publish should be executed in ios platform, but android_publish in android platform.

**Comment by TKBurner** [comment]
@AndreyNikiforov Thanks for following up. How is the script getting run without you knowing it's input? You can use ruby syntax to handle with if statements etc.

Thanks!

**Comment by AndreyNikiforov** [comment]
@TKBurner from circle.yml file I am executing different lanes based on branch: `fastlane alpha`, `fastlane beta`, and `fastlane appstore`.

Looks to me that fastlane was designed to support multiple builds from one code base (each build for specific platform), while I need one build from one code base with multiple platform-specific outputs. However, I found that I can override platform just before running platform-sensitive action with `Actions.lane_context[Actions::SharedValues::PLATFORM_NAME] = :android`. 

That trick worked for Supply, but did not for Crashlytics as it seems that Crashlytics is using presence of the ipa file as platform selector instead of parameters (e.g. apk_path) or platform lane context. I have to create my own version of crashlytics to solve that, but the rest worked fine.

Thanks everybody for help!

**Comment by hjanuschka** [comment]
`Actions.lane_context[Actions::SharedValues::PLATFORM_NAME] = :android` this does'nt look good to me - should be avoided i guess.


can you post your circle.ci config - and you current fastlane file - so we can get a bit more detail on the whole picture?

**Comment by AndreyNikiforov** [comment]
circleci.yml (portion):

```Ruby
deployment:
  release:
    branch: /release\/.*/
    commands:
      - fastlane appstore
  beta:
    branch: /rc\/.*/
    commands:
      - fastlane beta
  alpha:
    branch: /.*/
    commands:
      - fastlane alpha
```

fastfile (portion):
```Ruby
lane :alpha do
  before_build_alpha
  build
  deploy_alpha
end

lane :beta do
  before_build_beta
  build
  deploy_beta
end

lane :appstore do
  before_build_appstore
  build
  deploy_appstore
end

private_lane :build_ios do
  Actions.lane_context[Actions::SharedValues::PLATFORM_NAME] = :ios
  gym
end

private_lane :build_android do
  Actions.lane_context[Actions::SharedValues::PLATFORM_NAME] = :android
  gradle
end

private_lane :deploy_ios do |options|
  Actions.lane_context[Actions::SharedValues::PLATFORM_NAME] = :ios
  hockey
  crashlytics
  if options[:deploy_pilot]
    pilot
  end
  if options[:deploy_deliver]
    deliver
  end
end

private_lane :deploy_android do |options|
  Actions.lane_context[Actions::SharedValues::PLATFORM_NAME] = :android
  hockey
  crashlytics_custom
  supply
end

#other private lanes
```
