### ISSUE TITLE
deliver download_metadata keeps asking whether I want to overwrite existing metadata

### ISSUE THREAD

**Issue by vmalyi** [fastlane/fastlane#4728]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
First I run "deliver init" which downloaded metadata into newly created /metadata and /screenshots folders. Then I deleted those folders and run "deliver download_metadata" and was asked whether I want to overwrite existing metadata though I already deleted it.

Please notice that both /metadata and /screenshots folders were recreated when running "deliver download_metadata" which caused this issue.

##### Complete output when running fastlane, including the stack trace and command used

```
wue-18172mac:fastlane$ deliver download_metadata
[09:58:48]: Login to iTunes Connect (viktor.malyi@xxxxxx.com)
[09:58:51]: Login successful

+--------------------+-------------------------+
|            deliver 1.11.3 Summary            |
+--------------------+-------------------------+
| app_identifier     | xxx.xxx.xxx          |
| username           | viktor.malyi@xxx.com |
| screenshots_path   | ./screenshots           |
| metadata_path      | ./metadata              |
| skip_binary_upload | false                   |
| skip_screenshots   | false                   |
| skip_metadata      | false                   |
| force              | false                   |
| submit_for_review  | false                   |
| automatic_release  | false                   |
+--------------------+-------------------------+

Do you want to overwrite existing metadata on path '/Users/malyi/projects/xxx/apps/xxxxxx/fastlane/metadata'? (y/n)
n
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.88.0 

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by vmalyi** [comment]
Found a workaround for the issue: set "DELIVER_FORCE_OVERWRITE" to "1" prior executing deliver "download_metadata" command

**Comment by TKBurner** [comment]
@vmalyi Glad to hear you found that solution. Hope that you have a wonderful day! 👍
