### ISSUE TITLE
sigh buffer error

### ISSUE THREAD

**Issue by charleyzhu** [fastlane/fastlane#4729]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'a0716b9645a0100c46a5411269f7399d'
The crash report has been stored locally '/tmp/sentry_a0716b9645a0100c46a5411269f7399d.json'

##### Complete output when running fastlane, including the stack trace and command used

➜  GainOnPocketAppStore git:(master) ✗ sigh --adhoc

+-------------------------------------+------------------------+
|                    Summary for sigh 1.8.0                    |
+-------------------------------------+------------------------+
| adhoc                               | true                   |
| skip_install                        | false                  |
| development                         | false                  |
| force                               | false                  |
| app_identifier                      | com.dotop.xxxxxxx |
| username                            | xxxxxx@aliyun.com  |
| team_id                             | [[DEV_PORTAL_TEAM_ID]] |
| ignore_profiles_with_different_name | false                  |
| skip_fetch_profiles                 | false                  |
| skip_certificate_verification       | false                  |
+-------------------------------------+------------------------+
INSERT OUTPUT HERE
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'a0716b9645a0100c46a5411269f7399d'
The crash report has been stored locally '/tmp/sentry_a0716b9645a0100c46a5411269f7399d.json'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish': [!] buffer error (Zlib::BufError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:357:in `finish'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `ensure in inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:262:in `inflater'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:274:in `read_body_0'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:201:in `read_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1132:in `block in get'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1419:in `block (2 levels) in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:162:in `reading_body'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1418:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1131:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:313:in `itc_service_key'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:274:in `block in send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:404:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:322:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:403:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:379:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:273:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/portal_client.rb:35:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:346:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:225:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.26.2/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/runner.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.4/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:99:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:117:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
not use
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
not use

**Comment by TKBurner** [comment]
Hi @charleyzhu Thanks for reporting this. Can you run fastlane run update_fastlane? We've corrected this issue and shipped the fix. Let me know how it goes! 👍

**Comment by charleyzhu** [comment]
run command fastlane run update_fastlane crash

i'm not dislable the Rootlees 

use “sudo gem update -n /usr/local/bin fastlane” command install

run command "fastlane run update_fastlane" 
# crash report
## Operation not permitted - /usr/bin/deliver
➜  GainOnPocketAppStore git:(master) ✗ sudo fastlane run update_fastlane
Password:
[09:12:27]: -----------------------------
[09:12:27]: --- Step: update_fastlane ---
[09:12:27]: -----------------------------
[09:12:27]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
[09:12:46]: Updating deliver from 1.11.2 to 1.11.3 ... 🚀
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '87009e7c2f2276b653b52f8415877f1f'
The crash report has been stored locally '/tmp/sentry_87009e7c2f2276b653b52f8415877f1f.json'
/Library/Ruby/Site/2.0.0/rubygems/installer.rb:450:in `initialize': [!] Operation not permitted - /usr/bin/deliver (Errno::EPERM)
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:450:in `open'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:450:in `generate_bin_script'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:430:in `block in generate_bin'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:414:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:414:in `generate_bin'
	from /Library/Ruby/Site/2.0.0/rubygems/installer.rb:254:in `install'
	from /Library/Ruby/Site/2.0.0/rubygems/request_set.rb:166:in `block in install'
	from /Library/Ruby/Site/2.0.0/rubygems/request_set.rb:150:in `each'
	from /Library/Ruby/Site/2.0.0/rubygems/request_set.rb:150:in `install'
	from /Library/Ruby/Site/2.0.0/rubygems/dependency_installer.rb:404:in `install'
	from /Library/Ruby/Site/2.0.0/rubygems/commands/update_command.rb:211:in `update_gem'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/update_fastlane.rb:86:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/update_fastlane.rb:78:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/update_fastlane.rb:78:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:162:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/runner.rb:161:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/one_off.rb:36:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/one_off.rb:22:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.43.4/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:175:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/commands_generator.rb:13:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.89.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by TKBurner** [comment]
Hi! Can you run gem update sigh and gem update deliver?

Thanks!

**Comment by charleyzhu** [comment]
# tks for you help!

install rmv and update "gem 2.64 "  "Ruby 4.2.6"  

The fastlane now works as expected

**Comment by KrauseFx** [comment]
Yeah, great to hear @charleyzhu 👍
