### ISSUE TITLE
Spaceship, download provision profiles in parallel

### ISSUE THREAD

**Issue by castus** [fastlane/fastlane#4733]
I have question regarding spaceship gem. Hope you will help me ;)
I have simple loop to download all provisioning profiles from Dev Portal:
 
```
profiles = Spaceship.provisioning_profile.all
profiles.each_with_index do |profile, index|
    File.write("#{ENV['HOME']}/Library/MobileDevice/Provisioning\ Profiles/#{profile.uuid}.mobileprovision", profile.download)
end
```
 
The question is, can I download them in parallel? Currently this process is simple serialized queue and it is a bit slow (I have more than 50 provisiones).
Somebody have a clue how I can do it? :)

Thanks!

**Comment by vpolouchkine** [comment]
That is currently not supported.

**Comment by castus** [comment]
Thanks, but do you know how can I do it in Ruby?

**Comment by KrauseFx** [comment]
I wouldn't recommend doing so, since it will probably cause additional problems. spaceship was not designed to run in parallel. This will probably have different kinds of side effects

**Comment by castus** [comment]
Thanks @KrauseFx , so it is a good time to add new functionality ;)
