### ISSUE TITLE
Sort team selections

### ISSUE THREAD

**Issue by ravinggenius** [fastlane/fastlane#4737]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When presenting the list of teams for interactive selection (both for Developer Portal and iTunes Connect), the teams are listed in whatever order Apple sends them. When scanning long lists, it would be easier to find the correct team if they were alphabetized by name.

### Environment

fastlane version (run `fastlane -v`): fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by KrauseFx** [comment]
I'm curios how many teams you have in the list 😄 

We could definitely sort them, however it's confusing when 2 teams have the exact same name (that's what I have) and so I already know if the Enterprise one is the team on the top or bottom.

**Comment by ravinggenius** [comment]
Currently we have close to 98 teams in Developer Portal and 16 in iTunes Connect. :) We're doing some organization, so we will eventually have the same number (98) in both.

If you're willing to sort the teams, I would prefer to sort by name first then by team id. This will keep them ordering consistent over time.

**Comment by KrauseFx** [comment]
Cool, thanks for letting us know. As noted above, it would be confusing for many users to change the order, so we'll leave it as is for now 👍 Thanks for your feedback

**Comment by ravinggenius** [comment]
Okay, but the order is already **not deterministic**. In iTunes Connect the team listing changes nearly every time it is displayed to me. The Developer Center listing appears to be consistent (I haven't noticed it changing), but it is still random, and Apple makes no guarantee it will remain consistent.

If it helps I'm happy to make this change.

**Comment by KrauseFx** [comment]
Interesting, I really thought it would be the same every time. Feel free to add this to spaceship, check out the code inside the `spaceship` sub-folder

**Comment by TKBurner** [comment]
@ravinggenius Marking this as help wanted in case anyone wants to submit a PR. Let me know if you are interested 👍

**Comment by ravinggenius** [comment]
@TKBurner I submitted a pull request yesterday and Felix already merged it (see above). Did I miss something?

**Comment by KrauseFx** [comment]
Yeah, thanks @ravinggenius 👍 This will be in the next spaceship release 🚀
