### ISSUE TITLE
Working on the fastlane plugin system

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#4744]
When `fastlane` was first launched, it had 10 built-in actions. Just within about a year, fastlane now features over 170 actions 🚀 

Out of those 170 actions, 121 were created by external contributors (that's 71%), a very impressive number. At this point, a big shout out and thank you to everyone bringing `fastlane` to where it is today!

Just to give you an idea of what `fastlane` can do out of the box (letters `a` to `e`):

<a href="https://gist.github.com/KrauseFx/09b72a81e25b372a756e5dadcbd55acd"><img width="1109" alt="screenshot 2016-05-19 13 58 47" src="https://cloud.githubusercontent.com/assets/869950/15409498/d59de280-1dc9-11e6-8079-cc08aa3744b5.png"></a>
[**Open the full list**](https://gist.github.com/KrauseFx/09b72a81e25b372a756e5dadcbd55acd)

Every new action, and every change of actions has to be approved by the `fastlane` team, which means we get a very high number of pull requests, improving or fixing certain actions for various web services and tools. This resulted in us being the bottleneck for new actions and improvements for existing actions.

Wouldn't it be great, if you could manage the `fastlane` action of your own tool, without having to wait for our approval every time you change something?

##### That's why we are exploring a system for `fastlane` plugins, here is how we think it could work

Let's assume there is a plugin called `tesla`, which allows you to remote control your car from within `fastlane`. To add the plugin to your project, just run:

```
fastlane add_plugin tesla
```

This will add a new `Pluginsfile`, that contains all external plugins your project uses. Additionally this will automatically install the `tesla` plugin on your local machine.

When you're on a different machine, you also have to install all required plugins, to do that run

```
fastlane install_plugins
```

And once Tesla announces, that you can now also remote control rockets with their plugin, you have full control over if and when you want to update your plugins. If you're ready, just run

```
fastlane update_plugins
```

All Tesla has to do to create their plugin, is run
```
fastlane new_plugin
```
implement and test it locally, and then push it to [RubyGems](https://rubygems.com) or GitHub.

Under the hood `fastlane` uses the great [Bundler](https://github.com/bundler/bundler) project to resolve and install dependencies. The goal is that the end-user doesn't necessarily need to understand or know about Bundler, since the target group is iOS and Android developers. 

We're actively working on this feature right now, you can follow it [over here](https://github.com/fastlane/fastlane/pull/4722): https://github.com/fastlane/fastlane/pull/4722

We would love your feedback on this, and can't wait to see what you're going to build with it 🚀

**Comment by mfurtak** [comment]
Some recent discussion also happened on https://github.com/fastlane/fastlane/issues/839, but it would be great to direct everyone's feedback here! 👍

**Comment by jcampbell05** [comment]
So happy to see #839 to become a reality!

**Comment by jcampbell05** [comment]
@KrauseFx  So https://github.com/fastlane/fastlane/pull/4722/files#diff-cf9ca7bd4b992dfc6d9b6cdb37a890c0R13 mentions that we need a way to determine when an action should become a core part of Fastlane.

I believe we should treat actions the way people treat standard libraries for languages. Actions that are bundled with Fastlane should ideally be:

- Universal (i.e Works with the standard development tools most Android or iOS developers would have installed).
- Needed Often (i.e They would solve an issue commonly encountered by Developers such as Certificate signing or bumping the build version).

Anything for a custom setup (Like a custom tool such as https://github.com/jcampbell05/xcake) should be distributed as a Gem File.

Anything not needed that often or trivial (Like perhaps printing out the current time) could either be implemented as a local action or simply written in the Fastfile as code.

**Comment by bassrock** [comment]
With this it would be great to see a search site like cocoapods has that can do the following:

* Search available plugins
* Show the current plugin version number
* Show the version of Fastlane the plugin requires/works with
* Show the readme and usage states
* Rates  the plugins based on:
 * Community Use
 * Test Coverage
 * Activity
 * etc
* Search filter for ios, android specific plugins

**Comment by KrauseFx** [comment]
@bassrock I was thinking to even use the RubyGems API to do that, it has all the things we need already 👍 

Check out the release section of the docs: https://github.com/fastlane/fastlane/blob/c74ac7ca695f807d7672fe8e294f7aa84f21d1bc/fastlane/docs/Plugins.md, I'd say we recommend to use RubyGems to distribute plugins.

**Comment by bassrock** [comment]
I think that their search api works for the short term and getting the feature out there. And you can still use RubyGems to distribute.

My concern is visibility of plugins as well as filtering with fastlane specific items (ios, android, uses spaceship, etc) and quality of the plugin.

For instance something like this: https://cocoapods.org/pods/JSQCoreDataKit/quality is one item I use on Cocoapods to determine if I should use it.  With the rate that some of the sites and tools change, I want to make sure I use a plugin to associate with Tesla, that is regularly updated, not one that gets an update once every 2 years.

I wonder if there is a way to build a fastlane plugin search system based on the RubyGems search system that would only show fastlane plugins and the data that I am suggesting above.

**Comment by blackjid** [comment]
Does the plugin manager support to import the `PluginsFile` from a git repository??

The use case is where I have a repo with a `Fastfile` that I `import_with_git` in different projects. I would like the to have the `PluginsFile` definition inside this external common repository and maybe add more plugins in the specific project.

**Comment by TKBurner** [comment]
@bassrock I think we agree that once there are many plugins we'll need a resource like this. Can we revisit this once we launch the plugin system? I want to make sure we do it right 👍

**Comment by bassrock** [comment]
@TKBurner yea that works

**Comment by KrauseFx** [comment]
@blackjid We can already auto-generate the `AvailablePlugins.md`: https://github.com/fastlane/fastlane/blob/a076f1503ba8c321cf0d4bf8c5ffbb940280bac4/fastlane/docs/AvailablePlugins.md, which is a good start 👍 

@blackjid It's a standard Gemfile, you can't import it from somewhere else, however you can easily just have your own gem hosted on GitHub that as all the other required gems as dependency 👍

**Comment by jcampbell05** [comment]
@krausefx @mfurtak

We should look into:

- update the readme to hotline to the badge in the fastlane repo
- update the docs to suggest adding the badge to the main readme of a repo for an existing gem ;) as some gems like Xcake will have the plugin in a unfolded
