### ISSUE TITLE
Supply not uploading screenshots

### ISSUE THREAD

**Issue by dmfrey** [fastlane/fastlane#4747]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I run supply with the json key it seems to update all text files and images but not the screenshots in the various size directories. The directories are located under metadata/en_US. Is there something I am missing in the setup? I did previously run init. Could there be an issue if the screenshot filenames changed? I do get a success message that everything updated OK, however the screenshots are not the new ones.
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):
0.7.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Rbenv

**Comment by vpolouchkine** [comment]
I wonder if it's because the locale dir is en_US and not en-US. Was that generated by `supply init`?

**Comment by dmfrey** [comment]
sorry, it is en-US, I was going from memory when I posted that. Here is a
tree of my metadata directory:

$ tree
.
└── en-US
    ├── changelogs
    │   ├── 10.txt
    │   ├── 11.txt
    │   ├── 12.txt
    │   ├── 13.txt
    │   ├── 14.txt
    │   ├── 15.txt
    │   ├── 16.txt
    │   ├── 17.txt
    │   ├── 18.txt
    │   ├── 19.txt
    │   ├── 20.txt
    │   ├── 21.txt
    │   ├── 2.txt
    │   ├── 3.txt
    │   ├── 4.txt
    │   ├── 5.txt
    │   ├── 6.txt
    │   ├── 7.txt
    │   ├── 8.txt
    │   └── 9.txt
    ├── full_description.txt
    ├── images
    │   ├── featureGraphic.png
    │   ├── icon.png
    │   ├── phoneScreenshots
    │   ├── promoGraphic.png
    │   ├── sevenInchScreenshots
    │   ├── tenInchScreenshots
    │   ├── tvBanner.png
    │   ├── tvScreenshots
    │   └── wearScreenshots
    ├── phoneScreenshots
    │   ├── about.png
    │   ├── home_encoders.png
    │   ├── home_recent.png
    │   ├── home_upcoming.png
    │   ├── navigation_drawer.png
    │   ├── settings.png
    │   ├── watch_recordings_details.png
    │   ├── watch_recordings_episodes.png
    │   ├── watch_recordings.png
    │   ├── watch_video_details.png
    │   └── watch_videos.png
    ├── sevenInchScreenshots
    │   ├── about.png
    │   ├── home_encoders.png
    │   ├── home_recent.png
    │   ├── home_upcoming.png
    │   ├── navigation_drawer.png
    │   ├── settings.png
    │   ├── watch_recordings_details.png
    │   ├── watch_recordings_episodes.png
    │   ├── watch_recordings.png
    │   ├── watch_videos_details.png
    │   └── watch_videos.png
    ├── short_description.txt
    ├── tenInchScreenshots
    │   ├── about.png
    │   ├── home_encoders.png
    │   ├── home_recent.png
    │   ├── home_unwatched.png
    │   ├── navigation_drawer.png
    │   ├── settings.png
    │   ├── watch_recordings_details.png
    │   ├── watch_recordings_episodes.png
    │   ├── watch_recordings.png
    │   ├── watch_videos_details.png
    │   └── watch_videos.png
    ├── title.txt
    ├── tvScreenshots
    │   ├── Main Menu.png
    │   ├── Recordings.png
    │   ├── Setting.png
    │   ├── Videos-Movies.png
    │   ├── Videos.png
    │   └── Videos-TV.png
    └── video.txt

**Comment by dmfrey** [comment]
wait, do my screenshots need to be under the images directory? I see that
they are sitting at the same level as images

**Comment by dmfrey** [comment]
This was my fault. Android Studio wasn't showing me the empty directories for the screenshots. So I created my own directories. I moved them into the correct ones under images for that language and now they are uploading
