### ISSUE TITLE
CrashlyticsHelper download_android_tools on linux

### ISSUE THREAD

**Issue by nomisRev** [fastlane/fastlane#4748]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Linux by default doesn't support the `unzip` command and thus when invoking a fastlane script that works on osx might not work on linux.

I developed a fastlane script on osx, and when invoking it form Jekins installed on Ubuntu it failed.
I'm willing to look into this later and create a pull request but for now.

**Similar bug also present in `notification action` it crashes a fastlane script run on linux or windows. I'm not sure if this is intended or forced use of crashlytics_path the desired behaviour.**

##### Complete output when running fastlane, including the stack trace and command used

```
10:46:08]: Variable Dump:
[10:46:08]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android alpha", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/home/vergasi/Android-Fastlane/app/build/outputs/apk/app-1.0.0-666-release.apk", "/home/vergasi/Android-Fastlane/app/build/outputs/apk/app-1.0.0-666-debug.apk"], :GRADLE_APK_OUTPUT_PATH=>"/home/vergasi/Android-Fastlane/app/build/outputs/apk/app-1.0.0-666-release.apk", :JACOCO_BUILD_TYPE=>"Debug"}
[10:46:08]: Error fetching remote file: Exit status of command 'unzip '/home/vergasi/Library/CrashlyticsAndroid/crashlytics-devtools.zip' -d '/home/vergasi/Library/CrashlyticsAndroid'' was 127 instead of 0.
sh: 1: unzip: not found
[10:46:08]: fastlane finished with errors

[!] Error fetching remote file: Exit status of command 'unzip '/home/vergasi/Library/CrashlyticsAndroid/crashlytics-devtools.zip' -d '/home/vergasi/Library/CrashlyticsAndroid'' was 127 instead of 0.
sh: 1: unzip: not found
```

### Configuration Files

`pw_from_keychain` is a custom action that retrieves a password from my keychain, above error occured when invoking with `password:'XXXX'`. (It is just a small ruby script with 1-2 lines of code in there and requires a specific setup in keychain that's why i choose not to merge it into fastlane repo. If some1 from fastlane is interested in this send me a pm. I'm willing to improve some scripts and share them into action like `assemble_signed_apk`)

Fastfile:
```ruby
  desc "Distribute a new Beta via Crashlytics"
  private_lane :publish_fabric_beta do |options|
    if options[:api_token] && options[:build_secret]
      api_token = options[:api_token]
      build_secret = options[:build_secret]
    else
      api_token = pw_from_keychain(service: "crashlytics", account: "api-key")
      build_secret = pw_from_keychain(service: "crashlytics", account: "build-secret")
    end

    unless api_token.empty? || build_secret.empty?
       crashlytics(api_token: api_token, build_secret: build_secret)
     else
       UI.error("No api_token or build_secret were specified. Cannot upload to BETA.")
    end 
  end
```

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No

**Comment by KrauseFx** [comment]
Nice catch, thanks for reporting this. `fastlane` was built initially for Mac OS X, and therefore there might be some rough edges when running on Linux. We don't support Windows yet. 

Replacing the `unzip` command with something Linux provides should be possible 👍

**Comment by nomisRev** [comment]
@KrauseFx after looking into a command that could replace `unzip` with something Linux provides (for all or most used linux variants). It seems that `tar` is the only solution, but `tar` does not support extracting `.zip` files.

> We don't support Windows yet.
If it's on the roadmap than some way of detecting the host platform must be implemented. The solution for this problem might be quite different depending on how this will be implemented. 

Otherwise a fix for this could be provide a `.tar` archive instead of a `.zip` and replace the `unzip` command @ line 75 with:

`Action.sh "tar -xf '#{zip_path}' -C '#{containing}'"`

The difference in size between the `.tar` and `.zip` archive is about ~ 1MB. (Tested on Ubuntu server 14.04 TLS and OSX 10.11.4)
