### ISSUE TITLE
fork/exec permission denied

### ISSUE THREAD

**Issue by devtoro** [fastlane/fastlane#4749]
Hello all,

I have installed GO 1.6 on an ubuntu gnome 15 machine, along with the latest version of delve. I am trying to to run godebug run < go file > and I get the following result:

fork/exec /home/manolis/crypteia/gospace/src/tmp/godebug870803687/godebug.a.out: permission denied

Any suggestions why this might happen? ( As you can see I changed the TEMPDIR, hoping that this issues will be solved, but with no luck )

**Comment by vpolouchkine** [comment]
Wrong GitHub project? :)
