### ISSUE TITLE
Fastlane documentation for commands in fastlane

### ISSUE THREAD

**Issue by cepages** [fastlane/fastlane#4750]
Hi

I'm trying to find the documentation for how to use the options in some commands in the `fastlane` file.

For example, I'm trying to use `match` in the `fastlane` file. I can get all the option in the terminal for the terminal command with: ```match --help``` but which are the option I can use in the `fastlane` file, like this one:

```match(git_branch: "team1", username: "user@team1.com")```

In my particular case I want to know if I can use `--force_for_new_devices` in the `fastlane` file, but it's more a general request so I won't ask the next time, if I can use this or that option :D 

Could you point me to the documentation?

**Comment by vpolouchkine** [comment]
Take a look at https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

In general, any parameter that you find via `--help` can be passed directly via the command-line or in a `Fastfile`.

**Comment by KrauseFx** [comment]
@cepages Additionally you can also run `fastlane action match` to get a description of the action with all its available parameters.

Let us know if that helps 👍

**Comment by cepages** [comment]
Yeah that's great thanks!

**Comment by KrauseFx** [comment]
🚀
