### ISSUE TITLE
Pilot and testflight doesn't resolve relative path with '~' like gym

### ISSUE THREAD

**Issue by mgrilloteravisiongames** [fastlane/fastlane#4755]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi all!! first of all, thank you for this wonderful tool, It has allowed me to save a lot of time building our applications. I'm trying to use pilot to upload into testflight a currently baked ipa, so I tried using:

pilot upload --ipa "~/Documents/Project/project.ipa" --username "user@mail.com"

And it failed with:

Could not find ipa file at path '~/Documents/Project/project.ipa'

Same thing happened with the testflight lane.

##### Complete output when running fastlane, including the stack trace and command used

```
ERROR [2016-05-20 16:01:15.97]: Error setting value '~/Documents/Project/project.ipa' for option 'ipa'
/Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/config_item.rb:80:in `rescue in valid?': [!] Could not find ipa file at path '~/Documents/Project/project.ipa' (FastlaneCore::Interface::FastlaneError)
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/config_item.rb:76:in `valid?'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/config_item.rb:61:in `verify!'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/configuration.rb:61:in `block in verify_value_exists'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/configuration.rb:55:in `each'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/configuration.rb:55:in `verify_value_exists'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/configuration.rb:39:in `initialize'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/configuration.rb:27:in `new'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/configuration/configuration.rb:27:in `create'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pilot-1.6.0/lib/pilot/commands_generator.rb:59:in `block (2 levels) in run'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.43.5/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pilot-1.6.0/lib/pilot/commands_generator.rb:126:in `run'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pilot-1.6.0/lib/pilot/commands_generator.rb:16:in `start'
	from /Users/developer/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/pilot-1.6.0/bin/pilot:6:in `<top (required)>'
	from /Users/developer/.rbenv/versions/2.3.0/bin/pilot:23:in `load'
	from /Users/developer/.rbenv/versions/2.3.0/bin/pilot:23:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

Not needed, the IPA was generated using XCODE with the correct distribution provisioning, in fact, the uploading was done with XCODE afterwards.

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

rbenv 1.0.0

**Comment by vpolouchkine** [comment]
Can you try running `pilot` from the dir where your ipa is found?

**Comment by mgrilloteravisiongames** [comment]
Running pilot from the dir where the ipa is found works perfectly @vpolouchkine

**Comment by KrauseFx** [comment]
Oh, this is actually the case across the whole code base when setting config items. Maybe that's something we can take over in our configuration manager, to detect if it's a path and try to `File.expand_path` if it starts with `~/`? 
What do you think @mfurtak @asfalcone

**Comment by mfurtak** [comment]
@KrauseFx Anything that changes the behavior of path handling for so many things will be risky, but it's probably a good idea.
