### ISSUE TITLE
Change compiler optimization level in gym

### ISSUE THREAD

**Issue by mgrilloteravisiongames** [fastlane/fastlane#4759]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I would like to know if it is possible to set the compiler optimization level from gym, because, using a less strict optimization level could give a faster build, and when you're focussed in solving logic issues instead of performance checking, it would be nice to have faster builds.

If this is not implemented, do you plan to add it in the future?, currently that can be done in XCODE as described in the section Compiler-Level Optimizations:

https://developer.apple.com/library/mac/documentation/General/Conceptual/MOSXAppProgrammingGuide/Performance/Performance.html

Best Regards,

**Comment by vpolouchkine** [comment]
If you can set those options in `xcodebuild`, you should be able to set them in `gym` as well.

**Comment by mgrilloteravisiongames** [comment]
Thanks for your response, the thing is, I'm not sure which option can I use to use that in gym, I executed fastlane action gym and read all the options, however I'm not sure which one will allow me to set the optimization parameter, do you know which one is it?

**Comment by vpolouchkine** [comment]
I believe it should be `--xcargs`, eg. "Pass additional arguments to xcodebuild. Be sure to quote the setting names and values e.g. OTHER_LDFLAGS="-ObjC -lstdc++" (GYM_XCARGS)".

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
