### ISSUE TITLE
Why the `wait_processing_interval` key not exists in deliver action

### ISSUE THREAD

**Issue by MickeyHub** [fastlane/fastlane#4765]
as we know, iTC processes the build after uploading a ipa file, the processing interval is different, may be 30 seconds, 1 minute or even 1week.
**pilot action** has the functionality that upload binary ipa, and then submit it, so pilot provide the `wait_processing_interval` key to specify the time interval to call submit api, default to 30s.
**deliver action** also has the functionality to upload & submit, but it does not provide a akin key, so why ?

**Comment by vpolouchkine** [comment]
Feel free to create a new Issue to discuss a proposed change. 👍
