### ISSUE TITLE
Confluence action

### ISSUE THREAD

**Issue by bgannin** [fastlane/fastlane#4769]
### New Issue Checklist

🔑 

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm currently working on an action for fastlane that creates a new page on a Confluence (wiki) server. The use case comes from a cultural norm we have at Atlassian: the release announcement. Typically this is a blog post containing basic info and changes that's then shared with the appropriate group(s). It's a helpful way to track various build artifacts 😃 

Currently the only supported type is 'blog post' and primary parameters include title [plain text] and content [html] along with configuration details. With some additional work it should be able to support an arbitrary child page with a specific parent instead.

### Environment

fastlane version (run `fastlane -v`): 1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? not typically

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by KrauseFx** [comment]
Hey @bgannin, thanks for submitting this issue, even with a 🔑. We're currently working on a plugin architecture that enables you to distribute and maintain your own plugins: #4744, so might be a great candidate to be one of the first publicly available plugins 👍

**Comment by bgannin** [comment]
Thanks, I'd not seen that. I'll keep working on it as a custom action until then :)

**Comment by KrauseFx** [comment]
Perfect, yeah, migrating the custom action to a plugin will be very easy to do 🚀

**Comment by TKBurner** [comment]
@bgannin Thanks for following up. Feel free to reach out if you run into issues developing your plugin.

👍
