### ISSUE TITLE
Set aps-environment entitlement to production

### ISSUE THREAD

**Issue by ignacioalles** [fastlane/fastlane#477]
When submitting an IPA to Apple Store aps-environment entitlement has to be set to production. 
The error returned is:
ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/appname.app/appname' is not supported."]

resign.sh script set other entitlement values (beta-reports-active, get-task-allow) and it may set this value as well.

**Comment by KrauseFx** [comment]
Have you tried deleting and re-generating your provisioning profile?

**Comment by ignacioalles** [comment]
Mi provisioning profile has aps-environment set to production but the IPA I was resigning was generated with development value.

As far as I can see in resign script, most of entitlements is preserved from IPA, isn't it?

**Comment by fatuhoku** [comment]
+1 I've run into this issue as well just now.

**Comment by fatuhoku** [comment]
I don't understand enough about what on earth `aps-environment` is supposed to be. It's not a configuration setting, you can find anywhere...  all I know is that it's something related to push notifications.

**Comment by fatuhoku** [comment]
I am pretty sure that the provisioning profile I'm working with is not outdated (i.e. generated before the Push Notifcation certificate was generated); because it's worked for me in the past.

**Comment by fatuhoku** [comment]
I think Xcode might have built the IPA with code signing for `Development` in mind (see my explanation in fastlane/examples#2) and therefore included development entitlements (???) into the IPA, which `resign` doesn't pick up on. Is that how it works? :S

**Comment by kristofer** [comment]
there are a couple of weird aspects to Xcode 7 and I'm getting this "aps-environment development not supported" error
http://stackoverflow.com/questions/18969988/getting-error-itms-9000-when-trying-to-upload-an-app-using-application-loader
http://stackoverflow.com/questions/28106791/error-itms-90164-90046-invalid-code-signing-entitlements

these have different effects, but the combined aspects, well, you might want to make sure neither is the case.

**Comment by JaviSoto** [comment]
Hi @kristofer! 
Is this still an issue when using the new `gym` to build and package your app?

**Comment by asfalcone** [comment]
Going to close this since it has been open for a while without response.
