### ISSUE TITLE
Need ability to specify app_identifier in latest_test_flight_build_number action

### ISSUE THREAD

**Issue by BigSauce** [fastlane/fastlane#4773]
I have an Xcode project with multiple targets, and I would like to be able to increment the build number to be the latest Test Flight build number + 1.  The problem is that my lanes have varying app_identifier values, and it seems that the current version of this action does not support specifying an app identifier.

Is this something the current contributors might consider supporting?

**Comment by vpolouchkine** [comment]
Not on our radar, but I'll keep this open for any upvotes.

**Comment by BigSauce** [comment]
I have written my own script to increment a target's build number, but I need to be able to tell `latest_test_flight_build_number` which target I'm asking about.  Does `latest_test_flight_build_number` have the same `avgtool` limitation as the contributors in #837 describe?  Is there a way that `latest_test_flight_build_number` can be modified to accommodate an `app_identifier` parameter?

**Comment by TKBurner** [comment]
Hi @BigSauce Thanks for following up. Have you used the increment_build_number action? Is the root of the problem that you need to query from Test Flight first? Thanks!
