### ISSUE TITLE
Gym is unable to find provisioning profiles when invoked from a Fastlane lane

### ISSUE THREAD

**Issue by BigSauce** [fastlane/fastlane#4774]
If I run 
`gym --scheme "Scheme Name"`
 directly from the terminal, my app builds fine.

However, if I run either 

`gym(scheme: "Scheme Name")`
 or 
`gym(scheme: "#{gym_build_scheme}")`

 from within a lane in my Fastfile, I get an error explaining that no non-expired provisioning files were found.

Here are my two lanes.  When invoking Fastlane, I do so by using `fastlane ios beta_mo`

![image](https://cloud.githubusercontent.com/assets/1718470/15452670/62569ef8-1fc6-11e6-88c1-d6fb80dc1a7c.png)

![image](https://cloud.githubusercontent.com/assets/1718470/15452656/c66611a4-1fc5-11e6-8268-3b51ed650655.png)

This is a particularly frustrating issue, as I don't understand what `gym` could be doing differently based upon whether I invoke `gym` directly from the terminal or if `gym` is invoked from a lane.  Below is the error I get when invoking gym with a scheme from the lane.

![image](https://cloud.githubusercontent.com/assets/1718470/15452689/1dc26712-1fc7-11e6-90ed-87574dea76eb.png)

However, when I use the terminal command `gym --scheme "Scheme Name"` (my scheme name is "Motion Organized"), it builds successfully without any provisioning issues.

The `gym` summary printouts are identical whether I invoke directly from terminal or through the lane.

*Directly from Terminal*
![image](https://cloud.githubusercontent.com/assets/1718470/15452807/c2d8343c-1fc9-11e6-9c4b-4bb00ba9d2ac.png)

*Invoking `gym` from a lane*
![image](https://cloud.githubusercontent.com/assets/1718470/15452762/fc1470be-1fc7-11e6-9114-1bb7608517b3.png)

For reference and for SEO, here is the error:
`Code Sign error: No provisioning profiles found: No non–expired provisioning profiles were found.`

Does anybody have any ideas as to what I might be able to do to work around this issue?

Please let me know if you need any additional information.

Thanks!

**Comment by vpolouchkine** [comment]
Can you try adding calls to `cert` and `sigh` before `gym`?

**Comment by BigSauce** [comment]
Thanks for your prompt response, @vpolouchkine.

Per your request, I added (to my lane) calls to `cert` and `sigh` before `gym`, and I received the same error.

I think a telling sign that this may be a bug is that I get different results when invoking `gym` from different places.  `gym` fails to find provisioning profiles when run from a lane but succeeds when running directly from terminal using identical parameters.

**Comment by BigSauce** [comment]
@vpolouchkine: In my previous message, I was a bit unclear when I said that `gym`

> [`gym`] succeeds when running directly from terminal.

What I meant is that the build succeeds when running `gym` from terminal and fails after a few seconds when running from a lane.  When running `gym` from either, however, it ultimately ends up with this error message.  Please note that I have replaced the app name with `<AppName>` and my project name with `<ProjectName>`, due to an NDA to which I am bound.

> [01:28:21]: ▸ Touching <AppName>.app
[01:28:21]: ▸ Signing /Users/Alex/Library/Developer/Xcode/DerivedData/<ProjectName>-fwoucivldnnsgoawkbrrzykriffp/Build/Intermediates/ArchiveIntermediates/<AppName>/InstallationBuildProductsLocation/Applications/<AppName>.app
[01:28:22]: ▸ Touching <AppName>.app.dSYM
[01:28:22]: ▸ Archive Succeeded
xattr: No such file: /Users/Alex/Library/Developer/Xcode/Archives/2016-05-24/<AppName> 2016-05-24 01.27.03.xcarchive
[01:28:22]: The generated archive is invalid, this can have various reasons:
[01:28:22]: Usually it's caused by the `Skip Install` option in Xcode, set it to `NO`
[01:28:22]: For more information visit https://developer.apple.com/library/ios/technotes/tn2215/_index.html
[01:28:22]: Also, make sure to have a valid code signing identity and provisioning profile installed
[01:28:22]: Follow this guide to setup code signing https://github.com/fastlane/fastlane/blob/master/fastlane/docs/CodeSigning.md
[01:28:22]: If your intention was only to export an ipa be sure to provide a valid archive at the archive path.
[!] Archive invalid

I have run both cert and sigh and have still gotten this error message every time.  Archiving from Xcode works just fine, so I'm not sure why `gym` is having so much difficulty finding the right profile to use.

Any other debug steps or tips you may have would be greatly appreciated.  Thanks, again!

**Comment by BigSauce** [comment]
Oh, snap.  The archives aren't even showing in Xcode's Organizer anymore.  Please standby on this issue until I confirm that I didn't derp something on my end.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue, so I’m closing it. If this is still a problem, feel free to re-open and I’d be happy to help :+1:
