### ISSUE TITLE
Gym derived_data_path

### ISSUE THREAD

**Issue by nbeithalevi** [fastlane/fastlane#4775]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hi, 

On my local machine i'm using Xcode's 'Shared Folder' in the location section in order to generate at the end of the run code coverage. My issue is: how do I set with a remote machine via terminal? (I do not have access to xcode)
I've tried to use the gym "derived_data_path" so I can generate from there the coverage but without success... It can not find the right file. Any ideas ?
##### Complete output when running fastlane, including the stack trace and command used

```
No such file or directory```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by vpolouchkine** [comment]
Just to confirm, are you trying to build an ipa using `gym` for which the source is located somewhere remotely?

**Comment by nbeithalevi** [comment]
Hi, thanks for your quick reply..

Yes, then I want that the files will be copied to the shared folder so I
can run the code coverage.

But I don't have access to the xcode on that remote.

Is there a way to change the destination of the folder.. I tried the
derived_data_path but it did not copy any files..

Thx.

Nadav

On Mon, May 23, 2016 at 8:35 PM, Val Polouchkine <notifications@github.com>
wrote:

> Just to confirm, are you trying to build an ipa using gym for which the
> source is located somewhere remotely?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fastlane/fastlane/issues/4775#issuecomment-221039924>
>



-- 
[image: Ping Identity logo] <https://www.pingidentity.com/>
Nadav Beithalevi
Mobile Developer
Ping Identity
@ nbeithalevi@pingidentity.com
[image: phone] [Enter Number]
[image: twitter] @pingidentity
Connect with us!

[image: pingidentity.com] <https://www.pingidentity.com/>
[image: twitter logo]
<http://www.glassdoor.com/Overview/Working-at-Ping-Identity-EI_IE380907.11,24.htm>
[image:
twitter logo] <https://twitter.com/pingidentity> [image: youtube logo]
<https://www.youtube.com/user/PingIdentityTV> [image: LinkedIn logo]
<https://www.linkedin.com/company/21870> [image: Facebook logo]
<https://www.facebook.com/pingidentitypage> [image: Google+ logo]
<https://plus.google.com/u/0/114266977739397708540> [image: slideshare logo]
<http://www.slideshare.net/PingIdentity> [image: rss feed icon]
<https://www.pingidentity.com/blogs/>
------------------------------
[image: CIS 2016] <https://www.cloudidentitysummit.com/en/index.html>

**Comment by vpolouchkine** [comment]
Well, you can use the `--project` argument to specify where the project is located and the `--destination` argument to specify where to build the app. Unless I'm missing something here.

**Comment by nmayafit** [comment]
Hi @vpolouchkine,
What we are trying to achieve is the same result as when you go into Xcode's prefs and change the Derived Data build location into a shared Build folder. This way, all of our developers change to this shared location on their Xcode, and the build path is always the same in the Derived Data folder. But, you need to do it manually from Xcode. What we need is a way to do it also from Fastfile gym as our build machine is a remote jenkins and there is no way to open Xcode in this machine and start playing with its configurations.

**Comment by nmayafit** [comment]
OK,

derived_data_path did it.

Thanks.

**Comment by TKBurner** [comment]
@nmayafit Awesome! Glad to hear you got up and running. Hope that you have a wonderful weekend coming up 👍
