### ISSUE TITLE
problem with  devices_file option of register_devices

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#4782]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
it works if use the devices option. 
devices: {
         'My iPhone6' => 'A123456789012345678901234567890123456789'
      }
##### Complete output when running fastlane, including the stack trace and command used

```
NFO [2016-05-22 22:56:57.82]: ------------------------------
INFO [2016-05-22 22:56:57.82]: --- Step: register_devices ---
INFO [2016-05-22 22:56:57.82]: ------------------------------
INFO [2016-05-22 22:57:04.15]: Fetching list of currently registered devices...
WARN [2016-05-22 22:57:04.36]: Variable Dump:
INFO [2016-05-22 22:57:04.36]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios devices_old"}
ERROR [2016-05-22 22:57:04.36]: Invalid device line, please provide a file according to the Apple Sample UDID file (https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip)
INFO [2016-05-22 22:57:04.36]: Successfully generated documentation to path '/Users/vamsee/Development/MyApp/myapp-ios/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 4           |
| 4    | register_devices                    | 6           |
+------+-------------------------------------+-------------+

ERROR [2016-05-22 22:57:04.37]: fastlane finished with errors
/Users/vamsee/Software/ruby/gems/fastlane_core-0.43.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Invalid device line, please provide a file according to the Apple Sample UDID file (https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip) (FastlaneCore::Interface::FastlaneError)
	from /Users/vamsee/Software/ruby/gems/fastlane_core-0.43.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/vamsee/Software/ruby/gems/fastlane-1.89.0/lib/fastlane/actions/register_devices.rb:40:in `block in run'
	from /Users/vamsee/Software/ruby/gems/fastlane-1.89.0/lib/fastlane/actions/register_devices.rb:37:in `map'
	from /Users/vamsee/Software/ruby/gems/fastlane-1.89.0/lib/fastlane/actions/register_devices.rb:37:in `run'
	from /Users/vamsee/Software/ruby/gems/fastlane-1.89.0/lib/fastlane/runner.rb:177:in `block (2 levels) in execute_action'
	from /Users/vamsee/Software/ruby/gems/fastlane-1.89.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
```

### Configuration Files
I got the sample file from this place and it looks like this:
(https://devimages.apple.com.edgekey.net/downloads/devices/Multiple-Upload-Samples.zip
It has these 3 files. 

multiple-device-upload-ios.deviceids 
multiple-device-upload-ios.txt        
multiple-device-upload-mac.txt

I made my devices file look like multiple-device-upload-ios.txt  , reproduced below:

Device ID       Device Name
A123456789012345678901234567890123456789        NAME1
B123456789012345678901234567890123456789        NAME2

### Environment

fastlane version (run `fastlane -v`)
1.89.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by vpolouchkine** [comment]
Can you try formatting it per multiple-device-upload-ios.deviceids?

**Comment by lakamsani** [comment]
Hi,  using that file format gave a different error. I enabled crash reporting and it uploaded something to sentry. The crash id is: 7e664f679c9ea71a6164ecb22e2618cb

Here is the file:

``
 ✗ more fastlane/multiple-device-upload-ios.deviceids
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>Device UDIDs</key>
        <array>
                <dict>
                        <key>deviceIdentifier</key>
                        <string>A123456789012345678901234567890123456789</string>
                        <key>deviceName</key>
                        <string>My iPhone6</string>
                </dict>
        </array>
</dict>
</plist>
``

the lane
`` 
  lane :devices do
    register_devices(
        devices_file: 'fastlane/multiple-device-upload-ios.deviceids'
    )

  end
``
and the log
``
ERROR [2016-05-23 10:50:01.00]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '7e664f679c9ea71a6164ecb22e2618cb'
The crash report has been stored locally '/tmp/sentry_7e664f679c9ea71a6164ecb22e2618cb.json'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1854:in `block (2 levels) in shift': [!] Illegal quoting in line 1. (CSV::MalformedCSVError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1816:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1816:in `block in shift'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1776:in `loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1776:in `shift'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1718:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1732:in `to_a'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/csv.rb:1732:in `read'
``

**Comment by vpolouchkine** [comment]
Gotcha. Thanks for trying that out, we'll investigate on our end.

**Comment by vpolouchkine** [comment]
@lakamsani Could you send over the file that you've created per multiple-device-upload-ios.txt?

**Comment by lakamsani** [comment]
[multiple-device-upload-ios.txt](https://github.com/fastlane/fastlane/files/298628/multiple-device-upload-ios.txt)
Its attached. I changed the names and device ids a bit to anonymize

**Comment by vpolouchkine** [comment]
Can you try replacing spaces by a tab between the entries?

**Comment by lakamsani** [comment]
Just the tab did not work, but what worked was a tab and a space between the id and the name!.  Very sensitive. 

I found this out by copying the apple text file and carefully comparing the spaces and tabs between the id and the name. When I tried initially I did not pay much attention to the spaces or tabs.

**Comment by vkaramov** [comment]
The problem still exists. The new device is added, but error is shown anyway
