### ISSUE TITLE
Add new parameters and options to pilot

### ISSUE THREAD

**Issue by MickeyHub** [fastlane/fastlane#4783]
For each Build, There are some info to fill:
- What to test
- App description
- Feedback email
- Marketing URL
- Support URL
- Privacy policy URL (optional)
- Beta App Review contact information
- Beta App Review notes (optional)

but pilot action doesn't provides the functionality to setup these values.

so is it possible that setup these value in a config file called Pilotfile, and enhanced pilot using this file to set these values?

**Comment by ajwalters** [comment]
I've been hitting this same problem trying to automate our test flight setup process.  It would be nice to avoid having to manually go to iTunes Connect to enter these values.  Without them, fast lane fails after the upload completes

**Comment by vpolouchkine** [comment]
Thanks for the feature request; keeping this open for upvotes.

**Comment by MickeyHub** [comment]
it's open for upvotes

**Comment by TKBurner** [comment]
@MickeyHub Sounds good! We are retiring things that haven't gotten any attention in 6 months, but if you are still interested we'll leave this open!

**Comment by youngrafi** [comment]
At least some of this seems to be covered in https://github.com/fastlane/fastlane/pull/5455

**Comment by pedro380085** [comment]
Have these fields been supported?
