### ISSUE TITLE
Fastlane is not pushing the app to testflight when bitcode is enabled  

### ISSUE THREAD

**Issue by esivakumar** [fastlane/fastlane#4787]
### Issue Description

When build is uploaded to test flight ,success message is displayed in command line  but failure notification is sent via email. This scenario only occurs when bit code is enabled .

### Error message displayed in mail

```
We have discovered one or more issues with your recent delivery for "Networking Demo App". To process your delivery, the following issues must be corrected: 
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it. 
Once these issues have been corrected, you can then redeliver the corrected binary. 

```

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue, so I’m closing it. If this is still a problem, feel free to re-open and I’d be happy to help :+1:
