### ISSUE TITLE
Enable to collect screenshots even if some tests fail

### ISSUE THREAD

**Issue by bobish31** [fastlane/fastlane#4788]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Improvement Description

I have a particular use case using Snapshot : I need to deliver a report after a Xcode server integration showing tests results and screenshots about my UI tests.

I build a custom report thanks to the Xcode server API to show the tests results to my client.
In this scenario, I launch first an Xcode integration, and then launch Snapshot as an after trigger of the integration to collect screenshots.

You got it, I have to test twice my app, once to get tests results and once to collect screenshots.. And it can be dangerous : I have the case when Xcode tests passed but not Snapshots's.. so my report indicates a green tick saying this test is ok but I don't have screenshots to prove it because Snapshot fails on this test.

That is why I create this improvement request, even if this is not the best way to do, but it will improve a little my process.
An other solution would be Snapshot creates an integration as Xcode server's integrations with the ability to request later the Xcode Server API to get tests results from the Snapshot's integration.

Hope you'll take this improvement request as a prior one 👍 
Thanks !

**Comment by vpolouchkine** [comment]
This is something that we've heard a few people asking for; keeping this open for upvotes.
