### ISSUE TITLE
Update fastlane slather action to support new commands

### ISSUE THREAD

**Issue by bootstraponline** [fastlane/fastlane#4796]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane's slather action is out of date. Critical commands are missing.

I've [sent a pull request](https://github.com/fastlane/fastlane/issues/4799) which adds the following commands:

- teamcity
- verbose
- source_files
- decimals

**Comment by TKBurner** [comment]
Hi @bootstraponline Great to hear from you and thanks for this submission. Since you included test coverage we'll be able to review this faster. We'll work with you on your PR. Thanks 👍

**Comment by bootstraponline** [comment]
Thank you! This has been merged in https://github.com/fastlane/fastlane/issues/4825 Sorry for all the noise.
