### ISSUE TITLE
Enable crash reporting no longer working

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#4800]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane enable_crash_reporting
[15:12:48]: ------------------------------
[15:12:48]: --- Step: default_platform ---
[15:12:48]: ------------------------------
[15:12:49]: Variable Dump:
[15:12:49]: {:DEFAULT_PLATFORM=>:ios}
[15:12:49]: Could not find lane 'ios enable_crash_reporting'. Available lanes: ios testflight, ios hockeyapp, ios hockeyapp_travesty

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
+------+------------------+-------------+

[15:12:49]: fastlane finished with errors

[!] Could not find lane 'ios enable_crash_reporting'. Available lanes: ios testflight, ios hockeyapp, ios hockeyapp_travesty
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
```

Not relevant, `fastlane enable_crash_reporting` doesn't depend on `Fastfile`.

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.90.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No

**Comment by KrauseFx** [comment]
We actually removed crash reporting today, so you can't enable it any more. Thanks for helping by trying to enable it though, really appreciated 👍 
Instead if you have any issues, please submit an issue on GitHub

**Comment by KrauseFx** [comment]
I'll update fastlane to show an appropriate error message instead though 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/4805 🚀
