### ISSUE TITLE
iTunes Connect Analytics

### ISSUE THREAD

**Issue by ravinggenius** [fastlane/fastlane#4801]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'd like to download analytics, but I haven't found a Ruby library to do so. I poked around and didn't see a way to get analytics using Spaceship; is it supported? If not what is the interest in adding it?

### Environment

fastlane version (run `fastlane -v`): fastlane 1.90.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by KrauseFx** [comment]
There are some issues for that already: https://github.com/fastlane/fastlane/search?q=iTunes+Connect+Analytics&type=Issues&utf8=%E2%9C%93

Some contributors already started building it (https://github.com/fastlane-old/spaceship/pull/190), however it doesn't seem like it got merged.

You might want to reach out on that issue and offer your help if you want to 👍

**Comment by KrauseFx** [comment]
Closing this for now 👍
