### ISSUE TITLE
[Feature] Add overlay image on icons action

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#481]
I created an action to apply overlay images on icons as a part of our build process. 

The result can be seen here:

![](https://www.dropbox.com/s/ar1wcm49s7o7tlz/playkids-icons.png?dl=1)

I posted the action on a Gist (https://gist.github.com/marcelofabri/ac3884d6170ee6414257) to gather feedback before creating a PR. It's not very generic yet because we don't need it now.

**Comment by KrauseFx** [comment]
This looks nice :+1: 

Some notes:
- You can remove `ADD_ICON_OVERLAY_CUSTOM_VALUE`
- `mini_magick` should be added as dependency for `fastlane` in the `fastlane.gemspec`
- If the path to `appiconset_path` is wrong, this will modify and replace all the `png` files there, right? 

How do you use it? Do you store the resulting image in git? Or do you use this action and then do a `git reset` afterwards?

**Comment by marcelofabri** [comment]
> If the path to appiconset_path is wrong, this will modify and replace all the png files there, right?
Yep. Any ideas to make it better?

> How do you use it? Do you store the resulting image in git? Or do you use this action and then do a git reset afterwards?
I don't store them, doing a git reset after. This is because each lane can use a different overlay, so it doesn't make sense for us to commit. Only the "clean" version is versioned.

**Comment by iainsmith** [comment]
I was hoping someone had already built this. 😀

It can also be very helpful to add either the first few characters of the sha-1 or the build number. That way everyone can easily see exactly what build they have.

**Comment by coreyfloyd** [comment]
@marcelofabri Awesome work!

As for improvements, I agree with @iainsmith - It would be great to pass arbitrary text and maybe a color so we can customize the overlay at build time.

I currently have something like this in my Xcode build phases. We use image magic to overlay the build number and the build type (beta/alpha/etc…). 

It looks something like this:

```
convert -background $overlay_color -fill white -gravity center -size ${overlay_width}x${overlay_height}\
caption:"${CONFIGURATION}\n(${build})"\
"${source_icon_path}" +swap -gravity south -composite "${target_icon_path}"
```

**Comment by KrauseFx** [comment]
@coreyfloyd agreed, instead of providing multiple images, passing a color + text and maybe a font should be the way to go :+1:

**Comment by vinnybad** [comment]
@coreyfloyd @KrauseFx it would be great if the commit hash were also on the app icon in case we need to identify the exact commit.  I've found it useful on some of my projects.  Here's a quick way to do it:

commit=`git rev-parse --short HEAD`

**Comment by squarefrog** [comment]
I've had a quick play with this today. Works great.

I've tried converting the action to support text, and it's not without difficulty. Here are a few of the issues I ran into:

- It's not enough to just require the `mini_magick` gem. Unsurprisingly, you need to have `imagemagick` installed ( `brew install imagemagick` ).
- by default, `imagemagick` needs some extra extensions to support text `brew install imagemagick --with-fontconfig=yes --with-freetype=yes`
- additionally, you need the ghostscript fonts - `brew install gs`

I've got the basic overlays working, but I've wasted a whole morning trying to figure out the rotated coordinate space. Now my head hurts and I need a little sleep so I'll leave [this gist](https://gist.github.com/squarefrog/324d3e114f2c63135bc0) here incase anyone else wants to carry on.

The basics of the function is ensuring you've installed the previous brews and adding this:

```ruby
width = original_icon.width
height = original_icon.height
rect_height = 10
x = width / 1.5
text_size = width / 8
padding = text_size / 2

result = original_icon.combine_options do |c|
  #c.fill('#FF00FF') # you can set the fill of the rectangle here
  #c.draw "rotate -45 rectangle #{x},#{x},1,1" # uncomment this to draw a rotated rectangle in the wrong place
  c.fill('#FFFFFF') # set the text fill colour
  c.gravity 'Northeast' # anchor the text to the top right
  c.draw "rotate 45 text #{text_size + padding},#{text_size + padding} 'BETA'" # draw text
  c.pointsize "#{text_size}" # set font size
  #c.font 'Helvetica' # must be in font list `convert -list font`
end
```

Personally, it's a whole lot of work, when simply overlaying the images works well!

**Comment by squarefrog** [comment]
Oh and I had to set `result.format 'png'` before `result.write icon` or Xcode would refuse to compile my new assets :disappointed:

**Comment by KrauseFx** [comment]
@squarefrog About ImageMagic: I know that `frameit` requires it as well

I have this code as `dependency_checker.rb`

```ruby
    def self.check_image_magick
      unless `which convert`.include? "convert"
        Helper.log.fatal '#############################################################'
        Helper.log.fatal "# You have to install the ImageMagick to use FrameIt"
        Helper.log.fatal "# Install it using 'brew update && brew install imagemagick'"
        Helper.log.fatal "# If you don't have homebrew: http://brew.sh"
        Helper.log.fatal '#############################################################'
        raise "Install ImageMagick and start frameit again!"
      end
    end
```

**Comment by KrauseFx** [comment]
Thanks for taking a look at this integration :+1:

**Comment by squarefrog** [comment]
I suppose in that case, it may still be worth going for it. 

However someone with better knowledge about coordinates will have to take over, as I cant wrap my head around translating the position on a rotated canvas!

**Comment by esttorhe** [comment]
Guys; I played with this some and added a bunch of crazy optionals; don't know if I overdid or not but attached are 3 possible icons you get with my modified action (besides the image overlay already created):
![icon-60 2x 3](https://cloud.githubusercontent.com/assets/2642850/10716676/fdb0c75e-7b05-11e5-9010-358abe9530a1.png)
![icon-60 2x 2](https://cloud.githubusercontent.com/assets/2642850/10716675/fdaed8a4-7b05-11e5-941f-66f97d898480.png)
![icon-60 2x](https://cloud.githubusercontent.com/assets/2642850/10716677/fdb0f0bc-7b05-11e5-9cc3-e82c36261f58.png)

---

I added 2 new possible overlay types `banner` and `text` (there's also `image`).
With text you get to choose if you want it `north` or `south` and on both you can customize the following:

- text_background_color
- text_foreground_color
- text_overlay_height
- text_overlay
- text_overlay_font

---

Going to move it to my fork and I'll issue a `PR` for this if anyone is interested; eventually I would like to support the position of the banner because ATM I'm drawing it always in the top right corner of the icon

**Comment by esttorhe** [comment]
```console
Loading documentation for add_icon_overlay:

+------------------------------------------------------------------------------------------------------------------------------------+
|                                                          add_icon_overlay                                                          |
+------------------------------------------------------------------------------------------------------------------------------------+
| Overlays an image or text over all icons.                                                                                          |
|                                                                                                                                    |
| Overlays an image or text over all icons, using ImageMagick and replacing the old icons.                                           |
|         Text overlay based off @merowing's script http://merowing.info/2013/03/overlaying-application-version-on-top-of-your-icon/ |
|         Banner overlay based off of @squarefrog's comment https://github.com/KrauseFx/fastlane/issues/481#issuecomment-147368555   |
|                                                                                                                                    |
| Created by esttorhe, marcelofabri                                                                                                  |
+------------------------------------------------------------------------------------------------------------------------------------+

+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+
|                                                                                             add_icon_overlay                                                                                              |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+
| Key                   | Description                                                                                                                           | Env Var                                   |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+
| * appiconset_path     | Path for .appiconset containing the icons (default: '**/AppIcon.appiconset')                                                          | FL_ADD_ICON_OVERLAY_APPICONSET_PATH       |
| overlay_image_path    | Path for the image that will be overlaid on the icons                                                                                 | FL_ADD_ICON_OVERLAY_OVERLAY_IMAGE_PATH    |
| * overlay_type        | Flag specifying if an image, text or banner will be overlayed over the icon (default: 'text')                                         | FL_ADD_ICON_OVERLAY_OVERLAY_TYPE          |
| text_background_color | Background color for the text overlay. If a hex value is provided must contain the '#' character (default: '#C2C2C3')                 | FL_ADD_ICON_OVERLAY_TEXT_BACKGROUND_COLOR |
| text_foreground_color | Foreground color for the text overlay (Text color). If a hex value is provided must contain the '#' character (default: 'white')      | FL_ADD_ICON_OVERLAY_TEXT_FOREGROUND_COLOR |
| text_overlay_height   | Height of the overlay in respect to the overall height of the icon (e.g. 0.5 for 50%) (default: '0.3')                                | FL_ADD_ICON_OVERLAY_OVERLAY_HEIGHT        |
| text_overlay          | The text to be overlayed over the icon; can contain '\t' and '\n' when overlay type is 'text', not on 'banner'                        |                                           |
| text_overlay_position | Where on the icon the text will be overlayed (south & north) (default: 'south')                                                       | FL_ADD_ICON_OVERLAY_TEXT_OVERLAY_POSITION |
| text_overlay_font     | Name of the font to be used on the text overlay. Must be in font list `convert -list font or full path to font (default: 'Helvetica') | FL_ADD_OVERLAY_ICON_FONT                  |
+-----------------------+---------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------+
2 of the available parameters are required
They are marked with an asterix *

More information can be found on https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```

**Comment by squarefrog** [comment]
Exciting! Looking forward to see how you solved sizing. I figured out how to draw the banner and text but things fell apart when you used something other than `beta` for the text!

**Comment by esttorhe** [comment]
Latest build on `CI` just failed with this message:
>ImageMagick/GraphicsMagick is not installed

So yeah; had to add the `brew install`s to the `before_install`

**Comment by esttorhe** [comment]
well… even with `brew install gs` my build is hanging forever on `TravisCI` when trying to overlay the icon :cry:

**Comment by serluca** [comment]
Any news on this?

**Comment by esttorhe** [comment]
Haven't had the time to work on this. I saw another action that does the same banner approach with a baked in image and also ads a badge with the version.

This action works fine for custom labels and custom banners as long as the banner text is 1 word middle long or short/

We moved from `Travis` to `Xcode Bots` so won't be able to try much on `Travis` more though

**Comment by ohwutup** [comment]
Going to close this issue for now as I believe there is another action -- `badge`that will do this. Let us know if you are still having any issues and please feel free to reopen it! :name_badge:

**Comment by esttorhe** [comment]
I think it does most of what I need (the new action) and for the edge cases i can always fallback to my own but those are fewer and fewer each day so i think its :100: to close this

**Comment by ohwutup** [comment]
awesome! thanks @esttorhe! and please feel free to reopen this or open another issue if there are still problems with it!
