### ISSUE TITLE
Danger is broken and failing pull requests

### ISSUE THREAD

**Issue by bootstraponline** [fastlane/fastlane#4810]
Danger is broken and is failing non-contributor pull requests

- https://github.com/fastlane/fastlane/pull/4799 && https://circleci.com/gh/fastlane/fastlane/2363
- https://github.com/fastlane/fastlane/pull/4697 && https://circleci.com/gh/fastlane/fastlane/2221

```
bundle exec danger
Your build output is too large to display in the browser. Only the first 400000 characters are displayed.
Download the full output as a file.
fatal: Not a valid branch point: '4d22f03f0181e6085053d9e4d1cd5da23b3758e5'.
error: packfile .git/objects/pack/pack-09e7a1fd28e5ceb3bdda92f31d5e8f415e28be98.pack does not match index
er
```

fastlane team members aren't impacted because danger is skipped.

> Not a Pull Request - skipping `danger` run
- https://circleci.com/gh/fastlane/fastlane/2365

**Comment by bootstraponline** [comment]
Based on the error message, danger appears to error when a pull request is force pushed to. The only work around is to close & resubmit the pull request.

**Comment by asfalcone** [comment]
Rebase and force pushing should work. #4799 ended up with a green checkmark from CI so I'm going to close this isn't since there isn't any action for us to take 👍

**Comment by bootstraponline** [comment]
> there isn't any action for us to take 👍

Fixing Danger isn't an action? At least so it doesn't fail PRs when it crashes.
