### ISSUE TITLE
Crash when running `sigh download_all`

### ISSUE THREAD

**Issue by BigSauce** [fastlane/fastlane#4813]
Here is the crash report number: `a9b451ab797c1a5f17fe642a62451ec4`.  Looks like a permission denied error.  Let me know if you need any other info not already included in the stack trace listed in the aforementioned Sentry crash report.

**Comment by BigSauce** [comment]
It worked once I ran `sudo sigh download_all`.  Is this the intended approach to using this command?

**Comment by TKBurner** [comment]
@BigSauce Are you using RVM? That should get rid of your need to have sudo in front of your command. Otherwise yes, that is expected. Thanks! 👍
