### ISSUE TITLE
please add the ensure_git_status_clean action to the beginning of your lane, or if you're absolutely sure of what you're doing then call this action with the :force option

### ISSUE THREAD

**Issue by nbeithalevi** [fastlane/fastlane#4817]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hi,

I've two lanes. 
The first run unit tests and automation (called 'test_lane') and just before it ends I push to git the changes.
The second lane (called 'hockeyapp_lane') uplaods to hockeyapp the .ipa files.
when I try to switch to the second lane I get the exception to add 'ensure_git_status_clean', so i've added it and still got the same error (I've added the force option as well).

When I try to run one lane that contains the two - everything works... 

What am i missing ?

##### Complete output when running fastlane, including the stack trace and command used

```
This is a destructive and potentially dangerous action. To protect from data loss, please add the `ensure_git_status_clean` action to the beginning of your lane, or if you're absolutely sure of what you're doing then call this action with the :force option.```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):1.9.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?no

**Comment by vpolouchkine** [comment]
Can you please share your `Fastfile` and the full log? Thanks!

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue, so I’m closing it. If this is still a problem, feel free to re-open and I’d be happy to help :+1:
