### ISSUE TITLE
[testfairy action] enable parameters/options

### ISSUE THREAD

**Issue by tcurdt** [fastlane/fastlane#4819]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Right now the parameters for the testfairy upload are very limited. I would like set a couple more parameters on the upload.

##### Complete output when running fastlane, including the stack trace and command used

NA

### Configuration Files

NA

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

    testfairy(
      api_key: "...",
      comment: notes,
      testers_groups: [ 'all' ],
      symbols_file: Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH],
      auto_update: 'on',
      icon_watermark: 'on',
      options: [ 'shake' ]
    )

### Environment

fastlane version (run `fastlane -v`): fastlane 1.90.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? chruby

**Comment by vpolouchkine** [comment]
Thanks for the contrib!

**Comment by tcurdt** [comment]
@vpolouchkine anything else I can do to get this merged?

**Comment by vpolouchkine** [comment]
Looks like asfalcone is already chatting with you in the PR.
