### ISSUE TITLE
Deliver - Non-Interactive Mode not working for initial setup

### ISSUE THREAD

**Issue by BKAppsmart** [fastlane/fastlane#4820]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
So, I want to set up a folder that builds "deliver" areas for all of our app in the iTunes store so that we can easily edit metadata and use deliver's submit_build feature (which is awesome by the way thanks for that!) to submit the build for review automatically whilst at the same time pumping in updated metadata.
Firstly I need to create a folder for each of our apps dynamically, which I have done then using a bash script I move into the folder and want to run an initial deliver, in order to set up the folder and collect the metadata, screenshots and deliverFile (which we will then change).
HOWEVER the issue is the first input required by Deliver...
```
'No deliver configuration found in the current directory. Do you want to
setup deliver? (y/n)'
```
I need some way of simply answering 'y' to this from where the bash script calls the program.
After a search I found that you can pipe an input into it by using:
```
echo "y" | deliver ...
```
Which actually works when im copying and pasting the exact same command into the terminal, but as soon as its a bash script calling it, then I receive the usual error of:
```
`crash!': [31m[!] Could not retrieve response as fastlane runs in non-interactive mode
```
Please tell me there is someway of forcing this input requirement to stop, I have also included --force true into the command parameters but this seems to only tame the "are the screenshots ok?" screen....

I suspect that there is an easy parameter I have missed on the net or this functionality simply isn't possible, so I may have been a little bit lacking in my explaination so please let me know if more details are needed...
Thanks in advance...

##### Complete output when running fastlane, including the stack trace and command used

```
outputfromFirstDeliver=$(echo 'y' | deliver --verbose --username 'OUR_LOGIN' --app_identifier 'OUR_APP_IDENT' --force true)
```
... ... ... 
```
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/interface.rb:127:in `crash!': [31m[!] Could not retrieve response as fastlane runs in non-interactive mode[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/implementations/shell.rb:114:in `verify_interactive!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/implementations/shell.rb:92:in `confirm'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/commands_generator.rb:41:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.44.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/commands_generator.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.11.3/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

### Configuration Files

This process doesn't rely on the fastFile or deliverFile as it is just the initial setup.

### Environment

fastlane 1.90.0
deliver 1.11.3

**Comment by KrauseFx** [comment]
Sorry that's currently not supported. You can always call the internal setup classes directly and write your own custom script 👍 

Check out `setup.rb` inside the `deliver` folder for that
