### ISSUE TITLE
Can we get App Analytics Data using Fastlane.

### ISSUE THREAD

**Issue by NikhilRyan** [fastlane/fastlane#4822]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi, this is not an issue, Just a query for a Feature. 
Is it possible to get App Analytics Data Using Fastlane or Spaceship.

**Comment by vpolouchkine** [comment]
Take a look at https://github.com/fastlane/fastlane/issues/3682
