### ISSUE TITLE
Exporting iOS app archive replaces embedded provisioning profile with older version

### ISSUE THREAD

**Issue by triplef** [fastlane/fastlane#4823]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I’m using `match` to manage provisioning profiles and have set up the Xcode project to use the sigh environment variables to select the correct profile. Building the app works fine and looking at the `embedded.mobileprovision` file inside the app in the Xcode archive generated by running `match` + `gym`, I can see that the correct (latest) profile was used. However, when the IPA is exported by gym using `xcodebuild -exportArchive`, the `embedded.mobileprovision` inside the IPA is replaced with another older version of the profile with the same name ("match AdHoc _appid_") that is installed on the system.

I can reproduce this by manually running the archive step on the same xcarchive like this:

```
/usr/bin/xcrun /Library/Ruby/Gems/2.0.0/gems/gym-1.6.3/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist 'path/to/gym_config.plist' -archivePath 'path/to/My App.xcarchive' -exportPath 'path/to/gym_output'
```

I read that with Xcode 7 `exportArchive` should be using the profile from the archive, but that does not seem to be the case here. Since the `provisioning_profile_path` is no longer supported, I don’t see another option to tell `exportArchive` which profile to use.

Deleting the older profile from my system resolves the issue.

This seems to be more of an Xcode issue, but I was hoping for possible pointers on how to best resolve this short of manually deleting the match provisioning profiles from the system before running fastlane. Thanks!
### Environment

Xcode version:
7.3.1

fastlane version (run `fastlane -v`):
1.90.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No.

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by vpolouchkine** [comment]
Looks similar to https://github.com/fastlane/fastlane/issues/4760

**Comment by triplef** [comment]
Regarding #4760, the sigh environment variable _does_ seem to be set correctly, as the build itself is done without issues and the Xcode archive is created with the correct provisioning profile.

As far as I could see from the code, the `xcodebuild -exportArchive` process does not seem to explicitly set the provisioning profile to use via an environment variable or otherwise, and this is where the incorrect (old) provisioning profile is used.

Maybe `match` should always delete other provisioning profiles with the same name before installing the current one?

**Comment by startupthekid** [comment]
Part of the problem though, at least for me, is that even if I deleted all the other profiles on my machine, the one getting installed instead of my ad_hoc provisioning file is one managed by Xcode i.e. a iOS Team Provisioning Profile. And that profile, if I delete it from the account dashboard, continually gets re-generated. 

The only way I've found around this problem so far is to:
1) Use sigh to create the provisioning profile you need
2) CMD + , in Xcode
3) Go to the Accounts tab
4) Remove your account
5) Re-add your account
6) Go to build settings and set the value of the desired configuration to your newly created provisioning profile.

For example I was trying to use an ad hoc one to upload to crashlytics so I had to explicitly set my `Release` configuration to `com.company.App AdHoc. Which I don't like, because it means I'll have to remember to switch it for app store uploads.

**Comment by TKBurner** [comment]
Hi @triplef! Thanks for following up. Can you provide a screenshot of the provisioning profiles section of your build settings. I want to check if that is set correctly. The recent change with provisioning profile path on our end affected a few configs. 👍

**Comment by triplef** [comment]
Thanks @TKBurner, here are the settings:

![untitled-1](https://cloud.githubusercontent.com/assets/6037/15568149/8cc2175a-232a-11e6-86d3-cd6b9d329f52.png)

In this case we were using the "AdHoc_Partner" configuration, which uses a separate Apple Developer account configured to use a separate git branch for match. Please let me know if I can provide any other information that could be helpful.

**Comment by TKBurner** [comment]
Hi @triplef Thanks for following up. What happens if you manually set the provisioning profile here rather than using the Automatic setting? Thanks for working with me on this! If we still don't get you up and running after this step, I'll loop in the core team 👍

**Comment by triplef** [comment]
Hi @TKBurner, I was using the environment variable from match/sigh (see the "AdHoc_Partner" setting in the screenshot) - does that still count as "Automatic"? Also, as I said the correct provisioning profile was in fact used during the build process. Does `xcbuild -exportArchive` (which replaced it with the old profile) also use these settings from the Xcode project (I wouldn’t think so). Thanks again for your help!

**Comment by TKBurner** [comment]
HI @triplef Thanks for following up. xcbuild alone might have some different behavior. Now we query the project settings and use those in gym, which gets passed by us to xcbuild. Thanks!

**Comment by triplef** [comment]
Thanks @TKBurner, let me know if you need any further info from my end. I appreciate the help.

**Comment by triplef** [comment]
I’m still having this issue with the latest fastlane 1.104.0. This is also the same issue as #3896.

Potentially the new Xcode 8 PROVISIONING_PROFILE_SPECIFIER might help I think.

**Comment by TKBurner** [comment]
@triplef You'll need to either manually set your provisioning profile in the build settings or use the PROVISIONING_PROFILE_SPECIFIER. Let me know how it goes!

**Comment by biolinh** [comment]
@TKBurner 
If I not using match, I can parse value for PROVISIONING_PROFILE_SPECIFIER because sigh will download mobileprovision into workspace as below
```
sh "mv '#{ENV["PROJECT_DIR"]}'/*.mobileprovision brandedapp.mobileprovision"
parsed = FastlaneCore::ProvisioningProfile.parse("brandedapp.mobileprovision")
 ProfileSpecifier = parsed["Name"]
```

But, when using match, I dont know how to parse name of mobileprovision
Try it but I cannot get anything.
```
lane :test do
    match(type: "appstore")
    ENV["ProfileSpecifier"] = #{sigh_#{ENV["BUNDLE_IDENTIFIER"]}_appstore_profile-name}
    sh "echo PROVISIONING_PROFILE_SPECIFIER=#{ENV["ProfileSpecifier"]} >> .env"
  end
```
refer: https://github.com/mathiasAichinger/fastlane/commit/70c5b3af3489a3effa4583663d9ea70925ebf310
