### ISSUE TITLE
Revoke old certificates before generating new ones

### ISSUE THREAD

**Issue by bre7** [fastlane/fastlane#4824]
Allow pem to revoke old certificates before generating new ones. Not standalone at the moment, they are revoked before generating new ones.

Flag name: `revoke_old`
PR #4814

Similar to #1754

**Comment by TKBurner** [comment]
@bre7 Hi! Hope you are doing well! I noticed that you don't have any tests on your PR. Can you add test coverage? Thanks! 👍

**Comment by bre7** [comment]
Hi Tk. I must say I'm really new to Ruby 😓 Not sure how to start with tests, any examples on the repo ?

**Comment by TKBurner** [comment]
Hi @bre7. Search for any spec files related to the attributes you added. Let me know how it goes! 👍

**Comment by bre7** [comment]
PR was closes by Krause since the implementation was too destructive. New PR should only revoke expired/about-to expire ? Using the same criteria as force ?

**Comment by doapp-ryanp** [comment]
Any update on this? This is a pretty important missing feature for us

**Comment by nolanwilson** [comment]
While I understand how destructive this can be, I would love to be able to implement this. We often want to renew all of our certificates en mass (even though some of them don't expire for 6+ months). Would love to have a `--force-revoke` option that will renew/revoke old certs even if they are 30+ days out. Perhaps having the two options of `--force` and `--force-revoke` (with the proper warnings / documentation) will serve everyone's purpose while protecting the average user from destroying certificates that he or she needs.

**Comment by bre7** [comment]
Plugins might be the way to go. I'm not sure how to separate the function to a plugin. The code it quite simple since it's already in PEM:
```ruby
def revoke_old_certificates
        UI.important "Revoking existing Push Certificates."

          certificate.all.select { |crt| crt.name == PEM.config[:app_identifier] }.each { |crt| revoke(crt) }
      end
```
