### ISSUE TITLE
OTA html, and manifest files

### ISSUE THREAD

**Issue by kennygunie** [fastlane/fastlane#4828]
### New Issue Checklist
- [X ] Updated fastlane to the latest version

### Question:
I discover fastlane recently, it's there an option to generate html, and manifest files to distribute app by OTA please ?

Big thanks to Fastlane Team for this powerful tool !

### Environment
fastlane version (run `fastlane -v`):
1.90.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Yes

**Comment by KrauseFx** [comment]
Hey @kennygunie, I think you're talking about the `s3` action, right? Run `fastlane action s3` to get more information about this 👍

**Comment by kennygunie** [comment]
Hi @KrauseFx 

Thank you answer about `s3` action 🙏. However I would like generate only the OTA package: html, manifest files, to publish on my own server. I understand that `s3` action will publish on Amazon S3 server, could I use `s3` action (or another action) to generate the package without publishing to S3 ?

**Comment by TKBurner** [comment]
Hi @kennygunie! Thanks for reaching out. Can you let me know what exactly you are trying to export. It sounds like you should be using `supply` 👍

**Comment by kennygunie** [comment]
Hi @TKBurner,

Actually I use this script https://github.com/RichardBronosky/ota-tools with fastlane to generate a package for the OTA distribution:
- 1 html page
- 1 plist file

However, I wonder that are there an action or an option in fastlane to do it natively (without script)?

**Comment by TKBurner** [comment]
Hi @kennygunie Thanks for following up. I don't think we have a good way of doing this right now. But if you check out 'supply' with the skip_upload parameters you might be able to achieve what you are aiming for. However you might be generating more than those two files.

Thanks 👍

**Comment by KrauseFx** [comment]
Hey @kennygunie, sorry, currently the generation of these files is tightly coupled with `s3`, so you'd have to use `s3` right now. However you could adapt the `s3` action to upload the files to your own server instead
