### ISSUE TITLE
renewing pem files

### ISSUE THREAD

**Issue by shoshRose** [fastlane/fastlane#4839]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by shoshRose** [comment]
> If you already have a push certificate enabled, which is active for at least 30 more days, pem will not create a new certificate. 

I had a certificate that would expire in 45 days and renewed it using pem, though it still created a new certificate in the apple developer center. I didn't use the force. 
Shouldn't pem extend the expiration of the existing certificate?

**Comment by TKBurner** [comment]
Hi @shoshRose Thanks for reaching out. Can you share the full output when you run pem? I want to take a look. Thanks 👍

**Comment by shoshRose** [comment]
this is it:
```
pem -u apple@domain.com -a com.domain.app -o /location/to/output/file/app.pem

+------------------+------------------------------------------------------------------+
|                                Summary for PEM 1.3.0                                |
+------------------+------------------------------------------------------------------+
| username         | apple@domain.com                                  |
| app_identifier   | com.catchmedia.paFYE                                             |
| pem_name         | /location/to/output/file/app.pem |
| development      | false                                                            |
| generate_p12     | true                                                             |
| force            | false                                                            |
| save_private_key | true                                                             |
| output_path      | .                                                                |
+------------------+------------------------------------------------------------------+

[10:20:41]: Starting login with user 'apple@domain.com'
[10:20:44]: Successfully logged in
[10:20:46]: Creating a new push certificate for app 'com.catchmedia.app'.
[10:20:49]: Private key: /location/to/output/file/app.pkey
[10:20:49]: p12 certificate: /location/to/output/file/app.p12
[10:20:49]: PEM: /location/to/output/file/app.pem
#######################################################################
# pem 1.3.1 is available. You are on 1.3.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update pem'.
#######################################################################
```

**Comment by TKBurner** [comment]
Hi @shoshRose. Hope you are doing well, what happens if you set generate_p12 to false? Thanks! 👍

**Comment by shoshRose** [comment]
Hello @TKBurner!
I tried your suggestion and got the same result.
I remember this working for me once upon a time so I've been playing around renewing certificates and realized that certificates that expire in 2016 (even with more than 30 days. tested for months: AUG, OCT, DEC) will be renewed (while setting --generate_p12 false)
Whilst certificates that expire in 2017 are not renewed:
```
[17:42:28]: Existing push notification profile 'XXX' is valid for 247 more days.
[17:42:28]: You already have a push certificate, which is active for more than 30 more days. No need to create a new one
[17:42:28]: If you still want to create a new one, use the --force option when running PEM.
```

**Comment by KrauseFx** [comment]
> If you already have a push certificate enabled, which is active for at least 30 more days, pem will not create a new certificate.

That is true, a new push certificate shouldn't be created. Can you reproduce this error? Are you sure you had a certificate on the same Apple account and team, and same type (production, development) that was still valid? You're the first one to report this issue, so I'm curios on what's causing the issue

**Comment by shoshRose** [comment]
I am sure it was the same account team and it was valid. Was able to reproduce many times. This is very weird.

**Comment by TKBurner** [comment]
Hi @shoshRose Thanks for following up. Is this reproducible on a new project for you? Have you run sudo gem update fastlane? If it is reproducible on a new project can you write out repro steps, definitely want to send this out to the team 👍
