### ISSUE TITLE
How to filter gym output

### ISSUE THREAD

**Issue by onmyway133** [fastlane/fastlane#4842]
I'm on fastlane 1.91.0 and gym 1.6.3

gym uses xcpretty to make xcodebuild outputs more readible. But that output is so long and it 's hard to track things.

I can do this in Terminal, but I'd like to do in Fastfile

```ruby
gym -s "MyApp" | grep -A 5 error:
```

That seems like a Ruby thing, is that possible? Is there better way to filter `gym` output? Thanks

**Comment by onmyway133** [comment]
It seems I can deal with $stdout for now http://stackoverflow.com/questions/14987362/how-can-i-capture-stdout-to-a-string

**Comment by TKBurner** [comment]
@onmyway133 Thanks for reaching out. This is definitely possible in Ruby, so it's not handled by Fastlane directly. I'm glad you found a solution. Hope you have a wonderful week! 👍
