### ISSUE TITLE
How do I specify Content Rating, Application Type, Category using 'Supply'?

### ISSUE THREAD

**Issue by LovesBruins** [fastlane/fastlane#4845]
### New Issue Checklist
I am using 'supply' for Android.  How can I specify the Content Rating, Application Type and Category that is required to upload a NEW application to the play store?

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
@LovesBruins Thanks for reaching out. Did you follow the steps on this page to get initialized? https://github.com/fastlane/fastlane/tree/master/supply

Thanks!

**Comment by LovesBruins** [comment]
Hi Todd,
Yes I did follow the steps.  Coincidentally I did not see the FeatureGraphic downloaded.  Even in the instructions there is no way to specify these parameters.

**Comment by TKBurner** [comment]
Thanks @LovesBruins! Can you show me the contents of your Fastlane dir? I want to make sure that is setup right 👍 Do you have a metadata path set?

**Comment by asfalcone** [comment]
It is not possible to upload a NEW application the Play Store with `supply` (Google does not expose that ability via API). You can only make updates to an existing one. 👍

**Comment by LovesBruins** [comment]
Hi Andrea,
Thank you so much for this information.  I was leaning toward that answer
anyway.
/Loren

On Thu, Jun 2, 2016 at 4:11 PM, Andrea Falcone <notifications@github.com>
wrote:

> It is not possible to upload a NEW application the Play Store with supply
> (Google does not expose that ability via API). You can only make updates to
> an existing one. 👍
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/fastlane/fastlane/issues/4845#issuecomment-223407321>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AQR8KfSevW3DoZsoZs5ATxdPc34PiFKvks5qHzjggaJpZM4ImqO5>
> .
>



-- 
*Loren Rogers *| Android Developer

Retrieve Technologies
100 Commercial Street | Manchester, NH 03101

*Twitter <https://twitter.com/retrievetech> | Facebook
<https://www.facebook.com/retrievetech/?fref=ts> | LinkedIn
<https://www.linkedin.com/company/retrieve-technology> | Website
<http://www.retrieve.com/> *

**Comment by asfalcone** [comment]
Going to close this issue for now. 🌷
