### ISSUE TITLE
Missing rest-client dependency

### ISSUE THREAD

**Issue by nevir** [fastlane/fastlane#4848]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The `upload_symbols_to_sentry` action [depends on `rest-client`](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/upload_symbols_to_sentry.rb#L5), which `fastlane` doesn't have a runtime dependency for.  It could use one!

**Comment by TKBurner** [comment]
@nevir Thanks for letting us know. I've reached out to the core team about this. Hope that you have a wonderful day! 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/pull/4871 👍

**Comment by KrauseFx** [comment]
Thanks for letting us know @nevir 👍

**Comment by chintan1891** [comment]
@KrauseFx  Can't we add 'rest-client' as normal dependency instead of development dependency in this file "https://github.com/fastlane/fastlane/blob/master/fastlane/fastlane.gemspec". So rest-client will be install automatically with Fastlane..
