### ISSUE TITLE
Is it possible to use Fastlane to pull Xcode project from git/folder?

### ISSUE THREAD

**Issue by trustyfrog** [fastlane/fastlane#4854]
Sorry, not sure how to label as a question.

What I'd like to do is use fastlane to pull down an Xcode project that I can then run fastlane init on. Is there a hook to do this, because `fastlane init` expects a project to be there all ready.

**Comment by TKBurner** [comment]
Hi @trustyfrog Thanks for reaching out. You can use the shell commands action 'sh'. However, I believe you'll need to run produce and deliver rather than running Fastlane init. Thanks!

**Comment by KrauseFx** [comment]
Yeah, or you can have your own shell script that does a `git clone` and then `fastlane init`
