### ISSUE TITLE
Add static analysis step to scan

### ISSUE THREAD

**Issue by klundberg** [fastlane/fastlane#4856]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

More of a feature request. In our current test builds in CI that do not use fastlane, we both run unit tests and static analysis to get clang analyzer warnings. If it isn't too much for the scan tool to handle, I'd love for it to have an analyze option to also run static analysis in one command.

The only major thing I can think of in favor of not doing this in scan is that typically the analyze build action builds code in release mode, while unit testing happens in debug mode, therefore this would have to rebuild the same code twice in each configuration. However, I'm unaware of any other fastlane tool that does this build action, and optionally running this in scan seems like the right place to do this to me.
### Environment

fastlane version (run `fastlane -v`):
1.91.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by andybest** [comment]
I know it's not exactly what you wanted, but the OCLint action can run the static analyzer and include the results as part of its report

**Comment by TKBurner** [comment]
Hi @andybest! Thanks for reaching out with this idea. I'm marking it as help wanted in case anyone in the community wants to take a crack at it. This probably makes more sense in our new plugin system.

Thanks 👍

**Comment by klundberg** [comment]
I've done a bit more digging, and this is possible using xcargs:

Command line: `scan -x "analyze"`
Fastfile: `scan(xcargs: "analyze")`

this will properly add `analyze` onto the `build` and `test` xcodebuild actions. It might be nice to have this as a first class option though.

**Comment by TKBurner** [comment]
@klundberg Thanks for letting me know! Any chance you are interested in submitting a PR? We'd love to work with you on this. Thanks!

**Comment by klundberg** [comment]
I might be able to work on this over the next week or two, but I can't make any guarantees. I'll try, but someone else who's interested can certainly try and will probably beat me :)

**Comment by TKBurner** [comment]
Hi @klundberg Thanks for letting me know. The help wanted flag should let people know that they can contribute. Follow up on this thread if you start working on something! Thanks!

**Comment by Stoff81** [comment]
@TKBurner Ive been spending the week implementing fast lane here at Touch Surgery. Noticed your posts come up often. Must say I'm really impressed with the tool. Ive tried to implement my own version a few months ago, this certainly makes it easier. 

I have a question regarding PRs and deving new features... Is there somewhere which shows how to setup an environment with a local version of fast lane so that I can edit the code and create a PR. I would love to improve OCLint so that it picks up the commands.json automatically from the scan results. PM if you like...

**Comment by TKBurner** [comment]
Hi @Stoff81 Thanks for following up on this. You can check out the guide here, https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md and if you are interested in doing new work integrated into Fastlane, check out our plugin system, https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins.

Let me know if you have any questions, I'd love to help 👍

**Comment by rompic** [comment]
would also love to see this to run scan without "test" in order to analyze using oclint on a legacy project without tests
