### ISSUE TITLE
update_fastlane step fails while fastlane installed with --user-install parameter

### ISSUE THREAD

**Issue by vdugnist** [fastlane/fastlane#4858]
### New Issue Checklist

- [✗ ] Updated fastlane to the latest version
- [✓ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
`update_fastlane` step is not working due to file permission error. But `gem update fastlane` works fine. My solution for non-sudo gems is installing gems in user directory. 

> cat ~/.gemrc
> \> gem: --user-install -n~/bin --no-document

### Environment

fastlane version (run `fastlane -v`): 1.89.0

> Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No.

> Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No.

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by vdugnist** [comment]
I've [changed](https://github.com/vdugnist/fastlane/commit/a4ccdb85275fa19edce3d11ddb44678679bbb2c6) sudo condition, but now I get gem updater [error](http://pastebin.com/cUsbMkAt).

**Comment by ohwutup** [comment]
Hey @vdugnist! Thanks for submitting the issue, and that you are running into this issue. As of now I am going to close this as "won't fix" as installing with `gem install -n` is on the more power-user end of use cases and would add a decent amount of complexity to the install/update process to add functionality for persist the method by which the gem was initially installed. You can definitely run `gem update fastlane -n~/bin --no-document` if you would like to keep the binstub in the ~/bin directory. 🐙 🚀
