### ISSUE TITLE
Jenkins cannot find FastLane

### ISSUE THREAD

**Issue by sasal** [fastlane/fastlane#4864]
Steps:

sudo gem install fastlane --verbose ...
After Successfully installing fastlane cd MyAppFolder/
fastlane init (works and set up custom lane)
fastlane CustomLane (Works fine locally)
git commit -a -m "pushing to git"
In Jenkins, added build step as execute shell script "fastlane CustomLane"
Build now

Error:

 fastlane CustomLane
[33mCould not find fastlane in current directory. Would you like to set it up?[0m
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.44.2/lib/fastlane_core/ui/interface.rb:127:in `crash!':[31m[!] Could not retrieve response as fastlane runs in non-interactive mode[0m (FastlaneCore::Interface::FastlaneCrash)

**Comment by madhu-b** [comment]
running same issues? any solution?

**Comment by TKBurner** [comment]
@madhu-b Can you please submit a new issue? I'd love to help 👍
