### ISSUE TITLE
Can you set a signing certificate and a provisioning profile in gym?

### ISSUE THREAD

**Issue by dakamojo** [fastlane/fastlane#4865]
Fastlane and all the actions bring a lot of power and flexibility.  I'm trying to migrate an existing build process to fastlane step by step.  I already have the correct certificates and profiles loaded on the machine in the normal places.  I want to avoid any actions that auto-generate new certificates or profiles.  I don't want to use match yet either.  I understand that process and it makes sense, but I need to make changes incrementally.

My existing build looks like this

#enterprise
xcodebuild with enterprise provisioning profile and enterprise signing identity
xcrun to package with enterprise provisioning profile and enterprise signing identity 

#adhoc and release
xcodebuild with release provisioning profile and release signing identity
xcrun to package with adhoc provisioning profile and release signing identity
xcrun to package with release provisioning profile and release signing identity

I think this should be two lanes.  Many examples simply show using sigh followed by gym.  I understand that sign works by generating and downloading the profiles as needed, rather than using the existing ones on the machine.  So I don't think I want to use sigh initially.

Can gym be told exactly which profile and signing identity to use?

**Comment by vpolouchkine** [comment]
Sure, you can use the `--codesigning_identity` and `--provisioning_profile_path` arguments. You can also run `gym help` to get the full list of available arguments.

**Comment by KrauseFx** [comment]
Actually the `--codesigning_identity` and `--provisioning_profile_path` are both deprecated since Xcode 7, as this doesn't work with multiple targets. 

Check out the documentation on how to setup your Xcode project to pass the provisioning profile and the code signing identity using environment variables: https://github.com/fastlane/fastlane/blob/master/match/README.md#setup-xcode-project

**Comment by dakamojo** [comment]
This helps a little.

$(sigh_<bundle_identifier>_<profile_type>)

What are the possible options for profile_type?  The example shows app_development as one.  Are the other two options app_release and app_enterprise?  And instead of saying the profile type is there a way to specify exactly which profile.  We have multiple enterprise profiles and some of our bundle ids will match with multiple ones.

**Comment by TKBurner** [comment]
Hi @dakamojo Thanks for following up. The only way to set this now is via the build settings of your app. Can you share the code signing and provisioning profile sections of your build settings? Thanks 👍

**Comment by dakamojo** [comment]
At my company the dev team is isolated from the deployment team for compliance reasons.  The dev team writes the code and the deployment team signs and deploys the app.  For this reason the code is simply configured to create debug builds.  On the other side of the fence the deployment team has a build script that builds, signs, and packages the app.

This is the build script.

`security unlock-keychain -p "*****" ~/Library/Keychains/login.keychain
security find-identity -p codesigning

BUILD_WORKSPACE="MobuyleUniversal.xcworkspace"
BUILD_SCHEME="MobuyleRetail"

echo BUILD_WORKSPACE=$BUILD_WORKSPACE
echo BUILD_SCHEME=$BUILD_SCHEME

RELEASE_SIGNING_IDENTITY="iPhone Distribution: Heartland Payment Systems, Inc. (GY7QL9RND6)"
ENTERPRISE_SIGNING_IDENTITY="iPhone Distribution: Heartland Payment Systems, inc"

RELEASE_PROVISIONING_GUID="5725b514-312a-4861-88d5-8896dba9a9c2"
ADHOC_PROVISIONING_GUID="c73a164e-4e84-4038-a804-6597d4b0c30d"
ENTERPRISE_PROVISIONING_GUID="a3ab7205-150a-435a-b43b-3f7031a155f8"

RELEASE_PROVISIONING_PROFILE="${HOME}/Library/MobileDevice/Provisioning Profiles/${RELEASE_PROVISIONING_GUID}.mobileprovision"
ADHOC_PROVISIONING_PROFILE="${HOME}/Library/MobileDevice/Provisioning Profiles/${ADHOC_PROVISIONING_GUID}.mobileprovision"
ENTERPRISE_PROVISIONING_PROFILE="${HOME}/Library/MobileDevice/Provisioning Profiles/${ENTERPRISE_PROVISIONING_GUID}.mobileprovision"

SRCROOT="${WORKSPACE}/mobuyle"

/usr/bin/agvtool new-version -all ${BUILD_NUMBER}

#get app version
APP_VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" MobuyleUniversal/${BUILD_SCHEME}-Info.plist)
echo APP_VERSION=$APP_VERSION

#build the adhoc and release build
xcodebuild -workspace ${BUILD_WORKSPACE} -scheme ${BUILD_SCHEME} -sdk iphoneos -configuration Release -derivedDataPath . clean build PROVISIONING_PROFILE="${RELEASE_PROVISIONING_GUID}" CODE_SIGN_IDENTITY="${RELEASE_SIGNING_IDENTITY}"

#compress the DSYM file
/usr/bin/zip -q -r "${WORKSPACE}/artifacts/${BUILD_SCHEME}-${APP_VERSION}-${BUILD_NUMBER}-dSYM.zip" "${WORKSPACE}/mobuyle/build/Products/Release-iphoneos/${BUILD_SCHEME}.app.dSYM"

#package the adhoc build
xcrun -sdk iphoneos PackageApplication -v "${WORKSPACE}/mobuyle/build/Products/Release-iphoneos/${BUILD_SCHEME}.app" -o "${WORKSPACE}/artifacts/${BUILD_SCHEME}-adhoc-${APP_VERSION}-${BUILD_NUMBER}.ipa" --sign "$RELEASE_SIGNING_IDENTITY" --embed "$ADHOC_PROVISIONING_PROFILE"

#package the release build
xcrun -sdk iphoneos PackageApplication -v "${WORKSPACE}/mobuyle/build/Products/Release-iphoneos/${BUILD_SCHEME}.app" -o "${WORKSPACE}/artifacts/${BUILD_SCHEME}-release-${APP_VERSION}-${BUILD_NUMBER}.ipa" --sign "$RELEASE_SIGNING_IDENTITY" --embed "$RELEASE_PROVISIONING_PROFILE"

#build the enterprise build
xcodebuild -workspace ${BUILD_WORKSPACE} -scheme ${BUILD_SCHEME} -sdk iphoneos -configuration Release -derivedDataPath . clean build PROVISIONING_PROFILE="${ENTERPRISE_PROVISIONING_GUID}" CODE_SIGN_IDENTITY="${ENTERPRISE_SIGNING_IDENTITY}"

#package the enterprise build
xcrun -sdk iphoneos PackageApplication -v "${WORKSPACE}/mobuyle/build/Products/Release-iphoneos/${BUILD_SCHEME}.app" -o "${WORKSPACE}/artifacts/${BUILD_SCHEME}-enterprise-${APP_VERSION}-${BUILD_NUMBER}.ipa" --sign "$ENTERPRISE_SIGNING_IDENTITY" --embed "$ENTERPRISE_PROVISIONING_PROFILE"
`

**Comment by TKBurner** [comment]
Hi @dakamojo! Thanks for following up. Because we now inherit from Xcode you'll need to go to the code signing section and provisioning profile section in your build settings. From there you can manually set by build type. If you still run into issues can you send me a screenshot of this section? Thanks!

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
