### ISSUE TITLE
Match fails to import certificates when using a fully-qualified path to the keychain

### ISSUE THREAD

**Issue by lyricsboy** [fastlane/fastlane#4866]
### Issue Description

In `match/lib/match/utils.rb` there's a hard-coded path to `~/Library/Keychains` prepended to the keychain "name".

https://github.com/fastlane/fastlane/blob/5dff30df8712b1120ff992446804178deedab922/match/lib/match/utils.rb#L4

When using a fully-specified path to the keychain, for example using Jenkins' "Keychains and Provisioning Profiles" plugin, the path ends up getting augmented incorrectly. A sanitized example from my project:

```
security import /var/folders/t4/99vplf817qs40m8tz1tkkj500000gn/T/d20160526-57929-19soscm/certs/distribution/xxxx.cer -k ~/Library/Keychains//Users/user/.jenkins-slave/workspace/iOS\ Parameterized\ Build/jenkins_match.keychain -T /usr/bin/codesign -T /usr/bin/security&> /dev/null
```

FastlaneCore::CertChecker can handle this situation correctly, so perhaps some similar techniques can be applied to the match implementation to fix this.

It would also be nice to avoid sending output from the import process to `/dev/null`, at least when running in verbose mode. That would make the failure easier to see.

Possibly related to #4826

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by ffittschen** [comment]
@vpolouchkine Any news on this?

**Comment by vpolouchkine** [comment]
@ffittschen I'm afraid not.

**Comment by mfurtak** [comment]
If folks have a minute to try the solution in #5549, that would be a big help!

**Comment by mfurtak** [comment]
@ffittschen I've merged a likely solution to master if you have a moment to give it a try 👍

**Comment by ffittschen** [comment]
@mfurtak Great! I'll try it as soon as I can

**Comment by mfurtak** [comment]
Hi all, [`match` 0.6.2](https://github.com/fastlane/fastlane/releases/tag/match/0.6.2) 🔥 has been released, which includes the recent improvements to address this.

I'll close this issue for now, but please let me know how it looks! 👍

**Comment by lyricsboy** [comment]
Thanks! I may decide to use match again in the CI context where this popped up and I'll let you know how it works.

**Comment by ffittschen** [comment]
@mfurtak I just had time to try `match 0.6.2`:

`keychain_name "~/Dev/MatchTest/CI.keychain"` does not work. It results in the following error:
```
[!] Could not locate the provided keychain. Tried:
	/Users/ffittschen/Library/Keychains/~/Dev/MatchTest/CI.keychain
	~/Dev/MatchTest/CI.keychain
```

But `keychain_name "/Users/ffittschen/Dev/MatchTest/CI.keychain"` does work. Thanks for the fix 👍🏻

**Comment by mfurtak** [comment]
@ffittschen Thanks for giving it a try, and pointing out that lingering weakness! I'll get a fix for that as well.
