### ISSUE TITLE
Features for fastlane pilot

### ISSUE THREAD

**Issue by nirvanagit** [fastlane/fastlane#4867]
### Issue Description
I want to automate testflight using fastlane.

The process I've worked on so far is just this:

1) Upload to testflight using pilot.
2) Manually add users as internal testers
3) Select version to Test for internal tests.

Can processes 2 and 3 not be automated using pilot? If they exist I am not able to find examples. 

Please provide if those are possible.

FYI: I used 
```
fastlane pilot add user_email -a app_identifier
```
It returns a non informative message: 

```
{"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"}
```

I have no users as internal testers but when I do:
```
fastlane pilot list -a app_identifier
```
I get the list of all the users from our team. Is there an API which only gives me internal/external users?

**Comment by nirvanagit** [comment]
When I try to remove a user I get similar response
```
pilot remove 'useremail' -a 'app_id'
[15:58:04]: Login to iTunes Connect (useremail)
[15:58:07]: Login successful
[15:58:07]: [useremail]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}

[!] Some operations failed: ["useremail"]
```

**Comment by nirvanagit** [comment]
I went through pilot code, and it seems that we cannot add internal developers at all right now.

Please correct me if I am wrong.

**Comment by nirvanagit** [comment]
```
tester = Spaceship::Tunes::Tester::Internal.find('useremail')
Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Forbidden"], "info"=>nil}, "statusCode"=>"ERROR"}
```

**Comment by vpolouchkine** [comment]
You can use the `--distribute_external` argument to specify if the build should be distributed to internal or external testers. You can run `pilot help` to get the full list of available arguments.

**Comment by nirvanagit** [comment]
@vpolouchkine : Thanks for the response. 
I used what you said and got this:

```
[15:14:18]: Could not create tester useremail
[15:14:18]: [useremail]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}
```

**Comment by nirvanagit** [comment]
And can I not select the version to test for internal testing?

**Comment by nirvanagit** [comment]
I saw this issue: https://github.com/fastlane-old/deliver/issues/137

My intention was to make testflight internal use the latest version I uploaded via ```pilot upload```

When I ran 
```
deliver --ipa app.ipa --skip_binary_upload
```

It said uploaded but did not mark this build for Internal testing. Am I doing anything wrong?

**Comment by vpolouchkine** [comment]
Re https://github.com/fastlane/fastlane/issues/4867#issuecomment-222264827

That does not look like an error that you would get if you just passed `--distribute_external`. How are you calling `pilot`?

**Comment by nirvanagit** [comment]
@vpolouchkine : I am using

```
fastlane pilot add 'useremail' -a 'appId'
```
also used
```
pilot add 'useremail' -a 'appId'
```

And it happens irrespective of --distribute_external

**Comment by vpolouchkine** [comment]
What's the role of the user that you're using?

**Comment by nirvanagit** [comment]
@vpolouchkine : I figured out that I am not able to add internal users form fastlane pilot cli.  But I am able to do it via itunesconnect ui. I confirmed with a colleague, he is able to add internal users (he has different permissions)

**Comment by vpolouchkine** [comment]
Gotcha. Yeah, this is a known limitation. Thanks for confirming.

**Comment by TKBurner** [comment]
Hi @nirvanagit Thanks for following up. Can you let us know what role you have in iTunes connect. Pilot works with iTC accounts with admin privileges.
