### ISSUE TITLE
Problem running fastlane from crontab

### ISSUE THREAD

**Issue by rrecio** [fastlane/fastlane#488]
It works fine in Terminal, but when running in crontab I get this:

![screen shot 2015-08-08 at 4 49 12 pm](https://cloud.githubusercontent.com/assets/52694/9151975/8dd7407a-3ded-11e5-830f-57954e34b0e1.png)

**Comment by KrauseFx** [comment]
Your shell environment is not correctly configured
Instead of UTF-8 your shell uses US-ASCII
Please add the following to your '~/.bashrc':
```
       export LANG=en_US.UTF-8
       export LANGUAGE=en_US.UTF-8
       export LC_ALL=en_US.UTF-8
```
You'll have to restart your shell session after updating the file.
If you are using zshell or another shell, make sure to edit the correct bash file.
For more information visit this stackoverflow answer:
http://stackoverflow.com/a/17031697/445598

**Comment by rrecio** [comment]
This helped with the encoding problem, also had to run `rvm cron setup` so `update_fastlane` and `cocoapods` actions could run without ruby environment problems. 

I'm still stuck on this code signing error:

![screen shot 2015-08-11 at 4 21 31 pm](https://cloud.githubusercontent.com/assets/52694/9207727/b68332ea-4045-11e5-9f27-784c9580cfbd.png)

**Comment by rrecio** [comment]
I'm stuck in sigh asking for Password:
Even though I have added `DELIVER_USER` and `DELIVER_PASSWORD` to crontab environment

**Comment by rrecio** [comment]
Unlocking keychain using `security unlock-keychain -p password ~/Library/Keychains/login.keychain` seems to resolve sigh asking for password.

**Comment by rrecio** [comment]
Even though I'm still stuck on the error in the screenshots below. It may be related to the environment because it runs fine in my user shell. 

![screen shot 2015-08-11 at 5 39 13 pm](https://cloud.githubusercontent.com/assets/52694/9210081/908b021a-4050-11e5-9b57-b346c969494a.png)

**Comment by rrecio** [comment]
The only workaround I figured is to don't execute sigh in the lane that runs on crontab.

**Comment by KrauseFx** [comment]
Please share the output below the `fastlane finished with errors`

**Comment by JaviSoto** [comment]
Hi @rrecio! Did you get a chance to look into this? Thanks!

**Comment by rrecio** [comment]
@javisoto in the end I just gave up trying to use crontab, sorry

**Comment by KrauseFx** [comment]
Okay, we'll close the issue then :+1:
