### ISSUE TITLE
--decimals flag type must be Fixnum not String

### ISSUE THREAD

**Issue by bootstraponline** [fastlane/fastlane#4881]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The decimals type is incorrect.

> 'decimals' value must be a String! Found Fixnum instead.

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane test
[11:01:20]: 'decimals' value must be a String! Found Fixnum instead.
```

**Comment by KrauseFx** [comment]
Awesome 👍
