### ISSUE TITLE
ipa file not uploaded once I use crashlytics action in fastlane 

### ISSUE THREAD

**Issue by FaisalCs** [fastlane/fastlane#4885]
### Issue Description

I use crashlytics action to upload beta build for my app. it seems to be ipa file not uploaded and the terminal message show successful  message. I got new build in beta app but there is no build uploaded 😔 . if I uploaded the app from the fabric app on mac it works. Should I use fastlane with Fabric App on Mac or should I use only fastlane ? 

Thanks a lot and I appreciate your time and help 

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE

[19:03:30]: Successfully exported and compressed dSYM file
[19:03:30]: Successfully exported and signed the ipa file:
[19:03:30]: /Users/Faisal/Development/exampletest/fastlane/crashlytics/App.ipa
[19:03:30]: -------------------------
[19:03:30]: --- Step: crashlytics ---
[19:03:30]: -------------------------
[19:03:30]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[19:03:30]: Build successfully uploaded to Crashlytics Beta 🌷

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 2           |
| 4    | update_info_plist                   | 0           |
| 5    | increment_build_number              | 1           |
| 6    | cert                                | 14          |
| 7    | sigh                                | 13          |
| 8    | gym                                 | 30          |
| 9    | crashlytics                         | 0           |
+------+-------------------------------------+-------------+

[19:03:30]: fastlane.tools finished successfully 🎉
```
### Configuration Files
```
Fastfile:
  desc "Submit a new Beta Build to crashlytics"
  lane :beta do
    cocoapods
    increment_build_number
    cert
    sigh
    gym(scheme: "Example")
    crashlytics(
      crashlytics_path: './Pods/Crashlytics/Crashlytics.framework',
      api_token: "api_token",
      build_secret: "build_secret",
      groups: ['ios-tester']
    )

  end
```
### Environment
```
fastlane version (run `fastlane -v`):
fastlane 1.90.0
```

**Comment by vpolouchkine** [comment]
Are you able to upload using the Crashlytics binary directly? https://docs.fabric.io/ios/beta/build-tools.html

**Comment by jcampbell05** [comment]
I noticed that this was due to a shim in the latest version of crashlytics which breaks when used with Fastlane due to its use of `PODS_ROOT` I had to manually pass in the new path to the submit executable for it to work. 

We should update the action for the new path and also communicate to the Fabric team that the shim doesn't work.

**Comment by TKBurner** [comment]
@jcampbell05 Thanks for looking into this! I'm going to notify both Fastlane and Beta teams 👍

**Comment by cepages** [comment]
+1

Is this fixed, I have exactly the same problem:

```
        crashlytics(
           crashlytics_path: './Pods/Crashlytics/Crashlytics.framework',
           api_token: crashlyticsAPIKEY,
           build_secret: crashlyticsSecret,
           ipa_path: "#{Actions.lane_context[SharedValues::IPA_OUTPUT_PATH]}",
           notes: "New build Global",
           emails: "miEmail@email.com"
          )
```

I tried using:

`crashlytics_path: './Pods/Crashlytics/Crashlytics.framework/submit'` but it doesn't work and it seems to be related with the old problem: https://github.com/fastlane/fastlane/issues/877

**Comment by TKBurner** [comment]
Hi @cepages Thanks for following up on this. Can you let me know if it persists after you run `sudo gem update fastlane`? Thanks!

**Comment by cepages** [comment]
Yeah, I already had my fastlane updated :)

**Comment by TKBurner** [comment]
@cepages Thanks for following up. Do you get the success message like above, or do you get a failure message? Is the app appearing the Beta dashboard? Thanks so much for working with me on this 👍

**Comment by cepages** [comment]
Yeah, I just updated fastlane again and run my lane:

```
[09:58:51]: -------------------------
[09:58:51]: --- Step: crashlytics ---
[09:58:51]: -------------------------
[09:58:51]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[09:58:51]: Build successfully uploaded to Crashlytics Beta 🌷`
```

But in fabric, It's in the archive list but not in the active list. It used to work time ago :_(

Thanks

**Comment by jakubprusa** [comment]
Same state as @cepages right now on latest version.

**Comment by polok** [comment]
I have exactly the same problem which @cepages and @jakubprusa 
Fastlane version: 1.97.2

I also checked groups/emails param as I saw in some other thread that sometimes changing groups to emails did a trick. Unfortunately, not for me.

**Comment by bimawa** [comment]
Guys i have same trouble. And i found in Crashlytics folder two different binary for submit apps.
1. in path: `./Pods/Crashlytics/Crashlytics.framework/submit`
2. in path: `./Pods/Crashlytics/submit` 

after this i change my FastlaneFile from

```Ruby
crashlytics_path: "./Pods/Crashlytics/Crashlytics.framework",
```
 to

```ruby
crashlytics(crashlytics_path: "./Pods/Crashlytics",
                notes_path: "./fastlane/metadata/ru/release_notes.txt",
                groups: ['betatesters'],           
                notifications: true)
```

and now builds successfully uploading on fabric.

**Comment by cepages** [comment]
@bimawa it's working for me too. Thanks!!!

**Comment by TKBurner** [comment]
@bimawa Thanks for sharing your workaround! Really glad to hear you are up and running. 👍

**Comment by bimawa** [comment]
Not at all guys ;) we are all in one boat!
