### ISSUE TITLE
[Information] Command Line username and password for Apple  Developer

### ISSUE THREAD

**Issue by mirkos93** [fastlane/fastlane#4887]
Hello,
mainly I want to congratulate you on the work done so far, you have created a powerful and simple tool at the same time, a magnificent project.
I have a question: I saw that among the various tools in fastlane I can select my email address for access to Apple Developer via command line; I now have an Apple Developer Access database (for my customers) and I would use it to compile applications using the fastlane tools, without having to add them one by one by hand, but by placing them through the command line.

I can already do this? If yes, how?

Thanks so much,
Mirko

**Comment by mirkos93** [comment]
Ok, i've see this:
https://github.com/fastlane/fastlane/tree/master/credentials_manager
And this is right for me

Thanks!
Mirko

**Comment by KrauseFx** [comment]
Yeah 🚀
