### ISSUE TITLE
New actions to get/set version number directly from/to Info.plist

### ISSUE THREAD

**Issue by SiarheiFedartsou** [fastlane/fastlane#4895]
Hi! Currently fastlane has a very useful actions like `get_current_version` and `increment_current_version`. But they use `agvtool` under the hood. `agvtool` has a lot of restrictions. For example it is difficult to match target and its version using `agvtool` or you cannot set new version for single target - `agvtool` will update all targets with the same version. At my current working project I periodically see very strange things: right after pbxproj merge `agvtool what-marketing-version -terse` becomes to return nothing. Then after some very strange manipulations it starts return correct results:
1. Add "./" before Info.plist path build setting in main target
2. Remove "./" before Info.plist path build setting in main target

It was the last straw, so I've decided to write new actions to get/set version number directly from/to Info.plist: `get_version_number_from_plist`/`increment_version_number_in_plist`. Also I've added `get_info_plist_path` action, which returns a path to Info.plist of specific target in project. 

P.S. I don't think that `get_version_number_from_plist` and `increment_version_number_in_plist` are very good names for such actions, but I cannot come up with something more suitable.

**Comment by TKBurner** [comment]
Hi @SiarheiFedartsou Thanks for working with us. We have created a new plugin system. I was wondering if you could reapproach this PR as a plugin rather than an action? Thanks!

**Comment by SiarheiFedartsou** [comment]
Hi @TKBurner ! Okay, and where can get an information about writing plugins for fastlane?

**Comment by jinjorge** [comment]
@SiarheiFedartsou you can find the plugins info here - https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md

**Comment by TKBurner** [comment]
@jinjorge Thanks for stepping in! 👍
