### ISSUE TITLE
Feature: Xcode Plugin

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#49]
Trigger fastlane right inside Xcode and show the output in Xcode.

**Comment by jcampbell05** [comment]
@KrauseFx my only concern is that for some tools which fastlance may run such as CocoaPods its not a good idea to have Xcode open as it modifies the project/workspace which can cause instability (I've had one case where it got corrupted as xcode was trying to write to the project at the same time as it detected changes)

**Comment by KrauseFx** [comment]
Good point, I didn't even think about this.

**Comment by vpolouchkine** [comment]
There is now a 3rd-party plugin for this: https://github.com/RishabhTayal/Fastlane-Plugin

**Comment by KrauseFx** [comment]
This is not possible due to the Xcode 8 limitations unfortunately
