### ISSUE TITLE
Help: Sigh is creating new profiles instead of renewing them.

### ISSUE THREAD

**Issue by amuzzy** [fastlane/fastlane#4909]
### New Issue Checklist

- [ yes] Updated Sigh to the latest version
- [ yes] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Thanks for creating Sigh.  It's awesome.

Sigh is creating new profiles instead of renewing them.  All I want is for Sigh to refresh my development provisioning profile, adding all available developer certs and devices.  Instead, Sigh is creating a new profile, and the existing profile is not renewed.

The BundleID already has a development provisioning profile created, with a name of "Friendly Name Development.mobileprovision".  Sigh creates a second profile with the name "Development_bundleid.mobileprovision".  The profile does have all available developer certs and devices.

Is there a way to force Sigh to renew the profile instead of creating one?

##### Complete output when running fastlane, including the stack trace and command used

Command Used: sigh renew -a com.company.app -o "~/Documents/Profiles/" -u me@company.com -b ABCDE12345 --development --skip_install --skip_certificate_verification --force  --skip_fetch_profiles

```
+-------------------------------------+-----------------------------------------+
|                            Summary for sigh 1.8.0                             |
+-------------------------------------+-----------------------------------------+
| app_identifier                      | com.company.app                         |
| username                            | me@company.com                          |
| team_id                             | ABCDE12345                              |
| development                         | true                                    |
| skip_install                        | true                                    |
| skip_certificate_verification       | true                                    |
| force                               | true                                    |
| skip_fetch_profiles                 | true                                    |
| adhoc                               | false                                   |
| ignore_profiles_with_different_name | false                                   |
+-------------------------------------+-----------------------------------------+

[17:52:08]: Starting login with user 'me@company.com'
[17:52:10]: Successfully logged in
[17:52:10]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[17:52:11]: Creating new provisioning profile for 'com.company.app' with name 'com.company.app Development'
[17:52:12]: Downloading provisioning profile...
[17:52:13]: Successfully downloaded provisioning profile...
/Users/Me/Documents/Profiles/Development_com.company.app.mobileprovision```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```
N/A
```

### Environment

fastlane version (run `fastlane -v`): Sigh 1.8.0, Fastlane is not installed.

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
Hi @amuzzy Thanks for reaching out about this. Can you try setting force to false? Thanks! 👍

**Comment by amuzzy** [comment]
Hello @TKBurner and thank you for your time.  Removing the --force flag did not fix the issue.

$ sigh renew -a com.company.app -o "~/Documents/Profiles/" -u me@company.com -b ABCDE12345 --development --skip_install --skip_certificate_verification --skip_fetch_profiles

+-------------------------------------+---------------------------------------+
|                           Summary for sigh 1.8.0                            |
+-------------------------------------+---------------------------------------+
| app_identifier                      | com.company.app                       |
| username                            | me@company.com                        |
| team_id                             | ABCDE12345                            |
| development                         | true                                  |
| skip_install                        | true                                  |
| skip_certificate_verification       | true                                  |
| skip_fetch_profiles                 | true                                  |
| adhoc                               | false                                 |
| force                               | false                                 |
| ignore_profiles_with_different_name | false                                 |
+-------------------------------------+---------------------------------------+

[11:43:14]: Starting login with user 'me@company.com'
[11:43:16]: Successfully logged in
[11:43:16]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[11:43:17]: Creating new provisioning profile for 'com.company.app' with name 'com.company.app Development'
[11:43:19]: Downloading provisioning profile...
[11:43:19]: Successfully downloaded provisioning profile...
/Users/me/Documents/Profiles/Development_com.company.app.mobileprovision

**Comment by asfalcone** [comment]
@amuzzy You're going to want `force` to be true. That is what controls renewing vs creating a new one. 

I'm looking at [the code](https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/runner.rb#L22) and the output from your first run. It seems like there are no matching profiles locally. You can do `sigh manage` to see the profiles you have locally.

Can you try changing `skip_fetch_profiles` to **false** so that you will have the profile locally (and put `force` back to false) and let me know what the result (with output) is? Thanks!

**Comment by amuzzy** [comment]
Hello asfalcone, and thank you for taking a look at this.  I agree that I will want force to be true.  My team has thousands of profiles and certs which I think is causing an issue.  The script fails.  The profile is not renewed.  Here are the results of running the script without the skip_fetch_profiles flag.

sigh renew -a com.company.app -o "~/Documents/Profiles/" -u me@company.com -b ABCDE12345 --development --skip_install --skip_certificate_verification --force --verbose


+-------------------------------------+---------------------------------------+
|                           Summary for sigh 1.8.0                            |
+-------------------------------------+---------------------------------------+
| app_identifier                      | com.company.app |
| username                            | me@company.com                |
| team_id                             | ABCDE12345                            |
| development                         | true                                  |
| skip_install                        | true                                  |
| skip_certificate_verification       | true                                  |
| force                               | true                                  |
| adhoc                               | false                                 |
| ignore_profiles_with_different_name | false                                 |
| skip_fetch_profiles                 | false                                 |
+-------------------------------------+---------------------------------------+

INFO [2016-06-02 13:32:14.57]: Starting login with user 'me@company.com'
INFO [2016-06-02 13:32:16.89]: Successfully logged in
INFO [2016-06-02 13:32:16.89]: Fetching profiles...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:175:in `sysread_nonblock': [!] end of file reached (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/buffering.rb:175:in `read_nonblock'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:153:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1375:in `block in request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:409:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:327:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:408:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:384:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/portal_client.rb:317:in `provisioning_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/provisioning_profile.rb:246:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/provisioning_profile.rb:266:in `find_by_bundle_id'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/runner.rb:68:in `fetch_profiles'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/manager.rb:7:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.45.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:99:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:117:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'

**Comment by amuzzy** [comment]
I should add, that when I run "sigh manage", it lists the profile that I am trying to update.

**Comment by asfalcone** [comment]
@amuzzy Thanks for the updates. Seems like the downloading of those 1000s of profiles could be causing the problem. Is there just one you're trying to renew here? If you could download and install it manually, then you'd be able to update it with the new devices. 

I'll keep looking for a way to download/install a single profile via `sigh` as well, and see if we can address the root cause of failing while trying to download so many things.

**Comment by amuzzy** [comment]
@asfalcone.  Eventually I want to use Sigh to renew about 100 profiles daily, adding all available developer certs and devices.  I can't have it renew all profiles for security reasons.

I have downloaded and installed the Developer Provisioning Profile I am trying to update, and verified that it is listed when I run "sigh manage".  I still encounter the issue where Sigh creates a new profile instead of renewing the existing entry.

**Comment by TKBurner** [comment]
@amuzzy Thanks for following up. We are looking into ways of dealing with large numbers of profiles and you should see continuous improvement. However, I'm also going to mark this as help wanted in case anyone from the community wants to step in. Thanks! 👍
