### ISSUE TITLE
Unexpected error during capture

### ISSUE THREAD

**Issue by mihir815** [fastlane/fastlane#4910]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
Exit status: 127
Caught error... 127
Too many errors... no more retries...
![screenshot capture error](https://cloud.githubusercontent.com/assets/968132/15665412/a244bdec-2728-11e6-9ac5-5baed5bf3bfd.png)

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.64.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "BabyLearn") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "BabyLearn") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md

```

### Environment

fastlane version (run `fastlane -v`): 1.86.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? Yes

**Comment by vpolouchkine** [comment]
Can you please post the full log and explain what's happening? Thanks.

**Comment by mihir815** [comment]
@vpolouchkine

I have attached the full log here, the log itself will explain you everything what issue i'm facing.

[Terminal Saved Output_02_06_2016.zip](https://github.com/fastlane/fastlane/files/294830/Terminal.Saved.Output_02_06_2016.zip)

Please advice.

Thanks

**Comment by vpolouchkine** [comment]
Can you first upgrade to the latest version of `snapshot` and then run this against a single language and device?

**Comment by mihir815** [comment]
I've updated to the latest version of fastlane, and everything appears fine in the report, however the script is taking a very long time to run (20 minutes for 5 screenshots on 5 devices in 1 language). It is also not capturing two of the five screens, even though the report says otherwise (for all devices)

**Comment by vpolouchkine** [comment]
Can you share the log please? If you could repro this in a separate project that would be 💯 .

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
