### ISSUE TITLE
Build on Jenkins in combination with match fails

### ISSUE THREAD

**Issue by lammertw** [fastlane/fastlane#4918]
I'm running a fastlane job on Jenkins with match and gym.

I've read the guide at https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Jenkins.md and it tells me to use the Keychains and Provisioning Profiles Plugin but that seems a bit outdated since I'm using match. I don't see how this plugin works in combination with match since it asks me to specify codesigning identities at configuration time.

I finally got match working after runnig into many problems (I'm using now MATCH_PASSWORD and FASTLANE_PASSWORD env variables to avoid some of the errors).

The result of match:
[15:15:18]: Cloning remote git repo...
[15:15:20]: [32m🔓  Successfully decrypted certificates repo[0m
[15:15:20]: Verifying that the certificate and profile are still valid on the Dev Portal...
[15:15:23]: Installing certificate...
[15:15:24]: Installing provisioning profile...

Unfortunately, once it starts building with gym, it fail with the following error:
[31m❌  Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found.[0m

How is this possible if it just installed it with match?

**Comment by TKBurner** [comment]
Hi @lammertw Thanks for reaching out. Can you let me know what happens if you set the codesigning_identity parameter of gym? Thanks!

**Comment by lenkaiser** [comment]
Hey @lammertw, I've been struggling with this problem too the last couple of days. What worked for me was a cleanup of my certificates in ITC (it was a mess). Then installed and set all the certificates on the jenkins build server (in the xcode project) so that Xcode doesn't give any warnings/errors regarding the provision profiles. It might nog be perfect but it works for me. This way I didn't have to use match at all.

**Comment by lammertw** [comment]
I found a solution and it seemed to be releated to the keychain. When I configure the job to first run the folllowing it works:

    security unlock-keychain -p ****

Does that make sense or should things also work without running that command. I'm using a `jenkins` user on a virtualbox instance.

**Comment by TKBurner** [comment]
@lammertw Awesome! Really glad you got up and running. Hope you have a wonderful day! 

@lenkaiser Thanks for stepping in! 💯

**Comment by lammertw** [comment]
Actually I found that the solution I mentioned is not the right one. So for those reading this later on, the right solution is to use the `setup_jenkins` action of fastlane and set a `keychain_path` option or `KEYCHAIN_PATH` environment variable. 

I could only find this by looking in the setup_jenkins action source code. Is there any documentation on this that describes this or anyway to run a `--help` command on this action?
