### ISSUE TITLE
Improve documentation to show how to find team IDs

### ISSUE THREAD

**Issue by mfurtak** [fastlane/fastlane#4921]
We should improve documentation to show a simple way to discover the values for the iTunes Connect team ID and the Developer Portal team ID, since some folks struggle to discover these values.

**Comment by nicolasbraun** [comment]
Also add how to find `itc_provider` for `deliver`;)

**Comment by KrauseFx** [comment]
This is something we now actually do automatically when using `fastlane init`, right?

**Comment by mfurtak** [comment]
I'm unsure about `fastlane init` and the iTC team ID and Developer Portal team ID. I think @nicolasbraun's request for help discovering the value for `itc_provider`is still a good one. Running

`/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/bin/iTMSTransporter -m provider -u <USER> -p <PASS> -account_type itunes_connect -v off`

is still the only way I know to get the right value for that for sure (since it is often the developer portal ID, but **not always**)

Some folks have asked that pilot/deliver determine that value automatically for them https://github.com/fastlane/fastlane/issues/5433#issuecomment-234139479

**Comment by chezzdev** [comment]
Sorry for interruption, but do you know a way to find iTunes Connect team id from UI (e.g. iTunes Connect web-site)?
