### ISSUE TITLE
When running sigh it hangs at "Starting login with user"

### ISSUE THREAD

**Issue by jlubeck** [fastlane/fastlane#4924]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

    osx:~ jenkins$ sigh download_all --verbose
    INFO [2016-05-31 13:03:48.53]: To not be asked about this value, you can specify it using 'username'
    Your Apple ID Username: user@domain.com 
    INFO [2016-05-31 13:04:00.46]: Starting login with user 'user@domain.com'

The terminal just hangs there with no error no nothing. No timeouts, nothing... It's been like that for 30 minutes. 

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
No FastFile, just plain sigh
```

### Environment

fastlane version (run `fastlane -v`): 1.91.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by KrauseFx** [comment]
Can you try running `sigh` on a different internet connection?

**Comment by jlubeck** [comment]
After I posted this I actually tried running it from a different User in the same computer (same connection), and it works fine. But then I go back to the same user that wasn't working before, and still does the same thing. How can that be? Is there something else I can check?

**Comment by jlubeck** [comment]
I don't know if this helps, but I eventually hit Ctrl-Z, and I got this:

````
^C/Library/Ruby/Gems/2.0.0/gems/security-0.1.3/lib/security/password.rb:88:in` ``': Interrupt
	from /Library/Ruby/Gems/2.0.0/gems/security-0.1.3/lib/security/password.rb:88:in `find'
	from /Library/Ruby/Gems/2.0.0/gems/credentials_manager-0.14.0/lib/credentials_manager/account_manager.rb:23:in `password'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:215:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:88:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/download_all.rb:6:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/manager.rb:34:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:45:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.36.5/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:99:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:117:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'

**Comment by jlubeck** [comment]
Ok, I was able to make it work by unlocking the keychain first:

    security unlock-keychain ~/Library/Keychains/Login.keychain

Is there any way to catch this and provide an error to the user? 
It also seems like I need to to this every time I open the terminal. Is there anyway to prevent this?

Thanks!!

**Comment by KrauseFx** [comment]
Oh yeah 👍 Actually I don't know of any way, since it requires a user input, but the shelling out doesn't get this output
