### ISSUE TITLE
ensure_git_clean -  problem with "" vs no quotes in Podfile.lock

### ISSUE THREAD

**Issue by kikolobo** [fastlane/fastlane#4926]
There is an issue with gem dependency called Psych, which adds quotes or not to a Podfile.lock

This makes the ensure_git_clean fail, because some developers have a different version that changes de Podfile.lock.

We are using CocoaPods 1.0 and Ruby ruby 2.0.0p648

All same version. The only dif is Psych.

A work around is to have everyone on the same Psych version;
Ej : 
gem install psych -v 2.0.8
gem uninstall psych -v 2.x.y

So.... Is there anyway that ensure_git_clean can ignore "" in some circumstances?

**Comment by vpolouchkine** [comment]
I don't believe there is.
