### ISSUE TITLE
Swiftlint support all the arguments

### ISSUE THREAD

**Issue by giacgbj** [fastlane/fastlane#4928]
$ swiftlint help lint
Print lint warnings and errors (default command)

[--path (string)]
	the path to the file or directory to lint

[--use-stdin]
	lint standard input

[--config (string)]
	the path to SwiftLint's configuration file

[--strict]
	fail on warnings

[--use-script-input-files]
	read SCRIPT_INPUT_FILE* environment variables as files

[--benchmark]
	save benchmarks to benchmark_files.txt and benchmark_rules.txt

[--reporter (string)]
	the reporter used to log errors and warnings

[--quiet]
	don't print status logs like 'Linting <file>' & 'Done linting'

**Comment by vpolouchkine** [comment]
This is not on our radar, but keeping this open for upvotes.

**Comment by jcampbell05** [comment]
Perhaps you could move this into a plugin to be developed seperatley ?

**Comment by TKBurner** [comment]
@jcampbell05 That seems like the best path for this! Thanks for following up. Hope you have a great weekend coming up 👍
