### ISSUE TITLE
Add multiple choice selection to the Prompt action

### ISSUE THREAD

**Issue by czechboy0** [fastlane/fastlane#494]
Used in [`line_manager`](https://github.com/KrauseFx/fastlane/blob/5e9510c98481388d75d8b519357a711e4f15187a/lib/fastlane/lane_manager.rb#L97), it'd be nice to add this utility to the Prompt action. The goal is to be able to call `selection = prompt(text: "Which cat?", choices: ["happy", "fluffy", "furry"])` and have the user be able to just input the index of the choice, getting back `fluffy` if I type `2`.

The user would see something like
```
Which cat?
1) happy
2) fluffy
3) furry
```

**Comment by KrauseFx** [comment]
Ah, back then I was still young, there is a much cooler way to do that: https://github.com/fastlane/gym/blob/master/lib/gym/detect_values.rb#L62-L63

But yes, having this as a `fastlane` action as past of `prompt` sounds great! :

**Comment by ohwutup** [comment]
Hey everyone! I am going to go ahead and close this issue for now as it has been quite some time since there has been activity on it! We will leave it marked as a feature request and reopen it as soon as we have a chance to bite this off for a future release! 

Thanks @czechboy0 ! :octopus:

**Comment by KrauseFx** [comment]
@ohwutup We now actually have a new method that makes it super easy for us to add

```ruby
project = UI.select("Select your project: ", ["Test Project", "Test Workspace"])
```

It's probably 10 minutes of time to add an action for that :+1:

**Comment by KrauseFx** [comment]
@czechboy0 Do you want to take this over? :smile:

**Comment by czechboy0** [comment]
@KrauseFx I'll take a look at it, sure. Time to write some Ruby anyway. :laughing:

**Comment by KrauseFx** [comment]
Oh yeah :rocket:

**Comment by czechboy0** [comment]
Actually, the `UI.select` function does pretty much what I need. It's trivial to just look up the index of the answer afterwards, so I don't think there's much value in adding that to `fastlane_core`.

**Comment by KrauseFx** [comment]
Agreed
