### ISSUE TITLE
Scan exits with error code 65 with failed tests

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#4947]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I working towards a full conversion of my employer's build system which uses a collection of bash scripts and ruby scripts to a unified system using Fastlane. Our code is automatically tested by Jenkins when new code is pushed and the web hook is called.

Our current system will output Green for a test job that has 0 failures. It will output Orange for a test job that has 1 or more failures. It will output Red for a test job that fails for some other reason such as a crash, an inability to build, an inability to clone the repo, etc. Jenkins uses Green or Orange if the exit code is 0. Green if it finds no failures in the test report xml file, and Orange if it finds 1 or more failures in the test report.xml file.

With `scan`, I do not get the 3 results that I want. It is either Green for a test job that has 0 failures, or Red for a test job that fails to build and test or if there are more than 1 failing test. That is because when xcodebuild finds a failing test, it returns 65. 

Is there a way to configure the `fastlane test` (test being the name of the lane that sets up and runs `scan`) so that if there is a failing test, the exit code of the command is 0? Do I have to wrap the code up in a shell script that checks the result of the test log to see if tests passed or failed and return 0 for that case (or 1 for missing files or lack of test success state)?

##### Complete output when running fastlane, including the stack trace and command used

```
+-----------------------+-------------------------+
|             Summary for scan 0.7.1              |
+-----------------------+-------------------------+
| scheme                | MainTestScheme    |
| buildlog_path         | logs                    |
| output_directory      | test-reports            |
| workspace             | ./app.xcworkspace |
| clean                 | false                   |
| code_coverage         | false                   |
| address_sanitizer     | false                   |
| skip_build            | false                   |
| output_types          | html,junit              |
| open_report           | false                   |
| skip_slack            | false                   |
| slack_only_on_failure | false                   |
+-----------------------+-------------------------+

[14:10:05]: Killing all running simulators
[14:10:05]: Explicitly opening simulator for device: iPhone 5s
[14:10:05]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace './app.xcworkspace' -scheme 'MainTestScheme' -destination 'OS=9.3,name=iPhone 5s' build test | tee '/Users/me/workspace/workspace/lyndsey-ferguson_convert-to-fastlane-buildtest-infrastructure_ios/logs/MainTestScheme.log' | xcpretty --no-color

...

Executed 17 tests, with 1 failure (0 unexpected) in 554.209 (554.226) seconds
** TEST FAILED **
[14:21:07]: Exit status: 65
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 17    |
| Number of failures | 1     |
+--------------------+-------+
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
desc "Runs the tests for the X iOS app depending on the given scheme."
  desc "If no test scheme is specified, the Main Test scheme will be used."
  lane :test do |options|
    scheme_to_test = options.fetch(:scheme, "MainTestScheme")
    scan_options = {
      :scheme => scheme_to_test,
      :destination => "OS=9.3,name=iPhone 5s",
      :buildlog_path => "logs",
      :output_directory => "test-reports" # used by Jenkins to display trends and reports
    }
    scan(scan_options)
  end
```

### Environment

fastlane version (run `fastlane -v`): 1.92.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No. I am currently calling it from a script for it to work with our current Jenkins environment: 
```
SCHEME_ARGUMENT="scheme:MainTestScheme"
while [[ $# > 1 ]]
do
  key="$1"

  case $key in
      -s|--scheme)
        SCHEME_ARGUMENT="scheme:${2}"
        ;;
      *)
        echo "Unknown option $key"
        exit -1
        ;;
  esac
done

source ./scripts/prep_environment.sh

FASTLANE_EXPLICIT_OPEN_SIMULATOR=1 fastlane test "$SCHEME_ARGUMENT"
```

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by vpolouchkine** [comment]
I don't believe there is a way to do that, but your workaround seems reasonable.

**Comment by lyndsey-ferguson** [comment]
Here is how I changed my script that calls `fastlane test`:
```bash
FASTLANE_EXPLICIT_OPEN_SIMULATOR=1 fastlane test "$SCHEME_ARGUMENT"
if [[ $? -eq 65 ]]
then
  if [ "$(ls -A test-reports)"]
  then
    exit 0 # xcode reported a failure, but there are test reports, probably we have run through the tests successfully
  fi
fi
```

**Comment by vpolouchkine** [comment]
Nice one.

**Comment by CodeStage** [comment]
I had this too, for me it was an async test case with an expectation. This test case would crash the test runner when calling waitForExpectationsWithTimeout. Which was super weird because it would only happen on some machines but not all. And the test case had not been touched in months. So I refactored the test case to use GCD locking instead of waitForExpectationsWithTimeout and the problem was gone.
