### ISSUE TITLE
[Match] 

### ISSUE THREAD

**Issue by matthijs2704** [fastlane/fastlane#4966]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Fastlane doesn't build anymore with error "CodeSign error: code signing is required for product type '...' in SDK '...'" and I noticed the text in Xcode as in the screenshot below:

![bpdpueb4](https://cloud.githubusercontent.com/assets/4346200/15749886/72c59d08-28e4-11e6-89b2-594d5a02f226.jpg)

The correct Match profile is selected in all targets but still Xcode shows "Don't Code Sign" but definitely Code Signing is enabled.

##### Relevant output when running fastlane, including the stack trace and command used

```
[14:49:33]: ▸ Building MyProject/Project iOS [Release]
[14:49:33]: ▸ Check Dependencies
[14:49:33]: ▸ ❌  CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.3'
[14:49:33]: ▸ ** ARCHIVE FAILED **
[14:49:33]: ▸ The following build commands failed:
[14:49:33]: ▸ Check dependencies
[14:49:33]: ▸ (1 failure)
▸ Building MyProject/Project iOS [Release]
▸ Check Dependencies
❌  CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 9.3'
```

**Comment by TKBurner** [comment]
@matthijs2704 Hope you are doing well! Let me know if you still need any help 👍 Hope you have a great week!
