### ISSUE TITLE
iTunes rejects uploads due to missing SwiftSupport Files.

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#4969]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When uploading an app with Swift, iTunes rejects it due to missing support libraries but in the IPA that gym exports they are there so iTunes should in theory be happy with what is uploaded.

### Configuration Files

Not to do with the Fastfile.

### Environment

fastlane version (run `fastlane -v`): 1.91.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by jcampbell05** [comment]
I can send the IPA being uploaded upon request (Too big for github)

**Comment by TKBurner** [comment]
Hi @jcampbell05 Thanks for reaching out! Always great to hear from you. Can you let me know if you are running gym from the cmdline or in a Fastfile? Either way send the full output with the --verbose flag.

Thanks again for working with us 👍

**Comment by GabrielCartier** [comment]
I'm having a similar problem. Right now, the only (less than ideal) way I found to send my build was to do it manually.

Are you using legacy API, because I am and I feel like it may be related to the issue.

**Comment by TKBurner** [comment]
Hi @GabrielCartier Thanks for following up on this. Can you let me know if you still see this issue not using the legacy API? I want to get to the bottom of this. Thanks!

**Comment by GabrielCartier** [comment]
Haven't updated to try without the legacy API. We use bitrise and it wasn't working, I'll try updating and let you guys know.
