### ISSUE TITLE
"hockey" action has misleading api description

### ISSUE THREAD

**Issue by pRizz** [fastlane/fastlane#4970]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running `fastlane action hockey`, the description tells the user to use certain values for the api, but when these literal values are used, fastlane errors out saying the parameters are of the wrong type.

#### Expected
I can supply `1` to the hockey action.

#### Actual
Fastlane returns an error:
```
[11:23:15]: fastlane finished with errors

[!] 'notify' value must be a String! Found Fixnum instead.
```

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane action hockey
...
| notify            | Notify testers? 1 for yes                                                                                                                | FL_HOCKEY_NOTIFY            | 1                  |
...
```
#### Proposal
Fix the description to surround the values with double quotes `""` if they need to be strings, like:
```
fastlane action hockey
...
| notify            | Notify testers? "1" for yes                                                                                                                | FL_HOCKEY_NOTIFY            | 1                  |
...
```

### Configuration Files

~~Please copy the complete content of your `Fastfile` and any other configuration files you use below:~~
This issue is Fastfile independent.

### Environment

fastlane version (run `fastlane -v`): fastlane 1.93.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

### Pull Request
I can probably make a PR in the next few days addressing this. It seems like a simple change.

**Comment by vpolouchkine** [comment]
This makes sense to me, a PR would be great. 💯

**Comment by pRizz** [comment]
Close issue? @vpolouchkine

**Comment by KrauseFx** [comment]
Yeah, thanks for your contribution @pRizz 👍
