### ISSUE TITLE
Resuming a lane that got cancelled

### ISSUE THREAD

**Issue by crylico** [fastlane/fastlane#498]
Hey, I think it would be pretty neat to have the ability to start off after the last successful action.

For example, if a lane looks like

    lane :beta do
        increment_build_number
        sigh(....)
        gym(....)
        crashlytics(....)
    end

and for some reason, crashlytics fails (perhaps the network request failed due to poor connection), it would be awesome if you could resume starting at that action.

Thoughts?

**Comment by KrauseFx** [comment]
I love the idea. I'd have to carefully think about any side effects that may occur, e.g. restoring the lane context and the environment variables (which may contain sensitive data).

I really like the idea, thanks for letting me know :+1:

**Comment by ohwutup** [comment]
Hey @crylico! Thanks for raising this as an issue, its definitely a sweet idea. I am going to close this and keep it marked as a feature request and we will reopen it when we can get a chance to pull the task. If you would want to propose a nice way to do this given the concerns of restoring the lane's context and the environment variables with sensitive information, we would be happy to discuss! Thanks again! :octopus: !
