### ISSUE TITLE
Fastlane does use Appfile when issuing the command Produce from Fastfile or from shell. 

### ISSUE THREAD

**Issue by smittysmee** [fastlane/fastlane#4980]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Fastlane does use Appfile when issuing the command Produce from Fastfile or from shell.
Specifically, the command for creating the app in the iTunes Connect teams is asked even when the team_name is specified in the Appfile.

### Configuration Files
app_identifier XXXXXX  # Removed for public display
apple_id "XXXXXXXXXXX # Your Apple email address... Removed for public display
team_name "XXXXXXXXXXXX" # Removed for public display

Fastfile:
```ruby

produce(
        app_name: options[:app_name],
        company_name: options[:company_name],
        language: "English",
        app_version: get_version_number(options[:scheme]),
        sku: options[:app_id]
    )

    # Because there is now way as of right now with spaceship to implement this call we do command line
    sh("produce enable_services  --push-notification")

```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.93.1 
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by KrauseFx** [comment]
Sorry what's the problem? That is uses the username?

**Comment by smittysmee** [comment]
I am apart of 10 or so teams and when submitting a "produce" procedure via fast lane, even with my Appfile correctly setup, I am being asked to select a team for only iTunes Connect. Apple Developer Center is fine and does not ask for the team.

I have tried manually defining it in the call as well as in the Appfile yet no matter what, the iTunes Connect always request for team selection.

**Comment by smittysmee** [comment]
Summary for produce 1.1.2  is produced correctly with all the correct information that should be needed to select the iTunes Connect team.

**Comment by TKBurner** [comment]
Hi @smittysmee What happens if you set itc_team_name or itc_team_id?

Thanks!

**Comment by smittysmee** [comment]
I will test this and let you know. :)

**Comment by smittysmee** [comment]
Shoot. I don't think I read the man page close enough missed that last section. 
Closing this.
