### ISSUE TITLE
Sigh: authentication.failed Your session has expired.  Please log in.

### ISSUE THREAD

**Issue by jlubeck** [fastlane/fastlane#4981]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running sigh to download_all my certificates I get this error. 

```
osx:drivemode jan$ sigh download_all --verbose
INFO [2016-06-02 17:22:06.59]: Starting login with user '***@***.com'
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:432:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
	authentication.failed
	Your session has expired.  Please log in.
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/portal_client.rb:51:in `teams'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/ui/select_team.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/portal_client.rb:67:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/portal/spaceship.rb:81:in `select_team'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/download_all.rb:7:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/lib/sigh/manager.rb:34:in `download_all'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:45:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:99:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/sigh-1.8.0/bin/sigh:117:in `<top (required)>'
	from /usr/local/bin/sigh:23:in `load'
	from /usr/local/bin/sigh:23:in `<main>'
```

It was working a couple of hours ago. I saw other tickets (old ones) that mentioned it got fixed by itself after a while. Like it was an Apple issue. Just wondering if this is the case or I did something wrong. 

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
No Fastfile. Just plain old sigh
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.93.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by KrauseFx** [comment]
This might be related to http://techcrunch.com/2016/06/02/apple-app-store-goes-down/, let's try again later today 👍

**Comment by KennethRMason** [comment]
FWIW, we are experiencing this exact same symptom in out CI system, which uses `sigh` to download provisioning profiles.
```
[12:47:43][Step 1/1] [!] Apple provided the following error info:
[12:47:43][Step 1/1] 	authentication.failed
[12:47:43][Step 1/1] 	Your session has expired.  Please log in.
```
We have confirmed that the credentials are valid, when typed in manually on `developer.apple.com`.

**Comment by jlubeck** [comment]
I need to remember to keep checking this page: https://www.apple.com/support/systemstatus/

Several service were down yesterday on that page.

Everything seems to be back to normal now and sigh is working fine again. Thanks Felix for that techcrunch link!
