### ISSUE TITLE
Fastlane exits with 0 even though the log shows exit 65

### ISSUE THREAD

**Issue by arunks** [fastlane/fastlane#4982]
I am executing a fastlane command in jenkins as follows - 

fastlane EnterpriseBuild

That is the only command I have on my jenkins build shell 

There is a build error and the exit status on the log was Exit Status 65
But then, the overall jenkins shell exits with a 0.

Has anyone seen this behavior?

I am on fastlane 1.48.0

TIA
Arun

**Comment by KrauseFx** [comment]
Please follow the issue template, in particular the complete output and `Fastfile` 👍

**Comment by TKBurner** [comment]
Hi @arunks! Great to hear from you. Can you share the full output as well as the commands you are using. Also can you run sudo gem update fastlane? Thanks!
