### ISSUE TITLE
scan on iOS physical device

### ISSUE THREAD

**Issue by stas6100** [fastlane/fastlane#4986]
I can't find a way to run `scan` command on physical device. 
Does the possibility exist? If so what should provide as arguments so it will end up running something like: 
```xcodebuild -destination ‘id=%physical_device_id%’````

**Comment by hibento** [comment]
I'd be interested in this too - we have some tests here that strictly need to run a on a Hardware-Device.

**Comment by TKBurner** [comment]
Hi @stas6100 Great to hear from you! Right now this isn't supported however I'll mark this as a feature request since it's come up twice lately. Thanks so much for working with us and using Fastlane! Have an awesome week 👍

**Comment by krze** [comment]
I've been successfully running scan on a physical device. You can use `destination` with platform and id to specify a platform of `iOS` and a device UDID for id

**Comment by hibento** [comment]
Great, works for us - thank you.

**Comment by jeffreyjackson** [comment]
Ive been doing the same thing with multiple devices.

**Comment by stas6100** [comment]
@krze thanks that works

**Comment by krze** [comment]
@jeffreyjackson what do you mean by multiple devices? Is there a way to pass in multiple UDIDs into one destination?

**Comment by TKBurner** [comment]
@krze I believe @jeffreyjackson  meant on multiple devices one at a time.  Thanks!

**Comment by AshMorningStar** [comment]
Hey,How can I set this in the scanfile?
