### ISSUE TITLE
Failed on fastlane init : app has white space in name

### ISSUE THREAD

**Issue by alokc83** [fastlane/fastlane#4988]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
fastlane init spit out the errors.
I think issue is that my app having spaces in the name. 

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane init
/Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:43:in `eval': (eval):21: syntax error, unexpected ':', expecting keyword_end (SyntaxError)
      app_name: 'my Prayers Lite',
               ^
(eval):21: syntax error, unexpected ',', expecting keyword_end
(eval):22: syntax error, unexpected ',', expecting keyword_end
(eval):23: syntax error, unexpected ',', expecting keyword_end
(eval):25: syntax error, unexpected ')', expecting keyword_end
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:43:in `block in initialize'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:31:in `chdir'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:31:in `initialize'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:7:in `new'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:7:in `try_fetch_value'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:127:in `android_app_identifier'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:151:in `p_hash'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:72:in `generate_fetch_url'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:18:in `start_looking_for_update'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.93.1/lib/fastlane/commands_generator.rb:15:in `start'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.93.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.93.1/bin/fastlane:5:in `<top (required)>'
	from /Users/alokchoudhary/.rvm/rubies/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/alokchoudhary/.rvm/rubies/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.93.1
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

**Comment by TKBurner** [comment]
Hi @alokc83 Thanks for writing in. Can you share the full output of Fastlane init? Also what is your app name set to in your project?

Thanks!

**Comment by alokc83** [comment]
Following is the complete output when I run the fastlane init.
> /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:43:in `eval': (eval):21: syntax error, unexpected ':', expecting keyword_end (SyntaxError)
>       app_name: 'Indian Prayers Lite',
>                ^
> (eval):21: syntax error, unexpected ',', expecting keyword_end
> (eval):22: syntax error, unexpected ',', expecting keyword_end
> (eval):23: syntax error, unexpected ',', expecting keyword_end
> (eval):25: syntax error, unexpected ')', expecting keyword_end
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:43:in `block in initialize'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:31:in `chdir'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:31:in `initialize'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:7:in `new'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/credentials_manager-0.16.0/lib/credentials_manager/appfile_config.rb:7:in `try_fetch_value'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:127:in `android_app_identifier'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:151:in `p_hash'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:72:in `generate_fetch_url'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane_core-0.46.2/lib/fastlane_core/update_checker/update_checker.rb:18:in `start_looking_for_update'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.93.1/lib/fastlane/commands_generator.rb:15:in `start'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.93.1/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3@global/gems/fastlane-1.93.1/bin/fastlane:5:in `<top (required)>'
> 	from /Users/alokchoudhary/.rvm/rubies/ruby-2.2.3/bin/fastlane:23:in `load'
> 	from /Users/alokchoudhary/.rvm/rubies/ruby-2.2.3/bin/fastlane:23:in `<main>'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
> 	from /Users/alokchoudhary/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

I am not sure about your second question but project name is "Indian Prayers', I have two targets "app_name: 'Indian Prayers Lite' that is lite/ free version. Its out on appstore but I am have not released paid version "Indian Prayers" yet.

**Comment by TKBurner** [comment]
Hi @alokc83 Thanks for following up. What folder are you in when you run fastlane init? Can you let me know if you have an single or double quotes in the name of this app. It looks like there is an issue with the way we are parsing the name.

Finally can you sudo gem update fastlane so I can make sure you are on the most current version? And is there any chance you can run on ruby 2.3+?

Thanks!
