### ISSUE TITLE
Shared Logs Path

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/fastlane#4989]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Various **fastlane** tools have options for specifying a log output path. **gym**, **snapshot**, **scan**, and the **xcodebuild** action. They all default to a directory under `~/Library/Logs/` but to override this they have to be changed individually within their options, their `*file` config, or ENV variables.

I'd like to propose introducing a new shared variable to be used across all fastlane tools and actions to allow setting a global log output base directory.

**Comment by TKBurner** [comment]
Hi @Ashton-W! Great idea! Are you interested in submitting a PR? I've marked this as help wanted in case anyone wants to take a crack at it 👍

**Comment by KrauseFx** [comment]
I love the idea 👍

**Comment by Ashton-W** [comment]
I need to do another Pull Request to complete this

**Comment by TKBurner** [comment]
Thanks @Ashton-W! Tag this issue in your PR when you create it so we can clean things up. Really glad to be working with you 👍

**Comment by Ashton-W** [comment]
Sorry, this was completed in #5881

**Comment by KrauseFx** [comment]
Thanks for updating @Ashton-W 👍
