### ISSUE TITLE
Signing without logging into to dev account

### ISSUE THREAD

**Issue by gdunnjr** [fastlane/fastlane#499]
It appears that in order to use ipa and sigh for signing apps, I would have to provide my apple developer account username and password and store them in environment variables on the build server. Since we are going to use a cloud based CI Server this is a security concern.

Using CircleCI I was able to write shell scripts to create a keychain using the specific signing cert and private cert I had checked into github. The private cert is encrypted and password protected. Although I have to put the password to this cert into github, this is preferable to putting the password to my account in an environment variable.

Is there any way to use ipa and point it at a keychain you create on the build server manually?

**Comment by JaviSoto** [comment]
We just launched a new tool called [match](https://github.com/fastlane/match) that simplifies code signing and takes care of all the heavy lifting for you. You should give it a try :+1:

**Comment by KrauseFx** [comment]
`match` allows you to use certificates without having access to the developer portal :rocket: Let us know how that goes for you
