### ISSUE TITLE
Prevent scan from failing the lane if a test fails?

### ISSUE THREAD

**Issue by cutz** [fastlane/fastlane#5001]
Is there an option to run scan in a way that won't fail the lane if a test fails.  I wan't to run several iterations of scan (on different targets) in one lane and report on the produced results.  By default if scan detects failed tests it throws an exception that triggers the lane to stop.  Besides catching the exception is there another way to make scan not fail the lane if a test fails?

**Comment by KrauseFx** [comment]
Yeah, you can use Ruby for that
```ruby
lane :test do
  ["scheme1", "scheme2"].each do |current_scheme|
    begin
      scan(scheme: current_scheme)
    rescue => ex
       puts ex
    end
  end
end
```

**Comment by cutz** [comment]
Thanks, I will go that route.
