### ISSUE TITLE
Is Fastlane::Actions.sh_control_output public API?

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#5005]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have build secrets that I want to keep out of my fastlane logs. I discovered `Fastlane::Actions.sh_control_output` inside the `fastlane` `gem` source. I want to make sure this is supported API so that I can be sure my `Fastfile` doesn't break going forward.

In my `Fastfile`, I simply replaced `sh` calls whose output should be suppressed:

```
secret=sh("./my_script_that_prints_a_secret.bash")
```

with `Fastlane::Actions.sh_control_output` calls:

```
secret=Fastlane::Actions.sh_control_output("./my_script_that_prints_a_secret.bash", 
                                           print_command_output: false)
```

Also, if this and `sh` are supported actions, why don't they show in `fastlane actions`? Is there a different command for implicit actions?

**Comment by TKBurner** [comment]
Hi @hborders! Great to hear from you. Glad you are getting into Fastlane. The sh command runs shell commands. Let me know if you run into any issues getting up and running. 👍

**Comment by hborders** [comment]
But `sh` puts its output into the logs, which I don't want because I'm grabbing secrets. I want to make sure that `Fastlane::Actions.sh_control_output` is public API. It works for me now, but I don't want my `Fastfile` to break in a future release because you changed `Fastlane::Actions.sh_control_output`.

**Comment by TKBurner** [comment]
@hborders Thanks for clarifying. It is not a public API, but if you can access it from Spaceship you should be able to trust it for the foreseeable future. Thanks!

**Comment by hborders** [comment]
I don't need this specifically to be a public API, but I'd like to request something like this that hides output from logs to prevent data leakage. Do you want me to create a new PR?

**Comment by TKBurner** [comment]
Hi @hborders Thanks for following up. A PR would be great if you are interested. Make sure to include test coverage. 👍
