### ISSUE TITLE
Deliver: Incorrect App_Icon Uploaded

### ISSUE THREAD

**Issue by vbresults** [fastlane/fastlane#5006]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When running deliver back to back, using the app_icon option, sometimes at random, the wrong icon is assigned (another icon from the app store) and uploaded to ITC.

### Environment

deliver version: 1.11.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
@vbresults Thanks for sharing this. It's going to be hard to hunt down on our end. Can you provide repro steps, or screenshots so we can see this exactly? I really appreciate you helping us improve Fastlane 👍 

Thanks!

**Comment by vbresults** [comment]
@TKBurner Try to deliver 2 or 3 dozen apps back to back with an app_icon in the deliver file

**Comment by vbresults** [comment]
@TKBurner Found the problem, and it was not deliver; sorry and thank you.
