### ISSUE TITLE
increment_build_number xcodeproj path

### ISSUE THREAD

**Issue by PabloLerma** [fastlane/fastlane#5012]
Hi,

I am having problems configuring "increment_build_number" action.
I have my .xcodeproj in a subfolder so I tried to setup my fastfile with:
incremental_build_number(xcodeproj: 'subfolder')

But looking at the [increment_build_number source code](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_build_number.rb#L19) it appends a "/.." at the end of the path specified so fastlane reads: 
"Users/MyUser/Repository/MyProject/" instead of "Users/MyUser/Repository/MyProject/subfolder"

If I setup incremental_build_number(xcodeproj: 'subfolder/anotherSubfolder') it works (because of the "/.."

Is it a bug or where I am wrong?

### Environment

fastlane version (run `fastlane -v`):
1.94.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No.
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No.

**Comment by TKBurner** [comment]
Hi @PabloLerma Thanks for reaching out! This is expected behavior for now. Your workaround is a good solution. Thanks!

**Comment by PabloLerma** [comment]
Hi @TKBurner 
I'm wondering why this is expected behaviour... 
Why not just append "." like in the commit_version_bump action:
xcodeproj_path = params[:xcodeproj] ? File.expand_path(File.join('.', params[:xcodeproj])) : nil

**Comment by TKBurner** [comment]
Hi

**Comment by TKBurner** [comment]
Hi @PabloLerma Thanks for following up. Because this is inconsistent between the two actions I'll mark this as help wanted in case anyone wants to submit a PR. Thanks!

**Comment by emoreth** [comment]
I am also having problems finding Info.plist file...
My project is a cordova/ionic with a few customizations. My plist file isnt located at the default path.

Maybe we could add another option to manually set the plist path, so no guessing would be done.

Does it make sense ?

**Comment by TKBurner** [comment]
@emoreth Thanks for following up and for your update I'm going to leave this open in case anyone wants to fix this inconsistency. Thanks 👍
