### ISSUE TITLE
Snapshot disables hardware keyboard but never re-enables when completed

### ISSUE THREAD

**Issue by yankat** [fastlane/fastlane#5013]
### Issue Description

The simulator's hardware keyboard is disabled by snapshot with the following command:
`defaults write com.apple.iphonesimulator ConnectHardwareKeyboard 0`

But when snapshot completes, it never reconnects the hardware keyboard.

### Environment

fastlane version (run `fastlane -v`): 1.94.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by TKBurner** [comment]
@yankat Thanks for reaching out. This is an interesting point. I'm sending it out to the core team.

Thanks! 👍
