### ISSUE TITLE
[supply] - Explicit command to download store data

### ISSUE THREAD

**Issue by philippb** [fastlane/fastlane#5025]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Feature request

It would be nice to have a serrate command to download existing store descriptions besides `init`.
We have multiple apps and I can't find out how to download the metadata from another app that I didn't use to initialize supply with.

I have existing store descriptions that would be good to get downloaded to local for modifications.

**Comment by vpolouchkine** [comment]
Thanks for the feedback; keeping this open for upvotes.

**Comment by dantaylorseo** [comment]
+1 this feature would be really useful

**Comment by athornz** [comment]
+1

**Comment by TKBurner** [comment]
Going to mark this as help wanted in case anyone wants to submit a PR. Thanks!
