### ISSUE TITLE
commander 4.3.5 warning: constant ::TimeoutError is deprecated with ruby 2.3.0

### ISSUE THREAD

**Issue by raven** [fastlane/fastlane#5027]
# ruby 2.3.0 deprecation warning

commander 4.3.5 with ruby 2.3.0 issues a deprecation warning. This was fixed in commander 4.3.6, https://github.com/commander-rb/commander/pull/22.

I understand that fastlane has a pinning requirement on 4.3.5, per:
https://github.com/fastlane/fastlane/issues/3966

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
$ bundle exec fastlane --version
/Users/petergoldsmith/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
fastlane 1.94.1
```

### Environment

fastlane version (run `fastlane -v`): 1.94.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by vpolouchkine** [comment]
Thanks for the report! We'll take a look.

**Comment by ohwutup** [comment]
https://github.com/fastlane/fastlane/pull/5101

**Comment by mojtabacazi** [comment]
Any update on this?

**Comment by vpolouchkine** [comment]
I'm afraid not.

**Comment by KrauseFx** [comment]
I'm working on it 🚀 https://github.com/fastlane/fastlane/pull/5612

**Comment by KrauseFx** [comment]
This has been fixed 👍
