### ISSUE TITLE
gym, upload_bitcode, hidden symbols, oh my

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/fastlane#5028]
### Bitcode uploaded when gym told not to

Need to verify behavior on this.
Our Xcode project has `ENABLE_BITCODE = YES`
Our gym settings have `include_bitcode: false`

The resultant xcodebuild command says

```
set -o pipefail && xcodebuild -workspace './MYAPPLICATION.xcworkspace' -scheme 'MYAPPLICATION' -configuration 'Release' -sdk 'iphoneos' -destination 'generic/platform=iOS' -archivePath '/Users/travis/Library/Developer/Xcode/Archives/2016-06-07/MYAPPLICATION_2c1f96f 2016-06-07 06.30.33.xcarchive' clean archive CODE_SIGN_IDENTITY='iPhone Distribution: MYCOMPANY, Inc.' | tee /Users/travis/Library/Logs/gym/MYCOMPANY-MYCOMPANY.log | xcpretty
```

There is no `-uploadBitcode 'false'` as an xcodebuild `exportOptionsPlist` parameter, as I would expect according to `xcodebuild --help`

So, I'm not sure what the include_bitcode parameter of gym is actually trying to do. 

Result is that we have `__hidden#xxx__` symbols in our dSYMs that are uploaded to iTunes Connect.
Before our experiments with bitcode uploading, we did not encounter hidden symbols. 
(Now I see that there is a `GCC_SYMBOLS_PRIVATE_EXTERN` setting. 
Perhaps this is the actual root problem?)
### gym settings

``` ruby
gym (scheme: SCHEME_APPSTORE,
             configuration: 'Release',  
             codesigning_identity: CODESIGN_ID_APPSTORE,                                 
             output_name: "MYAPPLICATION_#{CURRENT_COMMIT}",    
             use_legacy_build_api: true,
             sdk: 'iphoneos',
             clean: true,
             include_symbols: true,     
             include_bitcode: false     
)       
```
### Environment

Travis-CI with fastlane 1.85.0 (yes, I see it is a little old; but I didn't see any updates that address my issue)

**Comment by vpolouchkine** [comment]
Looks like a bug to me. Thanks for the report.

**Comment by asgoel** [comment]
any updates on this one? actually got an email from iTunes Connect on our last upload saying that we shouldn't be uploading bitcode, which confused me because I also have `include_bitcode=False`

**Comment by mfurtak** [comment]
Hi @ChristopherDrum - when you run your build, do you see output like: 

```
Legacy build api is enabled, the `include_bitcode` value will be ignored
```

I believe `use_legacy_build_api` precludes the generation of an **exportOptionsPlist**, so gym should be attempting to warn you about this with the above message.

**Comment by serluca** [comment]
Hi @mfurtak 

I'm having the same issue with all the symbols hidden when using `use_legacy_build_api` to true.
Setting `use_legacy_build_api` to false instead works but most of the time gym fails and suggests to set that flag to true. 
Any suggestion on how to fix it?

**Comment by mfurtak** [comment]
Hi @serluca - I'm sorry, I don't immediately see the connection to this issue. Would it make sense to open a new issue with full details for your problem?
