### ISSUE TITLE
[match] Prevent match from overwriting the README

### ISSUE THREAD

**Issue by 3lvis** [fastlane/fastlane#5029]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

How do I stop `match` from overwriting my README?

Is driving me nuts.

**Comment by TKBurner** [comment]
@3lvis Thanks for following up. Match requires it's own full repo (branch of a repo). You can use multiple branches to avoid this but the best solution would be having your readme live outside of this repo. Thanks!

**Comment by 3lvis** [comment]
@TKBurner Thanks Todd! That sounds like a good solution.
