### ISSUE TITLE
Action to inject a specific properties file to override one in an IPA?

### ISSUE THREAD

**Issue by fatuhoku** [fastlane/fastlane#503]
Staging and production builds only differ by a few string values.

The build process (cocoapods, ipa / gym) is virtually identical in the most part.

It'd be great if it's possible to break open an IPA, replace a `server-keys.properties` file, and then off the IPA goes to a different `deliver` process!

**Comment by KrauseFx** [comment]
I assume that should be part of [gym](https://github.comf/astlane/gym), right?

**Comment by KrauseFx** [comment]
So you want to modify an existing ipa file (extract, modify and compress again) to replace/change just a few files?

**Comment by fatuhoku** [comment]
Yes. It's a use-case that could potentially optimize on calling fastlane once rather than twice (I currently do this manually!).

**Comment by ohwutup** [comment]
Hey @fatuhoku! Thanks for raising up this feature request! We will close it for now but leave it marked so that, as soon as we get to this for a future release, we will update the issue to keep you informed! Thanks again! :octopus: :ocean: :ox:
