### ISSUE TITLE
Get tests results from scan in lane

### ISSUE THREAD

**Issue by teriiehina** [fastlane/fastlane#5030]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,

it would be nice to be able to get the test results from a `Fastlane` lane. A quick'n'dirty way to do it can be seen in [this gist](https://gist.github.com/teriiehina/adfc7198f81be7ad705a4c3913e05dea)

But this is just the unfolding of the `gem` inside the `action`. It could break at any update. A simple way to do it would be for the `gem` to have an option to be called `fastlane style` so that it returns all the infos needed in a `result` object.

I'm sorry I won't have time to propose any PR for this. But maybe someone is interested or already working on a similar case.

**Comment by TKBurner** [comment]
@teriiehina Interesting idea! I'm going to leave this open and mark it as help wanted. We will see if the community is interested 👍

**Comment by krze** [comment]
This would be handy. I run fastlane via jenkins and found that you can run parallel tests on real devices on one machine using scan. The results within each lane are accurate within each job's terminal output, but the final junit result bundle is a muddle of both lanes together.

If there was a way to fetch results from a lane it would permit parallel tests on real devices in a CI environment
