### ISSUE TITLE
Android sync stops working

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#5033]
Are there any decent docs that describe how to set up an android project using fastlane.  I'm struggling with what I've found so far.  I want to know things like

 * what features are supported in android?
 * what manual steps are required to get a project running?

**Comment by TKBurner** [comment]
Hi @npomfret Thanks for reaching out.

Check out https://github.com/fastlane/fastlane/tree/master/screengrab and https://github.com/fastlane/fastlane/tree/master/supply

Let me know if you have any other questions 👍
