### ISSUE TITLE
[gym] Option to configure/disable xcpretty

### ISSUE THREAD

**Issue by nevir** [fastlane/fastlane#5035]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I would find it useful to be able to disable xcpretty when running `gym`.  The `xcodebuild` action supports this, but gym [currently hard codes `xcpretty`](https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/gym/lib/gym/generators/build_command_generator.rb#L66).  This is problematic for a couple reasons:

* [xcpretty currently swallows script output](https://github.com/supermarin/xcpretty/issues/163), making it very hard to debug gym builds where scripts fail
* No way to change the xcpretty theme (though, I suspect current alternatives aren't useful when running gym)

**Comment by TKBurner** [comment]
@nevir Interesting idea! I'm going to leave this open and mark it as help wanted. I want to see if the community is excited about it before we consider integrating on our end or accepting a PR. Thanks!

**Comment by pylebecq** [comment]
Hello there,
I would love to see this new feature because I need to add some custom options to xcpretty to make it generate a report. 👍

**Comment by NachoSoto** [comment]
I'd love this as well. My team just ran into a problem that took us a while to debug. This was `gym`'s output (via `xcpretty`):
> ❌  error: Failed to read Info.plist of app /Users/NachoSoto/Library/Developer/Xcode/DerivedData/Build/Intermediates/ArchiveIntermediates/Khan Academy/InstallationBuildProductsLocation/Applications/Khan Academy.app (Couldn't load Info dictionary for <DVTFilePath:0x7fd9f76f4650:'/Users/NachoSoto/Library/Developer/Xcode/DerivedData/Build/Intermediates/ArchiveIntermediates/Khan Academy/InstallationBuildProductsLocation/Applications/Khan Academy.app'>)

Without `xcpretty` we see what the problem is immediately:
> Check dependencies
> Code Sign error: No matching provisioning profiles found: This product type must be built using a provisioning profile, however no provisioning profile matching both the identity “iPhone Distribution: Khan Academy (XXXX)” and the bundle identifier “XXX” was found.
>
> ** ARCHIVE FAILED **

**Comment by KrauseFx** [comment]
Great suggestions. Looking into this further, check out [this method](https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/gym/lib/gym/generators/build_command_generator.rb#L73-L79).
You should be able to find the raw build output in `~/Library/Logs/gym/[app-name]-scheme.log` 👍

**Comment by bgannin** [comment]
If no one is actively working on this already I'd like to add it to my 'as time allows' list. 

- add "-disable_xcpretty" optional flag for 'gym' that does what it says on the tin
- add "-xcpretty_formatter" optional parameter for 'gym' that takes a valid path or prints error

**Comment by TKBurner** [comment]
@bgannin Thanks for working with us! Definately submit a PR if you are interested 👍

**Comment by bgannin** [comment]
Additions so far:

1. _-np_ to disable xcpretty entirely
2. _-pf_ which takes a path to a custom formatter
3. _-pt_ to use 'test' format instead of default 'simple' format

Haven't settled on a good way to do reports yet.

**Comment by bgannin** [comment]
Current plan is…

- _-rxml_ for JUnit style XML report, passing an output path optionally
- _-rhtm_ for simple HTML report, passing an output path optionally
- _-rjson_ for JSON complication database, passing an output path optionally

**Comment by bgannin** [comment]
Short options ended up much different… follow along in the PR 😆

**Comment by TKBurner** [comment]
@bgannin Thanks! We'll work with you on the PR 👍

**Comment by bgannin** [comment]
Is there additional work needed or did I just miss this in recent release notes?
