### ISSUE TITLE
snapshot run with CI (jenkins): command not found

### ISSUE THREAD

**Issue by Huan9** [fastlane/fastlane#5036]
- snapshot 1.12.3 
-  I have read the Contribution Guidelines(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I installed Jenkin and snapshot on my Mac. When i integrate Snapshot with Jenkin with command line:

;execute script

snapshot

I got an error: snapshot: command not found

But if I run this in bash window, it just worked. Same issue as in https://github.com/fastlane/fastlane/issues/2629

**Comment by vpolouchkine** [comment]
Have you tried https://github.com/fastlane/fastlane/issues/2629#issuecomment-193509788?

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
