### ISSUE TITLE
[match] Ability to specify a custom keychain

### ISSUE THREAD

**Issue by raven** [fastlane/fastlane#5038]
# Feature request for match

## Ability to specify a custom keychain, instead of the default login keychain. 

I was recently working on a project whereby match was unable to be used easily, because the CI box was configured in a way where we didn't have control over the user account that was performing the build. This user also had their keychain locked by default, and without knowing the users password, we could not unlock the login keychain.

It would be great if we could specify a keychain to be used with match, instead of it only working with the login keychain.

**Comment by vpolouchkine** [comment]
You can specify the keychain using the `--keychain_name` parameter, no?

**Comment by raven** [comment]
Yes, yes you can. I am a numpty. :face_palm:
