### ISSUE TITLE
pilot list throw an error

### ISSUE THREAD

**Issue by cnsdato** [fastlane/fastlane#5043]
### New Issue Checklist

- [x] Updated pilot to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
pilot list throw an error since a few days.

##### Complete output when running pilot, including the stack trace and command used

```
$ pilot list --verbose -u xxxxx
INFO [2016-06-08 08:40:12.38]: Login to iTunes Connect (xxxxx)
INFO [2016-06-08 08:40:15.48]: Login successful
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/client.rb:432:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tunes_client.rb:740:in `testers'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.1/lib/spaceship/tunes/tester.rb:74:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/tester_manager.rb:106:in `list_testers_global'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/tester_manager.rb:87:in `list_testers'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/commands_generator.rb:86:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.46.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/commands_generator.rb:126:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/commands_generator.rb:16:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
I have no fastfile
```

### Environment

pilot version (run `pilot -v`): pilot 1.9.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by vpolouchkine** [comment]
What's the role of the user you're using?

**Comment by cnsdato** [comment]
The user has the "Administrator" role

**Comment by vpolouchkine** [comment]
If you specify an app_id (-a) or apple_id (-p) does the request succeed?

**Comment by cnsdato** [comment]
Right now the same request succeeded: 
`pilot list --verbose -u xxxxx`
May be there was a problem @ Apple on the other day.

**Comment by KrauseFx** [comment]
I just tried this locally for 2 different Apple IDs and it's working fine. Do you have access to another Apple ID to give it a try?

**Comment by cnsdato** [comment]
@KrauseFx: I have tried with 5 different Apple IDs and 2 of them are working and 3 of them not.
The 2 of them which are working have the "Administrator" role in iTunes Connect the 3 of them which are not working only have the "Technical" role.

**Comment by KrauseFx** [comment]
Could you try running 

````
pilot list --verbose -u xxx -a app.identifier
```

I assume if you go to iTunes Connect with your non-admin user, go to Users item and try to list all users, that you can't do that

**Comment by cnsdato** [comment]
@KrauseFx: it looks like it works when using -a app.identifier. Thanks for help.

Maybe the error should be catched with a meaningful error message.

**Comment by KrauseFx** [comment]
Great idea, I provided a PR 👍 https://github.com/fastlane/fastlane/issues/5245
