### ISSUE TITLE
register_devices fails with 403 Forbidden when device_name is in Chinese

### ISSUE THREAD

**Issue by plrthink** [fastlane/fastlane#5045]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When using register_devices action with setting device_names in Chinese, the API endpoint would give
403 Forbidden. 
##### Complete output when running fastlane, including the stack trace and command used

```
➜  fastlane git:(master) ✗ fastlane register_device name:姓名 udid:27b27bb75a94b6c0893aa5cf105e86384b010e91 username:plrthink@gmail.com
[18:16:00]: ------------------------------
[18:16:00]: --- Step: default_platform ---
[18:16:00]: ------------------------------
[18:16:00]: Driving the lane 'ios register_device' 🚀
[18:16:00]: ------------------------------
[18:16:00]: --- Step: register_devices ---
[18:16:00]: ------------------------------
[18:16:10]: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
 caused by register_device
[18:16:10]: Variable Dump:
[18:16:10]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios register_device"}
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby

default_platform :ios

platform :ios do
  before_all do
  end

  desc "register a device on apple dev portal"
  lane :register_device do |options|
    register_devices(
      devices: {
        options[:name] => options[:udid]
      },
      username: options[:username]
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
    puts "#{exception} caused by #{lane}"
  end
end

```

### Environment

fastlane version (run `fastlane -v`): `fastlane 1.94.1`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Yes

**Comment by plrthink** [comment]
also tried pass the encoded utf8 value to the fastlane register_devices action like this: `fastlane register_device name:%E5%A7%93%E5%90%8D  udid:27b27bb75a94b6c0893aa5cf105e86384b010e91 username:plrthink@gmail.com` but get this some error.

howerver, set the value of name to english like `name`, it would successfully register the device.

**Comment by vpolouchkine** [comment]
Are you able to set names in Chinese manually, eg without `fastlane`?

**Comment by plrthink** [comment]
@vpolouchkine Yeah, I can do that in developer portal.

**Comment by mfurtak** [comment]
I am able to reproduce this locally.

**Comment by mfurtak** [comment]
I can confirm that passing the name works from the web interface, but fails from inside of spaceship. Like @plrthink, I also tried a variety of encodings for the data, but none of it was acceptable to Apple's servers.

I'm not sure what else to try right now, so I'll ask for help from the community. The code is here: https://github.com/fastlane/fastlane/blob/0c5917741b4111394ec58c513b6db7d168dd77d1/spaceship/lib/spaceship/portal/portal_client.rb#L251
