### ISSUE TITLE
Does Supply support uploading multiple APKs per release?

### ISSUE THREAD

**Issue by dmfrey** [fastlane/fastlane#5047]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
This is the case where you produce multiple apk's (for instance, 1 for phones/tablets and 1 for android tv).

Can you pass multiple --apk command line arguments?

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):
1.9.4

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by vpolouchkine** [comment]
You can use `--apk_paths` to pass paths to APK files to upload.

**Comment by dmfrey** [comment]
Thank you.
