### ISSUE TITLE
[Pilot] - Error uploading non-bitcode enabled app to iTunes Connect.

### ISSUE THREAD

**Issue by eskerber** [fastlane/fastlane#5049]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

As of the first week of June, Pilot has been failing the upload to iTunes command with an error consistent with the error one would see by leaving the "include bitcode" option checked when an app _is not_ bitcode compliant.

![screen shot 2016-06-08 at 9 58 52 am](https://cloud.githubusercontent.com/assets/75236/15898963/c5189612-2d5f-11e6-8c22-7ea787aa4e03.png)

**Worth noting that I can take the build produced by Fastlane and manually upload it successfully via Xcode using Organizer and unchecking "include bitcode".**

I am of course unfamiliar with the implementation details of Pilot, but it would appear from the surface that the ability of Pilot to automatically handle the appropriate "checked state" of "include bitcode" either stopped working - or is not up to date with the changes rolled out to iTunes Connect last week.

##### Complete output when running fastlane, including the stack trace and command used

```
[23:55:37]: [Transporter Error Output]: ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "XXX.app/Frameworks/Mantle.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(machine code) and arm64(machine code), while the nested bundle Mach-O contains armv7(bitcode and machine code) and arm64(bitcode and machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

[23:55:37]: [Transporter Error Output]: ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "XXX.app/Frameworks/AFNetworking.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(machine code) and arm64(machine code), while the nested bundle Mach-O contains armv7(bitcode and machine code) and arm64(bitcode and machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
private_lane :release do |options|
  gym(
    provisioning_profile_path: 'fastlane/profiles/XXXt_App_Store.mobileprovision',
    configuration: 'Release',
    export_method: 'app-store',
  )

  build_url = bullflight(
    build_prefix: "appStore-",
    bundle_id: "com.xxx.XXX"
  )

  pilot(skip_submission: true, skip_waiting_for_build_processing: true)
  post_message_to_slack("TestFlight", "TestFlight")
end
```

### Environment

fastlane 1.94.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

Yes. rbenv.

ruby 2.3.1p112

**Comment by mcactive** [comment]
Having the same issue...

**Comment by EvilOne** [comment]
I'm also having the same issue.

**Comment by TKBurner** [comment]
@eskerber @mcactive @EvilOne Thanks for reporting this. I've sent it out to the core team and we will follow up on this thread 👍

**Comment by ossmalpha** [comment]
Happened to me as well. In my case, I had some pods installed, that had problems with bitcode. I just reinstalled them and it was working again. 

Then bitcode can be checked, actually it should always be checked (if you want to test with others) ^^

**Comment by keatongreve** [comment]
I'm having this exact same issue, but with `deliver`.

**Comment by Lutzifer** [comment]
could someone label this as "deliver" please?

**Comment by TKBurner** [comment]
@keatongreve Thanks for letting us know. I've bumped the core team about this. Thanks!

**Comment by Gladkov-Art** [comment]
Can confirm @ossmalpha. I have the same issue. My target had bitcode disabled, but all my pods have enabled. So, enabling bitcode for my application target resolved uploading to Itunes Connect issue.

**Comment by eskerber** [comment]
Hey @TKBurner, anything else I can provide?
