### ISSUE TITLE
No way to upload encryption registration number (ERN) PDF with `produce`

### ISSUE THREAD

**Issue by dusek** [fastlane/fastlane#5050]
### Issue Description

`produce` modifies App's entries in Developer Center and iTunes Connect. iTunes Connect includes a section for each app called "Features > Encryption" where developers of apps using encryption (including mere HTTPS) are supposed to upload PDFs from Bureau of Industry and Services with their ERN (Encryption Registration Number), and potentially any other relevant export compliance documentation.

There is currently no documentation with guidance on how to upload such ERN PDF (and perhaps other export compliance documents) with `produce`, requiring one to use the web interface of iTunes Connect instead to do the job.

ERN is required e.g. for any app in App Store that uses HTTPS (which is probably a majority of apps).

**Comment by TKBurner** [comment]
@dusek Hope you are doing well! Thanks for this request. I sent this out to the core team and have marked this as help wanted in case anyone wants to work on this. Thanks!

**Comment by dusek** [comment]
I think I misunderstood how ERN works (I dealt with it for the first time). Now that I uploaded the PDF to the iTunes Connect (App > Features > Encryption > iOS Documentation), after it got approved and I put the relevant key value in my Info.plist, I am no longer asked for it when submitting a new external beta. So I think there is nothing `produce` could do during each submission.

Also getting the ERN from the US Bureau of Industry and Security already requires manual clicking on their website for each new app, so manual steps when first time submitting app to external world (Beta or App Store) cannot be avoided (unless of course produce would like to automate that as well one day - 😄 )

So sorry for the noise.

**Comment by TKBurner** [comment]
@dusek Thanks for following up. That makes a lot of sense. Yes we can't get that number for you and it isn't exposed in the APIs. I'm going to close this out. Hope you have a great week!
