### ISSUE TITLE
Transferring app along with configuration between apple accounts

### ISSUE THREAD

**Issue by wedkarz** [fastlane/fastlane#5054]
### Issue Description
Provide a way to actually transfer app from one account to another (and update all fastlane configs accordingly)

**Use case**:

- You develop app till it's almost ready on your personal account
- You give the app to company you have build app for, but they have their own account and want to pay for subscription as late as possible

**Comment by TKBurner** [comment]
Hi @wedkarz Thanks for following up. This seems like it could be implemented as a plugin. Do you have any interest in submitting a PR? Thanks 👍

**Comment by wedkarz** [comment]
Well I'd love, but currently I have very limited time to learn upskill in ruby and develop plugin. 
Is there any guide to fastlane plugin development? Is plugin just another name for action?

**Comment by TKBurner** [comment]
Hi @wedkarz Thanks for following up. We decided to create a better maintainable system of plugins, check out the info here, #4744 

Hope you have a wonderful day!
