### ISSUE TITLE
[SIGH] Resign using specific keychain

### ISSUE THREAD

**Issue by Jugale** [fastlane/fastlane#5058]
Currently, it is not possible to pass the path of a keychain to `sigh resign`. 

The `resign.sh` script supports a keychain name but simply makes it default.

Add functionality to `sigh-resign` and `resign.sh` so that the path to a keychain file gets passed to `/usr/bin/codesign`

**Comment by asfalcone** [comment]
@Jugale Thanks for submitting the issue. The PR has been reviewed! 👍
