### ISSUE TITLE
SSH logs issue on Jenkins

### ISSUE THREAD

**Issue by nmayafit** [fastlane/fastlane#5062]
### Issue Description
Updated to 1.94.1 with the latest SSH update (@ravron created this PR due to my request).
The logs are not printed live on jenkins console while building, only when step is finished. This was working before the PR when I tested it.

You can look at the minutes difference between the start of the SSH step and the first log output.

##### Complete output when running fastlane, including the stack trace and command used

```
[03:32:40]: -----------------
[03:32:40]: --- Step: ssh ---
[03:32:40]: -----------------
**[03:32:43]**: $ cd /Users/local/Desktop/Shared/automation_mobile ; python flow1.py android FULL TEST /Users/local/Desktop/Shared/automation_mobile/files/TEST/android_1.6.4_9406.apk
**[03:50:16]**: ▸ File class object
[03:50:16]: ▸ File class object
[03:50:16]: ▸ File class object
```

### Environment

fastlane version (run `fastlane -v`): 1.94.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? N

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? N

**Comment by asfalcone** [comment]
tagging @ravron so they can comment on this 👍

**Comment by nmayafit** [comment]
OK, I found the issue.
Jenkins has issues with output buffering to STDOUT and STDERR from scripts, especially Ruby and Python.
What I was trying to do is running a python script in SSH from a Jenkins machine. After lots of trial and error I found out that there is a need to run "python -u" (-u - unbuffered binary stdout and stderr) as Jenkins is trying to minimize the amount of I/O by not flushing after each output.
This one solves the issue.
@asfalcone you can close this one.
Thanks.

**Comment by asfalcone** [comment]
Glad you're up and running @nmayafit 👍

**Comment by ravron** [comment]
Easiest fix ever! 😛
