### ISSUE TITLE
CodeSign exits with status 65

### ISSUE THREAD

**Issue by henriklundstedt** [fastlane/fastlane#5064]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

CodeSign exits with status 65. This issue only occurs when running the fastlane job on Jenkins. If I run locally it works fine. Output summary for cert and sigh is the same. I run the Xcode 7.3.1 on both platforms.

##### Complete output when running fastlane, including the stack trace and command used

CodeSign /Users/buildslave/Library/Developer/Xcode/DerivedData/AppName-erxcjqbwlgtyxzaocvnbmkfzrihb/Build/Intermediates/ArchiveIntermediates/AppName/InstallationBuildProductsLocation/Applications/AppName.app
(1 failure)
ERROR [2016-06-09 13:44:59.87]: [31mExit status: 65[0m

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by alexeychirkov** [comment]
I have the same issue: https://github.com/fastlane/fastlane/issues/4197#issuecomment-224869765

**Comment by TKBurner** [comment]
@henriklundstedt Did you unlock the keychain per @alexeychirkov suggestion? Thanks!

**Comment by henriklundstedt** [comment]
That solved the issue. Thanks!
