### ISSUE TITLE
[Match] Include team_name in provisionning profile

### ISSUE THREAD

**Issue by nicolasbraun** [fastlane/fastlane#5076]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Being on several teams with a wildcard `*`profile, match will generate (for example) a` match Development *` profile for each.

Du to an Xcode bug only one will be listed in the Xcode dropdown menu.

### Possible solution

I suggest we add the team name to the provisionning profile.
Several options :
• Make it an opt-in option
• Add a prefix or suffix option to the match command

**Comment by nicolasbraun** [comment]
As stated by @bassrock on Slack, we might have the same issue once fastlane supports tvOS profiles

**Comment by TKBurner** [comment]
@nicolasbraun Hope you are doing well! I went ahead and sent this out to the core team so we can take a look. Thanks so much for sharing it 👍
