### ISSUE TITLE
[feature] Retrieve/Update current devices list from Apple Developer

### ISSUE THREAD

**Issue by nicolasbraun** [fastlane/fastlane#5077]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Currently the `register_device` action allows to add a single device or upload a CSV file.
To facilitate the transition we could add an action to retrieve the current list (`Spaceship::Device::all) and convert it to the correct CSV format for later update

**Comment by nicolasbraun** [comment]
I am not quite familiar with spaceship but I could give it a try.
This would look like

```ruby


# Connect to spaceship $ spaceship -u username
# Create an instance $ d= spaceship
# Select team : d.select_team
# Retrieve device array = devices = d.device.all

headers = "Device ID\tDevice Name"
csv.write(headers)
devices.each do |d|
  line = line = "#{d.udid}\t#{d.name}" #not sure how to add the tabulation for the csv
  csv.write(line)
end
```

**Comment by TKBurner** [comment]
@nicolasbraun Thanks for reaching out. I think this would work out better as a plugin. https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/plugins/template/README.md.erb

Let me know if you take a crack at it 👍

**Comment by nicolasbraun** [comment]
Hi @TKBurner 

I have seen the you implemented plugins lately but could not find any doc on how to use those (or create one) is there any ?

I would gladly give it a try

**Comment by TKBurner** [comment]
Hi @nicolasbraun Thanks for working with me on these issues. You can find the plugin system information on this thread: https://github.com/fastlane/fastlane/issues/4744

Let me know if you have any questions 👍
