### ISSUE TITLE
[match] Allow fastlane to call the match nuke command

### ISSUE THREAD

**Issue by nicolasbraun** [fastlane/fastlane#5078]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Feature Description

Currently running the `match nuke $type` command seems not possible through Fastlane or is missing documentation

**Comment by KrauseFx** [comment]
Can you share the complete output including the command you run

**Comment by nicolasbraun** [comment]
hello @KrauseFx  thanks for stepping in.

I actually have no idea how I could call this command using the `match` action in its current configuration.
(I could write the command in CLI)

I think the match action is missing maybe a nuke boolean parameter

**Comment by KrauseFx** [comment]
Sorry, I don't understand what you're trying to do, could you clarify?

**Comment by nicolasbraun** [comment]
Sorry, here is a little bit more input about my setup

h2. Setup

• my and my team are on many teams (as an agency)
• I use a JSON configuration file to describe the teams and the available bundles :

```json
[{
	"apple_id": "xx@applidium.com",
	"team_name": "APPLIDIUM",
	"team_id": "xxx",
	"repo": "ssh://git@repos.applidium.net/xxx",
	"branch": "master",
	"app_ids": [{
		"bundle": "*",
		"environments": [
			"development"
		]
	}, {
		"bundle": "com.applidium.app1"
	}, {
		"bundle": "com.applidium.app2"
	}, {
		"bundle": "com.applidium.tvos",
		"platform": "tvos"
	}]
}, {
	"apple_id": "xxx@applidium.com",
	"team_name": "team2",
	"team_id": "xxx",
	"is_enterprise": true,
	"repo": "ssh://git@repos.applidium.net/xxx",
	"branch": "team2",
	"app_ids": [{
		"bundle": "*"
	}, {
		"bundle": "com.team2.xx"
	}]
}]
```

and a quite simple Fastfile to retrieve/renew all assets (very usefull for CI servers) or only specific ones

```ruby
lane :get do |options|
  options[:readonly] = true
  retrieve_assets(options)
end

lane :renew do |options|
  options[:readonly] = false
  retrieve_assets(options)
  puts "🚀🚀🚀🚀 All Done. Do not forget to update the ADDEV udid"
end

private_lane :retrieve_assets do |options|

  password = options[:password] || ENV["FASTLANE_PASSWORD"]
  teams = JSON.parse(open("bundles.json").read)
  teams.each do |team|
    apple_id = team["apple_id"]
    team_name = team["team_name"]
    team_id = team["team_id"]
    is_enterprise = team["is_enterprise"]
    ENV["MATCH_FORCE_ENTERPRISE"]= is_enterprise ? "1" : "0"
    repo = team["repo"] 
    branch = team["branch"] || master
    bundles = team["app_ids"]

    if (options[:team] && options[:team] != team_name)
      puts "Skipping team #{team_name}"
    else
      bundles.each do |bundle|
        app_identifier = bundle["bundle"]
        if (options[:bundle] && options[:bundle] != app_identifier)
          puts "Skipping bundle #{app_identifier}" 
        else
          platform = bundle["platform"] || "ios" # not used yet
          environments = bundle["environments"] || default_environments(is_enterprise)
          environments.each do |environment|
            if (options[:env] && options[:env] != environment)
              puts "Skipping #{app_identifier} for environment #{environment}"
            else
              match(
                git_url: repo,
                git_branch: branch,
                type: environment,
                username: apple_id,
                team_id: team_id,
                team_name: team_name,
                app_identifier: app_identifier,
                shallow_clone: false,
                force_for_new_devices: true,
                readonly: options[:readonly]
              )
            end 
          end
        end
      end
    end
  end
end
```

h2. Feature

I would like to be able to add a lane that would do this

```ruby
lane :nuke do |options|
  #Nuke all stuff for a given team and a given type
````

As far as I know there is no way to call match nuke from the `match`action in fastlane. (or match change_password for that matters) doing something like

```ruby
match(
  action: "nuke",
  ...
)
```

Using CLI my lane would look like

```ruby
lane :nuke do |options|
  # Stuff to retrieve the team config (repo, branch, team, team_id, username)
  cli = "match nuke #{options[:type]} --git_url MY_BRANCH -- git_branch MY_BRANCH -u MY_NAME -b MY_TEAM_ID  -l MY_TEAM_NAME"
  sh(cli)
```

Writing the cli command is super easy (assuming it supports the multi-branch - will test). So this is a suggestion to add this directly in the `match` action

**Comment by TKBurner** [comment]
@nicolasbraun Thanks for following up. You can always ran shell commands with the `sh` action.

Let me know if that simplifies things for you 👍

**Comment by nicolasbraun** [comment]
Ho @TKBurner 
Pretty sure i will work with CLI .It was simply a suggestion for the match action :)

Edit : I tried running CLI but 

```shell
➜  repo git:(master) ✗ match nuke distribution --git_url 'ssh://git@repo'                           
[09:43:11]: Cloning remote git repo...
[09:43:16]: 🔓  Successfully decrypted certificates repo
[09:43:16]: To not be asked about this value, you can specify it using 'app_identifier'
```
It also happens when using match directly.

Match nuke is not suposed to take the `app_identifier` as an argument. Should I fill another issue?

**Comment by TKBurner** [comment]
@nicolasbraun Thanks for following up. Yes please file that as a separate issue so I can send it over the match team. Please include full input and output so we can repro 👍

**Comment by KrauseFx** [comment]
@nicolasbraun Sorry for not following up earlier. Did you create a new issue for this?

**Comment by nicolasbraun** [comment]
Completely forgot, just did it #5776

Thanks
