### ISSUE TITLE
push_to_git_remote option to avoid pushing tags

### ISSUE THREAD

**Issue by dcordero** [fastlane/fastlane#5079]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
At the moment the action `push_to_git_remote` is always pushing tags. It would be useful to have an option to avoid pushing tags in certain scenarios. For example when using Jenkins generating tags for each build that you don't want to keep shared.

### Environment
fastlane 1.94.1

**Comment by TKBurner** [comment]
@dcordero Saw this got merged! Thanks so much for contributing! Hope you have an awesome day! 👍

**Comment by dcordero** [comment]
Thanks a lot @TKBurner 
I wish you also have a great day. 👍
