### ISSUE TITLE
Cannot have access to cross-platform lanes

### ISSUE THREAD

**Issue by Liquidsoul** [fastlane/fastlane#508]
I have set up some cross-platform (aka general) lanes, but I cannot call them.
If I call `fastlane general_lane` I have this error:
`Could not find lane 'ios general_lane'. Available lanes: ios platform_lane, general_lane`

If I call `fastlane` it only prompts me for the ios lane:
```
You must provide a lane to drive. Available lanes:
1) ios platform_lane
```

And the lane `platform_lane` can be called using `fastlane platform_lane` with no error.

Here is the Fastfile used in the examples above
```Ruby
fastlane_version "1.11.0"

default_platform :ios

platform :ios do

  before_all do |lane|
  end

  desc "Do nothing"
  lane :platform_lane do
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
  end

end

desc "General lane."
lane :general_lane do
end
```

**Comment by KrauseFx** [comment]
Thanks for reporting this. Was this introduced with one of the last updates?

**Comment by Liquidsoul** [comment]
I don't think so. I tried with version 1.15.0 and it has the same issue.

**Comment by Liquidsoul** [comment]
The problem seems to come from `default_platform :ios`.
If I remove this I can access all the lanes.
However, I have to be explicit for `ios` lanes (e.g. `fastlane platform_lane`).

**Comment by KrauseFx** [comment]
This is definitely something I want to fix, please remove the `default_platform` for now to make it work, it will probably take a few more weeks until I can get this resolved.

**Comment by Liquidsoul** [comment]
I'll do that. :+1: 
I tried to see if I could make the fix, but I do not feel comfortable enough to make it because of all the potential side effects.

**Comment by KrauseFx** [comment]
Thanks, but you're right, it's code that's very near the core of `fastlane` :+1:

**Comment by Liquidsoul** [comment]
Sorry, I had forgotten I opened this issue.

I made a quick test on version `1.55.0` with this simple `Fastfile`:
```ruby
default_platform :ios

lane :root_build do
  puts "root build lane"
end

platform :ios do

  lane :platform_build do
    puts "ios build lane"
  end
  
end
```

And calling `fastlane root_build`, `fastlane platform_build` or `fastlane ios platform_build` work as expected!

So this issue is resolved :+1:

**Comment by KrauseFx** [comment]
Thanks for updating :+1:
