### ISSUE TITLE
Switching to a different lane does not re-load Appfile

### ISSUE THREAD

**Issue by evilDave** [fastlane/fastlane#5086]
### Issue Description

This is a "re-opening" of #616
I am seeing this problem when I run a CI lane that calls a bunch of different build lanes. I agree with the comment by @humblehacker in the other issue: "I would expect the lane options defined in the AppFile to be respected regardless of how the lane was executed."

I understand that I can just specify the app_identifier in the match or whatever, but is seems like it should just do this already.

**Comment by humblehacker** [comment]
Might not be a perfect solution, but I've worked around this issue by `exec`ing fastlane again from my Fastfile, something like this excerpt:

```ruby
  lane :ci do |options|

    # forward the options
    options = options.to_s.gsub(/[{:\"}]/, "").gsub("=>",":")

    exec ("bundle exec fastlane beta #{options}") if includes_beta_tag
    exec ("bundle exec fastlane app_store #{options}") if includes_release_tag

  end
```

**Comment by KrauseFx** [comment]
Basically looking at https://github.com/fastlane/fastlane/issues/616#issuecomment-143299170, we can't change this behaviour, as it would break existing setups.

**Comment by evilDave** [comment]
You might be able to add this behaviour if you do it with the proviso that parent lane configuration takes precedence over child lane configuration. Anyone who is calling another lane expecting its configuration in Appfile to be ignored will still get the same behaviour as long as the same configuration is done in the parent lane.
Can you show any examples where someone is calling other lanes and "expecting the config in the Appfile to be ignored". Do you have any examples that would break or are you just positing that there might be?

**Comment by TKBurner** [comment]
@evilDave Thanks for following up. I think Felix was referring to the fact there might be apps that have their config setup around the current behavior with or without an understanding of this behavior. They would see a breaking change if we changed this and troubleshooting would be hard. Thanks!

**Comment by evilDave** [comment]
By the way, the ENV stuff seems more like what I was wanting.
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/FAQs.md#multiple-targets-of-the-same-underlying-app
Rather than having multiple lanes I should just have multiple envs. That works quite nicely.
