### ISSUE TITLE
Appfile.md

### ISSUE THREAD

**Issue by zvjerka24** [fastlane/fastlane#5093]
It seems that there is an issue in documentation for fastlane/fastlane/docs/Appfile.md

At the end it says
> 
> Therefore, while driving the :beta lane, this configuration is loaded:
> 
> app_identifier "net.sunapps.1.beta"
> apple_id "felix@krausefx.com"
> team_id "Q2CBPJ58CC"

I think team_id should be '123', since we're driving different lane not different platform.

**Comment by vpolouchkine** [comment]
Yup, looks like you're right. Thanks!

**Comment by KrauseFx** [comment]
I noticed that the `:beta` lane isn't even listed in `Appfile.md`, did this get removed? @vpolouchkine what's the status on this?
