### ISSUE TITLE
latest_testflight_build_number specify version number

### ISSUE THREAD

**Issue by sasal** [fastlane/fastlane#5098]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines]

### Issue Description
When uploading a new version number to iTunes connect we use the latest_testflight_build_number  on jenkins in our fast lane file however since it is a new version number it cannot find a build number in connect. I tried specifying the version number in the function:

latest_testflight_build_number(version: '4.1.4') but it still prompts for "You have to specify a new version number: " 

When I commit a new version number I want Jenkins to be able to check if the version number has been uploaded to connect yet and if not use version number in the Xcode project and start the build number at 1.

Fast lane: 

 desc "Build Production App and Upload to Connect using Delivery metadata"
   lane :ProdBuildUpload do
    cert
    sigh
    increment_build_number(xcodeproj: 'my.xcodeproj', build_number:                                                                  latest_testflight_build_number(version:'4.1.4') + 1)
    gym(scheme: "STORE", workspace: "path.xcw$
    deliver
   end

**Comment by TKBurner** [comment]
Hi @sasal Thanks for reaching out. Can you share the full output from when you run this lane? That'll help with looking into it. Thanks!
