### ISSUE TITLE
Need help setting up new android test case for screengrab

### ISSUE THREAD

**Issue by kd8ssq** [fastlane/fastlane#5104]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I'm struggling to figure something out and I'm hoping someone can help me.  I need some help figuring out where to define a test case for android.  I can see the example test case at https://github.com/fastlane/fastlane/tree/master/screengrab#ui-tests, but I just don't seem to understand where you place the test case file and where you're supposed to define what test case to use.  Are you supposed to define it in the build.gradle file or are you supposed to define it in the manifest.xml file?  

Any help would be greatly appreciated.

Thanks,

Adam

**Comment by vpolouchkine** [comment]
Did you checkout the example project? https://github.com/fastlane/fastlane/tree/master/screengrab/example

**Comment by kd8ssq** [comment]
I did, and while it's a good example of the directory structure, I still can't find out where do you tell the app to reference the test cases?
