### ISSUE TITLE
fastlane_core and krausefx-shenzen version conflict

### ISSUE THREAD

**Issue by davidrothera** [fastlane/fastlane#5108]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
[drothera@drothera-mbp SugarFix]$ (master) fastlane ios fabricbeta
/Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate fastlane_core-0.46.3, because commander-4.4.0 conflicts with commander (= 4.3.5) (Gem::ConflictError)
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1408:in `activate'
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1428:in `each'
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1410:in `activate'
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:279:in `block in activate_bin_path'
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:279:in `synchronize'
	from /Users/drothera/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems.rb:279:in `activate_bin_path'
	from /Users/drothera/.rvm/gems/ruby-2.2.1/bin/fastlane:22:in `<main>'
	from /Users/drothera/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/drothera/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
n/a
```

### Environment

fastlane version (run `fastlane -v`): Unable to run

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by davidrothera** [comment]
Shenzen was update 5 hours ago to use a new version of commander: https://github.com/fastlane/shenzhen/commit/3f1d8e012429868624309203fecb09c1a4f03f56

This version is a mismatch to the one required in `fastlane_core`

**Comment by flaushi** [comment]
same problem here

**Comment by KrauseFx** [comment]
@neonichu is on it 🚀 cc @ohwutup

**Comment by ohwutup** [comment]
Sorry for the issue @davidrothera ! We reverted that commit, so things should be 💯 now!
