### ISSUE TITLE
update_project_team fails unless team has been set first

### ISSUE THREAD

**Issue by mosesoak** [fastlane/fastlane#5109]
This line (`gsub(/DevelopmentTeam...`) assumes a `DevelopmentTeam` exists https://github.com/fastlane/fastlane/blob/9c0494ef5e7d71afc51c73fe0b141b02e8991d9c/fastlane/lib/fastlane/actions/update_project_team.rb#L15

But new projects with Team is set to 'None' don't have that key, e.g.:
```
				TargetAttributes = {
					0A1CA8F01D0B76B8005D5B89 = {
						CreatedOnToolsVersion = 7.3.1;
					};
				};
```

Projects created with an older version of Xcode, e.g. a freshly initialized React Native project which uses a stale project, the app target is not present. In that case the main app target needs to be looked up, something like this (I'm not a Ruby programmer...)

```ruby
main_target = xcproj.targets.find { |t| t.name == project_name }
main_target_uuid = main_target && main_target.uuid
if main_target_uuid
  # add to TargetAttributes with the uuid as the key and DevelopmentTeam inside
end
```

I realize that this is due to limitations in the `xcodeproj` gem, and I've submitted a sister issue there, but they have over 30 open issues so it's not likely that there will be a quick solution on their side.

For now, I'll do my own gsub on the project file and avoid `update_project_team`... thanks!

**Comment by TKBurner** [comment]
Hi @mosesoak! Hope you are doing well. Are you interested in submitting a PR about this? That'd be 💯

**Comment by mosesoak** [comment]
from the convo at the thread linked just above this post, it seems Xcode might make the attribute mandatory in the near future which would make this problem go away on its own.
