### ISSUE TITLE
check version and build numbers before ipa is uploaded

### ISSUE THREAD

**Issue by akaralar** [fastlane/fastlane#5114]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When uploading an ipa to testflight, the ipa gets rejected if the uploaded version is not ahead of the version at testflight. That means it will be rejected when both `build number` and `version number` is the same or less than testflight version, but the rejection happens after the ipa is uploaded to testflight, which means towards the end of a lane. It would be really useful if only there were an action like `ensure_git_status_clean`, ie `ensure_build_is_ahead_of_testflight` that we will invoke at the start, so that we don't compile and link and upload only to see we forgot to change the build number.

I know there are build and version incrementing actions but they might result in redundant increments if the lane fails after the increment is invoked.

Is there any way to achieve this currently with fastlane?

##### Complete output when running fastlane, including the stack trace and command used

```
No output
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
Not applicable
```

### Environment

fastlane version (run `fastlane -v`):
1.95
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by vpolouchkine** [comment]
That would be a pretty useful addition. 💯

**Comment by sbhklr** [comment]
@akaralar Is there already an action to increment / set the app version in iTunes connect? So far I always had to create a new app version manually by logging into ITC.

**Comment by akaralar** [comment]
@sbhklr yeah you can check actions here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

**Comment by sbhklr** [comment]
@akaralar Thank you for your reply. I checked there already. I found `increment_version_number` which only increments the version number in the Xcode project. Neither `pilot` nor `deliver` provides such an option. Which action do you use for this purpose?

**Comment by akaralar** [comment]
@sbhklr 

### `latest_testflight_build_number`

Fetches most recent build number from TestFlight based on the version number. Provides a way to have `increment_build_number` be based on the latest build you uploaded to iTC.

```ruby
latest_testflight_build_number(version: "1.3")
```

can be used in combination with `increment_build_number`

```ruby
increment_build_number({
  build_number: latest_testflight_build_number + 1
})
```

**Comment by sbhklr** [comment]
@akaralar Thx bud. Hmm, what I want to do is increment the version number in Xcode and let fastlane check if there is such a version in ITC. If not, create it. If there is for example no version 1.3.0 set up in ITC and I try to upload a build containing this number to TestFlight, it will be rejected.

**Comment by qimingweng** [comment]
iTunesConnect doesn't let you upload a new build number to an existing version number that exists in the app store.

Is there a way to somehow capture that in fastlane?
