### ISSUE TITLE
Error in fastlane init. Your account is in no teams

### ISSUE THREAD

**Issue by ahmed1490** [fastlane/fastlane#5115]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Error in fastlane init. Your account is in no teams

##### Complete output when running fastlane, including the stack trace and command used

<img width="1106" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/15986709/2bccb332-300f-11e6-9a14-36f91569267c.png">

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
app_identifier "com.kello.app" # The bundle identifier of your app
apple_id "kello@gmail.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by TKBurner** [comment]
Hi @ahmed1490! Hope you are doing well. Are you part of a team in Apple Developer Portal? Can you try manually setting the value in the Fastfile and see if that clears things up? Thanks!

**Comment by theothertomelliott** [comment]
I was seeing this error today and it turned out to be because the account I was using (which I'd just set up specifically for fastlane) had passed the grace period and the e-mail address needed verifying.

If you don't have this Apple Id set up in XCode, trying to add it there might give a clearer error.

**Comment by ahmed1490** [comment]
I wasnt part of team in Apple Developer Portal. This was my mistake!

**Comment by TKBurner** [comment]
@ahmed1490 Glad to hear you got up and running. Hope you have a wonderful day! 👍
