### ISSUE TITLE
Deliver fails with "Invalid provisioning profile"

### ISSUE THREAD

**Issue by trustyfrog** [fastlane/fastlane#5127]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have created a generic/template XCode project so the same project can be used for different bundle/app IDs for different purposes. The idea is that a newly configure app is config-driven from the get-go.

I'm getting this message when fastlane uploads to iTC:

`Transporter Warning Output]: WARNING ITMS-90159: "Invalid provisioning profile. This app contains an embedded provisioning profile that is not associated with your account. Please use a provisioning profile associated with Team ID XXXXXXXXXX."`

Using custom variables for team_id, app_identifier, app_name, etc my flow goes like this:

update_project_team(...)
update_info_plist(...)
match(..., type: "appstore", ...)
gym(...)
deliver(...)

The original project settings from the template are very vanilla; I haven't set the team, code signing, provisioning profile or any other specific settings apart from the Release provisioning profile which is set to $(sigh_BUNDLEID>adhoc). (I had to set this manually to see if this would make the solve the issue, but it made no difference.)

Is there something else I need to do?

##### Complete output when running fastlane, including the stack trace and command used

```
[16:13:50]: Going to upload updated app to iTunes Connect
[16:13:50]: This might take a few minutes, please don't interrupt the script
[16:14:20]: [Transporter Warning Output]: WARNING ITMS-90159: "Invalid provisioning profile. This app contains an embedded provisioning profile that is not associated with your account. Please use a provisioning profile associated with Team ID XXXXXXXXXX."
[16:14:20]: iTunes Transporter successfully finished its job
[16:14:20]: WARNING ITMS-90159: "Invalid provisioning profile. This app contains an embedded provisioning profile that is not associated with your account. Please use a provisioning profile associated with Team ID XXXXXXXXXX."
[16:14:20]: ------------------------------------------------------------------------------------------------------
[16:14:20]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[16:14:20]: ------------------------------------------------------------------------------------------------------
[16:14:20]: Finished the upload to iTunes Connect```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Embedded in issue

### Environment

fastlane version (run `fastlane -v`): 1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by nicolasbraun** [comment]
Did you use `$(sigh_BUNDLEID>adhoc)`or `$(sigh_BUNDLEID_adhoc)` ? 
The second one is the correct one.

Furthermother your Fastfile builds `match`using `appstore` for the `type` param so there is a mismatch here. Make sure you align all the planets and use `$(sigh_BUNDLEID_appstore)` for the Xcode configuration you are trying to build

**Comment by trustyfrog** [comment]
Sorry, @nicolasbraun that was a typo.

It turns out my build order wasn't quite right. I wasn't actually matching before the gym. Correcting this saw the true error appear and it's because I need to make my $(sigh_BUNDLEID_adhoc) actyally use the bindle ID for the specific app I'm building.

This last bit I need to do dynamically.

**Comment by nicolasbraun** [comment]
👍  you can close this issue if this is all OK now

**Comment by trustyfrog** [comment]
Just in case it helps anyone, I use this code for my scenario:

```
        target_filter = "ClientApp"
        config_filter = "Release"

        project = Xcodeproj::Project.open("ClientApp.xcodeproj")
        project.targets.each do |target|
            
            if target.name != target_filter
                break
            end
            
            puts target.name
            
            target.build_configurations.each do |config|
                if !config.name.match(config_filter)
                    next
                end
                
                config.build_settings["PROVISIONING_PROFILE"] = "$(sigh_#{app_identifier}_appstore)"
                #puts config.build_settings["PROVISIONING_PROFILE"]
            end
            
        end

        project.save()
```

Please excuse the quality of ruby.
