### ISSUE TITLE
Feature Request: Print a PDF

### ISSUE THREAD

**Issue by ogezue** [fastlane/fastlane#5131]
Wouldn't it be great if snapshot could create a pdf in a mail compatible file size that could be send to the business? Unfortunately the pages get cropped I I print the html-file as a pdf.

**Comment by vpolouchkine** [comment]
Good idea, keeping this open for upvotes.

**Comment by KrauseFx** [comment]
We generated a PDF in the past, but had troubles with encoding and file size, so we decided to stick with HTML reports. 
I don't know why things get cropped, have you tried a different browser? 👍

**Comment by ogezue** [comment]
I have round about 50 screenshots per device and tried it with Chrome, Firefox and Safari. All of them crop the images if I print it as PDF.
