### ISSUE TITLE
Remote actions can't be used in remote Fastfile when imported

### ISSUE THREAD

**Issue by richsage** [fastlane/fastlane#5132]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a very basic remote Fastlane repository, with a single dummy lane in (called `dummy`), and a single custom action (`wo_project_config_file`). The remote Fastfile references this custom action. Running `fastlane dummy` on a clone of the remote repo uses my custom action as expected. I'd like to also be able to use this custom action in a local Fastfile.

If I import the remote repository into a local Fastfile using `import_from_git`, and attempt to use the custom action in the same way, Fastlane tells me that the action could not be found.

Poking around a bit, it seems that Fastlane [tries to parse the remote Fastfile first](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/fast_file.rb#L193-L197), before importing the actions. So the custom action can't be found when the parse is carried out. Moving the action import lines to before the `parse` line however gives me:

```
[10:15:24]: Clearing the git repo...
[10:15:24]: $ rm -rf '/var/folders/b9/j9f2wfs95gl77hbq0k97dzgh0000gn/T/fl_clone20160615-6921-1pql65q'
Fastfile:5:in `parsing_binding': [!] uninitialized constant Fastlane::FastFile::WoProjectConfigFileAction (NameError)
```

So I'm a bit lost as to what to do here! I'd like to keep it as an action if possible, and the Advanced docs certainly suggest this is doable.

##### Complete output when running fastlane, including the stack trace and command used

```
[rich@mbp:~/projects/test] (master %)$ fastlane dummy
[10:24:29]: -----------------------------
[10:24:29]: --- Step: import_from_git ---
[10:24:29]: -----------------------------
[10:24:29]: Cloning remote git repo...
[10:24:29]: $ git clone 'file:///Users/rich/projects/wo-fastfile' '/var/folders/b9/j9f2wfs95gl77hbq0k97dzgh0000gn/T/fl_clone20160615-7101-wk60gz/wo-fastfile' --depth 1 -n
[10:24:29]: ▸ Cloning into '/var/folders/b9/j9f2wfs95gl77hbq0k97dzgh0000gn/T/fl_clone20160615-7101-wk60gz/wo-fastfile'...
[10:24:29]: $ cd '/var/folders/b9/j9f2wfs95gl77hbq0k97dzgh0000gn/T/fl_clone20160615-7101-wk60gz/wo-fastfile' && git checkout HEAD 'fastlane/Fastfile'
[10:24:29]: $ cd '/var/folders/b9/j9f2wfs95gl77hbq0k97dzgh0000gn/T/fl_clone20160615-7101-wk60gz/wo-fastfile' && git checkout HEAD 'fastlane/actions'

[!] Could not find action or lane 'wo_project_config_file'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Remote Fastfile (in `fastlane/Fastfile`):
```ruby

wo_project_config_file 'config.yml'

before_all do
  project_config = read_config(wo_project_config_file)
end

lane :dummy do
  puts "Hello, world"
end

def read_config(config_file)
  # TODO
end
```

Remote custom action (in `fastlane/actions/wo_project_config_file.rb`):
```ruby
module Fastlane
  module Actions
    module SharedValues
      WO_PROJECT_CONFIG_FILE = :WO_PROJECT_CONFIG_FILE
    end

    class WoProjectConfigFileAction < Action
      def self.run(params)
        params = nil unless params.kind_of? Array
        value = (params || []).first
        Actions.lane_context[SharedValues::WO_PROJECT_CONFIG_FILE] = value
      end

      #####################################################
      # @!group Documentation
      #####################################################

      def self.description
        "Project configuration file setting"
      end

      def self.details
      end

      def self.available_options
      end

      def self.output
      end

      def self.return_value
      end

      def self.authors
        ["richsage"]
      end

      def self.is_supported?(platform)
        true
      end
    end
  end
end
```

Local Fastfile:
```ruby
import_from_git(
  url: "file:///Users/rich/projects/wo-fastfile"
)

wo_project_config_file 'my-config.yml'
```

### Environment

fastlane version (run `fastlane -v`): 1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? RVM

**Comment by KrauseFx** [comment]
Could you move the call to the custom action inside the `before_all` block? That should solve your problem 👍

**Comment by richsage** [comment]
Ah - perfect, thanks! 👍  I might submit a docs PR for that clarification :-)
