### ISSUE TITLE
Fastlane and RSA key

### ISSUE THREAD

**Issue by bhavinmdesai** [fastlane/fastlane#5133]
I have a RSA key that I want Fastlane to use for reading and writing to a bitbucket repo of iOS app certificates. Can someone please help how can I do that ?

**Comment by vpolouchkine** [comment]
Can you describe your setup in a bit more detail? Which tools within `fastlane` do you want to use?

**Comment by bhavinmdesai** [comment]
I am using fastlane on Buildkite. I have setup SSH key on my buildkite
agents which has read-only access to all the Bitbucket repos.

Fastlane needs write access as well to manage provisioning profiles and
other certificates. To overcome this problem, our devops created another
user which has a write access to just one repo and he gave me RSA key.

Now I am not sure how can I use that RSA key with fastlane so that it can
read-write to the ios certificate repo.

Please help.
Thanks

**Comment by rameshprajapati27** [comment]
How can we use RSA key in conjunction with fastlane file?
Is there any way to use RSA key to deploy in bitbucket repos using fastlane actions?

**Comment by vpolouchkine** [comment]
Apologies for the late reply. I spoke with the team and looks like this is not something we support as of today.
