### ISSUE TITLE
Flag for considering "ERROR ITMS-90189: Redundant Binary Upload" a success

### ISSUE THREAD

**Issue by dral3x** [fastlane/fastlane#5137]
Hi there,
back in the days there was a flag for considering this ITMS error a success of the process.

Is it possible to re-introduce it? It would make my setup more stable if I run the lane more times with the same IPA.

What do you think?
Thanks

**Comment by vpolouchkine** [comment]
Is this for `spaceship`? What was the flag's name?

**Comment by dral3x** [comment]
Can't remember really. I recreate my Deliverfile last week because it was very old.
It was in `deliver`, not spaceship.

Maybe I introduced it myself just to make our deploy script more robust (in that case sorry).
I still think that could be useful having a flag for that for come CI workflow (like ours).

Thanks

**Comment by vpolouchkine** [comment]
Gotcha. This is not something we're currently looking at, but I'll keep this thread open to see if there is more interested in this functionality.

**Comment by dral3x** [comment]
It will be a "nice to have" feature. We can work without it :)

**Comment by TKBurner** [comment]
@dral3x Thanks! We had to do some housekeeping 👍
