### ISSUE TITLE
[install_xcode_plugin] optional hash to verify download integrity

### ISSUE THREAD

**Issue by bootstraponline** [fastlane/fastlane#5138]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Feature request. Optionally allow providing a hash to `install_xcode_plugin` so people can't silently override a zip on github and pwn everyone...

https://github.com/fastlane/fastlane/pull/4911

**Comment by bootstraponline** [comment]
Or a better idea, a way to digitally sign & verify releases.

> https://github.com/blog/2144-gpg-signature-verification

**Comment by vpolouchkine** [comment]
Keeping this open for upvotes. 👍

**Comment by bootstraponline** [comment]
Homebrew has a nice syntax for this. Probably more realistic than expecting people to sign releases.


> url "https://downloads.sourceforge.net/project/libbinio/libbinio/1.4/libbinio-1.4.tar.bz2"
> sha256 "4a32d3154517510a3fe4f2dc95e378dcc818a4a921fc0cb992bdc0d416a77e75"
>
> https://github.com/Homebrew/homebrew-core/blob/bb651b73ddf233121d7c72e05ef0c9ecb661c4de/Formula/libbinio.rb#L5

**Comment by KrauseFx** [comment]
Thanks for the idea @bootstraponline. As you know Xcode plugins are soon officially deprecated with the new Xcode, so we don't plan on investing more time into extending this action. Let's close this for now 👍
