### ISSUE TITLE
How do I see the notified date for a testflight user?

### ISSUE THREAD

**Issue by jeremiahScribblePost** [fastlane/fastlane#5139]
TestFlight's external testers list has a field: "Notified May 18, 2016" which shows for any users that have never installed the app.

Fastlane Pilot tells me when each user installed the app, but nothing for the users who have never installed. 

How can I see this date? It is useful knowing which users have been on TestFlight for 3 months and never installed the app.

By the way thanks for creating this package, you have saved me dozens of man hours in the last few months.

**Comment by vpolouchkine** [comment]
I don't believe that data is exposed via `pilot`.
