### ISSUE TITLE
OSX install fastlane failed

### ISSUE THREAD

**Issue by playing** [fastlane/fastlane#5141]
- OSX: 10.11.5
- ruby: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

```
➜  ~ sudo gem install fastlane
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane_core requires commander (= 4.3.5)
```

seem like fastlane require commander>= 4.4 bug fastlane_core requires commander = 4.3.5?

**Comment by vpolouchkine** [comment]
See https://github.com/fastlane/fastlane/issues/3966#issuecomment-202917773 Let's track the convo there.
