### ISSUE TITLE
Per-lane Gym export_method?

### ISSUE THREAD

**Issue by TiagoVeloso** [fastlane/fastlane#5142]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is it possible to have a `Gymfile` configuration per lane?
I need to set the export method on a per-lane basis, can I do that with the `Gymfile`, or the `Appfile`

### Environment

fastlane version (run `fastlane -v`):
1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
`bundle exec fastlane`

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
 `rbenv`

🔑

**Comment by vpolouchkine** [comment]
Unfortunately, no. You'd have to pass values using environment variables, see `gym help`.
