### ISSUE TITLE
add unzip lane

### ISSUE THREAD

**Issue by punksta** [fastlane/fastlane#5144]
### New Issue Checklist

- [+ ] Updated fastlane to the latest version
- [+ ] I have read the [Contribution Guidelines]

We have zip action for zip files, but have no unzip action

I want add something like this:
```
lane :unzip_file do |options|
    require 'zip'
    require 'ruby gems'
    file = options[:file]
    destination = options[:path]
    Zip::File.open(file) do |zip_file|
      zip_file.each { |f|
        f_path=File.join(destination, f.name)
        FileUtils.mkdir_p(File.dirname(f_path))
        zip_file.extract(f, f_path) unless File.exist?(f_path)
      }
    end
  end
```

**Comment by vpolouchkine** [comment]
It would be great if you could use the new plugin system for this, see https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md 👍

**Comment by suculent** [comment]
Or call sh "unzip ..." and save some lines of code.
