### ISSUE TITLE
Use result of gym when using scan with skip_build: true

### ISSUE THREAD

**Issue by nvh** [fastlane/fastlane#5147]
It would be great if it was possible to use the result from `gym` when using `scan` with `skip_build: true`.

Currently it is possible to let them share a derived_data folder, which helps, but isn't exactly the same thing.

There are some new features in xcodebuild of Xcode 8 (mentioned in [Advanced Testing and Continuous Integration](https://developer.apple.com/videos/play/wwdc2016/409/)) that could help with this (`build-for-testing` and `test-without-building`), but it would be great if it could work in Xcode 7 as well.

**Comment by vpolouchkine** [comment]
Keeping this open for upvotes. 👍
