### ISSUE TITLE
install sigh error

### ISSUE THREAD

**Issue by shuijinliuxi** [fastlane/fastlane#5154]
The error is ：

PDhouse-Macbook-Pro:~ xxx$ sudo gem install sigh
Password:
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/commander

**Comment by muzoman** [comment]
Yep, same error here. How is this fixed?

**Comment by muzoman** [comment]
Having dug around. This is a duplicate of issue 567. The following install worked:

 sudo gem install -n /usr/local/bin snapshot

**Comment by vpolouchkine** [comment]
@shuijinliuxi Does that help ^^?

**Comment by shuijinliuxi** [comment]
It is right. tks ^-^
