### ISSUE TITLE
Support for TPA beta distribution

### ISSUE THREAD

**Issue by mbogh** [fastlane/fastlane#5157]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

At work we use Fastlane and TPA and would like to have direct support for TPA in Fastlane.
I have submitted a PR #5156

**Comment by TKBurner** [comment]
Hi @mbogh Thanks for reaching out. I'm glad to hear you are checking out the plugins system. Let us know how it goes! 👍
