### ISSUE TITLE
Snapshot not working in localized versions

### ISSUE THREAD

**Issue by tattva20** [fastlane/fastlane#5161]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to use Snapshot to create screenshots from my app in all it's localized versions, but it only opens the english version of the app, the app is already internationalized and localized for both spanish and english, when I build it using the scheme configured for the Spanish language and Mexico as the region it works properly and all the strings are in spanish but when I run snapshot I only get english text, although according to Snapshot the Spanish version should have opened:

[15:20:04]: --------------------------
[15:20:04]: --- iPhone 4s - es-ES  ---
[15:20:04]: --------------------------

Any fix to this issue?

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:

# A list of devices you want to take the screenshots from
 devices([
  "iPhone 6",
   "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
#  "iPad Retina",
#   "iPad Pro"
])

languages([
  "en-US",
  "es-ES ",
#  "de-DE",
#  "it-IT",
#  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "appname"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
project "./appname.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help

### Environment

fastlane version (run `fastlane -v`):

Fastlane 1.94

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No

**Comment by tattva20** [comment]
Found the solution:

After this argument in my UITests file

 private let app = XCUIApplication()
       
    override func setUp() {
        super.setUp()
        app.launchArguments += ["UI-Testing"]
        setupSnapshot(app)
        app.launch()

I had this argument

XCUIApplication().launch()

this argument was overriding the language in the simulator, removing it took care of the problem.

**Comment by TKBurner** [comment]
@tattva20 Awesome! Really glad to hear you got up and running. Hope that you have a wonderful day! 👍

**Comment by tattva20** [comment]
@TKBurner Thank you so much! Now everything is running smoothly and fastlane is working perfectly, have a wonderful week!
