### ISSUE TITLE
Gym hangs with Xcode 8

### ISSUE THREAD

**Issue by IngmarStein** [fastlane/fastlane#5163]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The project https://github.com/IngmarStein/Kraftstoff/tree/swift3 ([Travis output here](https://travis-ci.org/IngmarStein/Kraftstoff/builds/138674606)) hangs with fastlane 1.95.0 and Xcode 8 at the `xcrun xcodebuild -list` stage.

The command succeeds when run directly from the command line:
```
$ xcrun xcodebuild -list -project ./Kraftstoff.xcodeproj
Information about project "Kraftstoff":
    Targets:
        Kraftstoff
        Kraftstoff Tests
        Kraftstoff UI Tests

    Build Configurations:
        Debug
        Release

    If no build configuration is specified and -scheme is not passed then "Release" is used.

    Schemes:
        Kraftstoff
        Kraftstoff UI Tests
```

When I xcode-select Xcode 7.3.1, gym proceeds as normal.

##### Complete output when running fastlane, including the stack trace and command used

```
$ bundle exec gym --scheme Kraftstoff
[13:05:22]: xcrun xcodebuild -list -project ./Kraftstoff.xcodeproj
2016-06-19 13:05:24.945 xcodebuild[6388:217906] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11130.20/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:286
Details:  Failed to expand identifiers "{(
    "iCloud.$(CFBundleIdentifier)"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7f9006bc90c0>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7f9001514750>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-06-19 13:05:24.968 xcodebuild[6388:217906] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11130.20/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:286
Details:  Failed to expand identifiers "{(
    "iCloud.$(CFBundleIdentifier)"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7f9006bc90c0>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7f9001514750>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
```

### Environment

fastlane version (run `fastlane -v`): 1.95.0
gym version: 1.6.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by lyndsey-ferguson** [comment]
I get this issue as well and was about to ask the same question. It runs fine after I `xcode-select` the Xcode-beta.app and run the `xcrun xcodebuild -list` command from the Terminal. When `gym` runs it, it hangs indefinitely.

**Comment by vpolouchkine** [comment]
Thanks for the reports!

**Comment by cuva** [comment]
Same issue here running `1.96.0` w/ `bundler` and via `rbenv` when running the `scan` command.

Running `xcrun xcodebuild -list -project ...` manually seems to return fine.

**Comment by ansonLS** [comment]
I am also having the exact same issue @lyndsey-ferguson is having.

**Comment by IngmarStein** [comment]
The issue persists with Xcode 8 Beta 2.

**Comment by IngmarStein** [comment]
Here's the command that actually produces the error:

```xcodebuild -showBuildSettings -scheme … -project …```

**Comment by lyndsey-ferguson** [comment]
@IngmarStein nice find

**Comment by Hoderu** [comment]
Hi! I get this issue after command:
xcodebuild -workspace LingvoLive.xcworkspace -scheme LingvoLive -configuration AdHoc -sdk iphoneos10.0
I use Xcode-beta.app
Help to fix it. Thank you!

> 2016-07-12 06:31:35.676 xcodebuild[19450:7323578] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11130.20/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
[06:31:35][Step 13/22] Details:  Failed to expand identifiers "{(
[06:31:35][Step 13/22]     "group.com.abbyy.lingvolive"
[06:31:35][Step 13/22] )}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
[06:31:35][Step 13/22] Object:   <Xcode3TargetCapabilitiesContext: 0x7fd0c3ec0180>
[06:31:35][Step 13/22] Method:   -_appIDFeatureStateIncludingEntitlements:
[06:31:35][Step 13/22] Thread:   <NSThread: 0x7fd0c0404f80>{number = 1, name = main}
[06:31:35][Step 13/22] Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
[06:31:35][Step 13/22] 2016-07-12 06:31:35.682 xcodebuild[19450:7323578] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11130.20/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
[06:31:35][Step 13/22] Details:  Failed to expand identifiers "{(
[06:31:35][Step 13/22]     "group.com.abbyy.lingvolive"
[06:31:35][Step 13/22] )}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
[06:31:35][Step 13/22] Object:   <Xcode3TargetCapabilitiesContext: 0x7fd0c3ec0180>

**Comment by KonradCLAPP** [comment]
I'm having same issue while running on Travis CI(using the latest image : osx_image: xcode8). Locally everything is working fine. 

Is there any workaround to make it work? Can you pleas tell me when Can I expect this to be fixed?

**Comment by IngmarStein** [comment]
In case anyone else wants to have a temporary workaround (probably until Xcode 8 Beta 3 is release tomorrow), here's what I did:

- removed the Core Data model from my project
- ran xcodebuild -showBuildSettings to get working settings
- created a shell script named `xcrun` with the following content:
```
if [ "$1 $2" == "xcodebuild -showBuildSettings" ]; then
	echo <<EOF
	<Working build settings>
EOF
else
	/usr/bin/xcrun "$@"
fi
```
- set PATH environment variable so that this script precedes `/usr/bin/xcrun` (e.g. in .travis.yml)

**Comment by TKBurner** [comment]
Hi @IngmarStein There is a PR in place that fixes this issue. It will be merged into master shortly 👍

**Comment by IngmarStein** [comment]
If you mean https://github.com/fastlane/fastlane/pull/5188, it probably is a different issue. Xcode 8 always hangs at showBuildSettings for projects with Core Data models.

**Comment by TKBurner** [comment]
@IngmarStein Thanks for following up.  I'm looping in the core team so we can investigate. 👍

**Comment by IngmarStein** [comment]
I'm curious if you can find a solution to this. I guess it's just a bug in xcodebuild which hopefully will be fixed in the final Xcode 8 release.

**Comment by IngmarStein** [comment]
Unfortunately, the bug is still present in Xcode 8 Beta 4 :(

**Comment by pronebird** [comment]
Xcode 8 beta 4 prints "Failed to expand identifiers" however it proceeds to build the app and seems to be working. Is it some caching issue because I don't see how it can expand already expanded identifiers.

**Comment by TKBurner** [comment]
@pronebird Thanks for sharing this. We are looking into Xcode 8 support and gradually making PRs across the board. If you have any other insights or are interested in working on a PR let me know! Thanks 👍

**Comment by zqxiaojin** [comment]
Unfortunately, the bug is still present in Xcode 8 Beta 6 :(

**Comment by TKBurner** [comment]
@zqxiaojin Thanks for letting us know. We are working on Xcode 8 support. Thanks!

**Comment by appsandwich** [comment]
With GM date fast approaching, is there a timeline for when Xcode 8 will be supported?

**Comment by TKBurner** [comment]
@appsandwich Are you still running into issues with gym on Xcode 8? Thanks for letting me know.

**Comment by IngmarStein** [comment]
@TKBurner the bug hasn't been fixed with gym 1.8.0. Projects with Core Data models still hang at `xcodebuild -showBuildSettings`.

**Comment by TKBurner** [comment]
@IngmarStein Just followed up with the core team. We'll look into this. Thanks and hope you have a wonderful weekend!

**Comment by appsandwich** [comment]
@TKBurner Thanks, it's the same problem as the root issue - fastlane hangs at xcrun xcodebuild -list

**Comment by ctaclas** [comment]
I also have this issue. I find that if I kill the fastlane process with ctrl-c and retry it I can sometimes get it to run to completion. It's an ok workaround for manually building things, but my CI pipeline is pretty much dead until this issue gets resolved.

**Comment by IngmarStein** [comment]
PR #5626 provides a workaround.

**Comment by whootang12** [comment]
is an app with core data using fast lane dead in the water until Apple fixes Xcode?  I'm guessing PR 5626 won't be merged?

**Comment by TKBurner** [comment]
@whootang12 Thanks for following up. Expect a fix for this this week. Thanks!

**Comment by mfurtak** [comment]
Hi all, we've shipped a workaround (#5626) and timeout/retry solution (#5188) as part of [`fastlane_core` 0.51.0](https://github.com/fastlane/fastlane/releases/tag/fastlane_core/0.51.0) 🚀 

Thanks very much for your help! Please let us know how it looks 👍

**Comment by mfurtak** [comment]
To test the latest release, please run `[sudo] gem update fastlane_core` or if you have a `Gemfile`, `bundle update`

**Comment by IngmarStein** [comment]
Working fine locally and on Travis. Thanks a lot!

**Comment by tmm1** [comment]
Still having this issue with the latest fastlane_core

**Comment by tmm1** [comment]
Specifically, I'm seeing the "The operation requires a selected developer portal team" error message that @Hoderu experience above. Likely a separate issue than the hang which has been fixed.

**Comment by IngmarStein** [comment]
The workaround only fixes the hang. The error message printed by `xcodebuild` is more a cosmetic issue and mostly harmless (as far as I can tell).

**Comment by tmm1** [comment]
You're right, the messages were unrelated. I had some codesigning issues that were being masked because of `gym(silent: true)` that I was able to fix by disabling the new "Automatic Signing" feature in Xcode 8.

**Comment by mfurtak** [comment]
Great, I'll close this issue for now, but please feel free to continue the conversation as needed! 👍

**Comment by tmm1** [comment]
I was able to re-enable "Automatic Signing" in Xcode 8 once I removed the `codesigning_identity` option from my Gymfile/Fastfile. The actual error message was hidden away in `~/Library/Logs/gym` and not present in the fastlane output, which is why it was so hard to debug the issue.

Once I found the log with all the xcodebuild output, the error was clearly spelled out:

```
    TARGET has conflicting provisioning settings. TARGET is automatically signed, but code signing identity iPhone Distribution: COMPANY has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.
    Code signing is required for product type 'Application' in SDK 'tvOS 10.0'
```

**Comment by TKBurner** [comment]
@tmm1 Thanks!

**Comment by CurlyHeir** [comment]
sill had problem with gym in XCode 8 GM, seems like you cant have opened xcode if you run gym

**Comment by ChristopherDrum** [comment]
Xcode 8 GM, gym 1.9.0
Continuing issue with builds on Travis CI. Works locally just fine.
The dreaded "check dependencies" when trying to do automated builds for Fabric Beta distribution (Enterprise builds)

Using @tmm1 's advice, I spit out the gym log and finally see something that explains the situation

```
=== BUILD TARGET iOSReachability OF PROJECT Framework WITH THE DEFAULT CONFIGURATION (Release) ===
Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "<<REDACTED>>" with a private key was found.
=== BUILD TARGET AdjustSdk OF PROJECT Adjust WITH THE DEFAULT CONFIGURATION (Release) ===
Check dependencies
No signing certificate "iOS Development" found:  No "iOS Development" signing certificate matching team ID "<<REDACTED>>" with a private key was found.
```
Oddly enough, I don't see anything in my own keychain that matches this either, but fastlane builds for Fabric Beta without incident. Xcode 7.3 builds are working fine, and local Xcode 8 builds are working fine using the same lane to create those builds.

Our project contains two submodules, but mostly subprojects which are brought into the project as a git subtree. It is my understanding that all of these subprojects can (hopefully?!) be left as-is with "automatic" to inherit from the parent project?

No other subprojects are exhibiting this behavior, which includes:
GRMustache
SocketRocket
Some private SDK projects
MBProgressHUD

I'm having a really difficult time understanding how fastlane + gym + Xcode 8 + subproject dependencies + manual code sign works together, and what needs to be set in what way. Every documentation I read seems to assume a very simple, "set the main project targets to manual code signing"... so I *assume* this means I can just forget about the subprojects... except when they collide with my gym builds...

**Comment by mfurtak** [comment]
Hi @ChristopherDrum - could you please start a new issue for your problem? We'd love to try to help 👍
