### ISSUE TITLE
Is it possible to run Deliver without the Deliverfile? / sips not found

### ISSUE THREAD

**Issue by igorsantos07** [fastlane/fastlane#5165]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I would like to run `deliver` in a non-interactive, one-off command, to upload screenshots to iTunes Connect. I notice there are CLI options to specify the Bundle ID, user email, and ENV vars to specify user password and "don't store" flag, but even by using these, `deliver` asks if I want to setup it before (creating the Deliverfile, that's not needed as all the used information is given through vars and options).

Would be great if there was a `--no_setup` flag or something similar.

##### Complete output when running fastlane, including the stack trace and command used
Output is not relevant, given the description above. The command works, but it waits for "y/n" user interaction.

```
~/images/test-user $ FASTLANE_USER=xxx@xxx.io FASTLANE_DONT_STORE_PASSWORD=1 FASTLANE_PASSWORD=xxx deliver -a io.xxx.ios --skip_metadata --skip_binary_upload -f --verbose
No deliver configuration found in the current directory. Do you want to setup deliver? (y/n)
n # <== this part makes the script need user interaction
INFO [2016-06-19 13:52:26.83]: Login to iTunes Connect (test@appshots.io)
INFO [2016-06-19 13:52:30.29]: Login successful

+--------------------+------------------------------+
|              deliver 1.13.1 Summary               |
+--------------------+------------------------------+
| app_identifier     | io.appshots.ios-tvos-watchos |
| skip_metadata      | true                         |
| skip_binary_upload | true                         |
| force              | true                         |
| screenshots_path   | ./screenshots                |
| metadata_path      | ./metadata                   |
| username           | test@appshots.io             |
| skip_screenshots   | false                        |
| submit_for_review  | false                        |
| automatic_release  | false                        |
+--------------------+------------------------------+

INFO [2016-06-19 14:09:02.70]: Starting with the upload of screenshots...
INFO [2016-06-19 14:09:02.70]: Uploading 2 screenshots for language pt-BR
INFO [2016-06-19 14:09:02.70]: Uploading './screenshots/pt-BR/pt_BR-1.png'...
sh: 1: sips: not found
sh: 1: sips: not found
INFO [2016-06-19 14:09:10.66]: Uploading './screenshots/pt-BR/pt_BR-4.png'...
sh: 1: sips: not found
sh: 1: sips: not found
INFO [2016-06-19 14:09:16.75]: Saving changes
INFO [2016-06-19 14:09:28.17]: Successfully uploaded screenshots to iTunes Connect
INFO [2016-06-19 14:09:30.03]: Finished the upload to iTunes Connect
```

### Configuration Files
There are no configuration files. That's exactly what this ticket is about :)

### Environment
deliver version (run `deliver -v`): **1.13.1**
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **no, but I can if needed**
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **no**

**Comment by igorsantos07** [comment]
Bonus question: what's that `sips: not found` message? Screenshot upload works as expected, though.

**Comment by KrauseFx** [comment]
It should be good enough to create an empty `Deliverfile`. Currently it's a requirement to have one as far as I know. This might be something we could change though.

**Comment by KrauseFx** [comment]
Can you run `which sips`?

**Comment by igorsantos07** [comment]
It doesn't seem to be a requirement because if I answer no, it works just
fine. But there's no way to programatically answer no in this case, you
see?

`which sips` gives no output.

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by igorsantos07** [comment]
@KrauseFx do you have any idea of what's `sips` about?
I'm trying to implement deliver under a PHP application but that sips issue is enough to give me a faux-negative exec result :/

**Comment by TKBurner** [comment]
@igorsantos07 Hi! Can you let me know what happens when you run `brew install sips`? Thanks!

**Comment by igorsantos07** [comment]
The project was running on Linux. Maybe that's the reason?
I can't help you anymore as I was fired from the project. lol

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]

**Comment by TKBurner** [comment]
@igorsantos07 Thanks for letting me know. If you run into this issue again always feel free to reach out. Thanks!
