### ISSUE TITLE
Question: commit_version_bump for Android?

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#5168]
Is there a commit_version_bump for android that will commit my Manifest file that get automatically updated by the build process with a new version number?

**Comment by TKBurner** [comment]
Hi @npomfret! Thanks for this idea. Right now it's not possible, but I'm going to mark this as a feature request so we can see if other community members would find this useful. Thanks!

**Comment by KrauseFx** [comment]
Hey @npomfret,
We recently introduced the new [fastlane plugin system](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#create-your-own-plugin) that allows you to distribute and maintain your own plugins, and still be exposed to `fastlane` users. Your idea would be a great candidate for that 👍 
Please let us know how the integration goes, and if you need any help getting up and running 🚀
