### ISSUE TITLE
Supply - AND -- will this upload apk to alpha, beta, or straight to production?

### ISSUE THREAD

**Issue by lam2558** [fastlane/fastlane#5174]
Hi,
I'm reading the description of supply and have a few question regarding it.
I would like to run this through CI build and after every build, would upload it to alpha testing only. Then push it to beta with another command. Then finally, gradually push to production.  From the command/description, it is not clear if this goes directly to production or alpha?

**Comment by truth3** [comment]
Hey @lam2558 it will upload the build to whichever track you have defined for that lane. For example you may have 3 different lanes in your Fastfile (alpha, beta, and production) which has the corresponding track defined. So once your QA team approves of everything in alpha or beta, you can call the production lane to send to the build off for a production release.

Hope that helps

**Comment by lam2558** [comment]
Ahh I see it now. Thanks for the quick response!
