### ISSUE TITLE
terminal scan command can not run through swift code.

### ISSUE THREAD

**Issue by noorshiblee** [fastlane/fastlane#5179]
### Issue Description

when i use "scan" from terminal, it runs properly.
but if i want to run this scan command through swift code like below:

import Foundation

class runTest{
    
    class func shell(args: String...) -> Int32 {
        let task = NSTask()
        task.launchPath = "/usr/bin/env"
        task.arguments = args
        task.currentDirectoryPath = "/Users/username/Desktop/Xocde/ios-ui-automation-demo-master/"
        task.launch()
        task.waitUntilExit()
        return task.terminationStatus
    }
}

runTest.shell("scan") //func call

it gives the below error:

env: scan: No such file or directory
Program ended with exit code: 0

##### Complete output when running fastlane, including the stack trace and command used

```
error:
env: scan: No such file or directory
Program ended with exit code: 0
```

i am using xcode 7.3 and swift 2.2 and osx 10.11 el captain

**Comment by vpolouchkine** [comment]
I don't believe this is a supported way of running `scan` or any other tool within `fastlane`. What's the end goal here?

**Comment by noorshiblee** [comment]
actually i want to run the "scan" command through swift code in osx. In terminal it scan command runs but in swift code it does not.

**Comment by vpolouchkine** [comment]
Right, but what are you trying to achieve running `scan` in Swift?

**Comment by noorshiblee** [comment]
Actually i am using this  for testing automation purpose.  I have done a lot of things by my code. I used a lot of terminal command in my swift code. But i stuck when i use this "scan" terminal command in my swift code. Actually it will be very helpful for me if i can run this terminal "scan" command through my swift code.
