### ISSUE TITLE
supply - promot_to_track requires APK!

### ISSUE THREAD

**Issue by hjanuschka** [fastlane/fastlane#5182]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Supply `promot_to_track` requires APK to be available - but doesnt require it to finish the promotion.

 
as a workaround - we run `gradle(task: "assembleRelease")` - but with the fix in the PR: https://github.com/fastlane/fastlane/pull/5180 - we could skip the build as it is not necassary, we only want to put the latest beta into production track.

##### Complete output when running fastlane, including the stack trace and command used

```
fastlane android_publish_beta

[17:09:52]: No apk file found, you can pass the path to your apk using the `apk` option
[17:09:52]: Updating track 'beta'...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- gh_inspector (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:92:in `show_github_issues'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:68:in `handle_unknown_error!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:47:in `rescue in run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'

```

### Configuration Files

Fastfile:
```ruby
lane :android_publish_beta do
supply(
         json_key: 'fastlane/google_play_key.json',
         track: "beta",
         track_promote_to: "production",
         skip_upload_apk: true,
         skip_upload_metadata: true,
         skip_upload_images: true,
         skip_upload_screenshots: true,
        )
end
```

### Environment
latest fastlane version (installed via gem install)
no rvm - local installation.

**Comment by vpolouchkine** [comment]
Thanks for the PR!

**Comment by asfalcone** [comment]
@hjanuschka The error message that appears after "No apk file found, you can pass the path to your apk using the `apk` option" isn't related to the apk being provided or not. It is the same error as in #5191 and https://github.com/fastlane/fastlane/issues/5187.

Could you try `sudo gem update gh_inspector` and let me know if that resolves your issue?

**Comment by hjanuschka** [comment]
@asfalcone yeah the gh_inspector fixed the error - and as posted in the PR - was on a wrong path, and forgot to set `skip_apk_upload`
