### ISSUE TITLE
Provisioning profile outputted by sign doesn't match profile on ipa

### ISSUE THREAD

**Issue by chrismanderson** [fastlane/fastlane#5183]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm using Fastlane to export ad hoc builds for Crashlytics beta. The build should be signed with the adhoc provisioning profile (that has been created successfully). I tell `sign` to use the adhoc provisioning profile, and I see it referencing that profile in the build steps,
  
    provisioning_profile_path | /Users/chris/Todos/Todos-ios/AdHoc_com.Todos.app.mobileprovision

    $ /usr/bin/xcrun /tmp/PackageApplication4Gym -v /Users/chris/Library/Developer/Xcode/Archives/2016-06-21/Todos\ 2016-06-21\ 12.02.40.xcarchive/Products/Applications/Todos.app -o '/var/folders/n0/2xbgdq1d23n5fzz9w65wxvhm0000gn/T/gym_output20160621-9843-6k7q5w/Todos.ipa' exportFormat ipa --embed '/Users/chris/Todos/Todos-ios/AdHoc_com.Todos.app.mobileprovision' 

But the resulting `.ipa` is signed with my distribution profile instead, not the adhoc profile. I feel like I'm missing something obvious here :).

### 
Fastfile:
```ruby
lane :beta do
  sigh(adhoc: true)
  gym(scheme: "Todos", use_legacy_build_api: true, clean: true) # Build your app - more options available
  crashlytics(
    api_token: "thesecrets",
    build_secret: "moresecrets"
  )
end
```

### Environment

fastlane version (run `fastlane -v`): `1.95.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by vpolouchkine** [comment]
Can you try setting the provisioning profile in `gym`?

**Comment by carrchr** [comment]
I'm having a similar issue where an updated adhoc profile is not getting packaged into the `.ipa` file.
In the `xcodebuild` log, I see the Code Sign message where it is using the correct (updated) provisioning profile. But the .ipa generated has the previous one (`embedded.mobileprovision` in the .ipa Payload folder).
I use this terminal command to examine the UUID of the `.mobileprovision` files
` security cms -D -i /path/to/profile`

**Comment by vpolouchkine** [comment]
@carrchr Can you please share your setup? Thanks!

**Comment by carrchr** [comment]
I was able to workaround the problem by deleting ALL cached provisioning profiles in `~/Library/MobileDevice/Provisioning Profiles`
We had recently reset all devices on our Apple Developer account. I had re-created the AdHoc provisioning profile in question but for some reason the product packaging phase (I assume) would copy the old provisioning profile into the .app package inside the .ipa Payload folder.
There must be some string pattern matching going on because I used the same name for the updated provisioning profile file.
I can provide more details, if desired.

**Comment by TKBurner** [comment]
@carrchr Awesome! Really glad to hear you got up and running!

**Comment by carrchr** [comment]
Might be worthwhile adding "delete ALL cached provisioning profiles in `~/Library/MobileDevice/Provisioning Profiles`" to the Code Signing troubleshooting/FAQ

**Comment by TKBurner** [comment]
@carrchr Thanks if you want to add it you can submit a PR, otherwise we'll update it in our docs review (once a month) Thanks!

**Comment by artonragsdale** [comment]
I've been seeing the same issue as @carrchr whenever I add devices using match. When I then try to upload the build to Crashlytics with fastlane it always uses an old provisioning profile. Archiving with Xcode and uploading with the Fabric app works correctly. 

I'll try deleting caches provisioning profiles, but it would be nice if the option to delete them would only delete the ones for the current project. Not every project I work on uses fastlane and reinstalling all those profiles is not worth the trouble.

Perhaps just automatically deleting the specific cached profiles when adding new devices with match using `force` or `force_for_new_devices` would make the most sense.

**Comment by TKBurner** [comment]
@artonragsdale Great idea! Would you be interested in submitting a PR to improve your workflow? Thanks!
