### ISSUE TITLE
FrameIt iPad Pro Frame Not Aligned and Has White Border

### ISSUE THREAD

**Issue by Megatron1000** [fastlane/fastlane#5184]
Frame downloaded from official Apple site, as per the setup link produces this misaligned image.

![ipadpro-3launch_framed](https://cloud.githubusercontent.com/assets/1567652/16243714/8318cda4-37f0-11e6-9faa-fc63ee43db28.png)

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by JonathanBouaziz** [comment]
Hey @Megatron1000, did you find a way to fix it? I'm also experiencing the same issue.

**Comment by Techprimate** [comment]
Duplicate of #4108

**Comment by TKBurner** [comment]
Closing as duplicate 👍
