### ISSUE TITLE
New Action: FTP

### ISSUE THREAD

**Issue by PoissonBallon** [fastlane/fastlane#5186]
I've already created a pull request for this action (and then got the notification to create an issue ^^)
If you have a question ? 
PR : https://github.com/fastlane/fastlane/pull/5185

(it's my first PR ^^ sorry if i have forgot something)

**Comment by suculent** [comment]
You can try `add_plugin apprepo` https://github.com/suculent/fastlane-plugin-apprepo (sequel of https://github.com/suculent/apprepo) - it's a SFTP uploader.

**Comment by TKBurner** [comment]
@PoissonBallon Great to hear from you! We've introduced a plugin system recently to help speed up our community. With this change we aren't adding new actions. If you are interested you can read more here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md

@suculent Awesome plugin!
