### ISSUE TITLE
supply init failed upon first install

### ISSUE THREAD

**Issue by klavergne** [fastlane/fastlane#5187]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Installed supply, ran supply init, and got the below error.

##### Complete output when running fastlane, including the stack trace and command used

```
klavergne$ supply init
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- gh_inspector (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Users/klavergne/.gem/ruby/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:92:in `show_github_issues'
	from /Users/klavergne/.gem/ruby/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:43:in `rescue in run!'
	from /Users/klavergne/.gem/ruby/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/klavergne/.gem/ruby/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Users/klavergne/.gem/ruby/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Users/klavergne/.gem/ruby/2.0.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /Users/klavergne/bin/supply:23:in `load'
	from /Users/klavergne/bin/supply:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile: None

### Environment

fastlane version (run `fastlane -v`): fastlane 1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by sundbry** [comment]
Same problem here. Running ruby 2.2.0, fastlane 1.95, supply 0.7.0

**Comment by vpolouchkine** [comment]
Thanks for the reports! We'll take a look.

**Comment by asfalcone** [comment]
This is another report of an issue with `gh_inspector` https://github.com/fastlane/fastlane/issues/5191. Not sure if it is related.

**Comment by KrauseFx** [comment]
Could you try running `sudo gem update gh_inspector` and see if that resolves the issue? 🚀

**Comment by gdeividas** [comment]
Had the same issue today. Ran the the command as root user(sudo) (since it was also installed using "sudo") -  worked fine and did not throw this error, so i guess it has something to do how fastlane resolves paths or smthg along the lines.

**Comment by klavergne** [comment]
@KrauseFx, that worked! I tried the same thing yesterday _before_ I posted this, and it didn't work then.
