### ISSUE TITLE
Can't get fastlane to run properly on xcode server machine

### ISSUE THREAD

**Issue by ggrell** [fastlane/fastlane#5191]
### New Issue Checklist

- [✓] Updated fastlane to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
fastlane works great on a couple different laptops (on El Capitan), thank you! Sadly can't get it to work properly on our xcode server. Fastlane installed locally to _xcsbuildd user (following this article: https://blog.xmartlabs.com/2016/03/07/ci-with-xcode-server-and-fastlane/)
When I installed it root (sudo gem install fastlane) it still gave the same error unless I ran it with ```sudo fastlane pre-beta``` so probably running into some kind of rights issue.

##### Complete output when running fastlane, including the stack trace and command used

```
_xcsbuildd$ fastlane pre-beta
[22:02:59]: -------------------------------------------------
[22:02:59]: --- Step: Verifying required fastlane version ---
[22:02:59]: -------------------------------------------------
[22:02:59]: fastlane version valid
[22:02:59]: ------------------------------
[22:02:59]: --- Step: default_platform ---
[22:02:59]: ------------------------------
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- gh_inspector (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:92:in `show_github_issues'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:43:in `rescue in run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /var/_xcsbuildd/.gem/ruby/2.0.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:239:in `run'
	from /var/_xcsbuildd/.gem/ruby/2.0.0/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /var/_xcsbuildd/.gem/ruby/2.0.0/gems/fastlane-1.95.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /var/_xcsbuildd/.gem/ruby/2.0.0/gems/fastlane-1.95.0/bin/fastlane:5:in `<top (required)>'
	from /var/_xcsbuildd/.gem/ruby/2.0.0/bin/fastlane:23:in `load'
	from /var/_xcsbuildd/.gem/ruby/2.0.0/bin/fastlane:23:in `<main>'
LABS-MAC1:listbuilder-ios _xcsbuildd$
```

### Configuration Files

Fastfile:
```ruby
fastlane_version "1.95.0"

default_platform :ios

platform :ios do
  def version_string(version_number, build_number)
    "#{version_number} (#{build_number})"
  end

  def change_log_since_last_tag
    return changelog_from_git_commits(pretty: '* %s')
  end
  
  desc "Pre-build step for Xcode Server Beta build"
  lane :pre-beta do |options|
    cert
    cocoapods
    git_pull(only_tags: true)
  end

  desc "Post-build step for Xcode Server Beta build"
  lane :post-beta do |options|
    build_number = increment_build_number
    version_number = options[:version_number] || get_version_number
    complete_version_number = version_string(version_number, build_number)

    change_log = change_log_since_last_tag
    crashlytics(
      api_token: "###",
      build_secret: "###",
      groups: "fastlane-test",
      notes: change_log
    )
    add_git_tag(tag: "LB-#{version_number}-BETA-#{build_number}")
    push_git_tags

    hipchat(
        api_token: "###",
        version: "1",
        message: "New build of ListBuilder Beta v#{complete_version_number}",
        channel: "Mobile iOS"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "ListBuilder", configuration: "Release") # Build your app - more options available
    pilot
    # frameit
  end
end
```

### Environment

Mac OS X 10.11.5 El Capitan w/ Mac Server & Xcode Server, Xcode 7.3.1
fastlane version (run `fastlane -v`): fastlane 1.95.0
Fastlane installed locally to _xcsbuildd user (following this article: https://blog.xmartlabs.com/2016/03/07/ci-with-xcode-server-and-fastlane/)
When I installed it root (sudo gem install fastlane) it still gave the same error unless I ran it with ```sudo fastlane pre-beta```

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by punksta** [comment]
have a same problem with Fastlane on Mac Mini with same version after update to Capitan

**Comment by sttz** [comment]
Bumped into this issue as well after updating.

The issue seems to be caused by the `gh_inspector` gem added in fe7f576e. Looking at the files installed by `gem`, they only had read rights for the owner (root in this case), which makes it impossible for ruby to load the gem unless run as root.

As a temporary fix, I changed to permissions manually:

    sudo chmod -R go+r /Library/Ruby/Gems/2.0.0/gems/gh_inspector-1.0.0/lib

This is on El Capitan, you might have to adjust the path on other versions.

I suspect the gem archive has these faulty permissions and needs to be updated for a proper fix.

**Comment by ggrell** [comment]
Thanks @sttz that fixes the issue on El Capitan.

**Comment by KrauseFx** [comment]
Could you try running `sudo gem update gh_inspector` and see if that resolves the issue? 🚀

**Comment by lyc2345** [comment]
`sudo gem update gh_inspector `

This is resolve problem for me.

**Comment by KrauseFx** [comment]
@lyc2345 cool, thanks for letting us know 👍
