### ISSUE TITLE
Can you require Gem in a Fastlane Action?

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#5192]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I see this issue that I didn't see before:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': /.../fastlane/actions/create_intranet_download_page.rb:117: syntax error, unexpected ')', expecting => (SyntaxError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Users/appian/.gems/gems/fastlane-1.95.0/lib/fastlane/actions/actions_helper.rb:81:in `block in load_external_actions'
	from /Users/appian/.gems/gems/fastlane-1.95.0/lib/fastlane/actions/actions_helper.rb:80:in `each'
	from /Users/appian/.gems/gems/fastlane-1.95.0/lib/fastlane/actions/actions_helper.rb:80:in `load_external_actions'
	from /Users/appian/.gems/gems/fastlane-1.95.0/lib/fastlane.rb:34:in `load_actions'
	from /Users/appian/.gems/gems/fastlane-1.95.0/lib/fastlane/commands_generator.rb:16:in `start'
	from /Users/appian/.gems/gems/fastlane-1.95.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Users/appian/.gems/gems/fastlane-1.95.0/bin/fastlane:5:in `<top (required)>'
	from /Users/appian/.gems/bin/fastlane:23:in `load'
	from /Users/appian/.gems/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
```

And I think it is due to a `require 'gemname'` in my create_intranet_download_page.rb action. Can I not do that or is there another issue?

##### Complete output when running fastlane, including the stack trace and command used

See above

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# None
```

### Environment

fastlane version (run `fastlane -v`): 1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by KrauseFx** [comment]
It's a syntax error, can you share all your configuration files please?

**Comment by lyndsey-ferguson** [comment]
Thanks for confirming that this is a syntax error. I backtracked in my commit history and found that I was passing a parameter without the required keyword:

Good:
```
FastlaneCore::PrintTable.print_values(config: params, hide_keys: [], title: "Summary for Create Intranet Download Page")
```

Bad (notice missing `title:`):
```
FastlaneCore::PrintTable.print_values(config: params, hide_keys: [], "Summary for Create Intranet Download Page")
```

**Comment by KrauseFx** [comment]
🚀
