### ISSUE TITLE
Signing for 'enterprise' using match

### ISSUE THREAD

**Issue by suculent** [fastlane/fastlane#5193]
It appears to me, like there's a missing fastlane/match type 'enterprise' (iTC-less).

Should i use 'appstore' for retrieving enterprise distribution certificates? It might require re-using existing identity.

```
  Commands:
    adhoc             Run match for a adhoc provisioning profile -- possible typo: an addhoc or a profile?
    appstore          Run match for a appstore provisioning profile -- possible typo: an appstore or a profile?
    change_password   Re-encrypt all files with a different password
    decrypt           Decrypts the repository and keeps it on the
filesystem
    development       Run match for a development provisioning profile
    ...
   enterprise     Run match for an enterprise provisioning profile
```

**Comment by vpolouchkine** [comment]
Glad to hear you're giving `match` a whirl! Omitting enterprise was a conscious decision; please take a look at https://github.com/fastlane/fastlane/tree/master/match#enterprise-profiles for more information. Thanks!

**Comment by KrauseFx** [comment]
Also, if you really want to use it, you might want to check out https://github.com/fastlane/fastlane/blob/master/match/lib/match.rb#L29

**Comment by lukewakeford** [comment]
+1
