### ISSUE TITLE
Warn on multiline release-notes?

### ISSUE THREAD

**Issue by Luke-SF** [fastlane/fastlane#5198]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When updating an app using deliver, with a multiline release_notes text, it fails to update metadata.

Apparently since earlier today, they no longer allow multiline what's new text.

You can verify this by trying to update and save it in the browser, you will get a invalid-characters error when saving whats-new text with enter in it.

Assuming this may not be intended behavior, I have submitted an Apple bug report.

**Comment by evilDave** [comment]
Seems to be a bug (resurrected http://stackoverflow.com/questions/4047990/itunes-connect-does-not-allow-to-enter-multiline-description).
Have lodged bug report also. Last time it took a few days to correct.

**Comment by programmin1** [comment]
Maybe you could have a suggestion "You can tweet #iTunesConnectDoesNotSupportMultiline Why must my release notes be in one line?" every time this happens, similar to what happens when it takes hours for a build to show up?

**Comment by evilDave** [comment]
Haha. If it was only release notes I would not be blocked, but it is the description field too.

**Comment by programmin1** [comment]
What do you mean, "Haha"? Was there a one-liner I missed? :)

**Comment by evilDave** [comment]
I think this is good to close - as described it was an Apple bug regression that was fixed quite quickly.

**Comment by TKBurner** [comment]
@evilDave Thanks!
