### ISSUE TITLE
`pilot add` and `pilot import` don't work anymore

### ISSUE THREAD

**Issue by jorgeazevedo** [fastlane/fastlane#5200]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`pilot add` and `pilot import` don't work anymore. Running a command like this

`pilot add mail@domain.com --username "me@domain.com" --app_identifier "my.app"`

Fails with

```
[11:14:53]: Could not create tester user@gmail.com
[11:14:53]: [user@gmail.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["service_http_bad_response"]}, "statusCode"=>"ERROR"}
```

##### Complete output when running fastlane, including the stack trace and command used

```
[jazevedo@ip-10- ~]$ pilot add user@gmail.com --username "me@guardian.co.uk" --app_identifier "uk.co.guardian.iphone2"
[11:14:42]: Login to iTunes Connect (me@guardian.co.uk)
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for me@guardian.co.uk): ************
[11:14:51]: Login successful
[11:14:53]: Could not create tester user@gmail.com
[11:14:53]: [user@gmail.com]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["service_http_bad_response"]}, "statusCode"=>"ERROR"}

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new

[!] Some operations failed: ["user@gmail.com"]
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
Not used
```

### Environment

fastlane version (run `fastlane -v`):

pilot 1.9.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No

**Comment by b-andris** [comment]
I'm getting the same with

    pilot list

Which gives me this error message

    /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/client.rb:434:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["service_http_bad_response"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:747:in `testers'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/tunes/tester.rb:74:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/tester_manager.rb:106:in `list_testers_global'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/tester_manager.rb:87:in `list_testers'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/commands_generator.rb:86:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/commands_generator.rb:126:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/commands_generator.rb:16:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'

**Comment by jorgeazevedo** [comment]
@b-andris ah, good shout, didn't notice that. Looks like something changed in the iTC API? I tried rolling back as far as pilot 1.0.1 and couldn't get it to work, but I'm not 100% sure the rollback actually worked.

**Comment by b-andris** [comment]
@jorgeazevedo that was my guess. Especially since as far as I know Apple does not have any Applications that do these kinds of things. So there bound to be pretty careless when it comes to changing the API

**Comment by b-andris** [comment]
Although. I just noticed that iTC website also gives me an error message when i try to access
Users and Roles -> TestFlight Beta Testers

**Comment by jorgeazevedo** [comment]
@b-andris you found it! This endpoint is down https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/users/pre/ext

This one still works though
    https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/user/externalTesters/app_id/

**Comment by vpolouchkine** [comment]
Thanks for the reports! We'll take a look.

**Comment by KrauseFx** [comment]
Thanks for the report everybody, taking a look at this now 👍

**Comment by KrauseFx** [comment]
Alright, this is actually broken on Apple's side, I'll contact support. The exact same thing happens when doing via the web browser 👍 

![screenshot 2016-06-23 14 14 24](https://cloud.githubusercontent.com/assets/869950/16320478/d1e0272c-394c-11e6-9b82-57f87212152f.png)

**Comment by KrauseFx** [comment]
Everybody experiencing this issue, feel free to also contact the Apple Developer Support with the following text

```
1) Login to iTunes Connect
2) Click on Users & Roles
3) Click on "TestFlight Beta Testers"
4) Click on "External"
5) You see the attached error message
```

**Comment by KrauseFx** [comment]
I just tried both boarding and pilot, and both work without problems. I'll close this issue for now, however feel free to re-open if you're still running into issues 👍
