### ISSUE TITLE
Error setting value - iTunesArtwork@2x.jpg' for option 'app_icon' - only accepts .png file

### ISSUE THREAD

**Issue by ardee19** [fastlane/fastlane#5207]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

error is thrown when uploading a jpeg app_icon. 1024x1024 jpeg icon is valid when manually uploading app icon but fastlane looks for a .png file. Uploading jpegs make the all alpha disabled.

***This works if in the DeliverFile setting for app_icon is set to .png

##### Complete output when running fastlane, including the stack trace and command used

iTunesArtwork@2x.jpg' doesn't seem to be a png file

### Environment

run `fastlane deliver`

**Comment by TKBurner** [comment]
@ardee19 Is this similar to #1626 ? I've let the core team know. Thanks!

**Comment by ardee19** [comment]
@TKBurner Not really. That one, downloaded screenshots from iTunesConnect then tried uploading it.

This one is just uploading a new app_icon. Fastlane doesn't accept a .JPG file because it looks for a .PNG file even if iTunesConnect accepts a .JPG file when you do it manually.

**Comment by KrauseFx** [comment]
@ardee19 Apple's policy is that you should have your app icon in png, both on iTunes Connect and in your Xcode project. The fact that iTunes Connect seems to auto-convert jpg to png is good to know, however with fastlane we follow the best practises on only accepting the file type png without an alpha layer

**Comment by ardee19** [comment]
Thanks for clarifying @KrauseFx  but I found that JPEG files are accepted according to Apple's iTunes Connect Developer Guide.

https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html

This is the actual text for the app icon:

The large app icon is displayed for your app on the App Store and, if needed, is used to feature your app on the App Store.

iOS app icons need to meet the following requirements:

- 1024 x 1024 pixels (don’t scale up smaller artwork, because this could appear pixelated and blurry)
- 72 dpi, RGB, flattened, no transparency, no rounded corners
- **High-quality JPEG or PNG image file format.**

**Note**: The small icon (57 x 57 pixels for iPhone and iPod touch, 50 x 50 pixels and 72 x 72 pixels for iPad) that you include inside the build is used on the device Home screen when installed.


---------------------------------------------------------------

They might have updated their policy that's why they accept the JPEG files now.
