### ISSUE TITLE
Getting values from an .xcconfig file

### ISSUE THREAD

**Issue by FranDepascuali** [fastlane/fastlane#5211]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello, I'm configuring fastlane from a project. In this project we have different `.xcconfig` files in which we store variables which are used then by xcode, through the `info.plist`.

I need to use some of these keys on fastlane, I've looked for a way to retrieving them from an `xcconfig` and couldn't find one. I ended up adding a `.env.default` file with those keys (using dotfiles). 

Is there any way to parse an `xcconfig` file and get the keys from there? I would prefer to have a single `xcconfig` from which the `info.plist` and the fastfile file reads from rather than having two separate files. Thank you very much, fastlane is a great tool!

**Comment by vpolouchkine** [comment]
`gym` has a `--xcconfig` argument that you can use. 👍  You can run `gym help` to get the full list.

**Comment by FranDepascuali** [comment]
Thanks. The thing is that I don't want to build the app. I needed to upload the dsyms to an external service and I had a token for it. I do not need to build the app; I would just want to read these values form an xcconfig.

**Comment by FranDepascuali** [comment]
And please, let me answer before closing an issue. Maybe you didn't understand my request, or I wasn't satisfied by your answer and you just close it
