### ISSUE TITLE
Incorrect documentation for last_git_commit_message

### ISSUE THREAD

**Issue by lgauthier** [fastlane/fastlane#5213]
### Issue Description

The documentation for the last_git_commit_message action shows an example that implies that the return value is a hash representing the commit as a whole, but it actually just returns a string for the message.

https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#last_git_commit_message-was-last_git_commit

**Comment by asfalcone** [comment]
Closing this issue because the associated PR was merged 👍 🚀

**Comment by shoby** [comment]
It doen't work in my environment (v1.97.2).

```
crashlytics(notes: last_git_commit_message)
```

```
[!] Could not find action or lane 'last_git_commit_message'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane
```

I think `last_git_commit_message` is not a action.
It's just a method in `git_helper.rb`

https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/helper/git_helper.rb

```
bundle exec fastlane actions

| last_git_commit                     | Return last git commit hash, abbreviated commit hash, commit message and author | ngutman          |
```
