### ISSUE TITLE
There is no IRC channel or mailing list for fastlane, or if there is its not obvious where it is

### ISSUE THREAD

**Issue by pdebruic** [fastlane/fastlane#5216]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The fastlane.tools and github pages and docs don't describe where a newbie could go to ask questions in a forum other than github issues. I would like to ask questions like: 

```OK - I've run fastlane init.  Now what?  I want to build my phonegap app for android and iOS.  Is there documentation to go from nothing to a working set up? It seems like the docs for the tools are complete but there isn't something (I found ;) ) that says "things should be run in this order."  ```

And I imagine I'll hit other solved issues that I have no idea are out there, just because I don't know.

So can we set something like that up or make it obvious if there is such a place. 

Thanks

##### Complete output when running fastlane, including the stack trace and command used

```
N/A
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
N/A
```

### Environment
N/A

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by asfalcone** [comment]
@pdebruic Give these [docs](https://github.com/fastlane/fastlane/tree/master/fastlane/docs) a look and check out the [examples](https://github.com/fastlane/setups/tree/master/samples-android). 

Let me know where you would have expected to see these linked from so we can improve the documentation! 👍

**Comment by KrauseFx** [comment]
In general, we encourage everyone to submit issues on GitHub, even if it's not actual an "Issue", but just a question. It's easier to have everything at one central public space, so that everyone can search for existing issues

**Comment by pdebruic** [comment]
OK.  Thanks for closing.
