### ISSUE TITLE
ipa generated by gym cannot upload to iTunes Connect.

### ISSUE THREAD

**Issue by JohnnyTseng** [fastlane/fastlane#5217]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Can't upload .ipa to iTunes Connect after using `gym` to build.
Having error message generated by iTunes Connect

`ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/ProjectName.app/ProjectName' is not supported."`

##### Complete output when running fastlane, including the stack trace and command used

```
01:24:10]: Making sure the latest version on iTunes Connect matches '3.5.1' from the ipa file...
[01:24:13]: '3.5.1' is the latest version on iTunes Connect
ITC.apps.devReject.message.and.link.inReview.canReject
[01:24:15]: Uploading binary to iTunes Connect
[01:24:15]: Going to upload updated app to iTunes Connect
[01:24:15]: This might take a few minutes, please don't interrupt the script
[01:24:39]: [Transporter Error Output]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/ProjectName.app/ProjectName' is not supported."
[01:24:39]: Transporter transfer failed.
[01:24:39]:
[01:24:39]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/ProjectName.app/ProjectName' is not supported."
[01:24:39]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/ProjectName.app/ProjectName' is not supported."
Return status of iTunes Transporter was 1: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/ProjectName.app/ProjectName' is not supported."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- gh_inspector (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:92:in `show_github_issues'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:43:in `rescue in run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.47.0/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.1/lib/deliver/commands_generator.rb:132:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.1/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.1/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
```

### Configuration Files
Using 2 commands:

1. Generate ipa by gym

`gym --workspace "ProjectName.xcworkspace" --scheme "ProjectName-Release" -i "iPhone Distribution: XX Xxxxxxx (XXXXXXXX)" -e "./scripts/profile/project.mobileprovision" --clean --verbose --use_legacy_build_api`

2. Upload to iTunes Connect using `deliver`

`deliver --team_name "Team Name" --submit_for_review --skip_metadata --skip_screenshots -f`

Fastfile: NOT using Fastfile, only commands

### Environment

fastlane version: 1.96.0

Do you use bundler to execute fastlane? NO

Do you use a Ruby environment manager? NO

Xcode Version: Xcode 7.3.1 & Xcode 8 beta
OSX Version: OSX Yosemite

I confirm that:

- Upload ipa that generated by gym to iTunes Connect works normally in the past, but suddenly, it just brokes.
- ipa archive by Xcode with same provisioning profile & target can be uploaded to iTunes Connect succesfully.
- I'm using the distribution provisioning profile
- Push Notifications in App Id settings were enabled (both development and production)
- The provisioning profile is generated after enabling push notifications.

Are there anyone else facing the same issue?

**Comment by FranciscoAmado** [comment]
Hi,
I've encountered the same problem as you and managed to solve it by checking both project and target "Build Settings" > "Code Signing" > "Code Signing Identity".
"Code Signing Entitlements" should be empty, at least, in my case.

If your problem is in uploading to iTunes Connect you may also verify your build info with [shenzhen](https://github.com/nomad/shenzhen), which turns out to be very useful for these issues.

If you choose to use [shenzhen](https://github.com/nomad/shenzhen), after installing, run
`ipa info ./build/ProjectName.ipa`
It will give a much detailed info of the generated .ipa

**Comment by ohwutup** [comment]
Thanks for chiming in @FranciscoAmado!! @JohnnyTseng - @FranciscoAmado is likely right, this looks very much like some misconfiguration of your application such that it is not being properly code signed for sending to the App Store. I am going to close this issue for now, but please comment again here if you are still running into any issues! 🚀

**Comment by JohnnyTseng** [comment]
Hi, thanks for the reply: @FranciscoAmado and @ohwutup 
I've tried @FranciscoAmado's solution, changed the Xcode build settings as this image shows:

![2016-06-29 09 58 28](https://cloud.githubusercontent.com/assets/2656519/16438236/6a792708-3de0-11e6-9913-d0c346dac8c9.png)

This setting will generate a ipa signed with developer profile (I don't know why, I've already specified distribution profile for `gym` command)
So I use `sigh` to resign the ipa.

Shows 2 new errors:

`CE14A42003/1049222004.itmsp - Error Messages:
		ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '*' for key 'com.apple.developer.associated-domains' in 'Payload/ProjectName.app/ProjectName' is not supported."
`

and 

`ERROR ITMS-90345: "Metadata/Info.plist Mismatch. The value for bundle_version in the metadata.xml file does not match the value for CFBundleVersion in ProjectName [Payload/ProjectName.app]."`

My app is using associated domain, and configured in the developer center.

**Comment by FranciscoAmado** [comment]
Hi, 
@JohnnyTseng Have you tried changing the "Don't Code Sign" for Debug Config "iPhone Developer" and Release Config "iPhone Distribuition" and run it again? The second error is most likely linked with the first one also.

**Comment by JohnnyTseng** [comment]
Hello @FranciscoAmado ,
Yes, my default settings is same as what you described. But it still doesn't works.
But now the only problem left is the associated domain:

`ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '*' for key 'com.apple.developer.associated-domains' in 'Payload/ProjectName.app/ProjectName' is not supported.`

I've also tried added domain in the capabilities tab, and specify the CODE_SIGNING_ENTITLEMENTS file like this:

![2016-06-29 16 48 34](https://cloud.githubusercontent.com/assets/2656519/16446294/65bf7e22-3e19-11e6-99dd-93b8bdd4a255.png)

Still doesn't works ;(

**Comment by ohwutup** [comment]
Hey @JohnnyTseng checkout `sigh` (https://github.com/fastlane/fastlane/tree/master/sigh) and maybe give that a try. It should take care of most of your provisioning profile problems. Might help to look at `cert` (https://github.com/fastlane/fastlane/tree/master/cert) and `pem` (https://github.com/fastlane/fastlane/tree/master/pem) too.

**Comment by JohnnyTseng** [comment]
Hi @ohwutup @FranciscoAmado ,
My problem has been solved.

The solution is, add 2 keys to the `*.entitlements` file

1. `application-identifier` which format follows `TEAMID.APP_IDENTIFIER`
2. `com.apple.developer.team-identifier`

and specify the `Code Signing Entitlements` in Xcode's Build Settings,
problem solved!
