### ISSUE TITLE
fastlane for cordova Android

### ISSUE THREAD

**Issue by OkancanCosar** [fastlane/fastlane#5220]
Hello, 
we developing phonegap/cordova project. And publish Google play store/Appstore. Is there any developing solution for phonegap/cordova projects?
Thank you...

**Comment by TKBurner** [comment]
Hi @OkancanCosar Thanks for reaching out. You should still be able to use Supply, by passing it your APK directly. I'm not sure if screengrab will work. Let me know if you have any other questions. Thanks!

**Comment by OkancanCosar** [comment]
As I understand it, supply dosnt help for create app in google play store. Actually I'm looking for it. Google support it?

**Comment by lucasvanhalst** [comment]
@OkancanCosar Google does not supply an API for it (see https://developers.google.com/android-publisher/#subscriptions) so it is not possible. You can only use supply to update apps, at least for now

**Comment by ohwutup** [comment]
Thanks for chiming in here @lucasvanhalst! @OkancanCosar - we will definitely keep our eyes peeled to add this functionality if it becomes available from Google! You can definitely use `produce` https://github.com/fastlane/fastlane/tree/master/produce to get this going in the App Store though!
