### ISSUE TITLE
Create Crashlytics beta build share.

### ISSUE THREAD

**Issue by Vishal-Singh-Panwar** [fastlane/fastlane#5222]
##### `Its a feature request.`
🔑
Can we get build share link from `Crashlytics Beta`? And infact, build information also, like `title`, `bundle_indentifier`. Like we get `HOCKEY_DOWNLOAD_LINK` and `HOCKEY_BUILD_INFORMATION ` as output variables for [Hockey App](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb). Maybe we could use these details for creating a notification message for slack or other channels?

**Comment by TKBurner** [comment]
Hi @Vishal-Singh-Panwar Thanks for reaching out. Right now we aren't expanding our actions. We have added a plugin system if you are interested in implementing this yourself. Check out this page for info, https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md Thanks!
