### ISSUE TITLE
No warnings when using xcode 7 build features with legacy build api enabled

### ISSUE THREAD

**Issue by mtynior** [fastlane/fastlane#5225]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Right now, when we use the Xcode's 7 feature e.g. `include_bitcode`  with the `use_legacy_build_api` enabled such feature is just being ignored without notifying user. This is very confusing for people who doesn't really know what "legacy build api" means. 
It would be nice to at least display warning message. It might be something like this:

```bash
[Warning] Lagacy buid api is enabled. Following options will be ignored:
 - include_bitcode
```

### Configuration Files

Fastfile:
```ruby
gym(
   include_bitcode: true,
   use_legacy_build_api: true,
)
```

### Environment

fastlane version (run `fastlane -v`): `1.95.0`

**Comment by KrauseFx** [comment]
This makes perfect sense. I'd love to have this as part of gym, you can easily print out warnings like this using `UI.important("text here")`
The correct file to add this is https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/package_command_generator_legacy.rb, similar to https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/package_command_generator_xcode7.rb#L163, called from https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/package_command_generator_xcode7.rb#L13

Let me know if you need any help preparing a pull request, this should be easy to add 👍

**Comment by mtynior** [comment]
Just to make things clear. I think following options are being ignored when `use_legacy_build_api` is enabled:
- `include_bitcode`
- `include_symbols`
- `export_team_id`
- `export_method`

Is this list correct, or I'm missing something? If so, do you know where can I find the full list of options that are related with new api, beside the xcodebuild's `exportOptionsPlist` help?
