### ISSUE TITLE
[produce] error => Creation of apps of this type is not available

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#5226]
I tried to create new app in appstore and got this issue:

`produce create -u email@email.com -a com.appid.app -q "App Name"`

> +----------------+--------------------------+
> |         Summary for produce 1.1.2         |
> +----------------+--------------------------+
> | username       | email@email.com |
> | app_identifier | com.appid.app        |
> | app_name       | App Name            |
> | sku            | 1467015419               |
> | language       | English                  |
> | skip_itc       | false                    |
> | skip_devcenter | false                    |
> +----------------+--------------------------+
> 
> [11:17:06]: [DevCenter] App 'com.appid.app' already exists, nothing to do on the Dev Center
> [11:17:11]: Creating new app 'App Name' on iTunes Connect
> 
> Looking for related GitHub issues on fastlane/fastlane...
> 
> ➡️  Creation of apps of this type is not available
>    https://github.com/fastlane/fastlane/issues/4298 [closed] 3 💬
>    22 Apr 2016
> 
> ➡️  error: Creation of apps of this type is not available
>    https://github.com/fastlane/fastlane/issues/3531 [closed] 6 💬
>    21 Apr 2016
> 
> ➡️  Creation of apps of this type is not available
>    https://github.com/fastlane/fastlane/issues/674 [closed] 4 💬
>    21 Apr 2016
> 
> and 3 more at: https://github.com/fastlane/fastlane/search?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22error%22=%3E[%22Creation%20of%20apps%20of%20this%20type%20is%20not%20available%22],%20%22info%22=%3Enil%7D,%20%22statusCode%22=%3E%22ERROR%22%7D&type=Issues&utf8=✓
> /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/spaceship-0.27.2/lib/spaceship/client.rb:434:in `parse_response': [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Creation of apps of this type is not available"], "info"=>nil}, "statusCode"=>"ERROR"} (Spaceship::Client::UnexpectedResponse)
> 	from /Users/petrkorolev/.rvm/gems/ruby-2.1.5@global/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:231:in `create_application!'

**Comment by KrauseFx** [comment]
Do any of the suggested links help you? https://github.com/fastlane/fastlane/search?q=%7B%22data%22=%3Enil,%20%22messages%22=%3E%7B%22warn%22=%3Enil,%20%22error%22=%3E%5B%22Creation%20of%20apps%20of%20this%20type%20is%20not%20available%22%5D,%20%22info%22=%3Enil%7D,%20%22statusCode%22=%3E%22ERROR%22%7D&type=Issues&utf8=%E2%9C%93

**Comment by skywinder** [comment]
@KrauseFx double checked this list and so yes. it's duplicate of mine old issue: #2035
I checked - there some actions required in itunes connect to upload build.
I believe it would be nice to notify users, to check itunes connect when they seen this error.
