### ISSUE TITLE
[match] Ability to implicity specify which certificate use for match

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#5227]
I have 3 iOS Distribution Certificates. 
I don't know, which one `match` will use for signing. 
Is there any way to specify certificate to use or guess, which one it will use for signing new provosion profiles?

**Comment by KrauseFx** [comment]
There is only one certificate in your git repo, right? This one will be used. `match` creates and maintain its own certificates

**Comment by skywinder** [comment]
@KrauseFx 
Ok, here is  steps to reproduce to clarify my case:

0. I have account with 3 certificates already and want to create new app.
1. I created private repo to store certificates and provisions
2. I created app via `produce`
3. Now I want to create provisions, I run `match development -a com.my.app -r https://skywinder@mydomain.com/myapp.git -u mail@gmail.com`

Which of 3 certificate will be used to sign new provision in this case?

**Comment by KrauseFx** [comment]
If you run `match development` for the first time, it will try to generate a new one and not use an existing one. `match` will maintain its own set of certificates and profiles and won't touch or use your existing ones. Since you already have 3 certificates, it will probably fail when you try to create a new one, as you only have spots for so many certificates

**Comment by skywinder** [comment]
@KrauseFx Got it, thank you for clarification!
Just checked, last one just created yesterday, as you explained.
So, what should I do, if I want to manage one more app from this account via match? is it possible to reuse old certificates in new apps?

**Comment by skywinder** [comment]
@KrauseFx to not create new issue, I will specify my feture-request:
Ability to specify certificate for match. In order to use one certificate for different applications. (i.e. different match repositories for them, but with one common certificate)

**Comment by TKBurner** [comment]
@skywinder Thanks! 👍
