### ISSUE TITLE
Summary output for PEM 1.3.1 tries to print a proc

### ISSUE THREAD

**Issue by marcomorain** [fastlane/fastlane#5228]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description

The summary table for PEM 1.3.1 outputs a to_s of a proc for the `new_profile` key.

Maybe the best thing to do is to not show this key, or to replace it with 'yes'.

##### Complete output when running fastlane, including the stack trace and command used

```
+------------------+--------------------------------------+
|                  Summary for PEM 1.3.1                  |
+------------------+--------------------------------------+
| new_profile      | #<Proc:0x007ff0fe633070@Fastfile:59> |
| development      | false                                |
| generate_p12     | true                                 |
| force            | false                                |
| save_private_key | true                                 |
```

Fastfile snippet:

```Ruby
sigh
pem(new_profile: Proc.new { |pem| upload_pem(config, pem) })
gym
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.92.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? yes

Building on travisci.com

**Comment by KrauseFx** [comment]
Nice catch, I'll provide a fix in a minute 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/issues/5232, this will be in the next `pem` release 👍 Thanks again

**Comment by marcomorain** [comment]
Thanks @KrauseFx !
