### ISSUE TITLE
spaceship -  customer review

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#5233]
Hi

with spaceship. it's possible to have the customer review?

Bolo

**Comment by KrauseFx** [comment]
If you're asking to create a customer review, no you can't and it's not something we want to do.
If you're asking to receive reviews: that's currently not available in spaceship, but would be something we could review a pull request of 👍

**Comment by bolom** [comment]
> If you're asking to receive reviews: that's currently not available in spaceship, but would be something we could review a pull request of

do you think you can give me some direction to have this info. I will try to implement it

**Comment by TKBurner** [comment]
Hi @bolom Thanks for reaching out. Because this isn't available in Spaceship, I think your best reference will be the iTunes Connect API documentation. Let me know if you get started 👍 Thanks!

**Comment by revile** [comment]
I've made a Pull Request that implements this here: #5861

**Comment by bolom** [comment]
@TKBurner yes it's better tks

**Comment by TKBurner** [comment]
@revile Awesome! @bolom Did you get a chance to test out the PR? Thanks!
