### ISSUE TITLE
app name not in english

### ISSUE THREAD

**Issue by hula1** [fastlane/fastlane#5236]
I'm trying to create a new application with fastlane/produce by running the following command
produce -u "$user" -a "$bundle_id" -q "$app_name" -z "$version" -y "$bundle_identifier" -m English

(as you can see I run it with bash)

but unfortunately when app_name is not in english I receive the following error

Creating new app '  ' on the Apple Dev Center
[31m
[!] Apple provided the following error info:
	There were errors in the data supplied. Please correct and re-submit.
	No value was provided for the parameter &#x27;appIdName&#x27;.[0m

is it possible to specify app_name in the language other than english?

**Comment by truth3** [comment]
@hula1 Is this the first application being created for this iTunes Connect account?

**Comment by hula1** [comment]
No, it's not the first time I create new application (my account already has some apps), but previously I used app names in english, when I try to use fastlane/produce with app name specified in another language then I receive that error

**Comment by hula1** [comment]
Is it possible at all to use fastlane/produce with a non-english language?

**Comment by vpolouchkine** [comment]
Which language are you using? I'll try it on my end.

**Comment by hula1** [comment]
I use hebrew

**Comment by jiyee** [comment]
same problem in using Simplified Chinese

**Comment by TKBurner** [comment]
Hi! Can you give an example of an app name that is affected? Can you add the --verbose flag and share the full input and output? Thanks!

**Comment by ofrioster** [comment]
I'm also using hebrew and is receive and error. 
An app example can be: "דוגמה לשם "
Do you have solution?

**Comment by TKBurner** [comment]
@GT-3 Thanks for following up on this. I looped in the core team and they'll take a look. I'm also going to mark this as help wanted in case anyone wants to submit a PR. Thanks!

**Comment by mfurtak** [comment]
I can reproduce this locally. But based on the code, removing all non-latin characters appears to be intentional behavior. See: https://github.com/fastlane/fastlane/blob/master/produce/lib/produce/developer_center.rb#L37-L40

@KrauseFx can you recall the history of this code and why it is important?

**Comment by TKBurner** [comment]
Hi, we need to look into this on the core team before we can accept a PR. Removing the help wanted label. Thanks!

**Comment by hjanuschka** [comment]
this has been fixed.  with #7210  and #7211
