### ISSUE TITLE
Add equivalent to generate_summary to supply

### ISSUE THREAD

**Issue by evilDave** [fastlane/fastlane#5239]
### Issue Description

It would be nice to be able to generate similar metadata and screenshot reports for Android with supply that deliver does for iOS.

**Comment by TKBurner** [comment]
Hi @evilDave! Great idea. I'm going to mark this as help wanted in case anyone is interested in submitting a PR 👍

**Comment by bgannin** [comment]
Added to my 'as time allows' list 👍

**Comment by bgannin** [comment]
Clarification - is this in reference to supply's summary in terminal upon completion or the HTML page generated along with the screenshots?

**Comment by evilDave** [comment]
I was referring to the generated HTML. I too have it on my list of things to do when I get some time :) It should be relatively straightforward to just copy the iOS one.

**Comment by evilDave** [comment]
I am still hoping to work on this some time in the future.

**Comment by TKBurner** [comment]
@evilDave Thanks for following up! We'll leave this open 👍
