### ISSUE TITLE
Running unit tests in parallel on the same machine

### ISSUE THREAD

**Issue by xfreebird** [fastlane/fastlane#524]
Hi,

Thanks for this beautiful tool.
When running iOS tests on a machine the iOS simulator is used.
And on the same machine can run only one instance of iOS simulator at a time.

Does fastlane tackle this case somehow ? 
Does it support concurrent testing on the same machine ?

For example I have two iOS projects on the same machine, and I start in different terminals fastlane.

Terminal 1, project1:
fastlane runtests

Terminal 2, project2:
fastlane runtests

Cheers,
Nicolae

**Comment by KrauseFx** [comment]
You can only run one simulator instance at a time. `fastlane` itself can be run multiple times in parallel, but it's not recommended, since some integrations like the simulator tests can only be executed once.

**Comment by xfreebird** [comment]
Thanks @KrauseFx. 

Then something like simulator locking would be handy (e.g. processes from lanes would wait until other processes from other lane finished using the simulator).

I think the same is valid and for CocoaPods, if two fastlane processes are updating the same pod would brake the pod cache on the build machine

**Comment by KrauseFx** [comment]
Agreed, but that's not something `fastlane` can do right now.

**Comment by xfreebird** [comment]
Hi @KrauseFx ,

I was thinking about a possible solution for this case.
But since I know very little ruby, it will take some time for me to make it.

My general  general idea is to have something like this:

````ruby
lane :beta do

   #all other fastlane execexclusive cocoapods actions with will wait this one to terminate
    runexclusive {
        name : "cocoapods_lock"
        action : cocoapods
    }

    runexclusive {
        name : "xctest_lock"
        action : xctest
    }
end
````

and runexclusive might look like this:

````ruby
LockFileExclusive("/tmp/#{lockname}.lock")
action
UnLockFileExclusive("/tmp/#{lockname}.lock")
````
Is this something that looks reasonable ?

Cheers,
Nicolae

**Comment by xfreebird** [comment]
Hi @KrauseFx,

I've been looking on how to implement the locking mechanism so that only one cocoapods or xctest is running on a given machine.

My approach is quite simple and generic. The basic idea is to have a lock file with the pid of the process that created it. In this way it will guarantee than only one instance of that action is being run currently on a machine.

My only problem right now is that I don't know how it should be integrated into fastlane the method I created.
Any help or feedback is appreciated :)

Here is my code:

```ruby

default_platform :ios

def runexclusive(name, &block)
  lock_recheck_sleep = 30 #wait between checks 30 seconds
  max_waited_time = 120 * (2 * lock_recheck_sleep) #max wait 2 hours

  lock_file_name = "/tmp/fastlane_#{name}.lock"
  current_pid = Process.pid

  waited_time = 0 
  loop do
    # exit the loop if:
    # - lock_file does not exist
    # or - waited more than 2h, that process must be hung somewhere
    break if !File.exist?(lock_file_name) || waited_time >= max_waited_time

    # get the current locking process pid from the lock file
    locking_pid = Integer(File.read(lock_file_name))

    # check whether the process still exists
    # break the loop if it doesn't exits
    begin
      Process.getpgid(locking_pid)
    rescue Errno::ESRCH
      File.delete(lock_file_name)
      break
    end

    # wait a little bit, then try again
    sleep lock_recheck_sleep
    waited_time += lock_recheck_sleep
  end

  # create the lock file with the current process pid
  File.open(lock_file_name, "w") do |f| 
    f.write(current_pid) 
    f.close
  end

  # execute the block
  block.call

  # remove the lock file
  File.delete(lock_file_name)
end

platform :ios do

  lane :beta do

    runexclusive("cocoapods") { 
      cocoapods
    }

  end

end
```

Cheers,
Nicolae

**Comment by plu** [comment]
It is possible to run tests in parallel on multiple simulators. I've created an example project where you can see how to achieve that: https://github.com/plu/parallel_ios_tests

Maybe this will help you implementing this feature in fastlane :)

**Comment by xfreebird** [comment]
Thanks ! I've seen it in iOS Dev Weekly issue. Amazing job. 

For now I'm using access locking solution to various resources like simulator, cocoapods etc., in my view is somehow safer, and easier to manage on a single build machine with multiple fastlane jobs running.

Your solution might be extremely useful for the snapshot tool.

I'll play with it, to see what it works.

**Comment by plu** [comment]
A bit off topic: It would also be great if `snapshot` could be less destructive. Instead of resetting all simulators, it could work with its own set by using a prefix in the name. Example:

```ruby
require 'simctl'

SimCtl.list_devicetypes.each do |devicetype|
  begin
    SimCtl.reset_device "snapshot: #{devicetype.name}", devicetype, SimCtl.runtime(name: 'iOS 9.2')
  rescue Exception => e
    # Ignore error
  end
end
```

Result:

```
-- iOS 9.2 --
    snapshot: iPhone 4s (5F7488B9-DAFC-448C-9B79-E9B0ED25E080) (Shutdown)
    iPhone 5 (6ED291B3-B4B2-478E-A3A6-9451E0F45AE8) (Shutdown)
    snapshot: iPhone 5 (28FF5328-CBD4-4F81-8C33-6E5905E14621) (Shutdown)
    snapshot: iPhone 5s (95F431AC-68D7-4FEA-8A04-C8911DABA447) (Shutdown)
    snapshot: iPhone 6 (D8D741F8-3D35-439A-AA3D-6E1DF4629578) (Shutdown)
    snapshot: iPhone 6 Plus (F764FF56-3264-4000-9596-969A8D482AE0) (Shutdown)
    snapshot: iPhone 6s (DEEF2C8C-9794-45A4-8DF2-EAA4094401B3) (Shutdown)
    snapshot: iPhone 6s Plus (EC3B16D9-FC92-4A49-A8AB-2E4CB7707733) (Shutdown)
    snapshot: iPad 2 (E6400107-C676-4C30-B9B1-F41B1CF1928D) (Shutdown)
    snapshot: iPad Retina (D0ECCA32-59B7-4934-987A-56DB8081FCE0) (Shutdown)
    snapshot: iPad Air (29341B5B-1E15-42EF-AE19-F1889D072F43) (Shutdown)
    snapshot: iPad Air 2 (7016B4E1-3466-47D7-ABA4-9F5906DBDDFB) (Shutdown)
    snapshot: iPad Pro (2BE55DAE-9D2E-4B97-9132-088FF45C765A) (Shutdown)
```

**Comment by ohwutup** [comment]
Closing this as it has been inactive for quite some time! 🐙
