### ISSUE TITLE
xcbuild-safe.sh should support chruby (and others?)

### ISSUE THREAD

**Issue by aidansteele** [fastlane/fastlane#5240]
I noticed that [`gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh`](https://github.com/fastlane/fastlane/blob/master/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh) explicitly checks for the present of either rvm or rbenv - as you can imagine, this fails in the scenario where a user is using chruby.

chruby needs the same treatment as rbenv, e.g.

```bash
if chruby-exists-or-whatever; then
  echo "chruby detected, removing env variables"
  unset RUBYLIB
  unset RUBYOPT
  unset GEM_HOME
  unset GEM_PATH
fi
```

(My bash-fu isn't strong enough to know how to check for chruby's existence.)

That said, is there any reason we don't just execute `xcodebuild` with these env vars unconditionally unset? Is there any scenario where we'd want them to be set? Surely we don't want this script to grow as the number of Ruby managers grows, but I'm out of my depth here.

**Comment by KrauseFx** [comment]
I don't have any background on this, but the original PR can be found here https://github.com/fastlane/fastlane/pull/4625. I'm more than happy to merge a PR adding chruby support. The reason why this was added in the first place is because of the way Xcode handles its Ruby environment.

**Comment by dflems** [comment]
RVM is the invasive one that needs special logic. `rbenv` and `chruby` just need the ruby environment unset.  Aside from the RVM logic, this should work fine as a catch-all for other ruby managers (at least it's worked for me with chruby).

```bash
unset BUNDLE_BIN_PATH
unset BUNDLE_GEMFILE
unset GEM_HOME
unset GEM_PATH
unset RUBYLIB
unset RUBYOPT
unset RUBY_ENGINE
unset RUBY_ROOT
unset RUBY_VERSION
unset _ORIGINAL_GEM_PATH
```

**Comment by KrauseFx** [comment]
Hey everyone, we just pushed a new _gym_ release with [gym 1.11.1](https://github.com/fastlane-old/gym/releases/tag/1.11.1), that should fix an error in `xcodebuild`. Xcode depends on system Ruby being used, and sometimes can't find the system gems. The new release should fix that error. Please disable the `use_legacy_build_api` flag, update to the latest version of _gym_ and give it a try. More information about the fixed error can be found here: https://github.com/fastlane/fastlane/issues/6495

Let us know if that fixes the issue for you. If it doesn't work still, please share the complete output with the latest version of _gym_ so we can further investigate the problem 👍 

Thanks everybody for helping resolve this issue  🚀
