### ISSUE TITLE
'Unexpected Machine Code' warning from AppStore while uploading with Deliver. 

### ISSUE THREAD

**Issue by arv1989** [fastlane/fastlane#5241]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I build and upload to App Store with Deliver, I get an email warning which includes. 

Unexpected Machine Code - Your upload contains both bitcode and native machine code. When you provide bitcode, it's not necessary to include machine code as well. To reduce the size of your upload, use Xcode 7.3 or later, or any other toolchain that removes machine code.

After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.

Regards,

The App Store team

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):fastlane 1.95.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by iv-mexx** [comment]
I get the same mail. Not yet sure if it's just a warning and the binary can be submitted anyway (thanks to processing duration 😩)

**Comment by whiskey** [comment]
Same here.
* rbenv 1.0.0
* fastlane 1.96.0
* deliver 1.13.1

**Comment by iv-mexx** [comment]
> according to the mail it's just a nice hint regarding redundant code. At least it's not blocking us from uploading new bits ¯\_(ツ)_/¯

Yeah right, I've just got the "Processing complete" mail and was able to send out a Testflight Beta.

**Comment by hjanuschka** [comment]
seems to be a issue in apple-side 😨 

http://stackoverflow.com/questions/38061045/unexpected-machine-code-warning-from-itunes-connect?rq=1

**Comment by evilDave** [comment]
It does seem to be "just a warning" and it does seem to be recent, I deployed a version with deliver on monday and did not get this email, I have just sent a new build up for the next version today and did get it.

**Comment by evilDave** [comment]
According to the SO question linked by @hjanuschka it was an apple bug. I can say that I have not seen this issue again since June.

**Comment by TKBurner** [comment]
@evilDave Awesome! Thanks for following up on this Dave. I'm going to go ahead and close it out, but if anyone sees this pop back up feel free to bump this thread. Thanks!
