### ISSUE TITLE
Add new unzip action

### ISSUE THREAD

**Issue by maxoly** [fastlane/fastlane#5247]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Add a new `unzip` action.

https://github.com/fastlane/fastlane/pull/5246

### Environment

fastlane 1.96

**Comment by KrauseFx** [comment]
Cool, thanks, I replied on #5246
