### ISSUE TITLE
fastlane init finds wrong App Name and App Identifier

### ISSUE THREAD

**Issue by jeffreyjackson** [fastlane/fastlane#5248]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

fastlane init is bringing back incorrect App Name and App Identifier - values presented are referring to private pod?

##### Complete output when running fastlane, including the stack trace and command used

using command `fastlane init`

Steps:
1.  `fastlane init`
2.  choose dev login
3.  choose team
4.  Detected Values output is shown with incorrect data.  App Name is the name of a pod I'm using, and App Identifier is org.cocoapods.PrivatePodRepo

### Configuration Files

Fastfile isn't created yet as I'm encountering issue during `fastlane init`

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.96.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by KrauseFx** [comment]
Does the process fail? It's not a big deal if it's not automatically detected, as you can easily update the configuration files

**Comment by jeffreyjackson** [comment]
Ok, sounds good - I continued with the process and I believe everything is OK.  Thank you!
