### ISSUE TITLE
Question: how to pass api_token and build_secret securely

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#5253]
I want to pass api_token and build_secret values to the crashlytics task.  I have these values in a file checked into a separate repo.  How can I pass them so that I don't have to enter the values manually when my build script runs?

**Comment by vpolouchkine** [comment]
We recommend the env variables approach (https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#environment-variables).

**Comment by npomfret** [comment]
Thanks for the reply
