### ISSUE TITLE
Importing and calling platform-specific lanes from general platform

### ISSUE THREAD

**Issue by 7mllm7** [fastlane/fastlane#5255]
I have (`react-native`) app, with both `ios` and `android` dirs inside a common dir.
I want to be able to release (execute a lane) iOS or Android independently, so I setup `fastlane init` in each of the platform dirs (which created two `fastlane/Fastfile` in each platform dir).
Android `Fastfile` roughly contains:
```
platform :android do
  lane: release_android do
    ...
  end
```
 AND iOS:
```
platform :ios do
  lane: release_ios do
    ...
  end
```

Now I also manually created a `fastlane/Fastfile` file in the common containing dir that looks like this:
```
import '../ios/fastlane/Fastfile'
import '../android/fastlane/Fastfile'

lane :release_all do
  release_android
  release_ios
end
```

However, when I run `fastlane release_all` from the main dir, it breaks with `Could not find action or lane 'release_android'`.

Any idea what I'm doing wrong here? Could it not be possible to call a platform-specific lane from a general lane?

### Environment

fastlane 1.96.0

**Comment by ohwutup** [comment]
Hey @7mllm7! Thanks for submitting the issue! Currently, the lanes can only be properly detected if there is a platform specified in the Fastfile you are calling. I'm not sure how this will reconcile with the fact that you are using two platforms, but I would try to wrap your `:release_all` lane in `platform :ios .... end` (even though I know the semantics of that don't make perfect sense).

**Comment by ohwutup** [comment]
Also, it looks like your `release_*` lanes have the colon following `lane` rather than preceding the lane name like so: `lane :release_ios` and `lane :release_android`. 🐙 🚀

**Comment by 7mllm7** [comment]
Is there then a way to call a lane in a specific platform? So if when you execute a lane from command line with `fastlane ios release`, you could also in ruby do `ios release`, instead of creating a lane named `release_ios` inside the `platform :ios` scope?
