### ISSUE TITLE
how to submit B2b (business to business) app for review

### ISSUE THREAD

**Issue by deanezra** [fastlane/fastlane#5256]
I want to automate submitting of a business to business app using the apple  volume program.

As far as I can see on the iTunes connect webpage you have to tick 'b2b'  

does fastlane support this?

**Comment by vpolouchkine** [comment]
I don't think this ever came up before. Would you mind trying and sharing the result? :)

**Comment by deanezra** [comment]
I would love to try it, not sure how I would go about it.

I have read that there is a 'b2b' tick box somewhere on the iTunes app webpage.

Do you suggest I create the app entry manually via web page then use 
fastlane to do app submits after that?
