### ISSUE TITLE
pilot does not read `PILOT_TEAM_NAME` from environment

### ISSUE THREAD

**Issue by tmm1** [fastlane/fastlane#5257]
If I set `PILOT_TEAM_NAME` and invoke `pilot`, it will still ask me to pick a team interactively.

However, if I run `pilot -r "$PILOT_TEAM_NAME"` it works.

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by KrauseFx** [comment]
@tmm1 I worked on this issue a few days ago, could you try again with the latest code on `master`?
