### ISSUE TITLE
Could not install WWDR certificate

### ISSUE THREAD

**Issue by robertofrontado** [fastlane/fastlane#5259]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

After a while without using this, it starts throwing this error when I try my lane first_release, so I updated the gems fastlane and sigh but it still happens

```
+-------------------------------------+----------------------+
|                   Summary for sigh 1.8.0                   |
+-------------------------------------+----------------------+
| adhoc                               | false                |
| skip_install                        | false                |
| development                         | false                |
| force                               | false                |
| username                            | username@gmail.com |
| ignore_profiles_with_different_name | false                |
| skip_fetch_profiles                 | false                |
| skip_certificate_verification       | false                |
+-------------------------------------+----------------------+

[03:31:08]: Starting login with user 'username@gmail.com'
[03:31:10]: Successfully logged in
[03:31:10]: Fetching profiles...
[03:31:10]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: com.username.mock
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1062  100  1062    0     0   1518      0 --:--:-- --:--:-- --:--:--  1519
security: SecKeychainItemImport: UNIX[Invalid argument]

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Match] "Could not install WWDR certificate" in Travis-CI
   https://github.com/fastlane/fastlane/issues/4798 [closed] 18 💬
   5 weeks ago

➡️  Could not install WWDR certificate
   https://github.com/fastlane/fastlane/issues/2852 [closed] 6 💬
   5 weeks ago

➡️  WWDR certificate install keychain search
   https://github.com/fastlane/fastlane/pull/3621 [closed] 7 💬
   05 Apr 2016

and 20 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20install%20WWDR%20certificate&type=Issues&utf8=✓

[!] Could not install WWDR certificate

```
### Configuration Files

Fastfile:

``` ruby
lane :first_release do

    config = SomeScript.new

    sigh(
      force: true,
      app_identifier: config.appId
      )
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    gym

end
```
### Environment

fastlane version (run `fastlane -v`): 1.96.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by semka** [comment]
I'm experiencing the same right now on one of my CI servers:

```
fastlane 1.96.0
```

```
[17:12:26]: ------------------
[17:12:26]: --- Step: sigh ---
[17:12:26]: ------------------

+-------------------------------------+--------------------+
|                  Summary for sigh 1.8.0                  |
+-------------------------------------+--------------------+
| app_identifier                      | *                  |
| adhoc                               | false              |
| skip_install                        | false              |
| development                         | false              |
| force                               | false              |
| username                            | some-apple@id.com |
| ignore_profiles_with_different_name | false              |
| skip_fetch_profiles                 | false              |
| skip_certificate_verification       | false              |
+-------------------------------------+--------------------+

[17:12:27]: Starting login with user 'some-apple@id.com'
[17:12:41]: Successfully logged in
[17:12:41]: Fetching profiles...
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  1062  100  1062    0     0    797      0  0:00:01  0:00:01 --:--:--   797100  1062  100  1062    0     0    797      0  0:00:01  0:00:01 --:--:--   797
security: SecKeychainItemImport: UNIX[Invalid argument]
[17:12:53]: -------------------
[17:12:53]: --- Step: slack ---
[17:12:53]: -------------------
[17:12:54]: Successfully sent Slack notification
[17:12:54]: Variable Dump:
[17:12:54]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios dev", :SCHEME_PROD=>"xxx", :SCHEME_DEV=>"MGRDashboard-dev", :PORTAL_ID_PROD=>xxx, :PORTAL_ID_DEV=>xxx, :PORTAL_ID_STAGING=>xxx, :APP_NAME=>"xxx"}
[17:12:54]: Could not install WWDR certificate
```

**Comment by vpolouchkine** [comment]
@robertofrontado Are you running this in a CI cycle as well?

**Comment by robertofrontado** [comment]
@vpolouchkine Yes, I'm using jenkins, but I'm getting that error if I ran it in the terminal too

**Comment by vpolouchkine** [comment]
Do you have any non-ANSI characters in your profile name?

**Comment by robertofrontado** [comment]
Nope, it was working a month ago

**Comment by sashakid** [comment]
Guys, any updates to this thing? My fastlane has broken and I'm not big specialist to fix it, please help, I have the same issue from today :-)

**Comment by KrauseFx** [comment]
> [17:12:54]: Could not install WWDR certificate

Does it work when you manually code sign using Xcode? Have you followed our [Code Signing Guide](https://github.com/fastlane/fastlane/tree/master/fastlane/docs/Codesigning)?

**Comment by sashakid** [comment]
@KrauseFx I've not followed "Code Signing Guide" before, shoud I get rid of `cert` and `sigh` in favor of `match`? Will it be simpler? 
Finally, I've fixed the issue with WWDR by deleting and reinstalling WWDR on my local machine. But after updating fastlane there are many other issues which have broken my lane `beta` :-(

**Comment by rompic** [comment]
same here :(

**Comment by idomizrachi** [comment]
I had this issue on a jenkins slave.
What solved it was importing the WWDR certificate to "login" keychain in addition to the "System" keychain

**Comment by TKBurner** [comment]
@idomizrachi Thanks for letting me know! Really glad to hear everyone is up and running. Thanks!

**Comment by mcany** [comment]
hi all,

I am receiving the same error now. I have tried both on my CI tool Travis and on my local machine but the behaviours are the same. I have checked my keychain and i have the certificate both on Login and System folder. I also checked that the certificate is still valid. I have the latest version of fastlane. Any suggestion would be appreciated. Thanks in advance

**Comment by TKBurner** [comment]
Hi @mcany Thanks for reaching out. Can you let me know what version of OS X your are using, also will you let me know what versions of Xcode you have installed?

Thanks!

**Comment by mcany** [comment]
hey @TKBurner thanks for your help. I am currently using OSX 10.11.6 and Xcode 7.3.1. I believe I also updated my fastlane and match versions

**Comment by TKBurner** [comment]
Hi @mcany Can you look in your keychain and see if there is an Apple Developer Cert? Thanks!

**Comment by mcany** [comment]
hi agian @TKBurner can you make it more clear, there is a developer cert in my keychain but why does it need a developer cert when it signs with release appstore cert? or do you mean a different cert that i didnt understand, maybe from WWDR?

**Comment by TKBurner** [comment]
@mcany Can you check out the explanation in #264 it seems like that is relevant here. Thanks!

**Comment by mcany** [comment]
@TKBurner No chance, it is not related to our case. We are trying yet still not able to fix the issue.

**Comment by TKBurner** [comment]
@mcany Do you have a WWDR cert in your system and login keychain? Can you delete it and then see if it works?

If not, check out the steps here on BuddyBuilds docs http://docs.buddybuild.com/docs/installing-apples-updated-intermediate-wwdr-certificate

**Comment by geoHeil** [comment]
I have the same problem for fastlane version `1.104.0`
But re-installing certificates did not help. I even put them In both directories
![certs installed](https://cloud.githubusercontent.com/assets/1694964/18781291/644fef30-8181-11e6-8072-74dde70acfa8.jpg)

**Comment by KrauseFx** [comment]
@geoHeil Make sure to also list the expired certificates in the Keychain, and delete all of them. Can you build using Xcode directly?

**Comment by geoHeil** [comment]
Indeed I deleted all expired certificates. A build with Xcode directly
works fine.
Felix Krause <notifications@github.com> schrieb am Fr. 23. Sep. 2016 um
19:33:

**Comment by TKBurner** [comment]
@geoHeil Thanks for following up. You WWDR cert consists of two parts the certificate and the secret key. Your keychain should show a triangle next to the WWDR that lets you expose the secret key. It appears that is the problem here.

**Comment by geoHeil** [comment]
I see so how can I obtain the secret key if it is missing?

**Comment by TKBurner** [comment]
@geoHeil Try downloading it directly from apple and installing it after deleting the existing one. The secret key is generated on your machine.

**Comment by geoHeil** [comment]
@TKBurner I used https://www.apple.com/certificateauthority/ However, the key does not seem to be created.

**Comment by TKBurner** [comment]
@geoHeil Have you followed these steps: http://docs.buddybuild.com/docs/installing-apples-updated-intermediate-wwdr-certificate

Thanks!

**Comment by KrauseFx** [comment]
Hey @geoHeil, do you have multiple keychains? Are you using _match_ or _cert_ to make sure the certificate is installed locally?

**Comment by geoHeil** [comment]
We use match. Indeed, that could be a problem. We needed to reset the
password once. I think I this generates a new key chain.
Felix Krause <notifications@github.com> schrieb am Fr. 7. Okt. 2016 um
04:16:

**Comment by TKBurner** [comment]
@geoHeil Can you check you check your system and login keychains and let me know if this cert appears in both places? Thanks for working with me on this. Hope you have a great day! Also are you running into issues exporting from Xcode as well? Thanks!

**Comment by geoHeil** [comment]
Nope Xcode worked fine. But it seems to work now after finally fixing the
keychain.

Todd Burner <notifications@github.com> schrieb am Di., 11. Okt. 2016 um
16:43 Uhr:

**Comment by TKBurner** [comment]
@geoHeil Glad to hear you got up and running. 👍

**Comment by jwitcig** [comment]
I am having the " Could not install WWDR certificate" issue as we.. I have read all of the comments I can possibly comprehend and haven't gotten anywhere. I am not a professional developer so if somebody could explain this in a friendly way to me, it would be greatly appreciated.

**Comment by clementmangin** [comment]
@jwitcig Please see https://github.com/fastlane/fastlane/issues/6993#issuecomment-279080936, where I explain how I overcome the issue.

**Comment by GoodMirek** [comment]
Additional info, which might help to someone, as I spent a good deal of time chasing this issue.
The problems described in this issue #5259 and in issue #6993 are not identical, although both can be solved by manually reordering the keychain search list from GUI, as described in #6993.
However, if keychain is recreated before each CI build and deleted afterwards, manual reordering of the search list is not suitable approach.

This issue #5259 is indicated by following line in `fastlane` output:
```
security: SecKeychainItemImport: UNIX[Invalid argument]
```
while the issue #6993 is indicated by a different line in `fastlane` output:
```
security: SecKeychainItemImport: The specified keychain could not be found.
```
In my case, this issue #5259 was caused by setting keychain search list to an empty string via command:
```
security list-keychains -d user -s ""
```
It results in following keychain search list:
```
security list-keychains
    "/Users/administrator/Library/Keychains"
    "/Library/Keychains/System.keychain"
```
`"/Users/administrator/Library/Keychains"` is a directory, what `match` fails to handle. The directory remains on first position of the list even when an another new keychain is added.
The issue can be solved from command line by setting the list to an explicit string, e.g.:
```
security list-keychains -s "/Users/admin/iphone-app/ci.keychain-db"
```
This issue happens only on Macos 10.12 Sierra, not on Macos 10.11 El Capitan.

**Comment by wilferrel** [comment]
Just in case anyone follows the above and still receives same error, I was getting this on jenkins so seems like there needs to be a keychain available for jenkins user that resides in the Library directory for it. So I copied my keychain over there and it worked. Jenkins user directory was `/Users/CiUser/.jenkins/Library/Keychains/login.keychain`    My original directory for macOS user is `/Users/CiUser/Library/Keychains/login.keychain` I hope this helps..

**Comment by romk1n** [comment]
the issue has resurfaced with Xcode 8.3.3

**Comment by GoodMirek** [comment]
I run Xcode 8.3.3 and it works for me correctly, the same way as it does in Xcode 8.3.2.

@romk1n I assume your issue has a different cause than Xcode 8.3.3, but it is difficult to guess what the issue can be without any inputs. If your issues persisted, I would recommend to open another issue and fill in all information, required by the issue template.

**Comment by romk1n** [comment]
@GoodMirek oops forgot to include some output sorry. we using as suggested a separate keychain. 

```
[15:00:35]: 🔓  Successfully decrypted certificates repo
[15:00:35]: Installing certificate...
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1062  100  1062    0     0   5706      0 --:--:-- --:--:-- --:--:--  5740
security: SecKeychainItemImport: Unknown format in import.
+-----------------------------+---------------------------+
|                      Lane Context                       |
+-----------------------------+---------------------------+
| DEFAULT_PLATFORM            | ios                       |
| PLATFORM_NAME               | ios                       |
| LANE_NAME                   | ios build_development_ipa |
| GIT_REPO_WAS_CLEAN_ON_START | true                      |
+-----------------------------+---------------------------+
[15:00:36]: Could not install WWDR certificate
```

**Comment by jackhst** [comment]
hi 
I am receiving the same error ,

security list-keychains
    "/Users/Shared/Jenkins/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"

security find-certificate -c  xxxxxxxxxxx
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
 
Using the command line is OK, but Jenkins has the same error
