### ISSUE TITLE
[sigh] Mirror download behaviour of Cupertino

### ISSUE THREAD

**Issue by sharkusmarkus** [fastlane/fastlane#5262]
As Cupertino has been broken for a while, and all suggestions seem to point to Sigh as the way forward, I have switched over to use Sigh.

There is one functionality of Cupertino that, unless I'm missing something, does not exist in Sigh, which is to just download a profile by name. I don't want to have to specify the bundle ID, nor have certificates checked, nor have a new profile created if the name is not found. I just want the ability to download the profile I've asked for.

I fully understand that Sigh is trying to be really useful and not let you get into a position where your build will not compile / sign / package / upload because provisioning or code signing is incorrect, and I do appreciate that, but I want to mirror the previous behaviour Cupertino had.

I may be in a somewhat unique position, having access to an enterprise and app store portal, and this allows me to provision and sign a build using enterprise credentials without having to change the bundle ID. The problem is I need to explicitly provide a bundleID, so I have to supply "*" to get Sigh to actually download the profile, as using the default bundle ID will fail, as the ID isn't on the enterprise portal.

**Comment by vpolouchkine** [comment]
Thanks for your interest in `sigh`. This is not something that we're currently looking at, but I'll keep this thread open for any upvotes. In the meantime, take a look at [`spaceship`](https://github.com/fastlane/fastlane/tree/master/spaceship) – perhaps you'll be be able to code this functionality yourself. Cheers.

**Comment by sharkusmarkus** [comment]
Thanks. I dipped into spaceship. Was a bit overwhelming at first, given I've not really done anything with ruby, but after a few hours I managed to knock up the following code below, which seems to mirror what Cupertino would do.

`#!/usr/bin/env ruby
# This script will use Spaceship - part of the Fastlane tools - to login to the developer portal and download the specified provisioning profile
the_user_name = ARGV[0]
the_user_password = ARGV[1]
the_team_id = ARGV[2]
the_profile_name = ARGV[3]
base_profile_path = ARGV[4]


require "spaceship"
begin
	puts ""
	# Login
	puts "   Logging into Developer Portal as: '#{the_user_name}'"
	puts ""
	Spaceship.login(the_user_name, the_user_password)
	
	# Select team
	puts "   Selecting team: '#{the_team_id}'"
	puts ""
	Spaceship.client.team_id = the_team_id

	# Find the exact profile we're looking for
	puts "   Finding profile named: '#{the_profile_name}'"
	puts ""
	my_profile = Spaceship.provisioning_profile.all.find { |p| p.name == the_profile_name }

	# Download the profile
	the_profile_name = the_profile_name.tr(' ', '_')
	the_profile_path = "#{base_profile_path}#{the_profile_name}.mobileprovision"
	puts "   Downloading profile named named: '#{the_profile_name}' to: '#{the_profile_path}'"
	puts ""
	File.write(the_profile_path, my_profile.download)
end
`

**Comment by KrauseFx** [comment]
Perfect, great to hear you found a solution 👍
