### ISSUE TITLE
Screengrab Device List

### ISSUE THREAD

**Issue by kd8ssq** [fastlane/fastlane#5266]
Any chance you'll include a device list in the Screengrabfile?  Something similar to the device list that is in the Snapfile.

I know that you have to manually create each avd that you want to test on, but even if the device list was a list of the names of the created emulators that you wanted to test on.  That way you wouldn't need to launch each emulator prior to running the screengrab script.

**Comment by vpolouchkine** [comment]
Thanks for the feedback! Keeping this open for upvotes.
