### ISSUE TITLE
Simulator Focus (Feature Request)

### ISSUE THREAD

**Issue by jeffreyjackson** [fastlane/fastlane#5284]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Not an issue, but potential feature request.

Is it possible to keep iOS simulator in the background while running snapshot?  I have a build server running fastlane and few other things, but may need to keep focus on something else (like a VM, or Xcode).  Is there a tweak or setting that can be added to keep simulator from taking focus?

Thanks so much for all of the effort in building fastlane.  You guys are awesome.  

##### Complete output when running fastlane, including the stack trace and command used
N/A
### Configuration Files
N/A
### Environment
N/A
fastlane version (run `fastlane -v`):
1.97.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

**Comment by ohwutup** [comment]
Hey @jeffreyjackson! Thanks for the feature request, this is definitely a cool feature that would be nice to have. We would be happy to review a PR with these changes and can keep discussion going if you would need any help! I am going to close it for now and mark it as a feature request, but let us know if you have some time to bite off this chunk of work and we can reopen the issue for discussion! Thanks! 🐙

**Comment by KrauseFx** [comment]
As far as I know we're using `xcodebuild` to launch the simulator and its tests. If there is a way to tell the simulator to launch in the background, let us know 👍

**Comment by jeffreyjackson** [comment]
Would putting this key in the Info.plist of simulator.app be acceptable?
```
<key>LSBackgroundOnly</key>
<string>True</string>
```

**Comment by KrauseFx** [comment]
We already have some of those work-arounds to make `snapshot` work:
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/fixes/hardware_keyboard_fix.rb
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/fixes/simulator_zoom_fix.rb

We're happy to accept a PR adding a new file, applying the patch, as I think it's really useful 👍

**Comment by jeffreyjackson** [comment]
Cool, I'll try to get to it in the next couple days. Unless someone beats me to it!  Thank you!

**Comment by KrauseFx** [comment]
Cool, thanks @jeffreyjackson 👍

**Comment by jeffreyjackson** [comment]
Turns out this flag doesn't do what I originally thought.  Will close this until I can find a different option.  🍻

**Comment by KrauseFx** [comment]
Cool, thanks @jeffreyjackson for looking into this, keep us up to date :+1:
