### ISSUE TITLE
[deliver] Using relative screenshot path in Preview.html

### ISSUE THREAD

**Issue by cnsdato** [fastlane/fastlane#5286]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
We have a common Fastfile for all our apps and one Fastfile for each app which includes the common. The common defines the lanes and on the app specific Fastfile only some ENV`s are defined.

When running deliver we must set the `screenshots_path` width `Dir.pwd` + "..." or `File.dirname(__FILE__) + "..."` so deliver find the screenshots. But then we have the full path in the Preview.html which is not good when checking in the Preview.html file into SCM.

Please cut off the base path in delviver internally.

### Configuration Files
Fastfile (app specific):
```ruby
import "../../../../fastlane/Fastfile"

# our internal name of the app (also the dir is named like this)
ENV["appname"] = "xxxx"
# the apple id
ENV["username"] = "xxxx"
# the app identifier
ENV["app_identifier"] = "xxxx"
# the team id
ENV["team_id"] = "xxxx"
```

Fastfile (common):
```ruby
...

lane :upload_metadata do
  deliver(
    username: ENV["username"],
    app_identifier: ENV["app_identifier"],
    team_id: ENV["team_id"],
    #skip_screenshots: true,
    metadata_path: Dir.pwd + "/metadata",
    screenshots_path: Dir.pwd + "/screenshots"
  )
end

...
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.97.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by vpolouchkine** [comment]
Thanks for the feedback!
