### ISSUE TITLE
[deliver] Add old Release notes to new version

### ISSUE THREAD

**Issue by appcelerate** [fastlane/fastlane#5288]
How can i copy the old release notes to the new version. Because some of of the release notes are everytime the same like please rate the app, ... and then only the changes will change but this i will do manually at itunesconnect.

Any idea how to do this?

Thanks :)

**Comment by ohwutup** [comment]
Hey @appcelerate, there currently is not a way to do this, but if you would like to submit a PR with this feature, that would be amazing! I am going to close this issue for now and mark it as a feature request and please feel free to open it if you have some time to bite off that work! 🚀
