### ISSUE TITLE
Unable to update from version 1.93 to 1.97

### ISSUE THREAD

**Issue by OxenBoxen** [fastlane/fastlane#5291]
### New Issue Checklist

- [ (tried) ] Updated fastlane to the latest version 
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hey guys, I'm running into a weird bug when trying to update fastlane.

`fastlane -v` gets me fastlane 1.93.1 , and a list of improvements to 1.97 , 1.6, etc as well as commands for updating fastlane:  When I type `sudo gem update fastlane`, I type in my os pw, then get `Updating installed gems` , `Nothing to update` . I am using RBenv version: 1.0.0,  and ruby version: ruby 2.3.1.

Curious if this is a fastlane issue? Or a rbenv/ruby issue... thanks for any help / insights.

**Comment by ohwutup** [comment]
Hey @OxenBoxen, you should be able to just run `gem update fastlane` without the `sudo`. `sudo` is only necessary if you are using system ruby not if you are using `rbenv` or another ruby manager.
