### ISSUE TITLE
fastlane no longer installs out of the box as of June 30, 2016

### ISSUE THREAD

**Issue by emmby** [fastlane/fastlane#5294]
### Issue Description

Installing fastlane on a fresh mac with OS X El Capitan no longer works out of the box, because the activesupport gem was updated on 6/30/2016 to version 5.0, and now requires ruby 2.2.2 or later (which does not ship with osx)

https://rubygems.org/gems/activesupport

```
Mac-Pro:~ build$ sudo gem install fastlane
ERROR:  Error installing fastlane:
	activesupport requires Ruby version >= 2.2.2.
```

As a workaround, doing the following works around the issue:

```
sudo gem install activesupport -v 4.2.6
sudo gem install fastlane
```

**Comment by KrauseFx** [comment]
Thanks for the report, we're looking into this 👍

**Comment by KrauseFx** [comment]
Preparing a new release now 🚀
