### ISSUE TITLE
unable to create a group or associate with a group using produce

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#5295]
### New Issue Checklist
- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
% produce --verbose group -g group.test -n "Test Group"

INFO [2016-07-01 17:25:49.80]: Successfully logged in
INFO [2016-07-01 17:25:50.43]: Creating new app group 'Test Group' with identifier 'group.test' on the Apple Dev Center

Looking for related GitHub issues on fastlane/fastlane...
Search query: Apple provided the following error info:
    There were errors in the data supplied. Please correct and re-submit.
    An Application Group with Identifier &#x27;group.test&#x27; is not available. Please enter a different string.

URL: https://api.github.com/search/issues?q=Apple%20provided%20the%20following%20error%20info:%0A%09There%20were%20errors%20in%20the%20data%20supplied.%20Please%20correct%20and%20re-submit.%0A%09An%20Application%20Group%20with%20Identifier%20&%23x27;group.test&%23x27;%20is%20not%20available.%20Please%20enter%20a%20different%20string.+repo:fastlane/fastlane
➡️  10.11
   https://github.com/jwise/HoRNDIS/issues/42 [open] 408 💬
   an hour ago

➡️  Meteor 1.3 *early beta* (Cordova)
   https://github.com/meteor/meteor/issues/6050 [closed] 171 💬
   3 weeks ago

➡️  Discuss2

% produce associate_group -a com.mine.TestGroups  group.created.via.browser 

[17:28:38]: Successfully logged in
[17:28:39]: Validating groups before association
[17:28:39]: Finalising association with 1 groups
[17:28:39]: Done!

But if you go to the dev center the group association is not setup. See screenshot below.


```

<img width="673" alt="screen shot 2016-07-01 at 5 30 55 pm" src="https://cloud.githubusercontent.com/assets/3322496/16537199/d02e0910-3fb1-11e6-89c4-f76c44e6efcd.png">
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
directly invoking produce.
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.97.1
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by lakamsani** [comment]
Hi, Any feedback on whether you can reproduce it and/or plans to fix? Thanks.

**Comment by vpolouchkine** [comment]
Can you please try a different group identifier? Looks like `group.test` is already taken.

**Comment by lakamsani** [comment]
Hi, I showed group.test just as an example. For our app we are actually use reverse DNS name which we are fairly sure is accurate. 

The produce command with associate_group looks like this. <corp> is our unique DNS domain. 

produce associate_group -a <app-id> group.com.<corp>.apps.debug

It prints this:

[01:05:30]: Successfully logged in
[01:05:31]: Validating groups before association
[01:05:31]: Finalising association with 1 groups
[01:05:32]: Done!

But when we got into Dev portal, the  app id's app groups setting is disabled under Application Services: (see attached screen shot). 

<img width="566" alt="screen shot 2016-08-16 at 1 12 45 am" src="https://cloud.githubusercontent.com/assets/3322496/17692460/b7813d04-634e-11e6-944e-be3168602ea6.png">

**Comment by vpolouchkine** [comment]
Thanks for the detailed writeup. Looks like a bug to me!

**Comment by gcamp** [comment]
Having the same problem here

**Comment by gcamp** [comment]
Actually got it working simply by ```enable_services --app-group``` before ```associate_group```. It would however be better that ```associate_group``` returns an error or enable the service when that call is done.

**Comment by lakamsani** [comment]
@gcamp  thanks for that workaround.

**Comment by TKBurner** [comment]
@gcamp Thanks for stepping in. We'd love to see a PR around this 👍
