### ISSUE TITLE
pilot - batch add/remove users

### ISSUE THREAD

**Issue by inteist** [fastlane/fastlane#5307]
Using import is not feasible/convenient sometimes and there is no alternative for mass remove users as far as I am aware. 

Using add/remove works but requires login for each operation. It would be great if the add/remove operation could be batched using a file of line by line emails to add/remove.

**Comment by KrauseFx** [comment]
Yeah, great idea, not sure about how the API should look like, what do you suggest? To have full control, you can always use spaceship directly to integrate it into your existing server system 👍

**Comment by inteist** [comment]
Hi, glad you like the idea. Not sure what you mean by API. I am using pilot from command line so maybe just add a switch `-file`  – something like:

Ideally it would be `-f` but `-f` is taken for the `add` command.

`pilot add -u user@email.com -file userlist.csv`

`pilot remove -u user@email.com -file userlist.csv`

in the case of remove the format of the file would be just emails on new line and in case of add it would be the standard csv `first,last,eml@domain.com`

full add command to add user to an app would be:
`pilot add -u user@email.com -file userlist.csv -a com.example.SomeApp`

**Comment by inteist** [comment]
for the remove command (and actually for the add as well) using semicolon to separate different users to add/remove could be also option:

e.g.
pilot remove -u user@email.com  eml1@a.com; eml2@a.com; eml3@a.com 

for quick add/removal of several users without using a file.

**Comment by KrauseFx** [comment]
Why can't you use the `pilot import` feature again? What's missing or not working as expected?

**Comment by inteist** [comment]
For the import, and I must preface this with the note that I used it while there were issues with the pilot recently (apple changing the endpoint) I have experienced the following:  

Importing users would import the users to external users (I had some users imported via pilot and some directly from ITC) but when I tried to add them to the app, ITC would just say "Could not process your request" or something like that with no details as to error and do nothing. I figured that it does not like some emails (and there were some wrong emails imported as well) ITC and/or pilot gladly imported them but then I could not add them to the app via ITC. This was pretty frustrating. I ended up deleting all of them and adding one by one via pilot which worked great but took like 5 hours to complete for ~2K users.

And the remove does not have mass remove afaict. And I actually need it to remove dormant users. My plan was to use pilot list and then some regex manipulation to get users who did not install the app and remove them. Would be great if that can be done within pilot e.g. `pilot remove --all --inactive` or something along these lines.

**Comment by jaleksynas** [comment]
You can specify as many to add/remove on a single command line...
`pilot add -u <login.email.address> email1@foo.com email2@foo.com`;  only a single login is performed.  `pilot remove` works similarly.

**Comment by TKBurner** [comment]
@jaleksynas Thanks for stepping in here! Hope you have a great weekend coming up.

**Comment by inteist** [comment]
@jaleksynas would that work with -f FIRSTNAME -l LASTNAME -e EMAIL ? I think I tried and could not make it work.

**Comment by TKBurner** [comment]
@inteist Thanks for following up. Did you get it working? I think for multiple users you are going to want to use import if you want those fields imported. Thanks!

**Comment by inteist** [comment]
@TKBurner no, I do not think it is possible with the current syntax the `add` command supports.

**Comment by TKBurner** [comment]
@inteist Correct, you'll need to use the import function instead. Thanks!

**Comment by inteist** [comment]
@TKBurner did you miss the part where I specifically say that the import has inherent issues? Why do you just close a perfectly legitimate idea which was commented by the project leader as being such. That's pretty upsetting the way this got handled. @jaleksynas swings by with an absolutely inadequate suggestion which does not address the problem and then you close the issue without it being resolved. I am gravely disappointed.

**Comment by inteist** [comment]
@KrauseFx, you should choose who you assign the issues to follow up on more carefully perhaps in the future.

**Comment by KrauseFx** [comment]
Thanks for the feedback! I completely understand where you're coming from and we're very grateful for all feedback we receive from the community, it's what makes fastlane so great 😃 

Unfortunately, we don't have the ability to tackle every suggestion and idea, which is why we invested time and energy to make the [plugin architecture](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md) which allows anyone to create something that works with fastlane. This in combination with [spaceship](https://spaceship.airforce) you can easily build something that perfectly fits your needs. For your issue around importing, could you submit a separate issue with steps to reproduce so we can figure out what's going on and get a fix out for you? If you find a solution for it, feel free to submit a pull request, and we would be more than happy to review and merge it :+1:

**Comment by inteist** [comment]
@KrauseFx, thanks for responding. 

Being on a very small team, I totally understand the need for prioritization. My disappointment here is with the fact that the suggestions were not really helpful and/or addressed the problem and the proposed "final solution" said to use what I stated could not be used in the first place. I'd rather have no response here than a response showing that the person responding did not bother to read and/or understand the problem.

I would be glad to implement this and perhaps even submit a PR but not being familiar with Ruby *at all* I can't, unfortunately, expect to waltz into such a big project and hack what I need to do in a reasonable amount of time. 

Thanks for such a great project, it is appreciated. I just hope in the future the dev. relations guys would take the time to understand the issue at hand in a bit more depth before responding.

**Comment by inteist** [comment]
P.S. The issue with importing is **very** simple. Import seems to chew up anything you give it, including emails that are not legitimate whilst iTunesConnect would not allow adding such emails to a project and it would not say which one causes an issue. 

I did check that even after running (several) regexes to identify illegal email addresses and removing them, there were still some emails that look legitimate but apparently are not to ITC. 

Given that the external beta testers are usually app users, it is expected that the emails would be collected directly from users who can make mistakes and going over thousands of emails one by one and validating them is simply impractical. Maybe we are doing something inherently wrong in how we do this i.e. not running thorough validation on data collected at collection time but this goes back to resources and UX and this is where automated tools come in handy to solve such problems. Hope this feedback is somewhat useful.
