### ISSUE TITLE
pilot crashes with: submit_testflight_build_for_review!': [!] undefined method....

### ISSUE THREAD

**Issue by kikolobo** [fastlane/fastlane#5309]
### Issue Description
This issue happens when running my beta lane: fastlane beta  

Everything runs soothly, until it tries to submit the app for review after the processing finishes with iTunes.

Pilot crashes the process with : submit_testflight_build_for_review!':[!] undefined method...

This happens in the pilot step in my fastfile to distribute to external:
```
pilot(distribute_external: true, "Some text here")
```

##### Complete output when running fastlane, including the stack trace and command used
```
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:618:in `submit_testflight_build_for_review!': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/build_manager.rb:127:in `distribute_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/build_manager.rb:43:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:87:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Fastfile

Fastfile:
```ruby
desc "Submit a new Beta Build to Apple TestFlight"  
lane :beta do
  
    #default_payloads: [:test_result, :git_branch]
    #PULL GIT WITH LATEST CHANGES
    slack(
      message: "[FastLane] Starting BETA Integration.",
      success: true,        # optional, defaults to true   
      default_payloads: []
    )   
    
    ensure_git_branch(
      branch: 'develop'
      )
    
    git_pull                
    

  #SIGN PROVISIONING PROFILES      
  slack(
    message: "[FastLane] Signing Provisioning Profiles.",
    success: true,        # optional, defaults to true   
    default_payloads: []
  )   
  
  sigh

    #INCREMENT BULD NUMBER
    increment_build_number    
    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    # add_git_tag(tag: "testflight-#{build_number}")      

    #BUILD APP
    slack(
      message: "[FastLane] Compiling Build: #{build_number}",
      success: true,        # optional, defaults to true   
      default_payloads: []
    )   


    gym(scheme: "MyApp",
         clean: true        
      )       

    #COMMIT VERSION
    commit_version_bump(
      message: 'minor [CI] Build Bump'
      )    

      #PUSH GIT
      push_to_git_remote
      
      
    slack(
      message: "[FastLane] Build #{build_number} Now Commited. \n Delivering App. ",
      success: true,        # optional, defaults to true   
      default_payloads: []
    )   
      
    pilot(distribute_external: true, 
        changelog: "We constantly improve our app and deliver upgrades. This release includes bug fixes and performance enhancements."
    ) # Also Distribute to external testers
                           
    end
```

### Environment
fastlane version (run `fastlane -v`): fastlane 1.97.2

**Comment by kikolobo** [comment]
Nope. Not code signing...  Otherwise I wouldn't be able to trigger the release manually using iTunes connect website...

**Comment by kikolobo** [comment]
Anyone?

**Comment by VPTeamMobile** [comment]
I have exactly the same error. I was working well until last week.
```
pilot(
                distribute_external: true,
                changelog: "Application XXXX",
                ipa: "./fastlane/ipa/prodRelease/prodRelease.ipa")
```

And the issue : 

```
and 138 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]'%20for%20nil&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:618:in `submit_testflight_build_for_review!': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/build_manager.rb:127:in `distribute_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/build_manager.rb:43:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:97:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by AvanKempen** [comment]
I have the same issue when setting distribute_external to true:

`ERROR [2016-07-06 13:38:59.69]: undefined method `[]' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | increment_build_number              | 0           |
| 5    | sigh                                | 13          |
| 6    | gym                                 | 15          |
| 7    | pilot                               | 534         |
+------+-------------------------------------+-------------+

ERROR [2016-07-06 13:38:59.69]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60[]'%20for%20nil+repo:fastlane/fastlane
➡️  "undefined method `strip' for nil:NilClass" during init
   https://github.com/fastlane/fastlane/issues/4330 [open] 6 💬
   a week ago

➡️  pilot crashes with: submit_testflight_build_for_review!': [!] undefined method....
   https://github.com/fastlane/fastlane/issues/5309 [open] 4 💬
   an hour ago

➡️  Pilot tool is crashing with undefined method 'strip' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/3238 [open] 0 💬
   08 Mar 2016

and 138 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]'%20for%20nil&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.27.2/lib/spaceship/tunes/tunes_client.rb:618:in `submit_testflight_build_for_review!': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/build_manager.rb:127:in `distribute_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.9.2/lib/pilot/build_manager.rb:43:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:197:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:182:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:181:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:107:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:106:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.97.2/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE`

**Comment by kikolobo** [comment]
So it seems that no-one from the team is watching these thread 😊

Maybe because the bot did not tagged it or something.. This is an annoying bug.. Any help would be appreciated very very much!

KnockKnock: @KrauseFx  @TKBurner  @asfalcone

**Comment by tildedave** [comment]
I'm also seeing this with a script that calls spaceship directly.

When I run with VERBOSE=1, I get the error:

```
<String>There is no route for the path 'apps/691096785/platforms/ios/trains/2.23.0/builds/4342/submit/start'.</String>

rake aborted!
NoMethodError: undefined method `[]' for nil:NilClass
```

I see an entry with buildVersion = 4342 and trainVersion = 2.23.0 returned from the previous `ra/apps/691096785/trains/?testingType=external` call, so I'm not certain why getting the exact build isn't working.

**Comment by tildedave** [comment]
One thing I noticed when dealing with the iTunes connect control panel is that it POSTed to the following URL `apps/691096785/platforms/ios/trains/2.23.0/builds/4340/review/submit` to submit a related build on clicking through adding a build for external testing (did not set its testing status to true).

**Comment by kikolobo** [comment]
I can't believe we still got no official comment 😊  Are we in the right issue reporter?
@KrauseFx @TKBurner @asfalcone

**Comment by tildedave** [comment]
I have a WIP change to fix my own script that I'll try to turn into something that I can contribute back here.  Noticed that other people are having this problem too: https://github.com/fastlane/fastlane/issues/5394

Basic approach was to get all the data from the build train `apps/:appId/trains/?testingType=extermal` instead of querying `apps/:appId/platforms/ios/trains/:version/builds/:build`, and then submitting to `apps/:appId/platforms/ios/trains/:version/builds/:build/review/submit` (rather than `submit/start`)

**Comment by tmm1** [comment]
> Basic approach was to get all the data from the build train apps/:appId/trains/?testingType=extermal instead of querying apps/:appId/platforms/ios/trains/:version/builds/:build, and then submitting to apps/:appId/platforms/ios/trains/:version/builds/:build/review/submit (rather than submit/start)

Can you share the changes to your script, specifically for the first part? I can put together a patch to fastlane.

**Comment by tildedave** [comment]
Okay... don't judge me 😄 

`build` is the Spaceship base Build

```
+      build_info = JSON.parse(build.raw_data.to_json)
 +      build_info.delete("build_train")
 +
 +      build_info['buildTestInformationTO']['details'].each do |current|
 +        current['whatsNew']['value'] = changelog if changelog
 +        current['description']['value'] = description if description
 +        current['pageLanguageValue'] = current['language'] # There is no valid reason why we need this, only iTC being iTC
 +      end
 +      build_info['significantChange'] ||= {}
 +      build_info['significantChange']['value'] = false
 +
 +      build_info['exportComplianceTO'] ||= {}
 +      build_info['exportComplianceTO']['encryptionUpdated'] ||= {}
 +      build_info['exportComplianceTO']['encryptionUpdated']['value'] = false
 +      # build_info['encryptionUpdated']['value'] = false
 +      # build_info[['usesEncryption'] ||= {}
 +      # build_info['usesEncryption']['value'] = false
 +      # build_info['isExempt'] ||= {}
 +      # build_info['isExempt']['value'] = false
 +      # build_info['containsProprietaryCryptography'] ||= {}
 +      # build_info['containsProprietaryCryptography']['value'] = false
 +      # build_info['containsThirdPartyCryptography'] ||= {}
 +      # build_info['containsThirdPartyCryptography']['value'] = false
 +
 +      r = build.client.send(:request, :post) do |req| # same URL, but a POST request
 +        app_id = build.build_train.application.apple_id
 +        platform = 'ios'
 +        train = build.build_train.version_string
 +        build_number = build.build_version
 +
 +        req.url "ra/apps/#{app_id}/platforms/#{platform}/trains/#{train}/builds/#{build_number}/review/submit"
 +
 +        req.body = build_info.to_json
 +        req.headers['Content-Type'] = 'application/json'
 +      end
```

This doesn't have the right values for cryptography/significant change setup for everyone.  Basically I worked backwards from what the website submitted on a successful build.

**Comment by tmm1** [comment]
I managed to get it working for my app based on @tildedave's work in https://github.com/fastlane/fastlane/pull/5407. Would appreciate others confirming that works for them.

**Comment by mfurtak** [comment]
[`spaceship` 0.29.0](https://github.com/fastlane/fastlane/releases/tag/spaceship%2F0.29.0) has been released. :rocket: `pilot` release coming soon!

**Comment by asfalcone** [comment]
[pilot 1.10.0](https://github.com/fastlane/fastlane/releases/tag/pilot/1.10.0) has been released. Please let us know if you have any further issues 👍

**Comment by kikolobo** [comment]
Thanks.. Updating now!
