### ISSUE TITLE
Snapshot problem with the new Xcode Beta

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#5316]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am in the process of updating the tutorial but I have come across a very strange behaviour with snapshot. I was using https://blog.twitter.com/2016/spotlight-on-fastlane-snapshot as a basis for testing snapshot. Now if I use only a single language it works as it is supposed to. However if I add another language in my case French the first simulator screenshot works but when it switches to french it just hangs. I have attached my console output. Do you have any ideas?

I found the reason why this is happening. I had both Xcode and Xcode-Beta. Once I un-installed the Xcode Beta it worked fine. Just and FYI

---

I had both the current Xcode and the new Beta Installed on my machine. If I added multiple languages then on the second screenshot (second language) of the same device the simulator would just show a black screen and hang.

Once I deleted the beta Xcode everything worked as expected.

Submitted via https://twitter.com/sbambra

**Comment by ohwutup** [comment]
Notes:
- I am unable to reproduce this on my machine with both Xcode's installed on my machine with a second language, French or others.
- I'm curious to know the version of Xcode selected in `xcode-select`
