### ISSUE TITLE
fastlane pilot has other team_id's

### ISSUE THREAD

**Issue by avalanched** [fastlane/fastlane#5317]
### New Issue Checklist

- [✓] Updated fastlane to the latest version
- [✓] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

when using `cert` i get the following teams:
```
1) ARRSWVJT62 "Company 1" (Company/Organization)
2) B939LU9623 "Company 2" (Company/Organization)
3) CWLA9Q8XY4 "Company 3" (Company/Organization)
```
but i get different id's for `pilot`
```
1) "Company 1" (117900111)
2) "Company 2" (117715988)
3) "Company 3" (95578877)
```
how can I define those team id's respectively for cert (and I think everything else) & pilot.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  lane :beta_sales do
    slack(
      message: "Start deploying."
    )
    cert
    sigh(force: true)
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "spotshop") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
```

### Environment

fastlane version (run `fastlane -v`):
`fastlane 1.97.2`
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by avalanched** [comment]
it works providing the team_id cert provides
but when its pilot's time you have to select it manual.. it would be handy if its automatic.

I don't think its a code signing issue, at least not a problem that is discussed in the troubleshooting guide

**Comment by bencollier** [comment]
The first set are developer team IDs, the second set are iTunes Connect Team IDs.

Apple likes to keep it easy :)

**Comment by TKBurner** [comment]
Hi @avalanched You can set them in pilot using ENV with the following names:

    -q, --team_id [VALUE] The ID of your team if you're in multiple teams (PILOT_TEAM_ID)
    -r, --team_name STRING The name of your team if you're in multiple teams (PILOT_TEAM_NAME)

Thanks!
