### ISSUE TITLE
Run snapshot with prebuild app

### ISSUE THREAD

**Issue by hffmnn** [fastlane/fastlane#5320]
Hi,

Not an issue more of a question:
Is it somehow possible to skip the rather time consuming build step of `snapshot` and give it e.g. a path to a pre-build debuggable `.app`?

Regards,
Christian

**Comment by vpolouchkine** [comment]
Unfortunately, this is not currently possible.

**Comment by Lutzifer** [comment]
I am also very interested in this feature
