### ISSUE TITLE
Help with setting up Fastlane with Circle-CI

### ISSUE THREAD

**Issue by shams-ahmed** [fastlane/fastlane#533]
am having a issues with fastlane not outputting console logs while using it with a CI platform like Circle-CI... is there any parameter i could use to force output to console or debug this issue?

<img width="893" alt="screen shot 2015-08-24 at 11 18 38 am" src="https://cloud.githubusercontent.com/assets/2887472/9441347/7602ddec-4a6d-11e5-82f9-1b419ae841d5.png">

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.18.0"

default_platform :ios


platform :ios do

  before_all do
    increment_build_number

    gym(
        workspace: "Fuse.xcworkspace",
        configuration: "Release",
        scheme: "Fuse",
        provisioning_profile_path: "./scripts/357edb88-c6d4-491a-9079-08456a97733a.mobileprovision",
        clean: true
    )

  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    sigh
    deliver(beta: true)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    sigh
    deliver(skip_deploy: false, force: true)

    clean_build_artifacts
    commit_version_bump message: "Deploying new version to iTunes"
    add_git_tag
    push_to_git_remote
  end


  after_all do |lane|
  
  end

  error do |lane, exception|
  
  end
end

```

**Comment by KrauseFx** [comment]
I'd have to take a closer look at this, but maybe setting `STDOUT.sync = true` on the top of your `Fastfile` helps?

**Comment by shams-ahmed** [comment]
@KrauseFx still no output

**Comment by KrauseFx** [comment]
Is there a way to increase the timeout time on CircleCI? You may want to ask support why it doesn't fetch the latest terminal output.

**Comment by shams-ahmed** [comment]
i increased the timeout for "fastlane beta" to 1.5 hours, no output at all... project not too big on my personal workspace it takes under 10 minutes to complete

```
[16:48:39]: -----------------
[16:48:39]: --- Step: gym ---
[16:48:39]: -----------------
[16:48:39]: Installing provisioning profile...
[16:48:39]: xcrun xcodebuild -list -workspace 'Fuse.xcworkspace'
[16:48:40]: xcrun xcodebuild -showBuildSettings -workspace 'Fuse.xcworkspace' -scheme 'Fuse'

+---------------+-------------------------------+
|            Building Application 🚀             |
+---------------+-------------------------------+
| Workspace     | Fuse.xcworkspace              |
| Scheme        | Fuse                          |
| Configuration | Release                       |
| Platform      | iOS                           |
| Xcode Path    | /Applications/Xcode-6.3.1.app |
+---------------+-------------------------------+

[16:48:42]: set -o pipefail && xcodebuild -workspace 'Fuse.xcworkspace' -scheme 'Fuse' -configuration 'Release' -destination 'generic/platform=iOS' -archivePath '/Users/distiller/Library/Developer/Xcode/Archives/2015-08-24/Fuse 2015-08-24 16.48.42.xcarchive' clean archive | xcpretty

-----

command fastlane beta took more than 120 minutes to run
```

**Comment by xfreebird** [comment]
@shams-ahmed  I think it is looking for keychain access, and the keychain is locked. I think sigh manages only the provisioning profiles, but you might also need to provide the signing certificate in a keychain.

**Comment by shams-ahmed** [comment]
@xfreebird am using the following script to unlock the keychain.

```
# Make any command erroring fail the whole script
set -e -x

# Get the absolute keychain path - `security` requires absolute paths
pushd $(dirname $0)
TOOLS_PATH=$(pwd)
popd

pwd
KEYCHAIN_NAME="$TOOLS_PATH/circle-ci.keychain"
echo $KEYCHAIN_NAME

# Set our keychain as the search path. Don't run this locally.
security list-keychains -s "$KEYCHAIN_NAME"

# Unlock it using the environmental variable.
security unlock-keychain -p "$IOS_CI_KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"

# Make sure we have a long timeout window.
security set-keychain-settings -t 3600 -u "$KEYCHAIN_NAME"

function cleanup {
  # Clean up on any kind of exit, just in case something bad happens.
  echo "Cleaning up keychain due to exit"
  security lock-keychain -a
}

trap cleanup EXIT

PROVISIONING_SYSTEM="$HOME/Library/MobileDevice/Provisioning Profiles/"
PROVISIONING_LOCAL="$TOOLS_PATH/provisioning-profiles/"

# mkdir -p "$PROVISIONING_SYSTEM"
# find "$PROVISIONING_LOCAL" -type f -exec cp '{}' "$PROVISIONING_SYSTEM" \;
```

am finding it difficult to debug the issue as i cant see any logs

**Comment by worldpay-cse-mobile-support** [comment]
I think I see the problem, but not 100% sure. 
First it would be sufficient to run:

```
security unlock-keychain -p "$IOS_CI_KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
security set-keychain-settings "$KEYCHAIN_NAME"
open "$KEYCHAIN_NAME"
```
This will add the keychain to the search list.

No need for 
```
security list-keychains -s "$KEYCHAIN_NAME"
```

Secondly, make sure you don't have bash special chars in $IOS_CI_KEYCHAIN_PASSWORD, like "$`"

If these didn't help, you also might want to to use the xcodebuild action to see the exact error. It seems gym with xcpretty is hiding the real error.

By the way, now fastlane has a new action unlock_keychain, which you might find it useful.

Hope this will help.

**Comment by xfreebird** [comment]
I think I see the problem, but not 100% sure. 
First it would be sufficient to run:

security unlock-keychain -p "$IOS_CI_KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
security set-keychain-settings "$KEYCHAIN_NAME"
open "$KEYCHAIN_NAME"
This will add the keychain to the search list.

No need for

security list-keychains -s "$KEYCHAIN_NAME"
Secondly, make sure you don't have bash special chars in $IOS_CI_KEYCHAIN_PASSWORD, like "$`"

If these didn't help, you also might want to to use the xcodebuild action to see the exact error. It seems gym with xcpretty is hiding the real error.

By the way, now fastlane has a new action unlock_keychain, which you might find it useful.

Hope this will help.

**Comment by JaviSoto** [comment]
Hi!
I'm going through some old issues to see if I can help out. Since this one has been inactive for a while, I'm going to go ahead and close it. Let me know if you're still running into any issues :) Thanks!
