### ISSUE TITLE
Frameit enforces relative font locations, ignores explicit path

### ISSUE THREAD

**Issue by dombarnes** [fastlane/fastlane#5333]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Specifying an explicit path to font files fails as Frameit assumes they are relative to current folder
i.e in Framefile.json
````
     "font": "/Users/username/Fonts/fontfile.otf"},
````

##### Complete output when running fastlane, including the stack trace and command used

```
Could not find font at path '/Users/username/projects/projectname/fastlane/screenshots/Users/username/Fonts/fontfile.otf'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
{
  "default": {
    "keyword": { 
       "font": "/Users/username/Fonts/fontfile.otf"},
    "title": {
      "color": "#49aea3"
      },
    "background": "./background.jpg",
    "padding": 50
  },

  "data": [
    {
      "filter": "Settings",
      "keyword": {
        "color": "#d21559"
      }
    },
    {
      "filter": "Category",
      "keyword": {
        "color": "#feb909"
      }
    },
    {
      "filter": "Playlist",
      "keyword": {
        "color": "#aa4dbc"
      }
    },
    {
      "filter": "Home",
      "keyword": {
        "color": "#31bb48"
      }
    }
  ]
}

```

### Environment

fastlane version (run `fastlane -v`): Frameit 2.7.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by vpolouchkine** [comment]
Thanks for the report! 👍
