### ISSUE TITLE
Custom project path with agvtool & increment_build_number.

### ISSUE THREAD

**Issue by cartfisk** [fastlane/fastlane#5341]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Attempting to use fastlane with an Ionic framework Cordova project. I have my fastlane config directory at `../..` relative to my Xcode project located in `platforms/ios` however agvtool is not recognizing this and is looking for the project in the working directory rather than the path I gave fastlane during init (`platforms/ios`).

##### Complete output when running fastlane, including the stack trace and command used

```
mobile-build-server git:81e7e33 ❯ fastlane dev                                                                                                                        ⏎ ✹ ✭
[10:51:09]: -------------------------------------------------
[10:51:09]: --- Step: Verifying required fastlane version ---
[10:51:09]: -------------------------------------------------
[10:51:09]: fastlane version valid
[10:51:09]: ------------------------------
[10:51:09]: --- Step: default_platform ---
[10:51:09]: ------------------------------
[10:51:09]: Driving the lane 'ios dev' 🚀
[10:51:09]: --------------------------------------------
[10:51:09]: --- Step: latest_testflight_build_number ---
[10:51:09]: --------------------------------------------
[10:51:14]: Fetching the latest build number for version 0.0.1
[10:51:15]: Latest upload is build number: 5
[10:51:15]: ------------------------------------
[10:51:15]: --- Step: increment_build_number ---
[10:51:15]: ------------------------------------
[10:51:15]: $ cd /Users/build/Jenkins/workspace/mobile-build-server && agvtool new-version -all 6 && cd -
[10:51:15]: ▸ There are no Xcode project files in this directory.  agvtool needs a project to operate.
[10:51:15]: Make sure to follow the steps to setup your Xcode project: https://developer.apple.com/library/ios/qa/qa1827/_index.html
[10:51:15]: Variable Dump:
[10:51:15]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios dev", :LATEST_TESTFLIGHT_BUILD_NUMBER=>5}
[10:51:15]: Exit status of command 'cd /Users/build/Jenkins/workspace/mobile-build-server && agvtool new-version -all 6 && cd -' was 3 instead of 0.
There are no Xcode project files in this directory.  agvtool needs a project to operate.


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | latest_testflight_build_number      | 5           |
| 4    | increment_build_number              | 0           |
+------+-------------------------------------+-------------+

[10:51:15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new

[!] Exit status of command 'cd /Users/build/Jenkins/workspace/mobile-build-server && agvtool new-version -all 6 && cd -' was 3 instead of 0.
There are no Xcode project files in this directory.  agvtool needs a project to operate.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/xxxxxxxxxxx"
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :dev do
    increment_build_number({
      build_number: latest_testflight_build_number(
        app_identifier: "com.xxxxx.xxxxx"
      ) + 1
    })

    gym(
      scheme: "Mobile"
    )
    # Upload to Testflight
    pilot(
      app_identifier: "com.xxxxx.xxxxx",
      skip_waiting_for_build_processing: true
    )

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```

### Environment
OS X 10.11.5

fastlane version (run `fastlane -v`): 1.97.2

- [ ] Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
- [x] Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? – `rbenv`

**Comment by vpolouchkine** [comment]
Does this work locally?

**Comment by fotiDim** [comment]
I have the same issue. My `fastlane` folder is on the same level as my `.xcworkspace`. Didn't try locally...

**Comment by TKBurner** [comment]
@fotiDim Which folder are you running from. The project folder or the fastlane foler. Thanks!

**Comment by fotiDim** [comment]
@TKBurner from project folder. Moving workspace to the same level as the project file did the trick but it would be nice not to have that restriction.

**Comment by TKBurner** [comment]
Thanks @fotiDim, Glad to hear you got up and running. Can you explain your use case of having these files at different directory levels? I'm going to mark this as a feature request 👍

**Comment by fotiDim** [comment]
It's mostly to avoid clutter and confusion. Every developer in our project is supposed to only use the workspace file so having that file at the root of our project and hiding the project file away helps makes sure that nobody will be confused.

**Comment by cartfisk** [comment]
@TKBurner when using Fastlane with Ionic projects, the .xcodeproj is generated by Cordova in platforms/ios/build instead of the project root. It's nice to keep fastlane files in the root when hosting on git repos. Right now I have Jenkins triggering builds and I have to make it copy the config to that folder and run fastlane from there. Not a huge deal but I would have assumed it would work if fastlane's setup asks for the .xcodeproj location.

**Comment by fotiDim** [comment]
Just a note, the workspace file has the info of the xcproj file inside. So
ideally if you execute fastlane one the workspace level you won't need to
specify xcproj location

**Comment by TKBurner** [comment]
@fotiDim @cartfisk Thanks for sharing those use cases. I think this is viable for a community PR. I've marked it to get attention, but I was wondering if you could let me know if you are interested?

Thanks!

**Comment by fotiDim** [comment]
@TKBurner I am not a ruby guy but I would love to contribute. Let me see what I can do.

**Comment by tdorsey** [comment]
@fotiDim Similar issues here related to cordova, similar lack of ruby experience. Would be willing to pitch in if you need hands.

**Comment by bguidolim** [comment]
It's already done, please run `fastlane action increment_build_number`, you will see all parameters supported, one of them is `xcodeproj`. So, on your lane `dev`, you can do this:

```
    increment_build_number({
      xcodeproj: 'project_path',
      build_number: latest_testflight_build_number(
        app_identifier: "com.xxxxx.xxxxx"
      ) + 1
    })
```

**Comment by TKBurner** [comment]
@bguidolim Thanks for pointing this out!

**Comment by GabLeRoux** [comment]
I was looking for this too. I use fastlane to automatically sign and send an ios project generated by Unity3D. I was able to use it like this:

```
  
  lane :increment do
    increment_build_number({
      xcodeproj: 'build/ios/Unity-iPhone.xcodeproj',
      build_number: latest_testflight_build_number(
        app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
      ) + 1
    })
  end
```
```
fastlane ios increment
```
Worked 🎉 

Thanks to bguidolim answer, I also looked at other commands. I found that `gym` uses the parameter `project`.

```
  lane :beta do
    cert
    sigh(force: true)
    gym(project: "build/ios/Unity-iPhone.xcodeproj") # Build your app - more options available
    pilot
  end
```

But looks like the linker fails for me with this custom `parameter` as described here:
https://github.com/fastlane/fastlane/issues/4208#issuecomment-257209655
