### ISSUE TITLE
iTC Reporting API using Spaceship

### ISSUE THREAD

**Issue by marbetschar** [fastlane/fastlane#5343]
Will it be possible in the near future to access the iTunes Connect reporting API through spaceship?

In my opinion the API of spaceship looks very promising and easy to use, therefore an additional fastlane tool for retrieving app reports which then can be integrated in some sort of custom monitoring tool together with other app relevant key metrics (like website visitors etc.) would be awesome!!

**Comment by KrauseFx** [comment]
Sorry, this is currently not planned

**Comment by marbetschar** [comment]
Sad to here that :( Any chances this may get revisited?
If not, are you aware of another already existing project of getting the report values out of iTC ?

Unfortunately I can't find one which looks stable/promising apart from spaceship.

**Comment by diaojunxian** [comment]
@marbetschar HI,I also would like to get our app report from itcunes connect with the help spaceship,and I  don't know how to achive ,and you can see my StackOverflow post `http://stackoverflow.com/questions/40060147/how-to-login-to-itunes-and-use-requests-to-download-our-apps-unofficial-documen`, 
Do you have achive it?Can you help me?Thanks a lot.

**Comment by marbetschar** [comment]
@diaojunxian we ditched the reporting feature for iTunes Connect for the moment. But you may want to give the Apple Reporter Tool a try:

http://help.apple.com/itc/appsreporterguide/#/itcbe21ac7db

**Comment by diaojunxian** [comment]
@marbetschar I konw the reporter.jar but I still can not get the scores and user evaluation
from itc,how can I solve it

**Comment by marbetschar** [comment]
@diaojunxian unfortunately I can't help you out here. To provide more insights I have to digg into the topic too - and as I'm short of time that's currently only possible, if you are interested in some sort of payed support. Sorry for not having better news for you.

**Comment by diaojunxian** [comment]
ok,I don't have any ideas now
