### ISSUE TITLE
Use launch arguments in XCTestCase directly

### ISSUE THREAD

**Issue by bkrijgsman** [fastlane/fastlane#5344]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi, i'm trying to pass the launch arguments of snapshot directly to the XCTestCase, to perform different tests based on the configuration. My snapfile contains the following arguments

```
launch_arguments([
  "-hide_login false -login_type "
])
```

In the XCTestCase is use the following code to retrieve the variables:

`

        let hideLogin = NSUserDefaults.standardUserDefaults().stringForKey("hide_login") ?? "not_found_hide_login"
         snapshot(hideLogin)
        let loginType = NSUserDefaults.standardUserDefaults().stringForKey("login_type") ?? "not_found_login_type"
        
        snapshot(loginType)`

When i run snapshot, the program can't find the variables. What am i missing? :)

**Comment by vpolouchkine** [comment]
Does this help? https://github.com/fastlane/fastlane/issues/3745#issuecomment-196561294

**Comment by bkrijgsman** [comment]
I already saw that ticket. I used the following method:

```
func argValueForKey(key:String, app:XCUIApplication) -> String? {
        if let index = app.launchArguments.indexOf(key) {
            return app.launchArguments[index+1]
        } else {
            return nil
        }
    }

//Fetch launch argument
let app = XCUIApplication()
setupSnapshot(app)

let testcase = argValueForKey("-testcase", app:app) ?? "0"
```

And that worked :)
