### ISSUE TITLE
Got developerDdaNotAccepted error but I see nothing to accept in account

### ISSUE THREAD

**Issue by jkammerer** [fastlane/fastlane#5347]
using supply 0.7.0 I receive this error with init:
_/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:202:in `check_status': [!] developerDdaNotAccepted: This developer accounts owner has not accepted the latest Developer Distribution Agreement. (Google::Apis::ClientError)_
But when I login to the account as admin there is no agreement.

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!

**Comment by jkammerer** [comment]
**New Issue Checklist**
Done

**Complete output when running fastlane, including the stack trace and command used**
==> supply --json_key x.json --package_name com.x

+-------------------------+-------------------------+
|             Summary for supply 0.7.0              |
+-------------------------+-------------------------+
| json_key                | x.json |
| package_name            | com.x                |
| track                   | production              |
| rollout                 | 1.0                     |
| metadata_path           | ./metadata              |
| skip_upload_apk         | false                   |
| skip_upload_metadata    | false                   |
| skip_upload_images      | false                   |
| skip_upload_screenshots | false                   |
+-------------------------+-------------------------+
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:202:in `check_status': [!] developerDdaNotAccepted: This developer accounts owner has not accepted the latest Developer Distribution Agreement. (Google::Apis::ClientError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/api_command.rb:103:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:170:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:275:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/lib/google/apis/core/base_service.rb:267:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.2/generated/google/apis/androidpublisher_v2/service.rb:209:in `insert_edit'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/client.rb:81:in `begin_edit'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/uploader.rb:6:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/supply-0.7.0/bin/supply:6:in `<top (required)>'
	from /usr/local/bin/supply:23:in `load'
	from /usr/local/bin/supply:23:in `<main>'

**Configuration Files**
Please copy the complete content of your Fastfile and any other configuration files you use below:

Fastfile:
u

**Environment**

fastlane version (run fastlane -v):
fastlane 1.97.2
Do you use bundler to execute fastlane (i.e. bundle exec fastlane)?
no
Do you use a Ruby environment manager (e.g. chruby, rbenv, rvm)?
no
