### ISSUE TITLE
Inconsistency in way we create new action and plugin

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#5361]
Currently there is a inconsistency in way we make new action and plugin:

According to this document.
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md

- `fastlane new_action name` won't pick `name` as the action's name
- `fastlane new_action --name name` will pick `name` as the action's name

However:
- `fastlane new_plugin name`will pick `name` as the plugin's name
- `fastlane new_plugin --name name` won't pick `name` as the plugin's name

**Comment by KrauseFx** [comment]
Valid point @jcampbell05, feel free to submit a PR fixing this, just make sure it's backwards compatible 👍
