### ISSUE TITLE
Logging & Screenshot at/of failure

### ISSUE THREAD

**Issue by logicry** [fastlane/fastlane#5364]
### Screenshots

I would like to ask whether it's possible to capture screenshot when it comes to some failure. Consider the following code:

```
waitForExpectationsWithTimeout(timeout, handler: { error in
            if let e = error {
                let message = "Element \(element.label) was not available after \(timeout) seconds, error: \(error?.localizedDescription)";
                NSLog(message)
                snapshot("failure")
            }
        })
```

I have the feeling screenshots are just being marked and made in the end, as I've never seen screenshots in case of failure.
### Logging

I would like the snapshot's output to also include NSLog / Print logging, is there a way to realize that? I'm currently just exporting device logs from ~/Library/CoreSimulator/... but this would be very nice.

**Comment by vpolouchkine** [comment]
I don't believe this is currently possible.

**Comment by revolter** [comment]
There is no `~/Library/CoreSimulator` folder on my machine. Did you create that manually?
