### ISSUE TITLE
Error packaging up the application when building framework with gym

### ISSUE THREAD

**Issue by demetrisch** [fastlane/fastlane#5367]
I am using gym to build & package a framework (Cocoa Touch Framework) but the build fails at the end.  The command I use is the following:

gym --workspace LiveSafe.xcworkspace --scheme LiveSafeDistribution --use_legacy_build_api true --clean

Does gym support building a framework or only IPA files?

The log output at the end of this command is the following:

[14:32:09]: ▸ Touching LiveSafe.framework
[14:32:09]: ▸ Signing /Users/demetris/Library/Developer/Xcode/DerivedData/LiveSafe-fpryfxrvkwrrcmgrbypoqipdjpok/Build/Intermediates/ArchiveIntermediates/LiveSafeDistribution/InstallationBuildProductsLocation/Library/Frameworks/LiveSafe.framework
[14:32:11]: ▸ Touching LiveSafe.framework.dSYM
[14:32:13]: ▸ Archive Succeeded
[14:32:13]: $ /usr/bin/xcrun /tmp/PackageApplication4Gym -v '' -o '/var/folders/rs/b1tjcf0918sfvzcs5xhss9xc0000gn/T/gym_output20160711-16968-20lkvb/LiveSafe.ipa' exportFormat ipa 
error: An application was not specified.
[14:32:13]: Exit status: 1

Looking for related GitHub issues on fastlane/fastlane...

➡️   Export Failed - Error Packaging up the application, Rsync failed issues
   https://github.com/fastlane/fastlane/issues/4150 [open] 32 💬
   a week ago

➡️  Error packaging up the application
   https://github.com/fastlane/fastlane/issues/1145 [closed] 8 💬
   5 weeks ago

➡️  Gym errors: error 14 and exit status 70.
   https://github.com/fastlane/fastlane/issues/5358 [open] 1 💬
   13 hours ago

and 25 more at: https://github.com/fastlane/fastlane/search?q=Error%20packaging%20up%20the%20application&type=Issues&utf8=✓

[!] Error packaging up the application

**Comment by maxdisney** [comment]
Yeah seeing this here too (with Xcode 8 beta 2). Doesn't look like the legacy build API works either... :/

**Comment by izqui** [comment]
Issue is still present in beta 3.

**Comment by TKBurner** [comment]
Hi @izqui @maxdisney! Thanks for following up on this. We aren't going to dedicate internal resources to Xcode 8 until it's close to the general release. However, we'd love to see PRs starting now. I'm marking this as help wanted in case anyone from the community wants to work on a PR for Xcode 8 support. Thanks!
