### ISSUE TITLE
snapshot: The sandbox is not in sync with the Podfile.lock

### ISSUE THREAD

**Issue by rodrigoreis22** [fastlane/fastlane#5368]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to run snapshot and I'm receiving the error below (complete output attached).
I've tried:
- run pod install again (of course)
- cleaning and building again
- remove /Pods and Podfile.lock

##### Complete output when running fastlane, including the stack trace and command used

```
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'

❌  error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.


▸ Building Arena/ARNUITests [Debug]
▸ Check Dependencies
2016-07-11 15:04:05.915 xcodebuild[19455:12621071] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7ff1df6c37f0>
2016-07-11 15:04:05.918 xcodebuild[19455:12621074] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7ff1de269ff0>

Testing failed:
Diff: /../Podfile.lock: No such file or directory
Diff: /Manifest.lock: No such file or directory
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:
```
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
   "iPhone 6",
   "iPhone 6 Plus",
   "iPhone 5",
   "iPhone 4s",
   "iPad Retina",
   "iPad Pro"
])

languages([
  "en-US",
  ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
scheme "Arena"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "./Arena.xcworkspace"

# For more information about all available options run
# snapshot --help
```

### Environment

Rodrigos-MacBook-Pro:Arena rodrigoreis$ snapshot -v
snapshot 1.12.3

Rodrigos-MacBook-Pro:Arena rodrigoreis$ pod --version
0.39.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

[snapshot_out.txt](https://github.com/fastlane/fastlane/files/357988/snapshot_out.txt)

**Comment by ohwutup** [comment]
Hey @rodrigoreis22, it looks like maybe snapshot is not detecting your workspace perhaps. Could you share with us your fastfile (and Appfile if you have one)?

**Comment by rodrigoreis22** [comment]
Hi @ohwutup , I got it to work, one of my other targets had a problem. We can close this issue.

**Comment by ohwutup** [comment]
👍 🚀 !

**Comment by rodrigoreis22** [comment]
@mikepsinn sorry, i don't really recall.. but I think my test target had some basic configuration problem.

**Comment by mikepsinn** [comment]
@rodrigoreis22 Got it. Thanks, anyway!
