### ISSUE TITLE
Pass variables to export_options

### ISSUE THREAD

**Issue by pscadiz** [fastlane/fastlane#5371]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
<dict>
	<key>kind</key>
	<string>software-package</string>
	<key>url</key>
	<string>http://testserver.domain/${PLAN_KEY}-${BUILD_NUMBER}/${APP_NAME}.ipa</string>
</dict>
```
Is it possible to create the manifest.plist using user defined variables? So far I can't get the build to pass a variable to the manifest on build, already tried environment variables and adding build settings.

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
      export_options: {
        manifest: {
          appURL: "http://testserver.domain/${PLAN_KEY}-${BUILD_NUMBER}/${APP_NAME}.ipa",
          displayImageURL: "http://testserver.domain/${PLAN_KEY}-${BUILD_NUMBER}/app_icon.png",
          fullSizeImageURL: "http://testserver.domain/${PLAN_KEY}-${BUILD_NUMBER}/app_icon_full.png"
        }
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? nope

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? nope

**Comment by vpolouchkine** [comment]
Maybe this can help: http://stackoverflow.com/questions/38328837/change-user-defined-variable-from-fastlane

**Comment by KrauseFx** [comment]
If you're talking about the `plist` file, why do you generate it using `gym`, and not at a later point, by using the `s3` action for example?

**Comment by pscadiz** [comment]
I am generating the plist file using gym, here's the full gym step:

```
gym(
  scheme: "Test Application",
  codesigning_identity: "iPhone Distribution",
  clean: true,
  output_directory: "build",
  export_options: {
    manifest: {
      appURL: "http://testserver.domain/${PLAN_KEY}-${BUILD_NUMBER}/${APP_NAME}.ipa",
      displayImageURL: "http://testserver.domain/${PLAN_KEY}-${BUILD_NUMBER}/app_icon.png",
      fullSizeImageURL: "http://testserver.domain/${PLAN_KEY}-${BUILD_NUMBER}/app_icon_full.png"
    }
  }
)
```

The issue is that the generated plist file still has the variable names instead of being interpolated with the values provided either in an environment variable, a user-defined value or a key in the info plist

**Comment by pscadiz** [comment]
This ticket can be closed for now. Cannot test this since I have changed my method. Thank you

**Comment by TKBurner** [comment]
@pscadiz Thanks for updating. Hope you have a great week!
