### ISSUE TITLE
Unable to you JIRA Action

### ISSUE THREAD

**Issue by eikebartels** [fastlane/fastlane#5373]
### Issue Description

```
 jira(
        url: "https://urlJira.net",
        username: "username",
        password: "pwd",
        ticket_id: options[:ticket],
        comment_text: "Comment generated by fastlane"
      )
```

##### Complete output when running fastlane, including the stack trace and command used

```
.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- jira (LoadError)
```

**Comment by ohwutup** [comment]
Could you try running `gem install jira` to see if that kicks it into gear?

**Comment by eikebartels** [comment]
I tried `jira` and `ruby-jira` for both didn't work

**Comment by ohwutup** [comment]
Did you install fastlane via the Fabric Mac app?

**Comment by eikebartels** [comment]
No I didn't

**Comment by ohwutup** [comment]
could you show me what happens when you do `gem list jira`

**Comment by ohwutup** [comment]
and `gem which jira`

**Comment by eikebartels** [comment]
`gem list jira`

```
*** LOCAL GEMS ***
 
jira (0.1.0)
jira-ruby (1.0.0)
```
`gem which lira`

`/Users/eikebartels/.rvm/gems/ruby-2.3.0/gems/jira-0.1.0/lib/jira.rb`

**Comment by KrauseFx** [comment]
You didn't follow the issue template, so we don't know how you actually called `fastlane`. Did you use `bundle exec`? Do you have a `Gemfile`? If so, please add `jira` to your `Gemfile`
