### ISSUE TITLE
Scan with FASTLANE_EXPLICIT_OPEN_SIMULATORS produces errors

### ISSUE THREAD

**Issue by ffittschen** [fastlane/fastlane#5375]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hi,
I'm running into the issue where running scan on the CI machine (Jenkins) produces following error: 
```
** TEST FAILED **
Exit status: 65
```

I read these two issues (https://github.com/fastlane/fastlane/issues/3368 and https://github.com/fastlane/fastlane/issues/3886) and tried the approach described by @mfurtak in https://github.com/fastlane/fastlane/issues/3886#issuecomment-218165178. However, this produces error windows.
#### Case 1 (no open simulator when scan gets executed)
Produces: `Error returned in reply: Connection invalid`
But it still runs the tests successfully in a second simulator window that gets opened a few seconds later.
<img width="843" alt="screen shot 2016-07-12 at 16 49 45" src="https://cloud.githubusercontent.com/assets/7734806/16771980/aecda326-4852-11e6-837c-eb433d582b11.png">

##### Possible solution
I observed that `open -a Simulator --args -CurrentDeviceUDID #{device.udid}` will open the Xcode 8 beta Simulator which does not exist with the given UDID.

To avoid this issue, I'd suggest to use `xcrun instruments -t 'Blank' -l 1 -w "#{device.udid}"` instead [this](https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/runner.rb#L95), because this will use the Simulator.app of the in `xcode-select` currently specified Xcode.

#### Case 2 (simulator is already open)
Produces: `Simulator quit unexpectedly.`
The tests won't execute, because `scan` gets stuck at `▸ Check Dependencies`.
<img width="545" alt="screen shot 2016-07-12 at 17 14 48" src="https://cloud.githubusercontent.com/assets/7734806/16772378/54fa9276-4854-11e6-99c6-4b64fce03ea1.png">

##### Possible solution
same as in Case 1, because the report also states Xcode-beta:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The loaded com.apple.CoreSimulator.CoreSimulatorService job does not match our expectations: pathOfLoadedJob: /Applications/Xcode.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework/Versions/A/XPCServices/com.apple.CoreSimulator.CoreSimulatorService.xpc, our frameworkPath: /Applications/Xcode-beta.app/Contents/Developer/Library/PrivateFrameworks/CoreSimulator.framework'
```

##### Complete output when running fastlane, including the stack trace and command used

output is not relevant

### Configuration Files

Fastfile:
```ruby
default_platform :ios

platform :ios do
  lane :build do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "1"
    scan(
      project: Actions.lane_context[SharedValues::XCODEPROJECT_FILE]
    )

    sigh(
      provisioning_name: "#{Actions.lane_context[SharedValues::PROJECT_NAME]}_appstore"
    )

    # store the UDID of the provisioning profile in the ENV variables for Xcode
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    
    increment_build_number(
      xcodeproj: Actions.lane_context[SharedValues::XCODEPROJECT_FILE],
      build_number: ENV["BUILD_NUMBER"]
    )

    gym(
      project: Actions.lane_context[SharedValues::XCODEPROJECT_FILE],
      output_name: "#{Actions.lane_context[SharedValues::IPA_NAME]}",
      include_bitcode: true,
      use_legacy_build_api: true,
      clean: true
    )
  end
end
```

Scanfile:
```ruby
scheme "SchemeName"
devices ["iPhone 6", "iPhone 6s"]
skip_slack true
```

### Environment

fastlane version: 1.97.2
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **yes**
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **yes, rbenv**

**Comment by ffittschen** [comment]
I just realized that the proposed `xcrun instruments -t 'Blank' -l 1 -w "#{device.udid}"` will create a `.trace` file for each run... So either we additionally need to delete it, or we add an optional option to scan to specify which simulator to use (with the normal Xcode.app simulator as default)

**Comment by jcampbell05** [comment]
I may be getting a similar error to this in Travis CI - we also use explicit open simulators. I can't see what happening UI-wise though so can't see what is happening but the tests fail with an unexplained `Code: 65`

**Comment by mfurtak** [comment]
Hi folks, am I understanding correctly that this is failing because the Xcode 8 beta simulator is in the mix?

**Comment by ffittschen** [comment]
Yes, but I don't think this is limited to Xcode 8 beta. This will happen whenever there are multiple versions of Xcode (and therefore Simulator) are installed, because `scan` / `fastlane_core` uses `xcrun` to gather the available simulators and I assume the `xcrun` version is determined by the currently selected command line tools. I don't know how the `open -a` command decides which application it uses if there are multiple versions.

**Comment by TKBurner** [comment]
Hi @ffittschen Thanks for following up. Because this is an edge case (you will only have multiple version of Xcode in the case of a beta version existing) we need to mark this as a feature request. I'm also marking this help wanted because I'd love to see a community contribution.

Thanks!

**Comment by ffittschen** [comment]
@TKBurner I created a PR which should solve the issue: #5530 😉
@jcampbell05 You could try if my PR solves your issue on travis as well

**Comment by mfurtak** [comment]
I see that we wound up in the same place @ffittschen 👍  (#5529 & #5530) :smile:

I'll be getting some feedback on this approach from https://github.com/fastlane/fastlane/issues/5128 as well, and then I think we can get the fix in.

**Comment by ffittschen** [comment]
@mfurtak Yes, I just saw the reference popping up 😄

**Comment by ffittschen** [comment]
@mfurtak I just realized, that those are the "same" changes, but in different files. Your change is done for `snapshot` mine for `scan`.
I'll adopt my PR to use the `FastlaneCore::Helper` as well. Should I add the second level of feature switching too?

**Comment by mfurtak** [comment]
Ah, yes - that'd be great. Once we get some positive feedback on that change, we should be able to unroll at least one level of feature switching, and hopefully consolidate this functionality into a shared location. 👍

**Comment by mfurtak** [comment]
Hi folks - I've released [`scan` 0.10.0](https://github.com/fastlane/fastlane/releases/tag/scan/0.10.0) with @ffittschen's fix for this (#5530)

Please update to the latest with `gem update scan` then try running things with:

```
FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 scan
```

⚠️ Note that the environment variable value has changed to **2** where previously it was 1! ⚠️

If you're running things through fastlane, do:

```
FASTLANE_EXPLICIT_OPEN_SIMULATOR=2 fastlane test
```

... or whatever lane you need. 

This should allow `scan` to account for your current Xcode of choice (via `xcode-select`) when attempting to get the simulator ready.

You'll know you got it right if you see the "Explicitly opening simulator" output change to include a path, like:

```
Explicitly opening simulator at /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app for device: iPhone 4s
```

After that, please let me know if this gets things working again for you. If not, complete output is always helpful. Thanks! 🚀

**Comment by bfcrampton** [comment]
Cool! I was having the same issue, thanks for the fix @mfurtak and @ffittschen

**Comment by mfurtak** [comment]
@bfcrampton Does that mean that `FASTLANE_EXPLICIT_OPEN_SIMULATOR=2` gets things working for you?

**Comment by mfurtak** [comment]
Hi folks, [`scan` 0.10.1](https://github.com/fastlane/fastlane/releases/tag/scan/0.10.1) 🔍  has been released, which makes @ffittschen's fix the default behavior when using the `FASTLANE_EXPLICIT_OPEN_SIMULATOR` feature flag.

I'm going to close this issue for now, but please let me know how things look! 👍
