### ISSUE TITLE
number_of_commits issue when using branches

### ISSUE THREAD

**Issue by PitchLabsAsh** [fastlane/fastlane#5376]
Would number_of_commits be better using `git rev-list --all --count` rather than `git rev-list HEAD --count`?

I find the current version does not work so well when using branches.

**Comment by ohwutup** [comment]
Would love to get @onevcat's opinion as they are the author! 🚀

**Comment by onevcat** [comment]
The initial purpose of `number_of_commits` is supplying a identifier number to a certain branch (maybe the release branch), so I could use it as the build/release version number.

That's true two numbers from different branches might be the same under current implementation. However, if we use `git rev-list --all --count`, the final number will be unpredicted and cannot be used as an identifier. There is some use case for it, but I also want to keep the only `HEAD` or "current branch" version.

Maybe we could add an option for this action to calculate for all branches? So the users could choose in which way they want to use this action.

@PitchLabsAsh @ohwutup How do you think about it?

**Comment by ohwutup** [comment]
That seems like a good idea to me!

**Comment by onevcat** [comment]
Cool. But I am in my vacation. I will try to implement it some days later, if there is no one else does it.

**Comment by PitchLabsAsh** [comment]
My use case is the same in that I want to use this number as a build number in the app so I can display the number inside the app and identify exactly which commit it was built from.
I also tag git with a label based that includes this number.

I don’t like using other git labelling methods as they all result in a new commit rather than  just a tag, using the git number as a tag means I don’t create a new commit.

"However, if we use git rev-list --all --count, the final number will be unpredicted and cannot be used as an identifier.”

What exactly do you mean here? Why do you think —all can’t be used an an identifier?

**Comment by TKBurner** [comment]
@onevcat Are you still interested in submitting a PR? Thanks!
