### ISSUE TITLE
Match: one target, multiple bundle identifiers stored in .xcconfig

### ISSUE THREAD

**Issue by krodak** [fastlane/fastlane#5377]
Hi,
while enjoying your tool a lot since early beginning, I can't figure out how to use `match` tool in my use case and browsing through options and existing issues didn't help.

I have 1 XCode project with 1 Target, but multiple Configurations to generate multiple instances of applications which differs in branding and of course `Bundle Identifier`.

What would be the best setup to use `match` if I store `Bundle Identifier` in .xcconfig files, not different targets? I know I can specify .xcconfig for `gym`, but I don't see any similar option for `match`.
Thanks in advance!

**Comment by KrauseFx** [comment]
Sorry for not replying earlier to this, do you still have this problem?
