### ISSUE TITLE
Fastlane shows available lanes when passing parameter

### ISSUE THREAD

**Issue by kalvish21** [fastlane/fastlane#5383]
When I call a lane like so:

fastlane sign

Everything works fine. But when I call with an argument:

fastlane sign bundle_id:com.example

I get the following:

+--------+----------------------+----------------------------------------------------+
|                               Available lanes to run                               |
+--------+----------------------+----------------------------------------------------+
| Number | Lane Name            | Description                                        |
+--------+----------------------+----------------------------------------------------+
| 1      | ios beta             | Submit a new Beta Build to Apple TestFlight        |
|        |                      | This will also make sure the profile is up to date |
| 2      | ios set_project_info | Change Info Plist                                  |
| 3      | ios sign             | Get the provisioning profiles for the app          |
| 4      | ios screenshots      | Create screenshots                                 |
| 5      | ios build            | Build new app for appstore                         |
| 6      | ios deploy           | Deploy a new version to the App Store              |
| 0      | cancel               | No selection, exit fastlane!                       |
+--------+----------------------+----------------------------------------------------+

This is with the new version fastlane_version "1.97.2". Is this intentional?

**Comment by TKBurner** [comment]
Hi @kalvish21 Thanks for reaching out about this. Can you let me know what the old behavior you saw was? I'm pretty sure this never behaved the way you are expecting.

Thanks!

**Comment by KrauseFx** [comment]
Hey @kalvish21, could you also share your Fastfile please? 👍

**Comment by KrauseFx** [comment]
Was this resolved?

**Comment by kalvish21** [comment]
Yes. My AppFile had some invalid arguments that were creating the issue.

**Comment by TKBurner** [comment]
@kalvish21 Awesome! Really glad to hear you got up and running!
