### ISSUE TITLE
get_version_number does not search for target

### ISSUE THREAD

**Issue by Ro-M** [fastlane/fastlane#5388]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When we use `get_version_number(target: "YourTarget")`, it does not look for the specified target but tries to match the target string against the paths returned by agvtool. This is implicit because not every target has its own subdirectory named after it in the project folder.

For example, if we have a target FooTests that resides in a folder named "Tests" (instead of "FooTests") `get_version_number(target: "FooTests")` would return nothing (we would need to call `get_version_number(target: "Tests")` to get the version number of FooTests).

This behavior should be explained in the description of `get_version_number` (perhaps "folder" or something similar is a better name for the "target" parameter?)
It could also be possible to match the info.plist paths  that can be found in the `project.pbxproj` file against the paths returned by the agvtool
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by mortenholmgaard** [comment]
@KrauseFx please reopen this issue - and please fix it. I experience the exact same thing. I also have targets that does not have a specific folder to the target like this:

> [13:09:35]: --------------------------------
> [13:09:35]: --- Step: get_version_number ---
> [13:09:35]: --------------------------------
> [13:09:35]: $ cd /Users/mortenholmgaard/Code/MyEvent && agvtool what-marketing-version -terse
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/AaFestival-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/Demo-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/Development-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/Discipeltraef-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/Event-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/Hjallerup-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/Konnekt-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/MTC-Info.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/Paaskelejr.plist
> [13:09:35]: ▸ $(SRCROOT)/MyEvent/Supporting Files/SE-Info.plist
> [13:09:35]: ▸ "MyEvent.xcodeproj/../UI_TEST_AaFestival/Info.plist"=1.0
> [13:09:35]: ▸ "MyEvent.xcodeproj/../UI_TEST_Discipeltraef/Info.plist"=1.0
> [13:09:35]: ▸ "MyEvent.xcodeproj/../UI_TEST_Event/Info.plist"=1.0
> [13:09:35]: ▸ "MyEvent.xcodeproj/../UI_TEST_Hjallerup/Info.plist"=1.0
> [13:09:35]: ▸ "MyEvent.xcodeproj/../UI_TEST_Konnekt/Info.plist"=1.0
> [13:09:35]: ▸ "MyEvent.xcodeproj/../UI_TEST_MTC/Info.plist"=1.0
> [13:09:35]: ▸ "MyEvent.xcodeproj/../UI_TEST_Paaskelejr/Info.plist"=1.0

**Comment by TKBurner** [comment]
@mortenholmgaard Thanks for reaching out about this. Can you provide a sample project that is affected by this issue? If you can provide that and repro steps, I'd love to loop in the core team.

Thanks!
