### ISSUE TITLE
Fastlane / Supply on Travis

### ISSUE THREAD

**Issue by PatrickHeneise** [fastlane/fastlane#5390]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to get Supply running on Travis with a small Android app. There's barely any documentation on supply and nothing on running supply on Travis. Succeeded to get the build, but the upload fails:

/home/travis/.rvm/gems/ruby-2.3.1/gems/google-api-client-0.9.11/lib/google/apis/core/http_command.rb:211:in `check_status': [!] apkNotZipAligned: APK is not zip aligned. (Google::Apis::ClientError)

Anyone ever tried this setup?

**Comment by asfalcone** [comment]
Hey @PatrickHeneise are you using the latest Android Gradle plugin? 2.2.0-alpha3 had an issue where it was not zip aligning correctly, and produced this exact error. If you're using that version, try -alpha4 or -alpha2. 👍

**Comment by PatrickHeneise** [comment]
Thanks for the hint, I'll check. Is that something built into gradle or do I have to run an action before?

**Comment by asfalcone** [comment]
In your build.gradle, what's the version number after `classpath 'com.android.tools.build:gradle:` ?

**Comment by PatrickHeneise** [comment]
We're running 2.1.2. I personally haven't used gradle before and new to it, that's why I wasn't sure if the zip align is handled automatically.

**Comment by joemasilotti** [comment]
I'm running into the same issue with 2.1.2. Using 2.2.0-alpha4 does not help.

**Comment by asfalcone** [comment]
This is super weird! Can you try running `./gradlew assembleRelease` from your command line and uploading the apk manually to Google Play? I just want to make sure that this is something with fastlane and not your build/signing setup before we get too far.

If the apk uploads correctly to Google Play that way, then I'd be happy to help investigate. Please paste your fastfile if you have one, the exact command you're running, and complete output of running supply.

Thanks!

**Comment by joemasilotti** [comment]
:facepalm: (why isn't that an emoji?)

Turns out my Gradle build script wasn't running `zipalign` on the build, I was doing it manually. For some reason I assumed Fastlane would take care of that.

I was able to fix my particular issue by adding the `zipAlignEnabled true` line to Gradle.

```
android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.beermenus.beermenus"
        minSdkVersion 19
        targetSdkVersion 23
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            zipAlignEnabled true
        }
    }
}
```

**Comment by TKBurner** [comment]
@PatrickHeneise Can you let me know if you are still running into this issue? Thanks so much! 👍

**Comment by PatrickHeneise** [comment]
We have zipAlignEnabled in the config, but not sure about the signing configs. Where do I get the keystore from? I have the json downloaded as it is stated in the instructions

**Comment by asfalcone** [comment]
@PatrickHeneise Check out [this article](https://developer.android.com/studio/publish/app-signing.html#release-mode) on signing your APK. The json file that you downloaded is for authenticating with Google Play for uploads.

**Comment by PatrickHeneise** [comment]
Thanks, that helped! Last issue we have is:

`testingTrackApkInMultipleTracks: Testing-track (alpha/beta) APK with version code 3 appears in another track`

I'll try to summarise everything in the Supply readme.

**Comment by TKBurner** [comment]
@PatrickHeneise Thanks for following up. Can you share your full input and output? I want to take a look. Thanks!

**Comment by PatrickHeneise** [comment]
I think it's resolved by now. Will catch up with the team and then hopefully write everything down for a better readme

**Comment by TKBurner** [comment]
@PatrickHeneise Awesome! Thanks for working with us 👍

**Comment by zxfrank** [comment]
@PatrickHeneise how did you get rid of testingTrackApkInMultipleTracks ?

**Comment by TKBurner** [comment]
@zxfrank If you are running into an issue, please submit a new ticket. We'd love to help 👍
