### ISSUE TITLE
Unable to run fastlane - SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by biddster** [fastlane/fastlane#5396]
I'm using fast lane with rvm. I've been through the intertubes reading up on this and, historically, there appears to have been some issues.

I'm running El Cap OSX. I have brew installed.

Firstly, I started by following the docs with my rvm installed ruby 2.1.5:

```
$ brew update && brew upgrade openssl
$ rvm osx-ssl-certs update all
$ gem install fastlane
$ fastlane init
...
SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

I then followed this https://github.com/fastlane/fastlane/issues/745

```
gem uninstall fastlane
rvm reinstall ruby-2.1.5 --with-openssl-dir=/usr/local
$ gem install fastlane
$ fastlane init
...
SSL_connect returned=1 errno=0 state=error: certificate verify failed
```

I then tried manually downloading the curl certificate and exporting the certificate from here https://github.com/fastlane/fastlane/issues/258#issuecomment-99390505. Still the same ssl error.

I then did this https://github.com/fastlane/fastlane/issues/258#issuecomment-126286545 and used `rvm reinstall 2.1.5 --disable-binary`, followed by reinstalling the fastlane gem. Still the same ssl error.

I then tried all of the above with ruby 2.2.3 and 2.3.1 with rvm sourced rubies and clean gemsets. Still the same error.

Sorry for raising this bug again, but I don't know what to try now.

**Comment by biddster** [comment]
I've also just checked against this, https://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html. No issue there either, I'm looking in the correct place for certs.

**Comment by ycace** [comment]
@biddster I also tried all the solutions which you have tried , also i can't fix zhis problem , if you get some new way to fix it ,please notice me , thanks!

**Comment by ycace** [comment]
@biddster i final fix it with zhis [https://toadle.me/2015/04/16/fixing-failing-ssl-verification-with-rvm.html](url) try it , if u hava any problem , connet me 🤔
