### ISSUE TITLE
How to call deliver download_metadata from fastlane

### ISSUE THREAD

**Issue by felix-dumit** [fastlane/fastlane#5397]
### Issue Description

Is there any way to call `deliver download_metadata` from inside a fastlane lane?

**Comment by biolinh** [comment]
I think  you can run it via call shell  script. 
sh "delivery download_metadata"

It will be like  you run "delivery download_metadata" directly in command line.

**Comment by TKBurner** [comment]
@biolinh Thanks for stepping in. That should do the trick @felix-dumit  👍

**Comment by felix-dumit** [comment]
here's the lane i'm trying to run:

```ruby
lane :app_store do 
  sh 'deliver download_metadata'
end
```

I get this error:

```
[13:53:40]: Do you want to overwrite existing metadata on path '/Users/felixdumit/Dropbox/Copy/projects/sensortower/adblock-ios/fastlane/metadata'?

Looking for related GitHub issues on fastlane/fastlane...

➡️  Jenkins cannot find FastLane
   https://github.com/fastlane/fastlane/issues/4864 [closed] 0 💬
   26 May 2016

➡️  Deliver - Non-Interactive Mode not working for initial setup
   https://github.com/fastlane/fastlane/issues/4820 [closed] 1 💬
   27 May 2016

➡️  Bug - using fastlane to run fastlane (as shell script) fails when interaction required
   https://github.com/fastlane/fastlane/issues/3788 [closed] 3 💬
   17 Mar 2016

/Users/felixdumit/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fastlane_core-0.48.1/lib/fastlane_core/ui/interface.rb:127:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
```

I took a look at those issues and tried passing in the `--force` parameter but it still didn't work.

**Comment by TKBurner** [comment]
@felix-dumit What happens if you use a similar shell command to delete the metadata that exists in the folder first? Thanks!

**Comment by felix-dumit** [comment]
@TKBurner I still get the same results

**Comment by TKBurner** [comment]
@felix-dumit Thanks for following up. Have you tried setting the force flag to true? Thanks!

**Comment by felix-dumit** [comment]
@TKBurner This is how I tried it:

```ruby
sh 'rm -rf metadata'
sh 'deliver download_metadata --force'
```

**Comment by TKBurner** [comment]
Hi @felix-dumit Thanks for following up. Currently Deliver doesn't support this behavior when run from a lane. That is why it's not available as an option. With that in mind, if you want to build a plugin https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md that handles this behavior we'd love it!
