### ISSUE TITLE
Read Appfile values for a specific lane

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/fastlane#5398]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to create a lane that calls two other lanes that build the app with some different Appfile values. Calling the lanes on their own will read the correct for_lane values, but when the lanes are run from another lane, they don't.
How can I make the lanes always read the Appfile values for the current lane rather than the original lane being called.

`CredentialsManager::AppfileConfig.try_fetch_value()` doesn't seem to have a way to specify a lane to fetch the values for.

**Comment by TKBurner** [comment]
@Ashton-W Do you still need any help with this? Thanks!

**Comment by iONsky** [comment]
Isnt' this the same as described at #1270?
It seems that this behaviour is by design and currently not supported in the way you want it to work.
