### ISSUE TITLE
[Proposal]: Upload symbols to New Relic action

### ISSUE THREAD

**Issue by bitwit** [fastlane/fastlane#5399]
I would like to propose (and offer the code for) an action to upload symbols to new relic as a direct part of fastlane; not as a repo plugin.

Before I continue with some justification and food for thought, I just want to be clear **I've already written the action** and [it's here in a fork](https://github.com/fastlane/fastlane/compare/master...bitwit:feat/upload-symbols-new-relic) . So no matter where this goes, it's on the record for anyone else trying to solve this problem right now.

##### Why I'm proposing it be moved to a PR on this repo

1. It would be useful for many developers. With an increased emphasis on bitcode compilation, the work of getting these files all uploaded is a bigger hassle than ever and it can't be done from CI builds since iTunes Connect finishes the processing of the dsyms.
2. While I understand the documentation suggests that 3rd party API communications should go into the plugin repo and be owned by that party, I am not an employee of New Relic and I'm not really personally interested in maintaining this code on an ongoing basis though I would be happy to work on it further and polish it to the quality of a perfect PR for this repo.

So unless someone can petition New Relic to take ownership of this or you think it is PR-worthy for the main repo, I'll just leave the code as is here so that there is a documented solution for others.

Cheers!

**Comment by KrauseFx** [comment]
Thanks for creating this issue, this sounds perfectly reasonable and makes sense, as the other dsym actions are also built-in. 
Please submit a PR and we'll make sure to include this into fastlane 👍 This will also require you to add some documentation to `Actions.md`

**Comment by bitwit** [comment]
Thanks @KrauseFx! I will review the feedback provided so far, better familiarize myself with Ruby environments and see what I can do about documentation and unit testing. I copied a lot from the crashlytics code so I'll try to make sure it's got the same level of coverage and documentation.
