### ISSUE TITLE
error when trying to run tests on Jenkins 2.0 with scan

### ISSUE THREAD

**Issue by CurlyHeir** [fastlane/fastlane#5402]
i'm trying to set up continuous integration, on jenkins v2.0 with latest fastlane, 
when i want to run tests on simulator i'm getting error. 

##### Complete output when running fastlane, including the stack trace and command used

```
[33m>[0m [39;1mCheck Dependencies[0m
[33m>[0m [39;1mRunning script[0m 'Check Pods Manifest.lock'
[33m>[0m [39;1mRunning script[0m 'Embed Pods Frameworks'
[33m>[0m [39;1mRunning script[0m 'Copy Pods Resources'
[33m>[0m [39;1mBuild[0m Succeeded
2016-07-15 02:05:15.414 xcodebuild[68897:19176659] [MT] iPhoneSimulator: Could not launch simulator: -10810
xcodebuild: error: Failed to build workspace Integration-example with scheme IntegrationTests.
Reason: The operation couldn’t be completed. (OSStatus error -10810.)
invalid byte sequence in US-ASCII
[02:05:15]: [33m[33mVariable Dump:[0m[0m
[02:05:15]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios integrationTest"}
[02:05:15]: [31minvalid byte sequence in US-ASCII[0m
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :integration do 
    scan(
      clean: true,
      device: "iPhone 6s"
    )
  end 
```

Scanfile:
```ruby
workspace "Integration-example.xcworkspace"
scheme "IntegrationTests"
```

whole repo with this example is here: 
https://github.com/CurlyHeir/ios-jenkins-test-runs/commits?author=CurlyHeir

**Comment by rammangai87** [comment]
We need to do few configuration change in the CI Machine to allow Jenkins to control GUI.
Like - Changing Jenkins to LaunchAgent rather than Daemon - etc.,

There is no fastlane issue in this.

**Comment by CurlyHeir** [comment]
@rammangai87 thx for fast response, could you tell me how to configure this?

**Comment by rvi** [comment]
This article is really helpful: http://www.cimgf.com/2015/05/26/
