### ISSUE TITLE
SelectTeam should not prompt the user to select a team when running in a non-interactive session

### ISSUE THREAD

**Issue by doapp-nick** [fastlane/fastlane#5405]
### New Issue Checklist
- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

SelectTeam should not prompt the user to select a team when running in a non-interactive session

https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/ui/select_team.rb#L65

The method to select team does not respect running in a non-interactive situation.  In particular, we've had it paralyze our CI servers because it is waiting for user input that is never coming.

**Comment by JelleDamen** [comment]
hear hear

**Comment by TKBurner** [comment]
Hi @doapp-nick Thanks for reaching out about this. Are you interested in submitting a PR to change this functionality? I think it'd be interesting. Thanks!

**Comment by joedaniels29** [comment]
+ 1! this would be super!
