### ISSUE TITLE
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.

### ISSUE THREAD

**Issue by MickeyHub** [fastlane/fastlane#5408]
as title above said,  I fastlane-credentials add --username xxxx, the result is below

```
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.
Credential xxxx:****** added to keychain.
```
although the output says xxxx added to keychain, but I can't find this item in Keychain Access.

when cert or sigh use it to login iTC, the output is below:

```
[13:24:35]: Starting login with user 'negativespacetech@gmail.com'
The login credentials for 'negativespacetech@gmail.com' seem to be wrong
Do you want to re-enter your password? (y/n)
```

when I input `y`, it let me input password, the output is below after I input the correct password

```
Password (for negativespacetech@gmail.com): *******************
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.
Could not store password in keychain
```

credentials_manager is 0.16.0, it's latest version by now.
fastlane version is : 1.97.2, it's also latest version by now.

**Comment by TKBurner** [comment]
@MickeyHub Thanks for reaching out. What happens if you unlock your keychain prior to these commands? Let me know! Thanks 👍

**Comment by MickeyHub** [comment]
@TKBurner , thanks,  the keychain is unlocked, when I run this commands.

![image](https://cloud.githubusercontent.com/assets/5426838/16936282/1c285cf0-4d98-11e6-906c-09bc974caae6.png)

**Comment by TKBurner** [comment]
Hi @MickeyHub! Thanks for following up. Does this issue persist if you remove this account using

fastlane-credentials remove --username xxxx

and add it fresh?

Thanks!

**Comment by MickeyHub** [comment]
@TKBurner thx, when I'm going to remove it. the output is below:
ngsserver:~ ngsserver$ fastlane-credentials remove --username negativespacetech@gmail.com
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.

but it really exists in the KeyChain

![image](https://cloud.githubusercontent.com/assets/5426838/16976869/daede6cc-4e84-11e6-950e-177b20743ee3.png)

**Comment by MickeyHub** [comment]
and all keychains items don't prefixed with 'deliver.'

**Comment by TKBurner** [comment]
@MickeyHub Thanks for following up. What happens if you change the name off that account and try again? Let me know how it goes 👍
