### ISSUE TITLE
Can I deliver submit_build in Fastfile?

### ISSUE THREAD

**Issue by LeBlaaanc** [fastlane/fastlane#5417]
Is it possible to use `deliver submit_build` within Fastfile similar to how `deliver` works?

**Comment by asfalcone** [comment]
@LeBlaaanc not directly. You can look at the [options that `submit_build`](https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/commands_generator.rb#L52) sub command passes to deliver you should be able to replicate it using the `deliver` action.
