### ISSUE TITLE
Integration with Applivery.com

### ISSUE THREAD

**Issue by CesarTrigo** [fastlane/fastlane#5419]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Dear fastlane team,
My name is César Trigo, founder and CEO of Applivery.com (http://www.applivery.com). Our service allows companies and developers to easily deliver Apps in a fast, beauty and easy way, for both beta testing and enterprise purposes.

We just wanted to suggest work together on building a new action to deploy iOS and Android Apps to Applivery.com and I just want to know what do you think and if you can provide any documentation on how to proceed.

You already have some similar actions like TestFairy or HockeyApp that in some way do the same so maybe we can start from that point.

Our development team will be happy to contribute to the fastlane project, not only with that integration but also with everything that could be helpful.

I look forward to your reply.

Kind regards,

César

**Comment by asfalcone** [comment]
Hi @CesarTrigo! Thanks for wanting to contribute to fastlane! 😍  

The best way to add functionality to fastlane is to create a [plugin](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins). Please check out that link and let us know if you have any other questions 👍
