### ISSUE TITLE
get_build_number project path errors out

### ISSUE THREAD

**Issue by mosesoak** [fastlane/fastlane#5431]
Hey guys, I think `get_build_number` botches the `xcodeproj` input. It should work the same as `increment_build_number`'s input with the same name, but instead it appends `..` to the end of the path, which breaks. Thanks

**Comment by TKBurner** [comment]
@mosesoak Thanks for reaching out about this. I want to let the team know too, but first can you write out exact repro steps, if you could include your input and output as well that'd help. I'm going to mark this as help wanted in case anyone wants to take a look in the meantime. Thanks!

**Comment by mosesoak** [comment]
sure

0. start with an Xcode project that has a valid 3-part version number like 0.0.0
1. put your Xcode project in a subfolder like 'ios'
2. write a fastlane command that performs `increment_build_number` by passing the relative path to the project from the repo root (fastlane seems to automatically cd up out of its directory before targeting which is convenient)
  - as expected, the version number is incremented
3. using the same path parameter, make the command run `get_build_number`
  - unexpectedly errors based on the path that it is trying to build, which appends '..' (not prepends) to the path you passed, this is a mistake I think

**Comment by TKBurner** [comment]
@mosesoak Thanks for sharing! I've reached out to the team. We will see what we can do to improve this. Thanks!
