### ISSUE TITLE
Snapshot tool can remain stuck forever if "xcrun simctl list devices" is stuck.

### ISSUE THREAD

**Issue by cleclef** [fastlane/fastlane#5435]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Snapshot tool can remain stuck forever if "xcrun simctl list devices" is stuck in device_manager.rb
at

```
Open3.popen3('xcrun simctl list devices') do |stdin, stdout, stderr, wait_thr|
```

I encounter that the snapshot tool was blocked. I found out that it was waiting for xcrun command output, but xcrun was stuck. When I killed xcrun, snapshot tool continue (of course with error on the xcrun command itself).
##### Complete output when running fastlane, including the stack trace and command used

```
10:42:35 Analyzing dependencies
10:42:35 Downloading dependencies
10:42:35 Generating Pods project
10:42:36 Integrating client project
10:42:37 Sending stats
10:42:37 Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
10:42:37 + snapshot
[STUCK FOREVER!]
08:45:47 [08:45:47]: xcrun simctl CLI broken, run `xcrun simctl list devices` and make sure it works
08:45:47 [08:45:47]: Error setting value '["iPhone 4s", "iPhone 5", "iPhone 5s", "iPhone 6", "iPhone 6s", "iPhone 6s Plus", "iPad 2", "iPad Air", "iPad Air 2", "iPad Pro", "iPad Retina"]' for option 'devices'
08:45:47 
08:45:47 [!] xcrun simctl not working.
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:

``` ruby
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from

devices([
   "iPhone 4s",
   "iPhone 5",
   "iPhone 5s",
   "iPhone 6",
   "iPhone 6s",
   "iPhone 6s Plus",
   "iPad 2",
   "iPad Air",
   "iPad Air 2",
   "iPad Pro",
   "iPad Retina"
]);

ios_version "9.3"

languages([
  "en-US",
  "fr-BE",
  "nl-BE"
])

# Clean before building it
clean

localize_simulator true

number_of_retries 3

# The name of the scheme which contains the UI Tests
scheme "xxx"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

# clear all previously generated screenshots before creating new ones
clear_previous_screenshots true

# Choose which project/workspace to use
workspace "./xxx.xcworkspace"

# do not open the browser with the result at the end
skip_open_summary true

app_identifier "xxx"

erase_simulator true

reinstall_app "xxxx"

```
### Environment

fastlane version (run `fastlane -v`):
No fastlane, only snapshot

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by TKBurner** [comment]
Hi @cleclef Hope you are doing well! Can you send over the output of `xcrun simctl list devices`


Thanks!

**Comment by cleclef** [comment]
It is 99% of the time working this command. I don't why sometimes it's stuck. Probably an iOS bug...

<pre>
:~ admin$ xcrun simctl list devices
== Devices ==
-- iOS 8.4 --
    iPhone 4s (9354F5BB-B2AE-4BA4-A6FA-4EE9823304A8) (Shutdown)
    iPhone 5 (1F5FC6D8-C3D8-4C78-8481-2CDB5111C9BA) (Shutdown)
    iPhone 5s (950BC74A-5F41-45DD-8118-042353B34BCC) (Shutdown)
    iPhone 6 (B2699442-139A-4473-B30C-4E237926212C) (Shutdown)
    iPhone 6 Plus (E2F66BD8-5489-4A2E-BA08-3A123DA54E45) (Shutdown)
    iPad 2 (34BEDC62-D246-4E66-9BF5-525087E63C4C) (Shutdown)
    iPad Retina (108CB882-ACD1-42E2-80F7-2C9CD79B2B52) (Shutdown)
    iPad Air (CC5EA838-CA63-40DC-8E29-80A07BB1F5AD) (Shutdown)
    iPad Air 2 (38864798-F869-4A57-AC7A-CE2E32DC0BF5) (Shutdown)
-- iOS 9.0 --
-- iOS 9.3 --
    iPhone 4s (95FCAEAB-119A-4B6C-AD3D-0305B9D75BDD) (Shutdown)
    iPhone 5 (B8B8B522-4022-4730-8606-B255DABBE2BE) (Shutdown)
    iPhone 5s (B943B286-1BAF-46ED-ACE4-B3ED18919A34) (Shutdown)
    iPhone 6 (FFF64372-DCD5-4031-BFCA-52DF6C7B9650) (Shutdown)
    iPhone 6 Plus (6DE3380A-5E95-412B-B9A4-F9E59A2545AD) (Shutdown)
    iPhone 6s (FBAE2EB4-E073-4731-B7DF-DB3D6732D9BB) (Shutdown)
    iPhone 6s Plus (939DCBC0-E981-4490-BB79-1E571562E692) (Shutdown)
    iPad 2 (1F67AEF7-4717-4CBE-8E0A-9E1F0CC687B3) (Shutdown)
    iPad Retina (D7409705-97DA-4E49-90BE-9305A03F788E) (Shutdown)
    iPad Air (5889CF87-5F24-4507-BDA1-FECA9B39DA07) (Shutdown)
    iPad Air 2 (8810166B-B1C7-4FEE-AE3F-A1C4CE865B46) (Shutdown)
    iPad Pro (07418253-9CC6-486F-A079-E1AD2B897B5A) (Shutdown)
-- tvOS 9.2 --
-- watchOS 2.2 --
-- Unavailable: com.apple.CoreSimulator.SimRuntime.watchOS-2-0 --
    Apple Watch - 42mm (D7C87C2B-682F-43D5-A1E3-31EBE7EEBDA7) (Creating) (unavailable, runtime profile not found)
</pre>

That's why I suggest timeout such as:

<pre>
require 'timeout'
status = Timeout::timeout(5) {
  Open3...('xcrun. ...')
}
</pre>

**Comment by TKBurner** [comment]
Hi @cleclef Thanks for following up. If you are interested in submitting a PR to add this we'd be happy to work with you. Let me know! 👍

**Comment by mgrebenets** [comment]
We have just started migrating to Xcode 8 and faced this issue.
It started happening on our TeamCity agents when building with Xcode 8 while previous build was using Xcode 7.3.1.
It is actually quite easy to reproduce on a local machine too.
Let's say you have Xcode 8 installed to `/Applications/Xcode.app` and Xcode 7.3.1. to `/Applications/Xcode7.3.1.app`. The following shell scripts will reproduce the issues with about 90% probability.

```
# Launch Xcode 8 simulator
DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer osascript -e 'open app "Simulator"'
sleep 5 # Give it time to start

# Kill all simulators (this is just the way our CI setup works)
echo "---Kill"
killall -9 Simulator || echo "Not found"

# Wait here for 5 seconds, but this will not help the issue
# Then next simctl will still fail
sleep 5

# Run any kind of xcrun simctl command
# Can be erase or list devices
echo "---List"
DEVELOPER_DIR=/Applications/Xcode7.3.1.app/Contents/Developer xcrun simctl list devices # 2>/dev/null
echo "Last command: $?" # This will fail with 90% chances and will return 134 error code

sleep 5 # Wait for some time

# Run simctl command again
echo "---List again"
DEVELOPER_DIR=/Applications/Xcode7.3.1.app/Contents/Developer xcrun simctl list devices # 2>/dev/null 1>/dev/null
echo "Last command: $?"
```

As you can see killing running simulators does not fix the issue.
The workaround is to run `simctl` command 2 times in a row with a pause between runs.
`5` seconds is the empirical timeout value we've got so far.

Though I don't thing waiting for fixed time is a solution.
If we do have to use workaround we'd better try to run `simctl` command until it's successful and bail out if number of retry is above certain limit.

In terms of bash script it would be something like

```
# Launch Xcode 8 simulator
DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer osascript -e 'open app "Simulator"'
sleep 5 # Give it time to start

# Kill all simulators (this is just the way our CI setup works)
echo "---Kill"
killall -9 Simulator || echo "Not found"

export DEVELOPER_DIR=/Applications/Xcode7.3.1.app/Contents/Developer
xcrun simctl help 2>/dev/null
while [[ $? -ne 0 ]]; do
    sleep 1
    xcrun simctl help 2>/dev/null
done

# Now it's good to list devices
xcrun simctl list devices
```

So I guess similar fix needs to be applied in Ruby code where `Open3` is used.


I'm pretty sure there must be a better fix, but this is the best we've came up with so far.

**Comment by TKBurner** [comment]
@mgrebenets Thanks so much for sharing. Any chance you are interested in applying a general solution for two versions of Xcode as a PR? This seems like a cyclical issue that'll pop up every year during update season and it'd be great if we can future proof.

**Comment by mgrebenets** [comment]
I have wrapped it into a custom action. I'll invest some time and turn it into a plugin then.

Do you think it should be a plugin or part of fastlane core code?
This looping command needs to be executed before any other Xcode toolchain call and only makes sense in context of switching Xcode version. So I think it would be hard to put it in fastlane itself, because there may be no such place which is always executed first.

With plugin people can simply put it in `before_all` hook right after `DEVELOPER_DIR` is set.

**Comment by mgrebenets** [comment]
Here it is: https://rubygems.org/gems/fastlane-plugin-wait_xcrun

Just published it and haven't yet fully tested in our project. Will post an update later.

**Comment by mgrebenets** [comment]
Looks good when plugged into one of our projects, action runs all the same.

**Comment by TKBurner** [comment]
@mgrebenets Very cool. We'll leave it a plugin for now since we are only graduating plugins into actions, no more direct path. I'm curious to know what type of fastfile you are running with this plugin. Thanks!

**Comment by mgrebenets** [comment]
@TKBurner you mean where do I call the plugin or how the whole file looks like?

**Comment by TKBurner** [comment]
@mgrebenets Thanks for getting back to me. Hope you are having a nice week. What order are you running this with snapshot? Thanks!

**Comment by mgrebenets** [comment]
@TKBurner this particular plugin needs to be run before _any other_ command that uses `xcrun` or `xcodebuild` or other commands from Xcode toolchain.

I would assume `snapshot` is using `xcrun simctl` for launching simulator, so plugin should run before `snapshot`.

I've put it in README, the best place is in `before_all` hook:

```
before_all do
  # Make sure proper Xcode version is selected by CI server
  # or by setting DEVELOPER_DIR environment variable

  wait_xcrun
end
```

**Comment by TKBurner** [comment]
@mgrebenets Thank you! Really appreciate your contributions. Can you email me at burner@twitter.com, I want to ask you something on a private channel?
