### ISSUE TITLE
Question: checking app name and bundle id for avalibility without creating apps

### ISSUE THREAD

**Issue by punksta** [fastlane/fastlane#5436]
In our service apps are created from web-ui. Is it possible to check entered app name and bundle id for availability in Dev portal and Itunes connect by ruby script?

**Comment by TKBurner** [comment]
Hi @punksta Thanks for reaching out. Right now we don't have a tool to do this in an automated way. 
This sounds like a great use of a plugin. The best way to add functionality to fastlane is to create a [plugin](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins). Please check out that link and let us know if you have any other questions 👍
