### ISSUE TITLE
not all lanes of all platforms are listed when running fastlane

### ISSUE THREAD

**Issue by Lutzifer** [fastlane/fastlane#5437]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x]  I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Given multiple platforms in a fastfile, either only the ones from the default platform are presented to the user (if a default platform is defined)  or fastlane does not find any lanes (see output).

I use fastlane to manage cross platform builds, so having two platforms in the same fastfile is very useful.

'fastlane lanes' correctly lists all lanes, so doing something like the "--- Step: default_platform ---" step across platforms would be very nice.
##### Complete output when running fastlane, including the stack trace and command used

```
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated

Looking for related GitHub issues on fastlane/fastlane...

➡️  Lanes table
   https://github.com/fastlane/fastlane/pull/4076 [closed] 6 💬
   08 Apr 2016


[!] It looks like you don't have any lanes to run just yet. Check out how to get started here: https://github.com/fastlane/fastlane 🚀
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
platform :ios do
  desc "An iOS Lane"
  lane :laneForIOS do
  end
end

platform :android do
  desc "An Android Lane"
  lane :laneForAndroid do
  end
end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.98.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
Hi @Lutzifer Thanks for reaching out. Can you share your full input and output? I want to take a look. Thanks!

**Comment by Lutzifer** [comment]
you can simply take the fastfile and then run `fastlane`

I don't know what to add more, but will try.

**Comment by TKBurner** [comment]
Hi @Lutzifer Thanks for following up. Can you provide the full command you entered and all output of fastlane up to the error? Thanks!

**Comment by Lutzifer** [comment]
Ok, i'll try to be more specific:

**Case 1: Fastfile with default platform**

Fastfile:

```ruby
default_platform :ios

platform :ios do
  desc "An iOS Lane"
  lane :laneForIOS do
  end
end

platform :android do
  desc "An Android Lane"
  lane :laneForAndroid do
  end
end
```

Command and Output:

```
$  bundle exec fastlane
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[22:51:49]: ------------------------------
[22:51:49]: --- Step: default_platform ---
[22:51:49]: ------------------------------
[22:51:49]: Welcome to fastlane! Here's what your app is setup to do:
+--------+----------------+------------------------------+
|                 Available lanes to run                 |
+--------+----------------+------------------------------+
| Number | Lane Name      | Description                  |
+--------+----------------+------------------------------+
| 1      | ios laneForIOS | An iOS Lane                  |
| 0      | cancel         | No selection, exit fastlane! |
+--------+----------------+------------------------------+
Which number would you like run?
```

**Case 2: Fastfile without default platform**

Fastfile:

```ruby
platform :ios do
  desc "An iOS Lane"
  lane :laneForIOS do
  end
end

platform :android do
  desc "An Android Lane"
  lane :laneForAndroid do
  end
end
```

Actual Command and Output:

```
$  bundle exec fastlane
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated

Looking for related GitHub issues on fastlane/fastlane...

➡️  not all lanes of all platforms are listed when running fastlane
   https://github.com/fastlane/fastlane/issues/5437 [open] 3 💬
   2 hours ago

➡️  Lanes table
   https://github.com/fastlane/fastlane/pull/4076 [closed] 6 💬
   08 Apr 2016


[!] It looks like you don't have any lanes to run just yet. Check out how to get started here: https://github.com/fastlane/fastlane 🚀
```

Expected/More useful output:

```
$  bundle exec fastlane
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[22:51:49]: ------------------------------
[22:51:49]: --- Step: default_platform ---
[22:51:49]: ------------------------------
[22:51:49]: Welcome to fastlane! Here's what your app is setup to do:
+--------+----------------+------------------------------+
|                 Available lanes to run                 |
+--------+----------------+------------------------------+
| Number | Lane Name      | Description                  |
+--------+----------------+------------------------------+
| 1      | ios laneForIOS | An iOS Lane                  |
| 2      | android laneForAndroid | An Android Lane                  |
| 0      | cancel         | No selection, exit fastlane! |
+--------+----------------+------------------------------+
Which number would you like run?
```

**Comment by stovmascript** [comment]
I'm seeing the same thing and would also like to see all available lanes when executing `fastlane`.

This is my output, when I comment out `default_platform`:

```shell
$ fastlane
[09:44:05]: -------------------------------------------------
[09:44:05]: --- Step: Verifying required fastlane version ---
[09:44:05]: -------------------------------------------------
[09:44:05]: fastlane version valid

[!] It looks like you don't have any lanes to run just yet. Check out how to get started here: https://github.com/fastlane/fastlane �
```

**Comment by TKBurner** [comment]
@stovmascript Thanks for following up. Does `fastlane lanes` provide the correct output? I'm marking this to see if someone from the community is interested in submitting a PR.

**Comment by stovmascript** [comment]
Yup, that's what I'm currently using to get an overview of all available
lanes.

**Comment by TKBurner** [comment]
@stovmascript Thanks! The common usage command is fastlane lanes, but since we have the behavior for running just fastlane it should work there. I think we'd love to see a community PR! Thanks for pointing this out, hope you have a great day!
