### ISSUE TITLE
ERROR - Snapshot don't use my .PCH during compilation

### ISSUE THREAD

**Issue by AmityTek** [fastlane/fastlane#5438]
### New Issue Checklist

- [Yes] Updated fastlane to the latest version
- [Yes] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

i run just snapshot without flag 
i don't understand why fastlane don't use my .pch during compilation
whereas xcode compile with it !

Testing failed:
No known class method for selector 'MR_defaultContext'
** TEST FAILED **

### Configuration Files

i use the original files
i just need to use snapshot !

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
Hi @AmityTek Hope you are doing well! Can you send out the full input and output you get when you have this error? I'd love to take a look 👍

**Comment by AmityTek** [comment]
Thanks for answer ! I think its ok thanks you again :)
