### ISSUE TITLE
[spaceship] add new languages

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#5456]
Hi Guys

With spaceship can i do that?

- Is it possible to add a new version for an app with Spaceship?
- Is it possible to add a new language for an app with Spaceship?

B

**Comment by KrauseFx** [comment]
Yes, it supports all that, please check out the source code for more information

e.g. https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/application.rb#L153 and https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_version.rb#L197

**Comment by KrauseFx** [comment]
I hope that helps, feel free to submit a PR improving the docs if you feel like it helps other users, any help appreciated 👍

**Comment by bolom** [comment]
@KrauseFx thanks 

>  hope that helps, feel free to submit a PR improving the docs if you feel like it helps other users, any help appreciated

sure

**Comment by KrauseFx** [comment]
Awesome, thanks @bolom 👍

**Comment by bolom** [comment]
@KrauseFx i don't see in the doc a way to delete a screenshoot. We can just upload?

**Comment by KrauseFx** [comment]
You can also delete, you might want to dive into the deliver source code, which does all of those things 👍

**Comment by bolom** [comment]
ah thanks @KrauseFx
