### ISSUE TITLE
Deliver drops app preview videos

### ISSUE THREAD

**Issue by martnst** [fastlane/fastlane#5457]
On my latest upload of metadata & screenshots `deliver 1.13.1` removed the app preview videos in iTC.

I cloud not find anybody reporting this before, which makes me wondering if that's special circumstances for me or just didn't bother anybody else before.

**Comment by TKBurner** [comment]
@martnst Thanks for reaching out. I haven't heard any other reports of this. Can you confirm if you are able to duplicate this if you run deliver again? Thanks so much for reporting this and working with me 👍

**Comment by martnst** [comment]
I actually had the video being dropped again working with iTC directly. Hence it's probably not related to fastlane.

**Comment by TKBurner** [comment]
@martnst Thanks for following up. Hope you project is going well!
