### ISSUE TITLE
Path escaping across actions is inconsistent

### ISSUE THREAD

**Issue by michaelharro** [fastlane/fastlane#5458]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Some fastlane actions call `shellecape` on my paths and some don't. None of the actions document whether they will or not. For me to figure out if I need to provide an escaped path or an unescaped path I need to look into the implementation of the action. It would be nice if there was a standard across fastlane about escaping paths. It could be standard in documentation or it could be a standard for implementation, both work. But it is very time consuming trying to use fastlane on servers that need their paths escaped and a standard would really reduce that time.

Thanks for your consideration.
##### Complete output when running fastlane, including the stack trace and command used

The output varies on the action and is not overly helpful as this is a bigger picture issue.
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Here is a portion of my fastfile that deals with directories. You can see that most of them are escaped but carthage does the escaping for me so I have to use the unescaped path for it. The keychain actions also escape paths for me.

Fastfile:

``` ruby
        # Set output directory
        output_directory_path = "#{cru_output_directory_escaped}/builds"
        UI.message "Set output directory path to: \"#{output_directory_path}\"."
        ENV['GYM_BUILD_PATH'] = output_directory_path
        ENV['GYM_OUTPUT_DIRECTORY'] = output_directory_path
        ENV['BACKUP_XCARCHIVE_DESTINATION'] = output_directory_path

        # Set derived data
        derived_data_path = "#{cru_output_directory_escaped}/derivedData"
        UI.message "Set derived data path to: \"#{derived_data_path}\"."
        ENV['DERIVED_DATA_PATH'] = derived_data_path # Used by clear_derived_data.
        ENV['XCODE_DERIVED_DATA_PATH'] = derived_data_path
        ENV['GYM_DERIVED_DATA_PATH'] = derived_data_path
        ENV['SCAN_DERIVED_DATA_PATH'] = derived_data_path
        ENV['FL_CARTHAGE_DERIVED_DATA'] = "#{cru_output_directory}/derivedData"

        # Set screenshot directory
        ENV['SNAPSHOT_OUTPUT_DIRECTORY'] = "#{cru_output_directory_escaped}/screenshots"
        UI.message "Set screenshot output path to: \"#{ENV['SNAPSHOT_OUTPUT_DIRECTORY']}\"."

        # Set unit test output directory
        ENV['SCAN_OUTPUT_DIRECTORY'] = "#{cru_output_directory_escaped}/unit_test_reports"
        UI.message "Set unit test output path to: \"#{ENV['SCAN_OUTPUT_DIRECTORY']}\"."

        # Set code coverage output directory
        ENV['XCOV_OUTPUT_DIRECTORY'] = "#{cru_output_directory_escaped}/code_coverage_reports"
        UI.message "Set code coverage output path to: \"#{ENV['XCOV_OUTPUT_DIRECTORY']}\"."
```
### Environment

fastlane version (run `fastlane -v`): 1.98.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by TKBurner** [comment]
Hi @michaelharro Thanks for reaching out about this. I'm going to mark this as a feature request and close it for house keeping purposes. If you are interested in submitting a PR we can work with you!

**Comment by michaelharro** [comment]
I would be open to submitting a PR. However, ruby is not my primary language and this could impact a lot of actions. I'm not sure I feel comfortable tackling it myself. I did submit a PR to xcov to fix the problem in that action and what I discovered in the process was that Ruby requires unescaped paths and `sh` requires escaped paths so what should happen is that all actions should take unescaped paths, which should be noted somewhere in the action docs and then each action should be responsible for escaping paths just before they are sent to `sh`. This should be noted in the new action documentation. Someone should also probably go through existing actions  and fastlane core code and make sure that they escape paths before sending them to `sh` (that is going to be a terrible task. It is one I can help with but I didn't write a lot of the code so I might miss ones that aren't obvious).

Do you have thoughts on how best to move forward?

**Comment by TKBurner** [comment]
Hi @michaelharro Thanks for following up. I'll mark this as help wanted so someone can step in here. Thanks!

**Comment by michaelharro** [comment]
this is still an issue. Here is an example of where the problem exists in the current codebase https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/fast_file.rb#L214-L223

**Comment by TKBurner** [comment]
@michaelharro Thanks for following up. Are you interested in submitting a PR to clean up some of this behavior? Thanks!

**Comment by michaelharro** [comment]
np. theoretically I would be happy to do it but I am a new Dad and rarely have time to contribute to open source stuff these days. I would not rely on me to be able to do this.

**Comment by TKBurner** [comment]
@michaelharro Thanks! We'll leave this open in case someone else is interested in working on this. Thanks!

**Comment by michaelharro** [comment]
I still see examples of this in the code base so I think it should be kept open

**Comment by KrauseFx** [comment]
Sorry about that, the bot will keep coming back here every few weeks/months... We currently don't have the resources to work on this, however this would definitely be a nice thing. We're more than happy to review and merge a pull request whenever you have the time or somebody else jumps in 👍 

Congrats on being a dad!
