### ISSUE TITLE
Add commit/object option to add_git_tag

### ISSUE THREAD

**Issue by Liquidsoul** [fastlane/fastlane#5459]
### Suggestion

Allow to call the action with a commit/object option: `add_git_tag(tag: 'release', object: 'release_candidate')`

### Motivation

I'd like to be able to specify the commit where to put the tag in the git history instead of needing to perform a manual checkout of the commit.

The git command looks like this `git tag <tagname> <commit>`.
See the [`git-tag`](https://www.git-scm.com/docs/git-tag) documentation for more information on this.

This can allow to tag existing objects in the repository without needing to checkout at the said object before adding the tag in fastlane. In my case, once I've released a release candidate version to the app store, I want to add a `release` tag where my `release_candidate` is alongside some other automated stuff done using fastlane.

### Implementation

In the action, the implementation would be to just add an optional parameter to the action that would be added to the command just after [this line](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/add_git_tag.rb#L15).
I would be delighted to contribute again and do this 😉

**Comment by TKBurner** [comment]
Hi @Liquidsoul Thanks for reaching out and filling out an issue. We will happily work with you on this PR. I'm going to close out this issue in favor of the PR. Thanks!
