### ISSUE TITLE
Run match appstore but nothing happen

### ISSUE THREAD

**Issue by douglasalexandre** [fastlane/fastlane#5460]
When run `match appstore` he start with a message: `Cloning remote git repo...` but after this, nothing more happened. 

Ruby version
```ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]```

When i force the stop process, i received this message:
``` ^C[16:02:43]: 🔒  Successfully encrypted certificates repo```

I repeat this process several times, but I got always the same result

**Comment by nmcdonaldd** [comment]
Same thing here.

**Comment by douglasalexandre** [comment]
@nmcdonaldd 
My problem was here:
with problem: i commented this line code
```#type "development" # The default type, can be: appstore, adhoc or development```
without problem: i uncommented this line code
```type "development" # The default type, can be: appstore, adhoc or development```

**Comment by nmcdonaldd** [comment]
Just tried that and it doesn't work for me still unfortunately. Thanks for your input, however!

**Comment by TKBurner** [comment]
HI @nmcdonaldd Can you share your matchfile? Thanks!
