### ISSUE TITLE
update_app_identifier action to read Appfile bundle id value

### ISSUE THREAD

**Issue by aln787** [fastlane/fastlane#5464]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The Fastlane action `update_app_identifier` doesn't read the Appfile value `app_identifier`.  I would expect that this action would read this value so you don't have to reset your bundle identifier value in `FL_UPDATE_APP_IDENTIFIER`.

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.94.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by aln787** [comment]
Thanks @jaleksynas thanks for taking a look.

**Comment by TKBurner** [comment]
Hi @aln787! Thanks for pointing this out. Since there is already a PR. I'm going to close this out for now. Hope you have a wonderful weekend 👍
