### ISSUE TITLE
[iOS] Preprocessor macros

### ISSUE THREAD

**Issue by kennygunie** [fastlane/fastlane#5472]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I would like to inject a password from jenkins (with preprocessor macros) during the build. 

Fastfile1:
gym(
      clean: true,
      xcargs:"CERTIFICATE_PASSWORD=**@\"secret\"**",
      use_legacy_build_api:true)

Fastfile second try:
gym(
      clean: true,
      xcargs:"CERTIFICATE_PASSWORD=**\@\"secret\**"",
      use_legacy_build_api:true)

Build Settings:
Processor Macros        CERTIFICATE_PASSWORD=$(CERTIFICATE_PASSWORD)

But I receive an error:
❌  unexpected '@' in program
NSString *const ServiceConfigP12Password = CERTIFICATE_PASSWORD;
                                                     ^~~~~~~~~~~
How can I inject "secret" to ServiceConfigP12Password ? Thanks

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.98.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Yes, RVM

**Comment by TKBurner** [comment]
Hi @kennygunie Thanks for reaching out. You should be using ENV to get this working. Search our repo for more info! Hope you have a wonderful weekend 👍
