### ISSUE TITLE
update_project_team action to read Appfile bundle id value

### ISSUE THREAD

**Issue by aln787** [fastlane/fastlane#5477]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The Fastlane action `update_project_team` doesn't read the Appfile value team_id. I would expect that this action would read this value so you don't have to reset your team id value in `FL_PROJECT_TEAM_ID`.

##### Complete output when running fastlane, including the stack trace and command used
N/A

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

N/A

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.98.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
@aln787 I see we are working with you on your PR. Closing out this issue for housekeeping! Thanks so much for contributing 💯 💯 💯
