### ISSUE TITLE
snapshot ios10 simulators ?

### ISSUE THREAD

**Issue by chnbr** [fastlane/fastlane#5483]
Hi,

I am trying to setup iOS 10 simulators for snapshot with Xcode 8beta3. The XCtests are correctly setup, but it always tries to start ios9.3 sims. 

How to do that ? The -i 10 option does not work.

fastlane version (run `fastlane -v`): 1.98.0

Thanks
Chris

**Comment by TKBurner** [comment]
Hi @chnbr Thanks for reaching out. We don't support ios10 simulators yet. However, I'm going to mark this as a feature request so we can track it and see if anyone from the community wants to implement it. Thanks!

**Comment by chnbr** [comment]
Hi,

further info:

I found out that snapshot basically is working with ios 10 simulators, if you set it up like below. 

The only bug I found is that the simulator is not terminated  correctly by snapshot after the text is completed. If you terminate the simulator manually, the script goes on and produces the next localization. I guess fixing this is not a  big issue.

Regards
Chris

**Comment by TKBurner** [comment]
@chnbr Thanks for sharing that'll help in tracking this down. Hopefully someone from the community is interested in submitting a PR. Thanks!
