### ISSUE TITLE
Copy app data to .app before taking screenshots with Snapshot

### ISSUE THREAD

**Issue by bvirlet** [fastlane/fastlane#5485]
Hi @KrauseFx,

I'm trying to setup some app data before doing my screenshots. In some other Issues, I noticed that you suggested using `setup_for_device_change` to copy the files in the .app, but this was removed in Snapshot 1.0. What is the recommended workaround?

Thanks!

**Comment by TKBurner** [comment]
Hi @bvirlet Thanks for reaching out. You can always use shell commands with the `sh` action.

What specifically are you trying to setup, your app or the simulator?

Thanks!

**Comment by bvirlet** [comment]
I would like to setup the app. On the device, I can upload an .xcappdata using Xcode schemes, but that's not possible on the simulator. 

The example referred to in the documentation is https://github.com/fastlane/examples/blob/master/MindNode/Snapfile#L46.

I'm happy to use the `sh` actions but how do I copy the files to the right app folder between each snapshot session (locale/device).

Thanks!
