### ISSUE TITLE
pem from terminal doesn't work

### ISSUE THREAD

**Issue by akudryashov** [fastlane/fastlane#5486]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

So, today I needed to create pem certification with p12 and I dealt with 2 problems.
1. parameter output_path doesn't works. (Also if I already have the directory)
2. files aren't created in whole mac.

##### Complete output when running fastlane, including the stack trace and command used

MacBook-Pro-Anton:baby.ru AntonKudryashov$ pem --output_path:"fastlane/pem/" --generate_p12:true
/Users/AntonKudryashov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated

+------------------+---------------------+
|         Summary for PEM 1.3.1          |
+------------------+---------------------+
| development      | false               |
| generate_p12     | true                |
| force            | false               |
| save_private_key | true                |
| username         | _appleID_ |
| team_id          | E998C2ZJFE          |
| output_path      | .                   |
+------------------+---------------------+

[21:13:36]: Starting login with user '_appleID_'
[21:13:43]: Successfully logged in
[21:13:44]: To not be asked about this value, you can specify it using 'app_identifier'
The bundle identifier of your app: ru.babik.babik
[21:13:50]: Existing push notification profile 'ru.babik.babik' is valid for 224 more days.
[21:13:50]: You already have a push certificate, which is active for more than 30 more days. No need to create a new one
[21:13:50]: If you still want to create a new one, use the --force option when running PEM.

### Environment
fastlane 1.98.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

**Comment by asfalcone** [comment]
@akudryashov When calling `pem` from the command line, you don't need to use the `key:value` syntax.

Can you try running `pem --output_path "fastlane/pem/" --generate_p12 true`?  and let me know how that works? 👍
