### ISSUE TITLE
Any tools for Android similar to the Produce of Fastlane?

### ISSUE THREAD

**Issue by none2011** [fastlane/fastlane#5487]
Hello, Thanks for your team's great work.
Any tools for Android similar to the Produce of Fastlane, which can create apps through command line ?

**Comment by asfalcone** [comment]
Hi @none2011. Thanks for the question. Currently there is no API to create apps in Google Play. They require an uploaded APK to build the foundation of the project. I'm going to close this for now, but if Google makes such an API available we'd love to consider a tool like this 👍
