### ISSUE TITLE
Update to latest version of deliver

### ISSUE THREAD

**Issue by biesbjerg** [fastlane/fastlane#5489]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Trying to use deliver to upload screenshots. It doesn't detect da-DK, sv-SE and other locales. There's a ticket for it here: https://github.com/fastlane-old/deliver/issues/317

It should be fixed in version 1.13.4, but I get 1.13.1 when installing via gem. Is that expected? How do I update?

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.98.0
deliver 1.13.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by TKBurner** [comment]
Hi @biesbjerg Great to hear from you! Can you run `sudo gem update fastlane` and then send me the output of deliver -v Thanks!
