### ISSUE TITLE
Scan hanging when trying to fetch workspaces

### ISSUE THREAD

**Issue by tspecht** [fastlane/fastlane#5490]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I'm trying to run my tests using scan. However the command is stuck for more than 15 minutes (reproducable) while trying to fetch the schemes and targets of my workspace through `xcodebuild`. When trying the printed command myself everything works as expected. If I run everything against Xcode 7.2 instead of Xcode 7.3.1 everything works as expected.
##### Complete output when running fastlane, including the stack trace and command used

Command:

```
scan(
      skip_build: true,
      scheme: 'MyScheme',
      output_directory:'reports',
      output_types:'html',
      clean: true,
      device: options[:device],
      code_coverage: true
    )
```

Output:

```
[15:03:51]: --- Step: scan ---
[15:03:51]: ------------------
[15:03:52]: xcrun xcodebuild -list -workspace ./Dubsmash.xcworkspac
```
### Environment

fastlane version (run `fastlane -v`): 1.98.0

scan version: 0.8.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
Hi @tspecht! Thanks for reaching out. Can you share the full output when you run your lane with the --verbose flag? Also, do you have Xcode 8 installed on your machine? Thanks!

**Comment by tspecht** [comment]
Hey, thanks for the reply! I do not have Xcode 8 installed. When I run `fastlane test --verbose` somehow the output doesn't change?! Weird ...

**Comment by tspecht** [comment]
Hi @TKBurner , did you have a chance to look into this already?

**Comment by KrauseFx** [comment]
Hey @tspecht, sorry for the delayed reply. 

Unfortunately we've had some of those reports in the past (e.g. https://github.com/fastlane/fastlane/issues/5163), however these kind of issues are super hard to reproduce locally. 

I only have Xcode 7.3.0 installed locally, so I'm downloading 7.3.1 to try to reproduce your issue. In the mean-time, do you run into the same problem on a newly created Xcode project?

**Comment by KrauseFx** [comment]
I wonder if that issue in general is resolved by Apple's fix in the latest Xcode Beta (https://github.com/supermarin/xcpretty/issues/227#issuecomment-236719334)

**Comment by ChristopherDrum** [comment]
I'm having similar hanging issues on Travis CI using Xcode 8 build.
Like @IngmarStein reports with Gym: https://github.com/fastlane/fastlane/issues/5163
I see the "failed to expand identifiers" issue with Scan as well.

Like @tspecht reports, Scan hangs, but hangs at a different spot
```
Running Tests: ▸ Touching <<REDACTED>>.xctest
▸ Signing /Users/travis/Library/Developer/Xcode/DerivedData/<<REDACTED>>-fjcdsntgidituxdawvnlxqyifuvi/Build/Products/Debug-iphonesimulator/<<REDACTED>>.app/PlugIns/<<REDACTED>>Tests.xctest
```

which seems to relate to something @tmm1 said about code signing:https://github.com/fastlane/fastlane/issues/5163#issuecomment-246099180

but I can't get it to proceed with automatic nor manual code signing so far.

**Comment by TKBurner** [comment]
@ChristopherDrum Can you run `sudo gem update fastlane` and then run this again providing the full input and output? I want to get this over to the core team 👍
