### ISSUE TITLE
[snapshot] summary report shows "4.7-Inch" instead of "iPhone6s"

### ISSUE THREAD

**Issue by tcurdt** [fastlane/fastlane#5502]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running the `snapshot` from `fastlane` generates the report just fine. It does not show the device name `iPhones6s` but `4.7-Inch` instead though. Is there a way to change that?

Also: Is there a template for the report that could be adjusted?

##### Complete output when running fastlane, including the stack trace and command used

NA

### Configuration Files

```
devices([
  "iPhone 6s",
])

languages([
  "de-DE",
])

ios_version '9.3'
reinstall_app true
erase_simulator true
skip_open_summary true
clear_previous_screenshots true
output_directory "./Screenshots"
stop_after_first_error true
```

### Environment

fastlane version (run `fastlane -v`):

`fastlane 1.98.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

chruby

**Comment by TKBurner** [comment]
Hi @tcurdt Thanks for reaching out. Right now this is not an option however, you could definitely implement this in a plugin by manipulating our html file. Let me know if you have any questions.

**Comment by tcurdt** [comment]
@TKBurner So why is it shown here then?

https://github.com/fastlane/fastlane/blob/master/snapshot/assets/htmlPagePreviewFade.jpg

**Comment by TKBurner** [comment]
Hi @tcurdt Thanks for following up. The reason for this change is now there are multiple versions of the iPhone with the same screen size. However, if you'd like to make a PR with the titles annotated with example devices that'd be great!

**Comment by tcurdt** [comment]
@TKBurner Not sure I can follow the reasoning. So when I configure `devices([ ... ])` to include two iPhones that share the same screen size - what will happen?

**Comment by TKBurner** [comment]
Hi @tcurdt Do you apply multiple screenshots to the different sizes in iTC? Thanks!

**Comment by tcurdt** [comment]
@TKBurner not sure I understand the intent of the question

The iPhone SE has a screen size of 4" so has the iPhone 5 and the iPhone 5s. Hence is the question what the expected output is if snapshot is configured as such:

```
devices([
  "iPhone 5",
  "iPhone 5s",
])
```

Right now the screenshots are grouped all together as one 4" - which I think does not make much sense given that I defined 2 separate devices. IMO the focus is too much on implementation details of iTC.

**Comment by KrauseFx** [comment]
Hey @tcurdt, thanks for the suggestion, you can find the mapping here: https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/reports_generator.rb#L51-L64.
So this happens when you run `snapshot`? Would you mind submitting and testing a PR fixing this?

**Comment by tcurdt** [comment]
Sure can do. A simple fix should be to change the mapping to this

```
    def available_devices
      # The order IS important, since those names are used to check for include?
      # and the iPhone 6 is inlucded in the iPhone 6 Plus
      {
        'iPhone6sPlus' => "iPhone6sPlus (5.5-Inch)",
        'iPhone6Plus' => "iPhone6Plus (5.5-Inch)",
        'iPhone6s' => "iPhone6s (4.7-Inch)",
        'iPhone6' => "iPhone6 (4.7-Inch)",
        'iPhone5' => "iPhone5 (4-Inch)",
        'iPhone4' => "iPhone4 (3.5-Inch)",
        'iPadPro' => "iPad Pro",
        'iPad' => "iPad",
        'Mac' => "Mac"
      }
    end
```

Would that be acceptable?

**Comment by KrauseFx** [comment]
I'm not sure I'm following, how would that fix the issue?

**Comment by KrauseFx** [comment]
Did you test this locally?

**Comment by tcurdt** [comment]
@KrauseFx No, this is untested - but if you look at the code:

https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/reports_generator.rb#L13
https://github.com/fastlane/fastlane/blob/master/snapshot/lib/snapshot/page.html.erb#L77

it looks like the data passed into the ERB template is keyed by the `output_name`. So if those are the same they end up in the same `@data[language][output_name]`.  Which is the issue I was describing. So if you change the key to be unique per device they should show up as separate entries in the template.

Now one could either just change the mapping or change the code how the data is prepared for the template. I am wondering if there is any preference - and then I will test of course :)

**Comment by TKBurner** [comment]
@tcurdt Were you able to test locally ever? Definitely want to get this fixed 👍

**Comment by tcurdt** [comment]
Sorry for the delay. I can indeed confirm the [proposed change](https://github.com/fastlane/fastlane/issues/5502#issuecomment-236830706) works as expected.

It shows as:
```
de-DE
iPhone6 (4.7-Inch)
...
iPhone6s (4.7-Inch)
...
```

**Comment by TKBurner** [comment]
Awesome @tcurdt! Are you interested in submitting a PR for this?

Thanks!

**Comment by tcurdt** [comment]
@TKBurner sure can do.

**Comment by TKBurner** [comment]
@tcurdt Awesome! Thanks so much 👍 💯 💯

**Comment by tcurdt** [comment]
@TKBurner Please see the question in #5848 to get this merged.

**Comment by TKBurner** [comment]
@tcurdt Thanks for following up.  I don't see your question, but I'll make sure Felix follows up on your thread. Thanks!

**Comment by tcurdt** [comment]
@TKBurner all taken care of by now.

**Comment by tcurdt** [comment]
...just hoping for a merge ;)
