### ISSUE TITLE
pilot using wrong log in credentials for iTunes connect

### ISSUE THREAD

**Issue by mark5422** [fastlane/fastlane#551]
I have two separate projects that both use different iTunes connect logins. When using testflight/deliver the upload works just fine. When using pilot to try and do the same thing the upload fails stating that the log in credentials are wrong.

It seems like in the case of their being two deliver entries in the keychain that pilot is just pulling the first one it comes to and using that to try and log in. Because this is being done using Jenkins it’s preferable to not specify the password during the call to pilot.

One of the projects works fine and logs in Ok, the other does not. When only one project exists then that project worked Ok. Again this issue isn’t there when not using pilot.

-----

On a side note does pilot support the DELIVER_WHAT_TO_TEST and other associated TestFlight beta variables?

**Comment by lukkas** [comment]
Any update on that? I've just encountered similar issue.

**Comment by KrauseFx** [comment]
How and where do you specify the Apple ID to use?

**Comment by lukkas** [comment]
In environmental variables at the beginning. i.e. "bundle exec fastlane ios staging --env staging" Variable is PILOT_USERNAME.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
