### ISSUE TITLE
Deliver should sanity check screenshot/metadata language selections

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#5512]
### New Issue Checklist

- [Y ] Updated fastlane to the latest version
- [ Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

if there is a mismatch between the language folders in your screenshot directory, and your metadata directory, then deliver fails when it tries to upload screenshots for the problem directory.

e.g. 
Screenshot languages
da,el,fi,it,ja,ko
Metadata languages
da,el,fi,it,ja

deliver will upload the screenshots for all languages, then fail at the final hurdle 'ko' with 'language not activated'

If you're uploading 30 screenshots / language with 20 languages, then the failure may come after an hour or more of uploading.

A quick sanity check at the outset would allow deliver to fail much more quickly.

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.98.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm

**Comment by TKBurner** [comment]
@ConfusedVorlon Thanks for reaching out about this. Are you interested in submitting a PR to correct this? The team would love it! Thanks 👍

**Comment by ConfusedVorlon** [comment]
nope - I'm done with PRs. I'll keep myself to comments and suggestions for now.

**Comment by TKBurner** [comment]
Thanks for letting me know @ConfusedVorlon. I'll leave this open with the help wanted flag for now. Thanks!
