### ISSUE TITLE
[fastlane-plugin] proposal of android integration-tests emulator run plugin update

### ISSUE THREAD

**Issue by FisherKK** [fastlane/fastlane#5513]
I would like to submit plugin for Fastlane, dedicated for Android platform.

Description:

> Plugin dedicated for Android platform. Wraps gradle task/shell command used for launching instrumented tests. Provides start of single AVD before test run, waits for boot, kills emulator and deletes from hdd after tests are finished or disturbed.

Plugin git:

https://github.com/AzimoLabs/fastlane-plugin-automated-test-emulator-run

I am aware that such plugin already existed within fastlane repo and was provided by joshrlesch:

https://github.com/fastlane/fastlane/compare/master...joshrlesch:fastlane-instrument-tests

I used joshrlesch plugin as base to my work. Because of that I have left joshrlesch as main author of this plugin and added my nickname as contributor/person that have modified already provided solution.

What my changes has to offer?

1. Every functionality of plugin fastlane-instrument-tests has been kept.
2. Added new optional run parameter named "initdata_snapshot_path". It allows user to point at direction of AVD image so it will be loaded as initial state of freshly created by script emulator. (e.g. you can save image of AVD with turned off animations, stay awake, or turned on fingerprint if your tests are going to work with that function)
3. Added new optional run parameter named "shell_command". Previously script allowed user only to run tests by gradle task. Now you can also run tests from shell (e.g. you can use spoon or rely on other fastlane lanes)
4. Changed the way emulator session is handled. At start of script temp file was created for output of emulator. Port on which emulator stands was read by regex and string matching inside this tempfile. Problem is, that for example on my PC that string never appeared and script was always using default port 5554. I have changed that so I iterate over 5554 - 5586 ports and check if any of them is free. Then I chose first one and start emulator on it. I save port in variable at start of script run.
5. Waiting for emulator boot was bugged. It was checking if ANY emulator in the system was already booted. So if I had already my emulator-5554 running in the system, run of script caused creation of new emulator, started emulator-5556, wait for emulator boot instantly quit wait loop as emulator-5554 was already ready to run tests (emulator-5556 is booting at that moment), tests started on emulator-5554, emulator-5556 booted and nothing happens, script kills emulator-5554 and deletes from hdd emulator-5556. It was fixed by creating emulator session in point 4. Now every check is done only on port that was picked on script start. (even if you have other device running in your system it will still wait for the emulator created/launched by plugin)
6. Waiting for emulator stop was bugged. To kill process - port was needed. Previous script never found right port on which my emulator was currently working. (it was looking for string which never appeared on my PC - in created tempfile) Consequently it was always using default port 5554. It was fixed by creating emulator session in point 4. Now at start of script port is being picked and every process kill is done on that port. 
7. Changed SDK path. Previously script tried to use SDK root specified in environment variable called SDK_PATH. Problem is neither me or my colleagues have such environment variable. Usually after installing IDE (e.g. Android Studio), SDK is saved in environment variable PATH by default. I have added method that iterates over directories saved in PATH variable and then finds SDK root dir.
8. Deleted deprecated classes. In previous script some of logs were performed by Helper class. Now everything uses UI.message.
9. More output to terminal.

**Comment by TKBurner** [comment]
Hi @FisherKK thanks for reaching out. You can publish your plugin on your own using the steps here, https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins. You should maybe reach out to @joshrlesch or at least make sure to credit them in your gem.

Hope you have a great day! 👍

**Comment by joshrlesch** [comment]
@FisherKK Im glad my action is of use to people. I was away for awhile on paternity leave and vacation so didn't get the plugin created after my original pr was closed https://github.com/fastlane/fastlane/pull/4315#issuecomment-235558774
You can see I was working to get the current PR transfer back to me. I also have some changes/improvements to make with it. Maybe instead of creating yet another plugin, you open a PR once it gets transfer back to me.

**Comment by TKBurner** [comment]
@FisherKK @joshrlesch Really glad you two were able to connect!

**Comment by joshrlesch** [comment]
@FisherKK feel free to open a PR for your changes https://github.com/joshrlesch/fastlane-plugin-instrumented_tests
