### ISSUE TITLE
[Match] Distribution Certificate Adhoc != Appstore

### ISSUE THREAD

**Issue by DouglasHennrich** [fastlane/fastlane#5521]
When I run `match adhoc` it tried to create a new distribution certificate, but I already have one distribution certificate on that git repo, but I create it with `match appstore`... since it's the same certificate(distribution) it shouldn't create a new one... on this case, I will have to have 2 distribution cert on my keychain and on my apple developer portal

**Comment by TKBurner** [comment]
Hi @DouglasHennrich Thanks for reaching out. This is expected behavior. Is there a reason you need to run match adhoc specifically if it's the same as your other cert? Thanks!

**Comment by DouglasHennrich** [comment]
I'm running `match adhoc` to get adhoc's provisioning and distribution cert because I need to build it deploy it to Installrapp.com

So I have both provisionings(`appstore` and `adhoc` )

**Comment by TKBurner** [comment]
Hi @DouglasHennrich Are you able to use the same cert for both through Xcode? Thanks!

**Comment by DouglasHennrich** [comment]
Hi @TKBurner I'm facing problems because when I run match adhoc, it created a new cert and create the provisioning with that cert signed... now I have two distribution cert on my keychain and this confuse me when I build for adhoc or appstore... I don't know which cert were assigned with the provisioning
