### ISSUE TITLE
Fastlane With Jenkins

### ISSUE THREAD

**Issue by dgoyaldiksha** [fastlane/fastlane#5534]
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### For making the build automated,am using fastlane with jenkins,Can i know the steps to execute that.

Is this possible that when the user push the code to github all the fastlane commands start executing when user press build now button in jenkins.i have tried pilot upload command,which works fine,but i have to make the ipa through terminal and then upload the build to github and then build is uploaded to testflight after pressing the build now button.So it is possible to make fastfile and all the things when the buildnow is pressed in jenkins.

**Comment by CurlyHeir** [comment]
Start with Fastfile, and create lanes, then try use Gym tool to build IPA, sending your file to github can be done with fastlane git plugin and 

Fastfile
```ruby
lane :your_lane do 
  gym 
  git_commit // you will have to search how to do it
  pilot
end
```
seems to be easy, right? : )

**Comment by dgoyaldiksha** [comment]
@CurlyHeir Thanks for the response :) 

Is this possible that if the person just uploads a project to the github without any fastfile or any fastlane component in it and all the lanes or fastline would generate when buildnow in jenkins is triggered by writing down all the commands in execute shell.

**Comment by CurlyHeir** [comment]
YES, 
you can use shell in jenkins and write each command, passing all parameters. 
you don't really have to declare lanes in Fastfile (but that apporoarch is rather poinless)
