### ISSUE TITLE
Fastlane official plugin for running tests on multiple simulators / devices in the same time

### ISSUE THREAD

**Issue by CurlyHeir** [fastlane/fastlane#5535]
### Fastlane oficial plugin for running unit and integration tests with KIF on iOS simulators and devices
- [x] I have read the [Contribution Guidelines]

### Issue Description

Hi, can we add plugin to support running tests on multiple devices / simulators in the same time? 
I'd be convenient to run all tests on few devices or run part of tests on each device to get info ASAP.

### Technical requirements 
For now running tests in parallel is possible with XCTOOL, but this tool is avoided in fastlane, but with Xcode 8.0 Apple released some  flags for xcodebuild / xcrun to run tests without building or just build test target. For now those flags really don't work  for parallel but it'd be nice if they will fix this. 

### Example solutions 
I forked Johannes Pluniens repo and made some improvements [repo link](https://github.com/CurlyHeir/parallel_ios_tests),  it works with example but simulators hangs when runned pretty big one app on 3 simulators in the same time - however - it's possible to make it working! :) 

### Roadmap
- tests shredding 
- integration tests run on many devices at once
- scalability and free solution for creating own testing cloud
- integration with Scan

What do you think about this?

**Comment by KrauseFx** [comment]
Hey @CurlyHeir, you're more than welcome to build your fastlane plugin for that 👍 It seems like a complex problem you tackle, so it might take some time to implement it. 
You can also use `xctool` from fastlane btw 👍

**Comment by CurlyHeir** [comment]
@KrauseFx using `xctool` is pointless now, there is no support for XCode 8.
For now i finished feature that allows to run tests on many devices in parallel ^^,  it run tests in infinity loop due do bug in `xcodebuild`, but i hope it will be solved.

There is still huge problem with simulators and i have to figure out how to hack `xcodebuild`.
