### ISSUE TITLE
[pilot] Adding internal testers

### ISSUE THREAD

**Issue by pj4533** [fastlane/fastlane#5539]
Can you add internal testers with Pilot?  If so, how?

`pilot --help` specifies external testers, and `pilot add <email>` doesn't seem to work.

See also:

https://github.com/fastlane/fastlane/issues/4753

**Comment by TKBurner** [comment]
Hi @pj4533 Thanks for reaching out. Right now it's not possible to do this through `pilot`

I'm going to mark this as a feature request and see if anyone from the community wants to submit a PR. Thanks!

**Comment by pj4533** [comment]
Thanks @TKBurner       This is fairly key to my workflow, so I might take a look into it myself.  If anyone has any tips on where to start, i'm all ears!  👂

**Comment by pj4533** [comment]
I looked into this and it is beyond my scope of understanding for now.  I started by just trying to do this in a custom action, going right to Spaceship.  The main issues:

## Getting a 'forbidden' error 

When doing a `find` for an internal tester like this:
```
        testermanager = Pilot::TesterManager.new
        pilotoptions = {
          app_identifier: params[:app_identifier],
          dev_portal_team_id: params[:dev_portal_team_id],
          team_id: "#{params[:team_id]}",
          email: "ios@evertrue.com"
        }
        config = FastlaneCore::Configuration.create(Pilot::Options.available_options, pilotoptions)
        testermanager.start(config)

        email = "ios@evertrue.com"
        tester = Spaceship::Tunes::Tester::Internal.find(email)
        if tester
        	UI.success("Existing tester #{email}")
        else
	        Spaceship::Tunes::Tester::Internal.create!(
	        	email: "ios@evertrue.com",
				first_name: "Paul",
				last_name: "Gray"
			)
			UI.success("Successfully added internal tester: #{email}")
        end
```

The `find` line gets the forbidden, likely somewhat related to this issue:
https://github.com/fastlane/fastlane/issues/1895    The tunes user in question is an 'app manager' and can add testers via the web, but maybe the find is hitting an endpoint that is admin only?

## Action not provided for this tester type

So I commented out the 'find' and just assumed that the tester wasn't added yet.  Essentially, just doing this line:

```
	        Spaceship::Tunes::Tester::Internal.create!(
	        	email: "ios@evertrue.com",
				first_name: "Paul",
				last_name: "Gray"
			)
```

But that triggers a `Action not provided for this tester type`, so i am guessing it is pretty deep in Spaceship that adding of internal testers isn't supported.

Anyway, I hope this helps someone willing to dive in deeper!

**Comment by jaleksynas** [comment]
The main issue here is that Internal testers are not just arbitrary email addresses... they are actually ITC accounts. 

"Up to 25 iTunes Connect users with the Admin, App Manager, Developer, Marketer or Legal role can be added as internal testers."

This is also why `create!` action is not supported on `InternalTester` as that would imply creation of an ITC account.  It may be possible to find/filter the list and select and assign the one specified. Probably something better done with spaceship.  

The Forbidden error (during find) is due to the fact that internal testers (when no 'app_id' is specified) is selected from a very high level endpoint that requires Admin level access.  Try using the `def find_by_app(app_id, identifier)` -- it doesn't necessarily filter the list, but will return.

**Comment by KrauseFx** [comment]
Thanks for jumping in @jaleksynas 👍 We don't plan on supporting creating internal testers.

**Comment by pj4533** [comment]
I totally understand that.  If the users email isn't already an ITC user, that presents a problem.  

But what about the case where they are?  For example, I ship apps under several different teams.  I know my email is an admin on the dev team, and an App Manager on ITC.  I can automate every other aspect of the process, but in order to get TestFlight builds I have to go to ITC and add my email to the internal testers, manually.

If the email in question isn't a current ITC user, I think it's a valid error case that wouldn't be supported.  But if they are, as you say, it should be possible with spaceship, right?

**Comment by KrauseFx** [comment]
@pj4533 couldn't you add yourself as external tester too?

**Comment by pj4533** [comment]
@KrauseFx    I could...but then I'd have to wait 24hrs+ for external approval.  This is all part of a automated system of shipping apps, so the faster it is the better.   The goal is to:

1.  `be fastlane verify` (sets up Xcode project, uses match for signing, builds app, delivers to TestFlight)
2.  Download app via TestFlight, and verify app on your phone as 'ready to ship'
3.  `be fastlane submit`  (delivers previously uploaded bits to store for approval)

But now our process is:

1. Manually add ourself as an internal test flight tester
2. (above 3 steps)

Not horrible, only one trip to iTunes connect on the web is way better than pre-Fastlane, but still...its so close to being fully automated!!! 

I have done lots of custom work in our lanes & actions for our process, so I am somewhat comfortable going directly to Spaceship, but I couldn't figure this one out.  Any help would be appreciated.  Not sure what @jaleksynas meant by "It may be possible to find/filter the list and select and assign the one specified."
