### ISSUE TITLE
Fastlane Deliver will not submit to the App Store

### ISSUE THREAD

**Issue by la5487** [fastlane/fastlane#5542]
### New Issue Checklist
- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Fastlane Deliver says the app was submitted, but its still in "Prepare for submission".

From looking around at others who have this issue, it looks like there is a problem when "add_id_info_uses_idfa" is set to true. When I go to iTunes connect to manually submit the app, the only thing that is asked for is my idfa settings, when usually it would ask for both idfa and export compliance. So it seems that the export compliance settings were successfully passed, and something about the idfa settings are failing. 

I'm resurrecting this issue from #1550 , which was recently closed but had many people experiencing the same problem, with no solutions.
##### Complete output when running fastlane, including the stack trace and command used

```
[19:23:46]: You can tweet: "iTunes Connect #iosprocessingtime 34 minutes"
[19:24:18]: Selecting build 4.0.2 (161)...
[19:24:21]: Successfully selected build
[19:24:21]: Submitting the app for review...
[19:24:39]: Setting 'export_compliance_available_on_french_store' to 'false'...
[19:24:39]: Setting 'export_compliance_contains_proprietary_cryptography' to 'false'...
[19:24:39]: Setting 'export_compliance_contains_third_party_cryptography' to 'false'...
[19:24:39]: Setting 'export_compliance_is_exempt' to 'false'...
[19:24:39]: Setting 'export_compliance_uses_encryption' to 'false'...
[19:24:39]: Setting 'export_compliance_app_type' to ''...
[19:24:39]: Setting 'export_compliance_encryption_updated' to 'false'...
[19:24:39]: Setting 'export_compliance_compliance_required' to 'false'...
[19:24:39]: Setting 'export_compliance_platform' to 'ios'...
[19:24:39]: Setting 'content_rights_contains_third_party_content' to 'false'...
[19:24:39]: Setting 'content_rights_has_rights' to 'false'...
[19:24:39]: Setting 'add_id_info_limits_tracking' to 'false'...
[19:24:39]: Setting 'add_id_info_serves_ads' to 'false'...
[19:24:39]: Setting 'add_id_info_tracks_action' to 'true'...
[19:24:39]: Setting 'add_id_info_tracks_install' to 'true'...
[19:24:39]: Setting 'add_id_info_uses_idfa' to 'true'...
[19:24:41]: Successfully submitted the app for review!
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
    deliver(
      ipa: "./MyApp.ipa",
      metadata_path: "./fastlane/metadata"
    )
```

Deliverfile:

``` ruby
app_identifier "com.myapp.MyApp" # The bundle identifier of your app
username "me@myemail.com" # your Apple ID user
submit_for_review true
force true
automatic_release false

submission_information({

  export_compliance_available_on_french_store: "false",
  export_compliance_contains_proprietary_cryptography: "false",
  export_compliance_contains_third_party_cryptography: "false",
  export_compliance_is_exempt: "false",
  export_compliance_uses_encryption: "false",
  export_compliance_app_type: nil,
  export_compliance_encryption_updated: "false",
  export_compliance_compliance_required: "false",
  export_compliance_platform: "ios",
  content_rights_contains_third_party_content: "false",
  content_rights_has_rights: "false",
  add_id_info_limits_tracking: "false",
  add_id_info_serves_ads: "false",
  add_id_info_tracks_action: "true",
  add_id_info_tracks_install: "true",
  add_id_info_uses_idfa: "true"
});
```
### Environment

fastlane version (run `fastlane -v`): 

fastlane 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

no

**Comment by vpolouchkine** [comment]
Are you able to repro this in a separate project?

**Comment by ramirantala** [comment]
It seems we have same/similar issue. Everything looks ok, but the app is not submitted for review. When we do it from itc, only thing that is asked is itc.

**Comment by TKBurner** [comment]
@ramirantala Can you add the --verbose flag and share your full input and output. I'd like to look into this. Thanks!

**Comment by ramirantala** [comment]
Verbose does not help much..

INFO [2016-09-09 17:22:31.86]: Making sure the latest version on iTunes Connect matches '1.0.0' from the ipa file...
INFO [2016-09-09 17:22:35.91]: Successfully set the version to '1.0.0'
INFO [2016-09-09 17:22:35.91]: Loading './fastlane/metadata/de-DE/description.txt'...
INFO [2016-09-09 17:22:35.91]: Loading './fastlane/metadata/de-DE/keywords.txt'...
INFO [2016-09-09 17:22:35.91]: Loading './fastlane/metadata/de-DE/release_notes.txt'...
INFO [2016-09-09 17:22:35.91]: Loading './fastlane/metadata/de-DE/support_url.txt'...
INFO [2016-09-09 17:22:35.91]: Loading './fastlane/metadata/de-DE/marketing_url.txt'...
INFO [2016-09-09 17:22:35.91]: Loading './fastlane/metadata/de-DE/name.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/de-DE/privacy_url.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/copyright.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/primary_category.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/secondary_category.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/primary_first_sub_category.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/primary_second_sub_category.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/secondary_first_sub_category.txt'...
INFO [2016-09-09 17:22:35.92]: Loading './fastlane/metadata/secondary_second_sub_category.txt'...
WARN [2016-09-09 17:22:35.92]: Verifying the upload via the HTML file can be disabled by either adding
WARN [2016-09-09 17:22:35.92]: `force true` to your Deliverfile or using `deliver --force`
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
INFO [2016-09-09 17:23:11.86]: HTML file confirmed...
INFO [2016-09-09 17:23:14.14]: Activating language de-DE...
INFO [2016-09-09 17:23:17.85]: Uploading metadata to iTunes Connect
INFO [2016-09-09 17:23:20.01]: Successfully uploaded initial set of metadata to iTunes Connect
INFO [2016-09-09 17:23:23.62]: Finished the upload to iTunes Connect
INFO [2016-09-09 17:23:25.60]: Selecting the latest build...
INFO [2016-09-09 17:23:28.05]: Selecting build 2.5.0 (123500)...
INFO [2016-09-09 17:23:29.71]: Successfully selected build
INFO [2016-09-09 17:23:29.71]: Submitting the app for review...
INFO [2016-09-09 17:23:51.52]: Setting 'add_id_info_limits_tracking' to 'false'...
INFO [2016-09-09 17:23:51.52]: Setting 'add_id_info_serves_ads' to 'true'...
INFO [2016-09-09 17:23:51.53]: Setting 'add_id_info_tracks_action' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'add_id_info_tracks_install' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'add_id_info_uses_idfa' to 'true'...
INFO [2016-09-09 17:23:51.53]: Setting 'content_rights_has_rights' to 'true'...
INFO [2016-09-09 17:23:51.53]: Setting 'content_rights_contains_third_party_content' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_platform' to 'ios'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_compliance_required' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_encryption_updated' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_app_type' to ''...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_uses_encryption' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_is_exempt' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_contains_third_party_cryptography' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_contains_proprietary_cryptography' to 'false'...
INFO [2016-09-09 17:23:51.53]: Setting 'export_compliance_available_on_french_store' to 'false'...
INFO [2016-09-09 17:23:53.77]: Successfully submitted the app for review!

..but after this it is not in review.

**Comment by TKBurner** [comment]
Hi @ramirantala Can you print out the summary of inputs into deliver that prints before this? I'd love to have a look. Thanks!

**Comment by ramirantala** [comment]
| automatic_release                                                          | false               |
| skip_binary_upload                                                         | true                |
| skip_screenshots                                                           | true                |
| build_number                                                               | latest              |
| submit_for_review                                                          | true                |
| release_notes.de-DE                                                        |  neu    |
| submission_information.add_id_info_limits_tracking                         | false               |
| submission_information.add_id_info_serves_ads                              | true                |
| submission_information.add_id_info_tracks_action                           | false               |
| submission_information.add_id_info_tracks_install                          | false               |
| submission_information.add_id_info_uses_idfa                               | true                |
| submission_information.content_rights_has_rights                           | true                |
| submission_information.content_rights_contains_third_party_content         | false               |
| submission_information.export_compliance_platform                          | ios                 |
| submission_information.export_compliance_compliance_required               | false               |
| submission_information.export_compliance_encryption_updated                | false               |
| submission_information.export_compliance_uses_encryption                   | false               |
| submission_information.export_compliance_is_exempt                         | false               |
| submission_information.export_compliance_contains_third_party_cryptography | false               |
| submission_information.export_compliance_contains_proprietary_cryptography | false               |
| submission_information.export_compliance_available_on_french_store         | false               |
| screenshots_path                                                           | ./fastlane/scree... |
| metadata_path                                                              | ./fastlane/metadata |
| app_version                                                                | 1.0.0               |
| ipa                                                                        | CI.ipa        |
| skip_metadata                                                              | false               |
| force                                                                      | false               |

I've removed account related lines - like username, team and appid. 

Which submission information parameters are mandatory? @TKBurner

**Comment by TKBurner** [comment]
@ramirantala Nothing looks odd there. Can you provide exact repro steps using a blank project? I want to circle in the core team. Thanks!

**Comment by iv-mexx** [comment]
I'm facing the same problem. 
Maybe it has something to do with the fact that we're using the IDFA. 
When submitting by hand in iTunesConnect, theres an extra Checkbox where I have to confirm that the App uses the IDFA only in the described way.
See the very last screenshot [here in the Apple Documentation](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/SubmittingTheApp.html)

Not sure what the correct flag for that is, maybe its `add_id_info_limits_tracking`?
If so, then I think that needs to be set to `true`. Unfortunately, this occurred to me just after I've submitted the current update by hand so I cant test right now. 

I will test this when we're submitting the next update.

**Comment by hjanuschka** [comment]
we are using IDFA too - and with following `submission_info`  a submit works
my pitfall was the missing `export_compliance_available_on_french_store` and missing `app_review_infomation`


```ruby
deliver(
    app_review_information: {
     first_name: 'Helmut',
      last_name: 'Januschka',
      phone_number: '+43 xxxx',
      email_address: 'helmut@januschka.com',
      demo_user: 'xxx',
      demo_password: 'xxx',
      notes: 'app should be usable even with no user'
   },
    submit_for_review: true,
    submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
  )
```

**Comment by MaximusMcCann** [comment]
Same thing... Still see 
![image](https://cloud.githubusercontent.com/assets/1643285/19824449/2a2832c0-9d35-11e6-8e38-f0205828e92b.png)


My Deliverfile

```
force true
skip_metadata true
skip_binary_upload true 
submit_for_review true
automatic_release true
submission_information({
  add_id_info_limits_tracking: false,
  add_id_info_serves_ads: false,
  add_id_info_tracks_action: true,
  add_id_info_tracks_install: true,
  add_id_info_uses_idfa: true,
  content_rights_has_rights: false,
  content_rights_contains_third_party_content: false,
  export_compliance_platform: 'ios',
  export_compliance_compliance_required: false,
  export_compliance_encryption_updated: false,
  export_compliance_app_type: nil,
  export_compliance_uses_encryption: false,
  export_compliance_is_exempt: false,
  export_compliance_contains_third_party_cryptography: false,
  export_compliance_contains_proprietary_cryptography: false,
  export_compliance_available_on_french_store: false
})
```



### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

##### Complete output when running fastlane, including the stack trace and command used

```
[17:12:42]: Making sure the latest version on iTunes Connect matches '1.9.0' from the ipa file...
[17:12:44]: '1.9.0' is the latest version on iTunes Connect
[17:12:44]: Starting with the upload of screenshots...
[17:12:44]: Successfully uploaded screenshots to iTunes Connect
[17:12:46]: Finished the upload to iTunes Connect
[17:12:47]: Selecting the latest build...
[17:12:49]: Selecting build 1.9.0 (842)...
[17:12:50]: Successfully selected build
[17:12:50]: Submitting the app for review...
[17:13:17]: Setting 'add_id_info_limits_tracking' to 'false'...
[17:13:17]: Setting 'add_id_info_serves_ads' to 'false'...
[17:13:17]: Setting 'add_id_info_tracks_action' to 'true'...
[17:13:17]: Setting 'add_id_info_tracks_install' to 'true'...
[17:13:17]: Setting 'add_id_info_uses_idfa' to 'true'...
[17:13:17]: Setting 'content_rights_has_rights' to 'false'...
[17:13:17]: Setting 'content_rights_contains_third_party_content' to 'false'...
[17:13:17]: Setting 'export_compliance_platform' to 'ios'...
[17:13:17]: Setting 'export_compliance_compliance_required' to 'false'...
[17:13:17]: Setting 'export_compliance_encryption_updated' to 'false'...
[17:13:17]: Setting 'export_compliance_app_type' to ''...
[17:13:17]: Setting 'export_compliance_uses_encryption' to 'false'...
[17:13:17]: Setting 'export_compliance_is_exempt' to 'false'...
[17:13:17]: Setting 'export_compliance_contains_third_party_cryptography' to 'false'...
[17:13:17]: Setting 'export_compliance_contains_proprietary_cryptography' to 'false'...
[17:13:17]: Setting 'export_compliance_available_on_french_store' to 'false'...
[17:13:18]: Successfully submitted the app for review!
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.4.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.53.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.0       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.2        |
| molinillo                 | 0.4.5        |
| nanaimo                   | 0.1.1        |
| xcodeproj                 | 1.4.0        |
| cocoapods                 | 1.0.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types                | 2.99.3       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.19       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.8        |
| rest-client               | 1.8.0        |
</details>

**Comment by TKBurner** [comment]
@MaximusMcCann Thanks for following up. What happens if you move your deliver parameters to the fastfile instead of the deliver file? Thanks!

**Comment by hjanuschka** [comment]
@MaximusMcCann have you tried providing: `app_review_information` as in my comment above?

**Comment by MaximusMcCann** [comment]
Same issue :(.  Everything is up-to-date. But Submit for Review button is still available as the app didn't actually submit.

Output:

```
[18:34:40]: ---------------------
[18:34:40]: --- Step: deliver ---
[18:34:40]: ---------------------
[18:34:40]: Successfully loaded '/Users/aa/CODE/ios-swift3/ios/fastlane/Deliverfile' 📄

+------------------------+---------------------------------------------+
|            Detected Values from './fastlane/Deliverfile'             |
+------------------------+---------------------------------------------+
| copyright              | © 2016. All rights reserved. |
| app_review_information |                                             |
| force                  | true                                        |
| skip_metadata          | true                                        |
| skip_binary_upload     | true                                        |
| submit_for_review      | true                                        |
| automatic_release      | true                                        |
| submission_information |                                             |
+------------------------+---------------------------------------------+

[18:34:40]: Login to iTunes Connect (aa@aa.com)
[18:34:44]: Login successful

+----------------------------------------------------------------------------+---------------------+
|                                      deliver 1.16.1 Summary                                      |
+----------------------------------------------------------------------------+---------------------+
| app_version                                                                | 2.1.0               |
| release_notes.default                                                      | UI Cleans           |
| release_notes.en-US                                                        | UI Cleans           |
| copyright                                                                  | © 2016... |
| app_review_information.first_name                                          | aa             |
| app_review_information.last_name                                           | aa              |
| app_review_information.phone_number                                        | aa          |
| app_review_information.email_address                                       | aa@aa... |
| app_review_information.demo_user                                           | aa@aa.com    |
| app_review_information.demo_password                                       | *******            |
| app_review_information.notes                                               | See Whats New       |
| force                                                                      | true                |
| skip_metadata                                                              | true                |
| skip_binary_upload                                                         | true                |
| submit_for_review                                                          | true                |
| automatic_release                                                          | true                |
| submission_information.add_id_info_limits_tracking                         | false               |
| submission_information.add_id_info_serves_ads                              | false               |
| submission_information.add_id_info_tracks_action                           | true                |
| submission_information.add_id_info_tracks_install                          | true                |
| submission_information.add_id_info_uses_idfa                               | true                |
| submission_information.content_rights_has_rights                           | false               |
| submission_information.content_rights_contains_third_party_content         | false               |
| submission_information.export_compliance_platform                          | ios                 |
| submission_information.export_compliance_compliance_required               | false               |
| submission_information.export_compliance_encryption_updated                | false               |
| submission_information.export_compliance_uses_encryption                   | false               |
| submission_information.export_compliance_is_exempt                         | false               |
| submission_information.export_compliance_contains_third_party_cryptography | false               |
| submission_information.export_compliance_contains_proprietary_cryptography | false               |
| submission_information.export_compliance_available_on_french_store         | false               |
| screenshots_path                                                           | ./fastlane/scree... |
| metadata_path                                                              | ./fastlane/metadata |
| username                                                                   | aa@aa.com  |
| app_identifier                                                             | aa.aa.cl... |
| ipa                                                                        | aa.ipa          |
| platform                                                                   | ios                 |
| skip_screenshots                                                           | false               |
| dev_portal_team_id                                                         | aa          |
| overwrite_screenshots                                                      | false               |
+----------------------------------------------------------------------------+---------------------+

[18:34:46]: Making sure the latest version on iTunes Connect matches '2.1.0' from the ipa file...
[18:34:47]: '2.1.0' is the latest version on iTunes Connect
[18:34:47]: Detected languages: ["default", "en-US"]
[18:34:49]: Starting with the upload of screenshots...
[18:34:49]: Successfully uploaded screenshots to iTunes Connect
[18:34:51]: Finished the upload to iTunes Connect
[18:34:52]: Selecting the latest build...
[18:34:55]: Selecting build 2.1.0 (963)...
[18:34:56]: Successfully selected build
[18:34:56]: Submitting the app for review...
[18:35:20]: Setting 'add_id_info_limits_tracking' to 'false'...
[18:35:20]: Setting 'add_id_info_serves_ads' to 'false'...
[18:35:20]: Setting 'add_id_info_tracks_action' to 'true'...
[18:35:20]: Setting 'add_id_info_tracks_install' to 'true'...
[18:35:20]: Setting 'add_id_info_uses_idfa' to 'true'...
[18:35:20]: Setting 'content_rights_has_rights' to 'false'...
[18:35:20]: Setting 'content_rights_contains_third_party_content' to 'false'...
[18:35:20]: Setting 'export_compliance_platform' to 'ios'...
[18:35:20]: Setting 'export_compliance_compliance_required' to 'false'...
[18:35:20]: Setting 'export_compliance_encryption_updated' to 'false'...
[18:35:20]: Setting 'export_compliance_app_type' to ''...
[18:35:20]: Setting 'export_compliance_uses_encryption' to 'false'...
[18:35:20]: Setting 'export_compliance_is_exempt' to 'false'...
[18:35:20]: Setting 'export_compliance_contains_third_party_cryptography' to 'false'...
[18:35:20]: Setting 'export_compliance_contains_proprietary_cryptography' to 'false'...
[18:35:20]: Setting 'export_compliance_available_on_french_store' to 'false'...
[18:35:23]: Successfully submitted the app for review!
[18:35:23]: -------------------
[18:35:23]: --- Step: slack ---
[18:35:23]: -------------------
[18:35:23]: Successfully sent Slack notification

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | update_fastlane            | 2           |
| 2    | default_platform           | 0           |
| 3    | xcversion                  | 0           |
| 4    | ensure_git_branch          | 0           |
| 5    | get_version_number         | 0           |
| 6    | changelog_from_git_commits | 0           |
| 7    | add_git_tag                | 0           |
| 8    | push_git_tags              | 1           |
| 9    | deliver                    | 42          |
| 10   | slack                      | 0           |
+------+----------------------------+-------------+

[18:35:23]: fastlane.tools finished successfully 🎉
```

**Comment by hjanuschka** [comment]
@MaximusMcCann  double check the phone number, i think apple forced the `+` some time ago.
in generall - you should run deliver. and if it does not work, do it once by hand via itunesconnect, if there is some sort of validation error, you'll see it in itunesconnect.

hope that helps!

**Comment by MaximusMcCann** [comment]
@hjanuschka Just tried with the updated phone number as `+1 xxxxxxxxx`.  Also tried w/out the space.  No luck :/  Still seeing the blue 'Submit for Review' btn.

Appreciate the help though!

**Comment by MaximusMcCann** [comment]
Just found it!  Had to set `submission_information.add_id_info_limits_tracking` = `true`
Didn't realize that was the check box on the actual web page.

**Comment by hjanuschka** [comment]
@MaximusMcCann awesome thx - for letting me know!

@TKBurner can we close this issue - as i think it is resolved, and the initial creatore has not replied for ages. (just for notification noise) - if some of you guys still expierence a problem please open a seperate issue.
