### ISSUE TITLE
Problem with multiple targets

### ISSUE THREAD

**Issue by Urkman** [fastlane/fastlane#5543]
### New Issue Checklist

- [ y] Updated fastlane to the latest version
- [ y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

My project has two targets (iOS and tvOS). I used the iOS most oft the time, and everything was fine..
But three days ago a build a new tvOS version (2.2 with build 63). There were some errors, but the build arrived in iTunes connect.

Now I want to build a new iOS Version (3.2 build 69)...

Now he always want to upload the 2.2 build 63 from the tvOS build :(

##### Complete output when running fastlane, including the stack trace and command used

[10:15:45]: [Transporter Error Output]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '63' for version '2.2'"
[10:15:45]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '63' for version '2.2'"
[10:15:45]: You have to change the build number of your app to upload your ipa file
[10:15:45]: Transporter transfer failed.
[10:15:45]:
[10:15:45]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '63' for version '2.2'"
[10:15:45]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '63' for version '2.2'"
Return status of iTunes Transporter was 1: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '63' for version '2.2'"
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "slack_url"
    cocoapods

  end

  lane :beta do

	increment_build_number()

    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "ios-target") # Build your app - more options available
    pilot(distribute_external: true,
		changelog: 'description'
    )
  end

  lane :beta_apple_tv do

	increment_build_number()

    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "apple-tv-target") # Build your app - more options available
    pilot(distribute_external: true,
		changelog: 'description'
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot

    gym(scheme: "ios-target") # Build your app - more options available
    deliver(force: true)
  end

  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(
      message: "Successfully deployed new App Update."
    )
  end
end
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by vpolouchkine** [comment]
Can you examine the ipa and confirm that it builds the correct target?
