### ISSUE TITLE
Is there any way to asynchronously or concurrently run actions from Fastfile?

### ISSUE THREAD

**Issue by objectmethod** [fastlane/fastlane#5544]
For example:

Our `pod install` command takes about 30 seconds to run, and our `carthage bootstrap` command takes 90 seconds.

There really is no reason for them to wait for one another to finish executing.  They could execute simultaneously.

Is there any way via Fastlane to execute these actions simultaneously within a single lane?

**Comment by CurlyHeir** [comment]
i never tried, but you can try with threads
try something like: 
```ruby
threads = []
commands = ['pod install', 'carthage bootstrap']
commands.each do |command| 
  threads << Thread.new do
  system "#{command}" #idk, probably you will have to add " before and after command
  Thread.current[:result] = $? 
  end
end 
# Wait for all threads to finish
threads.each do |thread|
  thread.join
  exit_code |= thread[:result].to_i
end
```

**Comment by KrauseFx** [comment]
Yeah, you can use basic Ruby threading for that, however fastlane was not built for that. Use it at your own risk. I personally wouldn't recommend doing it, but you're free to use Ruby threading 👍
