### ISSUE TITLE
(feat/actions): Add new action 'check if the given git tag exists in the repo or not'

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#5554]
🔑
Hi there, in my current "fastflow" I have to check whether the given tag exists or not and perform actions based on the result. So far I haven't found an action to do this and decided to write one.
I think it fits the rule of accepting new actions - `Generally usable for a big majority of developers (e.g. basic interactions with git)` and could be considered as basic interactions with git. 😉

**Comment by TKBurner** [comment]
@Antondomashnev Glad to see we merged your PR! Thanks again!
