### ISSUE TITLE
App Icon is uploaded, even when you want to skip

### ISSUE THREAD

**Issue by Luke-SF** [fastlane/fastlane#5564]
### Issue Description

When using deliver command to just submit some prepared apps, you can use --skip_metadata --skip_binary_upload --skip_screenshots --submit_for_review

While this mostly does what you would expect, if you happen to have an /images/ directory with an app icon in it, Deliver puts that app icon on every app it submits!

### Environment

fastlane version (run `fastlane -v`):
1.97.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by KrauseFx** [comment]
The only way to not upload the app icon is to not provide one to upload. Does that workaround work for you?

**Comment by programmin1** [comment]
Make sure an "images" folder is not in current directory when running it? Yeah, I guess, but it seems odd that there is --skip_binary_upload, --skip_screenshots, --skip_metadata, but none skip setting app icon image.
