### ISSUE TITLE
Connect match to project repo

### ISSUE THREAD

**Issue by chshapiro** [fastlane/fastlane#5565]
Is there a way to make a connection between the certificate repo and the project repo, so that when a developer pulls from the project repo, the certificates will automatically be updated/match will run?

**Comment by asfalcone** [comment]
@chshapiro Yep, when you configure `match` you'll generate a Matchfile that contains the `git_url` for the match repo 👍

**Comment by chshapiro** [comment]
So if I have a project called MyApp with a Git repo called MyApp, and in there is the Matchfile with the git_url for the match repo, when I pull from MyApp, my certificates/provisioning profiles will automatically be updated and I don't need to call match separately?

**Comment by asfalcone** [comment]
Ah I see now what you're asking. When you pull you want something to happen. You'd have to tie into git hooks I think to accomplish that.

If you include `match` in your Fastfile though, and do all of your building and deploying with `fastlane`, whenever certs and profiles are needed they should be retrieved correctly.
