### ISSUE TITLE
Script with errors with nonzero exit code causes gym to fail

### ISSUE THREAD

**Issue by fralways** [fastlane/fastlane#5578]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

--- Command /bin/sh emitted errors but did not return a nonzero exit code to indicate failure

I have custom script which gives this error when I upload app to the test flight. Upload is **successful** when uploading via xcode but when I run gym it does not complete. When I remove script, gym is completed.

##### Complete output when running fastlane, including the stack trace and command used

I'm not allowed to post whole output but notable part is:

```
[11:49:16]: ▸ Running script 'Run Script'
[11:49:17]: ▸ Touching XXXXX.app
[11:49:23]: ▸ Signing .../XXXXX.app
[11:49:24]: ▸ Touching XXXXX.app.dSYM
[11:49:25]: ▸ ** ARCHIVE FAILED **
Exit status: 65
```

### Configuration Files

There isn't anything of interest here since gym is used.

### Environment

fastlane version (run `fastlane -v`): fastlane 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by pedro380085** [comment]
Same error in here.

**Comment by KrauseFx** [comment]
There must be some more information about the error in the build error.

**Comment by pedro380085** [comment]
@KrauseFx Unfortunately no.... It's similar to: https://github.com/fastlane-old/gym/issues/113

I got the solution by changing the Xcode scheme to Release, building for my device and looking for the error log. Turns out Xcode just logged an warning where gym failed. It's due to a pngcrush misconfiguration.

All good 👍 . And thanks for the quick reply!

**Comment by fralways** [comment]
There is no more information - I rechecked and besides some warnings (ex. deprecated methods used) only ARHIVE FAILED is noted. I run with --verbose as well. End output is

/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/interface.rb:139:in `user_error!': [!] Error building the application - see the log above (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/error_handler.rb:53:in `handle_build_error'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/runner.rb:101:in `block in build_app'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.3/lib/fastlane_core/command_executor.rb:88:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.3/lib/fastlane_core/command_executor.rb:88:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/runner.rb:97:in `build_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/runner.rb:12:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/manager.rb:10:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/commands_generator.rb:42:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.3/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/commands_generator.rb:61:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/lib/gym/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.7.0/bin/gym:6:in `<top (required)>'
	from /usr/local/bin/gym:23:in `load'
	from /usr/local/bin/gym:23:in `<main>'

But I can tell you how to reproduce:
Try this framework : https://pspdfkit.com
Follow steps 1), 2) in getting started topic. Try gym.
