### ISSUE TITLE
fastlane ios analyze does not work

### ISSUE THREAD

**Issue by ankitgupta1309** [fastlane/fastlane#558]
@KrauseFx : I am attaching this screenshot. Everything works fine till 'fastlane test'. After that, it starts showing errors on commands. I am not able to understand how to go about taking the screenshots.

<img width="907" alt="screen shot 2015-09-02 at 1 18 09 pm" src="https://cloud.githubusercontent.com/assets/6194315/9625628/239f2fec-5175-11e5-95da-0ed734b92a79.png">

**Comment by KrauseFx** [comment]
Could you also share your `Fastfile`?

**Comment by ankitgupta1309** [comment]
I haven't made any changes to the *FastFile* as such.
<img width="754" alt="screen shot 2015-09-03 at 7 14 26 am" src="https://cloud.githubusercontent.com/assets/6194315/9648938/95902e58-520b-11e5-86cf-ec19c5fb92c9.png">
<img width="609" alt="screen shot 2015-09-03 at 7 14 40 am" src="https://cloud.githubusercontent.com/assets/6194315/9648939/959aaa40-520b-11e5-9306-1ee45169f7b6.png">

**Comment by Liquidsoul** [comment]
Hi @ankitgupta1309 

I think you may misunderstand how Fastlane works.
If you want to be able to call `fastlane ios analyse`, you need to have a lane `analyze` in the `platform :ios`section of your Fastfile. Something like this:
```ruby
lane :analyse do
  # xcodebuild analyze
end
```
However, as you can see in my code snippet, I am not aware of any direct command to execute `analyze` on a project from Fastlane. I think something can be done using the `xcodebuild` action to achieve that.

**Comment by KrauseFx** [comment]
Thanks for jumping in @Liquidsoul :+1:

**Comment by ohwutup** [comment]
going to close this issue for now because it has been inactive for quite a while. feel free to reopen if necessary!! :cat2:
