### ISSUE TITLE
Match certificate name

### ISSUE THREAD

**Issue by chshapiro** [fastlane/fastlane#5585]
When I run `match` and a certificate is generated, what determines what the name of the certificate will be? Is it based directly on the Apple account username/email? Can the name of the certificate be customized or is it just a default of the Apple account username?

**Comment by KrauseFx** [comment]
The name is consistent and cannot be customised. Why do you feel like changing the name?

**Comment by i-schuetz** [comment]
I would like to change the name because it has my name and since it's shared, it would be better if it has the company name?

**Comment by i-schuetz** [comment]
@KrauseFx I would like to change the name because it has my name and since it's shared, it would be better if it has the company name?

**Comment by TKBurner** [comment]
@i-schuetz Thanks for following up. We'll track this as a feature request.
