### ISSUE TITLE
Snapshot - Take screenshots manually not by record

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#5591]
The record process might by Ok in certain cases, but if  we need to take screenshots for each app from various locations (for example - each app has a different video movie) - how can we manually point the screenshot point, then the snapshot will do the same for all other simulators.
Is it possible?

**Comment by TKBurner** [comment]
@prolog3001 Thanks for reaching out. Right now you'd have to do that through Apple's UI tests, there isn't a mechanism of doing that through Snapshot. Thanks!
