### ISSUE TITLE
[match] invalid .p12 format?

### ISSUE THREAD

**Issue by morgondag** [fastlane/fastlane#5593]
trying to use one of the generate .p12 files generated with match.

`openssl pkcs12 -info -in NV6QMF9E9T.p12`
But when i try to validate the .p12 i get errors:

``` bash
17354:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.40.2/src/crypto/asn1/tasn_dec.c:1344:
17354:error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.40.2/src/crypto/asn1/tasn_dec.c:387:Type=PKCS12
```

I can't use the .p12 file in my keychain or in unity cloud builds.
**Failed to update credentials! This does not appear to be a valid .p12 file. Perhaps it's been corrupted.**

Are the generated .p12 file encrypted somehow and how do i generate a normal .p12 files from the encrypted .p12 files?

**Comment by mgrebenets** [comment]
I just configured `match` to share signing identity and profiles with the rest of the team few weeks ago. So my understanding may not be complete.

As far as I understand it atm, encrypting `.p12` files is the key feature of `match`. You can't even do an initial setup if you provide empty passphrase for encryption.

Have you tried the `match decrypt` subcommand? It says `Decrypts the repository and keeps it on the filesystem`, so you should be able to access unencrypted `.p12` after that.

**Comment by FodderMK** [comment]
I'm wondering if the issue could be related to https://github.com/fastlane/fastlane/issues/1805 , which I just banged my head against a little while ago.
