### ISSUE TITLE
[match/proposal] possible action to remove provision profiles locally

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#5601]
Hi there, this is more like a question or topic to discuss rather than an issue.

I'm using `match` to deal with code signing and found the repetitive scenario that I'm doing manually and it starts bothering me. But I'm not sure if I'm doing right and it makes sense at all so want to discuss it with the community.

Imagine the workflow:
1. We have clean machine and clean developer portal
2. We run `match` to create provision profiles and install it locally
3. Somebody adds a new device
4. Two possible ways:
* For me, if I run `match` it creates a new provision profiles and in the end, I have two provision profiles - one a new one and another the old one. And this exactly I don't like.
* To avoid this situation before running `match` I go to the `certificates repo`, remove all provision profiles that will be outdated, then remove the same provision profiles from the local machine and only then run `match`.

So my question: am I doing something wrong and match already can do it for me? If not, I've already created the custom action for `fastlane` and maybe we can think to integrate it into `match`.

Thanks 🚀

**Comment by KrauseFx** [comment]
It should be enough to just run `match(force: true)` to force a re-generation of the profile on each match run. Would that work for you?

**Comment by Antondomashnev** [comment]
@KrauseFx thanks, it is definitely better because it doesn't create a new provision profile now. But unfortunately I still have two provision profiles locally with the same name If I run it twice:
![example](https://api.monosnap.com/rpc/file/download?id=2CRsxlSmRAbPR0fTy115MCM8K5FEQ7)

**Comment by KrauseFx** [comment]
That's weird. If you set up your Xcode project according to [XcodeProject.md](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Codesigning/XcodeProject.md) `match` will automatically pass the UDID of the provisioning profile to `xcodebuild`, so you don't have to worry about it.

**Comment by Antondomashnev** [comment]
That is not a big deal for me, but I think this could be a nice to have that `match` removes the old provision profile from the local folder as well. This will simply keep Xcode folder with provision profiles cleaner. But the discussion can be closed if you don't see the point of it =)

**Comment by KrauseFx** [comment]
Cool, thanks 👍 Generally fastlane tries to avoid destructive actions, as it could delete something you might still need.

**Comment by KrauseFx** [comment]
Cool, thanks 👍 Generally fastlane tries to avoid destructive actions, as it could delete something you might still need.

**Comment by Antondomashnev** [comment]
@KrauseFx Quick question related to that issue. I've implemented a `fastlane` plugin do the proposed action. How can I make it available through `fastlane search_plugins`.
Thanks.

**Comment by KrauseFx** [comment]
@Antondomashnev Can you send me a link to the plugin? It will automatically show up after a while. I think currently only the top 25 plugins are listed, but of course, we should update it so that it shows all available plugins.

**Comment by Antondomashnev** [comment]
@KrauseFx sure [fastlane-plugin-remove-provisioning-profile](https://github.com/Antondomashnev/fastlane-plugin-remove-provisioning-profile)
