### ISSUE TITLE
scan hangs indefinitely

### ISSUE THREAD

**Issue by wkoszek** [fastlane/fastlane#5603]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have an open-source iOS app and encountered issue running `scan`. It hangs indefinitely, quite likely on `xcrun xcodebuild -list -workspace Sensorama.xcworkspace`.

https://travis-ci.org/wkoszek/sensorama-ios/builds/149670819

### Configuration Files

I minimised the whole project configuration on Travis CI to make it easier to report issues. Right now: `scan --workspace Sensorama.xcworkspace --scheme SensoramaTests` is the very first thing I run in script after `fastlane -v` and `scan -v`. It hangs (link above)

### Environment

fastlane version (run `fastlane -v`):
- fastlane 1.97.2
- scan 0.8.0
I don't use bundler to run fastlane. I use rvm.

And I have tried the same flow with the latest stuff, same result:
- fastlane 1.99.0
- scan 0.10.1

https://travis-ci.org/wkoszek/sensorama-ios/builds/149673251

**Comment by wkoszek** [comment]
I've updated my 2nd machine: MacMini to El Captain and XCode 7.3.1. It happens very often too. This is the Intel i7 model, so it's not about weak Travis-CI worker or anything anymore, which I suspected [also read through previous reports where people had trouble with waiting for xcodebuild to list workspaces] 

Steps to reproduce:

```
git clone https://github.com/wkoszek/sensorama-ios.git
cd sensorama-ios/Sensorama
../scripts/reproduce_test_issues
```

do it several times. If it doesn't hang, do "git clean -dfx ." and repeat. For me it's `50%`/`50%` that it'll happen.

**Comment by wkoszek** [comment]
Small detail:

```
$ scan --verbose --workspace Sensorama.xcworkspace --scheme SensoramaTests
WARN [2016-08-08 22:03:50.24]: xcodebuild -list -workspace Sensorama.xcworkspace
```

So it says "xcodebuild -list -workspace Sensorama.xcworkspace"

But it seems like it's hanging on:

```
$ ps axuw | grep xcode
wk              38980   0.0  0.0  2444412    980 s002  S+   10:05pm   0:00.01 grep xcode
wk              38957   0.0  0.3  2707128  29020 s001  S+   10:03pm   0:01.12 /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -showBuildSettings -workspace Sensorama.xcworkspace -scheme SensoramaTests
```

I can do:

```
kill 38957
```

and the `scan` comes back to normal.

**Comment by wkoszek** [comment]
Ok, I guess I'm getting closer to root cause. I've been running this command in my terminal:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -showBuildSettings -workspace Sensorama.xcworkspace -scheme SensoramaTests
```

and maybe 4th or 5th time I've got it to reproduce:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -showBuildSettings -workspace Sensorama.xcworkspace -scheme SensoramaTests
Build settings for action build and target SensoramaTests:
```

and it's hanging.

**Comment by wkoszek** [comment]
Seems like it's related to https://github.com/fastlane/fastlane/issues/5163 but I'm at XCode 7.3.1 + El Captain for now

**Comment by IngmarStein** [comment]
I think, you're talking about #4059, not #5163. For the former, there's an open PR (#5188) which fixes the issue.

**Comment by wkoszek** [comment]
@IngmarStein You are probably right. I skimmed through the bug report and the `xcodebuild` invocation in #5163 looked similar, but I guess it's not the same bug. I meant #4059.

**Comment by vpolouchkine** [comment]
Would you mind testing this on the latest version of `scan`? 0.11.2 Thanks!

**Comment by ianterrell** [comment]
@vpolouchkine I can reproduce this issue on `scan` 0.11.3 with Xcode 8 beta 6.

It hangs once every few tries. In my case I can also hang `xcodebuild` manually with `xcodebuild -showBuildSettings`, so it does seem to be #4059.

**Comment by vpolouchkine** [comment]
Thanks for confirming, we'll take a look.

**Comment by mfurtak** [comment]
Hi all, we've shipped a workaround (#5626) and timeout/retry solution (#5188) as part of [`fastlane_core` 0.51.0](https://github.com/fastlane/fastlane/releases/tag/fastlane_core/0.51.0) 🚀 

Thanks very much for your help! Please let us know how it looks 👍

**Comment by mfurtak** [comment]
To test the latest release, please run `[sudo] gem update fastlane_core` or if you have a `Gemfile`, `bundle update`

**Comment by mfurtak** [comment]
I'm going to close this for now, but please feel free to continue the conversation and we can reopen as needed! 👍
