### ISSUE TITLE
In-App enable in produce

### ISSUE THREAD

**Issue by gmogames** [fastlane/fastlane#5614]
Hi,

Sorry, this is more of a question that I could not find an answer to it then an issue.

We've automated the complete app creation here in our company, but one thing that we want to do that I'm not sure how is to enable In-App purchase during produce enable_services. Note that I don't want to upload in-app purchase data to itunes, I just want to enable the service when creating the App Id in developer portal.

Is there a way to enable in-app using produce?

Thanks!

**Comment by vpolouchkine** [comment]
Unfortunately, I don't believe you can do it, see https://github.com/fastlane/fastlane/tree/master/produce#parameters

**Comment by sogko** [comment]
cc @vpolouchkine 
Related to #5100

**Comment by sogko** [comment]
For reference, PR #6820 that allows `produce` to enable/disable In-App Purchase service has been merged.

**Comment by TKBurner** [comment]
@sogko Thanks!
