### ISSUE TITLE
Add progress to SCP

### ISSUE THREAD

**Issue by tomachi** [fastlane/fastlane#5615]
Would like an option to add a progress to the SCP command
Can be done by using tty, e.g:
scp File.xxx server:/Users/Desktop/Shared > /dev/tty

File.xxx  
                                                                                                                                                         6% 3840KB 629.5KB/s   01:31 ETA^File.xxx
                                                                                                                                                             7% 4608KB 478.9KB/s   01:58 ETA^File.xxx 
                                                                                                                                                            7% 4608KB 431.0KB/s   02:12 ETA%...
...

**Comment by TKBurner** [comment]
@tomachi Thanks for reaching out. Are you interested in submitting a PR? Thanks!

**Comment by tomachi** [comment]
Sorry. Ruby is not my strongest (-:

**Comment by TKBurner** [comment]
@tomachi No problem! I'll mark this as help wanted in case anyone from the community wants to submit a PR. Thanks for using Fastlane!
