### ISSUE TITLE
Flow of bumping versions

### ISSUE THREAD

**Issue by bartoszhernas** [fastlane/fastlane#5616]
Hi,

what is the best flow to handle bumping app versions?

I want to use `git_ensure_branch: master` when building my release apps and at the same time I want to build release candidate from `develop`.

As I see it now, if I commit the version changes on master and then release candidate version changes on develop I will have conflicts when merging develop to master.

What do you recommend is the best flow?

**Comment by vpolouchkine** [comment]
Take a look some of the setups that folks have shared: https://github.com/fastlane/examples
