### ISSUE TITLE
Action for configuring a plist inside an ipa/xcarchive

### ISSUE THREAD

**Issue by richardszalay** [fastlane/fastlane#5618]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

🔑 I'm doing a blog series on creating a "build-once" deployment pipeline using fastlane. As part of this process, the signing of the IPA happens at deployment time, at the moment the configuration is known, rather than at build.

As part of this, I've written a custom action that might fit well with the main predict. It's code purpose is to set a number of keys in a list that's inside an IPA file. It also supports: 

* explicit options for the plist version keys
* a list of plist buddy commands, rather than the more restrictive (but easier to look at) hash of value
* replacing the icon with a .iconset

I'm also thinking of added support for xcarchives in addition to ipas, since people might prefer their single build to work like that.

Would that be of interest and, if so, any thought on name? My current thoughts are:

* tempest - because it changes the environment
* faceoff - because it's swapping out the configuration
* facelift - as above, but slightly less trademark infring-y

Thoughts?

**Comment by richardszalay** [comment]
It's not, mr fastlane bot, at least not in any way that's relevant to your linka.

**Comment by KrauseFx** [comment]
Don't forget there is already a [liftoff](https://github.com/thoughtbot/liftoff) 👍 

Do you plan on providing this as a fastlane plugin?

**Comment by richardszalay** [comment]
I know about liftoff, but I'm not sure there's any similarities between it and what I'm proposing.

Yes, that's the plan, unless you can see it being useful in the main product.

**Comment by richardszalay** [comment]
@KrauseFx Is there an official way of distributing custom fastlane actions. For example, via gems?

**Comment by KrauseFx** [comment]
@richardszalay Yes, there is, check out the [Plugins guide](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)

**Comment by richardszalay** [comment]
Gotcha. Ok, I've run through the documentation and the plugin infrastructure code and I see how it all fits together.

I'll put together the action as a plugin and update this issue when it's ready.

**Comment by KrauseFx** [comment]
That's awesome, thanks @richardszalay. Let us know if you need any help

**Comment by richardszalay** [comment]
Done: https://rubygems.org/gems/fastlane-plugin-facelift

Includes all the trimmings (tests, working example fastfile)

**Comment by TKBurner** [comment]
@richardszalay Awesome! Really cool stuff here!

**Comment by richardszalay** [comment]
I've finally published my blog series, which might give some context as to why I wanted to do this - https://blog.richardszalay.com/2016/08/22/ios-deploy-pipeline-1-introduction/
