### ISSUE TITLE
Using a temporary keychain

### ISSUE THREAD

**Issue by richardszalay** [fastlane/fastlane#5619]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

🔑 I'm doing a blog series on creating a "build-once" deployment pipeline using fastlane. As part of this process, the signing of the IPA happens at deployment time, at the moment the configuration is known, rather than at build.

tl;dr I've created a pattern for temporarily replacing the keychain and safety restoring it afterwards. Would this be useful as a PR and what's the best way for it integrate?

As part of the process I mentioned above, I discovered that the support for specifying keychain files doesn't go very far, because many commands (not least of which, xcodebuild exportarchive) will use the keychain search list anyway. 

Given that, with Match, the source of truth for the private keys is the repository, there's no need for the keychain to stick around anyway. Plus it makes for a more secure and isolated process for a build server, since multiple projects may use the same "agent" (and this keychain).

So I created a helper function that creates a temporary strong-passworded keychain and adds it to the top of the search list. It also accepts a flag for temporarily clearing the search list to avoid falling back to a locked keychain in a build server environment.

The two issues are what to call it, and how it would best be implemented in a fastlane-esque way. Currently it simply accepts a block which is called while the keychain is in play (I wrap match+resign with it). I can't find any precedent for anything that temporarily changes state of something. Is there currently any support for lane decorator"? Because that could fit nicely.

**Comment by KrauseFx** [comment]
Hey @richardszalay, thanks for submitting the issue. Do you mean you set a keychain as the default keychain?

**Comment by richardszalay** [comment]
Hi @KrauseFx, no it actually only changes the search list using "security list-keychains". The default keychain remains unaffected.

**Comment by richardszalay** [comment]
I came to the conclusion that the scoped/block nature of the preferred API doesn't really suite being a plugin to fastlane. Ideally it would be implemented as some kind of "metadata" that decorates a lane and automatically adds before/after methods to it, but fastlane supports no such feature.

I've released the functionality as a regular ruby gem, for those that might find it useful: https://rubygems.org/gems/fastlane-plugin-facelift

**Comment by KrauseFx** [comment]
That's awesome, thanks for sharing @richardszalay 👍
