### ISSUE TITLE
deliver(beta: true) not working

### ISSUE THREAD

**Issue by aloifolia** [fastlane/fastlane#562]
'deliver' fails if I use it to manage Testflight. After the upload, when the program tries to activate the new version, I get the following error message:
`````
757: unexpected token at ''
````
Additionally, I get a screen shot of my app in iTunesConnect; but instead of the "Prerelease" tab the  "Versions" tab is presented.

Apart from this problem, I have a general question: Is it possible to manage the prerelease information that has to be added for each version? Sometimes these data get lost when I add a new version manually. It would be great if fastlane could upload all the necessary information from some files inside the meta directory.

**Comment by ohwutup** [comment]
hey @aloifolia ! sorry for the issue you were having, there have been a lot of releases since this issue was opened, would you mind updating fastlane and trying this again. feel free to reopen the issue if there is still a problem! thank you!! :+1:
