### ISSUE TITLE
Match for exisitng apps that are live

### ISSUE THREAD

**Issue by Rameshv** [fastlane/fastlane#5620]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to integrate Match into our build pipeline. It works great with newer apps, but when i try to use it for apps that are already live, it gives issues. The problem is its not finding the existing profile, instead it creates a new profile. Thats not acceptable since the app is already live, we cant switch to new profile.  

```

INFO [2016-08-05 19:30:52.72]: Starting login with user 'admin@xxxx.co.uk'
INFO [2016-08-05 19:30:57.64]: Successfully logged in
INFO [2016-08-05 19:30:57.64]: Fetching profiles...
WARN [2016-08-05 19:31:01.46]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
INFO [2016-08-05 19:31:06.01]: $ security list-keychains -d user

```

### Environment

fastlane version (run `fastlane -v`):  1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? nope

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by KrauseFx** [comment]
It is acceptable, as once your app is already in he App Store, you can revoke your certificates and your app will still work. 
The instructions of `match` state, that you need to run `match nuke [environment]` to start using it, as `match` handles its own set of profiles and certificates.

Let me know if that works for you and if you need any help 👍

**Comment by KrauseFx** [comment]
I assumed you mean the App Store with `live apps`, if you were talking about Ad Hoc or Enterprise, the situation is a bit different. 

Also make sure to check out https://codesigning.guide 👍

**Comment by richardszalay** [comment]
Michał Laskowski has a blog post on that includes how to migrate from existing keys / profiles to Match. http://macoscope.com/blog/simplify-your-life-with-fastlane-match/#migration

**Comment by Rameshv** [comment]
Thanks @KrauseFx, got it now, thanks

THanks @richardszalay, it looks interesting

**Comment by lnhrdt** [comment]
@KrauseFx I've been through this a few times in organizations where we don't have permissions to create provisioning profiles, etc. The blog article @richardszalay linked has bailed be out, but I see the justification for match to support this workflow! Any thoughts?

**Comment by TKBurner** [comment]
@lnhrdt I don't think we intend to do this, as the setup steps require new certs be made. Glad to hear @richardszalay link helped.

Thanks @richardszalay 👍
