### ISSUE TITLE
Improve speed of scan-gym process

### ISSUE THREAD

**Issue by krystiansliwa** [fastlane/fastlane#5628]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description

My issue is about optimizing scan/gym flow to do some 2 step tests. Now process of testing in project looks like:

- Run unit tests
- Run UITests
- Manual tests by QA Engineer 

Currently in my project I have lane that contains these steps:

1. Scan for UnitTests and UITests
2. Gym to make ipa file for QA Testers
3. Upload symbols to Crashlytics

Scan process takes about 15min including building, unit testing and uitesting.
After that I let gym module to build ipa file for our testers to make some manual tests. (Here gym also builds project and signing).
Gym takes about 10min.

So whole lane process takes 25min. Scan uses clean, next step (gym) don't use clean but compiling is starting again.

It is possible to make ipa file for testers after scan? Without building project again? Xcode configuration for scheme is identical (no mix of release and debug).

Fastfile:
```ruby
default_platform :ios

platform :ios do
  before_all do
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "1"
  end

  lane :qa_lane do
    clear_derived_data
    version = ENV["BUILD_NUMBER"]
    scan_lane(scheme: "MyApp QA")
    build_lane(
      scheme: "MyApp QA",
      ipa_name: "MyApp_QA_##{version}.ipa",
      export_method: "ad-hoc"
    )
    upload_symbols_to_crashlytics
    post_slack(message: "QA successful build and distributed with version #{version}")
  end

  private_lane :build_lane do |options|
    scheme = options[:scheme]
    ipa_name = options[:ipa_name]
    export_method = options[:export_method]
    gym(
      scheme: scheme,
      workspace: "MyApp.xcworkspace",
      clean: false,
      silent: true,
      output_directory: "./fastlane/build",
      output_name: ipa_name,
      include_bitcode: false,
      use_legacy_build_api: true,
      export_method: export_method
    )
  end

  private_lane :scan_lane do |options|
    scheme = options[:scheme]
    scan(
    scheme: scheme,
    clean: true,
    device: "iPhone 6 9.3",
    slack_only_on_failure: true
    )
  end

  private_lane :post_slack do |options|
    message = options[:message]
    slack(
    message: message,
    default_payloads: [:git_author]
    )
    end

  error do |lane, exception|
     slack(message: exception.to_s, success: false)
  end

end
```

### Environment

Project is on iOS and is running on Jenkins.
fastlane version 1.99.0

**Comment by alistra** [comment]
I would say that it has to be this way, as the Unit and UI testing target the simulator which is `i386`, and builds for manual testers need to be `arm` or `arm64`, so the whole process needs to be redone for a different architecture.

**Comment by krystiansliwa** [comment]
Thanks, It might be this case. Do you have some solutions to solve this limitations?

**Comment by TKBurner** [comment]
Thanks @alistra! There isn't another workaround for this. 👍
