### ISSUE TITLE
Write output in same line on the console?

### ISSUE THREAD

**Issue by tomachi** [fastlane/fastlane#5630]
### Issue Description

I use jenkins in order to build with fastlane.
As part of the fastlane job I send the built file to a server so I can run automation on it.
As fastlane SCP will not give progress of file uploading I added Net::SCP to the fastfile and use its progress, like this:
Net::SCP.start("10.8.1.29", "serverlocal", :password => "pass") do |scp|
  			scp.upload!(ENV['IPA_OUTPUT_PATH'], "#{destination}", recursive: true, verbose: true)  do |ch, name, sent, total|
  				percent = ((sent.to_f/total.to_f)*100.to_f).to_i
  				UI.important "Uploading... #{percent}% \r"
  				STDOUT.flush
			end
			UI.message(['[SCP COMMAND]', "Successfully Uploaded", ENV['IPA_OUTPUT_PATH'], "#{destination}"].join(': '))
		end

Where in the UI log I put \r in order to try overwriting on the same console line like I do in the terminal and flush it, but with no luck. Fastlane will always run a new line with timestamp what will create a long log counting to 100%

##### Complete output when running fastlane, including the stack trace and command used

```
...
[04:54:14]: Uploading... 0% 

[04:54:15]: Uploading... 0% 

[04:54:15]: Uploading... 0% 

[04:54:15]: Uploading... 0% 

[04:54:15]: Uploading... 0% 

[04:54:15]: Uploading... 0% 

[04:54:15]: Uploading... 0% 

[04:54:15]: Uploading... 1% 

[04:54:15]: Uploading... 1% 

[04:54:15]: Uploading... 1% 

[04:54:15]: Uploading... 1% 

[04:54:15]: Uploading... 1% 

[04:54:15]: Uploading... 1% 
...
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
Net::SCP.start("10.8.1.29", "serverlocal", :password => "pass") do |scp|
  			scp.upload!(ENV['IPA_OUTPUT_PATH'], "#{destination}", recursive: true, verbose: true)  do |ch, name, sent, total|
  				percent = ((sent.to_f/total.to_f)*100.to_f).to_i
  				UI.important "Uploading... #{percent}% \r"
  				STDOUT.flush
			end
			UI.message(['[SCP COMMAND]', "Successfully Uploaded", ENV['IPA_OUTPUT_PATH'], "#{destination}"].join(': '))
		end
```

### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by vpolouchkine** [comment]
Perhaps @hjanuschka can include this in v2 of `scp` 💯

**Comment by tomachi** [comment]
That would be great!
