### ISSUE TITLE
[Not an issue] Request to add documentation to match readme for adding a new device

### ISSUE THREAD

**Issue by AJMiller** [fastlane/fastlane#5633]
I was having a lot of trouble finding the 'right way' to add a device to the developer portal and re-sign the app for beta distribution just following the readme for match. A short paragraph about 'adding a new device' would go a long way. I would write it myself and submit a pull request if I felt comfortable with what the steps actually should be. I'm guessing something like this:

1. Add device uuid to developer portal (or alternatively add the device ID to the Fastfile using register_devices ?)
2. run ```match development --force``` on the command line (running ```match development``` I assume will not auto-detect new udid's and regenerate the provisioning profile)

I'm also assuming it's recommended to keep ```match development``` or ```match development --read-only``` in the Fastfile build process and run ```match development --force``` manually when adding a new device? To be honest, it's not super clear to me when match decides to regenerate the provisioning profile and when it uses the existing one.

**Comment by KrauseFx** [comment]
Great idea, I'll update the documentation, thanks for your feedback 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/issues/5658, let me know what you think 👍

**Comment by AJMiller** [comment]
Yeah definitely along the lines of what I was thinking. I also saw a force_for_new_devices option that appears to do exactly that, correct? So maybe something like

**Comment by KrauseFx** [comment]
@AJMiller Ha, great catch, I completely forgot about that option 👍

**Comment by AJMiller** [comment]
@KrauseFx glad I could help. Thanks for such an awesome build tool!

**Comment by KrauseFx** [comment]
🎉
