### ISSUE TITLE
cert issues: Could not store password in keychain

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5634]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The issue at presence is why the error is issues and how to sort it (the message is obscure and doesn't give any hint related to the problem)

##### Complete output when running fastlane, including the stack trace and command used

```
bash-3.2$ cert

+---------------+-------------------------------------------------+
|                     Summary for cert 1.4.1                      |
+---------------+-------------------------------------------------+
| development   | false                                           |
| force         | false                                           |
| keychain_path | /Users/xxxx/Library/Keychains/login.keychain |
+---------------+-------------------------------------------------+

[15:33:06]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: xxx@xxx.xxx
[15:33:15]: Starting login with user 'xxx@xxx.xxx'
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for xxx@xxx.xxx): **********
security: SecKeychainAddInternetPassword <NULL>: User interaction is not allowed.
Could not store password in keychain
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

cert version (run `fastlane -v`):
cert 1.4.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Standard macos environment with ruby linked from brew, fully updated

**Comment by vpolouchkine** [comment]
Is this the same as https://github.com/fastlane/fastlane/issues/5632?

**Comment by lferro9000** [comment]
Not exactly. This is just due to the fact that keychains can't be unlocked within the command that tries to access them in a terminal (Apple limitation).

This can be sorted by just using security command to open the keychain, before issueing the command. Annoying, but one can live with it, i guess.

Closing this down, as there is a work-around and there is not much that can be done (apart from improving the information on the error messages stating for instance that one may need to unlock the keychain before trying to use it on the terminal).
