### ISSUE TITLE
Cert could create .keychain if name doesn't exist

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5635]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When creating a new cert, the system allows the use of the -k parameter to state the keychain to use, but doesn't create a new one if the file doesn't exit.

##### Complete output when running fastlane, including the stack trace and command used

```
cert -k cert.keychain
[16:25:28]: Error setting value 'cert.keychain' for option 'keychain_path'

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new

[!] Keychain not found at path '/Users/xxxx/keystores/cert.keychain'```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

cert version (run `cert -v`):
cert -v
cert 1.4.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Just standard with ruby from brew linked to avoid "Apple" reserved links errors.

**Comment by vpolouchkine** [comment]
Thanks for the report. I believe that is the intended behavior. 👍
