### ISSUE TITLE
Specify release date with deliver

### ISSUE THREAD

**Issue by matthewjsloane** [fastlane/fastlane#5645]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I know that it's possible to specify the date that you would like your app to be released via iTunes Connect - for example, releasing the app on August 24th, 2016 at 12:00pm EST. Does the API support this functionality/if so, are there plans to add this feature? As far as I can tell, the only option currently is to automatically or manually release upon approval (as opposed to setting a future date). Thanks!

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by TKBurner** [comment]
Hi @matthewjsloane Thanks for reaching out. Right now we don't have support for this and I'm pretty sure that's because it's not alterable or consumable via the API. I'm going to mark this as blocked because of that. Thanks!
