### ISSUE TITLE
Pilot: Automatically distribute to internal testers without waiting for build processing

### ISSUE THREAD

**Issue by GeovationMax** [fastlane/fastlane#5650]
Hi,

we are using fastlane in CircleCI to build and deploy our iOS app to Testflight.

As far as I see it is necessary to wait for the build process to finish in order to distribute the app to internal or external testers respectively.

In a local environment this wouldn't be a problem, but in a CI environment it consumes precious build minutes.

Now I am wondering:
Is there a possibility to tell iTunes connect to automatically distribute a newly uploaded IPA internally, i.e. without telling it explicitely to do so?
This would allow us to skip waiting for the build processing.

Cheers,
Max

**Comment by KrauseFx** [comment]
Hey @GeovationMax, I don't think there is a way to do that. If you find a way to enable automatic distribution on iTunes Connect directly, we could also implement it in pilot and spaceship, but we're limited to what you can do on iTunes Connect 👍

**Comment by johngibb** [comment]
I'm in the same boat.

At the very least, maybe it would make sense to add a `max_processing_wait` option to `pilot` to limit how long it will poll? That way, there'd at least be an upper bound on build minutes consumed. 

I'm worried about the occasional build that'll take over an hour to process.

**Comment by anantsaraswat** [comment]
I am facing the same... Do anyone have update on this ?

**Comment by TKBurner** [comment]
@anantsaraswat Right now it's not possible to implement this but if you find a way please do let us know! 👍
