### ISSUE TITLE
Cannot submit for review, --skip_screenshots no longer working

### ISSUE THREAD

**Issue by Luke-SF** [fastlane/fastlane#5653]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

You used to be able to just submit an app for review:

```
deliver submit_build -u useremail --skip_metadata --skip_binary_upload --skip_screenshots --submit_for_review -a my.app.id.here
```

Now it just gives an error about nonexistent image file:
```
[08:35:51]: Finished the upload to iTunes Connect
[08:35:52]: Selecting the latest build...
[08:35:54]: Selecting build version (version)...
[08:35:55]: Successfully selected build
[08:35:55]: Submitting the app for review...

Looking for related GitHub issues on fastlane/fastlane...

[08:35:58]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass

[!] The request could not be completed because:
	You must provide a screenshot for the primary size of a device. You must provide a screenshot for the primary size of a device. You must provide a screenshot for the primary size of a device. You must provide a screenshot for the primary size of a device.

```

### Environment

fastlane version (run `fastlane -v`): N/A, command hangs.

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by KrauseFx** [comment]
> You must provide a screenshot for the primary size of a device
Please make sure to provide screenshots for all languages for the device type iPhone 6 and iPhone 6s 👍

**Comment by KrauseFx** [comment]
Also make sure to update to the latest version of `spaceship` and `deliver` using `[sudo] gem update deliver`

If `-v` hangs, run `[sudo[ gem cleanup`

**Comment by kaililleby** [comment]
Hi, I'm experiencing a similar problem.
My Fastfile contains (amongst other command) "deliver(force: true, submit_for_review: true)"
I have in my screenshots folder both images for iPhone 6 and 6+ .. and iPad and iPhone 4 and 5..
After upgrading to latest fast lane version i get the following error:

/Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/tunes/tunes_client.rb:180:in `handle_itc_response': [31m[!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	You must provide a screenshot for the primary size of a device. You must provide a screenshot for the primary size of a device.[0m
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/tunes/tunes_client.rb:684:in `prepare_app_submissions'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/tunes/app_submission.rb:117:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.1/lib/spaceship/tunes/application.rb:267:in `create_submission'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.2/lib/deliver/submit_for_review.rb:8:in `submit!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.2/lib/deliver/runner.rb:87:in `submit_for_review'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.13.2/lib/deliver/runner.rb:30:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/actions/deliver.rb:18:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:192:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:177:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:176:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:176:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:102:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:50:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:50:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:51:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:248:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/lib/fastlane/cli_tools_distributor.rb:53:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.100.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

This did not fail when last run on fastlane 1.81.0 in early july..
And no changes have been done to the fastlane setup or screenshots..

Any idea??

**Comment by kaililleby** [comment]
i haven't provided a "iPad Pro" screenshot, ref https://developer.apple.com/library/ios/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Appendices/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW2 
could that be the cause?

**Comment by vpolouchkine** [comment]
That is the likely culprit.

**Comment by hjanuschka** [comment]
i can confirm - adding ipad_pro screenshots fixes the issue! thx @kaililleby
