### ISSUE TITLE
spaceship: credential_manager incorrectly detected

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5654]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When issuing spaceship from the command line without any other parameter, the process detects incorrectly the credentials_manager gem.

The credentials_manager is version 0.16.0 when the requirements are just 0.9.0

##### Complete output when running fastlane, including the stack trace and command used

```
spaceship
WARN: Unresolved specs during Gem::Specification.reset:
      credentials_manager (>= 0.9.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

spaceship (0.30.0, 0.29.1, 0.28.0, 0.27.2, 0.27.1, 0.26.2, 0.26.1, 0.25.1, 0.24.1, 0.19.4, 0.19.3)
credentials_manager (0.16.0, 0.15.0, 0.14.0)

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Just ruby installed and linked with brew to avoid apple protected links.

**Comment by KrauseFx** [comment]
Thanks for letting us know, I just pushed https://github.com/fastlane/fastlane/pull/5656 🚀  This will be in the next release. In the mean-time, please run `[sudo] gem cleanup` to clean old versions

**Comment by lferro9000** [comment]
Fixed. Thanks :)

The whole toolchain does look impressive.

I think the major problems i've encountered so far are based around my "weak" knowledge of ruby and workflow differences between a pure "fastlane" one and what we are using.

But with the power of spaceship one can tailor things enough if needed be (which on certain cases is what i've being using).
