### ISSUE TITLE
Spaceship::Tunes.login Permission denied @ dir_s_mkdir - /home/webapp

### ISSUE THREAD

**Issue by summera** [fastlane/fastlane#5662]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Getting `Permission denied @ dir_s_mkdir - /home/webapp` when logging into iTunes with 

``` ruby
Spaceship::Tunes.login(ENV['ITUNES_USER'], ENV['ITUNES_PASS'])
```

I'm running this command on AWS Elasticbeanstalk as the webapp user. From what I can tell, it looks like Spaceship wants to [store the cookie in a directory](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L160) that does not exist, `/home/webapp`. 

To test this out:

``` bash
su -s /bin/bash -c "ls ~/" webapp
ls: cannot access /home/webapp/: No such file or directory
```

Stack trace:

```
/opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:252:in `mkdir': Permission denied @ dir_s_mkdir - /home/webapp (Errno::EACCES)
    from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:252:in `fu_mkdir'
    from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:226:in `block (2 levels) in mkdir_p'
    from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:224:in `reverse_each'
    from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:224:in `block in mkdir_p'
    from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:210:in `each'
    from /opt/rubies/ruby-2.2.4/lib/ruby/2.2.0/fileutils.rb:210:in `mkdir_p'
    from gems/spaceship-0.30.0/lib/spaceship/client.rb:162:in `persistent_cookie_path'
    from gems/spaceship-0.30.0/lib/spaceship/two_step_client.rb:77:in `load_session_from_file'
    from gems/spaceship-0.30.0/lib/spaceship/client.rb:243:in `send_shared_login_request'
    from gems/spaceship-0.30.0/lib/spaceship/tunes/tunes_client.rb:126:in `send_login_request'
    from gems/spaceship-0.30.0/lib/spaceship/client.rb:352:in `do_login'
    from gems/spaceship-0.30.0/lib/spaceship/client.rb:225:in `login'
    from gems/spaceship-0.30.0/lib/spaceship/client.rb:88:in `login'
    from gems/spaceship-0.30.0/lib/spaceship/tunes/spaceship.rb:22:in `login'
```
### Environment

Running Spaceship `0.30.0`. Previously I was running Spaceship `0.22.0` without this issue. I think I've pinpointed the change to [this commit](https://github.com/fastlane/fastlane/commit/e12d1caf8d1efa48eb419dd70fe02dfcd58a3013#diff-a9086da2d7e8a66b647fdabdb0a7cca7). Where was the cookie being stored in version `0.22.0`?

It's possible I'm missing something here. Can we set the cookie path for spaceship manually? Didn't see an option for this.

Thanks!

**Comment by KrauseFx** [comment]
Interesting, fastlane uses the following to create a directory
```ruby
path = File.expand_path(File.join("~", ".spaceship", self.user, "cookie"))
FileUtils.mkdir_p(File.expand_path("..", path))
```
Is there any way you can fix the permission problem on your side?

**Comment by summera** [comment]
I put in a temporary hack on my end to get things working:
```ruby
module Spaceship
  class Client
    def persistent_cookie_path
      path = File.expand_path(File.join("./tmp", ".spaceship", self.user, "cookie"))
      FileUtils.mkdir_p(File.expand_path("..", path))
      return path
    end
  end
end
```

In this case I'm utilizing Spaceship in a Rails environment and so I'm storing it in the tmp dir. 

If the file path at which Fastlane chooses to store the cookie is not always reliable I think it would be good to provide an option to specify the path. If this is going to be an issue on AWS or other server environments, I don't think  messing with permissions is a good long term fix.

**Comment by summera** [comment]
@KrauseFx Checking back in on this. One solution would be to change `File.expand_path(File.join("~", ".spaceship", self.user, "cookie"))` to `File.expand_path(File.join("/tmp", ".spaceship", self.user, "cookie"))`. Thoughts on this?

This would put the cookie in the same dir as the `itc_service_key` and allow for compatibility in an environment where `~/` is not an option (like AWS Elasticbeanstalk).

If you're cool with this, I'll put in a PR.

A second option would be to pass in the cookie_path on login.

**Comment by chris-armstrong** [comment]
I can confirm that I'm experiencing this issue on AWS Elastic Beanstalk too with the boarding app (I'm working around it by creating and chown/chmod the /home/webapp directory). It seems that a library shouldn't assume it has access to the current user's home directory - is there not a standard directory for writeable filesystem access in rails apps?

**Comment by summera** [comment]
@chris-armstrong Agreed, but we can't assume we are in a rails environment either. I think a good place to store would be `/tmp` or `/var/tmp` since it's fairly safe to assume we are on a unix filesystem.

**Comment by KrauseFx** [comment]
@summera storing it in /tmp sounds reasonable to me, let me know if you find the time to prepare a PR for this 👍

**Comment by summera** [comment]
@KrauseFx submitted https://github.com/fastlane/fastlane/pull/6759

**Comment by TKBurner** [comment]
@summera Awesome! Thanks, we'll work with you there 👍
