### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#5665]
### New Issue Checklist
- [x] Updated fastlane to the latest version
##### Complete output when running fastlane, including the stack trace and command used

```
Command used: `fastlane beta`

Output:

[14:47:07]: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 4           |
| 4    | gym                                 | 43          |
| 5    | pilot                               | 2           |
+------+-------------------------------------+-------------+

[14:47:07]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[14:47:07]: Error finding relevant GitHub issues: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

<details>
<summary>

Click to see Fastfile</summary>

``` ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Jokes", use_legacy_build_api: true) # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Jokes", use_legacy_build_api: true) # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```

</details>
### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? Not sure.

**Comment by KrauseFx** [comment]
Have you tried following the instructions on https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb#L63-L69

**Comment by RishabhTayal** [comment]
Yes. I tried `brew update && brew upgrade openssl`. When I run this command it says `Error: openssl 1.0.2h_1 already installed`.

**Comment by KrauseFx** [comment]
Can you try completely uninstall `openssl` and installing it again?

**Comment by RishabhTayal** [comment]
`brew uninstall --force openssl`?

**Comment by RishabhTayal** [comment]
I did `brew uninstall --force openssl` and then `brew install openssl`. No luck.

**Comment by ninjz** [comment]
I'm getting this issue as welll

**Comment by TKBurner** [comment]
@ninjz @RishabhTayal Thanks for following up on this. What version of Ruby are you using? (run `ruby -v` to find out)

**Comment by RishabhTayal** [comment]
@TKBurner ruby 2.2.1p85

**Comment by TKBurner** [comment]
Hi @RishabhTayal Thanks for following up. Are you able to upgrade to 2.3.0 or higher? That'd help me figure out what's going on here. Thanks!

**Comment by RishabhTayal** [comment]
I now have `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]` installed.

**Comment by TKBurner** [comment]
Hi @RishabhTayal Thanks for following up. Can you add the --verbose flag to your run of fastlane and share your full input and outuput? I want to take a look. Thanks!

**Comment by RishabhTayal** [comment]
@TKBurner Here is the output with the `deliver --verbose` option. I used `deliver` in this example. But I get the same error when using `fastlane`.

<details>
<summary>Click to see details</summary>
```
rtayal$ deliver --verbose
INFO [2016-08-30 12:37:38.52]: Login to iTunes Connect (username@example.com)

Looking for related GitHub issues on fastlane/fastlane...
Search query: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

URL: https://api.github.com/search/issues?q=SSL_connect%20returned=1%20errno=0%20state=SSLv3%20read%20server%20certificate%20B:%20certificate%20verify%20failed+repo:fastlane/fastlane
ERROR [2016-08-30 12:37:39.64]: Error finding relevant GitHub issues: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': [!] SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
        from /Users/rtayal/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1133:in `get'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-cookie_jar-0.0.6/lib/faraday/cookie_jar.rb:22:in `call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:423:in `block in send_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:340:in `with_retry'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:422:in `send_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:397:in `request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:326:in `itc_service_key'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:276:in `block in send_shared_login_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:423:in `block in send_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:340:in `with_retry'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:422:in `send_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:397:in `request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:275:in `send_shared_login_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/tunes/tunes_client.rb:126:in `send_login_request'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:369:in `do_login'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:227:in `login'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/client.rb:90:in `login'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/spaceship-0.32.0/lib/spaceship/tunes/spaceship.rb:22:in `login'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/deliver-1.13.3/lib/deliver/runner.rb:14:in `login'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/deliver-1.13.3/lib/deliver/runner.rb:7:in `initialize'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/deliver-1.13.3/lib/deliver/commands_generator.rb:47:in `new'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/deliver-1.13.3/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/deliver-1.13.3/lib/deliver/commands_generator.rb:128:in `run'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/deliver-1.13.3/lib/deliver/commands_generator.rb:12:in `start'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1@global/gems/deliver-1.13.3/bin/deliver:5:in `<top (required)>'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1/bin/deliver:23:in `load'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1/bin/deliver:23:in `<main>'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/rtayal/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```
</details>

**Comment by TKBurner** [comment]
Hi @RishabhTayal Thanks for following up. Can you take a look at #5476. It seems like he has found a viable solution. Thanks!

**Comment by RishabhTayal** [comment]
@TKBurner Still getting the same error. Just one observation when I ran the `brew update && brew upgrade openssl` command, I got the following message in the terminal output.

```
rtayal$ brew update && brew upgrade openssl

Already up-to-date.
Error: openssl 1.0.2h_1 already installed
```

**Comment by TKBurner** [comment]
Hi @RishabhTayal Thanks for following up. I see you are still using Ruby 2.2.1, can you type `rvm use 2.3.2`?

Thanks!

**Comment by RishabhTayal** [comment]
The latest version of ruby is `2.3.1`. I willl try to use the latest version and check again.

**Comment by wongzigii** [comment]
I am getting this error.

**Comment by TKBurner** [comment]
@wongzigii Can you uninstall and reinstall openSSL? Thanks!

**Comment by wongzigii** [comment]
@TKBurner  It works after re-installing openSSL.

**Comment by RishabhTayal** [comment]
@wongzigii how did you reinstall openssl? I am still getting this error.

**Comment by wongzigii** [comment]
@RishabhTayal  I removed the original source and changed to `https://gems.ruby-china.org/`. 

    gem source -a https://gems.ruby-china.org/
    gem source -r YOUR_GEM_SOURCE

**Comment by louisatome** [comment]
I had the same problem with the command `supply init`.
I changed my ruby version from 2.1.5 to 2.3.1 and it works now.

**Comment by TKBurner** [comment]
@louisatome Awesome! Glad to hear that we've gotten to the bottom of this. Do you think there is a change we can make on our end to avoid this for other users?

**Comment by JingWZ** [comment]
same issue when using match and fixed by switched to ruby 2.3.0

**Comment by KrauseFx** [comment]
Hey everyone, we've been working on a new way to install and use fastlane, all you have to do is to download `fastlane.zip` and double click the `install` file. This will install fastlane with all its Ruby and OpenSSL dependencies, and should all work out of the box.
We just finished building this, and would love your early feedback on this beta. Please let us know how it works for you and if you run into any problems :+1: 
Download the latest version [here](https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip).

**Comment by KrauseFx** [comment]
I'll close this for now

**Comment by RishabhTayal** [comment]
I got this error recently when installing fastlane and running a lane on a new machine. I think this issue definitely needs to be resolved. Have been getting this more often recently on first installations.

Please re-open.

**Comment by RishabhTayal** [comment]
Here is the `fastlane env` output from the new machine.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | 
Value                                                          |
| ------------------- | 
-------------------------------------------------------------- |
| OS                  | 
10.11.6                                                        |
| Ruby                | 
2.0.0                                                          |
| Bundler?            | 
false                                                          |
| Git                 | git version 2.10.1 (Apple 
Git-78)                              |
| Installation Source | 
/usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 
(15G31)                                       |
| Ruby Lib Dir        | 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 
2015                                    |
| Is contained        | 
false                                                          |
| Xcode Path          | 
/Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 
8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.2.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

platform :ios do

   before_all do
   
  desc "\033[1mDownloads all provisioning profiles and certificates\033[0m"
  desc "This action does the following:"
  desc "- Adds new devices from developer portal to provisioning profiles"
  desc "- Fetches development provisioning profiles and certificates"
  desc "- Fetches adhoc provisioning profiles and certificates"
  desc "- Fetches appstore provisioning profiles and certificates"
  lane :match_all_profiles do
   match(
     type: 'development',
     force_for_new_devices: true,
     app_identifier: [
       "com.xxx.xxx"
	])
   puts "------------- Downloaded all certificates and provisioning 
profiles -----------------".yellow
end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
team_name "xxxx"
# team_id "xxxx"

# To select a team for iTunes Connect use
itc_team_name "xxxx"
# itc_team_id "xxxx"

# you can even provide different app identifiers, Apple IDs and team 
names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.5        |
| xcodeproj                 | 1.1.0        |
| claide                    | 1.0.1        |
</details>

*generated on:* **2017-01-10**
</details>
