### ISSUE TITLE
Match should not call sigh with force: true

### ISSUE THREAD

**Issue by richardszalay** [fastlane/fastlane#5667]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

🔑 If a profile can't be found on the repository, match calls sigh with `force: true`. With this flag set, sigh will add all devices to the profile, which may not be what the user wanted.

(I also think that force_for_new_devices should be comparing the local/remote _profile_ devices count, rather than comparing the local profile device count to the _total_ number of devices on the portal)
### Environment

fastlane version (run `fastlane -v`): 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
Interesting, thanks @richardszalay  👍 What's the reason you don't want all devices to be included? Just curios about the use-case :

**Comment by richardszalay** [comment]
Essentially one "Portal Team" doesn't represent every user for every app. Different apps have different "sets" of users (that we're happy to maintain ourselves in the portal).

**Comment by richardszalay** [comment]
This hasn't been resolved by a newer release.

**Comment by TKBurner** [comment]
@richardszalay Thanks for following up. I'm going to mark this as a feature request and open it up to PRs. I think this would make more sense as an option than a default. What do you think?

**Comment by richardszalay** [comment]
@TKBurner I think that sounds like a great idea. I'll do it myself, if I ever get a spare moment ;)
