### ISSUE TITLE
[sigh] Embedded mobileprovision in framework bundles is not updated while resigning

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#5669]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When using `PROVISIONING_PROFILE` option for `xcodebuild` command, an `embedded.mobileprovision` is added to all dynamic frameworks. In my case I'm using CocoaPods with `use_frameworks!` configuration option.
## With `PROVISIONING_PROFILE`

```
xcodebuild -workspace MyProject.xcworkspace -scheme MyScheme -configuration Release PROVISIONING_PROFILE="my-profile-UUID"
```

So when "Embed Pods Frameworks" build phase is running, I can see `embedded.mobileprovision` present in all frameworks, e.g.

> building file list ... done
> SVProgressHUD.framework/
> SVProgressHUD.framework/Info.plist
> **SVProgressHUD.framework/embedded.mobileprovision**
> SVProgressHUD.framework/SVProgressHUD
> ...
> SVProgressHUD.framework/_CodeSignature/
> SVProgressHUD.framework/_CodeSignature/CodeResources

I believe this is how `xcodebuild` works when `PROVISIONING_PROFILE` option is specified - it just embeds it into anything that has bundle ID, including frameworks.

This is how it looks in the IPA:
![image](https://cloud.githubusercontent.com/assets/350654/17536816/3070d0bc-5edb-11e6-9792-58d7673bbece.png)
## Without `PROVISIONING_PROFILE`

```
xcodebuild -workspace MyProject.xcworkspace -scheme MyScheme -configuration Release
```

This time there is no provisioning profile embedded into framework. I think that's because automatic lookup finds no profile matching framework's bundle ID.
## How Does It Relate to Sigh?

Basically, when resigning an app using `sigh resign` action, the `embedded.mobileprovision` inside `.framework` bundles is neither updated nor removed. So when uploading such resigned app to iTC it comes back with errors like this:

> ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/MyApp.app/Frameworks/AFNetworking.framework/AFNetworking' must be signed with the certificate that is contained in the provisioning profile."

After resigning, signing identity, team ID and profile UUID have changed, except for those "extra" `embedded.mobileprovision` inside frameworks.
## Suggested Fix?

It does feel like Xcode is doing us a bad service by sticking that profile everywhere, on the other hand it kind of makes sense since we explicitly used `PROVISIONING_PROFILE` option.

For the app I'm currently working on, the CI setup is a bit of legacy and I can't just rewrite scripts and get rid of that option.

So I guess `sigh resign` could take care of this problem, i.e. remove all embedded mobile provisioning profiles from all `.framework` bundles before resigning them.

After all, those profiles inside frameworks make no sense at all.

... waiting when we can move to Xcode 8 with signing not required any more for frameworks :)
### Environment

cocoapods: `1.0.0`
fastlane: `1.99.0`
sigh: `1.6.0`
bundle exec: `yes`
rvm: `yes`

**Comment by vpolouchkine** [comment]
Thanks for the report, sounds like a bug to me. I will bubble this up to the core team.  👍

**Comment by jlubeck** [comment]
So I built my app with gym and sent the IPA to my client. I have no access to how they do the re-signing, but they did came back to me with an error when submitting to the App Store with all the frameworks having the "must be signed with the certificate that is contained in the provisioning profile. frameworks" error. 

This is my gym command inside the lane:

    gym(scheme: "Name", use_legacy_build_api: true, configuration: "Production", export_method: "enterprise", output_directory: "build", output_name: "Name", clean: true)


How can I change it so that it gives me proper IPA that they can re-sign and upload without issues?

Thanks

**Comment by jlubeck** [comment]
Hi @mgrebenets, thanks for your quick reply. This is the contents of my IPA (with my own signing before sending to client):

![Alt text](https://monosnap.com/file/tJE7LVkYFgfizseJ7xt4JChb1PwZuO.png)

There is only one embedded.mobileprovision and it is outside the Frameworks folder. Would that be fine, or is that the problem?

If this is fine and the problem is on their end, like I said, I don´t know what they use, and I don´t think they will tell me. But is there anything I can tell them to help them?

Oh, this is (one of) the actual errors that they sent me:

> "Error Domain=ITunesConnectionOperationErrorDomain Code=1091 \"Invalid Code Signing. The executable 'Payload/Name.app/Frameworks/AFNetworking.framework/AFNetworking' must be signed with the certificate that is contained in the provisioning profile.\" UserInfo={NSLocalizedRecoverySuggestion=Invalid Code Signing. The executable 'Payload/Name.app/Frameworks/AFNetworking.framework/AFNetworking' must be signed with the certificate that is contained in the provisioning profile., NSLocalizedDescription=Invalid Code Signing. The executable 'Payload/Name.app/Frameworks/AFNetworking.framework/AFNetworking' must be signed with the certificate that is contained in the provisioning profile., NSLocalizedFailureReason=iTunes Store operation failed.}",

Thanks!

**Comment by mgrebenets** [comment]
> There is only one embedded.mobileprovision and it is outside the Frameworks folder. Would that be fine, or is that the problem?

That's actually fine. When such a file exists, iTunesConnect returns the error, just like the one you posted.

I can only assume, that the resign script or software, which you client is using, does something like this

```
for all nested frameworks
  copy provisioning profile and name it embedded.mobileprovision
end
```

They probably use one of the dozens scripts that can be found online.
I wouldn't be surprised if they are using something they wrote in-house.

You should recommend them to try `sign resign` instead :)

**Comment by jlubeck** [comment]
Well, glad to hear the problem is not on my side! I´ll try your suggestion. Thanks!

**Comment by jlubeck** [comment]
Success. Thanks @mgrebenets !

**Comment by TKBurner** [comment]
@mgrebenets Thanks so much for helping out! @jlubeck So glad to hear you are up and running! 👍
