### ISSUE TITLE
how to update on El Capitan?

### ISSUE THREAD

**Issue by haemi** [fastlane/fastlane#567]
I get informed that I'm using a pretty old version:

```
#######################################################################
# snapshot 0.9.2 is available. You are on 0.7.1.
# It is recommended to use the latest version.
# Update using 'sudo gem update snapshot'.
# To see what's new, open https://github.com/KrauseFx/snapshot/releases.
#######################################################################
```

but if I try to update:

```
sudo gem update snapshot
Password:
Updating installed gems
Updating snapshot
Fetching: credentials_manager-0.7.4.gem (100%)
Successfully installed credentials_manager-0.7.4
Fetching: commander-4.3.5.gem (100%)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/commander
```

**Comment by lacostej** [comment]
This appears to be an OSX 10.11 security change. See https://github.com/CocoaPods/CocoaPods/issues/3680

I wouldn't go for disabling rootless, but instead try making gem install the gems under /usr/local, which appears unaffected.

Maybe with

`````
gem update -n /usr/local/bin spaceship
`````

You may need to reinstall all gems for that version of ruby you are working with. No idea if gems can update a gem and change gem_dir at the same time.

Feel free to report.

**Comment by KrauseFx** [comment]
Uh, I'm sure this will cause a lot of problems once the release is public... :disappointed: 

@lacostej thanks for researching a solution. Should I add this to the FAQ?
@haemi Please let me know if that solves your problem :+1:

**Comment by helgetan** [comment]
@lacostej suggestion did not work on my side, anybody else ?

**Comment by KrauseFx** [comment]
@helgetan I assume you tried using `sudo`? If nothing works, you can always start using [rvm](https://rvm.io/) to have a "sudo-less" installation of `fastlane` and the other gems.

**Comment by chrism21** [comment]
@helgetan I was getting the exact same error with El Capitan. I fixed it by logging into the root user:

`sudo su`

You know you have logged into the root user if you see `sh-3.2# ` or something similar instead of your OS X username. Then run the install command:

`sudo gem install fastlane --verbose`

Then exit the root fast :)

`exit`

This should work with updates as well. If not, I would suggest removing fastlane entirely and then reinstalling using the above process.

**Comment by sandman4sure** [comment]
The suggestion from @lacostej worked for me.

**Comment by xfreebird** [comment]
I have no such issues on ```El Capitan```. May be because I did a clean install.

**Comment by entropid** [comment]
Installing using 
```
sudo gem install -n /usr/local/bin snapshot
```

did the trick for me. :)

**Comment by klemensz** [comment]
Is there an "official" solution for this problem?
I get `Operation not permitted - /usr/bin/sigh` etc. for all the tools. 
`sudo gem install -n /usr/local/bin sigh` will fix it, but I need to go through all the different tools?

**Comment by benjaminhorner** [comment]
@lacostej 's solution worked for me

**Comment by jcampbell05** [comment]
@klemensz The official solution would be to use something like `rbenv` or `rvm` to manage ruby. You can specify all of the tools you need via`bundler` it can install all of the for you in one command in a place where OS X won't complain.

Bundler: bundler.io

**Comment by mitchellporter** [comment]
@entropid Your solution was the only one that worked for me thanks.

**Comment by FBente** [comment]
Thanks @klemensz The only solution that worked for me to install fastlane on El Capitan. 
By installing RVM stable with ruby 
`\curl -sSL https://get.rvm.io | bash -s stable --ruby` 
follow the instruction at the end (with individual _username_)
`source /Users/username/.rvm/scripts/rvm` 
the installation of fastlane was finally possible. 
`sudo gem install fastlane --verbose`

**Comment by odemolliens** [comment]
The suggestion from @lacostej worked for me.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Comment by gtokman** [comment]
I am still getting the issue trying to install Fastlane on El Capitan 10.11.4. Same error message: 

```
Operation not permitted - /usr/bin/rougify
```

I have tried @entropid and @lacostej suggestions.

**Comment by gtokman** [comment]
I was able to find a solution from a different issue. 

```
sudo gem install -n /usr/local/bin fastlane 
```

**Comment by TKBurner** [comment]
Awesome @gtokman! Really glad to hear you are up and running 👍
