### ISSUE TITLE
undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by gran33** [fastlane/fastlane#5677]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

While using `watchbuild` I keep getting `undefined method `fetch' for nil:NilClass`

##### Complete output when running fastlane, including the stack trace and command used

```
[12:29:08]: Starting login with user 'user@domain.com'
[12:29:11]: Successfully logged in
[12:29:13]: undefined method `fetch' for nil:NilClass
[12:29:13]: Something failed... trying again to recover```
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

My command is:
```
bundle exec watchbuild --app_identifier="<APP_ID>"
```
### Environment
```
watchbuild v0.1.3
```
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
YES
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

**Comment by vpolouchkine** [comment]
As a first step, can you please try updating `watchbuild` to 0.1.4? Thanks!
