### ISSUE TITLE
Update Artifactory action with support to API key instead of username/password

### ISSUE THREAD

**Issue by anthonymonori** [fastlane/fastlane#5678]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I would like to be able to use an API key on the Artifactory action instead of username and password. This would be a more secure option instead of exposing a user/password to this use. Also our artifactory server is connected via AD and that is the only way to authenticate.

### Environment

fastlane version (run `fastlane -v`): `fastlane 1.99.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? `No`

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? `Yes`

**Comment by TKBurner** [comment]
Hi @anthonymonori Thanks for reaching out. Right now we'd consider this a good implementation for a plugin. The best way to add functionality to fastlane is to create a [plugin](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins). Please check out that link and let us know if you have any other questions 👍
