### ISSUE TITLE
fastlane init does not ask if app should be created in iTC / Dev Portal

### ISSUE THREAD

**Issue by ffittschen** [fastlane/fastlane#5679]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I just wanted to use `fastlane init` for a project, that is not intended to be published (it's a simple test app), and according to the [docs](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Guide.md#setting-up-fastlane) `fastlane init` will ask, if the app should be created in iTunes Connect / the Developer Portal, but this is not the case. It just gives me the option to confirm the values or enter them manually.

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane init
[12:53:48]: Detected iOS/Mac project in current directory...
[12:53:48]: This setup will help you get up and running in no time.
[12:53:48]: fastlane will check what tools you're already using and set up
[12:53:48]: the tool automatically for you. Have fun!
[12:53:48]: Created new folder './fastlane'.
Your Apple ID (e.g. fastlane@krausefx.com): <hidden>
[12:54:25]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[12:54:25]: Starting login with user '<hidden>'
Two Fator Authentication for account '<hidden>' is enabled
Please enter the 6 digit code: <hidden>
Requesting session...

+----------------+------------------------------------------------------------------------------------------+
|                                              Detected Values                                              |
+----------------+------------------------------------------------------------------------------------------+
| Apple ID       | <hidden>                                                                                 |
| App Name       | App                                                                                      |
| App Identifier |                                                                                          |
| Project        | /Users/ffittschen/Development/test-app/Test App/Test App.xcodeproj                       |
+----------------+------------------------------------------------------------------------------------------+

[12:55:24]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[12:55:24]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
Please confirm the above values (y/n)
n
App Identifier (com.krausefx.app): ^C
Cancelled... use --verbose to show the stack trace
```

### Environment

fastlane version (run `fastlane -v`): 
`fastlane 1.99.0`
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes ✅
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
`rbenv`

**Comment by TKBurner** [comment]
Hi @ffittschen Thanks for reaching out. Can you let me know what happens if you go through the manual setup? What happens if you use an invalid iTC account? Thanks!

**Comment by ffittschen** [comment]
Ahh I just tried to enter invalid iTC account details which brings me to the manual setup and after I entered the `App Identifier`, the init asked if the app should be created on iTC and the Developer Portal. Sorry, my fault... 
I was assuming it will be created automatically, because it said so 4 lines above.
I'm just cautious, because this once happened to me with an early version of `produce` and now I've got a test application stuck in my iTC account

**Comment by TKBurner** [comment]
@ffittschen No problem. Really glad to hear you are sorted. Hope that you have a wonderful weekend! 👍
