### ISSUE TITLE
Performing an action for all schemes within a lane

### ISSUE THREAD

**Issue by timothy-volvo** [fastlane/fastlane#5680]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
It would be nice to have the ability to execute an action for all schemes within a lane before proceeding to the next action.  For example to test with scan, then build with gym, then upload with pilot. As far as I can see the only current documented way to achieve this is using a bash wrapper script with --env arguments.

Ideally it would be better for fastlane to handle everything, so I created a Fastfile (see below) that creates caches for the ENV and the Actions.lane_context, swapping them in and out as needed.  Everything seems to work as expected, but was wondering if I could get some feedback regarding the risks of doing this or to see if there is an easier way to implement. 

### Configuration Files

Fastfile:
```ruby
fastlane_version "1.98.0"

default_platform :ios

platform :ios do
  before_all do
  
    schemeListArgIndex = ARGV.index { |arg| arg =~ /^schemes\:/}
    if (schemeListArgIndex)
      schemeList = ARGV[schemeListArgIndex].split(':')[1].split(',')
    else
      schemeList = Dir.glob(".scheme.*")
      schemeList.each { |c| c.gsub!(/\.scheme\./, '') }
    end
    
    globalENV = ENV.to_hash    
    schemeList.each do |schemeName|      
      schemeEnvFile = File.join(Fastlane::FastlaneFolder.path || "", ".schemeList.#{schemeName}")
      Dotenv.overload(schemeEnvFile)

      envCache[schemeName] = ENV.to_hash
      laneContextCache[schemeName] = Actions.lane_context.clone
      
      ENV.clear
      globalENV.each { |k, v| ENV[k] ||= v }
    end 
  end
  
  lane doSomething do |options|
    preAction
    
    execute_for_all_schemes { scan }
    execute_for_all_schemes { gym }
    execute_for_all_schemes { pilot }
    
    postAction
  end
end

def execute_for_all_schemes
    envCache.each do |schemeName, schemeENV|
    
      Actions.lane_context.clear
      laneContextCache[schemeName].each { |k, v| Actions.lane_context[k] = v }
      
      ENV.clear
      schemeName.each { |k, v| ENV[k] ||= v }
      
      yield 
      
      envCache[schemeName] = ENV.to_hash #update targets hash with any new variables
      laneContextCache[schemeName] = Actions.lane_context.clone
            
    end
end

def envCache
    @envCache ||= {}
end

def laneContextCache
    @laneContextCache ||= {}
end
  
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.99.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
Hi @timothy-volvo Thanks for reaching out. This is the right approach using ENV. Let me know if you have any other questions! 👍
