### ISSUE TITLE
Spaceship::Device.all doesn't fetch all devices

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5681]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

require "spaceship"

Spaceship.login()
Spaceship.select_team()

devices = Spaceship.device.all

the devices will not have all the devices on the device list, but only the active ones. The currently deactivated ones will not show, when it's expected them to show with the relevant status.
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

spaceship version (run `spaceship -v`):
spaceship doesn't have a -v option (enter interactive playground)

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
ruby installed with brew and linked. gems installed with sudo.

**Comment by TKBurner** [comment]
@lferro9000 Thanks for sharing this. I haven't seen any additional reports of this. Can you share a sample output so I can take a look? You can sanitize it. Thanks!

**Comment by lferro9000** [comment]
I'm running things on my local machine and on the jenkins agent that is running all iOS stuff.

There are way more devices on the target account, but they all follow this pattern.

Thing of notice:
- All the devices returned have: status="c", when there are also on the account devices deactivated (which i would suppose should return with a different status).
- There are some device model not returned correctly: iPods and iPhone 6s Plus are returning model as nil (when i'm sure there will be a model on it) - this can either be a limitation of the APIs or some filtering going on on spaceship.

I've noticed that on the expected tests there is some assumptions regarding the status be "c", but i couldn't dig that much as ruby is not exactly my best language.


Test code:

```
require "spaceship"

Spaceship.login()
Spaceship.select_team()

devices = Spaceship.device.all

puts devices
exit

```

Output:

```
<Spaceship::Portal::Device 
        id="xxxxx01", 
        name="iPad 2 Wi-Fi + 3G (GSM)", 
        udid="a1exxxxxb41", 
        platform="ios", 
        status="c", 
        model="iPad 2 Wi-Fi + 3G (GSM)", 
        device_type="ipad">
<Spaceship::Portal::Device 
        id="xxxxx02", 
        name="iPhone 4s", 
        udid="f5exxxxxb7e", 
        platform="ios", 
        status="c", 
        model="iPhone 4s", 
        device_type="iphone">
<Spaceship::Portal::Device 
        id="xxxxx03", 
        name="iPod Touch (Red)", 
        udid="24dxxxxxf6d", 
        platform="ios", 
        status="c", 
        model=nil, 
        device_type="ipod">
<Spaceship::Portal::Device 
        id="xxxxx04", 
        name="iPhone 6s Plus", 
        udid="60dxxxxxf7c", 
        platform="ios", 
        status="c", 
        model=nil, 
        device_type="iphone">
<Spaceship::Portal::Device 
        id="xxxxx05", 
        name="iPod 8.4", 
        udid="ddexxxxx102", 
        platform="ios", 
        status="c", 
        model=nil, 
        device_type="ipod">
```

**Comment by TKBurner** [comment]
Hi @lferro9000 Thanks for following up. Are you able to access the inactive devices by id if you try through a different command in `spaceship`? I'm trying to determine if this is a limitation of the API or a behavior of Fastlane. Thanks!

**Comment by lferro9000** [comment]
I will do some testing regarding this next week.

**Comment by lferro9000** [comment]
Have been a bit busy latelly... Will get back to this as soon as possible.

**Comment by TKBurner** [comment]
@lferro9000 Really appreciate the update. Let me know what you find out once you get a chance to check out the API's limitations! Hope you have a great weekend coming up 👍
