### ISSUE TITLE
Pilot distribute requiring extra metadata — where to set it?

### ISSUE THREAD

**Issue by nmonasterio** [fastlane/fastlane#5686]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

After uploading an app and submitting it for review via `deliver`, I'm trying to kick off internal testing via `pilot`. However, as soon as I do so with a command such as:

`pilot distribute -a com.foo.bar.awesomesauce -u me@example.com -w test_test_test`

I get the following error:

```
Error finding relevant GitHub issues: undefined method `map' for nil:NilClass

[!] The request could not be completed because:
    Beta App Description is required. The phone number is missing. The email must be in the format: contact@example.com. The email is required. Beta App Description is required. The email must be in the format: contact@example.com. The email is required. The phone number is missing. Validation errors
```

The exception is self-evident, and hopping into iTunes Connect evidently shows the issue: Data is not there.

So, that begs the question: Can I upload any of that data through either `deliver` or `pilot`? If so, where? (I see it's available through `spaceship` [here](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/iTunesConnect.md#builds), I believe, but I wasn't sure if anywhere else.)

Thanks so much!

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? Yes, `rvm`

**Comment by vpolouchkine** [comment]
Please take a look at the following section of the `deliver` documentation: https://github.com/fastlane/fastlane/tree/master/deliver#usage

**Comment by KrauseFx** [comment]
Currently you can't provide all information from pilot as far as I know. Could you fill in the basic metadata manually on iTunes Connect and then try using `pilot` again?

**Comment by joeydong** [comment]
> Currently you can't provide all information from pilot as far as I know. Could you fill in the basic metadata manually on iTunes Connect and then try using pilot again?

I've seen iTC drop the beta app description between versions for no reason. Is making this available through `pilot distribute` just a matter of piping through the `spaceship` parameters?

**Comment by ikovalisko** [comment]
I have a similar issue. `pilot` fails to distribute a fresh build to External testers with the following error: 
```
Beta App Description is required. Beta App Description is required. Validation errors
```
However, the Beta App Description is filled in. When I opened build details I found there *two* localisations for the same language:
![screen shot 2016-08-23 at 20 03 06](https://cloud.githubusercontent.com/assets/555642/17901703/3f03bc06-696d-11e6-9974-12a0e8d43258.png)
Both have a correct changelog, but one is missing Beta App Description. I haven't found any way to remove the duplicated localisation. Any ideas?

**Comment by joeydong** [comment]
> Both have a correct changelog, but one is missing Beta App Description. I haven't found any way to remove the duplicated localisation. Any ideas?

Oh man that looks super broken. Maybe play around with it until you can access the red "Delete" button. What if you add another localization temporarily? I would also try playing with the HTML to enable the button and see what happens.

**Comment by TKBurner** [comment]
@ikovalisko Let me know how it goes! Is this affecting the whole app or just a specific version?

Thanks!

**Comment by ikovalisko** [comment]
Seems like adding English localization for Testflight builds (on the web) removes the duplicated Norwegian. I think that was an issue in iTunesConnect creating these duplicates. I haven't investigated it deeper as it worked for me and I could proceed with ongoing work.

**Comment by TKBurner** [comment]
@ikovalisko Very interesting. Thanks for sharing.
