### ISSUE TITLE
Deliver creates default metadata/screenshot folder to ./fastlane not to ./.fastlane

### ISSUE THREAD

**Issue by chreno** [fastlane/fastlane#5696]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Conditions:
1. I use fastlane from the hidden ".fastlane" folder.
2. I use deliver from fastlane using skip_screenshots: true.
3. I don't specify a custom path for screenshots.

If I run it, deliver creates the empty screenshots folder to ./fastlane/screenshots and not to ./.fastlane/screenshots.

So I will have 2 fastlane folders:
1. ./.fastlane: with all the necessary files
2. ./fastlane: with only the empty screenshots folder

On the next run I get the following message:
`Could not find fastlane in current directory. Would you like to set it up?
(y/n)`

Because fastlane thinks that it should use the - actually empty - ./fastlane folder.

The error might be around here:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/detect_values.rb#L35

We might also consider not to create the screenshots folder if skip_screenshots: true.

Thanks!

**Comment by KrauseFx** [comment]
Hey @chreno, nice catch, that's definitely a bug that needs to be fixed. You found the right line of the source code. 

Maybe we should move https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/fastlane_folder.rb#L6 to fastlane_core, so that it can be used across the tools, what do you think?

**Comment by chreno** [comment]
Hi @KrauseFx, yeah, moving it to fastlane_core and use it as a single source of truth everywhere seems to be the right way!

**Comment by TKBurner** [comment]
Hi @chreno Are you interested in submitting a PR? We'd love to see you contributing to our project! 👍 💯 💯

**Comment by chreno** [comment]
Hi @TKBurner Sure, I'm happy to contribute! Will try to apply the fix in the upcoming days.

**Comment by KrauseFx** [comment]
Cool, thanks @chreno. Let us know if you need any help getting started 👍
