### ISSUE TITLE
Deliver - select previously uploaded build without submitting to review

### ISSUE THREAD

**Issue by chreno** [fastlane/fastlane#5697]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm not sure this is supported now by deliver. Use-case:
1. I use pilot to upload the IPA to TestFlight
2. I use deliver to create the new version and upload the metadata
3. I would also like to select the build uploaded previously by pilot, but I don't want to automatically send it to review (I would like to keep it as a manual step).

As I can see calling select_build is only possible through submit for review:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/submit_for_review.rb#L30

Could we somehow support this?
Thanks!

**Comment by KrauseFx** [comment]
Sorry that's currently not supported, however you can build your own custom solution using [spaceship](https://spaceship.airforce) 👍

**Comment by chreno** [comment]
Hi @KrauseFx, yep, thanks! 👍

What do you think is there any chance that we will support this in the future? Is there any specific reason why selecting the build and submitting to review should be coupled?

How about something like this? https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/runner.rb#L30
`
      UI.success("Finished the upload to iTunes Connect")

      **select_build if options[:build_number]**
      submit_for_review if options[:submit_for_review]
    end
`
And here just call:
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/submit_for_review.rb#L30

(Or also outsource the select_build method to a separate ruby file.)

What do you think?
Many thanks!

**Comment by TKBurner** [comment]
Hi @chreno If you want to work on something locally and then make a PR we'd definitely take a look. Thanks!
