### ISSUE TITLE
'add_git_tag' fails if you reset the build number to 1 with version changes

### ISSUE THREAD

**Issue by sareninden** [fastlane/fastlane#5703]
### New Issue Checklist

- [ Check ] Updated fastlane to the latest version
- [ Check ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Apple allows you to set the build number to 0 (or any other value) after increasing the version number.

So you have version 1.3.1, build 8 uploaded.
You increase the version to 1.3.2 and set the build back to 1.

This is a valid condition for iTunes connect. Only if you than add a git tag with the command 'add_git_tag' it will fail if in example a git tag already exists for 'build 1'.

This can be solved by adding the version number also to the git tag by default.

Tag will than be something like 'builds/iosbeta/1.3.2/3' instead of 'builds/iosbeta/3'

##### Complete output when running fastlane, including the stack trace and command used

[11:20:12]: Exit status of command 'git tag -am builds/iosbeta/3\ \(fastlane\) 'builds/iosbeta/3'' was 128 instead of 0.
fatal: tag 'builds/iosbeta/3' already exists

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by sareninden** [comment]
I did not add my fast files since they seem not to be relevant in this case.

Kind regards

Saren

**Comment by sareninden** [comment]
I did not add my fast files since they seem not to be relevant in this case.

Kind regards

Saren

**Comment by sareninden** [comment]
Possible solution might also be to include it in your command like

Example:
add_git_tag(prefix: get_version_number + "/", build_number: get_build_number)

But an option like 'include_version_number' or something like that would be prettier I think.

**Comment by vpolouchkine** [comment]
Thanks for the report. Are you able to test your proposed workaround?

**Comment by sareninden** [comment]
I'm terrible sorry for the late response. Yes it works like this.
Thank you for your reply.
