### ISSUE TITLE
reset_simulator action doesn't support iOS list

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#5705]
I want to make it like snapshot command:
`snapshot reset_simulators -i 9.3,10.0`

**Comment by TKBurner** [comment]
Hi @yakimant Thanks for reaching out. Can you let me know if the parameter: 

```
 --erase_simulator [VALUE] Enabling this option will automatically erase the simulator before running
the application (SNAPSHOT_ERASE_SIMULATOR)
```

Solves your use case?
