### ISSUE TITLE
Sigh with provisioning profiles with different specs

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5707]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

On the development portal, create one app without any entitlements.

Create one provisioning profile for it.

Change the entitlements (to add for instance notifications).

Create a different provisioning profile for it.

Run sigh:

sigh download_all

You get:
1 provisioning profile only.

You should get:
2 provisioning profile.

The problem?
When saving provisioning profiles, the file is saved regardless of be already existing or not, which means that in this case, the first provisioning profile (without any entitlement) gets overwriten by the one with notifications entitlement.

How to solve this?
1. When starting sigh, get the timestamp.
2. Before saving a file, check if the timestamp is more recent then the starting timestamp, if so, add an order integer after the filename and before the .mobileprovision
3. x
4. profit
##### Complete output when running fastlane, including the stack trace and command used

```
AdHoc_com.example.myapp.mobileprovision
```
### Environment

sigh version (run `sigh -v`):
sigh 1.9.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Just Apple ruby overwriten with brew link --overwrite ruby, and gems global installed.

**Comment by lferro9000** [comment]
No, it is not related with code sign, it is related with how to download multiple provisioning profiles for the same app when they all get the same name.

**Comment by TKBurner** [comment]
@lferro9000 Thanks for reaching out about this. I have marked it as help wanted in case anyone wants to submit a PR around your suggestion. Hope that you have a wonderful day! 👍

**Comment by lferro9000** [comment]
This has to do on how the provisioning profiles are sorted in the code (both in terms of filename, and if they are App Store or Ad Hoc).

In the end i solved this by using spaceship (but would be nice for a more robust solution out of the box on sigh):

https://github.com/fastlane/fastlane/issues/5754#issuecomment-241021283

**Comment by TKBurner** [comment]
@lferro9000 Thanks! We'll take a look at this 👍
