### ISSUE TITLE
Cannot get use_clang_report_name to work in scan

### ISSUE THREAD

**Issue by Stoff81** [fastlane/fastlane#5709]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Cannot get `use_clang_report_name` to work in scan.
There is very little docs on this flag, I am trying to use it to feed into OCLint
From my scan output I can see that things are configured correctly, my output dir is defined. This is working as I get my junit and html reports going there, just not my `compile_commands.json`which from reading all the docs is what needs to be fed into OCLint.

Please help

##### Complete output when running fastlane, including the stack trace and command used

```
+-----------------------+--------------------------------------------------------------------------+
|                                     Summary for scan 0.11.0                                      |
+-----------------------+--------------------------------------------------------------------------+
| workspace             | <XXX>.xcworkspace                                                 |
| scheme                | <XXX>                                                                |
| clean                 | true                                                                     |
| output_directory      | output/scan                                                              |
| use_clang_report_name | true                                                                     |
| derived_data_path     | <XXX> |
| code_coverage         | false                                                                    |
| address_sanitizer     | false                                                                    |
| skip_build            | false                                                                    |
| output_types          | html,junit                                                               |
| buildlog_path         | ~/Library/Logs/scan                                                      |
| open_report           | false                                                                    |
| skip_slack            | false                                                                    |
| slack_only_on_failure | false                                                                    |
| fail_build            | true                                                                     |
+-----------------------+--------------------------------------------------------------------------+
```

### Configuration Files

Fastfile:
```ruby
scan(
      workspace: "<XXX>",
      scheme: "<XXX>",
      clean: true,
      output_directory: "output/scan",
      use_clang_report_name: true
    )
```

### Environment

fastlane 1.100.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? .rvm/rubies/ruby-2.2.1/bin/fastlane

**Comment by Stoff81** [comment]
Sorry I have just seen this PR, will try now! https://github.com/fastlane/fastlane/pull/4841

**Comment by Stoff81** [comment]
Ok its not outputting as expected! Great! I will try and make a PR which explains the workflow for future users

**Comment by TKBurner** [comment]
@Stoff81 Awesome! Thanks for considering a PR. We'd be happy to work with you if you are interested in improving the usability of the flag. Thanks!

**Comment by Stoff81** [comment]
Hey @TKBurner, it turns out that scan can already output the commands.json that is required for OCLint, so that great news. I will still consider creating a PR to update the docs when I can find the time.

**Comment by TKBurner** [comment]
@Stoff81 Thanks for following up. Really glad you found what you were looking for. I'd love to see a docs update 👍
