### ISSUE TITLE
allow scan to complete snapshot procedure on failed tests

### ISSUE THREAD

**Issue by bartpowers** [fastlane/fastlane#5727]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
It would be nice to a bit or somewhere where I can tell snap I still want it to save the corresponding snapshot files for failed tests.  Another user commeted about this, but they were asking for a separate solution.  I already overrode the recordFailureWithDescription method within xctestcase and tried to use snapshot in there.  It hits but the file is never generated since its considered a failure

Its great to see what the app looked like right before it failed.  

Let me know where I can look or if this is possible with the way you have it parsing the plist files.  

Thank you
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
Hi @bartpowers Great to hear from you! Right now as you noted this isn't possible, but it's an interesting idea. I don't see us implementing this internally but we'd look at a PR.

Thanks!
