### ISSUE TITLE
Spaceship / Sigh marking all provisioning profiles as Adhoc

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5729]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Spaceship / sigh is updating the profiles with devices even for Apple Store Distribution provisioning profiles.

When using "sigh download_all" the above provisioning profile is being saved with the name of:

AdHoc_com.example.myapp.mobileprovision

When it should have the name of:

Store_com.example.myapp.mobileprovision

Because ALL provisioning profiles are marked on the datastructure as "Adhoc" even when they are in fact related some are development, others adhoc and others even App Store distribution ones.
##### Test Code used

```
require 'spaceship'

Spaceship.login()
Spaceship.select_team()

profiles = Array.new
#profiles += Spaceship.provisioning_profile.development.all
#profiles += Spaceship.provisioning_profile.ad_hoc.all
profiles += Spaceship.provisioning_profile.all

result = ""

profiles.each do |profile|
  result << profile.to_s + "\n"
end
File.write("results.txt", result)
```
##### Output generated

```
<Spaceship::Portal::ProvisioningProfile::AdHoc 
    id="Pxxxxxx9", 
    uuid="ef6xxxxxx497", 
    expires=#<DateTime: xxx-oneday-xxx>, 
    distribution_method="adhoc", 
    name="MyApp Store", 
    status="Active", 
    type="iOS Distribution", 
    version="2", 
    platform="ios", 
    managing_app=nil, 
    app=<Spaceship::Portal::App 
        app_id="Cxxxxxx8", 
        name="xxx-myapp-xxx", 
        platform="ios", 
        prefix="Vxxxxxx8", 
        bundle_id="com.example.myapp", 
        is_wildcard=false, 
        features={"push"=>false, "iCloud"=>false, "inAppPurchase"=>true, "gameCenter"=>true, "LPLF93JG7M"=>false, "passbook"=>false, "IAD53UNK2F"=>false, "V66P55NK2I"=>false, "dataProtection"=>"", "SKC3T5S89Y"=>false, "APG3427HIY"=>false, "HK421J6T7P"=>false, "homeKit"=>false, "WC421J6T7P"=>true, "cloudKitVersion"=>1}, 
        enabled_features=["WC421J6T7P", "gameCenter", "inAppPurchase"], 
        dev_push_enabled=false, 
        prod_push_enabled=false, 
        app_groups_count=nil, 
        cloud_containers_count=nil, 
        identifiers_count=nil>, 
    certificates=[<Spaceship::Portal::Certificate::Production 
        id="XxxxxxM", 
        name="iOS Distribution", 
        status=nil, 
        created=nil, 
        expires=#<DateTime: xxx-oneday-xxx>, 
        owner_type="team", 
        owner_name=nil, 
        owner_id=nil, 
        type_display_id="RxxxxxxO", 
        can_download=nil>], 
    devices=[<Spaceship::Portal::Device 
        id="8xxxxxx9", 
        name="iPad Mini", 
        udid="fb6xxxxx3f0", 
        platform="ios", 
        status="c", 
        model="iPad mini (Model A1455)", 
        device_type="ipad">, <Spaceship::Portal::Device 
        id="3xxxxxxN", 
        name="iPhone 4S", 
        udid="d86xxxxxx79f", 
        platform="ios", 
        status="c", 
        model="iPhone 4s", 
        device_type="iphone">, 
        [... more devices ...], 
        <Spaceship::Portal::Device 
        id="Bxxxxx3", 
        name="AppleWatch", 
        udid="5e7xxxxxxf43", 
        platform="ios", 
        status="c", 
        model="Apple Watch 42mm", 
        device_type="watch">,
        <Spaceship::Portal::Device 
        id="ZxxxxxxK", 
        name="iPhone 6s", 
        udid="028xxxxxx129", 
        platform="ios", 
        status="c", 
        model="iPhone 6s Plus", 
        device_type="iphone">]>
```
### Environment

Latest sigh, spaceship and fastlane with ruby updated with brew, and gems updated as global.

**Comment by vpolouchkine** [comment]
Thanks for the report, we'll take a look.

**Comment by lferro9000** [comment]
The only difference between Ad Hoc and App Store distribution provisioning profiles is that the first has devices, and the other doesn't.

So if you have both, only one gets written on the local machine when downloading them.

I solved it by using spaceship and working around a way to differenciate those profiles in a more deterministic way as it can be seen on this ticket:

https://github.com/fastlane/fastlane/issues/5754#issuecomment-241021283

The other part of the problem is the identification of the model of the devices, which i didn't investigated further for the moment.

**Comment by vpolouchkine** [comment]
Thanks for the followup and providing more details!

**Comment by KrauseFx** [comment]
Is this issue still relevant? 👍

**Comment by rgarib** [comment]
Yes, it is

**Comment by TKBurner** [comment]
@rgarib Thanks for following up. Can you provide exact repro steps for this. I'd love to look into it. Thanks!
