### ISSUE TITLE
Getting latest build number from hockey

### ISSUE THREAD

**Issue by pahnev** [fastlane/fastlane#5730]
Hi, I was trying to look if this was possible currently and seems like it isn't. Something along the lines of current `latest_testflight_build_number`.

Since HockeyApp basically [requires to increase the build number](https://support.hockeyapp.net/discussions/problems/39011-why-is-the-latest-version-only-looking-at-build-number), would this be something you could consider? 
Or is this even possible with their APIs?

**Comment by vpolouchkine** [comment]
I don't believe this is currently possible using this action; keeping this open for upvotes.

**Comment by nikolaykasyanov** [comment]
I have something like that: https://gist.github.com/nikolaykasyanov/fa9f727a2659450f49825a238546ea8b

@vpolouchkine why do you think it isn't possible?

**Comment by TKBurner** [comment]
@nikolaykasyanov Thanks for stepping in! Are you interested in adding this as a plugin so users can more easily adopt it? Thanks!

**Comment by nikolaykasyanov** [comment]
@TKBurner sure I'll try, have to learn how to do plugins first though.

**Comment by TKBurner** [comment]
@nikolaykasyanov Very cool! 👍 💯

**Comment by pahnev** [comment]
I turned @nikolaykasyanov 's gist into plugin. https://github.com/pahnev/fastlane-plugin-latest_hockey_build_number
I guess it needs some tests before it can be added to the main plugin repo, but this works for me now.

**Comment by TKBurner** [comment]
@pahnev Check out this article for publishing your plugin https://docs.fastlane.tools/plugins/CreatePlugin/#rubygems

**Comment by pahnev** [comment]
And I see @tpalmer got this merged as official plugin https://github.com/tpalmer/fastlane-plugin-latest_hockeyapp_version_number 👍
