### ISSUE TITLE
How to delete Devices

### ISSUE THREAD

**Issue by zhouzerong** [fastlane/fastlane#5734]
The Spaceship can only register a new device,but  how can i delete one???

**Comment by TKBurner** [comment]
Hi @zhouzerong Thanks for reaching out. Can you let me know if you are trying to add a tester or what specifically? Thanks!

**Comment by zhouzerong** [comment]
hi @TKBurner  i want to delete some devies that are not used.The class of Device only has “create” method， i hasn't find method like "delete"

**Comment by zhouzerong** [comment]
@TKBurner   if i have some apple account and i has added devices to every account, but now, i want to delete some ones, if i logined every account to do it, that is too much trouble,can you tell me  how to add a "delete" method to class of Device, Thanks!

**Comment by TKBurner** [comment]
@zhouzerong Thanks for following up. I don't believe this is currently supported in Spaceship.

Checkout the bottom of this page for the full documentation on testers, https://github.com/fastlane/fastlane/blob/master/spaceship/docs/iTunesConnect.md

Thanks!

**Comment by zhouzerong** [comment]
@TKBurner  Yeah，you mean the "delete" method is not supported on class of Device!   But i want to now when can you add this method ? @KrauseFx

**Comment by TKBurner** [comment]
Hi @zhouzerong Thanks for following up. I marked this as a feature request and labeled it to see if any one is interested in submitting a PR. Thanks!

**Comment by VicHnp** [comment]
Hi, i also want this feature, sometimes when we test ,you need to add a large of number device,but we need manually remove device when test complete. Thanks you so much if you could support this feature.

**Comment by fafu2008** [comment]
I hope add this feature
