### ISSUE TITLE
Plugin installation wizard

### ISSUE THREAD

**Issue by pajapro** [fastlane/fastlane#5736]
I work on [`fastlane-plugin-changelog`](https://github.com/pajapro/fastlane-plugin-changelog) and would like to perform a set of actions while this plugin is being installed. 

For example [check whether CHANGELOG.md file is located in the project directory](https://github.com/pajapro/fastlane-plugin-changelog/issues/1), if not ask used if he/she wants to generate one etc. 

Does the current plugin ecosystem enable to do this? If so, could you please point me to resources? Current [documentation](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md) covers only the basic stuff.

**Comment by TKBurner** [comment]
Hi @pajapro Right now the plugin install doesn't support this. Since they are basically ruby gems, it should be possible in some way to run shell commands during install. Thanks!

**Comment by pajapro** [comment]
Hi @TKBurner, based on your answer:
> it should be possible in some way to run shell commands during install. 

I looked a bit around and came up with the following [solution](https://github.com/pajapro/fastlane-plugin-changelog/commit/6a3db9df0f92d64e6d8af892af2d359ba33c09f8) to implement the "installation wizard". It works, but would you mind having a look at that code anyway to see if this is the right place to do it or it won't potentially impact other parts?

**Comment by TKBurner** [comment]
Looks good to me @pajapro! However, this might make it so fastlane has to be attended during run. You should make sure it can run without human attention.

Thanks!

**Comment by pajapro** [comment]
> However, this might make it so fastlane has to be attended during run. You should make sure it can run without human attention.

I didn't get that, could you please elaborate on that? How would I ensure that fastlane isn't needed during run?

**Comment by TKBurner** [comment]
Hi @pajapro Thanks for following up. This means that you won't be able to add this install step as an automated step. Otherwise should work 100% as expected. Thanks!
