### ISSUE TITLE
Scan should recognize all TestSummaries.plist files, not just the last one.

### ISSUE THREAD

**Issue by lyricsboy** [fastlane/fastlane#5739]
As of [this commit](https://github.com/fastlane/fastlane/commit/497ca7a420e33eab38f3120c826ec7ce577aa064), scan now supports stuffing the name of the "last" TestSummaries.plist file that was created during the test run into `SCAN_GENERATED_PLIST_FILE`. This works fine if you have only one such file.

In my use of scan, I set `SCAN_DESTINATIONS` to have it run on two simulators. Each of these will trigger a separate test run, and each of those will generate a separate TestSummaries.plist file.

It would be great if all of the TestSummaries.plist filenames could be put into a (separate?) variable, and thus be accessible to e.g. trainer.

Without that, compared to `xcpretty`'s JUnit report generation, we're missing half our test report.

**Comment by KrauseFx** [comment]
Interesting - I didn't know you could get 2 files by passing multiple simulators. 

If you want to fix this, let's add another `SharedValue`, named `SCAN_GENERATED_PLIST_FILES` containing an array and not just one path.
The one path is used in [trainer](https://github.com/KrauseFx/trainer).

Let me know if you need any help 👍

**Comment by lyricsboy** [comment]
OK cool, that sounds like just what I was thinking. Then we can update trainer too :)

**Comment by KrauseFx** [comment]
Awesome, thanks @lyricsboy 👍 I don't know about trainer, I think there was a reason why I only passed one path

**Comment by lyricsboy** [comment]
I was hoping we could get it to aggregate all of them into a single JUnit report. Based on [this schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) it seems like it would be as simple as appending more `testsuite` elements based on the combined TestSummaries files. You could use a `properties` element within the `testsuite` to include various distinct things from the `RunDestinations` key in the Plist. Perhaps also augment the `testsuite` name with the name of the `RunDestination`.

**Comment by KrauseFx** [comment]
Sounds great, thanks for looking into this @lyricsboy 👍

**Comment by mfurtak** [comment]
Merged #5740 to address this! 🚀
