### ISSUE TITLE
Environment variable not set for fastlane match

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#5752]
I have observed that match is not setting the environment variable.

+----------------------+----------------------------------------+
|                Installed Provisioning Profile                 |
+----------------------+----------------------------------------+
| App Identifier       | myapp.test.prod            |
| Type                 | adhoc                                  |
| UUID                 | b99338ae-cc51-41ad-84ac-49f392ad05e3   |

Now on command line if I enter:
echo $(sigh_myapp.test.prod_adhoc) I don't get the UUID.

**Comment by KrauseFx** [comment]
It's only being set in the context of the fastlane process. There is no way for a process to pass an environment variable to its parent process, so make sure to run both `match` and `gym` from within fastlane 👍

**Comment by santoshshetty2612** [comment]
Thanks a lot Felix for your quick reply. I have couple of queries.

1. Can I define the name of the provision profile created in match? sigh allows us to specific the name. But don't see this option in match.

2. Am using Jenkins to automate the build and I wanted to use fastlane/match for only creating the provisioning profiles. Am maintaining few environment variables inside jenkins like lastbuildnumber, etc. and hence am using Jenkins xcode plugin rather than gym.

Am selecting the profile at run time in Jenkins using PlistBuddy and passing to Xcode:
 PP_PATH="${WORKSPACE}/Profiles/myapp_${COUNTRYCODE}_${XCODE_PROFILE_ENV}_${1}.mobileprovision"

PP_UUID=$(/usr/libexec/PlistBuddy -c 'Print UUID' /dev/stdin <<< $(security cms -k "${KEYCHAIN_PATH}" -D -i "${PP_PATH}"))

where ${1}.mobileprovision is my profile and its has a fix value eg: us_mypp_profile. 
When the profile is updated, the profile file is overwritten manually by me and everything works fine on Jenkins. 

With match am having difficulty fetching the UUID as the profile names are auto generated plus cant access the environment variables.

**Comment by santoshshetty2612** [comment]
Thanks KrauseFx , 

I have successfully set up fastlane with jenkins. Thanks for all the support.

Thanks and Regards,
Santosh

**Comment by ruslanfutureuniverse** [comment]
@KrauseFx But is there a way to read env var from match and pass it outside? I need it to set up Unreal Engine project on Jenkins.

**Comment by ruslanfutureuniverse** [comment]
@santoshshetty2612 how did you manage to pass env vars from Match to Jenkins shell?

**Comment by santoshshetty2612** [comment]
Hi @ruslanfutureuniverse  I passed the environment variables from Jenkins to fastlane.
I copied the Jenkins environment variables into .env file and copied it into fastlane folder.

When fastlane runs, it will read the value from this .env file.

**Comment by ruslanfutureuniverse** [comment]
@santoshshetty2612 ah yeah, understand. But are there any way to pass _match_  job results to env var? If new profile was generated here, I need to pass it to Jenkins script.

**Comment by santoshshetty2612** [comment]
@ruslanfutureuniverse 
Consider your project Folder -> fastlane
Inside which you have fastfile. 

Now you can run the fastlane you can write the variables in a file (example fastline.properties)

In Jenkins, you can read this file and load it using the inject environment variable step passing the path to fastline.properties.

**Comment by ruslanfutureuniverse** [comment]
@santoshshetty2612 wow. I see...
Could you please write a snippet, how to write _match_ values to file and read from it?
