### ISSUE TITLE
The 2nd step in the README

### ISSUE THREAD

**Issue by snap9** [fastlane/fastlane#5753]
I have a question about the 2nd setup step in the [README](https://github.com/fastlane/fastlane/tree/master/match#readme):

_Optional: Create a new, shared Apple Developer Portal account, something like office@company.com that will be shared across your team from now on (for more information visit codesigning.guide)_

In what sense is this step optional? Is it optional in the sense that bob@company.com and john@company.com (two separate apple IDs) can work with the same certificates/profiles through fastlane?

**Comment by KrauseFx** [comment]
You should use one Apple account for your whole team if you want to use match. Check out [codesigning.guide](https://codesigning.guide) for more information 👍

**Comment by snap9** [comment]
Thanks for the swift reply and thanks for making fastlane! Follow up questions,

1. Why is one Apple account needed? Is it because a certificate or profile (or both) is tied to a single Apple account?
2. Why was that step marked as an optional when in fact it's necessary?

**Comment by KrauseFx** [comment]
1) Because you share the same certificates and profiles across your team, instead of everyone having their own set of profiles

2) You can also just use a person's account, and share it across the team. The README just recommends having a separate one, since this way it's not tied to one person 👍
