### ISSUE TITLE
Spaceship handling of old xcode managed profiles

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#5754]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

On one of my accounts, i've some very old provisioning profiles that where created by one of the older versions of xcode.

Instead of having a "managed by app" field, they have a patterned name with:

XC: *

Where \* is either \* for all bundles, or a specific bundle_id.

Currently i exclude those by checking the profile name.

Probably not worthy to spend time solving this.
##### test code

``` ruby
if !profile.name.include? "XC:"
  # your code here
end 
```
### Environment

Latest version of spaceship with ruby and all gems updated.

**Comment by KrauseFx** [comment]
So you're suggesting it should skip those? Is there any way to get this kind of profiles today, or just when you have old ones?

**Comment by lferro9000** [comment]
I don't think one can "get" them today as i believe those where created on xcode 5.x long time ago (one can simulate them by changing their names, but i don't think there is usefulness in doing much regarding backward compatibility).

I solved this by skipping them by using spaceship to just parse those that didn't matched those signatures:

```ruby
base_dir = "/tmp"
profiles = Spaceship.provisioning_profile.all
profiles.each do |profile|
  name = profile.name
  type = profile.type
  bundle = profile.app.bundle_id

  mode = "AdHoc"
  if type == "iOS Distribution"
    mode = "Store"
  end

  if profile.devices.count > 0
    mode = "AdHoc"
  end


filename = base_dir + "/" + mode + "_" + bundle + "_" + name.downcase.split.join('_') + ".mobileprovision"
  if !(profile.name.include? "XC:")
        File.open(filename, "wb") do |f|
      f.write(profile.download)
    end
  end
end
```
Of notice, i'm handling the "mode" somewhat differently. Basically there is no difference from a distribution to App Store and a distribution Ad Hoc, apart from the fact that the provisioning profile on App Store can't have any device associated.

When updating the provisioning profiles (or creating them) i append the word "Store" to the name, if they are to be for distribution to app store, making it easy to distinguish between an Ad Hoc without devices and an App Store that actually can't have any. That way i avoid adding devices to App Store distribution provisioning profiles.

The way sigh handles filenames when downloading the provisioning profiles is conducent to file overwrite if you have an ad hoc / app store provisioning profile for the same app (they get the same name on sigh).
