### ISSUE TITLE
Play a sound when fastlane completes

### ISSUE THREAD

**Issue by TheLionKing1** [fastlane/fastlane#5755]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to be able to play a sound when a process finishes... I think this needs to be added to the fastlane code? It would be super beneficial as I like to multi-task :+1:  Thank you

```
afplay /System/Library/Sounds/Funk.aiff
say done
```

### Environment

fastlane version (run `fastlane -v`): 1.100.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by jcampbell05** [comment]
A couple of plugins already exist for this for fastlane.

**Comment by TheLionKing1** [comment]
could you link just one to me, please.

**Comment by jcampbell05** [comment]
https://rubygems.org/gems/fastlane-plugin-tunes
