### ISSUE TITLE
Can't download dSYM files for tvOS builds

### ISSUE THREAD

**Issue by hannseman** [fastlane/fastlane#5767]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running `download_dsyms` for a processed tvOS-build no dSYM files can be found. The dSYM files are downloadable through iTunes Connect so they should be available.  I've tried submitting new builds so it's not contained to a specific build number. I've also tried waiting 24 hours after a build finished processing. The error message `No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet` is still returned.

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane refresh_dsyms
+------------------------+---------+--------------------+
|                     Used plugins                      |
+------------------------+---------+--------------------+
| Plugin                 | Version | Action             |
+------------------------+---------+--------------------+
| fastlane-plugin-sentry | 0.1.0   | sentry_upload_dsym |
+------------------------+---------+--------------------+

[10:40:53]: -------------------------------------------------
[10:40:53]: --- Step: Verifying required fastlane version ---
[10:40:53]: -------------------------------------------------
[10:40:53]: fastlane version valid
[10:40:53]: ------------------------------
[10:40:53]: --- Step: default_platform ---
[10:40:53]: ------------------------------
[10:40:53]: Driving the lane 'ios refresh_dsyms' 🚀
[10:40:53]: ----------------------------
[10:40:53]: --- Step: download_dsyms ---
[10:40:53]: ----------------------------
[10:40:53]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username for iTunes Connect: appleid@example.com
[10:41:01]: Login to iTunes Connect (appleid@example.com)
[10:41:09]: Login successful
[10:41:09]: Looking for dSYM files for com.example.App
[10:41:09]: No dSYM files found on iTunes Connect - this usually happens when no recompling happened yet

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | download_dsyms                      | 16          |
+------+-------------------------------------+-------------+

[10:41:09]: fastlane.tools finished successfully 🎉
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
fastlane_version "1.81.0"

default_platform :ios

platform :ios do

  desc "Upload dsyms to Sentry"
  desc "Should be done after iTunes Connect has finished processing the latest build"
  lane :refresh_dsyms do |options|
    download_dsyms
  end
end
```

### Environment

fastlane version (run `fastlane -v`): `fastlane 1.100.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by vpolouchkine** [comment]
Thanks for the report!

**Comment by mdlci** [comment]
Please try `download_dsyms(platform: "appletvos")`

**Comment by TKBurner** [comment]
@hannseman Did you get a chance to try out that workaround? Thanks!

**Comment by hannseman** [comment]
Yes! It worked just fine when specifying the platform as `appletvos`. Thank you!

**Comment by TKBurner** [comment]
@hannseman Awesome! Really glad to hear that worked. Hope you have a wonderful day! 👍
