### ISSUE TITLE
Default screenshot for all localize

### ISSUE THREAD

**Issue by lifez** [fastlane/fastlane#5771]
### Issue Description

How i can upload screenshot just only for en-US  then use it for all localize that i active in metadata

**Comment by jcampbell05** [comment]
@lifez  you should look at the new screenshot manager on iTunes Connect, I believe it will handle it for you. This is out of fastlane's scope.

**Comment by KrauseFx** [comment]
As far as I know, if you only provide iPhone 6 Plus screenshots to deliver/fastlane, it will automatically use the same screenshots for all device sizes 👍

**Comment by lifez** [comment]
@jcampbell05 On itune connect it need to check checkbox on language that need to use en-US screenshot

I think delivery shoud do it instead ?

**Comment by lifez** [comment]
@KrauseFx On itune connect it need to check checkbox on language that need to use en-US screenshot

I think delivery should do this for provide default screenshot ? ?

**Comment by KrauseFx** [comment]
@lifez sorry, I'm not sure I understand the question

**Comment by lifez** [comment]
@KrauseFx Sometime I want to use en-US screenshot apply to all localize that i active

Currently workflow is -> upload en-US screenshot by deliver and check to use en-US screenshot for each of localize in iTuneConnect website

**Comment by KrauseFx** [comment]
Yeah, you'll have to do that using iTunes Connect, deliver doesn't currently do that for you
