### ISSUE TITLE
Prompt command doesn't wait user input on Jenkins

### ISSUE THREAD

**Issue by Mohab1** [fastlane/fastlane#5773]
I'm having a problem with fastlane command prompt, waiting user input it works fine when I run it on my local machine but it doesn't when I execute shell script from Jenkins 

Here is the part inside fastfile that reads user input
```
  changelog = prompt(text: "Changelog: ")
  contents = "iOS\n" +"Live\n" + changelog
  print contents
```

Here is how I call fastlane from Jenkins
```
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export FASTLANE_XCODE_LIST_TIMEOUT=50
echo "password"  | sudo gem update -n /usr/local/bin fastlane
echo "some release notes" | fastlane testing
```

it only prints "iOS" and "Live" in case of running on CI

**Comment by Mohab1** [comment]
Any updates on this guys ?

**Comment by vpolouchkine** [comment]
Can you try getting the change log from a text file instead?

**Comment by Mohab1** [comment]
I just needed more easy way to include relaese notes while pushing a new build from jenkins.
I changed the approach now to make it take these logs via "options" for each lane it's more convenient than passing it from prompt

**Comment by vpolouchkine** [comment]
Glad you were able to work around this.
