### ISSUE TITLE
[match] nuke command asks from app_identifier which is not usefull

### ISSUE THREAD

**Issue by nicolasbraun** [fastlane/fastlane#5776]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Running the `match nuke`command will prompt the user for app_identifier.
As a precision I do not have an Fastfile / Appfile, just trying to run the command from anywhere on my computer.
##### Complete output when running fastlane, including the stack trace and command used

```
➜  ~ match nuke development --git_url 'myrepoURL' --username 'nicolas.braun@applidium.com'
INFO [2016-08-17 09:31:43.71]: Cloning remote git repo...
WARN [2016-08-17 09:31:45.07]: To not be asked about this value, you can specify it using 'app_identifier'
```

Please note that this is a minor bug as the app_identifier will be ignored and the nuke works ☢️

`ERROR [2016-08-17 09:31:56.89]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!`
### Configuration Files

None
### Environment

fastlane version : fastlane 1.100.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by vpolouchkine** [comment]
Thanks for the report!
