### ISSUE TITLE
ios enable push notifications capability.

### ISSUE THREAD

**Issue by netdotcom** [fastlane/fastlane#5778]
It possible add\enable SystemCapabilities = {com.apple.Push = {enabled = 1;}}; in .xcodeproj/project.pbxproj with fastlane? (like a turn on Capabilities -> Push Notifications switch in xcode)

**Comment by vpolouchkine** [comment]
There's an [action](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#update_info_plist) to modify the Info.plist,  but I don't believe there's one for project.pbxproj.

**Comment by Nailer** [comment]
I have the same question. I would like to disable push capabilities for some test versions signed with a generic wildcard provisioning profile.

**Comment by TKBurner** [comment]
Hi @Nailer, is your goal to do this when using gym? You should check out the xcargs parameter.

Thanks!

**Comment by Nailer** [comment]
Yes! Thank you, I'll check that out!

**Comment by Nailer** [comment]
Hm, I couldn't figure out which arguments to pass with xcargs to do this. Any tips?

**Comment by TKBurner** [comment]
@Nailer I'm going to mark this as help wanted to see if anyone from the community can help. I haven't messed around with xcargs too much.
