### ISSUE TITLE
Using with custom localization logic

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#5781]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Can this tool be used with custom localization logic? Meaning that the app language is not linked to the device's language, but rather handled manually by the app using `NSUserDefaults` for persistence.

**Comment by vpolouchkine** [comment]
Which tool (within fastlane) are you referring to specifically?

**Comment by revolter** [comment]
Sorry! I was referring to [snapshot][1]. Should I move this issue there?

  [1]: https://github.com/fastlane/fastlane/tree/master/snapshot

**Comment by vpolouchkine** [comment]
No worries. I believe you can make this work via Launch Arguments (https://github.com/fastlane/fastlane/tree/master/snapshot#launch-arguments).

**Comment by revolter** [comment]
I can't get it to work. having set `app.launchArguments += ["-myCustomLanguageId", "2"];` in the `setLanguage` function from the `SnapshotHelper.swift` file, that key is not updated in the user defaults. I don't know how to debug it too. Tried adding an `NSLog` but couldn't find it in the `Console` app. Also, the README mentions `NSProcessInfo.processInfo().arguments` but doesn't provide an example. The `myCustomLanguageId` is of type integer, but `launchArguments` is of type `NSArry<NSString *>`, could this be the problem?

**Comment by revolter** [comment]
Fixed it. Xcode automatically adds a `launch()` call in the `setUp()` function, so after copying

```
app = XCUIApplication()
setupSnapshot(app)
app.launch()
```

in the `setUp()` function, I had 2 `launch()` calls. After removing the auto-generated one, the problem went away and the user defaults properly saved.

I also solved my custom localization method by setting a user default based on the variable `deviceLanguage` which `snapshot` adds.

**Comment by vpolouchkine** [comment]
Glad to hear you're up and running. I'll re-open this to keep track of the doc update work.

**Comment by revolter** [comment]
Sorry about closing it.

**Comment by revolter** [comment]
@vpolouchkine, Did you manage to update the docs?

**Comment by TKBurner** [comment]
@revolter Thanks for reaching out. You can now localize the simulator. Let me know if that meets your needs. 👍

**Comment by revolter** [comment]
@TKBurner, this issue was left open to add [this warning](https://github.com/fastlane/fastlane/issues/5781#issuecomment-242298434) in the README.

> You can now localize the simulator.

What do you mean by this? What exactly was changed?

**Comment by TKBurner** [comment]
@revolter Sorry about that. I'll make sure we update the readme. Thanks!
