### ISSUE TITLE
Unclear how to use fixed font size with frameit

### ISSUE THREAD

**Issue by kcharwood** [fastlane/fastlane#5782]
While trying to use frameit, my screenshots came back looking slightly off because the fonts were differently across all 5 screenshots. Doing some digging, I found various references to `fontSize` in several PR's and issues, and those issues showed `fontSize` being included at different points in the data structure of the `FrameFile.json` I attempted to use `fontSize` in various places, but none of them seemed to impact the font size on the screenshots.

I was not able to find any documentation on the use of that property anywhere.

In addition, I could not find that property in the source code of frameit.

Would some clarity on if this is supported, and some documentation demonstrating the correct place to include it.

**Comment by cratrifork** [comment]
I'm that this was never intented to work due to the text having to be much larger on iPads and smaller on iPhones: [https://github.com/fastlane/fastlane/issues/2773](https://github.com/fastlane/fastlane/issues/2773)

**Comment by kcharwood** [comment]
@KrauseFx thought it was in there, and ask me to create this ticket to track it.

**Comment by Anders123fr** [comment]
I have the same issue.

Can this commit fix it?
https://github.com/futuretap/fastlane/commit/d719893d881c7f717b04a861e1ce52b517cb2109

**Comment by TKBurner** [comment]
@Anders123fr You should test out the fix? We would love to see this improved.

**Comment by Anders123fr** [comment]
I am not that much into Ruby so don't know how to build it myself, so i was hoping someone could try it out.

**Comment by TKBurner** [comment]
@Anders123fr No problem :+1:

**Comment by dzungpv** [comment]
I like fix font size too, now it difference each image @TKBurner  please add this to release, i don't know how to build fastlane

**Comment by alpennec** [comment]
Hello,

Any idea why the fontSize feature had been added in 2.5.0 and then immediately removed?
I have to create portrait screenshots for an iPad app, I am using raw screenshots from an iPad Pro 12.9 inches (and intend to use the iTunes screenshot manager). Currently, the title is taking way too much space above the screenshot.

<img width="563" alt="screenshot 2016-12-24 11 54 55" src="https://cloud.githubusercontent.com/assets/2082662/21466532/ce11b480-c9cf-11e6-8279-fb5eda04a323.png">

I can play a bit with the padding, but it's not ideal.
It would be really nice to precise the fontSize (or fontScale) for iPhone & iPad and being able to differentiate for both. cc @KrauseFx 

Thanks for your help,
Axel

**Comment by KrauseFx** [comment]
@alpennec If it was removed there was probably a problem with it. If you can find the PRs for adding and then for removing the features for me, that would help 👍

**Comment by alpennec** [comment]
@KrauseFx thanks for the update.
Here is the tag https://github.com/fastlane-old/frameit/releases/tag/2.5.0
Fontsize is at the end of this file: https://github.com/fastlane-old/frameit/blob/2.5.0/lib/frameit/editor.rb
