### ISSUE TITLE
screengrab installation problem for windows10

### ISSUE THREAD

**Issue by misteriusdrh** [fastlane/fastlane#5783]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description : 

Can not install Screengrab on windows10 for Android Studio using tutorial :
https://github.com/fastlane/fastlane/tree/master/screengrab

Could you please add more info how to do that?

Thank you.

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
@misteriusdrh Thanks for reaching out. Right now screengrab is not compatible with Windows. That is why you are experiencing this issue. I'll mark this as a feature request. Thanks!
