### ISSUE TITLE
Action Idea: Push notifications via Pushover for Fastlane lane status

### ISSUE THREAD

**Issue by teddynewell** [fastlane/fastlane#5784]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

While running long Fastlane lanes, I would love to get push notifications as the lane progresses in case I leave my computer.  [Pushover](https://pushover.net) provides an API for sending push notifications that I will wrap in a custom Action.

**Comment by TKBurner** [comment]
Hi @teddynewell I saw Felix followed up on your pull request. This would work better as a plugin.  Hope you have a great day!
