### ISSUE TITLE
Fastlane hockey action with upload-only API token

### ISSUE THREAD

**Issue by matthewjsloane** [fastlane/fastlane#5786]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Hi there, not sure if this is Fastlane's responsibility, but I accidentally used an upload-only HockeyApp API token when attempting to upload a build to HockeyApp AND make it available for testers to download (e.g. status: "2", as is the default), and it wasn't until I opened up the HockeyApp API documentation that I realized my mistake, since Fastlane doesn't indicate that the build wasn't released (or why). This isn't a particularly important issue, but I just wanted to point it out in case there is something that could or should be done.

Sample output (no difference if an upload-only or a full access API token was used):

```
14:12:48.263 [14:12:48]: --------------------
14:12:48.263 [14:12:48]: --- Step: hockey ---
14:12:48.263 [14:12:48]: --------------------
14:12:48.280 [14:12:48]: Starting with ipa upload to HockeyApp... this could take some time.
14:13:12.199 [14:13:12]: Public Download URL: https://some.url.net/abcdefghijklmnopqrstuvwxyz
14:13:12.199 [14:13:12]: Build successfully uploaded to HockeyApp!
```
### Configuration Files

Example Fastfile:

``` ruby
  hockey # with default status: "2", api token env var set elsewhere
```
### Environment

fastlane version (run `fastlane -v`): 1.100.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by vpolouchkine** [comment]
Thanks for the report; what would expect to see in the log?
