### ISSUE TITLE
Ambiguous instructions in match readme

### ISSUE THREAD

**Issue by mrmartineau** [fastlane/fastlane#5791]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am just getting started with fastlane and am unsure about some ambiguous copy on the match readme. Could you clarify what by point 3 of [the setup](https://github.com/fastlane/fastlane/tree/master/match#setup) means?

> Run the following in your project folder to start using `match`:

Is the 'project' the repo that houses the certificates for match? or is it the repo for my app?

I ran `match init` on the certificates repo and a `Matchfile` was created but I am stuck beyond that. The instructions say to then run `match development`, where should this be done?

Apologies for the noob questions. This sort of thing is quite alien to me..

### Environment

fastlane version (run `fastlane -v`): 1.100.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
1) It's the repo of your app
2) You should run `match development` in the same directory

I agree, the README might not be very clear, would you mind submitting a PR once you got it up and running? 👍
