### ISSUE TITLE
ERROR:  While executing gem ... (Errno::EPERM)     Operation not permitted - /usr/bin/spaceship

### ISSUE THREAD

**Issue by Kjens93** [fastlane/fastlane#5795]
### New Issue Checklist

- [ ] Updated fastlane to the latest version (Can't do this. That's the problem.)
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Unable to update fast lane to version 1.101.0 or install that version from scratch.

##### Complete output when running fastlane, including the stack trace and command used

```
#######################################################################
# fastlane 1.101.0 is available. You are on 1.100.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

$ sudo gem update fastlane
Updating installed gems
Updating fastlane
Fetching: spaceship-0.31.2.gem (100%)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/spaceship
```

### Environment

OS version: Mac OS X 10.11.6

fastlane version (run `fastlane -v`): N/A

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by vpolouchkine** [comment]
Can you take a look at https://github.com/fastlane/fastlane/issues/5313 to see if it helps?

**Comment by Kjens93** [comment]
Yes, this solved the problem. Thank you.

—iKyler

**Comment by vpolouchkine** [comment]
Great!
