### ISSUE TITLE
Changelog from Git Commits

### ISSUE THREAD

**Issue by mattfred** [fastlane/fastlane#5796]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I'm attempting to include a log of git commits when I push a new android build to hockey app. However, the log shown in hockey app is always "No changelog given"
##### Complete output when running fastlane, including the stack trace and command used

hockey(
      api_token: ENV["HOCKEYAPP_API_TOKEN"],
      ipa: HOCKEYAPP_APK,
      notes_type: '0',
      notes: changelog_from_git_commits(pretty: '%h %s')
    )
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
  desc "Hockey Deploy"
  lane :hockey do |options|
    # Clean and build the apk
    gradle(task: "clean",
                    properties: {
                    'versCode' => options[:build_number]
                     })
    gradle(task: "assembleDebug",
           properties: {
           'versCode' => options[:build_number]
           })


    # Push to Hockey
    hockey(
      api_token: ENV["HOCKEYAPP_API_TOKEN"],
      ipa: HOCKEYAPP_APK,
      notes_type: '0',
      notes: changelog_from_git_commits(pretty: '%h %s')
    )
  end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane_version "1.100.0"

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by vpolouchkine** [comment]
As a sanity check, can you set `notes` to some string?
