### ISSUE TITLE
Produce not creating new applications anymore

### ISSUE THREAD

**Issue by spawrks** [fastlane/fastlane#5799]
### Issue Description
Produce does not seem to be able to create new applications on the latest version.  Previously it was was able to do so but now we have to create manually in itunes connect.  It works fine if it is a no-op.  Not Specifying --skip-_itc results in the same error.

##### Complete output when running fastlane, including the stack trace and command used

```
-$ produce -u engineering@themagazinechannel.com -a com.tmc.guitaraficionadomag --skip_itc

+----------------+------------------------------------+
|              Summary for produce 1.2.0              |
+----------------+------------------------------------+
| username       | engineering@themagazinechannel.com |
| app_identifier | com.tmc.guitaraficionadomag        |
| skip_itc       | true                               |
| sku            | 1471553608                         |
| language       | English                            |
| skip_devcenter | false                              |
| team_id        | EHVF94JHMQ                         |
+----------------+------------------------------------+

[15:53:31]: To not be asked about this value, you can specify it using 'app_name'
App Name: Guitar Aficionado Magazine
[15:53:42]: Creating new app 'Guitar Aficionado Magazine' on the Apple Dev Center

Looking for related GitHub issues on fastlane/fastlane...

➡️  Bad Request - portal_client.rb - associate_groups_with_app
   https://github.com/fastlane/fastlane/issues/2049 [open] 0 💬
   07 Mar 2016

➡️  757: unexpected token at 'HTTP 400 Bad Request'
   https://github.com/fastlane/fastlane/issues/2947 [closed] 4 💬
   08 Mar 2016

➡️  unexpected token at HTTP 400 Bad Request
   https://github.com/fastlane/fastlane/issues/3468 [closed] 12 💬
   08 Mar 2016

and 17 more at: https://github.com/fastlane/fastlane/search?q=757:%20unexpected%20token%20at%20'Bad%20Request'&type=Issues&utf8=✓
/Users/spawrks/.rvm/gems/ruby-2.1.2/gems/json-1.8.3/lib/json/common.rb:155:in `parse': [!] 757: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.31.2/lib/spaceship/client.rb:411:in `block in send_request'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.31.2/lib/spaceship/client.rb:328:in `with_retry'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.31.2/lib/spaceship/client.rb:410:in `send_request'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.31.2/lib/spaceship/client.rb:385:in `request'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.31.2/lib/spaceship/portal/portal_client.rb:177:in `create_app!'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/spaceship-0.31.2/lib/spaceship/portal/app.rb:97:in `create!'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/produce-1.2.0/lib/produce/developer_center.rb:22:in `create_new_app'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/produce-1.2.0/lib/produce/developer_center.rb:8:in `run'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/produce-1.2.0/lib/produce/manager.rb:7:in `start_producing'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/produce-1.2.0/lib/produce/commands_generator.rb:37:in `block (2 levels) in run'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/produce-1.2.0/lib/produce/commands_generator.rb:127:in `run'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/produce-1.2.0/lib/produce/commands_generator.rb:11:in `start'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/produce-1.2.0/bin/produce:6:in `<top (required)>'
	from /Users/spawrks/.rvm/rubies/ruby-2.1.2/bin/produce:23:in `load'
	from /Users/spawrks/.rvm/rubies/ruby-2.1.2/bin/produce:23:in `<main>'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

We use this in our file, but it doesnt matter if we use it in the fastfile or from the command line.
Fastfile:
```ruby
  produce(
    app_name: accountDetails['tmc_app_name'],
    app_identifier: appid,
    language: 'English',
    app_version: '1.1',
    sku: accountDetails['tmc_app_build_name'],
    team_name: 'The Magazine Channel' 
  )
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.101.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by brockklein** [comment]
+1 getting this as well. Was able to produce earlier this week but stopped when moving from 1.99.0 to 1.101.0.

Seems like it used to be a common experience: https://github.com/fastlane/fastlane/issues/349

I tried the recommended solution (which it looks like @KrauseFx [has already incorporated](on Dec 14, 2015) into the source): 

```
require 'faraday'
Faraday::Utils.default_params_encoder = Faraday::FlatParamsEncoder
```

but that has not solved the issue. Confirmed on multiple machines on multiple networks.

**Comment by Guilherme92Dev** [comment]
duplicate of #5797

**Comment by KrauseFx** [comment]
Thanks for the report everyone, I can reproduce and work on a fix right now

**Comment by KrauseFx** [comment]
Pull request is ready, we'll push a new release in a few minutes https://github.com/fastlane/fastlane/pull/5803 🚀

**Comment by KrauseFx** [comment]
The new release is live, please update using `[sudo] gem update spaceship` or if you're using `bundler`, use `bundle update` 🚀 
Please let us know if that solves the problem for you 👍

**Comment by brockklein** [comment]
@KrauseFx as always major kudos for the fast response!

Sadly still getting the same error running `produce` directly after `sudo gem update spaceship` (and `sudo gem update produce` just to be safe).

```
/Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse': [!] 757: unexpected token at 'Bad Request' (Faraday::ParsingError)
	from /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.3/lib/spaceship/client.rb:411:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.3/lib/spaceship/client.rb:328:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.3/lib/spaceship/client.rb:410:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.3/lib/spaceship/client.rb:385:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.3/lib/spaceship/portal/portal_client.rb:175:in `create_app!'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.3/lib/spaceship/portal/app.rb:97:in `create!'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/developer_center.rb:22:in `create_new_app'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/developer_center.rb:8:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/manager.rb:7:in `start_producing'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:37:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:127:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:11:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/bin/produce:6:in `<top (required)>'
	from /usr/local/bin/produce:23:in `load'
	from /usr/local/bin/produce:23:in `<main>'
```

**Comment by spawrks** [comment]
Just tried again after updating fastlane, produce, and spaceship, same error returning when running produce from commandline.
I should mention that when I run from the fastfile I get a different error:

fastfile:
```
  produce(
    app_name: accountDetails['tmc_app_name'],
    app_identifier: appid,
    language: 'English',
    app_version: '1.1',
    sku: accountDetails['tmc_app_build_name'],
    team_name: 'The Magazine Channel' 
  )
```

results in this error:

```+----------------+------------------------------------+
|              Summary for produce 1.2.0              |
+----------------+------------------------------------+
| app_name       | Golf Course Industry Magazine      |
| app_identifier | com.tmc.golfcourseindustrymag      |
| language       | English                            |
| app_version    | 1.1                                |
| sku            | golfcourseindustrymag              |
| team_name      | The Magazine Channel               |
| username       | engineering@themagazinechannel.com |
| skip_itc       | false                              |
| skip_devcenter | false                              |
| team_id        | EHVF94JHMQ                         |
+----------------+------------------------------------+

[13:06:14]: Creating new app 'Golf Course Industry Magazine' on the Apple Dev Center
[13:06:15]: Variable Dump:
[13:06:15]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"62", :VERSION_NUMBER=>"2.7.113"}
[13:06:15]: undefined method `+' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | slack                               | 0           |
| 4    | increment_build_number              | 1           |
| 5    | increment_version_number            | 1           |
| 6    | get_version_number                  | 1           |
| 7    | update_info_plist                   | 2           |
| 8    | update_info_plist                   | 0           |
| 9    | produce                             | 7           |
+------+-------------------------------------+-------------+

[13:06:15]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `fetch' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/5677 [open] 1 💬
   a week ago

➡️  Pilot tool is crashing with undefined method 'strip' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/3238 [open] 0 💬
   08 Mar 2016

➡️  Spaceship parsing fails with "undefined method `fetch' for nil:NilClass"
   https://github.com/fastlane/fastlane/issues/5701 [closed] 2 💬
   3 days ago

and 154 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60+'%20for%20nil&type=Issues&utf8=✓
Fastfile:424:in `block (2 levels) in parsing_binding': [!] undefined method `+' for nil:NilClass (NoMethodError)
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/runner.rb:63:in `call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/runner.rb:63:in `block in execute'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/runner.rb:59:in `chdir'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/runner.rb:59:in `rescue in execute'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/runner.rb:44:in `execute'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2@global/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `load'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/bin/fastlane:23:in `<main>'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/spawrks/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by KrauseFx** [comment]
@spawrks The error message you posted is caused by your Fastfile line 424, which you didn't share with us 👍

**Comment by asfalcone** [comment]
[`spaceship 0.31.4`](https://github.com/fastlane/fastlane/releases/tag/spaceship/0.31.4) has been released. Please run `gem update spaceship` and confirm the fix for us! 👍

**Comment by quadecco** [comment]
spaceship 0.31.4:

 > /Library/Ruby/Gems/2.0.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse': [!] 743: unexpected token at 'Bad Request' (Faraday::ParsingError)
        from /Library/Ruby/Gems/2.0.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:411:in `block in send_request'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:328:in `with_retry'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:410:in `send_request'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:385:in `request'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/portal/portal_client.rb:128:in `update_service_for_app'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/portal/app.rb:138:in `update_service'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/service.rb:160:in `update'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/service.rb:19:in `enable'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/service.rb:4:in `enable'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:64:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:127:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:11:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/bin/produce:6:in `<top (required)>'
        from /usr/local/bin/produce:23:in `load'
        from /usr/local/bin/produce:23:in `<main>'

**Comment by asfalcone** [comment]
@quadecco thanks! we'll keep trying! so the command you're running is `produce enable_services` ?

**Comment by quadecco** [comment]
produce create now working:

+----------------+-------------------------------------------+
|                 Summary for produce 1.2.0                              |
+----------------+-------------------------------------------+
| username       | xxx@gmail.com                            |
| app_identifier | com.xxx.application210.store |
| app_name       | app test 12                                 |
| sku            | 1471638822                                |
| language       | English                                   |
| skip_itc       | false                                     |
| skip_devcenter | false                                     |
+----------------+-------------------------------------------+

[16:33:45]: [DevCenter] App 'com.xxx.application210.store' already exists, nothing to do on the Dev Center
[16:33:46]: [iTC] App 'com.xxx.application210.store' already exists (1144573904), nothing to do on iTunes Connect


But same issue on enable push notifications
produce enable_services --push-notification -u xxx@gmail.com -a com.xxx.application210.store

[16:35:42]: Starting login with user 'xxx@gmail.com'
[16:35:44]: Successfully logged in
[16:35:45]: [DevCenter] App found 'test'
[16:35:45]: Enabling services
[16:35:45]:     Push Notifications

Looking for related GitHub issues on fastlane/fastlane...

➡️  "unexpected token at 'Bad Request'" from Spaceship when attempting to repair a provisioning profile
   https://github.com/fastlane/fastlane/issues/5813 [open] 3 💬
   10 minutes ago

/Library/Ruby/Gems/2.0.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse': [!] 743: unexpected token at 'Bad Request' (Faraday::ParsingError)
        from /Library/Ruby/Gems/2.0.0/gems/json-2.0.2/lib/json/common.rb:156:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:48:in `parse'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:39:in `process_response'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:32:in `block in call'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:411:in `block in send_request'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:328:in `with_retry'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:410:in `send_request'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/client.rb:385:in `request'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/portal/portal_client.rb:128:in `update_service_for_app'
        from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.31.4/lib/spaceship/portal/app.rb:138:in `update_service'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/service.rb:160:in `update'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/service.rb:19:in `enable'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/service.rb:4:in `enable'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:64:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.2/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:127:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/lib/produce/commands_generator.rb:11:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/produce-1.2.0/bin/produce:6:in `<top (required)>'
        from /usr/local/bin/produce:23:in `load'
        from /usr/local/bin/produce:23:in `<main>'

**Comment by asfalcone** [comment]
Thanks for updating! we're working to fix `enable_services` as well. Hang tight!

**Comment by guangmingwan** [comment]
try this, i work fine with spaceship 0.31.1 by add some code
Mac:ios-code-signing adouming$ diff ~/Documents/client.rb  /usr/local/lib/ruby/gems/2.2.0/gems/spaceship-0.31.1/lib/spaceship/client.rb
72a73,75
>     # Raised when 421 is received from portal request
>     class BadCSRFError < BasicPreferredInfoError; end
> 
335a339,346
>     rescue BadCSRFError => ex
>       unless (tries -= 1).zero?
> 
>         logger.warn("BadCSRFError received: '#{ex.message}'.  Retrying after 3 seconds (remaining: #{tries})...")
>         sleep 3 unless defined? SpecHelper
>         retry
>       end
>       raise ex # re-raise the exception
377c388
<       log_request(method, url_or_path, params,headers)
---
>       log_request(method, url_or_path, params)
392c403
<     def log_request(method, url, params, headers)
---
>     def log_request(method, url, params)
399,405c410
<       headers_to_log = Hash(headers).dup
<       headers_to_log = headers_to_log.collect do |key, value|
<         "{#{key}: #{value}}"
<       end
<       logger.info(">> #{method.upcase}: #{url}: ")
<       logger.info(">> #{headers_to_log.join(', ')}:")
<       logger.info(">> #{params_to_log.join(', ')}:")
---
>       logger.info(">> #{method.upcase}: #{url} #{params_to_log.join(', ')}")
409,410c414
<       response || {}
<       logger.debug("<< #{method.upcase}: #{url}: #{response.headers}: #{response.body}")
---
>       logger.debug("<< #{method.upcase}: #{url}: #{response.body}")
417d420
< 	begin
419,423d421
< 	rescue
< 	@csrf_tokens = {}	
< 	end
< 	if response.nil?
< 	else 
424a423,433
> 
>         if resp_hash[:status] == 421
>           @csrf_tokens = {}
>           store_csrf_tokens(response) # reget csrf
>           headers.merge!(csrf_tokens)
> 
>           msg = "csrf bad"
>           logger.warn msg
>           raise BadCSRFError.new, "csrf bad"
>         end
> 
435d443
< 	end

**Comment by KrauseFx** [comment]
Thanks everybody, could you update to the latest spaceship that we just release, and let us know if that fixes the issue?

**Comment by quadecco** [comment]
Tharks you!
Now working for me:

produce enable_services --push-notification -u xxx@gmail.com -a com.xxx.application210

Starting login with user 'xxx@gmail.com'
Successfully logged in
[DevCenter] App found 'test'
Enabling services
Push Notifications
Done! Enabled 1 services.

**Comment by spawrks** [comment]
@KrauseFx re: fastfile , ah yes that was my error messaging block crashing- I apologize for not looking closer before copy and pasting.  

I can confirm the fix is working for me now as well, thank you so much!

**Comment by BrianSemiglia** [comment]
Spaceship 0.31.4 fixed my issue as well. Thanks!

**Comment by TKBurner** [comment]
@BrianSemiglia Awesome!
