### ISSUE TITLE
Upload increment_build_number or increment_version_number programatically

### ISSUE THREAD

**Issue by mchiesa** [fastlane/fastlane#581]
Hi KrauseFx, I want to update build number or version number depending a boolean value

Here is my fastlane file :

```ruby
platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods
    gym # Build your app - more options available

    # xctool # run the tests of your app
  end

  private_lane :build_app do |options|
    if options[:increment_build_number]
      increment_build_number
    end

    if options[:increment_version_number]
      increment_version_number
    end
  end

  desc "Runs all the tests"
  lane :test do
    #snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    #snapshot
    build_app
    sigh

    if options[:upload_to_testflight]
      deliver(beta: true)
    end
   
   if options[:upload_to_crashlytics]
       crashlytics({
         crashlytics_path:'./Crashlytics.framework',
         api_token: '5895XXXXXXXXXXXXX872XXX',
         build_secret: 'XXXXXXX',
         ipa_path: 'Test.ipa'
      })
   end
end
```

Everything works fine, but build/version number is not updating.. What is wrong?

Thanks a lot,
Martin

**Comment by KrauseFx** [comment]
You don't pass anything to the `build_app` lane inside the `beta` lane


```ruby
platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods
    gym # Build your app - more options available

    # xctool # run the tests of your app
  end

  private_lane :build_app do |options|
    if options[:increment_build_number]
      increment_build_number
    end

    if options[:increment_version_number]
      increment_version_number
    end
  end

  desc "Runs all the tests"
  lane :test do
    #snapshot
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    #snapshot
    build_app(options)
    sigh

    if options[:upload_to_testflight]
      deliver(beta: true)
    end
   
   if options[:upload_to_crashlytics]
       crashlytics({
         crashlytics_path:'./Crashlytics.framework',
         api_token: '5895XXXXXXXXXXXXX872XXX',
         build_secret: 'XXXXXXX',
         ipa_path: 'Test.ipa'
      })
   end
end
```

Then call the lane using

```
fastlane ios beta increment_build_number:1
```

or

```
fastlane ios beta increment_version_number:1
```

:rocket:

**Comment by KrauseFx** [comment]
The only thing I changed it 

```
build_app
```

to

```
build_app(options)
```

Let me know if that works for you :+1:

**Comment by mdeandreis** [comment]
Hi KrauseFx, it´s me again

I´m triying to update build number or version number depending a boolean value using fastlane

If I do this I can´t achieve what I want

before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods
    gym # Build your app - more options available
    # xctool # run the tests of your app
  end

  private_lane :build_app do |options|
    if options[:increment_build_number]
      increment_build_number
    end

    if options[:increment_version_number]
      increment_version_number
    end
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    #snapshot
    echo
    build_app(options)
    sigh

    if options[:upload_to_testflight]
      deliver(beta: true)
    end
   
   if options[:upload_to_crashlytics]
       crashlytics({
         crashlytics_path:'./Crashlytics.framework',
         api_token: 'XXX5XXx',
         build_secret: 'XXXX0d6667166cXX',
         ipa_path: 'Test.ipa'
      })
   end
   
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end

On the other hand, If I change my code and do this I update version/build number. I want to update version/build number only if the increment_version_number parameter is true. Besides, in before_all section I can´t access to options. How can I achieve what I want? 

before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # cocoapods
    gym # Build your app - more options available
    # xctool # run the tests of your app
   increment_version_number
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    #snapshot
    echo
    build_app(options)
    sigh

    if options[:upload_to_testflight]
      deliver(beta: true)
    end
   
   if options[:upload_to_crashlytics]
       crashlytics({
         crashlytics_path:'./Crashlytics.framework',
         api_token: 'XXX5XXx',
         build_secret: 'XXXX0d6667166cXX',
         ipa_path: 'Test.ipa'
      })
   end
   
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
end

Thanks, Martin

**Comment by ohwutup** [comment]
hey @mchiesa! I'm going to close this issue for now as it's been a while since there was any activity, feel free to reopen if necessary! :dart:
