### ISSUE TITLE
Allow gym's build and export to each run in isolation

### ISSUE THREAD

**Issue by richardszalay** [fastlane/fastlane#5824]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

🔑 I'd like to propose a change to gym that would allow build and export to run at different times.

It would involve two change:
1. Adding a skip_export option
2. Allowing the output type (iOS, tv) to be passed in as an option (ie so there's no dependency on the project still being around)

**Comment by TKBurner** [comment]
Hi @richardszalay Thanks for reaching out about this. I marked this as a feature request to see if the community is interested in this functionality. Thanks!

**Comment by richardszalay** [comment]
Thanks @TKBurner - I'm happy to look at doing a PR for it.

If you're interested in the usecase, checkout the [blog series I just published](https://blog.richardszalay.com/2016/08/22/ios-deploy-pipeline-1-introduction/) (though I don't mention this issue until the "Closing Thoughts" in part 4.

**Comment by TKBurner** [comment]
@richardszalay Very cool! I think it makes sense to add these. If you are interested go for it. We are a little behind on merging PRs so I want to set the expectation that it might be slow going once you prepare something. By making sure you have good test coverage we can hopefully merge faster!

**Comment by richardszalay** [comment]
I'm working on the PR :)

**Comment by TKBurner** [comment]
@richardszalay Awesome! 👍 We'll work with you there .

**Comment by nubbel** [comment]
It is pretty common to build the archive once and export multiple ipas, i.e. one for adhoc, one for in-house, and one for App Store distribution.
I would love to have to separate actions for that `gym_archive` and `gym_export`.

Better yet, gym would detect that the archive has already been built and skips that step. This would allow me to define the following sequence of actions:
```ruby
gym output_name: 'adhoc', export_method: 'ad-hoc'
gym output_name: 'inhouse', export_method: 'enterprise'
gym output_name: 'appstore', export_method: 'appstore'
```
Only the first invocation of `gym` would build the archive, the others would just export ipas from it.

@richardszalay, @TKBurner: What do you think?

**Comment by richardszalay** [comment]
@nubbel Even more so for us. We have an app with 3 (and counting) sub brands, and our deployment process is 3-phased (testing using test APIs, testing using live APIs, app store). Using a single build artifact reduces a full deployment cycle from over an hour to 20 minutes, and we could drop that further by taking advantage of the new multiple-identifier support in match.

We currently use unsigned IPAs to facilitate this process, but the Export+Plist stuff in Xcode 7+ no longer allows for that.

**Comment by nubbel** [comment]
@richardszalay Oh wow, cool setup!

Exporting multiple ipas from a single archive is not only convenient and saves a lot of time, it is also a guarantee that the binary that goes to QA is exactly the same as the one that lands in the App Store.

**Comment by richardszalay** [comment]
Exactly! I see you're a fan of Continuous Delivery?
