### ISSUE TITLE
Default appstore lane name conflicts with appstore action alias 

### ISSUE THREAD

**Issue by dombarnes** [fastlane/fastlane#5851]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Fastlane warns that lane ````appstore```` conflicts with the appstore alias to deliver. Given this is the default lane name on ````fastlane init```` it makes sense to change one of these things.  

##### Complete output when running fastlane, including the stack trace and command used

```
Name of the lane 'testflight' is already taken by the action named 'testflight'
Name of the lane 'appstore' is already taken by the action named 'appstore'
```

### Environment

fastlane version (run `fastlane -v`):
1.101.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
@dombarnes Thanks for reaching out about this. So when do you get this error? When you run the lane or on fastlane init? Can you run sudo gem update fastlane? Thanks!

**Comment by dombarnes** [comment]
I was getting the error when running my lanes I think. It was more a warning than an error.

Ran ````fastlane init```` on another project not using it yet, I get the default lanes as :beta and :appstore

Ran gem update fastlane and everything is up to date.

````
11:39:41]: -------------------------------------------------
[11:39:41]: --- Step: Verifying required fastlane version ---
[11:39:41]: -------------------------------------------------
[11:39:41]: fastlane version valid
[11:39:41]: ------------------------------
[11:39:41]: --- Step: default_platform ---
[11:39:41]: ------------------------------
[11:39:41]: Name of the lane 'appstore' is already taken by the action named 'appstore'
[11:39:41]: Driving the lane 'ios dummy' 🚀
````
The lane finishes without errors.

**Comment by revolter** [comment]
I have the same issue. Ran `fastlane init` and `fastlane lanes` and got that error.

**Comment by KrauseFx** [comment]
Great catch, thanks, I'll look into this 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/5895, which will be in the next release, thanks for letting us know. Please rename the lane to something else for now 👍

**Comment by revolter** [comment]
More exactly, rename it to `release` if you want to match the new `fastlane`'s default name.
