### ISSUE TITLE
Couldn't find app with 'yyyyyyyyy'

### ISSUE THREAD

**Issue by vani2** [fastlane/fastlane#5852]
I try `pilot list -u <my-appleid>`, but it fails. What app name actually using for searching? I disappointed about this error.

```
[17:02:43]: Login to iTunes Connect (<my-appleid>)
[17:02:47]: Login successful

[!] Couldn't find app with 'yyyyyyyyy'
```

I use

```
fastlane 1.101.0

rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

**Comment by TKBurner** [comment]
Hi @vani2 Can you share the full input and output when you run `pilot list`? Also can you provide your fastfile? Thanks!

**Comment by KrauseFx** [comment]
Where did you set the bundle identifier `yyyyyyyyy`?

**Comment by vani2** [comment]
The problem was wrong branch with another app id, but not `yyyyyyyyy`.Thanks for quick reply.

**Comment by TKBurner** [comment]
@vani2 Really glad to hear you got up and running. Always feel free to reach out with thoughts or questions.
