### ISSUE TITLE
Need to detect if PEM created a certificate or not

### ISSUE THREAD

**Issue by CareerFairPlus** [fastlane/fastlane#5857]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to figure out a way to determine - programmatically in my Fastfile - if PEM created a new Push Certificate for my app or if my current certificate is still valid for a while.  I can examine the console output to see if PEM created one or not, but I can't seem to find a way to determine it in my Fastfile.  I tried to set the return value of the PEM call to something and print it out, but nothing is returned.  Anyone have any ideas?

##### Complete output when running fastlane, including the stack trace and command used
```
$ fastlane test_pem
[14:09:34]: -------------------------------------------------
[14:09:34]: --- Step: Verifying required fastlane version ---
[14:09:34]: -------------------------------------------------
[14:09:34]: fastlane version valid
[14:09:34]: ------------------------------
[14:09:34]: --- Step: default_platform ---
[14:09:34]: ------------------------------
[14:09:34]: Driving the lane 'ios test_pem' 🚀
[14:09:34]: -----------------
[14:09:34]: --- Step: pem ---
[14:09:34]: -----------------

+------------------+---------------------------------+
|               Summary for PEM 1.3.2                |
+------------------+---------------------------------+
| app_identifier   | [redacted]   |
| username         | [redacted] |
| generate_p12     | true                            |
| p12_password     | [redacted]                        |
| development      | false                           |
| force            | false                           |
| save_private_key | true                            |
| output_path      | .                               |
+------------------+---------------------------------+

[14:09:35]: Starting login with user '[redacted]'
[14:09:36]: Successfully logged in
[14:09:48]: Existing push notification profile '[redacted]' is valid for 395 more days.
[14:09:48]: You already have a push certificate, which is active for more than 30 more days. No need to create a new one
[14:09:48]: If you still want to create a new one, use the --force option when running PEM.
[14:09:48]: PEM Return Value: 

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | pem                                 | 13          |
+------+-------------------------------------+-------------+

[14:09:48]: fastlane.tools finished successfully 🎉
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :test_pem do
    pemReturn = pem(
      app_identifier: '[redacted]',
      username: '[redacted]',
      generate_p12: true,
      p12_password: ENV['P12_PASSWORD'])
    UI.message "PEM Return Value: #{pemReturn.to_s}"
  end
```

### Environment

fastlane version (run `fastlane -v`): 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by TKBurner** [comment]
Hi @CareerFairPlus Thanks for reaching out about this. There isn't a good way to do this. You could force a new cert to always be created, or you could check the created date of the actual file. Thanks!

**Comment by CareerFairPlus** [comment]
The problem with forcing a new cert to always be created (which is what we do currently) is that PEM won't auto-revoke the oldest push cert and will fail after 2 certs have already been generated.  

I think a simpler approach is to add a return value to the pem action: true if a new cert has been created, false if no certs have been created.  It looks like the inner-workings of PEM already does this, it's just not bubbled up to the action wrapper.

**Comment by CareerFairPlus** [comment]
Just noticed the new_profile option in the PEM action:
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#pem

**Comment by TKBurner** [comment]
@CareerFairPlus Thanks for following up on this. Glad you found what you were looking for. Hope you have an excellent day!
