### ISSUE TITLE
Installing fastlane on a xcode8 Beta6 Fails Json-1.8.3.gem working fine with Xcode 7

### ISSUE THREAD

**Issue by sfransen** [fastlane/fastlane#5858]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

$ sudo gem install fastlane  -n/usr/local/bin
Fetching: highline-1.7.8.gem (100%)
Successfully installed highline-1.7.8
Fetching: commander-4.4.0.gem (100%)
Successfully installed commander-4.4.0
Fetching: terminal-table-1.4.5.gem (100%)
Successfully installed terminal-table-1.4.5
Fetching: json-1.8.3.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/json-1.8.3 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/json-1.8.3/ext/json/ext/generator/gem_make.out

**Comment by sfransen** [comment]
I tried Xcode beta 5 and Xcode beta 6 both fail.

**Comment by TKBurner** [comment]
Hi @sfransen Thanks for reaching out. We don't have official support for Xcode 8 yet. However, can you downgrade to json 1.8.1 and let me know how it goes? Thanks!

**Comment by verticelo** [comment]
Running xcode-select --install solved this problem for me.

**Comment by KrauseFx** [comment]
I'll close this issue for now, feel free to re-open if you still run into it 👍
