### ISSUE TITLE
Supply - json_key_file - Set data with environment variable instead?

### ISSUE THREAD

**Issue by Syrou** [fastlane/fastlane#5866]
We are setting up a complete buildflow with fastlane, ci & docker, and kind of think this would be a important feature to add into supply.

Keeping credentials is important, and supplying a json file that potentially someone can just get access to by either getting an url or just copying the from the repository file is probably harder to protect than just using the build variables added in most Git repository management systems.

Is there already a simple way of making supply fetching the json_key_file data from an environment variable or could this be added?

**Comment by TKBurner** [comment]
@Syrou Thanks for reaching out. You should be able to set it as an enviromental variable with the SUPPLY_JSON_KEY key. Let me know how it goes!
