### ISSUE TITLE
Dependency Problem

### ISSUE THREAD

**Issue by glancashire** [fastlane/fastlane#5868]
When I try to update to the newest version I receive the following error (on two different machines)

```
Error installing fastlane:
conflicting dependencies highline (~> 1.6.11) and highline (>= 1.7.2)
  Activated highline-1.7.2
  which does not match conflicting dependency (~> 1.6.11)

  Conflicting dependency chains:
    fastlane (= 1.101.0), 1.101.0 activated, depends on
    krausefx-shenzhen (>= 0.14.10), 0.14.10 activated, depends on
    highline (>= 1.7.2), 1.7.2 activated

  versus:
    fastlane (= 1.101.0), 1.101.0 activated, depends on
    krausefx-shenzhen (>= 0.14.10), 0.14.10 activated, depends on
    commander (< 5.0, >= 4.3), 4.3.0 activated, depends on
    highline (~> 1.6.11)

Nothing to update
```

I have tried uninstalling and reinstalling to no avail.

Thanks for your help.

**Comment by TKBurner** [comment]
Hi @glancashire Thanks for reaching out. Do you use RVM to manage rubies? Also can you uninstall the highline gem and then run `sudo gem update fastlane`?

**Comment by glancashire** [comment]
Dear Todd

I am not using RVM.

I have uninstalled highline and installed fastlane

Both of which worked (highline-1.7.8), w.o. error.

When I try to update, the same error.
As far as I can see commander v4.3 is used which requires highlane 1.6… which causes the problem


…
ERROR:  Error installing fastlane:
	
conflicting dependencies highline (~> 1.6.11) and highline (>= 1.7.2)
  Activated highline-1.7.2
  which does not match conflicting dependency (~> 1.6.11)

  Conflicting dependency chains:
    fastlane (= 1.101.0), 1.101.0 activated, depends on
    krausefx-shenzhen (>= 0.14.10), 0.14.10 activated, depends on
    highline (>= 1.7.2), 1.7.2 activated

  versus:
    fastlane (= 1.101.0), 1.101.0 activated, depends on
    krausefx-shenzhen (>= 0.14.10), 0.14.10 activated, depends on
    commander (< 5.0, >= 4.3), 4.3.0 activated, depends on
    highline (~> 1.6.11)

Nothing to update
…

Kind Regards

Graham

➜

Swift Management AG | Managing Partner
St. Alban Vorstadt 104 | 4052 Basel | Switzerland
T ++41 61 385 55 50 | M ++41 79 485 25 20
lancashire@swift.ch | www.swift.ch

**Comment by KrauseFx** [comment]
Can you run `gem cleanup` and then `[sudo] gem install fastlane`? 👍 

If that doesn't work, you might want to start using a [Gemfile](https://guides.cocoapods.org/using/a-gemfile.html), which is the recommended way to store dependencies in your repo.

**Comment by glancashire** [comment]
This worked
> gem cleanup

Thanks for the suggestion I added a gemfile

Graham

**Comment by KrauseFx** [comment]
Yeah 🎉
