### ISSUE TITLE
latest_testflight_build_number ignores team_id

### ISSUE THREAD

**Issue by nikolaykasyanov** [fastlane/fastlane#5880]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

`latest_testflight_build_number` ignores `team_id` parameter and always asks to pick the team.

Here's how I tried to call it:
- `fastlane run latest_testflight_build_number team_id:<team id>`
- `env FASTLANE_TEAM_ID=<team id> fastlane run latest_testflight_build_number` (I'm usng fish shell)

I don't have an Appfile, .env file doesn't contain any `FL_` variables except `FL_HOCKEY_API_TOKEN`.
##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane run latest_testflight_build_number team_id:<team id>
+-------------------------+---------+---------+
|                Used plugins                 |
+-------------------------+---------+---------+
| Plugin                  | Version | Action  |
+-------------------------+---------+---------+
| fastlane-plugin-trainer | 0.2.0   | trainer |
+-------------------------+---------+---------+

[12:39:33]: --------------------------------------------
[12:39:33]: --- Step: latest_testflight_build_number ---
[12:39:33]: --------------------------------------------
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
...
```
### Environment

fastlane version (run `fastlane -v`): 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? YES

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by TKBurner** [comment]
@nikolaykasyanov Thanks for doing that research. It looks like you have found the reason for this behavior. I was wondering if you were able to figure out a workaround? Thanks!

**Comment by nikolaykasyanov** [comment]
@TKBurner yep, I was able to workaround the issue by explicitly setting `FASTLANE_ITC_TEAM_ID` through `env` before calling the action.

**Comment by TKBurner** [comment]
@nikolaykasyanov Thanks for letting me know. I'm going to leave this open in case anyone from the community wants to step in to make this more clear in the product. Thanks!
