### ISSUE TITLE
Name of the lane XXX is already taken by the action named XXX

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#5882]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It seems that since v1.0 lanes and actions names collide which gives error in console. How to solve that or what's the point?

##### Complete output when running fastlane, including the stack trace and command used

```
...

[12:36:24]: Name of the lane 'app_config' is already taken by the action named 'app_config'
[12:36:24]: Name of the lane 'seed' is already taken by the action named 'seed'
[12:36:24]: Name of the lane 'mogenerator' is already taken by the action named 'mogenerator'

...

```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  desc "Generate NSManagedObject subclasses from CoreData Model."
  lane :mogenerator do
    mogenerator
  end
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by asfalcone** [comment]
Thanks for the feedback @pronebird. We added this error messaging so that it is easy to distinguish between lanes and actions in your Fastfile. These are simply warnings, so if you don't want to change your Fastfile, you can just ignore them. 👍  I'm going to close this issue since we don't plan to make any changes to this behavior
