### ISSUE TITLE
latest_testflight_build_number should have option to get latest build number of last *released* train

### ISSUE THREAD

**Issue by nikolaykasyanov** [fastlane/fastlane#5883]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Here's my use case:
- I'm adding new version to iTC.
- I'm trying to upload a build to that new empty release train, and to make sure I won't get build number collision, I'd like to know the very latest build number existing in iTC for that particular app.

As far as I understand, `latest_testflight_build_number` only checks unreleased train (if any) and asks the user to enter version number manually if there's no such train. It doesn't work well with automated setups (I'm using Jenkins to do iTC uploads).

Am I missing something?

Thank you!

**Comment by TKBurner** [comment]
@nikolaykasyanov Thanks for reaching out. The behavior you are experiencing is currently expected. I'm going to mark this as a feature request to see if anyone else in the community is interested in enhancing this. Thanks!
