### ISSUE TITLE
I use fastlane well,but at gitlab-ci failed ,and the gitlab-ci runner is my computer

### ISSUE THREAD

**Issue by tanhuiya** [fastlane/fastlane#5884]
## I run  ' fastlane test' in my project well ,but when I submit to gitlab-ci , and the gitlab-ci runner is my local computer , it got errors ,please help me . Before fastlane , I use xcodebuild and xctool command working successful.

[22:12:53]: -------------------------------------------------
[22:12:53]: --- Step: Verifying required fastlane version ---
[22:12:53]: -------------------------------------------------
[22:12:53]: fastlane version valid
[22:12:53]: ------------------------------
[22:12:53]: --- Step: default_platform ---
[22:12:53]: ------------------------------
[22:12:53]: Name of the lane 'testFlight' is already taken by the action named 'testFlight'
[22:12:53]: Name of the lane 'appstore' is already taken by the action named 'appstore'
[22:12:53]: Driving the lane 'ios test' 🚀
[22:12:53]: ------------------
[22:12:53]: --- Step: scan ---
[22:12:53]: ------------------
[22:12:53]: xcodebuild -list -workspace ParentAndSchool.xcworkspace
[22:13:00]: Variable Dump:
[22:13:00]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios test"}
[22:13:00]: no implicit conversion of nil into String
[22:13:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  [Spaceship] TypeError: no implicit conversion of String into Integer in app_version.rb:641
   https://github.com/fastlane/fastlane/issues/5652 [closed] 9 💬
   2 weeks ago

➡️  no implicit conversion of nil into String
   https://github.com/fastlane/fastlane/issues/3379 [closed] 3 💬
   08 Mar 2016

➡️  I use fastlane well,but at gitlab-ci failed ,and the gitlab-ci runner is my computer
   https://github.com/fastlane/fastlane/issues/5884 [open] 2 💬
   a minute ago

and 33 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓
/Users/xwl/.rvm/gems/ruby-2.2.3/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `include?': [!] no implicit conversion of nil into String (TypeError)
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `block in default_device_ios'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `each'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `default_device_ios'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/scan-0.11.3/lib/scan/detect_values.rb:23:in `set_additional_default_values'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/scan-0.11.3/lib/scan.rb:27:in `config='
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/actions/scan.rb:14:in `run'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `chdir'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:13:in `block (2 levels) in parsing_binding'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xwl/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
ERROR: Build failed: exit status 1
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  desc "Runs all the tests"
  lane :test do
    scan({
      workspace:"xxxxxxx.xcworkspace",
      scheme:"parent",
      device:"iPhone 6s"
    })
  end
```

### Environment

fastlane 1.101.0

I use RVM ,and my ruby version is 2.2.3

**Comment by asfalcone** [comment]
@tanhuiya Can you please include the full stack trace in the output? Thanks! 👍

**Comment by tanhuiya** [comment]
and 33 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓
/Users/xwl/.rvm/gems/ruby-2.2.2/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `include?': [!] no implicit conversion of nil into String (TypeError)
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/scan-0.11.3/lib/scan/detect_values.rb:60:in `block in default_device_ios'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `each'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/scan-0.11.3/lib/scan/detect_values.rb:58:in `default_device_ios'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/scan-0.11.3/lib/scan/detect_values.rb:23:in `set_additional_default_values'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/scan-0.11.3/lib/scan.rb:27:in `config='
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/actions/scan.rb:14:in `run'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `chdir'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:13:in `block (2 levels) in parsing_binding'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `load'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `<main>'
	from /Users/xwl/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'

**Comment by tanhuiya** [comment]
@asfalcone  Then I use   gym(scheme: "parent")  in gitlab-ci runner it failed again ,and It works well in the root project .here is the full stack trace , I add my bashrc ,but not worked for me .

/Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:383:in `===': invalid byte sequence in US-ASCII (ArgumentError)
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:383:in `update_test_state'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/parser.rb:270:in `parse'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/formatters/formatter.rb:83:in `pretty_format'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/lib/xcpretty/printer.rb:15:in `pretty_print'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/bin/xcpretty:80:in `block in <top (required)>'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/bin/xcpretty:79:in `each_line'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/gems/xcpretty-0.2.2/bin/xcpretty:79:in `<top (required)>'
from /usr/local/bin/xcpretty:22:in `load'
from /usr/local/bin/xcpretty:22:in `<main>'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
from /Users/tanhui/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
[23:57:43]: Exit status: 1
[23:57:43]: Your shell environment is not correctly configured
[23:57:43]: Instead of UTF-8 your shell uses US-ASCII
[23:57:43]: Please add the following to your '~/.bashrc':
[23:57:43]: 
[23:57:43]:        export LANG=en_US.UTF-8
[23:57:43]:        export LANGUAGE=en_US.UTF-8
[23:57:43]:        export LC_ALL=en_US.UTF-8
[23:57:43]: 
[23:57:43]: You'll have to restart your shell session after updating the file.
[23:57:43]: If you are using zshell or another shell, make sure to edit the correct bash file.
[23:57:43]: For more information visit this stackoverflow answer:
[23:57:43]: https://stackoverflow.com/a/17031697/445598
[23:57:43]: Variable Dump:
[23:57:43]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios testFlight", :LATEST_TESTFLIGHT_BUILD_NUMBER=>1, :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings."}
[23:57:43]: Error building the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | latest_testflight_build_number      | 19          |
| 4    | increment_build_number              | 0           |
| 5    | gym                                 | 314         |
+------+-------------------------------------+-------------+

[23:57:43]: fastlane finished with errors

[!] Error building the application - see the log above
ERROR: Build failed: exit status 1

**Comment by tanhuiya** [comment]
I solve it by adding this to my .bash_profile
I do not know why, and my ipa file contains Chinese , I occurs on another question seems to be xcpretty, but it works !

export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

**Comment by TKBurner** [comment]
@tanhuiya Awesome! Really glad to hear you got up and running. Hope you have a great week!
