### ISSUE TITLE
Changing the Bundle Id of Apps with WatchApp 

### ISSUE THREAD

**Issue by henry42** [fastlane/fastlane#5886]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

If changing bundle id of app with watch app, the watch app's bundle id would not be changed together.(`resign --new_bundle_id`)

Is there any plan supporting it?

**Comment by TKBurner** [comment]
Hi @henry42 Great idea! Right now that behavior doesn't happen. Can you let me know what happens when you try to take this action at present? Thanks!
