### ISSUE TITLE
Snapshot targets

### ISSUE THREAD

**Issue by chrisortman** [fastlane/fastlane#5889]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I run snapshot it does 20 runs and in each run it looks like it is rebuilding my project.

I'm using cocoa pods, so I have a scheme that is my project and then schemes for each of the pods I use.

I have to specify my scheme when I run snapshot

Should I create a new scheme that is just for my UITests? Would that make the snapshot run faster?

**Comment by TKBurner** [comment]
Hi @chrisortman Thanks for reaching out. You can try and create a scheme directly for snapshot. You might run into a linking issue if your frameworks aren't also linked to it. Thanks!

**Comment by chrisortman** [comment]
@TKBurner Do you do this in your projects? Is it common practice?

**Comment by TKBurner** [comment]
Hi @chrisortman Thanks for following up. Generally making it a separate target alone is your better bet.
