### ISSUE TITLE
`increment_version_number` fails for the default Xcode project starting version of "1.0"

### ISSUE THREAD

**Issue by sharplet** [fastlane/fastlane#5890]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

New Xcode projects start with a version number of 1.0. I think it would be useful to assume this implies a semantic version of 1.0.0, but the `increment_version_number` action doesn't behave this way.

I'd like to update the action to handle this case gracefully, and [have a patch ready](https://github.com/sharplet/fastlane/commit/e51968d2fb972b9c389a9f2cf25e0b82e5c55fef) that implements my proposed change.

##### Complete output when running fastlane, including the stack trace and command used

```
[!] Your current version (1.0) does not respect the format A.B.C
```

### Environment

fastlane version (run `fastlane -v`): **fastlane 1.101.0**

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **No**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **No**

**Comment by TKBurner** [comment]
@sharplet Hi! Hope you are doing well. Right now this is expected behavior. Thanks!

**Comment by sharplet** [comment]
Do you have a particular reason in mind for not changing the behaviour?

**Comment by TKBurner** [comment]
Hi @sharplet! Thanks for following up. I'm not sure of the history of this, but it's been this way historically within Fastlane. We think the error message is a graceful fail here. If people come in and comment on this thread we'll definitely consider the change.

**Comment by SAVeselovskiy** [comment]
@TKBurner, it will be cool if there is support for the format "A.B". In our team we use this format for some projects. Hope this feature will be released somewhen.

**Comment by TKBurner** [comment]
@SAVeselovskiy Thanks for following up on this. I bring it up with the team.
