### ISSUE TITLE
Add snapshot option to skip building

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#5898]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is there any possibility to add an option for snapshot to skip the build part? Building my project takes quite a long time, and while trying to integrate snapshot and fiddle with it, it's annoying and inefficient to wait 5+ minutes between each `snapshot` command.

**Comment by KrauseFx** [comment]
Sorry no, snapshot needs to build the app to run it on the simulator.

**Comment by revolter** [comment]
So I guess it's not possible to do a hot build or how it's called. So it builds only the modified files, right?

**Comment by TKBurner** [comment]
@revolter It's not possible right now. Because we require you build on a test target it's hard to avoid this. Thanks!
