### ISSUE TITLE
When ever i run supply to upload apk.I get this error

### ISSUE THREAD

**Issue by PankeshGupta** [fastlane/fastlane#5900]
Is a directory @ io_fread - /home/Documents
[11:23:03]: supply failed, but don't worry, you can launch supply using `supply init` whenever you want.

**Comment by PankeshGupta** [comment]
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/usr/lib/ruby/gems/2.3.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:75:in `read': [!] Is a directory @ io_fread - /home/pankesh/Documents (Errno::EISDIR)
	from /usr/lib/ruby/gems/2.3.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:75:in `read_json_key'
	from /usr/lib/ruby/gems/2.3.0/gems/googleauth-0.5.1/lib/googleauth/service_account.rb:59:in `make_creds'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/client.rb:53:in `initialize'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/client.rb:29:in `new'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/client.rb:29:in `make_from_config'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/uploader.rb:157:in `client'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/uploader.rb:6:in `perform_upload'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /usr/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/lib/ruby/gems/2.3.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:57:in `run'
	from /usr/lib/ruby/gems/2.3.0/gems/supply-0.7.0/lib/supply/commands_generator.rb:15:in `start'
	from /usr/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/lib/fastlane/cli_tools_distributor.rb:48:in `take_off'
	from /usr/lib/ruby/gems/2.3.0/gems/fastlane-1.101.0/bin/fastlane:5:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by asfalcone** [comment]
@PankeshGupta can you please include the full output of running supply as well as your Fastfile? Thanks 👍
