### ISSUE TITLE
gym: When output_name contains "/" (directory character), export fails

### ISSUE THREAD

**Issue by frisocki** [fastlane/fastlane#5909]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When the value of output_name contains a slash(/), xcodebuild will create directories underneath the archive path. Then when gym attempts to export the archive and dSYM, it will potentially fail if any of the directories do not exist under the export path.

##### Complete output when running fastlane, including the stack trace and command used

```
+----------------------+------------------------------+
|                Summary for gym 1.7.0                |
+----------------------+------------------------------+
| output_name          | feature/some_feature         |
| scheme               | feature-dev                  |
| export_method        | enterprise                   |
| include_bitcode      | false                        |
| output_directory     | '/Users/user/export'         |
| project              | ./feature.xcodeproj          |
| destination          | generic/platform=iOS         |
| clean                | false                        |
| silent               | false                        |
| use_legacy_build_api | false                        |
+----------------------+------------------------------+

set -o pipefail && xcodebuild -scheme feature-dev \
-project ./feature.xcodeproj \
-destination 'generic/platform=iOS' \
-archivePath \
'/Users/user/Library/Developer/Xcode/Archives/2016-08-26/feature/some_feature 2016-08-26 11.20.45.xcarchive'
...
[11:22:38]: $ cd '/Users/user/Library/Developer/Xcode/Archives/2016-08-26/feature/some_feature 2016-08-26 11.20.45.xcarchive/dSYMs' && zip -r '/Users/user/export/feature/some_feature.app.dSYM.zip' *.dSYM
[11:22:38]: ▸ zip I/O error: No such file or directory
[11:22:38]: ▸ zip error: Could not create output file (/Users/user/export/feature/some_feature.app.dSYM.zip)
```

The work around is to ensure the output_name does not contain any slash characters. However, should gym either:

1. Convert any slashes(/) to dash(-) or underscore(_) in output_name, before passing archive path to xcodebuild.
2. Attempt to create any directories under export_path, if any directories were created under archive_path.

### Environment

fastlane version (run `fastlane -v`): fastlane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by TKBurner** [comment]
Hi @frisocki Thanks for reaching out. This seems like a reproducible issue. Are you interested in submitting a PR to correct this behavior? Thanks!
