### ISSUE TITLE
Expose the provisioning profile name out of sigh/match to use it for Xcode 8 codesigning

### ISSUE THREAD

**Issue by mathiasAichinger** [fastlane/fastlane#5910]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

With Xcode 8 the way to set the provisioning profile has changed. Instead of using the UUID of the profile, it uses the team_id/profile_name. As we have different environments we need to set the name dynamically. Unfortunately sigh/match only expose the UUID as evironment variable.
#### Fix

Additionally to the UUID also expose the profile_name as environment variable

**Comment by TKBurner** [comment]
@mathiasAichinger Thanks for pointing this out! We don't have official support for Xcode 8 yet, but it is something we are working on. We really appreciate the PR and will work with you on it. Thanks!

**Comment by KrauseFx** [comment]
@TKBurner @mathiasAichinger already submitted a PR for this, I'm working together with him to get this merged 👍 Thanks for your contribution

**Comment by matt-digitaliceltd** [comment]
Do we know when this is likely to be merged? Or I guess more generally, when Xcode 8 will be officially supported?

Cheers
Matt

**Comment by hjanuschka** [comment]
any updates on this one?! currently can't build with xcode8 😢

**Comment by etolstoy** [comment]
Waiting for this fix - can't build with Xcode8.

**Comment by lemonkey** [comment]
Same.

**Comment by KrauseFx** [comment]
Hey everyone, so @mfurtak and I worked on this today, and added support for exposing those values with https://github.com/fastlane/fastlane/pull/6189.
However I'm surprised on why you can't build with Xcode 8. Did you follow the code signing guide for Xcode 8? https://docs.fastlane.tools/codesigning/XcodeProject/

**Comment by aarsland** [comment]
Great, @KrauseFx! In our case we do builds for different customers from a base xcode project, so we need to set both teamId´s and provisioning profiles dynamically from the Fastfile, that’s why we needed this change.
