### ISSUE TITLE
commit_version_bump not committing all files

### ISSUE THREAD

**Issue by marcelosalloum** [fastlane/fastlane#5912]
### New Issue Checklist
- [x ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Hey guys,

I've been using `commit_version_bump` but not all my files are being committed. One of my targets, that is an iOS Today Widget, is not having it's Info.plist file committed. Is that a known issue?

**Comment by TKBurner** [comment]
Hi @marcelosalloum Are you running `git add .` The version bump can only commit what is properly staged. Thanks!

**Comment by marcelosalloum** [comment]
Hi @TKBurner, adding `git_add(path: ".")` before `commit_version_bump` did the trick, thanks.

But wasn't `commit_version_bump` supposed to do that too?

**Comment by TKBurner** [comment]
Hi @marcelosalloum Thanks for following up. We want to only commit changes that have been added by the user.

**Comment by blackm00n** [comment]
Hi @TKBurner, I got the same problem. It doesn't seem like an intentional behaviour to me. Single plist file is being omitted and the rest 5 files been added to the commit. I didn't add any of them manually so it's not the "commit changes that have been added by the user" behaviour.

**Comment by TKBurner** [comment]
@blackm00n Can you share the output? Also is this happening on all projects or just one specific project? Thanks for working with me and hope you have a great day!
