### ISSUE TITLE
Exit lane

### ISSUE THREAD

**Issue by juliangsp** [fastlane/fastlane#5913]
Is there a way to exit/end/return/quit/abort with success a lane?

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by KrauseFx** [comment]
Yeah, you can use
```ruby
UI.user_error!("Whoops, something went wrong")
```
to fail the current lane.

Nothing for finishing a lane, you can always do that using if else blocks

**Comment by mfurtak** [comment]
After researching some ideas from the community, we found a built-in language construct that can help!

``` ruby
lane :test do
  puts "hi"
  next
  raise "bye"
end

after_all do
  puts "after"
end
```

produces:

```
$ fastlane test
[09:24:02]: Driving the lane 'test' 🚀
[09:24:02]: hi
[09:24:02]: after
[09:24:02]: fastlane.tools finished successfully 🎉
```

As you can see, the `next` keyword skips the rest of the lane, but allows _fastlane_ to complete normally, so the `after_all` block is still run.

Hope that helps 🚀

**Comment by KrauseFx** [comment]
@mfurtak thanks for posting this here. Maybe that's something we should mention in `Advanced.md`?

**Comment by KrauseFx** [comment]
Thanks @mfurtak for the writeup: https://github.com/fastlane/fastlane/pull/6674 🚀

**Comment by juliangsp** [comment]
Thanks @mfurtak 👍  it's good info shared and great if it's documented.
