### ISSUE TITLE
Fastlane deliver new version (1.13.3) error

### ISSUE THREAD

**Issue by makeappioseasy** [fastlane/fastlane#5916]
### Issue Description

i can use deliver long time , before fastlane update version (1.13.3) .

my localizations can use long time , before fastlane update version (1.13.3) too.

```
INSERT OUTPUT HERE
```

Looking for related GitHub issues on fastlane/fastlane...

[15:22:50]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass

[!] The request could not be completed because:
	What's New In This Version in French must be at least 4 characters in length. What's New In This Version in English (U.K.) must be at least 4 characters in length. What's New In This Version in German must be at least 4 characters in length. What's New In This Version in French (Canada) must be at least 4 characters in length. What's New In This Version in Chinese (Traditional) must be at least 4 characters in length. What's New In This Version in Dutch must be at least 4 characters in length. What's New In This Version in Swedish must be at least 4 characters in length. What's New In This Version in Vietnamese must be at least 4 characters in length. What's New In This Version in Finnish must be at least 4 characters in length. What's New In This Version in Portuguese (Brazil) must be at least 4 characters in length. What's New In This Version in Spanish (Mexico) must be at least 4 characters in length. What's New In This Version in English (Canada) must be at least 4 characters in length. What's New In This Version in Spanish (Spain) must be at least 4 characters in length. What's New In This Version in Malay must be at least 4 characters in length. What's New In This Version in Danish must be at least 4 characters in length. What's New In This Version in English (Australia) must be at least 4 characters in length. What's New In This Version in Indonesian must be at least 4 characters in length. What's New In This Version in Portuguese (Portugal) must be at least 4 characters in length. What's New In This Version in Italian must be at least 4 characters in length. What's New In This Version in Greek must be at least 4 characters in length. What's New In This Version in Turkish must be at least 4 characters in length. What's New In This Version in Japanese must be at least 4 characters in length. What's New In This Version in Chinese (Simplified) must be at least 4 characters in length. What's New In This Version in Korean must be at least 4 characters in length. What's New In This Version in Russian must be at least 4 characters in length. What's New In This Version in Thai must be at least 4 characters in length. What's New In This Version in English (U.S.) must be at least 4 characters in length. Review Notes must be at least 2 characters in length. There are errors on the page and for 27 of your localizations.

please help me to fix it's.

Thanks T_T

**Comment by nafu** [comment]
@makeappioseasy 

You might want to follow the issue template.

> 
> ### New Issue Checklist
> 
> - [ ] Updated fastlane to the latest version
> - [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
> 
> ### Issue Description
> 
> ##### Complete output when running fastlane, including the stack trace and command used
> 
> ```
> INSERT OUTPUT HERE
> ```
> 
> ### Configuration Files
> 
> Please copy the complete content of your `Fastfile` and any other configuration files you use below:
> 
> Fastfile:
> ```ruby
> # INSERT CONTENT HERE
> ```
> 
> ### Environment
> 
> fastlane version (run `fastlane -v`):
> 
> Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
> 
> Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
>

**Comment by KrauseFx** [comment]
This is a metadata error, make sure to read and address the error message you received 👍
