### ISSUE TITLE
fastlane reporting apple developer website is down

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#5918]
Hi,

My fastlane setup suddenly stopped working reporting apple developer website is under maintenance.
Its been a while and am getting the same error. I verified that the apple developer website is working by visiting the website and even downloading the profiles. Am wondering if anything has been broken on fastlane end.

[14:06:24]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

[14:06:24]: [31mError finding relevant GitHub issues: undefined method `map' for nil:NilClass
Did you mean?  tap[0m
/Users/Shared/Jenkins/.rvm/gems/ruby-2.3.0/gems/spaceship-0.31.10/lib/spaceship/client.rb:436:in `parse_response': [31m[!] <?xml version="1.0" encoding="UTF-8"?> (Spaceship::Client::UnexpectedResponse)
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
     <key>resultCode</key>
     <integer>503</integer>
     <key>userString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>resultString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>httpCode</key>
     <integer>503</integer>
     <key>userLocale</key>
     <string>en_US</string>
  </dict>
</plist>
[0m

**Comment by vancex** [comment]
same....

**Comment by nafu** [comment]
I think this is a problem of Apple Developer website although [System status](https://developer.apple.com/system-status/) is all green.
Here is what I got after running Spaceship.select_team 3 times in order for example.
They return errors randomly and sometimes it will succeed.

```ruby
[2] pry(main)> Spaceship.select_team
Spaceship::Client::UnexpectedResponse: {"responseId"=>"b1fd1489-64b4-45e0-ab2e-c5c47f41f8da", "resultCode"=>-1, "resultString"=>"Unexpected error occured", "userString"=>"An unexpected error occurred. Please try again.  If the problem persists, please contact Apple Developer Program Support.\nhttps://developer.apple.com/support", "creationTimestamp"=>"2016-08-27T13:56:08Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developerservices2.apple.com/services/QH65B2/listTeams.action", "httpCode"=>200}
from /Users/nafu/Projects/fastlane/spaceship/lib/spaceship/client.rb:436:in `parse_response'
[3] pry(main)> Spaceship.select_team
Spaceship::Client::UnexpectedResponse: <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
     <key>resultCode</key>
     <integer>503</integer>
     <key>userString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>resultString</key>
     <string>The Apple Developer website is undergoing maintenance. For details, visit developer.apple.com/system-status.</string>
     <key>httpCode</key>
     <integer>503</integer>
     <key>userLocale</key>
     <string>en_US</string>
  </dict>
</plist>
from /Users/nafu/Projects/fastlane/spaceship/lib/spaceship/client.rb:436:in `parse_response'
[4] pry(main)> Spaceship.select_team
=> "*MYTEAMID*"
```

**Comment by guangmingwan** [comment]
try my temporary solution, will fix:  
```
vi /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.31.10/lib/spaceship/portal/portal_client.rb
52       #req = request(:post, "https://developerservices2.apple.com/services/QH65B2/listTeams.action")
 53       req = request(:post, "https://developer.apple.com/services-account/QH65B2/account/listTeams.action")
```

**Comment by vancex** [comment]
@guangmingwan  
I tried something like this about listProvision...., no use

**Comment by guangmingwan** [comment]
@vancex 
find function `provisioning_profiles` in portal_client.rb, need change url and params also ...

**Comment by vancex** [comment]
@guangmingwan 
https://developer.apple.com/services-account/QH65B2/account/ios/profile/listProvisioningProfiles.action

like this?

**Comment by vancex** [comment]
@guangmingwan something worse.... 504 gameway  now

**Comment by guangmingwan** [comment]
@vancex 
I test the api url  interface for listProvisioningProfiles, call 5 times,  success 4 times, failed 1 times
I think Apple's CDN server may has a bad node. so , wo don't need do anything, just go sleep, the problem will solved.

**Comment by santoshshetty2612** [comment]
Thanks, only option left is to wait for the Apple servers to respond in an appropriate way.

**Comment by santoshshetty2612** [comment]
Things are working smooth again. Thanks for everyone's time and effort.

**Comment by vancex** [comment]
@santoshshetty2612 @guangmingwan is it ok now?
almost 504 gateway.
ping ip?

**Comment by santoshshetty2612** [comment]
@vancex Its working now. I didn't had to change anything.

**Comment by vancex** [comment]
@santoshshetty2612 
what is the ip address if you ping developerservices2.apple.com.
17.146.1.142?

**Comment by swl367** [comment]
mine is 17.146.1.2

**Comment by TKBurner** [comment]
@swl367 Are you still running into this issue? There was an issue on the Apple side this past weekend.
Thanks!

**Comment by swl367** [comment]
@TKBurner I was running into the issue since Saturday morning until yesterday night. I tried sigh this morning and it seems like it's working (although it's not as quick as before). It seems to pause on "fetching profiles" for a lot longer than usual.

**Comment by TKBurner** [comment]
Hi @swl367 Can you run `sudo gem update fastlane` and then share your full input and output. I'd love to take a look. Thanks!

**Comment by swl367** [comment]
@TKBurner 

not much to go off on but...

[13:39:15]: Starting login with user 'x@y.com'
[13:39:18]: Successfully logged in
[13:39:18]: Fetching profiles...
[13:39:52]: Found 1 matching profile(s)
[13:39:52]: Downloading provisioning profile...
[13:39:53]: Successfully downloaded provisioning profile...
[13:39:53]: Installing provisioning profile...

You can see that it took 34 seconds to fetch the 1 profile. The account I'm using has about 100 apps/profiles, so that could be potentially an issue.

**Comment by TKBurner** [comment]
Hi @swl367 Thanks for following up. Can you continue to monitor this? It seems like it's on the API side, but I want to make sure. Thanks!
