### ISSUE TITLE
Plugin specs - expectations with Fastlane UI

### ISSUE THREAD

**Issue by pajapro** [fastlane/fastlane#5920]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
While writing specs for plugin, I want to assert on my action's UI outputs. Example:
``` ruby
expect(FastlaneCore::UI).to receive(:important).with("WARNING: No changes in [Unreleased] section to stamp!")
```

##### Complete output when running fastlane, including the stack trace and command used

```
  1) Fastlane::Actions::StampChangelogAction Stamp CHANGELOG.md action rejects to stamp an empty [Unreleased] section
     Failure/Error: expect(FastlaneCore::UI).to receive(:important).with("WARNING: No changes in [Unreleased] section to stamp!")
     
       (FastlaneCore::UI (class)).important("WARNING: No changes in [Unreleased] section to stamp!")
           expected: 1 time with arguments: ("WARNING: No changes in [Unreleased] section to stamp!")
           received: 0 times
     # ./spec/stamp_changelog_action_spec.rb:66:in `block (3 levels) in <top (required)>'
```

### Environment

fastlane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by pajapro** [comment]
I just realised that I placed my expectation _after_ executing action. Reversing the order (expectation then action execution) fixed the problem.

**Comment by KrauseFx** [comment]
Glad to hear you got it resolved 👍
