### ISSUE TITLE
[Match] Manually encrypt and upload manually created certs?

### ISSUE THREAD

**Issue by reallistic** [fastlane/fastlane#5921]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Because of issue #5123 i'm wondering if there is a way to manually encrypt some certs to upload?
My specific scenario is that I need to re-generate the provisioning profiles in order to test on a new device but since apple's developer site is sporadic I can't get `match` to work however the site does occasionally work (very slowly).

### Environment

fastlane version (run `fastlane -v`): fastlane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? - No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? - No

**Comment by KrauseFx** [comment]
Hey @reallistic, you can run `match` in readonly mode to just decrypt and install all the certificates

**Comment by reallistic** [comment]
@KrauseFx I was under the impression I needed to run `match --force_for_new_devices` in order for the new devices to be added to the provisioning profile and/or certs?

**Comment by KrauseFx** [comment]
@reallistic Yes, that's correct, but you can't add new devices when the Developer Portal is down, sorry

**Comment by reallistic** [comment]
@KrauseFx Thanks for the info.
Does this also mean it isn't possible to manually encrypt the repo to add new (or other) stuff?

**Comment by KrauseFx** [comment]
@reallistic to add a new device, you'll have to access the developer portal, as it all happens on the server-side. You'll have to wait until Apple's servers are up again. Alternatively, you can manually add the device using the Apple Dev Portal website as as far I as know, just the Xcode API is down (which is what spaceship uses)

**Comment by reallistic** [comment]
I should have further explained that some time ago I messed up my repo by manually adding a provisioning profile.
I've since reverted the commit which now allows readonly to work, but i'm wondering if it is possible for me to manually encrypt that provisioning profile so `match --readonly` can successfully pull it.

I completely understand the limitations of match without the dev portal.

What I now want to know is (as the title of this issue states) **Can you manually encrypt and upload certs/provisioning profiles/other files/etc?**
Perhaps by using a local `pgp` install or similar?

**Comment by TKBurner** [comment]
@reallistic Thanks for following up. Right now it's not possible. The reason is Match checks against Apple to see if the profile is valid when run. Thanks!

**Comment by reallistic** [comment]
Thanks for the info.
