### ISSUE TITLE
Run script in Xcode project didn't print anything

### ISSUE THREAD

**Issue by jacobjiangwei** [fastlane/fastlane#5929]
Here is the jenkins output
13:52:25 [13:52:25]: ▸ [35m[33m>[0m [39;1mRunning script[0m 'Embed Pods Frameworks'[0m
13:52:27 [13:52:27]: ▸ [35m[33m>[0m [39;1mRunning script[0m 'Copy Pods Resources'[0m
13:52:27 [13:52:27]: ▸ [35m[33m>[0m [39;1mRunning script[0m 'Upload To Crittercism'[0m

Is there a way to know what's happening inside? We have our own script running there, please do not disable any output for non-code scripts.

**Comment by TKBurner** [comment]
Hi @jacobjiangwei Thanks for reaching out. What happens if you add the --verbose flag to your lane? Thanks!

**Comment by jacobjiangwei** [comment]
already did

发自我的 iPhone

**Comment by TKBurner** [comment]
Hi @jacobjiangwei Thanks for following up. Are you logging anything to the console during your action? Thanks!

**Comment by jacobjiangwei** [comment]
We are using crittercism upload script to upload dSYM files, apparently it logs a few important stuff.

Is fast lane hijacked the console output?

发自我的 iPhone

**Comment by jacobjiangwei** [comment]
@TKBurner

**Comment by TKBurner** [comment]
@jacobjiangwei Thanks for following up. Fastlane controls the output. It doesn't look like  you are going to be able to log this information directly from the crittercism script. Do you have access to the actual source for the script you are using? Thanks!

**Comment by jacobjiangwei** [comment]
Here is the script https://github.com/crittercism/crittercism-example-apps/blob/master/ios/Crittercism/dsym_upload.sh

发自我的 iPhone

**Comment by TKBurner** [comment]
Thanks @jacobjiangwei! How are you calling this from your lane? Are you using `sh`

**Comment by jacobjiangwei** [comment]
Yes, sh

发自我的 iPhone

**Comment by mfurtak** [comment]
@jacobjiangwei What version of `fastlane` are you using?

If you add `sh 'date'` to your lane, can you see the date output during your run?

**Comment by jacobjiangwei** [comment]
Are you saying this because it should work or it's just experimenting?

发自我的 iPhone

**Comment by mfurtak** [comment]
The default behavior of `sh` within the lane is to print the output of the command that is run. When I include `sh 'date'` in my lane, I see the date printed out. If you try it, do you see the same?
