### ISSUE TITLE
Stuck creating fastlane folder

### ISSUE THREAD

**Issue by katgironpe** [fastlane/fastlane#5931]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Setup stuck at creating a new folder.

```
 fastlane init --verbose                                                                                                          
DEBUG [2016-08-29 18:17:20.76]: Checking if there are any plugins that should be loaded...
INFO [2016-08-29 18:17:20.76]: Detected iOS/Mac project in current directory...
INFO [2016-08-29 18:17:20.77]: This setup will help you get up and running in no time.
INFO [2016-08-29 18:17:20.77]: fastlane will check what tools you're already using and set up
INFO [2016-08-29 18:17:20.77]: the tool automatically for you. Have fun!
INFO [2016-08-29 18:17:20.77]: Created new folder './fastlane'.
```

### Environment

fastlane version (run `fastlane -v`): `1.101.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? `rbenv`

I use Ruby version `2.3.1`

**Comment by katgironpe** [comment]
Closing issue. It's probably because I installed with `sudo`.

**Comment by TKBurner** [comment]
@katgironpe Let me know if you are still running into any issues getting up and running. Thanks!
