### ISSUE TITLE
itc_service_key cache directory

### ISSUE THREAD

**Issue by chrhsmt** [fastlane/fastlane#5952]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have some feature of fastlane running on Linux OS, and that itc_service_key cache directory is not valid directory path in default state on Linux.
I guess that it is needed that cache directory is depends on each OS.

reference: #5887 

##### Complete output when running fastlane, including the stack trace and command used

```
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/deploy/Library/Caches/spaceship_itc_service_key.txt
       	from /home/deploy/.bundler/mozart/ruby/2.3.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:330:in `write'
       	from /home/deploy/.bundler/mozart/ruby/2.3.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:330:in `itc_service_key'
       	from /home/deploy/.bundler/mozart/ruby/2.3.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:276:in `block in send_shared_login_request'
```

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.101.0

**Comment by mfurtak** [comment]
Hi @chrhsmt - Thanks for the report 👍  As you say, this path does seem to be a bit too Mac specific.

/cc @KrauseFx

**Comment by nitramb** [comment]
Hello,

Just thought I would add in that this also is happening on enterprise accounts, which I wouldn't of thought it needed to have a itc_service_key cached, assuming itc is for itunes connect.

Also running on a simpler setup to chrhsmt, linux box on centos 6

[1] pry(main)> require "spaceship"
=> true
[2] pry(main)> Spaceship.login("******************", "**********")
Errno::ENOENT: No such file or directory @ rb_sysopen - /root/Library/Caches/spaceship_itc_service_key.txt
from /usr/local/rvm/gems/ruby-2.3.0/gems/spaceship-0.32.0/lib/spaceship/client.rb:330:in `write'
[3] pry(main)> quit
[root@app_server portal]# fastlane -v
fastlane 1.102.0

**Comment by KrauseFx** [comment]
Thanks for the reports, looking into this right now 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/pull/5980, which should fix the issue 👍
