### ISSUE TITLE
Scan  xcodebuild -list timed-out after 10 seconds

### ISSUE THREAD

**Issue by n4me1ess** [fastlane/fastlane#5953]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
 I used Scan for running my XCUI Tests. On the one mac mini i have an error " xcodebuild -list timed-out after 10 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT". I tried to set env var by export (I can see this var by printenv)
, but it doesn't help me. Should I 
a)somehow set FastFile or 
b) set this variable as param of scan like "scan -p 'FASTLANE_XCODE_LIST_TIMEOUT=120'" or 
c) need to necessarily use fastlane for that (i do not wanna provide apple ID for that)

##### Complete output when running fastlane, including the stack trace and command used

```
scan -s 'MyScheme'
[!] xcodebuild -list timed-out after 10 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT[0m
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`): scan 0.11.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by TKBurner** [comment]
Hi @n4me1ess Here is an example lane with env setup:

```
  lane :my_app_continuous do
    ENV['APP'] = "ch.my.app.name"
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '600'
    ENV['FL_UNLOCK_KEYCHAIN_PATH'] = 'login.keychain'
    ENV['FL_UNLOCK_KEYCHAIN_PASSWORD'] = 'password' 
    unlock_keychain
  end
```

**Comment by n4me1ess** [comment]
Tnx, @TKBurner . Maybe it will help smb, I decide my problem by ` fastlane scan1`, my Fastfile:
```
desc "Runs all the tests" 
 lane :scan1 do 
  ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120" 
  scan(scheme: "MyScheme") 
 end
```
