### ISSUE TITLE
Cocoapods verification failed for bundler 

### ISSUE THREAD

**Issue by Mehdzor** [fastlane/fastlane#5954]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When cocoapods gem is installed using bundler but not globally, then cocoapods action fails. 

Steps to repeat:
- Uninstall cocoapods completely
- Install cocoapods using bundle install
- Run fastlane run cocoapods 
##### Complete output when running fastlane, including the stack trace and command used

```
Snow:iOS jenkins$ fastlane run cocoapods
[14:50:09]: -----------------------
[14:50:09]: --- Step: cocoapods ---
[14:50:09]: -----------------------
[14:50:09]: Could not find gem 'cocoapods'
[14:50:09]:
[14:50:09]: If you installed fastlane using `sudo gem install fastlane` run
[14:50:09]: $ sudo gem install cocoapods
[14:50:09]: to install the missing gem
[14:50:09]:
[14:50:09]: If you use a Gemfile add this to your Gemfile:
[14:50:09]:   gem 'cocoapods'
[14:50:09]: and run `bundle install`

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
fastlane_version "1.94.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods(use_bundle_exec: true)
  end
....
end

### Environment

fastlane version (run `fastlane -v`): 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv
```

**Comment by mfurtak** [comment]
When you say that you "Install cocoapods using bundle install", that implies that you have a `Gemfile`? If so, can you post its contents? 👍

**Comment by Mehdzor** [comment]
It does.

# coding: utf-8
source 'http://rubygems.org'
gem 'cocoapods', '1.0.1'

**Comment by mfurtak** [comment]
Ok. My suspicion is that your Bundler gem environment is separated from your system Ruby gems. 

If you want to use Bundler to manage your gems, you'll want to tell it about all of your requirements and then use `bundle exec` to run your commands to ensure that your Bundler configuration is respected. 🙌 

What happens if you adjust your Gemfile to be the following:

```ruby
source 'http://rubygems.org'

gem 'cocoapods', '1.0.1'
gem 'fastlane'
```

then run `bundle install`, then run `bundle exec fastlane run cocoapods`?

**Comment by Mehdzor** [comment]
Yes.

It fails when run from Fastfile as well.

**Comment by Mehdzor** [comment]
I guess the issue caused by a gem verification.

**Comment by mfurtak** [comment]
Hm, I'm at a loss. I don't know how to further investigate what you're seeing, so I'm going to mark this as **help wanted** to ask for help from other folks in the community!

**Comment by KrauseFx** [comment]
@Mehdzor In what directory do you have the Gemfile? Can you share your Gemfile.lock with us?

**Comment by Mehdzor** [comment]
I would provide the lock file later next week. 

My personal guess about the issue that problem is about Actions.verify_gem method. 
I'm not sure that a Gem::Specification.find_by_name method looks into bundle installed gems. 

So when gem is not presented in any way in the system the method fails.
