### ISSUE TITLE
[Request] Add support for specifying files to process in Frameit

### ISSUE THREAD

**Issue by dombarnes** [fastlane/fastlane#5971]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Feature Description

Frameit currently processes all files found un any sub-folder of the current working dir. It would be useful to support specifying options, such as a filename filter, device size, language, etc to limit processing to just those required.
If I change the text title in my strings file, I have to reprocess frameit for all screenshots, which with a universal binary is 30 per language.  
For example, I could run something like the following to redo ad hoc screenshots.

```
frameit --device=iphone6
frameit *Settings.png
frameit --language=en-gb
frameit en/*
frameit en/en-4.0-*
```

**Comment by TKBurner** [comment]
Hi @dombarnes Great idea! I've marked this as a feature request and added the help wanted flag to see if anyone is interested in submitting a PR. Thanks!
