### ISSUE TITLE
Docs on resign bundle version are wrong

### ISSUE THREAD

**Issue by samskiter** [fastlane/fastlane#5978]
### Issue Description

Your docs state that the bundle_version and version arguments to `resign` update `CFBundleIdentifier` - that should say `CFBundleVersion` no?

While I'm here, is there any way to set the version through gym? I'd like by builds to be numbered when they are built despite resigning.

**Comment by TKBurner** [comment]
Hi @samskiter Thanks for reaching out. That is correct? Any chance you want to update the docs in a PR? You might be able to do this in gym using the --xcargs or --xcconfig parameters. Thanks!

**Comment by samskiter** [comment]
OK could I submit a feature request to have gym set the version strings?

**Comment by samskiter** [comment]
Done :)

**Comment by TKBurner** [comment]
Hi @samskiter Awesome! Thanks 👍 Yes please submit a separate issue with your feature request so I can mark it and we can track it appropriately!

**Comment by samskiter** [comment]
Done https://github.com/fastlane/fastlane/issues/5995
