### ISSUE TITLE
Can't update gym. "gym 1.8.0 is available. You are on 1.7.0."

### ISSUE THREAD

**Issue by zapjonny** [fastlane/fastlane#5983]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
(not using fastlane)
- [v] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I get the message "gym 1.8.0 is available. You are on 1.7.0." in build logs.
Indeed on command line, "gym -v" says 1.7.0.
However "sudo gem update gym
Updating installed gems
Nothing to update
"

##### Complete output when running fastlane, including the stack trace and command used
```
(not using fastlane)
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
(not using fastlane)
```

### Environment

fastlane version (run `fastlane -v`):
-bash: fastlane: command not found

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
I don't think so.

**Comment by KrauseFx** [comment]
Can you try doing so without sudo?

**Comment by zapjonny** [comment]
Same. It seems happy at 1.7.0. Well, I don't really have a problem with gym at current version.

> gem update gym
> Updating installed gems
> Nothing to update

**Comment by zapjonny** [comment]
No real problem... so I'll just close this for now...

**Comment by TKBurner** [comment]
@zapjonny Can you run ruby -v and send the output? Also, does gym update if you run sudo gem update fastlane?

**Comment by mixdesign** [comment]
The same problem. It doesn't cause the problem but, I like to have latest versions.
I get green message while running lane including gym:
```
#######################################################################
# gym 1.9.0 is available. You are on 1.8.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update gym'.
#######################################################################
```
Gym version:
```
almas$ gym -v
gym 1.9.0
```
Ruby version:
```
almas$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
```
Fastlane update with sudo
```
almas$ sudo gem update fastlane
Updating installed gems
Nothing to update
```
I use fbenv, so:
```
almas$ which fastlane
/Users/almasadilbek/.rbenv/shims/fastlane
```
And where is the hidden version 1.8.0?

**Comment by zapjonny** [comment]
I'm not sure what happened but I could only update to 1.9.0 by uninstalling then installing again.

**Comment by mixdesign** [comment]
There are 1.9.0, 1.8.0 versions. I've uninstalled 1.8.0; But when I running lane with `gym` action I get:
```
Could not find gym-1.8.0 in any of the sources
Run `bundle install` to install missing gems.
```
Running `bundle install` installs old 1.8.0 version.
If I find where fastlane hardcoded that specific version for `gym`, it would be one step to resolve this problem.

**Comment by KrauseFx** [comment]
@mixdesign Try `bundle update`
