### ISSUE TITLE
gym xcargs set multiple user defined values

### ISSUE THREAD

**Issue by zake1989** [fastlane/fastlane#5987]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

basically, I need to set two user defined values and with some search I find xcargs to set one. However I still couldn't find a way to set multiple values with xcargs

here is one of my gym setting in fastfile
Fastfile:

    gym(
      	workspace: 'HBGC.xcworkspace',
      	scheme: 'HBGC',
      	clean: true,
      	configuration: 'release',
      	use_legacy_build_api: true,
      	output_directory: "/Users/zeng/Desktop/",
      	silent: true,
      	xcargs: "USE_API_SETTING=1 USE_CHANNEL_SETTING=1",
    	)

### Environment

fastlane 1.101.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by frisocki** [comment]
What does the final xcodebuild command look like that gym outputs in the log?

What build setting is being set and which one is not when you try to specify two?

What is the output from

```bash
xcodebuild -target [your_target] -showBuildSettings | grep USE_
```

**Comment by zake1989** [comment]
Problem solved. I just got the syntax wrong, it should be
 "USE_API_SETTING='1' USE_CHANNEL_SETTING='1'" .
