### ISSUE TITLE
Screengrab timestamp in screenshot name

### ISSUE THREAD

**Issue by kwasny2** [fastlane/fastlane#5988]
### Issue Description

I need possibility to skip time stamp in screenshot name.
Could you implement some parameter to optionally skip it (maybe as part of strategy definition).

Currently I am overriding FileWritingScreenshotCallback to achieve expected behaviour:

```
        String screenshotFileName = screenshotName + NAME_SEPARATOR + System.currentTimeMillis() + EXTENSION;
```

to 

```
        String screenshotFileName = screenshotName  + EXTENSION;
```
### Environment

screengrab version 0.5.0

**Comment by kwasny2** [comment]
We have some static htmls with embedded constant screenshot filenames. It will be very useful if screengrab has possibility to skip timestamp generation, so we can reuse the same htmls every time when new screenshot are generated.

**Comment by TKBurner** [comment]
@kwasny2 Great idea! I'm going to mark this as a feature request and see if the community is interested in implementing it. Thanks!

**Comment by mfurtak** [comment]
Hi @kwasny2 - thanks for the feedback!

You are doing the right thing by overriding the behavior, as the `ScreenshotCallback` is intended to be the way to customize how captured screenshots are stored. 👍 

I believe that such customizations are preferable to a set of options that alter the default behavior. Is there some way that this approach didn't meet your needs?
