### ISSUE TITLE
gym: xcodebuild -list timed-out after 10 seconds

### ISSUE THREAD

**Issue by devluyy** [fastlane/fastlane#5989]
I use this command 
 gym --workspace ${workspace_path} --scheme ${scheme} --clean --configuration ${configuration} --archive_path ${archive_path} --export_method ${export_method} --output_directory ${output_path} --output_name ${ipa_name}

then ,i get a isssue
xcodebuild -list timed-out after 10 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT

because i just use gym command, so i cann't set  EVN[FASTLANE_XCODE_LIST_TIMEOUT]
how i can fix it ,thanks for you help!

**Comment by TKBurner** [comment]
HI @devluyy Thanks for reaching out. You can including the ENV command before your gym command in the same line and it'll work. Let me know how it goes!

**Comment by devluyy** [comment]
It's work. Sorry for the slow replay!
