### ISSUE TITLE
Allow version to be set through gym

### ISSUE THREAD

**Issue by samskiter** [fastlane/fastlane#5995]
### Issue Description

Right now I'm using `resign` purely to give my app a different version.

It would be great to be able to do that from Gym instead.

Our requirement for this is because we want to pull in the build numbers from our CI as part of the version and we would like to tie it to the actual build, not resigning.

**Comment by TKBurner** [comment]
@samskiter Thanks for submitting this. Sounds like a cool idea. I'm going to mark this to get community feedback! Thanks!

**Comment by programmin1** [comment]
Why don't you change it in the xml plist file before running Gym?

**Comment by mfurtak** [comment]
Hi @samskiter - do any of these actions get you what you need? https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#modifying-project

**Comment by samskiter** [comment]
@mfurtak I think we might be able to use the update plist action, but the increment version number stuff won't work as we need to set a number from our CI

**Comment by mfurtak** [comment]
@samskiter Great! Do you think `update_info_plist` can get your CI-provided version number into the plist?

**Comment by samskiter** [comment]
@mfurtak sure. This feature would still be useful. If it's valid to pop it in the resign lane, may was well have it in the gym lane as well?

**Comment by mfurtak** [comment]
@samskiter While I understand where you're coming from, part of our job needs to be keep each individual tool as sharp and focused as possible. If there's a good way to solve the problem, we should aim to avoid adding more complexity to _gym_ to solve it in another way. 👍 

Taking another look at `increment_version_number` and `increment_build_number`, each seems to support specifying an exact value to be set. Had you seen those options? Would that also work?

**Comment by samskiter** [comment]
Fair enough  - those tools will do the trick - will make sure we switch over soon! Thanks 👍

**Comment by mfurtak** [comment]
Really excellent question - thanks for chatting it out!
