### ISSUE TITLE
crashlytics upload fails on occassion 

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#5999]
### New Issue Checklist
- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Crashlytics upload fails on occassion. Need a retry flag. 
##### Complete output when running fastlane, including the stack trace and command used

```
[11:00:12]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[11:01:11]: 2016-09-03 11:00:12.894 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (17)
2016-09-03 11:00:29.468 submit Crashlytics: Added Release Notes Successfully 200
2016-09-03 11:00:29.879 submit Crashlytics: Added Testers/Groups Successfully 200
2016-09-03 11:01:11.722 submit Crashlytics: Unable to submit build. Response code: 0
2016-09-03 11:01:11.800 submit Crashlytics: Failed to upload binary
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:
Not reproducing the entire Fastfile to save time removing all the non-public info. But the following are the two relevant commands that worked dozens of times but once or twice a week fail during the upload phase.

Fastfile:

``` ruby
        gym(
            workspace: 'MyApp.xcworkspace',
            scheme: app['scheme'],
            output_directory: "archives",
            clean: false, use_legacy_build_api:true, include_bitcode:false
        )

        crashlytics(
            #notes: change_log
            notes_path: File.expand_path("beta-release-notes.txt"),
            groups: ['testers']
        )
```
### Environment

fastlane version (run `fastlane -v`):
1.102.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by TKBurner** [comment]
Hi @lakamsani Any chance you want to implement this in the crashlytics action? We'd love to see a PR 👍

**Comment by lakamsani** [comment]
sure. if someone has a pointer on where to start that might speed things up. In the meantime I will review the code and try to get started. is there any coding guidelines/PR notes for fastlane?

**Comment by TKBurner** [comment]
Hi @lakamsani Check out this page for some info on contributing https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md. It should have most of the information you need! Thanks!

**Comment by simonrice** [comment]
If it helps at all, a slight workaround I've been doing for the time being is something like this:

```
    tries = 3
    begin
      crashlytics(
        # Parameters go here
      )
    rescue Exception => e
      tries -= 1
      if tries > 0
        retry
      else
        raise e
      end
    end
```

However, it goes without saying a `retry` parameter for the Crashlytics action would be much nicer!  And I'm sure there's a neater version where `retry` has been implemented in other fastlane actions.

**Comment by TKBurner** [comment]
@simonrice Thanks so much for sharing!
