### ISSUE TITLE
Fastlane fails on IDFA step on itunes connect

### ISSUE THREAD

**Issue by pieisgood** [fastlane/fastlane#600]
If there are options for setting the IDFA requirements for an app, in the deliver file or otherwise I'm not aware of them. Not having these options for apps that use the IDFA causes a crash when submitting to Apple. Not the biggest issue, and likely born of ignorance on my part. Any help would be Baller.

**Comment by KrauseFx** [comment]
Sorry, it seems like there is an issue with that: https://github.com/KrauseFx/deliver/issues/306

In the mean-time you'll have to manually submit the app for review, you can still upload everything using `deliver` using the `--skip-deploy` flag.
