### ISSUE TITLE
gym: error: unable to rename temporary 'xx-yy' to output file 'xx': 'No such file or directory'

### ISSUE THREAD

**Issue by cybertk** [fastlane/fastlane#6002]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When running fastlane gym on a VirtualBox VM, it often failed with **error: unable to rename temporary 'xx-yy' to output file 'xx': 'No such file or directory'**

This issue is same as https://github.com/fastlane/fastlane/issues/4692
##### Complete output when running fastlane, including the stack trace and command used

```
+---------------------------+--------------------------------------------------------------+
|                                  Summary for gym 1.8.0                                   |
+---------------------------+--------------------------------------------------------------+
| scheme                    | A                                                       |
| workspace                 | A/A.xcworkspace                                    |
| include_bitcode           | false                                                        |
| output_name               | A                                                  |
| codesigning_identity      | iPhone Distribution: XX |
| provisioning_profile_path | ./fastlane/provisions/x-general-inhouse.mobileprovision |
| export_method             | enterprise                                                   |
| destination               | generic/platform=iOS                                         |
| clean                     | false                                                        |
| output_directory          | .                                                            |
| silent                    | false                                                        |
| use_legacy_build_api      | false                                                        |
| buildlog_path             | ~/Library/Logs/gym                                           |
+---------------------------+--------------------------------------------------------------+

[02:22:46]: $ set -o pipefail && xcodebuild -workspace A/A.xcworkspace -scheme S -destination 'generic/platform=iOS' -archivePath '/Users/vagrant/Library/Developer/Xcode/Archives/2016-05-13/A 2016-05-13 02.22.46.xcarchive' archive | tee /Users/vagrant/Library/Logs/gym/A-A.log | xcpretty
[02:22:48]: ▸ Building Pods/Pods-AFNetworking [Release]
[02:22:48]: ▸ Check Dependencies
[02:22:48]: ▸ Precompiling Files/Pods-AFNetworking/Pods-AFNetworking-prefix.pch
[02:22:56]: ▸ Precompiling Files/Pods-AFNetworking/Pods-AFNetworking-prefix.pch
[02:22:58]: ▸ Precompiling Files/Pods-AFNetworking/Pods-AFNetworking-prefix.pch
...(hide verbose build log)
[17:59:44]: ▸ Compiling JSONAPI.m
[17:59:44]: ▸ Compiling JSONHTTPClient.m
[17:59:44]: ▸ Compiling JSONKeyMapper.m
[17:59:44]: ▸ Compiling JSONModel+networking.m
[17:59:44]: ▸ ❌  error: unable to rename temporary '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/JSONModel+networking-5cdab4.bc-ccc7bbb4' to output file '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/JSONModel+networking-5cdab4.bc': 'No such file or directory'
[17:59:44]: ▸ Compiling JSONModel.m
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
opt_out_usage
fastlane_version "1.102.0"
default_platform :ios
platform :ios do
  lane :test do
    gym
  end
end
```
### Environment

fastlane version (run `fastlane -v`): fastlane 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by cybertk** [comment]
It's not 100% reproduce, and the error is occurred while compiling source code. So I think it's not problem of code signing.

**Comment by TKBurner** [comment]
Hi @cybertk Can you share you full input to you gym command? I want to take a look. Thanks!

**Comment by cybertk** [comment]
Full gym parameter is attached,

```
    gym(
      scheme: "A",
      workspace: "A/A.xcworkspace",
      include_bitcode: false,
      output_name: "A.ipa",
      codesigning_identity: "iPhone Distribution: XX",
      provisioning_profile_path: "./fastlane/provisions/x-general-inhouse.mobileprovision",
      export_method: "enterprise"
    )
```

**Comment by TKBurner** [comment]
@cybertk Do you have read and write access to that temporary folder from the command line in VirtualBox? Thanks!

**Comment by cybertk** [comment]
Yes, I have. It's reproduce at ~5% percent. So most time it works fine, and I used the same VM snapshot for every build job.

**Comment by TKBurner** [comment]
Hi @cybertk Can you let me know if the issue is ever reproducible by running the command `set -o pipefail && xcodebuild -workspace A/A.xcworkspace -scheme S -destination 'generic/platform=iOS' -archivePath '/Users/vagrant/Library/Developer/Xcode/Archives/2016-05-13/A 2016-05-13 02.22.46.xcarchive' archive | tee /Users/vagrant/Library/Logs/gym/A-A.log | xcpretty`

Thanks!

**Comment by cybertk** [comment]
I tried to use the underlying scripts (instead of gym) for ~200 times, can not reproduce the issue.

**Comment by TKBurner** [comment]
@cybertk Thanks for following up. I've marked this to see if we can get some help from the community. 👍

**Comment by cybertk** [comment]
This issue is still there on latest gym 1.12.0

**Comment by TKBurner** [comment]
@cybertk Sorry to hear that! We'll leave this open until we've confirmed this issue is no longer affecting anyone. Thanks!
