### ISSUE TITLE
Can't run update_fastlane

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#6006]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Reading through the `fastlane`'s default file, I stumbled upon:

```
# If you want to automatically update fastlane if a new version is available:
# update_fastlane
```

Trying to run it in terminal exits with not found error. How to run that command?

**Comment by spilbuildserver** [comment]
`fastlane run update_fastlane`

**Comment by iCarambaa** [comment]
`fastlane run update_fastlane`

**Comment by revolter** [comment]
Firstly, that command is not documented [here][1], and I strongly believe it should.

Secondly, after running that command, I get this:

```
[23:54:18]: -----------------------------
[23:54:18]: --- Step: update_fastlane ---
[23:54:18]: -----------------------------
[23:54:18]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, match, pem, pilot, produce, scan, screengrab, sigh, snapshot, spaceship, supply...
[23:54:18]: The update_fastlane action requires rubygems version 2.1.0 or greater.
[23:54:18]: Please update your version of ruby gems before proceeding.
[23:54:18]: $ gem install rubygems-update
[23:54:18]: $ update_rubygems
[23:54:18]: $ gem update --system
```

And after running `update_rubygems` I get this:

```
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Library/Ruby/Site/2.0.0/rubygems
```

I don't think it's safe to run it with `sudo`. And if it was, it, again, should have been mentioned in the first output.

  [1]: https://github.com/fastlane/fastlane/blob/3ec18cafc982e66b14daa8149e35a81899a06677/fastlane/docs/Actions.md#update_fastlane

**Comment by iCarambaa** [comment]
For the first part I think you're right that it should be at least mentioned.

The second part simply says that you need a different ruby version. You can use rbenv or whatever to do that.

**Comment by revolter** [comment]
I don't have any knowledge of ruby, so as a first time user of `fastlane`, I find it a bit harder to integrate than it could be. I don't say `fastlane` should teach the user about rbenv, but a link to a tutorial would help.

**Comment by TKBurner** [comment]
@revolter Thanks for reaching out about this. What happens if you run `sudo gem update fastlane`


Thanks!

**Comment by revolter** [comment]
It correctly updates `fastlane`, or prints

> Updating installed gems
Nothing to update

if it's up to date. Is `update_fastlane` the same thing? I thought it updates configuration files like `snapshot` does. For example, the

```
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"
```

part in the `Fastfile`. Or should I update it manually to `1.102.0`?

**Comment by KrauseFx** [comment]
`fastlane_version` will ensure you have a certain version installed, and doesn't actually update itself. It is recommended to use a Gemfile, more information in the [docs](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile) 👍
