### ISSUE TITLE
Snapshot man page not clear

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#6007]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Upon running `snapshot -h`, I stumbled upon `-c, --clean [VALUE]  Should the project be cleaned before building it? (SNAPSHOT_CLEAN)`, but couldn't find in that man page or here on github how to run it automatically. Tried adding `SNAPSHOT_CLEAN true` to the `Snapfile` with no success.

Not understanding how to properly use basic settings gets really frustrating. I think that the docs could be hugely enhanced to make them clearer.

**Comment by TKBurner** [comment]
Hi @revolter Thanks for reaching out. If you add the 

clean: true 

parameter to your snapshot command, it should function as expected. Thanks!

**Comment by revolter** [comment]
Can you show me an example of a full command? Is it `snapshot clean: true`?

**Comment by TKBurner** [comment]
Hi @revolter Try `snapshot --clean true`

**Comment by revolter** [comment]
I want for it to default to `true` when running `snapshot` (e.g. adding it in the `Snapfile`). Is this possible?

**Comment by KrauseFx** [comment]
Yes, as @TKBurner posted in https://github.com/fastlane/fastlane/issues/6007#issuecomment-245040530 add the following to your Snapfile:

```ruby
clean true
```

and then run `snapshot` without parameters

**Comment by revolter** [comment]
Ok, thanks.
