### ISSUE TITLE
Snapshot add_photos destination location

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#6008]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The snapshot [README][1] says that you can use the `add_photos` option to add photos to the simulator before running snapshot, but it doesn't tell how to use them, where are they added, how to load them in code.

  [1]: https://github.com/fastlane/fastlane/blob/master/snapshot/README.md

**Comment by KrauseFx** [comment]
This will add the screenshots to the photo library of your iOS simulator, so you can access them from within your app. This is UI Testing related, and not something fastlane would do 👍

**Comment by revolter** [comment]
I understand. Do you consider that your answer could find a place in the readme? Or a link to a `UI Testing` documentation that explains the `add_photos`? It would greatly help new users to understand that `fastlane`'s `add_photos` is just a wrapper over a native command.

**Comment by TKBurner** [comment]
@revolter We'll add this to our docs requests. Thanks!
