### ISSUE TITLE
[question] supply is spaceship for android?

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#6009]
Hi Guys

We are using on our app spaceship to upload and edit the locales , screenshoots. Now we would like to to same with Android

Can we use supply to the same thing. Supply is equivalent of SpaceShip but for android ?

Thanks a lot

**Comment by KrauseFx** [comment]
It's not, supply is like deliver for Android. There is an official API client for Google Play for all major languages, you don't need to use fastlane if you want more control 👍

**Comment by bolom** [comment]
@KrauseFx thanks a lot !
