### ISSUE TITLE
[pilot] Add support for metadata

### ISSUE THREAD

**Issue by iCarambaa** [fastlane/fastlane#6011]
### New Issue Checklist
- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

If you want to distribute a testflight build to external testers you need to provide some metadata like feedback mail or urls. For App Store builds there is the possibility to add metadata directly from deliver and the same would be awesome for pilot.
##### Complete output when running fastlane, including the stack trace and command used

```
The request could not be completed because:
    What to Test is required. Beta App Description is required. Feedback emails must be in the format: contact@example.com. Feedback emails are required. The marketing URL you entered is invalid. Make sure you entered it correctly and try again. Marketing URLs are required. The phone number is missing. The email must be in the format: contact@example.com. The email is required. Enter a demo account user name, or deselect "A demo account is required to use all the features of the app." Enter demo account password, or deselect "A demo account is required to use all the features of the app." What to Test is required. Beta App Description is required. Feedback emails must be in the format: contact@example.com. Feedback emails are required. The marketing URL you entered is invalid. Make sure you entered it correctly and try again. Marketing URLs are required. The email must be in the format: contact@example.com. The email is required. The phone number is missing. Enter a demo account user name, or deselect "A demo account is required to use all the features of the app." Enter demo account password, or deselect "A demo account is required to use all the features of the app." Validation errors[0m
Build step 'Execute shell' marked build as failure
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
pilot(distribute_external: true)
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv, ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by TKBurner** [comment]
@iCarambaa Thanks for reaching out. You'll need to fill out basic metadata in iTC before you can use pilot. Let me know how it goes after  you try again. Thanks!

**Comment by mfc19** [comment]
@TKBurner I am getting this same error.  what basic metadata needs to be filled out in iTC?  I feel I have filled it out and still getting the error.

**Comment by milch** [comment]
@mfc19 Did you fill out the fields described in the error? You should be able to find them by going into iTunes Connect -> TestFlight -> External Testing and then clicking on "Add Build to Test". When you select a build there should be a pop up with "Test Information" where you can enter all the required fields.

**Comment by mfc19** [comment]
Yes I know I can enter the fields there but isn't that the point of the automation? So we don't have to go into the UI to fill them out?  I am populating those fields in my script.

**Comment by TKBurner** [comment]
@mfc19 Thanks for reaching out. Do you have to do this once per app or each time you upload a build? You can use the submission_information in `deliver` to setup most of this.

**Comment by mfc19** [comment]
it happens for every app I try to submit for beta review

**Comment by mfc19** [comment]
This is what I am using:
def submit_beta(app, config, build_train)
      build_train = app.build_trains[config.version]
      raise 'No build train found for version ' + config.version + ' of ' + config.identifier if !build_train

      latest_build = build_train.latest_build
      raise 'No build found for version ' + config.version + ' of ' + config.identifier if !latest_build

      reviewInfo = {
        changelog: 'text here',
        description: 'preview of app ' + config.version,
        feedback_email: 'email@myemail.com',
        marketing_url: 'http://www.website.com',
        first_name: config.beta_test.review_info.first_name,
        last_name: config.beta_test.review_info.last_name,
        review_email: 'email@myemail.com',
        phone_number: config.beta_test.review_info.phone_number,
        significant_change: false,
        review_user_name: config.beta_test.review_info.demo_user,
        review_password: config.beta_test.review_info.demo_password,
        review_notes: 'None',
        encryption: false
      }
      
      begin
        latest_build.submit_for_beta_review!(reviewInfo)
      rescue
        # For some reason, it fails validation the first time (even in the UI)
        puts 'Trying again one more time for ' + config.identifier
        latest_build.submit_for_beta_review!(reviewInfo)
      end
    end

**Comment by TKBurner** [comment]
Hi @iCarambaa You should use deliver directly. Let me know how it goes.
