### ISSUE TITLE
[Question] How to persist (string) result of a lane between different runs of fastlane?

### ISSUE THREAD

**Issue by phlippieb** [fastlane/fastlane#6012]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Context: I am trying to improve my Fastfile by taking a lane with several actions and breaking it up into smaller, retry-able lanes. Here is the current lane (the important bits, anyway):

```ruby
lane :beta do
    increment_build_number

    changelog = changelog_from_git_commits(
        pretty: '- (%ae) %s',
        include_merges: false)

    gym(
        silent: true,
        verbose: false,
        scheme: "STAGING",
        use_legacy_build_api: true)

    crashlytics(
        api_token: "[redacted]",
        build_secret: "[redacted]",
        groups: "[redacted]",
        notes: changelog)
end
```

The problem with this setup is that the steps tend to fail. For example, after `gym` has run for ~ 15 minutes to complete, `crashlytics` can randomly fail due a flaky connection. When that happens, I would like to be able to run `crashlytics` again, without needing to run `gym` again. So I'm trying to split it up into lanes like these:

```ruby
lane :beta_changelog do
   changelog_from_git_commits(
      pretty: '- (%ae) %s',
      include_merges: false)
end

lane :beta_build do
   gym(
      silent: true,
      verbose: false,
      scheme: "STAGING",
      use_legacy_build_api: true)
end

lane :beta_upload do
   crashlytics(
      ipa: "./build/STAGING.ipa"
      api_token: "[redacted]",
      build_secret: "[redacted]",
      groups: "[redacted]",
      notes: changelog)
end
```

The main issue I'm facing is that fastlane is no longer passing the result of each action on the next, so I need to make sure each action has all the parameters it needs. I can tell `crashlytics` where the .ipa file is that it should use quite easily. I'm getting stuck on the changelog though. What I need is to persist the result of `changelog_from_git_commits` in a way that will allow me to access it the next time I run fastlane, so that if I run

```
fastlane beta_changelog
fastlane beta_build
fastlane beta_upload
```

then the `crashlytics` action in `:beta_upload` will know what the changelog was that was generated by `:beta_changelog`.

I can read bash environment variables using `sh($ENV_VAR)`, but I can't seem to set them using `sh("export ENV_VAR='" + changelog +"'")`. I'm not generally familiar with Ruby but this seems to be a restriction of the language. I can use `sh("echo \""+ changelog + "\" > ~/tmp/changelog")` and `changelog = sh("cat ~/tmp/changelog")`, but that's sort of clunky. Any native solutions?

### Environment

fastlane version (run `fastlane -v`): 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
You can solve this by using Ruby exception handling
```ruby
lane :beta do
  begin
    gym
  rescue => ex
    beta # endless recursion
  end
end
```

basically in your rescue block you can call whatever you want 👍

**Comment by phlippieb** [comment]
Handy! 😸 

In case someone else is doing the same, I had a concern that if my lane looks something like this:

```ruby
lane :beta do
   begin
      gym
   rescue => ex
      beta
   end

   crashlytics
end
```

then, if gym fails once and then succeeds , `crashlytics` will be called twice - once after the successful gym, and then again when the recursive call returns to the rescue block and continues. In fact, a quick test seems to confirm that this will happen. So I added `exit(0)` right at the end of the lane, so that the first recursive call to complete the entire lane will stop all the others. Fastlane doesn't _love_ this (it always says "fastlane finished with errors", but it looks pretty safe.
