### ISSUE TITLE
[deliver][featurerequest] Use default fallback for screenshots

### ISSUE THREAD

**Issue by iCarambaa** [fastlane/fastlane#6013]
### New Issue Checklist
- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

For metadata there's a special language code "default" for resources that are not localized. I think the same does not exist for screenshots. If I create a folder "default" I get `iTunes Connect error: default isn't an activated language`. I would love to be able to define default screenshots. There are also these checkboxes `Use English (U.S.) 5.5-Inch Display` which could be used by deliver.

fastlane version (run `fastlane -v`):
fastlane 1.102.0

**Comment by TKBurner** [comment]
@iCarambaa Great idea! I'm going to leave this open and mark it as a feature request so we can see what the community thinks!

**Comment by steddyman** [comment]
I notice iTunes recently added a checkbox on all of the language pages to use the screenshots from the default language for the app.  I currently have screenshots for 10 languages but they are all the same image.  It takes a long time to generate 6 device screenshots per language, when all I need is one.

It would be great if Deliver can be updated to only upload one set of screenshots for the default language, then automatically set the checkboxes in iTunes Connect on the non-default languages.

**Comment by KrauseFx** [comment]
That's already possible, have you tried putting screenshots into a `default` directory next to your languages?

**Comment by steddyman** [comment]
I haven't. Sorry, I couldn't see anywhere in the documentation about how to do it though I did see a mention of it in one of the updates. 

How do you configure the Snapfile then? Do you just put the primary language in or use "default"? I thought Deliver relied upon the Screenshots.html created by Snapshot referencing all the files.  I had already tried creating one screenshot then creating the correct language directories under the Screenshots folder then copying a file into each. That didn't work.  When deliver previewed the upload, it showed no screenshots on any language other than the primary.

**Comment by steddyman** [comment]
Also, this other requests seems to indicate it does not have this functionality (last post):

https://github.com/fastlane/fastlane/issues/5771

**Comment by s2imon** [comment]
I've tried "That's already possible, have you tried putting screenshots into a default directory next to your languages?", but this gave me an error indicating this issue?

**Comment by TKBurner** [comment]
@s2imon Can you share your full input and output when you got that error? I'd love to take a look, it'd help us figure this out. Hope you have a great day!

**Comment by bennettrogers** [comment]
I agree that this would be a useful feature - could it be reopened? A workaround is to duplicate screenshots in each localization folder, but it would be great if Deliver could somehow "check the box" that says "Use English (U.S.) 5.5-Inch Display" for each localization. That is, assuming Apple exposes that via their APIs?
