### ISSUE TITLE
Unable to run cert and sigh

### ISSUE THREAD

**Issue by josete89** [fastlane/fastlane#6014]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Unable to run cert and sigh
##### Complete output when running fastlane, including the stack trace and command used

```
[13:02:59]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

[13:02:59]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass

[!] The request could not be completed because:
	{}
aa=3582E5BB5A96833FD7C54AECF279299F31BAF5EF10B4DFDBEE7387DE321540BAC7C2D8D4081C62048343923445F6D22409C0E23531E12476A62B7246D97A1305AC5D1CD56BC11D851227BF020A46F5AE161371F6C8B265A5470C1C42B99D898B5E619E5953626FA69403D8548DB1AB335117EF74FEB49F54F572E5011E68F618C4D59BF6BAEEC907B29B61517BF773309BEFECC06184F6A4A4D43AFA423ADBCF427DDFECBA13050B025BBC345F8D9EA1B4B3E7E9527944F8F3735E20E2C9F775E56A66BA07A416D6EE7D23A5C595A1A47D15C747F0ADC17C6EFC7F97B08179687D17027879478EB6B020E723BEA1905E49B187F1BF3500281D02F8C744EFDDF3; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=.apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=.apple.com; Path=/; Secure; HttpOnly, acn01="aBeJg2HVD0iu+3b7S9rXhtZkZaNciQ1/tnpG2PfjsGwHAAaf2EGZoVg="; Version=1; Domain=.apple.com; Max-Age=31536000; Expires=Wed, 06-Sep-2017 11:02:56 GMT; Path=/; Secure; HttpOnly
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
lane :beta do
    #import_certificates
    #ensure_git_status_clean
    #increment_build_number
    cert
    sigh(adhoc:"true",app_identifier:"io.traaq.Traaq-io.Traaq-ioWidget")
    sigh(adhoc:"true")
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID] # use the UDID of the newly created provisioning profile
    version = "#{get_version_number}.#{get_build_number}"
    #badge(shield: "Version-#{version}-blue")
    gym(scheme: "Traaq.io",clean: true,configuration:"Release")
    

    crashlytics(
        api_token: "b420169f28a8b231a6553849d4d9fa2501802a23",
        build_secret: "f93f01adc6c1d07808890a0d092b22411da932113498acf493e954d8b713fb62",
        notes: "Example",
        debug: true
      )
  end
```
### Environment

fastlane version (run `fastlane -v`):
alcaljos$ fastlane -v
fastlane 1.102.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

**Comment by TKBurner** [comment]
@josete89 Hi! Hope you are doing well. Can you run `sudo gem update fastlane`? Let me know if that resolves your issue. Thanks!

**Comment by KrauseFx** [comment]
Hey @josete89, could you run this again using `--verbose`, and share the complete output, including the stack trace with us?

**Comment by josete89** [comment]
Hi!

There we go:


Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	{}
aa=AD17C0A2B7CA16A2868E9299E63C7DB8B7C0DF2974D98507E0E05D33AF95D983734C68402DB65C0457DA0B1F7B78F24FB77FFF7AE2ED6C7E0BBA49F684F9ECA227C8C65C08CC64DDC0463E402146A7B8790DD9DC827FA2FB41AACF288B5ACCA3215B5E5210FA758DFB73B6B6B7E7DA0BD51AD546BA7D0393C19C8CDC939A28B68473E493766FECBD0947CA5B04F1A717FAB4BD8EB377913AB4E37C5699A0C6B7CD6C3A4DC1C7D9F9C292372FE9A273766F567DF21BD2CA0641C4242BA86D6FA8F0F715E0DD2F93F7DED99857B21C313F3BE04E0E52C00DF8335CD4C3EF5AC9F881B73C91F6BAD01C9705E3520C01AFA94E1A911E2253C2F33F14175AE9B8C25F; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=.apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=.apple.com; Path=/; Secure; HttpOnly, acn01="t1rCJUKoS7CplhhSw4lrkO/bl9B2Xkj46pLCvVd2lhs4AAbDE5JTEgA="; Version=1; Domain=.apple.com; Max-Age=31536000; Expires=Wed, 06-Sep-2017 21:50:34 GMT; Path=/; Secure; HttpOnly

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09%7B%7D%0Aaa=AD17C0A2B7CA16A2868E9299E63C7DB8B7C0DF2974D98507E0E05D33AF95D983734C68402DB65C0457DA0B1F7B78F24FB77FFF7AE2ED6C7E0BBA49F684F9ECA227C8C65C08CC64DDC0463E402146A7B8790DD9DC827FA2FB41AACF288B5ACCA3215B5E5210FA758DFB73B6B6B7E7DA0BD51AD546BA7D0393C19C8CDC939A28B68473E493766FECBD0947CA5B04F1A717FAB4BD8EB377913AB4E37C5699A0C6B7CD6C3A4DC1C7D9F9C292372FE9A273766F567DF21BD2CA0641C4242BA86D6FA8F0F715E0DD2F93F7DED99857B21C313F3BE04E0E52C00DF8335CD4C3EF5AC9F881B73C91F6BAD01C9705E3520C01AFA94E1A911E2253C2F33F14175AE9B8C25F;%20Domain=idmsa.apple.com;%20Path=/;%20Secure;%20HttpOnly,%20dslang=US-EN;%20Domain=.apple.com;%20Path=/;%20Secure;%20HttpOnly,%20site=USA;%20Domain=.apple.com;%20Path=/;%20Secure;%20HttpOnly,%20acn01=%22t1rCJUKoS7CplhhSw4lrkO/bl9B2Xkj46pLCvVd2lhs4AAbDE5JTEgA=%22;%20Version=1;%20Domain=.apple.com;%20Max-Age=31536000;%20Expires=Wed,%2006-Sep-2017%2021:50:34%20GMT;%20Path=/;%20Secure;%20HttpOnly+repo:fastlane/fastlane
ERROR [2016-09-06 23:50:37.47]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/client.rb:306:in `send_shared_login_request': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	{}
aa=AD17C0A2B7CA16A2868E9299E63C7DB8B7C0DF2974D98507E0E05D33AF95D983734C68402DB65C0457DA0B1F7B78F24FB77FFF7AE2ED6C7E0BBA49F684F9ECA227C8C65C08CC64DDC0463E402146A7B8790DD9DC827FA2FB41AACF288B5ACCA3215B5E5210FA758DFB73B6B6B7E7DA0BD51AD546BA7D0393C19C8CDC939A28B68473E493766FECBD0947CA5B04F1A717FAB4BD8EB377913AB4E37C5699A0C6B7CD6C3A4DC1C7D9F9C292372FE9A273766F567DF21BD2CA0641C4242BA86D6FA8F0F715E0DD2F93F7DED99857B21C313F3BE04E0E52C00DF8335CD4C3EF5AC9F881B73C91F6BAD01C9705E3520C01AFA94E1A911E2253C2F33F14175AE9B8C25F; Domain=idmsa.apple.com; Path=/; Secure; HttpOnly, dslang=US-EN; Domain=.apple.com; Path=/; Secure; HttpOnly, site=USA; Domain=.apple.com; Path=/; Secure; HttpOnly, acn01="t1rCJUKoS7CplhhSw4lrkO/bl9B2Xkj46pLCvVd2lhs4AAbDE5JTEgA="; Version=1; Domain=.apple.com; Max-Age=31536000; Expires=Wed, 06-Sep-2017 21:50:34 GMT; Path=/; Secure; HttpOnly
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/client.rb:369:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/client.rb:227:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/client.rb:90:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/portal/spaceship.rb:77:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.2/lib/cert/runner.rb:17:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.2/lib/cert/runner.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/cert-1.4.2/lib/cert/runner.rb:6:in `launch'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/actions/cert.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:190:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:175:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:174:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:100:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:36:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by josete89** [comment]
Hi @TKBurner @KrauseFx ,

Looks like my password has been expired, I've just renewed the password and now works fine!.

You can close this :)

Thanks for the fast response and sorry for the inconveniences.

**Comment by TKBurner** [comment]
@josete89 Awesome! So glad to hear you got back up and running. Hope you have a great weekend coming up! 👍
