### ISSUE TITLE
How do I sign my apk before upload to Craslytics beta?

### ISSUE THREAD

**Issue by MiralDesai** [fastlane/fastlane#6015]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I would like to use fastlane to automate creating builds when I push to master. However it requires a signed APK, and I would like to avoid putting my keystore and keystore password directly into my build.gradle and into version control. Someone suggested Jenkins environment variables to me, but when I run the lane, the build fails because it can't find the ENV variable. Do you guys have a suggested way to do this? I haven't seen any docs about this which is surprising since Crashlytics Beta requires signed apks only.

i created ENV variables in jenkins, and reference them in my gradle.properties file like so:

```
ANDROID_KEYSTORE=$ANDROID_KEYSTORE
ANDROID_STORE_PASSWORD=$ANDROID_STORE_PASSWORD
ANDROID_KEY_ALIAS=$ANDROID_KEY_ALIAS
ANDROID_ALIAS_PASSWORD=$ANDROID_ALIAS_PASSWORD
```

Do I need the full path of the ENV variables in jenkins? Because I can't seem to find that.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateReleaseSigning'.
> Keystore file /Users/office/.jenkins/workspace/AndroidTests/app/$ANDROID_KEYSTORE not found for signing config 'release'.
```

### Configuration Files

Fastfile:
```ruby
desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assemblePreprod")
    crashlytics(api_token:"xxxxxx", build_secret:"xxxxxx", groups:"test", notifications:true)
  end
```

### Environment

fastlane version (run `fastlane -v`): 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

Sorry for what might seem like a basic question. So close to getting this working and never done it before. Lots more information on iOS rather than Android

**Comment by MiralDesai** [comment]
Seems to be iOS only

**Comment by TKBurner** [comment]
@MiralDesai Thanks for reaching out about this. You will need to use Gradle to create a signed APK. We don't have any suggestions around this. After that you can use the crashlytics action to upload your build. Thanks!

**Comment by MiralDesai** [comment]
Solved by asking on StackOverflow where a fastlane employee replied: https://stackoverflow.com/questions/39366308/read-jenkins-environment-variables-in-android-project-sign-apk-for-automated-bu/39378213#39378213

For anyone else that comes here.
