### ISSUE TITLE
Sigh support for personal teams

### ISSUE THREAD

**Issue by Siguza** [fastlane/fastlane#6022]
### New Issue Checklist
- [x] Updated fastlane to the latest version (v1.102.0 at the time of writing)
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When running `sigh` with an account that isn't in any teams, we get presented with:

```
No teams available on the Developer Portal
You must accept an invitation to a team for it to be available
To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html

Looking for related GitHub issues on fastlane/fastlane...

[...]

and 45 more at: https://github.com/fastlane/fastlane/search?q=Your%20account%20is%20in%20no%20teams&type=Issues&utf8=✓
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/portal/ui/select_team.rb:41:in `select_team': [!] Your account is in no teams (RuntimeError)
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/portal/portal_client.rb:55:in `select_team'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/portal/spaceship.rb:37:in `select_team'
    from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.32.1/lib/spaceship/portal/spaceship.rb:81:in `select_team'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.10.1/lib/sigh/runner.rb:16:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.10.1/lib/sigh/manager.rb:7:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.10.1/lib/sigh/commands_generator.rb:34:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.50.3/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.10.1/lib/sigh/commands_generator.rb:98:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.10.1/lib/sigh/commands_generator.rb:11:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/sigh-1.10.1/bin/sigh:6:in `<top (required)>'
    from /usr/local/bin/sigh:23:in `load'
    from /usr/local/bin/sigh:23:in `<main>'
```

As per issue #2003 and PR #5636, this seems to be by design.  
However, [a comment](https://github.com/fastlane/fastlane/issues/2003#issuecomment-227939071) on issue #2003 states:

> Sigh could support free provisioning aka the personal team if there are no other teams as Xcode does. Looking in DVTFoundation.framework, Xcode uses the same API protocol i.e. QH65B2. Just a head's up that this functionality exists even if not exposed by the web UI.

The `[feature]` tag was added thereafter, but the issue was still closed in accordance with PR #5713.
### Feature Request

I would like for `sigh` to offer a way to use the "personal team" (aka. free provisioning) of an Apple ID.

**Comment by Siguza** [comment]
Still the same for sigh 1.11.2.

**Comment by TKBurner** [comment]
@Siguza Thanks for letting us know! We'll leave this open to track interest!

**Comment by EliyahuStern** [comment]
+1

**Comment by gaming-hacker** [comment]
still bombs, updated to the latest gems


➡️  Sigh support for personal teams
   https://github.com/fastlane/fastlane/issues/6022 [open] 5 💬
   a week ago

➡️  Crash: When no teams exist in your AppleID account
   https://github.com/fastlane/fastlane/issues/2003 [closed] 12 💬
   13 Sep 2016

➡️  Error in fastlane init. Your account is in no teams
   https://github.com/fastlane/fastlane/issues/5115 [closed] 3 💬
   12 Aug 2016

**Comment by KrauseFx** [comment]
Why do you want to use _sigh_ for personal teams? It's usually good enough to use Xcode's Fix Issue button if you just want a development profile 👍

**Comment by EliyahuStern** [comment]
My use case is an automated script that involves signing and installing already archived `ipa`s on a device.

**Comment by Siguza** [comment]
I'm trying to do provisioning from the command line and from Makefiles.

My projects are based entirely on Makefiles rather than xcodeproj's (and I'm avoiding the XCode GUI altogether), and I've been able to do every step of development this way, except for provisioning.  
So far I've been using "Cydia Impactor" to install IPAs along with provisioning profile on my devices, but a) that's another GUI and b) it asks for email and password every time, overall consuming quite a lot of time for something that I feel could be fully automated.
