### ISSUE TITLE
Distribute_external fails when the app version is not yet approved

### ISSUE THREAD

**Issue by GeovationMax** [fastlane/fastlane#6026]
### Issue Description

When running pilot with the option distribute_external active and a changelog provided I would expect the app to be submitted for beta app review.

Instead I get an error saying "This build could not be used for external testing because the build is not approved". This is fair enough and understandable. But the process should not fail on this message, but instead provide information that the app was submitted for beta app review.

Ideally I would like to automatically activate this version for testing, but I don't know if this is technically possible.

Would it be possible to implement the aforementioned behavior?

##### Complete output when running fastlane, including the stack trace and command used

```
[...]
[10:00:34]: Variable Dump:
[10:00:34]: {:PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy", :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.", :VERSION_NUMBER=>"0.2.495", :IPA_OUTPUT_PATH=>"/Users/distiller/refill/platforms/ios/build/fastlane/Refill.ipa", :DSYM_OUTPUT_PATH=>"/Users/distiller/refill/platforms/ios/build/fastlane/Refill.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/distiller/Library/Developer/Xcode/Archives/2016-09-06/Refill 2016-09-06 09.47.27.xcarchive"}
[10:00:34]: This build could not be used for external testing because the build is not approved.
[...]
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile (relevant section):
```ruby
  desc "Building and deploying ios app"
  lane :deploy do |options|
    environment = ENV["ENVIRONMENT"]
    UI.user_error!("Incorrect environment '#{environment}' specified. Use either staging or production") unless environment == "staging" || environment == "production"
    ipaPath = build(forDeployment:true, environment:environment)
    pilot({
      ipa: ipaPath,
      distribute_external: true,
      skip_waiting_for_build_processing: false,
      changelog: ENV["GIT_COMMIT_DESC"]
    })
    firebaseDeploy(environment: environment)
    ionicDeploy(environment: environment)
  end
```

### Environment

fastlane version: 1.102.0 (on CircleCI)

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by TKBurner** [comment]
Hi @GeovationMax Thanks for reaching out. Right now this is expected behavior. The lane fails because the version is not available for external testing. Thanks!

**Comment by owurman** [comment]
@TKBurner This may be expected behavior but I respectfully disagree that it's **best** behavior. When using fastlane as part of a larger script, there is no way to tell between a real failure (something went bad and I need to intervene) and the app simply being submitted for review rather than pushed to testers. Perhaps an argument can be added to allow submitted for review to be considered a non-error exit condition?

**Comment by GeovationMax** [comment]
@TKBurner I agree with @owurman. Ideally I aim to not have to go to iTunes connect at all and it would be good if this would be handled gracefully and not as an error.

**Comment by SAVeselovskiy** [comment]
@TKBurner Is there any reason for any attempts to begin external testing without beta review approval? It will always fail, because uploaded build isn't approved, isn't it? Maybe you should separate submitting for beta review and start testing?

**Comment by owurman** [comment]
I like the suggestion from @SAVeselovskiy. It makes more sense than what I suggested. Simply have a flag for whether to submit for beta review instead of push to external testing.

**Comment by petersuwara** [comment]
@SAVeselovskiy , this is a perfect suggestion.

When would you want to submit a build that's already been approved ?
I always do beta external releases that expect to be submitted. Not distribute beta external releases.

The existing state of error does not make any sense and should be a successful result. The build successfully pushed to apple for review.

**Comment by petersuwara** [comment]
Why is this issue closed ?
