### ISSUE TITLE
Gym skip code signing

### ISSUE THREAD

**Issue by samskiter** [fastlane/fastlane#6027]
### Issue Description

Could you please add option to skip code signing for gym builds - we just want to build.

We have a test app as a target in our project with a different bundle identifier to our main project - as such we don't have a provisioning profile for it - we just use this project on simulator which XCode handles just fine.

We want to test that this test project compiles as part of our integration tests, but can't make gym reproduce the build that XCode can.

Building from XCode with the simulator selected works just fine. With 'Generic iOS Device' selected it fails with a code sign error. We definitely have the wrong provisioning profile setup in the build settings (the test target just inherits from the main project) so that makes sense. Does XCode always ignore the setup and use a different signing identity when signing for the simulator?

We ARE able to get a build to work by using the xcodebuild action and setting the destination option to a simulator but your advise is not to use that and use gym instead.

I understand we have a wacky XCode project (which we are working on fixing) but it would be great to be able to say 'if it works in XCode, it works in Gym'

##### Complete output when running fastlane, including the stack trace and command used

Command run:

`gym build --destination 'platform=iOS Simulator,name=iPhone 6s,OS=9.3' --configuration 'Debug'`

Output:

```
Code Sign error: Provisioning profile does not match bundle identifier: The provisioning profile specified in your build settings (“[redacted]”) has an AppID of “[redacted]” which does not match your bundle identifier “[redacted]”
```

### Environment

fastlane version (run `fastlane -v`):

`fastlane 1.102.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

Yes

**Comment by KrauseFx** [comment]
Sorry, that's not planned, however you can use the `xcodebuild` action in fastlane to just build your app with no code signing 👍

**Comment by samskiter** [comment]
@KrauseFx that's exactly what we did, but annoyingly we had to select a simulator as the destination to force it to stop trying to code sign.

**Comment by TKBurner** [comment]
@samskiter Thanks for following up. Are you able to do it with a shell command? That's always a fallback option using the `sh` action. Thanks!
