### ISSUE TITLE
How can I change bundleid use fastlane gym?

### ISSUE THREAD

**Issue by diaojunxian** [fastlane/fastlane#6037]
This is the first time I used the `fastlane gym`,as I am a testers,I don't know much Xcode and OC.And now I git clone our app's codes,  and would like to use 'fastlane gym' build ipa.But our codes need to change Bundleid,my question is  how can I change bundleid when using`fastlane gym`?

**Comment by mfurtak** [comment]
Hi @diaojunxian - Do any of the actions here get you what you need? https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#modifying-project
