### ISSUE TITLE
Carthage action does not support project directory option.

### ISSUE THREAD

**Issue by kndl** [fastlane/fastlane#6052]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`carthage` commands have an optional `--project-directory` that can be passed. There is no matching option in the fastlane carthage action.

##### Complete output when running fastlane, including the stack trace and command used

N/A

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

I would like something like the following to work:

Fastfile:
```ruby
  desc "Deploy a new version to the App Store"
  lane :appstore do
    carthage(command: "bootstrap", platform: "iOS", project_directory: "something")
    gym(scheme: "SchemeName")
    deliver(force: true, app_identifier: "com.example.app")
    end
  end
```

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

Yes

**Comment by kndl** [comment]
I have done some work around this if you think it'd be useful. It seems pretty straightforward, for whatever that is worth.

**Comment by asfalcone** [comment]
@kndl Thanks for the report. We'd be happy to review a PR to add this option 👍

**Comment by Ashton-W** [comment]
This can be closed https://github.com/fastlane/fastlane/pull/6072

**Comment by TKBurner** [comment]
@Ashton-W Awesome! Thanks for letting me know. Hope you are having a great week! 👍 👍
