### ISSUE TITLE
match: Support specify ssh-key used to access certificates repo

### ISSUE THREAD

**Issue by cybertk** [fastlane/fastlane#6057]
Can we consider add a option like `--key` to match in order to access **certificates.git** easier?

**Comment by TKBurner** [comment]
@cybertk Great idea! I'm marking it as a feature request to see if there is more interest in the community. Thanks 👍

**Comment by rafaelnobrepd** [comment]
That would be great! 👍

**Comment by KrauseFx** [comment]
You can also use the HTTPs based auth to clone repos

**Comment by cybertk** [comment]
How to specify credentials for HTTPs based repo?

**Comment by hjanuschka** [comment]
@cybertk  you could use ssh agent - and load up all keys you have, the clone should bubble threw all of them, trying to find a working one.

or you could pin. a specific key - to a host e.g:
this goes to: `~/.ssh/config`

```
Host hostname.com
  IdentityFile ~/.ssh/github_rsa
  User git
```

you can find a good explanation at: http://nerderati.com/2011/03/17/simplify-your-life-with-an-ssh-config-file/

**Comment by TKBurner** [comment]
@hjanuschka Thanks for stepping in! 👍

**Comment by cybertk** [comment]
@hjanuschka You solution is good. But it requires a lot of pre-setup before using **match**, especially on a clean CI environment. If **match** has capability to catch those setup scripts, our life will be more easier.

**Comment by jbolter** [comment]
I would like this feature as well!  Passing a --cert would be easier since we have multiple developers using these build scripts that run match.
