### ISSUE TITLE
Default ios_version for snapshot not sensitive to device limitations

### ISSUE THREAD

**Issue by lightbow** [fastlane/fastlane#6058]
### Issue Description

iPhone 4s only supports up to iOS 9.x, while all the other device types needed for a full iTunesConnect screen size representation will work on iOS 10. For apps that support both iOS 9 and iOS 10, snapshot on the latest Xcode 8 setup doesn't succeed out of the box in a single run without creating custom simulators first. Calling `snapshot reset_simulators` clears everything out and reinstalls iOS 10-based simulators for most devices. This results in a case where setting `ios_version '10.0'` will fail on iPhone 4s, and setting `ios_version '9.3'` will fail on all other devices.

### Workaround

In Xcode 8, manually create simulators for all devices for iOS 9.3, then run snapshot with the override `ios_version '9.3'`

### Configuration Files

snapfile:
```ruby
devices([
  "iPad Air",
  "iPhone 4s",
  "iPad Pro (12.9-inch)",
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus"
])

languages([ "da", "de-DE", "el", "en-AU", "en-CA", "en-GB", "en-US", "es-ES", "fr-FR", "it", "ja", "ko", "nl", "no", "pt-BR", "ru", "sv", "tr", "zh-Hans", "zh-Hant"])

scheme "Lightbow"
stop_after_first_error true

output_directory "./Store/screenshots"
clear_previous_screenshots true

ios_version '9.3'
```

### Environment

snapshot 1.14.0, executed via just "snapshot" on the command line on macOS 10.11.6

**Comment by TKBurner** [comment]
@lightbow Hope you are doing well! Thanks for the clear explanation. I've looped in the core team for them to take a look. Thanks!

**Comment by KrauseFx** [comment]
What actions are required from our side? Is it just the sample `Snapfile` that needs to be updated, or the default value that is being determined? Can you also share your output when _snapshot_, especially the table summary in the beginning

**Comment by Harold-D** [comment]
Perhaps a good addition would be to be able to specify an "ios_version" on a device basis?

This would allow for screenshots which feature "new functionality" of a "higher iOS" version on compatible devices.

For instance the new "CallKit" feature, only available on iOS 10 thus excluding the iPhone 4s. With the ability to specify iOS version per device, you would be able to create screenshots for the iPhone 4s excluding the new CallKit features and screenshots for other devices which do show the new CallKit features.

**Comment by NicosKaralis** [comment]
Question, could we solve this problem using a more dynamic way to select the simulator?

I managed to solve this problem updating the following ``snapshot-1.14.0 lib/snapshot/test_command_generator.rb # L81``

    def find_device(device_name, os_version = Snapshot.config[:ios_version])
      devices = FastlaneCore::DeviceManager.simulators.select do |sim|
        sim.name.strip == device_name.strip and sim.os_version == os_version
      end
      return FastlaneCore::DeviceManager.simulators.select do |sim|
        sim.name.strip == device_name.strip
      end.last if devices.length != 0
      devices
    end

This could even solve the problem with multiple devices

```
# We might get this error message
# > The requested device could not be found because multiple devices matched the request.
#
# This happens when you have multiple simulators for a given device type / iOS combination
#   { platform:iOS Simulator, id:1685B071-AFB2-4DC1-BE29-8370BA4A6EBD, OS:9.0, name:iPhone 5 }
#   { platform:iOS Simulator, id:A141F23B-96B3-491A-8949-813B376C28A7, OS:9.0, name:iPhone 5 }
#
```

If someone could create a PR, this was the best solution for me

**Comment by mfurtak** [comment]
> Perhaps a good addition would be to be able to specify an "ios_version" on a device basis?

That makes sense to me. What do folks think about the following syntax?

```ruby
# A hash of device name to desired OS version
devices({
  "iPad Air" => "10.0",
  "iPhone 4s" => "9.3",
  "iPad Pro (12.9-inch)" => "10.0",
  "iPhone 5" => "10.0",
  "iPhone 6" => "10.0",
  "iPhone 6 Plus" => "10.0"
})
```

If you have no need for devices that aren't on the latest/configured OS version, we could still allow the following to work:

```ruby
ios_version '10.0'

devices([
  "iPad Air",
  "iPhone 4s",
  "iPad Pro (12.9-inch)",
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus"
])
```

**Comment by mfurtak** [comment]
I chatted with @KrauseFx about this, and he has a different solution in mind 😄

**Comment by lightbow** [comment]
You guys are wonderful, and sorry I didn't check the thread right after your reply. I have no strong opinions on syntax.

**Comment by NicosKaralis** [comment]
I strongly dislike the syntax provided by Michael. It feels dirty and complex.

The point of fastlane is to save time in a elegant way. If fastlane can (and should) find the correct device without user input then the choice is obvious.

On Xcode 6 I had some simulators named like "iPhone 4s (8.4)". On Xcode 8 you can add any device with any sdk installed with any name you want.
Fastlane should be smart enough to look by the name and ignore the "max iOS version" when needed.

My line of thought was:

- find a device with name X and iOS version of Y
- if you didn't find one yet look for one with the provided name

If you registered for an "iPhone 4s" simulator then you probably have one that is capable of running the app, if you don't have one with the latest iOS version then you have other that can perform the task

**Comment by mfurtak** [comment]
That's OK @NicosKaralis - @KrauseFx strongly disliked it as well 😄

**Comment by mfurtak** [comment]
Hi all, there's a change for this staged over on #6204. If you are able to pull that branch and give it a try, that would be very helpful!

**Comment by mfurtak** [comment]
[_snapshot_ 1.15.0](https://github.com/fastlane/fastlane/releases/tag/snapshot/1.15.0) was released with the changes from #6204. Please upgrade with `gem update snapshot`, and let us know how it looks 🚀

**Comment by NicosKaralis** [comment]
@mfurtak Its working for me

**Comment by mfurtak** [comment]
Hi folks, I'm going to close this for now, but please feel free to continue the conversation as needed! 👍
