### ISSUE TITLE
Carthage action doesn't support framework to archive specification

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#6061]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) 🔑

### Issue Description

My `xcworkspace` contains multiple frameworks that have to be archived by `Carthage`, but currently, I can only specify the command `archive` in `Carthage` action but not framework name. So I'm not able to archive all my built frameworks, but only one that picked automatically by `Carthage`

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
YES

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
`rvm`

**Comment by TKBurner** [comment]
@Antondomashnev Great to hear from you. Right now this isn't possible. I've marked this as feature request. Any chance you'd be interested in contributing a PR? Thanks!

**Comment by Antondomashnev** [comment]
@TKBurner I've already created a custom action to do it, let me clean the code and I'll create a PR=)

**Comment by TKBurner** [comment]
@Antondomashnev Awesome! 👍 We'll work with you on the PR 💯 💯
