### ISSUE TITLE
Cannot start fastlane

### ISSUE THREAD

**Issue by craigzour** [fastlane/fastlane#6066]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am unable to start fastlane.

##### Complete output when running fastlane, including the stack trace and command used

```
BuildMachine:~ builder$ fastlane

/Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source': uninitialized constant Gem::Source (NameError)
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:1747:in `gem_build_complete_path'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:1420:in `build_extensions'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `each'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/source.rb:1:in `<top (required)>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:1747:in `gem_build_complete_path'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/specification.rb:1420:in `build_extensions'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/stub_specification.rb:60:in `build_extensions'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/basic_specification.rb:56:in `contains_requirable_file?'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:68:in `block in require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `each'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `find'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:67:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.13.0/lib/bundler/rubygems_integration.rb:2:in `<top (required)>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/bundler-1.13.0/lib/bundler.rb:11:in `<top (required)>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:3:in `<class:PluginManager>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:2:in `<module:Fastlane>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugin_manager.rb:1:in `<top (required)>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.102.0/lib/fastlane/plugins/plugins.rb:9:in `<top (required)>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.102.0/lib/fastlane.rb:22:in `<top (required)>'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /Users/builder/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
	from /Users/builder/.rbenv/versions/2.1.3/bin/fastlane:23:in `load'
	from /Users/builder/.rbenv/versions/2.1.3/bin/fastlane:23:in `<main>'
```

**Comment by PetrosIchor** [comment]
I was getting very similar issues a moment ago. For me, bundler updated to 1.13 (pushed yesterday). Removing that version and rolling back fixed the fastlane and other gem related issues I was having.  
So:
gem uninstall bundler -v1.13

You're not the only one having the issue today. :)

https://github.com/fastlane/fastlane/issues/6065

**Comment by drosenstark** [comment]
That worked! I had to do

`sudo gem uninstall bundler -v1.13`

which uninstalled the whole thing, and then a fancier thing for El Cap

`sudo gem install -n /usr/local/bin bundler -v 1.12`

Now I'm up and running. Thanks!

**Comment by craigzour** [comment]
@PetrosIchor That worked for me as well ! Thank you !

**Comment by johndoran** [comment]
fwiw I had the same issue, I use rvm so had to do an additional
`rm -rf ~/.rvm/gems/ruby-2.0.0-p647/gems/bundler-1.13.1`

**Comment by microinsurance** [comment]
Hi i am getting the below mention error, please suggest...

[root@mia crop-insurance-portal]# rails db:create

rails aborted!
LoadError: incompatible library version - /usr/local/rvm/gems/ruby-2.2.4/gems/pg-0.19.0/lib/pg_ext.so
/usr/local/rvm/gems/ruby-2.2.4/gems/pg-0.19.0/lib/pg.rb:4:in `require'
/usr/local/rvm/gems/ruby-2.2.4/gems/pg-0.19.0/lib/pg.rb:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `require'
/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.13.1/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `each'
/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.13.1/lib/bundler/runtime.rb:86:in `block in require'
/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `each'
/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.13.1/lib/bundler/runtime.rb:75:in `require'
/usr/local/rvm/gems/ruby-2.2.4/gems/bundler-1.13.1/lib/bundler.rb:106:in `require'
/root/crop-insurance-portal/config/application.rb:7:in `<top (required)>'
/root/crop-insurance-portal/Rakefile:4:in `require'
/root/crop-insurance-portal/Rakefile:4:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:12:in `block in run_rake_task'
/usr/local/rvm/gems/ruby-2.2.4/gems/railties-5.0.0.1/lib/rails/commands/rake_proxy.rb:10:in `run_rake_task'
/usr/local/rvm/gems/ruby-2.2.4/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/usr/local/rvm/gems/ruby-2.2.4/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
/root/crop-insurance-portal/bin/rails:9:in `require'
/root/crop-insurance-portal/bin/rails:9:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
/usr/local/rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.2.4/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
/usr/local/rvm/gems/ruby-2.2.4/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
/root/crop-insurance-portal/bin/spring:13:in `require'
/root/crop-insurance-portal/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
(See full trace by running task with --trace)

**Comment by WaKeMaTTa** [comment]
**Solution** https://github.com/fastlane/fastlane/issues/6203#issuecomment-251627196
