### ISSUE TITLE
`pilot` upload waits forever for processing of an *older* build if that is stuck in processing

### ISSUE THREAD

**Issue by dusek** [fastlane/fastlane#6069]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When a TestFlight build is "processing", and a new build is uploaded with `pilot` without turning off waiting for processing (the default), then `pilot` will wait for the _old_ build to finish processing even after the actual (new) build it just uploaded has already finished processing.

This is quite a nuisance when the old build is stuck in processing for a long time, e.g. happened to me 2 days ago when uploading with bad internet connectivity resulted in a "successful" upload which however was somehow damaged. The build, with build number 66, displayed as uploaded in iTunes Connect, but was "processing" all the time without option to click its details (and without app icon displayed). It took more than 24 hours for this damaged build to get removed from iTunes Connect. When uploading a subsequent, new build, with build number 67, `pilot` displayed _"Waiting for iTunes Connect to finish processing the new build (1.0.0 - 66)"_ (i.e. the old build, not the one that was uploaded by that invocation of fastlane).

Please note that there is no option to remove such a stalled old build from iTunes Connect on one's own. I contacted iTunes Support with request to remove the build, but even they are unable to remove the build as they responded:

> The system will eventually cleanup builds stuck in processing states, but **we are unable to remove them manually** at this time.
> 
> If you are the developer of your integration system, you may consider modifying the system to account for situations like this. Otherwise you might want to report the issue to the developer of this integration system so they are aware of the issue.

I suggest fastlane accounts for this by checking for processing status specifically of the build it uploaded, not [checking in general whether any build is processing](https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L127-L128).
##### Complete output when running fastlane, including the stack trace and command used

No longer have it, the stalled build has since then been removed so cannot reproduce it.
### Configuration Files

using `pilot` with `skip_waiting_for_build_processing` left unspecified, defaulting to `false`:

```
...
pilot distribute_external: false, changelog: changelog
...
```
### Environment

fastlane version (run `fastlane -v`): **`fastlane 1.102.0`**

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **yes**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **rbenv (ruby 2.0.0p648)**
### Note

A fix for this will obviously be hard to test 😄. Reproducing a successful upload of a damaged build is probably hard. However it is possible to at least test that normal uploads continue working.

**Comment by TKBurner** [comment]
@dusek Thanks for reaching out about this. I'm going to circulate this with the community to see if anyone is interested in investigating. Thanks!

**Comment by szotyi** [comment]
This would be a nice "fix" for me too. One of my builds are stuck in "Processing" for almost a month. Got the same response from Apple, that there is no way of manually removing it, just have to wait for some kind of automatic removal.
The suggestion, that checking the status for only the currently uploaded build would be the right solution in my opinion too.

**Comment by negebauer** [comment]
This still isn't fixed
Should be easy to fix

Passing from this
```ruby
def wait_for_processing_build(options, platform)
      # the upload date of the new buid
      # we use it to identify the build
      start = Time.now
      wait_processing_interval = config[:wait_processing_interval].to_i
      latest_build = nil
      UI.message("Waiting for iTunes Connect to process the new build")
      must_update_build_info = config[:update_build_info_on_upload]
      loop do
        sleep(wait_processing_interval)

        # before we look for processing builds, we need to ensure that there
        #  is a build train for this application; new applications don't
        #  build trains right away, and if we don't do this check, we will
        #  get break out of this loop and then generate an error later when we
        #  have a nil build
        if app.build_trains(platform: platform).count == 0
          UI.message("New application; waiting for build train to appear on iTunes Connect")
        else
          builds = app.all_processing_builds(platform: platform)
          break if builds.count == 0
          latest_build = builds.last

          if latest_build.valid and must_update_build_info
            # Set the changelog and/or description if necessary
            if should_update_build_information(options)
              latest_build.update_build_information!(whats_new: options[:changelog], description: options[:beta_app_description], feedback_email: options[:beta_app_feedback_email])
              UI.success "Successfully set the changelog and/or description for build"
            end
            must_update_build_info = false
          end

          UI.message("Waiting for iTunes Connect to finish processing the new build (#{latest_build.train_version} - #{latest_build.build_version})")
        end
      end
```

To this

```ruby
def wait_for_processing_build(options, platform)
      # the upload date of the new buid
      # we use it to identify the build
      start = Time.now
      wait_processing_interval = config[:wait_processing_interval].to_i
      latest_build = nil
      UI.message("Waiting for iTunes Connect to process the new build")
      must_update_build_info = config[:update_build_info_on_upload]
      found_build = false
      loop do
        sleep(wait_processing_interval)

        # before we look for processing builds, we need to ensure that there
        #  is a build train for this application; new applications don't
        #  build trains right away, and if we don't do this check, we will
        #  get break out of this loop and then generate an error later when we
        #  have a nil build
        if app.build_trains(platform: platform).count == 0
          UI.message("New application; waiting for build train to appear on iTunes Connect")
        elsif !found_build
          builds = app.all_processing_builds(platform: platform)
          latest_build = builds.last
          found_build = true
        else
          break if ! latest_build in builds

          if latest_build.valid and must_update_build_info
            # Set the changelog and/or description if necessary
            if should_update_build_information(options)
              latest_build.update_build_information!(whats_new: options[:changelog], description: options[:beta_app_description], feedback_email: options[:beta_app_feedback_email])
              UI.success "Successfully set the changelog and/or description for build"
            end
            must_update_build_info = false
          end

          UI.message("Waiting for iTunes Connect to finish processing the new build (#{latest_build.train_version} - #{latest_build.build_version})")
        end
      end
```

Is a quick fix
