### ISSUE TITLE
RFC: Introduce `VERSION_BUMP_PATHS` to generalize `commit_version_bump`

### ISSUE THREAD

**Issue by dusek** [fastlane/fastlane#6071]
🔑
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description - TL;DR version

Allow actions to specify files to include in the `commit_version_bump` through a new lane context variable, e.g. `VERSION_BUMP_PATHS`.
### Issue Description

Currently, `commit_version_bump` includes a [hard-coded logic](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/commit_version_bump.rb#L11-L69) to find files which need to be committed in a version bump. The hardcoded logic includes the `.xcodeproj` file and targets' `.plist` files, if I understand correctly, i.e. the same files bumped by `increment_build_number` and `increment_version_number` (though the latter does not bump the `.xcodeproj` file).

This makes it hard for other tools (e.g. fastlane plugins or future built-in actions) to extend this file list with other files they are changing to bump the version. E.g. the [`changelog` plugin](https://github.com/pajapro/fastlane-plugin-changelog) includes a [🔖 `stamp_changelog` action](https://github.com/pajapro/fastlane-plugin-changelog#--stamp_changelog) which just updates the "Unreleased" section in `CHANGELOG` to include the current version number and creates a new "Unreleased" section for future releases (see this e.g. [in this diff](https://github.com/pajapro/fastlane-plugin-changelog/commit/b2513c355d57f4395ac442c39d2030621179db4d?diff=split)). If one wants then to include the "stamped" `CHANGELOG.md` file in the version bump commit, one has to resort to hacks like adding `git_add(path: 'CHANGELOG.md')` before `commit_version_bump(force: true)`, and using the `force: true` with `commit_version_bump`.
### Proposed Solution

A solution would be to generalize how the list of files `commit_version_bump` commits is generated, by introducing e.g. a `VERSION_BUMP_PATHS` lane context variable. Then actions changing files to bump version, like `stamp_changelog`, and in the end perpahs even the built-in `increment_build_number` and `increment_version_number` themselves, would be responsible to know which files they are updating and to add them to the `VERSION_BUMP_PATHS` array. `commit_version_bump` would then, instead of having a hard-coded logic, use paths in `VERSION_BUMP_PATHS` array as the ones it expects to commit. The effect on the user would be that they could use `stamp_changelog` followed by `commit_version_bump` without any hiccup.
#### Technical breakdown
- define `VERSION_BUMP_PATHS` lane context variable (e.g. in `commit_version_bump` which consumes it)
- make `increment_build_number` and `increment_version_number` add files they are changing to `VERSION_BUMP_PATHS`, removing the relevant code detecting the list of such files from `commit_version_bump`
  - as the code specifying the files will be used by both actions, perhaps add it to some common helper file
  - there is no way to reliably get list of files `agvtool` has updated; only way would be parsing its stdout, but that is error-prone, so probably stick to the current hardcoded list approach
- make `commit_version_bump` use the `VERSION_BUMP_PATHS`
  - think about compatibility w.r.t. users who bump files themselves without fastlane `increment_*` actions - see “Possible issues” below for more discussion
- after (if) this is merged, file bugs with authors of any other version bumping actions where the result should be included in `commit_version_bump` to use `VERSION_BUMP_PATHS`
#### Possible issues/questions
- I think the lane context variable approach is the only possible given that `commit_version_bump` should work also with changes from external plugins (if that was not the requirement, then `commit_version_bump` could continue hardcoding files, extending them when needed).
- strictly relying on `VERSION_BUMP_PATHS` in `commit_version_bump` would destroy current behavior in case one already increments build and version numbers in `.xcodeproj` and targets' `.plist` files manually without use of fastlane actions `increment_build_number` and `increment_version_number`. This could be avoided by the `commit_version_bump` adding, for compatibility (legacy) reasons, the same files to `VERSION_BUMP_PATHS` by default (i.e. the `.xcodeproj` file and targets' `.plist` files), and then maybe phase out this interim compatibility behavior later. Or maybe on the other hand simply add a warning if `commit_version_bump` finds unexpected changes that bumping `.plist` and `.xcodeproj` files must be done through `increment_*` actions; or maybe here give people a flag in `commit_version_bump`, by default false, which specifies whether to use the strict new behavior, and allow people to turn it off?
- Fastlane always defines lane context variable in the variable's value producer, as opposed to in its value consumer. However in case of `VERSION_BUMP_PATHS`, where producer-consumer relationship is many-to-one, defining it in the single consumer makes more sense to me. However another similar example, the `clean_build_artifacts` action, i.e. an action which consumes output from multiple actions, currently [hardcodes the list of files it removes](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/clean_build_artifacts.rb#L5-L13) too - it uses lane context variables defined by many producing actions, effectively hardcoding which producing actions are eligible to have their build artifacts removed during the `clean_build_artifacts` action. Perhaps that precedent is not worth following, but I would appreciate some design insight here.
- is it possible to reliably specify a default value for a context lane variable so that it is set before any action tries to access it/modify it? Obviously here I would like to set the `VERSION_BUMP_PATHS` variable to an empty array so that any action accessing it could save itself from having to account for a situation where `VERSION_BUMP_PATHS` has not yet been set.
### See also
- [pajapro/fastlane-plugin-changelog#8](https://github.com/pajapro/fastlane-plugin-changelog/issues/8): Some initial discussion about this in fasstlane-plugin-changelog
- #5758: Full support for incrementing version number in Settings.bundle
### Conclusion

As I would like to give implementing this a shot, I would greatly appreciate some comments from the fastlane team w.r.t. this proposal for new and refined functionality. I also invite @pajapro, author of the [`changelog` plugin](https://github.com/pajapro/fastlane-plugin-changelog), to share his opinion or remarks if he wants to. Thanks for your time if you have read it up to here 😊.

**Comment by TKBurner** [comment]
@dusek Thanks for reaching out about this! I like the idea and I want to get some feedback from the community before we give you the greenlight to make this change. Thanks!

**Comment by LeoBakerHytch** [comment]
@dusek @TKBurner I would definitely appreciate this, both for using with `stamp_changelog`, and for a custom Android version bump action I have.
