### ISSUE TITLE
[pem] Remove/revoke old push certificate if 'force' option selected

### ISSUE THREAD

**Issue by joseluissb** [fastlane/fastlane#6075]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Allow pem to revoke old certificates before generating new ones. To avoid unnecesary/accidental certificate revocations, make this default only when 'force' option is selected.

PR #4814
Similar to #4824 and #1754

**Comment by bre7** [comment]
(#4824) Plugins might be the way to go. I'm not sure how to extract the function to a plugin. The code is quite simple since everything needed is already in PEM.

From pem/lib/pem/manager.rb:
```ruby
def revoke_old_certificates
    UI.important "Revoking existing Push Certificates."
    
    certificate.all.select { |crt| crt.name == PEM.config[:app_identifier] }.each { |crt| revoke(crt) }
end
```

**Comment by joseluissb** [comment]
The reason why I brought out the issue is to avoid the "You already have 2 active push profiles for this application/environment. You'll need to revoke an old certificate to make room for a new one" error.

In this case if you no longer have access to the original private key, then you need to manually delete one of the certificates. One approach could be deleting the oldest or both certificates when receiving this error and the 'force' option is set to 'true'.

I also agree that including this functionality into a plugin would suffice, though I'm not sure if this is possible.

**Comment by TKBurner** [comment]
@joseluissb Thanks for following up on this. I'm going to mark this as a feature request to see if there is interest in it being integrated into fastlane core. Otherwise I'd be really interested to see a plugin implementation. Thanks!

**Comment by doapp-ryanp** [comment]
@TKBurner curious - why plugin? This seems like core function, everyone runs into this eventually.

**Comment by TKBurner** [comment]
@doapp-ryanp Thanks! We aren't accepting new actions directly anymore. I could see this being included in PEM, but the fastest way to get it in the worlds hands is through our plugin system. Thanks and always feel free to reach out 👍
