### ISSUE TITLE
Gym include_bitcode defaults to false, xcodebuild defaults to true

### ISSUE THREAD

**Issue by maschall** [fastlane/fastlane#6079]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

If export_options is not defined, we default include_bitcode to false (https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/package_command_generator_xcode7.rb#L146)

However if you look at `xcodebuild --help` it specifies that:

```
uploadBitcode : Bool

    For App Store exports, should the package include bitcode? Defaults to YES.

uploadSymbols : Bool

    For App Store exports, should the package include symbols? Defaults to YES.
```

I think that we should be consistent with what should happen if you just built via xcodebuild -exportArchive command.

**Comment by TKBurner** [comment]
Hi @maschall! Interesting, I believe this change will come in the next few months. We chose the default based on common usage.

Thanks!
