### ISSUE TITLE
[scan] DEVELOPER_DIR does not work with FASTLANE_EXPLICIT_OPEN_SIMULATOR

### ISSUE THREAD

**Issue by mindows** [fastlane/fastlane#6088]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Setting `FASTLANE_EXPLICIT_OPEN_SIMULATOR=1` to pre-open the simulator doesn't appear to use the right Xcode if you try to override the default Xcode selection by specifying `DEVELOPER_DIR`

I may be reading this incorrectly, but getting the simulator list uses 
`xcrun simctl list devices` which does allow specifying a custom Xcode installation. 
For example, this is entirely possible:

```
DEVELOPER_DIR=/Applications/Xcode-8.app/Contents/Developer xcrun simctl list devices
<list of available devices under Xcode 8>

DEVELOPER_DIR=/Applications/Xcode-7.3.1.app/Contents/Developer xcrun simctl list devices
<list of available devices under Xcode 7.3.1>
```

However, `FASTLANE_EXPLICIT_OPEN_SIMULATOR` determines the location of the Xcode installation by running `xcode-select -s`, discarding the Xcode installation location specified with `DEVELOPER_DIR`
### Environment

fastlane version (run `fastlane -v`):
1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by TKBurner** [comment]
@mindows Great to hear from you! We'd love to see a PR to change this behavior. Are you interested in contributing? I've marked this to see if the community can help too!
