### ISSUE TITLE
[deliver] issue with bundler 1.13.0

### ISSUE THREAD

**Issue by andyh200** [fastlane/fastlane#6090]
When attempting to execute deliver (1.13.3) we are seeing the following error relating to bundler (1.13.0)

`/Users/andy/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source': uninitialized constant Gem::Source (NameError)
Did you mean?  Gem::Source
        from /Users/andy/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:65:in `extension_dir'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:46:in `gem_build_complete_path'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2174:in `missing_extensions?'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:71:in `contains_requirable_file?'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1067:in `block in find_in_unresolved'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1067:in `each'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1067:in `find_all'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1067:in `find_in_unresolved'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:73:in `require'
        from /Users/andy/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:23:in `source'
        from /Users/andy/.rvm/gems/ruby-2.3.1/gems/bundler-1.13.0/lib/bundler/rubygems_ext.rb:35:in `full_gem_path'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:142:in `block in full_require_paths'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:141:in `map'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/basic_specification.rb:141:in `full_require_paths'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1542:in `add_self_to_load_path'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1411:in `activate'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `block in activate_bin_path'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `synchronize'
        from /Users/andy/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:299:in `activate_bin_path'
        from /Users/andy/.rvm/gems/ruby-2.3.1/bin/deliver:22:in `<main>'
        from /Users/andy/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/andy/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'`

Reverting to bundler-1.13.0.rc.1 resolves the problem.

Is anybody else experiencing this issue?

**Comment by TKBurner** [comment]
@andyh200 Hi! We are aware of this issue and are working on a fix. It is being tracked elsewhere, but I cannot find it because 'bundler' is in every issue. Thanks!

**Comment by andyh200** [comment]
This looks to be resolved now with deliver 1.13.3 and bundler 1.13.1

**Comment by TKBurner** [comment]
@andyh200 Really appreciate you updating us and so glad you got up and running. Hope that you have a great weekend coming up. 👍 💯
