### ISSUE TITLE
Deliver does not download iMessage app screenshots

### ISSUE THREAD

**Issue by garnett** [fastlane/fastlane#6091]
### New Issue Checklist
- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

We have iMessage app bundled with out main app. `deliver download_screenshots` downloads only app screenshots.
### Environment

```
deliver 1.13.3
fastlane 1.102.0
```

**Comment by muhammet** [comment]
How you guys uploading screenshots for iMessage app ? We are named `messages-iPad-*_framed.png` 

isnt it right ?

**Comment by garnett** [comment]
@muhammet wont' speak for everybody, but currently we do it manually.

**Comment by TKBurner** [comment]
@muhammet Are you able to get your screenshots for your iMessage app via deliver with this naming convention? We'd love to see a PR to improve this functionality.

**Comment by JustinJiaDev** [comment]
@TKBurner 

The naming convention won't work. According to https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/upload_screenshots.rb

```ruby
is_watch = file_path.downcase.include?("watch")
# probably need to add this
# is_message = file_path.downcase.include?("message")
```

**Comment by JustinJiaDev** [comment]
@TKBurner It seems like Apple Watch screenshots support is based on image resolution. But iMessage screenshots have the same resolution.

**Comment by TKBurner** [comment]
@JustinJiaDev Followed up on our other issue. 👍

**Comment by JustinJiaDev** [comment]
@milch This can be closed as well.

**Comment by milch** [comment]
@JustinJiaDev Great, thanks for letting me know!
