### ISSUE TITLE
Bundler fails to install fastlane

### ISSUE THREAD

**Issue by Mehdzor** [fastlane/fastlane#6094]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When running bundler with contents:

```
source 'http://rubygems.org'
gem 'fastlane'
```

It fails with an error: 

```
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
An error occurred while installing gym (1.9.0), and Bundler cannot continue.
Make sure that `gem install gym -v '1.9.0'` succeeds before bundling.
```

But an installation through simple `gem install fastlane` goes fine.  
The issue appears only when a bundle config contains `BUNDLE_BIN: ".somedirectory"`
### Environment

fastlane version (run `fastlane -v`): 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

Ruby version: 2.2.5

Bundler version: 1.13.0

OS: OSX 10.11

**Comment by KrauseFx** [comment]
Hey, we've been working on a new way to install and use fastlane, all you have to do is to download `fastlane.zip` and double click the `install` file. This will install fastlane with all its Ruby and OpenSSL dependencies, and should all work out of the box.
We just finished building this, and would love your early feedback on this beta. Please let us know how it works for you and if you run into any problems :+1: 
Download the latest version [here](https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip)
