### ISSUE TITLE
Gym always cleans project, no way to set timeout to not be 10s

### ISSUE THREAD

**Issue by programmin1** [fastlane/fastlane#6099]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When running gym with the "--clean false" arguments, it still cleans project.
If it takes longer than 10s (on very slow hard drive or while you are unzipping large files, etc.) it will never complete.

Unfortunately there doesn't seem to be a way to set that 10s timeout, FASTLANE_XCODE_LIST_TIMEOUT environment variable doesn't do it.
### Environment

fastlane version (run `fastlane -v`):1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by TKBurner** [comment]
Hi @programmin1 Great to hear from you and sorry that you are running into this. Can you run `gym --clean false` and provide the full input and output? Thanks!

**Comment by programmin1** [comment]
Ok. Sometimes clean works, sometimes it doesn't (you can nearly guarantee it will timeout if you are unzipping a 1gb file on the same hard disk while trying this):

It would be great to have a timeout or a --clean false that disables the clean step..

```
$ gym --clean false
[15:17:57]: $ xcodebuild -list -workspace ./somefile.xcworkspace
[15:18:07]: Command timed out after 10 seconds on try 1 of 4, trying again...
Select Scheme: 
1. somescheme
2. Pods-anotherscheme
3. Pods-andanotherscheme
?  1
[15:18:20]: $ xcodebuild clean -showBuildSettings -workspace ./somefile.xcworkspace -scheme somescheme

+----------------------+------------------------------------+
|                   Summary for gym 1.9.0                   |
+----------------------+------------------------------------+
```
 ...and then it either completes successfully, or keeps timing out because build clean doesn't happen in ten seconds!

**Comment by programmin1** [comment]
So is there some environment variable, or gym command that will skip that `xcodebuild clean` step?

I also tried skipping clean by adding a Gymfile with:

```
scheme theschemename
clean false
```

and run gym, and it still runs that `xcodebuild clean` command.

Or, if it was a mistake that the clean option was added, it _has to_ clean it, please add a timeout so it doesn't break on slower computers.

**Comment by TKBurner** [comment]
Hi @programmin1 Is it always timing out on the 

`xcodebuild -list -workspace ./somefile.xcworkspace`

step? I just want to see if it is reverting after a timeout. Thanks!

**Comment by programmin1** [comment]
No, clean has been timing out, there is already an option that works, to change the timeout so -list does not time out (#87)

There is apparently no option to tell it not to clean - or even change the timeout for that process.

**Comment by Luke-SF** [comment]
I'm not seeing the timeout option, or the cleanup command in the files in the Ruby gems/gym directory source files. Anyone know where I might track down this setting to fix it manually?

**Comment by TKBurner** [comment]
@Luke-SF @programmin1 I'm going to mark this as a feature request. If you are interested in submitting a PR please let me know so we can work with you. Thanks!

**Comment by Luke-SF** [comment]
Why is it a "feature request", not a bug, that the documented --clean false option doesn't actually do anything?

Try it, run `gym --clean false`,  `gym --clean true`,  `gym --clean FALSE`, every way it shows the xcodebuild clean step. Thank you for looking into this.

**Comment by jeanregisser** [comment]
@Luke-SF I hit the same bug here, `--clean false` always cleans. This should be labelled as a bug.

**Comment by TKBurner** [comment]
@Luke-SF Changed this labeling and also sent out to the core team for investigation. Really sorry this is causing headaches for you. Hope you have a great day!

**Comment by Luke-SF** [comment]
@TKBurner Great, thanks for the good work on this tool :)

**Comment by KrauseFx** [comment]
Please share the complete command you ran, the content of the `Gymfile`, and the complete output, including the summary table and the commands that are generated. his parameter should work as expected, only for fetching the build settings we call `clean` every time

**Comment by programmin1** [comment]
I'm not only getting this timeout 4 times and failing fairly often, I'm also getting "Seems like launching fastlane takes a while - please run [sudo] gem cleanup" since last update.

I have run sudo gem cleanup and it still takes a long time, times out 4 times.

**_If_** there is a requirement to have an SSD, or this program just isn't tested on older spinning hard disk drives, or fairly full drives, I highly recommend mentioning it in a system requirements page. Thanks!

**Comment by KrauseFx** [comment]
@programmin1 have you seen our new [download.fastlane.tools](https://download.fastlane.tools)? It should be faster than installing it using system Ruby 👍

**Comment by programmin1** [comment]
@KrauseFx Thanks, I'm not sure I understand, is that a binary format of the fastlane ruby library?

**Comment by programmin1** [comment]
This is becoming a serious problem, and the environment variable it says should help, doesn't change the behavior at all, either from Java process runner, or from shell:

```
$ FASTLANE_XCODE_LIST_TIMEOUT=400
$ echo $FASTLANE_XCODE_LIST_TIMEOUT;
400
$ fastlane gym -j app-store --clean false --scheme schemename
[14:26:18]: Seems like launching fastlane takes a while - please run
[14:26:18]: 
[14:26:18]: $ [sudo] gem cleanup
[14:26:18]: 
[14:26:18]: to uninstall outdated gems and make fastlane launch faster
[14:26:18]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[14:26:18]: To get started with a Gemfile, run
[14:26:18]: 
[14:26:18]: $ bundle init
[14:26:18]: $ echo 'gem "fastlane"' >> Gemfile
[14:26:18]: $ bundle install
[14:26:18]: 
[14:26:18]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[14:26:18]: For more information, check out https://guides.cocoapods.org/using/a-gemfile.html
/Library/Ruby/Gems/2.0.0/gems/gym-2.0.0/lib/gym/version.rb:3: warning: already initialized constant Gym::DESCRIPTION
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.4.0/gym/lib/gym.rb:46: warning: previous definition of DESCRIPTION was here
[14:26:24]: $ xcodebuild -list -workspace ./the.xcworkspace
[14:26:34]: Command timed out after 10 seconds on try 1 of 4, trying again...
[14:26:44]: Command timed out after 10 seconds on try 2 of 4, trying again...
[14:26:54]: Command timed out after 10 seconds on try 3 of 4, trying again...
[14:27:04]: Command timed out after 10 seconds on try 4 of 4

[!] xcodebuild -list timed-out after 30 seconds. You might need to recreate the user schemes. You can override the timeout value with the environment variable FASTLANE_XCODE_LIST_TIMEOUT
```

Perhaps the minimum requirements need to say, a fast SSD, or a hard disk drive that is <90% full.

**Comment by nafu** [comment]
@programmin1 

Please try this.

```
$ export FASTLANE_XCODE_LIST_TIMEOUT=400
$ fastlane gym -j app-store --clean false --scheme schemename
```

**Comment by programmin1** [comment]
@nafu Still shows the Command timed out after 10 seconds on try 1 of 4, trying again...

**Comment by programmin1** [comment]
https://github.com/fastlane/fastlane/issues/4205 may be the same root issue, that you can't extend the 10s wait.

**Comment by Luke-SF** [comment]
This is still happening, please reopen... maybe it should wait 10s, then 100s?

**Comment by kciarnie** [comment]
please fix this, --clean false should not add clean to the xcodebuild statement

**Comment by Luke-SF** [comment]
This is even worse now, it is not even possible to compile now since it says
```
[16:49:10]: Command timed out after 10 seconds on try 1 of 4, trying again...
[16:49:20]: Command timed out after 10 seconds on try 2 of 4, trying again...
[16:49:30]: Command timed out after 10 seconds on try 3 of 4, trying again...
[16:49:40]: Command timed out after 10 seconds on try 4 of 4
```

_every time._ not just once in awhile.

**Comment by YoungApple** [comment]
+1 to reopen this.

Everytime, i will get four "timed out" error...

**Comment by ohayon** [comment]
Hey @Luke-SF  and @kciarnie - could you share the entire output from your command line and how you are calling fastlane (whether calling gym directly or using a Fastfile)... also, it would help to see the output of `fastlane env` too. Thanks! 🐙

**Comment by taglia3** [comment]
Hi, 
same issue here.

After updating fastlane I've the same error.

`$ xcodebuild -list -workspace ./MyProjectName.xcworkspace
$ xcodebuild -showBuildSettings -workspace ./MyProjectName.xcworkspace -scheme Sch_System
Command timed out after 10 seconds on try 1 of 4, trying again...
Command timed out after 10 seconds on try 2 of 4, trying again...
Command timed out after 10 seconds on try 3 of 4, trying again...
Command timed out after 10 seconds on try 4 of 4
Successfully loaded '/Users/company/Documents/Development/MyProject/fastlane/Gymfile' 📄
No values defined in './fastlane/Gymfile'
$ xcodebuild -showBuildSettings -workspace ./MyProjectName.xcworkspace -scheme Sch_System`

**Comment by ohayon** [comment]
Hey @taglia3 curious to know what version of Xcode you are running here? We have seen this as a big problem with Xcode 9 beta 5. 🕐  🐙

**Comment by dacohn** [comment]
+1

This is blocking me as well. The `xcodebuild -showBuildSettings ...` command takes about 12 seconds to run when I manually execute it from the command line, so it times out in fastlane. Setting FASTLANE_XCODE_LIST_TIMEOUT has no effect.

**Comment by ohayon** [comment]
Hey @dacohn - Which version of Xcode are you using?

**Comment by dacohn** [comment]
@ohayon 8.3.2

**Comment by taglia3** [comment]
@ohayon I'm using Xcode 8.3.3

I solved the issue by placing this line before invoke fast lane:

`export FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT=100`
