### ISSUE TITLE
Hockey action errantly fails when build is actually uploaded

### ISSUE THREAD

**Issue by brianmichel** [fastlane/fastlane#6101]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
[13:29:54]: Error when trying to upload ipa to HockeyApp: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: dVisPBuxHoLhoNlykv08bGfZt5NBcfDZzZCqieyZFupYJIeNBOKRXw==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "1.102.0"

before_all do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

  puts 'Deleting old build folder'
  `rm -rf ../build`
end

lane :beta do
  gym({
    workspace: "Orangina.xcworkspace",
    scheme: "Orangina",
    configuration: "beta",
    output_directory: "build",
    clean: true,
    include_symbols: true,
    include_bitcode: false,
    toolchain: "com.apple.dt.toolchain.Swift_2_3",
    export_method: "enterprise",
  })

  hockey({
    api_token: "api_token",
    public_identifier: "app_identifer",
    tags: "devs"
  })
end
```
### Environment

fastlane version (run `fastlane -v`): `fastlane 1.102.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? `YES`

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? `YES`

**Comment by brianmichel** [comment]
I attempted to make an issue on Fastlane's fork of Shenzhen but was unable to do so, so I'm making an issue here.

We also talked with HockeyApp support about this specific issue and here was their response...

```
We have to endpoints for the upload API:

rink.hockeyapp.net - this will go to a load balancer which will then go directly to any of our app servers processing the request
upload.hockeyapp.net - this is behind Amazon CloudFront which is a CDN which are normally use for content delivery. But Amazon also allows it to use it for POST requests. The request will go to one of Amazons servers, taking the file and then forward it to our Load Balancer. Amazon will use it's own optimized network for that so in theory the upload should go much faster the farer away you are from the Amazon US-East datacenter.
Looking at your error message there is something going wrong when Amazon Cloudfront speaks with Amazon ELB (LoadBalancer) which is something we have to ask Amazon trough a support request. And my gut feeling is that they will come back with "can happen" but we will still try.

But since it isn't really necessary if you are in the US the best way to fix the issue would be to just switch the domain to rink.hockeyapp.net.

The library is build by your team or another team in your company?

I hope this helps understanding the issue.

```

It looks like Shenzhen is currently using `upload.hockeyapp.net` according to https://github.com/fastlane/shenzhen/blob/master/lib/shenzhen/plugins/hockeyapp.rb#L9 would it be possible to have an option to pass in something else?

**Comment by brianmichel** [comment]
I think some gentle refactoring of that gem would allow people additional flexibility for problems like this, here's a sample diff, https://github.com/brianmichel/shenzhen/commit/f35813ebdbe474674b736856a1af2e70927e7680

**Comment by TKBurner** [comment]
Hi @brianmichel Thanks for reaching out. If you are interested in adding this as an option on the Hockey action that'd be good. Let me know!

**Comment by brianmichel** [comment]
@TKBurner I'm happy to take this on, I assume I'll have to patch both shenzhen (at the previous comment mentions) and provide an update to the Hockey action within Fastlane to offer this as an option, correct?

Are there any other details I'm missing?

**Comment by TKBurner** [comment]
@brianmichel Sounds like a plan! Sorry for taking a little while to get back to you. We are really happy to have you contribute. 👍

**Comment by jverdi** [comment]
+1 seeing these failures fairly consistently as of late. Any luck throwing a PR together @brianmichel ?

**Comment by otaran** [comment]
You can now instruct `hockey` to use `https://rink.hockeyapp.net` by specifying `bypass_cdn: true` parameter. This does not solve the issue reported for Amazon CDN but lets you temporarily switch to the reliable (albeit slow) Hockey load balancer.
