### ISSUE TITLE
Relogin if token has expired

### ISSUE THREAD

**Issue by edsanville** [fastlane/fastlane#6103]
Hello,

I have dozens of screenshots in over a dozen languages, and deliver's iTunes Connect token times out after exactly 1 hour, but my upload takes longer than an hour because of all the screenshots.

I think deliver should re-login if its token expires during the upload process.

Also, syncing the screenshots, rather than uploading all of them every time would help immensely in my use case.

Thank you very much for a great product.

**Comment by TKBurner** [comment]
@edsanville Can you let me know what error message you get? I think this might explain some other behavior I've seen recently. Thanks!

**Comment by edsanville** [comment]
@TKBurner I don't have the exact error, because it only occurred once. After that, I broke up my screenshot uploads so it wouldn't time out again. The error message was pretty clear, though: the iTunes Connect token had timed out. And, the timestamp was exactly 1 hour after deliver had logged in.

**Comment by TKBurner** [comment]
@edsanville Thanks so much. If you run into this again can you update this thread? We are going to continue to track this here and and on our other threads on deliver.  If you are interested in submitting a PR around re-authenticating that'd be 💯  Hope you have a great week!
