### ISSUE TITLE
XCTest Hangs when Used with Scan on Bitrise with Xcode 8

### ISSUE THREAD

**Issue by Ben-G** [fastlane/fastlane#6111]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running scan via fastlane on Bitrise with Xcode 8, the unit tests will always hang and fail the build. This issue does not occur on Bitrise when calling `xcodebuild` directly. The issue does also not occur when running fastlane on a local machine - I could only reproduce the issue in this combination. I'm wondering if others are seeing similar issues on other CI providers?

Fastlane fails with exit code 65 when attempting to run unit tests, without any additional information:

```
▸ Running script '[CP] Copy Pods Resources'
▸ Touching PlanGridUnitTests.xctest
▸ Signing /Users/vagrant/Library/Developer/Xcode/DerivedData/PlanGrid-fwcdtyfkquxsxabgkthlycyyhpvt/Build/Intermediates/CodeCoverage/Products/Debug-iphonesimulator/PlanGrid.app/PlugIns/PlanGridUnitTests.xctest
** TEST FAILED **
[14:59:19]: Exit status: 65
[14:59:20]: Variable Dump:
[14:59:20]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios dev", :SCAN_DERIVED_DATA_PATH=>"/Users/vagrant/Library/Developer/Xcode/DerivedData/PlanGrid-fwcdtyfkquxsxabgkthlycyyhpvt", :SCAN_GENERATED_PLIST_FILES=>[], :SCAN_GENERATED_PLIST_FILE=>nil}
[14:59:20]: Error building/testing the application - see the log above
```

The `xcactivitylog` from the test run is looks as following and provides more details:

```
14:50:25.982 xcodebuild[1706:14490] Returning /private/tmp/com.apple.launchd.O2dWsgK0Ma/com.apple.testmanagerd.unix-domain.socket for TESTMANAGERD_SIM_SOCK
14:50:25.982 xcodebuild[1706:14490] Sim iPad Air 2 has testmanagerd socket at /private/tmp/com.apple.launchd.O2dWsgK0Ma/com.apple.testmanagerd.unix-domain.socket
14:50:25.982 xcodebuild[1706:14490] Connected socket 32 to testmanagerd for Sim iPad Air 2
14:50:25.988 xcodebuild[1706:8431] Returning /private/tmp/com.apple.launchd.O2dWsgK0Ma/com.apple.testmanagerd.unix-domain.socket for TESTMANAGERD_SIM_SOCK
14:50:25.988 xcodebuild[1706:8431] Sim iPad Air 2 has testmanagerd socket at /private/tmp/com.apple.launchd.O2dWsgK0Ma/com.apple.testmanagerd.unix-domain.socket
14:50:25.988 xcodebuild[1706:8431] Connected socket 35 to testmanagerd for Sim iPad Air 2
14:50:26.016 xcodebuild[1706:8431] Creating the test bundle connection.
14:50:26.043 xcodebuild[1706:8431] Listening for proxy connection request from the test bundle (all platforms)
14:50:26.043 xcodebuild[1706:8431] Resuming the connection.
14:50:26.043 xcodebuild[1706:8431] Test connection requires daemon assistance.
14:50:26.859 xcodebuild[1706:8363] Starting test session with ID <__NSConcreteUUID 0x7fe44fc7d580> BBFEE52F-8CCB-42F7-B095-099301FE730A
14:50:26.859 xcodebuild[1706:8363] Checking test manager availability..., will wait up to 120s
14:52:26.863 xcodebuild[1706:8363] Unable to get debug console for logging target process thread state.
14:52:26.865 xcodebuild[1706:8363] Test operation failure: Canceling tests due to timeout in Checking test manager availability...
14:52:26.865 xcodebuild[1706:8363] _finishWithError:Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Canceling tests due to timeout in Checking test manager availability..." UserInfo={NSLocalizedDescription=Canceling tests due to timeout in Checking test manager availability...} didCancel: 1
```

The full log can be found [here](https://gist.github.com/Ben-G/70117e18e794f7398ba42661c48995af).

### Configuration Files

Relevant Fastfile lane:
```ruby
  desc "Runs all the tests & uploads code coverage data to codecov.io and updates translation keys on Phraseapp"
  lane :dev do
    # Upload latest localization keys to Phraseapp
    UpdateLocalization.upload_latest_localization

    scan(
      scheme: "PlanGrid_CI",
      devices: ["iPhone SE"],
      clean: false,
      code_coverage: true
    )

    sh "../scripts/upload_codecoverage.sh"
  end
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No, bitrise uses homebrew's ruby version. Currently 2.3.1.

**Comment by Ben-G** [comment]
Not related to code signing -  but good guess @fastlane-bot!

**Comment by TKBurner** [comment]
@Ben-G Hope you are doing well! Does this happen in Xcode 8 locally as well or just on Bitrise? Can you share your full input and output? Thanks!

**Comment by Ben-G** [comment]
@TKBurner Thanks for getting back on this. This only occurs on bitrise. Running on a local machine it works fine. However, I can run tests on bitrise when only using `xcodebuild` and not using fastlane. So this appears to be an issue that only occurs when both tools are combined :|

As for input/output: you can find the full log file of the build [here](https://gist.github.com/Ben-G/92f0c5cedbe23f08c8bd2b2f686d5988). I shared the Fastfile [here](https://gist.github.com/Ben-G/d8e1f415f913da8fa246a32f39ad5fb9).

**Comment by TKBurner** [comment]
Hi @Ben-G So sorry for the delay in getting back to you. Can you let me know what happens if you set 

`clean: true`

or `erase_simulators` prior to running your lane. Thanks and hope you have a great week!

**Comment by scottrhoyt** [comment]
Same thing for me on travis and Xcode 8. Can't find an `erase_simulators` action. Is that perhaps `reset_simulators` now?

**Comment by scottrhoyt** [comment]
FWIW `clean: true` and running `reset_simulators` did not work for me.

**Comment by TKBurner** [comment]
@scottrhoyt Can you share your full input and output so I can take a look? Thanks so much!

**Comment by carsten-wenderdel** [comment]
Hi everybody, I've had the same problem with the Xcode 8.0 stack on bitrise. (fastlane/scan on my computer and xcodebuild on bitrise also worked.)
Using the Xcode 8.1 stack on bitrise has solved the problem for me - now fastlane/scan works there as well!

**Comment by Ben-G** [comment]
@carsten-wenderdel Thanks a lot for letting me know about this. It appears the issue is indeed fixed with the Xcode 8.1 stack. 🎉 

Closing this issue.

**Comment by KrauseFx** [comment]
Great to hear this is resolved now, thanks for updating this issue 👍

**Comment by werner77** [comment]
See my solution here: http://stackoverflow.com/a/40790171/480467

The problem lies in the fact that the timeout counter in xcodebuild starts as soon as the command is executed, so the compile time counts towards the timeout (which is 120 seconds)
