### ISSUE TITLE
Support -configuration in Project class to get build_settings based on configuration

### ISSUE THREAD

**Issue by maschall** [fastlane/fastlane#6113]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

---------

To support development with Push Notifications in a App Store and Enterprise environments, we have setup multiple configurations with different PRODUCT_BUNDLE_IDENTIFIER.

I want to easily check the build_settings for the project to get the PRODUCT_BUNDLE_IDENTIFIER for current build to pass into sigh.

PR to come shortly.

**Comment by TKBurner** [comment]
@maschall Thanks for the contribution! We will work with you there.
