### ISSUE TITLE
fastlane:How to support a compilation, and then packaged a-hoc, appstore.

### ISSUE THREAD

**Issue by tzq582905** [fastlane/fastlane#6115]

**Comment by tzq582905** [comment]
Now I need to separate the 2 packages.

**Comment by TKBurner** [comment]
Hi @tzq582905! Hope you are doing well! Can you use the issue template? It seems like you'll want to use _gym_ and _deliver_. Let me know how it goes! Thanks!

**Comment by tzq582905** [comment]
@TKBurner now,i can packaged  a-hoc, appstore.but need compile two times use gym. xcode can once compile,then export a-hoc, appstore package. i want to know how can once compile and export a-hoc, appstore package use fastlane.

**Comment by TKBurner** [comment]
@tzq582905 You'll need to run gym twice to sign with the relevant profiles. Thanks!

**Comment by tzq582905** [comment]
@TKBurner It seems to be the only way.Thanks
