### ISSUE TITLE
Need fixed title height parameter for frameit

### ISSUE THREAD

**Issue by chezzdev** [fastlane/fastlane#6116]
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hello everyone. 
I've tried `frameit` for its direct purpose and everything went good (after an hour figuring out parameters and possibilities) except for one thing. I can't set the parameters to get devices frames laid out identically on all screenshots for specific device type. The height of the title is always different so device frame can end up slightly (or hugely) shifted vertically relatively to other screenshots. 

My configuration is simple:

```
{
  "default": {
    "title": {
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 70
  },
  "data": []
}
```

If someone can help me setting this I would greatly appreciate that.

But in the meantime I implemented this possibility myself. I decided that the problem can be resolved introducing fixed title height. With fixed title height device frame will always be placed in the same position for one device type.

So before making a pull request I would like to discuss these points:
- Is it possible to conveniently achieve this with the current tool?
- I noticed that the parameter `offset` can be described in `Framefile.json` and it can contain `offset`, `width`, and `titleHeight` entries. `titleHeight` looks like everything I need but it's currently used only in `mac_editor`. Also you can't specify only `titleHeight` entry in `offset` because without `offset` entry in `offset` entry (sorry, this is actually how they're called) the latter is considered invalid:

``` ruby
if @offset_information and (@offset_information['offset'] or @offset_information['offset'])
  return @offset_information
end
UI.user_error! "Could not find offset_information for '#{screenshot}'"
```

So the question is: can I use `titleHeight` entry to specify fixed title height or it's better to introduce new entry in `Framefile.json`? 
If existing one is ok, we  should consider merging offset specified in `Framefile.json` and offset from `Offsets.image_offset(screenshot)` because we don't want to lose `offset` and `width` calculated for current screenshot.
- I don't want to actually resize title to fit fixed title height. It can become too short or too long. Instead I propose adjusting title paddings so that top space above device will always be 

```
top_space_above_device = fixed_title_height + 2 * padding
```

Again, described solution is already implemented and tested. I just want to confirm these points before making a pull request.

Thanks for attention!

**Comment by TKBurner** [comment]
@chezzdev I think we'd be interested in taking a look. Right now the behavior of frameit is expected when using titles. Can you provide some screenshots of your results vs. what you see with the current tool? Thanks!

**Comment by chezzdev** [comment]
@TKBurner sure. Here's an overview of framed screenshots (current tool).
![screen shot 2016-09-28 at 19 18 51](https://cloud.githubusercontent.com/assets/5272337/18947687/beb9c1f2-863c-11e6-9845-df6549adf3af.png)
As you can see there's a huge difference in frame position when using different numbers of lines in title. But also there's a tiny but actually noticeable difference in frame position even with the same number of lines. This can be very annoying especially when the device screen is cropped or the home button is visible on some of resulting images.

This is the result of my solution:
![screen shot 2016-09-28 at 19 20 56](https://cloud.githubusercontent.com/assets/5272337/18947925/b581f022-863d-11e6-9255-c9ef29f26afc.png)
Perfectly aligned device frames.

And this is how my `Framefile.json` looks like right now:
```
{
  "default": {
    "title": {
      "color": "#545454"
    },
    "background": "./background.jpg",
    "padding": 70
  },
  "data": [
    {
      "filter": "iPhone5",
      "offset": {
        "titleHeight": 80 
      }
    },
    {
      "filter": "iPhone6",
      "offset": {
        "titleHeight": 90 
      }
    },
    {
      "filter": "iPhone6Plus",
      "offset": {
        "titleHeight": 100 
      }
    }
  ]
}
```
So yes, you have to specify concrete value for each device type to get comparable results (e.g. I wanted the frame to be cropped in the area between lower edge of the screen and the home button). But it is much easier than trying to adjust text to get comparable results on each image.

I'm still not sure that using existing entry of `Framefile.json` is the best decision so my initial questions are open.

**Comment by TKBurner** [comment]
@chezzdev Nice! Are you interested in submitting a PR to improve this behavior? Thanks!

**Comment by Anders123fr** [comment]
Yeah would be great if you could make a PR @chezzdev ! 
I really need this too :)

**Comment by ownmas** [comment]
These not resolve yet

**Comment by AndriyGo** [comment]
I would also love to see this feature
