### ISSUE TITLE
Specify provisioning profile in Xcode 8 with gym

### ISSUE THREAD

**Issue by chrisfsampaio** [fastlane/fastlane#6118]
With Xcode 8 and manual code signing, a new build parameter is used to specify a provisioning profile to sign with.
It's all covered in [the code signing guide](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Codesigning/XcodeProject.md#readme), but for the ones that are not yet using `match`, it would be useful to have a `gym` parameter reflecting the change in Xcode. And then our `Fastfile`s could have something like this: 

```
gym({
    workspace: "AwesomeProject.xcworkspace",
    scheme: "AwesomeScheme",
    configuration: "Release",
    provisioning_profile_specifier: "Foo AppStore"
  })
```

Right now, my solution involves the `xcargs` parameter, like this:
```
  gym({
    workspace: "AwesomeProject.xcworkspace",
    scheme: "AwesomeScheme",
    configuration: "Release",
    xcargs: "PROVISIONING_PROFILE_SPECIFIER='Foo AppStore'"
  })
```

But it wasn't easy to figure it out for me and I think that a proper `gym` parameter with `README` documentation could be more discoverable.

@KrauseFx What do you think?
I can a open PR with the implementation if y'all agree it makes sense adding this parameter.

**Comment by TKBurner** [comment]
@chrisfsampaio Thanks for reaching out. I want to leave this open for feedback before giving you the go ahead for a PR. The team will take a look here.

**Comment by RobertNNms** [comment]
+1

**Comment by raven** [comment]
+1

**Comment by bkrijgsman** [comment]
@chrisfsampaio Thank you so much, this was exactly what i needed.
No I can enjoy my friday afternoon drinks 👍

**Comment by KrauseFx** [comment]
Thanks 👍 How does this work if you have multiple targets?

**Comment by bkrijgsman** [comment]
We don't use fastlane, only the fastlane tools (deliver / match / gym) to deliver our apps. In gym we specify the parameters manually for each target.

**Comment by chrisfsampaio** [comment]
@KrauseFx with multiple targets, this would set the same provisioning profile for every target under the selected scheme. We can make that explicit in the parameter documentation.

In this particular case it works well because we only have one main target, which I would guess is the setup for most of the apps. Once it gets more complex, with multiple targets and different configurations (e.g. AppStore, Debug, Release Candidate), we should advice the use of `match` or the automatic system embedded in Xcode, since it wouldn't make sense to use the same provisioning profile for everything.

**Comment by Po-Chang** [comment]
@chrisfsampaio In my project, my share extension target and app's target using different provisioning profile, how can I use your solution?

**Comment by chrisfsampaio** [comment]
@marcuswu0814 The short answer is you can't 😕. Unfortunately `xcodebuild` doesn't provide an API to manipulate build settings per target.

If you want to "manually" manage code signing, you need to provide the correct provisioning profile names for each target in Xcode on the Build Settings tab.
You can also use [match](https://github.com/fastlane/fastlane/tree/master/match#readme) if you're working within a team. You can find a lot of useful information in the [Code Signing Troubleshooting Guide](https://github.com/fastlane/fastlane/tree/master/fastlane/docs/Codesigning).

**Comment by KrauseFx** [comment]
This is all actually described in https://docs.fastlane.tools/codesigning/GettingStarted/, in the [Xcode docs](https://docs.fastlane.tools/codesigning/XcodeProject/) it is described how you can set up code signing for multiple targets 👍

**Comment by KrauseFx** [comment]
I'll close the issue for now, as fastlane's recommended setup is to specify either the profile in Xcode 8, or to use environment variables in Xcode 7 and below

**Comment by chrisfsampaio** [comment]
👍

**Comment by jeeftor** [comment]
@chrisfsampaio  - thanks for this issue it gave me a workaround to get things working in my situation.  In my case i have 2 targets with 3 different profiles per target in my code.  

Using the     `xcargos: "PROVISIONING_PROFILE_SPECIFIER='Foo AppStore'"` helped things along.

**Comment by RyanCopley** [comment]
@KrauseFx I have an app that has over 40 instances in the store, now using Xcode 8 this is going to be a nightmare if I can do this programmatically :/

**Comment by danielbowden** [comment]
I'm in a similar situation to @RyanCopley. We have 3 targets (app, watch app, watch extension) and use fastlane to build many instances of the same product for clients. Each of these instances have their own bundle ids / provisioning profiles and up until now we have generated different `.env` files to manage this.

Along with this we were using sigh UDID and environment variables to select the correct provisioning profiles for the targets in the project. And using the Other field to point at the environment variable.

```
ENV["XX_WATCHKIT_TARGET_PROFILE"] = sigh(
      app_identifier: "#{ENV["APP_IDENTIFIER"]}.watchkitapp",
      filename: "#{ENV["APP_IDENTIFIER"]}.watchkitapp.mobileprovision",
      output_path: ENV["ARTIFACT_OUTPUT_PATH"]
    )
``` 

I understand that with Xcode 8 we should be now using the `PROVISIONING_PROFILE_SPECIFIER` and have successfully migrated to this on a much simpler vanilla project. What is the approach on Xcode 8? 

sigh returns the UDID, is there a way to retrieve the profile name from sigh so I can place this in an environment variable.

**Comment by puttin** [comment]
@danielbowden 
> sigh returns the UDID, is there a way to retrieve the profile name from sigh so I can place this in an environment variable?

checkout method in https://github.com/fastlane/fastlane/issues/6245

**Comment by danielbowden** [comment]
Interesting, thanks @puttin. I was just looking at how match does it internally too.

https://github.com/fastlane/fastlane/blob/master/match/lib/match/runner.rb#L102-L116

It already handles the parsing, via 
```ruby
FastlaneCore::ProvisioningProfile.parse(profile)
```

Provided I could get the correct profile path to pass to it, I could do.
```ruby
 parsed = FastlaneCore::ProvisioningProfile.parse(profile)
 name = parsed["Name"]
```

Though that may be a method better suited to be on provisioning_profile.rb like `udid` is:

https://github.com/fastlane/fastlane/blob/fa5fc3ef7ef22c9e6b760f0e15b7f2498beb151e/fastlane_core/lib/fastlane_core/provisioning_profile.rb#L37-L39

Is there a safer way to get provisioning profile path than what you have provided?
```ruby
profiles_path = File.expand_path("~") + "/Library/MobileDevice/Provisioning Profiles/*.mobileprovision"
  profile_paths = Dir[profiles_path]
```

As per my `sigh` example in my [previous comment above](https://github.com/fastlane/fastlane/issues/6118#issuecomment-250355996) I guess I already have specified the filename and output_path so I could take it from there?

**Comment by puttin** [comment]
@danielbowden It seems that my Xcode only use profile in the library position.
You can modify the method use your dir to try.

**Comment by rodriguv** [comment]
Hey @jeeftor! That sounds exactly like the solution I need for the sticker extensions which has two targets. One main app and one extensions with two different profiles. What did you setup look like?

**Comment by danielbowden** [comment]
In line with [my comment above](https://github.com/fastlane/fastlane/issues/6118#issuecomment-250361514) I have created a Fastlane action to retrieve the provisioning profile specifier from a provided profile.

I am happy to put this up as an actions PR if others find this useful. There is a gist of it here: https://gist.github.com/danielbowden/7cb4a5c71a0372ea3b7ceeae1c71022a

```ruby
module Fastlane
  module Actions
    module SharedValues
      GET_PROVISIONING_PROFILE_SPECIFIER_CUSTOM_VALUE = :GET_PROVISIONING_PROFILE_SPECIFIER_CUSTOM_VALUE
    end

    class GetProvisioningProfileSpecifierAction < Action
      def self.run(params)
        profile_path = params[:profile]
        UI.message "Provisioning profile: #{profile_path}"

        parsed = FastlaneCore::ProvisioningProfile.parse(profile_path)
        parsed["Name"]
      end

      #####################################################
      # @!group Documentation
      #####################################################

      def self.description
       "Returns the provisioning profile specifier for the provided provisioning profile"
      end

      def self.details
        "Returns the provisioning profile specifier for the provided provisioning profile"
      end

      def self.available_options
        [
          FastlaneCore::ConfigItem.new(key: :profile,
                                       env_name: "FL_GET_PROVISIONING_PROFILE_SPECIFIER_PROFILE_PATH",
                                       description: "The path to a provisioning profile",
                                       optional: false,
                                       verify_block: proc do |value|
                                          UI.user_error!("Couldn't find provisioning profile at path `#{value}`") unless File.exist?(value)
                                       end
                                      )
        ]
      end

      def self.output
        [
          ['GET_PROVISIONING_PROFILE_SPECIFIER', 'The corresponding provisioning profile specifier']
        ]
      end

      def self.return_value
        "The returned provisioning profile specifier is to be used in an environment variable for Xcode 8+ to use in order to select the correct provisioning profile"
      end

      def self.authors
        ["danielbowden"]
      end

      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end
```

I have run this on several different projects using the Xcode 8 build tools. The projects have 3 targets (app, watch app, watch extension) and I've verified the embedded provisioning profile in each of these packaged payloads is as expected.

My Xcode 8 project specifies each of the provisioning profiles using environment variables similar to the way it was done in Xcode 7, though this time it uses the name specifier. See screenshot

![screen shot 2016-10-11 at 2 49 54 pm](https://cloud.githubusercontent.com/assets/1997110/19258260/32448222-8fc2-11e6-9e5a-c1d1be216da5.png)

My Fastfile uses the profile retrieved via `sigh` and passes it to my action `get_provisioning_profile_specifier profile: <profile_path>` 

```ruby
sigh(
      app_identifier: "#{ENV["APP_IDENTIFIER"]}.watchkitapp",
      filename: "#{ENV["APP_IDENTIFIER"]}.watchkitapp.mobileprovision",
      output_path: ENV["ARTIFACT_OUTPUT_PATH"]
)

ENV["AS_WATCHKIT_TARGET_PROFILE"] = get_provisioning_profile_specifier profile: File.join("#{ENV["ARTIFACT_OUTPUT_PATH"]}", "#{ENV["APP_IDENTIFIER"]}.watchkitapp.mobileprovision")
    
UI.message "ENV AS_WATCHKIT_TARGET_PROFILE: #{ENV["AS_WATCHKIT_TARGET_PROFILE"]}".blue
```

**Comment by jeeftor** [comment]
I actually wrote up what I ended up doing in a medium article (https://medium.com/@Jeef/coming-to-terms-with-xcode-8s-new-build-settings-with-fastlane-75a06ebf2c18#.9ci88e47i) 

Basically what I wrote here didn't actually end up working for me.  My approach was to actually manually rewrite the project file and use manual signing.  But it works well.

**Comment by TKBurner** [comment]
@jeeftor Thanks so much for sharing. Really glad to have you as part of our community 👍

**Comment by KrauseFx** [comment]
@jeeftor what's the reason you're not using environment variables as described [here](https://docs.fastlane.tools/codesigning/xcode-project/)? This way you don't have modify and revert the project file.

**Comment by biolinh** [comment]
That is weird that when I configured

 "xcargs "PROVISIONING_PROFILE_SPECIFIER='#{ENV["PROVISIONING_PROFILE_SPECIFIER"]}'""
in Gymfile, it build forever with Jenkins and take me 5h11m in local (running in my laptop) to build app.

Gymfile:
```
output_directory "./build/"
output_name "360"
include_symbols "false"
include_bitcode "false"
codesigning_identity  (ENV["CODE_SIGN_IDENTITY"])
# provisioning_profile_path ENV["SIGH_OUTPUT_PATH"]
xcargs "PROVISIONING_PROFILE_SPECIFIER='#{ENV["PROVISIONING_PROFILE_SPECIFIER"]}'"
configuration "Fastlane"
```
Fastlane: 1.105.3

**Comment by zake1989** [comment]
@KrauseFx @TKBurner Is there any way to specify the target when I set provisioning profile with provisioning_profile_specifier? Because I got extension in side my project, each target should be set with one unique provisioning profile, separately. 

below is my gym content, I got it working for those projects without multiple targets. And I already try the action update_project_provisioning, which didn't work for Xcode 8 anymore.

```
defined = output+" PROVISIONING_PROFILE_SPECIFIER='#{ENV["BUILD_PROVISIONING_PROFILE_TARGET"]}' DEVELOPMENT_TEAM='$(sigh_#{options[:app_identifier]}_adhoc_team-id)'"
    base_gym(
      configuration: "Release",
      user_defined: defined, 
      postfix: postfixString, 
      workspace: options[:workspace],
      xcodeproj: options[:xcodeproj],
      scheme: options[:scheme], 
      package_name: options[:package_name], 
      export_method: "ad-hoc",
      codesigning_identity: "#{ENV["BUILD_CODESIGNING_IDENTITY"]}" 
      )
```

**Comment by TKBurner** [comment]
@zake1989 I think you'll need to setup manual code signing in Xcode for your project and then it'll work properly with gym. Let me know how it goes!

**Comment by vbresults** [comment]
@zake1989 @TKBurner If you are doing multiple build steps and need to sign a project in a CI environment before you can pass it to gym, use this: https://gist.github.com/vbresults/9da2b42e0fabf111a100e05c502aba98
