### ISSUE TITLE
Unable to import/use SnapshotHelper.swift in Objective-C project

### ISSUE THREAD

**Issue by Sea-Eagle** [fastlane/fastlane#6119]
Hi All I'm also facing same issue. I configured snapshot and generated SnapshotHelper.swift, added it to my Test Target and writing following code in Test.m file throws error

```

XCUIApplication *app = [[XCUIApplication alloc] init];
[Snapshot setupSnapshot:app];
[app launch];

But it is showing error "Use of undeclared identifier 'Snapshot'".
Bridge file UITests-Bridging-Header.h is empty with comments

//
// Use this file to import your target's public headers that you would like to expose to Swift.
//

```

XCode : 7.3.1
Defines Module : YES

Can any one resolved this issue

**Comment by xta** [comment]
I'm also getting `"Use of undeclared identifier 'Snapshot'"` issue following the [Quick Start](https://github.com/fastlane/fastlane/tree/master/snapshot#quick-start)

Note: I'm using the Xcode 8 Bridging-Header helper when adding the SnapshotHelper.swift file

**Comment by TKBurner** [comment]
@Sea-Eagle Are you still running into this issue? Did you follow these steps:

`Create a new UI Test target in your Xcode project (top part of this article)
Run snapshot init in your project folder
Add the ./SnapshotHelper.swift to your UI Test target (You can move the file anywhere you want)
(Objective C only) add the bridging header to your test class.
#import "MYUITests-Swift.h"
The bridging header is named after your test target with -Swift.h appended.
In your UI Test class, click the Record button on the bottom left and record your interaction
To take a snapshot, call the following between interactions
Swift: snapshot("01LoginScreen")
Objective C: [Snapshot snapshot:@"01LoginScreen" waitForLoadingIndicator:YES];
Add the following code to your setUp() method`

**Comment by Sea-Eagle** [comment]
Sorry for delay.
Still I'm getting the issue even following above steps

**Comment by TKBurner** [comment]
@Sea-Eagle Thanks for following up. Can you provide a sample project or exact repro steps from a blank project? I'd love to investigate this. Thanks!

**Comment by 0xced** [comment]
I had the same issue because I did not import the right *bridging header* file. The quick start says
> * #import "MYUITests-Swift.h"
> * The bridging header is named after your test target with -Swift.h appended.

I think the use of the *bridging header* word is a bit misleading since you must `#import "My_App_UI_Tests-Swift.h"`, which is **not** the `My App UI Tests-Bridging-Header.h` file generated by Xcode when you added the first swift file to your project.

You have to guess the `My_App_UI_Tests-Swift.h` filename since it only exists deep inside the derived data directory of your project. If you don't want to guess the filename, you can find it like that:

```bash
find ~/Library/Developer/Xcode/DerivedData/ -name "*-Swift.h"
```

**Comment by intari** [comment]
I encountered same issue. In my case project cleanup, rebuild and restart of tests helped. file was generated with correct name.
