### ISSUE TITLE
How can I get the password of match create sign,I want to know the password for .p12

### ISSUE THREAD

**Issue by yaochenfeng** [fastlane/fastlane#6121]
I use the match create p12 file,and I don't know the password ,how can I get the password

**Comment by TKBurner** [comment]
@yaochenfeng The password should match the one you used to encrypt your repo. Let me know if that works. Thanks!

**Comment by KrauseFx** [comment]
You can open the Keychain on the mac you already used _match_ on and search for "match" 👍
