### ISSUE TITLE
how i can call supply directly in ruby script

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#6123]
I am wondering if there is a way to call **supply** directly in ruby script. So far i am doing that

`  result = %x(cd tmp/#{app.package}/ && supply -j 'Google_Play_Android_Developer.json' -p '#{app.package}' 2>&1)`

i have tried to that

`Supply(Google_Play_Android_Developer.json,app.package)`

it's not working :(

**Comment by TKBurner** [comment]
@bolom Looks like you got up and running. Hope you have a great weekend coming up!
