### ISSUE TITLE
Category select and iMessage Screenshot upload isn't working.

### ISSUE THREAD

**Issue by cagataycali** [fastlane/fastlane#6124]
### New Issue Checklist
- [y] Updated fastlane to the latest version
- [y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

With new iOS 10.0.1, Apple has new extension for **iMessage sticker package extension**. 
- Fastlane can not select properly project category as "Stickers" as well as sub categories.
- Fastlane can not upload iMessage screen shots with deliver.
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

**Default Fastfile configration.**
### Environment

fastlane version (run `fastlane -v`): **fastlane 1.102.0**

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **n**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **n**

**Comment by sahin** [comment]
+1

**Comment by muhammet** [comment]
+ 1 Same problem

**Comment by TKBurner** [comment]
Hi @cagataycali @sahin @muhammet Thanks for pointing this out. I'm going to let the team here know about this. We'd love to see a PR supporting this functionality, but will implement it internally if we can't find a community member. Hope you are all having a great week!

**Comment by TKBurner** [comment]
@cagataycali @sahin @muhammet Had a chance to talk to the team about it. We are taking this work up internally and hope to have an update in the coming week or two. Thanks!

**Comment by asfalcone** [comment]
@cagataycali Can you further explain "Fastlane can not select properly project category as "Stickers" as well as sub categories."?

I was able to set primary_category to Stickers, and primary_first_sub_category to Art and use deliver to upload and download the metadata. 

Can you provide a stacktrack or error you're getting? Thanks 👍

**Comment by asfalcone** [comment]
I am now able to see the issues. The category is actually "Apps.Stickers" not "Stickers". I'll make a PR to prepend Apps. 👍

**Comment by asfalcone** [comment]
Stickers category fixed here https://github.com/fastlane/fastlane/pull/6257

**Comment by HenryGlendening** [comment]
Has anyone found a way to upload iMessage screen shots with deliver yet?

**Comment by sahin** [comment]
@HenryGlendening we do a lot of small hacks and we have like 200+ apps now. , 

u can use our platform https://mojilala.com and https://creators.mojilala.com to publish your stickers.

**Comment by TKBurner** [comment]
@HenryGlendening Can you let me know if you were able to implement the fix in #6257? Do you have a different type of imessage screenshot? If so, can you provide exact repro steps and maybe a sample project? Thanks!

**Comment by JustinJiaDev** [comment]
@TKBurner Any updates on this? iMessage Screenshots are like Apple Watch Screenshots. They are different from the app screenshots and currently deliver doesn't support uploading them.

**Comment by TKBurner** [comment]
@JustinJiaDev Followed up with the team. We'll work with you here.

**Comment by JustinJiaDev** [comment]
@TKBurner Is there anything I can help? I'm willing to provide any information. I read the `spaceship` source code and it seems like iTunes Connect uses a different API (or JSON key) for iMessage screenshots? But I couldn't find any documentation online.

**Comment by JustinJiaDev** [comment]
@TKBurner Some updates:

Using Apple's iTMSTransporter, I got a XML file of my iMessage app which looks like this:

```
                            <software_screenshots>
                                <software_screenshot display_target="iOS-5.5-in" position="1">
                                    <size>428898</size>
                                    <file_name>1242x2208.jpg</file_name>
                                    <checksum type="md5">d41d8cd98f00b204e9800998ecf8427e</checksum>
                                </software_screenshot>
                                <software_screenshot display_target="iOS-5.5-in" position="2">
                                    <size>501920</size>
                                    <file_name>1242x2208.png</file_name>
                                    <checksum type="md5">d41d8cd98f00b204e9800998ecf8427e</checksum>
                                </software_screenshot>
                                <software_screenshot display_target="iOS-iPad-Pro" position="1">
                                    <size>470947</size>
                                    <file_name>2048x2732.jpg</file_name>
                                    <checksum type="md5">d41d8cd98f00b204e9800998ecf8427e</checksum>
                                </software_screenshot>
                                <software_screenshot display_target="iOS-iPad-Pro" position="2">
                                    <size>679605</size>
                                    <file_name>2048x2732.png</file_name>
                                    <checksum type="md5">d41d8cd98f00b204e9800998ecf8427e</checksum>
                                </software_screenshot>
                            </software_screenshots>
```

I think position 2 is for iMessage screenshots.

**Comment by TKBurner** [comment]
@JustinJiaDev Thanks that'll help when we have a chance to action this!

**Comment by JustinJiaDev** [comment]
@TKBurner Any update? Currently we are using fastlane to manage 40+ iMessages sticker pack apps. It would be great if we can also use fastlane to upload iMessage screenshots!

I tried to use `Surge` to monitor the network requests.

```
URL: https://du-itc.itunes.apple.com/upload/image

Request Header:

POST /upload/image HTTP/1.1
Host: du-itc.itunes.apple.com
Accept: application/json, text/plain, */*
X-Apple-Request-UUID: 1c5664c6-fe54-427c-949d-8c5fe7ab52fc
X-Apple-Upload-ContentProviderId: 118418461
X-Apple-Upload-Referrer: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1161628288/ios/versioninfo
X-Apple-Upload-Validation-RuleSets: MZPFT.SortedJ99MessagesScreenShot
X-Apple-Upload-AppleId: 1161628288
Accept-Language: en-us
X-Apple-Upload-itctoken: wYv+NwzFh0iG6sesoL4pM2WuCBY8J8tel1E6ePFVH9c=
Origin: https://itunesconnect.apple.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14
X-Original-Filename: 2-Screenshot-2048x2732-1.jpg
Referer: https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/1161628288/ios/versioninfo
Content-Length: 360582
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Type: image/jpeg

Request Body:

// Actual Image

Response Header:

HTTP/1.1 201 Created
X-Apple-Jingle-Correlation-Key: DRLGJRX6KRBHZFE5RRP6PK2S7Q
X-Apple-Request-UUID: 1c5664c6-fe54-427c-949d-8c5fe7ab52fc
apple-seq: 0
apple-tk: false
Apple-Originating-System: MZDirectUploader
Access-Control-Allow-Origin: https://itunesconnect.apple.com
Location: http://du-itc.itunes.apple.com/upload/image/NULL
Last-Modified: Sat, 29 Oct 2016 07:17:30 GMT
Content-Type: application/json
Transfer-Encoding: chunked

Response Body:

{
  "height" : 2732,
  "hasAlpha" : false,
  "length" : 360582,
  "md5" : "d41d8cd98f00b204e9800998ecf8427e",
  "width" : 2048,
  "tokenType" : "AssetToken",
  "token" : "Purple19\/v4\/2b\/aa\/4a\/2baa4a1f-2851-230f-1a1d-bc06932b4c4f\/pr_source.jpg",
  "type" : "MZSortedJ99MessagesScreenShotImageType.SOURCE"
}
```

**Comment by JustinJiaDev** [comment]
@TKBurner I opened a pull request: https://github.com/fastlane/fastlane/pull/6823

**Comment by TKBurner** [comment]
@JustinJiaDev Awesome! We'll work with you there 👍 👍

**Comment by JustinJiaDev** [comment]
@TKBurner I have submitted my PRs last week. Is there anything else I should do to get them merged? Thanks!

**Comment by ConfusedVorlon** [comment]
@vpolouchkine again:  #4628
I have certainly given up on pull requests. It would be nice if you could work to stop @JustinJiaDev doing the same.

**Comment by JustinJiaDev** [comment]
@ConfusedVorlon Thanks for the friendly bump XD

The issue was opened 2 months ago. I provided some information to the team a month ago. Without any sign of progress (I assumed they were busy), I decided to implement the feature myself. It's a pretty big change (300+ lines of code added). I spent a couple days working on it and finished everything two weeks ago. I split my changes into two PRs as requested, but after that no one replies to me anymore.

I think many developers would love to see the support of uploading iMessage screenshots. I would like to work with the team to get my PRs merged.

**Comment by ConfusedVorlon** [comment]
yup - it's certainly a feature I'd like to use.
fingers crossed that someone gets to it eventually. 

I think it is a crying shame to leave people who contribute this kind of code frustrated and ignored. Unfortunately, fastlane under new management doesn't seem equipped to work with third party contributors effectively.

**Comment by ConfusedVorlon** [comment]
excellent. thanks @JustinJiaDev
