### ISSUE TITLE
[Circle CI] - Build Failed, but badge shows pass

### ISSUE THREAD

**Issue by maschall** [fastlane/fastlane#6125]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Pulled down latest code from Github
Executed `bundle exec rake test_all`

### Results

Finished in 98.003 seconds
2211 examples, 1 failure(s)

==========================================
| 1 repo(s) with test failures: snapshot |
==========================================

1) Snapshot Snapshot::TestCommandGenerator Valid Configuration default options uses the default parameters on tvOS too
Failure/Error: Snapshot.config = FastlaneCore::Configuration.create(Snapshot::Options.available_options, options)
Device 'Apple TV 1080p' not in list of available simulators 'iPhone 6, iPhone 6s Plus'# snapshot/spec/test_command_generator_spec.rb:11:in `configure'

Failed examples:
snapshot/spec/test_command_generator_spec.rb:37 # Snapshot Snapshot::TestCommandGenerator Valid Configuration default options uses the default parameters on tvOS too

**Comment by KrauseFx** [comment]
You didn't share all the information that's required by the issue template. Also please share your `.circle.yml`

**Comment by maschall** [comment]
You're right, and I now seeing it pass :)

**Comment by TKBurner** [comment]
@maschall So glad you got up and running! Always feel free to reach out or contribute. Have a great week 👍
