### ISSUE TITLE
Swift 3 issues

### ISSUE THREAD

**Issue by kalvish21** [fastlane/fastlane#6128]
I'm not able to run snapshot with xcode 8 (final) with Swift 3 as the SnapshotHelper.swift file is not written for it. Is there a compatible version i'm not familiar with?

**Comment by KrauseFx** [comment]
Currently you could probably just migrate the file locally on your machine, until we provide a fix 👍

**Comment by KrauseFx** [comment]
We just prepared https://github.com/fastlane/fastlane/pull/6218, this will be in the next _snapshot_ release 👍 
In the mean-time you can already download the updated template from the PR
