### ISSUE TITLE
Lane list

### ISSUE THREAD

**Issue by WilliamParty** [fastlane/fastlane#6132]
Hi everybody,

I was wondering if there is a way to know what lanes are defined in a specific Fastfile.

Thank you!

**Comment by truth3** [comment]
@WilliamParty You can do the following `fatlane lanes` to expose all the available lanes in your Fastfile.

**Comment by WilliamParty** [comment]
Thank you @truth3 ! Very much appreciated ;)

**Comment by KrauseFx** [comment]
Thanks for your help @truth3 👍
