### ISSUE TITLE
Language settings for new app

### ISSUE THREAD

**Issue by freynolds** [fastlane/fastlane#6134]
fastlane 1.103.0

Hello, I'm skipping most of the common issue template because this is something I've been searching in the docs and can't find.
When creating an app with produce, it normally creates it with the default language English. Since most of my apps are only in spanish, I need to configure this so that I can set the default language to spanish and delete completely the english one. Is there a way to do this with produce? or deliver?

My regards
Francisco

**Comment by TKBurner** [comment]
Hi @freynolds If you set 

`-m, --language STRING Primary Language (e.g. 'English', 'German') (PRODUCE_LANGUAGE)`

You'll be able to avoid the English. 

`PRODUCE_LANGUAGE="Spanish" fastlane init`
