### ISSUE TITLE
Pilot - Is there a way to add a tester to a Group?

### ISSUE THREAD

**Issue by bpham711** [fastlane/fastlane#6136]
### New Issue Checklist
- [ x] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

We have many different groups and I'd like a way to add new testers to specific groups in TestFlight. Is there a way to do that with Pilot?

**Comment by TKBurner** [comment]
@bpham711 _pilot_ doesn't currently have support for groups. I'm marking this as a feature request so we can see if there is interest. Thanks!

**Comment by wacheski** [comment]
I am interested. Just tried to include groups in the import csv :)

**Comment by TKBurner** [comment]
@wacheski Have you checked out spaceship? You might be able to get it working there.

**Comment by wacheski** [comment]
@bpham711 Thanks. I don't see group support yet, but will have a closer look.

**Comment by daneov** [comment]
👍

**Comment by wacheski** [comment]
A beautiful thing. Works great. Thanks!
