### ISSUE TITLE
spaceship incorrectly reports "Successfully logged in to iTunes Connect" for a user who is not in iTunes Connect.

### ISSUE THREAD

**Issue by stevekohls** [fastlane/fastlane#6138]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

`spaceship -u [my email]` incorrectly reports "Successfully logged in to iTunes Connect" for a user who is not in iTunes Connect.

When initializing  a new project using `fastlane init --verbose` I received an "Unauthorized Access" error. During the debug process, I ran `spaceship -u [my email]`. This reported that it successfully logged in to iTunes Connect. See issue #6084 for more background.

Within `spaceship` if I execute `Spaceship::Tunes::Application.all` I see an `Unauthorized Access` error, as I would expect.

After some investigation, I determined that I had not been added to my company's iTunes Connect portal.

After being added to iTunes Connect, `Spaceship::Tunes::Application.all` correctly returns the list of our applications.

I have verified I am using the latest versions of fastlane and all dependencies, as well as the Xcode command-line tools. fastlane does not crash and I am able to continue with the manual steps once access fails.
##### Complete output when running fastlane, including the stack trace and command used

Output when a user is not in iTunes Connect:

```
$ spaceship -u xxx@xxx.com

Logging into to iTunes Connect (xxx@xxx.com)...
Successfully logged in to iTunes Connect

Logging into the Developer Portal (xxx@xxx.com)...
Successfully logged in to the Developer Portal

---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------

Enter docs to open up the documentation
Enter exit to exit the spaceship playground
Enter _ to access the return value of the last executed command

Just enter the commands and confirm with Enter
[1] pry(main)> 
```

With no valid user, if I execute `Spaceship::Tunes::Application.all` I see an `Unauthorized Access` error, as I would expect.

```
[6] pry(main)> Spaceship::Tunes::Application.all
Spaceship::Client::UnauthorizedAccessError: Unauthorized Access
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.32.1/lib/spaceship/client.rb:428:in `block in send_request'
```

With a valid user, the list of applications is output.
### Environment

fastlane version (run `fastlane -v`): **1.102.0**

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? **NO**

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? **NO**

**Comment by TKBurner** [comment]
@stevekohls Thanks for reaching out. You must be an iTC admin to get full functionality with Fastlane. The API permissions are more restrictive than the front end rules and that is why you are experiencing this situation. Thanks!
