### ISSUE TITLE
[gym] gym swallows dependency errors in Xcode 8 builds

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#6140]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Code signing issues are not printed to stdout by fastlane after migrating to Xcode 8.
The archive fails with error code `65` and `fastlane` properly reports the failure.
However, `fastlane` doesn't print actual reason to stdout so developer has to dig down into the logs to find out what the reason is.

This is an example of the error message from build log:

```
Check dependencies
No certificate matching 'iPhone Developer: ABC (ABC)' for team 'XYZ':  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
```

##### Complete output when running fastlane, including the stack trace and command used

```
| 100  | Switch to ios build lane                                      | 0           |
| 101  | gym                                                           | 173         |
| 102  | is_ci                                                         | 0           |

fastlane finished with errors
Process exited with code 1
Step Run Fastlane CI Lane (Command Line) failed
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  gym(
    sdk: "iphoneos",
    workspace: $XCODE_WORKSPACE,
    scheme: scheme,
    configuration: "Release",
    clean: clean_build?,
    codesigning_identity: default_code_signing_identity,
    archive_path: "#{$ARCHIVE_PATH}/#{scheme}",
    output_directory: ".",
    output_name: "#{scheme}.ipa",
    xcargs: "BUILD_NUMBER=#{build_counter}",
    buildlog_path: $BUILD_LOG_PATH,
    include_bitcode: false,
    use_legacy_build_api: true
  )
```

### Environment

fastlane version (run `fastlane -v`): `1.102.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Yes, `rvm`

**Comment by ChristopherDrum** [comment]
Most frustrating was that the hidden gym log contained the **most** useful debugging information I've seen so far. Why it isn't output to console, I don't know.

**Comment by TKBurner** [comment]
Hi @mgrebenets Can you share the full input and output? Also do you see the added output with the --verbose flag? Thanks!

**Comment by KrauseFx** [comment]
_fastlane_ uses [xcpretty](https://github.com/supermarin/xcpretty) under the hood, which is kind of out our control. Feel free to submit the issue on the _xcpretty_ repo or submit a pull request for it 👍

**Comment by mgrebenets** [comment]
Indeed, it seems to be tracked there already https://github.com/supermarin/xcpretty/issues/235.
Should I close this one or keep it open until `xcpretty` releases a patch?

**Comment by mgrebenets** [comment]
@ChristopherDrum I think the log is not printed to console on purpose. In our case full Team City logs get HUGE, tens of megabytes. TeamCity's build log page takes quite a long time to load and render it in our case.

**Comment by KrauseFx** [comment]
Let's close it here, since it's not directly related to _fastlane_ and no action is required from our side 👍
