### ISSUE TITLE
Sigh download_all Skipping invalid/expired profile 

### ISSUE THREAD

**Issue by maxydon** [fastlane/fastlane#6141]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue description
sigh download_all -> "Skipping invalid/expired profile" even though sigh manage and developer.apple.com said all provisioning profiles were valid

##### Complete output when running fastlane, including the stack trace and command used

```
sigh download_all
[17:18:07]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: xxx
[17:18:14]: Starting login with user 'xxx'
[17:18:17]: Successfully logged in
[17:18:17]: Skipping invalid/expired profile 'xxxx'
```

### Configuration Files

Not applicable

### Environment

fastlane version (run `fastlane -v`): 1.103.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by triage** [comment]
we're having this issue as of today as well. our profiles are definitely valid and not expired.

**Comment by maschall** [comment]
This sounds like the same issue as #6137

**Comment by SandyChapman** [comment]
Same thing as #6144 too, I think.

**Comment by TKBurner** [comment]
Thanks all for working together to report this. Hope you all have pulled the update and looked at #6137. This is now resolved, if you run into the issue please read and update #6137
