### ISSUE TITLE
sigh: Cannot create or download AdHoc provisioning profile with Enterprise account 

### ISSUE THREAD

**Issue by SandyChapman** [fastlane/fastlane#6144]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm attempting to download an existing AdHoc provisioning profile (not InHouse!) from my Enterprise account. However, whenever I try to use the `--adhoc` flag the operation fails. Without the flag, `sigh` thinks I want to create a new InHouse profile, generates a new name and creates / downloads it.

How can I download my AdHoc profile using sigh?

##### Complete output when running fastlane, including the stack trace and command used

```
$ sigh --app_identifier my.app.id --provisioning_name 'My Profile AdHoc' --team_id MYT34M1D --ignore_profiles_with_different_name --adhoc --username me@myemail.com


+-------------------------------------+--------------------+
|                 Summary for sigh 1.10.2                  |
+-------------------------------------+--------------------+
| app_identifier                      | my.app.id    |
| provisioning_name                   | My Profile AdHoc |
| team_id                             | MYT34M1D         |
| ignore_profiles_with_different_name | true               |
| adhoc                               | true               |
| username                            | me@myemail.com |
| skip_install                        | false              |
| development                         | false              |
| force                               | false              |
| skip_fetch_profiles                 | false              |
| skip_certificate_verification       | false              |
+-------------------------------------+--------------------+

[00:02:28]: Starting login with user 'me@myemail.com'
[00:02:35]: Successfully logged in
[00:02:35]: Fetching profiles...
[00:02:35]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you

[!] Could not find a matching code signing identity for type 'AdHoc'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide.If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert
```

Example without using `--adhoc`:

```
$ sigh --app_identifier my.app.id --provisioning_name 'My Profile AdHoc' --team_id MYT34M1D --ignore_profiles_with_different_name

+-------------------------------------+--------------------+
|                 Summary for sigh 1.10.2                  |
+-------------------------------------+--------------------+
| app_identifier                      | my.app.id    |
| provisioning_name                   | My Profile AdHoc |
| team_id                             | MYT34M1D         |
| ignore_profiles_with_different_name | true               |
| adhoc                               | false              |
| skip_install                        | false              |
| development                         | false              |
| force                               | false              |
| skip_fetch_profiles                 | false              |
| skip_certificate_verification       | false              |
+-------------------------------------+--------------------+

[23:58:08]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: me@myemail.com
[23:58:13]: Starting login with user 'me@myemail.com'
[23:58:16]: Successfully logged in
[23:58:16]: Fetching profiles...
[23:58:17]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[23:58:21]: The name 'My Profile AdHoc' is already taken, using another one.
[23:58:21]: Creating new provisioning profile for 'my.app.id' with name 'My Profile AdHoc 1473994701'
[23:58:23]: Downloading provisioning profile...
[23:58:24]: Successfully downloaded provisioning profile...
[23:58:24]: Installing provisioning profile...
/Users/me/Workspace/project/InHouse_my.app.id.mobileprovision
```

### Configuration Files

None, I'm invoking `sigh` directly.

### Environment

Tested with:
sigh 1.10.2
fastlane 1.102.0
fastlane (latest master 4e722b1da8d2376a5b4408e75b77c81b7b7deb1b)

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Both with and without

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by SandyChapman** [comment]
@fastlane-bot : Thanks, but no. I can properly build my app with the existing profile and identity.

**Comment by SandyChapman** [comment]
Also, I should note, this was working within the last couple months, so it's been broken fairly recently.

**Comment by gmogames** [comment]
This is not just happening on Enterprise, I'm having the same problems with a regular developer account.

This was working fine last month, all of a sudden I went to the developer portal and found out that I had hundreds of provisioning profiles created while I was expecting sigh to download the existing one as it was doing before.

I ran
```
security find-identity -v -p codesigning
  1) DDB599D956BEF832192EDB62FXXXXXXXXX "iPhone Developer: Main Person Name (XXXXXXXXXX)" (CSSMERR_TP_CERT_REVOKED)
  2) CEB57A14815FDB1A139CE50A2XXXXXXXXXX "iPhone Distribution: Fragmob, LLC (XXXXXXXXXX)"
  3) A2BA242F0893EF0FE27FC06DDXXXXXXXXXX "iPhone Developer: Another Person (XXXXXXXXXX)" (CSSMERR_TP_CERT_REVOKED)
  4) 7806B00AA95FE51EA1817F8DA7XXXXXXXXXX "iPhone Developer: Main Person Name (XXXXXXXXXX)" (CSSMERR_TP_CERT_REVOKED)
  5) 9376D8D40FC5A6B2B470395AEXXXXXXXXXX "iPhone Developer: Main Person Name (XXXXXXXXXX)"
```

But everytime I run `sigh --app_identifier com.mybundle.id --adhoc`, I get the message
```
[01:15:37]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[01:15:40]: Creating new provisioning profile for 'com.fragmob.luxx' with name 'com.fragmob.luxx AdHoc'
[01:15:41]: Downloading provisioning profile...

```

We use Jenkins and do not use match as we cannot right now. Our build process is very big as we are a platform that generates several apps from the same codebase, and we always run SIGH to download the provisioning and then GYM to generate the build.

I'm running with all the gems updated to the latest version, the keychain is unlocked, this was working fine and out of the blue it's not anymore, I've tried **--force** but with the same results.

Any input is gladly appreciated

**Comment by nikolaykasyanov** [comment]
Same here, this started happening today.

**Comment by SandyChapman** [comment]
Some more details. I reproduced the exact set of gems that was successful two months ago and its failing now too. My guess is that Apple has changed the API in someway that breaks spaceship. I think this is a deeper issue than just sigh.

**Comment by wilrnh** [comment]
Agree. Same here for Adhoc and Inhouse (Enterprise) builds. Doesn't seem to affect tvOS builds, however (yet?)

**Comment by wilrnh** [comment]
Seems to be affecting tvOS builds now :(

**Comment by jserviss** [comment]
I am seeing the same issue.  
[09:53:18]: Starting login with user 'xxxxxx@xxxxx.com'
[09:53:20]: Successfully logged in
[09:53:20]: Fetching profiles...
[09:53:21]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you

**Comment by SandyChapman** [comment]
Looks like they've fixed this issue on #6137.

**Comment by gmogames** [comment]
Actually it didn't, I've updated to the new version, same problems

**Comment by gmogames** [comment]
Nevermind, The update didn't work, but now it's fine. Thanks!
