### ISSUE TITLE
Missing_method

### ISSUE THREAD

**Issue by chshapiro** [fastlane/fastlane#6153]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I try to run any fastlane commands, I get the following error:

##### Complete output when running fastlane, including the stack trace and command used

```
/Users/xxx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fd56180205c fastlane-1.103.0> (NoMethodError)
	from /Users/xxx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/xx/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/xxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.103.0/bin/fastlane:4:in `<top (required)>'
	from /Users/xxx/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/xxx/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/xxx/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xxx/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`): 

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by TKBurner** [comment]
Hi @chshapiro Thanks for reaching out about this. Can you share the full input and output? I'd love to take a look at what is going on. Also if you create a blank project does it still experience this issue? Thanks!

**Comment by chshapiro** [comment]
I resolved this issue. Thank you!

**Comment by TKBurner** [comment]
@chshapiro Awesome! So glad to hear you got up and running! Hope you have a great weekend coming up 👍
