### ISSUE TITLE
March integration with StackExchange/blackbox

### ISSUE THREAD

**Issue by thiagofelix** [fastlane/fastlane#6154]
Is there any plan to strengthen match cryptography process by integration with tools like https://github.com/StackExchange/blackbox? 

Does anyone thinks it is a good idea at all?

I think the idea is move from a shared passphrase (OpenSSL key) and start using individuals Public/Private pairs instead.

**Comment by KrauseFx** [comment]
Thanks for the idea, however we don't plan on doing so. git itself already handles the public private key encryption, and you have fine control over who gets access to the git repo itself 👍
