### ISSUE TITLE
How to use `increment_build_number` to change build number?

### ISSUE THREAD

**Issue by drosenstark** [fastlane/fastlane#6157]
How do I get my `Current Project Version` to be the actual build number in my Xcode target for iOS?

## `increment_build_number` updates this
![Current Project Version](https://dl.dropboxusercontent.com/s/lrj5z1oevi2oxv5/Screen%20Shot%202016-09-16%20at%206.14.46%20PM.png?dl=0)

## `increment_build_number` does not update this
![](http://dr2050.com/automatic-images/BuildNumberForReal.png)

(I realize this is an Xcode question, but any guidance would be appreciated, thanks!)

**Comment by drosenstark** [comment]
Some of my targets were actually updating and others weren't. It turns out that the top syntax works for Xcode but not for `avgtool`... so you have to replace in your `.pbxproject`

![](https://dl.dropboxusercontent.com/s/sr748orl2xs7gtd/Screen%20Shot%202016-09-16%20at%206.34.43%20PM.png?dl=0)

**Comment by drosenstark** [comment]
Okay, that solved it. So the answer was "run avgtool and see what's up" or something like that.

**Comment by TKBurner** [comment]
@drosenstark Awesome! Glad you got up and running. Always feel free to reach out and have an awesome weekend!
