### ISSUE TITLE
Running one lane after the other within a lane doesn't seem to reload Appfile

### ISSUE THREAD

**Issue by kylejm** [fastlane/fastlane#616]
I've got a lane like this:

```ruby
lane :all do
    prod # this is a lane
    clean_build_artifacts
    staging # this is a lane
    clean_build_artifacts
    dev # this is a lane
  end
```

My app file like this:

```ruby
app_identifier "com.my.app"
apple_id "my@email.com"

for_platform :ios do
  for_lane :staging do
    app_identifier com.my.app-Staging'
  end

  for_lane :dev do
    app_identifier 'com.my.app-Development'
  end
end
```

If I run `fastlane all` the first lane (`prod`) within the `all` lane gets its bundle ID loaded from the Appfile, but then when the second lane (`staging`) runs fastlane crashes at `deliver` because the Bundle ID doesn't match iTC. On inspection, the Bundle ID that deliver is being given to upload `staging` is the Bundle ID of `prod`.

**Comment by KrauseFx** [comment]
The thing is: `fastlane` will always load the information from the `Appfile` from the lane you called from the terminal. This means it will *always* try to fetch `all` from your `Appfile` which you don't have so it falls back to `com.my.app` as app identifier.

**Comment by lemonkey** [comment]
I have a similar situation where if I want to export a build for both the TestFlight and TestFairy, I need to be able to use the "app-store" archive export method for TestFlight while using "ad-hoc" for TestFairy. This currently results in two separate calls to gym in the same overall lane. Both calls to gym generate the expected IPA with the correct filename (where I'm appending the export method to the end of the filename), however, the archive export is the same for both TestFlight and TestFairy (same filename, same export method, etc).

**Comment by kylejm** [comment]
@KrauseFx could I request the feature that Fastlane reloads the Appfile when switching lanes, or do you see this causing problems?

**Comment by KrauseFx** [comment]
I'll take a closer look at this over the days. As always I need to make sure it doesn't break any existing setups.

**Comment by kylejm** [comment]
Awesome! Thx :smile: 

Could `deliver` pickup the Bundle ID from the `Info.plist`?

**Comment by KrauseFx** [comment]
@kylejm yes it does, but I haven't yet implemented this into `deliver 1.0.0.beta1`

**Comment by kylejm** [comment]
@KrauseFx I've come up with a solution using `pilot`:

```ruby
lane :dev do
    gym(scheme: "App Development")
    pilot(username: "my@email.com", app_identifier: "com.my.app-dev", skip_submission: true)
  end

  lane :staging do
    ensure_git_branch(branch: '^release\/v[0-9]\.[0-9]\.[0-9]$')
    gym(scheme: "App Staging")
    pilot(username: "my@email.com", app_identifier: "com.my.app-staging", skip_submission: true)
  end

  lane :prod do
    ensure_git_branch(branch: '^release\/v[0-9]\.[0-9]\.[0-9]$')
    gym(scheme: "App")
    pilot(username: "my@email.com", app_identifier: "com.my.app-dev", skip_submission: true)
  end
```

:blush:

**Comment by KrauseFx** [comment]
Looks good :+1:

**Comment by humblehacker** [comment]
I believe this is the source of a problem I just encountered.  I've got a lane called `ci` that will decide which lane to execute based on branches and tags.  But it fails at `sigh` because I don't have `app_identifier` defined in the global scope of my AppFile, and I wouldn't want it to choose that if it were defined.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
