### ISSUE TITLE
[match] Match does not recognize profiles created by previous version

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#6164]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've used match to create certificate and profile in ADP.
The match version was `0.6.2`
All worked well for a while and people on the team we able to use read-only mode to install certificate and profile.
I was also able to add new devices and update profile, all using `match`.
The profile name was something like `match Development au.com.company.*`.

Then I had to bump `fastlane` to `1.103.0` because spaceship seemed to have issues with logging in. I was getting `Forbidden 403` error.

So I add new device after an upgrade, all works good, device is added to ADP.
Then I try to update profile with same `Matchfile` as before.

```
git_url "ssh://git@out.git.url"
type "development"
app_identifier "au.com.company.*"
readonly "true"
```

This time however, it doesn't recognize the existing profile in ADP and creates a new one instead with name like `match Development au.com.company.* 12345678`.
The match version is now `0.6.4`.

This would be fine otherwise, but not in our setup.
We use `PROVISIONING_PROFILE` in our project build settings, which mean we have profile UDID fixed in build settings.
So people use `match` to keep the profile up-to-date and simply "build and run" after checkout.
Once `match` fails to recognize the profile and creates a new one, it means we have to update Xcode project to keep it up-to-date with ADP.

So it looks like `match` along with `sigh` and `spaceship` didn't recognize the profile created by previous version.
Probably it is by design.
Is it expected behavior or is it due to large changes in ADP in view of Xcode 8, iOS 10 and all that?

Could there be an additional option, so that we could tell `match` to use specific profile if we know for sure it already exists? Or other similar workaround.

### Environment

fastlane version (run `fastlane -v`):
`1.103.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
YES

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
YES, rvm

**Comment by KrauseFx** [comment]
Hey @mgrebenets, thanks for taking the time to report this issue.
We'd need some more information to work on a fix for this:

1. The complete output when running _match_, including the table of parameters
1. The complete tree of your _match_ repo that contains the certificates and profiles

**Comment by nicolasbraun** [comment]
I had the same issue, updating to match 0.7.0 (from 0.6.4) seems to fix it

**Comment by KrauseFx** [comment]
@nicolasbraun Could you also try the latest release from today? 👍

**Comment by nicolasbraun** [comment]
That's ok for me too on 0.8.0 🚀

**Comment by KrauseFx** [comment]
Perfect, I'll close the issue for now, feel free to re-open 👍
