### ISSUE TITLE
Error with gym; Exit Status: 65

### ISSUE THREAD

**Issue by jpmcglone** [fastlane/fastlane#6165]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Trying to build an ENTERPRISE build that will get distributed on Crashlytics or HockeyApp.

Maybe this error is easy for some of you:

```
▸ Building XYZ/XYZ [Release]
▸ Check Dependencies
** ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
[17:35:45]: Exit status: 65
[17:35:45]: Variable Dump:
[17:35:45]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios internal", :GIT_REPO_WAS_CLEAN_ON_START=>true, :CERT_FILE_PATH=>"/Users/jpmcglone/ABC/XYZ/certs/HA837P5PUY.cer", :CERT_CERTIFICATE_ID=>"HA837P5PUY", :SIGH_PROFILE_PATH=>"/Users/jpmcglone/ABC/XYZ/InHouse_com.xyzchat.ios.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/jpmcglone/ABC/XYZ/InHouse_com.xyzchat.ios.mobileprovision"], :SIGH_UDID=>"f374f803-3dfd-415a-ad87-7ae650c10b6a", :SIGH_PROFILE_TYPE=>"enterprise", :BUILD_NUMBER=>"9"}
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.103.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
YES

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
NO

**Comment by ben73** [comment]
Same issue. 
In ~/Library/Logs/gym/<my_build_name>.log
```

=== BUILD TARGET wizl_2 OF PROJECT wizl_2 WITH CONFIGURATION Release ===

Check dependencies
wizl_2 has conflicting provisioning settings. wizl_2 is automatically signed for development, but a conflicting code signing identity iPhone Distribution has been manually specified. Set the code signing identity value to "iPhone Developer" in the build settings editor, or switch to manual signing in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

```

**Comment by ben73** [comment]
https://docs.fastlane.tools/codesigning/XcodeProject/

**Comment by ChristopherDrum** [comment]
I have done all of the things recommended by the fastlane code signing guide. 
Still having problems with code signing **some** subprojects. 
Made a big, explanatory ticket here: https://github.com/fastlane/fastlane/issues/6219

**Comment by TKBurner** [comment]
@jpmcglone Can you share your full input and output? I want to take a look. @ChristopherDrum I'll work with you on your other ticket. Thanks!
