### ISSUE TITLE
Fast Lane Has Issues Building iOS Projects Using CoreData

### ISSUE THREAD

**Issue by josephmisiti** [fastlane/fastlane#6174]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I started a new ios project (obj c) from scratch and checked "use core data" as the option. The ran `fastlane init` and `fastlast gym` and see the following output

```
❌ AppDelegate.h:16:30: unknown type name 'NSPersistentContainer'; did you mean 'NSPersistentStore'?

@property (readonly, strong) NSPersistentContainer *persistentContainer;
                             ^~~~~~~~~~~~~~~~~~~~~


▸ Compiling AppDelegate.m

❌  AppDelegate.h:16:30: unknown type name 'NSPersistentContainer'; did you mean 'NSPersistentStore'?

@property (readonly, strong) NSPersistentContainer *persistentContainer;
           ^



❌ AppDelegate.m:57:4: expected a type

- (NSPersistentContainer *)persistentContainer {
           ^


▸ Compiling ViewController.m
** ARCHIVE FAILED **```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

cfastlane 1.103.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

No

**Comment by KrauseFx** [comment]
This is a compiler error. I assume it has something to do with a new Version of Xcode, but still using Swift 2 or something similar?

**Comment by josephmisiti** [comment]
@KrauseFx i downloaded xcoded beta from the developer site and started a new project. it was objective C, not swift.

**Comment by PaulTaykalo** [comment]
@josephmisiti Make sure that you're using correct `xcodebuild`
- is pointing to the correct Xcode version
See what `xcode-select -p` gives you, and make sure that this one gives you expected Xcode version
also, make sure that you're passing params to the gym (like .xcworkspace, for example)

Does the project coplies in Xcode?

**Comment by josephmisiti** [comment]
@PaulTaykalo @KrauseFx it looks like upgrading to the latest version of xcode fixed this problems! thanks

**Comment by TKBurner** [comment]
@josephmisiti Awesome! Really glad to hear you got up and running 👍
