### ISSUE TITLE
supporting store configuration in Pemfile for pem

### ISSUE THREAD

**Issue by jk2K** [fastlane/fastlane#6176]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

supporting store configuration in Pemfile for [pem](https://github.com/fastlane/fastlane/tree/master/pem)

### Environment
fastlane 1.103.0

**Comment by TKBurner** [comment]
@jk2K Great to hear from you. Can you provide a little more information about what you'd like to see? I'm marking this to see if we get +1s. Thanks!

**Comment by KrauseFx** [comment]
Sorry we don't plan on adding a configuration file for every tool as of now, instead please use a `Fastfile` to call _pem_ with your parameters 👍
