### ISSUE TITLE
Xcode8 export failed with exit status: 70 when having two match account 

### ISSUE THREAD

**Issue by zake1989** [fastlane/fastlane#6180]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I got two match accounts for enterprise distribution sign and App Store distribution sign separately. Before Xcode8 it works fine. After I update to Xcode 8, I have to change all those code sign settings, and it turns out all of those depend on the code sign setting on release. 
if I set the release code sign like the image below it can only use the app store development account certificate
<img width="591" alt="1" src="https://cloud.githubusercontent.com/assets/5278866/18630889/915d7282-7ea1-11e6-906e-cc27a79acb52.png">
if I set the release code sign like the image below it can only use the enterprise development account certificate
<img width="565" alt="2" src="https://cloud.githubusercontent.com/assets/5278866/18630918/b91ec0f0-7ea1-11e6-8ce1-99a1e81bcf1f.png">
##### Complete output when running fastlane, including the stack trace and command used

```
[19:35:39]: Exit status: 70
[19:35:39]: 2016-09-19 11:35:38 +0000 [MT] Running step: IDEDistributionSigningAssetsStep with <IDEDistributionContext: 0x7f842687a1d0; archive(resolved)='<IDEArchive: 0x7f8426a14c00>', distributionTask(resolved)='2', distributionMethod(resolved)='<IDEDistributionMethodEnterprise: 0x7f84268627d0>', teamID(resolved)='(null)'>
    Chain (2, self inclusive):
    <IDEDistributionContext: 0x7f842687a1d0; archive = '(null)', distributionMethod='<IDEDistributionMethodEnterprise: 0x7f84268627d0>', teamID='(null)'>
    <IDEDistributionContext: 0x7f8426a159b0; archive = '<IDEArchive: 0x7f8426a14c00>', distributionMethod='(null)', teamID='(null)'>
</IDEDistributionContext: 0x7f842687a1d0>

[19:35:39]: There was an error exporting your application
[19:35:39]: Unfortunately the new Xcode export API is unstable and causes problems on some projects
[19:35:39]: You can temporary use the :use_legacy_build_api option to get the build to work again
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
  lane :enterprise do |options|
    base_match(git_url:"git@techgit.meitu.com:iosmodule_dev/certificates.git", type: "appstore", app_identifier:"com.meitu.*")
    base_gym(configuration: "enterprise", user_defined: options[:user_defined], postfix: options[:postfix], workspace: options[:workspace],
    xcodeproj: options[:xcodeproj], scheme: options[:scheme], package_name: options[:package_name], export_method: "enterprise")
  end

  desc "上传appstore打包"
  lane :appstoreUpLoad do |options|
    increase_build_number(xcodeproj: options[:xcodeproj])
    base_match(git_url:ENV["GIT_URL"], type: "appstore", app_identifier: options[:app_identifier])
    base_gym(configuration: "distribution", user_defined: options[:user_defined], postfix:        options[:postfix], workspace: options[:workspace],
    xcodeproj: options[:xcodeproj], scheme: options[:scheme], package_name: options[:package_name], export_method: "app-store")
    # base_deliver()
  end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.103.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by zake1989** [comment]
I already follow the guild and try the PROVISIONING_PROFILE_SPECIFIER doesn't work~~

**Comment by zake1989** [comment]
The thing is  gym don't use the provision file I specify in the project.

**Comment by zake1989** [comment]
Think I find out the problem, when gym start archive it sill use the configuration in the image below
<img width="573" alt="3" src="https://cloud.githubusercontent.com/assets/5278866/18654646/6a86fc4a-7f15-11e6-9c18-7f0f9c39d9a7.png">
so now the problem will be  how to change that configuration

**Comment by danleechina** [comment]
could you tell me how to get multiple siging section? Like you pic shows Debug, Release, Enterprise and Distribution?

**Comment by TKBurner** [comment]
@zake1989 Hope you are doing well! Sorry for the delay in updating this thread. _match_ doesn't support enterprise profiles officially and that is part of this issue. Can you let me know what happens if you use the legacy_build_api?

**Comment by zake1989** [comment]
@danleechina do it as follow image, in your project-> just press + button, and rename the one you want to duplicate!!
<img width="715" alt="1" src="https://cloud.githubusercontent.com/assets/5278866/19503647/9d981fe0-95e7-11e6-8807-9cd0ef5aa1e5.png">

**Comment by zake1989** [comment]
@TKBurner I was assigning to another team for short support for last two weeks, and I check my fastfile again, when I got back to CI team. It turns out I made a silly mistake by setting the configurations in lowercase, and the setting in Xcode 8 is case-insensitive. By setting the right name, it works. I will test it with enterprise account with the new doc here. https://docs.fastlane.tools/codesigning/xcode-project/  I will update the progress when I finish this part.

**Comment by TKBurner** [comment]
@zake1989 Thanks for letting me know. I'll leave this open for the time being. Hope you have a great day!

**Comment by zake1989** [comment]
@TKBurner I think I got the issue you mentioned before. And I got a temporary solution. The problem is when I using match to create an App Store provisioning profile with enterprise account. The file in App Store folder is start with InHouse. So other team member can never fetch it with match. I just replace the InHouse with  AppStore. Actually the the enterprise account should have a in-house type profile. In this case, could you and an new type inhouse to match.

**Comment by TKBurner** [comment]
@zake1989 Match doesn't have official support for Enterprise profiles, so this does seem to explain your issue. Thanks!
