### ISSUE TITLE
lcov .gcda files in x86_64 build folder

### ISSUE THREAD

**Issue by rafaortiz** [fastlane/fastlane#619]
Hi,

I'm trying to use  the lcov action to generate code coverage reports, but i'm getting this error:

Capturing coverage data from /Users/rortiz/Library/Developer/Xcode/DerivedData/roproject-fcachpkjymhnigcbynpuoxckbwyt/Build/Intermediates/roproject.build/Debug-iphonesimulator/roproject.build/Objects-normal/i386/
Found gcov version: 7.0.0
Found LLVM gcov version 3.4, which emulates gcov version 4.2
Scanning /Users/rortiz/Library/Developer/Xcode/DerivedData/roproject-fcachpkjymhnigcbynpuoxckbwyt/Build/Intermediates/roproject.build/Debug-iphonesimulator/roproject.build/Objects-normal/i386/ for .gcda files ...
geninfo: WARNING: no .gcda files found in /Users/rortiz/Library/Developer/Xcode/DerivedData/roproject-fcachpkjymhnigcbynpuoxckbwyt/Build/Intermediates/roproject.build/Debug-iphonesimulator/roproject.build/Objects-normal/i386/ - skipping!

When I checked the folder i386 he really no have the .gcda files, but in the folder /Users/rortiz/Library/Developer/Xcode/DerivedData/roproject-fcachpkjymhnigcbynpuoxckbwyt/Build/Intermediates/roproject.build/Debug-iphonesimulator/roproject.build/Objects-normal/x86_64/ the files are created.

How can I configure the lcov to get these files in x86_64 folder or configure the gcov to generate the files in the both folders when i'm testing in x86_64 platform?

Thanks!

**Comment by rafaortiz** [comment]
Just to be clearer, here is the script i'm using:

  lane :beta do
    xctest(
      workspace: "roproject.xcworkspace",
      scheme: "roproject",
      destination: "platform=iOS Simulator,name=iPhone 5s",
      sdk: "iphonesimulator",
      destination_timeout: 120,
      build_settings: {
        "GCC_INSTRUMENT_PROGRAM_FLOW_ARCS" => "YES",
        "GCC_GENERATE_TEST_COVERAGE_FILES" => "YES"
      }
    )

    lcov(
      project_name: 'roproject',
      scheme: 'roproject',
      output_dir: 'coverage_reports'
    )
  end

**Comment by xfreebird** [comment]
Try enabling "Gather coverage data" in ```Scheme -> Test step -> Test```
![Image of Xcode](https://cdn.pbrd.co/images/TQBU2vd.png)

**Comment by rafaortiz** [comment]
Hi @xfreebird, this option is already enabled.

Looking at lcov action, looks like the script supports only i386 architecture, the path for find the files .gcda it is fixed code

```ruby
def self.derived_data_dir(options)
        pn = options[:project_name]
        sc = options[:scheme]

        initial_path = "#{Dir.home}/Library/Developer/Xcode/DerivedData/"
        end_path = "/Build/Intermediates/#{pn}.build/Debug-iphonesimulator/#{sc}.build/Objects-normal/i386/"

        match = find_project_dir(pn, initial_path)

        "#{initial_path}#{match}#{end_path}"
      end
```

@KrauseFx Has some way to detect the architecture and replace in the end_path?

Thanks!

**Comment by KrauseFx** [comment]
@rafaortiz Sorry, I'm not using the `lcov` action myself.

**Comment by rafaortiz** [comment]
I created a pull request to we can specify the architecture in `lcov`

See in:
https://github.com/KrauseFx/fastlane/pull/633#1
