### ISSUE TITLE
Import Certificate Action Log_Output cannot accept a value

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#6199]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

There is a problem where the `log_output` parameter is a boolean, but not specified as such, so it picks up the default parameter type which is string. If one actually tries to use this, you get an error when you try to pass in the default parameter type or the boolean type.

##### Complete output when running fastlane, including the stack trace and command used

```
You passed invalid parameters to 'import_certificate'.
[10:18:14]: Check out the error below and available options by running `fastlane action import_certificate`

[!] 'log_output' value must be a String! Found TrueClass instead.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

**Not necessary**

### Environment

fastlane version (run `fastlane -v`): 1.103.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by lyndsey-ferguson** [comment]
I have an open [PR](https://github.com/fastlane/fastlane/pull/6198)

**Comment by TKBurner** [comment]
@lyndsey-ferguson Thanks for the PR! We'll work with you there. Hope that you have a great weekend coming up!
