### ISSUE TITLE
latest_testflight_build_number doesn't consider Invalid Binaries

### ISSUE THREAD

**Issue by dirkoswanepoel** [fastlane/fastlane#6207]
OS X 10.11.6
fastlane 1.103.0
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

This is not a crash and there is nothing of real value in the Fastfile, or the scripts output. This is easiest to explain as follows:

The Fastfile gets the latest build number from testflight using latest_testflight_build_number.
This value is 14.
The value is incremented and a build is made and uploaded to testflight and we wait for apple's response. (skip_waiting_for_build_processing is not set)
The whole process succeeds and a build is available for download to testers.

A second build is made using the same script.
The build number is now 15, but because of an Invalid Binary error during upload (Entitlements in this case), the binary is rejected.

When any subsequent builds are made, they will fail. This is because the build number will again be set to 15.

The problem is that latest_testflight_build_number only considers valid binaries (or Apple only considers valid binaries when returning the build number), and thus the script will keep trying to upload the same build number. (15 in this case)

**Comment by dirkoswanepoel** [comment]
[Transporter Error Output]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '15' for version '1.1'"

**Comment by TKBurner** [comment]
@dirkoswanepoel Great to hear from you! Can you try uploading a valid build manually and then checking to see if it works? We'd love to see a PR to correct this behavior in the long term. Thanks!
