### ISSUE TITLE
Add raw log option to xcodebuild action

### ISSUE THREAD

**Issue by corristo** [fastlane/fastlane#621]
Recent addition of raw build log support to `gym` is cool and it would be cool to do the same for `xcodebuild` as well.

**Comment by KrauseFx** [comment]
This is for `xcodebuild`. I assume you mean to also cover the second `xcodebuild` which packages up the application? The raw output of the second command is displayed in the terminal anyway, as it's not piped through `xcpretty`.

**Comment by KrauseFx** [comment]
Why would you want to use it?

**Comment by corristo** [comment]
@KrauseFx I'm using `xctest` to build the app & run tests and I'd like to use [Jenkins Warnings Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Warnings+Plugin).

This plugin supports Clang/LLVM output & works well with raw `xcodebuild` output, but it doesn't seem to like xcpretty output, unfortunately.

**Comment by KrauseFx** [comment]
There is no more `xcpretty` output. Building will now show you the `xcpretty` output, but will also export the raw content in your `~/Library/Logs/gym`. You should be able to use that file.

**Comment by corristo** [comment]
@KrauseFx but I'm not using gym, I'm using xctest.

**Comment by iKorich** [comment]
I have same issue with xcode project

I made a script, it's works fine from terminal
but when I run it from Jenkins I have an error:

```
sh: xcpretty: command not found
** ARCHIVE FAILED **           
                    

The following commands produced analyzer issues:
AnalyzeShallow SocketRocket/SRWebSocket.m       
(1 command with analyzer issues)         
                                
The following build commands failed:
Check dependencies                  
(1 failure)   
```

And ca't find a way to check error.
my script doesn't use xcpretty
Jenkins Warnings Plugin doesn't shows any logs((

**Comment by xfreebird** [comment]
This is something that is being brewed in PR #626

**Comment by corristo** [comment]
@xfreebird :+1:

**Comment by xfreebird** [comment]
This was added in the latest release.

**Comment by KrauseFx** [comment]
Thanks again @xfreebird
