### ISSUE TITLE
How to use with pem, apple pay certs

### ISSUE THREAD

**Issue by blackxored** [fastlane/fastlane#6220]
I've a push notification cert generated by manually running `pem`, I've also an Apple Pay cert that was also manual cause lack of support. Intermittently those don't seem to be part of my provisioning profile (specially the push cert which gives me a warning from Apple after upload occasionally), I'm fairly new can someone point me to how to fix this?

**Comment by TKBurner** [comment]
HI @blackxored We don't support Apple Pay certs yet, but I can make this a feature request. Can you please provide your full input and output if you are getting any errors with _pem_? I want to look into this. Also, can you try running `pem --force`?

Thanks!
