### ISSUE TITLE
`Helper.gem_path` is deprecated

### ISSUE THREAD

**Issue by hardikdevios** [fastlane/fastlane#6222]
`Helper.gem_path` is deprecated. Use the `ROOT` constant from the appropriate tool module instead.
How can i solve this ?

**Comment by KrauseFx** [comment]
Could you share the complete output when running fastlane? Do you call Helper.gem_path anywhere in your project?

**Comment by mfurtak** [comment]
Hi @hardikdevios - Sorry, we won't be able to help you without more information. Please follow the new issue template to give us information about your system and your setup. 👍

**Comment by hardikdevios** [comment]
Hey guys sorry for late i am closing this issue as my gem was old and need to update this solved my issue 👍

**Comment by KrauseFx** [comment]
Oh nice 👍

**Comment by Poliuk** [comment]
@hardikdevios can you share the gem you have to update?

**Comment by KrauseFx** [comment]
@Poliuk Make sure to update _fastlane_, which should update all other gems for you

**Comment by Poliuk** [comment]
I've updated fastlane but I'm still getting the 
`Helper.gem_path is deprecated. Use the ROOT constant from the appropriate tool module instead. ` error

**Comment by hardikdevios** [comment]
Ok Guys Sometime Updating _**fastlane**_ not update All gems (Don't know why @KrauseFx may help)
For this Issue Make sure you have Latest `fastlane_core` updated,

`gem install fastlane_core --verbose`

**Alternatively**, In future (To Avoid this kind of issues) if Any version not update with **_fastlane_** command
You can try 

`sudo gem update -- verbose `

**Comment by KrauseFx** [comment]
We actually built a new system to auto-update all dependencies from now on 👍

**Comment by hardikdevios** [comment]
@KrauseFx Well great to hear that, Any milestone for this feture or any wiki page if already done.

**Comment by KrauseFx** [comment]
@hardikdevios what do you mean? You can see the source code here https://github.com/fastlane/fastlane/pull/6326

**Comment by hardikdevios** [comment]
ok i thought you guys have apply some different update method  and we have to follow that but it looks like some under the hood changes so i hope we won't see any issue like "dependent gem won't getting updated with `gem update fastlane`"

**Comment by TKBurner** [comment]
@hardikdevios Thanks for following up. You should no longer see these problems. Let me know how it's going.

**Comment by hardikdevios** [comment]
@TKBurner Bro Great work i don't see any glitch so far. 
Cheers 🍻
