### ISSUE TITLE
"sigh download_all" and Profile naming

### ISSUE THREAD

**Issue by wasa1234** [fastlane/fastlane#6224]
Hi,

i updated sigh to version 1.11.0 and now all profiles are prefixed with "AppStore_" instead "AdHoc_". 

I use "sigh download_all".

Can anyone help me?

**Comment by rompic** [comment]
I have the same problem using sigh with adhoc:true (see the ticket I mentioned)

**Comment by KrauseFx** [comment]
We just pushed https://github.com/fastlane/fastlane/pull/6228, pushing a new release right now 🚀

**Comment by rompic** [comment]
+1 . works like a charm. thanks for the fast update.

**Comment by TKBurner** [comment]
@rompic Awesome! So glad to hear it worked for you!
