### ISSUE TITLE
Override lanes and call parent lane with parameters

### ISSUE THREAD

**Issue by iONsky** [fastlane/fastlane#6225]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Currently I'm using fastlane with a number of apps and the Fastfile configuration is always almost the same. The only major difference are the scheme and name of the project.

So I tried to put all the lane declarations in a shared Fastfile. But now the first problem arised: how to pass the scheme to the lanes? I solved that by passing it via command line parameter.
But I don't want to pass the scheme as a parameter every time I run fastlane.

I tried to override the lanes to call the parent lane from the shared Fastfile but that's not possible at the moment.

So I wanted to know if this feature is planned or if I should try to implement it and open a PR?

PS: I'm also open for other solutions to this problem

### Configuration Files

I thought of something like this:

Shared Fastfile:
```ruby
lane :integration do |options|
  gym(scheme: options[:scheme])
end
```

App Fastfile:
```ruby
override_lane :integration do
  super_integration(scheme: "App")
end
```

**Comment by KrauseFx** [comment]
Sorry, there is no way to call the parent lane, and we don't plan on adding this, as it adds a lot of complexity. There are various solutions, the easiest is probably to have a shared lane that is being called from other lanes.

**Comment by iONsky** [comment]
For some reason I didn't even thought of the idea to just name the parent lane different, make them private and call them from all other lanes. 😄
Thanks  👍
