### ISSUE TITLE
s3 action doesn't respect specified region

### ISSUE THREAD

**Issue by timgshi** [fastlane/fastlane#623]
in `self.upload_plist_and_html_to_s3`, the region specified in the s3 options isn't used. it's causing an error for my plist upload because I'm not using the default s3 region

**Comment by KrauseFx** [comment]
I don't have anything to test, but it should be okay to switch the following?

```ruby
s3_client = AWS::S3.new(
          access_key_id: s3_access_key,
          secret_access_key: s3_secret_access_key
        )
```
to
```ruby
        s3_client = AWS::S3.new(
          access_key_id: s3_access_key,
          secret_access_key: s3_secret_access_key,
          region: region
        )
```

**Comment by chinnawatp** [comment]
+1

**Comment by KrauseFx** [comment]
Fixed with https://github.com/fastlane/fastlane/pull/774
