### ISSUE TITLE
Disable gym to find relevant Github issues

### ISSUE THREAD

**Issue by DiogoLG** [fastlane/fastlane#6230]
### New Issue Checklist

- [x] Updated gym to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We are using `gym` to build our apps using Jenkins. Our CI servers can't access the internet due to security reasons. When a build fails gym trys to check if there are any issues in github. Is it possible to disable that feature?  

Although not critical it would make the log a little more readable.

```
09:45:07| ▸ Compiling schema.cpp
09:45:07| [09:55:30]: Exit status: 65
09:45:07| 
09:45:07| Looking for related GitHub issues on fastlane/fastlane...
09:45:07| 
09:45:07| **[09:55:31]: Error finding relevant GitHub issues: SSL_connect returned=1 errno=0 state=error: certificate verify failed**
09:45:07| 
09:45:07| [!] Error building the application - see the log above
```

### Environment

gym version (run `gym -v`): 
gym 1.6.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by TKBurner** [comment]
@DiogoLG Right now it's not possible. However, we'd love to see a PR to make this fail friendlier.

Thanks!

**Comment by KrauseFx** [comment]
You can use the `FASTLANE_HIDE_GITHUB_ISSUES` environment variable to disable looking for GitHub issues 👍
