### ISSUE TITLE
FastlaneCore::ProvisioningProfile.install(profile) fails on macOS 10.12

### ISSUE THREAD

**Issue by jshier** [fastlane/fastlane#6233]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Attempting to run `FastlaneCore::ProvisioningProfile.install(profile)` on macOS 10.12 results in an error for every profile attempted.

```
[13:38:22]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
```

This seems similar to [this issue](https://github.com/DanTheMan827/ios-app-signer/issues/19) and there is a workaround linked from that thread.
##### Complete output when running fastlane, including the stack trace and command used

```
fastlane installProfiles
[13:38:22]: -------------------------------------------------
[13:38:22]: --- Step: Verifying required fastlane version ---
[13:38:22]: -------------------------------------------------
[13:38:22]: fastlane version valid
[13:38:22]: ------------------------------
[13:38:22]: --- Step: default_platform ---
[13:38:22]: ------------------------------
[13:38:22]: Driving the lane 'installProfiles' 🚀
[13:38:22]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[13:38:22]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[13:38:22]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[13:38:22]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[13:38:23]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[13:38:23]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

[13:38:23]: fastlane.tools finished successfully 🎉
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
desc "Installs any provisioning profiles in $PROFILE_DIRECTORY, relative to fastlane's execution path."
lane :installProfiles do
  Dir.glob("#{ENV["PROFILE_DIRECTORY"]}/*.mobileprovision") do |profile|
    FastlaneCore::ProvisioningProfile.install(profile)
  end
end
```
### Environment

fastlane version (run `fastlane -v`): `fastlane 1.103.0`
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? `rvm`

**Comment by KrauseFx** [comment]
Did you find out how the command has changed in 10.12 and how we have to update _fastlane_?

**Comment by jshier** [comment]
Reading other bug reports about it it doesn't seem the command has changed but there's some sort of internal bug. There isn't anything new since the Sierra release yesterday.

**Comment by DenHeadless** [comment]
Guys, just trying to help with this issue. On my end this error happens several times:

```bash
[17:38:04]: Installing certificate...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.

....


[17:38:09]: [32mSuccessfully downloaded provisioning profile...[0m
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[17:38:09]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[Path to mobileprovision here]
[17:38:09]: Installing provisioning profile...
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
[17:38:09]: [32m🔒  Successfully encrypted certificates repo[0m
```

Gem versions used:
sigh 1.10.2
match 0.6.4
gym 1.9.0

Updating to more recent versions of sigh, match and gym does not help.

Build is successful, however sign does not seem to find match-stored provisioning profile, and does not seem to save a new one there.

**Comment by Lutzifer** [comment]
this is very similar to https://github.com/fastlane/fastlane/issues/5649

**Comment by TKBurner** [comment]
@DenHeadless @Lutzifer Can you share your fastfile? I want to share this with the core team. Thanks!

**Comment by steve-gray** [comment]
I'm hitting this:  the fastfile is literally just the default one, but I added match/sigh to the 'beta' lane. It appears to plough on regardless, but the first time I realised this was a problem was when later on it failed to create the archive due to the profiles....

The symlinking keychain thing doesn't appear to help either.

**Comment by steve-gray** [comment]
Other folks are hitting the same issue on Sierra:

- https://github.com/openbakery/gradle-xcodePlugin/issues/297
- https://github.com/maciekish/iReSign/issues/89

The grade plugin solution appears to have been just to ignore the error.

**Comment by DenHeadless** [comment]
@TKBurner All errors reported here are a result of match command:

```ruby
match(type: "appstore",force_for_new_devices: true)
```

Matchfile:

```ruby
git_url "[Redacted]"
type "development" # The default type, can be: appstore, adhoc or development
app_identifier "[Redacted]"
```

Our environment is macOS Sierra, Xcode 8.

**Comment by Lutzifer** [comment]
i digged a bit deeper:

- Provisioning Profile seems to now install correctly (i guess after the workaround "ln -s ~/Library/Keychains/login.keychain-db ~/Library/Keychains/login.keychain" from https://github.com/fastlane/fastlane/issues/5649)

- the error message is caused by

plist = Plist.parse_xml(`security cms -D -i "#{path}"`)

in provisioning_profile.rb

**Comment by KrauseFx** [comment]
Thanks @Lutzifer, this was really helpful, I summed this up in an issue https://github.com/fastlane/fastlane/issues/6387 and pushed a PR https://github.com/fastlane/fastlane/pull/6388 👍 

Looking into the Keychain issue now

**Comment by KrauseFx** [comment]
@steve-gray Ignoring the error is the only thing to do, right? Or how did https://github.com/maciekish/iReSign/issues/89 get resolved?
