### ISSUE TITLE
Use of unresolved Identifier 'setupSnapshot' 

### ISSUE THREAD

**Issue by tinder-ayu** [fastlane/fastlane#6235]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Seeing Use of unresolved Identifier 'setupSnapshot' when i compile
What i have done:
- add "SnapshotHelper2-3.swift" to project
- set SWIFT_VERSION in build settings to 2.3 from 3.0
- i add setupSnapshot(app) in setUp()
I'm using xcode 8, swift 2.3

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
@tinder-ayu Hope you are doing well! I was wondering if you can provide your full input and output? I'd love to take a look. Thanks!

**Comment by tinder-ayu** [comment]
@TKBurner what do you mean by input and output? 

setupSnapshot(app) in setUp() gives me unresolved identifier setupSnapshot.

**Comment by tinder-ayu** [comment]
Turns out it had to be individually enabled for each target. problem solved.
