### ISSUE TITLE
Actions `increment_version_number` and `commit_version_bump` have different behaviour for `xcodeproj` parameter

### ISSUE THREAD

**Issue by diogot** [fastlane/fastlane#6238]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Actions `increment_version_number` and `commit_version_bump` have different behaviour for `xcodeproj` parameter

[increment_version_number](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_version_number.rb#L18) accepts full path but [commit_version_bump](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/commit_version_bump.rb#L11) only accepts relative path.

Would be great to user full path for both.
### Environment

fastlane version (run `fastlane -v`):
`fastlane 1.103.0`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
`rbenv`

**Comment by TKBurner** [comment]
@diogot Would you be interested in submitting a PR to make both behaviors work on one of the actions? Thanks!

**Comment by diogot** [comment]
Yes, I'll do something and let you know

**Comment by KrauseFx** [comment]
Nice catch @diogot, this should be an easy fix, please let me know if you need any help 👍

**Comment by diogot** [comment]
I did a fix but don't know to write a test for it.
By the way this class has no test at all.

**Comment by KrauseFx** [comment]
Don't worry about the tests, some actions don't have any currently
