### ISSUE TITLE
Unsolved conflict between options: 'apk_paths' and 'apk'

### ISSUE THREAD

**Issue by gagaJay** [fastlane/fastlane#6240]
### Issue Description

Hi, I have a few questions about apk_path parameter. apprecated if you can answer them. cheers!
1. what is the correct format of inputing 'apk_paths'? is it something like: 
apk_paths: ["/app/build/outputs/apk/app-release-unaligned.apk", "/app/build/outputs/apk/app-release-unaligned.apk"] ?
2. Is it not allowed to manually set parameters for 'apk_paths' and 'apk' at the same time? I guess that might be the reason causing the conflict as mentioned in the title. But there is a weird case that when i run 'supply' without giving any parameters, the apk_paths is filled with a default value, and it upload the data to play store successfully. don't know why?
+-------------------------+------------------------------------------------------------------------+
|                                     Summary for supply 0.7.1                                     |
+-------------------------+------------------------------------------------------------------------+
| package_name            | com.***.supplydemo                                           |
| track                   | alpha                                                                  |
| metadata_path           | /***/SupplyDemo/fastlane/metadata/android             |
| json_key                | /***/SupplyDemo/key.json                              |
| apk_paths               | ["/app/build/outputs/apk/app-debug.apk |
| rollout                 | 1.0                                                                    |
| apk                     | app/build/outputs/apk/app-Release.apk                                  |
| skip_upload_apk         | false                                                                  |
| skip_upload_metadata    | false                                                                  |
| skip_upload_images      | false                                                                  |
| skip_upload_screenshots | false                                                                  |
+-------------------------+------------------------------------------------------------------------+

##### Complete output when running fastlane, including the stack trace and command used

[10:40:45]: --------------------
[10:40:45]: --- Step: supply ---
[10:40:45]: --------------------
[10:40:47]: You passed invalid parameters to 'supply'.
[10:40:47]: Check out the error below and available options by running `fastlane action supply`
[10:40:47]: Variable Dump:
[10:40:47]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android alpha", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/phuang/GitRepo/SupplyDemo/app/build/outputs/apk/app-release.apk"], :GRADLE_APK_OUTPUT_PATH=>"/Users/phuang/GitRepo/SupplyDemo/app/build/outputs/apk/app-release.apk"}
[10:40:47]: Unresolved conflict between options: 'apk_paths' and 'apk'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 2           |
| 4    | gradle                              | 18          |
| 5    | supply                              | 2           |
+------+-------------------------------------+-------------+

[10:40:47]: fastlane finished with errors

[!] Unresolved conflict between options: 'apk_paths' and 'apk'

### Configuration Files

Fastfile:
```ruby
# INSERT CONTENT HERE
lane :alpha do
    gradle(task: "clean")
    gradle(task: "assembleRelease")
    supply(package_name: "com.***.***.supplydemo",
           track: "alpha",
           metadata_path: "/***/SupplyDemo/fastlane/metadata/android",
           json_key: "/***/SupplyDemo/key.json",
           apk_paths: ["***/SupplyDemo/app/build/outputs/apk/app-release-unaligned.apk"],
           apk: "/***/SupplyDemo/app/build/outputs/apk/app-Release.apk")

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

### Environment

fastlane version (run `fastlane -v`): fastlane 1.102.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by asfalcone** [comment]
@gagaJay Thanks for the questions.

The array format is correct for `apk_paths`.

You cannot specify both as params. If you have `apk_paths` from an environment variable (`GRADLE_ALL_APK_OUTPUT_PATHS` iss set because you ran `gradle` prior to supply) it will use that over the `apk` param.

Hope this helps. 👍

**Comment by gagaJay** [comment]
thanks for clarification!

**Comment by asfalcone** [comment]
👍
