### ISSUE TITLE
Use match without recreating certificate and provision profiles ?

### ISSUE THREAD

**Issue by donnib** [fastlane/fastlane#6241]
Is it possible to use Match without creating new provision profiles and new certificates ? I mean we already have all that in place but i'd like to use Match to put all stuff in git and be able to distribute it to developers. I am afraid of running the command to find out it have re-created everything. That will not be popular.

**Comment by Lutzifer** [comment]
see http://stackoverflow.com/questions/36963467/how-do-i-manually-add-existing-provisioning-profiles-and-certificates-to-fastlan/37057325?noredirect=1#comment64759957_37057325

**Comment by TKBurner** [comment]
@Lutzifer Thanks for stepping in here 👍 👍
