### ISSUE TITLE
[Action] Action to toggle the "Automatically manage signing" flag of Xcode 8

### ISSUE THREAD

**Issue by mathiasAichinger** [fastlane/fastlane#6244]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
To use "Automatically manage signing" during development, I need an action to disable this flag on the build server

**Comment by mathiasAichinger** [comment]
Realized that Actions are not accepted ATM. Need to rewrite it as a Plugin.
https://github.com/mathiasAichinger/fastlane/tree/update-project-automatic-codesigning-action

**Comment by hjanuschka** [comment]
thx @mathiasAichinger  i put those in my fastlane/actions folder (loaded with `import_from_git`) many thx!

**Comment by KrauseFx** [comment]
I love the idea @mathiasAichinger, please provide this as a plugin and let me know once it's live. We still accept new actions, but only if they existed as plugins first and are actively used by multiple companies already. This way we make sure to only include actions that are useful for a majority of our user base 👍

**Comment by hjanuschka** [comment]
as we are using it inhouse, as a custom action, but i think there are way more people needing this.
i did the plugin, based on your code, left the author intact!

https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning

feel free to join and PR - i could also transfer the repo to your username, or we do a n fastlane-contrib org?

@mathiasAichinger @KrauseFx

**Comment by mathiasAichinger** [comment]
@hjanuschka Cool 🎉 Unfortunately I haven't got time to implement the plugin, so it's great that you did it in the meanwhile :)

**Comment by hjanuschka** [comment]
@mathiasAichinger  can we close this issue?

**Comment by KrauseFx** [comment]
Yeah, thanks @hjanuschka 👍
