### ISSUE TITLE
IPA not signed with Ad Hoc profile

### ISSUE THREAD

**Issue by jvanzummeren** [fastlane/fastlane#625]
I'm trying to use Fastlane to distribute builds to Crashlytics. It's sending the .ipa succesfully to Crashlytics, but it keeps getting signed with an Appstore provisioning profile instead of Ad Hoc. I'm not sure wether this is a bug or if i'm doing something wrong. It does download the Ad Hoc profile correctly, but doesn't seem to be using it to sign the ipa.
This is the script i'm running:
```
    sigh(adhoc:true)
    gym
    crashlytics({
       crashlytics_path: "XXX",
       api_token: "XXX",
       build_secret: "XXX",
    })
```
I can get it to work by adding "resign" with a specific provisioning profile, but i doubt this is the right way to do it. 

Thanks!

**Comment by KrauseFx** [comment]
Could you try to use the following command for `gym`:

```ruby
gym(export_method: 'ad-hoc')
```

This will make sure you app gets signed as Ad Hoc app

**Comment by KrauseFx** [comment]
Also, I pushed this update https://github.com/KrauseFx/fastlane/releases/tag/1.29.1
This should now work automatically :+1:

**Comment by jvanzummeren** [comment]
Cool, both solutions work perfectly! Thanks!
The only issue i still have is "400 Bad request" when generating a Ad Hoc profile when it doesn't exist yet. I guess this is related to #349. Is this an unresolved vague issue?

**Comment by KrauseFx** [comment]
Great! :+1: 
The other issue you mentioned has something to do with your internet connection.

**Comment by pronebird** [comment]
`export_method` does not seem to work with gym if you pass `configuration` option.

`sigh(adhoc:true)` solves this for me.

**Comment by KrauseFx** [comment]
I'll close this issue for now :+1:
