### ISSUE TITLE
Pilot: How can I share the build with beta testers? Without submitting for review?

### ISSUE THREAD

**Issue by muzammil-triffort** [fastlane/fastlane#6263]
Whenever I am trying to use Pilot to share the build with beta tester, It also submitted for review and I get the message from iTunes regarding my app issues. I am not sure is this issue of my app or something wrong with my Pilot lane. I am following this code inside beta lane:

```
pilot
    {
      distribute_external:false,
      skip_submission:true,
      skip_waiting_for_build_processing:true
    }
```

**Comment by TKBurner** [comment]
@muzammil-triffort Does this happen if you manually distribute the build on testflight? Thanks!

**Comment by muzammil-triffort** [comment]
I did't checked that, but I will do and let you know. Thank you in advance.

**Comment by TKBurner** [comment]
@muzammil-triffort Were you able to get up and running? Thanks!

**Comment by muzammil-triffort** [comment]
@TKBurner Thank you for your help. I fixed the issue, it was due to using KIF in my project.

**Comment by muzammil-triffort** [comment]
If anyone unable to distribute build with test users, use this command:

`pilot(distribute_external: true, skip_waiting_for_build_processing:true, skip_submission:false, changelog: changelog)`

where changelog can be define as:

` changelog = prompt(text: "What is new in this version?: ", multi_line_end_keyword: "END")
`
