### ISSUE TITLE
runner.rb seems to be chdir'ing once extra in a rescue clause, causing a less meaningful exception

### ISSUE THREAD

**Issue by owurman** [fastlane/fastlane#6264]
runner.rb recovers from an error in a clause which does a chdir into the fastlane folder by chdir'ing into the fastlane folder yet again. This is causing a backtrace that says "No such file or directory - {fastlane folder}" when that's not actually true, and thus masking the real issue. I suggest removing the Dir.chdir(path_to_use) wrapper block from the rescue clause starting on runner.rb:59.

With the clause, I see this:

```
    /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:59:in `chdir': [!] No such file or directory - ./fastlane/ (Errno::ENOENT)
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:59:in `rescue in execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/runner.rb:44:in `execute'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/command_line_handler.rb:30:in `handle'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:246:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/commands_generator.rb:20:in `start'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
    from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
    from /usr/local/bin/fastlane:23:in `load'
    from /usr/local/bin/fastlane:23:in `<main>'
```

This is untrue as ./fastlane/ does actually exist.

If I remove it, I get the much more meaningful (real) exception:

```
    /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/configuration/configuration_file.rb:24:in `eval': [!] No such file or directory - fastlane/Config (Errno::ENOENT)
```

Although fastlane/Config does exist, my pwd at this point is ./fastlane/, and ./fastlane/fastlane/Config does NOT exist.

This is all strange because it worked a week ago, but that's a different issue altogether (that fastlane seems to switch the concept of pwd on me periodically, but I'm not entirely sure that's a fastlane bug yet and not somehow the fault of my configuration).

**Comment by KrauseFx** [comment]
Thanks for the report, this is a little tricky. What's the best way to reproduce this error?

**Comment by owurman** [comment]
@KrauseFx In my case, I have a fastlane subdirectory with a Snapfile and a Config file:

Snapfile (the version with the error)
```
print "Snapfile pwd: " + FileUtils.pwd() + "\n"
content = File.read("fastlane/Config")
eval(content)

content = File.read("../../fastlane/Snapfile")
eval(content)

# The name of the project's scheme
scheme ENV["SCHEME"]
```

Config
```
ENV["SCHEME"] ||= "LifeMed Alaska"
ENV["APP_NAME"] ||= "LifeMed Alaska"
ENV["BUNDLE_ID"] ||= "com.acidremap.PPPLifeMedAlaska"
ENV["SNAPSHOT_PROTOCOL_INDEX"] ||= "3"
```

The real error (my error) was that Snapfile pwd is the fastlane subdir itself, so I had to fix the two paths to:
content = File.read("Config")
content = File.read("../../../fastlane/Snapfile")

As mentioned, this is odd, because this very setup worked last week. I upgraded to Xcode 8 and fastlane 1.104.0, either of which might have changed the behavior of pwd, but I tried downgrading to fastlane 1.100.0 for comparison and it still had the same issue, so I'm not sure what changed.

**Comment by owurman** [comment]
In case it matters, my ./fastlane/Fastfile:
```
content = File.read("Config")
eval(content)

content = File.read("../../../fastlane/Fastfile")
eval(content)
```

And the master Fastfile (at ../../../fastlane/Fastfile)
```
...
  lane :snapshot_lane do
    prepare_UITest_target("../../../ParamedicProtocolProvider.xcodeproj", "../../../test.xcodeproj", ENV["SCHEME"])
    if Dir.exist?("../screenshots/") then
      FileUtils.rm_r "../screenshots/"
    end
    snapshot(project: "../../../test.xcodeproj", scheme:ENV["SCHEME"])
    system('say \"done with snapshot\"')
  end
...
```

The prepare_UITest_target() bit is my workaround to having the save snapshot XCUI test run on different flavors of the app (I have over 50).

**Comment by TKBurner** [comment]
@owurman Any chance you can supply a sample project that is affected? Thanks!

**Comment by owurman** [comment]
OK, so in trying to create you a sample project, I found that Ruby's concept is pwd (present working directory) is changed by the xcodeproj gem's Project.save(). This is what's causing this to appear as a bug. So, it's very specific to my setup, because I'm doing project-munging. It's probably more accurately a bug in xcodeproj. You can close this.

**Comment by owurman** [comment]
Although, https://www.dropbox.com/s/nmq09gajzbrl42i/test.tgz?dl=0 if you are curious. run `fastlane snapshot_lane` from Custom/Flavor/

**Comment by TKBurner** [comment]
@owurman Thanks so much! Glad to hear you got up and running. What do you think about your setup caused this?

**Comment by owurman** [comment]
Not sure why, but seems to be from calling xcodeproj::Project.save()

If you want to keep it open for now I can post what I find out from more investigation. I've switched gears for a moment (setting up Boarding for TestFlight).

**Comment by TKBurner** [comment]
@owurman Sounds good! I'll leave this open for now and you can update once you have more information. Hope you have a great weekend coming up! 👍
