### ISSUE TITLE
Feature request: add support for iCloud Sandbox testers

### ISSUE THREAD

**Issue by jflinter** [fastlane/fastlane#6271]
🔑

iCloud Sandbox users are a less-commonly-used type of iTunes Connect account that Fastlane doesn't currently support. They're useful for testing In-App Purchase and Apple Pay (for example, logging in with one on an iOS device lets you use the [Apple Pay Sandbox](https://developer.apple.com/support/apple-pay-sandbox/). iTunes connect appears to only have APIs to list, create, and delete them (they're immutable once they're made).

One important caveat is that after creating a sandbox user, Apple sends that email a verification email with a link that must be clicked. This is fine for our use case, but makes this API less broadly useful.

I have a PR that implements creating and listing open here: https://github.com/fastlane/fastlane/pull/6258

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

**Comment by KrauseFx** [comment]
Thanks again, done with https://github.com/fastlane/fastlane/pull/6258
