### ISSUE TITLE
scan running tests multiple times

### ISSUE THREAD

**Issue by reidmain** [fastlane/fastlane#6274]
### New Issue Checklist
- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

On my CI boxes scan appears to be running the tests multiple times.

I have a setup script that ensures the build environment is in the correct state for the tests to pass so when they are again they will undoubtably fail.
##### Complete output when running fastlane, including the stack trace and command used

The output is quite verbose but the key part is the following:

```
18:08:06 ▸ Test Succeeded
18:08:06 2016-09-23 11:02:58.571 xcodebuild[4894:738062] [MT] IDETestOperationsObserverDebug: (D15BB9C8-F85B-45D2-8C55-EC6589E66648) Beginning test session D15BB9C8-F85B-45D2-8C55-EC6589E66648 with Xcode 7D175 on target <DVTiPhoneSimulator: 0x7fb21c2c0020> {
18:08:06 SimDevice: SimDevice : iPhone 6s (14DA8B6F-6AB6-455E-ADEC-9D671BF496AF) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-6s } runtime={ SimRuntime : 9.3 (13E230) - com.apple.CoreSimulator.SimRuntime.iOS-9-3 }
18:08:06 } (9.3 (13E230))
18:08:06 2016-09-23 11:02:58.572 xcodebuild[4894:740035]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
18:08:06 /usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Reid-fiwowsroopmhmiexhhfwiqpktfjj/Logs/Test/92FCFE09-8BFC-426F-870B-94C407FAE544/Session-2016-09-23_11:02:58-RJstOb.log
```

When I run it locally the output is:

```
17:47:48 [10:47:48]: ▸ Test Succeeded
17:47:49 +--------------------+-------+
17:47:49 |        Test Results        |
17:47:49 +--------------------+-------+
17:47:49 | Number of tests    | 11    |
17:47:49 | Number of failures | 0     |
17:47:49 +--------------------+-------+
```

For some reason the second the tests fail the Simulator goes into some sort of shutdown state and immediately restarts and causes all the tests to run a second time.
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
lane :test do
      clear_derived_data
      sh "./resetSimulators.sh"

      scan(scheme: "Reid Tests",
           project: "Reid.xcodeproj",
           clean: true,
           device: "iPhone 6s (9.3)",
       )
end
```
### Environment

**fastlane version:**
1.103.0

**Do you use bundler to execute fastlane?**
No

**Do you use a Ruby environment manager?**
Yes, rbenv

**Comment by reidmain** [comment]
I figured out why. I specify `iphone 6s (9.3)` for my device to scan but apparently that build server has multiple iPhone 6s 9.3 simulators. Scan then runs on every one of them.

It feels like scan should only run on the first simulator it finds that matches the pattern?

**Comment by TKBurner** [comment]
@reidmain Great suggestion! Why do you have multiple iPhone 6s 9.3 simulators? Just want to see why this is a good use case. Thanks!

**Comment by reidmain** [comment]
@TKBurner the weirdest thing is I have absolutely no idea how it happened. These are Mac Minis setup strictly for CI so people are rarely doing anything manually to them. My only thought was that we use the `xcrun simctl erase` command to reset our simulators before launching our build job and maybe if one of the simulators was in the incorrect state something happened. That or perhaps updating to later version of Xcode caused it when it was updating the developer tools.

Regardless, my solution was to take all of the boxes offline, run `snapshot reset_simulators` and bring the back online and everything started working perfectly.

**Comment by TKBurner** [comment]
@reidmain Nice! That sounds like a viable solution. I think you can also provide the UDID after the simulator name.

**Comment by reidmain** [comment]
@TKBurner there would be no way to ensure the simulators across all of our CI boxes have the same UUID so it wouldn't scale.

Should this issue be kept open, or another one opened, so that scan by default doesn't use multiple simulators if they somehow exist? It would make sense to me to run multiple times if you explicitly provided the names of multiple devices but in my mind if you only provide one I would expect it would only run once.

**Comment by TKBurner** [comment]
@reidmain Would you be interested in submitting a PR to correct this behavior? I'm sending this out to the core team as well. Hope you have a great day!

**Comment by reidmain** [comment]
@TKBurner unfortunately I don't think my Ruby skills are in a place where I could contribute effectively.

**Comment by TKBurner** [comment]
@reidmain No problem! Thanks for using _fastlane_!
