### ISSUE TITLE
update_app_identifier and update_project_provisioning both change current directory, but do not change back when done

### ISSUE THREAD

**Issue by klundberg** [fastlane/fastlane#6278]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If you run the `update_app_identifier` or the `update_project_provisioning` action, they change directories from `${SRCROOT}/fastlane` to `${SRCROOT}`, but they never change back when they are done. This causes other code that looks for files in a specific path to always fail to find the file, and fastlane fails at that point. We run fastlane on multiple apps at once in a loop, so we're running these actions multiple times per lane execution. This only started happening recently, somewhere between fastlane 1.101 and 1.104.

##### Complete output when running fastlane, including the stack trace and command used

```
Prefer not to include, as it's sensitive. See example lane instead that reproduces issue
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  # lane that reproduces issue:
  lane :bug do
      puts File.absolute_path(".")
      # first time it's ${SRCROOT}/fastlane, second time it's ${SRCROOT}.
      # It should always be one or the other (preferrably the first as that's how it worked before).

      # replace with your own project info
      proj = 'WayfairApp.xcodeproj'
      plist = 'WayfairApp/Info.plist'
      identifier = 'com.wayfair.WayfairApp'
      target_pattern = '^WayfairApp$'

      # problem action 1
      update_app_identifier(xcodeproj: proj,
                            plist_path: plist,
                            app_identifier: identifier)
      # problem action 2
      cert
      sigh(app_identifier: identifier)
      update_project_provisioning(xcodeproj: proj,
                                  target_filter: target_pattern)

      puts File.absolute_path(".")
  end
```

### Environment

fastlane version (run `fastlane -v`): fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv, but happens on machines without it

**Comment by klundberg** [comment]
@fastlane-bot nope, not this time!

**Comment by klundberg** [comment]
This could also be a bug in xcodeproj, since both of these actions use that, but i'm not certain yet.

**Comment by klundberg** [comment]
Might be related to this too: https://github.com/CocoaPods/Xcodeproj/pull/404

**Comment by TKBurner** [comment]
@klundberg Can you share your full input and output from one of these errors? I want to check it out. Thanks!

**Comment by klundberg** [comment]
Sure, here's the output with the problem lines with a slightly tweaked lane, which i'll edit in the original comment. The first path is printed before anything happens, and the last path is printed at the end before the summary, where it changes when it shouldn't):

```sh
$ fastlane bug
[14:17:20]: -------------------------------------------------
[14:17:20]: --- Step: Verifying required fastlane version ---
[14:17:20]: -------------------------------------------------
[14:17:20]: fastlane version valid
[14:17:20]: ------------------------------
[14:17:20]: --- Step: default_platform ---
[14:17:20]: ------------------------------
[14:17:20]: Driving the lane 'ios bug' 🚀
[14:17:20]: /Users/klundberg/workspaces/wayfair-ios/fastlane
[14:17:20]: -----------------------------------
[14:17:20]: --- Step: update_app_identifier ---
[14:17:20]: -----------------------------------
[14:17:24]: Updated WayfairApp.xcodeproj 💾.
[14:17:24]: ------------------
[14:17:24]: --- Step: cert ---
[14:17:24]: ------------------

+---------------+---------------------------------------------------+
|                      Summary for cert 1.4.2                       |
+---------------+---------------------------------------------------+
| development   | false                                             |
| force         | false                                             |
| username      | (redacted)                                        |
| keychain_path | /Users/klundberg/Library/Keychains/login.keychain |
+---------------+---------------------------------------------------+

[14:17:24]: Starting login with user 'redacted'
[14:17:26]: Successfully logged in
[14:17:27]: Found the certificate (redacted) which is installed on the local machine. Using this one.
[14:17:28]: Verifying the certificate is properly installed locally...
[14:17:28]: Successfully installed certificate (redacted)
[14:17:28]: Use signing certificate '(redacted)' from now on!
[14:17:28]: ------------------
[14:17:28]: --- Step: sigh ---
[14:17:28]: ------------------

+-------------------------------------+------------------------+
|                   Summary for sigh 1.11.1                    |
+-------------------------------------+------------------------+
| app_identifier                      | com.wayfair.WayfairApp |
| adhoc                               | false                  |
| development                         | false                  |
| skip_install                        | false                  |
| force                               | false                  |
| username                            | (redacted)             |
| ignore_profiles_with_different_name | false                  |
| cert_id                             | (redacted)             |
| skip_fetch_profiles                 | false                  |
| skip_certificate_verification       | false                  |
+-------------------------------------+------------------------+

[14:17:28]: Starting login with user '(redacted)'
[14:17:29]: Successfully logged in
[14:17:29]: Fetching profiles...
[14:17:29]: Provisioning Profile 'com.wayfair.WayfairApp AppStore' is not valid, skipping this one...
[14:17:29]: Provisioning Profile 'com.wayfair.WayfairApp AdHoc' is not valid, skipping this one...
[14:17:31]: Found 1 matching profile(s)
[14:17:31]: Downloading provisioning profile...
[14:17:32]: Successfully downloaded provisioning profile...
[14:17:32]: Installing provisioning profile...
/Users/klundberg/workspaces/wayfair-ios/AppStore_com.wayfair.WayfairApp.mobileprovision
[14:17:32]: Setting Provisioning Profile type to 'app-store'
[14:17:32]: -----------------------------------------
[14:17:32]: --- Step: update_project_provisioning ---
[14:17:32]: -----------------------------------------
[14:17:32]: You’re updating provisioning profiles directly in your project, but have you considered easier ways to do code signing?
[14:17:32]: https://github.com/fastlane/fastlane/tree/master/fastlane/docs/Codesigning
[14:17:32]: Parsing mobile provisioning profile from '/Users/klundberg/workspaces/wayfair-ios/AppStore_com.wayfair.WayfairApp.mobileprovision'
[14:17:33]: Going to update project 'WayfairApp.xcodeproj' with UUID
[14:17:34]: Updating target WayfairApp...
[14:17:34]: Updating configuration Debug...
[14:17:34]: Updating configuration Release...
[14:17:36]: Successfully updated project settings in'WayfairApp.xcodeproj'
[14:17:36]: /Users/klundberg/workspaces/wayfair-ios

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | update_app_identifier               | 3           |
| 4    | cert                                | 3           |
| 5    | sigh                                | 4           |
| 6    | update_project_provisioning         | 3           |
+------+-------------------------------------+-------------+

[14:17:36]: fastlane.tools finished successfully 🎉
```

**Comment by TKBurner** [comment]
@klundberg Thanks for following up. Any chance you'd be interested in submitting a PR? I've reached out to the core team about this as well. Thanks!

**Comment by klundberg** [comment]
I'm not sure what the exact problem here is, if it's related to that XcodeProj bug or not. I can't say whether or not I'll have any time to investigate this in the near future.

**Comment by TKBurner** [comment]
@klundberg Does this only occur when you run from the fastlane directory? What happens if you run from the project directory? Thanks!

**Comment by klundberg** [comment]
I never run from the fastlane directory, always from the base project directory. For some reason the current directory for the sh action has been the fastlane subdirectory, which is what my scripts have relied on.

--
Kevin Lundberg

**Comment by klundberg** [comment]
with fastlane 1.105 this seems to be worse. now in my fastfile, if i first call `update_app_identifier` and then call `update_project_team` (while providing a path to the project for each), the second one fails since it can't find the project at a relative path name. for example:

```ruby
update_app_identifier(xcodeproj: "myproj.xcodeproj", 
  plist_path: "myproj/Info.plist",
  app_identifier: "com.example.myproj")

# fails here since it can't find myproj.xcodeproj wherever it happens to be looking.
update_project_team(path: "myproj.xcodeproj", 
  teamid: "12345") 
```

**Comment by TKBurner** [comment]
@klundberg Can you add the --verbose flag and send over the full input and output? I want to run the xcodeproj commands directly and see if they cause the issue. Really want to get to the bottom of this. Thanks!

**Comment by mfurtak** [comment]
Hi @klundberg - thanks for the report 👍  

We were [seeing some other problems](https://github.com/fastlane/fastlane/issues/6330#issuecomment-253077262) related to directory changing where `xcodeproj` was involved. As noted there, can you see if it is still a problem after updating to `xcodeproj` 1.3.2?

```
gem update xcodeproj
```

Thanks!

**Comment by quenbob** [comment]
I've been experiencing an issue with xcodeproj 1.3.2 and fastlane 1.105.2 when calling the update_app_identifier action.

I'm calling the following actions 

    update_project_team()
    update_app_identifier()
    update_info_plist()
    gym()

And I get following error message with update_info_plist()

Error setting value '*****.xcodeproj' for option 'xcodeproj'
You passed invalid parameters to 'update_info_plist'.
Check out the error below and available options by running `fastlane action update_info_plist`

if I switch the order of the actions to

   update_info_plist() 
   update_project_team()
    update_app_identifier()
    gym()

update_info_plist works however now I get a warning with the gym

Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
Couldn't automatically detect the project file, please provide a path:

I tried with bundle and without the results are the same.

I had not experienced this issue before when building on Xcode 7 with an older version of fastlane. I've recently updated Xcode to 8 and updated fastlane to 1.105.2 in order to get the fixes.

I hope this might help.

**Comment by quenbob** [comment]
Note: I also tested by removing the update_app_identifier and the gym started to compile the project.

**Comment by mfurtak** [comment]
I'm reproducing this locally now, and I think I see what @klundberg was saying. `xcodeproj` **1.3.2** exhibits this problem for me, but **1.3.1** does not.

@quenbob - if you do:
```
gem uninstall xcodeproj
gem install xcodeproj -v 1.3.1
```

Do things start to work?

**Comment by klundberg** [comment]
Xcodeproj 1.3.1 fixes the later issue I've seen where the actions themselves fail, but the original bug encountered by running the lane I added is still an issue. Before either action is run, ruby reports the current directory as `myProjectPath/fastlane`, but after either runs (which goes thru xcodeproj), the current directory is `myProjectPath` which breaks later assumptions in my fastfile that held before those actions ran.

I was able to get the expected behavior by reverting down to Xcodeproj 1.1.0 (Dir.curdir is the same before and after the lane runs). However we cannot depend on that, since we also pin cocoapods to 1.1.0.rc.2 in our Gemfile, which requires Xcodeproj 1.3.1 or greater.

Both this original bug in xcodeproj 1.2.0 and the newer one in 1.3.2 seem like they need to be fixed in that gem. I don't know if I'll have time to narrow down the issue to something reproducible only with xcodeproj though to make a useful bug report over there though.

**Comment by jshier** [comment]
I've been seeing this and was able to workaround it by resetting the various paths using `File.expand_path`. i.e. `ENV["GYM_WORKSPACE"] = File.expand_path("Project.xcworkspace")`.

**Comment by mfurtak** [comment]
Hi all,

The CocoaPods folks are tracking this problem and trying to work around it in [Xcodeproj](https://github.com/CocoaPods/Xcodeproj).

As noted here: https://github.com/CocoaPods/Xcodeproj/issues/426#issuecomment-251804075 please see if upgrading to `xcodeproj` 1.3.2 and then using the ENV variable `FORK_XCODE_WRITING=true` when running fastlane gets things working again in the short term.

```
gem update xcodeproj
FORK_XCODE_WRITING=true fastlane your_lane
```

Thanks!

**Comment by klundberg** [comment]
great, thank you for the update and the related bug @mfurtak! This works for me and solves the original bug that I encountered.
