### ISSUE TITLE
[gym] Issues found after uploading build to iTunes Connect with legacy build api

### ISSUE THREAD

**Issue by nafu** [fastlane/fastlane#6282]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I uploaded build to iTunes Connect **with legacy build api**.
I got the email below from iTunes Connect.

Note using legacy build api with Xcode 8 GM:
1. Does not work with Swift 2.3 at least (I didn't try with Swift 3.0 projects).
2. Does not work with WatchKit Target.

It works **without legacy build api**.
#### Full Email from iTunes Connect

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "Player! - Enjoy Live Games". To process your delivery, the following issues must be corrected:
> 
> **Invalid WatchKit Support** - The expected app is missing from the app’s root location, such as ${expectedLocation}.
> 
> **Invalid WatchKit Support** - The WatchKitSupport2 folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
> 
> **Invalid Swift Support** - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team
##### Complete output when running fastlane, including the stack trace and command used

```
$ bundle exec fastlane beta
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do |options|
    match(type: "appstore", app_identifier: "#{APP_IDENTIFIER}", readonly: true)
    match(type: "appstore", app_identifier: "#{APP_IDENTIFIER}.NotificationService", readonly: true)
    match(type: "appstore", app_identifier: "#{APP_IDENTIFIER}.watchkitapp", readonly: true)
    match(type: "appstore", app_identifier: "#{APP_IDENTIFIER}.watchkitapp.watchkitextension", readonly: true)

    gym(
      workspace: WORKSPACE,
      scheme: SCHEME,
      toolchain: "com.apple.dt.toolchain.Swift_2_3",
      configuration: "Release",
      use_legacy_build_api: true
    )

    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )

    slack(
      message: "#{read_version} will be pre-released soon!"
    )
  end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0 72119273bda23dacc8b07abe67b407c9c48fd36b

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No on CI.

**Comment by TKBurner** [comment]
@nafu Hope you are doing well! Thanks for submitting this. Do you think we need to update our error messaging around this? Do you think you'd be interested in submitting a PR? Thanks!

**Comment by nafu** [comment]
@TKBurner 

Thanks for the comment.

> Do you think we need to update our error messaging around this?

Yes. It's not good for fastlane users that they notice this kind of errors after uploading builds iTunes Connect.
If builds with legacy build api aren't accepted totally on iTunes Connect, failing the build make sense.

> Do you think you'd be interested in submitting a PR?

Sure.

**Comment by TKBurner** [comment]
@nafu Awesome! I really appreciate it 👍 Hope you have a great day!

**Comment by nafu** [comment]
Not yet, but I think this is ignorable because Xcode 8.2 is the last release that will support Swift 2.3.
I'm gonna close this, thanks.

**Comment by brandonroeder** [comment]
I'm still having this issue, is there not a workaround? I cannot build without the 'use_legacy_build_api' flag but I need watchkit support.

**Comment by KrauseFx** [comment]
@brandonroeder Please don't use the legacy build API. If it doesn't work, please submit a new issue so we can help you resolve it 👍

**Comment by brandonroeder** [comment]
@KrauseFx Will do!

**Comment by rlam3** [comment]
I've been running to a similar issue through my email.... Everything builds fine and uploads fine. Until I get the following email message from Apple saying:

**Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.**

```bash
$ /usr/bin/xcodebuild -version
Xcode 8.2.1
Build version 8C1002
```

```bash
$ swift --version
Apple Swift version 3.0.2 (swiftlang-800.0.63 clang-800.0.42.1)
Target: x86_64-apple-macosx10.9
```
Fastlane Env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.1 (Apple Git-78)               |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                      |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.2.1                                           |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.3.0"

default_platform :ios

platform :ios do

  ############################## PRE ##############################


  before_all do

    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    increment_build_number
    cocoapods
    
  end

  ######################### PUBLIC LANES ##########################

  desc "Runs all the tests"
  lane :test do
    scan
  end


  desc "Publish to TestFlight"
  private_lane :publish_testflight do
    # Generate a changelog with GIT since the last successful build in Jenkins
    changelog = sh("git log --graph --pretty=format:'%h -%d %s <%an>' --abbrev-commit #{ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || 'HEAD^^^^^'}..HEAD")

    testflight(
      skip_waiting_for_build_processing: true,
      changelog: "Trying Testflight...",
    )

    # Send the app to Testflight
    pilot(
      changelog: "#{changelog.to_s}"
    )
  end

  desc "Publish to Crashlytics Beta"
  private_lane :publish_crashlytics do |values|

    emails = values[:test_email] ? values[:test_email] : ['raymond.lam@midori.io'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'b20ca92d606bfcecb208cdf41ff30a6ff18d21fa',
             build_secret: '2599baab467c4e6650dd7bc8edb5c0f081b2b57b7ae45bb5cb6fa926765819cd',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane. Export Method: ad-hoc... with match adhoc', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

  end

  desc "Publish to HockeyApp"
  private_lane :publish_hockeyapp do
    hockey(api_token: "497a19ad245e44dca899ee157adc0ee0")
  end

  desc "Publish to Appstore"
  private_lane :publish_appstore do |values|
    deliver(force: true)
  end

  lane :build do
    gym(scheme: "fastLaneFun2", workspace:"fastLaneFun2.xcworkspace",export_method:"adhoc") # Build your app - more options available
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |values|
    match(type: "adhoc") # more information: https://codesigning.guide
    gym(
      clean: true,
      scheme: "fastLaneFun2", 
      workspace: "fastLaneFun2.xcworkspace",
      export_method: "ad-hoc",
      configuration: "Release",
      use_legacy_build_api: true,
      # tool_chain: "3.0.2"
    ) # Build your app - more options available

    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      changelog: "Trying Testflight...",
      # skip_submissio: true,
    )

    # testflight(
    #   skip_waiting_for_build_processing: true,
    #   changelog: "Trying Testflight...")
    # )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "fastLaneFun2") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.fastLaneFun2" # The bundle identifier of your app
apple_id "raymondlam1991@gmail.com" # Your Apple email address

team_id "64P9F2VDC8"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.3.0   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>


*generated on:* **2016-12-31**
</details>



# Fastfile

```ruby

  before_all do

    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    increment_build_number
    cocoapods
    
  end

desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |values|
    match(type: "adhoc") # more information: https://codesigning.guide
    gym(
      clean: true,
      scheme: "fastLaneFun2", 
      workspace: "fastLaneFun2.xcworkspace",
      export_method: "ad-hoc",
      configuration: "Release",
      use_legacy_build_api: true, ### Setting this to true is what made the error go away....
      # tool_chain: "3.0.2"
    ) # Build your app - more options available

    pilot(
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      changelog: "Trying Testflight...",
      # skip_submissio: true,
    )

    # testflight(
    #   skip_waiting_for_build_processing: true,
    #   changelog: "Trying Testflight...")
    # )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
```

Was wondering if ` use_legacy_build_api: true, ` is supposed to be used this way.... Thanks!
