### ISSUE TITLE
Equivalent of -exportProvisioningProfile?

### ISSUE THREAD

**Issue by jblack10101** [fastlane/fastlane#6283]
Is there an equivalent gym parameter to xcodebuild's -exportProvisioningProfile?  I would like to specifically define the provisioning profile that should be used to export the archive to ipa.  

provisioning_profile_path is no longer supported, and by using codesigning_identity, the wrong provisioning profile is selected because there are multiple profiles that will "work" for the app, but only one correct one with the entitlements I need.

**Comment by TKBurner** [comment]
@jblack10101 Great to hear from you! Have you tried --xcargs or --xconfig? THanks!

**Comment by jblack10101** [comment]
I ended up just defining the specific provisioning profile UUIDs to use in the project's xcconfig files.
