### ISSUE TITLE
Option for deliver to force it use DAV protocol

### ISSUE THREAD

**Issue by nickeyzzz** [fastlane/fastlane#6287]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Is it possible to add the option to start "deliver" and force it to use DAV transfer protocol? Something like
deliver -t DAV
For me DAV works stable, while other protocols - Signiant and Aspera always give errors.
I've made a change in itunes_transporter.rb file, added "-t 'DAV'" in two places and now it's uploading well, before that I could not upload anything. When internet connection is perfect, it's not a problem, but for ones who has some issues with connection or closed ports it can be problem.

**Comment by TKBurner** [comment]
@nickeyzzz Great to hear from you! Can you try something like this:

`DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="asdf" deliver`

Thanks!
