### ISSUE TITLE
Minor documentation aesthetic issue

### ISSUE THREAD

**Issue by kitsunde** [fastlane/fastlane#6291]
On https://docs.fastlane.tools/best-practices/ContinuousIntegration/#circle-integration

``` md
This will automatically cache the installed gems on Circle, making your CI 
builds much faster :rocket:
```

The `:rocket:` doesn't get replaced with :rocket:

**Comment by TKBurner** [comment]
@kitsunde Thanks for pointing this out! We'll update it. Hope you have a great day and thanks for checking out our new docs site. 👍 👍
