### ISSUE TITLE
Exit status 65

### ISSUE THREAD

**Issue by avnerbarr** [fastlane/fastlane#6293]
### New Issue Checklist
- [x ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Did the following commands:
cert
sigh
gym
##### Complete output when running fastlane, including the stack trace and command used

▸ Check Dependencies
*\* ARCHIVE FAILED **

The following build commands failed:
Check dependencies
(1 failure)
[15:36:53]: Exit status: 65

[!] Error building the application - see the log above

Looking at the log file I see this:
Check dependencies
"MyAppName" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

Not sure how to resolve this

**Comment by TKBurner** [comment]
Hi @avnerbarr Great to hear from you! Can you share the full output of cert and sigh? I want to take a look. Thanks so much!
