### ISSUE TITLE
Add 'spaceship' functionality for Google Play

### ISSUE THREAD

**Issue by LovesBruins** [fastlane/fastlane#6294]
### New Issue Checklist
- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Would it be possible to add the 'spaceship' functionality to Google Play store so we can automate the creation/submission of NEW applications with pricing/distribution, and something to somehow suffice, save, and apply the Content Rating Questionnaire?
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by TKBurner** [comment]
@LovesBruins Great idea! We'd love to see some of this functionality added. I'm going to leave this open as a feature request. If someone is interested in a PR let us know so we can help you scope the project!
