### ISSUE TITLE
How to delete or reset the password of per repository for match,i forget the password

### ISSUE THREAD

**Issue by ph661** [fastlane/fastlane#6297]
i want to delete or reset the password

[02:32:18]: Enter the passphrase that should be used to encrypt/decrypt your certificates
[02:32:18]: This passphrase is specific per repository and will be stored in your local keychain
[02:32:18]: Make sure to remember the password, as you'll need it when you run match on a different machine
Passphrase for Git Repo:

**Comment by TKBurner** [comment]
@ph661 Thanks for reaching out. You will need to run `match nuke` and regenerate your profiles and set a new password. Thanks!

**Comment by KrauseFx** [comment]
If you have access to your old mac, you can also find the password in the Keychain. Otherwise, run `match nuke`, and optionally clear out your repo

**Comment by joelmoss** [comment]
I'm trying to do this, but every time I run `match nuke`, it tries to clone the match git repo and asks me for the passphrase. How can I get around this, so I can reset the passphrase? thx

**Comment by JagCesar** [comment]
@joelmoss It's because you still have a git-url defined in your `Matchfile` that points to an encrypted repo. Create a new repo and update your `Matchfile` with the URL to this repo instead. Once you've done this you can run `fastlane match nuke [development/distribution]`.
