### ISSUE TITLE
Is there a way to get a blank xcworkspace to work with gym through cli?

### ISSUE THREAD

**Issue by kitsunde** [fastlane/fastlane#6298]
If I want to have a clean cordova build, I'm not supposed to include the ios platform, instead it gets generated on the build server together with everything else.

I can generate xcworkspace via xcode on CI. But is there some way of configuring xcode over cli like here: https://docs.fastlane.tools/codesigning/XcodeProject/#setting-up-your-xcode-project?

**Comment by TKBurner** [comment]
Hi @kitsunde what specifically are you trying to configure? What tool are you using? I'd love to help! 👍

**Comment by kitsunde** [comment]
I ended up replacing `gym` with using cordova directly over `sh` (`ember cdv:build` here calls cordova). This is what my lane looks like now:

```bash
lane :beta do
  match(type: "appstore")
  sh "../node_modules/.bin/ember cdv:build \
  --environment staging \
  --platform ios \
  --code-sign-identity='iPhone Distribution: Cannla Pte Ltd (856AP7L2GS)' \
  --provisioning-profile='" + ENV['sigh_org.patontheback.mobile_appstore'] + "' \
  --release"
  pilot(
    ipa: "ember-cordova/cordova/platforms/ios/build/device/Patontheback.ipa",
    skip_waiting_for_build_processing: true
  )
end
```

The issue was that Cordova keeps all the configuration in it's own config files so the ios project doesn't need to exist until the build happens so there's never a workspace. I was trying to create one anyways with:

```bash
open <path to my xcode project>
wait 10
killall XCode
```

But then the code signing docs says I have to manually configure by going through xcode, which doesn't seem possible. So it seems like the preferred way of using cordova is incompatible with gym. So I've solved it for all intents and purposes, even though it looks pretty ugly.

**Comment by TKBurner** [comment]
@kitsunde Glad you got up and running. That seems like a good way of doing things. There might also be a way to do this with ENV.
