### ISSUE TITLE
ItunesConnect UI change causing error 

### ISSUE THREAD

**Issue by ianwhite2** [fastlane/fastlane#630]
Hi all,

As the itunesconnect UI has been changed so it giving error after "Opening detail page for app"
 Couldn't find element '.page-subnav' after waiting for quite some time

Any Help on this ?

**Comment by KrauseFx** [comment]
I'm very aware of this https://twitter.com/KrauseFx/status/647146432911114240 and work on a fix right now.

**Comment by ianwhite2** [comment]
Oh sorry Will close it Wi

**Comment by KrauseFx** [comment]
You can leave it open, no problem. Thanks for reporting this issue :+1:

**Comment by ianwhite2** [comment]
Ok Cool
