### ISSUE TITLE
(Support Question) Unable to update change log

### ISSUE THREAD

**Issue by naxIO** [fastlane/fastlane#6303]
Hi guys,

this is more of a support question rather then a bug (I assume). Thanks for your help!
### Issue Description

I'm trying to use fastlane deliver to update the changelog (which is empty right now) for a new release. 

I have this in my
# Deliverfile

```
release_notes({
  'default' => "Shiny and new"
})
```

However when using deliver the changelog in the HTML output is always empty :( 

There is a release_notes.txt in every folder in metadata/$language but it's empty.

I assume since everything else is working and im running the latest version, it's correctly setup. What am I missing?
### Environment

fastlane 1.102.0

No Bundle Exec

RVM

**Comment by TKBurner** [comment]
@naxIO Thanks for reaching out. Were you able to get up and running? Can you let me know what happens if you set it to 'en-US' for testing purposes? Thanks so much!

**Comment by naxIO** [comment]
@TKBurner thanks for getting back. I can confirm it works with en-US. But still not with default. Using deliver 1.14.0

**Comment by TKBurner** [comment]
@naxIO So does it work as expected with both a default folder and a en-US? Is this related to #6226
