### ISSUE TITLE
Scan compile all files twice when using fastlane on travisCI

### ISSUE THREAD

**Issue by MouldiGABSI** [fastlane/fastlane#6306]
### New Issue Checklist
- [ ] Updated fastlane to the latest version YES
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
  YES
  ### Issue Description
  I am using fastlane with Travis CI to run unit test i am using Scan. when I take a look on the travis log, i find that all files are compiled twice test script take more then 10 mn to execute.
  PS: When i run unit test locally i dont have the problem.
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

Test runned twice and files compiled twice
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
desc "Run uni
t tests"
       lane :UnitTests do

```
     FASTLANE_EXPLICIT_OPEN_SIMULATOR=1
     scan(
       scheme: "MySchemeTests",
       clean: true,
       code_coverage: true,
       skip_build: true,
       skip_slack: false,
       sdk: "iphonesimulator",
       destination:"platform=iOS Simulator,name=iPhone 6s Plus,OS=9.3"
     )
   end
```
# INSERT CONTENT HERE

```

### Environment

fastlane version (run `fastlane -v`): latest

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? YES
```

**Comment by TKBurner** [comment]
@MouldiGABSI Thanks for reaching out. How many simulators named iPhone 6s Plus do you have on travis? That seems to be what's causing this.

**Comment by MouldiGABSI** [comment]
@TKBurner i have only one simulator on travis 
PS: I have the same issue with gym it compile all files twice

**Comment by TKBurner** [comment]
@MouldiGABSI Thanks for following up. What happens if you remove the line

`FASTLANE_EXPLICIT_OPEN_SIMULATOR=1`

Can you provide the full input and output and highlight the lines where you think the simulator is running twice? Thanks so much!
