### ISSUE TITLE
[Deliver] Q: Downloading screenshots of (old) live iOS App while new version is Prepare for Submission

### ISSUE THREAD

**Issue by Bureauwlamp** [fastlane/fastlane#6307]
- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hi,

I have a small question about downloading data/screenshots. I have an application which is 'Ready for Sale' in ITC. A few months ago we've prepared an update with completely different screenshots, which was Pending, but never released.

Today, we want to update the application (for iOS 10), but since the app never really changed, the wrong screenshots are still in the 'update shell' from earlier on. I've developer rejected but of course, I can only remove the 'wrong' screenshots.

Since this app is a cash cow but also pre-historic, we've lost the original screenshots. I'm wondering if it's possible to download the screenshots of the version that is currently Ready for Sale.

Using 'App version = "2.0"' (in the deliver file) doesn't help. It recognizes my input, but still downloads screenshots from the update version which is currently Prepare for Submission and containing the wrong screenshots.

Am I doing something wrong? Is this possible?

**Comment by Bureauwlamp** [comment]
Anybody? A yes or no if it is even possible would already suffice for now

**Comment by KrauseFx** [comment]
Hey @Bureauwlamp, sorry for the late reply. I'm not 100% sure, but you might be able to do so using _spaceship_: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/iTunesConnect.md

**Comment by TKBurner** [comment]
@Bureauwlamp Have you tried running `deliver download_screenshots`? That downloads all possible screenshots available in iTC. If they aren't available there I'm not sure it's possible through _fastlane_.
