### ISSUE TITLE
 Could not find action or lane 'pod_install'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane

### ISSUE THREAD

**Issue by BulletWu** [fastlane/fastlane#6315]
Could not find action or lane 'pod_install'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 39          |
| 4    | git_pull                            | 2           |
| 5    | ensure_git_branch                   | 0           |
+------+-------------------------------------+-------------+

[18:09:53]: fastlane finished with errors

[!] Could not find action or lane 'pod_install'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane

**Comment by KrauseFx** [comment]
Can you please share your Fastfile?

**Comment by BulletWu** [comment]
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

#!/bin/bash -l
#export LANG=en_US.UTF-8
#pod repo update hljnbw-xiangyuanzhi-iospodspecs
#pod install --no-repo-update

fastlane_version "1.102.0"
default_platform :ios
platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end
  lane :do_release_lib do |options|
  	target_version    = options[:version]
    raise "The version is missed." if target_version.nil?
  	project	        	= options[:project]
  	path		           = "#{project}.podspec"
  	git_pull
  	ensure_git_branch
  	pod_install
    pod_lib_lint(verbose: true, allow_warnings: true, sources: SOURCES, use_bundle_exec: true, fail_fast: true)
    version_bump_podspec(path: path, version_number: target_version) # 更新 podspec
    git_commit_all(message: "Bump version to #{target_version}") # 提交版本号修改
    add_git_tag(tag: target_version) # 设置 tag
    push_to_git_remote # 推送到 git 仓库
    pod_push(path: path, repo: "IOSPodSpecs", allow_warnings: true, sources: SOURCES) # 提交到 CocoaPods
    end
  end
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

**Comment by BulletWu** [comment]
fastlane_version "1.102.0"
default_platform :ios

platform :ios do

  MASTER_PATH    = "https://github.com/CocoaPods/Specs"
  PRIVATE_PATH   = "http://pricompany2.hljnbw.cn:3018/xiangyuanzhi/IOSPodSpecs.git"
  SOURCES        = [MASTER_PATH, PRIVATE_PATH]

  desc "Release new private pod version"
  lane :do_release_lib do |options|
    target_version = options[:version]
    project        = options[:project]
    path           = "#{project}.podspec"
    git_pull
    ensure_git_branch # 确认 master 分支
    pod_install
    pod_lib_lint(verbose: true, allow_warnings: true, sources: SOURCES, use_bundle_exec: true, fail_fast: true)
    version_bump_podspec(path: path, version_number: target_version) # 更新 podspec
    git_commit_all(message: "Bump version to #{target_version}") # 提交版本号修改
    add_git_tag(tag: target_version) # 设置 tag
    push_to_git_remote # 推送到 git 仓库
    pod_push(path: path, repo: "IOSPodSpecs", allow_warnings: true, sources: SOURCES) # 提交到 CocoaPods
    end
    after_all do |lane|
      # This block is called, only if the executed lane was successful

      # slack(
      #   message: "Successfully deployed new App Update."
      # )
    end
    error do |lane, exception|
      # slack(
      #   message: exception.message,
      #   success: false
      # )
    end
  end

**Comment by TKBurner** [comment]
@BulletWu Thanks for reaching out. Can you replace your pod_install command with `cocoapods`

Thanks!
