### ISSUE TITLE
What is use_legacy_build_api

### ISSUE THREAD

**Issue by onmyway133** [fastlane/fastlane#6321]
Hi, just wonder what does `use_legacy_build_api` do, and should we not specify it for now? I see the source code https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/package_command_generator_xcode7.rb

And I run `gym --verbose` and `gym --verbose --use_legacy_build_api`, from the output in `Generated Build Command` they generate the same `xcodebuild` commands

What are the the diff between them? Do they change anything differently to the project build settings?

**Comment by KrauseFx** [comment]
It's recommend not to use it, as it's the old way of archiving the application, but depending on your setup you might be required to enable it

**Comment by tabrindle** [comment]
Is it typical for for use_legacy_build_api to be faster than the modern build api? My project builds about 20% slower without this option on.

**Comment by onmyway133** [comment]
@KrauseFx thanks for your reply. With `--verbose` I see that those output the same `xcodebuild` commands, is that right?

**Comment by TKBurner** [comment]
@onmyway133 I think the commands that run are slightly different.

**Comment by onmyway133** [comment]
@TKBurner Hi, how are they different? Can you please elaborate a little bit?

**Comment by KrauseFx** [comment]
Yes, please don't use the legacy build API as it doesn't work well with the latest Apple frameworks.

**Comment by KrauseFx** [comment]
It's using the Xcode 6 build API, which is not officially supported any more. If you're having troubles with the new build API, please submit a new issue, so we can help you get up and running.
