### ISSUE TITLE
Coming to terms with XCode8 Code Signing

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#6324]
So I'm a little confused as how to best work with the code signing changes in Xcode 8.

I have a project with 2 targets and 3 build types
- `target1.alpha` (Enterprise Cert)
- `target1.beta` (Enterprise Cert)
- `target1` (app store Cert)
- `target2.alpha` (Enterprise Cert)
- `target2.beta` (Enterprise Cert)
- `target2` (app store Cert)

What I'd like to do is have my normal project been `Automatic` mode when developers are working on it  - but in Fastlane I'd like to have it converted over to `Manual` mode so that I can insert specific profiles etc.

When I toggle between Automatic and Manual the fields that are different in the project file are:

```
CODE_SIGN_IDENTITY 
"CODE_SIGN_IDENTITY[sdk=iphoneos*]" 
DEVELOPMENT_TEAM 
PROVISIONING_PROFILE
PROVISIONING_PROFILE_SPECIFIER 
```

I'm currently leaning towards a bunch of `sed` commands to rewrite these fields before fastlane runs and then at the end restore the file - but this seems terrible.

I've read over the docs at: https://docs.fastlane.tools/codesigning/xcode-project and nothing really seemed to jump out for what i'm looking for.

Am i missing something super obvious?  Things are complicated because I have 2 developer accounts with 6 different profiles i'm working with.

Thanks

**Comment by jeeftor** [comment]
> I've read over the docs at: https://docs.fastlane.tools/codesigning/xcode-project and nothing really seemed to jump out for what i'm looking for.

Yea I've read through everything you have and I guess i'm confused as to whether it is actually possible to do what I want. 

I have two targets a Framework and an App.  I tried to feed in settings via `GYM_XCARGS` but ended up with an error

```ruby
provisioning_profile_specifier='AMAT - Beta'
ENV['GYM_XCARGS'] = "DEVELOPMENT_TEAM=#{ENV["SIGH_CERTIFICATE_ID"]} PROVISIONING_PROFILE_SPECIFIER=#{provisioning_profile_specifier}"
```

That my framework was being force-fed a profile

> DataAPI has conflicting provisioning settings. DataAPI is automatically signed, but provisioning profile AMAT - Beta has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor, or switch to manual signing in the project editor.

Unfortunately because there are many group s sharing certs we can't use **match** which would probably be easier I'm assuming.

**Comment by jeeftor** [comment]
So I seem to have got things working in a rather less than ideal way.  The steps I follow are:

1) Use Manual Signing
2) Extract out the existing profile
```ruby
EXISTING_PROFILE = sh("xcodebuild -project ../AMAT.xcodeproj -scheme AMAT -showBuildSettings | grep PROVISIONING_PROFILE_SPECIFIER | sed -E s'/[[:space:]]+PROVISIONING_PROFILE_SPECIFIER = //g'").chomp()
```

Basically extract the `PROVISIONING_PROFILE_SPECIFIER` value out of `xcodebuild -showBuildSettings`

The reason I do this is because I want to change it during the build process - depending which version of the software I'm building - and then restore it when I'm done.

Depending on `Alpha`,or`Beta` or `Release` configurations I have a different specifier which gets written into the variable `provisioning_profile_specifier`

My code will automatically change the app name and bundle id to (app.beta, app or app.alpha) depending on my release.  The goal is to have a matching profile also get set.  

Next I setup some commands:

```ruby
CONVERT_REGEX = "s/#{EXISTING_PROFILE}/#{provisioning_profile_specifier}/g"
RESTORE_REGEX = "s/#{provisioning_profile_specifier}/#{EXISTING_PROFILE}/g"
CONVERT_CMD = "sed -i '' '#{CONVERT_REGEX}' ../AMAT.xcodeproj/project.pbxproj"
RESTORE_CMD = "sed -i '' '#{RESTORE_REGEX}' ../AMAT.xcodeproj/project.pbxproj"
```

And basically before I build i run the `CONVERT_COMMAND` and after I run the `RESTORE_COMMAND`

Whats nice is that the users can stick with their happy manual command and my CI server can handle building whatever release type is necessary based on checked-in branch, however, i feel there must be a better way.

Unless anybody has suggestions I'll close this issue in a day or two.

**Comment by TKBurner** [comment]
@jeeftor Thanks for following up. Are you not able to use different schemes for these to separate them more? Thanks!
