### ISSUE TITLE
SIGH_UDID should be SIGH_UUID

### ISSUE THREAD

**Issue by maschall** [fastlane/fastlane#6327]
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

UDID - Unique Device Identifiers
UUID - Universal Unique Identifier

In the Provision profile Plist the element is UUID, but we are using UDID, which is incorrect.

Anyway we can deprecate the incorrect one and change to UUID?

**Comment by KrauseFx** [comment]
Thanks for letting us know, I'm aware of this, however we'd still have to support both to not break any setups. This would add some complexity, however I'm more than happy to review a PR fixing this 👍

**Comment by maschall** [comment]
@KrauseFx What do you think if we refactored lane_context and ENV, into objects that could redirect UUID to UDID.

Example:
Environment["SIGH_UUID"] would read ENV["SIGH_UUID"] first and then fall back to ENV["SIGH_UDID"]

I'm thinking this should help in the future if we needed to deprecate/change an environment variables again.

**Comment by TKBurner** [comment]
@maschall Thanks for the PR, we need to make sure to not break any setups. We'll work with you over there. Hope that you are having a great week! 👍
