### ISSUE TITLE
Frameit places iPad Pro screenshots wrong

### ISSUE THREAD

**Issue by jannejava** [fastlane/fastlane#6332]
Just installed Frameit and downloaded Apple's templates. 

The screenshots are slightly off in relation to Apple's templates.

No errors in the terminal, could Apple have updated their graphics?

https://dl.dropboxusercontent.com/u/1066320/Simulator%20Screen%20Shot%2029%20sep.%202016%2011.19.04_framed.png

**Comment by TKBurner** [comment]
@jannejava Thanks for reaching out. Apple did change somethings recently and we are moving toward hosting our own templates. Can you update on #6272 and mention that affected devices you are seeing. Thanks so much!
