### ISSUE TITLE
Fastlane doesn't seem to 'play nicely' with automatic code signing

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#6333]
### New Issue Checklist
- [y ] Updated fastlane to the latest version
- [y ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I have a new Xcode 8 app with an iMessage plugin and shared app group entitlement.
I selected the 'automatically manage code signing' box in xcode, and it looks like finally XCode does a good job.
I can archive and upload to iTunes from XCode

Unfortunately, fastlane can no longer build an upload a binary for me.
I have tried adding sigh to the flow and it seems happy enough - but doesn't make iTunes happy
##### Complete output when running fastlane, including the stack trace and command used

```
...
[11:24:29]: Successfully exported and compressed dSYM file
[11:24:29]: Successfully exported and signed the ipa file:
[11:24:29]: /Users/rob/tmp/FastlaneBuild/Poop Pack.ipa
[11:24:29]: ------------------
[11:24:29]: --- Step: sigh ---
[11:24:29]: ------------------

+-------------------------------------+-------------------------------+
|                       Summary for sigh 1.11.1                       |
+-------------------------------------+-------------------------------+
| adhoc                               | false                         |
| development                         | false                         |
| skip_install                        | false                         |
| force                               | false                         |
| app_identifier                      | com.HobbyistSoftware.poop     |
| username                            | hobbyist@hobbyistsoftware.com |
| team_id                             | JHV5RC82C3                    |
| ignore_profiles_with_different_name | false                         |
| skip_fetch_profiles                 | false                         |
| skip_certificate_verification       | false                         |
+-------------------------------------+-------------------------------+
...

[11:25:55]: Going to upload updated app to iTunes Connect
[11:25:55]: This might take a few minutes. Please don't interrupt the script.
[11:26:35]: [Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.HobbyistSoftware.poop [Payload/Poop Pack.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[11:26:35]: Transporter transfer failed.
[11:26:35]: 
[11:26:35]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.HobbyistSoftware.poop [Payload/Poop Pack.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[11:26:35]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.HobbyistSoftware.poop [Payload/Poop Pack.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
Return status of iTunes Transporter was 1: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.HobbyistSoftware.poop [Payload/Poop Pack.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[11:26:35]: Variable Dump:
[11:26:35]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release", :BUILD_NUMBER=>"22", :IPA_OUTPUT_PATH=>"/Users/rob/tmp/FastlaneBuild/Poop Pack.ipa", :DSYM_OUTPUT_PATH=>"/Users/rob/tmp/FastlaneBuild/Poop Pack.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/rob/Library/Developer/Xcode/Archives/2016-09-29/Poop Pack 2016-09-29 11.22.49.xcarchive", :SIGH_PROFILE_PATH=>"/Users/rob/Documents/Development/Mac/iPhone/PoopPack/AppStore_com.HobbyistSoftware.poop.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/rob/Documents/Development/Mac/iPhone/PoopPack/AppStore_com.HobbyistSoftware.poop.mobileprovision"], :SIGH_UDID=>"75fce413-4882-4aac-afa8-c28a2c3b77a7", :SIGH_PROFILE_TYPE=>"app-store"}
[11:26:35]: Could not upload binary to iTunes Connect. Check out the error above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 0           |
| 4    | gym                                 | 102         |
| 5    | sigh                                | 11          |
| 6    | deliver                             | 115         |
+------+-------------------------------------+-------------+

[11:26:35]: fastlane finished with errors

```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    increment_build_number
    gym # Build your app - more options available
    sigh
    deliver(
      skip_screenshots: true,
      skip_metadata: false,
      submit_for_review: false,
      automatic_release: true)
    # frameit
  end
```

Deliverfile

```
scheme "Poop"
output_directory "~/tmp/FastlaneBuild"
use_legacy_build_api true

```
### Environment

fastlane version (run `fastlane -v`):

fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm

**Comment by ConfusedVorlon** [comment]
thank you fastlane bot!

to be more specific - automatic code signing seems to be pretty great now.

The troubleshooting guide suggests disabling it. 

Is that still the only way - and if so, are there any plans to make fastlane compatible with auto-code signing?

**Comment by KrauseFx** [comment]
Seems like it's using a Development profile instead of a Distribution one. Make sure to select the distribution profile in the Xcode `General` tab. Also, please share a screenshot of the `General` tab and the Code Signing section in the `Build Settings`

**Comment by ConfusedVorlon** [comment]
@KrauseFx I might be missing something - but my understanding is that with automatic signing, I don't get to choose the profile.

If the answer is just 'fastlane won't work with automatic', then so be it - but if there is a way to have the advantages of automatic, and also fastlane, then that would be great!

<img width="899" alt="2016-09-29 07 41 45 pm" src="https://cloud.githubusercontent.com/assets/586910/18967384/e8e09e98-867c-11e6-85d6-0a5a7592c4fc.png">

<img width="874" alt="2016-09-29 07 45 10 pm" src="https://cloud.githubusercontent.com/assets/586910/18967491/474007ee-867d-11e6-80ea-7364d0435639.png">

**Comment by TKBurner** [comment]
@ConfusedVorlon Thanks for following up. Right now you'll need to manually set this up in most cases. However, I have reached out to the team because I think we need to make a definitive statement on this. Also, are you interested in making this fail better or supported via a PR? That'd be really interesting. Thanks again 👍

**Comment by kwoylie** [comment]
Yeah, it would be great if we can share some light on this. So from after playing around with the automatically signing migration and fastlane. Automatically signing uses a developer profile to create the archive of the app, then it will export and sign with the distribution profile.

This developer profile that it signs with is a special provision profile that gets generated by Xcode, but isn't visible to the Apple portal and it's called "iOS Team Provisioning Profile: {bundle identifier}".

Now match doesn't seem to have a way of retrieve these special provisioning profile or generating them. I think if match development actually picks up these special provisioning profile it will fix the issue. In the interim, I have been manually adding them to the match repo, and it seems to work pretty smoothly.

**Comment by ConfusedVorlon** [comment]
@TKBurner it would be great to have clarity on this. Better still if you can play nicely with automatic signing.

re a pull request - I think I'm done with those. It was deeply painful the last couple of times I tried.

thanks for following up.

**Comment by KrauseFx** [comment]
Thanks for the feedback @ConfusedVorlon @kwoylie, I completely agree we can do a better job documenting best practices around how to manage code signing in Xcode 8 with _fastlane_ and _match_. As you know we've worked on completely building the [docs.fastlane.tools](https://docs.fastlane.tools) from scratch. We're still working on refining all the docs, and want to put a big focus on code signing too.

Thanks for the feedback, we'll definitely work on this over the next days and weeks 👍

**Comment by hdoria** [comment]
Same problem here. iTunes is rejecting my app when I use fastlane and automatic code signing is enabled on Xcode 8.

```
ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle myapp.app [Payload/MyApp.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[20:05:40]: Transporter transfer failed.
```

Match shows the correct provisioning profile on the summary.

**Comment by Cyclic** [comment]
It would be nice to be able to skip match and sigh altogether and stick with automatic, since it does appear to work with distribution; although maybe not the private key aspect, but I have not tested on a clean keychain yet.

Right now this issue is preventing us from pushing to crashlytics with fast lane.

**Comment by TKBurner** [comment]
@ConfusedVorlon @hdoria @Cyclic This is a topic of great discussion this week with the core team. We definitely want to improve expectations or behavior around this. Thanks! 👍 👍

**Comment by ConfusedVorlon** [comment]
any word on this?

**Comment by TKBurner** [comment]
@ConfusedVorlon Thanks for following up. Check out the docs here, https://docs.fastlane.tools/codesigning/xcode-project/#using-match-development-or-xcode-automatic-provisioning

**Comment by ConfusedVorlon** [comment]
Hi @TKBurner thanks for the response.

The docs seem to imply that we can use automatic signing if we're only developing on a single computer.

That works for me with some apps - but not with others. Is that now a bug I should report separately?
