### ISSUE TITLE
[Match] - match nuke profiles

### ISSUE THREAD

**Issue by tabrindle** [fastlane/fastlane#6334]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Match doesn't have the capability to nuke just provisioning profiles - it nukes the certs and provisioning profiles. While useful in a lot of use cases, this is far more destructive than necessary. Previously mentioned in https://github.com/fastlane/fastlane/issues/5540, it would be useful to be able to just update the profiles without invalidating the certificates. 

##### Complete output when running fastlane, including the stack trace and command used

Works as intended:
```
match nuke distribution 
```

Feature requested:
```
match nuke profile distribution
```
Leaves certificates intact, recreates and redownloads provisioning profiles. 

### Environment

fastlane version (run `fastlane -v`): 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
Sorry, it can only nuke everything, there is no plan on changing this for now. What's the main reason you need this?

**Comment by lferro9000** [comment]
Note that nuking everything doesn't affect published apps on App Store nor apps under review.

Not sure about apps on testflight or waiting to be sent for review (probably they will need a new binary, if the existing binary is checked when submiting and not when it was uploaded).

I'd one binary ready for testing in testflight (review done already), and it didn't become invalid after nuking either.
