### ISSUE TITLE
[Match] Concerns about Match nuke and APNs certificates

### ISSUE THREAD

**Issue by lucabartoletti** [fastlane/fastlane#6336]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This more a question than an issue. I can't find informations about this. If on my developer portal I have APNs certificates. Does `match nuke` delete those certificates?

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm

**Comment by tabrindle** [comment]
In my experience, no it does not. But I don't run nuke if I can help it.

**Comment by TKBurner** [comment]
@lucabartoletti Did you run this command? You might need to renew your cert after you run match nuke.

**Comment by KrauseFx** [comment]
It shouldn't affect push certificates

**Comment by lucabartoletti** [comment]
Verified that it doesn't

**Comment by KrauseFx** [comment]
Perfect, thanks for letting us know and confirming @lucabartoletti 👍
