### ISSUE TITLE
incomplete command in codesigning.guide

### ISSUE THREAD

**Issue by maschall** [fastlane/fastlane#6346]
"The certificates and private keys should be imported into your Keychain, either using Finder or using the ty import’ command"

I believe it should be

"The certificates and private keys should be imported into your Keychain, either using Finder or using the ’securitty import’ command"

**Comment by KrauseFx** [comment]
Thanks for letting us know, we'll update the website 👍

**Comment by KrauseFx** [comment]
This is fixed now, thanks again 👍
