### ISSUE TITLE
Fastlane still cannot create adhoc provisioning profiles for enterprise accounts.

### ISSUE THREAD

**Issue by SNN-reggie** [fastlane/fastlane#6349]
I manage an enterprise with several dozen apps, and Fastlane seems like an amazing tool, however having to manually create all the adhoc profiles is not fun!

Here's the verbose output when trying to use sigh from the command line to create an adhoc provisioning profile.

Steps to reproduce;

sigh -a pick.an.app_identifier --force true --adhoc true --verbose

Output;

INFO [2016-09-29 16:10:23.50]: Successfully logged in
INFO [2016-09-29 16:10:23.50]: Fetching profiles...
WARN [2016-09-29 16:10:24.10]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
/Users/reggie/.gem/ruby/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Could not find a matching code signing identity for type 'AdHoc'. It is recommended to use match to manage code signing for you, more information on https://codesigning.guide.If you don't want to do so, you can also use cert to generate a new one: https://fastlane.tools/cert (FastlaneCore::Interface::FastlaneError)
    from /Users/reggie/.gem/ruby/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/ui.rb:14:in`method_missing'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/lib/sigh/runner.rb:191:in `certificate_to_use'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/lib/sigh/runner.rb:123:in`create_profile!'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/lib/sigh/runner.rb:39:in `run'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/lib/sigh/manager.rb:7:in`start'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/lib/sigh/commands_generator.rb:56:in `block (2 levels) in run'
    from /Users/reggie/.gem/ruby/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in`call'
    from /Users/reggie/.gem/ruby/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/reggie/.gem/ruby/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in`run'
    from /Users/reggie/.gem/ruby/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/reggie/.gem/ruby/2.0.0/gems/fastlane_core-0.52.0/lib/fastlane_core/ui/fastlane_runner.rb:36:in`run!'
    from /Users/reggie/.gem/ruby/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/lib/sigh/commands_generator.rb:120:in`run'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/lib/sigh/commands_generator.rb:11:in `start'
    from /Users/reggie/.gem/ruby/2.0.0/gems/sigh-1.11.1/bin/sigh:6:in`<top (required)>'
    from /Users/reggie/bin/sigh:23:in `load'
    from /Users/reggie/bin/sigh:23:in`<main>'

**Comment by PetrosIchor** [comment]
The documentation states that fastlane does not support enterprise due to security concerns.  It's a pain I feel as well.  The only solution I found was to just manually script out the signing of those build types.  Pretty simple to get it up and running, you just have to manage two flows and lose the security convenience of match.

I could be wrong, but it shouldn't be hard to clone the match action and built out your own personal enterprise generation via the API.

**Comment by TKBurner** [comment]
@PetrosIchor There is also a workaround for forcing match and enterprise however if you run into any issues we cannot help. Thanks!

**Comment by SNN-reggie** [comment]
I'm not using match, I'm using cert/sigh.  This issue is really just about sigh.
