### ISSUE TITLE
I'm using libreadline.7.dylib

### ISSUE THREAD

**Issue by LawrenceHan** [fastlane/fastlane#6350]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When called fastlane lane, it first shows `dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib` then contiune working. Because I have installed the latest readline version.
##### Complete output when running fastlane, including the stack trace and command used

```
dyld: Library not loaded: /usr/local/opt/readline/lib/libreadline.6.dylib
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflight do
    increment_build_number
    #match(type: "appstore")
    gym(
    workspace: "flirten.xcworkspace",
    scheme: "Distribution"
    ) # Build your app - more options available
    pilot(
      skip_submission: true
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

**Comment by jedi4ever** [comment]
ruby requires readline 6 - you need to switch to that version.
and optionally use brew pin to avoid it from being upgraded

**Comment by revolter** [comment]
`brew switch readline 6.3.8`
