### ISSUE TITLE
Updating screenshots and metadata for existing apps

### ISSUE THREAD

**Issue by ahildinger** [fastlane/fastlane#6352]
Hi,
is there a possibility to update screenshots and metadata of a existing "Ready For Sale" app if the app is a newsstand app? Newstand apps are editable although they are "Ready For Sale". When I tried `deliver run` I got this error: 

> [!] The request could not be completed because:
> The version number has been previously used.

https://github.com/fastlane-old/deliver/issues/493 had the same issue but it was possible to update price tiers with spaceship. Nevertheless I found no solution to achieve this with screenshots and metadata using.

Can you help? Thanks in advance

**Comment by TKBurner** [comment]
@codmag This is not directly implemented but might be possible through spaceship. I'm going to mark this as a feature request. Thanks!
