### ISSUE TITLE
Spaceship::ProvisioningProfile::AppStore includes AdHoc profiles

### ISSUE THREAD

**Issue by imanf** [fastlane/fastlane#6354]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Calling Spaceship::ProvisioningProfile::AppStore return both AppStore and AdHoc provisioning profiles. 

### Environment

fastlane version (run `fastlane -v`): 1.91.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

**Comment by KrauseFx** [comment]
That's by design due to a recent change on the Dev Portal: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md#receiving-profiles, also check out the release notes https://github.com/fastlane/fastlane/releases/tag/spaceship%2F0.33.0
