### ISSUE TITLE
lane_context not updated from other_action

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#6358]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

When I call `other_action.unlock_keychain` with the `set_default: true` option, the `Actions.lane_context[Actions::SharedValues::ORIGINAL_DEFAULT_KEYCHAIN]` is not updated.

Is this to be expected?

### Environment

fastlane version (run `fastlane -v`): 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by KrauseFx** [comment]
It should be set when `add_to_search_list` is set to `:replace`

**Comment by lyndsey-ferguson** [comment]
@KrauseFx yes, that works. Thank you.

**Comment by KrauseFx** [comment]
Cool 👍
