### ISSUE TITLE
provisioning_profile requires a default keychain to be set

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#6359]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I have been trying to get around the need to change the default keychain by passing Xcode the keychain to use. However, when `gym` runs, it runs `Plist.parse_xml(security cms -D -i "#{path}")` within `ProvisioningProfile.parse`. This could be fixed if a _given_ keychain could be provided to the command, `Plist.parse_xml(security cms -D -i "#{path}" -k "#{keychain_name}")`
### Environment

fastlane version (run `fastlane -v`): 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by lyndsey-ferguson** [comment]
**Note**, I am more than willing to make the change if someone can provide a tip on how best to do this. I'm not sure I would want to change the function signatures a lot as that would cause too much disruption.

@fastlane-bot Yes, I have read the Guide, it doesn't meet my needs as we have other certs and provisioning files that need to be managed by us.

**Comment by TKBurner** [comment]
@lyndsey-ferguson Are you using Sierra? I think this might be related to some other similar issues. Thanks!

**Comment by lyndsey-ferguson** [comment]
No, I'm still using El Capitan. Looking at the code, it has to have a default keychain as it doesn't have one specified. I'd like to avoid changing the default keychain and instead pass it down to Xcode directly using `OTHER_CODE_SIGN_FLAGS="--keychain mykeychain"`
