### ISSUE TITLE
How to keep credentials secure if a team member is leaving?

### ISSUE THREAD

**Issue by deiucanta** [fastlane/fastlane#6361]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I can remove him from the certificates git repo but he still has the password for the iTunes Connect, right? If I keep the credentials to iTunes Connect I will be the only one able to push beta versions.

**Comment by TKBurner** [comment]
@deiucanta If you remove him from the repo, he'll still have the iTC information in his keychain if you gave it to him. However, to setup match you only need repo access and the password by using read_only: true.

**Comment by deiucanta** [comment]
@TKBurner correct, that's what I'll do — keep the match with the readonly flag active and have a different lane for the actual sync

thanks
