### ISSUE TITLE
Frameit is unable to use iPhone 6S frames

### ISSUE THREAD

**Issue by ayushgoel** [fastlane/fastlane#6362]
- [x] Updated fastlane to the latest version
Yes, using `fastlane run update_fastlane`.

- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

1. iPhone 7 device frames are not being used currently.
2. `frameit` even though able to find the device frame for iPhone 6S, is not using it.

##### Complete output when running fastlane, including the stack trace and command used

```
DEBUG [2016-10-01 17:50:32.62]: Looking for iPhone-6s-Plus-Silver-vertical and found 2
DEBUG [2016-10-01 17:50:33.10]: Looking for iPhone-6s-Plus-Silver-vertical and found 2
DEBUG [2016-10-01 17:50:33.10]: Parsing config file '.../fastlane/screenshots/Framefile.json'
DEBUG [2016-10-01 17:50:37.03]: Falling back to default text as there was nothing specified in the .strings file
ERROR [2016-10-01 17:50:37.04]: `Helper.gem_path` is deprecated. Use the `ROOT` constant from the appropriate tool module instead.
DEBUG [2016-10-01 17:50:37.66]: Using .../fastlane/screenshots/OpenSans.ttf as font the title of ./fastlane/screenshots/en-US/1.png
DEBUG [2016-10-01 17:50:37.66]: Adding text 'TEXT'
INFO [2016-10-01 17:50:42.64]: Added frame: '.../fastlane/screenshots/en-US/1_framed.png'
```

### Configuration Files

Framefile:
```ruby
{
  "default": {
    "keyword": {
      "font": "OpenSans.ttf"
    },
    "title": {
      "fonts": [
        {
          "font": "OpenSans.ttf",
          "supported": ["en-US"]
        }
      ],
      "color": "#545454"
    },
    "background": "./red-background.jpg",
    "padding": 50
  },
  "data": [
    {
      "filter": "LandingScreen",
      "keyword": {
        "color": "#d21559"
      }
    }
  ]
}
```

### Environment

fastlane version (run `fastlane -v`):

* fastlane 1.104.0
* frameit 2.7.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Yes, rvm
```
ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
```

**Comment by SRowley90** [comment]
Having the same issue too, one interim solution would be find the iPhone 6S assets from Apple but they are not available from the [link](https://developer.apple.com/app-store/marketing/guidelines/#images)

**Comment by madnik** [comment]
Anyone got those 6s version of files already downloaded? Appreciate if someone can share with me.

**Comment by verticelo** [comment]
Yes, would love to get those frames as well since Apple has removed them from the page.

**Comment by ayushgoel** [comment]
As mentioned in my initial report, I had bot iPhone 7 and iPhone 6S device frames. `frameit` was able to detect the 6S frames too (check above added logs), but still didn't use them.
Let me know if any other information is required.

**Comment by TKBurner** [comment]
@ayushgoel @verticelo @ayushgoel We are tracking this on #6272. Can you confirm this is the same issue? The basic end solution here is that we will host our own device templates. This is work in progress. Thanks!

**Comment by ayushgoel** [comment]
@TKBurner No this is not the same issue as https://github.com/fastlane/fastlane/issues/6272
Please reopen.

Here is a sample of what I get:

![1_framed](https://cloud.githubusercontent.com/assets/893050/19178107/69382f3e-8c6d-11e6-9d13-e1a191727da2.png)

**Comment by TKBurner** [comment]
@ayushgoel Thanks for following up. We are looking into this internally. I'm also marking this to see if we can get some community attention. Thanks!

**Comment by ayushgoel** [comment]
@TKBurner Thanks a lot! Let me know in case any logs or help is required at my end. 
I will keep a close watch on this thread. :bowtie:

**Comment by KrauseFx** [comment]
I'm actively working on a re-write of _frameit_ that supports all the latest devices with https://github.com/fastlane/fastlane/pull/6597, please subscribe to the pull request to stay up to date. We hope to have a new version ready this week  🚀
