### ISSUE TITLE
Scan README and Docs don't mention device version specifiers

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/fastlane#6366]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The devices list option for **scan** allows you to specify the version, for example `"iPhone 6s (9.3)"`. There is a spec for it in `test_command_generator_spec.rb`, but I can't find it documented.

**Comment by KrauseFx** [comment]
Is it documented in `scan --help`? That's where all the available parameters are described

**Comment by KrauseFx** [comment]
Seems to be in there 👍
