### ISSUE TITLE
Upgrade excon to 0.46.0+

### ISSUE THREAD

**Issue by cpunion** [fastlane/fastlane#6367]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm integrating `fastlane` into my project, the `fastlane_core` locked `excon` to `0.45.0` (see https://github.com/fastlane/fastlane/blob/master/fastlane_core/fastlane_core.gemspec#L29), but `excon-0.45.0` has a problem https://github.com/excon/excon/issues/547, it affected my project, so could you please upgrade `excon` to `0.46.0+`?

Thanks.

##### Output of `bundle update`

```
  In Gemfile:
    excon (>= 0.46.0)

    fastlane was resolved to 1.104.0, which depends on
      supply (< 1.0.0, >= 0.7.1) was resolved to 0.7.1, which depends on
        fastlane_core (>= 0.52.0) was resolved to 0.52.0, which depends on
          excon (~> 0.45.0)
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No, can't install with bundler.

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm

**Comment by KrauseFx** [comment]
Sounds okay to me, we can be less restrictive with the version. Could you submit a PR and test it locally?

**Comment by cpunion** [comment]
I will try. What is better for depends `gem 'excon', '~> 0.53.0` and `gem 'excon', '>= 0.46.0'`?

**Comment by KrauseFx** [comment]
I think replacing `spec.add_dependency 'excon', '~> 0.45.0' # Great HTTP Client` with `spec.add_dependency 'excon', '>= 0.45', '< 1.0' # Great HTTP Client` should do the trick.

**Comment by KrauseFx** [comment]
Thanks 👍
