### ISSUE TITLE
Certificates are 

### ISSUE THREAD

**Issue by daneov** [fastlane/fastlane#6377]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The certificates are duplicated. Every time (except after deleting all certificates) I run a lane which calls the lane `certificates`, the certificates are imported in my keychain, resulting in Xcode not being able to find the correctly linked certificate anymore (somehow).

I have a certificate which appears 3 times in my keychain.
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  private_lane :certificates do |options|
    build_type = (["development", "adhoc", "appstore"].include? options[:type]) ? options[:type] : "development"
    app_identifiers = [
      "com.vikingco.vikingapp",
      "com.vikingco.vikingapp.VikingApp-today",
      "com.vikingco.vikingapp.watchkitapp",
      "com.vikingco.vikingapp.watchkitapp.watchkitextension",

      "com.vikingco.vikingapp.alpha",
      "com.vikingco.vikingapp.alpha.VikingApp-today",
      "com.vikingco.vikingapp.alpha.watchkitapp",
      "com.vikingco.vikingapp.alpha.watchkitapp.watchkitextension"
    ]

    app_identifiers.each do | app_id |
      match(app_identifier: app_id, type: build_type, shallow_clone: true, force_for_new_devices: true)
    end

  end
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.104.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? [ ]

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? [ ]

**Comment by KrauseFx** [comment]
Have you set up the Xcode project as described here? https://docs.fastlane.tools/codesigning/XcodeProject/

**Comment by daneov** [comment]
There was a remnant of a previously selected UUID in the .xcodeproj somewhere.
Could that have been the culprit?

It isn't occurring anymore, so I guess it is fixed, though it was weird having the same certificate in the keychain for about 3 times.

**Comment by asfalcone** [comment]
Glad that the issue is resolved for you after fixing up your .xcodeproj 👍
