### ISSUE TITLE
TravisCI and itunesconnect password

### ISSUE THREAD

**Issue by jaroslavas** [fastlane/fastlane#6378]
### New Issue Checklist

- [+] Updated fastlane to the latest version
- [+] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to run fastlane commands on TravisCI. That includes creating new certificates and provisioning profiles and then uploading everything to itunesconnect. The problem is I can't login to dev portal. I've set `FASTLANE_PASSWORD` in `travis.yml` using secure variables, but fastlane still asks me for a password. Maybe there is something more to it?

From the output it looks like match doesn't even try to login and just asks for a password.

##### Complete output when running fastlane, including the stack trace and command used

```
[12:33:38]: Cloning remote git repo...
[12:33:40]:   Successfully decrypted certificates repo
[12:33:40]: You can also run `match` in readonly mode to not require any access to the
[12:33:40]: Developer Portal. This way you only share the keys and credentials
[12:33:40]: $ match --readonly
[12:33:40]: More information https://github.com/fastlane/fastlane/tree/master/match#access-control
[12:33:40]: Verifying that the certificate and profile are still valid on the Dev Portal...
-------------------------------------------------------------------------------------
The login information you enter will be stored in your Mac OS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` env variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for my@email.com): stty: stdin isn't a terminal
stty: stdin isn't a terminal
stty: stdin isn't a terminal
```

### Configuration Files

Fastfile:
```ruby
# Prepare certificates, keys and provisioning profiles
match(type: "appstore", force_for_new_devices: true, readonly: false) # creates certificates if needed
```

travis.yml:
```yml
language: objective-c
xcode_workspace: myApp/myApp.xcworkspace
xcode_scheme: testApp
osx_image: xcode8
xcode_sdk: iphonesimulator10.0
before_install:
- brew update
- brew outdated homebrew/versions/node4-lts || brew install homebrew/versions/node4-lts
- gem update fastlane
# Force bundler 1.12.5 because version 1.13 has issues, see https://github.com/fastlane/fastlane/issues/6065#issuecomment-246044617
- gem uninstall bundler -v '>1.12.5' --force || echo "bundler >1.12.5 is not installed"
- gem install bundler -v 1.12.5 --no-rdoc --no-ri --no-document --quiet
env:
    global:
        - secure: XXX # encrypted value is: FASTLANE_PASSWORD=my-passoword
script:
- cd myApp/ && ./fastlane/travis.sh
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
NO, i just run `fastlane my_lane`
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
Not sure

**Comment by jaroslavas** [comment]
Sorry, the problem was on my side. Everything's ok

**Comment by TKBurner** [comment]
@jaroslavas Awesome! Glad to hear you got up and running. Really happy to have you using _fastlane_.

**Comment by cepages** [comment]
@jaroslavas what was the problem for you, I have the same problem, maybe your solution helps me :)
