### ISSUE TITLE
Update provisioning profile import for Sierra

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#6387]
The error message

> security: SecPolicySetValue: One or more parameters passed to a function were not valid.

is shown for the command

```
security cms -D -i "#{path}"
```

however the command seems to be valid according to the documentation, and works as expected. We need to ignore the error message, as a fellow other project does (https://github.com/DanTheMan827/ios-app-signer/commit/3e4749855f3aab100f8f91ca0d34cf2098976f50)

Related issues:
- https://github.com/fastlane/fastlane/issues/5649
- https://github.com/fastlane/fastlane/issues/6233
- https://github.com/fastlane/fastlane/issues/6151
- https://github.com/fastlane/fastlane/issues/5649

**Comment by ericlewis** [comment]
+1

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/6388

@ericlewis if you have a chance, I'd love to get a +1 on the fix 🚀

**Comment by ericlewis** [comment]
@KrauseFx direct me to the docs necessary to do so an I will.

**Comment by damirjuretic** [comment]
@KrauseFx fix that you have made is not working. 

Message:`security: SecPolicySetValue: One or more parameters passed to a function were not valid.`
Is not piped to STDERR so fix with 2>/dev/null won't work.

A message is piped to STDOUT so the only solution would be analyzing STDOUT and removing the unnecessary message.

**Comment by TKBurner** [comment]
Hi @damirjuretic Can you run `fastlane run update_fastlane` and then share your input and output with this error? Thanks so much!

**Comment by KrauseFx** [comment]
@damirjuretic That's why we're using `2> /dev/null`, so the stderror gets piped there

**Comment by damirjuretic** [comment]
Hi @TKBurner, I have updated fastlane and now is working properly. Thank you @KrauseFx 👍

**Comment by KrauseFx** [comment]
Yeah 🎉
