### ISSUE TITLE
Scan excludes test failures due to assertionFailure from Test Results

### ISSUE THREAD

**Issue by juraj-blahunka** [fastlane/fastlane#6396]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Scan exits with status code 65, but number of failures is 0 when a test fails due to a `assertionFailure`

```
Failing tests:
-[XXXTests testXXX()]
** TEST FAILED **
[01:48:19]: Exit status: 65
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 609   |
| Number of failures | 0     |
+--------------------+-------+
[01:48:29]: Successfully generated report at '/REDACTED/report.html'
[01:48:33]: Successfully generated report at '/REDACTED/report.junit'

[!] Test execution failed. Exit status: 65
```

Generated test reports are all green and don't include failed (`assertionFailure`) tests.

Issue is a follow up of [#3339](https://github.com/fastlane/fastlane/issues/3339)
### Environment

`scan 0.13.0`

**Comment by TKBurner** [comment]
@juraj-blahunka Thanks for reaching out. Can you provide the full input and output as an attachment? I want to take a look and see what's going on here. Thanks!

**Comment by juraj-blahunka** [comment]
Sure, here is an example project with `assertionFailure` in unit tests that is not reported as test failure (so it looks like a passing test, since everything is green in `test_output/report.html`)

[ScanAssertionFailure.zip](https://github.com/fastlane/fastlane/files/515674/ScanAssertionFailure.zip)

**Comment by TKBurner** [comment]
@juraj-blahunka Thanks for providing the sample project. We'll have a look into this and follow up on this thread. Thanks!

**Comment by mfurtak** [comment]
Hi @juraj-blahunka - thanks for the report!

I can reproduce what you are seeing. Thanks for the sample project, that was perfect! :100:

If I look at the test logs when the `assertionFailure()` code gets run, here's what I see

```
Test Suite 'All tests' started at 2016-10-11 17:10:57.142
Test Suite 'ScanAssertionFailureTests.xctest' started at 2016-10-11 17:10:57.143
Test Suite 'ScanAssertionFailureTests' started at 2016-10-11 17:10:57.143
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testSuccessful]' started.
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testSuccessful]' passed (0.001 seconds).
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testThatDoesntGetReported]' started.
fatal error: file /Users/mfurtak/Desktop/ScanAssertionFailure/ScanAssertionFailureTests/ScanAssertionFailureTests.swift, line 11
2016-10-11 17:11:01.218702 ScanAssertionFailure[69723:2987818] subsystem: com.apple.UIKit, category: HIDEventFiltered, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-11 17:11:01.219542 ScanAssertionFailure[69723:2987818] subsystem: com.apple.UIKit, category: HIDEventIncoming, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-11 17:11:01.227454 ScanAssertionFailure[69723:2987817] subsystem: com.apple.BaseBoard, category: MachPort, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
2016-10-11 17:11:01.235337 ScanAssertionFailure[69723:2987814] subsystem: com.apple.UIKit, category: StatusBar, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
2016-10-11 17:11:01.250514 ScanAssertionFailure[69723:2987814] subsystem: com.apple.BackBoardServices.fence, category: App, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0

Restarting after unexpected exit or crash in ScanAssertionFailureTests/testThatDoesntGetReported(); summary will include totals from previous launches.
```

That looks somewhat bad. We don't want the test process to exit or crash because of an assertion, but that's what seems to be happening. When this output then gets handed to `xcpretty` to produce the JUnit report, it doesn't find anything it recognizes as output for the `testThatDoesntGetReported` method.

If I change `testThatDoesntGetReported` to be:

```swift
func testThatDoesntGetReported() {
    XCTAssert(false)
}
```

then the produced test output reads like:

```
Test Suite 'All tests' started at 2016-10-11 17:13:31.050
Test Suite 'ScanAssertionFailureTests.xctest' started at 2016-10-11 17:13:31.050
Test Suite 'ScanAssertionFailureTests' started at 2016-10-11 17:13:31.051
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testSuccessful]' started.
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testSuccessful]' passed (0.002 seconds).
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testThatDoesntGetReported]' started.
/Users/mfurtak/Desktop/ScanAssertionFailure/ScanAssertionFailureTests/ScanAssertionFailureTests.swift:11: error: -[ScanAssertionFailureTests.ScanAssertionFailureTests testThatDoesntGetReported] : XCTAssertTrue failed - 
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testThatDoesntGetReported]' failed (0.013 seconds).
Test Suite 'ScanAssertionFailureTests' failed at 2016-10-11 17:13:31.066.
	 Executed 2 tests, with 1 failure (0 unexpected) in 0.015 (0.015) seconds
```

and the report correctly identifies the failing test.

![image](https://cloud.githubusercontent.com/assets/343134/19289089/07b3740e-8fd7-11e6-9b66-c57ab5f644c3.png)

I don't think you should have to, but do you think you can use `XCTAssert(false)` as a workaround for `assertionFailure()` in the short term?

I'm not an expert, but this problem feels like a combination of `xcodebuild` behavior and `xcpretty` behavior, and I don't know that `scan` really has much to say about it.

@supermarin - do you have any thoughts on this?

**Comment by supermarin** [comment]
Next version of xcpretty will report this as an error (probably html reporter too), but as you can see from the log - there's no test failure that xcpretty could recognize.

```
Test Case '-[ScanAssertionFailureTests.ScanAssertionFailureTests testThatDoesntGetReported]' started.
fatal error: file /Users/mfurtak/Desktop/ScanAssertionFailure/ScanAssertionFailureTests/ScanAssertionFailureTests.swift, line 11
```

**Comment by KrauseFx** [comment]
Thanks for updating the issue here @supermarin, we already bumped the `xcpretty` dependency and will push a new _scan_ release tomorrow morning  🚀
