### ISSUE TITLE
[frameit] iPhone 7 shots

### ISSUE THREAD

**Issue by AdrienCog** [fastlane/fastlane#6398]
frameit is not up to date with new iPhone 7 et iPhone 7 Plus shots. I'm adding a pull request to update the offsets.
Also, it looks like Apple doesn't provide horizontal picture for this model anymore...

**Comment by KrauseFx** [comment]
Thanks for the PR 👍

**Comment by KrauseFx** [comment]
Closed with https://github.com/fastlane/fastlane/pull/6597/ 👍
