### ISSUE TITLE
Pilot: upload changelog without waiting for build to process

### ISSUE THREAD

**Issue by kylejm** [fastlane/fastlane#6427]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I've noticed that you can access the fields in iTunes Connect to submit a changelog (What to Test) before the build has finished processing. Can Pilot fill this field in without waiting for the build to process? The docs say:

```
-z, --skip_waiting_for_build_processing [VALUE] Don't wait for the build to process. If set to true, the changelog won't be set (PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING) 
```

Perhaps something has changed in the iTC API since?

Is Pilot capable of filling in the _Beta App Description_ field too?

Many thanks! ❤️ Fastlane!
### Environment

fastlane version (run `fastlane -v`):
1.104.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
@kylejm Very interesting. I think the processing times have increased a lot so it would surprise me if this has changed. Any chance you'd be interested in submitting a PR? Thanks!

**Comment by kylejm** [comment]
I'd love to explore making a PR, but I'm in the build up to a major release at my company. I'll be happy to come back to this in about a month if it still needs implementing by then. Setting a reminder in my inbox 😊.

**Comment by TKBurner** [comment]
@kylejm Awesome Kyle! We'll leave this open for you. Let us know what you find out if you get a chance to tinker with the API. Thanks!

**Comment by kylejm** [comment]
Got a moment to play around this morning. Here's where I got to:

### Uploading to iTC with fastlane without waiting for build to process to submit a changelog

1. Upload using `pilot` without waiting for processing
2. Get build from spaceship:
    1. login using spaceship
    2. get the app using the bundle id
    3. get the build train for the version you’re building (`app.build_trains["0.9.21”]`)
    4. get the specific build you want (`build = train.builds.first` is supposed to work, but when I tested the first build in the `builds` array wasn’t the latest build, it happened to be the second build in the array)
3. use the def update_build_information!(whats_new: nil, description: nil,  feedback_email: nil) function on Build.rb to upload a new changelot to the “What to test” field - tested on an already processed build and worked great. Need to test on a non-tested build

TODOs:
- Work out how to find the latest build in the build train. Pilot must do this correctly to know which one to submit, so perhaps look there.


Will play again later!

**Comment by kylejm** [comment]
Okay, I was able to upload the changelog using `spaceship` before the build had finished processing, but, but it failed (`ITC.response.error.BUILD_NOT_FOUND`) the first few moments after the build had been uploaded. Used the following code:

```ruby
train = app.build_trains[upcoming]
build = train.builds.first
build.update_build_information!(whats_new: changelog_string, description: nil,  feedback_email: nil)
```

I noticed that the call worked after two events:
1. I viewed the build in iTC
2. The following fields in the `build` attributes had changed:
    - `id`- went from `0` to an 8 digit number
    - `valid` - went from false to true
    - `icon_url` - went from nil to a value
    - `app_name` - went from nil to a value
    - `upload_date` - changed, which is odd

I suggest that `pilot` waits for `id` to be non-0 and `valid` to be true to upload the changelog, rather than waiting for `processing` to finish.

@TKBurner @KrauseFx thoughts? Any guidance you could offer? From my experience with this it could shave 80% time off when waiting to submit `changelog`.

**Comment by KrauseFx** [comment]
@kylejm this looks awesome, thanks for sharing your findings. I'd love it if _pilot_ didn't have to wait for minutes for the build to process before setting the changelog. 

Check out what values _pilot_ is currently setting after processing, and see if we can set all those values before already.

Distributing the build to beta testers still requires the build to be finished processing, right?

**Comment by TKBurner** [comment]
@kylejm I think this is the sort of change we'd like to see so if you are interested in submitting a PR based on your observation about id changes that could be great. Thanks!

**Comment by kylejm** [comment]
Sorry for slow response, busy preparing 2.0 release at work.

@KrauseFx I'd imagine you'll have to wait to submit still, yes. Okay cool, I'll take a look when I can :)

**Comment by kylejm** [comment]
@KrauseFx how/where do you mark OSS issues/tasks to come back to later? Just add them to a task management tool (reminders, Trello), or do you have some neater way?
