### ISSUE TITLE
Spaceship gem does not seem to be handling PENDING_DEVELOPER_RELEASE app status

### ISSUE THREAD

**Issue by patternpaul** [fastlane/fastlane#6430]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

spaceship (0.34.2)
Spaceship gem does not seem to be handling PENDING_DEVELOPER_RELEASE app status.

![image](https://cloud.githubusercontent.com/assets/3682501/19156007/031e52cc-8ba6-11e6-842d-d2963ea7deb8.png)

Example against the above app

``` ruby
require 'spaceship'
task :example_call do
  Spaceship::Tunes.login(ENV['USERNAME'], ENV['PASSWORD'])
  app = Spaceship::Tunes::Application.find(ENV['APP_ID'])
  puts app.edit_version.app_status
end
```

Will return nil. If I mod my local spaceship gem's app_status to include

``` ruby
'pendingDeveloperRelease' => PENDING_DEVELOPER_RELEASE
```

I get the correct return.
##### Complete output when running fastlane, including the stack trace and command used

```
rake example_call

```

With hacked local changes

```
rake example_call
Pending Developer Release
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:
N/A. Here is the contents of my rake task using the spaceship gem
Rakefile:

``` ruby
require 'spaceship'
task :example_call do
  Spaceship::Tunes.login(ENV['USERNAME'], ENV['PASSWORD'])
  app = Spaceship::Tunes::Application.find(ENV['APP_ID'])
  puts app.edit_version.app_status
end
```
### Environment

fastlane version (run `fastlane -v`): n/a -> spaceship (0.34.2)

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

Feel free to ping me for more details! I have the fix ready to roll:
https://github.com/patternpaul/fastlane/tree/app_version_fix

Hacktoberfest!

**Comment by TKBurner** [comment]
@patternpaul Can you submit a PR for this? That seems like a viable issue and we'd love to see it fixed. Thanks so much 💯 💯

**Comment by patternpaul** [comment]
My PR should have closed this issue. I'll close er' now.
