### ISSUE TITLE
Gym should include more error detail with Check Dependencies error 65

### ISSUE THREAD

**Issue by gcamp** [fastlane/fastlane#6431]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I've been having a code sign issue that was really hard to debug with fastlane. There's multiple issue about this here. Output when using gym looks like this : 

```
▸ Check Dependencies
** ARCHIVE FAILED **


The following build commands failed:
Check dependencies
(1 failure)
[10:55:25]: Exit status: 65
```

So it was basically trial and error until finding the problem. However, when I copied the xcodebuild command and ran it manually, I got a nice and clear error of what was going on : 

```
=== BUILD TARGET Transit Watch Extension OF PROJECT Transit WITH CONFIGURATION Release ===

Check dependencies
Provisioning profile "" doesn't include signing certificate "iPhone Developer: iOS Devs ()".
Provisioning profile "" belongs to team "", which does not match the selected team "".
Code signing is required for product type 'WatchKit Extension' in SDK 'watchOS 3.0'
```

Wow, that's better! 

The code signing guide tells to try to build in Xcode to find that kind of error. It works in most case but in my case I change some of the environment in the gym command so I couldn't reproduce in Xcode itself. 
### Environment

fastlane version (run `fastlane -v`): fastlane 1.105.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rbenv

**Comment by gcamp** [comment]
Yep, it was! 

Actually thinking more about this, maybe this should be a xcpretty issue?

**Comment by KrauseFx** [comment]
Nice catch, I completely agree. Yeah, that could be improved on `xcpretty` 👍
