### ISSUE TITLE
[gym] Add option to -parallelizeTargets

### ISSUE THREAD

**Issue by radex** [fastlane/fastlane#6432]
It generally makes sense to pass `-parallelizeTargets -jobs 4` (and play with the jobs number) to xcodebuild to speed up the compilation. In my tests, it could often speed up the build part by 30%.

I think there should be an easy flag you can pass to gym (without going through `xcargs`) to set this.

I also think it probably makes sense to make this a default.

**Comment by KrauseFx** [comment]
Thanks for the suggestion. Do you think this has any side effects? Why isn't this default of `xcodebuild` itself?

**Comment by radex** [comment]
I haven't investigated it deeply enough to say, but I suppose one effect is that the logs might become messy, as multiple threads write to it…

**Comment by TKBurner** [comment]
@radex Thanks for following up. If you are interested in looking into this more, we'd love to see some work toward it. Start with Felix's questions. If logs are really the only change, I think this is acceptable as an option. Thanks!

**Comment by radex** [comment]
Good to hear! No promises I'll tackle it soon, but I very well might on the next good occasion when I'm working on my build setup ;)
