### ISSUE TITLE
Cannot update deliver on sierra

### ISSUE THREAD

**Issue by rogomantik** [fastlane/fastlane#6457]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Cannot update / install

```
$ sudo gem install deliver
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/fastlane-credentials

$ sudo gem update
Password:
Updating installed gems
Updating activesupport
ERROR:  Error installing activesupport:
	activesupport requires Ruby version >= 2.2.2.
Updating credentials_manager
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/fastlane-credentials
```

### Environment

-bash: fastlane: command not found
deliver 1.13.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by TKBurner** [comment]
Hi @rogomantik What happens if you run `fastlane run update_fastlane`

Let me know if that fixes things for you. Are you using RVM? I'd suggest that since it lets you manage your rubies without using sudo. Thanks!

**Comment by rogomantik** [comment]
I don't have fastlane installed, only deliver

> $ fastlane run update_fastlane
> -bash: fastlane: command not found

If I dont use sudo i get

> $ gem install deliver
> Fetching: credentials_manager-0.16.2.gem (100%)
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I cannot update gem too

> $ sudo gem update --system
> Updating rubygems-update
> ERROR:  While executing gem ... (Errno::EPERM)
>     Operation not permitted - /usr/bin/update_rubygems
> $ gem update --system
> Updating rubygems-update
> Fetching: rubygems-update-2.6.7.gem (100%)
> ERROR:  While executing gem ... (Gem::FilePermissionError)
>     You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory.

I think is something related to the sierra update

**Comment by TKBurner** [comment]
Hi @rogomantik Can you run ruby -v? It looks like you need to update your ruby version. You might need to install rvm to do this. Thanks!

**Comment by rogomantik** [comment]
> $  ruby -v
> ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

Tried to upload data to itunes connect (the screenshots are correctly sized)

> Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
> 
> [!] The request could not be completed because:
> 	In order to save your changes, all iPad Pro screenshots must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all iPad Pro screenshots must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all iPad Pro screenshots must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all Screenshots for 5.5-Inchs must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all Screenshots for 5.5-Inchs must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all Screenshots for 5.5-Inchs must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all Screenshots for 5.5-Inchs must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all iPad Pro screenshots must be a .jpeg, .jpg, or .png file that is 2732x2048 or 2048x2732 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all Screenshots for 5.5-Inchs must be a .jpeg, .jpg, or .png file that is 2208x1242 or 1242x2208 pixels, at least 72 DPI, and in the RGB color space.
> 
> #######################################################################
> # deliver 1.14.2 is available. You are on 1.13.3.
> # It is recommended to use the latest version.
> # Update using 'sudo gem update deliver'.
> #######################################################################
> 
> 1.14.2 Improvements
> * Show information that we just skip screenshots if we have too many (#6446)
> * Update team selection and documentation across all fastlane actions (#6444)
> * Updated spaceship dependency for improved team selection
> 
> 1.14.1 Hot fix for saving images
> * Show language next to screenshot download (#6424)
> 
> * Fix upload of image assets to iTunes Connect (#6423)
> 
> 1.14.0 Add support for Stickers app category
> * Fix Sticker category by adding correct Apps prefix (#6257)
> * Update internal dependencies (#6104)

**Comment by TKBurner** [comment]
Hi @rogomantik Thanks for following up. Can you try installing ruby 2.3+? That should clear this up.

**Comment by KrauseFx** [comment]
@rogomantik You're using an outdated version of deliver, as shown in your output

> deliver 1.14.2 is available. You are on 1.13.3.

**Comment by KrauseFx** [comment]
Please update to the latest release
