### ISSUE TITLE
Promo code generation

### ISSUE THREAD

**Issue by Draknek** [fastlane/fastlane#6469]
This used to be possible: https://github.com/fastlane-old/codes but that repository now has the message "This tool is no longer maintained and does not work."

Is it now no longer possible to automate? Or is it still technically doable if someone writes the code?

Thanks for your time :)

**Comment by KrauseFx** [comment]
Thanks for submitting this issue. The tool was hardly used, and it wasn't worth the time updating it to work with the new iTunes Connect.
