### ISSUE TITLE
Support for Universal Purchases in Pilot/Spaceship/Deliver/Fastlane

### ISSUE THREAD

**Issue by dombarnes** [fastlane/fastlane#6480]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Currently, managing builds for apps with a Universal Purchase (iOS app and tvOS app using the same bundle ID) causes a number of conflicting results during use.
#### Setup

Parent folder has two sub-project folders, one for iOS app, one for tvOS app (named AppName and AppNameTVOS). Both share the same bundle ID, and so are both installable once one is purchased. Each project outputs its own independent IPA file, has its own TestFlight management, and has its own screenshots. Each project has its own fastlane directory, with screenshots, meta data. etc. 
#### Sample Fastfile

```
lane :beta do  
    ensure_git_branch(  
      branch: 'develop'  
      )  
    cocoapods    
    increment_build_number({  
      build_number:  latest_testflight_build_number({  
        initial_build_number:  get_build_number(  
          xcodeproj: 'TrilbyTVPlayerTVOS.xcodeproj'  
        ).to_i  
      }) + 1  
        })  
    gym(  
      scheme: "TrilbyTV Player",   
      workspace: "TrilbyTVPlayerTVOS.xcworkspace",   
      clean: true  
    )  
    # TODO: snapshot  
    sigh  
    pilot(  
      skip_submission: false,   
      distribute_external: false  
      )  
```

**Issues**
1. latest_testflight_build_number returns build number of iOS app, not tvOS when inside tvOS project folder
In my instance, the latest tvOS testflight build number is 10. It returns 124 based on my iOS app.
2. agvtool fails to update Info.plist's
I understand this isn't a fastlane issue, just noting it. Incorrect build number passed to agvtool though.

```
agvtool new-version -all 124
Setting version of project TrilbyTVPlayerTVOS to:
    124. 
Also setting CFBundleVersion key (assuming it exists)
Updating CFBundleVersion in Info.plist(s)...
$(SRCROOT)/TrilbyTVPlayerTVOS/TrilbyTVPlayer-Info.plist
Cannot find "$(SRCROOT)/TrilbyTVPlayerTVOS/TrilbyTVPlayer-Info.plist"
$(SRCROOT)/TrilbyTVPlayerTVOS/TrilbyTVPlayerDev-Info.plist
Cannot find "$(SRCROOT)/TrilbyTVPlayerTVOS/TrilbyTVPlayerDev-Info.plist"
```

This file does exist as its defined in Xcode and app compiles.

Suggestion would be to implement a platform :tvos in the Fastfile to be able to define these settings to the App.
### Configuration Files

See above
### Environment

fastlane version (run `fastlane -v`): 
1.105.0  
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
No  
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?  
rbenv

**Comment by TKBurner** [comment]
@dombarnes Thanks for reaching out. We'd love to see a PR to improve performance around TVos. Do other actions face a similar problem or just latest_testflight_build_number. What happens if you have two separate folders completely?

I'm trying to figure out if the issue is local or at the API level. Thanks!

**Comment by dombarnes** [comment]
I did some playing with Spaceship and it didn't seem to return any different data where I have a linked tvOS app, only the iOS app data. Not sure if it's API level or not but I'll dig around the code and test with my account and see what I can discover and feed back. 

In my mind there could be a 'platform :tvos' definition in the fastfile to set the preference. Or at least separate activity. TvOS apps have slightly different metadata requirements and don't support Watch, iMessage stuff, etc. 
I guess that would be up for discussion with the maintainers on best way forward to support this.

**Comment by TKBurner** [comment]
@dombarnes Thanks! Can you think of a smaller chunk of work you can take on toward this so we can start working with you on a PR? Hope you are having a great week!

**Comment by dombarnes** [comment]
I've started some work on this. See https://github.com/dombarnes/fastlane/tree/universal-purchase

This adds some basic support for a few actions I am able to test with.

**Comment by TKBurner** [comment]
@dombarnes Awesome! We'll leave this open 👍

**Comment by dombarnes** [comment]
I'd be grateful of a review of https://github.com/fastlane/fastlane/compare/master...dombarnes:universal-purchase
I can't seem to run `bundle exec rspec` - running from the root just does simplecov, running from fastlane_core returns `NameError: uninitialized constant FastlaneCore`

**Comment by dombarnes** [comment]
It looks like some support for `appletvos` platform has been added to tools, but isn't part of `lib/fastlane/supported_platforms.rb` so fastlane fails during validity checking of the Fastfile
