### ISSUE TITLE
S3 upload action builds invalid URL when region is us-east-1

### ISSUE THREAD

**Issue by lyricsboy** [fastlane/fastlane#6481]
### Issue Description

The `s3` action has a hard-coded mechanism for determining the domain for the URL it generates for the installation plist file. It assumes that if you have a region configured, it should append that region name to the subdomain, e.g. `s3-us-east-1.amazonaws.com` for a region of `us-east-1`.

This is a problem because the domain above is not valid, and the correct value is `s3.amazonaws.com`.

The issue can be resolved by using the AWS SDK's internal ability to generate a valid hostname, as this pull request implements:

https://github.com/fastlane/fastlane/pull/6344

Creating this issue post-hoc to ensure that it gets noticed :)

**Comment by TKBurner** [comment]
@lyricsboy Thanks for the contribution. We'll work with you there. It sounds like this is a verifiable issue. Thanks!
