### ISSUE TITLE
commit_version_bump settings doesn't read SRC_ROOT

### ISSUE THREAD

**Issue by dombarnes** [fastlane/fastlane#6482]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When using the param `settings: true` in a fastfile, it does not appear to include ${SRC_ROOT} from Xcode in the file path, so fails to locate if this is not in the root of the git repo
See [commit_version_bump.rb#L94](https://github.com/fastlane/fastlane/blob/6769d5c930d292bf31ab4be9ec80a7c7ccd30899/fastlane/lib/fastlane/actions/commit_version_bump.rb#L94)
##### Complete output when running fastlane, including the stack trace and command used

Note: /Users/domster83/workprojects/TrilbyTV-iOS/TrilbyTVPlayer is my Xcode project root.

```
[16:55:32]: fastlane finished with errors

[!] Exit status of command 'git add /Users/domster83/workprojects/TrilbyTV-iOS/TrilbyTVPlayer/TrilbyTVPlayer.xcodeproj/project.pbxproj /Users/domster83/workprojects/TrilbyTV-iOS/TrilbyTVPlayer/TrilbyTVPlayer/TrilbyTVPlayer-Info.plist /Users/domster83/workprojects/TrilbyTV-iOS/TrilbyTVPlayer/TrilbyTVPlayer/TrilbyTVPlayer-Dev-Info.plist /Users/domster83/workprojects/TrilbyTV-iOS/Settings.bundle/Root.plist' was 128 instead of 0.
fatal: pathspec '/Users/domster83/workprojects/TrilbyTV-iOS/Settings.bundle/Root.plist' did not match any files
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
ommit_version_bump(
      message: "Deploying version #{friendly_version}.",
      xcodeproj: 'TrilbyTVPlayer.xcodeproj',
      force: true,
      settings: true
    )
```
### Environment

fastlane version (run `fastlane -v`):
1.105.0
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv

**Comment by TKBurner** [comment]
@dombarnes Thanks for reaching out about this and sorry to hear that you are running into this. Which folder are you running fastlane from? Thanks!

**Comment by dombarnes** [comment]
In my case, I'm running it inside /Users/domster83/workprojects/TrilbyTV-iOS/TrilbyTVPlayer, which contains the entire Xcode project, as well as fastlane/

The root of my git repo is /Users/domster83/workprojects/TrilbyTV-iOS

**Comment by TKBurner** [comment]
@dombarnes Can you provide a sample project with a fastfile and repro steps? This seems reproducible and I want to send this out to the core team. Thanks!
