### ISSUE TITLE
Snapshot hangs on certain screens (have logs)

### ISSUE THREAD

**Issue by tinder-ayu** [fastlane/fastlane#6488]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Using latest snapshot ruby gem and snapshotHelper2-3.swift
Snapshot randomly hangs on a screen(its the same screen every time), without manual intervention, it will not proceed or fail. 
##### Complete output when running fastlane, including the stack trace and command used

```
/usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/syntax.rb:24:in `highlight_with_formatter': undefined method `include?' for nil:NilClass (NoMethodError)
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/syntax.rb:15:in `highlight'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:171:in `format_failure'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:157:in `block (2 levels) in format_failures'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:156:in `map'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:156:in `block in format_failures'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `each'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `map'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:155:in `format_failures'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:101:in `format_test_summary'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:563:in `format_summary_if_needed'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:336:in `parse'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/lib/xcpretty/printer.rb:19:in `pretty_print'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:84:in `block in <top (required)>'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `each_line'
from /usr/local/lib/ruby/gems/2.3.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `<top (required)>'
from /usr/local/bin/xcpretty:22:in `load'
from /usr/local/bin/xcpretty:22:in `<main>'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`): 
I only use snapshot alone and im using snapshot 1.16.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by TKBurner** [comment]
@tinder-ayu Hope you are doing well! Can you provide your snapfile? It looks like this might be an issue with the way you are navigating your app. Thanks!

**Comment by tinder-ayu** [comment]
@TKBurner here is my snapfile:

# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
# devices([
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 5",
#   "iPhone 4s",
#   "iPad Retina",
#   "iPad Pro"
# ])

 devices([
   "iPhone 6s"
 ])

#languages([
#  "en-US",
#  "de-DE",
#  "it-IT",
#  ["pt", "pt_BR"] # Portuguese with Brazilian locale
#])

languages([
 # "en-US",
 # "zh-Hant",
  "en",
  "es",
  "fr",
  "pt",
  "zh-Hans"
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

# The name of the scheme which contains the UI Tests
# scheme "SchemeName"
scheme "Tinder SnapshotTests"

# Where should the resulting screenshots be stored?
# output_directory "./screenshots"

# clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
# workspace "./Project.xcworkspace"

# For more information about all available options run
# snapshot --help

**Comment by TKBurner** [comment]
@tinder-ayu Thanks for following up. Can you share the full input and output of snapshot? I want to take a look at where it gets this error. Thanks so much!

**Comment by tinder-ayu** [comment]
@TKBurner can't you debug from what i uploaded, full log is over megabytes long, and i dont always get this error. this makes my testcase hang from time to time

**Comment by TKBurner** [comment]
@tinder-ayu Can you share the 50 or so lines before and after the crash? Thanks!

**Comment by KrauseFx** [comment]
Hey @tinder-ayu, sorry for not coming back earlier. Could you try updating to the latest _fastlane_ release and with it to the new xcpretty? Let us know if that works for you 👍
