### ISSUE TITLE
Missing Features on Fastlane for Android

### ISSUE THREAD

**Issue by matteo-harpoon** [fastlane/fastlane#6500]
Hi guys,
I've worked with Fastlane for iOS until last week and today I'm starting a similar project to upload and update our Android App.

I've noticed the following missing features on Fastlane for Andorid, I don't know if all of them or even one is possible but I'd like to give my support by showing you the differences between Fastlane for iOS and Android:
- [ ] Create Google Play Store App (on iOS I can easily create the app in case isn't available)
- [ ] Allow first-time upload of an APK (right now I need to upload an APK to Google Play Store to utilize supply)
- [ ] Keystore management (similar to pem for iOS)
- [ ] Setup Closed Beta Testing (select type, upload/edit list)
- [ ] Setup Open Beta Testing (Maximum number of testers, Feedback channel and return Opt-in URL)
- [ ] Setup Closed Alpha Testing (select type, upload/edit list)
- [ ] Setup Open Alpha Testing (Maximum number of testers, Feedback channel and return Opt-in URL)

**Comment by TKBurner** [comment]
@matteo-harpoon Thanks for reaching out. I sent this around to the core team to see if we can get some thoughts on your suggestions and maybe even some action. Would you be interested in submitting PRs for any of these? Thanks!

**Comment by KrauseFx** [comment]
You mentioned that in https://github.com/fastlane/fastlane/issues/169#issuecomment-252903183, I replied here https://github.com/fastlane/fastlane/issues/169#issuecomment-252964458, most of those things are not possible due to API limitations.
