### ISSUE TITLE
[supply] rollout option ingored when promoting to track "rollout"

### ISSUE THREAD

**Issue by belawaeckerlig** [fastlane/fastlane#6501]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I would like to move an APK from the alpha or beta track to the staged rollout track, but the Google API always returns that the user fraction must be greater than 0.0 and less than 1.0.

As far as I could see in the source code (supply/uploader.rb line 39) when passing the "promote_to" option, the `update_track` method is always called with 1.0 for the user fraction. So setting the rollout option has no effect and the default value is not working, because it can not be 1.0

##### Complete output when running fastlane, including the stack trace and command used

```
[bela@localhost common]$ fastlane changeTrack current:alpha target:rollout rollout:0.1 --verbose
DEBUG [2016-10-11 14:55:03.29]: Checking if there are any plugins that should be loaded...
DEBUG [2016-10-11 14:55:03.30]: Using current: alpha
DEBUG [2016-10-11 14:55:03.30]: Using target: rollout
DEBUG [2016-10-11 14:55:03.31]: Using rollout: 0.1
INFO [2016-10-11 14:55:03.32]: -------------------------------------------------
INFO [2016-10-11 14:55:03.32]: --- Step: Verifying required fastlane version ---
INFO [2016-10-11 14:55:03.32]: -------------------------------------------------
INFO [2016-10-11 14:55:03.32]: Your fastlane version 1.105.1 matches the minimum requirement of 1.105.0  ✅
INFO [2016-10-11 14:55:03.32]: ------------------------------
INFO [2016-10-11 14:55:03.32]: --- Step: default_platform ---
INFO [2016-10-11 14:55:03.32]: ------------------------------
INFO [2016-10-11 14:55:03.34]: Driving the lane 'android changeTrack' 🚀
INFO [2016-10-11 14:55:03.34]: --------------------
INFO [2016-10-11 14:55:03.34]: --- Step: supply ---
INFO [2016-10-11 14:55:03.34]: --------------------

+-------------------------+-----------------------------+
|               Summary for supply 0.7.1                |
+-------------------------+-----------------------------+
| track                   | alpha                       |
| track_promote_to        | rollout                     |
| skip_upload_apk         | true                        |
| skip_upload_metadata    | true                        |
| skip_upload_images      | true                        |
| skip_upload_screenshots | true                        |
| rollout                 | 0.1                         |
| package_name            | com.avira.common.test.app   |
| metadata_path           | ./fastlane/metadata/android |
| key                     | key.p12                     |
| json_key                | ./fastlane/key.json         |
+-------------------------+-----------------------------+

DEBUG [2016-10-11 14:55:03.68]: Fetching a new access token from Google...
INFO [2016-10-11 14:55:04.52]: Preparing to upload for language 'en-US'...
WARN [2016-10-11 14:55:05.15]: Variable Dump:
INFO [2016-10-11 14:55:05.15]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android changeTrack"}
ERROR [2016-10-11 14:55:05.15]: Google Api Error: trackEmpty: Track not found: no APK version codes in the specified track.
INFO [2016-10-11 14:55:05.15]: Successfully generated documentation at path '/home/bela/projects/common/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | supply                              | 1           |
+------+-------------------------------------+-------------+

ERROR [2016-10-11 14:55:05.16]: fastlane finished with errors
/usr/local/share/gems/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Google Api Error: trackEmpty: Track not found: no APK version codes in the specified track. (FastlaneCore::Interface::FastlaneError)
	from /usr/local/share/gems/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/share/gems/gems/supply-0.7.1/lib/supply/client.rb:334:in `rescue in call_google_api'
	from /usr/local/share/gems/gems/supply-0.7.1/lib/supply/client.rb:332:in `call_google_api'
	from /usr/local/share/gems/gems/supply-0.7.1/lib/supply/client.rb:232:in `track_version_codes'
	from /usr/local/share/gems/gems/supply-0.7.1/lib/supply/uploader.rb:36:in `promote_track'
	from /usr/local/share/gems/gems/supply-0.7.1/lib/supply/uploader.rb:28:in `perform_upload'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/actions/supply.rb:20:in `run'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:186:in `chdir'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:186:in `execute_action'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:81:in `block (2 levels) in parsing_binding'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/commands_generator.rb:49:in `block (2 levels) in run'
	from /usr/local/share/gems/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/share/gems/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/share/gems/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/share/gems/gems/fastlane_core-0.52.1/lib/fastlane_core/ui/fastlane_runner.rb:36:in `run!'
	from /usr/local/share/gems/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/commands_generator.rb:244:in `run'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/commands_generator.rb:20:in `start'
	from /usr/local/share/gems/gems/fastlane-1.105.1/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/share/gems/gems/fastlane-1.105.1/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end
  
  desc %Q(
Performs a release build and uploads it to the Alpha channel in Google play.
  )
  lane :publishAlpha do
    gradle(task: "clean")
    gradle(task: "increaseVersion")
    gradle(task: "assembleRelease")
    gradle(task: "commitVersion")
    supply(
      track: "alpha"
    )
  end
  
  desc %Q(
Performs a release build and uploads it to the Beta channel in Google play.
  )
  lane :publishBeta do
    gradle(task: "clean")
    gradle(task: "increaseVersion")
    gradle(task: "assembleRelease")
    gradle(task: "commitVersion")
    supply(
      track: "beta"
    )
  end
  
  desc %Q(
Performs a release build and uploads it to the Production channel in Google play.
  )
  lane :publishProd do
    gradle(task: "clean")
    gradle(task: "increaseVersion")
    gradle(task: "assembleRelease")
    gradle(task: "commitVersion")
    supply
  end
  
  desc %Q(
Moves an APK from one track to another.

Options:
* **current:** The current track of the apk to move.
* **target:** The target track.
* **rollout:** Set this only in case you want to switch to rollout track
  )
  lane :changeTrack do |options|
    if options[:current] and options[:target]
      supplyOptions = {}
      supplyOptions[:track] = options[:current]
      supplyOptions[:track_promote_to] = options[:target]
      supplyOptions[:skip_upload_apk] = true
      supplyOptions[:skip_upload_metadata] = true
      supplyOptions[:skip_upload_images] = true
      supplyOptions[:skip_upload_screenshots] = true
      if options[:target] == "rollout" and options[:rollout]
        supplyOptions[:rollout] = options[:rollout]
      end
      
      supply(supplyOptions)
    else
      UI.error "Please provide the current and the target track as options!"
    end
  end

  # desc "Runs all the tests"
  # lane :test do
  #   gradle(task: "test")
  # end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
  #   gradle(task: "assembleRelease")
  #   crashlytics

  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here
  # end

  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "assembleRelease")
  #   supply
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer

```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.105.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no

**Comment by belawaeckerlig** [comment]
I created a pull request for the issue, but there is another issue:
when I want to increase the user fraction I set both, the `track` and the `promote_to` option, to "rollout" and the `rollout` option to the desired value. But then I will get again the API response, that the user fraction needs to be grater than 0.0 and less than 1.0. but in line 37 (supply/uploader.rb) it is again hardcoded to 1.0. I haven't touched it in the pull request, because I was not sure what would be an appropriate value to pass there. Passing the `Supply.config[:rollout]` does not seem to be a good solution even thou as far as I could see this call is only used to clear the old track.
But to make a change of the user fraction possible, one of the supported user fraction values should be passed

**Comment by TKBurner** [comment]
@belawaeckerlig Can you bring this up on your PR as well? I want to make sure we work with you and get the best solution out the door as fast as possible. Thanks!

**Comment by asfalcone** [comment]
Thanks for raising this issue and opening the PR. I think your PR is a good idea and I can see why you'd want that functionality but I am more concerned about the fact that user fraction can't be 1.0! I wonder if this is a regression on the google API side or if this has never worked in _supply_.

Promoting from `alpha` to `beta` for 100% of people should be possible, so it is strange to get an error from google about that.  Have you tried removing the roll out percentage all together for the default behavior?

@sschendel introduced the promote to track feature, so he might have some ideas.

**Comment by belawaeckerlig** [comment]
@TKBurner I could bring it up in my PR as well, but still not sure what would be a good value there. actually the value shouldn't matter since the API call should only clear the version codes for this track. So I will edit my PR to pass 0.1 here, since it should be ignored by the Google Play API anyway.

@asfalcone This is no regression. The staged rollout track only allows a few values, something like 0.005, 0.05, 0.5, 0.1, 0.2, 0.5 and that's it. Not sure whether these are the correct values. Additionally, 1.0 user fraction on the staged rollout would make no sense, because that would equal the production track ;)

**Comment by belawaeckerlig** [comment]
maybe it would also make sense to change the default value of the rollout option to 0.1 or 0.5. right now the default value is 1.0 but as this is no valid value it seems to be a bad choice

**Comment by sschendel** [comment]
@belawaeckerlig Your PR makes sense.  I have never used the rollout track Play feature.  The hardcoded value of 1.0 was used to express 100% of users should be updated (the effect of using tracks other than rollout).  Perhaps a check could be added to not allow track option `rollout` when option promote_to is also included?  I'm not sure it makes sense to promote from `rollout`.

**Comment by belawaeckerlig** [comment]
@sschendel I tmakes totally sense to promote from track `rollout` to track `rollout` but with an increased `rollout` value :D that sounds confusing I know. But this is useful if you would like to increase the staged roll-out, so for example for the first day you want to set it to 10% and the next day if everything is fine, you want to increase it to 20% etc.

And just for clarification a small explanation of the tracks:
There are 4 tracks available.

1. alpha: an APK uploaded to this track will be available to all alpha testers
2. beta: an APK uploaded to this track will be available to all beta testers
3. production: an APK uploaded to this track will be available to all users
4. staged roll-out (called "rollout" in supply): like the production track, but it will only be available for limited amount of users (specified by the user fraction value, which equals the `rollout` option of supply)

So the `rollout` option will only have an effect if an APK is uploaded to the staged roll-out track and will be ignored by all other tracks. It is not possible to say only 20% of the alpha testers should be able to get the APK.

So if I'm not completely misunderstanding the `rollout` option of supply, it makes no sense to give it the default value of 100%, since the `rollout` options equals the "user fraction" value of the staged roll-out track, which can only have values between 5%-50%

**Comment by sschendel** [comment]
@belawaeckerlig I see what you are saying w.r.t. promoting from track `rollout` (i.e. staged roll-out track) to track `rollout`.  The supply option `rollout` perhaps would be better named `user_fraction`.  Using default 1.0 was a bad choice, since it is an invalid value when using the staged roll-out track.  I used it because - as you describe in your clarification of tracks - options 1, 2, and 3 above effect 100% of users and I was just describing my intent - knowing in my case - the value was completely moot.  Poor choice.  Glad you're changing it.  :) Like I said, I never use the feature.

**Comment by belawaeckerlig** [comment]
ok, then I will change the default value in the PR as well. But I'm not sure when I will have time to do it, I hope at the beginning of next week ;)

Regarding the name of the `rollout` option, should I create a new `user_fraction` option and deprecate the old one or how do you handle such changes to ensure backwards compatibility? Or should I not change it at all?

**Comment by asfalcone** [comment]
@belawaeckerlig I'd prefer not to change the `rollout` option. Can you give it a better description so that its purpose is more clear?

Thanks for the great discussion on this change @belawaeckerlig and @sschendel! You're both awesome ❤️  I'm looking forward to reviewing #6502, please @ me on that PR when it is complete!
