### ISSUE TITLE
How to set project path?

### ISSUE THREAD

**Issue by yogiben** [fastlane/fastlane#6516]
[x] updated
[x] read contribution guideline

Running `fastlane beta` prompts:

`Couldn't automatically detect the project file, please provide a path:`

What's the correct way to set the project file to avoid this prompt?

**Comment by lyndsey-ferguson** [comment]
What have you already tried? What does your Fastfile look like?

**Comment by TKBurner** [comment]
@yogiben GYM_PROJECT enviromental variable will set this. Let me know how it goes!

**Comment by Firfi** [comment]
Settings ENV["GYM_PROJECT"] in Fastfile works for me as a workaround.

**Comment by honghaoz** [comment]
We also met this issue.
The problem is the current working directory is changed to parent directory after `update_project_provisioning` action.

Here is related fastlane code:
```ruby
    puts "Current working directory before: #{Dir.pwd}"

    update_project_provisioning(
      xcodeproj: proj_xcodeproj_file,
      profile: "#{bundle_id}.mobileprovision",
      target_filter: target
    )

    puts "Current working directory after: #{Dir.pwd}"
```

The output is 
```
Current working directory before: PROJECT_DIR/fastlane

-----------------------------------------
--- Step: update_project_provisioning ---
-----------------------------------------
You’re updating provisioning profiles directly in your project, but have you considered easier ways to do code signing?
https://docs.fastlane.tools/codesigning/GettingStarted/
Parsing mobile provisioning profile from 'com.thescore.esports.mobileprovision'
Going to update project 'PROJECTNAME.xcodeproj' with UUID
Updating target PROJECTNAME...
Updating configuration Debug...
Updating configuration Ad-Hoc...
Skipping target PROJECTNAMETests as it doesn't match the filter 'PROJECTNAME'
Successfully updated project settings in'PROJECTNAME.xcodeproj'

Current working directory after: PROJECT_DIR
```

The workaround for us is `Dir.chdir "fastlane"`, which corrects the working directory.

**Comment by TKBurner** [comment]
@honghaoz Did you try the other workaround?

**Comment by honghaoz** [comment]
@TKBurner I didn't try `GYM_PROJECT`, since I didn't want to use hard-coded environment value. But since it worked before. the problem may cause by `update_project_provisioning ` action.

**Comment by TKBurner** [comment]
@honghaoz Interesting. I think that is the case. You should be able to manually set this in your build settings. You can else use the `provisioning_profile_specifier`

**Comment by yogiben** [comment]
I added `ENV["GYM_PROJECT"] = "/Users/gringo/dev/project/project-app/0.31.0/ios/Project.xcodeproj"` to the `Fastfile` but get the same prompt.

The path works when entered in the command line prompt.

**Comment by TKBurner** [comment]
Hi @yogiben can you also set the GYM_WORKSPACE? Thanks!

**Comment by yogiben** [comment]
@TKBurner that did it. thanks :)
