### ISSUE TITLE
Feature Request: Conditional dSYM download when Crashlytics needs one

### ISSUE THREAD

**Issue by ChristopherDrum** [fastlane/fastlane#6517]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
(iOS workflow request)
Since Fastlane is part of Fabric, and Crashlytics is also part of Fabric, it seems to me that it should now be possible to more tightly integrate with Crashlytics.

We have `download_dsyms` and `upload_symbols_to_crashlytics` actions,
but we don't have `ask_crashlytics_which_dsyms_are_missing`.

I believe this would even take care of the cases where Apple updates dsyms for a build, because Crashlytics would know that "unsymbolicated crashes were found", and could provide the exact build number for `download_dsyms` to use as a parameter to iTunes Connect.

### How it Would Work
I'd see the action running with a parameter for "time period", which is to say, "Only give me the build numbers for unsymbolicated crashes within the past <<XX (hour, day, week, month)>>"
`fastlane ask_crashlytics_which_dsyms_are_missing time_period:48h`

- That array of build numbers would be auto-magically passed over to `download_dsyms`
- `download_dsyms` would auto-magically pass its downloaded files as a parameter to `upload_symbols_to_crashlytics`

And, in fact, it occurs to me that `fix_crashlytics_symbols` could just chain all of the above into a single command

**Comment by TKBurner** [comment]
@ChristopherDrum Very interesting suggestion. Right now there is no public API to get the missing dSYM data from Crashlytics. We aren't going to use private API end points in _fastlane_. If this becomes possible we will definitely implement!
