### ISSUE TITLE
How to build IPA files without storing archivefiles in disk?

### ISSUE THREAD

**Issue by jacobjiangwei** [fastlane/fastlane#6522]
Just curious, how to build this IPA file without saving big archieved files?
It's large, we want to avoid saving it.

**Comment by hjanuschka** [comment]
not sure if it is possible - or atleast if its an easy one, to build ipa without having xcarchive, could'nt you just empty the archive folder, after `gym`

we do it on the ci machines with:

```
FileUtils.rm_rf "~Library/Developer/Xcode/Archives/*"
```

**Comment by TKBurner** [comment]
Hi @jacobjiangwei right now it's not possible. I think @hjanuschka suggestion is a great one! Hope you have a great weekend coming up 👍
