### ISSUE TITLE
Unable to update release notes using deliver

### ISSUE THREAD

**Issue by svintus** [fastlane/fastlane#6530]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Suddenly updating release notes does not work anymore. To the best of my knowledge, I haven't changed anything / updated any gems since the last time I was able to upload release notes successfully.

##### Complete output when running fastlane, including the stack trace and command used

```
➤ deliver --skip_screenshots --skip_metadata --release_notes --verbose
INFO [2016-10-13 10:53:53.89]: Login to iTunes Connect (xxx@gmail.com)
Looking for iTunes Connect Team with ID XXX
INFO [2016-10-13 10:53:55.33]: Login successful

+--------------------+-------------------------------+
|               deliver 1.14.2 Summary               |
+--------------------+-------------------------------+
| skip_screenshots   | true                          |
| skip_metadata      | true                          |
| release_notes      | true                          |
| app_version        | 2.5.3                         |
| app_identifier     | com.xxx.xxx.Xxx               |
| username           | xxx@gmail.com                 |
| screenshots_path   | ./screenshots                 |
| metadata_path      | ./metadata                    |
| skip_binary_upload | false                         |
| force              | false                         |
| submit_for_review  | false                         |
| automatic_release  | false                         |
+--------------------+-------------------------------+

INFO [2016-10-13 10:53:56.42]: Making sure the latest version on iTunes Connect matches '2.5.3' from the ipa file...
INFO [2016-10-13 10:53:59.91]: '2.5.3' is the latest version on iTunes Connect
INFO [2016-10-13 10:53:59.91]: Detected languages: ["de-DE", "default", "en-US", "es-ES", "es-MX", "fr-FR", "it", "ja", "ko", "nl-NL", "pt-BR", "ru", "tr", "zh-Hans", "zh-Hant"]
INFO [2016-10-13 10:54:04.81]: Finished the upload to iTunes Connect
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Deliverfile:
```ruby

# The version of your app - remove this if you provide an ipa file
app_version "2.5.3"


###################### Automatically generated ######################
# Feel free to remove the following lines if you use fastlane

app_identifier "com.xxx.xxx.Xxxx" # The bundle identifier of your app
#apple_id "xxxxx" # This is NOT your Apple login ID, but the App ID of your app
username "xxx@gmail.com" # the login email address

```

### Environment

fastlane version (run `fastlane -v`): 1.105.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

**Comment by hjanuschka** [comment]
try removing `--skip_metadata` - i think this skips the release notes too. see https://github.com/fastlane/fastlane/blob/485199c8757113f2fdd1eee3448a0e0f3cd6d4e7/deliver/lib/deliver/upload_metadata.rb#L20

**Comment by svintus** [comment]
Okay, I guess I did accidentally update fastlane at some point; 

`deliver --skip_screenshots --skip_metadata =release_notes`

was literally the command that worked for me last time I updated metadata. 

I had to remove `--release_notes` as well, so I ended up with 

`fastlane --skip_screenshots --skip_binary_upload`

which worked. Thanks!
