### ISSUE TITLE
[gym] for_lane support in Gymfile

### ISSUE THREAD

**Issue by maschall** [fastlane/fastlane#6531]
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I work on a project with multiple schemes and configurations.  I'd like to be able to specify a configuration for gym in specific lane.

Example:

```
lane :crashlytics do
   sigh
   gym
end

lane :appstore do
   sigh
   gym
end
```

Appfile:

```
for_platform :ios do
  apple_id #{appleId}

  for_lane :crashlytics do
    app_identifier ENV['CRASHLYTICS_APP_ID']
    team_id ENV['CRASHLYTICS_APP_ID_TEAM_ID']
  end

  for_lane :appstore do
    app_identifier ENV['APPSTORE_APP_ID']
    team_id ENV['APPSTORE_TEAM_ID']
  end
end
```

Gymfile:

```
for_platform :ios do
  apple_id #{appleId}

  scheme ENV['SCHEME'

  for_lane :crashlytics do
     configuration "Crashlytics"  
  end

  for_lane :appstore do
    configuration "Release"
  end
end
```

I think this can apply to `Scanfile`s as well, but there could also be a better solution to have `configuration` set-able `for_lane` in another fashion. (Maybe using the `lane_context`?)

**Comment by KrauseFx** [comment]
This looks good, however I think this requires a lot of changes in various code parts, which may lead to unexpected side effects. Did you look into how it's possible to change this?
