### ISSUE TITLE
Code signing with Xcode 8

### ISSUE THREAD

**Issue by Allansk2** [fastlane/fastlane#6533]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have the latest version, but since I update the xcode to Version 8.0 (8A218a), the Automatically manage signing has been painful. When I ran "fastlane appstore", I got the fail to build error.  I have to manually disable Automatically manage signing, clean project and enable Automatically manage signing. (http://stackoverflow.com/questions/37806538). But it's weird that I don't have problem if I open the project and choose "Product" -> "Archive". (I am using the latest Xcode command line tools) I try to use the plugin to do that , add 
update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: false) 
xcodebuild -alltargets clean
update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: true) 
in Fastfile before "gym(include_bitcode: false)", then I got "Syntax error in your Fastfile"  

What am I doing wrong with the plugin? Can anyone help? Thanks!
           
##### Complete output when running fastlane, including the stack trace and command used

[10:19:10]: ▸ Building ****project_name**** [Release]
[10:19:10]: ▸ Check Dependencies
[10:19:11]: ▸ ❌  Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the Push Notifications capability.
[10:19:11]: ▸ ❌  Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment entitlement.
[10:19:11]: ▸ ❌  Code signing is required for product type 'Application' in SDK 'iOS 10.0'
[10:19:11]: ▸ ** ARCHIVE FAILED **
[10:19:11]: ▸ The following build commands failed:
[10:19:11]: ▸ Check dependencies
[10:19:11]: ▸ (1 failure)
▸ Building ****project_name**** [Release]
▸ Check Dependencies

❌  Provisioning profile "iOS Team Provisioning Profile: *" doesn't support the Push Notifications capability.

❌  Provisioning profile "iOS Team Provisioning Profile: *" doesn't include the aps-environment entitlement.

❌  Code signing is required for product type 'Application' in SDK 'iOS 10.0'

** ARCHIVE FAILED **

### Configuration Files
Fastfile:
platform :ios do
  before_all do
  end
 
lane :appstore do
  produce(
    username: '***@*******.com',
    app_identifier: '***.*****',
    app_name: '*******',
    language: 'English',
    app_version: '1.0.5',
    sku: '**',
    team_id: '****,
  )
  
  cert
  pem(generate_p12: true, save_private_key: true)
  sigh
  gym(include_bitcode: false)
  deliver  
end

  after_all do |lane|
  end
  error do |lane, exception|
  end
end

### Environment
fastlane version  
1.105.2

**Comment by hjanuschka** [comment]
```
update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: false) 
xcodebuild -alltargets clean
update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: true) 
```


has a parse error because of `xcodebuild` btw. you could do it like this, `clean: true` does the clean


````
update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: false) 
gym(include_bitcode: false, clean: true)
update_project_codesigning(path: "app.xcodeproj",use_automatic_signing: true) 
```

let me know if this helps

**Comment by bruno-rocha-movile** [comment]
Having the same problem after updating fastlane and xcode. Unfortunately @hjanuschka 's solution did not worked for me :(

**Comment by hjanuschka** [comment]
have you guys checked what your provisionig profile is set under the release configuration?
it should be something like `$(sigh_krone.at-fivexfive_appstore_profile-name)`  (hint: `sigh` prints out the whole name)

and codesigning should be set to manual (or using the plugin toggled to manual, if not already

![bildschirmfoto 2016-10-15 um 20 56 58](https://cloud.githubusercontent.com/assets/2891702/19412603/f4a03f3c-9319-11e6-8cef-73d63365fb3e.png)

**Comment by fassko** [comment]
Hi all,

I run in this issue while building in Travis CI. Finding a solution for several hours I removed all certificates from my locale machine and I found out that it didn't build because development cert was missing.

So I found solution to download all certs (development, appstore, adhoc) before running gym.

Maybe it helps someone.

P.S. I'm not using automatic code signing.

**Comment by Allansk2** [comment]
Just update ruby solve my problem 
 
1) Follow the instructions here (https://developer.xamarin.com/guides/testcloud/calabash/configuring/osx/updating-ruby-using-rbenv/) to install rbenv and ruby-build.
2) Run $ rbenv install 2.3.1 and rbenv global 2.3.1.
3) Reinstall fastlane gem install fastlane.
4) Restart the build server.

**Comment by TKBurner** [comment]
@Allansk2 Awesome! So glad to hear you got up and running 👍

**Comment by antulik** [comment]
Above solutions didn't work for me, but the solution in the blog below did

https://dpogue.ca/articles/cordova-xcode8.html

**Comment by bruno-rocha-movile** [comment]
I got it to work by disabling automatic signing entirely. It's not the best solution, but it solves my problem for now.

**Comment by TKBurner** [comment]
@bruno-rocha-movile For now we don't support automatic signing with fastlane. Glad to hear you got up and running.

**Comment by Ro-M** [comment]
Hi,
I also ran into this locally and on travis after updating to Xcode8.
- make sure "Code Signing Identity" -> "Release" and "Any iOS SDK" is set to "iOS Distribution"
- set provisioniong profile correctly like @hjanuschka mentioned (although i think the correct suffix is just "_appstore" ....?)
- set a Development Team (shouldn't this only be required for automatic signing?)

That's what helped me to resolve the issue locally and on travis

**Comment by mandevx** [comment]
@Ro-M  Thanks for the reply and the suggestion but could you please guide me a bit that where do I do this bit as below and other points you mentioned if it needs to be done by opening the project first in xcode gui then its an issue because I requirement is purely command line or fastlane opening the project manually to set such will be a problem for my situation .
"make sure "Code Signing Identity" -> "Release" and "Any iOS SDK" is set to "iOS Distribution"
