### ISSUE TITLE
Screengrab does not work on Windows

### ISSUE THREAD

**Issue by breakline87** [fastlane/fastlane#6538]
Tried to install screengrab, when I run it I get this error:

C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pty (LoadError)
	from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core/itunes_transporter.rb:1:in `<top (required)>'
	from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fastlane_core.rb:17:in `<top (required)>'
	from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/screengrab-0.5.5/lib/screengrab.rb:4:in `<top (required)>'
	from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby23-x64/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/screengrab-0.5.5/bin/screengrab:4:in `<top (required)>'
	from C:/Ruby23-x64/bin/screengrab:22:in `load'
	from C:/Ruby23-x64/bin/screengrab:22:in `<main>'

I have GEM as 2.6.7
I have Ruby as 2.3.1

If you need any more information let me know, is something missing? Some dependency maybe?

PS: Also please if you can make install not last 1 hour for people who don't know anything about Ruby. A simple executable would be great. I had to install Ruby, Ruby DevKit, Gem, then a bunch of packages for a simple program... No thanks.

**Comment by breakline87** [comment]
I'm not sure about that, I can try. Documentation does not mention Windows at all, I assumed because it's OS independent.

**Comment by TKBurner** [comment]
@hjanuschka Thanks for stepping in. 

@breakline87 Because of our gem dependency we don't support Windows.
