### ISSUE TITLE
Match doesn't repair invalid provisioning profiles

### ISSUE THREAD

**Issue by Antoine4011** [fastlane/fastlane#6541]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

If my provisioning profiles gets invalid, when running match it should detect it and then re-generate the provisioning. Instead it's telling me everything is okay.
##### Complete output when running fastlane, including the stack trace and command used

```
[11:46:13]: Verifying that the certificate and profile are still valid on the Dev Portal...
[11:46:23]: Installing certificate...
[11:46:25]: Installing provisioning profile...

+---------------------+---------------------------------------------------------------------+---------------------------------------------------------+
|                                                           Installed Provisioning Profile                                                            |
+---------------------+---------------------------------------------------------------------+---------------------------------------------------------+
| Parameter           | Environment Variable                                                | Value                                                   |
+---------------------+---------------------------------------------------------------------+---------------------------------------------------------+
| App Identifier      |                                                                     | app_identifier                   |
| Type                |                                                                     | development                                             |
| Profile UUID        | sigh_app_identifier_development              | xxxxxxxx-e6da-4bc9-9fc9-9446b7e4216e                    |
| Profile Name        | sigh_app_identifier_development_profile-name | match Development app_identifier |
| Development Team ID | sigh_ app_identifier_development_team-id      | xxxxxxxx                                              |
+---------------------+---------------------------------------------------------------------+---------------------------------------------------------+

[11:46:27]: All required keys, certificates and provisioning profiles are installed 🙌
```

If I regenerate myself the provisioning profile or delete it. Then I now have an error:

```
[11:46:34]: Verifying that the certificate and profile are still valid on the Dev Portal...
[11:46:43]: Installing certificate...
[11:46:45]: Installing provisioning profile...
[11:46:46]: Provisioning profile 'xxxxxxxx-e6da-4bc9-9fc9-9446b7e4216e' is not available on the Developer Portal
[11:46:46]: for the user xx@xxx.com
[11:46:46]: Make sure to use the same user and team every time you run 'match' for this
[11:46:46]: Git repository. This might be caused by deleting the provisioning profile on the Dev Portal
```

Then the solution is only to nuke everything and start over. But all projects aren't using only match. That means invalid certificates for everyone and start over for every single new projects. It's just not possible... 
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
fastlane_version "1.90.0"

default_platform :ios

platform :ios do

  desc "Download and setup if needed all certificates"
  lane :certificates do
    match(type: "development", app_identifier: "app_identifier-debug")
    match(type: "adhoc", app_identifier: "app_identifier-adhoc")
    match(type: "appstore", app_identifier: "app_identifier")
  end
end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.105.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
nope

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
nope

What Xcode version do you use (e.g. 7.3, 8.0)
8.0

**Comment by Antoine4011** [comment]
Yes I already took a look and Xcode 8 automatic code signing is of course disabled. 
The workaround for this is to actually delete the provisioning profile on the shared git repo. That way, it's being regenerated.

**Comment by lucabartoletti** [comment]
+1 same problem for me

When i add a new device than match fails to repair the provision. It creates a duplicated provisioning

**Comment by TKBurner** [comment]
@Antoine4011 @lucabartoletti Has this behavior changed? It seems inline with the expectations here: https://github.com/fastlane/fastlane/tree/master/match#run

**Comment by lucabartoletti** [comment]
My understanding is that is suggested to nuke before using match for the first time

My problem is that every time I add a device and than i run match I get duplicated provisionings. The old are invalid the new one are valid.

My expectation in this case is that match should repair the existing provisioning adding the new devices

**Comment by TKBurner** [comment]
@lucabartoletti Is this reproducible on a blank project? Can provide exact steps? I want to send this out to the core team 👍

**Comment by jeffremer** [comment]
> My problem is that every time I add a device and than i run match I get duplicated provisionings. The old are invalid the new one are valid.

This happens for us as well and it's been consistent since we started using `match` (switched from `sigh`). Every time I want to add a device we have to nuke all the existing profiles and certificates because calling `match` (from `fastlane`) results in a new profile being added rather than just adding the device to the existing profiles.

Here are excerpts from our `Fastfile`:

```ruby
  lane :provision do |options|
    register_devices(devices:{options[:name] => options[:udid]}, username: "<redacted>")
    nuke
    initialize_match
    
    slack(
      message: "New device has been provisioned. Run `fastlane bootstrap` at your leisure."
    )
  end

  lane :nuke do
    sh 'export MATCH_USERNAME=<Redacted> && cd .. && match nuke distribution && match nuke development'
  end

  lane :initialize_match do
    bootstrap_certificates(:development, readonly: false, force_for_new_devices: true)
    bootstrap_certificates(:adhoc, readonly: false, force_for_new_devices: true)
    bootstrap_certificates(:appstore, readonly: false, force_for_new_devices: true)
  end

  lane :bootstrap do
    bootstrap_certificates(:development, readonly: true, force_for_new_devices: true)
    bootstrap_certificates(:adhoc, readonly: true, force_for_new_devices: true)
    bootstrap_certificates(:appstore, readonly: true, force_for_new_devices: true)
  end

def bootstrap_certificates(type, readonly: true, force_for_new_devices: false)
  match(username:"iphone@strava.com", type: type.to_s, readonly: readonly, force_for_new_devices: force_for_new_devices, team_id: "L27UJU3HDT", app_identifier: [<redacted>]
end
```

We have five app identifiers with three configurations (DEBUG/development, AdHoc/nightly, Release/AppStore). Maybe I don't fully understand the `match` options, but I'd expect/prefer that a new device should be added to existing profiles. Otherwise if a new profile is generated it has a new name (with a numeric suffix) and this is useless since Xcode 8 (and the code signing guide) expects the profile names to match.

Are we just not quite using the right options to have `match` add new devices to existing profiles and  regenerate them?

**Comment by KrauseFx** [comment]
Hey everyone, we just pushed a new release of _match_, that should automatically repair provisioning profile. Let us know if that works 👍

**Comment by lucabartoletti** [comment]
Thanks, I'll test it soon
