### ISSUE TITLE
"Missing Push Notification Entitlement" with sigh

### ISSUE THREAD

**Issue by Azenet** [fastlane/fastlane#6544]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,

I am trying to build a Cordova/Ionic app on a headless Mac but I am running into a lot of issues. I managed to use `match` and `sigh` to sign my application, however when it's uploaded to TestFlight I get an email about "Missing Push Notification Entitlement". `sigh` created a file named `AppStore_com.package.name.mobileprovision`, which contains these lines:
```xml
<key>aps-environment</key>
<string>production</string>
```
This makes me think that the ipa could be signed with the wrong profile, but this is the only one that's active for distribution in the developer account. Maybe I am using it wrong and shouldn't use sigh, but this is the only way I found to build and sign the app properly. If I do not give it the mobileprovision file `xcodebuild` will error with "Code signing is required for product type 'Application' in SDK 'iOS 10.0'". The main issue is that Ionic will re-create a xcodeproj for each build so I cannot open Xcode and set anything there since it will get overwritten on the next build.

Fastfile:
```ruby
fastlane_version "1.105.2"

default_platform :ios

cwd     = File.expand_path(__dir__ + "/../")
teamid  = "XXXXX"
appname = "XXXXX"
appid   = "com.package.name"
plios   = cwd + "/platforms/ios"
xcpj    = plios + "/" + appname + ".xcodeproj"
csid    = "ABCDE (XXXXX)"

platform :ios do
  lane :beta do
    version = prompt(text: "Version: ")
    sh "git checkout -- " + cwd + "/config.xml"
    sh "perl -pi -e 's/^(\\<widget.*version=)\"[0-9\\.]+\"/\$1\"#{version}\"/' " + cwd + "/config.xml"

    match(type: "appstore", team_id: teamid, app_identifier: appid)
    update_project_provisioning(xcodeproj: xcpj, profile: "AppStore_" + appid + ".mobileprovision")
    update_app_identifier(xcodeproj: xcpj, plist_path: appname + "/" + appname + "-Info.plist", app_identifier: appid)
    recreate_schemes(project: xcpj)
    gym(project: xcpj, verbose: true, scheme: appname, xcconfig: plios + "/cordova/build-release.xcconfig", export_team_id: teamid, codesigning_identity: csid)
    pilot(username: "abcde", app_identifier: appid, skip_submission: true, team_id: teamid)
  end
end
```

### Environment

fastlane version (run `fastlane -v`): 1.105.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? no

What Xcode version do you use (e.g. 7.3, 8.0) 8.0

Thanks for any help.

**Comment by hjanuschka** [comment]
starting with xcode8 entitlements in provisioning profiles are not required - they are in the projects `.entitlement` file  - go to your xcode project in the app target  and check that the push capability is enabled - mabye you have to toogle it off & on.

![bildschirmfoto 2016-10-14 um 18 53 16](https://cloud.githubusercontent.com/assets/2891702/19395762/8fd732ac-923f-11e6-92c5-2544662b87cf.png)

if that doesn't do it - check that in your entitlements file you have something like the following:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
```

to verfiy if a entitlements file is set and what it is named go to  the target in xocde -> Build Settings -> and search for entitlement.

![bildschirmfoto 2016-10-14 um 18 55 28](https://cloud.githubusercontent.com/assets/2891702/19395797/d256c7be-923f-11e6-9b23-d03e51583105.png)

**Comment by Azenet** [comment]
Thanks a lot @hjanuschka, figured it out with your comment.

Since I want to be able to build with a new xcodeproj every time, here is my solution for anyone that would have the same problem (using `xcodeproj` gem):

1. Create a file named YourApp.entitlements containing what @hjanuschka posted above
2. Add to your Fastfile a step to copy your file to a folder named YourApp that's in the same folder as YourApp.xcodeproj
3. Create this ruby script and add it as a step to your Fastfile 
```ruby
#!/usr/bin/env ruby
require 'xcodeproj'

proj = Xcodeproj::Project.open("path/to/YourApp.xcodeproj")

targetid = proj.targets.first.uuid
proj.root_object.attributes['TargetAttributes'] = {targetid => {"SystemCapabilities" => {"com.apple.Push" => {"enabled" => 1}}}}

proj.build_configurations.each do |config|
    config.build_settings.store("CODE_SIGN_ENTITLEMENTS", "YourApp/YourApp.entitlements")
end

proj.recreate_user_schemes
proj.save
```

**Comment by TKBurner** [comment]
@hjanuschka Thanks for stepping in here 👍 👍 👍 😻

**Comment by philipkaare** [comment]
@Azenet Thanks for your script. However I could not get it to work until i changed it to also add the entitlements file to the project. 

`#!/usr/bin/env ruby
require 'xcodeproj'

name = ARGV[0]
projectpath = "../platforms/ios/" + name + ".xcodeproj"
puts "Adding entitlement push to " + name
puts "Opening " + projectpath
proj = Xcodeproj::Project.open(projectpath)
entitlement_path = name + "/" + name + ".entitlements"

group_name= proj.root_object.main_group.name

file = proj.new_file(entitlement_path)

attributes = {}
proj.targets.each do |target|
    attributes[target.uuid] = {"SystemCapabilities" => {"com.apple.Push" => {"enabled" => 1}}}
    target.add_file_references([file])
    puts "Added to target: " + target.uuid
end
proj.root_object.attributes['TargetAttributes'] = attributes

proj.build_configurations.each do |config|
    config.build_settings.store("CODE_SIGN_ENTITLEMENTS", entitlement_path)
end
puts "Added entitlements file path: " + entitlement_path

#proj.recreate_user_schemes
proj.save`

**Comment by Azenet** [comment]
@philipkaare This might be because of the location of the script in your Fastfile. In the Fastfile I posted in my first comment I placed my script above the `match` line.

**Comment by philipkaare** [comment]
@Azenet That makes sense as I am not using match, but instead manual signing. I think this is more robust. Anyway you and @hjanuschka got me 90% of the way, so thanks a lot!
