### ISSUE TITLE
Make Supply work with the same directory structure as Produce 

### ISSUE THREAD

**Issue by rstupek** [fastlane/fastlane#6552]
##### Complete output when running fastlane, including the stack trace and command used

supply uses a different data structure than product making a single directory impossible.  

```
```

**Comment by asfalcone** [comment]
@rstupek Can you please describe your request further? Why do you need _supply_ and _produce_ to share a directory structure? Are your Android and iOS projects in the same directory?

**Comment by rstupek** [comment]
The reason it would be convenient that they coexist is that the settings
for android and ios apps are mostly the same and if they can co-exist in
the same directory you wouldn't have to have two separate directory
structures for both.  As it is now, it is necessary to setup two separate
directories for the same app destined for the two stores since you can't
use the same for both apps.

**Comment by TKBurner** [comment]
@rstupek Thanks for following up. I don't think we intend to make this change as it would be breaking others setups.

**Comment by rstupek** [comment]
You can make the change and convert old format to the new. I'm surprised
they weren't already compatible

**Comment by TKBurner** [comment]
@rstupek We'll leave this open as a feature request.
