### ISSUE TITLE
Getting -- pty (LoadError) when call "fastlane init" in windows for android

### ISSUE THREAD

**Issue by rajasekaranm** [fastlane/fastlane#6556]
D\>fastlane init
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
: cannot load such file -- pty (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fas
tlane_core/itunes_transporter.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane_core-0.52.1/lib/fas
tlane_core.rb:17:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-1.105.2/lib/fastlan
e.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55
:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-1.105.2/lib/fastlan
e/cli_tools_distributor.rb:14:in `take_off'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-1.105.2/bin/fastlan
e:5:in `<top (required)>'
        from C:/Ruby23-x64/bin/fastlane:23:in `load'
        from C:/Ruby23-x64/bin/fastlane:23:in `<main>'

**Comment by KrauseFx** [comment]
Windows is not supported by fastlane yet, sorry.
