### ISSUE TITLE
Inappropriate update messages when executing with Bundler

### ISSUE THREAD

**Issue by Onejjy** [fastlane/fastlane#6560]
When we use an outdated version of a gem, we got this message (from `UpdateChecker`): 
```
# gym 1.11.2 is available. You are on 1.11.1.
# It is recommended to use the latest version.
# Update using 'sudo gem update gym'.
```

But when we are in a Bundler environement (like with `bundle fastlane myLane`), this message is not appropriate. It should end with something like:
```
# Update using 'bundle update gym'.
```

Also, we sometimes (1 in 5 cases) have this message (which is not appropriate in Bundler environment):
```
Run `sudo gem cleanup` from time to time to speed up fastlane
``` 

So, if it's OK for you, I have a PR to follow :)

**Comment by KrauseFx** [comment]
Hey @Onejjy, great idea, I'd love to see a PR for this 👍 The first message should be updated, and the second one shouldn't be shown at all when using bundler.

**Comment by Onejjy** [comment]
Closed since it's merged :)

**Comment by KrauseFx** [comment]
Thanks again 👍
