### ISSUE TITLE
[Action/Plugin] download the GitHub release's asset

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#6562]
Hi there, recently for my `lane` I had to download the asset from GitHub release on the hard disk and do some work with it. To do so, I've implemented the custom action and I think this one can be also useful for the community. However, I have a concern whether that can be useful enough to be a new action in `fastlane` or it's better to release it as a plugin.

Pros to make it an action: there is action `get_github_release` to get GitHub release, and action to download the release's asset can be a good pair for it, for example, use the same `shared_var`.

Thoughts? =)

**Comment by hjanuschka** [comment]
can you integrate it into existing `get_github_release`?  - if not, i personally would go for the plugin - and see if it gets some traction  to probably evolve into core.

**Comment by Antondomashnev** [comment]
@hjanuschka thanks for the response, I think the idea to create a plugin and then track the usage is the most reasonable. So here we are [plugin](https://github.com/Antondomashnev/fastlane-plugin-download_github_release_asset).

**Comment by KrauseFx** [comment]
Thanks for building and sharing this plugin  🚀
