### ISSUE TITLE
Summary Improvements: Show build version and itunesconnect URL (if available)

### ISSUE THREAD

**Issue by besi** [fastlane/fastlane#6564]
### Issue Description

I just uploaded a build and it failed (This is not the focus of this issue). However, so now I want to check if the build was uploaded to itunesconnect. So I think it would be very handy to have the version and the itunes connect URL (if available) displayed in the summary.

Especially the version / build number is a key value when dealing with depoloyments.

**Comment by TKBurner** [comment]
@besi Thanks for the suggestion. I'm marking this as a feature request to see if others are interested in it. Thanks!

**Comment by whiskey** [comment]
+1 at least for getting the build number

**Comment by besi** [comment]
@TKBurner: Since this is a feature request, I think this should not be closed automatically.

**Comment by besi** [comment]
Unfortunately I dont have the trace. Also this is not an actual bug in fastlane but it would be handy to have the version and build number displayed in the summary, which is my feature request.

Also I might want to make some adjustments on the app prior to upload. So a deep link into itunes connect would be handy:

Itunesconnect.apple.com/builds/37373783
