### ISSUE TITLE
Match and max number of Distribution certificates 

### ISSUE THREAD

**Issue by callmephilip** [fastlane/fastlane#6565]
### New Issue Checklist

- [+] Updated fastlane to the latest version
- [+] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

With match generating new certificates for every app bundle id, I soon reach a limit on the max number of distribution certificates (3). What are the best practices to work around this limitation?

**Comment by KrauseFx** [comment]
The distribution certificate will be re-used automatically across all your apps 👍

**Comment by callmephilip** [comment]
This is not the behavior I am seeing with match (0.8.1). Running ```match appstore``` given the current Matchfile

```
git_url "git@github.com:callmephilip/test-certs.git"

type "appstore" # The default type, can be: appstore, adhoc or development

app_identifier "io.thebakery.todos" 
username "***" # Your Apple Developer Portal username
```

Creates a new "Production certificate" in addition to a previously created one used by another Matchfile (different app_identifier)

**Comment by callmephilip** [comment]
To clarify, I've used 2 different repositories in both cases, which is probably why 2 different certs were generated. Am I expected to use the same repo across multiple projects?

**Comment by hjanuschka** [comment]
i am using one repo for more than 10 apps and did'nt have a issue with the 3 availaible certs.

**Comment by KrauseFx** [comment]
You have to use one repository, otherwise it can't find the existing certificate. Have you read the guide on https://codesigning.guide?

**Comment by callmephilip** [comment]
I have read and re-read it and while it never states explicitly that each Matchfile should point to a new repo, I somehow got a (wrong) impression that this was the case. In any case, this thread definitely clarifies things. Thank you
