### ISSUE TITLE
Testflight fails with little description, able to upload ipa through XCode

### ISSUE THREAD

**Issue by thecb4** [fastlane/fastlane#6567]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2016-10-16 16:34:03.42]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios release_internal_beta", :GIT_REPO_WAS_CLEAN_ON_START=>true, :SIGH_PROFILE_TYPE=>"development", :VERSION_NUMBER=>"0.1.93", :BUILD_NUMBER=>"155", :IPA_OUTPUT_PATH=>"/Users/xx/Documents/thecb4/apps/FastlanePlugin/TheCB4-FastlaneTest1/dist/TheCB4-FastlaneTest1.ipa", :DSYM_OUTPUT_PATH=>"/Users/xx/Documents/thecb4/apps/FastlanePlugin/TheCB4-FastlaneTest1/dist/TheCB4-FastlaneTest1.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/xx/Library/Developer/Xcode/Archives/2016-10-16/TheCB4-FastlaneTest1 2016-10-16 16.28.33.xcarchive", :SCAN_DERIVED_DATA_PATH=>"/Users/xx/Library/Developer/Xcode/DerivedData/TheCB4-FastlaneTest1-ghcrhchawfokctfloxefohhomzsd", :SCAN_GENERATED_PLIST_FILES=>["/Users/xx/Library/Developer/Xcode/DerivedData/TheCB4-FastlaneTest1-ghcrhchawfokctfloxefohhomzsd/Logs/Test/BF5A146A-D0AB-4C9F-8B30-EA942F58C9B6_TestSummaries.plist"], :SCAN_GENERATED_PLIST_FILE=>"/Users/xx/Library/Developer/Xcode/DerivedData/TheCB4-FastlaneTest1-ghcrhchawfokctfloxefohhomzsd/Logs/Test/BF5A146A-D0AB-4C9F-8B30-EA942F58C9B6_TestSummaries.plist"}
ERROR [2016-10-16 16:34:03.42]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"}
INFO [2016-10-16 16:34:03.42]: Successfully generated documentation at path '/Users/xx/Documents/thecb4/apps/FastlanePlugin/TheCB4-FastlaneTest1/fastlane/README.md'
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
  desc "Push ipa to iTunes App Store"
  lane :push_app_to_testflight do
    whattotest = File.read("metadata/testflight.txt")
    testflight(
      changelog:whattotest,
      ipa:"./dist/#{config["app_name"]}.ipa",
      skip_submission: false,
      distribute_external: false,
      verbose: true
    )
  end
```
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.105.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rbenv
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

What Xcode version do you use (e.g. 7.3, 8.0)
8.0

**Comment by thecb4** [comment]
I am going to close this one myself.  In the instructions it reads that testflight is an alias for pilot, but testflight does not work, while pilot does.  Changing the function from testflight to pilot.

**Comment by KrauseFx** [comment]
Could you try changing this again? Both actions should be the exact same thing

**Comment by thecb4** [comment]
Seemed to only work once.  Now pilot is giving me the same error as testflight

**Comment by thecb4** [comment]
ERROR [2016-10-16 21:11:04.98]: {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["Unexpected Error"], "info"=>nil}, "statusCode"=>"ERROR"}

**Comment by KrauseFx** [comment]
Yeah, so it's not related to the actual action, but the underlying implementation

**Comment by thecb4** [comment]
Is it transporter breaking?

**Comment by alexandreblin** [comment]
I am unable to upload to TestFlight using pilot too. pilot doesn't fail but the build never appears on iTunes Connect.

If I try to reupload the same, I get the error saying that a build with the same build number already exists. I double checked everywhere, no trace of the build (even in the Activity tab, no processing build at all).

Uploading the same archive through Xcode works. I know this is not the exact same problem but it seems pretty close. I'll open a separate issue after doing some more testing.

**Comment by thecb4** [comment]
I am stuck since the error message isn't telling me anything.  It seemed to work when I switched from testflight to pilot, but now errors again.

**Comment by asfalcone** [comment]
@thecb4 Did you give the StackOverflow post that @alexandreblin linked to a try?

**Comment by thecb4** [comment]
```ruby
    git_switch_branch(branch: integration_branch)

    version = app_version(bump:"patch")

    start_topic(topic:"release-#{version}")

    bootstrap_provisions(type:"appstore")
    version = app_version(bump:"patch", write:true)
    save_topic

    build_topic(configuration:"Debug")
    save_topic

    test_topic(configuration:"Debug")
    save_topic

    puts "bumped version to #{version}"
    add_git_tag(tag: version)

    push_marketing_to_appstore
    push_app_to_testflight
```

and the push marketing_to_appstore lane

```ruby
  desc "release marketing information to iTunes App Store"
  lane :push_marketing_to_appstore do
    deliver(
      skip_binary_upload:true,
      force:true,
      # submission_information: {
      #   add_id_info_uses_idfa: false,
      #   add_id_info_serves_ads: false,
      #   add_id_info_tracks_action: false,
      #   add_id_info_tracks_install: false,
      #   add_id_info_limits_tracking: false,
      #   content_rights_contains_third_party_content: true,
      #   content_rights_has_rights: true,
      #   export_compliance_is_exempt: true,
      #   export_compliance_contains_proprietary_cryptography: false,
      #   export_compliance_contains_third_party_cryptography: false,
      #   export_compliance_available_on_french_store: false,
      #   export_compliance_ccat_file: false,
      #   export_compliance_uses_encryption: false,
      #   export_compliance_app_type: false,
      #   export_compliance_encryption_updated: false,
      #   export_compliance_compliance_required: false,
      #   export_compliance_platform: false
      # },
      verbose:true
    )
  end
```

and push app to store

```ruby
  desc "Push ipa to iTunes App Store"
  lane :push_app_to_testflight do
    whattotest = File.read("metadata/testflight.txt")
    pilot(
      changelog:whattotest,
      ipa:"./dist/#{config["app_name"]}.ipa",
      # skip_submission: false,
      # distribute_external: false,
      verbose: true
    )
  end
```

**Comment by TKBurner** [comment]
@thecb4 Have you tried setting any of the submission information that is commented out?

**Comment by thecb4** [comment]
@TKBurner it appears there's an issue with Transporter on the build machine.  Identified that last night. I'll be looking into it more this evening.

**Comment by TKBurner** [comment]
@thecb4 Thanks! Let me know how it goes 👍

**Comment by thecb4** [comment]
@TKBurner It appears that similarly to #6237 testflight fails as part of a lane, but when I run it alone it completes.  I have also noticed that my account gets locked on the itunes connect web page after a few attempts also, but transporter still works as a standalone run even though my account is locked.

**Comment by TKBurner** [comment]
@thecb4 Is this reproducible on a blank Xcode project? I just want to see if this is project specific or environment specific. We haven't had any other reports.

**Comment by thecb4** [comment]
Not sure what was changed, but the latest build 1.108 has fixed the issue.  Everything uploads with no failures.
I am using fastlane inside of gitlab-ci multi runner

**Comment by TKBurner** [comment]
@thecb4 Awesome!
