### ISSUE TITLE
BCSymbolMaps is not included

### ISSUE THREAD

**Issue by DBocksteger** [fastlane/fastlane#6574]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the Contribution Guidelines
### Issue Description

I'm telling gym to include bitcode symbols (BCSymbolMaps dir) into the resulting .ipa, but it isn't including this directory into the .ipa

Furthermore I have 3 schemes (AppName, AppName AdHoc and AppName App Store), passing "AppName App Store" to scheme parameter but gym asks nevertheless which scheme I want to build. Entering "AppName App Store" starts the build of this scheme.
### Configuration Files

``` ruby
    lane :release do
        gym(scheme: "AppName App Store", include_bitcode: true) 
    end
```
### Environment
- Running fastlane version (run `fastlane -v`)? => 1.105.2; gym => 1.11.2
- Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? => NO
- Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? => NO
- What Xcode version do you use (e.g. 7.3, 8.0)? => 7.3.1

**Comment by hjanuschka** [comment]
do you have bitcode enabled ? - do you get the bitcode symbols on a manual archive in xcode?

**Comment by DBocksteger** [comment]
Hi @hjanuschka , bitcode is not enabled, but manually building with Xcode creates the BCSymbolMaps directory.

**Comment by hjanuschka** [comment]
have you tried enabling it? or using `xcargs: "ENABLE_BITCODE=1"` on gym?
