### ISSUE TITLE
ITMS-90167: "No .app bundles found in the package"

### ISSUE THREAD

**Issue by DBocksteger** [fastlane/fastlane#6575]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We're running fastlane on macOS Sierra with Xcode 7.3.1 and are currently getting the following error while trying to upload our binary.

Is there any possible workaround within fastlane to get our binary uploaded without errors?

##### Complete output when running fastlane, including the stack trace and command used

```
[05:49:30]: [Transporter Error Output]: ERROR ITMS-90167: "No .app bundles found in the package"
[05:49:30]: Transporter transfer failed.
[05:49:30]:
[05:49:30]: ERROR ITMS-90167: "No .app bundles found in the package"
[05:49:31]: ERROR ITMS-90167: "No .app bundles found in the package"
Return status of iTunes Transporter was 1: ERROR ITMS-90167: "No .app bundles found in the package"
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

### Configuration Files

Fastfile:
```ruby
    lane :release do
        gym(scheme: "AppName App Store", include_bitcode: true) 
    end
```

### Environment

- fastlane version (run `fastlane -v`):
- Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? => NO
- Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? => NO
- What Xcode version do you use (e.g. 7.3, 8.0) => 7.3.1

**Comment by DBocksteger** [comment]
Seems to be duplicate of https://github.com/fastlane/fastlane/issues/5807 => Can be closed.

**Comment by hjanuschka** [comment]
@DBocksteger  you should see the close issue button (as you are the creator)
