### ISSUE TITLE
Question: Can you use Fastlane plugins without `bundle exec`?

### ISSUE THREAD

**Issue by SpacyRicochet** [fastlane/fastlane#6577]
After installing a plugin, you get the 'Fastlane is running slow, use `bundle exec` instead' warning. This also saves us from using the wrong version of the plugin gem. We have one in development right now, while there is an older one released as an official gem.

However, we were wondering if you can use development gems from a git page _without_ having to use `bundle exec`. Is this possible?

For some extra context; we would like to avoid having to use `bundle exec` during normal fastlane use as well, since it requires more steps for new developers to perform, which can go wrong depending on how they set up their Ruby.

**Comment by hjanuschka** [comment]
without bundler you can build the gem locally and install it.

```
cd /path/to/your/gem
gem build fastlane-plugin-sharethemeal.gemspec
gem install fastlane-plugin-sharethemeal-0.1.7.gem
```

but then you ll always have to rebuild the gem  once it changes.


you can also `require` the gem directly from source folder in your fastfile

Fastfile:

```
require "/Users/h.januschka/Desktop/CLOUD_DRIVE_OLD/fastlane-plugin-sharethemeal/lib/fastlane/plugin/sharethemeal.rb"

lane :demo do
        sharethemeal
end
```

However i guess this is strongly unrecommended.

**Comment by SpacyRicochet** [comment]
Yeah, we're working out how to best ensure new developers don't have to jump through a lot of hoops or learn new habits. I'll try both of these out.

Thanks!
