### ISSUE TITLE
Not working in jenkins

### ISSUE THREAD

**Issue by jinsumv** [fastlane/fastlane#6587]
### New Issue Checklist
- [yes ] Updated fastlane to the latest version
- [yes ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Snapshot is working fine locally but not working in Jenkins.
Through Jenkins noticed three issues below:
1. Build fails after signing identity
2. App crashes when it tries to launch
3. Login page never loads and times out

But didn't notice any of this issue locally. I happens only in Jenkins.
### Environment

fastlane version (run `fastlane -v`): 16.1

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager ? No

What Xcode version do you use (8.0)

**Comment by asfalcone** [comment]
@jinsumv Can you provide your Fastfile and the full output of running fastlane, the crash and build failure that you mention?
