### ISSUE TITLE
Errors after fastlane deliver update

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#6588]
Hi,

I updated the deliver and there after am facing lots of issues with fastlane.
I got the error  "Could not find 'commander'" when running my lane.

Then I updated fastlane to latest verion 1.105.2, but so success with the error.

Then I installed gem commander. But it started complaining for highline.
Once highline was installed, its now started complaining for terminal-table.

Need help related to this as we have a delivery. I have had bad experience whenever I have updated any fastlane tools.

Thanks,
Santosh

**Comment by santoshshetty2612** [comment]
Issue has been resolved. I just uninstalled and then installed again Ruby 2.3.0

**Comment by TKBurner** [comment]
@santoshshetty2612 Awesome! So glad to hear you got up and running 👍

**Comment by santoshshetty2612** [comment]
Probably the reason for the issue was that inside a particular ruby version, I updated fastlane and deliver using sudo command.
When updating gems inside a particular ruby version (which I installed through RVM), one should not use sudo.
