### ISSUE TITLE
Allow for iOS territory updating with Spaceship

### ISSUE THREAD

**Issue by enozero** [fastlane/fastlane#6592]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Currently, you can specify pricing through Spaceship; however, if you want to change the territories, there does not appear a way to do this. Spaceship could expose, as part of pricing (since this happens through the `pricing/instance` API) or something separate, a way to directly set and unset the territories allowed.

For instance:
`app.update_territories!(['USD', 'CAD'])`

This follows the same pattern as `update_price_tier!`

**Comment by enozero** [comment]
I'm already working on this change now...

**Comment by TKBurner** [comment]
@enozero Awesome! We'll work with you there 👍

**Comment by enozero** [comment]
Sounds great!

**Comment by enozero** [comment]
Is anyone available to review the change?

**Comment by TKBurner** [comment]
@enozero We are a little backed up on PRs right now, but rest assured, we will work with you. In the meantime, if you see any other threads related to this, get them to pull down your PR to test it for us. Thanks!

**Comment by haydus** [comment]
Is this change in production?
If so, how can I use it?

**Comment by enozero** [comment]
It is not in production yet. Awaiting a review of the PR. Check the PR that is attached to the issue for the latest updates.
_____________________________

**Comment by KrauseFx** [comment]
This is live now 🚀

**Comment by haydus** [comment]
Is there a documentation on how to use this feature?

**Comment by hjanuschka** [comment]
@haydus  should be something like this:

(inside fastfile)
```ruby
require "spaceship"
Spaceship::Tunes.login("email@host.com")

app = Spaceship::Application.find("krone.at-fivexfive")
app.update_territories!(['USD', 'CAD'])
```

**Comment by haydus** [comment]
Thanks, but i'm getting this error:
undefined method `update_territories!' for #<Spaceship::Tunes::Application:0x007f9a88349908>
Did you mean?  update_price_tier!

I've made sure i had the latest version.
Is this for sure in production?
If not, what changes do i need to make myself to support it?

**Comment by hjanuschka** [comment]
@haydus ohhh i see method got renamed in the PR.


can you try it with:

```
app.update_territories!(['USD', 'CAD'])
```

@enozero can you jump in on this?

**Comment by haydus** [comment]
I managed to remove all territories, but i still don't know how to add ones );
The correct syntax is:
```
require "spaceship"
Spaceship::Tunes.login("email@host.com")
app = Spaceship::Application.find("blabla.blabla")
availability = app.availability
availability.include_future_territories = true
availability.territories = []
availability = app.update_availability!(availability)
```

**Comment by enozero** [comment]
@haydus You can get all the possible territories through `Spaceship::Tunes.client.supported_territories`. If you don't want to parse through that list and pluck out the countries you don't want, you can specify just the two character country code via `Spaceship::Tunes::Availability.from_territories(["FR", "GB", "US"])`.

There is a good amount of testing around this at `spaceship/spec/tunes/availability_spec.rb`. It has some great examples of how to fully use the API in all sorts of different ways.

Thanks for using the new API!

**Comment by haydus** [comment]
Thanks!
