### ISSUE TITLE
Setting up CI on BitBucket using match

### ISSUE THREAD

**Issue by vkislicins** [fastlane/fastlane#6603]
I'm having issues with my setup and the documentation is a bit too high level for me. Would appreciate any help as I've already spent a few days trying to make fastlane work with cert and sigh, so match is my last hope!

```

+-----------------------+-----------------------------------------------+
|                        [32mSummary for match 0.8.1[0m                        |
+-----------------------+-----------------------------------------------+
| app_identifier        | <identifier_here>                         |
| type                  | appstore                                      |
| git_url               | git@bitbucket.org:<git_path_here>.git |
| git_branch            | master                                        |
| keychain_name         | login.keychain                                |
| readonly              | false                                         |
| verbose               | false                                         |
| force                 | false                                         |
| shallow_clone         | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
+-----------------------+-----------------------------------------------+

[11:01:23]: Cloning remote git repo...
[11:01:25]: [33mEnter the passphrase that should be used to encrypt/decrypt your certificates[0m
[11:01:25]: [33mThis passphrase is specific per repository and will be stored in your local keychain[0m
[11:01:25]: [33mMake sure to remember the password, as you'll need it when you run match on a different machine[0m
[11:01:25]: [33mPassphrase for Git Repo: [0m
[11:01:25]: [31mCouldn't decrypt the repo, please make sure you enter the right password![0m
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
```

I'm using bitbucket for my repo and as far as I understand `match` should be using my public key to access the repo, but it keeps looking for the password. I've tried ssh to the machine as `jenkins` user and run the `git clone` command on my certificates repo and it works fine. So it deffinetly requires the same public key. However I can't understand how to switch `match` from looking for a password in a keychain to just cloning the repo.

The documentation suggests `add your CI's public ssh key as a deploy key for your match repo`. That doesn't mean much to me. How should I add the ssh key? Should I put it into a keychain? Should I put it into a file? Also if it can't access the certificates repo, how will adding the key into the repo help? I don't really understand.

Second part of the docs suggest `Once you've decided which approach to take, all that's left to do is to set your encryption password as secret environment variable named MATCH_PASSWORD.` Which password should I be using?

Thanks

**Comment by hjanuschka** [comment]
the key is used to access the git repo - this can be tested using:

 
`git clone git@repo.url.com:repo.git`  - with your ssh key loaded, this is the key that the CI should also have loaded.

 
the error above is about `MATCH_PASSWORD`  - wich has nothing todo with git itself.
it is the `secret` used to encrypt & decrypt your whole repo. as all keys/certs are crypted.

so in your case, you should set the `MATCH_PASSWORD` env - and set it to the password you used, to init the repo.

**Comment by vkislicins** [comment]
Thanks for the response @hjanuschka 

What if I didn't encrypt my repo? Do I have to encrypt it?

**Comment by hjanuschka** [comment]
it will be automatically encrypted.
just follow this guide, https://github.com/fastlane/fastlane/tree/master/match#usage basically watch the GIF 🍭 

in worst-case, if something is screwed with your repo, you could create a new one, as profiles & certs can easily be restored

**Comment by vkislicins** [comment]
Hmm.. I was looking at this issue here: https://github.com/fastlane/fastlane/issues/4020

and someone there (pkoder) suggested following http://macoscope.com/blog/simplify-your-life-with-fastlane-match/ to add the keys to the repo (Migrate Existing Certificates part). So I found my certificate and the keys, extracted, encrypted, uploaded to the repo, and retried. I'm still getting  `Couldn't decrypt the repo, please make sure you enter the right password!`

But if I run match init will it remove all the stuff I already added? Do I nuke first, init then upload my stuff to encrypt the repo?

**Comment by vkislicins** [comment]
Looks like that error was related to my provisioning profiles. Although I've encrypted them the same way, strange... So I've removed those from the repo and now I'm presented with `Could not create another Distribution certificate, reached the maximum number of available Distribution certificates`

**Comment by vkislicins** [comment]
The saga continues.. I've used the nuke and trying to rely on match to create the certs, however, It's failing. If I use 'readonly', then I get ` No code signing identity found and can not create a new one because you enabled `readonly`` and if I remove `readonly`, it fails with `No value found for 'keychain_path'`

**Comment by vkislicins** [comment]
Ok, I've recreated all certificates, uploaded them to the repository again. `match` is running decryption on all certificated and provision profiles successfully, but then the problems start. I get a warning `Couldn't find a valid code signing identity in the git repo for distribution... creating one for you now[`, this initiates `cert`(which shouldn't really run cause those are valid certificates and profile), which then fails with the same `keychain_path` error. Any help very much appreciated as I've been battling this for far too long!

**Comment by vkislicins** [comment]
```

+-----------------------+-----------------------------------------------+
|                        �[32mSummary for match 0.8.1�[0m                        |
+-----------------------+-----------------------------------------------+
| app_identifier        | <identifier_here>                         |
| type                  | appstore                                      |
| username         | <username>
| git_url               | git@bitbucket.org:<git_path_here>.git |
| git_branch            | master                                        |
| keychain_name         | jenkins.keychain                                |
| readonly              | false                                         |
| verbose               | false                                         |
| force                 | false                                         |
| shallow_clone         | false                                         |
| force_for_new_devices | false                                         |
| skip_docs             | false                                         |
+-----------------------+-----------------------------------------------+

INFO [2016-10-18 15:09:52.42]: Cloning remote git repo...
INFO [2016-10-18 15:09:52.42]: [4m[36m$ GIT_TERMINAL_PROMPT=0 git clone 'git@bitbucket.org:<....>t' '/var/folders/0c/txpqbtt52sd87g2tbcffcjb000007x/T/d20161018-15788-1jx09xh'[0m[0m
INFO [2016-10-18 15:09:52.42]: ▸ [35mCloning into '/var/folders/0c/txpqbtt52sd87g2tbcffcjb000007x/T/d20161018-15788-1jx09xh'...[0m
INFO [2016-10-18 15:09:53.55]: ▸ [35mremote: Counting objects: 45, done.[0m
INFO [2016-10-18 15:09:53.60]: ▸ [35mremote: Compressing objects: 100% (41/41), done.[0m
INFO [2016-10-18 15:09:53.72]: ▸ [35mremote: Total 45 (delta 4), reused 0 (delta 0)[0m
INFO [2016-10-18 15:09:53.72]: ▸ [35mReceiving objects: 100% (45/45), 63.29 KiB | 0 bytes/s, done.[0m
INFO [2016-10-18 15:09:53.72]: ▸ [35mResolving deltas: 100% (4/4), done.[0m
INFO [2016-10-18 15:09:53.73]: ▸ [35mChecking connectivity... done.[0m
INFO [2016-10-18 15:09:53.74]: [32m🔓  Decrypted '....cer'[0m
INFO [2016-10-18 15:09:53.74]: [32m🔓  Decrypted '....cer'[0m
INFO [2016-10-18 15:09:53.74]: [32m🔓  Decrypted '....p12'[0m
INFO [2016-10-18 15:09:53.75]: [32m🔓  Decrypted '....p12'[0m
INFO [2016-10-18 15:09:53.75]: [32m🔓  Decrypted 'AppStore_....mobileprovision'[0m
INFO [2016-10-18 15:09:53.76]: [32m🔓  Decrypted 'Development_....mobileprovision'[0m
INFO [2016-10-18 15:09:53.76]: [32m🔓  Successfully decrypted certificates repo[0m
INFO [2016-10-18 15:09:53.76]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2016-10-18 15:09:57.45]: [33mCouldn't find a valid code signing identity in the git repo for distribution... creating one for you now[0m

+-------------+----------------------+
|       [32mSummary for cert 1.4.3[0m       |
+-------------+----------------------+
| development | false                |
| force       | true                 |
| username    | <...> |
+-------------+----------------------+

INFO [2016-10-18 15:09:57.46]: Starting login with user '<...>'
INFO [2016-10-18 15:09:58.86]: Successfully logged in
INFO [2016-10-18 15:10:02.01]: [32m🔒  Successfully encrypted certificates repo[0m
WARN [2016-10-18 15:10:02.01]: [33m[33mVariable Dump:[0m[0m
INFO [2016-10-18 15:10:02.01]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
ERROR [2016-10-18 15:10:02.02]: [31mNo value found for 'keychain_path'[0m
```

**Comment by TKBurner** [comment]
@vkislicins What happens if you set a `keychain_path` on match?

**Comment by vkislicins** [comment]
Thanks for your reply, @TKBurner . I'm not sure if it's possible to to set `keychain_path` on match. From what I understood it only takes `keychain_name` argument, not the path one. Or am I missing something?

**Comment by hjanuschka** [comment]
can you post your fastfile, would be interessting from where the `keychain_path missing` is comming.

also run the fastlane with `--verbose`  to hopefully get a reasonable stacktrace.

**Comment by vkislicins** [comment]
Well if I'm reading this log correctly, `keychain_path missing` is coming from `cert`. And match takes only `keychain_name` parameter.

Sure, my fastfile looks like this (I've replaced emails and ids with <...>):

```
fastlane_version "1.105.0"
default_platform :ios

platform :ios do
before_all do

ENV['KEYCHAIN_NAME'] = "jenkins.keychain"
ENV['ORIGINAL_DEFAULT_KEYCHAIN'] = "/Users/Shared/Jenkins/Library/Keychains/jenkins.keychain"

# ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
# xctool # run the tests of your app
end
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning

    match(app_identifier: '<...>', type: 'appstore', username: '<...>', verbose: true, keychain_name:ENV['KEYCHAIN_NAME'])
    gym(scheme: '<...>', export_method: 'app-store')

    emails = values[:test_email] ? values[:test_email] : ['<...>'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

#crashlytics(api_token: '8f5b2bd8ec978ae9dc426603d3ec59d3aa87752e',
#             build_secret: '0bc783955c0f901c30f7fa6cbbea5d16e0f9a90ffa7ecd6ec6e43862a8bbad02',
#                   emails: emails,
#                  groups: groups,
#                   notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
#           notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    #)
  end
end
```

**Comment by vkislicins** [comment]
I'm running in `--verbose` mode however, stack trace I get is for the error `Could not create another Distribution certificate, reached the maximum number of available Distribution certificates`. But as I understand it should never even try to do that cause it should use the stuff it decrypted from the repo.. I think the problems comes from:

` WARN [2016-10-19 13:13:29.47]: [33mCouldn't find a valid code signing identity in the git repo for distribution... creating one for you now[0m`

But I'm not sure why...

**Comment by hjanuschka** [comment]
i have pretty much the same setup - except i am not setting the keychain stuff on `match`
i set it via `ENV` maybe you could give it a try. have you tried revoking one of your certifictates manually on itunesconnect? - so match could create a new one? - maybe something is messed up in the repo it self.

```
ENV['FL_UNLOCK_KEYCHAIN_PATH']="/Users/hjanuschka/Library/Keychains/login.keychain"
ENV['FL_UNLOCK_KEYCHAIN_PASSWORD']="xxx"
unlock_keychain
match
gym
pilot
```

**Comment by vkislicins** [comment]
If I don't set the keychain in match, it attempts to use `login.keychain` that doesn't exist for jenkins user. I've tried your suggestion but no luck unfortunately

I've also tried to 1) revoke and delete everything from repo and run match to create the certificates and 2) revoke and recreate everything manually - didn't work.

**Comment by TKBurner** [comment]
@vkislicins Thanks for following up. Can you go on the developer portal and delete at least one of your distribution certificates? Thanks!

**Comment by vkislicins** [comment]
@TKBurner I've tried that already with no luck.. Maybe I took a wrong step somewhere. Can you please suggests the steps to take just to be 100% sure.

**Comment by TKBurner** [comment]
@vkislicins Check out this page: https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html#//apple_ref/doc/uid/TP40012582-CH31-SW26

Thanks!
