### ISSUE TITLE
Simulator failing to launch every second build

### ISSUE THREAD

**Issue by liamogierussell1** [fastlane/fastlane#6604]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I am using scan to run UI and unit tests as part of my fastfile. Since updating to XCode 8 i get the following error when attempting to launch the iOS 10 simulator. Watching the simulator, when it works it launches the MyAppUITests app on then closes and launches the main app to run the tests. When it fails it launches the MyAppUITests app then goes to a black screen and never runs the main app.

At the moment it fails every second build. Fail, succeed, fail, succeed. 

<img width="88" alt="screen shot 2016-10-18 at 15 10 13" src="https://cloud.githubusercontent.com/assets/22645594/19481198/105004b0-9545-11e6-897b-ba6dd7316f2d.png">

I have attempted resetting the simulator between builds, setting a particular simulator to run on, clearing derived data but no success in stabilising this. Nothing changes between builds, I am only running the tests in my fasfile at the moment for debugging.

No system alert is displayed when the app opens that seems to be the cause of this in other cases. There are no tests being run, I have removed all tests to ensure it wasn't an issue with the test code.

The following is the error logged in fastlane.

`2016-10-18 14:51:27.545 xcodebuild[87722:166492] Error Domain=IDETestOperationsObserverErrorDomain Code=5 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
Test target MyAppUITests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
*\* TEST FAILED **
[14:51:27]: Exit status: 65`
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
desc "Executes unit and UI tests"
lane :executeTestsLane do

    scan(
        workspace: "MyApp.xcworkspace",
        scheme: "MyAppUITests",
        clean: true,
        output_directory: "build"
    )

end
```
### Environment

fastlane version (run `fastlane -v`):
1.105.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? 
yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? 
rvm

What Xcode version do you use (e.g. 7.3, 8.0) 
8.0

**Comment by TKBurner** [comment]
@liamogierussell1 Have you set a device directly on scan?

**Comment by liamogierussell1** [comment]
Hi @TKBurner , ya i tried setting the device in scan using devices: ["iPhone 7"] which didn't help. Iv since found that using a script to reset the simulator content and settings between builds I am able to successfully run unit tests every build. However UI tests continue to fail on subsequent builds.

**Comment by TKBurner** [comment]
@liamogierussell1 Thanks for following up. Can you provide the full output of your run when it fails?

**Comment by vrutberg** [comment]
Hi, I am experiencing a similar isse. @liamogierussell1, did you ever resolve this?
