### ISSUE TITLE
Languages

### ISSUE THREAD

**Issue by petitmat** [fastlane/fastlane#6607]
Just a question about this file : https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/languages.rb

Why don't you use the code_languages of iTunes Connect and Google Play Console ? Moreover, why supply isn't available in estonian or in polish for example ?

Thanks,

**Comment by TKBurner** [comment]
@petitmat Do you run into an issue when you try to upload in those languages? Thanks!

**Comment by petitmat** [comment]
`/Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.15/lib/google/apis/core/http_command.rb:211:in `check_status': [!] unsupportedListingLanguage: Listing language pl is not supported. (Google::Apis::ClientError)
`

Yes I ran it, with supply command, and in my metadata folder I have two languages en-US and pl

**Comment by TKBurner** [comment]
@petitmat I reached out to the core team about this. Hope you have a great day!

**Comment by asfalcone** [comment]
Have you tried `pl-PL` as the language code?

from google play console:
![image](https://cloud.githubusercontent.com/assets/1848683/19562249/99c03e76-96a9-11e6-8950-101de95abef8.png)

I don't believe that _supply_ uses `languages.rb`.
