### ISSUE TITLE
[supply] Doesn't upload apk, if there is other apk in build folder

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#6608]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
If there is another apk in my build folder: `/app/build/outputs/apk/` - then lane doesn't' work properly and gets error during upload build.

It caused because all apk stored in `GRADLE_ALL_APK_OUTPUT_PATHS`.

How to specify, that I want to upload only apk, that just built by grade?

##### Complete output when running fastlane, including the stack trace and command used

```
[20:11:40]: Variable Dump:
[20:11:40]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android deploy", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/skywinder/AndroidStudioProjects/app-android/app/build/outputs/apk/app-alfa-v.0.5.119022.apk", "/Users/skywinder/AndroidStudioProjects/app-android/app/build/outputs/apk/app-beta-v.0.5.119021.apk", "/Users/skywinder/AndroidStudioProjects/app-android/app/build/outputs/apk/app-beta-v.0.5.119022.apk"], :GRADLE_APK_OUTPUT_PATH=>"/Users/skywinder/AndroidStudioProjects/app-android/app/build/outputs/apk/app-beta-v.0.5.119022.apk"}
[20:11:40]: Google Api Error: apkUpgradePackageNameIsDifferent: APK has the wrong package name.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gradle                              | 49          |
| 💥    | supply                              | 71          |
+------+-------------------------------------+-------------+

[20:11:40]: fastlane finished with errors

[!] Google Api Error: apkUpgradePackageNameIsDifferent: APK has the wrong package name.
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  gradle(task: 'assembleMyAppAlpha')
    supply(skip_upload_images:true, skip_upload_screenshots:true, skip_upload_metadata:true,track:'alpha')
```

### Environment

fastlane version (run `fastlane -v`): 1.105.2

**Comment by TKBurner** [comment]
@skywinder Can you share your full input to this lane? I want to take a look at what variables you are setting. Also can you run `fastlane run update_fastlane` we pushed an update that has more debugging info.

**Comment by asfalcone** [comment]
@skywinder you can also try 
```ruby
gradle(task: 'clean assembleMyAppAlpha')
```
to clean the other apks from the directory before building the apk you want to upload.

**Comment by skywinder** [comment]
Clean do the trick. Thanks!
