### ISSUE TITLE
NSMutableAttributedString in hierarchy causes snapshot run to stall & fail.

### ISSUE THREAD

**Issue by williamsjj** [fastlane/fastlane#6610]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Basically, if you have an NSMutableAttributedString anywhere in your view hierarchy, UI Testing (and snapshot) will hang on any call that inspects the view tree: https://forums.developer.apple.com/message/129839#129839

This is more a bug with UI Testing, however since Apple has acknowledged but not fixed the issue I'm wondering if anyone here has a workaround?

##### Complete output when running fastlane, including the stack trace and command used
```
$ snapshot

...

Failing tests:
-[Screenshots testShowBrowseHistoryForUser()]
** TEST FAILED **

All tests
Test Suite UITests.xctest started
Screenshots
✗ testShowBrowseHistoryForUser, UI Testing Failure - Failed to get snapshot within 15.0s


UITests.Screenshots
testShowBrowseHistoryForUser, UI Testing Failure - Failed to get snapshot within 15.0s
SnapshotHelper.swift:117
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Snapfile:
```ruby
# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
 devices([
   "iPhone 7",
 ])

languages([
  "en-US",
])

# Arguments to pass to the app on launch. See https://github.com/fastlane/snapshot#launch-arguments
# launch_arguments(["-favColor red"])

number_of_retries 3

# The name of the scheme which contains the UI Tests
scheme "Screenshots"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots"

#clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./project.xcodeproj"
workspace "./workspace.xcworkspace"

erase_simulator true
localize_simulator true
clean true

# For more information about all available options run
# snapshot --help

```

### Environment

fastlane version (run `fastlane -v`):

snapshot 1.16.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

no

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

no

What Xcode version do you use (e.g. 7.3, 8.0)

8.0

**Comment by TKBurner** [comment]
@williamsjj I'm not sure we can be of much help. Let me know if you find a viable workaround 👍
