### ISSUE TITLE
snapshot gets stuck at Build Succeeded

### ISSUE THREAD

**Issue by xaphod** [fastlane/fastlane#6618]
### New Issue Checklist

- [X] Updated fastlane to the latest version (`gem update fastlane`)
- [X] Updated SnapshotHelper to the latest version (`snapshot update`)
- [X] Cleared derived data in xcode 8 (when I ask snapshot to do this it says `No derived_data_path`)
- [X] reset all simulators -- argh i hate this, it takes me ages to make them all again because snapshot doesn't make all the iOS 8 and 9 pairs that I need...
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I run `snapshot`, it gets stuck and **never opens the simulator**

##### Complete output when running fastlane, including the stack trace and command used

```
xaphod$ snapshot
...
+----------------------------+-------------------------------------------------------+
|                            Summary for snapshot 1.16.2                             |
+----------------------------+-------------------------------------------------------+
| devices                    | ["iPhone 7"]                                          |
| languages                  | ["en-US"]                                             |
| scheme                     | Photobooth-SCREENSHOTS                                |
| output_directory           | /Users/Tim/iPhone-dev/Photobooth/fastlane/screenshots |
| clear_previous_screenshots | false                                                 |
| workspace                  | ./Photobooth.xcworkspace                              |
| launch_arguments           | [""]                                                  |
| skip_open_summary          | false                                                 |
| reinstall_app              | false                                                 |
| erase_simulator            | false                                                 |
| localize_simulator         | false                                                 |
| app_identifier             | com.xaphod.wifibooth                                  |
| buildlog_path              | ~/Library/Logs/snapshot                               |
| clean                      | false                                                 |
| number_of_retries          | 1                                                     |
| stop_after_first_error     | false                                                 |
+----------------------------+-------------------------------------------------------+

[17:48:53]: Building and running project - this might take some time...
...
[17:35:09]: ▸ Processing Info.plist
[17:35:09]: ▸ Generating 'Photobooth.app.dSYM'
[17:35:11]: ▸ Running script '[CP] Embed Pods Frameworks'
[17:35:14]: ▸ Running script '[CP] Copy Pods Resources'
[17:35:14]: ▸ Running script 'Build number in info.plist'
[17:35:14]: ▸ Running script 'Build number in Settings.bundle'
[17:35:14]: ▸ Copying /var/folders/yl/mw_r1p4j3vj2mfp32rqs0y7r0000gn/T/snapshot_derived20161018-1525-1iy2lfo/Build/Products/Screenshots-watchsimulator/Watch.app
[17:35:14]: ▸ Running script 'Crashlytics'
[17:35:15]: Running Tests: ▸ Touching Photobooth.app
[17:35:15]: ▸ Signing /var/folders/yl/mw_r1p4j3vj2mfp32rqs0y7r0000gn/T/snapshot_derived20161018-1525-1iy2lfo/Build/Products/Screenshots-iphonesimulator/Photobooth.app
[17:35:16]: ▸ Build Succeeded
```

At this point i'd expect a simulator to open up, but nothing happens.

### Configuration Files

I'm running `snapshot` from the command-line, with this Snapfile:

```ruby
devices([
   "iPhone 7",
])

languages([
  "en-US",
])
scheme "Photobooth-SCREENSHOTS"
output_directory "./fastlane/screenshots"
clear_previous_screenshots false
workspace "./Photobooth.xcworkspace"
```

### Environment

fastlane version (run `fastlane -v`):
fastlane 1.105.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
RVM 1.27.0 

What Xcode version do you use (e.g. 7.3, 8.0)
8.0

Code is a mix of Swift 3 and Objective-C with lots of Pods, in case that matters

**Comment by TKBurner** [comment]
@xaphod Thanks for reaching out. What happens if you don't set the device type or include others? What happens if you erase your simulators?

**Comment by xaphod** [comment]
@TKBurner I erased all my simulators, derived data, and every other option snapshot has. Didn't make a difference.  I tried commenting out the devices in the Snapfile (so snapshot by default tries to do 9 runs), didn't make a difference.

**Comment by TKBurner** [comment]
Hi @xaphod Can you add the --verbose flag to your run of snapshot? That'll hopefully provide more information.

**Comment by xaphod** [comment]
I tried that. No additional information.

**Comment by xaphod** [comment]
@tkburner 
I tried that. No additional information.

**Comment by xaphod** [comment]
After leaving it spinning 1 core at 100% via xcodebuild for ages, I got this:

````
▸ Build Succeeded
sh: line 1: 39197 Killed: 9               xcodebuild -workspace ./Photobooth.xcworkspace -scheme Photobooth-SCREENSHOTS -derivedDataPath '/var/folders/yl/mw_r1p4j3vj2mfp32rqs0y7r0000gn/T/snapshot_derived20161018-24652-pfbnwy' -destination 'platform=iOS Simulator,id=029A0523-647D-482E-A024-31D6CC52F65B,OS=10.0' FASTLANE_SNAPSHOT=YES build test
39198 Done                    | tee /Users/Tim/Library/Logs/snapshot/Photobooth-Photobooth-SCREENSHOTS.log
39199 Done                    | xcpretty
ERROR [2016-10-18 21:37:29.86]: Exit status: 137
ERROR [2016-10-18 21:37:29.86]: Caught error... 137
````

@TKBurner What's that about? the log file it mentions has nothing exciting:

````
...
    /bin/sh -c /var/folders/yl/mw_r1p4j3vj2mfp32rqs0y7r0000gn/T/snapshot_derived20161018-24652-pfbnwy/Build/Intermediates/Photobooth.build/Screenshots-iphonesimulator/Photobooth.build/Script-22640C3A1A3CDD4F0007701F.sh
2016-10-18 21:37:37.249 uploadDSYM[40017:146624] Fabric.framework/run 1.6 (203)
2016-10-18 21:37:37.255 uploadDSYM[40017:146624] Launched uploader in validation mode

** BUILD SUCCEEDED **
````

**Comment by xaphod** [comment]
.. I tried removing the fabric run script to see if that had any effect -- nada.
I am confused as to why xcodebuild is running AFTER it says build succeeded.

**Comment by bl4design** [comment]
I update Fastlane and started experiencing issues with Snapshot including hanging when calling 'fastlane snapshot' 
fastlane version (run fastlane -v):
fastlane 1.105.3

Do you use bundler to execute fastlane (i.e. bundle exec fastlane)?
No

Do you use a Ruby environment manager (e.g. chruby, rbenv, rvm)?
No
ruby 2.3.1

What Xcode version do you use (e.g. 7.3, 8.0)
8.0 

Code is newly converted to Swift 3 with Pods. Once I added 'clear_previous_screenshots true' to my Snapfile I was getting the following error coming from 'Pods/URITemplate/Sources/URITemplate.swift'

$ fastlane snapshot
[21:52:36]: Successfully loaded '/Users/bl/Documents/apps/app/fastlane/Snapfile' 📄

+----------------------------+----------------------+
|    Detected Values from './fastlane/Snapfile'     |
+----------------------------+----------------------+
| devices                    | ["iPhone 6"]         |
| languages                  | ["en-US"]            |
| scheme                     | app                  |
| output_directory           | ./screenshots        |
| clear_previous_screenshots | true                 |
+----------------------------+----------------------+

[21:52:36]: Successfully loaded '/Users/bl/Documents/apps/app/fastlane/Snapfile' 📄
[21:52:36]: No values defined in './fastlane/Snapfile'
[21:52:36]: $ xcodebuild -list -workspace ./app.xcworkspace

+----------------------------+---------------------------------------------+
|                       Summary for snapshot 1.16.2                        |
+----------------------------+---------------------------------------------+
| devices                    | ["iPhone 6"]                                |
| languages                  | ["en-US"]                                   |
| scheme                     | app                                         |
| output_directory           | /Users/bl/Documents/apps/app/screenshots    |
| clear_previous_screenshots | true                                        |
| workspace                  | ./app.xcworkspace                           |  
| launch_arguments           | [""]                                        |
| skip_open_summary          | false                                       |
| reinstall_app              | false                                       |
| erase_simulator            | false                                       |
| localize_simulator         | false                                       |
| app_identifier             | com.co.app                                  |
| buildlog_path              | ~/Library/Logs/snapshot                     |
| clean                      | false                                       |
| number_of_retries          | 1                                           |
| stop_after_first_error     | false                                       |
+----------------------------+---------------------------------------------+

[21:52:36]: Clearing previously generated screenshots
[21:52:36]: Building and running project - this might take some time...
[21:52:36]: snapshot run 1 of 1

**Comment by xaphod** [comment]
Getting desperate here: completely uninstalled xcode including erasing user Developer folder and all Application support subfolders, reinstalled xcode -- no change. Even if I just run the xcodebuild command that snapshot is running (manually from the command-line), it also hangs. I realize this means it is not a snapshot bug, it's something with xcode... but how can I debug?

**Comment by TKBurner** [comment]
@xaphod Does this persist on all projects or just one specific project? I read another report the other day related to an nsunmutable in the test files.

**Comment by xaphod** [comment]
@TKBurner this rabbit hole is endless. I just realized that even after completely reinstalling xcode (including defaults delete, plist delete, compelte purge), in this project I cannot run any UItests in xcode. The second I click the little arrow next to the test, xcode hangs. In another project it's fine...

**Comment by xaphod** [comment]
@TKBurner small progress: If I delete the dependency between my main target and my apple watch target, then the hang disappears.

**Comment by TKBurner** [comment]
@xaphod Nice! Is your test target also having that dependency, that might be the problem. I believe it **should**

**Comment by xaphod** [comment]
@TKBurner Yes, dependencies are the obvious - test->main->watch.
Now to figure out why my watch target hangs for all UITests.

**Comment by xaphod** [comment]
@TKBurner OK I figured it out: my watch extension has a dependency on Watch, and that for some reason destroys UITests. I removed that, and now it gets a tiny bit further.

Next error is exactly https://github.com/fastlane/fastlane/issues/5964 ...
seems like fastlane really doesn't wanna work for me yesterday or today.

**Comment by TKBurner** [comment]
@xaphod Thanks for following up. 👍
