### ISSUE TITLE
How to collect screenshots in HTML report via xcpretty?

### ISSUE THREAD

**Issue by kirillzh** [fastlane/fastlane#6619]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

`xcpretty` has [`screenshots`](https://github.com/supermarin/xcpretty/blob/4b90228e80dd74dbdb209553668178023447ff85/bin/xcpretty#L65) option, how do I enable it using `scan`? 
I see [there is](https://github.com/fastlane/fastlane/blob/ba824767f7fcf60d13d870cbe183b9fb5d80a565/fastlane/lib/fastlane/actions/xcodebuild.rb#L203) `screenshots` option used in [`xcodebuild.rb`](https://github.com/fastlane/fastlane/blob/ba824767f7fcf60d13d870cbe183b9fb5d80a565/fastlane/lib/fastlane/actions/xcodebuild.rb), but it's not clear how to enable it.
### Configuration Files

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version: `1.105.3`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? `No`

Ruby environment manager: `rbenv`

Xcode version: `8.1`

**Comment by TKBurner** [comment]
Hi @kirillzh You can set it using the `xcargs` parameter. Let me know how it goes!

**Comment by kirillzh** [comment]
@TKBurner, do you mean something like that `--xcargs 'screenshots'`?
I'm getting `xcodebuild: error: Unknown build action 'screenshots'` error.

**Comment by KrauseFx** [comment]
Could you clarify on what you want to do?

**Comment by kirillzh** [comment]
@KrauseFx, sure, essentially I want to pass argument to `xcpretty` while running tests using `scan`.

**Comment by TKBurner** [comment]
@kiliankoe Thanks for following up. Sorry for the confusion, xcargs actually points to xcodebuild so that's why that didn't work. I'm not certain there is a good way to do this.

**Comment by kiliankoe** [comment]
You probably meant to mention @kirillzh instead of me, I got a bit confused there for a moment :D

**Comment by TKBurner** [comment]
Sorry about that 👍

**Comment by RichardGuion** [comment]
I am also using scan to run tests with xcode and need the screenshots enabled. @dtrenz would you have any insight here, is there currently a way to pass a flag through scan so that screenshots are enabled for xcpretty? I see your commit from 2015 where there are the screenshots flags in xccodebuild.rb...

https://github.com/fastlane/fastlane/commit/5a8d582d13e6bde226c19af4e7a66ab8530f24ee
