### ISSUE TITLE
Add ENV support to Pilot

### ISSUE THREAD

**Issue by whlsxl** [fastlane/fastlane#6625]
##### Complete output when running fastlane, including the stack trace and command used

pilot builds --env [some_env]

```
invalid option: --env
```

Does  it necessary to add environment support in other gem like Pilot.

I use ENV to separate different targets. Sometimes I use `pilot builds` to check the all the binary, but command line ask me to input my `App Identifier`.

I think if I can just specify a ENV to determine `App Identifier` is more convenient.
### Environment

fastlane version (run `fastlane -v`): 1.105.2

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? YES

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? YES rbenv

What Xcode version do you use (e.g. 7.3, 8.0) 7.3

**Comment by TKBurner** [comment]
Hi, @whlsxl Try something like `ENV_NAME="123" fastlane beta`

**Comment by KrauseFx** [comment]
Are you talking about .env? If so, you should use fastlane and call pilot from there?

**Comment by whlsxl** [comment]
@KrauseFx @TKBurner Thanks for reply
I have another question, I don't know how to use `pilot builds` in `Fastfile`.

**Comment by TKBurner** [comment]
Hi @whlsxl You can set these at the top of your fastfile or in your shell enviroment.
