### ISSUE TITLE
Failures due to presence of FASTLANE_PASSWORD

### ISSUE THREAD

**Issue by esttorhe** [fastlane/fastlane#6626]
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When `FASTLANE_PASSWORD` is present as an env var (configured on `.zshrc` or `.bashrc`) `fastlane` ignores the password inputed when asked on the terminal.
### Environment

fastlane version (run `fastlane -v`):
`1.105.2`

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
`chruby`

What Xcode version do you use (e.g. 7.3, 8.0)
`8.0`

---

Worth noting that this isn't the first time I've experienced this; just that being the numbnuts i am i never took the time to file an issue about this.

Recently I tried on a fresh new machine at work (that I configured using my `dotfiles` repo which carried away the `FASTLANE_PASSWORD` var) and then I was faced again with a case of «your password is wrong» even though `fastlane`was asking me to input it via terminal and I was copy/pasting it from `LastPass`.

When I was about to rage quit I realised that the variable was set and after removing it and `fastlane` asking me for the password again, adding the same one I used multiple times (without success) worked.

Hope this is enough info to repro; if not let me know and I'll be more than happy to provide more details.

PS. Thanks for the amazing work so far

**Comment by asfalcone** [comment]
@esttorhe Thanks for the report! Can you share your Fastfile so we can see which tools you're using?

**Comment by esttorhe** [comment]
Hi @asfalcone, can't share the `Fastfile` but we are using `gym`, `match`, `sigh`, `pem`, `pilot`

Let me know if this is not enough or if there's anything specific you need

**Comment by TKBurner** [comment]
@esttorhe Can you share the full output of one of your lanes and also share the output of `fastlane env`

**Comment by esttorhe** [comment]
@TKBurner `fastlane env` doesn't seem to be a recognisable thing

```console
[!] Could not find 'env'. Available lanes: install_xcode, install_pods, install_bash_aliases, install_ohmyzsh_aliases, install_fish_aliases, setup, fetch_submodules, update_devices, dev_certificates_fetch, dist_certificates_fetch, dev_certificates_update, dist_certificates_update, build_debug, build_release, build_alpha, copy_provisioning_profiles, build_frank, build_core, build_ui, build_playback, build_search, build_payments, build_core_examples, build_ui_examples, build_playback_examples, build_search_examples, build_payments_examples, build_frameworks, build_frameworks_examples, ci, deploy_appstore, deploy_hockey, ab_testing, tests_core, tests_ui, tests_playback, tests_search, tests_payments, tests_all, tests_ruby, tests_app, acceptance_tests
```

**Comment by hjanuschka** [comment]
you should upgrade fastlane - the `env` is only available since **1.106.1**  -> https://github.com/fastlane/fastlane/releases/tag/1.106.1

is your `FASTLAN_PASSWORD`  maybe set to value that is just wrong?

**Comment by TKBurner** [comment]
@esttorhe Run `fastlane run update_fastlane` first. Thanks!

**Comment by esttorhe** [comment]
I will do that but I think you guys are deviating from the issue; this has been present since A LONG time ago and I'm almost 💯 the issue is still there unless someone actually addressed it.

I'll update and try to post the new stuff in here but I doubt that's going to be today since we are almost at our EOD.

**Comment by TKBurner** [comment]
@esttorhe Thanks! If you can provide a sample project affected by the issue that'll help us dig in. 👍

**Comment by esttorhe** [comment]
@TKBurner :( i feel like you guys are not actually reading the description of the issue.

There's no project specific setting I can provide you to reproduce other than this:

- Set up a `FASTLANE_PASSWORD` env var on your `~/.zshrc` or `~/.bashrc` or your `rc` file of choice for your shell with a value of `WRONG_PASSWORD`
- Launch a `fastlane` integration that requires the use of a username and password 
- `fastlane` will fail because the password is wrong and will ask you to set the correct one
- Input the correct password
- `fastlane` will fail saying that the password is incorrect
- Remove the env var from your dotfiles and try again
- `fastlane` will ask for the password
- input the correct password again
- See how `fastlane` succeeds 

I hope this is enough information for you to reproduce

**Comment by hjanuschka** [comment]
@esttorhe  i think now i got it :)

i tried reproducing as you said with following lane:

```ruby
lane :demo do
  latest_testflight_build_number(app_identifier: "krone.at-fivexfive", username: "helmut@januschka.com")
end
```


running it with (pw is wrong):  `FASTLANE_PASSWORD=1234 fastlane demo`
ends with:

```
DEBUG [2016-11-03 18:49:49.49]: Checking if there are any plugins that should be loaded...
INFO [2016-11-03 18:49:49.53]: Driving the lane 'demo' 🚀
INFO [2016-11-03 18:49:49.53]: --------------------------------------------
INFO [2016-11-03 18:49:49.53]: --- Step: latest_testflight_build_number ---
INFO [2016-11-03 18:49:49.53]: --------------------------------------------
INFO [2016-11-03 18:49:49.71]: Login to iTunes Connect (helmut@januschka.com)
WARN [2016-11-03 18:49:50.60]: Variable Dump:
INFO [2016-11-03 18:49:50.60]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"demo"}
ERROR [2016-11-03 18:49:50.60]: Invalid username and password combination. Used 'helmut@januschka.com' as the username.
INFO [2016-11-03 18:49:50.60]: Successfully generated documentation at path '/Users/hja/Desktop/SPORTPORTAL/fastlane/fastlane/README.md'

+------+--------------------------------+-------------+
|                  fastlane summary                   |
+------+--------------------------------+-------------+
| Step | Action                         | Time (in s) |
+------+--------------------------------+-------------+
| 💥    | latest_testflight_build_number | 1           |
+------+--------------------------------+-------------+

ERROR [2016-11-03 18:49:50.61]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Invalid username and password combination. Used 'helmut@januschka.com' as the username.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Invalid%20username%20and%20password%20combination.%20Used%20'helmut@januschka.com'%20as%20the%20username.+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Users/hja/.rvm/gems/ruby-2.2.5/gems/spaceship-0.36.2/lib/spaceship/client.rb:287:in `rescue in send_shared_login_request': [!] The request could not be completed because: (Spaceship::Client::InvalidUserCredentialsError)

```


and does not ask - for password. can you share your fastfile (or the relevant part atleast)?

**Comment by mpirri** [comment]
@esttorhe Just to +1 what @hjanuschka said above - can you provide a simple lane that can demonstrate the issue. Specifically, what is your `Fastfile` calling that allows the password to be entered after it has been found to be invalid? I've tried a few things to try to reproduce the behavior you described, but the tools fail because of the invalid password and don't ask for the password to be re-entered. So, I suspect I'm just trying the wrong things.  😄

**Comment by esttorhe** [comment]
Have you tried match?

If I'm not mistaken this happened with match.

–
Esteban Torres
CraftKollective (http://craftkollective.com) Co-Founder

Phone: (+506)8813-0934 (tel:(+506)8813-0934)
Skype: esteban.a.torres.hernandez
Twitter: @esttorhe (https://twitter.com/esttorhe)

**Comment by mpirri** [comment]
@esttorhe when using `match`, was it with your git password or AppleID password?

**Comment by hjanuschka** [comment]
@esttorhe  i really wan't to help you,and find the bug.
but i am unable to reproduce it.

tried match via fastfile

```
  match(
        git_url: "git@gitlab.krone.at:mobile/IOS-CERTIFICATES.git",
        app_identifier: "krone.at-new"
)
```

results in:

```
[12:10:30]: Driving the lane 'dd' 🚀
[12:10:30]: asdf
[12:10:30]: -------------------
[12:10:30]: --- Step: match ---
[12:10:30]: -------------------

+-----------------------+-------------------------------------------------+
|                        Summary for match 0.10.0                         |
+-----------------------+-------------------------------------------------+
| git_url               | git@gitlab.krone.at:mobile/IOS-CERTIFICATES.git |
| app_identifier        | krone.at-new                                    |
| git_branch            | master                                          |
| type                  | development                                     |
| keychain_name         | login.keychain                                  |
| readonly              | false                                           |
| verbose               | false                                           |
| force                 | false                                           |
| shallow_clone         | false                                           |
| force_for_new_devices | false                                           |
| skip_docs             | false                                           |
+-----------------------+-------------------------------------------------+

[12:10:31]: Cloning remote git repo...
[12:10:39]: 🔓  Successfully decrypted certificates repo
[12:10:39]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: helmut@januschka.com
[12:10:43]: Verifying that the certificate and profile are still valid on the Dev Portal...
The login credentials for 'helmut@januschka.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
Please run this tool again to apply the new password
[12:10:44]: An error occured while verifying your certificates and profiles with the Apple Developer Portal.
[12:10:44]: If you already have your certificates stored in git, you can run `match` in readonly mode
[12:10:44]: to just install the certificates and profiles without accessing the Dev Portal.
[12:10:44]: To do so, just pass `readonly: true` to your match call.
[12:10:44]: 🔒  Successfully encrypted certificates repo
[12:10:44]: Variable Dump:
[12:10:44]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"dd"}
[12:10:44]: Invalid User Credentials

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 💥    | match  | 14          |
+------+--------+-------------+


```

and commandline
```
export FASTLANE_PASSWORD=1234
match -a krone.at-krone1.at

+-----------------------+--------------------+
|          Summary for match 0.10.0          |
+-----------------------+--------------------+
| app_identifier        | krone.at-krone1.at |
| git_branch            | master             |
| type                  | development        |
| keychain_name         | login.keychain     |
| readonly              | false              |
| verbose               | false              |
| force                 | false              |
| shallow_clone         | false              |
| force_for_new_devices | false              |
| skip_docs             | false              |
+-----------------------+--------------------+

[12:07:02]: To not be asked about this value, you can specify it using 'git_url'
URL to the git repo containing all the certificates: git@gitlab.krone.at:mobile/IOS-CERTIFICATES.git
[12:07:03]: Cloning remote git repo...
[12:07:12]: 🔓  Successfully decrypted certificates repo
[12:07:12]: To not be asked about this value, you can specify it using 'username'
Your Apple ID Username: helmut@januschka.com
[12:07:17]: Verifying that the certificate and profile are still valid on the Dev Portal...
The login credentials for 'helmut@januschka.com' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
Please run this tool again to apply the new password
[12:07:18]: An error occured while verifying your certificates and profiles with the Apple Developer Portal.
[12:07:18]: If you already have your certificates stored in git, you can run `match` in readonly mode
[12:07:18]: to just install the certificates and profiles without accessing the Dev Portal.
[12:07:18]: To do so, just pass `readonly: true` to your match call.
[12:07:18]: 🔒  Successfully encrypted certificates repo

```
