### ISSUE TITLE
How to change the screenshot storage directory ?

### ISSUE THREAD

**Issue by Muthukathiravan** [fastlane/fastlane#6627]
### New Issue Checklist
- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

What Xcode version do you use (e.g. 7.3, 8.0)

**Comment by asfalcone** [comment]
@Muthukathiravan Please provide additional information about your question. For example, what tool are you using?

**Comment by Muthukathiravan** [comment]
I m using fastlane tool for grab the screenshots .

**Comment by asfalcone** [comment]
@Muthukathiravan `screengrab` or `snapshot`? Can you provide your Fastfile?

**Comment by Muthukathiravan** [comment]
screengrab

**Comment by asfalcone** [comment]
Are you looking to change the storage directory on the device or on your computer?

**Comment by Muthukathiravan** [comment]
my computer

**Comment by asfalcone** [comment]
You can also run "fastlane action screengrab" to see a list of all of the options you can pass to screengrab 👍

**Comment by Muthukathiravan** [comment]
I have two fastfile one in myproect and another one in lib where I can add

**Comment by asfalcone** [comment]
Add it to whichever Fastfile you've configured _screengrab_ inside of. 

Please try a few things and if you're not able to get it working, provide the configuration you're using and the output of running _fastlane_

**Comment by Muthukathiravan** [comment]
I am using the fastlane screengrab github example

**Comment by Muthukathiravan** [comment]
For that example project i need to change .can you tell me which fastfile in that

**Comment by asfalcone** [comment]
Add it to the Screengrabfile https://github.com/fastlane/fastlane/blob/master/screengrab/example/fastlane/Screengrabfile
```
output_directory "your/directory/here"
```

**Comment by Muthukathiravan** [comment]
i gave output_directory "assets" like this not working

**Comment by Muthukathiravan** [comment]
screengrab --output_directory "your/directory/here" this one worked.. Thanks
But i can store only in app or outside directory?

**Comment by Muthukathiravan** [comment]
How to create directory programatically? How images/phoneScreenshots these path  to reduce?

**Comment by TKBurner** [comment]
@Muthukathiravan You could do something like `sh mkdir nameofdir`

**Comment by Muthukathiravan** [comment]
@TKBurner its creating automatically when I gave new directory..Thanks for suggestions .

**Comment by Muthukathiravan** [comment]
@asfalcone Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run. these error will return while run the test cases

**Comment by Muthukathiravan** [comment]
@asfalcone I have to add fastfile ,appfile,screengrab file for my project.I just copied the screengrab file,fast file and appfile from example to my project..But thats not working how to configure the file into my project..

**Comment by Muthukathiravan** [comment]
@asfalcone I have to add fastfile ,appfile,screengrab file for my project.I just copied the screengrab file,fast file and appfile from example to my project..But thats not working how to configure the file into my project..

**Comment by TKBurner** [comment]
@Muthukathiravan Can you provide your full input and output? Are you running into a specific error? It'll help a lot if we can reproduce this on our end. Thanks so much for working with us 👍

**Comment by Muthukathiravan** [comment]
Just in the emulator..its shows these error..but in data folder of phone screenshots stored..

**Comment by balajitringapps** [comment]
@TKBurner How to create the output directory for flavors dynamically..

**Comment by TKBurner** [comment]
@balajitringapps Just copy paste the ouptput when your run fastlane. Thanks!
