### ISSUE TITLE
[pilot] update build description immediately

### ISSUE THREAD

**Issue by tadelv** [fastlane/fastlane#6628]
### New Issue Checklist
- [☑️] Updated fastlane to the latest version
- [☑️ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I want me and my internal testers to receive the changelog in the email as soon as the build changes it's status to processing (after validation) instead of when it's being submitted for review for external testing. (sometimes i don't want external testing).

For this purpose I've modified pilot's build_manager.rb to upload build data immediately after build is uploaded and has passed validation.

**Comment by TKBurner** [comment]
@tadelv Thanks for sharing. This was previously not possible, but it is now. Glad to hear you implemented it. Where is the PR?

**Comment by tadelv** [comment]
@TKBurner hey, here's the link to the associated pr: #6631 :)

**Comment by TKBurner** [comment]
@tadelv Thanks!

**Comment by tadelv** [comment]
a new PR is tracking this issue now: #6946
