### ISSUE TITLE
Unable to get all apps from iTunes

### ISSUE THREAD

**Issue by fbomb111** [fastlane/fastlane#6636]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

In a rails app I am running:

```
def itunes_all_apps
    begin
      Spaceship::Tunes.login(params[:itunes_username], params[:itunes_password])
      apps = Spaceship::Tunes::Application.all
      render json: apps.to_json, status: 200
    rescue => e
      render json: {error: e, status: 500}.to_json
    end
  end
```

It returns the blank error every time.  I have no other feedback to offer. :/

However, if I change this around slightly, for example getting teams, this works fine:

```
def itunes_all_apps
    begin
      spaceship = Spaceship.login(params[:itunes_username], params[:itunes_password])
      teams = spaceship.teams
      render json: teams.to_json, status: 200
    rescue => e
      render json: {error: e, status: 500}.to_json
    end
  end
```

I'm not using any fast file or or config or anything.  Just passing in a username and password via an api call and trying to get a response back.  I'm new to rails so it may be my implementation of the Spaceship examples provided.

Using spaceship 0.32.3 gem

I really appreciate any suggestions.  Thanks.

##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
# INSERT CONTENT HERE
```

### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

What Xcode version do you use (e.g. 7.3, 8.0)

**Comment by TKBurner** [comment]
Hi @fbomb111 Does the command work when you run it directly from interactive spaceship? Also, you should note only active apps will appear. Thanks!

**Comment by fbomb111** [comment]
@TKBurner Your time and help is extremely appreciate here.

That was a great idea.  I ran irb in terminal and executed only two commands:
```
Spaceship::Tunes.login('myappleid', 'mypassword')
Spaceship::Tunes::Application.all
```

It worked perfectly.

Knowing these 3 things:
1) those 2 commands do work in irb (not an iTunes account problem)
2) those 2 commands do not work when using them in my rails app
2) 2 similar commands do work in my rails app in the exact same method (not a routes problem) with the exact same parameters (not a params problem) if I call:
```
spaceship = Spaceship.login('myappleid', 'mypassword')
teams = spaceship.teams
```

Can you derive any thoughts from that?  Is there a difference in the way spaceship is used in irb and the way it's used when installed as a gem in a rails project?  My project is using spaceship 0.32.3.

**Comment by fbomb111** [comment]
Updated to Spaceship 0.36.1.  No difference.

**Comment by fbomb111** [comment]
Running just

```
def itunes_all_apps
      Spaceship::Tunes.login(params[:itunes_username], params[:itunes_password])
      apps = Spaceship::Tunes::Application.all
      render json: apps.to_json, status: 200
  end
```

Gives me IOError (not opened for reading) line 58 (render)

**Comment by fbomb111** [comment]
Solved it.  

This method: http://www.rubydoc.info/gems/spaceship/Spaceship/Tunes/Application#all-class_method

Does not return an array, at least not one that can be serialized into json.  Calling apps.to_s works while apps.to_json gave me this 5 day wild goose chase.

**Comment by TKBurner** [comment]
@fbomb111 Awesome! Really glad you got up and running!
