### ISSUE TITLE
Assertion: Trigger script exited with code: 127

### ISSUE THREAD

**Issue by madhu-b** [fastlane/fastlane#6638]
### Issue Description

When i run fast lane beta from from After integration trigger i get following error. 
##### Complete output when running fastlane, including the stack trace and command used

Bot Issue for Mumo Bot (trigger error)
Integration #23 of Mumo Bot
Open in Xcode: xcbot://Liftoff’s MacBook Pro/botID/1328fcde84c1b9a245f92f401601bef4/integrationID/45e1a5f4b5963b9223c391bb6100e77d

Assertion: Trigger script exited with code: 127 /var/folders/sn/_y1l8_217370xt3g12sh637r000087/T/095CF91F-0C55-43E3-B377-11D4213E8CD4-50235-0000062248284BE1: line 4: fastlane: command not found

File: (null):(null)

Full logs for this integration are attached.

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

fastlane_version "1.105.3"
default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    #increment_build_number
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  #lane :beta do
   # cert
    #sigh
   # gym(scheme: “Mumo”)
   # pilot
    #testflight
  #end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

desc "Submit a new Beta Build to crashlytics"
    lane :beta do
   #increment_build_number #agvtool next-version -all need to run once from beginging, more details :https://developer.apple.com/library/mac/qa/qa1827/_index.html
    cocoapods
    cert
    sigh
    gym(
    scheme: “Mumo”,
    output_directory: "$HOME/releases/",
    archive_path: "$HOME/Mumo",
    )
    crashlytics(api_token: 'e5778eb604687e3ff4780bc817488352ece97526’,
                build_secret: '1899d0e6f4bfc0b2d60bd854a9732cf2320e8e7c46074a23e402e9014e5a1650')

  end

end

fastlane version (run `fastlane -v`): fastlane 1.105.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? i don't know

What Xcode version do you use (e.g. 7.3, 8.0) 7.3.1

**Comment by hjanuschka** [comment]
have you installed fastlane, looks like the xcbot couln't find the fastlane binary 😢 
see here: https://github.com/fastlane/fastlane#installation

**Comment by madhu-b** [comment]
Yes.
I really appreciate your help. Thanks for the reply

*Logs from My user*
which fastlane

/usr/local/bin/fastlane

Liftoffs-MacBook-Pro:Mumo liftoff$ fastlane -v

fastlane 1.105.3


*Logs from xcsbuidd*

sudo su - _xcsbuildd

Password:

Liftoffs-MacBook-Pro:~ _xcsbuildd$ which fastlane

/usr/local/bin/fastlane

Liftoffs-MacBook-Pro:~ _xcsbuildd$ fastlane -v

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in
`to_specs': Could not find 'fastlane' (>= 0) among 16 total gem(s)
(Gem::LoadError)

from
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in
`to_spec'

from
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in
`gem'

from /usr/local/bin/fastlane:22:in `<main>'

Liftoffs-MacBook-Pro:~ _xcsbuildd$ fastlane -version

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in
`to_specs': Could not find 'fastlane' (>= 0) among 16 total gem(s)
(Gem::LoadError)

from
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in
`to_spec'

from
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in
`gem'

from /usr/local/bin/fastlane:22:in `<main>'

Liftoffs-MacBook-Pro:~ _xcsbuildd$



What could be going wrong. If u think i don't have fast lane binary
installed. sudo gem install fastlane --verbose running this on under my
user would work?


Waiting for your valuable reply



Thank you

Madhu

Thanks & Regards

Madhu.

On Thu, Oct 20, 2016 at 12:37 PM, Helmut Januschka <notifications@github.com

**Comment by hjanuschka** [comment]
you first of all have to upgrade your ruby as this looks like the built-in apple one, wich is heavily outdated and has ssl issues.

```
brew update && brew upgrade openssl && brew install ruby
```

after that - try again to install fastlane:
(should work with any user)
```
sudo gem install fastlane
```

the best would be if you go with a bundler based solution, but its not required, see documentation on how to go with bundler: https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

remember from then on you have to call `bundle exec fastlane` instead of `fastlane` ;)

**Comment by madhu-b** [comment]
I did install bundle and my script looks like this

bundle install

bundle update

cd Mumo

bundle exec fastlane beta




1.

Bot Issue for Mumo Bot (error in Mumo-Bridging-Header.h:21)

Integration #29 of Mumo Bot

Open in Xcode: xcbot://Liftoff’s MacBook
Pro/botID/1328fcde84c1b9a245f92f401601bef4/integrationID/45e1a5f4b5963b9223c391bb61039bb0


Assertion: 'Branch/Branch.h' file not found

File: Mumo/Mumo/Mumo-Bridging-Header.h:21


Introduced 2 integrations ago


Full logs for this integration are attached.



2.


Bot Issue for Mumo Bot (error)

Integration #29 of Mumo Bot

Open in Xcode: xcbot://Liftoff’s MacBook
Pro/botID/1328fcde84c1b9a245f92f401601bef4/integrationID/45e1a5f4b5963b9223c391bb61039bb0


Assertion: Failed to import bridging header
'/Library/Developer/XcodeServer/Integrations/Caches/1328fcde84c1b9a245f92f401601bef4/Source/Mumo/Mumo/Mumo-Bridging-Header.h'

File: (null):(null)


Introduced 2 integrations ago


Full logs for this integration are attached.


3.


Bot Issue for Mumo Bot (trigger error)

Integration #29 of Mumo Bot

Open in Xcode: xcbot://Liftoff’s MacBook
Pro/botID/1328fcde84c1b9a245f92f401601bef4/integrationID/45e1a5f4b5963b9223c391bb61039bb0


Assertion: Trigger script exited with code: 127
/var/folders/sn/_y1l8_217370xt3g12sh637r000087/T/87A15D7E-1FED-4C7B-B321-603C88C5A615-11771-00000AA106A3F3C8:
line 2: bundle: command not found

/var/folders/sn/_y1l8_217370xt3g12sh637r000087/T/87A15D7E-1FED-4C7B-B321-603C88C5A615-11771-00000AA106A3F3C8:
line 3: bundle: command not found

/var/folders/sn/_y1l8_217370xt3g12sh637r000087/T/87A15D7E-1FED-4C7B-B321-603C88C5A615-11771-00000AA106A3F3C8:
line 5: bundle: command not found


File: (null):(null)


Full logs for this integration are attached.


*Do we need to create any symbolic link for bundle?*






Thanks & Regards

Madhu.

On Thu, Oct 20, 2016 at 12:54 PM, Helmut Januschka <notifications@github.com

**Comment by madhu-b** [comment]
*bundle: command not found :(*

Bot Issue for Mumo Bot (trigger error)
Integration #31 of Mumo Bot
Open in Xcode: xcbot://Liftoff’s MacBook
Pro/botID/1328fcde84c1b9a245f92f401601bef4/integrationID/45e1a5f4b5963b9223c391bb610462e5

Assertion: Trigger script exited with code: 127
/var/folders/sn/_y1l8_217370xt3g12sh637r000087/T/4D8923E8-FCA3-4E94-B939-15E6504D1BDF-22714-00000D71820A4F67:
line 2: bundle: command not found
/var/folders/sn/_y1l8_217370xt3g12sh637r000087/T/4D8923E8-FCA3-4E94-B939-15E6504D1BDF-22714-00000D71820A4F67:
line 3: bundle: command not found
/var/folders/sn/_y1l8_217370xt3g12sh637r000087/T/4D8923E8-FCA3-4E94-B939-15E6504D1BDF-22714-00000D71820A4F67:
line 5: bundle: command not found

File: (null):(null)

Full logs for this integration are attached.

Thanks & Regards

Madhu.

**Comment by TKBurner** [comment]
@madhu-b Thanks for following up. This doesn't seem like a fastlane specific issue but a ruby issue. I'm not sure we are the best to help. Can you run `which ruby` and also run `ruby -v` and share the output?

**Comment by madhu-b** [comment]
Thank you

here is the ruby details

Liftoffs-MacBook-Pro:Mumo liftoff$ which ruby

*/usr/local/bin/ruby*

Liftoffs-MacBook-Pro:Mumo liftoff$ ruby -v

*ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]*

Liftoffs-MacBook-Pro:Mumo liftoff$



Thanks & Regards

Madhu.

**Comment by TKBurner** [comment]
@madhu-b Can you share your full input and output of the error message? I want to figure out what command is being run that is resulting in this error. Thanks for working with me and I hope you have a good weekend.
