### ISSUE TITLE
Hockey Upload failing with proxy

### ISSUE THREAD

**Issue by speedy-afr** [fastlane/fastlane#6639]
### New Issue Checklist
- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

We are operating behind a proxy and have created the env variable SPACESHIP_DEBUG=1 in .evn. This works fine for cert and sigh, but the action hockey fails with Broken pipe - SSL_connect. We are using Charles as a Proxy.
##### Complete output when running fastlane, including the stack trace and command used

```
INFO [2016-10-20 10:50:52.77]: --------------------
INFO [2016-10-20 10:50:52.77]: --- Step: hockey ---
INFO [2016-10-20 10:50:52.77]: --------------------
INFO [2016-10-20 10:50:52.81]: Starting with ipa upload to HockeyApp... this could take some time.
WARN [2016-10-20 10:52:08.36]: Variable Dump:
INFO [2016-10-20 10:52:08.36]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios hockeyAppUpload"}
ERROR [2016-10-20 10:52:08.36]: Broken pipe - SSL_connect
INFO [2016-10-20 10:52:08.37]: Successfully generated documentation at path '/Users/tsbuildslave/jenkins/slave/workspace/ts-mobile-ios-0010-xcode8-build/Ticketshop 2.0/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | xcode_select                        | 0           |
| 4    | setup_jenkins                       | 0           |
| 💥    | hockey                              | 75          |
+------+-------------------------------------+-------------+

ERROR [2016-10-20 10:52:08.38]: fastlane finished with errors
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

```
fastlane_version "1.105.2"

default_platform :ios

platform :ios do
  before_all do
    xcode_select "/Applications/Xcode8.app"
    #update_fastlane
    setup_jenkins
  end

  lane :build do
    cert(output_path: "output")
    ENV["test_provisioning_profile"] = sigh(output_path: "output")
    gym(
        scheme: "Ticketshop", 
        output_directory: "output", 
        output_name: "Ticketshop.ipa", 
        use_legacy_build_api: true,
        xcargs: "$GCC_PREPROCESSOR_DEFINITIONS STAGE=\"ADEV\" HOCKEY_APP_ID=\"XXXXXXXXXXXXX\""
        ) 
  end

  lane :hockeyAppUpload do 
    hockey(
       api_token: "XXXXXXXXXXXXXXX",
       ipa: "output/Ticketshop.ipa"
    )
  end

end
```
### Environment

fastlane version (run `fastlane -v`):
INFO [2016-10-20 10:47:30.57]: Your fastlane version 1.105.2 matches the minimum requirement of 1.105.2  ✅
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
no
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
no
What Xcode version do you use (e.g. 7.3, 8.0)
8.0

**Comment by TKBurner** [comment]
@speedy-afr Thanks for reaching out. Can you add the --verbose flag to your lane and share the output? It looks like you might have an issue with openssl on your machine. I'd suggest investigating this.

**Comment by speedy-afr** [comment]
This is already the output of the verbose mode. When we connect the machine via a personal hotspot and disable the proxy the upload works fine.

**Comment by TKBurner** [comment]
Hi @speedy-afr Thanks for letting me know. Can you reach out to hockey about preferred proxy settings? It doesn't seem like this is a fastlane issue. Thanks!
