### ISSUE TITLE
 Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.

### ISSUE THREAD

**Issue by Muthukathiravan** [fastlane/fastlane#6641]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`):

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

What Xcode version do you use (e.g. 7.3, 8.0)

**Comment by Muthukathiravan** [comment]
@TKBurner most of the devices does not have sdcard in above api level 21,so ly the screenshots can not retrive from the particular path..so this issue happened

**Comment by TKBurner** [comment]
@Muthukathiravan Thanks for following up. Did you find a viable workaround? If not share your full input and output. Hope that you have a great weekend!

**Comment by Muthukathiravan** [comment]
some times if device does not have any sdcard means,its search for remote object location.sometime its not search any location.really its confusing..

**Comment by Muthukathiravan** [comment]
remote object '/data/data/com.xxx.xxx/app_screengrab' does not exist
 Exit status: 1
Make sure you've used Screengrab.screenshot() in your tests and that your expected tests are being run.
These error will occur for all devices..If you need anything other than that

[!] No screenshots were detected 📷❌
