### ISSUE TITLE
Unable to add both adhoc:false and development:true

### ISSUE THREAD

**Issue by damienmollard** [fastlane/fastlane#6642]
Hello, 

My old build doesn't work for these commit : https://github.com/fastlane/fastlane/commit/7fcd9ec4405174ae4fd8a96bf33631d21717ac0e

I call the method sigh with both adhoc and development with ternary condition : 
    sigh(
          app_identifier: my.identifier.com,
          adhoc: ENV["PROV_TYPE"]=="Adhoc" ? "true" : "false",
          development: ENV["PROV_TYPE"]=="Dev" ? "true" : "false",
          output_path: "./Provisionings",
          filename: "myprovisioning.mobileprovision",
          force: true)

I have these error : 
Error resolving conflict between options: 'adhoc' and 'development'
You can't enable both :development and :adhoc

**Comment by TKBurner** [comment]
Hi @damienmollard Thanks for following up. Did this previously work? I think you'll need to place the logic around the whole adhoc/development lines.

**Comment by smumryak** [comment]
Hey guys! I'm experiencing same issue. My case is that I've created lane that runs sigh based in lane's input parameters and in different cases there could be development, adhoc or production profiles used by sigh. And the reason i'm using both parameters is that i don't want to duplicate code. Reopening issue.

**Comment by KrauseFx** [comment]
Please submit a new issue for this  @smumryak
