### ISSUE TITLE
Frameit: Add option to Framefile.json to skip adding frame ie. ONLY add text

### ISSUE THREAD

**Issue by xaphod** [fastlane/fastlane#6643]
### New Issue Checklist
- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I'd like to be able to define in my `Framefile.json` (in the "data" section) that certain screens ONLY have the text added to the top -- the frames don't get added. This is because it is popular to create screens that show multiple devices, ie. the frames are already in the screenshot (custom, not full size). But then there's the issue of adding 10 languages' of text to these... currently I have to do this manually. It seems like it would be simple for fastlane to just skip the framing part and still do the part that adds the text at the top.

Example `Framefile.json`showing "skipFraming" (my imaginary new option) for the first screen:

```
{
  "default": {
    "keyword": {
      "color": "#00C7C7",
      "fonts": [
        {
          "font": "./NotoSansCJKsc-Regular.otf",
          "supported": ["zh-Hans"]
        },
        {
          "font": "NotoSansCJKtc-Regular.otf",
          "supported": ["zh-Hant"]
        },
        {
          "font": "./OpenSans-Regular.ttf",
          "supported": ["de-DE", "en-US", "es-ES", "fr-FR", "it", "sv"]
        }
      ]
    },
    "title": {
      "color": "#000000",
      "fonts": [
        {
          "font": "./NotoSansCJKsc-Regular.otf",
          "supported": ["zh-Hans"]
        },
        {
          "font": "NotoSansCJKtc-Regular.otf",
          "supported": ["zh-Hant"]
        },
        {
          "font": "./OpenSans-Regular.ttf",
          "supported": ["de-DE", "en-US", "es-ES", "fr-FR", "it", "sv"]
        }
      ]
    },
    "background": "./background.jpg",
    "padding": 35,
    "show_complete_frame": false
  },

  "data": [
    {
      "filter": "FirstScreen",
      "skipFraming": "true",
      "title": {
        "color": "#00C7C7"
      }
    },
    {
      "filter": "Connected",
      "title": {
        "color": "#FC375B"
      }
    },
    {
      "filter": "ShowingPhoto",
      "title": {
        "color": "#27282D"
      }
    },
    {
      "filter": "ShowingAlert",
      "title": {
        "color": "#00C7C7"
      }
    }
  ]
}
```

**Comment by TKBurner** [comment]
@xaphod Thanks for reaching out. Right now this isn't possible as you've noted. I've made this a feature request. Are you interested in working on this as a PR? Thanks!

**Comment by xaphod** [comment]
@TKBurner at the moment i'm slammed, but in a month or two I might be able to, who knows.

**Comment by TKBurner** [comment]
@xaphod Thanks for following up. I'll leave this open for the time being.
