### ISSUE TITLE
Android on danger device_grid

### ISSUE THREAD

**Issue by StevePotter** [fastlane/fastlane#6646]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am building an app via react native and have fastlane directories for each of those projects.  I'm also using the danger device_grid plugin to render iOS.  I'd like to also include android in that.  I've included the dangerfile below.  Instead of using Fastland.OneOff, I'd like to be able to run lanes from both my android and ios directories.  Something like this:

```
ios_public_key = fastlane::FastFile.initialize("ios/fastlane/Fastfile").runner.execute(:upload_to_appetize)

device_grid.run(
  public_key: ios_public_key,
  languages: ["en"],
  devices: ["iphone6splus", "ipadair"]
)

android_public_key = Fastlane::FastFile.initialize("android/fastlane/Fastfile").runner.execute(:upload_to_appetize)

device_grid.run(
  public_key: android_public_key,
  languages: ["en"],
  devices: ["nexus5", "nexus7"]
)
```

I've already noticed a few things.  First, the android devices have no image associated with them.  Also since the public key would be different for android and ios, there would have to be separate grids, or new properties added to the device_grid.

Anyway, is something like I described possible?  Thanks!

### DANGERFILE
options = {
  xcodebuild: {
      workspace: "ios/Vydia.xcworkspace",
      scheme: "Staging"
    }
}

require 'fastlane'
result = Fastlane::OneOff.run(action: "build_and_upload_to_appetize",
                          parameters: options)

device_grid.run(
  public_key: result,
  languages: ["en"],
  devices: ["iphone6splus", "ipadair"]
)

### Environment

fastlane version (run `fastlane -v`):
1.105.0   
Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
yes
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
rvm
What Xcode version do you use (e.g. 7.3, 8.0)
8.0

**Comment by KrauseFx** [comment]
Sorry, device grid is currently only available for iOS apps

**Comment by StevePotter** [comment]
Thanks @KrauseFx.  I have another question then.  What's the ruby command for me to run a lane from a fastfile I specify?  I tried:
result = Fastlane::FastFile.initialize("ios/fastlane/Fastfile").runner.execute(:myaction) but got an error.  Is there something else I need to do?

**Comment by KrauseFx** [comment]
@StevePotter What's the error? You didn't share any details. Also, could you submit this in a new issue, as it's not related?
