### ISSUE TITLE
Bitbucket Pipeline support

### ISSUE THREAD

**Issue by simformsolutions** [fastlane/fastlane#6647]
Do fastlane support bitbucket pipeline integration ? If not are you planning to support that in near future ?

**Comment by TKBurner** [comment]
Hi @simformsolutions I haven't seen anyone doing this, but I'd be curious if you are running into any specific errors. Thanks!

**Comment by greggmojica** [comment]
+1

**Comment by KrauseFx** [comment]
@greggmojica how could fastlane support it better?

**Comment by greggmojica** [comment]
@KrauseFx Do you have any docs on how to setup fastlane with bitbucket pipelines? It's a relatively new CI so that's why I ask.

**Comment by hjanuschka** [comment]
@greggmojica can you share a sample `.bitbucket-pipeline.yml` e.g. of another app building/running with it, than i could maybe help you adopt it to run fastlane.


according to docs, it should be something like this:


```yaml
pipelines:
  default:
    - step:
        script:
          - fastlane lane
```

**Comment by greggmojica** [comment]
@hjanuschka I'm afraid I'm unsure how to setup a pipeline with fastlane. I've used bitbucket pipelines with Web Applications in the past, but not sure how the setup should be configured for fastlane. Thanks.

**Comment by hjanuschka** [comment]
can you share a setup you'v used for a web application?

**Comment by greggmojica** [comment]
@hjanuschka Yes:

<pre>
image: python:3.5.1

pipelines:
  branches:
    master:
      - step:
          script:
             - apt-get update
             - apt-get install -y zip
             - pip install boto3==1.3.0
             - cd gradology
             - zip ../server -r * .[^.]* *
             - python myScript.py
</pre>

**Comment by hjanuschka** [comment]
tbh honest first of all you should try to find out if the support macOS, as otherwise, you'll run into alot of other issues.



but once its clear that this runs on a mac - the following should do it.:

pipelines:
  branches:
    master:
      - step:
          script:
             - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
             - brew install fastlane
             - fastlane beta

**Comment by greggmojica** [comment]
@hjanuschka Thank you. Should the docker image be Ruby?

**Comment by hjanuschka** [comment]
i think you have to run it outside docker, so i am unsure about the image.
best would be to ask the bitbucket support on how to run pipelines on a mac.
