### ISSUE TITLE
iTC now using "no" for Norwegian

### ISSUE THREAD

**Issue by odrobnik** [fastlane/fastlane#6648]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

We added Norwegian as app store description on iTunes Connect and downloaded the metadata. A folder `no` was created.

However, in Xcode `nn` is used for Norwegian. `no` is an unsupported language code.

So the problem is this:
- if you put `no` in the Snapfile my iOS 10 simulator runs in English, producing Englisch screenshots in the `Screenshots/no` folder. Thus the wrong language is uploaded.
- if you put `nn` in the Snapfile, the simulator produces Norwegian screenshots, but they end up in an `Screenshots/nn` folder. Since `deliver` is looking for the Norwegian screenshots in the wrong folder nothing is being uploaded.

I suggest that for uploading `no` screenshots you also accept files residing in the `nn` folder.

**Comment by bjornoss** [comment]
Just a quick comment. 
We use two language codes in Norway, `nb` (NO-nb, Bokmål) and `nn` (NO-nn, Nynorsk). 
`nb` is the preferred written standard.
We use only nb i our projects.

**Comment by TKBurner** [comment]
@odrobnik @bjornoss Thanks for sharing this. I reaching out to the core team so we can fix this. Let me know if either of you is interested in submitting a PR. Thanks!

**Comment by ohwutup** [comment]
Hey @odrobnik! Thanks for submitting the issue... I tried reproducing this and found that using `nb` as @bjornoss stated is the best approach. While there a number of Norwegian localization options in Xcode, Norwegian Bokmål is the preferred standard and works alongside _deliver_ with screenshots and metadata being saved into `./fastlane/screenshots/no/` and `./fastlane/metadata/no/` directories respectively.

In the `Snapfile` that I used to get this issue solved, I used the following languages array:
``` ruby
languages([
  "en-US",
  "no"
])
```
This is what it looks in Xcode for my project's Localization settings.
![screen shot 2016-10-26 at 3 04 19 pm](https://cloud.githubusercontent.com/assets/2587018/19741122/7e9aef0e-9b8d-11e6-8053-c50a48a110e8.png)

Please let us know if you have any more questions! 🚀

**Comment by odrobnik** [comment]
@ohwutup When you use languages no, does it pass nb as locale to Simulator?

**Comment by KrauseFx** [comment]
@odrobnik _snapshot_ doesn't modify the language codes, so it would just pass whatever you provide in your `Snapfile`. 

You can also provide 2 values for one language, to define its exact locale (not sure if that helps):

```ruby
languages([
  "en-US",
   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])
```

**Comment by odrobnik** [comment]
@KrauseFx i.e. If the language in Snapfile is either nn or nb, then the sim language should be that, but the output folder name needs to be no

**Comment by ohwutup** [comment]
@odrobnik I think we would want to keep the output folder matching the code that is in your Snapfile for consistency. While Xcode uses `nb`, we found through our testing that `no` works when passed to the simulator and on iTC.

**Comment by odrobnik** [comment]
Then there IS still a problem. If I pass no in Snapfile the sim runs in English. If I pass nn, the it runs in nn, but the folder name for delivery is incorrect!

Von meinem iPhone gesendet

**Comment by bjornoss** [comment]
We use `no` in the Snapfile and the simulator runs in Norwegian as expected. 
We save our strings in the `nb.lproj` folder.

**Comment by ohwutup** [comment]
@odrobnik we see the same situation as @bjornoss. Is there any chance you could provide us with a sample project that demonstrates that issue?

**Comment by odrobnik** [comment]
The problem is not with nb, but with nn. If you pass no to sim, it does not pick up the nb localization. Our workaround will probably have to be that we switch to use nb as well.

**Comment by TKBurner** [comment]
@odrobnik Thanks for working with us. If you can provide a sample project we'll be able to action this a lot faster. Is your workaround working for you?

**Comment by odrobnik** [comment]
I moved my nn localization to nb. Snapfile has nb. output arrives in no. Works for me.

Your problem is, if nb is the only localization and you put nb in Snapfile output is put into nb.

**Comment by ohwutup** [comment]
Thanks for confirming that @odrobnik! Out of curiosity, is there a reason why you were using `nn` in the first place?

**Comment by odrobnik** [comment]
@ohwutup I cannot tell you why I ended up with `nn` probably just picked one that sounded reasonable to me, as I don't know which is the more predominant language in Norway.

**Comment by KrauseFx** [comment]
Great to hear this got resolved 👍

**Comment by odrobnik** [comment]
@KrauseFx @ohwutup Now something weird happened. I ran `snapshot` and even though I have `nb` in the languages, the screenshots did end up in the `nb` folder. `deliver` - freshly updated - did not pick up the screenshots in there, but showed a confirmation page with empty `no` screenshots. 

I have to copy screenshots from `nb` into `no` for it to work. 

snapshot is 1.6.3
deliver is 1.15.1
