### ISSUE TITLE
Gym doesn't escape output parameters properly for xcpretty calls

### ISSUE THREAD

**Issue by wiedem** [fastlane/fastlane#6653]
### Issue Description

Gym does not escape paths inside the `pipe` function [build_command_generator.rb#86](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/build_command_generator.rb#L86) which causes a malformed call of `xcpretty` if the paths to the output files (`xcpretty_report_json`, `xcpretty_report_junit`, `xcpretty_report_html`) contain any whitespace:

```
xcodebuild -workspace ./Test.xcworkspace -scheme Test -destination 'generic/platform=iOS' -archivePath /Test.xcarchive clean archive | tee /Test.log | xcpretty  --report json-compilation-database --output  /My Path With Spaces/compile_commands.json
```

As you can see the `output` argument is `--output /My Path With Spaces/compile_commands.json` but it should be `--output /My\ Path\ With\ Spaces/compile_commands.json`.

Problem for `xcpretty_report_json` is solved if you change [Line 86](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/build_command_generator.rb#L86) to

``` ruby
pipe << report_output_json.shellescape`
```
### Configuration Files

Fastfile:

``` ruby
report_json_path = "/My Path With Spaces/compile_commands.json"

gym(
      scheme: scheme,
      clean: true,
      buildlog_path: buildlog_path,
      disable_xcpretty: false,
      xcpretty_report_json: report_json_path,
      suppress_xcode_output: false
)
```
### Environment

fastlane version: 1.105.3

**Comment by hjanuschka** [comment]
nice catch - i did a PR with your proposed solution https://github.com/fastlane/fastlane/pull/6655

**Comment by wiedem** [comment]
> nice catch - i did a PR with your proposed solution #6655

Thanks for the PR, didn't find the time yet to create one on my own.

However, I think [L80](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/build_command_generator.rb#L80) and [L83](https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/build_command_generator.rb#L83) need to be changed as well.

**Comment by hjanuschka** [comment]
@wiedem  thx for the hint - fixed it

**Comment by hjanuschka** [comment]
@wiedem  PR just got merged 👏
