### ISSUE TITLE
Access to the common name of `match`'s managed certificate

### ISSUE THREAD

**Issue by sibljon** [fastlane/fastlane#6654]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

_Omitted because I assume it not to be relevant, since I am asking a question rather than troubleshooting._

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  match(
    app_identifier: build_config.bundle_id, 
    readonly: true,
    verbose: true,
    force_for_new_devices: true,
    git_branch: build_config.codesigning_git_branch,
    type: build_config.provisioning_type,
    git_url: "[omitted]",
  )

  gym(
    workspace: build_config.workspace,
    scheme: build_config.scheme,
    configuration: build_config.xc_build_config,
    output_name: archive_file_name,
    output_directory: "#{build_folder}/archives",
    xcargs: xcargs,
    clean: true #build_config.app_store_build?
  )
```

_NOTE: I'm happy to provide any of the values that are stored in variables above, as needed._

### Environment

fastlane version (run `fastlane -v`):

fastlane 1.105.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

rvm

ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]

What Xcode version do you use (e.g. 7.3, 8.0)

8.1 beta 3

### My question:

I'm using a user-defined setting (see below) to specify the `PROVISIONING_PROFILE_SPECIFIER`:

![screen shot 2016-10-20 at 6 27 15 pm](https://cloud.githubusercontent.com/assets/442307/19583588/d7d13668-96f2-11e6-8f9b-419e10de41ca.png)

I'm using `match` to create and sync the certificate and provisioning profile.

However, my code signing identity (`CODE_SIGN_IDENTITY`) is set to `iPhone Developer`:

![screen shot 2016-10-20 at 6 28 08 pm](https://cloud.githubusercontent.com/assets/442307/19583627/10ecf48c-96f3-11e6-82d1-b971abe0312b.png)

And on some machines, `iPhone Developer` is resolved to a certificate that was not created with `match`, is not included in the provisioning profile (that `match` manages), and thus produces the following error:

> ❌  Provisioning profile "match Development com.sprucehealth.messenger-dev" doesn't include signing certificate "iPhone Developer: Ray Lillywhite (Y3W8W5AJ86)".

Is there a way to get the common name of the certificate managed by `match` (or, really, whatever certificate on the machine that is included in the provisioning profile being used) such that I can use it to explicitly set `CODE_SIGN_IDENTITY` to prevent this incorrect resolution of `iPhone Developer`? 

For example, does this live in an environment variable that I can access that contains the exact common name of the certificate?

**Comment by hjanuschka** [comment]
you could set the signing identity using `xcargs` - > `CODE_SIGN_IDENTITY='iPhone Developer: Josh'

**Comment by hjanuschka** [comment]
ok got it you want to retrieve the exact value you require for `CODE_SIGN_IDENTITY` from a .cert?
i am not 100% sure how to do this, but i ll try to have a look

@TKBurner maybe you have an idea?

**Comment by hjanuschka** [comment]
@sibljon  ok took me a while - since i am on a business trip in a different timezone.
anyway - i guess your best way should be - relying on `match`  setting the right env vars.

so with match you get an output like this.

```
| Profile UUID        | sigh_krone.at-fivexfive_appstore              | 11156606-76cc-4122-a191-7d3ca18fc9d1 |
```

in that case - you could use following on `gym`

```
gym(
    xcargs: "CODE_SIGN_IDENTITY='#{ENV['sigh_krone.at-fivexfive_appstore']}'"
)
```

or you set it directly in the xcode proj. - by setting the "Other" and entering `$(sigh_krone.at-fivexfive_appstore)` - and nevermind the display of "not codesigning"  - its because env is not set, without match run.

![bildschirmfoto 2016-10-22 um 21 48 04](https://cloud.githubusercontent.com/assets/2891702/19624247/3dd07ed8-98a1-11e6-95f4-7b0cca6f5e38.png)



for sure - please adopt to your app-identifier 😄 
let me know if it worked.

**Comment by hjanuschka** [comment]
@sibljon  ok after a few hours of sleep:

not 100% sure if this will work out for you - but you could use spaceship - to query the live certificates at itunesconnect
```
cert=Spaceship.certificate.development.all.find_all { |i| i.name == "Helmut Januschka" }
puts cert.first.owner_id
```



![bildschirmfoto 2016-10-23 um 08 05 17](https://cloud.githubusercontent.com/assets/2891702/19627250/849f8786-98f7-11e6-94a5-5813fb9c8ba5.png)


![bildschirmfoto 2016-10-23 um 08 05 32](https://cloud.githubusercontent.com/assets/2891702/19627251/87c09d10-98f7-11e6-8b90-d5827ff94e2d.png)



even if this works - i suggest you to read the code signing guide, as i think this is not an elegant solution et-all.
i think it would be better, to get rid of already importet, non-match managed certs, to use a custom keychain.

e.g.:


````
create_keychain(name: "my_own_keychain.keychain", unlock: true, default_keychain: true)
match
gym
deliver
delete_keychain(name: "my_own_keychain.keychain");

```

**Comment by sibljon** [comment]
@hjanuschka thanks so much for looking into this for me, and for the detailed response!

I think the custom keychain will work best for us, as we have apps in our team that we haven't been able yet to migrate to use `match`. Thanks for the idea of using Spaceship as well, as I'm sure that may be helpful for us in the future (or perhaps for a future reader of this PR), but I agree that the ideal solution is to let `match` manage all of our certs (which we plan to do long-term). Thanks again!
