### ISSUE TITLE
deliver download_all doesn't append newlines to text files.

### ISSUE THREAD

**Issue by remcohaszing** [fastlane/fastlane#6656]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description

`deliver download_all` doesn't append newlines to text files.

Some philosophies say that a line in a text file end with a newline. This makes the files created by Deliver technically not text files.

Many editors add a newline when saving a file, making changes compared to what deliver pulls in when just opening and saving a file.

Git adds `\ No newline at end of file` when diffing. This is annoying, though correct.

### Environment

fastlane version (run `fastlane -v`):

```
$ fastlane -v
fastlane 1.105.3
$ deliver -v
deliver 1.14.2
```

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? No

What Xcode version do you use (e.g. 7.3, 8.0) 7.3

**Comment by hjanuschka** [comment]
@remcohaszing  there is no `download_all` on `deliver` - you mean the `download_metadata` ?

**Comment by KrauseFx** [comment]
Thanks @hjanuschka, this got merged and will be ready with the next release  🚀

**Comment by remcohaszing** [comment]
Yes, I meant `download_metadata`. Thanks for the quick fix!
