### ISSUE TITLE
Checking at archiving time if archive was initiated by gym or manually - in xcconfig file

### ISSUE THREAD

**Issue by Sajjon** [fastlane/fastlane#6657]
### New Issue Checklist
- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

In an xcconfig file (I am still not sure which is the correct syntax for conditional variables, [I just asked on StackOverflow](http://stackoverflow.com/q/40171376/1311272) I want to determine if the archiving was initiated manually or by fastlane gym, and set the correct provisioniong profile accordingly. So that I can archive both via gym and manually.

**Is this possible?**

```
    _IS_ARCHIVING_WITH_GYM = YES // <---- How to check if achieving with fastlane gym?

    #ifdef _IS_ARCHIVING_WITH_GYM
        _PROVISIONING_PROFILE_APP_STORE = sigh_com.mycomp.app_appstore
    #else
        _PROVISIONING_PROFILE_APP_STORE = match AppStore com.mycomp.app
    #endif

    PROVISIONING_PROFILE_SPECIFIER[config=Release] = $(_PROVISIONING_PROFILE_APP_STORE)
```
##### Complete output when running fastlane, including the stack trace and command used

Irrelevant
### Configuration Files

Irrelevant
### Environment

fastlane version (run `fastlane -v`):
fastlane 1.105.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
No

What Xcode version do you use (e.g. 7.3, 8.0)
Xcode 8.0 (8A218a)

**Comment by TKBurner** [comment]
@Sajjon Thanks for reaching out. Couldn't you use a naming convention on your archives to determine if it was build by gym?
