### ISSUE TITLE
Feature Request: Push Certificates in Match

### ISSUE THREAD

**Issue by vbresults** [fastlane/fastlane#6658]
It would be a great help if we could store, retrieve and use all of the associated parts of push certificates just like other certificates managed by match, simple has the same benefits.

**Comment by TKBurner** [comment]
Thanks for the suggestion. What functionality would you like to see the most?

**Comment by vbresults** [comment]
@TKBurner Simply storing the certificate components in the repository, and being able to fetch them as a drop-in replacement for pem, the same way match does it for sigh.

I do use PEM right now.

I'd like to see `match(type: "apns", app_id:"my.example.app" p12:true cer:true pem:true)` generate the push certificate for that app id, save it in the repo, and drop a copy of specific parts of the certificate in the current folder.  If it already exists, instead of generating, just pull it from the repo, then drop the copy like before.

**Comment by TKBurner** [comment]
@vbresults Those are great ideas. I think it's possible to store your certificate in your repo. However, you'll still need to use pem to access it.

**Comment by vbresults** [comment]
@TKBurner so match to store it, then `pem(match:true)` or something similar?

**Comment by TKBurner** [comment]
@vbresults Correct, provide the path to the push cert.

**Comment by StevePotter** [comment]
+1
