### ISSUE TITLE
Can`t install `deliver` tool on Ubuntu Linux (running inside Virtual Box using Windows as a Host)

### ISSUE THREAD

**Issue by fabiobh** [fastlane/fastlane#6660]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
This is the output when I try to install deliver tool on Ubuntu Linux(I run Ubuntu inside a Virtual Box machine using a Windows Host)

---

fabio@fabio-VirtualBox:~$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
fabio@fabio-VirtualBox:~$ sudo gem install deliver
Building native extensions.  This could take a while...
ERROR:  Error installing deliver:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext
/usr/bin/ruby2.3 -r ./siteconf20161021-3395-1gyd4bl.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.2/gem_make.out

```

### Configuration Files

I didn`t use any fastfile, just want to install the deliver tool

Fastfile:
```ruby
```

### Environment

fastlane version (run `fastlane -v`):
It`s not possible, I can`t install fastlane or deliver tool

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?
No

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?
I don`t use any Ruby environment manager

What Xcode version do you use (e.g. 7.3, 8.0)
I`m using Ubuntu Linux, don`t have Xcode on it

**Comment by fabiobh** [comment]
I discover the problem.

The ruby versions that I install was not the ruby-dev version. I just run the command
sudo apt-get install ruby-dev

After that, it works.

**Comment by TKBurner** [comment]
@fabiobh Awesome! So glad to hear you got up and running. Always feel free to reach out with any thoughts or questions.

**Comment by bkpawlowski** [comment]
@TKBurner 
I've encountered the same issue on Ubuntu 16.04. I had already ruby and ruby-dev(both in version 2.3.0) installed but I was still unable to compile one of this ruby plugins. Thing that helped was installing `build-essential` package. Perhaps appropriate `linux-headers` package is also required  - but i'm not sure, it was already there - as gem does stuff using gcc.

Best regards!

**Comment by TKBurner** [comment]
@bkpawlowski Glad to hear you got up and running! We're working on a bundled version of ruby with Fastlane that should have prevented this issue. Thanks!
