### ISSUE TITLE
Better Developper/ITC Teams display

### ISSUE THREAD

**Issue by Onejjy** [fastlane/fastlane#6661]
Here is my situation, as many freelancers, I'm a member of a lot of Apple Developer teams (and many Itunes Connect). I often have fastlane outputs like this:  

```
+-----------------------+-------------------------------------------------+
|                         Summary for match 0.8.1                         |
+-----------------------+-------------------------------------------------+
| type                  | development                                     |
                                      [...]
| team_id               | 4815162342                                      |
                                      [...]
+-----------------------+-------------------------------------------------+
```

I don't know the ids of all my teams, so it's not easy to know directly which one is concerned.

I think it would be a lot more user-friendly to display the name of the team beside the `team_id`. It would give something like this: 

```
+-----------------------+-------------------------------------------------+
|                         Summary for match 0.8.1                         |
+-----------------------+-------------------------------------------------+
| type                  | development                                     |
                                      [...]
| team_id               | 4815162342 (Oceanic Airlines)                   |
                                      [...]
+-----------------------+-------------------------------------------------+
```

The idea is to do this everywhere a `team_id` is displayed to the user. Does anyone see any drawback on this ? If it's OK for you, I'll make a PR with this.

**Comment by KrauseFx** [comment]
Ah, nice idea, so you're talking about the summary of each tool that is being shown when you launch it, right? The team selection itself is okay?

**Comment by Onejjy** [comment]
So, I'll do it. But I have a huge schedule on the next 8 days (I'm doing a tour in China). I'll submit my PR just after :)

About your question, are you talking of this menu ? 
```
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) 4815162342 "Oceanic Airlines" (Company/Organization)
2) KRO166486 "Dharma" (Company/Organization)
```

If yes, it seems perfect to me !

**Comment by KrauseFx** [comment]
Alright cool, enjoy your trip @Onejjy 👍 Let us know if you need any help with this

**Comment by Onejjy** [comment]
So, after digging into the code, it seems to be a bad idea :/. 

Indeed, each time we display summaries like above, it's just a dump of the passed parameters. If we want to be able to display the team name, we would have to make a web request for that. IMHO, it doesn't worth it/ 

Sorry for making you lose time.

**Comment by TKBurner** [comment]
@Onejjy No problem! Always great to work with you 👍

**Comment by KrauseFx** [comment]
Thanks for looking into this @Onejjy and letting us know :rocket;
