### ISSUE TITLE
Perf improvement: frameit takes 10 mins but only uses 15% CPU

### ISSUE THREAD

**Issue by xaphod** [fastlane/fastlane#6671]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Frameit is great.
But it takes a lllooooong time, and there's only 15% CPU usage going on. Could this be better parallelized?

**Comment by TKBurner** [comment]
@xaphod Great question! Right now this isn't possible but it's an interesting idea. I'll talk to the core team about it. Thanks!
