### ISSUE TITLE
Is there a way to deliver .app file for MacOS to iTunes Connect?

### ISSUE THREAD

**Issue by nickeyzzz** [fastlane/fastlane#6673]
### New Issue Checklist
- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

For me gym makes .app file for MacOS by default, no PKG file.
This issue is explained here https://github.com/fastlane/fastlane/issues/1234

As far, as I understand (am I mistaken?) there are two ways to upload app to iTunes
1. APP file itself, no installer
2. PKG file with app installer

As there are two kinds of certificate for Mac OS X:
1. Mac App Distribution
This certificate is used to code sign your app and configure a Distribution Provisioning Profile for submission to the Mac App Store.
2. Mac Installer Distribution
This certificate is used to sign your app's Installer Package for submission to the Mac App Store.

For me first way is preferable and APP file is enough.
Is "deliver" able to upload APP files instead of PKG files?

**Comment by yokoe** [comment]
You can not upload .app file itself to iTunes and unfortunately gym still doesn't support exporting .pkg file.

At least in Xcode 8, we can create .pkg file from xcarchive in the same way exporting ipa file from iOS project using xcodebuild with "--exportArchive" option.
So I think very small change may add support for exporting pkg file.
In fast, I could confirm .pkg file exported by just adding "package_app" in `runner.rb`.

```
module Gym
  class Runner
    # @return (String) The path to the resulting ipa
    def run
      ...
      if Gym.project.ios? || Gym.project.tvos?
        ...
      elsif Gym.project.mac?
        package_app
        compress_and_move_dsym
        copy_mac_app
        # need_some_additional_things_here
      end
    end
```

Hope somebody to create PR, or I may make it some time later.

**Comment by TKBurner** [comment]
@yokoe We'd love to see a PR from you. Let me know if you need any help getting started 👍

**Comment by yokoe** [comment]
I created a small PR #6774 . This PR just adds support for exporting pkg file to gym. 
Some additional PRs for deliver or fastlane will be required to support entire pkg upload process in fastlane though.

**Comment by TKBurner** [comment]
@yokoe Awesome! We'll work with you there. To set an expectation, we have had a backlog of PRs lately so it might take a little while, but we will definitely address it. I really appreciate you contributing 👍

**Comment by triplef** [comment]
In case it helps anyone, here’s what I came up with to enable uploads of Mac apps to iTunes Connect and also allow them to be exported using Developer ID. In both cases I’m using `xcexport` to package / sign the app, and I also had to fix a couple of paths as they were set incorrectly. Sorry I haven’t been able to track down and report the root causes of these issues.

```ruby
# set based on selected app/scheme
isMAS = true/false

# build app
gym

# gym does not export the archive for Mac, so we need to do so manually to code sign with Developer ID
export_method = isMAS ? 'app-store' : 'developer-id'
xcexport({export_options_plist: {method: export_method}})

# delete incorrect ipa path in lane context
Actions.lane_context[SharedValues::IPA_OUTPUT_PATH] = nil

# fix dSYM path
Actions.lane_context[SharedValues::DSYM_OUTPUT_PATH] = "#{ENV['GYM_OUTPUT_DIRECTORY']}/#{ENV['GYM_OUTPUT_NAME']}.app.dSYM.zip"

# remove .ipa extension from output path that xcexport incorrectly adds
export_dir = Actions.lane_context[SharedValues::IPA_OUTPUT_PATH].gsub(/\.ipa$/, '')

# find pkg/app inside export folder and upload / show in Finder
if isMAS
    ENV['DELIVER_PKG_PATH'] = Dir[File.join(export_dir, "*.pkg")].last
    
    deliver(force: true)
else
    app_path = Dir[File.join(export_dir, "*.app")].last
    
    sh "open -R #{app_path.shellescape}"
end
```

**Comment by TKBurner** [comment]
@triplef Thanks for sharing that, I'm sure it'll help others 👍

**Comment by yokoe** [comment]
Updated the PR #6774.
