### ISSUE TITLE
Could not find a .xcodeproj in the current repository's working directory.

### ISSUE THREAD

**Issue by WANGjieJacques** [fastlane/fastlane#6675]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When my iOS project path is something like `xxxPods/myProjectName`,  `commit_version_bump` could not find a .xcodeproj in the current repository's working directory.
##### Complete output when running fastlane, including the stack trace and command used

[18:35:01]: ▸ /Users/xxxx/Developer/xxxx/xxxxxPods/myProjectName
[18:35:01]: Variable Dump:
[18:35:01]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"12", :VERSION_NUMBER=>"1.0.10"}
[18:35:01]: Could not find a .xcodeproj in the current repository's working directory.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 1           |
| 4    | increment_version_number            | 1           |
| 5    | get_version_number                  | 0           |
| 💥    | commit_version_bump                 | 0           |
+------+-------------------------------------+-------------+

[18:35:01]: fastlane finished with errors

[!] Could not find a .xcodeproj in the current repository's working directory.

```
INSERT OUTPUT HERE
```
### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:

``` ruby
# INSERT CONTENT HERE
```
### Environment

fastlane version (run `fastlane -v`): fastlane 1.105.3

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)?

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)?

What Xcode version do you use (e.g. 7.3, 8.0): 8.0

**Comment by TKBurner** [comment]
@WANGjieJacques Can you share a screenshot of your directory structure for your project?

**Comment by WANGjieJacques** [comment]
Why you need that? I have already created a pull request for this issue.

**Comment by TKBurner** [comment]
@WANGjieJacques Thanks for letting me know. Can you link your PR here? Thanks!

**Comment by WANGjieJacques** [comment]
@TKBurner  https://github.com/WANGjieJacques/fastlane/commit/62b890b1a1e1672472874020fadcc201e3a607aa
here it is.
