### ISSUE TITLE
Sigh downloads latest profile. Gym doesn't use it. (Xcode8)

### ISSUE THREAD

**Issue by scottrhoyt** [fastlane/fastlane#6683]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Hi there. Prior to Xcode 8, the instructions in the code signing guide gave predictable results when using `sigh` to select the correct provisioning profile. However, after following the project setup instructions for Xcode 8 [here](https://docs.fastlane.tools/codesigning/xcode-project/#xcode-8-and-up), I have found the results to be unpredictable. `sigh` will always successfully downloads/creates/selects the desired profile, but `gym` doesn't appear to always use that profile. Sometimes, it uses an earlier version of the profile. Are there any additional steps to take with Xcode8 to get more reliable results? Thanks.
##### Complete output when running fastlane, including the stack trace and command used

_n/a_
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

```
Scotts-iMac:Test scottrhoyt$ fastlane env
[22:16:22]: -------------------------------------------------
[22:16:22]: --- Step: Verifying required fastlane version ---
[22:16:22]: -------------------------------------------------
[22:16:22]: Your fastlane version 1.105.3 matches the minimum requirement of 1.105.0  ✅
[22:16:22]: ------------------------------
[22:16:22]: --- Step: default_platform ---
[22:16:22]: ------------------------------
[22:16:22]: Variable Dump:
[22:16:22]: {:DEFAULT_PLATFORM=>:ios}
[22:16:22]: Could not find lane 'ios env'. Available lanes: ios test, ios beta, ios adhoc, ios release
```

**Comment by hjanuschka** [comment]
could you please - upgrade fastlane and fastlane_core to its latest version, and re-run the `fastlane env` - as this will help to troubleshoot the issue. many thx

**Comment by scottrhoyt** [comment]
Thanks for the assistance, @hjanuschka. Unfortunately, `fastlane env` doesn't seem to be working for me:

```
Scotts-iMac:Test scottrhoyt$ gem update fastlane_core
Updating installed gems
Nothing to update
Scotts-iMac:Test scottrhoyt$ gem update fastlane
Updating installed gems
Nothing to update
Scotts-iMac:Test scottrhoyt$ fastlane env
[10:09:08]: -------------------------------------------------
[10:09:08]: --- Step: Verifying required fastlane version ---
[10:09:08]: -------------------------------------------------
[10:09:08]: Your fastlane version 1.105.3 matches the minimum requirement of 1.105.0  ✅
[10:09:08]: ------------------------------
[10:09:08]: --- Step: default_platform ---
[10:09:08]: ------------------------------
[10:09:08]: Variable Dump:
[10:09:08]: {:DEFAULT_PLATFORM=>:ios}
[10:09:08]: Could not find lane 'ios env'. Available lanes: ios test, ios beta, ios adhoc, ios release
```

```
Scotts-iMac:Test scottrhoyt$ fastlane -v
fastlane 1.105.3
```

**Comment by KrauseFx** [comment]
The latest fastlane version is 1.106.1 (https://rubygems.org/gems/fastlane), seems like `gem update` didn't work. Could you try `sudo gem update fastlane`? How do you usually update fastlane? 

Have you followed the [Xcode 8 docs](https://docs.fastlane.tools/codesigning/xcode-project/#xcode-8-and-up) you linked? Can you share a screenshot of your Xcode project's build settings

**Comment by scottrhoyt** [comment]
I did follow the instructions on the Xcode 8 page, by disabling automatic management and selecting my profiles manually. Here's what the build settings look like (sorry I had to redact things for legal reasons):

<img width="1805" alt="screen shot 2016-10-24 at 4 42 53 pm" src="https://cloud.githubusercontent.com/assets/4259250/19668104/30e7b94c-9a0a-11e6-9def-76a00ca1ddf6.png">

Just did another `gem update fastlane` and it picked up 1.106.1 this time so `fastlane env` worked:

## `fastlane env` output

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.10.1                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12 (16A319)                     |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    #carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Test") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to Hockey"
  lane :adhoc do
    sigh(adhoc: true, force: true)
    cert
    gym(scheme: "Test")
    hockey(api_token: "************")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Test") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.scotthoyt.Test" # The bundle identifier of your app
apple_id "***********" # Your Apple email address

team_id ********  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.1  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| deliver             | 1.14.3  | ✅ Up-To-Date        |
| snapshot            | 1.16.2  | ✅ Up-To-Date        |
| frameit             | 2.8.0   | 🚫 Update availaible |
| pem                 | 1.3.2   | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| pilot               | 1.11.0  | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.8.1   | 🚫 Update availaible |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.106.1 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| xcodeproj                 | 1.3.3        |
</details>


*generated on:* **2016-10-24**
</details>

**Comment by scottrhoyt** [comment]
By the way, when this happens to me, my workaround is to just nuke my installed provisioning profiles on my machine. So, sigh is correctly downloading and installing the right profile. And gym uses it when it's the only option.

**Comment by TKBurner** [comment]
@scottrhoyt Thanks for reaching out about this. Are your provisioning profiles set manually in your build settings? Fastlane isn't compatible with automatic code signing introduced in Xcode 8.
