### ISSUE TITLE
match generates new profiles instead of repairing old ones

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#6684]
Hi,

I have the profiles all well set up and working. 
**match AdHoc com.myapp.alpha** is the name of the profile on the Apple developer profile generated by fastlane match.

For ease of use for my fellow developers, I have mentioned the name of the profile in XCode 8 project settings. (Also Xcode 8 don't have the automatic option for profiles.)

I use match with force_for_new_devices:true 

Then I disabled one existing device on apple developer website.
The profile (**match AdHoc com.myapp.alpha**) became invalid.

Now when I ran match again it created a new profile with name **match AdHoc com.myapp.alpha 1477229329** instead of repairing the old one. 
This is a problem as my XCode project settings still have the profile name mentioned as **match AdHoc com.myapp.alpha**. This will not pick up the latest profiles.

I have the CI set up which dynamically assigns the profile and generates the build. 

But in our day to day activities, developers do the debugging through Xcode.
I want an environment where developers don't need to touch any code signing settings in xcode and can easily debug on device. 

If match repairs the existing profiles without generating a new profile with a different name then everything will work absolutely wonderful for me.

**Comment by KrauseFx** [comment]
Hey @santoshshetty2612, thanks for the report. This should be fixed with https://github.com/fastlane/fastlane/pull/6703. Feel free to give the branch a try, or wait for the official release tomorrow morning 👍
