### ISSUE TITLE
deliver download_metadata requires the ipa file to exist if specified

### ISSUE THREAD

**Issue by remcohaszing** [fastlane/fastlane#6687]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

`deliver download_metadata` requires the ipa file to exist if it's specified in the Deliverfile. It shouldn't require this.
##### Complete output when running fastlane, including the stack trace and command used

```
$ deliver download_metadata
[13:06:48]: Error setting value 'SomeApp.ipa' for option 'ipa'

[!] Could not find ipa file at path 'SomeApp.ipa'
```

**Comment by TKBurner** [comment]
@remcohaszing Thanks for letting me know about this. Can you set your .ipa path in your Fastfile instead? That seems like the most viable workaround. I agree this isn't optimal though, are you interested in submitting a PR to get this working? Thanks!

**Comment by remcohaszing** [comment]
Commenting out the ipa path worked for that single occasion I've ever needed this so far. :wink: 

I've never written any Ruby except for Fastlane configuration files. So no, sorry, I won't be able to make a PR.

**Comment by TKBurner** [comment]
@remcohaszing Thanks for following up. We'll leave this open in case anyone is interested in contributing. 👍
