### ISSUE TITLE
Deliver failed to read accented characters ("\xC3" on US-ASCII)

### ISSUE THREAD

**Issue by akkhilns** [fastlane/fastlane#6688]
Deliver command failed to read accented characters from the description.txt file.
Please look these output.

/metadata/en-US/description.txt'...
INFO [2016-10-24 17:57:20.23]: Activating language en-US...
INFO [2016-10-24 17:57:24.92]: Uploading metadata to iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...
Search query: "\xC3" on US-ASCII

URL: https://api.github.com/search/issues?q=%22%5CxC3%22%20on%20US-ASCII+repo:fastlane/fastlane
?? [33mError with posting data with 0x00FA character[0m
https://github.com/fastlane/fastlane/issues/1967 [[32mclosed[0m] 27 ??
3 weeks ago

?? [33musing supply with ant[0m
https://github.com/fastlane/fastlane/issues/1968 [[32mclosed[0m] 2 ??
16 May 2016

/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/base.rb:52:in `encode': [31m[!] "\xC3" on US-ASCII[0m (Encoding::InvalidByteSequenceError)
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/base.rb:52:in`to_json'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/base.rb:52:in `to_json'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/tunes_client.rb:362:in`block (2 levels) in update_app_version!'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in`block in build_request'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in`tap'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in`build_request'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
from /usr/local/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in`post'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/client.rb:445:in `block in send_request'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/client.rb:347:in`with_retry'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/client.rb:444:in `send_request'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/client.rb:385:in`request'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/tunes_client.rb:360:in `block in update_app_version!'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/tunes_client.rb:952:in`with_tunes_retry'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/tunes_client.rb:359:in `update_app_version!'
from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.1/lib/spaceship/tunes/app_version.rb:285:in`save!'
from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/upload_metadata.rb:58:in `upload'
from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/runner.rb:58:in`upload_metadata'
from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/runner.rb:21:in `run'
from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/commands_generator.rb:47:in`block (2 levels) in run'
from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in`run'
from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in`run!'
from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/commands_generator.rb:128:in`run'
from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/lib/deliver/commands_generator.rb:12:in `start'
from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.3/bin/deliver:5:in`'
from /usr/local/bin/deliver:23:in `load'
from /usr/local/bin/deliver:23:in`'

**Comment by TKBurner** [comment]
@akkhilns Thanks for reaching out about this. Are you able to share your deliver file? That'll help a lot. Thanks!

**Comment by akkhilns** [comment]
`The diacritic letters ä, ö and ü are used to indicate the presence of umlauts (frontalizations of back vowels).`

This is the content in my description.txt file. Accented characters in the description file. Without this characters they are working fine.

**Comment by TKBurner** [comment]
Thanks! Can you provide a sample project effected by this issue so I can send this over to the core team? Thanks!

**Comment by akkhilns** [comment]
i converted that characters to HTML entities. Its worked

**Comment by akkhilns** [comment]
Im using deliver command in the shell script. Added these lines top of the shell script and its working.
export LANG=en_US.UTF-8;
export LANGUAGE=en_US:en;

**Comment by dral3x** [comment]
I've encountered the same problem with an app name. In my case, `produce` is failing.

All the app metadata are inside a `.env` file. This is the relevant content
```
CUSTOMAPP_LANGUAGE="Spanish"
CUSTOMAPP_CULTURE="es-ES"
CUSTOMAPP_NAME="Hinnení"
CUSTOMAPP_DESCRIPTION="Peregrino es una app donde puedes escuchar los podcast del Padre Carlos Alberto Cardona. \n\nPublicamos pensamientos, lecturas y sueños... y uno que otro documento de los Papas en formato de audiolibro. Cuenta con la opción de chat."
CUSTOMAPP_KEYWORDS="Podcast,Audiolibros,Religión,Católico,Iglesia"
CUSTOMAPP_CATEGORY="Education"
```

The `Deliverfile` content, regarding the title is this
```
name ({ ENV["CUSTOMAPP_CULTURE"] => ENV["CUSTOMAPP_NAME"] })
primary_category ENV["CUSTOMAPP_CATEGORY"]
```

and finally the lane from `Fastfile`
```
lane :deploy do

    if ENV["CUSTOMAPP_APPLE_ID"].to_s.empty?

      # It will create the app
      produce(
        username:                 ENV["DELIVER_USER"],
        app_identifier:           "xxx.xxxxxxxx.xxxxxx.*",
        bundle_identifier_suffix: ENV["CUSTOMAPP_BUNDLE_SUFFIX"],
        app_version:              ENV["CUSTOMAPP_VERSION"],
        app_name:                 ENV["CUSTOMAPP_NAME"],
        language:                 ENV["CUSTOMAPP_LANGUAGE"],
        sku:                      ENV["CUSTOMAPP_SKU"],
        skip_devcenter:           true
        )

      # ENV["PRODUCE_APPLE_ID"] is now available

    else

      ENV["PRODUCE_APPLE_ID"] = ENV["CUSTOMAPP_APPLE_ID"]

    end

    # Upload all metadata, screenshots and ipa file
    # force = skip preview report
    deliver(
      force: true,
      submit_for_review: true
    )
  end
```

Here it is the log from `report.xml`
```
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/actions/actions_helper.rb:33:in `execute_action'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:187:in `block in execute_action'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:186:in `chdir'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:186:in `execute_action'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/fast_file.rb:146:in `method_missing'&#10;Fastfile:24:in `block (2 levels) in parsing_binding'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/lane.rb:33:in `call'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:49:in `block in execute'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:45:in `chdir'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/runner.rb:45:in `execute'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/command_line_handler.rb:30:in `handle'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:95:in `block (2 levels) in run'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.58.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:292:in `run'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/commands_generator.rb:36:in `start'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'&#10;/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.111.0/bin/fastlane:5:in `&lt;top (required)&gt;'&#10;/usr/local/bin/fastlane:23:in `load'&#10;/usr/local/bin/fastlane:23:in `&lt;main&gt;'&#10;&#10;&quot;\xC3&quot; from ASCII-8BIT to UTF-8
```

I hope this can helps you @TKBurner 👍

**Comment by akkhilns** [comment]
LANG=en_US.UTF-8;
LANGUAGE=en_US:en; 

@dral3x  did you check this

**Comment by dral3x** [comment]
Sorry for the late response.
Adding LANG and LANGUAGE to the shell enviroment worked!

Thanks @akkhilns 👍
