### ISSUE TITLE
Different behavior of require and base path on fastlane and match

### ISSUE THREAD

**Issue by guidomb** [fastlane/fastlane#6696]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I've been trying to include external ruby files in Matchfile, Appfile and Fastfile and I found that `require` behaves differently depending if I am using `fastlane` o `match` from the command line.

I have a file called `read_credentials.rb` located inside the `fastlane` directory. In the `Matchfile` I have to require like `require './fastlane/read_credentials` but in the `Appfile` I have to require like `./read_credentials`.

Same happens if I want to read a file from the file system. Lets say I have a file called `some_config.yml` inside the `fastlane` directory. If I want to read in the `Matchfile` when using `bundle exec match` I need to read like `File.read('./fastlane/some_config.yml')` but if I executed `bundle exec fastlane` I need to read like `File.read('some_config.yml')`.

Is this the expected behavior? I would expect same behavior between `fastlane` and `match` command line apps.

**Comment by TKBurner** [comment]
@guidomb Thanks for reaching out. The behavior you are seeing is expected and not specific to your ruby setup. I've marked this as a feature request because I think finding a way to make these behave similarly would be nice, however it's important to note we can't break any existing set ups.
