### ISSUE TITLE
how to pass scheme from scan to xcov

### ISSUE THREAD

**Issue by huminzhi** [fastlane/fastlane#6697]
I basically want to run scan then xcov and let the user to pick a scheme during scan..
However, I don't want the usr to select scheme again in xcov,  it should just use the scheme I picked for scan before..

how to achieve this? Really appreciate!

**Comment by TKBurner** [comment]
@huminzhi Thanks for reaching out. Right now, scan doesn't set this for xcov, but we'd be interested in a PR to make this possible.
