### ISSUE TITLE
frameit version 3.0.0 missing iPhone7 offsets

### ISSUE THREAD

**Issue by flightlyverduyn** [fastlane/fastlane#6698]
frameit version 3.0.0 is missing iPhone7 from https://fastlane.github.io/frameit-frames/latest/offsets.json

```
$ frameit
[11:53:37]: Using device frames version 'latest'
[11:53:37]: Framing screenshot './ar/iPhone7-Welcome.png'
[11:53:37]: Tried looking for offset information for 'portrait', iPhone 7
[11:53:37]: Could not find offset_information for './ar/iPhone7-Welcome.png'
```

Doing

```
$ frameit download_frames
```

Did not help because it's missing from https://fastlane.github.io/frameit-frames/latest/offsets.json

I'm using version 3.0.0 
```
$ frameit --version
frameit 3.0.0
```

### Environment

```
$ fastlane env
### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12                                                          |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12 (16A323)                                        |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.1  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| deliver             | 1.14.3  | ✅ Up-To-Date        |
| snapshot            | 1.16.2  | ✅ Up-To-Date        |
| frameit             | 2.8.0   | 🚫 Update availaible |
| pem                 | 1.3.2   | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| pilot               | 1.11.0  | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.8.1   | ✅ Up-To-Date        |
| screengrab          | 0.5.4   | 🚫 Update availaible |
| fastlane            | 1.106.0 | ✅ Up-To-Date        |

```

I have two versions of frameit version 2.8.0 and version 3.0.0

I'm unable to uninstall frameit version 2.8.0 because 
fastlane-1.106.0 depends on frameit (< 3.0.0, >= 2.8.0)

**Comment by GandjaFuzz** [comment]
having this problem too

**Comment by GandjaFuzz** [comment]
```
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'frameit' (< 3.0.0, >= 2.8.0) - did find: [frameit-3.0.0] (Gem::LoadError)
Checked in 'GEM_PATH=/Users/Shared/Jenkins/.gem/ruby/2.3.0:/usr/local/lib/ruby/gems/2.3.0:/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/gems/2.3.0', execute `gem env` for more information
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1438:in `block in activate_dependencies'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `each'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/specification.rb:1409:in `activate'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by KrauseFx** [comment]
Oh wow, nice catch, I'll push an update in a minute 👍

**Comment by KrauseFx** [comment]
I just pushed the new version, could you run
```
frameit download_frames
```
and let me know if that works for you?

**Comment by KrauseFx** [comment]
@GandjaFuzz you have a different issue, could you submit a separate issue for this? Make sure to run `fastlane env` to share your Ruby environment.

**Comment by flightlyverduyn** [comment]
works thanks!

**Comment by GandjaFuzz** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.1  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| deliver             | 1.14.3  | ✅ Up-To-Date        |
| snapshot            | 1.16.2  | ✅ Up-To-Date        |
| frameit             | 2.8.0   | 🚫 Update availaible |
| pem                 | 1.3.2   | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| pilot               | 1.11.0  | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.8.1   | 🚫 Update availaible |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.106.0 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.5       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.18       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2016-10-24**
</details>

**Comment by KrauseFx** [comment]
Awesome, glad to hear 👍
