### ISSUE TITLE
Remove fastlane dependency on ruby

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#6699]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I know it sounds crazy but putting the hassle of managing non-system rubies on users of the tool is ridiculous. Package a ruby binary with fastlane itself or rebuild it on top of a macOS tool or technology not as poorly supported as ruby.
##### Complete output when running fastlane, including the stack trace and command used

```
[13:20:36]: fastlane finished with errors
[13:20:36]: -----------------------------------------------------------------------
[13:20:36]: Connection reset by peer - SSL_connect
[13:20:36]: 
[13:20:36]: SSL errors can be caused by various components on your local machine.
[13:20:36]: Apple has recently changed their servers to require TLS 1.2, which may
[13:20:36]: not be available to your system installed Ruby (2.0.0)
[13:20:36]: 
[13:20:36]: The best solution is to install a new version of Ruby
[13:20:36]: 
[13:20:36]: - Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
[13:20:36]: - If you use system Ruby:
[13:20:36]:   - Run `brew update && brew install ruby`
[13:20:36]: - If you use rbenv with ruby-build:
[13:20:36]:   - Run `brew update && brew upgrade ruby-build && rbenv install ruby-2.3.1`
[13:20:36]:   - Run `rbenv global ruby-2.3.1` to make it the new global default Ruby version
[13:20:36]: - If you use rvm:
[13:20:36]:   - First run `rvm osx-ssl-certs update all`
[13:20:36]:   - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local
[13:20:36]: 
[13:20:36]: If that doesn't fix your issue, please google for the following error message:
[13:20:36]:   'Connection reset by peer - SSL_connect'
[13:20:36]: -----------------------------------------------------------------------
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

[INSERT OUTPUT HERE]

**Comment by Aaron81** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12                                                          |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12 (16A323)                                        |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| deliver             | 1.14.4  | ✅ Up-To-Date  |
| snapshot            | 1.16.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.9.0   | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.1 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
</details>


*generated on:* **2016-10-25**
</details>

**Comment by Aaron81** [comment]
brew uninstall ruby # not using homebrew's ruby

rm -rf ~/.gem
rm -rf ~/.gems
rm -rf ~/.rbenv
brew install rbenv ruby-built

Add rbenv to bash so that it loads every time you open a terminal

echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile
source ~/.bash_profile

Install Ruby

rbenv install 2.3.1
rbenv global 2.3.1

close teminal and re-open it

ruby -v # should output 2.3.1 now
sudo chown -R $(whoami): ~/.rbenv # important!!!
gem update --system
gem install fastlane # this will install a lot of gems, since we are not using the old 2.0.0 gems anymore.

**Comment by KrauseFx** [comment]
Hey @postmechanical, thanks for the suggestion, I completely agree with you to the dependency to Ruby is a tough one, especially since Apple bundles a really old version of Ruby in macOS.

We actually worked on some bundled Ruby support with the Fabric app for now (you can download the Fabric Mac app to give it a try). 

While we don't actively work on it right now, we're definitely interested in providing a fastlane zip file on our website, that people can just drag & drop to their Application folder, ready to be used, including the latest Ruby and OpenSSL dependency.

Let me know what you think 👍

**Comment by postmechanical** [comment]
@KrauseFx Thank you for considering it. As a user I don't care how the tools are implemented unless I have to deal with managing any dependencies that make the tools work at which point I do care because I have to care about ruby, which I don't, in order to just be able to use the tools. Looking at the history of support for third-party scripting languages on macOS, though, I would seriously caution against sticking with ruby or switching to python or anything other than swift. Apple clearly doesn't care about any other dev tools and technologies than its own and that's only going to become more of a critical problem in the future.

**Comment by TKBurner** [comment]
@postmechanical Thanks for the suggestion. We are definitely looking into packaging a ruby version with fastlane. Let me know if there are any first steps we can take now to make things better for you. 👍

**Comment by zilinskas** [comment]
If you are using system ruby and seeing the version 2 but have 2.3 installed with ruby -v then try...

gem update --system

**Comment by GoodMirek** [comment]
With system ruby on MacOSX fastlane does not work. It is because Apple developer portal forces usage of a newer TLS ciphers and system ruby uses pretty old openssl.

What has helped is installation of a newer ruby with a newer openSSL.
```
xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install openssl
brew install rbenv
brew install ruby-build
rbenv init
RUBY_CONFIGURE_OPTS="--with-lib-dir=$(brew --prefix openssl)/lib --with-include-dir=$(brew --prefix openssl)/include" rbenv install 2.3.1
rbenv global 2.3.1
```
Adding following lines to $HOME/.bash_profile, this way the system ruby is masked:
```
export PATH="$HOME/.rbenv/bin:/usr/local/opt/openssl/bin:$PATH"
eval "$(rbenv init -)"
```
Verify which version of openssl is used by ruby:
```
ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.2j  26 Sep 2016
```
# Reboot the machine #

Then, install fastlane:
```
gem update
gem install fastlane
```

**Comment by postmechanical** [comment]
@GoodMirek Thanks for the suggestion but you miss the point of the issue. As a user of fastlane, I am not interested in maintaining a ruby installation in order to use fastlane.

**Comment by GoodMirek** [comment]
@postmechanical Hi, I believe I understand the point. I agree my comment is off-topic. Though this is one of the best tickets related to the issue I have found, so maybe my suggestion can help someone. It took me a couple of hours to figure out how to make fastlane working, I am complete Ruby and Macosx newbie.

**Comment by postmechanical** [comment]
@GoodMirek And therein lies the problem.

**Comment by TKBurner** [comment]
@postmechanical @GoodMirek We are looking into the possibility of having fastlane manage it's own ruby so these issues won't occur. We'll update once we have something more concrete. Thanks!

**Comment by ohwutup** [comment]
Hey everyone, we've been working on a new way to install and use fastlane, all you have to do is to download `fastlane.zip` and double click the `install` file. This will install fastlane with all its Ruby and OpenSSL dependencies, and should all work out of the box.
We just finished building this, and would love your early feedback on this beta. Please let us know how it works for you and if you run into any problems :+1: 
Download the latest version [here](http://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/bundle-1.107.0.zip).

**Comment by postmechanical** [comment]
@ohwutup Thanks! Long term you're going to want to distribute this via a signed installer package. Also, the install script borked the `~/.bash_profile` update for me by writing literally `\nexport PATH="$HOME/.fastlane/bin:$PATH"\n` into my profile, resulting in:

```
source ~/.bash_profile
-bash: nexport: command not found
```

**Comment by ohwutup** [comment]
Hey @postmechanical we updated the build, would you mind giving it another shot?

**Comment by postmechanical** [comment]
@ohwutup Same link? http://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/bundle-1.107.0.zip

**Comment by ohwutup** [comment]
yup!

**Comment by postmechanical** [comment]
@ohwutup The `install` script needs to `cd` to its parent directory, otherwise the `cp -R "fastlane_lib/" $FASTLANE_DIR` command at line 63 fails silently.

**Comment by ohwutup** [comment]
Thanks for going through the trial and error @postmechanical ! We just cleaned that up again and it should be working properly. Mind giving it another shot?

**Comment by postmechanical** [comment]
@ohwutup Working well now.

**Comment by ohwutup** [comment]
Amazing! Thanks @postmechanical !! :rocket:

**Comment by milch** [comment]
Thanks for helping us test @postmechanical!

**Comment by KrauseFx** [comment]
Thanks everyone, we'll close this issue for now, as this is implemented 👍
