### ISSUE TITLE
tvOS with extension Linker Error

### ISSUE THREAD

**Issue by nikitaame** [fastlane/fastlane#6706]
### New Issue Checklist
- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When trying to make a build of a tvOS application with a TopShelf extension, I keep running into linking error.
##### Complete output when running fastlane, including the stack trace and command used

```
❌  ld: library not found for -lPods-Prod - [APP_NAME] - TopShelf
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **

The following build commands failed:
Ld fastlane/deriveddata/[APP_NAME]-PROD-ad-hoc-1.4.0.9-DEVELOP/Build/Intermediates/ArchiveIntermediates/Prod\ -\ [APP_NAME]/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Prod\ -\ [APP_NAME]\ -\ TopShelf.appex/Prod\ -\ [APP_NAME]\ -\ TopShelf normal arm64
(1 failure)
[16:05:55]: Exit status: 65
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>

🚫 fastlane environment 🚫</summary>

### Stack

| Key | Value |
| --- | --- |
| OS | 10.11.6 |
| Ruby | 2.3.1 |
| Bundler? | false |
| Xcode Path | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version | 8.0 |
| Git | git version 2.10.1 |
| Installation Source | /Users/ameln002/.rvm/gems/ruby-2.3.1/bin/fastlane |
| Host | Mac OS X 10.11.6 (15G31) |
| Ruby Lib Dir | /Users/ameln002/.rvm/rubies/ruby-2.3.1/lib |
| OpenSSL Version | OpenSSL 1.0.2j  26 Sep 2016 |
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| spaceship | 0.36.1 | ✅ Up-To-Date |
| deliver | 1.14.3 | ✅ Up-To-Date |
| snapshot | 1.16.2 | ✅ Up-To-Date |
| frameit | 2.8.0 | 🚫 Update availaible |
| pem | 1.3.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| pilot | 1.11.0 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| match | 0.8.1 | 🚫 Update availaible |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| fastlane | 1.106.1 | ✅ Up-To-Date |

**Comment by TKBurner** [comment]
Hi @nikitaame Can you share your full input and output? I want to take a look at what command runs before your error. Thanks so much!

**Comment by nikitaame** [comment]
Hey @TKBurner thanks for the response. I'm working on putting together a sample project to post on here but in the meantime here is some more info on the error:

[12:52:23]: ▸ Linking Prod\
[12:52:23]: ▸ ❌  ld: library not found for -lPods-Prod - [APP_NAME] - TopShelf
[12:52:23]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[12:52:23]: ▸ ** ARCHIVE FAILED **
[12:52:23]: ▸ The following build commands failed:
[12:52:23]: ▸ Ld fastlane/deriveddata/[APP_NAME]-PROD-ad-hoc-1.4.0.9-DEVELOP/Build/Intermediates/ArchiveIntermediates/Prod\ -\ [APP_NAME]/IntermediateBuildFilesPath/UninstalledProducts/appletvos/Prod\ -\ [APP_NAME]\ -\ TopShelf.appex/Prod\ -\ [APP_NAME]\ -\ TopShelf normal arm64
[12:52:23]: ▸ (1 failure)
2016-10-26 12:52:08.001 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde63bd010>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:08.005 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde63bd010>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:08.053 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]",
"group.[COMPANY_NAME].tvos"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde5f24120>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:08.055 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]",
"group.[COMPANY_NAME].tvos"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde5f24120>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
▸ Cleaning aka/Prod - [APP_NAME] - TopShelf [Debug]
▸ Check Dependencies
▸ Cleaning aka/Prod - [APP_NAME] [Debug]
▸ Check Dependencies
2016-10-26 12:52:09.001 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]",
"group.[COMPANY_NAME].tvos"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde5f24120>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:09.001 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]",
"group.[COMPANY_NAME].tvos"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde5f24120>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:09.009 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde63bd010>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:09.010 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde63bd010>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
▸ Clean Succeeded
2016-10-26 12:52:09.138 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde63bd010>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:09.139 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde63bd010>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:09.150 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]",
"group.[COMPANY_NAME].tvos"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde5f24120>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2016-10-26 12:52:09.151 xcodebuild[90150:16249177] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-11204/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/ProjectModel/Capabilities/Xcode3TargetCapabilitiesContext.m:292
Details:  Failed to expand identifiers "{(
"group.[COMPANY_NAME].tvos.[APP_NAME]",
"group.[COMPANY_NAME].tvos"
)}": Error Domain=IDECapabilitiesErrorDomain Code=1 "The operation requires a selected developer portal team." UserInfo={NSLocalizedDescription=The operation requires a selected developer portal team., NSLocalizedRecoverySuggestion=}
Object:   <Xcode3TargetCapabilitiesContext: 0x7fbde5f24120>
Method:   -_appIDFeatureStateIncludingEntitlements:
Thread:   <NSThread: 0x7fbde0d14df0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

**Comment by nikitaame** [comment]
Here's my Fastfile. A very similar one works 100% for the iOS version of the app. The tvOS app seems to not be building with the TopShelf extension being included.

```
# Customise this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

# This is the minimum version number required.
# Update this, if you use features of a newer version
require 'yaml'
require 'ostruct'

fastlane_version "1.85.0"

default_platform :ios

platform :ios do

  desc "Run Tests"
  lane :test do
  # snapshot
  end

  desc "Increments the build number via Build Setting's CURRENT_PROJECT_VERSION"
  lane :increment_build_number do
    increment_build_number
  end

  desc "Install Certificates"
  lane :install_certs do
    import_certificate(
      certificate_path: "fastlane/certificates/[GROUP_NAME]_tvOS_Distribution.p12",
      certificate_password: "[PASSWORD]",
      keychain_name: "login.keychain"
    )

    import_certificate(
      certificate_path: "fastlane/certificates/[COMPANY_NAME]_tvOS_Distribution_2015.p12",
      certificate_password: "[PASSWORD]",
      keychain_name: "login.keychain"
    )
  end

  desc "Retrieve all profiles associated with the PROD and QA builds and installs the profiles for RELEASE"
  lane :retrieve_profiles do |options|
    config = YAML.load(open(File.join(File.dirname(__FILE__), "config.yaml")))
    settings = OpenStruct.new(config)


    profiles_settings = settings['PROFILES']
    profiles_info = profiles_settings['profiles_info']
    ENV['FASTLANE_PASSWORD'] = profiles_settings['password']

    profiles_info.each do |profile_info|
      if profile_info['is_from_local'] == false
        sigh(
          username: profiles_settings['username'],
          team_id: profiles_settings['team_id'],
          app_identifier: profile_info['app_identifier'],
          output_path: "tmp",
          adhoc: true,
          skip_certificate_verification: true,
          provisioning_name: profile_info['provisioning_name'],
          ignore_profiles_with_different_name: true
        )
      end

      if profile_info['is_from_local'] == true
        provisioning_name = profile_info['provisioning_name'] + '.mobileprovision'
        sh "./scripts/copy.sh ../Provisioning/#{provisioning_name}"
      end
    end

    system "rm -r ../tmp/"

  end

  desc "Builds with envs DEVELOP, QA, STAGING, MASTER and HOTFIX."
  desc "Every execution of this lane builds PROD, QA, RELEASE ipas"
  desc "The ipas can be found in ./fastlane/builds."
  desc "Examples: \n
      fastlane make_build env:DEVELOP \n
      fastlane make_build env:QA \n
      fastlane make_build env:STAGING \n
      fastlane make_build env:MASTER \n
      fastlane make_build env:HOTFIX"

  lane :make_build do |options|

    config = YAML.load(open(File.join(File.dirname(__FILE__), "config.yaml")))
    settings = OpenStruct.new(config)

    environment = options[:env]

    version = get_version_number
    build = get_build_number
    version_name = "#{version}.#{build}-#{environment}"

    all_versions = settings['VERSIONS']

    all_versions.each do |version|
      version_settings = settings[version['version']]
      targets = version_settings['targets']

      targets.each do |target_settings|
        ipa_name = target_settings['output_prefix'] + "-" + version_settings['export_method'] + "-" + version_name
        gym(
          scheme: target_settings['target_identifier'],
          project: settings['project'],
          clean: true,
          output_directory: "./fastlane/builds",
          output_name: ipa_name + ".ipa",
          export_method: version_settings['export_method'],
          build_path: "./fastlane/archives/",
          archive_path: "./fastlane/archives/" + ipa_name,
          derived_data_path: "./fastlane/deriveddata/" + ipa_name,
          codesigning_identity: version_settings['codesigning_identity']
        )
      end
    end

  end

end

after_all do |lane|
  version = get_version_number
  build = get_build_number

  sh "echo \"APP_VERSION=#{version} \nAPP_BUILD=#{version}.#{build}\" > version.properties"
end


error do |lane, exception|
  sh "echo \"#{lane} Failed please check logs!\""
end

```

**Comment by nikitaame** [comment]
After doing some research, I'm feeling like this might be an issue with fastlane and extensions. I know cocoapods wasn't working with extensions until 1.1.0. Could their more recent fix to the issue not have been accounted for in fastlane?

**Comment by TKBurner** [comment]
@nikitaame Thanks for following up. I want to send this out to the core team, but I want to make sure they can take action if possible. Can you create the most simple possible sample project that this is impacted by and share the complete project with us? That way we can dive right in. 

To be specific, is this TVos specific extensions that are affected?

**Comment by nikitaame** [comment]
I've figured out what the problem was.

When running pod install,  -lPods-Prod - [APP_NAME] - TopShelf.a was being generated in the Frameworks folder of the project workspace. When deleted the fastlane build would work once again, until pod install would be run.

**Comment by TKBurner** [comment]
@nikitaame Awesome! Glad to hear you found a workaround.

**Comment by nikitaame** [comment]
If anyone else ever has this problem:

```project: settings['project']```

needs to be 

```workspace: settings['workspace']```

in the fastfile.

**Comment by KrauseFx** [comment]
Cool, thanks for sharing the solution, I'll close the issue for now 👍
