### ISSUE TITLE
Spaceship::TunesClient::ITunesConnectError: invalid request body

### ISSUE THREAD

**Issue by summera** [fastlane/fastlane#6711]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Receiving `Spaceship::TunesClient::ITunesConnectError: invalid request body` when calling `Spaceship::Tunes.select_team`. The request to set the team id on [line 88](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb#L88) is returning HTTP 400. Here is the response body:

```ruby
{
  "data"=>nil,
  "messages"=>{"warn"=>nil, "error"=>["invalid request body"], "info"=>nil}, 
  "statusCode"=>"ERROR"
}
```

I did some digging with switching teams in ITC and it looks like Spaceship needs the `dsId` param in the `ra/v1/session/webSession`. Once I added this param to the request, I received a 200 and everything worked as expected. 

```ruby
response = request(:post) do |req|
  req.url "ra/v1/session/webSession"
  req.body = { contentProviderId: team_id, dsId: 'mydsid' }.to_json
  req.headers['Content-Type'] = 'application/json'
end
```

Note: by the time i got this posted there was a duplicate: #6710 . sorry about that

**Comment by ldiqual** [comment]
@summera I'm sure the fastlane team will react promptly, but in the meantime is there a workaround besides patching the gem?

**Comment by summera** [comment]
I'm not quite sure what the dsId is yet because I can't even load ITC right now haha. Maybe its the user's ID? So I'm not sure if Spaceship provides a way to obtain this ID already. As far as I can tell this needs to be in the request for it to work now. So immediate fix would be patching.

**Comment by chakming** [comment]
@summera ITC seems updated, have a new login page layout now

**Comment by summera** [comment]
@chakming yea ITC was telling me it was down for a few and now login page looks a little different. I think everything else seems to be the same and error still exists though.

dsId is different for each user. If you go to your Personal Details for your account it's the id at the end of that URL... https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/users_roles/#{dsid}

**Comment by chakming** [comment]
@summera found one interesting thing: if I use another `dsId` which is not refer to my user account, it still works

**Comment by summera** [comment]
Ha. You're right. Just putting a random ID does work. This worked for me:

```ruby
      response = request(:post) do |req|
        req.url "ra/v1/session/webSession"
        req.body = { contentProviderId: team_id, dsId: '123' }.to_json
        req.headers['Content-Type'] = 'application/json'
      end
```

**Comment by ChrisVolentine** [comment]
@summera I added a random dsId to my request body like you have, and it started working again for me as well

**Comment by summera** [comment]
I found that the actual dsId can be obtained from the user detail request in [TunesClient#user_detail_data](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tunes_client.rb#L537) inside the `sessionToken` json object. It's just not parsed from the response in the current implementation.

**Comment by luskin** [comment]
where is this file located?

**Comment by luskin** [comment]
^ worked for me as well!

**Comment by KrauseFx** [comment]
Hey everyone, thanks for the reports, I can reproduce the issue, I'm working on a fix 🚀

**Comment by summera** [comment]
@KrauseFx just came up with this:

https://github.com/summera/fastlane/commit/7f8adc36d990abe6039bfcccf0fd967d2fdec965

I can open PR if you'd like.

**Comment by KrauseFx** [comment]
Awesome, thank you @summera, I pushed this via https://github.com/fastlane/fastlane/pull/6716. Preparing a new release in a minute

**Comment by KrauseFx** [comment]
Hey, thanks for your patience everyone, we were able to push new releases for _spaceship_, _pilot_ and _deliver_, please update to the latest release using `[sudo] gem update deliver` or `[sudo] gem update pilot`. If you're using `bundler` use `bundle update` instead 👍 

Special thanks to @summera for providing a super fast fix, and @milch for reviewing all the required version bumps and dependency updates :rocket: 

Please let us know if that solves the issue for you.

**Comment by santoshshetty2612** [comment]
updated to latest version of deliver and fastlane. Invalid request body error is resolved now.
But getting the following error:

ruby-2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:63:in `block in generate_metadata_files': [!] undefined method `<<' for nil:NilClass (NoMethodError)
	from .rvm/gems/ruby-2.3.0/gems/deliver-1.14.4/lib/deliver/setup.rb:57:in `each'

**Comment by KrauseFx** [comment]
@santoshshetty2612 That's a separate issue, I'll provide a fix in a minute 👍

**Comment by nitindhar7** [comment]
@KrauseFx thanks for the fast fixes! works perfectly for me :)
