### ISSUE TITLE
Expose `device_grid` as a standalone gem

### ISSUE THREAD

**Issue by ldiqual** [fastlane/fastlane#6714]
Right now `danger-device_grid` depends on the danger's plugin system to function. I'd like to be able to use `device_grid` outside of the Danger library so that I can publish my app to Appetize with different triggers.

A couple examples:
- CircleCI doesn't trigger a build when creating a private pull request, so builds only trigger when pushing commits and there might not be any pull request open for our bot to comment on, which is why Danger won't work. In this case, we can work around it by pushing an empty commit with a specific `[appetize]` tag that will trigger the CircleCI build and push to Appetize without Danger.
- Taking the `swift-ci` approach, we can comment `@company-ci Please appetize` which triggers a Zapier zap, which will communicate with the CircleCI REST API to trigger a build. In this case, just like the previous one, there's no Danger involved.

We took the latter approach and it works pretty well. However we had to copy the whole `plugin.rb` code and adapt it outside of Danger.

It seems that the device grid could easily be extracted to a standalone gem `appetize-device-grid` which `danger-device_grid` would depend on, and that we could use outside of Danger as well.

**Comment by TKBurner** [comment]
@ldiqual Thanks for your suggestion. I've marked it as a feature request so we can see if others are interested. Were you interested in implementing this yourself?
