### ISSUE TITLE
Rubygems error: `check_version_conflict': can't activate json-2.0.2, already activated json-1.8.3

### ISSUE THREAD

**Issue by choiks14** [fastlane/fastlane#6725]
i did "**fastlane run update_fastlane**"

but i got error.

<pre>
/Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2274:in `check_version_conflict': can't activate json-2.0.2, already activated json-1.8.3 (Gem::LoadError)
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1403:in `activate'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core.rb:1:in `<top (required)>'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.1/lib/fastlane.rb:1:in `<top (required)>'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.1/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
        from /Users/choiks14/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.1/bin/fastlane:5:in `<top (required)>'
        from /Users/choiks14/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
        from /Users/choiks14/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
</pre>

so i removed json 2.0.2
`
$ gem uninstall json -v 2.0.2
`

it works.

please update json library

and my ruby is 
`
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
`

**Comment by PetrosIchor** [comment]
It states right in the error you have 2 versions of json conflicting.  That needs resolved to continue.

**Comment by TKBurner** [comment]
Hi @choiks14 what happens if you run gem update and try again? Can you send the full output?

**Comment by GoodMirek** [comment]
The same issue happened to me after running `sudo gem update`
Removal of json 2.0.2 helped.
After that, I have tried to update the gems again:
`sudo gem update`
and it worked this time.
```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ gem list | sort | grep json
json (2.0.2, default: 1.8.3)
multi_json (1.12.1)
```
No idea what made the difference.

**Comment by milch** [comment]
Sometimes this just happens. The simplest possible fix is to run `gem cleanup` after upgrading fastlane.

I'm closing this as it is actually an issue with Rubygems: https://github.com/rubygems/rubygems/issues/1309

**Comment by choiks14** [comment]
thank you!!
