### ISSUE TITLE
fastlane supply timed publishing

### ISSUE THREAD

**Issue by mychaelgo** [fastlane/fastlane#6727]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Can "fastlane supply" upload APK with manual release?

**Comment by TKBurner** [comment]
@mychaelgo Thanks for reaching out. Are you running into a specific error? You should be able to do this. Thanks!

**Comment by hjanuschka** [comment]
on CI we run `fastlane android_publish_beta`  - in order to have the latest apk in beta train.

```
lane :android_publish_beta do
  supply(json_key: 'fastlane/google_play_key.json',
         track: options[:track])
end
lane :android_promote_beta do
  supply(
    json_key: 'fastlane/google_play_key.json',
    track: 'beta',
    track_promote_to: 'production',
    skip_upload_apk: true,
    skip_upload_metadata: true,
    skip_upload_images: true,
    skip_upload_screenshots: true
  )
end
```

and once we decide to release - we do `fastlane android_promote_beta`  to move the latest beta to production train.

**Comment by mychaelgo** [comment]
@TKBurner  @hjanuschka Thanks for reaching out, but "fastlane supply" manual release i mean is google play timed publishing, is fastlane support it?

**Comment by asfalcone** [comment]
@mychaelgo Take a look at the [Google API](https://github.com/google/google-api-ruby-client/tree/master/generated/google/apis/androidpublisher_v2) we use. If this API has support for timed publishing, then it is something that could be added to _supply_
