### ISSUE TITLE
How to use fastlane Screenshots for product flavours in android?

### ISSUE THREAD

**Issue by Muthukathiravan** [fastlane/fastlane#6728]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
[INSERT OUTPUT HERE]
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

[INSERT OUTPUT HERE]

**Comment by Muthukathiravan** [comment]
@asfalcone I have three product flavors ,wanna run at single comment and store the all flavors screen shot in as per the flavor name in directory..

**Comment by asfalcone** [comment]
@Muthukathiravan this isn't currently supported by _screengrab_ itself. you could use _fastlane_ to build each debug and test variant per flavor, then run _screengrab_, specifying a different output folder. Hope this helps 👍

**Comment by TKBurner** [comment]
@Muthukathiravan Thanks for reaching out. You'll need to run screengrab three times in the same lane. Let me know if you have any questions.
