### ISSUE TITLE
pilot script：The call to the iTMSTransporter completed with a non-zero exit status

### ISSUE THREAD

**Issue by lieliefengzheng** [fastlane/fastlane#6729]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I entered :
pilot upload -u xxx@xxx -a xxx -i ${ipapath} -s -z   
 
in the terminal, and then the output below 
```
[INSERT OUTPUT HERE]
```
[18:38:18]: Going to upload updated app to iTunes Connect
[18:38:18]: This might take a few minutes. Please don't interrupt the script.
[18:40:24]: [Transporter Error Output]: Could not start delivery: all transports failed diagnostics
[18:40:24]: Transporter transfer failed.
[18:40:24]: 
[18:40:24]: Could not start delivery: all transports failed diagnostics
[18:40:25]: Could not start delivery: all transports failed diagnostics
Return status of iTunes Transporter was 1: Could not start delivery: all transports failed diagnostics
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

[!] Error uploading ipa file, for more information see above

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| deliver             | 1.14.4  | ✅ Up-To-Date  |
| snapshot            | 1.16.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.9.0   | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.1 | ✅ Up-To-Date  |

**Comment by lieliefengzheng** [comment]
the problem is solved.
pilot upload -u xxx@xxx -a xxx -i ${ipapath} -s --skip_submission true

**Comment by TKBurner** [comment]
@lieliefengzheng Are you still running into this issue? It looks like a temporary issue with the endpoint on Apple's side. I'd love to look into this if you are seeing it consistently still. Thanks!
