### ISSUE TITLE
scan: report generation takes a rather long time

### ISSUE THREAD

**Issue by AndyIsaacson** [fastlane/fastlane#6736]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

When I run `scan`, the final step to generate test reports take a very long time to complete.  My project is complicated to compile, but (unfortunately) there are not a ton of tests.  To give an example, compilation takes ~20m on CircleCI, the 174 tests run in 13s, and then generating a junit report takes another 8m.  I turned off HTML report generation, as it was taking even longer to run.

Is there anything I can do to speed this up?  Can I (should I?) turn it off entirely?  My builds are slow enough as it is - I'd love to shave off those extra minutes.  TBH, I'm not even sure if I've set it up properly for Circle to see the results.
##### Complete output when running fastlane, including the stack trace and command used

Just the end of the scan command, happy to provide more context if it would be useful:

[08:35:31](▸): ▸      Executed 174 tests, with 0 failures (0 unexpected) in 13.240 (13.369) seconds

[08:35:35]: ▸ Test Succeeded
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 174   |
| Number of failures | 0     |
+--------------------+-------+

[08:43:05]: Successfully generated report at '/Users/distiller/project-ios/fastlane/test_output/report.junit'
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
Redacted the Fastfile - literally just running `scan` 

<details><summary>

✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| --- | --- |
| OS | 10.11.6 |
| Ruby | 2.2.5 |
| Bundler? | true |
| Xcode Path | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version | 8.0 |
| Git | git version 2.8.4 (Apple Git-73) |
| Installation Source | /Users/andyi/.rvm/gems/ruby-2.2.5/bin/fastlane |
| Host | Mac OS X 10.11.6 (15G1004) |
| Ruby Lib Dir | /Users/andyi/.rvm/rubies/ruby-2.2.5/lib |
| OpenSSL Version | OpenSSL 1.0.2e 3 Dec 2015 |
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| spaceship | 0.36.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| deliver | 1.14.4 | ✅ Up-To-Date |
| frameit | 3.0.0 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| match | 0.9.0 | ✅ Up-To-Date |
| pem | 1.3.2 | ✅ Up-To-Date |
| pilot | 1.11.1 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| snapshot | 1.16.2 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| fastlane | 1.106.1 | ✅ Up-To-Date |
### Loaded fastlane plugins:

| Plugin | Version | Update-Status |
| --- | --- | --- |
| fastlane-plugin-versioning | 0.2.4 | ✅ Up-To-Date |

<details><summary>

<b>Loaded gems</b></summary>

| Gem | Version |
| --- | --- |
| ZenTest | 4.11.1 |
| RubyInline | 3.12.4 |
| i18n | 0.7.0 |
| json | 1.8.3 |
| minitest | 5.9.1 |
| thread_safe | 0.3.5 |
| tzinfo | 1.2.2 |
| activesupport | 4.2.7.1 |
| addressable | 2.4.0 |
| babosa | 1.0.2 |
| bundler | 1.12.5 |
| colored | 1.2 |
| highline | 1.7.8 |
| commander | 4.4.0 |
| security | 0.1.3 |
| credentials_manager | 0.16.2 |
| excon | 0.54.0 |
| gh_inspector | 1.0.2 |
| multi_json | 1.12.1 |
| plist | 3.1.0 |
| rubyzip | 1.1.7 |
| terminal-table | 1.4.5 |
| fastlane_core | 0.53.0 |
| multipart-post | 2.0.0 |
| faraday | 0.9.2 |
| unf_ext | 0.0.7.2 |
| unf | 0.1.4 |
| domain_name | 0.5.20160826 |
| http-cookie | 1.0.3 |
| faraday-cookie_jar | 0.0.6 |
| faraday_middleware | 0.10.0 |
| fastimage | 1.6.8 |
| multi_xml | 0.5.5 |
| claide | 1.0.1 |
| fuzzy_match | 2.0.4 |
| nap | 1.1.0 |
| cocoapods-core | 1.1.1 |
| cocoapods-deintegrate | 1.0.1 |
| cocoapods-downloader | 1.1.2 |
| cocoapods-plugins | 1.0.0 |
| cocoapods-search | 1.0.0 |
| cocoapods-stats | 1.0.0 |
| netrc | 0.7.8 |
| cocoapods-trunk | 1.1.1 |
| cocoapods-try | 1.1.0 |
| escape | 0.0.4 |
| fourflusher | 2.0.1 |
| molinillo | 0.5.1 |
| xcodeproj | 1.3.3 |
| cocoapods | 1.1.1 |
| dotenv | 2.1.1 |
| osx_keychain | 1.0.1 |
| cocoapods-keys | 1.7.0 |
| mini_magick | 4.5.1 |
| rouge | 1.11.1 |
| xcpretty | 0.2.4 |
| net-ssh | 3.2.0 |
| net-sftp | 2.1.2 |
| krausefx-shenzhen | 0.14.10 |
| slack-notifier | 1.5.1 |
| xcpretty-travis-formatter | 0.0.4 |
| jwt | 1.5.6 |
| little-plugger | 1.1.4 |
| logging | 2.1.0 |
| memoist | 0.15.0 |
| os | 0.9.6 |
| signet | 0.7.3 |
| googleauth | 0.5.1 |
| httpclient | 2.8.2.4 |
| hurley | 0.2 |
| mime-types-data | 3.2016.0521 |
| mime-types | 3.1 |
| uber | 0.0.15 |
| representable | 2.3.0 |
| retriable | 2.1.0 |
| google-api-client | 0.9.19 |
| terminal-notifier | 1.7.1 |
| word_wrap | 1.0.0 |
| xcode-install | 2.0.7 |
| fastlane-plugin-versioning | 0.2.4 |

</details>

_generated on:_ **2016-10-25**
</details>

**Comment by TKBurner** [comment]
@AndyIsaacson  Thanks for reaching out. Can you add the --verbose flag to your run of this to see if we get any more details on why the report is taking a long time to generate? Have you tried working with the --output_style option? Thanks!

**Comment by AndyIsaacson** [comment]
Hi @TKBurner !  Unfortunately, nothing extra comes when I add --verbose (assuming I'm doing it right `bundle exec fastlane scan --verbose`).  I haven't tried the `output_style` option, but TBH, I've been trying to figure out where the docs for these options are, and short of scouring source, haven't found a good reference.  Is there a spot where those options are documented?

**Comment by TKBurner** [comment]
@AndyIsaacson Thanks for  following up. There isn't a good resource for the documentation except by running `scan help`. Can you try erasing your simulators? I just want to make sure we optimize your experience. Thanks!

**Comment by arrrnas** [comment]
same issue: 
```
[12:33:02]: ▸ Test Succeeded
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 1112  |
| Number of failures | 0     |
+--------------------+-------+

[12:33:47]: Successfully generated report at '.../fastlane/test_output/report.html'
[12:34:10]: Successfully generated report at '.../fastlane/test_output/report.junit'

#######################################################################
# scan 0.14.1 is available. You are on 0.13.1.
# It is recommended to use the latest version.
# Update using 'bundle update scan'.
#######################################################################

0.14.1 Hot Fix
* Fix crash when running scan on macOS projects (#6864)

0.14.0 Single scheme Xcode projects, better failure handling & more
* Properly handle report generation failures (#6788)
* Handle single scheme Xcode projects (#6637)
* Fix importing the Scanfile twice when Scanfile is in project's directory (#6598)
* Show Xcode path in summary table (#6470)
* Update internal dependencies

Update using 'sudo gem update scan'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | export LC_ALL=en_US.UTF-8           | 0           |
| 4    | scan                                | 284         |
+------+-------------------------------------+-------------+

[12:34:11]: fastlane.tools finished successfully 🎉
```
Would be cool to reduce the time from `[12:33:02]: ▸ Test Succeeded`  to `[12:34:11]: fastlane.tools finished successfully 🎉` since that's about 25% of the test running time.  this is with
```
       scheme: "...", 
       device: "iPhone 7",
       clean: true,
       skip_build: true,
       slack_only_on_failure: true,
       slack_channel: "...",
```
and running with `bundle exec` if that changes anything.

**Comment by TKBurner** [comment]
Thanks for following up! If anyone from the community is interested in looking into this, we'd be interested in a PR. Thanks!

**Comment by keatongreve** [comment]
This issue is affecting us too. Noting a lack of console output around the freeze time, I dug into this locally.

The root of the issue is that `scan` doesn't generate the report with the piped input, but instead waits until `xcodebuild` has finished. It reads the entire log file back in through a separate `cat $file | xcpretty` process to generate the report. Here's the most relevant source: [scan/lib/scan/report_collector.rb#L48-L52](https://github.com/fastlane/fastlane/blob/e721b30/scan/lib/scan/report_collector.rb#L48-L52)

Ultimately, it might be a limitation of `xcpretty` if it isn't optimized to skip through all the build output to parse the test output for report generation, and we're trying to use it on a finished build log.

One workaround might involve putting the report generation options on the first (terminal output) `xcpretty` command, which is https://github.com/fastlane/fastlane/blob/aa34de7/scan/lib/scan/test_command_generator.rb#L91. The biggest downside here is we can't generate multiple reports in this way, unless we make some changes to the `xcpretty` executable. I've experimented with this locally and it seems to be promising but I have yet to test the impact on the `json-compilation-database` report type. Also, no clue if the xcpretty devs would accept this change, though [their code](https://github.com/supermarin/xcpretty/blob/4b90228/bin/xcpretty#L85) suggests that they would want to support it.

**Comment by keatongreve** [comment]
Update: my bad! just realized, they already do support that, i just didn't understand how OptionParser worked in that case. https://github.com/supermarin/xcpretty/issues/135 still, i think we can make improvements using this info.

**Comment by AndyIsaacson** [comment]
Nice @keatongreve !  I wanted to add a data point, as I've been digging into my builds a bit more.  The size of the raw output of xcodebuild for my project is ~250 MB.  Didn't expect that, but certainly adds some color to why things move slowly while processing.

**Comment by RishabhTayal** [comment]
Can someone please reopen this issue? I am still facing it.

**Comment by keatongreve** [comment]
Hey @RishabhTayal, https://github.com/fastlane/fastlane/pull/7365 is still open and being reviewed. I think it will be merged soon but I'm sure the fastlane team is busy. In the meantime, feel free to switch to my fork and let me know if it helps. That feedback would help.

**Comment by RishabhTayal** [comment]
Thanks. Hoping to get it merged soon.

**Comment by palusik86** [comment]
@keatongreve I probably will need to use it because scan report takes about 20 min in my project, after we split code base to another 5 submodules. So now I'm facing this issue. Thanks for your input here.
