### ISSUE TITLE
Automatic signing issue

### ISSUE THREAD

**Issue by markffrench** [fastlane/fastlane#6738]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm unable to use gym to compile in XCode 8 and macOS Sierra. I am running gym during a jenkins build, on an xcodeproj created by Unity3D. Because the xcodeproj gets created at compilation I don't have the ability to go in and fix my signing options.

When I try gym I get

> Signing for "XXX" requires a development team. Select a development team in the project editor.
> Code signing is required for product type 'Application' in SDK 'iOS 10.0'

I am using Match to sync my certificates and profiles. I've been trying every different method I could find for a couple of days now, but I just can't figure out how to override the default "Automatic signing" behaviour thats been added.

I can get the project to compile if I go in and either set it to automatic and pick a team, or set it to manual and select the match profiles. However if I select a team when on automatic it appears to try to make new profiles instead of using the match ones.

This broke for us around 13th Oct

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| deliver             | 1.14.4  | ✅ Up-To-Date  |
| snapshot            | 1.16.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.9.0   | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-10-25**
</details>

**Comment by markffrench** [comment]
I have, but that advice only works if you are able to manually open the xcodeproj and switch signing to manual, as far as I can tell.

**Comment by PetrosIchor** [comment]
Fastlane provides their recommended way to handle app signing. If you plan to use another methodology, you will need to do research and implement what works for you.  My uses require manual signing as well. Through a couple plugins and self created actions, it's easy to setup.

**Comment by markffrench** [comment]
Could you point me in the direction of what you're using?

**Comment by markffrench** [comment]
Also, I don't think I'm using fastlane in a way that is that unusual, I've been able to compile newly created xcode projects using gym for well over a year, and it's only Apple's changes to XCode 8 that are breaking my CI setup.

**Comment by markffrench** [comment]
Also, I don't think I'm using fastlane in a way that is that unusual, I've been able to compile newly created xcode projects using gym for well over a year, and it's only Apple's changes to XCode 8 that are breaking my CI setup.

**Comment by PetrosIchor** [comment]
First thing is to read the release notes and documentation. Specifically around the new signing process.  Xcode8 brings a heavy handed automatic signing to the client. They've also depreciated some values like PROVISIONING_PROFILE.

You'll need to find a way to update your setup to accommodate your apps needs. For me, it was disabling automatic signing, injecting the new expected values, and updating the the appID in both the plist files and xcodeproj files.

Checkout the available actions as well as the plugins list. Some of them work for xcode8 others do not.  They might not even work for your application's setup.  If they don't, crack open the actions/plugins that are close to what you need and modify them to work how you want. 

If there's still some areas you need to address, create a new action and write out the operations yourself.  Plus it has the bonus of maybe becoming a plugin/action if you wanted. Help the project out :) (you're not the only setup xcode8 wrecked)

Xcode will be your friend and enemy.  Make small changes, check xcode to see if it moves you closer. No reason to run gym every time you want to try something. Pay attention to any and all errors, they are there to point you in the direction of what is missing or wrong. 

Alternatively, modify your iOS application's setup at the xcodeproj/xcworkspace level as the signing guide suggests.  Long run that might be the better solution for some.  

The fastlane toolset can't cover every possible software design.  Use the tools where you can, modify where possible, and build your own when necessary.  I began using fastlane about 6 months ago.  Each week another piece is removed or modified in favor of strengthening the specific projects I have using it. 

Happy hunting!

**Comment by markffrench** [comment]
Thanks for your detailed response :) It's sod's law, but this issue cropped up just as we're trying to ship!
