### ISSUE TITLE
Feature: Retrieve Developer Program information

### ISSUE THREAD

**Issue by stevekohls** [fastlane/fastlane#6739]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I manage multiple iOS Developer Program accounts, and I would like to be able to retrieve the information for each program. Specifically, I am interested in the Expiration Date. From looking at the documentation and code, this functionality is not currently available in any fastlane tools, including Spaceship. Is this information able to be retrieved using any of the available methods to communicate with the developer portal? If so, can this be included in a future version of the tools?

Here is a screenshot of the fields visible on the developer portal.

![screen shot 2016-10-25 at 1 57 02 pm](https://cloud.githubusercontent.com/assets/1894005/19697938/641c5f64-9abb-11e6-8c2d-876c61223a7d.png)

**Comment by stevekohls** [comment]
I just discovered I can retrieve this information using Spaceship:

```ruby
 Spaceship::Portal.client.teams
```

It would be a nice feature to retrieve this information via one of the tools. Perhaps `produce`?

**Comment by KrauseFx** [comment]
Hey @stevekohls, great idea, however this seems to not be something the majority of _fastlane_ users would use, therefore it shouldn't be part of any of the tools. The best solution is to build a [fastlane plugin](https://docs.fastlane.tools/plugins/create-plugin/) for this and provide it for everybody to use 👍 

Let me know what you think.

**Comment by stevekohls** [comment]
Thanks @KrauseFx. I'll look into creating a plugin. Right now I'm writing some Ruby scripts to automate our deployment processes. We manage Developer Program accounts for *many, many* customers, and it's useful for us to ping them when their developer program is about to expire.

**Comment by TKBurner** [comment]
@stevekohls Awesome! Yeah, we'd love to see something like this in our plugin ecosystem. Hope that you have a great weekend coming up 👍
