### ISSUE TITLE
Is it possible to disable xcpretty in scan?

### ISSUE THREAD

**Issue by benjaminsnorris** [fastlane/fastlane#6742]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

I am having a problem with my iOS project that code coverage data from UI tests is not reported. I have tried using Slather and directly with Codecov, as well as just looking locally, and no data is reported for UI tests. There is [an issue](https://github.com/nakiostudio/xcov/issues/22#issuecomment-232014641) reported in xcov, as well as [an issue](https://github.com/codecov/example-swift/issues/14#issuecomment-249427948) reported in Codecov that discuss this further. I'm wanting to keep using Fastlane, and want to try disabling `xcpretty` to see if I can get proper results. I can disable it fine with `gym`, but cannot figure it out with `scan`. Thanks!

**Comment by TKBurner** [comment]
Hi @benjaminsnorris right now that's not possible in scan but it'd be an interesting PR. Would you be interested in contributing to our repo? We'd love that 👍

**Comment by aamctustwo** [comment]
@benjaminsnorris Could you use the `output_style` option with `raw`? Looking at the code, this should eliminate the use of `xcpretty`.

https://github.com/fastlane/fastlane/blob/0e54a6ddd734e4dc04546f3d0cffff59d48700ca/scan/lib/scan/test_command_generator.rb#L62-L92

**Comment by benjaminsnorris** [comment]
Sorry, I should have come back to this. I did some manual tests and found that the underlying issue of UI test code coverage is not solved by disabling `scan`, so this fell completely off my radar.

**Comment by ohayon** [comment]
Thanks for following up! Going to close this issue as it seems to have been a red herring resolved. Feel free to continue conversation if necessary! 🐙
