### ISSUE TITLE
iTunesConnect app submission error

### ISSUE THREAD

**Issue by wimbledon** [fastlane/fastlane#6743]
### Issue Description
The issue start occuring on Tuesday, Oct. 25th, 2016 when I tried to submit new app update via iTunesConnect, I get following error message:
"New apps and app updates must be built with the public (GM) versions of Xcode 6 or later, macOS, and iOS SDK. Don't submit apps built with beta software including beta macOS builds."
![image](https://cloud.githubusercontent.com/assets/3291853/19701973/af5718ce-9acb-11e6-9d11-93ba1268ed15.png)

### Environment
| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.11.6                                           |
| Ruby                | 2.3.0                                             |
| Bundler?            | false                                             |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/       |
| Xcode Version       | 8.0                                               |
| Git                 | git version 2.8.4 (Apple Git-73)                  |
| Installation Source | /Users/davidliu/.rvm/gems/ruby-2.3.0/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                        |
| Ruby Lib Dir        | /Users/davidliu/.rvm/rubies/ruby-2.3.0/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                       |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| deliver             | 1.14.4  | ✅ Up-To-Date  |
| snapshot            | 1.16.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |

**Comment by nordfogel** [comment]
I guess it is related to the security update 2016-002 which you might have downloaded. It is still marked as beta as long as the itunes connect team does not whitelist 10.11.6 plus security patch 2016-002.

sources: 
https://forums.developer.apple.com/thread/64697#185895
https://forums.developer.apple.com/thread/50064

**Comment by wimbledon** [comment]
The problem is now resolved by Apple!

**Comment by TKBurner** [comment]
@wimbledon Awesome! Glad to hear you got up and running 👍
