### ISSUE TITLE
Deliver - Issues submitting to iTunesConnect via ruby script

### ISSUE THREAD

**Issue by swl367** [fastlane/fastlane#6747]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
(from a ruby script): deliver --ipa \"myapp.ipa\" --force -u #{account_name}

/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/implementations/shell.rb:119:in `verify_interactive!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/implementations/shell.rb:92:in `input'
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/detect_values.rb:20:in `find_app_identifier'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/detect_values.rb:4:in `run!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/runner.rb:8:in `initialize'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:47:in `new'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:47:in `block (2 levels) in run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:128:in `run'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/commands_generator.rb:12:in `start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/bin/deliver:5:in `<top (required)>'
    from /usr/local/bin/deliver:23:in `load'
    from /usr/local/bin/deliver:23:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

Generating fastlane environment output, this might take a few seconds...
<details><summary>

✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| --- | --- |
| OS | 10.11.6 |
| Ruby | 2.3.1 |
| Bundler? | false |
| Xcode Path | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version | 8.0 |
| Git | git version 2.8.4 (Apple Git-73) |
| Installation Source | /usr/local/bin/fastlane |
| Host | Mac OS X 10.11.6 (15G1004) |
| Ruby Lib Dir | /usr/local/Cellar/ruby/2.3.1_2/lib |
| OpenSSL Version | OpenSSL 1.0.2j  26 Sep 2016 |
### fastlane files:

**No Fastfile found**

**No Appfile found**
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| spaceship | 0.36.2 | ✅ Up-To-Date |
| deliver | 1.14.5 | ✅ Up-To-Date |
| snapshot | 1.16.2 | ✅ Up-To-Date |
| frameit | 3.0.0 | ✅ Up-To-Date |
| pem | 1.3.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| pilot | 1.11.1 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| match | 0.10.0 | ✅ Up-To-Date |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| fastlane | 1.106.2 | ✅ Up-To-Date |
### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary>

<b>Loaded gems</b></summary>

| Gem | Version |
| --- | --- |
| did_you_mean | 1.0.0 |
| highline | 1.7.8 |
| commander | 4.4.0 |
| terminal-table | 1.4.5 |
| json | 1.8.3 |
| multipart-post | 2.0.0 |
| faraday | 0.9.2 |
| faraday_middleware | 0.10.0 |
| dotenv | 2.1.1 |
| net-ssh | 3.2.0 |
| net-sftp | 2.1.2 |
| plist | 3.1.0 |
| rubyzip | 1.1.7 |
| security | 0.1.3 |
| krausefx-shenzhen | 0.14.10 |
| slack-notifier | 1.5.1 |
| i18n | 0.7.0 |
| thread_safe | 0.3.5 |
| tzinfo | 1.2.2 |
| minitest | 5.8.3 |
| activesupport | 4.2.7.1 |
| colored | 1.2 |
| claide | 1.0.1 |
| xcodeproj | 1.3.2 |
| rouge | 1.11.1 |
| xcpretty | 0.2.4 |
| terminal-notifier | 1.7.1 |
| addressable | 2.3.8 |
| xcode-install | 2.0.7 |
| word_wrap | 1.0.0 |
| multi_json | 1.12.1 |
| babosa | 1.0.2 |
| excon | 0.54.0 |
| gh_inspector | 1.0.2 |
| credentials_manager | 0.16.2 |
| fastlane_core | 0.53.0 |
| bundler | 1.13.5 |
| multi_xml | 0.5.5 |
| unf_ext | 0.0.7.2 |
| unf | 0.1.4 |
| domain_name | 0.5.20160826 |
| http-cookie | 1.0.3 |
| faraday-cookie_jar | 0.0.6 |
| fastimage | 1.6.8 |
| mini_magick | 4.5.1 |
| xcpretty-travis-formatter | 0.0.4 |
| uber | 0.0.15 |
| representable | 2.3.0 |
| retriable | 2.1.0 |
| mime-types-data | 3.2016.0521 |
| mime-types | 3.1 |
| hurley | 0.2 |
| little-plugger | 1.1.4 |
| logging | 2.1.0 |
| jwt | 1.5.6 |
| memoist | 0.15.0 |
| os | 0.9.6 |
| signet | 0.7.3 |
| googleauth | 0.5.1 |
| httpclient | 2.8.2.4 |
| google-api-client | 0.9.18 |
| io-console | 0.4.5 |

</details>

_generated on:_ **2016-10-25**
</details>

**Comment by klundberg** [comment]
I've had the same issue today, here's my stacktrace:
```
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/interface.rb:132:in `crash!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/implementations/shell.rb:119:in `verify_interactive!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/implementations/shell.rb:97:in `confirm'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/html_generator.rb:22:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/runner.rb:95:in `validate_html'
  /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/runner.rb:55:in `upload_metadata'
  /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.14.5/lib/deliver/runner.rb:21:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/actions/deliver.rb:18:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:187:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `chdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/fast_file.rb:140:in `method_missing'
  Fastfile:280:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:165:in `try_switch_to_lane'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:120:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/fast_file.rb:140:in `method_missing'
  Fastfile:266:in `block (3 levels) in parsing_binding'
  Fastfile:261:in `each'
  Fastfile:261:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/command_line_handler.rb:30:in `handle'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:52:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:246:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:23:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/bin/fastlane:5:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

**Comment by asfalcone** [comment]
@klundberg I think the behavior you're seeing is different, and is expected. If you're running _deliver_ on CI you'll need to pass `force` so that you aren't prompted to confirm that the screenshots look good.

**Comment by asfalcone** [comment]
@swl367 Passing `ipa` to _deliver_ should be enough for it to gather the `app_identifier`

Can you confirm that the ipa you're passing to _deliver_ has `CFBundleIdentifier` in the plist?

**Comment by swl367** [comment]
@asfalcone yes. I've been using deliver for a while now on over 200 apps. It's been working up until now! All of the projects I'm working on have the `CFBundleIdentifier` property.

**Comment by TKBurner** [comment]
@swl367 Did updating with` force: true` resolve your issue?

**Comment by swl367** [comment]
@TKBurner is this separate from setting --force in my deliver prompt? Where should I set force: true for my fastfile?

**Comment by TKBurner** [comment]
@swl367 I meant in your deliver file. You can try setting it on the deliver action in your fastfile but that shouldn't make a difference. Can you try running that command not in a script and share the full output, I want to see what is prompting you for user input. Thanks!
