### ISSUE TITLE
Mac Apps category will not update in store 

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#6748]
I have noticed that when uploading to the Mac App store, these two values do not work:

primary_category "Travel"
secondary_category "Reference"

It stays empty on store.

Anyone knows why?

**Comment by asfalcone** [comment]
@prolog3001 Hey thanks for the report. If you set the values on itunes connect and then do a `deliver init` Can you see the values that are set for the category and secondary category?

**Comment by prolog3001** [comment]
That was a great idea!
Thank you.

**Comment by asfalcone** [comment]
@prolog3001 Could you share the values? We might be able to update the code to include them correctly 👍
