### ISSUE TITLE
Feature: Deliver upload App store 30 sec. video clip

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#6749]
Will there be any solution to upload the 30 sec. clip vis fastlane?...

**Comment by TKBurner** [comment]
@prolog3001 Great idea! Right now it's not supported but I'm marking this as a feature request so we can see if anyone else is interested. Thanks!

**Comment by prolog3001** [comment]
Thanks.
Because nowadays we make video clips that present the app functionality, and it is a real burden to open Safari... upload... save... wait... it ruins the great automatization process that fastlane has given us!

**Comment by JustinJiaDev** [comment]
If I understand if correctly, spaceship already supports uploading app trailer. Only deliver needs to be updated?

**Comment by prolog3001** [comment]
Correct. We dont use spaceship, so adding it to deliver would be awesome!
