### ISSUE TITLE
Errors after installing Xcode 8.1 GM while already have Xcode 7.3.1 installed?

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#6750]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
snapshot
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': Could not determine installed iOS SDK version. Try running the _xcodebuild_ command manually to ensure it works. (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/lib/snapshot/latest_os_version.rb:23:in `version_for_os'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/lib/snapshot/latest_os_version.rb:10:in `version'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/lib/snapshot/latest_os_version.rb:5:in `ios_version'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/lib/snapshot/dependency_checker.rb:20:in `check_xcode_select'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/lib/snapshot/dependency_checker.rb:6:in `check_dependencies'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/lib/snapshot.rb:50:in `<module:Snapshot>'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/lib/snapshot.rb:21:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/snapshot-1.16.2/bin/snapshot:4:in `<top (required)>'
	from /usr/local/bin/snapshot:23:in `load'
	from /usr/local/bin/snapshot:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

fastlane env
-bash: fastlane: command not found

**Comment by NikhilRyan** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.1                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.1 (16B2555)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Library/Developer/CommandLineTools/                           |
| Xcode Version       |                                                                |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.restwla.1c6073a0" 
apple_id "apple_id@zomato.com"
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.38.4  | 🚫 Update availaible |
| fastlane_core       | 0.57.2  | 🚫 Update availaible |
| deliver             | 1.15.1  | 🚫 Update availaible |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | 🚫 Update availaible |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.2   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | 🚫 Update availaible |
| screengrab          | 0.5.2   | 🚫 Update availaible |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| dotenv                    | 2.0.2   |
| net-ssh                   | 3.0.1   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.1.0   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.11 |
| slack-notifier            | 1.3.1   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| minitest                  | 5.8.1   |
| activesupport             | 4.2.6   |
| colored                   | 1.2     |
| claide                    | 0.9.1   |
| xcodeproj                 | 0.28.2  |
| rouge                     | 1.10.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.6.3   |
| addressable               | 2.4.0   |
| multipart-post            | 2.0.0   |
| credentials_manager       | 0.16.2  |
| multi_xml                 | 0.5.5   |
| unf_ext                   | 0.0.7.1 |
| unf                       | 0.1.4   |
| domain_name               | 0.5.25  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| babosa                    | 1.0.2   |
| xcode-install             | 2.0.2   |
| word_wrap                 | 1.0.0   |
| multi_json                | 1.11.2  |
| excon                     | 0.45.4  |
| gh_inspector              | 1.0.2   |
| fastlane_core             | 0.57.2  |
| bundler                   | 1.12.5  |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.3   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| logging                   | 2.0.0   |
| jwt                       | 1.5.1   |
| memoist                   | 0.12.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.2   |
| googleauth                | 0.5.1   |
| thor                      | 0.19.1  |
| httpclient                | 2.7.1   |
| google-api-client         | 0.9.2   |
</details>


*generated on:* **2016-12-06**
</details>
