### ISSUE TITLE
undefined method `[]=' for nil:NilClass for sigh manage

### ISSUE THREAD

**Issue by ff-ahumberston** [fastlane/fastlane#6751]
### New Issue Checklist
- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Error received when attempting to run sigh manage 
##### Complete output when running fastlane, including the stack trace and command used

```
$sigh manage
INFO [2016-10-26 09:55:52.19]: Loading Provisioning profiles from ~/Library/MobileDevice/Provisioning Profiles/

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `[]=' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60[]='%20for%20nil+repo:fastlane/fastlane
➡️  undefined method `[]=' for nil:NilClass for sigh manage
   https://github.com/fastlane/fastlane/issues/6751 [open] 0 💬
   8 minutes ago

➡️  undefined method `<<' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/6731 [closed] 5 💬
   11 hours ago

➡️  Pilot tool is crashing with undefined method 'strip' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/3238 [open] 0 💬
   6 weeks ago

and 182 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]='%20for%20nil&type=Issues&utf8=✓
/Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/local_manage.rb:130:in `block in load_profiles': [!] undefined method `[]=' for nil:NilClass (NoMethodError)
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/local_manage.rb:128:in `each'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/local_manage.rb:128:in `load_profiles'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/local_manage.rb:45:in `list_profiles'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/local_manage.rb:9:in `start'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/commands_generator.rb:114:in `block (2 levels) in run'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/commands_generator.rb:120:in `run'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/commands_generator.rb:11:in `start'
        from /Users/ffadmin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/bin/sigh:6:in `<top (required)>'
        from /Users/ffadmin/.rbenv/versions/2.3.1/bin/sigh:22:in `load'
        from /Users/ffadmin/.rbenv/versions/2.3.1/bin/sigh:22:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
### Stack

| Key | Value |
| --- | --- |
| OS | 10.12.1 |
| Ruby | 2.3.1 |
| Bundler? | false |
| Xcode Path | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version | 8.0 |
| Git | git version 2.8.4 (Apple Git-73) |
| Installation Source | /Users/ffadmin/.rbenv/versions/2.3.1/bin/fastlane |
| Host | Mac OS X 10.12.1 (16B2555) |
| Ruby Lib Dir | /Users/ffadmin/.rbenv/versions/2.3.1/lib |
| OpenSSL Version | OpenSSL 1.0.2j  26 Sep 2016 |
### fastlane files:

**No Fastfile found**

**No Appfile found**
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| spaceship | 0.36.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| deliver | 1.14.5 | ✅ Up-To-Date |
| snapshot | 1.16.2 | ✅ Up-To-Date |
| frameit | 3.0.0 | ✅ Up-To-Date |
| pem | 1.3.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| pilot | 1.11.1 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| match | 0.10.0 | ✅ Up-To-Date |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| fastlane | 1.106.2 | ✅ Up-To-Date |
### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary>

<b>Loaded gems</b></summary>

| Gem | Version |
| --- | --- |
| did_you_mean | 1.0.0 |
| highline | 1.7.8 |
| commander | 4.4.0 |
| terminal-table | 1.4.5 |
| json | 1.8.3 |
| multipart-post | 2.0.0 |
| faraday | 0.9.2 |
| faraday_middleware | 0.10.0 |
| dotenv | 2.1.1 |
| net-ssh | 3.2.0 |
| net-sftp | 2.1.2 |
| plist | 3.1.0 |
| rubyzip | 1.1.7 |
| security | 0.1.3 |
| krausefx-shenzhen | 0.14.10 |
| slack-notifier | 1.5.1 |
| i18n | 0.7.0 |
| thread_safe | 0.3.5 |
| tzinfo | 1.2.2 |
| minitest | 5.8.3 |
| activesupport | 4.2.7.1 |
| colored | 1.2 |
| claide | 1.0.1 |
| xcodeproj | 1.3.3 |
| rouge | 1.11.1 |
| xcpretty | 0.2.4 |
| terminal-notifier | 1.7.1 |
| addressable | 2.3.8 |
| credentials_manager | 0.16.2 |
| multi_xml | 0.5.5 |
| unf_ext | 0.0.7.2 |
| unf | 0.1.4 |
| domain_name | 0.5.20160826 |
| http-cookie | 1.0.3 |
| faraday-cookie_jar | 0.0.6 |
| fastimage | 1.6.8 |
| xcode-install | 2.0.8 |
| word_wrap | 1.0.0 |
| multi_json | 1.12.1 |
| babosa | 1.0.2 |
| excon | 0.54.0 |
| gh_inspector | 1.0.2 |
| fastlane_core | 0.53.0 |
| bundler | 1.13.6 |
| mini_magick | 4.5.1 |
| xcpretty-travis-formatter | 0.0.4 |
| uber | 0.0.15 |
| representable | 2.3.0 |
| retriable | 2.1.0 |
| mime-types-data | 3.2016.0521 |
| mime-types | 3.1 |
| hurley | 0.2 |
| little-plugger | 1.1.4 |
| logging | 2.1.0 |
| jwt | 1.5.6 |
| memoist | 0.15.0 |
| os | 0.9.6 |
| signet | 0.7.3 |
| googleauth | 0.5.1 |
| httpclient | 2.8.2.4 |
| google-api-client | 0.9.19 |
| io-console | 0.4.5 |

**Comment by asfalcone** [comment]
@ff-ahumberston Thanks for the report. I wasn't able to immediately reproduce this error.

Could you do `ls ~/Library/MobileDevice/Provisioning\ Profiles/` and let me know the output?

The _sigh_ code that is failing is here: https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/local_manage.rb#L130 I'm wondering if you've got a profile that isn't parsable by `security` for some reason.

**Comment by ff-ahumberston** [comment]
output of command
`ls ~/Library/MobileDevice/Provisioning\ Profiles/
10192b18-3e06-4e40-9986-6a25dea618ae.provisionprofile   7ff853ab-e679-4aac-9040-52adcf687473.mobileprovision    c2dded3c-2152-4ed0-94d7-01a3715010fe.provisionprofile
25370d02-b7f8-4601-9c24-512772d60db7.provisionprofile   a96fea62-0d62-4596-b8bd-2a175550df4f.provisionprofile   cc55d165-5bb9-43c9-8edb-ccd04873c5fe.provisionprofile
285b60cc-edf9-4cbe-af7e-3aa6e873be04.provisionprofile   b4e2987a-3bbe-4a44-8bb7-f15669e69662.mobileprovision    d4327c20-59a6-4d1c-ace5-f7453ad28800.provisionprofile
44fc9cab-5197-4e8c-83be-b253e204b6cf.provisionprofile   bfb764d6-b4d6-497f-be18-c680088db8f2.provisionprofile   e00d587c-f034-4650-a4f1-57b1d197c291.mobileprovision
4a8e318e-b9b0-4472-8dba-aa957d0f0fb7.mobileprovision    c001afd9-3cd2-4d33-838e-5887f4c2f6d6.mobileprovision    e8cdc92f-438c-4e7e-a24b-af52c3d639be.mobileprovision
`
All of the file are owned by the logged in user

**Comment by TKBurner** [comment]
@ff-ahumberston Thanks! We are going to look into this 👍

**Comment by PlayDevelop** [comment]
I have the same issue, and this begun after Sierra installation is the problem only exists when is over ssh .  Locally on client it works

**Comment by ff-ahumberston** [comment]
I can confirm that the issue occurs when running over ssh with Sierra, running locally works as desired.

**Comment by mpirri** [comment]
@PlayDevelop & @ff-ahumberston can you clarify what you mean by "running over ssh"?  Do you mean, when connected to your CI machine over ssh, or something different?  Have you tried moving all of the provisioning profiles out of `~/Library/MobileDevice/Provisioning\ Profiles/`, running `sign` to re-download them, and then doing `sign manage` again? I ask because, based on the error you are reporting, it appears possible that you have a corrupt profile of some sort, and re-downloading them will help reduce this risk.

**Comment by ff-ahumberston** [comment]
@mpirri 
When connecting to the CI machine over SSH the error is evident, when accessing from the console we do not see the error.

**Comment by hjanuschka** [comment]
have you unlocked your keychains ?  `unlock_keychain` - i think this is one major difference in ssh over local terminal

**Comment by PlayDevelop** [comment]
I have also tried unlock_keychain with no result.  Also tried manually unlock with security -v unlock-keychain.

**Comment by PlayDevelop** [comment]
This post saved me: 
https://www.quernus.co.uk/2016/10/10/ssh-keychain-changes-macos-sierra/ 

1. On my CI machine, added my id_rsa.pub to ~/.ssh/authorized_keys 
All good now.

**Comment by ff-ahumberston** [comment]
I'm manually connecting to my host via an SSH connection, the suggestion would mean adding my id_rsa.pub to the same accounts ~/.ssh/authorized_keys 

(I've tried it and the problem still persists)

**Comment by PlayDevelop** [comment]
@ff-ahumberston  just to verify. 
1.On your client,  copy your ida_rsa.pub created at ~/.ssh/authorized_keys
2.On your ssh host `vim ~/.ssh/authorized_keys` and paste from step1 
3.Logout from host, reconnect. 

If you:  
`security list-keychain` 
on your ssh host. What do you get?

**Comment by ff-ahumberston** [comment]
I'm using a Windows 10 host to connect using SSH to my Sierra host.

I've created public/private keys on Windows host and I can now successfully run 
admin$ security list-keychain
    "/Users/admin/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"

sigh manage also works successfully

Thanks for your help Martin @PlayDevelop

**Comment by ff-ahumberston** [comment]
I guess we can mark this as closed, may be useful if sigh could give a pointer.
