### ISSUE TITLE
[Feature] Disabling encryption/decryption for Match

### ISSUE THREAD

**Issue by AlexTatarinchik** [fastlane/fastlane#6753]
### Issue Description

Add parameter to disable encryption/decryption operations for match.
### Environment

<details><summary>

✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| --- | --- |
| OS | 10.11.5 |
| Ruby | 2.3.1 |
| Bundler? | false |
| Xcode Path | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version | 8.0 |
| Git | git version 2.8.4 (Apple Git-73) |
| Installation Source | /usr/local/rvm/rubies/ruby-2.3.1/bin/fastlane |
| Host | Mac OS X 10.11.5 (15F34) |
| Ruby Lib Dir | /usr/local/rvm/rubies/ruby-2.3.1/lib |
| OpenSSL Version | OpenSSL 1.0.2h  3 May 2016 |
### fastlane files:

**No Fastfile found**

**No Appfile found**
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| spaceship | 0.36.2 | ✅ Up-To-Date |
| deliver | 1.14.5 | ✅ Up-To-Date |
| snapshot | 1.16.2 | ✅ Up-To-Date |
| frameit | 3.0.0 | ✅ Up-To-Date |
| pem | 1.3.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| pilot | 1.11.1 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| fastlane | 1.106.2 | ✅ Up-To-Date |
### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary>

<b>Loaded gems</b></summary>

| Gem | Version |
| --- | --- |
| did_you_mean | 1.0.0 |
| executable-hooks | 1.3.2 |
| bundler-unload | 1.0.2 |
| rubygems-bundler | 1.4.4 |
| bundler | 1.13.5 |
| io-console | 0.4.5 |
| highline | 1.7.8 |
| commander | 4.4.0 |
| terminal-table | 1.4.5 |
| json | 1.8.3 |
| multipart-post | 2.0.0 |
| faraday | 0.9.2 |
| faraday_middleware | 0.10.0 |
| dotenv | 2.1.1 |
| net-ssh | 3.2.0 |
| net-sftp | 2.1.2 |
| plist | 3.1.0 |
| rubyzip | 1.1.7 |
| security | 0.1.3 |
| krausefx-shenzhen | 0.14.10 |
| slack-notifier | 1.5.1 |
| i18n | 0.7.0 |
| thread_safe | 0.3.5 |
| tzinfo | 1.2.2 |
| minitest | 5.8.3 |
| activesupport | 4.2.7.1 |
| colored | 1.2 |
| claide | 1.0.1 |
| xcodeproj | 1.3.3 |
| rouge | 1.11.1 |
| xcpretty | 0.2.4 |
| terminal-notifier | 1.7.1 |
| addressable | 2.3.8 |
| xcode-install | 2.0.7 |
| word_wrap | 1.0.0 |
| multi_json | 1.12.1 |
| babosa | 1.0.2 |
| excon | 0.54.0 |
| gh_inspector | 1.0.2 |
| credentials_manager | 0.16.2 |
| fastlane_core | 0.53.0 |
| multi_xml | 0.5.5 |
| unf_ext | 0.0.7.2 |
| unf | 0.1.4 |
| domain_name | 0.5.20160826 |
| http-cookie | 1.0.3 |
| faraday-cookie_jar | 0.0.6 |
| fastimage | 1.6.8 |
| mini_magick | 4.5.1 |
| xcpretty-travis-formatter | 0.0.4 |
| uber | 0.0.15 |
| representable | 2.3.0 |
| retriable | 2.1.0 |
| mime-types-data | 3.2016.0521 |
| mime-types | 3.1 |
| hurley | 0.2 |
| little-plugger | 1.1.4 |
| logging | 2.1.0 |
| jwt | 1.5.6 |
| memoist | 0.15.0 |
| os | 0.9.6 |
| signet | 0.7.3 |
| googleauth | 0.5.1 |
| httpclient | 2.8.2.4 |
| google-api-client | 0.9.19 |

</details>

_generated on:_ **2016-10-26**
</details>

**Comment by TKBurner** [comment]
@AlexTatarinchik Thanks for your idea. Right now we aren't planning on implementing this. Can you let me know your use case, I'd be interested.

**Comment by KrauseFx** [comment]
Why do you want to enable/disable encryption for _match_?

**Comment by AlexTatarinchik** [comment]
The profiles and certificates are  stored on the private secure git server. Nobody have access to this git server without permission. Why I should use additional security level to protect profiles an certs?

**Comment by TKBurner** [comment]
@AlexTatarinchik Thanks for following up. We'll leave this open for now in case other users are interested in this use case. We'd be interested to know. Hope that you have a great week!

**Comment by tabrindle** [comment]
A different use case might be to be able to directly inspect the certificates/profiles inside the repo if you clone them down manually, without having to manually decrypt them. 

Sometimes I get an error where a profile in my repo is no longer available on the portal, and I would like to be able to see the UUID, devices, etc. The CLI tool suggests nuke, but all the profiles on the portal are valid, and the rest of the profiles in the repo are also valid. Just deleting the one profile manually will solve the issue.

**Comment by KrauseFx** [comment]
Interesting, I can see the use-case. If you feel like it, feel free to work on this feature, however it's not something we can invest time in. Personally I'm not sure if it's worth the effort.
