### ISSUE TITLE
Run `match nuke` from Fastfile without asking for confirmation

### ISSUE THREAD

**Issue by kylejm** [fastlane/fastlane#6754]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

Is there a way to run `match nuke` without it asking you for confirmation as below?

```
[10:06:08]: ▸ [10:06:08]: ---
[10:06:08]: ▸ [10:06:08]: Are you sure you want to completely delete and revoke all the
[10:06:08]: ▸ [10:06:08]: certificates and provisioning profiles listed above? (y/n)
[10:06:08]: ▸ [10:06:08]: Warning: The :app_identifier value will be ignored - this will delete all profiles for all your apps!
[10:06:08]: ▸ [10:06:08]: ---
```

I tried running with force but the question is still asked:

```
match nuke appstore -a __BUNDLE_ID__ --force true
```

**Comment by TKBurner** [comment]
@kylejm There isn't a way to programmatically nuke right now. Can you explain your use case? Thanks!

**Comment by savage7** [comment]
It's easy to do this with any command line script:
yes | ./script
This passes y, to pass n:
yes n | ./script

It use this with match when I automatically renew our dev certs on Jenkins, before renewing I always do a nuke.

Reference:
http://askubuntu.com/questions/338857/automatically-enter-input-in-command-line

**Comment by hjanuschka** [comment]
@kylejm  here is a PR wich should add support for `--force`  on match.

https://github.com/fastlane/fastlane/pull/6886 (lets see if this is going to be merged)

@TKBurner i see a use case where you wan't to have a clean run on CI or something like that.

**Comment by mpirri** [comment]
Merged the PR, thanks so much @hjanuschka !
