### ISSUE TITLE
How to change the last three directories to store the screen shots.example en-US/images/phoneScreenshots

### ISSUE THREAD

**Issue by Muthukathiravan** [fastlane/fastlane#6756]
### New Issue Checklist
- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
##### Complete output when running fastlane, including the stack trace and command used

```
[INSERT OUTPUT HERE]
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

[INSERT OUTPUT HERE]

**Comment by TKBurner** [comment]
Hi @Muthukathiravan Thanks for reaching out. You can use the --output_directory parameter to set the output, however we will still use our folder structure. You might need to run screengrab for each language separately. Thanks!
