### ISSUE TITLE
Match: Development Provisioning Profile only contains one certificate

### ISSUE THREAD

**Issue by bes** [fastlane/fastlane#6757]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Our team uses match to manage provisioning profiles, but since we switched to XCode 8 we have started using manually managed signing for Debug & Release, as recommended by the [Fastlane Docs](https://docs.fastlane.tools/codesigning/xcode-project/).

This works fine on my machine, but not on my colleagues' machines. Their error is `Provisioning profile "match Development com.our.App" doesn't include signing certificate "iPhone Developer: John Doe (XXXXXXX)".`

Obviously this worked in XCode 7 since each developer signed the app using their individually selected certificate when developing, but using the new setting as recommended by the guide forces the certificate to come from the development provisioning profile.

Checking the apple developer portal under `Provisioning Profiles > Development > match Development com.our.App > Edit` reveals that indeed, only MY certificate is selected.

Running e.g. `bundle exec match development --username my.user@domain.com --force true` does nothing to change this, the provisioning profile still only has my certificate.

I guess my question are:
- Am I wrong in assuming fastlane/match should handle updating the provisioning profile for me? 
- Should I go into the developer portal, select all certificates, and press "Generate"?
  - (This seems stupid since match promises to do this - although I have not found anything about this specific case in the documentation, I just get that feeling)

Thanks

**Comment by bes** [comment]
Any help on this would be greatly appreciated!

**Comment by bes** [comment]
![Hello?](https://media.giphy.com/media/TAqYM2x2WHoT6/giphy.gif)

**Comment by hjanuschka** [comment]
we are actually using - automatic codesigning for development - and set the prov.-profile-specifier to `$(sigh.....)` match env. var for `release` configuration.

having "auto codesigning" checked - development works on all dev-stations 👍 
on CI - we toggle the checkmark to off - so it uses manually signing - and then the `$(sigh....)`  comes into the game - wich sets the prov-profiles to the ones needed for release.


to toggle the codesigning see this plugin: https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning

this way we don't have any dev profiles or certs inside the match repo.
i am not sure if this is the 100% best way todo it - but it works across a few devs and a few apps.

**Comment by bes** [comment]
Thank you @hjanuschka! I saw your answer/post in another similar thread while googling (before posting my question), I will implement it that way for now.

I still have the feeling that this should be addressed by the fastlane team, especially since I followed all the guides properly (or at least that's what I think).

Some ways to address this issue, from the fastlane team, would be:
* Update the guides to reflect your proposed approach as the correct one.
* Update the guides to give steps for correctly setting up certificates / provisioning profiles for teams of more than one developer.

I appreciate that the fastlane developers have better things to do than to answer my silly questions, but I can't imagine I am the only one being affected by this.

<details>
<summary>Irrelevant Rant</summary>
I have been developing for iOS for more than one year now and I can't wrap my head around the fact that everything that has to do with signing is broken to the point where a massive add-on like fastlane is needed.

Before my iOS days I worked for a major Android phone company for 9 years and I can tell you that app signing and app distribution for Android is so easy compared to this; provisioning profile? Bah! Everyone can install your app as long as they have the APK! 

XCode is probably the worst IDE I have tried, and to put that in perspective I spent two years coding PHP in a PuTTy window using pico...
</details>

Anyway, thanks again!

**Comment by bes** [comment]
A-ha! It HAS been updated, but it has been done under the (my...) radar!

I just went in to check the XCode8 section of the fastlane docs, and reading it I discovered that it had a new section addressing my problems.

https://github.com/fastlane/docs/pull/170

**Comment by bes** [comment]
Please close this issue

**Comment by bes** [comment]
Here's what I did and what is working for us at the moment...

# Update your development provisioning profiles on developer.apple.com
Go to your account on https://developer.apple.com: `Certificates... > Provisioning Profiles > Development`

For all your match profiles update them (Edit) and add the certificates of all the developers on the team. (Why can't this be done by match itself? @KrauseFx )

# Update your provisioning profiles locally
Since you updated the profiles on apple's site, you need to update them in your match repo as well. For all your provisioning profiles do:

```
bundle exec match appstore --force --app_identifier "com.my.app.Identifier" --name my.apple.developer.email@domain.com
```

For me I needed to do it for all three provisioning profiles we have (iOS, Apple watch, Apple watch extension).

# Make sure you don't use automatic signing in XCode
Uncheck `Automatically manage signing` from all your Targets, you can find some hints on how to set things up here https://docs.fastlane.tools/codesigning/xcode-project/

For the record I have `Target > Build Settings >Provisioning Profile` and `Target > Build Settings >Provisioning Profile (Deprecated)` set to the same values, I don't know if that is strictly needed.

# Summary
It is possible to get stuff to work with some manual labour. Unfortunately this is what I was hoping match would do for me, maybe it does and I just have not figured it out yet?

<details>
<summary>Irrelevant Rant</summary>
Again, I just want to point out how utterly useless XCode is compared to basically any other development environment I have used in the last 20 years. If XCode were an app released by anyone but Apply itself, it would be instantly rejected from the App store for being unusable and buggy.
</details>

**Comment by jakerockland** [comment]
Also experiencing this issue, @bes your solution was very helpful! 😄

**Comment by jaroslavas** [comment]
Would be a very good present for Christmas if fastlane team would add a feature to include all certificates in Development Provisioning Profile :)

**Comment by rhcpfan** [comment]
@bes If you modify the profile on the developer portal in the beginning (to add another development certificate) and use `--force`, doesn't this re-create the profiles?

**Comment by bes** [comment]
@rhcpfan The profile still has the same name (on the developer profile). Maybe technically it's a new profile (new contents, etc.) but when force updating them the match git repo is updated and after synchronizing everything seems to work.

Maybe not a straight answer to your question - is the profile recreated? I don't know if I'm qualified to answer that, but as far as I can tell for us this approach works.

Hope this answers your question.

**Comment by rhcpfan** [comment]
@bes In the documentation of `match`, it says that the `--force` parameter does the following: `Renew the provisioning profiles every time you run match`. 

I have modified the provisioning profile on the developer portal to include another development certificate, and after running the command you mentioned, it deleted the existing profile from the dev portal (the one I have modified) and created a new one that contained only my developer certificate

**Comment by bes** [comment]
@rhcpfan Now I understand what you mean, and after many months of using fastlane I have finally understood how THEY want you to use fastlane/match

From https://codesigning.guide/
> The basic requirement is to have one code signing identity shared across your team. The easiest way to do that is to create a new Apple ID for the team (e.g. ios-dev@company.com) and use that from now on. To get started:

They want us (you, me) to use ONE code signing identity PER TEAM! With a "shared Apple ID for the team".

I will now go ahead and reconfigure our project using that model. Maybe it was clear for everyone from the beginning, (RTFM & so on), but it had totally passed me by. This should basically be the first sentence in bold capital 50em font on the fastlane/match front page:

"YOUR WHOLE TEAM SHOULD SHARE ONE APPLE ID, ONE CERTIFICATE!"


If this is totally banans, and I have misunderstood the whole thing _again_, please do tell.

**Comment by bes** [comment]
What we are currently doing, and what seems to be the correct way of doing things:

As stated on https://codesigning.guide/, when using match to distribute/share/simplify code signing, one should use ONE COMMON apple id, shared between ALL team members.

What I have done most recently in our team

# Create a common Apple ID
Google how to do this, it will probably change, so no point in describing this.

Distribute the username and password to this account, securely, within your team. E.g. use GPG to share the credentials.

# Update your fastlane/match credentials to point at the new account
`fastlane fastlane-credentials add --username ourcommon@appleid.com`

I also opened the keychain and manually deleted my old credentials:

* The certificate called `iPhone Developer: XXXX@yyy.com`
* The key ("Internet password") called `deliver.XXXX@yyy.com`

# Nuke your old match git
There does not seem to be any easy way to update the certs in the git, but some people have attempted to do it with success: http://macoscope.com/blog/simplify-your-life-with-fastlane-match/#migration

Personally, I just nuked our repo and started fresh

# Start fresh
`bundle exec fastlane match development`

# Done
At this point (if I have not missed some step) you, and everyone on your team, should be able to use fastlane as usual.

**Comment by rhcpfan** [comment]
We are not using a single Apple ID per team, every member of the team has it's own Apple ID. The thing is that we are doing public releases (on  TestFlight and on the AppStore) only from one account (we have a Mac Mini that we are using as a release server). In this case, every developer has enabled the "Automatically manage signing" thingy in Xcode 8 (to use for development) and only the server is configured for distribution...

**Comment by beretis** [comment]
So the only way to run this on multiple machines is to reuse 1 apple id to sign apps? When I read about match in a article, it was mention that its optional.

**Comment by Alesete** [comment]
Hello everyone! are there any plan to support multiple apple id to match? 

The policy in my company is that every developer should have their own apple id, so their accounts can be easily managed and deactivated when they eventually leave the company. Also, we can manage the admin permissions only for trusted people.

It would be very nice that everybody store their apple ID locally in their machines, and then match simply generate and add their certificates to the existing provisioning profile (updating and syncing the provisioning across the team), instead of recreate the profile with only one certificate.

Is only a suggestion, if not possible, thanks anyway!

**Comment by bes** [comment]
@Alesete I think it is better if you open a new issue, because it was a long time since someone from the fastlane team commented here. Feel free to reference this issue when you do.

**Comment by Alesete** [comment]
@bes You are right!

**Comment by Appuploader** [comment]
Share Appuploader tool only need to enter the iOS certificate name, password can quickly apply for iOS certificate. P12 and ..mobileprovision iOS certificate file

But also in the Windows system directly apply for iOS certificate

https://github.com/Appuploader/applicationloader

**Comment by KrauseFx** [comment]
Hey everyone, sorry for not replying earlier. Yeah, creating a new issue is the way to go, if you have any similar problems 👍
