### ISSUE TITLE
Find the currently published build number on App Store

### ISSUE THREAD

**Issue by fotiDim** [fastlane/fastlane#6770]
### New Issue Checklist
- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

This is a feature request I suppose. I need a way to be able to get the **currently published build number** on App Store. `Latest_testflight_build_number` returns the latest build number from my uploaded builds but I need the build number of the latest published one (the one being sold on the App Store). Is there any way to achieve that?

**Comment by hjanuschka** [comment]
ok i am not 100% sure if this is the most elegant way to solve it but i tested it on 5 apps apps.

```
lane :get_prod_build_nr do
    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find("krone.at-fivexfive")
    version = app.live_version
    latest_prod_build_nr = version.raw_data["preReleaseBuild"]["buildVersion"]
    puts "#{latest_prod_build_nr}"
end

```

**Comment by fotiDim** [comment]
@hjanuschka you sir are wonderful. Worked like a charm. I only had to alter `Spaceship::Tunes.login("email@icloud.com")` to include my ITC email and not ask for login interactively.

I really think this should be a fastlane feature.

**Comment by hjanuschka** [comment]
nice to know it helps - you can set the right env vars to get arround the fixed email@icloud.com - fastlane should named them

**Comment by hjanuschka** [comment]
@KrauseFx  i am not sure on how to add this to spaceship - so `app.live_version`  has the key's set - any idea where to start from? - after it is in spaceship - i think it would be easy  to add an action like `latest_live_build_number` - or modify `Latest_testflight_build_number` to be also capable to return the production build nr.

**Comment by hjanuschka** [comment]
ok got it -  here is the PR to add spaceship support for the build_number https://github.com/fastlane/fastlane/pull/6785

**Comment by TKBurner** [comment]
@fotiDim The only way to do this is through spaceship directly. Let me know if you run into any issues once you try that 👍 Have a great weekend!

**Comment by TKBurner** [comment]
@hjanuschka Nice! Thanks so much for your continued help with this 👍

**Comment by hjanuschka** [comment]
@fotiDim there we go here is the PR to include a fastlane action for this 👍 
https://github.com/fastlane/fastlane/pull/6790

**Comment by fotiDim** [comment]
I think this issue can be closed now. Just a question for the sake of curiosity. I am executing this code:
`   require 'spaceship'
    Spaceship::Tunes.login("user@icloud.com")
    app = Spaceship::Tunes::Application.find("com.org.app")
    build_trains = app.build_trains.keys
    puts build_trains`

which returns
`1.3.3 1.4`

Is it this?
<img width="1427" alt="screen shot 2016-11-10 at 17 45 28" src="https://cloud.githubusercontent.com/assets/2326415/20183395/d855c2c6-a76d-11e6-8017-48cd5aa269ac.png">

So build_trains are the app versions currently in Testflight?

**Comment by hjanuschka** [comment]
yes those are the build trains.


this is how `latest_testflight_build_number` works.:


```ruby
app = Spaceship::Tunes::Application.find("krone.at-fivexfive")
trains = app.build_trains.keys
train = app.build_trains[trains.last]
build_nr = train.builds.map(&:build_version).map(&:to_i).sort.last
```

**Comment by KrauseFx** [comment]
Awesome, thanks @hjanuschka 👍
