### ISSUE TITLE
Supply - as a deliver file

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#6771]
will Supply ever have a deliver file rather than the meta folder and .txt files?

**Comment by asfalcone** [comment]
@prolog3001 At this time we don't have a plan to change the structure of the _supply_ metadata. Could you describe why you'd prefer that?

**Comment by prolog3001** [comment]
Many of our app data just need some simple text replace... and on a single file it is much much easier.

**Comment by TKBurner** [comment]
@prolog3001 We'll leave this open as a suggestion 👍
