### ISSUE TITLE
Supply - wait for "Update is live in the store" response from Google Play

### ISSUE THREAD

**Issue by tomachi** [fastlane/fastlane#6772]
### Issue Description

Is there an option for supply to add a flag for waiting until the app hits the Play Store (same like in pilot you can wait for processing to be done).
Usually it can take couple of hours and we would like to send an automated email from jenkins to our testers when the app is live in the store.

Fastlane 1.105.3

**Comment by asfalcone** [comment]
@tomachi thanks for the feature request. We use the [Google Api Client](https://github.com/google/google-api-ruby-client) for interacting with Google Play. If there is a api for knowing when a version is live, this is something that we'd accept a PR for. 👍
