### ISSUE TITLE
fastlane env --quiet option or --force

### ISSUE THREAD

**Issue by MaximusMcCann** [fastlane/fastlane#6781]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Would like to run `bundle exec fastlane env` on our CI box.  piping in 'n' results in the same error.  Would like a --force option if possible :)

##### Complete output when running fastlane, including the stack trace and command used

```
bundler: failed to load command: fastlane (/Users/distiller/ios/vendor/bundle/ruby/2.3.0/bin/fastlane)
FastlaneCore::Interface::FastlaneCrash: [!] Could not retrieve response as fastlane runs in non-interactive mode
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

would like `fastlane env --force` or `fastlane env --quiet` as a possibility :)

Partial

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| spaceship           | 0.36.2  | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| deliver             | 1.14.5  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| pem                 | 1.3.2   | ✅ Up-To-Date        |
| pilot               | 1.11.1  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| snapshot            | 1.16.2  | 🚫 Update availaible |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| fastlane            | 1.106.2 | ✅ Up-To-Date        |

**Comment by KrauseFx** [comment]
Oh wow, nice catch, thanks 👍  Working on this right now

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/6782  🚀This will be in the next release
