### ISSUE TITLE
how to get XCode user defined settings in a lane

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#6795]
### New Issue Checklist
- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
### Issue Description

How can I get the value of a user defined setting in my Xcode project for use in a lane? Let's call it MY_CUSTOM_ID for discussion. It is printing the variable in the gym log file (under ~/Library/Logs/gym) as "export MY_CUSTOM_ID=xxx".   But trying to get it via ENV['MY_CUSTOM_ID'] is blank. 

Some additional context is at the link below but its more of a general fastlane question. 
https://github.com/hjanuschka/fastlane-plugin-upload_symbols_to_new_relic/issues/2
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>

✅ fastlane environment ✅</summary>

### Stack

| Key | Value |
| --- | --- |
| OS | 10.12.1 |
| Ruby | 2.3.1 |
| Bundler? | false |
| Xcode Path | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version | 8.1 |
| Git | git version 2.10.0 |
| Installation Source | /Users/vamsee/Software/ruby/bin/fastlane |
| Host | Mac OS X 10.12.1 (16B2555) |
| Ruby Lib Dir | /usr/local/Cellar/ruby/2.3.1/lib |
| OpenSSL Version | OpenSSL 1.0.2h  3 May 2016 |
### fastlane gems

| Gem | Version | Update-Status |
| --- | --- | --- |
| credentials_manager | 0.16.2 | ✅ Up-To-Date |
| spaceship | 0.36.2 | ✅ Up-To-Date |
| fastlane_core | 0.53.0 | ✅ Up-To-Date |
| deliver | 1.14.5 | ✅ Up-To-Date |
| snapshot | 1.16.3 | ✅ Up-To-Date |
| frameit | 3.0.0 | ✅ Up-To-Date |
| pem | 1.3.2 | ✅ Up-To-Date |
| cert | 1.4.3 | ✅ Up-To-Date |
| sigh | 1.11.2 | ✅ Up-To-Date |
| produce | 1.2.1 | ✅ Up-To-Date |
| gym | 1.11.3 | ✅ Up-To-Date |
| pilot | 1.11.1 | ✅ Up-To-Date |
| scan | 0.13.1 | ✅ Up-To-Date |
| supply | 0.7.1 | ✅ Up-To-Date |
| match | 0.10.0 | ✅ Up-To-Date |
| screengrab | 0.5.5 | ✅ Up-To-Date |
| fastlane | 1.106.2 | ✅ Up-To-Date |
### Loaded fastlane plugins:

| Plugin | Version | Update-Status |
| --- | --- | --- |
| fastlane-plugin-upload_symbols_to_new_relic | 0.1.1 | ✅ Up-To-Date |

<details><summary>

<b>Loaded gems</b></summary>

| Gem | Version |
| --- | --- |
| did_you_mean | 1.0.0 |
| highline | 1.7.8 |
| commander | 4.4.0 |
| terminal-table | 1.4.5 |
| json | 1.8.3 |
| multipart-post | 2.0.0 |
| faraday | 0.9.2 |
| faraday_middleware | 0.10.0 |
| dotenv | 2.1.1 |
| net-ssh | 3.2.0 |
| net-sftp | 2.1.2 |
| plist | 3.1.0 |
| rubyzip | 1.1.7 |
| security | 0.1.3 |
| krausefx-shenzhen | 0.14.10 |
| slack-notifier | 1.5.1 |
| i18n | 0.7.0 |
| thread_safe | 0.3.5 |
| tzinfo | 1.2.2 |
| activesupport | 4.2.7.1 |
| CFPropertyList | 2.3.3 |
| claide | 1.0.1 |
| colored | 1.2 |
| nanaimo | 0.1.2 |
| xcodeproj | 1.4.0 |
| rouge | 1.11.1 |
| xcpretty | 0.2.4 |
| terminal-notifier | 1.7.1 |
| addressable | 2.4.0 |
| credentials_manager | 0.16.2 |
| multi_xml | 0.5.5 |
| unf_ext | 0.0.7.2 |
| unf | 0.1.4 |
| domain_name | 0.5.20161021 |
| http-cookie | 1.0.3 |
| faraday-cookie_jar | 0.0.6 |
| fastimage | 1.6.8 |
| xcode-install | 2.0.8 |
| word_wrap | 1.0.0 |
| multi_json | 1.12.1 |
| babosa | 1.0.2 |
| excon | 0.54.0 |
| gh_inspector | 1.0.2 |
| fastlane_core | 0.53.0 |
| bundler | 1.12.5 |
| mini_magick | 4.5.1 |
| xcpretty-travis-formatter | 0.0.4 |
| uber | 0.0.15 |
| representable | 2.3.0 |
| retriable | 2.1.0 |
| mime-types-data | 3.2016.0521 |
| mime-types | 3.1 |
| hurley | 0.2 |
| little-plugger | 1.1.4 |
| logging | 2.1.0 |
| jwt | 1.5.6 |
| memoist | 0.15.0 |
| os | 0.9.6 |
| signet | 0.7.3 |
| googleauth | 0.5.1 |
| httpclient | 2.8.2.4 |
| google-api-client | 0.9.19 |
| io-console | 0.4.5 |
| fastlane-plugin-upload_symbols_to_new_relic | 0.1.1 |

</details>

_generated on:_ **2016-10-29**
</details>

**Comment by hjanuschka** [comment]
i think that the `export` inside the log is printed by `xcodebuild` itself - wich is not a part of fastlane (atleast not directly) - i guess.


can you provide a trimmed-to-essentials sample project? so we can see where you set `MY_CUSTOM_ID` ?

**Comment by lakamsani** [comment]
@hjanuschka  you may be right. The nice thing is that xcodebuild is doing the required scheme specific variable expansion (in this case NEW_RELIC_ID) that I 'm unable to get via the get_info_plist_value action even if I can get past the problem of dynamically building the target specific plist path. 

Trimmed project is a bit of work but here are 3 semi-anonymized screenshots that might convey my setup enough to may be setup something if someone feels like its worth supporting. 

Lets start with build settings. In this screenshot you can see a variable called NEW_RELIC_ID initialized to one of the 3 New Relic app keys on the right (anonymized with black,  purple and red) depending on the build scheme.  The three schemes are shown at the top left (for Adhoc, Debug and Release respectively) for the selected target on the immediate left. 

You can also see 7 targets on the left each of which has 3 schemes, corresponding to build configs for Adhoc, Debug, Release which nicely map to match provisioning profiles. I have a ruby settings file where I specify the New Relic app ids as I only need them during symbol upload. The 3 app keys in the build settings are however needed by the Swift code and Xcode IDE so they can't live in the outside ruby settings file (may be there is some clever way to do that I don't know). 

<img width="1188" alt="3-new-relic-ids-per-target" src="https://cloud.githubusercontent.com/assets/3322496/19871236/4bc3aaca-9f71-11e6-9d97-6f48fcb64346.png">

Here is a build config in the scheme. 
<img width="765" alt="build-config" src="https://cloud.githubusercontent.com/assets/3322496/19871235/4bc28b4a-9f71-11e6-86de-e19c1f1147ce.png">

Here is the plist (one per target) that has a NewRelicAppId initialized to the aforementioned NEW_RELIC_ID. In the Swift is it accessed as newRelicAppId = infoPlist["NewRelicAppId"] as we discussed in the other thread in your plugin repo. 

<img width="950" alt="info-plist" src="https://cloud.githubusercontent.com/assets/3322496/19871234/4bc1089c-9f71-11e6-8822-418857a78304.png">

The Swift app at runtime picks up the right New Relic key based on the scheme. It is also printed in the gym log file (which I have extracted in the lane I shared on the other thread).

**Comment by lakamsani** [comment]
I should add that if Fabric is much better at handling multiple apps compared this New Relic complication with multiple keys but our apps need this data in  both for various reasons.

**Comment by hjanuschka** [comment]
ok got you, yeah me too thinks that fabric is eaysier to handle, but anyway - its not the tool you use so - lets try it  👏 


you can use the `xcodeproj` gem - than something like this would work (i guess, as said without a sample project wich i can clone - its hard to 100% verify)


```
require 'xcodeproj'

proj = XcodeProject::Project.new('app.xcodeproj')
data = proj.read
ENV['NEW_RELIC_ID'] =  data.target('example').config('Release').build_settings['NEW_RELIC_ID']

```

you have to adjust the target and config - and probably use `.inspect` on `data.target('example').config('Release').build_settings`  to see what it returns 🙏

**Comment by lakamsani** [comment]
Thanks for that suggestion. Somehow your code does not work in a lane. Gives an error like this:

Fastfile:398:in `block (2 levels) in parsing_binding': [!] undefined method `target' for #<Xcodeproj::Project:0x007fee8b99f7d8> (NoMethodError)
Did you mean?  targets

If I change it to targets it says I need to supply a integer index into it. I looked up docs but didn't find much. After some trial and error this kind of looping gets the right values but would be nicer if there is a working hash based indexing to get to them directly. 

    project = Xcodeproj::Project.open('../iPhone/My.xcodeproj')
    project.targets.each do |target|
        target.build_configurations.each do |config|
            puts config.build_settings['NEW_RELIC_ID']
        end
    end

**Comment by hjanuschka** [comment]
hmmm - ok seems to be i was reffing to another gem :D `xcodeproject` instead of `xcodeproj` - seems to be a fork - bet


```ruby
require 'xcodeproject'
proj = XcodeProject::Project.new('app.xcodeproj')
data = proj.read
ENV['NEW_RELIC_ID'] =  data.target('example').config('Release').build_settings['NEW_RELIC_ID']

```

**Comment by lakamsani** [comment]
yes. that works. thanks.

**Comment by hjanuschka** [comment]
awesome 🚀 , glad it helped!

**Comment by lakamsani** [comment]
@hjanuschka  while that worked in a test lane, the xcodeproject gem seems to trigger a conflict in another lane where gym is used. here's the error. I have gym 1.11.3. I 'm going to stay with my solution of parsing the gym build log for now. You might be able to reproduce this easily in a test project. Just try to invoke gym with the xcodeproject-0.3.13 gem installed. If you remove xcodeproject gem gym runs fine. 

```bash
[20:30:20]: ▸ Archive Succeeded
[20:30:20]: Generated plist file with the following values:
[20:30:20]: ▸ -----------------------------------------
[20:30:20]: ▸ {
[20:30:20]: ▸   "method": "ad-hoc"
[20:30:20]: ▸ }
[20:30:20]: ▸ -----------------------------------------
[20:30:20]: Variable Dump:
[20:30:20]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :SIGH_PROFILE_TYPE=>"ad-hoc"}
[20:30:20]: undefined method `to_plist' for :method:Symbol

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 61          |
| 4    | match                               | 12          |
| 💥    | gym                                 | 383         |
+------+-------------------------------------+-------------+

[20:30:20]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Users/me/Software/ruby/gems/xcodeproject-0.3.13/lib/xcodeproject/extend/hash.rb:30:in `block in to_plist': [!] undefined method `to_plist' for :method:Symbol (NoMethodError)
	from /Users/me/Software/ruby/gems/xcodeproject-0.3.13/lib/xcodeproject/extend/hash.rb:30:in `each'
	from /Users/vamsee/Software/ruby/gems/xcodeproject-0.3.13/lib/xcodeproject/extend/hash.rb:30:in `map'
	from /Users/vamsee/Software/ruby/gems/xcodeproject-0.3.13/lib/xcodeproject/extend/hash.rb:30:in `to_plist'
	from /Users/vamsee/Software/ruby/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:175:in `config_content'
	from /Users/vamsee/Software/ruby/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:19:in `generate'
	from /Users/vamsee/Software/ruby/gems/gym-1.11.3/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Users/vamsee/Software/ruby/gems/gym-1.11.3/lib/gym/runner.rb:118:in `package_app'
```

Without xcodeproject gem, gym output looks like this around the same lines and it succeeds. 

```bash
....
....
[20:49:15]: ▸ Archive Succeeded
[20:49:16]: Generated plist file with the following values:
[20:49:16]: ▸ -----------------------------------------
[20:49:16]: ▸ {
[20:49:16]: ▸   "method": "ad-hoc"
[20:49:16]: ▸ }
[20:49:16]: ▸ -----------------------------------------
[20:49:16]: $ /usr/bin/xcrun /Users/me/Software/ruby/gems/gym-1.11.3/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/69/5dwbppxx1h1c89l7msfw05fm0000gn/T/gym_config20161031-43664-1fh14l8.plist' -archivePath /Users/vamsee/Library/Developer/Xcode/Archives/2016-10-31/MyApp\ 2016-10-31\ 20.43.40.xcarchive -exportPath '/var/folders/69/5dwbppxx1h1c89l7msfw05fm0000gn/T/gym_output20161031-43664-1fqkt2f'
[20:50:04]: Compressing 17 dSYM(s)
....
... 
````

**Comment by lakamsani** [comment]
Seems like xcodeproject is somewhat older and not actively maintained. 
https://rubygems.org/gems/xcodeproject/versions (last version at 0.3.13 in dec, 2014)

whereas xcodeproj seems to be more actively maintained.
https://rubygems.org/gems/xcodeproj/versions (last version 1.4.0 a couple of days ago). 

Sounds like that older xcodeproject doesn't play well with gym. I will look into solving this (low pri) via xcodeproj as an alternative to parsing gym logs.

**Comment by lakamsani** [comment]
Here is another approach that does not involve importing anything extra and does not involve parsing gym log file. 

```ruby

    # assume we got the following three via some  via some app custom hash
    target='MyAppDebug'
    build='Debug'
    nrAppId = 'nr-myAppDebug
' 
    # figure out the nr key by looping through the project targets.
      nrKey = ''
      project = Xcodeproj::Project.open('../MyApp.xcodeproj')
      project.targets.each do |mtarget|
          if mtarget.name == target
              mtarget.build_configurations.each do |mbuild|
                  if mbuild.name == build
                      nrKey =  mbuild.build_settings['NEW_RELIC_ID'].chomp
                  end
              end
          end
      end
      
      puts "  #{nrKey} #{nrAppId}"
      unless nrAppId.nil?
          upload_symbols_to_new_relic(
                new_relic_license_key: nrKey,
                new_relic_app_name: nrAppId
            )
      end
      
```
