### ISSUE TITLE
sigh: ambiguous option: -f

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/fastlane#6796]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
sigh's help says -f should work as --force
However, it is not the case. While --force works, -f does not.

##### Complete output when running fastlane, including the stack trace and command used

```
 admin$ sigh manage -f -p ".*"
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:379:in `parse_global_options': ambiguous option: -f (OptionParser::AmbiguousOption)
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:31:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/commands_generator.rb:120:in `run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/commands_generator.rb:11:in `start'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/bin/sigh:6:in `<top (required)>'
        from /Users/admin/.rbenv/versions/2.3.1/bin/sigh:23:in `load'
        from /Users/admin/.rbenv/versions/2.3.1/bin/sigh:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.11.6                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 7.3.1                                           |
| Git                 | git version 2.7.4 (Apple Git-66)                |
| Installation Source | /Users/admin/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                      |
| Ruby Lib Dir        | /Users/admin/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.1.2        |
| xcodeproj                 | 1.4.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.4.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
</details>

*generated on:* **2016-10-29**
</details>

Looking for related GitHub issues on fastlane/fastlane...

➡️  invalid byte sequence in US-ASCII
   https://github.com/fastlane/fastlane/issues/2253 [closed] 2 💬
   5 weeks ago

➡️  invalid byte sequence in US-ASCII
   https://github.com/fastlane/fastlane/issues/2389 [closed] 2 💬
   5 weeks ago

➡️  invalid byte sequence in US-ASCII (ArgumentError)
   https://github.com/fastlane/fastlane/issues/227 [closed] 20 💬
   6 weeks ago

and 15 more at: https://github.com/fastlane/fastlane/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:730:in `gsub': [!] invalid byte sequence in US-ASCII (ArgumentError)
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:730:in `format_statement'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:621:in `say'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:261:in `ask'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:227:in `agree'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/implementations/shell.rb:98:in `confirm'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:237:in `block (2 levels) in run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:246:in `run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:23:in `start'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/bin/fastlane:5:in `<top (required)>'
        from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:22:in `load'
        from /Users/admin/.rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'

**Comment by KrauseFx** [comment]
```
sigh --help
```

```
  sigh

  CLI for 'sigh' - Because you would rather spend your time building stuff than fighting provisioning

  Commands:
    download_all Downloads all valid provisioning profiles
    help         Display global or [command] help documentation
    manage       Manage installed provisioning profiles on your system.
    renew        Renews the certificate (in case it expired) and outputs the path to the generated file
    repair       Repairs all expired or invalid provisioning profiles
    resign       Resigns an existing ipa file with the given provisioning profile

  Global Options:
    --verbose
    --adhoc [VALUE]      Setting this flag will generate AdHoc profiles instead of App Store Profiles (SIGH_AD_HOC)
    --development [VALUE] Renew the development certificate instead of the production one (SIGH_DEVELOPMENT)
    --skip_install [VALUE] By default, the certificate will be added on your local machine. Setting this flag will skip this action (SIGH_SKIP_INSTALL)
    --force [VALUE]      Renew provisioning profiles regardless of its state - to automatically add all devices for ad hoc profiles (SIGH_FORCE)
    -a, --app_identifier STRING The bundle identifier of your app (SIGH_APP_IDENTIFIER)
    -u, --username STRING Your Apple ID Username (SIGH_USERNAME)
    -b, --team_id STRING The ID of your team if you're in multiple teams (SIGH_TEAM_ID)
    -l, --team_name STRING The name of your team if you're in multiple teams (SIGH_TEAM_NAME)
    -n, --provisioning_name STRING The name of the profile that is used on the Apple Developer Portal (SIGH_PROVISIONING_PROFILE_NAME)
    --ignore_profiles_with_different_name [VALUE] Use in combination with :provisioning_name - when true only profiles matching this exact name will be downloaded
(SIGH_IGNORE_PROFILES_WITH_DIFFERENT_NAME)
    -o, --output_path STRING Directory in which the profile should be stored (SIGH_OUTPUT_PATH)
    -i, --cert_id STRING The ID of the code signing certificate to use (e.g. 78ADL6LVAA)  (SIGH_CERTIFICATE_ID)
    -c, --cert_owner_name STRING The certificate name to use for new profiles, or to renew with. (e.g. "Felix Krause") (SIGH_CERTIFICATE)
    -q, --filename STRING Filename to use for the generated provisioning profile (must include .mobileprovision) (SIGH_PROFILE_FILE_NAME)
    -w, --skip_fetch_profiles [VALUE] Skips the verification of existing profiles which is useful if you have thousands of profiles (SIGH_SKIP_FETCH_PROFILES)
    -z, --skip_certificate_verification [VALUE] Skips the verification of the certificates for every existing profiles. This will make sure the provisioning profile can be used
on the local machine (SIGH_SKIP_CERTIFICATE_VERIFICATION)
    -h, --help           Display help documentation
    -v, --version        Display version information
```

doesn't list `-f`, I'll add it for the `:force` parameter 👍

**Comment by GoodMirek** [comment]
`sigh manage --help` documents it.

```
admin$ sigh manage --help

  manage

  Usage: sigh manage

  Manage installed provisioning profiles on your system.

  Examples:

    # Remove all "iOS Team Provisioning" provisioning profiles
    sigh manage -p "iOS\ ?Team Provisioning Profile"

  Options:
    -f, --force          Force remove all expired provisioning profiles. Required on CI.
    -e, --clean_expired  Remove all expired provisioning profiles.
    -p, --clean_pattern STRING Remove any provisioning profiles that matches the regular expression.

```

**Comment by GoodMirek** [comment]
@KrauseFx Unfortunately, it still does not work:
```
DN:~ admin$ sigh manage -f --clean_pattern ".*"
/Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:379:in `parse_global_options': ambiguous option: -f (OptionParser::AmbiguousOption)
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.55.0/lib/fastlane_core/ui/fastlane_runner.rb:31:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/commands_generator.rb:120:in `run'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/sigh/commands_generator.rb:11:in `start'
        from /Users/admin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/bin/sigh:6:in `<top (required)>'
        from /Users/admin/.rbenv/versions/2.3.1/bin/sigh:23:in `load'
        from /Users/admin/.rbenv/versions/2.3.1/bin/sigh:23:in `<main>'
DN:~ admin$ sigh -v
sigh 1.11.2
```

**Comment by TKBurner** [comment]
Thanks for reporting this @GoodMirek I've sent this out to the core team to take a look. Thanks 👍

**Comment by hjanuschka** [comment]
@GoodMirek i think you ll have to wait for the next update of `sigh` - then the commit should be included.

**Comment by GoodMirek** [comment]
Thanks, I did not realize that sigh was not updated as part of fastlane
1.108.

**Comment by hjanuschka** [comment]
each gem gets released one by one. - so with the next sigh release, and the following fastlane update  - it should be included.
