### ISSUE TITLE
Register new Pass Type ID

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#6799]
Following this question https://github.com/fastlane/fastlane/issues/2067, is it possible to register new Pass Type IDs using fastlane? I'm aware that there is support to build upon already registered ids, but how can I create them automatically for every new app? Thanks,

**Comment by TKBurner** [comment]
@pedro380085 This is not currently possible but I'll mark it as a feature request to see if others are interested. Thanks!

**Comment by DavidSporer** [comment]
Refistering Pass Type IDs would be especially useful if you could also create a certificate for it.
