### ISSUE TITLE
Could not find proper version of fastlane

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#6802]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When ever i run fastlane it says:

> Could not find proper version of fastlane (1.101.0) in any of the sources
> Run `bundle install` to install missing gems.

I know this is a ruby issue:

```
gem list fastlane


*** LOCAL GEMS ***

fastlane (1.106.2)
fastlane-plugin-figlet (0.1.0)
fastlane-plugin-version_f
```

Any idea where my missing reference to 1.101.0 would be??  I'm confused.  Thanks!

This also only occurs in ONE of my fastlane projects not all of them...???

**Comment by KrauseFx** [comment]
I assume you have a `Gemfile` somewhere? Can you run `[sudo] bundle install`?

**Comment by milch** [comment]
Also, can you run `fastlane env` and attach that output to this issue? Preferably it'd also include the `Fastfile` from the project where the problem occurs.

**Comment by heatherSnepenger** [comment]
Hey there - @jeeftor were you able to resolve this? I'm running into a similar issue. I've updated fastlane, and after that didn't work, even uninstalled, then reinstalled.

Any solutions?

**Comment by milch** [comment]
> Hey everyone, we've been working on a new way to install and use fastlane, all you have to do is to download `fastlane.zip` and double click the `install` file. This will install fastlane with all its Ruby and OpenSSL dependencies, and should all work out of the box.
We just finished building this, and would love your early feedback on this beta. Please let us know how it works for you and if you run into any problems :+1: 
Download the latest version [here](https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip).

Since this issue is unrelated, I would recommend you try out the fastlane bundle we've been testing. Let me know if this works for you, @heatherSnepenger and @jeeftor!

**Comment by MattKiazyk** [comment]
@milch had the same issue as @jeeftor stated above. The `fastlane.zip` file worked perfectly, and all my problems have disappeared.

**Comment by milch** [comment]
@MattKiazyk Thanks for reporting back! 

I'll close this issue for now. @jeeftor and @heatherSnepenger let me know if you still experience problems, then we'll reopen this.
