### ISSUE TITLE
Application specific password seems wrong

### ISSUE THREAD

**Issue by suzhaev** [fastlane/fastlane#6805]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I turned on 2fa auth for my apple id.
I tried running my fastlane script this evening and received this error:

##### Complete output when running fastlane, including the stack trace and command used

```
[19:36:37]: ▸ [19:36:37]: Ready to upload new build to TestFlight (App: 1161154268)...
[19:36:37]: ▸ [19:36:37]: Going to upload updated app to iTunes Connect
[19:36:37]: ▸ [19:36:37]: This might take a few minutes. Please don't interrupt the script.
[19:36:41]: ▸ 
[19:36:42]: ▸ [19:36:42]: Transporter transfer failed.
[19:36:42]: ▸ [19:36:42]: 
[19:36:42]: ▸ 
[19:36:42]: ▸ [19:36:42]: Application specific password seems wrong
[19:36:42]: ▸ [19:36:42]: Please make sure to follow the instructions
[19:36:42]: ▸ security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[19:36:42]: ▸ [19:36:42]: Your account has 2 step verification enabled
[19:36:42]: ▸ [19:36:42]: Please go to https://appleid.apple.com/account/manage
[19:36:42]: ▸ [19:36:42]: and generate an application specific password for
[19:36:42]: ▸ [19:36:42]: the iTunes Transporter, which is used to upload builds
[19:36:42]: ▸ [19:36:42]: Going to upload updated app to iTunes Connect
[19:36:42]: ▸ [19:36:42]: This might take a few minutes. Please don't interrupt the script.
[19:36:46]: ▸ 
[19:36:46]: ▸ [19:36:46]: Transporter transfer failed.
[19:36:46]: ▸ [19:36:46]: 
[19:36:46]: ▸ 
[19:36:46]: ▸ [19:36:46]: Application specific password seems wrong
[19:36:46]: ▸ [19:36:46]: Please make sure to follow the instructions
[19:36:46]: ▸ security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[19:36:46]: ▸ [19:36:46]: Your account has 2 step verification enabled
[19:36:46]: ▸ [19:36:46]: Please go to https://appleid.apple.com/account/manage
[19:36:46]: ▸ [19:36:46]: and generate an application specific password for
[19:36:46]: ▸ [19:36:46]: the iTunes Transporter, which is used to upload builds
[19:36:46]: ▸ [19:36:46]: Going to upload updated app to iTunes Connect
[19:36:46]: ▸ [19:36:46]: This might take a few minutes. Please don't interrupt the script.
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                |
| ------------------- | ---------------------------------------------------- |
| OS                  | 10.12.1                                              |
| Ruby                | 2.3.1                                                |
| Bundler?            | false                                                |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version       | 8.1                                                  |
| Git                 | git version 2.9.3 (Apple Git-75)                     |
| Installation Source | /Users/***/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                           |
| Ruby Lib Dir        | /Users/***/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                          |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  def beta_client
    ipa = gym(scheme: "***", use_legacy_build_api: true)
    pilot(username: "***", skip_waiting_for_build_processing:true, ipa: ipa)
  end

  def beta_admin
    ipa = gym(scheme: "***", use_legacy_build_api: true)
    pilot(username: "***", skip_waiting_for_build_processing:true, ipa: ipa)
  end
  
  def beta_all
    ensure_git_branch
    sh "fastlane beta_client"
    sh "fastlane beta_admin"
    increment_build_number
    commit_version_bump
  end

  lane :beta do
    beta_all
  end

  lane :beta_client do
    beta_client
  end

  lane :beta_admin do
    beta_admin
  end

  lane :increment do
    increment_build_number
  end
  
  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "***"

apple_id "***" # Your Apple email address

team_id "***"  # Developer Portal Team ID
itc_team_id "***"

for_platform :ios do
    for_lane :beta_admin do
        app_identifier "***"
    end
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| deliver             | 1.14.5  | ✅ Up-To-Date        |
| snapshot            | 1.16.2  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.3.2   | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| pilot               | 1.11.1  | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.106.2 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| io-console                | 0.4.6        |
</details>

*generated on:* **2016-10-31**
</details>

**Comment by hjanuschka** [comment]
have you read the error message, telling you what todo for 2fa enabled accounts?

see here https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification for a detailed howto on using 2fa - even on CI

**Comment by suzhaev** [comment]
@hjanuschka yes, i did it before. After success auth and run fastlane i'we got an error

`[00:24:47]: Fixnum is not a String

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | cocoapods        | 1           |
| 3    | gym              | 16          |
| 💥    | pilot            | 0           |
+------+------------------+-------------+

[00:24:47]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Match - 2FA - Fixnum is not a String
   https://github.com/fastlane/fastlane/issues/6768 [open] 5 💬
   a day ago

➡️  --decimals flag type must be Fixnum not String
   https://github.com/fastlane/fastlane/issues/4881 [closed] 1 💬
   27 May 2016

➡️  [slather action] Fix --decimals flag type
   https://github.com/fastlane/fastlane/pull/4880 [closed] 3 💬
   27 May 2016

and 1 more at: https://github.com/fastlane/fastlane/search?q=Fixnum%20is%20not%20a%20String&type=Issues&utf8=✓
/Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie.rb:373:in `value=': [!] Fixnum is not a String (TypeError)
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie.rb:680:in `block in yaml_initialize'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie.rb:674:in `each'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie.rb:674:in `yaml_initialize'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie.rb:667:in `init_with'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:382:in `init_with'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:374:in `revive'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:208:in `visit_Psych_Nodes_Mapping'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:330:in `block in register_empty'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:330:in `each'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:330:in `register_empty'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:141:in `visit_Psych_Nodes_Sequence'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/visitor.rb:16:in `visit'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/visitors/to_ruby.rb:32:in `accept'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych/nodes/node.rb:38:in `to_ruby'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/psych-2.1.1/lib/psych.rb:255:in `load'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie_jar/yaml_saver.rb:24:in `load'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:325:in `block in load'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `open'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/http-cookie-1.0.3/lib/http/cookie_jar.rb:324:in `load'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/two_step_client.rb:95:in `load_session_from_env'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:250:in `send_shared_login_request'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/tunes/tunes_client.rb:160:in `send_login_request'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:411:in `do_login'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:230:in `login'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:90:in `login'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/spaceship-0.36.2/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pilot-1.11.1/lib/pilot/manager.rb:15:in `login'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pilot-1.11.1/lib/pilot/manager.rb:8:in `start'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/pilot-1.11.1/lib/pilot/build_manager.rb:4:in `upload'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/actions/pilot.rb:18:in `run'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `chdir'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `execute_action'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:20:in `beta_client'
	from Fastfile:41:in `block (2 levels) in parsing_binding'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/lane.rb:33:in `call'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `execute'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:52:in `block (2 levels) in run'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:246:in `run'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:23:in `start'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/***/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.106.2/bin/fastlane:5:in `<top (required)>'
	from /Users/***/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/***/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'`

**Comment by akaralar** [comment]
I'm having trouble with a 2FA protected bitbucket account as well. Reading and writing to remote both via https and ssh works ok with the match repo when I do `git clone`, but fastlane can not authenticate. The interesting thing is I was able to authenticate a few hours ago.

**Comment by TKBurner** [comment]
Hi @suzhaev Check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification for steps of setting this up. Thanks!

**Comment by suzhaev** [comment]
@TKBurner already read it

>  hjanuschka commented 20 hours ago
> have you read the error message, telling you what todo for 2fa enabled accounts?
> 
> see here https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification for a detailed howto on using 2fa - even on CI
> @suzhaev
>      
> suzhaev commented 19 hours ago • edited
> @hjanuschka yes, i did it before. After success auth and run fastlane i've got an error

**Comment by TKBurner** [comment]
@suzhaev Can you share your current full input and output? It looks like this is a different issue now that 2-factor is setup.

**Comment by KrauseFx** [comment]
Hey everyone, _fastlane_ now fully supports both two-factor and two-step verification 👋 

Please make sure to update to the latest version of _fastlane_ by running 

```
fastlane update_fastlane
```

If you use a `Gemfile`, just run `bundle update`

### On your computer 🚀
To use _fastlane_ with two-factor, just run _fastlane_ as you usually would. You'll be asked for the verification method, and a 4 or 6 digits pin. Everything will just work out of the box 📦 

### On your continuous integration system 💻 
Check out the [official two-factor docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth) for more information on how to setup two-step on CI system. You'll have to authenticate on your local machine to get a session cookie, which you then transfer to your CI.

----

If you have any issues setting this up, please submit [a new issue](https://github.com/fastlane/fastlane/issues/new) so we can help you get up and running 👍
