### ISSUE TITLE
Match can't find foreign branch when shallow clone option used

### ISSUE THREAD

**Issue by xNekOIx** [fastlane/fastlane#6806]
fastlane 1.106.2

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Generate new signings using Match in the not default branch.
`bundle exec match appstore --git_branch not_default_branch`

Install them with `--shallow_clone` option.
`bundle exec match appstore --git_branch not_default_branch --readonly --shallow_clone --verbose`

Installation faults with the following stack trace:
```
bundler: failed to load command: match (/Users/some-user/.rbenv/versions/2.3.0/bin/match)
FastlaneCore::Interface::FastlaneCrash: [!] No code signing identity found and can not create a new one because you enabled `readonly`
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/interface.rb:132:in `crash!'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/runner.rb:72:in `fetch_certificate'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/runner.rb:30:in `run'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/commands_generator.rb:119:in `run'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/commands_generator.rb:12:in `start'
  /Users/some-user/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/match-0.10.0/bin/match:6:in `<top (required)>'
  /Users/some-user/.rbenv/versions/2.3.0/bin/match:23:in `load'
  /Users/some-user/.rbenv/versions/2.3.0/bin/match:23:in `<top (required)>'
```

When do that without `--shallow_clone` installation succeeds.

**Comment by xNekOIx** [comment]
Suppose issue is in this line
https://github.com/fastlane/fastlane/blob/1.106.2/match/lib/match/git_helper.rb#L126

When shallow clone repo `git branch --list origin/#{branch.shellescape} --no-color -r` returns nothing.

Related info:
http://stackoverflow.com/questions/23708231/git-shallow-clone-clone-depth-misses-remote-branches

**Comment by TKBurner** [comment]
@xNekOIx Hope you are doing well! Any chance you want to submit a PR to fix this? We'd be really interested. Thanks!

**Comment by xNekOIx** [comment]
@TKBurner I'd glad to. but have no idea how to fix it so far. 😿

**Comment by xNekOIx** [comment]
don't think it has been resolved. nothing has changed in the mentioned line since then (checked latest 2.3.1).

**Comment by loiclec** [comment]
Hi all! 

As far as I can tell, building on @xNekOIx’ suggestion:
The repo is cloned with this line:
https://github.com/fastlane/fastlane/blob/1.106.2/match/lib/match/git_helper.rb#L8
which only clones one branch if the shallow option (`--depth`) is specified. 

Therefore this line:
https://github.com/fastlane/fastlane/blob/1.106.2/match/lib/match/git_helper.rb#L26
won't be able to checkout the branch we want.

It seems like this could be fixed by either 
- adding `--no-single-branch` to the initial `clone` command
- cloning and checking out the correct branch directly by adding `--branch xxxx` to the `clone` command

Right now, I don't really have the time (or knowledge) to setup fastlane for development, otherwise I would happily test it and send a PR 😞

**Comment by xNekOIx** [comment]
@loiclec you are right. missed this. will try to prepare a PR. 
will add `--no-single-branch` to `--depth 1`.
