### ISSUE TITLE
Strange issues on latest version

### ISSUE THREAD

**Issue by revile** [fastlane/fastlane#681]
I'm getting some pretty cryptic errors when trying to build on the latest version.

```
[11:08:36]: Could not find action or lane 'options'. Check out the README for more details: https://github.com/KrauseFx/fastlane

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | clean_build_artifacts               | 0           |
| 4    | xcode_select                        | 0           |
| 5    | sigh                                | 10          |
| 6    | git_branch                          | 0           |
| 7    | get_build_number                    | 3           |
| 8    | increment_build_number              | 0           |
| 9    | generate_changelog                  | 0           |
| 10   | gym                                 | 111         |
+------+-------------------------------------+-------------+

[11:08:36]: fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:117:in `try_switch_to_lane': Could not find action or lane 'options'. Check out the README for more details: https://github.com/KrauseFx/fastlane (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:129:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/fast_file.rb:124:in `method_missing'
	from (eval):136:in `block (3 levels) in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:65:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:65:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:61:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:61:in `rescue in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.1/bin/fastlane:142:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'
```

The lane in question is here:
```
lane :buildUat do |options|

    xcode_select "/Applications/Xcode.app"

    sigh(adhoc: true, app_identifier: "blah.blah")

    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]

    branch = git_branch[/(?:.*\/)?([\w-]*)/, 1]
    increment_build_number(build_number: "#{get_build_number}.#{options[:build_number]}-#{branch}")

    generate_changelog(previous_commit: "#{options[:previous_commit]}")

    gym(
      workspace: "App.xcworkspace",
      configuration: "Beta",
      scheme: "App",
      silent: true,
      clean: true
    )

  end
```

It seems to fail right at the end, it has successfully completed gym, and there are no further instructions.  Any help would be appreciated.

**Comment by KrauseFx** [comment]
Do you still run into this error? I just tried and it's working fine locally.

**Comment by povi** [comment]
Running into same issue when using with gym(use_legacy_build_api: true):

[17:40:45]: Could not find action or lane 'tests_file_path'. Check out the README for more details: https://github.com/KrauseFx/fastlane

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 16          |
| 4    | increment_build_number              | 1           |
| 5    | sigh                                | 12          |
| 6    | gym                                 | 119         |
+------+-------------------------------------+-------------+

[17:40:46]: fastlane finished with errors
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`
👍  This makes resolving issues much easier and helps improving fastlane
🔒  The reports might contain personal data, but will be stored securely on getsentry.com
✨  Once crash reporting is enabled, you have much cleaner output when something goes wrong
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/runner.rb:117:in `try_switch_to_lane': Could not find action or lane 'tests_file_path'. Check out the README for more details: https://github.com/KrauseFx/fastlane (RuntimeError)
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:46:in `block (2 levels) in parsing_binding'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/lane.rb:36:in `call'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/runner.rb:46:in `execute'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/bin/fastlane:152:in `run'
	from /Users/povi/.rvm/gems/ruby-2.2.3/gems/fastlane-1.37.0/bin/fastlane:158:in `<top (required)>'
	from /Users/povi/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/povi/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/povi/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/povi/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

**Comment by KrauseFx** [comment]
@povi Please share your complete `Fastfile`, you have an error there.

**Comment by ohwutup** [comment]
Going to close this issue for now as there has not been any activity in some time. Please feel free to reopen it if you are running into the same issue on up-to-date versions! :rabbit:
