### ISSUE TITLE
is it possible to supply a file to the notes field in app_review_information of deliver?

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#6811]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is it possible to set notes in the app_review_information hash of deliver to a file say with File.read('file.txt')?  Most examples shown show in line text.
```ruby
app_review_information({
  first_name: "Felix",
  last_name: "Krause",
  phone_number: "123123",
  email_address: "github@krausefx.com",
  demo_user: "demoUser",
  demo_password: "demoPass",
  notes: "such notes, very text"
})
```
##### Complete output when running fastlane, including the stack trace and command used

```bash
[00:06:09]: [en-US]: You must detail what's new in this version in English (U.S.).
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
<details>
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |
| Git                 | git version 2.10.0                          |
| Installation Source | /Users/me/Software/ruby/bin/fastlane    |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-upload_symbols_to_new_relic | 0.1.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.0.0        |
| highline                                    | 1.7.8        |
| commander                                   | 4.4.0        |
| terminal-table                              | 1.4.5        |
| json                                        | 1.8.3        |
| multipart-post                              | 2.0.0        |
| faraday                                     | 0.9.2        |
| faraday_middleware                          | 0.10.0       |
| dotenv                                      | 2.1.1        |
| net-ssh                                     | 3.2.0        |
| net-sftp                                    | 2.1.2        |
| plist                                       | 3.1.0        |
| rubyzip                                     | 1.1.7        |
| security                                    | 0.1.3        |
| krausefx-shenzhen                           | 0.14.10      |
| slack-notifier                              | 1.5.1        |
| i18n                                        | 0.7.0        |
| thread_safe                                 | 0.3.5        |
| tzinfo                                      | 1.2.2        |
| activesupport                               | 4.2.7.1      |
| CFPropertyList                              | 2.3.3        |
| claide                                      | 1.0.1        |
| colored                                     | 1.2          |
| nanaimo                                     | 0.1.2        |
| xcodeproj                                   | 1.4.0        |
| rouge                                       | 1.11.1       |
| xcpretty                                    | 0.2.4        |
| terminal-notifier                           | 1.7.1        |
| addressable                                 | 2.4.0        |
| credentials_manager                         | 0.16.2       |
| multi_xml                                   | 0.5.5        |
| unf_ext                                     | 0.0.7.2      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20161021 |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| fastimage                                   | 1.6.8        |
| xcode-install                               | 2.0.8        |
| word_wrap                                   | 1.0.0        |
| multi_json                                  | 1.12.1       |
| babosa                                      | 1.0.2        |
| excon                                       | 0.54.0       |
| gh_inspector                                | 1.0.2        |
| fastlane_core                               | 0.53.0       |
| mini_magick                                 | 4.5.1        |
| xcpretty-travis-formatter                   | 0.0.4        |
| uber                                        | 0.0.15       |
| representable                               | 2.3.0        |
| retriable                                   | 2.1.0        |
| mime-types-data                             | 3.2016.0521  |
| mime-types                                  | 3.1          |
| hurley                                      | 0.2          |
| little-plugger                              | 1.1.4        |
| logging                                     | 2.1.0        |
| jwt                                         | 1.5.6        |
| memoist                                     | 0.15.0       |
| os                                          | 0.9.6        |
| signet                                      | 0.7.3        |
| googleauth                                  | 0.5.1        |
| httpclient                                  | 2.8.2.4      |
| google-api-client                           | 0.9.19       |
| io-console                                  | 0.4.5        |
| bundler                                     | 1.13.6       |
| fastlane-plugin-upload_symbols_to_new_relic | 0.1.1        |
</details>

*generated on:* **2016-11-01**
</details>

**Comment by johndolljr** [comment]
notes: File.read("./fastlane/notes.txt")

path is relative to where you execute fastlane from.

**Comment by TKBurner** [comment]
@lakamsani Did you get up and running? Thanks!

**Comment by lakamsani** [comment]
@johndolljr  thanks for that suggestion. I was trying relative path because that is how it works with crashlytics,  notes_path: File.expand_path("beta-release-notes.txt"), and  pilot changelog : File.read("tf-changelog.txt"). After the initial failure I tried with "./fastlane/notes.txt" and even direct notes string but they all failed as ITC seems to be in a inconsistent state for that app. So I released it manually. I plan to update my app later this week and will try it with "./fastlane/notes.txt" the first time and see how that goes.

**Comment by lakamsani** [comment]
Just tried notes: File.read("./fastlane/notes.txt") and it does not work. 

```bash
% cat ./fastlane/tf-release-notes.txt  # works fine

However running a lane that contains this, just fails with error that it cant access the file. 

app_review_information: {
# other info
notes: File.read("./fastlane/tf-release-notes.txt") 
}

Fastfile:201:in `read': [!] No such file or directory @ rb_sysopen - ./fastlane/tf-release-notes.txt (Errno::ENOENT)
	from Fastfile:201:in `block (2 levels) in parsing_binding'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:69:in `block (2 levels) in run'
	from /Users/me/Software/ruby/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/me/Software/ruby/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/me/Software/ruby/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/me/Software/ruby/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/me/Software/ruby/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:257:in `run'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:31:in `start'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/me/Software/ruby/gems/fastlane-1.107.0/bin/fastlane:5:in `<top (required)>'
	from /Users/me/Software/ruby/bin/fastlane:23:in `load'
	from /Users/me/Software/ruby/bin/fastlane:23:in `<main>'
```
