### ISSUE TITLE
What is the pricing scheme for Fastlane ?

### ISSUE THREAD

**Issue by shrutigoyal7032** [fastlane/fastlane#6813]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
[INSERT OUTPUT HERE]
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

[INSERT OUTPUT HERE]

**Comment by milch** [comment]
`fastlane` is free and Open Source (under the [MIT license](https://tldrlegal.com/license/mit-license)). You can keep using fastlane forever and never pay a dime. 

Let me know if that answers your question!
