### ISSUE TITLE
Match stuck cloning repo

### ISSUE THREAD

**Issue by lucabartoletti** [fastlane/fastlane#6815]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If i run any match command it get stuck trying to clone the signing repo.

For example if I run `match nuke development --verbose`

```
INFO [2016-11-01 11:02:20.44]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:<redacted>/ios-signing.git' '/var/folders/pq/3lpdj9_55dq_9yp_r36ch3980000gn/T/d20161101-1549-p9pe0'
INFO [2016-11-01 11:02:20.45]: ▸ Cloning into '/var/folders/pq/3lpdj9_55dq_9yp_r36ch3980000gn/T/d20161101-1549-p9pe0'...
INFO [2016-11-01 11:02:21.53]: ▸ remote: Counting objects: 120918, done.
```

This is what i see when i kill match

```
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/command_executor.rb:65:in `wait': Interrupt
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/command_executor.rb:65:in `ensure in block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/command_executor.rb:65:in `block in execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/command_executor.rb:46:in `spawn'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/command_executor.rb:46:in `execute'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/git_helper.rb:14:in `clone'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/nuke.rb:14:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/commands_generator.rb:112:in `block (3 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/commands_generator.rb:119:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.10.0/lib/match/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/match-0.10.0/bin/match:6:in `<top (required)>'
	from /usr/local/bin/match:23:in `load'
	from /usr/local/bin/match:23:in `<main>'
```

If open another terminal and i run the same clone command than it works

It was working in the past. It stoped after the update

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.1  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version |
| -------------------------- | ------- |
| did_you_mean               | 1.0.2   |
| highline                   | 1.7.8   |
| commander                  | 4.4.0   |
| terminal-table             | 1.4.5   |
| json                       | 1.8.3   |
| multipart-post             | 2.0.0   |
| faraday                    | 0.9.2   |
| faraday_middleware         | 0.10.0  |
| dotenv                     | 2.1.1   |
| net-ssh                    | 3.2.0   |
| net-sftp                   | 2.1.2   |
| plist                      | 3.1.0   |
| security                   | 0.1.3   |
| krausefx-shenzhen          | 0.14.10 |
| slack-notifier             | 1.5.1   |
| rouge                      | 1.11.1  |
| xcpretty                   | 0.2.4   |
| terminal-notifier          | 1.7.1   |
| addressable                | 2.4.0   |
| word_wrap                  | 1.0.0   |
| multi_json                 | 1.12.1  |
| colored                    | 1.2     |
| babosa                     | 1.0.2   |
| rubyzip                    | 1.1.7   |
| gh_inspector               | 1.0.2   |
| credentials_manager        | 0.16.2  |
| fastlane_core              | 0.53.0  |
| multi_xml                  | 0.5.5   |
| http-cookie                | 1.0.3   |
| faraday-cookie_jar         | 0.0.6   |
| fastimage                  | 1.6.8   |
| mini_magick                | 4.5.1   |
| xcpretty-travis-formatter  | 0.0.4   |
| i18n                       | 0.7.0   |
| thread_safe                | 0.3.5   |
| tzinfo                     | 1.2.2   |
| minitest                   | 5.9.1   |
| activesupport              | 4.2.7.1 |
| io-console                 | 0.4.6   |
| excon                      | 0.54.0  |
| CFPropertyList             | 2.3.3   |
| claide                     | 1.0.1   |
| nanaimo                    | 0.1.2   |
| xcodeproj                  | 1.4.0   |
| bundler                    | 1.13.6  |
| fastlane-plugin-versioning | 0.2.4   |
</details>

*generated on:* **2016-11-01**
</details>

**Comment by hjanuschka** [comment]
can you run the clone manually?

```bash
git clone 'git@github.com:<redacted>/ios-signing.git' '/tmp/sample_clone'
```

to see if there is any git error behind it.

**Comment by lucabartoletti** [comment]
Yes, As i wrote in the description above, If open another terminal and i run the same clone command than it works.

I can see this problem on my laptop and on the CI machine. Same behaviour

**Comment by lucabartoletti** [comment]
Update now it started to work again. But is still stuck for a long time (an hour) on 

`remote: Counting objects: 120918, done.`

If I run the git clone command manually it works smoothly

**Comment by hjanuschka** [comment]
hmmm can you run it with `--verbose` - i guess there are many files in it. and the decryption takes time ?

**Comment by zwang** [comment]
I have the same problem. Just set up the a new git repo and stuck at the cloning steps like forever. The git repo is self hosted behind a VPN. Here are the logs:

`➜  Pla git:(task/automate-build) ✗ sudo match development --verbose
Password:
INFO [2016-11-11 22:47:56.82]: Successfully loaded '/Users/zhao/workspace/Pla/fastlane/Matchfile' 📄

+----------------------+----------------------------------------------------------------------------------------------------+
|                                        Detected Values from './fastlane/Matchfile'                                        |
+----------------------+----------------------------------------------------------------------------------------------------+
| git_url              | https://git.pla.net/pla/iOSCertificates.git                                              |
| type                 | development                                                                                        |
| app_identifier       | ["com.plaapp.Pla", "com.plaapp.Pla.Dev", "com.plaapp.Pla.Debug", "com.plaapp.stage"] |
| username             | dev@plaapp.com                                                                                  |
+----------------------+----------------------------------------------------------------------------------------------------+


+-----------------------+--------------------------------------------------------------------------+
|                                     Summary for match 0.11.0                                     |
+-----------------------+--------------------------------------------------------------------------+
| verbose               | true                                                                     |
| git_url               | https://git.pla.net/pla/iOSCertificates.git                    |
| type                  | development                                                              |
| app_identifier        | ["com.plaapp.Pla", "com.plaapp.Pla.Dev", "com.plaapp.Pla.... |
| username              | dev@plaapp.com                                                        |
| git_branch            | master                                                                   |
| keychain_name         | login.keychain                                                           |
| readonly              | false                                                                    |
| force                 | false                                                                    |
| skip_confirmation     | false                                                                    |
| shallow_clone         | false                                                                    |
| force_for_new_devices | false                                                                    |
| skip_docs             | false                                                                    |
+-----------------------+--------------------------------------------------------------------------+

INFO [2016-11-11 22:47:56.82]: Cloning remote git repo...
INFO [2016-11-11 22:47:56.82]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://git.pla.net/pla/iOSCertificates.git' '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20161111-17055-1x0l82e'
INFO [2016-11-11 22:47:56.83]: ▸ Cloning into '/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/d20161111-17055-1x0l82e'...
INFO [2016-11-11 22:47:57.34]: ▸ The authenticity of host 'git.pla.net (10.0.129.153)' can't be established.
INFO [2016-11-11 22:47:57.34]: ▸ ECDSA key fingerprint is SHA256:FQZILJ6imB+I8aSduPTaJGSGo7tQnb+VA7yz3UkeRsA.`

**Comment by hjanuschka** [comment]
@zwang  but normal cloning works ? 

`git clone  https://git.pla.net/pla/iOSCertificates.git  test`

**Comment by zwang** [comment]
@hjanuschka  yes. Sorry. Forgot to mention this.  It works normally, took a couple of seconds. I have tried most of the solutions I can find in this repository, but has no luck..

**Comment by hjanuschka** [comment]
tbh. i have no clou, do you have any chances using ssh instead of https?
the stacktrace clearly says that it hangs during clone.

**Comment by zwang** [comment]
I tried SSH before. Having the same issue. I am wondering if it is because the git repo is behind the VPN..

**Comment by TKBurner** [comment]
@lucabartoletti Was your repo behind a network as well or is it hosted on Github? Thanks!
