### ISSUE TITLE
What is  Artifactory - Artifact properties hash

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#6816]
@koglinjg I was interested in using the Artifactory plugin but I'm unclear how to set properties.  The documentation just says "Artifact properties hash" - could you explain what this means.  What hash algorithm do I use etc?

**Comment by koglinjg** [comment]
See [fastlane/lib/fastlane/actions/artifactory.rb#L19](https://github.com/fastlane/fastlane/blob/a094c54e152dc1a2e960e1290c696007d5442a48/fastlane/lib/fastlane/actions/artifactory.rb#L19)

This is just calling to `Artifactory::Resource::Artifact#upload`. See https://github.com/chef/artifactory-client/blob/v2.5.0/lib/artifactory/resources/artifact.rb#L514

An example in fastlane would be:
```
artifactory(
            username: "username",
            password: "password",
            endpoint: "https://artifactory.example.com/artifactory/",
            file: "example.ipa",                                # File to upload
            repo: "mobile_artifacts",                           # Artifactory repo
            repo_path: "/ios/appname/example-major.minor.ipa"   # Path to place the artifact including its filename
            properties: {
              status: "DEV",
              rating: 5,
              branch: "master"
            }
          )
```

@jeeftor Let me know if that works for you.

**Comment by TKBurner** [comment]
@koglinjg Thanks so much for helping 👍 👍 👍

**Comment by jeeftor** [comment]
Thanks. Does it also support API key based logins?

**Comment by TKBurner** [comment]
@jeeftor I don't think it does at current implementation. Thanks!

**Comment by koglinjg** [comment]
Actually it does. See: https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-Authentication

Where you would supply your password, you can instead use your API key.

**Comment by jeeftor** [comment]
Thanks guys!!!
