### ISSUE TITLE
Pilot : submit for external review crashes when it's currently in review or already approved

### ISSUE THREAD

**Issue by gcamp** [fastlane/fastlane#6818]
I'm using `Pilot::BuildManager.new.distribute(config)` directly in my Fastfile. Not sure if this is bad practice but it was my best way to reuse code from Pilot and not re-implement everything myself using spaceship. 

There's a problem with how pilot is handling the submit for external review part. Here is the current timeline of events : 
- Submit a beta for a new build train. 
  - The call for `client.submit_testflight_build_for_review!` is working. 
  - However the call `build_train.update_testing_status!` throws an error "This build could not be used for external testing because the build is not approved." This is a valid error, however it should probably be catched in some way and shown to the user as a warning.
- The previous beta that was sent to review is either currently in review or approved.
  - The call for `client.submit_testflight_build_for_review!` is not working and instead a error is thrown "ITC.response.error.INVALID_REQUEST" (can't submit a build to review if it's already in review)
  - The call `build_train.update_testing_status!` is not called at all since an error is thrown before. 

Proposed solution : 
- Add attributes in Spaceship::Tunes::Build for `betaState` and `internalState`. Current values I've seen are "inactive", "submitForReview", "waiting", "active".  I'm missing the in review and approved state. 
- pilot should take into account this value to either not send the build to review, or not send to beta testers if the build is not approved. 

I can do a pull request. Just wanted to discuss it first.

**Comment by TKBurner** [comment]
@gcamp I think these make sense as changes. Can you submit a lightweight PR to address this first in spaceship? And then ask in that PR about Pilot? We really appreciate you working with us 👍 Thanks!

**Comment by joeydong** [comment]
I've also run into this workflow problem. The beta app review can take 24-48 hours so it's unreasonable to keep `pilot` running in the background like we currently do while waiting for the build to be processed.

I agree once we have the right information coming from Spaceship, we can provide a cleaner exit code for `pilot`. Then it will be up to the user to run `pilot distribute` once they get an email notification that their build has been approved by beta app review.

On the other hand, nothing is really stopping us from keeping `pilot` running for a day or so while waiting for the review so maybe we can make this an advanced feature for those who are running `pilot` on a build machine that stays connected all the time anyway.

**Comment by gcamp** [comment]
Still on my todo list, sorry for the delay

**Comment by BroderickLee** [comment]
When will this issue be resolved? I really hope it can be fixed as soon as possible. Thanks!!!

**Comment by cpk1** [comment]
I've got something that lets pilot upload and submit to external testflight, and before attempting to turn on the external distribution will check the status of the build to see if it is possible or not. This will prevent the "This build could not be used for external testing because the build is not approved." error.
