### ISSUE TITLE
numberOfLines and textBelowImage ? 

### ISSUE THREAD

**Issue by claesjacobsson** [fastlane/fastlane#6824]
It would be cool if we could choose the number of lines for the text + if the text could be placed below the image.

**Comment by claesjacobsson** [comment]
Another possibility could be a fixed font size option, which would adjust the number of rows automatically.

**Comment by TKBurner** [comment]
@claesjacobsson Thanks for the ideas! We'll leave this open as a feature request 👍

**Comment by claesjacobsson** [comment]
Great! Haven't done any Ruby dev before, or I would take a stab at it. Perhaps this is when I learn Ruby ;-)

**Comment by TKBurner** [comment]
@claesjacobsson That'd be really cool 👍 👍
