### ISSUE TITLE
Inappropriate message when using fastlane_version action with bundler

### ISSUE THREAD

**Issue by Onejjy** [fastlane/fastlane#6828]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using `fastlane_version` action in a bundler environment (with `bundle exec fastlane`), the update message is not appropriate: 

```
$ bundle exec fastlane my_lane_farmer
-------------------------------------------------
--- Step: Verifying required fastlane version ---
-------------------------------------------------
[!] The Fastfile requires a fastlane version of >= 8.8.8. You are on 1.101.0. Please update using `sudo gem update fastlane`
```

It should ask the user to do a `bundle update fastlane`.

**Comment by TKBurner** [comment]
@Onejjy Can you share your fastfile? Thanks!

**Comment by Onejjy** [comment]
Sure, here is a sample `FastFile`: 
```
fastlane_version "8.8.8"

lane :my_lane_farmer do
    say "Hi there !"
end
```

Actually, I know that version `8.8.8` is irrelevant. It's just to demonstrate the issue.

**Comment by KrauseFx** [comment]
Thanks for submitting the PR, we replied 👍
