### ISSUE TITLE
Got Code signing is required for product type 'Application' in SDK 'iOS 10.1

### ISSUE THREAD

**Issue by LanfordCai** [fastlane/fastlane#6832]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi, I tried to build my app by gym, but I got `“Code signing is required for product type 'Application' in SDK 'iOS 10.1’”` and process failed. I have read #6519 , but the solution not work for me.

Here is some information:

1. My Xcode version is 8.1
2. I hope the build process can be done without adding account to Xcode Accounts(**I want to do everything without open Xcode**), so `Automatically manage signing` has been unchecked. 
3. I didn't use `match`.
4. My lane is:

    ```ruby
      lane :fastlane_try do
        cert
        sigh
        update_project_team(
          path: "FastTry.xcodeproj",
          teamid: "XXXXXXXXX"
        )
        update_project_provisioning(
          xcodeproj: "FastTry.xcodeproj",
          target_filter: ".*FastTry.*",
          build_configuration: "Release",
        )
        gym(
          clean: true,
          codesigning_identity: "iOS Distribution: XXXXXX"
        )
      end
    ```
    I tried to use `update_project_team` and `update_project_provisioning` to set the provisioning profiles of my project, after the fastlane process, `Sign(Release)` part of Xcode is like this:
      
    ![Imgur](http://i.imgur.com/6err3Ae.png)

5. fastlane process failed at step gym, the output is:

    ```
    ▸ Cleaning FastTry/FastTry [Debug]
    ▸ Check Dependencies
    ▸ Clean Succeeded
    ▸ Building FastTry/FastTry [Release]
    ▸ Check Dependencies
    
    ❌  Code signing is required for product type 'Application' in SDK 'iOS 10.1'
    
    
    ** ARCHIVE FAILED **
    
    
    The following build commands failed:
    Check dependencies
    (1 failure)
    [17:19:07]: Exit status: 65
    [17:19:07]: 📋  For a more detailed error log, check the full log at:
    [17:19:07]: 📋  /Users/XXXXXX/Library/Logs/gym/FastTry-FastTry.log
    [17:19:07]: Variable Dump:
    [17:19:07]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios fastlane_try", :CERT_FILE_PATH=>"#{CERT_FILE_PATH}", :CERT_CERTIFICATE_ID=>"#{CERT_CERTIFICATE_ID}", :SIGH_PROFILE_PATH=>"#{SIGH_PROFILE_PATH}", :SIGH_PROFILE_PATHS=>["#{SIGH_PROFILE_PATHS}"], :SIGH_UDID=>"#{SIGH_UDID}", :SIGH_PROFILE_TYPE=>"app-store"}
    [17:19:07]: Error building the application - see the log above
    
    +------+-------------------------------------+-------------+
    |                     fastlane summary                     |
    +------+-------------------------------------+-------------+
    | Step | Action                              | Time (in s) |
    +------+-------------------------------------+-------------+
    | 1    | Verifying required fastlane version | 0           |
    | 2    | default_platform                    | 0           |
    | 3    | cert                                | 8           |
    | 4    | sigh                                | 13          |
    | 5    | update_project_team                 | 0           |
    | 6    | update_project_provisioning         | 0           |
    | 💥    | gym                                 | 2           |
    +------+-------------------------------------+-------------+
    ```

6. If I open Xcode, and tap `Provisioning Profile` in `Signing(Release)`, choose `com.lanford.FastTry AppStore`(the option isn't changed), the `Signing(Release)` part would be like this:
![Imgur](http://i.imgur.com/PwPWL3I.png) -- Signing Certificate changed from `None` to `iPhone Distribution`, and then, gym would works fine, the app can be build successfully.

7. **If I keep `Signing` parts are none, and I can build the app by xcodebuild successfully, All in all, I hope I can do it by gym, so could you tell me what should I do?(no Xcode Accounts, without open Xcode, build app with provisioning profiles managed by sigh and certificates generated by cert directly), thank you!**

##### Complete output when running fastlane, including the stack trace and command used

output is the 5th part of Issue Description, the command is `fastlane ios fastlane_try`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                  |
| ------------------- | ------------------------------------------------------ |
| OS                  | 10.11.6                                                |
| Ruby                | 2.3.1                                                  |
| Bundler?            | true                                                   |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/            |
| Xcode Version       | 8.1                                                    |
| Git                 | git version 2.9.3 (Apple Git-75)                       |
| Installation Source | /Users/GavinFlying/.rvm/rubies/ruby-2.3.1/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                             |
| Ruby Lib Dir        | /Users/GavinFlying/.rvm/rubies/ruby-2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                             |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :fastlane_try do
    cert
    sigh
    update_project_team(
      path: "FastTry.xcodeproj",
      teamid: "XXXXXXXXX"
    )
    update_project_provisioning(
      xcodeproj: "FastTry.xcodeproj",
      target_filter: ".*FastTry.*",
      build_configuration: "Release",
    )
    gym(
      clean: true,
      codesigning_identity: "iOS Distribution: XXXXXX"
    )
  end

  lane :fast_test do
    puts("#{ENV}")
    #update_info_plist(
    #  plist_path: "FastTry/Info.plist",
    #  app_identifier: "com.lanford.iOSclub",
    #  display_name: "iOSclub"
    #)
    update_project_team(
      path: "FastTry.xcodeproj",
      teamid: "Y2VDUB37Q5"
    )
    update_project_provisioning(
      xcodeproj: "FastTry.xcodeproj",
      target_filter: ".*FastTry.*",
      build_configuration: "Release",
    #  certificate: "2MEN5Y44Y6.cer"
    )
    #update_provisioning_profile_specifier
    gym(
      #clean: true,
      codesigning_identity: "iOS Distribution: Linfeng Cai"
    )
    #update_app_group_identifiers(
    #  entitlements_file: "MoreSpaces/MoreSpaces.entitlements",
    #  app_group_identifiers: ["group.com.lanford.iOSclub"]
    #)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "FastTry") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "FastTry") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.lanford.FastTry" # The bundle identifier of your app
apple_id "gavinflying@126.com" # Your Apple email address

team_id "Y2VDUB37Q5"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| pilot               | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status       |
| ----------------------------------------------------- | ------- | ------------------- |
| fastlane-plugin-update_project_codesigning            | 0.1.2   | ✅ Up-To-Date        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.1.0   | 🚫 Update availaible |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| executable-hooks                                      | 1.3.2        |
| bundler-unload                                        | 1.0.2        |
| rubygems-bundler                                      | 1.4.4        |
| bundler                                               | 1.13.6       |
| CFPropertyList                                        | 2.3.3        |
| i18n                                                  | 0.7.0        |
| json                                                  | 1.8.3        |
| minitest                                              | 5.9.1        |
| thread_safe                                           | 0.3.5        |
| tzinfo                                                | 1.2.2        |
| activesupport                                         | 4.2.7.1      |
| addressable                                           | 2.4.0        |
| babosa                                                | 1.0.2        |
| colored                                               | 1.2          |
| highline                                              | 1.7.8        |
| commander                                             | 4.4.0        |
| security                                              | 0.1.3        |
| credentials_manager                                   | 0.16.2       |
| excon                                                 | 0.54.0       |
| gh_inspector                                          | 1.0.2        |
| multi_json                                            | 1.12.1       |
| plist                                                 | 3.1.0        |
| rubyzip                                               | 1.1.7        |
| terminal-table                                        | 1.4.5        |
| fastlane_core                                         | 0.53.0       |
| multipart-post                                        | 2.0.0        |
| faraday                                               | 0.9.2        |
| unf_ext                                               | 0.0.7.2      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20161021 |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| faraday_middleware                                    | 0.10.0       |
| fastimage                                             | 1.6.8        |
| multi_xml                                             | 0.5.5        |
| claide                                                | 1.0.1        |
| dotenv                                                | 2.1.1        |
| mini_magick                                           | 4.5.1        |
| rouge                                                 | 1.11.1       |
| xcpretty                                              | 0.2.4        |
| net-ssh                                               | 3.2.0        |
| net-sftp                                              | 2.1.2        |
| krausefx-shenzhen                                     | 0.14.10      |
| slack-notifier                                        | 1.5.1        |
| xcpretty-travis-formatter                             | 0.0.4        |
| jwt                                                   | 1.5.6        |
| little-plugger                                        | 1.1.4        |
| logging                                               | 2.1.0        |
| memoist                                               | 0.15.0       |
| os                                                    | 0.9.6        |
| signet                                                | 0.7.3        |
| googleauth                                            | 0.5.1        |
| httpclient                                            | 2.8.2.4      |
| hurley                                                | 0.2          |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| uber                                                  | 0.0.15       |
| representable                                         | 2.3.0        |
| retriable                                             | 2.1.0        |
| google-api-client                                     | 0.9.19       |
| terminal-notifier                                     | 1.7.1        |
| word_wrap                                             | 1.0.0        |
| xcode-install                                         | 2.0.8        |
| nanaimo                                               | 0.1.4        |
| xcodeproj                                             | 1.4.0        |
| fastlane-plugin-update_project_codesigning            | 0.1.2        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.1.0        |
</details>

*generated on:* **2016-11-02**
</details>

**Comment by hjanuschka** [comment]
please read the codesigning guide - about how to sign on xcode8.

also the action `update_project_provisioning` is not working for xcode8 and above as another variable is used inside the project file.

please see - and maybe +1 this PR - wich adds a param `provisioning_profile_specifier` to set the new variable inside the `update_project_provisioning` action.

https://github.com/fastlane/fastlane/pull/6561


also you can look at this comment: https://github.com/fastlane/fastlane/issues/6533#issuecomment-253746551  (and that issue in general) on how to use the https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning to toggle auto, manual signing

**Comment by fhperuchi** [comment]
Thank you @hjanuschka ! It solved my problem. :+1: 

I had to implement this way:

  ```
update_project_provisioning(
        xcodeproj: 'build_files/ios/project/Cavadinha.xcodeproj',
        profile: 'app/env/match_AppStore_comCavadinha.mobileprovision',
        target_filter: '.*',
        build_configuration: '.*'
    )

    gym(
        project: 'build_files/ios/project/Cavadinha.xcodeproj',
        scheme: 'Cavadinha'
    )

    testflight
```

**Comment by TKBurner** [comment]
@hjanuschka As always thanks so much for helping out 👍 Hope you are having a great week!

**Comment by wolffan** [comment]
Just a note, that solution won't work on complex projects.
Projects with cocoapods or with multiple targets will need a more fine grained solution (this means using some Build setting magic checked in the project or modified on the fly).

Related: https://github.com/fastlane/fastlane/issues/6519

**Comment by KrauseFx** [comment]
Hey everyone, with newer versions of fastlane we'll now also show the last few lines of the raw build output, this might look like the following

```
[14:02:53]: ▸ === BUILD TARGET wwdcfamily OF PROJECT wwdcfamily WITH CONFIGURATION Release ===
[14:02:53]: ▸ Check dependencies
[14:02:53]: ▸ No iOS profile matching 'N8X438SEU2/match AppStore family.wwdc.app' found:  Xcode couldn't find a profile matching 'N8X438SEU2/match AppStore family.wwdc.app'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
[14:02:53]: ▸ Code signing is required for product type 'Application' in SDK 'iOS 10.3'
[14:02:53]: 
[14:02:53]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[14:02:53]: 📋  For the complete and more detailed error log, check the full log at:
[14:02:53]: 📋  /tmp/circle-artifacts.3CI68wp/gym/wwdcfamily-wwdcfamily.log
```

Note how the following line tells you the exact problem:

```
No iOS profile matching 'N8X438SEU2/match AppStore family.wwdc.app' found:  Xcode couldn't find a profile matching 'N8X438SEU2/match AppStore family.wwdc.app'. Install the profile
```

This should make it possible for you to debug the issue and work out a fix 👍  We'll continue working on improving the messaging of fastlane 🚀
