### ISSUE TITLE
gym fails with undefined method `each_with_object' for nil:NilClass

### ISSUE THREAD

**Issue by pxm8436** [fastlane/fastlane#6834]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
/Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:116:in `keys_to_symbols': [!] undefined method `each_with_object' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:133:in `read_export_options'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:154:in `config_content'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:19:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/runner.rb:118:in `package_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/runner.rb:20:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.11.3/lib/gym/manager.rb:14:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/actions/gym.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:36:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:52:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:246:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/commands_generator.rb:23:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.106.2/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

etails><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.5                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.5 (15F34)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.3.2   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.2  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.0        |
| activesupport             | 4.2.6        |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.1.0        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.2        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.1        |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.12.5       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.0        |
| google-api-client         | 0.9.9        |
</details>

*generated on:* **2016-11-02**
</details>

**Comment by TKBurner** [comment]
Hi @pxm8436 Thanks for reaching out. It looks like you might have better luck if you manage your ruby version through something like rvm. That way you can use 2.3.2 for fastlane. Let me know how it goes!

**Comment by ollieatkinson** [comment]
I am getting the same error, 

```
Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:116:in `keys_to_symbols': [!] undefined method `each_with_object' for nil:NilClass (NoMethodError)
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:133:in `read_export_options'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:154:in `config_content'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/generators/package_command_generator_xcode7.rb:19:in `generate'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/runner.rb:118:in `package_app'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/runner.rb:20:in `run'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/gym-1.11.3/lib/gym/manager.rb:14:in `work'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/fastlane-1.106.2/lib/fastlane/actions/gym.rb:24:in `run'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/fastlane-1.106.2/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/fastlane-1.106.2/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/fastlane-1.106.2/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `chdir'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/fastlane-1.106.2/lib/fastlane/runner.rb:186:in `execute_action'
	from /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/gems/fastlane-1.106.2/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                   |
| ------------------- | ------------------------------------------------------- |
| OS                  | 10.11.6                                                 |
| Ruby                | 2.0.0                                                   |
| Bundler?            | true                                                    |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version       | 8.0                                                     |
| Git                 | git version 2.9.3                                       |
| Installation Source | /Users/oat01/.rvm/gems/ruby-2.0.0-p648@ssn/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                              |
| Ruby Lib Dir        | /Users/oat01/.rvm/rubies/ruby-2.0.0-p648/lib            |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                               |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Do not track our usage
opt_out_usage

default_platform :ios

platform :ios do

  lane :test do
    
    Dir.mktmpdir do |tmp|
    
      scan(
        scheme:            "UK", 
        workspace:         "#{name}.xcworkspace", 
        code_coverage:     true,
        device:            "iPhone 6 (9.3)",
        derived_data_path: tmp
      )
    
    end
    
  end
  
  lane :build do |options|
    
    target        = "UK"
    configuration = options[:configuration] || "Live"
    
    export_name = "#{name}_#{target}_#{configuration}"
    
    Dir.mktmpdir do |tmp|
    
      gym(
        scheme:           target,
        workspace:        "#{name}.xcworkspace",
        configuration:    "#{configuration}",
        export_options:   "CI/exportOptions#{configuration}.plist",
        output_directory: "artifacts",
        archive_path:     "artifacts/#{export_name}-Enterprise.xcarchive",
        output_name:      "#{export_name}_Enterprise",
        xcargs:           "-derivedDataPath #{tmp}"
      )
    
    end
    
  end

end

def name
  'SkySports'
end
```

</details>

**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| spaceship           | 0.36.2  | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| deliver             | 1.14.5  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| pem                 | 1.3.2   | 🚫 Update availaible |
| pilot               | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| fastlane            | 1.106.2 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| rake                      | 11.3.0       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.4.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.53.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.0       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.0        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.1        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.0.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.2        |
| molinillo                 | 0.4.5        |
| xcodeproj                 | 1.3.1        |
| cocoapods                 | 1.0.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.19       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.8        |
| mustache                  | 0.99.8       |
| open4                     | 1.3.4        |
| redcarpet                 | 3.3.4        |
| sass                      | 3.4.22       |
| sqlite3                   | 1.3.11       |
| liferaft                  | 0.0.4        |
| xcinvoke                  | 0.2.1        |
| jazzy                     | 0.7.2        |
</details>


*generated on:* **2016-11-03**

**Comment by ollieatkinson** [comment]
I had the same error before, make sure you have the export options plist available.

**Comment by pxm8436** [comment]
@ollieatkinson Thanks a lot. I had the same problem. Added the export options plist back in the right location. Closing this.

**Comment by pxm8436** [comment]
Fixed. export options plist was not in the right location.
