### ISSUE TITLE
How to specify working directory for git commands

### ISSUE THREAD

**Issue by stark525** [fastlane/fastlane#6842]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have a Fastfile in the root of my project.  I'm trying to run `fastlane` and execute git Actions from this directory, using my machine and a Jenkins OSX build slave.  However, it bombs out because it isn't being run in the directory where I call `fastlane`.  How am I meant to specify the git directory to run my Source Control Actions?  

_As an aside, I find myself adding `#{pwd}` to the beginning of most of my Actions with a path. I suspect solving this would also allow me to drop that. I'm doing it wrong but don't know the alternative_ 😖

`fastlane push_tag framework:MyFrameworkName`

##### Complete output when running fastlane, including the stack trace and command used

```
[20:10:30]: -----------------------------
[20:10:30]: --- Step: import_from_git ---
[20:10:30]: -----------------------------
[20:10:30]: Cloning remote git repo...
[20:10:30]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@private-git-url.com:ios/ios-fastlane.git' '/var/folders/87/033ng7911cl0y1drgxxj3czc00019_/T/fl_clone20161102-10174-eeaizg/ios-fastlane.git' --depth 1 -n --branch starktest
[20:10:30]: ▸ Cloning into '/var/folders/87/033ng7911cl0y1drgxxj3czc00019_/T/fl_clone20161102-10174-eeaizg/ios-fastlane.git'...
[20:10:30]: ▸ Warning: Permanently added 'private-git-url.com,172.1.2.3' (ECDSA) to the list of known hosts.
[20:10:31]: $ cd '/var/folders/87/033ng7911cl0y1drgxxj3czc00019_/T/fl_clone20161102-10174-eeaizg/ios-fastlane.git' && git checkout starktest 'fastlane/Fastfile'
[20:10:31]: $ cd '/var/folders/87/033ng7911cl0y1drgxxj3czc00019_/T/fl_clone20161102-10174-eeaizg/ios-fastlane.git' && git checkout starktest 'fastlane/actions'
[20:10:31]: ▸ error: pathspec 'fastlane/actions' did not match any file(s) known to git.
[20:10:31]: Clearing the git repo...
[20:10:31]: $ rm -rf '/var/folders/87/033ng7911cl0y1drgxxj3czc00019_/T/fl_clone20161102-10174-eeaizg'
[20:10:31]: Driving the lane 'push_tag' 🚀
[20:10:31]: ----------------------------------
[20:10:31]: --- Step: get_info_plist_value ---
[20:10:31]: ----------------------------------
[20:10:31]: -------------------------
[20:10:31]: --- Step: add_git_tag ---
[20:10:31]: -------------------------
[20:10:31]: Adding git tag '6' 🎯.
[20:10:31]: $ git tag -am 6\ \(fastlane\) '6'
[20:10:31]: ▸ fatal: Not a git repository (or any of the parent directories): .git
[20:10:31]: Variable Dump:
[20:10:31]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"push_tag", :GET_INFO_PLIST_VALUE_CUSTOM_VALUE=>"6"}
[20:10:31]: Exit status of command 'git tag -am 6\ \(fastlane\) '6'' was 128 instead of 0.
fatal: Not a git repository (or any of the parent directories): .git


+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | import_from_git      | 1           |
| 2    | get_info_plist_value | 0           |
| 💥    | add_git_tag          | 0           |
+------+----------------------+-------------+

[20:10:31]: fastlane finished with errors

[!] Exit status of command 'git tag -am 6\ \(fastlane\) '6'' was 128 instead of 0.
fatal: Not a git repository (or any of the parent directories): .git
```

> Note: I am storing my Fastfile in ios-fastlane.git so my main Fastfile for testing on a branch is:
```
import_from_git(url: "git@private-git-url.com:ios/ios-fastlane.git",
  branch: "starktest"
)
```
(I don't think this matters, but explains some of the output)

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                               |
| ------------------- | --------------------------------------------------- |
| OS                  | 10.12.1                                             |
| Ruby                | 2.3.1                                               |
| Bundler?            | false                                               |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version       | 8.1                                                 |
| Git                 | git version 2.4.6                                   |
| Installation Source | /Users/danstark/.rvm/rubies/ruby-2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2657)                          |
| Ruby Lib Dir        | /Users/danstark/.rvm/rubies/ruby-2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                         |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
import_from_git(url: "git@private-git-url.com:ios/ios-fastlane.git",
branch: "starktest"
)
```
</details>

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| deliver             | 1.14.5  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.3.2   | 🚫 Update availaible |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.106.2 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| did_you_mean              | 1.0.0       |
| executable-hooks          | 1.3.2       |
| bundler-unload            | 1.0.2       |
| rubygems-bundler          | 1.4.4       |
| bundler                   | 1.13.6      |
| io-console                | 0.4.5       |
| highline                  | 1.7.8       |
| commander                 | 4.4.0       |
| terminal-table            | 1.4.5       |
| json                      | 1.8.3       |
| multipart-post            | 2.0.0       |
| faraday                   | 0.9.2       |
| faraday_middleware        | 0.10.0      |
| dotenv                    | 2.1.1       |
| net-ssh                   | 3.2.0       |
| net-sftp                  | 2.1.2       |
| plist                     | 3.1.0       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| krausefx-shenzhen         | 0.14.10     |
| slack-notifier            | 1.5.1       |
| rouge                     | 1.11.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.7.1       |
| claide                    | 1.0.1       |
| colored                   | 1.2         |
| credentials_manager       | 0.16.2      |
| multi_xml                 | 0.5.5       |
| http-cookie               | 1.0.3       |
| faraday-cookie_jar        | 0.0.6       |
| xcode-install             | 2.0.8       |
| word_wrap                 | 1.0.0       |
| multi_json                | 1.12.1      |
| babosa                    | 1.0.2       |
| excon                     | 0.54.0      |
| gh_inspector              | 1.0.2       |
| fastlane_core             | 0.53.0      |
| fastimage                 | 1.6.8       |
| mini_magick               | 4.5.1       |
| xcpretty-travis-formatter | 0.0.4       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| logging                   | 2.1.0       |
| jwt                       | 1.5.6       |
| memoist                   | 0.15.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.3       |
| googleauth                | 0.5.1       |
| httpclient                | 2.8.2.4     |
| google-api-client         | 0.9.19      |
| i18n                      | 0.7.0       |
| thread_safe               | 0.3.5       |
| tzinfo                    | 1.2.2       |
| activesupport             | 4.2.7.1     |
| CFPropertyList            | 2.3.3       |
| nanaimo                   | 0.2.0       |
| xcodeproj                 | 1.4.1       |
</details>

*generated on:* **2016-11-02**
</details>

## Lane from Fastfile
```
lane :push_tag do |options|  
  framework_version = get_info_plist_value(
    path: "#{pwd}/#{options[:framework]}/Info.plist",
    key: "CFBundleVersion"
  )

  add_git_tag(
    tag: "#{framework_version}"
  )

  push_to_git_remote(
    tags: true
  )
end
```

**Comment by TKBurner** [comment]
@stark525 Hope you are doing well! What directory are you running this from? It needs to be inside of a git repo itself. Thanks!

**Comment by stark525** [comment]
Hi @TKBurner thanks for your response!

I'm running this from within a git repo. My workaround for the time being (which works) looks like this:

```
  pwd = ENV['PWD']

  sh "cd #{pwd}"
  sh "git tag #{framework_version}"
  sh "git push --all"
  sh "git push origin #{framework_version}"

#  add_git_tag(
#    tag: "#{framework_version}"
#  )
#  push_to_git_remote(
#    tags: true
#  )
```

I feel like there must be a way to tell Fastlane to use the PWD for all actions/lanes.  I'm not sure how to debug what the `add_git_tag` and `push_to_git_remote` actions think the working dir is.  I suspect it's `/fastlane`, though.
