### ISSUE TITLE
Supply: Google Api Error: developerDdaNotAccepted: This developer accounts owner has not accepted the latest Developer Distribution Agreement.

### ISSUE THREAD

**Issue by nicbarker** [fastlane/fastlane#6843]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to run `supply`, I get the following error:
`[!] Google Api Error: developerDdaNotAccepted: This developer accounts owner has not accepted the latest Developer Distribution Agreement.`  
I've not only accepted all the agreements, but even tried making a brand new, fresh google developer account (just to make 100% sure there wasn't some kind of screwy "parent" account going on like I've referenced in some issues). Followed all the setup instructions listed on the supply page to generate the JSON key.  
  
Any ideas?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
/project/android(master)$ supply init --verbose
DEBUG [2016-11-03 14:41:32.20]: Fetching a new access token from Google...
/Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Google Api Error: developerDdaNotAccepted: This developer accounts owner has not accepted the latest Developer Distribution Agreement. (FastlaneCore::Interface::FastlaneError)
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/lib/supply/client.rb:334:in `rescue in call_google_api'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/lib/supply/client.rb:332:in `call_google_api'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/lib/supply/client.rb:81:in `begin_edit'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/lib/supply/setup.rb:9:in `perform_download'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/lib/supply/commands_generator.rb:51:in `block (2 levels) in run'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/lib/supply/commands_generator.rb:57:in `run'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/lib/supply/commands_generator.rb:15:in `start'
    from /Users/hidden/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/supply-0.7.1/bin/supply:6:in `<top (required)>'
    from /Users/hidden/.rbenv/versions/2.2.4/bin/supply:23:in `load'
    from /Users/hidden/.rbenv/versions/2.2.4/bin/supply:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                               |
| ------------------- | --------------------------------------------------- |
| OS                  | 10.11.6                                             |
| Ruby                | 2.2.4                                               |
| Bundler?            | false                                               |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version       | 8.1                                                 |
| Git                 | git version 2.9.3 (Apple Git-75)                    |
| Installation Source | /Users/hidden/.rbenv/versions/2.2.4/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                          |
| Ruby Lib Dir        | /Users/hidden/.rbenv/versions/2.2.4/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                         |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.2"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./Google Play Android Developer-b441281d1fa4.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.project" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| spaceship           | 0.36.2  | ✅ Up-To-Date        |
| deliver             | 1.14.5  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.3.2   | 🚫 Update availaible |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | ✅ Up-To-Date        |
| gym                 | 1.11.3  | ✅ Up-To-Date        |
| pilot               | 1.11.2  | ✅ Up-To-Date        |
| scan                | 0.13.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.106.2 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.1        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.4.0        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.53.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.5       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
</details>

*generated on:* **2016-11-03**
</details>

**Comment by TKBurner** [comment]
@nicbarker Can you login and accept the developer terms on Google Play? That looks like the problem here. Thanks!

**Comment by nicbarker** [comment]
Hi @tkburner, unfortunately I've already tried that. On my primary account I've been presented with and accepted the developer terms, only to get this message. After trying many different things, I finally resorted to making (and paying for) a brand new developer account. Logged in, accepted the developer license, still get this problem. Unsure really what to do at this point.

**Comment by TKBurner** [comment]
Hi @nicbarker Thanks for letting me know. This isn't expected, can you provide exact repro steps on a blank android project? Thanks!
