### ISSUE TITLE
Waiting for iTunes Connect to process the new build...

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#685]
Everything works, build went through, TestFlight sent me an email. But Fastlane keeps telling me that it's waiting for iTC to process the new build... I don't think this ever worked for me to be honest. Have you ever seen this go through? I think Fastlane is broken and cannot figure out the status of test flight submission. I really wish I could see :beers: in the end of submission. :+1:

**Comment by KrauseFx** [comment]
I'm pretty sure that's an iTunes Connect issue. I assume you have at least one build stuck in `Processing`, `Invalid` or similar? Could you send a screenshot of how your build list looks like?

**Comment by pronebird** [comment]
You're right. There are some of builds stuck forever, but new ones are getting regularly delivered.

**Comment by sethhoward** [comment]
Having the same issue. I have never had a successful run and this creates havoc on our Jenkins jobs. It always gets stuck here, running indefinitely or crashes. Is there a way to successfully complete the job after iTunes has received the upload or when it has returned the build # etc?

generally with:
[22:52:36]: getaddrinfo: nodename nor servname provided, or not known

[22:52:36]: fastlane finished with errors
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: nodename nor servname provided, or not known (Faraday::ConnectionFailed)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:877:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1126:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/client.rb:243:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/client.rb:175:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/client.rb:175:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/client.rb:242:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/client.rb:218:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/tunes/tunes_client.rb:442:in `build_trains'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/tunes/build_train.rb:47:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.12.0/lib/spaceship/tunes/application.rb:195:in `build_trains'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.3.0/lib/pilot/build_manager.rb:81:in `wait_for_processing_build'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-0.3.0/lib/pilot/build_manager.rb:21:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/actions/pilot.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:47:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/bin/fastlane:136:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.32.4/bin/fastlane:142:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by jkyin** [comment]
![qq20151017-0](https://cloud.githubusercontent.com/assets/1644903/10557310/7024d4ac-74d9-11e5-9192-5f8d3a019708.png)

I don't have any build, but it still show this issue. Please help.

**Comment by Paulo-Branco** [comment]
Are there any news on this ? I'm currently experiencing the same problem.

**Comment by pronebird** [comment]
I am currently seeing long long delays in TestFlight distribution and I think it's simply overloaded. While this error doesn't occur to me anymore I receive tons of other mysterious errors from iTC.

**Comment by theMeatloaf** [comment]
I am also experiencing this.  The build does complete processing in iTC, but it never gets set as the current build and gets distributed.  Fastlane also keeps printing `Waiting for iTunes Connect to process the new build` indefinitely

**Comment by Paulo-Branco** [comment]
The funny thing is that if you launch watchbuild on a separate terminal it'll report the progess correctly, which leads me to conclude that something must be wrong with pilot.

**Comment by theMeatloaf** [comment]
Yeah like I said, it definitely gets done processing, but pilot doesn't pick up on the change and set it as the current version. I did notice that one of our builds from November randomly never finished processing, and I believe @KrauseFx mentioned that could be a cause up above.  Pilot must only check for any builds still in processing instead of the specific one you just submitted.

**Comment by theMeatloaf** [comment]
After looking into it further...my suspicions are correct:
https://github.com/fastlane/pilot/blob/master/lib/pilot/build_manager.rb#L74

pilot only looks for no more occurrences of processing builds....so if you have an old build that never completed processing this can happen...

I've contacted apple about removing that dead build for me.  Is there any way to check for this particular build instead of any processing build?  I dont know for sure but it sounds like a limitation of iTC access...

**Comment by vittoriom** [comment]
Same problem here :( some very old builds are stuck on Processing, but new ones are delivered correctly. I have to kill the Jenkins job every morning.

**Comment by kikolobo** [comment]
Same issue here.... Finishes correctly and delivers correctly, but pilot doesn't pick it up an reports it as a failed build.

**Comment by theMeatloaf** [comment]
@kikolobo I believe the problem you are experiencing is related to this PR: https://github.com/fastlane/spaceship/pull/235

If your build is getting through processing and being distributed to testers you are fine, just wait for the next version spaceship and the error should be gone.  

This issue (#685) is related to builds never being distributed to testers, even though they are finished processing and the "Waiting for iTunes Connect to process the new build" shows forever.

If thats the case the fix is to contact apple support about removing old stale builds from ITC that never finished processing...Since fastlane only checks for zero processing builds to determine if it is done.

**Comment by theMeatloaf** [comment]
actually it looks as though this logic has been changed to look for the specific build you just submitted instead of zero processing builds.... @KrauseFx I believe this issue can be closed

**Comment by kikolobo** [comment]
@theMeatloaf That's the case! So il wait for the updated version. I appreciated!

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
