### ISSUE TITLE
Apple 302 redirect causing failure

### ISSUE THREAD

**Issue by RyanCopley** [fastlane/fastlane#6859]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] sudo gem update fastlane
sudo ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

302 apple error. I dunno what it is but it's stopping my build from happening ¯\_(ツ)_/¯ 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[22:03:15]: Driving the lane 'store' 🚀
[22:03:15]: ---------------------------------------------------------------------
[22:03:15]: --- Step: cd .. && bash script/clone-switcher.sh "" ---
[22:03:15]: ---------------------------------------------------------------------
[22:03:15]: $ cd .. && bash script/clone-switcher.sh ""
[22:03:15]: ▸ Need to sync
[22:03:15]: ▸ Moving stub file:  LaunchScreen.storyboard
[22:03:15]: ▸ Moving stub file:  LaunchScreen.xcassets
[22:03:15]: ▸ Moving stub file:  ADBMobileConfig.json
[22:03:15]: ▸ Moving stub file:  Info.plist
[22:03:15]: ▸ Scanning ...  airplane_active, airplane, bottom_fade, Brand Assets, close_white, CompanyBanner, down-arrow, fade, gradient, headerbg, icon-feedback-negative, icon-feedback-neutral, icon-feedback-positive, key_gray, key_white, left_arrow_grey, left_arrow_white, logo_opaque, logo_translucent, menu_white, right_arrow_grey, right_arrow_white, save_gray_outline, save_white_fill, save_white_outline, search_white, settings_white, settings, share_gray, share_white, spinner, SubscribeArt, thumb_card_default_image, up-arrow ... found
[22:03:17]: ---------------------------------------------------
[22:03:17]: --- Step: cd .. && bash script/get-bundle-id.sh ---
[22:03:17]: ---------------------------------------------------
[22:03:17]: $ cd .. && bash script/get-bundle-id.sh
[22:03:17]: ------------------
[22:03:17]: --- Step: sigh ---
[22:03:17]: ------------------

+-------------------------------------+-------------------------+
|                    Summary for sigh 1.11.2                    |
+-------------------------------------+-------------------------+
| username                            |        |
| team_id                             |              |
| app_identifier                      | |
| adhoc                               | false                   |
| development                         | false                   |
| skip_install                        | false                   |
| force                               | false                   |
| ignore_profiles_with_different_name | false                   |
| skip_fetch_profiles                 | false                   |
| skip_certificate_verification       | false                   |
+-------------------------------------+-------------------------+

[22:03:17]: Starting login with user '@.com'
[22:03:18]: Successfully logged in
[22:03:18]: Fetching profiles...
[22:03:36]: Variable Dump:
[22:03:36]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"store"}
[22:03:36]: Apple 302 detected

+------+---------------------------------------------------------+-------------+
|                               fastlane summary                               |
+------+---------------------------------------------------------+-------------+
| Step | Action                                                  | Time (in s) |
+------+---------------------------------------------------------+-------------+
| 1    | cd .. && bash script/clone-switcher.sh "-" | 1           |
| 2    | cd .. && bash script/get-bundle-id.sh                   | 0           |
| 💥    | sigh                                                    | 19          |
+------+---------------------------------------------------------+-------------+

[22:03:36]: fastlane finished with errors

```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                               |
| ------------------- | --------------------------------------------------- |
| OS                  | 10.12                                               |
| Ruby                | 2.3.1                                               |
| Bundler?            | false                                               |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/         |
| Xcode Version       | 8.1                                                 |
| Git                 | git version 2.9.3 (Apple Git-75)                    |
| Installation Source | /Users/ryancopley/.rvm/gems/ruby-2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                             |
| Ruby Lib Dir        | /Users/ryancopley/.rvm/rubies/ruby-2.3.1/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                         |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

lane :store do
	puts "Current directory: #{File.expand_path(File.dirname(File.dirname(__FILE__)))}"
	puts ENV["bonnie_flavor"]
	if ENV["bonnie_flavor"].length == 0 
		abort(1)
	end

	sh("cd .. && bash script/clone-switcher.sh \"" + ENV["bonnie_flavor"] + "\"")
	bundleId = sh("cd .. && bash script/get-bundle-id.sh").strip!
	if bundleId.length == 0 
		abort(1)
	end
	sigh(	
			username: ".com",
			team_id: "",
			app_identifier: bundleId
	)
	gym(	
			scheme: "Bonnie",
			workspace: "Bonnie.xcworkspace",
			configuration: "Release"
	)
	deliver(
			username: "@.com",
			force: true,
			skip_screenshots: true,
			automatic_release: true,
			submit_for_review: true
	)
end

lane :enterprise do
	puts "Current directory: #{File.expand_path(File.dirname(File.dirname(__FILE__)))}"
	puts ENV["bonnie_flavor"]
	if ENV["bonnie_flavor"].length == 0 
		abort(1)
	end

	sh("cd .. && bash script/clone-switcher.sh \"" + ENV["bonnie_flavor"] + "\"")
	bundleId = sh("cd .. && bash script/get-bundle-id.sh").strip!
	if bundleId.length == 0 
		abort(1)
	end
	cert(	
			username:"@.com", 
			team_id: ""
	)
	gym(	
			scheme:"Bonnie - Enterprise",
			workspace: "Bonnie.xcworkspace",
			configuration: "Enterprise",
			xcargs: "PROVISIONING_PROFILE_SPECIFIER='Enterprise Wildcard 110116'",
			use_legacy_build_api: true,
			codesigning_identity: "iPhone Distribution: Co., Inc.",
			output_name: "Bonnie-" + ENV["BUILD_NUMBER"]
	)

	sh("cd .. && bash script/enterprise-distribute.sh \"" + ENV["bonnie_flavor"] + "\" \"" + bundleId + "\"");
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.0  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.1.4        |
| xcodeproj                 | 1.4.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.53.0       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
</details>

*generated on:* **2016-11-03**
</details>```

**Comment by mkismy** [comment]
I'm getting the same problem on `Step: sigh`

**Comment by mdubs** [comment]
We were getting this issue but it has suddenly started working

**Comment by RyanCopley** [comment]
It appears to be working now, but more info on this error would be appreciated

**Comment by TKBurner** [comment]
@RyanCopley @mdubs Thanks for following up. This looks like an issue on the endpoint side. I sent it out to the team to take a look to be sure. Thanks!
