### ISSUE TITLE
Is there a way to run multiple scheme from single config file? - SNAPSHOT

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#6860]
I have multiple targets for my app and I have single snapshot file. I have mentioned all the schemes there but it's taking only the very first scheme. Is there way to accomplish this? 

If it's not possible, please let me know how to run them all.

**Comment by KrauseFx** [comment]
You should use _fastlane_ with a `Fastfile` for this, you call _snapshot_ multiple times from there

**Comment by tringManoj** [comment]
I have single snapfile file. Can you tell me how to call snapshot multiple times? My single snap file takes only the first scheme bcaz the command is String not Array SCHEME. 
So can you tell me 
1) how to add multiple SCHEMES? on single file OR
2) Should I add multiple snapfiles OR
3) If should I call snapshot multiple times, plz advice me with the steps how to do this on fastlane file please.

**Comment by hjanuschka** [comment]
Fastfile:

```ruby
lane :snapshot_demo do
       snapshot(
            devices: ["iPhone6"],
            scheme: "scheme1"
       )
       snapshot(
            devices: ["iPhone6"],
            scheme: "scheme2"
       )
end

```

this will run snapshot 2 times with different schemes, be  sure to check the other options from your snapfile - and add them in fastfile

**Comment by tringManoj** [comment]
For snapfile and scanfiles I have "SNAPSHOT" & "SCAN" commands. Whats the
command  "FASTFILE" ?

R.Manoj
Sr.Software Developer - Mobile | tringapps research labs Pvt Ltd,
Unit 2-5 (Ground Floor), Zenith Building,
Ascendas IT Park, CSIR Road, Taramani,
Chennai 600 113, Tamil Nadu, India.
*E-Mail:* *manoj.r@tringapps.com <manoj.r@tringapps.com>*

**Comment by tringManoj** [comment]
cool. Got it working. No worries

R.Manoj
Sr.Software Developer - Mobile | tringapps research labs Pvt Ltd,
Unit 2-5 (Ground Floor), Zenith Building,
Ascendas IT Park, CSIR Road, Taramani,
Chennai 600 113, Tamil Nadu, India.
*E-Mail:* *manoj.r@tringapps.com <manoj.r@tringapps.com>*
