### ISSUE TITLE
Jenkins/Deliver: Operation timed out - connect(2)

### ISSUE THREAD

**Issue by mpateck** [fastlane/fastlane#6862]
Hi there, 

i hope you can help me out. 
Since my company introduced a new proxy, i had many problems getting my ci back to work.
Till now, everything works, except the deliver via my jenkins to itunesconnect.

I upgraded everything, set the proxy for gem, npm, git, itunestransporter.

This is what jenkins says after firing:

DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS='-t DAV' pilot upload --skip_submission -u 'MYID' --skip_waiting_for_build_processing true --verbose
INFO [2016-11-03 15:36:53.83]: Login to iTunes Connect (MYID)
Operation timed out - connect(2)
Operation timed out - connect(2)
Operation timed out - connect(2)
Operation timed out - connect(2)
Operation timed out - connect(2)

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Could not receive latest API key from iTunes Connect, this might be a server issue.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Could%20not%20receive%20latest%20API%20key%20from%20iTunes%20Connect,%20this%20might%20be%20a%20server%20issue.+repo:fastlane/fastlane
ERROR [2016-11-03 16:12:18.06]: [31mError finding relevant GitHub issues: Operation timed out - connect(2)[0m
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:339:in `rescue in itc_service_key': [31m[!] The request could not be completed because: (Spaceship::Client::AppleTimeoutError)
	Could not receive latest API key from iTunes Connect, this might be a server issue.[0m
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:316:in `itc_service_key'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:279:in `block in send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:445:in `block in send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:347:in `with_retry'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:444:in `send_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:385:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:278:in `send_shared_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/tunes/tunes_client.rb:160:in `send_login_request'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:411:in `do_login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:230:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/client.rb:90:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/spaceship-0.36.2/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.11.0/lib/pilot/manager.rb:15:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.11.0/lib/pilot/manager.rb:8:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.11.0/lib/pilot/build_manager.rb:4:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.11.0/lib/pilot/commands_generator.rb:59:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.11.0/lib/pilot/commands_generator.rb:135:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.11.0/lib/pilot/commands_generator.rb:15:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.11.0/bin/pilot:6:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'

Firing the cmd from a terminal works like a charm.
So it must be in combination with jenkins (or i missed setting the proxy somewhere).

Here's my env:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1004)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.36.2  | ✅ Up-To-Date  |
| deliver             | 1.14.5  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.2.1   | ✅ Up-To-Date  |
| gym                 | 1.11.3  | ✅ Up-To-Date  |
| pilot               | 1.11.2  | ✅ Up-To-Date  |
| scan                | 0.13.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.106.2 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded***

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| highline                  | 1.7.8   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| multipart-post            | 2.0.0   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.1.0   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.10 |
| slack-notifier            | 1.5.1   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| minitest                  | 5.8.3   |
| activesupport             | 4.2.5   |
| colored                   | 1.2     |
| claide                    | 0.9.1   |
| xcodeproj                 | 0.28.2  |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| addressable               | 2.3.7   |
| xcode-install             | 2.0.8   |
| word_wrap                 | 1.0.0   |
| multi_json                | 1.11.0  |
| commander                 | 4.4.0   |
| babosa                    | 1.0.2   |
| excon                     | 0.45.4  |
| gh_inspector              | 1.0.2   |
| credentials_manager       | 0.16.2  |
| fastlane_core             | 0.53.0  |
| bundler                   | 1.13.6  |
| multi_xml                 | 0.5.5   |
| unf_ext                   | 0.0.7.1 |
| unf                       | 0.1.4   |
| domain_name               | 0.5.25  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| mime-types                | 2.4.3   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| logging                   | 2.0.0   |
| jwt                       | 1.5.2   |
| memoist                   | 0.14.0  |
| signet                    | 0.7.0   |
| googleauth                | 0.5.0   |
| thor                      | 0.19.1  |
| httpclient                | 2.8.0   |
| google-api-client         | 0.9.8   |
</details>

*generated on:* **2016-11-03**
</details>

Thank you!

**Comment by hjanuschka** [comment]
maybe same as this: https://github.com/fastlane/fastlane/issues/6765
wich is not addressed in https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/client.rb#L109



how do you set your proxy? 


@KrauseFx @mfurtak  how proxy settings are handled inside spaceship right now?

**Comment by mpateck** [comment]
Hi @hjanuschka ,

there was only http_proxy set on the jenkins directory.
If fixed that and after a restart of the server everything worked fine.

Thank you very much!
