### ISSUE TITLE
Fastlane install fails

### ISSUE THREAD

**Issue by Urkman** [fastlane/fastlane#6863]
### New Issue Checklist

- [ ] Updated fastlane to the latest version

### Issue Description

I simply try to install fastlane

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

sudo gem install fastlane
Password:
Building native extensions.  This could take a while...
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    current directory: /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.2/ext/unf_ext
/Applications/MAMP/Library/bin/ruby -r ./siteconf20161104-37131-4cxk9m.rb extconf.rb
checking for main() in -lstdc++... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Applications/MAMP/Library/bin/$(RUBY_BASE_NAME)
	--with-static-libstdc++
	--without-static-libstdc++
	--with-stdc++lib
	--without-stdc++lib
/Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:765:in `try_func'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:997:in `block in have_library'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:942:in `block in checking_for'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:350:in `block (2 levels) in postpone'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:350:in `block in postpone'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:320:in `open'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:346:in `postpone'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:941:in `checking_for'
	from /Applications/MAMP/Library/lib/ruby/2.3.0/mkmf.rb:992:in `have_library'
	from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Applications/MAMP/Library/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-13/2.3.0-static/unf_ext-0.0.7.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/unf_ext-0.0.7.2 for inspection.
Results logged to /Applications/MAMP/Library/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-13/2.3.0-static/unf_ext-0.0.7.2/gem_make.out

**Comment by hjanuschka** [comment]
it seems - that you use the `ruby` from your `MAMP` installation.
can you post your `$PATH`

```
echo $PATH
```

do you use rbenv or rvm? - i think the path of rvm/rbenv should be prepended to $PATH so `gem` and ruby et-all will be used from there not from MAMP.

**Comment by Urkman** [comment]
Thanks... That was the case...
I resorted the PATH and everything works fine.
