### ISSUE TITLE
Adding Multiple device for snapshot

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#6865]
snapshot --scheme "somescheme" --devices (["iPad Pro (12.9 inch)", "iPhone 7 Plus"])

This is not working. Can you please help how to send the multiple device command for snapshot?

**Comment by hjanuschka** [comment]
i am not sure if it is possible to passthrough arrays via commandline flag.


you can set the `devices` inside your `Snapfile`

if you need to change them - via commandline.
i would preferr a ENV based solution like this.

```
devices(
    ENV['SNAPSHOT_DEVICES'].split(",")
)
```

and then running it with (in your case):

```
SNAPSHOT_DEVICES="iPad Pro (12.9 inch), iPhone 7 Plus" snapshot --scheme "somescheme"
```

let me know if this works for you

**Comment by tringManoj** [comment]
Thank you. I got it working by this command 

--devices "iPad Pro (12.9 inch), iPhone 7 Plus"

**Comment by hjanuschka** [comment]
ahh nice - arrays work too, thx for the info

**Comment by hjanuschka** [comment]
ahh nice - arrays work too, thx for the info

**Comment by hjanuschka** [comment]
ahh nice - arrays work too, thx for the info

**Comment by hjanuschka** [comment]
ahh nice - arrays work too, thx for the info

**Comment by hjanuschka** [comment]
ahh nice - arrays work too, thx for the info

**Comment by hjanuschka** [comment]
ahh nice - arrays work too, thx for the info

**Comment by hjanuschka** [comment]
ahh nice - arrays work too, thx for the info
