### ISSUE TITLE
Remove the defualt device name and launch option from screenshot

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#6867]
Why every screenshot name is appended with DEVICE NAME and LAUNCH Arguments? 

iPadPro(12.9inch)--animation NoAnimation-MyCustomName

I just want it to be named - "MyCustomName"

**Comment by tringManoj** [comment]
iPhone7Plus-MyCustomName.png . This how screenshot images are names. But I Don't want the Device Name which is appended before the image name. I just want it like MyCustomeName.png

**Comment by TKBurner** [comment]
@tringManoj Hi, right now it's not possible to config this. Let me know if you have any other questions :)
