### ISSUE TITLE
Invalid sticker pack: non-compliant or prerelease tools

### ISSUE THREAD

**Issue by tabrindle** [fastlane/fastlane#6873]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastfile:
```
  lane :appstore_profiles do
    match(type: 'appstore', app_identifier: "#{app_identifier}")
    match(type: 'appstore', app_identifier: "#{app_identifier}.MessagesExtension")
  end

  lane :build_release do
    appstore_profiles
    gym(
      configuration: "Release",
      output_name: "#{app_name}-release.ipa"
    )
  end

  lane :beta do
    build_release
    pilot
  end
```

Command:
`fastlane beta`

Results in:

Email form iTunes Connect:
_Invalid iMessage App - Your iMessage app contains an invalid sticker pack. The app may have been built or signed with non-compliant or prerelease tools. For more information, go to developer.apple.com._

Archiving with Xcode, then submitting through Xcode works fine. 

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |
| Git                 | git version 2.10.1                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.104.0"

default_platform :ios

app_name = "Shop"
app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

platform :ios do

  lane :development_profiles do
    match(type: 'development', app_identifier: "#{app_identifier}")
    match(type: 'development', app_identifier: "#{app_identifier}.MessagesExtension")
  end

  lane :appstore_profiles do
    match(type: 'appstore', app_identifier: "#{app_identifier}")
    match(type: 'appstore', app_identifier: "#{app_identifier}.MessagesExtension")
  end

  lane :profiles do
    development_profiles
    appstore_profiles
  end

  lane :build_development do
    development_profiles
    gym(
      configuration: "Debug",
      output_name: "#{app_name}-development.ipa"
    )
  end

  lane :build_release do
    appstore_profiles
    gym(
      configuration: "Release",
      output_name: "#{app_name}-release.ipa"
    )
  end

  lane :hockeyapp do |options|
    hockey(
      ipa: "../../builds/#{Time.now.strftime('%F')}/#{app_name}-#{(options[:release] ? "release" : "development")}.ipa",
      dsym: "../../builds/#{Time.now.strftime('%F')}/#{app_name}-#{(options[:release] ? "release" : "development")}.app.dSYM.zip",
      api_token: "2e2f1260692140dba94474a4b66e9a56",
      notes: "Build " + (ENV["BUILD_NUMBER"] ? ENV["BUILD_NUMBER"] + " " : "") + "From " + git_branch + " branch on " + Time.now.strftime('%F') + " at " + Time.now.strftime('%T'),
      notify: "0"
    )
  end

  lane :ci do
    build_development
    hockeyapp
  end

  lane :beta do
    build_release
    pilot
  end

  lane :release do
    deliver(
      ipa: "../../builds/#{Time.now.strftime('%F')}/#{app_name}-release.ipa",
      force: true,
      skip_metadata: true,
      skip_screenshots: true
    )
  end

  lane :screenshots do
    deliver(
      skip_binary_upload: true
    )
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.marketamerica.MAMobile"
apple_id "mobile@marketamerica.com"
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version      |
| ------------------- | ------------ |
| did_you_mean        | 1.0.0        |
| highline            | 1.7.8        |
| commander           | 4.4.0        |
| terminal-table      | 1.4.5        |
| json                | 1.8.3        |
| multipart-post      | 2.0.0        |
| faraday             | 0.9.2        |
| faraday_middleware  | 0.10.0       |
| dotenv              | 2.1.1        |
| net-ssh             | 3.2.0        |
| net-sftp            | 2.1.2        |
| plist               | 3.1.0        |
| rubyzip             | 1.1.7        |
| security            | 0.1.3        |
| krausefx-shenzhen   | 0.14.10      |
| slack-notifier      | 1.5.1        |
| i18n                | 0.7.0        |
| thread_safe         | 0.3.5        |
| tzinfo              | 1.2.2        |
| minitest            | 5.8.3        |
| activesupport       | 4.2.7.1      |
| colored             | 1.2          |
| claide              | 1.0.1        |
| xcodeproj           | 1.3.3        |
| rouge               | 1.11.1       |
| xcpretty            | 0.2.4        |
| terminal-notifier   | 1.7.1        |
| addressable         | 2.3.8        |
| xcode-install       | 2.0.7        |
| word_wrap           | 1.0.0        |
| multi_json          | 1.12.1       |
| babosa              | 1.0.2        |
| excon               | 0.54.0       |
| gh_inspector        | 1.0.2        |
| credentials_manager | 0.16.2       |
| fastlane_core       | 0.53.0       |
| bundler             | 1.13.6       |
| multi_xml           | 0.5.5        |
| unf_ext             | 0.0.7.2      |
| unf                 | 0.1.4        |
| domain_name         | 0.5.20160826 |
| http-cookie         | 1.0.3        |
| faraday-cookie_jar  | 0.0.6        |
| fastimage           | 1.6.8        |
| mini_magick         | 4.5.1        |
| uber                | 0.0.15       |
| representable       | 2.3.0        |
| retriable           | 2.1.0        |
| mime-types-data     | 3.2016.0521  |
| mime-types          | 3.1          |
| hurley              | 0.2          |
| little-plugger      | 1.1.4        |
| logging             | 2.1.0        |
| jwt                 | 1.5.6        |
| memoist             | 0.15.0       |
| os                  | 0.9.6        |
| signet              | 0.7.3        |
| googleauth          | 0.5.1        |
| httpclient          | 2.8.2.4      |
| google-api-client   | 0.9.19       |
| io-console          | 0.4.5        |
</details>

*generated on:* **2016-11-04**
</details>

**Comment by TKBurner** [comment]
@tabrindle Thanks for reaching out. Can you confirm if this happens on all projects or just one? Are you able to make this happen consistently? I've reached out to the core team to have them take a look. Thanks!

**Comment by hjanuschka** [comment]
please see the sample app - with a sticker-pack extension using fastlane 👍 

https://github.com/hjanuschka/sticker-pack-with-fastlane

be sure to not use `use_legacy_build_api`  - and also ensure that you remove the sim. frameworks with a custom script phase.

```bash
cd "${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/"
  if [[ -d "Frameworks" ]]; then
    rm -fr Frameworks
  fi
```

**Comment by tabrindle** [comment]
This happens consistently, on two (cordova) projects with the same configuration. Am going to try disabling `use_legacy_build_api`, sounds like that is the issue. I will reopen if this is not solved with your suggestions. Thank you @TKBurner and @hjanuschka.
