### ISSUE TITLE
UI Test output at snapshot command line?

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#6874]
This is not so much an issue.

But I am having difficulty getting a test to work with snapshot without failing.

Therefore I'm trying to add some kind of output which will show in the command line to try and determine where the problem occurs.

The line number isn't shown in the error.

I've tried NSLog and tried an assertion, but only failed assertions are shown.

Any suggestions?

**Comment by TKBurner** [comment]
@Jules2010 Have you tried adding --verbose to your run of snapshot? If you have Xcode open does your debug output appear in the console?  Thanks!

**Comment by menriquez** [comment]
you need to add a sleep() command after every button push

**Comment by Jules2010** [comment]
Yeah thanks, added more sleep intervals.
Just not always straight forward to figure out where the issue occurs when no line number is provided in the error.
I know this isn't an issue with snapshot.
Just hoping I could add more output to the command line instead.

**Comment by TKBurner** [comment]
@Jules2010 Thanks for the feedback. I added this to our documentation flag. Hope you have a great day!
