### ISSUE TITLE
cert supports path to custom keychain, but create_keychain does not

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/fastlane#6880]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
cert supports path to custom keychain, but create_keychain does not.
Use case is to create a temporary keychain in working directory by CI process. The working directory is always cleaned up, thus assuring maximum reproducibility and no dependency/interference with files in ~/Library/Keychains

Is it desirable to add the support for custom keychain path into create_keychain?

**Comment by hjanuschka** [comment]
@GoodMirek - i love the "maximum reproducibility" - see this PR: https://github.com/fastlane/fastlane/pull/6887 - maybe you +1 it for me.

**Comment by GoodMirek** [comment]
Solved via #6887, thanks!
