### ISSUE TITLE
Add 'force' option to create_keychain

### ISSUE THREAD

**Issue by GoodMirek** [fastlane/fastlane#6881]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Use case: for continuous integration, I prefer to create a new temporary keychain for every build to ensure maximum reproducibility. If the keychain already exists on the CI system it needs to be delete first, otherwise create_keychain fails. Would be helpful if there is 'force' option which would remove the existing keychain if exists and then create a new one.
Is it desirable to support the described option?
May I submit pull request with the change?

**Comment by hjanuschka** [comment]
i don't think a `force`  option is good in this case. i bet there are users out there accidentally deleting there `login` keychain.

cant you do something like.

```
if FileUtils.exists?("~/Libary/Keychains/my-keychain.keychain-db")
   FileUtils.rm_f("~/Libary/Keychains/my-keychain.keychain-db")
end
create_keychain(name: "my-kechain.keychain_db")
```

**Comment by GoodMirek** [comment]
Thanks for response. I will also need to remove the keychain from search list. 
I understand the good reason for not having the simple `force` option. Maybe if there was a special check to never delete login.keychain?

**Comment by hjanuschka** [comment]
i got you, but i still think there should be no "auto-delete if existing" in a `create`  function like this.
can't you just call `delete_keychain` before creating it? - if it fails handle the exception in a `rescue`

**Comment by GoodMirek** [comment]
Will try, thanks.

**Comment by KrauseFx** [comment]
Thanks for helping @hjanuschka 👍
