### ISSUE TITLE
Can't remove certificates

### ISSUE THREAD

**Issue by i-schuetz** [fastlane/fastlane#6883]
I'm troubleshooting some issues I'm having with match (not relevant for this question), with this: https://docs.fastlane.tools/codesigning/troubleshooting/ specifically the part to check that there's a private key for the certificate in my keychain. My problem: There are 3 development certificates with the same name / userId and no one has private key.

I think this may be related with the fact that I'm using other mac than the one where I generated the certificates. Though I believe to remember one of them was generated with the current one (with match). But in any case there are no private keys for any. Also, the other mac can't be used anymore.

In an effort to bring some clarity in the situation I decided to remove the certificates. I also removed one which was listed in developer portal, manually in one attempt, as well as using `nuke` in another. Everything cleared.

Then I ran `fastlane match`, and the 3 certificates came back. What do I have to do to remove them? I was about to create a certificate manually in the developer portal, but not sure this will work with match - can I force it then to use this certificate? What am I missing / what is the correct way to fix all this?

Thanks!

**Edit:** I deleted the contents of the repo and ran `fastlane match` again. Now I have 4 certificates (without private keys). I tried also installing manually the certificate, by cloning the repo and double-clicking it, but it won't let me - "the contents of this file cannot be retrieved". Is it because of the encryption? Tried decrypting with openssl but it doesn't work. What is also the password for the generated p12 file?

**Edit2:** Sorry, the certificates generated by match do have a private key (!) - I was looking in the general tab in keychain which doesn't associate the keys with the certificates.

**Comment by TKBurner** [comment]
@i-schuetz Thanks for reaching out. So are you still running into an issue? You should be able to delete the unused profiles without any issues. Thanks!

**Comment by i-schuetz** [comment]
@TKBurner It's solved, thanks!
