### ISSUE TITLE
Installing on Sierra

### ISSUE THREAD

**Issue by JulianKingman** [fastlane/fastlane#6888]
In order to install on Sierra (maybe El Capitan, too), you have to install it locally, as it won't install in root (you'll get an error about `usr/bin/commander`).

Here's the required command:
`sudo gem install -n /usr/local/bin pem`

I suggest adding it to the readme

**Comment by hjanuschka** [comment]
this is not really fastlane specific - this happend somwhere in el-capitan.
you can also add:

```
gem: -n/usr/local/bin
```

to your `~/.gemrc` file.
or the better use `rvm/rbenv` to manage your ruby versions - as the one that apple ships is pretty old and has a lot of issues (e.g: ssl)

**Comment by JulianKingman** [comment]
In any case, it's not an issue for me anymore since I managed to get it installed.
