### ISSUE TITLE
`encode': [31m[!] "\xE2" on US-ASCII[0m 

### ISSUE THREAD

**Issue by petitmat** [fastlane/fastlane#6891]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello, when I run Deliver I got this error. But I haven't it before and it worked properly. I am using a DeliverFile (because we use fastlane only for delivering our apps (hundreds every year) and we create it dynamically according the app we want to deliver).

Here is my DeliverFile :

app_identifier 'xxxxxxxxx'
username 'xxxxxxxxx'
skip_binary_upload true
screenshots_path '/my/path/to/screenshots'
app_version '2.0.0'
app_icon '/my/path/to/iTunesIcon.png'
submit_for_review false
force true
metadata_path '/my/path/to/metadata'
app_review_information(
 first_name: 'xxxxxxxxx',
 last_name: 'Le xxxxxxxxx',
 phone_number: '+xxxxxxxxx',
 demo_user: 'xxxxxxxxx',
 demo_password: 'xxxxxxxxx',
 notes: 'xxxxxxxxx',
 email_address: 'xxxxxxxxx')
automatic_release false
app_rating_config_path '/my/path/to/app_rating.json'

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[10:50:49]: Uploading metadata to iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mencode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)[0m
   https://github.com/fastlane/fastlane/issues/2034 [[32mclosed[0m] 2 💬
   22 Aug 2016

➡️  [33mError with posting data with 0x00FA character[0m
   https://github.com/fastlane/fastlane/issues/1967 [[32mclosed[0m] 27 💬
   5 weeks ago

/Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/base.rb:52:in `encode': [31m[!] "\xE2" on US-ASCII[0m (Encoding::InvalidByteSequenceError)
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/base.rb:52:in `to_json'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/base.rb:52:in `to_json'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:365:in `block (2 levels) in update_app_version!'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:374:in `block in run_request'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:388:in `block in build_request'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request.rb:26:in `block in create'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `tap'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/request.rb:25:in `create'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:384:in `build_request'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:370:in `run_request'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:445:in `block in send_request'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:347:in `with_retry'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:444:in `send_request'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/client.rb:385:in `request'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:363:in `block in update_app_version!'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:964:in `with_tunes_retry'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/tunes/tunes_client.rb:362:in `update_app_version!'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/spaceship-0.37.0/lib/spaceship/tunes/app_version.rb:299:in `save!'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.15.0/lib/deliver/upload_metadata.rb:58:in `upload'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.15.0/lib/deliver/runner.rb:58:in `upload_metadata'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.15.0/lib/deliver/runner.rb:21:in `run'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:63:in `block (2 levels) in run'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:149:in `run'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/matthieu/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/deliver-1.15.0/bin/deliver:5:in `<top (required)>'
	from /Users/matthieu/.rbenv/versions/2.2.2/bin/deliver:23:in `load'
	from /Users/matthieu/.rbenv/versions/2.2.2/bin/deliver:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.11.6                                            |
| Ruby                | 2.2.2                                              |
| Bundler?            | false                                              |
| Xcode Path          | /Applications/Xcode_7.3.1.app/Contents/Developer/  |
| Xcode Version       | 7.3.1                                              |
| Git                 | git version 2.10.0                                 |
| Installation Source | /Users/matthieu/.rbenv/versions/2.2.2/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                         |
| Ruby Lib Dir        | /Users/matthieu/.rbenv/versions/2.2.2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                         |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.1        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| colored                   | 1.2          |
| claide                    | 1.0.0        |
| xcodeproj                 | 1.3.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.53.0       |
| bundler                   | 1.13.1       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
</details>

*generated on:* **2016-11-07**
</details>

**Comment by petitmat** [comment]
I fixed it !

It was because I'm using Jenkins and it doesn't support utf-8 by default. You have to add : 

export LANG=en_US.UTF-8
export LANGUAGE=en_US:en

in your build step before calling your script.

**Comment by TKBurner** [comment]
@petitmat Thanks for reaching out. I've looped in the core team. Can you let me know if you updated ruby, your OS or open-SSL recently? Thanks!

**Comment by petitmat** [comment]
@TKBurner 

Hi ! I'm using : 
ruby 2.2.2p95
OSX 10.11.6
and OpenSSL 0.9.8
Which haven't been update for a while !

**Comment by KrauseFx** [comment]
Hey @petitmat, could you give this a try? https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip

**Comment by petitmat** [comment]
Hi I've installed it and my scripts seem to run correctly on Jenkins and upload on Itunes Connect without problems. What this package is supposed to do ? 

Just surprise about my fastlane env output :

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.11.6                                           |
| Ruby                | 2.2.4                                             |
| Bundler?            | false                                             |
| Xcode Path          | /Applications/Xcode_7.3.1.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                             |
| Git                 | git version 2.10.0                                |
| Installation Source | /Users/matthieu/.fastlane/bin/bundle/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                        |
| Ruby Lib Dir        | /Users/matthieu/.fastlane/bin/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                        |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.54.0  | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| babosa              | 1.0.2   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.1.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.54.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>


*generated on:* **2016-11-10**
</details>

**Comment by akkhilns** [comment]
im running deliver command in shell script. 
Added these lines 
**export LANG=en_US.UTF-8
export LANGUAGE=en_US:en**
on the top of shell script solved my issue.
