### ISSUE TITLE
changelog_from_git_commits -> crashlytics has [m in it

### ISSUE THREAD

**Issue by riyaz** [fastlane/fastlane#6892]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm generating changelog using changelog_from_git_commits and pass it to crashlytics, I tried writing it a file and send to crashlytics using notes_path path param still no use.

##### Fastfile snippet #####

```
changelog_from_git_commits(
    pretty: '*%d%Creset',
    merge_commit_filtering: 'exclude_merges' 
)

crashlytics(
    api_token: 'XXX',
    build_secret: 'YYY',
    notifications: 'false',
)
```
##### Changelog uploaded to crashlytics

*[m init commit[m
*[m another init[m
*[m Version Bump[m

![image](https://cloud.githubusercontent.com/assets/22842/20066599/1223751c-a538-11e6-9a45-6f5f466bac20.png)

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                          |
| ------------------- | ---------------------------------------------- |
| OS                  | 10.12.1                                        |
| Ruby                | 2.3.0                                          |
| Bundler?            | true                                           |
| Xcode Path          | /Library/Developer/CommandLineTools/           |
| Xcode Version       |                                                |
| Git                 | git version 2.10.2                             |
| Installation Source | /Users/riyaz/.rvm/gems/ruby-2.3.0/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                     |
| Ruby Lib Dir        | /Users/riyaz/.rvm/rubies/ruby-2.3.0/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                    |

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| deliver             | 1.15.0  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| pilot               | 1.12.0  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| scan                | 0.14.0  | 🚫 Update availaible |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| fastlane            | 1.107.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.4.0        |
| artifactory               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.53.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.0       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| dot-properties            | 0.1.3        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.19       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.8        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
</details>

*generated on:* **2016-11-07**
</details>

**Comment by asfalcone** [comment]
@riyaz what should `pretty` format you're using (pretty: '*%d%Creset %s<%an>%Creset') look like?

**Comment by riyaz** [comment]
yes

**Comment by hjanuschka** [comment]
can you try removing `%Creset` - as this forces ansi color reset.
wich is not displayable by crashlytics changelog (seems to be)

without '%Creset' it works on my machine.


i guess you tried to disable colored `git log` - to disable coloring see: https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration#Colors-in-Git

**Comment by riyaz** [comment]
@hjanuschka 👍 that fixed the issue thanks, closing the issue too.
