### ISSUE TITLE
Add options to disable the printing of lane context and fastlane summary table

### ISSUE THREAD

**Issue by CareerFairPlus** [fastlane/fastlane#6897]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
This is an enhancement/feature request to please add a configuration option that gives users the ability to disable fastlane from outputting the lane_context during an error.  Also, please add a separate configuration option that gives users the ability to disable fastlane from outputting the "fastlane summary" table when fastlane is finished.
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

N/A

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

N/A

**Comment by milch** [comment]
Can you go into a bit more detail why that would be useful for you, and how other users could benefit from this change?

**Comment by CareerFairPlus** [comment]
Sure.  This would be very useful for us because our Fastfiles are setup to deploy multiple different apps at once (like tens of apps at a time).  We have our CI server running our builds with fastlane and the logs get ginormous.  The major driver of the size of the logs is build output, fastlane summary table output and fastlane lane context output.  Being able to turn off the summary and the lane context would save us a tremendous amount of space on our CI server.  This would benefit anyone who has their builds setup with a CI server.

**Comment by CareerFairPlus** [comment]
Just to further clarify, I'm referring to the "fastlane summary" table at the end of execution, _**not**_ the individual lane summary tables (like produce, pem, etc.)

**Comment by milch** [comment]
Alright, I can see the value in that. We could add a global `--quiet` option that disables outputs like these - or even disables most of the output except for errors. Does that sound like a good solution to you? Any other things you think would make sense to have muted? 

In the meantime, you should also be able to mute the lane_context output using `egrep`: 

```bash
fastlane release | egrep -v ":DEFAULT_PLATFORM=>|Variable Dump"
```

**Comment by CareerFairPlus** [comment]
I think that seems reasonable.  The update messages would also seem like a good candidate to filter out if `--quiet` is present.

ex.
```
#######################################################################
# fastlane 1.107.0 is available. You are on 1.106.2.
# It is recommended to use the latest version.
# Update using 'bundle update fastlane'.
#######################################################################

1.107.0 New actions, enhanced debugging features & more
* Add error message on `fastlane init` when fastlane directory or file already exists (#6849)
* Update error message when using fastlane_version with bundle (#6831)
* Automatically use GITHUB_API_TOKEN for create pull request action (#6841)
* Add app_store_build_number action (#6790)
* Honor system proxy settings when downloading crashlytics.jar (#6817)
* enhance env printing + add  `--capture_output`  option
* Move Actions.md to docs.fastlane.tools (#6809)
* Improve `fastlane init` already exists error message (#6798)
* Fix slack action error when passing a custom payload option (#6792)
* Don’t ask for clipboard on non-interactive shell (#6782)
* Update dependencies
```

**Comment by KrauseFx** [comment]
You can also use the `FASTLANE_SKIP_UPDATE_CHECK` to hide the update messages 👍

**Comment by ohayon** [comment]
Going too close this issue for now as I think @KrauseFx's solution is great. Feel free to drop a note here if things are still not working as desired. 🐙

**Comment by CareerFairPlus** [comment]
@KrauseFx's solution is only for the update check output....not all the other output this issue was referring to...
