### ISSUE TITLE
Sigh: Add option to save provision profiles by name rather than by app ID

### ISSUE THREAD

**Issue by craigho** [fastlane/fastlane#6898]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm using fastlane (sigh) to manage a large list of provisioning profiles. It is easier for my purposes to have `sigh download_all` pull down the provision profiles by name, rather than app ID.

I am proposing a feature: a flag to switch from using `profile.app.bundle_id` to `profile.name`.

Please let me know if I should submit a pull request for this functionality. https://github.com/craigho/fastlane/tree/profile-download

##### Complete output when running fastlane, including the stack trace and command used

(-d is the flag for the newly proposed functionality)
> /usr/local/bin/sigh download_all --username abc@xyz.com --skip_install -d -o /tmp/profiles
> [08:21:15]: Starting login with user 'abc@xyz.com'
> [08:21:17]: Successfully logged in
> [08:21:19]: Downloading profile 'A Profile'...
> [08:21:19]: Downloading profile 'B Profile'...
> ls /tmp/profiles
>  Development_A Profile.mobileprovision Development_B Profile.mobileprovision

**Comment by TKBurner** [comment]
@craigho I'm not sure how this will work with implications in _match_. I'm going to leave this open for more feedback 👍

**Comment by craigho** [comment]
I considered download_all, plus the renewal scenario. The drawback to this is that some actions require you to reference the app.bundle_id (like --force), so having a bunch of profiles _not_ named by app.bundle_id  makes for a bit of a logistical headache, though the ID can be found inside the file (for adhoc and developer).

**Comment by craigho** [comment]
@tkburner do you think it would be appropriate to create a pull request for this?

**Comment by craigho** [comment]
Would it be bad form to submit my pull request now ?

**Comment by AnneTheAgile** [comment]
+1 for this feature. 
@craigho it seems like due to the bot the ticket status changed to await your reply. Maybe this will be good enough.

To get the UUID, in Bash this works; 
http://stackoverflow.com/questions/10398456/can-an-xcode-mobileprovision-file-be-installed-from-the-command-line/10775025
````
grep UUID -A1 -a adhoc.mobileprovision | grep -io "[-A-Z0-9]\{36\}"
````
