### ISSUE TITLE
frameit offsets not quite right

### ISSUE THREAD

**Issue by claesjacobsson** [fastlane/fastlane#6899]
I'm having problems with offsets placing the screenshot slightly wrong in the frame. Historically, I believe this has been caused by Apple changing their device frames. Is this a known problem in the latest version of frameit?

**Comment by claesjacobsson** [comment]
Is it correct that Apple sometimes changes the positioning of the device frames and that this has caused problems in the past?

**Comment by TKBurner** [comment]
@claesjacobsson Can you share the output of `fastlane env` and also share some screenshots of the issue you are seeing? I'd love to take a look 👍

**Comment by claesjacobsson** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.1                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode 8.1.app/Contents/Developer/                |
| Xcode Version       | 8.1                                                            |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.1 (16B2555)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| terminal-table            | 1.4.5   |
| multipart-post            | 2.0.0   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| net-sftp                  | 2.1.2   |
| plist                     | 3.1.0   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.10 |
| xcpretty                  | 0.2.4   |
| claide                    | 1.0.1   |
| xcode-install             | 2.0.8   |
| word_wrap                 | 1.0.0   |
| colored                   | 1.2     |
| babosa                    | 1.0.2   |
| gh_inspector              | 1.0.2   |
| credentials_manager       | 0.16.2  |
| fastlane_core             | 0.53.0  |
| bundler                   | 1.13.6  |
| multi_xml                 | 0.5.5   |
| faraday-cookie_jar        | 0.0.6   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| httpclient                | 2.8.2.4 |
| google-api-client         | 0.9.19  |
| json                      | 1.8.3   |
| excon                     | 0.54.0  |
| CFPropertyList            | 2.3.3   |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
</details>

**Comment by claesjacobsson** [comment]
![iphone5s-listscreen_framed](https://cloud.githubusercontent.com/assets/507101/20107518/196b87d2-a5d9-11e6-862f-e812f8a8fd6f.png)
![iphone7-listscreen_framed](https://cloud.githubusercontent.com/assets/507101/20107519/196e7fc8-a5d9-11e6-82dc-179e0a7a4ef9.png)
![iphone7plus-listscreen_framed](https://cloud.githubusercontent.com/assets/507101/20107520/196f036c-a5d9-11e6-9cce-51ae3c9dc93a.png)

**Comment by claesjacobsson** [comment]
If Apple keeps changing the device frames: is there a way for MiniMagick to detect the inner transparent frame where we'd like to place the screenshot? If that's possible, screenshots could always be correctly positioned and we could get rid of the offsets.json file.

**Comment by KrauseFx** [comment]
No, we actually updated _frameit_ 3.0 to not be influenced by Apple from now on. You can find the `offsets.json` here https://github.com/fastlane/fastlane/blob/master/frameit/frames_generator/offsets.json

Feel free to modify it locally inside `~/.frameit` and send a PR to the JSON file 👍

**Comment by claesjacobsson** [comment]
Ok, great!

**Comment by claesjacobsson** [comment]
Submitted PR #6923.

**Comment by claesjacobsson** [comment]
How did you avoid being influenced by Apple's device images, by the way?

**Comment by KrauseFx** [comment]
By using Facebook's image resources 👍
