### ISSUE TITLE
[match] Import code signing certificate to match repo

### ISSUE THREAD

**Issue by fabiomassimo** [fastlane/fastlane#6900]
# What

As `match` user I love that all my certificates and provisioning profiles can be automated, although when using `match` it is not possible to import an existing code signing certificate to the repo. 
The suggested solution is to use `match nuke` to remove all certificate not managed by `match`, since creation, and recreate them. Although this is a valid solution, that aims to keep consistency in the repo, it can easily be not ideal for some projects.

A command like `match import {certificate}` makes it easy to import a P12 certificate (for instance exported from the Keychain) to a `match` repo.

# Why

1. The team has distributed apps via TestFlight and it has reached the number of iOS Distribution certificate that can be issued. Since they want to start using `match` they soon find out that they should run `match nuke` because no new distribution certificate can be issued. This solution, would make all the distributed TestFlight builds stop working. 
Thanks to `match import` the team can easily move the project to start using `match` by importing the iOS Distribution certificate they already own in their Keychain.

2. https://fastlane-tools.slack.com/archives/questions/p1478178628000681

3. https://fastlane-tools.slack.com/archives/questions/p1475762422000253

# TODO

The `import` feature must take care of:

- make sure the certificate to import exists in the Apple Developer Portal.
- the certificate type is properly identified such that can be added to the repo in the correct folder tree structure.
- the certificate to import gets renamed with the id assigned by the Apple Developer Portal

# Spoiler alert

I have implemented this functionality already but before opening a PR I'd love to have your opinion here.
For more details: https://github.com/fabiomassimo/fastlane/tree/match_import

**Comment by TKBurner** [comment]
@fabiomassimo Thanks for reaching out. I'm bumped this with the core team to see what the interest is. I am really happy to see what you built 👍

**Comment by milch** [comment]
@fabiomassimo Thanks for your detailed issue! I am very open to this feature as I've run into this before myself. 

However, we always have to be careful when implementing new features. This especially affects core features that could have a big impact on how users are using fastlane, like this one. 

In my experience, while it is a nuisance to send out another build that testers need to update to, fastlane does make it very easy. Review times being as low as they are right now also means that the new build would be available to testers VERY soon. As such, I am not entirely convinced yet that this would fulfill the need of a large amount of users. 

What do you think?

**Comment by fabiomassimo** [comment]
@milch You are right, this is not an easy feature and I'd like to gather as more feedbacks as possible. Thank you for chiming in.

It is true, `fastlane` makes it possible to create new builds in no time but distributing an app can involve different use cases.
Let's say you distribute your beta apps via Fabric Beta to multiple testers or potential clients. Nuking the distribution certificate could trigger unexpected behaviours to old builds already installed on different devices.
It is true, an update can be submitted and the issue fixed but if you have an enterprise certificate used for beta distributing different apps to different clients, you do not want to make a new build for all of those apps, asking to your clients to update.
As fast you can try to reach them it could happen that the app just crashes on launch.

As it concerns the consistency of fastlane's core features, I see the `import` more as an option that the user can take advantage of if he needs it. 
It is a convenience command that you "trigger-and-forget". My goal is just to import an external certificate in the proper way. After it's in the repo, `match` will take care of it.

**Comment by milch** [comment]
> Let's say you distribute your beta apps via Fabric Beta to multiple testers or potential clients. Nuking the distribution certificate could trigger unexpected behaviours to old builds already installed on different devices.

Right, I hadn't thought about the client use-case. 

> As it concerns the consistency of fastlane's core features, I see the import more as an option that the user can take advantage of if he needs it. 

My concern is that there is a lot that can go wrong while using `import` - basically everything you listed above and more. There's also the fact that people will wonder why they can't import a certificate without having the associated Apple ID (e.g. the developers might not have access to the developer account, also a situation I've experienced). All that translates into an increased support-load that we have to weigh against the usefulness for this feature to the general userbase. 

That being said, if we have enough diagnostics/documentation that users know exactly what this feature does (and doesn't) do I'm open to accepting the PR.

**Comment by fabiomassimo** [comment]
I see your point and I believe we can deliver this feature without weakening the user experience or tremendously increasing the support-load.

Match has in mind most of the user's use cases and we should take inspiration from the lessons learned and the powerful options at our disposal. 

I'll workout a PR that puts out there some code on which we could work/discuss on. I'd really appreciate some practical feedbacks on that too. 

For what it concerns the documentation, certificates are a domain of knowledge not common to everyone and we should put even more effort in making it easy to approach and understand to properly guide the user to use this command. Once (and if) we are ready to merge it, we should follow up with another PR for the fastlane's docs. 

Sounds like a plan?

**Comment by milch** [comment]
> Sounds like a plan?

Yes, thank you! 

> I'll workout a PR that puts out there some code on which we could work/discuss on.

Just as a general advice for submitting PR's because I saw you changed things in `match` as well as `sigh`. Usually we split up PRs by tool, so there should be a separate `match` and a `sigh` one. It'd also be good if we could work on the docs alongside this and then merge all three in one go.

**Comment by fabiomassimo** [comment]
Sorry,my bad, the `sigh` changed files were inherited from another PR still awaiting for approval.

I reverted those and started to share my code in the PR, working on the docs now.
