### ISSUE TITLE
Sigh: Add option to update provision profile with a single UDID

### ISSUE THREAD

**Issue by craigho** [fastlane/fastlane#6901]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm using fastlane (sigh) to manage a large list of UDIDs. It is easier for my purposes to have sigh add a single UDID to a provision profile, rather than pulling in all available UDIDs.

I am proposing a feature: a flag that works similar to/overrides --force functionality. The profile is renewed, but only a single UDID is added. (Existing UDIDs will remain). This can be accomplished by setting `profiles.devices` to a single device rather than `Spaceship.device.all_for_profile_type(profile.type)`. The device can be found by using `Spaceship.device.find_by_udid`

Please let me know if I should submit a pull request for this functionality. https://github.com/craigho/fastlane/tree/device-list

##### Complete output when running fastlane, including the stack trace and command used
(--add is the newly proposed flag for this functionality)

> sigh -a com.company.app.id -u abc@xyz.com --skip_install --skip_certificate_verification --add 1234567890123456789012345678901234567890 --development
> [14:11:46]: Starting login with user 'abc@xyz.com'
> [14:11:48]: Successfully logged in
> [14:11:48]: Fetching profiles...
> [14:11:49]: Found 1 matching profile(s)
> [14:11:50]: Attempting to add 1234567890123456789012345678901234567890 to the provision profile
> [14:11:57]: Downloading provisioning profile...
> [14:11:57]: Successfully downloaded provisioning profile...

**Comment by TKBurner** [comment]
@craigho This is an interesting idea. I can understand the use case. If you are interested in a submitting a PR we'd work with you.

**Comment by craigho** [comment]
Thanks @TKBurner, I have submitted my PR.

**Comment by milch** [comment]
I'm going to close this, as discussed in https://github.com/fastlane/fastlane/pull/6911#issuecomment-270947910
