### ISSUE TITLE
new check for imagemagick fails ci even when graphicsmagick install

### ISSUE THREAD

**Issue by ooopscc** [fastlane/fastlane#6904]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

new check for imagemagick fails ci even when graphicsmagick install
minimagick works on both imagemagick and graphicsmagick

related pr: https://github.com/fastlane/fastlane/pull/6568/commits
[badge](https://github.com/HazAT/badge) -> [minimagic](https://github.com/minimagick/minimagick) -> imagemagick **OR** graphicsmagick

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[16:25:30]: -------------------
[16:25:30]: --- Step: badge ---
[16:25:30]: -------------------
[16:25:30]: You have to install ImageMagick to use `badge`
[16:25:30]: 
[16:25:30]: Install it using:
[16:25:30]: $ brew update && brew install imagemagick
[16:25:30]: 
[16:25:30]: If you don't have homebrew, visit http://brew.sh
[16:25:30]: Variable Dump:
[16:25:30]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios dailybuild", :VERSION_NUMBER=>"4.1.0", :BUILD_NUMBER=>"472"}
[16:25:30]: Install ImageMagick and start your lane again!
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                          |
| ------------------- | ---------------------------------------------- |
| OS                  | 10.12.1                                        |
| Ruby                | 2.2.4                                          |
| Bundler?            | false                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version       | 8.1                                            |
| Git                 | git version 2.9.3 (Apple Git-75)               |
| Installation Source | /Users/ooops/.rvm/gems/ruby-2.2.4/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                     |
| Ruby Lib Dir        | /Users/ooops/.rvm/rubies/ruby-2.2.4/lib        |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                     |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.13.6  |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| terminal-table            | 1.4.5   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| dotenv                    | 2.1.1   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.1.0   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.10 |
| slack-notifier            | 1.5.1   |
| xcpretty                  | 0.2.4   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| multi_json                | 1.12.1  |
| colored                   | 1.2     |
| babosa                    | 1.0.2   |
| gh_inspector              | 1.0.2   |
| credentials_manager       | 0.16.2  |
| fastlane_core             | 0.53.0  |
| multi_xml                 | 0.5.5   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| json                      | 1.8.3   |
| excon                     | 0.54.0  |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
</details>

*generated on:* **2016-11-08**
</details>

**Comment by hjanuschka** [comment]
i did a PR right now - to also support graphicsmagick 
https://github.com/fastlane/fastlane/pull/6905

**Comment by ooopscc** [comment]
@hjanuschka 👍 very fastlane.

**Comment by ZaidSA** [comment]
@hjanuschka I'm still getting same error while building on Travis-CI, works fine on local machine.
Any hint?

**Comment by hjanuschka** [comment]
@ZaidSA are you on the latest version?

**Comment by ZaidSA** [comment]
@hjanuschka Thank you for very fast response, I'm having `fastlane_version "1.109.0"` version.

**Comment by hjanuschka** [comment]
ohhh that is quiet old 👍  you should upgrade to the latest version, and atleast `2.3.0`

**Comment by ZaidSA** [comment]
Thank you @hjanuschka, updating on travis now. 👍
I appreciate your quick help.

**Comment by hjanuschka** [comment]
you are welcome, if you still have problems please open a new issue (feel free to ping me directly)
as this issue is closed and it might trigger notifications for users that they not expect.
