### ISSUE TITLE
Adding the target for xCode automatically.

### ISSUE THREAD

**Issue by bapsteks** [fastlane/fastlane#6908]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I understand that Fastlane may have been built to maintain 1 App? However we are looking to automate the submission of over 800 Apps, is there a way of automatically adding the target for Snapshot? We're currently hitting a real bottleneck when adding the UI Testing Bundle.

Thanks,

**Comment by hjanuschka** [comment]
hello @bapsteks  this is probably the same as here:  

  * https://github.com/fastlane/fastlane/issues/6365#issuecomment-258881646

wich points to following stackoverflow solution:

  * http://stackoverflow.com/questions/39934254/xcode-8-preparing-archive-takes-forever/40313078#40313078

after the upgrade the keychains get  messed up (sometimes)
so either create a new one using `create_keychain` - or clean them up.

**Comment by hjanuschka** [comment]
so you want to end up with a single project with 800 targets?

what is your goal?
for example - we have a single project - and depending on the git branch - we change the app-identifier and generate another app out of it :)


example:

```ruby
lane :brand_app do
  before_build
  update_app_identifier(
    app_identifier: 'new.app.idf',
    plist_path: 'FiveXFive/Supporting Files/fivexfive-Info.plist'
  )
  update_info_plist(
    plist_path: 'FiveXFive/Supporting Files/fivexfive-Info.plist',
    display_name: 'Willi-Bird'
  )
  badge(dark: true)
  match
  gym
  sh 'git stash'

end
```

**Comment by bapsteks** [comment]
We will have around 800 individual Apps that will be checked out one by one in git, each having a new xcode project associated with it. When we check these new Apps out they will not have the target needed to create screenshots via snapshot and adding this in manually takes away from the automation that I am trying to achieve. The entire apps are unfortunately completely different so we won't be able to just change the bundle id's etc.

**Comment by hjanuschka** [comment]
got you - you can try using `xcodeproj` gem.


```ruby
project_path = '/your_path/your_project.xcodeproj'
proj = Xcodeproj::Project.open(project_path)
app_target = proj.new_target(:application, 'App', :ios, '9.0')
header_ref = proj.main_group.new_file('./Class.h')
implm_ref = proj.main_group.new_file('./Class.m')
app_target.add_file_references([implm_ref])
proj.save_as(project_path)
```

untested - but it should be a good starting point,  you may need to digg a bit into the xcodeproj-api.

**Comment by bapsteks** [comment]
That's brilliant, relatively new to Ruby so all of this is new to me but this appears to be a step in the right direction. Thanks a lot :)

**Comment by bapsteks** [comment]
Just incase anybody runs into the same issue, I was able to overcome this eventually by editing the xcodeproj file itself every time the App is built to always include that target.
