### ISSUE TITLE
how to distribute a build to internal tester using spaceship (when using --skip-sumission)

### ISSUE THREAD

**Issue by jedi4ever** [fastlane/fastlane#6912]
### Issue Description
I'm coding a cli called `slowlane` - <https://github.com/jedi4ever/slowlane/>

a) To upload an ipa I've looked at the `pilot` code and that works
https://github.com/jedi4ever/slowlane/blob/01fd3a77dd84151c0eba2cb737b3df58096ffe3d/lib/slowlane/itunes/build.rb#L67

b) I skip submission as I use the tool during CI builds and the timeout of apple is high for the build system to complete. Now I'm looking for a way to submit a build to internal testers but can't understand how to use the build_trains etc. to do this. Any code or pointer to relevant code is appreciated.

**Comment by jedi4ever** [comment]
nevermind found it

https://github.com/fastlane/fastlane/blob/714b3a40117f8b59d0d13c7ebd32e7abe46c6b5b/spaceship/lib/spaceship/tunes/build_train.rb#L112

**Comment by KrauseFx** [comment]
👍
