### ISSUE TITLE
gym: "invalid option: -derivedDataPath" after updating

### ISSUE THREAD

**Issue by JAStanton** [fastlane/fastlane#6913]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This has only started happening to be since updating all my fastlane gems:

```bash
gym 
  --verbose \ 
  --buildlog_path /Users/jas/Github/redacted-app-name/build/demo/archive:ios \ 
  --workspace /Users/jas/Github/redacted-app-name/ios/App.xcworkspace \ 
  --scheme demo \ 
  --output_directory /Users/jas/Github/redacted-app-name/build/demo \ 
  --xcargs '-derivedDataPath "/Users/jas/Github/redacted-app-name/build/demo/_intermediates/ios"'
  --codesigning_identity 'iPhone Distribution: Redacted, Inc (redacted numbers)'
```
The error:
```
invalid option: -derivedDataPath "/Users/jas/Github/redacted-app-name/build/demo/_intermediates/ios"
```

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.5                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | true                                                           |
| Xcode Path          | /Applications/Xcode-7.app/Contents/Developer/                  |
| Xcode Version       | 7.3.1                                                          |
| Git                 | git version 2.7.4 (Apple Git-66)                               |
| Installation Source | ./vendor/bin/fastlane                                          |
| Host                | Mac OS X 10.11.5 (15F34)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
apple_id 'redacted@redacted.com'
team_id 'redacted'
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.53.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.12.4       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.53.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.0       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.1        |
| cocoapods-deintegrate     | 1.0.0        |
| cocoapods-downloader      | 1.0.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.0.0        |
| cocoapods-try             | 1.0.0        |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.1        |
| molinillo                 | 0.4.5        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.0.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types                | 2.99.3       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.19       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.8        |
| psych                     | 2.0.17       |
| rest-client               | 1.8.0        |
</details>

**Comment by JAStanton** [comment]
Ah I think I may have figured it out. It seems as if the `-` wasn't being escaped. This was valid before (1.7.0 I think).

from this:
```
  --xcargs '-derivedDataPath "/Users/jas/Github/redacted-app-name/build/demo/_intermediates/ios"'
```

to this:
```
  --xcargs '\-derivedDataPath "/Users/jas/Github/redacted-app-name/build/demo/_intermediates/ios"'
```

**Comment by JAStanton** [comment]
So this is the command that eventually runs:
```bash
set -o pipefail
&& xcodebuild -workspace /Users/jas/Github/redacted-app-name/ios/Driver.xcworkspace
  -scheme demo
  -destination 'generic/platform=iOS'
  -archivePath /Users/jas/Library/Developer/Xcode/Archives/2016-11-08/Driver\ 2016-11-08\ 10.04.31.xcarchive
  \-derivedDataPath "/Users/jas/Github/redacted-app-name/build/demo/_intermediates/ios"
  archive CODE_SIGN_IDENTITY=Redacted\ App \(RedactedNumbers\)
| tee /Users/jas/Github/redacted-app-name/build/demo/archive:ios/Driver-demo.log | xcpretty
```

I suppose thats valid syntax `\-derivedDataPath` but it's not confidence inspiring to see the bask slash :)

**Comment by milch** [comment]
That's interesting - I can reproduce it on my local machine too. I'm guessing for some reason dashes aren't escaped correctly when generating the build command. 

However, in your case `derivedDataPath` is actually an option that's supported by gym natively, so this should work for your purposes:

```bash
gym 
  --verbose \ 
  --buildlog_path /Users/jas/Github/redacted-app-name/build/demo/archive:ios \ 
  --workspace /Users/jas/Github/redacted-app-name/ios/App.xcworkspace \ 
  --scheme demo \ 
  --output_directory /Users/jas/Github/redacted-app-name/build/demo \ 
  --derived_data_path "/Users/jas/Github/redacted-app-name/build/demo/_intermediates/ios" \
  --codesigning_identity 'iPhone Distribution: Redacted, Inc (redacted numbers)'
```

**Comment by JAStanton** [comment]
Oh nice! thanks for this bit of information :)

**Comment by PetrosIchor** [comment]
Yeah, I started seeing it this week as well.  Thought I broke my environment for a minute haha.
