### ISSUE TITLE
Add language settings to env output

### ISSUE THREAD

**Issue by milch** [fastlane/fastlane#6914]
We often receive issues that have problems with the language settings, see #6891. Users receive errors like `�[33mencode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)�[0m`, or other, similar ones. To be able to quickly triage/solve these issues, the value of these environment vars needs to be added to the output of `fastlane env`:

- LANG
- LANGUAGE
- LC_ALL

The value of all of these should be `en_US.UTF-8` (or some other type of UTF-8, I guess), and the output should show some sign if they aren't (e.g. ✅  and ⛔️ respectively)

**Comment by hjanuschka** [comment]
ready for review: https://github.com/fastlane/fastlane/pull/6915
