### ISSUE TITLE
Add Regex support for crashlytics `apk_path`

### ISSUE THREAD

**Issue by caipivara** [fastlane/fastlane#6916]
On current `fastlane 1.107.0` version you cant define a regex for apk path, I mean:

```
crashlytics(
        //...
        apk_path: "./app/build/output/apk/*-debug.apk",
)
```

Because apk names can be dynamic if you use `archivesBaseName = "$appVersionName-$appVersionCode"` setup on gradle

**Comment by hjanuschka** [comment]
if you build with `gradle` action - the apk name should be in: `lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]`

**Comment by caipivara** [comment]
@hjanuschka I didn't understand what you mean by that :P, can you try to explain again?

what is `lane_context` and `SharedValues` in _FastLane_?

**Comment by hjanuschka** [comment]
@caipivara some actions store values in a `lane_context`

gradle for example stores the path of the compiled apk in the above variable 


so you could do stuff like this.:

```ruby
gradle(task: "assembleDebug")
crashlytics(apk_path: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH])
```

**Comment by caipivara** [comment]
@hjanuschka got it now, thanks!
