### ISSUE TITLE
krausefx-shenzhen/plist dependencies

### ISSUE THREAD

**Issue by sebastianludwig** [fastlane/fastlane#6917]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

[fastlane.gemspec](https://github.com/fastlane/fastlane/blob/master/fastlane/fastlane.gemspec) references `'krausefx-shenzhen', '>= 0.14.10'` as dependency - and it seems to be a bit of a mess. I was unable to find its repository, otherwise I'd have opened an issue there. However the `krausefx` suggests a tight relationship to fastlane, so I opened it here.

-  I guess it's a fork of [nomad/shenzhen](https://github.com/nomad/shenzhen), which is stuck on 0.14.02.
- According to [rubygems](https://rubygems.org/gems/krausefx-shenzhen/versions/0.14.10) the 0.14.10 release was in August (the gem contains a file `krausefx-shenzhen-0.14.9.gem`)
- It specifies a dependency for `"plist", "~> 3.1.0"` - fastlane specefies ['plist', '>= 3.1.0', '< 4.0.0'](https://github.com/fastlane/fastlane/blob/master/fastlane/fastlane.gemspec)
- This results in plist 3.1.0 to be used. That version still generates plists containing "Apple Computer" instead of just "Apple" in its header. That has been [changed in 2011](https://github.com/bleything/plist/commit/81bba1b39e066710dba6a4b4098b5559ab38613e), but the version 3.2.0 containing the change has only been [released in January 2016](https://rubygems.org/gems/plist/versions/3.2.0). This causes an unnecessary diff when using the [`set_info_plist_value`](https://docs.fastlane.tools/actions/#set_info_plist_value) action.

### Proposed solutions
1. Integrate `krausefx-shenzen` into the fastlane repository
1. Upgrade dependency to `'plist', '>= 3.1.0', '< 4.0.0'` - I checked the diff and don't see any problems.

**Comment by milch** [comment]
Hi, thanks for your report!

The `krausefx-shenzhen` gem sources are available at [fastlane/shenzhen](https://github.com/fastlane/shenzhen) in case you want to take a look, or even submit a PR. 

When #6858 is merged, we might also be able to pull out some of the dependencies and install them on the fly when needed.

**Comment by sebastianludwig** [comment]
Oh man,  fastlane/shenzhen was pretty obvious - should have found that. I'll submit a PR and consider this closed 👍

**Comment by milch** [comment]
Thanks for understanding 😄  

We are looking forward to your contribution! 🚀

**Comment by revolter** [comment]
But [this][1] says that `gym is a replacement for shenzhen`, so why does fastlane has shenzhen as a dependency?

  [1]: https://github.com/fastlane/fastlane/tree/master/gym#whats-gym

**Comment by sebastianludwig** [comment]
For backwards compatibility and historical reasons (I guess). There's the `ipa` action which still uses `shenzhen`. The removal of `shenzhen` is discussed in #6991.

**Comment by milch** [comment]
@revolter: Yes, @sebastianludwig is correct

**Comment by revolter** [comment]
Thanks!
