### ISSUE TITLE
match enterprise support

### ISSUE THREAD

**Issue by jostster** [fastlane/fastlane#6918]
I know there was a previous issue about match support for enterprise accounts but it seems to have been closed. Can this be added back in with clear warnings? We currently use a shell script to run our enterprise builds but want to switch to fastlane. However, after finding out we will be unable to use match with this, it seems to be pointless to switch for us.

Could this issue be revisited and allow match to optionally support enterprise?

**Comment by PetrosIchor** [comment]
Enterprise is not officially supported. Take a close look at the match repo for ideas on how to solve your problem.  It helped me with creating enterprise parity.

**Comment by jostster** [comment]
@PetrosIchor do you have any tips on adding in this parity? I'm new to fastlane.

**Comment by KrauseFx** [comment]
You can enable it manually, see https://github.com/fastlane/fastlane/blob/master/match/lib/match.rb#L31 👍
