### ISSUE TITLE
Execute fastlane from web.

### ISSUE THREAD

**Issue by ramrcram** [fastlane/fastlane#6920]
### how can i run fastlane deploy from php ?
I am trying to automate the fastlane deploy from a web based. For that i am trying to call “Fastlane deploy” from a php, Unfortunately this is not executing no out put.

Could you please help me to solve this issue.

Thanks in advance.

**Comment by hjanuschka** [comment]
can you post your php code?

something like that should do it:

```php
$handle = popen('fastlane deploy 2>&1', 'r');
$read = fread($handle, 2096);
echo $read;
pclose($handle);
```


i think it would be cooler to use ruby to do it - like doing a little `sinatra` app - and embedd fastlane like this (unofficial - unsupported)

```ruby
require "fastlane"
module Fastlane
  class Embedded
    def initialize(params = {})
      available_lanes = Fastlane::FastlaneFolder.available_lanes
      lane = params[:lane]
      platform = params[:platform]
      lane_parameters = params[:lane_parameters]
      Fastlane::LaneManager.cruise_lane(platform, lane, lane_parameters, nil)
    end
end
end

Fastlane.load_actions
Fastlane::Embedded.new({ lane: "deploy" })
```
