### ISSUE TITLE
Match does not find any matching provisioning profiles even though it just created them

### ISSUE THREAD

**Issue by ph1lb4** [fastlane/fastlane#6921]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Match does not find any matching provisioning profiles even though it just created them.

My lane looks like this:

  lane :do_match do
    match(app_identifier: "com.example.identifier", readonly: true, force_for_new_devices: true, force: true)
  end

If I perform it with readonly "false" it creates the new profiles correctly. If I then try to perform it again with readonly "true" it does not work with below mentioned output.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[13:39:54]: -------------------------------------------------
[13:39:54]: --- Step: Verifying required fastlane version ---
[13:39:54]: -------------------------------------------------
[13:39:54]: Your fastlane version 1.107.0 matches the minimum requirement of 1.104.0  ✅
[13:39:54]: ------------------------------
[13:39:54]: --- Step: default_platform ---
[13:39:54]: ------------------------------
[13:39:55]: Driving the lane 'ios do_match' 🚀
[13:39:55]: -------------------
[13:39:55]: --- Step: match ---
[13:39:55]: -------------------
[13:39:56]: Successfully loaded '######################/fastlane/Matchfile' 📄

+----------------------+---------------------------------------------+
|            Detected Values from './fastlane/Matchfile'             |
+----------------------+---------------------------------------------+
| git_url              | #################################           |
| type                 | development                                 |
| username             | #####################                       |
+----------------------+---------------------------------------------+

+-----------------------+---------------------------------------------+
|                      Summary for match 0.10.0                       |
+-----------------------+---------------------------------------------+
| app_identifier        | com.example.identifier                      |
| readonly              | true                                        |
| force_for_new_devices | true                                        |
| force                 | true                                        |
| git_url               | #################################           |
| type                  | development                                 |
| username              | ######################                      |
| git_branch            | master                                      |
| keychain_name         | login.keychain                              |
| team_id               | ######################                      |
| verbose               | false                                       |
| shallow_clone         | false                                       |
| skip_docs             | false                                       |
+-----------------------+---------------------------------------------+

[13:39:56]: Cloning remote git repo...
[13:40:13]: 🔓  Successfully decrypted certificates repo
[13:40:13]: Installing certificate...
[13:40:15]: No matching provisioning profiles found for 'Development_com.example.identifier'
[13:40:15]: A new one cannot be created because you enabled `readonly`
[13:40:15]: Provisioning profiles in your repo for type `development`:
[13:40:15]: - 'Development_com.example.identifier-Dev.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier-Dev.NotificationContentExtension.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier-Dev.NotificationExtension.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier.NotificationContentExtension.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier.NotificationExtension.mobileprovision'
[13:40:15]: If you are certain that a profile should exist, double-check the recent changes to your match repository
[13:40:15]: 🔒  Successfully encrypted certificates repo
[13:40:15]: Variable Dump:
[13:40:15]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios do_match"}
[13:40:15]: No matching provisioning profiles found and can not create a new one because you enabled `readonly`. Check the output above for more information.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | match                               | 20          |
+------+-------------------------------------+-------------+

[13:40:15]: fastlane finished with errors

[!] No matching provisioning profiles found and can not create a new one because you enabled `readonly`. Check the output above for more information.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| deliver             | 1.15.0  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.3   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.0  | ✅ Up-To-Date        |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.2   | 🚫 Update availaible |
| fastlane            | 1.107.0 | ✅ Up-To-Date        |
| fastlane_core       | 0.54.0  | ✅ Up-To-Date        |

**Comment by KrauseFx** [comment]
Has this worked before or was this issue introduced recently?

**Comment by ph1lb4** [comment]
It worked well a while ago. However last time I checked was at least 1-2 months ago.

**Comment by TKBurner** [comment]
@ph1lb4 Thanks for following up. It looks like the string '-Dev' is being appended to your profiles,  'Development_com.example.identifier-Dev.NotificationContentExtension.mobileprovision''

Do you know of a reason why this would be happening? Thanks!

**Comment by milch** [comment]
That is weird, especially looking at the output here: 

[13:40:15]: No matching provisioning profiles found for **'Development_com.example.identifier'**
[13:40:15]: A new one cannot be created because you enabled readonly
[13:40:15]: Provisioning profiles in your repo for type development:
[13:40:15]: - 'Development_com.example.identifier-Dev.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier-Dev.NotificationContentExtension.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier-Dev.NotificationExtension.mobileprovision'
[13:40:15]: - **'Development_com.example.identifier.mobileprovision'**
[13:40:15]: - 'Development_com.example.identifier.NotificationContentExtension.mobileprovision'
[13:40:15]: - 'Development_com.example.identifier.NotificationExtension.mobileprovision'
[13:40:15]: If you are certain that a profile should exist, double-check the recent changes to your match repository

**Comment by ph1lb4** [comment]
We append '-Dev' for the staging version of our app. This means that we have every provisioning profile as normal and as -Dev.

So this is wanted behaviour from our side. Does this cause any trouble?

**Comment by ph1lb4** [comment]
@milch that's troubling us the most. We can see that the right profile is listed, however match does not find it.

**Comment by milch** [comment]
@ph1lb4 It shouldn't be a problem, as the correct provisioning profile seems to exist. 

The relevant code from `match` is here: 

```ruby
      profile_name = [Match::Generator.profile_type_name(prov_type), app_identifier].join("_").gsub("*", '\*') # this is important, as it shouldn't be a wildcard
      base_dir = File.join(params[:workspace], "profiles", prov_type.to_s)
      profiles = Dir[File.join(base_dir, "#{profile_name}.mobileprovision")]

      # Install the provisioning profiles
      profile = profiles.last

      #...

      if profile.nil? or params[:force]
        if params[:readonly]
          all_profiles = Dir.entries(base_dir).reject { |f| f.start_with? "." }
          UI.error "No matching provisioning profiles found for '#{profile_name}'"

          #...

        end
      end
```

I don't really see anything that could be going wrong here once the name is already correct, and I'm not able to reproduce it on my machine. Could I ask you to `git clone` your repo into some folder on your local machine, run the following code snippet (e.g. in `irb`) and check if the last line returns something?

```ruby
workspace = "<the directory you git clone'd the certificate repo into>" 
profile_name = "Development_<your bundle ID>"

base_dir = File.join(workspace, "profiles", "development")
profiles = Dir[File.join(base_dir, "#{profile_name}.mobileprovision")]
```

**Comment by milch** [comment]
Also just to make sure, what OS are you running this on?

**Comment by ph1lb4** [comment]
I will do that first thing tomorrow morning and post the result here.
Running on latest version of osx 10.11 el capitan as well as latest version osx 10.12 sierra

**Comment by ph1lb4** [comment]
The output is really weird. The last line does return an empty array. I think this is bad?

```
irb(main):001:0> workspace = "/Users/XXX/Desktop/fasltanematchtest"
=> "/Users/XXX/Desktop/fasltanematchtest"
irb(main):002:0> profile_name = "Development_com.example.identifier"
=> "Development_com.example.identifier"
irb(main):003:0> base_dir = File.join(workspace, "profiles", "development")
=> "/Users/XXX/Desktop/fasltanematchtest/profiles/development"
irb(main):004:0> profiles = Dir[File.join(base_dir, "#{profile_name}.mobileprovision")]
=> []
irb(main):005:0> 
```

**Comment by ph1lb4** [comment]
I do not understand how this is possible. In the folder "profiles" -> "development" I can see that there is the needed profile available. The name of the file is "Development_com.example.identifier.mobileprovision"

**Comment by ph1lb4** [comment]
@milch I found the problem thanks to your code snippets. The directory of our git repo looks like this

```
/certificates/profiles/development/
```

If I move the profiles folder up to the toplevel your scripts work. Is this something we have introduced or did you change that recently? I do not remeber anyone in our team messing around with the folder structure. Also can we change that manually?

**Comment by ph1lb4** [comment]
Sorry I had a blackout, I was running your commands in the wrong directory. Actually they are returning the right profile, the array is not empty.
