### ISSUE TITLE
Recommended way to increment the build number in Hockeyapp?

### ISSUE THREAD

**Issue by i-schuetz** [fastlane/fastlane#6922]
Hi,

I'm currently using Testflight, where there's an action to increment the build number based on the latest build available in Testflight.

I want to add Hockeyapp support. There doesn't seem to be an equivalent of the Testflight action here.

I'm using CircleCI to build.

So far I see following possibilities:

1) Keep the build number in the app, i.e. Circle will do an additional commit to increment the build number, after code has been pushed. This has the disadvantages that git will be full with these commits, since this will be done on each build, and also that Circle will start the build 2x, which is a no go. I read there are some solutions for this like described here: https://github.com/fastlane/fastlane/issues/35 but that seems to be only for Jenkins?

2) Use a date as build number like in this example: https://github.com/fastlane/examples/blob/master/Artsy/eidolon/Fastfile (+time, since multiple builds can run in a day)

3) Use [number_of_commits](https://docs.fastlane.tools/actions/) action. This seems to be the more reasonable possibility.

Any thoughts / advices?

**Comment by hjanuschka** [comment]
we use Gitlab-CI - and there is `ENV["CI_BUILD_ID"]` - wich increments by its own (therefore its safe to use).

| CI platform |   ENV |
| ------------|------|
| Gitlab-CI     | CI_BUILD_ID |
| Circle          | CIRCLE_BUILD_NUM |
| Travis         | TRAVIS_BUILD_NUMBER |

we just do 

```ruby
increment_build_number build_number: ENV["CI_BUILD_ID"]
testflight #in your case hockey
```

and don't commit back, and just ignore the fact that the build id in project is old.

**Comment by i-schuetz** [comment]
@hjanuschka 

oh this is great! I'll use this. Thanks!
