### ISSUE TITLE
Languages code with Produce ?

### ISSUE THREAD

**Issue by petitmat** [fastlane/fastlane#6924]
Hello, 

I'm asking about PRODUCE_LANGUAGE. Is it possible to use the same language code than in deliver to choose the primary language of the app ? 

For example is it possible to use "en-GB" instead of "English_UK" or "pt-BR" instead of Brazilian ? It could avoid me to create useless conversion method...

Thanks

**Comment by petitmat** [comment]
I don't understand why I have to add it because, it's an asking about a feature and not about an issue...

**Comment by TKBurner** [comment]
@petitmat Great idea! I've marked this as a feature request so we can track interest 👍
