### ISSUE TITLE
snapshot reset_all_simulators should have a -f option

### ISSUE THREAD

**Issue by ZevEisenberg** [fastlane/fastlane#6927]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
It would be nice if `snapshot reset_simulators` had a `-f`, `--force`, or similar option to run without prompting. Currently, there is no (easy) way to completely automate the use of this command because it always prompts for confirmation before resetting simulators.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$ bundle exec snapshot --version
snapshot 1.16.3
$ bundle exec snapshot reset_simulators
Are you sure? All your simulators will be DELETED and new ones will be created! (y/n)
y
Removing device iPhone 5 (E8AA6F65-A22E-44F6-B655-5699A17E7F67)
Removing device iPhone 5s (12E8B4BC-9040-43ED-B711-C554B44312AD)
Removing device iPhone 6 (A31AD851-B183-4E8A-8DE0-8B292C3BAF53)
Removing device iPhone 6 Plus (6A6CBFC4-E9C4-4019-BDDE-3A7E572C7F6B)
Removing device iPhone 6s (D6AA807D-E883-4DCE-8E63-E94B2FC3316E)
Removing device iPhone 6s Plus (386B5CC2-D09D-417A-ADEA-E055C266D7C6)
Removing device iPhone 7 (31FEFDD8-9AC4-4FC0-A58A-92F4DF2CBC5F)
Removing device iPhone 7 Plus (6A3114D0-08C2-4F67-94CC-AA6D7A96B8C8)
Removing device iPhone SE (9200DB32-6C44-45EF-9206-31145AD8D6B5)
Removing device iPad Retina (B45EC656-6A43-417B-84DC-D1195474DF53)
Removing device iPad Air (13D4C38E-B7F1-4DC9-86C8-C09EA3C19608)
Removing device iPad Air 2 (59C48604-50AC-47C6-B4B0-A9F1687D4F5E)
Removing device iPad Pro (9.7-inch) (B0D48AD0-CD0A-4630-8315-B88DCCA0701C)
Removing device iPad Pro (12.9-inch) (A5CE30DD-ADDF-4D5A-8F26-56258107A00C)
Removing device Apple TV 1080p (09714D50-5F05-4581-9C5B-9744BD31A8C5)
Removing device Apple Watch - 38mm (6FB23CA4-B331-4877-B37E-E63AF462DFEE)
Removing device Apple Watch - 42mm (7A57944C-E761-417F-BD8C-583B85FF411C)
Removing device Apple Watch Series 2 - 38mm (A9086DDA-8150-4FCD-AD5C-0197E1BD7799)
Removing device Apple Watch Series 2 - 42mm (15FBCE5A-B866-4FDC-B5DA-8003EBFB2A38)
Creating ["iPhone 4s", "com.apple.CoreSimulator.SimDeviceType.iPhone-4s"] for iOS version 10.1
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating ["iPhone 5", "com.apple.CoreSimulator.SimDeviceType.iPhone-5"] for iOS version 10.1
Creating ["iPhone 5s", "com.apple.CoreSimulator.SimDeviceType.iPhone-5s"] for iOS version 10.1
Creating ["iPhone 6", "com.apple.CoreSimulator.SimDeviceType.iPhone-6"] for iOS version 10.1
Creating ["iPhone 6 Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus"] for iOS version 10.1
Creating ["iPhone 6s", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s"] for iOS version 10.1
Creating ["iPhone 6s Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus"] for iOS version 10.1
Creating ["iPhone 7", "com.apple.CoreSimulator.SimDeviceType.iPhone-7"] for iOS version 10.1
Creating ["iPhone 7 Plus", "com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus"] for iOS version 10.1
Creating ["iPhone SE", "com.apple.CoreSimulator.SimDeviceType.iPhone-SE"] for iOS version 10.1
Creating ["iPad 2", "com.apple.CoreSimulator.SimDeviceType.iPad-2"] for iOS version 10.1
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating ["iPad Retina", "com.apple.CoreSimulator.SimDeviceType.iPad-Retina"] for iOS version 10.1
Creating ["iPad Air", "com.apple.CoreSimulator.SimDeviceType.iPad-Air"] for iOS version 10.1
Creating ["iPad Air 2", "com.apple.CoreSimulator.SimDeviceType.iPad-Air-2"] for iOS version 10.1
Creating ["iPad Pro (9.7-inch)", "com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-"] for iOS version 10.1
Creating ["iPad Pro (12.9-inch)", "com.apple.CoreSimulator.SimDeviceType.iPad-Pro"] for iOS version 10.1
Creating ["Apple TV 1080p", "com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p"] for tvOS version 10.0
Creating ["Apple Watch - 38mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm"] for watchOS version 3.1
Creating ["Apple Watch - 42mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm"] for watchOS version 3.1
Creating ["Apple Watch Series 2 - 38mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm"] for watchOS version 3.1
Creating ["Apple Watch Series 2 - 42mm", "com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm"] for watchOS version 3.1
Creating device pair of 04C44F6A-F8DB-4D15-80F5-11F8DF148EA9 and A39245F3-9F40-4992-AB87-03A74832196C
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Unable to pair devices
At least one of the requested devices is already paired with the maximum number of supported devices and cannot accept another pairing.
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | true                                            |
| Xcode Path          | /Applications/Xcode_8.1.app/Contents/Developer/ |
| Xcode Version       | 8.1                                             |
| Git                 | git version 2.10.2                              |
| Installation Source | /Users/zev/.rvm/gems/ruby-2.2.4/bin/fastlane    |
| Host                | Mac OS X 10.12.1 (16B2555)                      |
| Ruby Lib Dir        | /Users/zev/.rvm/rubies/ruby-2.2.4/lib           |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.96.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Padiddle") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    snapshot
    gym(scheme: "Padiddle") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Pull dSYM files from Apple and upload them to Crashlytics."
  desc "This is so we can get symbolicated crash reports even when using Bitcode."
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.zeveisenberg.Padiddle" # The bundle identifier of your app
apple_id "zev@zeveisenberg.com" # Your Apple email address

team_id "2KJHM26Y46"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.54.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bundler                   | 1.13.6       |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.0       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.3        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.1.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.8        |
</details>

*generated on:* **2016-11-09**
</details>

**Comment by hjanuschka** [comment]
`SNAPSHOT_FORCE_DELETE=1 snapshot reset_simulators`  should do it 👍

**Comment by ZevEisenberg** [comment]
@hjanuschka that worked! Thanks. It would still be nice if there were a discoverable option via `snapshot --help`.

**Comment by hjanuschka** [comment]
@ZevEisenberg  PR is here: https://github.com/fastlane/fastlane/pull/6954

enables `snapshot reset_simulators --force`

**Comment by KrauseFx** [comment]
Yeah, this is implemented now, thanks again @hjanuschka 👍
