### ISSUE TITLE
Output buffering issues in Jenkins

### ISSUE THREAD

**Issue by xfreebird** [fastlane/fastlane#693]
It seems that the output of ```fastlane``` suffers from buffering issues. Something that ```xcpretty``` was suffering in past [#123](https://github.com/supermarin/xcpretty/pull/123).

When there are actions that make little output but take a lot of time to execute, the printed content appears in Jenkins only when there are additional outputs printed, enough to trigger a terminal ```flush```.

As resulting the ouput of an action appears in Jenkins only when the action actually finishes and some more text is printed.

**Comment by xfreebird** [comment]
@KrauseFx how can we fix this issue ? Is this something that can be controlled in ```fastlane_core```

**Comment by xfreebird** [comment]
MR https://github.com/fastlane/fastlane_core/pull/41

**Comment by KrauseFx** [comment]
Thanks :+1:
