### ISSUE TITLE
Add gradle params support for Gradle Action

### ISSUE THREAD

**Issue by caipivara** [fastlane/fastlane#6930]
The idea is to be able to call something like:

```$ ./gradlew assemble --stacktrace -PdisablePreDex --no-daemon -Dscan```

Something like:

```
gradle(task: "assemble", params: " --stacktrace -PdisablePredex --no-daemon -Dscan")
```

I don't find a way to add `--PdisablePreDex` and others to _gradle action_.

**Comment by hjanuschka** [comment]
use 
```ruby
gradle(task: "assemble", flags: "--stacktrace -PdisablePredex --no-daemon -Dscan")
```

**Comment by KrauseFx** [comment]
Awesome, thanks @hjanuschka  🚀
