### ISSUE TITLE
Check if the project fulfils iTC fantasies as a first step in deliver

### ISSUE THREAD

**Issue by Czajnikowski** [fastlane/fastlane#6937]
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] Updated fastlane to the latest version

### Issue Description

I'm just disappointed on how iTunes Connect submission process works.
First we need to build the app (I don't know why, but it takes ages for me atm - never mind, it's a different thing), validate the ipa, send it to iTC and then finally [boom](https://twitter.com/czajnikowski/status/796488156904353792):

![ERROR ITMS-](https://cloud.githubusercontent.com/assets/973682/20158754/aebb90e4-a6dc-11e6-80d6-c4893c17136e.png)

Sometimes iTC reports some hard to figure issues like signing/linker issues, but I believe sometimes we can save ourselves from this kind of disappointments (ITMS-90022, 90474, 90475...) and implement a check for them as an early step in `deliver`

**Comment by KrauseFx** [comment]
Do you know a way to verify a build beforehand?

**Comment by Czajnikowski** [comment]
It's a bit problematic, as app icon info is holed up in .pbxproj.

Here's how it looks like:

```
AE7F971F1D9BE22D00AAD171 /* Release */ = {
			isa = XCBuildConfiguration;
			baseConfigurationReference = 4214683F37560DD4F312880D /* Pods-Annotations.release.xcconfig */;
			buildSettings = {
				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
				DEVELOPMENT_TEAM = 47872CSHA2;
				INFOPLIST_FILE = Recall/Info.plist;
				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
				PRODUCT_BUNDLE_IDENTIFIER = com.mczarnik.Annotations;
				PRODUCT_NAME = "$(TARGET_NAME)";
				SWIFT_VERSION = 3.0;
			};
			name = Release;
		};
```

We'll need to get `ASSETCATALOG_COMPILER_APPICON_NAME` and check if any of target's .xcassets file has the necessary icon files.

**Comment by KrauseFx** [comment]
It's never a good idea to do validation yourself, as validation rules change and it's hard to keep them in sync. Instead we should always rely on Apple's verification process. If you find a faster way to verify the `ipa` with Apple's rules, let me know, however I don't think that's possible.
