### ISSUE TITLE
Cannot build a "Command Line Tool" project.

### ISSUE THREAD

**Issue by rewislam** [fastlane/fastlane#6944]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to build a "Command Line Tool" project using fastlane, however it seems it expects a mac app.

Would be great if this was possible.

<details><summary>Crash stack</summary>

```

platform :mac do
  lane :build do
    gym(scheme: "CloverReportJoin", output_name: "CloverReportJoin")
  end
end

/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Couldn't find application in '/Users/Bob/Library/Developer/Xcode/Archives/2016-11-10/CloverReportJoin 2016-11-10 12.55.41.xcarchive' (FastlaneCore::Interface::FastlaneCrash)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.12.0/lib/gym/runner.rb:161:in `copy_mac_app'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.12.0/lib/gym/runner.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/gym-1.12.0/lib/gym/manager.rb:14:in `work'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/actions/gym.rb:24:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/fast_file.rb:140:in `method_missing'
	from Fastfile:5:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:69:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:257:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/commands_generator.rb:31:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.107.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1108)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.106.2"
default_platform :mac
platform :mac do
  lane :build do
    gym(scheme: "CloverReportJoin", output_name: "CloverReportJoin")
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.dashlane.cloverreportjoin" # The bundle identifier of your app
apple_id "rew.islam@dashlane.com" # Your Apple email address

team_id "4N836T6WLM"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.3   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.10.0  | ✅ Up-To-Date  |
| fastlane            | 1.107.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| multipart-post            | 2.0.0   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| dotenv                    | 2.0.2   |
| net-ssh                   | 3.0.1   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.1.0   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.10 |
| slack-notifier            | 1.4.0   |
| rouge                     | 1.10.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.6.3   |
| addressable               | 2.3.8   |
| xcode-install             | 2.0.2   |
| word_wrap                 | 1.0.0   |
| bundler                   | 1.12.5  |
| colored                   | 1.2     |
| credentials_manager       | 0.16.2  |
| multi_xml                 | 0.5.5   |
| unf_ext                   | 0.0.7.1 |
| unf                       | 0.1.4   |
| domain_name               | 0.5.25  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| mime-types                | 2.6.2   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.11.2  |
| logging                   | 2.0.0   |
| jwt                       | 1.5.2   |
| memoist                   | 0.12.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.2   |
| googleauth                | 0.5.1   |
| thor                      | 0.19.1  |
| httpclient                | 2.7.1   |
| google-api-client         | 0.9.3   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.4   |
| tzinfo                    | 1.2.2   |
| minitest                  | 5.5.1   |
| activesupport             | 4.2.0   |
| babosa                    | 1.0.2   |
| excon                     | 0.45.4  |
| gh_inspector              | 1.0.2   |
| fastlane_core             | 0.55.0  |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.1.1   |
| xcodeproj                 | 1.4.0   |
</details>

*generated on:* **2016-11-10**
</details>

**Comment by TKBurner** [comment]
@rewislam Hi! Hope you are doing well! We don't currently support command line projects, but if you could let me know a little bit more about your requirements, I can mark this as a feature request. Thanks!

**Comment by brockboland** [comment]
I ran into that very problem yesterday. In case anyone wants more data for this in the future, here's the code and CI output:

- https://github.com/vokal/Cat2Cat/pull/36
- https://travis-ci.org/vokal/Cat2Cat/jobs/174922173

For the time being, I'm using `xcodebuild`

**Comment by rewislam** [comment]
Hi @TKBurner we're using fastlane throughout our projects (our CI heavily relies on it). While most of our work involves iOS and Mac apps, we do sometimes also create Command Line Tools which we'd like to serve from our CI as built products. Ideally it would be awesome to simple continue to use fastlane to do this rather than call xcodebuild commands directly.

**Comment by hjanuschka** [comment]
@rewislam @brockboland @TKBurner 
here is a PR https://github.com/fastlane/fastlane/pull/7005 trying to add commandline app support.

anyone of you can try this?

**Comment by TKBurner** [comment]
@hjanuschka As always we really appreciate it! The team will take a look and work with you on the PR 👍 👍 💯
