### ISSUE TITLE
fastlane_require 'posix/spawn' Unable to resolve dependency

### ISSUE THREAD

**Issue by bootstraponline** [fastlane/fastlane#6951]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane require fails on posix spawn. The gem is called `posix-spawn`.

```
fastlane_require 'posix/spawn'
```

```
 `add_always_install': [!] Unable to resolve dependency: user requested 'posix/spawn (>= 0)' (Gem::UnsatisfiableDependencyError)
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.12.1                                            |
| Ruby                | 2.3.1                                              |
| Bundler?            | false                                              |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/        |
| Xcode Version       | 8.1                                                |
| Git                 | git version 2.10.1                                 |
| Installation Source | /Users/user/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                         |
| Ruby Lib Dir        | /Users/user/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
---

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| xcode-install             | 2.0.2        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| colored                   | 1.2          |
| babosa                    | 1.0.2        |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.12.5       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.11       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| growl                     | 1.0.3        |
| io-console                | 0.4.6        |
| excon                     | 0.54.0       |
| plist                     | 3.2.0        |
| xcodeproj                 | 1.3.1        |
| claide                    | 1.0.1        |
</details>

*generated on:* **2016-11-10**
</details>

**Comment by KrauseFx** [comment]
Did this work before? Does it work when you use `require` instead of `fastlane_require`?
Can you share the complete output with stack trace?

**Comment by bootstraponline** [comment]
> Did this work before?

No.

> Does it work when you use require instead of fastlane_require?

Yes, require works fine. Only fastlane_require breaks.

> Can you share the complete output with stack trace?

Sure, here is the complete Fastfile that can repro the issue.

```ruby
fastlane_version "1.108.0"

default_platform :android

platform :android do
  desc "Runs all the requires"
  lane :test do
    # require 'posix/spawn'
    fastlane_require 'posix/spawn'
  end

end
```

```
fastlane test
[08:06:34]: -------------------------------------------------
[08:06:34]: --- Step: Verifying required fastlane version ---
[08:06:34]: -------------------------------------------------
[08:06:34]: Your fastlane version 1.108.0 matches the minimum requirement of 1.108.0  ✅
[08:06:34]: ------------------------------
[08:06:34]: --- Step: default_platform ---
[08:06:34]: ------------------------------
[08:06:34]: Driving the lane 'android test' 🚀
[08:06:34]: Installing Ruby gem 'posix/spawn'...
[08:06:35]: Variable Dump:
[08:06:35]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android test"}
[08:06:35]: Unable to resolve dependency: user requested 'posix/spawn (>= 0)'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

[08:06:35]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane_require 'posix/spawn' Unable to resolve dependency
   https://github.com/fastlane/fastlane/issues/6951 [open] 1 💬
   11 hours ago

/Users/user/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/resolver/installer_set.rb:71:in `add_always_install': [!] Unable to resolve dependency: user requested 'posix/spawn (>= 0)' (Gem::UnsatisfiableDependencyError)
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:194:in `install_gem'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/fastlane_require.rb:23:in `install_gem_if_needed'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/fast_file.rb:189:in `fastlane_require'
	from Fastfile:22:in `block (2 levels) in parsing_binding'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/runner.rb:45:in `execute'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/commands_generator.rb:69:in `block (2 levels) in run'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.55.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/commands_generator.rb:266:in `run'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/commands_generator.rb:31:in `start'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-1.108.0/bin/fastlane:5:in `<top (required)>'
	from /Users/user/.rbenv/versions/2.3.1/bin/fastlane:22:in `load'
	from /Users/user/.rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'
```

**Comment by mcactive** [comment]
Having the same issue with `fastlane_require 'open-uri'`

Just normal `require 'open-uri'` works..

`[09:18:47]: Installing Ruby gem 'open-uri'...

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/roadmap/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/resolver/installer_set.rb:71:in `add_always_install': [!] Unable to resolve dependency: user requested 'open-uri (>= 0)' (Gem::UnsatisfiableDependencyError)
	from /Users/roadmap/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:474:in `resolve_dependencies'
	from /Users/roadmap/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:194:in `install_gem'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/fastlane_require.rb:23:in `install_gem_if_needed'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/fast_file.rb:189:in `fastlane_require'
	from Fastfile:1:in `parsing_binding'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/fast_file.rb:54:in `eval'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/fast_file.rb:54:in `block in parse'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/fast_file.rb:43:in `chdir'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/fast_file.rb:43:in `parse'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/fast_file.rb:33:in `initialize'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/lane_manager.rb:12:in `new'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/commands_generator.rb:69:in `block (2 levels) in run'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.55.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/commands_generator.rb:266:in `run'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/commands_generator.rb:31:in `start'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/roadmap/.rvm/gems/ruby-2.3.0@global/gems/fastlane-1.108.0/bin/fastlane:5:in `<top (required)>'
	from /Users/roadmap/.rvm/rubies/ruby-2.3.0/bin/fastlane:22:in `load'
	from /Users/roadmap/.rvm/rubies/ruby-2.3.0/bin/fastlane:22:in `<main>'`

**Comment by TKBurner** [comment]
@bootstraponline @mcactive Thanks for sharing this! I've reached out to the core team to have them take a look. Thanks!

**Comment by mfurtak** [comment]
Hi @bootstraponline - thanks for the report :smile:

As `fastlane_require` is written right now, it doesn't appear to me to be a drop-in replacement for Ruby's `require`. Meaning, you shouldn't use `fastlane_require` everywhere you'd normally use `require`.

`fastlane_require` tries to ensure that a Gem matching the provided name is installed before attempting to later require it. This doesn't make sense for Ruby system-provided libraries like `posix/spawn`. `fastlane_require` seems to be related to the _fastlane_ plugin system. @KrauseFx Do you have any more context about it? Is it intended for user use at all?

@bootstraponline can you share how/where you got the idea to use `fastlane_require` in this way?

Thanks! 👍

**Comment by bootstraponline** [comment]
> This doesn't make sense for Ruby system-provided libraries like posix/spawn

[posix-spawn](https://github.com/rtomayko/posix-spawn) is not a system library.

> @bootstraponline can you share how/where you got the idea to use fastlane_require in this way?

Fastlane is telling people to break their code...

 > fastlane
[17:02:20]: You require a gem, please call `fastlane_require 'posix/spawn'` before to ensure the gem is installed

This is a bug in `fastlane_require` related to gem names. Fastlane is not able to determine that `posix/spawn` is a valid require for the `posix-spawn` gem. This fastfile reproduces the problem:

```ruby
fastlane_version "1.108.0"
default_platform :android
platform :android do
  desc "Runs all the requires"
  lane :test do
    # require 'posix/spawn'
    require 'posix/spawn'
  end
end
```

**Comment by mfurtak** [comment]
Thanks for the clarifications - my initial tests to try to understand were insufficient! 👍

**Comment by bootstraponline** [comment]
If you look at [posix-spawn.rb](https://github.com/rtomayko/posix-spawn/blob/master/lib/posix-spawn.rb) it just runs `require "posix/spawn"` so there are two valid ways to require the gem.

My work around for now is to do ` fastlane_require 'posix-spawn'` instead of `fastlane_require 'posix/spawn'`. Both work with regular require. The bug is that both should also work with fastlane_require.

**Comment by farwayer** [comment]
`fastlane_require 'yaml'` doesn't work also
