### ISSUE TITLE
Uncaught Exception: Couldn't posix_spawn: error 7

### ISSUE THREAD

**Issue by suihan** [fastlane/fastlane#6956]
### Issue Description
when I use fastlane to create Inhouse package，sometimes it fail with few info，like that：

![image](https://cloud.githubusercontent.com/assets/5337010/20214268/0aebb030-a848-11e6-96fe-b79f7a636200.png)

I try to google to find solution bug got nothing 

[INSERT OUTPUT HERE]

### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.12                                              |
| Ruby                | 2.2.4                                              |
| Bundler?            | false                                              |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/        |
| Xcode Version       | 8.1                                                |
| Git                 | git version 2.9.3 (Apple Git-75)                   |
| Installation Source | /Users/mogujie/.rvm/rubies/ruby-2.2.4/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                            |
| Ruby Lib Dir        | /Users/mogujie/.rvm/rubies/ruby-2.2.4/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                        |

[INSERT OUTPUT HERE]

**Comment by suihan** [comment]
### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.12                                              |
| Ruby                | 2.2.4                                              |
| Bundler?            | false                                              |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/        |
| Xcode Version       | 8.1                                                |
| Git                 | git version 2.9.3 (Apple Git-75)                   |
| Installation Source | /Users/mogujie/.rvm/rubies/ruby-2.2.4/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                            |
| Ruby Lib Dir        | /Users/mogujie/.rvm/rubies/ruby-2.2.4/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                        |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.102.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "120"
#    cocoapods
#   sh "pod update"   
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Mogujie4iPhone") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Mogujie4iPhone") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want
  lane :Inhouse do
    gym(scheme: "Mogujie4iPhone-WithoutWatch",use_legacy_build_api:true,output_directory:"./build",archive_path:"./build/Mogujie4iPhone.xcarchive",configuration:"CI",provisioning_profile_path:"./provisions/84da0b16-3228-4a9d-9039-9f3d2f9c244e.mobileprovision")
  end
  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.juangua.mogujie" # The bundle identifier of your app
apple_id "mogu.iphone@mogujie.com" # Your Apple email address

team_id "X8LV58VH9V"  # Developer Portal Team ID

for_lane :Inhouse do
  app_identifier "com.juangua.mogujiedev"
  apple_id "juangua.iphone@mogujie.com"
  team_id "MEU26PKGC2"
end
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date        |
| deliver             | 1.15.0  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.3   | 🚫 Update availaible |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.0  | ✅ Up-To-Date        |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | 🚫 Update availaible |
| screengrab          | 0.5.5   | ✅ Up-To-Date        |
| fastlane            | 1.107.0 | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.1        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.55.0       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
</details>


*generated on:* **2016-11-11**
</details>

**Comment by suihan** [comment]
for more info,the log is end with touch -c  ...dsym action, maybe it is break when calculate the saving time?:

Touch /Users/***/Library/Developer/Xcode/DerivedData/***-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/***-WithoutWatch/BuildProductsPath/CI-iphoneos/***.app.dSYM
    cd /Users/***/Jenkins/workspace/***
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/***/.rvm/rubies/ruby-2.2.4/bin:/Users/mogujie/.rvm/gems/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/touch -c /Users/***/Library/Developer/Xcode/DerivedData/***-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/***-WithoutWatch/BuildProductsPath/CI-iphoneos/***.app.dSYM

**Comment by suihan** [comment]
on the same machine,it maybe work success,but sometimes fail, it confuse me

**Comment by hjanuschka** [comment]
try disabling: `use_legacy_build_api`  in most cases this is the culprit.
otherwise it seems like a xcode crash - can you build via xcode?

**Comment by suihan** [comment]
I had try remove use_legacy_build_api setting,and execute fastlane Inhouse,but the result is fail too.and it can be build via Xcode

**Comment by suihan** [comment]
Touch /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app
    cd /Users/mogujie/Jenkins/workspace/Mogujie4iPhone
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/mogujie/.rvm/rubies/ruby-2.2.4/bin:/Users/mogujie/.rvm/gems/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/touch -c /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app

ProcessProductPackaging "" /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/IntermediateBuildFilesPath/Mogujie4iPhone.build/CI-iphoneos/Mogujie4iPhone-WithoutWatch.build/Mogujie4iPhone.app.xcent
    cd /Users/mogujie/Jenkins/workspace/Mogujie4iPhone
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/mogujie/.rvm/rubies/ruby-2.2.4/bin:/Users/mogujie/.rvm/gems/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"


Entitlements:

{
    "application-identifier" = "MEU26PKGC2.com.juangua.mogujiedev";
    "com.apple.developer.team-identifier" = MEU26PKGC2;
    "get-task-allow" = 0;
    "keychain-access-groups" =     (
        "MEU26PKGC2.com.juangua.mogujiedev"
    );
}


    builtin-productPackagingUtility -entitlements -format xml -o /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/IntermediateBuildFilesPath/Mogujie4iPhone.build/CI-iphoneos/Mogujie4iPhone-WithoutWatch.build/Mogujie4iPhone.app.xcent

CodeSign /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app
    cd /Users/mogujie/Jenkins/workspace/Mogujie4iPhone
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/mogujie/.rvm/rubies/ruby-2.2.4/bin:/Users/mogujie/.rvm/gems/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

Signing Identity:     "iPhone Distribution: Hangzhou Juangua Network Co.,Ltd."
Provisioning Profile: "Mogujie4iPhone_Juangua_Inhouse"
                      (84da0b16-3228-4a9d-9039-9f3d2f9c244e)

    /usr/bin/codesign --force --sign B4C3B01B36692802B3C018A6D51BC25C1A40F580 --entitlements /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/IntermediateBuildFilesPath/Mogujie4iPhone.build/CI-iphoneos/Mogujie4iPhone-WithoutWatch.build/Mogujie4iPhone.app.xcent --timestamp=none /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app

Validate /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app
    cd /Users/mogujie/Jenkins/workspace/Mogujie4iPhone
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/mogujie/.rvm/rubies/ruby-2.2.4/bin:/Users/mogujie/.rvm/gems/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app

Touch /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/BuildProductsPath/CI-iphoneos/Mogujie4iPhone.app.dSYM
    cd /Users/mogujie/Jenkins/workspace/Mogujie4iPhone
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/mogujie/.rvm/rubies/ruby-2.2.4/bin:/Users/mogujie/.rvm/gems/ruby-2.2.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /usr/bin/touch -c /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/BuildProductsPath/CI-iphoneos/Mogujie4iPhone.app.dSYM

**Comment by suihan** [comment]
the whole log is too much, here is the last part,is it useful?

**Comment by suihan** [comment]
after touch dSYM,there is no more log,i do not know what fastlane is doing now,is just break.

**Comment by suihan** [comment]
I use "wc -l" to count the log line,got 107991,it is too big

**Comment by suihan** [comment]
according to the log,the dSYM file had been created,but then something happened

**Comment by hjanuschka** [comment]
@suihan i am just blind guessing here, lets see if we can break it down one by one.
can you check if you have "Custom Scripts" running - under "Build Phase" - and disable one after another everytime testing if it works?

maybe there is one script - with a `*` as a parameter wich results in too many arguments , wich is a possibility for the spawn_error (according to mach docs)

**Comment by suihan** [comment]
ok,i will try it

**Comment by suihan** [comment]
we have a custom script like that:

if command -v convert >/dev/null 2>&1; then
    echo "do not copy ci icon"
else
    echo "copy ci icon"
    if [ ${CONFIGURATION} == "CI" ]
    then
            cp Mogujie4iPhone/TestIcon/* Mogujie4iPhone/Images.xcassets/AppIcon.appiconset/
    fi
fi

I will try to remove it and execute fastlane first.

**Comment by suihan** [comment]
not good,when I run via jenkins,it seems custom script is done:


eqcyrotwhhexwwbwnomyrifxqtlm/TRAE_iOS_StaticLib-Prefix.pch.pch: No such file or directory[0m
[33m/data/rdm/projects/22380/app/TRAE_Lib/TRAE_StaticLib/build/TRAE_iOS_StaticLib-Prefix-ehakbxkmwzfygfarurttjvpojorg/TRAE_iOS_StaticLib-Prefix.pch.pch: No such file or directory[0m
[33mUnsupported attribute form in cloneAttribute. Dropping.[0m
[33mUnsupported attribute form in cloneAttribute. Dropping.[0m
[33mUnsupported attribute form in cloneAttribute. Dropping.[0m
[33mUnsupported attribute form in cloneAttribute. Dropping.[0m
[33mUnsupported attribute form in cloneAttribute. Dropping.[0m
[33mUnsupported attribute form in cloneAttribute. Dropping.[0m
[33mUnsupported attribute form in cloneAttribute. Dropping.[0m
[33m▸[0m [39;1mRunning script[0m '[CP] Embed Pods Frameworks'
[33m▸[0m [39;1mRunning script[0m '[CP] Copy Pods Resources'
[33m▸[0m [39;1mTouching[0m Mogujie4iPhone.app
[33m▸[0m [39;1mSigning[0m /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app
[33m▸[0m [39;1mTouching[0m Mogujie4iPhone.app.dSYM
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: Couldn't posix_spawn: error 7
Stack:
0   __exceptionPreprocess (in CoreFoundation)
1   objc_exception_throw (in libobjc.A.dylib)
2   +[NSException raise:format:] (in CoreFoundation)
3   -[NSConcreteTask launchWithDictionary:] (in Foundation)
4   __46-[IDEShellScriptExecutionActionOperation main]_block_invoke_2.229 (in IDEStandardExecutionActionsCore)
5   ___DVTAsyncPerformBlockOnMainRunLoop_block_invoke (in DVTFoundation)
6   __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ (in CoreFoundation)
7   __CFRunLoopDoBlocks (in CoreFoundation)
8   __CFRunLoopRun (in CoreFoundation)
9   CFRunLoopRunSpecific (in CoreFoundation)
10   CFRunLoopRun (in CoreFoundation)
11   -[Xcode3CommandLineBuildTool _buildWithTimingSection:] (in Xcode3Core)
12   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
13  0x000000010c06d202 (in xcodebuild)
14   start (in libdyld.dylib)

sh: line 1: 55022 Abort trap: 6           xcodebuild -workspace ./Mogujie4iPhone.xcworkspace -scheme Mogujie4iPhone-WithoutWatch -configuration 'CI' -destination 'generic/platform=iOS' -archivePath

**Comment by suihan** [comment]
I had remove all custom script，the left looks created by cocoapods：
![image](https://cloud.githubusercontent.com/assets/5337010/20235621/bd7572b6-a8d1-11e6-8adb-60e10b2a62bd.png)

**Comment by suihan** [comment]
![image](https://cloud.githubusercontent.com/assets/5337010/20236025/2a492c12-a8e0-11e6-8c41-8a184db617c2.png)
the same code,if I execute fastlane local,it success,and it always fail on server,maybe zip error?the dSYM file is 422M size.

**Comment by suihan** [comment]
[17:13:15]: ▸ /var/folders/rw/q2c3bg810hj6j_j8kv86pp0r0000gn/T/SchemeScriptAction-UrvDJd: line 2: /usr/bin/python: Argument list too long

**Comment by suihan** [comment]
I update fastlane to last version , it seems fixed the issue

**Comment by suihan** [comment]
here is the new log,when I execute "fastlane Inhouse",the logs like below,but if I run via jenkins,it turn tobe fail.
~~~
[20:15:15]: ▸ Touching Mogujie4iPhone.app
[20:15:15]: ▸ Signing /Users/mogujie/Library/Developer/Xcode/DerivedData/Mogujie4iPhone-ddjjjuzjryqajchchcbdfvtaqtsc/Build/Intermediates/ArchiveIntermediates/Mogujie4iPhone-WithoutWatch/InstallationBuildProductsLocation/Applications/Mogujie4iPhone.app
[20:15:17]: ▸ Touching Mogujie4iPhone.app.dSYM
[20:15:18]: ▸ /var/folders/h_/700r8wts0vd6s2_nsxy1klhm0000gn/T/SchemeScriptAction-7EnNVx: line 2: /usr/bin/python: Argument list too long
[20:15:19]: ▸ Archive Succeeded
[20:15:20]: Successfully stored the archive. You can find it in the Xcode Organizer.
[20:15:20]: $ /usr/bin/xcrun /tmp/PackageApplication4Gym -v ./build/Mogujie4iPhone.xcarchive/Products/Applications/Mogujie4iPhone.app -o '/var/folders/h_/700r8wts0vd6s2_nsxy1klhm0000gn/T/gym_output20161112-27504-1n790lc/Mogujie4iPhone.ipa' exportFormat ipa --embed './provisions/84da0b16-3228-4a9d-9039-9f3d2f9c244e.mobileprovision' 
[20:15:32]: $ zip --recurse-paths '/var/folders/h_/700r8wts0vd6s2_nsxy1klhm0000gn/T/gym_output20161112-27504-1n790lc/Mogujie4iPhone.ipa' SwiftSupport > /dev/null
[20:15:33]: Compressing 1 dSYM(s)
[20:15:33]: $ cd '/Users/mogujie/Jenkins/workspace/Mogujie4iPhone/build/Mogujie4iPhone.xcarchive/dSYMs' && zip -r '/Users/mogujie/Jenkins/workspace/Mogujie4iPhone/build/Mogujie4iPhone.app.dSYM.zip' *.dSYM
[20:15:50]: ▸   adding: Mogujie4iPhone.app.dSYM/ (stored 0%)
[20:15:50]: ▸   adding: Mogujie4iPhone.app.dSYM/Contents/ (stored 0%)
[20:15:50]: ▸   adding: Mogujie4iPhone.app.dSYM/Contents/Info.plist (deflated 52%)
[20:15:50]: ▸   adding: Mogujie4iPhone.app.dSYM/Contents/Resources/ (stored 0%)
[20:15:50]: ▸   adding: Mogujie4iPhone.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
[20:15:50]: ▸   adding: Mogujie4iPhone.app.dSYM/Contents/Resources/DWARF/Mogujie4iPhone (deflated 74%)

[20:15:50]: Successfully exported and compressed dSYM file
[20:15:50]: Successfully exported and signed the ipa file:
[20:15:50]: /Users/mogujie/Jenkins/workspace/Mogujie4iPhone/build/Mogujie4iPhone.ipa

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 1467        |
+------+-------------------------------------+-------------+

**Comment by suihan** [comment]
what can I do now?is there anything I can do?
maybe because my project is too heavy?how to fix it?

**Comment by hjanuschka** [comment]
would be interessting what `SchemeScriptAction` is - that invokes a python with a too long arg list - wich is as i think a `*` resolving to too many files - or as it works locally - being run in wrong path.

have you tried wipeing all data from the jenkins user?

**Comment by suihan** [comment]
so how can I check where SchemeScriptAction code is？may I remove some code from fastlane？It seems some code is unnecessary and have some bug。

**Comment by suihan** [comment]
or how to wipe all data from the jenkisn user?

**Comment by hjanuschka** [comment]
i still bet on any "build phase" script - have you checked all targets?
the error states "/usr/bin/python: Argument list too long" so there must be a script wich invokes python, with too many (>1000) arguments.   this can only happen if there is a `*`  in the arg list, wich resolves to more than 1000 files.

i am not a jenkins ninja, but i think you can find a folder on the ci server where the sources are checked out, and remove them?

**Comment by suihan** [comment]
yeah，I had check all run phase，there is no python code，only shell。maybe because the sourcefile is overthan 1000？

**Comment by suihan** [comment]
I archive with Xcode and it success always.

**Comment by suihan** [comment]
I think I had found it，there is a Python script In scheme script，which can only be found via edit scheme. so that is why I had check all my build phases and nothing help. Thank you for your help.

**Comment by suihan** [comment]
I think I had found it，My project had a scheme script，which was not in build phases，but only can be found by edit scheme，and the python run error will cause the issue. 
Furthermore,I think the python script push some wanning which made fastlane thought it is been failed.

**Comment by hjanuschka** [comment]
so you managed to solve it? - can you close the issue then?

**Comment by suihan** [comment]
ok
