### ISSUE TITLE
fastlane sometimes stop in loadding status.

### ISSUE THREAD

**Issue by suihan** [fastlane/fastlane#6957]
### Issue Description
  fastlane sometimes keep loadding but not fail,it may take 5 hours and still in loadding status.
my question is that,what does fastlane do when it output the info? if fastlane should now visit some foreign url, it maybe fail in china. so may i set the fastlane not to visit the site？if it is not necessary.thank you.

![image](https://cloud.githubusercontent.com/assets/5337010/20216837/bef2b2f4-a857-11e6-9143-69a82ffafbc2.png)

[INSERT OUTPUT HERE]

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12                                            |
| Ruby                | 2.2.4                                            |
| Bundler?            | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.1                                              |
| Git                 | git version 2.9.3 (Apple Git-75)                 |
| Installation Source | /Users/mogujie/.rvm/gems/ruby-2.2.4/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                          |
| Ruby Lib Dir        | /Users/mogujie/.rvm/rubies/ruby-2.2.4/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                      |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | 🚫 Update availaible |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| deliver             | 1.15.0  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.3   | 🚫 Update availaible |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.0  | ✅ Up-To-Date        |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | 🚫 Update availaible |
| screengrab          | 0.5.2   | 🚫 Update availaible |
| fastlane            | 1.107.0 | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.12.5       |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.1        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.0        |
| xcodeproj                 | 1.3.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.4.0        |
| xcode-install             | 2.0.4        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.53.0       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.3      |
| google-api-client         | 0.9.13       |
</details>

*generated on:* **2016-11-11**
</details>

**Comment by hjanuschka** [comment]
not recommended - but you can add - at top of your fastfile:

```
ENV["FASTLANE_SKIP_UPDATE_CHECK"]=1
```

this should disable update check. as described here -> https://github.com/fastlane/fastlane/blob/0cd59ddaec2671e7434d843698dec5be847f5188/fastlane/README.md#statistics

**Comment by suihan** [comment]
thanks! I will try to use that ENV.
and you means another question I ask for fail reason? I will try it,but we have 2 branches for the project,one can use fastlane successful and another is fail always. I think if I can see what fastlane is doing when break, maybe helps to find the reason

**Comment by suihan** [comment]
I use "wc -l" to count the log line,got 107991,it is too big

**Comment by suihan** [comment]
for this situation，maybe fastlane can add a timeout logic to avoid .
