### ISSUE TITLE
Why snapshot isn't building once

### ISSUE THREAD

**Issue by petitmat** [fastlane/fastlane#6958]
### Issue Description

Hi, I'm doubtful about how Snapshot is working, I don't understand why it needs to recompile the project for each device type. We used previously an intern tool to make our screenshots (using .js) and we now want to adopt fastlane. But this tool needs to build only once and then run this build on different device types... So screenshots take 5 minutes for 4 device types instead of 7 minutes with snapshot.
If someone can enlighten me why fastlane needs it.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.11.6                                           |
| Ruby                | 2.2.4                                             |
| Bundler?            | false                                             |
| Xcode Path          | /Applications/Xcode_7.3.1.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                             |
| Git                 | git version 2.10.0                                |
| Installation Source | /Users/matthieu/.fastlane/bin/bundle/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                        |
| Ruby Lib Dir        | /Users/matthieu/.fastlane/bin/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                        |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.54.0  | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| babosa              | 1.0.2   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.1.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.54.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-11-11**
</details>
</br>

https://github.com/fastlane/fastlane/issues/6891 to understand why my env isn't up to date

**Comment by TKBurner** [comment]
@petitmat Thanks for reaching out. Can you provide your full output so I can take a look? I think this is expected behavior but I'd love to take a look. Thanks!

**Comment by petitmat** [comment]
Hi @TKBurner, 
This issue is related with  https://github.com/fastlane/fastlane/issues/6992

I don't really want to copy/paste my input with all the classes built of my company... I'm just asking why the code is recompiled entirely between all devices (4 times if I want screenshots of iphone 4s, iphone 5s, iphone 6s and iphone 6s plus). And why it isn't compiled once at the beginning and the ipa installed on all these devices...

**Comment by TKBurner** [comment]
@petitmat

 @hjanuschka is going to look into this when he has some time. We are going to track this on #6992. , so closing this issue. Thanks!
