### ISSUE TITLE
FrameIt beginner question

### ISSUE THREAD

**Issue by psamhaber** [fastlane/fastlane#6965]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I want to get frameit to frame my osx app screens (2304x1440px) with either one of the latest macbook frames. I reinstalled fastlane and downloaded the new frames.
Simply running `frameit` on my screens folder results in:    

```
[20:53:43]: Using device frames version 'latest'    
[20:53:43]: Framing screenshot './editorial-detail.png'    
[20:53:43]: Couldn't find template for screenshot type 'Apple MacBook Space Gray'    
[20:53:43]: Please run `frameit download_frames` to download the latest frames    
```    

Looking into `./frameit/device_frames_2/latest` the pngs are there, but offsets.json seems to be missing the following?    
```
"Macbook": {    
      "offset": "+380+128",    
      "width": 2304    
    }
```
Sorry for the basic question– I'm new to git, ruby and all, so any hints and tips on how or what to do would be very much appreciated!
    
### Stack

| Key                 | Value                                                   |
| ------------------- | ------------------------------------------------------- |
| OS                  | 10.12.1                                                 |
| Ruby                | 2.1.3                                                   |
| Bundler?            | false                                                   |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version       | 8.1                                                     |
| Git                 | git version 2.9.3 (Apple Git-75)                        |
| Installation Source | /Users/ps/.rvm/rubies/ruby-2.1.3/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2553a)                             |
| Ruby Lib Dir        | /Users/ps/.rvm/rubies/ruby-2.1.3/lib          |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |
`

**Comment by TKBurner** [comment]
@psamhaber Check out the steps here: https://github.com/fastlane/fastlane/tree/master/frameit#mac

You do need to provide the offsets yourself. Thanks!

**Comment by psamhaber** [comment]
@TKBurner already did, thanks. Opened another issue with more specific description here: #7782
