### ISSUE TITLE
Why no screenshot even with just 1 failure

### ISSUE THREAD

**Issue by tinder-ayu** [fastlane/fastlane#6966]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
"If any error occurs while running the snapshot script on a device, that device will not have any screenshots" 

Can you tell us the logic behind this? For each language, i get at least 1 random failure due to screens being stuck. why are there no screenshots taken when only 1 error occur? Why cant we export the rest of the screenshots? Any testing framework is prone to have setup issues here and there.

"By default snapshot automatically retries running UI Tests if they fail."
Snapshot actually tries the entire language over again with just one failure, why don't we just re-run the ones that failed? Seems inefficient when you have a large suite of tests. 

Why is this 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by tinder-ayu** [comment]
fastlane env: 

/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2278:in `check_version_conflict': can't activate json-2.0.2, already activated json-1.8.3 (Gem::LoadError)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1404:in `activate'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.55.0/lib/fastlane_core.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane.rb:1:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.102.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

**Comment by TKBurner** [comment]
@tinder-ayu Can you uninstall the json gem and then reinstall version 1.8.3 thanks!
