### ISSUE TITLE
Possible to set "Use 5.5 Display" setting when uploading screenshots?

### ISSUE THREAD

**Issue by ChrisVolentine** [fastlane/fastlane#6969]
I have a very large number of existing apps that don't have the "Use 5.5 Display" setting checked. I am wanting to update screenshots for all of these apps.

Is it possible to upload only iPhone 6s Plus and iPad Pro screenshots, and automatically set the remaining to use those 5.5/12 inch displays?

**Comment by ChrisVolentine** [comment]
In case anyone has the same issue - solved this by creating a Spaceship script which clears existing screenshots, sets the "Use x Display" for each screen size, then uses fastlane to deliver the new screenshots:

````
app = Spaceship::Tunes::Application.find("insertbundleidhere")
v = app.edit_version
v.screenshots.each do |language, screenshots|
    screenshots.each do |s|
        v.upload_screenshot!(nil, s.sort_order, s.language, s.device_type)
    end
end
v.save!
v.languages.each { |lang|
    lang['displayFamilies']['value'].each { |d|
        d['scaled']['value'] = true
}}
v.save!
`(cd #{$ios_dir} && fastlane ios deliver)`
````

**Comment by at-daihv** [comment]
@ChrisVolentine 

Please help me, how I can run that script?
