### ISSUE TITLE
Can’t pass options containing a space for all fastlane tools

### ISSUE THREAD

**Issue by 0xced** [fastlane/fastlane#6971]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It looks like there’s a problem parsing option containing spaces. Here are two examples where the part after the space is ignored:

```bash
$ deliver --ipa /System/Library/Automator/Activate\ Fonts.action
[00:21:19]: Error setting value '/System/Library/Automator/Activate' for option 'ipa'
```
or
```bash
$ deliver --ipa '/System/Library/Automator/Activate Fonts.action'
[00:21:35]: Error setting value '/System/Library/Automator/Activate' for option 'ipa'
```

Another example with scan:
```bash
$ ~/.fastlane/bin/scan --device "iPhone 5s"
[00:23:29]: $ xcodebuild -list -workspace ./XCDYouTubeKit\ Demo.xcworkspace
[00:23:35]: $ xcodebuild clean -showBuildSettings -workspace ./XCDYouTubeKit\ Demo.xcworkspace -scheme XCDYouTubeKit\ Framework
[00:23:36]: Ignoring 'iPhone', couldn’t find matching simulator
[00:23:36]: Couldn't find any matching simulators for '["iPhone"]' - falling back to default simulator
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                          |
| ------------------- | ---------------------------------------------- |
| OS                  | 10.11.6                                        |
| Ruby                | 2.2.4                                          |
| Bundler?            | false                                          |
| Xcode Path          | /Applications/Xcode81.app/Contents/Developer/  |
| Xcode Version       | 8.1                                            |
| Git                 | git version 2.9.3                              |
| Installation Source | /Users/0xced/.fastlane/bin/bundle/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                     |
| Ruby Lib Dir        | /Users/0xced/.fastlane/bin/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| babosa              | 1.0.2   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.1.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.55.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-11-12**
</details>

**Comment by 0xced** [comment]
This looks like a bug specific to the self-contained version of fastlane. Tools installed with gem are fine:
```bash
$ ~/.gem/bin/deliver --ipa /System/Library/Automator/Activate\ Fonts.action
[00:36:20]: Error setting value '/System/Library/Automator/Activate Fonts.action' for option 'ipa'

[!] '/System/Library/Automator/Activate Fonts.action' doesn't seem to be an ipa file
```

**Comment by 0xced** [comment]
@ohwutup Any idea where this is coming from?

**Comment by 0xced** [comment]
I found the problem: most of the fastlane tools wrapper scripts forget to quote the argument forwarding, i.e. it should be 
```bash
exec "${DIR}/bundle/bin/bundle-env" deliver "$@"
```
instead of
```bash
exec "${DIR}/bundle/bin/bundle-env" deliver $@
```
Notice the quotes!

**Comment by ohwutup** [comment]
Thanks @0xced we will definitely fix this up ASAP!

**Comment by shadone** [comment]
I just hit this very issue with `gym --workspace "My Project.xcworkspace"`. Is there any update on it?

**Comment by KrauseFx** [comment]
Thanks everyone, looking into the issue now 👍

**Comment by KrauseFx** [comment]
Thanks everyone, we submitted the patch, and will release a new bundle shortly 👍

**Comment by KrauseFx** [comment]
Did you have a chance to try the new bundle? Please let us know if that works for you.

**Comment by shadone** [comment]
I am slightly confused. I tried just now and it seems to work but I haven't upgraded explicitly. So either I cannot reproduce the issue any more or fastlane toolset was autoupdated (I installed it via brew cask).

```
$ gym --version
gym 1.12.1
```
