### ISSUE TITLE
gym cannot find non-latin (greek) scheme from Fastfile

### ISSUE THREAD

**Issue by tbatzakas** [fastlane/fastlane#6974]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to run my lane containing schemes in greek like the one mentioned below "Πορφυρός" I get a message that the scheme cannot be found. If I try to select it from scheme list, gym escapes all characters (and makes a strange escape on accent mark "tonos" ' for "ό" as you can see below).
Then gym seems to run (I tried to copy this escaped string to my Fastfile and seems to work too) only to stop afterwards with the following screen:

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | increment_build_number              | 2           |
| 💥    | gym                                 | 171         |
+------+-------------------------------------+-------------+

[20:52:52]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/fileutils.rb:1570:in `block in fu_each_src_dest': [!] same file: /var/folders/fg/kly4vjyn781fdyj3hb4xsd200000gn/T/gym_output20161112-61810-1yssjmy/Πορφυρός.ipa and /var/folders/fg/kly4vjyn781fdyj3hb4xsd200000gn/T/gym_output20161112-61810-1yssjmy/Πορφυρός.ipa (ArgumentError)

The only way to submit this ipa now is from Organizer.

##### Complete output when running fastlane, including the stack trace and command used

[20:45:22]: Successfully loaded '/Users/xxxx/Documents/iOS/xxx/xxx/fastlane/Gymfile' 📄
[20:45:22]: No values defined in './fastlane/Gymfile'
[20:45:22]: $ xcodebuild -list -workspace ./project.xcworkspace
[20:45:27]: Couldn't find specified scheme 'Πορφυρός'.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | el_GR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.54.0"

platform :ios do
desc "build all apps"
 
  project_file = 'χχχχχ.xcodeproj'
  increment_build_number(xcodeproj: project_file) # version bump

lane :build_all do  
[
"Πορφυρός",
...
...
...
...
...
].each do |scheme_name|
  gym(
    scheme: scheme_name,
    clean: true
  )
deliver(
    force: true,
    skip_screenshots: true,
    skip_metadata: false,
    submit_for_review: true
)
end
end

lane :build_demo do
["xxxxxx", "xxxxxx"].each do |scheme_name|
  gym(
    scheme: scheme_name,
    clean: true
  )
deliver(
    force: true,
    skip_screenshots: true
)
end
end

lane :single_update_submit do
  gym(    	
    workspace: "xxxxxx.xcworkspace",
    clean: true
  )
deliver(
    force: true,
    skip_screenshots: true,
    skip_metadata: false,	
    submit_for_review: true
)
end
lane :single_update_nosubmit do
  gym(
    workspace: "xxxxxx.xcworkspace",
    clean: true
  )
deliver(
    force: true,
    skip_screenshots: true,
    skip_metadata: true,
    submit_for_review: false
)
end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "xxx@xxx.com" # Your Apple email address

team_id "xxxxxx"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.1.2        |
| xcodeproj                 | 1.4.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.13.6       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-11-12**
</details>

**Comment by TKBurner** [comment]
@tbatzakas Thanks for reaching out. I've let the team know about this issue, but I'm not sure how fast it can be prioritized. Can you rename your schemes for the time being? Thanks!

**Comment by tbatzakas** [comment]
of course, that's my current approach and it works just fine. As a matter of fact this is a workaround that causes no issues at all, so I believe that even if this remains unfixed it will be just fine, but at least a warning about non-latin scheme names would help other developers reach a solution quickly.
