### ISSUE TITLE
Documentation for deliver price_tier (Alternate Price Tiers)

### ISSUE THREAD

**Issue by waroo** [fastlane/fastlane#6976]
Further documentation needed for possible values to enter into price_tier.  Current help states:

`-r, --price_tier [VALUE] The price tier of this application`

Some of the examples use --price_tier 0 and --price_tier 5 which makes sense for the standard price tiers.

However, I could not find what values to use when selecting Alternate Price Tier A or B or Alternate Price Tiers 1 - 5.

**Comment by waroo** [comment]
I figured out that Alternate Tier B is value 530

**Comment by JustinJiaDev** [comment]
Just a side note: Alternative Tier A is 510.

**Comment by TKBurner** [comment]
@waroo Are you interested in submitting a PR to update this for us? We'd LOVE that!
