### ISSUE TITLE
Getting 'invalid username and password combination'

### ISSUE THREAD

**Issue by bitops** [fastlane/fastlane#6977]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I set up fastlane on one of my workstations and everything works great. I am able to do a beta build and push it to Hockey without issue. I am now trying to run `fastlane beta` on my other workstation but I keep getting the 'invalid username and password combination' error message. I can't figure out where my password is captured or how to tell fastlane to ask me for it again. fastlane asked me for my password the first time I set it up but isn't asking me for it on this machine. 

I am not sure how to work around this.

### Captured Output

Captured output with `bundle exec fastlane beta --capture_output`.

Command Used: `beta`
<details><summary>Output/Log</summary>

```

[16:40:54]: -------------------------------------------------
[16:40:54]: --- Step: Verifying required fastlane version ---
[16:40:54]: -------------------------------------------------
[16:40:54]: Your fastlane version 1.108.0 matches the minimum requirement of 1.107.0  ✅
[16:40:54]: ------------------------------
[16:40:54]: --- Step: default_platform ---
[16:40:54]: ------------------------------
[16:40:54]: Driving the lane 'ios beta' 🚀
[16:40:54]: -----------------------
[16:40:54]: --- Step: cocoapods ---
[16:40:54]: -----------------------
[16:40:54]: $ bundle exec pod install
[16:40:56]: ▸ Analyzing dependencies
[16:40:56]: ▸ Downloading dependencies
[16:40:56]: ▸ Using Hue (1.3.0)
[16:40:56]: ▸ Using Whisper (3.1.1)
[16:40:56]: ▸ Generating Pods project
[16:40:56]: ▸ Integrating client project
[16:40:57]: ▸ Sending stats
[16:40:57]: ▸ Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.
[16:40:57]: ▸ [!] The `Foo [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Foo/Pods-Foo.debug.xcconfig'. This can lead to problems with the CocoaPods installation
[16:40:57]: ▸ [!] The `Foo [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-Foo/Pods-Foo.release.xcconfig'. This can lead to problems with the CocoaPods installation
[16:40:57]: ▸ - Use the `$(inherited)` flag, or
[16:40:57]: ▸ - Remove the build settings from the target.
[16:40:57]: ▸ - Use the `$(inherited)` flag, or
[16:40:57]: ▸ - Remove the build settings from the target.
[16:40:57]: ------------------------------------
[16:40:57]: --- Step: increment_build_number ---
[16:40:57]: ------------------------------------
[16:40:57]: $ cd /Users/sebastian/src/foo && agvtool next-version -all && cd -
[16:40:57]: ▸ Setting version of project Foo to:
[16:40:57]: ▸ 262.
[16:40:57]: ▸ Also setting CFBundleVersion key (assuming it exists)
[16:40:57]: ▸ Updating CFBundleVersion in Info.plist(s)...
[16:40:57]: ▸ Updated CFBundleVersion in "Foo.xcodeproj/../Foo/Info.plist" to 262
[16:40:57]: ▸ Updated CFBundleVersion in "Foo.xcodeproj/../FooTests/Info.plist" to 262
[16:40:57]: ▸ /Users/sebastian/src/foo
[16:40:58]: ------------------------------
[16:40:58]: --- Step: register_devices ---
[16:40:58]: ------------------------------
[16:40:59]: Variable Dump:
[16:40:59]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta", :BUILD_NUMBER=>"262"}
[16:40:59]: Invalid username and password combination. Used 'sebastian@bitops.io' as the username.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 2           |
| 4    | increment_build_number              | 1           |
| 💥    | register_devices                    | 1           |
+------+-------------------------------------+-------------+

[16:40:59]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
	Invalid username and password combination. Used 'sebastian@bitops.io' as the username.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.12                                              |
| Ruby                | 2.1.1                                              |
| Bundler?            | true                                               |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/        |
| Xcode Version       | 8.0                                                |
| Git                 | git version 2.2.1                                  |
| Installation Source | /Users/sebastian/.rvm/gems/ruby-2.1.1/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                            |
| Ruby Lib Dir        | /Users/sebastian/.rvm/rubies/ruby-2.1.1/lib        |
| OpenSSL Version     | OpenSSL 1.0.1g 7 Apr 2014                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.107.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Hockey"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    register_devices(
      devices: {
        "stuffs" => "UUID-SCRUBBED",        
      }
    )
    match(
      type: "adhoc",
      git_url: "git@github.com:bitops/that-repo-scrubbed.git"
    )
    gym(
      scheme: "Foo",
      workspace: "Foo.xcworkspace",
      use_legacy_build_api: true
    )
    hockey(
      api_token: "HOCKEY_TOKEN"
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Foo",
        workspace: "Foo.xcworkspace")
    deliver(force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "io.bitops.Foo" # The bundle identifier of your app
apple_id "sebastian@bitops.io" # Your Apple email address

team_id "TEAM_ID_SCRUBBED"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bundler                   | 1.12.5       |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.3        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.1.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
</details>

*generated on:* **2016-11-12**
</details>

**Comment by hjanuschka** [comment]
you either have set a ENV variable with wrong password:
 like: `FASTLANE_PASSWORD` or `DELIVER_PASSWORD` - or you have a faulty keychain entry.


you can check that when you go to your "Keychain Acess.app"  and search on all objects for `deliver.sebastian@bitops.io` - you can delete it or change the pw directly from keychain app :)


let me know if this helps you.

**Comment by bitops** [comment]
@hjanuschka that did help, thank you! Removing the `deliver.sebastian@bitops.io` entry from Keychain Access did the trick. However, I would *never* have figured this out if I hadn't filed this issue. 

I think it would be nice to include a helpful error message that suggests this as a fix if the stored username/combo doesn't work.

**Comment by hjanuschka** [comment]
glad it worked, @bitops  i had to look at the source tbh. can you close the issue.
you are right that it should be documented somwhere.
