### ISSUE TITLE
PLAY Store content rating

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#6978]
Will there ever be a fastlane solution for the annoying IARC content rating needed to fill for each app?

Thnkx.

**Comment by prolog3001** [comment]
Thank you.
Can you help some more and link me to instructions how include the output of fastlane env?

**Comment by mychaelgo** [comment]
@prolog3001 it means you must incluce your fastlane env when posting an issue, like this https://github.com/fastlane/fastlane/issues/6982#issue-188994796

**Comment by prolog3001** [comment]
Got it! here:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1108)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :android

platform :android do
  before_all do
     ICON_FOLDER = "5XXX4"
  end

 # desc "Runs all the tests"
 # lane :test do
 #   gradle(task: "test")
 # end

 # desc "Submit a new Beta Build to Crashlytics Beta"
 # lane :beta do
 #  gradle(task: "assembleRelease")
 #  crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
 # end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    #gradle(task: "assembleRelease")
    sh "curl -o ./metadata/android/iw-IL/images/icon.png http://pro548.s3.amazonaws.com/apps/pb/psd9/#{ICON_FOLDER}/Icon-512.png" 
    #supply
    #supply --skip_upload_apk [true]
    #supply --skip_upload_metadata
    #supply --skip_upload_images
    #supply --skip_upload_screenshots
    #supply --skip_upload_apk --skip_upload_screenshots

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer

#https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb#L92


```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

json_key_file "./fastlane/Google Play Android Developer-8aebb2d20ebd.json" 

package_name "com.digital.pbapp"

```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date        |
| deliver             | 1.15.0  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.0  | ✅ Up-To-Date        |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.3   | 🚫 Update availaible |
| fastlane            | 1.108.0 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.0        |
| activesupport             | 4.2.7        |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.2.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| xcode-install             | 2.0.2        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.12.5       |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.0        |
| google-api-client         | 0.9.11       |
</details>


*generated on:* **2016-11-14**
</details>

**Comment by TKBurner** [comment]
@prolog3001 Thanks for following up. Are you using deliver? Can you share your output? For new apps you'll have to set some initial content data.

**Comment by prolog3001** [comment]
Not deliver... using "supply" for Play Store.

**Comment by TKBurner** [comment]
@prolog3001 Thanks for following up. If this is possible to add we'd love to see a PR. Let me know if you are interested!
