### ISSUE TITLE
Deliver `upload_screenshot!': [!] sort_order must be higher than 0

### ISSUE THREAD

**Issue by Jules2010** [fastlane/fastlane#6981]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description
I'm getting the following error when delivering

##### Complete output when running fastlane, including the stack trace and command used
```
Julians-MBP:snip jm$ deliver
[20:24:42]: Successfully loaded '/Users/jm/Dropbox/Code_ObjC/snip/Deliverfile' 📄

+-----------------------+-------------------------+
|      Detected Values from './Deliverfile'       |
+-----------------------+-------------------------+
| app_identifier        | com.snip.snip  |
| username              | snip@gmail.com |
| skip_binary_upload    | true                    |
| skip_metadata         | true                    |
| overwrite_screenshots | true                    |
+-----------------------+-------------------------+

[20:24:42]: Login to iTunes Connect (julesthecoder@gmail.com)
[20:24:44]: Login successful

+-----------------------+-------------------------+
|             deliver 1.15.0 Summary              |
+-----------------------+-------------------------+
| app_identifier        | com.snip.snip  |
| username              | snip@gmail.com |
| skip_binary_upload    | true                    |
| skip_metadata         | true                    |
| overwrite_screenshots | true                    |
| screenshots_path      | ./screenshots           |
| metadata_path         | ./metadata              |
| skip_screenshots      | false                   |
| force                 | false                   |
| submit_for_review     | false                   |
| automatic_release     | false                   |
+-----------------------+-------------------------+

[20:24:46]: Verifying the upload via the HTML file can be disabled by either adding
[20:24:46]: `force true` to your Deliverfile or using `deliver --force`
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
[20:26:13]: HTML file confirmed...
[20:26:14]: Starting with the upload of screenshots...
[20:26:14]: Removing all previously uploaded screenshots...

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
/Library/Ruby/Gems/2.0.0/gems/spaceship-0.37.0/lib/spaceship/tunes/app_version.rb:384:in `upload_screenshot!': [!] sort_order must be higher than 0 (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/upload_screenshots.rb:20:in `block (2 levels) in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/upload_screenshots.rb:19:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/upload_screenshots.rb:19:in `each_with_index'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/upload_screenshots.rb:19:in `block in upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/upload_screenshots.rb:18:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/upload_screenshots.rb:18:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/runner.rb:59:in `upload_metadata'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/runner.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:63:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.53.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:149:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/lib/deliver/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/deliver-1.15.0/bin/deliver:5:in `<top (required)>'
	from /usr/local/bin/deliver:23:in `load'
	from /usr/local/bin/deliver:23:in `<main>'
Julians-MBP:snip jm$ 
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.1                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |
| Git                 | git version 2.3.0                                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.1 (16B2555)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| colored                   | 1.2          |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| commander                 | 4.4.0        |
| babosa                    | 1.0.2        |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.13.6       |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.6        |
| excon                     | 0.54.0       |
| plist                     | 3.2.0        |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
</details>

*generated on:* **2016-11-13**
</details>

**Comment by nolanwilson** [comment]
+1. We're seeing this issue happen for all of our apps using the `overwrite_screenshots` flag

**Comment by nolanwilson** [comment]
Thanks for the update @Jules2010. That's a good workaround for the meantime but I would love to see this fixed as otherwise I'll have to go in and do that for each and every app update that we have.

**Comment by TKBurner** [comment]
@Jules2010 @nolanwilson I flagged this for the core team to take a look 👍

**Comment by KrauseFx** [comment]
This was introduced with https://github.com/fastlane/fastlane/pull/6540, and should only happen when you set the `overwrite_screenshots` flag. Definitely a bug that should be fixed. I'm surprised that this ever worked before cc @giginet

**Comment by nolanwilson** [comment]
We've disabled this option for now and I'll just be manually checking screenshots to make sure they are removed in the mean time. Thanks @TKBurner @KrauseFx for the prompt reply as always!

**Comment by giginet** [comment]
Thank you, notify me about this.
I apologize for the inconvenience.

**Comment by nolanwilson** [comment]
@giginet any chance you'll be able to take a look at this in the near future? Hoping to be able to utilize this feature in the future and I'm a python dev myself/haven't been able to pick up Ruby yet to give it a shot

**Comment by giginet** [comment]
OK, I'll try to fix this issue in a few weeks.
Please moment...

**Comment by milch** [comment]
Hey everyone, just wanted to let you know that we're investigating this, but we don't want to push a new release because most of our core team is on Thanksgiving break right now 🦃 

In the meantime, please use @Jules2010's [workaround](https://github.com/fastlane/fastlane/issues/6981#issuecomment-260280383) if you depend on this feature.

**Comment by milch** [comment]
Fixed in #7273

**Comment by nolanwilson** [comment]
Thanks for the follow up @milch. Will give it a shot later!

**Comment by milch** [comment]
Let me just note that I had trouble with that fix during my testing - I'm just assuming that I'm doing something wrong, since the other PR was tested and approved by someone else. If you still can't get it to work, please submit a new issue!

**Comment by nolanwilson** [comment]
Thanks, will do!
