### ISSUE TITLE
frameit (iPad Air 2 frames have different offsets)

### ISSUE THREAD

**Issue by psamhaber** [fastlane/fastlane#6985]
**Problem:**
The space gray iPad Air 2 frame artwork has a different offset than the rose gold / silver ones
Space gray: 111px/...
Rose gold: 112px/...

**Result:**
Space gray framing works fine
The other colors are off by one pixel

I downloaded and checked the original uncropped device pngs from facebook.design, and the Space gray version is simply 1px wider ( only the ipad artwork outer, not the file, not the viewport area).

**EDIT**
~~How should we handle this? Include their files in the frameit repo and change this one manually?~~
Ah, sorry. Just saw that you already provisioned for this. I will update the space grey file and add a pull request...

**Comment by KrauseFx** [comment]
Is this issue still relevant? Any action required from our side?

**Comment by psamhaber** [comment]
Still relevant, haven't come arround to add a PR but will do later this week, sorry guys
