### ISSUE TITLE
Resign can not find provision profile at path '~/Library/MobileDevice/Provisioning Profiles/'

### ISSUE THREAD

**Issue by ruslanfutureuniverse** [fastlane/fastlane#6986]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Resign fails to find provisioning profile at path '~/Library/MobileDevice/Provisioning Profiles/something.mobileprovision'. But '/Users/user/Library/MobileDevice/Provisioning Profiles/something.mobileprovision' works. And this is fragile.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

bundle exec fastlane resign_ipa
[14:11:00]: -------------------------------------------------
[14:11:00]: --- Step: Verifying required fastlane version ---
[14:11:00]: -------------------------------------------------
[14:11:00]: Your fastlane version 1.108.0 matches the minimum requirement of 1.107  ✅
[14:11:00]: ------------------------------
[14:11:00]: --- Step: default_platform ---
[14:11:00]: ------------------------------
[14:11:00]: Driving the lane 'ios resign_ipa' 🚀
[14:11:00]: --------------------
[14:11:00]: --- Step: resign ---
[14:11:00]: --------------------
[14:11:00]: Error setting value '~/Library/MobileDevice/Provisioning Profiles/f100dffe-dca0-4a73-9363-9bec3de7aa19.mobileprovision' for option 'provisioning_profile'
[14:11:00]: You passed invalid parameters to 'resign'.
[14:11:00]: Check out the error below and available options by running `fastlane action resign`
[14:11:00]: Variable Dump:
[14:11:00]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios resign_ipa"}
[14:11:00]: Couldn't find provisiong profile at path '~/Library/MobileDevice/Provisioning Profiles/f100dffe-dca0-4a73-9363-9bec3de7aa19.mobileprovision'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | resign                              | 0           |
+------+-------------------------------------+-------------+

[14:11:00]: fastlane finished with errors

[!] Couldn't find provisiong profile at path '~/Library/MobileDevice/Provisioning Profiles/f100dffe-dca0-4a73-9363-9bec3de7aa19.mobileprovision'

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |
| Git                 | git version 2.10.1                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.107"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Prepare certificates"
  lane :certificates do
    register_devices(devices_file: "fastlane/devices.txt")
    match(type: "development", force_for_new_devices: true)
    match(type: "appstore")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do |options|
    pem(
      save_private_key: true,
      new_profile: proc do |profile_path| # this block gets called when a new profile was generated
        puts profile_path # the absolute path to the new PEM file
        # insert the code to upload the PEM file to the server
      end
    )
    pilot(skip_submission: true,
          ipa: options[:ipa],
          skip_waiting_for_build_processing: true)
  end

  desc "Resigns app with correct entitlements from profile"
  lane :resign_ipa do
    # sh "sigh resign Binaries/IOS/FutureMobile-IOS-Shipping.ipa
    #  --signing_identity 'iPhone Distribution: The Future Group AS (4TM2DK894Y)'
    #   -n 'match AppStore com.futuregroup.futureuniverse'"
    resign(
      ipa: "Binaries/IOS/FutureMobile-IOS-Shipping.ipa", # can omit if using the `ipa` action
      signing_identity: "iPhone Distribution: The Future Group AS (4TM2DK894Y)",
      use_app_entitlements: true,
      provisioning_profile: "~/Library/MobileDevice/Provisioning\ Profiles/f100dffe-dca0-4a73-9363-9bec3de7aa19.mobileprovision"
    )

  end

  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.futuregroup.futureuniverse" # The bundle identifier of your app
apple_id "developer@futureuniverse.com" # Your Apple email address

team_id "4TM2DK894Y"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.55.0       |
| bundler                   | 1.13.6       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| io-console                | 0.4.5        |
| plist                     | 3.2.0        |
| xcode-install             | 2.0.9        |
</details>

*generated on:* **2016-11-14**
</details>

**Comment by hjanuschka** [comment]
just a blind guess - have you tried removing: the `\ `  for the space?
as it seems that `shellescape` is done here: https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/resign.rb#L30 so in your case this will result in a double shell escape 💥

**Comment by orkenstein** [comment]
@hjanuschka thanks for suggestions. 
Tried both. No, that's not the case.

**Comment by hjanuschka** [comment]
ahhh ok - i think i was reading the issue too fast 👍  and missed the point with the `~`.
seems that resign does not do `expand_path` on it

can you try it like this (as a work around):

```ruby
resign(
      ipa: "Binaries/IOS/FutureMobile-IOS-Shipping.ipa", # can omit if using the `ipa` action
      signing_identity: "iPhone Distribution: The Future Group AS (4TM2DK894Y)",
      use_app_entitlements: true,
      provisioning_profile: File.expand_path("~/Library/MobileDevice/Provisioning\ Profiles/f100dffe-dca0-4a73-9363-9bec3de7aa19.mobileprovision")
    )
```

**Comment by orkenstein** [comment]
It's kinda works, but prints some strange errors:
```
[17:29:18]: -------------------------------------------------
[17:29:18]: --- Step: Verifying required fastlane version ---
[17:29:18]: -------------------------------------------------
[17:29:18]: Your fastlane version 1.108.0 matches the minimum requirement of 1.107  ✅
[17:29:18]: ------------------------------
[17:29:18]: --- Step: default_platform ---
[17:29:18]: ------------------------------
[17:29:18]: Driving the lane 'ios resign_ipa' 🚀
[17:29:18]: --------------------
[17:29:18]: --- Step: resign ---
[17:29:18]: --------------------
/usr/local/lib/ruby/gems/2.3.0/gems/sigh-1.11.2/lib/assets/resign.sh Binaries/IOS/FutureMobile-IOS-Shipping.ipa 2363926241AE7BA87BD172118227A8C8F64CF8FF -p /Users/milo/Library/MobileDevice/Provisioning\ Profiles/f100dffe-dca0-4a73-9363-9bec3de7aa19.mobileprovision      --use-app-entitlements   Binaries/IOS/FutureMobile-IOS-Shipping.ipa 
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
Executable=/Users/milo/Development/FGProject/git_mirror_ignore/Projects/FutureMobile/_floatsignTemp/Payload/FutureMobile.app/FutureMobile
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
_floatsignTemp/Payload/FutureMobile.app: replacing existing signature

[17:30:18]: Successfully signed Binaries/IOS/FutureMobile-IOS-Shipping.ipa!
[17:30:18]: Successfully re-signed .ipa 🔏.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | resign                              | 60          |
+------+-------------------------------------+-------------+

[17:30:18]: fastlane.tools finished successfully 🎉
```

The second question is, how to check if new entitlements actually exist in re-packaged .ipa?

**Comment by hjanuschka** [comment]
use the ipa gem  
or just open it in finder - or unzip it

--  
Helmut Januschka
Sent with Airmail

**Comment by orkenstein** [comment]
Yep, unzipped it.
Not sure, where to look in particular?

**Comment by TKBurner** [comment]
Hi @orkenstein Are you providing the path relative to your directory or relative from the home directory of your user? Thanks!

**Comment by orkenstein** [comment]
@TKBurner relative to the home:
```
provisioning_profile: "~/Library/MobileDevice/Provisioning\ Profiles/f100dffe-dca0-4a73-9363-9bec3de7aa19.mobileprovision"
```

**Comment by hjanuschka** [comment]
@orkenstein  here is a explanation on how to get entitlements: http://stackoverflow.com/a/12851886/1945875

**Comment by orkenstein** [comment]
@hjanuschka Yes, it's there. Thanks a lot!
Despite that not very clean solution with `File.expand_path` and some weird `SecPolicySetValue` warnings, I think the issue is fixed.
The reason I needed to resign the `.ipa` file is 'cause I assemble build from Unreal Engine Editor and I get APNS-entitlement warning from Apple: 
http://stackoverflow.com/questions/14807129/missing-push-notification-entitlement
The only idea I has is to resign app to make 100% sire it's present. 
Maybe there is something else I'm missing?

**Comment by hjanuschka** [comment]
@orkenstein i don't think that the `expand_path` is really unclean, but you'r right - resign itself should do it. ( i ll do a PR for that - i guess)

the `SecPolicySetValue` warning, i don't know right now where this comes from, having this on a few ci machines, but not all - so its kinda os related.


the real solution in your case should be, Unreal Engine Editor exporting it correctly, so maybe creating an issue on their side is the way to go.

can you close this issue here?

**Comment by hjanuschka** [comment]
@orkenstein  PR is here: https://github.com/fastlane/fastlane/pull/7004

**Comment by ruslanfutureuniverse** [comment]
@hjanuschka thanks for swift support!

**Comment by milch** [comment]
The `SecPolicySetValue` definitely is environment related, I've also seen it on a couple machines before. Nevertheless, I'm glad it works despite the warning! 🚀
