### ISSUE TITLE
frameit (Landscape detection not working as expected)

### ISSUE THREAD

**Issue by psamhaber** [fastlane/fastlane#6987]
**Problem:**
Landscape screenshots of iPhone and iPad frames are not framed correctly, see attached.
It seems the landscape detection part doesn't seem to understand the offset/widths correctly?

**Specs:**
- Running frameit directly from the console
- Version: frameit 3.0.0;
- Screenshot sizes are correct (iPhone 750x1334px, iPad 2048x1536px)
- I'm using the latest frames version

![ipad-horz-max-00_framed](https://cloud.githubusercontent.com/assets/4225828/20266459/766300a4-aa76-11e6-8df4-25feb30e2295.png)

![digitalcontent-01_test_framed](https://cloud.githubusercontent.com/assets/4225828/20266440/640dcd80-aa76-11e6-9c46-f113deee0a37.png)

**Comment by psamhaber** [comment]
Can anyone reproduce this?

**Comment by TKBurner** [comment]
@psamhaber I think I've seen another report elsewhere so we are going to test on our end. Thanks!

**Comment by futuretap** [comment]
Yes, I can reproduce this when no background is set.

**Comment by psamhaber** [comment]
@TKBurner any update on this? I would fix it myself but my ruby skills are basic at best. 

Looking at editor.rb (line 23ff) I guess the problem lies in `width = offset['width']`. If you check the resulting screens I attached above, it looks like the width value is taken from before the frame is flipped...

**Comment by mfurtak** [comment]
Thanks for the report! I've reproduced this locally, and will look into it. 👍

**Comment by mfurtak** [comment]
Hi folks - I've merged a change in #7759 that seems to fix this problem. If possible, could you give it a try before we ship it in the next release?

Thanks! 🙌

**Comment by psamhaber** [comment]
Hi Michael, it's working again, awesome! Thanks a bunch!

**Comment by mfurtak** [comment]
Great - glad to hear it! 🙌 

This has shipped as part of [_fastlane_ 2.6.0](https://github.com/fastlane/fastlane/releases/tag/2.6.0) :rocket:
