### ISSUE TITLE
Integrating phonegap build with fastlane

### ISSUE THREAD

**Issue by herberzt** [fastlane/fastlane#6988]
I've been digging around looking to see if there is a way to integrate PhoneGap build into Fastlane. Our application is a Ruby on Rails app and not written in a native mobile language. From what I can see Gym is were the IPA or APK come from, is there a way to get Gym to run the PhoneGap APIs instead?

**Comment by hjanuschka** [comment]
what is `Phonegap Build`? the cloud based building service?
can you provide a sample app?

you can always shell out to run normal console commands with `sh "echo 124"` - so if you can build from commandline you can do it from fastlane too.

i'v seen samples (using ionic framework; should be comparable) -> https://github.com/fiahfy/ionic2-fastlane-sample

where you get a real xcodeproject, therefore one can build normally with gym.

**Comment by herberzt** [comment]
@hjanuschka yes, the cloud-based building service. essentially with Phonegap I can upload a project to the web-based interface they provide and it will shoot out and IPA and APK file this can be achieved by calling their API directly as well.

**Comment by hjanuschka** [comment]
ok i dont think there is currently a phonegap action or plugin for fastlane.
if i get this right, you have to configure your git repo on phonegap build site.

and then you can trigger build by calling this rest api:

`http://docs.phonegap.com/phonegap-build/developer-api/write/#_post_https_build_phonegap_com_api_v1_apps_id_build`

right?

so you could do a plugin/action around it to use `RestClient` to issue the build.

**Comment by herberzt** [comment]
Okay, well hopefully I can figure it out and get it submitted for other people to use. Thanks

**Comment by hjanuschka** [comment]
i am not quite into phonegap at-all - but let me know if i can assist you somewhere, could you provide a sample app and maybe a account i can play arround with?

**Comment by herberzt** [comment]
@hjanuschka there is this. it might help. I don't want to give away our specific project. https://github.com/phonegap/phonegap-start

**Comment by hjanuschka** [comment]
ohhh i see do you have https://github.com/phonegap/phonegap-cli installed?

`phonegap remote build`  try this from your terminal. :)

**Comment by menriquez** [comment]
we are currently using Ionic built apps with fastlane but doing so locally, not with the phonegap cloud-build system, and it requires a good amount of custom scripting to tie all the pieces together, as would be expected.

my guess would be just skip the `gym` part of `fastlane`, do a `phonegap remote build`, and use `deliver`  and `supply` to submit the app to the stores.

**Comment by herberzt** [comment]
@menriquez seems like a decent approach. How do you manage to do screenshots?

**Comment by menriquez** [comment]
@herberzt ahhh yes....the screenshots,,,the final yet-unfinished piece to our fully automated Ionic./Cordova build system.  First, a little background....we are a small company that services the pharmacy industry, and in that capacity we write the websites and prescription refill software that our clients require. Of course, they all want mobile apps nowadays (rightfully so), so we chose Ionic to give us both iOS and Android apps for the price of one (well, it sounds great on paper at least).

with the help of an outstanding offshore Ionic dev, we build our app and it works very well...however, now we needed for it to be used as a frameworks for perhaps **100's** of branded apps that shared 98% of the codebase and had slight changes for each pharmacy.

we of course wanted to automate the process of building and submitting these customized apps, so we looked at fastlane, rolled up our sleeves, learned some Ruby, and built out the custom scripts needed to create individual symlinked directories for each pharmacy build, all referencing a 'mobile-app-framework' dir that allows us to modify the source and quickly rebuild and submit all of our apps to the two stores.

so we worked out all the issues required to automate the entire process except the snapshot build.  I am currenlty experimenting with both the xcodeproj gem and the more powerful https://github.com/appsquickly/XcodeEditor xcodeeditor app to dynamically attach the screenshot UITest Target and scheme to the existing project and then run `snapshot` for the screenshots.

i am pretty close to having it working, but so far the holy grail of completely automated solution is not there yet...we hope you are having better luck and would like to hear how you are approaching the problem.

**Comment by herberzt** [comment]
Me and another dev will be tackling this task tomorrow. We are gonna have to probably do some custom scripting and monkeying around so it probably won't be the cleanest but I will try and share what we come up with. It looks like we manage apps the same way a number of customers all using the same code base just different branding
