### ISSUE TITLE
Gym doesn't compile core data generated classes

### ISSUE THREAD

**Issue by jniemin** [fastlane/fastlane#6989]
### Issue Description

Trying to build my app but it randomly fails for following error

```
clang: error: no such file or directory: '/Users/MyUser/Library/Developer/Xcode/DerivedData/fuel-gqgstqcwdrmbbtdszohjbofhqceo/Build/Intermediates/ArchiveIntermediates/fuel/IntermediateBuildFilesPath/fuel.build/Release-iphoneos/fuel.build/DerivedSources/CoreDataGenerated/DataModel/MyOwn+CoreDataProperties.m'
```

From time to time it builds but most of the time it doesn't. Even if I haven't changed anything, just ran builds one after another. After build if I check the directory, the file actually exists in the dir. Also when compiling through xcode, the build is fine.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                          |
| ------------------- | ---------------------------------------------- |
| OS                  | 10.12.1                                        |
| Ruby                | 2.3.1                                          |
| Bundler?            | false                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version       | 8.1                                            |
| Git                 | git version 2.9.3 (Apple Git-75)               |
| Installation Source | /Users/MyUser/.rvm/gems/ruby-2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                     |
| Ruby Lib Dir        | /Users/MyUser/.rvm/rubies/ruby-2.3.1/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end


  desc "Creates new build"
  lane :build do
    increment_build_number
    gym(
      scheme: "fuel",
      configuration: "Release",
      silent: true,
      clean: true
    )
    end


  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxxxx" # The bundle identifier of your app
apple_id "xxxxxx@xxxxxxxxxxx" # Your Apple email address

team_id "XXXXXXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.53.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.55.0       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
</details>

*generated on:* **2016-11-14**
</details>

**Comment by hjanuschka** [comment]
can you try adding:

```
clear_derived_data
```

right before the call to `gym` - maybe this helps.

**Comment by jniemin** [comment]
No help from adding clear_derived_data. Still won't compile

**Comment by TKBurner** [comment]
@jinjorge Can you try manually setting the derived_data_path?

**Comment by jinjorge** [comment]
@TKBurner I think you meant ^^ for @jniemin

**Comment by jniemin** [comment]
@TKBurner Adding derived_data_path manually doesn't seem to help

**Comment by falcon03** [comment]
Same problem here... Any workaround? The suggested ones didn't work for me either.

**Comment by samuelbeek** [comment]
Same problem here

**Comment by reich** [comment]
Same issue with CoreData Codegen.
fastlane 1.110.0
Xcode 8.2.1
Code Generation: Swift
Codegen: Class Definition

**Comment by falcon03** [comment]
I've been able to workaround the problem by explicitly passing the scheme name to Jym. Not sure of the reason why, but doing that fixes the problem for me.

**Comment by falcon03** [comment]
I've been able to workaround the problem by explicitly passing the scheme name to use for building the project to Gym. Not sure of the reason why, but that fixes the problem for me.

**Comment by alexey-pelykh** [comment]
Unfortunately that doesn't help either

**Comment by alexey-pelykh** [comment]
DISABLE_XCPRETTY=true seems do help, but I have really no idea how that may be related

**Comment by petersuwara** [comment]
Are people still having problems with this issue ?
