### ISSUE TITLE
How to group multiple lanes in config files (e.g. Appfile)

### ISSUE THREAD

**Issue by kluepfel** [fastlane/fastlane#6994]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
We have two versions of our app, a "regular" one and a "beta" one. We have multiple lanes for each, for running tests, distributing testflight builds, and releasing regular builds. Do I have to write a for_lane block for each of these in config files (e.g. Appfile) or is there some way to group them?

Here's what we have now:

```
app_identifier "my.beta.App"`

for_lane :test  do 
    app_identifier "my.production.App"
end

for_lane :distributeTestVersion do 
    app_identifier "my.production.App"
end

for_lane :release do
    app_identifier "my.production.App"
end

````

I hope there is a better way

**Comment by KrauseFx** [comment]
You can always pass the `app_identifier` to each action in your Fastfile too, so it looks something like 
```ruby
deliver(app_identifier: "my.app", ...)
```

**Comment by hjanuschka** [comment]
a bit more in detail you can do it like this:

```ruby
# you can use options[:app_identifier] where-ever you need the variable
# passing them to deliver/match/gym...... most tools support the appidf
lane :demo do | options |
        puts "Building: #{options[:app_identifier]}"
end
```


call it from commandline with:

`fastlane demo app_identifier:hello.world.app``

or from within fastfile you can call it with:

```ruby
demo(app_identifier: "hello.world.app")
```

let me know if this helps @kluepfel

**Comment by kluepfel** [comment]
Awesome, thanks! Passing options into fastlane actions was the key to solving this.

Our Fastfile looks like this now:

```ruby
desc "Submit a new beta build to testflight"
lane :testflightBeta do
    testflight_internal(is_beta: true)
end

desc "Submit a new release build to testflight"
lane :testflightRelease do
    testflight_internal(is_beta: false)
end

lane :testflight_internal do | options |
    if (options[:is_beta]) then
        app_identifier = "de.companyName.AppNameBeta"
        scheme = "AppNameBeta"
        output_directory = "./build/Beta/"
    else 
        app_identifier = "de.companyName.AppName"
        scheme = "AppName"
        output_directory = "./build/Production/"
    end
    
    gym(scheme: scheme, use_legacy_build_api: true, output_directory: output_directory)
    cert #get the certificate
    sigh(app_identifier: app_identifier) #get the provisioning profile
    resign(signing_identity: "iPhone Distribution: CompanyName (ABCD123456)")
    pilot #upload and distribute testflight build
end
```
