### ISSUE TITLE
Require Xcode Version

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#6996]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Since we can use `fastlane_version` to require a specific `fastlane` version, we should be able to use `xcode_version` to require a specific Xcode version.[ I realize we can use `xcode-select` to select a specific version](https://github.com/fastlane/fastlane/issues/50), but that requires running `fastlane` with `root` permissions. I don't want all of my `fastlane` script to have `root`. I just want to guarantee that `fastlane` is running with a specific Xcode version.

**Comment by KrauseFx** [comment]
Do you mean something like `xcversion`? https://docs.fastlane.tools/actions/#xcversion

**Comment by KrauseFx** [comment]
Or even `ensure_xcode_version` 👍

**Comment by hborders** [comment]
Thanks! `ensure_xcode_version` is exactly what I wanted. I swear I googled this before I asked. :)

**Comment by KrauseFx** [comment]
👍
