### ISSUE TITLE
Ability to return information about a Membership and Contracts

### ISSUE THREAD

**Issue by barnaclebarnes** [fastlane/fastlane#7000]
### Issue Description

We manage over 150 different client apps on our platform and we often find that client let their Apple Developer memberships lapse and fail to agree to new developer agreements. We would like to automate a check on the developer and iTunes Connect portal to:

* Return Membership information (i,.e. Program Type, Entity Type, Phone, Address, Expiration Date, Device Reset Date, Team Agent)
* Return an indicator if there are any agreements that need to be signed from the Developer Portal
* Return an indicator if there are any agreements that need to be signed from iTunesConnect

If we could do this then we could proactively reach out to clients so their apps do not get removed from the app store.

**Comment by TKBurner** [comment]
@barnaclebarnes Are you interested in submitting a PR for this? I'll mark it as a feature request for now 👍
