### ISSUE TITLE
Allow for uploading iTunes Connect export compliance documentation

### ISSUE THREAD

**Issue by enozero** [fastlane/fastlane#7001]
### Issue Description
Uploading of iTunes Connect export compliance is not yet implemented in Spaceship. Let's get it implemented!

**Comment by enozero** [comment]
I'll start working on this issue.

**Comment by TKBurner** [comment]
@enozero Sounds like a plan! Really happy to have you contributing 👍

**Comment by enozero** [comment]
Thanks @TKBurner! iTC does Export Compliance almost like a build, so I'll be taking that into account along with uploading during the submission phase.
