### ISSUE TITLE
The sh action is undocumented.

### ISSUE THREAD

**Issue by remcohaszing** [fastlane/fastlane#7007]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The `sh` action is undocumented. I was looking for it on https://docs.fastlane.tools/actions/, because I was hoping to find a way to disable the colored output. I have no clue if this is possible, because the action is not documented at all, it's just mentioned in some examples.

**Comment by hjanuschka** [comment]
good point, btw to disable colored output set `FASTLANE_DISABLE_COLORS` to 1


in your fastfile (on top):
```
ENV['FASTLANE_DISABLE_COLORS'] = 1
```

**Comment by asfalcone** [comment]
Thanks @hjanuschka 👍
