### ISSUE TITLE
How to write unit tests for local/private actions

### ISSUE THREAD

**Issue by xfreebird** [fastlane/fastlane#7010]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,

I want to write unit/integration tests for my local fastlane actions.
Currently I'm not sure what is the best (less friction) setup.

What is the simplest way to do it in terms of env setup and running the tests ?

Thanks!

**Comment by hjanuschka** [comment]
i would preffer (we do so) - create a plugin, e.g.: fastlane-plugin-mycompany - have my actions in there, and in the plugin skeleton there is a `rspec` sample setup. (see here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#create-your-own-plugin)

we don't even use the pluginfile, just put a `require "fastlane/plugin/mycompany"` at the top of my fastfile, and ensure the gem `fastlane-plugin-mycompany`  is installed.
