### ISSUE TITLE
[Feature] Use snapshot to create screenshots for apache cordova apps

### ISSUE THREAD

**Issue by Jianbo-Zhu** [fastlane/fastlane#7013]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

fastlane is a great tool, we have done a lot with it. Now we want to use snapshot for creating screenshots. However, the instructions below are for Xcode projects. How can I do for apache cordova projects?

> Open your Xcode project and make sure to do the following:
> 1) Add a new UI Test target to your project
> 2) Add the ./fastlane/SnapshotHelper.swift to your UI Test target
>   You can move the file anywhere you want
> 3) Call 

> when launching your app
> 
>  let app = XCUIApplication()
>  setupSnapshot(app)
>  app.launch()
> 
> 4) Add `snapshot("0Launch")` to wherever you want to create the screenshots

**Comment by hjanuschka** [comment]
according to the documentation - https://cordova.apache.org/docs/en/latest/guide/platforms/ios/index.html

you just could open the xcode project, and follow the normal snapshot integration guide here => https://github.com/fastlane/fastlane/tree/master/snapshot#ui-tests

**Comment by hjanuschka** [comment]
here is a cordova sample - with fastfile + snapshot:
  * https://github.com/hjanuschka/fastlane-cordova-sample
  

steps i did:
  * create a new cordova app
  * add ios platform
  * open xcode project
  * add new XCUITest Target
  * `fastlane init`(on cordova root folder)
  *  `snapshot init` ( in platforms/ios/)
  *  in xcode - added `SnapshotHElper.swift`  to XCUITest Target -> say yes on Bridging header
  * go to UITests.m -> import Bridigng header `#import "FastlaneCordovaUITests-Swift.h"`
  *  add the snapshot init code in `setup`
  * add some unit test in `testExample`
  * and call screenshot with
```
    sleep(5);
    [Snapshot snapshot:@"Startpage" waitForLoadingIndicator:NO];
```
  * run `fastlane snap`

![bildschirmfoto 2016-11-15 um 16 22 43](https://cloud.githubusercontent.com/assets/2891702/20311397/f170b49c-ab4f-11e6-9d55-8b1b2e78f324.png)


and resulting screenshot:

<img src='https://raw.githubusercontent.com/hjanuschka/fastlane-cordova-sample/master/fastlane/screenshots/de-DE/iPhone6s-Demo.png' width=100>


please consider this as unofficial and unfinished, so you may have to adjust the sample here and there to fit your needs. AND BACKUP EVERTHING before you add the target.

also i am not sure what happens on project upgrades by cordova.

**Comment by asfalcone** [comment]
@hjanuschka Thanks for this awesome response! 🙏 

@Jianbo-Zhu I'm going to close this issue since it looks completely answered 👍

**Comment by qwertynik** [comment]
@hjanuschka 
- add new XCUITest Target
- fastlane init(on cordova root folder)
- snapshot init ( in platforms/ios/)
- in xcode - added SnapshotHElper.swift to XCUITest Target -> say yes on Bridging header
- go to UITests.m -> import Bridigng header #import "FastlaneCordovaUITests-Swift.h"

I am a beginner to iOS development. I do not fully understand on how to do those steps. Can you explain me on how to do these steps or if you could point me to some links explaining on how these should be done, that would be great
