### ISSUE TITLE
Deliver: [en-US]: You must detail what's new in this version in English (U.S.).

### ISSUE THREAD

**Issue by MaximusMcCann** [fastlane/fastlane#7016]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
[09:05:39]: [en-US]: You must detail what's new in this version in English (U.S.).
```

but I have clearly entered `release_notes`.  I also edited the fastlane/metadata/en-US/release_notes.text to not be blank, but still no luck.
```
deliver(app_version: VERSION_NUMBER, release_notes: "What is New in v#{VERSION_NUMBER}:")
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.11.6                                          |
| Ruby                | 2.2.2                                            |
| Bundler?            | true                                             |
| Xcode Path          | /Applications/Xcode8.app/Contents/Developer/     |
| Xcode Version       | 8.0                                              |
| Git                 | git version 2.8.4 (Apple Git-73)                 |
| Installation Source | /Users/a/.rbenv/versions/2.2.2/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1004)                       |
| Ruby Lib Dir        | /Users/a/.rbenv/versions/2.2.2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2d 9 Jul 2015                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
desc "Deploy a new version to the App Store"
lane :release do
  ENV["APP_IDENTIFIER"] = "com.aoeu.aoeu"
  ENV["BUILD_SCHEME"] = "aoeu"

  ensure_git_branch(branch: 'master')
  VERSION_NUMBER = get_version_number(target: "#{ENV["BUILD_SCHEME"]}")

  add_git_tag(tag: "v#{VERSION_NUMBER}", message: changelog_from_git_commits(commits_count: 5), force: true)
  push_git_tags(force: true)

  deliver(app_version: VERSION_NUMBER, release_notes: "What is New in v#{VERSION_NUMBER}:")

  slack(message: "Successfully deployed new App Update.")
end


```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.5   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.108.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.2        |
| molinillo                 | 0.4.5        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.0.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types                | 1.25.1       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| rest-client               | 1.6.9        |
| fastlane-plugin-sentry    | 0.1.0        |
</details>

*generated on:* **2016-11-15**
</details>

**Comment by TKBurner** [comment]
Hi @MaximusMcCann Thanks for reaching out. Can you provide your full output? It looks like you might need to login and setup some intial information in iTC but I want to make sure. 

Thanks!

**Comment by MaximusMcCann** [comment]
Back again, same error trying to submit.
My deliver file contains:
```
release_notes({
  'default' => "UI Cleans",
  'en-US' => "UI Cleans"
})
```

Pertinent output:

```
+------------------------+---------------------------------------------+
|            Detected Values from './fastlane/Deliverfile'             |
+------------------------+---------------------------------------------+
| copyright              | © 2016. All rights reserved. |
| app_review_information |                                             |
| force                  | true                                        |
| skip_metadata          | true                                        |
| skip_binary_upload     | true                                        |
| submit_for_review      | true                                        |
| automatic_release      | true                                        |
| submission_information |                                             |
+------------------------+---------------------------------------------+

[18:20:07]: Login to iTunes Connect (aa@aa.com)
[18:20:11]: Login successful

+----------------------------------------------------------------------------+---------------------+
|                                      deliver 1.16.1 Summary                                      |
+----------------------------------------------------------------------------+---------------------+
| app_version                                                                | 2.1.0               |
| release_notes.default                                                      | UI Cleans           |
| release_notes.en-US                                                        | UI Cleans           |
| copyright                                                                  | © 2016... |
| app_review_information.first_name                                          | aa             |
| app_review_information.last_name                                           | aa              |
| app_review_information.phone_number                                        | aa          |
| app_review_information.email_address                                       | aa@aa... |
| app_review_information.demo_user                                           | aa@aa.com    |
| app_review_information.demo_password                                       | *******            |
| app_review_information.notes                                               | See Whats New       |
| force                                                                      | true                |
| skip_metadata                                                              | true                |
| skip_binary_upload                                                         | true                |
| submit_for_review                                                          | true                |
| automatic_release                                                          | true                |
| submission_information.add_id_info_limits_tracking                         | false               |
| submission_information.add_id_info_serves_ads                              | false               |
| submission_information.add_id_info_tracks_action                           | true                |
| submission_information.add_id_info_tracks_install                          | true                |
| submission_information.add_id_info_uses_idfa                               | true                |
| submission_information.content_rights_has_rights                           | false               |
| submission_information.content_rights_contains_third_party_content         | false               |
| submission_information.export_compliance_platform                          | ios                 |
| submission_information.export_compliance_compliance_required               | false               |
| submission_information.export_compliance_encryption_updated                | false               |
| submission_information.export_compliance_uses_encryption                   | false               |
| submission_information.export_compliance_is_exempt                         | false               |
| submission_information.export_compliance_contains_third_party_cryptography | false               |
| submission_information.export_compliance_contains_proprietary_cryptography | false               |
| submission_information.export_compliance_available_on_french_store         | false               |
| screenshots_path                                                           | ./fastlane/scree... |
| metadata_path                                                              | ./fastlane/metadata |
| username                                                                   | aa@aa.com  |
| app_identifier                                                             | com.aaa.aa... |
| ipa                                                                        | aa.ipa          |
| platform                                                                   | ios                 |
| skip_screenshots                                                           | false               |
| dev_portal_team_id                                                         | aa          |
| overwrite_screenshots                                                      | false               |
+----------------------------------------------------------------------------+---------------------+

[18:20:12]: Making sure the latest version on iTunes Connect matches '2.1.0' from the ipa file...
[18:20:14]: '2.1.0' is the latest version on iTunes Connect
[18:20:14]: Detected languages: ["default", "en-US"]
[18:20:15]: Starting with the upload of screenshots...
[18:20:15]: Successfully uploaded screenshots to iTunes Connect
[18:20:17]: Finished the upload to iTunes Connect
[18:20:18]: Selecting the latest build...
[18:20:21]: Selecting build 2.1.0 (963)...
[18:20:22]: Successfully selected build
[18:20:22]: Submitting the app for review...
[18:20:25]: Variable Dump:
[18:20:25]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"release", :VERSION_NUMBER=>"2.1.0", :FL_CHANGELOG=>"fastlane\ndeliverfile\nfastfile\nignore a in a.\nbundle a\n"}
[18:20:25]: [en-US]: You must detail what's new in this version in English (U.S.).

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | update_fastlane            | 1           |
| 2    | default_platform           | 0           |
| 3    | xcversion                  | 1           |
| 4    | ensure_git_branch          | 0           |
| 5    | get_version_number         | 0           |
| 6    | changelog_from_git_commits | 0           |
| 7    | add_git_tag                | 0           |
| 8    | push_git_tags              | 1           |
| 💥    | deliver                    | 17          |
+------+----------------------------+-------------+

[18:20:25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane is not utilizing my Deliverfile while uploading w/ deliver
   https://github.com/fastlane/fastlane/issues/6345 [closed] 5 💬
   10 Oct 2016


[!] The request could not be completed because:
	[en-US]: You must detail what's new in this version in English (U.S.).
```

**Comment by MaximusMcCann** [comment]
Would appreciate any help on this.  Still receiving the same issue

```
[en-US]: You must detail what's new in this version in English (U.S.).
```
but clearly I have added that in the deliveryfile:
```
| release_notes.default                                                      | UI Cleans           |
| release_notes.en-US                                                        | UI Cleans           |
```

Cheers!

**Comment by MaximusMcCann** [comment]
Had to set `skip_metadata` to false!

https://github.com/fastlane/fastlane/issues/3716
