### ISSUE TITLE
download_dsyms + hockey_app : how to ?

### ISSUE THREAD

**Issue by nicolasbraun** [fastlane/fastlane#7017]
Hi,

I am trying to implement the `download_dsyms`download feature and then upload the dsym to HockeyApp.

The problem is since this dSYM upload is done async from the build, HockeyApp can not know to which build I am trying to attach the symbol file. The `hockey` action uses the [`POST /api/2/apps/APP_ID/app_versions/upload`](https://support.hockeyapp.net/kb/api/api-versions#-u-post-api-2-apps-app_id-app_versions-upload-u-) API where we should use the [`PUT /api/2/apps/APP_ID/app_versions/ID`](https://support.hockeyapp.net/kb/api/api-versions#update-version)

The problem now is retrieving the build ID I want to upload my symbols to. I could call [`GET /api/2/apps/APP_ID/app_versions`](https://support.hockeyapp.net/kb/api/api-versions#-u-get-api-2-apps-app_id-app_versions-u-) and parse the result to find the build ID which matches my version (marketing version and build number).

Coding this is not particularly difficult but I was wondering if there was a cleaner way to do this with Shenzen (I am not a ruby pro at all!) The example in the documentation is very simple for crashlytics so I am wondering if I am missing something.

Last question would be the output of the `download_dsyms` action which is an array. I suspect this is because there can be ios and watchos symbols but if anyone cares to confirm it would be greatly appreciated ;)

Thanks 

Nicolas

**Comment by hjanuschka** [comment]
can you look at this PR -> https://github.com/fastlane/fastlane/pull/638


i think a combination of `upload_dsym_only: true`, and `dsym: /path/to/dsym.dSYM`


something like this:
(according to docs, DSYM_PATHS holds: "An array to all the zipped dSYM files")
```ruby
download_dsyms
lane_context[SharedValues::DSYM_PATHS].each do | dsym_file |
   hockey(upload_dsym_only: true, dsym: dsym_file)
end
```

untested,unofficial -> but i think its the right direction?

**Comment by TKBurner** [comment]
@nicolasbraun Thanks for reaching out. I'm not aware of a way to clean this up. Crashlytics associates the UUID with the dSYM and therefore can take a random stream of dSYMs and apply them to the appropriate build. Thanks!

**Comment by nicolasbraun** [comment]
Hello @hjanuschka @TKBurner, thanks for stepping in.

I am already using #638 for my store builds and surely intend to use it for what I am trying to do here.
I will share my work in this post if anyone wants to use ii / clean it 

Thanks

**Comment by nicolasbraun** [comment]
Here it is 

Find the **build** ID that matches your version and buildnumber :

```ruby
def find_hockey_app_id_for(public_app_id, hockey_api_token, version, build_number)
  abort "Version must be passed" unless version
  puts "Searching for your app on HockeyApp"
  puts "⚠️ Only the app version will be used since you did not provide the build_number".yellow unless build_number
  uri = URI.parse("https://rink.hockeyapp.net/api/2/apps/#{public_app_id}/app_versions/")
  request = Net::HTTP::Get.new(uri)
  request["X-Hockeyapptoken"] = hockey_api_token

  begin
    response = Net::HTTP.start(uri.hostname, uri.port, use_ssl: uri.scheme == "https") do |http|
      http.request(request)
    end
  rescue response.code != 200, Timeout::Error, Errno::EINVAL, Errno::ECONNRESET, EOFError,
    Net::HTTPBadResponse, Net::HTTPHeaderSyntaxError, Net::ProtocolError => e
    puts "HTTP Request to HockeyApp Failed"
    false
  end
  apps = JSON.parse(response.body)["app_versions"] # http://pastebin.com/gRdmRPxS
  matching_app_ids =[]
  apps.each do |app|
    if app["shortversion"] == version && (app["version"] == build_number || !build_number)
      matching_app_ids << app["id"]
    end
  end
  puts matching_app_ids.empty? ? "No matching app id found".red :  "Found matching app Ids : #{matching_app_ids}"
  matching_app_ids
end
```

Upload the dSYM

```ruby
def upload_symbols_to_hockey(public_app_id, hockey_api_token, version, build_number, symbols)
  app_ids = find_hockey_app_id_for(public_app_id, hockey_api_token, version, build_number)
  abort "The ID of your build was not provided" if app_ids.empty?
  abort "No symbols passed to the upload_to_hockey function" unless symbols
  app_ids.each do |app_id|
    symbols.each do |symbol|
      #TODO This might be done using net/http but sending a file is complicated . Will only work on Unix machines
      cli = 'curl'
      cli << ' -X PUT'
      cli << " -H \"X-HockeyAppToken: #{ENV['HOCKEY_API_TOKEN']}\""
      cli << " -F \"dysm=@#{symbol}\""
      cli << " https://rink.hockeyapp.net/api/2/apps/#{public_app_id}/app_versions/#{app_id}"
      sh(cli)
      puts "successfully upload symbols #{symbol} to app Id #{app_id}"
    end
  end
end
```

**Comment by nicolasbraun** [comment]
FYI https://support.hockeyapp.net/discussions/problems/65576-automatic-detection-of-app-or-build-when-upload-dsym-files
