### ISSUE TITLE
[Feature request] Planning price changes through fastlane?

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#7018]
Is it currently possible? Perhaps I could help a little with some minimal guidance?

**Comment by TKBurner** [comment]
Hi @masteranza Right now IAP changes aren't available through fastlane. I'll leave this open as a feature request. Thanks!

**Comment by masteranza** [comment]
I didn't have IAP in mind, I've meant the price of the whole app without uploading a new version.

**Comment by JustinJiaDev** [comment]
@masteranza It is possible. Set everything to false (upload binary, upload screenshot, and upload meta). You will only update app icon and price (without the need to create a new version). However, I wish `delver` could allow me to modify meta without uploading new version (this is possible through iTC website).

**Comment by masteranza** [comment]
@JustinJiaDev that would be great! Also thank you for the tip, but how can you tell iTunes to set a planned price change? Say, "20 Nov set the price to 0.99$ then 22 Nov set it to back to previous price"?

**Comment by JustinJiaDev** [comment]
I don't think deliver currently supports this.
