### ISSUE TITLE
screengrab error on Android

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7019]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Getting following error while running `fastlane screenshots` lane.

```
The `adb` command could not be found on your PATH
Please ensure that the Android SDK is installed and the platform-tools directory is present and on your PATH
```

### Captured Output

Command Used: `screenshots`
<details><summary>Output/Log</summary>

```

[11:19:07]: -------------------------------------------------
[11:19:07]: --- Step: Verifying required fastlane version ---
[11:19:07]: -------------------------------------------------
[11:19:07]: Your fastlane version 1.108.0 matches the minimum requirement of 1.108.0  ✅
[11:19:07]: ------------------------------
[11:19:07]: --- Step: default_platform ---
[11:19:07]: ------------------------------
[11:19:07]: Driving the lane 'android screenshots' 🚀
[11:19:07]: ------------------------
[11:19:07]: --- Step: screengrab ---
[11:19:07]: ------------------------
[11:19:07]: The `adb` command could not be found on your PATH
[11:19:07]: Please ensure that the Android SDK is installed and the platform-tools directory is present and on your PATH
[11:19:07]: Variable Dump:
[11:19:07]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android screenshots"}
[11:19:07]: adb command not found

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | screengrab                          | 0           |
+------+-------------------------------------+-------------+

[11:19:07]: fastlane finished with errors

[!] adb command not found


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.0                                             |
| Git                 | git version 2.8.4 (Apple Git-73)                |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2657)                      |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.108.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Create and Upload screenshots to Play Store"
  lane :screenshots do
    screengrab
    # supply
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "play-store.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.rtayal.cotton" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| babosa              | 1.0.2   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.55.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-11-15**
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.0                                             |
| Git                 | git version 2.8.4 (Apple Git-73)                |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2657)                      |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| babosa              | 1.0.2   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.55.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-11-15**
</details>

**Comment by TKBurner** [comment]
@RishabhTayal Thanks for reaching out. Can you run `fastlane run update_fastlane` and let me know if you still hit this issue? It looks like your version of screengrab is out of date. Thanks!

**Comment by RishabhTayal** [comment]
Quick question: in my project structure, where should I install `fastlane`? in the first level folder or inside `app` folder?

![screenshot 2016-11-15 13 09 26](https://cloud.githubusercontent.com/assets/2100166/20319706/c9649e2a-ab34-11e6-9782-08b646fc6ab6.png)

**Comment by hjanuschka** [comment]
i think its supposed to be in first level folder!

**Comment by RishabhTayal** [comment]
Updated screengrab. Still getting same error.

```
 Updating screengrab from 0.5.5 to 0.5.6 ... 🚀
[13:11:34]: Finished updating screengrab
[13:11:34]: Cleaning up old versions...
[13:11:34]: fastlane.tools successfully updated! I will now restart myself... 😴
```

**Comment by hjanuschka** [comment]
@RishabhTayal i think you are missing the `adb` command.
can you post the output of the following commands:

```
echo $PATH
echo $ANDROID_HOME
```

`ANDROID_HOME` - should be somthing like: ` ~/Library/Android/sdk/`

and inside your path there should be something like: `~/Library/Android/sdk/platform-tools/`
as there is the `adb`

**Comment by RishabhTayal** [comment]
Here is my output:
```
$ echo $PATH
/Users/rtayal/.rvm/gems/ruby-2.2.1/bin:/Users/rtayal/.rvm/gems/ruby-2.2.1@global/bin:/Users/rtayal/.rvm/rubies/ruby-2.2.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MAMP/Library/bin/:/Users/rtayal/.rvm/bin:/Users/rtayal/.rvm/bin
$ echo $ANDROID_HOME

```
Seems like my `ANDROID_HOME` is empty. How do I update my `$PATH` and `$ANDROID_HOME`

**Comment by hjanuschka** [comment]
* install android-studio (if not already)
    * https://developer.android.com/studio/install.html


run following commands before running fastlane:
```
export ANDROID_HOME="~/Library/Android/sdk/"
export PATH=$PATH:~/Library/Android/sdk/platform-tools/
fastlane screenshots
```

you can also add the two ENVs to your `~/.profile` (and restart your terminal) - then those 2 env-vars are always available.

**Comment by RishabhTayal** [comment]
@hjanuschka Awesome! now I am not getting the `adb` error. But now getting ` There are no connected and authorized devices or emulators`.

**Comment by hjanuschka** [comment]
@RishabhTayal we are getting there.
do you have an device attached by usb?

you can try to restart adb-server
```
adb kill-server
adb start-server
```

and then list devices - like:
```
adb list
```

if you are intended to use an emulator you should create one by starting the avd-manager

```
~/Library/Android/sdk/tools/android avd
```

this will bring up the AVD you can create a emulator - and launch it - once it is launched it should be listed in `adb list` - and from that point on you should be able to use screengrab 👏

**Comment by RishabhTayal** [comment]
Should I already have an emulator in the avd since I have been debugging and running my app on emulator?

**Comment by RishabhTayal** [comment]
I already had an avd. Just needed to launch it. I will go through the remaining tutorial. Thanks for the help!

**Comment by RishabhTayal** [comment]
@hjanuschka I am kinda stuck here. I don't have UI test in my project. Do I need to add that for `screengrab`?

**Comment by hjanuschka** [comment]
@RishabhTayal  yes you require to have a AndroidTest - see https://github.com/fastlane/fastlane/tree/master/screengrab#tips and https://developer.android.com/training/testing/ui-testing/espresso-testing.html

then you'll have to have atleast one uitest - that at some point will call:

```
Screengrab.screenshot("after_button_click");
```

wich actually produces the screenshot

**Comment by RishabhTayal** [comment]
Thanks. You can close this issue now.
