### ISSUE TITLE
How can I reuse same signing certificates on different apps?

### ISSUE THREAD

**Issue by jlubeck** [fastlane/fastlane#7021]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Up until now I was lucky enough to always use fastlane on different developer accounts, so I never ran into this situation. 

But today I had to create a new App inside the same account. And when I ran match to create the provisioning profiles, I got this message: 

> [!] Could not create another Development certificate, reached the maximum number of available Development certificates.

So I logged in, and I noticed new signing certificates were created for both production and development, even though I´m using the same computer.

Also, a very bad side note, is that old provisioning profiles created by match for another app, now appear as invalid.

How should I handle this situation??

NOTE: the repo used to store the certificates is different than the other project, although like I said, I am using the same computer and credentials. 

Thank you.

**Comment by jlubeck** [comment]
Yes, it is a code signing issue, but I couldn´t find my specific use case in the guide. And I don´t think the output of fastlane is relevant to this question. Thanks!

**Comment by hjanuschka** [comment]
as you use different repo's - its intended to to generate new signing identies, as they are not found in the git repo.


you should use one git repo per itunes account - you can have dozens of apps in one match repo.

**Comment by jlubeck** [comment]
Mmm, ok... so, as I didn´t know that before, the repo with the certificates is named after the project, and not the account. If I just clone the repo to a new one, and point match to that repo, should everything work as expected moving forward?

**Comment by hjanuschka** [comment]
can't you just rename the git repo (instead of clone, wich should work too.)? and then change the git url in your fastfile.

**Comment by jlubeck** [comment]
Yup, that worked too, and everything is running fine now. Thanks!!
