### ISSUE TITLE
Can I get the password of the p12 file generated by cert

### ISSUE THREAD

**Issue by Jianbo-Zhu** [fastlane/fastlane#7041]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

My app is build with 3rd party platform, telerik, I'm going to create the certificate with cert, and import the p12 file into telerik. However, I don't know the password of this p12 file. Please help!!

**Comment by TKBurner** [comment]
@Jianbo-Zhu Are you using `match`? Thanks!

**Comment by hjanuschka** [comment]
@Jianbo-Zhu  i am not sure if they are pw protected anyway, can you post a screenshot of the pw prompt? - probably it is from the keychain  - wich should be your accounts password?!
