### ISSUE TITLE
The unlock_keychain action is unaware of the new Sierra keychain location

### ISSUE THREAD

**Issue by jverdi** [fastlane/fastlane#7046]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
In `fastlane/fastlane/lib/fastlane/actions/unlock_keychain.rb`, the new Sierra keychain path of `~/Library/Keychains/login.keychain-db` is not included in the possible keychain locations. This results in failure when the command is run:

`Could not find the keychain file in: ["login", "~/Library/Keychains/login", "~/Library/Keychains/login.keychain"]`

### Environment

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| fastlane            | 1.109.0 | ✅ Up-To-Date  |

**Comment by hjanuschka** [comment]
on my machines i symlinked the keychain 😢  - anyway here is the PR - for adding `-db`  to availaible paths.

https://github.com/fastlane/fastlane/pull/7048

**Comment by jverdi** [comment]
Yup, as a workaround, a symlink works, as does supplying the full path to the new keychain to your Fastfile's `unlock_keychain` action. But, this should work out of the box.

**Comment by milch** [comment]
Linking back from here to the other 3 PRs -> #7075, #7076, #7077

**Comment by KrauseFx** [comment]
Is it correct that this was fixed @jverdi?

**Comment by jverdi** [comment]
@KrauseFx yes, it appears to work for me on Sierra now with the default path specified as "login". thanks
