### ISSUE TITLE
Pem: Add option to download push certificate if it exists

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#7050]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Trying to create an already existing push certificate throws there warnings:

> [11:11:32]: You already have a push certificate, which is active for more than 30 more days. No need to create a new one
> [11:11:32]: If you still want to create a new one, use the --force option when running PEM.

It would be great if there was an option that would let you only download it, if it exists. So something like:

> [11:11:32]: If you only want to download it, use the --download option when running PEM.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                        |
| ------------------- | -------------------------------------------- |
| OS                  | 10.11.6                                      |
| Ruby                | 2.0.0                                        |
| Bundler?            | true                                         |
| Git                 | git version 2.9.3 (Apple Git-75)             |
| Installation Source | /Users/Iulian/.gems/bin/fastlane             |
| Host                | Mac OS X 10.11.6 (15G1004)                   |
| Ruby Lib Dir        | /Users/Iulian/.rbenv/versions/2.0.0-p353/lib |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                    |
| Is contained        | false                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version       | 8.1                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.109.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
</details>

*generated on:* **2016-11-17**
</details>

**Comment by hjanuschka** [comment]
good point, i invalided mine a few times just to get a p12 file 😝 
here is a PR: https://github.com/fastlane/fastlane/pull/7052 trying to add a download existing certificates, lets see if it gets merged, maybe you 👍  it

**Comment by hjanuschka** [comment]
downloading existing push certificates is currently not support by apple, my initial thoughts where wrong the PR #7052  has been closed.

probably hacking in `match` support to pem, is a way? - keeping them in the same repo? 

@KrauseFx would that be a thing? or does it not fit in the use-case of match?
( i mean we could probably do it with https://github.com/hjanuschka/cryptex 😊 )

**Comment by revolter** [comment]
Hmm, yes, it downloads a `.cer` file, not a `.p12`.

Maybe add a `--replace` option that revokes any existing certificates?
So, if you generated profiles for a couple of your apps, but something happened and it stopped, if you want to re-generate them for all your apps, a couple of them would have 2 certificates.

**Comment by revolter** [comment]
Can the `--replace` option be implemented? Simply said, can Pem revoke a certificate too?

**Comment by bmwertman** [comment]
I'm also interested in this. I just added match to my fastfile. But Firebase requires me to upload a .p12 file. Now my .p12 certs on firebase are not in sync with the new provisioning profile created by match.

**Comment by KrauseFx** [comment]
@bmwertman you can always update the push cert without having to update the provisioning profile. This issue should be closed, there is no way to really download a p12, and just downloading the cer would be confusing for most users. 

We don't want to implement revoking, as it's a destructive action, that potentially breaks working setups.
