### ISSUE TITLE
fastlane requires  for windows  os ?

### ISSUE THREAD

**Issue by vishal901** [fastlane/fastlane#7051]
this tool working for window os??

**Comment by vishal901** [comment]
I have study for https://docs.fastlane.tools/ ,

System Requirements:
 fastlane requires macOS or Linux with Ruby 2.0.0 or above.
https://docs.fastlane.tools/

this tool support for windows 7 etc. or not????

**Comment by hjanuschka** [comment]
there are a few gems used, that just don't work on windows. i think `pty` for example - so as for now it seems not to be supported.

**Comment by asfalcone** [comment]
Going to close as a duplicate of #2082
