### ISSUE TITLE
[Feature Request] Disable/enable devices in spaceship?

### ISSUE THREAD

**Issue by grisevg** [fastlane/fastlane#7053]
Hey guys,

Is there a way to Disable/Re-enable devices in spaceship? Couldn't find anything in docs or source-code.
I have an account with tons of devices and was thinking of writing a script to manage it nicer.

UPDATE:
I've looked through chrome tools and these are the requests I've seen:

To disable device:
`POST` to `https://developer.apple.com/services-account/QH65B2/account/ios/device/deleteDevice.action`
with params: `teamId` and `deviceId`

And to enable device:
`POST` to `https://developer.apple.com/services-account/QH65B2/account/ios/device/enableDevice.action`
with params: `teamId`, `deviceId` (empty, with no value for some reason. Maybe it's optional), `deviceNumber` (UDID), `displayId` (not sure what it is)

UPDATE2:
Also `https://developer.apple.com/services-account/QH65B2/account/ios/device/listDevices.action` need to pass `includeRemovedDevices:true` and `includeAvailability:true` to include disabled devices.

**Comment by TKBurner** [comment]
@grisevg Thanks for reaching out. Would you be interested in implementing this in a PR? Thanks!

**Comment by grisevg** [comment]
@TKBurner Yeah sures

**Comment by grisevg** [comment]
@TKBurner done

**Comment by mfurtak** [comment]
Merged in #7067 🎉
