### ISSUE TITLE
Appfile: git recommandation

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#7054]
Why is Appfile recommended to be commited to git? I noticed it contains my `apple_id`, so it makes no sense at all to commit it as it is. Though the `team_id` could be commited.

Is there a way to split this file? As every team member has a different Apple ID.

In my case, `app_identifier` makes no sense too because I have 33 bundle identifiers for the same project. Can this be omitted?

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                        |
| ------------------- | -------------------------------------------- |
| OS                  | 10.11.6                                      |
| Ruby                | 2.0.0                                        |
| Bundler?            | true                                         |
| Git                 | git version 2.9.3 (Apple Git-75)             |
| Installation Source | /Users/Iulian/.gems/bin/fastlane             |
| Host                | Mac OS X 10.11.6 (15G1004)                   |
| Ruby Lib Dir        | /Users/Iulian/.rbenv/versions/2.0.0-p353/lib |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                    |
| Is contained        | false                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version       | 8.1                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.15.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.0  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.109.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
</details>

*generated on:* **2016-11-17**
</details>

**Comment by hjanuschka** [comment]
@revolter i just have "demo.app" in all my Appfiles :D - and set `app_identifier` on the other tools directly like `match`, `deliver`....

about the apple_id - we use one "fastlane" apple-id accross all devs. - but you can also set it to a dummy account, and set the account name on the tools - like with app_id.

```ruby
deliver(
  username: "myaccount@domain.com",
  app_identifier: "my.app.id"
)
```

you can also use ".env" files. as described here: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#environment-variables

e.g. if you set `DELIVER_USERNAME` in an .env file - you can totally ommit the `username` param.
and then just add the .env file to `.gitignore` - and every dev gets his own .env file.


does that help?

**Comment by revolter** [comment]
Immensely, this should be in the docs in a section named something like "Dealing with multiple apple ids/bundle identifiers".

Though, can apple id and bundle identifier be removed safely from that file?

**Comment by hjanuschka** [comment]
@revolter  i am not sure - just try it.
let me know if you found a solution for your issue - and please close the issue if so.

**Comment by revolter** [comment]
Seems to work. I'll reopen if anything comes up. Thanks!

**Comment by revolter** [comment]
Just noticed that I'll have to use:

```
PEM_USERNAME=my@email.address
DELIVER_USERNAME=my@email.address
```

which is a bit of an overkill. Isn't there a global environment variable for the username that will be used by all the commands?
