### ISSUE TITLE
Upload Android APK to S3

### ISSUE THREAD

**Issue by jerome-cp** [fastlane/fastlane#7058]
At Chauffeur Privé, we are big fans of fastlane tools so we propose a simple plugin to be able to upload an APK to amazon S3.

The current s3 upload plugin is very helpful but unfortunately it doesn't handle very well APKs.. so we decided to create a S3 APK plugin inspired by the actual s3 plugin.

The plugin is available here : 
https://github.com/transcovo/fastlane-plugin-s3-android

Feel free to download it, use it, comment it as needed :-)

I hope this will help some of us using fastlane with Android to build better apps

Cheeers

**Comment by asfalcone** [comment]
Thanks @jerome-cp 👍 

I'm going to close this issue since there isn't action we can take here. We'll be sure to include this plugin in the available plugins list on our next release 🚀

**Comment by jerome-cp** [comment]
Great ! 👍
