### ISSUE TITLE
Error when creating VoipPush cert

### ISSUE THREAD

**Issue by Fluzzarn** [fastlane/fastlane#7059]
### New Issue Checklist

- [:white_check_mark:] Updated fastlane to the latest version
- [:white_check_mark:] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Trying to create a VoipPush cert results in an error from the Apple Servers

	There were errors in the data supplied. Please correct and re-submit.
	No value was provided for the parameter &#x27;type&#x27;.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `create_pushkit_cert`
<details><summary>Output/Log</summary>

```

+-----------------------+---------+--------+
|               Used plugins               |
+-----------------------+---------+--------+
| Plugin                | Version | Action |
+-----------------------+---------+--------+
| fastlane-plugin-unzip | 1.0.1   | unzip  |
+-----------------------+---------+--------+

[11:36:27]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[11:36:27]: You require a gem, please call `fastlane_require 'spaceship'` before to ensure the gem is installed
[11:36:27]: -------------------------------------------------
[11:36:27]: --- Step: Verifying required fastlane version ---
[11:36:27]: -------------------------------------------------
[11:36:27]: Your fastlane version 1.109.0 matches the minimum requirement of 1.102.0  ✅
[11:36:27]: ------------------------------
[11:36:27]: --- Step: default_platform ---
[11:36:27]: ------------------------------
[11:36:27]: Driving the lane 'create_pushkit_cert' 🚀
[11:36:27]: ------------------------------------
[11:36:27]: --- Step: mkdir -p ../build-post ---
[11:36:27]: ------------------------------------
[11:36:27]: $ mkdir -p ../build-post
[11:36:29]: Successfully logged in
[11:36:31]: Variable Dump:
[11:36:31]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"airwatchDemonstration", :PLATFORM_NAME=>nil, :LANE_NAME=>"create_pushkit_cert"}
[11:36:31]: {"responseId"=>"ID", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"No value was provided for the parameter &#x27;type&#x27;.", "creationTimestamp"=>"2016-11-17T16:36:29Z", "protocolVersion"=>"QH65B2", "requestId"=>"", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com:443/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action", "httpCode"=>200, "suppressed"=>[], "validationMessages"=>[{"validationKey"=>"type", "validationUserMessage"=>"No value was provided for the parameter &#x27;type&#x27;."}]}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | mkdir -p ../build-post              | 0           |
+------+-------------------------------------+-------------+

[11:36:31]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  ECC and SHA-2 support in OpenSC.tokend
   https://github.com/OpenSC/OpenSC/issues/570 [open] 142 💬
   5 weeks ago

➡️  app name not in english
   https://github.com/fastlane/fastlane/issues/5236 [closed] 13 💬
   5 weeks ago

➡️  Discuss2
   https://github.com/carcabot/iCloud-Bypass/issues/12 [closed] 2523 💬
   02 Jul 2016

and 7 more at: https://github.com/fastlane/fastlane/search?q=Apple%20provided%20the%20following%20error%20info:%0A%09There%20were%20errors%20in%20the%20data%20supplied.%20Please%20correct%20and%20re-submit.%0A%09No%20value%20was%20provided%20for%20the%20parameter%20&%23x27;type&%23x27;.&type=Issues&utf8=✓

[!] Apple provided the following error info:
	There were errors in the data supplied. Please correct and re-submit.
	No value was provided for the parameter &#x27;type&#x27;.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.11.6                                           |
| Ruby                | 2.3.1                                             |
| Bundler?            | false                                             |
| Git                 | git version 2.7.4 (Apple Git-66)                  |
| Installation Source | /usr/local/bin/fastlane                           |
| Host                | Mac OS X 10.11.6 (15G31)                          |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                        |
| Is contained        | false                                             |
| Xcode Path          | /Applications/Xcode-7.3.1.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby

	lane :create_pushkit_cert do |options|
        require 'spaceship'
        	Spaceship.login("email@email.com", nil)
        	Spaceship.client.select_team
        	UI.message "Successfully logged in"
				csr, pkey = Spaceship::Certificate.create_certificate_signing_request

		
		voipcert = Spaceship::Certificate::VoipPush.create!(csr:csr,bundle_id:ENV["MY_APP_IDENTIFIER"])


	end
	
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| deliver             | 1.15.0  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.0  | ✅ Up-To-Date        |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| fastlane            | 1.109.0 | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | 🚫 Update availaible |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-unzip | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| addressable               | 2.4.0        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| colored                   | 1.2          |
| babosa                    | 1.0.2        |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.56.0       |
| multi_xml                 | 0.5.5        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| excon                     | 0.53.0       |
| plist                     | 3.2.0        |
| xcode-install             | 2.0.7        |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.2        |
| bundler                   | 1.13.6       |
| fastlane-plugin-unzip     | 1.0.1        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| bigdecimal                | 1.2.8        |
| psych                     | 2.1.1        |
</details>

*generated on:* **2016-11-17**
</details>

**Comment by sainttail** [comment]
I think based on the line [here] (https://github.com/fastlane/fastlane/blob/485199c8757113f2fdd1eee3448a0e0f3cd6d4e7/spaceship/lib/spaceship/portal/certificate.rb#L145) 

There is no `certificate_type_id` for `VoipPush`. That's why maybe it displays that error.

I also don't know how to get that `certificate_type_id` and want to know how to get them myself either.
My speculation is that if we manage to get that then we can use `fastlane` create `VoipPush`

Sorry for not able to solve your problem.

**Comment by Fluzzarn** [comment]
@sainttail 

As previous research into creating the cert, I outputted all of the certs currently on the account and VOIP Certificates corresponded with [E5D663CMZW](https://github.com/fastlane/fastlane/blob/485199c8757113f2fdd1eee3448a0e0f3cd6d4e7/spaceship/lib/spaceship/portal/certificate.rb#L154). So it might be that the VoipPush class doesn't have a key in IOS_CERTIFICATE_TYPE_IDS  so when .create! is called the type is set to an empty string instead of an exception being thrown?

**Comment by TKBurner** [comment]
@Fluzzarn Thanks for reaching out. Right now this isn't possible so I'm going to mark this as a feature request. I'd love to see a PR.

**Comment by hjanuschka** [comment]
the key was there  E5D663CMZW - but had the wrong class, changing from WebsitePush to VoipPush solved it - see pr #7087

**Comment by npomfret** [comment]
Could someone explain how to create a voip cert using fastlane tools?

**Comment by hjanuschka** [comment]
should be somthing like this:

```ruby
Spaceship.login("email@email.com", nil)
Spaceship.client.select_team
csr, pkey = Spaceship::Certificate.create_certificate_signing_request
voipcert = Spaceship::Certificate::VoipPush.create!(csr:csr,bundle_id:"app.identifier")

```

**Comment by npomfret** [comment]
Thanks for the reply.  I think you've assumed a lot more knowledge than I actually have!  What's this code?

**Comment by npomfret** [comment]
I added a lane to my fast file containing this code.  It ran fine, thanks!  But I'm very new to this and don't actually know what this has done.  What I'm after is the p12 file so I can send notifications from my server.  In the past, for regular push notification certs I've used something like :

`pem --development --verbose --generate_p12 --force --p12_password password --output_path path-to-config
`

Have you any idea how I can get hold o the p12 file for this voip cert?

**Comment by npomfret** [comment]
... ok, I've hacked together the following (though not tested it out yet).

```
  lane :voip_cert do
    app_identifier = "my.app.id"
    apple_id = "my-apple@email"
    output_path = "/path-to-config/config"
    p12_password = "blah"

    UI.important "Creating a new push certificate for app '#{app_identifier}'."

    Spaceship.login(apple_id)
    Spaceship.client.select_team
    csr, pkey = Spaceship::Certificate.create_certificate_signing_request
    cert = Spaceship::Certificate::VoipPush.create!(csr:csr,bundle_id:app_identifier)

    x509_certificate = cert.download
    certificate_type = "voippush"
    filename_base = "#{certificate_type}_#{app_identifier}"

    p12_cert_path = File.join(output_path, "#{filename_base}.p12")
    p12 = OpenSSL::PKCS12.create(p12_password, certificate_type, pkey, x509_certificate)
    File.write(p12_cert_path, p12.to_der)
    UI.message("p12 certificate: ".green + Pathname.new(p12_cert_path).realpath.to_s)

    x509_cert_path = File.join(output_path, "#{filename_base}.pem")
    File.write(x509_cert_path, x509_certificate.to_pem + pkey.to_pem)
    UI.message("PEM: ".green + Pathname.new(x509_cert_path).realpath.to_s)
  end
```

Which has created all the files I need... I think.  Is there the concept of development v's production certs for voip like there is for regular push notifications?
