### ISSUE TITLE
switching wi-fi network before uploading to iTunes Connect

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7070]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Is there a way to switch the wi-fi network before uploading to iTunes Connect?

**Comment by hjanuschka** [comment]
you want to turn wifi of your mac off? or off and on again, i don't get it.
whats the reason for it - maybe there is another fix for your problem? - i think this a bit out of scope from fastlane


anyway this should work (maybe you have to adjust `en0` - to your setup) :

```ruby
sh "networksetup -setairportpower en0 off"
sh "networksetup -setairportpower en0 on"
```

**Comment by RishabhTayal** [comment]
@hjanuschka  I have wi-fi 'A' and wi-fi 'B'. I am usually on wi-fi 'A', which is under firewall and it blocks the iTunes Connect ports. In order to upload to iTunes Connect, I need to manually switch to wi-fi 'B' each time. I am sure there are other solutions for this but just wanted to check if fastlane supports this since there is so much awesome things it can do. 😄

**Comment by hjanuschka** [comment]
@RishabhTayal try adding the following on top of your fastfile

```
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'
```

fixes most of the firewall issues.


anyway here is a way to switch network (adjust ssid and pw) 👍 

```ruby
sh "networksetup -setairportnetwork en0 SSID_OF_WIRELESS_NETWORK WIRELESS_NETWORK_PASSPHRASE"
```

**Comment by hjanuschka** [comment]
@RishabhTayal try adding the following on top of your fastfile

```
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'
```

fixes most of the firewall issues.


anyway here is a way to switch network (adjust ssid,pw and en0) 👍 

```ruby
sh "networksetup -setairportnetwork en0 SSID_OF_WIRELESS_NETWORK WIRELESS_NETWORK_PASSPHRASE"
```

**Comment by RishabhTayal** [comment]
I will try the `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS` option. Thanks.

**Comment by RishabhTayal** [comment]
@hjanuschka I can not believe I missed on this option till now. I have been looking for this option for over 8 months. Super amazing. 💯 

Works like a charm.

**Comment by hjanuschka** [comment]
so you did wifi-switch (by hand) for 8 months - poor you.
nice to know it works for you.
can you close the issue.

**Comment by RishabhTayal** [comment]
well I did not use `fastlane` for uploading to iTunes Connect till now. But now...
