### ISSUE TITLE
Update Product Bundle Identifier When Using update_info_plist (part 2)

### ISSUE THREAD

**Issue by mrubin** [fastlane/fastlane#7071]
I'd like to revisit the question posed in #2670.

Starting with Xcode 7, update_info_plist should be updating the bundle identifier in the project file, not in Info.plist.

(I am blocked by this in relation to code signing.. I'm switching teams and bundle IDs for certain builds and Xcode 8 does not pick up the change to the bundle id when it's modified via the Info.plist. Even though you can open up Xcode and the change is there... code signing doesn't work until you change the bundle id to something else and back to what you want it... then the change 'takes'.)

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C48b)                   |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
redacted
</details>

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| deliver             | 1.15.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.2   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.0        |
| xcodeproj                 | 1.3.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.6        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.56.0       |
| bundler                   | 1.13.1       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-11-17**
</details>

**Comment by mrubin** [comment]
I'm trying something like this.. and it looks like I got past the code signing issue with xcodebuild. It's building now.

Now we need something like `update_project_team` which does this.

```
# set_info_plist_value(path: 'myApp/Resources/Info.plist', key: 'CFBundleIdentifier', value: "foo")

path = 'myApp.xcodeproj/project.pbxproj'
UI.message("Updating product bundle identifier (foo) for the given project '#{path}'")
p = File.read(path)
p.gsub!(/PRODUCT_BUNDLE_IDENTIFIER = .*;/, "PRODUCT_BUNDLE_IDENTIFIER = foo;")
File.write(path, p)
UI.success("Successfully updated project settings to use product bundle identifier 'foo'")
```

**Comment by KITSTABLucianoMarisi** [comment]
Removing the `PRODUCT_BUNDLE_IDENTIFIER` altogether works as before, i.e. picking the `CFBundleIdentifier` modified by `update_info_plist`.

Probably a temporary solution though.

**Comment by TKBurner** [comment]
@mrubin Does that workaround work for you? Thanks!

**Comment by mrubin** [comment]
It does.

**Comment by TKBurner** [comment]
@mrubin Awesome! I'm going to mark this to see if anyone is interested in creating a longer term solution. Hope you have a great day!
