### ISSUE TITLE
Can't specify a custom dotenv .env file location

### ISSUE THREAD

**Issue by tristanbbq** [fastlane/fastlane#7072]
According to [docs](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md), I can specify custom .env files to load when running fastlane, but unfortunately it does not seem possible to specify a custom .env file **location**.

For example, I already have a `.env` file at the root of my project. I'd like to load that exact same file instead of having a duplicate in my /fastlane folder.

**Comment by TKBurner** [comment]
@tristanbbq Thanks for reaching out. Right now this isn't possible but we'd be interested in seeing this added. Let me know if you are interested in submitting a PR. 

Also, have you tried using imports? Thanks!

**Comment by tristanbbq** [comment]
@TKBurner: it'd be happy to contribute - not very familiar with the ruby world but I'll definitely give it a shot if it's not fixed anytime soon. Please keep me updated if it gets added in the meantime.
