### ISSUE TITLE
Fastlane Supply not respecting apk parameter, tries to upload all APKs generated

### ISSUE THREAD

**Issue by pscadiz** [fastlane/fastlane#7073]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a lane to build an android APK and submit to the store. The lane does four things:
1 - Build the APK, with output app-release-unsigned.apk
2 - Sign the -unsigned APK, with output app-release.apk
3 - Align the -release APK, which renames the current -release to app-release-unaligned.apk and outputs app-release.apk.

By now there are three APK files in app/build/outputs/apk

4 - When I run supply with the apk parameter supplied to "app/build/outputs/apk/app-release.apk", supply also tries to upload -unsigned.apk. Further checking shows that the apk_paths gets supplied with the paths of the three APKs created, and does not actually respect the apk parameter provided.

I am calling supply in the Fastfile as such:
```
supply(
  track: alpha,
  apk: "app/build/outputs/apk/app-release.apk"
)
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.11.5                                          |
| Ruby                | 2.3.1                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.7.4 (Apple Git-66)                 |
| OpenSSL Version     | OpenSSL 1.0.2f  28 Jan 2016                      |
| Is contained        | false                                            |
| Xcode Version       | 7.3.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| deliver             | 1.15.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.1  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.2   |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| multipart-post            | 2.0.0   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.11 |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| word_wrap                 | 1.0.0   |
| multi_json                | 1.12.1  |
| colored                   | 1.2     |
| babosa                    | 1.0.2   |
| rubyzip                   | 1.1.7   |
| gh_inspector              | 1.0.2   |
| credentials_manager       | 0.16.2  |
| fastlane_core             | 0.56.0  |
| multi_xml                 | 0.5.5   |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| activesupport             | 4.2.7.1 |
| io-console                | 0.4.6   |
| excon                     | 0.54.0  |
| plist                     | 3.2.0   |
| claide                    | 1.0.1   |
| xcode-install             | 2.0.8   |
| CFPropertyList            | 2.3.3   |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
| bundler                   | 1.13.6  |
</details>

*generated on:* **2016-11-18**
</details>

**Comment by asfalcone** [comment]
@pscadiz Could you try setting `apk_paths: nil` to explicitly clear the value in apk_paths?

I am surprised that it gets to the point up uploading multiple apks when you are explicitly passing the `apk` param because there should be [code to handle](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb#L72) that (and raise an exception). 

Can you also include the output of running supply so we can dig in further?

**Comment by pscadiz** [comment]
Hi @asfalcone 

Apparently I was missing the gradle clean task. Adding that before grade assemble worked with supply only being `supply(track:alpha)`

Also noting that setting `apk_paths: nil` works :)

Thanks a lot for this. Let me know if you still need the broken supply output and I can replicate that for you.

**Comment by asfalcone** [comment]
Thanks for confirming! Glad you're up and running. I'll close this issue out 👍

**Comment by GokhanArik** [comment]
I tried setting `apk_paths` nil didn't work. I do `gradle clean` before the foreach loop. I din't want to clean after each build since it will take longer.

**Comment by s-gagandeep** [comment]
hi @GokhanArik @asfalcone is there any way apart from  gradle clean, as it takes much longer time to build. I have around 20 flavors and corresponding 20 lanes for each flavor, so i clean and build again it takes lot of time.
I want to build all apks once and upload it one by one.
