### ISSUE TITLE
Support incremental builds

### ISSUE THREAD

**Issue by hfossli** [fastlane/fastlane#7079]
Currently `gym` builds an archive. Building archives is not incremental (it basically doesn't care about the derivedData). Building and uploading feature builds while developing locally can take quite some time. The whole app is built from ground up as it seems to me.

Would it be possible to support incremental builds?

**Comment by hfossli** [comment]
In `gym` what's the point of the `clean` option when building to archives which isn't incremental anyways? :)

**Comment by TKBurner** [comment]
Hi @hfossli this isn't a currently supported use case. We will track it as a feature request. Thanks!

**Comment by hfossli** [comment]
Perfect!
