### ISSUE TITLE
latest_testflight_build_number parameter error

### ISSUE THREAD

**Issue by weibel** [fastlane/fastlane#7081]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to obtain the latest build number on iTunes Connect Fastlane says
`FastlaneCore::Interface::FastlaneError: [!] 'live' value must be a String! Found TrueClass instead.`

This happens whether I provide a boolean or a string.

The command run from my Fastfile is
```
latest_testflight_build_number(
      initial_build_number: 0,
      live: true,
      team_id: "<redacted>",
      username: ENV['testflight_id']
    )
```

##### Complete output when running fastlane, including the stack trace and command used
```
DEBUG [2016-11-18 10:55:12.64]: Checking if there are any plugins that should be loaded...
INFO [2016-11-18 10:55:12.65]: -------------------------------------------------
INFO [2016-11-18 10:55:12.65]: --- Step: Verifying required fastlane version ---
INFO [2016-11-18 10:55:12.65]: -------------------------------------------------
INFO [2016-11-18 10:55:12.65]: Your fastlane version 1.110.0 matches the minimum requirement of 1.106.1  ✅
INFO [2016-11-18 10:55:12.65]: ------------------------------
INFO [2016-11-18 10:55:12.65]: --- Step: default_platform ---
INFO [2016-11-18 10:55:12.65]: ------------------------------
INFO [2016-11-18 10:55:12.69]: Driving the lane 'ios testflight_upload' 🚀
INFO [2016-11-18 10:55:12.70]: --------------------------------------------
INFO [2016-11-18 10:55:12.70]: --- Step: latest_testflight_build_number ---
INFO [2016-11-18 10:55:12.70]: --------------------------------------------
ERROR [2016-11-18 10:55:12.70]: You passed invalid parameters to 'latest_testflight_build_number'.
ERROR [2016-11-18 10:55:12.70]: Check out the error below and available options by running `fastlane action latest_testflight_build_number`
No matching processes belonging to you were found
WARN [2016-11-18 10:55:12.71]: Variable Dump:
INFO [2016-11-18 10:55:12.71]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios testflight_upload"}
ERROR [2016-11-18 10:55:12.71]: 'live' value must be a String! Found TrueClass instead.
INFO [2016-11-18 10:55:12.71]: Successfully generated documentation at path '<redacted>'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | latest_testflight_build_number      | 0           |
+------+-------------------------------------+-------------+

ERROR [2016-11-18 10:55:12.71]: fastlane finished with errors
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
FastlaneCore::Interface::FastlaneError: [!] 'live' value must be a String! Found TrueClass instead.

  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/ui/interface.rb:145:in `user_error!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/config_item.rb:72:in `valid?'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/config_item.rb:61:in `verify!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/configuration.rb:65:in `block in verify_value_exists'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/configuration.rb:59:in `each'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/configuration.rb:59:in `verify_value_exists'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/configuration.rb:43:in `initialize'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/configuration.rb:31:in `new'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/configuration/configuration.rb:31:in `create'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/configuration_helper.rb:8:in `parse'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:193:in `block (2 levels) in execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:187:in `block in execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:186:in `chdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:186:in `execute_action'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:207:in `block (2 levels) in parsing_binding'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/lane.rb:33:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:49:in `block in execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:45:in `chdir'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:45:in `execute'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/command_line_handler.rb:30:in `handle'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:95:in `block (2 levels) in run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane_core-0.56.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:292:in `run'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:36:in `start'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-1.110.0/bin/fastlane:5:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.4.1                           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_version "1.106.1"

default_platform :ios

platform :ios do

  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # increment_build_number
  end

  desc "Deploy a new version to Testflight"
  lane :testflight_upload do
    ENV['FASTLANE_USER'] = ENV['testflight_id']
    ENV['FASTLANE_PASSWORD'] = ENV['testflight_pw']

    current_build_number = latest_testflight_build_number(
      initial_build_number: 0,
      live: 'true',
      team_id: "<redacted>",
      username: ENV['testflight_id']
    )

    increment_build_number(
      build_number: current_build_number + 1
    )

    cocoapods

    %x(rake localization:send_translations)
    %x(rake localization:get_translations)

    match(
      git_url: "<redacted>",
      type: "appstore",
      team_id: "<redacted>",
      username: "<redacted>",
      readonly: true,
      app_identifier: ["<redacted>", "<redacted>"]
    )

    gym(
      clean: true,
      export_method: "app-store",
      output_name: "<redacted>",
      configuration: "Release",
      workspace: "<redacted>",
      scheme: "<redacted>",
      use_legacy_build_api: true
    )

    pilot(
      team_id: "<redacted>",
      username: ENV['testflight_id'],
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )

    clean_build_artifacts
  end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<redacted>" # The bundle identifier of your app
apple_id "<redacted>" # Your Apple email address

```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.0  | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| scan                | 0.14.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| snapshot            | 1.16.3  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| rake                      | 10.5.0       |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| awesome_print             | 1.7.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.2        |
| calabash-common           | 0.0.2        |
| clipboard                 | 1.1.1        |
| diff-lcs                  | 1.2.5        |
| multi_json                | 1.12.1       |
| gherkin                   | 2.12.2       |
| multi_test                | 0.1.2        |
| cucumber                  | 1.3.20       |
| edn                       | 1.1.1        |
| geocoder                  | 1.4.0        |
| httpclient                | 2.8.2.4      |
| command_runner_ng         | 0.1.0        |
| thor                      | 0.19.1       |
| run_loop                  | 2.2.1        |
| slowhandcuke              | 0.0.3        |
| calabash-cucumber         | 0.20.0       |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.4        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.1.1        |
| concurrent-ruby           | 1.0.2        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| hurley                    | 0.2          |
| mime-types                | 2.99.3       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| hashie                    | 3.4.6        |
| mini_portile2             | 2.0.0        |
| nokogiri                  | 1.6.7.2      |
| parallel                  | 1.9.0        |
| parallel_calabash         | 0.2.4        |
| rack                      | 1.6.5        |
| rack-protection           | 1.5.3        |
| rdoc                      | 4.3.0        |
| rest-client               | 1.8.0        |
| rspec-support             | 3.5.0        |
| rspec-core                | 3.5.4        |
| rspec-expectations        | 3.5.0        |
| rspec-mocks               | 3.5.0        |
| rspec                     | 3.5.0        |
| rtrail                    | 0.0.3        |
| tilt                      | 2.0.5        |
| sinatra                   | 1.4.7        |
| sim_launcher              | 0.4.13       |
| slather                   | 2.3.0        |
| smartling                 | 1.0.1        |
</details>

*generated on:* **2016-11-18**
</details>

**Comment by hjanuschka** [comment]
sorry for your problems, thx for the report - this PR should fix it: https://github.com/fastlane/fastlane/pull/7082

**Comment by hjanuschka** [comment]
in the meanwhile if you require the latest build number from live version.

you can use:

```
appstore_build_number(
      initial_build_number: 0,
      team_id: "<redacted>",
      username: ENV['testflight_id']
)
```

both are quite the same action.
