### ISSUE TITLE
Provide passphrase for Travis using match in fastlane

### ISSUE THREAD

**Issue by cepages** [fastlane/fastlane#7083]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Is there any way to pass the passphrase in match via fastlane. I'm using match for travis and I always stop asking for the passphrase:

>[10:34:59]: Cloning remote git repo...
>[10:35:16]: Enter the passphrase that should be used to encrypt/decrypt your certificates
>[10:35:16]: This passphrase is specific per repository and will be stored in your local keychain
>[10:35:16]: Make sure to remember the password, as you'll need it when you run match on a different machine
>Passphrase for Git Repo:

This is my current command:

```match(type: "adhoc", app_identifier: "app identifier", git_url: "git url", username: "username", readonly: true)```

I'm using the password environment variable, FASTLANE_PASSWORD for the password.

**Comment by cepages** [comment]
I think I found the solution:

I need to use `MATCH_PASSWORD` to use the passphrase.

Sorry, I hope this is useful for someone in the future :)

**Comment by pandaApe** [comment]
Can't understand. How to use MATCH_PASSWORD ? @cepages

**Comment by cepages** [comment]
@pandaApe 

`MATCH_PASSWORD= this is the passphrase for the certificate repo`

https://github.com/fastlane/fastlane/tree/master/match#passphrase

I added it in travis with 

```travis encrypt "MATCH_PASSWORD=thePassphrase" --add``` 

to escape special characters such as `!` you need to use two backward slash `\\!`
