### ISSUE TITLE
[Feature Request] Add support for build-for-testing and test-without-building

### ISSUE THREAD

**Issue by samskiter** [fastlane/fastlane#7086]
### Issue Description

XCode 8 added build-for-testing and test-without-building commands to xcodebuild - we could potentially use these to greatly speed up our CI system. It would be great if fastlane had a native way to support this.

**Comment by hjanuschka** [comment]
how about using the `xcodebuild` action?

```ruby
xcodebuild(
  clean: true,
  workspace: 'FiveXFive.xcworkspace',
  scheme: 'UITests',
  destination: 'generic/platform=iOS',
  configuration: 'Development',
  xcargs: " build-for-testing"
)
```

**Comment by hjanuschka** [comment]
see -> https://github.com/fastlane/fastlane/pull/7130

**Comment by samskiter** [comment]
@hjanuschka Looks good. Build for testing available too?

**Comment by hjanuschka** [comment]
@samskiter with this pr scan supports the use of a already build test app - just running it without building it.

what exactly do you wan't to do?

as described here: https://github.com/fastlane/fastlane/issues/7086#issuecomment-261608999  you already can - "just build" the test binary?


for snapshot  i also did a PR: https://github.com/fastlane/fastlane/pull/7131 - to only build once and run snapshot on different devices, using build-for-testing, test-without-building.

**Comment by samskiter** [comment]
I would like to build the artifacts, distribute them to different build machines and run them there.

The idea of scan is to be easy to use right?
"scan uses the latest APIs and tools to make running tests plain simple and offer a great integration into your existing workflow, like fastlane or Jenkins."

I'd like to use the same simple api that scan provides rather than trying to use xcodebuild if possible

**Comment by hjanuschka** [comment]
@samskiter ok got you!
updated my pr.

now following thing should work:

```ruby
  scan(derived_data_path: "my_folder", build_for_testing: true)
# copy the whole folder 'my_folder' to another machine

# run this on other machine
  scan(derived_data_path: "my_folder", test_without_building: true, skip_build: true)
```

**Comment by samskiter** [comment]
@hjanuschka looks great, thank-you!

**Comment by hjanuschka** [comment]
@samskiter please +1 the PR if you mind.
