### ISSUE TITLE
Error Uploading to iTunes Connect

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7092]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.9.3 (Apple Git-75)                |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2657)                      |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.108.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #

  lane :certificates do
    match(app_identifier: ['com.rtayal.Translate', 'com.rtayal.Translate.TranslateActionExtension', 'com.rtayal.Translate.TranslateClipboardExtension', 'com.rtayal.Translate.watchkitapp', 'com.rtayal.Translate.watchkitapp.watchkitextension'], type: 'development')
    match(app_identifier: ['com.rtayal.Translate', 'com.rtayal.Translate.TranslateActionExtension', 'com.rtayal.Translate.TranslateClipboardExtension', 'com.rtayal.Translate.watchkitapp', 'com.rtayal.Translate.watchkitapp.watchkitextension'], type: 'appstore')
  end

  lane :screenshots do 
  	snapshot(scheme: "Translate", stop_after_first_error: true, devices: ["iPhone 7 Plus"], languages: ["en-US"])
  	frameit(white: true)
  	deliver
  end

  lane :app_store do
    match(app_identifier: ['com.rtayal.Translate', 'com.rtayal.Translate.TranslateActionExtension', 'com.rtayal.Translate.TranslateClipboardExtension', 'com.rtayal.Translate.watchkitapp', 'com.rtayal.Translate.watchkitapp.watchkitextension'], type: 'appstore')
  	gym(scheme: 'Translate', use_legacy_build_api: true, export_method: 'app-store')
  	pilot(skip_waiting_for_build_processing: true)
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.rtayal.Translate" # The bundle identifier of your app
apple_id "contact@appikon.com" # Your Apple email address

# team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.56.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| babosa              | 1.0.2   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.56.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-11-18**
</details>

### Issue

Getting error while uploading to iTunes Connect using `pilot`. Below is the `Fastfile`.

<details><summary>Fastfile</summary>

```
fastlane_version "1.108.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #

  lane :certificates do
    match(app_identifier: ['com.rtayal.Translate', 'com.rtayal.Translate.TranslateActionExtension', 'com.rtayal.Translate.TranslateClipboardExtension', 'com.rtayal.Translate.watchkitapp', 'com.rtayal.Translate.watchkitapp.watchkitextension'], type: 'development')
    match(app_identifier: ['com.rtayal.Translate', 'com.rtayal.Translate.TranslateActionExtension', 'com.rtayal.Translate.TranslateClipboardExtension', 'com.rtayal.Translate.watchkitapp', 'com.rtayal.Translate.watchkitapp.watchkitextension'], type: 'appstore')
  end

  lane :screenshots do 
  	snapshot(scheme: "Translate", stop_after_first_error: true, devices: ["iPhone 7 Plus"], languages: ["en-US"])
  	frameit(white: true)
  	deliver
  end

  lane :app_store do
    match(app_identifier: ['com.rtayal.Translate', 'com.rtayal.Translate.TranslateActionExtension', 'com.rtayal.Translate.TranslateClipboardExtension', 'com.rtayal.Translate.watchkitapp', 'com.rtayal.Translate.watchkitapp.watchkitextension'], type: 'appstore')
  	gym(scheme: 'Translate', use_legacy_build_api: true, export_method: 'app-store')
  	pilot(skip_waiting_for_build_processing: true)
  end
end
```
</details>

<details><summary>Error</summary>

```
[14:37:20]: Login to iTunes Connect (.....)
[14:37:21]: Login successful
[14:37:22]: Ready to upload new build to TestFlight (App: ....)...
[14:37:23]: Going to upload updated app to iTunes Connect
[14:37:23]: This might take a few minutes. Please don't interrupt the script.
[14:38:03]: [Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.rtayal.Translate [Payload/Translate.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[14:38:03]: Transporter transfer failed.
[14:38:03]: 
[14:38:04]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.rtayal.Translate [Payload/Translate.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[14:38:04]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.rtayal.Translate [Payload/Translate.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
Return status of iTunes Transporter was 1: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.rtayal.Translate [Payload/Translate.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
[14:38:04]: Variable Dump:
[14:38:04]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios app_store", :SIGH_PROFILE_TYPE=>"app-store", :IPA_OUTPUT_PATH=>"/Users/rtayal/Desktop/Personal/Translate/Translate.ipa", :DSYM_OUTPUT_PATH=>"/Users/rtayal/Desktop/Personal/Translate/Translate.app.dSYM.zip", :XCODEBUILD_ARCHIVE=>"/Users/rtayal/Library/Developer/Xcode/Archives/2016-11-18/Translate 2016-11-18 14.36.02.xcarchive"}
[14:38:04]: Error uploading ipa file, for more information see above
```

</details>

**Comment by hjanuschka** [comment]
first of all try to remove: `use_legacy_build_api`  and `export_method`  from gym, and see if it works then.

**Comment by RishabhTayal** [comment]
@fastlane-bot I have followed the guide. I am using `match` to generate the provisioning profiles and storing them on private repo. The issue is that it's selecting `development` as code signing identity. If I specify the code signing identity in `gym` as `iPhone Distribution`, I get another error.

**Comment by hjanuschka** [comment]
@RishabhTayal see me post above, watchkit is not supported by `use_legacy_build_api`

**Comment by RishabhTayal** [comment]
@hjanuschka That worked. Thanks. Closing now.
