### ISSUE TITLE
Supply should support a dry run option

### ISSUE THREAD

**Issue by tmtrademarked** [fastlane/fastlane#7094]
I recently had an issue where I managed to break my master build on CI due to a failure to upload to Google Play. (I had stupidly left an APK as debuggable - d'oh!) This wasn't caught by my tests, since non-master branches don't run my deploy step.

The Google Play Publisher API supports a "validate edit" feature. This can be used to verify that the edit is valid without actually changing the data. This would have been super helpful for me.

From what I understand, this should be pretty trivial to implement. Thoughts?

**Comment by tmtrademarked** [comment]
I'm a terrible person, and decided to just create a sample pull request to see what it would take. But my ruby is very weak - so please feel free to ignore this if it's not a good way to fix this problem!

**Comment by milch** [comment]
> I'm a terrible person

Aww, don't be too hard on yourself. We love all our contributors equally! ❤️ 

> The Google Play Publisher API supports a "validate edit" feature. This can be used to verify that the edit is valid without actually changing the data. This would have been super helpful for me.

That does indeed sound like a very good idea. I'm gonna take a look at your PR now 🚀

**Comment by tmtrademarked** [comment]
Quick question here - what's the process look like for getting this into a release? No urgency, just curious about the flow of releases for the various tools.

**Comment by milch** [comment]
@tmtrademarked 

Unless there is an emergency bugfix or a large feature merged, we usually wait until there's a small number of PRs merged before we release a new version of one of the tools.
