### ISSUE TITLE
match always syncs the certificates/profiles on git repo

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#7099]
Hi,

I have been using fastlane quite successfully. 
But I have this question in mind from some time now.

I use match with force_for_new_devices true for all my profiles "dev, adhoc and store".
Every time when the build runs and I call match, it does some modifications to the certificates and profiles and syncs it to the git repo. I get a new git commit every time when match runs. This is happening even when am not adding any new device.

I feel match should do any modification on git only when new devices are added or profiles are generated or renewed. This will help to keep the git repo light and will result in faster cloning of the git repo.

**Comment by santoshshetty2612** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                   |
| ------------------- | ------------------------------------------------------- |
| OS                  | 10.12                                                   |
| Ruby                | 2.3.0                                                   |
| Bundler?            | false                                                   |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/             |
| Xcode Version       | 8.0                                                     |
| Git                 | git version 2.8.4 (Apple Git-73)                        |
| Installation Source | /Users/Shared/Jenkins/.rvm/gems/ruby-2.3.0/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                                 |
| Ruby Lib Dir        | /Users/Shared/Jenkins/.rvm/rubies/ruby-2.3.0/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                             |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.100.0"

#app Identifiers
app_ids = ['us.univadis.Consult']

#supported countries
supportedCountries = ['us','uk','fr']

private_lane :syncprofiles_for_app_identifier do |options|
	match(type: "development", readonly: !options[:admin], app_identifier: options[:app_identifier], force_for_new_devices: options[:admin])
	match(type: "adhoc", readonly: !options[:admin], app_identifier: options[:app_identifier], force_for_new_devices: options[:admin])
	if options[:admin] && !options[:ignoreappstore]
		match(type: "appstore", readonly: !options[:admin], app_identifier: options[:app_identifier], force_for_new_devices: options[:admin])
	end	
end

private_lane :pullprofiles do |options|
	app_ids.each do |appid|

		appidentifier = appid
		syncprofiles_for_app_identifier(app_identifier: appidentifier, admin: options[:admin])

		appidentifier = appid + ".alpha"
		syncprofiles_for_app_identifier(app_identifier: appidentifier, admin: options[:admin])

		appidentifier = appid + ".beta"
		syncprofiles_for_app_identifier(app_identifier: appidentifier, admin: options[:admin])

		appidentifier = appid + ".preprod"
		syncprofiles_for_app_identifier(app_identifier: appidentifier, admin: options[:admin])
	end 
	
end

lane :pullprofilesForAppId do |options|
	syncprofiles_for_app_identifier(app_identifier: options[:appidentifier], admin: options[:admin], ignoreappstore: options[:ignoreappstore])
end

def supportedAppIds(countryArray)
	supportedAppIdArray = Array.new
	countryArray.each do |country|
		app_id="#{country}.univadis.Consult"
		supportedAppIdArray = supportedAppIdArray + ["#{app_id}","#{app_id}.alpha","#{app_id}.beta","#{app_id}.preprod"]
	end 
	return supportedAppIdArray
end

def deleteProfilesWithName(name)
	#delete existing profiles.
	profiles_path = File.expand_path("~") + "/Library/MobileDevice/Provisioning Profiles/*.mobileprovision"
   	profile_paths = Dir[profiles_path]

	profile_paths.each do |profile_path|
		profile = Plist.parse_xml(`security cms -D -i '#{profile_path}'`)
		profileName=profile['Name']

		if profileName.include?(name)
			profile_path=profile_path.gsub(" ") {"\\ "}
			puts("🚀 Removing profile #{profileName}")
			sh "rm -rf #{profile_path}"       
		end	      		
   	end
end

def deleteProfilesForAppId(appId)
	deleteProfilesWithName(appId)
end

def deleteProfilesForCountry(country)
	profName="#{country}.univadis.Consult"
	deleteProfilesWithName(profName)
end

def get_profile_name(uuid)
    profiles_path = File.expand_path("~") + "/Library/MobileDevice/Provisioning\\ Profiles/*.mobileprovision"
    profile_paths = Dir[profiles_path]

    profile_paths.each do |profile_path|
      profile = Plist.parse_xml(`security cms -D -i '#{profile_path}'`)
      if profile['UUID'] == uuid
        return profile['Name']
      end
    end
end

lane :build do |options|
	appId="#{ENV["APP_ID"]}"
	configuration="#{ENV["XCODE_CONFIGURATION"]}"
	countryCode="#{ENV["COUNTRYCODE"]}"
	scheme="Univadis #{countryCode}"
	versionNum="#{ENV["VERSION_NUM"]}"
	buildNum="#{ENV["BUILD_NUM"]}"
	runUnitTests="#{ENV["RUN_UNIT_TEST"]}"
	
	sh "rm -rf ../../build"
	
	if runUnitTests == "yes"
		scan(
			scheme: "UnivadisTests",
			clean: true
		)
	end
		
	profiles(appid:"#{appId}", admin: options[:admin])
	
	projectRootPath="#{ENV["PROJECT_ROOT_PATH"]}"
	buildForStore="#{ENV["BUILD_FOR_STORE"]}"
	
	if configuration != "prod"
	   
	   imagesPath="./Univadis/Resources/Country/#{countryCode}/Images.xcassets"
	   
	   if "#{countryCode}" == "UK"
	   	  badge(custom: "./Univadis/badge/#{configuration}.png",shield:"#{countryCode}-#{buildNum}-ff69b4",shield_gravity:"South",path:"#{imagesPath}") 
	   elsif "#{countryCode}" == "FR"
	   	  badge(custom: "./Univadis/badge/#{configuration}.png",shield:"#{countryCode}-#{buildNum}-brightgreen",shield_gravity:"South",path:"#{imagesPath}")
	   else 
	   	  badge(custom: "./Univadis/badge/#{configuration}.png",shield:"#{countryCode}-#{buildNum}-blue",shield_gravity:"South",path:"#{imagesPath}")
	   end
	end
	
	adhocProfileId="#{ENV["sigh_#{appId}_adhoc"]}"
	storeProfileId="#{ENV["sigh_#{appId}_appstore"]}"
	
	profile_name_adhoc = get_profile_name("#{adhocProfileId}")
	profile_name_store = get_profile_name("#{storeProfileId}")
	
	outputDirAdhoc="../build/build-adhoc"
	outputDirStore="../build/build-store"
	
	ipaNameAdhoc="Consult-"+"#{countryCode}-"+"#{configuration}-"+"adhoc-"+"#{versionNum}-"+"#{buildNum}"
	ipaNameStore="Consult-"+"#{countryCode}-"+"#{configuration}-"+"store-"+"#{versionNum}-"+"#{buildNum}"

	cocoapods
	
	set_info_plist_value(path: "./Univadis/SupportingFiles/Country/#{countryCode}/Consult-Info.plist", key: 'CFBundleShortVersionString', value: "#{versionNum}")
	set_info_plist_value(path: "./Univadis/SupportingFiles/Country/#{countryCode}/Consult-Info.plist", key: 'CFBundleVersion', value: "#{buildNum}")
	
	gym(
		scheme: scheme,
		configuration: configuration,
		output_name: ipaNameAdhoc,
		output_directory: outputDirAdhoc,
		export_method: 'ad-hoc',
		xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile_name_adhoc}'", clean: true
	    )

	if buildForStore == "yes"
		gym(
		scheme: scheme,
		configuration: configuration,
		output_name: ipaNameStore,
		output_directory: outputDirStore,
		xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile_name_store}'", clean: true
		)
		
	end	

	sh "git checkout ../Univadis/Resources/Country/#{countryCode}/Images.xcassets/"
end


#usage fastlane uploadBuildToTesters group:"InternalTesters" notes:"Daily Build"

lane :uploadBuildToTesters do |options|
 configuration="#{ENV["XCODE_CONFIGURATION"]}"
 countryCode="#{ENV["COUNTRYCODE"]}"
 versionNum="#{ENV["VERSION_NUM"]}"
 buildNum="#{ENV["BUILD_NUM"]}"
	
 ipaFileName="../build/build-adhoc/Consult-"+"#{countryCode}-"+"#{configuration}-"+"adhoc-"+"#{versionNum}-"+"#{buildNum}.ipa"
 	
 crashlytics(
 	  crashlytics_path: "./Pods/Crashlytics",
      api_token: "5e2a1b3a7600d25d2ef6b2348781291b3fe405de",
      build_secret: "0f816421182f309f1aeeb26a2959435b1c20f278c8f56b1410be0fe954729af8",
      ipa_path: "#{ipaFileName}",
      groups: options[:group],
      notes: options[:notes]
    )
end

#######################################################################################################

#usage fastlane registerdevice uuid:25bd99805e2a22f437bdb1fd1613ce58c7f267cd name:"SShetty iPod"

lane :registerdevice do |options|
	register_devices(devices: {options[:name]=>options[:uuid]})
end

lane :xcodefix do
  install_xcode_plugin(github: 'https://github.com/neonichu/FixCode')
end


lane :profiles do |options|
	if options[:appid]
		country=options[:appid].slice(0, 2)
		deleteProfilesForAppId(country)
		pullprofilesForAppId(appidentifier:options[:appid], admin: options[:admin], ignoreappstore: options[:ignoreappstore])
	else
		supportedCountries.each do |country|
			deleteProfilesForCountry(country)
		end 
		
		appIdsArray= supportedAppIds(supportedCountries)
		pullprofilesForAppId(appidentifier:appIdsArray, admin: options[:admin], ignoreappstore: options[:ignoreappstore])
	end
end

lane :coredatabase do |options|
	
	if options[:country]
		selectedCountry=options[:country]
		sh "script/database.sh coredatabase #{selectedCountry}"
	else 
		sh "script/database.sh coredatabase"
	end
end

lane :database do |options|

	if options[:country]
		selectedCountry=options[:country]
		sh "script/database.sh database #{selectedCountry}"
	else 
		sh "script/database.sh database"
	end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "consult.ci@aptushealth.com" # Your Apple email address
team_id "H2W5J5JCK3"  # Developer Portal Team ID
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | 🚫 Update availaible |
| spaceship           | 0.36.2  | 🚫 Update availaible |
| snapshot            | 1.16.2  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.3.2   | 🚫 Update availaible |
| cert                | 1.4.3   | 🚫 Update availaible |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.2.1   | 🚫 Update availaible |
| gym                 | 1.11.3  | 🚫 Update availaible |
| pilot               | 1.11.1  | 🚫 Update availaible |
| scan                | 0.13.1  | 🚫 Update availaible |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.10.0  | 🚫 Update availaible |
| screengrab          | 0.5.3   | 🚫 Update availaible |
| fastlane            | 1.106.2 | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded***


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.12.5       |
| io-console                | 0.4.5        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.10      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.0        |
| xcodeproj                 | 1.2.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.2        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.53.0       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.2.2      |
| google-api-client         | 0.9.12       |
</details>


*generated on:* **2016-11-20**
</details>

**Comment by TKBurner** [comment]
@santoshshetty2612 I believe this is a product of the encryption, but will leave this open in case anyone as more insight. Thanks!

**Comment by santoshshetty2612** [comment]
Is there any update on this?
Git size is increasing because of profile syncs. If I have not changed anything, my profiles on Apple developer portal should not be updated.

Further while running my build on Jenkins, If I cancel the job when in between the profile syc, then next time when I run the build, the profiles on the Apple portal and the fastlane Gir repo is not in sync. If fastlane don't always upload new profiles then such problems will be resolved.
