### ISSUE TITLE
[sigh] Even if using wildcard provisioning profile, WKAppBundleIdentifier is rewritten

### ISSUE THREAD

**Issue by yukiasai** [fastlane/fastlane#7105]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm using app groups with iOS and Today extension. so I'm building with following configuration.

* iOS app
  * bundle identifier is `com.my.app`
  * use `com.my.app` provisioning profile. (Same as bundle identifier)
* Today extension
  * bundle identifier is `com.my.app.today`
  * use `com.my.app.today` provisioning profile. (Same as bundle identifier)
* Watch app
  * bundle identifier is `com.my.app.watch`
  * use `com.my.*` provisioning profile. (**Different form bundle identifier**)
* Watch app extension
  * bundle identifier is `com.my.app.watch.extension`
  * use `com.my.*` provisioning profile. (**Different form bundle identifier**)

In this case, when resign, the `WKAppBundleIdentifier` in `Info.plist` of Watch app extension becomes `com.my.*`.

When trying to installing application from deploygate etc., the following error is output to device log and installation will fail.

```
installd(MobileSystemServices)[52] <Notice>: 0x16dfdb000 -[MIBundle validatePluginMetadataWithError:]: 552: WatchKit 2 app extension's NSExtension.NSExtensionAttributes.WKAppBundleIdentifier value does not match WatchKit app's bundle ID (found "com.my.*"; expected "com.my.app.watch").
```

### Idea

Submited a pull request #7110

thank you.

**Comment by TKBurner** [comment]
@yukiasai Thanks for contributing! We are a little behind on pull requests but will work with you soon over there. I hope you have a wonderful week!

**Comment by asfalcone** [comment]
@yukiasai The PR looks good but it would be great to get some verification from the community that this meets their signing needs before merging. 👍

**Comment by mgrebenets** [comment]
@yukiasai, @asfalcone 
Hey there ~

I'm not sure what's the process, but this fix actually breaks our resigning.
I'm looking into more details, but once I have identified actual reason, what do I do next?
Do I reopen this issue or open a new one?

**Comment by mgrebenets** [comment]
I'm not sure on this code:

```
if [ "$REF_BUNDLE_ID" != "$NEW_REF_BUNDLE_ID" && ! "$NEW_REF_BUNDLE_ID" =~ \* ];
              then
```

Is it correct bash syntax?

I'm trying the following and getting errors:
```
 ~ git:(master) ✗ if [ au.com.commbank.commbank.apnscrypto =~ \* ]; then echo "Match"; fi
zsh: ~ not found
 ~ git:(master) ✗ if [ "au.com.commbank.commbank.apnscrypto" =~ \* ]; then echo "Match"; fi
zsh: ~ not found
 ~ git:(master) ✗
```

**Comment by mgrebenets** [comment]
So here's what I got in the end:

```
 ~ git:(master) ✗ REF_BUNDLE_ID="app.prod" NEW_REF_BUNDLE_ID="app"; if [[ "$REF_BUNDLE_ID" != "$NEW_REF_BUNDLE_ID" ]] && ! [[ ${NEW_REF_BUNDLE_ID} =~ '\*' ]]; then echo "YES"; else echo "NO"; fi
YES
 ~ git:(master) ✗ REF_BUNDLE_ID="app.prod" NEW_REF_BUNDLE_ID="app.*"; if [[ "$REF_BUNDLE_ID" != "$NEW_REF_BUNDLE_ID" ]] && ! [[ ${NEW_REF_BUNDLE_ID} =~ '\*' ]]; then echo "YES"; else echo "NO"; fi
NO
 ~ git:(master) ✗
```

I'll follow up with PR to `sigh` to use this syntax.

**Comment by mgrebenets** [comment]
zsh is apparently not the same as bush :/

```
bash-3.2$ REF_BUNDLE_ID="app.prod" NEW_REF_BUNDLE_ID="app.*"; if [[ "$REF_BUNDLE_ID" != "$NEW_REF_BUNDLE_ID" ]] && ! [[ ${NEW_REF_BUNDLE_ID} =~ \* ]]; then echo "YES"; else echo "NO"; fi
NO
bash-3.2$ REF_BUNDLE_ID="app.prod" NEW_REF_BUNDLE_ID="app"; if [[ "$REF_BUNDLE_ID" != "$NEW_REF_BUNDLE_ID" ]] && ! [[ ${NEW_REF_BUNDLE_ID} =~ \* ]]; then echo "YES"; else echo "NO"; fi
YES
bash-3.2$
```

**Comment by mgrebenets** [comment]
still current code seems to be causing error in bash 3.2

```
bash-3.2$ REF_BUNDLE_ID="app.prod" NEW_REF_BUNDLE_ID="app.*"; if [ "$REF_BUNDLE_ID" != "$NEW_REF_BUNDLE_ID" && ! "$NEW_REF_BUNDLE_ID" =~ \* ]; then echo "YES"; else echo "NO"; fi
bash: [: missing `]'
NO
bash-3.2$ REF_BUNDLE_ID="app.prod" NEW_REF_BUNDLE_ID="app"; if [ "$REF_BUNDLE_ID" != "$NEW_REF_BUNDLE_ID" && ! "$NEW_REF_BUNDLE_ID" =~ \* ]; then echo "YES"; else echo "NO"; fi
bash: [: missing `]'
NO
bash-3.2$
```

**Comment by asfalcone** [comment]
[_sigh_ 1.12.1](https://github.com/fastlane/fastlane/releases/tag/sigh/1.12.1) has been released with the fix. Thanks @mgrebenets

**Comment by jvashishtha** [comment]
This seems to have broken our signing. Embedded extensions resigning is no longer working for us when using a non wildcard identifier.

**Comment by asfalcone** [comment]
@jvashishtha Could you please open a new issue with full details? You can link to this issue if you think it is related. Thanks 👍

**Comment by mgrebenets** [comment]
+1. @jvashishtha 
We're using 12.1 for resigning our app, which has watchkit app and extension.
Just resigned on couple of ours ago.
So would be good to have it as separate issue with more details.

**Comment by jvashishtha** [comment]
I opened #7977 .
