### ISSUE TITLE
Pointers to use Spaceship to select existing ITC members as internal testers...

### ISSUE THREAD

**Issue by erikjthomas** [fastlane/fastlane#7115]
Can anyone share pointers for how I can use Spaceship to add existing ITC users as INTERNAL TestFlight testers for an app, select the latest version, and kick off an internal test?

Note the following:
* I do NOT need to create internal testers. They already exist in our account.
* I cannot use external testers because of the review delay.

Reading about Pilot I see it is not going to do this for us since it deals only with external testers. There is an existing issue from August sort of related: https://github.com/fastlane/fastlane/issues/5539

This functionality in Pilot would be so cool for us but I'm willing to try and figure out how to do this with Spaceship directly, if it is possible since Pilot doesn't do it. I'm already using some direct Spaceship stuff from my ruby scripts.

If interested in why we need this: we automate branding of white-label apps and it is not uncommon for us to submit 45+ apps per day to ITC, and for each one, I need to go into ITC->New App->TestFlight after uploading, and choose two internal testers from our already registered ITC team members, and select the latest build and kick a new test so these internal testers (employees of my company) receive an email notice that a new app is ready for sanity testing.

If I could automate this with my submission script it would be super helpful! Regardless, I have to give a big shout-out of how awesome fastlane is. Thanks to all who had anything to do with its development!

**Comment by erikjthomas** [comment]
OK, I figured out how to do the first part of this and it's just too easy! You fastlane contributors rock!

Spaceship::Tunes.login(admin_email, password)
app = Spaceship::Tunes::Application.find(bundle_id)
tester = Spaceship::Tunes::Tester::Internal.find(tester_email)
tester.add_to_app!(app.apple_id)

Voila! Excellent. Now I need to spelunk Spaceship code to find how to kick an internal test...

**Comment by hjanuschka** [comment]
@erikjthomas  it should be like:

```ruby
Spaceship::Tunes.login(admin_email, password)
app = Spaceship::Tunes::Application.find(bundle_id)
tester = Spaceship::Tunes::Tester::Internal.find(tester_email)
tester.remove_from_app!(app.apple_id)
```

**Comment by erikjthomas** [comment]
Hey hjanuschka, I needed to add not remove. But thanks for confirming my approach is correct. Appreciate it!

**Comment by hjanuschka** [comment]
@erikjthomas thought becaus you said you need to kick an tester. 😄  i needed to google `spelunk` 👏

**Comment by erikjthomas** [comment]
Ah, I see. Thanks, for your help. 

If you still have any suggestions for where in Spaceship I could initiate/start a new internal test of the latest uploaded version of an app, that would be super helpful. I've been searching through Spaceship sources and haven't yet found anything to do this.

Anyway, thanks again for responding with help!
