### ISSUE TITLE
Unable to run match or match nuke, says password is incorrect

### ISSUE THREAD

**Issue by mofojed** [fastlane/fastlane#7127]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I've been using fastlane/match successfully for a while now, but now today when I try to run match, it gives me an error about my password being incorrect. I haven't changed my password, and it didn't used to ask me before, so I'm not sure why it's asking now. I entered the correct password but it didn't work.

I read in a previous issue (https://github.com/fastlane/fastlane/issues/4020), and the suggestion there was to run `match nuke`, but even when I run that, it's asking me for the passphrase.

How do I fix this?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
INFO [2016-11-21 18:57:13.61]: Successfully loaded '/Users/bender/dev/redcurrent/redcurrent-ios/RedCurrent/fastlane/Matchfile' 📄

+----------------------+-----------------------------------------------------------+
|                   Detected Values from './fastlane/Matchfile'                    |
+----------------------+-----------------------------------------------------------+
| git_url              | git@source.redcurrent.com:redcurrent/ios-code-signing.git |
| type                 | development                                               |
+----------------------+-----------------------------------------------------------+

DEBUG [2016-11-21 18:57:13.61]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+-----------------------------------------------------------+
|                             Summary for match 0.11.0                              |
+-----------------------+-----------------------------------------------------------+
| verbose               | adhoc                                                     |
| git_url               | git@source.redcurrent.com:redcurrent/ios-code-signing.git |
| type                  | adhoc                                                     |
| git_branch            | master                                                    |
| app_identifier        | com.redcurrent.RedCurrent                                 |
| username              | bender@redcurrent.com                                     |
| keychain_name         | login.keychain                                            |
| readonly              | false                                                     |
| team_id               | 47TEXE9F4X                                                |
| force                 | false                                                     |
| skip_confirmation     | false                                                     |
| shallow_clone         | false                                                     |
| force_for_new_devices | false                                                     |
| skip_docs             | false                                                     |
+-----------------------+-----------------------------------------------------------+

INFO [2016-11-21 18:57:13.62]: Cloning remote git repo...
INFO [2016-11-21 18:57:13.62]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@source.redcurrent.com:redcurrent/ios-code-signing.git' '/var/folders/q2/kgvshx8s3n373l28wwwcr_j80000gn/T/d20161121-67478-aodufw'
INFO [2016-11-21 18:57:13.63]: ▸ Cloning into '/var/folders/q2/kgvshx8s3n373l28wwwcr_j80000gn/T/d20161121-67478-aodufw'...
INFO [2016-11-21 18:57:14.88]: ▸ remote: Counting objects: 97, done.
INFO [2016-11-21 18:57:14.95]: ▸ remote: Compressing objects: 100% (90/90), done.
INFO [2016-11-21 18:57:15.79]: ▸ remote: Total 97 (delta 9), reused 0 (delta 0)
INFO [2016-11-21 18:57:15.80]: ▸ Receiving objects: 100% (97/97), 231.00 KiB | 205.00 KiB/s, done.
INFO [2016-11-21 18:57:15.80]: ▸ Resolving deltas: 100% (9/9), done.
INFO [2016-11-21 18:57:15.80]: ▸ Checking connectivity... done.
WARN [2016-11-21 18:57:15.84]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2016-11-21 18:57:15.84]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2016-11-21 18:57:15.84]: Make sure to remember the password, as you'll need it when you run match on a different machine
Passphrase for Git Repo: ****************
Type passphrase again: ****************
bad decrypt
140736029340608:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:crypto/evp/evp_enc.c:529:
ERROR [2016-11-21 18:57:17.70]: Couldn't decrypt the repo, please make sure you enter the right password!
keychain: "/Users/bender/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@source.redcurrent.com:redcurrent/ios-code-signing.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303136313132313233353731375A00  "20161121235717Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303136313132313233353731375A00  "20161121235717Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@source.redcurrent.com:redcurrent/ios-code-signing.git"
    "type"<uint32>=<NULL>
password has been deleted.
WARN [2016-11-21 18:57:17.77]: Enter the passphrase that should be used to encrypt/decrypt your certificates
WARN [2016-11-21 18:57:17.77]: This passphrase is specific per repository and will be stored in your local keychain
WARN [2016-11-21 18:57:17.77]: Make sure to remember the password, as you'll need it when you run match on a different machine
INFO [2016-11-21 18:57:19.18]: 🔒  Successfully encrypted certificates repo
/Users/bender/.rvm/gems/ruby-2.3.0/gems/highline-1.7.8/lib/highline/system_extensions.rb:250:in `getbyte': Interrupt
	from /Users/bender/.rvm/gems/ruby-2.3.0/gems/highline-1.7.8/lib/highline/system_extensions.rb:250:in `get_character'
	from /Users/bender/.rvm/gems/ruby-2.3.0/gems/highline-1.7.8/lib/highline.rb:899:in `get_response'
	from /Users/bender/.rvm/gems/ruby-2.3.0/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.57.0/lib/fastlane_core/ui/implementations/shell.rb:111:in `password'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.57.0/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/change_password.rb:17:in `block in ask_password'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/change_password.rb:16:in `loop'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/change_password.rb:16:in `ask_password'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:21:in `password'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:51:in `block in decrypt_repo'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:70:in `block in iterate'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:68:in `each'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:68:in `iterate'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:48:in `decrypt_repo'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:57:in `rescue in block in decrypt_repo'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:49:in `block in decrypt_repo'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:70:in `block in iterate'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:68:in `each'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:68:in `iterate'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/encrypt.rb:48:in `decrypt_repo'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/git_helper.rb:39:in `clone'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/runner.rb:13:in `run'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
	from /Users/bender/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/bender/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/bender/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.57.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/bender/.rvm/gems/ruby-2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/commands_generator.rb:119:in `run'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/lib/match/commands_generator.rb:12:in `start'
	from /Users/bender/.rvm/gems/ruby-2.3.0@global/gems/match-0.11.0/bin/match:6:in `<top (required)>'
	from /Users/bender/.rvm/gems/ruby-2.3.0/bin/match:23:in `load'
	from /Users/bender/.rvm/gems/ruby-2.3.0/bin/match:23:in `<main>'
	from /Users/bender/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/bender/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.3.0                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.9.3 (Apple Git-75)                |
| Installation Source | /Users/bender/.rvm/gems/ruby-2.3.0/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                      |
| Ruby Lib Dir        | /Users/bender/.rvm/rubies/ruby-2.3.0/lib        |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  changelog = ''

  before_all do
    changelog = `./changelog.sh`

    sh "./update_bundle_version.sh"    

    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Debug build to TestFairy"
  lane :debug do
    UI.message "Creating debug build with changes:\n #{changelog}"
    register_devices(devices_file: "fastlane/devices.txt")
    match(app_identifier: "com.redcurrent.RedCurrent-Debug", type: "adhoc")
    gym(scheme: "RedCurrent-Debug", configuration: "Debug", output_name: "RedCurrent-Debug.ipa", output_directory: "archives")
    testfairy(api_key: '******', comment: changelog)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    UI.message "Creating release build with changes:\n #{changelog}"
    #sigh(output_path: "profiles")
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "RedCurrent", configuration: "Release", output_name: "RedCurrent-Release.ipa", output_directory: "archives") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

#  desc "Deploy a new version to the App Store"
#  lane :appstore do
    # match(type: "appstore")
    # snapshot
#    gym(scheme: "RedCurrent") # Build your app - more options available
#    deliver(force: true)
    # frameit
#  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    #sh "./update_bundle_version.sh"
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.redcurrent.RedCurrent" # The bundle identifier of your app
apple_id "bender@redcurrent.com" # Your Apple email address

team_id "47TEXE9F4X"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.0  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| deliver             | 1.15.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.57.0       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
</details>

*generated on:* **2016-11-21**
</details>

**Comment by mofojed** [comment]
Yes fastlane-bot, I've checked the Code Signing Troubleshooting Guide. I can't run `match nuke distribution` (error above) or `match init` (says `Matchfile` already exists). 

I'm pretty sure I've got the right password, but shouldn't I be able to `nuke` even if I've forgotten the password? And it's cloning from the git repo fine... I'm not sure what to try next.

**Comment by fernandes456** [comment]
Same problem here =/
But some Macs doesn’t have this problem.
I noticed the Macs that match works fine have the keychain password “match_git@your-git-repository”, so, it’s not necessary to type the password again. But i can’t put this password manually in key chain :-(

I tried to put the environment variable MATCH_PASSWORD, but didn’t work either.

**Comment by TKBurner** [comment]
@fernandes456 @mofojed Thanks for letting us know. Has this setup previously worked?

**Comment by mofojed** [comment]
Yes - it last worked for me a four days ago, and I'm not aware of anything that I've changed. I've confirmed there have been no commits to the code signing repo in a month, and the only change in the Fastfile or Matchfile in the past month is updating my upload key for TestFairy (which comes after this step, so should not matter).

**Comment by asfalcone** [comment]
Are all of the machines experiencing this problem running macOS Sierra? Does the same setup work on an older OS?

**Comment by fernandes456** [comment]
All machines are using macOS El Captain.
@TKBurner this setup worked just fine, until I removed the keychain.

I investigated a bit and found new details.

We have two projects. The project in default branch (master) does not have this problem. The error only occurs in the other project.
I'll try to upload the certificates following the steps in the site:
http://macoscope.com/blog/simplify-your-life-with-fastlane-match/

**Comment by mofojed** [comment]
My machine is using Sierra and it's not working. I tried my old machine with El Capitan, and it was able to decrypt the certs correctly.

I tried uninstalling/reinstalling fastlane (`sudo gem uninstall fastlane`) to see if that made a difference, no luck.

**Comment by mofojed** [comment]
Figured it out. Looks like it was using the wrong OpenSSL. Installed the latest OpenSSL and put it on the path, and now we're all good.
