### ISSUE TITLE
Uploading apk to alpha testing on Google Play Store for Android

### ISSUE THREAD

**Issue by stracatone** [fastlane/fastlane#7134]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is it possible to upload apk to alpha testing for Android?

**Comment by hjanuschka** [comment]
supply can do that for you 😄 
```ruby
supply({
    key: "fastlane/google_play_key.p12",
    track: "beta",
    apk: "app/build/outputs/apk/app-release.apk"
    })
```

**Comment by asfalcone** [comment]
@stracatone I'm going to close out this issue because @hjanuschka has the right answer for you!
