### ISSUE TITLE
[Snapshot] How to get detailed test result after running snapshot command

### ISSUE THREAD

**Issue by luisxiaomai** [fastlane/fastlane#7139]

**Comment by luisxiaomai** [comment]
@fastlane-bot , thanks for your quick answer.
My question is that I only installed snapshot and run it with 5 devices which was described in snapfile. After running snapshot I got a nice screenshot summary but without 5 devices detailed test result. I hope it can also generate detailed test report just like scan do.

**Comment by hjanuschka** [comment]
@luisxiaomai the bot just trys to help us get the info.

about your issue, i had the same problem, and ended with the following:

```ruby
snapshot(workspace: "app.xcworkspace",
           scheme: "Scheme",
           devices:  ['iPhone 6'],
           languages: ['en-US'],
           clear_previous_screenshots: true,
           reinstall_app: true,
           clean: clean,
           buildlog_path: 'fastlane/logs',
           skip_open_summary: true,
           xcpretty_args: '--report html --output fastlane/logs/test_report.html  -t')
```

please modify according to your project, the key is the `xcpretty_args` option.
in that case you ll find a html in `fastlane/logs/test_report.html`

**Comment by luisxiaomai** [comment]
@hjanuschka , it's ok to see one html report with your suggestion. But it only display last device test result, it can't display all devices test result. Last device test result will overwrite previous device test result.

**Comment by hjanuschka** [comment]
ahhh - ok true point.
as a hotfix could'nt you do it like:

```ruby
[ "iPhone6", "iPhone5"].each do | dev |
    snapshot(workspace: "app.xcworkspace",
           scheme: "Scheme",
           device: dev,
           languages: ['en-US'],
           clear_previous_screenshots: false,
           reinstall_app: true,
           clean: clean,
           buildlog_path: 'fastlane/logs',
           skip_open_summary: true,
           xcpretty_args: "--report html --output fastlane/logs/test_report#{dev}.html  -t")
end
```

surly for the language you would require another `each` - not sure if this should be a native feature of snapshot.

**Comment by luisxiaomai** [comment]
@hjanuschka , sure we can do in invoke snapshot command level.
But I hope snapshot can implement it just like scan do.  Scan can merge all test results in one test report.

**Comment by hjanuschka** [comment]
ok got you, you are right, lets keep this issue and see if it gets a few +1 and wait what core members think about it.
