### ISSUE TITLE
Could not set team ID to 'xxxxxxxxxx', only found the following available teams: 118361725, 118103445, 118225401, 118456689 

### ISSUE THREAD

**Issue by singhamit089** [fastlane/fastlane#7142]
While uploading the build to iTunes Connect with "Deploy to iTunes Connect / TestFlight (with Deliver)" There seems to be problem with it detecting my team_id

Even tough I have provided the team_id it couldn't find it.

Where did the issue happen? -> Deploy to iTunes Connect / TestFlight (with Deliver)

**Comment by hjanuschka** [comment]
can you run `fastlane env` and also post your deliverfile?
is your team in the "available list" ?

**Comment by singhamit089** [comment]
@hjanuschka I am using bitrise.io to do this, following is the log which was generated and what I supply as my team is an alpha-numeric team id, whereas the the list which is printed is numeric team_ids. So no the available list doesn't contain my team id and as a matter of fact among all the teams I have no team has any ID similar to ones being printed
**+------------------------------------------------------------------------------+
| (7) deploy-to-itunesconnect-deliver@2.6.2                                    |
+------------------------------------------------------------------------------+
| id: deploy-to-itunesconnect-deliver                                          |
| version: 2.6.2                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-11-22T10:14:43-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
Config:
 * ipa_path: /Users/vagrant/deploy/XXX_Prod.ipa
 * pkg_path: 
 * itunescon_user: XXX@heady.io
 * password: ***
 * app_id: XXXXXXXXXX
 * submit_for_beta: no
 * skip_metadata: yes
 * skip_screenshots: yes
 * team_id: *my_alpha_numeric_team_id*
 * team_name: XXXXXXXXXX
 * update_deliver: yes

# Setup

 (i) deliver already installed
 (i) updating  deliver...

 (i) Which ruby: /usr/local/bin/ruby
 (i) Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]

 -> using brew (/usr/local/bin/ruby) ruby
$ gem install deliver --no-document
Successfully installed credentials_manager-0.16.2
Successfully installed spaceship-0.37.0
Successfully installed fastlane_core-0.57.0
Successfully installed deliver-1.15.1
4 gems installed

 (i) Setup took 2 seconds to complete


# Deploy


**Note:** if your password
contains special characters
and you experience problems, please
consider changing your password
to something with only
alphanumeric characters.


**Be advised** that this
step uses a well maintained, open source tool which
uses *undocumented and unsupported APIs* (because the current
iTunes Connect platform does not have a documented and supported API)
to perform the deployment.
This means that when the API changes
**this step might fail until the tool is updated**.

[10:14:49]: Login to iTunes Connect (dev@heady.io)

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
	Could not set team ID to '*my_alpha_numeric_team_id*', only found the following available teams: 118361725, 118103445, 118225401, 118456689
 [!] Error description: Deploy failed!
     (i) Exit code was: 1
 (i) Calling cleanup function before exit
-> finalcleanup

# Error


**Error Description**:


Deploy failed!


*See the logs for more information*


**If this is the very first build**
of the app you try to deploy to iTunes Connect then you might want to upload the first
build manually to make sure it fulfills the initial iTunes Connect submission
verification process.

|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | deploy-to-itunesconnect-deliver@2.6.2 (exit code: 1)          | 9.07 sec |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...om/bitrise-io/steps-deploy-to-itunesconnect-deliver/issues |
| Source: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver  |
+---+---------------------------------------------------------------+----------+**

**Comment by hjanuschka** [comment]
ok thx - i am not familiar with bitrise, can you share your fastfile?

**Comment by viktorbenei** [comment]
@hjanuschka the Bitrise Deliver step runs `deliver` directly, without using `fastlane` - see: https://github.com/bitrise-io/steps-deploy-to-itunesconnect-deliver/blob/master/step.sh#L134

Basically: `deliver --team_id "${team_id}" ...`

**Comment by viktorbenei** [comment]
Based on the non redacted log, it seems that Deliver might expect a different kind of team id. The user specified the team ID from the Apple Developer Portal, the one which is e.g. in the Provisioning Profiles.

Related infos: https://github.com/bitrise-io/build.issues/issues/10#issuecomment-262468196

> My guess, based on the log, is that `deliver` might require some kind of internal team ID - if you check the error, the Developer Team ID you specified is alpha numerical (e.g. `12345A12B1`), while the IDs deliver lists as "available" team IDs include only numbers, and are 1 character shorter too (e.g. `123456789`).
>
> Relevant part of the log (with changed value):
> 
> ```
> Could not set team ID to '12345A12B1', only found the following available teams: 123456789, 223456789, 323456789, 423456789
> ```

Can this be the issue? Is this expected, or a `deliver` bug?

**Comment by hjanuschka** [comment]
you can run spaceship from commandline
and get the right team id by:

```
spaceship
Spaceship.client.teams
```

it should output the teams object - where you can find the id under `teamId`

for the first team you can do it like this.

```
Spaceship.client.teams.first["teamId"]
```

**Comment by viktorbenei** [comment]
Was this changed? I believe the team id param of `deliver` used to accept the Developer Team ID, but I might be wrong (we don't have a test where we'd use the Team ID, we always use the Team Name param)

**Comment by hjanuschka** [comment]
not sure if this was changed, i don't think so - can you test with the sample above, and let me know if it works.?

**Comment by viktorbenei** [comment]
I believe @singhamit089 resolved this issue by using the team name parameter instead of the team ID param - https://github.com/bitrise-io/build.issues/issues/10#issuecomment-262468196 & https://github.com/bitrise-io/build.issues/issues/10#issuecomment-262694209
