### ISSUE TITLE
Sigh - No value found for 'uuid'

### ISSUE THREAD

**Issue by igorstimoli** [fastlane/fastlane#7145]
### Issue Description
@hjanuschka
Since the last fastlane update v 1.110.0 I get "No value found for uuid" in the Sigh step

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
+-------------------------------------+----------------------------------+
|                        Summary for sigh 1.11.2                         |
+-------------------------------------+----------------------------------+
| force                               | true                             |
| adhoc                               | false                            |
| development                         | false                            |
| skip_install                        | false                            |
| app_identifier                      | ************ |
| username                            | ************    |
| team_id                             | ************                       |
| team_name                           | ************                       |
| ignore_profiles_with_different_name | false                            |
| cert_id                             | ************                       |
| skip_fetch_profiles                 | false                            |
| skip_certificate_verification       | false                            |
+-------------------------------------+----------------------------------+

[10:30:06]: Starting login with user '************'
[10:30:08]: Successfully logged in
[10:30:08]: Fetching profiles...
[10:30:09]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[10:30:29]: Creating new provisioning profile for '************' with name '************'
[10:30:32]: Downloading provisioning profile...
[10:30:34]: Successfully downloaded provisioning profile...
[10:30:34]: Installing provisioning profile...
************.mobileprovision
[10:30:34]: Setting Provisioning Profile type to 'app-store'
[10:30:36]: Variable Dump:
[10:30:36]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy", :BUILD_NUMBER=>"There does not seem to be a CURRENT_PROJECT_VERSION key set for this project.  Add this key to your target's expert build settings.", :PRODUCE_APPLE_ID=>"************", :CERT_FILE_PATH=>"/Users/Shared/Jenkins/Home/workspace/iOS Build - Complete Release/iOS/************.cer", :CERT_CERTIFICATE_ID=>"************", :SIGH_PROFILE_PATH=>"/Users/Shared/Jenkins/Home/workspace/iOS Build - Complete Release/iOS/AppStore_com.************.************.mobileprovision", :SIGH_PROFILE_PATHS=>["/Users/Shared/Jenkins/Home/workspace/iOS Build - Complete Release/iOS/AppStore_com.************.************.mobileprovision"], :SIGH_UDID=>"3e62eddd-c680-456d-b78b-dc6ad726a652", :SIGH_UUID=>"3e62eddd-c680-456d-b78b-dc6ad726a652", :SIGH_PROFILE_TYPE=>"app-store"}
[10:30:36]: No value found for 'uuid'

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | team_id                                                       | 0           |
| 3    | increment_build_number                                        | 2           |
| 4    | produce                                                       | 120         |
| 5    | cert                                                          | 37          |
| 6    | pem --force                                                   | 9           |
| 7    | sigh                                                          | 27          |
| 💥    | update_project_code_signing                                   | 0           |
+------+---------------------------------------------------------------+-------------+

[10:30:36]: fastlane finished with errors
```

**Comment by hjanuschka** [comment]
can you please provide the `fastlane env` output.
what is the reason you require update_code_signing?

this one usually happens on corrupted projects where you have to toggle the versioning 
toggling it from current to none and back on.


<img width="1355" alt="bildschirmfoto 2016-11-23 um 13 51 35" src="https://cloud.githubusercontent.com/assets/2891702/20562455/fddcc434-b183-11e6-99e8-8d59a1b3b52a.png">


i am not sure if `update_project_code_signing`  corrupts the project, lets see if we find a way without the action, as i am not 100% sure who this works on xcode8

**Comment by igorstimoli** [comment]
Here is the fastlane env output

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.7.4 (Apple Git-66)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.37.0  | ✅ Up-To-Date        |
| deliver             | 1.15.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| produce             | 1.3.0   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.7.1   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| bundler                   | 1.13.5       |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.18       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.57.1       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2016-11-24**
</details>

Anyway it might sound strange, but I don't really know the reason of using update_project_code_signing
That line was there long before I started working on this project and who put it there is no more in the team.

This is how the lane looks like
```ruby
lane :deploy do |options|
  increment_build_number( build_number: "" )
  produce({
    	app_name: "",
    	language: "",
    	app_version: "",
    	sku: "",
	team_name: ""
  })
  cert
  sigh( force: true )
  ENV["SNAPSHOT_SKIP_OPEN_SUMMARY"] = "1"
  update_project_code_signing( path: "App.xcodeproj")
  ENV["FASTLANE_XCODE_LIST_TIMEOUT"]="120"
  gym(
    scheme: "App",
  )
  ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Aspera,Signiant,DAV -m diagnostic"
  deliver( 
	force: true,
	submit_for_review: options[:submit],
	automatic_release: options[:release],
	metadata_path: "./fastlane/metadata"
  )
end
```

**Comment by hjanuschka** [comment]
@igorstimoli  ok just for a quick test, can you remove the  `update_project_code_signing` and give it a try?

**Comment by igorstimoli** [comment]
@hjanuschka
Well... seems that just removing update_project_code_signing was enough to solve the issue

**Comment by hjanuschka** [comment]
🙏  nice to know - can you close the issue ?
