### ISSUE TITLE
[sigh] Generated `-p` option of resign is strange

### ISSUE THREAD

**Issue by yukiasai** [fastlane/fastlane#7155]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When Hash is given to provisioning_profile to resign, `-p` option is wrong

Hash

```
{
  "at.fastlane" => "/path/to/provision/at.fastlane.mobileprovision",
  "at.fastlane.today" => "/path/to/provision/at.fastlane.today.mobileprovision",
}
```

Generated `-p` option

```
-p /path/to/project/at.fastlane=/path/to/provision/at.fastlane.mobileprovision -p /path/to/project/at.fastlane.today=/path/to/provision/at.fastlane.today.mobileprovision
```

AppID (Key of Hash) is expanded to absolute path. This is not fulfilled the test case written in the comment.
https://github.com/fastlane/fastlane/blob/master/sigh/lib/sigh/resign.rb#L31

**Comment by hjanuschka** [comment]
@yukiasai seems to be introduced with #7004  - i did a pr with a fix: https://github.com/fastlane/fastlane/pull/7157

can you give the PR a try?

**Comment by hjanuschka** [comment]
@yukiasai  saw you did a PR too - closed mine, your's seems a bite nicer with the test case too! 🙌

**Comment by yukiasai** [comment]
@hjanuschka hi! sorry for confusing you. 🙇

**Comment by hjanuschka** [comment]
@yukiasai  no problem - thx for the quick 'n nice PR
