### ISSUE TITLE
Update metadata for current version of the app

### ISSUE THREAD

**Issue by bunuelcubosoto** [fastlane/fastlane#7156]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,

I would like to use deliver to update an existing version that is already Ready For Sale. Title, description, marketing URL, and other fields are editable although the app is "Ready For Sale". When I tried I got this error:

```
Could not find a version to edit for app 'TITLE', the app metadata is read-only currently
```

Here's my deliver configuration:

```
deliver(
skip_screenshots: true,
skip_binary_upload: true,
)
```

It seems deliver does not support updating current version.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.2.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2d 9 Jul 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby

# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.38.1"

default_platform :ios

ENV["SLACK_URL"] ||= ""

platform :ios do
	
  before_all do
   update_fastlane
   #ensure_git_status_clean
  end
  
  desc "Push release notes to iTunes Connect"
  lane :update_rn do
	  deliver(
	  	skip_screenshots: true,
		skip_binary_upload: true,
	  )
  end

end

error do |lane, exception|
    slack(
      message: exception.to_s,
      success: false
    )
end

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.37.0  | ✅ Up-To-Date  |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.1        |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.57.1       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.6        |
</details>

*generated on:* **2016-11-24**
</details>

**Comment by hjanuschka** [comment]
i don't think this is possible right now with deliver.

but you can do this with spaceship:


```ruby
require 'spaceship'
Spaceship::Tunes.login("helmut@januschka.com")

app = Spaceship::Tunes::Application.find("krone.at-fivexfive")
v = app.live_version
v.send("marketing_url")["de-DE"] = "http://www.yourhost.com"
v.send("release_notes")["de-DE"] = "Some New Release notes"
v.save!
```

for reference:

this are the localized keys (like above marketing_url):

```ruby
description, keywords, release_notes, support_url, marketing_url, name, privacy_url
```

this are the unlocalised:
```
copyright
```

let me know if this helps you

**Comment by bunuelcubosoto** [comment]
Hi,

Thanks. I just wrote a quick sample and that works.

**Comment by hjanuschka** [comment]
probably we can patch deliver to support live version editing with a custom flag ?

**Comment by bunuelcubosoto** [comment]
Definitely. I think that should be a feature to be implemented on deliver.

**Comment by hjanuschka** [comment]
@bunuelcubosoto PR done https://github.com/fastlane/fastlane/pull/7172
