### ISSUE TITLE
[Feature request] [produce] add support for Mac platform

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#7166]
Exactly whats in title. To do this we'd need to update **spaceship** as well by adding platform param to create_application(...) from tunes_client.rb

**Comment by hjanuschka** [comment]
thx for the feedback - i did 2 PR's as those need to be seperated.

#7180 (adding platform to spaceship)
#7181 (adding platform to produce)


if you wan't to test it out, i also pushed a branch to https://github.com/hjanuschka/fastlane/tree/produce_macapp_combined - having both PR's applied to current `master`

**Comment by masteranza** [comment]
It works great! Thank you @hjanuschka
