### ISSUE TITLE
Confusion between osx and mac platform name

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#7168]
When trying to run platform `mac` through fastfile deliver gives me a message:

`[!] The platform can only be ios, appletvos, or osx`

on the other hand when I switch the platform in fastfile to `osx` I cannot run the fastfile at all, because of:

`[!] §Platform 'osx' is not supported. Must be either [:ios, :mac, :android]`

Probably this kind of files https://github.com/fastlane/fastlane/blob/485199c8757113f2fdd1eee3448a0e0f3cd6d4e7/fastlane/lib/fastlane/supported_platforms.rb need editing

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
require 'dotenv'
Dotenv.load
import "../MasterFastfile"
```
</details>

<details><summary>`./Appfile`</summary>

```ruby

```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| produce             | 1.3.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| faraday_middleware        | 0.10.1  |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.2.0   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.11 |
| slack-notifier            | 1.5.1   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| activesupport             | 4.2.7.1 |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| colored                   | 1.2     |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| public_suffix             | 2.0.4   |
| addressable               | 2.5.0   |
| multipart-post            | 2.0.0   |
| xcode-install             | 2.0.9   |
| word_wrap                 | 1.0.0   |
| bundler                   | 1.13.6  |
| credentials_manager       | 0.16.2  |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.12.1  |
| logging                   | 2.1.0   |
| jwt                       | 1.5.6   |
| memoist                   | 0.15.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| httpclient                | 2.8.2.4 |
| google-api-client         | 0.9.20  |
| babosa                    | 1.0.2   |
| excon                     | 0.54.0  |
| gh_inspector              | 1.0.2   |
| fastlane_core             | 0.57.1  |
| io-console                | 0.4.5   |
| xcpretty-travis-formatter | 0.0.4   |
</details>

*generated on:* **2016-11-24**
</details>

**Comment by hjanuschka** [comment]
i think that in fastlane it is generally `mac` to use the mac platform.
in the above example - its actually inside deliver, which requires a "platform" parameter, but in this case it hase nothing todo with fastlane, its the "product" you create/manage on itunesconnect, and those strings are named, `ios,appletvos,osx`

i don't think that changing all `:mac`  to `:ios`  would be a good solution.
(as officially apple does not refere to osx anymore since sierra)

does that help?

**Comment by masteranza** [comment]
> (as officially apple does not refere to osx anymore since sierra)

That's true, but as I saw in spaceship source code most iTC links contain `osx` and not `mac`.

> edit: probably add a mapping inside the verify_block to also support :mac, as :osx ;)

Agreed, that would be a good-enough solution.

**Comment by hjanuschka** [comment]
deliver(platform: "ios")

**Comment by masteranza** [comment]
Both did't work, I'm still getting:
`[!] The platform can only be ios, appletvos, or osx`

**Comment by hjanuschka** [comment]
can you share your fastfile - or the file that gets loaded?

i tried it locally with

```ruby
platform :mac do
        lane :deliver_test do
                deliver(platform: "osx")
        end
end

```


and i could succesfully change platform to ios/osx/tvos - seeing the value used in the summary table.

**Comment by masteranza** [comment]
my exact code looks like this:

`platform :mac do
  lane :macupload do
    identifier = identifier + '.osx'
    puts identifier
    deliver(platform: "osx", username: apple_id, app_identifier: identifier, force: true, submit_for_review: true, pkg: pkg, automatic_release: true, app_review_information: app_review_information, metadata_path:("./" + game_name + "/metadata/"), screenshots_path:("./" + game_name + "/screenshots_mac/"))
    # deliver(pkg: pkg)
  end
end`

**Comment by hjanuschka** [comment]
@masteranza can you check the ENV['DELIVER_PLATFORM'] - i think if the env is set it may overrule the `platform` param.

you can force unset it with

```ruby
platform :mac do
  lane :macupload do
    identifier = identifier + '.osx'
    ENV["DELIVER_PLATFORM"]=nil
    deliver(platform: "osx", username: apple_id, app_identifier: identifier, force: true, submit_for_review: true, pkg: pkg, automatic_release: true, app_review_information: app_review_information, metadata_path:("./" + game_name + "/metadata/"), screenshots_path:("./" + game_name + "/screenshots_mac/"))
  end
end

```

**Comment by masteranza** [comment]
Still no success, are you sure this is the way to set it? Even though I set it to `nil` it's still showing `mac`
![screen shot 2016-11-25 at 09 23 25](https://cloud.githubusercontent.com/assets/911135/20618696/e3b63838-b2f0-11e6-8b91-5618518de518.png)

**Comment by hjanuschka** [comment]
@masteranza 
strange, can you run it with --verbose and post the output?

do you use a Deliverfile ? - probably the platform is set there ?

**Comment by hjanuschka** [comment]
ok sorry to say - the bug is in here: https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/detect_values.rb#L65

its forced to be "mac" once you use pkg - i am going to investigate what introduced this behaviour and why.

**Comment by hjanuschka** [comment]
@masteranza seems to be a bug, can you give this PR: https://github.com/fastlane/fastlane/pull/7174  a try? - i don't have a mac app / pkg project right now here.

**Comment by masteranza** [comment]
@hjanuschka sure, thanks for looking into this!

**Comment by masteranza** [comment]
It works now! Thank you so much!

**Comment by hjanuschka** [comment]
awesome! thx for your info. going to remove WIP now.

**Comment by masteranza** [comment]
@hjanuschka  Btw. how do I tell fastlane to ask me about platform when running an fastfile?

Currently for instance I'm either doing  `fastlane ios release` for a lane called `release` or setting manually `default_platform :ios` in the fastfile and then choosing the `release` lane. 
If I delete this `default_platform :ios` line it complains on having no lanes instead of asking which platform I'd like to run.

**Comment by hjanuschka** [comment]
@masteranza thats a brilliant question, i thought of adding a global lane, and then calling the platform lane, but after a bit of research i am not sure on how to call platform specific lanes.


@KrauseFx you have an idea about that?



anyway to fix your use case:
remove the `default_platform` from your Fastfile, and add this at the top :)

```ruby
if [:mac, :ios, :android].include?(ARGV[0].to_sym)
        default_platform ARGV[0].to_sym
else
        def_pl = false
        until def_pl == true
                userin = UI.input("Please select default platform (ios,mac,android)")
                if [:mac, :ios, :android].include?(userin.to_sym)
                        default_platform userin.to_sym
                        def_pl = true
                end
        end

end
```


this should ask for platform if not specified.
> keep in mind,, this is unofficial and unsupported use at your own risk 👍

**Comment by masteranza** [comment]
Thanks for the workaround @hjanuschka ! 
I hope we'll see an enumerated menu soon :)

**Comment by KrauseFx** [comment]
Hey everyone, what change would be necessary in the fastlane code base to make this easier?
