### ISSUE TITLE
[deliver] App_review_information not being sent with mac (pkg) upload

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#7175]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

So I tried passing app_review_information through deliver as I did in ios, but there are no changes on iTC, not sure exactly why.

`deliver(platform: "osx", price_tier: 1, username: apple_id, app_identifier: identifier, force: true, submit_for_review: true, pkg: pkg, automatic_release: true, app_review_information: app_review_information)`

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
require 'dotenv'
Dotenv.load
import "../MasterFastfile"
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date  |
| spaceship           | 0.38.0  | ✅ Up-To-Date  |
| deliver             | 1.15.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.11.2  | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| supply              | 0.7.1   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version      |
| ------------------- | ------------ |
| did_you_mean        | 1.0.0        |
| highline            | 1.7.8        |
| commander           | 4.4.0        |
| terminal-table      | 1.4.5        |
| json                | 1.8.3        |
| faraday_middleware  | 0.10.1       |
| dotenv              | 2.1.1        |
| net-ssh             | 3.2.0        |
| net-sftp            | 2.1.2        |
| plist               | 3.2.0        |
| rubyzip             | 1.1.7        |
| security            | 0.1.3        |
| krausefx-shenzhen   | 0.14.11      |
| slack-notifier      | 1.5.1        |
| i18n                | 0.7.0        |
| thread_safe         | 0.3.5        |
| tzinfo              | 1.2.2        |
| activesupport       | 4.2.7.1      |
| CFPropertyList      | 2.3.3        |
| claide              | 1.0.1        |
| colored             | 1.2          |
| nanaimo             | 0.2.2        |
| xcodeproj           | 1.4.1        |
| rouge               | 1.11.1       |
| xcpretty            | 0.2.4        |
| terminal-notifier   | 1.7.1        |
| public_suffix       | 2.0.4        |
| addressable         | 2.5.0        |
| multipart-post      | 2.0.0        |
| xcode-install       | 2.0.9        |
| word_wrap           | 1.0.0        |
| bundler             | 1.13.6       |
| credentials_manager | 0.16.2       |
| multi_json          | 1.12.1       |
| babosa              | 1.0.2        |
| excon               | 0.54.0       |
| gh_inspector        | 1.0.2        |
| fastlane_core       | 0.57.1       |
| multi_xml           | 0.5.5        |
| unf_ext             | 0.0.7.2      |
| unf                 | 0.1.4        |
| domain_name         | 0.5.20161021 |
| http-cookie         | 1.0.3        |
| faraday-cookie_jar  | 0.0.6        |
| fastimage           | 1.6.8        |
| mini_magick         | 4.5.1        |
| uber                | 0.0.15       |
| representable       | 2.3.0        |
| retriable           | 2.1.0        |
| hurley              | 0.2          |
| little-plugger      | 1.1.4        |
| logging             | 2.1.0        |
| jwt                 | 1.5.6        |
| memoist             | 0.15.0       |
| os                  | 0.9.6        |
| signet              | 0.7.3        |
| googleauth          | 0.5.1        |
| httpclient          | 2.8.2.4      |
| google-api-client   | 0.9.20       |
| io-console          | 0.4.5        |
</details>

*generated on:* **2016-11-25**
</details>

**Comment by hjanuschka** [comment]
can you share your `app_review_information` hash?  - a quick test worked for me.

**Comment by masteranza** [comment]
I'm loading this json file:
`{
"first_name": "xx,
"last_name": "yy",
"phone_number": "+48 111222333",
"email_address": "xxx@gmail.com",
"demo_user": "",
"demo_password": "",
"notes": ""
}`

**Comment by hjanuschka** [comment]
can you run deliver with VERBOSE=1 (as a ENV) ? 
and have a look at the payloads that get sent?

BEWARE before copy n pasting it , it may include private data. (double check it)

**Comment by masteranza** [comment]
http://pastebin.com/n2gWZE6A I hope that helps, please ignore ios-indicating debugs, this is 100% mac os build. It looks like app_review_information doesn't get sent even though I pass it and it shows up in fastlane information printouts.

**Comment by hjanuschka** [comment]
seems the request fails but fastlane says metadata completet

thx for the debug - i ll dig into it and try finding the problem

**Comment by hjanuschka** [comment]
@masteranza 

i tried it now with a newly created macapp and the following fastfile:


```
$tester_info = {
  first_name: 'Helmut',
  last_name: 'Januschka',
  phone_number: '+43 XXXX',
  email_address: 'helmut@januschka.com',
  demo_user: 'trottendes.lama',
  demo_password: 'XXXX',
  notes: 'app should be usable even with no user'
}



lane :deliver_mac do
	deliver(platform: "osx", skip_binary_upload: true, skip_screenshots: true, app_review_information: $tester_info)
end
```

it successfully set the values on iTC. have you tried setting the exact same values you'd set in the `app_review_information` by hand in iTC? maybe there is a character/format problem?

**Comment by masteranza** [comment]
Ahhh, found the problem. I was parsing a .json file that looked like this:

```
{
"first_name": "Name",
"last_name": "Surname",
"phone_number": "+48 11111111",
"email_address": "xxx@gmail.com"
}

```

using the command
`JSON.parse(File.read("review_information.json"))`

and it didn't work, but when I added the `symbolize_names: true` it started working.
The funny thing is that when I copied the file contents with names as string it still worked.
Thanks!
