### ISSUE TITLE
Running PEM from python

### ISSUE THREAD

**Issue by IrSent** [fastlane/fastlane#7176]
### New Issue Checklist

- [yes] Updated fastlane to the latest version
- [yes] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`pem` runs correctly via command line.
But when I try to run `pem` through `sh` library which is just a wrapper around the original Python `subproccess` library. I add all needed environment variables and then run prepared command. And the process hangs.

Do you have any advice on how can I solve this problem?

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                          |
| ------------------- | ---------------------------------------------- |
| OS                  | 10.12.1                                        |
| Ruby                | 2.2.4                                          |
| Bundler?            | false                                          |
| Git                 | git version 2.9.3 (Apple Git-75)               |
| Installation Source | /Users/*****/.fastlane/bin/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2657)                     |
| Ruby Lib Dir        | /Users/*****/.fastlane/bin/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                     |
| Is contained        | true                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version       | 8.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| deliver             | 1.15.1  | ✅ Up-To-Date        |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| produce             | 1.3.1   | ✅ Up-To-Date     |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| spaceship           | 0.38.0  | ✅ Up-To-Date |
| supply              | 0.7.1   | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.3        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.0        |
| credentials_manager       | 0.16.2       |
| domain_name               | 0.5.20161021 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 0.57.1       |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.2        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.1        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2016-11-25**
</details>

**Comment by PetrosIchor** [comment]
Not the exact solution you are looking for, but might help troubleshoot while moving closer to your goal:  Have you tried making a simple 1 line bash script file and using python to run that file instead? 

Create a file pem.sh with your pem commands inside.  Then:
```
import os
os.system('./pem.sh')
```
You can also use  `os.system`  for driving commands: 
`os.system('fastlane ios beta --env myApp')`

If those don't work for you, you'll need to provide a lot more information about your environment and the commands you are trying to run.

**Comment by IrSent** [comment]
Actually it works just fine. Thanks.
