### ISSUE TITLE
[gym] Only one(/wrong) .app artefact is copied over

### ISSUE THREAD

**Issue by notjosh** [fastlane/fastlane#7190]
Hi!

I have a Mac app which contains another .app as a dependency & build artefact (it's a helper app to allow the app to boot on startup, [documented here](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLoginItems.html).

The `BuildProductsPath/Release` directory listing looks like:

```
Foo.app
Foo.app.dSYM
Foo.swiftmodule
FooHelper.app
FooHelper.app.dSYM
FooHelper.swiftmodule
... // other frameworks
```

So far, so good...

### What happens

Currently, `copy_mac_app()` only [copies the last found .app in the folder](https://github.com/fastlane/fastlane/blob/7a83e79d56deed259dfc68af446b5984d4c9c3d3/gym/lib/gym/runner.rb#L160) (in this case it's `FooHelper.app`) during a build.

My CLI output is:

```
[12:29:02]: Successfully exported and compressed dSYM file
[12:29:02]: Successfully exported the .app file:
[12:29:02]: ./FooHelper.app
```

### What should happen

I'd expect `Foo.app` to be available at the end of the build. It's `.dSYM` is, so that's a start :)

### Solutions/discussion

There are a couple of solutions I can think of to this:

 - Copy all `.app`s. This is probably not good (since you probably never need only the `*Helper.app` on its own), but it's easiest to implement
 - Specify an env var to state which `.app` to copy
 - Look into the chosen scheme's `Info.plist` to find the `CFBundleExecutable`, and copy only that (defaulting to the last .app if not found?)

I'd say the last one is the best way to do this. I'll take a look at how easy that is, but would appreciate input!

**Comment by notjosh** [comment]
`fastlane env` output: https://gist.github.com/notjosh/e68a1afff659e798e1d79d078faf81f0

**Comment by hjanuschka** [comment]
@notjosh i did a few PR's to improve gym
  *  https://github.com/fastlane/fastlane/pull/7090
  *  https://github.com/fastlane/fastlane/pull/7091

this include a fix for this issue, using the last option you described (fetching `EXECUTABLE_NAME`)

**Comment by notjosh** [comment]
Whoa nice! Any idea when that'll make it to a release?

**Comment by hjanuschka** [comment]
@notjosh hopefully soon - you may +1 the PR's - and probably you can try it out?
