### ISSUE TITLE
Fastlane Action reset_simulators doesn't support ios parameter

### ISSUE THREAD

**Issue by fawkeswei** [fastlane/fastlane#7192]
Running `snapshot reset_simulators --ios 8.1,10.0` resets and creates simulators with iOS 8.1 & iOS 10.0, but the fastlane action used in fastfile `reset_simulators` doesn't respect the `--ios` parameter given.

Fastfile is like this
```
platform :ios do
  lane :test do
    reset_simulators(
        ios: ["8.1", "10.0"]
    )
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[13:48:38]: -------------------------------------------------
[13:48:38]: --- Step: Verifying required fastlane version ---
[13:48:38]: -------------------------------------------------
[13:48:38]: Your fastlane version 1.106.2 matches the minimum requirement of 1.25.0  ✅
[13:48:38]: ------------------------------
[13:48:38]: --- Step: default_platform ---
[13:48:38]: ------------------------------
[13:48:39]: Driving the lane 'ios test' 🚀
[13:48:39]: ------------------------------
[13:48:39]: --- Step: reset_simulators ---
[13:48:39]: ------------------------------
[13:48:39]: Resetting iPhone 5
[13:48:39]: Resetting iPhone 7
[13:48:40]: Resetting iPhone 7 Plus
[13:48:40]: Simulators reset

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | reset_simulators                    | 1           |
+------+-------------------------------------+-------------+

[13:48:40]: fastlane.tools finished successfully 🎉
```

**Comment by hjanuschka** [comment]
see PR: https://github.com/fastlane/fastlane/pull/7194

**Comment by milch** [comment]
@fawkeswei Hey, thanks for submitting your issue! Could you go into a bit more detail of why this would be useful, or how this would benefit your workflow?

Also, adding an `ios` parameter to the `reset_simulators` action might give users the wrong idea of what exactly that action does: while the `snapshot reset_simulators` command completely deletes and recreates either a set of default or user-supplied simulators, the action you run in the Fastfile only shuts them down and deletes installed apps/settings. I realize they are named rather confusingly, sorry about that.

**Comment by hjanuschka** [comment]
@milch true! so i am still sold on the idea to reset contents only on specific ios version.
could we just rename the action to `reset_simulator_contents` - keeping the older one as an alias - to not break existing uses?

**Comment by milch** [comment]
@hjanuschka I'm not exactly sure how that is useful, though. I'll wait for comment from @fawkeswei before I proceed.

**Comment by fawkeswei** [comment]
@milch The work flow I'm try to achieve is reset all simulators before testing on iOS 8 & iOS 10 simulators. Actually it was the naming of `reset_simulator_contents` in Fastfile action that got me thinking that it will delete and recreate all simulators for the latest version SDK only (like `snapshot reset_simulators`). That's why I was requesting to add `--ios` parameter.

I think @hjanuschka's proposal of renaming the action in Fastfile to `reset_simulator_contents` is great, to clarify what the action actually does.

**Comment by milch** [comment]
@hjanuschka @fawkeswei 

Alright, thanks for your explanation, sounds good to me. I just reviewed the alias PR, let's rename the action to `reset_simulator_contents` and create a `reset_simulators` alias for it that points users to the new name 👍
