### ISSUE TITLE
New build for #6501 ?

### ISSUE THREAD

**Issue by albgz** [fastlane/fastlane#7201]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to use changeTrack to move an APK from beta the staged rollout track. I found about issue [#6501](https://github.com/fastlane/fastlane/issues/6501) which was merged in [PR6502](https://github.com/fastlane/fastlane/pull/6502) but there is no build. Can we get a new build?

**Comment by hjanuschka** [comment]
this will hopefully be released soon.

**Comment by mfurtak** [comment]
[_supply_ 0.8.0](https://github.com/fastlane/fastlane/releases/tag/supply/0.8.0) has been released! 🚀
