### ISSUE TITLE
How does fastlane pick up my ruby version?

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#7215]
I'm getting the error below which is complaining about my ruby version.  However, if I run `ruby --version` it says `ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin15]`.  Any idea why its picking up this older version (2.0.0) of ruby?

> SSL errors can be caused by various components on your local machine.
> Apple has recently changed their servers to require TLS 1.2, which may
> not be available to your system installed Ruby (2.0.0)

**Comment by npomfret** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1108)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.38.1  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date        |
| deliver             | 1.16.0  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.12.0  | ✅ Up-To-Date        |
| produce             | 1.3.1   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.3   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.0        |
| net-ssh                   | 3.0.2        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.5        |
| colored                   | 1.2          |
| claide                    | 0.9.1        |
| xcodeproj                 | 0.28.2       |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160309 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.2        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.11.2       |
| babosa                    | 1.0.2        |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.57.1       |
| bundler                   | 1.12.5       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.3        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.7.1        |
| google-api-client         | 0.9.4        |
</details>


*generated on:* **2016-11-29**
</details>

**Comment by npomfret** [comment]
Looks like its picking up the _system_ ruby from `/usr/bin/ruby` .  Any idea how I get around this?

```
$ which ruby
/Users/nickpomfret/.rbenv/shims/ruby
$ whereis ruby
/usr/bin/ruby
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
$ /usr/bin/ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
```

**Comment by hjanuschka** [comment]
check you $PATH env. variable.
maybe check you `.profile`, `.bash_profile` - for this.
look at this: https://github.com/rbenv/rbenv#understanding-shims

**Comment by npomfret** [comment]
That's the weird thing, my path starts with `/Users/username/.rbenv/shims:` as expected.  And my command line picks up the right version:

```
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

```

But for some reason fastlane appears to pick up: `/usr/bin/ruby`

**Comment by hjanuschka** [comment]
whats the output of: `/usr/bin/env ruby`

there is a new thing in the air: http://download.fastlane.tools/ 
which provides as a contained version (shipping its own ruby, ssl and all the things) maybe you can try this.

**Comment by npomfret** [comment]
Thanks for the reply. `/usr/bin/env ruby` just hangs - there's no output at all.

**Comment by hjanuschka** [comment]
my fault env does not output anything :(

can you try this answer here: http://stackoverflow.com/a/12150580/1945875

**Comment by npomfret** [comment]
That's the weird thing, my path looks fine, my bash_profile looks fine.  When I run ruby from the command line I get the correct version.  But for some reason fastlane is picking up the wrong one.

**Comment by hjanuschka** [comment]
@npomfret you can install fastlane now via brew - which ships a built in ssl,ruby and all the other dependencies

see here: https://github.com/fastlane/fastlane#choose-your-installation-method

or you just download it https://download.fastlane.tools - and double click the "install"

**Comment by npomfret** [comment]
Yep, tried that.  Doesn't work for me. Installed using `brew cask install fastlane` but get same error message.  It always picks up the wrong version.

**Comment by npomfret** [comment]
The installer seems to have worked around the problem.  Thanks for the tip.  Got another issue now though but I'll open a separate ticket if needed.

**Comment by Tapestes** [comment]
Having a very similar issue.  ruby -v gives me ruby 2.4.0p0.  When I run pilot list I get
`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (< 3.0.0, >= 2.0.0) among 226 total gem(s) (Gem::LoadError)`

Running a lane (e.g., fastlane alpha) seems to get it to run off 2.4 rather than 2.0 system Ruby.  I've tried installing fastlane via brew, ruby gem, and the install package.  No luck.
