### ISSUE TITLE
After using match I get xCode error: A valid provisioning profile for this executable was not found.

### ISSUE THREAD

**Issue by samphilipd** [fastlane/fastlane#7218]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've set up my provisioning using match, now I see this error when trying to build one of my targets for a local device (strangely, the other target works fine).

"A valid provisioning profile for this executable was not found."

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

A valid provisioning profile for this executable was not found.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                         |
| ------------------- | --------------------------------------------- |
| OS                  | 10.12.1                                       |
| Ruby                | 2.3.1                                         |
| Bundler?            | true                                          |
| Git                 | git version 2.9.3 (Apple Git-75)              |
| Installation Source | /Users/sam/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                    |
| Ruby Lib Dir        | /Users/sam/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                    |
| Is contained        | false                                         |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/   |
| Xcode Version       | 8.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "ca14a13e-c7da-4b5a-8941-95ba1f3da241"

default_platform :ios

desc "Submits a new Beta Build to Apple TestFlight"
lane :beta do
  # cocoapods

  # increment_build_number


  # build your iOS app
  gym(
    scheme: ENV['SCHEME'],
    use_legacy_build_api: false
  )

  # upload to Testflight
  pilot(
    skip_waiting_for_build_processing: true,
    app_identifier: ENV['APP_IDENTIFIER'],
    ipa: "#{ENV['SCHEME']}.ipa"
  )
end

desc "Deploys a new version to the App Store"
lane :deploy do
  cocoapods
  gym(configuration: "Release")
  deliver(force: true)
end

lane :refresh_dsyms do
  download_dsyms                  # Download dSYM files from iTC
  upload_symbols_to_crashlytics   # Upload them to Crashlytics
  clean_build_artifacts           # Delete the local dSYM files
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["BUNDLE_ID"]
apple_id ENV["APPLE_ID"]
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date        |
| spaceship           | 0.38.1  | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| deliver             | 1.15.1  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| sigh                | 1.11.2  | 🚫 Update availaible |
| match               | 0.11.0  | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| produce             | 1.3.1   | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| supply              | 0.7.1   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.12.5       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.57.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.4        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.1.1        |
| coderay                   | 1.1.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| method_source             | 0.8.2        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slop                      | 3.6.0        |
| pry                       | 0.10.4       |
| slather                   | 2.3.0        |
</details>

*generated on:* **2016-11-29**
</details>

**Comment by hjanuschka** [comment]
have you checked the signing settings of the target? maybe a typo in the `$(sigh....`  variable.
compare it with the one from the target that works.

also can you share gym output?

**Comment by samphilipd** [comment]
I've been through that guide several times already :(

**Comment by samphilipd** [comment]
@hjanuschka I'm building using xcode, not gym. Where can I find the signing settings of the target?

Building using gym for distribution works fine, not sure how to build for development.

**Comment by samphilipd** [comment]
Nailed it! I was using an old, previously removed build configuration... doh! Thanks for the helpful error message, xcode...
