### ISSUE TITLE
Produce (by default) enables push-notification service and it leads to export problems with deliver

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#7219]
Is there any need for enabling push-notification service on a brand new app by default?
Currently it leads to an obscure problem which doesn't prevent building and signing, but prevents exporting the app for iTC submission.

**Comment by hjanuschka** [comment]
it seems to be fixed inside produce, @masteranza what is the error you get on submission?

**Comment by hjanuschka** [comment]
see PRS 

  * 1/2  https://github.com/fastlane/fastlane/pull/7222 -> spaceship
  * 2/2 https://github.com/fastlane/fastlane/pull/7223 -> produce

**Comment by masteranza** [comment]
@hjanuschka you're amazing. This was really fast and solves the problem, although this is similar to running `produce disable_services --push-notification` post creation.

My original question was: 
What's the point of turning on push-notification **on default** in the first place?
It doesn't seem to me that everyone will want push-notifications in their apps, but perhaps there's another reason?

**Comment by hjanuschka** [comment]
@masteranza updated the pr to support more flags 👍  and taken the logic from `disable_service` maybe you can try again? (call is  a bit different)

**Comment by masteranza** [comment]
@hjanuschka great modification! I'll test it asap.
Still I'm voting for changing the default produce behaviour, so it does not turn on push-notifications. What does the fastlane team think about that?

**Comment by masteranza** [comment]
@hjanuschka I forgot to say it works!
