### ISSUE TITLE
can't produce with 'Simplified Chines'

### ISSUE THREAD

**Issue by nAviram** [fastlane/fastlane#7221]
### New Issue Checklist

- [v] Updated fastlane to the latest version
- [v] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to produce with parameter
--language 'Simplified Chines'

and it fails:
[!] The request could not be completed because:
                You must provide a valid default language. You must provide a valid default language. You must provide a valid default language.
 
what's the correct value I should put for Chinese ? 
Thanks!

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[I[!] The request could not be completed because:
                You must provide a valid default language. You must provide a valid default language. You must provide a valid default language.]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by hjanuschka** [comment]
can you provide `fastlane env`

also `--language 'Simplified Chines'`  is missing an `e` at the end, maybe thats the problem?

**Comment by nAviram** [comment]
sorry I didn't copy it right... in the command it's 'Simplified Chinese'
I'm on fastlane version 1.100.0.

**Comment by hjanuschka** [comment]
sorry i see - the PR that fixes this https://github.com/fastlane/fastlane/pull/7193 has been merged, but the spaceship update has not yet been released, i think this will be released soon.

**Comment by nAviram** [comment]
I also noticed produce update:
1.3.1 Bugfix for primary_language selection
* Update internal dependencies 
* Bugfix for primary_language selection

and I'm currently on version 1.2.0 so I'll also try to update.
Thanks!

**Comment by hjanuschka** [comment]
@nAviram spaceship has been released a few minutes ago: https://github.com/fastlane/fastlane/releases/tag/spaceship/0.38.2

which includes the fix.
can you confirm and close issue?

**Comment by nAviram** [comment]
It Works!
I updated produce - and problem solved.
Thanks a lot!
