### ISSUE TITLE
[match] How to use match as a 'member' (not admin) of developer portal?

### ISSUE THREAD

**Issue by pj4533** [fastlane/fastlane#7226]
As a user of Match, I want to be able to create developer certificates & download developer provisioning profiles after my admin creates them for me.

Currently, if I run `match developer` (or match with type `development` in my Fastfile), match correctly creates my developer certificate. Then it attempts to create a new provisioning profile, but fails due to my member-level status.  However, the certificate created is never committed to the repo.  

Then, my admin goes and creates a provisioning profile for me, using the above (non-committed) certificate.

I attempt to run `match developer` again, and it doesn't find a certificate in the repo, so it creates a new one.  It finds a provisioning profile, but now this profile doesn't match the (new) certificate, so it skips it, and attempts to create a new provisioning profile (which fails due to member-level access).

Is this supported?  Can I split apart the cert creation from the provisioning profile creation using match?

**Comment by pj4533** [comment]
env output:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.3.0                                           |
| Bundler?            | true                                            |
| Git                 | git version 2.9.3 (Apple Git-75)                |
| Installation Source | /Users/pgray/.rbenv/versions/2.3.0/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2555)                      |
| Ruby Lib Dir        | /Users/pgray/.rbenv/versions/2.3.0/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'open-uri'

fastlane_version "1.42.0"

############### Private Lanes ##########################

private_lane :setup_and_build do |options|

  manualship = options[:manualship].nil? ? false : options[:manualship]
  
  setup_project_from_template(
    manualship: manualship,
    oid: options[:oid],
    slug: options[:slug],
    bundle_id: options[:bundle_id],
    org_name_short: options[:org_name_short],
    facebook_app_id: options[:facebook_app_id],
    team_id: options[:team_id]
  )

  match(
    git_branch: options[:slug],
    type: "development",
    app_identifier: options[:bundle_id],
    team_id: options[:team_id]
  )

  if !manualship
    match(
      git_branch: options[:slug],
      type: "appstore",
      app_identifier: options[:bundle_id],
      team_id: options[:team_id]
    )    
  end

  gym(
    scheme: "EverTrue",
    configuration: "Release",
    output_directory: "gym"      
  )

end

private_lane :git_submodule_update do |options|
  Actions.sh("git submodule update --init")
end

private_lane :bump_version do |options|
  increment_build_number(
    xcodeproj: "evertrue.xcodeproj"
  )
  
  commit_version_bump(
    xcodeproj: "evertrue.xcodeproj"
  )
end

############### Public Lanes ##########################

desc "Checkup"
lane :doctor do |options|
  require 'terminal-table'

  rows = []

  # check if repo is clean
  if `git status --porcelain`.empty?
    rows << ["✅", "Repo is clean"]
  else
    rows << ["🚫", "Local changes in repo - see 'git status' for details"]
  end

  # check if team is set
  team_is_set = false
  org_values = get_org_values_from_oid(oid: options[:oid])

  if !org_values[:teamname].nil?
    team_is_set = true
    rows << ["✅", "Developer Team correctly set in console"]
  else
    rows << ["🚫", "Developer Team not set in console"]
  end

  if !org_values[:app_keywords]["en-US"].nil?
    rows << ["✅", "App keywords correctly set in console"]
  else
    rows << ["🚫", "App keywords not set in console"]
  end

  if !org_values[:bundle_id].nil?
    rows << ["✅", "Bundle ID: #{org_values[:bundle_id]}"]
  else
    rows << ["🚫", "Bundle ID not set"]
  end

  if !org_values[:app_description]["en-US"].nil?
    rows << ["✅", "App description correctly set in console"]
  else
    rows << ["🚫", "App description not set in console"]
  end

  if options[:manualship]
    client = Spaceship::PortalClient.new
    client.login
    client.team_id = org_values[:team_id]
    found = false
    client.apps.each do |app|
      if app["identifier"] == org_values[:bundle_id]
        found = true
      end
    end
    if found
      rows << ["✅", "App identifier created on developer portal"]
    else
      rows << ["🚫", "App identifier (#{org_values[:bundle_id]}) not found on developer portal"]
    end
  end

  # check if invitations accepted
  if team_is_set
    if org_values[:team_id] == ""
      rows << ["🚫", "Developer Portal invitation not accepted"]
    else
      rows << ["✅", "Developer Portal invitation accepted"]
    end
    if !options[:manualship]
      if org_values[:itc_provider] == ""
        rows << ["🚫", "iTunes Connect invitation not accepted"]
      else
        rows << ["✅", "iTunes Connect invitation accepted"]
      end
    end
  else
    rows << ["❓", "Developer Portal invitation status unknown until teamname set in console"]
    if !options[:manualship]
      rows << ["❓", "iTunes Connect invitation status unknown until teamname set in console"]
    end
  end

  # check if affiliation set
  require "net/https"
  require "uri"
  require "json"

  affiliation_set = false
  password = CredentialsManager::AccountManager.new(user: "ios@evertrue.com", password: nil).password
  # this works but i am surprised i don't have to do a dry run on affiliation_request, but
  # maybe they are actually MATCHING the record in console?
  uri = URI.parse("https://api.evertrue.com/auth/session")
  http = Net::HTTP.new(uri.host, uri.port)
  request = Net::HTTP::Post.new(uri.request_uri)
  request.basic_auth 'ios@evertrue.com', password
  request.add_field 'Application-Key', '590b6855ec417400015682e454c6acec8f371adf861b830b031fa9ad3ac84c90'
  request.add_field 'Authorization-Provider','EvertrueBasicAuth'
  http.use_ssl = true
  response = http.request(request)
  json = JSON.parse(response.body)
  json["user"]["affiliations"].each do |affiliation|
    if org_values[:oid] == "#{affiliation["organization"]["id"]}"
      affiliation_set = true
    end
  end
  if affiliation_set
    rows << ["✅", "Test user record added & matched in console"]
  else
    rows << ["🚫", "Test user record not added and/or matched in console (no affiliation)"]
  end


  ENV['FASTLANE_HIDE_TIMESTAMP']="1"

  puts ""
  puts ""
  puts Terminal::Table.new(
    title: "alumni directory build doctor".green,
    headings: ["Status", "Description"],
    rows: rows
  )
  puts ""

end

desc "Clean up after a build"
lane :clean do |options|
    # finished build so reset back to templated project file
  `git checkout ../evertrue.xcodeproj/project.pbxproj`
  `git checkout ../EverTrueUITests/EverTrueUITests.swift`
  `git checkout ../evertrue.xcodeproj/xcshareddata/xcschemes/EverTrue.xcscheme`
  `git checkout ../EverTrue/evertrue.entitlements`
  `rm -rf ../fastlane/screenshots`

  Dir.glob('../EverTrue/Images.xcassets/AppIcon.appiconset/ET.Assets.*.png').each { |f| File.delete(f) }
  Dir.glob('../EverTrue/Images.xcassets/LaunchImage.launchimage/ET.Assets.*.png').each { |f| File.delete(f) }    
end

desc "Just Setup The Project"
lane :setup_project do |options|
  org_values = get_org_values_from_oid(oid: options[:oid])

  setup_project_from_template(
    manualship: false,
    oid: org_values[:oid],
    slug: org_values[:slug],
    bundle_id: org_values[:bundle_id],
    org_name_short: org_values[:org_name_short],
    facebook_app_id: org_values[:facebook_app_id],
    team_id: org_values[:team_id]
  )

end

desc "Setup and do the build"
lane :build do |options|
  org_values = get_org_values_from_oid(oid: options[:oid])
  org_values[:manualship] = false
  setup_and_build(org_values)
end

desc "Create a new app on iTunes Connect"
lane :createapp do |options|
  ensure_git_status_clean

  git_pull
  git_submodule_update

  ensure_git_status_clean

  org_values = get_org_values_from_oid(oid: options[:oid])
  
  raise "***** Developer team not set in console -- BE SURE TO RUN DOCTOR FIRST ******" if org_values[:teamname].nil?

  buildnumber = `cd ..;agvtool vers -terse`.strip
  versionnumber = `cd ..;agvtool mvers -terse1`.strip

  register_devices(
    username: 'ios@evertrue.com',
    team_name: org_values[:teamname],
    devices: { "evertrue test device" => "8d624f0a33dec2aacd9e0b014ce750fd0528311a"}
  )

  produce(
    username: 'ios@evertrue.com',
    app_identifier: org_values[:bundle_id],
    app_name: org_values[:app_name_full]["en-US"],
    language: 'English',
    app_version: versionnumber,
    sku: "et-#{org_values[:slug]}-001".upcase,
    team_name: org_values[:teamname],
    company_name: org_values[:teamname],
    itc_team_id: org_values[:itc_provider] 
  )
end

# this process isn't finished yet -- BU originally would only give us member status
# so we needed to do this process in order to create an xcarchive to send them
# but then BU changed their minds.  We might eventually get another client
# that needs this tho, so I am leaving it here to build on
#
# The process is weird tho it would be something like:
# 1) client adds ios@evertrue.com as member
# 2) we create developer certificate using a lane with a match command (but it doesn't do the profile yet?)
# 3) we request them to make an app id & provisioning profile
# 4) run manualship command to build and output an xcarchive
# 5) have the command also output all the metadata they would need to create the itunes app
# 6) send via email the xcarchive & associated metadata
# 
#  (steps 2 & 3 might be swapped or broken out, that is where i was in the BU process)
#  
desc "Build an xcarchive and associated data for shipping to a non-admin customer"
lane :manualship do |options|
  # ensure_git_status_clean

  # git_pull
  # git_submodule_update

  # ensure_git_status_clean

  skip_screenshots = options[:skip_screenshots].nil? ? false : options[:skip_screenshots]

  org_values = get_org_values_from_oid(oid: options[:oid])
  
  raise "***** Developer team not set in console -- BE SURE TO RUN DOCTOR FIRST ******" if org_values[:teamname].nil?

  buildnumber = `cd ..;agvtool vers -terse`.strip
  versionnumber = `cd ..;agvtool mvers -terse1`.strip
  
  org_values[:manualship] = true
  
  setup_and_build(org_values)

  # figure out screenshots
  # figure out necessary metadata for app
  # figure out testing


end

desc "Submit a new Release Candidate Build to Apple TestFlight"
lane :verify do |options|
  ensure_git_status_clean

  git_pull
  git_submodule_update

  ensure_git_status_clean

  skip_screenshots = options[:skip_screenshots].nil? ? false : options[:skip_screenshots]

  org_values = get_org_values_from_oid(oid: options[:oid])
  
  raise "***** Developer team not set in console -- BE SURE TO RUN DOCTOR FIRST ******" if org_values[:teamname].nil?

  buildnumber = `cd ..;agvtool vers -terse`.strip
  versionnumber = `cd ..;agvtool mvers -terse1`.strip

  # this checks is the build already exists, if it does, we still do the setup/build and take screenshots
  # but we don't tag and we don't sent to itunes connect for testflight
  build_exists = check_build_exists(
    build_number: "#{buildnumber}",
    version_number: "#{versionnumber}",
    app_identifier: org_values[:bundle_id],
    dev_portal_team_id: org_values[:team_id],
    team_id: org_values[:itc_provider]
  )

  org_values[:manualship] = false

  setup_and_build(org_values)

  if !skip_screenshots
    snapshot

    # This deliver step is specifically for the screenshots, if they aren't skipped, otherwise,
    # the metadata can be updated during the submit step
    deliver(
      app_version: "#{versionnumber}",
      app_identifier: org_values[:bundle_id],
      metadata_path: "fastlane/metadata",
      screenshots_path: "fastlane/screenshots",
      force: true,
      skip_screenshots: false,
      skip_binary_upload: true,
      submit_for_review: false,
      automatic_release: false,
      app_icon: './EverTrue/Images.xcassets/AppIcon.appiconset/ET.Assets.AppStoreArtwork.png',
      description: org_values[:app_description],
      name: org_values[:app_name_full],
      keywords: org_values[:app_keywords],
      marketing_url: org_values[:org_url]["en-US"],
      copyright: "2013 #{org_values[:org_name_short]}",
      dev_portal_team_id: org_values[:team_id],
      team_id: "#{org_values[:itc_provider]}"  
    )
  end

  clean 

  # doesn't work yet  -- have to manually add internal tester for now?
  # `pilot add ios@evertrue.com`

  ENV["PILOT_WAIT_FOR_NEW_BUILD_TRAINS_ON_ITUNES_CONNECT"]="1"

  ## only upload if build doesn't exist  
  if build_exists
    UI.success "*** BUILD: #{versionnumber} (#{buildnumber}) already exists on iTunes Connect ***"
  else

    add_git_tag(
      grouping: "#{versionnumber}/#{org_values[:slug]}",
      build_number: buildnumber
    )

    # don't bump version every build in the directory app -- cause we will be shipping a bunch off the same tag
    # bump_version

    push_git_tags

    pilot(
      changelog: "TESTING",
      app_identifier: org_values[:bundle_id],
      dev_portal_team_id: org_values[:team_id],
      team_id: "#{org_values[:itc_provider]}",
      email: "ios@evertrue.com"
    )
  end

end

desc "Update Fastlane"
lane :update do |options|
  update_fastlane
end

desc "Submit a previously uploaded build for review on appstore"
lane :submit do |options|
  # tag = options[:tag].nil? ? "misc" : options[:tag]   ## used for dockhand

  ensure_git_status_clean

  org_values = get_org_values_from_oid(oid: options[:oid])

  raise "***** Developer team not set in console -- BE SURE TO RUN DOCTOR FIRST ******" if org_values[:teamname].nil?

  buildnumber = `cd ..;agvtool vers -terse`.strip
  versionnumber = `cd ..;agvtool mvers -terse1`.strip

  password = CredentialsManager::AccountManager.new(user: "ios@evertrue.com", password: nil).password
  premium_notes = "#1 - When presented with 'Enter Now with LinkedIn' or 'Use Email': select 'Use Email'\n#2 - Select 'Login' instead of 'Sign Up'\n#3 - When prompted to enter Email and Password, please use the demo account."
  standard_notes = "#1 - From the 'Select a Community' screen, enter 'evertruedemo' (all lowercase) and choose 'EverTrue Demo'\n#2 - When presented with 'Enter Now with LinkedIn' or 'Use Email': select 'Use Email'\n#3 - Select 'Login' instead of 'Sign Up'\n#3 - When prompted to enter Email and Password, please use the demo account."
  app_review_information = {
      first_name: "Paul",
      last_name: "Gray",
      phone_number: "781-354-7635",
      email_address: "ios@evertrue.com",
      demo_user: "ios@evertrue.com",
      demo_password: password,
      notes: (org_values[:slug] == "evertrue" ) ? standard_notes : premium_notes
  }

  # part of process should be manually enter release notes into release_notes.txt -- add to DNA? Console?
  #
  # This deliver step never does screenshots, but will update metadata and submit the build for review
  deliver(
    app_version: "#{versionnumber}",
    app_identifier: org_values[:bundle_id],
    metadata_path: "fastlane/metadata",
    screenshots_path: "fastlane/screenshots",
    force: true,
    skip_screenshots: true,
    skip_binary_upload: true,
    submit_for_review: true,
    automatic_release: true,
    description: org_values[:app_description],
    name: org_values[:app_name_full],
    keywords: org_values[:app_keywords],
    marketing_url: org_values[:org_url],
    copyright: "2013 #{org_values[:org_name_short]}",
    dev_portal_team_id: org_values[:team_id],
    team_id: "#{org_values[:itc_provider]}",
    app_review_information: app_review_information
  )

  ifttt(
    api_key: "dspUh54u82BYiCg7Q21qoN",
    event_name: "alumni_directory_build",
    value1: "#{org_values[:slug]}/#{org_values[:oid]}",
    value2: "#{org_values[:org_name_short]}",
    value3: "#{versionnumber} (#{buildnumber})"
  )
  # dockhand(tag: tag)

  # post_to_slack(destination: "TestFlight", quiet: options[:quiet])

end


####### ERROR

error do |lane, exception|
  clean
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "ios@evertrue.com" # Your Apple email address

```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | 🚫 Update availaible |
| spaceship           | 0.38.1  | 🚫 Update availaible |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| deliver             | 1.15.1  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| gym                 | 1.12.0  | 🚫 Update availaible |
| sigh                | 1.11.2  | 🚫 Update availaible |
| match               | 0.11.0  | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| produce             | 1.3.0   | 🚫 Update availaible |
| scan                | 0.14.1  | 🚫 Update availaible |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | 🚫 Update availaible |
| supply              | 0.7.1   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.12.5       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.3        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.9.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.5.5        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.4        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.1.1        |
| dotenv                    | 2.1.1        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
</details>


*generated on:* **2016-11-29**
</details>

**Comment by raphael-goncalves** [comment]
I am facing the same issue !

**Comment by pj4533** [comment]
@raphael-goncalves   I think it is unlikely match will support this use-case.   I worked around it by making direct calls to Match, cert & sigh as necessary.   For example, to split out the generation of certificates, i do this:

```
  params[:workspace] = Match::GitHelper.clone(params[:git_url], params[:shallow_clone], skip_docs: params[:skip_docs], branch: params[:git_branch])

  Match::Generator.generate_certificate(params, :development)

  message = Match::GitHelper.generate_commit_message(params)
  Match::GitHelper.commit_changes(params[:workspace], message, params[:git_url], params[:git_branch])
```

Then I wait for the admin to create a profile on my behalf, using that cert.  Then, I thought I could just use Match normally to download the created profile, but unfortunately Match hardcodes a 'force: true' in its call to Sigh, so it always updates the profile, even if unnecessary.  So,  I run my generate profile command directly:

```
  params[:workspace] = Match::GitHelper.clone(params[:git_url], params[:shallow_clone], skip_docs: params[:skip_docs], branch: params[:git_branch])

  certs = Dir[File.join(params[:workspace], "certs", "development", "*.cer")]

  certificate_id = File.basename(certs.last).gsub(".cer", "")

  values = {
    app_identifier: org_values[:bundle_id],
    output_path: File.join(params[:workspace], "profiles", params[:type]),
    username: params[:username],
    force: false,
    cert_id: certificate_id,
    provisioning_name: profile_name,
    ignore_profiles_with_different_name: true,
    team_id: org_values[:team_id],
    development: true
  }

  arguments = FastlaneCore::Configuration.create(Sigh::Options.available_options, values)

  Sigh.config = arguments
  path = Sigh::Manager.start

  message = Match::GitHelper.generate_commit_message(params)
  Match::GitHelper.commit_changes(params[:workspace], message, params[:git_url], params[:git_branch])
```

All that code is basically just pulling apart the various bits of Match & doing it manually, with the few tweaks I needed.

Hope that helps other people stuck with only member-level accounts.

**Comment by raphael-goncalves** [comment]
Thanks for you snippet, I'll give it a try.

Also, another solution may be to prepare a Matchfile to the admin. When, the admin creates the account for the team member, he would : 
1. set the lattest as admin. 
1. Launch the match command ==> this will lead to store the certificate & provisioning profile in the GIT repo
1. downgrade the account as "Team Member"
1. ... and let the team work with match, straight from the git repo

The main disadvantage of our solutions is that, in the end, fastlane doesn't really automatically manage certificates for us. Team members or freed from this constraint, but admins still have actions to perform.

This said, I think `match` should split its workflow with the use of arguments. It would allow to create a workflow between huge teams and admins.

**Comment by milch** [comment]
@pj4533 @raphael-goncalves 

I see why this would be frustrating for you, but a big goal of `match` is to enforce best practices. We know that when you are working with clients or in large teams this is not always possible, but for the general majority of fastlane users the recommended setup is to have `match` manage the profiles of developer accounts, which means they have to be admin users. 

For us this is an edge case that currently doesn't affect a lot of users. If it was officially supported, we would have to bear the load of keeping the code working in the future, until the last user stops using the feature (i.e. at the heat death of the universe). 

If someone has particular needs that are not supported out of the box, they can always code up a custom solution like @pj4533 did. If you think that this is useful for other users, you can package it up and publish it as a fastlane plugin. If it turns out that a lot of users are using your plugin, we'll revisit adding this back into the main repo at a later time!
