### ISSUE TITLE
Pilot broken after update to spaceship 0.38.2

### ISSUE THREAD

**Issue by lkraider** [fastlane/fastlane#7229]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
pilot --help
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- unicode (LoadError)
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/utf8/unicode_proxy.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/identifier.rb:41:in `<class:Identifier>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/identifier.rb:31:in `<module:Babosa>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/identifier.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa.rb:16:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.38.2/lib/spaceship/client.rb:9:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.38.2/lib/spaceship.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/lib/pilot.rb:14:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/bin/pilot:4:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.11.6                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.9.3 (Apple Git-75)                |
| Installation Source | /usr/local/bin/fastlane                         |
| Host                | Mac OS X 10.11.6 (15G1108)                      |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib              |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode-8.1.app/Contents/Developer/ |
| Xcode Version       | 8.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date  |
| deliver             | 1.16.0  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| produce             | 1.3.1   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.110.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| did_you_mean              | 1.0.0       |
| highline                  | 1.7.8       |
| commander                 | 4.4.0       |
| terminal-table            | 1.4.5       |
| json                      | 1.8.3       |
| multipart-post            | 2.0.0       |
| faraday                   | 0.9.2       |
| faraday_middleware        | 0.10.0      |
| dotenv                    | 2.1.1       |
| net-ssh                   | 3.2.0       |
| net-sftp                  | 2.1.2       |
| plist                     | 3.2.0       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| krausefx-shenzhen         | 0.14.11     |
| slack-notifier            | 1.5.1       |
| i18n                      | 0.7.0       |
| thread_safe               | 0.3.5       |
| tzinfo                    | 1.2.2       |
| minitest                  | 5.8.3       |
| activesupport             | 4.2.7.1     |
| CFPropertyList            | 2.3.4       |
| claide                    | 1.0.1       |
| colored                   | 1.2         |
| nanaimo                   | 0.2.2       |
| xcodeproj                 | 1.4.1       |
| rouge                     | 1.11.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.7.1       |
| addressable               | 2.3.8       |
| xcode-install             | 2.0.9       |
| word_wrap                 | 1.0.0       |
| bundler                   | 1.13.6      |
| credentials_manager       | 0.16.2      |
| multi_json                | 1.12.1      |
| babosa                    | 1.0.2       |
| excon                     | 0.54.0      |
| gh_inspector              | 1.0.2       |
| fastlane_core             | 0.57.1      |
| fastimage                 | 1.6.8       |
| mini_magick               | 4.5.1       |
| xcpretty-travis-formatter | 0.0.4       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| logging                   | 2.1.0       |
| jwt                       | 1.5.6       |
| memoist                   | 0.15.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.3       |
| googleauth                | 0.5.1       |
| httpclient                | 2.8.2.4     |
| google-api-client         | 0.9.20      |
| io-console                | 0.4.5       |
</details>

*generated on:* **2016-11-29**
</details>

**Comment by lkraider** [comment]
```
$ gem list spaceship
*** LOCAL GEMS ***
spaceship (0.38.2, 0.38.1, 0.38.0, 0.37.0, 0.36.2, 0.36.0)

$ gem uninstall spaceship -v 0.38.2
Successfully uninstalled spaceship-0.38.2

$ pilot --help
---------------------------------------------
-------------------WARNING-------------------
---------------------------------------------
You're using an old version of spaceship
To ensure spaceship and fastlane works
update to the latest version.

Run `[sudo] gem update spaceship`

or `bundle update` if you use bundler.

You're on spaceship version: 0.38.1
Latest spaceship version  : 0.38.2

  pilot

  The best way to manage your TestFlight testers and builds from your terminal

  Commands:
    add        Adds new external tester(s) to a specific app (if given). This will also add an existing tester to an app.
    builds     Lists all builds for given application
    distribute Distribute a previously uploaded binary to Apple TestFlight
    export     Exports all external testers to a CSV file
    find       Find tester(s) (internal or external) by their email address
    help       Display global or [command] help documentation
    import     Create external testers from a CSV file
    list       Lists all registered testers, both internal and external
    remove     Remove external tester(s) by their email address
    upload     Uploads a new binary to Apple TestFlight

  Global Options:
    -u, --username STRING Your Apple ID Username (PILOT_USERNAME)
    -a, --app_identifier STRING The bundle identifier of the app to upload or manage testers (optional) (PILOT_APP_IDENTIFIER)
    -i, --ipa STRING     Path to the ipa file to upload (PILOT_IPA)
    -w, --changelog STRING Provide the what's new text when uploading a new build (PILOT_CHANGELOG)
    -d, --beta_app_description STRING Provide the beta app description when uploading a new build (PILOT_BETA_APP_DESCRIPTION)
    -n, --beta_app_feedback_email STRING Provide the beta app email when uploading a new build (PILOT_BETA_APP_FEEDBACK)
    -s, --skip_submission [VALUE] Skip the distributing action of pilot and only upload the ipa file (PILOT_SKIP_SUBMISSION)
(...)
```

**Comment by asfalcone** [comment]
Possibly related to https://github.com/fastlane/fastlane/pull/7210

**Comment by lkraider** [comment]
The fix is to install the `unicode` gem (need to update pilot/spaceship? dependencies):

```
$ gem install unicode
Fetching: unicode-0.4.4.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed unicode-0.4.4.2
1 gem installed

$ gem update spaceship
Updating installed gems
Updating spaceship
Fetching: spaceship-0.38.2.gem (100%)
Successfully installed spaceship-0.38.2
Gems updated: spaceship

$ pilot --help
  pilot

  The best way to manage your TestFlight testers and builds from your terminal

  Commands:
    add        Adds new external tester(s) to a specific app (if given). This will also add an existing tester to an app.
    builds     Lists all builds for given application
    distribute Distribute a previously uploaded binary to Apple TestFlight
    export     Exports all external testers to a CSV file
    find       Find tester(s) (internal or external) by their email address
    help       Display global or [command] help documentation
    import     Create external testers from a CSV file
    list       Lists all registered testers, both internal and external
    remove     Remove external tester(s) by their email address
    upload     Uploads a new binary to Apple TestFlight

  Global Options:
    -u, --username STRING Your Apple ID Username (PILOT_USERNAME)
    -a, --app_identifier STRING The bundle identifier of the app to upload or manage testers (optional) (PILOT_APP_IDENTIFIER)
    -i, --ipa STRING     Path to the ipa file to upload (PILOT_IPA)
    -w, --changelog STRING Provide the what's new text when uploading a new build (PILOT_CHANGELOG)
    -d, --beta_app_description STRING Provide the beta app description when uploading a new build (PILOT_BETA_APP_DESCRIPTION)
    -n, --beta_app_feedback_email STRING Provide the beta app email when uploading a new build (PILOT_BETA_APP_FEEDBACK)
    -s, --skip_submission [VALUE] Skip the distributing action of pilot and only upload the ipa file (PILOT_SKIP_SUBMISSION)
```

**Comment by hjanuschka** [comment]
babosa was introduced as dep. which in some cases requires unicode gem, and babosa did not specify it in gemspec. pr is out to add it to spaceship #7231

**Comment by mfurtak** [comment]
Thanks for the quick heads up! We're going to roll this change back and make a new release. Apologies for the trouble!

**Comment by asfalcone** [comment]
[_spaceship_ 0.38.3](https://github.com/fastlane/fastlane/releases/tag/spaceship/0.38.3)

**Comment by lkraider** [comment]
Confirmed with 0.38.4:

```
$ gem uninstall unicode
Successfully uninstalled unicode-0.4.4.2

$ pilot --help
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- unicode (LoadError)
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/utf8/unicode_proxy.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/identifier.rb:41:in `<class:Identifier>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/identifier.rb:31:in `<module:Babosa>'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa/identifier.rb:2:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/babosa-1.0.2/lib/babosa.rb:16:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.38.2/lib/spaceship/client.rb:9:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.38.2/lib/spaceship.rb:3:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/lib/pilot.rb:14:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/pilot-1.12.1/bin/pilot:4:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'

$ gem update spaceship
Updating installed gems
Updating spaceship
Fetching: spaceship-0.38.4.gem (100%)
Successfully installed spaceship-0.38.4
Gems updated: spaceship
zergling:~ zergling$ pilot --help
  pilot

  The best way to manage your TestFlight testers and builds from your terminal

  Commands:
    add        Adds new external tester(s) to a specific app (if given). This will also add an existing tester to
an app.
    builds     Lists all builds for given application
    distribute Distribute a previously uploaded binary to Apple TestFlight
    export     Exports all external testers to a CSV file
    find       Find tester(s) (internal or external) by their email address
    help       Display global or [command] help documentation
    import     Create external testers from a CSV file
    list       Lists all registered testers, both internal and external
    remove     Remove external tester(s) by their email address
    upload     Uploads a new binary to Apple TestFlight

  Global Options:
    -u, --username STRING Your Apple ID Username (PILOT_USERNAME)
    -a, --app_identifier STRING The bundle identifier of the app to upload or manage testers (optional)
(PILOT_APP_IDENTIFIER)
    -i, --ipa STRING     Path to the ipa file to upload (PILOT_IPA)
    -w, --changelog STRING Provide the what's new text when uploading a new build (PILOT_CHANGELOG)
    -d, --beta_app_description STRING Provide the beta app description when uploading a new build
(...)
```

**Comment by asfalcone** [comment]
Thanks @lkraider 🎉
