### ISSUE TITLE
Getting a crash on fast lane deliver

### ISSUE THREAD

**Issue by walsht** [fastlane/fastlane#723]
[22:17:04]: fastlane finished with errors
Successfully submitted crash report. If this is a problem with one of the tools you want to report
please submit an issue on GitHub and attach the following number to it: 'cbd1dc93ae24340c4bf58ce24f443632'

**Comment by walsht** [comment]
Not sure if this helps:

[22:16:58]: #<NoMethodError: undefined method `split' for #<Array:0x007f9663217c70>>
[22:16:58]: (erb):136:in `block in render'
(erb):113:in `each'
(erb):113:in `render'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `eval'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/erb.rb:849:in `result'
/Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/html_generator.rb:43:in `render'
/Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/html_generator.rb:5:in `run'
/Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/runner.rb:79:in `validate_html'
/Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/runner.rb:49:in `upload_metadata'
/Library/Ruby/Gems/2.0.0/gems/deliver-1.3.3/lib/deliver/runner.rb:20:in `run'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/actions/deliver.rb:18:in `run'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:128:in `block in execute_action'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:127:in `execute_action'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/fast_file.rb:149:in `method_missing'
Fastfile:63:in `block (2 levels) in parsing_binding'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/lane.rb:36:in `call'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:51:in `block in execute'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `chdir'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/runner.rb:46:in `execute'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/lib/fastlane/command_line_handler.rb:31:in `handle'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/bin/fastlane:35:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
/Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/bin/fastlane:152:in `run'
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.34.0/bin/fastlane:158:in `<top (required)>'
/usr/local/bin/fastlane:23:in `load'
/usr/local/bin/fastlane:23:in `<main>'
Could not render HTML preview. Do you still want to continue? (y/n)
y

**Comment by KrauseFx** [comment]
Is the app filled in with metadata and screenshots?

**Comment by walsht** [comment]
Yes, I have successfully used fastlane before.  But, this is a new mac and upgraded to the latest fastlane.  I resolved the  "undefined method `split'" by removing it from the Deliver file.  I was using it for my keywords before.   

I was able to verify my './Preview.html' and everything looked good.

But, still not able to successfully use deliver.
Here is the latest crash report, 1130df860bb70c270eab997037bbbd86

**Comment by KrauseFx** [comment]
@walsht don't worry about the generated HTML file, this is just a design issue. About the error: it seems like it's a standard internet/server error.

**Comment by walsht** [comment]
I don't think it is a internet/server error.  I get a crash every time...
```
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
HTML file confirmed...

[16:55:57]: Activating languages de-DE, en-US, es-ES, fr-FR, it-IT, ja-JP, ko-KR, pt-PT, ru-RU, cmn-Hans...
[16:55:58]: Variable Dump:
[16:55:58]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"bbl", :PLATFORM_NAME=>:ios, ...
[16:55:58]: 

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 118         |
| 4    | sigh                                | 306         |
| 5    | deliver                             | 11          |
+------+-------------------------------------+-------------+

[16:55:58]: fastlane finished with errors
Successfully submitted crash report. If this is a problem with one of the tools you want to report
please submit an issue on GitHub and attach the following number to it: 'f561aca3755479ce5146547349e9e626'
Also stored the crash report locally '/tmp/sentry_f561aca3755479ce5146547349e9e626.json'
```
or
```
[16:58:30]: fastlane finished with errors
Successfully submitted crash report. If this is a problem with one of the tools you want to report
please submit an issue on GitHub and attach the following number to it: 'b208cdd8bbf29f75d3ec48a57ca91519'
Also stored the crash report locally '/tmp/sentry_b208cdd8bbf29f75d3ec48a57ca91519.json'
```

**Comment by ohwutup** [comment]
Hey @walsht, I am going to close this issue for now because its been a while since there has been activity on it. If you are still running into this problem with new versions of the fastlane toolset, please don't hesitate to reopen the issue! Thanks! :sunny:
