### ISSUE TITLE
ensure_xcode_version sometimes fails

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#7230]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The first step in my `before_all` is: `ensure_xcode_version(version: "8.1")`.
`xcodebuild -version` outputs:

```
Xcode 8.1
Build version 8B62
```

`xcode-select -p` outputs:

```
/Applications/Xcode.app/Contents/Developer
```

I'm running this on an early 2016 Mac Pro with only Xcode 8.1 installed. Previously, it had Xcode 7.3.1 installed, but I deleted Xcode 7.3.1 from `/Applications` before installing Xcode 8.1.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

I'm not allowed to attach the full failing output. Sorry.

After updating `fastlane` to `1.110.0`, `ensure_xcode_version` sometimes fails with:
<details><summary>fastlane `ensure_xcode_version` failure output</summary>

```
--- Step: ensure_xcode_version ---
----------------------------------
$ xcversion selected | head -1 | xargs echo -n
▸ xargs: unterminated quote
Variable Dump:
{:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios master"}
 Exit status of command 'xcversion selected | head -1 | xargs echo -n' was 1 instead of 0.


Successfully generated documentation at path '/Users/jenkins/workspace/twitch-iphone-pull-requests/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 💥    | ensure_xcode_version                | 1           |
+------+-------------------------------------+-------------+

fastlane finished with errors
/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Exit status of command 'xcversion selected | head -1 | xargs echo -n' was 1 instead of 0. (FastlaneCore::Interface::FastlaneError)
xargs: unterminated quote

	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/helper/sh_helper.rb:55:in `sh_control_output'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/action.rb:98:in `sh'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/actions/ensure_xcode_version.rb:11:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:202:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:187:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:186:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:186:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:112:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:26:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:218:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:218:in `execute_flow_block'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:46:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:95:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.57.1/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:292:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/commands_generator.rb:36:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.110.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```
</details>

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1108)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

I'm not allowed to attach my `Fastfile`.

I'm not allowed to attach my `Appfile`.

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.1  | ✅ Up-To-Date        |
| deliver             | 1.15.1  | 🚫 Update availaible |
| snapshot            | 1.16.3  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.0   | 🚫 Update availaible |
| gym                 | 1.12.0  | 🚫 Update availaible |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.1  | 🚫 Update availaible |
| supply              | 0.7.1   | 🚫 Update availaible |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.3   | 🚫 Update availaible |
| fastlane            | 1.110.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| highline                  | 1.7.8       |
| commander                 | 4.4.0       |
| terminal-table            | 1.4.5       |
| json                      | 1.8.3       |
| multipart-post            | 2.0.0       |
| faraday                   | 0.9.2       |
| faraday_middleware        | 0.10.0      |
| dotenv                    | 2.1.1       |
| net-ssh                   | 3.2.0       |
| net-sftp                  | 2.1.2       |
| plist                     | 3.1.0       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| krausefx-shenzhen         | 0.14.11     |
| slack-notifier            | 1.5.1       |
| i18n                      | 0.7.0       |
| thread_safe               | 0.3.5       |
| tzinfo                    | 1.2.2       |
| minitest                  | 5.9.0       |
| activesupport             | 4.2.7.1     |
| colored                   | 1.2         |
| xcodeproj                 | 1.2.0       |
| rouge                     | 1.11.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.6.3       |
| addressable               | 2.3.8       |
| xcode-install             | 2.0.2       |
| word_wrap                 | 1.0.0       |
| multi_json                | 1.12.1      |
| babosa                    | 1.0.2       |
| excon                     | 0.45.4      |
| gh_inspector              | 1.0.2       |
| credentials_manager       | 0.16.2      |
| fastlane_core             | 0.57.1      |
| bundler                   | 1.12.5      |
| fastimage                 | 1.6.8       |
| mini_magick               | 4.5.1       |
| xcpretty-travis-formatter | 0.0.4       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| logging                   | 2.1.0       |
| jwt                       | 1.5.4       |
| memoist                   | 0.14.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.3       |
| googleauth                | 0.5.1       |
| thor                      | 0.19.1      |
| httpclient                | 2.8.2.2     |
| google-api-client         | 0.9.11      |
| claide                    | 1.0.1       |
</details>

*generated on:* **2016-11-29**
</details>

**Comment by asfalcone** [comment]
@hborders I *just* released [_fastlane_ 1.111.0](https://github.com/fastlane/fastlane/releases/tag/fastlane/1.111.0) which I think fixes this issue. You could update _fastlane_ and let me know? 👍

**Comment by hborders** [comment]
Works for me.

I get this warning now, which is weird:

`Couldn't verify that spaceship is up to date`

In context:

```
--- Step: ensure_xcode_version ---
----------------------------------
$ xcversion selected
▸ Couldn't verify that spaceship is up to date
▸ Xcode 8.1
▸ Build version 8B62
Selected Xcode version is correct: 8.1
```

**Comment by asfalcone** [comment]
Glad that `ensure_xcode_version` is working for you!

Can you help me with the other warning? pass `--verbose` to the command you're running and paste the output? Thanks!

**Comment by hborders** [comment]
That was with `--verbose`.

```
fastlane --verbose master
Successfully loaded Appfile at path 'XXXXXXX'
- apple_id: 'XXXXX'
- team_name: 'XXXXX'
- team_id: 'XXXXXXXX'
-------
Checking if there are any plugins that should be loaded...
---------------------------
--- Step: opt_out_usage ---
---------------------------
Disabled upload of used actions
-------------------------------------------------
--- Step: Verifying required fastlane version ---
-------------------------------------------------
Your fastlane version 1.111.0 matches the minimum requirement of 1.110.0  ✅
------------------------------
--- Step: default_platform ---
------------------------------
Driving the lane 'ios master' 🚀
----------------------------------
--- Step: ensure_xcode_version ---
----------------------------------
$ xcversion selected
▸ Couldn't verify that spaceship is up to date
▸ Xcode 8.1
▸ Build version 8B62
Selected Xcode version is correct: 8.1
```
