### ISSUE TITLE
[Feature Request] Have Deliver automatically retry on failure (up to a limit)

### ISSUE THREAD

**Issue by dannyNK** [fastlane/fastlane#7234]
When using deliver to upload screenshots we are at the whim of iTunesConnect, and quite often it fails. When uploading many screenshots in many languages it makes no sense to upload everything again, when some parts of the upload have actually succeeded.

At the moment I am having to copy out languages that have uploaded and saved correctly, then re-run deliver. It has taken many hours and I am now only half-way.

It would be great if deliver could retry the last language when failing, and if it fails X times, _then_ stop. 

Another option would be to save after X uploads, and jump back to the last save point if an error occurs (up to X times).

 Thanks,

: D

**Comment by KrauseFx** [comment]
_spaceship_ already does that partly, however I agree that this could probably be improved.
