### ISSUE TITLE
[Feature Request] Prepackaged sandboxed fastlane environment

### ISSUE THREAD

**Issue by tabrindle** [fastlane/fastlane#7240]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane is an amazing tool, but obviously requires a lot of maintenance, and judging by the issues on Github (and the issue template), **a huge proportion of Fastlane issues are related to the environment it is installed on**. Anything from Ruby versions (rvm, rbenv, system ruby etc), to SSL package issues, to system file permission issues (to sudo or not to sudo) can mess up an installation and cause extra debugging work for developers and maintainers alike, not to mention all the duplicate issues. 

Fastlane needs, to keep both maintainers and developers more productive, is **a sandboxed environment that will ensure all Fastlane tools and all dependencies are packaged and working together** as intended with no side effects as a result of differences in installation.

This can be done in a variety of ways, either similar to how [calabash](https://github.com/calabash/calabash-ios) works, or even a [docker](https://www.docker.com/products/overview) container.

I would happily volunteer to work with maintainers on this project.

**Comment by asfalcone** [comment]
Hi @tabrindle This sounds similar to what we build with the [installer](https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip). We offer this as one of the [install options](https://github.com/fastlane/fastlane#choose-your-installation-method). 

Have you given this a try? Let us know what you think!

**Comment by tabrindle** [comment]
Cue sad-trombone sound. I hadn't seen this, and will give it a shot. Interesting that I hadn't seen it on the front page of the repo - we might push this as a first step of debugging for people in issues, if they aren't already using it. 

Thanks!

**Comment by asfalcone** [comment]
@tabrindle It was very recent! Don't feel bad at all! We are suggesting it to more and more people to see how it works in different environments and it may be the recommended installation approach in the future 🎺
