### ISSUE TITLE
Supply setup instructions are outdated

### ISSUE THREAD

**Issue by owurman** [fastlane/fastlane#7242]
https://github.com/fastlane/fastlane/tree/master/supply has instructions for the Google Play Console which no longer match the current Google Play Console UI.

Specifically, starting at step 3:
3. Click the Create Service Account button and follow the Google API Console link in the dialog

**Comment by asfalcone** [comment]
@owurman We'd happily accept a PR to update the instructions! 👍

**Comment by hjanuschka** [comment]
i just tested it and current README seems to be fine, i think this PR https://github.com/fastlane/fastlane/pull/5992  updtaed it.

**Comment by owurman** [comment]
Perhaps I'm using a different version of the developer console.

**Comment by hjanuschka** [comment]
@owurman i just tested it again, documentation still seems to be correct - can you confirm, and close the issue?

**Comment by owurman** [comment]
Not sure how I'd check it now that I'm already set up. Go ahead and close
it I guess.
