### ISSUE TITLE
[Feature Request] Change max 'fetch_application' iterations to configurable in produce create_new_app

### ISSUE THREAD

**Issue by erikjthomas** [fastlane/fastlane#7251]
### Feature Description

Change max 'fetch_application' iterations to configurable in call to produce. 

In 'itunes_connect.rb' in Produce, line 39, after creating a new app on iTC, it is **hardcoded to wait 200 iterations** of 15 seconds each while waiting for the app to become available on iTC:

UI.crash!("Couldn't find newly created app on iTunes Connect - please check the website for more information") if counter == **200**

iTC has been very slow the past few weeks when creating new apps and this timeout is being reached very nearly every time. Great to pass an additional config property to produce that defines how many iterations to wait before failing. This could default to 200 if not provided.

Thanks!

**Comment by KrauseFx** [comment]
We try to avoid adding more options to _fastlane_ if not absolutely necessary. Instead we usually try to fix the underlying issue or have more sensible defaults 👍 
How long does waiting take for you usually?

**Comment by erikjthomas** [comment]
Only Apple can fix the underlying issue in this case. We need to be able to create 20+ apps on iTC in a single day. I was able to do 45 apps in one day a couple weeks ago when iTC was fast.

To answer your question, the last 5 apps I've tried to create on iTC with produce all timed out after 200 X 15 secs = 50 minutes.

During the past several weeks creating new apps takes hours before they show up as editable, so I have started doing batches of apps in stages, updating scripts to do the produce first for them all, and then the next day doing the sigh, pem, creating app groups, and deliver, etc.

This is OK though. So you can close this issue if you like. 

We are so loving Fastlane by the way. I'd love to become a contributor once our startup reaches break-even and I can afford to take the time. Maybe Q1 '17 if you need more contributors.

Cheers,

Erik

**Comment by LanfordCai** [comment]
Similar situation with Erik, and hope the fetch times can be customized :-)

**Comment by hjanuschka** [comment]
same here - i personally think increasing the timeout will not fix it, making it an option is probably a workaround.

i even had one app stuck for more that 24hours.


i filed a radar - maybe you guys can dupe it: 
http://openradar.appspot.com/radar?id=5024333961363456 ( rdar://29437198 )
