### ISSUE TITLE
Snapshot - Pass xcodebuild arguments to snapshot

### ISSUE THREAD

**Issue by barteljan** [fastlane/fastlane#7255]
It would be very nice if we could pass some xcodebuild arguments in snapshot.

This would be exceptional awesome since we create our snapshots in one XCTest, while having many others with no snapshot attached.

We would speed up the snapshot creation with factor unlimited if we could choose this exclusive testcase with a xcodebuild parameter like that:

-only-testing TestBundle/TestSuite/Screenshots

Thank you :-)

**Comment by hjanuschka** [comment]
PR -> https://github.com/fastlane/fastlane/pull/7261

**Comment by batesyuk** [comment]
👍
