### ISSUE TITLE
Fastlane not updating

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7257]
The after successfully running the `fastlane` lane. I get a message saying there is a new version available. When I do `sudo gem update fastlane`, I get message saying 'Nothing to update'. Refer to screenshot.

![screenshot 2016-11-30 10 51 44](https://cloud.githubusercontent.com/assets/2100166/20762267/6e1962e0-b6eb-11e6-9aa0-f8ff79a7dd8f.png)

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.1                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.9.3 (Apple Git-75)                |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.1 (16B2657)                      |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.108.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #

  lane :screenshots do 
  	snapshot(scheme: "Cotton", stop_after_first_error: true, devices: ["iPhone 7 Plus"], languages: ["en-US"])
  	frameit(white: true)
  	deliver
  end

  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Cotton', export_method: 'ad-hoc', use_legacy_build_api: true)

    emails = values[:test_email] ? values[:test_email] : ['rtayal11@gmail.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '02d3f7db22ac1a3e538528547a694d5230eb8278',
             build_secret: 'af6ede98bc0742057c556b0ed733e4c57ae435cd7cc81f516bb2b4e456b7e234',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end

  lane :app_store do
    match(app_identifier: ['com.rtayal.Cotton'], type: 'appstore')
    gym(scheme: 'Cotton')
    pilot(skip_waiting_for_build_processing: true)
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.rtayal.Cotton" # The bundle identifier of your app
apple_id "contact@appikon.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.56.0  | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| babosa              | 1.0.2   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.56.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-11-30**
</details>

**Comment by hjanuschka** [comment]
i think you are using the contained version? 
try manually updating it with redownloading it: https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip

**Comment by KrauseFx** [comment]
Thanks @hjanuschka 👍
