### ISSUE TITLE
How to get latest uploaded IPA version of an app from iTC

### ISSUE THREAD

**Issue by erikjthomas** [fastlane/fastlane#7258]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Using Spaceship to retrieve app info for an existing app on iTC, I am having trouble determining the highest version number uploaded so I can programmatically bump the version when submitting new builds.

Spaceship::Tunes.login(Credentials::ITUNES_SIGNING_USER_NAME, 
    Credentials::ITUNES_SIGNING_PASSWORD)
app = Spaceship::Tunes::Application.find(bundle_id)

Both app.build_version and app.latest_version show 1.0.1 when there is actually a 1.0.2 already on iTC. I need the latest version for bumping and then setting in the Info.plist before repackaging and uploading.

**NOTE: I do not have xcode projects for the IPAs we package and upload so suggestions regarding xcode project settings will not help.**

Do I need to iterate version_sets to find the latest uploaded build? Or is there a simple API already available in Fastlane to retrieve the latest version of an app on iTC that has been uploaded?

Thanks in advance for suggestions.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

N/A

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.gem/ruby/2.3.1/bin/fastlane              |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.rubies/ruby-2.3.1/lib                    |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.57.2  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| spaceship           | 0.38.4  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| sigh                | 1.12.0  | ✅ Up-To-Date  |
| deliver             | 1.16.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.11 |
| slack-notifier            | 1.5.1   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| activesupport             | 4.2.7.1 |
| claide                    | 1.0.1   |
| colored                   | 1.2     |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| bundler                   | 1.13.6  |
| credentials_manager       | 0.16.2  |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| multi_json                | 1.12.1  |
| excon                     | 0.54.0  |
| gh_inspector              | 1.0.2   |
| fastlane_core             | 0.57.2  |
| io-console                | 0.4.5   |
| plist                     | 3.2.0   |
| multi_xml                 | 0.5.5   |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| babosa                    | 1.0.2   |
| xcode-install             | 2.0.9   |
</details>

**Comment by erikjthomas** [comment]
Even in version_history and version_sets there is only one version being retrieved. Normally this works to get latest version, but I think the problem here is that a version was submitted for beta testing and failed the review, and after uploading a newer version, the fetch_application call is only going to return the first version.

Perhaps there is another iTC API for retrieving information about other uploaded builds?

**Comment by hjanuschka** [comment]
@erikjthomas 
i don't get the issue 100% 

how about that:
```ruby
app = Spaceship::Tunes::Application.find("krone.at-fivexfive")

# all build trains
versions = app.build_trains.keys
# latest should be 
latest_non_live_version = app.build_trains.keys.last


# get build info from latest version, non-ready-for-sale
builds = app.build_trains[latest_non_live_version].builds


# to get latest build in train
train = app.build_trains[latest_non_live_version]
build_nr = train.builds.map(&:build_version).map(&:to_i).sort.last


# app store - currently ready-for-sale
version = app.live_version.version

```

does that help you?

**Comment by erikjthomas** [comment]
Yep, that did the trick. Thanks, hjanuschka!
