### ISSUE TITLE
IAP not being reflected after itmsp creation

### ISSUE THREAD

**Issue by gonzaloju** [fastlane/fastlane#726]
We create IAP items via itmsp to itunesconnect. For the last 48hs these items havent been able to appear in the system. Is anyone experiencing the same bug?

**Comment by KrauseFx** [comment]
`deliver` and `fastlane` doesn't support in app purchases.

**Comment by ohwutup** [comment]
Going to close this issue due to inactivity, please feel free to reopen it if necessary!
