### ISSUE TITLE
xxx is already taken, using another one

### ISSUE THREAD

**Issue by hpsoar** [fastlane/fastlane#7271]
### New Issue Checklist

- [ ] match version 0.11.0
- [ ] match(type: "development", app_identifier: "some app indentifier", force: true)
(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### 
The name 'match Development <app_identifier>' is already taken, using another one.
Creating new provisioning profile for '<app_identifier>' with name 'match Development <app_identifier> 1480564048'

#####
when I run the command, there's already a invalid provisioning profile on developer.apple.com.

I wonder why `match` doesn't just update the invalid provisioning profile instead of creating a new one.

**Comment by KrauseFx** [comment]
It should automatically repair your existing profile, please share your output and env as requested by the bot 👍

**Comment by hpsoar** [comment]
when I run fastlane env, it yields

[!] Could not find lane 'ios env'. Available lanes: ios test, ios add_device, ios invoke, ios certificates, ios beta, ios inhouse_debug, ios inhouse_release, ios appstore, ios upload_appstore, ios submit

**Comment by KrauseFx** [comment]
@hpsoar Try `fastlane env`

**Comment by hpsoar** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

def do_update_certificates(t)
     match(type: t, app_identifier: "com.chunyu.SymptomChecker", readonly: true)
     match(type: t, app_identifier: "com.chunyu.SymptomChecker.Extension", readonly: true)
end

def project_scheme()
# define APP_SCHEME in .env file
  return ENV['APP_SCHEME']
end

def clean_certificates
  sh 'rm -rf ~/Library/MobileDevice/Provisioning\ Profiles/*'
end

def do_renew_certificates(t)
     clean_certificates()
     match(type: t, app_identifier: "com.chunyu.SymptomChecker", force: true)
     match(type: t, app_identifier: "com.chunyu.SymptomChecker.Extension", force: true)
     match(type: t, app_identifier: "com.chunyu.DoctorClient", force: true)
     match(type: t, app_identifier: "com.chunyu.StepCounter", force: true)
     match(type: t, app_identifier: "com.chunyu.StepCounter.Today", force: true)
     match(type: t, app_identifier: "com.chunyu.StepCounter.watchkitextension", force: true)
     match(type: t, app_identifier: "com.chunyu.StepCounter.watchkitapp", force: true)
end

def renew_certificates
  sh 'echo "Paraphrase: 768"'
  do_renew_certificates("development")
  do_renew_certificates("adhoc")
  do_renew_certificates("appstore")
end

def update_certificates
  sh 'echo "Paraphrase: 768"'
  clean_certificates()
  do_update_certificates("development")
  do_update_certificates("adhoc")
  do_update_certificates("appstore")
end

def deliver_to_appstore(submit)
    version = get_version_number(xcodeproj: project_scheme() + ".xcodeproj", target: project_scheme())

    sh 'echo ' + version
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"  #can upload ipa Successfully with this
    update_text = IO.read('../appstore_update_text.txt')
#update_version = IO.read('../appstore_update_version.txt')
    deliver(
      force: true,              #false: generate html report
      submit_for_review: submit,  #submit to appstore directly
      ipa: "./build_f/" + project_scheme() + ".ipa",
      app_version: version, #update_version.strip,
      #metadata_path: "./fastlane/metadata",
      #app_icon './AppIcon.png'
      submission_information: ({
        add_id_info_uses_idfa: true,       #是否使用idfa
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,   #将使用idfa归因于之前的广告
        add_id_info_tracks_install: true,  #将使用idfa归因于之前的安装
        add_id_info_limits_tracking: true,
        export_compliance_uses_encryption: false,
        export_compliance_encryption_updated: false,
        #export_compliance_compliance_required: true,
        }),
      release_notes: ({
        'zh-Hans' => update_text
        }),
      automatic_release: true,
      skip_binary_upload: false,
      skip_screenshots: false,
      skip_metadata: false,
    )
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "60"
    ENV['MATCH_PASSWORD'] = '768'
    #sh "pod update"
    #cocoapods   # this will run pod install
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "register devices"
  lane :add_device do
      register_devices(devices_file: "./devices.txt")
      renew_certificates
      update_certificates
  end

  desc "invoke profiles"
  lane :invoke do
      renew_certificates
  end

  desc "update certificates"
  lane :certificates  do
      update_certificates
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Generate ipa for Debug distribution"
  lane :inhouse_debug do
    do_update_certificates("development")
    gym(
      sdk: "iphoneos",
      configuration: "Debug",
      scheme: project_scheme(),
      clean: true,
      export_method: "development",
      output_directory: "build", # Destination directory. Defaults to current directory.
      build_path: "build",  #where the archive is
    )
  end

  desc "Generate ipa for AdHoc distribution"
  lane :inhouse_release do
    do_update_certificates("adhoc")
    gym(
      sdk: "iphoneos",
      configuration: "Release",
      scheme: project_scheme(),
      codesigning_identity: "iPhone Distribution: Beijing Spring Rain Software Co Ltd (KN3N6ZJA53)",
      clean: true,
      export_method: "ad-hoc",
      output_directory: "build", # Destination directory. Defaults to current directory.
      build_path: "build",  #where the archive is
    )
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    do_update_certificates("adhoc")
    do_update_certificates("appstore")
    # Build
    gym(
      sdk: "iphoneos",
      configuration: "Release",
      scheme: project_scheme(),
      codesigning_identity: "iPhone Distribution: Beijing Spring Rain Software Co Ltd (KN3N6ZJA53)",
      clean: true,
      export_method: "app-store",
      output_directory: "build_f", # Destination directory. Defaults to current directory.
      build_path: "build_f",  #where the archive is
      buildlog_path: "log_f",
      include_bitcode: false,
      include_symbols: true,
    )

    # submit to appstore
    deliver_to_appstore(false)
    # frameit
  end

  lane :upload_appstore do
    deliver_to_appstore(false)
  end

  lane :submit do
    deliver_to_appstore(true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
    sh "echo 'fastlane fail' > ../log_f/fastlane_result.txt"
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.chunyu.SymptomChecker" # The bundle identifier of your app
apple_id "kakarottochunyu@163.com" # Your Apple email address

team_id "KN3N6ZJA53"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date        |
| spaceship           | 0.38.5  | ✅ Up-To-Date        |
| deliver             | 1.16.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.3  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.1   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.2   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.7.1   | 🚫 Update availaible |
| match               | 0.11.0  | 🚫 Update availaible |
| screengrab          | 0.5.2   | 🚫 Update availaible |
| fastlane            | 1.110.0 | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.1.2        |
| xcodeproj                 | 1.4.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| addressable               | 2.4.0        |
| xcode-install             | 2.0.4        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.45.4       |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.58.0       |
| bundler                   | 1.12.5       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.3      |
| google-api-client         | 0.9.13       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.5        |
</details>


*generated on:* **2016-12-07**
</details>

**Comment by hpsoar** [comment]
in my case, there are already provisioning profiles with same nave on developer.apple.com, but these profiles are invalid.

I wonder why match just update these invalid profiles rather than create new ones
