### ISSUE TITLE
[match] can't commit new provisioning profiles when shallow_clone = true

### ISSUE THREAD

**Issue by vbresults** [fastlane/fastlane#7272]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
error: failed to push some refs to 'git+ssh://git@github.com/vbresults/match.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[00:32:14]: Exit status: 1
[00:32:14]: Couldn't commit or push changes back to git...
[00:32:14]: Exit status: 1
```

I can clone the repo with --depth=1, remove a profile, and commit the change, so there is no technical justification for this, it's just a bug somewhere.

**Comment by hjanuschka** [comment]
can you provide full output of match?
was the repo modified after the clone (this is what git reports)

**Comment by vbresults** [comment]
I can't provide the full output at this time.

That said, no, it wasn't modified after the clone.  But before the clone, it was.  As I said earlier, if modify it outside of match, do a git pull --depth=1, make a new commit, and push it,

There are no problems with match reading or writing to it later.  It's *only* if I have shallow_clone set to true that this occurs.

**Comment by vbresults** [comment]
@KrauseFx Please take a look at this, it's adding a lot to the build time

**Comment by vbresults** [comment]
@TKBurner @KrauseFx Please resolve this, I am getting tired of having to manually trim my repos :S

**Comment by vbresults** [comment]
:S

**Comment by KrauseFx** [comment]
> It would do a git push -f; we'd lose history, but in use cases where that doesn't matter, it's an option not default, and is really helpful for this use case and maybe some others.

Doesn't seem like a good approach.

> I can clone the repo with --depth=1, remove a profile, and commit the change, so there is no technical justification for this, it's just a bug somewhere.

You see all the executed commands printed out as _match_ runs, can you let me know how the commands need to be modified to make it work, while avoiding force pushign?

**Comment by vbresults** [comment]
It's the only approach that works.

**Comment by nafu** [comment]
Could you share the git version you are using?

**Comment by vbresults** [comment]
2.10.1.

**Comment by nafu** [comment]
@vbresults Thanks! 🙂 

Could you share the complete output when running _fastlane_?
We'd love to reproduce your case so that we can solve this.
