### ISSUE TITLE
Match and SIGH_PROFILE_PATH

### ISSUE THREAD

**Issue by orkenstein** [fastlane/fastlane#7281]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The [documentation](https://docs.fastlane.tools/codesigning/xcode-project/#) states that `match` fills `lane_context` in a proper way:
> If you use fastlane you don't have to do any extra work, since the environment variable for the latest profile are automatically set by match
> ```
> lane :beta do
>   match(type: "adhoc")
>   gym
> end
> ```

But I can't find any confirmation. Even variable dump shows only this:
```
Variable Dump:
{:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build_for_shipping", :SIGH_PROFILE_TYPE=>"app-store"}
```
Does it really work? Or `gym` reads another values?

**Comment by KrauseFx** [comment]
Nice catch, it seems like _match_ only fills in the profile type in the lane context, and stores the rest as environment variable.

**Comment by orkenstein** [comment]
@KrauseFx why not to set profile and certificate to lane context?

**Comment by KrauseFx** [comment]
`gym` should automatically fetch the profile from the environment variable. Doesn't it work for you?

**Comment by orkenstein** [comment]
I don't use `gym`. It's an **Unreal Engine** project, so I have to build it with custom script. I want to pass profile (and certificate if possible) to `resign` and `pilot` tools. Now I do it manually with `options`.
Just for the reference, could you please point to the part, where `gym` reads the profile from the environment variable?

**Comment by ruslanfutureuniverse** [comment]
Want to resurrect this issue.
How to find `Lane Context` values actions are actually use?

**Comment by hjanuschka** [comment]
@ruslanfutureuniverse you can get a list of available ENV vars per action by running:

`fastlane action adb` (where adb is the action in this case)

![bildschirmfoto 2017-01-24 um 12 13 17](https://cloud.githubusercontent.com/assets/2891702/22245097/883910bc-e22e-11e6-8e04-f7e140f2dd11.png)


i am not sure if there is a posibility to actually list what Lanecontext is set or used.

**Comment by ruslanfutureuniverse** [comment]
@hjanuschka yes, but it's about ENV only. No mention of `Lane context`. So, it's hard to know where it actually works or not.

**Comment by hjanuschka** [comment]
@ruslanfutureuniverse as said, i don't think there is a consistent way right now.

some actions have module inside `SharedValues` where you can see what values are there. (but right now i dont see some code on how to display them) - might be worth adding to the `fastlane action ` call.

**Comment by ruslanfutureuniverse** [comment]
@hjanuschka yes, it would be great to see all this values somewhere.
