### ISSUE TITLE
Custom PLIST

### ISSUE THREAD

**Issue by anthonygeranio** [fastlane/fastlane#7282]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

On the project I work on we have created our own plist called `AppName-Info.plist` and save that in `AppName/Application/`.

Using things `get_version_number` doesn't seem to work in our lanes because Fastlane can't seem to find our plist.

I'm wondering if there's a way to currently set a default plist and tell Fastlane where to find it so that when these commands are run they can be properly set. ;)

**Comment by lyndsey-ferguson** [comment]
According to [these docs](https://developer.apple.com/library/content/qa/qa1827/_index.html). It seems that `get_build_number` relies on agvtool which scans your xcode project file. Has that project file been set up to point to your new AppName-Info.plist properly?
