### ISSUE TITLE
Brew cask install fastlane fails

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#7290]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`brew cask install fastlane` fails with `Error: Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16`

**Comment by KrauseFx** [comment]
Please share the complete output when trying to install _fastlane_ 👍

**Comment by postmechanical** [comment]
That is the complete output.

**Comment by postmechanical** [comment]
Interesting...
```
ll /Library/Ruby/Gems/2.0.0/extensions
total 0
drwxr-xr-x   4 root  wheel  136 Jun 11  2015 .
drwxr-xr-x  10 root  wheel  340 Oct 28 15:44 ..
drwxr-xr-x   3 root  wheel  102 Jun  8  2014 universal-darwin-14
drwxr-xr-x   3 root  wheel  102 Jun 11  2015 universal-darwin-15
```

**Comment by postmechanical** [comment]
Is `brew` or the `fastlane` keg not respecting `$GEM_HOME`, which in my case is exported as `/Users/foobar/.gems`?

**Comment by hjanuschka** [comment]
@postmechanical have you tried unsetting the GEM_HOME and installing fastlane - as a test if it is the cause?

**Comment by postmechanical** [comment]
@hjanuschka I typically run with `export GEM_HOME=~/.gems`. Install with it set to that value and unset entirely always fails with `Error: Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-16`

**Comment by crawlik** [comment]
@postmechanical solved `brew cask install` problem using `HOMEBREW_RUBY_PATH=$(which ruby)  brew cask install whatever`. Note `which ruby` should point to NON-SYSTEM ruby. In my case `~/.rvm/rubies/ruby-2.3.3/bin/ruby`

**Comment by postmechanical** [comment]
@crawlik Hmmm...no difference for me using `/usr/local/bin/ruby` installed via `brew`.

**Comment by crawlik** [comment]
`brew --config | grep 'Homebrew Ruby'`
```
Homebrew Ruby: 2.0.0-p648 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
```
I get ^^^

```
$ /usr/bin/ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
```
^^^ see what version is OSX system ruby and make sure that `/usr/local/bin/ruby` is NOT the same.

```
 /usr/local/bin/ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
```
^^^ in my case

all that magic of what ruby to call happens in `/usr/local/Homebrew/Library/Homebrew/utils/ruby.sh` 
you can debug it and see what is happening there in your case

**Comment by postmechanical** [comment]
@crawlik 
```
brew --config | grep 'Homebrew Ruby'
Homebrew Ruby: 2.0.0-p648

/usr/bin/ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

/usr/local/bin/ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
```

**Comment by crawlik** [comment]
Hmm looks good me. You would need to look into `/usr/local/Homebrew/Library/Homebrew/utils/ruby.sh` and put some printouts to see what `HOMEBREW_RUBY_PATH` is set to.
