### ISSUE TITLE
Update icons for retina display

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7291]
The current icons on https://codesigning.guide are not updated for retina display. Please see the attached screenshot. Looks blurry on retina display.

<img width="925" alt="screenshot 2016-12-02 21 23 04" src="https://cloud.githubusercontent.com/assets/2100166/20856493/adb6c0fa-b8d5-11e6-92a3-239953957820.png">

**Comment by KrauseFx** [comment]
I forwarded this to the team responsible for the website, I'll see what we can do 👍
