### ISSUE TITLE
Snapshot UI test error "No buildable for testable." when attempting to record actions in iMessage Sticker app

### ISSUE THREAD

**Issue by AT5Hack** [fastlane/fastlane#7293]
### New Issue Checklist

- [ YES] Updated fastlane to the latest version
- [YES ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to use Snapshot with an iMessage sticker app with no luck. I created a UITest target than then dragged the SnapshotHelper.swfit file in. I attempted to record actions when I got the error "No buildable for testable."

I read on Stackoverflow that you have to set the UITest Target's target application under "Testing"; but when I tried it only gives me the option  "None".

Also when I run Snapshot it gives me the error "Scheme is not properly configured, make sure to check out the snapshot README" I assume its because of the problem above.

###Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.2                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.2/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

lane :sentToAppStore do
  gym(scheme: “StickerPackExtension”)
  produce
  appstore       

end

lane :releaseTheApp do
  produce(
    username: ‘auston.salvana@live.com’,
    app_identifier: 'com.ASolo.CookingStickers',
    app_name: ‘Cooking Stickers’,
    language: 'English',
    app_version: '1.0',
    sku: ‘CookingStickers’,
    team_name: ‘auston salvana’ # only necessary when in multiple teams,
  )

  deliver
end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ASolo.CookingStickers" # The bundle identifier of your app
apple_id "auston.salvana@live.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.57.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| did_you_mean        | 1.0.0   |
| json                | 1.8.3   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.57.2  |
| io-console          | 0.4.5   |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.8.5   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.3   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-12-04**
</details>

**Comment by JustinJiaDev** [comment]
Currently, there is no way to use snapshot with iOS extension applications (iMessage, keyboard, etc).
