### ISSUE TITLE
Gym archive succeeds but fails to export ipa for Enterprise builds

### ISSUE THREAD

**Issue by brandonroeder** [fastlane/fastlane#7308]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I use the gym command, the archive succeeds but it fails to export. This occurs when building an Enterprise signed app. Additionally, on all other builds (app-store, & ad-hoc) it takes ~20+ minutes to export the app after a successful archive. This seems crazy long. I tried looking at the logs but nothing jumps out at me. 

I recently had to disable the 'use_legacy_build_api' flag because iTunes Connect was rejecting the app for WatchKit issues. I've been unable to build since. 

Not using match, we have a ton of different configs so we manage the provisioning profiles ourselves.

Any ideas? I've combed through pretty much every gym issue and came up empty. The only relevant issue I found was #6583 but there was no real solution. 

Let me know if you need any more info!

##### Complete output when running fastlane, including the stack trace and command used

**Gym command:**

```
gym(project: "./Projects/Kevin/Kevin.xcodeproj",
	scheme: "Kevin",
	output_name: "#{options[:org]}-#{ENV['BUILD_ID']}-#{options[:env]}-#{options[:type]}.ipa",
        codesigning_identity: [REDACTED],
	export_method: "enterprise",
	include_bitcode: false,
	include_symbols: false)

```

```
[11:20:49]: ▸ Touching entios1.app
[11:23:00]: ▸ Signing /Users/capitanbuild/Library/Developer/Xcode/DerivedData/Kevin-ewrlpkgiurmwdjfrdufxkfpzvwaf/Build/Intermediates/ArchiveIntermediates/Kevin/InstallationBuildProductsLocation/Applications/entios1.app
[11:23:30]: ▸ Archive Succeeded
[11:23:30]: Generated plist file with the following values:
[11:23:30]: ▸ -----------------------------------------
[11:23:30]: ▸ {
[11:23:30]: ▸   "method": "enterprise"
[11:23:30]: ▸ }
[11:23:30]: ▸ -----------------------------------------

+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/42/9h0fg5xj3xs3s9wrc1t8_4pm0000gn/T/gym_config20161205-13326-1oyxet.plist -archivePath '/Users/capitanbuild/Library/Developer/Xcode/Archives/2016-12-05/MMB-103-rsdevelopment-qa 2016-12-05 11.17.28.xcarchive' -exportPath /var/folders/42/9h0fg5xj3xs3s9wrc1t8_4pm0000gn/T/gym_output20161205-13326-8vbuh5
2016-12-05 11:23:31.325 xcodebuild[19255:58996] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/42/9h0fg5xj3xs3s9wrc1t8_4pm0000gn/T/Kevin_2016-12-05_11-23-31.324.xcdistributionlogs'.
1.2.840.113635.100.1.61
2016-12-05 11:32:39.825 xcodebuild[19255:58996] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7ff1b92de570>: Error Domain=IDEFoundationErrorDomain Code=1 "Codesign failed" UserInfo={NSLocalizedDescription=Codesign failed}
error: exportArchive: Codesign failed
Error Domain=IDEFoundationErrorDomain Code=1 "Codesign failed" UserInfo={NSLocalizedDescription=Codesign failed}

** EXPORT FAILED **
[11:32:39]: Exit status: 70
[11:32:39]: 📋  For a more detailed error log, check the full log at:
[11:32:39]: 📋  /Users/capitanbuild/Library/Logs/gym/entios1-Kevin.log
[11:32:39]: Variable Dump:
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.1                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.1 (16B2555)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.2  | ✅ Up-To-Date        |
| spaceship           | 0.38.4  | ✅ Up-To-Date        |
| deliver             | 1.15.1  | 🚫 Update availaible |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | ✅ Up-To-Date        |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.2   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| credentials_manager       | 0.16.2       |
| fastlane_core             | 0.57.2       |
| bundler                   | 1.13.6       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| plist                     | 3.2.0        |
</details>

*generated on:* **2016-12-05**
</details>

**Comment by brandonroeder** [comment]
Hmmmm I tried running the export command by itself and it worked...

```
Capitans-Mac-mini:~ capitanbuild$ xcodebuild -exportArchive -exportOptionsPlist /var/folders/42/9h0fg5xj3xs3s9wrc1t8_4pm0000gn/T/gym_config20161205-13326-1oyxet.plist -archivePath '/Users/capitanbuild/Library/Developer/Xcode/Archives/2016-12-05/MMB-103-rsdevelopment-qa 2016-12-05 11.17.28.xcarchive' -exportPath /var/folders/42/9h0fg5xj3xs3s9wrc1t8_4pm0000gn/T/gym_output20161205-13326-8vbuh5 -verbose
2016-12-05 11:37:48.485 xcodebuild[29365:85803] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/42/9h0fg5xj3xs3s9wrc1t8_4pm0000gn/T/Kevin_2016-12-05_11-37-48.483.xcdistributionlogs'.
1.2.840.113635.100.1.61
Exported MMB-103-rsdevelopment-qa 2016-12-05 11.17.28.xcarchive to: /var/folders/42/9h0fg5xj3xs3s9wrc1t8_4pm0000gn/T/gym_output20161205-13326-8vbuh5
** EXPORT SUCCEEDED **
```

**Comment by milch** [comment]
@brandonroeder I see that you are running on Sierra - could it be related to issue #6866 ? Can you try removing the certificate and re-running match?
