### ISSUE TITLE
deliver: there is no web session to update

### ISSUE THREAD

**Issue by Poliuk** [fastlane/fastlane#7309]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Same issue described here  #6826  But iTunes Connect seems to be ok.

```
[!] The request could not be completed because:
	there is no web session to update
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| deliver             | 1.16.0  | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.57.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| match               | 0.11.0  | ✅ Up-To-Date  |
| pem                 | 1.4.0   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| spaceship           | 0.38.4  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.0        |
| concurrent-ruby           | 1.0.2        |
| credentials_manager       | 0.16.2       |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 0.57.2       |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.1        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2016-12-05**
</details>

**Comment by danramteke** [comment]
same here.

**Comment by JimHowell20** [comment]
same here :(

**Comment by osolano** [comment]
same here

**Comment by GYFK** [comment]
same

**Comment by avalanched** [comment]
same for `pilot`

**Comment by Matthew-WON** [comment]
Same for `pilot` as well

**Comment by pawelkata** [comment]
same for pilot for me, too

**Comment by jeroenleenarts** [comment]
Tried uploading with Apple's Application Loader. That works without a problem... :/

**Comment by alexmarktl** [comment]
me too :-(

**Comment by darkdongdong** [comment]
same same

**Comment by mendesbarreto** [comment]
same here =(

**Comment by raxityo** [comment]
A suggestion:
Let's use 👍 reaction to the top comment instead of "Same Here".

**Comment by KrauseFx** [comment]
Thanks everyone, I can reproduce and work on a fix right now 👍

**Comment by drosenstark** [comment]
@KrauseFx was it a change on the ITC side? Thank you.

**Comment by KrauseFx** [comment]
Yes, there was a small change in how sessions are handled in iTunes Connect. The PR is live at https://github.com/fastlane/fastlane/pull/7311, preparing a new release right now 👍

**Comment by KrauseFx** [comment]
Thanks for the patience everyone, the new release is live with _spaceship_ `0.38.5`, please update to the latest version :rocket: 

To do so, either run `[sudo] gem update spaceship` or `bundle update` (if you use bundler), or `fastlane update_fastlane` 

Let us know if that works for you ✨

**Comment by kcinman11358** [comment]
Updated to spaceship 0.38.5 and it works great. Thank you so much @KrauseFx!!!

I was worried because no one else had opened the issue

**Comment by drosenstark** [comment]
@KrauseFx great, thanks! So when Apple changes the ITC API, they don't inform via email etc.?

**Comment by jonstjohn** [comment]
Incredibly quick fix here, appreciate the turn-around. Updating Spaceship works for me.

**Comment by prnewman** [comment]
@KrauseFx Appreciate the update, but still get error using pilot find:

```undefined method `length' for nil:NilClass```

**Comment by KrauseFx** [comment]
@prnewman This seems to be a different error message, please submit a separate issue for this
@drosenstark No, we don't get an email or heads-up when something changes, we just hear it from GitHub and Twitter usually. 

Thanks everyone for updating, glad this issue got resolved, I'll lock the conversation for now, so that we don't trigger more emails 👍  

If you still experience an issue, please submit a new issue for it
