### ISSUE TITLE
cert fails when output_path is different than `.`

### ISSUE THREAD

**Issue by nicolasbraun** [fastlane/fastlane#731]
When setting up the `output_path`parameter the cert command fails.
From what I could see the `.cer` file is stored in the root folder instead of chose one, thus the file is not found.

Extract from my Fastfile :
```
  cert(
    development: options[:development],
    output_path: "./fastlane/profiles"
    #team_id: "yourteamid" # Fails to work with team_id from AppFile https://github.com/KrauseFx/fastlane/issues/700
  ) 
````

Logs 

```
[17:41:17]: Starting login with user 'nicolas.braun@applidium.com'
[17:41:57]: Successfully logged in
[17:42:08]: Variable Dump:
[17:42:08]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"dev"}
[17:42:08]: No such file or directory @ rb_sysopen - ./fastlane/profiles/E9X8ZTAN62.cer
```

On disk :
![image](http://i.imgur.com/Hkmu49e.png)

**Comment by ohwutup** [comment]
Hey @nicolasbraun! Are you still running into this issue? Apologies for the long response time, but would you mind updating your tools and trying this again? Please reopen the issue if you're still having trouble. Thanks! :bear:

**Comment by nicolasbraun** [comment]
Hi @ohwutup 

From my last test on version 1.63.0 the `output_path`paramter is now ignored

Fastfile : 
````
  cert(
      development: development,
      username: ENV["APPLE_ID"],
      team_id: ENV["TEAM_ID"],
      output_path: "./test"
  ) 

`````

Console : 

```
INFO [2016-02-25 10:25:45.10]: ------------------
INFO [2016-02-25 10:25:45.10]: --- Step: cert ---
INFO [2016-02-25 10:25:45.10]: ------------------

+---------------+------------------------------------------------------+
|                        Summary for cert 1.3.0                        |
+---------------+------------------------------------------------------+
| development   | false                                                |
| force         | false                                                |
| username      | XXX@applidium.com                                |
| team_id       | XXX                                           |
| keychain_path | /Users/nicolasbraun/Library/Keychains/login.keychain |
+---------------+------------------------------------------------------+

```

**Comment by nicolasbraun** [comment]
PS : I cannot reopen the issue (http://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github)

**Comment by ohwutup** [comment]
hey @nicolasbraun, apologies that you couldn't reopen the issue... it does look like the `output_path` option is being used, but it is just not being printed out in the table as you can see here: https://github.com/fastlane/cert/blob/master/lib/cert/runner.rb#L18. 

is this not working for you? or were you just expecting to see the line printed in the table?

**Comment by nicolasbraun** [comment]
Oh you are right, my bad.
It is working. I believe this should be printed out :)

Thanks

**Comment by ohwutup** [comment]
Awesome! Glad it is working for you! If you would like to submit a PR with the change to keep it printing out, we would be happy to have some discussion about it over there! :rocket: :+1:
