### ISSUE TITLE
Move environment variable checking into fastlane_core

### ISSUE THREAD

**Issue by milch** [fastlane/fastlane#7326]
As discussed in https://github.com/fastlane/fastlane/pull/7064#issuecomment-264584574 - we should provide a method in fastlane_core to check if a boolean environment variable was set to a "falsy" value. Right now, we use many checks of the form 

```ruby
if ENV["MATCH_FORCE_ENTERPRISE"]
  # ... do work
end

# or

do_work("value) if ENV["MATCH_FORCE_ENTERPRISE"]
```

Users falsely assume that they can enable and disable boolean environment variables by setting them to truthy/falsy values (e.g. by putting `ENV["VAR"] = "0"` at the top of their Fastfile), which is not the case right now. An implementation of this could look like 

```ruby
if FastlaneCore::feature_enabled?("MATCH_FORCE_ENTERPRISE")
  # ... do work
end

# or even better, fancy dynamic method version

if FastlaneCore::env_match_force_enterprise?
  # ... do work
end
```

but I'm open to other ideas.

**Comment by KrauseFx** [comment]
How about prefixing it with a class? 

```
FastlaneCore::Env.enabled?("MATCH_FORCE")
```

I'd prefer not to have dynamic methods here, as it might not immediately be clear for contributors when looking at the code on where the value comes from

**Comment by milch** [comment]
> How about prefixing it with a class?

Sounds good to me! 

> I'd prefer not to have dynamic methods here, as it might not immediately be clear for contributors when looking at the code on where the value comes from

If it is implemented in the prefixed class, the implementation for the lookup will be in there.

**Comment by hjanuschka** [comment]
awesome! ok when i go for it? with @KrauseFx  suggestion ?
