### ISSUE TITLE
Use scan: file not found

### ISSUE THREAD

**Issue by shbIOS** [fastlane/fastlane#7329]
![5958167a-85a2-4324-8233-1688ebebffd1](https://cloud.
![1111](https://cloud.githubusercontent.com/assets/7531102/20910898/5f6e3dfc-bb9f-11e6-9edb-f8d40e45e71b.png)

### Issue Description
Excuse me
When I cd to my project dir, run 'scan',it takes error:'file not found',but It's build successed with Xcode 8.1 (My project contain TodayExtension) Tks.

**Comment by KrauseFx** [comment]
Did you specify the workspaces instead of the project file?

**Comment by shbIOS** [comment]
When I run 'scan' , shows:Select Scheme: (Use cocoaPods)

**Comment by shbIOS** [comment]
@KrauseFx  When I run 'scan' , shows:Select Scheme: (Use cocoaPods)
