### ISSUE TITLE
gym always fails with exit code 65 at CompileSwift normal

### ISSUE THREAD

**Issue by bb-git** [fastlane/fastlane#7332]
### Issue Description

my fastlane is not working anymore since upgrading to XCode 8.1. Gym always exits with error code 65. It always compiles all pods and then I get the error as stated below. I updated everything including ruby, reinstalled fastlane and of course restarted the machine several times. Any help appreciated.

##### Output

```
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling Pods-arise2-dummy.m
▸ Compiling Pods_arise2_vers.c
▸ Compiling Pods-arise2-dummy.m
▸ Compiling Pods_arise2_vers.c
▸ Copying Pods-arise2-umbrella.h
▸ Touching Pods_arise2.framework
▸ Building arise2/arise2 [Release]
▸ Check Dependencies
▸ Running script '[CP] Check Pods Manifest.lock'

** ARCHIVE FAILED **


The following build commands failed:
CompileSwift normal arm64
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
ERROR [2016-12-06 13:09:18.26]: Exit status: 65
WARN [2016-12-06 13:09:18.27]: 📋  For a more detailed error log, check the full log at:
WARN [2016-12-06 13:09:18.27]: 📋  /Users/metatron/Library/Logs/gym/arise2-arise2.log
ERROR [2016-12-06 13:09:18.33]: Found multiple versions of Xcode in '/Applications/'
ERROR [2016-12-06 13:09:18.33]: Make sure you selected the right version for your project
ERROR [2016-12-06 13:09:18.33]: This build process was executed using '/Applications/Xcode.app'
WARN [2016-12-06 13:09:18.33]: If you want to update your Xcode path, either
INFO [2016-12-06 13:09:18.33]: 
INFO [2016-12-06 13:09:18.33]: - Specify the Xcode version in your Fastfile
INFO [2016-12-06 13:09:18.33]: ▸ xcversion(version: "8.1") # Selects Xcode 8.1.0
INFO [2016-12-06 13:09:18.33]: 
INFO [2016-12-06 13:09:18.33]: - Specify an absolute path to your Xcode installation in your Fastfile
INFO [2016-12-06 13:09:18.33]: ▸ xcode_select "/Applications/Xcode8.app"
INFO [2016-12-06 13:09:18.33]: 
INFO [2016-12-06 13:09:18.33]: - Manually update the path using
INFO [2016-12-06 13:09:18.34]: ▸ sudo xcode-select -s /Applications/Xcode.app
INFO [2016-12-06 13:09:18.34]: 

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 1.12.1                  |
| sdk         | iPhoneOS10.1.sdk        |
+-------------+-------------------------+


```
### Environment

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.66.0"
#xcversion(version: "8.1")

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end


  desc "Deploy a new version to the App Store"
  lane :appstore do
    #match(type: "appstore")
    increment_build_number
    cert
    sigh
    gym(scheme: "arise2",clean: true) # Build your app - more options available
    deliver(force: true, skip_screenshots: true)
    #deliver(force: true, skip_metadata: true, skip_screenshots: true)
    #deliver(force:true)
  end




  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "removed" # The bundle identifier of your app
apple_id "removed" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.38.5  | ✅ Up-To-Date  |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date  |
| deliver             | 1.16.1  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.58.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-12-06**
</details>

```

**Comment by bb-git** [comment]
My fault, there was an error in my code.

**Comment by gauravChaturvedi** [comment]
@bb-git what was the error in your code ? I'm facing the exact same issue

**Comment by bb-git** [comment]
Try to clean your build and also your build folder, then it should also not compile any more, when you build for your device or simulator. Xcode will then show you, the error.

**Comment by gauravChaturvedi** [comment]
Okay.. @bb-git what did you change in your code to fix this
