### ISSUE TITLE
Is there any way to reorder screenshorts with deliver command

### ISSUE THREAD

**Issue by akkhilns** [fastlane/fastlane#7338]
Hi,
Please tell me is there any way to reorder screenshots with the deliver command.

**Comment by hjanuschka** [comment]
@akkhilns can you try renaming your screenshots in an alphabetic order?
let me know if this helps.

**Comment by akkhilns** [comment]
i renamed screenshots in alphabetic order. it worked. thanks @hjanuschka

**Comment by hjanuschka** [comment]
awesome @akkhilns - can you please close the issue
