### ISSUE TITLE
[frameit] Want same font size for all shots

### ISSUE THREAD

**Issue by futuretap** [fastlane/fastlane#7345]
Currently, the font size of the two labels is determined according to the available space. This leads to vastly varying font sizes if the length of the labels differ.

In my [pull request](https://github.com/fastlane/fastlane/pull/7334) I introduce a `font_scale_factor` parameter that sets the font size as a fraction of the screen width. For instance, a factor of `0.06` results in a font size of `38.4` for a 640*1172 shot.

**Comment by mpirri** [comment]
PR merged; issue fixed on `master`.
