### ISSUE TITLE
[frameit] offset is changing from shot to shot

### ISSUE THREAD

**Issue by futuretap** [fastlane/fastlane#7347]
If `offsets.json` specifies a width smaller than the screenshot width, the applied offset varies from shot to shot. The first shot is positioned correctly but the following shots are positioned increasingly off.

The bug only occurs for device artwork whose screenshot placeholder is smaller than the screenshot. This is the case for Apple's device frames - [Facebook's device frames](http://facebook.design/devices) are fine. Since Facebook doesn't provide a 3.5" device frame, I have to resort to Apple's artwork for that.

Fixed in this [pull request](https://github.com/fastlane/fastlane/pull/7334).

**Comment by mpirri** [comment]
PR merged; issue fixed on `master`.
