### ISSUE TITLE
deliver fails on 2FA

### ISSUE THREAD

**Issue by SuperTango** [fastlane/fastlane#7353]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running a build in CircleCI, trying to push to the Apple App Store with deliver.  I have had this build working for a while, but just turned on Apple 2 factor authentication. Originally, sigh was failing, so I performed the steps in https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification, and sigh started working without issue. However, further along in the build, deliver is failing with this:

```
+-----------------------+--------------------------------------------+
|                       deliver 1.16.1 Summary                       |
+-----------------------+--------------------------------------------+
| skip_screenshots      | true                                       |
| skip_metadata         | true                                       |
| team_id               | 117267682                                  |
| app_identifier        | com.xxxxxxx.ios                     |
| username              | XXXXXXXXXXXXX                     |
| ipa                   | /Users/distiller/xxxxxx/XXXXX.ipa |
| screenshots_path      | ./fastlane/screenshots                     |
| metadata_path         | ./fastlane/metadata                        |
| app_version           | 1.11                                       |
| platform              | ios                                        |
| skip_binary_upload    | false                                      |
| force                 | false                                      |
| submit_for_review     | false                                      |
| automatic_release     | false                                      |
| dev_portal_team_id    | XXXXXXX                                 |
| overwrite_screenshots | false                                      |
+-----------------------+--------------------------------------------+

[13:05:36]: Making sure the latest version on iTunes Connect matches '1.11' from the ipa file...
[13:05:39]: '1.11' is the latest version on iTunes Connect
[13:05:43]: Uploading binary to iTunes Connect
[13:05:43]: Going to upload updated app to iTunes Connect
[13:05:43]: This might take a few minutes. Please don't interrupt the script.

[13:07:17]: Transporter transfer failed.
[13:07:17]: 

[13:07:17]: Application specific password seems wrong
[13:07:17]: Please make sure to follow the instructions
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[13:07:17]: Your account has 2 step verification enabled
[13:07:17]: Please go to https://appleid.apple.com/account/manage
[13:07:17]: and generate an application specific password for
[13:07:17]: the iTunes Transporter, which is used to upload builds
[13:07:17]: Going to upload updated app to iTunes Connect
[13:07:17]: This might take a few minutes. Please don't interrupt the script.

[13:07:22]: Transporter transfer failed.
[13:07:22]: 

[13:07:22]: Application specific password seems wrong
[13:07:22]: Please make sure to follow the instructions
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[13:07:22]: Your account has 2 step verification enabled
[13:07:22]: Please go to https://appleid.apple.com/account/manage
[13:07:22]: and generate an application specific password for
[13:07:22]: the iTunes Transporter, which is used to upload builds
[13:07:22]: Going to upload updated app to iTunes Connect
[13:07:22]: This might take a few minutes. Please don't interrupt the script.

[13:07:27]: Transporter transfer failed.
```

What can I do to fix deliver failing?

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[14:27:40]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.11.6                                         |
| Ruby                | 2.2.5                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.2                              |
| Installation Source | /opt/rubies/ruby-2.2.5/bin/fastlane             |
| Host                | Mac OS X 10.11.6 (15G1108)                      |
| Ruby Lib Dir        | /opt/rubies/ruby-2.2.5/lib                      |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode-8.1.app/Contents/Developer/ |
| Xcode Version       | 8.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.0"

default_platform :ios


def import_certificates
  return unless Helper.is_ci? # As in my local machine I don't need to import the certificates, only run if it's in the CI

  create_keychain(
      name: ENV["KEYCHAIN_NAME"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      # lock_when_sleeps: true,
      password: ENV["KEYCHAIN_PASSWORD"]
  )

  import_certificate(
      certificate_path: "fastlane/certificates/tango-distribution.p12",
      certificate_password: ENV['PKCS12_FILE_PASSWORD'],
      keychain_name: ENV["KEYCHAIN_NAME"],
      log_output: true
  )
end

platform :ios do
  before_all do
    cocoapods
    ENV['KEYCHAIN_NAME'] = "TempKeychain.keychain"
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to HockeyApp"
  desc "This will also make sure the profile is up to date"
  lane :ci do
    # match(type: "appstore") # more information: https://codesigning.guide
    if Helper.is_ci?
      import_certificates
      sigh(
          adhoc: true
      )
    end
    gym(
        scheme: "CI_Build",
        export_method: "ad-hoc",
        use_legacy_build_api: true,
    )
    hockey(
        api_token: ENV['HOCKEYAPP_TOKEN'],
        commit_sha: ENV['CIRCLE_SHA1'],
        build_server_url: ENV['CIRCLE_BUILD_URL'],
        repository_url: ENV['CIRCLE_REPOSITORY_URL'],
        public_identifier: ENV['HOCKEYAPP_BETA_ID'],
        teams: ENV['HOCKEY_TEAMS'],
        notes: File.open('/tmp/relnotes.md').read,
        notes_type: '1'
    )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    if Helper.is_ci?
      import_certificates
      sigh(
          adhoc: false
      )
    end

    gym(scheme: "Production_Release") # Build your app - more options available
    deliver(
        skip_screenshots: true,
        skip_metadata: true,
        team_id: '117267682')
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxxxx.music.ios" # The bundle identifier of your app
apple_id "xxxx@xxxxx.com" # Your Apple email address

team_id "xxxxxxx"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.38.5  | ✅ Up-To-Date        |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date        |
| deliver             | 1.16.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | 🚫 Update availaible |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.12.1  | ✅ Up-To-Date        |
| produce             | 1.3.2   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | 🚫 Update availaible |
| screengrab          | 0.5.6   | ✅ Up-To-Date        |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.1        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.58.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.7.1      |
| plist                     | 3.2.0        |
</details>

*generated on:* **2016-12-06**

**Comment by KrauseFx** [comment]
Could you try with the most recent release? We've pushed some fixes around 2 factor 👍

**Comment by SuperTango** [comment]
OK. I ended up turning off 2FA, but I'll re-enable it to see if I can get it to work.  It may be a couple of days before I get to it as we're not ready to do another appstore build yet.

**Comment by KrauseFx** [comment]
Cool, thanks 👍 Let us know how it goes
