### ISSUE TITLE
Fastlane error: "You must detail what's new in this version" #deliver

### ISSUE THREAD

**Issue by MartinPrz** [fastlane/fastlane#7354]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

ERROR:

[!] The request could not be completed because:
	[es-MX]: You must detail what's new in this version in Spanish (Mexico).

notes = ({'default' => "Mejoras de performance."})
lane :beta do

	gym(
		scheme: ”Wasabi”,
		configuration: "Release”,
		include_bitcode: true,
		silent: true
	)

	deliver(
		
		force: true,
		submit_for_review: true,
		automatic_release: true,
		release_notes: notes,
		app_review_information: notes,
		release_notes: notes
	)

**Comment by hjanuschka** [comment]
can you try it with:

```ruby
notes = ({'default' => "Mejoras de performance.", "es-MX"=>"Mejoras de performance."})
```

do you have multiple languages enabled?
