### ISSUE TITLE
[fastlane] Emoji in file names cause issues for TeamCity (💪, 🚀)

### ISSUE THREAD

**Issue by mgrebenets** [fastlane/fastlane#7355]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We have to update Ruby gems via Artifactory rubygems.org mirror. Company proxy is (to put it politely) unreliable and causes `bundle install/update` command to fail quite often. So we decided to bundle all the gems with the repo using `bundle install --path .vendor` command.

Committing `.vendor` and `.bundle` directories to git caused no issues. Bitbucket server worked fine. However, TeamCity (9.1) couldn't fetch change information from Bitbucket and the error was SQL error like so:

```
SQL exception: Incorrect string value: '\xF0\x9F\x92\xAA' for column 'vcs_file_name' at row 1
```

The `'\xF0\x9F\x92\xAA'` is actually 💪 emoji. So TeamCity's SQL database can't properly handle correct UTF-8 sequences for emojis. I'm pretty sure our TeamCity instance is running on Windows platform, which may have additional contribution to the issue.

I know that this is definitely TeamCity issue, but I would still like to get some input from Fastlane community.

Should I manually (or with help of a script) remove all filenames containing emoji from `.vendor` path?
Is it possible to make emoji aliases optional and not installed by default? Or have a switch to opt out from installing them.
Maybe there's some `budnler` trick that can automate this task for me...

Related PR: https://github.com/fastlane/fastlane/pull/4436

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.2                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rvm/gems/ruby-2.2.2/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.2/lib                |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  # Redacted
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "au.com.commbank.app.tools" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date  |
| spaceship           | 0.38.5  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.16.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| rake                      | 0.9.6        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| multi_json                | 1.12.1       |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| terminal-table            | 1.4.5        |
| fastlane_core             | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| multi_xml                 | 0.6.0        |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| colorize                  | 0.7.7        |
| mini_magick               | 4.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| terminal-notifier         | 1.7.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.3.0        |
| commbank-app-tools        | 0.21.1       |
</details>

*generated on:* **2016-12-07**
</details>

**Comment by KrauseFx** [comment]
Argh, this is not good. Emoji names are just fun, and shouldn't cause an actual build error. However we can't just remove the emoji binary now, as people already use the emoji binaries. It's probably best if you remove those binaries before using your own script. Feel free to share it here, so that other users benefit from it 👍

**Comment by mgrebenets** [comment]
I see. I've found an answer here: http://unix.stackexchange.com/questions/109747/identify-files-with-non-ascii-or-non-printable-characters-in-file-name

This simple command finds them all: `LC_ALL=C find .vendor -name '*[! -~]*'`

```
~ git:(branch) ✗ LC_ALL=C find .vendor -name '*[! -~]*'
.vendor/ruby/2.2.0/bin/💪
.vendor/ruby/2.2.0/bin/🚀
.vendor/ruby/2.2.0/gems/fastlane-1.111.0/bin/🚀
.vendor/ruby/2.2.0/gems/gym-1.12.1/bin/💪
```

So using `-delete` does the job: `LC_ALL=C find .vendor -name '*[! -~]*' -delete`.

I guess I will just use this bash command in our tools to "sanitize" bundle directory from emojis. Can also stick it in git commit hooks.

I'll close the issue as well. Thanks for your help! 👍

**Comment by wilrnh** [comment]
How does someone actually use emoji binaries?

**Comment by KrauseFx** [comment]
Check this out: https://twitter.com/KrauseFx/status/727887795734380545

**Comment by wilrnh** [comment]
sry i still dont think I get it 🐳  so they cmd $emoji[rocket] using the emoji zsh plugin?

**Comment by wilrnh** [comment]
if anyone else was curious:

on macs you can hit Ctrl + Cmd + Space to open a "character viewer" https://support.apple.com/en-us/HT201586
