### ISSUE TITLE
deliver fails with: [!] undefined method `description' for nil:NilClass  

### ISSUE THREAD

**Issue by Tibbs** [fastlane/fastlane#7356]
When I run "deliver --skip_screenshots" it fails with the following error:

```
/Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/upload_metadata.rb:40:in `block (2 levels) in upload': [!] undefined method `description' for nil:NilClass (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/upload_metadata.rb:37:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/upload_metadata.rb:37:in `block in upload'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/upload_metadata.rb:28:in `each'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/upload_metadata.rb:28:in `upload'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/runner.rb:59:in `upload_metadata'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/runner.rb:21:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/commands_generator.rb:63:in `block (2 levels) in run'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/fastlane_core-0.58.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/commands_generator.rb:149:in `run'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/user/.rvm/gems/ruby-2.3.0@global/gems/deliver-1.16.1/bin/deliver:5:in `<top (required)>'
	from /Users/user/.rvm/rubies/ruby-2.3.0/bin/deliver:23:in `load'
	from /Users/user/.rvm/rubies/ruby-2.3.0/bin/deliver:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/user/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

```
### Environment

`<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| did_you_mean              | 1.0.0       |
| executable-hooks          | 1.3.2       |
| bundler-unload            | 1.0.2       |
| rubygems-bundler          | 1.4.4       |
| bundler                   | 1.13.6      |
| io-console                | 0.4.5       |
| highline                  | 1.7.8       |
| terminal-table            | 1.4.5       |
| json                      | 1.8.3       |
| multipart-post            | 2.0.0       |
| faraday                   | 0.9.2       |
| faraday_middleware        | 0.10.0      |
| dotenv                    | 2.0.2       |
| net-ssh                   | 3.0.2       |
| net-sftp                  | 2.1.2       |
| plist                     | 3.1.0       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| krausefx-shenzhen         | 0.14.11     |
| slack-notifier            | 1.5.1       |
| rouge                     | 1.10.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.6.3       |
| xcode-install             | 2.0.7       |
| word_wrap                 | 1.0.0       |
| colored                   | 1.2         |
| credentials_manager       | 0.16.2      |
| fastimage                 | 1.6.8       |
| mini_magick               | 4.5.1       |
| xcpretty-travis-formatter | 0.0.4       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| multi_json                | 1.11.2      |
| logging                   | 2.0.0       |
| jwt                       | 1.5.2       |
| memoist                   | 0.14.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.2       |
| googleauth                | 0.5.1       |
| httpclient                | 2.8.2.4     |
| google-api-client         | 0.9.19      |
| i18n                      | 0.7.0       |
| thread_safe               | 0.3.5       |
| tzinfo                    | 1.2.2       |
| minitest                  | 5.8.3       |
| activesupport             | 4.2.5       |
| commander                 | 4.4.0       |
| excon                     | 0.45.4      |
| gh_inspector              | 1.0.2       |
| fastlane_core             | 0.58.0      |
| CFPropertyList            | 2.3.3       |
| claide                    | 1.0.1       |
| nanaimo                   | 0.1.2       |
| xcodeproj                 | 1.4.0       |
</details>

*generated on:* **2016-12-07**
</details>`

I failed with the same error on two different Macs

**Comment by hjanuschka** [comment]
thats strange.

can you share the output of:

`ls -lR fastlane/metadata`

are you working on a mac or ios app?

**Comment by Tibbs** [comment]
This is for a macOS app. I also tried to initialize it from iTunes Connect and upload directly the downloaded data. 

I use deliver directly and the output is:

-rw-r--r--@ 1 user  staff   12 Dec  7 11:13 copyright.txt
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 de-DE
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 en-AU
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 en-CA
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 en-GB
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 en-US
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 es-ES
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 es-MX
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 fr-CA
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 fr-FR
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 it
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 ja
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 nl-NL
-rw-r--r--@ 1 user  staff   31 Dec  7 11:13 primary_category.txt
-rw-r--r--@ 1 user  staff    1 Dec  7 11:13 primary_first_sub_category.txt
-rw-r--r--@ 1 user  staff    1 Dec  7 11:13 primary_second_sub_category.txt
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 pt-PT
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 ru
-rw-r--r--@ 1 user  staff   27 Dec  7 11:13 secondary_category.txt
-rw-r--r--@ 1 user  staff    1 Dec  7 11:13 secondary_first_sub_category.txt
-rw-r--r--@ 1 user  staff    1 Dec  7 11:13 secondary_second_sub_category.txt
drwxr-xr-x@ 9 user  staff  306 Dec  7 11:13 zh-Hans

metadata/de-DE:
total 56
-rw-r--r--@ 1 user  staff  1685 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff    88 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    51 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    33 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/en-AU:
total 56
-rw-r--r--@ 1 user  staff  1347 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff    99 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    49 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    27 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/en-CA:
total 56
-rw-r--r--@ 1 user  staff  1347 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff    98 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    49 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    27 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/en-GB:
total 56
-rw-r--r--@ 1 user  staff  1345 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff    99 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    49 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    27 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/en-US:
total 56
-rw-r--r--@ 1 user  staff  1347 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   101 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    49 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    27 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/es-ES:
total 56
-rw-r--r--@ 1 user  staff  1638 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   104 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    47 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    32 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/es-MX:
total 56
-rw-r--r--@ 1 user  staff  1638 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   104 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    47 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    32 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/fr-CA:
total 56
-rw-r--r--@ 1 user  staff  1659 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   106 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    56 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    33 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/fr-FR:
total 56
-rw-r--r--@ 1 user  staff  1656 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   106 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    56 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    33 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/it:
total 56
-rw-r--r--@ 1 user  staff  1528 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff    98 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    43 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    30 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/ja:
total 56
-rw-r--r--@ 1 user  staff  1745 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   243 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    85 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    27 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/nl-NL:
total 56
-rw-r--r--@ 1 user  staff  1496 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff    98 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    49 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/pt-PT:
total 56
-rw-r--r--@ 1 user  staff  1347 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   101 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    49 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    27 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/ru:
total 56
-rw-r--r--@ 1 user  staff  1347 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   101 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    49 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    27 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

metadata/zh-Hans:
total 56
-rw-r--r--@ 1 user  staff  1344 Dec  7 11:13 description.txt
-rw-r--r--@ 1 user  staff   196 Dec  7 11:13 keywords.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 marketing_url.txt
-rw-r--r--@ 1 user  staff    44 Dec  7 11:13 name.txt
-rw-r--r--@ 1 user  staff     1 Dec  7 11:13 privacy_url.txt
-rw-r--r--@ 1 user  staff    24 Dec  7 11:13 release_notes.txt
-rw-r--r--@ 1 user  staff    31 Dec  7 11:13 support_url.txt

**Comment by hjanuschka** [comment]
@Tibbs i think this is a bug with the mac platform. see #7360 should fix it.
you need to specify `-j osx`  at the end of deliver command, maybe you can try if this fixes your issues, if not maybe you can try the PR?

**Comment by Tibbs** [comment]
@hjanuschka `-j osx` worked! I wasn't aware of this switch.  Thank you very much for the solution!

**Comment by hjanuschka** [comment]
@Tibbs  awesome - can you close the issue?
