### ISSUE TITLE
Unable to activate spaceship-0.38.5, because fastimage-2.0.1 conflicts with fastimage (~> 1.6)

### ISSUE THREAD

**Issue by vegidio** [fastlane/fastlane#7362]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I try to use `deliver` I get the error message below:

I know that if I run `gem uninstall fastimage -v 2.0.1` deliver works again, but shouldn't it run with the latest version of `fastimage`?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
/usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2285:in `raise_if_conflicts': Unable to activate spaceship-0.38.5, because fastimage-2.0.1 conflicts with fastimage (~> 1.6) (Gem::ConflictError)
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems.rb:196:in `rescue in try_activate'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems.rb:193:in `try_activate'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:125:in `rescue in require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.16.1/lib/deliver.rb:17:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/deliver-1.16.1/bin/deliver:4:in `<top (required)>'
	from /usr/local/bin/deliver:22:in `load'
	from /usr/local/bin/deliver:22:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.0                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                   | Version |
| --------------------- | ------- |
| did_you_mean          | 1.0.2   |
| multi_json            | 1.12.1  |
| highline              | 1.7.8   |
| colored               | 1.2     |
| commander             | 4.4.1   |
| excon                 | 0.54.0  |
| rubyzip               | 1.1.7   |
| plist                 | 3.2.0   |
| gh_inspector          | 1.0.2   |
| security              | 0.1.3   |
| credentials_manager   | 0.16.2  |
| fastlane_core         | 0.58.0  |
| json                  | 2.0.2   |
| io-console            | 0.4.6   |
| CFPropertyList        | 2.3.4   |
| claide                | 1.0.1   |
| nanaimo               | 0.2.3   |
| xcodeproj             | 1.4.1   |
| bundler               | 1.13.6  |
| word_wrap             | 1.0.0   |
| unicode-display_width | 1.1.1   |
| terminal-table        | 1.7.3   |
</details>

*generated on:* **2016-12-07**
</details>

**Comment by milch** [comment]
Hi @vegidio,

It seems like you are right, the only breaking change I found with fastimage 2.0 is that it only supports ruby >= 2.0 - which is what we support anyway. I'll close this issue and open a separate issue to track upgrading fastimage. 

In general, the error you are getting results from running gem update and can be fixed by either running fastlane using bundler, or installing fastlane through brew using `brew cask install fastlane`.
