### ISSUE TITLE
deliver doesn't download iMessage screenshots into `iMessage` subdirectory

### ISSUE THREAD

**Issue by hborders** [fastlane/fastlane#7366]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I just ran `deliver download_screenshots`, and it dutifully downloaded all my app's screenshots. However, it didn't put iMessage screenshots into the `./screenshots/iMessage` directory [as is required for iMessage screenshot uploading](https://github.com/fastlane/fastlane/pull/6830). Instead all of my screenshots are mixed together in their respective localization folders.

**Comment by hborders** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.8.3                                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1108)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode-8.1.app/Contents/Developer/                |
| Xcode Version       | 8.1                                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.38.5  | ✅ Up-To-Date        |
| fastlane_core       | 0.58.0  | ✅ Up-To-Date        |
| deliver             | 1.16.1  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | 🚫 Update availaible |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.1   | 🚫 Update availaible |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | 🚫 Update availaible |
| screengrab          | 0.5.2   | 🚫 Update availaible |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| highline                  | 1.7.8       |
| commander                 | 4.4.0       |
| terminal-table            | 1.4.5       |
| json                      | 1.8.3       |
| multipart-post            | 2.0.0       |
| faraday                   | 0.9.2       |
| faraday_middleware        | 0.10.0      |
| dotenv                    | 2.0.2       |
| net-ssh                   | 3.0.2       |
| net-sftp                  | 2.1.2       |
| plist                     | 3.1.0       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| krausefx-shenzhen         | 0.14.11     |
| slack-notifier            | 1.5.1       |
| i18n                      | 0.7.0       |
| thread_safe               | 0.3.5       |
| tzinfo                    | 1.2.2       |
| minitest                  | 5.9.0       |
| activesupport             | 4.2.7.1     |
| colored                   | 1.2         |
| claide                    | 1.0.1       |
| xcodeproj                 | 1.3.3       |
| rouge                     | 1.10.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.6.3       |
| addressable               | 2.4.0       |
| credentials_manager       | 0.16.2      |
| multi_xml                 | 0.5.5       |
| unf_ext                   | 0.0.7.1     |
| unf                       | 0.1.4       |
| domain_name               | 0.5.25      |
| http-cookie               | 1.0.2       |
| faraday-cookie_jar        | 0.0.6       |
| fastimage                 | 1.6.8       |
| babosa                    | 1.0.2       |
| xcode-install             | 2.0.2       |
| word_wrap                 | 1.0.0       |
| multi_json                | 1.11.2      |
| excon                     | 0.45.4      |
| gh_inspector              | 1.0.2       |
| fastlane_core             | 0.58.0      |
| bundler                   | 1.12.5      |
| mini_magick               | 4.5.1       |
| xcpretty-travis-formatter | 0.0.4       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0221 |
| mime-types                | 3.0         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| logging                   | 2.0.0       |
| jwt                       | 1.5.2       |
| memoist                   | 0.14.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.2       |
| googleauth                | 0.5.1       |
| thor                      | 0.19.1      |
| httpclient                | 2.7.1       |
| google-api-client         | 0.9.3       |
</details>


*generated on:* **2016-12-07**
</details>

**Comment by milch** [comment]
Thanks for the report, good catch!

**Comment by hjanuschka** [comment]
see PR's  here: 
  * 1/2 -> https://github.com/fastlane/fastlane/pull/7399 (spaceship)
  * 2/2 -> https://github.com/fastlane/fastlane/pull/7400 (deliver)
