### ISSUE TITLE
Update fastimage dependency

### ISSUE THREAD

**Issue by milch** [fastlane/fastlane#7370]
See: #7362 

I looked at the fastimage gem, and it looks like the only breaking change from version 1 to 2 was dropping ruby 1.x support. As we don't support ruby 1.x anyway, we should upgrade fastimage as well. 

You can find the fastimage repo here: https://github.com/sdsykes/fastimage

**Comment by hjanuschka** [comment]
see PR series: 

# Full Branch:
  * https://github.com/hjanuschka/fastlane/tree/fastimage_gemspec

# PR's
  * 1/4 -> https://github.com/fastlane/fastlane/pull/7401 (spaceship)
  * 2/4 -> https://github.com/fastlane/fastlane/pull/7402 (deliver)  
  * 3/4 -> https://github.com/fastlane/fastlane/pull/7403 (frameit)
  * 4/4 -> https://github.com/fastlane/fastlane/pull/7404(snapshot)
