### ISSUE TITLE
Bug: other_action.rb doesn't respect ".fastlane" folder

### ISSUE THREAD

**Issue by puttin** [fastlane/fastlane#7373]
see this line https://github.com/fastlane/fastlane/blob/8370c81544a9b30239c9b686732fc23237d707d8/fastlane/lib/fastlane/other_action.rb#L24

also check this line if anyone want more detail
https://github.com/fastlane/fastlane/blob/8370c81544a9b30239c9b686732fc23237d707d8/fastlane/lib/fastlane/runner.rb#L199

update:
use latest commit for long term issue persistence

**Comment by puttin** [comment]
hey dear @fastlane-bot,

you can check [current code](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/other_action.rb#L24).

It seems that it's not resolved.

---

And for anyone curious about how I solve the problem.

I wrote a custom action in our project that run at the very beginning of fastlane. That action saves the SRC_ROOT and fastlane folder absolute path. So all my other custom action can rely on them.

It would be nice that fastlane can record fastlane folder and source folder in fastlane context so that anyone can benefit from this.

**Comment by puttin** [comment]
It seems that problem has been fixed. I will close this issue.

**Comment by KrauseFx** [comment]
Glad to hear, and sorry for not responding back earlier 👍
