### ISSUE TITLE
Wrong Provisioning Profile Used in Enterprise Builds

### ISSUE THREAD

**Issue by zhunt11** [fastlane/fastlane#7382]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have an app with multiple targets. Each target represents a different customer. Some customers have a regular developer account, other have both a regular developer account and an enterprise account.

I have a lane that uses cert, sigh and gym. The lane must be able to build for Enterprise and Non-Enterprise accounts. During Sigh, we set adhoc: false if there is an Enterprise account. Also, export_method is set to "enterprise", though this doesn't matter because we set use_legacy_build_api: true.

Gym completes successfully, however, the .ipa file that is produced cannot be installed on all devices. If I take a look into the contents of the .ipa file and look at the embedded.mobileprovision file, I see that ProvisionedDevices is being set with a list of devices.

It is important to note that this list of provisioned devices exists in the customers non-enterprise account. It is also important to note, when Fastlane downloads and stores the Provisioning Profile, that file contains ProvisionsAllDevices set to true.

It appears that Fastlane is working properly in regards to getting the correct certs and profiles, however, when the .ipa file is exported it is not using the provisioning profile for the enterprise account.

**How can I get builds for an Enterprise account to use the correct provisioning profile and set the ProvisionsAllDevices to true?**

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

client_name is a replacement for the name of the client. It is not an environment variable. Just a replace I did for the sake of anonymity. Same with the ***** on the username.

```
$ fastlane build_production --env client_name output_directory:/Users/zhunt/Desktop/
[12:41:15]: ---------------------------
[12:41:15]: --- Step: opt_out_usage ---
[12:41:15]: ---------------------------
[12:41:15]: Disabled upload of used actions
[12:41:15]: -------------------------------------------------
[12:41:15]: --- Step: Verifying required fastlane version ---
[12:41:15]: -------------------------------------------------
[12:41:15]: Your fastlane version 1.111.0 matches the minimum requirement of 1.29.2  ✅
[12:41:15]: ------------------------------
[12:41:15]: --- Step: default_platform ---
[12:41:15]: ------------------------------
[12:41:15]: Loading from './.env.client_name'
[12:41:15]: Driving the lane 'ios build_production' 🚀
[12:41:15]: --------------------------
[12:41:15]: --- Step: xcode_select ---
[12:41:15]: --------------------------
[12:41:15]: Setting Xcode version to /Applications/Xcode.app for all build steps
[12:41:15]: ------------------
[12:41:15]: --- Step: cert ---
[12:41:15]: ------------------

+---------------+-----------------------------------------------+
|                    Summary for cert 1.4.4                     |
+---------------+-----------------------------------------------+
| development   | false                                         |
| force         | false                                         |
| username      | *****                            |
| keychain_path | /Users/zhunt/Library/Keychains/login.keychain |
+---------------+-----------------------------------------------+

[12:41:16]: Starting login with user '*****'
[12:41:18]: Successfully logged in
[12:41:19]: Found the certificate 6AJ7SRQJ29 (client_name) which is installed on the local machine. Using this one.
[12:41:19]: Verifying the certificate is properly installed locally...
[12:41:19]: Successfully installed certificate 6AJ7SRQJ29
[12:41:19]: Use signing certificate '6AJ7SRQJ29' from now on!
[12:41:19]: ------------------
[12:41:19]: --- Step: sigh ---
[12:41:19]: ------------------

+-------------------------------------+--------------------------------------------------+
|                                Summary for sigh 1.12.1                                 |
+-------------------------------------+--------------------------------------------------+
| adhoc                               | false                                            |
| force                               | true                                             |
| development                         | false                                            |
| skip_install                        | false                                            |
| app_identifier                      | us.client_name.enterprise.MobileBanking.ProductionTest |
| username                            | *****                               |
| ignore_profiles_with_different_name | false                                            |
| cert_id                             | 6AJ7SRQJ29                                       |
| skip_fetch_profiles                 | false                                            |
| skip_certificate_verification       | false                                            |
+-------------------------------------+--------------------------------------------------+

[12:41:19]: Starting login with user '*****'
[12:41:21]: Successfully logged in
[12:41:21]: Fetching profiles...
[12:41:22]: Found 1 matching profile(s)
[12:41:22]: Updating the provisioning profile
[12:41:22]: Downloading provisioning profile...
[12:41:23]: Successfully downloaded provisioning profile...
[12:41:23]: Installing provisioning profile...
/Volumes/tfs/PSITP/Releases/HBP_2016.2.HotFix/src/OLBMobile/MobileBanking/iOS/fastlane/artifacts/InHouse_us.client_name.enterprise.MobileBanking.ProductionTest.mobileprovision
[12:41:23]: Setting Provisioning Profile type to 'enterprise'
[12:41:23]: -----------------
[12:41:23]: --- Step: gym ---
[12:41:23]: -----------------
[12:41:23]: Using legacy build system - waiting for radar to be fixed: https://openradar.appspot.com/radar?id=4952000420642816
[12:41:23]: Installing provisioning profile...
[12:41:23]: $ xcodebuild -list -workspace ./ConnectMobile.xcworkspace -configuration Production\ Test
[12:41:26]: $ xcodebuild clean -showBuildSettings -workspace ./ConnectMobile.xcworkspace -scheme client_name -configuration Production\ Test

+---------------------------+----------------------------------------------------------------------+
|                                      Summary for gym 1.12.1                                      |
+---------------------------+----------------------------------------------------------------------+
| clean                     | true                                                                 |
| configuration             | Production Test                                                      |
| export_method             | enterprise                                                           |
| output_directory          | /Users/zhunt/Desktop/                                                |
| output_name               | client_name-1.16207.41-production                                       |
| scheme                    | client_name                                                                |
| use_legacy_build_api      | true                                                                 |
| provisioning_profile_path | /Volumes/tfs/PSITP/Releases/HBP_2016.2.HotFix/src/OLBMobile/Mobil... |
| workspace                 | ./ConnectMobile.xcworkspace                                          |
| destination               | generic/platform=iOS                                                 |
| silent                    | false                                                                |
| buildlog_path             | ~/Library/Logs/gym                                                   |
| xcode_path                | /Applications/Xcode.app                                              |
+---------------------------+----------------------------------------------------------------------+

[12:41:28]: $ set -o pipefail && xcodebuild -workspace ./ConnectMobile.xcworkspace -scheme client_name -configuration Production\ Test -destination 'generic/platform=iOS' -archivePath /Users/zhunt/Library/Developer/Xcode/Archives/2016-12-08/client_name-1.16207.41-production\ 2016-12-08\ 12.41.28.xcarchive clean archive | tee /Users/zhunt/Library/Logs/gym/Production-client_name.log | xcpretty

** I REMOVED FOR BREVITY. COMPLIES ALL FILES AND SIGNS SOME EMBEDDED FRAMEWORKS **

[12:42:59]: ▸ Touching Production.app
[12:42:59]: ▸ Signing /Users/zhunt/Library/Developer/Xcode/DerivedData/ConnectMobile-frazytmzpdqcvsawoashlcoanmti/Build/Intermediates/ArchiveIntermediates/client_name/InstallationBuildProductsLocation/Applications/Production.app
[12:43:01]: ▸ Touching Production.app.dSYM
[12:43:01]: ▸ Archive Succeeded
[12:43:02]: Legacy build api is enabled, the `export_method` value will be ignored
[12:43:02]: $ /usr/bin/xcrun /tmp/PackageApplication4Gym -v /Users/zhunt/Library/Developer/Xcode/Archives/2016-12-08/client_name-1.16207.41-production\ 2016-12-08\ 12.41.28.xcarchive/Products/Applications/Production.app -o '/var/folders/1q/gdj1_yn531z5h1zlw3jl4zdc6xxp45/T/gym_output20161208-92535-7k9k0j/client_name-1.16207.41-production.ipa' exportFormat ipa --embed '/Volumes/tfs/PSITP/Releases/HBP_2016.2.HotFix/src/OLBMobile/MobileBanking/iOS/fastlane/artifacts/InHouse_us.client_name.enterprise.MobileBanking.ProductionTest.mobileprovision' 
[12:43:05]: $ zip --recurse-paths '/var/folders/1q/gdj1_yn531z5h1zlw3jl4zdc6xxp45/T/gym_output20161208-92535-7k9k0j/client_name-1.16207.41-production.ipa' SwiftSupport > /dev/null
[12:43:05]: Compressing 1 dSYM(s)
[12:43:05]: $ cd '/Users/zhunt/Library/Developer/Xcode/Archives/2016-12-08/client_name-1.16207.41-production 2016-12-08 12.41.28.xcarchive/dSYMs' && zip -r '/Users/zhunt/Desktop/client_name-1.16207.41-production.app.dSYM.zip' *.dSYM
[12:43:06]: ▸   adding: Production.app.dSYM/ (stored 0%)
[12:43:06]: ▸   adding: Production.app.dSYM/Contents/ (stored 0%)
[12:43:06]: ▸   adding: Production.app.dSYM/Contents/Info.plist (deflated 52%)
[12:43:06]: ▸   adding: Production.app.dSYM/Contents/Resources/ (stored 0%)
[12:43:06]: ▸   adding: Production.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
[12:43:06]: ▸   adding: Production.app.dSYM/Contents/Resources/DWARF/Production (deflated 71%)

[12:43:06]: Successfully exported and compressed dSYM file
[12:43:06]: Successfully exported and signed the ipa file:
[12:43:06]: /Users/zhunt/Desktop/client_name-1.16207.41-production.ipa

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | xcode_select                        | 0           |
| 5    | cert                                | 4           |
| 6    | sigh                                | 3           |
| 7    | gym                                 | 102         |
+------+-------------------------------------+-------------+

[12:43:06]: fastlane.tools finished successfully 🎉
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                |
| ------------------- | ------------------------------------ |
| OS                  | 10.11.6                              |
| Ruby                | 2.3.1                                |
| Bundler?            | false                                |
| Git                 | git version 2.7.4 (Apple Git-66)     |
| Installation Source | /usr/local/bin/fastlane              |
| Host                | Mac OS X 10.11.6 (15G1108)           |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib   |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016          |
| Is contained        | false                                |
| Xcode Path          | /Library/Developer/CommandLineTools/ |
| Xcode Version       |  8.1 (8B62)                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
opt_out_usage
fastlane_version "1.29.2"
default_platform :ios

def my_get_version_number
	pbx_contents = IO.read("../ConnectMobile.xcodeproj/project.pbxproj")
	version_match = pbx_contents.match(/CONNECT_MOBILE_VERSION\s*=\s*(.*?);/)

	if version_match == nil or version_match.size < 2
		raise "Could not find version number"
	end

	return version_match[1]
end

def app_filename(configuration)
	version_number = my_get_version_number
	credit_union = Actions.lane_context[SharedValues::ENVIRONMENT]
	return "#{credit_union}-#{version_number}-#{configuration}.ipa"
end

def build_app(filename, export_method, configuration, scheme, output_directory)
	
	gym(
		clean: true,
		configuration: configuration,
		export_method: export_method,
		output_directory: output_directory,
		output_name: filename,
		scheme: scheme,
		use_legacy_build_api: true
	)
end

platform :ios do
	before_all do
		raise "Make sure you have set a client using --env ClientName" unless ENV["CONNECT_SCHEME"]

		xcode_select "/Applications/Xcode.app"
	end

	desc "Performs a build for the App Store"
	lane :build_store do |options|
		output_directory = options[:output_directory] || "/Users/tfsbuild/Desktop/Builds"

		# Get a code signing cert if we don't have one
		cert(output_path: "./artifacts")

		# Force creation or re-download of provisioning profile
		project_udid = sigh(
			adhoc: false,
			force: true,
			output_path: "./fastlane/artifacts"
		)

		# Save profile's GUID in environment variable (which is referenced in pbxproj)
		ENV["PROJECT_UDID"] = project_udid

		filename = app_filename("release")

		# Build the app
		build_app(filename, "app-store", "App Store", ENV["CONNECT_SCHEME"], output_directory)
	end

	desc "Performs a build pointed at production"
	lane :build_production do |options|
		output_directory = options[:output_directory] || "/Users/tfsbuild/Desktop/Builds"

		# Get a code signing cert if we don't have one
		cert(output_path: "./artifacts")

		# Force creation or re-download of provisioning profile
		project_udid = sigh(
			adhoc: (ENV["CONNECT_APPLE_ID_ENTERPRISE"] ? false : true),	# If credit union has an enterprise account, don't do an AdHoc build
			force: true,
			output_path: "./fastlane/artifacts"
		)

		# Save profile's GUID in environment variable (which is referenced in pbxproj)
		ENV["PROJECT_UDID"] = project_udid

		filename = app_filename("production")
		exportMethod = ENV["CONNECT_APPLE_ID_ENTERPRISE"] ? "enterprise" : "ad-hoc"

		# Build the app
		build_app(filename, exportMethod, "Production Test", ENV["CONNECT_SCHEME"], output_directory)
	end

	desc "Performs a build pointed at test"
	lane :build_test do |options|
		output_directory = options[:output_directory] || "/Users/tfsbuild/Desktop/Builds"

		# Get a code signing cert if we don't have one
		cert(output_path: "./artifacts")

		# Force creation or re-download of provisioning profile
		project_udid = sigh(
			adhoc: (ENV["CONNECT_APPLE_ID_ENTERPRISE"] ? false : true),
			force: true,
			output_path: "./fastlane/artifacts"
		)

		# Save profile's GUID in environment variable (which is referenced in pbxproj)
		ENV["PROJECT_UDID"] = project_udid
		
		filename = app_filename("test")
		exportMethod = ENV["CONNECT_APPLE_ID_ENTERPRISE"] ? "enterprise" : "ad-hoc"

		# Build the app
		build_app(filename, exportMethod, "Test", ENV["CONNECT_SCHEME"], output_directory)
	end
	
	desc "Takes screenshots from the production build"
	lane :screenshots do |options|
		output_directory = options[:output_directory] || "/Users/tfsbuild/Desktop/Builds"

		# Screenshots
		version_number = my_get_version_number
		credit_union = Actions.lane_context[SharedValues::ENVIRONMENT]
		screenshots_path = File.join(output_directory, "#{credit_union}-#{version_number}-screenshots")
		ENV["SNAPSHOT_SCHEME"] = ENV["CONNECT_SCHEME"] + "Snapshot"
		ENV["SNAPSHOT_OUTPUT_DIRECTORY"] = screenshots_path
		snapshot
	end

end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# See https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md for documentation

for_platform :ios do
	apple_id ENV["CONNECT_APPLE_ID"]

	for_lane :build_store do
		app_identifier ENV["CONNECT_BUNDLE_ID_STORE"]
	end

	for_lane :build_production do
		app_identifier ENV["CONNECT_BUNDLE_ID_PRODUCTION"]

		# If credit union has an enterprise account, use that for production build
		if ENV["CONNECT_APPLE_ID_ENTERPRISE"]
			apple_id ENV["CONNECT_APPLE_ID_ENTERPRISE"]
		end
	end

	for_lane :build_test do
		app_identifier ENV["CONNECT_BUNDLE_ID_TEST"]

		# If credit union has an enterprise account, use that for test build
		if ENV["CONNECT_APPLE_ID_ENTERPRISE"]
			apple_id ENV["CONNECT_APPLE_ID_ENTERPRISE"]
		end
	end
end
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.38.5  | ✅ Up-To-Date        |
| fastlane_core       | 0.57.2  | 🚫 Update availaible |
| deliver             | 1.16.0  | 🚫 Update availaible |
| snapshot            | 1.16.4  | ✅ Up-To-Date        |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | 🚫 Update availaible |
| cert                | 1.4.4   | ✅ Up-To-Date        |
| sigh                | 1.12.1  | ✅ Up-To-Date        |
| produce             | 1.3.2   | ✅ Up-To-Date        |
| gym                 | 1.12.1  | ✅ Up-To-Date        |
| pilot               | 1.12.1  | ✅ Up-To-Date        |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | 🚫 Update availaible |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.1.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.8        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.57.2       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-12-08**
</details>

**Comment by zhunt11** [comment]
The app is being signed just fine. This has something to do with Enterprise builds with Fastlane, maybe Gym or Sigh.

**Comment by zhunt11** [comment]
Can anyone help me with this issue?

**Comment by zhunt11** [comment]
Any update on this?

**Comment by zhunt11** [comment]
Any update? Can I get someone assigned to this issue? I'm not familiar with the process so if there is something I'm missing please let me know.

**Comment by zhunt11** [comment]
Any update? Has anyone looked at this? I still cannot resolve this issue.

**Comment by zhunt11** [comment]
Any update?

**Comment by zhunt11** [comment]
Can anyone help me with this? Not sure what I have to do to get a reply.

**Comment by philk** [comment]
We were having the same issue. Turning off `use_legacy_build_api` fixed it for us but we didn't actually need it anymore so turning it off made sense anyway.

In your logs the line:
`[12:43:02]: Legacy build api is enabled, the export_method value will be ignored`
makes me think you just can't use legacy build with enterprise.

**Comment by zhunt11** [comment]
I just saw a console message in a build I did today that says use_legacy_build_api is deprecated so I took it out. Now none of my builds are working. What do I need to set export_method to for enterprise builds?

**Comment by zhunt11** [comment]
Hmmm. The error I'm getting now that I took out use_legacy_build_api is: "No applicable devices found."
This post says setting use_legacy_build_api to true fixes it, but I also get a message during the build that says it is deprecated and we should not use it anymore. I feel stuck.

https://github.com/fastlane/fastlane/issues/3184

**Comment by philk** [comment]
`No applicable devices` sounds like something in the project config rather than fastlane to me, but could be something with adhoc (we only use fastlane for enterprise signing).

At any rate, here's the section from our Fastfile for the build. Good luck, all this stuff is basically magic to me.

```ruby
  desc "Build new ipa for distribution"
  lane :beta do |options|
    ENV["MATCH_FORCE_ENTERPRISE"] = '1'
    match(
      type: "enterprise",
      git_url: "git@github.com:team/repo.git",
      readonly: true
    )
    gym(
      workspace: 'app.xcworkspace',
      configuration: 'Release',
      scheme: options[:scheme] || 'staging',
      output_name: 'AppName.ipa'
    )
  end
```

**Comment by ohayon** [comment]
Hey @zhunt11! Apologies for the slow response and the issues youre having with _match_! It sounds like you have quite the setup 😄  Debugging codesigning issues can be pretty difficult sometimes, but my initial assumption is that the correct profile is not being assigned at export time. Have you tried programmatically setting the `SIGH_PROVISIONING_PROFILE_NAME` environment variable? 🐙
