### ISSUE TITLE
Where does iTunes "by Company Name" come from?

### ISSUE THREAD

**Issue by erikjthomas** [fastlane/fastlane#7384]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is it possible to change the "by Company Name" that appears just below the app name in the Apple App Store? 

Or does that come from the company name on the Apple Developer account? If so, do you think it would be possible to change it dynamically using Spaceship or in produce or another action? 

Looking at iTC forms I don't see a place where this can be changed, but perhaps it can be using APIs? 

Background: We brand white-label apps for other companies and we have been doing it from our own Developer Account, but we're starting to get rejections from reviewers because the name of the app identifies a company when the "seller" or "by company name" is the company name of our apple Developer account. 

We're trying to figure out the best solution that might scale. Being able to specify a different "seller" as app metadata would be ideal. 

Thanks for any advice.

##### Complete output when running fastlane, including the stack trace and command used

N/A

### Environment

N/A

**Comment by KrauseFx** [comment]
I feel like this is not _fastlane_ related, but something you should discuss with Apple directly 👍

**Comment by erikjthomas** [comment]
Yup, closing.
