### ISSUE TITLE
[ Deliver ] : Can I add release and resolution_center as a Parameter ? 

### ISSUE THREAD

**Issue by ram0287** [fastlane/fastlane#7394]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

[ Deliver ] : Can I add release and resolution_center as a Parameter ? 
Both the actions have been provided - but not being exposed as a parameter in Deliver
Is there any reason behind it ?

**Comment by KrauseFx** [comment]
Could you clarify a bit more about the flag and feature you want to add? 👍

**Comment by ram0287** [comment]
Flag name : **release_app** 
Flag Value : true or false
Flag Description : If the App is in Pending for Developer Release state, setting this true will Release the app to the app store

resolution_center is quite different
What I was thinking is, it would be handy if we can get the status of the Submitted App ( After submitting for review ) 
Is it been rejected, if so, whats the reason - likewise

But I wanted to get your opinion as well
Please let me know.

**Comment by ram0287** [comment]
Any update on this @KrauseFx
