### ISSUE TITLE
error:'Could not find 'fastlane' (>= 0) among 13 total gem(s) (Gem::LoadError)'  When I update the Ruby version to 2.3.3 

### ISSUE THREAD

**Issue by ShenJieSuzhou** [fastlane/fastlane#7396]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I usa command 'sudo gem install fastlane -NV' to intsall fastlane , 
then run the command 'fastlane init', after i input the AppleID , The terminal displays the following error message：Connection reset by peer - SSL_connect...
I checked the information on the Internet, the result is ruby ​​version, so I updated to 2.3.3 But there are my question today, I hope someone can help me , thanks

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
silicontekiMac-mini:SnailFastlaneDemo silicon$ rvm list

rvm rubies

   ruby-2.0.0-p648 [ x86_64 ]
=* ruby-2.3.1 [ x86_64 ]
   ruby-2.3.3 [ x86_64 ]

silicontekiMac-mini:SnailFastlaneDemo silicon$ fastlane init
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (>= 0) among 13 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

silicontekiMac-mini:SnailFastlaneDemo silicon$ fastlane env
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (>= 0) among 19 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by KrauseFx** [comment]
Could you try our new [fastlane setup page](https://fabric.io/features/distribution#) and let us know if that works for you? 👍

**Comment by ShenJieSuzhou** [comment]
@KrauseFx Thx, after I re-install  fastlane  today ,it works fine ...

But very strange, I  re-installed it before, but did not resolve.
