### ISSUE TITLE
Supply fetch_access_token error - google oauth

### ISSUE THREAD

**Issue by jpokrzyk** [fastlane/fastlane#7407]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I run supply I'm getting an oauth error. Tried this on multiple computers and multiple versions of ruby. I haven't really touched my fastlane setup in the past 6 months except updating fastlane and then updating ruby because of the openssl issue.

```
+-------------------------+-------------------------------------------------------------+
|                               Summary for supply 0.8.0                                |
+-------------------------+-------------------------------------------------------------+
| package_name            | com.smartpathfinancial.smartpath                            |
| track                   | production                                                  |
| rollout                 | 0.1                                                         |
| metadata_path           | ./fastlane/metadata/android                                 |
| json_key                | android/app/Google Play Android Developer-0bfc954ebc97.json |
| skip_upload_apk         | false                                                       |
| skip_upload_metadata    | false                                                       |
| skip_upload_images      | false                                                       |
| skip_upload_screenshots | false                                                       |
| validate_only           | false                                                       |
+-------------------------+-------------------------------------------------------------+


Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:981:in `fetch_access_token': [!] Authorization failed.  Server message: (Signet::AuthorizationError)
{
 "error": "invalid_client",
 "error_description": "The OAuth client was not found."
}
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/signet-0.7.3/lib/signet/oauth_2/client.rb:998:in `fetch_access_token!'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/googleauth-0.5.1/lib/googleauth/signet.rb:69:in `fetch_access_token!'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/client.rb:58:in `initialize'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/client.rb:30:in `new'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/client.rb:30:in `make_from_config'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/uploader.rb:165:in `client'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/uploader.rb:6:in `perform_upload'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/commands_generator.rb:39:in `block (2 levels) in run'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane_core-0.59.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/commands_generator.rb:57:in `run'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/lib/supply/commands_generator.rb:15:in `start'
	from /Users/jon/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/supply-0.8.0/bin/supply:6:in `<top (required)>'
	from /Users/jon/.rbenv/versions/2.3.1/bin/supply:23:in `load'
	from /Users/jon/.rbenv/versions/2.3.1/bin/supply:23:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C63a)                   |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.83.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")

    increment_build_number(
      xcodeproj: './ios/smartpathmobile.xcodeproj'
    )

    gym(
      scheme: "smartpathmobile",
      workspace: './ios/smartpathmobile.xcworkspace',
      # use_legacy_build_api: true
    )

    commit_version_bump(
      message: "Deployed new build #{lane_context[SharedValues::BUILD_NUMBER]}",
      xcodeproj: './ios/smartpathmobile.xcodeproj'
    )

    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    add_git_tag(tag: "testflight-#{build_number}")

    pilot(skip_waiting_for_build_processing: false)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")

    increment_build_number(
      xcodeproj: './ios/smartpathmobile.xcodeproj'
    )

    gym(
      scheme: "smartpathmobile",
      project: './ios/smartpathmobile.xcodeproj'
    )

    commit_version_bump(
      message: "Deployed new build #{lane_context[SharedValues::BUILD_NUMBER]}",
      xcodeproj: './ios/smartpathmobile.xcodeproj'
    )

    build_number = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    add_git_tag(tag: "appstore-#{build_number}")

    deliver(
      # skip_deploy: true,
      force: true
    )

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

platform :android do
  desc "Deploy a new version to the Google Play Store"
  lane :alpha do
    gradle(
      task: 'clean',
      project_dir: "android/"
    )
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android/"
    )
    supply(
      track: "alpha",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.smartpathfinancial.smartpath" # The bundle identifier of your app
apple_id "apple@smartpathfinancial.com" # Your Apple email address

team_id "Q85LEPVMAX"  # Developer Portal Team ID

json_key_file "android/app/Google Play Android Developer-0bfc954ebc97.json"
package_name "com.smartpathfinancial.smartpath"
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.38.5  | ✅ Up-To-Date  |
| fastlane_core       | 0.59.0  | ✅ Up-To-Date  |
| deliver             | 1.16.1  | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| addressable               | 2.3.8        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.6.0        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.59.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-12-09**
</details>

**Comment by asfalcone** [comment]
@jpokrzyk Sorry it's been a month with no response to your issue! Is this still a problem for you with the latest _fastlane_?

**Comment by RBische** [comment]
Bumped into the same issue, may I ask you what you did ?

**Comment by jpokrzyk** [comment]
Had to generate a new token on google and everything worked fine. Not sure how it got invalidated.
