### ISSUE TITLE
How can I configure fastlane gym to build with ad hoc provisioning profile using match?

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7408]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This is not a issue more of a query. How can I specify a project to build for `adhoc`  and for `App Store`. I am using `gym` and `match`.

**Comment by PetrosIchor** [comment]
Lots of ways. Be sure to read through the documentation.  Simplest would be to have separate lanes and just call the one you want to build.

**Comment by RishabhTayal** [comment]
I went through documentation but I couldn't find a way to specify the provisioning profile in the `Fastfile`. If I set the right provisioning profile in the Xcode then it works. Maybe I am missing something.

**Comment by RishabhTayal** [comment]
I have different lanes for app store and adhoc distribution. But I don't understand how we can pick the right provisioning profile in the `Fastfile`.

**Comment by PetrosIchor** [comment]
The variables match outputs need to be in the xcodeproj file.  If match is pulling those profiles/cert then assigning them to the sigh variables correctly and you have those same sigh variables in the xcodeproj file.  Gym should build correctly.   

Check out the fastlane codesigning guide.  If you've followed those steps correctly it should work for you.  If it's not, provide more details please and maybe someone can help.

**Comment by KrauseFx** [comment]
I'll close this issue for now due to inactivity. Please feel free to re-open or submit a new one if you have any more questions 👍
