### ISSUE TITLE
Sync certificates and provisioning profiles between team members.

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7409]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This is more of a question than issue. I am using match to sync the provisioning profiles and certificates on git repo. How can I sync certificates and provisioning profiles between team members **without** sharing the password for the developer portal account.

**Comment by KrauseFx** [comment]
You can use the `readonly` mode for that 👍
