### ISSUE TITLE
Change fastlane to be a mono gem

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#7412]
We want fastlane to be just one gem instead of 10. People would install _fastlane_, and get all the other tools with that. We want to deprecate the other tools as standalone gems and make them part of fastlane

**Why?**

- Make releases much simpler, just one gem to ship
- No more internal dependency updates
- No more version conflicts if we add some methods to some sub-gems
- 1 PR could modify multiple tools and tests are still passing (doesn’t mean we have to, but we can for example to update _spaceship_ and _deliver_ at the same time if necessary)

Are there any concerns or disadvantages we should consider?

**Comment by hjanuschka** [comment]
i really like this idea - no more PR splitting!!!

**Comment by KrauseFx** [comment]
> we found some issues with having spaceship as standalone gem, as this would also require _credentials_manager_ as standalone gem
> this way, we’d have some sub-folders being there own gems, and some not
making the whole setup much more complex
> we looked at libraries.io, the only big open source project using spaceship directly is xcode-install, which is owned by me, and could be part of the fastlane mono repo
> let us know if you have any concerns around this

**Comment by hjanuschka** [comment]
so for people who wan't to use spacehip only they would have to install fastlane gem, and then `require "fastlane/spaceship"` ?

**Comment by KrauseFx** [comment]
@hjanuschka they can just `require 'spaceship'` and it just works ™ but yeah, they need to _fastlane_ as dependency

**Comment by supermarin** [comment]
Disadvantages - we can't use just pilot now. we need to add 50 gems only to use pilot.
I believe there's better way to pack gems rather than merging all into one

**Comment by supermarin** [comment]
To elaborate, this adds further potential gem collisions if users have been using different versions of gems `fastlane` is depending on

**Comment by ikonst** [comment]
We woke up to a morning of breaking CI, since:
a) `credentials_manager-1.6.0` and `credentials_manager-1.6.2` were yanked out of Rubygems
b) we were using `pilot-1.13.1` which depends on `credentials_manager>=1.6.0`

All Pilot users are now forced to either downgrade their Pilot to 1.10.0 (all versions above are unusable due to missing deps), or install Fastlane 2.0.

**Comment by fabb** [comment]
We always upgrade to the newest gym/pilot/deliver versions in our CI script. Packing all into one gem increases the unnecessary dependencies a lot. Isn't there a better way to install only the necessary tools? Something like subspecs or as plugins to fastlane core?

**Comment by KrauseFx** [comment]
> Something like subspecs

There is no concept of subspecs in the Ruby World to my knowledge.

> We always upgrade to the newest gym/pilot/deliver versions in our CI script

Sounds good, now you only have to update the _fastlane_ gem.

> b) we were using pilot-1.13.1 which depends on credentials_manager>=1.6.0

Yes, it seems like there was an issue pushing the new pilot release with the updated dependencies, sorry for the troubles. All the other tools should work with no issues. Follow https://github.com/fastlane/fastlane/issues/7590 to stay up to date.

> Disadvantages - we can't use just pilot now. we need to add 50 gems only to use pilot.

I completely understand - we're trying to cover the main use-case, which is using _fastlane_ with some of its tools. We want to have a better solution to separate different scenarios, e.g. using _fastlane_ without any of the iOS or Android specific modules.

> I believe there's better way to pack gems rather than merging all into one

What do you have in mind? I'd love to find a better solution 👍 

> To elaborate, this adds further potential gem collisions if users have been using different versions of gems fastlane is depending on

True, but due to _fastlane_'s nature of usually needing the most up-to-date _spaceship_ release, we really want people to be on the latest release usually. While this is not ideal as builds might not be reproducible, there is no way (to my knowledge) to do that, with the third party API changing, and us needing to update _spaceship_ regularly to stay up to date. _pilot_ uses the transporter to upload the binary, however everything around that like providing the changelog, distributing the build and adding testers requires the iTunes Connect API. If you really just want to upload the build, you might be better off using the [iTunes Transporter CLI](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/itunes_transporter.rb) directly.

--- 

We tried to make the transition as smooth as possible, and I understand not everything is perfect for everyone. That's why we tried to communicate the plan in advance here via GitHub so users can chime in and add their concerns and feedback. Until now the overall feedback was great, in particular from our contributors who now have a much easier time contributing to _fastlane_.

**Comment by mathaeus** [comment]
> Sounds good, now you only have to update the fastlane gem.

We have a CI server where we build our app in a dedicated workspace for every build. We install all the necessary tools within that standalone workspace. That means we install the necessary gems/binaries for _every_ build. Until now we only had to install just a few selected gems, now we have to install the whole `fastlane` toolchain, which 
a) just takes too long to do it every time
b) adds a lot of overhead we don't need.

So we'd really appreciate a solution which would allow us to still just use, for example, `gym`, `pilot` and `scan`.

**Comment by KrauseFx** [comment]
> So we'd really appreciate a solution which would allow us to still just use, for example, gym, pilot and scan.

I'm open for suggestions, however maintaining 15 gems was a pain, and cost us a ton of time (working-wise, not computer time), see the reasons mentioned [on the body of this issue](https://github.com/fastlane/fastlane/issues/7412#issue-194701262).

> a) just takes too long to do it every time

How much time difference is it compared to installing 3 standalone gems? 

> b) adds a lot of overhead we don't need.

Agreed, however calling `fastlane gym [something]` will behave the exact same way before, no other areas or tools are being called or used.

**Comment by milch** [comment]
> We have a CI server where we build our app in a dedicated workspace for every build. We install all the necessary tools within that standalone workspace. That means we install the necessary gems/binaries for every build. Until now we only had to install just a few selected gems, now we have to install the whole fastlane toolchain, which
a) just takes too long to do it every time
b) adds a lot of overhead we don't need.

If you are concerned about the time it takes to download all gems I'd suggest setting up a local [rubygems mirror](http://guides.rubygems.org/run-your-own-gem-server/#running-gemirro). This should dramatically speed up your installation time, and will probably even be a bit faster than before the monogem since dependency resolution should now be faster ✨ Since you pull down gems on every build, it seems like this would yield huge benefits for your setup. 

> b) we were using pilot-1.13.1 which depends on credentials_manager>=1.6.0

We're really sorry about that - there was an issue pushing out the new version of pilot that should now be fixed. We also silently released a version of credentials_manager (0.16.4) that is compatible with old versions of pilot.

**Comment by mathaeus** [comment]
> If you are concerned about the time it takes to download all gems I'd suggest setting up a local rubygems mirror. This should dramatically speed up your installation time, and will probably even be a bit faster than before the monogem since dependency resolution should now be faster ✨ Since you pull down gems on every build, it seems like this would yield huge benefits for your setup.

Hmm yeah I guess we should have a look at that. Thanks for the hint!
We'll try it out and let you know if that works for us.

**Comment by jonah-williams** [comment]
@mathaeus you might want to take a look at the tools bundler already provides (http://bundler.io/v1.13/deploying.html#deploying-your-application and http://bundler.io/v1.13/man/bundle-install.1.html#DEPLOYMENT-MODE). Wanting a fast, isolated, and stable dependency installation step in your deploy pipeline is a pretty common problem and I've found the existing Ruby toolchain solves it well.

**Comment by mathaeus** [comment]
> you might want to take a look at the tools bundler already provides 

@jonah-williams thanks, I'll have a look!

**Comment by chappejw** [comment]
If users have already created an automated ruby build system and have adopted some of the fastlane tools such as spaceship, pilot, pem, sigh, cert, can those tools still be used in an independent ruby script? such as:
...
`pem_cmd = "/usr/local/bin/pem"
    if (isDevelopment)
        pem_cmd = "#{pem_cmd} --development"
    end

    pem_output = `#{pem_cmd}`
    puts pem_output`
...

or could I still use it like this?

`pem_cmd = "/usr/local/bin/fastlane pem"
    if (isDevelopment)
        pem_cmd = "#{pem_cmd} --development"
    end

    pem_output = `#{pem_cmd}`
    puts pem_output`

**Comment by KrauseFx** [comment]
@chappejw yes, you can always just call any of the tools directly using `fastlane [tool_name] [parameters]` 👍

**Comment by chappejw** [comment]
Great.! Thanks for the follow up Felix. Now if only there was a way to make use of Xcode 8's automatic provisioning via command line.

**Comment by KrauseFx** [comment]
@chappejw That's already possible, check out the [code signing docs](https://docs.fastlane.tools/codesigning/xcode-project/#xcode-8-and-up). Either way, it's not related to this issue, so please submit a new issue if you're having troubles with it.
