### ISSUE TITLE
Getting a static key for the matched provision profile by match.

### ISSUE THREAD

**Issue by ishaanSejwal** [fastlane/fastlane#7418]
I am currently using match to sync my certificates profile to my CI instance before building the app using gym. In some cases a new provisioning profile might be created by match and synced upto my git repo after a newly mentioned bundle identifier is pushed in my latest code commit.

So for such cases I need a static environment variable for matched provisioning profile so I can build my app. Let me know if there is any other way also to achieve my use case. I currently get variable like `sigh_xxxxxxxxxxxxx_appstore` which is not static for me to mention in gym.

I have currently set`PROVISIONING_PROFILE_SPECIFIER` in Xcode to none in the hope that I can mention some variable for a correct provisioning profile synched by match that can be used by gym. Ofcourse currently build is failing because `PROVISIONING_PROFILE_SPECIFIER` remains set to none and I get `Code signing is required for product type 'Application' in SDK 'iOS 10.1'`

**Comment by hjanuschka** [comment]
you can use `$(sigh_xxxxxxxxxxxxx_appstore)`  in xcode - than it uses the env variable
which `match` sets during `gym`

**Comment by ishaanSejwal** [comment]
Sure but that env variable would still need to be resolved with the currently being used bundle id and hence a static variable would be nice. I am raising a feature request or this. Because setting code signing identity to `Automatic` allows Xcode to pick up the certificate synched by match for a particular configuration but there is no `Automatic` option for `PROVISIONING_PROFILE_SPECIFIER`.
