### ISSUE TITLE
Upload a new version to testflight using fastlane and jenkins via ssh

### ISSUE THREAD

**Issue by mdeandreis** [fastlane/fastlane#742]
I´m trying to upload a new version to Testflight using Fastlane and Jenkins. If I run fastlane beta locally everything works fine. On the other hand, when I try to upload a new version with Jenkins via ssh I get an error. Scheme is shared, keys are in system and not in login (keychain)

After run the job I get this:

[37m[13:08:39]: [0m[32m-------------------------------------------------[0m
[37m[13:08:39]: [0m[32m--- [0m[32mStep: Verifying required fastlane version[0m[32m ---[0m
[37m[13:08:39]: [0m[32m-------------------------------------------------[0m
[37m[13:08:39]: [0mfastlane version valid
[37m[13:08:39]: [0m[32m------------------------------[0m
[37m[13:08:39]: [0m[32m--- [0m[32mStep: default_platform[0m[32m ---[0m
[37m[13:08:39]: [0m[32m------------------------------[0m
[37m[13:08:39]: [0m[32mDriving the lane 'ios beta' 🚀[0m
[37m[13:08:39]: [0m[32m-----------------[0m
[37m[13:08:39]: [0m[32m--- [0m[32mStep: gym[0m[32m ---[0m
[37m[13:08:39]: [0m[32m-----------------[0m
[37m[13:08:39]: [0mInstalling provisioning profile...
[37m[13:08:40]: [0m[33mxcrun xcodebuild -list -workspace './Pepe.xcworkspace'[0m
[37m[13:08:46]: [0m[33mxcrun xcodebuild -showBuildSettings -workspace '.Pepe.xcworkspace' -scheme 'Pepe'[0m
+---------------+--------------------------------+
|             [32mBuilding Application 🚀[0m             |
+---------------+--------------------------------+
| Workspace     | ./Pepe.xcworkspace |
| Scheme        | Pepe               |
| Export Method | app-store                      |
| Platform      | iOS                            |
| Xcode Path    | /Applications/Xcode.app/       |
+---------------+--------------------------------+

[37m[13:08:48]: [0m[33mset -o pipefail && xcodebuild -workspace './Pepe.xcworkspace' -scheme 'Pepe' -destination 'generic/platform=iOS' -archivePath '/Users/../Library/Developer/Xcode/Archives/2015-10-26/Pepe 2015-10-26 13.08.48.xcarchive' archive | tee '/Users/,,/Library/Logs/gym/Pepe-Pepe.log' | xcpretty[0m
[36msh: xcpretty: command not found[0m
sh: xcpretty: command not found
[37m[13:10:59]: [0mExit status: 127
[37m[13:10:59]: [0m[33mVariable Dump:[0m
[37m[13:10:59]: [0m{:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
[1m[31m[13:10:59]: [0m[0m[31mError building the application - see the log above[0m

**Comment by xfreebird** [comment]
You are missing the ```xcpretty``` command on you build machine.

To install it, on your build machine please run:
```sudo gem install xcpretty```

 Also you could update all your gems to make sure that you get all dependencies on your build machine from updates.

```sudo gem update -p```

What version of ```fastlane``` you have on your build machine ?

**Comment by mdeandreis** [comment]
I have fastlane 1.35.0. I just installed xcpretty (version 0.2.0) and updated gem (version 2.0.14) )and I get the same error. I have Xcode Version 7.1 (7B91b) and the app is developed in Swift

Any idea?

**Comment by KrauseFx** [comment]
Did you follow the [Jenkins Guide](https://github.com/KrauseFx/fastlane/blob/master/docs/Jenkins.md)?

**Comment by xfreebird** [comment]
@mdeandreis it seems a issue with El Capitan. When you login to your build machine through ssh, can you execute ```xcpretty``` command ? Did you get any errors during ```gem update -p```

**Comment by mdeandreis** [comment]
I did not get an error when I run gem update -p (Nothing to update). I tried to execute xcpretty via ssh to my mac and works fine

**Comment by xfreebird** [comment]
You might need to restart your build machine :8ball:

**Comment by mdeandreis** [comment]
Finally, I solved this issue. I set the command´s path in the script (/usr/local/bin) and everything works fine.
Thanks a lot @xfreebird and @KrauseFx

**Comment by xfreebird** [comment]
:+1:  @mdeandreis that means you installed the gems to a ```/usr/local/``` prefix :), I was mislead by the sudo command. In this case you could use ```rbenv```.

**Comment by mdeandreis** [comment]
Now, I have a different error. I run fastlane beta on Jenkins and the app is uploaded to Testflight. However, fastlane finished with errors 0m"\xF0" on US-ASCII. Any idea what happend?

**Comment by xfreebird** [comment]
yes

```bash
echo "export LC_ALL=en_US.UTF-8" >> ~/.profile
ln -s ~/.profile ~/.bashrc
```

and restart Jenkins, or even better your build machine

**Comment by mdeandreis** [comment]
Ok, I'll try this and I'll tell you how it works as soon as I can
Thanks!

**Comment by mdeandreis** [comment]
Fantastic, everything works fine!

Thanks @xfreebird

**Comment by KrauseFx** [comment]
Thanks @xfreebird :+1:

**Comment by biolinh** [comment]
I have been got the error. 

>...|  tee '/Users/jenkins/Library/Logs/fastlane/xcbuild/2016-03-08/43144/xcodebuild.log' | xcpretty --color --simple' was 127 instead of 0. (FastlaneCore::Interface::FastlaneCrash)
> sh: xcpretty: command not found

I did every suggestion you said:
- xcpretty in folder /usr/local/bin/
- restart server

But, it is no luck. Still get the error.

**Comment by zapjonny** [comment]
Where do you set /usr/local/bin/ for xcpretty? It can't find xcpretty for me either.

**Comment by smaljaar** [comment]
I get the same thing. I'm executing a shell from Jenkins, and there I get the error xcpretty: command not found
When I run from terminal xcpretty works, also when logged in as Jenkins user.

Any clues?

**Comment by TKBurner** [comment]
Hi @smaljaar This is a Jenkins config issue. I think you will need to set up your Jenkins shell to to know the path to xcpretty. Thanks!

**Comment by smaljaar** [comment]
I fixed this a suggested in this thread, in my jenkins job I now successfully run 
xcodebuild [args] | /usr/local/bin/xcpretty 
instead of 
xcodebuild [args] | xcpretty

**Comment by TKBurner** [comment]
@smaljaar Awesome! Glad to hear you are up and running. Have a wonderful week!

**Comment by fishercraigj** [comment]
I'm still running into the issue, "sh: xcpretty: command not found" when running fastlane.  The xcsbuildd user has /usr/local/bin xcpretty installed.  I can run it from the xcsbuildd user through terminal.  I have rebooted the server about 5 times.  All my gems are up to date.  The main difference between myself and the rest of what I'm seeing on this thread is that I'm running my CI through Xcode Server not Jenkins.

I'm kind of at a loss for thing to try.  I'm on Xcode 7.3.1 and OS X 10.11.6.  Any guidance would be much appreciated!

**Comment by TKBurner** [comment]
Hi @fishercraigj Can you run `which xcpretty`? Also what version of ruby are you using?

Thanks!

**Comment by devluyy** [comment]
@TKBurner I have a same question with @fishercraigj.
 My ruby version is ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]

**Comment by fishercraigj** [comment]
@TKBurner - yes, i can run it just fine from the xcsbuildd user. Sorry for the slow reply.

**Comment by fishercraigj** [comment]
And I'm on 2.0.3

**Comment by devluyy** [comment]
@fishercraigj you can add this code in your script file 
export PATH="$PATH:/usr/local/bin:/usr/local/bin:/usr/local/sbin$:"

**Comment by TKBurner** [comment]
@fishercraigj You can either use rvm to manage your ruby version or use homebrew to install xcpretty. Let me know how it goes!

**Comment by Patrickuang** [comment]
@devluyy add `export PATH="$PATH:/usr/local/bin:/usr/local/bin:/usr/local/sbin$:"` in script file works for me. Thanks.
