### ISSUE TITLE
[match] app + today extension

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#7430]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hello, tell me please how I can sigh app through match for app and app extension.
app id = com.company.id
app id extension = com.company.id.WidgetOrdersInfo

**Comment by GandjaFuzz** [comment]
I use match this 
```
		match(
			force: true,
			app_identifier: work_bundle_id(),
			git_url: get_match_url(),
			type: "appstore",
			username: get_apple_id(),
			shallow_clone: true		
		)
```

**Comment by hjanuschka** [comment]
app_identifier can also be an array:

```ruby
match(git_url: url_git,
        type: 'appstore',
        app_identifier: ["com.company.id", "com.company.id.WidgetOrdersInfo"])
```

**Comment by GandjaFuzz** [comment]
Many thanks!

**Comment by hjanuschka** [comment]
works? can you close the issue?
