### ISSUE TITLE
frameit: Unsupported screen size [2286, 3168] for path

### ISSUE THREAD

**Issue by samphilipd** [fastlane/fastlane#7432]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running frameit for iPad Pro screenshots, I see this error: `Unsupported screen size [2286, 3168] for path 'fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator Screen Shot 24 Aug 2016, 16.24.41_framed.png'`

The original file has resolution of 2048 × 2732

### Captured Output

Command Used: `release --env pgm`
<details><summary>Output/Log</summary>

```

+----------------------------+---------+------------------------------------+
|                               Used plugins                                |
+----------------------------+---------+------------------------------------+
| Plugin                     | Version | Action                             |
+----------------------------+---------+------------------------------------+
| fastlane-plugin-versioning | 0.2.5   | get_app_store_version_number       |
|                            |         | get_build_number_from_plist        |
|                            |         | get_info_plist_path                |
|                            |         | get_version_number_from_git_branch |
|                            |         | get_version_number_from_plist      |
|                            |         | increment_build_number_in_plist    |
|                            |         | increment_version_number_in_plist  |
+----------------------------+---------+------------------------------------+

[14:12:00]: -------------------------------------------------
[14:12:00]: --- Step: Verifying required fastlane version ---
[14:12:00]: -------------------------------------------------
[14:12:00]: Your fastlane version 1.111.0 matches the minimum requirement of 1.109.0  ✅
[14:12:00]: ------------------------------
[14:12:00]: --- Step: default_platform ---
[14:12:00]: ------------------------------
[14:12:00]: Loading from './fastlane/.env.pgm'
[14:12:00]: Driving the lane 'release' 🚀
[14:12:00]: ---------------------
[14:12:00]: --- Step: frameit ---
[14:12:00]: ---------------------
[14:12:02]: Framing screenshots at path ./fastlane/screenshots-pgm
[14:12:02]: Using device frames version 'latest'
[14:12:02]: Framing screenshot './en-AU/1_ipadPro_1.Simulator Screen Shot 24 Aug 2016, 16.24.41.png'
[14:12:05]: Added frame: '/Users/sam/code/progolfme/progolfme-ios/fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator Screen Shot 24 Aug 2016, 16.24.41_framed.png'
[14:12:05]: Framing screenshot './en-AU/1_iphone6Plus_1.Simulator Screen Shot 24 Aug 2016, 15.58.54.png'
[14:12:07]: Added frame: '/Users/sam/code/progolfme/progolfme-ios/fastlane/screenshots-pgm/en-AU/1_iphone6Plus_1.Simulator Screen Shot 24 Aug 2016, 15.58.54_framed.png'
[14:12:07]: Framing screenshot './en-AU/2_ipadPro_2.Simulator Screen Shot 24 Aug 2016, 16.25.23.png'
[14:12:10]: Added frame: '/Users/sam/code/progolfme/progolfme-ios/fastlane/screenshots-pgm/en-AU/2_ipadPro_2.Simulator Screen Shot 24 Aug 2016, 16.25.23_framed.png'
[14:12:10]: Framing screenshot './en-AU/2_iphone6Plus_2.Simulator Screen Shot 24 Aug 2016, 16.28.48.png'
[14:12:11]: Added frame: '/Users/sam/code/progolfme/progolfme-ios/fastlane/screenshots-pgm/en-AU/2_iphone6Plus_2.Simulator Screen Shot 24 Aug 2016, 16.28.48_framed.png'
[14:12:11]: ---------------------
[14:12:11]: --- Step: deliver ---
[14:12:11]: ---------------------
[14:12:11]: Successfully loaded '/Users/sam/code/progolfme/progolfme-ios/fastlane/Deliverfile' 📄

+-----------------------+-----------------------+
| Detected Values from './fastlane/Deliverfile' |
+-----------------------+-----------------------+
| username              | seivadmas@gmail.com   |
+-----------------------+-----------------------+

[14:12:11]: Login to iTunes Connect (seivadmas@gmail.com)
[14:12:22]: Login successful

+-----------------------+--------------------------+
|              deliver 1.16.1 Summary              |
+-----------------------+--------------------------+
| metadata_path         | fastlane/metadata-pgm    |
| screenshots_path      | fastlane/screenshots-pgm |
| app_identifier        | com.progolfme.app        |
| ipa                   | ProGolfMe.ipa            |
| submit_for_review     | true                     |
| username              | seivadmas@gmail.com      |
| app_version           | 1.3.0                    |
| platform              | ios                      |
| skip_binary_upload    | false                    |
| skip_screenshots      | false                    |
| skip_metadata         | false                    |
| force                 | false                    |
| automatic_release     | false                    |
| overwrite_screenshots | false                    |
+-----------------------+--------------------------+

[14:12:23]: Making sure the latest version on iTunes Connect matches '1.3.0' from the ipa file...
[14:12:27]: '1.3.0' is the latest version on iTunes Connect
[14:12:27]: Framed screenshots are detected! 🖼 Non-framed screenshot files may be skipped. 🏃
[14:12:27]: 🏃 Skipping screenshot file: fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator Screen Shot 24 Aug 2016, 16.24.41.png
[14:12:27]: Variable Dump:
[14:12:27]: {:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"pgm", :PLATFORM_NAME=>nil, :LANE_NAME=>"release"}
[14:12:27]: Unsupported screen size [2286, 3168] for path 'fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator Screen Shot 24 Aug 2016, 16.24.41_framed.png'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | frameit                             | 11          |
| 💥    | deliver                             | 15          |
+------+-------------------------------------+-------------+

[14:12:27]: fastlane finished with errors

[!] Unsupported screen size [2286, 3168] for path 'fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator Screen Shot 24 Aug 2016, 16.24.41_framed.png'


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

def build_app(configuration)
  cocoapods

  increment_build_number_in_plist(target: ENV['SCHEME'])

  # build your iOS app
  gym(
    scheme: ENV['SCHEME'],
    configuration: configuration
  )

  commit_version_bump(
    message: 'Version Bump by fastlane',
    force: true
  )

  push_to_git_remote
end

def run_tests
  begin
    sh "xcodebuild test"
  rescue => ex
    puts ex
    raise "iOS Unit Tests failed:\n\n #{ex.to_s}"
  end
end

################
# All the lanes:
################

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "ca14a13e-c7da-4b5a-8941-95ba1f3da241"

default_platform :ios

# TODO: Get tests working
before_all do
  # run_tests
end

lane :analyze do
  analyze
end

desc "Submits new builds for both targets to Apple TestFlight"
lane :beta_all do
  sh "fastlane beta --env pgc"
  sh "fastlane beta --env pgm"
end

desc "Submits a new Beta Build to Apple TestFlight"
lane :beta do
  build_app('Release Staging API')

  # upload to Testflight
  pilot(
    skip_waiting_for_build_processing: true,
    app_identifier: ENV['APP_IDENTIFIER'],
    ipa: "#{ENV['SCHEME']}.ipa"
  )
end

desc "Deploys a new version to the App Store"
lane :release do
  # build_app('Release')

  frameit(white: true, path: "./fastlane/screenshots-#{ENV['APP']}")

  deliver(
    metadata_path: "fastlane/metadata-#{ENV['APP']}",
    screenshots_path: "fastlane/screenshots-#{ENV['APP']}",
    app_identifier: ENV['BUNDLE_ID'],
    ipa: "#{ENV['SCHEME']}.ipa",
    submit_for_review: true
  )
end

lane :refresh_dsyms do
  download_dsyms                  # Download dSYM files from iTC
  upload_symbols_to_crashlytics   # Upload them to Crashlytics
  clean_build_artifacts           # Delete the local dSYM files
end

lane :certificates do
  match(app_identifier: ["com.progolfme.app", "com.progolfme.coaches"], readonly: true)
end

lane :register_all_devices do
  register_devices(devices_file: "./fastlane/devices.txt")
  certificates
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["BUNDLE_ID"]
apple_id ENV["APPLE_ID"]
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.59.0  | ✅ Up-To-Date  |
| spaceship           | 0.38.5  | ✅ Up-To-Date  |
| cert                | 1.4.4   | ✅ Up-To-Date  |
| deliver             | 1.16.1  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| gym                 | 1.12.1  | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| pilot               | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.3.2   | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| snapshot            | 1.16.4  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.0.0        |
| bundler                    | 1.12.5       |
| io-console                 | 0.4.5        |
| CFPropertyList             | 2.3.4        |
| i18n                       | 0.7.0        |
| json                       | 1.8.3        |
| minitest                   | 5.10.1       |
| thread_safe                | 0.3.5        |
| tzinfo                     | 1.2.2        |
| activesupport              | 4.2.7.1      |
| public_suffix              | 2.0.4        |
| addressable                | 2.5.0        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| highline                   | 1.7.8        |
| commander                  | 4.4.1        |
| security                   | 0.1.3        |
| credentials_manager        | 0.16.2       |
| excon                      | 0.54.0       |
| gh_inspector               | 1.0.2        |
| multi_json                 | 1.12.1       |
| plist                      | 3.2.0        |
| rubyzip                    | 1.1.7        |
| terminal-table             | 1.4.5        |
| fastlane_core              | 0.59.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.10.0       |
| unf_ext                    | 0.0.7.2      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20161129 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.10.1       |
| fastimage                  | 1.6.8        |
| multi_xml                  | 0.6.0        |
| claide                     | 1.0.1        |
| clamp                      | 0.6.5        |
| fuzzy_match                | 2.0.4        |
| nap                        | 1.1.0        |
| cocoapods-core             | 1.1.1        |
| cocoapods-deintegrate      | 1.0.1        |
| cocoapods-downloader       | 1.1.2        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| netrc                      | 0.7.8        |
| cocoapods-trunk            | 1.1.1        |
| cocoapods-try              | 1.1.0        |
| escape                     | 0.0.4        |
| fourflusher                | 2.0.1        |
| molinillo                  | 0.5.4        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.4.1        |
| cocoapods                  | 1.1.1        |
| coderay                    | 1.1.1        |
| dotenv                     | 2.1.1        |
| mini_magick                | 4.5.1        |
| rouge                      | 1.11.1       |
| xcpretty                   | 0.2.4        |
| net-ssh                    | 3.2.0        |
| net-sftp                   | 2.1.2        |
| krausefx-shenzhen          | 0.14.11      |
| slack-notifier             | 1.5.1        |
| xcpretty-travis-formatter  | 0.0.4        |
| jwt                        | 1.5.6        |
| little-plugger             | 1.1.4        |
| logging                    | 2.1.0        |
| memoist                    | 0.15.0       |
| os                         | 0.9.6        |
| signet                     | 0.7.3        |
| googleauth                 | 0.5.1        |
| httpclient                 | 2.8.3        |
| hurley                     | 0.2          |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| uber                       | 0.0.15       |
| representable              | 2.3.0        |
| retriable                  | 2.1.0        |
| google-api-client          | 0.9.20       |
| terminal-notifier          | 1.7.1        |
| word_wrap                  | 1.0.0        |
| xcode-install              | 2.0.9        |
| fastlane-plugin-versioning | 0.2.5        |
| method_source              | 0.8.2        |
| mini_portile2              | 2.1.0        |
| nokogiri                   | 1.6.8.1      |
| slop                       | 3.6.0        |
| pry                        | 0.10.4       |
| slather                    | 2.3.0        |
</details>

*generated on:* **2016-12-12**
</details>

**Comment by hjanuschka** [comment]
@samphilipd size is determed by `fastimage` gem.

can you quickly check if the source image is correct

in a shell
```bash
file "fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator Screen Shot 24 Aug 2016, 16.24.41_framed.png"
```


ohhh and during answering i saw the `,`  in the filename, maybe you try rename it first to some name without spaces and "," - like: `1_ipadPro_1.screen1.png`

**Comment by samphilipd** [comment]
@hjanuschka 

The source image certainly exists. I tried stripping special characters, now I see the same error, like so:

```
[!] Unsupported screen size [2286, 3168] for path 'fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator_Screen_Shot_24_Aug_2016__16.24.41_framed.png'
```

```
file 'fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator_Screen_Shot_24_Aug_2016__16.24.41_framed.png'
fastlane/screenshots-pgm/en-AU/1_ipadPro_1.Simulator_Screen_Shot_24_Aug_2016__16.24.41_framed.png: PNG image data, 2286 x 3168, 8-bit/color RGBA, non-interlaced
```

**Comment by KrauseFx** [comment]
Did you provide a Framefile? 

Taken from https://github.com/fastlane/fastlane/tree/master/frameit#usage

> When using frameit without titles on top, the screenshots will have the full resolution, which means they can't be uploaded to the App Store directly. They are supposed to be used for websites, print media and emails. Check out the section below to use the screenshots for the App Store.

**Comment by samphilipd** [comment]
@KrauseFx Ah, this fixed it. Somehow I missed that in the documentation before 🤔 . Thanks!
