### ISSUE TITLE
download certs and profiles for multiple app_identifier at once

### ISSUE THREAD

**Issue by tompson** [fastlane/fastlane#7434]
We have an iOS app with 4 extension, each with its special bundle identifier. 

In the my lane I included multiple match commands to fetch all the required certs and profiles like 

```desc "Deploy a new version to the App Store"
  lane :release do
    match(app_identifier: "my.company.app", type: "appstore", readonly: true)
    match(app_identifier: "my.company.app.extension1", type: "appstore", readonly: true)
    match(app_identifier: "my.company.app.extension2", type: "appstore", readonly: true)
    match(app_identifier: "my.company.app.watchapp", type: "appstore", readonly: true)
    match(app_identifier: "my.company.app.notifications", type: "appstore", readonly: true)    
    cocoapods
    gym 
  end
```

starting the whole match process 5 times for the build causes a lot of overhead - it would be nice to fetch the profiles for all identifiers in one step

**Comment by johnknapprs** [comment]
Does the multiple targets option not work for your situation? 

https://github.com/fastlane/fastlane/tree/master/match#multiple-targets

**Comment by tompson** [comment]
wow, somehow I overlooked that, looks like exactly what I was looking for
