### ISSUE TITLE
[sigh] Feature - change bundle ID while resign .ipa

### ISSUE THREAD

**Issue by AntonNix** [fastlane/fastlane#7435]
Hello, I'm trying to change bundle id in .ipa file and resign it. 
As I understand you documentation and try some variants -- I can't change bundle ID in a ipa file by resign. Maybe there is some action that can change bundle ID in ipa file not by sigh?

How should I solve this thing by fastlane?

Thank you.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12 (16A319)                     |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| fastlane_core       | 0.59.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| did_you_mean        | 1.0.0   |
| executable-hooks    | 1.3.2   |
| bundler-unload      | 1.0.2   |
| rubygems-bundler    | 1.4.4   |
| bundler             | 1.13.6  |
| io-console          | 0.4.5   |
| json                | 1.8.3   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.59.0  |
| excon               | 0.54.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| activesupport       | 4.2.7.1 |
| claide              | 1.0.1   |
| nanaimo             | 0.2.2   |
| xcodeproj           | 1.4.1   |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-12-12**
</details>

**Comment by NixSolutionsMobile** [comment]
Sorry for this maybe a bit primitive question, can any one give me some suggestion or tips about where I can find solution? Still even with 'fastlane actions' I can't find solution of this question.

Thank you.

**Comment by AntonNix** [comment]
Sorry for this maybe a bit primitive question, can any one give me some suggestion or tips about where can I find solution? Still even with 'fastlane actions' I can't find solution of this question.

Thank you.

**Comment by mgrebenets** [comment]
@AntonNix hey man, once you change bundle ID inside `Info.plist` you are changing the contents of the app bundle. Which effectively breaks the signature.

So if you can't rebuild your only option is to resign, which can be done with `sigh resign` command.
Whether you rebuild or resign, changing bundle ID means that you have to have signing identity and a provisioning profile and also ideally new entitlements file for that bundle ID - you can't rebuild or resign otherwise.

So let's say you have identity, profile and entitlements, you command would be like

```
fastlane sigh resign -i "Signing Identity Name" -e path/to/entitlements -p profile-for-new-bundle-id.mobileprovision my.ipa
```

if you have nested apps or extension, provide -p option multiple times for each bundle ID (see help)

if you don't have entitlements, use `--use-app-entitlements` option

**Comment by mgrebenets** [comment]
Since it's really a question and not an issue, I'll close it if you don't mind.

**Comment by AntonNix** [comment]
Thank you for your answer.
