### ISSUE TITLE
Issue on network with proxy

### ISSUE THREAD

**Issue by gcstang** [fastlane/fastlane#7438]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Network is unreachable when executing fastlane -v or -h or XX
Using the brew cask version of fastlane

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[/Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Network is unreachable - connect(2) for "kits-crashlytics-com.s3.amazonaws.com" port 443 (Errno::ENETUNREACH)
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:583:in `start'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:478:in `get_response'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:455:in `get'
	from /Users/myuser/.fastlane/bin/bundle_update_checker.rb:5:in `<main>']

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status  |
| ------------------- | ------- | -------------- |
| credentials_manager | 0.16.2  | 💥 Check failed |
| fastlane_core       | 0.59.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                 | Version |
| ------------------- | ------- |
| json                | 1.8.1   |
| multi_json          | 1.12.1  |
| highline            | 1.7.8   |
| colored             | 1.2     |
| commander           | 4.4.0   |
| excon               | 0.54.0  |
| rubyzip             | 1.1.7   |
| plist               | 3.2.0   |
| terminal-table      | 1.4.5   |
| gh_inspector        | 1.0.2   |
| security            | 0.1.3   |
| credentials_manager | 0.16.2  |
| fastlane_core       | 0.59.0  |
| i18n                | 0.7.0   |
| thread_safe         | 0.3.5   |
| tzinfo              | 1.2.2   |
| minitest            | 5.4.3   |
| activesupport       | 4.2.7.1 |
| CFPropertyList      | 2.3.4   |
| claide              | 1.0.1   |
| nanaimo             | 0.2.3   |
| xcodeproj           | 1.4.1   |
| bundler             | 1.13.6  |
| word_wrap           | 1.0.0   |
</details>

*generated on:* **2016-12-12**
</details>]

**Comment by AliakseiT** [comment]
Duplicate #7685
