### ISSUE TITLE
Select team before list device on register_devices.rb

### ISSUE THREAD

**Issue by damienmollard** [fastlane/fastlane#744]
I use an Apple ID which have 10 teams.

When I use register_devices, I pass team_id parameter but it's not used.

So, this line return an error asking to choose a team : 
https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/register_devices.rb#L33

Please could you use the team_id parameter to select to good team before listing device ?

Thank you

**Comment by KrauseFx** [comment]
Thanks, fixed with https://github.com/fastlane/fastlane/commit/663e9e26f1174d76564dcbc7581f10ef547de02f :+1: This will be in the next release
