### ISSUE TITLE
P12/Cer File encryption

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#746]
Currently I am using a custom script to decrypt and install my certificates onto travis, would be awesome if we could add a action that could do this for us. 

Is there a way I could contribute this? Or would you just suggest custom method in my fastfile.

**Comment by xfreebird** [comment]
Hi @jcampbell05, to create a new action you can do it by running:

```bash
fastlane new_action
```

You could get inspired from existing [actions](https://github.com/fastlane/fastlane/tree/master/lib/fastlane/actions) but you need some Ruby knowledge. 

To contribute to this project:
* fork this repository and put your new action to ```lib/fastlane/actions``` and an integration test to ```spec/actions_specs```
* run ```sudo gem install bundler rubocop; bundler install``` to setup the build enviornment
* check code styles with ```rubocop```
* run integration tests with ```rspec```

or also you could try https://github.com/fastlane/countdown .

**Comment by jcampbell05** [comment]
Cheers @xfreebird will do this :)

**Comment by KrauseFx** [comment]
Thanks @xfreebird :+1:
