### ISSUE TITLE
Use different frame colors for device in frameit

### ISSUE THREAD

**Issue by Sjoerdjanssenen** [fastlane/fastlane#7469]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'd love to see the possibility to select per screenshot which device frame color you'd like to use.

**Comment by dral3x** [comment]
Hi there,
a while ago I made a plugin that allows you to have more freedom with framed screenshot generation. It's a more customizable version of frameit, called *framer*.

Maybe you can take a look at it and see if it fits for needs
https://github.com/spreaker/fastlane-framer-plugin
