### ISSUE TITLE
Congratulations on being in top most active Github communities!

### ISSUE THREAD

**Issue by buger** [fastlane/fastlane#7470]
Hello there! 

Great work happening here! 
Last month fastlane project had over 400 active community members, which is higher than `rails`, `webpack` or even `react`. 

You can see your stats here:
https://ossmetrics.com/leaderboard
https://ossmetrics.com/fastlane/fastlane

Wish you a happy new year and continue to be awesome!

**Comment by KrauseFx** [comment]
Hey @buger, thanks for submitting this issue. Ironically I missed the notification for this, and didn't see it until now 👍 

OSSMetrics looks amazing, thanks for building it
