### ISSUE TITLE
gym export_options per lane

### ISSUE THREAD

**Issue by drosenstark** [fastlane/fastlane#7472]
I have these export_options in my gymfile

```
export_options(
    method: "ad-hoc",
    thinning: "<none>"
)
```

but I don't want them to apply to all of my lanes/schemes. How can use different export options for other lanes? 

I understand that I need to do this from the command line, but I can't figure out what exactly that means. Thanks!

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1108)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | ~/Downloads/BIG/Xcode8.app/Contents/Developer/                 |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.102.0"

default_platform :ios

platform :ios do
  before_all do
#      increment_build_number({
          #build_number: '11000'
          #build_number: latest_testflight_build_number + 1
#          build_number: Time.now.strftime("%Y%m%d%H%M")
#       })
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # carthage
    # you CANNOT put the increment build number stuff here, as it
    # will apply to a random target
  end

  lane :pro do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Pro'
      )
      gym(scheme: "Pro")
      deliver
  end

  desc "Deliver MIDI Designer Pro (Next), the Beta!"
  lane :next do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Pro (Next)'
      )
      gym(scheme: "Pro (Next)")
      deliver
  end

  lane :lite do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Lite'
      )
      gym(scheme: "Lite")
      deliver
  end

  desc "Build and deploy MD Limited"
  lane :limited do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Limited'
      )
      gym(scheme: "Limited")
      deliver
  end


#  desc "Deploy a new version to the App Store"
# try pilot
  lane :md77 do
      gym(scheme: "MD77")
      deliver
  end

  lane :clav do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'MDClav'
      )
      gym(scheme: "MDClav")
      deliver
  end

  lane :xg do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'MDXG'
      )
      gym(scheme: "MDXG")
      deliver
  end

  lane :xw do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'XW'
      )
      gym(scheme: "XW")
      deliver
  end

  lane :alpha do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Pro (Alpha)'
      )
      gym(
        scheme: "Pro (Alpha)"
      )
  end



  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end


  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "apple@dr2050.com" # Your Apple email address
team_id "6FKVWU2G7X"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
for_platform :ios do
  for_lane :next do
    app_identifier "com.confusionstudios.MidiDesignerNext" # The bundle identifier of your app
  end
  for_lane :lite do
    app_identifier "com.confusionists.MidiDesignerFree" # The bundle identifier of your app
  end
  for_lane :limited do
    app_identifier "com.confusionists.MidiDesignerTwelve" # The bundle identifier of your app
  end
  for_lane :md77 do
    app_identifier "com.confusionstudios.mdtg" # The bundle identifier of your app
  end
  for_lane :pro do
    app_identifier "com.confusionists.MidiDesigner" # The bundle identifier of your app
  end
  for_lane :clav do
    app_identifier "com.confusionstudios.mdclav" # The bundle identifier of your app
  end
  for_lane :xg do
    app_identifier "com.confusionstudios.mdxg" # The bundle identifier of your app
  end
  for_lane :xw do
    target "xw"
    app_identifier "com.confusionists.MidiDesignerXW" # The bundle identifier of your app
  end
end
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| snapshot            | 1.16.4  | 🚫 Update availaible |
| frameit             | 3.0.0   | ✅ Up-To-Date        |
| pem                 | 1.4.0   | 🚫 Update availaible |
| cert                | 1.4.4   | 🚫 Update availaible |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.1   | 🚫 Update availaible |
| pilot               | 1.12.1  | 🚫 Update availaible |
| scan                | 0.14.2  | ✅ Up-To-Date        |
| supply              | 0.8.0   | ✅ Up-To-Date        |
| match               | 0.11.0  | 🚫 Update availaible |
| fastlane            | 1.111.0 | ✅ Up-To-Date        |
| fastlane_core       | 0.60.0  | ✅ Up-To-Date        |
| spaceship           | 0.38.5  | 🚫 Update availaible |
| deliver             | 1.16.1  | 🚫 Update availaible |
| gym                 | 1.13.0  | ✅ Up-To-Date        |
| screengrab          | 0.5.5   | 🚫 Update availaible |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version |
| -------------------------- | ------- |
| highline                   | 1.7.8   |
| commander                  | 4.4.0   |
| terminal-table             | 1.4.5   |
| json                       | 1.8.3   |
| multipart-post             | 2.0.0   |
| faraday                    | 0.9.2   |
| faraday_middleware         | 0.10.0  |
| dotenv                     | 2.1.1   |
| net-ssh                    | 3.2.0   |
| net-sftp                   | 2.1.2   |
| rubyzip                    | 1.1.7   |
| security                   | 0.1.3   |
| krausefx-shenzhen          | 0.14.11 |
| slack-notifier             | 1.5.1   |
| rouge                      | 1.11.1  |
| xcpretty                   | 0.2.4   |
| word_wrap                  | 1.0.0   |
| colored                    | 1.2     |
| credentials_manager        | 0.16.2  |
| fastimage                  | 1.6.8   |
| mini_magick                | 4.5.1   |
| xcpretty-travis-formatter  | 0.0.4   |
| i18n                       | 0.7.0   |
| thread_safe                | 0.3.5   |
| tzinfo                     | 1.2.2   |
| activesupport              | 4.2.7.1 |
| multi_json                 | 1.12.1  |
| gh_inspector               | 1.0.2   |
| fastlane_core              | 0.60.0  |
| excon                      | 0.54.0  |
| multi_xml                  | 0.5.5   |
| faraday-cookie_jar         | 0.0.6   |
| babosa                     | 1.0.2   |
| plist                      | 3.2.0   |
| xcode-install              | 2.0.8   |
| CFPropertyList             | 2.3.3   |
| claide                     | 1.0.1   |
| nanaimo                    | 0.2.2   |
| xcodeproj                  | 1.4.1   |
| bundler                    | 1.13.1  |
| fastlane-plugin-versioning | 0.2.5   |
</details>

*generated on:* **2016-12-13**
</details>

**Comment by drosenstark** [comment]
@fastlane-bot not a code signing issue. Just trying to figure out how to do this. Thx.

**Comment by KrauseFx** [comment]
You can use a `Fastfile`, and have multiple lanes there, where you call `gym` differently depending on the lane / environment 👍

**Comment by drosenstark** [comment]
Thanks @KrauseFx. I have lanes set up and use gym that way. The issue is how to get the export options into there. 

## This works (no export options at all)

```
  lane :alpha do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Pro (Alpha)'
      )
      gym(
        scheme: "Pro (Alpha)",
        output_directory: "/eraseme"
      )
  end
```

## This Fails due to syntax issues

```
  lane :alpha do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Pro (Alpha)'
      )
      gym(
        scheme: "Pro (Alpha)",
        output_directory: "/eraseme",
        export_options.method: "ad-hoc",
        export_options.thinning: "<none>"
      )
  end
```

## This Fails Also Due to Syntax Issues

```
  lane :alpha do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Pro (Alpha)'
      )
      gym(
        scheme: "Pro (Alpha)",
        output_directory: "/eraseme",
       export_options(method: "ad-hoc",thinning: "<none>")
      )
  end
```

I feel like I'm just a few characters away from the right syntax. 

Thanks for helping!

**Comment by drosenstark** [comment]
Okay, I can't figure out thinning, but from the errors I got to this

```
      gym(
        scheme: "Pro (Alpha)",
        output_directory: "/eraseme",
        export_method: "ad-hoc",
        include_bitcode: "no"
      )
```

which might be enough. Still testing.

**Comment by drosenstark** [comment]
Okay, that worked for me. I still don't understand WHERE I could find all this syntax and how to translate it between the gymfile, fastfile and the command line. But I'm solved for now

```
  lane :alpha do
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Pro (Alpha)'
      )
      gym(
        scheme: "Pro (Alpha)",
        output_directory: "/whatever",
        export_method: "ad-hoc",
        include_bitcode: "no",
        output_name: "alpha.ipa"
      )
  end
```
