### ISSUE TITLE
"Could not find app with app identifier" when init Mac project

### ISSUE THREAD

**Issue by chenyihu** [fastlane/fastlane#7480]
Spaceship::Application.find  

```ruby
def find(identifier, mac: false)
          all.find do |app|
            (app.apple_id == identifier.to_s || app.bundle_id == identifier) &&
              app.version_sets.any? { |v| v.platform == (mac ? "osx" : "ios") }
          end
end
```

and Deliver

detect_values.rb
```ruby
def find_app(options)
      search_by = options[:app_identifier]
      search_by = options[:app] if search_by.to_s.length == 0
      app = Spaceship::Application.find(search_by)  # <-----  Issue Here
      if app
        options[:app] = app
      else
        UI.user_error!("Could not find app with app identifier '#{options[:app_identifier]}' in your iTunes Connect account (#{options[:username]} - Team: #{Spaceship::Tunes.client.team_id})")
      end
end
```

`fastlane env`

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |
| fastlane_core       | 0.60.0  | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| pilot               | 1.13.1  | ✅ Up-To-Date  |
| gym                 | 1.13.0  | ✅ Up-To-Date  |
| produce             | 1.4.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

**Comment by chenyihu** [comment]
<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| highline                  | 1.7.8   |
| terminal-table            | 1.4.5   |
| json                      | 1.8.3   |
| dotenv                    | 2.1.1   |
| net-ssh                   | 3.2.0   |
| net-sftp                  | 2.1.2   |
| plist                     | 3.2.0   |
| security                  | 0.1.3   |
| krausefx-shenzhen         | 0.14.11 |
| slack-notifier            | 1.5.1   |
| colored                   | 1.2     |
| claide                    | 1.0.0   |
| xcodeproj                 | 1.3.0   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| bundler                   | 1.12.5  |
| credentials_manager       | 0.16.2  |
| fastimage                 | 1.6.8   |
| mini_magick               | 4.5.1   |
| xcpretty-travis-formatter | 0.0.4   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.12.1  |
| logging                   | 2.1.0   |
| memoist                   | 0.15.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| httpclient                | 2.8.2.4 |
| google-api-client         | 0.9.20  |
| excon                     | 0.54.0  |
| rubyzip                   | 1.1.7   |
| gh_inspector              | 1.0.2   |
| fastlane_core             | 0.60.0  |
| commander                 | 4.4.1   |
| io-console                | 0.4.5   |
| multi_xml                 | 0.5.5   |
| faraday-cookie_jar        | 0.0.6   |
| babosa                    | 1.0.2   |
</details>


*generated on:* **2016-12-14**
</details>

**Comment by hjanuschka** [comment]
@chenyihu thx for the report - in fact there is already PR for that: https://github.com/fastlane/fastlane/pull/7360

**Comment by dcordero** [comment]
This is also happening for tvOS in which the value for platform is "appletvos"

**Comment by chenyihu** [comment]
@hjanuschka Thank you very much!

**Comment by SemenovAlexander** [comment]
@hjanuschka 
I've also have related issue - `Could not find app with app identifier ` and `-j osx` doesn't fix it, because in current release that value goes nowhere.

Actually deliver now fails to do anything with Mac apps

Any news, when #7360 will be merged?

**Comment by hjanuschka** [comment]
hmmm - seems to work - as a workaround for others - maybe you +1 the #7360  so it will get a bit more attention
