### ISSUE TITLE
Build with gym is not support localization in application name 

### ISSUE THREAD

**Issue by auycro** [fastlane/fastlane#7481]
### Issue Description

When building project with gym, my application name don't support localization in app name.
(It works normally when I build application with Xcode)

Here is my project structure :
AppName
 |-Data
 |-Classes
 |-Frameworks
 |-Libraries
 |-en.lproj
 |-ja.lproj

I want to try adding this build flag in gym command but I don't know how to do this..
```
xcodebuild -exportLocalizations
```

Could you please suggest me how to add the support for localization name?

Thank you in advance!!

**Comment by hjanuschka** [comment]
you can try `xcargs: "-exportLocalizations"`  and/or `export_xcargs: "-exportLocalizations"` (used when exporting the archive)

**Comment by auycro** [comment]
Thank you for your comment @hjanuschka !! I will try this and report it again :)

**Comment by auycro** [comment]
I still cannot built my app to application with support localization name.
But the above solution is solved my question.
Thank you so much
