### ISSUE TITLE
match hangs on Cloning remote git repo...

### ISSUE THREAD

**Issue by parleer** [fastlane/fastlane#7482]
### Issue Description
Latest Match (0.11.1) doesn't work. Stuck on "Cloning remote git repo..."

My git repo is in ~/.ssh/known_hosts.

My keychain is unlocked.

git version 2.11.0

```
INFO [2016-12-14 02:43:48.70]: Cloning remote git repo...
INFO [2016-12-14 02:43:48.70]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@gitlab.mydomain.com:my-group/my-app-certificates.git' '/var/folders/lc/wjt2vfs50vsbd38_n8cp551h0000gn/T/d20161214-59866-xxnfgf'
INFO [2016-12-14 02:43:48.70]: ▸ Cloning into '/var/folders/lc/wjt2vfs50vsbd38_n8cp551h0000gn/T/d20161214-59866-xxnfgf'...

/opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane_core-0.60.0/lib/fastlane_core/command_executor.rb:65:in `wait': Interrupt
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane_core-0.60.0/lib/fastlane_core/command_executor.rb:65:in `ensure in block in execute'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane_core-0.60.0/lib/fastlane_core/command_executor.rb:65:in `block in execute'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane_core-0.60.0/lib/fastlane_core/command_executor.rb:46:in `spawn'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane_core-0.60.0/lib/fastlane_core/command_executor.rb:46:in `execute'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/match-0.11.1/lib/match/git_helper.rb:14:in `clone'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/match-0.11.1/lib/match/runner.rb:13:in `run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/match-0.11.1/lib/match/commands_generator.rb:53:in `block (3 levels) in run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/fastlane_core-0.60.0/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/match-0.11.1/lib/match/commands_generator.rb:119:in `run'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/match-0.11.1/lib/match/commands_generator.rb:12:in `start'
	from /opt/local/lib/ruby2.2/gems/2.2.0/gems/match-0.11.1/bin/match:6:in `<top (required)>'
	from /opt/local/bin/match:23:in `load'
	from /opt/local/bin/match:23:in `<main>'

```
**UPDATE:** Removed passphrase on ~/.ssh/id_rsa and still get same error.

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.6                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.11.0                          |
| Installation Source | /opt/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | /opt/local/lib                              |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

**Comment by parleer** [comment]
Got match working downgrading git to 2.10.2 and removing passphrase from ~/.ssh/id_rsa.

**Comment by emiliopavia** [comment]
I have the same issue and removing the passphrase doesn't seem a reasonable fix. Other suggestions? Thanks!

**Comment by parleer** [comment]
Figured it out...was on a new box and hadn't added my key to ssh-agent.

`ssh-add -K ~/.ssh/id_rsa`
