### ISSUE TITLE
How can I turnoff the password re-enter and just get the error when the password is incorrect?

### ISSUE THREAD

**Issue by LanfordCai** [fastlane/fastlane#7484]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I use produce to create a new app in iTC, if the password is incorrect, fastlane will ask for a new password. However, my script is running in a un-interactive terminal, so I want to skip the re-enter step and get an error. Is there a way to do this?

### Environment

fastlane version 1.111.0
OS: macOS 10.11.6

**Comment by hjanuschka** [comment]
did you set the ENV `FASTLANE_PASSWORD` to the right iTC password ?

**Comment by KrauseFx** [comment]
Could you share the complete output when doing that? You want fastlane to fail instead of asking for information on your non-interactive system, right? 
What CI system do you use? Make sure the environment variables for the CI are properly set (e.g. `CI`)
