### ISSUE TITLE
IPA not found (Travis integration)

### ISSUE THREAD

**Issue by mattiacantalu** [fastlane/fastlane#7485]
Hi guys,

Note: I use fastlane w/ travis integration and Xcode 8.1 on travis.

Since yesterday afternoon my builds encounter always same error:
**` File /var/folders/bb/xxx/T/gym_output20161214-1974-19sxfl4/APPNAME.ipa not found`**
`from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rubyzip-1.1.7/lib/zip/file.rb:96:in "new"
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/rubyzip-1.1.7/lib/zip/file.rb:96:in "open"
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/gym-1.13.0/lib/gym/xcodebuild_fixes/swift_fix.rb:90:in "zip_entries_matching"
	from /Users/travis/.rvm/gems/ruby-2.0.0-p648/gems/gym-1.13.0/lib/gym/xcodebuild_fixes/swift_fix.rb:82:in "check_for_swift"
[...]`

No fastlane changes from many days.. before yesterday all the things were ok.

**Local builds work perfectly.. seems travis issue with fastlane!**

Any ideas?

Thanks

**Comment by zemelenda** [comment]
I think I just watched this breaking change happen on my local system when I upgraded from gym 1.12.1 to gym 1.13.0. FWIW it also broke my Bamboo integration when we updated fastlane within the last 24 hours or so. Here's my local fastlane env output:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.2                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.2.2/bin/fastlane        |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.2.2/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.69.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods

  end

  desc "Build adhoc build"
  lane :adhoc_build do

  # Add a badge to the app icon
  version = "#{get_version_number}"

  # if there is "/" in the version number, replace it with "_"
  version = version.tr('/', '_')
  splitAry = version.split("-")

  puts("splitAry: #{splitAry}")
  # We expect vesion string looks like "3.10.2-IPH-1234" or "3.10.4-epic_IPH-1234"
  if splitAry.count >= 3
    #get the version at splitAry[0]
    version = splitAry.shift
    #join rest of array with "_"
    rest = splitAry*"_"
    badge(shield: "#{version}-#{rest}-blue", no_badge: true)
  elsif splitAry.count >= 2
    badge(shield: "#{splitAry[0]}-#{splitAry[1]}-blue", no_badge: true)
  end

  sigh(
    output_path: "~/Library/MobileDevice/Provisioning\ Profiles",
    skip_certificate_verification: true,
    app_identifier: "com.schoology.schoology",
    team_name: "Schoology, Inc",
    adhoc: true,
  )

  gym(
    use_legacy_build_api: true,
    export_method: "ad-hoc",
    workspace: "Schoology.xcworkspace",
    scheme: "Schoology",
    configuration: "Ad Hoc",
    output_name: "Schoology",
    output_directory: "./build/Products/Ad Hoc-iphoneos",
    disable_xcpretty: true,
    verbose: true,
    clean: true
  )

  end
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane_core       | 0.60.0  | ✅ Up-To-Date  |
| deliver             | 1.16.2  | ✅ Up-To-Date  |
| snapshot            | 1.17.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| cert                | 1.4.5   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.4.0   | ✅ Up-To-Date  |
| gym                 | 1.13.0  | ✅ Up-To-Date  |
| pilot               | 1.13.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| terminal-table            | 1.4.5        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.6.0        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.60.0       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
</details>


*generated on:* **2016-12-14**
</details>

**Comment by mattiacantalu** [comment]
`I think I just watched this breaking change happen on my local system when I upgraded from gym 1.12.1 to gym 1.13.0.`
Travis has sent to me a report too, detail below:

> I had a look and your build failure seems to have started at the same time Fastlane Gym 1.13 was released 2 days ago: https://github.com/fastlane/fastlane/releases/tag/gym%2F1.13.0. I see that your last successful build was using 1.12. Hence can you try to pin down the Gym version you are using in your build to 1.12 and see if it helps?

**Comment by jjrebollo** [comment]
I just figured a workaround out to use gym v1.12.1:

```
gem install gym -v "=1.12.1"
gem uninstall gym -v "=1.13.0"
```

After this, the latest gym version you are going to have in your machine will be 1.12.1, so this will be the one used.

This version is working for me just fine.

As said before, this is just a workaround. Looking forward to getting new releases that fix this issue.

**Comment by mattiacantalu** [comment]
Found a solution!
- Update fastlane to last version (`gem install fastlane`)
- Remove last gym version (`gem uninstall gym`)
- Install gym 1.12.1 (`gem install gym -v 1.12.1`)

_NOTE: if u install fastlane with sudo cmd, u must use sudo w/ other gem cmd too!_

**Comment by KrauseFx** [comment]
This is not fixed yet

**Comment by KrauseFx** [comment]
I just pushed a PR, we're trying to get a release out as soon as possible: https://github.com/fastlane/fastlane/issues/7526
