### ISSUE TITLE
No way to supply an app-specific password to pilot/deliver when running under CI

### ISSUE THREAD

**Issue by ben-lings-tessella** [fastlane/fastlane#7489]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver/Pilot support storing an app-specific password when run on the command line (see https://github.com/fastlane/fastlane/pull/4324). However, there isn't a way to specify the app-specific password via an environment variable when running on a CI server.  We use `FASTLANE_PASSWORD` and `FASTLANE_SESSION` which works for for `sigh`, but then when running `pilot`, it tries to use the same password and fails.

**Comment by jeffyoung** [comment]
Presumably on CI machines, we have to set FASTLANE_SESSION as well as  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD (see these [Fastlane docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth)).

**Comment by jeffyoung** [comment]
With a bit more detail [here](https://github.com/fastlane/fastlane/issues/7199).

**Comment by KrauseFx** [comment]
Hey @jeffyoung, this should actually work, and we published some improvements with the most recent release. Setting the `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` is the way to go for CIs. What's not working? Can you share some more information, and also the `fastlane env` output?

**Comment by KrauseFx** [comment]
Let's continue the discussion at https://github.com/fastlane/fastlane/issues/7199 👍

**Comment by KrauseFx** [comment]
Hey everyone, _fastlane_ now fully supports both two-factor and two-step verification 👋 

Please make sure to update to the latest version of _fastlane_ by running 

```
fastlane update_fastlane
```

If you use a `Gemfile`, just run `bundle update`

### On your computer 🚀
To use _fastlane_ with two-factor, just run _fastlane_ as you usually would. You'll be asked for the verification method, and a 4 or 6 digits pin. Everything will just work out of the box 📦 

### On your continuous integration system 💻 
Check out the [official two-factor docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth) for more information on how to setup two-step on CI system. You'll have to authenticate on your local machine to get a session cookie, which you then transfer to your CI.

----

If you have any issues setting this up, please submit [a new issue](https://github.com/fastlane/fastlane/issues/new) so we can help you get up and running 👍
