### ISSUE TITLE
Cannot resolve symbol 'Screengrab' and others

### ISSUE THREAD

**Issue by quetool** [fastlane/fastlane#7490]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

![captura de pantalla 2016-12-14 a las 11 57 56](https://cloud.githubusercontent.com/assets/14978705/21186886/d220c760-c1f4-11e6-868f-b7ba4e40a8de.png)

Dependencies in build.gradle
```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile 'com.android.support:support-annotations:25.0.1'
    androidTestCompile 'tools.fastlane:screengrab:0.5.6'
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.0.1'
    testCompile 'junit:junit:4.12'
}
```

That's all. I can not make screenshots because of that

**Comment by asfalcone** [comment]
@quetool Is this still an issue for you? If so, could you try doing a gradle sync or building via the command line and sharing any error output?

**Comment by quetool** [comment]
@asfalcone Hi, thanks for your interest! No, it is not an issue anymore! Sorry, I don not remember how I solved it! :(

**Comment by asfalcone** [comment]
Glad you're up and running. Going to close this out!
