### ISSUE TITLE
Inclusion of tvOS as supported platform

### ISSUE THREAD

**Issue by dcordero** [fastlane/fastlane#7491]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Even though Fastlane is working quite well with tvOS Applications, the fact is that tvOS is not yet part of the [supported platforms](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/supported_platforms.rb)

We have been actually [using Fastlane](https://github.com/fastlane/examples/pull/38) in our tvOS App, for months already, without any mayor issue. But the point is that we still lack the possibility to define tvOS as platform, as a first class citizen.

might it be, after a lot of work in actions and modules during the last months to support tvOS, the right moment to include it as one of the supported platform?  💪📺

**Comment by yonaskolb** [comment]
Are there any updates on this?

**Comment by KrauseFx** [comment]
Unfortunately we haven't had the time yet to go through the whole process and ensure tvOS works everywhere. We've had some contribution here and there around this recently, but never looked at the bigger picture for tvOS so far.

**Comment by KrauseFx** [comment]
Hey everyone, thanks for submitting this issue, great idea 🚀
Right now we’re super focused on making the best experience possible for iOS and Android mobile apps, so support for tvOS isn't on the immediate roadmap.
I'll close this issue for now, and will re-open it if that changes 👍

**Comment by yonaskolb** [comment]
Thanks for the reply Felix. Do you know what the remaining pieces left to do are, so that adding tvOS to the supported platforms would be a reasonable step?
As @dcordero says, it's working well and seems to be a valid platform already, it just can't be targeted by platform name
