### ISSUE TITLE
Hockey action shows wrong message

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7492]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am using `hockey` action to upload dsyms only by using `upload_dsym_only` option. When running the action the message displayed is `Starting with ipa upload to HockeyApp... this could take some time.` which is misleading in this case.

It would be nice if it would show message based on the `upload_dsym_only` option. 👍

**Comment by KrauseFx** [comment]
Sounds like it's not super important, feel free to submit a PR updating the wording to be more general, see [hockey.rb](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb#L68) 👍

**Comment by RishabhTayal** [comment]
submitted my first PR even though it's a working change! 👍 https://github.com/fastlane/fastlane/pull/7493
