### ISSUE TITLE
Error when trying to upload ipa to HockeyApp

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7495]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am getting the error `Error when trying to upload ipa to HockeyApp: ` while using the `hockey` action. Here is my `lane`.

```
lane :refresh_dsyms do
 hockey(
  api_token: 'MY-API-TOKEN',
  dsym: './xxx.app.dSYM.zip',
  upload_dsym_only: true,
  public_identifier: "com.example.bundleid"
 )
end
```

**Comment by KrauseFx** [comment]
You didn't share the complete output when running it

**Comment by RishabhTayal** [comment]
```
[12:45:59]: Running lane `ios refresh_dsyms`. Next time you can do this by directly typing `fastlane ios refresh_dsyms` 🚀.
[12:46:00]: Driving the lane 'ios refresh_dsyms' 🚀
[12:46:00]: --------------------
[12:46:00]: --- Step: hockey ---
[12:46:00]: --------------------
[12:46:00]: Starting with ipa upload to HockeyApp... this could take some time.
[12:46:03]: -------------------
[12:46:03]: --- Step: slack ---
[12:46:03]: -------------------
[12:46:03]: Successfully sent Slack notification
[12:46:03]: Variable Dump:
[12:46:03]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios refresh_dsyms"}
[12:46:03]: Error when trying to upload ipa to HockeyApp:  

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥    | hockey                              | 2           |
| 4    | slack                               | 0           |
+------+-------------------------------------+-------------+

[12:46:03]: fastlane finished with errors

[!] Error when trying to upload ipa to HockeyApp:  
```

**Comment by lyndsey-ferguson** [comment]
Is there anything more to the output? It seemed that it was ready to output the error. If you look at the [hockeyapp](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb) action, you'll see that it should output failures via the UI methods.

**Comment by lyndsey-ferguson** [comment]
Also, I find that it is helpful to either generate a bunch of log messages by using 'puts' right in the installed plugin, or get the pry-byebug gem, and add `require 'pry-byebug'` right to the plugin and a `byebug` statement in the run method to break in an interactive debugger.

**Comment by RishabhTayal** [comment]
That's the strange thing. This is the complete output. Earlier I was getting error saying I need to specify the `public_identifier`, the bundle identifier does not match with the one specified in Hockey. After I added the `public_identifier`, I got the above mentioned error.

**Comment by lyndsey-ferguson** [comment]
Interesting, I don't provide as much data as you do. Here is what I provide the `hockey` action:

```ruby

commits_to_this_commit = ENV.fetch('GIT_COMMIT') do
      `git rev-parse --verify HEAD`.strip
end

commits_from_that_commit = ENV.fetch('GIT_PREVIOUS_COMMIT') do
      `git rev-parse --verify #{commits_to_this_commit}~5`.strip
end

changelog_notes = changelog_from_git_commits(
      between: [commits_from_that_commit, commits_to_this_commit],
      include_merges: false,
      pretty: '%s (%h)'
)

hockey(
      api_token: options[:api_token],
      notes: changelog_notes,
      notes_type: '0',
      commit_sha: commits_to_this_commit
)
```

That works fine. Try that and add the other things that you want until it fails again? Failing that, I would definitely debug it interactively with `pry-byebug`.

**Comment by RishabhTayal** [comment]
it works for me if I use hockey action for uploading ipa. I think the issue is that my dSYM folder contains dSYM for pods as well. so while uploading the dSYM Hockey throws an error. 

How can we upload dSYM files if we use `pod`?

**Comment by lyndsey-ferguson** [comment]
I haven't uploaded dSYMs to hockey app. Can you upload that same file via the web interface without any errors?

**Comment by RishabhTayal** [comment]
Yes I am able to upload the same file manually through we interface. But adding through the `hockey` action fails.

**Comment by RishabhTayal** [comment]
I did some more research and looks like `Hockey.rb` is using `https://upload.hockeyapp.net/api/2/apps/upload` as the upload url. I called the same url from rest client and I get error while uploading dSYM. If I change the url to `https://upload.hockeyapp.net/api/2/apps/<APP-ID>/app_versions/upload` it works.

Do we need to change the url in `hockey` action? Do we need to ask for app id from user in order to upload dSYM?

I can contribute if I get these answers.

**Comment by lyndsey-ferguson** [comment]
If you modify your local `hockey.rb`, does the regular ipa upload work? If so, you may want to consider creating a pull request...

**Comment by RishabhTayal** [comment]
So the issue is **it does require app-id** in order to upload the dSYM. In the [docs](https://docs.fastlane.tools) the key says `public_identifier` which is misleading. Instead of `public_identifier` it should be `app_id` and we need to provide that id from Hockey dashboard **Not the bundle id**. We should change the docs so that it's more specific. Also need to change the key from `public_identifier` to `app_id`.

**Comment by RishabhTayal** [comment]
Created PR https://github.com/fastlane/docs/pull/214 to upload docs. Will also create PR to change the key.

**Comment by RishabhTayal** [comment]
Created PR https://github.com/fastlane/fastlane/pull/7498
