### ISSUE TITLE
APK output file path in `gradle` action is not computed correctly in all cases

### ISSUE THREAD

**Issue by kaoskorobase** [fastlane/fastlane#750]
In cases where the project is not named `app`, or when multiple product flavors and build types are used, the APK path generation is not correct:

~~~~
 apk_path = File.join("app", "build", "outputs", "apk", "app-#{flavor}.apk")
~~~~

In our case, the APK is at `locosonic-player/build/outputs/apk/locosonic-player-LocosonicPlayer-release.apk`, i.e. `${PROJECT_NAME}/build/outputs/apk/${PROJECT_NAME}-${PRODUCT_FLAVOR}-${BUILD_TYPE}.apk`. A solution might be to be able pass those parameters to the `gradle` action.

**Comment by KrauseFx** [comment]
Oh - stupid mistake on my side, thanks for letting me know!

**Comment by KrauseFx** [comment]
I'll push a new release later today :+1:

**Comment by kaoskorobase** [comment]
Thanks! Haven't tested yet, but I can see a few problems with this fix:

* The `app` directory and prefix might be called differently (see my initial bug report)
* I'm pretty sure that the parsing of `flavor` doesn't work with multiple product flavors and build types
* It only works reliably if there's only one APK in that directory; we're e.g. building two apps that end up there

**Comment by KrauseFx** [comment]
Interesting. Do you know if there is a way to reliable get the path to the just generated package? This should be seen as a sensible default value - you can always overwrite the path to the correct one in later steps.

**Comment by kaoskorobase** [comment]
I'm afraid I'm not aware of a reliable way to get the path to the APK. How do you overwrite the path, by setting `lane_context[SharedValues::APK_OUTPUT_PATH]` directly?

Maybe a cleaner solution could be to add an `apk_output_path` option to the `gradle` action and include a hint to that option in case automatic detection fails, i.e. when the expected apk is not produced by the call to `gradlew`?

**Comment by KrauseFx** [comment]
@kaoskorobase the easiest way is just to provide the path to the apk in the next action, e.g. `supply`

```ruby
supply(apk: "path/to/file.apk")
```

**Comment by asfalcone** [comment]
@kaoskorobase  this is fixed and will be available in the next release of fastlane! 🚀
