### ISSUE TITLE
[gym] Export of archive takes a LOT of time.

### ISSUE THREAD

**Issue by palusik86** [fastlane/fastlane#7505]
### Issue Description

Using `gym` and export method `ad-hoc` or `app-store` takes on our project 30 minutes or more on Jenkins., but manual archive of the same project, same settings but using xCode archive takes 1/4 of the time - using MacBook Pro late 2015 with i7.

As you will se below, export action took 26 minutes.

### Environment

Spec of Jenkins machine:
Mac Pro late 2013, Xeon E5 5 cores, 16 GB RAM, 512 SSD
MacOS: 10.12.1
Jenkins Version: 2.36
Xcode 8.1

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#
# Project spec. Necessary things go here
#

	default_device = "iPhone 6s"

	devices_tests_ab = [
		"iPad Pro (12.9 inch)",
		"iPad Pro (9.7 inch)",
		"iPad Air",
		"iPhone 6s Plus",
		"iPhone 6s",
		"iPhone 5s"
	]

	schemes_tests_ab = [ 
	]

	schemes_tests = [
		"DataTypes",
		"GUI",
		"SportFeedsIO",
		"Store",
		"AppStore",
		"UIReusable",
		"UIDataSources",
		"App"
	]

	project_path_name = "App/App.xcodeproj"
	workspace_name = "Main.xcworkspace"
	scheme_release = "App"
	crashlytics_local_path = "App/Vendors/Crashlytics.framework/"
	sonar_name = "iOS-App"
	default_config = "Release"

	#Signing details, please fill it always!
	provisioning_adhoc = "PROVISIONING_PROFILE_SPECIFIER=\"App Ad Hoc\""
	provisioning_release = "PROVISIONING_PROFILE_SPECIFIER=\"App App Store\""


#
# the end of needed things
#

platform :ios do
	desc "Before all do this:"
	before_all do
	   	unlock_keychain(path: "login.keychain-db",
	   					password: "password")
 	end

	desc "Upload on iTunes"
	lane :deploy do 
		name = scheme_release
		provisioning_profile = provisioning_release

		project_path = project_path_name
		build_number = number_of_commits

		increment_build_number(
			build_number: build_number,
			xcodeproj: project_path)
		
		build(export: "app-store",
			  provisioning: provisioning_profile)
		
		deliver(ipa: "#{name}.ipa",
				submit_for_review: false,
				skip_metadata: true,
				automatic_release: false,
				force: true)
	end

	desc "Run unit tests"
	lane :test do
		schemes = schemes_tests
		schemes.each do |scheme|
			test_generic(
				scheme:scheme,
				devices: [default_device])
		end
	end

	desc "Install all dependencies"
	lane :make do
		carthage(
			command: "bootstrap",
			platform: "iOS",
			use_binaries: true)
	end

	desc "Run build for fabric"
	lane :fabric do

		build_number = number_of_commits
		project_path = project_path_name
		workspace = workspace_name
		scheme = scheme_release
		crashlytics_path = crashlytics_local_path
		provisioning_profile = provisioning_adhoc
		
		version_number = get_version_number(xcodeproj: project_path)
		git_tag = "CI/v#{version_number}/##{build_number}"

		m_build_number = "Build number: #{build_number}"
		m_build_branch = "Branch: #{git_branch}"
		m_build_commit = "Commit: #{last_git_commit[:abbreviated_commit_hash]}"
		m_groups = ENV["CRASHLYTICS_GROUPS"]
		m_comments = ENV["CRASHLYTICS_NOTES"]
		
		message = [
			m_build_number,
			m_build_branch,
			m_build_commit,
			"GIT TAG: #{git_tag}",
			"Groups: #{m_groups}",
			"Release Notes: #{m_comments}"
		]
		.join("\n")

		increment_build_number(
			build_number: build_number,
			xcodeproj: project_path)

		build(export: "ad-hoc", 
			  provisioning: provisioning_profile)

		crashlytics(
			crashlytics_path: "#{crashlytics_path}",
			api_token: "xxxxx",
			build_secret: "xxxxxx",
			notes: "#{message}",
			groups: m_groups)

		if !git_tag_exists(tag: git_tag)
			add_git_tag(tag: git_tag)
			push_git_tags
		end

		slackNotifier(message: message)
	end

	desc "Run metrics for all project modules"
	lane :metrics do
		schemes = schemes_tests
		schemes.each do |scheme|
			metrics_generic(
				scheme: scheme,
				devices: default_device)
		end
	end

	desc "Run all AB Tests"
	private_lane :test_ab do
		devices = devices_tests_ab
		schemes = schemes_tests_ab

		schemes.each do |scheme|
			test_generic(
				scheme:scheme,
				devices:devices)
		end
	end

	desc "Build project"
	private_lane :build do |options|
		cleanAll

		export = options[:export]
		provisioning = options[:provisioning]
		workspace = workspace_name
		scheme = scheme_release
		config = default_config

		gym(workspace: workspace,
			scheme: scheme,
			configuration: config,
			include_bitcode: false,
			export_method: export,
			clean: true,
			output_name: "#{scheme}.ipa")
	end

	desc "Run metrics for selected scheme in project"
	private_lane :metrics_generic do |options|

		scheme = options[:scheme]
		devices = options[:devices]
		project_path = project_path_name
		workspace = workspace_name
		crashlytics_path = crashlytics_local_path
		project_name = sonar_name

		test_generic(
			scheme:scheme,
			devices:devices)

		slather(
			workspace: "#{workspace}",
			scheme: "#{scheme}",
			proj: "#{scheme}/#{scheme}.xcodeproj",
			cobertura_xml: true,
			jenkins: true,
			build_directory: "./build/#{scheme}.DerivedData",
			output_directory: "./build/#{scheme}.reports/")
		sh("cd .. && lizard ./#{scheme}/ -l swift --xml > ./build/#{scheme}.reports/lizard-report.xml")

		swiftlint(output_file: "./build/#{scheme}.reports/swiftlint.txt", ignore_exit_status: true)

		sonar_parameters = [
			"sonar.projectKey=#{project_name}.#{scheme}",
			"sonar.projectName=#{project_name}.#{scheme}",
			"sonar.junit.reportsPath=build/#{scheme}.reports",
			"sonar.junit.include=*.junit",
			"sonar.sources=#{scheme}/#{scheme}",
			"sonar.tests=#{scheme}/#{scheme}Tests",
			"sonar.swift.lizard.report=build/#{scheme}.reports/lizard-report.xml",
			"sonar.swift.coverage.reportPattern=build/#{scheme}.reports/cobertura.xml",
			"sonar.swift.swiftlint.report=build/#{scheme}.reports/*swiftlint.txt",
			"sonar.swift.workspace=#{workspace}",
			"sonar.swift.project=#{scheme}/#{scheme}.xcodeproj"
		]

		final_sonar_parameters = "-D" + sonar_parameters.join(" -D")

		sonar(
			project_key:"#{project_name}.#{scheme}",
			project_name:"#{project_name}.#{scheme}",
			sonar_runner_args: final_sonar_parameters)
	end

    desc "Runs unit tests for selected scheme"
	private_lane :test_generic do |options|

		scheme = options[:scheme]
		devices = options[:devices]

		scan(
			scheme: scheme,
			code_coverage: true,
			clean: true,
			devices: devices,
			derived_data_path: "./build/#{scheme}.DerivedData",
			output_directory: "./build/#{scheme}.reports/")
	end

	private_lane :cleanAll do 
		workspace = workspace_name
		scheme = scheme_release

		xcclean(workspace:  workspace_name,
	      		scheme: scheme)

		clear_derived_data
	end

	private_lane :slackNotifier do |options|
		message = options[:message]
		slack(
			slack_url: "https://hooks.slack.com/services/xxxx",
			channel: "xxxxi",
			message: "#{message}")
	end


	desc "Called on error"
	error do |lane, exception, options|
		slackNotifier(message: exception)	
	end
end
```
</details>
**No Appfile found**
### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane_core       | 0.60.0  | ✅ Up-To-Date  |
| deliver             | 1.16.2  | ✅ Up-To-Date  |
| snapshot            | 1.17.0  | ✅ Up-To-Date  |
| frameit             | 3.0.0   | ✅ Up-To-Date  |
| pem                 | 1.4.1   | ✅ Up-To-Date  |
| cert                | 1.4.5   | ✅ Up-To-Date  |
| sigh                | 1.12.1  | ✅ Up-To-Date  |
| produce             | 1.4.0   | ✅ Up-To-Date  |
| gym                 | 1.13.0  | ✅ Up-To-Date  |
| pilot               | 1.13.1  | ✅ Up-To-Date  |
| scan                | 0.14.2  | ✅ Up-To-Date  |
| supply              | 0.8.0   | ✅ Up-To-Date  |
| match               | 0.11.1  | ✅ Up-To-Date  |
| screengrab          | 0.5.6   | ✅ Up-To-Date  |
| fastlane            | 1.111.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.6        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.6.0        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.60.0       |
| fastimage                 | 1.6.8        |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
</details>
*generated on:* **2016-12-15**
</details>

##### Fastlane output

```
[13:35:03]: ▸ Touching App.app
[13:37:09]: ▸ Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/Main-dxwovjwuwgnfzygmrpkrhcvwkesr/Build/Intermediates/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.com.app
[13:37:36]: ▸ Touching App.app.dSYM
[13:37:37]: ▸ Archive Succeeded
[13:37:37]: Generated plist file with the following values:
[13:37:37]: ▸ -----------------------------------------
[13:37:37]: ▸ {
[13:37:37]: ▸   "method": "ad-hoc"
[13:37:37]: ▸ }
[13:37:37]: ▸ -----------------------------------------
[13:37:37]: $ /usr/bin/xcrun /Users/jenkins/.rvm/gems/ruby-2.3.1/gems/gym-1.13.0/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/q1/45d0dl9x52g0p0r2rq9ld3680000gn/T/gym_config20161215-45654-18u2704.plist' -archivePath /Users/jenkins/Library/Developer/Xcode/Archives/2016-12-15/App\ 2016-12-15\ 13.17.52.xcarchive -exportPath '/var/folders/q1/45d0dl9x52g0p0r2rq9ld3680000gn/T/gym_output20161215-45654-pz12s5' 
[14:03:54]: Compressing 32 dSYM(s)
[14:03:54]: $ cd '/Users/jenkins/Library/Developer/Xcode/Archives/2016-12-15/App 2016-12-15 13.17.52.xcarchive/dSYMs' && zip -r '/Users/jenkins/.jenkins/jobs/Mobile-iOS-App-Develop/workspace/App.app.dSYM.zip' *.dSYM
```

**Comment by neldridge** [comment]
I recently had an issue with my build times increasing with each run; I'd suggest checking your keychain search path from the command line. 

`security list-keychains`

I was using `unlock_keychain`, and every time it ran, it would add my login keychain to the search path.

Before I found the problem, my build was taking over 2 hours. It was due to codesigning looping through each search path entry to do the codesigning.


and try `security find-identity`

I resolved the issue by adding the add_to_search_list to my unlock_keychain call.
```
		unlock_keychain(
			path: "login.keychain",
			add_to_search_list: :replace,
			password: ENV['FASTLANE_PASSWORD']
		)
```

**Comment by palusik86** [comment]
@neldridge Thank you for that, I've checked list of key chains and look like this:
```
    "/Users/jenkins/Library/Keychains/login.keychain-db"
    "/Users/jenkins/Library/Keychains/login.keychain-db"
    "/Users/jenkins/Library/Keychains/login.keychain-db"
    "/Users/jenkins/Library/Keychains/login.keychain-db"
    "/Users/jenkins/Library/Keychains/login.keychain-db"
    "/Users/jenkins/Library/Keychains/login.keychain-db"
    "/Users/jenkins/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
```

So I have to remove those duplicate ones in list ?

**Comment by neldridge** [comment]
Look for `unlock_keychain`  in your Fastfile (or maybe it's a config option in Jenkins?), and add the parameter below- fastlane will remove the duplicates by itself, and resolve the issue.

```
add_to_search_list: :replace
```

**Comment by palusik86** [comment]
Ok now I know what to do. `Fastlane action unlock_keychain` does no share that knowledge with me ;)
I will test it, once again thank you for help.

**Comment by neldridge** [comment]
@KrauseFx is this a known issue? 

It may be worth changing the default behavior of `unlock_keychain`; I would think the expected behavior would be `:replace` - not adding the same keychain to the search path with every execution.

**Comment by KrauseFx** [comment]
Hey, I don't have enough background information about this. What kinds of setups does this affect? What would we change? Would that have any side effects? Would that break any existing setups?

**Comment by hjanuschka** [comment]
this could only happen if the keychain to be unlocked could not be found in the current listed keychains. (https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/unlock_keychain.rb#L35)


but even if triggered - the code executed then is exact the same as with `:replace`

@milch could that be related to the `FastlaneCore::Helper.keychain_path`  i could'nt reproduce it.
setting `:path`  to a full path or even setting it to just the filename (as initial issue reporter did)

**Comment by neldridge** [comment]
@hjanuschka 

Hi Helmut,

I am able to reproduce this with a new project directory and fastfile. What is the default expected behavior here? It sounds like the default behavior is `:replace`

Fastlane version: 2.1.1
OS X version: 10.12.1

Fastfile contents
```
skip_docs
opt_out_usage
fastlane_version "2.0.0"

default_platform :ios

platform :ios do

	lane :test_unlock do
		unlock_keychain(
			path: "login.keychain",
		)
	end
end
```

Commands to reproduce

```
iosbuilder:test-fastlane iosbuilder$ security list-keychains
    "/Users/iosbuilder/Library/Keychains/login.keychain-db"
    "/Users/iosbuilder/Library/Keychains/login.keychain-db"
    "/Users/iosbuilder/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
iosbuilder:test-fastlane iosbuilder$ fastlane
[08:52:41]: ---------------------------
[08:52:41]: --- Step: opt_out_usage ---
[08:52:41]: ---------------------------
[08:52:41]: Disabled upload of used actions
[08:52:41]: -------------------------------------------------
[08:52:41]: --- Step: Verifying required fastlane version ---
[08:52:41]: -------------------------------------------------
[08:52:41]: Your fastlane version 2.1.1 matches the minimum requirement of 2.0.0  ✅
[08:52:41]: ------------------------------
[08:52:41]: --- Step: default_platform ---
[08:52:41]: ------------------------------
[08:52:41]: Welcome to fastlane! Here's what your app is setup to do:
+--------+-----------------+------------------------------+
|                 Available lanes to run                  |
+--------+-----------------+------------------------------+
| Number | Lane Name       | Description                  |
+--------+-----------------+------------------------------+
| 1      | ios test_unlock |                              |
| 0      | cancel          | No selection, exit fastlane! |
+--------+-----------------+------------------------------+
Which number would you like run?
1
[08:52:44]: Running lane `ios test_unlock`. Next time you can do this by directly typing `fastlane ios test_unlock` 🚀.
[08:52:44]: Driving the lane 'ios test_unlock' 🚀
[08:52:44]: -----------------------------
[08:52:44]: --- Step: unlock_keychain ---
[08:52:44]: -----------------------------
[08:52:44]: To not be asked about this value, you can specify it using 'password'
Keychain password: **************

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | unlock_keychain                     | 3           |
+------+-------------------------------------+-------------+

[08:52:47]: fastlane.tools finished successfully 🎉
iosbuilder:test-fastlane iosbuilder$ security list-keychains
    "/Users/iosbuilder/Library/Keychains/login.keychain-db"
    "/Users/iosbuilder/Library/Keychains/login.keychain-db"
    "/Users/iosbuilder/Library/Keychains/login.keychain-db"
    "/Users/iosbuilder/Library/Keychains/login.keychain-db"
    "/Library/Keychains/System.keychain"
```


Please let me know if there's anything else I can help with.

-Nick

**Comment by milch** [comment]
@hjanuschka Don't worry, I'm able to reproduce it - could be related to the change, could be that it's something that only happens on Sierra. I'll take a look.

@neldridge Thanks for the detailed report! I was able to quickly reproduce it using 

```
$ security list-keychains
    ".../login.keychain-db"
    ".../System.keychain"
$ fastlane run unlock_keychain path:"login.keychain" password:$KEYCHAIN_PASSWORD
[10:48:35]: -----------------------------
[10:48:35]: --- Step: unlock_keychain ---
[10:48:35]: -----------------------------
[10:48:35]: Result: ["", "", ""]
$ security list-keychains
    ".../login.keychain-db"
    ".../login.keychain-db"
    ".../System.keychain"
```

**Comment by neldridge** [comment]
@milch No problem, glad I can help out. good you know you can run functions in fastlane like that also, thanks :) 


fwiw, I had this issue before upgrading to fastlane version 2. (which makes sense in the context that no code changes were made, only the conversion to a monogem).

Let me know if there's anything else I can help with.

**Comment by hjanuschka** [comment]
@milch ohh nice to hear you can reproduce, seeing your output i think the problem is that list-keychains return's ".." in the path - which does not match the `include?`  in https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/unlock_keychain.rb#L35

in my case list-keychains reports full-resolved paths. strange!

**Comment by milch** [comment]
@hjanuschka Oh sorry for the confusion, the `...` were just put in by me to get rid of the full path.

**Comment by hjanuschka** [comment]
@milch  oh well - i thought that might be the problem - let me know if can help in any way to tackle this.

**Comment by milch** [comment]
@hjanuschka Thanks, will do! 

In an attempt to reproduce this on my work computer this morning, I suddenly wasn't able to anymore! The only difference between this one and my personal laptop (where I was able to repro it) I can think of is that this one had a fresh install of Sierra, while my personal one was upgraded from ElCap. I'll take a look at it again tonight when I get home!

**Comment by neldridge** [comment]
As a note, my machines are upgraded from ElCap to Sierra.

**Comment by palusik86** [comment]
> As a note, my machines are upgraded from ElCap to Sierra.

Same story with my CI machine.
