### ISSUE TITLE
Import shell scripts with Fastfile from another repo

### ISSUE THREAD

**Issue by AndrewSB** [fastlane/fastlane#7510]
I'm trying to import a Fastfile from one repo to another, and I'm running into an issue.

I have the Fastfile I'd like to import in this repo https://github.com/AndrewSB/fastlane, and the shell script included in the directory.
When I run `fastlane bootstrap`, a command that tries to run the shell script (see output of command [here](https://circleci.com/gh/AndrewSB/wrytr/8)), fastlane errors out saying the script doesn't exist.

The app I'm trying to get this to work for is here: GitHub.com/AndrewSB/wrytr
How can I share the shell script from AndrewSB/fastlane along with the Fastfile?

**Comment by KrauseFx** [comment]
Sorry that's currently not natively support by _fastlane_, however you can easily build that yourself as part of your `Fastfile` using the `download` action, or directly using `wget` or `curl` 👍
