### ISSUE TITLE
Raise if conflict fastlane_core-0.58.0

### ISSUE THREAD

**Issue by cuongta** [fastlane/fastlane#7517]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm getting this error after upgrading to the latest fastlane version. I've done gem cleanup and there seems to be conflicts. The lane I ran was `fastlane test_badge`

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
[15:11:57]: -------------------
[15:11:57]: --- Step: badge ---
[15:11:57]: -------------------
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios test_badge |
+------------------+----------------+

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | pod install                         | 7           |
| 4    | badge                               | 0           |
+------+-------------------------------------+-------------+

[15:11:57]: fastlane finished with errors
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate fastlane_core-0.58.0, because rubyzip-1.2.0 conflicts with rubyzip (~> 1.1.6) (Gem::ConflictError)
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `each'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1428:in `activate_dependencies'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1410:in `activate'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:220:in `rescue in try_activate'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:213:in `try_activate'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/actions/badge.rb:7:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:225:in `block (2 levels) in execute_action'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:210:in `block in execute_action'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:209:in `chdir'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:209:in `execute_action'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:131:in `trigger_action_by_name'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:37:in `block (2 levels) in parsing_binding'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/cli_tools_distributor.rb:60:in `take_off'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.2/bin/fastlane:5:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/bin/fastlane:22:in `load'
	from /usr/local/var/rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'
exit 1
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12                                            |
| Ruby                | 2.3.1                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.7.2                                |
| Installation Source | /usr/local/var/rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12 (16A323)                          |
| Ruby Lib Dir        | /usr/local/var/rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                       |
| Is contained        | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.1                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.49.0"

default_platform :ios

platform :ios do
    before_all do
        sh 'pod install'
        # increment_build_number
        # xctool # run the tests of your app
    end

    desc "Build the project"
    lane :test_badge do
        badge(custom: "AppIcon.png")
    end

end

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of your app
apple_id "XXXX@XYZ.com" # Your Apple email address

team_id "XXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane            | 2.0.2   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.0        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.6        |
| io-console                | 0.4.6        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2016-12-15**
</details>

**Comment by KrauseFx** [comment]
Hey @cuongta, thanks for submitting the issue. I submitted a PR to the plugin's repo yesterday with https://github.com/HazAT/badge/pull/36, we'll just have to wait for a new release by @HazAT 👍

**Comment by HazAT** [comment]
Hey
Just released version `0.7.0` ... please update and the problem should be resolved.

**Comment by HazAT** [comment]
@KrauseFx @hjanuschka 
Also released a fastlane plugin now ... so the old badge action could be removed
https://github.com/HazAT/fastlane-plugin-badge

**Comment by nicolasbraun** [comment]
I updated to 0.7 and have the same issue with another gem @HazAT 

`/Users/slave/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate badge-0.7.0, because fastimage-2.0.1 conflicts with fastimage (~> 1.6) (Gem::ConflictError)`

**Comment by HazAT** [comment]
@nicolasbraun 
I just pushed `0.7.1` could you try to update ... added open end dependency now.

**Comment by KrauseFx** [comment]
Oh yeah

**Comment by cuongta** [comment]
@KrauseFx @HazAT Works now. thanks!
