### ISSUE TITLE
Circular dependency between fastlane and deliver.

### ISSUE THREAD

**Issue by shammatime** [fastlane/fastlane#7519]
We started getting this error earlier today and am not sure how to solve the problem.

The command run 'bundle exec update'

Output:
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove either gem 'deliver' or gem 'fastlane' and try again.

Our Gemfile :
source "https://rubygems.org"

gem 'fastlane' , '1.111.0'
gem 'curb'
gem 'rubyzip' , '1.1.7'
gem 'cocoapods' , '1.1.1'

We do not want to update to 2.0.2. Any help would be great.

**Comment by milch** [comment]
@shammatime You should upgrade to 2.0.2 to fix this issue or you won't get future updates for version 1. There are minimal breaking changes for our users (other than how the gem and internal dependencies are structured), so the change should be seamless. 

Barring that you would need to pin the deliver version in your Gemfile to `1.16.2`, which was the last version that supported fastlane `1.x`.

Let me know if you have any further problems.

**Comment by KrauseFx** [comment]
Is there any specific reason why you don't want to update to 2.0?

**Comment by shammatime** [comment]
We tried 2.0.2 and having issues with gym in 2.0.2. Here is our error:
bundler: failed to load command: fastlane (/private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/bin/fastlane)
20:07:05 Zip::Error: [31m[!] File /var/folders/q8/ntxbg8dn2cv3jmdrbxbd6w3c0000gq/T/gym_output20161215-30066-hkixcp/IonicIosSdk.ipa not found[0m
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:85:in `initialize'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `new'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/rubyzip-1.2.0/lib/zip/file.rb:99:in `open'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/gym/lib/gym/xcodebuild_fixes/swift_fix.rb:90:in `zip_entries_matching'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/gym/lib/gym/xcodebuild_fixes/swift_fix.rb:82:in `check_for_swift'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/gym/lib/gym/xcodebuild_fixes/swift_fix.rb:15:in `swift_library_fix'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/gym/lib/gym/runner.rb:94:in `fix_package'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/gym/lib/gym/runner.rb:20:in `run'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/gym/lib/gym/manager.rb:14:in `work'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:225:in `block (2 levels) in execute_action'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:210:in `block in execute_action'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:209:in `chdir'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:209:in `execute_action'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:131:in `trigger_action_by_name'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
20:07:05   Fastfile:156:in `block (2 levels) in parsing_binding'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/lane.rb:33:in `call'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:184:in `try_switch_to_lane'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
20:07:05   Fastfile:126:in `block (2 levels) in parsing_binding'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/lane.rb:33:in `call'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/fastlane/lib/fastlane/cli_tools_distributor.rb:60:in `take_off'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/gems/fastlane-2.0.2/bin/fastlane:5:in `<top (required)>'
20:07:05   /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load


We have not changed any of our build scripts between 1.111.0. Not sure whats up.

**Comment by KrauseFx** [comment]
@shammatime would you mind sharing your configuration files using `fastlane env`?

**Comment by shammatime** [comment]
12:17:04 [12:17:04]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
12:17:06 <details><summary>??? fastlane environment ???</summary>
12:17:06 
12:17:06 ### Stack
12:17:06 
12:17:06 | Key                 | Value                                                                                                            |
12:17:06 | ------------------- | ---------------------------------------------------------------------------------------------------------------- |
12:17:06 | OS                  | 10.11.6                                                                                                          |
12:17:06 | Ruby                | 2.3.1                                                                                                            |
12:17:06 | Bundler?            | true                                                                                                             |
12:17:06 | Git                 | git version 2.9.3 (Apple Git-75)                                                                                 |
12:17:06 | Installation Source | /private/tmp/workspace_build/workspace/MOBILE_READER_IOS_BUILD/I/IosReader/vendor/bundle/ruby/2.3.0/bin/fastlane |
12:17:06 | Host                | Mac OS X 10.11.6 (15G31)                                                                                         |
12:17:06 | Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib                                                                                 |
12:17:06 | OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                                                                                       |
12:17:06 | Is contained        | false                                                                                                            |
12:17:06 | Xcode Path          | /Applications/Xcode.app/Contents/Developer/                                                                      |
12:17:06 | Xcode Version       | 8.1                                                                                                              |
12:17:06 
12:17:06 
12:17:06 ### System Locale
12:17:06 
12:17:06 | Variable | Value       |   |
12:17:06 | -------- | ----------- | - |
12:17:06 | LANG     | en_us.UTF-8 | ??? |
12:17:06 | LC_ALL   |             |   |
12:17:06 | LANGUAGE |             |   |
12:17:06 
12:17:06 
12:17:06 ### fastlane files:
12:17:06 
12:17:06 <details><summary>`./fastlane/Fastfile`</summary>
12:17:06 
12:17:06 ```ruby
12:17:06 require 'curb'
12:17:06 
12:17:06 # This is the minimum version number required.
12:17:06 # Update this, if you use features of a newer version
12:17:06 fastlane_version "1.103.0"
12:17:06 
12:17:06
12:17:06 
12:17:06 ### fastlane gems
12:17:06 
12:17:06 | Gem                 | Version | Update-Status |
12:17:06 | ------------------- | ------- | ------------- |
12:17:06 | credentials_manager | 0.16.2  | ??? Up-To-Date  |
12:17:06 | spaceship           | 0.39.0  | ??? Up-To-Date  |
12:17:06 | fastlane            | 2.0.3   | ??? Up-To-Date  |
12:17:06 
12:17:06 
12:17:06 ### Loaded fastlane plugins:
12:17:06 
12:17:06 **No plugins Loaded**
12:17:06 
12:17:06 
12:17:06 <details><summary><b>Loaded gems</b></summary>
12:17:06 
12:17:06 | Gem                       | Version      |
12:17:06 | ------------------------- | ------------ |
12:17:06 | did_you_mean              | 1.0.0        |
12:17:06 | bundler                   | 1.13.6       |
12:17:06 | io-console                | 0.4.5        |
12:17:06 | CFPropertyList            | 2.3.4        |
12:17:06 | i18n                      | 0.7.0        |
12:17:06 | json                      | 1.8.3        |
12:17:06 | minitest                  | 5.10.1       |
12:17:06 | thread_safe               | 0.3.5        |
12:17:06 | tzinfo                    | 1.2.2        |
12:17:06 | activesupport             | 4.2.7.1      |
12:17:06 | public_suffix             | 2.0.4        |
12:17:06 | addressable               | 2.5.0        |
12:17:06 | babosa                    | 1.0.2        |
12:17:06 | claide                    | 1.0.1        |
12:17:06 | fuzzy_match               | 2.0.4        |
12:17:06 | nap                       | 1.1.0        |
12:17:06 | cocoapods-core            | 1.1.1        |
12:17:06 | cocoapods-deintegrate     | 1.0.1        |
12:17:06 | cocoapods-downloader      | 1.1.2        |
12:17:06 | cocoapods-plugins         | 1.0.0        |
12:17:06 | cocoapods-search          | 1.0.0        |
12:17:06 | cocoapods-stats           | 1.0.0        |
12:17:06 | netrc                     | 0.7.8        |
12:17:06 | cocoapods-trunk           | 1.1.1        |
12:17:06 | cocoapods-try             | 1.1.0        |
12:17:06 | colored                   | 1.2          |
12:17:06 | escape                    | 0.0.4        |
12:17:06 | fourflusher               | 2.0.1        |
12:17:06 | gh_inspector              | 1.0.2        |
12:17:06 | molinillo                 | 0.5.4        |
12:17:06 | nanaimo                   | 0.2.3        |
12:17:06 | xcodeproj                 | 1.4.1        |
12:17:06 | cocoapods                 | 1.1.1        |
12:17:06 | highline                  | 1.7.8        |
12:17:06 | commander                 | 4.4.1        |
12:17:06 | security                  | 0.1.3        |
12:17:06 | credentials_manager       | 0.16.2       |
12:17:06 | curb                      | 0.9.3        |
12:17:06 | unf_ext                   | 0.0.7.2      |
12:17:06 | unf                       | 0.1.4        |
12:17:06 | domain_name               | 0.5.20161129 |
12:17:06 | dotenv                    | 2.1.1        |
12:17:06 | excon                     | 0.54.0       |
12:17:06 | multipart-post            | 2.0.0        |
12:17:06 | faraday                   | 0.10.0       |
12:17:06 | http-cookie               | 1.0.3        |
12:17:06 | faraday-cookie_jar        | 0.0.6        |
12:17:06 | faraday_middleware        | 0.10.1       |
12:17:06 | fastimage                 | 2.0.1        |
12:17:06 | jwt                       | 1.5.6        |
12:17:06 | little-plugger            | 1.1.4        |
12:17:06 | multi_json                | 1.12.1       |
12:17:06 | logging                   | 2.1.0        |
12:17:06 | memoist                   | 0.15.0       |
12:17:06 | os                        | 0.9.6        |
12:17:06 | signet                    | 0.7.3        |
12:17:06 | googleauth                | 0.5.1        |
12:17:06 | httpclient                | 2.8.3        |
12:17:06 | hurley                    | 0.2          |
12:17:06 | mime-types-data           | 3.2016.0521  |
12:17:06 | mime-types                | 3.1          |
12:17:06 | uber                      | 0.0.15       |
12:17:06 | representable             | 2.3.0        |
12:17:06 | retriable                 | 2.1.0        |
12:17:06 | google-api-client         | 0.9.20       |
12:17:06 | mini_magick               | 4.5.1        |
12:17:06 | multi_xml                 | 0.6.0        |
12:17:06 | plist                     | 3.2.0        |
12:17:06 | rubyzip                   | 1.2.0        |
12:17:06 | slack-notifier            | 1.5.1        |
12:17:06 | terminal-notifier         | 1.7.1        |
12:17:06 | unicode-display_width     | 1.1.2        |
12:17:06 | terminal-table            | 1.7.3        |
12:17:06 | word_wrap                 | 1.0.0        |
12:17:06 | xcode-install             | 2.0.9        |
12:17:06 | rouge                     | 1.11.1       |
12:17:06 | xcpretty                  | 0.2.4        |
12:17:06 | xcpretty-travis-formatter | 0.0.4        |
12:17:06 </details>
12:17:06 
12:17:06 
12:17:06 *generated on:* **2016-12-16**

@KrauseFx Here is the fasltane env output. I removed our build scripts because I can't expose that information.

**Comment by sylvek** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                    |
| ------------------- | -------------------------------------------------------- |
| OS                  | 10.11.6                                                  |
| Ruby                | 2.1.0                                                    |
| Bundler?            | true                                                     |
| Git                 | git version 2.11.0                                       |
| Installation Source | /Volumes/local/permiloc-ios/.gem/ruby/2.1.0/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1212)                               |
| Ruby Lib Dir        | ~/.rbenv/versions/2.1.0/lib                              |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                               |
| Is contained        | false                                                    |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version       | 8.2                                                      |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# believe me, it's not a good option.
# If you want to automatically update fastlane if a new version is available:
# update_fastlane

fastlane_version "1.104.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end
  desc "Runs all the tests"
  lane :test do

    scan(scheme: "Notico-icTests",
      clean: true,
      device: "iPhone 7",
      code_coverage: true,
      output_directory: "sonar-reports",
      output_types: "junit,json-compilation-database",
      buildlog_path: "sonar-reports",
      derived_data_path: "sonar-reports",
      use_clang_report_name: true,
      custom_report_file_name: "TEST-report.xml",
      xcargs: "ONLY_ACTIVE_ARCH=YES"
    )
    slather(
      cobertura_xml: true,
      output_directory: "sonar-reports",
      proj: "Notico.xcodeproj",
      workspace: "Notico.xcworkspace",
      scheme: "Notico-ic",
      build_directory: "sonar-reports",
      binary_basename: "Notico-ic"
     )
    oclint(
      compile_commands: "sonar-reports/compile_commands.json",
      report_type: 'pmd',
      select_regex: /Notico/,
      max_priority_1: 10000,
      max_priority_2: 10000,
      max_priority_3: 10000,
      enable_clang_static_analyzer: false,
      allow_duplicated_violations: false,
      list_enabled_rules: true,
      report_path: "sonar-reports/oclint.xml",
      disable_rules: ["UseContainerLiteral", "UseObjectSubscripting", "MissingBreakInSwitchStatement", "MissingDefaultStatement", "UseNumberLiteral", "PreferEarlyExit", "UnnecessaryDefaultStatement"]
    )
    sonar
  end

  desc "Generate new version"
  lane :release do |options|
    unlock_keychain
    if options[:to_appaloosa]
      increment_build_number(build_number: get_build_number_from_appaloosa(group_name: "Notico", with_increment: true, app_identifier: "com.deveryware.notico-#{options[:build]}"))
    end
    if options[:to_store]
      #increment_build_number(build_number: latest_testflight_build_number + 1)
    end
    if options[:build_number]
      increment_build_number(build_number: options[:build_number])
    end

    current_version_number = get_version_number(xcodeproj: "./Notico.xcodeproj", target:"Notico")
    File.open('current_version_number', 'w') { |file| file.write(current_version_number) }

    app_identifier = (options[:to_appaloosa]) ? "com.deveryware.notico-#{options[:build]}" : "com.deveryware.notico"
    scheme = (options[:to_appaloosa]) ? "Notico-#{options[:build]}" : "Notico"
    output_name = (options[:to_appaloosa]) ? "notico-#{options[:build]}.ipa" : "notico.ipa"

    sigh(adhoc: !options[:to_store], skip_install: true, app_identifier: app_identifier)
    gym(scheme: scheme, use_legacy_build_api: true, output_name: output_name, codesigning_identity: "iPhone Distribution: Deveryware (YY96N698P3)")
    if options[:to_appaloosa]
      appaloosa(group_ids: "4641", screenshots: "")
    end
    if options[:to_store]
      deliver(skip_metadata: true, skip_screenshots: true)
    end
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.deveryware.notico"
apple_id "dev.apple@deveryware.com"

team_id "YY96N698P3"
itc_team_id "460500"

for_platform :ios do

		for_lane :ic_vo2 do
    	apple_id 'stephane.villette@vo2-group.com'
    	app_identifier 'com.deveryware.notico-ic'
  	end
  	for_lane :integ_vo2 do
    	apple_id 'stephane.villette@vo2-group.com'
    	app_identifier 'com.deveryware.notico-integ'
  	end
  	for_lane :prod_vo2 do
    	apple_id 'stephane.villette@vo2-group.com'
    	app_identifier 'com.deveryware.notico-prod'
		end
end
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane            | 2.0.5   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| CFPropertyList            | 2.3.4        |
| ZenTest                   | 4.11.1       |
| RubyInline                | 3.12.4       |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.2        |
| molinillo                 | 0.4.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| cocoapods                 | 1.0.1        |
| dotenv                    | 2.1.1        |
| osx_keychain              | 1.0.1        |
| cocoapods-keys            | 1.7.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.3.0        |
</details>


*generated on:* **2016-12-17**
</details>
