### ISSUE TITLE
Pilot Fails with 'invalid request body' message

### ISSUE THREAD

**Issue by steve-gray** [fastlane/fastlane#7523]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When running a my lane configuration with `fastlane ios beta` I'm getting errors back from spaceship internally about 'invalid request body'. This error also occurs when running a simple command, such as `fastlane pilot list --verbose`:

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

````
Successfully loaded Appfile at path '/Users/steve/workspace/src/github.com/<redacted>/customer/fastlane/Appfile'
- package_name: 'com.<redacted>.apps.customer'
- app_identifier: 'com.<redacted>.apps.customer'
- apple_id: 'steve@<redacted>.com'
- team_id: 'V64X484NJ7'
-------
INFO [2016-12-16 12:25:35.19]: Login to iTunes Connect (steve@<redacted>.com)
Looking for iTunes Connect Team with ID 118412271

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	invalid request body

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09invalid%20request%20body+repo:fastlane/fastlane
➡️  Deliver fails with `invalid request body`
   https://github.com/fastlane/fastlane/issues/6710 [closed] 24 💬
   25 Oct 2016

➡️  pilot crashes on upload
   https://github.com/fastlane/fastlane/issues/4821 [closed] 24 💬
   6 weeks ago

➡️  Unable to log in to iTunes Connect - returns HTML
   https://github.com/fastlane/fastlane/issues/2149 [closed] 18 💬
   22 Sep 2016

and 1 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09invalid%20request%20body&type=Issues&utf8=✓
/usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.0/lib/spaceship/tunes/tunes_client.rb:218:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	invalid request body
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.0/lib/spaceship/tunes/tunes_client.rb:94:in `team_id='
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.0/lib/spaceship/tunes/tunes_client.rb:121:in `select_team'
	from /usr/local/lib/ruby/gems/2.3.0/gems/spaceship-0.36.0/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/pilot/lib/pilot/manager.rb:16:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/pilot/lib/pilot/manager.rb:8:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/pilot/lib/pilot/tester_manager.rb:93:in `list_testers'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/pilot/lib/pilot/commands_generator.rb:93:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/pilot/lib/pilot/commands_generator.rb:133:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/pilot/lib/pilot/commands_generator.rb:14:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/fastlane/lib/fastlane/cli_tools_distributor.rb:46:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.0.3/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
````

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.0.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# ================== ANDROID / GOOGLE PLAY SETTINGS ===============
json_key_file "../android-keys/android-developer.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.yaalax.apps.customer" # e.g. com.krausefx.app

# ================== IOS / APPLE SETTINGS =========================

app_identifier "com.yaalax.apps.customer" # The bundle identifier of your app
apple_id "steve@yaalax.com" # Your Apple email address

team_id "V64X484NJ7"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| spaceship           | 0.36.0  | 🚫 Update availaible |
| fastlane            | 2.0.3   | ✅ Up-To-Date        |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| faraday                   | 0.9.2        |
| faraday_middleware        | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.7        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.0        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-12-16**
</details>
````

**Comment by steve-gray** [comment]
The warning about the update in the gems from fastlane env just appeared to explain it to me: I didnt read the mountain of text before pasting it into the issue. I literally just updated fastlane though, so I'm suprised that I didnt get spaceship with it.

**Comment by KrauseFx** [comment]
No worries, that's why we have a [mono gem](https://github.com/fastlane/fastlane/releases/tag/2.0.0) now 👍
