### ISSUE TITLE
Metadata and screenshots for multiple "Branded" Targets of the same underlying App 

### ISSUE THREAD

**Issue by deberle** [fastlane/fastlane#753]
I am using the setup described in the  [FAQs](https://github.com/fastlane/fastlane/blob/master/docs/FAQs.md#multiple-targets-of-the-same-underlying-app) using dotenv for multiple targets (see also issue #88 ).   
However, I am still having trouble to figure out how to handle screenshots and metadata. I need to store them in target-specific folders like `TARGET_NAME/screenshots` or `TARGET_NAME/metadata`
I am setting the custom paths in the Fastfile like this:
```
    deliver(
      screenshots_path: ENV['SCREENSHOTS_PATH'],
      metadata_path: ENV['METADATA_PATH']
    )
```
Now that works. I'd prefer to declare them in the Deliverfile itself, but it does't seem to work with dotenv (or am I missing something?). 

But the real issue is:  
**How can I download the initial metadata and screenshots from ITC to my custom folders?**

For screenshots, there is an API `deliver download_screenshots` but I don't know how to make it use my custom paths.

For metadata, the only way to get them seems to be a `deliver setup` but then again how do I get it to use my custom paths!

**Comment by KrauseFx** [comment]
`deliver init` will always just init the files in the current directory. There is no way to change this. You can easily write a script to clone everything somewhere into `/tmp` and then move the resulting files.

**Comment by deberle** [comment]
I was trying just that, but deliver setup requires user interaction. I didn't manage to set bundle id etc. via script. 
I also tried pre generating the Deliverfiles but then deliver setup wouldn't run. 
deliver download_screenshots should work however. 

So from an API perspective I think it would make sense to expose an Interface download_metadata. 

I think that should also resolve my issue. 

What do you think?

**Comment by deberle** [comment]
Ok, I have a setup script for my app targets like this:

```
# iterate apps
apps.each do |app|
  app_name = app[:ProjectName]
  bundle_id = app[:id]

  # create Deliverfile 
  out_file = File.new("#{app_name}/Deliverfile", "w")
  out_file.puts("app_identifier \"#{bundle_id}\"\nusername \"#{username}\"")
  out_file.close

  # load screenshots
  %x( cd "#{app_name}" && deliver download_screenshots && cd - )

  # TODO: load metadata
  # %x( cd "#{app_name}" && deliver download_metadata && cd - )
end
```

Works fine except of `deliver download_metadata` of course. 

Any chance you would add that API?

**Comment by KrauseFx** [comment]
@baarde sorry, no `download_metadata` planned

**Comment by baarde** [comment]
That's OK. **I** don't need it. 😉

**Comment by deberle** [comment]
Ok, too bad. Thanks anyway for your incredible work!  
Why am I the only one with the "multiple branded targets" setup who is running into this issue...? 
Help from someone who's been through this would be very much appreciated! What am I missing?
I'm looking at setting up Deliver 50+ times....

**Comment by truth3** [comment]
Don't laugh as I'm sure there is a better approach, but I used something like this to run through all my branded targets which get pushed to the App Store.

`echo "Setting up Deliver for all targets"

mkdir "x1";
cd x1;
deliver init -u "xxxxx@xxxx.com" -a "com.xxx.apps.x1";
cd ..
mkdir "x2";
cd x2;
deliver init -u "xxxxx@xxxx.com" -a "com.xxx.apps.x2.";
`

Hope that helps

**Comment by deberle** [comment]
Oh, I'm not laughing at all! That was exactly what I was looking for. I was messing around with `deliver init` but the options -u, -a were not obvious to me.

So I would still consider a `download_metadata` API to be the better option, but as for me this issue can be closed.

**Comment by truth3** [comment]
@deberle Glad it helped!

**Comment by ohwutup** [comment]
Hey everyone! I am going to close this issue for now as there has not been any activity for a while! Please feel free to reopen if necessary! :+1:
