### ISSUE TITLE
rubyzip-1.1.7 conflicts with rubyzip (< 2.0.0, >= 1.2.0)

### ISSUE THREAD

**Issue by mpateck** [fastlane/fastlane#7534]
### Issue Description

pilot started to not upload ipas anymore. 
I updated my mac to sierra, removed fastlane completely and reinstalled fastlane with:
sudo gem install fastlane fastlane_core

This is the output:
Fetching: rubyzip-1.2.0.gem (100%)
Successfully installed rubyzip-1.2.0
Fetching: fastlane-2.0.3.gem (100%)
Successfully installed fastlane-2.0.3
Parsing documentation for rubyzip-1.2.0
Installing ri documentation for rubyzip-1.2.0
Parsing documentation for fastlane-2.0.3
unable to convert "\x89" from ASCII-8BIT to UTF-8 for frameit/lib/assets/empty.png, skipping
Installing ri documentation for fastlane-2.0.3
Fetching: rubyzip-1.1.7.gem (100%)
Successfully installed rubyzip-1.1.7
Please use `fastlane fastlane_core` instead of `fastlane_core` from now on.
Successfully installed fastlane_core-0.60.1
Parsing documentation for rubyzip-1.1.7
Installing ri documentation for rubyzip-1.1.7
Parsing documentation for fastlane_core-0.60.1

As you can see in the env listing, my system has rubyzip 1.2.0 installed, but with fastlane installation ruby zip 1.1.7 will be installed in addition.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS='-t DAV' pilot upload --skip_submission -u 'xxx@xxx.de' --skip_waiting_for_build_processing true --verbose --capture_output
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate fastlane-2.0.3, because rubyzip-1.1.7 conflicts with rubyzip (< 2.0.0, >= 1.2.0) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:186:in `rescue in try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems.rb:183:in `try_activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:132:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.60.1/lib/fastlane_core.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.13.1/lib/pilot.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/pilot-1.13.1/bin/pilot:4:in `<top (required)>'
	from /usr/local/bin/pilot:23:in `load'
	from /usr/local/bin/pilot:23:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.2                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.2 (16C68)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane            | 2.0.3   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| slack-notifier            | 1.5.1   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| minitest                  | 5.8.3   |
| activesupport             | 4.2.5   |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| colored                   | 1.2     |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| terminal-table            | 1.4.5   |
| plist                     | 3.1.0   |
| addressable               | 2.3.7   |
| multipart-post            | 2.0.0   |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| security                  | 0.1.3   |
| credentials_manager       | 0.16.2  |
| multi_xml                 | 0.5.5   |
| faraday                   | 0.9.2   |
| faraday_middleware        | 0.10.0  |
| unf_ext                   | 0.0.7.1 |
| unf                       | 0.1.4   |
| domain_name               | 0.5.25  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| babosa                    | 1.0.2   |
| xcode-install             | 2.0.8   |
| word_wrap                 | 1.0.0   |
| excon                     | 0.45.4  |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| mime-types                | 2.4.3   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.11.0  |
| logging                   | 2.0.0   |
| jwt                       | 1.5.2   |
| memoist                   | 0.14.0  |
| signet                    | 0.7.0   |
| googleauth                | 0.5.0   |
| thor                      | 0.19.1  |
| httpclient                | 2.8.0   |
| google-api-client         | 0.9.8   |
| mini_magick               | 4.5.1   |
| rubyzip                   | 1.2.0   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| bundler                   | 1.13.6  |
| json                      | 1.8.3   |
</details>

*generated on:* **2016-12-16**
</details>

**Comment by KrauseFx** [comment]
Could you try the latest release and let us know if that fixes the issue for you?

**Comment by mpateck** [comment]
That worked for me, thank you.
But i have to open another one because another relationship.

**Comment by milch** [comment]
@mpateck Alright, thanks for letting us know!

**Comment by lfarah** [comment]
@KrauseFx I got this error when updating fastlane to 2.6.0:
```
unable to convert "\x89" from ASCII-8BIT to UTF-8 for frameit/lib/assets/empty.png, skipping
```

**Comment by KrauseFx** [comment]
@lfarah this looks more like a warning than an error, does it work?

**Comment by lfarah** [comment]
Just checked and it works perfectly
