### ISSUE TITLE
set_info_plist_value should fail build on error

### ISSUE THREAD

**Issue by zantoku** [fastlane/fastlane#7535]
We're setting some Info.plist values using set_info_plist_value(). Due to a typo in the Fastfile, set_info_plist_value() ended up being called with a key, but a null value, like this:

```
set_info_plist_value(
    path: options[:plist],
    key: 'FacebookAppID',
    value: options[:facebook_app_id]
)
```

It's structured like this because we need to set different FB AppIDs for different build variants. The build proceeded with this warning message:

```
[11:41:54]: ----------------------------------
[11:41:54]: --- Step: set_info_plist_value ---
[11:41:54]: ----------------------------------
[11:41:54]: No value found for 'value'
[11:41:54]: Unable to set value to plist file at '/jenkins/workspace/[redacted]/Info.plist'

```

However, we missed the warning message, and the build went through and was marked with SUCCESS. Unfortunately, we ended up with a non-functioning/crashing FB login on the App Store. :-(

I believe that a failed set_info_plist_value should fail the build.

ENVIRONMENT

We're not super up to date but I haven't found any reported issues related to this, so I expect current behaviour is the same.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.11.6                                            |
| Ruby                | 2.3.1                                              |
| Bundler?            | true                                               |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/        |
| Xcode Version       | 8.1                                                |
| Git                 | git version 2.9.3 (Apple Git-75)                   |
| Installation Source | /Users/[redacted]/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                         |
| Ruby Lib Dir        | /Users/[redacted]/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                        |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.39.0"

default_platform :ios

[content removed, contains sensitive info]

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "[redacted]" # Your Apple email address
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date        |
| fastlane_core       | 0.53.0  | 🚫 Update availaible |
| spaceship           | 0.37.0  | 🚫 Update availaible |
| cert                | 1.4.3   | 🚫 Update availaible |
| deliver             | 1.15.0  | 🚫 Update availaible |
| frameit             | 3.0.0   | 🚫 Update availaible |
| gym                 | 1.12.0  | 🚫 Update availaible |
| sigh                | 1.11.2  | 🚫 Update availaible |
| match               | 0.10.0  | 🚫 Update availaible |
| pem                 | 1.4.0   | 🚫 Update availaible |
| pilot               | 1.12.0  | 🚫 Update availaible |
| produce             | 1.3.0   | 🚫 Update availaible |
| scan                | 0.14.1  | 🚫 Update availaible |
| screengrab          | 0.5.5   | 🚫 Update availaible |
| snapshot            | 1.16.3  | 🚫 Update availaible |
| supply              | 0.7.1   | 🚫 Update availaible |
| fastlane            | 1.107.0 | 🚫 Update availaible |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status       |
| ----------------------------------------------------- | ------- | ------------------- |
| fastlane-plugin-update_project_codesigning            | 0.1.2   | 🚫 Update availaible |
| fastlane-plugin-update_provisioning_profile_specifier | 1.1.1   | 🚫 Update availaible |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.0.0        |
| bundler                                               | 1.13.6       |
| io-console                                            | 0.4.5        |
| i18n                                                  | 0.7.0        |
| json                                                  | 1.8.3        |
| minitest                                              | 5.9.1        |
| thread_safe                                           | 0.3.5        |
| tzinfo                                                | 1.2.2        |
| activesupport                                         | 4.2.7.1      |
| public_suffix                                         | 2.0.4        |
| addressable                                           | 2.5.0        |
| jmespath                                              | 1.3.1        |
| aws-sdk-core                                          | 2.6.18       |
| aws-sdk-resources                                     | 2.6.18       |
| aws-sdk                                               | 2.6.18       |
| babosa                                                | 1.0.2        |
| colored                                               | 1.2          |
| highline                                              | 1.7.8        |
| commander                                             | 4.4.0        |
| security                                              | 0.1.3        |
| credentials_manager                                   | 0.16.2       |
| excon                                                 | 0.54.0       |
| gh_inspector                                          | 1.0.2        |
| multi_json                                            | 1.12.1       |
| plist                                                 | 3.1.0        |
| rubyzip                                               | 1.1.7        |
| terminal-table                                        | 1.4.5        |
| fastlane_core                                         | 0.53.0       |
| multipart-post                                        | 2.0.0        |
| faraday                                               | 0.9.2        |
| unf_ext                                               | 0.0.7.2      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20161021 |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| faraday_middleware                                    | 0.10.0       |
| fastimage                                             | 1.6.8        |
| multi_xml                                             | 0.5.5        |
| claide                                                | 1.0.1        |
| fuzzy_match                                           | 2.0.4        |
| nap                                                   | 1.1.0        |
| cocoapods-core                                        | 1.1.0.beta.1 |
| cocoapods-deintegrate                                 | 1.0.1        |
| cocoapods-downloader                                  | 1.1.2        |
| cocoapods-plugins                                     | 1.0.0        |
| cocoapods-search                                      | 1.0.0        |
| cocoapods-stats                                       | 1.0.0        |
| netrc                                                 | 0.7.8        |
| cocoapods-trunk                                       | 1.1.1        |
| cocoapods-try                                         | 1.1.0        |
| escape                                                | 0.0.4        |
| fourflusher                                           | 1.0.1        |
| molinillo                                             | 0.5.3        |
| xcodeproj                                             | 1.3.1        |
| cocoapods                                             | 1.1.0.beta.1 |
| dotenv                                                | 2.1.1        |
| mini_magick                                           | 4.5.1        |
| rouge                                                 | 1.11.1       |
| xcpretty                                              | 0.2.4        |
| net-ssh                                               | 3.2.0        |
| net-sftp                                              | 2.1.2        |
| krausefx-shenzhen                                     | 0.14.10      |
| slack-notifier                                        | 1.5.1        |
| xcpretty-travis-formatter                             | 0.0.4        |
| jwt                                                   | 1.5.6        |
| little-plugger                                        | 1.1.4        |
| logging                                               | 2.1.0        |
| memoist                                               | 0.15.0       |
| os                                                    | 0.9.6        |
| signet                                                | 0.7.3        |
| googleauth                                            | 0.5.1        |
| httpclient                                            | 2.8.2.4      |
| hurley                                                | 0.2          |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| uber                                                  | 0.0.15       |
| representable                                         | 2.3.0        |
| retriable                                             | 2.1.0        |
| google-api-client                                     | 0.9.19       |
| terminal-notifier                                     | 1.7.1        |
| word_wrap                                             | 1.0.0        |
| xcode-install                                         | 2.0.8        |
| fastlane-plugin-update_project_codesigning            | 0.1.2        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.1.1        |
</details>

*generated on:* **2016-12-16**
</details>

**Comment by hjanuschka** [comment]
i did a PR for that -> https://github.com/fastlane/fastlane/pull/7547 - lets see

**Comment by KrauseFx** [comment]
Ouch, really sorry your app was broken in the App Store 😢 Thanks @hjanuschka for the fix, this will be in the next release  🚀

**Comment by zantoku** [comment]
Awesome, thanks!
