### ISSUE TITLE
invalid options

### ISSUE THREAD

**Issue by lxzhh** [fastlane/fastlane#754]
I'm using fastlane tools, and when I pass some arguments to the action, there always be some crash reports. Here is one of them
```
 "event_id": "88dbf900fef08108fb9ebd9d4cc7e67e",
  "message": "OptionParser::InvalidOption: invalid option: --message",
  "timestamp": "2015-10-28T05:36:43",
```
In my case,  I build an ipa by using gym and upload it to a url:
```
 lane :fir do |args, options|
    output_directory_path = 'XXX'
    output_name = 'xxxx'
    gym(scheme: "xxx",
     sdk: "iphoneos9.1",
     configuration: "Debug",
     output_directory: output_directory_path,
     output_name: output_name,
     export_method: "development",
     codesigning_identity: "xxxxx",
     silent: true,
     use_legacy_build_api: true)

     sh "fir p " + output_directory_path + output_name + " -c " + options[:message]
  end
```
and it crash when I use the command 
fastlane fir --message "something"

Thanks in advance.

**Comment by KrauseFx** [comment]
I don't know what you're trying to do exactly, but you might like the [passing parameters](https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#passing-parameters) documentation.

**Comment by lxzhh** [comment]
@KrauseFx thanks, this is what I want.
