### ISSUE TITLE
Bundle install fails due to cyclic dependency

### ISSUE THREAD

**Issue by samdods** [fastlane/fastlane#7540]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `bundle install` fails when **Gemfile** includes `fastlane`.

Contents of **Gemfile**:
```
source 'https://rubygems.org'
gem 'fastlane', '1.111.0'
```

Running command `bundle install`:
```
$ bundle install
Fetching gem metadata from https://rubygems.org/
Fetching version metadata from https://rubygems.org/
Fetching dependency metadata from https://rubygems.org/
Resolving dependencies...
Your bundle requires gems that depend on each other, creating an infinite loop. Please remove either gem 'deliver' or gem 'fastlane'
and try again.
```

Note, this is a completely fresh directory with nothing in it other than the **Gemfile**. There is no **Gemfile.lock**. If there is a **Gemfile.lock** then the bundle install will succeed. This suggests that one of the dependencies referenced by an optimistic version has been changed such that it creates the dependency cycle.

Note also, the version of fastlane doesn't matter. We get the same error for version 1.1.0 as we do for 1.111.0.

**Comment by milch** [comment]
Hi @samdods, thanks for submitting this issue! We recently released `fastlane 2.0` which changed how the gems are structured internally. Please see [my answer here](https://github.com/fastlane/fastlane/issues/7540) for information on how to resolve this.

I'm going to close this issue for now, let me know if that doesn't work for you and we'll reopen it!

**Comment by milch** [comment]
Updated the link to https://github.com/fastlane/fastlane/issues/7519#issuecomment-267494438 - sorry, I initially pasted in the wrong one.

**Comment by samdods** [comment]
OK, we can update to version 2, but don't you think it's crazy that the dependencies were setup in a way that this could break ALL old versions? i would expect if we don't change the version we use then nothing should break.

isn't there a way we could prevent this from happening in future?

**Comment by KrauseFx** [comment]
@samdods That's something where we thought bundler would automatically resolve the dependencies: old release requires old gems, however it didn't happen like this. @milch had an idea on how we can solve it, hopefully we get this done by Monday 👍

**Comment by milch** [comment]
@samdods 

We just implemented a fix, a Gemfile like yours should work now! We've removed a couple of the older gems in the process, so if another cyclic dependency error comes up, please uninstall existing fastlane gems and re-run `bundle install`.
