### ISSUE TITLE
register device action bug

### ISSUE THREAD

**Issue by lxzhh** [fastlane/fastlane#755]
I think it's a bug, in the 
fastlane/actions/register_devices.rb in run at line 20:
``
ENV["FASTLANE_TEAM_ID"] = platform[:team_id]
``
should it be 
``
ENV["FASTLANE_TEAM_ID"] = params[:team_id]
``

**Comment by damienmollard** [comment]
+1

**Comment by KrauseFx** [comment]
Sorry about this, it's fixed, I'll push a new release in a minute
