### ISSUE TITLE
Hidden error while failing to decode provisioning profile

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#7557]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I probably have broken my keychain setup because some tests are failing by default when running the standard rspec.

In particular I found out that `security cms -D -i  ./match/spec/fixtures/test.mobileprovision` fails:

```
security: cert import failed: The specified keychain could not be found.
security: problem decoding
```

This fails the following code:
```
      def parse(path)
        require 'plist'

        plist = Plist.parse_xml(`security cms -D -i "#{path}" 2> /dev/null`) # /dev/null: https://github.com/fastlane/fastlane/issues/6387
        if (plist || []).count > 5
          plist
        else
          UI.error!("Error parsing provisioning profile at path '#{path}'")
          nil
        end
```

And the error message is maybe not 100% accurate / complete.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

N/A

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

N/A

**Comment by KrauseFx** [comment]
Test issue has been resolved now 👍

**Comment by taquitos** [comment]
It has been reported that setting the `login` keychain to be the default should allow the command to be run:
`security cms -D -i /Users/lyndsey.ferguson/Desktop/embedded.mobileprovision`
Thanks @lyndsey-ferguson !!
