### ISSUE TITLE
Hockey Upload Size

### ISSUE THREAD

**Issue by ollieatkinson** [fastlane/fastlane#756]
When uploading via the hockey lane the file size is much larger than if i were to upload using the native mac hockey app.

```
    hockey(
      api_token: 'token', 
      ipa: "MyApp.ipa",
      notify: '0',
      status: '1',
      teams: 'team',
      notes: changelog
    )
```

As far as I am aware it should be a small file size - is this something hockey is reporting incorrectly in its web UI or is there indeed extra build artefacts added to the hockey upload?

circled in red is the __same__ version but uploaded through fastlane hockey
![rapp com commonagency rapp hockeyapp safari today at 10 32 29](https://cloud.githubusercontent.com/assets/1382565/10785971/4a8b359a-7d5f-11e5-8b84-0ca6bb757001.png)

**Comment by xfreebird** [comment]
@ollieatkinson was the ipa created with ```fastlane``` in both cases ?

**Comment by ollieatkinson** [comment]
@xfreebird Yes, both created using fastlane - I uploaded the same IPA produced by __gym__ :muscle:

**Comment by xfreebird** [comment]
could you download both ipa files and check the decompressed size of the binaries. It could be that the hockey desktop app repacks the ipa file with a better compression rate.

**Comment by ollieatkinson** [comment]
it seems like fastlane is bundling extra swift support files

![swift support](http://i.imgur.com/L8c3TGL.png)

vs Hockey 

![hockey](http://i.imgur.com/CYLtk14.png)

**Comment by xfreebird** [comment]
interesting that HockeyApp drops that folder. AFAIK SwfitSupport is needed for AppStore submission. I think that is why HockeyApp drops folder to save space on their servers, or a bug in their app.

**Comment by ollieatkinson** [comment]
Hm. OK - Is that something we would be able to strip for AdHoc deployment or do you think its better to leave them

**Comment by xfreebird** [comment]
I think it would be better to leave it, but it would work and without it. Not sure why Apple insists on that when submitting to AppStore.

**Comment by ollieatkinson** [comment]
@xfreebird It will be a build support file for the different iOS, you can compile swift 2 to run on iOS 7
