### ISSUE TITLE
Failure while using two factor authentication 

### ISSUE THREAD

**Issue by chipsnyder** [fastlane/fastlane#7562]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- Using fastlane 2.0.5
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Spaceship can't find method `store_cookie` and failing while trying to authenticate using 2-factor.
Result says it failed to log in however I am seeing the prompt on my phone and computer to allow the connection and provide the code. However the flow crashes before I can respond. 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
spaceauth -u redacted_email --capture_output
Logging into to iTunes Connect (redacted_email)...
Could not login to iTunes Connect...
/Users/csnyder/.rvm/gems/ruby-2.3.0/gems/spaceship-0.39.0/bin/spaceauth:25:in `<top (required)>': undefined method `store_cookie' for nil:NilClass (NoMethodError)
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/spaceauth:23:in `load'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/spaceauth:23:in `<main>'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "f03ed20c-0f62-437c-b0bd-29b25fe7b0af"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later


############################## PRE ##############################

before_all do
  carthage(
  command: 'bootstrap',
  platform: 'ios'
  )
end

############################ Deploy #############################

lane :profile do
  sigh(
  skip_install: true,
  development: true,
  username: "redacted_email"
  )
end

lane :beta do
  # increment_build_number

  sigh(
  skip_install: true,
  development: true,
  username: "redacted_email"
  )

  # build your iOS app
  gym(
  scheme: "Sample",
  configuration: "Debug"
  )

  # upload to Beta by Crashlytics
  crashlytics(
  api_token: "redacted_API_Token",
  build_secret: "redacted_Build_Secret",
  groups: ['testers']
  )
end

############################# Test ##############################

lane :test do
  scan
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your Apple or Google credentials, or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier/package name of your app
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane            | 2.0.5   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2016-12-17**
</details>

**Comment by A1iAshoor** [comment]
+1 same issue

**Comment by hjanuschka** [comment]
@A1iAshoor @chipsnyder 
i think with the transition to 2.0 of fastlane it's supposed to run with:

`fastlane spaceship spaceauth -u email@host.com`  

can you guys point me out where you found the old command? (so i can update it there)
also would be nice if you let me know if this worked for you

**Comment by A1iAshoor** [comment]
@hjanuschka it's [here](https://docs.fastlane.tools/best-practices/continuous-integration/#2-factor-auth) and [here](https://docs.fastlane.tools/best-practices/continuous-integration/)

It worked with the code you posted, However I get this:
```
Fastlane update available
Please run `brew cask reinstall fastlane`
---------------------------------------------
-------------------WARNING-------------------
---------------------------------------------
You're using an old version of spaceship
To ensure spaceship and fastlane works
update to the latest version.

Run `[sudo] gem update spaceship`

or `bundle update` if you use bundler.

You're on spaceship version: 0.38.4
Latest spaceship version  : 1.0.0 
```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.3.0                           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2659)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | 🚫 Update availaible |
| spaceship           | 0.38.4  | 🚫 Update availaible |
| fastlane            | 2.1.0   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.1.7        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
</details>


*generated on:* **2016-12-19**
</details>

**Comment by dflourusso** [comment]
$ fastlane spaceauth -u user@domain.com.br

    /Users/daniel/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.1.1/spaceship/lib/spaceship/spaceauth_runner.rb:23:in
    `run': [!] undefined method `store_cookie' for nil:NilClass (NoMethodError)

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |



### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.1   | ✅ Up-To-Date  |

**Comment by chipsnyder** [comment]
@hedjirog I found the old command on the [Spaceship ReadMe](https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification)

I won't be able to try that command until later today but I will post back to this ASAP

**Comment by R0cKET** [comment]
+1

**Comment by rsigg** [comment]
spaceauth -u user@email.com

is referenced at: 

https://docs.fastlane.tools/best-practices/continuous-integration/

**Comment by chipsnyder** [comment]
@hjanuschka tried with your command same issue ...
```
fastlane spaceship spaceauth -u chip.snyder3@gmail.com
/Users/csnyder/.rvm/gems/ruby-2.3.0/gems/spaceship-0.39.0/lib/spaceship/version.rb:3: warning: already initialized constant Spaceship::DESCRIPTION
/Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/spaceship/lib/spaceship.rb:30: warning: previous definition of DESCRIPTION was here
Logging into to iTunes Connect (chip.snyder3@gmail.com)...
Could not login to iTunes Connect...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Failure while using two factor authentication 
   https://github.com/fastlane/fastlane/issues/7562 [open] 8 💬
   a day ago

/Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/spaceship/lib/spaceship/spaceauth_runner.rb:23:in `run': [!] undefined method `store_cookie' for nil:NilClass (NoMethodError)
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/spaceship/lib/spaceship/commands_generator.rb:40:in `block (2 levels) in run'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/spaceship/lib/spaceship/commands_generator.rb:46:in `run'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/spaceship/lib/spaceship/commands_generator.rb:12:in `start'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/fastlane/lib/fastlane/cli_tools_distributor.rb:46:in `take_off'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/gems/fastlane-2.0.5/bin/fastlane:5:in `<top (required)>'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/csnyder/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by chipsnyder** [comment]
Update tried with `bundle exec fastlane spaceship spaceauth -u chip.snyder3@gmail.com` no luck. Forcefully uninstalled all of Fastlane's gems reinstalled and updated again. It's now working

**Comment by hjanuschka** [comment]
@chipsnyder nice to hear, thx for feedback, can you close the issue?

**Comment by crenwick** [comment]
I also had the same problems described in this issue. At @chipsnyder 's advice, I uninstalled fastlane again (all the previously separated fastlane projects were still living on my ruby build, so I made sure I uninstalled those too), reinstalled, and it worked fine.

**Comment by KrauseFx** [comment]
@crenwick oh yeah, great to hear 👍
