### ISSUE TITLE
Could not find 'spaceship' (< 1.0.0, >= 0.39.0) - did find: [spaceship-1.0.0]

### ISSUE THREAD

**Issue by mpateck** [fastlane/fastlane#7574]
### Issue Description

I uninstalled everything. 
After installing fastlane, i installed fastlane deliver. 
With deliver, spaceship 0.39.0 got installed. 
With that, my transfer to itunes connect fails. 
I updated spaceship to 1.0.0 but still got the spaceship is outdated message. 
After uninstalling 0.39.0 the error 
Could not find 'spaceship' (< 1.0.0, >= 0.39.0) - did find: [spaceship-1.0.0]
appeared

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.2                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.8.4 (Apple Git-73)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.2 (16C68)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.0                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| slack-notifier            | 1.5.1   |
| i18n                      | 0.7.0   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| minitest                  | 5.8.3   |
| activesupport             | 4.2.5   |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| colored                   | 1.2     |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| terminal-table            | 1.4.5   |
| plist                     | 3.1.0   |
| addressable               | 2.3.7   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| highline                  | 1.7.8   |
| commander                 | 4.4.0   |
| excon                     | 0.45.4  |
| faraday                   | 0.9.2   |
| unf_ext                   | 0.0.7.1 |
| unf                       | 0.1.4   |
| domain_name               | 0.5.25  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| mime-types                | 2.4.3   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.11.0  |
| logging                   | 2.0.0   |
| jwt                       | 1.5.2   |
| memoist                   | 0.14.0  |
| signet                    | 0.7.0   |
| googleauth                | 0.5.0   |
| thor                      | 0.19.1  |
| httpclient                | 2.8.0   |
| google-api-client         | 0.9.8   |
| mini_magick               | 4.5.1   |
| multi_xml                 | 0.5.5   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| bundler                   | 1.13.6  |
| faraday_middleware        | 0.10.0  |
| json                      | 1.8.3   |
| rubyzip                   | 1.2.0   |
</details>

*generated on:* **2016-12-19**
</details>

**Comment by mpateck** [comment]
Seems to be fixed in newest version

**Comment by NikKovIos** [comment]
Still not fixed

**Comment by KrauseFx** [comment]
Yeah, please install `fastlane`, which now includes the _spaceship_ code, add the following to your `Gemfile`
```ruby
gem "fastlane"
```
and run `bundle update`

**Comment by NikKovIos** [comment]
I use lane:

```
lane :updateAllProfiles do
  match(type: "adhoc", readonly: true)
  match(type: "development", readonly: true)
  match(type: "appstore", readonly: true)
end
```

```
fastlane finished with errors
rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:310:in `to_specs': Could not find 'spaceship' (< 1.0.0, >= 0.25.1) - did find: [spaceship-1.0.0] (Gem::MissingSpecVersionError)
```

**Comment by KrauseFx** [comment]
@NikKovIos you didn't share your Gemfile. Also you can run `[sudo] gem uninstall spaceship`

**Comment by NikKovIos** [comment]
I don't use Gemfile. Is it necessary? Doing fastlane match xxx do the job without Gemfile. 

I've tried to reinstall spaceship already.

**Comment by KrauseFx** [comment]
@NikKovIos not reinstalling, try uninstalling. It's all just one gem now. Run `gem cleanup` and `gem uninstall fastlane_core spaceship credentials_manager` and then `gem update fastlane` 👍

**Comment by NikKovIos** [comment]
Still 
`rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'spaceship' (< 1.0.0, >= 0.25.1) among 127 total gem(s) (Gem::MissingSpecError)`

What i did:
1) gem uninstall fastlane_core spaceship credentials_manager
2) gem uninstall fastlane
3) gem cleanup
4) gem install fastlane
5) gem update fastlane

`gem list` doesn't have spaceship. Does have fastlane (2.6.0).

**Comment by KrauseFx** [comment]
@NikKovIos can you run `which fastlane`

**Comment by KrauseFx** [comment]
also, you might want to use the pre-packaged fastlane: [download.fastlane.tools](https://download.fastlane.tools)

**Comment by NikKovIos** [comment]
which fastlane:
`.rvm/gems/ruby-2.3.0/bin/fastlane`

**Comment by KrauseFx** [comment]
Maybe since that doesn't work, you should try using bundler: Follow the CocoaPods Guide (https://guides.cocoapods.org/using/a-gemfile.html), but add `fastlane` as gem instead 👍

**Comment by NikKovIos** [comment]
At last! Works.
What have i done:
1) bundle init
2) In Gemfile
source "https://rubygems.org"
gem "xcode-install"
gem "spaceship"
gem "fastlane"
3) bundle install
4) be fastlane updateAllProfiles
(where be is alias for bundle exec and updateAllProfiles is my lane)

@KrauseFx Thanks for help!

**Comment by KrauseFx** [comment]
@NikKovIos please remove `spaceship` from the Gemfile, and run `bundle update`, that should be the way to make it work 👍

**Comment by NikKovIos** [comment]
Yep!
