### ISSUE TITLE
Why use separate API endpoint for listProvisioningProfile? [Question]

### ISSUE THREAD

**Issue by EliyahuStern** [fastlane/fastlane#7576]
### New Issue Checklist

- [√] Updated fastlane to the latest version
- [√] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
As stated in the Spaceship [Readme](https://github.com/fastlane/fastlane/blob/master/spaceship/README.md) file, the Provisioning Profile entities are handled using 2 separate API endpoint:

> - `https://developerservices2.apple.com`:
>  -- Get a list of all available provisioning profiles
...
> - `https://developer.apple.com`:
>  -- Create new certificates, provisioning profiles and apps

Looking at the code, this introduces a big deal of modifications to the `provisioning_profile` class, compared to the rest of the classes, especially for handling CSRF tokens.

I was playing with Spaceship and made it use the same API endpiont (`developer.apple.com`) for `listProvisioningProfile.action`, and couldn't spot any difference in the outcome.
I also could not find a comment in the code or earlier commits referring this difference.

Is there a specific reason for using `https://developerservices2.apple.com` there?

**Comment by asfalcone** [comment]
@EliyahuStern I'm going to close out this issue. We've recently switched over to using the developer.apple.com api, however one major difference is that the`appId` isn't included in the listProvisioningProfiles call so we're having to make an additional request to getProvisioningProfile for each profile right now to get that data.
