### ISSUE TITLE
Cannot install pilot 1.13.1 - no fastlane_core (< 1.0.0, >= 0.60.0)

### ISSUE THREAD

**Issue by Ivan-L** [fastlane/fastlane#7579]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

As part of a build process on macOS, we have a build step which uploads our IPA file to TestFlight using pilot. The build step ensures that the latest version of pilot is installed using:
```
/usr/bin/gem install pilot
```
Installation fails with the following output:
> /usr/bin/gem install pilot
> ERROR:  While executing gem ... (Gem::DependencyError)
> Unable to resolve dependencies: pilot requires fastlane_core (< 1.0.0, >= 0.60.0)

The current version of pilot as of this writing ([1.13.1](https://rubygems.org/gems/pilot/versions/1.13.1)) has a dependency on fastlane_core (< 1.0.0, >= 0.60.0), yet no such version exists because 0.60.0 and 0.60.1 were [yanked](https://rubygems.org/gems/fastlane_core/versions/0.60.1) and there is no other version less than 1.0.0 to satisfy the dependency.

The last version that works is [1.12.1](https://rubygems.org/gems/pilot/versions/1.12.1). Unfortunately we do not have control over the build step and cannot force a particular version of pilot to be used - the build step always tries to install the latest version of pilot and installation fails.

The fix would be to yank pilot 1.13.0 and 1.13.1 as they do not install successfully, or to release a newer version of pilot that installs.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.2                                             |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1108)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.9.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2016-12-19**
</details>

**Comment by Ivan-L** [comment]
@KrauseFx do you think it would be easiest to yank pilot 1.13.0 and 1.13.1 as a quick solution?

**Comment by isigui** [comment]
Hello, I got the same problem and can't find previous version of pilot compatible ?
Would you know which previous version of pilot have no "invalid" dependencies ?

**Comment by Ivan-L** [comment]
@isigui - the older version [1.12.1](https://rubygems.org/gems/pilot/versions/1.12.1) of pilot installs fine.
```
gem install pilot -v 1.12.1
```

**Comment by isigui** [comment]
Trying to install this version 
`gem install --http-proxy http://127.0.0.1:3128 pilot -v 1.12.1`
give me this error:

`ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: pilot requires credentials_manager (>= 0.16.0); spaceship requires credentials_manager (>= 0.16.0); fastlane_core requires credentials_manager (< 1.0.0, >= 0.16.2)
`

**Comment by Ivan-L** [comment]
@isigui, perhaps it worked for me because mine was not a fresh install and I still had some of the old dependencies. In any case, I.see a new version 2.0.0 of pilot has been pushed to address the issue, so the original problem should be resolved.

Here is the duplicate issue where it is stated that the problem is resolved: #7590 

I'm closing this issue as a result.

**Comment by isigui** [comment]
@Ivan-L , Thanks a lot, indeed i did not install any package before. This morning, with the new version, everything is working fine !!
