### ISSUE TITLE
Issue using cert to output certificates to folder

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#758]
Issue Number 5c22679bafb1e54e42c0538fb0fa096a

I am trying to get the "cert" action to check a folder for certificates, if they aren't there, then it will  make some and then install the ones in that folder. 

I am trying to implement Travis Cache for this so cert doesn't keep re-generating them as it will see them in the folder. I am trying to avoid having my certificates in my repo via this method.

**Comment by KrauseFx** [comment]
Replied on Twitter, a simple solution is to follow [this guide](http://natanrolnik.me/2015/10/21/introduction-to-fastlane-and-integrating-it-with-circleci-to-deploy-beta-with-crashlytics-fabric/)

**Comment by jcampbell05** [comment]
You say that yet I was able to get cert to spit it out into a folder, but when I ask cert to load from that same folder with the certificate their in fastlane it fails to work :)

I get this.
No such file or directory @ rb_sysopen - ./cache/DTE72PCU7D.cer

But look it is defiantly there:
<img width="417" alt="screen shot 2015-10-28 at 17 36 02" src="https://cloud.githubusercontent.com/assets/1484989/10797393/61471a98-7d9a-11e5-9ff0-532f556b11b5.png">

**Comment by KrauseFx** [comment]
@jcampbell05 You not only need the cer, but also the private key. There is a built-in action to import the certificate.

**Comment by jcampbell05** [comment]
@KrauseFx :) Yes but the thing is I run that exact same command on my machine from CLI 
`cert -output_path ./cache` it pulls down the cert, puts it in the folder and detects I have it on my machine with the p12. Everything rosy and happy.

Do the same thing with fastlane with cert and it complains about not even finding the file and folder. Even when running it on travis where it generates the certificate request and P12 it fails. 

So essentially this is what I expect to happen:
- Check apple for certificates like usual
- If the CER and P12 already exists in the keychain then Success.
- Check output_path from both CLI or from fastlane parameters for those same certificates with P12 and install them.
- If not then make a new one by requesting new certificate, put it into the output_path directory with the P12 and install it.

If this worked then I could use the Travis Cache feature to keep the cache folder between builds, cert will detect the P12 and cer is in there and then install it automatically. No generating a new one, no having to commit the certificates into the repo,  no having to manually run some script or action to decrypt a certificate and then install it.

Currently the above only happens with Command Line to a certain extent. Cert, finds the output_path, detects I have the CER installed and succeeds, yet when I run the exact same command within fastlane it complains about not finding my output path which is odd.

**Comment by jcampbell05** [comment]
So when I use a absolute path i.e "/cache/" it works the same both in CLI and fastlane. As soon as I use a releative path i.e "cache/" or "./cache/" then cert can't find the folder when ran under fastlane but is fine in the CLI. None of the other actions have this issue.

**Comment by jcampbell05** [comment]
@KrauseFx  Created a PR for cert, I found its handling ouput_path slightly different from gym, so I tweaked it.

https://github.com/fastlane/cert/pull/43
