### ISSUE TITLE
push application to apple\google store, without building [Help Request]

### ISSUE THREAD

**Issue by opetrovskyi** [fastlane/fastlane#7580]
### New Issue Checklist

- [+] Updated fastlane to the latest version
- [+] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to publish already built application to google\apple store with fastlane (i have no src, only apk and ipa files). lets say that developers deliver new version of application to me and i just want to push it in to store. For google play it is straight forward: sign apk, zipalign and 'supply'. While running 'fastlane init' i have all metadata stored in developer console for my application downloaded in fastlane folder. I found nothing even close to this approach for apple. For apple mandatory is having a .project file. My goal is to sign with appropriate cert\profile application and push it to apple store. Can you please give a hand in this? how can i download already existing metadata in applestore in fastlane/metadata ( to have all actual metadata in git repo), sign new ipa file with cert and push this application into apple store. If something is not clear in my question let me know i'll try to clarify it.
Thanks.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| cert                | 1.5.1   | 🚫 Update availaible |
| credentials_manager | 0.16.2  | 🚫 Update availaible |
| deliver             | 1.17.1  | 🚫 Update availaible |
| fastlane            | 2.0.3   | 🚫 Update availaible |
| fastlane_core       | 0.60.1  | 🚫 Update availaible |
| frameit             | 3.1.1   | 🚫 Update availaible |
| gym                 | 1.14.0  | 🚫 Update availaible |
| match               | 0.12.1  | 🚫 Update availaible |
| pem                 | 1.5.1   | 🚫 Update availaible |
| pilot               | 1.13.1  | ✅ Up-To-Date        |
| produce             | 1.5.1   | 🚫 Update availaible |
| scan                | 0.15.0  | 🚫 Update availaible |
| screengrab          | 0.6.1   | 🚫 Update availaible |
| sigh                | 1.13.1  | 🚫 Update availaible |
| snapshot            | 1.18.1  | 🚫 Update availaible |
| spaceship           | 0.39.0  | 🚫 Update availaible |
| supply              | 0.9.0   | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.1        |
| concurrent-ruby           | 1.0.2        |
| credentials_manager       | 0.16.2       |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 0.60.1       |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.1        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2016-12-19**
</details>
[INSERT OUTPUT HERE]

**Comment by dombarnes** [comment]
If you already have the IPA, you can just use `deliver` with some arguments to deliver to to iTunes connect, or `pilot` to send to testflight.

**Comment by opetrovskyi** [comment]
Thanks for reply. 
`fastlane init` is asking for .xcworkspace or .xcodeproj file even if Appfile with app\apple\bundle\team ID exist.  As i only have .ipa file i cannot use this.
I have found that `delivery init` do the metadata job for me, it grabs existing  data from the itunes. Now i am on the best way to sign this .ipa file with appropriate certs. The way i want to do this is using cert files lying next to .ipa file and if possible not using keychain at all.

**Comment by opetrovskyi** [comment]
I wonder is there a way to resign .ipa file using certs and profile from `match`. I managed to resign using `sigh` and manually pointing profile file and name of certificate to use but i want to manage all process as variables got from previous tasks. in `match` output there is a certificate name imported and there is also a provisioning file name but i have no idea how to use that output as input for `resign`.  


  lane :signandpublish do
    match(type: "appstore", readonly: true)
    sigh(
      output_path: "./",
      filename: "profile.mobileprovision"
    )
    resign(ipa: "./XXX-XXX-XXX-ReleaseProd-25.ipa",
        signing_identity: "iPhone Distribution: blah blah blah",
        provisioning_profile: "./profile.mobileprovision"
    )
    deliver(force: true,
        automatic_release: true,
       submit_for_review: false
    )
  end

**Comment by dombarnes** [comment]
I have a feeling that Fastlane handles some of that data passing between actions. For instance, if you use `gym` to build your IPA, you don't need to pass the IPA name to the other actions. If the Fastlane toolchain is handling generation, it retains that data for later lane actions. Its built for fairly minimal input. 

If you're using `sigh` to get your provisioning profiles then remove that named variable from `resign`, just provide your IPA file name, and possible signing identity if you have a bunch being access by `match`

**Comment by opetrovskyi** [comment]
i've though about the purpose of using `match` and `sigh` at the same time as the both download provisioning profile. I change the whole approach for my task. Now the lane do:
- `create_keychain`
- `match`
- `resign`
- `delete_keychain`
- `deliver`

to get this working i had to change ruby files of match module to add new variables for resign (signing_identity, provisioning_profile). It works but it'll be painful while updating fastlane.

Thanks for your reply, it is nice when somebody cares and trying to help.
