### ISSUE TITLE
New option in gym action

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7584]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to contribute. I want to write a new option in the gym action by enabling which it will record the compile time of the Xcode project and then write it to a txt file. I have added the option in https://github.com/RishabhTayal/fastlane/commit/397f9b41ba9bba6b8b747254b72324d90754b8f6#diff-440c4122de8c51769dc40db14188f030. How can I add the option to the actual command i.e. when `gym` runs `xcodebuild` command?

**Comment by joshdholtz** [comment]
@RishabhTayal The `xcodebuild` command get generated here - https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/generators/build_command_generator.rb#L7-L16

Somewhere in there (or the methods it calls) you would do something like...
```
if Gym.config[: analyze_build_time]
  parts << "your stuff"
end
```

 I think that is what you are looking for 😊

**Comment by RishabhTayal** [comment]
@joshdholtz Thanks for the pointer. When I try to use the local `fastlane` fork clone in my test project. I get error saying `The path /Users/rtayal/Desktop/Forks/fastlane_core does not exist.` Does that have anything to do with the new `fastlane` release process?

**Comment by joshdholtz** [comment]
@RishabhTayal I have not seen this yet myself but that sounds like it could be it (see issue https://github.com/fastlane/fastlane/issues/7579)

**Comment by RishabhTayal** [comment]
now I am getting this when I run `bundle install`

```
[!] There was an error parsing `Gemfile`: syntax error, unexpected tIDENTIFIER, expecting end-of-input - ...local_fastlane_path), "fastlane.gemspec"))
...                               ^. Bundler cannot continue.

 #  from /Users/rtayal/Downloads/asdfasfdasdf/Gemfile:7
 #  -------------------------------------------
 #  
 >  if File.exist?(File.join(File.expand_path(local_fastlane_path), "fastlane.gemspec"))
 #    local_fastlane_path = File.expand_path("..", local_fastlane_path)
 #  -------------------------------------------
```

**Comment by RishabhTayal** [comment]
@KrauseFx @hjanuschka any idea on why I am not able to test the changes locally?
