### ISSUE TITLE
Gem conflicts issue on fastlane update with terminal_table gem

### ISSUE THREAD

**Issue by Rameshv** [fastlane/fastlane#7593]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

After updating to the latest fastlane (2.1.1), i am seeing gem conflicts error for `terminal_table` gem. It used to work fine like an hour ago, after update i cant make any new builds.

Heres the screenshot of the error

![screen shot 2016-12-20 at 5 42 23 pm](https://cloud.githubusercontent.com/assets/750555/21350312/a841d92e-c6dc-11e6-8baf-58830e984fe3.png)

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                        |
| ------------------- | -------------------------------------------- |
| OS                  | 10.11.6                                      |
| Ruby                | 2.2.5                                        |
| Bundler?            | false                                        |
| Git                 | git version 2.6.4                            |
| Installation Source | ~/.rvm/gems/ruby-2.2.5/bin/fastlane          |
| Host                | Mac OS X 10.11.6 (15G31)                     |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.5/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                    |
| Is contained        | false                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer// |
| Xcode Version       | 8.0                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.95.0"

default_platform :ios

platform :ios do
  before_all do |lane, options|
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/"
    cocoapods
    increment_build_number_using_Shenzhen(options) unless options[:skipVersionNo]
    ENV['DEVELOPER_DIR'] = options[:xcodeDir] if options[:xcodeDir]
    ENV['MATCH_PASSWORD'] = options[:matchPass] if options[:matchPass]
  end

  # desc "Runs all the tests"
  # lane :test do
  #   scan
  # end

  desc "This lane updates the CFBundleShortVersionString & CFBundleVersion using Shenzhen::PlistBuddy"
  lane :increment_build_number_using_Shenzhen do |options|
    require 'Shenzhen' 
    puts 'incrementing build number'
    short_version = options[:version]
    bundle_version = 1
    if options[:build_number]
      bundle_version = options[:build_number]
    else
      old_version = Shenzhen::PlistBuddy.print(ENV['PLIST_PATH'], 'CFBundleVersion')
      bundle_version = old_version.to_i + 1 
    end
    puts "short version:: #{short_version}"
    puts "bundle version:: #{bundle_version}"
    Shenzhen::PlistBuddy.set(ENV['PLIST_PATH'], 'CFBundleShortVersionString', short_version)
    Shenzhen::PlistBuddy.set(ENV['PLIST_PATH'], 'CFBundleVersion', bundle_version)
  end

  desc "Match lane to download certificates from veezu-certs github repo"
  lane :download_certs do |options|
    cert_type = getFastlaneBuildType options
    puts " APP_IDENTIFIER :: #{ENV["APP_IDENTIFIER"]}"
    match(git_url: ENV["MATCH_URL"],
           type: cert_type,
           app_identifier: ENV["APP_IDENTIFIER"],
           username:  ENV["APPLE_ID"],
           force:true)
  end

  desc "This will add new UDIDs to the given profile and calls `download_certs` to get the veezu-certs match repo upto date"
  desc "Also this will download and install the new profile with the added UDIDs"
  lane :add_devices do |options|
    if options[:udids]
      devices = options[:udids].split '+'
      devices.each do |device|
        register_devices(
          username:ENV['APPLE_ID'],
          devices:{
            "Fastlane Added Device" =>  device
          }
        )
      end


    end
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do |options|
    add_devices options
   
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    if (options[:configuration])
      build_type =  options[:releaseType]#ad-hoc/app-store
      build_configuration = options[:configuration] # StagingServer/LiveServer/DevelopmentCloudServer
    else
      build_type = "ad-hoc" #ad-hoc/app-store
      build_configuration = "StagingServer" # StagingServer/LiveServer/DevelopmentCloudServer
    end

    unlock_keychain(path: "login.keychain", password: options[:systemPass] || ENV["SYSTEM_PASSWORD"])

    gym(
      scheme: ENV["SCHEME_NAME"],
      export_method: build_type,
      configuration: build_configuration,
      verbose: true,
      output_directory: "./build",
      use_legacy_build_api: true,
      toolchain: 'swift_2_3'
    )
    
    ENV['FASTLANE_PASSWORD'] =  ENV['ITUNES_PASSWORD']

    
    notes = changelog_from_git_commits

    # Upload the build to HockeyApp.
    hockey(
      api_token: ENV['HOCKEYAPP_TOKEN'],
      public_identifier: ENV['HOCKEYAPP_ID'],
      notes: notes,
      notes_type: "2",
      commit_sha: `git rev-parse HEAD`.strip,
      status: "2",
      repository_url:"https://github.com/xxxx"
    )

    uploaded_version = Actions.lane_context[Actions::SharedValues::HOCKEY_BUILD_INFORMATION]["id"]
    hockey_link = "https://rink.hockeyapp.net/apps/#{ENV['HOCKEYAPP_ID']}/app_versions/#{uploaded_version}"
    puts Actions.lane_context[Actions::SharedValues::HOCKEY_BUILD_INFORMATION]
    puts "Hockey version link #{hockey_link}"
    

  if build_type == 'app-store'
   pilot(skip_submission: true, username: ENV['APPLE_ID'])
  end

  clean_build_artifacts

    after_all do |lane|
      slack(
        message: "New #{ENV['SCHEME_NAME']} app is availabe here #{hockey_link}",
        channel: ENV["SLACK_CHANNEL"]
      )
    end

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end



  # You can define as many lanes as you want



  error do |lane, exception|
    slack(
      message: exception.message,
      success: false,
      channel: ENV["SLACK_CHANNEL"]
    )
  end
end

def getFastlaneBuildType(options)
   cert_type = "adhoc"
    if (options[:releaseType])
      if options[:releaseType] == "ad-hoc"
        cert_type = "adhoc"
      elsif options[:releaseType] == "app-store"
        cert_type = "appstore"
      else
        cert_type = "development"
      end
    end
    cert_type
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of your app
apple_id ENV["APPLE_ID"] # Your developer account email address
itunes_connect_id ENV["ITUNES_CONNECT_ID"] # Your itunes connect email address
team_id ENV["TEAM_ID"]  # Developer Portal Team ID
itc_provider ENV["TEAM_ID"]
username ENV["APPLE_ID"]
# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.6.3   |
| unicode-display_width     | 1.1.1   |
| terminal-table            | 1.7.3   |
| plist                     | 3.1.0   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| commander                 | 4.4.0   |
| excon                     | 0.45.4  |
| faraday                   | 0.9.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| logging                   | 2.1.0   |
| jwt                       | 1.5.4   |
| memoist                   | 0.14.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| thor                      | 0.19.1  |
| httpclient                | 2.8.0   |
| google-api-client         | 0.9.11  |
| mini_magick               | 4.5.1   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| bundler                   | 1.12.5  |
| faraday_middleware        | 0.10.0  |
| json                      | 1.8.3   |
| highline                  | 1.7.8   |
| rubyzip                   | 1.2.0   |
| xcodeproj                 | 1.2.0   |
| claide                    | 1.0.1   |
</details>

*generated on:* **2016-12-20**
</details>

**Comment by joshdholtz** [comment]
@Rameshv Are you running your comands with `bundle exec`? ie: `bundle exec fastlane <lane name>`? If not, can you try that? It looks like you have multiple `terminal_table ` gems installed and the system does not know which one to grab. `bundle exec` will make sure it `fastlane` will only use the one that is specified in the `Gemfile`

If that does not work for you, can you try updating to `2.2.0`? That was just released recently.

Thanks 😊

**Comment by Rameshv** [comment]
Thanks @joshdholtz for the reply
Unfortunately fastlane with `bundle exec` also not working.. For some funny reasons it started working after removing 1.7.3 version and restarting. :)
