### ISSUE TITLE
What is the best practice to have three bundle application (Dev, QA, PROD) on iOS  for ONE APP? 

### ISSUE THREAD

**Issue by Faisalcs** [fastlane/fastlane#7594]
### Issue Description
Hi everyone, How can I build an iOS application for different environments and keep tracking for each one?

After research I did I came up with this approach. 

 Achieving this on iOS, It means I have to have three targets in my ios project each target will have its own: 
1. Bundle identifier, entitlement, and plist.  
3. Every time I need to create extension I have to create three extensions to match three targets. 

I don't know but I believe I can minimize the process by using xcconfig but I'm struggling with it because of the lack of the documentation. Is there any way I can reach this by using the fastlane tool or not? 
### Environment

[INSERT OUTPUT HERE]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.0                          |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| cert                | 1.5.1   | 🚫 Update availaible |
| credentials_manager | 0.16.2  | 🚫 Update availaible |
| deliver             | 1.17.1  | 🚫 Update availaible |
| fastlane            | 2.0.5   | 🚫 Update availaible |
| fastlane_core       | 0.60.1  | 🚫 Update availaible |
| frameit             | 3.1.1   | 🚫 Update availaible |
| gym                 | 1.14.0  | 🚫 Update availaible |
| match               | 0.12.1  | 🚫 Update availaible |
| pem                 | 1.5.1   | 🚫 Update availaible |
| pilot               | 1.13.1  | ✅ Up-To-Date        |
| produce             | 1.5.1   | 🚫 Update availaible |
| scan                | 0.15.0  | 🚫 Update availaible |
| screengrab          | 0.6.1   | 🚫 Update availaible |
| sigh                | 1.13.1  | 🚫 Update availaible |
| snapshot            | 1.18.1  | 🚫 Update availaible |
| spaceship           | 0.39.0  | 🚫 Update availaible |
| supply              | 0.9.0   | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.1.1        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| commander                 | 4.4.1        |
| concurrent-ruby           | 1.0.2        |
| credentials_manager       | 0.16.2       |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 0.60.1       |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.4        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.1        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2016-12-20**
</details>

**Comment by ram0287** [comment]
You can have One Target in iOS  
     By default, each target will have Debug and Release Build Configuration
     Just add one more configuration and name it as QA

Use fastlane gym to build an ipa by passing configuration as a parameter ( Debug/Release/QA )

Simple. You can use any CI System to achieve this. :)

**Comment by Faisalcs** [comment]
Yes. Exactly but I didn't know how can I handle entitlement file. How can I handle it? 

Can you share sample project?

**Comment by joshdholtz** [comment]
@Faisalcs In your xcconfig (different for each of your environments) you would define the following...
```
// The path to a file specifying code-signing entitlements.
CODE_SIGN_ENTITLEMENTS = /path/to/your/entitlements/file.plist
```

This is a common practice I use in a majority of the apps I make 😊  I'm going to close this issue out for now though (since this isn't an issue with `fastlane` itself) but I will provide two great screencasts for leaning more about using xcconfigs if you need to find out more!

- http://nsscreencast.com/episodes/154-xcconfig-files
- http://nsscreencast.com/episodes/155-xcconfig-files-part-2

**Comment by Faisalcs** [comment]
Thank you guys. It's very clear now.
