### ISSUE TITLE
CredentialsManager README appears to be out of date after the mono gem migration

### ISSUE THREAD

**Issue by reidmain** [fastlane/fastlane#7599]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`fastlane-credentials` seems to have been removed as a command following the migration to a mono gem so https://github.com/fastlane/fastlane/blob/master/credentials_manager/README.md is now out of date.

I proceeded to install [xcode-install](https://github.com/KrauseFx/xcode-install) and ran `xcversion list` which prompted me for an Apple ID and password which I gave and was then somehow saved to the keychain. So it seems that the CredentialsManger has somehow been installed again but if I run `gem list` I don't see it.

How are we expected to use the CredentialsManager from the command line in the mono gem world?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                |
| ------------------- | ------------------------------------ |
| OS                  | 10.12.2                              |
| Ruby                | 2.3.1                                |
| Bundler?            | false                                |
| Git                 | git version 2.11.0                   |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane |
| Host                | Mac OS X 10.12.2 (16C67)             |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016          |
| Is contained        | false                                |
| Xcode Path          | /Library/Developer/CommandLineTools/ |
| Xcode Version       |                                      |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.2   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2016-12-20**
</details>

**Comment by joshdholtz** [comment]
@reidmain Thanks for letting us know and sorry about the issue! I will work on updating these docs to reflect the monogem updates. 

## How to run
 `fastlane fastlane-credentials add --username felix@krausefx.com`

## No gem in list
All the code that was in the `credentials_manager` gem is now moved into the single `fastlane` gem which is why it did not appear in your list. The same code is installed but its not in the separate gems anymore.

## Magically saved still
The same logic that happens in `fastlane-credentials` is used in many places through the fastlane codebase/actions. So when an actions asks for your email/password, it will first look for it in the keychain. If it is not found in the keychain, it will prompt you for it and save it there for you for furute uses.

Let me know if you have any questions about anything but I will work on fixing up that doc for you and everyone else 😊

**Comment by reidmain** [comment]
Thanks for addressing this so quickly. I'm sure I could have worked this out on my own but after the little snafu of removing credentials_manager 0.16.2 our CI environment was busted when running `bundle install` and I was scrambling a bit to try to understand the fix. Everything makes sense and is working now so good luck with the monogem.

**Comment by joshdholtz** [comment]
@reidmain No problem at all! This is what we are here for ❤️  Let us know if you have any other issues with anything!
