### ISSUE TITLE
Fastlane Throws me into Playground Console

### ISSUE THREAD

**Issue by barnaclebarnes** [fastlane/fastlane#7606]
### New Issue Checklist

- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines]

### Issue Description

I just updated to the latest (2.1.3) version of fastlane and it always throws me into the playground when I run a spaceship command:

```
➜  mytours-ios git:(develop) ✗ bundle exec fastlane spaceship build
Logging into to iTunes Connect (business@***.com)...
Successfully logged in to iTunes Connect

Logging into the Developer Portal (business@***.com)...
Successfully logged in to the Developer Portal

---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------

Enter docs to open up the documentation
Enter exit to exit the spaceship playground
Enter _ to access the return value of the last executed command

Just enter the commands and confirm with Enter

From: /Users/barnacle/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.1.3/spaceship/lib/spaceship/playground.rb @ line 63 Spaceship::Playground#run:

    58:
    59:       # rubocop:disable Lint/Debugger
    60:       binding.pry(quiet: true)
    61:       # rubocop:enable Lint/Debugger
    62:
 => 63:       puts "" # Fixes https://github.com/fastlane/spaceship/issues/203
    64:     end
    65:
    66:     def docs
    67:       url = 'https://github.com/fastlane/fastlane/tree/master/spaceship/docs'
    68:       `open '#{url}'`
```

Any ideas of why?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_NZ.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'byebug'

fastlane_version "1.111.0"

default_platform :ios

APP_SETTINGS = nil

platform :ios do
  before_all do
    APP_SETTINGS = JSON.parse(File.read('../Bundle/Updates/app.json'))
    cocoapods
  end

  desc "Create certificate and provisioning profiles"
  lane :provision_app do
    cert(output_path: './downloads/certificates')

    app_id                = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    watchkit_app_id       = "#{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}.watchkitapp"
    wathckit_extension_id = "#{CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)}.watchkitapp.watchkitextension"
    
    produce( app_name: APP_SETTINGS["name"],                         skip_itc: true, app_identifier: app_id)
    produce( app_name: "#{APP_SETTINGS["name"]} Wathckit App",       skip_itc: true, app_identifier: watchkit_app_id)
    produce( app_name: "#{APP_SETTINGS["name"]} Wathckit Extension", skip_itc: true, app_identifier: wathckit_extension_id)
    
    sigh( app_identifier: app_id,                 force: true, output_path: './downloads/provisioning_profiles', filename: "#{app_id}.mobileprovision" )
    sigh( app_identifier: watchkit_app_id,        force: true, output_path: './downloads/provisioning_profiles', filename: "#{watchkit_app_id}.mobileprovision" )
    sigh( app_identifier: wathckit_extension_id,  force: true, output_path: './downloads/provisioning_profiles', filename: "#{wathckit_extension_id}.mobileprovision" )

  end

  desc "Build a new version for the App Store"
  lane :build do
    app_id                = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    gym(scheme: "MyTours", output_directory: './downloads/builds', output_name: "#{app_id}.ipa")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    app_id = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    produce( app_name: APP_SETTINGS["name"], skip_itc: false, skip_devcenter: true, app_identifier: app_id)
    deliver
  end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.mytoursapp.kroad" # The bundle identifier of your app
apple_id "business@kroad.com" # Your Apple email address

team_id "3EUQ5Y2B6L"  # Developer Portal Team ID
# itc_team_id 118293679
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.1.3   | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.6        |
| rake                      | 12.0.0       |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| byebug                    | 9.0.6        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.2        |
| molinillo                 | 0.4.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.0.0        |
| coderay                   | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| credentials_manager       | 1.0.0        |
| httparty                  | 0.14.0       |
| method_source             | 0.8.2        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slop                      | 3.6.0        |
| pry                       | 0.10.4       |
| pry-byebug                | 3.4.2        |
| zip                       | 2.0.2        |
</details>

*generated on:* **2016-12-21**
</details>

**Comment by barnaclebarnes** [comment]
@fastlane-bot Nope - This happens even when we are just trying to use `cert` to generate a cert to start with.

**Comment by milch** [comment]
Hey @barnaclebarnes, thanks for submitting your issue. Sorry, but I'm not sure that I follow. I just tried it on spaceship `0.39.0` and it has the same behaviour - both `cert` and `build` are not spaceship commands. If you just want to run a fastlane lane, running `fastlane cert` or `fastlane build` is enough.

**Comment by barnaclebarnes** [comment]
@milch In my Fastfile I have the `cert` command. So I'm running:

`bundle exes fastlane spaceship provision_app`

And my `Fastfile` has:

```
 desc "Create certificate and provisioning profiles"
 lane :provision_app do
   cert(output_path: './downloads/certificates')
  # ... (produce, sign)
 end
```

Does this make sense? It seems to login to the developer portal and get no further.

**Comment by milch** [comment]
@barnaclebarnes Sorry about the confusion, but running `bundle exec fastlane provision_app` should be enough. You don't need the `spaceship` in there.

**Comment by barnaclebarnes** [comment]
@milch OK - This is an easy (maybe...) fix then. The warning you get when you run `bundle exec spaceship provision_app` is:

```
[WARNING] You are calling spaceship directly. Usage of the tool name without the `fastlane` prefix is deprecated in fastlane 2.0
Please update your scripts to use `fastlane spaceship provision_app` instead.
``

So that warning needs to change.

**Comment by milch** [comment]
@barnaclebarnes No, the warning is correct, you can't run spaceship directly anymore. So to fix your issue, Instead of running `bundle exec spaceship provision_app` you need to run `bundle exec fastlane provision_app`. Hope this helps!

**Comment by barnaclebarnes** [comment]
@milch But the warning you get says to "Please update your scripts to use `fastlane spaceship provision_app` instead:" It incorrectly states that you have to include the `spaceship` command when you don't.

**Comment by barnaclebarnes** [comment]
So yes - I now have it working but others will probably run into the same issue if they follow the warning instructions?

**Comment by milch** [comment]
> But the warning you get says to "Please update your scripts to use fastlane spaceship provision_app instead:" It incorrectly states that you have to include the spaceship command when you don't.

In the case of the command you ran originally (`spaceship provision_app`), the message is correct, albeit maybe a bit confusing since running spaceship with any parameters doesn't do anything. We can't really do much about that though, since at the stage where we output the warning we don't know anything about the context of the parameters of the tools and including that knowledge would require too much coupling.

**Comment by barnaclebarnes** [comment]
Ok - Closing then. Cheers for helping me sort out the correct command line to use. 👍
