### ISSUE TITLE
.assets/Gemfile produces error

### ISSUE THREAD

**Issue by joeboyscout04** [fastlane/fastlane#7610]
I'm working on my first PR for fastlane and read over the documentation here: [YourFirstPR](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md)

I followed the directions about copying the .assets/Gemfile to my project root and changed the path to:

local_fastlane_path = "~/Documents/Joulebug/Development/fastlane"

But running bundle install in my project root produces the following error:

"The path `/Users/josephelliott/Documents/Joulebug/Development/fastlane_core` does not exist."

Something may be wrong with the .assets/Gemfile or the documentation may need updating to add additional instructions. 

This issue was also mentioned by @akaralar here: https://github.com/fastlane/fastlane/pull/7575

**Comment by milch** [comment]
Hey @joeboyscout04, good catch, thanks for submitting your issue! I've just created a PR that will fix this.
