### ISSUE TITLE
Correct code signing for unit tests target

### ISSUE THREAD

**Issue by mfclarke** [fastlane/fastlane#7622]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Question

Hi guys, can I ask - what are the recommended code signing settings for a *unit test target* on Xcode 8, when running scan? I'm under the impression that if we have "Automatically manage signing" disabled, then we should select a team and signing certificate. But my CI provider is telling me otherwise and is asking me to completely disable code signing for my unit test target to resolve intermittent failures.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.1.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    if ENV["CIRCLE_TEST_REPORTS"] != nil
      output_dir = File.join(ENV["CIRCLE_TEST_REPORTS"], ENV["APP_TESTSCHEME"])
    else
      output_dir = "./output"
    end

    scan(
      scheme: "TestUnitTestsCircle",
      skip_build: true, # this still builds, but ensures it doesn't build twice for no reason
      devices: ["iPhone 6s (10.1)", "iPad 2 (8.4)"],
      output_directory: output_dir,
      output_types: "junit",
      custom_report_file_name: "report.xml"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<redacted>" # The bundle identifier of your app
apple_id "<redacted>" # Your Apple email address

team_id "<redacted>"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.3   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| aws-sdk-v1                | 1.66.0       |
| aws-sdk                   | 1.66.0       |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2016-12-21**
</details>

**Comment by mfclarke** [comment]
That's correct friendly @fastlane-bot but this case isn't covered by the guide :)

**Comment by mfclarke** [comment]
Thanks @hjanuschka ! I've just tried this, but it seems to still be signing the unit tests bundle. I'm seeing this in the log:

`Signing /Users/<redacted>/Library/Developer/Xcode/DerivedData/<redacted>-fauuzbhvhkwrsradonnqvekrlaqk/Build/Products/Debug-iphonesimulator/<redacted>.app/PlugIns/UnitTests.xctest`

It's this line in particular in the log that my CI provider has issue with, and says is causing the intermittent failures.

**Comment by hjanuschka** [comment]
hmmm strange, you could also try to disable signing on the target.

<img width="961" alt="bildschirmfoto 2016-12-21 um 16 10 30" src="https://cloud.githubusercontent.com/assets/2891702/21394224/1564e7e2-c798-11e6-9b96-2dc59dcbc020.png">

**Comment by mfclarke** [comment]
@hjanuschka This I tried before creating the issue, but still saw the `Signing` step of the xctest bundle in the logs.

I seem to remember in Xcode 6 and 7 that it would complain if signing was disabled for unit test targets. Did this change for Xcode 8? Is it actually supposed to be disabled for unit tests?

**Comment by hjanuschka** [comment]
sorry - i think that is beyond my scope!  - could you share the whole output?
and maybe if you have some time - create a sample (does not need to be your real app) repo with a reproducable test target? (so i ll can test it on my machine)

**Comment by mfclarke** [comment]
No problem @hjanuschka. I have resolved the issue with my CI provider, and it didn't seem to be related to code signing in the end. So I think we can close this - the normal Xcode defaults (specify team on the general page) work fine
