### ISSUE TITLE
PR Check: wiring up the "platform" option for deliver command-line

### ISSUE THREAD

**Issue by elliot-nelson** [fastlane/fastlane#7623]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Right now, you can set `--platform` on the deliver command-line, but the flag doesn't actually pass-through to the Runner's calls when it verifies the version and uploads the binary (this essentially breaks attempts to upload for the appletvos platform).

I have a PR ready to fix this, I can submit unless there are already plans in the work to fix this issue.

**Comment by milch** [comment]
> I have a PR ready to fix this, I can submit unless there are already plans in the work to fix this issue.

I don't know anything about that, so we'd very much welcome your PR if you decide to submit it!

**Comment by elliot-nelson** [comment]
PR has been reviewed, once merged this issue can be closed.  Thanks!

**Comment by elliot-nelson** [comment]
Done!
