### ISSUE TITLE
Actions to accept unlisted options in order to support forwarding of options passed via CLI

### ISSUE THREAD

**Issue by Sajjon** [fastlane/fastlane#7624]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I think that it would be nice to change the behaviour of how fastlane treats the `options` Hash, passed into Actions (both fastlane's "bundled" actions as well as custom actions).

The current behaviour is that if `my_bool: bool` to an action not listing `my_bool` as a `ConfigItem` in `available_options` method, fastlane executes halts with error. It is the method `verify_value_exists` inside the `class Configuration` in `FastlaneCore` module (file: `fastlane_core/lib/fastlane_core/configuration/configuration.rb`) that raises the exception/error.

Below is a somewhat simplified version of my setup, which I think is kind of neat, because I can work with fastlane and test my code by passing `dev_mode:true`, bypassing `git status clean` check. I can also pass `dry_run:true` so that I know that my lane does not actually send any IPA to iTC. But most importantly I can pass any value from CLI to every individual tool (gym, match, deliver) or action! 

But aha, no I cant! This setup results in `Could not find option '#{key}' in the list of available options`

```ruby
platform :ios do
  before_all do |lane, options|
    next if options[:dev_mode]
    ensure_git_status_clean
  end

  desc "Release app to App Store"
  lane :store do |options|
    begin
      # Wrapper of fastlane tool `match`, adding standard values to options, for sake of convenience
      my_match(options) # Forwarding of arguments, e.g. `:force_for_new_devices` or `readonly` from CLI
      #⬆️❌‼️ Causes crash, since `match` does not support options meant for `gym` like `clean` or my custom options `:dev_mode`, nor `:dry_run`
  
      # Wrapper of fastlane tool `gym`, adding standard values to options, for sake of convenience
      my_gym(options) # Forwarding of arguments, e.g. `clean`or `xcargs` from CLI
      #⬆️❌‼️ Causes crash, since `gym` does not support options meants for `match` like `force_for_new_devices` or my custom options `:dev_mode`, nor `:dry_run`
  
      return if options[:dry_run] # Do not continue with uploading of IPA to iTC if :dry_run
  
      deliver(options.merge({ team_id: "MyTeam" })) # Forwarding of arguments, e.g. `automatic_release` or `submit_for_review` from CLI 
      #⬆️❌‼️ Causes crash, since `deliver` does not support options meants for `match` or `gym` or my custom options
    rescue Interrupt
      cleanup(options)
    end
  end

  error do |lane, exception, options|
    cleanup(options) # see method declaration below
  end

  def cleanup(options)
    return if options[:dev_mode]
    clean_build_artifacts # Remove .ipa, .dSYM etc
    reset_git_repo # Reset changes in an other files
  end
end
```

Since fastlane actions does not accept non listed options we have to "extract" values from options hash, which makes the code bloated and very verbose, like this:

```ruby
desc "Release app to App Store"
lane :store do |options|
  begin
    # Wrapper of fastlane tool `Match`
    my_match(
      force_for_new_devices: options[:force_for_new_devices],
      readonly: options[:readonly]
    )

    # Wrapper of fastlane tool `Gym`
    my_gym(
      clean: options[:clean],
      xcargs: options[:xcargs]
    )
    
    return if options[:dry_run] # Do not continue with uploading of IPA to iTC if :dry_run

    deliver(
      team_id: "MyTeam",
      submit_for_review: options[:submit_for_review],
      automatic_release: options[:automatic_release]
    )
  rescue Interrupt
    cleanup(options)
  end
end
```

By changing two lines in the function `FastlaneCore::Configuration::verify_value_exists` to this:

```ruby
  def verify_value_exists 
      @values.each do |key, value|
        next if key == :trace # special treatment
        option = option_for_key(key)
        if option
          @values[key] = option.auto_convert_value(value)
          Fastlane::UI.deprecated("Using deprecated option: '--#{key}' (#{option.deprecated})") if option.deprecated
          option.verify!(@values[key]) # Call the verify block for it too
        else
          Fastlane::UI.error "Could not find option '#{key}' in the list of available options: #{@available_options.collect(&:key).join(', ')}, thus removing it"
          @values.delete(key)
        end
      end
  end
```

So what we do not raise an error and also deleting the non listed option form the hash we can have the short nice version of the lane `store`, listed here again without comments:

```ruby
desc "Release app to App Store"
lane :store do |options|
  begin
    my_match(options)
    my_gym(options)
    return if options[:dry_run]
    deliver(options.merge({ team_id: "MyTeam" }))
  rescue Interrupt
    cleanup(options)
  end
end
```

I was just about to create a PR when I read that I should open issue before.

### Feedback?
What do you think? Is not this nice? I understand there are some risks, e.g. if two actions/tools share the same name on an argument/option and said argument is passed in via CLI. But then I would just wrap that argument. Like this:

#### Problem

```bash
bundle exec fastlane store force:true
```

```ruby
foo(options) # Custom action `foo` accepts option `force`
bar(options) # Custom action `bar` accepts option `force`
# ⬆️❌‼️ oh no! option `force` was meant for `foo` not `bar`
```

#### Solution

```bash
bundle exec fastlane store foo_force:true
```

```ruby
foo(options[:force] = options.delete :foo_force)
bar(options)
```

### Captured Output

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:
Fastfile omitted

</details>

<details><summary>`./fastlane/Appfile`</summary>
Appfile omitted
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.1.3   | ✅ Up-To-Date  |
| deliver  | 2.0.1   | ✅ Up-To-Date  |
| gym      | 2.0.0   | ✅ Up-To-Date  |
| match    | 1.0.0   | ✅ Up-To-Date  |
| scan     | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| ast                       | 2.3.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| aws-sdk-v1                | 1.66.0       |
| babosa                    | 1.0.2        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.2        |
| molinillo                 | 0.5.4        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| curb                      | 0.9.3        |
| fastimage                 | 2.0.1        |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| parser                    | 2.3.3.1      |
| powerpack                 | 0.1.1        |
| rainbow                   | 2.1.0        |
| require_all               | 1.3.3        |
| ruby-progressbar          | 1.8.1        |
| rubocop                   | 0.46.0       |
</details>

*generated on:* **2016-12-21**
</details>
[15:12:51]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅

```

</details>

**Comment by Sajjon** [comment]
@KrauseFx Any input? Is this proposal too dangerous if actions share arguments using same name on the key?

**Comment by KrauseFx** [comment]
Hey @Sajjon, very interesting idea. Sorry for not coming back earlier. The reason why _fastlane_ throws an error when passing non-existing values is that when the user misread something from the documentation, or has a spelling mistake, they'd get a message, instead of failing silently, which would be quite dangerous. 
For shared configuration you can often use a tool specific config file, e.g. the `Gymfile` to have defaults, and only overwrite them if necessary. Wouldn't that solve your problem? 👍

**Comment by Sajjon** [comment]
Thanks for getting back to me so quickly after having pinged you @KrauseFx !

Sorry for not being clearer... The use case is this:
  1. Being able to pass options from CLI (thus a tool specific config file does not work)
  2. Being able to share option between different actions/custom ruby functions.

## Regarding 2. 
Many CLI tools have a `dry-run` option (e.g. [git](https://git-scm.com/docs/git-commit#git-commit---dry-run), [svn](http://svnbook.red-bean.com/en/1.7/svn.ref.svn.html), [gradle](https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:dry_run), [AWS S3](https://docs.aws.amazon.com/cli/latest/reference/s3/sync.html) etc ) that enables you to test your scripts without changing any state (e.g. a git repository) after the run.

I have incorporated this in my own actions. When I run one of my lanes, I want to be able to set the `dry_run` argument to `true` using CLI, like this:
```ruby
bundle exec fastlane my_lane dry_run:true
```

And I want the `dry_run` argument to propagate to all my custom actions and custom ruby helper functions etc.

That is why had used this example:
```ruby
desc "Release app to App Store"
lane :store do |options|
  begin
    my_match(options)
    my_gym(options)
    do_stuff(options)
    return if options[:dry_run]
    deliver(options.merge({ team_id: "MyTeam" }))
  rescue Interrupt
    cleanup(options)
  end
end
```

Where `my_match` and `my_gym` are ruby functions wrapping the `Match` and `Gym` tools with some extra logic and where `do_stuff` only performs some "state mutating" thing if the `dry_run` option is `false`.

Is there any other way of achieving **2.** ?

Maybe using `Actions::SharedValues::` somehow?

**Comment by KrauseFx** [comment]
I can now follow your example, and understand how it would be useful, great idea 👍  However I feel this would add complexity to the fastlane code base, and might end up in unplanned side effects when a user provides a value by mistake. 

We try to make _fastlane_ simpler, more stable and more robust, to make it more useful for more mobile app developers. 

You can probably easy build something not as elegant, but just as effective using ENV variables, or by accessing the lane context directly 👍 

Let me know if that works for you 😃

**Comment by ohayon** [comment]
Going to close this issue for now as it doesnt seem like we are going to take action on here. Feel free to continue discussion though! 😄 🐙
