### ISSUE TITLE
push_to_git_remote causing CI loop

### ISSUE THREAD

**Issue by MaikoHermans** [fastlane/fastlane#7644]
I'm not sure if this is the right place to ask since it really is a CI(Jenkins) related question but I can't seem to figure it out or find a solution anywhere so I'm hoping multiple people here have faced this problem and found a solution.

I'm committing/pushing a version bump to git in my beta lane. 
for my Jenkins builds to trigger I'm using webhooks. So when I push to my gitlab repo during my fastlane execution a new build will be triggered thus causing an infinite loop.

What I want to do is exclude a user from triggering builds. I tried to do this but it seems like this wil only work when using polling to trigger your jobs.
<img width="887" alt="screen shot 2016-12-21 at 15 34 28" src="https://cloud.githubusercontent.com/assets/6593958/21422899/68aec524-c83a-11e6-9f34-c1afa16e11f4.png">

Does anyone know a solution/fix for this? I know I could add `[ci skip]` to my commit but this will cause the build to trigger and abort. I don't want this behaviour either. I just don't want the build to get triggered at all.

**Comment by lacostej** [comment]
I haven't set that up yet (as we are not pushing from git), but will have to do it soon.

I think the solution is to:

1. use polling+notify commit method (http://kohsuke.org/2011/12/01/polling-must-die-triggering-jenkins-builds-from-a-git-hook/) not webhooks
2. use Jenkins git advanced options to filter out commits that come from fastlane

Feel free to update the Jenkins specific fastlane documentation when you have a working setup.

**Comment by MaikoHermans** [comment]
@lacostej 
I figured out how to do it with webhooks. I will update the specific fastlane documentation in a few. I'm only sure this works for gitlab tho. I will have to see if it works for GitHub as well.

**Comment by MaikoHermans** [comment]
@lacostej 
I've created a pull request
https://github.com/fastlane/docs/pull/246
