### ISSUE TITLE
iOS UniversalDistribution Provisioning Profile

### ISSUE THREAD

**Issue by DalenceSergio** [fastlane/fastlane#7647]
Hi,

I am trying to use match to generate provisioning profile for Universal Distribution.
I see that using match we can generate iOS Distribution and Development is there anyway to create iOS Universal Distribution using match?

**Comment by dombarnes** [comment]
Do you mean for Universal Purchase, i.e iOS and tvOS share a App Store Listing? If so, you just use the same bundle ID and provisioning profiles. I've been working on a pull request to add support for the `appletvos` platform that Apple's tools use when uploading, so you'd need different fast lane folders for each Xcode project.

**Comment by bassrock** [comment]
https://github.com/fastlane/fastlane/pull/7815 Was merged and it may solve your issue.
