### ISSUE TITLE
Output is buffered when running via 'bundle exec'

### ISSUE THREAD

**Issue by mjbeauregard** [fastlane/fastlane#7652]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm using gitlab-ci-multi-runner with the following configuration:
<details><summary>.gitlab-ci.yml</summary>

```yml
CI:
  stage: build
  script:
    - open -b com.apple.iphonesimulator
    - cd App
    - bundle install
    - bundle exec fastlane test
  tags:
    - xcode-8.2
```
</details>
When running fastlane like this (via `bundle exec`), it appears that stdout is buffered until fastlane completes which means I can't see live build progress via the gitlab web UI. If I change `.gitlab-ci.yml` to run fastlane directly (without bundle exec), output is not buffered and I see live build progress via the gitlab web UI. In either case, the build succeeds as expected.

Is there any way to fix this?

This stackoverflow answer might shed light on what is happening here: http://stackoverflow.com/questions/9949156/ruby-file-output-from-fork

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.2                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.11.0                                             |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.2 (16C67)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode-8.2.app/Contents/Developer/                |
| Xcode Version       | 8.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "Tests-CI", device: 'iPhone 6', clean: true, skip_slack: true)
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id ENV["APPLE_ID"]
team_id ENV["TEAM_ID"]  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.2.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| highline                  | 1.7.8        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| json                      | 1.8.3        |
| commander                 | 4.4.2        |
| rubyzip                   | 1.2.0        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2016-12-22**
</details>

**Comment by joshdholtz** [comment]
@mjbeauregard I don't have any experience with gitlab but it appears that this is an issue with `gitlab` and `bundle exec` (not an issue with `fastlane`)

What I _might_ suggest you try doing is at `STDOUT.sync = true` to the top of your `Fastile` and see if that does anything 😊  If you could try that and report back to me that would be awesome 🙌

**Comment by mjbeauregard** [comment]
Before posting this issue I tried adding `STDOUT.sync = true` to my `Appfile` (as opposed to my `Fastfile`) which didn't help. I assume that would have the same effect, but let me know if I'm mistaken.

I just switched over to the brew install rather than using gems directly, but that didn't make any difference.

**Comment by joshdholtz** [comment]
@mjbeauregard I thik rying to put it in `Fastfile` would be better since I _THINK_ that gets execute before the `Appfile` does but I have not had this issue so I am not able to verify 😊

**Comment by mjbeauregard** [comment]
I just tried that and it didn't help. I've also created an issue with gitlab: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1862

**Comment by joshdholtz** [comment]
Hopefully they are able to provide a little more insight into how things get executed on their side 😊

**Comment by mjbeauregard** [comment]
Yes, thanks for your help. I'll report back when I have more information.

**Comment by asutula** [comment]
@mjbeauregard Did you ever figure this out? I'm having the same problem and I'm not having much luck figuring it out. Thanks.

**Comment by mjbeauregard** [comment]
@asutula No I haven't found anything that helped. The thing I can add is that I am now seeing a little bit of output from gitlab in the browser:
```
Running with gitlab-ci-multi-runner 1.8.1 (a2efdd4)
Using Shell executor...
Running on Mac-mini.local...
Fetching changes...
Removing App/fastlane/report.xml
Removing App/fastlane/test_output/
HEAD is now at f4ebe026 Finish link service and tests
Checking out 21a69c3f as link-service...
$ open -b com.apple.iphonesimulator
$ cd App
$ fastlane test
```
Followed by the spinning arrows with no more output until fastlane is finished. This is a slight improvement from before where I didn't get any output at all until fastlane was finished. I'm not sure what changed other than having updated fastlane periodically.

**Comment by asutula** [comment]
Yea I actually noticed yesterday that I started seeing live output on Gitlab again. I didn't change anything on my end, so maybe this was an issue with Gitlab.
