### ISSUE TITLE
Invalid byte sequence with invalid strings file

### ISSUE THREAD

**Issue by lyptt** [fastlane/fastlane#7661]
### New Issue Checklist

- [✔︎] Updated fastlane to the latest version
- [✔︎] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

One of our devs updated our Localisable.strings file which turned out to be invalid, but for some reason we ended up having an issue with fastlane invoking our build. Instead of getting a normal build error about the invalid file format, fastlane blew up.

The error we expected to get (which was in fact recorded in the gym log when disabling xcpretty):

```
Base.lproj/Localizable.strings:0: error: read failed: The data couldn't be read because it isn't in the correct format.
```

The error we actually got:

```
08:23:08.848 > Copying Localizable.strings
08:23:08.848 /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:422:in `===': invalid byte sequence in US-ASCII (ArgumentError)
08:23:08.848 from /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:422:in `update_test_state'
08:23:08.848 from /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/lib/xcpretty/parser.rb:299:in `parse'
08:23:08.848 from /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/lib/xcpretty/formatters/formatter.rb:87:in `pretty_format'
08:23:08.848 from /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/lib/xcpretty/printer.rb:19:in `pretty_print'
08:23:08.849 from /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/bin/xcpretty:84:in `block in <top (required)>'
08:23:08.849 from /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `each_line'
08:23:08.849 from /Users/build/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/xcpretty-0.2.4/bin/xcpretty:83:in `<top (required)>'
08:23:08.849 from /Users/build/.rbenv/versions/2.2.2/bin/xcpretty:22:in `load'
08:23:08.849 from /Users/build/.rbenv/versions/2.2.2/bin/xcpretty:22:in `<main>'
08:23:08.849 ** ARCHIVE FAILED **
```

**Comment by joshdholtz** [comment]
@lyptt This _seems_ like you need to tell your CLI how to encode stuff. You can either set environment variables to fix this like... http://stackoverflow.com/a/17031697

```bash
# from your command line
# this can also be set in your .bash_profile, .bachrc, .zshrc, etc
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
bundle exec fastlane <your lane>
```

or put this at the top of your `Fastfile`

```rb
if RUBY_VERSION =~ /1.9/ # assuming you're running Ruby ~1.9
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end
```

This has solved similar issues for me before but let me know if this still doesn't work for you and we can try to figure out what actually does 😊

**Comment by lyptt** [comment]
Unfortunately @joshdholtz this didn't help at all with this issue. We added those exports to our profile as suggested in another bug fix and it had zero effect.

**Comment by lyptt** [comment]
I should state again that fixing the contents of our Localizable.strings file is what fixed the issue, not updating our environment. This leads me to believe there's an actual code issue going on with Fastlane/xcpretty, rather than anything else. Otherwise it would be nothing to do with our strings file.

**Comment by joshdholtz** [comment]
@lyptt Do you have an example of the bad `Localizable.strings` file that you could share so I can take a look at what was causing it / how to prevent this from happening in the future?

**Comment by KrauseFx** [comment]
In general, a project to reproduce the issue would help 👍
