### ISSUE TITLE
[!] undefined method `release_on_approval=' for nil:NilClass

### ISSUE THREAD

**Issue by tuenguyenhd** [fastlane/fastlane#7668]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rvm/rubies/ruby-2.2.1/bin/fastlane       |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/XCode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do

  # desc "Deploy a new version to the App Store"
  # lane :"233_prepare" do    
  #   # produce(
  #   #    username: 'username@gmail.com',
  #   #    app_identifier: 'com.ltv.dmr.233',
  #   #    app_name: 'Indian Recipes - Free Sweet and Spicy Indian Food',
  #   #    language: 'English',
  #   #    app_version: '1.0',       
  #   #  )  
  #   #  deliver(
  #   #  screenshots_path: "fastlane/233/screenshots/",
  #   #  metadata_path: "fastlane/233/metadata/",
  #   #  app_identifier: "com.ltv.dmr.233",
  #   #  skip_binary_upload: true,
  #   #  force: true
  #   #  )           
  #   snapshot    
  #   sigh(
  #   username: 'username@gmail.com',
  #   app_identifier: 'com.ltv.dmr.233',    
  #   )
  # end
  
  desc "Deploy a new version to the App Store"
  lane :"276_prepare" do    
    # produce(
    #    username: 'username@gmail.com',
    #    app_identifier: 'com.ltv.dmr.276',
    #    app_name: 'Cake Recipes - Easy and Delicious Cake',
    #    language: 'English',
    #    app_version: '1.0',       
    #  )  
    deliver(
    screenshots_path: "fastlane/276/screenshots/",
    metadata_path: "fastlane/276/metadata/",
    app_identifier: "com.ltv.dmr.276",
    skip_binary_upload: true,     
    edit_live: true,
    force: true
    )           
    snapshot    
    sigh(
    username: 'username@gmail.com',
    app_identifier: 'com.ltv.dmr.276',    
    )
  end      
  
  lane :"233_deploy" do    
     gym(
          scheme: "DMR233",
          output_directory:"fastlane/233/"
     )
  
     deliver(
     screenshots_path: "fastlane/233/screenshots/",
     metadata_path: "fastlane/233/metadata/",
     app_identifier: "com.ltv.dmr.233",
     app_icon: "fastlane/233/233.png",  
     app_rating_config_path: "fastlane/rating_config.json",   
     ipa: "fastlane/233/DMR233.ipa",
     force: true,
     app_review_information: ({
       first_name: "Linh",
       last_name: "Hoang",
       phone_number: "+84946652992",
       email_address: "username@gmail.com",
       demo_user: "",
       demo_password: "",
       notes: ""
     })     
     )           
  end  

  # lane :"193" do
  #   gym(scheme: "DMR193")
  #   
  #   deliver(metadata_path: "../193/metadata/",
  #   screenshots_path: "../193/metadata/screenshots/",
  #   app_identifier: "com.ltv.dmr.193")    
  #   # deliver(force: true)
  #   # frameit
  # end  

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "n" # The bundle identifier of your app
apple_id "username@gmail.com" # Your Apple email address

team_id "BPY783VY4D"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.13.6  |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.10.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.6.3   |
| plist                     | 3.1.0   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| highline                  | 1.7.2   |
| commander                 | 4.4.0   |
| excon                     | 0.45.3  |
| faraday                   | 0.9.2   |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.11.0  |
| logging                   | 2.1.0   |
| jwt                       | 1.5.3   |
| memoist                   | 0.14.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.2   |
| googleauth                | 0.5.1   |
| thor                      | 0.19.1  |
| httpclient                | 2.7.1   |
| google-api-client         | 0.9.4   |
| mini_magick               | 4.5.1   |
| multi_xml                 | 0.5.5   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| faraday_middleware        | 0.10.0  |
| json                      | 1.8.3   |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.2   |
| xcodeproj                 | 1.4.1   |
| terminal-table            | 1.5.2   |
</details>

*generated on:* **2016-12-24**
</details>

**Comment by KrauseFx** [comment]
Please share the complete output and the stack trace

**Comment by hjanuschka** [comment]
i am going to close this because of missing information, feel free to reopen the issue with a stacktrace included, so we can help you!
