### ISSUE TITLE
Cruising from regular lanes to platform lanes would be immensely helpful

### ISSUE THREAD

**Issue by kdubb** [fastlane/fastlane#7676]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We are building frameworks (and test applications) that support iOS & macOS (soon we'll be adding watchOS & tvOS).  We've just completed automating our entire build & test cycle with fastlane.... Awesome work!

Currently we use the "platform" feature to make lanes for specific platforms which is working well. It seems the suggested method of building both platforms is to use something like 'fastlane ios build_and_test && fastlane mac build_and_test'.  Since parts of our fastlane automation includes starting/stopping docker containers to run integration tests against, this causes needless starting/stopping of containers just to switch platforms.

For example, executing this on the command line:
```
fastlane ios build_and_test && fastlane Mac build_and_test
```
Causes the docker containers to be started and stopped twice; once for each platform. It's only going to get worse once we add more platforms.

Alternatively, If we had the ability to do something along these lines in the `Fastfile`:
```ruby
platform :ios do
  lane build_and_test do
  end
end

platform :mac do
  lane build_and_test do
  end
end

lane build_and_test do

  start_server

  begin

    #using "platform" to switch platforms inside a lane
    platform :ios do
      build_and_test
   end

    #using "platform" to switch platforms inside a lane
    platform :mac do
      build_and_test
   end

  ensure
    stop_server
  end

do
```

There are 2 or 3 cases we could use this feature if it were available.  It would allow us to offer more lanes to our developers that easily build and test what they are working on.

Without this a rework of our Fastfile is needed to separate it out of platforms and use non-platform lanes & options to allow executing our lanes for the platforms we need.

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.2                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.2 (16C67)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'yaml'

workspace = "MessagesKit.xcworkspace"
edge_compositions = {
  'test' => "fastlane/edge-test-compose.yml",
  'dev' => "fastlane/edge-dev-compose.yml"
}


# Build Configuraion

$build = YAML.load(open('../build.yaml'))

before_all do

  # Set environment variables for docker-compose
  container = $build['server']['container']
  ENV['EDGE_CONTAINER_REG'] = container['registry']
  ENV['EDGE_CONTAINER_REPO'] = container['repository']
  ENV['EDGE_CONTAINER_TAG'] = container['tag']

  # Cocoapods
  unless ENV['NO_PODS']
    
    cocoapods

  end

end

# MARK: Test Server Environment

desc "Starts an Edge server environment (Docker composition)"
lane :start_environment do |options|

  type = options[:type] || :dev
  name = options[:name] || type
  pull = options[:pull] || true

  files = [
    edge_compositions[type.to_s]
  ]

  # Pull image (if requested)
  if pull
    docker_compose(
      files: files,
      command: "pull"
    )
  end

  docker_compose(
    files: files,
    command: "up",
    project: name.to_s
  )
  
  port_info = docker_port(
    container: "#{name}_edge_1",
    port: 8080,
  )

  # Ensure we have a publicly usable address
  if port_info[:host] == '0.0.0.0'
    ip = Socket.ip_address_list.detect{|intf| intf.ipv4_private?}
    port_info[:host] = ip.ip_address
  end

  http_service_available(
    target: "http://#{port_info[:host]}:#{port_info[:port]}/admin/healthcheck"
  )
  
  port_info
end


desc "Stops an Edge server environment (Docker composition)"
lane :stop_environment do |options|

  type = options[:type] || :dev
  name = options[:name] || type

  files = [
    edge_compositions[type.to_s]
  ]

  docker_compose(
    files: files,
    command: "down",
    project: name.to_s
  )
end

lane :build_and_test do

  Fastlane::LaneManager.cruise_lane('mac', 'build_and_test')

end

# MARK: iOS Tests

platform :ios do

  sim_os_versions = [
    '10.2'
  ]

  sim_device_types = [
    'iPhone 7',
    'iPhone 5'
  ]

  lane :build_and_test do |options|

    # Simulator testing

    xctest_build(
      workspace: workspace,
      scheme: "MessagesKit-iOS-Testing",
      simulator: true
    )

    unit_tests(
      sim_os_versions: sim_os_versions,
      sim_device_types: sim_device_types
    )

    integration_tests(
      sim_os_versions: sim_os_versions,
      sim_device_types: sim_device_types
    )


    # Device testing
    devices = FastlaneCore::DeviceManager.connected_devices("iOS")
    unless devices.empty?

      xctest_build(
        workspace: workspace,
        scheme: "MessagesKit-iOS-Testing",
        simulator: false
      )

      devices = devices.map { |d| d.udid }

      unit_tests(
        devices: devices
      )

      integration_tests(
        devices: devices
      )
    
    end

  end

  lane :unit_tests do |options|

    xctest_run(
      **options,
      skip_testing: [
        'MessagesKit-iOSTests/RoundTripTests',
        'MessagesKit-iOSTests/MessagesKitTests'
      ],
      output_type: 'Unit',
      fail_build: false
    )

  end

  lane :integration_tests do |options|
    
    integration_id = (0...8).map { (65 + rand(26)).chr }.join.downcase

    server_info = start_environment(
      type: :test,
      name: integration_id,
      pull: true
    )

    begin

      xctest_run(
        **options,
        launch_args: [
          "-io.retxt.test.Host #{server_info[:host]}",
          "-io.retxt.test.Port #{server_info[:port]}"
        ],
        only_testing: [
          'MessagesKit-iOSTests/RoundTripTests',
          'MessagesKit-iOSTests/MessagesKitTests'
        ],
        output_type: 'Integration',
        fail_build: false
      )

    ensure

      stop_environment(
        type: :test,
        name: integration_id
      )

    end

  end

end

# MARK: macOS Tests

platform :mac do

  lane :build_and_test do |options|

    xctest_build(
      workspace: workspace,
      scheme: "MessagesKit-macOS-Testing",
      code_coverage: true
    )
    
    # unit_tests

    integration_tests
    
  end

  lane :unit_tests do |options|
    
    xctest_run(
      archs: [
        'x86_64'
      ],
      skip_testing: [
        'MessagesKit-macOSTests/RoundTripTests',
        'MessagesKit-macOSTests/MessagesKitTests'
      ],
      output_type: 'Unit',
      fail_build: false
    )
        
  end

  lane :integration_tests do |options|
    
    integration_id = (0...8).map { (65 + rand(26)).chr }.join.downcase

    server_info = start_environment(
      type: :test,
      name: integration_id,
      pull: true
    )

    begin

      xctest_run(
        archs: [
          'x86_64'
        ],
        launch_args: [
          "-io.retxt.test.Host #{server_info[:host]}",
          "-io.retxt.test.Port #{server_info[:port]}"
        ],
        only_testing: [
          'MessagesKit-macOSTests/RoundTripTests',
          'MessagesKit-macOSTests/MessagesKitTests'
        ],
        output_type: 'Integration',
        fail_build: false
      )

    ensure
      
      stop_environment(
        type: :test,
        name: integration_id
      )

    end

  end

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| json                      | 1.8.3        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
</details>

*generated on:* **2016-12-26**
</details>

**Comment by KrauseFx** [comment]
Hey it seems like your setup is pretty advanced. You can always use standard Ruby features to do the same thing by using classes and methods, and therefore having more control over the behaviour 👍

**Comment by kdubb** [comment]
@KrauseFx Isn't that an argument you could make about fastlane itself?  Sure it's doable in Ruby but it's a lot of verbose code. Fastlane has mostly made that code very small and concise.  With a simple added feature (which seems very intuitive, you're just putting the platform selector in the lane instead of around the lane) we could continue using the brevity of Fastlane and achieving our goals.  Your suggestion seems to be to go "rewrite it" in Ruby; that seems odd to me.

**Comment by PetrosIchor** [comment]
I understand where you're coming from kdubb, but don't think it's as big a lift as it appears. 

You're example isn't really enough information to discuss deeper, but I would recommend simply removing the platforms from fastlane and using options or environment flags to trigger what you need. 

For example: 

```
# Add to the top of your fastfile or before all step
@platform = options[:platform].split(',')

#  ---------------- later in your fastfile --------------
lane :build_and_test do |lane, options|
  start_server
  @platform.each do |agency| 
     'some build and test actions'
  end
end
```

Using the `options` feature you'd simply need run something like this:

`fastlane build_and_test platform:ios,mac`

There's a massive amount of options for driving more customized lanes. Personally, I ditched the `platform` lane early on when setting up fastlane.  They were creating more complexity than I needed. 

More info on options/environment flags: https://docs.fastlane.tools/advanced/

**Comment by kdubb** [comment]
@PetrosIchor In some ways I agree.  Since creating this issue our Fastfile has been re-engineered to work somewhat like you've proposed.  It's a lot more "manual" and a big backtrack from the road fastlane documentation suggested we go down... but it works.

None of this detracts from my main point that not being able to call a "platform lane" from a "lane" is severely limiting of the platforms feature in general.  So limiting in fact, everybody suggests ditching it in favor of more complex methods.  Also, the limitations aren't outlined anywhere in fastlane docs. People moving to fastlane with a complex setup walk a pretty far road only to find out they need to backtrack.  Finally, the solution *_seems_* like it would be fairly easy and I proposed. a natural extension that would make pretty good sense. 

So, instead of telling people to ditch the feature, why not make it more useful?

**Comment by KrauseFx** [comment]
@kdubb _fastlane_ is an open source project, everyone can contribute and build their own features to make it better, however we have to keep the core as small and solid as possible. 

I don't have a full understanding yet on how the feature would look like and what changes in the code would be necessary. If you submit a proposal with a summary of what has to be changed in the code base, and how it would affect existing setups, it's definitely something you could submit a PR for if you'd like 👍 

_fastlane_ is a big open source project, with lots of feature requests, and we have to prioritise those that will help a majority of the user-base.

If you don't have the time for this right now, the easiest way for you is to probably use `private_lanes` in combination with regular lanes that call each other. Instead of using the platform block, name your lanes `ios_build_and_test` to have a similar effect.

Sorry if you don't feel that answer is helpful, however there is not much more we can do for now, unless there is more people having the same problem.

**Comment by joshdholtz** [comment]
@kdubb If you still need to do this, it _can be_ accomplished like this (right now)...

```rb
lane :setup do
  self.runner.current_platform = :android
  setup
  
  self.runner.current_platform = :ios
  setup
end

platform :android do
  lane :setup do
    # stuff
  end
end

platform :ios do
  lane :setup do
    # stuff
  end
end
```

**Comment by hjanuschka** [comment]
@joshdholtz nice workaround, actually we are using a similar setup since a few months.


```
lane :beta do | options |
        Fastlane::LaneManager.cruise_lane("ios", "beta", options)
        Fastlane::LaneManager.cruise_lane("android", "beta", options)
end

platform :ios do
        lane :beta do
                UI.message "ios beta"
        end
end


platform :android do
        lane :beta do
                UI.message "android beta"
        end
end

```

**Comment by joshdholtz** [comment]
@hjanuschka That is much prettier 👌
