### ISSUE TITLE
Fish shell integration issue.

### ISSUE THREAD

**Issue by dzan** [fastlane/fastlane#7677]
New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane install scripts ask the user to add the following line to their fish shell configuration;

`set -x PATH $HOME/.fastlane/bin $PATH`

However the layout of the `.fastlane` folder is the following;

```
└── bin
    └── fastlane_lib
        ├── ...
        ├── fastlane
        ├── ...
```
Because of this `fastlane` itself will not be in the user's PATH because fish (and other shells?) don't look in subdirectories it seems.

Fixes;

- Symlink `fastlane` to the bin folder itself.
- Add the `$HOME/.fastlane/bin/fastlane_lib` folder to the path instead.

Kind regards,
Sander

**Comment by fulldecent** [comment]
I installed using `brew cask install fastlane`. It makes this recommendation:

> ==> Couldn't detect shell config file (fish - ~/.config/fish/config.fish)
> ==> Please add the following line to your fish profile:
> ==> set -x PATH $HOME/.fastlane/bin $PATH

Then I fixed the problem by doing:

    echo 'set -x PATH $HOME/.fastlane/bin $PATH' > ~/.config/fish/config.fish

**Comment by KrauseFx** [comment]
Hey everyone, I'm not a fish user myself, sorry that this happened. Can you join the discussion over there https://github.com/fastlane/fastlane/issues/7724 👍

**Comment by agisilaos** [comment]
Thank you @fulldecent!!!!
