### ISSUE TITLE
[Error] specifies a non-existent file for the CFBundleExecutable key

### ISSUE THREAD

**Issue by koxon** [fastlane/fastlane#7679]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

xcrun throws an error on the Bundle I have in my project. The project compiles and launch fine in XCode though.

```
[14:41:57]: $ /usr/bin/xcrun /Users/nico/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.3.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/nf/vb_nt19s0sqcygc79bw731z40000gn/T/gym_config20161227-32539-1du5v9t.plist' -archivePath /Users/nico/Library/Developer/Xcode/Archives/2016-12-27/bFan-ios-dev\ 2016-12-27\ 14.37.49.xcarchive -exportPath '/var/folders/nf/vb_nt19s0sqcygc79bw731z40000gn/T/gym_output20161227-32539-1cyl2vb'
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/nf/vb_nt19s0sqcygc79bw731z40000gn/T/gym_config20161227-32539-1du5v9t.plist -archivePath '/Users/nico/Library/Developer/Xcode/Archives/2016-12-27/bFan-ios-dev 2016-12-27 14.37.49.xcarchive' -exportPath /var/folders/nf/vb_nt19s0sqcygc79bw731z40000gn/T/gym_output20161227-32539-1cyl2vb
2016-12-27 14:42:02.538 xcodebuild[37360:975617] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/nf/vb_nt19s0sqcygc79bw731z40000gn/T/bFan-ios-dev_2016-12-27_14-42-02.537.xcdistributionlogs'.
1.2.840.113635.100.1.61
1.2.840.113635.100.1.61
1.2.840.113635.100.1.61
2016-12-27 14:42:18.245 xcodebuild[37360:975617] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7ff661dc7320>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.

Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}

** EXPORT FAILED **
```

In the logs, I have the following:

```
2016-12-27 13:42:18 +0000  error: Info.plist of “bFan - DEV.app/VGPlayer.bundle” specifies a non-existent file for the CFBundleExecutable key
2016-12-27 13:42:18 +0000 [MT] /Applications/Xcode.app/Contents/Developer/usr/bin/ipatool exited with 1
2016-12-27 13:42:18 +0000 [MT] ipatool JSON: {
    alerts =     (
                {
            code = 2567;
            description = "Configuration issue: platform AppleTVSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        },
                {
            code = 2567;
            description = "Configuration issue: platform iPhoneSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        },
                {
            code = 2567;
            description = "Configuration issue: platform WatchSimulator.platform doesn't have any non-simulator SDKs; ignoring it";
            info =             {
            };
            level = WARN;
        },
                {
            code = 0;
            description = "Info.plist of \U201cbFan - DEV.app/VGPlayer.bundle\U201d specifies a non-existent file for the CFBundleExecutable key";
            info =             {
            };
            level = ERROR;
            type = "malformed-payload";
        }
    );
}
```

The Info.Plist file in the bundle contains the CFBundleExecutable key though.

My Gym command:

```
gym(
      workspace: "bFan-ios-dev.xcworkspace",
      scheme: org + "-ios-dev",
      output_name: org + "-ios-dev.ipa",
      clean: false,
      derived_data_path: "/var/tmp/derived_data",
      output_directory: "build"
    ) 
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C68)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.2        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

**Comment by mpirri** [comment]
@koxon as you may know, `gym` uses the `xcodebuild` command line tool to build your project. Have you tried feeding the arguments to `gym` into a direct call to `xcodebuild`?

You should be able to do something like this:
```
xcodebuild -workspace bFan-ios-dev.xcworkspace -scheme '<org>-ios-dev' build
```
You made need to add a few more options to make the build succeed (you can see the other options required by doing `xcodebuild -help`, and any command line errors should point you in the right direction), but I'm curious to know if `xcodebuild` will fail with the same error as `gym`, or if you will get a successful build.

**Comment by koxon** [comment]
Thanks. I just tested and it builds fine with your command. No other options required.

What doesn't work is is the -exportArchive and provided options. That fails.
The archive folder contains a bunch of project files, an Info.plist at the root, my Bundle, and inside the Bundle another Plist file. 

Not sure why this bundle creates a problem :(

**Comment by koxon** [comment]
I think it was a signing issue. I also deleted the CFBundleExecutable key in the Bundle Plist. 
Closing
