### ISSUE TITLE
ITMS-90046 when delivering

### ISSUE THREAD

**Issue by scottlemke** [fastlane/fastlane#768]
With the same profiles and app setup that has been fine in the past, I now get this error when trying to deliver.

[Transporter Error Output]: ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value '*' for key 'com.apple.developer.associated-domains' in 'Payload/{App.app/App}' is not supported."

I have 3 values configured in Xcode for associated-domains and the checkbox is checked on the App in iTunes Connect. Any ideas?

**Comment by KrauseFx** [comment]
How do you build your app? Using `gym`? If so, can you try passing the `use_legacy_build_api`?

**Comment by scottlemke** [comment]
I use gym, and I have to use use_legacy_build_api for my alpha lane since the export would always fail. I'll try it on my release lane as well, which is where I'm seeing this error, and let you know.

**Comment by scottlemke** [comment]
I tried with the use_legacy_build_api flag set and it still failed with the same error.

**Comment by scottlemke** [comment]
It seems like it's not pulling in the additional entitlements that are specified in the Entitlements file. It's just using the entitlements that are in the provisioning profile. The prepared archive that Xcode shows when I submit from the Xcode organizer displays the correct associated domains pulled in from the Entitlements.plist. Does the make sense at all? I'm not too familiar with the signing process.

**Comment by scottlemke** [comment]
I found a fix for this. I was re-signing after gym to ensure that the IPA was signed with the app store profile before delivering. I think this was causing the incorrect entitlements. I removed the re-signing and it works now. Still seems like a possible bug in resign?

**Comment by KrauseFx** [comment]
Great to hear :+1:

**Comment by samsonjs** [comment]
I just hit this bug and I'd really like to resign instead of building again.

**Comment by JMCPH** [comment]
I get the same error after changing the GoogleService-Info.plist and then resigning the .ipa file. What were the fix to get it to work with resign? It seems like it does not sign the cocoa pods too.

**Comment by TKBurner** [comment]
Hi @JMCPH Can you submit a new issue for this? Thanks!
