### ISSUE TITLE
deliver: No value found for 'edit_live'

### ISSUE THREAD

**Issue by MarkMolina** [fastlane/fastlane#7680]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The deliver command fails after checking the version in iTC.
```
[16:11:19]: fastlane finished with errors

[!] No value found for 'edit_live'
```

Might be related to this PR: https://github.com/fastlane/fastlane/pull/7172

##### Complete output when running fastlane, including the stack trace and command used
[[16:11:11]: --- Step: deliver ---
[16:11:11]: ---------------------
[16:11:12]: Successfully loaded '/archive/jenkins/workspace/iOS-release-build/fastlane/Deliverfile' 📄

+-----------------------+-----------------------------+
|    Detected Values from './fastlane/Deliverfile'    |
+-----------------------+-----------------------------+
| app                   | 10101010101                   |
| username              | mobile-admin@travelbird.com |
+-----------------------+-----------------------------+

[16:11:12]: Login to iTunes Connect (mobile-admin@travelbird.com)
[16:11:15]: Login successful

+-----------------------+-------------------------------------------------------------------+
|                                   deliver 2.3.0 Summary                                   |
+-----------------------+-------------------------------------------------------------------+
| ipa                   | /archive/jenkins/workspace/iOS-release-build/build/TravelBird.ipa |
| force                 | true                                                              |
| skip_screenshots      | true                                                              |
| skip_metadata         | true                                                              |
| username              | mobile-admin@travelbird.com                                       |
| screenshots_path      | ./fastlane/screenshots                                            |
| metadata_path         | ./fastlane/metadata                                               |
| app_version           | 6.6                                                               |
| app_identifier        | nl.travelbird.TravelBird                                          |
| platform              | ios                                                               |
| skip_binary_upload    | false                                                             |
| submit_for_review     | false                                                             |
| automatic_release     | false                                                             |
| overwrite_screenshots | false                                                             |
+-----------------------+-------------------------------------------------------------------+

[16:11:16]: Making sure the latest version on iTunes Connect matches '6.6' from the ipa file...
[16:11:18]: '6.6' is the latest version on iTunes Connect
[16:11:18]: -------------------
[16:11:18]: --- Step: slack ---
[16:11:18]: -------------------
[16:11:19]: Successfully sent Slack notification
+----------------------------+---------------------------------------------------------------------+
|                                           Lane Context                                           |
+----------------------------+---------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                 |
| PLATFORM_NAME              | ios                                                                 |
| LANE_NAME                  | ios release                                                         |
| SIGH_PROFILE_TYPE          | app-store                                                           |
| IPA_OUTPUT_PATH            | /archive/jenkins/workspace/iOS-release-build/build/TravelBird.ipa   |
| DSYM_OUTPUT_PATH           | /archive/jenkins/workspace/iOS-release-build/build/TravelBird.ap... |
| XCODEBUILD_ARCHIVE         | /Users/tbmobileci2/Library/Developer/Xcode/Archives/2016-12-27/T... |
| SCAN_DERIVED_DATA_PATH     | /Users/tbmobileci2/Library/Developer/Xcode/DerivedData/TravelBir... |
| SCAN_GENERATED_PLIST_FILES | ["/Users/tbmobileci2/Library/Developer/Xcode/DerivedData/TravelB... |
| SCAN_GENERATED_PLIST_FILE  | /Users/tbmobileci2/Library/Developer/Xcode/DerivedData/TravelBir... |
+----------------------------+---------------------------------------------------------------------+
[16:11:19]: No value found for 'edit_live'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 274         |
| 4    | match                               | 13          |
| 5    | match                               | 7           |
| 6    | match                               | 10          |
| 7    | match                               | 7           |
| 8    | gym                                 | 776         |
| 9    | scan                                | 889         |
| 💥    | deliver                             | 6           |
| 11   | slack                               | 1           |
+------+-------------------------------------+-------------+

[16:11:19]: fastlane finished with errors

[!] No value found for 'edit_live'
Build step 'Conditional step (single)' marked build as failure
Recording test results
Finished: FAILURE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.2                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | ~/.rvm/rubies/ruby-2.2.2/bin/fastlane       |
| Host                | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.2/lib                |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.102.0"

default_platform :ios


platform :ios do

  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/xxxxx"

    cocoapods(repo_update: true)

  end

  # Responsible for building and signing the alpha app
  def build_alpha_app

    register_devices(devices_file: './fastlane/devices.txt')

    match(app_identifier: "nl.travelbird.TravelBird.alpha",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.alpha.Daily-Deals",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.alpha.watchkitapp",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.alpha.watchkitapp.watchkitextension",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    gym(
      workspace: "TravelBird.xcworkspace",
      configuration: "Alpha",
      scheme: "Distribution",
      silent: true,
      clean: true,
      output_directory: "build"
    )
  end

  # Responsible for building and signing the beta app
  def build_beta_app

    register_devices(devices_file: './fastlane/devices.txt')

    match(app_identifier: "nl.travelbird.TravelBird.beta",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.beta.Daily-Deals",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.beta.watchkitapp",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.beta.watchkitapp.watchkitextension",
          type: "adhoc",
          force_for_new_devices: true,
          readonly: true)

    gym(
      workspace: "TravelBird.xcworkspace",
      configuration: "Distribution",
      scheme: "Distribution",
      silent: true,
      clean: true,
      output_directory: "build"
    )
  end

  # Responsible for building and signing the release candidate app
  def build_release_app

    match(app_identifier: "nl.travelbird.TravelBird",
          type: "appstore",
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.Daily-Deals",
          type: "appstore",
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.watchkitapp",
          type: "appstore",
          readonly: true)

    match(app_identifier: "nl.travelbird.TravelBird.watchkitapp.watchkitextension",
          type: "appstore",
          readonly: true)

    gym(
      workspace: "TravelBird.xcworkspace",
      configuration: "Release",
      scheme: "Release",
      silent: true,
      clean: true,
      output_directory: "build"
    )
  end

  desc "Registers new devices in devices.txt for development provisioning profiles"
  lane :devices do

    match(app_identifier: "nl.travelbird.TravelBird.alpha",
          type: "development",
          force_for_new_devices: true)

    match(app_identifier: "nl.travelbird.TravelBird.alpha.Daily-Deals",
          type: "development",
          force_for_new_devices: true)

    match(app_identifier: "nl.travelbird.TravelBird.alpha.watchkitapp",
          type: "development",
          force_for_new_devices: true)

    match(app_identifier: "nl.travelbird.TravelBird.alpha.watchkitapp.watchkitextension",
          type: "development",
          force_for_new_devices: true)

  end

  lane :cert_dev do
    match(app_identifier: ["nl.travelbird.TravelBird.alpha", "nl.travelbird.TravelBird.alpha.Daily-Deals", "nl.travelbird.TravelBird.alpha.watchkitapp", "nl.travelbird.TravelBird.alpha.watchkitapp.watchkitextension"], type: "development", readonly: true)
  end  

  lane :cert_alpha do
    match(app_identifier: ["nl.travelbird.TravelBird.alpha", "nl.travelbird.TravelBird.alpha.Daily-Deals", "nl.travelbird.TravelBird.alpha.watchkitapp", "nl.travelbird.TravelBird.alpha.watchkitapp.watchkitextension"], type: "adhoc", readonly: true)
  end

  lane :cert_beta do
    match(app_identifier: ["nl.travelbird.TravelBird.beta", "nl.travelbird.TravelBird.beta.Daily-Deals", "nl.travelbird.TravelBird.beta.watchkitapp", "nl.travelbird.TravelBird.beta.watchkitapp.watchkitextension"], type: "adhoc", readonly: true)
  end

  lane :cert_release do
    match(app_identifier: ["nl.travelbird.TravelBird", "nl.travelbird.TravelBird.Daily-Deals", "nl.travelbird.TravelBird.watchkitapp", "nl.travelbird.TravelBird.watchkitapp.watchkitextension"], type: "appstore", readonly: true)
  end

  lane :get_cert_dev do
    match(app_identifier: ["nl.travelbird.TravelBird.alpha", "nl.travelbird.TravelBird.alpha.Daily-Deals", "nl.travelbird.TravelBird.alpha.watchkitapp", "nl.travelbird.TravelBird.alpha.watchkitapp.watchkitextension"], type: "development", readonly: true)
  end  

  lane :get_cert_alpha do
    match(app_identifier: ["nl.travelbird.TravelBird.alpha", "nl.travelbird.TravelBird.alpha.Daily-Deals", "nl.travelbird.TravelBird.alpha.watchkitapp", "nl.travelbird.TravelBird.alpha.watchkitapp.watchkitextension"], type: "adhoc", readonly: true)
  end

  lane :get_cert_beta do
    match(app_identifier: ["nl.travelbird.TravelBird.beta", "nl.travelbird.TravelBird.beta.Daily-Deals", "nl.travelbird.TravelBird.beta.watchkitapp", "nl.travelbird.TravelBird.beta.watchkitapp.watchkitextension"], type: "adhoc", readonly: true)
  end

  lane :get_cert_release do
    match(app_identifier: ["nl.travelbird.TravelBird", "nl.travelbird.TravelBird.Daily-Deals", "nl.travelbird.TravelBird.watchkitapp", "nl.travelbird.TravelBird.watchkitapp.watchkitextension"], type: "appstore", readonly: true)
  end

  desc "Run for dev builds. Does building and testing."
  lane :dev do

    scan(
      scheme: "Test",
      clean: true,
      device: "iPhone 6s"
    )

  end

  desc "Submit a new Alpha build to HockeyApp for developers."
  lane :alpha do

    # Download and build with latest provisioning
    build_alpha_app

    hockey(
      api_token: "xxxxxxx",
      ipa: './build/TravelBird.ipa',
      #notes_type: markdown_type,
      notes: "https://github.com/travelbird/for-your-iphone-only/commits/dev",
      notify: "0"
    )

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

  end

  desc "Submit a new Team build to HockeyApp for developers."
  lane :team do

    # Download and build with latest provisioning
    build_alpha_app

    hockey(
      api_token: "xxxxxxxxx",
      ipa: './build/TravelBird.ipa',
      notify: "0"
    )

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

  end

  desc "Submit a new Beta build to HockeyApp for testers."
  lane :beta do

    # Download and build with latest provisioning
    build_beta_app

    changelog = File.read("../docs/CHANGELOG.md")

    hockey(
      api_token: "xxxxxxxxx",
      ipa: './build/TravelBird.ipa',
      notes_type: "1",
      notes: changelog,
      notify: "0"
    )

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

  end

  desc "Deploy a release candidate to the App Store with TestFlight"
  lane :release do

    # Download and build with latest provisioning
    build_release_app

    scan(
      scheme: "Test",
      clean: true,
      skip_build: true,
      device: "iPhone 6s"
    )

    deliver(
      ipa: './build/TravelBird.ipa',
      force: true, # Set to true to skip PDF verification
      skip_screenshots: true,
      skip_metadata: true
    )

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    slack(
      message: "Successfully execute lane."
    )
  end


  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end

end


# More information about multiple platforms in fastlane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "nl.travelbird.TravelBird" # The bundle identifier of your app
apple_id "mobile-admin@travelbird.com" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "TravelBird Nederland BV"
# team_id "P36Y9AVLN7"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#the-appfile

for_lane :alpha do
  app_identifier "nl.travelbird.TravelBird.alpha"
end

for_lane :team do
  app_identifier "nl.travelbird.TravelBird.alpha"
end

for_lane :beta do
  app_identifier "nl.travelbird.TravelBird.beta"
end

for_lane :release do
  app_identifier "nl.travelbird.TravelBird"
end```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| executable-hooks          | 1.3.2       |
| bundler-unload            | 1.0.2       |
| rubygems-bundler          | 1.4.4       |
| bundler                   | 1.12.5      |
| slack-notifier            | 1.5.1       |
| rouge                     | 1.10.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.6.3       |
| plist                     | 3.1.0       |
| multipart-post            | 2.0.0       |
| word_wrap                 | 1.0.0       |
| babosa                    | 1.0.2       |
| colored                   | 1.2         |
| highline                  | 1.7.8       |
| commander                 | 4.4.0       |
| excon                     | 0.45.4      |
| faraday                   | 0.9.2       |
| unf_ext                   | 0.0.7.1     |
| unf                       | 0.1.4       |
| domain_name               | 0.5.25      |
| http-cookie               | 1.0.2       |
| faraday-cookie_jar        | 0.0.6       |
| gh_inspector              | 1.0.2       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| mime-types-data           | 3.2016.0221 |
| mime-types                | 3.0         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| multi_json                | 1.11.2      |
| logging                   | 2.0.0       |
| jwt                       | 1.5.2       |
| memoist                   | 0.14.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.2       |
| googleauth                | 0.5.1       |
| thor                      | 0.19.1      |
| httpclient                | 2.7.1       |
| google-api-client         | 0.9.3       |
| mini_magick               | 4.5.1       |
| multi_xml                 | 0.5.5       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| xcpretty-travis-formatter | 0.0.4       |
| dotenv                    | 2.1.1       |
| faraday_middleware        | 0.10.0      |
| json                      | 1.8.3       |
| claide                    | 1.0.1       |
| xcodeproj                 | 1.3.2       |
| terminal-table            | 1.5.2       |
</details>


*generated on:* **2016-12-27**
</details>

**Comment by Reedyuk** [comment]
Im also experiencing the same issue, nothing changed on the code signing part for the project.

**Comment by hjanuschka** [comment]
can some of you guys try this pr -> https://github.com/fastlane/fastlane/pull/7684 i hope that it fixes the issue.

**Comment by shabeepk** [comment]
@mpirri 

Do we know when this fix might be out?

I have a high priority deployment pending because of this issue...

**Comment by MarkMolina** [comment]
@shabeepk It's already out. Working now with version 2.3.1

**Comment by shabeepk** [comment]
@MarkMolina  I can't seem to update delivery to 2.3.1, has it been pushed to the gem repo ?

**Comment by shabeepk** [comment]
@MarkMolina I think I know what I was doing wrong, I was doing **deliver** instead of **fastlane deliver**. Trying now, I hope it works 👍

**Comment by shabeepk** [comment]
@MarkMolina Okay, it works. Apologies 😄 and sorry for the dumb questions 😦

**Comment by biolinh** [comment]
Hi all,

I got the same issue and It seems that there is a new feature . ["Modify live metadata, this option disables ipa upload and screenshot upload"](https://github.com/fastlane/fastlane/commit/58234e286a9ea92d77eb3dd76fa4ef02577eedf7#diff-cec46a69540d57cbb9c8631d43a7a89b)

Then, I set 
```
edit_live "false"
```
in DeliverFile.

```
app_identifier ENV["BUNDLE_IDENTIFIER"] 
username ENV["FASTLANE_USER"]
name ENV["APP_NAME"]
team_name ENV["TEAM_NAME"]
app_version ENV["BUNDLE_VERSION"]
team_id ENV["DELIVER_TEAM_ID"]
**edit_live "false"**
```

Lane upload_ipa
```
desc "Upload iPA to Apple Store"
  lane :upload_ipa do
    deliver(force: true)
  end
```

runing command: fastlane upload_ ipa
it runs without error.

but running deliver --force true, it returns error:
```
!] Could not find option 'edit_live' in the list of available options: username, app_identifier, app, ipa, pkg, platform, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, app_version, skip_metadata, force, submit_for_review, automatic_release, price_tier, build_number, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, overwrite_screenshots, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, app_review_information, description, name, keywords, release_notes, privacy_url, support_url, marketing_url
```

Besides, running under Jenkins, deliver file cannot upload ipa for me with error:
```
Unauthorized Access
``

Running directly in command line, it throw the error:
```
[!] Could not find a version to edit for app 'Bolderland', the app metadata is read-only currently
```

**Comment by KrauseFx** [comment]
@biolinh Please share your `fastlane env` output 👍

**Comment by biolinh** [comment]
[<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

desc "Upload iPA to Apple Store"
  lane :upload_ipa do
    deliver(force: true)
  end

  desc "Deploy a new version to the App Store"
  lane :upload_appstore do
    sh "fastlane-credentials add --username FASTLANE_USER --password KEYCHAIN_PASSWORD"
    publishing = ENV["PUBLISHING"]
    puts publishing
    if publishing == '1'
      createnewapp
    end 
    set_google_info_plist_value
    appleprovision
    sh "pod cache clean 360-Data --all"
    sh "pod cache clean 360-Domain --all"
    sh "pod update" 
    increment_build_number(build_number: BUILD_NUMBER) 
    sh "mv '#{ENV["PROJECT_DIR"]}'/*.mobileprovision brandedapp.mobileprovision"
    parsed = FastlaneCore::ProvisioningProfile.parse("brandedapp.mobileprovision")
    ProfileSpecifier = parsed["Name"]
    sh "echo PROVISIONING_PROFILE_SPECIFIER=#{ProfileSpecifier} >> .env"
    puts ProfileSpecifier;
    unlock_keychain(path: "login.keychain", password: KEYCHAIN_PASSWORD)
    xcclean(scheme: "360" )
    sh "sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/' '#{ENV["PROJECT_DIR"]}'/360.xcodeproj/project.pbxproj"
    gym(scheme: "360",codesigning_identity: CODE_SIGN_IDENTITY,xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{ProfileSpecifier}'")
    upload_ipa
    sh "fastlane-credentials remove --username FASTLANE_USER"
  end
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["BUNDLE_IDENTIFIER"] 
apple_id ENV["FASTLANE_USER"]
team_name ENV["TEAM_NAME"]
team_id ENV["TEAM_ID"]

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.6.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-01-09**
</details>]

**Comment by hjanuschka** [comment]
@biolinh how'd you run deliver?
it is supposed to be run with `fastlane deliver ....`  since the migration to a `monogem` 👍 
you probably still have a olde deliver installed, which does not have the `edit_live`  feature.

let me know if this helps?

**Comment by biolinh** [comment]
@hjanuschka: checking version of deliver, it returns that: 
```
deliver -version
deliver 2.6.0

```

**Comment by hjanuschka** [comment]
@biolinh hmmm - strange, looks good, can you check if jenkins has authentication problems ? e.g. do some other iTC stuff known-to-work? like calling `produce`  to create a dummy app?

**Comment by biolinh** [comment]
@hjanuschka: No, my Jenkins job do not do any unrelated work. 
It runs as normal for a long time without any problem.

**Comment by sungjin0213** [comment]
I added "fastlane" prefix before "deliver", and this problem was resolved for me too.
