### ISSUE TITLE
Running the scan template crashes Fastlane

### ISSUE THREAD

**Issue by BalestraPatrick** [fastlane/fastlane#7682]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I ran `fastlane init` to set up fastlane automatically. I then proceeded to run `fastlane test` to run my unit tests but I encountered a crash at this line: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/project.rb#L244
My project is open source, feel free to take a look at my setup here: https://github.com/BalestraPatrick/Tweetometer/tree/master/fastlane 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `test`
<details><summary>Output/Log</summary>

```

[21:12:25]: -------------------------------------------------
[21:12:25]: --- Step: Verifying required fastlane version ---
[21:12:25]: -------------------------------------------------
[21:12:25]: Your fastlane version 2.3.0 matches the minimum requirement of 2.3.0  ✅
[21:12:25]: ------------------------------
[21:12:25]: --- Step: default_platform ---
[21:12:25]: ------------------------------
[21:12:25]: Driving the lane 'ios test' 🚀
[21:12:25]: -----------------------
[21:12:25]: --- Step: cocoapods ---
[21:12:25]: -----------------------
[21:12:26]: $ pod install
[21:12:27]: ▸ Analyzing dependencies
[21:12:27]: ▸ Fetching podspec for `Keys` from `Pods/CocoaPodsKeys`
[21:12:28]: ▸ Downloading dependencies
[21:12:28]: ▸ Using ActiveLabel (0.7.0)
[21:12:28]: ▸ Using Alamofire (4.2.0)
[21:12:28]: ▸ Using AlamofireImage (3.2.0)
[21:12:28]: ▸ Using Crashlytics (3.8.3)
[21:12:28]: ▸ Using Fabric (1.6.11)
[21:12:28]: ▸ Using Keys (1.0.0)
[21:12:28]: ▸ Using Presentr (1.0.3)
[21:12:28]: ▸ Using PullToRefresher (2.0.2)
[21:12:28]: ▸ Using Realm (2.1.1)
[21:12:28]: ▸ Using RealmSwift (2.1.1)
[21:12:28]: ▸ Using SwiftyUserDefaults (3.0.0)
[21:12:28]: ▸ Using TwitterCore (2.6.1)
[21:12:28]: ▸ Using TwitterKit (2.6.1)
[21:12:28]: ▸ Using Unbox (2.3.0)
[21:12:28]: ▸ Using ValueStepper (1.0)
[21:12:28]: ▸ Using Whisper (4.0.0)
[21:12:28]: ▸ Generating Pods project
[21:12:29]: ▸ Integrating client project
[21:12:30]: ▸ Sending stats
[21:12:30]: ▸ Pod installation complete! There are 15 dependencies from the Podfile and 16 total pods installed.
[21:12:30]: ▸ [!] The `TweetsCounter [Debug]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-TweetsCounter/Pods-TweetsCounter.debug.xcconfig'. This can lead to problems with the CocoaPods installation
[21:12:30]: ▸ [!] The `TweetsCounter [Release]` target overrides the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` build setting defined in `Pods/Target Support Files/Pods-TweetsCounter/Pods-TweetsCounter.release.xcconfig'. This can lead to problems with the CocoaPods installation
[21:12:30]: ▸ - Use the `$(inherited)` flag, or
[21:12:30]: ▸ - Remove the build settings from the target.
[21:12:30]: ▸ - Use the `$(inherited)` flag, or
[21:12:30]: ▸ - Remove the build settings from the target.
[21:12:30]: ------------------
[21:12:30]: --- Step: scan ---
[21:12:30]: ------------------
[21:12:30]: $ xcodebuild -list -workspace ./TweetsCounter.xcworkspace
[21:12:31]: $ xcodebuild clean -showBuildSettings -workspace ./TweetsCounter.xcworkspace -scheme TweetometerTests
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios test |
+------------------+----------+
[21:12:32]: undefined method `split' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 4           |
| 💥    | scan                                | 2           |
+------+-------------------------------------+-------------+

[21:12:32]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Fastlane Deliver failed.  Couldn't find 'split' in nil:NilClass or xcodebuild
   https://github.com/fastlane/fastlane/issues/7651 [open] 5 💬
   3 days ago

➡️  `supported_platforms': [!] undefined method `split' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/7141 [closed] 43 💬
   3 weeks ago

➡️  pilot upload failure undefined method `builds' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/6267 [closed] 9 💬
   04 Oct 2016

and 14 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60split'%20for%20nil&type=Issues&utf8=✓


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.2.3/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.3/lib                |
| OpenSSL Version     | OpenSSL 1.0.2f  28 Jan 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.3.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "TweetometerTests")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Tweetometer") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Tweetometer") # Build your app - more options available
    deliver(force: true)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.patrickbalestra.tweetometer" # The bundle identifier of your app
apple_id "me@patrickbalestra.com" # Your Apple email address

team_id "2EZDW5DVTJ"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| executable-hooks          | 1.3.2       |
| bundler-unload            | 1.0.2       |
| rubygems-bundler          | 1.4.4       |
| bundler                   | 1.13.7      |
| slack-notifier            | 1.5.1       |
| rouge                     | 1.10.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.7.1       |
| terminal-table            | 1.4.5       |
| addressable               | 2.3.8       |
| multipart-post            | 2.0.0       |
| word_wrap                 | 1.0.0       |
| babosa                    | 1.0.2       |
| colored                   | 1.2         |
| highline                  | 1.7.8       |
| commander                 | 4.4.2       |
| excon                     | 0.45.4      |
| faraday                   | 0.9.2       |
| http-cookie               | 1.0.2       |
| faraday-cookie_jar        | 0.0.6       |
| gh_inspector              | 1.0.2       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| multi_json                | 1.11.2      |
| logging                   | 2.1.0       |
| jwt                       | 1.5.6       |
| memoist                   | 0.15.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.3       |
| googleauth                | 0.5.1       |
| httpclient                | 2.8.3       |
| google-api-client         | 0.9.20      |
| mini_magick               | 4.5.1       |
| multi_xml                 | 0.5.5       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| xcpretty-travis-formatter | 0.0.4       |
| dotenv                    | 2.1.1       |
| faraday_middleware        | 0.10.0      |
| json                      | 1.8.3       |
| plist                     | 3.2.0       |
| CFPropertyList            | 2.3.3       |
| claide                    | 1.0.1       |
| nanaimo                   | 0.1.4       |
| xcodeproj                 | 1.4.0       |
</details>

*generated on:* **2016-12-27**
</details>

**Comment by KrauseFx** [comment]
Could you share the full stack trace by running _fastlane_ using `--verbose`? Also, did you find a way to update to `Fasfile` to make it work?

**Comment by BalestraPatrick** [comment]
This is the stack trace:
```
/Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane_core/lib/fastlane_core/project.rb:244:in `supported_platforms': [!] undefined method `split' for nil:NilClass (NoMethodError)
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane_core/lib/fastlane_core/project.rb:240:in `ios?'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/scan/lib/scan/detect_values.rb:28:in `set_additional_default_values'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/scan/lib/scan.rb:26:in `config='
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/actions/scan.rb:15:in `run'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:232:in `block (2 levels) in execute_action'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:25:in `block (2 levels) in parsing_binding'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/commands_generator.rb:96:in `block (2 levels) in run'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/commander-4.4.2/lib/commander/command.rb:153:in `run'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/commander-4.4.2/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/commander-4.4.2/lib/commander/delegates.rb:15:in `run!'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/gems/fastlane-2.3.1/bin/fastlane:5:in `<top (required)>'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `load'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/bin/fastlane:23:in `<main>'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/patrickbalestra/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by 0xced** [comment]
It looks like a rebirth of #7141. cc @hjanuschka

**Comment by 0xced** [comment]
@BalestraPatrick Changing `scan(scheme: "TweetometerTests")` to `scan(scheme: "Tweetometer")` in your Fastfile should solve your issue.

@hjanuschka We should definitely produce a better error message when build settings are not available suggesting that there‘s an issue with the chosen scheme.

**Comment by 0xced** [comment]
Pull request for better error message coming tomorrow.

**Comment by BalestraPatrick** [comment]
@0xced Yes, changing the scheme name fixed the issue! A better error message would be really useful in this case. Thanks a lot for the help 👍

**Comment by KrauseFx** [comment]
Awesome, thanks everybody. Definitely something that needs to be fixed to be a clear and useful error message 👍 

Let me know if I can help

**Comment by 0xced** [comment]
And of course, writing that *better error message* dragged me into a rabbit hole and I’m now disassembling Xcode to understand why the `xcodebuild clean -showBuildSettings -workspace ./TweetsCounter.xcworkspace -scheme TweetometerTests` command does not produce any output. 😖

**Comment by dral3x** [comment]
Today I found this same issue.

In my case, my "testing" scheme is intentionally without any executable/target set in Run (because I don't want to run it) and only for Test.

Inside Xcode, this scheme setup works.

Side note: if I run "fastlane scan --scheme UnitTests", I see this crash reported on the console, while if I have a lane and run it like "fastlane unit_test", nothing is displayed and I need to kill ruby process to unlock the situation.

Thanks everybody for the workaround anyway! 👍
