### ISSUE TITLE
Timeout: kits-crashlytics-com.s3.amazonaws.com

### ISSUE THREAD

**Issue by giurobrossi** [fastlane/fastlane#7685]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

/Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Operation timed out - connect(2) for "kits-crashlytics-com.s3.amazonaws.com" port 443 (Errno::ETIMEDOUT)
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:583:in `start'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:478:in `get_response'
	from /Users/aepadmin/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:455:in `get'

All the fastlane commands are correctly executed BUT they get this timeout at the beginning of the execution. My server is behind a proxy and the environment variables http_proxy and https_proxy are correctly initialized in the .bash_profile.

Is there the possibility to SKIP this connection to "kits-crashlytics-com.s3.amazonaws.com" since it's not blocking the correct execution of a fasten command ?

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.10.5                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.5.4 (Apple Git-61)            |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.10.5 (14F1909)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status  |
| ------------------- | ------- | -------------- |
| cert                | 2.0.0   | 💥 Check failed |
| credentials_manager | 1.0.0   | 💥 Check failed |
| credentials_manager | 0.16.2  | 💥 Check failed |
| deliver             | 2.0.1   | 💥 Check failed |
| fastlane            | 2.1.1   | 💥 Check failed |
| fastlane_core       | 1.0.0   | 💥 Check failed |
| fastlane_core       | 0.60.0  | 💥 Check failed |
| frameit             | 4.0.0   | 💥 Check failed |
| gym                 | 2.0.0   | 💥 Check failed |
| match               | 1.0.0   | 💥 Check failed |
| pem                 | 2.0.0   | 💥 Check failed |
| pilot               | 1.13.1  | 💥 Check failed |
| produce             | 2.0.0   | 💥 Check failed |
| scan                | 1.0.0   | 💥 Check failed |
| screengrab          | 1.0.0   | 💥 Check failed |
| sigh                | 2.0.1   | 💥 Check failed |
| snapshot            | 2.0.0   | 💥 Check failed |
| spaceship           | 1.0.0   | 💥 Check failed |
| spaceship           | 0.39.0  | 💥 Check failed |
| supply              | 1.0.0   | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.1        |
| concurrent-ruby           | 1.0.2        |
| credentials_manager       | 1.0.0        |
| credentials_manager       | 0.16.2       |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 1.0.0        |
| fastlane_core             | 0.60.0       |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.1        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2016-12-28**
</details>

**Comment by freps** [comment]
+1 same problem here

**Comment by hjanuschka** [comment]
@freps could you be so kind and run fastlane with `--verbose` to get a full stacktrace, i want to fix this 👍 

but the initial reporters stacktrace is to less.

**Comment by freps** [comment]
@hjanuschka, yes, I can, but unfortunately the result is not more detailed than above:

```
user-macmini:~ myuser$ fastlane --verbose
/Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `initialize': Operation timed out - connect(2) for "kits-crashlytics-com.s3.amazonaws.com" port 443 (Errno::ETIMEDOUT)
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `open'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/timeout.rb:73:in `timeout'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:852:in `start'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:583:in `start'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:478:in `get_response'
	from /Users/myuser/.fastlane/bin/bundle/lib/ruby/2.2.0/net/http.rb:455:in `get'
	from /Users/myuser/.fastlane/bin/bundle_update_checker.rb:5:in `<main>'
DEBUG [2017-01-18 13:40:42.57]: Checking if there are any plugins that should be loaded...
...
```

I guess the implementation for `http_proxy` for this request is missing.

**Comment by hjanuschka** [comment]
@freps  you are right, i did a PR on the packaged-fastlane repo -> https://github.com/fastlane/packaged-fastlane/pull/76

which should add support for http_proxy and also add a timeout handler, and report when a timeout happens but should not crash.

**Comment by schiller256** [comment]
In which fastlane Version will this fix released?

**Comment by hjanuschka** [comment]
new version has been release once homebrew merges this PR https://github.com/caskroom/homebrew-cask/pull/29655
