### ISSUE TITLE
How to fill copyright section

### ISSUE THREAD

**Issue by pbeast** [fastlane/fastlane#7690]
Hi,

Can you please help with the copyright section of iTC data. I use `copyright.txt` to set company name, but what fields should I use to provide contact information, i.e. name, phone number, email, address and etc.
![untitled](https://cloud.githubusercontent.com/assets/454344/21524122/6df3e884-cd1c-11e6-8c5c-add8a15689a8.png)

Thank you in advance

**Comment by KrauseFx** [comment]
This should help 👍  https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md

**Comment by pbeast** [comment]
Sorry, @KrauseFx, but provided documentation doesn't contain info for mentioned fields, or I'm missing something. Can you please check; that the last thing stops 👍

**Comment by KrauseFx** [comment]
It does as far as I understand: https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md#app_review_information

```ruby
app_review_information(
  first_name: "Felix",
  last_name: "Krause",
  phone_number: "+43 123123123",
  email_address: "github@krausefx.com",
  demo_user: "demoUser",
  demo_password: "demoPass",
  notes: "such notes, very text"
)
```

**Comment by pbeast** [comment]
Oh no😄 app review section is working perfectly. I'm asking about copyright section, that's why I mentioned copyright.txt file. 

Regards,
Pavel Yankelevich

**Comment by KrauseFx** [comment]
Ah, interesting, sorry I didn't know that's different. Then I guess that's not possible right now. Is this mandatory?

**Comment by pbeast** [comment]
> Is this mandatory?

I'm checking and let you know.

**Comment by hjanuschka** [comment]
@pbeast has this been resolved?

**Comment by pbeast** [comment]
Hi @hjanuschka,
I found that those fields can't be filled by fastlane, but, same time, they are optional, so I guess we can close the issue.

Thanks a lot,
Pavel
