### ISSUE TITLE
scan is slow on Jenkins

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7694]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `scan` on a Jenkins takes longer than running it locally on the same machine. The extra time is taken before and after generating the output report. Keeps on spinning for a while.

`Successfully generated report at '/Users/jenkins/.jenkins/workspacexxxx/fastlane/test_output/report.html'`

<img width="800" alt="screenshot 2016-12-28 13 30 20" src="https://cloud.githubusercontent.com/assets/2100166/21529813/df93842e-cd01-11e6-90f8-75ac6e0e4506.png">

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rvm/gems/ruby-2.2.1/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.2.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

platform :ios do

  before_all do
    # if is_ci?
    #   puts "Running on CI"
    #   setup_jenkins
    # else
    #   puts "Running on local machine"
    # end
  end

  desc "Run test cases for the My project"
  lane :my_scan do
    scan(scheme: ‘MyScheme’, skip_build: true, device: 'iPhone 7 Plus')
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams

# To select a team for iTunes Connect use

# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.13.6  |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| terminal-table            | 1.7.3   |
| plist                     | 3.2.0   |
| public_suffix             | 2.0.4   |
| addressable               | 2.5.0   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| excon                     | 0.54.0  |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 2.0.1   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.12.1  |
| logging                   | 2.1.0   |
| jwt                       | 1.5.6   |
| memoist                   | 0.15.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| httpclient                | 2.8.3   |
| google-api-client         | 0.9.20  |
| highline                  | 1.7.8   |
| json                      | 2.0.2   |
| mini_magick               | 4.5.1   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| commander                 | 4.4.2   |
| rubyzip                   | 1.2.0   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| unicode-display_width     | 1.1.2   |
</details>

*generated on:* **2016-12-28**
</details>

**Comment by RishabhTayal** [comment]
Any help on this? cc: @hjanuschka?

**Comment by hjanuschka** [comment]
@RishabhTayal i am not a jenkins pro - not sure if i can help here, any chances to get the full output (not only a screenshot?)

**Comment by RishabhTayal** [comment]
I am not able to get the full output. what's the best way to debug this?

**Comment by lyndsey-ferguson** [comment]
@RishabhTayal the Console for the Jenkins build should display everything that it is doing. It will display different log files that are being written to. Are you able to `ssh` into the Jenkins slave? If so, I would log in an look at the logs. We had slow issues where our Ruby Gems were causing problems with the codesigning and that information was in a `IDEDistribution.standard.log`. That may not be your problem though...

Review the logs. If you spend a day looking and you still do not know where to look next, include the Jenkins build console output here and I can take a look.
