### ISSUE TITLE
ensure_xcode_version failed

### ISSUE THREAD

**Issue by puttin** [fastlane/fastlane#7697]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

bundle install with `gem "fastlane", "~> 2.3"` won't install xcode-install/xcversion

**Comment by KrauseFx** [comment]
Can you add the following to your `Gemfile`

```ruby
gem "xcode-install"
```

and let me know if that works for you 👍

**Comment by puttin** [comment]
Yes, that should fix the problem.
And indeed it fix.
