### ISSUE TITLE
add different "app_identifier" automaticly

### ISSUE THREAD

**Issue by Mactub07** [fastlane/fastlane#7699]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
how I can import  different "app_identifier" from file (*.JS, *.JSON)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
Check out the [fastlane examples](https://github.com/fastlane/examples). Basically you can use environment variables or CLI parameters to pass a dynamic app identifier 👍

**Comment by Mactub07** [comment]
some logic can be implemented like this ...

paste code inside Fastfile:

 #  <-- custom script, you can add some logic here; -->
  before_all do

    # import config;
        CONFIG              = JSON.parse(open("../src/config/config.json").read) #import values from your 
        APPNAME             = CONFIG["app_name_ios"]
        APPIDENTIFIER       = CONFIG["apple_identifier"]
        APPVERSION          = CONFIG["appVersion_ios"]
        DESCRIPTION         = CONFIG["app_description_ios"]

    # set project location;
        ENV["GYM_PROJECT"] = "ios/" + APPNAME + ".xcodeproj"

    # set app identifier;
        ENV["APP_IDENTIFIER"] = APPIDENTIFIER
    
  end

**Comment by hjanuschka** [comment]
@Mactub07  looks like your issue is resolved, feel free to reopen or create a new issue if you have any further questions
