### ISSUE TITLE
Unable to resolve dependencies: fastlane and gym require different versions of xcpretty

### ISSUE THREAD

**Issue by superarts** [fastlane/fastlane#770]
$ `sudo gem install fastlane`
`Unable to resolve dependencies: fastlane requires xcpretty (>= 0.1.11); gym requires xcpretty (~> 0.1)`

I tried to uninstall fastlane and gym, but it didn't work.

**Comment by KrauseFx** [comment]
Could you try run `gem cleanup && gem uninstall xcpretty` and try installing `fastlane` again

**Comment by xfreebird** [comment]
@KrauseFx I tried my self with the system ruby, while it works in my rbenv.

```bash
sudo gem cleanup && sudo gem uninstall xcpretty
sudo gem install fastlane
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires xcpretty (>= 0.1.11); scan requires xcpretty (~> 0.1.12); xcpretty-travis-formatter requires xcpretty (>= 0.0.7, ~> 0.2); gym requires xcpretty (~> 0.1); snapshot requires xcpretty (>= 0)
```

**Comment by kohtenko** [comment]
Same here. `gem cleanup && gem uninstall xcpretty` doesn't help.

**Comment by KrauseFx** [comment]
I just pushed new versions for all gems, could you try updating? :+1:

**Comment by superarts** [comment]
Thanks man, it works on my home mac. I'll test on my work mac on Monday. Cheers & have a good weekend!

**Comment by superarts** [comment]
It works on my work mac as well, thanks!
