### ISSUE TITLE
Deliver is failing with "Forbidden"

### ISSUE THREAD

**Issue by erikjthomas** [fastlane/fastlane#7703]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

As of today, deliver always fails with this error:

```
[!] The request could not be completed because:
	Forbidden
```

No other error information is output. No changes have been made to my environment, scripts, or apps to explain this issue. Has Apple changed an API again?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

I'm running deliver as part of a Fastfile, not using command line.

```
[13:41:02]: ---------------------
[13:41:02]: --- Step: deliver ---
[13:41:02]: ---------------------
[13:41:02]: Login to iTunes Connect (fastlane@linqto.com)
[13:41:06]: Login successful

+-----------------------+--------------------------------------------------------------------------+
|                                      deliver 2.3.1 Summary                                       |
+-----------------------+--------------------------------------------------------------------------+
| username              | fastlane@linqto.com                                                      |
| team_id               | 6SNM9P3C6Y                                                               |
| ipa                   | /Users/ethomas/Documents/wib-launch/moneycarta/marinadvisor/marinadvi... |
| metadata_path         | /Users/ethomas/Documents/wib-launch/moneycarta/marinadvisor/metadata     |
| skip_screenshots      | true                                                                     |
| force                 | true                                                                     |
| app_identifier        | com.linqto.moneycarta.marinadvisor                                       |
| screenshots_path      | ./screenshots                                                            |
| app_version           | 1.0.3                                                                    |
| platform              | ios                                                                      |
| skip_binary_upload    | false                                                                    |
| skip_metadata         | false                                                                    |
| submit_for_review     | false                                                                    |
| automatic_release     | false                                                                    |
| overwrite_screenshots | false                                                                    |
+-----------------------+--------------------------------------------------------------------------+

[13:41:08]: Making sure the latest version on iTunes Connect matches '1.0.3' from the ipa file...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Distributing new build: The request could not be completed because:Forbidden
   https://github.com/fastlane/fastlane/issues/6023 [closed] 2 💬
   3 weeks ago

➡️  Distributing new build to testers: The request could not be completed because: 	Forbidden
   https://github.com/fastlane/fastlane/issues/4793 [closed] 10 💬
   3 weeks ago

➡️  Deliver fails with `Forbidden` error
   https://github.com/fastlane/fastlane/issues/4899 [closed] 5 💬
   3 weeks ago

and 1 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Forbidden&type=Issues&utf8=✓

[!] The request could not be completed because:
	Forbidden
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.gem/ruby/2.3.1/bin/fastlane              |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rubies/ruby-2.3.1/lib                    |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| excon                     | 0.54.0  |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| gh_inspector              | 1.0.2   |
| highline                  | 1.7.8   |
| json                      | 2.0.2   |
| mini_magick               | 4.5.1   |
| multi_json                | 1.12.1  |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| bundler                   | 1.13.6  |
| commander                 | 4.4.3   |
| io-console                | 0.4.5   |
| rubyzip                   | 1.2.0   |
| plist                     | 3.2.0   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| unicode-display_width     | 1.1.2   |
| terminal-table            | 1.7.3   |
</details>

*generated on:* **2016-12-29**
</details>

**Comment by KrauseFx** [comment]
This is a temporary server issue, does it work when you try it again?

**Comment by erikjthomas** [comment]
It does appear to be an iTC issue since I can reproduce it with both fastlane 1.1 and 2.3.1.

Alas, the problem still exists this morning.

**Comment by KrauseFx** [comment]
Interesting, do you know a good way for us to reproduce the issue?

**Comment by erikjthomas** [comment]
Josh Holtz is setting up to try reproducing this issue on his machine--he has access to all our scripts. If we can't figure this out, we'll provide some means to test it. Since nobody else is running into this, there could be something like Apple deciding it doesn't like our credentials anymore or maybe something they changed related to account access or roles. I'll update this issue with what we find. Thanks.

**Comment by KrauseFx** [comment]
What role does the account have?

**Comment by erikjthomas** [comment]
OK, figured it out. Deliver fails if the account role is Developer. Changing to App Manager didn't help, but changing to Admin fixed it. Developer role worked for previous 82 apps. Apple obviously changed the required permissions for some part of the deliver action in the past two weeks.

**Comment by KrauseFx** [comment]
Argh, that's not good, and also something we should show a more appropriate error message for. Sorry you ran into this.

**Comment by erikjthomas** [comment]
Oh well. We're back in business. Thanks!

**Comment by erikjthomas** [comment]
Oops, guess I don't understand how the labelling works and such. Reopening.

**Comment by pixelrevision** [comment]
Confirming that giving the user admin permissions worked for this.

**Comment by erikjthomas** [comment]
Yes, giving the user admin permissions worked for this.

**Comment by kensykora** [comment]
Are there any workarounds outside of giving the user admin?

**Comment by hjanuschka** [comment]
@kensykora i think it should be one of the following roles "Admin", "Developer", "App-Manager"

**Comment by pixelrevision** [comment]
@hjanuschka some of us were not able to get this working with "Developer".  For me changing to "Admin" was the only thing that fixed the error.

**Comment by netbe** [comment]
So same here, does not work with `App-Manager`. I cannot confirm it does work with `Admin`, but interesting that `App-Manager` is enough for testflight builds

**Comment by KrauseFx** [comment]
So if you update to the latest fastlane release, we'll now show a more appropriate error message when _fastlane_ fails, can you try again? Is the action you're trying something the user should have permission for?

**Comment by KrauseFx** [comment]
I'll close this for now, as it should be resolved
