### ISSUE TITLE
Snapshot implicitly runs NON-UI unit tests. These are unnecessary and unwanted.

### ISSUE THREAD

**Issue by fulldecent** [fastlane/fastlane#7704]
# 🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `fastlane snapshot` also implicitly runs NON-UI unit tests. These are unnecessary and unwanted.

##### Complete output when running fastlane, including the stack trace and command used

````
fastlane snapshot
/Users/fulldecent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/snapshot-2.0.0/lib/snapshot/version.rb:3: warning: already initialized constant Snapshot::DESCRIPTION
/Users/fulldecent/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.3.0/snapshot/lib/snapshot.rb:48: warning: previous definition of DESCRIPTION was here
[18:42:03]: Successfully loaded '/Users/fulldecent/Developer/formant-analyzer/Formant Analyzer/fastlane/Snapfile' 📄

+----------------------+--------------------------+
|   Detected Values from './fastlane/Snapfile'    |
+----------------------+--------------------------+
| devices              | ["iPhone 7", "iPad Pro"] |
| languages            | ["en-US"]                |
| scheme               | Formant Analyzer         |
+----------------------+--------------------------+

+----------------------------+---------------------------------------------------------------------+
|                                    Summary for snapshot 2.3.0                                    |
+----------------------------+---------------------------------------------------------------------+
| devices                    | ["iPhone 7", "iPad Pro"]                                            |
| languages                  | ["en-US"]                                                           |
| scheme                     | Formant Analyzer                                                    |
| workspace                  | ./Formant Analyzer.xcworkspace                                      |
| output_directory           | /Users/fulldecent/Developer/formant-analyzer/Formant Analyzer/fa... |
| launch_arguments           | [""]                                                                |
| skip_open_summary          | false                                                               |
| clear_previous_screenshots | false                                                               |
| reinstall_app              | false                                                               |
| erase_simulator            | false                                                               |
| localize_simulator         | false                                                               |
| app_identifier             | net.phor.FormantPlotter                                             |
| buildlog_path              | ~/Library/Logs/snapshot                                             |
| clean                      | false                                                               |
| number_of_retries          | 1                                                                   |
| stop_after_first_error     | false                                                               |
| xcode_path                 | /Applications/Xcode.app                                             |
+----------------------------+---------------------------------------------------------------------+
[18:42:06]: Building and running project - this might take some time...
[18:42:06]: snapshot run 1 of 2
[18:42:06]: Patching '/Users/fulldecent/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%
[18:42:11]: $ xcodebuild clean -showBuildSettings -workspace ./Formant\ Analyzer.xcworkspace -scheme Formant\ Analyzer
[18:42:12]: ------------------------
[18:42:12]: --- iPhone 7 - en-US ---
[18:42:12]: ------------------------
[18:42:12]: $ set -o pipefail && xcodebuild -workspace ./Formant\ Analyzer.xcworkspace -scheme Formant\ Analyzer -derivedDataPath '/var/folders/9z/ycyddbld1zgcx86xbqz2ywxm0000gp/T/snapshot_derived20161229-56601-h167pc' -destination 'platform=iOS Simulator,id=BEE57457-04BA-4B39-A861-65665B800EFA,OS=10.2' FASTLANE_SNAPSHOT=YES build test | tee /Users/fulldecent/Library/Logs/snapshot/Formant\ Analyzer-Formant\ Analyzer.log | xcpretty 
[18:42:12]: ▸ Loading...
[18:42:14]: ▸ Building Pods/FSLineChart [Debug]
[18:42:14]: ▸ Check Dependencies
[18:42:14]: ▸ Processing Info.plist
[18:42:24]: ▸ Compiling FSLineChart-dummy.m
[18:42:28]: ▸ Compiling FSLineChart.m
[18:42:28]: ▸ ⚠️  /Users/fulldecent/Developer/formant-analyzer/Formant Analyzer/Pods/FSLineChart/FSLineChart/FSLineChart/FSLineChart.m:63:1: method possibly missing a [super awakeFromNib] call [-Wobjc-missing-super-calls]
[18:42:28]: ▸ }
[18:42:28]: ▸ ^
[18:42:28]: ▸ Compiling FSLineChart_vers.c
[18:42:28]: ▸ Compiling UIColor+FSPalette.m
[18:42:28]: ▸ Linking FSLineChart
[18:42:28]: ▸ Copying FSLineChart-umbrella.h
[18:42:28]: ▸ Copying FSLineChart.h
[18:42:28]: ▸ Copying UIColor+FSPalette.h
[18:42:28]: Running Tests: ▸ Touching FSLineChart.framework
[18:42:28]: ▸ Signing /var/folders/9z/ycyddbld1zgcx86xbqz2ywxm0000gp/T/snapshot_derived20161229-56601-h167pc/Build/Products/Debug-iphonesimulator/FSLineChart/FSLineChart.framework
[18:42:28]: ▸ Building Pods/FDSoundActivatedRecorder [Debug]
[18:42:28]: ▸ Check Dependencies
[18:42:28]: ▸ Processing Info.plist
[18:42:28]: ▸ Compiling FDSoundActivatedRecorder.swift
[18:42:28]: ▸ Compiling FDSoundActivatedRecorder-dummy.m
[18:42:28]: ▸ Compiling FDSoundActivatedRecorder_vers.c
[18:42:28]: ▸ Linking FDSoundActivatedRecorder
````

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.84.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Formant Analyzer") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Formant Analyzer") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "net.phor.FormantPlotter" # The bundle identifier of your app
apple_id "william.entriken@drexel.edu" # Your Apple email address

team_id "8Q693ZG5RN"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.3.0   | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2016-12-29**
</details>

**Comment by GBoyadziev** [comment]
I extended my project with unit tests and I am observing the same problem. Even worse, sometimes snapshot fails to take screenshots, because some unit test fails. Is there any way of running only UI Tests with snapshot?

**Comment by KaneCheshire** [comment]
I've worked around this by creating a new scheme especially for snapshots, and made sure that the only tests that are included in that scheme are the UI tests. Then simply declare that scheme as the one to use in the snapfile.

**Comment by KrauseFx** [comment]
Creating a scheme is the best and easiest way for now to do that 👍

**Comment by fulldecent** [comment]
I had this project open for a while now. If I completely remove fastlane and then re-set it up will it set up a new scheme for me to do this?

**Comment by fulldecent** [comment]
Understood, thank you
