### ISSUE TITLE
Gradle action can't find apk path.

### ISSUE THREAD

**Issue by marcferna** [fastlane/fastlane#7705]
### Issue Description
Gradle action does not find new apks.
```
apk_search_path = File.join(project_dir, '*', 'build', 'outputs', 'apk', '*.apk')
``` 
is not finding the apks when is the exact path. Ex:
`<project_dir>/build/outputs/apk/release.apk`

Should it be? 
```
apk_search_path = File.join(project_dir, '**', 'build', 'outputs', 'apk', '*.apk')
```
https://github.com/marcferna/fastlane/commit/51b3472d4f9580c5663ce9a1eb55171a1e25735f

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                    |
| ------------------- | -------------------------------------------------------- |
| OS                  | 10.11.6                                                  |
| Ruby                | 2.3.0                                                    |
| Bundler?            | true                                                     |
| Git                 | git version 2.10.0                                       |
| Installation Source | ~/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G1108)                               |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.0/lib                              |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                                |
| Is contained        | false                                                    |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version       | 8.2.1                                                    |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| minitest                  | 4.7.5        |
| multi_json                | 1.12.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 0.3.52       |
| activesupport             | 4.0.13       |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| coderay                   | 1.1.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| method_source             | 0.8.2        |
| slop                      | 3.6.0        |
| pry                       | 0.10.3       |
</details>

*generated on:* **2016-12-29**
</details>

**Comment by asfalcone** [comment]
@marcferna could you submit a PR for this change?

**Comment by marcferna** [comment]
Hey @asfalcone! Thanks for your response - here you go: https://github.com/fastlane/fastlane/pull/7786
