### ISSUE TITLE
Use lane command instead of fastlane to run lanes

### ISSUE THREAD

**Issue by alexmx** [fastlane/fastlane#771]
It's just a suggestion for enhancement.
Use **lane** instead/together with **fastlane** command to run lanes.

Like **pod** instead of **cocoapods**. Or **brew** instead of **homebrew**.

Sometimes I ended up to write accidentally **lane** in my terminal instead of **fastlane**.

Thanks. :smile:

**Comment by KrauseFx** [comment]
Thanks for the feedback, but this will probably get confusing for users, as there are multiple ways of doing something. 

`cocoapods` only works with `pod`, same for `homebrew`. It would be confusing to change this now.

Again, this feedback is very much appreciated :+1:

**Comment by alexmx** [comment]
@KrauseFx No problem.
