### ISSUE TITLE
 can't satisfy 'json (< 3.0.0, >= 2.0.1)', already activated 'json-1.7.7' (Gem::LoadError)

### ISSUE THREAD

**Issue by lilongcnc** [fastlane/fastlane#7710]
- install fastlane sucess,but when run `fastlane init` have some error.
Successfully installed fastlane-2.3.1
1 gem installed

- input this: `$ fastlane init`

- then have some error:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1206:in `block in activate_dependencies': can't satisfy 'json (< 3.0.0, >= 2.0.1)', already activated 'json-1.7.7' (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'

**what should i do? **

**Comment by lilongcnc** [comment]
sorry,my english is not well.  i run `fastlane env`, the ouput is:
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1206:in `block in activate_dependencies': can't satisfy 'json (< 3.0.0, >= 2.0.1)', already activated 'json-1.7.7' (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by lilongcnc** [comment]
I don't solve the error yesterday. Then, I try to change mirr to `https://gems.ruby-china.org/`, I want do all step from beginning.
- First, I run sudo gem uninstall fastlane
output is
Password:
localhost:local Lauren$
`I don't konw if i uninstall success`

- Second, I run sudo gem install fastlane -NV, having some error:
output is
generator.c:861:25: error: use of undeclared identifier 'rb_cFixnum'
    } else if (klass == rb_cFixnum) {
                        ^
generator.c:863:25: error: use of undeclared identifier 'rb_cBignum'
    } else if (klass == rb_cBignum) {
                        ^
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
......
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
......
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
......
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
......
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
......
generator.c:975:5: warning: division by zero is undefined [-Wdivision-by-zero]
6 warnings and 2 errors generated.
make: *** [generator.o] Error 1
ERROR:  Error installing fastlane:
	ERROR: Failed to build gem native extension.

    Building has failed. See above output for more information on the failure.
make failed, exit code 2

Gem files will remain installed in /Users/Lauren/.rvm/rubies/ruby-2.4.0-rc1/lib/ruby/gems/2.4.0/gems/json-1.8.3 for inspection.
Results logged to /Users/Lauren/.rvm/rubies/ruby-2.4.0-rc1/lib/ruby/gems/2.4.0/extensions/x86_64-darwin-15/2.4.0/json-1.8.3/gem_make.out


- Third, i run fastlane env
output is 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'fastlane' (>= 0) among 31 total gem(s) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by oradyvan** [comment]
I confirm I have the same issue. `fastlane env` does not help. Here is the output:
```
jenkins$ gem list json

*** LOCAL GEMS ***

json (2.0.2, 1.8.3)
multi_json (1.12.1)
jenkins$ fastlane env
/Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1435:in `block in activate_dependencies': can't satisfy 'json (< 3.0.0, >= 2.0.1)', already activated 'json-1.8.3' (Gem::LoadError)
	from /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `each'
	from /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1427:in `activate_dependencies'
	from /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1409:in `activate'
	from /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:68:in `block in gem'
	from /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `synchronize'
	from /Users/jenkins/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:67:in `gem'
	from /Users/jenkins/.rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'
```

For me the solution was to downgrade to fastlane version 2.3.0

**Comment by lilongcnc** [comment]
I have sloved this problem by  install fastlane 2.3.0,and the version of Ruby is 2.3.

**Comment by ileitch** [comment]
Likely caused by this change: https://github.com/fastlane/fastlane/commit/b0a8aa4450599500bbb87c9cc06e511924c9d0b4

This issue is causing a different, but related error for me:
```
$ bundle update
Resolving dependencies......
Bundler could not find compatible versions for gem "json":
  In Gemfile:
    cocoapods (= 1.2.0.beta3) was resolved to 1.2.0.beta.3, which depends on
      activesupport (< 5, >= 4.0.2) was resolved to 4.2.7.1, which depends on
        json (>= 1.7.7, ~> 1.7)

    fastlane was resolved to 2.3.1, which depends on
      json (< 3.0.0, >= 2.0.1)
```

**Comment by KrauseFx** [comment]
Hey everyone, we just pushed [fastlane 2.4.0](https://github.com/fastlane/fastlane/releases/tag/2.4.0) which fixes the bundled _fastlane_, just run `fastlane update_fastlane` to get the latest release 🚀

However this release breaks support for Ruby 2.4.0 for now, which we should be able to add again soon. For now, please downgrade to an older version of Ruby, or use the bundled _fastlane_ from [download.fastlane.tools](https://download.fastlane.tools)

Please let us know if that works for you 👍

**Comment by syky27** [comment]
Hi Felix, I have tried your solution 
> just run `fastlane update_fastlane` to get the latest release 🚀

This command could not be completed because fastlane gem cannot run due dep's satisfaction

So I ran `gem install fastlane` then I check fastlane using `fastlane update_fastlane` and I got `Gem::ConflictError` on `json` gem so I did this:

```
gem uninstall json
gem install fastlane
```

And this time fastlane installed newer version of `json` and it is all working now.

Thank you 🎉

**Comment by oradyvan** [comment]
Hi @KrauseFx , updating fastlane to 2.4.0 just like you specified (`fastlane update_fastlane`) worked perfect for me. Thank you for the quick fix!

**Comment by KrauseFx** [comment]
Yeah, great to hear 👍
