### ISSUE TITLE
We are still having version validatio issue 

### ISSUE THREAD

**Issue by vikram1234** [fastlane/fastlane#7712]
### New Issue Checklist

https://github.com/fastlane/fastlane/issues/1513

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[00:54:10]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Issue while submitting to store
   https://github.com/fastlane/fastlane/issues/1513 [closed] 26 💬
   4 weeks ago


[!] The request could not be completed because:
	Re-validating version produced errors.
```

**Comment by sorenshg** [comment]
I got this same issue when I was trying to submit a new app for review. I figured out that I have not selected a price tier on iTunes Connect. I selected a price tier and then I could submit the app through deliver without any issues.

Hope this will work for you!

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
