### ISSUE TITLE
symlink File exists @ syserr_fail2_in when running `gym`

### ISSUE THREAD

**Issue by samuelbeek** [fastlane/fastlane#7713]
### Issue Description

When using `gym`, I get a very weird error:
```
/Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1371:in `symlink': [!] File exists @ syserr_fail2_in - /Users/samuelbeek/repos/WeTransfer-Mac/WeTransfer.app/Contents/Frameworks/Cartography.framework/Resources (Errno::EEXIST)
```

Please let me know if you need anything, so that we can figure out a fix. I know some ruby, so maybe I can add/change it myself :).

##### Complete output when running fastlane, including the stack trace and command used
command: `fastlane gym --scheme "WeTransferOSX Live" --clean`

_output (last 30 lines):_
```
[16:12:06]: ▸ Archive Succeeded
[16:12:06]: Compressing 6 dSYM(s)
[16:12:06]: $ cd '/Users/samuelbeek/Library/Developer/Xcode/Archives/2017-01-02/WeTransfer 2017-01-02 16.11.42.xcarchive/dSYMs' && zip -r '/Users/samuelbeek/repos/WeTransfer-Mac/WeTransfer.app.dSYM.zip' *.dSYM
[16:12:06]: ▸ zip I/O error: Permission denied
[16:12:06]: ▸ zip error: Could not create output file (/Users/samuelbeek/repos/WeTransfer-Mac/WeTransfer.app.dSYM.zip)

[16:12:06]: Successfully exported and compressed dSYM file

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1371:in `symlink': [!] File exists @ syserr_fail2_in - /Users/samuelbeek/repos/WeTransfer-Mac/WeTransfer.app/Contents/Frameworks/Cartography.framework/Resources (Errno::EEXIST)
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1371:in `copy'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1501:in `block in wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `each'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1500:in `wrap_traverse'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/gym/lib/gym/runner.rb:184:in `copy_mac_app'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/gym/lib/gym/runner.rb:31:in `run'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/gym/lib/gym/manager.rb:14:in `work'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/gym/lib/gym/commands_generator.rb:40:in `block (2 levels) in run'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/gym/lib/gym/commands_generator.rb:59:in `run'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/gym/lib/gym/commands_generator.rb:14:in `start'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.3.1/bin/fastlane:5:in `<top (required)>'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/bin/fastlane:22:in `load'
	from /Users/samuelbeek/.rvm/rubies/ruby-2.3.3/bin/fastlane:22:in `<main>'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/samuelbeek/.rvm/gems/ruby-2.3.3@global/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                              |
| ------------------- | -------------------------------------------------- |
| OS                  | 10.12.2                                            |
| Ruby                | 2.3.3                                              |
| Bundler?            | false                                              |
| Git                 | git version 2.10.0                                 |
| Installation Source | ~/.rvm/rubies/ruby-2.3.3/bin/fastlane              |
| Host                | Mac OS X 10.12.2 (16C67)                           |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.3/lib                       |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                        |
| Is contained        | false                                              |
| Xcode Path          | ~/../../Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                              |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "5c6cee03-4d4b-488e-a9b1-b7d2306d20d8"

default_platform :mac

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :tests do
  increment_build_number
  gym(
    scheme: "WeTransferOSX Live"
  )
  scan(scheme: "WeTransferOSX Live")
end

lane :beta do
  increment_build_number
  # gym(
  #   scheme: "WeTransferOSX Live"
  # )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.3.1   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2017-01-02**
</details>

**Comment by samuelbeek** [comment]
Thanks for the comment @KrauseFx, I didn't know there was a big difference between building macOS and iOS packages; interesting.
 I will take a look and see if I can (hopefully) figure out a fix 😄.

**Comment by vojto** [comment]
Same issue here.

**Comment by schlaeps** [comment]
This issue is definitely still occurring. Looks like it may be an issue with `FileUtils.cp_r`? Easily reproducible building any project with an embedded framework that has symlinks (which should be any embedded framework).
