### ISSUE TITLE
How to secure the json file for fastlane supply

### ISSUE THREAD

**Issue by paulononaka** [fastlane/fastlane#7715]
I am automating my CI with fastlane supply. Supply requires a json file that is created through Google Play to give fastlane access to upload my APK. Isn't unsafe to keep this json file in my CI? Looks like there is no way to pass the credentials through arguments, only through this file. If I could pass through arguments I could pass environment variables. I'm not expert in the subject, so sorry if I'm saying bullshit.

**Comment by VenkataMutyala** [comment]
@paulononaka @fastlane-bot @KrauseFx I actually have the same issue.

It looks like only a local file is supported at this time.
Per: https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb line 58 to 66  

I think it would help in terms of security by being able to pass in the credentials to supply as an environment variable or a parameter. This way we don't have to keep the .json file stored as plaintext on disk.




Here is my fastlane env output:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.5.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 2.0.2        |
| io-console                | 0.4.5        |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.3        |
</details>


*generated on:* **2017-01-04**
</details>

**Comment by VenkataMutyala** [comment]
@paulononaka I think you should be able to close this issue now. They just merged my PR into master so it should go out soon if it hasn't already. The flag you will want to use is -c instead of -j

**Comment by paulononaka** [comment]
Awesome! Thanks a lot @VenkataMutyala 😄
