### ISSUE TITLE
Simpler/less error-prone Fish shell Path binding

### ISSUE THREAD

**Issue by distransient** [fastlane/fastlane#7724]
Fastlane recommends appending a `set` command for `PATH` to the fish config. I recommend instead telling the user to use `fish_user_paths`. It's a universal variable which automatically prepends to the PATH, and doesn't require touching a file. The following...

```fish
set -U fish_user_paths $HOME/.fastlane/bin $fish_user_paths
```

...needs to only be ran once, and will immediately affect the current session and all future sessions.

**Comment by KrauseFx** [comment]
Hey @distransient, thanks for bringing this to our attention. I'm not a fish user myself, could you let me know what we should print out instead, so we can update the packaged fastlane? 👍 Thanks

**Comment by distransient** [comment]
Replace the whole file appending `set` with just:

```fish
set -U fish_user_paths $HOME/.fastlane/bin $fish_user_paths
```

**Comment by KrauseFx** [comment]
<img width="810" alt="screenshot 2017-01-04 19 14 35" src="https://cloud.githubusercontent.com/assets/869950/21653562/0b31a538-d2b2-11e6-9d80-d3f025ecc74e.png">

Is the diff above correct? Thanks again for your help @distransient 👍

**Comment by distransient** [comment]
Which file is this on?

**Comment by KrauseFx** [comment]
Hey, we just open sourced the code, can you take a look at https://github.com/fastlane/packaged-fastlane/pull/64? 

Thanks again for your help 👍
