### ISSUE TITLE
Silence output from zip action

### ISSUE THREAD

**Issue by rbaumbach** [fastlane/fastlane#7729]
🔑 Per fastlane/YourFirstPR.md I would like to start the discussion to see if it's appropriate for me to add additional functionality to the `zip` action.

As a user of the zip action, I would like to prevent the unnecessary output given from this action that can be given if a directory with many files is compressed.  It adds significant noise to my CI build console output.   I want to add a boolean flag to the zip action to silence the output of the zipping (`-q`).

Just looking for a thumbs up before I contribute =)

**Comment by KrauseFx** [comment]
Yeah, great idea, maybe hide the output by default and replace it with something sensible, and only show the raw output when an error occurs, or when `$verbose` is set 👍 

Sounds like a great candidate for a PR, thanks 👍

**Comment by hjanuschka** [comment]
as the PR #7777 has been merged, i am going to close this issue 💯  for your contribution
