### ISSUE TITLE
Using Match and Gym correctly for a complex build

### ISSUE THREAD

**Issue by weitzel926** [fastlane/fastlane#7745]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This is kind of a question related to both Gym and Match that I haven't been able to find an open issue about and could use some extra guidance.  

I have a complex workspace and build requirements.

1) Main app
	- Unique bundle ID.  Signed with account A.
	- Numerous deploys in HockeyApp.  Each has it's own bundle ID and provisioning profile.  Managed by account A.
2) Second app "flavor"
	- Unique bundle ID.  Signed with account B.
	- Numerous deploys in HockeyApp.  Each has it's own bundle ID and provisioning profile.  Managed by account A. (Yes A, not a typo)
3) Test tool app
	- Unique bundle ID.  Signed with account A.  

For each Hockey, the differences are P-list related.  So, we have build scripts that modify the plist, change the bundle ID and build the code with the right provisioning profile.  Right now, I am using the deprecated flags in gym to do this, and things work fine:  

gym(
      scheme: options[:scheme],
      clean: true,
      silent: true,
      provisioning_profile_path: options[:profile_path],
    )

(The scheme and the profile path are passed in).

In the output:

Using deprecated option: '--provisioning_profile_path' (Use target specific provisioning profiles instead)

Thus, my desire is to use Match for my multiple developer team as well as get rid of the deprecated flag -- I can't figure out how to do this.  For the main app and the second version of the app, we duplicated the target and made the changes specific to that release in the duplicated target.  This was a bit of a chore, but necessary for out needs.  I don't think the same approach is maintainable for each Hockey deploy/target because there are so many of them.  I was hoping I could use Target Dependencies to make the hockey targets "inherit" the settings from the main app, but thus far, I can't get it to work.  If I duplicate the main target, change the bundle ID and make the target dependency be the Main app target it works until I start removing stuff I don't want to maintain.  Specifically, it stops running (it does build) when I remove the Copy Bundle Resources entries.  We have tons of resources, and it won't be practical to manage that for each target.   

Am I approaching this correctly?  How can I achieve this?  

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                           |
| ------------------- | --------------------------------------------------------------- |
| OS                  | 10.12.2                                                         |
| Ruby                | 2.0.0                                                           |
| Bundler?            | true                                                            |
| Git                 | git version 2.2.1                                               |
| Installation Source | ~/workspace/XXX/vendor/bundle/ruby/2.0.0/bin/fastlane |
| Host                | Mac OS X 10.12.2 (16C67)                                        |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib  |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                     |
| Is contained        | false                                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version       | 7.3.1                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.4.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| rake                      | 12.0.0       |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| coffee-script-source      | 1.12.2       |
| colorful                  | 0.0.3        |
| execjs                    | 2.7.0        |
| json_pure                 | 2.0.2        |
| slop                      | 4.4.1        |
| bwoken                    | 2.0.0        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.2        |
| molinillo                 | 0.5.4        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| colorize                  | 0.8.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| coolops                   | 0.0.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-03**
</details>

**Comment by KrauseFx** [comment]
Have you seen the [Xcode docs](https://docs.fastlane.tools/codesigning/xcode-project/), you can probably do that using environment variables 👍

**Comment by weitzel926** [comment]
Thanks @KrauseFx.  I was actually still on 7.  I was trying to get the build up before we switched to 8, so we switched to 8 and the method mentioned there worked for me, with some minor caveats.  Thanks!

**Comment by asfalcone** [comment]
Looks like this issue has been resolved. Going to close it out 👍
