### ISSUE TITLE
Don't check for updates in CI or bundle exec builds

### ISSUE THREAD

**Issue by kdubb** [fastlane/fastlane#7746]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

You have a face paced release schedule... that's great!

For sanity, we use a version locked install of fastlane (via bundler) for both development and CI. In both these cases having fastlane check and report that version upgrades are available is not only useless (and a tiny bit annoying if we cannot update at the moment) but just adds needless to text to our CI build logs.

To put it in perspective we are now basing most of our development on fastlane. For example, starting and stopping local development server environments are now "lanes". So seeing this message for ever command does begin to interfere with your daily tasks.  You've had 3 releases in 3 days... at this point we've almost never run without an upgrade notice.

Detecting that fastlane is in one of these states and forgoing the check for updates, and therefore the display of the notice, would be nice.  A better idea for interactive use may be only do the check once in 24 hours; we get the notice but we're not inundated.

##### Complete output when running fastlane, including the stack trace and command used

A simple command to stop a local development server environment... ended with a message we cannot act upon (yet).

```

+-------------------------------------------------------+---------+---------------------------------------+
|                                              Used plugins                                               |
+-------------------------------------------------------+---------+---------------------------------------+
| Plugin                                                | Version | Action                                |
+-------------------------------------------------------+---------+---------------------------------------+
| fastlane-plugin-update_provisioning_profile_specifier | 1.2.0   | update_provisioning_profile_specifier |
| fastlane-plugin-update_project_codesigning            | 0.1.7   | update_project_codesigning            |
+-------------------------------------------------------+---------+---------------------------------------+

[12:11:28]: Driving the lane 'stop_environment' 🚀
[12:11:28]: ----------------------------------
[12:11:28]: --- Step: ensure_xcode_version ---
[12:11:28]: ----------------------------------
[12:11:28]: $ xcversion selected
[12:11:28]: ▸ Xcode 8.2
[12:11:28]: ▸ Build version 8C38
[12:11:28]: Selected Xcode version is correct: 8.2
[12:11:28]: -------------------
[12:11:28]: --- Step: is_ci ---
[12:11:28]: -------------------
[12:11:28]: -------------------
[12:11:28]: --- Step: is_ci ---
[12:11:28]: -------------------
[12:11:28]: ----------------------------
[12:11:28]: --- Step: docker_compose ---
[12:11:28]: ----------------------------
[12:11:28]: $ docker-compose  -f fastlane/edge-dev-compose.yml --project-name dev down
[12:11:29]: ▸ Stopping dev_edge_1 ...
[12:11:29]: ▸ Stopping dev_postgres_1 ...
[12:11:29]: ▸ Stopping dev_apns_1 ...
[12:11:50]: ▸ [1BRemoving dev_edge_1 ...
[12:11:50]: ▸ Removing dev_postgres_1 ...
[12:11:50]: ▸ Removing dev_apns_1 ...
[12:11:50]: ▸ [2BRemoving network dev_default

+------+----------------------+-------------+
|             fastlane summary              |
+------+----------------------+-------------+
| Step | Action               | Time (in s) |
+------+----------------------+-------------+
| 1    | ensure_xcode_version | 0           |
| 2    | is_ci                | 0           |
| 3    | is_ci                | 0           |
| 4    | docker_compose       | 21          |
+------+----------------------+-------------+

[12:11:50]: fastlane.tools finished successfully 🎉

#######################################################################
# fastlane 2.5.0 is available. You are on 2.4.0.
# It is recommended to use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.5.0 2-factor improvements
* Improve support for 2-factor and 2-step verification a lot (#7738)
* Add support for application specific passwords using environment variables (#7738)
* Improved wording and documentation for 2-factor and 2-step (#7738)
* Update checker ensures valid RubyGems source for fastlane updates (#7734)
* Print fastlane path when running `fastlane -v` (#7733)
* Fix crash in _deliver_ when using the new `live` option (#7726)
* Fix USB device discovery to account for USB hubs (#7727)
* Fix USB data parsing problem for DeviceManager (#7725)
* Skip installing plugins when running `fastlane -v` (#7722)
* Add support for uploading proguard mapping files (#7721)

Please update using `bundle update fastlane`


```

### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.4.0   | 🚫 Update availaible |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-update_provisioning_profile_specifier | 1.2.0   | ✅ Up-To-Date  |
| fastlane-plugin-update_project_codesigning            | 0.1.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version      |
| ----------------------------------------------------- | ------------ |
| did_you_mean                                          | 1.0.0        |
| bundler                                               | 1.13.7       |
| io-console                                            | 0.4.6        |
| CFPropertyList                                        | 2.3.4        |
| i18n                                                  | 0.7.0        |
| json                                                  | 1.8.3        |
| minitest                                              | 5.10.1       |
| thread_safe                                           | 0.3.5        |
| tzinfo                                                | 1.2.2        |
| activesupport                                         | 4.2.7.1      |
| public_suffix                                         | 2.0.5        |
| addressable                                           | 2.5.0        |
| babosa                                                | 1.0.2        |
| claide                                                | 1.0.1        |
| fuzzy_match                                           | 2.0.4        |
| nap                                                   | 1.1.0        |
| cocoapods-core                                        | 1.1.1        |
| cocoapods-deintegrate                                 | 1.0.1        |
| cocoapods-downloader                                  | 1.1.3        |
| cocoapods-plugins                                     | 1.0.0        |
| cocoapods-search                                      | 1.0.0        |
| cocoapods-stats                                       | 1.0.0        |
| netrc                                                 | 0.7.8        |
| cocoapods-trunk                                       | 1.1.2        |
| cocoapods-try                                         | 1.1.0        |
| colored                                               | 1.2          |
| escape                                                | 0.0.4        |
| fourflusher                                           | 2.0.1        |
| gh_inspector                                          | 1.0.2        |
| molinillo                                             | 0.5.4        |
| nanaimo                                               | 0.2.3        |
| xcodeproj                                             | 1.4.2        |
| cocoapods                                             | 1.1.1        |
| highline                                              | 1.7.8        |
| commander                                             | 4.4.3        |
| unf_ext                                               | 0.0.7.2      |
| unf                                                   | 0.1.4        |
| domain_name                                           | 0.5.20161129 |
| dotenv                                                | 2.1.1        |
| excon                                                 | 0.54.0       |
| multipart-post                                        | 2.0.0        |
| faraday                                               | 0.10.1       |
| http-cookie                                           | 1.0.3        |
| faraday-cookie_jar                                    | 0.0.6        |
| faraday_middleware                                    | 0.10.1       |
| fastimage                                             | 2.0.1        |
| jwt                                                   | 1.5.6        |
| little-plugger                                        | 1.1.4        |
| multi_json                                            | 1.12.1       |
| logging                                               | 2.1.0        |
| memoist                                               | 0.15.0       |
| os                                                    | 0.9.6        |
| signet                                                | 0.7.3        |
| googleauth                                            | 0.5.1        |
| httpclient                                            | 2.8.3        |
| hurley                                                | 0.2          |
| mime-types-data                                       | 3.2016.0521  |
| mime-types                                            | 3.1          |
| uber                                                  | 0.0.15       |
| representable                                         | 2.3.0        |
| retriable                                             | 2.1.0        |
| google-api-client                                     | 0.9.20       |
| mini_magick                                           | 4.5.1        |
| multi_xml                                             | 0.6.0        |
| plist                                                 | 3.2.0        |
| rubyzip                                               | 1.2.0        |
| security                                              | 0.1.3        |
| slack-notifier                                        | 1.5.1        |
| terminal-notifier                                     | 1.7.1        |
| unicode-display_width                                 | 1.1.2        |
| terminal-table                                        | 1.7.3        |
| word_wrap                                             | 1.0.0        |
| rouge                                                 | 1.11.1       |
| xcpretty                                              | 0.2.4        |
| xcpretty-travis-formatter                             | 0.0.4        |
| fastlane-plugin-update_project_codesigning            | 0.1.7        |
| fastlane-plugin-update_provisioning_profile_specifier | 1.2.0        |
| xcode-install                                         | 2.1.0        |
</details>

**Comment by KrauseFx** [comment]
You can either set `FASTLANE_SKIP_UPDATE_CHECK` or `FASTLANE_HIDE_CHANGELOG` (one skip the update checks all together, the other will just hide the changelog.

**Comment by kdubb** [comment]
@KrauseFx Thanks for the info.  I can update our CI easily.  For local, is there a easy place to put this in our fastlane setup or do we resort to .bashrc/.zshrc?

**Comment by KrauseFx** [comment]
`.bashrc/.zshrc` works 👍
