### ISSUE TITLE
Gym hangs when using xcpretty

### ISSUE THREAD

**Issue by xtreme-shane-lattanzio** [fastlane/fastlane#7747]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We are using concourse to run our continuous delivery builds. When doing this, gym seems to hang on the following command:

set -o pipefail && xcodebuild -workspace ../testapp/testapp.xcworkspace -scheme testapp-na -configuration Staging -destination 'generic/platform=iOS' -archivePath /Users/office/Library/Developer/Xcode/Archives/2017-01-04/test-NA-1.0.1-20170104-Staging-Internal\ 2017-01-04\ 16.39.34.xcarchive clean archive | tee /Users/office/Library/Logs/gym/Blindside-test-na.log | xcpretty

When running with the disable xcpretty tag there is no hang. I can run the command on my local machine with xcpretty with no issue. The hang only happens when running through concourse. I can also run the command directly in concourse without using fastlane and it does not hang in this case as well.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1004)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby 

default_platform :ios

ENV["LANG"] = "en_US.UTF-8"
ENV["LANGUAGE"] = "en_US.UTF-8"
ENV["LC_ALL"] = "en_US.UTF-8"

platform :ios do
  lane :build_ipa do |options|

 #   increment_build_number

      gym(
        workspace: EDITED,
        scheme: EDITED,
        clean: true,
        configuration: "Staging",
        output_directory: "../builds",
        output_name: STAGING_BUILDNAME,
        use_legacy_build_api: true,
        disable_xcpretty: true
        )
  end
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "yaaay" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| credentials_manager | 0.16.2  | ✅ Up-To-Date  |
| spaceship           | 0.39.0  | ✅ Up-To-Date  |
| fastlane            | 2.5.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.6.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.0        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| json                      | 1.8.3        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-01-04**
</details>

**Comment by joshdholtz** [comment]
@xfreebird I have never ran anything in consourse before but it seems like it _may_ be an issue more on their side. I see you are setting the follow environment variables in your `Fastfile` but concourse _may_ not like that for some reason. I would maybe try setting those outside of your `Fastfile` either in the bash command or using concourse's environment variable system.

Sorry for not being more help initially but this might be a good place to start debugging 😇 

```
ENV["LANG"] = "en_US.UTF-8"
ENV["LANGUAGE"] = "en_US.UTF-8"
ENV["LC_ALL"] = "en_US.UTF-8"
```

**Comment by xtreme-shane-lattanzio** [comment]
I have tried this previously with no success. I am not sure why environment variables would cause an issue only for the case that xcpretty is disabled.

**Comment by asfalcone** [comment]
Following the linked issue from carthage the follow resolution was listed:

Add
`sh("security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k #{ENV["KEYCHAIN_PASSWORD"]} #{ENV["KEYCHAIN_NAME"]}")`
to your Fastfile after _sigh_ and _cert_ 

Could you give this a try and let me know?
