### ISSUE TITLE
xcpretty conflict

### ISSUE THREAD

**Issue by SiarheiFedartsou** [fastlane/fastlane#775]
Hi! I'm trying to install fastlane at my jenkins machine and I've faced with the problem:
```shell
lcsas-Mac-mini:Users jenkins$ sudo gem install fastlane
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires xcpretty (>= 0.1.11); scan requires xcpretty (~> 0.1.12); xcpretty-travis-formatter requires xcpretty (>= 0.0.7, ~> 0.2)
```

It seems that different parts of fastlane needs different xcpretty version... How can I fix it?

**Comment by KrauseFx** [comment]
Fixing this now - sorry about that

**Comment by KrauseFx** [comment]
Please try again now :+1:

**Comment by SiarheiFedartsou** [comment]
@KrauseFx thank you for quick fix! I cannot check it right now(because I don't have access to my jenkins machine right now), but I've already fixed it by installing xcpretty-travis-formatter-0.0.3 gem before fastlane gem.

**Comment by KrauseFx** [comment]
Cool :+1:
