### ISSUE TITLE
Support setting testers in supply?

### ISSUE THREAD

**Issue by chrisvire** [fastlane/fastlane#7764]
### Issue Description

I see in the Google Play Developer API [documentation](https://developers.google.com/android-publisher/api-ref/edits/testers) that there is support for managing testers. However, I don't see any way to configure this in [supply](https://github.com/fastlane/fastlane/tree/master/supply#readme).  Was this feature tested but it isn't working? Was this feature intentionally left out (for some other reason)?  Or do you need someone to implement it?

### Environment

Ruby 2.0
Supply 2.1.1

**Comment by chrisvire** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | debian_based jessie/sid                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 1.9.1                                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Ubuntu 14.04.3 LTS debian_based jessie/sid (3.13.0-86-generic) |
| Ruby Lib Dir        | /usr/lib                                                       |
| OpenSSL Version     | OpenSSL 1.0.1f 6 Jan 2014                                      |
| Is contained        | false                                                          |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.1.1   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.2        |
</details>


*generated on:* **2017-01-06**
</details>

**Comment by asfalcone** [comment]
Hi @chrisvire. It would be awesome if you submitted a PR for managing testers via _supply_! 🤗

**Comment by chrisvire** [comment]
I was curious why the API was there but it wasn't included in the implementation.  I wanted to make sure the actual API worked...

I noticed that for [Edit.testers/get](https://developers.google.com/android-publisher/api-ref/edits/testers/get), [Edit.testers/patch](https://developers.google.com/android-publisher/api-ref/edits/testers/patch), and [Edit.testers/update](https://developers.google.com/android-publisher/api-ref/edits/testers/update) are actually the same as Edit.tracks.

**Comment by asfalcone** [comment]
We haven't had a chance to play around with it, so I'm not sure of the status of the API :) It's going to take some digging for sure 👷
