### ISSUE TITLE
Fastlane crashes after updating to 2.5.0 on Linux Fedora 22

### ISSUE THREAD

**Issue by cdongieux** [fastlane/fastlane#7765]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Fastlane crashes after updating to from 2.4.0 to 2.5.0 on Fedora Linux.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$ fastlane
/usr/local/share/gems/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/ui/ui.rb:5:in `current': uninitialized constant Class::Shell (NameError)
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:265:in `load_plugins'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/commands_generator.rb:33:in `start'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /usr/local/share/gems/gems/fastlane-2.5.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
$ fastlane env

Looking for related GitHub issues on fastlane/fastlane...

➡️  Remove Shenzhen dependency
   https://github.com/fastlane/fastlane/pull/6991 [closed] 19 💬
   3 weeks ago

➡️  build succeeded but can't archive with jenkins
   https://github.com/fastlane/fastlane/issues/4333 [closed] 0 💬
   20 Oct 2016

/usr/local/share/gems/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/ui/ui.rb:5:in `current': [!] uninitialized constant Class::Shell (NameError)
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/environment_printer.rb:20:in `get'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/commands_generator.rb:223:in `block (2 levels) in run'
	from /usr/local/share/gems/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/share/gems/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/share/gems/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/share/gems/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/share/gems/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/commands_generator.rb:293:in `run'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/commands_generator.rb:36:in `start'
	from /usr/local/share/gems/gems/fastlane-2.5.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /usr/local/share/gems/gems/fastlane-2.5.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by KrauseFx** [comment]
Please share the `fastlane env` output

**Comment by cdongieux** [comment]
The output below "$ fastlane env" is what is output.

**Comment by mfurtak** [comment]
I've wrapped the output sections in code fences (```) to make them a little easier to see :+1:

**Comment by KrauseFx** [comment]
Ahhh, interesting, the `fastlane env` command fails too, because `shell` can't be found. Could you share your Gemfile with us?

**Comment by cdongieux** [comment]
I don't have a Gemfile, executing fastlane in any directory produces this crash.

**Comment by KrauseFx** [comment]
That's a bug that needs to be fixed. Unfortunately we don't have any Linux machines ready to reproduce and fix the issue. Do you have the Ruby knowledge to dive into this and maybe prepare a PR? Otherwise we'll try our best to prepare a fix 👍

**Comment by mfurtak** [comment]
This is a strange one. I don't immediately see a reason why this would have broken between 2.4 and 2.5.

@cdongieux - by what means did you install _fastlane_ originally, and by what means did you upgrade it?

---

Just looking at the way that the code is failing, my suspicion is that `shell.rb` is not being found and required, which is handled by: https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/ui.rb#L21-L24

Given that we only have one implementation, and we instantiate it directly by name anyway (https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ui/ui.rb#L5), is our indirect loading really buying us very much right now? Might it not be simpler to just  `require 'fastlane_core/ui/implementations/shell'`?

**Comment by cdongieux** [comment]
@KrauseFx I discovered Ruby 3 days ago when I started using Fastlane, so I'm a beginner :D I know Linux quite well even though Fedora is not my favorite distribution (it is installed on my work computer), so I can try to help you, just tell me what to do.

@mfurtak When I first installed Fastlane on my Fedora 22 I did a `sudo gem install fastlane`, which installed fastlane-2.4.0.
Unfortunately running `fastlane init` did not work the first time: there was some gemspec file access issue (I can't remember its name right now, I'll tell you on monday): indeed this file belonged to root:root and was not readable by group and others. Performing a `sudo chmod a+r /path/to/the/xxx.gemspec` solved that issue, but running again `fastlane init` failed because of the fastlane file having the same issue as the gemspec file. Performing the chmod on it solved the problem and fastlane 2.4.0 finally ran smoothly.
Then Fastlane 2.5.0 came up, so I did a `sudo gem update fastlane`. Running fastlane produced the same issues as described for 2.4.0 (gemspec and fastlane files read permission issues), and the issue described in the first post of this issue.
So, maybe, these files permission issues apply to other gems too, and leads to the Shell issue.
The good news: today I installed Fastlane on my home machine (Linux Debian): all went fine without any error.

**Comment by mfurtak** [comment]
@cdongieux Thanks for those details - very interesting! A permissions problem might also explain things.

I wonder - on your machine that is having problems... if you do `sudo gem uninstall fastlane` followed by `gem install fastlane` (without `sudo` this time) does anything change?

**Comment by cdongieux** [comment]
So here is the stacktrace just after having installed Fastlane with `sudo gem install fastlane`:

`$ fastlane 
/usr/share/rubygems/rubygems/stub_specification.rb:75:in `initialize': Permission denied @ rb_sysopen - /usr/local/share/gems/specifications/fastlane-2.6.0.gemspec (Errno::EACCES)
	from /usr/share/rubygems/rubygems/stub_specification.rb:75:in `open'
	from /usr/share/rubygems/rubygems/stub_specification.rb:75:in `data'
	from /usr/share/rubygems/rubygems/stub_specification.rb:178:in `valid?'
	from /usr/share/rubygems/rubygems/specification.rb:731:in `block in each_stub'
	from /usr/share/rubygems/rubygems/specification.rb:723:in `block (2 levels) in each_gemspec'
	from /usr/share/rubygems/rubygems/specification.rb:722:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:722:in `block in each_gemspec'
	from /usr/share/rubygems/rubygems/specification.rb:721:in `each'
	from /usr/share/rubygems/rubygems/specification.rb:721:in `each_gemspec'
	from /usr/share/rubygems/rubygems/specification.rb:729:in `each_stub'
	from /usr/share/rubygems/rubygems/specification.rb:748:in `stubs'
	from /usr/share/rubygems/rubygems/specification.rb:936:in `find_inactive_by_path'
	from /usr/share/rubygems/rubygems.rb:187:in `try_activate'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
	from <internal:abrt_prelude>:2:in `<compiled>'`

`$ ll /usr/local/share/gems/specifications/fastlane-2.6.0.gemspec
-rw-r-----. 1 root root 8934 Jan  9 08:49 /usr/local/share/gems/specifications/fastlane-2.6.0.gemspec`

`$ sudo chmod a+r /usr/local/share/gems/specifications/fastlane-2.6.0.gemspec`

`$ fastlane 
/usr/bin/ruby-mri: Permission denied -- /usr/local/bin/fastlane (LoadError)`

`$ ll /usr/local/bin/fastlane
-rwxr-x--x. 1 root root 497 Jan  9 08:49 /usr/local/bin/fastlane`

`$ sudo chmod a+r /usr/local/bin/fastlane`

`$ fastlane 
/usr/local/share/gems/gems/fastlane-2.6.0/fastlane_core/lib/fastlane_core/ui/ui.rb:5:in `current': uninitialized constant Class::Shell (NameError)
	from /usr/local/share/gems/gems/fastlane-2.6.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/share/gems/gems/fastlane-2.6.0/fastlane/lib/fastlane/plugins/plugin_manager.rb:265:in `load_plugins'
	from /usr/local/share/gems/gems/fastlane-2.6.0/fastlane/lib/fastlane/commands_generator.rb:33:in `start'
	from /usr/local/share/gems/gems/fastlane-2.6.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /usr/local/share/gems/gems/fastlane-2.6.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'`

@mfurtak If I do `sudo gem uninstall fastlane` followed by `gem install fastlane`, running Fastlane just works fine!

**Comment by mfurtak** [comment]
OK, great! I'm glad you are back in business. :raised_hands:

We typically recommended people to `sudo gem install fastlane` because most users were on Macs, and this minimized problems with the way system Ruby worked on Macs.

This may not the right suggestion for Linux users, so we'll see if we can make those instructions better.

Thanks for your detailed notes! :100:
