### ISSUE TITLE
Take advantage of shared screenshots across localizations

### ISSUE THREAD

**Issue by keeshux** [fastlane/fastlane#7767]
It'd be nice to replicate the same functionality provided by the "Use English (U.S.) X.Y-Inch Display" checkbox in the "Screenshots" area on iTunes Connect. Actually, replace English with app's primary language.

In my scenario, I only use English screenshots for all other localization, and they're a lot (5 screenshots * 6 devices * 20 localizations = 600). By doing so, one can save both much time and bandwidth (if not on a broadband).

**Comment by KrauseFx** [comment]
Yeah, so it should be fine to set the checkbox on iTunes Connect and then just provide English screenshots to upload. 
Ideally you should use [snapshot](https://docs.fastlane.tools/getting-started/ios/screenshots/) to generate localised screenshots for your app 👍

**Comment by keeshux** [comment]
Thanks for the snappy answer @KrauseFx. Yeah we use snapshot for the application but we switched to framed screenshots and we still have to automate them. It's easier reverting to a single screenshots language for now.

However, my point is that I'd like that operation to be automated in `deliver`. Otherwise I would have to tick the checkbox for all localizations and all devices, and we're talking about non trivial numbers here.

**Comment by KrauseFx** [comment]
Yeah, sorry that's currently not possible in _deliver_ and not something that's planned to be implemented, since the ideal solution with _fastlane_ is to generate new screenshots using _snapshot_ 👍
