### ISSUE TITLE
Warning on `require` from Ruby stdlib / fastlane_require doesn't load from stdlib

### ISSUE THREAD

**Issue by reidab** [fastlane/fastlane#7769]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When requiring a module from Ruby's standard library in a Fastfile, fastlane warns: `You require a gem, if this is a third party gem, please use `fastlane_require 'base64'` to ensure the gem is installed locally`. Using `fastlane_require 'base64'` as suggested fails because `base64` is not a gem.

It seems like either the `require` scan should whitelist stdlib requires, or `fastlane_require` should support loading these dependencies.

This is by no means a blocker, since the `require` works fine, but it seems like the message is pointing people in the wrong direction in this case.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

**With `require`**

```
reidab ➜ bundle exec fastlane ios logo
[00:12:07]: You require a gem, if this is a third party gem, please use `fastlane_require 'base64'` to ensure the gem is installed locally

[... build continues ...]
```

**With `fastlane_require`**

```
reidab ➜ bundle exec fastlane ios logo
[00:13:09]: Missing gem 'base64', please add the following to your local Gemfile:
[00:13:09]:
[00:13:09]: ▸ gem "base64"
[00:13:09]:

[!] Add 'gem "base64"' to your Gemfile and restart fastlane
```

**Comment by reidab** [comment]
This turned out to be a red herring — the real issue is that `fastlane_require`'s `gem_installed?` check relies on the return value of `require` and `base64` had already been loaded. Opening a new issue for that.

**Comment by KrauseFx** [comment]
Great catch, thanks for the PR 👍
