### ISSUE TITLE
Show upload progress for some actions

### ISSUE THREAD

**Issue by larryonoff** [fastlane/fastlane#777]
Could you please add displaying upload progress for fastlane action splunkmint / crashlytics?

**Comment by xfreebird** [comment]
@larryonoff for ```crashlytics``` action now that is impossible, because ```Crashlytics``` ```submit``` command does not offer such information.  

For the ```splunkmint``` action that is possible as option for curl. See PR #783

**Comment by larryonoff** [comment]
@xfreebird thank you.

**Comment by xfreebird** [comment]
@larryonoff the ```splunkmint``` upload progress option is already in the latest release

**Comment by larryonoff** [comment]
@xfreebird Thank you!
