### ISSUE TITLE
Deliver cannot upload ipa to Applestore

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#7778]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Running Fastlane upload_ipa but delivery do not create new version, verfy new version and upload ipa file into Apple store
> fastlane upload_ipa

#### Lane upload_ipa
```
  desc "Upload iPA to Apple Store"
  lane :upload_ipa do
    deliver(force: true)
  end
```

#### Deliverfile
```
app_identifier ENV["BUNDLE_IDENTIFIER"] 
username ENV["FASTLANE_USER"]
name ENV["APP_NAME"]
team_name ENV["TEAM_NAME"]
app_version ENV["BUNDLE_VERSION"]
team_id ENV["DELIVER_TEAM_ID"]
edit_live "false"
```
#### Logs From: Jenkins (call lane upload_ipa in other lane)
[11:22:42]: [32m--- Step: deliver ---[0m
[11:22:42]: [32m---------------------[0m
[11:22:42]: [32mSuccessfully loaded '/Users/Shared/Jenkins/Home/jobs/360_iOS_fastlane/workspace/fastlane/Deliverfile' 📄[0m

+-----------------------+---------------------------------------+
|         Detected Values from './fastlane/Deliverfile'         |
+-----------------------+---------------------------------------+
| app_identifier        | x.y.z            |
| username              | test@360.com                    |
| name                  | sbc                            |
| team_name             | ABC PTY LTD |
| team_id               | xxxxxxxx                             |
| edit_live             | false                                 |
+-----------------------+---------------------------------------+

[11:22:42]: Login to iTunes Connect (test@360.com)
[11:22:45]: [32m-------------------------------------------------------------------------------------------------------------------------------------------------[0m
+------------------------------+-------------------------------------------------------------------+
|                                           [33mLane Context[0m                                           |
+------------------------------+-------------------------------------------------------------------+
| DEFAULT_PLATFORM             | ios                                                               |
| PLATFORM_NAME                | ios                                                               |
| LANE_NAME                    | ios upload_appstore                                               |
| CERT_FILE_PATH               | /Users/Shared/Jenkins/Home/jobs/360_iOS_fastlane/workspa... |
| CERT_CERTIFICATE_ID          | xxxxxxxxx                                                        |
| SIGH_PROFILE_PATH            | /Users/Shared/Jenkins/Home/jobs/360_iOS_fastlane/workspa... |
| SIGH_PROFILE_PATHS           | ["/Users/Shared/Jenkins/Home/jobs/360_iOS_fastlane/works... |
| SIGH_UDID                    | c355f99f-2a11-4bd7-80b4-0d8718a9d97e                              |
| SIGH_UUID                    | c355f99f-2a11-4bd7-80b4-0d8718a9d97e                              |
| SIGH_PROFILE_TYPE            | app-store                                                         |
| BUILD_NUMBER                 | There does not seem to be a CURRENT_PROJECT_VERSION key set fo... |
| XCODEBUILD_DERIVED_DATA_PATH |                                                                   |
| IPA_OUTPUT_PATH              | /Users/Shared/Jenkins/Home/jobs/360_iOS_fastlane/workspa... |
| DSYM_OUTPUT_PATH             | /Users/Shared/Jenkins/Home/jobs/360_iOS_fastlane/workspa... |
| XCODEBUILD_ARCHIVE           | /Users/jenkins/Library/Developer/Xcode/Archives/2017-01-09/JMa... |
+------------------------------+-------------------------------------------------------------------+
[11:22:45]: [31m**Unauthorized Access[**0m

### Running directly in terminal
[13:52:47]: ---------------------
[13:52:47]: --- Step: deliver ---
[13:52:47]: ---------------------
[13:52:47]: Successfully loaded '/Users/Shared/Jenkins/Home/jobs/360_iOS_fastlane/workspace/fastlane/Deliverfile' 📄

+-----------------------+---------------------------------------+
|         Detected Values from './fastlane/Deliverfile'         |
+-----------------------+---------------------------------------+
| app_identifier        | x.y.z            |
| username              | test@360.com                    |
| name                  | Bolderland                            |
| team_name             | JMANGO AUSTRALIA (OPERATIONS) PTY LTD |
| team_id               | 118055852                             |
| edit_live             | false                                 |
+-----------------------+---------------------------------------+

[13:52:47]: Login to iTunes Connect (test@360.com)
[13:52:52]: Login successful

+-----------------------+---------------------------------------+
|                     deliver 2.6.0 Summary                     |
+-----------------------+---------------------------------------+
| force                 | true                                  |
| app_identifier        | x.y.z               |
| username              | test@360.com                    |
| name                  | abc                            |
| team_name             | ABC (OPERATIONS) PTY LTD |
| team_id               | 118055852                             |
| edit_live             | false                                 |
| screenshots_path      | ./fastlane/screenshots                |
| metadata_path         | ./fastlane/metadata                   |
| platform              | ios                                   |
| skip_binary_upload    | false                                 |
| skip_screenshots      | false                                 |
| skip_metadata         | false                                 |
| submit_for_review     | false                                 |
| automatic_release     | false                                 |
| dev_portal_team_id    | xxxxxxxxxx                            |
| dev_portal_team_name  | ABC (OPERATIONS) PTY LTD |
| overwrite_screenshots | false                                 |
+-----------------------+---------------------------------------+

[13:52:56]: Error with provided 'name'. Must be a hash, the key being the language.
[13:52:56]: Uploading metadata to iTunes Connect
[13:52:58]: Successfully uploaded set of metadata to iTunes Connect
[13:52:59]: Starting with the upload of screenshots...
[13:52:59]: Successfully uploaded screenshots to iTunes Connect
[13:53:02]: Finished the upload to iTunes Connect
[13:53:02]: 
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1: 2.6.0
If you used `--capture_output` option please remove this block - as it is already included there.

[<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

desc "Upload iPA to Apple Store"
  lane :upload_ipa do
    deliver(force: true)
  end

  desc "Deploy a new version to the App Store"
  lane :upload_appstore do
    sh "fastlane-credentials add --username FASTLANE_USER --password KEYCHAIN_PASSWORD"
    publishing = ENV["PUBLISHING"]
    puts publishing
    if publishing == '1'
      createnewapp
    end 
    set_google_info_plist_value
    appleprovision
    sh "pod cache clean 360-Data --all"
    sh "pod cache clean 360-Domain --all"
    sh "pod update" 
    increment_build_number(build_number: BUILD_NUMBER) 
    sh "mv '#{ENV["PROJECT_DIR"]}'/*.mobileprovision brandedapp.mobileprovision"
    parsed = FastlaneCore::ProvisioningProfile.parse("brandedapp.mobileprovision")
    ProfileSpecifier = parsed["Name"]
    sh "echo PROVISIONING_PROFILE_SPECIFIER=#{ProfileSpecifier} >> .env"
    puts ProfileSpecifier;
    unlock_keychain(path: "login.keychain", password: KEYCHAIN_PASSWORD)
    xcclean(scheme: "360" )
    sh "sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/' '#{ENV["PROJECT_DIR"]}'/360.xcodeproj/project.pbxproj"
    gym(scheme: "360",codesigning_identity: CODE_SIGN_IDENTITY,xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{ProfileSpecifier}'")
    upload_ipa
    sh "fastlane-credentials remove --username FASTLANE_USER"
  end
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["BUNDLE_IDENTIFIER"] 
apple_id ENV["FASTLANE_USER"]
team_name ENV["TEAM_NAME"]
team_id ENV["TEAM_ID"]

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.6.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-01-09**
</details>]

**Comment by biolinh** [comment]
The weird thing is that I doesn't use ipa option to specific path of ipa file, and Delivery still find right ipa file to upload.

Now, I have just added ipa option intho DeliverFile,
```
app_identifier ENV["BUNDLE_IDENTIFIER"]
username ENV["FASTLANE_USER"]
name ENV["APP_NAME"]
team_name ENV["TEAM_NAME"]
app_version ENV["BUNDLE_VERSION"]
team_id ENV["DELIVER_TEAM_ID"]
edit_live "false"
ipa "build/360.ipa"
```

and runs again:

16:47:57]: --- Step: deliver ---
[16:47:57]: ---------------------
[16:47:57]: Successfully loaded '/Users/Shared/Jenkins/Home/jobs/JMango360_iOS_fastlane/workspace/fastlane/Deliverfile' 📄

+-----------------------+---------------------------------------+
|         Detected Values from './fastlane/Deliverfile'         |
+-----------------------+---------------------------------------+
| app_identifier | x.y.z |
| username | test@360.com |
| name | ABC |
| team_name | ABC (OPERATIONS) PTY LTD |
| team_id | xxxxxxxxxx |
| edit_live | false |
| ipa                   | build/JMango360.ipa                   |
+-----------------------+---------------------------------------+

[16:47:57]: Login to iTunes Connect (test@jmango360.com)
[16:48:04]: Login successful

+-----------------------+---------------------------------------+
| deliver 2.6.0 Summary |
+-----------------------+---------------------------------------+
| force | true |
| app_identifier | x.y.z |
| username | test@360.com |
| name | abc |
| team_name | ABC (OPERATIONS) PTY LTD |
| team_id | xxxxxxxxxx |
| edit_live | false |
| ipa                   | build/360.ipa                   |
| screenshots_path | ./fastlane/screenshots |
| metadata_path | ./fastlane/metadata |
| platform | ios |
| skip_binary_upload | false |
| skip_screenshots | false |
| skip_metadata | false |
| submit_for_review | false |
| automatic_release | false |
| dev_portal_team_id | xxxxxxxxxx |
| dev_portal_team_name | ABC (OPERATIONS) PTY LTD |
| overwrite_screenshots | false |
+-----------------------+---------------------------------------+
[16:48:05]: Making sure the latest version on iTunes Connect matches '2.13.1' from the ipa file...
[16:48:07]: '2.13.1' is the latest version on iTunes Connect
[16:48:10]: Error with provided 'name'. Must be a hash, the key being the language.
[16:48:10]: Uploading metadata to iTunes Connect
[16:48:13]: Successfully uploaded set of metadata to iTunes Connect
[16:48:14]: Starting with the upload of screenshots...
[16:48:14]: Successfully uploaded screenshots to iTunes Connect
[16:48:17]: Uploading binary to iTunes Connect
[16:48:17]: Going to upload updated app to iTunes Connect
[16:48:17]: This might take a few minutes. Please don't interrupt the script.

**Comment by asfalcone** [comment]
@biolinh Is your issue resolved? It seems like finding the `ipa` param for _deliver_ solved it?
