### ISSUE TITLE
Mac app doesn't get submitted for review, stays in 'Prepare for Submission'

### ISSUE THREAD

**Issue by masteranza** [fastlane/fastlane#7780]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

So I've noticed this issue happening in 2.5.0, but it continues to persist in 2.6.0.
Fastlane successfully uploaded the build and it claims no errors in selecting it, but the build doesn't get submitted for review.
All metadata is there, so I'm at lost at telling what happened.
Is there a command similar to --capture_output that would give us more information?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `mac toreview`
<details><summary>Output/Log</summary>

```

[12:30:54]: You require a gem, if this is a third party gem, please use `fastlane_require 'dotenv'` to ensure the gem is installed locally
[12:30:54]: Passed paths:
[12:30:54]: ------------------------------
[12:30:54]: --- Step: default_platform ---
[12:30:54]: ------------------------------
[12:30:54]: Driving the lane 'mac toreview' 🚀
[12:30:54]: --------------------
[12:30:54]: --- Step: prompt ---
[12:30:54]: --------------------
[12:30:54]: Set the price: 
[12:30:54]: ---------------------
[12:30:54]: --- Step: deliver ---
[12:30:54]: ---------------------
[12:30:55]: Login to iTunes Connect (masteranza@gmail.com)
[12:31:00]: Login successful

+--------------------------------------+------------------------------------+
|                           deliver 2.6.0 Summary                           |
+--------------------------------------+------------------------------------+
| platform                             | osx                                |
| price_tier                           | 0                                  |
| team_name                            | xxx                    |
| username                             | xxx@gmail.com               |
| app_identifier                       | xxx |
| force                                | true                               |
| submit_for_review                    | true                               |
| skip_binary_upload                   | true                               |
| automatic_release                    | true                               |
| app_review_information.first_name    | xxx                             |
| app_review_information.last_name     | xxx                           |
| app_review_information.phone_number  | xxxx                      |
| app_review_information.email_address | xxxx               |
| metadata_path                        | xxxx      |
| screenshots_path                     | xxxx   |
| overwrite_screenshots                | true                               |
| edit_live                            | false                              |
| skip_screenshots                     | false                              |
| skip_metadata                        | false                              |
+--------------------------------------+------------------------------------+

[12:31:01]: Loading './xxx/keywords.txt'...
[12:31:03]: Activating language en-US...
[12:31:08]: Uploading metadata to iTunes Connect
[12:31:11]: Successfully uploaded set of metadata to iTunes Connect
[12:31:12]: Starting with the upload of screenshots...
[12:31:12]: Removing all previously uploaded screenshots...
[12:31:12]: Activating language en-US...
[12:31:16]: Uploading 3 screenshots for language en-US
[12:31:16]: Uploading './xxx/OSX_mac_1280_800_gameplay.png'...
[12:31:24]: Saving changes
[12:31:26]: Successfully uploaded screenshots to iTunes Connect
[12:31:32]: Successfully updated the pricing from 2 to 0
[12:31:36]: Finished the upload to iTunes Connect
[12:31:37]: Selecting the latest build...
[12:31:39]: Selecting build 1.2.1 (20)...
[12:31:41]: Successfully selected build
[12:31:41]: Submitting the app for review...
[12:31:46]: Successfully submitted the app for review!

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | default_platform | 0           |
| 2    | prompt           | 0           |
| 3    | deliver          | 51          |
+------+------------------+-------------+

[12:31:46]: fastlane.tools finished successfully 🎉


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
require 'dotenv'
Dotenv.load
import "../MasterFastfile"
```
</details>

<details><summary>`./Appfile`</summary>

```ruby

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.6.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.0        |
| bigdecimal                | 1.2.8        |
| psych                     | 2.0.17       |
</details>

*generated on:* **2017-01-09**
</details>

**Comment by hjanuschka** [comment]
this stuff usually happens if there is some missing `submission_information`  or some invalid value.

check that you have the following things set on `deliver`


````
app_review_information: {
  first_name: 'Helmut',
  last_name: 'Januschka',
  phone_number: '+43 xxxxx',
  email_address: 'helmut@xxx.com',
  demo_user: 'trottendes.xxx',
  demo_password: 'xxx',
  notes: 'app should be usable even with no user'
},
submission_information: {
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: true,
      add_id_info_tracks_install: true,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: true,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    }
```


if errors continue - go to iTC manually - and try to hit "submit for review"  it should mark and show what field has errors.


let me know if this helps-.

**Comment by masteranza** [comment]
Worked great! I just deleted the line `export_compliance_platform: 'ios',` cause it's mac.
