### ISSUE TITLE
frameit: Mac framing fails

### ISSUE THREAD

**Issue by psamhaber** [fastlane/fastlane#7782]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I can't seem to get frameit to frame my osx app screens. I have a folder which includes:
- A macbook_bg.jpg which has a macbook frame on a white background
- Macbook screenshots (retina pngs, 2304x1440px)
- a framefile.json with the following:
```
 {
  "default": {
    "background": "macbook_bg.jpg",
    "offset": {
      "offset": "+1115+595"
    }
  }
}
```  
Running `fastlane frameit` in the folder results in the following:

```
 [15:25:06]: Using device frames version 'latest'
[15:25:06]: Framing screenshot './home-01.png'
[15:25:06]: Couldn't find template for screenshot type 'Apple MacBook Space Gray'
[15:25:06]: Please run `fastlane frameit download_frames` to download the latest frames
```    
Downloading new frames will result in the same error when I try it again.
- Is the Mac framing and framefile detection not supposed to work with a standalone`fastlane frameit` command?
- How does the offset specification work? My screens are retina resolution. Will they get placed at 1/2x the resolution automatically? Do I need to upsize the background?

Thanks guys!
   
### fastlane env:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C48b)                   |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.6.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-09**
</details>

**Comment by mfurtak** [comment]
Hi @psamhaber - thanks for the report 👍 

I've reproduced your problem, and I think I have a fix.

**Comment by mfurtak** [comment]
This should be fixed by #7790, which will go out in the next release 🎉

**Comment by KrauseFx** [comment]
I can't seem to get frameit to frame my osx app screens. I have a folder which includes:
- ✅ A macbook_bg.jpg which has a macbook frame on a white background 
- ✅Macbook screenshots (retina pngs, 2304x1440px)
- ✅ a framefile.json with the following:
```
 {
  "default": {
    "background": "macbook_bg.jpg",
    "offset": {
      "offset": "+1115+595"
    }
  }
}
```  

That all looks good, however when you run it, you need to tell _frameit_ to use macOS screenshots, as there is no way to _frameit_ to detect that automatically based on the size of the images.

Try running `fastlane frameit --force_device_type "Mac"`

However I'd like to note that _frameit_ was primarily designed for iOS apps, and the macOS support is very limited

**Comment by mfurtak** [comment]
Thanks for that explanation @KrauseFx 👍 

It's worth noting that the currently existing bug affects the proper handling of the `force_device_type` `"Mac"` value, so that will not work properly until the recent fix goes live :rocket:

**Comment by mfurtak** [comment]
@psamhaber I'll let you know here when that release is live.

**Comment by mfurtak** [comment]
This fix has shipped as part of [_fastlane_ 2.8.0](https://github.com/fastlane/fastlane/releases/tag/2.8.0) 🚀

**Comment by psamhaber** [comment]
@mfurtak @KrauseFx Thanks guys. 

Unfortunately this still doesn't seem to work for me.
- What screenshot sizes can be used with this? (I tried: 1280x800, 1440x900, 2880x800, )
- Do I also need to define their width in the framefile?

When running `fastlane frameit --force_device_type "Mac"` I get this:
`
INFO [2017-02-13 12:05:01.75]: Framing screenshot './main_screen.png'
DEBUG [2017-02-13 12:05:01.79]: Parsing config file '/Users/.../.../Framefile.json'
ERROR [2017-02-13 12:05:01.79]: undefined method `find' for nil:NilClass
ERROR [2017-02-13 12:05:01.79]: Backtrace:
	/Users/ps/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/config_parser.rb:27:in `fetch_value'
	/Users/ps/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/editor.rb:300:in `fetch_config'
	/Users/ps/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/editor.rb:73:in `offset'
	/Users/ps/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/mac_editor.rb:6:in `prepare_image'
	/Users/ps/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/editor.rb:10:in `frame!'
	/Users/ps/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/screenshot.rb:83:in `frame!'
	/Users/ps/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/runner.rb:34:in `block in run'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/runner.rb:24:in `each'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/runner.rb:24:in `run'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/commands_generator.rb:35:in `block (2 levels) in run'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/commands_generator.rb:89:in `run'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/frameit/lib/frameit/commands_generator.rb:12:in `start'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	/Users/philsamhaber/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/bin/fastlane:15:in `<top (required)>'
	/Users/philsamhaber/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	/Users/philsamhaber/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
`
I know what I'm doing is probably not at all the intended use for fastlane (I'm just framing things...) but since it works so well for ios screens, getting this to work with mac screens would be absolutely awesome! Any pointers much appreciated.
cheers

**Comment by psamhaber** [comment]
@mfurtak Can you reproduce the above error? If it does work for you it would be super nice if you can share the framefile.json and or actual image sizes...

**Comment by mfurtak** [comment]
@psamhaber Apologies - I know I've left you hanging here, but I haven't had time to try to reproduce yet.
