### ISSUE TITLE
Trying to use different bundle id

### ISSUE THREAD

**Issue by Yourney** [fastlane/fastlane#7783]
Hi,

Just installed the latest Fastlane.
First time I (try to) use sigh, so I might be doing something clumsy ;-)

I need to sign an IPA. The IPA has a bundle ID, but I need to change it.
I have the mobileprovisioning file with the correct bundle id sitting beside the app. (same dir)

When I look in the doc on github, I see:
```
fastlane sigh -a com.krausefx.app -u username
```

So I might be able to change the bundle id using the -a argument.
However, when I type:
```
fastlane sigh resign -a com.newDomain.app
```

I get:
```
No provisioning profile for nested application:
./floatsignTemp/Payload/Jabber.app/PlugIns/CallIntent.appex' with bundle identifier 'com.OldDomain.app'
Use the -p option (example: -p com.example.app=xxxx.mobileprovision)
```

So I tried:
```
fastlane sigh resign -a com.newDomain.app -p mb.mobileprovision=com.newDomain.app
```
with the same result.

When there is only one mobileprofisioning file in the dir, perhaps the script can get the bundle id from the script and ask the user if that is the proper id?

Thanks!
Wouter

**Comment by KrauseFx** [comment]
`-a` only works for `sigh` itself, not for resigning. I'm not sure how you can solve that for `resign`

**Comment by Yourney** [comment]
Somewhere we should call:
/usr/libexec/PlistBuddy -c "Set:CFBundleIdentifier $BUNDLE" "extracted/Payload/$APPLICATION/Info.plist"
after the API is unzipped ...

**Comment by joshdholtz** [comment]
@Yourney I _believe_ `fastlane sigh resign` is only meant to resign an IPA with a new provisioning profile with the **same** bundle id. "resigning" is only a subset of the tasks in the whole process of "changing bundle identifier" in an IPA.

I've recently went through this process for a project and changing a bundle identifier can get really complex if an app has a watch app or any other extensions included in it. There can be one to many bundle identifiers in `Info.plist`s that would need to get changed and get resigned. Something like this should be a different action completely, in my opinion 😊  I don't think anything like this exists yet as an action so if you want to make it that would be great 👌

**Comment by hjanuschka** [comment]
@Yourney  you should not change the bundle id of a already signed - resign is just for replacing provision profiles.


we have a setup where we publish ipa's to a testing company. to build an ipa for them we do it like this:


```ruby
lane :testbirds do
  before_build
  update_app_identifier(
    app_identifier: 'com.testbirds.app4442',
    plist_path: 'FiveXFive/Supporting Files/fivexfive-Info.plist'
  )
  update_info_plist(
    plist_path: 'FiveXFive/Supporting Files/fivexfive-Info.plist',
    display_name: 'Willi-Bird'
  )
  gym(scheme: $self_scheme,
      clean: false,
      workspace: $self_workspace,
      silent: true,
      buildlog_path: 'fastlane/logs',
      output_name: 'testbirds.ipa',
      use_legacy_build_api: true,
      provisioning_profile_path: 'testbirds.mobileprovision',
      codesigning_identity: 'iPhone Distribution: Testbirds GmbH')
end

```

Changing Display-Name, bundleId.

using their provided Certs/Prov.Profs.

for sure if you use app-extensions, like todayview, watch and so on, you would require to change those bundle-id's too.

**Comment by Yourney** [comment]
@hjanuschka I believe we do have to change the bundle id.
We receive an IPA with Watch app and a plugin (both signed) with the bundle id that the developer used for testing. We need the app (and Watch app) in our IPA with our own bundle id.
Therefore, we need to resign the Watch app and plugin with the proper bundle-id and the proper mobileprovisioning profile. And then package the App with the Watch app and plugin and Sign that.

Thanks for the script-snippet. I will look into that.
I am not a scripting hero, I am happy to be able call the fast lane resign command ;-)

Regards,
Wouter

**Comment by hjanuschka** [comment]
@Yourney yeah in that case, your proposed solution seems atleast worth a try. unzipping it - editing plist files - and then after bundle id's have changed,zip it again, name it .ipa 👍  and  run resign.

for extensions its like:
(in fastfile, not sure on how to pass it on commandline to sigh)

```
resign(
  ipa: "path/to/ipa", # can omit if using the `ipa` action
  signing_identity: "iPhone Distribution: Luka Mirosevic (0123456789)",
  provisioning_profile: {
    "com.example.awesome-app" => "path/to/profile",
    "com.example.awesome-app.app-extension" => "path/to/app-extension/profile"
  }
)
```

as seen in docs: https://docs.fastlane.tools/actions/#resign

**Comment by Yourney** [comment]
@hjanuschka Yeah, I'd like to do that, but how do I resign the individual Watch extension and Plugin?

It seems like there can be some sort of recursive element in a script running through all extensions and signing them individually before signing the whole IPA.

Wouter

**Comment by hjanuschka** [comment]
in the prev. comment you specify the variious bundle id's with the matching prov.prof.

**Comment by Yourney** [comment]
I see an example:

resign(
  ipa: "path/to/ipa", # can omit if using the `ipa` action
  signing_identity: "iPhone Distribution: Luka Mirosevic (0123456789)",
  provisioning_profile: {
    "com.example.awesome-app" => "path/to/profile",
    "com.example.awesome-app.app-extension" => "path/to/app-extension/profile"
  }
)

I will see if I can create the proper command for my app ;-)

Thanks for pointing me to te docs!
Wouter

**Comment by Yourney** [comment]
Perhaps a *stupid* question, but how do I call the above command? It is not a bash command for the Terminal.
Should I make some sort of script?

**Comment by hjanuschka** [comment]
put it in a file `fastlane/Fastfile`  


```ruby

lane :do_resign do
resign(
  ipa: "path/to/ipa", # can omit if using the `ipa` action
  signing_identity: "iPhone Distribution: Luka Mirosevic (0123456789)",
  provisioning_profile: {
    "com.example.awesome-app" => "path/to/profile",
    "com.example.awesome-app.app-extension" => "path/to/app-extension/profile"
  }
)
end

```

and run it with `fastlane do_resign`

**Comment by Yourney** [comment]
Yeah! That is perfect!
The command is executed!

Now I must fix some errors I get about entitlements. and conflicting mobileprovisioning files :-(

Thanks for your help guys!!!

Wouter

**Comment by Yourney** [comment]
Can I specify an entitlements file in that command?

Regards,
Wouter

**Comment by hjanuschka** [comment]
there are those 2 options: `entitlements`  and `use_app_entitlements` 
not sure how to use.


you could run `fastlane action resign` to get a help output

**Comment by mfurtak** [comment]
Thanks for the solid advice, @hjanuschka! 👍
