### ISSUE TITLE
Hockey notes show in same line

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7785]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When setting the `notes` option in `hockey` action,  the notes are showing in the same line on Hockey. While when I get the change logs locally from terminal they show in separate lines.

**My lane:**

```
lane :default_changelog do
  changelog = changelog_from_git_commits(
    between: [ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || "HEAD^^^^^", "HEAD"],
    pretty: "• %s",
    merge_commit_filtering: 'only_include_merges'
    )
  changelog = changelog.sub(/[\u{1F300}-\u{1F6FF}]/, '')
  Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
  changelog
end

lane deploy_app_hockey
    change_log = default_changelog
    hockey(
      api_token: hockey_api_token,
      notes: change_log,
      notify: "0"
      )
    commit_push_to_git
end
```

**My Output in Terminal:**
• Merge branch 'develop' into xxxxx
• Merge branch 'develop' into xxxxx
• Merge branch 'develop' into xxxxx

**Comment by joshdholtz** [comment]
@RishabhTayal So I did a test for this and its totally a single quote vs double quote issue (see example below). I don't know _exactly_ how to fix the your issue without playing more with how you are creating your changelog but the `hockey` action does do multiple lines in the notes if using `\n` in a double quoted string 😊 

```rb
hockey(
  notes: 'line1\nline2\nline3\n' # This won't add new lines
)

hockey(
  notes: "line1\nline2\nline3\n" # This will add new lines
)
```

**Comment by RishabhTayal** [comment]
Updated the description to reflect how the notes are added to `hockey` action.

If I add `\n` to `pretty: "• %s",` end of line, should it work?

**Comment by joshdholtz** [comment]
@RishabhTayal Ideally 😇  Give it a shot! If it doesn't, I can try your exact setup in an hour or two

**Comment by RishabhTayal** [comment]
That's strange. I will test with adding `\n`.

**Comment by joshdholtz** [comment]
@RishabhTayal It actually worked for me without adding `\n`

**Comment by joshdholtz** [comment]
```
	lane :default_changelog do
	  changelog = changelog_from_git_commits(
			commits_count: 2,
	    # between: ["HEAD~2", "HEAD"],
	    pretty: "• %s"
	    # merge_commit_filtering: 'only_include_merges'
	    )
	  changelog = changelog.sub(/[\u{1F300}-\u{1F6FF}]/, '')
	  Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
	  changelog
	end
	
	lane :beta do
		change_log = default_changelog
		hockey(
			notes: change_log,
			notify: "0"
		)
	end
```

**Comment by RishabhTayal** [comment]
I am not sure what's wrong here. Do you think it's `merge_commit_filtering` option? It was working for me until I added that option to the action.

**Comment by joshdholtz** [comment]
@RishabhTayal That _could_ be the issue. If you comment that out, does it work for you?

**Comment by RishabhTayal** [comment]
Just tried it. It  doesn't work 

![screenshot 2017-01-09 12 43 57](https://cloud.githubusercontent.com/assets/2100166/21778540/6801fe7e-d669-11e6-8565-eaca67261390.png)

**Comment by joshdholtz** [comment]
@RishabhTayal I uncommented mine out and it still worked for me... Can you paste your `fastlane env` output in here for me?

**Comment by RishabhTayal** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rvm/gems/ruby-2.2.1/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.2.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

platform :ios do
  
def deploy_app_hockey(scheme_name, xcodeproj_path, hockey_api_token)
    increment_build_number(
      xcodeproj: xcodeproj_path
      )
    gym_internal(scheme_name)
    change_log = default_changelog
    hockey(
      api_token: hockey_api_token,
      notes: change_log,
      notify: "0"
      )
    commit_push_to_git
  end

lane :default_changelog do
  changelog = changelog_from_git_commits(
    between: [ENV['GIT_PREVIOUS_SUCCESSFUL_COMMIT'] || "HEAD^^^^^", "HEAD"],
    pretty: "• %s\n",
    merge_commit_filtering: 'only_include_merges'
    )
  changelog = changelog.sub(/[\u{1F300}-\u{1F6FF}]/, '')
  Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog
  changelog
end

end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.6.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.13.6  |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| terminal-table            | 1.7.3   |
| plist                     | 3.2.0   |
| addressable               | 2.5.0   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| excon                     | 0.54.0  |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 2.0.1   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.12.1  |
| logging                   | 2.1.0   |
| jwt                       | 1.5.6   |
| memoist                   | 0.15.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| httpclient                | 2.8.3   |
| google-api-client         | 0.9.20  |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| json                      | 2.0.2   |
| commander                 | 4.4.2   |
| rubyzip                   | 1.2.0   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| unicode-display_width     | 1.1.2   |
</details>


*generated on:* **2017-01-09**
</details>

**Comment by joshdholtz** [comment]
@RishabhTayal I installed `2.2.1` on my machine and it still worked for me 😕  The only other thing different that I can see is that I have a git version of `2.10` but I don't know if that is the case.

Can you try harcoding notes to this and see if it works for you? `notes: "line1\nline2\nline3"`? Thanks!

**Comment by RishabhTayal** [comment]
@joshdholtz  I just changed the `•` to a `-` and it worked. Now the notes are shown in separate lines on Hockey. I am still not sure why `•` would be causing the line break to break.

**Comment by joshdholtz** [comment]
@RishabhTayal That is **super** strange but glad you figured it out 🙌
