### ISSUE TITLE
Spacechip - uninitialized constant Spaceship::Client::FastlaneCore

### ISSUE THREAD

**Issue by igorstimoli** [fastlane/fastlane#7787]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have a little ruby script that starts with

```ruby
#!/usr/bin/env ruby
require "spaceship"

itunes_username = ARGV[0]
itunes_password = ARGV[1]
app_identifier = ARGV[2]

client = Spaceship::Tunes.login(itunes_username, itunes_password)
```
since I updated to fastlane 2.6.0 It breaks at login with the following error
```
NameError: uninitialized constant Spaceship::Client::FastlaneCore
```

##### Complete output when running fastlane, including the stack trace and command used

```
NameError: uninitialized constant Spaceship::Client::FastlaneCore
Did you mean?  Fastlane
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/client.rb:175:in `persistent_cookie_path'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/two_step_client.rb:81:in `load_session_from_file'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/client.rb:264:in `send_shared_login_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/tunes/tunes_client.rb:164:in `send_login_request'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/client.rb:437:in `do_login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/client.rb:246:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/client.rb:93:in `login'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.6.0/spaceship/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from (irb):2
	from /usr/local/bin/irb:11:in `<main>'
```
### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.6.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-01-09**
</details>

**Comment by KrauseFx** [comment]
Hey @igorstimoli, thanks for bringing this up. It's actually a bug, for now please add `require 'fastlane'` after your spaceship require until we shipped a fix 👍

**Comment by igorstimoli** [comment]
@KrauseFx
Thanks for the fast fix!

**Comment by KrauseFx** [comment]
Yeah, does it work for you now? 👍

**Comment by igorstimoli** [comment]
@KrauseFx 
Yes, it does!
