### ISSUE TITLE
register one device from cli

### ISSUE THREAD

**Issue by pvinis** [fastlane/fastlane#7797]
i saw there is the `register_devices` and it takes a file or a dict. is there an easy way to add one device using the cli? like `fastlane run register_device name:"bla's iphone" udid:"123"`?

**Comment by KrauseFx** [comment]
Sorry, currently no, however I could see that being very useful. If you feel like it, feel free to update [register_devices.rb](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/register_devices.rb) to access those parameters, I'm sure many people would love that feature 👍

**Comment by pvinis** [comment]
alright. should i make it into a different action? `register_device`? otherwise we might have weird cases if you have a name and udid plus a devices file etc.

**Comment by KrauseFx** [comment]
Yeah, that sounds like a great idea. And the `register_devices` action could call the `register_device` action 👍 
Let me know if you need any help. Thanks for contributing to _fastlane_ ❤️

**Comment by pvinis** [comment]
i made a pr but i didnt make `register_devices` call `register_device`, fistly because i dont know, and secondly because then it has to check all the time for credentials, and i dont know if that will be too slow.. what do you think?

**Comment by asfalcone** [comment]
The PR was merged so I'm going to close out this issue 🎉
