### ISSUE TITLE
What If I have more than one Target ? For Snapshot I have added all targets under LANE: command on Fastfile. How can I implement GYM for multiple targets.

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#7798]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by mfurtak** [comment]
Please follow the issue template when creating an issue, so that we can have all the information needed to help with your question 👍 

Feel free to edit the body of this issue, and then we can take another look :smile:
