### ISSUE TITLE
Gym hangs after successful archive creation

### ISSUE THREAD

**Issue by ssnielsen** [fastlane/fastlane#7802]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
``gym`` finishes making the archive (at least ``Archive Suceeded`` is printed) but unfortunately hangs when on the following command which is:
```
 /usr/bin/xcrun /Users/soren/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.7.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_config20170110-7232-zqpto9.plist' -archivePath /Users/soren/Library/Developer/Xcode/Archives/2017-01-10/ReSwiftTest\ 2017-01-10\ 14.35.20.xcarchive -exportPath '/var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_output20170110-7232-jmxied' 
```

Command printed from ``--verbose``:
```
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
|                                                                                                            Generated Package Command                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| Option                                                                                                                                                 | Value                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| /usr/bin/xcrun /Users/soren/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.7.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive |                                                                                        |
| -exportOptionsPlist                                                                                                                                    | /var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_config20170110-8045-1sx61rw.plist |
| -archivePath /Users/soren/Library/Developer/Xcode/Archives/2017-01-10/ReSwiftTest\ 2017-01-10\ 14.41.34.xcarchive                                      |                                                                                        |
| -exportPath                                                                                                                                            | /var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_output20170110-8045-j5pel4        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
```

I've found and tried various stuff mentioned in issues that describes the same experience (e.g. manually rebuilding schemes as described in https://github.com/fastlane-old/gym/issues/143#issuecomment-158388533)

Any thoughts?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

<details><summary>OUTPUT</summary>
soren@Srens-MacBook-Pro ~/e/ReSwiftTest> fastlane gym --verbose
INFO [2017-01-10 14:41:32.63]: Successfully loaded '/Users/soren/econ-source/ReSwiftTest/fastlane/Gymfile' 📄

+---------------------+---------------------+
| Detected Values from './fastlane/Gymfile' |
+---------------------+---------------------+
| scheme              | ReSwiftTest         |
| output_directory    | ./build             |
+---------------------+---------------------+

INFO [2017-01-10 14:41:32.64]: Successfully loaded '/Users/soren/econ-source/ReSwiftTest/fastlane/Gymfile' 📄
WARN [2017-01-10 14:41:32.64]: No values defined in './fastlane/Gymfile'
INFO [2017-01-10 14:41:32.73]: $ xcodebuild -list -workspace ./ReSwiftTest.xcworkspace
INFO [2017-01-10 14:41:33.37]: $ xcodebuild clean -showBuildSettings -workspace ./ReSwiftTest.xcworkspace -scheme ReSwiftTest

+----------------------+---------------------------+
|              Summary for gym 2.7.0               |
+----------------------+---------------------------+
| scheme               | ReSwiftTest               |
| output_directory     | ./build                   |
| workspace            | ./ReSwiftTest.xcworkspace |
| destination          | generic/platform=iOS      |
| output_name          | ReSwiftTest               |
| clean                | false                     |
| silent               | false                     |
| use_legacy_build_api | false                     |
| buildlog_path        | ~/Library/Logs/gym        |
| xcode_path           | /Applications/Xcode.app   |
+----------------------+---------------------------+

+-------------------------------------------------------------------------------------------------------------------+----------------------+
|                                                         Generated Build Command                                                          |
+-------------------------------------------------------------------------------------------------------------------+----------------------+
| Option                                                                                                            | Value                |
+-------------------------------------------------------------------------------------------------------------------+----------------------+
| set -o pipefail &&                                                                                                |                      |
| xcodebuild                                                                                                        |                      |
| -workspace ./ReSwiftTest.xcworkspace                                                                              |                      |
| -scheme ReSwiftTest                                                                                               |                      |
| -destination                                                                                                      | generic/platform=iOS |
| -archivePath /Users/soren/Library/Developer/Xcode/Archives/2017-01-10/ReSwiftTest\ 2017-01-10\ 14.41.34.xcarchive |                      |
| archive                                                                                                           |                      |
| | tee /Users/soren/Library/Logs/gym/ReSwiftTest-ReSwiftTest.log                                                   |                      |
| | xcpretty                                                                                                        |                      |
+-------------------------------------------------------------------------------------------------------------------+----------------------+
INFO [2017-01-10 14:41:34.06]: $ set -o pipefail && xcodebuild -workspace ./ReSwiftTest.xcworkspace -scheme ReSwiftTest -destination 'generic/platform=iOS' -archivePath /Users/soren/Library/Developer/Xcode/Archives/2017-01-10/ReSwiftTest\ 2017-01-10\ 14.41.34.xcarchive archive | tee /Users/soren/Library/Logs/gym/ReSwiftTest-ReSwiftTest.log | xcpretty
INFO [2017-01-10 14:41:34.83]: ▸ Building Pods/ReSwift [Release]
INFO [2017-01-10 14:41:34.83]: ▸ Check Dependencies
INFO [2017-01-10 14:41:34.94]: ▸ Processing Info.plist
INFO [2017-01-10 14:41:34.97]: ▸ Compiling Action.swift
INFO [2017-01-10 14:41:35.60]: ▸ Compiling Assertions.swift
INFO [2017-01-10 14:41:35.60]: ▸ Compiling Coding.swift
INFO [2017-01-10 14:41:35.60]: ▸ Compiling CombinedReducer.swift
INFO [2017-01-10 14:41:35.60]: ▸ Compiling Middleware.swift
INFO [2017-01-10 14:41:35.60]: ▸ Compiling Reducer.swift
INFO [2017-01-10 14:41:35.60]: ▸ Compiling State.swift
INFO [2017-01-10 14:41:35.61]: ▸ Compiling Store.swift
INFO [2017-01-10 14:41:35.72]: ▸ Compiling StoreSubscriber.swift
INFO [2017-01-10 14:41:35.72]: ▸ Compiling StoreType.swift
INFO [2017-01-10 14:41:35.72]: ▸ Compiling Subscription.swift
INFO [2017-01-10 14:41:35.72]: ▸ Compiling TypeHelper.swift
INFO [2017-01-10 14:41:35.91]: ▸ Compiling Action.swift
INFO [2017-01-10 14:41:36.55]: ▸ Compiling Assertions.swift
INFO [2017-01-10 14:41:36.55]: ▸ Compiling Coding.swift
INFO [2017-01-10 14:41:36.55]: ▸ Compiling CombinedReducer.swift
INFO [2017-01-10 14:41:36.55]: ▸ Compiling Middleware.swift
INFO [2017-01-10 14:41:36.55]: ▸ Compiling Reducer.swift
INFO [2017-01-10 14:41:36.55]: ▸ Compiling State.swift
INFO [2017-01-10 14:41:36.56]: ▸ Compiling Store.swift
INFO [2017-01-10 14:41:36.66]: ▸ Compiling StoreSubscriber.swift
INFO [2017-01-10 14:41:36.66]: ▸ Compiling StoreType.swift
INFO [2017-01-10 14:41:36.66]: ▸ Compiling Subscription.swift
INFO [2017-01-10 14:41:36.66]: ▸ Compiling TypeHelper.swift
INFO [2017-01-10 14:41:40.97]: ▸ Compiling ReSwift_vers.c
INFO [2017-01-10 14:41:41.00]: ▸ Compiling ReSwift-dummy.m
INFO [2017-01-10 14:41:41.07]: ▸ Compiling ReSwift-dummy.m
INFO [2017-01-10 14:41:41.07]: ▸ Compiling ReSwift_vers.c
INFO [2017-01-10 14:41:41.08]: ▸ Linking ReSwift
INFO [2017-01-10 14:41:41.41]: ▸ Linking ReSwift
INFO [2017-01-10 14:41:41.43]: ▸ Generating 'ReSwift.framework.dSYM'
INFO [2017-01-10 14:41:41.48]: ▸ Copying ReSwift-umbrella.h
INFO [2017-01-10 14:41:41.48]: ▸ Touching ReSwift.framework
INFO [2017-01-10 14:41:41.51]: ▸ Building Pods/R.swift.Library [Release]
INFO [2017-01-10 14:41:41.51]: ▸ Check Dependencies
INFO [2017-01-10 14:41:41.51]: ▸ Processing Info.plist
INFO [2017-01-10 14:41:41.51]: ▸ Compiling Bundle+FileResource.swift
INFO [2017-01-10 14:41:41.52]: ▸ Compiling ColorResource+UIKit.swift
INFO [2017-01-10 14:41:41.52]: ▸ Compiling ColorResource.swift
INFO [2017-01-10 14:41:41.52]: ▸ Compiling Core+Migration.swift
INFO [2017-01-10 14:41:41.52]: ▸ Compiling Data+FileResource.swift
INFO [2017-01-10 14:41:41.53]: ▸ Compiling FileResource.swift
INFO [2017-01-10 14:41:41.53]: ▸ Compiling FontResource.swift
INFO [2017-01-10 14:41:41.53]: ▸ Compiling Foundation+Migration.swift
INFO [2017-01-10 14:41:41.53]: ▸ Compiling Identifier.swift
INFO [2017-01-10 14:41:41.54]: ▸ Compiling ImageResource.swift
INFO [2017-01-10 14:41:41.54]: ▸ Compiling NibResource+UIKit.swift
INFO [2017-01-10 14:41:41.54]: ▸ Compiling NibResource.swift
INFO [2017-01-10 14:41:41.54]: ▸ Compiling ReuseIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.54]: ▸ Compiling StoryboardResource.swift
INFO [2017-01-10 14:41:41.55]: ▸ Compiling StoryboardResourceWithInitialController+UIKit.swift
INFO [2017-01-10 14:41:41.55]: ▸ Compiling StoryboardSegueIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.55]: ▸ Compiling StoryboardViewControllerResource.swift
INFO [2017-01-10 14:41:41.55]: ▸ Compiling StringResource.swift
INFO [2017-01-10 14:41:41.56]: ▸ Compiling TypedStoryboardSegueInfo+UIStoryboardSegue.swift
INFO [2017-01-10 14:41:41.56]: ▸ Compiling UICollectionView+ReuseIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.56]: ▸ Compiling UIFont+FontResource.swift
INFO [2017-01-10 14:41:41.56]: ▸ Compiling UIImage+ImageResource.swift
INFO [2017-01-10 14:41:41.57]: ▸ Compiling UIKit+Migration.swift
INFO [2017-01-10 14:41:41.57]: ▸ Compiling UINib+NibResource.swift
INFO [2017-01-10 14:41:41.57]: ▸ Compiling UIStoryboard+StoryboardResource.swift
INFO [2017-01-10 14:41:41.57]: ▸ Compiling UIStoryboard+StoryboardViewControllerResource.swift
INFO [2017-01-10 14:41:41.57]: ▸ Compiling UITableView+ReuseIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.58]: ▸ Compiling UIViewController+NibResource.swift
INFO [2017-01-10 14:41:41.58]: ▸ Compiling UIViewController+StoryboardSegueIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.58]: ▸ Compiling Validatable.swift
INFO [2017-01-10 14:41:41.60]: ▸ Compiling Bundle+FileResource.swift
INFO [2017-01-10 14:41:41.61]: ▸ Compiling ColorResource+UIKit.swift
INFO [2017-01-10 14:41:41.61]: ▸ Compiling ColorResource.swift
INFO [2017-01-10 14:41:41.61]: ▸ Compiling Core+Migration.swift
INFO [2017-01-10 14:41:41.62]: ▸ Compiling Data+FileResource.swift
INFO [2017-01-10 14:41:41.62]: ▸ Compiling FileResource.swift
INFO [2017-01-10 14:41:41.62]: ▸ Compiling FontResource.swift
INFO [2017-01-10 14:41:41.62]: ▸ Compiling Foundation+Migration.swift
INFO [2017-01-10 14:41:41.63]: ▸ Compiling Identifier.swift
INFO [2017-01-10 14:41:41.63]: ▸ Compiling ImageResource.swift
INFO [2017-01-10 14:41:41.63]: ▸ Compiling NibResource+UIKit.swift
INFO [2017-01-10 14:41:41.64]: ▸ Compiling NibResource.swift
INFO [2017-01-10 14:41:41.64]: ▸ Compiling ReuseIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.64]: ▸ Compiling StoryboardResource.swift
INFO [2017-01-10 14:41:41.64]: ▸ Compiling StoryboardResourceWithInitialController+UIKit.swift
INFO [2017-01-10 14:41:41.65]: ▸ Compiling StoryboardSegueIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.65]: ▸ Compiling StoryboardViewControllerResource.swift
INFO [2017-01-10 14:41:41.65]: ▸ Compiling StringResource.swift
INFO [2017-01-10 14:41:41.65]: ▸ Compiling TypedStoryboardSegueInfo+UIStoryboardSegue.swift
INFO [2017-01-10 14:41:41.66]: ▸ Compiling UICollectionView+ReuseIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.66]: ▸ Compiling UIFont+FontResource.swift
INFO [2017-01-10 14:41:41.66]: ▸ Compiling UIImage+ImageResource.swift
INFO [2017-01-10 14:41:41.66]: ▸ Compiling UIKit+Migration.swift
INFO [2017-01-10 14:41:41.67]: ▸ Compiling UINib+NibResource.swift
INFO [2017-01-10 14:41:41.67]: ▸ Compiling UIStoryboard+StoryboardResource.swift
INFO [2017-01-10 14:41:41.67]: ▸ Compiling UIStoryboard+StoryboardViewControllerResource.swift
INFO [2017-01-10 14:41:41.68]: ▸ Compiling UITableView+ReuseIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.68]: ▸ Compiling UIViewController+NibResource.swift
INFO [2017-01-10 14:41:41.68]: ▸ Compiling UIViewController+StoryboardSegueIdentifierProtocol.swift
INFO [2017-01-10 14:41:41.68]: ▸ Compiling Validatable.swift
INFO [2017-01-10 14:41:41.71]: ▸ Compiling R.swift.Library-dummy.m
INFO [2017-01-10 14:41:41.71]: ▸ Compiling Rswift_vers.c
INFO [2017-01-10 14:41:41.72]: ▸ Compiling R.swift.Library-dummy.m
INFO [2017-01-10 14:41:41.72]: ▸ Compiling Rswift_vers.c
INFO [2017-01-10 14:41:41.72]: ▸ Linking Rswift
INFO [2017-01-10 14:41:41.73]: ▸ Linking Rswift
INFO [2017-01-10 14:41:41.73]: ▸ Generating 'Rswift.framework.dSYM'
INFO [2017-01-10 14:41:41.73]: ▸ Copying R.swift.Library-umbrella.h
INFO [2017-01-10 14:41:41.74]: ▸ Touching Rswift.framework
INFO [2017-01-10 14:41:41.74]: ▸ Building Pods/Pods-ReSwiftTest [Release]
INFO [2017-01-10 14:41:41.74]: ▸ Check Dependencies
INFO [2017-01-10 14:41:41.74]: ▸ Processing Info.plist
INFO [2017-01-10 14:41:41.74]: ▸ Compiling Pods-ReSwiftTest-dummy.m
INFO [2017-01-10 14:41:41.78]: ▸ Compiling Pods_ReSwiftTest_vers.c
INFO [2017-01-10 14:41:41.78]: ▸ Compiling Pods-ReSwiftTest-dummy.m
INFO [2017-01-10 14:41:41.78]: ▸ Compiling Pods_ReSwiftTest_vers.c
INFO [2017-01-10 14:41:41.80]: ▸ Copying Pods-ReSwiftTest-umbrella.h
INFO [2017-01-10 14:41:41.81]: ▸ Touching Pods_ReSwiftTest.framework
INFO [2017-01-10 14:41:41.84]: ▸ Building ReSwiftTest/ReSwiftTest [Release]
INFO [2017-01-10 14:41:41.84]: ▸ Check Dependencies
INFO [2017-01-10 14:41:41.86]: ▸ Running script '[CP] Check Pods Manifest.lock'
INFO [2017-01-10 14:41:41.90]: ▸ Running script 'R.swift'
INFO [2017-01-10 14:42:01.19]: ▸ Linking ReSwiftTest
INFO [2017-01-10 14:42:01.69]: ▸ Linking ReSwiftTest
INFO [2017-01-10 14:42:01.75]: ▸ Compiling Main.storyboard
INFO [2017-01-10 14:42:02.58]: ▸ Compiling LaunchScreen.storyboard
INFO [2017-01-10 14:42:02.59]: ▸ Compiling Customers.storyboard
INFO [2017-01-10 14:42:03.22]: ▸ Processing Info.plist
INFO [2017-01-10 14:42:03.22]: ▸ Generating 'ReSwiftTest.app.dSYM'
INFO [2017-01-10 14:42:03.30]: ▸ Running script '[CP] Embed Pods Frameworks'
INFO [2017-01-10 14:42:05.45]: ▸ Running script '[CP] Copy Pods Resources'
INFO [2017-01-10 14:42:05.50]: ▸ Touching ReSwiftTest.app
INFO [2017-01-10 14:42:11.36]: ▸ Signing /Users/soren/Library/Developer/Xcode/DerivedData/ReSwiftTest-elcskqbitkgvtpefwminkwbvhtwn/Build/Intermediates/ArchiveIntermediates/ReSwiftTest/InstallationBuildProductsLocation/Applications/ReSwiftTest.app
INFO [2017-01-10 14:42:12.82]: ▸ Touching ReSwiftTest.app.dSYM
INFO [2017-01-10 14:42:13.46]: ▸ Archive Succeeded
DEBUG [2017-01-10 14:42:13.62]: Stored the archive in: /Users/soren/Library/Developer/Xcode/Archives/2017-01-10/ReSwiftTest 2017-01-10 14.41.34.xcarchive
WARN [2017-01-10 14:42:13.62]: Generated plist file with the following values:
INFO [2017-01-10 14:42:13.62]: ▸ -----------------------------------------
INFO [2017-01-10 14:42:13.62]: ▸ {
INFO [2017-01-10 14:42:13.62]: ▸   "method": "app-store",
INFO [2017-01-10 14:42:13.62]: ▸   "uploadSymbols": true,
INFO [2017-01-10 14:42:13.62]: ▸   "uploadBitcode": false
INFO [2017-01-10 14:42:13.62]: ▸ }
INFO [2017-01-10 14:42:13.62]: ▸ -----------------------------------------
INFO [2017-01-10 14:42:13.62]: This results in the following plist file:
INFO [2017-01-10 14:42:13.62]: ▸ -----------------------------------------
INFO [2017-01-10 14:42:13.62]: ▸ <?xml version="1.0" encoding="UTF-8"?>
INFO [2017-01-10 14:42:13.62]: ▸ <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
INFO [2017-01-10 14:42:13.62]: ▸ <plist version="1.0">
INFO [2017-01-10 14:42:13.62]: ▸ <dict>
INFO [2017-01-10 14:42:13.62]: ▸ 	<key>method</key>
INFO [2017-01-10 14:42:13.62]: ▸ 	<string>app-store</string>
INFO [2017-01-10 14:42:13.62]: ▸ 	<key>uploadBitcode</key>
INFO [2017-01-10 14:42:13.62]: ▸ 	<false/>
INFO [2017-01-10 14:42:13.62]: ▸ 	<key>uploadSymbols</key>
INFO [2017-01-10 14:42:13.62]: ▸ 	<true/>
INFO [2017-01-10 14:42:13.62]: ▸ </dict>
INFO [2017-01-10 14:42:13.62]: ▸ </plist>
INFO [2017-01-10 14:42:13.62]: ▸ -----------------------------------------
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
|                                                                                                            Generated Package Command                                                                                                            |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| Option                                                                                                                                                 | Value                                                                                  |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| /usr/bin/xcrun /Users/soren/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.7.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive |                                                                                        |
| -exportOptionsPlist                                                                                                                                    | /var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_config20170110-8045-1sx61rw.plist |
| -archivePath /Users/soren/Library/Developer/Xcode/Archives/2017-01-10/ReSwiftTest\ 2017-01-10\ 14.41.34.xcarchive                                      |                                                                                        |
| -exportPath                                                                                                                                            | /var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_output20170110-8045-j5pel4        |
+--------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
INFO [2017-01-10 14:42:13.63]: $ /usr/bin/xcrun /Users/soren/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.7.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_config20170110-8045-1sx61rw.plist' -archivePath /Users/soren/Library/Developer/Xcode/Archives/2017-01-10/ReSwiftTest\ 2017-01-10\ 14.41.34.xcarchive -exportPath '/var/folders/dc/lx0z_6h15y98p5m83twdpq0r0000gp/T/gym_output20170110-8045-j5pel4' 
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.7.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "ReSwiftTest")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "ReSwiftTest") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "ReSwiftTest") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "X" # The bundle identifier of your app
apple_dev_portal_id "X" # Your Apple email address
itunes_connect_id "X"

team_id "XXXXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.1.1        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.5        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-10**
</details>

**Comment by KrauseFx** [comment]
Could you try running the same for a different project? I wonder if it's specific to the project or your machine 👍

**Comment by ssnielsen** [comment]
Hi @KrauseFx, thanks for the quick response.
I just tried running for another project - with the same outcome. I guess next thing is trying on a different machine.

**Comment by KrauseFx** [comment]
Yeah, that would be awesome. Unfortunately those kinds of issues are super hard to reproduce.

**Comment by haitaox** [comment]
Having the same issue. gym hangs forever at exportArchive after archive succeeded.

Tried reinstalling command line tools, xcode and upgrading ruby. none works.

**Comment by bod1ka** [comment]
Having the same issue , is there any working solution?

**Comment by ericlewis** [comment]
+1

**Comment by ericlewis** [comment]
I finally figured out the issue here, the xcrun command was needing me to unlock the RSA key again and wasn't displaying any indication of this. Properly ensuring it remains unlocked / decrypted resolves the problem.

**Comment by KrauseFx** [comment]
@EricKuck was that the popup that's rendered on the mac UI:?

**Comment by EricKuck** [comment]
Guessing that was supposed to be @ericlewis?

**Comment by ericlewis** [comment]
It wasn't rendering a popup which I found to be weird, it turns out when I would run the xcrun command it seemed to hang on in a different terminal tab that it would prompt me for unlocking rsa in the terminal command line itself again. Hanging there since fastlane didn't seem aware of it. I temporarily decrypted my keys to see if this was the case and it built fine after that.
