### ISSUE TITLE
[actions] cli output formatting for `fastlane action changelog_from_git_commits` 

### ISSUE THREAD

**Issue by jinjorge** [fastlane/fastlane#7811]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
It's difficult to read the output of `fastlane action changelog_from_git_commits`

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

![screen shot 2017-01-10 at 3 20 27 pm](https://cloud.githubusercontent.com/assets/2208083/21829125/3af6f6d8-d749-11e6-8aff-076008e565fb.png)

PR coming

**Comment by KrauseFx** [comment]
@hjanuschka just pointed out that we have a PR ready for this: https://github.com/fastlane/fastlane/pull/7391
