### ISSUE TITLE
Notification or Sound.

### ISSUE THREAD

**Issue by arasu01** [fastlane/fastlane#7813]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Moreover, this is not an issue, I'm using FastLane for exporting IPA file. The problem I run terminal command and I will start working on other tasks. So I will not know when the task is completed. So it is possible to play sound after completion of task or show notification.

This may be helpful when working with the simultaneous task.

**Comment by hjanuschka** [comment]
you could use the `notification` action - which fires a macOS notification (not sure if this has sounds tbh)


see docs:
https://docs.fastlane.tools/actions/#notification

**Comment by KrauseFx** [comment]
Ha, I really like that idea. Alternatively you can also use the following in your `Fastfile`

```ruby
  sh "say 'I am alive'"
```

**Comment by hjanuschka** [comment]
@KrauseFx 😆 how could i forgot `say` - may 3yr old always plays with it in the terminal

**Comment by KrauseFx** [comment]
Haha, yeah. Let's close this issue for now, let us know if you have any other questions 👍

**Comment by mfurtak** [comment]
How quickly we forget... 😉 

```
$ fastlane actions say

Loading documentation for say:

+--------------------------------------------+
|                    say                     |
+--------------------------------------------+
| This action speaks out loud the given text |
|                                            |
| Created by KrauseFx                        |
+--------------------------------------------+

No available options

More information can be found on https://docs.fastlane.tools/actions
```

**Comment by arasu01** [comment]
Thanks, guys. 

I was not using Fastfile, directly getting IPA using a terminal command. So I have missed this one.

**Comment by KrauseFx** [comment]
Ha, wow, so many options 👍

**Comment by KrauseFx** [comment]
That action has been around since the first release, ha 👍
