### ISSUE TITLE
Attaching obb files to new apk from prev apk

### ISSUE THREAD

**Issue by urmanchevandrey** [fastlane/fastlane#7816]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hi! How can I load apk to Developer Console and attach to this apk obb file, which was already loaded with previous apk? When I load apk with supply function, no obb file will be attached to apk, but it would be good if obb files will be attached to new apk from previous apk by default.
### Environment

GS Mobile Developers Account, [11.01.17 13:10]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.0                                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G31)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ru_RU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>./fastlane/Fastfile</summary>

ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the fastlane actions command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running fastlane

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.7.0"

default_platform :android

platform :android do
  before_all do
    ENV["CRASHLYTICS_API_TOKEN"] = "1d22b1c5af737ceefbc64d95eb5976ebc35eb72d"
    ENV["CRASHLYTICS_BUILD_SECRET"] = "f03d3a13592ee0018cc142b6285a858afac01da8a33127e17b84aba45f4fad7e"
  end

  desc "Deploy a new RC version to the Google Play"
  lane :rc do
    gradle(task: "clean")
    gradle(task: "assemble", flavor: ENV["flavor"], build_type: "Release")
    supply(track: "beta", apk: "/Users/ci/android/mapmobile/build/SscClient-MapMobile-release.apk",  skip_upload_metadata: true, skip_upload_images: true, skip_upload_screenshots: true)

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

</details>

GS Mobile Developers Account, [11.01.17 13:10]
<details><summary>./fastlane/Appfile</summary>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| faraday-cookie_jar        | 0.0.6   |
| gh_inspector              | 1.0.2   |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| multi_json                | 1.12.1  |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| json                      | 1.8.3   |
| commander                 | 4.4.3   |
| excon                     | 0.54.0  |
| rubyzip                   | 1.2.0   |
| plist                     | 3.2.0   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| bundler                   | 1.13.6  |
| terminal-table            | 1.7.3   |
| unicode-display_width     | 1.1.2   |
</details>

*generated on:* **2017-01-11**

GS Mobile Developers Account, [11.01.17 13:10]
</details>

**Comment by asfalcone** [comment]
@urmanchevandrey Thanks for the question. Does this behavior happen automatically in the developer console when you upload a new apk manually?

**Comment by urmanchevandrey** [comment]
After uploading apk to console you will see form with information about uploaded apk and two spinners with lists of previously loaded main and patch obbs, in these spinners selected those main and patch file, which were selected after previous apk loading. Then I just click on "Publish" button, and new apk will be available on Google Play.
