### ISSUE TITLE
ITMS-90150

### ISSUE THREAD

**Issue by bvirlet** [fastlane/fastlane#7818]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello,

I'm getting the following error when attempting to push a build to iTunesConnect with pilot since yesterday. I have since then updated fastlane to the latest version (2.7.0) but that didn't help. 

This is in fact an issue with iTunesConnect directly (I'm also getting the error message when trying to upload from Xcode), but I have not seen this error message anywhere.

Is this something that the folks Any pointers as to where to look for?

```
[05:35:03]: -------------------
[05:35:03]: --- Step: pilot ---
[05:35:03]: -------------------
[05:35:03]: Login to iTunes Connect 
[05:35:06]: Login successful
[05:35:07]: Ready to upload new build to TestFlight (App: XXXXXXX)...
[05:35:07]: Going to upload updated app to iTunes Connect
[05:35:07]: This might take a few minutes. Please don't interrupt the script.

[05:37:00]: Transporter transfer failed.
[05:37:00]: 

[05:37:00]: ERROR ITMS-90150: "Invalid Document Type Role: 'Default' is not a valid Role. Refer to the Information Property List Reference for more information."

Return status of iTunes Transporter was 1: ERROR ITMS-90150: "Invalid Document Type Role: 'Default' is not a valid Role. Refer to the Information Property List Reference for more information."

The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.`
```

**Comment by hjanuschka** [comment]
@bvirlet did you recently modify `Document Types` in `info.plist` ?
i think this is the doc. about it: https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/DocumentInteraction_TopicsForIOS/Articles/RegisteringtheFileTypesYourAppSupports.html maybe you are missing one of the keys.



let me know if this helps.

**Comment by bvirlet** [comment]
Brilliant!

The error message made me think it was any type of .plist config for the transporter, but it was just my app's .plist.

Thanks for your help! I'm closing this as this is totally unrelated to Fastlane.

**Comment by hjanuschka** [comment]
@bvirlet awesome, nice you got it working again,  THX for feedback
