### ISSUE TITLE
Codesigning fails after upgrade to fastlane 2.7.0 on Jenkins slave

### ISSUE THREAD

**Issue by stark525** [fastlane/fastlane#7821]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm having failures code signing after upgrading to Fastlane 2.7.0, with the latest OS and Xcode. I'm able to perform this action successfully on a different build slave that is running Fastlane 1.111.0. Same version of macOS (10.12.2) but different Xcode (8.1).

What is especially strange is if I try to run the codesign command manually on the command line it signs successfully (exit code 0).

I've verified match is correctly installing my certificate, automatic signing is not managed, keychain is unlocked, and my Provisioning Profile is the match profile I expect.  I'm at a loss, any advice would be appreciated.  Thanks! 

```
Code Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/App-ccxlejlrrpxnmydpcuyfzmkhlnlj/Build/Intermediates/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/Frameworks/Fmwk.framework with Identity iPhone Distribution: MyCorp, Inc. (Ent)
/usr/bin/codesign --force --sign 4F7E215A1C04D9B3883BDDAEA483A4C41D64CAF9  --preserve-metadata=identifier,entitlements '/Users/jenkins/Library/Developer/Xcode/DerivedData/App-ccxlejlrrpxnmydpcuyfzmkhlnlj/Build/Intermediates/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/Frameworks/Fmwk.framework'
SecKey API returned: -25308, (null)/Users/jenkins/Library/Developer/Xcode/DerivedData/App-ccxlejlrrpxnmydpcuyfzmkhlnlj/Build/Intermediates/ArchiveIntermediates/App/InstallationBuildProductsLocation/Applications/App.app/Frameworks/Fmwk.framework: unknown error -1=ffffffffffffffff
Command /bin/sh failed with exit code 1
```

Here is the gym command in my Fastfile that is failing on this slave but works on the other:
```
  gym(
    workspace: "#{pwd}/#{options[:scheme]}.xcworkspace",
    scheme: "#{options[:scheme]}",
    archive_path: "#{job_name}/Archive/Ent/#{options[:scheme]}.xcarchive",
    output_directory: "#{job_name}/Archive/Ent/",
    configuration: "Enterprise",
    codesigning_identity: "iPhone Distribution: MyCorp, Inc. (Ent)"
  )
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C68)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
import_from_git(url: "path/to/my/shared/Fastfile")

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| artifactory               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.0.beta.3 |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.2        |
| molinillo                 | 0.5.5        |
| ruby-macho                | 0.2.6        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.2.0.beta.3 |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| xcov                      | 0.12.5       |
</details>

*generated on:* **2017-01-11**
</details>

**Comment by PetrosIchor** [comment]
That 'fffffff' error code.  I ran into that once and can't remember how I solved it. 

My first guesses are the slave doesn't have the correct access to pull/decrypt match assets. Even though it appears it is working. 

Decryption requires the environment to use the same openssl version. (I think).  It's possible the task runs but is failing silently due to a versioning conflict. 

If you provide your fastlane, env, and full error output it'd be easier to help troubleshoot.

**Comment by stark525** [comment]
That's an interesting guess, I'll test it out today and report back.  Thanks @PetrosIchor!  Also, my environment config is posted (collapsed) in the original  post under ✅ fastlane environment ✅

**Comment by stark525** [comment]
I'm not sure what version of OpenSSL was used to encrypt the secrets originally and it's very possible it was old. 

I nuked the certs and upgraded to the same version (1.0.2j) before running match again. My old slave installed the new cert and continues to work. Unfortunately, I still see the same error on this slave. 😞 

Any other ideas of ways I can troubleshoot? 

Broken slave
```▸ Generating 'App.app.dSYM'
/Users/yogeshpatil/Library/Developer/Xcode/DerivedData/ModuleCache/1VQQ1H0GOWKMD/Darwin-1G5M3ABQ1XQI0.pcm: No such file or directory
/Users/yogeshpatil/Library/Developer/Xcode/DerivedData/ModuleCache/PPRFEMNZ4JKH/Darwin-1G5M3ABQ1XQI0.pcm: No such file or directory
▸ Running script '[CP] Embed Pods Frameworks'
** ARCHIVE FAILED **


The following build commands failed:
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/jenkins/Library/Developer/Xcode/DerivedData/App-ccxlejlrrpxnmydpcuyfzmkhlnlj/Build/Intermediates/ArchiveIntermediates/App/IntermediateBuildFilesPath/App.build/Enterprise-iphoneos/App.build/Script-E057FAE22FF11B7630EE390F.sh
(1 failure)
[16:22:41]: Exit status: 65
[16:22:41]: 📋  For a more detailed error log, check the full log at:
[16:22:41]: 📋  /Users/jenkins/Library/Logs/gym/App-App.log

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.7.0                   |
| sdk         | iPhoneOS10.2.sdk        |
+-------------+-------------------------+

+-----------------------------------+--------------------------------------------------------------+
|                                           Lane Context                                           |
+-----------------------------------+--------------------------------------------------------------+
| PLATFORM_NAME                     |                                                              |
| LANE_NAME                         | integration                                                  |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 371                                                          |
| SCAN_DERIVED_DATA_PATH            | /Users/jenkins/Library/Developer/Xcode/DerivedData/App-... |
| SCAN_GENERATED_PLIST_FILES        | ["/Users/jenkins/Library/Developer/Xcode/DerivedData/App.. |
| SCAN_GENERATED_PLIST_FILE         | /Users/jenkins/Library/Developer/Xcode/DerivedData/App-... |
| SIGH_PROFILE_TYPE                 | enterprise                                                   |
+-----------------------------------+--------------------------------------------------------------+
[16:22:41]: Error building the application - see the log above

+------+--------------------------------------------------------+-------------+
|                              fastlane summary                               |
+------+--------------------------------------------------------+-------------+
| Step | Action                                                 | Time (in s) |
+------+--------------------------------------------------------+-------------+
| 1    | import_from_git                                        | 0           |
| 2    | get_info_plist_value                                   | 0           |
| 3    | Switch to ApplicationIntegration lane                  | 0           |
| 4    | Switch to test lane                                    | 0           |
| 5    | cocoapods                                              | 29          |
| 6    | scan                                                   | 230         |
| 7    | Switch to generate_enterprise_signing_credentials lane | 0           |
| 8    | match                                                  | 1           |
| 9    | Switch to create_ipa_enterprise lane                   | 0           |
| 10   | Switch to generate_enterprise_signing_credentials lane | 0           |
| 11   | match                                                  | 1           |
| 12   | Switch to create_versionInfo_for_ipa lane              | 0           |
| 13   | cocoapods                                              | 7           |
| 14   | get_info_plist_value                                   | 0           |
| 15   | get_info_plist_value                                   | 0           |
| 16   | get_info_plist_value                                   | 0           |
| 17   | get_info_plist_value                                   | 0           |
| 18   | set_info_plist_value                                   | 0           |
| 19   | set_info_plist_value                                   | 0           |
| 💥   | gym                                                    | 254         |
+------+--------------------------------------------------------+-------------+

[16:22:41]: fastlane finished with errors

[!] Error building the application - see the log above```

Working slave completes gym and publish steps.

**Comment by bonebox** [comment]
I'm getting the exact same error on my Jenkins slave using Match.  OpenSSL is the same version on both my MacBook and slave.

**Comment by bonebox** [comment]
@stark525 Out of curiosity what version of fastlane were you using when you initially ran match to create the provisioning profiles?  I tried downgrading my fastlane version to 1.111.0 on my slave since you mentioned that version was working for you, but I still get the same error.  Wondering if the profiles/certs need to also be created with the older version to avoid the error.

**Comment by stark525** [comment]
I had created the profiles/certs with that older version, but I blew them away and recreated them with fastlane 2.7.0 on my Mac. The slave running 1.111.0 continues to work (match 0.11.0) despite being the data being "newer", and my fastlane 2.7.0 (match 2.7.0) slave doesn't work.  I haven't tried going to the current latest (2.9.0).

FWIW I'm also using MATCH_FORCE_ENTERPRISE=1 and enterprise signing is still not officially supported. I haven't had any problems with the older version, though.

I believe match is doing it's job as the certs and provisioning profiles are being installed, especially because I can run the failing codesign command outside of fastlane successfully.

Hope this helps.

**Comment by bonebox** [comment]
Sorry, I see now where you already said you nuked and recreated your certs in a later comment.  I'm actually using 2.9.0, so whatever the problem is, it's still present in the latest version.  Do you use CocoaPods, by chance?  My error is occurring during the Embed Pods Framework build phase after the app has finished building successfully.  Wondering if it could be related to that.

```
Code Signing /Users/ios/Jenkins/Home/workspace/com.allogy.RMF/build/RMF App Store.app/Frameworks/Alamofire.framework with *removed*
/usr/bin/codesign --force --sign 61B7490A2D2AB3BC16D8D0EF076DF4D66598CC6A  --preserve-metadata=identifier,entitlements '/Users/ios/Jenkins/Home/workspace/com.allogy.RMF/build/RMF App Store.app/Frameworks/Alamofire.framework'
SecKey API returned: -25308, (null)/Users/ios/Jenkins/Home/workspace/com.allogy.RMF/build/RMF App Store.app/Frameworks/Alamofire.framework: unknown error -1=ffffffffffffffff
Command /bin/sh failed with exit code 1

** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/ios/Library/Developer/Xcode/DerivedData/RMF-bfwywtosqtzstbbruqgqkyqfqppk/Build/Intermediates/RMF.build/Release-iphoneos/RMF\ App\ Store.build/Script-CA4B0382E1670E9A90A4F8F0.sh
(1 failure)
Build step 'Xcode' marked build as failure
```

**Comment by bonebox** [comment]
Well, I got it working.  I had to move my certificate from the `login` keychain to the `System` keychain.  For some reason Jenkins doesn't seem to have the proper authority to access the certificates from the `login` keychain when they're added by Match.  I then tried updating back to the latest via Homebrew to see if it would still work, and it failed with the same error.  So I reverted back to 2.0.1 via Rubygems (I misspoke in my earlier post--I wasn't actually able to install 1.111.0 from Rubygems as the appropriate fastlane_core wasn't available, so I did 2.0.1, instead) and it's working again.  So you might give that a shot.  Thankfully once the cert is moved, it remains in that keychain on subsequent calls to Match.  It appears that something changed in later versions with the way Match handles the certificates when installing them to the keychain.

**Comment by stark525** [comment]
That's great you got it working. I tried moving the cert to the System keychain and setting `Code Signing: Always Trust` but I'm seeing the same problem. Did you require the System keychain to remain unlocked? Mine keeps locking after about a minute and won't let me change settings on Sierra.

**Comment by stark525** [comment]
Also, I got different a more generic code signing error when running fastlane with `--capture-output`:

```
[16:58:46]: ▸ Touching App.app.dSYM
[16:58:46]: ▸ Archive Succeeded
[16:58:46]: Successfully stored the archive. You can find it in the Xcode Organizer.
[16:58:46]: The generated archive is invalid, this can have various reasons:
[16:58:46]: Usually it's caused by the `Skip Install` option in Xcode, set it to `NO`
[16:58:46]: For more information visit https://developer.apple.com/library/ios/technotes/tn2215/_index.html
[16:58:46]: Also, make sure to have a valid code signing identity and provisioning profile installed
[16:58:46]: Follow this guide to setup code signing https://docs.fastlane.tools/codesigning/GettingStarted/
[16:58:46]: If your intention was only to export an ipa be sure to provide a valid archive at the archive path.
+-----------------------------------+--------------------------------------------------------------+
|                                           Lane Context                                           |
+-----------------------------------+--------------------------------------------------------------+
| PLATFORM_NAME                     |                                                              |
| LANE_NAME                         | integration                                                  |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 377                                                          |
| SCAN_DERIVED_DATA_PATH            | /Users/jenkins/Library/Developer/Xcode/DerivedData/App-... |
| SCAN_GENERATED_PLIST_FILES        | ["/Users/jenkins/Library/Developer/Xcode/DerivedData/App... |
| SCAN_GENERATED_PLIST_FILE         | /Users/jenkins/Library/Developer/Xcode/DerivedData/App-... |
| SIGH_PROFILE_TYPE                 | enterprise                                                   |
+-----------------------------------+--------------------------------------------------------------+
[16:58:46]: Archive invalid
```

**Comment by bonebox** [comment]
I didn't change any of the settings in the System keychain.  I did delete the certificate/key from the keychain as well as the provisioning profile and re-ran match to recreate them, then moved the cert. You probably did this already, but make sure you move the private key along with the cert.  Also remember that I wasn't able to get this to work with the latest Fastlane, I have it working with 2.0.1--so if you're still running the latest that could be the problem.
