### ISSUE TITLE
Unknown command reinstall

### ISSUE THREAD

**Issue by quetool** [fastlane/fastlane#7823]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hi! Wich is the best way to update fastlane and all its components?

When I use fastlane update_fastlane the system suggest me to use brew cask reinstall fastlane

When I run it I get Error: Unknown command: reinstall

```
QuetoolMacBookPro:~ alfredo$ fastlane update_fastlane
Fastlane update available
Please run `brew cask reinstall fastlane`
Updating installed gems
Updating cert
Fetching: cert-2.0.0.gem (100%)
Please use `fastlane cert` instead of `cert` from now on.
Successfully installed cert-2.0.0
Updating credentials_manager
ERROR:  While executing gem ... (Gem::Resolver::Molinillo::CircularDependencyError)
    There is a circular dependency between spaceship and credentials_manager
Fastlane update available
Please run `brew cask reinstall fastlane`
Cleaning up installed gems...
Attempting to uninstall cert-1.5.1
Successfully uninstalled cert-1.5.1
Clean Up Complete
QuetoolMacBookPro:~ alfredo$ brew cask reinstall fastlane
brew-cask provides a friendly homebrew-style CLI workflow for the
administration of macOS applications distributed as binaries.

Commands:

    audit                  verifies installability of Casks
    cat                    dump raw source of the given Cask to the standard output
    cleanup                cleans up cached downloads and tracker symlinks
    create                 creates the given Cask and opens it in an editor
    doctor                 checks for configuration issues
    edit                   edits the given Cask
    fetch                  downloads remote application files to local cache
    home                   opens the homepage of the given Cask
    info                   displays information about the given Cask
    install                installs the given Cask
    list                   with no args, lists installed Casks; given installed Casks, lists staged files
    search                 searches all known Casks
    style                  checks Cask style using RuboCop
    uninstall              uninstalls the given Cask
    update                 a synonym for 'brew update'
    zap                    zaps all files associated with the given Cask

See also "man brew-cask"
Error: Unknown command: reinstall
```

Plus, when I run my lane I am getting a Warning to update spaceship

```
---------------------------------------------
-------------------WARNING-------------------
---------------------------------------------
You're using an old version of spaceship
To ensure spaceship and fastlane works
update to the latest version.

Run `[sudo] gem update spaceship`

or `bundle update` if you use bundler.

You're on spaceship version: 0.39.0
Latest spaceship version   : 1.0.0
```

I run sudo gem update spaceship but the warning is always shown!

So, which is the best way to update fastlane and all its components?

Fastlane env

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | 🚫 Update availaible |
| spaceship           | 0.39.0  | 🚫 Update availaible |
| fastlane            | 2.0.3   | 🚫 Update availaible |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| security                  | 0.1.3        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| babosa                    | 1.0.2        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| excon                     | 0.54.0       |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| rubyzip                   | 1.2.0        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
</details>

*generated on:* **2017-01-11**
</details>

**Comment by quetool** [comment]
I added fastlane env you noisy bot :P

**Comment by jinjorge** [comment]
interested that you don't have the `reinstall` option for `brew cask`

```
➜  ~ brew cask help
brew-cask provides a friendly homebrew-style CLI workflow for the
administration of macOS applications distributed as binaries.

Commands:

    audit                  verifies installability of Casks
    cat                    dump raw source of the given Cask to the standard output
    cleanup                cleans up cached downloads and tracker symlinks
    create                 creates the given Cask and opens it in an editor
    doctor                 checks for configuration issues
    edit                   edits the given Cask
    fetch                  downloads remote application files to local cache
    home                   opens the homepage of the given Cask
    info                   displays information about the given Cask
    install                installs the given Cask
    list                   with no args, lists installed Casks; given installed Casks, lists staged files
    reinstall              reinstalls the given Cask
    search                 searches all known Casks
    style                  checks Cask style using RuboCop
    uninstall              uninstalls the given Cask
    zap                    zaps all files associated with the given Cask

See also "man brew-cask"
➜  ~
```

try running `brew doctor` then `brew update`

**Comment by quetool** [comment]
Thank you very much @jinjorge I did it and now I can reinstall fastlane!

**Comment by jinjorge** [comment]
@quetool I am glad that was helpful 👍

**Comment by quetool** [comment]
@jinjorge  Obviously that command update all components (spaceship included) right?

**Comment by jinjorge** [comment]
@quetool It should, yes.

You can run `fastlane spaceship -v` to see the version of Spaceship.  Replace `spaceship` with any other component to see the version numbers of the component

```
➜  ~ fastlane spaceship -v
fastlane installation at path:
/Users/jeremiah/.rvm/gems/ruby-2.3.1/gems/fastlane-2.7.0/bin/fastlane
-----------------------------
spaceship 2.7.0
➜  ~
```

**Comment by quetool** [comment]
@jinjorge thank you very much!
