### ISSUE TITLE
NameError: uninitialized constant FastlaneCore::Env

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#7825]
$ BUNDLE_GEMFILE=Gemfile.fastlane bundle exec fastlane test app:ui
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NameError: uninitialized constant FastlaneCore::Env
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/plugins/plugin_update_manager.rb:18:in `show_update_status'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:39:in `ensure in start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/commands_generator.rb:46:in `start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.7.0/bin/fastlane:15:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

**Comment by KrauseFx** [comment]
Can you share your `Gemfile`? Do you still have `fastlane_core` in there?

**Comment by KrauseFx** [comment]
If so, please remove it

**Comment by yakimant** [comment]
```
source 'https://rubygems.org'

gem 'fastlane'
gem 'nokogiri'
gem 'slather'
gem 'CFPropertyList', '=2.2.8'
gem 'sqlite3', '>=1.3.7'

gem 'gym', '>=1.12.1'
```

**Comment by yakimant** [comment]
Looks like bundle update helped, will check now.

**Comment by KrauseFx** [comment]
Cool. Also please remove `gym` from your Gemfile 👍

**Comment by yakimant** [comment]
Helped, closing
