### ISSUE TITLE
[Transporter Error Output]

### ISSUE THREAD

**Issue by quetool** [fastlane/fastlane#7827]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This is more like an iTunes Connect Error.
Newest compilation throwing error because previous binary stucks on processing on iTunes.

![captura de pantalla 2017-01-11 a las 15 52 49](https://cloud.githubusercontent.com/assets/14978705/21862005/2dfaef66-d816-11e6-9bd2-62ebd7e755bf.png)

What can I do?

```
[15:48:31]: Uploading binary to iTunes Connect
[15:48:31]: Going to upload updated app to iTunes Connect
[15:48:31]: This might take a few minutes. Please don't interrupt the script.
[15:49:06]: [Transporter Warning Output]: Failed to obtain exclusive lock on token file.  Please ensure the following file is not locked by another process: /Users/alfredo/.itmstransporter/UploadTokens/QuetoolMacBookPro.local_AngeloAntonelli406489383_1191493567.itmsp.token
[15:49:06]: [Transporter Error Output]: Cannot proceed with delivery: an existing transporter instance is currently uploading this package
[15:49:06]: Transporter transfer failed.
[15:49:06]: Failed to obtain exclusive lock on token file.  Please ensure the following file is not locked by another process: /Users/alfredo/.itmstransporter/UploadTokens/QuetoolMacBookPro.local_AngeloAntonelli406489383_1191493567.itmsp.token
[15:49:06]: Cannot proceed with delivery: an existing transporter instance is currently uploading this package
[15:49:06]: Failed to obtain exclusive lock on token file.  Please ensure the following file is not locked by another process: /Users/alfredo/.itmstransporter/UploadTokens/QuetoolMacBookPro.local_AngeloAntonelli406489383_1191493567.itmsp.token
[15:49:06]: Cannot proceed with delivery: an existing transporter instance is currently uploading this package
Return status of iTunes Transporter was 1: Cannot proceed with delivery: an existing transporter instance is currently uploading this package
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2017-01-11**
</details>

**Comment by davidwattpad** [comment]
I'm also having this problem.
Adding `ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = '-t DAV'` to the top of my Fastfile hasn't worked (as suggested in https://github.com/fastlane/fastlane/issues/6151)

**Comment by quetool** [comment]
for me it was just a temporary iTunes Connect problem... I twitted that out :P https://twitter.com/quetool/status/819275082631618560

**Comment by mfurtak** [comment]
The error from the log in this ticket:

```
[Transporter Error Output]: Cannot proceed with delivery: an existing transporter instance is currently uploading this package
```

is explained by:

```
Please ensure the following file is not locked by another process: /Users/alfredo/.itmstransporter/UploadTokens/QuetoolMacBookPro.local_AngeloAntonelli406489383_1191493567.itmsp.token
```

@davidwattpad If you're also seeing this message, you could try to clear out the lock-files in the location that corresponds to your user. Also, be sure that you're not trying to run multiple instances of uploads at the same time.

If you're experiencing a different problem, please open a new ticket 👍  I'll close this for now, based on @quetool's comment above.

**Comment by bennettrogers** [comment]
@mfurtak Interesting - I just got this error as well while trying to upload multiple applications at once. Why do you say "be sure that you're not trying to run multiple instances of uploads at the same time"? Is this not supported by Fastlane?

**Comment by mfurtak** [comment]
Hi @bennettrogers 👋 

I don't know exactly what its rules are, but I was just attempting to interpret the messages, behavior, and mechanisms of the iTunes Transporter, which appears to use lock files to ensure that it is not doing two jobs simultaneously. 👍

**Comment by bennettrogers** [comment]
Gotcha, thanks. I did notice that when uploading screenshots, Fastlane will copy the images to a temporary directory (under /tmp) and use the hash of the relative path as the new filename. Because of this, it's easy to get conflicts for these temporary files when uploading multiple apps at once. A quick solution is to explicitly specify the screenshots directory in the Fastfile, including the app name in the path. That way the app name is included in the relative path, so the hashes don't collide.

[Here](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/du/upload_file.rb#L34) is the line where the temporary filepath is created.
