### ISSUE TITLE
scan ignores output_types value

### ISSUE THREAD

**Issue by NachoSoto** [fastlane/fastlane#7833]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
`Fastfile`:
```ruby
lane :test do
    scan(device: "iPhone SE (10.0)")
end
```

`Scanfile`:
```ruby
workspace "..."
scheme "..."
clean true
output_types "raw"
```

When running `fastlane test`, the raw output type is not being used.
Changing the `lane` to `scan(device: "iPhone SE (10.0)", outputTypes: "raw")` does not, either.

The only thing that does is invoking `fastlane scan -b raw` by hand.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.2                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.11.0                                             |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.2 (16C67)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| highline                  | 1.7.8        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| json                      | 2.0.2        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.2.0        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| bundler                   | 1.13.7       |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.2        |
</details>

*generated on:* **2017-01-11**
</details>

**Comment by NachoSoto** [comment]
Actually I just realized that I get the following warning at the end of `fastlane test`:
```
[14:39:53]: Couldn't find reporter 'raw', available html, junit, json-compilation-database
```

So I guess that's the real problem. I do need to use `scan`'s raw output format though, because if there is a compilation issue, the default output format does not offer all the necessary information.

**Comment by mfurtak** [comment]
Hi @NachoSoto 👋 

There's a couple similar options here that you may be confusing:

`--output_style` (`-b`) accepts `raw`, and controls `xcodebuild` output
`--output_types` (`-f`) does not, and controls the report generation

If your `Scanfile` gets `output_style "raw"` does that do what you'd expect?

**Comment by NachoSoto** [comment]
Ooooh, yup, that's exactly what I was confused about. `output_style "raw"` does precisely what I wanted. Thank you!
