### ISSUE TITLE
[Question] Generate Push notification certificate when certificate is expired. 

### ISSUE THREAD

**Issue by biolinh** [fastlane/fastlane#7835]
The situation is:

My membership is renewed in Jan, 2017 but the expiration-date of Push Notification is in Oct, 2017.
Due to the Certificate is expired, my Push Notification is expired too. 

But, when building app, I call pem command:
```
pem(generate_p12: true, p12_password: 'PASSWORD', pem_name: APP_NAME)
```
It returns the log:
```
[11:43:19]: Existing push notification profile '' is valid for 276 more days.
[11:43:19]: [32mYou already have a push certificate, which is active for more than 30 more days. No need to create a new one
```
Therefore, to create a new one, I manually run pem with  "--force".

Howerver, I want to  call pem command  in Fastlane file without using "--force" because I use Fastlane to build multiple apps with multiple accounts.

My question is
 How can I check and force to create new Push notification certificate when I renew my membership.

It means that my  certificate of Push Notification is expired but expiration-date of Push Notification is more than 30 days.
I still can check its expiration  and force to create new one.

**Comment by hjanuschka** [comment]
i am not 100% sure if i get it right.

but you could use spaceship - to fetch the current push certificate, and check the expiration date, and based on that toggle the force flag in following pem step's.



```ruby
push_cert = Spaceship.certificate.production_push.all.detect do | c | c.name == "krone.at-krone.at" end
push_cert.
```


![bildschirmfoto 2017-01-12 um 23 38 01](https://cloud.githubusercontent.com/assets/2891702/21911240/32bf8466-d920-11e6-9ec9-01da66729d6e.png)

**Comment by biolinh** [comment]
@hjanuschka 
Thank you, I will try it and let you know late.
