### ISSUE TITLE
New action for `git merge`

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7837]
Should we have a new action for `git merge` command? I want to push my local commit to remote repository on some other branch. How can I achieve this with the existing actions?

**Comment by PetrosIchor** [comment]
Check out the docs.  There's a ton of prebuilt git functions.  Also, the `sh` action.

https://docs.fastlane.tools/actions/#push_to_git_remote

**Comment by RishabhTayal** [comment]
the prebuilt git functions doesn't gives you ability to merge your current branch to other branch and push to remote.

**Comment by PetrosIchor** [comment]
Did you look at the `sh` action?  It'll solve most if not all fastlane action short comings. 

`sh(git merge $branch)`

**Comment by RishabhTayal** [comment]
That was my last resort. I thought it might be useful to have this action.

Regards,
Rishabh Tayal
rishabh.tayal@syw.com

**Comment by KrauseFx** [comment]
Nope, sorry, that's not planned right now, as it doesn't fit into the major use-cases of fastlane
