### ISSUE TITLE
testflight `Could not receive latest API key from iTunes Connect, this might be a server issue.`

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#7841]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Getting `Could not receive latest API key from iTunes Connect, this might be a server issue.` 

```
 Login to iTunes Connect (xxxx@xxxx.com)
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
+--------------------+-----------------------------------------------------------------------------+
[10:31:39]: Could not receive latest API key from iTunes Connect, this might be a server issue.
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                     |
| ------------------- | ----------------------------------------- |
| OS                  | 10.12.2                                   |
| Ruby                | 2.2.1                                     |
| Bundler?            | false                                     |
| Git                 | git version 2.10.1 (Apple Git-78)         |
| Installation Source | ~/.rvm/gems/ruby-2.2.1/bin/fastlane       |
| Host                | Mac OS X 10.12.2 (16C67)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.1/lib              |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                |
| Is contained        | false                                     |
| Xcode Path          | ~/Downloads/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                     |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.2.0"

default_platform :ios

ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'

platform :ios do

  lane :itunes_connect do |options|
    deploy_app_appstore('scheme', 'project.xcodeproj', options[:version_number])
    slack(message: "Successfully deployed new App Update.")
  end

  def deploy_app_appstore(scheme_name, xcodeproj_path, version_number)
   gym({
    scheme: scheme_name,
    export_method: 'app-store',
    toolchain: :swift_2_3,
    clean: true,
    disable_xcpretty: true,
    include_bitcode: false,
    codesigning_identity: 'iPhone Distribution',
    silent: true
    })
   testflight(
    skip_waiting_for_build_processing: true,
    distribute_external: true
    )
 end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
team_name "xxxx"

# To select a team for iTunes Connect use
itc_team_name "xxxx"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.7.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.13.6  |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| terminal-table            | 1.7.3   |
| plist                     | 3.2.0   |
| addressable               | 2.5.0   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| excon                     | 0.54.0  |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 2.0.1   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.12.1  |
| logging                   | 2.1.0   |
| jwt                       | 1.5.6   |
| memoist                   | 0.15.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.3   |
| googleauth                | 0.5.1   |
| httpclient                | 2.8.3   |
| google-api-client         | 0.9.20  |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| json                      | 2.0.2   |
| commander                 | 4.4.2   |
| rubyzip                   | 1.2.0   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| unicode-display_width     | 1.1.2   |
</details>

*generated on:* **2017-01-12**
</details>

**Comment by mfurtak** [comment]
It looks like you are using RVM... if so, please try running `rvm osx-ssl-certs update all` and then retrying.

More info:
https://rvm.io/support/fixing-broken-ssl-certificates
https://github.com/rvm/rvm/blob/master/help/osx-ssl-certs.md

**Comment by hanneskaeufler** [comment]
I am seeing the same on `bundle exec fastlane init`. I did run `rvm osx-ssl-certs update all` with output:

```
Updating certificates for /usr/local/etc/openssl/cert.pem: Already up to date.
Updating certificates for /etc/openssl/cert.pem: Already up to date.
```

My setup is entirely the same as above but with rvm  `ruby-2.2.3`

**Comment by hanneskaeufler** [comment]
I solved it by
```
brew update && brew upgrade openssl
rvm reinstall ruby-2.2.3 --with-openssl-dir=/usr/local
