### ISSUE TITLE
different targets and schemes

### ISSUE THREAD

**Issue by Mactub07** [fastlane/fastlane#7842]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

how I can use different schemes , which include different apps , with fastlane

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by PetrosIchor** [comment]
Using environment variables is probably the easiest way.  Depends on your setup and needs.  If you could provide more information/context I could try to provide a more targeted answer.

**Comment by hjanuschka** [comment]
most of the actions support parameters of `sheme` and/or `target`


for example gym:

```ruby
gym(scheme: "MyApp", workspace: "MyApp.xcworkspace")
```

**Comment by mgrebenets** [comment]
To add 5c, you can pass options to `gym` via command line too, e.g. `fastlane gym workspace:"MyApp.xcworkspace" scheme:"MyApp"`

**Comment by ohayon** [comment]
Going to close this issue for now as it looks like @mgrebenets and @hjanuschka have suggested some good work flows for this use case. Please do not hesitate to let us know if you are still having issues! 🐙 🚀
