### ISSUE TITLE
Is there any way to add a custom platform

### ISSUE THREAD

**Issue by SuperMarioBean** [fastlane/fastlane#7846]
hi there. I use your fastlane for both iOS and Android automate tasks in my team, it's great!
now I found the fastlane only support :ios :android :mac, in my team, I wound like use fastlane to rule all platform like :ios, :android, :h5.

in my team, we define a method `ci_building` method to every platform to complete build task. like:

```ruby
desc "build and package"
desc "  @param configuration"
desc "  @param skip_build_archive"
desc "  @param export_method as app-store, ad-hoc, package, enterprise, development, developer-id"
lane :ci_building do |options|
  if ENV['FASTLANE_PLATFORM_NAME'] == 'ios'
    configuration = options[:configuration]
    skip_build_archive = options[:skip_build_archive] || false
    export_method = options[:export_method]
    gym(
        workspace:ENV['FMT_PROJECT_WORKSPACE_NAME'],
        scheme:ENV['FMT_PROJECT_SCHEME_NAME'],
        clean:true,
        configuration:configuration,
        include_bitcode:false,
        build_path:'./build',
        derived_data_path:'./DerivedData',
        skip_build_archive:skip_build_archive,
        export_method: export_method
    )
  elsif ENV['FASTLANE_PLATFORM_NAME'] == 'android'
    task = options[:task]
    gradle(task: "clean")
    gradle
    if is_ci?
      gradle(task: task,
             properties:{
                 "versionCode" => ENV['BUILD_NUMBER']
             })
    else
      gradle(task: task)
    end
  end
end
```

the other method like `ci_testing`, `ci_releasing` has the same logic to share between different platforms. so I would like to add a :h5 platform for my h5 team members, just like

```ruby
  # add the h5 platform
  else if ENV['FASTLANE_PLATFORM_NAME'] == 'h5'
    task = option[:task]
    if is_ci?
      npm(task: task)
    end
  end
```

npm is a action like gradle. it would be great to share task in fastlane like `ci_release`, `ci_testing` while use the `gradle` or `npm` in `ci_building`.

**Comment by hjanuschka** [comment]
@SuperMarioBean i think that it is too deep bound to the mobile platforms. (like actions checking for `:android`, `:ios` and so on)

could'nt you use a custom ENV variable ? that you set before calling fastlane which holds your desired platform?


like:

```ruby
export MY_PLATFORM="h5"
fastlane lane
```

we do something similar but use lane parameters.


Fastfile:

```ruby
lane :deploy do | options |
       if options[:platform] == "docker"
         # do docker build and stuff
       end
end
```


calling it from fastfile:

```ruby
deploy(platform: "docker")
```


or via shell

```bash
fastlane deploy platform:docker
```


let me know if there is a way that works for you.

**Comment by SuperMarioBean** [comment]
@hjanuschka thanks a lot, it works. 

BTW, I got confused if we can use ENV variable or parameter for different platform, then why fastlane got :ios, :android, :mac? maybe a subclass of Platform to regist to fastlane for different platform will be better?

😄

**Comment by ohayon** [comment]
Hey @SuperMarioBean! Thanks for raising this issue. As @hjanuschka mentioned, I think that we have our platforms baked pretty deep into how _fastlane_ works. Additionally, our goal with _fastlane_ is to be an amazing deployment mechanism for mobile apps. Adding the ability to deploy to other platforms could result in increased surface area for support and a less focused toolset for iOS/Android. Feel free to create _fastlane_ plugins that can support other platforms and do more use-case specific things! Thanks again! 😄 🐙
