### ISSUE TITLE
Support creating JWT-signing keys (.p8 files) in pem

### ISSUE THREAD

**Issue by ide** [fastlane/fastlane#7848]
This is a feature request for Fastlane (specifically pem) to support creating APNs keys as opposed to certificates. The keys are used to sign tokens for Apple's token-based authentication.

The token-based authentication has several advantages: tokens never expire unless they are revoked and they are associated with individual requests instead of connections, allowing you to reuse one connection for several apps. Instead of a certificate and key, with token-based auth there is only the key (.p8 file) and it works for development and production.

**Comment by mfurtak** [comment]
Hi @ide 👋 

This is not something that the core team plans to take on right away, but folks should feel free to use the :+1: reaction on your description to vote for this if it's something they need. We can always revisit it!

Thanks!
