### ISSUE TITLE
Hockey: support for custom uploads

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#7852]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The Hockey action only supports the upload method right now (https://github.com/fastlane/fastlane/blob/HEAD/fastlane/lib/fastlane/actions/hockey.rb), which works fine for IOS/Android builds (and Mac if .app zipped).

For other types of builds, such as custom Windows / Mac, the HockeyApp API requires to use a different API.

See "https://support.hockeyapp.net/kb/api/api-versions#upload-version":

>  If you want to upload a custom .zip file or other file formats like .msi or .dmg, you need to use the Create Version and Update Version API.

Right now we use a curl script to support Windows/Mac uploads:

```
version=....
app_id=7b36c20e........................
            
echo "---- Create Version ----"

curl \
  -F "bundle_short_version=$version" \
  -F "tags=qa" \
  -F "bundle_version=$BUILD_NUMBER" \
  -H "X-HockeyAppToken: $HOCKEY_API_TOKEN" \
  https://rink.hockeyapp.net/api/2/apps/$app_id/app_versions/new | tee answer.json || exit -1

app_version_id=`cat answer.json | python -c "import sys, json; print json.load(sys.stdin)['id']"`

echo "---- Upload Version ----"

curl \
  -X PUT \
  -F "tags=qa" \
  -F "notify=1" \
  -F "status=2" \
  -F "ipa=@target/${BUILD_PRODUCT_ID}_win32.zip" \
  -H "X-HockeyAppToken: $HOCKEY_API_TOKEN" \
  -v "https://rink.hockeyapp.net/api/2/apps/$app_id/app_versions/$app_version_id"
```

We could support this directly in the `hockey` action.

fastlane has a stated goal to support Mobile development first and foremost.

Given that we support Mac upload as Zip file, I suspect it is OK to add support for custom builds upload as well.

**Comment by mfurtak** [comment]
Hm. Yeah, I think this falls outside of the core vision for _fastlane_, and I'd suggest it should be a plugin.

We should try to bias to not increasing the surface area of our built-in actions unless its a really strong fit for the core mission. 👍

**Comment by lacostej** [comment]
This ended up being supported in upcoming fastlane 2.15.0 per #8110
