### ISSUE TITLE
Upload dSYM only to Hockey is failing after update

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#7854]
Error:
```html
[18:01:56]: Error when trying to upload ipa to HockeyApp: <!DOCTYPE html>
<html lang='en' class="full_height">
  <head>
    <meta charset='utf-8'>
    <title>Server Error</title>
    <meta content="authenticity_token" name="csrf-param" />
    <link href="/assets/application-default.css" media="all" rel="stylesheet" type="text/css" />
    <link href='/favicon.ico' rel='shortcut icon'>
  </head>
  <body class='full_height'>
    <div class='container-fluid full-height full-width'>
      <div class='row-dialog'>
        <div class='centered-vertical'>
          <div class='centered-horizontal'>
            <div class='well'>
              <h3>Ooops…</h3>
              <p class="pad-top">
                We're sorry, but something went wrong. We've been notified about this issue and we'll take a look at it shortly. If you want to provide more
 information, please file a support ticket.
              </p>
              <p>
                <a href="/" class="btn btn-ha-primary">Home</a>
                <a href="https://support.hockeyapp.net" class="btn">Support</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class='clear'></div>
    </div>
    <script src="/assets/application-default.js" type="text/javascript"></script>
  </body>
</html>
```

Code
```ruby
  hockey(api_token: hockeyapp_api_token,
         public_identifier: hockeyapp_app_id,
         dsym: dsym,
         upload_dsym_only: true,
         strategy: 'replace',)
```

Or running from terminal:
```
fastlane run hockey api_token:TOKEN dsym:App.app.dSYM.zip public_identifier:ID upload_dsym_only:true strategy:replace
```

This issue appeared after last gems update.

**Comment by yakimant** [comment]
After small investigation I've discovered, that 2.6.0 is Ok, but 2.7.0 and 2.8.0 are failing.
As a workaround for this issue - reverting back to 2.6.0.

**Comment by jalmaas** [comment]
I can confirm this for all our projects as well. 2.6.0 works. Actually the dsym is uploaded with 2.7 and 2.8, but we see the error posted by @yakimant

**Comment by asfalcone** [comment]
Any chance it could be related to [this change](https://github.com/fastlane/fastlane/commit/6460a967b49444695e2795396dfcc2bff8938be9)? This is the only thing I see that was introduced for `hockey` in _fastlane_ 2.7.0. cc @overtake

**Comment by overtake** [comment]
Hm. I Think my commit not affect uploading dsym. Strange. For me its work🤔

**Comment by hjanuschka** [comment]
hey guys could you try this PR: https://github.com/fastlane/fastlane/pull/7875
i think the underlying issue is that if `dsa_signature` is not set it results in a request body including:

```
{
.....
dsa_signature: null
}
```

the PR ensures to remove dsa_signature if not explicitly set.

**Comment by jalmaas** [comment]
adding `dsa_signature: ""` to the hockey-step seems to work for me

**Comment by hjanuschka** [comment]
@jalmaas  awesome thx for the info, i updated my pr (https://github.com/fastlane/fastlane/pull/7875) to just set a default value to `""`  can you test the PR without supplieng the dsa_signature?
