### ISSUE TITLE
Feature Request: Allow match to store arbitrary encrypted data

### ISSUE THREAD

**Issue by scottrhoyt** [fastlane/fastlane#7858]
This is a big request, but I would love to see `match` provide a way to store arbitrary encrypted files along with certs and provisioning profiles. This would provide a solution to securing SDK keys. If arbitrary files were too big a request, perhaps this could be simplified to storing a single list of key/value pairs--either as a plist, json, or yaml. What do you guys think?

**Comment by PetrosIchor** [comment]
I agree, but match's purpose is very targeted and I think it's create more problems than good. 

This is what you're looking for!  I use it for Android signing assets, but it'll do any file. 

https://github.com/hjanuschka/fastlane-plugin-cryptex

**Comment by scottrhoyt** [comment]
That's a great suggestion @PetrosIchor! I'll be sure to check it out.

You are probably right about the risk of unintended consequences--especially in an already fickle process like code signing. I'm going to leave this open for a bit just to gather some other opinions, but your suggestion is a great alternative.

**Comment by mfurtak** [comment]
Hi @scottrhoyt - I think the opinion of the team is that _match_ should stay focused on its core job, as @petroslchor mentioned :+1:

If the plugin suggestion gets you going for alternatives, I'll close this out. People should still be able to leave other suggestions later. :rocket:

**Comment by scottrhoyt** [comment]
Thanks
