### ISSUE TITLE
Editing profiles in spaceship (rather than creating new ones)?

### ISSUE THREAD

**Issue by Taconut** [fastlane/fastlane#7864]
I know I can repair, create, and download provisioning profiles with spaceship, but what if I want to adjust their device ids? How would I go about adding devices to a provisioning profile without deleting it?

**Comment by KrauseFx** [comment]
Seems like that's currently not possible, sorry

**Comment by Taconut** [comment]
If I recreate a mobileprovision and there are currently apps signed using that mobileprovision, will they stop working? Just wondering if I can still use spaceship or if I'm going to have to resort to web scraping (ugh).

Thanks

**Comment by Taconut** [comment]
Actually, what about [this function](https://github.com/fastlane/fastlane/blob/92362904e6fa920d17b7d882f07a4b433279c6d1/spaceship/lib/spaceship/portal/portal_client.rb#L430)? Couldn't I call this and explicitly pass it a list of device IDs? It doesn't seem to be exposed like the rest of the functions, so how would I go about calling it and enabling all devices on a given provisioning profile?

**Comment by Taconut** [comment]
I can confirm that my above idea worked. This issue can be closed now.

Thanks for the great tool!

**Comment by hjanuschka** [comment]
@Taconut glad you got it working!
