### ISSUE TITLE
Error 70 using iOS Enterprise certificates with Gym

### ISSUE THREAD

**Issue by mbogh** [fastlane/fastlane#7866]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When trying to create an archive on our CI without using the Legacy Build API we get:
```
** EXPORT FAILED **
[15:38:53]: Exit status: 70
```
On our local machines we simply use the `Automatically manage signing` but due to reasons™ we can only get a certificate and a provisioning profile.

My guess is the following error has something to do with it but I have no clue how to fix this since it just works with legacy api.
```
"<IDEDistributionItem: 0x7fd8a8840df0 'com.lego.LEGOBrickX.live.nightly' '<DVTFilePath:0x7fd8a8d96bc0:'/Users/morten/Library/Developer/Xcode/Archives/2017-01-15/LEGOBrickXExample 2017-01-15 15.35.59.xcarchive/Products/Applications/LEGOBrickXExample.app'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=10 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=No valid 'ad-hoc' profiles were found., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7fd8a8829880; portalTeamID='9D73KSTR45', usingTeamBasedSigning='NO', bundleIdentifier='com.lego.LEGOBrickX.live.nightly', targetName='(null)', provisioningProfilePurpose='2', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"application-identifier\" = \"9D73KSTR45.com.lego.LEGOBrickX.live.nightly\";\n    \"keychain-access-groups\" =     (\n        \"9D73KSTR45.com.lego.LEGOBrickX.live.nightly\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-head/bin/fastlane          |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-head/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2d 9 Jul 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Opt out of tracking
opt_out_usage

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: 'BrickX')
  end

  desc "Build the framework"
  lane :build do
    xcodebuild(
      build_settings: {
        'CODE_SIGN_IDENTITY' => '',
        'CODE_SIGNING_REQUIRED' => false
      },
      scheme: 'BrickX'
    )
  end

  desc "Upload example app to TPA"
  lane :app do
    # General
    update_build_number

    # Live app
    set_app_identifier(
      app_identifier: "com.lego.BrickX.live.nightly"
    )

    archive(
      provisioning_profile: "LEGO_BrickX_live_nightly",
      scheme: "BrickXExample",
      configuration: "Release",
      uuid: "XXX-XXX"
    )

    distribute

    # QA app
    set_app_identifier(
      app_identifier: "com.lego.BrickX.webqa.nightly"
    )

    archive(
      provisioning_profile: "LEGO_BrickX_webqa_nightly",
      scheme: "BrickXExample",
      configuration: "Release",
      uuid: "XXX-XXX"
    )

    distribute
  end

  private_lane :update_build_number do
    build_number = ENV["CI_BUILD_ID"]
    increment_build_number(build_number: build_number)
  end

  private_lane :archive do |options|
    clear_derived_data

    codesigning_identity = options[:codesigning_identity] ? options[:codesigning_identity] : "iPhone Distribution: XXX"
    scheme = options[:scheme]
    include_symbols = options.key?(:include_symbols) ? options[:include_symbols] : true

    current_dir = ENV["PWD"]
    project_path = "#{current_dir}/BrickXExample/BrickXExample.xcodeproj"

    update_project_codesigning(
      use_automatic_signing: false,
      path: project_path
    )

    update_project_code_signing(
      uuid: options[:uuid],
      path: project_path
    )

    update_project_provisioning(
      profile: "#{current_dir}/fastlane/provisioning/#{options[:provisioning_profile]}.mobileprovision",
      xcodeproj: project_path,
      target_filter: "BrickXExample"
    )

    update_project_team(
      teamid: '9D73KSTR45',
      path: project_path
    )

    gym(
      workspace: "#{current_dir}/BrickX.xcworkspace",
      scheme: scheme,
      # codesigning_identity: codesigning_identity,
      configuration: options[:configuration],
      include_bitcode: true,
      include_symbols: include_symbols
      # export_method: "ad-hoc"
    )
  end

  private_lane :distribute do
    tpa(upload_url: 'https://xxx.tpa.io/xxx-xxx/upload')
  end

  private_lane :set_app_identifier do |options|
    current_dir = ENV["PWD"]
    update_app_identifier(
      xcodeproj: "#{current_dir}/BrickXExample/BrickXExample.xcodeproj",
      plist_path: "BrickXExample/Info.plist",
      app_identifier: options[:app_identifier]
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.8.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-tpa                        | 1.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-update_project_codesigning | 0.1.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| executable-hooks                           | 1.3.2        |
| bundler-unload                             | 1.0.2        |
| rubygems-bundler                           | 1.4.4        |
| bundler                                    | 1.13.7       |
| io-console                                 | 0.4.6        |
| CFPropertyList                             | 2.3.4        |
| i18n                                       | 0.7.0        |
| json                                       | 1.8.6        |
| minitest                                   | 5.10.1       |
| thread_safe                                | 0.3.5        |
| tzinfo                                     | 1.2.2        |
| activesupport                              | 4.2.7.1      |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.0        |
| babosa                                     | 1.0.2        |
| claide                                     | 1.0.1        |
| colored                                    | 1.2          |
| highline                                   | 1.7.8        |
| commander                                  | 4.4.3        |
| unf_ext                                    | 0.0.7.2      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20161129 |
| dotenv                                     | 2.1.1        |
| excon                                      | 0.54.0       |
| multipart-post                             | 2.0.0        |
| faraday                                    | 0.11.0       |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.11.0       |
| fastimage                                  | 2.0.1        |
| gh_inspector                               | 1.0.3        |
| jwt                                        | 1.5.6        |
| little-plugger                             | 1.1.4        |
| multi_json                                 | 1.12.1       |
| logging                                    | 2.1.0        |
| memoist                                    | 0.15.0       |
| os                                         | 0.9.6        |
| signet                                     | 0.7.3        |
| googleauth                                 | 0.5.1        |
| httpclient                                 | 2.8.3        |
| hurley                                     | 0.2          |
| mime-types-data                            | 3.2016.0521  |
| mime-types                                 | 3.1          |
| uber                                       | 0.0.15       |
| representable                              | 2.3.0        |
| retriable                                  | 2.1.0        |
| google-api-client                          | 0.9.20       |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| plist                                      | 3.2.0        |
| rubyzip                                    | 1.2.0        |
| security                                   | 0.1.3        |
| slack-notifier                             | 1.5.1        |
| terminal-notifier                          | 1.7.1        |
| unicode-display_width                      | 1.1.3        |
| terminal-table                             | 1.7.3        |
| word_wrap                                  | 1.0.0        |
| nanaimo                                    | 0.2.3        |
| xcodeproj                                  | 1.4.2        |
| rouge                                      | 1.11.1       |
| xcpretty                                   | 0.2.4        |
| xcpretty-travis-formatter                  | 0.0.4        |
| fastlane-plugin-tpa                        | 1.1.0        |
| fastlane-plugin-update_project_codesigning | 0.1.7        |
</details>

*generated on:* **2017-01-15**
</details>

**Comment by PetrosIchor** [comment]
Others might have a deeper knowledge on that error code. 

From my experience, you need to disable automatic signing before injecting you match/signing values in fastlane.  Definitely follow the signing guide if you are able to do so. 

My needs are similar, automatic signing in xcode creates a great deal of complexity. I use a combination of editing the configuration and disabling automatic signing in my Fastfile before running gym or match.  

First I disable automatic signing with an adapted plugin based off: https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning

Then I edit the xcodeproj file with an adapted plugin based off this: https://github.com/faithfracture/update_provisioning_profile_specifier

^ That updates the provisioning profile specifier to use the env variable match generates.

I say adapted because I'm often building blind. My CI will be passed apps built from a number of codebases and configurations.  I rolled the actions of those 2 plugins into a custom action.  It allows my tooling to be agnostic of the codebase.  No matter what the target is, it's going to disable automatic signing and update the signing assets from whatever was previously set by developers. 

Hope that helps!

**Comment by diidu** [comment]
I am having similar issue (IDEDistributionItem) without fastlane tools, when executing:
```
xcodebuild -exportArchive \
    		    -archivePath "${BUILD_DIR}/${PRODUCT_NAME}-${BUILD_NUMBER}.xcarchive" \
             	    -exportPath "${PROJECT_DIR}" \
          	    -exportOptionsPlist "${export_options_plist}"
```
When having method set to ad-hoc. With method: enterprise it works fine. It does not matter whether signing is set to auto or manual, in both cases it seems wrong signing certificate is selected. Building with Xcode succeeds.

In any case, I don't think this is really fastlane problem, but something wrong either in xcodebuild or the environment.

**Comment by Appuploader** [comment]
Recommended iOS Enterprise Certificate Request aids to quickly create p12 and mobileprovision iOS certificate files.

Https://github.com/Appuploader/applicationloader
