### ISSUE TITLE
Match encrypts repo after failed clone

### ISSUE THREAD

**Issue by koenpunt** [fastlane/fastlane#7869]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When match fails to clone the certificate repo, it will still continue with encrypting it. Or at least that's what the output suggests:

![image](https://cloud.githubusercontent.com/assets/351038/21965388/15b60d2c-db5f-11e6-98e1-8aad947b4454.png)

But I think that action shouldn't be executed when the clone fails.

**Comment by ohayon** [comment]
Thanks for submitting the issue @koenpunt! It looks like this might just be some erroneous output that got in there somehow and it was not in fact encrypting anything there. Hope this helps! 🚀 🐙 https://github.com/fastlane/fastlane/pull/8378
