### ISSUE TITLE
Docs code formatting is clipped on Chrome

### ISSUE THREAD

**Issue by rnystrom** [fastlane/fastlane#7870]
e.g. https://docs.fastlane.tools/getting-started/ios/beta-deployment/

<img width="889" alt="screen shot 2017-01-15 at 4 26 20 pm" src="https://cloud.githubusercontent.com/assets/739696/21966348/7ac4ad88-db3f-11e6-8f99-84926e64a657.png">

**Comment by hjanuschka** [comment]
i had that too, can you try it with CMD+R - i currently think that it is a cached .css file.

cc @KrauseFx

**Comment by rnystrom** [comment]
@hjanuschka hurray! all Good
