### ISSUE TITLE
Fastlane release gym error

### ISSUE THREAD

**Issue by derektlo** [fastlane/fastlane#7871]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I run `fastlane release` 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

I didn't want to paste the full output since it was so long

the following build commands failed:
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/dereklo/Library/Developer/Xcode/DerivedData/Py-dmreilycdhazgrahbgcgrxwrzegf/Build/Intermediates/ArchiveIntermediates/Py\ AppStore/IntermediateBuildFilesPath/Py.build/AppStore-iphoneos/Py.build/Script-93CE2F805B5DB9FAAACFA886.sh
(1 failure)
[17:24:17]: Exit status: 65

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.8.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>

**Comment by PetrosIchor** [comment]
Without more output or information it's hard to troubleshoot. 

If I'm not mistaken, error code 65 is an archive failure.  This generally is the result of a signing failure. 

Can you provide more output and your fastlane file?

Are you able to build and archive in xcode after receiving that error?

**Comment by derektlo** [comment]
```
▸ Running script '[CP] Embed Pods Frameworks'
** ARCHIVE FAILED **


The following build commands failed:
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/dereklo/Library/Developer/Xcode/DerivedData/Py-dmreilycdhazgrahbgcgrxwrzegf/Build/Intermediates/ArchiveIntermediates/Py\ AppStore/IntermediateBuildFilesPath/Py.build/AppStore-iphoneos/Py.build/Script-93CE2F805B5DB9FAAACFA886.sh
(1 failure)
[14:20:44]: Exit status: 65
[14:20:44]: 📋  For a more detailed error log, check the full log at:
[14:20:44]: 📋  /Users/dereklo/Library/Logs/gym/Py-Py AppStore.log

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.8.0                   |
| sdk         | iPhoneOS10.1.sdk        |
+-------------+-------------------------+

+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios release |
+------------------+-------------+
[14:20:44]: Error building the application - see the log above

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | Switch to ios build lane                                      | 0           |
| 4    | Switch to ios set_build_number lane                           | 0           |
| 5    | git tag | grep '^v*[0-9]' | sed 's/[^0-9.]//g' | sort -n | ta     | 0           |
| 6    | date -u +%y%m%d%H%M                                           | 0           |
| 7    | /usr/libexec/PlistBuddy -c 'Set :CFBundleShortVersionString 3 | 0           |
| 8    | /usr/libexec/PlistBuddy -c 'Set :CFBundleVersion 1701161916'  | 0           |
| 💥    | gym                                                           | 266         |
+------+---------------------------------------------------------------+-------------+

[14:20:44]: fastlane finished with errors

[!] Error building the application - see the log above

```

[Fastfile.txt](https://github.com/fastlane/fastlane/files/709245/Fastfile.txt)

I am able to build and archive successfully in Xcode.

**Comment by mfurtak** [comment]
@derektlo Can you please provide the complete output produced when running this again with the `--capture_output` flag.

One thing I'd like to be able to see is what `xcodebuild` command _fastlane_ is running. I can help you find that in the output, and then my next suggestion will be to run that command without _fastlane_ in the mix.

**Comment by derektlo** [comment]
https://gist.github.com/derektlo/f8428620350036f7162cbc8079f77ede

@mfurtak thank you so much.

**Comment by hjanuschka** [comment]
> error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.


hey @derektlo as the log shows can you try running (insider your project root, where `Podfile` is located)

```bash
pod install
```

**Comment by derektlo** [comment]
@hjanuschka thank you for the response. All my Pods are up-to-date though :/

Tried re-running `pod install` just in case. Here's the new Gist: https://gist.github.com/derektlo/a1088235bff08acbfc2c2cba42d31b7a

**Comment by PetrosIchor** [comment]
Looks like pods are still failing... There is a cocoapods action.  You might want to have it run with fastlane to ensure your installing them at build time?

I'm also inclined to blame the export_method flag.  I've never used it for my fastlane setup due to my apps configuration.

**Comment by derektlo** [comment]
So I should just remove the following from the `Fastfile`?

```
      export_method: options[:method],
    )
```

And how would I go about running it with fastlane?

Thanks again for all this help

**Comment by derektlo** [comment]
@PetrosIchor @hjanuschka Hi guys could I get an update on this by any chance? Thanks so much

**Comment by KrauseFx** [comment]
Did you try clearing your derived data directory?

**Comment by PetrosIchor** [comment]
Yeah, that's my next recommendation.

**Comment by derektlo** [comment]
Yes, I tried that. I've even tried doing a complete fresh clone and re-installing Fastlane. One of my teammates was able to deploy using `fastlane release` with the same exact repo. Any idea what this could be?

**Comment by pschneider** [comment]
Getting this error too.
- Removing `export_method` did not fix it for me.
- Automatic code sign is turned off and using distribution profile for my Production configuration (listed under eligible)


```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/developer/Library/Developer/Xcode/DerivedData/XXXXXXX-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/IntermediateBuildFilesPath/XXXXXXX.build/Production-iphoneos/XXXXXXX.build/Script-428D3768096288AF0AE66293.sh
    cd /Users/developer/Developer/XXXXXXXX
    /bin/sh -c /Users/developer/Library/Developer/Xcode/DerivedData/XXXXXX-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/IntermediateBuildFilesPath/XXXXXXX.build/Production-iphoneos/XXXXXXX.build/Script-428D3768096288AF0AE66293.sh
mkdir -p /Users/developer/Library/Developer/Xcode/DerivedData/Wearparts-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/BuildProductsPath/Production-iphoneos/XXXXXXXX.app/Frameworks
Symlinked...
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/developer/Library/Developer/Xcode/DerivedData/XXXXXX-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework" "/Users/developerl/Library/Developer/Xcode/DerivedData/XXXXXXX-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/InstallationBuildProductsLocation/Applications/XXXXXXX.app/Frameworks"
building file list ... done
Alamofire.framework/
Alamofire.framework/Alamofire
Alamofire.framework/Info.plist

sent 8807203 bytes  received 70 bytes  17614546.00 bytes/sec
total size is 8805889  speedup is 1.00


Code Signing /Users/developer/Library/Developer/Xcode/DerivedData/XXXXXX-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/InstallationBuildProductsLocation/Applications/XXXXXXX.app/Frameworks/Alamofire.framework with Identity iPhone Distribution: XXXXXXX (XXXXXXX)
/usr/bin/codesign --force --sign XXXXXXXXXXXX  --preserve-metadata=identifier,entitlements '/Users/developer/Library/Developer/Xcode/DerivedData/XXXXXXX-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/InstallationBuildProductsLocation/Applications/XXXXXXX.app/Frameworks/Alamofire.framework'
SecKey API returned: -25308, (null)/Users/developer/Library/Developer/Xcode/DerivedData/XXXXXXX-afjqsldntvpczjcefhrsrxeenkkp/Build/Intermediates/ArchiveIntermediates/production/InstallationBuildProductsLocation/Applications/XXXXXXX.app/Frameworks/Alamofire.framework: unknown error -1=ffffffffffffffff
```


lane:

```
lane :submit_testflight do |options|
    version_number = get_version_number(target: "XXXXXXX")
    build_number = get_build_number

    clear_derived_data
    clean_build_artifacts

    cocoapods(repo_update: true, clean: true)
    match(
      type:"appstore",
      readonly: true
    )
    gym(
      scheme: "production",
      clean: true,
      output_name: "XXXXXX-#{version_number}-#{build_number}.ipa",
      output_directory: "output/",
      include_bitcode: true,
      include_symbols: true,
      configuration: "Production",
    )
    testflight(
      distribute_external: false,
      beta_app_feedback_email: "XXXXXXX",
      team_id: "XXXXXXXX"
    )
  end
```

**Comment by pschneider** [comment]
Running `Archive` in Xcode manually once prompted me to allow access to an keychain key which I didn't allowed access manually previously. The Xcode archive succeeded.

After that I tried running the lane mentioned above and it finished successfully too. So it seems that somehow match installed the keychain items but `codesign` had no access to them which resulted in the error mentioned in my previous comment.

**Comment by Athosone** [comment]
I got the same error on my CI environment. On my local machine it works fine else it is exactly the same error.
I created a temporary keychain for match but the problem remains...

When it comes to:
`▸ Running script '[CP] Embed Pods Frameworks'
** ARCHIVE FAILED **
 
 
The following build commands failed:
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/admintfs/Library/Developer/Xcode/DerivedData/msheireb-belfivqweidsubadwzgwnbsmbfkq/Build/Intermediates/ArchiveIntermediates/wayfinding/IntermediateBuildFilesPath/msheireb.build/Release-iphoneos/wayfinding.build/Script-434BF36E44600C814A656523.sh
(1 failure)
ERROR [2017-03-30 17:44:04.56]: Exit status: 65`

**Comment by liamogierussell1** [comment]
Hey guys,

Hitting the same error here too. Just updated to Sierra and upgraded to the latest Fastlane, Gym, XCode etc so everything up to date. 

On my local machine all works as expected:
```PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/IntermediateBuildFilesPath/Example.build/Release-iphoneos/Example.build/Script-A732BBB2C5E061610E4BB936.sh
    cd /Users/lukemcdaid/Example-ios-property-config
    /bin/sh -c /Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/IntermediateBuildFilesPath/Example.build/Release-iphoneos/Example.build/Script-A732BBB2C5E061610E4BB936.sh
mkdir -p /Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/BuildProductsPath/Release-iphoneos/Example.app/Frameworks
Symlinked...
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AirlineConfiguration.framework" "/Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks"
building file list ... done
AirlineConfiguration.framework/
AirlineConfiguration.framework/AirlineConfiguration
AirlineConfiguration.framework/Info.plist
AirlineConfiguration.framework/Images.bundle/
AirlineConfiguration.framework/Images.bundle/Assets.car
AirlineConfiguration.framework/Images.bundle/Info.plist

sent 8046600 bytes  received 120 bytes  16093440.00 bytes/sec
total size is 8045183  speedup is 1.00
Code Signing /Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks/AirlineConfiguration.framework with Identity iPhone Distribution: Example Company LTD
/usr/bin/codesign --force --sign 0137D553748D488F831B0481FE19E6D8EBE36F20  --preserve-metadata=identifier,entitlements '/Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks/AirlineConfiguration.framework'
Symlinked...
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Aspects.framework" "/Users/lukemcdaid/Example-ios-property-config/DerivedData/Example/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks"
building file list ... done
Aspects.framework/
Aspects.framework/Aspects
Aspects.framework/Info.plist`
```


However on my build machine fails with the same error as above:
```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/IntermediateBuildFilesPath/Example.build/Debug-iphoneos/Example.build/Script-A732BBB2C5E061610E4BB936.sh
    cd /Users/jenkins/build/workspace/Example-ios-snapshot-automation-updates
    /bin/sh -c /Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/IntermediateBuildFilesPath/Example.build/Debug-iphoneos/Example.build/Script-A732BBB2C5E061610E4BB936.sh
mkdir -p /Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/BuildProductsPath/Debug-iphoneos/Example.app/Frameworks
Symlinked...
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AirlineConfiguration.framework" "/Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks"
building file list ... done
AirlineConfiguration.framework/
AirlineConfiguration.framework/AirlineConfiguration
AirlineConfiguration.framework/Info.plist
AirlineConfiguration.framework/Images.bundle/
AirlineConfiguration.framework/Images.bundle/Assets.car
AirlineConfiguration.framework/Images.bundle/Info.plist

sent 8046689 bytes  received 120 bytes  16093618.00 bytes/sec
total size is 8045271  speedup is 1.00
Code Signing /Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks/AirlineConfiguration.framework with Identity iPhone Distribution: Example Company LTD
/usr/bin/codesign --force --sign 0137D553748D488F831B0481FE19E6D8EBE36F20  --preserve-metadata=identifier,entitlements '/Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks/AirlineConfiguration.framework'
SecKey API returned: -25308, (null)/Users/jenkins/Library/Developer/Xcode/DerivedData/Example-cxwoeyupjxxzbnfayiatypvioaqr/Build/Intermediates/ArchiveIntermediates/Example/InstallationBuildProductsLocation/Applications/Example.app/Frameworks/Example.framework: unknown error -1=ffffffffffffffff
Command /bin/sh failed with exit code 1

```

Similar to the above comment, I am creating a temporary keychain and installing the certificate. Looking at the build machine I can see that this is correctly created and the cert successfully inserted. 

Also tried installing in the system keychain temporarily and unlocking it and get the same error.

Any ideas would be great, can't seem to find a way to fix this one.

Thanks,
Liam.

**Comment by Athosone** [comment]
same here still...

**Comment by AdrianZghibarta** [comment]
Same here

**Comment by AdrianZghibarta** [comment]
If someone uses CI tools as Jenkins with a slave Mac connected with ssh, you will have problems accessing keychain, so in your Jenkins script before `eval `ssh-agent -s`` add this line : `security unlock-keychain -p <yourPassword> login.keychain-db`, this will unlock keychain.

**Comment by ugenlik** [comment]
Same here, I get exact error as  @liamogierussell1  , exactly same setup.

before every build, I clear derived data and simulators.... 

Jenkins build slave to a mac mini, manually cloning repo to a directory and opening terminal and runing fastlane archives successfully. 

However whence Jenkins try to do the exact same thing, I get:

```
Running script [CP] Embed Pods Frameworks'
[Hugin] ** ARCHIVE FAILED **
[Hugin] 
[Hugin] 
[Hugin] The following build commands failed:
[Hugin] PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/IntermediateBuildFilesPath/Hugin.build/Release-iphoneos/Hugin.build/Script-70AF63783C1F53468CF3763A.sh
```

then checking log file I see: 

```
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/IntermediateBuildFilesPath/Hugin.build/Release-iphoneos/Hugin.build/Script-70AF63783C1F53468CF3763A.sh
    cd /Users/mhddeveloper/Workspace/workspace/iOS_Hugin/Hugin
    /bin/sh -c /Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/IntermediateBuildFilesPath/Hugin.build/Release-iphoneos/Hugin.build/Script-70AF63783C1F53468CF3763A.sh
mkdir -p /Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/BuildProductsPath/Release-iphoneos/Hugin.app/Frameworks
Symlinked...
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Alamofire.framework" "/Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/InstallationBuildProductsLocation/Applications/Hugin.app/Frameworks"
building file list ... done
Alamofire.framework/
Alamofire.framework/Alamofire
Alamofire.framework/Info.plist

sent 8284601 bytes  received 70 bytes  16569342.00 bytes/sec
total size is 8283348  speedup is 1.00
Code Signing /Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/InstallationBuildProductsLocation/Applications/Hugin.app/Frameworks/Alamofire.framework with Identity iPhone Distribution: XXXXXXXXX
/usr/bin/codesign --force --sign XXXXXXXXXX  --preserve-metadata=identifier,entitlements '/Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/InstallationBuildProductsLocation/Applications/Hugin.app/Frameworks/Alamofire.framework'
SecKey API returned: -25308, (null)/Users/mhddeveloper/Library/Developer/Xcode/DerivedData/Hugin-fsmtniwzaqbqbpccsrfbkzhfgxcj/Build/Intermediates/ArchiveIntermediates/Hugin/InstallationBuildProductsLocation/Applications/Hugin.app/Frameworks/Alamofire.framework: unknown error -1=ffffffffffffffff
Command /bin/sh failed with exit code 1
```` 

Looks like a code signing error happens at the last stage of Run Script Phases which happens to be 

cocoapods `[CP] Embed Pods Frameworks`

**Comment by AdrianZghibarta** [comment]
@ugenlik , in my opinion this problem occurs when the build script needs to access the certificates from the keychain. I had the same problem and unlocking the keychain and the beginning of the jenkins scripts that makes that starts the build resolved the issue.
So.. in your Jenkins script before `eval 'ssh-agent -s'` add this line : `security unlock-keychain -p <yourMacMiniUserPassword> login.keychain-db`, this will unlock keychain.

**Comment by Athosone** [comment]
Can't we just bypass this login.keychain by using a custom one which would be created before gym steps ?

**Comment by ugenlik** [comment]
@AdrianZghibarta that solution doesnt do anything for me.... 

@Athosone  I have solved this by moving Distribution profile from Login to System in keychain. 

Looks like Jenkin couldn't access it, because that line in Log stated that `with Identity iPhone Distribution: XXXXXXXXX`

So dragging that profile to System in keychain solved this....

**Comment by ugenlik** [comment]
Update:  moving certificate to System in keychain only worked a couple of times. 
adding the following before `gym` worked for me

```
    unlock_keychain(path:"login.keychain", password:"password")
    sh "security set-keychain-settings -t 3600 -l ~/Library/Keychains/login.keychain"
```

**Comment by KrauseFx** [comment]
Hey everyone, thanks for sharing your setups and outputs, however I see various completely different errors that shouldn't be mixed. Please submit a new issue if you're having build problems. 

**Please make sure you can successfully build using Xcode** before you submit an issue 👍 Always share your Fastfile, _fastlane_ output and the complete Xcode build log, so we can help you  🚀

Thanks
