### ISSUE TITLE
Gradle apk output path is not set when executing multiple tasks

### ISSUE THREAD

**Issue by iONsky** [fastlane/fastlane#7874]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I use the gradle action to build my android apps. Since the gradle action actually supports only one task I use a little workaround (maybe I shouldn't do this?) and chain the tasks together as a string eg. `clean test assemble`.

I expected that the gradle action would fill the `GRADLE_APK_OUTPUT_PATH` variable but it's never set.
After a little digging I figured out that if I only execute the `assemble` task the variable is set.

If this is indeed a bug and you guys need help I would look into it and try to fix it.

##### Complete output when running fastlane, including the stack trace and command used
>...
> --- Step: Gradle ---
>[11:29:01]: $ /Users/Test/Development/android-test/Test/gradlew clean test assemble -p ./Test/
>[11:29:06]: ▸ :app:clean
...
[11:29:14]: ▸ :app:test
...
[11:29:26]: ▸ :app:assemble
[11:29:27]: ▸ BUILD SUCCESSFUL
[11:29:27]: ▸ Total time: 25.432 secs
[11:29:27]: APK
+---------------------------------+------------------+
|                    Lane Context                    |
+---------------------------------+------------------+
| DEFAULT_PLATFORM                | android          |
| PLATFORM_NAME                   | android          |
| LANE_NAME                       | android internal |
+---------------------------------+------------------+`
>...

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.rbenv/versions/2.2.3/bin/fastlane        |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.2.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2d 9 Jul 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.63.1"

default_platform :android

platform :android do

  lane :build do
    gradle(task: "clean test assemble")
    UI.message "APK #{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.8.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.1       |
| json                      | 1.8.3        |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-01-16**
</details>

**Comment by hjanuschka** [comment]
@iONsky this has been fixed by https://github.com/fastlane/fastlane/pull/7845 and should be in the next release.

**Comment by iONsky** [comment]
@hjanuschka That's awesome 👍 
Thanks.

**Comment by mfurtak** [comment]
This has gone out as part of [_fastlane_ 2.9.0](https://github.com/fastlane/fastlane/releases/tag/2.9.0) 🚀
