### ISSUE TITLE
setup_jenkins print keychain password

### ISSUE THREAD

**Issue by thasegaw** [fastlane/fastlane#7879]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The setup_jenkins action print keychain password.
I'd like to hide or mask it.
```
$ fastlane run setup_jenkins force:true keychain_password:hogehoge
[23:25:51]: ---------------------------
[23:25:51]: --- Step: setup_jenkins ---
[23:25:51]: ---------------------------

+-----------------------------+-----------------+
|       Summary for Setup Jenkins Action        |
+-----------------------------+-----------------+
| force                       | true            |
| keychain_password           | hogehoge        |
| unlock_keychain             | true            |
| add_keychain_to_search_list | replace         |
| set_default_keychain        | true            |
| set_code_signing_identity   | true            |
| output_directory            | ./output        |
| derived_data_path           | ./derivedData   |
| result_bundle               | true            |
+-----------------------------+-----------------+

[23:25:51]: Set output directory path to: "/Library/Ruby/Gems/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/actions/output".
[23:25:51]: Set derived data path to: "/Library/Ruby/Gems/2.0.0/gems/fastlane-2.8.0/fastlane/lib/fastlane/actions/derivedData".
[23:25:51]: Set result bundle.
[23:25:51]: Result: YES
```

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1212)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ja_JP.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.8.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.4        |
| activesupport             | 4.2.6        |
| colored                   | 1.2          |
| claide                    | 0.9.1        |
| xcodeproj                 | 0.28.2       |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.11.2       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.7.1        |
| google-api-client         | 0.9.4        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.2        |
</details>

*generated on:* **2017-01-16**
</details>

**Comment by hjanuschka** [comment]
@thasegaw thx for the issue, i did a PR here: https://github.com/fastlane/fastlane/pull/7880 which should adress this.

**Comment by thasegaw** [comment]
@hjanuschka thank you! Looks good to me 👍

**Comment by asfalcone** [comment]
The PR has been merged and shipped so I'm going to close this out 🎉
