### ISSUE TITLE
Gym without XCode project/workspace file - Xamarin build support?

### ISSUE THREAD

**Issue by swirek** [fastlane/fastlane#7882]
I'm building a Xamarin iOS project using Xamarin-specific tools and the result of that operation is an archive (.xcarchive). I'd like to use Gym to generate IPA from the archive, however it looks like Gym expects to get XCode project or workspace as an input, even when using option skip_build_archive. With Xamarin there is typically no XCode project in the repository (although it could probably be generated from the command line, but I'd like to avoid that).
You might ask know: what's the point of using Gym, why not just xcodebuild action? So the reason is that Gym has build in support to fix Ruby issue by using xcbuild-safe.sh script internally, but xcodebuild action does not follow the same idea - it just runs xcodebuild command.

Is there a chance Gym could work without XCode project/workspace OR xcodebuild action used xcbuild-safe.sh script under the hood? Thanks!

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.4.5                           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.8.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build the application"
  lane :build do
    #sh('xbuild /p:Configuration=Release /p:Platform=iPhone /p:ArchiveOnBuild=true /t:"Build" ../src/Express.iOS/Express.iOS.csproj')
    #gym(export_team_id: "",export_method: "development", include_symbols: true, skip_build_archive: true, archive_path: "Express.iOS.xcarchive", output_name: "Express.iOS.ipa", output_directory: ".")

    buildCounter = 0
    if ENV["build.counter"]
      buildCounter = ENV["build.counter"]
      puts "Using build counter from environment: #{buildCounter}"
    else 
      puts "Using default build counter: #{buildCounter}"
    end

    sh 'nuget restore ../src/ExpressMobile.sln'
    sh '"/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" build "--configuration:Release|iPhone" ../src/ExpressMobile.sln'
    sh '"/Applications/Xamarin Studio.app/Contents/MacOS/mdtool" archive -p:Express.iOS "--configuration:Release|iPhone" ../src/ExpressMobile.sln'
    sh "bash ./copy_archive.sh"
    sh "/usr/libexec/PlistBuddy -c \"Set :ApplicationProperties:CFBundleShortVersionString 0.1.#{buildCounter}.0\" ../Express.iOS.xcarchive/Info.plist"
    cert(development: true, username: "aswierczek@infusion.com", team_id: "55UP4C5855")
    sigh(development: true, provisioning_name: "Express Dev")
    sh 'bash ./xcbuild-safe.sh -exportArchive -verbose -exportOptionsPlist "exportPlist.plist" -archivePath "../Express.iOS.xcarchive" -exportPath "../"'
    zip(path: "Express.iOS.xcarchive/dSYMs/Express.iOS.app.dSYM", output_path: "../../Express.iOS.app.dSYM.zip")
    hockey(public_identifier: "11229d026c79441ebacd6e6112d04315", dsym: "Express.iOS.app.dSYM.zip", api_token: "a78342626bc143bbb68aed69061e4859", ipa: "Express.iOS.ipa")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.infusion.Express.iOS" # The bundle identifier of your app
apple_id "aswierczek@infusion.com" # Your Apple email address

team_id "55UP4C5855"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.8.0   | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2017-01-18**
</details>

**Comment by pperera** [comment]
I suspect Gym is too tightly coupled to xcode builds, theres a plugin for Xamarin builds which for now deals with most of the simple cases that gym would be used for.

https://github.com/punksta/fastlane-plugin-xamarin_build

which seems to work though mdtool rather than mono's xbuild (I haven't found a plugin yet that does this using xbuild, might fork + PR)

**Comment by swirek** [comment]
Didn't know about the plugin, thanks! I was able to get my script running with mdtool and xcodebuild command, the only drawback is that I need to keep a copy of xcbuild-safe.sh in my repo to fix ruby environment issues.
I think I'll stick to my custom script for now as my case is a bit complex and I'm afraid the plugin would not work for my case.
