### ISSUE TITLE
Setup `fastlane beta` gets stuck on "Generating Your Fastfile"

### ISSUE THREAD

**Issue by PaulMest** [fastlane/fastlane#7884]
### New Issue Checklist

- [x] Updated fastlane to the latest version [2.9.0]
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to setup `fastlane beta` to work with my Xcode (React Native) application. I tried following the instructions a few times over the past couple of weeks and it always gets stuck on step 3 (Generating Your Fastfile):
![image](https://cloud.githubusercontent.com/assets/1721104/22009038/2aacac50-dc35-11e6-894d-93c5d39b4e9b.png)

Any idea how I could diagnose the problem?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.2                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.11.0                              |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.2 (16C67)                        |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.2.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
</details>

*generated on:* **2017-01-17**
</details>

**Comment by PaulMest** [comment]
Added `fastlane env` output.

**Comment by usmanmcs** [comment]
I am having the same issue, did you find any solution for this?

**Comment by PaulMest** [comment]
@usmanmcs No. I am still having the issue even after upgrading to 2.10

**Comment by mpirri** [comment]
@PaulMest & @usmanmcs Sorry for the delay in getting back to you about this.  The Fabric Mac app is generally not supported by the `fastlane` community, but I'm happy to help you with it!

Do you mind sending me some logs? Here's what I'd need you to do:
- Quit & Relaunch the Fabric Mac app
- Go through the `fastlane beta` setup process again. If you need a direct link to the process, go to the `fastlane` tab, then click `Get Started` next to `Distribute Beta Builds`.
- Once you get to the hang on step 3, let it run for a while.
- In the Finder, choose `Go->Go To Folder…` and enter this directory path:
`~/Library/Caches/com.crashlytics.data/com.crashlytics.mac/v3/`
- In that directory, zip up the contents of the `active` directory

You can email these zip'd logs to me at the email address listed on my profile. If you are not comfortable sending the logs to my email address, you can contact Fabric tech support directory and include the logs there and they can help you out.

**Comment by 3DTOPO** [comment]
I am having the same issue with fastlane 2.10.0 installed. Also, I don't have a com.crashlytics.mac/v3/ folder, mine is com.crashlytics.mac/v2/ and after letting it run for a half an hour or so, the only file in that directory is called 'crash_metadata' that is only 591 bytes. Those bytes are (I changed the API key to protect my privacy):

{"bundle_id":"com.crashlytics.mac","session_id":"cecaa62ed5604fc7bbaf16348f529a55","advertising_tracking_enabled":false,"locale":"en_US","os_build":"15G1004","links_ad_support":false,"platform":"Mac","generator":"Answers Mac SDK\/1.3.3","platform_code":0,"cores":12,"instance_id":"9fa50db743937604bf9b914401ff9cd0c61fc9fd","install_id":"20EE4271-F146-4CA6-ABD5-6FBB7D1D0C88","jailbroken":false,"model":"MacPro3,1","os_version":"10.11.6","started_at":1487734038,"bundle_version":"1273","api_key":"5g91ebza4a214417dg6321952dh46816242817tw","machine":"MacPro3,1","bundle_short_version":"2.6.6"}

**Comment by mpirri** [comment]
@3DTOPO This looks like the contents of the `analytics` directory. Is there no `v3` directory at the same level as the `analytics` directory?

Try quitting the Fabric Mac app, deleting the `~/Library/Caches/com.crashlytics.data/com.crashlytics.mac` directory and then trying again.

Thanks for looking into this!

**Comment by ambarc** [comment]
Near identical repro with Fastlane 2.15.0 and the Fabric Mac app.

**Comment by PaulMest** [comment]
Thanks for the reminder @fastlane-bot. I just submitted my logs to @mpirri via email.

**Comment by ohayon** [comment]
Hey @PaulMest apologies for the delay here! If you are still running into this issue, I think the best course of action to get working as quickly as possible would be to run `fastlane init beta` from the command line inside your project's directory and follow the prompts there. That should get you set up for deploying betas right away! 🐙 🚀  We are going to look into your logs and see whats going on though!

**Comment by nathan-fiscaletti** [comment]
I'm experiencing this same issue with the latest versions of both FastLane and Fabric
