### ISSUE TITLE
Spaceship `all` always filters out Xcode managed profiles

### ISSUE THREAD

**Issue by Ashton-W** [fastlane/fastlane#7885]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to use **spaceship** to download the provisioning profiles managed by Xcode, but those profiles are always filtered out when accessed through `all`.

I propose adding an optional flag to `all()` to include Xcode profiles.

**Comment by KrauseFx** [comment]
Cool, thanks, let's close this issue as we have a PR now that's about to be merged 👍
