### ISSUE TITLE
Clear Xcode Archives

### ISSUE THREAD

**Issue by natemann** [fastlane/fastlane#7888]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Every time Xcode archives an app, it creates a .xcarchive file in ~/Library/Developer/Xcode/Archives. This folder can get rather large over time. I would like the ability to deletes these files with a fastlane command (similar to clearing derived data).

**Comment by hjanuschka** [comment]
i am not sure if there is an existing fastlane action for that, but you can always shell out.
i do this in my fastfile on the ci machines (to clean archives):

```
sh(command: "rm -vfr ~/Library/Developer/Xcode/Archives/*")
```

let me know if this helps you.

**Comment by PetrosIchor** [comment]
Piggy backing on what hjanuschka said, I have a job running monthly that backs up then removes any older than 90 days. For my setup, having removal per build or scripted into fastlane another way was a bit overkill considering how infrequently it becomes an issue.

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up from the author.
