### ISSUE TITLE
Snapshot migration

### ISSUE THREAD

**Issue by jacao** [fastlane/fastlane#789]
Does migrating to snapshot 1.0.0, mean that snapshot.js cannot be used anymore? Or does it have to be done natively using UITests now?

Are there any params that can be used to enable the use of this still?

**Comment by KrauseFx** [comment]
There are no plans on keeping/maintaining the UI Automation support, see the [Release Notes](https://github.com/fastlane/snapshot/releases/tag/1.0.0), in particular the [Migration Guide](https://github.com/fastlane/snapshot/blob/master/MigrationGuide.md)

**Comment by jacao** [comment]
Ok thanks
