### ISSUE TITLE
Cannot install using `brew gem`

### ISSUE THREAD

**Issue by lkraider** [fastlane/fastlane#7895]
When using a the `brew gem` tool to install fastlane, the resulting installation cannot be used because of the way fastlane does its import of gems:

`$LOAD_PATH.push File.expand_path("../../lib", __FILE__)`

and brew gem cannot figure out the gems that fastlane requires, failing on runtime.

See: https://github.com/sportngin/brew-gem/issues/40

**Comment by KrauseFx** [comment]
What are you trying to do? You can install fastlane either using `gem install fastlane`, or using `brew cask install fastlane` or via [download.fastlane.tools](https://download.fastlane.tools)

**Comment by lkraider** [comment]
Brew gem allows to install "any" gem as a separate formula (well, at least until I tried fastlane):
`brew install brew-gem`
`brew gem install fastlane --homebrew-ruby`

The question is more about the require mechanism, is fastlane using some non-standard wizardry or is that a normal functionality gems usually deploy?

**Comment by KrauseFx** [comment]
We don't use any non-standard things as far as I know.

**Comment by KrauseFx** [comment]
I'll close this for now, as we have 3 different methods of installing and don't plan on adding another one 👍

**Comment by lkraider** [comment]
Understood, thanks for the feedback.
