### ISSUE TITLE
Fastlane has a misleading error when unable to find a variable

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#7899]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am setting up a variable in a lane, and trying to access it in the `error` handler. It fails with a misleading error:
```
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Could not find action or lane 'foo'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane (FastlaneCore::Interface::FastlaneError)
	from /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/ui.rb:1
```
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `test1`
<details><summary>Output/Log</summary>

```

DEBUG [2017-01-18 09:02:17.22]: Checking if there are any plugins that should be loaded...
INFO [2017-01-18 09:02:17.23]: Driving the lane 'test1' 🚀
DEBUG [2017-01-18 09:02:17.23]: /Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:142:in `trigger_action_by_name'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:12:in `block in parsing_binding'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:64:in `call'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:64:in `block in execute'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:59:in `chdir'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:59:in `rescue in execute'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:44:in `execute'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
/Users/lacostej/.rvm/gems/ruby-2.2.2/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
/Users/lacostej/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `load'
/Users/lacostej/.rvm/gems/ruby-2.2.2/bin/fastlane:23:in `<main>'
/Users/lacostej/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
/Users/lacostej/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
WARN [2017-01-18 09:02:17.23]: Lane Context:
INFO [2017-01-18 09:02:17.23]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"test1"}
ERROR [2017-01-18 09:02:17.23]: Could not find action or lane 'foo'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane
INFO [2017-01-18 09:02:17.23]: Successfully generated documentation at path '/Users/lacostej/Code/OSS/Fastlane/fastlane/TMP/fastlane/README.md'
ERROR [2017-01-18 09:02:17.23]: fastlane finished with errors


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.11.6                                           |
| Ruby                | 2.2.2                                             |
| Bundler?            | true                                              |
| Git                 | git version 2.5.0                                 |
| Installation Source | ~/.rvm/gems/ruby-2.2.2/bin/fastlane               |
| Host                | Mac OS X 10.11.6 (15G31)                          |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.2/lib                      |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                        |
| Is contained        | false                                             |
| Xcode Path          | /Applications/Xcode-7.3.1.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :test1 do
  foo = "1"
  raise "Faked error"
end

lane :test2 do
  foo = "2"
  raise "Faked error"
end

error do |lane, exception|
  puts "CHANNEL: #{foo}"
end

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.2        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| xcode-install             | 2.1.0        |
</details>

*generated on:* **2017-01-18**
</details>

**Comment by hjanuschka** [comment]
i think that this is expected behaviour, as the variables are scoped to the block/lane.
(if you set the variable outside the lane, on top of fastfile, it should work)

and the error results from: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/runner.rb#L114 as it try's to resolve the variable as a action name.

not sure if this is fixable - or detectable that you requested a variable.

**Comment by mfurtak** [comment]
I agree with @hjanuschka that it is expected for this usage to fail, however, perhaps what @lacostej is saying is that the error message is misleading?

@lacostej Can you update your issue description with what you think the expected behavior should be?

**Comment by lacostej** [comment]
@mfurtak @hjanuschka yes the error was misleading to me. Not sure if we want to address it.

Maybe `"Could not find action, lane or variable 'foo'."`

**Comment by hjanuschka** [comment]
@lacostej `or variable`  sounds good to me.

**Comment by mfurtak** [comment]
Sounds good!

**Comment by KrauseFx** [comment]
At least the link is wrong too https://github.com/fastlane/fastlane/tree/master/fastlane, we should link to docs.fastlane.tools/actions

**Comment by ohayon** [comment]
Closing this as it appears to have been solved? 👍 🐙
