### ISSUE TITLE
Team City Integration

### ISSUE THREAD

**Issue by KingOfBrian** [fastlane/fastlane#790]
Hey @KrauseFx ,
    I'd like to work on team city integration, but how to add support isn't so clear cut. It's not as much an Action as adding a number of log messages as existing actions are performed.

For instance:

1. When the build number is set:

    `puts "##teamcity[buildNumber '<build_number>'"`

2. When junit files are generated:

    `puts  "##teamcity[importData type='junit' path='<path>'`

3. When an artifact is generated:

    `puts "##teamcity[publishArtifacts '<path>']"`

The build number is easy, but the other two are a bit trickier.

I see a few approaches that could work:

1. A more formal contract like `add_artifact(path, context_variable)` and `add_build_log(path)` added to Action. Actions would use this API and 3rd party integrations could be added via another API

2. A pre-post lane action that would look for changes in lane_context, and if they matched a certain set of keys, trigger the integration. Then add some lane variables for junit output.

3. Add support by hand for each test runner and builder, but that seems like a fragile approach. 

Any preferences? I think approach 2 is probably the least invasive integration, but I think approach 1 may help add other features.

**Comment by ohwutup** [comment]
Hey @KingOfBrian, this is a great idea but I am going to close it for now and mark it as a feature request. If you would like to submit a PR with any of those approaches we would be more than happy to review and help out! Otherwise we will reopen this issue when we get a chance to tackle this for a later release. 

Thanks! :ocean:
