### ISSUE TITLE
Failed to run any line

### ISSUE THREAD

**Issue by vkaramov** [fastlane/fastlane#7900]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I updated my Fastlane installation via 'sudo gem update fastlane' from 1.111 to 2.5 and then to 2.9.
After trying to run any lane I've got an error.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

vkaramov@Mac-mini-Viacheslav:~/Desktop/fastlane$ fastlane ios exp
+-------------------------+---------+---------+
|                Used plugins                 |
+-------------------------+---------+---------+
| Plugin                  | Version | Action  |
+-------------------------+---------+---------+
| fastlane-plugin-trainer | 0.2.0   | trainer |
+-------------------------+---------+---------+

[12:27:31]: -------------------------------------------------
[12:27:31]: --- Step: Verifying required fastlane version ---
[12:27:31]: -------------------------------------------------
[12:27:31]: Your fastlane version 2.9.0 matches the minimum requirement of 1.106.2  ✅
[12:27:31]: ------------------------------
[12:27:31]: --- Step: default_platform ---
[12:27:31]: ------------------------------
[12:27:31]: Driving the lane 'ios exp' 🚀
Hello from Fastlane!/Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate fastlane_core-0.58.0, because rubyzip-1.2.0 conflicts with rubyzip (~> 1.1.6) (Gem::ConflictError)
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1408:in `activate'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:97:in `print_table'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:79:in `finish_fastlane'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:68:in `cruise_lane'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/vkaramov/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
	from /Users/vkaramov/.rbenv/versions/2.3.1/bin/fastlane:22:in `load'
	from /Users/vkaramov/.rbenv/versions/2.3.1/bin/fastlane:22:in `<main>'
vkaramov@Mac-mini-Viacheslav:~/Desktop/fastlane$ 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | ru_RU.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.106.2"
skip_docs
default_platform :ios

platform :ios do


	before_all do		
	end

	desc "Experimental!!!"
	lane :exp do
		print "Hello from Fastlane!"

	end

	after_all do |lane|
	end

	error do |lane, exception|
		UI.error("Fastlane '#{lane}' errored")
	end
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status      |
| ----------------------- | ------- | ------------------ |
| fastlane-plugin-trainer | 0.2.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.1        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
| trainer                   | 0.3.0        |
| fastlane-plugin-trainer   | 0.2.0        |
</details>

*generated on:* **2017-01-18**
</details>

**Comment by hjanuschka** [comment]
seems like you still have gems installed before fastlane switched to a monogem
could you try running:

```bash
gem uninstall fastlane_core
```

and retry?

**Comment by vkaramov** [comment]
I just installed ruby 2.4.0 and set it as global ruby.
Then install/uninstall fastlane and it works fine now.

**Comment by hjanuschka** [comment]
@vkaramov awesome 🚀
