### ISSUE TITLE
undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007ffb208656a0>

### ISSUE THREAD

**Issue by prasadbewakoof** [fastlane/fastlane#7901]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[17:02:37]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[17:02:37]: -------------------------------------------------
[17:02:37]: --- Step: Verifying required fastlane version ---
[17:02:37]: -------------------------------------------------
[17:02:37]: Your fastlane version 2.9.0 matches the minimum requirement of 2.9.0  ✅
[17:02:37]: ------------------------------
[17:02:37]: --- Step: default_platform ---
[17:02:37]: ------------------------------
[17:02:37]: Driving the lane 'ios beta' 🚀
[17:02:37]: -----------------------
[17:02:37]: --- Step: cocoapods ---
[17:02:37]: -----------------------
[17:02:38]: Installing Ruby gem 'cocoapods'...
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[17:02:45]: undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007ffb208656a0>

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | cocoapods                           | 7           |
+------+-------------------------------------+-------------+

[17:02:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

🔗 You can ⌘ + double-click on links to open them directly in your browser.
/Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed': [!] undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007ffb208656a0> (NoMethodError)
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/helper/gem_helper.rb:7:in `verify_gem!'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/actions/cocoapods.rb:5:in `run'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:21:in `block (2 levels) in parsing_binding'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:255:in `call'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:255:in `execute_flow_block'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/prasad/.rvm/gems/ruby-2.3.1@global/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12                                                          |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.6.2                                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12 (16A323)                                        |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane
ENV['DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS'] = '-t DAV'
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version “2.9.0”

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Example”,
        project: './ios/Example.xcworkspace’
	) # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Example",
        project: './ios/Example.xcworkspace’) # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
</details>

*generated on:* **2017-01-18**
</details>

**Comment by hjanuschka** [comment]
can you try installing fastlane via `brew` or the `installer` as reffered here: https://github.com/fastlane/fastlane#installation

if you use the gem version you should use rvm/rbenv - to get arround alot of ruby issues with the apple shipped one.

**Comment by prasadbewakoof** [comment]
lane :beta do
  cert
  sigh
  gym
end

**Comment by RuiAAPeres** [comment]
@prasadbewakoof what did solve your issue?

**Comment by zoufishanmehdi** [comment]
@prasadbewakoof @RuiAAPeres I'm facing the same issue. What's the best way to resolve this?

**Comment by KrauseFx** [comment]
I replied over there: https://github.com/fastlane/fastlane/issues/8290#issuecomment-280821763

Let me know if that works 👍
