### ISSUE TITLE
Select build for edit app version 

### ISSUE THREAD

**Issue by KondrikA** [fastlane/fastlane#7902]
Hi

If I use something from this:
    fastlane deliver submit_build --build_number XXX
or
    submit_for_review: true

This will only lead to the selection of the build (YYYYYYY.ipa) for edit-version or version will be sent to Apple Review?
How i can select build for edit app version without send for review?

**Comment by hjanuschka** [comment]
this is right now not supported from deliver as `submit_build` forces a submit_for_review

but anyway you can do this with spaceship (which you can directly from your fastfile/lane):


```ruby
Spaceship::Tunes.login
app = Spaceship::Tunes::Application.find("my.app.id")
version = app.edit_version

# to submit latest build do it with this
# use_build = version.candidate_builds.first

# for specific build_number use this.
use_build = version.candidate_builds.find(build_version: "BUILD_NR").first
version.select_build(use_build)
# optional enable beta testing
version.can_beta_test = true
version.save!
```

**Comment by KondrikA** [comment]
Thank you. I have everything turned out.

====== Fastfile ======
fastlane_require "spaceship"
...
lane :use_last_build do
    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find("com.MYAPP.MYAPP")
    puts( "app.all_processing_builds.count:" + app.all_processing_builds.count.to_s  )

    $i = 0
    $num = 60
    while $i < $num  do
      puts("wait for processing build..... iterate #i = #$i" )
      $i +=1
      if app.all_processing_builds.count == 0 then
          puts("no processing buils! it's ok")
          break
      end
      if $i == 60 then
        raise "Apple processing too long. You must select build manualy in iTunesConnect"
      end;
      sleep(20)
    end

    version = app.edit_version
    use_build = version.candidate_builds.first

    puts("")
    puts("SELECTED BUILD VERSION: " + use_build.build_version)
    puts("use_build.ready_to_install: " + use_build.ready_to_install.to_s)
    puts("use_build.processing: " + use_build.processing.to_s)
    puts("use_build.valid: " + use_build.valid.to_s)

    version.select_build(use_build)
    version.save!
  end
