### ISSUE TITLE
Add/invite User to iTunesconnect and Apple Developer Center via CLI

### ISSUE THREAD

**Issue by max-ott** [fastlane/fastlane#7903]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Feature Request

It would be great if you could add users to your team both on iTunes Connect and Apple Developer Center via CLI/`spaceship`. Basically it should work like how `produce` works for apps.

**Comment by hjanuschka** [comment]
hey @max-ott  i have started working on it -> https://github.com/fastlane/fastlane/pull/7993
would be nice if you can give it a try and provide some feedback

**Comment by hjanuschka** [comment]
this has been merged and will be in one of the next releases!

**Comment by hjanuschka** [comment]
work on portal stuff has been started in #8047

**Comment by max-ott** [comment]
Looks amazing so far! That's exactly what we were looking for. Thanks @hjanuschka already!

**Comment by hjanuschka** [comment]
portal mgmt has been merged. will be in one of the next releases. i am going to close this issue now 👍  feel free to open a new one if you run into any issues.
