### ISSUE TITLE
Feature request: `launch_arguments` equivalent for screengrab

### ISSUE THREAD

**Issue by hblumberg** [fastlane/fastlane#7907]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
We have been working on automating screenshots of the Khan Academy Android app using screengrab. It would be very helpful to be able to provide additional arguments to instrumentation tests. This feature seems to be available for the screenshot tool with `launch_arguments`.

Ideally, we would add something like:
`launch_arguments ['-username hblumberg']`
to our `Screengrabfile` and would be able to access those arguments in our tests with something like:
`final String username = InstrumentationRegistry.getArguments().getString("username");`

Thank you so much for creating the screengrab tool - we're so excited to use it!

**Comment by hjanuschka** [comment]
@hblumberg thats a good idea, i did a PR: https://github.com/fastlane/fastlane/pull/7911 maybe you can give it a try and confirm that it works?

**Comment by KrauseFx** [comment]
Yeah 👍

**Comment by hblumberg** [comment]
Thank you so much for the incredibly quick response and PR! We look forward to using this feature!
