### ISSUE TITLE
This app contains an embedded provisioning profile that is not associated with your account

### ISSUE THREAD

**Issue by dPackumar** [fastlane/fastlane#7912]
### New Issue Checklist

- [Yes ] Updated fastlane to the latest version
- [ Yes] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We have a specific use case where in we have one source code which is a app which can be bought by customers with their names and configurations. So currently we have like 20 customers with different iTunesConnect accounts and their own version of the app. Issue is that when Jenkins builds it shows the following error,

This app contains an embedded provisioning profile that is not associated with your account.

This used to work fine before Xcode 8. Where in this used to be taken care by cert and Sigh and using different team ids and different fastfiles.

In Xcode 8 we use Manual signing option. Not sure how this can be fixed, as we used cert, sigh with proper Team ID and it should be taken care by it.

lane-

  lane :release do
   	team_id "XXXXXXXX"
    gym(
      workspace: "./APP.xcworkspace",
      configuration: "Alpha",
      scheme: "VIA",
      clean: true,
      silent: true,
      use_legacy_build_api: true
      #codesigning_identity: 'iOS WildCard AppStore Profile',
      #export_team_id: "XXXXXXX"
    )
    pilot(username: 'XXXXX', skip_submission: true, changelog: changelog_from_git_commits)
    reset_git_repo(files: ["App.xcodeproj/project.pbxproj"])
    clean_build_artifacts
  end

Fastlane version used is 2.9

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Invalid provisioning profile. This app contains an embedded provisioning profile that is not associated with your account. Please use a provisioning profile associated with Team ID XXXXXX.

Invalid Provisioning Profile. The UPP provisioning profile included in the bundle XXXXX [XXXX] is disallowed.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.13.6  |
| io-console                | 0.4.5   |
| slack-notifier            | 1.5.1   |
| xcpretty                  | 0.2.4   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| faraday-cookie_jar        | 0.0.6   |
| gh_inspector              | 1.0.2   |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| json                      | 2.0.2   |
| commander                 | 4.4.3   |
| excon                     | 0.54.0  |
| rubyzip                   | 1.2.0   |
| plist                     | 3.2.0   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| unicode-display_width     | 1.1.2   |
| terminal-table            | 1.7.3   |
</details>

*generated on:* **2017-01-19**
</details>

**Comment by PetrosIchor** [comment]
Xcode 8 added automatic signing and the provisioning profile specifier. You are probably hitting conflicts there with fastlane. 

Also, it sounds like your trying to use a wildcard for appstore signing which I believe isn't allowed. 

I also work with many apps and all the store accounts belong to the customer.  With xcode 8 I had to disable automatic signing and inject the provisioning, code signing identity, and team IDs to get moving again. 

Checkout the code signing guide, it's the easiest way to get some traction.  If your products design is similar to mine, you'll have to roll a more custom solution.  Alot of which can be handled with some of the plugins in fastlane.

**Comment by dPackumar** [comment]
@PetrosIchor  how are you injecting the provisioning, code signing identity, and team ID ? i expected specifying the team ID to take care of that as the Xcode as the provisioning profile needed created in Sigh step.

**Comment by PetrosIchor** [comment]
So there are a number of ways to do this. From my experience, if you update the team_id it will not disable the automatic signing. You'll then get a conflict because xcode is trying to build an application with automatic signing while a hard team_id is being specified. 

Couple of actions/plugins to checkout: 
[update_project_codesigning](https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning) Will disable automatic signing and inject a team_id at the same time. 

[update_provisioning_profile_specifier](https://github.com/faithfracture/update_provisioning_profile_specifier) Will inject a specific provisioning profile specifier to use for builds where automatic signing is disabled. Here you could use the sigh output variable instead of the specific specifier if you wanted too. 

There's also: 
[update_build_settings_key](https://github.com/ungacy/update_build_settings_key)
[update_project_team](https://docs.fastlane.tools/actions/#update_project_team)
[update_app_identifier](https://docs.fastlane.tools/actions/#update_app_identifier)
[update_xcodeproj](https://github.com/nafu/fastlane-plugin-update_xcodeproj)

Ultimately, I cracked open a number of those actions and plugins. Used some of their ideas to roll my own plugin that supports my project's needs.  Happy hunting.

**Comment by asfalcone** [comment]
Going to close this out since @PetrosIchor left some great comments with doc links that should solve the issue 👍
