### ISSUE TITLE
Gym doesn't select unicode scheme name

### ISSUE THREAD

**Issue by Wouter33** [fastlane/fastlane#7913]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
It looks like gym doesn't select the correct scheme automatically when unicode characters are being used in the scheme name. 

##### Complete output when running fastlane, including the stack trace and command used
[10:33:54]: Couldn't find specified scheme 'Nestlé Events'.
Select Scheme: 
1. Nestlé Events
2. Pods-Nestlé Events

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
default_platform :ios

  lane :build do |options|

    match(
        username: "***",
        app_identifier: options[:app_identifier],
        type: options[:type],
        git_url: "https://bitbucket.org/superevent/certificates"
    )

    ENV["FL_PROJECT_SIGNING_FORCE_UPGRADE"] = 'true'
    update_project_codesigning(path: "#{options[:project_path]}.xcodeproj", use_automatic_signing: false)

    if options[:type] == "adhoc"
        @profType = "AdHoc"
    elsif options[:type] == "development"
        @profType = "Development"
    elsif options[:type] == "appstore"
        @profType = "AppStore"
    end

    update_provisioning_profile_specifier(
        xcodeproj: "#{options[:project_path]}.xcodeproj",
        new_specifier: "***/match #{@profType} #{options[:app_identifier]}"
    )

    update_project_team(
        path: "#{options[:project_path]}.xcodeproj",
        teamid: "***"
    )

    if options[:type] == "adhoc"
        @gymType = "ad-hoc"
        @configuration = "Release"
    elsif options[:type] == "development"
        @gymType = "development"
        @configuration = "Debug"
    elsif options[:type] == "appstore"
        @gymType = "app-store"
        @configuration = "Release"
    end

    gym(
        scheme: options[:app_name],
        export_method: @gymType,
        workspace: "#{options[:project_path]}.xcworkspace",
        configuration: @configuration,
        output_directory: options[:output_directory],
        output_name: options[:output_name]
    )

    end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "***" # The bundle identifier of your app
apple_id "***" # Your Apple email address

team_id "***"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                                | Version | Update-Status |
| ----------------------------------------------------- | ------- | ------------- |
| fastlane-plugin-update_project_codesigning            | 0.1.7   | ✅ Up-To-Date  |
| fastlane-plugin-update_provisioning_profile_specifier | 1.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                                   | Version |
| ----------------------------------------------------- | ------- |
| did_you_mean                                          | 1.0.0   |
| slack-notifier                                        | 1.5.1   |
| rouge                                                 | 1.11.1  |
| xcpretty                                              | 0.2.4   |
| terminal-notifier                                     | 1.7.1   |
| terminal-table                                        | 1.4.5   |
| multipart-post                                        | 2.0.0   |
| word_wrap                                             | 1.0.0   |
| babosa                                                | 1.0.2   |
| colored                                               | 1.2     |
| excon                                                 | 0.54.0  |
| http-cookie                                           | 1.0.3   |
| faraday-cookie_jar                                    | 0.0.6   |
| fastimage                                             | 1.6.8   |
| gh_inspector                                          | 1.0.2   |
| highline                                              | 1.7.8   |
| json                                                  | 1.8.3   |
| mini_magick                                           | 4.5.1   |
| multi_json                                            | 1.12.1  |
| rubyzip                                               | 1.1.7   |
| security                                              | 0.1.3   |
| xcpretty-travis-formatter                             | 0.0.4   |
| dotenv                                                | 2.1.1   |
| bundler                                               | 1.13.5  |
| i18n                                                  | 0.7.0   |
| thread_safe                                           | 0.3.5   |
| tzinfo                                                | 1.2.2   |
| activesupport                                         | 4.2.7.1 |
| commander                                             | 4.4.1   |
| io-console                                            | 0.4.5   |
| plist                                                 | 3.2.0   |
| CFPropertyList                                        | 2.3.4   |
| claide                                                | 1.0.1   |
| nanaimo                                               | 0.2.3   |
| xcodeproj                                             | 1.4.1   |
| fastlane-plugin-update_project_codesigning            | 0.1.7   |
| fastlane-plugin-update_provisioning_profile_specifier | 1.2.0   |
</details>

*generated on:* **2017-01-19**
</details>

**Comment by hjanuschka** [comment]
right now this seems to be not supported, we had issues like this a time ago (with no solution)
https://github.com/fastlane/fastlane/issues/6974

the current approach should be to rename schemes and not include unicode characters

**Comment by Wouter33** [comment]
We always have two schemes in our apps. Maybe it could be a possibility to select the scheme number through a CLI option?

**Comment by hjanuschka** [comment]
@Wouter33 in fact i was able to use the above scheme name with this command inside my fastfile:

```ruby
lane :s do
	gym(scheme: "Nestlé Events", project:"gym/examples/standard/Example.xcodeproj")
end
```


who's calling your `build`  lane, can you share the command that call's this?
i suspect that you call it from shell like `fastlane build app_name:Nestlé Events` - this is kinda shell problem that is not solvable easily.

i see the following workarounds:

#option 1
put the `Nestlé Events`  in a seperate file. `scheme_name``
and inside your lane you do

```
gym(
  scheme: File.read(options[:app_name])
  .....
)
```
and call it with `fastlane build app_name:scheme_name`


# option2

do not call it via shell, use a fastlane lane as a helper.

# option3
just rename the scheme so it does  not contain any unicode characters (i presonally would go with this.)

**Comment by hjanuschka** [comment]
ohhh and now i see, seems to be your terminal is not configured for UTF8 - which the env output says. ensure that you have something like this set (before calling fastlane)

```bash
export LANG=en_US.UTF-8
```

**Comment by Wouter33** [comment]
Thanks for your research @hjanuschka! Unfortunately fixing the LANG var didn't fix the issue. It's probably because the name is provided by a CLI parameter indeed. I'll try to put it in a file and go from there. Thanks!

**Comment by hjanuschka** [comment]
@Wouter33 thx for feedback, i ll close the issue now, feel free to reopen/create a new one, if you have further questions.
