### ISSUE TITLE
[!] Could not find option for key :platform.

### ISSUE THREAD

**Issue by jpgarcia** [fastlane/fastlane#7918]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When running the following command:
```bash
produce create --username juan***@****.com --app_identifier com.xxx.xxx --app_name "*** App" --sku com.xxx.xxx --company_name "XXX, LLC"
```
I'm getting the following error:
`[!] Could not find option for key :platform. Available keys: username, app_identifier, bundle_identifier_suffix, app_name, app_version, sku, language, company_name, skip_itc, skip_devcenter, team_id, team_name, itc_team_id, itc_team_name`

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

produce does not allow me to include de `--capture_output` and it i run `fastlane produce` I get:

`produce can't be called via `fastlane produce`, run 'produce' directly instead`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.8.1                           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| google-api-client         | 0.9.20       |
| highline                  | 1.7.8        |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| json                      | 2.0.2        |
| commander                 | 4.4.3        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.0        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.2        |
</details>

*generated on:* **2017-01-19**
</details>

**Comment by hjanuschka** [comment]
since the migration to monogem you have to call the tools with fastlane prepended.


```
fastlane produce .....
```

**Comment by jpgarcia** [comment]
HI @hjanuschka as I mentioned in the issue if I run `fastlane produce...` I get the following error:

```bash
produce can't be called viafastlane produce, run 'produce' directly instead
```

**Comment by hjanuschka** [comment]
hmmm thats strange just tested it on my machine and i am able to do a produce with `fastlane produce`

do you have the old produce gem installed? can you try uninstalling it?

**Comment by jpgarcia** [comment]
nailed it! @hjanuschka thank you so much!
