### ISSUE TITLE
--submission_information - how to use?

### ISSUE THREAD

**Issue by markerpen** [fastlane/fastlane#7920]
Hi there,

I want to use `deliver` through the command line (not using a Deliverfile or Fastfile).

There's an option for `--submission_information`, and the docs say to provide a hash. I've tried the following but the Ruby script sees it as a string, rather than a hash. Any way to add these properties through the command line?

`fastlane deliver --username <USERNAME> --app_identifier <APP_ID> --ipa <IPA LOCATION> --submit_for_review --force --metadata_path <METADATA_PATH> --skip_screenshots --submission_information "{add_id_info_limits_tracking: true, add_id_info_serves_ads: true, add_id_info_tracks_action: true, add_id_info_tracks_install: true, add_id_info_uses_idfa: false, content_rights_has_rights: true, content_rights_contains_third_party_content: false, export_compliance_platform: 'ios', export_compliance_compliance_required: false, export_compliance_encryption_updated: false, export_compliance_app_type: nil, export_compliance_uses_encryption: false, export_compliance_is_exempt: false, export_compliance_contains_third_party_cryptography: false, export_compliance_contains_proprietary_cryptography: false,  export_compliance_available_on_french_store: false}" `

I get the following error after the app has been uploaded and metadata successfully changed:

`.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/deliver/lib/deliver/submit_for_review.rb:18:in `submit!': [!] undefined method `each' for #<String:0x007ff08145b108> (NoMethodError)`

**Comment by hjanuschka** [comment]
@markerpen  i am not sure if hash'es are supported on commandline.
what's the reason you cant use a fastfile and/or a deliverfile - maybe we find a way to solve your issues?

**Comment by markerpen** [comment]
Hi @hjanuschka thanks for the reply. I'm working on a non-standard setup (Xamarin on multiple Macs) and I'd like to keep my projects 'portable'. I'd use a deliverfile but there doesn't seem to be a way to get fastlane to choose an arbitary path for the deliverfile - since I'm using fastlane/deliver as part of a larger pipeline I need to use it via the command line.

Is there any way to make fast lane use an arbitary path for fast/deliverfiles?

**Comment by hjanuschka** [comment]
hey @markerpen 
ok i got you, i have pretty much the same requirements for my apps 👍 
my fastfile inside one app is usually has 4-6 lines .


i think you have the following options:

# import_from_git
this is my preffered solution for a situation like this.

create git repo (this has to be accessable by all consumers of the fastfile).
put a  `fastlane/Fastfile` in it.

in that "shared fastfile"  you define your lanes.
keep in mind to use variables for dynamic things.

e.g.:
"Shared" Fastfile:

```ruby
lane :beta do
   match(app_identifiers: $app_identifiers)
   gym(scheme: $app_scheme)
   deliver(submission_information: $submission_info)
end
```

and inside your projects Fastfile do it like this:

```ruby
$app_identifiers = ["demo.app", "demo.app.watchkitextension"]
$app_scheme = "Scheme"
$submission_info = {
..
..
}

import_from_git(url: "http://yourgitrepo.com/repo")
```

# use env vars

export MY_SUBMISSION_INFORMATION = "{add_id_info_limits_tracking: true, add_id_info_serves_ads: true, add_id_info_tracks_action: true, add_id_info_tracks_install: true, add_id_info_uses_idfa: false, content_rights_has_rights: true, content_rights_contains_third_party_content: false, export_compliance_platform: 'ios', export_compliance_compliance_required: false, export_compliance_encryption_updated: false, export_compliance_app_type: nil, export_compliance_uses_encryption: false, export_compliance_is_exempt: false, export_compliance_contains_third_party_cryptography: false, export_compliance_contains_proprietary_cryptography: false, export_compliance_available_on_french_store: false}"

Fastfile:

```ruby
deliver(submission_information: JSON.parse(ENV["MY_SUBMISSION_INFORMATION"]))
```

# hack around it 

before calling fastlane do a shell command:

```
echo "{add_id_info_limits_tracking: true, add_id_info_serves_ads: true, add_id_info_tracks_action: true, add_id_info_tracks_install: true, add_id_info_uses_idfa: false, content_rights_has_rights: true, content_rights_contains_third_party_content: false, export_compliance_platform: 'ios', export_compliance_compliance_required: false, export_compliance_encryption_updated: false, export_compliance_app_type: nil, export_compliance_uses_encryption: false, export_compliance_is_exempt: false, export_compliance_contains_third_party_cryptography: false, export_compliance_contains_proprietary_cryptography: false, export_compliance_available_on_french_store: false}" > this_app.json
```

inside your fastlane:

```ruby
deliver(submission_information: JSON.parse(File.read("this_app.json")))
```



all options have pro and cons (e.g.: global $ variables....) 
let me know if there is suitable way for you in the suggestions.


>Is there any way to make fast lane use an arbitary path for fast/deliverfiles?
i don't think so, but its a good idea.

**Comment by ohayon** [comment]
Going to close this issue for now as it seems like @hjanuschka's work around could be a great solution to the problem. Feel free to comment and keep conversation going here and we will reopen it if necessary! 🐙
