### ISSUE TITLE
Snapshot treats the Location Services icon as a loading indicator

### ISSUE THREAD

**Issue by CraigSiemens** [fastlane/fastlane#7924]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The logic that `waitForLoadingIndicatorToDisappear()` in `SnapshotHelper.swift` uses to determine if there is a loading indicator in the status bar gets a false positive when the Location Services icon is in the status bar.

It's looking for a view with size `{10, 20}` which is the same size as the Location Services icon.

This causes snapshot to just wait until the icon disappears, which it never will.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.95.0"

default_platform :ios

platform :ios do
  before_all do |lane, options|
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new stage build to crashlytics"
  lane :stage do |options|
    changelog = prompt(
      text: "Enter the change log: ",
      multi_line_end_keyword: "END"
    )

    pre_build
    sigh(adhoc: true)
    gym(
      export_method: "ad-hoc",
      configuration: "Stage"
    )
    crashlytics(
      groups: "internal-stage",
      notes: changelog
    ) unless options[:skip_deploy]
  end

  desc "Submit a new demo build to crashlytics"
  lane :demo do |options|
    changelog = prompt(
      text: "Enter the change log: ",
      multi_line_end_keyword: "END"
    )

    pre_build
    sigh(adhoc: true)
    gym(
      export_method: "ad-hoc",
      configuration: "Demo"
    )
    crashlytics(
      groups: "internal-demo",
      notes: changelog
    ) unless options[:skip_deploy]
  end

  desc "Deploy a new version to the App Store"
  lane :release do |options|
    pre_build
    sigh
    gym(configuration: "Release")
    deliver(force: true) unless options[:skip_deploy]
  end

  desc "Download the dsyms from iTunes Connect"
  lane :dsym do
    number = prompt(
      text: "What build number should be downloaded: "
    )
    download_dsyms(build_number: number)
    upload_symbols_to_crashlytics
  end

  # You can define as many lanes as you want
  private_lane :pre_build do |options|
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '60'
    ENV['CRASHLYTICS_API_TOKEN'] = '79cc0b55f4832a59da08b612e85fb956544f1743'
    ENV['CRASHLYTICS_BUILD_SECRET'] = 'b8e11890eb5d1e2188d8d9ddbc7cb4bbc7c5a65bc52e589d14182c7c878fd6fc'
    cocoapods
  end

  after_all do |lane|
    clean_build_artifacts
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
team_id "CAPGY363TW"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

for_lane :stage do
    app_identifier 'net.payload.PayloadApp-Stage'
end

for_lane :demo do
    app_identifier 'net.payload.PayloadApp-Demo'
end

for_lane :release do
    app_identifier 'net.payload.PayloadApp'
end

for_lane :dsym do
    app_identifier 'net.payload.PayloadApp'
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.12.5       |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.2        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-19**
</details>

**Comment by hjanuschka** [comment]
@CraigSiemens thats a nice catch. could you share a sample app - where there is a loading indicator so we can further work on it?

right now i am not sure on how to solve it, but maybe there something else than the `self.frame.size` we can check for the indicator. (class name or whatever)

**Comment by CraigSiemens** [comment]
I've thrown together a sample project that shows off the issue

https://github.com/CraigSiemens/SnapshotLocationServicesBug

> Issue can be shown by running the tests from Xcode with `⌘ + U` or by running snapshot
> 
> ```
> fastlane snapshot
> ```
> 
> The issue only occurs when the Geofence icon (hollow icon) is in the status bar since it has the same size as the network activity indicator.
> ```
> Other 0x600000179500: traits: 8388608, {{321.0, 0.0}, {10.0, 20.0}}, identifier: 'GeofenceLocationTrackingOn', label: 'Region tracking on'
> ```
> 
> The regular icon (solid icon) has a smaller size so the issue doesnt occur.
> ```
> Other 0x60000017a400: traits: 8388608, {{322.0, 0.0}, {9.0, 20.0}}, identifier: 'StandardLocationTrackingOn', label: 'Location tracking on'
> ```

**Comment by hjanuschka** [comment]
<img src='http://s2.quickmeme.com/img/51/5172847fbb49535e849f907e458b00072cc6ae78f07e6eba6368535af487d4bd.jpg'> 

thx for the brilliant sample, i am going to dive into!

**Comment by hjanuschka** [comment]
ok did a PR -> https://github.com/fastlane/fastlane/pull/7940 maybe you can give it a try, with the sample app it worked!
