### ISSUE TITLE
I think Fastlane::Action.shell_out_should_use_bundle_exec is bugged.

### ISSUE THREAD

**Issue by jcayzac** [fastlane/fastlane#7925]
Hi there,

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

I think there's a problem with `Fastlane::Action.shell_out_should_use_bundle_exec` and that it's not behaving the way it should.

In a test setup I have now, I'm installing fastlane in a bundle. Here's the (simplified) structure of the project:

```
+ Gemfile # has fastlane and a few other things
+ Dir/
\---+ fastlane
    \---+ Fastfile etc
```

The problem is that, when running `cd Dir && bundle exec fastlane`, `shell_out_should_use_bundle_exec` will try to find a Gemfile in the current directory (`Dir`) only, fail, and prevent all actions from executing through bundler. It's currently implemented this way:

```rb
File.exist?('Gemfile') && !Helper.contained_fastlane?
```

I believe it should be changed to something like this (loosely adapted from `Bundler::SharedHelpers::find_gemfile`):

```rb
if !Helper.contained_fastlane?
  given = ENV["BUNDLE_GEMFILE"] # If present, fastlane (or a parent process) was most likely invoked using bundle exec
  return true if given && !given.empty?

  previous = nil
  current  = File.expand_path(Pathname.pwd).untaint
  until !File.directory?(current) || current == previous
    filename = File.join(current, "Gemfile")
    return true if File.file?(filename)

    previous = current
    current = File.expand_path("..", current)
  end
end
return false
```

Am I wrong? If not, should I send a PR?

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.2                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | true                                            |
| Git                 | git version 2.11.0                              |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane            |
| Host                | Mac OS X 10.12.2 (16C67)                        |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                     |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode_8.2.app/Contents/Developer/ |
| Xcode Version       | 8.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage
default_platform :ios

platform :ios do
  desc 'Run all the tests'
  lane :tests do |options|
    cocoapods
    scan
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.7       |
| io-console                | 0.4.6        |
| rake                      | 12.0.0       |
| CFPropertyList            | 2.3.4        |
| ZenTest                   | 4.11.1       |
| RubyInline                | 3.12.4       |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| dotenv                    | 2.1.2        |
| osx_keychain              | 1.0.1        |
| cocoapods-keys            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.3.0        |
| xcode-install             | 2.1.0        |
</details>

*generated on:* **2017-01-20**
</details>

**Comment by jcayzac** [comment]
Environment, which I thought was not relevant to the issue but had the bot complain :)

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.2                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | true                                            |
| Git                 | git version 2.11.0                              |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane            |
| Host                | Mac OS X 10.12.2 (16C67)                        |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                     |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode_8.2.app/Contents/Developer/ |
| Xcode Version       | 8.2                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage
default_platform :ios

platform :ios do
  desc 'Run all the tests'
  lane :tests do |options|
    cocoapods
    scan
  end
end
# vim:syntax=ruby:et:sts=2:sw=2:ts=2:ff=unix:
```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.7       |
| io-console                | 0.4.6        |
| rake                      | 12.0.0       |
| CFPropertyList            | 2.3.4        |
| ZenTest                   | 4.11.1       |
| RubyInline                | 3.12.4       |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| dotenv                    | 2.1.2        |
| osx_keychain              | 1.0.1        |
| cocoapods-keys            | 2.0.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.3.0        |
| xcode-install             | 2.1.0        |
</details>


*generated on:* **2017-01-20**
</details>

**Comment by jcayzac** [comment]
I would gladly submit a PR, but it seems your unit tests make assumptions that don't match my Xcode preferences (my derived data is always in a `build` folder relative to the project). Any reason for enforcing that in the tests? 🤔 

```
Failures:

  1) Scan Scan::DetectValues fetches the path from the Xcode config
     Failure/Error: expect(derived_data).to match(%r{/.*Xcode/DerivedData/app-\w*$})

       expected "/Users/jcayzac/github/fastlane/fastlane/scan/examples/standard/build" to match /\/.*Xcode\/DerivedData\/app-\w*$/
       Diff:
       @@ -1,2 +1,2 @@
       -/\/.*Xcode\/DerivedData\/app-\w*$/
       +"/Users/jcayzac/github/fastlane/fastlane/scan/examples/standard/build"

     # ./scan/spec/detect_values_spec.rb:11:in `block (3 levels) in <top (required)>'
```

**Comment by KrauseFx** [comment]
I'll close this for now, let's continue the discussion on the PR 👍
