### ISSUE TITLE
Code signing is required for product type

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#7927]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have tried to build an app without open Xcode but each time i have tried to build the project i have got this error

**Code signing is required for product type 'Application' in SDK 'iOS 10.2'** 

Of course as soon I am opening Xcode setup manually it's working. I have recorded a video 

https://lookback.io/watch/p7doeg5Bhne9GWBhi

**Fastfile**

```
require 'dotenv'
Dotenv.load

lane :build do
 fastlane_require  'dotenv'
 update_info_plist( # update app identifier string
   plist_path: "LeanIOS/#{ENV['APP_NAME']}-Info.plist",
   app_identifier: ENV['APP_IDENTIFIER']
 )

  update_project_codesigning(path: "#{ENV['PROJECT_NAME']}.xcodeproj" ,
    use_automatic_signing: false)

  # create the app
  produce(
    app_identifier: ENV['APP_IDENTIFIER'],
    username: ENV['USERNAME'],
    app_name: ENV['APP_NAME'],
    skip_itc: true
  )

  match(type: ENV['MATCH_TYPE'] ,
       username: ENV['USERNAME'],
       app_identifier: ENV['APP_IDENTIFIER'] ,
       team_id: ENV['FASTLANE_TEAM_ID'],
      git_url: ENV['MATCH_GIT_URL'])

  gym(clean: true )
end
```

** env ***

```
USERNAME=bolo+fastlane@lobo.studio
FASTLANE_PASSWORD=####@
FASTLANE_TEAM_ID=#####
FASTLANE_ITC_TEAM_ID=####
MATCH_GIT_URL=https://github.com/lobo-studio/transporter_certificates
MATCH_TYPE=appstore
DEVELOPMENT_TEAM = ID
PROJECT_NAME=NAME
APP_IDENTIFIER=studio.lobo.demo
APP_NAME=Demo app
PROVISIONING_PROFILE_SPECIFIER=match AppStore studio.lobo.demo
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.8.1                           |
| Installation Source | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'dotenv'
Dotenv.load

lane :beta do
  match(type: ENV['MATCH_TYPE'] ,
       username: ENV['USERNAME'],
       app_identifier: ENV['APP_IDENTIFIER'] ,
       team_id: ENV['FASTLANE_TEAM_ID'],
      git_url: ENV['MATCH_GIT_URL'])
end


lane :build do
  #ENV['PROVISIONING_PROFILE_SPECIFIER']= "match AppStore me.themoji.app.release"
  gym
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-update_project_codesigning | 0.1.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| did_you_mean                               | 1.0.0        |
| io-console                                 | 0.4.5        |
| CFPropertyList                             | 2.3.4        |
| i18n                                       | 0.7.0        |
| json                                       | 1.8.6        |
| minitest                                   | 5.10.1       |
| thread_safe                                | 0.3.5        |
| tzinfo                                     | 1.2.2        |
| activesupport                              | 4.2.7.1      |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.0        |
| babosa                                     | 1.0.2        |
| bundler                                    | 1.13.6       |
| claide                                     | 1.0.1        |
| colored                                    | 1.2          |
| highline                                   | 1.7.8        |
| commander                                  | 4.4.3        |
| unf_ext                                    | 0.0.7.2      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20161129 |
| dotenv                                     | 2.1.2        |
| excon                                      | 0.54.0       |
| multipart-post                             | 2.0.0        |
| faraday                                    | 0.11.0       |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.11.0       |
| fastimage                                  | 2.0.1        |
| gh_inspector                               | 1.0.3        |
| jwt                                        | 1.5.6        |
| little-plugger                             | 1.1.4        |
| multi_json                                 | 1.12.1       |
| logging                                    | 2.1.0        |
| memoist                                    | 0.15.0       |
| os                                         | 0.9.6        |
| signet                                     | 0.7.3        |
| googleauth                                 | 0.5.1        |
| httpclient                                 | 2.8.3        |
| hurley                                     | 0.2          |
| mime-types-data                            | 3.2016.0521  |
| mime-types                                 | 3.1          |
| uber                                       | 0.0.15       |
| representable                              | 2.3.0        |
| retriable                                  | 2.1.0        |
| google-api-client                          | 0.9.20       |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| plist                                      | 3.2.0        |
| rubyzip                                    | 1.2.0        |
| security                                   | 0.1.3        |
| slack-notifier                             | 1.5.1        |
| terminal-notifier                          | 1.7.1        |
| terminal-table                             | 1.4.5        |
| word_wrap                                  | 1.0.0        |
| nanaimo                                    | 0.2.3        |
| xcodeproj                                  | 1.4.2        |
| rouge                                      | 1.11.1       |
| xcpretty                                   | 0.2.4        |
| xcpretty-travis-formatter                  | 0.0.4        |
| fastlane-plugin-update_project_codesigning | 0.1.7        |
</details>

*generated on:* **2017-01-19**
</details>

**Comment by hjanuschka** [comment]
you can read the code signing guide, as the bot suggested, and also have a look at this comment: https://github.com/fastlane/fastlane/issues/6832#issuecomment-257883114 (and the linked issues inside)

let me know if this helps you.

**Comment by bolom** [comment]
I have read the doc and I have already seen your comment 

However the app is not signing. I am using the new var profiler but Xcode don't use it

I have to open Xcode.

I have tested manuallly and automatically too

**Comment by mgrebenets** [comment]
@bolom What's the full error message in xcodebuild log?
Usually all code signing errors show up during `Check dependencies` phase and will look like this:

```
Check dependencies
No profile matching 'TargetName' found:  Xcode couldn't find a profile matching 'TargetName'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
Code signing is required for product type 'WatchKit App' in SDK 'iOS 10.2'
```

`xcpretty` may not have all the matchers yet and will filter out some of the important output of xcodebuild log.

**Comment by bolom** [comment]
in my case. I have to updated 
CODE_SIGN_IDENTITY[sdk=iphoneos*]

**Comment by mgrebenets** [comment]
@bolom, goot to header :thumbsup:
Can this one be closed?

**Comment by bolom** [comment]
Yes tks

**Comment by oliverfoggin** [comment]
@bolom where did you update to this? CODE_SIGN_IDENTITY[sdk=iphoneos*]

Currently having this same error.

Thanks

**Comment by bolom** [comment]
did that

https://gist.github.com/bolom/ed043e1e0c0976a0fcb7e8476e824bf1#file-fastfile-L17
