### ISSUE TITLE
versioning is not finding increment_version_number_in_plist

### ISSUE THREAD

**Issue by cepages** [fastlane/fastlane#7936]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I can't use the plugin `versioning` it's like it's not installed.

I've installed the plugin and my Gemfile and my Pluginfile seems fine ( as the documentation says)

Pluginfile

```
# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

gem 'fastlane-plugin-versioning'
```

Gemfile

```
# frozen_string_literal: true
# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "fastlane"
gem "cocoapods"
gem "match"

plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
```

This is the error:

```
[!] Could not find action or lane 'increment_version_number_in_plist'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane
```

Also all the time I get this at the beginning: 

```
[14:06:41]: It seems like you wanted to load some plugins, however they couldn't be loaded
[14:06:41]: Please follow the troubleshooting guide: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md
```

But the lane keeps running after those two lines.

Any idea where I can check what's the problem?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `app_store`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/carlospages/Documents/Projects/eDetailing/eDetailing/fastlane/Appfile'
- app_identifier: 'com.incuna.edetailingios'
- apple_id: 'iosdev@incuna.com'
- team_id: 'STG469W75Q'
-------
DEBUG [2017-01-20 13:25:32.12]: Checking if there are any plugins that should be loaded...
ERROR [2017-01-20 13:25:32.12]: It seems like you wanted to load some plugins, however they couldn't be loaded
ERROR [2017-01-20 13:25:32.12]: Please follow the troubleshooting guide: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/PluginsTroubleshooting.md
WARN [2017-01-20 13:25:32.12]: You require a gem, if this is a third party gem, please use `fastlane_require 'credentials_manager'` to ensure the gem is installed locally
INFO [2017-01-20 13:25:32.13]: -------------------------------------------------
INFO [2017-01-20 13:25:32.13]: --- Step: Verifying required fastlane version ---
INFO [2017-01-20 13:25:32.13]: -------------------------------------------------
INFO [2017-01-20 13:25:32.13]: Your fastlane version 2.9.0 matches the minimum requirement of 1.63.0  ✅
INFO [2017-01-20 13:25:32.13]: ------------------------------
INFO [2017-01-20 13:25:32.13]: --- Step: default_platform ---
INFO [2017-01-20 13:25:32.13]: ------------------------------
INFO [2017-01-20 13:25:32.13]: Driving the lane 'ios app_store' 🚀
DEBUG [2017-01-20 13:25:32.13]: /Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:142:in `trigger_action_by_name'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:34:in `block (2 levels) in parsing_binding'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane.rb:33:in `call'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
/Users/carlospages/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
/Users/carlospages/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
/Users/carlospages/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
/Users/carlospages/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/carlospages/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
WARN [2017-01-20 13:25:32.13]: Lane Context:
INFO [2017-01-20 13:25:32.13]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios app_store"}
ERROR [2017-01-20 13:25:32.13]: Could not find action or lane 'increment_version_number_in_plist'. Check out the README for more details: https://github.com/fastlane/fastlane/tree/master/fastlane
INFO [2017-01-20 13:25:32.13]: Successfully generated documentation at path '/Users/carlospages/Documents/Projects/eDetailing/eDetailing/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-01-20 13:25:32.14]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.2.2                           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
require 'credentials_manager'
fastlane_version "1.63.0"


default_platform :ios

platform :ios do
  FORCE_DEVICES = false
  before_all do |lane, options|
    # cocoapods We need to fix the problem with repos
  end

  desc "Upload a new version to the Apple Store"
  lane :app_store do
    #match(type: "appstore", app_identifier: "com.incuna.edetailingios", git_url: "git@github.com:incuna/incuna-certificates-ios.git") # more information: https://codesigning.guide 
    increment_version_number_in_plist
    #increment_version_number_in_plist(
    #    version_source: 'appstore',
    #    target: 'eDetailing'
    #)
    build_app
    
  end
##########################################################################
## PRIVATE LINES
##########################################################################

end
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.incuna.edetailingios" # The bundle identifier of your app
apple_id "iosdev@incuna.com" # Your Apple email address

team_id "STG469W75Q"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |
| match    | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.2        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-20**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.2.2                           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
require 'credentials_manager'
fastlane_version "1.63.0"


default_platform :ios

platform :ios do
  FORCE_DEVICES = false
  before_all do |lane, options|
    # cocoapods We need to fix the problem with repos
  end

  desc "Upload a new version to the Apple Store"
  lane :app_store do
    #match(type: "appstore", app_identifier: "com.incuna.edetailingios", git_url: "git@github.com:incuna/incuna-certificates-ios.git") # more information: https://codesigning.guide 
    increment_version_number_in_plist
    #increment_version_number_in_plist(
    #    version_source: 'appstore',
    #    target: 'eDetailing'
    #)
    build_app
    
  end
##########################################################################
## PRIVATE LINES
##########################################################################

end
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.incuna.edetailingios" # The bundle identifier of your app
apple_id "iosdev@incuna.com" # Your Apple email address

team_id "STG469W75Q"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |
| match    | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.2        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-20**
</details>

**Comment by ohayon** [comment]
Hey @cepages, would you mind sharing a bit more of the command line input/output? What is the command that you are running to reproduce this error? Thanks!
