### ISSUE TITLE
Prevent tokens being shown in log

### ISSUE THREAD

**Issue by mammuth** [fastlane/fastlane#7937]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am using Fastlane on Travis CI for an open source project. On Travis I put all those tokens that shouldn't be public in the environment variables. They're used in my Fastfile like this
```
sonar_update_server_args = {
	project_configuration_path: "sonar-project.properties", 
	sonar_runner_args:  " -Dsonar.login="+ENV['SONAR_LOGIN_TOKEN']
}
sonar(sonar_update_server_args)
```

When I run the lane, Fastlane is logging the command it's currently executing, like shown below. This is a problem because the private tokens would show up in the public log when running this on Travis.

```
...
[15:45:48]: ------------------------------
[15:45:48]: Driving the lane 'test' 🚀
[15:45:48]: -------------------
[15:45:48]: --- Step: sonar ---
[15:45:48]: -------------------
[15:45:48]: $ cd /Users/max/Code/TumCampusApp-iOS && sonar-scanner \
-Dproject.settings="sonar-project.properties"  -Dsonar.login=6cd5b2_private_token_eb6b3b67e
...
```

When searching the docs I didn't find an option to prevent certain parameters from being logged, or even to disable the logging of the complete command.

How is this supposed to be handled?
Thanks!

**Comment by mfurtak** [comment]
If you change your runner args to be 

`sonar_runner_args: "-Dsonar.login=$SONAR_LOGIN_TOKEN"`

will it work and keep the actual value out of the log?

**Comment by mfurtak** [comment]
Longer term, I believe a more robust solution here is to change the code in `sonar.rb` to use

```ruby
Fastlane::Actions.sh_control_output(command, print_command: false, print_command_output: true) 
```

to avoid echoing the command that is executed at all.

**Comment by mammuth** [comment]
`sonar_runner_args: "-Dsonar.login=$SONAR_LOGIN_TOKEN"`
doesn't print the value to the log. 👍 What a shame I didn't think of it :) 

Shall we keep this issue open for your long-term solution?

**Comment by mfurtak** [comment]
I'm glad that can be a work-around for you! 🎉  Yes, let's keep this open to track the next step.

**Comment by hjanuschka** [comment]
@mammuth i did a PR here: https://github.com/fastlane/fastlane/pull/7939 maybe you can give it a try. it adds a custom parameter for setting the `sonar.login` (as i think this is  a pretty common case)

and it changes the command execution to @mfurtak  proposal. so it should not print the command to the terminal.

let me know if this works for you.
