### ISSUE TITLE
xcpretty Error on fastlane init

### ISSUE THREAD

**Issue by joeboyscout04** [fastlane/fastlane#794]
I've just updated to version 1.37.0 and I'm getting this error when I try to do 'fastlane init'. 

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:2007:in `raise_if_conflicts': Unable to activate scan-0.2.0, because xcpretty-0.2.1 conflicts with xcpretty (~> 0.1.12) (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1176:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1212:in `block in activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'
```

**Comment by stevepaks** [comment]
you can skip version check on the fastlane at the /usr/bin/fastlane if you have an emergency task.
just delete line 22.

**Comment by KrauseFx** [comment]
Try running `sudo gem cleanup`

**Comment by joeboyscout04** [comment]
I've tried sudo gem cleanup and still getting the same error.

**Comment by mortenholmgaard** [comment]
I have the same problem, `sudo gem cleanup` didn't fix it.

**Comment by iamchenchen** [comment]
@mortenholmgaard & @joeboyscout04 I've also encounter the same thing. I'm no gem expert, but remove the order version of scan and xcpretty did the trick for me.  
<img width="1254" alt="screenshot 2015-11-10 00 12 56" src="https://cloud.githubusercontent.com/assets/808905/11057425/c380360a-873f-11e5-92e1-f1776981247b.png">

**Comment by ohwutup** [comment]
Hi everyone, I'm going to close this issue for now as it has been a while since there has been any activity. Please reopen it if issues are still cropping up! Thanks! :100:

**Comment by joeboyscout04** [comment]
I haven't seen it recently, I'm now on version 1.57.0

**Comment by ohwutup** [comment]
thanks @joeboyscout04 !
