### ISSUE TITLE
How do you specify an error occurred in a lane?

### ISSUE THREAD

**Issue by SuperTango** [fastlane/fastlane#7944]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
This is a basic question, but I can't seem to find it on google.  When an external command exits with a non-zero response code, fastlane puts up an error that looks like: 
![image](https://cloud.githubusercontent.com/assets/709342/22171102/e3b97cba-df3b-11e6-8664-a3eacca5ed7e.png)

How do you make that happen if an internal lane has an error (without calling out to an external script)?  

In my build, I want to fail if a particular environment variable is not set.  So I want to do something like

```
    unless ENV.key?('DEPLOYAPP_TOKEN')
      puts("DEPLOYAPP_TOKEN not set.  Exiting")
      exit(1)
    end
```

But I don't want to do "exit 1".  I've tried `return 1`, as well, but that doesn't seem to work either.

Thanks.

**Comment by mgrebenets** [comment]
Good question. I was using `raise` but it just stops execution and doesn't mark the lane as failed and doesn't even take be to `error` block.

**Comment by KrauseFx** [comment]
You can use `UI.user_error!("My error message") unless `some command``

If `some command` fails the error message should be shown, could you give that a try? This will not print out the output of the command though.

Alternatively you can use
```ruby
begin
  sh "command"
rescue => ex
  UI.error ex
  UI.user_error!("My error message")
end
```

**Comment by SuperTango** [comment]
Thanks @KrauseFx.  However, that doesn't exactly do the same as the failure of an external output or built in command. 

![image](https://cloud.githubusercontent.com/assets/709342/22171872/27dee7b6-df4d-11e6-97b0-ccef2d9514cc.png)

Notice how the "fastlane summary" doesn't show an error, and it doesn't have the cute explosion emoji. 

What I'm trying to do is output an error from within the Fastfile: 

```
  lane ci:
    unless ENV.key?('DEPLOYAPP_TOKEN')
      UI.user_error!("DEPLOYAPP_TOKEN not set.  Exiting")
    end
  ...
```

**Comment by KrauseFx** [comment]
Mh, I'd have to dig in deeper to see why the emoji isn't printed. However this doesn't seem like super high priority. I'll close the issue for now, as the basic functionality works now 👍
