### ISSUE TITLE
[Android] Multi package set up

### ISSUE THREAD

**Issue by tobiasschuerg** [fastlane/fastlane#7949]
Is it possible to set up fastlane to use multiple packages or to switch between a set of packages so that I can run

`fastlane fooBeta` which work with com.app.foo
`fastlane barBeta` which work with  com.app.bar

Can I add multiple Appfiles oder add multiple package names to it?

(I know I can run it without the setup like `fastlane supply run --json_key googleplay_key_foo.json --verbose --package_name com.app.foo --skip_upload_images --skip_upload_apk` for each package but I would prefer to have it as one lane in my setup)

**Comment by mfurtak** [comment]
Hi @tobiasschuerg 👋 

What if you could pass the package name as a parameter to your lane, would that get you what you want? See: https://docs.fastlane.tools/advanced/#passing-parameters

`fastlane beta package:com.app.foo`

**Comment by tobiasschuerg** [comment]
As the package and the json key go together, there should ne those two parameters, than it' be fine

**Comment by hjanuschka** [comment]
@tobiasschuerg here is a sample:

(based on your initial sample, you may have to tweak options)
```ruby
lane :beta do | options |
  supply(
    json_key: options[:json_key],
    package_name: options[: package_name]
    skip_upload_images: true,
    skip_upload_apk: true
  )
end
```

then you could call it from shell like

```bash
fastlane beta json_key:/path/to/key.json package_name:some.package.name
```

**Comment by tobiasschuerg** [comment]
Thanks, I'll check this before my next release and let you know.

(and no, I wasn't in Berlin last year. I was about to go to the DroidCon, but finally didn't go ;-) )
