### ISSUE TITLE
fastlane login & keychain problem with Jenkins

### ISSUE THREAD

**Issue by dinneo** [fastlane/fastlane#7950]
### New Issue Checklist

- [V ] Updated fastlane to the latest version
- [V ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi ,may I ask a question about `FASTLANE_SESSION` & `FASTLANE_PASSWORD` from fastlane Credential Manager
It’s both work at terminal and I can retrieve them 

FASTLANE_SESSION
~/.fastlane/spaceship/xxx@xx.com/cookie #<== execute spaceauth update session
it’s works after doing fastlane spaceauth -u apple@krausefx.com

Credential Manager
fastlane fastlane-credentials add --username xxx@xxx.com
Password: *********
Credential xxx@xxx.com:********* added to keychain.

Retrive Credential from keychain
security find-internet-password -ws deliver.xxx@xxx.com
password=xxxxxx <===== works!!

but both fail at my Jenkins CI machine shell, how to solve this problem??

fastlane login & keychain problem with Jenkins

login to Jenkins User terminal
#################################################

fastlane spaceship get session

fastlane spaceauth -u apple@krausefx.com
export FASTLANE_SESSION='---\n- !ruby/object:HTTP::Cookie\n  name: DES5c148586dfd451e55afbaaa5f62418f91\n  value: XXXX\n'

Fastlane Credential Manager store at keychain

Adding Credentials
fastlane fastlane-credentials add --username xxx@xxx.com
Password: *********
Credential xxx@xxx.com:********* added to keychain.

Retrive Credential from keychain
security find-internet-password -ws deliver.xxx@xxx.com

both work at CI Machine Terminal, but fail at Jenkins service
#################################################

MY Jenkins CI Machine shell
Jenkins Execute shell
##############################################################
#!/bin/bash -lx

export FASTLANE_SESSION='---\n- !ruby/object:HTTP::Cookie\n  name: DES5c148586dfd451e55afbaaa5f62418f91\n  value: XXXX\n'

echo $FASTLANE_SESSION #<=====  donsn’t work???

#export FASTLANE_PASSWORD=security find-internet-password -ws deliver.xxx@xxx.com
echo $FASTLANE_PASSWORD # <========= empty

#fastlane action setup_jenkins --verbose #<===== works
fastlane deliver --verbose #<=======fail, need login session or credential password

# Cleanup a file fastlane creates that prevents the repo to be clean at the end of the run
#rm -Rf fastlane/report.xml

###############################################################

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

+ export 'FASTLANE_SESSION=---\n- !ruby/object:HTTP::Cookie\n  name: DES5c148586dfd451e55afbaaa5f62418f91\n  value: XXXX\n'
937 react-text: 4942   /react-text 	+ FASTLANE_SESSION='---\n- !ruby/object:HTTP::Cookie\n  name: DES5c148586dfd451e55afbaaa5f62418f91\n  value: XXXX\n'
938 react-text: 4947   /react-text 	+ echo '---\n-' '!ruby/object:HTTP::Cookie\n' name: 'DES5c148586dfd451e55afbaaa5f62418f91\n' value: 'XXXX\n'
939 react-text: 4952   /react-text 	---\n- !ruby/object:HTTP::Cookie\n name: DES5c148586dfd451e55afbaaa5f62418f91\n value: XXXX\n
940 react-text: 4957   /react-text 	+ export FASTLANE_PASSWORD=security find-internet-password -ws deliver.xxx@xxx.com
941 react-text: 4962   /react-text 	+ FASTLANE_PASSWORD=security
942 react-text: 4967   /react-text 	/Users/Shared/Jenkins/tmp/hudson8964587714233045216.sh: line 7: export: `find-internet-password': not a valid identifier
943 react-text: 4972   /react-text 	/Users/Shared/Jenkins/tmp/hudson8964587714233045216.sh: line 7: export: `-ws': not a valid identifier
944 react-text: 4977   /react-text 	/Users/Shared/Jenkins/tmp/hudson8964587714233045216.sh: line 7: export: `deliver.xxx@xxx.com': not a valid identifier
945 react-text: 4982   /react-text 	+ echo security
946 react-text: 4987   /react-text 	security
947 react-text: 4992   /react-text 	+ fastlane cert --verbose
948 react-text: 4997   /react-text 	[33mSuccessfully loaded Appfile at path '/Users/Shared/Jenkins/Home/workspace/JenkinsTest/fastlane/Appfile'[0m
949 react-text: 5002   /react-text 	- [36mapp_identifier[0m: '[32mcom.test.test.JenkinsTest[0m'
950 react-text: 5007   /react-text 	- [36mapple_id[0m: '[32mxxx@xxx.com[0m'
951 react-text: 5012   /react-text 	- [36mteam_id[0m: '[32mU2847EE6SS[0m'
952 react-text: 5017   /react-text 	-------
953 react-text: 5022   /react-text 	
954 react-text: 5027   /react-text 	+---------------+-----------------------------------------------------------+
955 react-text: 5032   /react-text 	|                          [32mSummary for cert 2.9.0[0m                           |
956 react-text: 5037   /react-text 	+---------------+-----------------------------------------------------------+
957 react-text: 5042   /react-text 	| development   | false                                                     |
958 react-text: 5047   /react-text 	| force         | false                                                     |
959 react-text: 5052   /react-text 	| username      | xxx@xxx.com                                          |
960 react-text: 5057   /react-text 	| team_id       | XXXXXXXXXX                                                |
961 react-text: 5062   /react-text 	| keychain_path | /Users/Shared/Jenkins/Library/Keychains/login.keychain-db |
962 react-text: 5067   /react-text 	+---------------+-----------------------------------------------------------+
963 react-text: 5072   /react-text 	
964 react-text: 5077   /react-text 	INFO [2017-01-21 20:49:42.44]: Starting login with user ‘xxx@xxx.com'
965 react-text: 5082   /react-text 	Loading session from environment variable
966 react-text: 5087   /react-text 	[31mThe login credentials for ‘xxx@xxx.com' seem to be wrong[0m
967 react-text: 5092   /react-text 	The password was taken from the environment variable
968 react-text: 5097   /react-text 	Please make sure it is correct
969 react-text: 5102   /react-text 	Please run this tool again to apply the new password
970 react-text: 5107   /react-text 	
971 react-text: 5112   /react-text 	Looking for related GitHub issues on fastlane/fastlane...
972 react-text: 5117   /react-text 	Search query: The request could not be completed because:
973 react-text: 5122   /react-text 		Invalid User Credentials
974 react-text: 5127   /react-text 	
975 react-text: 5132   /react-text 	URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Invalid%20User%20Credentials+repo:fastlane/fastlane
976 react-text: 5137   /react-text 	➡️  [33mGetting 'invalid username and password combination'[0m
977 react-text: 5142   /react-text 	   https://github.com/fastlane/fastlane/issues/6977 [[31mopen[0m] 4 💬
978 react-text: 5147   /react-text 	   a week ago
979 react-text: 5152   /react-text 	
980 react-text: 5157   /react-text 	➡️  [33mPilot Fails with 'invalid request body' message[0m
981 react-text: 5162   /react-text 	   https://github.com/fastlane/fastlane/issues/7523 [[32mclosed[0m] 2 💬
982 react-text: 5167   /react-text 	   5 weeks ago
983 react-text: 5172   /react-text 	
984 react-text: 5177   /react-text 	➡️  [33mDeliver fails with `invalid request body`[0m
985 react-text: 5182   /react-text 	   https://github.com/fastlane/fastlane/issues/6710 [[32mclosed[0m] 24 💬
986 react-text: 5187   /react-text 	   25 Oct 2016
987 react-text: 5192   /react-text 	
988 react-text: 5197   /react-text 	and 7 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Invalid%20User%20Credentials&type=Issues&utf8=✓
989 react-text: 5202   /react-text 	
990 react-text: 5207   /react-text 	🔗 You can ⌘ + double-click on links to open them directly in your browser.
991 react-text: 5218   /react-text 	/Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/spaceship/lib/spaceship/client.rb:96:in `login': [31m[!] The request could not be completed because: (Spaceship::Client::InvalidUserCredentialsError)
992 react-text: 5223   /react-text 		Invalid User Credentials[0m
993 react-text: 5228   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/spaceship/lib/spaceship/portal/spaceship.rb:22:in `login'
994 react-text: 5233   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/spaceship/lib/spaceship/portal/spaceship.rb:77:in `login'
995 react-text: 5238   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/cert/lib/cert/runner.rb:17:in `login'
996 react-text: 5243   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/cert/lib/cert/runner.rb:27:in `run'
997 react-text: 5248   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/cert/lib/cert/runner.rb:6:in `launch'
998 react-text: 5253   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/cert/lib/cert/commands_generator.rb:33:in `block (2 levels) in run'
999 react-text: 5258   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
1000 react-text: 5263   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
1001 react-text: 5268   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
1002 react-text: 5273   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
1003 react-text: 5278   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
1004 react-text: 5283   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
1005 react-text: 5288   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/cert/lib/cert/commands_generator.rb:49:in `run'
1006 react-text: 5293   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/cert/lib/cert/commands_generator.rb:11:in `start'
1007 react-text: 5298   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
1008 react-text: 5303   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
1009 react-text: 5308   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/bin/fastlane:22:in `load'
1010 react-text: 5313   /react-text 		from /Users/Shared/Jenkins/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
1011 react-text: 5318   /react-text 	Build step 'Execute shell' marked build as failure
1012 react-text: 5323   /react-text 	[BFA] Scanning build for known causes...
1013 react-text: 5328   /react-text 	[BFA] No failure causes found
1014 react-text: 5333   /react-text 	[BFA] Done. 0s
1015 react-text: 5338   /react-text 	Finished: FAILURE

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1                          |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.9.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Runs all the tests"
  lane :jenk do
    cert
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.test.test.JenkinsTest" # The bundle identifier of your app
apple_id "xxx@xxx.com" # Your Apple email address

team_id "xxxxxxxxxx"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.22       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
</details>

*generated on:* **2017-01-21**
</details>

**Comment by lacostej** [comment]
@dinneo it seems you are storing credentials under the default keychain (login).

When you are logged in remotely, e.g. using SSH, this one isn't visible/unlocked. 
Try doing a:

```
security unlock-keychain -s ~/Library/Keychains/login.keychain
```
(and enter your user password) before retrieving the `deliver` credential using ` find-internet-password`

You might need to do the same as part of your build process.

**Comment by mfurtak** [comment]
Hi @dinneo - please be careful about posting info returned from `spaceauth` into public places. You need to protect that value the same as you would as a username and password! 👍

**Comment by jeeftor** [comment]
@lacostej are we supposed to not use the default keychain now?

**Comment by lacostej** [comment]
@jeeftor I am not sure if there is an official recommendation regarding the default or non default keychain. At our place, we don't use the default one. And it causes us a few issues, e.g. #7932

Anyway, @dinneo should make sure his keychain is unlocked before he starts using it.

**Comment by jinjorge** [comment]
@dinneo 
add `#!/bin/bash -l` to the beginning of your shell command then call your build script.

![screen shot 2017-01-24 at 6 12 40 am](https://cloud.githubusercontent.com/assets/2208083/22250610/6c94704a-e1fc-11e6-990b-73df5699c316.png)

**Comment by dinneo** [comment]
Hi @lacostej
It's works!! Thank you!!
I can't imagine that cause different result, why the behavior is different between login and ssh??

**Comment by lferro9000** [comment]
Hi @jinjorge
This worked for me.
The only problem i had was to get the credentials into the login keychain (i resorted to login in macos with jenkins user and run the commands on terminal and then allow the access to all of the credential - probably there are better ways to do this, but it worked).

The remaining issue was just a question of environment when running the script that launches fastlane, and adding the "-l" to the bash she-bang works like a charm.
