### ISSUE TITLE
Deploy to Crashlytics with fast lane is not working although Xcode Archiving is working well

### ISSUE THREAD

**Issue by younatics** [fastlane/fastlane#7956]
### New Issue Checklist

- [v] Updated fastlane to the latest version
- [v] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I just tried to use fastlane and finally, I could compile and deploy to Crashlytics successfully. However, some functions not working like HTML Page, Server transaction in my application. When I had compiled it with Xcode and distributed with Crashlytics, it was working well. Is there any difference between two of them? Need to be figured out to use fast lane :( I attached my build settings. 

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.2                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.1 (Apple Git-78)               |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.2 (16C67)                        |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.2.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

#update_fastlane
fastlane_version "2.9.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods

  end

# Beta Settings
# Scheme: "zigbang_ios_debug”
  lane :Beta do

  ensure_git_status_clean

  checkNewVersionStart = get_info_plist_value(path: "./MYAPPLICATION/Release/MYAPPLICATION-Info.plist", key: "CFBundleVersion")
  if checkNewVersionStart == "0"
  increment_build_number(
      build_number: "0"
  )
  end

  formerNumber = get_build_number

  increment_build_number
  build_number = get_build_number
  version = get_version_number

  formerVersion = "#{version}-b#{formerNumber}”
  commitVersion = "#{version}-b#{build_number}”

  set_info_plist_value(path: “./MYAPPLICATION/Debug/MYAPPLICATION_debug-Info.plist", key: "CFBundleVersion", value: build_number)
  set_info_plist_value(path: “./MYAPPLICATION/Release/MYAPPLICATION-Info.plist", key: "CFBundleVersion", value: build_number)

  commit_version_bump(
      message: “Version #{commitVersion}”
      )
  add_git_tag(
      grouping: “v#{version}”,
      build_number: commitVersion
      )
  push_to_git_remote

  cert(
    output_path: "fastlane/certificate"
    )
  sigh(
    adhoc: true,
    force: true,
    output_path: "fastlane/certificate"
    )
  gym(scheme: "MYAPPLICATION_debug”,
      workspace: "MYAPPLICATION.xcworkspace",
      output_directory: “fastlane/ipa/“,
      clean: true,
      silent: true,
      include_bitcode: false
      )
  commitMessage = changelog_from_git_commits(
      pretty: "- %s",
      between: ["v#{version}/iosBeta/#{formerVersion}", "v#{version}/iosBeta/#{commitVersion}"]
      )
  crashlytics(
      groups: "Testers",
      notifications: true,
      notes: "MYAPPLICATION_debug\n#{commitMessage}",
      ipa_path: "./fastlane/ipa/MYAPPLICATION.ipa",
      api_token: "MYAPPLICATION_API_TOKEN",
      build_secret: "MYAPPLICATION_BUILD_SECRET"
      )
  end
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "MYAPPLICATION_APP_IDENTIFIER"
apple_id ENV["APPLE_ID"]

team_id "MYAPPLICATION_TEAM_ID"
itc_team_id "TEAM_ID"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
</details>

*generated on:* **2017-01-23**
</details>

**Comment by mfurtak** [comment]
Hi @skyboy1342 👋 

Sorry - this is not enough information for people to be able to help. Can you please include your `Fastfile`, the command you are running, logs from your Xcode build, and logs from your _fastlane_ build so they can be compared?

Thanks! 👍

**Comment by younatics** [comment]
Sorry for my late reply. After I cleaned my build also with derived data, It started to work perfectly. Thank you for your reply :)
