### ISSUE TITLE
iTunes: Add Build to Test

### ISSUE THREAD

**Issue by sauliusgrigaitis** [fastlane/fastlane#796]
Is there any way to automate process after app is uploaded to TestFlight for external testers? Currently we need to go to iTunes, click "Add Build to Test" and click few more times.

**Comment by KrauseFx** [comment]
Sure, if you use `pilot` it should do that automatically. Is it not working for you?

**Comment by sauliusgrigaitis** [comment]
@KrauseFx  thanks for response. Yes, but uploading via pilot takes really long time, because it waits until build is processed, it's really annoying when deploying from command line. But I believe three is no any faster way?

**Comment by KrauseFx** [comment]
Sorry, you can only distribute a build once it's ready processing, there is not much I can do.
