### ISSUE TITLE
uninitialized constant FastlaneCore::Swag (NameError)

### ISSUE THREAD

**Issue by gregk8288** [fastlane/fastlane#7960]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

While trying to fun Fastlane I immediately receive the following error: 

```iOS $ fastlane deploy
.../.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:13:in `start': uninitialized constant FastlaneCore::Swag (NameError)
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>' 
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

I can't as I get the very same error. 

```iOS $ fastlane env
/Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/commands_generator.rb:13:in `start': uninitialized constant FastlaneCore::Swag (NameError)
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/gems/fastlane-2.9.0/bin/fastlane:15:in `<top (required)>'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/gregkockott/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by KrauseFx** [comment]
Do you use a Gemfile? If so, can you make sure only `fastlane` is there? Also can you run `gem uninstall fastlane_core credentials_manager` and try again?

**Comment by hjanuschka** [comment]
@gregk8288 i reproduced it locally.
it happens when you use a gemfile where fastlane_core is included (as @KrauseFx  mentioned)


e.g:
```ruby
gem "fastlane_core"
gem "fastlane"
```

could you try removing fastlane_core, and confirm that it works?

**Comment by gregk8288** [comment]
Thanks @hjanuschka and @KrauseFx. I reinstalled **fastlane** and removed the **fastlane_core** and it did the trick. Not sure which one did the job but I was able to publish so all good. Thanks for the speedy response. 👍
