### ISSUE TITLE
Gemspec version requirement for Bundler

### ISSUE THREAD

**Issue by summera** [fastlane/fastlane#7963]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Wondering if there is a specific reason for having bundler version set to `~>1.12` in the gemspec? Default bundler for my server environment is `1.9.6`. So curious if it's possible to lower this requirement if it's not necessary. I see that it was changed in https://github.com/fastlane/fastlane/pull/4722. Thanks!

**Comment by KrauseFx** [comment]
Nice catch, thanks, just submitted https://github.com/fastlane/fastlane/pull/7964 👍

**Comment by summera** [comment]
@KrauseFx thanks for the quick response! i'm wondering if it's possible to go even lower than `1.12`. For example: `spec.add_dependency 'bundler', '~> 1.0'`

**Comment by KrauseFx** [comment]
Let's continue discussion on the PR 👍
