### ISSUE TITLE
ensure_xcode_version requires the xcode-install gem

### ISSUE THREAD

**Issue by streeter** [fastlane/fastlane#7965]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Installing Fastlane and not having the `xcode-install` gem installed as well, fails with the error:

```
fastlane-2.10.0/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `popen': [!] No such file or directory - xcversion (Errno::ENOENT)
```

**Comment by streeter** [comment]
Here's the error:

```
➜ /tmp/fastlane fastlane version
[17:38:56]: -------------------------------------------------
[17:38:56]: --- Step: Verifying required fastlane version ---
[17:38:56]: -------------------------------------------------
[17:38:56]: Your fastlane version 2.10.0 matches the minimum requirement of 1.106.2  ✅
[17:38:56]: ------------------------------
[17:38:56]: --- Step: default_platform ---
[17:38:56]: ------------------------------
[17:38:56]: Driving the lane 'ios version' 🚀
[17:38:56]: ----------------------------------
[17:38:56]: --- Step: ensure_xcode_version ---
[17:38:56]: ----------------------------------
[17:38:56]: $ xcversion selected
+------------------+-------------+
|          Lane Context          |
+------------------+-------------+
| DEFAULT_PLATFORM | ios         |
| PLATFORM_NAME    | ios         |
| LANE_NAME        | ios version |
+------------------+-------------+
[17:38:56]: No such file or directory - xcversion

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | ensure_xcode_version                | 0           |
+------+-------------------------------------+-------------+

[17:38:56]: fastlane finished with errors
/Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `popen': [!] No such file or directory - xcversion (Errno::ENOENT)
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/helper/sh_helper.rb:36:in `sh_control_output'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/action.rb:98:in `sh'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/actions/ensure_xcode_version.rb:10:in `run'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:20:in `block (2 levels) in parsing_binding'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:255:in `execute_flow_block'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/gems/fastlane-2.10.0/bin/fastlane:15:in `<top (required)>'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/bin/fastlane:22:in `load'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/bin/fastlane:22:in `<main>'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/bin/ruby_executable_hooks:15:in `eval'
	from /Users/streeter/.rvm/gems/ruby-2.3.3@fastlane/bin/ruby_executable_hooks:15:in `<main>'
```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                        |
| ------------------- | -------------------------------------------- |
| OS                  | 10.12.3                                      |
| Ruby                | 2.3.3                                        |
| Bundler?            | true                                         |
| Git                 | git version 2.11.0                           |
| Installation Source | ~/.rvm/gems/ruby-2.3.3@fastlane/bin/fastlane |
| Host                | Mac OS X 10.12.3 (16D32)                     |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                  |
| Is contained        | false                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/  |
| Xcode Version       | 8.2                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en          | 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

REQUIRED_XCODE_VERSION = "8.2"
REQUIRED_FASTLANE_VERSION = "1.106.2"

# Disable GH Issue search
ENV["FASTLANE_HIDE_GITHUB_ISSUES"] = "1"

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version REQUIRED_FASTLANE_VERSION

default_platform :ios

platform :ios do
  before_all do
    ensure_xcode_version(version: REQUIRED_XCODE_VERSION)
  end

  desc "Prints the version"
  lane :version do
      puts "Hello World"
  end
end
```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.10.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.2       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.2        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.23       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-01-23**
</details>

**Comment by streeter** [comment]
Here's the Gemfile I used to initialize the environment:

```Gemfile
source "http://rubygems.org"

gem "fastlane",             "2.10.0"
```

**Comment by lacostej** [comment]
specific actions may require extra bundles. You need to add it to your `Gemfile`.

**Comment by hjanuschka** [comment]
@streeter you need to add the `xcode-install` gem. to your Gemfile.

i did a PR -> #7972 -> to fix this, and install gem if required.

**Comment by streeter** [comment]
Right, I guess that wasn't documented anywhere, and the error message was ambiguous. Do you guys have a standardized place to document dependencies like this?

**Comment by streeter** [comment]
Looks like #7972 would be a great solution for this, thanks @hjanuschka!
