### ISSUE TITLE
commit_version_bump error

### ISSUE THREAD

**Issue by gholias** [fastlane/fastlane#797]
In the end of my lane, Im calling **commit_version_bump**

 ```clean_build_artifacts
    commit_version_bump(
      xcodeproj: 'Cars.xcodeproj'
    )

    add_git_tag
```

But Im getting the following error
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- xcodeproj/project/object (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.27.0/lib/xcodeproj/project.rb:4:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.37.0/lib/fastlane/actions/commit_version_bump.rb:44:in `run'
```

Line 44 of commit_version_bump.rb is 
```project = Xcodeproj::Project.open(xcodeproj_path)```

Looks like it cant find the project file, but the path is correct. Cars.xcodeproj is the same folder from where *fastlane lane* is called.

Am Im missing something?

thanks

**Comment by gholias** [comment]
I found out the problem. The folder I was using has a space in the name

I renamed the folder from **Cars Release** to **CarsRelease** and the error is gone.

**Comment by andreyslyusar** [comment]
I do not get an error but info.plist in folder with space "Supporting file" is ignored. I need to rename folder and remove space to get it work.

**Comment by ohwutup** [comment]
Going to close this for now as it looks like there are workarounds available. Let us know if there are any more issues with this!
