### ISSUE TITLE
Setting up Mac app with Hockey upload

### ISSUE THREAD

**Issue by vojto** [fastlane/fastlane#7970]
Setting up a Mac app with upload to Hockey doesn't "just work". It's pretty involved to set it up correctly.

- `gym` generates a `.app` directory and zipped up dsym
- Hockey expects zipped up app file and dsym
- zipping of `app` must be done manually
- paths aren't passed from one step to another
  - `gym` only returns a `DSYM_OUTPUT_PATH` (no other paths) which is really just the project directory. It's not even useful as you can see, because you can find this dir at `pwd/..`.

Based on #1110 I came up with this:

```ruby
  lane :beta do
    dir = File.expand_path(File.join(File.dirname(__FILE__), '..'))
    Actions.sh("rm -rf #{dir}/build/*")

    increment_build_number

    gym(scheme: "Median", clean: true, output_directory: "build") # Build your app - more options available

    dir = ENV[SharedValues::DSYM_OUTPUT_PATH.to_s]

    app_path = File.join(dir, "Median.app")
    dsym_path = File.join(dir, "Median.app.dSYM.zip")
    zip_path = app_path + ".zip"
    app_filename = File.basename(app_path)
    Actions.sh("pushd #{dir} && zip -r #{zip_path} #{app_filename}/* && popd")

    hockey(
      :api_token => # ...,
      :ipa => zip_path,
      :dsym => dsym_path
    )
  end
```

This is working fine. So I'm writing this down as a future reference, and also to open a conversation - is it doable to improve this process so we could have simply:

```ruby
  lane :beta do
    gym(scheme: "Median", clean: true, output_directory: "build")
    hockey(:api_token => "...")
  end
```

If it's not crazy difficult, I'd be happy to help.

**Comment by vojto** [comment]
@fastlane-bot Pretty sure it doesn't matter, but here you go little bot buddy: https://gist.github.com/vojto/8a6fba29bdbff808787f178c72bcd861

**Comment by hjanuschka** [comment]
nice workaround/solution - gym returns the path - not via shared values/envs. it directly returns it. (https://github.com/fastlane/fastlane/blob/master/gym/lib/gym/runner.rb#L32)

e.g.:
```
output_dir_full_path =  gym(scheme: "Median", clean: true, output_directory: "build")
```


i am unsure about the requirement to return a already zipped file, is this a common use case in mac-app dev? (or is it only required for hockey usage?)

**Comment by vojto** [comment]
@hjanushka - Thanks, should've thought of that.

Well hockey requires `.zip`, because `.app` is a directory. Not sure how App Store upload works (when you submit to MAS), because I've only done it through Xcode, but I imagine Xcode also does some kind of zipping before sending to App Store.

**Comment by hjanuschka** [comment]
@vojto looked at the code of deliver, looks like MAS expects to get a `.pkg` file, not sure how you'll get one.

anyway i am unsure implementing it into fastlane itself, for the specific hockey use case, i think its a ideal candidate to do as a plugin like `fastlane-plugin-package_for_hockey`

docs on how to do custom plugins: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by vojto** [comment]
Cool, thanks!

Yeah, I'm still using only Hockey, so haven't tried it with MAS yet.

Closing this as my original request for clarification & guidelines was answered.
