### ISSUE TITLE
Incorrect App ID detected and scheme option ignored when running fastlane init

### ISSUE THREAD

**Issue by mikelrob** [fastlane/fastlane#7973]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running `fastlane init` in my proj dir, the detected project values showed the incorrect `App Identifier`.

I tried using the `--scheme app` option however this was ignored.
```
2017-01-20 16:58:50- ~/Documents/repos/app-ios $ fastlane init -scheme "app"
[16:58:59]: Detected iOS/Mac project in current directory...
[16:58:59]: This setup will help you get up and running in no time.
[16:58:59]: fastlane will check what tools you're already using and set up
[16:58:59]: the tool automatically for you. Have fun! 
[16:58:59]: $ xcodebuild -list -workspace ./app.xcworkspace
[16:59:01]: $ xcodebuild clean -showBuildSettings -workspace ./app.xcworkspace -scheme AFNetworking
```

I found that the detected value for the App ID correlated with the first scheme listed in the Manage Schemes in Xcode.

![Xcode - Manage Schemes](https://cloud.githubusercontent.com/assets/3390342/22244724/a271622c-e224-11e6-8c74-5430ac2c8b93.png)

Dragging my app scheme to the top of the list resolved the issue.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
+----------------+----------------------------------------------------------------+
|                                 Detected Values                                 |
+----------------+----------------------------------------------------------------+
| Apple ID       | mike@p-------------.com                                        |
| App Name       | AFNetworking                                                   |
| App Identifier | org.cocoapods.AFNetworking                                     |
| Workspace      | /--------/---------/--------/-ios/app.xcworkspace              |
+----------------+----------------------------------------------------------------+
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.12.2                                         |
| Ruby                | 2.2.4                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.1 (Apple Git-78)               |
| Installation Source | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.12.2 (16C67)                        |
| Ruby Lib Dir        | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained        | false                                           |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version       | 8.2.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.9.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
</details>

*generated on:* **2017-01-20**
</details>

**Comment by ohayon** [comment]
Hey @mikelrob! Thanks for raising this issue. Currently, passing `-scheme "<scheme_name>"` is not supported by `fastlane init`. That being said, you should be prompted to "Please confirm the above values" after the scripts start to make assumptions about your project. If you enter `n` to not confirm the values, you should be directed into a more manual setup where _fastlane_ will ask you for the appropriate values it needs to run.

I am going to close this issue for now, but please do not hesitate to reopen or continue conversation if you run into more troubles! 🐙 🚀
