### ISSUE TITLE
Upload Changelogs (What's New) text only?

### ISSUE THREAD

**Issue by aareeph** [fastlane/fastlane#7974]
Hi

Is there a way to upload What's New text only? I want to skip metadata, screenshots and apk files.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.5                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.9.3 (Apple Git-75)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.5 (15F34)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.7.0   | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.11.2       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.3        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.7.1        |
| google-api-client         | 0.9.4        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.0       |
| json                      | 2.0.2        |
</details>

*generated on:* **2017-01-24**
</details>

Thanks

**Comment by hjanuschka** [comment]
@aareeph  are you looking for ios or android platform?

**Comment by aareeph** [comment]
@hjanuschka  sorry I forgot to mention. I am looking for android platform.

Thanks!

**Comment by hjanuschka** [comment]
looks like this is currently not supported via supply.

you could do it yourself using google api (which supply uses too)
(directly in your fastfile (e.g. in a lane))


```ruby
require 'googleauth'
require 'google/apis/androidpublisher_v2'
# CONFIGURE those variables
PACKAGE_NAME = "krone.at.fxf"
KEY_PATH = "~/Desktop/CLOUD_DRIVE_OLD/FXF/FXF-ANDROID/fastlane/google_play_key.json"

Androidpublisher = Google::Apis::AndroidpublisherV2
CredentialsLoader = Google::Auth::CredentialsLoader

scope = Androidpublisher::AUTH_ANDROIDPUBLISHER
service_account_json = File.open(File.expand_path(KEY_PATH))
auth_client = Google::Auth::ServiceAccountCredentials.make_creds(json_key_io: service_account_json, scope: scope)
auth_client.fetch_access_token!


Google::Apis::ClientOptions.default.application_name = "Autobot"
Google::Apis::ClientOptions.default.application_version = "1.0"
Google::Apis::RequestOptions.default.timeout_sec = 300
Google::Apis::RequestOptions.default.open_timeout_sec = 300
Google::Apis::RequestOptions.default.retries = 5

android_publisher = Androidpublisher::AndroidPublisherService.new
android_publisher.authorization = auth_client




# set the new text
apk_listing_object = Androidpublisher::ApkListing.new({
  language: "de-DE",
  recent_changes: "Updated Text"
})

# create an edit object
current_edit = android_publisher.insert_edit(PACKAGE_NAME)

# here you would have to itterate your self over apks, if you need anything else then the latest apk
latest_version = android_publisher.list_apks(PACKAGE_NAME, current_edit.id).apks.last

# update the recent_changes
android_publisher.update_apk_listing(
    PACKAGE_NAME,
    current_edit.id,
    latest_version.version_code,
    apk_listing_object.language,
    apk_listing_object
)
```

**Comment by hjanuschka** [comment]
let me know if this helps you.

**Comment by aareeph** [comment]
@hjanuschka  I'll give it a try and let you know about this. Thanks a lot for your help 👍
