### ISSUE TITLE
Platform specific lanes are only parsed if a matching default_platform is specified

### ISSUE THREAD

**Issue by AWrightIV** [fastlane/fastlane#7979]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to have a common fastfile between my iOS and Android projects. There appears to be a bug right now where I can't omit the ```default_platform``` line.
```ruby
# without this line, no lanes are recognized
# default_platform :ios

platform :ios do
  lane :mylane do
    gym(scheme: "myscheme")
  end
end

platform :android do
  lane :mylane do
    gradle(task: "assembleRelease")
  end
end
```
When running ```fastlane```, the verbose output ends with the following:
```
/Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] It looks like you don't have any lanes to run just yet. Check out how to get started here: https://github.com/fastlane/fastlane 🚀 (FastlaneCore::Interface::FastlaneError)
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane/lib/fastlane/lane_manager.rb:124:in `choose_lane'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane/lib/fastlane/lane_manager.rb:39:in `cruise_lane'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/gems/fastlane-2.10.0/bin/fastlane:15:in `<top (required)>'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/wrighta/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
```

### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/wrighta/igt/casino-client/mobile/ios/fastlane/Appfile'
- app_identifier: 'com.doubledowninteractive.ReactNativeDDC'
- apple_id: 'igt.mobile.codesigning@igt.com'
- team_id: 'WNMB4E4L95'
-------
DEBUG [2017-01-24 11:10:06.44]: Checking if there are any plugins that should be loaded...
INFO [2017-01-24 11:10:06.46]: -----------------------------
INFO [2017-01-24 11:10:06.46]: --- Step: update_fastlane ---
INFO [2017-01-24 11:10:06.46]: -----------------------------
INFO [2017-01-24 11:10:06.48]: Looking for updates for fastlane...
INFO [2017-01-24 11:10:08.20]: Nothing to update ✅
INFO [2017-01-24 11:10:08.21]: -------------------------------------------------
INFO [2017-01-24 11:10:08.21]: --- Step: Verifying required fastlane version ---
INFO [2017-01-24 11:10:08.21]: -------------------------------------------------
INFO [2017-01-24 11:10:08.21]: Your fastlane version 2.10.0 matches the minimum requirement of 1.111.0  ✅


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

# default_platform :ios

platform :ios do
  before_all do
    ENV["HIPCHAT_API_TOKEN"] = "my_token"

    # Attempt to select Xcode 8.2.1
    xcversion(version: "8.2.1")

    cocoapods

  end

  desc "Runs all the tests"
  lane :RunAllTests do
    scan(scheme: 'myscheme')
  end

  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  desc "Submit a new Beta Build to Crashlytics Beta"
  desc "This will also make sure the profile is up to date"
  lane :DeployToBeta do |values|
    match(type: "adhoc", force_for_new_devices: true)

    gym(scheme: 'myscheme', configuration: 'Release', clean: true)#export_method: 'ad-hoc',

    groups = 'mygroup' # You can define groups on the web and reference them here

    crashlytics(api_token: 'mytoken',
             build_secret: 'mybuildsecret,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # hipchat(
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta",
    #   message_format: "html", # or "text", defaults to "html"
    #   channel: "mychannel",
    #   success: true,
    #   version: 1
    # )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :DeployToTestflight do |values|
    match(type: "appstore")

    gym(scheme: 'myscheme', clean: true) # Build your app - more options available

    # Prevent connection error when uploading through our office wi-fi:
    #
    # [Transporter Output]: DEBUG: An error has occurred during the upload.
    # [Transporter Output]: DEBUG: An exception has occurred: Remote system reported message
    #   30156: Connection reset by peer
    # [Transporter Output]: DEBUG: Transfer error: Remote system reported message 30156:
    #   Connection reset by peer
    # [Transporter Output]: INFO: The Signiant transfer engine's status is DISCONNECTED
    # [Transporter Error Output]: The session's status is FAILED and the error description is
    #   'Client unable to connect to server (check UDP port and firewall) (15)'
    #
    # https://github.com/fastlane-old/deliver/issues/235
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    pilot()
  end

  desc "Deploy a new version to the App Store"
  lane :DeployToAppStore do
    match(type: "appstore")

    # snapshot

    gym(scheme: "myscheme", clean: true) # Build your app - more options available

    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    deliver(force: true)

    # frameit
  end

  desc "For testing your Fastlane install"
  lane :RunDebugBuild do
    match(type: "development")

    gym(scheme: "myscheme")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "myappid" # The bundle identifier of your app
apple_id "myappleid" # Your Apple email address

team_id "myteamid"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.10.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| rdoc                      | 5.0.0        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2017-01-24**
</details>

**Comment by KrauseFx** [comment]
```
 ~  Developer  fastlane  master  $  be fastlane mylane
+------------------------------+---------+--------------+
|                     Used plugins                      |
+------------------------------+---------+--------------+
| Plugin                       | Version | Action       |
+------------------------------+---------+--------------+
| fastlane-plugin-ruby         | 0.1.3   | rspec        |
|                              |         | rubocop      |
| fastlane-plugin-clubmate     | 0.1.0   | clubmate     |
| fastlane-plugin-sharethemeal | 0.1.9   | sharethemeal |
+------------------------------+---------+--------------+


[!] Could not find 'mylane'. Available lanes: ios mylane, android mylane
```

I tried with the exact same Fastfile and it's working fine on my machine. Do you have anything else set up differently maybe?

**Comment by KrauseFx** [comment]
Could you also update to the latest version 👍

**Comment by AWrightIV** [comment]
- [X] Updated to 2.11.0

I do get your same output when running `fastlane mylane`, but when simply running `fastlane` I expect to be presented with the same list of options as when I have `default_platform` set. Perhaps my reported issue is actually a feature request. :)

# fastlane mylane

### Captured Output

Command Used: `mylane`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/wrighta/igt/casino-client/mobile/android/fastlane/Appfile'
- package_name: 'com.ddi.ReactNativeDDC'
-------
DEBUG [2017-01-25 11:59:47.85]: Checking if there are any plugins that should be loaded...


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# without this line, no lanes are recognized
# default_platform :ios

platform :ios do
  lane :mylane do
    gym(scheme: "myscheme")
  end
end

platform :android do
  lane :mylane do
    gradle(task: "assembleRelease")
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.ddi.ReactNativeDDC" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.11.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| faraday_middleware        | 0.11.0       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2017-01-25**
</details>



# fastlane
### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/wrighta/igt/casino-client/mobile/android/fastlane/Appfile'
- package_name: 'com.ddi.ReactNativeDDC'
-------
DEBUG [2017-01-25 11:50:43.02]: Checking if there are any plugins that should be loaded...


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# without this line, no lanes are recognized
# default_platform :ios

platform :ios do
  lane :mylane do
    gym(scheme: "myscheme")
  end
end

platform :android do
  lane :mylane do
    gradle(task: "assembleRelease")
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.ddi.ReactNativeDDC" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.11.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| faraday_middleware        | 0.11.0       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2017-01-25**
</details>

**Comment by AWrightIV** [comment]
# Uncommented default_platform

```ruby
# without this line, no lanes are recognized
default_platform :ios

platform :ios do
  lane :mylane do
    gym(scheme: "myscheme")
  end
end

platform :android do
  lane :mylane do
    gradle(task: "assembleRelease")
  end
end
```

# fastlane

Here, we get interactive mode.

### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/wrighta/igt/casino-client/mobile/android/fastlane/Appfile'
- package_name: 'com.ddi.ReactNativeDDC'
-------
DEBUG [2017-01-25 12:06:00.34]: Checking if there are any plugins that should be loaded...
INFO [2017-01-25 12:06:00.35]: ------------------------------
INFO [2017-01-25 12:06:00.35]: --- Step: default_platform ---
INFO [2017-01-25 12:06:00.35]: ------------------------------
INFO [2017-01-25 12:06:00.35]: Welcome to fastlane! Here's what your app is setup to do:
+--------+------------+------------------------------+
|               Available lanes to run               |
+--------+------------+------------------------------+
| Number | Lane Name  | Description                  |
+--------+------------+------------------------------+
| 1      | ios mylane |                              |
| 0      | cancel     | No selection, exit fastlane! |
+--------+------------+------------------------------+
WARN [2017-01-25 12:06:00.35]: Which number would you like run?

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Running fastlane on Bitrise - non-interactive mode
   https://github.com/fastlane/fastlane/issues/5867 [closed] 5 💬
   06 Dec 2016

➡️  gem install fastlane started to fail
   https://github.com/fastlane/fastlane/issues/7508 [closed] 8 💬
   6 weeks ago

➡️  Cannot run fastlane on Xcode Server bot
   https://github.com/fastlane/fastlane/issues/6318 [closed] 8 💬
   a week ago

and 10 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗 You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# without this line, no lanes are recognized
default_platform :ios

platform :ios do
  lane :mylane do
    gym(scheme: "myscheme")
  end
end

platform :android do
  lane :mylane do
    gradle(task: "assembleRelease")
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.ddi.ReactNativeDDC" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.11.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| faraday_middleware        | 0.11.0       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2017-01-25**
</details>

**Comment by KrauseFx** [comment]
Sorry I must have misunderstood, could you sum up again on what the expected behavior is for a given Fastfile, and what's actually happening? Sorry for not following right away on this.

**Comment by AWrightIV** [comment]
In brief, when the Fastfile does not include a `default_platform`, `fastlane` without parameters fails to present interactive mode.

**Comment by AWrightIV** [comment]
Fastlane works with multiple platforms and no default now! Awesome!

```
$ fastlane
[12:49:32]: -----------------------------
[12:49:32]: --- Step: update_fastlane ---
[12:49:32]: -----------------------------
[12:49:32]: Looking for updates for fastlane...
[12:49:36]: Updating fastlane from 2.23.0 to 2.26.0 ... 🚀
[12:50:05]: Finished updating fastlane
[12:50:05]: Cleaning up old versions...
[12:50:06]: fastlane.tools successfully updated! I will now restart myself... 😴
[12:50:07]: -----------------------------
[12:50:07]: --- Step: update_fastlane ---
[12:50:07]: -----------------------------
[12:50:07]: -------------------------------------------------
[12:50:07]: --- Step: Verifying required fastlane version ---
[12:50:07]: -------------------------------------------------
[12:50:07]: Your fastlane version 2.26.0 matches the minimum requirement of 2.10.0  ✅
[12:50:07]: Welcome to fastlane! Here's what your app is setup to do:
+--------+------------------------+-----------------------------------------------------------------+
|                                      Available lanes to run                                       |
+--------+------------------------+-----------------------------------------------------------------+
| Number | Lane Name              | Description                                                     |
+--------+------------------------+-----------------------------------------------------------------+
| 1      | ios myLane1            | Runs all my iOS stuff                                           |
| 2      | android myLane2        | Runs all my Android stuff                                       |
| 0      | cancel                 | No selection, exit fastlane!                                    |
+--------+------------------------+-----------------------------------------------------------------+
[12:50:07]: Which number would you like run?
0

[!] Run `fastlane` the next time you need to build, test or release your app 🚀```
