### ISSUE TITLE
This app contains an embedded provisioning profile that is not associated with your account.

### ISSUE THREAD

**Issue by nishinamu13** [fastlane/fastlane#7988]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
ERROR ITMS-90159: "Invalid provisioning profile. This app contains an embedded provisioning profile that is not associated with your account. Please use a provisioning profile associated with Team ID 42VS245LG2."
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/MYFramework' must be signed with the certificate that is contained in the provisioning profile."
[10:02:30]: ERROR ITMS-90159: "Invalid provisioning profile. This app contains an embedded provisioning profile that is not associated with your account. Please use a provisioning profile associated with Team ID 123456789."
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/Myframework' must be signed with the certificate that is contained in the provisioning profile."
Return status of iTunes Transporter was 1: ERROR ITMS-90159: "Invalid provisioning profile. This app contains an embedded provisioning profile that is not associated with your account. Please use a provisioning profile associated with Team \nERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/MYFramework' must be signed with the certificate that is contained in the provisioning profile."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

### Environment

<details><summary> fastlane environment </summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.6.0"
 
default_platform :ios
 
platform :ios do
 
  # 1
  desc "Creating a code signing certificate and provisioning profile"
  # 2
  lane :provision do
    # 3
    produce(
      app_name: ‘App For iPad’,
      language: 'English',
      app_version: '1.0',
      sku: 'abc123'
    )
    # 4
    cert
    # 5
    sigh(force: true)
  end
 
  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end

  desc "Create ipa"
  lane :build do
    gym
  end

 desc "Upload to App Store"
  lane :upload do
    deliver
  end
 
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "MyIdentifier" # The bundle identifier of your app
apple_id "abc@gmail.com" # Your Apple email address

team_id "TEAMID"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.11.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.23       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.14.2       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-01-25**
</details>

**Comment by nishinamu13** [comment]
While uploading the app on app store I am getting this issue. I have only one developer account and one team. By using this credentials only I have uploaded the app on store 1 year before.
My account has only one TEAM ID then why it is not validating profile.
Please help me on the same

Thank You

**Comment by hjanuschka** [comment]
can you check in xcode that the right team is selected on all targets?

<img width="662" alt="bildschirmfoto 2017-01-25 um 09 20 47" src="https://cloud.githubusercontent.com/assets/2891702/22282951/b746705a-e2df-11e6-952e-d5f06b6b44f1.png">


could you provide the output of your fastlane by calling it with `--capture_output` ?

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
