### ISSUE TITLE
target_filter filtering with target.product_name instead of target.name in update_project_provisioning

### ISSUE THREAD

**Issue by chinnawatp** [fastlane/fastlane#799]
I used **target_filter** to match **target.name** , but it turn out that it matches with **target.product_name** instead. Is this intentional ?
https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/update_project_provisioning.rb
```ruby
project = Xcodeproj::Project.open(folder)
        project.targets.each do |target|
          if !target_filter || target.product_name.match(target_filter) || target.product_type.match(target_filter)
            Helper.log.info "Updating target #{target.product_name}...".green
          else
            Helper.log.info "Skipping target #{target.product_name} as it doesn't match the filter '#{target_filter}'".yellow
            next
          end
```

**Comment by jcavar** [comment]
We also have a problem with this. It seems that productName property is not changed when you rename target, and we couldn't find a way to change it in Xcode. We fixed it by opening pbxproj manually and changing it.

**Comment by KrauseFx** [comment]
I'm more than happy to merge a pull request for this, but you shouldn't use this action. Instead check out [match](https://github.com/fastlane/match)

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
