### ISSUE TITLE
Feature: Integrate with Facebooks Buck tool

### ISSUE THREAD

**Issue by weibel** [fastlane/fastlane#7990]
Has anyone looked into integrating Facebooks Buck tool with Fastlane?
https://buckbuild.com/

**Comment by asfalcone** [comment]
This sounds like it would be a great [plugin](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins) @weibel 👍  Going to close this out since we don't currently have a plan to implement this as a feature.
