### ISSUE TITLE
gym `skip_build_archive` still requires to specify a scheme

### ISSUE THREAD

**Issue by t089** [fastlane/fastlane#7991]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using `gym`'s `skip_build_archive` option to export an IPA from an existing xcarchive, gym still asks for a scheme. This is not necessary, as the no build process is required. Or am I missing something?

Please check the output below, these two commands should not be necessary:

```
$ xcodebuild -list -workspace ./MyApp.xcworkspace
Select Scheme: 
$ xcodebuild clean -showBuildSettings -workspace ./MyApp.xcworkspace -scheme MyApp
```

My plan is to separate the build process from the export part. This allows me to create from one archive several IPAs for different purposes (adhoc, TestFlight, etc). Also this allows me to re-export the same IPA once new devices have been added to a provisioning profile without the need to rebuild the app.

**Example from `fastfile`**

```
gym(archive_path: archive_path, 
   skip_build_archive: true, 
   export_method: "ad-hoc", 
   output_directory: "./output"
)
```

### Captured Output

```
INFO [2017-01-25 11:18:06.53]: -----------------
INFO [2017-01-25 11:18:06.53]: --- Step: gym ---
INFO [2017-01-25 11:18:06.53]: -----------------
INFO [2017-01-25 11:18:06.64]: $ xcodebuild -list -workspace ./MyApp.xcworkspace
Select Scheme: 
INFO [2017-01-25 11:18:11.52]: $ xcodebuild clean -showBuildSettings -workspace ./MyApp.xcworkspace -scheme MyApp

+----------------------+---------------------------------------------------------------------------+
|                                      Summary for gym 2.11.0                                      |
+----------------------+---------------------------------------------------------------------------+
| archive_path         | /Users/tobias/Developing/MyApp/MyApp/output/MyApp 2017-01-25 00.20.... |
| skip_build_archive   | true                                                                      |
| export_method        | ad-hoc                                                                    |
| output_directory     | ./output                                                                  |
| workspace            | ./MyApp.xcworkspace                                                      |
| scheme               | MyApp                                                                    |
| destination          | generic/platform=iOS                                                      |
| output_name          | MyApp                                                                    |
| clean                | false                                                                     |
| silent               | false                                                                     |
| use_legacy_build_api | false                                                                     |
| buildlog_path        | ~/Library/Logs/gym                                                        |
| xcode_path           | /Applications/Xcode.app                                                   |
+----------------------+---------------------------------------------------------------------------+

WARN [2017-01-25 11:18:12.51]: Generated plist file with the following values:
INFO [2017-01-25 11:18:12.52]: ▸ -----------------------------------------
INFO [2017-01-25 11:18:12.52]: ▸ {
INFO [2017-01-25 11:18:12.52]: ▸   "method": "ad-hoc"
INFO [2017-01-25 11:18:12.52]: ▸ }
INFO [2017-01-25 11:18:12.52]: ▸ -----------------------------------------
INFO [2017-01-25 11:18:12.52]: This results in the following plist file:
INFO [2017-01-25 11:18:12.52]: ▸ -----------------------------------------
INFO [2017-01-25 11:18:12.52]: ▸ <?xml version="1.0" encoding="UTF-8"?>
INFO [2017-01-25 11:18:12.52]: ▸ <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
INFO [2017-01-25 11:18:12.52]: ▸ <plist version="1.0">
INFO [2017-01-25 11:18:12.52]: ▸ <dict>
INFO [2017-01-25 11:18:12.52]: ▸ 	<key>method</key>
INFO [2017-01-25 11:18:12.52]: ▸ 	<string>ad-hoc</string>
INFO [2017-01-25 11:18:12.52]: ▸ </dict>
INFO [2017-01-25 11:18:12.52]: ▸ </plist>
INFO [2017-01-25 11:18:12.52]: ▸ -----------------------------------------
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

**Comment by awBSH** [comment]
+1
I am facing the same challenge. I want to export an .ipa from an already existing .xcarchive and I am trying to use gym with skip_build_archive:true
Why do I need to provide a Schema?

**Comment by awBSH** [comment]
@t089 Have you solved this meanwhile? Are you able to create an .ipa from an .xcarchive with gym?

**Comment by t089** [comment]
Nope, been using custom bash script instead and then switched from using fastlane/bash/jenkins to sign up with buddybuild instead.

**Comment by awBSH** [comment]
Hmm... ok thanks for the info. Too bad this hasn't been solved...
**fastlane** looks really promising (in the first place)

**Comment by t089** [comment]
Oh, make no mistake: fastlane is awesome.
