### ISSUE TITLE
[Feature proposal] Action for registering devices connected to computer

### ISSUE THREAD

**Issue by SebastianOsinski** [fastlane/fastlane#7992]
Me and my colleague created simple action for getting UDIDs of devices currently connected to computer and registering them in developer portal (by using `register_devices` action). Is there a place and need for such action to be added to this repository (Actions readme states that you don't accept every action)?

**Comment by hjanuschka** [comment]
i think best place is to do a plugin, and if alot of users want/use it - there's room for discussion migratining it into the main release.

plugin documentation: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by SebastianOsinski** [comment]
Thanks for the response! I completely forgot about existence of plugins.

**Comment by KrauseFx** [comment]
Awesome idea, let us know when you've had the time to finish the plugin 👍
