### ISSUE TITLE
Issue whilst using Pilot inside Fastlane

### ISSUE THREAD

**Issue by davidrothera** [fastlane/fastlane#801]
Feel free to close this and I will re-open under Pilot if needed

Whilst using the Pilot action under Fastlane I get errors pretty much every time even though everything works ok.

Usually it gets part way through the "Waiting for build to process" stage and then exits :-1: 

Crash filed under sentry ID `6764314714b4f3d71c2c106b594de2ed` if you want to take a look

**Comment by davidrothera** [comment]
```
[18:54:21]: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Could not generate a response."]}, "statusCode"=>"ERROR"}
```

**Comment by ohwutup** [comment]
Going to close this issue for now @davidrothera, but please, if you're still having the issue, go ahead and open up another issue there or reopen this one. Let us know if you are still running into this with newer-versions of the tools! Thanks :tada:
