### ISSUE TITLE
Turn off xcpretty from within Fastfile?

### ISSUE THREAD

**Issue by szweier** [fastlane/fastlane#8023]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I was just wondering if there was a way within the Fastfile to tell gym not to use xcpretty? I've noticed that while xcpretty seems to be willing to log the compiling of swift files within libraries

`Compiling UnidirectionalBinding.swift` 

it doesn't seem to be willing to log the compiling of swift files within the main code base.  This leads to a fair amount of time being spent without logs making it to my CI server.  When that time reaches a certain point the CI server shuts down due to inactivity.  I believe turning this xcpretty feature off will solve my problem but so far I haven't found a way to do that from within the Fastfile.

**Comment by KrauseFx** [comment]
Yeah, check out `fastlane action gym` and use the `disable_xcpretty` option in your Fastfile:

```ruby
lane :beta do
  gym(disable_xcpretty: true)
```

**Comment by szweier** [comment]
thanks!

**Comment by KrauseFx** [comment]
Glad to hear 👍
