### ISSUE TITLE
scan doesn't show test failures in the output files

### ISSUE THREAD

**Issue by huminzhi** [fastlane/fastlane#8026]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
There are test failures (tests actually crashed), SCAN lists the failed tests in the console log, however, in the output files and in the final summary, it shows all pass. see logs below:

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

...... too many lines.....

Failing tests:
-[SmartSyncTestSuite testSyncUpLocallyCreated]
-[SmartSyncTestSuite testSyncUpLocallyDeleted]
-[SmartSyncTestSuite testSyncUpLocallyDeletedWithNoOverwrite]
-[SmartSyncTestSuite testSyncUpLocallyUpdated]
-[SmartSyncTestSuite testSyncUpLocallyUpdatedWithGlobalStore]
-[SmartSyncTestSuite testSyncUpLocallyUpdatedWithGlobalStoreNamed]
-[SmartSyncTestSuite testSyncUpLocallyUpdatedWithNoOverwrite]
** TEST FAILED **

The following commands produced analyzer issues:
Analyze Views/RCTMapManager.m
Analyze Modules/RCTRedBox.m
(2 commands with analyzer issues)
[00:05:25]: Exit status: 65
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 622   |
| Number of failures | **0**     |
+--------------------+-------+

[00:37:46]: Successfully generated report at '/Users/mhu/dev/SalesforceMobileSDK/iOS/test_output/report.html'
[00:37:57]: Successfully generated report at '/Users/mhu/dev/SalesforceMobileSDK/iOS/test_output/report.junit'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G1212)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
if !ENV["device"] or ENV["device"]==""
	ENV["device"] = "iPhone 6"
end

if !ENV["scheme"] or ENV["scheme"]==""
	ENV["scheme"] = "UnitTests"
end

$Jenkins = false
if ENV["JENKINS_URL"]
  $Jenkins = true
end

$GITPRAPI = "https://api.github.com/repos/forcedotcom/SalesforceMobileSDK-iOS/pulls/%s/files"
$schemes = ["SalesforceAnalytics", "SalesforceHybridSDK", "SalesforceReact", "SalesforceSDKCore", "SmartStore", "SmartSync"]
$schemesWithUnitTests = Array.new($schemes)
$schemesWithUnitTests.push("UnitTests")

system("/usr/libexec/PlistBuddy -c \"add :ConnectHardwareKeyboard bool 0\" ~/Library/Preferences/com.apple.iphonesimulator.plist || /usr/libexec/PlistBuddy -c \"set :ConnectHardwareKeyboard 0\" ~/Library/Preferences/com.apple.iphonesimulator.plist")
system("rm -r $HOME/Library/Developer/Xcode/DerivedData/SalesforceMobileSDK-*")

def doDanger
	if $Jenkins
		begin
			 danger(
				 danger_id: "CI-result",
				 dangerfile: "DangerFile",
				 github_api_token: ENV["DANGER_GITHUB_API_TOKEN"],
				 verbose: true
			 )
		 rescue => ex
			 UI.error(ex)
		 end
	end
end


def testScheme(scheme)
	scan(
		workspace: "SalesforceMobileSDK.xcworkspace",
		scheme: scheme,
		device: ENV["device"],
		output_directory: "test_output”,
		code_coverage: true,
		clean: true
	)

	begin
		xcodebuild(
		 	xcargs: "CLANG_ANALYZER_OUTPUT=plist-html CLANG_ANALYZER_OUTPUT_DIR=./clangReport RUN_CLANG_STATIC_ANALYZER=YES",
		 	workspace: "SalesforceMobileSDK.xcworkspace",
		 	scheme: scheme,
		 	fail_build: false
		)
	rescue => ex
		UI.error(ex)
	ensure
		#move clangReports to one folder
		system("mkdir -p ../clangReport/StaticAnalyzer")
		system("mv ../libs/SalesforceAnalytics/clangReport/StaticAnalyzer/SalesforceAnalytics ../clangReport/StaticAnalyzer/")
		system("mv ../libs/SalesforceHybridSDK/clangReport/StaticAnalyzer/SalesforceHybridSDK ../clangReport/StaticAnalyzer/")
		system("mv ../libs/SalesforceReact/clangReport/StaticAnalyzer/SalesforceReact ../clangReport/StaticAnalyzer/")
		system("mv ../libs/SalesforceSDKCore/clangReport/StaticAnalyzer/SalesforceSDKCore ../clangReport/StaticAnalyzer/")
		system("mv ../libs/SmartStore/clangReport/StaticAnalyzer/SmartStore ../clangReport/StaticAnalyzer/")
		system("mv ../libs/SmartSync/clangReport/StaticAnalyzer/SmartSync ../clangReport/StaticAnalyzer/")
	end

  xcov(
    workspace: "SalesforceMobileSDK.xcworkspace",
    scheme: scheme,
    output_directory: "xcov_output",
    exclude_targets: "CocoaLumberjack.framework,SalesforceSDKCoreTestApp.app,SmartStoreTestApp.app,SmartSyncTestApp.app,SalesforceHybridSDKTestApp.app,SalesforceAnalyticsTestApp.app,RestAPIExplorer.app,AccountEditor.app,NoteSync.app,SmartSyncExplorerHybrid.app,SmartSyncExplorer.app,SmartSyncExplorerCommon.framework,RecentContactsTodayExtension.appexs"
  )

  schemes = [scheme]
  if scheme.include?("UnitTests")
     schemes = $schemes
  end
  for oneScheme in schemes
  	slather(
  		workspace: "SalesforceMobileSDK.xcworkspace",
  		scheme: oneScheme,
  		output_directory: "slather_output/#{oneScheme}",
      html: true,
      jenkins: $Jenkins,
      cobertura_xml: true,
      proj: "./libs/%s/%s.xcodeproj" %[oneScheme, oneScheme]
  	)
  end
end

lane :PR do
	schemes = Set.new
	if ENV["ghprbPullId"] && ENV["gitToken"]
		prFilesAPI = $GITPRAPI % ENV["ghprbPullId"]
		curlCommand = "curl %s -H 'Authorization: token %s'" % [prFilesAPI, ENV["gitToken"]]
		pullfiles = `#{curlCommand}`
		prfiles = JSON.parse(pullfiles)
		for prfile in prfiles
			path = prfile["filename"]
      for scheme in $schemes
  			if path.include? scheme
  				schemes = schemes.add(scheme)
  			end
      end
		end
		puts "schemes:" + schemes.to_a().join(",")
	end

	if schemes.size == 0
			schemes = ENV["scheme"].split(',')
	end

	if schemes.size >= 3 || schemes.include?("UnitTests")
		testScheme("UnitTests")
		doDanger
	else
		for scheme in schemes
			testScheme(scheme)
			doDanger
		end
	end
end

lane :LCL do
  index = 1
	puts "Select scheme:"
	for scheme in $schemesWithUnitTests
			puts index.to_s + ": " + scheme
			index = index + 1
	end

	print "Just enter a number:"
	selection = STDIN.gets.strip

	testScheme($schemesWithUnitTests[selection.to_i-1])

end

lane :CI do
	testScheme("UnitTests")
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.9.0   | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.53.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.0       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| bundler                   | 1.13.7       |
</details>

*generated on:* **2017-01-26**
</details>

**Comment by realf** [comment]
I can confirm the same behavior of `fastlane scan` with Xcode 8.2.1 on macOS 10.12.2.

**Comment by mgrebenets** [comment]
@realf Have you looked inside the actual `xcodebuild` log?
You can use `scan`'s `buildlog_path` option to specify output dir for log path.

It there are no details in the original log, then `xcpretty` would not be able to pick them up and parse.

If the original build log has errors, then probably we'd have to open pull request to `xcpretty`.

**Comment by realf** [comment]
If I understand the problem correctly, either `xcpretty`, or `fastlane scan` misses some tests. For example, **8 tests were run, 1 failed**, but we see, that `fastlane` reports about **7 tests and 0 failures**.

```
...
16:48:34 All tests
16:48:34 Test Suite UITests.xctest started
16:48:34 NGTrialPassTests
16:48:34 RewardsExtendedTests
16:48:34 ✓ testRejectTermsAndConditions (22.303 seconds)
16:48:34 ✓ testRewardsList (33.495 seconds)
16:48:34 StandardizedFlowTests
16:48:34 ✓ testInterstitialScreenStandardisedFlowWithLFIdentityProvider (9.874 seconds)
16:48:34 ✓ testLoginAsGuest (11.937 seconds)
16:48:34 ✓ testWelcomeScreenStandardisedFlow (7.807 seconds)
16:48:34 ✓ testWelcomeScreenStandardisedFlowWithGuestPassGuestMode (11.400 seconds)
16:48:34 ✓ testWelcomeScreenStandardisedFlowWithGuestPassNoGuestMode (7.750 seconds)
16:48:34 
16:48:34 
16:48:34 	 Executed 8 tests, with 1 failure (1 unexpected) in 147.675 (147.738) seconds
16:48:34 
16:48:34 Failing tests:
16:48:34 -[NGTrialPassTests testTrialPassSuccessfulScenarioAndFieldValidations]
16:48:34 ** TEST FAILED **
16:48:34 [16:48:34]: Exit status: 65
16:48:35 +--------------------+-------+
16:48:35 |        Test Results        |
16:48:35 +--------------------+-------+
16:48:35 | Number of tests    | 7     |
16:48:35 | Number of failures | 0     |
16:48:35 +--------------------+-------+
...
```

Here is what I found in `scan`'s buildlog:
```
...
Test Case '-[NGTrialPassTests testTrialPassSuccessfulScenarioAndFieldValidations]' failed (43.110 seconds).
Test Suite 'NGTrialPassTests' failed at 2017-02-03 16:46:50.082.
	 Executed 1 test, with 1 failure (1 unexpected) in 43.110 (43.152) seconds
...
Test Suite 'UITests.xctest' failed at 2017-02-03 16:48:34.668.
	 Executed 8 tests, with 1 failure (1 unexpected) in 147.675 (147.738) seconds
Test Suite 'All tests' failed at 2017-02-03 16:48:34.670.
	 Executed 8 tests, with 1 failure (1 unexpected) in 147.675 (147.742) seconds
```

**Comment by mgrebenets** [comment]
@realf 
From the output looks like `xcpretty` did pick them up and reported, but then there is a bug in the code that generates the `Test Results` table.

I think we may even have this issue in our project, but never noticed, because we just use `junit` test report for CI integration.

In any case, this looks like a bug in reporting tests summary. Thanks for spotting it 👍

**Comment by mgrebenets** [comment]
@realf Oh, wait, did you also mean that `report.html` and `report.junit` have no failed tests in them?

**Comment by realf** [comment]
Yes, it was absent in reports.
We have a custom script to restart UI tests that fail sometimes because of Apple's bug, but now with this bug some failing tests din't fail test suit, causing false positives.

Sergey Dunets

**Comment by realf** [comment]
To illustrate my previous comment, I'd like to add an extract of our test logs on CI. 
```
16:26:37 ✗ testRejectTermsAndConditions, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 ✗ testRewardsList, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 StandardizedFlowTests
16:26:37 ✗ testInterstitialScreenStandardisedFlowWithLFIdentityProvider, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 ✗ testLoginAsGuest, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 ✗ testWelcomeScreenStandardisedFlow, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 ✗ testWelcomeScreenStandardisedFlowWithGuestPassGuestMode, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 ✗ testWelcomeScreenStandardisedFlowWithGuestPassNoGuestMode, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 
16:26:37 
16:26:37 UITests.RewardsExtendedTests
16:26:37 testRejectTermsAndConditions, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 <unknown>:0
16:26:37 
16:26:37 testRewardsList, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 <unknown>:0
16:26:37 
16:26:37 UITests.StandardizedFlowTests
16:26:37 testInterstitialScreenStandardisedFlowWithLFIdentityProvider, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 <unknown>:0
16:26:37 
16:26:37 testLoginAsGuest, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 <unknown>:0
16:26:37 
16:26:37 testWelcomeScreenStandardisedFlow, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 <unknown>:0
16:26:37 
16:26:37 testWelcomeScreenStandardisedFlowWithGuestPassGuestMode, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 <unknown>:0
16:26:37 
16:26:37 testWelcomeScreenStandardisedFlowWithGuestPassNoGuestMode, UI Testing Failure - Failure attempting to launch <XCUIApplicationImpl: 0x7fc72dc45d60 com.Company.TheApp.inhouse at /Users/jenkins/Library/Developer/Xcode/DerivedData/product-ayeybvhadfuubdftdfygzjnazjvr/Build/Products/UITests-iphonesimulator/TheApp.app>: Error Domain=IDEPseudoTerminalDomain Code=1 "(null)"
16:26:37 <unknown>:0
16:26:37 
16:26:37 
16:26:37 	 Executed 132 tests, with 10 failures (3 unexpected) in 3378.525 (3378.967) seconds
16:26:37 
16:26:37 Failing tests:
16:26:37 -[NGABCFlowSignUpTests testSuccessfulSignUpScreen2]
16:26:37 -[NGStandardizedFlowSignInTests testSignInWithNonExistingEmailWithNeedHelp]
16:26:37 -[NGTrialPassTests testTrialPassSuccessfulScenarioAndFieldValidations]
16:26:37 -[RewardsExtendedTests testRejectTermsAndConditions()]
16:26:37 -[RewardsExtendedTests testRewardsList()]
16:26:37 -[StandardizedFlowTests testInterstitialScreenStandardisedFlowWithLFIdentityProvider()]
16:26:37 -[StandardizedFlowTests testLoginAsGuest()]
16:26:37 -[StandardizedFlowTests testWelcomeScreenStandardisedFlow()]
16:26:37 -[StandardizedFlowTests testWelcomeScreenStandardisedFlowWithGuestPassGuestMode()]
16:26:37 -[StandardizedFlowTests testWelcomeScreenStandardisedFlowWithGuestPassNoGuestMode()]
16:26:37 ** TEST FAILED **
```
Note, **10** tests failed.


```
16:26:37 [16:26:37]: Exit status: 65
16:26:50 +--------------------+-------+
16:26:50 |        Test Results        |
16:26:50 +--------------------+-------+
16:26:50 | Number of tests    | 129   |
16:26:50 | Number of failures | 7     |
16:26:50 +--------------------+-------+
16:26:50 
16:27:04 [16:27:05]: Successfully generated report at '/tmp/Logs/scan/2017-02-06_15-23-51/output/report.html'
16:27:18 [16:27:18]: Successfully generated report at '/tmp/Logs/scan/2017-02-06_15-23-51/output/report.junit'
16:27:18 
16:27:18 [!] Test execution failed. Exit status: 65
16:27:18 NG_TESTS_FAILED
```
Note, **7** tests were reported as failed and this is what I can actually find in `/tmp/Logs/scan/2017-02-06_15-23-51/output/report.html`.
This is why we are retrying only 7 tests of 10 that actually failed.

We retry only 7 tests.
```
16:27:19 Retrying tests:
16:27:19 UITests.RewardsExtendedTests
16:27:19 testRejectTermsAndConditions
16:27:19 UITests.RewardsExtendedTests
16:27:19 testRewardsList
16:27:19 UITests.StandardizedFlowTests
16:27:19 testInterstitialScreenStandardisedFlowWithLFIdentityProvider
16:27:19 UITests.StandardizedFlowTests
16:27:19 testLoginAsGuest
16:27:19 UITests.StandardizedFlowTests
16:27:19 testWelcomeScreenStandardisedFlow
16:27:19 UITests.StandardizedFlowTests
16:27:19 testWelcomeScreenStandardisedFlowWithGuestPassGuestMode
16:27:19 UITests.StandardizedFlowTests
16:27:19 testWelcomeScreenStandardisedFlowWithGuestPassNoGuestMode
```

And this is a result:
```
16:27:41 [16:27:42]: ▸ Test Suite UITests.xctest started
16:27:41 [16:27:42]: ▸ RewardsExtendedTests
16:28:02 [16:28:03]: ▸ ✓ testRejectTermsAndConditions (21.150 seconds)
16:28:33 [16:28:34]: ▸ ✓ testRewardsList (31.091 seconds)
16:28:33 [16:28:34]: ▸ StandardizedFlowTests
16:28:43 [16:28:44]: ▸ ✓ testInterstitialScreenStandardisedFlowWithLFIdentityProvider (9.613 seconds)
16:28:53 [16:28:54]: ▸ ✓ testLoginAsGuest (10.518 seconds)
16:29:01 [16:29:02]: ▸ ✓ testWelcomeScreenStandardisedFlow (7.658 seconds)
16:29:12 [16:29:13]: ▸ ✓ testWelcomeScreenStandardisedFlowWithGuestPassGuestMode (11.313 seconds)
16:29:20 [16:29:21]: ▸ ✓ testWelcomeScreenStandardisedFlowWithGuestPassNoGuestMode (7.594 seconds)
16:29:20 [16:29:21]: ▸ 	 Executed 7 tests, with 0 failures (0 unexpected) in 98.937 (98.957) seconds
16:29:20 [16:29:21]: ▸ 
16:29:20 [16:29:21]: ▸ Test Succeeded
16:29:21 +--------------------+-------+
16:29:21 |        Test Results        |
16:29:21 +--------------------+-------+
16:29:21 | Number of tests    | 7     |
16:29:21 | Number of failures | 0     |
16:29:21 +--------------------+-------+
16:29:21 
16:29:23 [16:29:23]: Successfully generated report at '/tmp/Logs/scan/2017-02-06_16-27-20/output/report.html'
16:29:24 [16:29:25]: Successfully generated report at '/tmp/Logs/scan/2017-02-06_16-27-20/output/report.junit'

16:29:28 Finished: SUCCESS
```
All 7 pass, and this is can be a false positive since we did not retry 3 tests that failed the previous time we run the full test suite.

**Comment by garie** [comment]
I am experiencing the same issue. The Test Results table reports 0 failures and an incorrect number of tests (total number minus actual failures). This finishes with "success", which allows our Bamboo build to succeed, which is not good behavior.

**Comment by mgrebenets** [comment]
I'm pretty sure this is related: https://github.com/supermarin/xcpretty/issues/87
Looks like we need a fix in `xcpretty` dependency.

**Comment by garie** [comment]
I agree. I did some research yesterday and it looks like all of my tests which aren't included had some other log output interrupt them. As a workaround, I switched log level to .error instead of .info but that doesn't fix all of my issues because we're using a library that doesn't allow specification of log level.

**Comment by realf** [comment]
I am not sure if it is related, but it seems that `fastlane` sometimes doesn't report tests as failed when `xcpretty` marks them as `unexpected`.

**Comment by realf** [comment]
Are there any updates on this issue?
