### ISSUE TITLE
gym select signing team

### ISSUE THREAD

**Issue by oliverfoggin** [fastlane/fastlane#8029]
In Xcode project settings in the "Signing" section you can select the "Team" from a drop down...

<img width="745" alt="screen shot 2017-01-27 at 10 35 24" src="https://cloud.githubusercontent.com/assets/1813244/22368043/88e9a706-e47c-11e6-8a6b-84969d0c050f.png">

However, when running `gym` with the following parameters...

	gym(
		export_method: 'app-store',
		scheme: 'SchemeName',
		export_team_id: theSigningTeamIWantToUse
	)

It seems to not be able to change that team.

The situation I am in is as follows...

The dev has been done on my company's Apple Dev team. The bundle id is defined on my company's dev portal and so on... However, the release is being done under the company's dev portal who own's the app. So we need to use the other company's team for release and our team for dev. (If that makes sense).

So... I can change the bundle id in the fastfile. But I can't find anything to change the signing team.

Is that something that is possible? At the moment we have to manually change the team each time we do a release and then change it back again.

Thanks

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.108.0"

default_platform :ios

gospelware_app_id = 'uk.co.gospelware.ChangingHealth'
gospelware_team_id = '7AY2EKKTUQ'

changingHealth_app_id = 'com.changingHealth.CHealth'
changingHealth_team_id = 'S8XM7THS3G'
changingHealth_team_name = 'Changing Health Limited'

#options:
# test_email: tester to invite
# version_number: version number
# build_number: build number
# message_header: message to add to front of Change Log

before_all do |lane, options|
	cocoapods
end

lane :beta do |options|
	update_info_plist(
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealth'
	)

	register_devices(
		devices_file: "./devices.txt",
		team_id: gospelware_team_id,
		username: ENV['USERNAME']
	)

	match(
		force_for_new_devices: true,
		type: "development",
		team_id: gospelware_team_id,
		app_identifier: gospelware_app_id,
		username: ENV['USERNAME']
	)

	increment_version_number(
		version_number: options[:version_number]
	)
	
	increment_build_number(
		build_number: options[:build_number]
	)

	gym(
		export_method: 'development',
		scheme: 'ChangingHealth'
	)

	emails = options[:test_email] ? options[:test_email] : nil
	groups = options[:test_email] ? nil : ['dev-team', 'gospelware', 'changing-health']

	changelog = changelog_from_git_commits(
		pretty: '%s',
		merge_commit_filtering: 'exclude_merges'
	)

	messageHeader = options[:message_header] ? options[:message_header] + '

' :  ''
	message = messageHeader + changelog

	crashlytics(
		api_token: '92a08cdcd474667c5d52a3099d4c74e3b3578bd4',
		build_secret: 'e0a44fae0ab0acdf575be3a4217bf2e54b8901558903ff071c549567304f131b',
		emails: emails,
		groups: groups,
		notes: message,
		notifications: true
	)
end

lane :screenshots do |options|
	update_info_plist(
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealth'
	)

	snapshot(
		clear_previous_screenshots: true,
		reinstall_app: true,
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealthSnapshots',
		devices: ['iPhone 4s', 'iPhone SE', 'iPhone 7', 'iPhone 7 Plus'],
		languages: ['en-GB']
	)
end

lane :deploy do |options|
#	screenshots

	update_info_plist(
		app_identifier: changingHealth_app_id,
		scheme: 'ChangingHealth'
	)

	register_devices(
		devices_file: "./devices.txt",
		team_id: changingHealth_team_id,
		username: ENV['APPSTORE_USERNAME']
	)

	increment_version_number(
		version_number: options[:version_number]
	)

	increment_build_number(
		build_number: options[:build_number]
	)

	produce(
		username: ENV['APPSTORE_USERNAME'],
	  	app_identifier: changingHealth_app_id,
	  	app_name: 'Changing Health',
	  	app_version: options[:version_number],
	  	sku: 'ChangingHealth1',
	  	company_name: 'Changing Health Limited',
		team_id: changingHealth_team_id,
		team_name: changingHealth_team_name,
		itc_team_name: changingHealth_team_name
	)

	match(
		app_identifier: changingHealth_app_id,
		type: 'appstore',
	   	team_id: changingHealth_team_id,
	  	username: ENV['APPSTORE_USERNAME']
	)

	gym(
		export_method: 'app-store',
		scheme: 'ChangingHealth',
		export_team_id: changingHealth_team_id
	)

	appstore(
		overwrite_screenshots: true,
		username: ENV['APPSTORE_USERNAME'],
		force: true,
		app_icon: './fastlane/metadata/appIcon.png',
		app_rating_config_path: './fastlane/metadata/app_rating_config.txt',
		app_review_information: {
			first_name: "Oliver",
			last_name: "Foggin",
			phone_number: "+44 7973791713",
			email_address: "oliver@gospelware.co.uk",
			demo_user: "appletest@changinghealth.com",
			demo_password: "password",
			notes: ""
		}
	)

	update_info_plist(
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealth'
	)

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.1.1        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.5        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-27**
</details>

**Comment by oliverfoggin** [comment]
Just to clarify. The `match` and `register_devices` scripts work correctly as I am able to pass in all the team information to them separately from what Xcode has. The only issue is that gym seems to take the signing team directly from what is selected in Xcode.

**Comment by hjanuschka** [comment]
@oliverfoggin  i am not 100% sure if export_team_id works with the recent signing changes inside xcode.


you could go into your xcode target and set the team id to the one that match proposes.:



eg. my match output: 

```
+---------------------+-----------------------------------------------+--------------------------------------+
|                                       Installed Provisioning Profile                                       |
+---------------------+-----------------------------------------------+--------------------------------------+
| Parameter           | Environment Variable                          | Value                                |
+---------------------+-----------------------------------------------+--------------------------------------+
| App Identifier      |                                               | krone.at-fivexfive                   |
| Type                |                                               | appstore                             |
| Profile UUID        | sigh_krone.at-fivexfive_appstore              | d1635f5a-b294-4da4-a685-125f59f6449b |
| Profile Name        | sigh_krone.at-fivexfive_appstore_profile-name | match AppStore krone.at-fivexfive    |
| Development Team ID | sigh_krone.at-fivexfive_appstore_team-id      | H2YB79SEHH                           |
+---------------------+-----------------------------------------------+--------------------------------------+
```


and setting development team to `$(sigh_krone.at-fivexfive_appstore_team-id)``
![bildschirmfoto 2017-01-27 um 20 37 47](https://cloud.githubusercontent.com/assets/2891702/22384865/861773ce-e4d0-11e6-8c4f-c370dcfd494c.png)





you could also use [fastlane-plugin_update_project_codesigning](https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning)

and configure your project (team_id and signing, to use the `$()`  envs from match, on the release build)


and before doing the release build something like this (whereas in dev. you stay on autosigning.)


```
update_project_codesigning(
    path: "demo-project/demo/demo.xcodeproj",
    use_automatic_signing: false
  )
```

once autosigning is disabled, it uses the `$()`  envs that match set's .


let me know if this helps, or if you need anything else.

**Comment by simonarcher** [comment]
I managed to get the `export_team_id ` argument to work recently with `gym`. I just found the Team ID from the Apple Developer portal, and seem to select it correctly with no problem..

did you get the Team ID from this page?
https://developer.apple.com/account/#/membership/
<img width="259" alt="screen shot 2017-01-29 at 8 51 36 pm" src="https://cloud.githubusercontent.com/assets/10696147/22406917/d866f27c-e664-11e6-9eb7-df178e7a99db.png">

**Comment by oliverfoggin** [comment]
@simonarcher yes. That's the team ID I put in there. The only problem is that it doesn't seem to make a difference. The problem (I think) is that the team and bundle id selected in Xcode is NOT the team or bundle id I want to use for release builds.

I can change the bundle id but then it complains that the bundle id can't be found for the original team id. That is correct. Because it still thinks the team id is the original one (it even puts it in the console). Even when I put the new team id into the gym function.

The only way I have found to do it so far is to manually change it in Xcode before it builds.
