### ISSUE TITLE
deliver metadata file formats and file structure

### ISSUE THREAD

**Issue by oliverfoggin** [fastlane/fastlane#8036]
I'm trying to set up the `./fastlane/metadata/` directory and file structure. I think I've got the file structure correct but various parts of the metadata are not being uploaded correctly.

Some of the metadata works when I put it in the fastfile parameters but when I try to put it into the file structure it is either ignored or it seems to remove those particular settings from the iTunesConnect app.

	deliver(
		overwrite_screenshots: true,
		username: ENV['APPSTORE_USERNAME'],
		force: true,
		app_icon: './fastlane/metadata/appIcon.png',
		app_rating_config_path: './fastlane/metadata/app_rating_config.txt',
		app_review_information: {
			first_name: "Oliver",
			last_name: "Foggin",
			phone_number: "My Phone Number",
			email_address: "oliver@email.com",
			demo_user: "blah@blah.com",
			demo_password: "*******",
			notes: ""
		}
	)

This is what I currently have in my fastfile. It's here because when I tried to add this information in a folder and txt files it was seemingly ignored or removed from iTC.

When I added file `./fastlane/metadata/app_icon.txt` with the contents `./fastlane/metadata/appIcon.png` the app icon was ignored (and then removed after I added it manually and did another upload with deliver).

This is the same with the `marketing_url`. I added the parameter ... `marketing_url: www.blah.com` to the fastfile and it told me it needed to be a hash with the language as the key. That makes sense. But when I add a file in the `en-GB` folder with the name `marketing_url.txt` and the contents `http://www.blah.com` it does't get added to iTC.

This is my current folder structure...

<img width="634" alt="screen shot 2017-01-27 at 11 26 43" src="https://cloud.githubusercontent.com/assets/1813244/22369399/900326be-e483-11e6-9665-db005bf36a28.png">

This was initially created by the `deliver init` method and is a pretty much exact copy of the one in the deliver docs.

The description, name and keywords are all uploading correctly so I know it's correct up to a point. So are things like the primary and secondary category and the copyright.

The app review information and app icon are now being added correctly but only when I add the parameters in the fastfile.

I am just struggling to understand WHAT can be added as metadata in a txt file and HOW to add each bit?

My initial guess is that EVERYTHING listed as "Metadata:" in the deliver help can be added as a text file. I just don't know what format the text file needs and whether or not I need to link to it?

### Deliver Metadata Parameters

| Key                           | Descrpition                                                                                               |
|-------------------------------|-----------------------------------------------------------------------------------------------------------|
| app_icon                      | Metadata: The path to the app icon                                                                        |
| apple_watch_app_icon          | Metadata: The path to the Apple Watch app icon                                                            |
| copyright                     | Metadata: The copyright notice                                                                            |
| primary_category              | Metadata: The english name of the primary category(e.g. `Business`, `Books`)                              |
| secondary_category            | Metadata: The english name of the secondary category(e.g. `Business`, `Books`)                            |
| primary_first_sub_category    | Metadata: The english name of the primary first sub category(e.g. `Educational`, `Puzzle`)                |
| primary_second_sub_category   | Metadata: The english name of the primary second sub category(e.g. `Educational`, `Puzzle`)               |
| secondary_first_sub_category  | Metadata: The english name of the secondary first sub category(e.g. `Educational`, `Puzzle`)              |
| secondary_second_sub_category | Metadata: The english name of the secondary second sub category(e.g. `Educational`, `Puzzle`)             |
| app_review_information        | Metadata: A hash containing the review information                                                        |
| description                   | Metadata: The localised app description                                                                   |
| name                          | Metadata: The localised app name                                                                          |
| keywords                      | Metadata: An array of localised keywords                                                                  |
| release_notes                 | Metadata: Localised release notes for this version                                                        |
| privacy_url                   | Metadata: Localised privacy url                                                                           |
| support_url                   | Metadata: Localised support url                                                                           |
| marketing_url                 | Metadata: Localised marketing url                                                                         |

Similarly there is an `app_rating_config_path` what content goes into the file in this path? I have tried to upload it and provide the path but it doesn't add the rating info.

Thanks

Oliver

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.108.0"

default_platform :ios

gospelware_app_id = 'uk.co.gospelware.ChangingHealth'
gospelware_team_id = '7AY2EKKTUQ'

changingHealth_app_id = 'com.changingHealth.CHealth'
changingHealth_team_id = 'S8XM7THS3G'
changingHealth_team_name = 'Changing Health Limited'

#options:
# test_email: tester to invite
# version_number: version number
# build_number: build number
# message_header: message to add to front of Change Log

before_all do |lane, options|
	cocoapods
end

lane :beta do |options|
	update_info_plist(
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealth'
	)

	register_devices(
		devices_file: "./devices.txt",
		team_id: gospelware_team_id,
		username: ENV['USERNAME']
	)

	match(
		force_for_new_devices: true,
		type: "development",
		team_id: gospelware_team_id,
		app_identifier: gospelware_app_id,
		username: ENV['USERNAME']
	)

	increment_version_number(
		version_number: options[:version_number]
	)
	
	increment_build_number(
		build_number: options[:build_number]
	)

	gym(
		export_method: 'development',
		scheme: 'ChangingHealth'
	)

	emails = options[:test_email] ? options[:test_email] : nil
	groups = options[:test_email] ? nil : ['dev-team', 'gospelware', 'changing-health']

	changelog = changelog_from_git_commits(
		pretty: '%s',
		merge_commit_filtering: 'exclude_merges'
	)

	messageHeader = options[:message_header] ? options[:message_header] + '

' :  ''
	message = messageHeader + changelog

	crashlytics(
		api_token: '92a08cdcd474667c5d52a3099d4c74e3b3578bd4',
		build_secret: 'e0a44fae0ab0acdf575be3a4217bf2e54b8901558903ff071c549567304f131b',
		emails: emails,
		groups: groups,
		notes: message,
		notifications: true
	)
end

lane :screenshots do |options|
	update_info_plist(
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealth'
	)

	snapshot(
		clear_previous_screenshots: true,
		reinstall_app: true,
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealthSnapshots',
		devices: ['iPhone 4s', 'iPhone SE', 'iPhone 7', 'iPhone 7 Plus'],
		languages: ['en-GB']
	)
end

lane :deploy do |options|
#	screenshots

	update_info_plist(
		app_identifier: changingHealth_app_id,
		scheme: 'ChangingHealth'
	)

	register_devices(
		devices_file: "./devices.txt",
		team_id: changingHealth_team_id,
		username: ENV['APPSTORE_USERNAME']
	)

	increment_version_number(
		version_number: options[:version_number]
	)

	increment_build_number(
		build_number: options[:build_number]
	)

	produce(
		username: ENV['APPSTORE_USERNAME'],
	  	app_identifier: changingHealth_app_id,
	  	app_name: 'Changing Health',
	  	app_version: options[:version_number],
	  	sku: 'ChangingHealth1',
	  	company_name: 'Changing Health Limited',
		team_id: changingHealth_team_id,
		team_name: changingHealth_team_name,
		itc_team_name: changingHealth_team_name
	)

	match(
		app_identifier: changingHealth_app_id,
		type: 'appstore',
	   	team_id: changingHealth_team_id,
	  	username: ENV['APPSTORE_USERNAME']
	)

	gym(
		export_method: 'app-store',
		scheme: 'ChangingHealth',
		export_team_id: changingHealth_team_id
	)

	appstore(
		overwrite_screenshots: true,
		username: ENV['APPSTORE_USERNAME'],
		force: true,
		app_icon: './fastlane/metadata/appIcon.png',
		app_rating_config_path: './fastlane/metadata/app_rating_config.txt',
		app_review_information: {
			first_name: "Oliver",
			last_name: "Foggin",
			phone_number: "+44 7973791713",
			email_address: "oliver@gospelware.co.uk",
			demo_user: "appletest@changinghealth.com",
			demo_password: "password",
			notes: ""
		}
	)

	update_info_plist(
		app_identifier: gospelware_app_id,
		scheme: 'ChangingHealth'
	)

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.1.1        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.5        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-27**
</details>

**Comment by KrauseFx** [comment]
Hey @oliverfoggin, really sorry for the delayed reply. Are you still running into this? The documentation isn't clear and up to date for this unfortunately.

**Comment by oliverfoggin** [comment]
Hi @KrauseFx no I never managed to get this working.

We gave up in the end and just left it in the fast file.

However I have since left that company and I'm working somewhere else so I won't be able to fix it.

If you could get some docs in I can let them know and hopefully they can sort it.
