### ISSUE TITLE
Google Api Error: noActiveApks

### ISSUE THREAD

**Issue by rostopira** [fastlane/fastlane#8037]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm getting `Google Api Error: noActiveApks`, but app already have 17 apks in beta, so it's strange

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/Appfile'
- json_key_file: './google_play_key.json'
- package_name: 'gl.kid.alert'
-------
DEBUG [2017-01-27 17:07:26.77]: Checking if there are any plugins that should be loaded...
INFO [2017-01-27 17:07:26.84]: -------------------------------------------------
INFO [2017-01-27 17:07:26.84]: --- Step: Verifying required fastlane version ---
INFO [2017-01-27 17:07:26.84]: -------------------------------------------------
INFO [2017-01-27 17:07:26.84]: Your fastlane version 2.12.0 matches the minimum requirement of 2.12.0  ✅
INFO [2017-01-27 17:07:26.85]: ------------------------------
INFO [2017-01-27 17:07:26.85]: --- Step: default_platform ---
INFO [2017-01-27 17:07:26.85]: ------------------------------
INFO [2017-01-27 17:07:26.85]: Driving the lane 'android beta' 🚀
INFO [2017-01-27 17:07:26.86]: --------------------
INFO [2017-01-27 17:07:26.86]: --- Step: supply ---
INFO [2017-01-27 17:07:26.86]: --------------------
Successfully loaded Appfile at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/Appfile'
- json_key_file: './google_play_key.json'
- package_name: 'gl.kid.alert'
-------
Successfully loaded Appfile at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/Appfile'
- json_key_file: './google_play_key.json'
- package_name: 'gl.kid.alert'
-------
Successfully loaded Appfile at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/Appfile'
- json_key_file: './google_play_key.json'
- package_name: 'gl.kid.alert'
-------
Successfully loaded Appfile at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/Appfile'
- json_key_file: './google_play_key.json'
- package_name: 'gl.kid.alert'
-------
Successfully loaded Appfile at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/Appfile'
- json_key_file: './google_play_key.json'
- package_name: 'gl.kid.alert'
-------
Successfully loaded Appfile at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/Appfile'
- json_key_file: './google_play_key.json'
- package_name: 'gl.kid.alert'
-------

+-------------------------+-----------------------------+
|               Summary for supply 2.12.0               |
+-------------------------+-----------------------------+
| track                   | beta                        |
| package_name            | gl.kid.alert                |
| rollout                 | 0.1                         |
| metadata_path           | ./fastlane/metadata/android |
| json_key                | ./google_play_key.json      |
| skip_upload_apk         | false                       |
| skip_upload_metadata    | false                       |
| skip_upload_images      | false                       |
| skip_upload_screenshots | false                       |
| validate_only           | false                       |
+-------------------------+-----------------------------+

DEBUG [2017-01-27 17:07:29.75]: Fetching a new access token from Google...
INFO [2017-01-27 17:07:31.01]: Preparing to upload for language 'en-US'...
INFO [2017-01-27 17:07:32.02]: Uploading image file ./fastlane/metadata/android/en-US/images/icon.png...
INFO [2017-01-27 17:07:35.05]: Updating changelog for code version '6' and language 'en-US'...
INFO [2017-01-27 17:07:35.62]: Updating changelog for code version '7' and language 'en-US'...
INFO [2017-01-27 17:07:36.34]: Updating changelog for code version '8' and language 'en-US'...
INFO [2017-01-27 17:07:36.95]: Updating changelog for code version '10' and language 'en-US'...
INFO [2017-01-27 17:07:37.55]: Updating changelog for code version '11' and language 'en-US'...
INFO [2017-01-27 17:07:38.22]: Updating changelog for code version '12' and language 'en-US'...
INFO [2017-01-27 17:07:38.80]: Updating changelog for code version '13' and language 'en-US'...
INFO [2017-01-27 17:07:39.42]: Updating changelog for code version '14' and language 'en-US'...
INFO [2017-01-27 17:07:39.96]: Updating changelog for code version '15' and language 'en-US'...
INFO [2017-01-27 17:07:40.64]: Updating changelog for code version '16' and language 'en-US'...
INFO [2017-01-27 17:07:41.18]: Updating changelog for code version '17' and language 'en-US'...
INFO [2017-01-27 17:07:41.87]: Updating changelog for code version '18' and language 'en-US'...
INFO [2017-01-27 17:07:42.48]: Preparing to upload for language 'ru-RU'...
INFO [2017-01-27 17:07:43.91]: No apk file found, you can pass the path to your apk using the `apk` option
INFO [2017-01-27 17:07:43.91]: Updating track 'beta'...
INFO [2017-01-27 17:07:44.63]: Uploading all changes to Google Play...
WARN [2017-01-27 17:07:45.57]: Lane Context:
INFO [2017-01-27 17:07:45.57]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android beta"}
ERROR [2017-01-27 17:07:45.57]: Google Api Error: noActiveApks: This app does not have any APKs in any tracks.
INFO [2017-01-27 17:07:45.57]: Successfully generated documentation at path '/Users/KidGeoLoc/Desktop/kid-in-the-city/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | supply                              | 18          |
+------+-------------------------------------+-------------+

ERROR [2017-01-27 17:07:45.64]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1108)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.12.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #gradle(task: "mobile:firebaseUploadReleaseProguardMapping")
    supply(track: 'beta')
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./google_play_key.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "gl.kid.alert" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.22       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
| psych                     | 2.0.8        |
</details>

*generated on:* **2017-01-27**
</details>

**Comment by asfalcone** [comment]
@rostopira are you still experiencing this problem? Can you confirm that the package name you were using is correct?

**Comment by rostopira** [comment]
@asfalcone yes, still experiencing this problem, trying everyday. According to attached log

> INFO [2017-01-27 17:07:41.87]: Updating changelog for code version '18' and language 'en-US'...

Package name is correct

**Comment by rostopira** [comment]
Error dissappeared. Now fastlane creates new release in beta without any apk

**Comment by asfalcone** [comment]
I wonder if there was some issue with the Google api? I'm going to close this out for now, but feel free to reopen if you run into this again!

**Comment by rostopira** [comment]
> I wonder if there was some issue with the Google api?

Yeah, probably. Sure, issue should be closed
