### ISSUE TITLE
Error caused by case sensitive bundle_id 

### ISSUE THREAD

**Issue by VolkerSchiewe** [fastlane/fastlane#8039]
```
+----------------+------------------------------+
|           Summary for produce 2.12.0          |
+----------------+------------------------------+
| username       | xxx@xxxx.com                 |
| app_identifier | com.xxx.catalog              |
| team_id        | 8G28592XXX                   |
| app_name       | app                          |
| skip_itc       | true                         |
| sku            | 1485526837                   |
| platform       | ios                          |
| language       | English                      |
| skip_devcenter | false                        |
+----------------+------------------------------+

[15:20:41]: Creating new app 'app' on the Apple Dev Center

Looking for related GitHub issues on fastlane/fastlane...

➡️  whitescreen after signing the app
   https://github.com/electron-userland/electron-osx-sign/issues/88 [open] 13 💬
   07 Nov 2016

➡️  Build Fail -- Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
   https://github.com/fbsamples/f8app/issues/123 [open] 7 💬
   13 Oct 2016

➡️  Can't access app path ../ios/build/device/name.app : No such file or directory
   https://github.com/driftyco/ionic-cli/issues/1197 [open] 45 💬
   4 weeks ago

[!] Apple provided the following error info:
	An App ID with Identifier &#x27;com.xxx.catalog&#x27; is not available. Please enter a different string.
```
I have an App ID with bundle_id `com.xxx.Catalog` in my Developer Portal.
If I understand correctly bundle_ids could not be case sensitive. To avoid this error the `app_exists?` mehtod or even `Spaceship.app.find` has to remove upper and lowercase.

**Comment by nolanwilson** [comment]
I just received this same error message with an all lower-case bundle ID.

Here is my output for `fastlane env`:
```
### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.7.4 (Apple Git-66)            |
| Installation Source | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.9.0   | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| executable-hooks          | 1.3.2       |
| bundler-unload            | 1.0.2       |
| rubygems-bundler          | 1.4.4       |
| bundler                   | 1.13.6      |
| slack-notifier            | 1.5.1       |
| claide                    | 1.0.1       |
| colored                   | 1.2         |
| xcodeproj                 | 1.4.1       |
| rouge                     | 1.11.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.7.1       |
| public_suffix             | 2.0.4       |
| addressable               | 2.5.0       |
| multipart-post            | 2.0.0       |
| word_wrap                 | 1.0.0       |
| babosa                    | 1.0.2       |
| excon                     | 0.54.0      |
| faraday                   | 0.10.0      |
| http-cookie               | 1.0.3       |
| faraday-cookie_jar        | 0.0.6       |
| gh_inspector              | 1.0.2       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| multi_json                | 1.12.1      |
| logging                   | 2.1.0       |
| jwt                       | 1.5.6       |
| memoist                   | 0.15.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.3       |
| googleauth                | 0.5.1       |
| google-api-client         | 0.9.20      |
| highline                  | 1.7.8       |
| json                      | 1.8.1       |
| mini_magick               | 4.5.1       |
| security                  | 0.1.3       |
| xcpretty-travis-formatter | 0.0.4       |
| dotenv                    | 2.1.1       |
| faraday_middleware        | 0.10.1      |
| commander                 | 4.4.1       |
| rubyzip                   | 1.2.0       |
| plist                     | 3.2.0       |
| unicode-display_width     | 1.1.2       |
| terminal-table            | 1.7.3       |
</details>


*generated on:* **2017-01-30**
```

Please let me know if I can provide any more details to help troubleshoot. I'm going to try again with a different bundle ID shortly.

**Comment by KrauseFx** [comment]
Interesting, is this something that was recently introduced? Did it work before?

**Comment by nolanwilson** [comment]
@KrauseFx this is the first time I've seen this error and just appending a few additional characters to the bundle ID fixed the issue.

Makes me think that it was a "transient Apple issue" that they just responded with the wrong error message. It's possible that someone else had this bundle ID registered in iTunes, but it's highly unlikely. We use bundle ID formatting that conforms to our enterprise patterns and shouldn't overlap with other developer's app IDs. I'll post back on here if the issue comes up again, but my gut tells me this won't come up again.

I think it's also worth noting that the output format for my bundle ID was in a similar format as above when the error message was displayed in the terminal:
```
&#x27;com.xxx.catalog&#x27;
```

I had assumed this was just a Unicode output issue. But maybe the bundle ID got malformed before the request and so Apple thought that I was trying to make a bundle ID in the format of:
```
&#x27;com.xxx.catalog&#x27;
```
instead of:
```
com.xxx.catalog
```

But the fact that it only happened once and has worked for ~20 other app submissions today makes that also seem not super likely.

**Comment by nolanwilson** [comment]
I'm fine closing out this issue if it helps to keep things organized.

@VolkerSchiewe, have you tried just registering a slightly different bundle ID for your app? I think you might find success in doing so.

**Comment by VolkerSchiewe** [comment]
I can reproduce this error as often as I want, because this is not an Apple problem. 'Fastlane produce' is checking if the bundle_id exists in Apple Developer Portal with comparing the strings directly (case-sensitiv). Problem is Apple does not allow bundle_ids which are only different in lower and upper case (com.xxx.Catalog and com.xxx.catalog) and this is the point where the Error occurs. 

As I wrote above a solution could be to change the `app.find` method of spaceship:

        # Find a specific App ID based on the bundle_id
        # @param mac [Bool] Searches Mac apps if true
        # @return (App) The app you're looking for. This is nil if the app can't be found.
        def find(bundle_id, mac: false)
          all(mac: mac).find do |app|
            app.bundle_id.casecmp(bundle_id)
          end
        end
      end


(But I'm not a ruby expert, so apologise if there are some misstakes ^^)

**Comment by VolkerSchiewe** [comment]
@nolanwilson I'm working on a integration of fastlane in a kind of CI, so I'm not responsible for the bundle_ids in our system, but I have to handle every kind of them ;)

**Comment by nolanwilson** [comment]
That makes sense, thanks for the additional information @VolkerSchiewe 

@KrauseFx can you (or one of your collabs) confirm that this validation is occurring on the Fastlane side? If the validation message that we're getting is from Apple, then they definitely have something wrong with their system as I didn't have a bundle ID even remotely resembling the one that I was trying to create today. But if this validation error is being raised on the Fastlane side, looks like there could be an issue with how that validation is being run.

**Comment by hjanuschka** [comment]
hey folks, could you give the PR #8068  a try? it should make app/application finding case insensitive (almost exactly the same solution as proposed by @VolkerSchiewe - thx for that, nice catch)

**Comment by nolanwilson** [comment]
I can't seem to replicate the issue anymore. If you could test with your bundle ID that's failing @VolkerSchiewe that would be :100:
