### ISSUE TITLE
update_fastlane: can't activate fastimage-1.7.0, already activated fastimage-1.6.8

### ISSUE THREAD

**Issue by gpbl** [fastlane/fastlane#804]
When i run the step `update_fastlane` it throws with the following error:

```
Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, pem, pilot, produce, scan, sigh, snapshot, spaceship, supply...
ERROR:  Loading command: update (Gem::LoadError)
	can't activate fastimage-1.7.0, already activated fastimage-1.6.8
Variable Dump:
{:DEFAULT_PLATFORM=>:ios, :ENVIRONMENT=>"myenv", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
undefined method `highest_installed_gems' for nil:NilClass
```

Any idea how to fix this? Thanks!

**Comment by iandundas** [comment]
I also have this issue

**Comment by KrauseFx** [comment]
Could you try running `[sudo] gem cleanup`

**Comment by iandundas** [comment]
hey - thanks for fast reply, unfortunately that didn't resolve it: 


	sudo gem cleanup
	Password:
	Cleaning up installed gems...
	[... lots here..]
	Clean Up Complete


and then 

	[17:59:04]: -----------------------------
	[17:59:04]: --- Step: update_fastlane ---
	[17:59:04]: -----------------------------
	[17:59:04]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, pem, pilot, produce, scan, sigh, snapshot, spaceship, supply...
	ERROR:  Loading command: update (Gem::LoadError)
		can't activate fastimage-1.7.0, already activated fastimage-1.6.8

**Comment by gpbl** [comment]
To me, `[sudo] gem cleanup` did work 👍 thanks

**Comment by KrauseFx** [comment]
Yeah :+1:

**Comment by gpbl** [comment]
@KrauseFx could we reopen this? I still get this error after running a `update_fastlane` action. Like @iandundas now the gem cleanup does not work. I even tried `gem uninstall fastimage` without success.

**Comment by danielgalasko** [comment]
Experiencing the same

**Comment by justin** [comment]
I am also hitting this issue as of this morning's updates.

```
[09:21:03]: -----------------------------
[09:21:03]: --- Step: update_fastlane ---
[09:21:03]: -----------------------------
[09:21:03]: Looking for updates for cert, credentials_manager, deliver, fastlane, fastlane_core, frameit, gym, pem, pilot, produce, scan, sigh, snapshot, spaceship, supply...
-------------------------------------------------------------------------------------------
😨  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
👍  This makes resolving issues much easier and helps improve fastlane.
🔒  The reports will be stored securely on getsentry.com.
✨  Once crash reporting is enabled, you get a clean output when something goes wrong.
🙊  More information about privacy: https://github.com/KrauseFx/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/actions/update_fastlane.rb:56:in `run': undefined method `highest_installed_gems' for #<Gem::Commands::UpdateCommand:0x007fc77b01dbd8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:1:in `parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/fast_file.rb:48:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/fast_file.rb:48:in `block in parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/fast_file.rb:37:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/fast_file.rb:37:in `parse'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/fast_file.rb:27:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/lane_manager.rb:12:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/bin/fastlane:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.47.0/bin/fastlane:159:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Compound-iMac:EventLink-iOS [master] justin$ 

```

**Comment by micnguyen** [comment]
I am also experiencing the same issue. sudo gem cleanup does not fix it. 

```
"message": "NoMethodError: undefined method `highest_installed_gems' for #<Gem::Commands::UpdateCommand:0x007f8f794339a0>",
```

**Comment by colinta** [comment]
Could Ruby version have something to do with this?  I'm on Ruby 2.0, my coworker @steam is on Ruby 2.1 and doesn't have this error.

**Comment by colinta** [comment]
Installing Ruby 2.1 (rvm) solved this for me.

**Comment by gpbl** [comment]
I don't believe it depends from the ruby version. 

This error appears randomly after updating fastlane. Now for some reasons it disappeared on my machine.

Maybe because I've updated fastlane with `gem update`?

**Comment by mAu888** [comment]
I'm experiencing the same error on my build server. I have `update_fastlane` in my `Fastfiles` and the second build after it updated itself it throws this error. Now I added a timed script to run `gem cleanup` every once in a while.

I'm on `ruby 2.2.1p85`.

**Comment by maxbritto** [comment]
I managed to fix this by manually updating all the fastlane  gems. I actually updated all my gems with this command :
`gem update ``gem list | cut -d ' ' -f 1`
And then `gem cleanup` to remove old versions. Thanks for the help

**Comment by gpbl** [comment]
I think I found the reason: I was manually installing fastlane via `sudo`, while the `update_fastlane` action wasn't running as superuser. Each time `update_fastlane` installed some updates, something broke. Now trying to keep everything without the need of su...

**Comment by huynguyen** [comment]
Some people might need to update the rubygem gem itself.
https://github.com/fastlane/fastlane/issues/969#issuecomment-171754860

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
