### ISSUE TITLE
Transporter transfer failed. When uploading to iTunes connect

### ISSUE THREAD

**Issue by TanderZA** [fastlane/fastlane#8040]
This seems to be related to this issue: https://github.com/fastlane/fastlane/issues/6151#issuecomment-249993354

When I run `fastlane appStore` which is my appStore lane - once the compiling is done and at the point of uploading to iTunes connect, I get the following error: 

> Return status of iTunes Transporter was 1:
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
Could not download/upload from iTunes Connect! It's probably related to your password or your internet connection.

I then tried: `FASTLANE_ITUNES_TRANSPORTER_USE_SHELL_SCRIPT=1 fastlane appStore`

And it too gave the same error. 

Using the latest version of Fastlane and Xcode 8 

Any suggestions? 
Thanks

**Comment by TanderZA** [comment]
Sorry about that. Here we go: 

`<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do
  before_all do
    increment_build_number
    sh("bash ./scripts/bidorbuy_web_fonts.sh")
  end
  
  desc "Submits a new Beta Build to HockeyApp"
  lane :beta do
    match(type: "adhoc")
	 gym(
		  scheme: "MyApp Ad-Hoc", 
		  configuration: "Demo -Ad-Hoc", 
		  clean: true, 
		  include_bitcode: true,
		  include_symbols: true,
		  workspace: MyApp.xcworkspace",
		  output_directory: "./builds/",
		  output_name: MyApp.ipa",
		)
		
		hockey(
			  api_token: "OUR_TOKEN",
			  notes_type: "1",
			  notes: changelog_from_git_commits
    )
  end

  desc "Deploys a new version to the App Store"
  lane :deploy do
     match(type: "appstore")
	 gym(
		  scheme: "MyApp Release", 
		  configuration: "Release", 
		  clean: true, 
		  include_bitcode: true,
		  workspace: "MyApp.xcworkspace",
		  output_directory: "./builds/",
		  output_name: "MyApp.ipa",
		)
    deliver(force: true)
  end
  
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.MyApp.MyApp" # The bundle identifier of your app
apple_id example@email.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.24       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>


*generated on:* **2017-01-27**
</details>`

**Comment by KrauseFx** [comment]
Could you share the complete output when running _fastlane_?

**Comment by TanderZA** [comment]
@KrauseFx Thanks for the response. I think there might be an issue with the network at my work place. Since I was able to successfully deploy the app to iTunes Connect without using anything more than the simple fast lane command- using my home network. I'll revert to the I.T department next week. 

Closing this as it isnt an issue with fastlane.
