### ISSUE TITLE
Match passphrases are branch-specific, not repo-specific

### ISSUE THREAD

**Issue by brockboland** [fastlane/fastlane#8041]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`match` passphrase appears to be per-branch, but the output indicates that it's per-repo.

The output below says "This passphrase is specific per repository and will be stored in your local keychain," and then "Passphrase for Git Repo." This appears to be inaccurate.

I'm at an agency that works with multiple clients, so we have several branches in our certificates repo for different team IDs. I discovered today that we're using different passwords for different clients and hadn't realized it yet.

I'm not sure if the documentation or the functionality should be updated in this case, but I'm leaning toward it being a matter of documentation updates.

##### Complete output when running fastlane, including the stack trace and command used
```
$ bundle exec fastlane match development
[16:13:30]: Successfully loaded '/path/to/SigningTest/fastlane/Matchfile' 📄

+-----------------------+-----------------------------------------------+
|              Detected Values from './fastlane/Matchfile'              |
+-----------------------+-----------------------------------------------+
| git_url               | https://github.com/secret/blahblah.git        |
| git_branch            | secret                                        |
| type                  | adhoc                                         |
| force_for_new_devices | true                                          |
+-----------------------+-----------------------------------------------+


+-----------------------+-----------------------------------------------+
|                       Summary for match 2.12.0                        |
+-----------------------+-----------------------------------------------+
| git_url               | https://github.com/secret/blahblah.git        |
| git_branch            | secret                                        |
| type                  | development                                   |
| force_for_new_devices | true                                          |
| app_identifier        | io.secret.SigningTest                         |
| username              | build@secret.io                               |
| keychain_name         | login.keychain                                |
| readonly              | false                                         |
| team_id               | LOLOLOLOLO                                    |
| verbose               | false                                         |
| force                 | false                                         |
| skip_confirmation     | false                                         |
| shallow_clone         | false                                         |
| skip_docs             | false                                         |
+-----------------------+-----------------------------------------------+

[16:13:30]: Cloning remote git repo...
[16:13:51]: Checking out branch secret...
[16:13:51]: Enter the passphrase that should be used to encrypt/decrypt your certificates
[16:13:51]: This passphrase is specific per repository and will be stored in your local keychain
[16:13:51]: Make sure to remember the password, as you'll need it when you run match on a different machine
Passphrase for Git Repo:
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
Agreed, sounds good to me. Do you mind submitting a PR updating the documentation to be correct? Check out [FirstPR.md](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) for more information on how to get started 👍

**Comment by brockboland** [comment]
I'll have to give some thought to how to word that. A coworker pointed out that the passphrase applies to the latest commit, not the branch as a whole, and furthermore, the Keychain stores a single password for the repo, so it's advisable to use the same passphrase for all branches if you have the option.

**Comment by brockboland** [comment]
Sorry I didn't have a chance to update any documentation on this one: I switched jobs and don't use match in my new gig, so it kind of fell down my priority list.
