### ISSUE TITLE
commit_version_bump- fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by simonarcher** [fastlane/fastlane#8042]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]
(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Whenever I try to do a git related action, it fails. And not 100% why..

If I use the action `git_branch`, the result appears to be null. 
Though if I do ``sh 'git branch'` it shows my branches.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

`### Captured Output

Command Used: `gittest`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/simon/Development/mobile/MyApp-ios/Appfile'
- app_identifier: 'xxxx'
- apple_id: 'xxxx'
-------
DEBUG [2017-01-28 13:18:02.51]: Checking if there are any plugins that should be loaded...
INFO [2017-01-28 13:18:02.55]: -------------------------------------------------
INFO [2017-01-28 13:18:02.55]: --- Step: Verifying required fastlane version ---
INFO [2017-01-28 13:18:02.55]: -------------------------------------------------
INFO [2017-01-28 13:18:02.55]: Your fastlane version 2.12.0 matches the minimum requirement of 1.109.0  ✅
INFO [2017-01-28 13:18:02.56]: ------------------------------
INFO [2017-01-28 13:18:02.56]: --- Step: default_platform ---
INFO [2017-01-28 13:18:02.56]: ------------------------------
INFO [2017-01-28 13:18:02.56]: Driving the lane 'gittest' 🚀
INFO [2017-01-28 13:18:02.56]: -------------------------------------------
INFO [2017-01-28 13:18:02.56]: --- Step: git rev-parse --show-toplevel ---
INFO [2017-01-28 13:18:02.56]: -------------------------------------------
INFO [2017-01-28 13:18:02.56]: $ git rev-parse --show-toplevel
INFO [2017-01-28 13:18:02.59]: ▸ /Users/simon/Development/mobile/MyApp-ios
INFO [2017-01-28 13:18:02.59]: ------------------------
INFO [2017-01-28 13:18:02.59]: --- Step: git branch ---
INFO [2017-01-28 13:18:02.59]: ------------------------
INFO [2017-01-28 13:18:02.59]: $ git branch
INFO [2017-01-28 13:18:02.60]: ▸ * dev
INFO [2017-01-28 13:18:02.60]: ▸ dev-fastlane
INFO [2017-01-28 13:18:02.60]: ▸ master
INFO [2017-01-28 13:18:02.61]: ------------------------
INFO [2017-01-28 13:18:02.61]: --- Step: git_branch ---
INFO [2017-01-28 13:18:02.61]: ------------------------
INFO [2017-01-28 13:18:02.63]: ---------------------------------
INFO [2017-01-28 13:18:02.63]: --- Step: commit_version_bump ---
INFO [2017-01-28 13:18:02.63]: ---------------------------------
INFO [2017-01-28 13:18:02.63]: $ git rev-parse --show-toplevel
INFO [2017-01-28 13:18:02.63]: ▸ fatal: Not a git repository (or any of the parent directories): .git
WARN [2017-01-28 13:18:02.64]: Lane Context:
INFO [2017-01-28 13:18:02.64]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"gittest"}
ERROR [2017-01-28 13:18:02.64]: Exit status of command 'git rev-parse --show-toplevel' was 128 instead of 0.
fatal: Not a git repository (or any of the parent directories): .git

INFO [2017-01-28 13:18:02.64]: Successfully generated documentation at path '/Users/simon/Development/mobile/MyApp-ios/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | git rev-parse --show-toplevel       | 0           |
| 4    | git branch                          | 0           |
| 5    | git_branch                          | 0           |
| 💥   | commit_version_bump                 | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-01-28 13:18:02.65]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "6a52f69f-53d8-40db-b16d-2c779582c8cf"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later


lane :gittest do
	sh 'git rev-parse --show-toplevel'
	sh 'git branch'
	git_branch
	commit_version_bump(
	  message: "Version Bump - 1"
	)

  	push_to_git_remote(
	  remote: "github",         # optional, default: "origin"
	  local_branch: "dev",  # optional, aliased by "branch", default: "master"
	  remote_branch: "dev" # optional, default is set to local_branch
	)
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

 app_identifier "xxxxx" # the bundle identifier of your app
 apple_id "xxxxx" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.2        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.22       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-01-28**
</details>`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

(Same as output above)

**Comment by hjanuschka** [comment]
hmmm - for whatever reason it does not seem to be a git repo.

can you try running this 
```
git rev-parse --show-toplevel
```

and see what the output is?

**Comment by simonarcher** [comment]
hi @hjanuschka ,

So i ran `git rev-parse --show-toplevel` as part of my script and you can see it log out my current directory where my project is in. Its also the same directory that my `.git` folder is sitting.

So `git rev-parse --show-toplevel` outputs
`/Users/simon/Development/mobile/MyApp-ios`
And my git folder is sitting at
`/Users/simon/Development/mobile/MyApp-ios/.git`

Im *relatively* new to the Git stuff, but my project is currently being synced to a GitHub repo and I can run `git` commands normally in that directory without issue. So I think based on that it must be the right 'git repo' type that its supposed to be expecting?

**Comment by mgrebenets** [comment]
I would have a wild guess that it's some kind of permission issues, maybe.

If you `ls -lha`, what would the `.git` entry look like?

for me it's along these lines:

```
drwxr-xr-x  18 grebenma  staff   612B  3 Feb 21:22 .git
```

**Comment by caiobiodere** [comment]
Hey there, i think the problem can be your fastlane folder reference please check if this is inside of your project like this "../MyApp-ios/fastlane"

**Comment by simonarcher** [comment]
@mgrebenets i get  
`drwxr-xr-x  17 simon  staff   578B Feb  1 11:03 .git`

@caiobiodere 
I don't have a fastlane folder in my project directory... 🤔

**Comment by mgrebenets** [comment]
The missing `fastlane` directory must the be issue.

If you have `fastlane` gem installed on the system, the fastlane command may run, but will then fail since it can't find integration for this particular project.

Did you run `fastlane init`? How did you setup fastlane for your project?
Is the name of fastlane directory `fastlane` or `.fastlane`?
Maybe it's `.fastlane` and you didn't copy it while moving files, cause it's hidden...

In any case, setting up fastlane integration should help.

**Comment by mgrebenets** [comment]
@simonarcher 

Interesting, I am running in this very same issue right now - on TeamCity.
Was just setting up a new fastlane CI for existing project...

**Comment by mgrebenets** [comment]
On another note, I am getting this directory when running `bundle install && bundle update` command even before running any of the Fastlane commands...

**Comment by mgrebenets** [comment]
Hey @simonarcher 

So I found the issue with my setup.
In my case all worked fine on my dev laptop, but failed on TeamCity.
The reason was the VCS checkout settings:
by default it uses "on the server" checkout mode
![image](https://cloud.githubusercontent.com/assets/350654/22631377/d311f578-ec5f-11e6-8c7f-72010e3b6138.png)

So I would assume it does checkout on server and then on the agent there is no `.git` directory.
That's why by `bundle` commands failed, because in my gepspec file I had `git ls-files` command.

For me the fix was to use the "Automatically on agent" option and all steps ran OK after that.

So in your case, it does seem very very similar.
Are your running it in CI environment too?
