### ISSUE TITLE
Support auto generation of Safari Web Push Certificates?

### ISSUE THREAD

**Issue by RafaelPlantard** [fastlane/fastlane#8045]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Is possible auto generate all Safari Web Push Certificates:
https://pushalert.co/creating-safari-web-push-certificate

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

➜  ~ fastlane env
[12:44:41]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12.3                                          |
| Ruby                | 2.4.0                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.11.0                               |
| Installation Source | /usr/local/opt/rbenv/versions/2.4.0/bin/fastlane |
| Host                | Mac OS X 10.12.3 (16D32)                         |
| Ruby Lib Dir        | /usr/local/opt/rbenv/versions/2.4.0/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained        | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.2.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-01-29**
</details>
🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
y
[12:44:51]: Successfully copied markdown into your clipboard 🎨
[12:44:51]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
➜  ~ fastlane --capture_output
### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

DEBUG [2017-01-29 12:45:11.50]: Checking if there are any plugins that should be loaded...
WARN [2017-01-29 12:45:11.52]: Could not find fastlane in current directory. Would you like to set it up?

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Running fastlane on Bitrise - non-interactive mode
   https://github.com/fastlane/fastlane/issues/5867 [closed] 5 💬
   06 Dec 2016

➡️  fastlane env --quiet option or --force
   https://github.com/fastlane/fastlane/issues/6781 [closed] 2 💬
   3 days ago

➡️  Platform specific lanes are only parsed if a matching default_platform is specified
   https://github.com/fastlane/fastlane/issues/7979 [open] 6 💬
   3 days ago

and 11 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12.3                                          |
| Ruby                | 2.4.0                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.11.0                               |
| Installation Source | /usr/local/opt/rbenv/versions/2.4.0/bin/fastlane |
| Host                | Mac OS X 10.12.3 (16D32)                         |
| Ruby Lib Dir        | /usr/local/opt/rbenv/versions/2.4.0/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained        | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.2.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-01-29**
</details>
🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
y
/usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/interface.rb:132:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:120:in `verify_interactive!'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:98:in `confirm'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane/lib/fastlane/commands_generator.rb:312:in `ensure_fastfile'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /usr/local/opt/rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.12.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/opt/rbenv/versions/2.4.0/bin/fastlane:22:in `load'
	from /usr/local/opt/rbenv/versions/2.4.0/bin/fastlane:22:in `<main>'
➜  ~ >....
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-01-29**
</details>:q
zsh: parse error near `<'
➜  ~ ### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

DEBUG [2017-01-29 12:45:11.50]: Checking if there are any plugins that should be loaded...
WARN [2017-01-29 12:45:11.52]: Could not find fastlane in current directory. Would you like to set it up?

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Running fastlane on Bitrise - non-interactive mode
   https://github.com/fastlane/fastlane/issues/5867 [closed] 5 💬
   06 Dec 2016

➡️  fastlane env --quiet option or --force
   https://github.com/fastlane/fastlane/issues/6781 [closed] 2 💬
   3 days ago

➡️  Platform specific lanes are only parsed if a matching default_platform is specified
   https://github.com/fastlane/fastlane/issues/7979 [open] 6 💬
   3 days ago

and 11 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary><2705> fastlane environment <2705></summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12.3                                          |
| Ruby                | 2.4.0                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.11.0                               |
| Installation Source | /usr/local/opt/rbenv/versions/2.4.0/bin/fastlane |
| Host                | Mac OS X 10.12.3 (16D32)                         |
| Ruby Lib Dir        | /usr/local/opt/rbenv/versions/2.4.0/lib          |                                                                              <....

### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

DEBUG [2017-01-29 12:45:11.50]: Checking if there are any plugins that should be loaded...
WARN [2017-01-29 12:45:11.52]: Could not find fastlane in current directory. Would you like to set it up?

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Running fastlane on Bitrise - non-interactive mode
   https://github.com/fastlane/fastlane/issues/5867 [closed] 5 💬
   06 Dec 2016

➡️  fastlane env --quiet option or --force
   https://github.com/fastlane/fastlane/issues/6781 [closed] 2 💬
   3 days ago

➡️  Platform specific lanes are only parsed if a matching default_platform is specified
   https://github.com/fastlane/fastlane/issues/7979 [open] 6 💬
   3 days ago

and 11 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12.3                                          |
| Ruby                | 2.4.0                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.11.0                               |
| Installation Source | /usr/local/opt/rbenv/versions/2.4.0/bin/fastlane |
| Host                | Mac OS X 10.12.3 (16D32)                         |
| Ruby Lib Dir        | /usr/local/opt/rbenv/versions/2.4.0/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained        | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.2.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-01-29**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.12.3                                          |
| Ruby                | 2.4.0                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.11.0                               |
| Installation Source | /usr/local/opt/rbenv/versions/2.4.0/bin/fastlane |
| Host                | Mac OS X 10.12.3 (16D32)                         |
| Ruby Lib Dir        | /usr/local/opt/rbenv/versions/2.4.0/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained        | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.2.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-01-29**
</details>

**Comment by ohayon** [comment]
Hey @RafaelPlantard! Thanks for raising this issue. Creating Safari Web Push Certificates is currently not supported by _fastlane_. We would be happy to have a plugin that could handle this functionality, but our [vision](https://github.com/fastlane/fastlane/blob/master/VISION.md) is really to be the sharpest tool for mobile app development so this is is not something we would immediately want to include in our main code base. Thanks again! 🐙 👍

**Comment by RafaelPlantard** [comment]
Thanks @ohayon

**Comment by hjanuschka** [comment]
releated to: https://github.com/fastlane/fastlane/pull/6943 seems like only pem is missing - i am going to ping the author if he could share the pem changes

**Comment by RafaelPlantard** [comment]
That's sound awesome @hjanuschka
