### ISSUE TITLE
[question] it's possible to implement manually 2 Step Verification with SpaceShip ?

### ISSUE THREAD

**Issue by bolom** [fastlane/fastlane#8048]
I would like to implement **2 Step Verification**  in web app. I have checked the code 
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/two_step_client.rb#L114
but i am stuck in the logic. I have got several questions

- It's possible to know if the apple_id has the option actived ?
- it's possible to get the list devices available ?
- it's possible to send  manually a sms ?

Thanks for your help

**Comment by KrauseFx** [comment]
There is no spaceship API for the first one, but the other points should be available. Did you check out the source code yet?

**Comment by bolom** [comment]
@KrauseFx tks for your quick answer. 

if i want to display devices available to send the SMS. 
I need to connect to my apple_id? correct ? If i need that i will have to do all the process though the terminal. I am correct @KrauseFx 

All i have tried to mimic the flow i have got from terminal in web app.

**Comment by bolom** [comment]
> When your Apple account has 2 factor verification enabled, you'll automatically be asked to verify your identity using your phone.

@KrauseFx there is way to not automatically be asked to verify the identity

**Comment by KrauseFx** [comment]
You might be able to build something yourself, if you look at the spaceship classes, however it won't be anything that we'll officially support.

**Comment by bolom** [comment]
@KrauseFx ok tks
