### ISSUE TITLE
dsym_zip: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by yakimant** [fastlane/fastlane#805]
Action running:
```ruby
dsym_zip(archive_path: "archive.xcarchive", dsym_path: "ipa")
```

Error log:
```
16:00:00]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build", :DSYM_ZIP_PATH=>"/Users/username/Workspace/ipa"}
[16:00:00]: undefined method `[]' for nil:NilClass
```

Here is the content of `archive.xcarchive/Info.plist`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ArchiveVersion</key>
	<integer>2</integer>
	<key>CreationDate</key>
	<date>2015-11-06T15:14:24Z</date>
	<key>Name</key>
	<string>AppName</string>
	<key>SchemeName</key>
	<string>AppName</string>
</dict>
</plist>
```

**Comment by snatchev** [comment]
Thanks for reporting @yakimant,
Could you provide the full stack trace or a sentry ID?

**Comment by arunks** [comment]
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/actions/dsym_zip.rb:23:in `run': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/runner.rb:142:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/actions/actions_helper.rb:37:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/runner.rb:128:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/runner.rb:127:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/runner.rb:127:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:66:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/runner.rb:51:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/lane_manager.rb:43:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/lib/fastlane/command_line_handler.rb:31:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/bin/fastlane:35:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/bin/fastlane:152:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.44.0/bin/fastlane:158:in `<top (required)>'
	from /usr/bin/fastlane:23:in `load'
	from /usr/bin/fastlane:23:in `<main>'

**Comment by ohwutup** [comment]
Hey @arunks, is this still an issue you are having?

**Comment by alaphao** [comment]
I just got this error after adding `pilot(distribute_external: true)` to my Fastfile

**Comment by ohwutup** [comment]
Hey @alaphao, would you mind filing a new issue with the whole output of your terminal? Thanks! 🐙
