### ISSUE TITLE
Pilot find returns unexpected results

### ISSUE THREAD

**Issue by prnewman** [fastlane/fastlane#8052]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have tested the 'fastlane pilot find' command with valid TestFlight external testers (i.e., users returned by the 'fastlane pilot list' command). The results vary: some users are found, some are not found, and some generate an error.

I have been unable to determine why some email addresses are found, and others fail to be found.

**Example 1: Error**

```
[10:31:20] NYPNewmanMAC:nightly-build paul.newman$ fastlane pilot find joe.user@example.com
[10:31:40]: Login to iTunes Connect (login@example.com)
[10:31:43]: Login successful
[10:31:46]: [joe.user@example.com]: undefined method `length' for nil:NilClass

[!] Some operations failed: [joe.user@example.com]: undefined method `length' for nil:NilClass
```

**Example 2: Not found**

```
[10:26:18] NYPNewmanMAC:nightly-build paul.newman$ fastlane pilot find jane@example.com
[10:27:55]: Login to iTunes Connect (login@example.com)
[10:27:58]: Login successful
[10:28:01]: [jane@example.com]: Tester jane@example.com not found

[!] Some operations failed: [jane@example.com]: Tester jane@example.com not found
```

**Example 3: Found**

```
[10:28:01] NYPNewmanMAC:nightly-build paul.newman$ fastlane pilot find alex.user@example.com
[10:31:12]: Login to iTunes Connect (login@example.com)
[10:31:16]: Login successful
+---------------------+---------------------------------+
|            alex.user@example.com            |
+---------------------+---------------------------------+
| First name          | Alex                            |
| Last name           | User                         |
| Email               | alex.user@example.com |
| Latest Version      | 4.15.0 (4)                      |
| Latest Install Date | 10/06/16 12:59                  |
| 1 Devices           | • iPhone 5s, iOS 10.0.2         |
+---------------------+---------------------------------+

```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.4.4                                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G31)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.12.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.11.2       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.7.1        |
| google-api-client         | 0.9.5        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.3        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
</details>

*generated on:* **2017-01-30**
</details>

**Comment by hjanuschka** [comment]
@prnewman  all of the above users really exist?
can you run fastlane with `--verbose` so we get a stacktrace of the Error case, and find that first?


can you provide (for sure with replaced names) a list of internal and external testers (as found on the web interface?)

**Comment by prnewman** [comment]
@hjanuschka Here are --verbose versions of Example 1 and Example 2

The list of Internal and External testers would be too long to include here, so here are just the entries for joe.user@example.com and jane@example.com. All I've done is find/replace the actual names and email addresses.

```
[11:47:39] NYPNewmanMAC:nightly-build paul.newman$ fastlane pilot list
[11:57:00]: Login to iTunes Connect (login@example.com)
[11:57:04]: Login successful
+-----------+-------------+---------------------------------------+--------+
|                             Internal Testers                             |
+-----------+-------------+---------------------------------------+--------+
| First     | Last        | Email                                 | Groups |
+-----------+-------------+---------------------------------------+--------+
| Joe       | User        | joe.user@example.com                  |        |
+-----------+-------------+---------------------------------------+--------+

+------------------+-------------+--------------------------------------+----------+
|                                 External Testers                                 |
+------------------+-------------+--------------------------------------+----------+
| First            | Last        | Email                                | Groups   |
+------------------+-------------+--------------------------------------+----------+
| Jane             | Doe         | jane@example.com                     |          |
+------------------+-------------+--------------------------------------+----------+
```

**Example 1: Error**

```
[11:39:40] NYPNewmanMAC:nightly-build paul.newman$ fastlane pilot find joe.user@example.com --verbose
Successfully loaded Appfile at path '/Users/paul.newman/Documents/github/ww/nightly-build/fastlane/Appfile'
- app_identifier: 'com.weightwatchers.identifier'
- apple_id: 'login@example.com'
- team_id: 'XXXXXXXXXX'
-------
INFO [2017-01-30 11:47:32.97]: Login to iTunes Connect (login@example.com)
Looking for iTunes Connect Team with ID XXXXXX
INFO [2017-01-30 11:47:36.12]: Login successful
ERROR [2017-01-30 11:47:39.48]: [joe.user@example.com]: undefined method `length' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Some operations failed: [joe.user@example.com]: undefined method `length' for nil:NilClass (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:39:in `handle_multiple'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:102:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:134:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Example 2: Not Found**

```
[10:31:46] NYPNewmanMAC:nightly-build paul.newman$ fastlane pilot find jane@example.com --verbose
Successfully loaded Appfile at path '/Users/paul.newman/Documents/github/ww/nightly-build/fastlane/Appfile'
- app_identifier: 'com.weightwatchers.identifier'
- apple_id: 'login@example.com'
- team_id: 'XXXXXXXXXX'
-------
INFO [2017-01-30 11:39:31.71]: Login to iTunes Connect (login@example.com)
Looking for iTunes Connect Team with ID XXXXXX
INFO [2017-01-30 11:39:35.36]: Login successful
ERROR [2017-01-30 11:39:40.42]: [jane@example.com]: Tester jane@example.com not found
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/interface.rb:145:in `user_error!': [!] Some operations failed: [jane@example.com]: Tester jane@example.com not found (FastlaneCore::Interface::FastlaneError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:39:in `handle_multiple'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:102:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:134:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/pilot/lib/pilot/commands_generator.rb:14:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.12.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by hjanuschka** [comment]
@prnewman thats a hard one.


can we take one step back  - and try to test if spaceship works?

can you run the following:

```ruby
require "spaceship"
require "pp"
# login with your itc account
Spaceship::Tunes.login("itc@domain.com") 

# find one internal tester
int = Spaceship::Tunes::Tester::Internal.find("helmut@januschka.com")
pp int

# find one external tester
ext = Spaceship::Tunes::Tester::External.find("helmut@januschka.com")
pp ext

```

and can you share the output?
lets see if we find the user at the core, and see if the object is valid.

it should be something like:

```ruby
 <Spaceship::Tunes::Tester::Internal 
	tester_id="d4ce8f78-b3f0-4d15-b2a6-edb30d3bfc73", 
	email="helmut@januschka.com", 
	first_name="Helmut", 
	last_name="Januschka", 
	groups=nil, 
	devices=[], 
	latest_install_app_id=nil, 
	latest_install_date=nil, 
	latest_installed_build_number=nil, 
	latest_installed_version_number=nil>
```

**Comment by prnewman** [comment]
@hjanuschka Here are the results. Finds the internal tester and returns nil for the external tester:

```
<Spaceship::Tunes::Tester::Internal 
	tester_id=nil, 
	email="joe.user@example.com", 
	first_name="Joe", 
	last_name="User", 
	groups=nil, 
	devices=[], 
	latest_install_app_id=nil, 
	latest_install_date=nil, 
	latest_installed_build_number=nil, 
	latest_installed_version_number=nil>
nil
```

**Comment by hjanuschka** [comment]
@prnewman thx for trying it.

ok i think i found the problem.

`.find`  skips entries with an `tester_id` of `nil` -> https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tester.rb#L93

where as the listing of all testers in the app does not skip nil tester_id's -> https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/tester.rb#L125



i am really unsure how it comes to the nil tester_id, can you have a look at the web itc to see if there is something strange with the tester?
maybe deleting and recreating it may help.

**Comment by hjanuschka** [comment]
@prnewman i did a PR -> https://github.com/fastlane/fastlane/pull/8071 which should fix this, could you give it a try?
