### ISSUE TITLE
Fastlane Travis Integration

### ISSUE THREAD

**Issue by greggmojica** [fastlane/fastlane#8055]
I'm trying to integrate travis with fastlane and have the following setup in my travis.yml file:

<pre>
language: objective-c
cache: cocoapods
osx_image: xcode7.3.1

notifications:
  email:
    - me@example.com

before_install:
  - gem install xcov --no-ri --no-rdoc --no-document
  - gem update fastlane --no-ri --no-rdoc --no-document

script:
  - fastlane ios beta
</pre>

Every time, on build travis fails with the following error:

<pre>
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | cocoapods                           | 1           |
+------+-------------------------------------+-------------+
[01:40:15]: fastlane finished with errors
[!] Exit status of command 'pod install' was 1 instead of 0.
Analyzing dependencies
[!] Unable to satisfy the following requirements:

</pre>

Any help would be appreciated! Thank you!!

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.1 (16B2659)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.12.0"

ENV["FASTLANE_ITC_TEAM_ID"] = "1379561"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods(use_bundle_exec: false)

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "gradology-ios") # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "gradology-ios") # Build your app - more options available
    deliver(force: true, skip_binary_upload: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.gradology.gradology-ios" # The bundle identifier of your app
apple_id "app.energyplus@gmail.com" # Your Apple email address

team_id "V5FE42WTHG"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.12.0  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.5   | ✅ Up-To-Date  |

Fastlane Env Details:
<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| slack-notifier             | 1.5.1        |
| i18n                       | 0.7.0        |
| json                       | 1.8.1        |
| thread_safe                | 0.3.5        |
| tzinfo                     | 1.2.2        |
| minitest                   | 5.10.1       |
| activesupport              | 4.2.7.1      |
| CFPropertyList             | 2.3.5        |
| claide                     | 1.0.1        |
| colored                    | 1.2          |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.4.2        |
| rouge                      | 1.11.1       |
| xcpretty                   | 0.2.4        |
| terminal-notifier          | 1.7.1        |
| unicode-display_width      | 1.1.3        |
| terminal-table             | 1.7.3        |
| plist                      | 3.2.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.0        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| babosa                     | 1.0.2        |
| highline                   | 1.7.8        |
| commander                  | 4.4.3        |
| excon                      | 0.54.0       |
| faraday                    | 0.11.0       |
| unf_ext                    | 0.0.7.2      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20161129 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| fastimage                  | 2.0.1        |
| gh_inspector               | 1.0.3        |
| uber                       | 0.0.15       |
| representable              | 2.3.0        |
| retriable                  | 2.1.0        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| hurley                     | 0.2          |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.12.1       |
| logging                    | 2.1.0        |
| jwt                        | 1.5.6        |
| memoist                    | 0.15.0       |
| os                         | 0.9.6        |
| signet                     | 0.7.3        |
| googleauth                 | 0.5.1        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.9.22       |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.2.0        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 0.0.4        |
| dotenv                     | 2.2.0        |
| bundler                    | 1.13.7       |
| faraday_middleware         | 0.11.0       |
| fastlane-plugin-versioning | 0.2.5        |
</details>

*generated on:* **2017-01-30**
</details>

**Comment by KrauseFx** [comment]
There is nothing below the `[!] Unable to satisfy the following requirements:`?

**Comment by greggmojica** [comment]
@KrauseFx Here's the rest of the log:

<pre>
You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
#######################################################################
# fastlane 2.13.0 is available. You are on 2.12.0.
# It is recommended to use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
2.13.0 User management and update pem for new Dev Portal
* Add user management to spaceship (#7993)
* Update _pem_ to work with the new Apple Developer Portal (#8049)
* Fix git_branch task for Jenkins Pipeline jobs as they set BRANCH_NAME instead of GIT_BRANCH (#8024)
Please update using `bundle update fastlane`
The command "fastlane ios test" exited with 1.
cache.2
store build cache
</pre>

**Comment by greggmojica** [comment]
@KrauseFx any thoughts on this? Your help would be most appreciated!

**Comment by hjanuschka** [comment]
@greggmojica looks like your pod repo needs to be updated, as stated in the output `pod repo update` does not happen on `pod install` anymore.

so put this into your fastfile (`repo_update: true`, should do it):

```
cocoapods(use_bundle_exec: false, repo_update: true)
```

we are using this on all of our ci machines - as they start with a blank image
let me know if this helps you.

**Comment by KrauseFx** [comment]
I wonder if we should catch that error in fastlane somehow and show a message on how to change the Fastfile?

**Comment by greggmojica** [comment]
@KrauseFx Do you have any idea why this would occur:

<pre>
Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `SkyFloatingLabelTextField (~> 2.0)` required by `Podfile`
- `SkyFloatingLabelTextField (= 2.0)` required by `Podfile.lock`
None of your spec sources contain a spec satisfying the dependencies: `SkyFloatingLabelTextField (~> 2.0), SkyFloatingLabelTextField (= 2.0)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
The command "eval bundle exec pod install " failed 3 times.
</pre>

**Comment by KrauseFx** [comment]
Can you run `pod repo update` then `pod install` and make sure you check in the `Gemfile.lock` to version control?

**Comment by greggmojica** [comment]
@KrauseFx yes, I have done that already and had no lucl. Any thoughts here as I am at a loss seemingly. Thank you!!

<pre>
Installing Pods with 'bundle exec pod install'
7.44s$ bundle exec pod install
Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `SkyFloatingLabelTextField (~> 2.0.0)` required by `Podfile`
- `SkyFloatingLabelTextField (= 2.0.0)` required by `Podfile.lock`
None of your spec sources contain a spec satisfying the dependencies: `SkyFloatingLabelTextField (~> 2.0.0), SkyFloatingLabelTextField (= 2.0.0)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
The command "eval bundle exec pod install " failed. Retrying, 2 of 3.
Analyzing dependencies
[!] Unable to satisfy the following requirements:
</pre>

**Comment by KrauseFx** [comment]
Can you manually run `pod install` or `pod update`? Do you run into the same error?

**Comment by greggmojica** [comment]
@KrauseFx Manually running it I do not experience this error. I was able to modify the travis configuration and I now see this error. Is there any documentation on how to use fastlane with travis...it seems somewhat complex.

❌  Code signing is required for product type 'Application' in SDK 'iOS 10.0'

Any ideas how to rectify this problem now? I tried:
<pre>    update_project_codesigning(path: "Gradology.xcodeproj",use_automatic_signing: true)</pre>

**Comment by greggmojica** [comment]
Updated fastfile with this but still no luck...
<pre>
  lane :beta do
    increment_build_number
    # match(type: "appstore") # more information: https://codesigning.guide
    update_project_provisioning(
        xcodeproj: 'Gradology.xcodeproj',
        profile: 'profile/test.mobileprovision',
        target_filter: '.*',
        build_configuration: '.*'
    )

    update_project_codesigning(path: "Gradology.xcodeproj",use_automatic_signing: true)

    gym(scheme: "gradology-ios",
     clean: true,
     workspace: "Gradology.xcworkspace",
     silent: true,
     buildlog_path: 'fastlane/logs')

    pilot(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
</pre>
