### ISSUE TITLE
Android: gradle action prints unexpected output

### ISSUE THREAD

**Issue by danielRi** [fastlane/fastlane#8058]
My build.gradle looks like this:

```
def versionNumber = "1.5.0"

task printVersion {
    println versionNumber
}
```

in my fastfile, I use the task `printVersion` to get the `versionNumber`.

```
versionNumber = gradle(
    task:'printVersion'
)
```
I use the `versionNumber` in artifactory action later:

```
artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-ltest1.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/Releases/stlg/REL_AND_STLG_#{versionNumber}_TEST1.apk"   # Path to place the artifact including its filename
    )
```

I expect the value of `versionNumber` to be:

```  
1.5.0.1
```

but other strings seem to be also going into that variable, see my error output:

```
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': [!] bad URI(is not URI?): lotto-apps/android/TestBinaries/stlg/REL_AND_STLG_Parallel execution with configuration on demand is an incubating feature. (URI::InvalidURIError)
1.5.0.1
Incremental java compilation is an incubating feature.
:android_stlg:printVersion UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.775 secs
_ISTEST.apk
```

(It says BUILD SCUCESSFUL but nothing is being pushed to my artifactory so it´s definetely not working.)
Anyone knows where the other output is comming from?

**Comment by danielRi** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.1                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.110.0"

default_platform :android

# get current Version of Project
versionNumber = gradle(
  task:'printVersion',
  print_command: true
)

versionString = versionNumber

platform :android do
  before_all do

    #ensure_git_status_clean

  end

  desc "Build Adhoc Binary for ITEST, TEST1 and TEST2 and publish all to Artifactory"
  lane :buildrc do

    gradle(
      task: 'assembleIstest'
    )

    gradle(
      task: 'assembleLtest1'
    )

    gradle(
      task: 'assembleLtest2'
    )

    artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-istest.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/TestBinaries/stlg/REL_AND_STLG_#{versionString}_ISTEST.apk"   # Path to place the artifact including its filename
    )

    artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-ltest1.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/TestBinaries/stlg/REL_AND_STLG_#{versionString}_TEST1.apk"   # Path to place the artifact including its filename
    )

    artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-ltest2.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/TestBinaries/stlg/REL_AND_STLG_#{versionString}_TEST2.apk"   # Path to place the artifact including its filename
    )


  end

  desc "Build Adhoc TEST1 and TEST2, Appstore Binary and publish all to Artifactory"
  lane :buildrelease do

    ensure_git_branch # defaults to `master` branch

    gradle(
      task: 'assembleLtest1'
    )

    gradle(
      task: 'assembleLtest2'
    )

    gradle(
      task: 'assembleProduktion'
    )

    artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-ltest1.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/Releases/stlg/REL_AND_STLG_#{version}_TEST1.apk"   # Path to place the artifact including its filename
    )

    artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-ltest2.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/Releases/stlg/REL_AND_STLG_#{version}_TEST2.apk"   # Path to place the artifact including its filename
    )

    artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-produktion.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/Releases/stlg/REL_AND_STLG_#{version}_PROD.apk"   # Path to place the artifact including its filename
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "de.multamedio.lottoapp.stlg" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status       |
| ------------------- | ------- | ------------------- |
| credentials_manager | 0.16.2  | 🚫 Update availaible |
| spaceship           | 0.38.0  | 🚫 Update availaible |
| fastlane_core       | 0.57.1  | 🚫 Update availaible |
| deliver             | 1.15.1  | 🚫 Update availaible |
| snapshot            | 1.16.4  | 🚫 Update availaible |
| frameit             | 3.0.0   | 🚫 Update availaible |
| pem                 | 1.4.0   | 🚫 Update availaible |
| cert                | 1.4.4   | 🚫 Update availaible |
| sigh                | 1.11.2  | 🚫 Update availaible |
| produce             | 1.3.1   | 🚫 Update availaible |
| gym                 | 1.12.1  | 🚫 Update availaible |
| pilot               | 1.12.1  | 🚫 Update availaible |
| scan                | 0.14.2  | 🚫 Update availaible |
| supply              | 0.7.1   | 🚫 Update availaible |
| match               | 0.11.0  | 🚫 Update availaible |
| screengrab          | 0.5.6   | 🚫 Update availaible |
| fastlane            | 1.110.0 | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| terminal-table            | 1.4.5        |
| json                      | 1.8.3        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| faraday_middleware        | 0.10.1       |
| dotenv                    | 2.1.1        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| plist                     | 3.2.0        |
| security                  | 0.1.3        |
| krausefx-shenzhen         | 0.14.11      |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| credentials_manager       | 0.16.2       |
| multi_xml                 | 0.5.5        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| xcode-install             | 2.0.9        |
| word_wrap                 | 1.0.0        |
| multi_json                | 1.12.1       |
| babosa                    | 1.0.2        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.1.7        |
| gh_inspector              | 1.0.2        |
| fastlane_core             | 0.57.1       |
| bundler                   | 1.13.6       |
| mini_magick               | 4.5.1        |
| xcpretty-travis-formatter | 0.0.4        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
</details>


*generated on:* **2017-01-31**
</details>

**Comment by hjanuschka** [comment]
@danielRi  thx for filinig the issue.

i am not sure if the gradle() action is supposed to work this way.
we do something similar here - but we set  the version number via fastfile.


```ruby
ENV["versionNumber"] = "1.5.0"
artifactory(
      username: ENV["ARTIFACTORY_USERNAME"],
      password: ENV["ARTIFACTORY_PASSWORD"],
      endpoint: ENV["ARTIFACTORY_URL"],
      file: "#{ENV["APP_BIN_DEST"]}/android_stlg-ltest1.apk",  # File to upload
      repo: "lotto-apps",       # Artifactory repo
      repo_path: "/android/Releases/stlg/REL_AND_STLG_#{ENV["versionNumber"]}_TEST1.apk"   # Path to place the artifact including its filename
    )
```


and to get this into java we have somthing like this in our shared gradle files:

```java
def versionNumber = System.env.versionNumber != null ? System.env.versionNumber  : "1.6.0"
```


this way we can set the version number via fastlane, if someone runs it without fastlane it defaults to "1.6.0"


let me know if this helps you.

**Comment by danielRi** [comment]
this is an option thank you. I wanted to keep the "origin" of the version in the build.gradle file, but if that´s not possible, your suggestion is also ok.

**Comment by hjanuschka** [comment]
you could also try to inspect the value that is returned by gradle.

```
v = gradle(task: "versionNumber")
puts v.inspect
```

maybe there is just a newline at the end 👍   (which you could remove with `v.chomp`)

**Comment by danielRi** [comment]
thanks for your time.

```
puts versionString.inspect 
// prints : "Parallel execution with configuration on demand is an incubating feature.\n1.5.0.1\nIncremental java compilation is an incubating feature.\n:android_stlg:printVersion UP-TO-DATE\n\nBUILD SUCCESSFUL\n\nTotal time: 0.805 secs\n"
```

**Comment by hjanuschka** [comment]
yeah that is what i was afraid of gradle returns the FULL gradle output, as when you run it in shell (`./gradlew versionNumber`) - in that case i think its nearly impossible to find the right line.

a hacky way would be:


```
task printVersion {
    println "@@" + versionNumber + "@@"
}
```


```ruby
v = gradle(task: "versionNumber")
real_version = v.split("@@")[1]
```


but as you see this is not even close to perfect 👍

**Comment by danielRi** [comment]
I´m fine with that solution, good idea. I will try it. Thank you. 👍

**Comment by hjanuschka** [comment]
good to know, i am closing the issue, feel free to reopen or create a new one once you need further help.!
