### ISSUE TITLE
Fastlane Gym Downloadable IPA

### ISSUE THREAD

**Issue by SilentHunter124** [fastlane/fastlane#8059]
I read your tutorial on how to integrate xcodeserver and fastlane with pre and post execution scripts. Normally xcode client gives me downloadable XCARCHIVE and IPA after running sucessfully a build bot.
Is it possible to do the same with fastlane tools? The developer should be able to download the signed ipa in their xcode integration window...? 

Would it be a nice feature for more people here?

**Comment by mgrebenets** [comment]
@SilentHunter124 

Could you provide more input, please?

As I understood, you're using `gym`. `gym` produces `xcarchive` as well as creates an `ipa`.
You can specify where to output the archive with `archive_path:` option and `output_name:` is the option you can use to specify output `ipa` file name.

Once `gym` is done, you need to collect the xcarchive and ipa and publish them as part of your CI build artifacts.

Each CI system has different ways to publish artifacts. I didn't use Xcode bots enough to know how to publish custom artifacts there.

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
