### ISSUE TITLE
Error when adding tvOS devices and update the provision file with Spaceship

### ISSUE THREAD

**Issue by hotsjf** [fastlane/fastlane#8063]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This is a bug related to Spaceship.

When you trying to add a new tvOS device and update the provision profile, you will get error message:

`Invalid deviceClass for profile type.
`

The problem is tvOS is not included as a subPlatform variable in portal_client.rb

Would be great if you guys can fix it in upcoming updates 

Thanks

##### Complete output when running fastlane, including the stack trace and command used

<details>
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/client.rb:449:in `parse_response': {"responseId"=>"0f3e6362-c0fa-4355-b24c-5c6d1c59543c", "resultCode"=>35, "resultString"=>"There were errors in the data supplied. Please correct and re-submit.", "userString"=>"Invalid deviceClass for profile type.", "creationTimestamp"=>"2017-01-31T19:53:04Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/profile/regenProvisioningProfile.action", "httpCode"=>200, "validationMessages"=>[{"validationKey"=>"provision.device.deviceclass.error", "validationUserMessage"=>"Invalid deviceClass for profile type."}]} (Spaceship::Client::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/portal/portal_client.rb:445:in `repair_provisioning_profile!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:381:in `block in update!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/client.rb:385:in `with_retry'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.13.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:380:in `update!'
</details>
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.13.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| json                      | 2.0.2        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-01-31**
</details>

**Comment by KrauseFx** [comment]
Looks like that's something that was introduced with the most recent release?

**Comment by lacostej** [comment]
Or could be related to #7815.

**Comment by hotsjf** [comment]
It's actually been there for a while, I guess not much people are working with tvOS devices.

I had some dirty patch on my own version of spaceship, but it would be great you guys can make an official fix :D

**Comment by lacostej** [comment]
@hotsjf Would you be able to try the PR in #7815? I suspect it will be merged any time soon but if you could confirm it is the same issue, it would be great. Thanks!

**Comment by hotsjf** [comment]
yes, what I'm reporting is just part of his PR.
specifically:
https://github.com/fastlane/fastlane/pull/7815/commits/f9b3791f069e95dc543316cd5f46f964c3e4942e#diff-039fca4abe1ab7d3789453780230a0b3
https://github.com/fastlane/fastlane/pull/7815/commits/f9b3791f069e95dc543316cd5f46f964c3e4942e#diff-ff2986eb23e8a88e58f19516741f6706

Please Merge 👍

**Comment by bassrock** [comment]
@hotsjf Looks like it was merged late last night.

**Comment by hotsjf** [comment]
@bassrock yes it was. So we should specify the subPlatform for tvOS profiles?
like
`profile.subPlatform = "tvOS"`
?
sorry I'm not native Ruby dev lol

**Comment by bassrock** [comment]
depends. How are you using it? Are you calling sigh or match or spaceship?

**Comment by hotsjf** [comment]
from spaceship.

I basically just need add new tvOS device, and update the profile.

**Comment by bassrock** [comment]
You should use sigh for that

**Comment by hotsjf** [comment]
@bassrock thanks, sigh won't do the entire job. so still need spaceship :D
