### ISSUE TITLE
[New Feature] Continuous Integration with Bitbucket Pipeline

### ISSUE THREAD

**Issue by younatics** [fastlane/fastlane#8069]
I want to integrate pipeline to fastlane! 
If it is possible, Could you give me some guideline that I can develop this feature? Thank you!

**Comment by hjanuschka** [comment]
hey @younatics, we already got a issue about bitbucket pipelines.
see here: https://github.com/fastlane/fastlane/issues/6647

could you provide a bit more information what bitbucket pipline supports?
i guess the minimum requirements are ruby and osx. (probably if you are doing an android app linux and ruby will work too)

**Comment by younatics** [comment]
I knew it was duplicate, but if fastlane team don't have enough time, I want to develop :)

**Comment by hjanuschka** [comment]
that would be great, you can have a look at the plugin guide -> https://docs.fastlane.tools/plugins/create-plugin/, let me know if you need any further help.

**Comment by younatics** [comment]
Great. I will try new plugin :)
