### ISSUE TITLE
ld: X duplicate symbols for architecture arm64

### ISSUE THREAD

**Issue by kraftydevil** [fastlane/fastlane#807]
I am able to archive this project from Xcode without linking errors, but I get duplicate symbols when linking in fastlane.

Lots of linking errors like this one:

```
❌  duplicate symbol l017 in
> GoogleMobileAds(GADAdNetworkJavaScriptAdViewDelegate.o)
> GoogleMobileAds(GADRewardBasedVideoAd+Mediation.o)
```
Crash report id: 890bd9921db4943c7488dbd82593e78e

```
Fastfile:
fastlane_version "1.37.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  lane :uat do
    gym(
        clean: true,
        workspace: "ObfuscatedWS.xcworkspace",
        configuration: "Release",
        scheme: "ObfuscatedSCH",
        )
  end
end
```

I've also tried using `include_symbols: true` but get the same result.

How can I avoid the duplicate symbols error just like Xcode does?

**Comment by xfreebird** [comment]
Under the hood ```gym``` is using ```xcodebuild``` to build, archive and export the app.
Have you tried running manually the same command ```gym``` executed ? You can see the commands to run from the ```fastlane``` output.

It could be something related to ```xcodebuild```.

**Comment by kraftydevil** [comment]
Definitely it's an issue with the project and xcodebuild. I'll post if I have a solution but I will close for now since this is outside of the fastlane scope.

**Comment by kraftydevil** [comment]
The solution came down to using an older version of Xcode (6.2). The duplicate symbols errors were removed when building with Xcode 7.1. I'm not sure of the particular problem project dependencies using 6.2 but the solution was ok for me.
