### ISSUE TITLE
Initializing with declared lazy var causes error

### ISSUE THREAD

**Issue by DBocksteger** [fastlane/fastlane#8070]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
07:40:43 .../workspace/.../CollectionViewController.swift:143:235: 
    extra argument 'timestamp' in call
07:40:43 ...forStruct: MyStruct(startDate: startDate.addingTimeInterval(-4 * 30 * 24 * 3600),
    endDate: endDate.addingTimeInterval(4 * 30 * 24 * 3600), timestamp: nil))
```

The same scheme with the same target can be compiled in Xcode directly without any error.

### Example

I've build a little example showing how MyStruct in the log above is implemented. In Xcode there is no upcoming error with the code we're using.

```
struct MyStruct {
    var startDate, endDate: Date
    lazy var timestamp = Date()
}

let anInstance = MyStruct(startDate: Date(), endDate: Date(), timestamp: Date())
```

Xcode suggests us to use the initializer with all three parameters.

<img width="723" alt="bildschirmfoto 2017-02-01 um 07 54 24" src="https://cloud.githubusercontent.com/assets/1019812/22497863/bc4829a2-e854-11e6-8b50-40404b247301.png">

But fastlane asks us for `let anFastlaneInstance = MyStruct(startDate: Date(), endDate: Date())` but Xcode is throwing an error then, that timestamp is Missing.

### Workaround

We've worked around this error/issue by changing the impekentation of our struct to something like this.

```
struct MyStruct {
    var startDate, endDate: Date
    var timestamp: Date
    
    init(startDate: Date, endDate: Date, timestamp: Date = Date()) {
        self.startDate = startDate
        self.endDate = endDate
        self.timestamp = timestamp
    }
}
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.12.3                                           |
| Ruby                | 2.2.4                                             |
| Bundler?            | false                                             |
| Git                 | git version 2.10.1 (Apple Git-78)                 |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane               |
| Host                | Mac OS X 10.12.3 (16D32)                          |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                        |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                        |
| Is contained        | false                                             |
| Xcode Path          | /Applications/Xcode_8.2.1.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.13.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-02-02**
</details>

**Comment by DBocksteger** [comment]
Added current environment

**Comment by lyndsey-ferguson** [comment]
fastlane is just running `xcodebuild` under the hood. Have you tried taking the command line argument that is being sent to `xcodebuild` and calling it directly from the Terminal?

**Comment by DBocksteger** [comment]
@lyndsey-ferguson yes we tried this, it is working by command-line, too.

**Comment by lyndsey-ferguson** [comment]
Can you include the output from fastlane?

**Comment by DBocksteger** [comment]
@lyndsey-ferguson I'm sorry but the snippet above is all i can publish from our log. Hoped it's enough to reproduce the error anywhere :(

**Comment by lyndsey-ferguson** [comment]
Unfortunately, it is not enough as it just points out the error. If I were to investigate it, I would look at the output from fastlane to learn:
- which action is being run, `gym`, `xcodebuild`
- what are the environment variables
- what is the exact `xcodebuild` command that is being executed from fastlane.
- what other errors or warnings are being emitted --> that would provide some clues

Maybe the above is enough for you to figure it out without providing more info here. Like clues or things to think about.

**Comment by DBocksteger** [comment]
I've installed xcode and fastlane fresh and clean again and it works now with my demo project, containing the code snippet above.

**Comment by hjanuschka** [comment]
@DBocksteger awesome!! glad it works now, i am going to close the issue then, feel free to reopen or file a new issue whenever needed.
