### ISSUE TITLE
Add frameit font size change & documentation

### ISSUE THREAD

**Issue by ownmas** [fastlane/fastlane#8072]
Please, add ability to change frameit text font size. It is VERY important. Look at my screens which i made with frameit: https://appsto.re/ru/gIX9gb.i. They are pretty bad, because font size is very small.

And please, make a documentation about frameit. I already seem these https://docs.fastlane.tools/getting-started/ios/screenshots/. But it is not a documentation, it is TUTORIALS.

Thank you.

**Comment by Damnum** [comment]
The problem is your text is too long so the default text size is shrunken.

Try to add \n inside the text, you'll get two lines with bigger font.
