### ISSUE TITLE
Fastlane init fails for Mac (OSX) app

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#8073]
### New Issue Checklist

- [ y] Updated fastlane to the latest version
- [ y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running fastlane init for a mac app where the app has not been created in iTunes connect has the following errors:

1) an IOS app ID is created (should be Mac app ID)
2) fastlane incorrectly reports that it cannot create the app as the name has been taken

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
```

[12:10:55]: Detected iOS/Mac project in current directory...
[12:10:55]: This setup will help you get up and running in no time.
[12:10:55]: fastlane will check what tools you're already using and set up
[12:10:55]: the tool automatically for you. Have fun! 
[12:10:55]: $ xcodebuild -list -workspace ./AV\ Rules.xcworkspace
2017-02-01 12:10:56.381 xcodebuild[3349:7391616] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OneSkyPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[12:10:57]: $ xcodebuild clean -showBuildSettings -workspace ./AV\ Rules.xcworkspace -scheme AV\ Rules
2017-02-01 12:10:57.234 xcodebuild[3355:7391701] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OneSkyPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
Your Apple ID (e.g. fastlane@krausefx.com): hobbyist@hobbyistsoftware.com
[12:11:08]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
[12:11:08]: Starting login with user 'hobbyist@hobbyistsoftware.com'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) JHV5RC82C3 "Hobbyist Software Limited" (Company/Organization)
2) VB58G7KRUY "Rhythm Skydiving LLC" (Company/Organization)
1
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "18645"

or

  itc_team_name "Hobbyist Software Limited"

1) "Hobbyist Software Limited" (18645)
2) "Rhythm Skydiving LLC" (118508946)
1

+----------------+-------------------------------------------------------------------------------------------+
|                                              Detected Values                                               |
+----------------+-------------------------------------------------------------------------------------------+
| Apple ID       | hobbyist@hobbyistsoftware.com                                                             |
| App Name       | AV Rules                                                                                  |
| App Identifier | com.HobbyistSoftware.AV-Rules                                                             |
| Workspace      | /Users/rob/Documents/Development/Mac/MacDesktopSwift/AVRules/AVRules/AV Rules.xcworkspace |
+----------------+-------------------------------------------------------------------------------------------+

[12:11:25]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[12:11:25]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
Please confirm the above values (y/n)
y
[12:11:31]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[12:11:31]: Creating the app on iTunes Connect and the Apple Developer Portal
[12:11:31]: $ xcodebuild clean -showBuildSettings -workspace ./AV\ Rules.xcworkspace
xcodebuild: error: If you specify a workspace then you must also specify a scheme.  Use -list to see the schemes in this workspace.

+----------------+-------------------------------+
|           Summary for produce 2.13.0           |
+----------------+-------------------------------+
| app_name       | App                           |
| app_identifier | com.HobbyistSoftware.AV-Rules |
| username       | hobbyist@hobbyistsoftware.com |
| sku            | 1485951092                    |
| platform       | ios                           |
| language       | English                       |
| skip_itc       | false                         |
| skip_devcenter | false                         |
| team_id        | JHV5RC82C3                    |
+----------------+-------------------------------+

[12:11:36]: Creating new app 'App' on the Apple Dev Center
[12:11:39]: Created app LF6YQU822N
[12:11:39]: Finished creating new app 'App' on the Dev Center
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "18645"

or

  itc_team_name "Hobbyist Software Limited"

1) "Hobbyist Software Limited" (18645)
2) "Rhythm Skydiving LLC" (118508946)
1
[12:11:49]: Creating new app 'App' on iTunes Connect
[12:11:52]: It looks like that App has already been taken by someone else, please enter an alternative.
App Name: 
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.HobbyistSoftware.AV-Rules" # The bundle identifier of your app
apple_id "hobbyist@hobbyistsoftware.com" # Your Apple email address

team_id "JHV5RC82C3"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.13.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| did_you_mean              | 1.0.0       |
| slack-notifier            | 1.5.1       |
| rouge                     | 1.10.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.6.3       |
| terminal-table            | 1.4.5       |
| plist                     | 3.1.0       |
| addressable               | 2.4.0       |
| multipart-post            | 2.0.0       |
| word_wrap                 | 1.0.0       |
| babosa                    | 1.0.2       |
| colored                   | 1.2         |
| highline                  | 1.7.8       |
| commander                 | 4.4.0       |
| excon                     | 0.45.4      |
| faraday                   | 0.9.2       |
| unf_ext                   | 0.0.7.1     |
| unf                       | 0.1.4       |
| domain_name               | 0.5.25      |
| http-cookie               | 1.0.2       |
| faraday-cookie_jar        | 0.0.6       |
| fastimage                 | 1.6.8       |
| gh_inspector              | 1.0.2       |
| uber                      | 0.0.15      |
| representable             | 2.3.0       |
| retriable                 | 2.1.0       |
| mime-types-data           | 3.2016.0521 |
| mime-types                | 3.1         |
| hurley                    | 0.2         |
| little-plugger            | 1.1.4       |
| multi_json                | 1.12.1      |
| logging                   | 2.0.0       |
| jwt                       | 1.5.6       |
| memoist                   | 0.14.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.2       |
| googleauth                | 0.5.1       |
| thor                      | 0.19.1      |
| httpclient                | 2.8.2.4     |
| google-api-client         | 0.9.3       |
| json                      | 1.8.3       |
| mini_magick               | 4.5.1       |
| multi_xml                 | 0.5.5       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| xcpretty-travis-formatter | 0.0.4       |
| dotenv                    | 2.1.1       |
| bundler                   | 1.12.5      |
| faraday_middleware        | 0.10.0      |
| io-console                | 0.4.5       |
| CFPropertyList            | 2.3.4       |
| claide                    | 1.0.1       |
| nanaimo                   | 0.2.3       |
| xcodeproj                 | 1.4.2       |
</details>

*generated on:* **2017-02-01**
</details>

**Comment by cherpake** [comment]
Hey, getting this error for my Mac app: 

Could not find app with app identifier 'com.cherpake.strings.manager' in your iTunes Connect account (d314127481@gmail.com - Team: 2028706)

Even though it exists and available on the Mac App Store.

**Comment by KrauseFx** [comment]
Sorry, _fastlane_ doesn't support macOS apps for now 😢

**Comment by cherpake** [comment]
Hey,

I guess I got confused by this sentence: 
"fastlane is a tool for iOS, Mac, and Android developers to automate tedious tasks like generating screenshots, dealing with provisioning profiles, and releasing your application."

Here: 
https://github.com/fastlane/fastlane <https://github.com/fastlane/fastlane>

-E

**Comment by KrauseFx** [comment]
ohhh, thanks for pointing this out, we'll fix the documentation. In the past we supported macOS for some of our tools.

**Comment by KrauseFx** [comment]
Working on this now 👍
