### ISSUE TITLE
deliver - contact information not updated

### ISSUE THREAD

**Issue by rompic** [fastlane/fastlane#8075]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have the strong impression that the app review information is not updated even though
app_review_information is set correctly.

can anyone test this easily?

**Comment by rompic** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_AT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do
  before_all do
    xcode_select "/Applications/Xcode_7.app"
	setup_jenkins
  end
  
  desc "Deliver a version to the appstore"
  lane :AppStore do |options|
...
  
  	deliver(
    	ipa:"build/example.ipa",
    	submit_for_review: false,
    	screenshots_path:"./fastlane/#{options[:city]}/screenshots",
    	metadata_path: "./fastlane/#{options[:city]}/metadata",
    	force:true, #do not create html report
    	automatic_release: false,
		itc_provider: '---',
		price_tier: 0,
		app_rating_config_path: "./fastlane/rating.json",
		app_review_information:{
		  "first_name" => "My",
		  "last_name" => "Name",
		  "phone_number" => "+43 0000",
		  "email_address" => "example@example.com"
		}
  	)
  end

 
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of your app
apple_id "example@example.com" # Your Apple email address

team_name "example"
team_id "asdf" # Developer Portal Team ID

itc_team_name "asdf"
itc_team_id "1234" # iTunes Connect Team ID

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.13.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.1.0        |
| xcodeproj                 | 1.4.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2017-02-01**
</details>

**Comment by ohayon** [comment]
Hey @rompic, could you provide a bit more context around what is going wrong? 😄  We would love to help but it would be great to know how you are calling _deliver_, what your terminal output looks like, and any other information you can provide to help us figure out whats going on. Thanks! 🐙

**Comment by rompic** [comment]
we recently changed our contact information in the fastfile but it doesn't update the review information at least not the first_name, last_name attributes.

we call deliver/ app_review_information from a fastlane lane using the following data:

  	deliver(
    	ipa:"path/to/ipa.ipa",
    	submit_for_review: false,
    	screenshots_path:"./path/to/screenshots",
    	metadata_path: "./path/to/metadata",
    	force:true, #do not create html report
    	automatic_release: false,
      itc_provider: 'example',
      price_tier: 0,
      app_rating_config_path: "./path/to/rating.json",
      app_review_information:{
        "first_name" => "name",
        "last_name" => "surname",
        "phone_number" => "+43 00000",
        "email_address" => "support@example.com"
      }
  	)
  	
everything looks good in the summary
+--------------------------------------+-----------------------------------+
|                          deliver 2.12.0 Summary                          |
+--------------------------------------+-----------------------------------+
| ipa                                  | path/to/ipa.ipa                   |
| submit_for_review                    | false                             |
| screenshots_path                     | ../path/to/screenshots            |
| metadata_path                        | ../path/to/metadata               |
| force                                | true                              |
| automatic_release                    | false                             |
| itc_provider                         | example                           |
| price_tier                           | 0                                 |
| app_rating_config_path               | ./pat/to/rating.json              |
| app_review_information.first_name    | name                              |
| app_review_information.last_name     | surname                           |
| app_review_information.phone_number  | +43 00000                         |
| app_review_information.email_address | support@example.com               |
| app_identifier                       | com.example.app                   |
| app_version                          | 1.1.10                            |
| username                             | user@example.com                  |
| edit_live                            | false                             |
| platform                             | ios                               |
| skip_binary_upload                   | false                             |
| skip_screenshots                     | false                             |
| skip_metadata                        | false                             |
| team_id                              | 111111                            |
| team_name                            | teamname                          |
| dev_portal_team_id                   | 123456                            |
| dev_portal_team_name                 | teamname                          |
| overwrite_screenshots                | false                             |
+--------------------------------------+-----------------------------------+  	

but it is not changed in the appstore.

I currently cannot test it, but it would be great if you could look into this / give me a hint what we are doing wrong.

Thx!

**Comment by KrauseFx** [comment]
I just tried running this on one of my sample apps and it seemed to have worked. Can you provide some more information on how to reproduce?

**Comment by rompic** [comment]
just tested it again (changed the first_name attribute) today and it still does not update, while it is correctly reflected in the deliver summary (| app_review_information.first_name    | New FirstName                    |

:(

**Comment by KrauseFx** [comment]
@rompic could you confirm the version of _fastlane_ you're using?

**Comment by rompic** [comment]
fastlane 2.28.9
deliver 2.28.9
