### ISSUE TITLE
`import_from_git` + Custom Actions

### ISSUE THREAD

**Issue by kcharwood** [fastlane/fastlane#808]
Loving Fastlane so far.

I'm looking to centralize my fastlane setup for multiple projects, and one thing I have is multiple custom actions that needs to be used by the fastlanes. 

I see the `import_from_git` action, and understand that would allow me to share a fastfile, but what is the best way to also share those custom actions?

I apologize if there is a way to do it, and I have missed it. If there is, perhaps there is a documentation improvement that can come of that.

Looking forward to sharing my setup soon :)

**Comment by xfreebird** [comment]
Hi @kcharwood, basically you would have the same structure on git, as for a standard project:

```shell
fastlane/
          - Fastfile
          - actions/
                   - myaction1
                   - myaction2
```

You should import on the top above your lane declarations. When defining a new lane fastlane will make sure to not run into any name conflicts. If you want to overwrite an existing lane (from the imported one), use the override_lane keyword.

https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md

Cheers

**Comment by KrauseFx** [comment]
Also, check out the fastlane usage of fastlane: https://github.com/fastlane/fastlane/tree/master/fastlane :rocket:

**Comment by kcharwood** [comment]
Thanks @xfreebird. So import_from_git brings the fastfile as well as the custom actions along for me to use.

That is what I was looking for! It may be helpful to update the docs to clarify that. Thanks!

**Comment by kcharwood** [comment]
Should `fastlane actions` print out the custom actions from the imported fastlane? I'm not seeing that in my current test.

**Comment by KrauseFx** [comment]
Thanks @kcharwood :+1:
