### ISSUE TITLE
"no implicit conversion of nil into String" in fastlane init

### ISSUE THREAD

**Issue by shanna** [fastlane/fastlane#8083]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Setting up a brand new IOS project I ran into:
* Missing duck typing or type checking of values.
* Occurred is spelled wrong in the error output.

```
react-native init MyProject
cd MyProject
fastlane init
```

### Capture

```
~/dev/src/github.com/shanna/my-project λ fastlane init --verbose
DEBUG [2017-02-02 13:57:22.22]: Checking if there are any plugins that should be loaded...
INFO [2017-02-02 13:57:22.24]: Couldn't automatically detect the platform
Is this project an iOS project? (y/n) y
INFO [2017-02-02 13:57:33.35]: This setup will help you get up and running in no time.
INFO [2017-02-02 13:57:33.35]: fastlane will check what tools you're already using and set up
INFO [2017-02-02 13:57:33.35]: the tool automatically for you. Have fun!
Couldn't automatically detect the project file, please provide a path: ./ios/MyProject.xcodeproj
INFO [2017-02-02 13:57:36.28]: $ xcodebuild clean -showBuildSettings -project ./ios/MyProject.xcodeproj
Your Apple ID (e.g. fastlane@krausefx.com): **removed**
WARN [2017-02-02 13:57:42.62]: Verifying if app is available on the Apple Developer Portal and iTunes Connect...
INFO [2017-02-02 13:57:42.62]: Starting login with user '**removed**'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use:
1) **removed** (Individual)
2) **removed** (Company/Organization)
2
Multiple iTunes Connect teams found, please enter the number of the team you want to use:
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "**removed**"

or

  itc_team_name "**removed**"

1) "**removed**" (**removed**)
2) "**removed**" (**removed**)
2

+----------------+---------------------------------------------------------------------------------------------------+
|                                                  Detected Values                                                   |
+----------------+---------------------------------------------------------------------------------------------------+
| Apple ID       | **removed**
| App Name       | MyProject
| App Identifier |
| Project        | /Users/shane/dev/src/github.com/shanna/my-project/ios/MyProject.xcodeproj
+----------------+---------------------------------------------------------------------------------------------------+

WARN [2017-02-02 13:57:52.31]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
WARN [2017-02-02 13:57:52.31]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
Please confirm the above values (y/n)
y
ERROR [2017-02-02 13:57:55.34]: no implicit conversion of nil into String
ERROR [2017-02-02 13:57:55.34]: An error occured during the setup process. Falling back to manual setup!
App Identifier (com.krausefx.app):
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/local/ruby/bin/fastlane                   |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/local/ruby/lib                            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.13.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version  |
| ------------------------- | -------- |
| did_you_mean              | 1.0.0    |
| slack-notifier            | 1.5.1    |
| CFPropertyList            | 2.3.4    |
| claide                    | 1.0.1    |
| colored                   | 1.2      |
| nanaimo                   | 0.2.3    |
| xcodeproj                 | 1.4.2    |
| rouge                     | 1.11.1   |
| xcpretty                  | 0.2.4    |
| terminal-notifier         | 1.7.1    |
| terminal-table            | 1.4.5    |
| plist                     | 3.2.0    |
| multipart-post            | 2.0.0    |
| word_wrap                 | 1.0.0    |
| babosa                    | 1.0.2    |
| highline                  | 1.7.8    |
| commander                 | 4.4.3    |
| excon                     | 0.54.0   |
| faraday                   | 0.9.2    |
| unf_ext                   | 0.0.7.2  |
| unf                       | 0.1.4    |
| domain_name               | 0.5.13   |
| http-cookie               | 1.0.1    |
| faraday-cookie_jar        | 0.0.6    |
| fastimage                 | 2.0.1    |
| gh_inspector              | 1.0.2    |
| uber                      | 0.0.15   |
| representable             | 2.3.0    |
| retriable                 | 2.1.0    |
| mime-types                | 1.25.1   |
| hurley                    | 0.2      |
| little-plugger            | 1.1.4    |
| multi_json                | 1.12.1   |
| logging                   | 2.1.0    |
| jwt                       | 1.5.1    |
| memoist                   | 0.15.0   |
| os                        | 0.9.6    |
| signet                    | 0.7.3    |
| googleauth                | 0.5.1    |
| httpclient                | 2.8.3    |
| google-api-client         | 0.9.26   |
| json                      | 1.8.3    |
| mini_magick               | 4.5.1    |
| multi_xml                 | 0.5.5    |
| rubyzip                   | 1.2.0    |
| security                  | 0.1.3    |
| xcpretty-travis-formatter | 0.0.4    |
| dotenv                    | 2.2.0    |
| bundler                   | 1.14.3   |
| faraday_middleware        | 0.11.0.1 |
| i18n                      | 0.7.0    |
| thread_safe               | 0.3.5    |
| tzinfo                    | 1.2.2    |
| activesupport             | 4.2.7.1  |
| io-console                | 0.4.5    |
</details>

*generated on:* **2017-02-02**
</details>

**Comment by KrauseFx** [comment]
Can you share the complete stack trace too? If it isn't shown by default, please run it again using `--verbose` 👍

**Comment by shanna** [comment]
The output I've pasted was running with `--verbose` flag but it didn't give me a stack trace. It prints the error as you see in the output (with no stack trace) and then continues execution to `App Identifier (...):`.

**Comment by KrauseFx** [comment]
Yeah, we'd need the stack trace to look into this issue, thanks.
