### ISSUE TITLE
ERROR ITMS-90189: "Redundant Binary Upload

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#8085]
I get the error `ERROR ITMS-90189: "Redundant Binary Upload` with every build, despite the fact the the build number is unique and being incremented automatically with each build.  In fact, the build is working correctly - but I'm still seeing this error:

```
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

ERROR [2017-02-02 14:47:38.43]: [Transporter Error Output]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '402' for version '1.0'"
ERROR [2017-02-02 14:47:38.43]: ERROR ITMS-90189: "Redundant Binary Upload. There already exists a binary upload with build '402' for version '1.0'"
ERROR [2017-02-02 14:47:38.43]: You have to change the build number of your app to upload your ipa file

```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.6.2                           |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.13.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| colored                   | 1.2          |
| claide                    | 1.0.1        |
| xcodeproj                 | 1.3.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.53.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.5       |
| faraday_middleware        | 0.10.0       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-02-02**
</details>

**Comment by mgrebenets** [comment]
@npomfret This error comes directly from iTunesConnect afaik.

Could you double check the value of `CFBundleVersion` key-value pair in your app's `Info.plist`?

I had this error number of times and in all cases it was because I was indeed uploading build with same build number.

**Comment by hjanuschka** [comment]
also check that you don't have an old `.ipa` in your folder, i had that once that it uploaded the wrong ipa, which has been built/submitted before

**Comment by npomfret** [comment]
Thanks for the replies.  When I run my build, 3 files get updated with the version number.  There are 2 `info.plist` files (one for the app and one for the tests) with a value in `CFBundleVersion` and the `project.pbxproj` file with a value in `CURRENT_PROJECT_VERSION`.  They are currently all set to 403 which is the same as the current version of my app.  The next build will increment them all before it builds the app.  

My build works, the app gets uploaded fine.  But I always see this error message.
