### ISSUE TITLE
Fastlane init causes undefined methond 'underline' error

### ISSUE THREAD

**Issue by osolano** [fastlane/fastlane#8095]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have an existing project and running fastlane for first time. I have just finished the setup for automatic build version increment and now when I run fastlane init I get this error

##### Complete output when running fastlane, including the stack trace and command used

`fastlane init`

```
undefined method `underline' for "\e[36m$ xcodebuild -list -workspace ./XXXXXXX.xcworkspace\e[0m":String
Did you mean?  underlined
               underlined!
[16:01:13]: An error occured during the setup process. Falling back to manual setup!
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored2                  | 3.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| json                      | 2.0.2        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-02-02**
</details>

**Comment by interstateone** [comment]
@osolano This sounds like the same root issue as https://github.com/fastlane/fastlane/issues/8093. Can you confirm that the full stack trace when running `fastlane init` contains something like `shell.rb:59:in `command': [!] undefined method `underline'` in it? Maybe post the full stack trace in your PR description if you can, it'd probably help the maintainers here.

**Comment by osolano** [comment]
#### Full Stack Trace

fastlane init --verbose
Successfully loaded Appfile at path '/Users/xxxxxxx/work/ProjectName/fastlane/Appfile'
- app_identifier: 'com.xxxxxxx.ProjectName'
- apple_id: 'osolano@healthwe.co'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
DEBUG [2017-02-02 16:47:45.49]: Checking if there are any plugins that should be loaded...
INFO [2017-02-02 16:47:45.50]: Detected iOS/Mac project in current directory...
INFO [2017-02-02 16:47:45.50]: This setup will help you get up and running in no time.
INFO [2017-02-02 16:47:45.50]: fastlane will check what tools you're already using and set up
INFO [2017-02-02 16:47:45.50]: the tool automatically for you. Have fun!
ERROR [2017-02-02 16:47:45.51]: undefined method `underline' for "\e[36m$ xcodebuild -list -workspace ./ProjectName.xcworkspace\e[0m":String
Did you mean?  underlined
               underlined!
ERROR [2017-02-02 16:47:45.51]: An error occured during the setup process. Falling back to manual setup!
App Identifier (com.krausefx.app): ^C/Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:870:in `gets': Interrupt
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:870:in `get_line'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:891:in `get_response'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/highline-1.7.8/lib/highline.rb:264:in `ask'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:94:in `input'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/setup/setup_ios.rb:150:in `ask_for_app_identifier'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/setup/setup_ios.rb:156:in `generate_appfile'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/setup/setup_ios.rb:75:in `manual_setup'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/setup/setup_ios.rb:56:in `try_manual_setup'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/setup/setup_ios.rb:41:in `rescue in run'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/setup/setup_ios.rb:23:in `run'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/setup/setup.rb:24:in `run'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:121:in `block (2 levels) in run'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/bin/fastlane:15:in `<top (required)>'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/xxxxxxx/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by osolano** [comment]
I also get the same issue when running one of the lanes on fast lane.. but a slightly different stack track trace after creating a fastfile manually... here ```shell.rb:59:in``` mentions pod install

#### Full Stack Trace after running fastfile beta

`fastlane beta
[16:51:55]: -------------------------------------------------
[16:51:55]: --- Step: Verifying required fastlane version ---
[16:51:55]: -------------------------------------------------
[16:51:55]: Your fastlane version 2.14.0 matches the minimum requirement of 2.14.0  ✅
[16:51:55]: ------------------------------
[16:51:55]: --- Step: default_platform ---
[16:51:55]: ------------------------------
[16:51:55]: Driving the lane 'ios beta' 🚀
[16:51:55]: -----------------------
[16:51:55]: --- Step: cocoapods ---
[16:51:55]: -----------------------
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[16:51:56]: undefined method `underline' for "\e[36m$ pod install\e[0m":String
Did you mean?  underlined
               underlined!

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | cocoapods                           | 0           |
+------+-------------------------------------+-------------+

[16:51:56]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:59:in `command': [!] undefined method `underline' for "\e[36m$ pod install\e[0m":String (NoMethodError)
Did you mean?  underlined
               underlined!
Did you mean?  underlined
               underlined!
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/helper/sh_helper.rb:29:in `sh_control_output'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/helper/sh_helper.rb:10:in `sh'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/actions/cocoapods.rb:27:in `run'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:21:in `block (2 levels) in parsing_binding'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:255:in `execute_flow_block'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0@global/gems/fastlane-2.14.0/bin/fastlane:15:in `<top (required)>'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/oliversolano/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'`

**Comment by KrauseFx** [comment]
Really sorry about this, new release will go live in about 5 minutes fixing this 🚀 We'll add tests for this to make sure this won't happen again 👍

**Comment by KrauseFx** [comment]
The new release is live [2.14.1](https://github.com/fastlane/fastlane/releases/tag/2.14.1), please update to the most recent version and let me know if that fixes the problem.

Again, I'm super sorry this happened, we'll add more tests to cover this area as well 👍

**Comment by osolano** [comment]
That did it! Thanks for the super fast reply!
