### ISSUE TITLE
Fastlane crashes when disabling colors

### ISSUE THREAD

**Issue by rvi** [fastlane/fastlane#8100]
### Issue Description

Disabling colors makes Fastlane crash. It was working well before updating to 2.14 (from 2.7).

```
$ export FASTLANE_DISABLE_COLORS=1
$ fastlane test --capture_output
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/ui/disable_colors.rb:12:in `<class:String>': uninitialized constant Colored2::EXTRAS (NameError)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/ui/disable_colors.rb:6:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/ui/ui.rb:26:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core.rb:27:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane.rb:1:in `<top (required)>'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/Cellar/ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

```
$ export FASTLANE_DISABLE_COLORS=0
$ fastlane env
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

```ruby

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.2   |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.10.1  |
| xcpretty                  | 0.2.4   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored2                  | 3.1.1   |
| highline                  | 1.7.8   |
| commander                 | 4.4.1   |
| faraday-cookie_jar        | 0.0.6   |
| gh_inspector              | 1.0.2   |
| mini_magick               | 4.5.1   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| bundler                   | 1.13.6  |
| i18n                      | 0.7.0   |
| json                      | 1.8.3   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| activesupport             | 4.2.6   |
| io-console                | 0.4.6   |
| excon                     | 0.54.0  |
| rubyzip                   | 1.2.0   |
| plist                     | 3.2.0   |
| CFPropertyList            | 2.3.4   |
| claide                    | 1.0.1   |
| colored                   | 1.2     |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.1   |
| unicode-display_width     | 1.1.2   |
| terminal-table            | 1.7.3   |
</details>

*generated on:* **2017-02-02**
</details>
```

**Comment by hjanuschka** [comment]
i did a PR can you give it a try #8103

**Comment by lacostej** [comment]
Weird that `Colored2::EXTRAS` is not found but `Colored2::COLORS` is. How is this lib pulled in?

**Comment by hjanuschka** [comment]
@lacostej  i updated the PR the real deal is that in colored it is called `EXTRAS` and in colored2 it is called `EFFECTS` -> http://www.rubydoc.info/gems/colored2/2.0.2/Colored2
