### ISSUE TITLE
 How to use spaceship to upload videos? Are there examples?

### ISSUE THREAD

**Issue by ShenJieSuzhou** [fastlane/fastlane#8105]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I would like to use spaceship to upload video, but did not find more documents, are there examples I can refer to?

**Comment by lacostej** [comment]
@ShenJieSuzhou It's not possible due to a bug, but will be attended soon (in a few days)
