### ISSUE TITLE
Crash on registering device UDID

### ISSUE THREAD

**Issue by RomanVolkov** [fastlane/fastlane#8106]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$ fastlane run register_devices devices: ".Device name"=<real UDID instead> && match development --force
[12:52:37]: ------------------------------
[12:52:37]: --- Step: register_devices ---
[12:52:37]: ------------------------------
[12:52:37]: To not be asked about this value, you can specify it using 'username'
Optional: Your Apple ID: <my email>

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane reporting apple developer website is down
   https://github.com/fastlane/fastlane/issues/5918 [closed] 19 💬
   06 Dec 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/actions/register_devices.rb:23:in `run': [!] undefined method `map' for "":String (NoMethodError)
Did you mean?  tap
Did you mean?  tap
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/one_off.rb:41:in `run'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/one_off.rb:22:in `execute'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/commands_generator.rb:191:in `block (2 levels) in run'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.14.1/bin/fastlane:15:in `<top (required)>'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/bin/fastlane:22:in `load'
	from /Users/romanvolkov/.rbenv/versions/2.3.3/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.12.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'Snapajob', export_method: 'development')

    emails = values[:test_email] ? values[:test_email] : [] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '',
             build_secret: '',
                   emails: emails,
                   groups: groups,
                    notes: '', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored2                  | 3.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-02-03**
</details>

**Comment by RomanVolkov** [comment]
The main issue it 
run': [!] undefined methodmap' for "":String (NoMethodError)
Did you mean? tap
Did you mean? tap

I'm not sure it's related to code signing

**Comment by ohayon** [comment]
Hey @RomanVolkov! 👋  It looks like this crash is coming from way that `register_devices` is getting called. It is not currently supported to call it on the command line with a hash of devices. Instead, its best practice to follow the example here: https://docs.fastlane.tools/actions/#register_devices

Let us know if you have any problems down the line! 🐙
