### ISSUE TITLE
reset_git_repo shouldn't always delete untracked files

### ISSUE THREAD

**Issue by 7mllm7** [fastlane/fastlane#811]
If you have a file like `.env` in your repository, then it will be deleted when you call `reset_git_repo` upon error. I kept setting `.env` up (for credentials) and every time the build failed, it would disappear.
So I'm suggesting to add a `skip_clean` option to this action to skip the `git clean` step in it.

**Comment by 7mllm7** [comment]
Created a pull request https://github.com/fastlane/fastlane/pull/812

**Comment by KrauseFx** [comment]
Closed with https://github.com/fastlane/fastlane/pull/812
