### ISSUE TITLE
kernel_require.rb:133:in `require': cannot load such file -- colored2 (LoadError)

### ISSUE THREAD

**Issue by mike011** [fastlane/fastlane#8112]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When ever I run any fastlane command I get a stack trace. This just started when I upgraded yesterday to fastlane 2-14

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

<pre> /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in` `require': cannot load such file -- colored2 (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/helper.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core.rb:10:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane/lib/fastlane.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
</pre>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

Can't, get the stack trace from above. I'm running fastlane-2.14.1,

**Comment by isigui** [comment]
I've got the same error

**Comment by mike011** [comment]
As noted above, when I run 'fastlane env', I also get the exception message.

<pre>
fastlane env
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- colored2 (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core/helper.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane_core/lib/fastlane_core.rb:10:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane/lib/fastlane.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/fastlane/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.1/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
</pre>

**Comment by quver** [comment]
Probably `gem install colored2` fix problem but I'm going to test it ASAP

**Comment by ildar-gilfanov-e-legion** [comment]
No it doesn't help. I have the same issue

**Comment by mike011** [comment]
Can't reproduce with fastlane 2.13.0

**Comment by ildar-gilfanov-e-legion** [comment]
`sudo gem uninstall fastlane `
`sudo gem install fastlane -v 2.12`

This is solution for now

**Comment by quver** [comment]
With 2.13 I still have crash

**Comment by isigui** [comment]
Unfortunately I'm using a deploy task from visual studio team services which install the lastest version of fastlane (ie 2.14.1). I've no hand on it ;(

**Comment by DanToml** [comment]
@isigui @mike011 Please could you try running `gem uninstall colored2` (if this prompts for a version to uninstall, select all), then run `gem install colored2 --version 3.1.1`?

**Comment by isigui** [comment]
Hello @DanToml , Just tried what you propose. I uninstall colored2 (it was already version 3.1.1) and reinstall colored 2 version 3.1.1.
Still have the same issue.

**Comment by mike011** [comment]
Thx @KrauseFx 👍

**Comment by KrauseFx** [comment]
Hey everyone, really sorry about this, just added a PR that reverts the change https://github.com/fastlane/fastlane/pull/8117

**Comment by kigster** [comment]
@KrauseFx Hey man, I am the author of colored2 — I am really surprised about this issue, and would love to help. I'll see if I can reproduce this problem on my system. Any suggestions on how to repro are much appreciated. Thanks!

**Comment by samratBasra** [comment]
gem install fastlane -v 2.12

thats the perfect solution

**Comment by KrauseFx** [comment]
Hey @kigster, sorry for the late reply - I can't read all GitHub notifications, so it's easy to miss some sometimes. When rolling out `colored2` everything worked perfectly on our machines, however we've got multiple issues being submitted with all kinds of weird error messages. We had to quickly rollback the change to do some damage control. 
It seems like lots of setups are very different (maybe different platforms, shell environments, ...), I don't know, but for us it's too risky to try to roll this out again, we'll have to stay with `colored` for now.

@samratBasra Please don't do that, we've already rolled out a patch a while ago, please update to the most recent release, which also fixes that problem, just update using `fastlane update_fastlane`

**Comment by kigster** [comment]
@KrauseFx Do what you must, but the issue has been identified and fixed. It was a simple permissions issue that ONLY comes into the effect when ruby is installed as root.

For most folks that use `rbenv` or `rvm` and install ruby as the user that uses it, the issue was not even there. 

But the permissions problem has been fixed in the last version of colored2.

**Comment by kigster** [comment]
Please note that version 3.1.1 has been yanked, and replaced with 3.1.2 that should work everywhere.

**Comment by KrauseFx** [comment]
> For most folks that use rbenv or rvm and install ruby as the user that uses it, the issue was not even there.

Most _fastlane_ users use System Ruby as they're iOS and Android developers and often not familar with Ruby.

I'll close this issue for now, thanks everyone for helping on this

**Comment by yakimant** [comment]
@KrauseFx, also i've seen with xcode tools if using not system Ruby.

**Comment by kigster** [comment]
Like I mentioned before the issue has been fixed.

Feel free to continue using original `colored` gem, but for those who prefer a more up to date version `colored2` should no longer have any permissions issues, afaik.

Thanks!

**Comment by yogesh-nykaa** [comment]
I have also faced this issue on `2.35.1` version. But after using command `sudo fastlane` it's working fine.
