### ISSUE TITLE
[Regression] "fastlane match nuke distribution" fails

### ISSUE THREAD

**Issue by rhcpfan** [fastlane/fastlane#8113]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After running `fastlane match dstribution`, I get ```/Users/Administrator/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.1/match/lib/match.rb:35:in `cert_type_sym': [!] Unknown cert type: 'distribution' (RuntimeError)```

I think (but I'm not sure) that you can fix this by changing line 34 from `match/lib/match.rb` from 
```ruby
return :distribution if type == "adhoc" || type == "appstore"
```
to
```ruby
return :distribution if type == "adhoc" || type == "appstore" || type == "distribution"
```

I guess it's a bug from the latest release 😕

**Comment by KrauseFx** [comment]
Thanks for submitting this, super helpful 👍  We just prepared https://github.com/fastlane/fastlane/pull/8119 for this

**Comment by rhcpfan** [comment]
Awesome! Glad I could help 😉
