### ISSUE TITLE
ERROR ITMS-90596: "Invalid Bundle...."

### ISSUE THREAD

**Issue by szmokus** [fastlane/fastlane#8114]
### Issue Description

I getting this error when trying to upload the build to iTunes Connect. Using "fastlane pilot upload --skip_submission true --skip_waiting_for_build_processing true" command

`ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/.../Watch/.../Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."`

I use a non-beta version of Xcode and I can upload the very same build with the Application Loader.

Any suggestions?
### Environment

'<details><summary>🚫 fastlane environment 🚫</summary>
### Stack
| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.5                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.7.4 (Apple Git-66)            |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.5 (15F34)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.3.1                                       |
### System Locale
| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |
### fastlane files:
**No Fastfile found**
**No Appfile found**
### fastlane gems
| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.13.0  | 🚫 Update available |
### Loaded fastlane plugins:
**No plugins Loaded**
<details><summary><b>Loaded gems</b></summary>
| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.19       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.0       |
| io-console                | 0.4.5        |
</details>
*generated on:* **2017-02-07**
</details>'

**Comment by croccio** [comment]
get same error

**Comment by szmokus** [comment]
Oh I see that agent is using XCode 7, could that be the problem? The project was built on an agent that uses XCode 8.

**Comment by croccio** [comment]
how can I verify that? I make it with Xcode 7.3.1 and organizer and loader tell me that message

**Comment by hjanuschka** [comment]
i am not sure if it is still supported to use 7.3.1 to submit - when using extensions like watchapp.

if you are using gym, be sure to set `use_legacy_build_api` to false (if using extensions you have to disable it)
