### ISSUE TITLE
Generialize Fastlane Match

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#8115]
I have certificates I use for AWS etc, I would love to somehow use some of the technology Match uses to encrypt these generic certificates into a repository.

**Comment by hjanuschka** [comment]
@jcampbell05  that has been requested a couple of times, but _match_'s purpos is and will stay focused on prof.provs and certs. however (as i am too in the need of a that) - i started - https://github.com/hjanuschka/fastlane-plugin-cryptex - which is kinda ripoff of matchs core tech. supporting all kinds of files, and ENVS - let me know if this helps you.

**Comment by jcampbell05** [comment]
@hjanuschka Awesome is that stand alone ?

**Comment by KrauseFx** [comment]
Yeah, so this shouldn't be part of _match_. _match_ is optimized for one use case, and it does it well 👍 Try using @hjanuschka's library instead :)
