### ISSUE TITLE
Docs - Clarify nuke

### ISSUE THREAD

**Issue by jacobjennings** [fastlane/fastlane#8120]
I have several app_identifiers in the same certificate repo. Does nuke affect all of them? Will I be prompted with the list for both development and distribution nukes?

**Comment by KrauseFx** [comment]
`nuke` will nuke all of them, before it actually nukes things, you'll have a chance to see a list of things that revoked with more information.

**Comment by ohayon** [comment]
Closing this issue for now. Feel free to continue conversation and we can definitely reopen it if necessary! 🐙 💯
