### ISSUE TITLE
Add `configuration` option to `carthage` Action

### ISSUE THREAD

**Issue by adcooley** [fastlane/fastlane#813]
By default carthage bootstrap uses the Release configuration, but in some scenarios it's helpful to switch that. See https://github.com/Carthage/Carthage/issues/281 and comment by @jspahrsummers "You could also pass --configuration Debug to Carthage, to select the Debug codesigning settings."

**Comment by KrauseFx** [comment]
Sure, feel free to add the option here: https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/carthage.rb

**Comment by ohwutup** [comment]
@adcooley that PR from @uny should take care of the issue! Please feel free to reopen this issue if necessary!
