### ISSUE TITLE
Cannot update PRODUCT_BUNDLE_IDENTIFIER Xcode 8

### ISSUE THREAD

**Issue by Parkarar** [fastlane/fastlane#8132]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello,

I'm having an issue when trying to update build settings PRODUCT_BUNDLE_IDENTIFIER to one of my targets in my xCode project (I have multiple targets). I'm running the fastlane command update_app_identifier. Unfortunately I'm getting an error. I observed that update_app_identifier command does not have a param for specifying the target, or does it? Bellow I will describe the command and the error I get. Also I am using xCode 8. I would like some help please. Maybe I'm doing something wrong. Can you help me please or guide me for another solution? 

Thank you very much.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

command: 

update_app_identifier(
plist_path: '/xxx/xxx.plist',
xcodeproj: 'path_to_my_project/xxx.xcodeproj',
app_identifier: 'com.xxx.ExampleApp'
)

Error: Xcodeproj doesn't have configuration with info plist /xxx/xxx.plist

**Comment by mgrebenets** [comment]
@Parkarar 

Sorry for asking obvious things, but is `/xxx/xxx.plist` part of your Xcode project?
Also, I'm not sure if relative path should start with `/`. Starting path with `/` would make it absolute path starting at root. Maybe it should be `xxx/xxx.plist`.

You can always run the command directly to see if it works from command line.
For example, this command worked for me with latest `2.14.2` fastlane version:

```
bundle exec fastlane run update_app_identifier xcodeproj:MyProject.xcodeproj plist_path:Sources/Info.plist app_identifier:new_bundle_id
```

**Comment by Parkarar** [comment]
Hello @mgrebenets . Thank you for your help. I've tried again after removing the '/' and use the plist path as xxx/xxx/plist, but I'm getting the same error. Can you give me an example please of how are you using this command to change the PRODUCT_BUNDLE_IDENTIFIER?

**Comment by Parkarar** [comment]
Finally solved the problem. I don't know how (maybe I've made some changes in the past and forgot), the plist path in build settings was not set related to the project, but to my root. So it wasn't set correct. I've changed the info plist path in build settings and now all works.
