### ISSUE TITLE
Scan: Collecting System Logs fail on circle ci

### ISSUE THREAD

**Issue by acicartagena** [fastlane/fastlane#8136]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Scan test Succeeded but, Collecting system logs fail on circle ci

```
/opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1366:in `mkdir': [!] No such file or directory @ dir_s_mkdir - ./fastlane/test_output/system_logs-iPhone 7_iOS_10.1.logarchive (Errno::ENOENT)
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1366:in `copy'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /opt/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/device_manager.rb:208:in `copy_logarchive'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/scan/lib/scan/runner.rb:101:in `block in copy_simulator_logs'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/scan/lib/scan/runner.rb:99:in `each'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/scan/lib/scan/runner.rb:99:in `copy_simulator_logs'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/scan/lib/scan/runner.rb:82:in `handle_results'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/scan/lib/scan/runner.rb:9:in `run'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/scan/lib/scan/manager.rb:14:in `work'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/actions/scan.rb:21:in `run'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:239:in `block (2 levels) in execute_action'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:217:in `block in execute_action'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:213:in `chdir'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:213:in `execute_action'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:135:in `trigger_action_by_name'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:33:in `block (2 levels) in parsing_binding'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/cli_tools_distributor.rb:59:in `take_off'
	from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.14.2/bin/fastlane:15:in `<top (required)>'
	from /opt/rubies/ruby-2.3.1/bin/fastlane:23:in `load'
	from /opt/rubies/ruby-2.3.1/bin/fastlane:23:in `<main>'

fastlane test returned exit code 1
```

Fastlane version 2.14.2
```
|                                     Summary for scan 2.14.2                                      |
+------------------------+-------------------------------------------------------------------------+
| slack_only_on_failure  | true                                                                    |
| scheme                 | AirtaskerDEV                                                            |
| output_types           | junit,html                                                              |
| device                 | iPhone 7 (10.1)                                                         |
| workspace              | ./Airtasker.xcworkspace                                                 |
| derived_data_path      | /Users/distiller/Library/Developer/Xcode/DerivedData/Airtasker-ejugj... |
| clean                  | false                                                                   |
| skip_build             | false                                                                   |
| output_directory       | ./fastlane/test_output                                                  |
| buildlog_path          | /tmp/circle-artifacts.etpn7Z4/scan                                      |
| include_simulator_logs | true                                                                    |
| open_report            | false                                                                   |
| skip_slack             | false                                                                   |
| use_clang_report_name  | false                                                                   |
| fail_build             | true                                                                    |
| xcode_path             | /Applications/Xcode-8.1.app     
```

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.11.6                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.2                              |
| Installation Source | /opt/rubies/ruby-2.3.1/bin/fastlane             |
| Host                | Mac OS X 10.11.6 (15G1108)                      |
| Ruby Lib Dir        | /opt/rubies/ruby-2.3.1/lib                      |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained        | false                                           |
| Is homebrew         | false                                           |
| Xcode Path          | /Applications/Xcode-8.1.app/Contents/Developer/ |
| Xcode Version       | 8.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| faraday                   | 0.10.0       |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| plist                     | 3.2.0        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-02-05**
</details>

**Comment by acicartagena** [comment]
fastlane env:
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                           |
| ------------------- | ----------------------------------------------- |
| OS                  | 10.11.6                                         |
| Ruby                | 2.3.1                                           |
| Bundler?            | false                                           |
| Git                 | git version 2.10.2                              |
| Installation Source | /opt/rubies/ruby-2.3.1/bin/fastlane             |
| Host                | Mac OS X 10.11.6 (15G1108)                      |
| Ruby Lib Dir        | /opt/rubies/ruby-2.3.1/lib                      |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained        | false                                           |
| Is homebrew         | false                                           |
| Xcode Path          | /Applications/Xcode-8.1.app/Contents/Developer/ |
| Xcode Version       | 8.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| faraday                   | 0.10.0       |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| plist                     | 3.2.0        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2017-02-05**
</details>

**Comment by hjanuschka** [comment]
@acicartagena we are working on a fix for that, this PR https://github.com/fastlane/fastlane/pull/8125 should adress it, it needs a little bit of work, but should be merged soon. as a workaround you could disable `include_simulator_logs`  until it is merged.


cc @DanToml @lyndsey-ferguson

**Comment by lyndsey-ferguson** [comment]
@hjanuschka do we close this once the fix is released?

**Comment by hjanuschka** [comment]
@lyndsey-ferguson yep - lets wait for the relase.

@acicartagena  #8125  has been merged

**Comment by lyndsey-ferguson** [comment]
@hjanuschka can we close this?

**Comment by DanToml** [comment]
Yep this is also out in a release now
