### ISSUE TITLE
Replace Open3 with FastlaneCore::CommandExecutor

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#8140]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`FastlaneCore::CommandExecutor` provides us more control and awareness over what is happening when calling shell commands. Several classes, such as `FastlaneCore::DeviceManager` still use `Open3`. It should be replaced (and the tests updated) to use `FastlaneCore::CommandExecutor`.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

N/A

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

N/A

**Comment by mfurtak** [comment]
I'm generally in favor of more consistency. However, In the past, we've struggled to understand and predict the possible impact of execution implementation changes like these.

How can we validate this swap without risking breaking people's setups?

**Comment by lyndsey-ferguson** [comment]
That is a good question. This kind of thing can be tricky. Unit tests may not be enough as in my experience, when I change shell commands, my tests can pass as I mocked responses that do not accurately reflect the real shell commands. 

That being said, if we do a 1-1 mapping and make sure that each and every code path is exercised in a real (non-test) situation, that may help prevent unexpected and unwanted surprises.

**Comment by KrauseFx** [comment]
I'm very much on the side of @mfurtak, everything around running commands has had side effects in the past, breaking some kinds of setups we didn't think about (e.g. Linux, Windows). Even though we don't support Windows for example, I'm pretty sure that there are people out there using some features on Windows with no issues.

**Comment by lyndsey-ferguson** [comment]
I fine with that too. Was looking for something to do and @hjanuschka and I discussed it [here|https://github.com/fastlane/fastlane/pull/8125#issuecomment-277703866]. Maybe going forward we should ask code to use `FastlaneCore::CommandExecutor`.

Any objection to closing this issue?
