### ISSUE TITLE
Feature Request: Gitter webhook integetration? 

### ISSUE THREAD

**Issue by rlam3** [fastlane/fastlane#8142]
Feature Request: Gitter webhook integetration? 

Similar to how we just add a line to integrate slack. Can we get integration for gitter? Thanks!

**Comment by ohayon** [comment]
Hey @rlam3! This is a great feature request. We would love to have support to notify more channels. This would be a great use case for [_fastlane_ plugins](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md)! 🐙
