### ISSUE TITLE
How to test locally when we have our own fast file importing fastlane file using import from git

### ISSUE THREAD

**Issue by sonnack** [fastlane/fastlane#8144]
We are trying to create our own fast file common that can be consumed by different product teams here.  Issue Example: Currently if we miss a parameter, we don't see the error until we actually run it in jenkins.  So our feedback loop is terrible.

I'm looking for a way to test our implementation locally.

**Comment by lacostej** [comment]
What prevents from testing it locally?

The way I do this in my project is to 
* pass most parameters using environment variables and dotenv
* each platform has a `before_all` block that checks for the required envs:
```ruby
platform :ios do
  before_all do
    check_env(keys: ['BUILD_PRODUCT_ID', 'BUILD_BUNDLE_ID',
                     'XCODE_VERSION', 'HOCKEY_API_TOKEN',
                     'FL_UNLOCK_KEYCHAIN_PASSWORD', 'MATCH_PASSWORD'])
```

The check_env is internal to our project. I could put it online but it's very basic.

* I also have a bunch of test lanes for troubleshooting/validation

* I have a `.env.CI` that simulates the CI setup (and isn't checked in) to simulate locally

**Comment by CubicNitrous** [comment]
@lacostej, what @sonnack  and I are doing is wrapping some Fastlane commands (say "scan") for example with our own method,  we do this to limit the number of things that are users are required to provide for example the itunes teamname is always the same, we always output to the same report directory, etc.

So we want to test that Fastlane gets called with the correct arguments by our function, but rspec isnt recognizing any of the fastlane commands.  

In production it works because we are using import_from_git to include our methods which call fastlane into the projects Fastfile so everything is "inline" and can call fastlane directly.

**Comment by sonnack** [comment]
@lacostej 
Thanks for the suggestion on using .env

I have one more question if we use .env files.

So we are building a fast file common project that all teams at our company will use.  We will call if Fast File Common.  Then we can have a dev team use this env file for their specific information (team name, app name, email) and their own fast file for custom methods.  Is there a way I can have a env in the same repo as fast file common instead of in every dev teams repo.

**Comment by lacostej** [comment]
@sonnack .env are not shared (the `import_from_git` only imports the `Fastfile` and actions right now). Until fastlane supports the feature you could hardcode it using the following mechanism

* store your .env files under your shared repor `fastlane/actions/shared/`
* these files will get cloned at fastlane start
* create an action in your shared repo that does something like
```ruby
      def self.run(params)
        env_file = File.join(File.expand_path("../shared", __FILE__), "shared.env")
        require 'dotenv'
        Dotenv.load(env_file) # or overload
     end
```
* add an action call at the start of your shared `Fastfile`. You will need fastlane 2.14.0 for this to work as there was a bug in < 2.14 WRT to properly loading actions and calling them from the shared fastfile.

Now this only works if the order in which you will load your dotenv works for you. You might need to add an extra mechanism to load your project dotenvs and not depend on fastlane `--env` parameter.

You could fetch your dotenv from elsewhere. I picked the git repo as this is where you already have your `Fastfile`

**Comment by lacostej** [comment]
@CubicNitrous it looks to me you are trying to write a wrapping `Fastfile` and test the wrapper in complete isolation of the imported Fastfile.

To achieve this I would probably mock all fastlane calls/functions/actions from my rspec helper.
