### ISSUE TITLE
screengrab example tests don't run 

### ISSUE THREAD

**Issue by mike011** [fastlane/fastlane#8148]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
1. Start emulator
2. Navigate to ./fastlane/screengrab/example/
3. ./gradlew connectedDebugAndroidTest

* What went wrong:
Execution failed for task ':example:connectedDebugAndroidTest'.

tools.fastlane.localetester.JUnit4StyleTests > testTakeMoreScreenshots[Nexus_4_API_23(AVD) - 6.0] FAILED
Test failed to run to completion. Reason: 'Test run failed to complete. Expected 2 tests, received 0'. Check device logcat for details
Tests on Nexus_4_API_23(AVD) - 6.0 failed: Test run failed to complete. Expected 2 tests, received 0
:example:connectedDebugAndroidTest FAILED

FAILURE: Build failed with an exception.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

:buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
\--- com.android.tools.build:gradle:2.2.3
     \--- com.android.tools.build:gradle-core:2.2.3
          +--- com.android.tools.build:builder:2.2.3
          |    +--- com.android.tools.build:builder-model:2.2.3
          |    |    \--- com.android.tools:annotations:25.2.3
          |    +--- com.android.tools.build:builder-test-api:2.2.3
          |    |    \--- com.android.tools.ddms:ddmlib:25.2.3
          |    |         +--- com.android.tools:common:25.2.3
          |    |         |    +--- com.android.tools:annotations:25.2.3
          |    |         |    \--- com.google.guava:guava:18.0
          |    |         \--- net.sf.kxml:kxml2:2.3.0
          |    +--- com.android.tools:sdklib:25.2.3
          |    |    +--- com.android.tools.layoutlib:layoutlib-api:25.2.3
          |    |    |    +--- com.android.tools:common:25.2.3 (*)
          |    |    |    +--- net.sf.kxml:kxml2:2.3.0
          |    |    |    +--- com.android.tools:annotations:25.2.3
          |    |    |    \--- com.intellij:annotations:12.0
          |    |    +--- com.android.tools:dvlib:25.2.3
          |    |    |    \--- com.android.tools:common:25.2.3 (*)
          |    |    +--- com.android.tools:repository:25.2.3
          |    |    |    +--- com.android.tools:common:25.2.3 (*)
          |    |    |    +--- org.apache.commons:commons-compress:1.8.1
          |    |    |    \--- com.google.jimfs:jimfs:1.1
          |    |    |         \--- com.google.guava:guava:18.0
          |    |    +--- com.google.code.gson:gson:2.2.4
          |    |    +--- org.apache.commons:commons-compress:1.8.1
          |    |    +--- org.apache.httpcomponents:httpclient:4.1.1
          |    |    |    +--- org.apache.httpcomponents:httpcore:4.1
          |    |    |    +--- commons-logging:commons-logging:1.1.1
          |    |    |    \--- commons-codec:commons-codec:1.4
          |    |    \--- org.apache.httpcomponents:httpmime:4.1
          |    |         +--- org.apache.httpcomponents:httpcore:4.1
          |    |         \--- commons-logging:commons-logging:1.1.1
          |    +--- com.android.tools:sdk-common:25.2.3
          |    |    +--- com.android.tools:sdklib:25.2.3 (*)
          |    |    +--- com.android.tools.build:builder-test-api:2.2.3 (*)
          |    |    +--- com.android.tools.build:builder-model:2.2.3 (*)
          |    |    +--- org.bouncycastle:bcpkix-jdk15on:1.48
          |    |    |    \--- org.bouncycastle:bcprov-jdk15on:1.48
          |    |    \--- org.bouncycastle:bcprov-jdk15on:1.48
          |    +--- com.android.tools:common:25.2.3 (*)
          |    +--- com.android.tools.build:manifest-merger:25.2.3
          |    |    +--- com.android.tools:common:25.2.3 (*)
          |    |    +--- com.android.tools:sdklib:25.2.3 (*)
          |    |    +--- com.android.tools:sdk-common:25.2.3 (*)
          |    |    +--- net.sf.kxml:kxml2:2.3.0
          |    |    \--- com.google.code.gson:gson:2.2.4
          |    +--- com.android.tools.ddms:ddmlib:25.2.3 (*)
          |    +--- com.android.tools.jack:jack-api:0.11.0
          |    +--- com.android.tools.jill:jill-api:0.10.0
          |    +--- com.android.tools.analytics-library:protos:25.2.3
          |    |    \--- com.google.protobuf:protobuf-java:2.5.0
          |    +--- com.android.tools.analytics-library:shared:25.2.3
          |    |    +--- com.android.tools.analytics-library:protos:25.2.3 (*)
          |    |    +--- com.android.tools:annotations:25.2.3
          |    |    +--- com.android.tools:common:25.2.3 (*)
          |    |    +--- com.google.guava:guava:17.0 -> 18.0
          |    |    \--- com.google.code.gson:gson:2.2.4
          |    +--- com.android.tools.analytics-library:tracker:25.2.3
          |    |    +--- com.android.tools:annotations:25.2.3
          |    |    +--- com.android.tools:common:25.2.3 (*)
          |    |    +--- com.android.tools.analytics-library:protos:25.2.3 (*)
          |    |    +--- com.android.tools.analytics-library:shared:25.2.3 (*)
          |    |    +--- com.google.protobuf:protobuf-java:2.5.0
          |    |    \--- com.google.guava:guava:17.0 -> 18.0
          |    +--- com.squareup:javawriter:2.5.0
          |    +--- org.bouncycastle:bcpkix-jdk15on:1.48 (*)
          |    +--- org.bouncycastle:bcprov-jdk15on:1.48
          |    +--- org.ow2.asm:asm:5.0.4
          |    \--- org.ow2.asm:asm-tree:5.0.4
          |         \--- org.ow2.asm:asm:5.0.4
          +--- com.android.tools.lint:lint:25.2.3
          |    +--- com.android.tools.lint:lint-checks:25.2.3
          |    |    +--- com.android.tools.lint:lint-api:25.2.3
          |    |    |    +--- com.android.tools:sdk-common:25.2.3 (*)
          |    |    |    +--- com.android.tools.build:builder-model:2.2.3 (*)
          |    |    |    +--- com.android.tools.external.lombok:lombok-ast:0.2.3
          |    |    |    |    \--- com.google.guava:guava:17.0 -> 18.0
          |    |    |    +--- com.android.tools.external.com-intellij:uast:145.597.4
          |    |    |    +--- org.ow2.asm:asm:5.0.4
          |    |    |    \--- org.ow2.asm:asm-tree:5.0.4 (*)
          |    |    \--- org.ow2.asm:asm-analysis:5.0.4
          |    |         \--- org.ow2.asm:asm-tree:5.0.4 (*)
          |    \--- org.eclipse.jdt.core.compiler:ecj:4.5.1
          +--- com.android.tools.build:transform-api:2.0.0-deprecated-use-gradle-api
          +--- com.android.tools.build:gradle-api:2.2.3
          |    +--- com.android.tools.build:builder-model:2.2.3 (*)
          |    \--- com.google.guava:guava:17.0 -> 18.0
          +--- com.android.databinding:compilerCommon:2.2.3
          |    +--- com.android.databinding:baseLibrary:2.2.3
          |    +--- org.antlr:antlr4:4.5.3
          |    +--- commons-io:commons-io:2.4
          |    +--- com.googlecode.juniversalchardet:juniversalchardet:1.0.3
          |    +--- com.google.guava:guava:17.0 -> 18.0
          |    \--- com.android.tools:annotations:24.5.0 -> 25.2.3
          +--- org.ow2.asm:asm:5.0.4
          +--- org.ow2.asm:asm-commons:5.0.4
          |    \--- org.ow2.asm:asm-tree:5.0.4 (*)
          +--- net.sf.proguard:proguard-gradle:5.2.1
          |    \--- net.sf.proguard:proguard-base:5.2.1
          +--- org.jacoco:org.jacoco.core:0.7.5.201505241946
          |    \--- org.ow2.asm:asm-debug-all:5.0.1
          +--- org.jacoco:org.jacoco.report:0.7.5.201505241946
          |    +--- org.jacoco:org.jacoco.core:0.7.5.201505241946 (*)
          |    \--- org.ow2.asm:asm-debug-all:5.0.1
          +--- net.sf.jopt-simple:jopt-simple:4.9
          +--- com.google.protobuf:protobuf-java:2.5.0
          \--- org.antlr:antlr:3.5.2
               +--- org.antlr:antlr-runtime:3.5.2
               \--- org.antlr:ST4:4.0.8
                    \--- org.antlr:antlr-runtime:3.5.2

(*) - dependencies omitted (listed previously)

**Comment by gersonmendes** [comment]
Hi @mike011,

Try this command:
`./gradlew assembleDebug assembleAndroidTest`

Instead of this:
`./gradlew connectedDebugAndroidTest `

**Comment by KrauseFx** [comment]
I'll close this issue for now due to inactivity. Please feel free to re-open or submit a new one if you have any more questions 👍
