### ISSUE TITLE
Crash, when app is not created.

### ISSUE THREAD

**Issue by skywinder** [fastlane/fastlane#815]
Since `produce` it's part of `fastlane` - it logcal, that fatlane should try to create app, if there is no exist yet in itunes connect.

Error: `12826a1d7e6a09a48f5d3bb95066f588`

**Comment by Rking788** [comment]
Which fastlane action is failing when an app doesn't exist? I think a few of them have that behavior. It could be scary to have fastlane create a new application for the user in iTunes Connect using produce whenever it assumes the user wanted one created. This seems like something that should be explicitly run by the user.

**Comment by skywinder** [comment]
@Rking788 I thought information about this stored in error file. Can't find it on my pc. Where is info about crashes stored locally?

**Comment by Rking788** [comment]
As far as i know it is uploaded, i think that is how most of the bugs are fixed. I am not a maintainer for the project so I don't have access to that data. I just meant if you wanted to share some of the error messages output to the terminal (after removing any sensitive/private information), maybe someone else would be able to help.

**Comment by skywinder** [comment]
@Rking788 you're right it's my fault. I will try to find out log and filll, which command it is.

**Comment by KrauseFx** [comment]
Actually the awesome @ohwutup is currently working on this: https://github.com/fastlane/fastlane/pull/981 :rocket:

**Comment by KrauseFx** [comment]
Very good feedback @skywinder :+1:

**Comment by KrauseFx** [comment]
Closing this for now, as we're bundling a new release fixing this right now :+1:
