### ISSUE TITLE
Pilot doesn't distribute new version to internal testers

### ISSUE THREAD

**Issue by negebauer** [fastlane/fastlane#8151]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Whenever I upload a new app version to iTunes Connect I have to go to the web and manually select the new version for internal testing
I would like pilot to automatically set the last version and build uploaded to internal testing

Searching for a way to do this I came across the command `fastlane pilot distribute` which does the trick **but** only for _external_ ([It's hardcoded](https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/commands_generator.rb#L67)) ([also the console log is hardcoded](https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L64))

I managed to distribute a new version by using it like this
```ruby
require 'pilot'
require 'fastlane_core'
lane :distribute do
    config = FastlaneCore::Configuration.create(Pilot::Options.available_options, {})
    config[:distribute_external] = false
    Pilot::BuildManager.new.distribute(config)
end
```

By using the above I'm able to make sure that the last upload gets delivered to internal testers, and thus I don't have to open iTunes Connect (which I'm currently forced to do)

It would be great if this could be done directly from a fastlane lane like
```ruby
pilot(distribute: true, distribute_external: false)
```

It appears like right now that when `distribute_external` is `false` new versions don't get distributed

### Steps to reproduce

Bump your app version and build number
Build with `gym` and upload with `pilot`
Check in iTunes Connect -> Testflight -> Internal Test
The new version isn't selected for testing
Run the lane `distribute` ☝️ 
Check in iTunes Connect -> Testflight -> Internal Test again
The new version is selected for testing

**Comment by negebauer** [comment]
I'll try it out soon

**Comment by KrauseFx** [comment]
_pilot_ currently only pushes for public testing as far as I know

**Comment by negebauer** [comment]
So this issue is still valid 😔

A little hack that I've used is executing the code mentioned above, specifically
```ruby
Pilot::BuildManager.new.distribute(config)
```
Which does distribute the build to internal testers

So it shouldn't be too difficult to add this has an option to the `pilot` command, right? 🤔

**Comment by KrauseFx** [comment]
Yeah, sounds like a reasonable thing to do 👍 Do you want to submit a PR?

**Comment by negebauer** [comment]
@KrauseFx I would. But I currently have no idea where the pilot fastlane command is run 😅 
I'll try to do it thought 👍
