### ISSUE TITLE
Does pem --force have any effect on an existing certificate?

### ISSUE THREAD

**Issue by steveharman** [fastlane/fastlane#8156]
We need to migrate 50+ apps from our existing push server into oneSignal.  For that we need a .p12  for each app.

So I thought we could use`pem --force` to easily create new certificates in p12 format and  avoid having to manually fetch all the existing certificates from the Apple Developer Portal as .cer , take them into Keychain Access and export them out one by one in .P12 format.

For internal reasons we need to keep the _existing_ push server running, with the existing app certificates.   Will 'pem --force' have any negative impact on the existing certificates?  i.e; will it revoke them?

Hopefully it will just create an additional certificate we can take into oneSignal leaving the existing certificate untouched.

Thanks,

Steve

**Comment by gersonmendes** [comment]
Hi @steveharman

`pem --force` will create a new certificate. The `--force` option is necessary in case that you already have a valid certificate. Without `--force` option, Fastlane will check if you already have a valid (not expired) certificate, if you have Fastlane will not create a new one. So, if you need to create a new one, even if you already have a valid certificate, you can use `--force` option.

**Comment by jeff-jk** [comment]
Building off of what @gersonmendes said, Apple restricts you 2 certificates per App ID and Pem --force will throw an error if you already have two.

**Comment by craigajohnson** [comment]
In our workflow it would be useful if we could --force creation do push a download so we can collect the download and store it for immediate use. Only worry is if it would not delete any existing certs or if there was no way for us to automatically delete the previous cert. It's all fine and good for 1 app but anything we can do automatically when generating x branded apps would be good.

**Comment by KrauseFx** [comment]
> In our workflow it would be useful if we could --force creation do push a download so we can collect the download and store it for immediate use

That's not possible, as only you have the private key, which is needed to generate a pem file
