### ISSUE TITLE
ERROR 65: Your shell environment is not correctly configured

### ISSUE THREAD

**Issue by BroderickLee** [fastlane/fastlane#8157]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Captured Output
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/Lee/Documents/RRX/git/JDBApp/fastlane/Appfile'
- app_identifier: 'com.renrenxing.JDBEnterprise'
- apple_id: 'app@jdcapital.com'
- team_id: 'WKJT8YDY9M'
-------
DEBUG [2017-02-08 12:25:31.25]: Checking if there are any plugins that should be loaded...
ERROR [2017-02-08 12:25:31.27]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
INFO [2017-02-08 12:25:31.27]: -------------------------------------------------
INFO [2017-02-08 12:25:31.27]: --- Step: Verifying required fastlane version ---
INFO [2017-02-08 12:25:31.27]: -------------------------------------------------
INFO [2017-02-08 12:25:31.28]: Your fastlane version 2.13.0 matches the minimum requirement of 2.13.0  ✅
INFO [2017-02-08 12:25:31.28]: ------------------------------
INFO [2017-02-08 12:25:31.28]: --- Step: default_platform ---
INFO [2017-02-08 12:25:31.28]: ------------------------------
INFO [2017-02-08 12:25:31.28]: Welcome to fastlane! Here's what your app is setup to do:
+--------+----------------+----------------------------------------------------+
|                            Available lanes to run                            |
+--------+----------------+----------------------------------------------------+
| Number | Lane Name      | Description                                        |
+--------+----------------+----------------------------------------------------+
| 1      | ios test       | Runs all the tests                                 |
| 2      | ios beta       | Submit a new Beta Build to Apple TestFlight        |
|        |                | This will also make sure the profile is up to date |
| 3      | ios release    | Deploy a new version to the App Store              |
| 4      | ios enterprise |                                                    |
| 0      | cancel         | No selection, exit fastlane!                       |
+--------+----------------+----------------------------------------------------+
WARN [2017-02-08 12:25:31.29]: Which number would you like run?

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  ERROR 65: Your shell environment is not correctly configured
   https://github.com/fastlane/fastlane/issues/8157 [open] 2 💬
   11 minutes ago

➡️  Running fastlane on Bitrise - non-interactive mode
   https://github.com/fastlane/fastlane/issues/5867 [closed] 5 💬
   06 Dec 2016

➡️  Support auto generation of Safari Web Push Certificates?
   https://github.com/fastlane/fastlane/issues/8045 [open] 0 💬
   a week ago

and 13 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

#######################################################################
# fastlane 2.14.2 is available. You are on 2.13.0.
# It is recommended to use the latest version.
# Please update using `fastlane update_fastlane`.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

2.14.2 Colored bugfix
- Fixed a regression when upgrading to the `colored2` gem
- Fixed `fastlane match nuke distribution` not detecting the certificate type
- Add support for percantages in _frameit_
- Fix _scan_ bug when providing the `xctestrun` parameter

2.14.1 Bugfixes
- Fix an issue with running _fastlane_ on old versions of Ruby
- Fix an issue with `.underline` which is used when printing out shell commands
- Improve keychain handling
- Improve test runner on CI

2.14.0 New spaceship features for InApp purchases and Developer Portal user management and more
**New features**:

- _spaceship_: Add support for managing In-App purchases (#7834)
- _spaceship_: Add Developer Portal user management (#8047)
- _match_: Officially add support for enterprise In-House profiles and certificates
- _scan_: support for test-without-building, build-for-testing, and xctestrun (#7130)
- _sigh_ and _spaceship_: Add tvOS support (#7815)
- _fastlane_: Add attachment support to `mailgun` action (#8044)
- _snapshot_ and _scan_: logarchive extraction (#8033)

**Improvements**
- _spaceship_: Fix issue with case sensitive bundle identifiers (#8068)
- _spaceship_: Allow our custom Spaceship::Base#inspect to work with object graphes containing circular references (#8019)
- _frameit_: Added font_scale_factor as a fraction of the screen width (#8034)
- _sigh_: download_all name file using profile UUID instead of application bundle identifier (#8082)
- Allow xcargs to accept Hash & Array, auto-converted to a shell-escaped String (#8051)
- Switch from unmaintained colored to maintained colored2 (#8028)
- Improved documentation for all tools
- local actions should be imported before their Fastfile otherwise importing the Fastfile might fail (#8080)

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `fastlane update_fastlane`

ERROR [2017-02-08 12:25:47.25]: RubyGems is not listed as your Gem source
ERROR [2017-02-08 12:25:47.25]: You can run `gem sources` to see all your sources
ERROR [2017-02-08 12:25:47.25]: Please run the following command to fix this:
INFO [2017-02-08 12:25:47.25]: $ gem sources --add https://rubygems.org


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.13.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "JDBClient") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "JDBClient") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want
  lane :enterprise do
    cert(output_path: ”build”)
    sigh(output_path: ”build”)
    gym
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.renrenxing.JDBEnterprise" # The bundle identifier of your app
apple_id "app@jdcapital.com" # Your Apple email address

team_id "WKJT8YDY9M"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.13.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-02-08**
</details>

```
** ARCHIVE FAILED **
[12:20:09]: Exit status: 65
[12:20:09]: Your shell environment is not correctly configured
[12:20:09]: Instead of UTF-8 your shell uses US-ASCII
[12:20:09]: Please add the following to your '~/.bashrc':
[12:20:09]: 
[12:20:09]:        export LANG=en_US.UTF-8
[12:20:09]:        export LANGUAGE=en_US.UTF-8
[12:20:09]:        export LC_ALL=en_US.UTF-8
[12:20:09]: 
[12:20:09]: You'll have to restart your shell session after updating the file.
[12:20:09]: If you are using zshell or another shell, make sure to edit the correct bash file.
[12:20:09]: For more information visit this stackoverflow answer:
[12:20:09]: https://stackoverflow.com/a/17031697/445598

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.13.0                  |
| sdk         | iPhoneOS10.2.sdk        |
+-------------+-------------------------+
```

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.13.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "JDBClient") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "JDBClient") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want
  lane :enterprise do
    cert(output_path: ”build”)
    sigh(output_path: ”build”)
    gym
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.renrenxing.JDBEnterprise" # The bundle identifier of your app
apple_id "app@jdcapital.com" # Your Apple email address

team_id "WKJT8YDY9M"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.13.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-02-08**
</details>

**Comment by LeeY0510** [comment]
The error is generated by Fastlane gym. However, it is working when it's built by xcodebuild command, as follows,

xcodebuild archive -scheme [APP_NAME] -workspace [APP_NAME].xcworkspace -configuration Enterprise -archivePath build/[APP_NAME].xcarchive | xcpretty -s
xcodebuild -exportArchive -archivePath build/[APP_NAME].xcarchive \
-exportPath build/[APP_NAME].ipa \
-exportFormat ipa \
-exportSigningIdentity "iPhone Distribution: xxx Co., Ltd."

Best Regards.

**Comment by LeeY0510** [comment]
Here is Gymfile details when i use fastlane gym.
```

# For more information about this configuration visit
# https://github.com/fastlane/fastlane/tree/master/gym#gymfile

# In general, you can use the options available
# fastlane gym --help

# Remove the # in front of the line to enable the option
disable_xcpretty true
clean true
scheme "JDBClient"
configuration "Enterprise"
archive_path "build/JDBClient.xcarchive"
output_directory "./build"
export_method "enterprise"
~                                                                                                                                                                                  
~                              
```

**Comment by mgrebenets** [comment]
The error message seems to be very straightforward: "No Fastfile found" and
"No Appfile found".

Could you double check if fastlane integration is properly set? Are those
files committed to fit? If u run on CI server, are those present in the got
checkout directory?

**Comment by KrauseFx** [comment]
There seems to be many errors with your setup. Wrong enconding which you can fix as instructed, do you have a Gemfile? If so it's missing the RubyGems.org source and other things that shouldn't happen. Are you based in China? Do you have access to RubyGems.org?

**Comment by LeeY0510** [comment]
Thanks @mgrebenets. Yes, I'm running on CI server, and update all my fastlane environment. However, the error still occurs, and for now, it will fail once for serval times. @KrauseFx @mgamer 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.0                          |
| Installation Source | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  # You can define as many lanes as you want
  lane :enterprise do |options|
    xcode_select "/Applications/Xcode.app"

    # Update JDBClient info plist
    update_info_plist(
      plist_path: "JDBClient/info.plist",
      app_identifier: "com.renrenxing.JDBEnterprise",
      display_name: "借贷宝" + options[:build_number]
    )

    # Update JDBClient Extension info plist
    update_info_plist(
      plist_path: "JDBClientExtension/info.plist",
      app_identifier: "com.renrenxing.JDBEnterprise",
      display_name: "借贷宝" + options[:build_number]
    )

    # Change version_number
    increment_version_number(version_number: options[:version_number])

    # Change build_number
    increment_build_number(build_number: options[:build_number])    

    # 证书
    cert(output_path: "build")

    # 签名
    sigh(output_path: "build")

    #编译
    gym(  
      use_legacy_build_api: true,
      disable_xcpretty: true,
      clean: true,
      scheme: "JDBClient",
      configuration: "Enterprise",
      output_directory: "./build",
      export_method: "enterprise"
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.renrenxing.JDBEnterprise" # The bundle identifier of your app
apple_id "app@jdcapital.com" # Your Apple email address

team_id "WKJT8YDY9M"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.3       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-02-10**
</details>

@KrauseFx Thank you for your reply. I'm sure I have access to RubyGems.org. Here is my Gemfile below.
```
if RUBY_VERSION =~ /2.3/
  Encoding.default_external = Encoding::UTF_8
  Encoding.default_internal = Encoding::UTF_8
end

source "https://rubygems.org"

gem "fastlane"
```

and I paste my fastlanefile below.

```
# You can define as many lanes as you want
  lane :enterprise do |options|
    xcode_select "/Applications/Xcode.app"

    # Update [APP_NAME] info plist
    update_info_plist(
      plist_path: "[APP_NAME]/info.plist",
      app_identifier: "com.xxx.JDBEnterprise",
      display_name: "[APP_NAME]" + options[:build_number]
    )

    # Update JDBClient Extension info plist
    update_info_plist(
      plist_path: "[APP_NAME]tExtension/info.plist",
      app_identifier: "com.xxx.JDBEnterprise",
      display_name: "[APP_NAME]" + options[:build_number]
    )

    # Change version_number
    increment_version_number(version_number: options[:version_number])

    # Change build_number
    increment_build_number(build_number: options[:build_number])

    # cer
    cert(output_path: "build")

    # sigh
    sigh(output_path: "build")

    # compile
    gym(
      use_legacy_build_api: true,
      disable_xcpretty: true,
      clean: true,
      scheme: "[APP_NAME]",
      configuration: "Enterprise",
      output_directory: "./build",
      export_method: "enterprise"
    )
  end
```

More error details

```
** ARCHIVE FAILED **
[18:05:35]: [31mExit status: 65[0m
[18:05:35]: [31mYour shell environment is not correctly configured[0m
[18:05:35]: [31mInstead of UTF-8 your shell uses US-ASCII[0m
[18:05:35]: [31mPlease add the following to your '~/.bashrc':[0m
[18:05:35]: [31m[0m
[18:05:35]: [31m       export LANG=en_US.UTF-8[0m
[18:05:35]: [31m       export LANGUAGE=en_US.UTF-8[0m
[18:05:35]: [31m       export LC_ALL=en_US.UTF-8[0m
[18:05:35]: [31m[0m
[18:05:35]: [31mYou'll have to restart your shell session after updating the file.[0m
[18:05:35]: [31mIf you are using zshell or another shell, make sure to edit the correct bash file.[0m
[18:05:35]: [31mFor more information visit this stackoverflow answer:[0m
[18:05:35]: [31mhttps://stackoverflow.com/a/17031697/445598[0m

+-------------+-------------------------+
|           [32m[33mBuild environment[0m[0m           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.14.2                  |
| sdk         | iPhoneOS10.0.sdk        |
+-------------+-------------------------+

+---------------------+----------------------------------------------------------------------------+
|                                           [33mLane Context[0m                                           |
+---------------------+----------------------------------------------------------------------------+
| DEFAULT_PLATFORM    | ios                                                                        |
| PLATFORM_NAME       | ios                                                                        |
| LANE_NAME           | ios enterprise                                                             |
| VERSION_NUMBER      | 2.8.1                                                                      |
| BUILD_NUMBER        | There does not seem to be a CURRENT_PROJECT_VERSION key set for this pr... |
| CERT_FILE_PATH      | /Users/charlotte/Jenkins-jdb-dev/workspace/iOS_CI_Ad-hoc/build/TY6BB4GE... |
| CERT_CERTIFICATE_ID | TY6BB4GE2Q                                                                 |
| SIGH_PROFILE_PATH   | /Users/charlotte/Jenkins-jdb-dev/workspace/iOS_CI_Ad-hoc/build/InHouse_... |
| SIGH_PROFILE_PATHS  | ["/Users/charlotte/Jenkins-jdb-dev/workspace/iOS_CI_Ad-hoc/build/InHous... |
| SIGH_UDID           | 8ee98b61-8d4b-4345-81ff-66ec8d1d5f58                                       |
| SIGH_UUID           | 8ee98b61-8d4b-4345-81ff-66ec8d1d5f58                                       |
| SIGH_PROFILE_TYPE   | enterprise                                                                 |
+---------------------+----------------------------------------------------------------------------+
[18:05:35]: [31mError building the application - see the log above[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | xcode_select                        | 0           |
| 4    | update_info_plist                   | 0           |
| 5    | update_info_plist                   | 0           |
| 6    | increment_version_number            | 0           |
| 7    | increment_build_number              | 0           |
| 8    | cert                                | 13          |
| 9    | sigh                                | 20          |
| 💥   | [31mgym[0m                                 | 340         |
+------+-------------------------------------+-------------+

[18:05:35]: [31mfastlane finished with errors[0m
[31m
[!] Error building the application - see the log above[0m
Process leaked file descriptors. See http://wiki.jenkins-ci.org/display/JENKINS/Spawning+processes+from+build for more information
Build step 'Execute shell' marked build as failure
Archiving artifacts
Finished: FAILURE
```

Any help will be appreciated. Thanks.

**Comment by KrauseFx** [comment]
What CI do you use? 

```
[18:05:35]: �[31mPlease add the following to your '~/.bashrc':�[0m
[18:05:35]: �[31m�[0m
[18:05:35]: �[31m       export LANG=en_US.UTF-8�[0m
[18:05:35]: �[31m       export LANGUAGE=en_US.UTF-8�[0m
[18:05:35]: �[31m       export LC_ALL=en_US.UTF-8�[0m
[18:05:35]: �[31m�[0m
[18:05:35]: �[31mYou'll have to restart your shell session after updating the file.�[0m
```

Have you tried that? Have you tried adding the 3 lines as your build step on your CI?

**Comment by BroderickLee** [comment]
@KrauseFx JENKINS CI. Yeah, I've tried. 
![9fac24fd-9a60-49f3-a1eb-e04a8700ef87](https://cloud.githubusercontent.com/assets/12880532/22874012/a3a3f15c-f1fe-11e6-8b4b-ee0f79e8a61d.png)

I don't know why the error #65 often occurs. And sometimes it also succeeds.
When I use xcodebuild command, it always succeeds without any failure. So can I use this one to replace the gym? 

Like this:
```
  lane :enterprise do |options|
    xcode_select "/Applications/Xcode.app"

    # Update JDBClient info plist
    update_info_plist(
      plist_path: "JDBClient/info.plist",
      app_identifier: "com.renrenxing.JDBEnterprise",
      display_name: "借贷宝" + options[:build_number]
    )

    # Update JDBClient Extension info plist
    update_info_plist(
      plist_path: "JDBClientExtension/info.plist",
      app_identifier: "com.renrenxing.JDBEnterprise",
      display_name: "借贷宝" + options[:build_number]
    )

    # Change version_number
    increment_version_number(version_number: options[:version_number])

    # Change build_number
    increment_build_number(build_number: options[:build_number])

    # cert
    cert

    # sign
    sigh

    # Compile
    xcodebuild(
        scheme="[APP_NAME]",
        configuration="Enterprise"
    )
  end
```

Waiting for ur reply. Thanks a lot for ur kind help!

**Comment by taisukeh** [comment]
The problem caused by Run script error, in my case.

**Comment by BroderickLee** [comment]
I've try to use xcodebuild command build, Thanks
