### ISSUE TITLE
Fastlane should be a layer on top of other libraries

### ISSUE THREAD

**Issue by Akekarat** [fastlane/fastlane#816]
Since Fastlane use so many libraries. It would be really nice that Fastlane wrap those libraries totally. 

For example, After Fastlane change to 'gym' after 'ipa', all users need to update Fastfile. This could break old setup. But if Fastlane has a wrapper layer on top of building tools, for example 'fastBuild'. Then users always use 'fastBuild' to build in their configuration. Fastlane can change 'ipa' to 'gym' or other build tools without break user's setup.

It would be really nice to have this feature on all tools. Then fastlane configuration file will be same most of the time.

**Comment by jcampbell05** [comment]
I think what would be better is if libraries could bundle Actions which fastlane could then detect. That was the gemspec can specify some basic libraries that do this to get started but the user can specify their own dependancies. So if the user wanted to use `ipa` and `ipa` included a fastlane action it could be used from fastlane if installed.

That said you can create actions that are stored in the folder in the project that fastlane can use, that way it will always be compatible, I not sure an abstraction like this would be great though

**Comment by KrauseFx** [comment]
`gym` and `ipa` are different tools with different options. The user can decide which one to use. Same for e.g. `crashlytics` and `hockey`: both actions do the same things, but require different inputs and parameters.

**Comment by ohwutup** [comment]
Hi everyone going to close this for now as something similar is going to be worked on per @KrauseFx's blog post today https://krausefx.com/blog/our-goal-to-unify-fastlane-tools.
