### ISSUE TITLE
Deliver and version detection

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#8161]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver looks to be grabing the app_version from the binary that is produced on previous steps and us it as parameter for submiting.

However, is not handling the fact that the ipa may contain a version that is inferior of the current version in itunesconnect.

In the affected app, i had already set it up to version 1.30 and the ipa that was produced was by mistake 1.25. However, instead of an error of mismatched app_versions, the version on the itunesconnect site was changed from 1.30 to 1.25 (which isn't what people will expect).

I would expect that if the current version on itunesconnect is > ipa version to get an error.
If they are the same, the upload is performed.
If itunesconnect version is < ipa version, and there isn't any "next" version, to create one with the same information as the last one, but with the build version as it is stated on the binary.
If itunesconnect version is < ipa version and it is already a "next" version, to generate an error stating that the version is too high for the expected one on itunesconnect.

What i was not expecting was the version to be changed to a number below the current one.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[...]
[xx:xx:xx]: Making sure the latest version on iTunes Connect matches '1.25' from the ipa file...
[xx:xx:xx] Successfully set the version to '1.25'
[...]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.1                          |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

#select xcode version
#xcversion(version: "8.1") # Selects Xcode 8.1.0

xcode_select "/Applications/Xcode.app"

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Create a new Alpha Build"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'xxxxx',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: 'xxxxx',
      use_legacy_build_api:true,
      configuration: 'Alpha',
      output_directory: './build',
      output_name: 'xxxxx-Alpha.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )
      
    # pilot
    hockey(
      api_token: 'xxxxx',
      public_identifier: 'xxxxx',
      ipa: 'build/xxxx-Alpha.ipa',
      notify: '1',
      status: '2',
      release_type: '2',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Create a new Beta Build"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'xxxxx',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: 'xxxxx',
      use_legacy_build_api:true,
      configuration: 'Beta',
      output_directory: './build',
      output_name: 'xxxxx-Beta.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )

    hockey(
      api_token: 'xxxxx',
      public_identifier: 'xxxxx',
      ipa: 'build/xxxxx-Beta.ipa',
      notify: '1',
      status: '2',
      release_type: '0',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )


    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

  end
 
  desc "Create a new Store Build"
  desc "This will also make sure the profile is up to date"
  lane :store do
    match(
      type: 'appstore',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'xxxxx',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    # snapshot

    gym(
      scheme: 'xxxxx',
      use_legacy_build_api:true,
      configuration: 'Store',
      output_directory: './build',
      output_name: 'xxxxx-Store.ipa',
      include_symbols:false,
      include_bitcode:false,
      silent:true
    )

    # deliver(force:true)
    deliver(
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      force: true,
      username: 'xxxxx'
    )

    # frameit

    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

    hockey(
      api_token: 'xxxxx',
      public_identifier:  'xxxxx',
      ipa: 'build/xxxxx-Store.ipa',
      notify: '1',
      status: '2',
      release_type: '1',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )


  end

  # You can define as many lanes as you want

  after_all do |lane|
    #hockey

    puts "All done successfully..."
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|

    puts "Error: " + exception.message

    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "xxxxx" # Your Apple email address
team_id "xxxxx"  # Developer Portal Team ID

for_lane :test do
    app_identifier 'xxxxx-alpha'
end

for_lane :alpha do
    app_identifier 'xxxxx-alpha'
end

for_lane :beta do
    app_identifier 'xxxxx-beta'
end

for_lane :store do
    app_identifier 'xxxxx'
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| plist                     | 3.2.0        |
| bundler                   | 1.14.3       |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-02-07**
</details>

**Comment by nolanwilson** [comment]
From my perspective this actually is what I would expect.

If I'm uploading an app at any version number, I want the App Store version number to be the same as what's baked into my IPA file (including if the app version I am submitting is lower than what currently exists in any pending state on iTunes.

Just to confirm, in your scenario version 1.30 is not live on the App Store correct? It is just a new version to be submitted to Apple that has not yet been submitted?

**Comment by ohayon** [comment]
Hey @lferro9000 👋 , I believe @nolanwilson is correct. Unless your app is live in the App Store and/or _I believe_ TestFlight, iTunesConnect will be able to change it to a lower version number. If it is already deployed to users however, I believe that iTunesConnect will behave as you are expecting.

Going to close this issue for now, but please feel free to continue conversation if you have any other issues. Thanks! 🐙
