### ISSUE TITLE
Including carthage debug symbols into final archive

### ISSUE THREAD

**Issue by ianbytchek** [fastlane/fastlane#8163]
I've a project with a bunch of framework dependencies managed with Carthage. After archiving the product all internal debug symbols for app and frameworks are included as expected, but Carthage ones are not. Whilst the behaviour is expected, it surely must be a common thing to do? Or not? I couldn't find a simple way doing this in Xcode, is there a way doing it with fastlane? 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.2                          |
| Installation Source | ~/.rubies/ruby-2.3.0/bin/fastlane           |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rubies/ruby-2.3.0/lib                    |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-02-07**
</details>

**Comment by hjanuschka** [comment]
@ianbytchek seems to be a problem with carthage itself. maybe this https://github.com/Carthage/Carthage/issues/507#issuecomment-121086252 comment helps.
not sure if this something fastlane could solve!

**Comment by ianbytchek** [comment]
@hjanuschka I've been pointed in the right direction, thanks for the clue!
