### ISSUE TITLE
pilot report repeat messages "New application; waiting for build train to appear on iTunes Connect"

### ISSUE THREAD

**Issue by diaojunxian** [fastlane/fastlane#8168]
Now can I ask you a question about `pilot`?
As I usually try the commands and it worked well，but after I update fastlane to 2.14.2,it told this and repeat `New application; waiting for build train to appear on iTunes Connect`:
```
 Successfully uploaded the new binary to iTunes Connect
INFO [2017-02-07 20:35:32.69]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
INFO [2017-02-07 20:35:32.69]: Waiting for iTunes Connect to process the new build
INFO [2017-02-07 20:36:05.05]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:36:36.97]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:37:08.67]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:37:40.14]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:38:11.59]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:38:43.34]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:39:15.29]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:39:47.20]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:40:19.35]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:40:51.05]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:41:23.39]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:41:54.83]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:42:26.74]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:42:58.23]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:43:29.99]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:44:01.64]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:44:33.18]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:45:04.72]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:45:36.17]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:46:08.38]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:46:39.88]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:47:12.11]: New application; waiting for build train to appear on iTunes Connect
INFO [2017-02-07 20:47:43.54]: New application; waiting for build train to appear on iTunes Connect
```
and my commands is:
```
DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV" PILOT_WAIT_FOR_NEW_BUILD_TRAINS_ON_ITUNES_CONNECT=1 fastlane pilot upload --verbose --username ${username} --app_identifier ${bundle_id} --changelog ${changelog} -d ${beta_app_description} --ipa ${ipa_path} --distribute_external ${distribute_external} --apple_id ${apple_id} --team_id ${team_id} --team_name "${team_name}" --dev_portal_team_id ${dev_portal_team_id} --itc_provider "${itc_provider}" || exit
```
why it append?

**Comment by PetrosIchor** [comment]
I believe that's intentional to allow the user to know it's not stuck and still processing. When I run pilot the amount of times it repeats varies.  I always assumed it was related to my binary size, the load on iTC, or something else along those lines.

**Comment by dzunglht** [comment]
My team also encounter above issue ! Below is our fastlane env output:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Is homebrew         | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.17.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  #desc "Runs all the tests"
  #lane :test do
  #  scan
  #end

  desc "Submit a new Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    sigh
    increment_build_number(xcodeproj: 'QuantaWallet.xcworkspace') # Increment the build number
    gym(scheme: "QuantaWallet", project: 'QuantaWallet.xcworkspace') # Build the app
    pilot(skip_submission: true) # Upload the app to TestFlight
  end

  #desc "Submit a new Beta Build to Apple TestFlight"
  #desc "This will also make sure the profile is up to date"
  #lane :beta do
  #  # match(type: "appstore") # more information: https://codesigning.guide
  #  gym(scheme: "QuantaWallet") # Build your app - more options available
  #  pilot
  #
  #  # sh "your_script.sh"
  #  # You can also use other beta testing services here (run `fastlane actions`)
  #end

  #desc "Deploy a new version to the App Store"
  #lane :release do
  #  # match(type: "appstore")
  #  # snapshot
  #  gym(scheme: "QuantaWallet") # Build your app - more options available
  #  deliver(force: true)
  #  # frameit
  #end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "im.quanta.wallet" # The bundle identifier of your app
apple_id "ios_dev@quanta.im" # Your Apple email address

team_id "CT95N7NKQQ"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-02-20**
</details>

**Comment by cwRichardKim** [comment]
if anyone else is having this issue, it took 45mins for me to get a response and ended up with this error:

`[!]  (RuntimeError)
TestFlight requires you to provide the answer to the encryption question
to provide the reply, please add the following to your Info.plist file

<key>ITSAppUsesNonExemptEncryption</key><false/>

Afterwards re-build your app and try again
iTunes Connect reported: 'You must provide an answer for this question.'`

**Comment by PetrosIchor** [comment]
Do you have the encryption flag set in your plist file?  It'll reject if that's the case

**Comment by cwRichardKim** [comment]
yup! sorry I'll amend my comment, meant to just say that it takes a while. my 2mb app took 50 minutes the second time once I fixed the flag
