### ISSUE TITLE
Slather is not seeing default fastlane environment flags for derived data

### ISSUE THREAD

**Issue by beloso** [fastlane/fastlane#8174]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines] 🔑(https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am running the action `setup_jenkins` to setup my jenkins environment.
When running slather action, it is not seeing the proper derived that path.

##### Complete output when running fastlane, including the stack trace and command used

[12:22:07]: fastlane finished with errors

```ruby
[!] Exit status of command 'slather coverage --jenkins --cobertura-xml --scheme Debug' was 1 instead of 0.
Slathering...
/Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:177:in `profdata_coverage_dir': No coverage directory found. (StandardError)
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:410:in `block in find_binary_files'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:409:in `each'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:409:in `find_binary_files'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:344:in `configure_binary_file'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/project.rb:240:in `configure'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/lib/slather/command/coverage_command.rb:51:in `execute'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/slather-2.3.0/bin/slather:17:in `<top (required)>'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/slather:23:in `load'
	from /Users/cashyt/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/bin/slather:23:in `<main>'
No coverage directory found.

	Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
	Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
	If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.1                          |
| Installation Source | ~/.rbenv/versions/2.2.3/bin/fastlane        |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.2.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| json                      | 2.0.3        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-02-08**
</details>

**Comment by ohayon** [comment]
Hey @beloso, thanks for raising the issue. It is a bit unclear from the information that you provided what exactly the issue is. Could you share some more of your terminal output? And also, it would be helpful to see how you are invoking the tool with environment flags and/or where you are setting the _fastlane_ env flags. Thanks! 🐙

**Comment by beloso** [comment]
Hi, what I meant is that the slather action is not checking the environment flags setted up by the `setup_jenkins`. The action `setup_jenkins` sets up the the following variables:
```
DERIVED_DATA_PATH
FL_CARTHAGE_DERIVED_DATA
GYM_DERIVED_DATA_PATH
SCAN_DERIVED_DATA_PATH
XCODE_DERIVED_DATA_PATH
```
The slacker action reads the variable `FL_SLATHER_BUILD_DIRECTORY`.

It would be nice if either `setup_jenkins` configured the `FL_SLATHER_BUILD_DIRECTORY` as well as the others.

**Comment by ohayon** [comment]
Hey @beloso, I think in general we try to keep the actions as decoupled as possible from one another, so having `setup_jenkins` set a flag specifically for slather feels a bit like we are mixing actions too much. Would it be a feasible option for you to do something like the following in your `Fastfile`?

```
setup_jenkins
ENV['FL_SLATHER_BUILD_DIRECTORY'] = "path/to/build/directory"
slather
```

**Comment by beloso** [comment]
That was what I ended up doing. 

But since `setup_jenkins` sets up the flag for Carthage, which is third party, from fastlane's point of view. I thought it might be nice if the configuration for `slather` to be also handled by `setup_jenkins`.

If you want to keep thinks decoupled it's okay I guess. I've managed to work around the "problem" (or not really a problem).

**Comment by ohayon** [comment]
Yeah, thanks for the understanding @beloso, I'm not sure how that carthage flag snuck in there, but we should work to minimize that type of overlap I think.

Let us know if you are having any more issues! 😄 🐙 🚀
