### ISSUE TITLE
Rename steps?

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#818]
Is there a way for providing custom, context-aware names for steps?

For example, I have a lane that calls `xcbuild` 12 times. I'd like to have a better description on the summary (and on the log itself).

**Comment by KrauseFx** [comment]
Are you referring just to the summary table?

**Comment by marcelofabri** [comment]
The summary and the "titles":

```
[19:11:31]: ---------------------
[19:11:31]: --- Step: xcbuild ---
[19:11:31]: ---------------------
```

**Comment by KrauseFx** [comment]
You can change the name for your own action by overwriting a method.

**Comment by KrauseFx** [comment]
But not for your usecase.

**Comment by ohwutup** [comment]
Going to close this for now as its been a while since there was an chatter, please let us know if you still have any questions @marcelofabri ! :cactus:
