### ISSUE TITLE
feature request: (optional) AppStore meta (like app description, key words...) customization  

### ISSUE THREAD

**Issue by AlexandrTerentyev** [fastlane/fastlane#8181]
It would be great customize appstore meta for multiple target projects.
I think current behaviour must be default and meta can be modified in app file by using some condition. Something like this in Appfile:

if condition
   APP_DESCRIPTION = "..."
end

Or in fastfile, it doesn't matter

**Comment by KrauseFx** [comment]
You can do that
```ruby
lane :metadata do
  deliver(description: { "en-US" => "English description", "de-DE" => "German description" })
end
```
👍
