### ISSUE TITLE
undefined method `id' for nil:NilClass while fastlane sigh repair

### ISSUE THREAD

**Issue by skyline00** [fastlane/fastlane#8184]
### Issue Description
I'm trying to use fastlane sigh repair to repair expired profiles, but I encounter an error described below.

**COMMAND:**
`$ fastlane sigh repair -u *** -b ***`

**OUTPUT:**
```Starting login with user '***'
Successfully logged in
Going to repair 6 provisioning profiles
Repairing profile '***'...


/Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:408:in `map': [!] undefined method `id' for nil:NilClass (NoMethodError)
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:408:in `block in update!'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/spaceship/lib/spaceship/client.rb:386:in `with_retry'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:402:in `update!'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/spaceship/lib/spaceship/portal/provisioning_profile.rb:370:in `repair!'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/sigh/lib/sigh/repair.rb:24:in `block in repair_all'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/sigh/lib/sigh/repair.rb:22:in `each'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/sigh/lib/sigh/repair.rb:22:in `repair_all'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/sigh/lib/sigh/commands_generator.rb:76:in `block (2 levels) in run'
	from /Users/builder/.rvm/gems/ruby-2.2.4@global/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/builder/.rvm/gems/ruby-2.2.4@global/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/builder/.rvm/gems/ruby-2.2.4@global/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/builder/.rvm/gems/ruby-2.2.4@global/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/builder/.rvm/gems/ruby-2.2.4@global/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/sigh/lib/sigh/commands_generator.rb:119:in `run'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Users/builder/.rvm/gems/ruby-2.2.4/gems/fastlane-2.14.2/bin/fastlane:15:in `<top (required)>'
	from /Users/builder/.rvm/gems/ruby-2.2.4/bin/fastlane:22:in `load'
	from /Users/builder/.rvm/gems/ruby-2.2.4/bin/fastlane:22:in `<main>'
	from /Users/builder/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
	from /Users/builder/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
```

### ENVIRONMENT

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.2.4/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.4/lib                |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

| Gem                       | Version |
| ------------------------- | ------- |
| executable-hooks          | 1.3.2   |
| bundler-unload            | 1.0.2   |
| rubygems-bundler          | 1.4.4   |
| bundler                   | 1.14.3  |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| excon                     | 0.54.0  |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| multi_json                | 1.12.1  |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| i18n                      | 0.7.0   |
| json                      | 1.8.1   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| minitest                  | 5.10.1  |
| activesupport             | 4.2.7.1 |
| commander                 | 4.4.3   |
| rubyzip                   | 1.2.0   |
| plist                     | 3.2.0   |
| CFPropertyList            | 2.3.4   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| unicode-display_width     | 1.1.3   |
| terminal-table            | 1.7.3   |

**Comment by YissacharB** [comment]
i am getting the same issue

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.6.0                           |
| Installation Source | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.3       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| unicode-display_width     | 1.1.3        |
</details>


*generated on:* **2017-02-20**
</details>

**Comment by janbednar** [comment]
I am having the same problem

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.4                                       |
| Ruby                        | 2.3.1                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.7.4 (Apple Git-66)              |
| Installation Source         | /usr/local/bin/fastlane                       |
| Host                        | Mac OS X 10.12.4 (16E195)                     |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode_7.app/Contents/Developer/ |
| Xcode Version               | 7.3.1           - same happens with 8.3.2                           |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| json                      | 2.0.2        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.0        |
</details>


*generated on:* **2017-04-24**
</details>
