### ISSUE TITLE
Print message on last line

### ISSUE THREAD

**Issue by StevePotter** [fastlane/fastlane#8186]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have a situation where I'd like to provide instructions to the user after a lane has completed.  Currently I use `puts` but the message is hidden by the summary.  So nobody sees it.  This could be achieved by either hiding the summary or a custom message shown after the summary.  AFAIK this is not possible.  I'd be happy to submit a PR if you can let me know what option, if any, you'd prefer.  Thanks!

**Comment by KrauseFx** [comment]
What kind of message is it? Is it always the same one? You could do `fastlane beta && echo "Hi"`

**Comment by KrauseFx** [comment]
I'll close this issue for now
