### ISSUE TITLE
scan is not always reporting failure return code

### ISSUE THREAD

**Issue by garie** [fastlane/fastlane#8188]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a bamboo build which executes tests using fastlane's scan. I have two builds with identical test failures but different execution statuses. It looks like an error code is not being returned by scan, which causes the build to think it has succeeded.

### Environment

fastlane: 2.13.0
scan: 2.13.0

These are the versions from the builds that behaved poorly. I have since updated to the latest version, but I no longer have failing tests since they have been fixed. I did look at the commits between 2.13.0 and 2.14.2, which is the latest version, and do not see anything that looks like it would have touched this problem.

Build script:

```
bundle exec fastlane test --env development
bundle exec fastlane integration --env development
```

Fastfile:
```
	lane :test do
		scan(scheme: "UnitTests", custom_report_file_name: "junit_unittests.xml", skip_build: true)
	end
	
	lane :integration do
		scan(scheme: "UITests", custom_report_file_name: "junit_uitests.xml", skip_build: true)
	end
```

### Output

This build had the correct behavior, which is an error return code which caused the build to fail:

```
31-Jan-2017 09:57:15	         Executed 36 tests, with 13 failures (0 unexpected) in 13.830 (13.834) seconds
31-Jan-2017 09:57:15	Failing tests:
31-Jan-2017 09:57:15	-[MyTestClass testMyTest()]
...
31-Jan-2017 09:57:15	** TEST FAILED **
31-Jan-2017 09:57:15	[09:57:15]: Exit status: 65
31-Jan-2017 09:57:16	+--------------------+----+
31-Jan-2017 09:57:16	|      Test Results       |
31-Jan-2017 09:57:16	+--------------------+----+
31-Jan-2017 09:57:16	| Number of tests    | 25 |
31-Jan-2017 09:57:16	| Number of failures | 0  |
31-Jan-2017 09:57:16	+--------------------+----+
31-Jan-2017 09:57:16	
31-Jan-2017 09:57:18	[09:57:18]: Successfully generated report at '/Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/build/reports/junit_uitests.xml'
31-Jan-2017 09:57:18	+----------------------------+---------------------------------------------------------------------+
31-Jan-2017 09:57:18	|                                           Lane Context                                           |
31-Jan-2017 09:57:18	+----------------------------+---------------------------------------------------------------------+
31-Jan-2017 09:57:18	| DEFAULT_PLATFORM           | ios                                                                 |
31-Jan-2017 09:57:18	| ENVIRONMENT                | development                                                         |
31-Jan-2017 09:57:18	| PLATFORM_NAME              | ios                                                                 |
31-Jan-2017 09:57:18	| LANE_NAME                  | ios integration                                                     |
31-Jan-2017 09:57:18	| SCAN_DERIVED_DATA_PATH     | /Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/De... |
31-Jan-2017 09:57:18	| SCAN_GENERATED_PLIST_FILES | ["/Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/... |
31-Jan-2017 09:57:18	| SCAN_GENERATED_PLIST_FILE  | /Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/De... |
31-Jan-2017 09:57:18	+----------------------------+---------------------------------------------------------------------+
31-Jan-2017 09:57:18	[09:57:18]: Test execution failed. Exit status: 65
31-Jan-2017 09:57:18	
31-Jan-2017 09:57:18	+------+-------------------------------------+-------------+
31-Jan-2017 09:57:18	|                     fastlane summary                     |
31-Jan-2017 09:57:18	+------+-------------------------------------+-------------+
31-Jan-2017 09:57:18	| Step | Action                              | Time (in s) |
31-Jan-2017 09:57:18	+------+-------------------------------------+-------------+
31-Jan-2017 09:57:18	| 1    | Verifying required fastlane version | 0           |
31-Jan-2017 09:57:18	| 2    | xcversion                           | 0           |
31-Jan-2017 09:57:18	| 3    | xcode_select                        | 0           |
31-Jan-2017 09:57:18	| 4    | default_platform                    | 0           |
31-Jan-2017 09:57:18	| ?   | scan                                | 737         |
31-Jan-2017 09:57:18	+------+-------------------------------------+-------------+
31-Jan-2017 09:57:18	
31-Jan-2017 09:57:18	[09:57:18]: fastlane finished with errors
31-Jan-2017 09:57:18	
31-Jan-2017 09:57:18	[!] Test execution failed. Exit status: 65
31-Jan-2017 09:57:19	Failing task since return code of [/bin/sh /Users/ops/bamboo-agent-home/temp/COM-PROJ-JOB1-271-ScriptBuildTask-4487576631677732088.sh] was 1 while expected 0
31-Jan-2017 09:57:19	Finished task 'test app' with result: Failed
```

This build had identical source code, identical build scripts, identical version dependencies, and the same failures, but "succeeded":

```
30-Jan-2017 13:54:31	         Executed 36 tests, with 13 failures (0 unexpected) in 14.307 (14.311) seconds
30-Jan-2017 13:54:31	Failing tests:
30-Jan-2017 13:54:31	-[MyTestClass testMyTest()]
30-Jan-2017 13:54:31	** TEST FAILED **
30-Jan-2017 13:54:31	[13:54:31]: Exit status: 65
30-Jan-2017 13:54:32	+--------------------+----+
30-Jan-2017 13:54:32	|      Test Results       |
30-Jan-2017 13:54:32	+--------------------+----+
30-Jan-2017 13:54:32	| Number of tests    | 25 |
30-Jan-2017 13:54:32	| Number of failures | 0  |
30-Jan-2017 13:54:32	+--------------------+----+
30-Jan-2017 13:54:32	
30-Jan-2017 13:54:34	[13:54:34]: Successfully generated report at '/Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/build/reports/junit_uitests.xml'
30-Jan-2017 13:54:35	+----------------------------+---------------------------------------------------------------------+
30-Jan-2017 13:54:35	|                                           Lane Context                                           |
30-Jan-2017 13:54:35	+----------------------------+---------------------------------------------------------------------+
30-Jan-2017 13:54:35	| DEFAULT_PLATFORM           | ios                                                                 |
30-Jan-2017 13:54:35	| ENVIRONMENT                | development                                                         |
30-Jan-2017 13:54:35	| PLATFORM_NAME              | ios                                                                 |
30-Jan-2017 13:54:35	| LANE_NAME                  | ios integration                                                     |
30-Jan-2017 13:54:35	| SCAN_DERIVED_DATA_PATH     | /Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/De... |
30-Jan-2017 13:54:35	| SCAN_GENERATED_PLIST_FILES | ["/Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/... |
30-Jan-2017 13:54:35	| SCAN_GENERATED_PLIST_FILE  | /Users/ops/bamboo-agent-home/xml-data/build-dir/COM-PROJ-JOB1/De... |
30-Jan-2017 13:54:35	+----------------------------+---------------------------------------------------------------------+
30-Jan-2017 13:54:35	[13:54:35]: Test execution failed. Exit status: 65
30-Jan-2017 13:54:35	
30-Jan-2017 13:54:35	+------+-------------------------------------+-------------+
30-Jan-2017 13:54:35	|                     fastlane summary                     |
30-Jan-2017 13:54:35	+------+-------------------------------------+-------------+
30-Jan-2017 13:54:35	| Step | Action                              | Time (in s) |
30-Jan-2017 13:54:35	+------+-------------------------------------+-------------+
30-Jan-2017 13:54:35	| 1    | Verifying required fastlane version | 0           |
30-Jan-2017 13:54:35	| 2    | xcversion                           | 0           |
30-Jan-2017 13:54:35	| 3    | xcode_select                        | 0           |
30-Jan-2017 13:54:35	| 4    | default_platform                    | 0           |
30-Jan-2017 13:54:35	| ?   | scan                                | 735         |
30-Jan-2017 13:54:35	+------+-------------------------------------+-------------+
30-Jan-2017 13:54:35	
30-Jan-2017 13:54:35	[13:54:35]: fastlane finished with errors
30-Jan-2017 13:54:35	
30-Jan-2017 13:54:35	[!] Test execution failed. Exit status: 65
30-Jan-2017 13:55:05	Finished task 'test app' with result: Success
```

**Comment by garie** [comment]
I included the relevant information, but fine.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.8.4 (Apple Git-73)            |
| Installation Source | ~/.gem/ruby/2.3.0/bin/fastlane              |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.0                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :ios

platform :ios do
	before_all do
	end
	
	desc "Installs FixCode which disables the \"Fix Issue\" button in Xcode"
	lane :xcode do
		install_xcode_plugin(
			url: "https://github.com/fastlane/FixCode/releases/download/0.5.0/FixCode.xcplugin.zip"
		)
	end
	
	desc "Runs unit tests"
	lane :test do
	
		scan(scheme: "UnitTests", custom_report_file_name: "junit_unittests.xml", skip_build: true)		#uses defaults from GymFile
		
	end
	
	desc "Run Integration tests"
	lane :integration do
	
		scan(scheme: "UITests", custom_report_file_name: "junit_uitests.xml", skip_build: true)
			
	end
	
	private_lane :build_dependencies do
	
		carthage(command: "bootstrap", # One of: build, bootstrap, update, archive. (default: bootstrap)
			verbose: false,
			platform: "iOS",	
			configuration: "Release")
			
	end
	
	desc "Update the plist files for the continuous integration environment"
	def update_plist_ci ( options )
	
		# Xcode versions to prevent warnings on build machine.
		xcversion(version: "8.0") # Selects Xcode 8.0.0
		xcode_select "/Applications/Xcode.app"

		# Update plist values
		build_number = options[:build_number] || get_build_number
		increment_build_number(
			build_number: build_number
		)
		set_info_plist_value( # Change the Display Name of your app
			path: "MyApp/Info.plist",
			key: "CFBundleDisplayName",
			value: ENV["BUNDLE_DISPLAY_NAME"]
		)
		set_info_plist_value( # Change the App Identifier of your app
			path: "MyApp/Info.plist",
			key: "CFBundleIdentifier",
			value: ENV["APP_IDENTIFIER"]
		)
	end
	
	desc "Build application"
	lane :build do |options|
		
		pre_build
		
		match(type: "development", app_identifier: ENV["APP_IDENTIFIER"])
		
		gym 		#uses defaults from GymFile
		
	end
	
	desc "pre build steps"
	lane :pre_build do
		build_dependencies
		swiftlint
	end
	
	desc "Build for the continuous integration environment"
	lane :build_ci_development do |options| 

		update_plist_ci(:build_number=> options[:build_number])

		match(type: "development", app_identifier: ENV["APP_IDENTIFIER"])

		gym 		#uses defaults from GymFile

	end
	
	desc "Build for deploying to iTunes Connect in the continuous integration environment"
	lane :build_ci_app do |options|
		
		update_plist_ci(:build_number=> options[:build_number])
		
		#need to run match and gym
		match(type: "appstore", app_identifier: ENV["APP_IDENTIFIER"])
		gym(output_name: ENV["IPA_FILE"]) 		#uses defaults from GymFile
							
	end
	
	def write_changelog(path)
		out_file = File.new(path, "w")
		changelog = change_log_since_last_tag
		out_file.puts(changelog)
		out_file.close
	end
	
	desc "Submit a new Beta Build to Apple TestFlight"
	desc "This will also make sure the profile is up to date"
	lane :beta do |options|
	
		changelog = "Update for MyApp iOS"
		
		if options[:changelog] && File.file?(options[:changelog])
			file = File.open(options[:changelog])
			changelog = file.read
			file.close
		end
		
		pilot(skip_submission:true, skip_waiting_for_build_processing:true, changelog: changelog, ipa: ENV["IPA_FILE"], app_identifier: ENV["APP_IDENTIFIER"])
		
	end
	
	desc "Submit a new Production Build to Apple iTunes Connect"
	desc "This will also make sure the profile is up to date"
	lane :production do |options|
	
		changelog = "Update for MyApp iOS"
		
		if options[:changelog] && File.file?(options[:changelog])
			file = File.open(options[:changelog])
			changelog = file.read
			file.close
		end
		
		pilot(skip_submission:true, skip_waiting_for_build_processing:true, changelog: changelog, ipa: ENV["IPA_FILE"], app_identifier: ENV["APP_IDENTIFIER"])
		
	end
	
end

def change_log_since_last_tag
		# http://git-scm.com/docs/pretty-formats
		# <short hash> <commit title>
		return changelog_from_git_commits(pretty: '%h %s')
end

def version_string(version_number, build_number)
		"#{version_number} (#{build_number})"
end

def tag_name(build_type, version_number, build_number)
		"#{build_type}/#{version_number}/#{build_number}"
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "my@email.com" # Your Apple email address
team_id "##########"  # Developer Portal Team ID

#use different bundle identifiers per lane
app_identifier "com.mycompany.myapp-dev" # The bundle identifier of your app

for_lane 'beta' do
	app_identifier "com.mycompany.myapp-beta" # The bundle identifier of your app
end

for_lane 'production' do
	app_identifier "com.mycompany.myapp" # The bundle identifier of your app
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                    | Version | Update-Status |
| ------------------------- | ------- | ------------- |
| fastlane-plugin-changelog | 0.6.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| awesome_print             | 1.7.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.6        |
| ruby-macho                | 0.2.6        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.2.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| diff-lcs                  | 1.3          |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| fastlane-plugin-changelog | 0.6.1        |
| find_a_port               | 1.0.1        |
| rack                      | 2.0.1        |
| rack-test                 | 0.6.3        |
| randexp                   | 0.1.7        |
| rspec-support             | 3.5.0        |
| rspec-core                | 3.5.4        |
| rspec-expectations        | 3.5.0        |
| rspec-mocks               | 3.5.0        |
| rspec                     | 3.5.0        |
| tins                      | 1.13.2       |
| term-ansicolor            | 1.4.0        |
| thor                      | 0.19.4       |
| pact-support              | 0.6.0        |
| webrick                   | 1.3.1        |
| pact-mock_service         | 0.12.1       |
| xcode-install             | 2.1.1        |
</details>


*generated on:* **2017-02-09**
</details>

**Comment by KrauseFx** [comment]
Do you run into the same results when you run it locally?

**Comment by garie** [comment]
I have not, but I don't often run tests via fastlane locally, and the issue is intermittent. Also my tests aren't usually failing. I can try running with purposeful test fails and see if I can get it to happen.
