### ISSUE TITLE
Is it possible to download the metadata like deliver does for screenshots?

### ISSUE THREAD

**Issue by RyanCopley** [fastlane/fastlane#8190]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,

I work on a platform that supports 100+ apps. We are adopting fastlane and want deliver to manage our metadata. However, it is extremely difficult / time consuming to do this by hand. Is there anything in deliver (or an easy API I can work with) to download the metadata from iTunes Connect and put them in the folder/file structure that fastlane uses? Then I can commit these to CI and use fastlane in its entirety.

Thanks,
Ryan

**Comment by RyanCopley** [comment]
The spaceship API works :D 

```ruby
require "json"
require "spaceship"

Spaceship::Tunes.login("user", "pass")

Spaceship::Tunes.select_team

Spaceship::Tunes::Application.all.collect do |app|
    puts app.name

	pth = '' # Path to where to save to

	metadata_pth = pth + 'ios_metadata/'
	Dir.mkdir metadata_pth

	eng_path = metadata_pth + 'en-US/'
	Dir.mkdir eng_path


	File.open(metadata_pth + 'copyright.txt', 'w') { |file| file.write(app.live_version.copyright) }
	File.open(metadata_pth + 'primary_category.txt', 'w') { |file| file.write(app.details.primary_category.split(".")[1]) }
	File.open(metadata_pth + 'secondary_category.txt', 'w') { |file| file.write(app.details.secondary_category.split(".")[1]) }


	File.open(eng_path + 'description.txt', 'w') { |file| file.write(app.live_version.languages[0]["description"]["value"]) }
	File.open(eng_path + 'keywords.txt', 'w') { |file| file.write(app.live_version.languages[0]["keywords"]["value"]) }
	File.open(eng_path + 'name.txt', 'w') { |file| file.write(app.name) }
	File.open(eng_path + 'privacy_url.txt', 'w') { |file| file.write(app.details.languages[0]["privacyPolicyUrl"]["value"]) }
	File.open(eng_path + 'support_url.txt', 'w') { |file| file.write(app.live_version.languages[0]["supportURL"]["value"]) }


end

```

**Comment by KrauseFx** [comment]
Have you tried `fastlane deliver download_metadata` and `fastlane deliver download_screenshots` 👍

**Comment by RyanCopley** [comment]
Why is that not documented anywhere 😓

**Comment by PetrosIchor** [comment]
It is:. https://github.com/fastlane/fastlane/blob/master/deliver/README.md

**Comment by RyanCopley** [comment]
No, download_metadata is not in that document

**Comment by PetrosIchor** [comment]
It is if you run fastlane deliver --help which that doc cites as a resource for all deliver CLI options.

**Comment by KrauseFx** [comment]
Yes `fastlane [command] --help` is the way to get all available commands, however I agree that documentation isn't perfect as it is now

**Comment by RyanCopley** [comment]
I'll update the documentation and open a PR tomorrow
