### ISSUE TITLE
fastlane and shenzhen

### ISSUE THREAD

**Issue by Gladkov-Art** [fastlane/fastlane#820]
Hi. 
Decided to try bundler for my iOS project and got dependency issue. 
I'm using RVM, with globally installed fastlane (Does it matter?)

Command:
```bundle package --all```
Issue:
```
Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    shenzhen (>= 0) ruby depends on
      faraday (~> 0.8.9) ruby

    fastlane (~> 1.38.0) ruby depends on
      spaceship (< 1.0.0, >= 0.13.1) ruby depends on
        faraday (~> 0.9) ruby
````

**Comment by KrauseFx** [comment]
Could you try cleaning up your old gems using `gem cleanup` or `sudo gem cleanup`? Also, try updating `shenzhen` to the latest release.

**Comment by Gladkov-Art** [comment]
Sorry for very late answer. 
It doesn't help :( 
```
Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    shenzhen (~> 0.14.2) ruby depends on
      faraday (~> 0.8.9) ruby

    fastlane (~> 1.38.0) ruby depends on
      spaceship (< 1.0.0, >= 0.13.1) ruby depends on
        faraday (~> 0.9) ruby
```
Also I've tried to delete Gemfile.lock and all bundler's files/folders, doesn't help either.

**Comment by KrauseFx** [comment]
Do you use a `Gemfile`? If so, try `bundle update`

**Comment by Gladkov-Art** [comment]
No luck :(
Yes I do, I have created Gemfile with fastlane, shenzhen and cocoapods. 
Here is how it looks like:
```
source 'https://rubygems.org'
gem 'fastlane', '~>1.38.0'
gem 'cocoapods', '0.37.0'
gem 'shenzhen', '~>0.14.2'
```

**Comment by Gladkov-Art** [comment]
I have verified the dependencies of spaceship and shenzhen. Spaceship depends on faraday with version at least 0.9.0. But shenzhen depends on faraday 0.8.9 but less then 0.9.0 . There is a conflict :( Don't understand why bundler doesn't what to have 2 different versions of the same gem. When I have used RVM, I remember that in my gemset I had the same gems with different versions.
I use shenzhen to distribute ipa to my private server. What can I do?

**Comment by KrauseFx** [comment]
@Gladkov-Art Please don't specify `shenzhen` but `krausefx-shenzhen` instead, as the `faraday` dependency is updated on the fork that `fastlane` uses.

**Comment by Gladkov-Art** [comment]
@KrauseFx Thanks. I asked ruby developers to increased dependency of our's fork. 
Fastlane is really impressive software! Thanks you. I think this issue can be closed.

**Comment by KrauseFx** [comment]
Yeah, great to hear :+1:
