### ISSUE TITLE
How to disable Fastlane from looking for related Github issues?

### ISSUE THREAD

**Issue by SupreeSeekSter** [fastlane/fastlane#8203]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to upload screenshots to the Play Store. I am using the command "fastlane supply" and it shows this message with github errors: 

"Looking for related GitHub issues on fastlane/fastlane..."
ERROR 65: Your shell environment is not correctly configured
   https://github.com/fastlane/fastlane/issues/8157 [open] 5 💬
   a day ago

➡️  Automaticaly retry failed requests on an internal server error for iTunesConnect
   https://github.com/fastlane/fastlane/pull/8017 [closed] 1 💬
   2 weeks ago

➡️  Automaticaly retry failed requests on an internal server error for iTunes Connect

I tried -->> ENV["FASTLANE_HIDE_GITHUB_ISSUES"] = “1" but it does not work.

My questions:
1. Is this the reason I can't upload screenshots to the Play Store?
2. Where do I put the "FASTLANE_HIDE_GITHUB_ISSUES" in my Fastfile to stop the warning.

[INSERT OUTPUT HERE]

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Is homebrew         | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :android

platform :android do
  before_all do
      ENV["FASTLANE_HIDE_GITHUB_ISSUES"] = “1”
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    ENV["FASTLANE_HIDE_GITHUB_ISSUES"] = “1”
    gradle(task: "assembleRelease")
    supply
  end

lane :playstore do
  gradle(
    task: 'assemble',
    build_type: 'Release'
  )
end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "/Users/supreenuritanon/Desktop/AndroidProject/FastLane/Google\ Play\ Android\ Developer-539733fd672b.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "co.seekster.android.production" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>
*generated on:* **2017-02-12**
[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
`FASTLANE_HIDE_GITHUB_ISSUES` works, I wonder how you've used it exactly? 

Try running _fastlane_ like this:

```
FASTLANE_HIDE_GITHUB_ISSUES=1 fastlane beta
```

I don't know if you can set it in the `Fastfile`, however you can always add it to your `~/.zshrc` (or similar)

**Comment by SupreeSeekSter** [comment]
Thank you, Fastlane does not look for errors on GitHub anymore. Look like there is only one error left. It said Google API Server error. Please help.

This is the log:
[14:51:53]: Preparing to upload for language 'th-'...
/Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:214:in `check_status': **## [!] Server error (Google::Apis::ServerError)**
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/api_command.rb:104:in `check_status'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/lib/google/apis/core/base_service.rb:351:in `execute_or_queue_command'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.20/generated/google/apis/androidpublisher_v2/service.rb:1355:in `get_listing'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/supply/lib/supply/client.rb:140:in `listing_for_language'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/supply/lib/supply/uploader.rb:17:in `block in perform_upload'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/supply/lib/supply/uploader.rb:13:in `each'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/supply/lib/supply/uploader.rb:13:in `perform_upload'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/supply/lib/supply/commands_generator.rb:37:in `block (2 levels) in run'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:178:in `call'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/command.rb:153:in `run'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.2/lib/commander/delegates.rb:15:in `run!'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/supply/lib/supply/commands_generator.rb:55:in `run'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/supply/lib/supply/commands_generator.rb:14:in `start'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Users/supreenuritanon/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/bin/fastlane:15:in `<top (required)>'
	from /Users/supreenuritanon/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/supreenuritanon/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by asfalcone** [comment]
@SupreeSeekSter Can you show the metadata directory structure that you're using for _supply_? A screenshot of finder would be helpful.

**Comment by SupreeSeekSter** [comment]
<img width="1039" alt="screen shot 2560-02-14 at 10 34 00" src="https://cloud.githubusercontent.com/assets/19761196/22914130/83a576e8-f2a1-11e6-853e-b60fcf087dd2.png">

**Comment by hjanuschka** [comment]
@SupreeSeekSter  try removing the folder with the minus `th-` i think this is the troublemaker.

**Comment by SupreeSeekSter** [comment]
<img width="568" alt="screen shot 2560-02-18 at 16 10 51" src="https://cloud.githubusercontent.com/assets/19761196/23092025/1b38182a-f5f5-11e6-829c-6bd2cf59329d.png">

I think it is almost there. Do I have to set apk path? Can I upload screenshots without uploading apk file?

**Comment by asmenter15** [comment]
FYI, I received the same error as above..
`check_status': # [!] Server error (Google::Apis::ServerError)

I experienced this with one of my apps, but then tried another and it worked fine. Not sure where it could be coming from.

**Comment by KrauseFx** [comment]
This discussion is not related to the original issue any more, please submit a new issue to discuss it there, I'll close this one for now 👍
