### ISSUE TITLE
[!] iTunes Connect error: undefined method `key?' for nil:NilClass (RuntimeError)

### ISSUE THREAD

**Issue by Abuki** [fastlane/fastlane#8204]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

getting error:
[!] iTunes Connect error: undefined method `key?' for nil:NilClass (RuntimeError)

when using command:
fastlane deliver --skip_binary_upload true --skip_metadata true --submit_for_review false --overwrite_screenshots true

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane deliver --skip_binary_upload true --skip_metadata true --submit_for_review false --overwrite_screenshots true

Successfully loaded '/Volumes/My Passport/Xcode projects/zviratka-ios/fastlane/Deliverfile' 📄

+---------------------+-------------------------+
| Detected Values from './fastlane/Deliverfile' |
+---------------------+-------------------------+
| app_identifier      | com.circusatos.zviratka |
| username            | michal@circusatos.com   |
+---------------------+-------------------------+

[19:31:01]: Login to iTunes Connect (michal@circusatos.com)
[19:31:05]: Login successful

+-----------------------+-------------------------+
|             deliver 2.14.2 Summary              |
+-----------------------+-------------------------+
| skip_binary_upload    | true                    |
| skip_metadata         | true                    |
| submit_for_review     | false                   |
| overwrite_screenshots | true                    |
| app_identifier        | com.circusatos.zviratka |
| username              | michal@circusatos.com   |
| screenshots_path      | ./fastlane/screenshots  |
| metadata_path         | ./fastlane/metadata     |
| app_version           | 0.3.0                   |
| edit_live             | false                   |
| ipa                   | zviratka.ipa            |
| platform              | ios                     |
| skip_screenshots      | false                   |
| force                 | false                   |
| automatic_release     | false                   |
| dev_portal_team_id    | PTAQTTL7HU              |
+-----------------------+-------------------------+

[19:31:06]: Making sure the latest version on iTunes Connect matches '0.3.0' from the ipa file...
[19:31:08]: '0.3.0' is the latest version on iTunes Connect
[19:31:10]: Verifying the upload via the HTML file can be disabled by either adding
[19:31:10]: `force true` to your Deliverfile or using `fastlane deliver --force`
Does the Preview on path './Preview.html' look okay for you? (y/n)
z
Please enter "yes" or "no".
Does the Preview on path './Preview.html' look okay for you? (y/n)
y
[19:31:18]: HTML file confirmed...
[19:31:19]: Starting with the upload of screenshots...
[19:31:19]: Removing all previously uploaded screenshots...
[19:31:19]: Activating language en-US...
[19:31:23]: Uploading 7 screenshots for language en-US
[19:31:23]: Uploading './fastlane/screenshots/en-US/UnderLeaves10_2880x1800.png'...

Looking for related GitHub issues on fastlane/fastlane...

➡️  [!] Undefined method `description' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/7686 [closed] 9 💬
   5 weeks ago

➡️  Pilot doesn't set requiring metadata for external testing
   https://github.com/fastlane/fastlane/issues/7085 [open] 19 💬
   3 days ago

➡️  pilot upload failure undefined method `builds' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/6267 [closed] 9 💬
   6 weeks ago

and 12 more at: https://github.com/fastlane/fastlane/search?q=iTunes%20Connect%20error:%20undefined%20method%20%60key?'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/tunes/app_version.rb:590:in `rescue in container_data_for_language_and_device': [!] iTunes Connect error: undefined method `key?' for nil:NilClass (RuntimeError)
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/tunes/app_version.rb:579:in `container_data_for_language_and_device'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/tunes/app_version.rb:571:in `screenshots_data_for_language_and_device'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/spaceship/lib/spaceship/tunes/app_version.rb:393:in `upload_screenshot!'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/upload_screenshots.rb:55:in `block (2 levels) in upload'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/upload_screenshots.rb:42:in `each'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/upload_screenshots.rb:42:in `block in upload'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/upload_screenshots.rb:40:in `each'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/upload_screenshots.rb:40:in `upload'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/runner.rb:63:in `upload_metadata'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/runner.rb:21:in `run'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/commands_generator.rb:62:in `block (2 levels) in run'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/commands_generator.rb:148:in `run'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/fastlane/lib/fastlane/cli_tools_distributor.rb:45:in `take_off'
	from /Users/abuki/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.14.2/bin/fastlane:15:in `<top (required)>'
	from /Users/abuki/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/abuki/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
logout

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.9.3 (Apple Git-75)            |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    increment_build_number(
    	build_number: latest_testflight_build_number + 1
    )
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.circusatos.zviratka" # The bundle identifier of your app
apple_id "michal@circusatos.com" # Your Apple email address

team_id "PTAQTTL7HU"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-02-12**
</details>

**Comment by Abuki** [comment]
uploading screenshot should not be related to code signing

**Comment by Abuki** [comment]
My fault. I was trying to upload a screenshot with 2880x1800px, which is for mac, not for iOS.

Anyway, it would be better to have there a warning: "You are uploading a wrong resolution". Or maybe do not upload the images with no matching dimensions.

**Comment by KrauseFx** [comment]
Agreed, the error message is not clear, fix incoming 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/8205 which will be available with the next release 👍
