### ISSUE TITLE
How to remove code sign in a app?

### ISSUE THREAD

**Issue by CodeLife2012** [fastlane/fastlane#8207]
I try to pass a null signing identity when  using `resign`, but  seems not work.

**Comment by hjanuschka** [comment]
what are you trying to achieve? unsign a signed app?

if you just wan't to build without signing et-all.:


```
gym(xcargs: "CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO")
```

**Comment by CodeLife2012** [comment]
Thanks for you quick reply. But if I also want to unsign a signed app?

**Comment by hjanuschka** [comment]
not sure if that works, i think resign is replace signing A with signing B?

**Comment by jeff-jk** [comment]
@CodeLife2012 If you're trying to remove the signature from an ipa archive you can unzip it, delete the ./appname/Payload/appname.app/_CodeSignature directory and the appname/Payload/appname.App/embedded.mobileprovision. This effectively removes the signature, entitlements, and provisioning profile for the app.

**Comment by CodeLife2012** [comment]
The signature for a binary is embed in itself,  just delete other resource may not work. And provisioning profile contain the `capabilities` a app required, delete it may not be a good idea.  @jeff-jk

**Comment by CodeLife2012** [comment]
I have tried the `codesign`, also can't find a option to remove the signature. If `fastlane` is build upon `codesign`, it's impossible  to implement this, so just close this issue.
