### ISSUE TITLE
beta version xcode

### ISSUE THREAD

**Issue by croccio** [fastlane/fastlane#8210]
i use not beta version of iTunes

### New Issue Checklist

- [v ] Updated fastlane to the latest version
- [v ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

+-----------------------+-----------------------------------------------------------------------+
|                                    deliver 2.14.2 Summary                                     |
+-----------------------+-----------------------------------------------------------------------+
| username              | antonio.scardigno@paybay.it                                           |
| app_identifier        | com.paybay.passpartu                                                  |
| ipa                   | /Users/paybaynetworks/Desktop/release 2017-02-13 09-54-47/release.ipa |
| skip_screenshots      | true                                                                  |
| skip_metadata         | true                                                                  |
| force                 | true                                                                  |
| submit_for_review     | false                                                                 |
| automatic_release     | false                                                                 |
| screenshots_path      | ./fastlane/screenshots                                                |
| metadata_path         | ./fastlane/metadata                                                   |
| app_version           | 2.5                                                                   |
| edit_live             | false                                                                 |
| platform              | ios                                                                   |
| skip_binary_upload    | false                                                                 |
| dev_portal_team_id    | CYQRJUG9MR                                                            |
| overwrite_screenshots | false                                                                 |
+-----------------------+-----------------------------------------------------------------------+

[10:28:02]: Making sure the latest version on iTunes Connect matches '2.5' from the ipa file...
[10:28:05]: Successfully set the version to '2.5'
[10:28:10]: Uploading binary to iTunes Connect
[10:28:11]: Going to upload updated app to iTunes Connect
[10:28:11]: This might take a few minutes. Please don't interrupt the script.
[10:29:24]: [Transporter Error Output]: ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Passpartu.app/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."
[10:29:24]: Transporter transfer failed.
[10:29:24]: 
[10:29:24]: ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Passpartu.app/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."
[10:29:24]: ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Passpartu.app/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."
Return status of iTunes Transporter was 1: ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Passpartu.app/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.5                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.7.4 (Apple Git-66)                               |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.5 (15F34)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 7.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | it_IT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.95.0"

default_platform :ios

platform :ios do

    before_all do
        cocoapods
    end

    desc "Runs all the tests"
        lane :test do
        scan
    end

    desc "Increment build number"
    lane :incrementBuildNumber do
        increment_build_number
    end

    desc "Submit a new Beta Build to Apple TestFlight"
    desc "This will also make sure the profile is up to date"
    lane :qualityExt do
        increment_build_number
    end

    desc "Deploy a new version to the App Store"
    lane :release do
        increment_build_number
    end

    after_all do |lane|

    end

    error do |lane, exception|

    end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.paybay.passpartu" # The bundle identifier of your app
apple_id "antonio.scardigno@paybay.it" # Your Apple email address

team_id "CYQRJUG9MR"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.9.0        |
| activesupport             | 4.2.6        |
| colored                   | 1.2          |
| xcodeproj                 | 1.1.0        |
| rouge                     | 1.11.0       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.0        |
| google-api-client         | 0.9.9        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.3        |
| plist                     | 3.2.0        |
| claide                    | 1.0.1        |
</details>

*generated on:* **2017-02-13**
</details>

**Comment by KrauseFx** [comment]
> Return status of iTunes Transporter was 1: ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Passpartu.app/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."

That's an error message generated by Apple. You'll need to use a non-beta release of Xcode to submit your apps. Make sure to select the right one using `xcode-select` 👍

**Comment by croccio** [comment]
I use not beta version. I use Xcode 7.3.1

**Comment by ohayon** [comment]
@croccio would you mind sharing the output of `xcode-select -p` from your command line?

**Comment by KrauseFx** [comment]
This is not a fastlane issue, please follow Apple's instructions:

> Return status of iTunes Transporter was 1: ERROR ITMS-90596: "Invalid Bundle. The asset catalog at 'Payload/Passpartu.app/Assets.car' can't be read. Try rebuilding the app with a non-beta version of Xcode and submit it again."
