### ISSUE TITLE
Can't upload p12 file created by match to firebase due to password set. 

### ISSUE THREAD

**Issue by bmwertman** [fastlane/fastlane#8213]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I just added match to my fastfile. I ran `match nuke` to clean up old certificates and provisioning profiles. Firebase requires that I upload the p12 file to use GCM/FCM password user name user authentication. 

When I try to upload the p12 file created by match in my Github certificates repository Firebase asks for the p12 certificate password. After several unsuccessful attempts to get the correct password I ran `match change_password` and reset the password. I then did `git pull origin master` from my Github certificate repo and tried uploading again but Firebase still says the password is incorrect.

### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.12.0"

private_lane :commit do |options|
  if options[:m] # There was a commit message
    sh("git add -A")
    sh("git commit -a -m '" + options[:m] +"'")
    if options[:b] # specify a branch to push to
      push_to_git_remote(local_branch: options[:b])
    else # or default branch is master
      push_to_git_remote
    end
    desc "Pushed commit to branch options[:b]"
  end
end

platform :android do

  before_all do
    # Make sure no debugger statements were left in our code 
    # ensure_no_debug_code
    # Make sure there are not uncommitted changes
    # ensure_git_status_clean
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  lane :testLocal do
    desc "Compiling a new build for Android ..."
    cordova(
    platform: 'android',
    release: false
    )
  end

  lane :beta do |options|
    if options[:m]
      commit(options)
      # changelog_from_git_commits(
      #   # pretty: "- (%ae) %s", # Optional, lets you provide a custom format to apply to each commit when generating the changelog text
      #   match_lightweight_tag: false, # Optional, lets you ignore lightweight (non-annotated) tags when searching for the last tag
      #   include_merges: false # Optional, lets you filter out merge commits
      # )

      # stamp_changelog( section_identifier: this_commit[:abbreviated_commit_hash] )

    end

    # commit = last_git_commit
    # crashlytics(notes: commit[:message]) # message of commit
    # author = commit[:author] # author of the commit
    # hash = commit[:commit_hash] # long sha of commit
    # short_hash = commit[:abbreviated_commit_hash] # short sha of commit
    # increment_version_code()

    desc "Compiling a new build for Android ..."
    cordova(
      platform: 'android',
      release: false
    )

    crashlytics(
      apk_path: './platforms/android/build/outputs/apk/android-debug.apk',
      api_token: "MY_API_TOKEN",
      build_secret: "MY_BUILD_SECRET,
      notifications: true,
      debug: true
    )
      
    rocket
    say "Brad you rocked another android deployment"
  end
end

platform :ios do
  before_all do
    # Make sure no debugger statements were left in our code 
    # ensure_no_debug_code
    # Make sure there are not uncommitted changes
    # ensure_git_status_clean
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."  
    cocoapods(
      use_bundle_exec: false,
      podfile: "./platforms/ios/Podfile"
    )
  end

  lane :testLocal do
    app_name_sanitized = 'Apparent'

    desc "Building your iOS app ..."
    cert
    sigh(
      adhoc: true,
      force:true
    )
    gym(
      workspace: "platforms/ios/#{app_name_sanitized}.xcworkspace",
      clean: true,
      export_method: "development",
      scheme: app_name_sanitized
    )

  end

  desc "Submit a new Beta Build to Fabric Beta"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    app_name_sanitized = 'Apparent'
    ios_project_path = "platforms/ios/#{app_name_sanitized}.xcodeproj"
    increment_build_number(
      xcodeproj: ios_project_path
    )

    # build your iOS app
    match(
      git_url: "https://github.com/bmwertman/certificates",
      git_branch: "master",
      type: "adhoc",
      app_identifier: "com.apparenttechnologies.apparent",
      verbose: true,
      force: true,
      platform: "ios"
    )
    sigh(
      adhoc: true,
      force:true
    )
    gym(
      workspace: "platforms/ios/#{app_name_sanitized}.xcworkspace",
      clean: true,
      export_method: "ad-hoc",
      scheme: app_name_sanitized
    )

    crashlytics(
      api_token: "MY_API_TOKEN",
      build_secret: "MY_BUILD_SECRET",
      notifications: true,
      debug: true
    )

    rocket
    say "Brad you rocked another i o s deployment"
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.apparenttechnologies.apparent" # The bundle identifier of your app
apple_id "MY_EMAIL" # Your Apple email address

team_id "MY_TEAM_ID"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                 | Version | Update-Status      |
| -------------------------------------- | ------- | ------------------ |
| fastlane-plugin-increment_version_code | 0.3.1   | ✅ Up-To-Date       |
| fastlane-plugin-branding               | 0.1.3   | ✅ Up-To-Date       |
| fastlane-plugin-cordova                | 0.1.4   | ✅ Up-To-Date       |
| fastlane-plugin-changelog              | 0.6.1   | 🚫 Update available |
| fastlane-plugin-ftp                    | 0.1.3   | ✅ Up-To-Date       |

<details><summary><b>Loaded gems</b></summary>

| Gem                                    | Version      |
| -------------------------------------- | ------------ |
| did_you_mean                           | 1.1.0        |
| slack-notifier                         | 1.5.1        |
| i18n                                   | 0.7.0        |
| json                                   | 1.8.6        |
| thread_safe                            | 0.3.5        |
| tzinfo                                 | 1.2.2        |
| minitest                               | 5.10.1       |
| activesupport                          | 4.2.7.1      |
| CFPropertyList                         | 2.3.5        |
| claide                                 | 1.0.1        |
| colored                                | 1.2          |
| nanaimo                                | 0.2.3        |
| xcodeproj                              | 1.4.2        |
| rouge                                  | 1.11.1       |
| xcpretty                               | 0.2.4        |
| terminal-notifier                      | 1.7.1        |
| unicode-display_width                  | 1.1.3        |
| terminal-table                         | 1.7.3        |
| plist                                  | 3.2.0        |
| public_suffix                          | 2.0.5        |
| addressable                            | 2.5.0        |
| multipart-post                         | 2.0.0        |
| word_wrap                              | 1.0.0        |
| babosa                                 | 1.0.2        |
| highline                               | 1.7.8        |
| commander                              | 4.4.3        |
| excon                                  | 0.54.0       |
| faraday                                | 0.11.0       |
| unf_ext                                | 0.0.7.2      |
| unf                                    | 0.1.4        |
| domain_name                            | 0.5.20161129 |
| http-cookie                            | 1.0.3        |
| faraday-cookie_jar                     | 0.0.6        |
| fastimage                              | 2.0.1        |
| gh_inspector                           | 1.0.3        |
| uber                                   | 0.0.15       |
| representable                          | 2.3.0        |
| retriable                              | 2.1.0        |
| mime-types-data                        | 3.2016.0521  |
| mime-types                             | 3.1          |
| hurley                                 | 0.2          |
| little-plugger                         | 1.1.4        |
| multi_json                             | 1.12.1       |
| logging                                | 2.1.0        |
| jwt                                    | 1.5.6        |
| memoist                                | 0.15.0       |
| os                                     | 0.9.6        |
| signet                                 | 0.7.3        |
| googleauth                             | 0.5.1        |
| httpclient                             | 2.8.3        |
| google-api-client                      | 0.9.26       |
| mini_magick                            | 4.5.1        |
| multi_xml                              | 0.6.0        |
| rubyzip                                | 1.2.0        |
| security                               | 0.1.3        |
| xcpretty-travis-formatter              | 0.0.4        |
| dotenv                                 | 2.2.0        |
| bundler                                | 1.14.3       |
| faraday_middleware                     | 0.11.0.1     |
| io-console                             | 0.4.6        |
| openssl                                | 2.0.2        |
| fastlane-plugin-increment_version_code | 0.3.1        |
| branding                               | 0.1.0        |
| fastlane-plugin-branding               | 0.1.3        |
| fastlane-plugin-cordova                | 0.1.4        |
| fastlane-plugin-changelog              | 0.6.1        |
| fastlane-plugin-ftp                    | 0.1.3        |
</details>

*generated on:* **2017-02-13**
</details>

**Comment by bmwertman** [comment]
Thanks @fastlane-bot but these were the docs I was following to get setup.

**Comment by KrauseFx** [comment]
Why do you want to upload your private key of your code signing identity to Firebase? Do you want to create push certificates? If so, you should use [pem](https://fastlane.tools/pem) instead of _match_ 👍

**Comment by bmwertman** [comment]
If a password is set on the p12 certificate Firebase asks for it when you upload the certificate.

![screen shot 2017-02-13 at 12 59 51 pm](https://cloud.githubusercontent.com/assets/2573903/22895985/6ba84b34-f1ec-11e6-9686-26a197cda21c.png)

**Comment by KrauseFx** [comment]
Hey @bmwertman, that's because you try to upload the private key of your certificate. Please use _pem_ to use push certificates, not _match_ 👍

**Comment by bmwertman** [comment]
OK thanks. I just tried to add pem. Ran my build and I'm now experiencing the issue as others on #8209
