### ISSUE TITLE
Resign with app entitlements escape problem

### ISSUE THREAD

**Issue by osrufung** [fastlane/fastlane#8216]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using "resign" action to resign an ipa containing an extension:
```
     resign(
        ipa: "#{ipaBoundName}",
        signing_identity: "#{ENV['RESIGN_IDENTIFIER']}",
        provisioning_profile: {
          "#{ENV["APP_IDENTIFIER"]}" => "#{ENV["APP_IDENTIFIER"]}.mobileprovision",
          "#{ENV["APP_IDENTIFIER"]}.widget" => "#{ENV["APP_IDENTIFIER"]}.widget.mobileprovision", 
        },
        use_app_entitlements: true
      )
```
I get an invalid regenerated entitlement file (archived-expanded-entitlements.xcent)  with this syntax error in the key (escaped chars which generate an error when you upload to ITC or install on device as an adhoc file):

`<key>com\.apple\.security\.application-groups</key>
	<array>`

This cannot be reproduced on previous versions of fastlane (2.9.0 by example). This version creates a valid .xcent file with all the keys with valid characters.

##### Complete output when running fastlane, including the stack trace and command used

Command used:

```
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.15.1/sigh/lib/assets/resign.sh 
original.ipa  <SIGNING_CERTIFICATE> -v --use-app-entitlements 
-p bundleID=bundle.mobileprovision 
-p bundleID.widget=bundleID.widget.mobileprovision 
resigned.ipa
```

Output:

```
...
Resigning application using certificate: '---'
and patched entitlements:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>---</string>
	<key>aps-environment</key>
	<string>production</string>
	<key>com.apple.developer.team-identifier</key>
	<string>---</string>
	<key>com\.apple\.security\.application-groups</key>
	<array>
		<string>----</string>
	</array>
	<key>get-task-allow</key>
	<false/>
	<key>keychain-access-groups</key>
	<array>
		<string>-.*</string>
		<string>-group</string>
	</array>
</dict>
</plist>


```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.5                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.5 (15F34)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.0/lib            |
| OpenSSL Version     | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.0   |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| multi_json                | 1.12.1  |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| bundler                   | 1.13.5  |
| json                      | 2.0.3   |
| commander                 | 4.4.3   |
| io-console                | 0.4.5   |
| excon                     | 0.54.0  |
| rubyzip                   | 1.2.0   |
| plist                     | 3.2.0   |
| CFPropertyList            | 2.3.4   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| terminal-table            | 1.7.3   |
| unicode-display_width     | 1.1.3   |
</details>

*generated on:* **2017-02-13**
</details>

**Comment by AliakseiT** [comment]
I can confirm the regression. Specifically it leads to subsequent validation errors on upload: `ERROR ITMS-90045: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, key 'com\.apple\.developer\.associated-domains' in ... is not supported.`

**Comment by mfurtak** [comment]
@mgrebenets Do you have any insights on this?

**Comment by AliakseiT** [comment]
`sigh` 1.12.1 did not have the problem.

**Comment by mgrebenets** [comment]
Looking into it. 👀

**Comment by osrufung** [comment]
Any idea guys? 🤔

**Comment by AliakseiT** [comment]
@osrufung, are you using `sigh` as a `fastlane sigh` already? Also, do you install it from `brew`? For me the workaround was: install latest `fastlane` and 1.12.1 `sigh` as a versioned gem and use it the old style, i.e. `sigh resign` rather then `fastlane sigh resign`.

**Comment by mgrebenets** [comment]
I believe it's been fixed here: https://github.com/fastlane/fastlane/pull/8295 by @djsison
