### ISSUE TITLE
2-step verification: FASTLANE_SESSION parameter ignored by spaceship/match

### ISSUE THREAD

**Issue by neilmcguiggan** [fastlane/fastlane#8218]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm using match to manage code signing, and I'm trying to set up my project to build on Travis CI. The Apple ID that I use for match is set up with 2 step verification, so I obviously want to avoid being asked to enter my password and verification code when building on the CI server.

Following the steps outlined in [issue 7199](https://github.com/fastlane/fastlane/issues/7199), I've run `fastlane spaceauth -u me@email.com` and generated a web session, which I enter as the value of an environment variable called `FASTLANE_SESSION` in Travis CI. I've also created an app-specific password and set that value in an environment variable called `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`.

But when I run my lane, it still asks for a password rather than using the environment variables that I've set. What am I missing; how do I get match/spaceship to use the session rather than wait for a password?

##### Complete output when running fastlane, including the stack trace and command used
```
... [removed unnecessary stuff from the start of the build output]

$ echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc

$ fastlane dev
[17:23:03]: -------------------------------------------------
[17:23:03]: --- Step: Verifying required fastlane version ---
[17:23:03]: -------------------------------------------------
[17:23:03]: Your fastlane version 2.14.2 matches the minimum requirement of 2.14.2  ✅
[17:23:03]: ------------------------------
[17:23:03]: --- Step: default_platform ---
[17:23:03]: ------------------------------
[17:23:03]: Driving the lane 'ios dev' 🚀
[17:23:03]: -----------------------
[17:23:03]: --- Step: cocoapods ---
[17:23:03]: -----------------------
[17:23:04]: $ pod install
[17:23:16]: ▸ Analyzing dependencies
[17:23:16]: ▸ Downloading dependencies
[17:23:16]: ▸ Using AppsFlyerFramework (4.6.4)
[17:23:16]: ▸ Using Firebase (3.12.0)
[17:23:16]: ▸ Using FirebaseAnalytics (3.6.0)
[17:23:16]: ▸ Using FirebaseCore (3.4.7)
[17:23:16]: ▸ Using FirebaseInstanceID (1.0.8)
[17:23:16]: ▸ Using FirebaseMessaging (1.2.1)
[17:23:16]: ▸ Using GoogleInterchangeUtilities (1.2.2)
[17:23:16]: ▸ Using GoogleSymbolUtilities (1.1.2)
[17:23:16]: ▸ Using GoogleToolboxForMac (2.1.1)
[17:23:16]: ▸ Using HanekeSwift (0.10.1)
[17:23:16]: ▸ Using NibDesignable (3.0.0)
[17:23:16]: ▸ Using Realm (2.4.2)
[17:23:16]: ▸ Using RealmSwift (2.4.2)
[17:23:16]: ▸ Using SnapKit (3.1.2)
[17:23:16]: ▸ Generating Pods project
[17:23:16]: ▸ Integrating client project
[17:23:17]: ▸ Sending stats
[17:23:17]: ▸ Pod installation complete! There are 7 dependencies from the Podfile and 14 total pods installed.
[17:23:17]: -------------------
[17:23:17]: --- Step: match ---
[17:23:17]: -------------------
[17:23:19]: Successfully loaded '/Users/travis/build/my_org/my_app/fastlane/Matchfile' 📄

+----------------------+----------------------------------------------------------+
|                   Detected Values from './fastlane/Matchfile'                   |
+----------------------+----------------------------------------------------------+
| git_url              | https://github.com/my_org/my_certificate_repo.git |
| app_identifier       | ["com.example.app", "com.example.app.dev"]                 |
| username             | me@email.com                                         |
+----------------------+----------------------------------------------------------+


+-----------------------+----------------------------------------------------------+
|                             Summary for match 2.14.2                             |
+-----------------------+----------------------------------------------------------+
| type                  | appstore                                                 |
| git_url               | https://github.com/my_org/my_certificate_repo.git |
| app_identifier        | ["com.example.app", "com.example.app.dev"]                 |
| username              | me@email.com                                         |
| git_branch            | master                                                   |
| keychain_name         | login.keychain                                           |
| readonly              | false                                                    |
| team_id               | my_team_id                                               |
| verbose               | false                                                    |
| force                 | false                                                    |
| skip_confirmation     | false                                                    |
| shallow_clone         | false                                                    |
| force_for_new_devices | false                                                    |
| skip_docs             | false                                                    |
| platform              | ios                                                      |
+-----------------------+----------------------------------------------------------+

[17:23:19]: Cloning remote git repo...
[17:23:20]: 🔓  Successfully decrypted certificates repo
[17:23:20]: You can also run `match` in readonly mode to not require any access to the
[17:23:20]: Developer Portal. This way you only share the keys and credentials
[17:23:20]: $ fastlane match --readonly
[17:23:20]: More information https://github.com/fastlane/fastlane/tree/master/match#access-control
[17:23:20]: Verifying that the certificate and profile are still valid on the Dev Portal...
-------------------------------------------------------------------------------------
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for me@email.com): 
```

### Appfile
```
app_identifier "com.example.app"
apple_id "me@email.com"

team_id "my_team_id"

for_lane :dev do
  app_identifier 'com.example.app.dev'
end

```

### Fastfile
```
fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "MyApp Dev build"
  lane :dev do
    match(type: "appstore")
    gym(
      workspace: "MyApp.xcworkspace",
      scheme: "MyApp Dev",
      configuration: "Debug"
    )
  end
```

**Comment by neilmcguiggan** [comment]
I've read the Code Signing Troubleshooting Guide, and I've included the output that seems relevant from `fastlane env`, including my Appfile and Fastfile. If there's anything missing that would help, let me know and I'll add that too.

**Comment by KrauseFx** [comment]
You'll also need to provide the `FASTLANE_PASSWORD` environment variable, which is your iTunes Connect / Dev Portal password. Have you done that?

**Comment by neilmcguiggan** [comment]
I hadn't. I'd assumed the password wasn't necessary because `FASTLANE_SESSION` was supposed to be used to log in instead.

Having set the `FASTLANE_PASSWORD`, it now asks for me to choose a device to receive the 2-step verification code, which is the whole problem - it seems like the steps to work around 2-step verification are still being ignored:

```
[06:49:47]: Cloning remote git repo...
[06:49:47]: 🔓  Successfully decrypted certificates repo
[06:49:47]: Verifying that the certificate and profile are still valid on the Dev Portal...
Two Step Verification for account 'me@email.com' is enabled
Please select a device to verify your identity
1. Device 1
2. Device 2
3. Device 3
4. Device 4
5. Device 5
6. Device 6
?  

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by KrauseFx** [comment]
Can you ensure the token is properly being set to `SPACESHIP_SESSION` or `FASTLANE_SESSION`? Can you echo the environment variables as part of your build step?

**Comment by neilmcguiggan** [comment]
It looks like it's being set to `FASTLANE_SESSION` properly:
```
[09:34:15]: $ echo $FASTLANE_SESSION
[09:34:15]: ▸ ---
[09:34:15]: ▸ - !ruby/object:HTTP::Cookie
[09:34:15]: ▸ name: [redacted]
[09:34:15]: ▸ value: [redacted]
[09:34:15]: ▸ domain: idmsa.apple.com
[09:34:15]: ▸ for_domain: true
[09:34:15]: ▸ path: "/"
[09:34:15]: ▸ secure: true
[09:34:15]: ▸ httponly: true
[09:34:15]: ▸ expires:
[09:34:15]: ▸ max_age: 2592000
[09:34:15]: ▸ created_at: 2017-02-13 14:19:53.394355000 +00:00
[09:34:15]: ▸ accessed_at: 2017-02-13 16:22:50.124457000 +00:00
[09:34:15]: ▸ - !ruby/object:HTTP::Cookie
[09:34:15]: ▸ name: [redacted]
[09:34:15]: ▸ value: [redacted]
[09:34:15]: ▸ domain: itunesconnect.apple.com
[09:34:15]: ▸ for_domain: false
[09:34:15]: ▸ path: "/"
[09:34:15]: ▸ secure: true
[09:34:15]: ▸ httponly: true
[09:34:15]: ▸ expires:
[09:34:15]: ▸ max_age: 1800
[09:34:15]: ▸ created_at: &1 2017-02-13 16:22:54.121291000 +00:00
[09:34:15]: ▸ accessed_at: *1
```

What should happen if it's an invalid session? Should it fall back to 2-step verification, as it does here? Or should it give an error?

**Comment by Badmuts** [comment]
Experiencing same problem on Travis CI with `FASTLANE_SESSION` and `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` set.

**Comment by mfurtak** [comment]
Taking a look through the code, `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` appears to only be used by the iTunes Transporter, and thus _pilot_ and _deliver_.

_spaceship_ (which backs _match_) doesn't use that env var at all. That env var is referenced in _spaceship_'s documentation, however, so we should think about that...

----

Here's a simple test I've tried, which would be great to have you try as well:

### Baseline

1. I've ensured that `FASTLANE_PASSWORD`, `FASTLANE_SESSION`, and `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD` are empty by using `unset FASTLANE_PASSWORD`, etc. in my shell
1. I have 2-step (not two-factor) verification on for my account, no trusted devices, using SMS to verify
1. I've deleted "deliver.my@email.com" creds for my account from  Keychain Access
1. I have deleted the my spaceship cookie storage path with `rm -rf ~/.fastlane/spaceship/my\@email.com`
1. I've run `fastlane spaceship -u my@email.com`
    * I need to provide my password again
    * I need to verify using SMS again

  ```
  Logging into to iTunes Connect (my@email.com)...
  -------------------------------------------------------------------------------------
  The login information you enter will be stored in your macOS Keychain
  You can also pass the password using the `FASTLANE_PASSWORD` environment variable
  More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
  -------------------------------------------------------------------------------------
  Password (for my@email.com): *********
  Two Step Verification for account 'my@email.com' is enabled
  Please select a device to verify your identity
  1. +• ••••••••75	SMS	(630)
  ?
  ```

### Expected Success

1. I have run `fastlane spaceauth -u me@email.com` and stored the resulting cookie value in `FASTLANE_SESSION` env var, exporting it from my dotfile
1. I have stored my account password in `FASTLANE_PASSWORD` and exported it from my dotfile
1. I have started a new shell, and verified that `FASTLANE_SESSION` and `FASTLANE_PASSWORD` have the values I expect
1. I have verified that the keychain does not contain "deliver.my@email.com" creds
1. I have verified that the spaceship cookie cache dir is empty
1. I've run `fastlane spaceship -u my@email.com`, and I get to the playground prompt with no credentials challenges

```
Logging into to iTunes Connect (me@email.com)...
Successfully logged in to iTunes Connect

Logging into the Developer Portal (me@email.com)...
Successfully logged in to the Developer Portal

---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------
```

That should signify that things are working well. :rocket: How does this controlled experiment work for you?

**Comment by Badmuts** [comment]
Thanks for your help mfurtak. I think I misunderstood the problem outlined here. My problem is with pilot and deliver, not match.

I do however get the same 2 factor auth problem with pilot and deliver even when I provide `FASTLANE_SESSION` and `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`. Should I open a separate issue for this?

**Comment by mfurtak** [comment]
@Badmuts Sure, that sounds good 👍

**Comment by RafaelPlantard** [comment]
I'm facing this same issue at `match`. Any solution?

**Comment by mfurtak** [comment]
Hi @RafaelPlantard - please track trouble with this as it relates to _pilot_ over here: https://github.com/fastlane/fastlane/issues/8298

**Comment by mfurtak** [comment]
@Badmuts If it's OK with you, I'm going to close this issue then, and we'll continue to work on _pilot_/_deliver_ stuff in #8374, #8298, #7380 👍

**Comment by KrauseFx** [comment]
Hey everyone, _fastlane_ now fully supports both two-factor and two-step verification 👋 

Please make sure to update to the latest version of _fastlane_ by running 

```
fastlane update_fastlane
```

If you use a `Gemfile`, just run `bundle update`

### On your computer 🚀
To use _fastlane_ with two-factor, just run _fastlane_ as you usually would. You'll be asked for the verification method, and a 4 or 6 digits pin. Everything will just work out of the box 📦 

### On your continuous integration system 💻 
Check out the [official two-factor docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth) for more information on how to setup two-step on CI system. You'll have to authenticate on your local machine to get a session cookie, which you then transfer to your CI.

----

If you have any issues setting this up, please submit [a new issue](https://github.com/fastlane-old/spaceship/issues/new) so we can help you get up and running 👍
