### ISSUE TITLE
Use cocoapods in different directory

### ISSUE THREAD

**Issue by shuhrat10** [fastlane/fastlane#8221]
Hi, 

I want to setup fastlane to use following folder structure. How can I do it? 

```
/Projects/MyProject/fastlane
/Projects/MyProject/app/MyProject.xcworkspace
```

Right now, I'm getting error and I can't find documentation how to set project path manually: 

`[!] No `Podfile' found in the project directory.`

**Comment by shuhrat10** [comment]
`
fastlane env
[16:37:32]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.2                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.2.2/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.2/lib                |
| OpenSSL Version     | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    # Dir.chdir("../app")
    # ENV['GYM_WORKSPACE'] = 'Shudder.xcworkspace'

    # Dir.chdir ".." do
    #   # sh("cd app")
    #   # sh("mkdir xxx")
    #   # sh("platforms/android/cordova/clean")
    #   # cocoapods
    # end

    cocoapods
  end

  desc "Create/Download certificates and profiles"
  lane :provisioning do
    cert(development: true, output_path: "provisioning")
    cert(output_path: "provisioning")

    sigh(development: true, output_path: "provisioning")
    sigh(adhoc: true, output_path: "provisioning")
    sigh(output_path: "provisioning")
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight / Production"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Shudder_PROD") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Submit a new Beta Build to Apple TestFlight / Development"
  desc "This will also make sure the profile is up to date"
  lane :betadev do
    increment_build_number
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Shudder_DEV") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Shudder_PROD") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.sundancenow.shudder" # The bundle identifier of your app
apple_id "Nathan.Taylor@amcnetworks.com" # Your Apple email address

team_id "72GP743PB7"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.14.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| json                      | 1.8.3        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
</details>


*generated on:* **2017-02-13**
</details>
`

**Comment by shuhrat10** [comment]
The idea is, I don't wanna put fastlane folder into my xCode project. I want to keep it one or two level up.

**Comment by PetrosIchor** [comment]
The error states it cannot find your pod file.  Make sure you set the path correctly when calling cocoapods actions.

**Comment by shuhrat10** [comment]
I know. As I said before, I want to move fastlane folder level up from xCode project. Once I did that, I start getting error. Now I wonder how can I set path to xCode project in Fastlane config file.

**Comment by KrauseFx** [comment]
You can use 
```ruby
Dir.chdir("../../other_dir") do
  cocoapods
end
```

**Comment by shuhrat10** [comment]
@KrauseFx I'trying this, but it's still not working. 

`
platform :ios do
  before_all do
    Dir.chdir("../app/") do
      sh("ls -al")
      cocoapods
    end
  end
`

and I'm getting error: 

`
[21:48:28]: -------------------------------------------------
[21:48:28]: --- Step: Verifying required fastlane version ---
[21:48:28]: -------------------------------------------------
[21:48:28]: Your fastlane version 2.15.1 matches the minimum requirement of 2.15.1  ✅
[21:48:28]: ------------------------------
[21:48:28]: --- Step: default_platform ---
[21:48:28]: ------------------------------
[21:48:28]: Driving the lane 'ios beta' 🚀
[21:48:28]: --------------------
[21:48:28]: --- Step: ls -al ---
[21:48:28]: --------------------
[21:48:28]: $ ls -al
[21:48:28]: ▸ total 48
[21:48:28]: ▸ drwxr-xr-x   9 myuser  1189838997    306 Feb 13 21:46 .
[21:48:28]: ▸ drwxr-xr-x  10 myuser  1189838997    340 Feb 13 21:45 ..
[21:48:28]: ▸ -rw-r--r--@  1 myuser  1189838997  10244 Feb 13 21:46 .DS_Store
[21:48:28]: ▸ -rw-r--r--   1 myuser  1189838997   1132 Feb 13 16:42 Podfile
[21:48:28]: ▸ -rw-r--r--   1 myuser  1189838997   6728 Feb 13 14:07 Podfile.lock
[21:48:28]: ▸ drwxr-xr-x  46 myuser  1189838997   1564 Feb 13 17:13 Pods
[21:48:28]: ▸ drwxr-xr-x   7 myuser  1189838997    238 Feb  9 11:51 TestApp
[21:48:28]: ▸ drwxr-xr-x@  6 myuser  1189838997    204 Feb 13 13:49 TestApp.xcodeproj
[21:48:28]: ▸ drwxr-xr-x   5 myuser  1189838997    170 Feb  8 17:33 TestApp.xcworkspace
[21:48:28]: -----------------------
[21:48:28]: --- Step: cocoapods ---
[21:48:28]: -----------------------
[21:48:29]: $ pod install
[21:48:30]: ▸ [!] No `Podfile' found in the project directory.
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[21:48:30]: Exit status of command 'pod install' was 1 instead of 0.
[!] No `Podfile' found in the project directory.
`

**Comment by KrauseFx** [comment]
Ah, try the following:
```ruby
platform :ios do
  before_all do
    Dir.chdir("../app/") do
      sh("pod install")
    end
  end
```
(feel free to replace `pod install` with `pod update`)

**Comment by shuhrat10** [comment]
@KrauseFx this is working but not how I want. It's mean I have to set 

```
Dir.chdir("../app/") do
```

for each lane. 

In addition, I tried this and I'm getting error:

```
lane :beta do
    Dir.chdir("../app") do
      sh("ls -al")
      increment_build_number
    end
  end
```

```
[22:22:04]: --------------------
[22:22:04]: --- Step: ls -al ---
[22:22:04]: --------------------
[22:22:04]: $ ls -al
[22:22:04]: ▸ total 48
[22:22:04]: ▸ drwxr-xr-x   9 myuser  1189838997    306 Feb 13 21:46 .
[22:22:04]: ▸ drwxr-xr-x  10 myuser  1189838997    340 Feb 13 21:45 ..
[22:22:04]: ▸ -rw-r--r--@  1 myuser  1189838997  10244 Feb 13 22:21 .DS_Store
[22:22:04]: ▸ -rw-r--r--   1 myuser  1189838997   1132 Feb 13 16:42 Podfile
[22:22:04]: ▸ -rw-r--r--   1 myuser  1189838997   6728 Feb 13 22:22 Podfile.lock
[22:22:04]: ▸ drwxr-xr-x  46 myuser  1189838997   1564 Feb 13 22:21 Pods
[22:22:04]: ▸ drwxr-xr-x   7 myuser  1189838997    238 Feb  9 11:51 TestApp
[22:22:04]: ▸ drwxr-xr-x@  6 stursunov  1189838997    204 Feb 13 13:49 TestApp.xcodeproj
[22:22:04]: ▸ drwxr-xr-x   5 stursunov  1189838997    170 Feb  8 17:33 TestApp.xcworkspace
[22:22:04]: ------------------------------------
[22:22:04]: --- Step: increment_build_number ---
[22:22:04]: ------------------------------------
[22:22:04]: $ cd /Users/myuser/Projects/App/ios_structure/application-ios && agvtool next-version -all && cd -
[22:22:04]: ▸ There are no Xcode project files in this directory.  agvtool needs a project to operate.
[22:22:04]: Before being able to increment and read the version number from your Xcode project, you first need to setup your project properly. Please follow the guide at https://developer.apple.com/library/content/qa/qa1827/_index.html
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[22:22:04]: Exit status of command 'cd /Users/myuser/Projects/App/ios_structure/application-ios && agvtool next-version -all && cd -' was 3 instead of 0.
There are no Xcode project files in this directory.  agvtool needs a project to operate.


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | pod install                         | 8           |
| 4    | ls -al                              | 0           |
| 💥   | increment_build_number              | 0           |
+------+-------------------------------------+-------------+

[22:22:04]: fastlane finished with errors

[!] Exit status of command 'cd /Users/myuser/Projects/App/ios_structure/application-ios && agvtool next-version -all && cd -' was 3 instead of 0.
There are no Xcode project files in this directory.  agvtool needs a project to operate.
```

**Comment by shuhrat10** [comment]
@KrauseFx looks like any fastlane command is not running correctly in 
```
Dir.chdir("../app") do
// Something
end
```

**Comment by KrauseFx** [comment]
I'd strongly recommend adding the `fastlane` directory into the project's directory to avoid all of these issues. Only put it in a custom location if you have the time and resources to look into the source code of _fastlane_ to analyze why it's not working.

**Comment by ohayon** [comment]
Hey @shuhrat10, I agree with @KrauseFx, it would be best practice to put your _fastlane_ directory next to your xcodeproj in the same directory.

Going to close this issue for now as there are working-work arounds and we really advise users to keep their _fastlane_ directories in a certain place relative to their projects. Let us know if you are having any more issues! 😄 🐙

**Comment by shuhrat10** [comment]
My idea is to have fastlane directory one level up. For example: 

Hello World (Application Folder)
--> app (xcode project)
--> fastlane (fastlance folder)
--> provision folder (cert and provision profiles)

I think this file structure much better. Rather to put everything in one xCode project folder. If I need copy project and share with someone via email, I don't have to worry about deleting fastlane and provision profile folder from the project folder.

**Comment by ohayon** [comment]
Hey @shuhrat10, I totally understand that you would want to keep your provisioning profile and other information separate. You should be able to pass arguments to _sigh_ and _cert_ to store those assets at different paths so that you can keep those specific files outside of your main directory.

**Comment by ndbroadbent** [comment]
Hi, I just wanted to mention that I'm running into this issue while trying to set up fastlane for a cross-platform React Native app. I really want to keep my fastlane directory at the root, and manage my ios and android lanes in a single `Fastfile`. (So that I can reuse code for things like Slack updates, etc.)

It took me a while to figure this out, but here's the solution:

```
cocoapods(podfile: './ios/Podfile')
```

So `Dir.chdir` is relative to the `fastlane` directory, but cocoapods is relative to the actual root directory (where you are running the fastlane command).

**Comment by KrauseFx** [comment]
Thanks for sharing this @ndbroadbent, it's not ideal, but not something we can change currently.
