### ISSUE TITLE
Can't Update Fastlane w/ sudo gem update fastlane

### ISSUE THREAD

**Issue by ehorodyski** [fastlane/fastlane#8238]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I can't update Fastlane to the latest version. I've tried using the stand-alone installer to reinstall as well as running `sudo gem update fastlane` and neither are working.

When trying `sudo gem update fastlane` I am returned:
>Updating installed gems
>Noting to update

##### Complete output when running fastlane, including the stack trace and command used
> Updating installed gems
Updating fastlane
Fetching: tty-screen-0.5.0.gem (100%)
Successfully installed tty-screen-0.5.0
Fetching: fastlane-2.15.1.gem (100%)
Successfully installed fastlane-2.15.1
Gems updated: fastlane tty-screen
Cleaning up installed gems...
Attempting to uninstall fastlane-2.13.0
Successfully uninstalled fastlane-2.13.0
Clean Up Complete
Detected fastlane is already in your path 🚀
xcdda:my-xplore ehorodys$ fastlane -v
fastlane installation at path:
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.14.2/bin/fastlane

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.11.6                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.11.6 (15G1217)                                     |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
fastlane_version "2.14.2"

# Fastlane Hooks
before_all do
   ENV["SLACK_URL"] = "https://hooks.slack.com/services/"
end

error do |lane, exception|
  slack(message: exception.message, success: false)
end

after_all do |lane, options|
  slack(message: @message)
end

# Multiplatform Lanes
desc "Asset Build"
private_lane :build do |options|
  #sh "gulp build --" + options[:env]
end

# Android Lanes
platform :android do
  # Valid Android Tracks: [alpha | beta | production | rollout]

  # Public Lanes

  desc "Submit a new build to Google Play"
  lane :deploy do |options|
    if !['dev', 'qa', 'prod'].include? options[:env]
      raise "Please provide 'env' option as 'dev', 'qa', or 'prod'"
    else
      case options[:env]
      when 'dev'
        build(env: options[:env])
        package()
        submit(track: "alpha")
       when 'qa'
        build(env: options[:env])
        package()
        submit(track: "qa")
       when 'prod'
        build(env: options[:env])
        package()
        submit(track: "production")
      else
        raise "Please provide 'env' option as 'dev', 'qa', or 'prod'"
      end
    end
  end

  # Private Lanes

  desc "Package APK"
  private_lane :package do |options|
    sh "cp -u /Users/Shared/keys/android/android_keystore.jks /Users/Shared/keys/android/release-signing.properties ./platforms/android/"
    #sh "ionic build android --release"
  end

  desc "Deploy to Google Play"
  private_lane :submit do |options|
    #supply(track: options[:track], apk_pahts: #["platforms/android/build/outputs/apk/android-release.apk"])
   # @message = "[Google Play] Deployed to " + options[:track].capitalize() + " Channel"
  end

end

# iOS Lanes
platform :ios do

  desc "Deploy to Internal Testflight"
  lane :internal do
    prepare()
    @message = "[AppStore] deployed to Internal TestFlight"
  end

  # Private Lanes

  desc "Prepare iOS"
  private_lane :prepare do |options|
    sh "ionic prepare ios"
  end


end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "automation.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "org.ieee.mobile.pubs.myxplore" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.14.2  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.6        |
</details>

*generated on:* **2017-02-14**
</details>

**Comment by KrauseFx** [comment]
From your other issue, could you try this? 

```
INFO [2017-02-14 11:02:11.35]: Looking for updates for fastlane...
WARN [2017-02-14 11:02:11.45]: The update_fastlane action requires rubygems version 2.1.0 or greater.
WARN [2017-02-14 11:02:11.45]: Please update your version of ruby gems before proceeding.
INFO [2017-02-14 11:02:11.45]: $ gem install rubygems-update
INFO [2017-02-14 11:02:11.45]: $ update_rubygems
INFO [2017-02-14 11:02:11.45]: $ gem update --system
```

**Comment by ehorodyski** [comment]
This is what I get:

```
xcdda:~ ehorodys$ gem install rubygems-update
Successfully installed rubygems-update-2.6.10
Parsing documentation for rubygems-update-2.6.10
Done installing documentation for rubygems-update after 0 seconds
1 gem installed
xcdda:~ ehorodys$ update_rubygems
RubyGems 2.6.10 installed
Parsing documentation for rubygems-2.6.10
Installing ri documentation for rubygems-2.6.10

=== 2.6.10 / 2017-01-23

Bug fixes:

* Fix `require` calling the wrong `gem` method when it is overridden.
  Pull request #1822 by Samuel Giddins.


------------------------------------------------------------------------------

RubyGems installed the following executables:
	/usr/local/Cellar/ruby/2.4.0/bin/gem

Ruby Interactive (ri) documentation was installed. ri is kind of like man 
pages for ruby libraries. You may access it like this:
  ri Classname
  ri Classname.class_method
  ri Classname#instance_method
If you do not wish to install this documentation in the future, use the
--no-document flag, or set it as the default in your ~/.gemrc file. See
'gem help env' for details.

xcdda:~ ehorodys$ gem update --system
Latest version currently installed. Aborting.
```
Then trying to update Fastlane gives me the same as my first post.

**Comment by edasque** [comment]
I have the same issue.

**Comment by Redysz** [comment]
The same here.
fastlane update_fastlane:
```
Updating installed gems
Nothing to update
Cleaning up installed gems...
Clean Up Complete
```

after download new version of fastlane from website:

```
fastlane is already installed at /Users/User/.fastlane/bin
Do you want to reinstall fastlane? The old directory, including any changes you made, will be removed! (y/N) y
The installer will now run the uninstall script to remove your existing fastlane bundle...
Do you want to uninstall fastlane from /Users/User/.fastlane/bin? (y/n) y
You can now remove fastlane from your search path by editing your unknown file.
fastlane was uninstalled successfully!
Done uninstalling, your regular installation will now commence. 🚕 💨
Installing fastlane to /Users/User/.fastlane/bin... this might take a few seconds
Successfully copied fastlane to /Users/User/.fastlane/bin

Updating installed gems
Updating fastlane
Fetching: tty-screen-0.5.0.gem (100%)
Successfully installed tty-screen-0.5.0
Fetching: fastlane-2.18.3.gem (100%)
Successfully installed fastlane-2.18.3
Gems updated: fastlane tty-screen
Cleaning up installed gems...
Attempting to uninstall fastlane-2.13.0
Successfully uninstalled fastlane-2.13.0
Clean Up Complete
Detected fastlane is already in your path 🚀
```

**Comment by ohayon** [comment]
Hi everyone! I think there might be two issues going on in here based on different mechanisms of having installed _fastlane_.

@ehorodyski It looks like you may have installed _fastlane_ from the Fabric Mac app, is that right? If so, you should be able to update by opening up the Fabric app again and clicking on the _fastlane_ tab to see that an update is available.

@Redysz it looks like you are all up to date with 2.18.3. Do you know what version you had when you only ran `fastlane update_fastlane`?

**Comment by ehorodyski** [comment]
Sorry, I should have mentioned a while ago that it seems to be working now. Not sure what I did, to be honest. 

@ohayon -- I did not install the Fabric Map app. I installed it from the page where you set up a beta script and you download the `zip` that contains Fastlane within it.

**Comment by ohayon** [comment]
Thanks for following up @ehorodyski ! 🚀
