### ISSUE TITLE
Problem trying to update fastlane

### ISSUE THREAD

**Issue by LudvigOdin** [fastlane/fastlane#824]
Hi! This is a problem I'm having, I can't update fastlane. Any ideas on how to debug and solve this? Thanks! :+1: 

```
#######################################################################
# fastlane 1.38.0 is available. You are on 1.37.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################

1.38.0 Improvements
- Fixed using the wrong output path in the `cert` action
- Fixed bug in the `Fastfile` template file
- Enforcement of https URLs for the `install_xcode_plugin` action
- Added code coverage option for `xcodebuild` action
- Other smaller improvements

Update using 'sudo gem update fastlane'
LudvigHstvikMBP:test ludvig$ sudo gem update fastlane
Updating installed gems
Nothing to update
LudvigHstvikMBP:test ludvig$
```

**Comment by KrauseFx** [comment]
Try doing it without `sudo`. How did you install `fastlane`?

**Comment by ohwutup** [comment]
Im going to close this issue as it's been a while. @LudvigOdin, please reopen this if you're still having an issue! Thanks! :computer:

**Comment by nezhyborets** [comment]
I'm having similar issue
![2016-07-12 4 50 58](https://cloud.githubusercontent.com/assets/2803931/16769300/dba5b3ae-4850-11e6-879c-71845465031b.png)

**Comment by ohwutup** [comment]
Hey @nezhyborets, any chance you could share with me what prints out in your terminal when you do `which fastlane` and `which ruby`?

Thanks! 🐙

**Comment by nezhyborets** [comment]
Sure
> oleksiis-imac:WinePicker Alexei$ which fastlane
> /usr/local/bin/fastlane
> oleksiis-imac:WinePicker Alexei$ which ruby
> /usr/bin/ruby

**Comment by ohwutup** [comment]
Ah, did you install fastlane via the Fabric Mac app?

**Comment by nezhyborets** [comment]
Yes i did, should i use Fabric App to update Fastlane?

**Comment by ohwutup** [comment]
Yeah! That would be great!

**Comment by nezhyborets** [comment]
Thanks! That worked

**Comment by SameerMB** [comment]
It worked for me when I ran "gem update fastlane" i.e. without sudo.

**Comment by vmalakhovskiy** [comment]
Also you could try to run `bundle update` - that should fix the problem too.

**Comment by vmalakhovskiy** [comment]
If you have `Gemfile` in project bundle - try to use `bundle update` - that will fix the problem.

**Comment by rlam3** [comment]
I'm having a similar issue...

tried installing fastlane with fabric app by results in version 1.110.0.

```
$$ gem update fastlane
Updating installed gems
Nothing to update
$$ which fastlane
/usr/local/bin/fastlane
$$ which ruby
/usr/local/bin/ruby
```

Would like to know how to properly set this up. Thanks!

**Comment by ohwutup** [comment]
Thanks for the report @rlam3! We will get this fixed up right away!

**Comment by ohwutup** [comment]
@rlam3, could you give updating via the Fabric app another shot? Apologies for the interruption! 🚀 🐙

**Comment by rlam3** [comment]
@ohwutup was able to update to newest version of fastlane but when i went back to check the version... I'm getting the following. I'm not sure if this is okay or not... Would love to hear your thoughts on the load error issue. Or should I just ignore it...?

```bash
ruby: No such file or directory -- /usr/local/lib/fastlane_lib/bundle_update_checker.rb (LoadError)
fastlane 2.2.0
```

**Comment by ohwutup** [comment]
ah! thats a little bug. if you wouldn't mind ignoring it for the moment, i will get a fix going soon!

**Comment by ohwutup** [comment]
hey @rlam3, you should be able to fix this by uninstalling fastlane from the Fabric app and then reinstalling. let us know if any other problems come up! 🚀

**Comment by rlam3** [comment]
@ohwutup you da bauss!!

**Comment by rlam3** [comment]
looks like fabric app isn't getting latest updates to upgrade fastlane again... is anybody else having the same issue?

**Comment by maxydon** [comment]
I am! fabric is getting the 2.5 version not the 2.8 one.

**Comment by ohwutup** [comment]
We just deployed a new version so you should be able to get the most recent version of _fastlane_ from the Fabric Mac app. 🚀

**Comment by Bunn** [comment]
@ohwutup I installed fastlane yesterday via brew
`brew cask install fastlane`

Today I'm seeing this:
 fastlane 2.11.0 is available. You are on 2.10.0.
 It is recommended to use the latest version.
 Please update using `sudo gem update fastlane`.

I tried with and without sudo as some comment above suggested:

Bunn-MBP:Scheduler bunn$ sudo gem update fastlane
Password:
Updating installed gems
Nothing to update

Bunn-MBP:Scheduler bunn$ gem update fastlane
Updating installed gems
Nothing to update

ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]

**Comment by ohwutup** [comment]
Thanks for letting us know about the issue @Bunn !! We will work on getting the messaging fixed to make sure that people don't get such confusing messages in the future! 🚀
