### ISSUE TITLE
Add option to specify version of cocoapods to use

### ISSUE THREAD

**Issue by alexanderjrobinson** [fastlane/fastlane#825]
CocoaPods often introduces breaking changes and it would be helpful to have the option to specify the version of CocoaPods as a parameter in the cocoapods line of the Fastfile.

Command line syntax for specify CocoaPods version is the following:

`pod _0.38.2_ install`

**Comment by KrauseFx** [comment]
Sure, you should use a `Gemfile` to do that. More information about this here: https://guides.cocoapods.org/using/a-gemfile.html

You commit the `Gemfile` and then use `cocoapods(use_bundle_exec: true)`
