### ISSUE TITLE
Environment issue

### ISSUE THREAD

**Issue by LargeShrimp** [fastlane/fastlane#8253]
### Issue Description

When i run `fastlane init` and It show error 。The error message is as follows

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
Could not receive latest API key from iTunes Connect, this might be a server issue.
An error occured during the setup process. Falling back to manual setup!

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.2                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/rubies/ruby-2.2.2/bin/fastlane       |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.2/lib                |
| OpenSSL Version     | OpenSSL 1.0.1j 15 Oct 2014                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.15.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.2        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
</details>

*generated on:* **2017-02-15**
</details>

 At last , I have upgrade openssl, but it may be not work. Please help me , Thanks in advance!

#openssl version
OpenSSL 1.0.2j  26 Sep 2016

**Comment by mfurtak** [comment]
SSL errors can be caused by various components on your local machine. The best solution is to use the self-contained _fastlane_ version which ships with a bundled OpenSSL, Ruby and all gems, so you don't depend on system libraries.

 - Use One-Click-Installer:
    - download _fastlane_ at https://download.fastlane.tools
    - extract the archive and double click the `install`
- Use Homebrew
    - update brew with `brew update`
    - install fastlane:
        - `brew cask install fastlane`

You can also install a new version of Ruby

- Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
- If you use system Ruby:
    - Run `brew update && brew install ruby`
- If you use rbenv with ruby-build:
    - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
    - Run `rbenv global 2.3.1` to make it the new global default Ruby version
- If you use rvm:
    - First run `rvm osx-ssl-certs update all`
    - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`

**Comment by LargeShrimp** [comment]
@mfurtak Thanks! It is work for me  When I uninstall fastlane and re-install it with  installer Script.
Although it was slow to log in, it was a success.

**Comment by mfurtak** [comment]
Glad you're back up and running! 🚀
