### ISSUE TITLE
Feature Request:  Stepwise debugging of Fastfile

### ISSUE THREAD

**Issue by jeeftor** [fastlane/fastlane#8255]
I'm doing some funky stuff with fastlane, a bunch of sed commands and various custom code i've written.  It would be SUPER helpful if there was a way to have a step through debugging.

`fastlane --debug`
* Hit Enter each time to execute a command
* Ability to add a "breakpoint" into the `Fastfile` that would cause the debug mode to break there and prompt the user to hit enter from that point.

I think this would be pretty useful for some folks.

**Comment by jeeftor** [comment]
Thank @fastlane-bot but this is a feature request :)

**Comment by orta** [comment]
@jeeftor if you include `pry` in your Gemfile ( or do a `gem install pry` if you're not )

Then you can add 

```ruby
require 'pry'
binding.pry
```

anywhere in your Fastfile and you'll get into a REPL.

**Comment by KrauseFx** [comment]
Yes, using `pry` is probably the easiest way currently 👍  Does that help you for your use case?

**Comment by jeeftor** [comment]
I couldn't get it to work but that's ok for now :) I'll give it another shot Monday

**Comment by ohayon** [comment]
Going to close this issue for now as there is a workable solution, @jeeftor please let us know if you have any more questions regarding stepping using `pry`. I have also been using https://github.com/pry/pry-stack_explorer as of lately for deeper inspection into running code. 🐙 🚀
