### ISSUE TITLE
gym not respecting the derived_data_path param, still writes to default xcode location

### ISSUE THREAD

**Issue by stonedauwg** [fastlane/fastlane#8259]
### New Issue Checklist

- [√] Updated fastlane to the latest version
- [√] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
NOTE: [Link to SO article](http://stackoverflow.com/questions/42260061/fastlane-gym-specify-derived-data-path-but-still-creates-deriveddata-in-xcode) I posted as well

When running gym with the derived_data_path param set to a custom path, the xcodebuild command seems to not add the command line switch to force the derived data folder to be set somewhere else, thus I'm left with a DerivedData in the standard default path of ~/Library/Developer/Xcode/DerivedData instead of the custom path I pass to gym.

Note that scan does not seem to have this issue. When passing the same derived_data_path param, it adds the xcodebuild switch for setting the custom dervieddata path

```
15:33:56 
15:33:56 [15:33:56]: -------------------------------------------------
15:33:56 [15:33:56]: --- Step: Verifying required fastlane version ---
15:33:56 [15:33:56]: -------------------------------------------------
15:33:56 [15:33:56]: Your fastlane version 2.17.0 matches the minimum requirement of 2.13.0  ✅
15:33:56 [15:33:56]: ------------------------------
15:33:56 [15:33:56]: --- Step: default_platform ---
15:33:56 [15:33:56]: ------------------------------
15:33:56 [15:33:56]: Driving the lane 'ios validation' 🚀
15:33:56 [15:33:56]: -------------------------------------
15:33:56 [15:33:56]: --- Step: ensure_git_status_clean ---
15:33:56 [15:33:56]: -------------------------------------
15:33:56 [15:33:56]: Git status is clean, all good! 💪
15:33:56 [15:33:56]: -----------------------------
15:33:56 [15:33:56]: --- Step: update_fastlane ---
15:33:56 [15:33:56]: -----------------------------
15:33:56 [15:33:56]: Looking for updates for fastlane...
15:34:03 [15:34:03]: Nothing to update ✅
15:34:03 [15:34:03]: -------------------------------------------
15:34:03 [15:34:03]: --- Step: Switch to ios build_test lane ---
15:34:03 [15:34:03]: -------------------------------------------
15:34:03 [15:34:03]: Cruising over to lane 'ios build_test' 🚖
15:34:03 [15:34:03]: -----------------
15:34:03 [15:34:03]: --- Step: gym ---
15:34:03 [15:34:03]: -----------------
15:34:04 [15:34:04]: $ xcodebuild -list -project ./iPadClientUnifiedFlow.xcodeproj -configuration Enterprise
15:34:05 [15:34:05]: $ xcodebuild clean -showBuildSettings -scheme Store\ \(Enterprise\) -project ./iPadClientUnifiedFlow.xcodeproj -configuration Enterprise
15:34:06 
15:34:06 +----------------------+---------------------------------------------------------------------------+
15:34:06 |                                      Summary for gym 2.17.0                                      |
15:34:06 +----------------------+---------------------------------------------------------------------------+
15:34:06 | scheme               | Store (Enterprise)                                                   |
15:34:06 | clean                | true                                                                      |
15:34:06 | configuration        | Enterprise                                                                |
15:34:06 | export_method        | enterprise                                                                |
15:34:06 | silent               | true                                                                      |
15:34:06 | output_directory     | /Users/mobileci/.jenkins/jobs/UnifiediPad-Validation/builds/85       |
15:34:06 | derived_data_path    | /Users/mobileci/.jenkins/jobs/UnifiediPad-Validation/builds/85/De... |
15:34:06 | archive_path         | /Users/mobileci/.jenkins/jobs/UnifiediPad-Validation/builds/85/Ar... |
15:34:06 | output_name          | StoreUnifiediPad                                                     |
15:34:06 | project              | ./iPadClientUnifiedFlow.xcodeproj                                         |
15:34:06 | destination          | generic/platform=iOS                                                      |
15:34:06 | use_legacy_build_api | false                                                                     |
15:34:06 | buildlog_path        | ~/Library/Logs/gym                                                        |
15:34:06 | xcode_path           | /Applications/Xcode.app                                                   |
15:34:06 +----------------------+---------------------------------------------------------------------------+
15:34:06 
15:34:07 [15:34:07]: ▸ Cleaning iPadClientUnifiedFlow/Store [Enterprise]
15:34:07 [15:34:07]: ▸ Check Dependencies
15:34:08 [15:34:08]: ▸ Clean Succeeded
15:34:08 [15:34:08]: ▸ Building iPadClientUnifiedFlow/Store [Enterprise]
15:34:08 [15:34:08]: ▸ Check Dependencies
15:34:10 [15:34:10]: ▸ Copying Graphics/splash.bmp
```
... etc etc with the compile steps...

### Environment

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.11.0                          |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Is homebrew         | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import "../../Fastfile_master"

#platform :ios do
  ############################################### Lane Overrides ###############################################
  #override_lane :masterlane do |lane, options|
  #end
#end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-settings_bundle | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| slack-notifier                  | 1.5.1        |
| json                            | 1.8.1        |
| thread_safe                     | 0.3.5        |
| tzinfo                          | 1.2.2        |
| activesupport                   | 4.2.7.1      |
| claide                          | 1.0.1        |
| colored                         | 1.2          |
| nanaimo                         | 0.2.3        |
| xcodeproj                       | 1.4.2        |
| rouge                           | 1.11.1       |
| xcpretty                        | 0.2.4        |
| terminal-notifier               | 1.7.1        |
| unicode-display_width           | 1.1.3        |
| terminal-table                  | 1.7.3        |
| plist                           | 3.2.0        |
| public_suffix                   | 2.0.5        |
| addressable                     | 2.5.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.5.0        |
| babosa                          | 1.0.2        |
| highline                        | 1.7.8        |
| commander                       | 4.4.3        |
| faraday                         | 0.11.0       |
| unf_ext                         | 0.0.7.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20161129 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.6        |
| fastimage                       | 2.0.1        |
| gh_inspector                    | 1.0.3        |
| uber                            | 0.0.15       |
| representable                   | 2.3.0        |
| retriable                       | 2.1.0        |
| mime-types-data                 | 3.2016.0521  |
| mime-types                      | 3.1          |
| hurley                          | 0.2          |
| little-plugger                  | 1.1.4        |
| multi_json                      | 1.12.1       |
| logging                         | 2.1.0        |
| jwt                             | 1.5.6        |
| memoist                         | 0.15.0       |
| os                              | 0.9.6        |
| signet                          | 0.7.3        |
| googleauth                      | 0.5.1        |
| httpclient                      | 2.8.3        |
| google-api-client               | 0.9.22       |
| mini_magick                     | 4.5.1        |
| multi_xml                       | 0.6.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 0.0.4        |
| bundler                         | 1.13.7       |
| faraday_middleware              | 0.11.0       |
| excon                           | 0.55.0       |
| rubyzip                         | 1.2.1        |
| fastlane-plugin-settings_bundle | 1.0.0        |
</details>

*generated on:* **2017-02-15**
</details>

```

**Comment by ohayon** [comment]
Hey @stonedauwg! Thanks for submitting an issue. Would you mind sharing some more of the output from _gym_ with us? _gym_ should be printing out he `xcodebuild` command that it generates to build your project and seeing/running that on its own without _gym_ will help us figure out whats going on. Thanks! 🐙

**Comment by stonedauwg** [comment]
Sorry, after reviewing this I was wrong, gym, like scan, is indeed adding the proper -derivedDataPath flag to xcodebuild. However, in both scan and gym's case, there are **still** build products, folders, etc being created at the ~/Library/Developer/Xcode/DerivedData path _as well as_ the custom path I pass to the derived_data_path param. Is that just normal for xcodebuild then? If so, what is the point of the -derivedDataPath flag?
