### ISSUE TITLE
Deprecation of xcode managed profiles in 2.17.0 

### ISSUE THREAD

**Issue by nonemoreblack** [fastlane/fastlane#8261]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I noticed that the ability to retrieve xcode managed profiles was deprecated in 2.17.0. From the comments in https://github.com/fastlane/fastlane/pull/8251, it would appear this is due to Apple no longer returning them in the latest API. This is a big problem for the way we work, and we won't be able to update as a result (fortunately, as of this morning, 2.16.0 started working again).

It would seem that these profiles must still be fetchable in some way, as xcode must fetch them. The old API is still returning them in 2.16.0. Could retaining this capability be investigated further? If there is no way going forward, we will be forced to change our Apple signing processes, which will be no small task.

Thanks for the quick work on 2.17.0, btw.

**Comment by asfalcone** [comment]
@nonemoreblack Thanks for letting us know that this is an issue for you. We'll try to figure out if there is a way to reliably access the xcode managed provisioning profiles via API. 👍

**Comment by asfalcone** [comment]
This should be fixed in _faslane_ 2.19.0. We reverted to the old behavior and introduced the `SPACESHIP_AVOID_XCODE_API` env variable. You'll want to use the default behavior to retreive the xcode managed profiles but if this API has issues again, you can set SPACESHIP_AVOID_XCODE_API=1 and at least have some functionality 👍. Please give it a try and let me know, thanks!

**Comment by nonemoreblack** [comment]
I installed 2.19.1 and it works perfectly. Thanks so much for fixing this!

**Comment by KrauseFx** [comment]
Great to hear, thanks for confirming @nonemoreblack 👍
