### ISSUE TITLE
Can fastlane change xcversion's the format of name for xcode beta?

### ISSUE THREAD

**Issue by metasmile** [fastlane/fastlane#8264]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

This issue is not telling about a problem. But I request you for changing the naming scheme of the tool "xcode-install (xcversion)" for beta version of xcode. So the example is like below.

```
Current      '8.3 beta 2'
$ xcversion install "8.3 beta 2"

New          '8.3.b2' or '8.3_b2'
$ xcversion install 8.3.b2
```
Confirm please :)

**Comment by metasmile** [comment]
Ya I already know. but 'fastlane env' is not required in this issue.

**Comment by ohayon** [comment]
Hey @metasmile! 👋 I am going to close this issue for _fastlane_ as this would be a better fit for an issue on https://github.com/KrauseFx/xcode-install. 🐙
