### ISSUE TITLE
How can use exist certs with match other than create new certs ?

### ISSUE THREAD

**Issue by tanhuiya** [fastlane/fastlane#8265]
How can use exist certs with match other than create new certs ?

**Comment by tanhuiya** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.2.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.2.3/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.104.0"

default_platform :ios
ENV["USER_NAME"]="chengli@corp-ci.com"
#ENV["LATEST_VERSION"]="40.3"
platform :ios do
  before_all do
#    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan({
      workspace:"ParentAndSchool.xcworkspace",
      scheme:"parent",
      device:"iPhone6s",	
      clean: true
    })
  end
  lane :archive_school do|options|
    increment_build_number(
        build_number: latest_testflight_build_number({
            version: options[:version_number]
        }) + 1,
        xcodeproj: "./jyb_ios_teacher/school/frameworks/runtime-src/proj.ios_mac/school.xcodeproj"
    )
    gym(
    	workspace: "ParentAndSchool.xcworkspace",
	scheme: "school",
	output_directory:"build",
	output_name: "jyb_school.ipa"
    )
    backup_xcarchive(
        destination: "build",
        zip: true
    )
  end
  lane :archive do | options |
    increment_build_number(
        build_number: latest_testflight_build_number({
            version: options[:version_number]
        }) + 2,
        xcodeproj: "./jyb_ios_parent/parent/frameworks/runtime-src/proj.ios_mac/parent.xcodeproj"

    )

    gym(
    	workspace: "ParentAndSchool.xcworkspace",
	scheme: "parent",
	output_directory:"build",
	output_name: "jyb.ipa"
    )
    
  end
  
  lane :testFlight do
#for firwall
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    pilot(
	ipa:"build/jyb.ipa",
	username: "chengli@corp-ci.com",
	skip_waiting_for_build_processing: true
    )
  end

  lane :testFlight_school do
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    pilot(
	ipa:"build/jyb_school.ipa",
	username: "chengli@corp-ci.com",
	skip_waiting_for_build_processing: true
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#app_identifier "com.ci123.jiayuanbao.school" # The bundle identifier of your app
apple_id "chengli@corp-ci.com" # Your Apple email address

team_id "U39HM55PYU"  # Developer Portal Team ID

for_lane :archive do
    app_identifier 'com.ci123.jiayuanbao.parent'
end

for_lane :archive_school do
    app_identifier 'com.ci123.jiayuanbao.school'
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.5.0   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.12.5       |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.2.2      |
| google-api-client         | 0.9.12       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.0       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
</details>


*generated on:* **2017-02-16**
</details>


@fastlane-bot

**Comment by PetrosIchor** [comment]
You can't. Use cert/sigh instead for that workflow.

**Comment by jeff-jk** [comment]
Technically, you could manually encrypt them with the Match repo password then commit & push them to the Match storage repository. You'd have to make sure the naming matches what Match expects. Using the read-only option with Match would not generate new certificates/profiles but it would still fetch your existing certs. I posted steps for manually encrypting in this [comment](https://github.com/fastlane/fastlane/issues/8209#issuecomment-279814710) on #8209 (minus the naming scheme).

**Comment by Lutzifer** [comment]
The use case for this can be, that your team is asked to sign using an external cert and provisioning profile without access to the accounts.
Another usecase is updating match while there are outages in the API, but a manual download is still possible, as was the case in last weeks #8209 

Having an actual import from match for this would be a great addition.

**Comment by PetrosIchor** [comment]
You can use cryptex for this

**Comment by ohayon** [comment]
Hey @tanhuiya, thanks for raising this issue. At the moment using existing certs is not supported as @PetrosIchor mentioned. I am going to close this issue for now as it is a feature request and maybe in the future we will be able to make something like this happen. Thanks again! 🐙 😄
