### ISSUE TITLE
[regression] undefined method `strftime' in match nuke

### ISSUE THREAD

**Issue by rhcpfan** [fastlane/fastlane#8266]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have tried to `nuke` my development certificates and got the following output (error included):

```
[09:38:10]: Fetching certificates and profiles...

+-----------------+------------+-------------+------------+
|        Certificates that are going to be revoked        |
+-----------------+------------+-------------+------------+
| Name            | ID         | Type        | Expires    |
+-----------------+------------+-------------+------------+
| iOS Development | JDQZFQR394 | Development | 2017-02-24 |
| iOS Development | PG6VDHQ6B9 | Development | 2018-02-09 |
| iOS Development | VFW24Y367Q | Development | 2018-02-09 |
| iOS Development | 75A33LX9Q8 | Development | 2018-02-14 |
+-----------------+------------+-------------+------------+


Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/match/lib/match/nuke.rb:99:in `block in print_tables': [!] undefined method `strftime' for "2018-02-09T14:08:36Z":String (NoMethodError)
Did you mean?  strip
Did you mean?  strip
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/match/lib/match/nuke.rb:96:in `collect'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/match/lib/match/nuke.rb:96:in `print_tables'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/match/lib/match/nuke.rb:23:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/match/lib/match/commands_generator.rb:111:in `block (3 levels) in run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/runner.rb:444:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/commander-4.4.0/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/match/lib/match/commands_generator.rb:118:in `run'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/match/lib/match/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/fastlane/lib/fastlane/cli_tools_distributor.rb:49:in `take_off'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.17.0/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

This works ok with `fastlane 2.14.2`

**Comment by serluca** [comment]
I'm having the same issue, here is my fastlane env

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.2                          |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_require 'yaml'
fastlane_require 'ostruct'
fastlane_require 'spaceship'

fastlane_version "2.14.2"

default_platform :ios

platform :ios do
  
  before_all do
    ensure_git_status_clean
    bundle_install
    ensure_xcode_version(version: "8.2.1")
    installDependencies
  end

  desc "Perform tests" 
  lane :test do |options|
    
    scan(
      xcargs: "GCC_PREPROCESSOR_DEFINITIONS='${inherited} TEST=1'",
      scheme: "Research Central",
      code_coverage: true,
      slack_only_on_failure: true,
      skip_slack: false,
      buildlog_path: "#{ENV['CIRCLE_ARTIFACTS']}"
    )

    # Code coverage
    xcov(
      scheme: "Research Central",
      output_directory: "./fastlane/test_output/",
      slack_channel: "#deployments",
      include_targets: "Research Central.app,RCAnalytics.framework,RCCoreData.framework,RCData.framework"
    )  

    # Save artifacts
    rc_copy_artifacts

  end

  desc "Deploy the app to iTunes Connect"
  lane :deployToItunesConnect do

    deploy(
      config: "Release",
      deliver: true
    )

    add_git_tag(
      prefix: 'v'
    )
    push_git_tags

    # Send message on slack
    message = "App submitted to app store"
    slack(
      message: message,
      channel: "#deployments"
    )
  end 

  desc "Send the last deployed build in to internal testflight"
  lane :sendLastBuildToTestFlight do
    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find("co.researchcentral.Research-Central")
    version = app.edit_version

    use_build = version.candidate_builds.first

    version.select_build(use_build)
    version.save!

    train_version = use_build.train_version
    train = app.build_trains[train_version]
    
    train.update_testing_status!(true, "internal", use_build)
end

  desc "Send the last deployed build in review (and to internal testflight)"
  desc "By default the build requires to be released once approved, but it is possible to release it automatically once approved by adding a parameter"
  desc "Usage example: fastlane sendLastBuildInReview"
  desc "Usage example with release automatically: fastlane sendLastBuildInReview automaticRelease:true"
  lane :sendLastBuildInReview do |options|
    automaticRelease =  options[:automaticRelease] ? options[:automaticRelease] : false
    
    sendLastBuildToTestFlight

    deliver(
      submit_for_review: true,
      automatic_release: automaticRelease,
      skip_metadata: true,
      skip_binary_upload: true,
      skip_screenshots: true
    )
  end

  desc "Manually deploy the project with one of the configuration present in the fastlane_config file"
  desc "If the configuration includes crashlytics beta you can specitfy the gruop programmatically"
  desc "Usage example: fastlane deploy config:RCProd crashlytics:true notes:true groups:'RC,ios-team'"
  lane :deploy do |options|
    raise "Config name missing".red unless options[:config]
    configName = options[:config]

    # Make sure current has not got ipa files
    Dir['../*.ipa'].each { |f| File.delete(f) }

    configure(config: configName)
    use_legacy_build_api = options[:config] == "Release" ? false : true

    gym(
      scheme: "Research Central",
      configuration: configName,
      codesigning_identity: "iPhone Distribution: Responsive Labs Ltd (NM2GHR4Q45)",
      include_symbols: true,     
      include_bitcode: false,
      use_legacy_build_api: use_legacy_build_api
    )

    if options[:crashlytics]
      notes = options[:notes] ? fetch_notes : ""
      groups = options[:groups] ? options[:groups] : ""  
      
      crashlytics(
        crashlytics_path: "./Pods/Crashlytics",
        api_token: ENV['Crashlytics_token'],
        build_secret: ENV['Crashlytics_secret'],
        notifications: "true",
        notes: notes,
        groups: groups
      )
    end

    # Updload dsym to crashlytics to symbolicate crashes
    upload_symbols_to_crashlytics({
      api_token: ENV['Crashlytics_token'],
    })
    
    if options[:deliver]
      changelog = YAML.load_file('../CHANGELOG.yml')
      version_number = changelog['changelog'].first['version']
      
      deliver(
        force: true, # Skip the HTML report file verification
        skip_screenshots: true, # Don't upload screenshots
        app_version: version_number
      )
    end

    # Save artifacts
    rc_copy_artifacts

    # Reset the repo
    reset_git_repo(disregard_gitignore:false)
  end

  desc "Invoke this lane to Download or Regenerate the certificates"
  desc "parameters: force_for_new_devices:true to force for new device or set the readonly to false"
  lane :install_certificates do |options|
    # Download and Install the apple certificates
    force_for_new_devices = options[:force_for_new_devices] ? options[:force_for_new_devices] : false; 
    readonly = force_for_new_devices ? false : true;
    
    # Development 
    development = [
    	"co.researchcentral.Research-Central", # Development
    	"co.researchcentral.Research-Central.testing", # RCUAT Dev
    	"co.researchcentral.Research-Central.tests" # Tests
    ]
    match(app_identifier: development, type: "development", force_for_new_devices: force_for_new_devices, readonly: readonly)

    # Ad Hoc
    adHoc = [
    	"co.researchcentral.Research-Central.dev", # RCProd
		"co.researchcentral.Research-Central.testing", # RCUAT
		"co.researchcentral.Research-Central.citiprod", # CitiProd
		"co.researchcentral.Research-Central.citiuat", # CitiUAT
		"co.researchcentral.Research-Central.touch" # RCTP
    ]
    match(app_identifier: adHoc, type: "adhoc", force_for_new_devices: force_for_new_devices, readonly: readonly) 

    # App store
    match(app_identifier: "co.researchcentral.Research-Central", type: "appstore", readonly: readonly) # Release

  end

  desc "Register devices to itunes connect"
  lane :registerDevices do
    
    register_devices( 
      devices_file: "fastlane/devices.txt"
    )

    # Regenerate certificates
    install_certificates(
      force_for_new_devices: true
    )

  end

  desc "Install project dependencies"
  private_lane :installDependencies do
    # Install carthage
    if carthage_cache_exist( bucket: 'rc-ios-cache' )
      UI.message "Using carthage cache".yellow
      carthage_cache_install( bucket: 'rc-ios-cache' )
    else
      UI.message "Cache does not exist, executing carthage install".yellow
      carthage(platform: "iOS")
      UI.message "Updating carthage cache".yellow
      carthage_cache_publish( bucket: 'rc-ios-cache' )
    end

    # Install cocoapdos
    cocoapods
  end

  desc "Configure the xcode project"
  private_lane :configure do |options|
    # Make sure the repo is clean to avoid to configure a weird version of the app
    changelog = YAML.load_file('../CHANGELOG.yml')
    version_number = changelog['changelog'].first['version']
    build_number = changelog['changelog'].first['build']
      
    # Set the project version number and build number
    increment_version_number version_number: version_number
    increment_build_number build_number: build_number

    # Install the badge for the RC PRod and RCUAT app
    case options[:config]
      when "RCProd"
        badge(custom: "fastlane/badge/prod_badge.png")
      when "RCTP"
        badge(custom: "fastlane/badge/prod_badge.png")
      when "RCUAT"
        badge(custom: "fastlane/badge/uat_badge.png")
    end
  end

  private_lane :rc_copy_artifacts do
    # save artifacts in circle-ci
    unless ENV['CIRCLE_ARTIFACTS'].nil?
      copy_artifacts({
        target_path: "#{ENV['CIRCLE_ARTIFACTS']}",
        artifacts: ['./fastlane/test_output/','*.cer', '*.mobileprovision', '*.ipa', '*.dSYM.zip']
      })
    end
  end

  ##############
  # AFTER ALL
  ##############
  error do |lane, exception|

    message = "[#{lane}] Something went wrong with the deployment: #{exception}"
    puts(message)

    if lane.to_s == 'release'
      slack(
        message: message,
        success: false
      )
    end
  end

end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "co.researchcentral.Research-Central" # The bundle identifier of your app
apple_id "luca@researchcentral.co" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                         | Version | Update-Status |
| ------------------------------ | ------- | ------------- |
| fastlane-plugin-carthage_cache | 0.1.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                            | Version      |
| ------------------------------ | ------------ |
| did_you_mean                   | 1.0.0        |
| bundler                        | 1.13.1       |
| io-console                     | 0.4.5        |
| CFPropertyList                 | 2.3.5        |
| i18n                           | 0.8.0        |
| json                           | 1.8.6        |
| minitest                       | 5.10.1       |
| thread_safe                    | 0.3.5        |
| tzinfo                         | 1.2.2        |
| activesupport                  | 4.2.7.1      |
| public_suffix                  | 2.0.5        |
| addressable                    | 2.5.0        |
| aws-sigv4                      | 1.0.0        |
| jmespath                       | 1.3.1        |
| aws-sdk-core                   | 2.7.9        |
| aws-sdk-resources              | 2.7.9        |
| aws-sdk                        | 2.7.9        |
| babosa                         | 1.0.2        |
| fastimage                      | 2.0.1        |
| colored                        | 1.2          |
| highline                       | 1.7.8        |
| commander                      | 4.4.3        |
| dotenv                         | 2.2.0        |
| excon                          | 0.55.0       |
| multipart-post                 | 2.0.0        |
| faraday                        | 0.11.0       |
| unf_ext                        | 0.0.7.2      |
| unf                            | 0.1.4        |
| domain_name                    | 0.5.20161129 |
| http-cookie                    | 1.0.3        |
| faraday-cookie_jar             | 0.0.6        |
| faraday_middleware             | 0.11.0.1     |
| gh_inspector                   | 1.0.3        |
| jwt                            | 1.5.6        |
| little-plugger                 | 1.1.4        |
| multi_json                     | 1.12.1       |
| logging                        | 2.1.0        |
| memoist                        | 0.15.0       |
| os                             | 0.9.6        |
| signet                         | 0.7.3        |
| googleauth                     | 0.5.1        |
| httpclient                     | 2.8.3        |
| hurley                         | 0.2          |
| mime-types-data                | 3.2016.0521  |
| mime-types                     | 3.1          |
| uber                           | 0.0.15       |
| representable                  | 2.3.0        |
| retriable                      | 2.1.0        |
| google-api-client              | 0.9.28       |
| mini_magick                    | 4.5.1        |
| multi_xml                      | 0.6.0        |
| plist                          | 3.2.0        |
| rubyzip                        | 1.2.1        |
| security                       | 0.1.3        |
| slack-notifier                 | 1.5.1        |
| terminal-notifier              | 1.7.1        |
| unicode-display_width          | 1.1.3        |
| terminal-table                 | 1.7.3        |
| tty-screen                     | 0.5.0        |
| word_wrap                      | 1.0.0        |
| claide                         | 1.0.1        |
| nanaimo                        | 0.2.3        |
| xcodeproj                      | 1.4.2        |
| rouge                          | 1.11.1       |
| xcpretty                       | 0.2.4        |
| xcpretty-travis-formatter      | 0.0.4        |
| badge                          | 0.7.1        |
| carthage_cache                 | 0.8.3        |
| fuzzy_match                    | 2.0.4        |
| nap                            | 1.1.0        |
| cocoapods-core                 | 1.2.0        |
| cocoapods-deintegrate          | 1.0.1        |
| cocoapods-downloader           | 1.1.3        |
| cocoapods-plugins              | 1.0.0        |
| cocoapods-search               | 1.0.0        |
| cocoapods-stats                | 1.0.0        |
| netrc                          | 0.7.8        |
| cocoapods-trunk                | 1.1.2        |
| cocoapods-try                  | 1.1.0        |
| escape                         | 0.0.4        |
| fourflusher                    | 2.0.1        |
| molinillo                      | 0.5.6        |
| ruby-macho                     | 0.2.6        |
| cocoapods                      | 1.2.0        |
| fastlane-plugin-carthage_cache | 0.1.1        |
| xcode-install                  | 2.1.1        |
| xcov                           | 1.0.1        |
</details>


*generated on:* **2017-02-16**
</details>

**Comment by asfalcone** [comment]
_fastlane_ 2.17.1 has been released as a hotfix for this issue. please run `fastlane update_fastlane` and let me know if this fixes _match_ for you!

**Comment by LargeShrimp** [comment]
@asfalcone  @lacostej  Perfect, Work for me!
