### ISSUE TITLE
FR: PEM should download the certificate if it already exists

### ISSUE THREAD

**Issue by phanikiranwtc** [fastlane/fastlane#8268]
PEM should have an option to download the push certficate if it already exists. right now it just throws error when we use force option. if not specify force option then it does nothing.

**Comment by asfalcone** [comment]
@phanikiranwtc Can you please share you environment details as requested by the fastlane bot and include the error that is thrown so that we can help you debug this problem. Thank you.

**Comment by KrauseFx** [comment]
That's not possible, as the push certificate needs a private key, which is only stored on your machine. We've actually received this request many times, e.g. https://github.com/fastlane/fastlane/issues/7158#issuecomment-262745836
