### ISSUE TITLE
Can't add credentials in Fastfile

### ISSUE THREAD

**Issue by andrewmcewen** [fastlane/fastlane#8277]
### Issue Description

I am attempting to add credentials in the Fastfile, but there seems to be an error when trying to add the password. The code for add the credentials is
``` 
  lane :ci_credentials do
    id = ENV["FASTLANE_APPLE_ID"]
    pw = ENV["FASTLANE_PW"]
    if id and pw
      sh("bundle exec fastlane-credentials add --username #{id} --password #{pw}")
    end
  end
```

When the Fastfile is executed, I get the following error. 
```
[13:42:52][Step 5/7] +----------------------------+---------------------------------------------------------------------+
[13:42:52][Step 5/7] |                                           Lane Context                                           |
[13:42:52][Step 5/7] +----------------------------+---------------------------------------------------------------------+
[13:42:52][Step 5/7] | DEFAULT_PLATFORM           | ios                                                                 |
[13:42:52][Step 5/7] | PLATFORM_NAME              | ios                                                                 |
[13:42:52][Step 5/7] | LANE_NAME                  | ios ci_full                                                         |
[13:42:52][Step 5/7] | SCAN_DERIVED_DATA_PATH     | ./build                                                             |
[13:42:52][Step 5/7] | SCAN_GENERATED_PLIST_FILES | ["./Build/Logs/Test/D83634FD-4AA6-4BBE-B451-49D8D9635D51_TestSum... |
[13:42:52][Step 5/7] | SCAN_GENERATED_PLIST_FILE  | ./Build/Logs/Test/D83634FD-4AA6-4BBE-B451-49D8D9635D51_TestSumma... |
[13:42:52][Step 5/7] | BUILD_NUMBER               | 507                                                                 |
[13:42:52][Step 5/7] +----------------------------+---------------------------------------------------------------------+
[13:42:52][Step 5/7] [13:42:52]: Exit status of command 'bundle exec fastlane-credentials add --username ios_provisioning@smartamp.com --password *******' was 127 instead of 0.
[13:42:52][Step 5/7] sh: abc123: command not found
[13:42:52][Step 5/7] security: SecKeychainAddInternetPassword <NULL>: The specified item already exists in the keychain.
[13:42:52][Step 5/7] Credential ios_provisioning@smartamp.com:*** added to keychain.
```

NOTE that abc123 is not the actual output, just there as a placeholder because it sends the password

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                | Mac OS X 10.12.2 (16C68)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :ios

developer_identity = "iPhone Developer: iOS Provisioning (ADC4SBH9J6)"
distribution_identity = "iPhone Distribution: SMART Technologies ULC (53V9BC2FMQ)"

#this is a workaround for issues with simulator launching successfully
ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "1"

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs CI Tests"
  lane :ci_test do
    ci_test
  end

  def increment_build_and_version_numbers(options)
#    increment_version_number(
#      version_number: options[:version_number]
#    )

    increment_build_number(
      build_number: options[:build_number]
    )
  end

  def ci_test
# print some debugging info upfront 
  sh('xcodebuild -workspace ../lab.xcworkspace -scheme "lab - No UI Tests" -showBuildSettings')
    scan(
      scheme:'lab - No UI Tests',
      output_directory:'Build/reports',
      output_types:'html, junit',
      derived_data_path:'.',
      code_coverage: true)
    slather(
      proj:'lab.xcodeproj',
      scheme:'lab - No UI Tests',
      ignore: ['Pods/*', '../*'],
      build_directory:'./Build',
      output_directory:'./Build/reports/coverage',
      html: true,
      verbose: true)
    slather(
      proj:'lab.xcodeproj',
      scheme:'lab - No UI Tests',
      ignore: ['Pods/*', '../*'],
      build_directory:'./Build',
      output_directory:'./Build/reports/coverage',
      cobertura_xml: true,
      verbose: true)
  end

  desc "Runs all the tests"
  lane :test do
    snapshot
  end
  
  desc "Creates the ad-hoc ipa for the ci server"
  lane :ci_adhoc do |options|
    increment_build_and_version_numbers(options)
    ci_credentials
    sigh(adhoc:true,
         skip_certificate_verification:true,
         output_path:'./Build')
     ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
     gym(workspace: 'lab.xcworkspace',
         export_method:'ad-hoc',
         scheme:'lab', 
         output_directory:'./Build',
         output_name:'Classlab',
         use_legacy_build_api:true,
         include_symbols:true)
  end

  desc "creates appium_ipa only" 
  lane :appium_ipa do
     ci_credentials
     sigh(development:true,
           skip_certificate_verification:true,
           output_path:'./Build')
     ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
     puts lane_context[SharedValues::SIGH_UDID];
     gym(workspace: 'lab.xcworkspace',
            scheme:'lab', 
            export_method: 'development',
            output_directory:'./Build',
            use_legacy_build_api:true,
            output_name:'Classlab-Appium',
            xcargs:"GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS LAB_FORCE_DEV_ENVIRONMENT=1'")

     resign(ipa:'./Build/Classlab-Appium.ipa',
           signing_identity: developer_identity)

  end
  
  desc "Creates the simulator app for appium testing"
  lane :ci_appium_simulator do
      abs_dir = Dir.pwd
      dir = "#{abs_dir}/../Build/Sim"
      derivedData = "#{abs_dir}/../DerivedData"
      
      puts dir
  
      xcodebuild(build:true,
                scheme:'lab',
                workspace:'lab.xcworkspace',
                sdk: 'iphonesimulator9.3',
                arch: 'i386',
                verbose: true,
                configuration: 'Debug',  
                build_settings: {
                    'SYMROOT' => dir,
                    'DSTROOT' => dir,
                    'GCC_PREPROCESSOR_DEFINITIONS' => '$GCC_PREPROCESSOR_DEFINITIONS LAB_FORCE_DEV_ENVIRONMENT=1'
                }
                );
    # dest = "-destination 'platform=iOS Simulator,name=iPad Air'"
    # build_dir = "CONFIGURATION_BUILD_DIR=$(pwd)/../Build/Sim"
    # env = "GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS LAB_FORCE_DEV_ENVIRONMENT=1'"
    # #sh("xcodebuild -workspace ../lab.xcworkspace -scheme lab -sdk iphonesimulator #{dest} #{build_dir} #{env}")
    sh("(cd ../Build/Sim/Debug-iphonesimulator && zip -r Classlab.zip Classlab.app)")
    sh("mv ../Build/Sim/Debug-iphonesimulator/Classlab.zip ../Build/Classlab.zip")
  end 

  lane :ci_full do |options|
    ci_test
    ci_release(options)
    beta
    ci_adhoc
    ci_appium_simulator
    appium_ipa
  end
  
  desc "Creates the release build for the ci server"
  lane :ci_release do |options|
    increment_build_and_version_numbers(options)
    ci_credentials
    sigh(skip_certificate_verification:true,
        provisioning_name:'LAB Release',
        output_path:'./Build')
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    gym(workspace: 'lab.xcworkspace',
        scheme:'lab', 
        output_directory:'./Build',
        output_name:'Classlab-Release',
        use_legacy_build_api:true,
        include_symbols:true,
        xcargs:"GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS LAB_FORCE_PROD_ENVIRONMENT=1'")
               
    hockey(
      api_token:          '1b64582421b04eb380e9179c3b2370c1',
      public_identifier:  'bb2d4ef22e144396bd59e3ac47da7a08',
      release_type:       '0',
      upload_dsym_only:   true,
      notes:              '',
      notify:             '0',
      status:             '1',
    )         
  end

  lane :ci_credentials do
    id = ENV["FASTLANE_APPLE_ID"]
    pw = ENV["FASTLANE_PW"]
    if id and pw
      sh("bundle exec fastlane-credentials add --username #{id} --password #{pw}")
    end
  end

  lane :ci_tf_credentials do
    id = ENV["FASTLANE_PILOT_ID"]
    pw = ENV["FASTLANE_PILOT_PASSWORD"]
    if id and pw
      sh("bundle exec fastlane-credentials add --username #{id} --password #{pw}")
    end
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ci_tf_credentials
    pilot(
      username:ENV["FASTLANE_PILOT_ID"],
      ipa:"Build/Classlab-Release.ipa",
      skip_waiting_for_build_processing:true
      )
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    #snapshot
    #desc "** Full Markdown** Support: `code`"
    # sigh
    #gym # Build your app - more options available
    # deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.smarttech.lab" # The bundle identifier of your app
apple_id ENV["FASTLANE_APPLE_ID"]

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.4       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-02-16**
</details>

**Comment by mfurtak** [comment]
Is it possible that you have non-alphanumeric characters in your password that the shell is interpreting? If so, try adding:

```ruby
require 'shellwords'
```

to the top of your file, and change your command to have `--password #{pw.shellescape}`.

That said, even if this works, this will still be less than great, as it is showing your password in your CI logs. 😞 

There may be an easier way around all this - what problem is shelling out to `fastlane-credentials` solving for you?

**Comment by andrewmcewen** [comment]
What would be the easier way around all this? There's no particular problem that shelling out `fastlane-credentials` is solving.

**Comment by KrauseFx** [comment]
If you really want to do this, you can use the following code:

```ruby
CredentialsManager::AccountManager.new(user: "username", password: "password").add_to_keychain
```
I haven't tried that code, but it might work. Look into the `account_manager.rb` class for more information 👍 

However I'd strongly recommend to use `FASTLANE_PASSWORD` and `FASTLANE_USER` directly instead of manually interacting with the Keychain.

**Comment by andrewmcewen** [comment]
Fixed the issue last week with @mfurtak's suggestion
