### ISSUE TITLE
replacing the deprecated ipa

### ISSUE THREAD

**Issue by tcurdt** [fastlane/fastlane#8279]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to upload an ipa from the command line to itunes and to hockey (without using the full fastlane setup).

`ipa` is deprecated but I don't see how to use the new successors to do the very same job. This was pretty self explanatory:

```
  ipa distribute:hockeyapp
  --token                     ""
  --identifier                ""
  --file                      ""
  --dsym                      ""
  --notes                     ""
  --commit-sha                ""
  --build-server-url          ""
  --repository-url            ""

  ipa distribute:itunesconnect
  --file      ""
  --apple-id  ""
  --warnings
```

but with `fastlane deliver` for example you have

```
    --team_id
    --team_name
    --dev_portal_team_id
    --itc_provider
```
and it leaves me wondering what to use when. They seem to be all for team selection.

Then the difference of `run` vs `submit_build` is all but clear:

```
    run                  Upload metadata and binary to iTunes Connect
    submit_build         Submit a specific build-nr for review, use latest for the latest build
```

Is `run` the actual upload and `submit_build` does not upload - but just submits an existing build?
It's unclear what is actually required for a simple upload and what is not. Is there an example - anywhere?

When trying to upload to hockey

```
$ bundle exec fastlane hockey help
Could not find fastlane in current directory. Would you like to set it up? (y/n)
```

It seems like it needs a full fastlane setup and no longer provides an CLI. It's almost as if just using `curl` is simpler

```
  curl \
    -F "status=2" \
    -F "notify=1" \
    -F "notes=Some new features and fixed bugs." \
    -F "notes_type=0" \
    -F "ipa=@hockeyapp.ipa" \
    -F "dsym=@hockeyapp.dSYM.zip" \
    -H "X-HockeyAppToken: 4567abcd8901ef234567abcd8901ef23" \
    https://rink.hockeyapp.net/api/2/apps/1234567890abcdef1234567890abcdef/app_versions/upload
```

This is basically a cry for better docs - or me not finding them. What am I missing?

**Comment by KrauseFx** [comment]
> I am trying to upload an ipa from the command line to itunes and to hockey (without using the full fastlane setup).
Any reason why you wouldn't use _fastlane_? That's literally what _fastlane_ is designed for to do.

> This is basically a cry for better docs - or me not finding them. What am I missing?
Agreed, docs is definitely something that can be improved. Check out our new [docs.fastlane.tools](https://docs.fastlane.tools) page

> bundle exec fastlane hockey help
To run an action, use `bundle exec fastlane run hockey`, to get its information run `bundle exec fastlane action hockey`

`submit_build` just submits a build and doesn't upload one.

**Comment by tcurdt** [comment]
> Any reason why you wouldn't use fastlane? That's literally what fastlane is designed for to do.

That probably deserves a longer blog post.

Thanks for help with calling the actions - and the documentation link.
Reading it, there are 3(!) ways to upload a build? `deliver`, `pilot` and `testflight`?

I guess I am after the `hockeyapp` and `testflight` actions then. I was using `pilot` before.

**Comment by KrauseFx** [comment]
That's correct, however `testflight` is just an alias for `pilot` 👍 

> That probably deserves a longer blog post.

I'd love to hear more, I really want to fix whatever is holding you back from using it.

**Comment by tcurdt** [comment]
> I'd love to hear more, I really want to fix whatever is holding you back from using it.

Well, I was using it before. I can send you a link to the post once finished. Or ping me if you are in Berlin again.

So with `bundle exec fastlane action hockey` I am getting the keys - but how would I specify them on the command line for `bundle exec fastlane run hockey`? Are the `env` variables the only way?

```
FL_HOCKEY_API_TOKEN=foo bundle exec fastlane run hockey
```

**Comment by tcurdt** [comment]
I found https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md

Given that his works

```
bundle exec fastlane run notification message:"message" title:"title"
```

I assume it should be along the lines of

```
bundle exec fastlane run hockey api_token:"foo"
```

**Comment by asfalcone** [comment]
yep key:value should be all you need to run one off actions on the command line @tcurdt. 

Does this solution work for you? Can we close out this issue?

**Comment by tcurdt** [comment]
Yes, I worked it all out.
