### ISSUE TITLE
telegram action for fastlane

### ISSUE THREAD

**Issue by sroik** [fastlane/fastlane#8283]
telegram action for fastlane

**Comment by mfurtak** [comment]
_fastlane_ is not looking to add more actions right now, sorry!

https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md#new-actions

If you'd like to explore building a telegram action for _fastlane_ please check out our plugins guide here:

https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md#plugins
