### ISSUE TITLE
Pod install ssl fail.

### ISSUE THREAD

**Issue by dzan** [fastlane/fastlane#8284]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I try the following things everything works fine;

- Manually perform pod install.
- Manually execute the curl command.
- Use the default curl manually (instead of the PHP one, PATH issue)

So I think this must have something to do with fastlane or/and its ruby environment.

```
/Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/interface.rb:146:in `user_error!': [!] Exit status of command 'pod install' was 1 instead of 0. (FastlaneCore::Interface::FastlaneError)
Analyzing dependencies
Downloading dependencies
Installing Firebase 3.12.0 (was 3.10.0)

[!] Error installing Firebase
[!] /usr/local/php5/bin/curl -f -L -o /var/folders/l4/k30c_qr12vn5wbc90b0m6xcr0000gn/T/d20170217-94916-1pf6tjp/file.tgz https://dl.google.com/dl/cpdc/cde07a14df33792c/Firebase-3.12.0.tar.gz --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (51) SSL: certificate verification failed (result: 5)

        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/helper/sh_helper.rb:55:in `sh_control_output'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/helper/sh_helper.rb:10:in `sh'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/cocoapods.rb:27:in `run'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `chdir'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:24:in `block (2 levels) in parsing_binding'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:259:in `call'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:259:in `execute_flow_block'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/fastlane/lib/fastlane/cli_tools_distributor.rb:63:in `take_off'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.17.1/bin/fastlane:15:in `<top (required)>'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/bin/fastlane:22:in `load'
        from /Users/me/.fastlane/bin/fastlane_lib/bundle/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                            |
| ------------------- | ------------------------------------------------ |
| OS                  | 10.11.6                                          |
| Ruby                | 2.2.4                                            |
| Bundler?            | false                                            |
| Git                 | git version 2.9.2                                |
| Installation Source | ~/.fastlane/bin/fastlane_lib/bundle/bin/fastlane |
| Host                | Mac OS X 10.11.6 (15G31)                         |
| Ruby Lib Dir        | ~/.fastlane/bin/fastlane_lib/bundle/lib          |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained        | true                                             |
| Is homebrew         | false                                            |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version       | 8.2.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.6        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 0.2.6        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-02-17**
</details>

**Comment by mfurtak** [comment]
Hi @dzan 👋 

SSL errors can be caused by various components on your local machine. The best solution is to use the self-contained _fastlane_ version which ships with a bundled OpenSSL, Ruby and all gems, so you don't depend on system libraries.

 - Use One-Click-Installer:
    - download _fastlane_ at https://download.fastlane.tools
    - extract the archive and double click the `install`
- Use Homebrew
    - update brew with `brew update`
    - install fastlane:
        - `brew cask install fastlane`

You can also install a new version of Ruby

- Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`
- If you use system Ruby:
    - Run `brew update && brew install ruby`
- If you use rbenv with ruby-build:
    - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`
    - Run `rbenv global 2.3.1` to make it the new global default Ruby version
- If you use rvm:
    - First run `rvm osx-ssl-certs update all`
    - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`
