### ISSUE TITLE
Setup Match for multiple projects in same git repo

### ISSUE THREAD

**Issue by Wiingaard** [fastlane/fastlane#8285]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description

I've have been using match for a while with a single app, and now I'm trying to set it up for a second app on the same team. I created a seperate Match Repo, looking like this: https://github.com/DonkeyRepublic/Match.git
I user this URL as the "git_url" in the first app's Matchfile. If you the same git_url for the second App, the certs and profiles will be overwritten. So I tried to make subfolders within my git repo, and use those as the git_url. The git_url for the second apps Matchfile becomes this: https://github.com/DonkeyRepublic/Match/tree/master/ios_rider.
When I run this I get "Exit status: 128. Error cloning certificates repo, please make sure you have read access to the repository you want to use". My suspicion is that it needs to have a .git-url as git_url, but I don't know how to do this with two different project. I all the official documentation is url's like this are used: 
`git_url "https://github.com/fastlane/fastlane/tree/master/certificates"`

##### Complete output when running fastlane, including the stack trace and command used

fastlane match development
[15:01:13]: Successfully loaded '/Users/Martin/Git/donkey_republic_ios/DonkeyRepublic/fastlane/Matchfile' 📄

+----------------+---------------------------------------------------------------+
|                       Detected Values from './Matchfile'                       |
+----------------+---------------------------------------------------------------+
| git_url        | https://github.com/DonkeyRepublic/Match/tree/master/ios_rider |
| app_identifier | com.donkeyrepublic.DonkeyRepublic                    |
| username       | xxxx@xx.com                                        |
+----------------+---------------------------------------------------------------+

+-----------------------+---------------------------------------------------------------+
|                               Summary for match 2.17.1                                |
+-----------------------+---------------------------------------------------------------+
| git_url               | https://github.com/DonkeyRepublic/Match/tree/master/ios_rider |
| app_identifier        | com.donkeyrepublic.DonkeyRepublic                    |
| username              | xxxx@xx.com                                        |
| type                  | development                                                   |
| git_branch            | master                                                        |
| keychain_name         | login.keychain                                                |
| readonly              | false                                                         |
| team_id               | 554248M85F                                                    |
| verbose               | false                                                         |
| force                 | false                                                         |
| skip_confirmation     | false                                                         |
| shallow_clone         | false                                                         |
| force_for_new_devices | false                                                         |
| skip_docs             | false                                                         |
| platform              | ios                                                           |
+-----------------------+---------------------------------------------------------------+

[15:01:13]: Cloning remote git repo...
Cloning into '/var/folders/kw/8wlmhgmj6gn478_xyx9d_n0h0000gn/T/d20170217-11758-u3mmmp'...
remote: Not Found
fatal: repository 'https://github.com/DonkeyRepublic/Match/tree/master/ios_rider/' not found
[15:01:14]: Exit status: 128
[15:01:14]: Error cloning certificates repo, please make sure you have read access to the repository you want to use
[15:01:14]: Run the following command manually to make sure you're properly authenticated:
[15:01:14]: $ git clone 'https://github.com/DonkeyRepublic/Match/tree/master/ios_rider' '/var/folders/kw/8wlmhgmj6gn478_xyx9d_n0h0000gn/T/d20170217-11758-u3mmmp'
[15:01:14]: 🔒  Successfully encrypted certificates repo

[!] Error cloning certificates git repo, please make sure you have access to the repository - see instructions above

### Environment

*`fastlane env`:*

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:
*I removed the fastlane files from this dump* 

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-02-17**
</details>

**Comment by PetrosIchor** [comment]
Sounds like you need to use branches.  I work with ~18 apps and use a single repository for both android (cryptex) and iOS (match).  To accomplish this, I use branching per platform + app.  

If you want to try this, create branches for each app you want to store match signing credentials. Then add the `git_branch` value to your Matchfile.  If you're not using the Matchfile (I'm not) simply add `git_branch: '$branch'` as a parameter to `match()` in your Fastfile.  

For more information/options available to match, run `fastlane action match`.

**Comment by Lutzifer** [comment]
Multiple projects for the same User and Team should work fine.
If you use different Users and/or Teams, you should use additional branches.

**Comment by kskrishnan** [comment]
I also experience this issue. I have one App ID, that is set-up for both ios & tvos. In my fastlane lane, I first run match for ios and then for tvos. What happens is - the tvos profiles overwrites the ios profiles. 

Do you suggest creating separate branches for iOS & tvOS, if the App IDs are the same?

**Comment by Dzamir** [comment]
I have the same issue. 

If I use match for only one project it works fine, but if I start using it in a second project it tries to creates a new certificate, even if I already have a valid certificate in git repository that was created for the first app.
