### ISSUE TITLE
'deliver'; Allow 'Use 4-Inch Display' override when delivering screenshots or improve error warning

### ISSUE THREAD

**Issue by SpacyRicochet** [fastlane/fastlane#8306]
Apple allows you to override the size for 3.5-inch display with only supplying screenshots for 4-inch displays. 

<img width="1061" alt="screen shot 2017-02-20 at 11 10 09" src="https://cloud.githubusercontent.com/assets/904596/23120791/1415d1f8-f75e-11e6-9731-523528746792.png">

However, if you do not have this enabled, you get the following warning from `deliver`;

```
 [!] The request could not be completed because:
	3.5-inch display must be 960x640, 960x600, 640x960 or 640x920 pixels, at least 72 DPI, in the RGB color space, and in the JPG or PNG format. 3.5-inch display must be 960x640, 960x600, 640x960 or 640x920 pixels, at least 72 DPI, in the RGB color space, and in the JPG or PNG format. 3.5-inch display must be 960x640, 960x600, 640x960 or 640x920 pixels, at least 72 DPI, in the RGB color space, and in the JPG or PNG format. 3.5-inch display must be 960x640, 960x600, 640x960 or 640x920 pixels, at least 72 DPI, in the RGB color space, and in the JPG or PNG format.
```

After enabling this, `deliver` works as expected.

---

It would be good to either;

* Allow `deliver` to adjust this option by itself, if it notices that 3.5-inch screenshots are missing.
* Improve the request error description with a message telling the user that the option can be enabled manually in iTunes Connect.

**Comment by KrauseFx** [comment]
Hey @SpacyRicochet, sorry for not coming back earlier. Do I understand correctly that you don't have those screenshots as _snapshot_ doesn't run on 3.5" devices?
