### ISSUE TITLE
Two apps, same team: Certificate (stored in your git repo) is not available on the Developer Portal

### ISSUE THREAD

**Issue by monotv** [fastlane/fastlane#8308]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am kind of stuck in a loop:

I have two iOS apps (A, B) in the same team. Each app has its own git for certificates (I use Match). Lets say I start with a clean state on the dev portal: When I build app A with Fastlane and want to build app B afterwards, Match tells me it can't find the certs from the git for B on the portal and I can only nuke whats there. Next time I want to build app A Match tells me it can't find the certs from the git for A (because I had to nuke them before) and if I want to nuke whats there. This continues each time I want to build app A or B, possibly messing with TestFlight builds and whatnot.

How can I get match to manage certs for two different apps in the same team with each app having its own cert git?

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G1212)                  |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
xxx
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# iOS
app_identifier "xxx" # The bundle identifier of your app
apple_id "xxx" # Your Apple email address
team_id "xxx"  # Developer Portal Team ID

# Android
json_key_file "xxx" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "xxx" # You Android app package

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.12.5       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.2.2      |
| google-api-client         | 0.9.12       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.0       |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
</details>

*generated on:* **2017-02-20**
</details>

**Comment by PetrosIchor** [comment]
Search through the issues board for Fastlane.  There are dozens, if not hundreds, of signing related questions.  Without more information regarding your Fastfile, apps configuration, and usage of Match it's difficult to pinpoint a solution. 

That said, you should try using different branches for your signing repo.  Personally, I have a variety of both in-house and third party apps that need signed.  Some apps share the same apple account or the same team or even have no commonality.   For each app I simple use a different branch with match.  In my case, this removed any possibility for signing conflicts.  Since each apps assets are defeated, they don't have the opportunity to pollute one another.

**Comment by monotv** [comment]
Thanks. The issue solved itself in the meantime. No idea or suggestion why so I can not give a solution for someone who has a similar problem, sorry.
