### ISSUE TITLE
Is it possible to only  upload apk and save it as draft version in playstore with Supply command

### ISSUE THREAD

**Issue by Sandeeprelease** [fastlane/fastlane#8313]
I recently started to use fastlane for automating the upload process of apk to playstore 
I always wanted to have an option with "supply " action which would just upload the apk to playstore and  saved it as draft version to the  track selected instead of directly publishing the app to the track selected 

  lane :upload_beta do
      supply(
      apk:"outputApks/release13.apk",
      track:"beta"
)

Checked the supply  action help and could not find a parameter that would let me do  it
I also tried editing the Permissions of JSON key generated  from Release Manager to Product Lead (as Product lead role only had access to create/update version to draft and not publish) but running supply command throws an "Unauthorized error"

 **Can some one provide if there is an existing option  just to upload the apk as a draft version?**

16:37:43]: -------------------------------------------------
[16:37:43]: --- Step: Verifying required fastlane version ---
[16:37:43]: -------------------------------------------------
[16:37:43]: Your fastlane version 2.17.1 matches the minimum requirement of 1.111.0  ✅
[16:37:43]: ------------------------------
[16:37:43]: --- Step: default_platform ---
[16:37:43]: ------------------------------
[16:37:43]: Driving the lane 'android upload_beta' 🚀
{"message":"success"}[16:37:43]: --------------------
[16:37:43]: --- Step: supply ---
[16:37:43]: --------------------

+-------------------------+------------------------------------------------------------------------+
|                                    Summary for supply 2.17.1                                     |
+-------------------------+------------------------------------------------------------------------+
| apk                     | outputApks/release13.apk                                               |
| track                   | production                                                             |
| rollout                 | 0.5                                                                    |
| package_name            | com.sundeepgurram.releasetest                                          |
| metadata_path           | ./fastlane/metadata/android                                            |
| json_key                | /Users/sundeep.gurram/Desktop/test_app/Google Play Android Develope... |
| skip_upload_apk         | false                                                                  |
| skip_upload_metadata    | false                                                                  |
| skip_upload_images      | false                                                                  |
| skip_upload_screenshots | false                                                                  |
| validate_only           | false                                                                  |
+-------------------------+------------------------------------------------------------------------+

[16:37:45]: Preparing to upload for language 'en-US'...
[16:37:45]: Uploading image file ./fastlane/metadata/android/en-US/images/icon.png...
[16:37:50]: Preparing apk at path 'outputApks/release13.apk' for upload...
[16:37:53]: Updating track 'production'...
[16:37:54]: Uploading all changes to Google Play...
sh: body: No such file or directory
+------------------+---------------------+
|              Lane Context              |
+------------------+---------------------+
| DEFAULT_PLATFORM | android             |
| PLATFORM_NAME    | android             |
| LANE_NAME        | android upload_beta |
+------------------+---------------------+
[16:37:56]: Unauthorized

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by Sandeeprelease** [comment]
@fastlane-bot  updated the fastlane output

**Comment by asfalcone** [comment]
@Sandeeprelease I don't believe this is currently supported. If it is possible with the [ruby api](https://github.com/google/google-api-ruby-client) that we use, we'd love to see a PR for this. Going to close and mark as a feature request 👍
