### ISSUE TITLE
Snapshots: If a test fails why recompile and all tests rerun?

### ISSUE THREAD

**Issue by ergunkocak** [fastlane/fastlane#8314]
### New Issue Checklist

- [+] Updated fastlane to the latest version
- [-] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When just one test fails retry parameter causes to recompile the whole project and rerun all the tests. 

Is it possible to rerun just the failed ones? If there would be a parameter for this it would be great.

**Comment by ergunkocak** [comment]
It could be better in my opinion at least to have a flag for not to recompiling

**Comment by KrauseFx** [comment]
I'd have to look into this, but I'm pretty sure that the compiling happens as part of running the tests. It should be using the build cache
