### ISSUE TITLE
fish: Unknown command 'fastlane'

### ISSUE THREAD

**Issue by chanricle** [fastlane/fastlane#8316]
### Environment
macOS 10.12.2
Xcode 8.2.1
Shell: fish

### Issue Description
When I typing `fastlane ⏎` in Fish shell terminal, I got message: `fish: Unknown command 'fastlane'`.

### Checklist

- [x] xcode-select --install
- [x] Reinstall fastlane successful. `brew cask reinstall fastlane`
- [x] close Terminal and reopen.

**Comment by KrauseFx** [comment]
How did you fix the issue?

**Comment by chanricle** [comment]
@KrauseFx Fish shell $PATH not include `~/.fastlane/bin/`, so unknown command 'fastlane'.

I config `~/.config/fish/config.fish` file:

~~~ 
# Fastlane path
set PATH {$HOME}/.fastlane/bin/ $PATH
~~~

Then, it's worked.
