### ISSUE TITLE
No certificate matching '' for team '

### ISSUE THREAD

**Issue by oscarg798** [fastlane/fastlane#8317]
I keep getting this error although i do have the certificate installed. it fails trying to execute gym command.

Any help would be much appreciated 

No certificate matching '' for team '':  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.2                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'faraday'
Faraday::Utils.default_params_encoder = Faraday::FlatParamsEncoder

lane :in_house do

  produce(
    username: 'admin@knomatic.com',
    app_identifier: 'com.knomatic.velocity.615c107e.CustomForm.8303140c',
    app_name: 'BM Test',
    app_version: '1.00',
    sku: '1487680133',
    language: 'English',
    team_id: 'XXXXXXX',
    skip_itc: true
  )

  profile_udid = sigh(
    username: 'admin@knomatic.com',
    app_identifier: 'com.knomatic.velocity.615c107e.CustomForm.8303140c',
    team_id: 'XXXXXX',
    cert_id: 'XXXX',
    provisioning_name: 'BM Test Provisioning Profile',
    output_path: '/tmp'
  )
  ENV["VELOCITY_PROFILE_UDID"] = profile_udid
  ENV["PRODUCT_BUNDLE_IDENTIFIER"] = 'com.knomatic.velocity.615c107e.CustomForm.8303140c'

  gym(
    workspace: 'Velocity.xcworkspace',
    scheme: 'Velocity',
    configuration: 'Release',
    codesigning_identity: 'XXXXXXX',
    clean: true,
    silent: true,
    include_bitcode: false,
    xcargs: 'ENABLE_BITCODE=false',
    export_method: 'enterprise',
    use_legacy_build_api: true
  )


end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.17.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-02-21**
</details>

**Comment by oscarg798** [comment]
already check that, keep getting the error

**Comment by PetrosIchor** [comment]
Be sure to read through the docs more carefully as well as past issues posted to the issues section. You should also check out the examples section: https://github.com/fastlane/examples

Your usage of sigh doesn't look correct to me at all (I'm on my phone at the moment or I'd provide more).  Why are you assigning sigh to profile_udid?  What type of value does it return for you with that setup?

**Comment by oscarg798** [comment]
is it wrong ?, meaning i have two enterprise accounts, enterprise account 1 works fine with the exact same fastfile. @PetrosIchor
