### ISSUE TITLE
Impossible to submit for review with 2.18.0 app_platform

### ISSUE THREAD

**Issue by latas2000** [fastlane/fastlane#8324]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Trying to run my scripts which worked several weeks ago, and after update fastlane to the latest release I get this issue:

[22:26:52]: Finished the upload to iTunes Connect
[22:26:54]: Selecting the latest build...

[!] Could not find option for key :app_platform.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[22:35:15]: Uploading app icon...
[22:35:22]: Finished the upload to iTunes Connect
[22:35:25]: Selecting the latest build...

[!] Could not find option for key :app_platform. Available keys: username, app_identifier, app, edit_live, ipa, pkg, platform, metadata_path, screenshots_path, skip_binary_upload, skip_screenshots, app_version, skip_metadata, force, submit_for_review, automatic_release, price_tier, build_number, app_rating_config_path, submission_information, team_id, team_name, dev_portal_team_id, dev_portal_team_name, itc_provider, overwrite_screenshots, app_icon, apple_watch_app_icon, copyright, primary_category, secondary_category, primary_first_sub_category, primary_second_sub_category, secondary_first_sub_category, secondary_second_sub_category, app_review_information, description, name, keywords, release_notes, privacy_url, support_url, marketing_url

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.3                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| bundler                   | 1.14.4       |
</details>

*generated on:* **2017-02-21**
</details>

**Comment by GandjaFuzz** [comment]
having same error fastlane version 2.18.1

**Comment by mfurtak** [comment]
@latas2000 GandjaFuzz Could you please share your `Fastfile` where you are using the `app_platform` option?

Thanks!

**Comment by latas2000** [comment]
Well that's the magic. I'm not using it. The only similar I'm using is the
export_platform key which is part of the submission options.

I'm using a Deliver file. Just submission options, automatic_release true,
and nothing else. I'll paste the content later.

**Comment by latas2000** [comment]
Here is my Deliverfile content:
###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md


###################### Automatically generated ######################
# Feel free to remove the following line if you use fastlane (which you should)

app_identifier "com.myapp.mycompany” # The bundle identifier of your app
username “user@foo.com" # your Apple ID user
submission_information({
      add_id_info_limits_tracking: true,
      add_id_info_serves_ads: true,
      add_id_info_tracks_action: false,
      add_id_info_tracks_install: false,
      add_id_info_uses_idfa: true,
      content_rights_has_rights: true,
      content_rights_contains_third_party_content: false,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
    });
automatic_release true



And this is the command line I'm using:
fastlane deliver -u user@foo.com --skip_screenshots --skip_metadata --skip_binary --submit_for_review latest -a com.myapp.mycompany --force


Thank you.

**Comment by GandjaFuzz** [comment]
I too don't use this parameter
my fastfile for deliver
```
		parameters = {
			app_identifier: "xxx",
			app_icon: "xxx",
			price_tier: 0,
			copyright: "xxx",
			primary_category: "xxx",
			secondary_category: "xxx",
			automatic_release: true,
			app_rating_config_path: "xxx",
			submit_for_review: true,
			force: true,
			username: "xxx",
			edit_live: false,
			name: {
				options[:language] => app["app_name"]
			},
			description: {
				options[:language] => app["description"]
			},
			keywords: {
				options[:language] => app["keywords"]
			},
			marketing_url: {
				options[:language] => ''
			},
			support_url: {
				options[:language] => "xxx"
			},
			submission_information: {
			   export_compliance_available_on_french_store: false,
			   export_compliance_contains_proprietary_cryptography: false,
			   export_compliance_contains_third_party_cryptography: false,
			   export_compliance_is_exempt: false,
			   export_compliance_uses_encryption: false,
			   export_compliance_app_type: nil,
			   export_compliance_encryption_updated: false,
			   export_compliance_compliance_required: false,
			   export_compliance_platform: "ios",
			   content_rights_contains_third_party_content: true,
			   content_rights_has_rights: true,
			   add_id_info_limits_tracking: false,
			   add_id_info_serves_ads: false,
			   add_id_info_tracks_action: false,
			   add_id_info_tracks_install: false,
			   add_id_info_uses_idfa: false
			},
			app_review_information: {
			  first_name: "xxx",
			  last_name: "xxx",
			  phone_number: "xxx",
			  email_address: "xxx",
			  demo_user: "",
			  demo_password: "",
			  notes: ""
			}
		}
	
		if(!app['ios_version'].empty?)
			parameters.merge!({
				release_notes: {
					options[:language] => File.read("#{Dir.pwd}/../../commit.txt")
				}
			})
		end
	
		if options[:skip_screenshots]
			parameters.merge!({
				skip_screenshots: true
			})
		end
		
		deliver(parameters)			
```

**Comment by GandjaFuzz** [comment]
for fix need
```
nano /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.18.1/deliver/lib/deliver/submit_for_review.rb
```
change this
```
build = FastlaneCore::BuildWatcher.wait_for_build(app, options[:app_platform], sleep_time)
```
on this
```
build = FastlaneCore::BuildWatcher.wait_for_build(app, options[:platform], sleep_time)
```

**Comment by hjanuschka** [comment]
@GandjaFuzz thx! good catch, did a PR for that https://github.com/fastlane/fastlane/pull/8333

**Comment by GandjaFuzz** [comment]
@hjanuschka need more change
now error
```
ERROR [2017-02-22 17:23:31.53]: undefined local variable or method `sleep_time' for #<Deliver::SubmitForReview:0x007f817fbfcb08>
```

need change this
```
build = FastlaneCore::BuildWatcher.wait_for_build(app, options[:app_platform], sleep_time)
```
on this
```
build = FastlaneCore::BuildWatcher.wait_for_build(app, options[:platform], 30)
```

**Comment by hjanuschka** [comment]
done, thx can you test it?

**Comment by mfurtak** [comment]
Thanks for the report. We are going to ship a hot-fix release to address this 👍

**Comment by asfalcone** [comment]
_fastlane_ 2.18.2 has been released. Please run `fastlane update_fastlane` and let us know if this issue is fixed for you. Thanks!

**Comment by GandjaFuzz** [comment]
yes it is done. work great

**Comment by latas2000** [comment]
Cool!! Thanks.
