### ISSUE TITLE
Scan junit XML file name and extension

### ISSUE THREAD

**Issue by marcomorain** [fastlane/fastlane#8326]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi team Fastlane!

I've been investigating how to have CircleCI [collect test-metadata](https://circleci.com/docs/test-metadata/#metadata-collection-in-custom-test-steps) as easily as possible from `scan`. I would like to submit a PR to change the default filename and extension of the junit XML report file.

CircleCI will parse any `.xml` file in the `$CIRCLE_TEST_REPORTS` directory after a build, and use these test results to generate UI showing failing tests, and improved build failure emails and notifications.

#### Initial tests

If I invoke `scan` like this:

```
bundle exec fastlane scan --output_types junit --output_directory "$CIRCLE_TEST_REPORTS"
```

then the resulting file is `$CIRCLE_TEST_REPORTS/report.junit`. This file name is not unique per test run, so if someone invokes `scan` twice as part of a CI run, then the output file of the first run will be clobbered by the second. We see a lot of projects where `scan` runs multiple times. There can be individual runs for phone, ipad and watch.

For builds on CircleCI, I was hoping to set `SCAN_OUTPUT_DIRECTORY` to  `$CIRCLE_TEST_REPORTS` and `SCAN_OUPUT_TYPES` to `junit` by default, so that if someone tests using scan on CircleCI, scan will produce XML output unless otherwise overridden by the user. 

### Proposed Change

To this aim I'd like to submit a PR to change this line:

https://github.com/fastlane/fastlane/blob/master/scan/lib/scan/report_collector.rb#L65-L67 in `determine_output_file_name` to use a unique filename for each test run. I guess using [make_tmpname](http://www.rubydoc.info/stdlib/tmpdir/Dir/Tmpname).

I'd also like to change the resulting extension to `.xml` - the CircleCI metadata parser uses the file extension to determine the file contents - `.cucumber` for Cucumber tests or `.xml` for Junit-style output.

Any feedback on this before I submit a PR?

Thanks!

**Comment by mfurtak** [comment]
Hi @marcomorain - thanks for starting this discussion 👍 

Have you taken a look at the `:custom_report_file_name` option? If you generate a filename yourself as part of your `Fastfile`, and then give it to _scan_ with that option, does it get you what you're looking for?

**Comment by lyndsey-ferguson** [comment]
You could add the `--custom_report_file_name "report_$CIRCLE_BUILD_NUM"` parameter to the `scan` command if you want a unique report name.

**Comment by marcomorain** [comment]
I've closed the PR – I don't think what I'm proposing can work while remaining backwards compatible.

Using `custom_report_file_name` does not quite do what I need. If I set `SCAN_CUSTOM_REPORT_FILE_NAME`[1] to something like `$CIRCLE_TEST_REPORTS/scan.xml` in each build, then if a customers invokes `scan` twice in a build, the second run will overwrite the first invocation.

As I think through this, I don't think that's too much of a problem, since at present, multiple runs of a `scan` will overwrite `result.junit` on each run, so there would be no regression.

I've had good success with this approach for Fastlane already: https://circleci.com/changelog/#automatic-collection-of-fastlane-logs-for-macos-projects - we set `FL_BUILDLOG_PATH` to `$CIRCLE_ARTIFACTS` so that Fastlane build logs are stored automatically after each build. This has made our support team's job easier.

[1] `--custom_report_file_name` is not exposed to env vars at present, I will open a PR to fix that.

**Comment by lyndsey-ferguson** [comment]
Curious, what do you mean that `--custom_report_file_name` is not exposed to env vars? If you are running the command from a circleCi job, that `$CIRCLE_BUILD_NUM` environment variable should be available to command run from the command line.

**Comment by marcomorain** [comment]
@lyndsey-ferguson I mean that there is no `SCAN_CUSTOM_REPORT_FILE_NAME` env var equivalent for `--custom_report_file_name`.

My goal here is to get Junit-xml reports into the `$CIRCLE_TEST_REPORTS` folder if a customer uses `scan`. I'd really like if I can do this without having to have people edit their `Fastfile`.

If I set `SCAN_CUSTOM_REPORT_FILE_NAME` to `$CIRCLE_TEST_REPORTS/scan.xml` when a build begins, then customers than invoke scan without options will get the full benefit of CircleCI test metadata collection without having to change their Fastfile.

**Comment by marcomorain** [comment]
I've exposed `--custom_report_file_name` here - https://github.com/fastlane/fastlane/pull/8351
