### ISSUE TITLE
"undefined method `wait_for_train' for Class:Class (NoMethodError)" when running pilot upload

### ISSUE THREAD

**Issue by lyahdav** [fastlane/fastlane#8329]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

Command I ran:
`fastlane pilot upload -i path/to/build.ipa`

Output:
```
[21:55:46]: ---------------------------------------------------------------------------------------------------------------
[21:55:46]: --- Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online. ---
[21:55:46]: ---------------------------------------------------------------------------------------------------------------
[21:55:46]: Successfully uploaded the new binary to iTunes Connect
[21:55:46]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/fastlane_core/lib/fastlane_core/build_watcher.rb:32:in `wait_for_build': [!] undefined method `wait_for_train' for Class:Class (NoMethodError)
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/pilot/lib/pilot/build_manager.rb:34:in `upload'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/pilot/lib/pilot/commands_generator.rb:59:in `block (2 levels) in run'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/pilot/lib/pilot/commands_generator.rb:158:in `run'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/fastlane/lib/fastlane/cli_tools_distributor.rb:49:in `take_off'
	from /Users/.../.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/fastlane-2.18.1/bin/fastlane:15:in `<top (required)>'
	from /Users/.../.rbenv/versions/2.0.0-p647/bin/fastlane:23:in `load'
	from /Users/.../.rbenv/versions/2.0.0-p647/bin/fastlane:23:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.0.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.0                          |
| Installation Source | ~/.rbenv/versions/2.0.0-p647/bin/fastlane   |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | ~/.rbenv/versions/2.0.0-p647/lib            |
| OpenSSL Version     | OpenSSL 1.0.2f  28 Jan 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
itc_team_name "..."
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.4        |
| activesupport             | 4.2.5.1      |
| xcodeproj                 | 1.1.0        |
| claide                    | 1.0.1        |
</details>

*generated on:* **2017-02-21**
</details>

**Comment by mfurtak** [comment]
Thank you for the report. We are going to ship a hot-fix release to address this. 👍

**Comment by asfalcone** [comment]
_fastlane_ 2.18.2 has been released. Please run `fastlane update_fastlane` and let us know if the latest versions fixes this for you! Thanks!
