### ISSUE TITLE
How to implement Screengrab.setDefaultScreenshotStrategy(); to capture webView snapshots

### ISSUE THREAD

**Issue by dpettit** [fastlane/fastlane#8330]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Could you help me better understand how and where to add the code: 

Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());

Currently, without implementing the above code, I'm getting webView screengrabs that are beautiful, but surrounded by big black boxes without skins or indicators, controls, or menubars, etc.  I'm hoping that proper implementation of the suggested code will help but I'm just not sure where to add it.

I tried adding it to the "@Before" section of my Instrumentation test, but it appeared to break my test code's ability to perform UIDevice.swipeLeft() to turn pages.  Is the "@Before" section a good place for it, or does it need to be added elsewhere in my codebase?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
n/a
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-02-22**
</details>

**Comment by mfurtak** [comment]
Hm, no, I would expect that in a `@Before` method or a `@BeforeClass` static method should be fine.

What's the result when `UIDevice.swipe` is broken? Is there a crash, or does it just stop working?

**Comment by dpettit** [comment]
Well, currently the emulator just opens, and my test code simply swipes through all the webView pages, taking screengrabs of each along the way (the total number of webView pages in this app is 14).

After adding the above code to the @Before method, it runs the first page of content, and just stops working.  It seems like the swipe event just isn't registering, or that the app is no longer in a state to accept the swipe event.  What ultimately happens, if I wait long enough, is that the summary preview with the screengrabs is called up, with only a snapshot of the first webView page.

Then my code cycles through two other devices to capture screengrabs of them as well. Of them, the second device doesn't register the swipe, but it still manages to take a second screengrab of the first page somehow.

On the third emulator device, I receive no snapshot of the actual app, only a single snapshot of the device screen before the app is loaded.

So, there are no crashes, it just doesn't seem to register the swipes any more, if that makes sense.

The script ends as usual, without any complaints or errors.

Here is my test code, in case it helps...

As you may notice, I actually take 2 different screengrabs of each page, as I am trying to work out how to best implement some kind of "wait" mechanism to get the timing right.  Ideally, I'd like to be able to get a precise snapshot of the page after a pre-determined number of seconds, but I can't seem to find a way to do that right now.

Anyway, here is the test code:

###########################################
package androidTest.java;

import android.support.test.InstrumentationRegistry;
import android.support.test.filters.SdkSuppress;
import android.support.test.rule.ActivityTestRule;
import android.support.test.runner.AndroidJUnit4;

import org.junit.Before;
import org.junit.ClassRule;                                 // For localization
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;

import tools.fastlane.screengrab.Screengrab;                // Script BT-A-3 inserts the code that uses this

import static org.hamcrest.Matchers.notNullValue;
import static org.junit.Assert.assertThat;

import android.support.test.uiautomator.UiDevice;
import android.support.test.uiautomator.UiObject;
import android.support.test.uiautomator.UiSelector;

import com.talespring.wrapper.AndroidHTMLWrapper;

import tools.fastlane.screengrab.UiAutomatorScreenshotStrategy;
import tools.fastlane.screengrab.locale.LocaleTestRule;     // For localization

@RunWith(AndroidJUnit4.class)
@SdkSuppress(minSdkVersion = 19)
public class AndroidHTMLWrapperTest {

    private UiDevice mDevice;
    private UiObject pageView;

    // This ClassRule enables localization
    @ClassRule
    public static final LocaleTestRule localeTestRule = new LocaleTestRule();

    @Rule
    public ActivityTestRule<AndroidHTMLWrapper> mActivityTestRule = new ActivityTestRule<>(AndroidHTMLWrapper.class);

    @Before
    public void startActivityFromHomeScreen() {
        // Initialize UiDevice instance
        mDevice = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
        pageView = mDevice.findObject(new UiSelector());

        // Setup screengrab to use UiAutomator by default
        Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());
    }

    @Test
    public void checkPreconditions() {
        assertThat(mDevice, notNullValue());
    }

    @Test
    public void testSwipeNextPage() throws Exception {

       // START CODE INSERTED BY TS ANDROID TEST AUTOMATION SCRIPT BT-A-3 
       pageView.waitForExists(7); 
       Screengrab.screenshot("Page_1A");
       pageView.waitForExists(7); 
       Screengrab.screenshot("Page_1B");
       pageView.swipeLeft(15); 

	pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_2-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_2-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_3-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_3-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_4-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_4-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_5-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_5-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_6-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_6-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_7-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_7-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_8-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_8-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_9-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_9-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_10-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_10-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_11-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_11-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_12-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_12-B");
        pageView.swipeLeft(17);

        pageView.waitUntilGone(5);
        Screengrab.screenshot("Page_13-A");
        pageView.waitForExists(5);
        Screengrab.screenshot("Page_13-B");
        pageView.swipeLeft(17);

        // END CODE INSERTED BY TS ANDROID TEST AUTOMATION SCRIPT BT-A-3 
    }
}

**Comment by mfurtak** [comment]
Yeah, that makes sense. Thanks for the example.

Maybe there's a conflict between `UiAutomation` and `UiDevice`? Honestly I'm not sure. I don't have a suggestion, unfortunately, so I'll need to leave this open for now.

**Comment by dpettit** [comment]
No problem, I just appreciate your taking the time to look at it.  Thank you!
