### ISSUE TITLE
Upload build to iTC with limited permission

### ISSUE THREAD

**Issue by olejnjak** [fastlane/fastlane#8332]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello, 

I'd like to ask how I can use deliver to upload builds to iTC if my account permission is limited? Currently my account has _Developer_ role assigned and I'm getting error that I don't have enough permission, but when I try to upload the same build using Application Loader it succeeds.

Thanks for your help.

##### Complete output when running fastlane, including the stack trace and command used
`deliver(username: <connect_account>, team_id: <connect_team_id>, skip_screenshots: true, force: true, skip_metadata: true)`

User <connect_account> (Team ID <connect_team_id>) doesn't have enough permission for the following action: update_app_version

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require_relative './utils/utils.rb'

##################################### SETTINGS #####################################

inhouse_apple_id = 'unicorn@ackee.cz'
inhouse_team_id = 'PXDF48X6VX'

####################################################################################

PROJECT_PATH = "../idc-letenky-ios.xcodeproj"

#import "../../fastlane/fastlane/Fastfile"
import(download_from_git(url: 'git@gitlab.ack.ee:Ackee/fastlane.git',branch: 'lh/version-2', use_cache: is_xcode ))

desc "Submit new **beta** build to Hockey app"
lane :beta do |options|
    target = options[:target] || prompt(text: "Please enter app identifier (lowercase, no spaces, eg. letenkysnadno):")
    environment = options[:environment]

    #Pods
	pod_install

    #Setup badge for beta
    badge(shield: "#{get_version_number}-#{number_of_commits}-blue", dark: true, shield_no_resize: true)

    provisioning_match(configuration: environment, type: "enterprise", use_wildcard: true,
        username: inhouse_apple_id, git_url: ENV["ACK_PRODUCTION_MATCH_GIT"], team_id: inhouse_team_id, readonly: true)

    begin
        gym(scheme: target, configuration: environment, provisioning_profile_path: lane_context[SharedValues::SIGH_PROFILE_PATH])
    ensure
        # Put badge back to original
        sh "git checkout -- ../Resources/Images.xcassets/"
    end

    if !is_ci
        hockey_identifier = hockey_id(target, environment)
        hockey(public_identifier: hockey_identifier, notify: '0')
    end
end


desc "Deploy new version to the App Store (and also hockey app) using match"
lane :appstore do |options|
    target = options[:target] || prompt(text: "Please enter app identifier (lowercase, no spaces, eg. letenkysnadno):")
    settings = get_app_settings_value(key: "app", target: target)
    dev_account = settings["developer_account"]
    team_id = settings["team_id"]
    connect_account = settings["connect_account"]
    connect_team_id = settings["connect_team_id"]
    bundle_id = bundle_id(PROJECT_PATH, target, "AppStore")
    provisioning_type = settings["provisioning_type"]

    pod_install

    if provisioning_type == "match" then
        provisioning_match(configuration: "AppStore", type: "appstore", app_identifier: bundle_id,
            username: dev_account, team_id: team_id, readonly: true)
    elsif provisioning_type == "sigh"
        provisioning_sigh(configuration: "AppStore", app_identifier: bundle_id,
            username: dev_account, team_id: team_id)
    end

    gym(scheme: target, configuration: "AppStore", clean: true)
    deliver(username: connect_account, team_id: connect_team_id, skip_screenshots: true, force: true, skip_metadata: true)
end

desc "Switches environment and sets app_name and app_identifier in plist"
lane :set_environment do |options|
    if is_xcode
        UI.message "Xcode run script phase"
    end

    environment = options[:environment]

    if !is_environment(environment: environment)
        raise "Unknown environment #{environment}"
    end

    UI.message "Setting environment for #{environment}"

    # Change environment plist
    replace_environment_plist(environment: environment)
    generate_preprocess_header(build_number: number_of_commits)
end

desc "Creates new app - create target, shceme, copy files and add to project"
lane :new_app do |options|

	identifier = options[:identifier] || prompt(text: "Please enter new app identifier (lowercase, no spaces, eg. letenkysnadno):")

	# copy all files
	cp_r("../apps/default/.", "../apps/"+identifier)

	# create target for new event
	target = duplicate_target(PROJECT_PATH, identifier)

	UI.crash! "Failed to create target #{identifier}" unless target

	# add copied files to project
	add_files(PROJECT_PATH, identifier, "../apps/"+identifier)

	# create scheme for new event
	duplicate_scheme(PROJECT_PATH, identifier)

    pod_install
end

def generate_preprocess_header(params)
    path = File.expand_path("../environment/environment_preprocess.h", FastlaneCore::FastlaneFolder.path)
    File.open(path, 'w') { |file|
        file.puts "#define ACK_ENVIRONMENT_VERSION #{params[:build_number].to_s}"
    }
end

def info_plist_path(params)
    target = params[:target]
    return File.expand_path("../apps/#{target}/Info.plist", FastlaneCore::FastlaneFolder.path)
end

#end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.18       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.5       |
| faraday_middleware        | 0.10.0       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-02-22**
</details>

**Comment by olejnjak** [comment]
Yes I have and I'm using manual code signing as the client is a bit complicated so I just have provisioning profile and private key so this shouldn't be the case.

**Comment by hjanuschka** [comment]
@olejnjak could you provide a full stacktrace? by running the command with `--verbose`  to see where the error origin's from?


also could you try adding the following options to deliver.

```
app_version: "", submit_for_review: false
```

**Comment by olejnjak** [comment]
Adding `app_version` and `submit_for_review` did not help

```ruby
fastlane appstore target:xyz --verbose
```

[output.txt](https://github.com/fastlane/fastlane/files/799003/output.txt)

**Comment by hjanuschka** [comment]
@olegoid  according to the log it looks like metadata update is activated:

```
| skip_metadata         | false 
```

can you check this?

**Comment by EskiMag** [comment]
The same is happening for me. I am trying to use user with role *Developer* to upload the app. I am calling:
```ruby
deliver(username: "********",
        skip_screenshots: true,
        skip_metadata: true,
        submit_for_review: false,
        app_version: "",
        team_id: '********',
        ipa: '********')
```

**Comment by EskiMag** [comment]
When I used user with role **Technical**, everything works correctly.

**Comment by olejnjak** [comment]
Question is why the upload via Application Loader works, but using deliver it doesn't.

**Comment by chezzdev** [comment]
@olejnjak it happens because `deliver` edits current version's metadata even with the `skip_metadata` set to `false` when `Developer` role doesn't have such permissions.
Application Loader on the other hand just uploads the build and does nothing more.

**Comment by mbogh** [comment]
We have run into this problem as well.

**Comment by slackfarmer** [comment]
Giving an account App Manager role instead of Developer is wrong for uploading to testflight.

Maybe there is an easy fix for this.

**Comment by Skymax1986** [comment]
yeah, we do have the same problem - upload fails with Developer role :( 

would be great if there's a possible fix..

**Comment by taquitos** [comment]
Thanks all, is this still a problem in _fastlane_ 2.35.1?

**Comment by ildar-gilfanov-e-legion** [comment]
@taquitos Yes. I am using 2.35.1 and I have the same issue. I am calling 
    deliver(ipa: "./build/app.ipa", 
            username: appstore_apple_id, 
            team_name: appstore_team_name, 
            skip_screenshots: true, 
            skip_metadata: true,
            app_version: "",
            submit_for_review: false)

**Comment by ildar-gilfanov-e-legion** [comment]
There is stack trace:

```
/Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/client.rb:627:in `raise_insuffient_permission_error!': [!] Insufficient permissions for your Apple ID: (Spaceship::Client::InsufficientPermissions)
	User <user> (Team ID *****) doesn't have enough permission for the following action: update_app_version
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:160:in `handle_itc_response'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:324:in `block in update_app_version!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1283:in `with_tunes_retry'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/tunes_client.rb:317:in `update_app_version!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/app_version.rb:362:in `save!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/spaceship/lib/spaceship/tunes/application.rb:216:in `ensure_version!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/deliver/lib/deliver/runner.rb:39:in `verify_version'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/deliver/lib/deliver/runner.rb:20:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/deliver/lib/deliver/commands_generator.rb:67:in `block (2 levels) in run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/deliver/lib/deliver/commands_generator.rb:168:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.35.1/bin/fastlane:20:in `<top (required)>'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by mbogh** [comment]
It is fixed in fastlane 2.38.0 via #9307 🚀

**Comment by Anetsch** [comment]
@mbogh this fix doesn't work for me. fastlane Version is 2.43.0

**Comment by mbogh** [comment]
@Anetsch the same error?
