### ISSUE TITLE
How to upload all apks(with different flavors) to playstore simultaneously

### ISSUE THREAD

**Issue by s-gagandeep** [fastlane/fastlane#8338]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have around 30 flavors of my android application, I want to upload all apks simultaneously to google playstore.
Is there any way to do it.
I dont want to run 30 fastlane supply command for each apk.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by PetrosIchor** [comment]
Read the docs https://docs.fastlane.tools/actions/#supply

Or run `fastlane action supply` for supply's options. 

You can pass an array of apk paths for multi file upload using `apk_paths: []`

**Comment by s-gagandeep** [comment]
How to add all paths in apk_paths: []
i) do i need to mention each apk or is there any option which lists the path of all apks like GRADLE_ALL_APK_OUTPUT_PATHS
ii) and do i need to add all package names also?
as just adding the apk_paths it is giving error  apkUpgradePackageNameIsDifferent: APK has the wrong package name.

**Comment by jpage4500** [comment]
Hi,

I'm also looking to do the same thing here.. I don't have an answer but I wonder if something can be done similar to this solution for uploading multiple APK's to Crashlytics:

http://stackoverflow.com/documentation/android/8215/fastlane/26395/fastfile-to-build-and-upload-multiple-flavors-to-beta-by-crashlytics#t=20170227195718036329

The key would be how to get the package name each time through this loop so we can upload each APK 1 at a time.. any ideas?

```
.. build each APK using gradle() ..

    # upload APK files to Play Store
    lane_context[SharedValues::GRADLE_ALL_APK_OUTPUT_PATHS].each do | apk |

        puts "Uploading APK to Play Store: " + apk

        begin
            # upload to Google Play
            supply(
              track: "alpha",
              apk: apk
              # package_name: ??
            )
        end
    end
```

**Comment by s-gagandeep** [comment]
hi,

I was also stuck at the above scenario, but as a way around i have lane switching and iteratively build 
all apk and uploading to playstore.

This is what i have tried:

  desc "deploy each flavor"
  lane :flavor1 do
    gradle(task: "clean")
    gradle(task: "assembleflavorRelease")
    supply(
    track: 'alpha',
    package_name: 'com.flavor.src',
    apk: "/Users/Involvio/AndroidStudioProjects/MyApplication/app/build/outputs/apk/app-flavor-release.apk"
  )
  end

  desc "deploy each flavor"
  lane :flavor2 do
  gradle(task: "clean")
  gradle(task: "assembleflavor1Release")
  supply(
  track: 'production',
  package_name: 'com.flavor1.src',
  apk: "/Users/Involvio/AndroidStudioProjects/MyApplication/app/build/outputs/apk/app-flavor1-release.apk")
  end
//// here i have added individual lanes so that they will run sequentially
  desc "upload to playstore"
  lane :upload do
  flavor1
  flavor2
end

The above is working fine, but here if i build all apks at once and then try to upload to playstore it gives error.
https://github.com/fastlane/fastlane/issues/3390
https://github.com/fastlane/fastlane/issues/4675

if you find any other solution, do let me know.
Thanks
