### ISSUE TITLE
Advice: Recommended solution for continuous integration/delivery builds

### ISSUE THREAD

**Issue by robfromca** [fastlane/fastlane#834]
I have an idea of how I want my CI/CD pipeline to work, and I have bits of it working, but I think for me there's some missing pieces. I'm happy to add them if it makes sense.

To update/fix provisioning profiles, I want the developers to be able to use sigh. But I don't want to have sigh (or anything else) on the build box connecting to apple to update the provisioning profiles (I want the builds to be deterministic, such that two consecutive builds will always use the same provisioning profiles unless someone checks in an update).

So I currently have something like this in my fastfile:

```
def build_app
    project_file = 'app.xcodeproj'
    udid = sigh(output_path: "build/certs",
          app_identifier: "com.app.bundleid",
          team_id: "XXXXXXXXXX")
    ENV["PROFILE_UDID"] = udid
    gym(scheme: "myscheme",
        output_directory: "build/",
        use_legacy_build_api: "true")
end
```

Sigh connects in using keychain credentials to download/verify the profile and then return the udid. What I want is the developers to be able to run sigh locally to download the profiles to a known place, check them in, and then have the above build pull the udid from the profile and verify it, without the dev center connection or apple id. That seems easy enough to patch in as an option to sigh or as a new fastlane action, and I'm happy to do it, just wondering if that's compatible with what you're thinking for sigh, or if theres already a different way to accomplish the same thing.

**Comment by KrauseFx** [comment]
Yeah, I'm happy to say there is now [match](https://github.com/fastlane/match) and with it [codesigning.guide](https://codesigning.guide) which should solve this issue. Let me know how you like it.

**Comment by KrauseFx** [comment]
With `match` you have a `--readonly` flag so you don't have to provide access to the Developer Portal.

**Comment by KrauseFx** [comment]
I'll close this issue for now :+1:
