### ISSUE TITLE
Fastlane init results in (Gem::MissingSpecError)

### ISSUE THREAD

**Issue by zoufishanmehdi** [fastlane/fastlane#8340]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I try to do fastlane init after downloading the installer script, I get this error `(Gem::MissingSpecError)`

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

`/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'fastlane' (>= 0) among 13 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/zinfandel/.gem/ruby/2.4.0:/usr/local/lib/ruby/gems/2.4.0:/usr/local/Cellar/ruby/2.4.0/lib/ruby/gems/2.4.0', execute `gem env` for more information
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/dependency.rb:320:in `to_spec'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'`

*****Running gem env results in ****

`RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.8
  - RUBY VERSION: 2.4.0 (2016-12-24 patchlevel 0) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: /Users/zinfandel/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/zinfandel/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.4.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.4.0
     - /Users/zinfandel/.gem/ruby/2.4.0
     - /usr/local/Cellar/ruby/2.4.0/lib/ruby/gems/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Applications/Postgres.app/Contents/Versions/9.4/bin
     - /usr/local
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /Users/zinfandel/.fastlane/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/git/bin
     - /usr/local/Cellar/openssl/1.0.2j/bin/openssl`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

`/usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'fastlane' (>= 0) among 13 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/zinfandel/.gem/ruby/2.4.0:/usr/local/lib/ruby/gems/2.4.0:/usr/local/Cellar/ruby/2.4.0/lib/ruby/gems/2.4.0', execute `gem env` for more information
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/dependency.rb:320:in `to_spec'
	from /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/fastlane:22:in `<main>'`

**Comment by ohayon** [comment]
Hey @zoufishanmehdi! Thanks for submitting the issue! It looks like there might be some issues with competing versions of _fastlane_ on your machine. Would you mind sharing the output of `which fastlane` and `echo $PATH`? I think with that information we should be able to understand a bit more of whats going on. Apologies for the inconvenience! 🐙

**Comment by samratBasra** [comment]
which fastlane
/Users/jenkins/.rvm/rubies/ruby-2.0.0-p648/bin/fastlane

 echo $PATH
/Users/jenkins/.rvm/gems/ruby-2.0.0-p648/bin:/Users/jenkins/.rvm/gems/ruby-2.0.0-p648@global/bin:/Users/jenkins/.rvm/rubies/ruby-2.0.0-p648/bin:/Users/jenkins/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:**/Users/jenkins/.rvm/rubies/ruby-2.0.0-p648/bin/fastlane****


still getting same issue.

**Comment by ohayon** [comment]
@samratBasra did you install _fastlane_ using the installer script or by running `gem install fastlane` on the jenkins machine?

**Comment by samratBasra** [comment]
@ohayon ,, yes it fastlane version issue. its working with fastlane 2.12.

issue can be close now.
