### ISSUE TITLE
fastlane deliver - submission_information docs

### ISSUE THREAD

**Issue by domenico-renna** [fastlane/fastlane#8345]
I'm searching advanced info about "fastlane deliver action".
I need more detail on the right meaning of the "submission_information" block of parameters so I can set that value correctly and completely automate my ios deployment continuos integration framework.

Reading fastlane documentation I understood the generic idea behind that params and debugging itunesconnect portal HTML code I found the bind between that params and the checkboxes in page.

With the aim to fully understand, I would like to read generic documentation about that params, documentation that I can find nowhere, I found only this link in fastlane docs (https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_submission.rb#L18-L69)

Can you help me?
Thanks

**Comment by domenico-renna** [comment]
fastlane env is not required to respond on my question, I only need some info or documentation link about the submit_information flag

**Comment by mfurtak** [comment]
Hi @domenico-renna 👋  I believe the references you have noted so far are the best documentation we have right now.

Maybe I can help? What would you like to know?

**Comment by hjanuschka** [comment]
you may look at https://github.com/fastlane/fastlane/issues/8260#issuecomment-281696248 - i think there are almost all options

let me know if this helps

**Comment by domenico-renna** [comment]
I would like to know the exact meaning of this flag (if possible):

```
attr_mapping({
        # Ad ID Info Section
        'adIdInfo.limitsTracking.value' => :add_id_info_limits_tracking,
        'adIdInfo.servesAds.value' => :add_id_info_serves_ads,
        'adIdInfo.tracksAction.value' => :add_id_info_tracks_action,
        'adIdInfo.tracksInstall.value' => :add_id_info_tracks_install,
        'adIdInfo.usesIdfa.value' => :add_id_info_uses_idfa,

        # Content Rights Section
        'contentRights.containsThirdPartyContent.value' => :content_rights_contains_third_party_content,
        'contentRights.hasRights.value' => :content_rights_has_rights,

        # Export Compliance Section
        'exportCompliance.availableOnFrenchStore.value' => :export_compliance_available_on_french_store,
        'exportCompliance.ccatFile.value' => :export_compliance_ccat_file,
        'exportCompliance.containsProprietaryCryptography.value' => :export_compliance_contains_proprietary_cryptography,
        'exportCompliance.containsThirdPartyCryptography.value' => :export_compliance_contains_third_party_cryptography,
        'exportCompliance.isExempt.value' => :export_compliance_is_exempt,
        'exportCompliance.usesEncryption.value' => :export_compliance_uses_encryption,
        'exportCompliance.appType' => :export_compliance_app_type,
        'exportCompliance.encryptionUpdated.value' => :export_compliance_encryption_updated,
        'exportCompliance.exportComplianceRequired' => :export_compliance_compliance_required,
        'exportCompliance.platform' => :export_compliance_platform
      })
```

I'm searching this info beacuse, depending from my application setting and code, I would automatically generate that configuration array

**Comment by mfurtak** [comment]
The code snippet you pasted handles the automatic mapping of iTunes data into the data structures that _spaceship_ uses.

Is there a particular field in there you're looking for clarification about?

**Comment by domenico-renna** [comment]
Ok thanks, starting from your reply I can find this page where is the definition of a lot of web service used in spaceship, in particular this [https://github.com/fastlane/itc-api-docs#submit-for-review](https://github.com/fastlane/itc-api-docs#submit-for-review).

However I would have some specification on params accepted by that itunesconnect API service, info that I can't find in fastlane docs or google too.

If you have a link to the official apple docs please link it,

**Comment by mfurtak** [comment]
It's important to realize that the iTunes Connect API is not a public API from Apple, so it is not documented by them. :smile: Everything that is built in _spaceship_ comes from reverse-engineering.

As you noticed, because that the submission information fields line up nicely with those same fields from the Apple website, I'd say that your best bet for finding explanations for what each means will be to look for documentation for the iTunes Connect website from Apple.

If you find a good reference, please share the link here and we'll incorporate it into our documentation 👍

**Comment by domenico-renna** [comment]
ok then great thanks for the incredible reverse-engineering work done, if I should find somethings usefull documentation I'll surly share it with this comunity
