### ISSUE TITLE
push_to_git_remote from Travis CI

### ISSUE THREAD

**Issue by alickbass** [fastlane/fastlane#8347]
Hi! I am using `fastlane` together with `Travis CI` to upload the build to testflight every time the new push arrives at master branch. However, I am having troubles using `push_to_git_remote` action from travis and I receive the following error: `Invalid username or password`. What is the proper way to use this action with travis? maybe there is a way to specify `github access token`? And what am I doing wrong? Thank you very much!)

**Comment by ohayon** [comment]
Hey @alickbass, from my experience with Travis it is good practice to use environment variables as is documented here: https://docs.travis-ci.com/user/environment-variables/. Thanks! 🐙

**Comment by alickbass** [comment]
@ohayon that's true, but current action `push_to_git_remote` doesn't support changing the user of specifying the custom url nor making it silent not to show the github api key.

**Comment by ohayon** [comment]
@alickbass, I'm not sure I totally understand what you mean here, but could you set up environment variables on Travis for each of the arguments passed to `push_to_git_remote` that way depending on the machine from which you are running, you can change the parameters via environment variables?
