### ISSUE TITLE
In-App Purchase screenshots review error in spaceship

### ISSUE THREAD

**Issue by umec** [fastlane/fastlane#8348]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hi,
I'm playing around with the new IAP feature for spaceship but I'm having trouble uploading the screenshot for review. I've tried with different sizes with no luck. If I try to upload it manually to iTunes it works.

```
require "spaceship"

Spaceship::Tunes.login("usr", "pwd")

app = Spaceship::Application.find("com.test.iostest")
app.in_app_purchases.create!(
  type: Spaceship::Tunes::IAPType::NON_CONSUMABLE, 
  versions: {
    'en-US': {
      name: "chapter 2",
      description: "English description has at least 10 characters"
    }
  },
  reference_name: "Chapter 2",
  product_id: "iostest.ch2",
  cleared_for_sale: true,
  review_notes: "Some Review Notes here bla bla bla",
  review_screenshot: "/Users/lcorral/Downloads/placeholders/ios_screenshot.jpg",
  pricing_intervals: 
    [
      {
        country: "WW",
        begin_date: nil,
        end_date: nil,
        tier: 2
      }
    ] 
)
```

##### Complete output when running fastlane, including the stack trace and command used
`ruby iapp_test.rb`

```
/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.18.1/spaceship/lib/spaceship/du/du_client.rb:127:in `parse_upload_response': [IMG_BAD_DIMENSIONS] The image dimensions are not supported. Please adjust to acceptable dimensions and re-save it. (Spaceship::Client::UnexpectedResponse)
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.18.1/spaceship/lib/spaceship/du/du_client.rb:83:in `upload_file'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.18.1/spaceship/lib/spaceship/du/du_client.rb:22:in `upload_purchase_review_screenshot'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.18.1/spaceship/lib/spaceship/tunes/tunes_client.rb:597:in `upload_purchase_review_screenshot'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.18.1/spaceship/lib/spaceship/tunes/tunes_client.rb:1109:in `create_iap!'
	from /usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.18.1/spaceship/lib/spaceship/tunes/iap.rb:71:in `create!'
```

<details><summary>🎨ios_screenshot.jpg🎨</summary>

![ios_screenshot](https://cloud.githubusercontent.com/assets/11942903/23262419/e8819f70-f9da-11e6-8198-2e535239043b.jpg)
</details>

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.13.6       |
| json                      | 2.0.2        |
| io-console                | 0.4.5        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.3        |
</details>

*generated on:* **2017-02-23**
</details>

**Comment by hjanuschka** [comment]
hmmm - according to docs and my local tests the screenshot hase to be 640x960 - can you try it with one?

the one you supplied has 1024x768.

hope that will resolve you'r issues - nice to see someone using the api for iap's 👍

**Comment by umec** [comment]
Hi !
That made the trick, thank you very much !! 😊

Also, thanks a lot for your iap contribution to spacechip, this will make a huge difference on my daily work.

**Comment by hjanuschka** [comment]
@umec nice to hear - going to close this issue then, if you need any further assitance or run into any other issue feel free to open a new one

**Comment by peter542** [comment]
Hello!

Thank you very much for adding this feature! It will save me so much time! 

Is it possible to support different screenshot sizes? 768*1024 for example? ITC supports these screenshots.

Again, thank you very much!

**Comment by jianghaoyuan2007** [comment]
This feature is very cool! 👍

**Comment by timothycosta** [comment]
If it's not possible to make this work for other sizes, maybe the error could explicitly mention 640x960?
