### ISSUE TITLE
Match is creating distribution provisioning profile with old certificate

### ISSUE THREAD

**Issue by jlubeck** [fastlane/fastlane#8354]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

So I'm trying to create a build to upload to the app store, and when I run match to get the certificates and provisioning profiles, it first created a second certificate (fine by me) but when it created the provisioning profiles it used the old certificate, so now when GYM tries to make the build, it complains that the certificate is not found. Is there a way to force match to use the latest certficate on the profile? Thanks!

Command Used: `match_update_appstore`
<details><summary>Output/Log</summary>

```

[16:39:40]: -------------------------------------------------
[16:39:40]: --- Step: Verifying required fastlane version ---
[16:39:40]: -------------------------------------------------
[16:39:40]: Your fastlane version 2.8.0 matches the minimum requirement of 1.101.0  ✅
[16:39:40]: ------------------------------
[16:39:40]: --- Step: default_platform ---
[16:39:40]: ------------------------------
[16:39:40]: Name of the lane 'appstore' is already taken by the action named 'appstore'
[16:39:40]: Driving the lane 'ios match_update_appstore' 🚀
[16:39:40]: -------------------
[16:39:40]: --- Step: match ---
[16:39:40]: -------------------
[16:39:40]: Successfully loaded '/Volumes/MacintoshHD2/Users/Jan/Projects/iOS/fastlane/Matchfile' 📄

+----------------------+-------------------------------------------------+
|              Detected Values from './fastlane/Matchfile'               |
+----------------------+-------------------------------------------------+
| git_url              | git@git.assembla.com:certificates.git |
+----------------------+-------------------------------------------------+


+-----------------------+-------------------------------------------------+
|                         Summary for match 2.8.0                         |
+-----------------------+-------------------------------------------------+
| type                  | appstore                                        |
| team_id               | XXXXX                                      |
| app_identifier        | com.xxxx.appstore                          |
| shallow_clone         | false                                           |
| force_for_new_devices | true                                            |
| git_url               | git@git.assembla.com:xxxx.certificates.git |
| git_branch            | master                                          |
| username              | jlubeck@xxxx.com                           |
| keychain_name         | login.keychain                                  |
| readonly              | false                                           |
| verbose               | false                                           |
| force                 | false                                           |
| skip_confirmation     | false                                           |
| skip_docs             | false                                           |
+-----------------------+-------------------------------------------------+

[16:39:40]: Cloning remote git repo...
[16:39:43]: 🔓  Successfully decrypted certificates repo
[16:39:44]: Verifying that the certificate and profile are still valid on the Dev Portal...
[16:39:46]: Installing certificate...

+-------------------+-------------------------------------------------+
|                        Installed Certificate                        |
+-------------------+-------------------------------------------------+
| User ID           | HC9BRC3KWP                                      |
| Common Name       | iPhone Distribution: xxxx LLC (xxxx) |
| Organisation Unit | xxxx                                      |
| Organisation      | xxxx LLC                                   |
| Country           | US                                              |
| Start Datetime    | Feb 23 21:10:43 2017 GMT                        |
| End Datetime      | Feb 23 21:10:43 2018 GMT                        |
+-------------------+-------------------------------------------------+


+-------------------------------------+---------------------------------------+
|                           Summary for sigh 2.8.0                            |
+-------------------------------------+---------------------------------------+
| app_identifier                      | com.xxxx.appstore                |
| username                            | jlubeck@xxxx.com                 |
| force                               | true                                  |
| cert_id                             | K544P57F7D                            |
| provisioning_name                   | match AppStore com.xxxx.appstore |
| ignore_profiles_with_different_name | true                                  |
| team_id                             | xxxx                            |
| adhoc                               | false                                 |
| development                         | false                                 |
| skip_install                        | false                                 |
| skip_fetch_profiles                 | false                                 |
| skip_certificate_verification       | false                                 |
| platform                            | ios                                   |
+-------------------------------------+---------------------------------------+

[16:39:51]: Starting login with user 'jlubeck@xxxx.com'
[16:39:53]: Successfully logged in
[16:39:53]: Fetching profiles...
[16:39:57]: Found 1 matching profile(s)
[16:39:57]: Updating the provisioning profile
[16:39:58]: Downloading provisioning profile...
[16:39:59]: Successfully downloaded provisioning profile...
[16:39:59]: Installing provisioning profile...
/var/folders/71/93d6p0bn21s0g6z6rskmb7h40000gt/T/d20170223-95942-1t8ksov/profiles/appstore/AppStore_com.xxxx.appstore.mobileprovision
[16:39:59]: Installing provisioning profile...
[16:40:01]: 🔒  Successfully encrypted certificates repo
[16:40:01]: Pushing changes to remote git repo...

+---------------------+---------------------------------------------------+---------------------------------------+
|                                         Installed Provisioning Profile                                          |
+---------------------+---------------------------------------------------+---------------------------------------+
| Parameter           | Environment Variable                              | Value                                 |
+---------------------+---------------------------------------------------+---------------------------------------+
| App Identifier      |                                                   | com.xxxx.appstore                |
| Type                |                                                   | appstore                              |
| Profile UUID        | sigh_com.xxxx.appstore_appstore              | 059977f1-ae53-4c8b-829a-408f6ff04f3e  |
| Profile Name        | sigh_com.xxxx.appstore_appstore_profile-name | match AppStore com.xxxx.appstore |
| Development Team ID | sigh_com.xxxx.appstore_appstore_team-id      | HC9BRC3KWP                            |
+---------------------+---------------------------------------------------+---------------------------------------+

[16:40:06]: All required keys, certificates and provisioning profiles are installed 🙌
[16:40:06]: Setting Provisioning Profile type to 'app-store'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 25          |
+------+-------------------------------------+-------------+

[16:40:06]: fastlane.tools finished successfully 🎉

#######################################################################
# fastlane 2.18.3 is available. You are on 2.8.0.
# It is recommended to use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################

2.18.3 Fix update checker
* Fix fastlane update checking for sub-tools (#8343)

2.18.2 deliver and pilot hotfix - revert BuildWatcher changes
* Revert "Centralize BuildWatcher for iTunes Connect builds" (#8335)

2.18.1 Hotfix for git_branch action
* Fix git-branch crash if no ENV vars present (#8321)

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `bundle update fastlane`


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.101.0"

default_platform :ios

platform :ios do
  before_all do
    ENV['VERSION_NUMBER'] = get_version_number
    ENV['BUILD_NUMBER'] = get_build_number
  end

  desc "Runs linting"
  lane :analyze do
    xcodebuild(
      workspace: "xxxx.xcworkspace",
      scheme: "xxxx",
      configuration: "Debug",
      sdk: 'iphonesimulator',
      destination: 'platform=iOS Simulator,OS=9.3,name=iPhone 6',
      analyze: true
    )
  end

  lane :match_get_appstore do
		match(type: 'appstore', team_id: 'xxxx', app_identifier: 'com.xxxx.appstore', shallow_clone: false, readonly: true)
  end

	lane :match_create_appstore do
		match(type: 'appstore', team_id: 'xxxx', app_identifier: 'com.xxxx.appstore',shallow_clone: false)
	end

	lane :match_update_appstore do
		match(type: 'appstore', team_id: 'xxxx', app_identifier: 'com.xxxx.appstore', shallow_clone: false, force_for_new_devices: true)
	end

	desc "Build and submit a new Appstore Build"
	lane :appstore do
	ensure_git_branch(branch: 'master')
	match_get_appstore
	cocoapods(repo_update: true)
	gym(scheme: "xxxx_Appstore", use_legacy_build_api: true, configuration: "Production", export_method: "app-store", output_directory: "build", output_name: "xxxx", clean: true)
	pilot
	end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end
end

# Helper functions

def get_build_number
  `/usr/libexec/PlistBuddy -c 'Print CFBundleVersion' ../DriveMode/xxxx-Info.plist`.strip
end

def get_version_number
  `/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' ../DriveMode/xxxx-Info.plist`.strip
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxxx.ios" # The bundle identifier of your app
apple_id "jlubeck@xxxx.com" # Your Apple email address

team_id "xxxx"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.8.0   | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| aws-sigv4                 | 1.0.0        |
| jmespath                  | 1.3.1        |
| aws-sdk-core              | 2.6.44       |
| aws-sdk-resources         | 2.6.44       |
| aws-sdk                   | 2.6.44       |
| babosa                    | 1.0.2        |
| bundler                   | 1.14.2       |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.2        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0       |
| fastimage                 | 2.0.1        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types                | 2.99.3       |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| net-ssh                   | 3.2.0        |
| net-sftp                  | 2.1.2        |
| krausefx-shenzhen         | 0.14.11      |
| rest-client               | 1.8.0        |
</details>

*generated on:* **2017-02-23**
</details>

**Comment by PetrosIchor** [comment]
Try removing both certs from your keychain, I've had odd collisions where depreciated or unrelated certs get used.  Removing all certs and letting fastlane repopulate my keychain resolved it. 

Or, for bonus points, use the creat and delete keychain actions.  Create a keychain that will only contain your certificate and use it at build time.  Then destroy it after.
