### ISSUE TITLE
Cannot create app in iTunes Connect with Auto Code Signing

### ISSUE THREAD

**Issue by kishinmanglani** [fastlane/fastlane#8356]
I can’t seem to create an app on the dev center and on iTunes connect if I use automatic code signing. Basically, whenever I change the bundle id in the Xcode project, it seems like the “app identifier is not available”. If I manually change the app_id in the App File and don’t update in the Xcode Project it works. Is there a way to get this to work while using automatic code signing?

- have Xcode Auto Signing turned on
- change bundle id in the Xcode project to something unique and that doesn’t exist
- run `fastlane init` with the following:
```
[22:00:04]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[22:00:04]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
Please confirm the above values (y/n)
y
[22:01:16]: Could not find app with app identifier 'com.uniquename.Demo1' in your iTunes Connect account (kishin.manglani+apple@gmail.com - Team: 2206009)
[22:01:16]: An error occured during the setup process. Falling back to manual setup!
App Identifier (com.krausefx.app): com.uniquename.Demo1
[22:01:37]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
Would you like to create your app on iTunes Connect and the Developer Portal? (y/n)
y
```
- Run `fastlane produce` with the following:
```
[22:01:57]: To not be asked about this value, you can specify it using 'app_name'
App Name: Demo 123987
[22:02:02]: Creating new app 'Demo 123987' on the Apple Dev Center

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] Apple provided the following error info:
	An App ID with Identifier 'com.uniquename.Demo1' is not available. Please enter a different string.
```
**Env**
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Is homebrew         | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.17.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.uniquename.Demo1" # The bundle identifier of your app
apple_id "kishin.manglani+apple@gmail.com" # Your Apple email address

team_id "DU3424MHW3"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-02-23**
</details>
```

**Comment by KrauseFx** [comment]
> 	An App ID with Identifier 'com.uniquename.Demo1' is not available. Please enter a different string.


That's the error message, the app identifier is taken

**Comment by kishinmanglani** [comment]
I'm certain that the app identifier is not taken. I'm creating arbitrary strings. It seems like Xcode Auto Signing could be creating an app with the identifier when I update the bundle id in the project, which is preventing me from creating the app using Fastlane.

**Comment by KrauseFx** [comment]
This means someone **else** uses the bundle identifier.

**Comment by KrauseFx** [comment]
I'm not sure why you assume this is related to code signing, because it isn't.

**Comment by kishinmanglani** [comment]
If I turn of auto code signing, change the bundle id, and then use produce it works. If I **turn on** auto code signing, change the bundle id, then use produce it **does not** work. That's what leads me to believe that its related to Xcode's Auto Code Signing.

It is literally not possible for anyone to be using these bundle identifiers. I'm creating them randomly with numbers, my name, etc. Again, if I use these same identifiers with auto code signing off, it all works. Unfortunately, that means xcode auto signing is doing something (not sure exactly) in the background that makes using Fastlane a bit more difficult.

**Comment by kishinmanglani** [comment]
I'm aware that this is not related to code signing directly, but when Xcode manages Code Signing it also handles App IDs, which we can agree is the source of the error.

**Comment by kishinmanglani** [comment]
Going to close this for now. It is definitely a bit more related to Xcode than Fastlane. If I find any more info, I'll reopen and update it here.
