### ISSUE TITLE
using match to actually change what profile is used to sign an app before building.

### ISSUE THREAD

**Issue by klundberg** [fastlane/fastlane#8357]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Previously we had been using `cert`, `sigh`, and `update_project_provisioning` to manually control what profiles are used to sign our app when we distribute. We did this because we build the same app using an app store dev team and an enterprise program dev team, depending on how we distribute (beta builds are signed as enterprise and sent through crashlytics, app store submissions are signed as app store and uploaded with deliver).

We are looking to move to match to try solving some code signing issues we've come across the past few days. I've followed the directions mentioned in codesigning.guide and docs.fastlane.tools as far as I can tell. However those documents don't seem to cover the use case where you actually want to change which profile is used at build time in fastlane.

I could hack together something in my `Fastfile` that manually edits the xcodeproj file to change the provisioning, but I'd rather use `update_project_provisioning` to do so. However, that action expects a profile path, or `sigh` to have been run previously. Is it reasonable to either update `match` to export the environment var that `sigh` does so that this can work, or conversely to change `update_project_provisioning` so that it can listen for what `match` might set as well? Is there some other way I'm not thinking of to physically change the build settings in the project using fastlane actions (I don't want to force developers to run fastlane if they want to build release builds, if they would prefer to just use Xcode on its own for that locally).

##### Complete output when running fastlane, including the stack trace and command used

(Will update tomorrow when I can get it, if it would be useful)

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                             |
| ------------------- | ------------------------------------------------- |
| OS                  | 10.11.6                                           |
| Ruby                | 2.3.1                                             |
| Bundler?            | false                                             |
| Git                 | git version 2.11.1                                |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane              |
| Host                | Mac OS X 10.11.6 (15G1108)                        |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                       |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                       |
| Is contained        | false                                             |
| Is homebrew         | false                                             |
| Xcode Path          | /Applications/Xcode-8.2.1.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```
Omitted for brevity, our fastfile is very large with some info i'd rather not post publicly
```

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.2        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-02-24**
</details>

**Comment by PetrosIchor** [comment]
This goes outside the scope of match at this time.  I've asked the same questions in the past.  There's a ton of options for you.  Definitely do some long search of old issues posted here, you'll find folks discussing different solutions.  

In my case, I've got 2 platform focused products that can any number of apps, all with different IDs. (Last I looked there's around 140 sets of different signing values. 

I've tried a number of workflows.  What I found works best is to update the xcodeproj and plist files with the correct values at build time. Leaving the app codebase a blank slate.  Match outputs ENV variables I grab in inject into the project. 

In conjunction with match, I'm using a modified version of this plugin: https://github.com/Mindera/fastlane-plugin-cosigner.  That gets my project setup with what I need, match/gym handle the rest as they normally would. 

I'll also mention each app has a yaml file with various parameters I need to specify.  You can do this with the build in dotenv functionality too.  I just find yaml to be easier.

**Comment by PetrosIchor** [comment]
To add to my comment.  Fastlane is focused on single app usage.  The tools expect you have an app with various config, build, and deployment targets.  If you have multiple apps with many more configuration needs, you have to get more creative in your workflows.  

It's totally doable.  Fastlane provides a wonderful, powerful base to start from.  Getting it over the finish line is on you though.  

You might also consider import_from_git.  I've been exploring that action as a way to marry my two platforms needs into a single Fastfile. (I have multiple at the moment).   Dictate out lanes for every possible use case and store in branches or in remote  git paths.  Then use a small, single Fastfile with import_from_git to pull in the relevant lanes and run them.   That might ease your pain a little from a monolith fastlane setuo
