### ISSUE TITLE
Snapshot fails on Travis, only when using iPhone 6/7 Plus

### ISSUE THREAD

**Issue by jaroslavas** [fastlane/fastlane#8358]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a very strange issue. My tests run perfectly on my machine. When I run them on Travis, they are also ok on all emulators that I try, except on iPhone 6/7 Plus, where I get this error:

```
UI Testing Failure - Failure fetching attributes for element 
<XCAccessibilityElement: 0x600000258150> Device element: 
Error Domain=XCTestManagerErrorDomain Code=13 
"Error copying attributes -25202" UserInfo={NSLocalizedDescription=Error copying attributes -25202}
```

Maybe someone has seen something similar and has a fix for that?

**Comment by jaroslavas** [comment]
`fatlane env`: (noting special, Travis)


<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |

| ------------------- | ------------------------------------------- |

| OS                  | 10.12.1                                     |

| Ruby                | 2.0.0                                       |

| Bundler?            | false                                       |

| Git                 | git version 2.11.0                          |

| Installation Source | ~/.rvm/gems/ruby-2.0.0-p648/bin/fastlane    |

| Host                | Mac OS X 10.12.1 (16B2555)                  |

| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.0.0-p648/lib           |

| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |

| Is contained        | false                                       |

| Is homebrew         | false                                       |

| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |

| Xcode Version       | 8.2                                         |

### System Locale

| Variable | Value       |   |

| -------- | ----------- | - |

| LANG     | en_US.UTF-8 | ✅ |

| LC_ALL   | en_US.UTF-8 | ✅ |

| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |

| -------- | ------- | ------------- |

| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |

| ------------------------- | ------------ |

| executable-hooks          | 1.3.2        |

| bundler-unload            | 1.0.2        |

| rubygems-bundler          | 1.4.4        |

| bundler                   | 1.12.5       |

| slack-notifier            | 1.5.1        |

| i18n                      | 0.7.0        |

| thread_safe               | 0.3.5        |

| tzinfo                    | 1.2.2        |

| minitest                  | 5.9.1        |

| activesupport             | 4.2.7.1      |

| CFPropertyList            | 2.3.3        |

| claide                    | 1.0.1        |

| colored                   | 1.2          |

| nanaimo                   | 0.2.2        |

| xcodeproj                 | 1.4.1        |

| rouge                     | 1.11.1       |

| xcpretty                  | 0.2.4        |

| terminal-notifier         | 1.7.1        |

| terminal-table            | 1.4.5        |

| plist                     | 3.1.0        |

| public_suffix             | 2.0.3        |

| addressable               | 2.5.0        |

| multipart-post            | 2.0.0        |

| word_wrap                 | 1.0.0        |

| tty-screen                | 0.5.0        |

| babosa                    | 1.0.2        |

| highline                  | 1.7.8        |

| commander                 | 4.4.0        |

| excon                     | 0.54.0       |

| unf_ext                   | 0.0.7.2      |

| unf                       | 0.1.4        |

| domain_name               | 0.5.20161021 |

| http-cookie               | 1.0.3        |

| faraday-cookie_jar        | 0.0.6        |

| fastimage                 | 1.6.8        |

| gh_inspector              | 1.0.2        |

| uber                      | 0.0.15       |

| representable             | 2.3.0        |

| retriable                 | 2.1.0        |

| mime-types                | 1.25.1       |

| hurley                    | 0.2          |

| faraday                   | 0.9.2        |

| little-plugger            | 1.1.4        |

| multi_json                | 1.12.1       |

| logging                   | 2.1.0        |

| jwt                       | 1.5.6        |

| memoist                   | 0.15.0       |

| os                        | 0.9.6        |

| signet                    | 0.7.3        |

| googleauth                | 0.5.1        |

| httpclient                | 2.8.2.4      |

| google-api-client         | 0.9.19       |

| mini_magick               | 4.5.1        |

| multi_xml                 | 0.5.5        |

| security                  | 0.1.3        |

| xcpretty-travis-formatter | 0.0.4        |

| dotenv                    | 2.1.1        |

| faraday_middleware        | 0.10.0       |

| json                      | 1.8.3        |

| rubyzip                   | 1.2.0        |

</details>

*generated on:* **2017-02-27**

</details>

## Fastfile:

```
desc "Deploy to AppStore"
lane :production do
    
    # Setup app: name, bundle id, etc.
    read_app_data_from_env
    
    # If app is newly created, creates it on apple developer portal
    produce_app_if_needed
    
    # Create custom keychain because of a bug: https://github.com/fastlane/fastlane/issues/7104
    create_keychain(
                    name: MATCH_KEYCHAIN_NAME,
                    password: MATCH_KEYCHAIN_PASSWORD,
                    default_keychain: true,
                    unlock: true,
                    timeout: 3600,
                    add_to_search_list: true
    )
    
    # Prepare certificates, keys and provisioning profiles
    match(
          keychain_name: MATCH_KEYCHAIN_NAME,
          keychain_password: MATCH_KEYCHAIN_PASSWORD,
          git_branch: MATCH_GIT_BRANCH,
          username: APPLE_USERNAME,
          team_id: APPLE_TEAM_ID,
          app_identifier: APP_BUNDLE_ID,
          type: "appstore",
          readonly: false
          )
    
    # Set right Provisioning profile
    PROVISIONING_PROFILE_NAME_KEY = certificate_name_variable(APP_BUNDLE_ID, 'appstore')
    PROVISIONING_PROFILE_NAME = ENV[PROVISIONING_PROFILE_NAME_KEY]
    update_provisioning_profile_specifier(project: "../MyProject.xcodeproj", build_configuration: "Release", prov_name: PROVISIONING_PROFILE_NAME)
    UI.important("Changed Provisioning profile to '#{PROVISIONING_PROFILE_NAME}'")
    
    # Trying to fix some weird errors on travis https://github.com/fastlane/fastlane/issues/3921
    ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "1"
    
    # Make screenshots
    snapshot(
        number_of_retries: 2
    )
          
    #Build
    gym(scheme: "MyApp Appstore")
    
    # Upload to appstore
    deliver(
        force: true, # Set to true to skip PDF verification
        username: APPLE_USERNAME,
        team_name: APPLE_TEAM_NAME,
        app_icon: "fastlane/metadata/AppIcon.png"
    )
    
    # Inform everyone
    post_to_slack(scheme: ENV["DEPLOY_APPLICATION_NAME"], destination: "AppStore")
    
end


#------------------------- Helper functions -------------------------#

private_lane :read_app_data_from_env do |options|
    if ENV["DEPLOY_VERSION"]
        increment_version_number(version_number: ENV["DEPLOY_VERSION"]) # Set a specific version number
    end
    
    if ENV["DEPLOY_APPLICATION_NAME"]
        APP_NAME = ENV["DEPLOY_APPLICATION_NAME"]
        update_info_plist(
                          plist_path: "MyApp-Appstore-Info.plist",
                          display_name: APP_NAME
                          )
        UI.important("Changed app Display Name to '#{APP_NAME}'")
    end
    
    if ENV["DEPLOY_PACKAGE_NAME"]
        update_app_identifier(
                              xcodeproj: "MyApp.xcodeproj", # Optional path to xcodeproj, will use the first .xcodeproj if not set
                              plist_path: "MyApp-Appstore-Info.plist", # Path to info plist file, relative to xcodeproj
                              app_identifier: APP_BUNDLE_ID # The App Identifier
                              )
        UI.important("Changed app bundle ID to '#{APP_BUNDLE_ID}'")
    end
    
end

private_lane :produce_app_if_needed do |options|
   produce(
           username: APPLE_USERNAME,
           app_identifier: APP_BUNDLE_ID,
           app_name: ENV["DEPLOY_APPLICATION_NAME"],
           language: 'English',
           app_version: ENV["DEPLOY_VERSION"],
           sku: APP_BUNDLE_ID,
           team_name: APPLE_TEAM_NAME
    )
end

# Get the name of env var created by match/sigh tool
def certificate_name_variable(bundle_id, certificate_type)
    return 'sigh_' + bundle_id + '_' + certificate_type + '_profile-name';
end

# Change setting of project to use given Provisioning Profile
lane :update_provisioning_profile_specifier do |params|
    proj = params[:project]
    target_filter = params[:target_filter] || params[:build_configuration_filter]
    configuration = params[:build_configuration]
    prov_name = params[:prov_name]
    
    require 'xcodeproj'
    
    project = Xcodeproj::Project.open(proj)
    project.targets.each do |target|
        if !target_filter || target.product_name.match(target_filter) || (target.respond_to?(:product_type) && target.product_type.match(target_filter))
            UI.success("Updating target #{target.product_name}...")
            else
            UI.important("Skipping target #{target.product_name} as it doesn't match the filter '#{target_filter}'")
            next
        end
        
        target.build_configuration_list.build_configurations.each do |build_configuration|
            config_name = build_configuration.name
            if !configuration || config_name.match(configuration)
                UI.success("Updating configuration #{config_name}...")
                else
                UI.important("Skipping configuration #{config_name} as it doesn't match the filter '#{configuration}'")
                next
            end
            
            build_configuration.build_settings["PROVISIONING_PROFILE_SPECIFIER"] = prov_name
        end
    end
    project.save
end

```

**Comment by asfalcone** [comment]
@jaroslavas It seems like this is problem for many people running UI tests and isn't specific to _snapshot_: https://forums.developer.apple.com/thread/6437 You might take a look through that forum and see if any of the posts or links help you resolve the problem. Feel free to report back here if you do find a solution.

**Comment by jaroslavas** [comment]
Yes, looks like a general problem with tests :(
