### ISSUE TITLE
Deliver causes AppStore review to reject metadata

### ISSUE THREAD

**Issue by lkraider** [fastlane/fastlane#8360]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Tried to submit 2 apps using Deliver, one a new app the other an update for an existing app, and both got stuck in review with Metadata Rejected with same message from the AppStore:
```
Feb 24, 2017 at 4:13 PM
From Apple

    0. 4.0 BEFORE YOU SUBMIT: INFO NEEDED

Information Needed


We began the review of your app but aren't able to continue because we need additional information about your app.

At your earliest opportunity, please review the following questions and provide as much detailed information as you can. The more information you can provide upfront, the sooner we can complete your review.

- Does your app access any paid content or services?
- What are the paid content or services, and what are the costs?
- Who pays for the content or services?
- Where do they pay, and what's the payment method?
- If users create an account to use your app, are there fees involved?

Once you reply to this message in Resolution Center with the requested information, we can proceed with your review.
```

Deliverfile:
```
app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

screenshots_path "fastlane/#{app_identifier}/screenshots"
metadata_path "fastlane/#{app_identifier}/metadata"

app_rating_config_path "fastlane/rating_config.json"

price_tier 0

app_review_information(
  first_name: "My",
  last_name: "Name",
  phone_number: "+123456",
  email_address: "user@co.com",
  demo_user: "myUser",
  demo_password: "myPass",
  notes: "Usage instructions"
)

submission_information({
  add_id_info_uses_idfa: false,
  export_compliance_uses_encryption: true,
  export_compliance_is_exempt: true,
  export_compliance_encryption_updated: false
})

automatic_release false
```

My guess there's something missing in the deliver submission that causes the review process to halt the app.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                        |
| ------------------- | -------------------------------------------- |
| OS                  | 10.11.6                                      |
| Ruby                | 2.3.1                                        |
| Bundler?            | false                                        |
| Git                 | git version 2.10.1                           |
| Installation Source | ~/.gem/ruby/2.3.0/bin/fastlane               |
| Host                | Mac OS X 10.11.6 (15G1217)                   |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.3.1_2/lib           |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                  |
| Is contained        | false                                        |
| Is homebrew         | false                                        |
| Xcode Path          | ~/Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#!/usr/bin/env ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.3"

default_platform :ios

platform :ios do

  lane :certificates do
    match(type: "development", readonly: true)
    match(type: "adhoc", readonly: true)
    match(type: "appstore", readonly: true)
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#!/usr/bin/env ruby

app_identifier "com.nkey.vistoria.entrada"

apple_id "build@nkey.com.br" # Your Apple email address
team_id "8LGTBBXKRY"  # Developer Portal Team ID
itc_team_id "215598"  # iTunes Connect Team ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.17.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.11.0       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-02-24**
</details>

**Comment by hjanuschka** [comment]
we ran into this once - with an app that was in store for really long time.
first of all i think, you should resolve it in the resolution center.
and on following updates i would tweak the `notes` to be more specific.


i am not 100% sure how one can trigger it, but i think its  a combination of too short review notes +  in-app-purchases + human interaction (on apple side)

**Comment by lkraider** [comment]
I don't know if it's a bug, but the iTunesConnect site allowed me to resubmit the same build for review (as if it was never submitted), I'll wait and see what happens now.

**Comment by hjanuschka** [comment]
🤔  ok would be nice if you share the results.

**Comment by lkraider** [comment]
Seems it was a misunderstanding of mine, you have to enter your response in the "Resolution Center" and then press "Submit for Review" again on the build for the resolution response to be considered by the review team.
