### ISSUE TITLE
how to set the country for sale?

### ISSUE THREAD

**Issue by haoshuncheng** [fastlane/fastlane#8362]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by asfalcone** [comment]
@haoshuncheng This issue is incomplete and missing the important information to be able to help you. Please provide the information requested above (the command you ran, the output, etc). Thanks!

**Comment by mpirri** [comment]
@haoshuncheng If you are looking to set the territories that the application can be downloaded from, look into using the `set_availability!` method on `Spaceship::Tunes::Application`.  You will need to create a `Spaceship::Tunes::Availability` object and pass that in to specify which territories you are interested in. 

If this is not helpful, please clarify your question, and provide the information requested by @asfalcone .

**Comment by KrauseFx** [comment]
Hey @haoshuncheng, I'll close this issue due to inactivity now. Feel free to re-open it, or submit a new one if you have the chance 👍 Thanks
