### ISSUE TITLE
increment_build_number increments build number in all targets

### ISSUE THREAD

**Issue by esusatyo** [fastlane/fastlane#837]
I have several targets in my Xcode project, with different `.plist` files and different build numbers.

When I used `increment_build_number` in my fastfile, it increments all the build numbers of my other targets as well as the build number of the target I built with `gym`. This made my other build numbers incorrect, as not all of them are the same.

Is there a way to fix this? Maybe somehow by passing the target name in the command? (e.g. `increment_build_number(target: "target_to_build")`)

**Comment by xfreebird** [comment]
@esusatyo that would be nice, but there is one limitation, in background ```increment_build_number``` is using Apple's ```agvtool``` to set the build numbers.

```agvtool``` itself doesn't have such option as on what target to apply the build number.

To be able to do that, ```increment_build_number``` would have to use a different tool.

In your case I would change the strategy.
For Target_A
1) Increase current build number for target_A
2) push to an array
3) build the target_A
4) reset changes

the same for Target_B.

After all targets are built.  Set the build numbers  from the array with the saved incremented build numbers, commit and push your changes.
***At this stage you would have to use some scripting***

For more information about agvtool [```man agvtool```](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/agvtool.1.html)

**Comment by esusatyo** [comment]
@xfreebird Ah, I see. I was assuming that the `increment_build_number` is just a variation of `update_info_plist` that took the build version number and +1 to it. 

I might just make my own script in this case then, instead of hacking `agvtool` this way.

**Comment by gpbl** [comment]
@esusatyo I have also the same need, please let us know if you have a script ready :P

**Comment by mmdumi** [comment]
Same here

**Comment by ohwutup** [comment]
Hi everyone, this is an awesome idea to have as a custom action. I think its best to keep using `agvtool` as a default as it's following Apple's best practices. I am going to close this issue and mark it as a feature request, and we will update the issue when we can pull it for a future release, but until then, if anyone would like to beat us to the punch, a PR with this as a custom action would be amazing! Thanks! :+1: :100:

**Comment by jffiorillo** [comment]
I'm having same issue here, I would like to increment_build_number related to an specific schema, someone can help me with the script or tutorial? Thanks

**Comment by BigSauce** [comment]
Same issue over here. 👍

**Comment by wimbledon** [comment]
Same issue here too!

**Comment by ohwutup** [comment]
Hey everyone! As I mentioned a while back, we definitely would like to keep `agvtool` as the default mechanism by which to manipulate version numbers as this is the technique Apple would like developers to use. We just created a new version of fastlane that allows for plugins- it would be really awesome to see someone in the community build a plugin that can handle different styles of versions and bumping them. I am going to re-close this issue as a feature request, but please continue discussion regarding any future development on a version-managing plugin. Thanks! 🐙 🌊 👍 🚀

**Comment by jffiorillo** [comment]
![screen shot 2016-06-02 at 15 35 41](https://cloud.githubusercontent.com/assets/777950/15746646/bb32c398-28d7-11e6-88a1-13ea6a008cbc.png)

ya_tu_sabes plugin? WTF?? xD

**Comment by drosenstark** [comment]
This is now real (I begged the author to include build number, and they obliged!). Should out to @SiarheiFedartsou for this plug!

https://github.com/SiarheiFedartsou/fastlane-plugin-versioning

I'm personally doing this:

```
      increment_build_number_in_plist(
        build_number: Time.now.strftime("%Y%m%d%H%M"),
        target: 'Lite'
      )
```

I'm currently specifying the target per lane, but that's probably my lack of understanding.
