### ISSUE TITLE
Why is $HOME/.fastlane created with an install using homebrew?

### ISSUE THREAD

**Issue by remcohaszing** [fastlane/fastlane#8371]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've just installed fastlane using homebrew and noticed a `~/.fastlane` directory was created. Why is this?

I'd expect fastlane to be installed to `/usr/local/Caskroom`. I don't see any reasons to install this in the home directory. I do see some cons:

- Even though the brew formula is installed system-wide, fastlane is only available for one user.
- I'd think it's safe to remove this directory from my home directory — What happens if I do so?
- Yet another directory has to be added to my `$PATH`.

I think this issue can be broken down into some sub issues:

- Is it necessary to install into `~/.fastlane`?
- If so, it should be documented. I guess this belongs in the FAQ then.
- If not, fastlane should be installed into the homebrew prefix.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                |
| ------------------- | ------------------------------------ |
| OS                  | 10.12.3                              |
| Ruby                | 2.2.4                                |
| Bundler?            | false                                |
| Git                 | git version 2.10.1 (Apple Git-78)    |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                | Mac OS X 10.12.3 (16D32)             |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained        | false                                |
| Is homebrew         | true                                 |
| Xcode Path          | /Library/Developer/CommandLineTools/ |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-02-27**

**Comment by ohayon** [comment]
Hey @remcohaszing! Thanks for raising the issue! One of the main reasons for installing into the home directory is so that we do not need to escalate permissions if/when users do not have write permissions to `/usr/local/lib` and `/usr/local/bin`. 

We would definitely be open to discussing this further, but I am going to close this issue for now as it does not cause any problems that we are aware of at the moment. 😄 🐙

**Comment by kalle** [comment]
I agree with @remcohaszing on this one.

My normal account doesn't have admin rights so I use a special account for that, and now fastlane installs into that user's $HOME. To use homebrew you have to fix the permissions on `/usr/local` etc anyway, so I don't get that argument at all.

Can you please make fastlane work like any other homebrew package again? I was on `1.11.2` when I needed to fix a seldom updated app and got hit by this madness. :-)
