### ISSUE TITLE
Distinguish device/simulator name in the test report

### ISSUE THREAD

**Issue by alexander-agri** [fastlane/fastlane#8372]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hey guys! I'm running UI tests with `scan` against different simulators and iOS versions. However, if I have a few simulators in the destination list and if there's a failure taking place - there's no way I can distinguish on which device did this happen (usually by checking HTML report). In XCTest there's an internal method `recordFailure()` , which I overrode and included `SIMULATOR_DEVICE_NAME` in the end of the error message, which basically solved my problem if I run it from XCode. But when I run the same tests through Fastlane, it doesn't use `recordFailure()` and prints raw error message.

Is there any way I could specify device/simulator name in my Fastlane reports or force it to go through `recordFailure()` ?

Thank you for good work!

**Comment by ohayon** [comment]
Hey @alexander-agri! This would be a great feature to have! This is the first I'm hearing of the `recordFailure()` . 

_scan_ is really just a wrapper for an `xcodebuild` test command so if `recordFailure()` gets called when a test run via `xcodebuild` fails, we should be able to output the results.

Can you run `xcodebuild test` on your project to see if you see what you are looking for? 😄 🐙
