### ISSUE TITLE
Add support for hidden -increment-minor-version option in increment_build_version action

### ISSUE THREAD

**Issue by craigedmunds** [fastlane/fastlane#8373]
As discussed in https://github.com/fastlane/fastlane/issues/596

Apple's agvtool has a hidden option -increment-minor-version I use to bump my build version.

agvtool next-version -increment-minor-version -all
will bump 35.3 to 35.4, while the default behaviour would bump to 36.

I would love to see a minor: true|false option in the increment_build_version action. It might be useful for others too.

**Comment by hjanuschka** [comment]
i am not sure if this should be labeld as "Bug".

this should be done here, if i get it right?: 
  * https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_build_number.rb#L36
  *  https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_version_number.rb#L26 here too ? 


would you like to go for a PR? - i more than happy to help you guide you through it.

**Comment by KrauseFx** [comment]
Thanks @hjanuschka!

I'll close this issue due to inactivity now. Feel free to re-open it, or submit a new one if you have the chance 👍 Thanks
