### ISSUE TITLE
Xcode bot, "Missing password for user" with 2FA and FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD set

### ISSUE THREAD

**Issue by burczyk** [fastlane/fastlane#8374]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi guys, I'm trying to integrate fastlane with Xcode bots and I'm facing some problems.
My configuration was based mainly on this great series of blog posts: https://honzadvorsky.com/articles/2015-08-17-17-30-xcode_server_tutorials_3_prebuild__postbuild_scripts/ but still I haven't succeed.

The error I'm getting is `Missing password for user test@test.abc, and running in non-interactive shell`
I do have 2FA enabled for my account and I did generate app-specific password. It's stored in my .profile as well as in Xcode's Post-Integration Trigger that looks like this:

```sh
#!/bin/sh
export PATH=/usr/local/bin:$PATH
export LANG=en_US.UTF-8
export LC_CTYPE=UTF-8
export FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD="..."

cd project-directory && fastlane appstore
```

Of course if I specify `FASTLANE_PASSWORD` it doesn't work as single password is not enough to authenticate. How can I approach this issue?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```bash
[15:25:12]: [31mMissing password for user test@test.abc, and running in non-interactive shell[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | gym                                 | 223         |
| 💥   | [31mdeliver[0m                             | 0           |
+------+-------------------------------------+-------------+

[15:25:12]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/credentials_manager/lib/credentials_manager/account_manager.rb:125:in `ask_for_login': [31m[!] Missing password for user test@test.abc, and running in non-interactive shell[0m (RuntimeError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/credentials_manager/lib/credentials_manager/account_manager.rb:48:in `password'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/spaceship/lib/spaceship/client.rb:259:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/spaceship/lib/spaceship/client.rb:109:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/spaceship/lib/spaceship/tunes/spaceship.rb:22:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/deliver/lib/deliver/runner.rb:14:in `login'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/deliver/lib/deliver/runner.rb:7:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/actions/deliver.rb:16:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:62:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.18.3/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```
### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.3                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.11.0                                             |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.102.0"

default_platform :ios

platform :ios do
  desc "Deploy new version to the App Store"
  lane :appstore do
    gym(scheme: "project", workspace: "project.xcworkspace", configuration: "Release", codesigning_identity: "...")
    deliver(username: "test@test.abc", skip_screenshots: true, skip_metadata: true, submit_for_review: false)
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"] # The bundle identifier of your app
apple_id "" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.24       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-02-27**
</details>

**Comment by mfurtak** [comment]
Related to #7380

**Comment by mfurtak** [comment]
Hi @burczyk - thanks for the report 👍 

Are you also using the `FASTLANE_SESSION` environment variable to capture the output of `fastlane spaceauth` as described here: https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth ?

**Comment by burczyk** [comment]
@mfurtak I did set it in `.profile` file but it may be a good hint it's not visible during build process. Tomorrow when I'm at work I'll set it directly in Post-Integration trigger and let you know about the results.

**Comment by mfurtak** [comment]
Hi all, I am trying to reproduce this, but so far I have not had any luck. By using a combination of `FASTLANE_PASSWORD`, `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`, and `FASTLANE_SESSION` I am able to do:

```ruby
lane :beta do
  match(type: "appstore")
  gym(scheme: "MyScheme")
  pilot
end
```


from my local machine without being prompted for any credentials.

As described in https://github.com/fastlane/fastlane/issues/8218#issuecomment-280862932, my account is set up for two-step auth.

My next step will be to try to do the same from Travis CI, and see if it is any different.

**Comment by burczyk** [comment]
@mfurtak thank you for your tests. I confirm that using all 3 values in script does solve the issue and builds can be successfully delivered. It's a bit non obvious though. Maybe it's a good case to extend this https://docs.fastlane.tools/best-practices/continuous-integration/ with Xcode bots?

**Comment by mfurtak** [comment]
Nice, thanks for working with me on this :+1: I don't personally have experience with Xcode bots, but it would be great if we could share what you have learned with everyone.

docs.fastlane.tools is open-source [here](https://github.com/fastlane/docs), so I would love to review a pull request to add what you've learned about Xcode bots and fastlane :+1:
