### ISSUE TITLE
Sigh taking awhile to download profiles (Duplicate of #6195)

### ISSUE THREAD

**Issue by MichaelCurtisEls** [fastlane/fastlane#8375]
This is a duplicate of https://github.com/fastlane/fastlane/issues/6195, but I can re-create it again.

Sigh is taking about 3.5 minutes to fetch provisioning profiles as opposed to 15-20 seconds which was typical. Everything completes as normal, it just takes significantly longer.

Version Info:
fastlane -v
fastlane 2.18.3

sigh -v
sigh 2.0.1

Sigh output: 

+-------------------------------------+--------------------------------------+
|                          Summary for sigh 2.18.3                                                                |
+-------------------------------------+--------------------------------------+
| team_id                                       | ************                                                     |
| cert_id                                         | *************                                                   |
| app_identifier                               | bundle_id                                                          |
| ignore_profiles_with_different_name | true                                                            |
| provisioning_name                               | Prov Prof Name                                       |
| adhoc                                                    | false                                                          |
| development                                         | false                                                         |
| skip_install                                             | false                                                         |
| force                                                       | false                                                         |
| username                                               | username                                                |
| skip_fetch_profiles                                | false                                                         |
| skip_certificate_verification                  | false                                                         |
| platform                                                  | ios                                                           |
+-------------------------------------+--------------------------------------+

[15:16:07]: Starting login with user 'username@username.com'
[15:16:10]: Successfully logged in
[15:16:10]: Fetching profiles...
[15:19:32]: Provisioning Profile 'profile' is not valid, skipping this one...
[15:19:33]: Found 1 matching profile(s)
[15:19:33]: Downloading provisioning profile...
[15:19:35]: Successfully downloaded provisioning profile...
[15:19:35]: Installing provisioning profile...

I'm just wondering if anyone else is having this issue again?

Fastlane env:
<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id ENV["APPLE_ID"]

#ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| did_you_mean              | 1.0.2   |
| slack-notifier            | 1.5.1   |
| rouge                     | 1.11.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.7.1   |
| plist                     | 3.2.0   |
| addressable               | 2.5.0   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| tty-screen                | 0.5.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| http-cookie               | 1.0.3   |
| faraday-cookie_jar        | 0.0.6   |
| highline                  | 1.7.8   |
| mini_magick               | 4.5.1   |
| multi_json                | 1.12.1  |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| json                      | 2.0.3   |
| commander                 | 4.4.3   |
| io-console                | 0.4.6   |
| excon                     | 0.55.0  |
| rubyzip                   | 1.2.1   |
| claide                    | 1.0.1   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.2   |
| bundler                   | 1.14.4  |
| terminal-table            | 1.7.3   |
| unicode-display_width     | 1.1.3   |
</details>

*generated on:* **2017-02-27**
</details>

**Comment by hjanuschka** [comment]
@MichaelCurtisEls we are aware of this issue, the PR here, is not yet finished, but is going to address the issue -> https://github.com/fastlane/fastlane/pull/8359

**Comment by MichaelCurtisEls** [comment]
Wonderful, thank you very much!
