### ISSUE TITLE
scan test_without_building not working

### ISSUE THREAD

**Issue by AymenFarrah** [fastlane/fastlane#8376]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I use Gym for build/archive so i have this:

```
+----------------------+---------------------------------------------------------------------------+
|                                      Summary for gym 2.18.3                                      |
+----------------------+---------------------------------------------------------------------------+
| export_method        | enterprise                                                                |
| workspace            | myApp.xcworkspace                                                           |
| configuration        | AdHoc                                                                     |
| scheme               | myScheme                                                                       |
| clean                | false                                                                     |
| output_directory     | buildPath                                                             |
| output_name          | myApp-Development                                                   |
| derived_data_path    | derivedDataPath                                                  |
| include_bitcode      | true                                                                      |
| destination          | generic/platform=iOS                                                      |
| silent               | false                                                                     |
| use_legacy_build_api | false                                                                     |
| buildlog_path        | ~/Library/Logs/gym                                                        |
| xcode_path           | /Applications/Xcode.app                                                   |
+----------------------+---------------------------------------------------------------------------+
```

So in logs: 

```
[15:58:39]: ▸ Touching myApp.app
[15:58:39]: ▸ Signing derivedData/Development/Build/Intermediates/ArchiveIntermediates/myTargetName/InstallationBuildProductsLocation/Applications/myApp.app
[15:58:40]: ▸ Touching myApp.app.dSYM
[15:58:40]: ▸ Archive Succeeded
[15:58:40]: Successfully stored the archive. You can find it in the Xcode Organizer.
```

When i use scan with those parameters
scan(derived_data_path: derivedDataPath, test_without_building: true) 

And then here is my Scan output:

```
+------------------------+---------------------------+
|              Summary for scan 2.18.3               |
+------------------------+---------------------------+
| derived_data_path      | derivedDataPath   |
| test_without_building  | true                      |
| workspace              | myApp.xcworkspace           |
| scheme                 | myAppTests                  |
| configuration          | Debug                     |
| devices                | ["iPhone 5"]              |
| clean                  | false                     |
| output_types           | html                      |
| output_directory       | ./fastlane/myAppTestsReport |
| skip_slack             | true                      |
| skip_build             | true                      |
| buildlog_path          | ~/Library/Logs/scan       |
| include_simulator_logs | false                     |
| open_report            | false                     |
| slack_only_on_failure  | false                     |
| use_clang_report_name  | false                     |
| fail_build             | true                      |
| xcode_path             | /Applications/Xcode.app   |

```

I get ** TEST EXECUTE FAILED **
And reason found in log is: 
no file found at /Users/myWorkspace/derivedData/Development/Build/Products/Debug-iphonesimulator/myApp.app"

And when i check log when i run Gym i found this log:

```
Signing derivedData/Development/Build/Intermediates/ArchiveIntermediates/myScheme/InstallationBuildProductsLocation/Applications/myApp.app
[15:58:40]: ▸ Touching myApp.app.dSYM
[15:58:40]: ▸ Archive Succeeded

```

so i have two problems:
- the path of myApp.app is not the same between gym and scan
- the myApp.app is removed automatically when archive succeeded

Any ideas how it works ? 

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
</details>

**Comment by hjanuschka** [comment]
to clarify the usage of `test_without_building` you should run scan with `build_for_testing`  in before.


like 

```ruby
scan(derived_data_path: "datapath", build_for_testing: true)
scan(derived_data_path: "datapath", test_without_building: true)
```

if you require to use gym - you ll have to set the `build-for-testing` via xcargs. which should result in a special file with `.xctestrun` at the end. you can than take that for scan.

```ruby
scan(xctestrun: "/path/to/app.xctestrun")
```

let me know if this helps.

**Comment by AymenFarrah** [comment]
i'm trying this one and it works
`scan(derived_data_path: "datapath", build_for_testing: true)
scan(derived_data_path: "datapath", test_without_building: true)
`
my idea was to build just one time my project with gym and next run scan on myApp.app generated by gem before.
but with this solution i will build twice my projet !

thank you

(i'm trying your second solution)

**Comment by hjanuschka** [comment]
@AymenFarrah glad you got it working 👏 

gym (xcode) does not build files required for testing by default. so without the xcargs it won't work. i am going to close this issue, feel free to reopen  (or file new one) if you need any further informations
