### ISSUE TITLE
Automate DSYMS upload to Crashlytics on Linux systems

### ISSUE THREAD

**Issue by najdanovicivan** [fastlane/fastlane#8377]
I'want to use fastlane to run DSYMS submission via cron job. I was able to configure the fastlane to work but the issue is that upload-symbols binary from Crashlytics app does not exits compiled for linux. I've already contacted Crashlytics support and they told me this is the fastlane issue.

 Is there a way to submit DSYSM without use of this binary or get the linux version of this binary file ?

**Comment by TKBurner** [comment]
@najdanovicivan Thanks for reaching out. Right now it's not possible to run the Crashlytics submit command on Linux, the Fastlane command runs this under the hood. The description of the submit command is in Crashlytics documentation. Feel free to ping your ticket with Fabric, we all work on the same team and can make a feature request for you. 👍
