### ISSUE TITLE
Two-Factor auth added to iTunes Connect - Sigh no longer can login

### ISSUE THREAD

**Issue by iandundas** [fastlane/fastlane#838]
<img width="509" alt="screen shot 2015-11-12 at 08 25 23" src="https://cloud.githubusercontent.com/assets/1131967/11112796/f091949e-8916-11e5-9a03-f8399909c50a.png">

Sigh just dumps the HTML out and throws an error. (the HTML of the login screen)

**Comment by xfreebird** [comment]
Yeah, it would be nice to have ```sigh``` asking for the verification step, or at least throw some error. But that is valid only if you intend to run ```fastlane``` manually from command line.

From automation perspective, you would need to disable ```two-factor auth```.
It is possible to automate, but that would be so much pain.

**Comment by iandundas** [comment]
Okay - strange it only started for me today though - probably Sigh should catch the error. 

I am running fastlane manually from the command-line, for now at least, so it would be indeed useful. In the browser there’s the option to “remember this browser” (presumably sets a cookie..) so that the two-factor auth is only necessary the first time. Sounds like a pain to implement here though, you’re right.

**Comment by cemo** [comment]
I think that https://github.com/fastlane/spaceship/issues/168 is related as well.

**Comment by KrauseFx** [comment]
Sorry for the inconvenience, please disable 2 step verification for now, until the issue is resolved. The best and easiest way is probably to create a separate Apple ID for `fastlane` so that your main account still has 2 step verification enabled.
I'm working on a solution :+1:

**Comment by schwa** [comment]
Any progress?

**Comment by KrauseFx** [comment]
Sorry, no solution for this yet. It would be possible to implement this using the actual 2 step process of verifying the phone number and entering the SMS code, but this doesn't work properly on CI systems like Jenkins and Travis. 
Instead I'd much rather prefer a solution with application specific passwords, but haven't found a way to authenticate with that yet.

**Comment by OE8CLR** [comment]
Hey Felix. Any solution on this problem or should we still disable 2FA? 😕

**Comment by KrauseFx** [comment]
This has been implemented with the most recent fastlane releases, please update to the latest version 👍

**Comment by KrauseFx** [comment]
Hey everyone, _fastlane_ now fully supports both two-factor and two-step verification 👋 

### On your computer 🚀
To use _fastlane_ with two-factor, just run _fastlane_ as you usually would. You'll be asked for the verification method, and a 4 or 6 digits pin. Everything will just work out of the box 📦 

### On your continuous integration system 💻 
Check out the [official two-factor docs](https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth) for more information on how to setup two-step on CI system. You'll have to authenticate on your local machine to get a session cookie, which you then transfer to your CI.

----

If you have any issues setting this up, please submit [a new issue](https://github.com/fastlane-old/spaceship/issues/new) so we can help you get up and running 👍
