### ISSUE TITLE
[Regression] Fastlane scan help doesn't list options anymore

### ISSUE THREAD

**Issue by RichardGuion** [fastlane/fastlane#8381]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The command "fastlane scan --help" does not print a list of options anymore.

fastlane scan --help
  scan

  The easiest way to run tests of your iOS and Mac app

  Commands:
    help  Display global or [command] help documentation
    init  Creates a new Scanfile for you
    tests The easiest way to run tests of your iOS and Mac app

  Global Options:
    --verbose
    -h, --help           Display help documentation
    -v, --version        Display version information

  Author:
    Felix Krause <scan@krausefx.com>

  Website:
    https://fastlane.tools

  GitHub:
    https://github.com/fastlane/fastlane/tree/master/scan

(END)

fastlane scan --help --verbose

[!] Could not find option 'help' in the list of available options: workspace, project, device, toolchain, devices, scheme, clean, code_coverage, address_sanitizer, thread_sanitizer, skip_build, output_directory, output_style, output_types, buildlog_path, include_simulator_logs, formatter, test_without_building, build_for_testing, xctestrun, derived_data_path, result_bundle, sdk, open_report, configuration, destination, xcargs, xcconfig, only_testing, skip_testing, slack_url, slack_channel, slack_message, skip_slack, slack_only_on_failure, use_clang_report_name, custom_report_file_name

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.1                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| highline                  | 1.7.8        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.13.6       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| json                      | 2.0.2        |
| commander                 | 4.4.3        |
| io-console                | 0.4.5        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.3        |
</details>

*generated on:* **2017-02-27**
</details>

**Comment by mfurtak** [comment]
Hi @RichardGuion - thanks for the report. 👍 

You are correct, and this is a known outcome from work done as part of https://github.com/fastlane/fastlane/pull/8297. You can read more about the problems that existed previously that motivated this change for _scan_ and all of the other tools, here: https://github.com/fastlane/fastlane/pull/8129

Because `fastlane scan` is just a shortcut for `fastlane scan tests`, you can get the help information you're looking for by running `fastlane scan tests -h`.

Hope that helps!
