### ISSUE TITLE
snapshot only-testing for specify file can't work

### ISSUE THREAD

**Issue by 84798012** [fastlane/fastlane#8386]
As we know when we run xcode script "xcodebuild -only-testing:TestFileName", it will only run the specified files.
But when run "fastlane snapshot --xcargs "only-testing=TestFileName", it seems not work, all test files will run in current scheme.
I know we can using single scheme and specify to run it.
But does any way to specify file to run the test and produce screenshot ?

**Comment by hjanuschka** [comment]
@84798012 can you try it with 

`fastlane snapshot --xcargs "'-only-testing:TestFileName'"`

**Comment by 84798012** [comment]
@hjanuschka ,it works like a charm.
Thank you very much!!
