### ISSUE TITLE
Windows support for fastlane

### ISSUE THREAD

**Issue by rekhaagarwal** [fastlane/fastlane#8387]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have tried to intsall ruby ( http://rubyinstaller.org/downloads/) and then tried to run "fastlane init".
But it gives me following error:
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.18.3/fastlane_core/lib/fastlane_core/update_checker/update_checker.rb:37:in `fork': fork() function is unimplemented on this machine (NotImplementedError)

I tried to solve the above prob by modifying update_checker.rb file but now I am getting below error:

`C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pty (LoadError)
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/fastlane-2.18.3/fastlane_core/lib/fastlane_core/itunes_transporter.rb:1:in `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/fastlane-2.18.3/fastlane_core/lib/fastlane_core.rb:19:in `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/fastlane-2.18.3/fastlane/lib/fastlane.rb:1:in `<top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/fastlane-2.18.3/fastlane/lib/fastlane/cli_tools_distributor.rb:18:in `take_off'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/fastlane-2.18.3/bin/fastlane:15:in `<top (required)>'
        from C:/Ruby23/bin/fastlane:22:in `load'
        from C:/Ruby23/bin/fastlane:22:in `<main>'`
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Can someone please help in this

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by mfurtak** [comment]
Hi @rekhaagarwal - thanks for the report 👍 

As you have discovered, Windows is not currently a supported platform for _fastlane_. Sorry about that! Since we don't currently have plans to change this, I am going to close this issue for now.

However, if you do more exploration into what it might take to have it work, we would definitely like to hear the results! 🚀
