### ISSUE TITLE
Actions as Plugins

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#839]
So I have an idea for actions which I am happy to implement, what if we had a full plugin system for fastlane, so all people will have to do is subclass from the Action class and it will be registered with fastlane, rather than fastlane having to search specific paths, include the files and then registering the classes.

Why use this ?

- Official Actions for `cert` and `sigh` could be bundled in the gems themselves, meaning it's easier to fix bugs with the action that cause these gems to behave differently when ran under `fastlane`. Potentially this will make it more stable to run a different version of cert with a different version of fastlane provided the action API is compatible. 
- This decouples actions from fastlane, we could have instead the actions as a separate gem, so you can choose to only add what actions you need in your gemfile. The current default ones we bundle with fastlane could be optional.
- We can still bundle them though, all fastlane has to do is keep searching in it's action folder and require them. We simplify the include code as the subclasses will be imported and automatically registered. This allows us to add fastlane support for tools that don't come out of the box with it.
- We can still allow custom actions, all fastlane has to do is keep searching in the fastlane folder and require them. We simplify the include code as the subclasses will be imported and automatically registered.
- Third party gems can add fastlane support without having to open a PR to fastlane making it easier for anyone to adopt support (i.e My Xcake Gem).

**Comment by KrauseFx** [comment]
> This decouples actions from fastlane, we could have instead the actions as a separate gem, so you can choose to only add what actions you need in your gemfile. The current default ones we bundle with fastlane could be optional.

I really like this. Right now you can already do this using the `actions` directory.

I'll think about this, thanks for posting this comment, sounds like a good idea.

**Comment by jcampbell05** [comment]
No problem, let me know if you come to a decision, I will be happy to implement this :)

**Comment by jcampbell05** [comment]
@KrauseFx Had any thoughts on this ?

**Comment by jcampbell05** [comment]
@KrauseFx could you check our my PR, would love to have this in :)

**Comment by lacostej** [comment]
Question: I could see this in the core as well. For example to solve fastlane/fastlane_core#73.

**Comment by jcampbell05** [comment]
@lacostej Could you elaborate ? cc@KrauseFx

**Comment by lacostej** [comment]
@jcampbell05 for the WIP  https://github.com/fastlane/fastlane_core/pull/73#issuecomment-176175716 I could have implemented the 2 different Runner implementations using the Plugin system. It's just an idea.

**Comment by jcampbell05** [comment]
Some great progress made on this issue in these following PRs:

- https://github.com/fastlane/fastlane/pull/881
- https://github.com/fastlane/fastlane/pull/1320
- https://github.com/fastlane/fastlane/pull/4619
- https://github.com/fastlane/fastlane/pull/4622

@KrauseFx good work 🚀 :) 

p.s look at the increase of the PR numbers.

**Comment by KrauseFx** [comment]
Thanks for updating the issue @jcampbell05! It really is big progress. It's actually not the PR number, but also any GitHub issue (since a PR is just an issue). By migrating to the mono repo, the number went up a lot 🚀

**Comment by jcampbell05** [comment]
Some additional work is also being done here:
https://github.com/fastlane/fastlane/pull/4722

**Comment by KrauseFx** [comment]
Thanks again @jcampbell05, I'll close this issue in favor of #4744 🚀
