### ISSUE TITLE
fastlane deliver infinite loop

### ISSUE THREAD

**Issue by domenico-renna** [fastlane/fastlane#8391]
Hi,
today I'm trying to deploy the new version of my app on apple store using fastlane deliver but when script has been saved screenshot and built .ipa the deliver action appear to be in infine loop waiting apple itunesconnect response that never arrive.

This is my custom fastlane configuration:

```ruby
lane :release do
  pem
  cert
  sigh(force: true)
  snapshot(scheme: "app-template", 
           skip_open_summary: true,
           clear_previous_screenshots: true)
  gym(scheme: "apps-template", include_bitcode: true)
  deliver(force: true, 
          overwrite_screenshots: true, 
          submit_for_review: true, 
          automatic_release: true, 
          price_tier: 0,  
          app_icon: "/appstore_icon.png")
end
```

While I'm waiting that infine loop fastlane log somthings like this in console:

```
[14:24:18]: You can tweet: "iTunes Connect #iosprocessingtime 123 minutes"
[14:24:53]: Waiting iTunes Connect processing for build 1.0 (19)... this might take a while...
[14:24:53]: 
[14:24:53]: You can tweet: "iTunes Connect #iosprocessingtime 123 minutes"
[14:25:26]: Waiting iTunes Connect processing for build 1.0 (19)... this might take a while...
[14:25:26]: 
[14:25:26]: You can tweet: "iTunes Connect #iosprocessingtime 124 minutes"
[14:25:59]: Waiting iTunes Connect processing for build 1.0 (19)... this might take a while...
[14:25:59]: 
[14:25:59]: You can tweet: "iTunes Connect #iosprocessingtime 124 minutes"
```

During that loop I receive an apple mail with this content:

> Dear developer,
> 
> We have discovered one or more issues with your recent delivery for "App title". To process your delivery, the following issues must be corrected:
> 
> Invalid Bundle - The embedded bitcode bundle is corrupted. Rebuild your entire app with the latest GM Xcode and submit the app again.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.
> 
> Regards,
> 
> The App Store team

Then this message suggest that built failed but the delivery action don't intercept that fail waiting in infine loop.

How can I automatic manage this kind of fails?

This is my `fastlane env`:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | false                                       |
| Is homebrew         | true                                        |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-02-28**
</details>

**Comment by juli1quere** [comment]
I think this issue is relative to #8152 no ?

**Comment by domenico-renna** [comment]
Yes, do you have any idea on how to work around this bug at the moment?
