### ISSUE TITLE
How to publish "Whats New in this release" in android via supply

### ISSUE THREAD

**Issue by s-gagandeep** [fastlane/fastlane#8398]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I want to update my release notes using supply,
How can i do it.
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by asfalcone** [comment]
@s-gagandeep Check out the documentation here: https://github.com/fastlane/fastlane/tree/master/supply#changelogs-whats-new 🎉

**Comment by s-gagandeep** [comment]
@asfalcone thanks for the reply, i have checked this doc, so i have to manually add "version-code.txt", in changelog folder before running supply everytime.
It would be good if we can add `changelog` action in Supply (which takes text or file path as input).
Thanks

**Comment by codyrotwein** [comment]
I have 300+ apps that all would need the same change log text when updating. Is there some way to create like a Supplyfile that has default changelog text? It looks like you can do something similar in Fastlane for ios, with a Deliverfile (untested) that has:

release_notes({
  'default' => "Stability improvements and minor bug fixes"
})
