### ISSUE TITLE
Not using the custom metadata_path specified

### ISSUE THREAD

**Issue by iOSAppMaker** [fastlane/fastlane#840]
Fastlane Deliver is not using the custom metadata_path specified. Instead it resorts to using the default ./fastlane/metadata folder.

I specified the custom path inside the deliverfile as:
metadata_path 'path/to/custom/folder'

When run, it creates folder at the custom location, but after that shows this y/n prompt "Do you want to overwrite existing metadata on path" and continues to create metadata files in the default location instead of the custom location.

download_metadata and metadata_path is supported from deliver 1.5.0 onwards.

**Comment by iOSAppMaker** [comment]
I think the problem is in commands_generator.rb 
You don't seem to be giving option to use the custom defined path, instead choosing the default path or returning 0. 

Check the pic: 
![commands_generator](https://cloud.githubusercontent.com/assets/15169453/11131230/9c465e44-89af-11e5-8b5d-cf0a1aa35fe8.png)

**Comment by iOSAppMaker** [comment]
I defined the metadata_path both in Deliverfile and also Fastfile

**Comment by iOSAppMaker** [comment]
I think I've fixed the issue in a personal fork, please consider the pull request:
https://github.com/iOSAppMaker/deliver/commit/ffac688756fce575b1526817e3ce6f1fc229c290

**Comment by KrauseFx** [comment]
Thanks again :+1:
