### ISSUE TITLE
fastlane deliver error

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#8401]
Hi,

I am all of a sudden getting the below error using deliver.

./metadata/app_icon.jpg' doesn't seem to be a png file

Looks like some check has changed on the Apple end.

As a workaround, I tried ignoring metadata but still it tries to upload metadata and then throws the error.

fastlane deliver --skip_metadata --skip_screenshots --force

**Comment by mfurtak** [comment]
Do you have a `Deliverfile`? If so, can you show me its contents?

**Comment by santoshshetty2612** [comment]
Hi I don't have much content in the Deliverfile apart from the below two lines.

app_identifier "myapp.company.com" # The bundle identifier of your app
username "build.ci@company.com" # your Apple ID user

A metadata folder is created which contains app_icon.jpg

The error is that the icon should be in png format and not jpg.

**Comment by hjanuschka** [comment]
seems to be related to #8402  i did a PR here: https://github.com/fastlane/fastlane/pull/8418 that should enable/allow jpg files - could you give it a try?

**Comment by santoshshetty2612** [comment]
Hi @hjanuschka, I updated fast lane but still facing the issue.

**Comment by santoshshetty2612** [comment]
My fast lane version is 2.19.1 and deliver version 2.0.1

Error is same /metadata/app_icon.jpg' doesn't seem to be a png file

**Comment by santoshshetty2612** [comment]
I can understand that your PR is not yet merged into master.

**Comment by CedricSoubrie** [comment]
2.19.3 version of deliver. Still the same problem
