### ISSUE TITLE
The format of app_icon

### ISSUE THREAD

**Issue by Xwoder** [fastlane/fastlane#8402]
### New Issue Checklist

- [!] Updated fastlane to the latest version
- [!] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane init 
[20:32:46]: Detected iOS/Mac project in current directory...
[20:32:46]: This setup will help you get up and running in no time.
[20:32:46]: fastlane will check what tools you're already using and set up
[20:32:46]: the tool automatically for you. Have fun! 
[20:32:46]: Created new folder './fastlane'.
...emit...
[20:34:04]: Successfully finished setting up fastlane
```

After all these done. I can find a icon file named `app_icon.jpg` in `./fastlane/metadata`

Then I use `fastlane deliver` to upload ipa, but fastlane exit and output
`[!] './fastlane/metadata/app_icon.jpg' doesn't seem to be a png file`

This is strange. I didn't rename or convert the icon to JPG format.

So I have to convert the icon to PNG format myself.

Is this a bug? I think that the icon image which fastlane downloaded for me should be in PNG format.

Thanks.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.12.0                          |
| Installation Source | /usr/local/bin/fastlane                     |
| Host                | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir        | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version     | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.18.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "RingDiyClient") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "RingDiyClient") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ringhelp.maringhelp" # The bundle identifier of your app
apple_id "zyluo2016@163.com" # Your Apple email address

team_id "3DGEDEJEBC"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.18.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| plist                     | 3.2.0        |
</details>

*generated on:* **2017-03-01**
</details>

**Comment by mfurtak** [comment]
Hi @Xwoder 👋  Thanks for the report.

I think the `app_icon` option is being too restrictive here. It should allow JPG as you say. I'll mark it as a bug.

If you don't use the `app_icon` option for now, can you continue without any other problems?

**Comment by mfurtak** [comment]
Do you have a `Deliverfile`? If so, could you show me its contents?

**Comment by Xwoder** [comment]
My `Deliverfile`
```
###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md


###################### Automatically generated ######################
# Feel free to remove the following line if you use fastlane (which you should)

app_identifier "com.xxxxxx.xxxxxx" # The bundle identifier of your app
username "xxxxxx@xxx.com" # your Apple ID user

```
It generated by `fastlane init` automatically, and I didn't modify it.

**Comment by hjanuschka** [comment]
@Xwoder i did a PR: https://github.com/fastlane/fastlane/pull/8418 which enables support for jpg files too - as of documenation and tests they are supported by iTC. could you give the PR a try?
