### ISSUE TITLE
xcode_server_get_assets action fail to fetch Integrations

### ISSUE THREAD

**Issue by fennecos** [fastlane/fastlane#841]
```
[14:09:28]: Failed to fetch Integrations for Bot e9964c211d5ab063f35680d948032af8 from Xcode Server at https://myserver.local, response: 400: {"status":400,"message":"filter(s) not supported: limit"}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | xcode_server_get_assets             | 0           |
+------+-------------------------------------+-------------+

[14:09:28]: fastlane finished with errors
```

According to Apple documentation, limit parameter does not exist. "last" exists though.

https://developer.apple.com/library/ios/documentation/Xcode/Conceptual/XcodeServerAPIReference/Integrations.html#//apple_ref/doc/uid/TP40016472-CH3-SW2

**Comment by alvarga-stuart** [comment]
You are right. I've modified the file in my local machine and it works. Thanks!

**Comment by KrauseFx** [comment]
Do we need a fix in `fastlane` for that? cc @czechboy0

**Comment by czechboy0** [comment]
Yeah, they probably changed it recently. Feel free to change it to `last` and PR it to fastlane, @fennecos or @alvarga-stuart. /cc @KrauseFx

**Comment by KrauseFx** [comment]
Thanks for jumping in @czechboy0 :+1:

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
