### ISSUE TITLE
[!] Server error (Google::Apis::ServerError)

### ISSUE THREAD

**Issue by bzSega** [fastlane/fastlane#8412]
### Issue Description
I have got this issue after execution this command:

`fastlane supply --skip_upload_metadata --skip_upload_images --skip_upload_screenshots --apk my.apk --json_key "file.json" --package_name com.mikhaylov.kolesov.plasticinechristmaswidgets --track alpha --rollout 1.0
`

[INSERT OUTPUT HERE]

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.3                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.5.1        |
| activesupport             | 4.2.1        |
| colored                   | 1.2          |
| xcodeproj                 | 0.23.1       |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.24       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-03-01**
</details>
[INSERT OUTPUT HERE]

**Comment by hjanuschka** [comment]
@bzSega  is this issue still existing? - can you please run fastlane with --verbose and share the full output?

for the little information - i suspect there was a server error on google side.

**Comment by bzSega** [comment]
Yes this issue still existing. 
I will run fastlane with--verbose later because now i have exceeded daily save quota.

**Comment by hjanuschka** [comment]
daily save quote? are you running it behind a proxy or on some CI - might be a network issue then...

**Comment by bzSega** [comment]
> or the little information - i suspect there was a server error on google side.
I agree with you. But how to understand, why i have faced with this issue;

**Comment by bzSega** [comment]
> daily save quote? are you running it behind a proxy or on some CI - might be a network issue then...

Yes, i tried about three times to upload my apk and after that i got this issue.

**Comment by Reyske** [comment]
Same problem here! same environment

**Comment by bzSega** [comment]
Hi, @hjanuschka . Here is results with --verbose.

```
segama$ fastlane supply --skip_upload_metadata --skip_upload_images --skip_upload_screenshots --apk /Users/segama/Developer/AndroidStudioProjects/kmplasticinechristmaswidgets/PlasticineChristmasWidgets/build/outputs/apk/PlasticineChristmasWidgets-release.apk --json_key "Google Play Android Developer-6d92c377779b.json" --package_name com.mikhaylov.kolesov.plasticinechristmaswidgets --track alpha --verbose

+-------------------------+------------------------------------------------------------------------+
|                                    Summary for supply 2.19.1                                     |
+-------------------------+------------------------------------------------------------------------+
| skip_upload_metadata    | true                                                                   |
| skip_upload_images      | true                                                                   |
| skip_upload_screenshots | true                                                                   |
| apk                     | /Users/segama/Developer/AndroidStudioProjects/kmplasticinechristmas... |
| json_key                | Google Play Android Developer-6d92c377779b.json                        |
| package_name            | com.mikhaylov.kolesov.plasticinechristmaswidgets                       |
| track                   | alpha                                                                  |
| rollout                 | 0.1                                                                    |
| metadata_path           | ./metadata                                                             |
| skip_upload_apk         | false                                                                  |
| validate_only           | false                                                                  |
+-------------------------+------------------------------------------------------------------------+

DEBUG [2017-03-03 12:08:34.41]: Fetching a new access token from Google...
INFO [2017-03-03 12:08:36.65]: Preparing to upload for language 'en-US'...
INFO [2017-03-03 12:08:37.50]: Preparing to upload for language 'ru-RU'...
INFO [2017-03-03 12:08:37.82]: Preparing apk at path '/Users/segama/Developer/AndroidStudioProjects/kmplasticinechristmaswidgets/PlasticineChristmasWidgets/build/outputs/apk/PlasticineChristmasWidgets-release.apk' for upload...
INFO [2017-03-03 12:08:41.53]: Updating track 'alpha'...
INFO [2017-03-03 12:08:42.10]: Uploading all changes to Google Play...

Looking for related GitHub issues on fastlane/fastlane...
Search query: Server error

URL: https://api.github.com/search/issues?q=Server%20error+repo:fastlane/fastlane
➡️  [!] Server error (Google::Apis::ServerError)
   https://github.com/fastlane/fastlane/issues/8412 [open] 6 💬
   19 hours ago

➡️  ERROR 65: Your shell environment is not correctly configured
   https://github.com/fastlane/fastlane/issues/8157 [open] 7 💬
   2 weeks ago

➡️  Automaticaly retry failed requests on an internal server error for iTunesConnect
   https://github.com/fastlane/fastlane/pull/8017 [closed] 1 💬
   5 weeks ago

and 374 more at: https://github.com/fastlane/fastlane/search?q=Server%20error&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:214:in `check_status': [!] Server error (Google::Apis::ServerError)
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/api_command.rb:104:in `check_status'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:179:in `process_response'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:286:in `execute_once'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:107:in `block (2 levels) in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:104:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:54:in `block in retriable'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/retriable-2.1.0/lib/retriable.rb:48:in `retriable'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/http_command.rb:96:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/lib/google/apis/core/base_service.rb:351:in `execute_or_queue_command'
	from /Library/Ruby/Gems/2.0.0/gems/google-api-client-0.9.24/generated/google/apis/androidpublisher_v2/service.rb:91:in `commit_edit'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/supply/lib/supply/client.rb:113:in `block in commit_current_edit!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/supply/lib/supply/client.rb:360:in `call_google_api'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/supply/lib/supply/client.rb:113:in `commit_current_edit!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/supply/lib/supply/uploader.rb:36:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/supply/lib/supply/commands_generator.rb:59:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/supply/lib/supply/commands_generator.rb:12:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

**Comment by hjanuschka** [comment]
for me it still looks like a proxy/isp/ci issue - can you try it with a different internet connection?
also check if you have either `http_proxy` and/or `https_proxy` ENV set. maybe trying unsetting it fixes it.

**Comment by mfurtak** [comment]
@bzSega I was able to successfully distribute an alpha with the following command (modeled from yours)

```
fastlane supply --skip_upload_metadata --skip_upload_images --skip_upload_screenshots --apk app/build/outputs/apk/app-release.apk --track alpha --verbose
```

This feels like perhaps something beyond _fastlane_. The type of error returned in your example indicates a 5xx HTTP response, usually indicating a problem on the receiving end.

**Comment by bzSega** [comment]
Ok. I will try to change environment.

**Comment by bzSega** [comment]
I solved this issue. The problem was in an Alpha testing settings, i didn't choose a testing method.

https://support.google.com/googleplay/android-developer/answer/3131213

@hjanuschka , I recommends you to add detailed server answer, because when i used native Python script for Android Play Publisher API, i had saw URL address with package name. It means that problem in separate app.

`googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/androidpublisher/v2/applications/com.mikhaylov.kolesov.plasticinechristmaswidgets/edits/01514358816717008128:commit?alt=json returned "">`

**Comment by hjanuschka** [comment]
@bzSega glad you got it sorted out! - i am going to close this.
thx for the hint with the detailed error information, while trying to add support for it, i stumbled upon a env `DEBUG`  once you set `DEBUG=1` it should run with full google api debug 👍

**Comment by Cyclic** [comment]
@bzSega, thank you for your answer. Can you please provide a little more detail or a screenshot where you set your alpha testing method? I created the user list and remember choosing closed beta, but I don't see anywhere to modify the setting.
