### ISSUE TITLE
Simulator log collecting failing for iOS 9 devices

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#8421]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

When `scan` collects logs for an iOS 9 device, it throws an error code 2. Stepping through the code indicates that it fails when trying to collect the log:

```ruby
FastlaneCore::Simulator
...
def copy_logarchive(device, log_identity, logs_destination_dir)
  sim_resource_dir = FastlaneCore::CommandExecutor.execute(command: "xcrun simctl getenv #{device.udid} SIMULATOR_SHARED_RESOURCES_DIRECTORY 2>/dev/null", print_all: true, print_command: true)
  logarchive_src = File.join(sim_resource_dir, "system_logs.logarchive")
  logarchive_dst = File.join(logs_destination_dir, "system_logs-#{log_identity}.logarchive")

  # if logarchive already exists it fails as the .logarchive is a directory, so delete it. to be sure its gone
  FileUtils.rm_rf(logarchive_src)
  FileUtils.rm_rf(logarchive_dst)

  command = "xcrun simctl spawn #{device.udid} log collect 2>/dev/null"
  FastlaneCore::CommandExecutor.execute(command: command, print_all: true, print_command: true)

  FileUtils.mkdir_p(logarchive_dst)
  FileUtils.cp_r("#{logarchive_src}/.", logarchive_dst)
  UI.success "Copying file '#{logarchive_src}' to '#{logarchive_dst}'..."
end
```

This is the command that fails:
```ruby
FastlaneCore::CommandExecutor.execute(command: command, print_all: true, print_command: true)
```
With:
```sh
xcrun simctl spawn DF0DD7F4-D944-4800-9D65-2095BF444C3C log collect
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
The operation couldn’t be completed. No such file or directory
No such file or directory
```

Is the answer to collect the logs via this file for < ios10.0 devices?
```sh
~/Library/Logs/CoreSimulator/DF0DD7F4-D944-4800-9D65-2095BF444C3C/system.log
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

N/A

**Comment by lyndsey-ferguson** [comment]
@russbishop should `log collect` work for iOS 9 devices?

**Comment by lyndsey-ferguson** [comment]
@hjanuschka FYI

**Comment by russbishop** [comment]
No, the new logging subsystem does not apply to iOS 9.

**Comment by lyndsey-ferguson** [comment]
Ok, I'll put a fix in so that it gets the log file for <=iOS 9 devices

**Comment by lyndsey-ferguson** [comment]
I'm working on this issue [here](https://github.com/fastlane/fastlane/pull/8433). I have to add tests and am considering that the best place should be in the 'fastlane_core/spec/simulator_spec.rb' as that is testing the class functions

**Comment by hjanuschka** [comment]
PR seems to be merged, ready to close @lyndsey-ferguson great work, @russbishop many thx for your help here.

**Comment by lyndsey-ferguson** [comment]
Thanks, yes, this issue can be closed
