### ISSUE TITLE
How to verify app-thinning actually works?

### ISSUE THREAD

**Issue by cnordvik** [fastlane/fastlane#8427]
We enabled app-thinning in the Fastfile.

```
gym(
     workspace: "MyApp.xcworkspace",
     scheme: "MainApp",
     export_options: {
        method: "app-store",
        thinning: “<thin-for-all-variants>”
     }
   )
```

Result: App went from 45.2MB compressed size to 87.9MB compressed size according to Testflight. Also the device specific sizes in Testflight shows increase from 87.8MB install size to 149MB install size for iPhone 5c.

So is Testflight wrong or did those options make our app crazy big?

The app thinning size report said it could reduce our app to 53MB uncompressed and 25MB compressed. Is there any chance of verifying this is the case without submitting the app to the AppStore?

**Comment by juli1quere** [comment]
As far as I know, `gym` is just a pass-through on this app thinning topic. It just forward `export_options` to the `xcodebuild` `-exportOptionsPlist` file. Your configuration seems to fit what's required by `xcodebuild -help`: 

>  thinning : String
> 
> For non-App Store exports, should Xcode thin the package for one or more device variants? Available options: \<none\> (Xcode produces a non-thinned universal app), \<thin-for-all-variants\> (Xcode produces a universal app and all available thinned variants), or a model identifier for a specific device (e.g. "iPhone7,1"). Defaults to \<none\>.

So, for me this is not a fastlane issue. 

I think you can take a look at [this doc from Apple](https://developer.apple.com/library/content/qa/qa1795/_index.html) (especially the `Getting an App Size Report` part).

**Comment by cnordvik** [comment]
Kind of agree I guess. Think I just have to trust the docs and close my eyes and hope for the best.
