### ISSUE TITLE
download_all name file conflict 

### ISSUE THREAD

**Issue by elianfish** [fastlane/fastlane#8430]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We have the following command to create a profile file

fastlane sigh -a com.ysl.apple -u ysl@163.com -n apple_appstore

Finally, the local storage name is InHouse_com.ysl.apple.mobileprovision

But when we updated the profile and execute the download command:

fastlane sigh download_all -u ysl@163.com

Its local storage name becomes InHouse_41939ba6-6190-4024-a7d7-e69922752778_com.ysl.apple.mobileprovision

Excuse me, create a new profile and re-download the profile, the storage name can be consistent?

**Comment by hjanuschka** [comment]
@elianfish this has been introduced by: https://github.com/fastlane/fastlane/pull/8082

@lgaches   could you do a follow-up PR also handling the initial filename ?  (or let me know if you don't have time for it)

**Comment by lgaches** [comment]
I'll take it

**Comment by hjanuschka** [comment]
@lgaches awesome 🚀  let me know if you need any help. and feel free to direct ping me on the PR so i can review it!

**Comment by mfurtak** [comment]
If we change the initial file name that _sigh_ generates, might that mess up people's setups?

**Comment by KrauseFx** [comment]
Yeah, as @mfurtak said, it would mess with other setups that assume the file name. I'll close the issue for now 👍
