### ISSUE TITLE
Summary not reporting all devices

### ISSUE THREAD

**Issue by zarghol** [fastlane/fastlane#8432]
### Issue Description
Hi ! 
I ran fastlane snapshot with 3 devices et 5 languages, all worked, but the summary only contains 2 devices...

I will run again the command to check if the bug persist, but even if it works, there's a random bug :-)

Thanks for your help !
##### Output

[Output fastlane.txt](https://github.com/fastlane/fastlane/files/816815/Output.fastlane.txt)
[Snapfile.txt](https://github.com/fastlane/fastlane/files/816819/Snapfile.txt)
[screenshots.html.txt](https://github.com/fastlane/fastlane/files/816827/screenshots.html.txt)

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                                          |
| ------------------- | -------------------------------------------------------------- |
| OS                  | 10.12.2                                                        |
| Ruby                | 2.0.0                                                          |
| Bundler?            | false                                                          |
| Git                 | git version 2.10.1 (Apple Git-78)                              |
| Installation Source | /usr/local/bin/fastlane                                        |
| Host                | Mac OS X 10.12.2 (16C67)                                       |
| Ruby Lib Dir        | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version     | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained        | false                                                          |
| Is homebrew         | false                                                          |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version       | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.4        |
| activesupport             | 4.2.6        |
| xcodeproj                 | 1.0.0        |
| claide                    | 1.0.1        |
</details>

*generated on:* **2017-03-03**
</details>

**Comment by zarghol** [comment]
After a second launch, the bug is still there

**Comment by juli1quere** [comment]
I reproduced your issue here. I think the issue is concerning iPhone SE, since this `Snapfile` just shows an empty report: 

```
 devices([
   "iPhone SE"
    ])

languages([
  "fr-FR"
])
```

And, when we add another device, it just displays the other device. I'm currently digging to understand why there is this bug, and how to fix it.

**Comment by juli1quere** [comment]
Indeed, it's an issue specific to iPhone SE. I'm making a PR to fix this ;)

**Comment by mfurtak** [comment]
Thanks for the report! We'll ship this fix in the next _fastlane_ release 🚀

**Comment by zarghol** [comment]
Thank you for the fix ! 👍

**Comment by mfurtak** [comment]
Yes, thanks @juli1quere 👏  👏
