### ISSUE TITLE
Automatically use 12.9-Inch Display for 9.7-Inch Display.

### ISSUE THREAD

**Issue by luisherranz** [fastlane/fastlane#8435]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It looks like you can use 5.5inch screenshots to populate all iPhone screenshots automatically, like this:
![screen shot 2017-03-03 at 16 24 20](https://cloud.githubusercontent.com/assets/3305402/23556726/dfc7db02-002d-11e7-8b0a-9df6b40ce45f.png)

But you can't do the same for iPad and 12.9 -> 9.7 inch. The checkbox is unmarked by default and there is no way to check it using fastlane:
![screen shot 2017-03-03 at 16 25 15](https://cloud.githubusercontent.com/assets/3305402/23556766/fff4a8e2-002d-11e7-84dc-f67ecf308262.png)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[!] The request could not be completed because:
        You must add at least one 9.7-Inch Display screenshot or use screenshots from a larger display. [zh-Hans]: You must add at least one 9.7-Inch Display screenshot or use screenshots from a larger display.
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.3                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.5.4 (Apple Git-61)            |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.11.3 (15D21)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 7.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-03**
</details>

**Comment by alexdmotoc** [comment]
I am also facing this problem. I am providing only the 5.5-Inch and iPad Pro screenshots, but the checkbox for smaller resolutions isn't automatically set to use the larger ones.

**Comment by KrauseFx** [comment]
Hey, thanks for reporting this. We want _fastlane_ to work out of the box with the default values for screenshots. When you run _snapshot_ and _deliver_ it should automatically generate the correct kind of screenshots to fill out all the required metadata. 

That seems to be not the case according to your submitted information. How can we update _fastlane_ to make it work again? Is the problem when generating the screenshots, or the uploading part?

**Comment by alexdmotoc** [comment]
We have the same app rebranded into 100+ apps, which all are submitted to App Store. When we submitted the apps there wasn't an option to reuse larger resolutions for smaller devices.

I'm talking about this checkbox in the iTunesConnect media manager:
<img width="180" alt="screen shot 2017-03-15 at 21 43 42" src="https://cloud.githubusercontent.com/assets/6683120/23967686/8ec5a4a6-09c8-11e7-9ec4-7cd866a7b9fe.png">

Since then we redesigned the app and now we want to update all versions. I have a set of predefined screenshots that I want to submit for all the apps, but they are only for the 5.5 - Inch devices and large iPad pro.

I wanted to use fastlane to submit the update for each app, together with the new screenshots - i.e. replace the old ones with the larger screenshots, and use the large screenshots for smaller devices as well (check the boxes that allow you to use the higher resolution screenshots)

I didn't find a way to do that, so I recreated the screenshots for every device

**Comment by luisherranz** [comment]
That's right. That's the exact same problem we are having. We want to upload only the necessary screenshots and let iTunes generate the other ones. That's possible in iPhone because those checkboxes are checked, but the iPad checkbox is not checked.

**Comment by KrauseFx** [comment]
I just tried this for my app, and everything seemed to be working as expected. I added the following devices to my `Snapfile`

```ruby
languages([
  "en-US"
])

devices ["iPhone 5", "iPhone 7", "iPhone SE", "iPhone 7 Plus"]

scheme "wwdcfamily"
reinstall_app true
```
and uploaded them using `fastlane deliver`, which results on the following

<img width="1835" alt="screenshot 2017-04-10 09 10 07" src="https://cloud.githubusercontent.com/assets/869950/24892518/1a5c8192-1e32-11e7-839b-2937e041fd1c.png">

---


<img width="632" alt="screenshot 2017-04-10 09 09 59" src="https://cloud.githubusercontent.com/assets/869950/24892517/1a588038-1e32-11e7-878b-8bdef66c1ce1.png">

---

I don't have 3.5" simulators installed any more, so _deliver_ automatically enabled the iTunes Connect scaling for that screenshot family only 👍 

From my perspective it seems like things work as expected. Please let me know how things should behave differently

**Comment by KrauseFx** [comment]
Also I submitted this patch for improved default simulator selection https://github.com/fastlane/fastlane/pull/8843

**Comment by luisherranz** [comment]
@KrauseFx, iPhone screenshots work as expected.

The problem is when apps can be used both in iPhone and iPad. In that case, the checkbox to automatically generate 9.7 screenshots from your 12.9 screenshots is not checked by default. The result is that you need to upload 9.7 screenshots as well or check it manually.

**Comment by KrauseFx** [comment]
Alright, thanks for clarifying, I'll take a closer look at the iPad screenshots later today

**Comment by luisherranz** [comment]
Thanks Felix!

**Comment by KrauseFx** [comment]
Hey @luisherranz, sorry for the delay on my side, looking into this now 👍

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/9072 👍

**Comment by luisherranz** [comment]
Awesome, thanks @KrauseFx!

**Comment by KrauseFx** [comment]
I'll close this for now, please re-open if you still experience the issue after the next release 👍
