### ISSUE TITLE
Extending jira action to update fix version field

### ISSUE THREAD

**Issue by yuriy-tolstoguzov** [fastlane/fastlane#8442]
### Issue Description
Our team have implemented couple of small actions to automate updating JIRA issues with fix version that were mentioned in git log. Here is example of usage:

```ruby
set_jira_fix_version(
    url: 'http://my-jira.com',
    username: 'username',
    issue_ids: jira_issue_ids_from_changelog, # <- second action
    version_name: '1.0.0', # calculated beforehand
    project_key: 'IOS'
)
```

So, here:
- `jira_issue_ids_from_changelog` searches log for issue ids in format `[project_key]-[number]`. By default starting from previous tag.
- `set_jira_fix_version` creates version if needed and updates issues with fix version. A password is stored in CredentialsManager. I also `jira` action in fastlane that create comments, so probably it would make sense to extend this one, instead of creating new action.

I was wondering would it be usable by a big majority of developers, because I don't have numbers, but JIRA seems one of the most popular tracking systems. In this case I will prepare pull request here.
Other solution will be to release it as standalone plugin as you suggested in the documentation.

I would like to hear your opinion on that. Thanks!

**Comment by beloso** [comment]
I'd like this. Additionally there could be an action to process a changelog from JIRA ID's.

I've done something similar, but I am not really sure if it's ready for public use.

**Comment by yuriy-tolstoguzov** [comment]
@Beloso both actions are more or less ready for public. Question is: will it be part of fastlane or standalone plugin.

**Comment by hjanuschka** [comment]
as suggested in the  [CONTRIBUTING](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md#new-actions) - this should start as a fastlane plugin, once there is enough usage and stable code, we can think of integrating it.

i would love to see a strong jira fastlane plugin, let me know if you need any help on the process of creating a plugin.

documentation should be here: https://docs.fastlane.tools/plugins/create-plugin/

**Comment by yuriy-tolstoguzov** [comment]
Got it.
