### ISSUE TITLE
fastlane pem command error: Apple provided the following error info: Unexpected error occured

### ISSUE THREAD

**Issue by tuchangwei** [fastlane/fastlane#8444]
After I input bundle identifier of my app, it shows:

[!] Apple provided the following error info:
	Unexpected error occured
	An unexpected error occurred. Please try again.  If the problem persists, please contact Apple Developer Program Support.
https://developer.apple.com/support

It was ok yesterday.

<details>

<summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.2.4                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version     | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained        | true                                        |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-06**
</details>

**Comment by hjanuschka** [comment]
@tuchangwei thx for stopping by - can you please provide a bit more information.


what lane do you run, how does your fastfile look - from the little information right now i don't see a chance to help you.

**Comment by tuchangwei** [comment]
@hjanuschka Thanks for your reply. 

I used `fastlane pem`. Then I supplied my Apple ID Username, then I chose the team, then I supplied The bundle identifier of my app, then it shows `Creating a new push certificate for app 'xxxx'`, after that, it shows

 `Looking for related GitHub issues on fastlane/fastlane...` 

and
```
[!] Apple provided the following error info:
	Unexpected error occured
	An unexpected error occurred. Please try again.  If the problem persists, please contact Apple Developer Program Support.
https://developer.apple.com/support
```

**Comment by hjanuschka** [comment]
@tuchangwei thx - could you do me a favor and run it via fastfile.

fastlane/Fastfile:

```ruby
lane :pem_try do
  pem(team_id: "XXX", app_identifier: "app.id", username:"appleid@host.com")
end
```

and than run it with: `fastlane --verbose pem_try` - then we should get a stacktrace. that you might share with us, to tackle the issue.

**Comment by tuchangwei** [comment]
@hjanuschka Sorry, I don't know where the Fastfile is, I installed fastlance by clicking the install file, like:

<img width="614" alt="wx20170306-152357 2x" src="https://cloud.githubusercontent.com/assets/2604045/23600297/f2992358-0280-11e7-8fe9-b7cf1fc6afa8.png">

Could you tell me where the Fastfile is, thanks

**Comment by hjanuschka** [comment]
ohhh - ok lets try it - open up a terminal - and `cd ` into your project.
create a folder `fastlane` (`mkdir fastlane`) - and put in a file `Fastfile` with the above contents.

again cd to your project and run `fastlane --verbose pem_try`

**Comment by tuchangwei** [comment]
Hi, @hjanuschka 
The log is as following, please have a look.

DEBUG [2017-03-06 15:33:24.51]: Checking if there are any plugins that should be loaded...
INFO [2017-03-06 15:33:24.54]: Driving the lane 'pem_try' 🚀
INFO [2017-03-06 15:33:24.55]: -----------------
INFO [2017-03-06 15:33:24.55]: --- Step: pem ---
INFO [2017-03-06 15:33:24.55]: -----------------

+------------------+-------------------------------------------------------------------------------+
|                                      Summary for PEM 2.19.1                                      |
+------------------+-------------------------------------------------------------------------------+
| team_id          | xxx                                                                    |
| app_identifier   | app.id |
| username         | changweitu@gmail.com                                                          |
| development      | false                                                                         |
| generate_p12     | true                                                                          |
| force            | false                                                                         |
| save_private_key | true                                                                          |
| output_path      | .                                                                             |
+------------------+-------------------------------------------------------------------------------+

INFO [2017-03-06 15:33:24.91]: Starting login with user 'changweitu@gmail.com'
INFO [2017-03-06 15:33:34.79]: Successfully logged in
WARN [2017-03-06 15:33:35.71]: Creating a new push certificate for app 'app.id'.
WARN [2017-03-06 15:33:43.26]: Lane Context:
INFO [2017-03-06 15:33:43.26]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"pem_try"}
ERROR [2017-03-06 15:33:43.26]: {"responseId"=>"13bc75a0-65fb-400b-adff-98d37322ef91", "resultCode"=>-1, "resultString"=>"Unexpected error occured", "userString"=>"An unexpected error occurred. Please try again.  If the problem persists, please contact Apple Developer Program Support.\nhttps://developer.apple.com/support", "creationTimestamp"=>"2017-03-06T07:33:43Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/submitCertificateRequest.action", "httpCode"=>200}
INFO [2017-03-06 15:33:43.26]: Successfully generated documentation at path '/Users/vale/Documents/iOS/Workspace/Heath/celebtts/fastlane/README.md'

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 💥   | pem    | 18          |
+------+--------+-------------+

ERROR [2017-03-06 15:33:43.27]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Apple provided the following error info:
	Unexpected error occured
	An unexpected error occurred. Please try again.  If the problem persists, please contact Apple Developer Program Support.
https://developer.apple.com/support

URL: https://api.github.com/search/issues?q=Apple%20provided%20the%20following%20error%20info:%0A%09Unexpected%20error%20occured%0A%09An%20unexpected%20error%20occurred.%20Please%20try%20again.%20%20If%20the%20problem%20persists,%20please%20contact%20Apple%20Developer%20Program%20Support.%0Ahttps://developer.apple.com/support+repo:fastlane/fastlane
➡️  fastlane pem command error: Apple provided the following error info: Unexpected error occured
   https://github.com/fastlane/fastlane/issues/8444 [open] 5 💬
   6 minutes ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/spaceship/lib/spaceship/client.rb:453:in `parse_response': [!] Apple provided the following error info: (Spaceship::Client::UnexpectedResponse)
	Unexpected error occured
	An unexpected error occurred. Please try again.  If the problem persists, please contact Apple Developer Program Support.
https://developer.apple.com/support
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/spaceship/lib/spaceship/portal/portal_client.rb:419:in `create_certificate!'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/spaceship/lib/spaceship/portal/certificate.rb:299:in `create!'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/pem/lib/pem/manager.rb:46:in `create_certificate'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/pem/lib/pem/manager.rb:30:in `start'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/actions/pem.rb:16:in `run'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:2:in `block in parsing_binding'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /Users/vale/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.19.1/bin/fastlane:15:in `<top (required)>'
	from /Users/vale/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/vale/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by hjanuschka** [comment]
@tuchangwei  - can you check if your apple-id has admin permissins, i guess thats required to create new certificates?

**Comment by tuchangwei** [comment]
@hjanuschka  I think I have the related-permission. I had used the command line to create 9 push certifications yesterday. But in the today morning, the error showed.

**Comment by hjanuschka** [comment]
thats strange, could you try creating it via the apple website? to find out if its fastlane related or not.

**Comment by tuchangwei** [comment]
@hjanuschka  it is really odd, I changed to another app bundle id, it worked. 😓
