### ISSUE TITLE
How to provide a Apple ID for init

### ISSUE THREAD

**Issue by Xwoder** [fastlane/fastlane#8446]
### New Issue Checklist

- [!] Updated fastlane to the latest version
- [!] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It seems that I couldn't provide a  Apple ID for `fastlane init`, like
```shell
fastlane init -u xxx@gmail.com
```
or
```shell
fastlane init --username xxx@gmail.com
```
So, I have to enter the Apple ID every time. For some reason, I need to use the command `fastlane init` frequently.

I think it's better to provide an option to pass Apple ID like `cert` or `deliver`

```shell
fastlane cert -u xxx@gmail.com
fastlane deliver --username xxx@gmail.com
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12                                       |
| Ruby                | 2.3.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.12.0                          |
| Installation Source | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version     | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.5       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.6        |
| colored                   | 1.2          |
| claide                    | 1.0.0        |
| xcodeproj                 | 1.3.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-03-06**
</details>

**Comment by hjanuschka** [comment]
for the record this PR solved it: https://github.com/fastlane/fastlane/pull/8594

**Comment by Xwoder** [comment]
@hjanuschka, after I updated `fastlane` to the version `2.22.0`, I typed `fastlane init --help` and suddenly found that there was an option `-u`. So I closed the issue. Thank you!

**Comment by hjanuschka** [comment]
@Xwoder glad it works now , i just posted the PR in case some one else stumbles upon the issue, as its always awesome to know what solved an issue 👍 

happy fastlane-ing ❤️

**Comment by KrauseFx** [comment]
Yeah, that's awesome, thanks to the work by @mfurtak and @nafu the `--help` command is now a lot more precisely 👍
