### ISSUE TITLE
What is updated if calling sudo gem update fastlane

### ISSUE THREAD

**Issue by bb-git** [fastlane/fastlane#845]
I just want to know if all components (snapshot, deliver, etc.) will be updated or just fastlane. I hacked snapshot to fit my needs and I don't want to overwrite it.
Also I didn't understand, will the old UIAutomization using .js files still work in newer versions of snapshot?

**Comment by KrauseFx** [comment]
The dependencies are all defined here: https://github.com/fastlane/fastlane/blob/master/fastlane.gemspec

**Comment by ohwutup** [comment]
Going to close this issue for now as it seems like the question was answered. @bb-git if you still have any questions please reopen the issue and let us know!
