### ISSUE TITLE
Fastlane Match should be configurable with git email & username

### ISSUE THREAD

**Issue by bes** [fastlane/fastlane#8450]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running the following command

```
match(
      type: "development",
      force: true,
      app_identifier: ["A", "B", "C"],
    )
```

I have recently started to get this error:

```
INFO [2017-03-06 15:02:23.81]: 🔒  Successfully encrypted certificates repo
INFO [2017-03-06 15:02:23.81]: Pushing changes to remote git repo...
INFO [2017-03-06 15:02:23.81]: $ git add -A
INFO [2017-03-06 15:02:23.82]: $ git commit -m \[fastlane\]\ Updated\ development\ and\ platform\ ios
INFO [2017-03-06 15:02:23.85]: ▸ *** Please tell me who you are.
INFO [2017-03-06 15:02:23.85]: ▸ Run
INFO [2017-03-06 15:02:23.85]: ▸ git config --global user.email "you@example.com"
INFO [2017-03-06 15:02:23.85]: ▸ git config --global user.name "Your Name"
INFO [2017-03-06 15:02:23.85]: ▸ to set your account's default identity.
INFO [2017-03-06 15:02:23.85]: ▸ Omit --global to set the identity only in this repository.
INFO [2017-03-06 15:02:23.85]: ▸ fatal: unable to auto-detect email address (got 'XXX@YYY.(none)')
```

I don't know why I have started seeing this error now.

Anyway, my problem is that I do NOT want to set global git email/username. It would be nice if fastlane match could apply those values (to the temp git directory) as user configurable parameters instead.

BR

**Comment by bes** [comment]
Maybe it has got something to do with the fact that I recently updated git to version 2.12.0 via homebrew?

**Comment by KrauseFx** [comment]
This has something to do with your local git setup, not sure if it would be useful to add options to _match_ for this. Can you make sure to follow the instructions to set it?

**Comment by bes** [comment]
Hi @KrauseFx, do you suggest I use`git config --global user.email` / `git config --global user.name`? Unfortunately that will not work for me :(

What about this: could match use the credentials from the git where the Fastfile / Matchfile are checked in, and use those credentials for creating patches in the "fastlane match" repository?

That would suit my use case, because then I would get the identity from the code git into the certs/profiles git.

Or am I just being stupid, does this kind of configuration exist implicitly somewhere already?

**Comment by hjanuschka** [comment]
@bes can you checkout this PR https://github.com/fastlane/fastlane/pull/8550 i think it addresses your issue

**Comment by bes** [comment]
@hjanuschka Thank you, perfect.
