### ISSUE TITLE
icon.png not uploading to Google Play

### ISSUE THREAD

**Issue by dpettit** [fastlane/fastlane#8454]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am running fastlane supply to upload metadata, including screengrabs and icons to Google Play, and everything seems to upload, except for the icon.png.  If I add icon.png manually through the Google Play Developer Console, it is a simple drag and drop, and the upload completes without any errors.

I do have SKIP_UPLOAD_APK set to "true", but I'm assuming that only applies to the .apk, and wouldn't prevent the upload of icon.png, correct?

Any ideas on what might be preventing the upload of icon.png?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
+-------------------------+------------------------------------------------------------------------+
|                                    Summary for supply 2.19.1                                     |
+-------------------------+------------------------------------------------------------------------+
| skip_upload_apk         | true                                                                   |
| apk                     | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Output-TS-B... |
| package_name            | com.talespring.mydaddy.android                                         |
| track                   | production                                                             |
| rollout                 | 0.1                                                                    |
| metadata_path           | ./fastlane/metadata/android                                            |
| json_key                | /Users/tsdev/Documents/TaleSpring/RandD/TS-Auto-Publish/Resources/f... |
| skip_upload_metadata    | false                                                                  |
| skip_upload_images      | false                                                                  |
| skip_upload_screenshots | false                                                                  |
| validate_only           | false                                                                  |
+-------------------------+------------------------------------------------------------------------+

[13:03:02]: Preparing to upload for language 'en-US'...
[13:03:03]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/1.png...
[13:03:07]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/3.png...
[13:03:12]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/4.png...
[13:03:16]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/7.png...
[13:03:20]: Uploading screenshot ./fastlane/metadata/android/en-US/images/phoneScreenshots/9.png...
[13:03:25]: Uploading screenshot ./fastlane/metadata/android/en-US/images/sevenInchScreenshots/1.png...
[13:03:34]: Uploading screenshot ./fastlane/metadata/android/en-US/images/sevenInchScreenshots/3.png...
[13:03:41]: Uploading screenshot ./fastlane/metadata/android/en-US/images/sevenInchScreenshots/4.png...
[13:03:48]: Uploading screenshot ./fastlane/metadata/android/en-US/images/sevenInchScreenshots/7.png...
[13:03:55]: Uploading screenshot ./fastlane/metadata/android/en-US/images/sevenInchScreenshots/9.png...
[13:04:04]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/1.png...
[13:04:15]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/3.png...
[13:04:27]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/4.png...
[13:04:38]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/7.png...
[13:04:48]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/9.png...
[13:05:00]: Uploading all changes to Google Play...
[13:05:03]: Successfully finished the upload to Google Play

Completed .apk processing (Android).
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.12.3                                     |
| Ruby                | 2.3.3                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir        | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version     | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.5        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-03-06**
</details>

**Comment by hjanuschka** [comment]
do you have your icon inside `fastlane/metadata/android/de-DE/images/icon.png` ?
with the file in the metadata folder it works - could you share a `ls -lR fastlane/`  output?

```
+-------------------------+---------------------------------------+
|                    Summary for supply 2.19.0                    |
+-------------------------+---------------------------------------+
| json_key                | fastlane/google_play_key.json         |
| track                   | beta                                  |
| package_name            | krone.at.fxf                          |
| rollout                 | 0.1                                   |
| metadata_path           | ./fastlane/metadata/android           |
| apk                     | app/build/outputs/apk/app-release.apk |
| skip_upload_apk         | false                                 |
| skip_upload_metadata    | false                                 |
| skip_upload_images      | false                                 |
| skip_upload_screenshots | false                                 |
| validate_only           | false                                 |
+-------------------------+---------------------------------------+

[19:32:04]: Preparing to upload for language 'de-DE'...
[19:32:05]: Uploading image file ./fastlane/metadata/android/de-DE/images/featureGraphic.png...
[19:32:07]: Uploading image file ./fastlane/metadata/android/de-DE/images/icon.png...
[19:32:10]: Uploading screenshot ./fastlane/metadata/android/de-DE/images/phoneScreenshots/1.png...
[19:32:14]: Uploading screenshot ./fastlane/metadata/android/de-DE/images/phoneScreenshots/2.png...
[19:32:18]: Uploading screenshot ./fastlane/metadata/android/de-DE/images/sevenInchScreenshots/1.png...
[19:32:25]: Uploading screenshot ./fastlane/metadata/android/de-DE/images/tenInchScreenshots/1.png...
```

**Comment by dpettit** [comment]
The path to icon. png is [app/fastlane/metadata/android/en-US/icon.png].  Do I need to move it to a different location?

Here is the output, as requested:

mymac:MyDaddy-1.30-ANDROID tsdev$ ls -lR fastlane/
total 40
-rw-r--r--  1 tsdev  staff   266 Mar  6 10:51 Appfile
-rw-r--r--@ 1 tsdev  staff  2081 Mar  6 10:51 Fastfile
-rw-r--r--  1 tsdev  staff  1482 Mar  6 10:58 README.md
-rw-r--r--  1 tsdev  staff   680 Mar  6 10:51 Screengrabfile
drwxr-xr-x  2 tsdev  staff    68 Mar  6 10:51 actions
drwxr-xr-x  5 tsdev  staff   170 Mar  6 13:00 metadata
-rw-r--r--  1 tsdev  staff   519 Mar  6 10:58 report.xml

fastlane//actions:

fastlane//metadata:
total 0
drwxr-xr-x  4 tsdev  staff  136 Mar  6 13:06 android
drwxr-xr-x  4 tsdev  staff  136 Mar  6 11:06 backup

fastlane//metadata/android:
total 0
drwxr-xr-x  10 tsdev  staff  340 Mar  6 13:06 en-US

fastlane//metadata/android/en-US:
total 1008
-rw-r--r--  1 tsdev  staff    1827 Mar  6 13:00 full_description.txt
-rw-r--r--@ 1 tsdev  staff  472053 Mar  6 13:00 icon.png
drwxr-xr-x  8 tsdev  staff     272 Mar  6 13:06 images
-rw-r--r--  1 tsdev  staff   26995 Mar  6 13:00 screenshots.html
-rw-r--r--  1 tsdev  staff      77 Mar  6 13:00 short_description.txt
-rw-r--r--  1 tsdev  staff       8 Mar  6 13:00 title.txt
-rw-r--r--  1 tsdev  staff       0 Mar  6 13:00 video.txt

fastlane//metadata/android/en-US/images:
total 0
drwxr-xr-x  7 tsdev  staff  238 Mar  6 13:03 phoneScreenshots
drwxr-xr-x  7 tsdev  staff  238 Mar  6 13:03 sevenInchScreenshots
drwxr-xr-x  7 tsdev  staff  238 Mar  6 13:03 tenInchScreenshots
drwxr-xr-x  2 tsdev  staff   68 Mar  6 13:00 tvScreenshots
drwxr-xr-x  2 tsdev  staff   68 Mar  6 13:00 wearScreenshots

fastlane//metadata/android/en-US/images/phoneScreenshots:
total 9408
-rw-r--r--@ 1 tsdev  staff   980753 Mar  6 13:03 1.png
-rw-r--r--@ 1 tsdev  staff  1053205 Mar  6 13:03 3.png
-rw-r--r--@ 1 tsdev  staff   844312 Mar  6 13:03 4.png
-rw-r--r--@ 1 tsdev  staff   872351 Mar  6 13:03 7.png
-rw-r--r--@ 1 tsdev  staff  1054522 Mar  6 13:03 9.png

fastlane//metadata/android/en-US/images/sevenInchScreenshots:
total 19120
-rw-r--r--@ 1 tsdev  staff  2104994 Mar  6 13:03 1.png
-rw-r--r--@ 1 tsdev  staff  1785853 Mar  6 13:03 3.png
-rw-r--r--@ 1 tsdev  staff  1774862 Mar  6 13:03 4.png
-rw-r--r--@ 1 tsdev  staff  1842503 Mar  6 13:03 7.png
-rw-r--r--@ 1 tsdev  staff  2274891 Mar  6 13:03 9.png

fastlane//metadata/android/en-US/images/tenInchScreenshots:
total 31328
-rw-r--r--@ 1 tsdev  staff  3293861 Mar  6 13:03 1.png
-rw-r--r--@ 1 tsdev  staff  3575055 Mar  6 13:03 3.png
-rw-r--r--@ 1 tsdev  staff  2744322 Mar  6 13:03 4.png
-rw-r--r--@ 1 tsdev  staff  2854136 Mar  6 13:03 7.png
-rw-r--r--@ 1 tsdev  staff  3561245 Mar  6 13:03 9.png

fastlane//metadata/android/en-US/images/tvScreenshots:

fastlane//metadata/android/en-US/images/wearScreenshots:

fastlane//metadata/backup:
total 0
drwxr-xr-x  6 tsdev  staff  204 Mar  6 13:00 en-US

fastlane//metadata/backup/en-US:
total 1000
drwxr-xr-x  6 tsdev  staff     204 Mar  6 13:00 backup
-rw-r--r--  1 tsdev  staff   33307 Mar  6 13:00 bkpscreenshots.html
-rw-r--r--@ 1 tsdev  staff  472053 Mar  6 13:00 icon.png

fastlane//metadata/backup/en-US/backup:
total 0
drwxr-xr-x  15 tsdev  staff  510 Mar  6 13:00 phoneScreenshots
drwxr-xr-x  15 tsdev  staff  510 Mar  6 13:00 sevenInchScreenshots
drwxr-xr-x  15 tsdev  staff  510 Mar  6 13:00 tenInchScreenshots

fastlane//metadata/backup/en-US/backup/phoneScreenshots:
total 24408
-rw-r--r--@ 1 tsdev  staff   980753 Mar  6 13:00 1.png
-rw-r--r--@ 1 tsdev  staff  1062085 Mar  6 13:00 10.png
-rw-r--r--@ 1 tsdev  staff   733416 Mar  6 13:00 11.png
-rw-r--r--@ 1 tsdev  staff  1091617 Mar  6 13:00 12.png
-rw-r--r--@ 1 tsdev  staff   781430 Mar  6 13:00 13.png
-rw-r--r--@ 1 tsdev  staff  1063834 Mar  6 13:00 2.png
-rw-r--r--@ 1 tsdev  staff  1053205 Mar  6 13:00 3.png
-rw-r--r--@ 1 tsdev  staff   844312 Mar  6 13:00 4.png
-rw-r--r--@ 1 tsdev  staff   987603 Mar  6 13:00 5.png
-rw-r--r--@ 1 tsdev  staff   992793 Mar  6 13:00 6.png
-rw-r--r--@ 1 tsdev  staff   872351 Mar  6 13:00 7.png
-rw-r--r--@ 1 tsdev  staff   946350 Mar  6 13:00 8.png
-rw-r--r--@ 1 tsdev  staff  1054522 Mar  6 13:00 9.png

fastlane//metadata/backup/en-US/backup/sevenInchScreenshots:
total 49840
-rw-r--r--@ 1 tsdev  staff  2104994 Mar  6 13:00 1.png
-rw-r--r--@ 1 tsdev  staff  1837221 Mar  6 13:00 10.png
-rw-r--r--@ 1 tsdev  staff  1505916 Mar  6 13:00 11.png
-rw-r--r--@ 1 tsdev  staff  2592519 Mar  6 13:00 12.png
-rw-r--r--@ 1 tsdev  staff  1248397 Mar  6 13:00 13.png
-rw-r--r--@ 1 tsdev  staff  2291125 Mar  6 13:00 2.png
-rw-r--r--@ 1 tsdev  staff  1785853 Mar  6 13:00 3.png
-rw-r--r--@ 1 tsdev  staff  1774862 Mar  6 13:00 4.png
-rw-r--r--@ 1 tsdev  staff  2100097 Mar  6 13:00 5.png
-rw-r--r--@ 1 tsdev  staff  2132203 Mar  6 13:00 6.png
-rw-r--r--@ 1 tsdev  staff  1842503 Mar  6 13:00 7.png
-rw-r--r--@ 1 tsdev  staff  2008812 Mar  6 13:00 8.png
-rw-r--r--@ 1 tsdev  staff  2274891 Mar  6 13:00 9.png

fastlane//metadata/backup/en-US/backup/tenInchScreenshots:
total 82328
-rw-r--r--@ 1 tsdev  staff  3293861 Mar  6 13:00 1.png
-rw-r--r--@ 1 tsdev  staff  3582336 Mar  6 13:00 10.png
-rw-r--r--@ 1 tsdev  staff  2317050 Mar  6 13:00 11.png
-rw-r--r--@ 1 tsdev  staff  4359261 Mar  6 13:00 12.png
-rw-r--r--@ 1 tsdev  staff  2493157 Mar  6 13:00 13.png
-rw-r--r--@ 1 tsdev  staff  3598207 Mar  6 13:00 2.png
-rw-r--r--@ 1 tsdev  staff  3575055 Mar  6 13:00 3.png
-rw-r--r--@ 1 tsdev  staff  2744322 Mar  6 13:00 4.png
-rw-r--r--@ 1 tsdev  staff  3279582 Mar  6 13:00 5.png
-rw-r--r--@ 1 tsdev  staff  3331384 Mar  6 13:00 6.png
-rw-r--r--@ 1 tsdev  staff  2854136 Mar  6 13:00 7.png
-rw-r--r--@ 1 tsdev  staff  3135393 Mar  6 13:00 8.png
-rw-r--r--@ 1 tsdev  staff  3561245 Mar  6 13:00 9.png
mymac:MyDaddy-1.30-ANDROID tsdev$
