### ISSUE TITLE
Fully Support Semver Versioning (for prerelease)

### ISSUE THREAD

**Issue by kcharwood** [fastlane/fastlane#846]
Both cocoapods and carthage allow alpha and beta versioning, but the fastlane tools currently won't allow bumping versions that conform to that.

For example, `3.0.0-beta.1` is not a supported version in fastlane, but is supported with cocoapods and carthage.

I think this would be a two step process:

1) Replace the regex in the multiple actions that pull out an existing version number. There is an example of semver regex [here](https://github.com/mojombo/semver/issues/266#issuecomment-135765386).
2) Update the actions that take in a bump type parameter.

Currently, the bump types are `major`, `minor`, and `patch`. The tricky part will be a sensible description for the prerelease bump type. I don't have a good idea yet, but wanted to open this issue in hopes someone else did.

**Comment by ohwutup** [comment]
This is a great point @kcharwood! We will mark this as a feature request and hopefully get to it for a release in the near future. If you would like to submit a PR to make this change that would be amazing. Let us know and we would be happy to help! I am going to close this issue for now, and feel free to reopen it if you want to discuss implementation or we will reopen when we get to it. Thanks!! :ocean: :octopus:
