### ISSUE TITLE
Need sigh to add CarPlay entitlement to provisioning profile

### ISSUE THREAD

**Issue by codyrotwein** [fastlane/fastlane#8463]
My apps support CarPlay and one of the requirements for this is to generate the provisioning profile with this entitlement (com.apple.developer.playable-content). Is there any way that you can force sigh to include this entitlement? I ran sigh on one of my apps that had an expired provisioning profile, but sigh didn't include the entitlement when it generated a new one.

Thanks for any help.

**Comment by tsafrir** [comment]
@codyrotwein have you found a solution for this? I need that too.

**Comment by hjanuschka** [comment]
i am not 100% sure but i think since xcode 8.2 - you should enable on the app itself (not provisiong profile) - and specify the features in your projects entitlement like:


```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.playable-content</key>
	<true/>
</dict>
</plist>
```

let me know if this helps.

**Comment by codyrotwein** [comment]
No I still haven't found a solution for this. I'm manually maintaining my provisioning profiles for now unfortunately. I'm almost 100% sure you still need the provisioning profile to have the playable-content/carplay entitlement, in addition to it being defined in Entitlements.plist.

**Comment by Fluzzarn** [comment]
When creating the Provisioning Profile through the Developer Center, it seems a "template" variable is passed in when a special entitlement is provided. It seems that sigh doesn't pass this variable when creating provisioning profiles. This is the reason why no provisioning profiles created with fastlane have custom entitlements enabled.
