### ISSUE TITLE
Testflight fail with [!] "\xDF" from ASCII-8BIT to UTF-8

### ISSUE THREAD

**Issue by AymenFarrah** [fastlane/fastlane#8464]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi i have a problem with TestFlight action who failed with **"\xDF" from ASCII-8BIT to UTF-8"**

Its maybe linked to Circle issue but i can't find a solution to these problem !

**My app.ipa is valid and the Info.plist is not corrupted**

here is my logs when i run the Testflight action command:
`
testflight(
        skip_submission: true, # to only upload the build
        skip_waiting_for_build_processing: true,
        app_identifier:"xxxxxxxxx",
        apple_id:"xxxxxxx",
        ipa:ipa_path
    )
` 

and my locale was :
`
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL=
`

and logs :

```
[17:31:48]: -------------------------------------------------
[17:31:48]: --- Step: Verifying required fastlane version ---
[17:31:48]: -------------------------------------------------
[17:31:48]: Your fastlane version 2.19.3 matches the minimum requirement of 2.6  ✅
[17:31:48]: ------------------------------
[17:31:48]: --- Step: default_platform ---
[17:31:48]: ------------------------------
[17:31:48]: Driving the lane 'ios uploadTestFlight' 🚀
[17:31:48]: ------------------------
[17:31:48]: --- Step: testflight ---
[17:31:48]: ------------------------
[17:31:48]: Login to iTunes Connect (xxx@xxx.xx)
[17:31:51]: Login successful
[17:31:51]: Ready to upload new build to TestFlight (App: xxxxxxxx)...
[17:31:51]: An error occured while executing the `error` block:
[17:31:51]: no implicit conversion of nil into String
+------------------+----------------------+
|              Lane Context               |
+------------------+----------------------+
| DEFAULT_PLATFORM | ios                  |
| PLATFORM_NAME    | ios                  |
| LANE_NAME        | ios uploadTestFlight |
+------------------+----------------------+
[17:31:51]: "\xDF" from ASCII-8BIT to UTF-8

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | testflight                          | 3           |
+------+-------------------------------------+-------------+

[17:31:51]: fastlane finished with errors
```

and error details :

`
/usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:40:in `write': [!] "\xDF" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:40:in `block (2 levels) in fetch_info_plist_file'
	from /usr/local/Cellar/ruby/2.2.4/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:37:in `block in fetch_info_plist_file'
	from /usr/local/lib/ruby/gems/2.2.0/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:31:in `fetch_info_plist_file'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:22:in `fetch_app_platform'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/pilot/lib/pilot/manager.rb:62:in `fetch_app_platform'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/pilot/lib/pilot/build_manager.rb:12:in `upload'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/pilot.rb:15:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/testflight.rb:5:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:243:in `block (2 levels) in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:279:in `uploadIPAToTestFlight'
	from Fastfile:147:in `block (2 levels) in parsing_binding'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /usr/local/lib/ruby/gems/2.2.0/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
`
### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.3        |
</details>

*generated on:* **2017-03-07**
</details>

**Comment by oussamtlili** [comment]
I have the same issue :(

**Comment by JadQuincyJohn** [comment]
Same here!

**Comment by mfurtak** [comment]
Hi all 👋 

Since #8455 is already merged, it should be part of a recent nightly build. If people are interested in trying it, that would really help us understand if it has been fixed.

Please give it a shot using `gem update fastlane --pre` or by adding `gem 'fastlane', '>= 2.20.0.beta.20170308010036'` to your Gemfile 👍

**Comment by KrauseFx** [comment]
Could you try with the most recent fastlane? We re-wrote how _pilot_ works 👍

**Comment by tejas-ardeshna** [comment]
@KrauseFx  on fastlane_version "2.32.1", still facing same issue.

My app contain following things
1) companion ios app
2) watch app
3) watch app extension
4)  ios app Siri extension 
5) watch app Siri extension

**Comment by tejas-ardeshna** [comment]
Still facing the same issue on latest built.

The archive is generating successfully but unable to generate .ipa from it.

**Comment by mpirri** [comment]
@tejas-ardeshna Interesting that you are still seeing this.  Can you attach the output of `fastlane env` to this issue so that we might be able to look into this further?

Thanks!  🚀

**Comment by tejas-ardeshna** [comment]
@mpirri Thanks for the reply. Where can I find that one?

**Comment by tejas-ardeshna** [comment]
Running script 'Run Script'
[13:47:41]: ▸ Touching xxxx.app
[13:47:48]: ▸ Signing /Users/Tejas.Ardeshna/Library/Developer/Xcode/DerivedData/xxxx-fwkjvphhnrknulfbvnvkzfmbwldj/Build/Intermediates/ArchiveIntermediates/xxxxWatch/InstallationBuildProductsLocation/Applications/xxxx.app
[13:47:52]: ▸ Touching xxxx.app.dSYM
[13:47:55]: ▸ Archive Succeeded
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
| BUILD_NUMBER     | 54       |
+------------------+----------+
[13:47:57]: no implicit conversion of nil into String

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_build_number              | 1           |
| 💥    | gym                                 | 495         |
+------+-------------------------------------+-------------+

[13:47:57]: fastlane finished with errors

**Comment by mpirri** [comment]
@tejas-ardeshna Just run the command `fastlane env` within your project directory and attach the output to this GItHub issue.

**Comment by tejas-ardeshna** [comment]
Here you go.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_version "2.32.1"

default_platform :ios


platform :ios do
   	lane :beta do
	    increment_build_number
    	#cert(output_path: "./fastlane/certificates")
    	#sigh(output_path: "./fastlane/profiles")
      gym(                                                       # GYM is used to build app
        scheme: "iTRAINWatch",                                  # Use your app scheme
        silent: true,
        include_bitcode: true,                                  # Include bit code in bit code
        output_directory: "./fastlane/build"                    # Destination directory. Defaults to current directory.
      )
   	 	deliver(                                                  # DELIVER is used to upload app on itunes connect
          skip_metadata: true,                                # it will skip all meta data to upload on itunes
          force: true) 
      crashlytics(api_token: '96c68e9c0138cb4916e862697ecd5746657596e6',
             build_secret: '26c18e9bb11b79d4fbf2b036d87c05bdbfef408cb7e58a4f496f2fa1451a1d1f',
                   emails: 'tejas.a@simform.in',
                   groups: nil,
                    notes: 'Distributed with fastlane',    # Check out the changelog_from_git_commits action
            notifications: true)                           # Should this distribution notify your testers via email?
   	end
	
	lane :create_pem do
	current = Dir.pwd
	  pem(
	    force: true,
	    generate_p12: true,
      new_profile: proc do |profile_path| 
	    Dir.chdir(current) do
	    end
	    end
	  )
	end

	lane :liveApp do
  		produce(
    		username: 'app@simform.in',
    		app_identifier: 'com.simform.PharmacyApp',
    		app_name: 'Pharmacy App Beta',
    		language: 'English',
   			app_version: '1.0',
   		 	sku: '123',
    		team_name: 'Mike Chang' # only necessary when in multiple teams
  		)
  	deliver
	end
  lane :dysms do
    download_dysms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end

	lane :live do
    	cert(output_path: "./fastlane/certificates")
    	sigh(output_path: "./fastlane/profiles")
   	 	gym(scheme: "iCoachU" , output_directory: "./fastlane/build") 
   	 	deliver(
     		 skip_screenshots: true,
     		 skip_metadata: false,
     		 submit_for_review: true)
   	 	#deliver(force: true, submit_for_review : true, automatic_release : true)
   	end

end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.yourcardioguru.iwatchdemo" # The bundle identifier of your app
apple_id "fitness@thecardioguru.com" # Your Apple email address

team_id "J9S3EC3CQP"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.32.1  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.5       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.53.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.6        |
| rubyzip                   | 1.2.0        |
</details>


*generated on:* **2017-07-27**
</details>

**Comment by mpirri** [comment]
@tejas-ardeshna Can you upgrade to the latest _fastlane_ and try again? (you are running 2.32.1, which is a little behind currently)

Thanks!

**Comment by tejas-ardeshna** [comment]
@mpirri Nil string issue solved but. Still no ipa.

Touching iTRAIN.app.dSYM
INFO [2017-07-28 17:03:58.18]: ▸ Archive Succeeded
DEBUG [2017-07-28 17:03:59.20]: Stored the archive in: /Users/Tejas.Ardeshna/Library/Developer/Xcode/Archives/2017-07-28/iTRAINWatch 2017-07-28 16.53.13.xcarchive
WARN [2017-07-28 17:03:59.20]: No output path received from gym
INFO [2017-07-28 17:03:59.21]: ---------------------
INFO [2017-07-28 17:03:59.21]: --- Step: deliver ---
INFO [2017-07-28 17:03:59.21]: ---------------------
INFO [2017-07-28 17:04:00.13]: Login to iTunes Connect (fitness@thecardioguru.com)
Looking for iTunes Connect Team with ID 117278598
INFO [2017-07-28 17:04:04.94]: Login successful

+-----------------------------+-------------------------------+
|                   deliver 2.49.0 Summary                    |
+-----------------------------+-------------------------------+
| skip_metadata               | true                          |
| force                       | true                          |
| run_precheck_before_submit  | false                         |
| screenshots_path            | ./fastlane/screenshots        |
| metadata_path               | ./fastlane/metadata           |
| username                    | fitness@thecardioguru.com     |
| app_identifier              | com.yourcardioguru.iwatchdemo |
| edit_live                   | false                         |
| platform                    | ios                           |
| skip_binary_upload          | false                         |
| skip_screenshots            | false                         |
| skip_app_version_update     | false                         |
| submit_for_review           | false                         |
| automatic_release           | false                         |
| dev_portal_team_id          | J9S3EC3CQP                    |
| overwrite_screenshots       | false                         |
| precheck_default_rule_level | warn                          |
+-----------------------------+-------------------------------+

INFO [2017-07-28 17:04:08.08]: Starting with the upload of screenshots...
INFO [2017-07-28 17:04:08.08]: Successfully uploaded screenshots to iTunes Connect
INFO [2017-07-28 17:04:09.48]: Finished the upload to iTunes Connect

**Comment by ohayon** [comment]
Hey @tejas-ardeshna is there in fact an archive at the `/Users/Tejas.Ardeshna/Library/Developer/Xcode/Archives/2017-07-28/iTRAINWatch 2017-07-28 16.53.13.xcarchive` path that was in that output you shared?

**Comment by tejas-ardeshna** [comment]
@ohayon Yes archive is successful but I need to generate ipa file for deliver step and upload it to itunes connect.

**Comment by ohayon** [comment]
@tejas-ardeshna does the `./fastlane/build` directory exist on your machine already?

**Comment by tejas-ardeshna** [comment]
@ohayon Yes, that is available in the 
![screen shot 2017-08-02 at 10 23 31 am](https://user-images.githubusercontent.com/12891361/28858219-b918fe8a-776c-11e7-8115-9a2e6ad0e908.png)
directory.

**Comment by tejas-ardeshna** [comment]
@mpirri Any update on this?

**Comment by tejas-ardeshna** [comment]
Any update on this guys?

**Comment by ohayon** [comment]
Hey @tejas-ardeshna - I just noticed in the output from your `fastlane env` command that the locale on your system is not set do you have `LANG=en_US.UTF-8` in your env? If not, can you try setting that environment variable and run again? Thanks ! 🚀

**Comment by taquitos** [comment]
Also, another thought: `\xDF` represents `ß`, so maybe you have a file somewhere that is not UTF8 encoded, and it contains a `ß`. Usually when I run into ASCII/UTF8 issues, it's because I have a file somewhere that is non-UTF-8 encoded.
