### ISSUE TITLE
Spaceship cookie path selection fails when no HOME environment variable is set

### ISSUE THREAD

**Issue by lafiosca** [fastlane/fastlane#8465]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running a spaceship application in an environment that has no `HOME` variable set, such as a default AWS Lambda, the cookie path selection logic [located here](https://github.com/fastlane/fastlane/blob/60bac7e4a2a6c1e19d1cd20eb83201e7d0cb9e48/spaceship/lib/spaceship/client.rb#L198) fails to expand the `~`, crashing the program before it can check the other paths. I believe it would be prudent to check for the existence of `HOME` before attempting to expand the `~`.

As a workaround, you can explicitly set `SPACESHIP_COOKIE_PATH` or `HOME` in the environment to `/tmp` before running your application.

I mentioned this in the comments on #6759 and was asked to open a new issue. I apologize for the delay and any lacking details. I think the cause of the problem is pretty simple, and I would offer a patch myself but for lack of ruby knowledge and time on my part.

##### Error output

```
{
  "errorMessage": "Command failed: /bin/sh -c ./ruby_app/itunes_app_status\n/var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:187:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:187:in `fastlane_user_dir'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:198:in `persistent_cookie_path'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/two_step_client.rb:81:in `load_session_from_file'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:287:in `send_shared_login_request'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/tunes/tunes_client.rb:161:in `send_login_request'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:500:in `do_login'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:269:in `login'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:109:in `login'\n\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/tunes/spaceship.rb:22:in `login'\n\tfrom /var/task/ruby_app/lib/app/itunes_app_status.rb:13:in `<main>'\n `./ruby_app/itunes_app_status` (exited with error code 1)",
  "errorType": "Error",
  "stackTrace": [
    "/var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:187:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:187:in `fastlane_user_dir'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:198:in `persistent_cookie_path'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/two_step_client.rb:81:in `load_session_from_file'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:287:in `send_shared_login_request'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/tunes/tunes_client.rb:161:in `send_login_request'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:500:in `do_login'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:269:in `login'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/client.rb:109:in `login'",
    "\tfrom /var/task/ruby_app/lib/vendor/ruby/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/tunes/spaceship.rb:22:in `login'",
    "\tfrom /var/task/ruby_app/lib/app/itunes_app_status.rb:13:in `<main>'",
    " `./ruby_app/itunes_app_status` (exited with error code 1)",
    "ChildProcess.exithandler (child_process.js:213:12)",
    "emitTwo (events.js:87:13)",
    "ChildProcess.emit (events.js:172:7)",
    "maybeClose (internal/child_process.js:821:16)",
    "Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)"
  ]
}
```

**Comment by lafiosca** [comment]
Unfortunately, it is non-trivial for me to run an arbitrary command (such as `fastlane env`) in the Lambda function, as it requires committing and pushing through our build pipeline to package Traveling Ruby into a Lambda package. I believe the specific issue and root cause are obvious enough to not require it in this case.

**Comment by hjanuschka** [comment]
out of curiosity  i really would like to see a sample code/repo of the lambda code 👍 
i don't think that getting rid of `~`  or `File.expand_path`  will happen, as it would require alot amount of work - with high potential for many regression issues.!

since you already proposed a workaround by setting either `SPACESHIP_COOKIE_PATH`  or `HOME` (and infact supporting lambda as platform, would just cover a rough edge case) i think this issue could be closed, whats your point of view?

**Comment by lafiosca** [comment]
If I get an opportunity, I'll see if I can release a sanitized version of our repo. Right now the project is private and contains proprietary information, plus it relies on some existing infrastructure that I've deployed in our account. I've been wanting to write articles about a lot of this Lambda deployment stuff anyway.

I'm fine with closing the issue if it will be too tricky to address. The workaround is fairly painless as long as you know to expect it. In the particular case of Lambda deployments, we are already setting environment variables to convey credentials, so it is simple to add another. (I don't know any contexts off the top of my head, other than Lambda, in which HOME would not be set, but I'm sure they exist somewhere.)
