### ISSUE TITLE
IPA uploaded to wrong hockey app 

### ISSUE THREAD

**Issue by tapwork** [fastlane/fastlane#847]
I use two hockey apps with different bundle identifiers
live and stage

once I upload with hockey( ) the stage app will be uploaded to the live app in hockey.
Even with specifying the ipa path
Here is how I use the tasks
```
before_all do
    cocoapods
     xctest(
      scheme: 'SomeScheme',
      destination: "platform=iOS Simulator,name=iPhone 6s,OS=9.1",
      clean: true
    )
  end

lane :stage do
    ensure_git_branch(
       branch: 'development'
    )
 
    ipa(
      workspace: "SomeApp.xcworkspace",
      scheme: "SomeApp Stage",
      ipa: "someapp-stage.ipa", 
      clean: true
    )
    
    hockey(
      api_token: 'thetoken',
      ipa: 'someapp-stage.ipa'
    )
  end
```

The `someapp-stage.ipa` will be posted to the live app in hockey.
Any idea ?

**Comment by xfreebird** [comment]
The ```hockeyapp`` action is calling the HockeyApp REST API, so the issue could lie there.
If you are using one upload API token, then you should talk to the HockeyApp support. And if you are using one upload token, then I would suggest having one per app.

**Comment by tapwork** [comment]
I fixed it by adding the configuration to the `ipa (...)`
`configuration: "Stage",`

the `ipa` used the wrong configuration from the xctest which ran before

**Comment by xfreebird** [comment]
:+1:

**Comment by KrauseFx** [comment]
You should use `gym` instead of `ipa` :+1:

**Comment by tapwork** [comment]
@KrauseFx I tried, but for some unknown reaosns it didn't work with `gym`...but fastlane is great work
