### ISSUE TITLE
Scan: Test execution failed. Exit status: 65

### ISSUE THREAD

**Issue by brunomiguensolx** [fastlane/fastlane#8472]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Every time execute scan, they run all the unit tests and return a "Exit status: 65", the log bellow is the report generated.

I already have set: ``` ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "0" ``` (saw it in this [link](https://github.com/fastlane-old/fastlane_core/issues/87)) and: ``` ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2" ```

My scan file only have:
```
clean true
device 'iPhone 7 (10.2)'
code_coverage true
output_types 'html'
output_directory './fastlane/builds/scan/'
```

I have done a lot of things and seen a lot of issues here but nothing works. 

```
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/actions/actions_helper.rb:48:in `execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:221:in `block in execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `chdir'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:217:in `execute_action'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:139:in `trigger_action_by_name'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:96:in `block (2 levels) in parsing_binding'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:192:in `try_switch_to_lane'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:147:in `trigger_action_by_name'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:84:in `block (2 levels) in parsing_binding'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane.rb:33:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:105:in `block (2 levels) in run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
/usr/local/bin/fastlane:22:in `load'
/usr/local/bin/fastlane:22:in `<main>'

Test execution failed. Exit status: 65
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-report | 0.1.10  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| bundler                   | 1.14.6       |
| pdfkit                    | 0.8.2        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.7.0.1      |
| websocket-extensions      | 0.1.2        |
| websocket-driver          | 0.6.5        |
| gli                       | 2.15.0       |
| hashie                    | 3.5.5        |
| slack-ruby-client         | 0.7.9        |
| wkhtmltopdf-binary        | 0.12.3.1     |
| fastlane-plugin-report    | 0.1.10       |
</details>

*generated on:* **2017-03-08**

Note: ``` fastlane-plugin-report``` is a plugin created by me and available on RubyGems.
</details>

**Comment by ianterrell** [comment]
We are also seeing this issue intermittently on our CI server (TeamCity).

**Comment by brunomiguensolx** [comment]
@ianterrell Thank you for the feedback, i'll wait until further news, if you need some from me to help solving this issue feel free to contact me.
