### ISSUE TITLE
Suppress UpdateChecker

### ISSUE THREAD

**Issue by giginet** [fastlane/fastlane#8475]
My co-worker claims me output to notify update is so noisy.
So, I'll add the feature to disable `UpdateChecker` when `Fastfile` is loaded.

in your `Fastfile`. declare this line.

```ruby
disable_update_checker
```

**Comment by KrauseFx** [comment]
There is already an environment variable you can use for that 👍 `FASTLANE_HIDE_CHANGELOG`
