### ISSUE TITLE
Gym matching toggle, better solution?

### ISSUE THREAD

**Issue by casz** [fastlane/fastlane#8477]
Is there really no better way then to change the scheme and go away from automatic signing while using match for CI?
This is what I came up with which works but it is kind of ugly.
The documentation lacks anything specific towards multiple targets.

I added a overriding xcconfig for each target and then simply writing PROVISIONING_PROFILE_SPECIFIER to each target. 

```
  desc 'Build it'
  lane :build do |options|
    if is_ci?
      increment_build_number build_number: ENV['BUILD_NUMBER']
      matching(type: "Development")
    end
    gym(
      export_method: 'development'
    )
  end

  desc 'Update codesigning stuff'
  lane :matching do |options|
    type = options[:type] || (options[:type].empty? ? "development" : options[:type])
    identifiers = [
      'com.my.iphoneapp',
      'com.my.iphoneapp.watchkitapp',
      'com.my.iphoneapp.watchkitapp.watchkitextension'
    ]
    xcconfigs = [
      '../iPhoneApp/iphone.xcconfig',
      '../WatchApp/watch.xcconfig',
      '../WatchApp Extension/extension.xcconfig'
    ]
    match(
      type: type.downcase,
      app_identifier: identifiers
    )
    sh "sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/' ../#{ENV['scheme']}.xcodeproj/project.pbxproj"
    line = "PROVISIONING_PROFILE_SPECIFIER ="
    identifiers.each_with_index do |v, i|
      File.open(xcconfigs[i], 'w') {|f| f.write("#{line} match #{type} #{identifiers[i]}") }
    end
  end
```

**Comment by hjanuschka** [comment]
you could use https://github.com/hjanuschka/fastlane-plugin-update_project_codesigning (there is also a PR running to bring that action into core #8417 )


basically you toggle it to auto on dev. machines, and on CI
you toggle it to manual (its almost the same as you did above)


```ruby
#set to manual signing
update_project_codesigning(
    path: "demo-project/demo/demo.xcodeproj",
    use_automatic_signing: false
  )
match
gym(configuration: "Release")
pilot
#set to automatic codesigning
update_project_codesigning(
    path: "demo-project/demo/demo.xcodeproj",
    use_automatic_signing: true
  )

```


and configure your provisiong profile in xcode:
![image](https://cloud.githubusercontent.com/assets/2891702/23763932/f011153c-04fb-11e7-8434-bc8926a69947.png)


let me know if this helps

**Comment by casz** [comment]
Thanks!
That was explained better than doc did 👍 
https://docs.fastlane.tools/codesigning/xcode-project/

**Comment by casz** [comment]
Consider my issue closed once you release #8417 😍

**Comment by pschneider** [comment]
@hjanuschka 
How can I output or see what env name match sets to know what I need to define in Xcode?

**Comment by hjanuschka** [comment]
@pschneider after match has run - you ll see it printed out:
![bildschirmfoto 2017-03-13 um 23 11 18](https://cloud.githubusercontent.com/assets/2891702/23877391/6a2a32e2-0842-11e7-9742-0d2b7767e983.png)


see the `Environment Variable`  column, thos can be used inside xocde with `$()` arround it 👍

**Comment by pschneider** [comment]
@hjanuschka Ha, never really noticed that while running match. Thanks for the fast and great help! 🎉

**Comment by KrauseFx** [comment]
Alright, thanks everybody, let's close this issue, as we'll soon ship the new fastlane release 🚀

**Comment by KrauseFx** [comment]
Thanks again @hjanuschka 👍
