### ISSUE TITLE
How to open the App Groups function

### ISSUE THREAD

**Issue by kuangxiaopao** [fastlane/fastlane#8478]
Fastlane is very good tool.But I create appId without App Groups.Please see below:

![groupprew](https://cloud.githubusercontent.com/assets/10973132/23742370/864e55ba-04e7-11e7-9921-fb20ce2f553f.png)

Please tell me how to add this function.Thanks

**Comment by kuangxiaopao** [comment]
| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.4.0                                       |
| Bundler?            | false                                       |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/rubies/ruby-2.4.0/bin/fastlane       |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version     | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained        | false                                       |
| Is homebrew         | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

**Comment by VolkerSchiewe** [comment]
[https://github.com/fastlane/fastlane/blob/master/produce/README.md](url)

## Enabling / Disabling Application Services

If you want to enable Application Services for an App ID (HomeKit and HealthKit in this example):

    fastlane produce enable_services --homekit --healthkit

If you want to disable Application Services for an App ID (iCloud in this case):

    fastlane produce disable_services --icloud

If you want to create a new App Group:

    fastlane produce group -g group.krausefx -n "Example App Group"

If you want to associate an app with an App Group:

    fastlane produce associate_group -a com.krausefx.app group.krausefx

**Comment by KrauseFx** [comment]
Thanks for the help @VolkerSchiewe, that should help 👍

**Comment by RishabhTayal** [comment]
how can we use `fastlane produce associate_group -a com.krausefx.app group.krausefx` with fastlane lane?

**Comment by KrauseFx** [comment]
No, you'll have to use `sh "fastlane produce associate_group .."` to shell out
