### ISSUE TITLE
Combine formatter and output_style

### ISSUE THREAD

**Issue by djbrooks111** [fastlane/fastlane#8479]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a question about combining both a `--formatter` and `--output_style` for scan. My company is currently running scan via the command line and am using the `'xcpretty-json-formatter'`. I tried adding `--output_style rspec` to the scan command, but this caused the formatter to not be able to parse the output correctly. Ultimately, we want only errors, warnings, and tests to be displayed when running scan and hide all of the compiling output. Do you know of a way to combine these two arguments to get this end result?

Here is what we are currently calling:
```
fastlane scan --configuration "Debug" \
--derived_data_path "${DERIVED_DATA_PATH}" \
--skip_build true \
--code_coverage true \
--scheme "${XCODE_SCHEME}" \
--device "${TESTING_DEVICE}" \
--clean \
--formatter 'xcpretty-json-formatter'
```

Ideally we would like to just add `--output_style rspec` to the end of this command.

**Comment by KrauseFx** [comment]
Hey @djbrooks111, thanks for reporting this 👍 

So if you just specify `output_style` to be `rspec` things work as expected?

**Comment by djbrooks111** [comment]
If you add both `--output_style rspec` and have the `--formatter 'xcpretty-json-formatter'` the rspec will actually cause the formatter to fail as they are conflicting in terms of syntax. The console output is `rspec` style, which is expected, but the formatter, which is supposed to generate a .json file, is unable to do so because it is reading in the wrong format. The formatter is expecting `xcpretty` format to them transform for its own purposes, but it being fed the `rspec` format.

The console output is `rspec` which is expected, but the formatter fails.

**Comment by KrauseFx** [comment]
Mhh, interesting. Is that something you'd be interested in working on a patch? We have some really nice docs on how to submit your first Pull Request to _fastlane_: https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md 👍

**Comment by djbrooks111** [comment]
Sure, I can take a whack at it

**Comment by KrauseFx** [comment]
Cool, thanks @djbrooks111, let me know if you have any questions 👍
