### ISSUE TITLE
Problem when 'fastlane produce' on empty folder

### ISSUE THREAD

**Issue by wolffan** [fastlane/fastlane#848]
I plan to start a project fully on fastlane from scratch.
So:
$ mkdir 'newfolder'
$ fastlane produce

Info: 
is iOS? y
everything commited? y (as it's empty)
deliver? n (not in the appstore as i'm creating it, maybe we could ignore this step)
snapshot? y
After snapshot:
[13:18:40]: Error occurred with the setup program! Reverting changes now!

Number of error cb3563ee778d80d1e45b3513b7a975c7

[sentry_cb3563ee778d80d1e45b3513b7a975c7.pdf](https://github.com/fastlane/fastlane/files/34605/sentry_cb3563ee778d80d1e45b3513b7a975c7.pdf)

**Comment by KrauseFx** [comment]
@wolffan What's `fastlane produce`? Do you mean `fastlane init`? 

The error message is
```
RuntimeError: Could not determine installed iOS SDK version. Try running the _xcodebuild_ command manually to ensure it works.
```
Also make sure to run `xcode-select --install` to make sure it works :+1:

**Comment by ohwutup** [comment]
Going to close this for now as its been quiet on this issue for a while. @wolffan let us know if this is still an issue for you with newer versions of the tools! Thanks! :+1:
