### ISSUE TITLE
How not to skip failing test from report?

### ISSUE THREAD

**Issue by orkenstein** [fastlane/fastlane#8480]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a piece of code:
```
begin
   register_devices(devices_file: "fastlane/devices.txt")
rescue => ex
   UI.message(ex)
end
```
If device limit is exceeded this will fail, but not crash, because of `rescue`. The question is:
How **not to** mark this "test" in `report.xml` as failing?

**Comment by KrauseFx** [comment]
You're doing this correctly, can you share the generated `report.xml` with me, so I can take a look?
