### ISSUE TITLE
Fastlane + CoreData with Travis-CI 

### ISSUE THREAD

**Issue by samuelbeek** [fastlane/fastlane#8486]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We user CoreData in our project, it generates classes automatically. When using Fastlane in our CI environment, it doesn't recognise/generate the CoreData generated classes. I get a lot of errors like these (using `gym` or `scan`) 
`❌  error: no such file or directory: /Users/travis/Library/Developer/Xcode/DerivedData/Rabbit-ccxvsecwxmilehgdphulhyhffxxu/Build/Intermediates/CodeCoverage/Intermediates/Rabbit.build/Debug-iphonesimulator/Rabbit.build/DerivedSources/CoreDataGenerated/Model/Model+CoreDataModel.swift
`

If we run these commands on travis, it does work: 
```yml
xcodebuild clean -project Rabbit.xcodeproj -scheme 'Rabbit' | xcpretty
xcodebuild test -project Rabbit.xcodeproj -scheme 'Rabbit' -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' | xcpretty -s
```
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
 error: no such file or directory:[0m /Users/travis/Library/Developer/Xcode/DerivedData/Rabbit-ccxvsecwxmilehgdphulhyhffxxu/Build/Intermediates/CodeCoverage/Intermediates/Rabbit.build/Debug-iphonesimulator/Rabbit.build/DerivedSources/CoreDataGenerated/Model/AudioContent+CoreDataProperties.swift
error: no such file or directory:[0m /Users/travis/Library/Developer/Xcode/DerivedData/Rabbit-ccxvsecwxmilehgdphulhyhffxxu/Build/Intermediates/CodeCoverage/Intermediates/Rabbit.build/Debug-iphonesimulator/Rabbit.build/DerivedSources/CoreDataGenerated/Model/Bucket+CoreDataProperties.swift

```

I've seen this issue being [discussed before](https://github.com/fastlane/fastlane/issues/6989), but there's no real solution yet 👼. 

### Environment 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.3                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "0121e253-f9e2-40ac-b489-f17f36e24ec6"

default_platform :ios

desc "Download and refresh profiles"
lane :sign do
  match(type: "development")
  match(type: "adhoc")
end


# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
desc "Send beta to iTunes Connect"
lane :beta do
  increment_build_number

  #todo: increment_build_number somewhere else

  # build your iOS app
  gym(
    scheme: "Coyote"
  )

  # upload to Testflight
  # tip: add changelog: changelog to make a changelog.
  testflight()
end

desc "CI Things"
lane :ci do
  scan(scheme: "Coyote")
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-03-09**
</details>

**Comment by mssun** [comment]
Same issue for me. The scan cannot find core data file.

**Comment by samuelbeek** [comment]
@mssun We never recieved an answer by Fastlane. In the end we chose to disable auto generated CoreData classes. It resolved this issue. It's by far not ideal, but it works.
