### ISSUE TITLE
Can match update the github repository from what's on Apple?

### ISSUE THREAD

**Issue by j2kun** [fastlane/fastlane#8487]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Suppose I create a new provisioning profile on the Apple Developer Portal, and revoke the existing profile (for `development`, say). Is there a way to tell match to overwrite what's in the git repository with that updated profile?

Instead, it seems that it will pull from the git remote and fail in the event that it can't find the profile on Apple. Is there a way to update the git repository manually with a profile that is installed locally?

I can also do `match nuke development`, but I'm curious if there is a way to avoid this, at least so I can understand how match works, and what mindset I should have when working with match. Until now, I thought that match would overwrite the git repository if the profiles on apple changed.

**Comment by RishabhTayal** [comment]
@j2kun Yes, you can manually delete the profile from your git repository and then run `match` command. This will regenerate the profile on developer portal if required and update them on your git repository.

**Comment by j2kun** [comment]
@RishabhTayal This sounds like just what I want! I would only now request the match documentation be updated somewhere for future reference :)

**Comment by j2kun** [comment]
@RishabhTayal Just curious, when I do this and run `match development`, and I inspect the resulting git commit, I notice that the encrypted certs and profiles change for even non-development profiles and certs. But it doesn't appear from the match CLI output that it is touching those. What's going on? Is it doing something like re-salting the encryption of all the profiles, regardless of whether they need to be changed?

**Comment by KrauseFx** [comment]
That's due to the nature of OpenSSL, the actual certificate doesn't change, you'll just see it on the git changelog

**Comment by RishabhTayal** [comment]
I will update the docs and create a PR.
