### ISSUE TITLE
Screengrab: clean status bar

### ISSUE THREAD

**Issue by dral3x** [fastlane/fastlane#8488]
It's not an issue, it's a feature request.

Looking around I found this awesome project for configuring Android status bar that will fit perfectly with screenshots generation
https://github.com/PSPDFKit-labs/QuickDemo

I hope you will think about integrating it in screengrab 👍 
Thanks!

**Comment by bonyadmitr** [comment]
@dral3x
I think [SimulatorStatusMagic](https://github.com/shinydevelopment/SimulatorStatusMagic) is enough for 99% of apps.

**Comment by KrauseFx** [comment]
@bonyadmitr that's for iOS apps only, I think @dral3x asks for the Android equivalent of it

**Comment by dral3x** [comment]
Correct, I was looking for a good option for Android, as @KrauseFx said.

Android 6/7 already as some built-in support in the OS for this DEMO mode, so, in theory, we can integrate that directly inside screengrab (at least I hope!).

**Comment by KrauseFx** [comment]
@dral3x We don't currently plan on building something ourselves, however we're more than happy to link to a good solution, similarly to how we do it for iOS apps 👍

**Comment by asfalcone** [comment]
I made a PR to mention QuickDemo in the _screengrab_ readme. https://github.com/fastlane/fastlane/pull/8739

**Comment by FlorianRauscha** [comment]
@dral3x I've made a demo mode plugin (https://github.com/FlorianRauscha/fastlane-plugin-demo_mode). Maybe it will help you.

**Comment by dral3x** [comment]
@FlorianRauscha amazing job! I will give it a try in the upcoming weeks. Thank you!
