### ISSUE TITLE
undefined method `install_gem' for #<Gem::Commands::InstallCommand

### ISSUE THREAD

**Issue by useeless37** [fastlane/fastlane#8489]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
running fastlane appium gets error 

> /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed': [!] undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007f81472a91d8> (NoMethodError) 

### Captured Output

Command Used: `qatestui`
<details><summary>Output/Log</summary>

```

DEBUG [2017-03-10 17:45:18.81]: Checking if there are any plugins that should be loaded...
INFO [2017-03-10 17:45:18.83]: -------------------------------------------------
INFO [2017-03-10 17:45:18.83]: --- Step: Verifying required fastlane version ---
INFO [2017-03-10 17:45:18.83]: -------------------------------------------------
INFO [2017-03-10 17:45:18.83]: Your fastlane version 2.19.3 matches the minimum requirement of 1.109.0  ✅
INFO [2017-03-10 17:45:18.83]: ------------------------------
INFO [2017-03-10 17:45:18.83]: --- Step: default_platform ---
INFO [2017-03-10 17:45:18.83]: ------------------------------
INFO [2017-03-10 17:45:18.83]: Driving the lane 'ios qatestui' 🚀
INFO [2017-03-10 17:45:18.83]: --------------------
INFO [2017-03-10 17:45:18.83]: --- Step: appium ---
INFO [2017-03-10 17:45:18.83]: --------------------
INFO [2017-03-10 17:45:18.92]: gem 'rspec' is already installed
WARN [2017-03-10 17:45:19.06]: Installing Ruby gem 'appium_lib'...
WARN [2017-03-10 17:45:22.38]: Lane Context:
INFO [2017-03-10 17:45:22.38]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios qatestui"}
ERROR [2017-03-10 17:45:22.38]: undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007f81472a91d8>
INFO [2017-03-10 17:45:22.38]: Successfully generated documentation at path '/Users/gonzalez/Documents/Crossover/RideClientiOS/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | appium                              | 3           |
+------+-------------------------------------+-------------+

ERROR [2017-03-10 17:45:22.39]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `install_gem' for Gem::Commands::InstallCommand

URL: https://api.github.com/search/issues?q=undefined%20method%20%60install_gem'%20for%20Gem::Commands::InstallCommand+repo:fastlane/fastlane
➡️  fastlane beta- undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007fcf2b4d7900>
   https://github.com/fastlane/fastlane/issues/8290 [open] 5 💬
   a week ago

➡️  undefined method `install_gem' for #<Gem::Commands::InstallCommand:0x007ffb208656a0>
   https://github.com/fastlane/fastlane/issues/7901 [closed] 6 💬
   3 weeks ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.3                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.10.1 (Apple Git-78)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.2.1                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.109.0"

default_platform :ios

platform :ios do
  desc "run appium test, please install rspec first"
  lane :qatestui do |values|
    app_path = "/Users/gonzalez/Library/Developer/Xcode/DerivedData/Ride-fvccocmzisewwygfxcfgquvzgjyp/Build/Products/Debug-iphonesimulator/RideAustinTest\ Automation.app"
    spec_path = "/Users/gonzalez/Documents/Crossover/RiderE2E/src/test/java/com/rideaustin/qa/tests/signin/SignInTest.java"
    appium(
      app_path: app_path,
      spec_path: spec_path,
      platform: "iOS",
      caps: {
        versionNumber: "10.2",
        deviceName: "iPhone 5S"
      }
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| rdoc                      | 4.0.0        |
| psych                     | 2.0.0        |
</details>

*generated on:* **2017-03-10**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```

WARN [2017-03-10 17:46:03.40]: Generating fastlane environment output, this might take a few seconds...
DEBUG [2017-03-10 17:46:04.05]: Checking if there are any plugins that should be loaded...

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `length' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60length'%20for%20nil+repo:fastlane/fastlane
➡️  `supported_platforms': [!] undefined method `split' for nil:NilClass (NoMethodError)
   https://github.com/fastlane/fastlane/issues/7141 [closed] 43 💬
   3 days ago

➡️  Pilot find returns unexpected results
   https://github.com/fastlane/fastlane/issues/8052 [open] 6 💬
   5 weeks ago

➡️  Undefined method 'length' for nil:NilClass running supply
   https://github.com/fastlane/fastlane/issues/4009 [closed] 1 💬
   28 Sep 2016

and 9 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60length'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.3                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.10.1 (Apple Git-78)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.2.1                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.109.0"

default_platform :ios

platform :ios do
  desc "run appium test, please install rspec first"
  lane :qatestui do |values|
    app_path = "/Users/gonzalez/Library/Developer/Xcode/DerivedData/Ride-fvccocmzisewwygfxcfgquvzgjyp/Build/Products/Debug-iphonesimulator/RideAustinTest\ Automation.app"
    spec_path = "/Users/gonzalez/Documents/Crossover/RiderE2E/src/test/java/com/rideaustin/qa/tests/signin/SignInTest.java"
    appium(
      app_path: app_path,
      spec_path: spec_path,
      platform: "iOS",
      caps: {
        versionNumber: "10.2",
        deviceName: "iPhone 5S"
      }
    )
  end

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2017-03-10**
</details>

**Comment by KrauseFx** [comment]
Can you try the following
```
gem install rubygems-update
update_rubygems
gem update --system
```

**Comment by useeless37** [comment]
Thanks @KrauseFx I had to update ruby to 2.2 and json to at least 1.8
