### ISSUE TITLE
Which build tool is fastlane using and can another one be used?

### ISSUE THREAD

**Issue by wegascee** [fastlane/fastlane#849]
Is xcodebuild the only tool possible here or can another one be used (e.g. mdtool, xbuild)?

**Comment by xfreebird** [comment]
```fastlane``` itself doesn't use any build tools at all. It is the actions that are wrappers over build tools like ```xcodebuild```, ```xctool```, ```gradle``` etc. Currently there are no actions for ```mdtool``` and ```xbuild```.

**Comment by wegascee** [comment]
Thanks for your response. Is it possible to configure `fastlane` to use other build tools or is this technically currently not possible? Is the environment flexible enough to support the needs for the different build tools like the ones mentioned by me?

**Comment by jcampbell05** [comment]
You should be able to create an action that just calls these tools using `fastlane new_action` or if your super desperate you could write shell code into fastlane directly using backticks but I recommend creating an action.

**Comment by KrauseFx** [comment]
You can call any other command using the `sh "command here"` action. For building iOS apps the default is to use [gym](https://github.com/fastlane/gym)

**Comment by wegascee** [comment]
OK, it`s possible via [Action](https://github.com/fastlane/fastlane/blob/master/docs/README.md#extensions) or shell code. For the first solution you have to be familiar with Ruby and for the second one with the shell.

Has [anyone](https://github.com/fastlane/fastlane/issues/314) made a fork and already wrote such an action? How would the action be integrated into [gym](https://github.com/fastlane/gym)?

**Comment by KrauseFx** [comment]
Basically you can just use
```ruby
sh "xcodebuild ..."
```
and add your full build command there. It depends on how you build using Xamarin, but you can just call the plain `xcodebuild` command directly from there.

**Comment by wegascee** [comment]
I'm no expert with the command line tools yet. As far as I know `xcodebuild` wants an Xcode project (file ending with *.app*). I don't have this project type and so I can't use `xcodebuild` for this. My project file ends with *.sln*. E.g. for `mdtool` the command looks like

`/Applications/Xamarin\ Studio.app/Contents/MacOS/mdtool -v build "--configuration:Release|iPhone" SOLUTION_FILE.sln`

Using shell commands seems to be the way to go. Currently I'm to unfamiliar with `fastlane`. Can you simply replace the build command from `gym` through the above one? Or wouldn't you use `gym` here at all and only use the shell command?

PS: BTW incredible support here!

**Comment by KrauseFx** [comment]
@wegascee Yes, you can easily just add `sh "your command here"` to use any command line build tool you'd like :+1:

**Comment by ohwutup** [comment]
Hey @wegascee! I am going to close this for now as its been a while since there was any talk on here. Please reopen it if you are still having any issues! Thanks! :+1:
