### ISSUE TITLE
what is fastlane action appium spec_path

### ISSUE THREAD

**Issue by useeless37** [fastlane/fastlane#8495]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hi I would like to ask regarding how to use [fastlane action appium](https://docs.fastlane.tools/actions/#appium). I'm not sure what exactly to write in spec_path 

> Path to Appium spec directory

Thanks!

**Comment by KrauseFx** [comment]
Sorry I don't understand the question, could you clarify?

**Comment by useeless37** [comment]
Hi thanks for checking,

```
appium(
  app_path:  "appium/apps/TargetApp.app",
  spec_path: "appium/spec",
  platform:  "iOS",
  caps: {
    versionNumber: "9.1",
    deviceName:    "iPhone 6"
  }
)
```

In the code above, what is "appium/spec"
is it the folder that contains files like `TestXXX.class` ?

If you can show an example that would be great, thanks!
