### ISSUE TITLE
Frameit: add new features draw_text_bottom & device_padding

### ISSUE THREAD

**Issue by bonyadmitr** [fastlane/fastlane#8497]
I have have some ideas for new features that will be great for frameit:

1.
What about to make one more key (like `draw_text_bottom`) to draw text(title and keyword) at the bottom of the screenshot.

Example:
http://a5.mzstatic.com/us/r30/Purple122/v4/3e/41/5a/3e415afb-fbcb-bbd5-0aee-4148a26cc7e1/screen696x696.jpeg

2. 
Another one key will be great is padding from sides or zoom of the device to make more space.

Example:
http://a3.mzstatic.com/us/r30/Purple122/v4/5b/c1/f7/5bc1f7e0-1e53-f3bf-af3a-e63956231c82/screen696x696.jpeg

p.s. I tried snapshot + frameit today. It is awesome! I don't need to have any paint app to make awesome screenshots! Thank you for all fastlane tools!

**Comment by ohayon** [comment]
Hey @bonyadmitr! Thanks for the feature request! I am going to close this now and mark it as a feature request and we will update this issue if/when we get a chance to bite off this work down the road! Glad to hear you are loving our tools! 🚀 🐙
