### ISSUE TITLE
Match seems to have no support for macOS targets

### ISSUE THREAD

**Issue by joedaniels29** [fastlane/fastlane#8498]
I'd like to be able to add my production macOS Signing cert to my match repo. Any guidance on how I can make match do this?

**Comment by joedaniels29** [comment]
Thanks mr bot. 

This doesn't look like it should be too challenging to implement, https://github.com/fastlane/fastlane/blob/master/match/lib/match/runner.rb
Would just need to be made aware that some certs are macOS certs. 
The logic already seems to exist in https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/certificate.rb to validate a macOS cert
any reason this can't be done pretty easily?

**Comment by Dids** [comment]
With match support, I think it'd definitely push more developers towards macOS support, because certificates are still a pain to manage. Really hoping this happens soon.

**Comment by Dids** [comment]
Another reason to have macOS support as soon as possible:
When using Visual Studio for Mac and editing Entitlements.plist, it requires you to add an Apple ID in its settings. When you try to add one, it prompts you to do so through fastlane, then shows you instructions on using fastlane's match, which of course doesn't support macOS, which becomes an issue.

**Comment by Dids** [comment]
Xamarin.Forms now also supports macOS (in Preview), and once that goes stable, macOS development will most likely increase dramatically.

**Comment by KrauseFx** [comment]
Hey everyone, unfortunately we don't support macOS apps for now, see https://github.com/fastlane/fastlane/commit/1b85d6f180722bd96a1d0cc8493c6c1bb36f0ce5

**Comment by JagCesar** [comment]
:(

It's the correct decision though :) Keep up the good work!

PS. For anyone not agreeing, I bet the fastlane team would gladly approve a PR that fixes macOS support :D .DS

**Comment by Dids** [comment]
While a PR would work, it would also have to be maintained in a timely fashion.
I'm wondering if a plugin would be better, although I have no idea if plugins could extend match functionality.

**Comment by KrauseFx** [comment]
It's not really possible to build this as a plugin unfortunately.
