### ISSUE TITLE
macOS 10.12.4 beta install problem.

### ISSUE THREAD

**Issue by weichencoder** [fastlane/fastlane#8501]
I install fastlane with 'sudo gem install fastlane' and it was installed successfully.

But, when I check its version with 'fastlane --version'.

It shows the message below:
```
------------------------------------------------------------------------------------------------------
fastlane installation at path:
/Users/David/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.19.3/bin/fastlane
-----------------------------
/Users/David/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:68:in `ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)
	from /Users/David/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:68:in `take_off'
	from /Users/David/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
	from /Users/David/.rvm/rubies/ruby-2.4.0/bin/fastlane:22:in `load'
	from /Users/David/.rvm/rubies/ruby-2.4.0/bin/fastlane:22:in `<main>'
------------------------------------------------------------------------------------------------------
```

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by weichencoder** [comment]
Oh, Thank you.
the message is:
/Users/David/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:68:in `ensure in take_off': uninitialized constant FastlaneCore::UpdateChecker (NameError)
	from /Users/David/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:68:in `take_off'
	from /Users/David/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
	from /Users/David/.rvm/rubies/ruby-2.4.0/bin/fastlane:22:in `load'
	from /Users/David/.rvm/rubies/ruby-2.4.0/bin/fastlane:22:in `<main>'

**Comment by lchavezpozo** [comment]
Hi, I had the same problem.
Solution:
1- `brew uninstall ruby `
2- go to folder /usr/local/lib/  delete folder ruby 
3- `brew install ruby`
4- `sudo gem install fastlane`

**Comment by ohayon** [comment]
Hi @weichencoder could you please try running `gem update fastlane`? Let us know if that gets you into a working place. It looks like _fastlane_ is installed into your `rvm` gemset rather than your system gemset which is used when you use `sudo gem...` by just doing `gem update fastlane` it should (hopefully) just update the version of _fastlane_ in rvm. Thanks!

**Comment by JalenChen** [comment]
There may be something wrong with `require 'excon'` and "openssl".
