### ISSUE TITLE
Problem：To not be asked about the value, you can specify it using ‘edit_live’ modify live metadata, this option disable ipa upload and screenshot upload: 

### ISSUE THREAD

**Issue by ShenJieSuzhou** [fastlane/fastlane#8502]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Why I use the command 'fastlane deliver'  , the terminal will output the following content 'To not be asked about the value, you can specify it using ‘edit_live’ modify live metadata, this option disable ipa upload and screenshot upload:  ',  and then it will modify my online version content . And my metadata is not uploaded to the new version。I know it should not be wrong, but I do not know how to solve this problem，please help me.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

To not be asked about the value, you can specify it using ‘edit_live’ modify live metadata, this option disable ipa upload and screenshot upload: 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
Yeah, please share the complete output when running _fastlane_ 👍

**Comment by ShenJieSuzhou** [comment]
@KrauseFx output of fastlane：

[11:24:54]: -------------------------------------------------
[11:24:54]: --- Step: Verifying required fastlane version ---
[11:24:54]: -------------------------------------------------
[11:24:54]: Your fastlane version 2.3.0 matches the minimum requirement of 1.111.0  ✅
[11:24:54]: ------------------------------
[11:24:54]: --- Step: default_platform ---
[11:24:54]: ------------------------------
[11:24:54]: Welcome to fastlane! Here's what your app is setup to do:
+--------+---------------------+--------------------------------------------------------------------------------------------------+
|                                                     Available lanes to run                                                      |
+--------+---------------------+--------------------------------------------------------------------------------------------------+
| Number | Lane Name           | Description                                                                                      |
+--------+---------------------+--------------------------------------------------------------------------------------------------+
| 1      | ios provision       | 创建项目的证书与签名                                                                             |
| 2      | ios upload_metadata | 仅上传素材 - 没有ipa包会被上传                                                                   |
|        |                     | You'll get a summary of the collected metadata before it's uploaded                              |
| 3      | ios build           | 编译，打包                                                                                       |
| 4      | ios beta            | 编译，上传 TestFlight版本                                                                        |
|        |                     | Build, sign and upload a new beta build to Apple TestFlight                                      |
|        |                     | This will **not** send an email to all testers, it will only be uploaded to the new TestFlight.  |
| 5      | ios upload_iap      | 上传 App Store 版本                                                                              |
|        |                     | upload a new build to the App Store.                                                             |
|        |                     | This will **not** submit the app for review.                                                     |
| 0      | cancel              | No selection, exit fastlane!                                                                     |
+--------+---------------------+--------------------------------------------------------------------------------------------------+
Which number would you like run?

**Comment by KrauseFx** [comment]
Yes, so you have to select a lane to start _fastlane_  🚀

**Comment by ShenJieSuzhou** [comment]
@KrauseFx 
In fact, I also chose the second option：

 “**| 2 | ios upload_metadata | 仅上传素材 - 没有ipa包会被上传 |
| | | You'll get a summary of the collected metadata before it's uploaded |** ” 

But when the terminal output this sentence:

"**To not be asked about the value, you can specify it using ‘edit_live’ modify live metadata, this option disable ipa upload and screenshot upload:**"

there will be problems，my new metadta is not uploaded to the new version, but the online version's information such as release_notes will be modified.

If i create a version number  in itunesconnnect for the application early , will lead to this problem？

**Comment by ShenJieSuzhou** [comment]
It solved after I update
