### ISSUE TITLE
Get the current group associated with app id

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#8508]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is there a way to get the current group association for an app id using `produce`? I know we can assign a group to app id using `associate_group` option in `produce`.

**Comment by yukiasai** [comment]
There is propably no feature yet, but I guess we can implement to `spaceship`. Let me do it!
