### ISSUE TITLE
Disable nuke or other tools

### ISSUE THREAD

**Issue by wolffan** [fastlane/fastlane#8518]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm organising a huge  team (rather multiple teams) into one account.
We want to use fastlane as facilitator and automation tool for some (almost all) of the development processes.
Question is if there's any way of not allowing certain commands like `fastlane nuke` that are highly destructive.
Since I plan to run multiple teams, the setup scripts (or manual tasks) will be performed by a single entity (as well as updates). The rest of the team will just use what is available (no creation powers).

I don't think fastlane was originally designed for this. But as use case, is real. 
The only think came to mind was the ability to disable certain features (on the fastfile or other config files).

If you have a better alternative I'm all ears :-).
Many thanks

PD: I acknowledge this is not an issue (rather a feature request) and this may already be possible but the knowledge over ruby is very limited on my side.

**Comment by KrauseFx** [comment]
Actually _fastlane_ is designed for this. You of course should use _match_ to manage and store your code signing identities and provisioning profiles. Once you run that for every app and environment you need, you can add the following to the `Fastfile`
```ruby
match(readonly: true)
```

This way, the actual users don't have to have access to the iTunes Connect / Dev Portal credentials at all, and also won't be asked for them, as _match_ will just use the code signing identities it can find in the git repo.

Let me know if that makes sense 👍

**Comment by wolffan** [comment]
Thanks for sharing this @KrauseFx 
I had a problem with `match` though. I had a requirement related to storage of secrets and keys. Basically I can't store them on github, so I'm using a self hosted secure solution.

I'll explore using it as the automation tool for generation/renewal. (but I'll need to plug another storage solution)

I am using `sigh` to download the Provisioning profiles (though at the moment the fastlane user from travis is in fact admin, this solution https://github.com/fastlane/fastlane/issues/8385 probably will allow me to remove the requirement).

Bonus problems for any team managing the certificates and provisioning as they want (like the Xcode 8 automated signing tool).

I can close this. But the structure will probably involve at least 1 person per team being admin and so the danger of having someone `nuke` or other nasty stuff will remain.

**Comment by KrauseFx** [comment]
> Basically I can't store them on github, so I'm using a self hosted secure solution.

We've heard this argument a lot, and I can assure you that storing your files inside git is a lot saver than most alternative approaches, like sending things via email, or storing them on an FTP server.

You can use your own self-hosted git, and use that with _match_ 👍

**Comment by wolffan** [comment]
i know, not my call :(.

BTW I expected your answer to be: "Make a fastlane plugin" ;)
Which I'll have to do for another reason.

Thanks again @KrauseFx I'll try to update with a blog post and solution if they allow me :)
