### ISSUE TITLE
Can fastlane create wildcard App ID?

### ISSUE THREAD

**Issue by hotsjf** [fastlane/fastlane#8524]
Sorry if it's the wrong place to ask, just wondering...

Can fastlane create wildcard App ID, and a provision file with wildcard App ID?

thanks

**Comment by KrauseFx** [comment]
Yes, that should work, you can use the _produce_ action for that 👍

**Comment by mgrebenets** [comment]
@hotsjf do you mean `match` when you ask about provisioning profile?

Then I can confirm that the answer is "Yes".

We are using `Matchfile` like this one to add new devices to wildcard provisioning profile:

```ruby
git_url "ssh://git@redacted/certificates.ios.git"
type "development"
app_identifier "au.com.redacted.*"
username "redacted@redacted.com.au"
force_for_new_devices "true"
```

On first run it created the profile for us.

Then we use similar `Matchfile` to pull the profile:

```ruby
git_url "ssh://git@redacted/certificates.ios.git"
type "development"
app_identifier "au.com.redacted.*"
readonly "true"
```

**Comment by hotsjf** [comment]
@ohayon 
I was trying to do something like this:
`fastlane produce create -u appleid@mail.com -a * -q wildcard -i`

but got this error:
`
+----------------+--------------------+
|     Summary for produce 2.17.1      |
+----------------+--------------------+
| username       | appleid@mail.com |
| app_identifier | Desktop            |
| app_name       | wildcard           |
| skip_itc       | true               |
| sku            | 1490088275         |
| platform       | ios                |
| language       | English            |
| skip_devcenter | false              |
+----------------+--------------------+

[!] Apple provided the following error info:
	An App ID with Identifier 'Desktop' is not available. Please enter a different string.
`

**Comment by hotsjf** [comment]
Lucky me, I can do that with Spaceship now, I remember it didn't work before :)

thanks guys.

**Comment by KrauseFx** [comment]
```
An App ID with Identifier 'Desktop' is not available. Please enter a different string.
```
That just means that the bundle identifier is taken 👍
