### ISSUE TITLE
fastlane not working after updating ruby.

### ISSUE THREAD

**Issue by samratBasra** [fastlane/fastlane#8529]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
**ERROR [2017-03-15 12:38:20.07]: fastlane finished with errors
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'activesupport' to activate (Gem::LoadError)**
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
fastlane installation at path:
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/bin/fastlane
-----------------------------
fastlane 2.19.3

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by samratBasra** [comment]
Here is the output of FASTLANE ENV

Ashus-MacBook:fastlane jenkins$ fastlane env
[14:20:56]: Generating fastlane environment output, this might take a few seconds...

Looking for related GitHub issues on fastlane/fastlane...

➡️  character encoding: US-ASCII and UTF-8
   https://github.com/fastlane/fastlane/issues/8234 [open] 1 💬
   4 weeks ago

➡️  No value found for 'username'hen try to Jenkins Integration with Fastlane. But the lane run successful via SSH.
   https://github.com/fastlane/fastlane/issues/4785 [closed] 2 💬
   19 Nov 2016

➡️  Running fastlane from run script phase - encoding problem
   https://github.com/fastlane/fastlane/issues/1239 [closed] 7 💬
   6 weeks ago

and 1 more at: https://github.com/fastlane/fastlane/search?q=incompatible%20character%20encodings:%20UTF-8%20and%20US-ASCII&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/environment_printer.rb:25:in `get': [!] incompatible character encodings: UTF-8 and US-ASCII (Encoding::CompatibilityError)
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/environment_printer.rb:4:in `output'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:232:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/runner.rb:444:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-4.4.1/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:302:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'
Ashus-MacBook:fastlane jenkins$

**Comment by KrauseFx** [comment]
Can you run `gem update`? Are you using bundler? If not, have you thought about starting to use it?  https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

**Comment by chappejw** [comment]
A lot of dead ends here with no solutions guys. I haven't been able to compile an archive using Fastlane gym since Xcode 8.  

I get as far as code signing, which seems to work, but no archive is created...

Entitlements:

{
    "application-identifier" = "XXXXXXXXXX.com.CompanyName.appName";
    "aps-environment" = development;
    "com.apple.developer.team-identifier" = XXXXXXXXXX;
    "get-task-allow" = 1;
}


    builtin-productPackagingUtility -entitlements -format xml -o /Users/jacobc/.jenkins/workspace/Build_iOS/build/App\ Name.build/app_name.app.xcent

CodeSign /Users/jacobc/Library/Developer/Xcode/DerivedData/PR-bbjxckucqljryhgulcketvgjjkbg/Build/Intermediates/ArchiveIntermediates//App\ Name/InstallationBuildProductsLocation/Applications/country_news.app
    cd /Users/jacobc/.jenkins/workspace/Build_iOS/SE
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0/bin:/Users/jacobc/.rvm/bin:/Users/jacobc/.fastlane/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0@global/bin:/Users/jacobc/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/opt/subversion/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/jacobc/bin:/Users/jacobc/.rvm/bin"
    
Signing Identity:     "iPhone Developer: Developer Name (XFGSDFSEDG)"
Provisioning Profile: "iOS Team Provisioning Profile: com.CompanyName.appName"
                      (6ae1b1dd-9ceb-4d40-99e2-256280768781)

    /usr/bin/codesign --force --sign 26396BE1B89647931F505BBA8FD5C4F597021708 --entitlements /Users/jacobc/.jenkins/workspace/Build_iOS/build/App\ Name.build/country_news.app.xcent --timestamp=none /Users/jacobc/Library/Developer/Xcode/DerivedData/PR-bbjxckucqljryhgulcketvgjjkbg/Build/Intermediates/ArchiveIntermediates/App\ Name/InstallationBuildProductsLocation/Applications/app_name.app

Validate /Users/jacobc/Library/Developer/Xcode/DerivedData/PR-bbjxckucqljryhgulcketvgjjkbg/Build/Intermediates/ArchiveIntermediates/App\ Name/InstallationBuildProductsLocation/Applications/app_name.app
    cd /Users/jacobc/.jenkins/workspace/Build_iOS/SE
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0/bin:/Users/jacobc/.rvm/bin:/Users/jacobc/.fastlane/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0@global/bin:/Users/jacobc/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/opt/subversion/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/jacobc/bin:/Users/jacobc/.rvm/bin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/jacobc/Library/Developer/Xcode/DerivedData/PR-bbjxckucqljryhgulcketvgjjkbg/Build/Intermediates/ArchiveIntermediates/App\ Name/InstallationBuildProductsLocation/Applications/app_name.app -validate-for-store

Touch /Users/jacobc/.jenkins/workspace/Build_iOS/build/app_name.app.dSYM
    cd /Users/jacobc/.jenkins/workspace/Build_iOS/SE
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0/bin:/Users/jacobc/.rvm/bin:/Users/jacobc/.fastlane/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0/bin:/Users/jacobc/.rvm/gems/ruby-2.4.0@global/bin:/Users/jacobc/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/opt/subversion/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/opt/ImageMagick/bin:/Applications/Wireshark.app/Contents/MacOS:/Users/jacobc/bin:/Users/jacobc/.rvm/bin"
    /usr/bin/touch -c /Users/jacobc/.jenkins/workspace/Build_iOS/build/app_name.app.dSYM


... and that is as far as the log goes...  touch symbols and that is it... no other clues, just Xcode exit status 65, compiles, signs, but does not generate an archive...

**Comment by chappejw** [comment]
Here is my output from fastlane env

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

Removed here for privacy
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# encoding: utf-8

#app_identifier "" # The bundle identifier of your app
apple_id "user@company.com" # Your Apple email address

team_id "XXXXXXXXXX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| did_you_mean                               | 1.1.2        |
| slack-notifier                             | 1.5.1        |
| CFPropertyList                             | 2.3.5        |
| claide                                     | 1.0.2        |
| colored2                                   | 3.1.2        |
| nanaimo                                    | 0.2.3        |
| xcodeproj                                  | 1.5.0        |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.2.8        |
| terminal-notifier                          | 1.8.0        |
| unicode-display_width                      | 1.3.0        |
| terminal-table                             | 1.8.0        |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.1        |
| multipart-post                             | 2.0.0        |
| word_wrap                                  | 1.0.0        |
| tty-screen                                 | 0.5.0        |
| babosa                                     | 1.0.2        |
| colored                                    | 1.2          |
| highline                                   | 1.7.8        |
| commander-fastlane                         | 4.4.4        |
| excon                                      | 0.57.0       |
| faraday                                    | 0.12.1       |
| unf_ext                                    | 0.0.7.4      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20170404 |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| fastimage                                  | 2.1.0        |
| gh_inspector                               | 1.0.3        |
| uber                                       | 0.1.0        |
| declarative                                | 0.0.9        |
| declarative-option                         | 0.1.0        |
| representable                              | 3.0.4        |
| retriable                                  | 3.0.2        |
| mime-types-data                            | 3.2016.0521  |
| mime-types                                 | 3.1          |
| little-plugger                             | 1.1.4        |
| multi_json                                 | 1.12.1       |
| logging                                    | 2.2.2        |
| jwt                                        | 1.5.6        |
| memoist                                    | 0.16.0       |
| os                                         | 0.9.6        |
| signet                                     | 0.7.3        |
| googleauth                                 | 0.5.1        |
| httpclient                                 | 2.8.3        |
| google-api-client                          | 0.12.0       |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| security                                   | 0.1.3        |
| xcpretty-travis-formatter                  | 0.0.4        |
| dotenv                                     | 2.2.1        |
| bundler                                    | 1.15.1       |
| faraday_middleware                         | 0.11.0.1     |
| json                                       | 2.1.0        |
| io-console                                 | 0.4.6        |
| rubyzip                                    | 1.2.1        |
| plist                                      | 3.3.0        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
</details>


*generated on:* **2017-06-26**
</details>
