### ISSUE TITLE
Fastlane monochrome mode

### ISSUE THREAD

**Issue by realf** [fastlane/fastlane#853]
Hi. Is there a possibility to configure fastlane's output in monochrome mode (for example in Jenkins)?

**Comment by KrauseFx** [comment]
Hey @realf, sorry for the late reply. Right now that's not possible, but definitely something I'd like to add in the future :+1:

**Comment by KrauseFx** [comment]
@realf you can disable colored output using the `FASTLANE_DISABLE_COLORS` environment variable
