### ISSUE TITLE
brew cask install fastlane missing spaceship dependencies?

### ISSUE THREAD

**Issue by casz** [fastlane/fastlane#8530]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
fastlane spaceship seems to be missing pry 👎 

##### Command output

```
$ fastlane spaceship
Could not find gem 'pry'

If you installed spaceship using `sudo gem install spaceship` run
  sudo gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.19.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-03-15**
</details>

**Comment by KrauseFx** [comment]
```
If you installed spaceship using `sudo gem install spaceship` run
  sudo gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```

It pretty much tells you exactly how to install `pry`, which isn't a dependency of _fastlane_ for multiple reasons. 

Let me know if the instructions help, and if you know how we can make them better to make them easier to understand 👍

**Comment by jjhesk** [comment]
i got the same error @KrauseFx i dont know what to do to make spaceship to work.

**Comment by Xwoder** [comment]
I got the same error too.

I install the `fastlane` using `brew install fastlane`, and the `fastlane spaceship` couldn't work neither after I tried `sudo gem install pry` many times.

For the second suggestion, I don't know where to find the `Gemfile`.

### Issue Description
```shell
$ fastlane spaceship
fastlane could not check for updates error: execution expired
Could not find gem 'pry'

If you installed spaceship using `sudo gem install spaceship` run
  sudo gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1421)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.27.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-04-16**
</details>

**Comment by KrauseFx** [comment]
Thanks for sharing. This should probably be mentioned in the docs. Do you want to submit a PR adding this? 👍

**Comment by casz** [comment]
I would like for it be fixed in the brew cask or give me the said gemfile I can edit so I can add pry to the installation.

**Comment by casz** [comment]
I don't see how mentioning it in the docs fixes anything

**Comment by KrauseFx** [comment]
@casz I'd recommend not installing _fastlane_ spaceship via brew cask, but [use a Gemfile instead](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile) 👍

**Comment by zhengying** [comment]
same error here!
is there any workaround solution?

**Comment by julestburt** [comment]
I have the same issue - I have a gem file and added gem 'pry' and then bundle update...but still same error? Do I need to uninstall fast lane. I possibly installed with brew originally?

**Comment by agordeev** [comment]
I'm having the same issue:

```
$ bundle exec fastlane spaceship
fastlane update available
Please run `brew update && brew cask reinstall fastlane`
Could not find gem 'pry'

If you installed spaceship using `sudo gem install spaceship` run
  sudo gem install pry
to install the missing gem

If you use a Gemfile add this to your Gemfile:
  gem 'pry'
and run `bundle install`
```

And my Gemfile is:
```
source "https://rubygems.org"

gem "fastlane"
gem "pry"
```

I ran `bundle install`

**Comment by danieljgmaclean** [comment]
After trying all of the above, I just did:

`sudo gem install spaceship`
`sudo gem install pry`

Then

`fastlane spaceship`

Worked just fine. Make sure you remove any PATH references to the brew installation of fastlane, otherwise you will still get the "Could not find gem 'pry'" error message.

**Comment by julestburt** [comment]
Yes, ultimately managed to remove fastlane in its various forms and start again w/ a gem file. Thx

**Comment by onderozcan** [comment]
Installing millions of gems for just install 1 environment seems to be non-logical.
after home brew install Fastlane wasn't enough, I tried to install spaceship it adds 53 gems more.
I deleted all the gems files immediately. Trying to saving time with insufficient way.

**Comment by BuXY** [comment]
Hey guys, i just found a solution!

Actually, there are **two** installations of ruby and its gems. One is in `/Library/Ruby/Gems/2.0.0` (at least on my computer), and that is why sudo is required to install in normal conditions.

But my Fastlane has installed itself to `~/.fastlane` and thus created a private gem library. So you must install pry in _this ruby gem library_, like: `gem install pry --install-dir ~/.fastlane/bin/bundle/lib/ruby/gems/2.2.0` (please update this path for yourself as this version will expire over time).

After that, `fastlane spaceship` starts without hassle. :)
