### ISSUE TITLE
No `Podfile' found in the project directory.

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#8532]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Just copied Fastfile from Fabric.io and tried `fastlane beta` and it didn't work.

```
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | cocoapods                           | 0           |
+------+-------------------------------------+-------------+

[14:09:58]: fastlane finished with errors

[!] Exit status of command 'pod install' was 1 instead of 0.
[!] No `Podfile' found in the project directory.
```

Podfile is right there:

```
➜  XXX git:(master) ✗ ls -la | grep file            
-rw-r--r--   1 pronebird  staff   813 Mar 15 14:08 Fastfile
-rw-r--r--   1 pronebird  staff    76 Mar 15 14:01 Gemfile
-rw-r--r--   1 pronebird  staff  4763 Mar 15 14:01 Gemfile.lock
-rw-r--r--@  1 pronebird  staff   455 Mar  9 23:58 Podfile
-rw-r--r--   1 pronebird  staff  1326 Mar  9 23:59 Podfile.lock
```

**Comment by pronebird** [comment]
I just ran `bundle exec pod install` and it works. Is there any way to know the location where it runs `pod install`? Can't be that hard to force it run in current directory?

**Comment by KrauseFx** [comment]
This should work by default, sorry you ran into this issue. Would you mind sharing a screenshot of your project directory, containing both the fastlane folder, Fastfile and the Podfile? I assume you didn't put the `Fastfile` inside a `fastlane` directory, which is required by _fastlane_ 👍  Let me know if that's the case

**Comment by pronebird** [comment]
Hi @KrauseFx,

You are right, I forgot to put Fastfile into `fastlane` folder and when I did everything worked like a charm. 

Could you please update https://fabric.io/features/distribution?utm_campaign=fastlane.tools to reflect that? I skimmed through that page many times but see no mention of subfolder requirement, even downloaded ZIP does not have `fastlane/` folder inside.

Maybe something like this as a hint:

<img width="265" alt="screenshot 2017-03-16 10 26 12" src="https://cloud.githubusercontent.com/assets/704044/23991941/02ad3432-0a33-11e7-9a0f-71be780fe7e2.png">

**Comment by KrauseFx** [comment]
Hey @pronebird, thanks again for the feedback, I've just pushed 2 patches on the fastlane side of things, that should auto-detect this source of error. It actually wasn't supposed to load the Fastfile if it's not inside a `fastlane` directory, and now it's reflected by _fastlane_ again 🚀

https://github.com/fastlane/fastlane/pull/8593 and https://github.com/fastlane/fastlane/pull/8592
