### ISSUE TITLE
supply lacks support for updating Android expansion file information

### ISSUE THREAD

**Issue by skicson** [fastlane/fastlane#8533]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Currently `supply` provides the ability to upload Android obb expansion files, but does not allow subsequent builds to simply reference the existing expansion file.   Uploading a new expansion file means that an existing user would need to redownload the expansion file on each update, whether or not the expansion data had changed.

The Google API that `supply` uses provides an `update_expansion_file` method that would allow `supply` to  address this issue.

**Comment by asfalcone** [comment]
@skicson That's for the report. 👍 We'd be happy to review a PR that handles this use case!
