### ISSUE TITLE
Set default whats new/changelog text for all android flavors using supply

### ISSUE THREAD

**Issue by codyrotwein** [fastlane/fastlane#8534]
I have 300+ apps that all would need the same change log text when updating. Is there some way to create like a Supplyfile that has default changelog text? It looks like you can do something similar in Fastlane for ios, with a Deliverfile (untested) that has:

release_notes({
'default' => "Stability improvements and minor bug fixes"
})

**Comment by asfalcone** [comment]
@codyrotwein This isn't currently possible today. I'm going to close this as a feature request.
