### ISSUE TITLE
Fastlane hangs for 2-3 minutes before doing anything

### ISSUE THREAD

**Issue by alexargo** [fastlane/fastlane#854]
At first I thought there no output until it was done, but turns out fastlane is just hanging for 2-3 minutes whenever I run anything and then the output starts happening. See the output below to see what I mean:
Alexs-Hack-Pro:Euchre Alex$ date && fastlane -v && date
Mon Nov 16 13:50:58 EST 2015
fastlane 1.39.0
Mon Nov 16 13:53:15 EST 2015

**Comment by xfreebird** [comment]
Have you tried running ```sudo gem cleanup``` ?

**Comment by alexargo** [comment]
@xfreebird I have not yet. I'll give that a try later today and see if it helps things. This is a fairly fresh install though I believe. Only a few months old.

**Comment by xfreebird** [comment]
@alexargo I have four build machines running ```fastlane``` since september, and some of them are mac mini from 2009. I get 17s on a 2009 mac mini.

```
date && fastlane -v && date
Tue Nov 17 20:09:07 EET 2015
fastlane 1.39.0
Tue Nov 17 20:09:24 EET 2015
```

**Comment by alexargo** [comment]
@xfreebird You are awesome! I'm not a rubyist so I would never have thought to do it. Is it mentioned somewhere in the docs to run it? Seems like the frequently release pace of fastlane et all necessitates running it. Here's some results from my Late 2014 Mac Mini

Before gem cleanup (7 min 27 sec):

    date && fastlane -v && date
    Tue Nov 17 13:13:49 EST 2015
    fastlane 1.39.0
    Tue Nov 17 13:21:22 EST 2015

After gem cleanup(2 sec):

    Tue Nov 17 13:25:12 EST 2015
    fastlane 1.39.0
    Tue Nov 17 13:25:14 EST 2015

**Comment by KrauseFx** [comment]
@alexargo Actually the update message should tell you to run `sudo gem cleanup` every 5th time there is an update. 

Also it is in the docs: https://github.com/fastlane/fastlane#installation

**Comment by alexargo** [comment]
@KrauseFx Gotcha. Yeah I'm not sure what else there is you can do reasonably to inform us. I normally just update all my gems so the update message normally just gets lost. Is the time before you actually run fastlane something that can be measured? (That way you could notify when running fastlane if it's taking longer than expected)

**Comment by KrauseFx** [comment]
I don't think that's possible.
