### ISSUE TITLE
Brew version out of date & update message not relevant to brew users

### ISSUE THREAD

**Issue by postmechanical** [fastlane/fastlane#8542]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Brew cask install fastlane installs out of date version of fastlane. Fastlane shows an update message that is not relevant to users of the tool who install it via brew.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
brew update  > /dev/null
brew cask install fastlane && fastlane --version
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalon
==> Verifying checksum for Cask fastlane
==> Running installer script /usr/local/Caskroom/fastlane/1.7/install
==> 
==> Installing fastlane to /Users/travis/.fastlane/bin... this might take a few 
==> 
==> 
==> Successfully copied fastlane to /Users/travis/.fastlane/bin
==> 
==> 
==> Updating installed gems
==> Updating fastlane
==> Successfully installed tty-screen-0.5.0
==> Successfully installed fastlane-2.20.0
==> Gems updated: fastlane tty-screen
==> Cleaning up installed gems...
==> Attempting to uninstall fastlane-2.13.0
==> Successfully uninstalled fastlane-2.13.0
==> Clean Up Complete
==> Detected shell config file at path '~/.bash_profile'
==> Please add the following line to your bash profile:
==> 
==> 
==> export PATH="$HOME/.fastlane/bin:$PATH"
==> 
==> After doing so close the terminal session and restart it to start
==> 
🍺  fastlane was successfully installed!
fastlane 1.109.0
```

Running fastlane then results in:

```
#######################################################################
# fastlane 2.20.0 is available. You are on 1.109.0.
# It is recommended to use the latest version.
# Update using 'sudo gem update fastlane'.
#######################################################################
```

**Comment by KrauseFx** [comment]
If you have the latest version, the update message should be updated 👍 Please let me know if that's true. Also, why are you still on `1.x`? 😉

**Comment by postmechanical** [comment]
@KrauseFx Because that's what `brew cask install fastlane` on TravisCI `osx_image: xcode8.2` produces.

**Comment by ohayon** [comment]
@postmechanical would you mind sharing the output of `which fastlane` and `echo $PATH`? Thanks!

**Comment by tutipeti** [comment]
```
$ brew cask info fastlane
fastlane: 1.7
https://fastlane.tools/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/fastlane.rb
==> Name
fastlane
==> Artifacts
```

I find it somewhat weird that the first suggested option for installing fastlane is using Homebrew, when brew will install 1.7 for me ;)

**Comment by KrauseFx** [comment]
@tutipeti actually the brew version is not synced with the fastlane version 👍

**Comment by tutipeti** [comment]
@KrauseFx oh. And that version info there kept me from using fastlane from homebrew so far.

**Comment by jgongo** [comment]
@postmechanical @tutipeti In case this helps, I also got this error and it was due to an old version installed with _gem_ instead of _brew_. The old version was already in the path, and I had no _.bash_profile_ file, so whenever I executed _fastlane_, the old version was being executed instead of the new one installed with _brew_. After deleting the gem and creating a _.bash_profile_ file with the proper path I no longer received this out of date messages.
