### ISSUE TITLE
Allow `increment_version_number` without a patch value

### ISSUE THREAD

**Issue by PezHead** [fastlane/fastlane#855]
We normally don't use a patch number for our project versions, so we usually go 1.1 -> 1.2 -> 1.3 . agvtool allows you to set a new-marketing-version string as such, however using increment_version_number will throw an error as `1.2` does not match the format `A.B.C`. 

What would you think about allowing the usage with versions that (optionally) do not have a patch value?

**Comment by KrauseFx** [comment]
I think this is required by the Apple versioning tool `fastlane` is using under the hood. Also, standard semantic versioning always includes a patch value.

**Comment by PezHead** [comment]
The tool will let you do it, but I agree that it doesn't keep with semantic versioning (I've since got our team on X.Y.Z version numbers :] ). Going to close this, as I think you are correct that the current approach is best.
