### ISSUE TITLE
Error: fastlane init command not found

### ISSUE THREAD

**Issue by nikunjazilen** [fastlane/fastlane#8551]
Hi,

I am following the below link for set up the fastlane in my mac for iOS but not working. I have create new project and go that directory path and tried with "fastlane init command" but its give me the error. I have successfully installed "brew cask install fastlane" command.

[https://docs.fastlane.tools/getting-started/ios/setup/](https://docs.fastlane.tools/getting-started/ios/setup/)

Can you please help me to resolve it?

Thanks,
Nikunj

**Comment by nikunjazilen** [comment]
How can I add `fastlane env` in Xcode 8.2?

**Comment by KrauseFx** [comment]
Did you add _fastlane_ to your path? Can you share the output when running `ENV | grep "PATH"`?
