### ISSUE TITLE
Supply does not promote multiple APKs in track

### ISSUE THREAD

**Issue by tmtrademarked** [fastlane/fastlane#8555]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When using supply to promote APKs from one track to another, it doesn't correctly promote all the APKs. Instead, it only promotes the single APK with the highest version. This is a trivial fix - the uploader for supply just needs to upload all APK versions at once instead of building the edit sequentially. I've uploaded a simple PR for this feature here: https://github.com/fastlane/fastlane/pull/8474

**Comment by mfurtak** [comment]
Fixed with #8474 - thanks for the contribution! 🚀
