### ISSUE TITLE
[feature] post something every minute during crashlytics action in CI environment

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#8556]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

If crashlytics takes too long to upload, Travis CI may cancel the build. Faced that trouble today, crashlytics were uploading the build more than 10 minutes and Travis broke my build because of that.
Is it possible to post waiting output string every 1-2 minutes, just like in pilot action?

### Environment

Generating fastlane environment output, this might take a few seconds...

<details><summary>âœ… fastlane environment âœ…</summary>

### Stack

| Key                         | Value                                                      |

| --------------------------- | ---------------------------------------------------------- |

| OS                          | 10.12.1                                                    |

| Ruby                        | 2.0.0                                                      |

| Bundler?                    | true                                                       |

| Git                         | git version 2.10.2                                         |

| Installation Source         | ~/build/company/iOS/vendor/bundle/ruby/2.0.0/bin/fastlane |

| Host                        | Mac OS X 10.12.1 (16B2555)                                 |

| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.0.0-p648/lib                          |

| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                                |

| Is contained                | false                                                      |

| Is homebrew                 | false                                                      |

| Is installed via Fabric.app | false                                                      |

| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                |

| Xcode Version               | 8.1                                                        |

### System Locale

| Variable | Value       |   |

| -------- | ----------- | - |

| LANG     | en_US.UTF-8 | âœ… |

| LC_ALL   | en_US.UTF-8 | âœ… |

| LANGUAGE |             |   |

### fastlane files:

<REDACTED>

### fastlane gems

| Gem      | Version | Update-Status |

| -------- | ------- | ------------- |

| fastlane | 2.20.0  | âœ… Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |

| ------------------------- | ------------ |

| CFPropertyList            | 2.3.5        |

| i18n                      | 0.8.1        |

| minitest                  | 5.10.1       |

| thread_safe               | 0.3.6        |

| tzinfo                    | 1.2.2        |

| activesupport             | 4.2.8        |

| public_suffix             | 2.0.5        |

| addressable               | 2.5.0        |

| babosa                    | 1.0.2        |

| bundler                   | 1.13.6       |

| claide                    | 1.0.1        |

| fuzzy_match               | 2.0.4        |

| nap                       | 1.1.0        |

| cocoapods-core            | 1.2.0        |

| cocoapods-deintegrate     | 1.0.1        |

| cocoapods-downloader      | 1.1.3        |

| cocoapods-plugins         | 1.0.0        |

| cocoapods-search          | 1.0.0        |

| cocoapods-stats           | 1.0.0        |

| netrc                     | 0.7.8        |

| cocoapods-trunk           | 1.1.2        |

| cocoapods-try             | 1.1.0        |

| colored                   | 1.2          |

| escape                    | 0.0.4        |

| fourflusher               | 2.0.1        |

| gh_inspector              | 1.0.3        |

| molinillo                 | 0.5.7        |

| ruby-macho                | 0.2.6        |

| nanaimo                   | 0.2.3        |

| xcodeproj                 | 1.4.2        |

| cocoapods                 | 1.2.0        |

| highline                  | 1.7.8        |

| commander                 | 4.4.3        |

| unf_ext                   | 0.0.7.2      |

| unf                       | 0.1.4        |

| domain_name               | 0.5.20170223 |

| dotenv                    | 2.2.0        |

| excon                     | 0.55.0       |

| multipart-post            | 2.0.0        |

| faraday                   | 0.11.0       |

| http-cookie               | 1.0.3        |

| faraday-cookie_jar        | 0.0.6        |

| faraday_middleware        | 0.11.0.1     |

| fastimage                 | 2.1.0        |

| jwt                       | 1.5.6        |

| little-plugger            | 1.1.4        |

| multi_json                | 1.12.1       |

| logging                   | 2.2.0        |

| memoist                   | 0.15.0       |

| os                        | 0.9.6        |

| signet                    | 0.7.3        |

| googleauth                | 0.5.1        |

| httpclient                | 2.8.3        |

| hurley                    | 0.2          |

| mime-types-data           | 3.2016.0521  |

| mime-types                | 3.1          |

| uber                      | 0.0.15       |

| representable             | 2.3.0        |

| retriable                 | 2.1.0        |

| google-api-client         | 0.9.28       |

| json                      | 2.0.3        |

| mini_magick               | 4.5.1        |

| multi_xml                 | 0.6.0        |

| plist                     | 3.2.0        |

| rubyzip                   | 1.2.1        |

| security                  | 0.1.3        |

| slack-notifier            | 1.5.1        |

| terminal-notifier         | 1.7.1        |

| unicode-display_width     | 1.1.3        |

| terminal-table            | 1.7.3        |

| tty-screen                | 0.5.0        |

| word_wrap                 | 1.0.0        |

| rouge                     | 1.11.1       |

| xcpretty                  | 0.2.4        |

| xcpretty-travis-formatter | 0.0.4        |

| mustache                  | 0.99.8       |

| open4                     | 1.3.4        |

| redcarpet                 | 3.4.0        |

| sass                      | 3.4.23       |

| sqlite3                   | 1.3.13       |

| liferaft                  | 0.0.6        |

| xcinvoke                  | 0.3.0        |

| jazzy                     | 0.7.4        |

</details>

*generated on:* **2017-03-16**

</details>

**Comment by Sega-Zero** [comment]
for example, this is crashlytics time from my last build:
```shell
[17:50:40]: Uploading the build to Crashlytics Beta. Time for some ☕️.
[17:59:34]: Build successfully uploaded to Crashlytics Beta 🌷
[17:59:34]: Visit https://fabric.io/_/beta to add release notes and notify testers.
```

9 minutes without any activity.

**Comment by KrauseFx** [comment]
Hey @Sega-Zero, thanks for submitting this issue, it sounds like a great idea and something we should add to the crashlytics beta upload binary 👍
