### ISSUE TITLE
Mailgun Action Deprecation message 

### ISSUE THREAD

**Issue by micnguyen** [fastlane/fastlane#856]
Hi,

First time fastlane user, loving it so far. Implementing mailgun functionality, getting: 

```
Using :mailgun_sandbox_postmaster is deprecated, please change to :postmaster

Using :mailgun_apikey is deprecated, please change to :apikey
```

despite 

```
     ENV['postmaster'] = "xxxxx"
     ENV['apikey'] = "xxxx"
```

I've 0 knowledge of Ruby, but I'm assuming the issue is in mailgun.rb on line 83. Should that puts be wrapped in an if, if the deprecated key is present.

EDIT: Sorry, I probably should have just fixed this myself in a pull request? First time GitHub user, sorry! :( https://github.com/fastlane/fastlane/pull/858

**Comment by KrauseFx** [comment]
This is fixed with your pull requests, right?
