### ISSUE TITLE
about mailgun params error

### ISSUE THREAD

**Issue by zhangyinglong** [fastlane/fastlane#8568]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I use mailgun action, my Fastfile content is following: 
```
 after_all do |lane|
    # This block is called, only if the executed lane was successful

    mailgun(postmaster: "https://api:key-xxxx@api.mailgun.net/v3/sandboxxxx.mailgun.org/messages",
            apikey: "key-xxxx",
            from: "zhangyinglong<postmaster@sandboxxxx.mailgun.org>",
            to: "yinglong.zhang@funplus.com",
            app_link: "https://www.google.com",
            subject: "Jenkins Job",
            message: "Successfully deployed new App Update.",
            success: true
    )
  end

  error do |lane, exception|
     puts "Failed Deployed!"
  end
```
But something wrong with the error : 301 Moved Permanently. 
```
[16:38:26]: -------------------------------------------------
[16:38:26]: --- Step: Verifying required fastlane version ---
[16:38:26]: -------------------------------------------------
[16:38:26]: Your fastlane version 2.20.0 matches the minimum requirement of 2.19.3  ✅
[16:38:26]: ------------------------------
[16:38:26]: --- Step: default_platform ---
[16:38:26]: ------------------------------
[16:38:26]: Driving the lane 'ios pgyer' 🚀
[16:38:26]: This lane will be ok
[16:38:26]: ---------------------
[16:38:26]: --- Step: mailgun ---
[16:38:26]: ---------------------
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios pgyer |
+------------------+-----------+
[16:38:28]: 301 Moved Permanently

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | mailgun                             | 1           |
+------+-------------------------------------+-------------+

[16:38:28]: fastlane finished with errors

```
So i go to check the source code，and find this code in mailgun.rb 111 line.
```
def self.mailgunit(options)
        sandbox_domain = options[:postmaster].split("@").last
        params = {
          from: "#{options[:from]}<#{options[:postmaster]}>",
          to: (options[:to]).to_s,
          subject: options[:subject],
          html: mail_template(options)
        }
        unless options[:reply_to].nil?
          params.store(:"h:Reply-To", options[:reply_to])
        end

        unless options[:attachment].nil?
          attachment_filenames = [*options[:attachment]]
          attachments = attachment_filenames.map { |filename| File.new(filename, 'rb') }
          params.store(:attachment, attachments)
        end

        RestClient.post "https://api:#{options[:apikey]}@api.mailgun.net/v3/#{sandbox_domain}/messages", params
        mail_template(options)
end
```
I modify the Fastfile to make sure 
```
sandbox_domain="sandboxxxxx.mailgun.org"
```
Unfortunately, occur error: 400 Bad Request, anybody can help me? Thanks!
```
[16:42:39]: -------------------------------------------------
[16:42:39]: --- Step: Verifying required fastlane version ---
[16:42:39]: -------------------------------------------------
[16:42:39]: Your fastlane version 2.20.0 matches the minimum requirement of 2.19.3  ✅
[16:42:39]: ------------------------------
[16:42:39]: --- Step: default_platform ---
[16:42:39]: ------------------------------
[16:42:39]: Driving the lane 'ios pgyer' 🚀
[16:42:39]: This lane will be ok
[16:42:39]: ---------------------
[16:42:39]: --- Step: mailgun ---
[16:42:39]: ---------------------
+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios pgyer |
+------------------+-----------+
[16:42:41]: 400 Bad Request

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | mailgun                             | 2           |
+------+-------------------------------------+-------------+

[16:42:41]: fastlane finished with errors
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.20.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-03-17**
</details>

**Comment by hjanuschka** [comment]
i am not sure if i can help here, just to let you know i removed sensitive api keys from your issue-body.

**Comment by zhangyinglong** [comment]
@hjanuschka Thank you for reminding me, these keys are test case. No problem

**Comment by zhangyinglong** [comment]
I sure that ```api-key``` and ```postmaster``` all right while using this shell statements, i can recive the email. What can i do next?

```
curl -s --user 'api:key-xxxx' https://api.mailgun.net/v3/sandboxxxx.mailgun.org/messages -F from='Mailgun Sandbox <postmaster@sandboxxxx.mailgun.org>' -F to='yinglong.zhang <yinglong.zhang@funplus.com>' -F subject='Hello yinglong.zhang' -F text='Congratulations yinglong.zhang, you just sent an email with Mailgun!  You are truly awesome!'
```

**Comment by zhangyinglong** [comment]
The Fatlane as follow, still 400 Bad Request
```
mailgun(postmaster: "postmaster@sandboxxxx.mailgun.org",
            apikey: "key-xxx",
            subject: "Jenkins MeMe Job",
            message: "Successfully deployed new App Update.",
            success: true
    )
```

**Comment by zhangyinglong** [comment]
Lucky, I debug mailgun.rb
```
begin
     RestClient.post ...
rescue RestClient::ExceptionWithResponse => e
     puts e.response
end
```
and find out error information:
```
[12:25:01]: ---------------------
[12:25:01]: --- Step: mailgun ---
[12:25:01]: ---------------------

post https://api:key-76e3532bd9e5a2117662f6455af2eae5@api.mailgun.net/v3/sandbox0f23817ed73144e78bf00fbff019fc9c.mailgun.org/messages
{
  "message": "'from' parameter is not a valid address. please check documentation"
}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | mailgun                             | 2           |
+------+-------------------------------------+-------------+
```
At last, modify param ```form``` to follow, everything is ok.
```
from: "zhangyinglong <postmaster@sandboxxxx.mailgun.org>",
```
 @hjanuschka Thank you,please closed this issue.
