### ISSUE TITLE
Can't uninstall fastlane, binaries are still installed

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#8570]
I'm trying to `brew install` fastlane, but first I want to remove the old version (which I didn't install).  I've tried 

 * `gem uninstall faslane`
 * `sudo gem uninstall faslane`
 * I've tried downloading the installer and running `uninstall`
 * I've removed the `rbenv` stuff from my `~/.bash_profile`

But when I run fastlane --version i get _fastlane `1.105.2`.  And `which fastlane` give me _/usr/local/bin/fastlane_

(And running `fastlane env` just gives me an error)

```
echo $PATH
/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin:/Volumes/data-ssd/java-bin/apache-maven-3.2.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

`ls -alrt /usr/local/bin/` reveals:

```
-rwx-w----   1 npomfret  admin     496 28 Jul  2016 pem
-rwx-w----   1 npomfret  admin     520 18 Aug  2016 commander
-rwx-w----   1 npomfret  admin     547 18 Aug  2016 krausefx-ipa
-rwx-w----   1 npomfret  admin     508 30 Aug  2016 supply
-rwx-w----   1 npomfret  admin     524 23 Sep 12:38 screengrab
-rwxr-xr-x   1 root      admin     561  6 Oct 19:46 fastlane-credentials
-rwxr-xr-x   1 root      admin     512  6 Oct 19:46 frameit
-rwxr-xr-x   1 root      admin     500  6 Oct 19:46 cert
-rwxr-xr-x   1 root      admin     500  6 Oct 19:46 sigh
-rwxr-xr-x   1 root      admin     512  6 Oct 19:46 produce
-rwxr-xr-x   1 root      admin     504  6 Oct 19:46 pilot
-rwxr-xr-x   1 root      admin     504  6 Oct 19:46 match
-rwxr-xr-x   1 root      admin     516 12 Oct 22:42 xcpretty
-rwxr-xr-x   1 root      admin     512 12 Oct 22:42 🚀
-rwxr-xr-x   1 root      admin     520 12 Oct 22:42 spaceship
-rwxr-xr-x   1 root      admin     520 12 Oct 22:42 spaceauth
-rwxr-xr-x   1 root      admin     516 12 Oct 22:42 snapshot
-rwxr-xr-x   1 root      admin     500 12 Oct 22:42 scan
-rwxr-xr-x   1 root      admin     516 12 Oct 22:42 fastlane
-rwxr-xr-x   1 root      admin     512 12 Oct 22:42 deliver
-rwxr-xr-x   1 root      admin     497 12 Oct 22:43 💪
-rwxr-xr-x   1 root      admin     496 12 Oct 22:43 gym
```

Where did these come from?  And which uninstaller would get rid of them?  Is it possible which ever uninstaller is responsible, it's failing because some of these executables are owned by root?

**Comment by mpirri** [comment]
Sorry that this is such a pain, @npomfret ! Can you do us a favor - can you run `gem which fastlane` to see where `gem` thinks `fastlane` is installed? I think that will help us figure out what the next step is.

Thanks!

**Comment by npomfret** [comment]
```
gem which fastlane
ERROR:  Can't find ruby library file or shared library fastlane

```

**Comment by ssteinerx** [comment]
Not sure if I found them all, but this is what I did...

I started with the list of "executables" from the website, then ran:

    grep -l fastlane /usr/local/bin/*

to find the helper ones that contain a note about being part of fastlane.

Below is the complete script I used to get rid of everything:

```bash
#!/usr/bin/env bash

rm /usr/local/bin/{produce,\
cert,\
sigh,\
snapshot,\
fastlane,\
fastlane-credentials,\
frameit,\
gym,\
deliver,\
pem,\
spaceship,\
pilot,\
boarding,\
match,\
scan,\
🚀}
```

__NOTE:__ If you edit the command, don't leave any extra spaces anywhere as bash gets confused.

**Comment by ssteinerx** [comment]
I don't know whether there is any intention of turning this into a feature request, but I'm sure others will have this question in the future and leaving it visible would probably be a good idea.  Adding it to the docs or FAQ would be even better.

**Comment by samjam48** [comment]
I'm am having this problem and this resource is helpful. Having it visible is definitely useful thanks @ssteinerx

**Comment by ssteinerx** [comment]
As far as I know, this issue still exists and no feature has been created to address it, please leave for search and historical purposes.

**Comment by ssteinerx** [comment]
No, @fastlane-bot.

**Comment by mpirri** [comment]
@ssteinerx This issue will remain searchable, even if closed (as suggested by our good friend Mr. Bot). We're happy to reopen it open if you think there is further discussion to be had, but otherwise there is no downside to closing it.

**Comment by ssteinerx** [comment]
@mpirri I was hoping that it would be turned into an "Uninstaller" feature request/planned feature etc.  Is there something I need to do to make that happen?

**Comment by mpirri** [comment]
Currently we rely on the "uninstaller" that is native to the install method that is used - either `gem uninstall`, `brew uninstall`, or the [packaged _fastlane_ uninstall script](https://github.com/fastlane/packaged-fastlane/blob/master/uninstall). Do you know which install method you used to end up with these files? Also, it could be that this is a side-effect of upgrading from _fastlane_ 1.x (with separate tool binaries) to 2.x (with a single `fastlane` binary) - is that possible?

**Comment by ssteinerx** [comment]
@mpirri  Sorry, it was too long ago.  I'll be back into that project shortly and I'll see if I left myself any notes.  The uninstall script assumes that everything is one specific fastlane directory and just kills that directory.  All of the fastlane 'executables' were in `/usr/local/bin` which would be a bad thing to delete.  Was its location in `/usr/local/bin` an artifact of an older install?

**Comment by alonp99** [comment]
The following worked for me:

1. uninstall with brew/gem
2. clone https://github.com/fastlane/packaged-fastlane
3. run `./uninstall` from packaged-fastlane folder
