### ISSUE TITLE
fastlane search_plugins key returns only results that starts from key

### ISSUE THREAD

**Issue by yuriy-tolstoguzov** [fastlane/fastlane#8580]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am not sure is it a bug or I use it wrong, but when I search, for example, `changelog` and expect it to return: changlelog, ci_changelog and changelog_generator. As I see it only returns those matches that starts from search query (in this case: changlelog, changelog_generator). I've tested it on different inputs. 
I tried to find reason of that and can't understand why it works like that in `PluginFetcher` it checks it like that:

```ruby
plugins.keep_if do |current|
  current.full_name.include?(search_query)
end
```

Which should work even if search query in the middle of plugin name.

P.S. Before that it does query to API with fastlane-plugin prefix + my search query. 
```
url = "https://rubygems.org/api/v1/search.json?query=#{PluginManager.plugin_prefix}#{search_query}&page=#{page}"
```
I think that the root of problems. Unfortunately, I have not found regex syntax documentation for that. Please advise.

Command Used: `search_plugins changelog`
<details><summary>Output/Log</summary>

```

INFO [2017-03-19 17:10:57.99]: Successfully loaded custom action '/Users/ossir/Desktop/AttrProject/Intro/fastlane/actions/jira_issue_ids_from_changelog.rb'.
INFO [2017-03-19 17:10:58.00]: Successfully loaded custom action '/Users/ossir/Desktop/AttrProject/Intro/fastlane/actions/set_jira_fix_version.rb'.
DEBUG [2017-03-19 17:10:58.00]: Checking if there are any plugins that should be loaded...
INFO [2017-03-19 17:10:58.09]: Looking for fastlane plugins containing 'changelog'...
DEBUG [2017-03-19 17:10:58.09]: RubyGems API Request: https://rubygems.org/api/v1/search.json?query=fastlane-plugin-changelog&page=1
DEBUG [2017-03-19 17:10:58.95]: RubyGems API Request: https://rubygems.org/api/v1/search.json?query=fastlane-plugin-changelog&page=2

+---------------------+-----------------------------------------------+-----------+
|                          fastlane plugins 'changelog'                           |
+---------------------+-----------------------------------------------+-----------+
| Name                | Description                                   | Downloads |
+---------------------+-----------------------------------------------+-----------+
| changelog           | Automate changes to your project CHANGELOG.md | 10544     |
| changelog_generator | Changelog generation based on merged pull     | 720       |
|                     | requests &amp; tags                           |           |
+---------------------+-----------------------------------------------+-----------+



```

</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.11.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.10.1 (Apple Git-78)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.11.6 (15G31)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.18.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    test
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.20.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.3        |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-03-19**
</details>

**Comment by yuriy-tolstoguzov** [comment]
Any ideas how to properly construct this query or how to fix `url` for searching plugins?

**Comment by KrauseFx** [comment]
Whops, sorry for not coming back earlier. That seems like something that should be fixed 👍

**Comment by KrauseFx** [comment]
I don't know if there is a way to pass wildcards, but something that's potentially a useful change. I'll leave this issue open for now.
