### ISSUE TITLE
Unclear what command replaced the setup_for_device_change in fast lane 1.0

### ISSUE THREAD

**Issue by damcify** [fastlane/fastlane#8585]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have searched for many hours now and fail to see what the recommended approach is to prep the simulator before creating snapshots. In this particular case I want to copy database files to the apps Documents directory in the simulator.
Previously there was a thread describing how to use the custom callback setup_for_device_change.
I have not been able to find any such examples for the new version (>=1) of snapshot.

Here I see it was removed https://github.com/fastlane/fastlane/blob/master/snapshot/MigrationGuide.md

This is an example that lead me to believe it is the recommended approach:
https://github.com/fastlane/examples/blob/master/MindNode/Snapfile

What is the recommended replacement for callbacks to copy database files to the app in the simulator?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
Will do later. Not relevant to question though. 
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.3                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.10.1 (Apple Git-78)               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.3 (16D32)                        |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 8.2.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.93.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: " Wait Launch") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.20.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-03-20**
</details>

**Comment by damcify** [comment]
I have searched for many hours now and fail to see what the recommended approach is to prep the simulator before creating snapshots. In this particular case I want to copy database files to the apps Documents directory in the simulator. 
Previously there was a thread describing how to use the custom callback setup_for_device_change.
I have not been able to find any such examples for the new version (>=1) of snapshot. 
What is the recommended replacement for callbacks to copy database files to the app in the simulator?

**Comment by KrauseFx** [comment]
I'd recommend using flags to tell your app it's running in _snapshot_ mode and then modifying the data accordingly

**Comment by damcify** [comment]
Thanks, but it is a lot of data that I won't bundle in the app, and it takes a long time to generate, so I prefer to copy it into the Documents folder of the app in all of the simulators.

Can you confirm there is no "built in" replacement for the legacy option "setup_for_device_change" in the snapshot file? 

I will most likely try calling a shell command for copying files from a source dir to the target simulator dir. I know how to retrieve the working directory when running an XCTest in Xcode - just need to figure out how to run a shell script if at all possible from XCTest... Will start googling... ( Any tips are welcome) 

I will close the issue when confirmed there is no official replacement callback for setup_for_device_change.

**Comment by KrauseFx** [comment]
It seems like there isn't, however that's something that could be added to _snapshot_. Let me know if you want to dive in to add this to _snapshot_ 👍

**Comment by damcify** [comment]
Currently I have added a Run Script phase in Xcode to copy these files to the bundle when in debug mode. Additionally I have added some code in the app (debug only) that copies these files from the bundle to the Documents directory. Not so pretty but it works. Never keen on changing the app code (even if it excluded in release builds).
I cant commit to updating snapshot I am afraid even though I would love too if I had the time! (Barely have time to keep my app alive :-(  )   I will never say never though - who knows. Would have to learn ruby I guess?

**Comment by damcify** [comment]
Use this run script in Xcode:
RESOURCE_PATH=$SRCROOT/../jpegdata
BUILD_APP_DIR=${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app
echo "buildappdir" $BUILD_APP_DIR
if [ "$CONFIGURATION" == "Debug" ]; then
     cp $RESOURCE_PATH/*.jpg "$BUILD_APP_DIR"
fi

And use this in my applicationdelegate of my app copy the files from my bundle to my Documents directory. 
This query helped me figure it out:
http://stackoverflow.com/questions/10915859/unable-to-copy-file-from-bundle-to-documents-directory-why-does-fileexistsatpat
