### ISSUE TITLE
Feature: `on_interrupt` block in Fastfile that gets run on `Interrupt` (ctrl-c) exception

### ISSUE THREAD

**Issue by johnboiles** [fastlane/fastlane#859]
**What I propose**
I propose adding an additional block, named `on_interrupt` (or possibly just `interrupt`) that gets run on an `Interrupt` exception (ie ctrl-c). This block would be like `error` and `after_all`, in that it would apply to all lanes for the current platform.

**My use case**
I've got custom steps in my `Fastfile` to unlock certain `.keychain` files and make them the default keychain when building for release. Then in my `error` or `after_all` blocks, I reset the keychain to the default login keychain. This works great, unless I ctrl-c out of a running lane. Then neither `error` or `after_all` blocks get called, so the build keychain remains the default. It's possible to add a `begin/rescue/end` to each lane in the `Fastfile`, like the following:

```
  desc "Build release"
  lane :release do
    begin
      snapshot
      unlock_keychain
      sigh
      gym
      restore_keychain
      deliver
    rescue Interrupt
      restore_keychain
      raise
    end
  end
```

But it's repetitious to have this for each lane and detracts from the simplicity of the Fastfile. An `on_interrupt` block seems like something that could be generally useful.

I'm a Ruby noob but might take this on, if @KrauseFx thinks this makes sense.

**Comment by OdNairy** [comment]
I want to +1 this issue. It have sense when working with keychains or temporary directory creation. 
Actually we can improve `after_all` block to call even for Interrupt action.

**Comment by Sajjon** [comment]
@johnboiles :+1: for the idea of interrupt block, is there currently no way of achieving this? Any work around?

**Comment by johnboiles** [comment]
@Sajjon just the per-lane `begin`/`rescue` method above was all I could come up with.

**Comment by ohwutup** [comment]
Hey everyone! I am going to close this issue as it hasn't been active in a while. Please feel free to continue discussions and we can absolutely reopen if necessary! Thanks! :eyeglasses:
