### ISSUE TITLE
Unable to run Build

### ISSUE THREAD

**Issue by imranbaigOps** [fastlane/fastlane#8597]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

 ```
  +------+-------------------------------------+-------------+
  |                     fastlane summary                     |
  +------+-------------------------------------+-------------+
  | Step | Action                              | Time (in s) |
  +------+-------------------------------------+-------------+
  | 1    | Verifying required fastlane version | 0           |
  | 2    | default_platform                    | 0           |
  | 3    | Switch to ios config lane           | 0           |
  | 4    | Switch to ios test lane             | 0           |
  | 5    | scan                                | 59          |
  | 💥   | slather                             | 20          |
  +------+-------------------------------------+-------------+
  [00:36:21]: fastlane finished with errors
  Looking for related GitHub issues on fastlane/fastlane...
  Found no similar issues. To create a new issue, please visit:
  https://github.com/fastlane/fastlane/issues/new
  Run `fastlane env` to append the fastlane environment to your issue
  /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:692:in `verify_gem_home': [!] You d
  on't have write permissions for the /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0 directory. (Gem::FilePermis
  sionError)
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:811:in `pre_install_checks'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:278:in `install'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/resolver/specification.rb:97:in `install'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:166:in `block in install'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `each'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `install'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:250:in `install_gem
  '
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/fastlane_require.r
  b:36:in `install_gem_if_needed'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/helper/gem_helper.
  rb:7:in `verify_gem!'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/slather.rb
  :42:in `run'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:243:in `
  block (2 levels) in execute_action'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/actions/actions_he
  lper.rb:50:in `execute_action'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:221:in `
  block in execute_action'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `
  chdir'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:217:in `
  execute_action'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:139:in `
  trigger_action_by_name'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/fast_file.rb:146:i
  n `method_missing'
  	from Fastfile:95:in `block (2 levels) in parsing_binding'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane.rb:33:in `cal
  l'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane.rb:33:in `cal
  l'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:49:in `b
  lock in execute'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `c
  hdir'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/runner.rb:45:in `e
  xecute'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/lane_manager.rb:52
  :in `cruise_lane'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/command_line_handl
  er.rb:30:in `handle'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator
  .rb:105:in `block (2 levels) in run'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_acti
  ve_command'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane_core/lib/fastlane_core/ui/fastl
  ane_runner.rb:38:in `run!'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator
  .rb:302:in `run'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/commands_generator
  .rb:42:in `start'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/fastlane/lib/fastlane/cli_tools_distribu
  tor.rb:65:in `take_off'
  	from /Users/admin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.20.0/bin/fastlane:20:in `<top (required)>'
  	from /Users/admin/.fastlane/bin/bundle/bin/fastlane:22:in `load'
  	from /Users/admin/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

  Error Output:

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.20.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-03-21**
</details>

**Comment by javanwood** [comment]
Could this be it? From a clean install:
```
$ cd ~/.fastlane/bin/bundle/ruby/
$ ls
2.0.0
```
Doesn't have permission because it doesn't exist?!

**Comment by javanwood** [comment]
I'm facing a similar issue

**Comment by entreprenik2** [comment]
I had to:
```
sudo chown -R <me>:staff /Users/<me>/.fastlane/bin/bundle/lib/ruby/gems/2.2.0
sudo chown -R <me>:staff /Users/<me>/.fastlane/bin/bundle/bin
```

to fix the permission error.

**Comment by ohayon** [comment]
Hey everyone, glad to see that re-owning your `~/.fastlane` directory has fixed things for you. I am going to close this issue for now, but please let us know if you are still running into this issue! 🚀
