### ISSUE TITLE
Bamboo can't run a Fastlane lane

### ISSUE THREAD

**Issue by LuffyCosta** [fastlane/fastlane#8613]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to make bamboo make a daily build, when i run the fastlane beta command in the terminal it works but when bambo tries it is saying : Code signing is required for product type 'Application' in SDK 'iOS 10.2'

in Bamboo i configured a simple job to move to the project folder and to run fastlane beta, is there anything i am missing it is the first time i am working with bamboo

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.19.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    cert
    sigh(
       force: false
       )
    gym(
      clean: true
    ) # Build your app - more options available
    #pilot
    crashlytics(api_token: "2d0f6f32b1f4ce5322258bc0b964fb799583eae5",
              build_secret: "30d7659cfbe3a72e81fa58126b735857f29c84c35bb924eea362b5ed97b7db2c")

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(
    scheme: "Survey") # Build your app - more options available
    deliver(force: true,
    output_directory: "/Users/bamboo/Downloads")
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xpand-it.survey" # The bundle identifier of your app
apple_id "fabric.mobile@xpand-it.com" # Your Apple email address

team_id "NB5SMLFRY7"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.20.0  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status |
| ------------------------------------------ | ------- | ------------- |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| CFPropertyList                             | 2.3.5        |
| activesupport                              | 4.2.7.1      |
| addressable                                | 2.5.0        |
| babosa                                     | 1.0.2        |
| bigdecimal                                 | 1.2.6        |
| bundler                                    | 1.14.3       |
| claide                                     | 1.0.1        |
| colored                                    | 1.2          |
| commander                                  | 4.4.3        |
| domain_name                                | 0.5.20161129 |
| dotenv                                     | 2.2.0        |
| excon                                      | 0.55.0       |
| excon                                      | 0.54.0       |
| faraday                                    | 0.11.0       |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.11.0.1     |
| fastimage                                  | 2.1.0        |
| fastimage                                  | 2.0.1        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
| gh_inspector                               | 1.0.3        |
| google-api-client                          | 0.9.26       |
| googleauth                                 | 0.5.1        |
| highline                                   | 1.7.8        |
| http-cookie                                | 1.0.3        |
| httpclient                                 | 2.8.3        |
| hurley                                     | 0.2          |
| i18n                                       | 0.8.1        |
| i18n                                       | 0.7.0        |
| io-console                                 | 0.4.3        |
| json                                       | 1.8.1        |
| jwt                                        | 1.5.6        |
| libxml-ruby                                | 2.9.0        |
| little-plugger                             | 1.1.4        |
| logging                                    | 2.2.0        |
| logging                                    | 2.1.0        |
| memoist                                    | 0.15.0       |
| mime-types                                 | 3.1          |
| mime-types-data                            | 3.2016.0521  |
| mini_magick                                | 4.5.1        |
| minitest                                   | 5.10.1       |
| minitest                                   | 5.4.3        |
| multi_json                                 | 1.12.1       |
| multi_xml                                  | 0.6.0        |
| multipart-post                             | 2.0.0        |
| nanaimo                                    | 0.2.3        |
| nokogiri                                   | 1.5.6        |
| os                                         | 0.9.6        |
| plist                                      | 3.2.0        |
| power_assert                               | 0.2.2        |
| psych                                      | 2.0.8        |
| public_suffix                              | 2.0.5        |
| rake                                       | 10.4.2       |
| rdoc                                       | 4.2.0        |
| representable                              | 2.3.0        |
| retriable                                  | 2.1.0        |
| rouge                                      | 1.11.1       |
| rubygems-update                            | 2.5.2        |
| rubyzip                                    | 1.2.1        |
| rubyzip                                    | 1.2.0        |
| security                                   | 0.1.3        |
| signet                                     | 0.7.3        |
| slack-notifier                             | 1.5.1        |
| sqlite3                                    | 1.3.13       |
| terminal-notifier                          | 1.7.1        |
| terminal-table                             | 1.7.3        |
| test-unit                                  | 3.0.8        |
| thread_safe                                | 0.3.6        |
| thread_safe                                | 0.3.5        |
| tty-screen                                 | 0.5.0        |
| tzinfo                                     | 1.2.2        |
| uber                                       | 0.0.15       |
| unf                                        | 0.1.4        |
| unf_ext                                    | 0.0.7.2      |
| unicode-display_width                      | 1.1.3        |
| word_wrap                                  | 1.0.0        |
| xcodeproj                                  | 1.4.2        |
| xcpretty                                   | 0.2.4        |
| xcpretty-travis-formatter                  | 0.0.4        |
</details>

*generated on:* **2017-03-22**
</details>]

**Comment by mgrebenets** [comment]
@LuffyCosta 

You need to make sure that your Bamboo setup matches your laptop setup.

You need to have same keychain(s) installed.
Before you run `gym` and any kind of code signing operation, you need to make sure that correct keychain is used and unlocked. Keep in mind that most keychains will be unlocked for 5 minutes only by default, so if you unlock then build and your build takes longer than 5 mins, you will end up having errors.

We are using Debug configuration for debugging and Release for the distribution builds. Code signing identity and provisioning profiles are configured as part of Xcode build settings. So on CI server we have to make sure the expected keychain is available and unlocked.

**Comment by LuffyCosta** [comment]
@mgrebenets

The bambo server is my laptop :( it is running using sudo so the keychain beeing locked or not having the necessary certificates it is the most likely, can you please tell me how can i unlock it ou change it to use the user keychain instead of the system?

**Comment by mgrebenets** [comment]
Oh, `sudo` - that's probably 2nd largest source of problems after `HTTP_PROXY` vars :)

I would recommend to change Bamboo setup to _not_ use `sudo` - that surprisingly solves tons of issues, starting from write permission and ending up with keychains access.

I mean the keychains are configured for you normal user, right?
When Bamboo runs as super user, it probably doesn't even get access to same list of keychains.

`security` is the command line utility that you can try to use directly to list, unlock and do other things with keychains.

What do you see if you run `security list-keychains` as part of your CI scripts?
Does the super user even see the keychains it needs to see?

That's where I'd start looking, but in the long run, `sudo` is the difficult bit and getting rid of it would be for good.

**Comment by LuffyCosta** [comment]
I have this on bamboo when i ran the Security list-keychains:

27-Mar-2017 14:29:08	    "/Users/fastlane/Library/Keychains/login.keychain-db"
27-Mar-2017 14:29:08	    "/Library/Keychains/System.keychain"

and when in run it a terminal it gives me the same result.

I think you are right when i use the sudo fastlane beta it gives me the same error in the terminal as in Bamboo, yes you are right this is eating my mind :S i think i am going mad :P

**Comment by LuffyCosta** [comment]
I have changed bamboo to the user it is working but now it is giving me this

[16:04:14]: ▸ Archive Succeeded
xattr: No such file: /Users/fastlane/Library/Developer/Xcode/Archives/2017-03-27/Survey 2017-03-27 16.04.11.xcarchive
[16:04:14]: The generated archive is invalid, this can have various reasons:
[16:04:14]: Usually it's caused by the `Skip Install` option in Xcode, set it to `NO`
[16:04:14]: For more information visit https://developer.apple.com/library/ios/technotes/tn2215/_index.html
[16:04:14]: Also, make sure to have a valid code signing identity and provisioning profile installed
[16:04:14]: Follow this guide to setup code signing https://docs.fastlane.tools/codesigning/GettingStarted/
[16:04:14]: If your intention was only to export an ipa be sure to provide a valid archive at the archive path.

:(

**Comment by LuffyCosta** [comment]
got it running by changing the archive path but now it asks me for a password every time

**Comment by mgrebenets** [comment]
I guess Login keychain is the default, so it needs to unlock System keychain to use it...
Are your private keys and certs still in System keychain?
Can you move them from System to Login?
Since you are not using `sudo` any more, it only makes sense to put keychain items to Login keychain.
That's the basic setup, something to start with.

If you get it working, you can then create more keychains and unlock/set-as-default those keychains as part of your lanes.

**Comment by LuffyCosta** [comment]
Wow thank you soooo much you help a lot :D
