### ISSUE TITLE
Versions can’t have more than one build

### ISSUE THREAD

**Issue by castus** [fastlane/fastlane#8616]
### New Issue Checklist

- [ ] Updated fastlane to the latest version - no, I cannot do that ;(
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

I want to distribute build to Internal Testers. I upload it successfully but during distribution I have an error. Currently I use fastlane 2.19.3 and I cannot install the newest version, I hope this isn't an issue. My app has 14 targets but I want to distribute only one target. In fact, I have multiple versions in ITC already. One of them is currently distributed to testers and the rest is not.

Can you help?

```
$ fastlane pilot distribute --team_name "XXX" --team_id "XXX" -a "XXX" --verbose
INFO [2017-03-22 17:34:44.42]: Login to iTunes Connect (XX@XX.XX)
Looking for iTunes Connect Team with ID XXX
INFO [2017-03-22 17:34:48.53]: Login successful
DEBUG [2017-03-22 17:34:48.53]: App identifier (XXX)
INFO [2017-03-22 17:34:52.95]: Distributing build 1.0.1(170322122814) from Expired -> Internal
INFO [2017-03-22 17:34:52.95]: Distributing new build to testers

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Versions can’t have more than one build.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Versions%20can%E2%80%99t%20have%20more%20than%20one%20build.+repo:fastlane/fastlane
➡️  Submit TF beta only with minor changes, without review
   https://github.com/fastlane/fastlane/issues/8507 [open] 3 💬
   a week ago

➡️  [pilot] "Error receiving the newly uploaded binary" on the very first upload
   https://github.com/fastlane/fastlane/issues/5125 [closed] 79 💬
   01 Feb 2017

➡️  Pilot does not detect completion of iTunes connect processing.
   https://github.com/fastlane/fastlane/issues/3888 [closed] 24 💬
   13 Nov 2016

and 4 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Versions%20can%E2%80%99t%20have%20more%20than%20one%20build.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

/Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/tunes/tunes_client.rb:222:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	Versions can’t have more than one build.
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/tunes/tunes_client.rb:781:in `update_build_trains!'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/spaceship/lib/spaceship/tunes/build_train.rb:148:in `update_testing_status!'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/pilot/lib/pilot/build_manager.rb:207:in `distribute_build'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/pilot/lib/pilot/build_manager.rb:76:in `distribute'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/pilot/lib/pilot/commands_generator.rb:71:in `block (2 levels) in run'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/pilot/lib/pilot/commands_generator.rb:158:in `run'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Users/XXX/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.19.3/bin/fastlane:15:in `<top (required)>'
	from /Users/XXX/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/XXX/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.5                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.3 (Apple Git-75)            |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.11.5 (15F34)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.19.3  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-03-22**
</details>

**Comment by jarod2d** [comment]
I'm seeing the same issue. I have Fastlane set up to bump the build number, build the project, then push to testflight and distribute to internal testers. The build uploads and finishes processing correctly, but fails with "Versions can’t have more than one build" when trying to distribute.

Fastlane output: https://gist.github.com/jarod2d/a72c016b51f5edd52a253e71a230ea7f

**Comment by jarod2d** [comment]
It looks like the issue is caused by encryption export compliance. If you don't have `ITSAppUsesNonExemptEncryption` in your Info.plist, then you have to manually specify whether you use encryption or not in iTunes Connect for each build. After I added it to my Info.plist, the errors stopped, and builds are now properly released to TestFlight automatically.

The error message is very misleading here -- any improvements that could be made to it would be very much appreciated.

**Comment by castus** [comment]
@jarod2d you are right, when I added it to plist file everything starting to work, many thanks!
