### ISSUE TITLE
Script fails at clean_build_artifacts.rb:21 #mac #hockeyapp #zip

### ISSUE THREAD

**Issue by gerbil802** [fastlane/fastlane#8619]
Hi guys,

It seems that my lane script gets an error in the clean_build_artifacts phase.
This is the error I'm getting:

```
/Users/user/.rvm/gems/ruby-2.3.3@global/gems/fastlane-2.22.0/fastlane/lib/fastlane/actions
/clean_build_artifacts.rb:21:in `delete': [!] Operation not permitted @ unlink_internal - 
/Users/user/Developer/MyApp (Errno::EPERM)
```

This is the lane:
```
lane :mac do  
  default_platform :mac
  ensure_git_status_clean
  git_pull
  scan(
    scheme: "MyApp_macOS"
  )  
  ensure_git_status_clean
  increment_build_number
  commit_version_bump
  push_to_git_remote
  gym(
    scheme: "MyApp_macOS"
  )
  zip(
      path: "myapp.app",
      output_path: "myapp.app.zip"
  )
  hockey(
    api_token: "...",
    ipa: "myapp.app.zip",
    dsym: "myapp.app.dSYM.zip",
    notes: "Build " + (ENV["BUILD_NUMBER"] ? ENV["BUILD_NUMBER"] + " " : "") + "From " + git_branch + " branch on " + Time.now.strftime('%F') + " at " + Time.now.strftime('%T'),
    notify: "0"
  )
  clean_build_artifacts
end
```

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.0                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.3/bin/fastlane       |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "fc660f54-f2ea-4da7-9a96-59302b402341"

before_all do
  # slack_url = get_global_value(key: "BMESlackUrl")
  # ENV["SLACK_URL"] = slack_url
  # ENV["BME_APP_TITLE"] = "Be My Eyes – Helping blind see"
end

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :ios do  
  default_platform :ios
  ensure_git_status_clean
  git_pull
  scan(
    scheme: "Memory"
  )  
  ensure_git_status_clean
  increment_build_number
  commit_version_bump
  push_to_git_remote

  # build your iOS app
  gym(
    scheme: "Memory"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true,
        username: "talshrestha@gmail.com")

  # slack(
  #   # slack_url: "https://hooks.slack.com/services/IDS"
  # )
end

# lane :hockeyapp do |options|
#     zip(
#         path: "#memory.app",
#         output_path: "#memory.app.zip"
#     )
#     hockey(
#       api_token: "b8263d3806e14104822bdec81b3910cc",
#       ipa: "#memory.app.zip",
#       dsym: "#memory.app.dSYM.zip",
#       notes: "Build " + (ENV["BUILD_NUMBER"] ? ENV["BUILD_NUMBER"] + " " : "") + "From " + git_branch + " branch on " + Time.now.strftime('%F') + " at " + Time.now.strftime('%T'),
#       notify: "0"
#     )
#   end

lane :mac do  
  default_platform :mac
  ensure_git_status_clean
  # git_pull
  # scan(
  #   scheme: "Memory - macOS"
  # )  
  # ensure_git_status_clean
  # increment_build_number
  # commit_version_bump
  # push_to_git_remote
  gym(
    scheme: "Memory - macOS"
  )
  zip(
      path: "#memory.app",
      output_path: "#memory.app.zip"
  )
  hockey(
    api_token: "b8263d3806e14104822bdec81b3910cc",
    ipa: "#memory.app.zip",
    dsym: "#memory.app.dSYM.zip",
    notes: "Build " + (ENV["BUILD_NUMBER"] ? ENV["BUILD_NUMBER"] + " " : "") + "From " + git_branch + " branch on " + Time.now.strftime('%F') + " at " + Time.now.strftime('%T'),
    notify: "0"
  )
  # deliver( 
  #   username: "talshrestha@gmail.com",
  #   app_identifier: "com.firstclass.memorymacos",
  #   app: "1201734252"
  # )
  # slack(
  #   # slack_url: "https://hooks.slack.com/services/IDS"
  # )
end

after_all do |lane|
  clean_build_artifacts
  notification(subtitle: "Finished Building", message: "Ready to upload...") # Mac OS X Notification
end

error do |lane, exception|
  puts exception
  # clean_build_artifacts
  # Something bad happened
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.22.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.2       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.23       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.6        |
</details>

*generated on:* **2017-03-22**
</details>

**Comment by switchawk** [comment]
No change..

**Comment by switchawk** [comment]
This is a Mac target.

**Comment by switchawk** [comment]
This thing keeps happening consistently. Anyone has success clean_build_artifacts for Mac targets?

**Comment by ohayon** [comment]
Hey @switchawk, apologies for the delayed response - it looks like your user may not have permissions to delete the files from your machine. Could you verify that you have permissions to delete those files manually? Thanks! 🚀

**Comment by switchawk** [comment]
Confirming there is permission (also iOS script runs with no issue)

**Comment by triplef** [comment]
I’m having the same issue. I think the problem is that [`clean_build_artefacts` uses `File.delete`](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/clean_build_artifacts.rb#L21), which will not delete directories (like app bundles).

To workaround you could manually delete the app bundle after the `zip` step like this:
```ruby
FileUtils.rm_rf "myapp.app"
```

I wonder if there is any reason why `clean_build_artefacts` wouldn’t also clean folder-type artefacts.

**Comment by ohayon** [comment]
Hey @triplef - it looks like you are also building a macOS app like @gerbil802 is right? Currently the `clean_build_artifacts` action only really supports iOS apps. Would you both mind sharing some more of your output? It would also help if you could run the command with `--verbose` so that we can see some more detail around what is trying to be deleted. Thanks!! 🐙
