### ISSUE TITLE
option for sh to control verbosity?

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#862]
Having a Travis CI build.
in my FastFile i have for example
```ruby
somevar=sh("curl '#{ENV["SECRET_URL"]}' --silent")
```
`SECRET_URL` variable is declared as secure, but sh prints the command as is, including the unhidden url. Is there a way to perform sh silently, so the url won't appear in execution log?

**Comment by xfreebird** [comment]
Try setting ```log``` to ```false```:

 ```ruby
somevar = sh("curl '#{ENV["SECRET_URL"]}' --silent", log: false)
```

**Comment by KrauseFx** [comment]
Yes, the `log` options should be the thing you're looking for.

**Comment by Sega-Zero** [comment]
`sh('echo test', log: false)` gives me an error:
> ArgumentError: wrong number of arguments (2 for 1)

**Comment by xfreebird** [comment]
Appologies, it looks that for ```Fastlane``` the ```sh``` method is not the same as for the ```actions```.

In our case you would have to use
```ruby
Fastlane::Actions::sh(command: 'echo test', log: false)
```
but here I get a weird error that it can't find the ```yellow``` method name, despited importing the ```colored``` gem.

or

```ruby
somevar =  `echo test`
```

**Comment by ohwutup** [comment]
I'm going to close this due to inactivity, but please feel free to reopen if this is still an issue with up-to-date tools! Thanks ! :tangerine:
