### ISSUE TITLE
Zip action description improvement

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#8620]
🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`zip` action has parameter `output_path` however, according the implementation of the action it expects to be just an output name not path. I think maybe the action can be in two ways:
1. Support path as a parameter and do not raise a `zip` command exception with message 
    `Exit status of command 'zip -r ./bin/FBSnapshotsViewerRunPhaseScript-0.1.0.zip
 FBSnapshotsViewerRunPhaseScript' was 15 instead of 0.`
2. Rename the `output_path` parameter to `output_name`.
For me personally, the first option looks much better.

### Captured Output

Command Used: `osx release`
<details><summary>Output/Log</summary>

```

INFO [2017-03-23 09:39:27.71]: Successfully loaded custom action '/Users/antondomashnev/Work/FBSnapshotsViewer/fastlane/actions/edit_github_release.rb'.
DEBUG [2017-03-23 09:39:27.71]: Checking if there are any plugins that should be loaded...
INFO [2017-03-23 09:39:27.73]: -------------------------------------------------
INFO [2017-03-23 09:39:27.73]: --- Step: Verifying required fastlane version ---
INFO [2017-03-23 09:39:27.73]: -------------------------------------------------
INFO [2017-03-23 09:39:27.73]: Your fastlane version 2.21.0 matches the minimum requirement of 2.21.0  ✅
INFO [2017-03-23 09:39:27.73]: ------------------------------
INFO [2017-03-23 09:39:27.73]: --- Step: default_platform ---
INFO [2017-03-23 09:39:27.73]: ------------------------------
WARN [2017-03-23 09:39:27.73]: Platform 'osx' is not officially supported. Currently supported plaforms are [:ios, :mac, :android].
WARN [2017-03-23 09:39:27.73]: Platform 'osx' is not officially supported. Currently supported plaforms are [:ios, :mac, :android].
INFO [2017-03-23 09:39:27.74]: Driving the lane 'osx release' 🚀
INFO [2017-03-23 09:39:27.74]: ----------------------------
INFO [2017-03-23 09:39:27.74]: --- Step: bundle_install ---
INFO [2017-03-23 09:39:27.74]: ----------------------------
INFO [2017-03-23 09:39:27.74]: $ bundle install
INFO [2017-03-23 09:39:28.29]: ▸ Using CFPropertyList 2.3.5
INFO [2017-03-23 09:39:28.29]: ▸ Using i18n 0.8.0
INFO [2017-03-23 09:39:28.29]: ▸ Using json 1.8.6
INFO [2017-03-23 09:39:28.29]: ▸ Using minitest 5.10.1
INFO [2017-03-23 09:39:28.30]: ▸ Using thread_safe 0.3.5
INFO [2017-03-23 09:39:28.30]: ▸ Using public_suffix 2.0.5
INFO [2017-03-23 09:39:28.30]: ▸ Using babosa 1.0.2
INFO [2017-03-23 09:39:28.30]: ▸ Using claide 1.0.1
INFO [2017-03-23 09:39:28.30]: ▸ Using fuzzy_match 2.0.4
INFO [2017-03-23 09:39:28.30]: ▸ Using nap 1.1.0
INFO [2017-03-23 09:39:28.30]: ▸ Using cocoapods-deintegrate 1.0.1
INFO [2017-03-23 09:39:28.30]: ▸ Using cocoapods-downloader 1.1.3
INFO [2017-03-23 09:39:28.30]: ▸ Using cocoapods-search 1.0.0
INFO [2017-03-23 09:39:28.30]: ▸ Using cocoapods-stats 1.0.0
INFO [2017-03-23 09:39:28.30]: ▸ Using netrc 0.7.8
INFO [2017-03-23 09:39:28.30]: ▸ Using cocoapods-try 1.1.0
INFO [2017-03-23 09:39:28.30]: ▸ Using colored 1.2
INFO [2017-03-23 09:39:28.30]: ▸ Using escape 0.0.4
INFO [2017-03-23 09:39:28.30]: ▸ Using fourflusher 2.0.1
INFO [2017-03-23 09:39:28.30]: ▸ Using gh_inspector 1.0.3
INFO [2017-03-23 09:39:28.30]: ▸ Using molinillo 0.5.5
INFO [2017-03-23 09:39:28.30]: ▸ Using ruby-macho 0.2.6
INFO [2017-03-23 09:39:28.30]: ▸ Using nanaimo 0.2.3
INFO [2017-03-23 09:39:28.30]: ▸ Using highline 1.7.8
INFO [2017-03-23 09:39:28.30]: ▸ Using unf_ext 0.0.7.2
INFO [2017-03-23 09:39:28.30]: ▸ Using dotenv 2.2.0
INFO [2017-03-23 09:39:28.30]: ▸ Using excon 0.55.0
INFO [2017-03-23 09:39:28.30]: ▸ Using multipart-post 2.0.0
INFO [2017-03-23 09:39:28.30]: ▸ Using fastimage 2.1.0
INFO [2017-03-23 09:39:28.30]: ▸ Using bundler 1.13.7
INFO [2017-03-23 09:39:28.30]: ▸ Using jwt 1.5.6
INFO [2017-03-23 09:39:28.30]: ▸ Using little-plugger 1.1.4
INFO [2017-03-23 09:39:28.30]: ▸ Using multi_json 1.12.1
INFO [2017-03-23 09:39:28.30]: ▸ Using memoist 0.15.0
INFO [2017-03-23 09:39:28.30]: ▸ Using os 0.9.6
INFO [2017-03-23 09:39:28.30]: ▸ Using httpclient 2.8.3
INFO [2017-03-23 09:39:28.30]: ▸ Using hurley 0.2
INFO [2017-03-23 09:39:28.30]: ▸ Using mime-types-data 3.2016.0521
INFO [2017-03-23 09:39:28.30]: ▸ Using uber 0.0.15
INFO [2017-03-23 09:39:28.30]: ▸ Using retriable 2.1.0
INFO [2017-03-23 09:39:28.30]: ▸ Using mini_magick 4.5.1
INFO [2017-03-23 09:39:28.30]: ▸ Using multi_xml 0.6.0
INFO [2017-03-23 09:39:28.30]: ▸ Using plist 3.2.0
INFO [2017-03-23 09:39:28.30]: ▸ Using rubyzip 1.2.1
INFO [2017-03-23 09:39:28.30]: ▸ Using security 0.1.3
INFO [2017-03-23 09:39:28.30]: ▸ Using slack-notifier 1.5.1
INFO [2017-03-23 09:39:28.30]: ▸ Using terminal-notifier 1.7.1
INFO [2017-03-23 09:39:28.30]: ▸ Using unicode-display_width 1.1.3
INFO [2017-03-23 09:39:28.30]: ▸ Using tty-screen 0.5.0
INFO [2017-03-23 09:39:28.30]: ▸ Using word_wrap 1.0.0
INFO [2017-03-23 09:39:28.30]: ▸ Using rouge 1.11.1
INFO [2017-03-23 09:39:28.32]: ▸ Using tzinfo 1.2.2
INFO [2017-03-23 09:39:28.32]: ▸ Using addressable 2.5.0
INFO [2017-03-23 09:39:28.32]: ▸ Using cocoapods-plugins 1.0.0
INFO [2017-03-23 09:39:28.32]: ▸ Using cocoapods-trunk 1.1.2
INFO [2017-03-23 09:39:28.32]: ▸ Using commander 4.4.3
INFO [2017-03-23 09:39:28.32]: ▸ Using unf 0.1.4
INFO [2017-03-23 09:39:28.32]: ▸ Using faraday 0.11.0
INFO [2017-03-23 09:39:28.32]: ▸ Using logging 2.2.0
INFO [2017-03-23 09:39:28.32]: ▸ Using mime-types 3.1
INFO [2017-03-23 09:39:28.32]: ▸ Using representable 2.3.0
INFO [2017-03-23 09:39:28.32]: ▸ Using terminal-table 1.7.3
INFO [2017-03-23 09:39:28.32]: ▸ Using xcpretty 0.2.4
INFO [2017-03-23 09:39:28.32]: ▸ Using activesupport 4.2.7.1
INFO [2017-03-23 09:39:28.32]: ▸ Using domain_name 0.5.20170223
INFO [2017-03-23 09:39:28.32]: ▸ Using faraday_middleware 0.11.0.1
INFO [2017-03-23 09:39:28.32]: ▸ Using signet 0.7.3
INFO [2017-03-23 09:39:28.32]: ▸ Using xcpretty-travis-formatter 0.0.4
INFO [2017-03-23 09:39:28.32]: ▸ Using cocoapods-core 1.2.0
INFO [2017-03-23 09:39:28.32]: ▸ Using xcodeproj 1.4.2
INFO [2017-03-23 09:39:28.32]: ▸ Using http-cookie 1.0.3
INFO [2017-03-23 09:39:28.32]: ▸ Using googleauth 0.5.1
INFO [2017-03-23 09:39:28.32]: ▸ Using cocoapods 1.2.0
INFO [2017-03-23 09:39:28.32]: ▸ Using faraday-cookie_jar 0.0.6
INFO [2017-03-23 09:39:28.32]: ▸ Using google-api-client 0.9.28
INFO [2017-03-23 09:39:28.32]: ▸ Using fastlane 2.21.0
INFO [2017-03-23 09:39:28.32]: ▸ Bundle complete! 2 Gemfile dependencies, 76 gems now installed.
INFO [2017-03-23 09:39:28.32]: ▸ Use `bundle show [gemname]` to see where a bundled gem is installed.
INFO [2017-03-23 09:39:28.34]: -----------------------------------------------------
INFO [2017-03-23 09:39:28.34]: Step: Switch to osx github_create_run_phase_script_release_assets lane
INFO [2017-03-23 09:39:28.34]: -----------------------------------------------------
INFO [2017-03-23 09:39:28.34]: Cruising over to lane 'osx github_create_run_phase_script_release_assets' 🚖
INFO [2017-03-23 09:39:28.35]: -----------------
INFO [2017-03-23 09:39:28.35]: --- Step: zip ---
INFO [2017-03-23 09:39:28.35]: -----------------
INFO [2017-03-23 09:39:28.35]: Compressing ./bin/FBSnapshotsViewerRunPhaseScript...
INFO [2017-03-23 09:39:28.35]: $ zip -r ./bin/FBSnapshotsViewerRunPhaseScript-0.1.0.zip FBSnapshotsViewerRunPhaseScript
INFO [2017-03-23 09:39:28.35]: ▸ zip I/O error: No such file or directory
INFO [2017-03-23 09:39:28.35]: ▸ zip error: Could not create output file (./bin/FBSnapshotsViewerRunPhaseScript-0.1.0.zip)
WARN [2017-03-23 09:39:28.36]: Lane Context:
INFO [2017-03-23 09:39:28.36]: {:DEFAULT_PLATFORM=>:osx, :PLATFORM_NAME=>:osx, :LANE_NAME=>"osx release"}
ERROR [2017-03-23 09:39:28.36]: Exit status of command 'zip -r ./bin/FBSnapshotsViewerRunPhaseScript-0.1.0.zip FBSnapshotsViewerRunPhaseScript' was 15 instead of 0.
zip I/O error: No such file or directory
zip error: Could not create output file (./bin/FBSnapshotsViewerRunPhaseScript-0.1.0.zip)

INFO [2017-03-23 09:39:28.36]: Successfully generated documentation at path '/Users/antondomashnev/Work/FBSnapshotsViewer/fastlane/README.md'

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | bundle_install                                                | 0           |
| 4    | Switch to osx github_create_run_phase_script_release_assets l | 0           |
| 💥   | zip                                                           | 0           |
+------+---------------------------------------------------------------+-------------+

ERROR [2017-03-23 09:39:28.36]: fastlane finished with errors


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.21.0"
default_platform :osx

platform :osx do
  before_all do
    bundle_install
  end

  desc "Release a new version of the FBSnapshotsViewer. Uploading a new release to a GitHub and CocoaPods trunk"
  desc "Before doing so don't forget to move the next version of Changelog to released as well as update FBSnapshotsViewerRunPhaseScript.podspec"
  lane :release do
    ...
    github_create_run_phase_script_release_assets(release_version: "0.1.0")
  end

  desc "Create run phase script asset to be uploaded as a github release"
  desc "####Options"
  desc "* **`release_version`** - releave version to be used as a part of name of asset"
  desc "####Return"
  desc "Path to the asset"
  private_lane :github_create_run_phase_script_release_assets do |options|
    release_version = options[:release_version]
    run_phase_script_path = "./bin/FBSnapshotsViewerRunPhaseScript"
    run_phase_script_zip_name = "./bin/FBSnapshotsViewerRunPhaseScript-#{release_version}.zip"
    run_phase_script_zip_path = "./bin/#{run_phase_script_zip_name}"
    zip(
      path: run_phase_script_path,
      output_path: run_phase_script_zip_name
    )
    run_phase_script_zip_path
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.21.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.0        |
| json                      | 1.8.6        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.5        |
| ruby-macho                | 0.2.6        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.2.0        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-23**
</details>

**Comment by ohayon** [comment]
Hey @Antondomashnev does `./bin/` already exist when you are running this lane?

**Comment by Antondomashnev** [comment]
Hey @ohayon, no it was not existed.

**Comment by Antondomashnev** [comment]
Hey @ohayon yes.
The structure was like this:
```
bin/
  FBSnapshotsViewerRunPhaseScript
fastlane/
  fastfile
```

**Comment by yukiasai** [comment]
@ohayon @Antondomashnev I tried to fix this issue with #8637 according to the 1st suggestion.  Could you review it? Thanks.

**Comment by Antondomashnev** [comment]
@yukiasai thanks a lot, for me it looks 👌 , but I think the review must be done by member.

**Comment by ohayon** [comment]
Thanks @yukiasai! Merged that PR! @Antondomashnev let us know if you have any more issues! 🐙  🚀
