### ISSUE TITLE
Unable to codesign using `match` and `gym` on travis.

### ISSUE THREAD

**Issue by jwaldrip** [fastlane/fastlane#8626]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running on travis I get the following error, this error does not happen locally:

```
❌  Code signing is required for product type 'Application' in SDK 'iOS 10.2'
```

### Captured Output

https://gist.github.com/jwaldrip/1b0cb040b63c7f22ff19f4241db1c2e1

**Comment by jwaldrip** [comment]
@fastlane-bot The env is in the gist. It was too big to include here. Also, I followed the code signing tutorial, still having issues.

**Comment by hjanuschka** [comment]
can you checkout this: https://docs.fastlane.tools/codesigning/getting-started/#automatic-manual-signing

are you sure you configured manual codesigning?

**Comment by toreolsensan** [comment]
Hi @jwaldrip! Did you use Xcode 8.3 when you experienced this problem? I recently tried building a beta with fastlane and Xcode 8.3, which failed with a `Code signing is required…` message. After reverting back to Xcode 8.2 the build succeeded.

I'm doing builds via circleci, not travis. If you can get this to work with 8.2 perhaps we're on to something.

**Comment by KrauseFx** [comment]
If it helps, check out a working fastlane setup on GitHub + Travis using fastlane and match: https://github.com/wwdc-family/app/
