### ISSUE TITLE
Automatic docs generation

### ISSUE THREAD

**Issue by jonah-williams** [fastlane/fastlane#8628]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to update fastlane so I run `bundle update fastlane` which updates my `Gemfile.lock`. Perfect, I make a "update fastlane from x to y" commit and move on.

Later I actually run a lane and notice that `fast lane/README.md` has been updated because the new version of fastlane changed some of the formatting or headers. The change is fine but I wish I had included it in my "update fast lane" commit.

I rebase and edit my commit to see if I can clean this up. `bundle exec fastlane lanes` doesn't update my readme. Running `bundle exec fastlane docs` works but reports:

> You don't need to run `fastlane docs` manually any more, this will be done automatically for you.

Which seems misleading.

I don't actually have a lane I want to run when updating fastlane. Can we have `fastlane lanes` update docs just like running a lane? Is that a side effect we want to avoid in which case maybe plan to continue to support `fastlane docs`? As is it sounds like `docs` is deprecated but I would be sad to lose it.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.gem/ruby/2.3.1/bin/fastlane              |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.1/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

redacted

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.22.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.14.3       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.4        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-23**
</details>

**Comment by ohayon** [comment]
Hey @jonah-williams, I am having a bit of a hard time reproducing this issue. Could you share the steps you took to install _fastlane_ and what version you were coming from when you ran `bundle update fastlane`? Thanks! 🐙

**Comment by jonah-williams** [comment]
This was a `2.8.0` to `2.22.0` update. Initially installed via `bundle install` into a `chruby` managed Ruby (so user not system owned gems, no `sudo`). My `Gemfile` is just `gem 'fastlane'` so the version is only pinned in `Gemfile.lock` which shows a very reasonable diff:

```
...
 -    fastimage (2.0.1)
 -      addressable (~> 2)
 -    fastlane (2.8.0)
 +    fastimage (2.1.0)
 +    fastlane (2.22.0)
...
```

Thanks for looking into this so quickly. I'll try to make time to reproduce in an isolated example repo where I can share it.

**Comment by jonah-williams** [comment]
Reproduced in https://github.com/jonah-williams/fastlane_issue_8628

```
> git clone git@github.com:jonah-williams/fastlane_issue_8628.git
> cd fastlane_issue_8628
> git checkout bae0bb92
> bundle exec fastlane lanes
> git status
HEAD detached at bae0bb9
nothing to commit, working tree clean
> bundle exec fastlane do_stuff
> git status
HEAD detached at bae0bb9
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   fastlane/README.md
	modified:   fastlane/report.xml

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by ohayon** [comment]
Hey @jonah-williams, thank you so much for providing a repo like that to reproduce the issue. Unfortunately, I am still unable to reproduce, when I follow the steps you listed, I only get changes to my `fastlane/report.xml` file and no changes to the README.md. Could you share the diff of your README.md?

**Comment by ohayon** [comment]
Hey @jonah-williams I am successfully reproducing this issue and I think you're right that it is a bit confusing the way this is setup currently. For now, I think the best way to handle this is to add a `before_all` block to your Fastfile that has `skip_docs` inside of it. That way, when running a lane, it will not cause your README.md to be updated. 

We are still supporting the `fastlane docs` command, so you can continue to use that as you have been. 

Let us know if that helps!

**Comment by KrauseFx** [comment]
Unless we ship fastlane 3.0, we won't remove the `fastlane docs` command. Great job @ohayon on tweaking the message. We can't automatically update the doc when you run `bundle update`, as there is no way for us to run code in that case.

**Comment by jonah-williams** [comment]
+1 thanks for taking the time to consider this and for keeping the docs clear. I agree there's no good way to include this automatically in a `bundle update` but I'm happy to keep running `fastlane docs` for now.
