### ISSUE TITLE
nexus_upload : crypted password

### ISSUE THREAD

**Issue by benjdum59** [fastlane/fastlane#863]
Hello,

It would be nice to be able to crypt password in the nexus_upload phase for ipa. The way I see it is the way Maven do in J2EE projects (https://maven.apache.org/guides/mini/guide-encryption.html): inside fastfile, user password is encrypted and inside a global file (e.g. in user's home directory, in a hidden folder), having a master password encrypted.

**Comment by xfreebird** [comment]
I see your point, but in this case you could just pass the password as ```FL_NEXUS_PASSWORD``` env variable. This is more flexible, since you don't depend on the build machine you are executing ```fastlane``` on.

**Comment by benjdum59** [comment]
Thanks for the answer. To create an env variable, I have to create a .env file in the repository/scm workspace. The problem is that I don't want users to know this password. For a better understanding, this is my UC: the only user who has the hability to upload file to nexus is my continuous integration user (e.g. jenkins). This forces developpers to have continuous integration and make some tasks (compilation, unit test, code quality...). What I understand in your answer is that the configuration will be visisble for developpers (which has access to jenkins and its workspace). Is there a way to use system global variable (e.g. in bash_profile)?

**Comment by xfreebird** [comment]
You can set that variable in Jenkins per job or globally. And no one will be able to see that password in config or build logs.

This provided by [Jenkins EnvInject Plugin](https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin)

![alt text](http://s8.postimg.org/fqfgkpmid/Screen_Shot_2015_11_25_at_12_46_49.png "Jenkins config")

**Comment by benjdum59** [comment]
Great! Thanks a lot. Exactly what I need.
