### ISSUE TITLE
Latest fastlane dependency bump for commander-fastlane requires interactive prompt to confirm, breaks automated updates

### ISSUE THREAD

**Issue by loyaltyarm** [fastlane/fastlane#8635]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
Error: Could not update: Execution of '/usr/bin/gem install --no-rdoc --no-ri fastlane --bindir=/usr/local/bin' returned 1: ERROR:  Error installing fastlane:
	"commander" from commander-fastlane conflicts with installed executable from commander
Error: /Stage[main]/Signing_tools/Package[fastlane]/ensure: change from ["2.22.0", "2.21.0", "2.20.0", "2.19.3", "2.19.2", "2.19.1", "2.18.3", "2.18.2", "2.18.1", "2.18.0", "2.17.1", "2.17.0", "2.16.0", "2.15.1", "2.14.2", "2.0.2"] to 2.23.0 failed: Could not update: Execution of '/usr/bin/gem install --no-rdoc --no-ri fastlane --bindir=/usr/local/bin' returned 1: ERROR:  Error installing fastlane:
	"commander" from commander-fastlane conflicts with installed executable from commander
irnhexci01:~ atc$ sudo gem install -n /usr/local/bin commander-fastlane
commander-fastlane's executable "commander" conflicts with commander
Overwrite the executable? [yN]
```

### Environment

fastlane env
[21:44:39]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.3                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.10.1 (Apple Git-78)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.3 (16D32)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.22.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.7.7        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.0        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.9.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| rubyzip                   | 1.2.0        |
</details>

**Comment by KrauseFx** [comment]
Thanks for reporting this, to fix it we have to comment out this line https://github.com/commander-rb/commander/blob/master/commander.gemspec#L17 as we don't need the executable anyway and therefore avoid the conflict. cc @mfurtak

**Comment by mfurtak** [comment]
I've bumped the forked commander library version with that change. Please let me know if it helps :+1:

**Comment by nafu** [comment]
@loyaltyarm Thanks for reporting this 🙂 

@mfurtak Seems good to me 🚀 
```bash
$ gem list commander

*** LOCAL GEMS ***

commander (4.4.3, 4.4.2, 4.4.1, 4.4.0, 4.3.5)
$ gem install 'commander-fastlane'
Fetching: commander-fastlane-4.4.4.gem (100%)
Successfully installed commander-fastlane-4.4.4
Parsing documentation for commander-fastlane-4.4.4
Installing ri documentation for commander-fastlane-4.4.4
Done installing documentation for commander-fastlane after 0 seconds
1 gem installed
```

**Comment by loyaltyarm** [comment]
I verified all is good now, thanks for jumping on this so quickly 🎉👏! Apologies for my slow response, came down with some kind of illness the last few days. 🤒

I'm counting this as resolved for now.

**Comment by KrauseFx** [comment]
Glad to hear you're better now @loyaltyarm 👍
