### ISSUE TITLE
New Action verify_brew or Plugin

### ISSUE THREAD

**Issue by netbe** [fastlane/fastlane#8636]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am writing a new plugin which depends on non-ruby tool that can be installed via `homebrew` so to help with that I was thinking about a `verify_brew` action which would bail out if tool is not installed and/or version mismatched (similar to [`verify_gem!` action](https://github.com/fastlane/fastlane/blob/7908e2af585ce859312972bc2bd9e361f4229b86/fastlane/lib/fastlane/helper/gem_helper.rb#L5) ).

I've read that you don't accept new actions anymore, even if imo this could be of general interest. So the alternative I guess is to make it a plugin.

Is it possible to write a plugin that depends on another plugin?

**Comment by PetrosIchor** [comment]
You should check out the badge plugin.  They just updated to include a brew dependency and have messaging for errors in fastlane when it's not installed.  No extra plugin required.  

As a side note, any package can be found outside of brew. Especially in CI environments you can't assume brew is available. If it were me, I'd follow the route Badge took with brew messaging.  Ops folks who know how to manage environments will see that message and know they need to add that dependency to their stack.

What type of plug are you working on?  Happy to see new flavors coming to fastlane!

**Comment by netbe** [comment]
@PetrosIchor are you talking about https://github.com/HazAT/fastlane-plugin-badge ? ~~I see only that they do `verify_gem!`~~. Got what you meant on the original gem.

I am working on making [rome](https://github.com/blender/rome) (An S3 cache tool for Carthage) available for fastlane.

**Comment by netbe** [comment]
Closing this issue, fyi the plugin is available :) : https://github.com/netbe/fastlane-plugin-rome

**Comment by KrauseFx** [comment]
That's awesome @netbe, thanks for sharing
