### ISSUE TITLE
Pass lane options to before_all, after_all and error blocks

### ISSUE THREAD

**Issue by phatblat** [fastlane/fastlane#864]
This would enable conditional actions inside these blocks such as:

- suppressing notifications when a `debug:true`
- only posting a release announcement when `submit:true`

Below is an example of how I see this in use.

```ruby
desc "Common setup for all lanes"
before_all do |lane, options|
  if options[:debug]
    puts "debug:true"
  else
    hipchat(message: "Starting #{lane_context[SharedValues::LANE_NAME]} lane")
  end
end

desc "Called on success"
after_all do |lane, options|
  if options[:debug]
    puts "debug:true"
  else
    hipchat(message: "#{lane_context[SharedValues::LANE_NAME]} lane completed successfully")
  end
end

desc "Called on error"
error do |lane, exception, options|
  if options[:submit]
    hipchat(message: "This message is only sent out when submit:true")
  end
end
```

If there are other ways to accomplish this same thing, then perhaps this isn't necessary. My main interest is in suppressing the notifications while I'm working on the build. The target channel gets pretty chatty with success and fail messages when I'm tweaking the build.

**Comment by spekke** [comment]
:+1:

**Comment by jcampbell05** [comment]
I love idea but I was wondering how does this fit in with `lane_context` could the options not be in that ?

**Comment by kevin-hirsch** [comment]
Would be great to have that! +1

**Comment by KrauseFx** [comment]
Very good idea, I'll see what I can do :wink:

**Comment by KrauseFx** [comment]
@phatblat I just pushed https://github.com/fastlane/fastlane/pull/1008, waiting for review now before it's available in the next release :+1:
