### ISSUE TITLE
Recent iTC Changes: Submit to non-existent train

### ISSUE THREAD

**Issue by suculent** [fastlane/fastlane#8645]
I have just experienced really (happily) unexpected behaviour while submitting app to iTC using XCode. It might help understanding recent changes in behaviour of Spaceship.

What just happened is that I've uploaded version 1.6 of app that had no such version train defined on the iTC website. 

Then I've created respective version train and the app seems to be processing on iTC under that version.

The build has been processed with the Export compliance approved through the plist. Operation resulted with successful TestFlight submission.

This would mean, that previous behaviour:
- where iTC rejected apps submitted by API while respective version train was not created

changed to somewhat that iTC does not reject those versions anymore. It's a topic to understand and explain, what does happen when API submitted version is 1.6.1 where the latter train defined will be 1.6.
- also whether this matters at all anyway

**Comment by suculent** [comment]
#!/bin/bash

# sorry for my language, but for this issue, dear loved bot:
fastlane env | /my/ass &2> /dev/null

**Comment by KrauseFx** [comment]
@suculent Why do you treat our bot to badly? He's just asking for some extra information we need to look into this issue

**Comment by suculent** [comment]
Dear @fastlane-bot, you can close this issue already as many things have been fixed in the past. And this ticket was just for your information, anyway. Maybe I haven't tagged it properly.

Give my bests to @KrauseFx  for keeping up the good work.

**Comment by KrauseFx** [comment]
❤️
