### ISSUE TITLE
Multiple simulators on Jenkins Instance when running two simultaneous jobs

### ISSUE THREAD

**Issue by beloso** [fastlane/fastlane#8646]
I am using Fastlane on a Jenkins set up with one OSX slave.

I have various jobs that I want to run simultaneously. However when two jobs are running that require use of the simulator to run UnitTests (no UI tests), one of the jobs fails. I believe this is because both jobs can't use the simulator at the same time.

Has anyone managed to overcome this limitation (using Fastlane)?

I heard of [FBSimulatorControl](https://github.com/facebook/FBSimulatorControl), but I don't think that tool is integrated in Fastlane, and I am not sure it should be. But what are your thoughts on this?

(I am sorry if fastlane's repo is not the best place for this question)

**Comment by mgrebenets** [comment]
Hi @beloso 
`fastlane` doesn't have a feature like this one.
Running multiple simulators in parallel is not something that's possible out-of-the-box.
Apple has done a lot of work with regards to managing simulators, but no progress in regards to having multiple instances running in parallel.

I heard about `FBSimulatorControl` just few months ago, but haven't had a chance to try it out.
They don't even make it easy to install (no Homebrew formula or Ruby gem).

I guess a Fastlane plugin is the way to go.
But someone would have to create a plugin for that.

**Comment by beloso** [comment]
There is a brew formula for `fbsimctl` 

https://github.com/facebook/FBSimulatorControl/blob/master/fbsimctl/README.md

I am wondering this because right now we have a mac pro that can only process one iOS Job at a time due to this limitation, which is kind of a waste :/

When I have some time on my hands I'll take a deeper look at `fbsimctl`. I just had to ask if anyone was going though this, and if there are known workarounds.
