### ISSUE TITLE
Fastlane with multiple targets setup

### ISSUE THREAD

**Issue by AndriyGo** [fastlane/fastlane#8647]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello everyone,

I might sound very nooby here, but I've been trying to understand how to properly setup fast lane with multiple targets and I still failed to do so, which is why I would like to ask for some more guidelines. I believe some other users will find it useful as well!

Basically, I have .xcodeproj which contains multiple targets. I have researched a lot of documentation on whether to use targets vs several projects and I am confident that in my case targets is the best solution.

I have never used fastlane before, but I want to set it up now so that I can easily deliver all of the updates to the App Store with a click of one button. I would also like to use snapshot to capture new screenshots whenever they need to be updated.

Ideally, I would like to have the following structure in my fastlane folder:

```
fastlane/
    app1/
        ... relevant subfolders for the app
    app2/
        ... relevant subfolders for the app
```

As the apps are already in the store, I would like to download all the existing metadata into the app specific folders. So far I only managed to download the metadata for my first target into the fastlane folder, but such solution is clearly not ideal.

I read a lot about .env files and also checked the sunApps example, but I am still puzzled as to how I can make it all work for my case. The thing I do not understand with the sunApps is the following comment:

> The Appfile contains the same Apple ID for every app, but a dynamic bundle identifier based on the current directory

This sounds like exactly what I need. However, I do not understand how I can change the current directory? My ideal solution would be to create a lane which, when executed, would build all relevant targets and would upload them to the App Store. I think that I only need one tiny example of how to do something with multiple targets and I will be able to sort out the rest!

If anyone could assist me it would be really great and I think helpful for many other users!

Thanks in advance!

**Comment by AndriyGo** [comment]
I have managed to get it working in the end. Quite a few trial and errors though :) Once I set up everything properly, I will make a note in my blog to describe what I did in case it may be helpful for others

**Comment by mgrebenets** [comment]
@AndriyGo 

How different are the targets/schemes in your case?

For use we just get list of all shared schemes with Ruby code like this:

```
# Get filtered list of Xcode project schemes
def schemes(project_path)
  # List /scchareddata/xcschemes and map to scheme base names
  Dir["#{project_path}/xcshareddata/xcschemes/**/*.xcscheme"].map { |f| File.basename(f, ".xcscheme") }
end
```

You could use `xcodebuild -list` as well, but browsing schemes is somewhat easier to parse and is actually faster than `xcodebuild` command.

Once we get the schemes we just loop through them, filter out the ones we don't want to build, etc - it's all custom Ruby script inside a custom lane.

There are so many ways to do this anyways.
