### ISSUE TITLE
Is it possible to retry failing UI automation tests using scan?

### ISSUE THREAD

**Issue by lucianomarisi** [fastlane/fastlane#8648]
I have seen that the `snapshot` has a `number_of_retries` argument since UI automation tests in Xcode are notoriously unreliable. 

I've looked into the `scan` docs but have not found such an option. Is it possible to re-run failing unit tests using scan. Currently my UI automation suite is composed of around 150ish tests and it's extremely rare that they would all pass in CI meaning that I cannot rely on them for picking up regressions.

**Comment by zaidkazi** [comment]
+1 really need this

**Comment by Utsira** [comment]
+1 excellent idea

**Comment by hactar** [comment]
I'd also find this very useful, UI Tests are still unreliable, so it would be great if the **number_of_retries** snapshot feature could be ported to scan too. I checked to see if it might be in already and only missing in the documentation, but unfortunately, it is not.

> [19:57:45]: Could not find option 'number_of_retries' in the list of available options: workspace, project, device, toolchain, devices, scheme, clean, code_coverage, address_sanitizer, thread_sanitizer, skip_build, output_directory, output_style, output_types, buildlog_path, include_simulator_logs, formatter, test_without_building, build_for_testing, xctestrun, derived_data_path, result_bundle, sdk, open_report, configuration, destination, xcargs, xcconfig, only_testing, skip_testing, slack_url, slack_channel, slack_message, skip_slack, slack_only_on_failure, use_clang_report_name, custom_report_file_name, fail_build

**Comment by hactar** [comment]
I just found this fastlane plug in that appears to do what we'd like it to: https://github.com/lyndsey-ferguson/fastlane_plugins/tree/master/fastlane-plugin-setup_fragile_tests_for_rescan

**Comment by Utsira** [comment]
@hactar I've used that plugin on a project, it's a good workaround, although it works by modifying the schema in the Xcode project file to skip passing tests. Now in Xcode 8 there is the `--only-testing` argument, which in theory would be a cleaner way of rerunning failing tests. A `number_of_retries` option in fastlane scan as proposed here would be even more convenient though.

**Comment by lyndsey-ferguson** [comment]
I'm the author of the `setup_fragile_tests_for_rescan` plugin and as we're moving towards using 'bluepill', our code is no longer using that and using `scans` `:only_testing` option with a list of the failed tests retrieved from the report.xml file. This is custom code in our private repo.

I am considering creating a plugin that you can use to simply get the failed and passing tests in the format that is acceptable to `:only_testing`. Give me a thumbs-up if you're interested in such a plug-in.
