### ISSUE TITLE
command fastlane not found after `brew cask install fastlane`

### ISSUE THREAD

**Issue by Nick-The-Uncharted** [fastlane/fastlane#8653]
Nicks-mac:~ administrasion$ brew cask install fastlane
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/bundle-1.7.zip
Already downloaded: /Users/administrasion/Library/Caches/Homebrew/Cask/fastlane--1.7.zip
==> Verifying checksum for Cask fastlane
==> Running installer script /usr/local/Caskroom/fastlane/1.7/install
==>
==> Installing fastlane to /Users/administrasion/.fastlane/bin... this might take a few seconds
==>
==>
==> Successfully copied fastlane to /Users/administrasion/.fastlane/bin
==>
==>
==> sed: /Users/administrasion/.fastlane/bin/bundle/bin/bundle-env: No such file or directory
==> /usr/local/Caskroom/fastlane/1.7/install: line 77: /Users/administrasion/.fastlane/bin/fastlane: No such file or
==> Detected fastlane is already in your path 🚀
==>
🍺  fastlane was successfully installed!
Nicks-mac:~ administrasion$ fastlane
-bash: fastlane: command not found
Nicks-mac:~ administrasion$ ls ~/.fastlane/bin
fastlane_lib

**Comment by Nick-The-Uncharted** [comment]
solved it, should
run `export PATH="$HOME/.fastlane/bin/fastlane_lib:$PATH"`
instead of `export PATH="$HOME/.fastlane/bin:$PATH"`
instruction during installing is wrong.

**Comment by jhon3rick** [comment]
solved, it install for rubi gem command 
terminal
sudo gem install fastlane -NV
