### ISSUE TITLE
Frameit always prints title/keyword in black even if another color is specified

### ISSUE THREAD

**Issue by AndriyGo** [fastlane/fastlane#8654]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Frameit draws title and keyword in black even though I specified another colours for them. Here is my Framefile:

```
{
  "default": {
    "keyword": {
    	"font": "../Fonts/SFCompactText-Heavy.otf",
    	"color": "#76a43b"
    },
    "title": {
    	"font": "../Fonts/SFCompactText-Regular.otf",
        "color": "#ffffff"
        },
    "background": "./background.jpg",
    "padding": 50,
    "stack_title" : true
  },
      "data": [
        {"filter":"Practice"},
        {"filter":"Mock"},
        {"filter":"PersonalTrainer"},
        {"filter":"Flag"}
      ]
}
```

Everything works well except for the colours. Could you please assist me?

I would also like to note that when I run frameit i get the following messages in the terminal:

> [17:52:58]: Framing screenshot './screenshots/motoTest/en-GB/iPhone7-Practice-d41d8cd98f00b204e9800998ecf8427e.png'
gm composite: profile matches sRGB but writing iCCP instead (/var/folders/19/7_vlfd_122553vwlfsgwvvyh0000gn/T/mini_magick20170326-43271-kzqsz2.png).
gm composite: iCCP: known incorrect sRGB profile (/var/folders/19/7_vlfd_122553vwlfsgwvvyh0000gn/T/mini_magick20170326-43271-kzqsz2.png).
gm identify: iCCP: known incorrect sRGB profile (/var/folders/19/7_vlfd_122553vwlfsgwvvyh0000gn/T/mini_magick20170326-43271-wbze33.png).
gm composite: iCCP: known incorrect sRGB profile (/var/folders/19/7_vlfd_122553vwlfsgwvvyh0000gn/T/mini_magick20170326-43271-wbze33.png).
gm convert: iCCP: known incorrect sRGB profile (/var/folders/19/7_vlfd_122553vwlfsgwvvyh0000gn/T/mini_magick20170326-43271-8hnlgq.png).

### Update 1

I have now tried all possible alterations I could come up with:

1) Putting framefile in different locations
2) Specifying other fonts
3) Running frameit from the lane instead of directly from the terminal

None of these helped to resolve my issue.

### Update 2

For some strange reason even MindNote example doesn't work for me. The result is the same - all screenshots are black. So, I guess it is definitely not due to some mistake in my framefile... 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "2ca95d1e-f7d9-4808-bd38-eb094ca74c1b"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :screenshots do
  SCHEMES = ENV["SCHEMES"].split(",")
  SCHEMES.each do |scheme_name|
	ENV["SCHEME"] = scheme_name
  	snapshot
	frameit
	slack ({
		slack_url: "OUR_URL",
		success:true,
		message: "Screenshots created for #{ENV["SCHEME"]}"
  	})
  end
   
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
apple_id "blablabla@gmail.com"
app_identifier "#{ENV["BUNDLE_ID_PREFIX"]}#{ENV["SCHEME"]}"```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-03-26**
</details>

**Comment by AndriyGo** [comment]
I cannot reproduce this issue with the latest fastlane (2.25.0)

**Comment by AnarH93** [comment]
i reproduce this today on 2.26.1 version

**Comment by AndriyGo** [comment]
Am reopening the issue as @AnarH93 is still experiencing it. I myself cannot reproduce it anymore
