### ISSUE TITLE
[snapshot] any examples for making screenshot with react native

### ISSUE THREAD

**Issue by jjhesk** [fastlane/fastlane#8655]
I was the UITest is depreciated from the list now I have react native code base. Are there any tutorial for making screenshots with this?

**Comment by jjhesk** [comment]
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.19.3"
generated_fastfile_id "e54d3136-3d8d-40e8-b4b2-4e6a3e6fb582"
##app_identifer "com.zyntauri.igallerygo"
identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
apple_id = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
##testers = CredentialsManager::AppfileConfig.try_fetch_value(:testers)

default_platform :ios

platform :ios do
  desc "Run deploy of the app"
  lane :schot do |values|
     snapshot(erase_simulator: true)
  end
  #
  # Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
  #
  desc "Run deploy of the app"
  lane :deploy do |values|
        increment_build_number
        cert(username: 'david@heskeyo.com')
        sigh(username: 'david@heskeyo.com')

        clear_derived_data

        # Generate release notes from CHANGELOG

              gym(scheme: 'gl',
               workspace:'glwork.xcworkspace',
        output_directory: './build/gl.ipa',
           export_method: 'app-store')


      xcodebuild(archive: true,
                 archive_path: './build/gl.xcarchive',
                       scheme: 'gl',
                    workspace: 'glwork.xcworkspace')
      snapshot
      deliver
  end

  lane :crashlyticswork do

    groups = nil # You can define groups on the web and reference them here
    emails = ['erickwok501@yahoo.com.hk', 'jobhesk@gmail.com', 'xyzlai208@gmail.com', 'ting041005@hotmail.com']

    crashlytics(api_token: 'd9d75a6d41d566ec63b74b3776fb2bf4e0ef20cb',
             build_secret: '7c49822cd09fc9ef34bb3235e44a23ee2ad8536e72735c247b8e821c793e4ec5',
                   emails: emails,
                   groups: groups,
         crashlytics_path: './Crashlytics.framework',
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true,
                 ipa_path: 'build/Products/Release-iphoneos/gl.ipa') # Should this distribution notify your testers via email?
  end


  lane :beta do |values|

    increment_build_number

    cert(username: 'david@heskeyo.com')

    sigh(username: 'david@heskeyo.com')
    # Fabric generated this lane for deployment to Crashlytics Beta
    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'gl', export_method: 'development')


    emails = ['erickwok501@yahoo.com.hk', 'jobhesk@gmail.com', 'xyzlai208@gmail.com', 'ting041005@hotmail.com']
    ##groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: 'd9d75a6d41d566ec63b74b3776fb2bf4e0ef20cb',
             build_secret: '7c49822cd09fc9ef34bb3235e44a23ee2ad8536e72735c247b8e821c793e4ec5',
                   emails: emails,
                   groups: nil,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?


    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )

    # Generate release notes from CHANGELOG
    release_notes = latest_version.split("\n")[1..-1].join("\n")


  end


  desc "Run tests"
  lane :build_test do
    output_directory = 'build/reports'

    scan(
      workspace: ENV['XCWORKSPACE_NAME'],
      scheme: ENV['SCHEME'],
      output_directory: output_directory,
      skip_slack: is_ci?,
      clean: true
    )

    sh "mv ../#{output_directory}/*.junit ../#{output_directory}/report.xml"
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # Uncomment match and add git_url
    match(
      type: "appstore",
      # Use your own repository!
      git_url: "https://gitlab.com/sugesk/ios-certs"
    )
    deliver(force: true)

  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.zyntauri.igallerygo" # The bundle identifier of your app
apple_id "david@heskeyo.com"  # Your Apple email address
apple_dev_portal_id "david@heskeyo.com"  # Apple Developer Account
itunes_connect_id "david@heskeyo.com"     # iTunes Connect Account
team_id "Q2CBPJ58CA" # Developer Portal Team ID
#fabric_api_key "d9d75a6d41d566ec63b74b3776fb2bf4e0ef20cb"
#fabric_secret "7c49822cd09fc9ef34bb3235e44a23ee2ad8536e72735c247b8e821c793e4ec5"
#/bin/sh
#${SRCROOT}/Fabric.framework/run d9d75a6d41d566ec63b74b3776fb2bf4e0ef20cb 7c49822cd09fc9ef34bb3235e44a23ee2ad8536e72735c247b8e821c793e4ec5
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-03-27**
</details>
```

**Comment by PetrosIchor** [comment]
That's not related to fastlane. You should check out reacts UI testing and screenshot generation

**Comment by jjhesk** [comment]
@PetrosIchor does it have any support directly to [Jest](https://facebook.github.io/jest/docs/snapshot-testing.html)

**Comment by wootwoot1234** [comment]
@jjhesk, did you ever figure this out?  I would like to generate screenshots from my apps make in react native.  Thanks!

**Comment by aj0strow** [comment]
@jjhesk @wootwoot1234 any tips?

**Comment by wootwoot1234** [comment]
@aj0strow I'm doing it manually right now.  Let me know if you find a better option.

**Comment by aj0strow** [comment]
I couldn't get it to compile when creating a new scheme, but if you run it in the same scheme, it seems to work. 

---

Created a new project.

```
$ react-native -v
react-native-cli: 2.0.1

$ react-native init NativeSnapshots

$ cd NativeSnapshots

$ react-native run-ios
```

Test it works, launch welcome screen.

```
$ cd ios

$ fastlane snapshot init
```

<details><summary>fastlane output</summary>

```
[14:37:56]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
✅  Successfully created SnapshotHelper.swift './SnapshotHelper.swift'
✅  Successfully created new Snapfile at './Snapfile'
-------------------------------------------------------
Open your Xcode project and make sure to do the following:
1) Add a new UI Test target to your project
2) Add the ./fastlane/SnapshotHelper.swift to your UI Test target
   You can move the file anywhere you want
3) Call `setupSnapshot(app)` when launching your app

  let app = XCUIApplication()
  setupSnapshot(app)
  app.launch()

4) Add `snapshot("0Launch")` to wherever you want to create the screenshots

More information on GitHub: https://github.com/fastlane/fastlane/tree/master/snapshot
```

</details>

#### Step 1: Add a new UI Test target to your project

Xcode Version 8.3.3 > Open `NativeSnapshots.xcodeproj`

```
File > New > Target > iOS UI Testing Bundle
```

![ui-target copy](https://user-images.githubusercontent.com/1374327/28841530-8de58c6e-76c8-11e7-99c5-2fb3b15cfcdd.jpg)

#### Step 2: Add the ./fastlane/SnapshotHelper.swift to your UI Test target

```
Highlight NativeSnapshotsUITests
File > Add Files to NativeSnapshots
Select SnapshotHelper.swift, Enter
```

#### Step 3: Call `setupSnapshot(app)` when launching your app

Open `NativeSnapshotsUITests/NativeSnapshotsUITests.swift` in Xcode.

Replace:

```
        XCUIApplication().launch()
```

With:

```
        let app = XCUIApplication()
        setupSnapshot(app)
        app.launch()
```

#### Step 4: Add `snapshot("0Launch")` to wherever you want to create the screenshots

Add snapshot call in `testExample()` in UI Tests. 

```
    func testExample() {
        snapshot("0Launch")
    }
```

Edit the `Snapfile` to avoid a huge matrix.

```
devices([
  "iPhone 6"
])

languages([
  "en-US"
])

scheme "NativeSnapshots"
```

It should be ready to go. 

```
$ cd ios && fastlane snapshot
```

**Comment by joncursi** [comment]
React native `View`s support a `testID` prop. You can give a view a `testID` and then in your UI Test script, tell the simulator to tap on that view by ID.

```jsx
<View
  testID="something"
>
  {...}
<View>
```

```swift
func testExample() {
    let app = XCUIApplication()

    ...

    app.otherElements["something"].tap()

    ...

    snapshot("0Something")
  }
```

**Comment by wootwoot1234** [comment]
@aj0strow Thanks!  Works like a charm!

@joncursi Thanks!  For some reason, it doesn't work if I add a `testID` to a component that is generated in the `<ListView />`'s `renderRow` method.  It works fine on components outside of the `<ListView />`.  Any idea why?
