### ISSUE TITLE
"include_symbols: false" has no effect

### ISSUE THREAD

**Issue by AntonBelousov** [fastlane/fastlane#8656]
I have Fastfile like this

```
fastlane_version "2.23.0"

generated_fastfile_id "4f808bfa-3660-4ef1-8577-2324ec613b9c"

default_platform :ios

lane  :adhoc do

    # blabla

    gym(
        # blabla
        include_symbols:  false,
        # blabla
    )

end
```

I use this command to build adhoc ipa
`fastlane adhoc`

It generates ipa and dSYM file as well.

**Comment by AntonBelousov** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.23.0"
generated_fastfile_id "4f808bfa-3660-4ef1-8577-2324ec613b9c"
default_platform :ios

lane  :adhoc do

    # build your iOS app
    gym(
        scheme:           "GymTest",
        clean:            true,
        output_directory: "~/Desktop/build",
        export_method:    "ad-hoc",
        include_symbols:  false
    )

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-03-26**
</details>

**Comment by KrauseFx** [comment]
The flag means it doesn't contain the symbols inside the `ipa` file. It will still generate the dSYM file locally. There is currently no way to disable that as far as I know, but you can use the [clean_build_artifacts](https://docs.fastlane.tools/actions/#clean_build_artifacts) action for after you finished uploading the binary file 👍

**Comment by PetrosIchor** [comment]
Try putting it in a string `include_symbols: 'false'`?  Every so often I find I need to string a Boolean parameter.

Though krausefx is most likely right.

**Comment by KrauseFx** [comment]
@PetrosIchor I'm pretty sure the boolean parameter shouldn't be passed as string

**Comment by mgrebenets** [comment]
@AntonBelousov 

`include_symbols` maps directly to `uploadSymbols` of `xcodebuild -exportArchive` command.
According to `xcodebuild -h` output:

```
	uploadBitcode : Bool

		For App Store exports, should the package include bitcode? Defaults to YES.

	uploadSymbols : Bool

		For App Store exports, should the package include symbols? Defaults to YES.
```

The main thing here is **For App Store exports**, which makes me think this flag should have no effect for "ad-hoc" exports.

Does it generate `dSYM` files _outside_ the `ipa`?
In that case it is normal. The `dSYM` option is controlled `DEBUG_INFORMATION_FORMAT` build setting, it's not part of export command:

![image](https://cloud.githubusercontent.com/assets/350654/24354834/29d09648-133f-11e7-83dc-22c02c487f84.png)

`include_symbols` tells `xcodebuild` whether debug symbols should or should not be included inside App Store ipa.

Why would you want to get rid of `dSYM`s though?
Is it the issue with free space on the build server?
You may need those when you get crashes in ad-hoc build and you'd want to symbolicate the crashes.

**Comment by AntonBelousov** [comment]
> Why would you want to get rid of dSYMs though?
> Is it the issue with free space on the build server?

Actually I'm ok with dSYM files but it was not obvious for me - how this parameter worked
