### ISSUE TITLE
 No value found for 'crashlytics_path'

### ISSUE THREAD

**Issue by thim81** [fastlane/fastlane#8658]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

DEBUG [2017-03-27 01:23:46.81]: Checking if there are any plugins that should be loaded...
INFO [2017-03-27 01:23:46.84]: -------------------------------------------------
INFO [2017-03-27 01:23:46.84]: --- Step: Verifying required fastlane version ---
INFO [2017-03-27 01:23:46.84]: -------------------------------------------------
INFO [2017-03-27 01:23:46.84]: Your fastlane version 2.23.0 matches the minimum requirement of 2.23.0  ✅
INFO [2017-03-27 01:23:46.85]: ------------------------------
INFO [2017-03-27 01:23:46.85]: --- Step: default_platform ---
INFO [2017-03-27 01:23:46.85]: ------------------------------
INFO [2017-03-27 01:23:46.85]: Driving the lane 'ios beta' 🚀
INFO [2017-03-27 01:23:46.86]: ------------------
INFO [2017-03-27 01:23:46.86]: --- Step: sigh ---
INFO [2017-03-27 01:23:46.86]: ------------------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------
Successfully loaded Appfile at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/Appfile'
- app_identifier: 'com.parcify.crew'
- team_id: '[[DEV_PORTAL_TEAM_ID]]'
-------

+-------------------------------------+------------------------+
|                   Summary for sigh 2.23.0                    |
+-------------------------------------+------------------------+
| adhoc                               | true                   |
| force                               | true                   |
| app_identifier                      | com.parcify.crew       |
| development                         | false                  |
| skip_install                        | false                  |
| team_id                             | [[DEV_PORTAL_TEAM_ID]] |
| ignore_profiles_with_different_name | false                  |
| skip_fetch_profiles                 | false                  |
| skip_certificate_verification       | false                  |
| platform                            | ios                    |
+-------------------------------------+------------------------+

WARN [2017-03-27 01:23:46.89]: Lane Context:
INFO [2017-03-27 01:23:46.89]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
ERROR [2017-03-27 01:23:46.89]: No value found for 'username'
INFO [2017-03-27 01:23:46.90]: Successfully generated documentation at path '/Volumes/Extra HDD/Parcify/app/crew-app/platforms/ios/Parcify Crew.xcodeproj/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | sigh                                | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-03-27 01:23:46.91]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.23.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    # gym(scheme: "com.parcify.crew") # Build your app - more options available
    # pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)


      app_name = "Parcify Crew"

     # Get changelog
      changelog = File.read("../../../../changelog_fastlane.txt")

      # Sign with AdHoc provision profile
      sigh(
        adhoc: true,
        force: true,
        app_identifier: "com.parcify.crew",
      )

      # build your iOS app
      gym(
        scheme: app_name,
        # project: xcodeproj
      )

      # upload to Beta by Crashlytics
      crashlytics(
        api_token: "xxxx",
        build_secret: "xx",
        notes: changelog
      )
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "com.parcify.crew") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.parcify.crew" # The bundle identifier of your app
apple_id "" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.2        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-27**
</details>

**Comment by KrauseFx** [comment]
How did you setup Crashlytics? Do you use CocoaPods?

**Comment by thim81** [comment]
Hi Felix,

It's for a Ionic App, so we were using https://github.com/sarriaroman/FabricPlugin

I'm going to contact the plugin maintainer as well.
The strange thing is that in the previous versions of FastLane it did not complain about the path but after the update it's stopping the beta lane due to the missing path.

That's why I'm reporting it here as well
