### ISSUE TITLE
Fastlane Supply: Distribute the build to testers for Alpha/Beta Track

### ISSUE THREAD

**Issue by arokiagetz** [fastlane/fastlane#8663]
Hi, Would like to setup Fastlane for Android and wanted to submit the apps for Beta/Alpha Track. Now my requirement is, once uploaded, I need to distribute the version for the list of testers who are already configured. Is there anything to distribute to Android Testers please, like the way for iOS TestFlight. I have nearly 30+ apps to submit for testing, looking for automated distribution to testers. Please let me know if this already available in your documentation. Thanks

**Comment by arokiagetz** [comment]
Here is the env details:

Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.11.6                                       |
| Ruby                        | 2.0.0                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.10.1 (Apple Git-78)             |
| Installation Source         | ~/.rvm/gems/ruby-2.0.0-p648/bin/fastlane      |
| Host                        | Mac OS X 10.11.6 (15G1217)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.0.0-p648/lib             |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                     |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode_8.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                         |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.*.*" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.3       |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| i18n                      | 0.7.0        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| json                      | 1.8.3        |
| excon                     | 0.54.0       |
| plist                     | 3.2.0        |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| unicode-display_width     | 1.1.1        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2017-03-27**
</details>

**Comment by mfurtak** [comment]
Hi @arokiagetz 👋 

It sounds like you're getting started with Android beta testing, so let me suggest a couple resources:

To better understand things from the perspective of Google Play, check out: https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

On the _fastlane_ side, you'll want to make sure you've done the steps for [setting up _supply_](https://docs.fastlane.tools/getting-started/android/setup/#setting-up-supply). After that, you should be ready to get started with [beta deployment](https://docs.fastlane.tools/getting-started/android/beta-deployment/) with _fastlane_ 👍 

I hope that helps you get things going! 🚀

**Comment by arokiagetz** [comment]
thanks @mfurtak, will setup supply and get back
