### ISSUE TITLE
GYM Codesigning issues with complicated setup

### ISSUE THREAD

**Issue by StupidDutchName** [fastlane/fastlane#8669]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to build and codesign my app for delivery to HockeyApp. My app codesigns fine when I select Archive in Xcode and then export the app as ipa. We do manual certificates / provisioning because my company has a strict access policy to the developer portal.

When I run `fastlane dev` everything builds fine, but when fastlane tries to codesign my archive it fails with the error: `No matching provisioning profiles found`, `None of the valid provisioning profiles allowed the specified entitlements: application-identifier, beta-reports-active, keychain-access-groups.`. Again, all works fine in Xcode doing things manually.

A "brief" explanation of our codesigning setup. I have 4 scheme's, `DEV`, `TST`, `ACC` and `PRD`.
For each scheme there is a release build configuration, in this case `InHouseDist-DEV`. Each configuration specifies a number of environment specific `Info.plist` values, for example:

* `CUSTOM_BUNDLE_ID`, so we can install the `DEV`/`TST`/`ACC` apps simultaneously on the same device (e.g. 'nl.mycompany.myapp.dev`)
* `API_URL`
* `BUNDLE_NAME_POSTFIX`, a small string we add behind the display name to be able to discern the different builds on the same device (e.g. '-DEV')

In the `Info.plist` we then use these values:

* `<key>CFBundleIdentifier</key><string>$(CUSTOM_BUNDLE_ID)</string>`
* `<key>apiUrl</key><string>$(API_URL)</string>`
* `<key>CFBundleDisplayName</key><string>MyApp$(BUNDLE_NAME_POSTFIX)</string>`

This seems to be expanded the way it's supposed to be if I check intermediate the intermediate build results in `/Users/MyUser/Library/Developer/Xcode/Archives`. Which leads me to believe our "complicated" setup is not the source of the problem.

For the hockeyapp builds we have a wildcard enterprise distribution certificate `nl.mycompany.myapp.*`.

##### App File
```
app_identifier ENV["APP_IDENTIFIER"]
apple_id "stupiddutchname@mycompany.com" # Your Apple email address
team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID
```

##### Fast File
```
fastlane_version "2.23.0"
default_platform :ios

platform :ios do
  desc "Submit a new Hockeyapp DEV build"
  lane :dev do
    ENV["APP_IDENTIFIER"] = "nl.mycompany.myapp.dev"
 
    # Build your app - more options available
    gym(scheme: "MyApp-DEV")
  end
end
```

##### Complete output when running fastlane, including the stack trace and command used
`$ fastlane dev`
```
[16:59:18]: ▸ Archive Succeeded
[16:59:18]: Generated plist file with the following values:
[16:59:18]: ▸ -----------------------------------------
[16:59:18]: ▸ {
[16:59:18]: ▸   "method": "app-store",
[16:59:18]: ▸   "uploadSymbols": true,
[16:59:18]: ▸   "uploadBitcode": false
[16:59:18]: ▸ }
[16:59:18]: ▸ -----------------------------------------
[16:59:18]: $ /usr/bin/xcrun /Users/MyUser/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/p8/z57kqcp5153425d74gq3pkgm0000gp/T/gym_config20170327-29830-x8omy3.plist' -archivePath /Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp\ 2017-03-27\ 16.56.53.xcarchive -exportPath '/var/folders/p8/z57kqcp5153425d74gq3pkgm0000gp/T/gym_output20170327-29830-ho9hy6' 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/p8/z57kqcp5153425d74gq3pkgm0000gp/T/gym_config20170327-29830-x8omy3.plist -archivePath '/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive' -exportPath /var/folders/p8/z57kqcp5153425d74gq3pkgm0000gp/T/gym_output20170327-29830-ho9hy6
2017-03-27 16:59:19.212 xcodebuild[32706:4599729] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/p8/z57kqcp5153425d74gq3pkgm0000gp/T/MyApp-DEV_2017-03-27_16-59-19.211.xcdistributionlogs'.
1.2.840.113635.100.1.61
2017-03-27 16:59:19.555 xcodebuild[32706:4599729] [MT] IDEDistribution: -[IDEDistributionProvisioning _itemToSigningInfoMap:]: Can't find any applicable signing identities for items: (
"<IDEDistributionItem: 0x7ff3562b93a0 'nl.mycompany.myapp.dev' '<DVTFilePath:0x7ff3561a7110:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app'>'>",
"<IDEDistributionItem: 0x7ff358bebe90 'org.cocoapods.OwnCustomLib' '<DVTFilePath:0x7ff358a31990:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/OwnCustomLib.framework'>'>",
"<IDEDistributionItem: 0x7ff358bf0780 'org.cocoapods.Freddy' '<DVTFilePath:0x7ff358a3cf30:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/Freddy.framework'>'>",
"<IDEDistributionItem: 0x7ff358bd5700 'org.cocoapods.GHODictionary' '<DVTFilePath:0x7ff358a424b0:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/GHODictionary.framework'>'>",
"<IDEDistributionItem: 0x7ff358be3110 'org.cocoapods.Haneke' '<DVTFilePath:0x7ff358a47fe0:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/Haneke.framework'>'>",
"<IDEDistributionItem: 0x7ff358bda3c0 'org.cocoapods.MPMessagePack' '<DVTFilePath:0x7ff358a5cd60:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/MPMessagePack.framework'>'>",
"<IDEDistributionItem: 0x7ff358be1ef0 'org.cocoapods.RNCryptor' '<DVTFilePath:0x7ff358a63190:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/RNCryptor.framework'>'>",
"<IDEDistributionItem: 0x7ff358bbfcd0 'org.cocoapods.SwiftyRSA' '<DVTFilePath:0x7ff358a68bd0:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/SwiftyRSA.framework'>'>",
"<IDEDistributionItem: 0x7ff358a91b30 'org.cocoapods.XCGLogger' '<DVTFilePath:0x7ff358a6e4f0:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/XCGLogger.framework'>'>",
"<IDEDistributionItem: 0x7ff358ba79c0 'org.cocoapods.MyApiKit' '<DVTFilePath:0x7ff358a74040:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/MyApiKit.framework'>'>",
"<IDEDistributionItem: 0x7ff358bb7c20 'com.apple.dt.runtime.swiftAVFoundation' '<DVTFilePath:0x7ff358a4d880:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftAVFoundation.dylib'>'>",
"<IDEDistributionItem: 0x7ff358be1570 'com.apple.dt.runtime.swiftCore' '<DVTFilePath:0x7ff358a4f030:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftCore.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bc96e0 'com.apple.dt.runtime.swiftCoreAudio' '<DVTFilePath:0x7ff358a50270:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftCoreAudio.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bbe380 'com.apple.dt.runtime.swiftCoreGraphics' '<DVTFilePath:0x7ff358a4c070:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftCoreGraphics.dylib'>'>",
"<IDEDistributionItem: 0x7ff356766710 'com.apple.dt.runtime.swiftCoreImage' '<DVTFilePath:0x7ff358a52d50:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftCoreImage.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bed4e0 'com.apple.dt.runtime.swiftCoreMedia' '<DVTFilePath:0x7ff358a54080:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftCoreMedia.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bd2150 'com.apple.dt.runtime.swiftDarwin' '<DVTFilePath:0x7ff358a54e50:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftDarwin.dylib'>'>",
"<IDEDistributionItem: 0x7ff358a944e0 'com.apple.dt.runtime.swiftDispatch' '<DVTFilePath:0x7ff358a56b10:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftDispatch.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bdbe60 'com.apple.dt.runtime.swiftFoundation' '<DVTFilePath:0x7ff358a519e0:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftFoundation.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bc3240 'com.apple.dt.runtime.swiftObjectiveC' '<DVTFilePath:0x7ff358a59460:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftObjectiveC.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bb7460 'com.apple.dt.runtime.swiftQuartzCore' '<DVTFilePath:0x7ff358a5aaf0:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftQuartzCore.dylib'>'>",
"<IDEDistributionItem: 0x7ff358bceb00 'com.apple.dt.runtime.swiftUIKit' '<DVTFilePath:0x7ff358a5be60:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app/Frameworks/libswiftUIKit.dylib'>'>"
)
Errors={
"<DVTSigningCertificate: 0x7ff358bc4e40; name='iPhone Distribution: My Company B.V.', hash='85AD288B88901E9775B0F878077C6AA0FFFEED15', serialNumber='35AF333A113A26F3', certificateKind='1.2.840.113635.100.6.1.4, issueDate='2015-10-19 10:54:32 +0000''>" =     {
"<IDEDistributionItem: 0x7ff3562b93a0 'nl.mycompany.myapp.dev' '<DVTFilePath:0x7ff3561a7110:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=7 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=None of the valid provisioning profiles allowed the specified entitlements: application-identifier, beta-reports-active, keychain-access-groups., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7ff35675daa0; portalTeamID='R5AYLB8W95', usingTeamBasedSigning='NO', bundleIdentifier='nl.mycompany.myapp.dev', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"application-identifier\" = \"R5AYLB8W95.nl.mycompany.myapp.dev\";\n    \"beta-reports-active\" = 1;\n    \"keychain-access-groups\" =     (\n        \"R5AYLB8W95.nl.mycompany.myapp.dev\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
};
}
2017-03-27 16:59:19.556 xcodebuild[32706:4599729] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7ff3561c33f0>: Error Domain=IDEDistributionErrorDomain Code=3 "(null)" UserInfo={IDEDistributionErrorSigningIdentityToItemToUnderlyingErrorKey={
"<DVTSigningCertificate: 0x7ff358bc4e40; name='iPhone Distribution: My Company B.V.', hash='85AD288B88901E9775B0F878077C6AA0FFFEED15', serialNumber='35AF333A113A26F3', certificateKind='1.2.840.113635.100.6.1.4, issueDate='2015-10-19 10:54:32 +0000''>" =     {
"<IDEDistributionItem: 0x7ff3562b93a0 'nl.mycompany.myapp.dev' '<DVTFilePath:0x7ff3561a7110:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=7 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=None of the valid provisioning profiles allowed the specified entitlements: application-identifier, beta-reports-active, keychain-access-groups., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7ff35675daa0; portalTeamID='R5AYLB8W95', usingTeamBasedSigning='NO', bundleIdentifier='nl.mycompany.myapp.dev', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"application-identifier\" = \"R5AYLB8W95.nl.mycompany.myapp.dev\";\n    \"beta-reports-active\" = 1;\n    \"keychain-access-groups\" =     (\n        \"R5AYLB8W95.nl.mycompany.myapp.dev\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
};
}}
error: exportArchive: The operation couldn’t be completed. (IDEDistributionErrorDomain error 3.)

Error Domain=IDEDistributionErrorDomain Code=3 "(null)" UserInfo={IDEDistributionErrorSigningIdentityToItemToUnderlyingErrorKey={
"<DVTSigningCertificate: 0x7ff358bc4e40; name='iPhone Distribution: My Company B.V.', hash='85AD288B88901E9775B0F878077C6AA0FFFEED15', serialNumber='35AF333A113A26F3', certificateKind='1.2.840.113635.100.6.1.4, issueDate='2015-10-19 10:54:32 +0000''>" =     {
"<IDEDistributionItem: 0x7ff3562b93a0 'nl.mycompany.myapp.dev' '<DVTFilePath:0x7ff3561a7110:'/Users/MyUser/Library/Developer/Xcode/Archives/2017-03-27/MyApp 2017-03-27 16.56.53.xcarchive/Products/Applications/MyApp.app'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=7 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=None of the valid provisioning profiles allowed the specified entitlements: application-identifier, beta-reports-active, keychain-access-groups., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7ff35675daa0; portalTeamID='R5AYLB8W95', usingTeamBasedSigning='NO', bundleIdentifier='nl.mycompany.myapp.dev', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"application-identifier\" = \"R5AYLB8W95.nl.mycompany.myapp.dev\";\n    \"beta-reports-active\" = 1;\n    \"keychain-access-groups\" =     (\n        \"R5AYLB8W95.nl.mycompany.myapp.dev\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
};
}}
```
All identifiable information has been removed from this log, but I garuantee that all the bundle identifiers are correct.

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>
*generated on:* **2017-03-27**
</details>

**Comment by Lutzifer** [comment]
I am seeing similar errors in an enterprise project, probably related to the Xcode 8.3 update

**Comment by StupidDutchName** [comment]
Apparently this had to do with enterprise program signing. In the gym command you have to add: `export_method: "enterprise"`.
This will add something to the plist which is sent to the xcrun archive command and then it works for us!
