### ISSUE TITLE
Cannot find an installed Xcode 8.3, but Xcode 8.3 is installed

### ISSUE THREAD

**Issue by dlo** [fastlane/fastlane#8671]
🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

fastlane fails to run our action with `[!] Cannot find an installed Xcode satisfying '8.3'`, but Xcode 8.3 is installed, and it has been specified as the default Xcode with `xcode-select`.

```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
$ xcversion selected
Xcode 8.3
Build version 8E162
```

```
$ fastlane release
+------------------------+---------+--------------------+
|                     Used plugins                      |
+------------------------+---------+--------------------+
| Plugin                 | Version | Action             |
+------------------------+---------+--------------------+
| fastlane-plugin-sentry | 1.0.4   | sentry_upload_dsym |
+------------------------+---------+--------------------+

[18:30:10]: -------------------------------------------------
[18:30:10]: --- Step: Verifying required fastlane version ---
[18:30:10]: -------------------------------------------------
[18:30:10]: Your fastlane version 2.23.0 matches the minimum requirement of 2.23.0  ✅
[18:30:10]: -----------------------
[18:30:10]: --- Step: xcversion ---
[18:30:10]: -----------------------

[!] Cannot find an installed Xcode satisfying '8.3'
```

### Captured Output

Command Used: `release`
<details><summary>Output/Log</summary>

```

DEBUG [2017-03-27 18:29:31.48]: Checking if there are any plugins that should be loaded...
DEBUG [2017-03-27 18:29:31.63]: Loading 'fastlane-plugin-sentry' plugin
INFO [2017-03-27 18:29:31.71]: gem 'fastlane-plugin-sentry' is already installed
+------------------------+---------+--------------------+
|                     Used plugins                      |
+------------------------+---------+--------------------+
| Plugin                 | Version | Action             |
+------------------------+---------+--------------------+
| fastlane-plugin-sentry | 1.0.4   | sentry_upload_dsym |
+------------------------+---------+--------------------+

INFO [2017-03-27 18:29:31.78]: -------------------------------------------------
INFO [2017-03-27 18:29:31.78]: --- Step: Verifying required fastlane version ---
INFO [2017-03-27 18:29:31.78]: -------------------------------------------------
INFO [2017-03-27 18:29:31.78]: Your fastlane version 2.23.0 matches the minimum requirement of 2.23.0  ✅
INFO [2017-03-27 18:29:31.79]: -----------------------
INFO [2017-03-27 18:29:31.79]: --- Step: xcversion ---
INFO [2017-03-27 18:29:31.79]: -----------------------
INFO [2017-03-27 18:29:31.84]: gem 'xcode-install' is already installed
DEBUG [2017-03-27 18:29:32.22]: All plugins are up to date


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.2                          |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# vim: set ft=ruby:

fastlane_version "2.23.0"

# xcode_select "/Applications/Xcode.app"
xcversion(version: "8.3")

default_platform :ios

platform :ios do
  lane :submit_smart_price do
    build_number = latest_testflight_build_number(app_identifier: "com.callahan-roach.Smart-Price")
    deliver(build_number: build_number.to_s)
  end

  lane :submit_call_smart do
    build_number = latest_testflight_build_number(app_identifier: "com.callahan-roach.Call-Smart2")
    deliver(build_number: build_number.to_s)
  end

  lane :beta do
    gym
    deliver
  end

  lane :superuser do
    gym
    deliver
  end

  desc "Deploy Smart Price to the App Store"
  lane :smart_price_release do |options|
    ensure_git_status_clean
    increment_build_number(xcodeproj: "Call Smart.xcodeproj")

    gym

    ENV["SCHEME"] = "Smart Price"
    # snapshot
    if options[:submit_for_review]
      deliver(submit_for_review: true)
    else
      deliver
    end

    version_number = get_version_number(xcodeproj: "Call Smart.xcodeproj", target: "Smart Price")
    build_number = get_build_number(xcodeproj: "Call Smart.xcodeproj")
    commit_version_bump(message: "bump to #{build_number}", xcodeproj: "./Call Smart.xcodeproj")
    add_git_tag tag: "v#{version_number}+#{build_number}"
    push_to_git_remote
  end

  desc "Deploy Call Smart to the App Store"
  lane :release do
    ensure_git_status_clean
    increment_build_number(xcodeproj: "Call Smart.xcodeproj")

    gym

    ENV["SCHEME"] = "Call Smart"
    # snapshot
    deliver

    version_number = get_version_number(xcodeproj: "Call Smart.xcodeproj", target: "Call Smart")
    build_number = get_build_number(xcodeproj: "Call Smart.xcodeproj")
    commit_version_bump(message: "bump to #{build_number}", xcodeproj: "./Call Smart.xcodeproj")
    add_git_tag tag: "v#{version_number}+#{build_number}"
    push_to_git_remote
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# vim: set ft=ruby:

apple_id "dan+cr@lionheartsw.com"
team_id "SRH249X7P3"

for_platform :ios do
  for_lane :superuser do
    app_identifier "com.callahan-roach.Call-Smart2-Superuser"
  end

  for_lane :beta do
    app_identifier "com.callahan-roach.Call-Smart2-Beta"
  end

  for_lane :release do
    app_identifier "com.callahan-roach.Call-Smart2"
  end

  for_lane :smart_price_release do
    app_identifier "com.callahan-roach.Smart-Price"
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-sentry | 1.0.4   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.13.7       |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| excon                     | 0.55.0       |
| openssl                   | 2.0.2        |
| rubyzip                   | 1.2.1        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fastlane-plugin-sentry    | 1.0.4        |
| xcode-install             | 2.1.1        |
</details>

*generated on:* **2017-03-27**
</details>

**Comment by mfurtak** [comment]
Hi @dlo 👋 - thanks for the report!

I was able to reproduce this locally, and have filed https://github.com/KrauseFx/xcode-install/issues/203 to track the underlying issue.

**Comment by dlo** [comment]
Thanks!

**Comment by KrauseFx** [comment]
I was able to install Xcode 8.3 using _fastlane_ without issue, can you try again?

**Comment by dlo** [comment]
Can't reproduce anymore—appears to have just gone away on its own. ¯\_(ツ)_/¯

**Comment by janmisar** [comment]
Reindexing Spotlight worked for me. No idea why, but seems to be fixed.

**Comment by jondwillis** [comment]
http://osxdaily.com/2012/01/17/rebuild-spotlight-index/  Rebuilding worked for me too. I restarted macOS to try and fix this and noted that Xcode wouldn't show up in my spotlight.
