### ISSUE TITLE
No such file or directory @ rb_sysopen on Xcode 8.3 - Gym

### ISSUE THREAD

**Issue by Bunn** [fastlane/fastlane#8672]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
gym started to fail after Xcode (Version 8.3 (8E162)) installation

```
+------------------+----------+
|        Lane Context         |
+------------------+----------+
| DEFAULT_PLATFORM | ios      |
| PLATFORM_NAME    | ios      |
| LANE_NAME        | ios beta |
+------------------+----------+
[20:43:42]: No such file or directory @ rb_sysopen - /Applications/Xcode.app/Contents/Developer//Platforms/iPhoneOS.platform/Developer/usr/bin/PackageApplication

+------+------------------+-------------+
|           fastlane summary            |
+------+------------------+-------------+
| Step | Action           | Time (in s) |
+------+------------------+-------------+
| 1    | update_fastlane  | 7           |
| 2    | default_platform | 0           |
| 💥   | gym              | 48          |
+------+------------------+-------------+

[20:43:42]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/bunn/.fastlane/bin/bundle/lib/ruby/2.2.0/digest.rb:49:in `initialize': [!] No such file or directory @ rb_sysopen - /Applications/Xcode.app/Contents/Developer//Platforms/iPhoneOS.platform/Developer/usr/bin/PackageApplication (Errno::ENOENT)
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/2.2.0/digest.rb:49:in `open'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/2.2.0/digest.rb:49:in `file'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/2.2.0/digest.rb:34:in `file'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/gym/xcodebuild_fixes/package_application_fix.rb:23:in `block in patch_package_application'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/gym/xcodebuild_fixes/package_application_fix.rb:13:in `patch_package_application'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/gym/generators/package_command_generator_legacy.rb:16:in `generate'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/gym/generators/package_command_generator.rb:16:in `generate'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/gym/runner.rb:121:in `package_app'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/gym/runner.rb:19:in `run'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/gym/lib/gym/manager.rb:14:in `work'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:16:in `block (2 levels) in parsing_binding'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
	from /Users/bunn/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.23.0/bin/fastlane:20:in `<top (required)>'
	from /Users/bunn/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/bunn/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

```
[INSERT OUTPUT HERE]

### Environment

```
| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

```

**Comment by KrauseFx** [comment]
Hey @Bunn, thanks for submitting this issue. Do you have the legacy build API enabled? If so, can you try disabling it?

**Comment by Bunn** [comment]
@KrauseFx That did the trick, thanks 👍 
But it's interesting, I had the legacy build enabled for some reason, I can't remember but I think it was related to code signing. So I guess this is not an issue anymore.

Thanks again.

**Comment by KrauseFx** [comment]
Yeah, it's unfortunate, but lots of people still use the legacy build API 😢

**Comment by jlubeck** [comment]
Hey @KrauseFx can you give a brief description of what did that parameter do? Because I ran into this same issue, and yes, removing it fixed it. But I had to had for some reason, right?

Thanks!!

**Comment by Bunn** [comment]
In my case I'm not 100% sure but I think was something related to code signing an ad-hoc build.
I found more info here:
https://github.com/fastlane/fastlane/issues/6321 and here https://github.com/fastlane-old/gym/issues/104

**Comment by WANGjieJacques** [comment]
Hi, @KrauseFx, I have the same error, and I disabled the legacy build API, and I have an other error.

Error Domain=IDECodesignResolverErrorDomain Code=5 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier \U201xxxxxxx.xx.xx.x\U201d were found., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7fa774391160; portalTeamID='xxxx', usingTeamBasedSigning='NO', bundleIdentifier='xx.xx.xx.x.xt', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"aps-environment\" = development;\n    \"beta-reports-active\" = 1;\n    \"keychain-access-groups\" =     (\n        \"9SP4AKXQTU.com.thanksys.fidcashx.user\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
};
and it works when I use Xcode 8.2, legacy API.

**Comment by RHKliffer** [comment]
Hi @KrauseFx, Also getting errors, even after removing the legacy api
[18:57:04]: Exit status: 70
[18:57:04]: 📋  For a more detailed error log, check the full log at:
[18:57:04]: 📋  /Users/ronkliffer/Library/Logs/gym/DriverBox-DriverBox.log
+----------------------------+---------------------------------------------------------------------+
|                                           Lane Context                                           |
+----------------------------+---------------------------------------------------------------------+
| DEFAULT_PLATFORM           | ios                                                                 |
| PLATFORM_NAME              | ios                                                                 |
| LANE_NAME                  | ios release                                                         |
| SCAN_DERIVED_DATA_PATH     | /Users/ronkliffer/Library/Developer/Xcode/DerivedData/DriverBox-... |
| SCAN_GENERATED_PLIST_FILES | ["/Users/ronkliffer/Library/Developer/Xcode/DerivedData/DriverBo... |
| SCAN_GENERATED_PLIST_FILE  | /Users/ronkliffer/Library/Developer/Xcode/DerivedData/DriverBox-... |
| BUILD_NUMBER               | 20170329.185212                                                     |
| VERSION_NUMBER             | 8.9.10                                                              |
+----------------------------+---------------------------------------------------------------------+
[18:57:04]: Error packaging up the application

+------+---------------------------------------------+-------------+
|                         fastlane summary                         |
+------+---------------------------------------------+-------------+
| Step | Action                                      | Time (in s) |
+------+---------------------------------------------+-------------+
| 1    | default_platform                            | 0           |
| 2    | Switch to ios tests lane                    | 0           |
| 3    | scan                                        | 83          |
| 4    | xcov                                        | 8           |
| 5    | Switch to ios release_no_tests lane         | 0           |
| 6    | Switch to ios slack_notification_begin lane | 0           |
| 7    | slack                                       | 1           |
| 8    | increment_build_number                      | 1           |
| 9    | increment_version_number                    | 1           |
| 10   | Switch to ios build lane                    | 0           |
| 11   | get_version_number                          | 0           |
| 💥   | gym                                         | 288         |
+------+---------------------------------------------+-------------+

[18:57:04]: fastlane finished with errors

**Comment by lferro9000** [comment]
Same issue:
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

#select xcode version
#xcversion(version: "8.1") # Selects Xcode 8.1.0

xcode_select "/Applications/Xcode.app"

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Create a new Alpha Build"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'xxxx',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: 'xxxx',
      use_legacy_build_api:true,
      configuration: 'Alpha',
      output_directory: './build',
      output_name: 'xxxx-Alpha.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )
      
    # pilot
    hockey(
      api_token: 'xxxx',
      public_identifier: 'xxxx',
      ipa: 'build/xxxx-Alpha.ipa',
      notify: '1',
      status: '2',
      release_type: '2',
      teams: 'xxxx',
      tags: 'developer,tester',
      strategy: 'replace'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Create a new Beta Build"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'xxxx',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: 'xxxx',
      use_legacy_build_api:true,
      configuration: 'Beta',
      output_directory: './build',
      output_name: 'xxxx-Beta.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )

    hockey(
      api_token: 'xxxx',
      public_identifier: 'xxxx',
      ipa: 'build/xxxx-Beta.ipa',
      notify: '1',
      status: '2',
      release_type: '0',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )


    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

  end
 
  desc "Create a new Store Build"
  desc "This will also make sure the profile is up to date"
  lane :store do
    match(
      type: 'appstore',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'xxxx',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    # snapshot

    gym(
      scheme: 'xxxx',
      use_legacy_build_api:true,
      configuration: 'Store',
      output_directory: './build',
      output_name: 'xxxx-Store.ipa',
      include_symbols:false,
      include_bitcode:false,
      silent:true
    )

    deliver(
      skip_metadata: true, 
      skip_screenshots: true, 
      submit_for_review: false, 
      force: true,
      username: 'xxxx'
    )
    # frameit

    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

    hockey(
      api_token: 'xxxx',
      public_identifier:  'xxxx',
      ipa: 'build/xxxx-Store.ipa',
      notify: '1',
      status: '2',
      release_type: '1',
      teams: 'xxxx',
      tags: 'developer,tester',
      strategy: 'replace'
    )


  end

  # You can define as many lanes as you want

  after_all do |lane|
    #hockey

    puts "All done successfully..."
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|

    puts "Error: " + exception.message

    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "xxxx" # Your Apple email address
team_id "V7J29L8Y68"  # Developer Portal Team ID

for_lane :test do
    app_identifier 'xxxx'
end

for_lane :alpha do
    app_identifier 'xxxx'
end

for_lane :beta do
    app_identifier 'xxxx'
end

for_lane :store do
    app_identifier 'xxxx'
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.3        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| fastimage                 | 2.1.0        |
| bundler                   | 1.14.6       |
</details>


*generated on:* **2017-03-29**
</details>
```

**Comment by jgenden** [comment]
@WANGjieJacques I was seeing a similar error when building against an enterprise profile with Xcode 8.3 after removing the legacy build api setting. The solution was to add `export_method: "enterprise"` to the gym invocation.

**Comment by WANGjieJacques** [comment]
@jgenden thanks, it works, for me, I add  `export_method: "development"`

**Comment by gleyba** [comment]
Hello.
With use_legacy_build_api:true I get this error:
No such file or directory @ rb_sysopen - /Applications/Xcode.app/Contents/Developer//Platforms/iPhoneOS.platform/Developer/usr/bin/PackageApplication
Without use_legacy_build_api I get this:
"exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found development}

Xcode 8.3
default config from https://fabric.io/features/distribution?utm_campaign=fastlane.tools
Have anyone fixed it?

**Comment by lferro9000** [comment]
I tryed to remove the legacy_mode thing, and add the export_method. But now i'm getting the error stated in:

https://github.com/fastlane/fastlane/issues/8704

Basically, on xcode 8.3, the PackageApplication which is inside xcode.app bundle is not present anymore.

**Comment by i-schuetz** [comment]
I removed legacy mode but now I get "No matching provisioning profiles found". I think this was the reason I had to add legacy mode in the first place. It was working in Xcode 8.2.

I also tried with the setting posted by @WANGjieJacques `export_method: "development"` or `export_method: "ad-hoc"` but I still get the same error...

**Comment by WANGjieJacques** [comment]
@i-schuetz maybe you can try other options, available options are `app-store, ad-hoc, package, enterprise, development, developer-id`.

**Comment by i-schuetz** [comment]
@WANGjieJacques I need ad-hoc...

**Comment by KrauseFx** [comment]
Hey everyone, sorry for jumping in so late, I had to do some investigations before replying 👋 

Unfortunately the legacy build API was removed with Xcode 8.3. Please make sure to remove `use_legacy_build_api` from your `./fastlane/Fastfile` and update the `gym` call to include the export method like this:

**App Store Builds**
```ruby
gym(scheme: "MyScheme", export_method: "app-store")
```

**Ad Hoc Builds**
```ruby
gym(scheme: "MyScheme", export_method: "ad-hoc")
```

**Development Builds**
```ruby
gym(scheme: "MyScheme", export_method: "development")
```

**In-House Enterprise Builds**
```ruby
gym(scheme: "MyScheme", export_method: "enterprise")
```

---

### What to do if you run into code signing errors?

If you run into a code signing error, please check out our [troubleshooting guide](https://docs.fastlane.tools/codesigning/troubleshooting/) and [common issue and how to solve them](https://docs.fastlane.tools/codesigning/common-issues/).

If that still doesn't help **please** [submit a new issue](https://github.com/fastlane/fastlane/issues/new) instead of replying to this one. Make sure to share your `fastlane env` output when doing so, and mention that you followed all steps in the linked docs.

I hope that helps, please let me know if the documentation is unclear, or if there is anything else we can do better 🚀

**Comment by lferro9000** [comment]
So that others can find it also...

I had exactly the case as referred by @gleyba and in my case, the solution was that i had some subprojects included as dependencies which had on the building settings a wrong setting:

From:
```
Skip Install: No
```
Change to:
```
Skip Install: Yes
```
On all such subprojects.

You can test if your binary is fine by trying to "Archive" it in xcode.

If the binary ends up in the organizer inside the "Other items" and marked as a "Generic Xcode Archive", then there is something wrong with the libraries with that setting or there are public header-files being exposed (which can also trigger the same issue as the skip install setting).

If the binary ends up in the "iOS Apps" (no idea on the other kinds like macOS ones etc), then the binary should be fine and the new build process will not complain anymore of the "method" error.

**Comment by adasGit** [comment]
@lferro9000 saved my struggle!! Thanks a lot :)
I was lost with the following issue,
binary ends up in the organizer inside the "Other items" and marked as a "Generic Xcode Archive"!
Sub project: Change to
Skip Install: Yes
