### ISSUE TITLE
SwiftLint action doesn't work when SwiftLint is installed from CocoaPods

### ISSUE THREAD

**Issue by kevinrenskers** [fastlane/fastlane#8674]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm using SwiftLint with the Fastlane action to run it automatically on build time. Now that I've switched SwiftLint from Homebrew to Cocoapods, Fastlane's SwiftLint action no longer works (it can't find SwiftLint). 

How can I point to the new bin location in the pods folder?

**Comment by kevinrenskers** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.1u  22 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
opt_out_usage

fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(type: "development")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean
    cocoapods

    # Test for linting errors (warnings are ok)
    #swiftlint

    # Increment the build number (not the version number)
    increment_build_number

    # Commit the version bump
    commit_version_bump

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    # Deal with certificates and provisioning
    match(type: "appstore")

    # Build your app
    gym(scheme: "LastFm")

    # Upload to TestFlight
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # Make sure we only release from a clean master branch
    ensure_git_branch
    ensure_git_status_clean

    # Deal with TODO items before releasing!
    ensure_no_debug_code(text: "// TODO")

    cocoapods
    swiftlint

    match(type: "appstore")
    gym(scheme: "LastFm")

    # Upload to App Store
    deliver(force: true)
  end

  lane :repilot do
    pilot
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "fm.last.batch-scrobbler" # The bundle identifier of your app
apple_id "kevin@loopwerk.io" # Your Apple email address

team_id "4L3739XFB8"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 2.0.3        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| faraday                   | 0.11.0       |
| faraday_middleware        | 0.11.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| fastimage                 | 2.1.0        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| unicode-display_width     | 1.1.3        |
</details>


*generated on:* **2017-03-28**
</details>

**Comment by kevinrenskers** [comment]
This is not solved.

**Comment by mgrebenets** [comment]
Hi @kevinrenskers 

It can't find SwiftLint since it's not in the system `PATH`.

Potentially, a new parameter _could_ be added to `swiftlint` to allow specifying exact executable path... I say "potentially", because this approach may not scale up too good. Any action that uses external tool could have this tool installed in custom location.

I'm not sure on this one, would love to hear from others whether a new param should be added or not.

Meanwhile, as a workaround, you can add location of your SwiftLint installation to system `PATH` before calling `swiftlint` action.

Something like this:

```ruby
ENV["PATH"] = ["path/to/dir/with/swiftlint", ENV["PATH"]].join(":")
swiftlint
```

**Comment by voloshynslavik** [comment]
@kevinrenskers I had the same problem. I've fixed it by reinstallation SwiftLint. Try to run next 2 commands 
`brew uninstall swiftlint`
and 
`brew install swiftlint`

**Comment by kevinrenskers** [comment]
Reinstalling SwiftLint with brew isn't really a solution, since I want to have it installed per-project with Cocoapods :)

**Comment by ohayon** [comment]
@kevinrenskers I think that @mgrebenets is on to something with his solution. One option would be following his proposal by prepending the path to your `swiftlint` binary to your `PATH`, another would be, like he mentioned, we could make a change to the swift lint action so that it would take an `executable_path` option, where you could point it to your binary in your `Fastfile`.

**Comment by ohayon** [comment]
That PR ^ allows you to specify the path to your `swiftlint` executable. So now your `swiftlint` action in your `Fastfile` can be changed to something like: `swiftlint(executable: './Pods/SwiftLint/swiftlint')` 🚀
