### ISSUE TITLE
ERROR:  While executing gem ... (Gem::DependencyError)

### ISSUE THREAD

**Issue by mcmengchen** [fastlane/fastlane#8679]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When I install fast lane via ```sudo gem install fastlane```

##### Complete output when running fastlane, including the stack trace and command used
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires xcpretty (< 1.0.0, >= 0.2.4), terminal-notifier (< 2.0.0, >= 1.6.2), terminal-table (< 2.0.0, >= 1.4.5), plist (< 4.0.0, >= 3.1.0), addressable (< 3.0.0, >= 2.3), multipart-post (~> 2.0.0), word_wrap (~> 1.0.0), tty-screen (~> 0.5.0), babosa (< 2.0.0, >= 1.0.2), commander (< 5.0.0, >= 4.4.0), excon (< 1.0.0, >= 0.45.0), faraday-cookie_jar (~> 0.0.6), fastimage (>= 1.6), google-api-client (~> 0.9.2), highline (< 2.0.0, >= 1.7.2), mini_magick (~> 4.5.1), multi_json (>= 0), multi_xml (~> 0.5), rubyzip (< 2.0.0, >= 1.1.0), security (= 0.1.3), xcpretty-travis-formatter (>= 0.0.3), dotenv (< 3.0.0, >= 2.1.1), bundler (< 2.0.0, >= 1.12.0), faraday (~> 0.9), faraday_middleware (~> 0.9)
[INSERT OUTPUT HERE]

**Comment by mfurtak** [comment]
Hi @mcmengchen 👋 

Can you please post the command you are using to run _fastlane_?" Thanks 👍

**Comment by mcmengchen** [comment]
Hi @mfurtak 
I've just open the c
localhost:~ mengchen$ sudo gem install fastlane
Password:
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires terminal-notifier (< 2.0.0, >= 1.6.2), terminal-table (< 2.0.0, >= 1.4.5), plist (< 4.0.0, >= 3.1.0), addressable (< 3.0.0, >= 2.3), multipart-post (~> 2.0.0), word_wrap (~> 1.0.0), tty-screen (~> 0.5.0), babosa (< 2.0.0, >= 1.0.2), commander (< 5.0.0, >= 4.4.0), excon (< 1.0.0, >= 0.45.0), faraday-cookie_jar (~> 0.0.6), fastimage (>= 1.6), google-api-client (~> 0.9.2), highline (< 2.0.0, >= 1.7.2), mini_magick (~> 4.5.1), multi_json (>= 0), multi_xml (~> 0.5), rubyzip (< 2.0.0, >= 1.1.0), security (= 0.1.3), xcpretty-travis-formatter (>= 0.0.3), dotenv (< 3.0.0, >= 2.1.1), bundler (< 2.0.0, >= 1.12.0), faraday (~> 0.9), faraday_middleware (~> 0.9)
localhost:~ mengchen$

**Comment by mfurtak** [comment]
Hi @mcmengchen - I'm not sure how to approach debugging this for you. You may have better luck using our pre-packaged fastlane installer, which comes with its own Ruby environment.

You can download it from https://download.fastlane.tools and then run the `install` script from your terminal.

Hope that helps 🚀

**Comment by KrauseFx** [comment]
I'll close this issue for now, feel free to re-open 👍
