### ISSUE TITLE
tvOS not supported

### ISSUE THREAD

**Issue by victor** [fastlane/fastlane#868]
I tried adding fastlane to a tvOS project. After completing fastlane init, I tried listing the lanes or invoking the beta action and got a few crashes. Here are a few of the crash ids: 

9f4bae97ab5d5d5cddce1af2057c64d0
e46a1df88377aebc3b0da1523c36fe25
4ffd876398b5469f5b2778f81d8b829a
b8c5b74435c6b8f7da13fe960e1af1d3

After looking at the crash reports, it's clear what is the reason:

    "message": "RuntimeError: \u001b[31mPlatform 'tvos' is not supported. Must be either [:ios, :mac, :android]\u001b[0m",

Let me know how can I help you to add support for the AppleTV

**Comment by EmilYo** [comment]
+1 for tvos support :)

**Comment by pdesantis** [comment]
+1 :)

**Comment by EmilYo** [comment]
There was some tvOS related changes on fastlane_core. Hopefully all tools will be update for tvOS as well.

**Comment by KrauseFx** [comment]
@EmilYo we're busy working on it :rocket: It's not very easy and straight forward, as the tvOS app is tightly coupled with the iOS app.

**Comment by mgazdich** [comment]
Any update on the support for tvOS? Currently trying to use a sigh lane in my fastfile to pull down an adhoc provisioning profile of type tvOS, if I just perform the sigh command from the CLI it gives me the correct profile, but the sigh lane wont recognize the profile and I believe it is because the platform is not specified as tvOS.

**Comment by ohwutup** [comment]
Hey @mgazdich! Thanks for submitting the issue, looks like you got the problem taken care of? I am going to close the issue for now but please feel free to reopen/comment if you are still running into problems!
