### ISSUE TITLE
match git_user_email option not working

### ISSUE THREAD

**Issue by jpaas** [fastlane/fastlane#8681]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I don't have a global git email configured, and I've configured git_user_email in my Matchfile, but it still doesn't seem to work because pushing my cert repo still fails. See output below.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$ bundle exec fastlane match nuke development
[11:42:29]: Successfully loaded '/Users/jpaas/Documents/karma/worker-react-app/fastlane/Matchfile' 📄

+----------------+------------------------------------------------+
|           Detected Values from './fastlane/Matchfile'           |
+----------------+------------------------------------------------+
| app_identifier | ["com.karmacasting.karmacasting"]              |
| git_full_name  | Karma Apple Dev aka Cody McCodeface            |
| git_url        | git@bitbucket.org:karmacasting/karma-certs.git |
| git_user_email | appledev@karmacasting.com                      |
| type           | development                                    |
| username       | appledev@karmacasting.com                      |
+----------------+------------------------------------------------+

[11:42:29]: Cloning remote git repo...
[11:42:31]: Migrating to new match...
[11:42:31]: Cloning remote git repo...
[11:42:34]: 🔓  Successfully decrypted certificates repo
keychain: "/Users/jpaas/Library/Keychains/login.keychain-db"
version: 512
class: "inet"
attributes:
    0x00000007 <blob>="match_git@bitbucket.org:karmacasting/karma-certs.git"
    0x00000008 <blob>=<NULL>
    "acct"<blob>=<NULL>
    "atyp"<blob>="dflt"
    "cdat"<timedate>=0x32303137303332383135323733345A00  "20170328152734Z\000"
    "crtr"<uint32>=<NULL>
    "cusi"<sint32>=<NULL>
    "desc"<blob>=<NULL>
    "icmt"<blob>=<NULL>
    "invi"<sint32>=<NULL>
    "mdat"<timedate>=0x32303137303332383135323733345A00  "20170328152734Z\000"
    "nega"<sint32>=<NULL>
    "path"<blob>=<NULL>
    "port"<uint32>=0x00000000 
    "prot"<blob>=<NULL>
    "ptcl"<uint32>=0x00000000 
    "scrp"<sint32>=<NULL>
    "sdmn"<blob>=<NULL>
    "srvr"<blob>="match_git@bitbucket.org:karmacasting/karma-certs.git"
    "type"<uint32>=<NULL>
password has been deleted.
[11:42:34]: 🔒  Successfully encrypted certificates repo
[11:42:34]: Pushing changes to remote git repo...

*** Please tell me who you are.

Run

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'jpaas@slimshady.(none)')
[11:42:34]: Exit status: 128
[11:42:34]: Couldn't commit or push changes back to git...
[11:42:34]: Exit status: 128

+-----------------------+------------------------------------------------+
|                     Summary for match nuke 2.23.0                      |
+-----------------------+------------------------------------------------+
| git_full_name         | Karma Apple Dev aka Cody McCodeface            |
| git_url               | git@bitbucket.org:karmacasting/karma-certs.git |
| git_user_email        | appledev@karmacasting.com                      |
| type                  | development                                    |
| username              | appledev@karmacasting.com                      |
| git_branch            | master                                         |
| keychain_name         | login.keychain                                 |
| readonly              | false                                          |
| team_id               | 258N8Y58G5                                     |
| verbose               | false                                          |
| force                 | false                                          |
| skip_confirmation     | false                                          |
| shallow_clone         | false                                          |
| force_for_new_devices | false                                          |
| skip_docs             | false                                          |
| platform              | ios                                            |
+-----------------------+------------------------------------------------+

[11:42:34]: Fetching certificates and profiles...

[11:42:39]: No relevant certificates or provisioning profiles found, nothing to nuke here :)
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 10.12.3                                              |
| Ruby                        | 2.4.0                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.11.0 (Apple Git-81)                    |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0@worker-react-app/bin/fastlane |
| Host                        | Mac OS X 10.12.3 (16D32)                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                         |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                          |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 8.3                                                  |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.23.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "KarmaWorkerApp development") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "KarmaWorkerApp development") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.karmacasting.karmacasting" # The bundle identifier of your app
apple_id "julian.paas@karmacasting.com" # Your Apple email address

team_id "258N8Y58G5"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-28**
</details>
```

**Comment by jpaas** [comment]
When I did configure a global git email, my certs repo was committed using the global email instead of the one configured using git_user_email.

**Comment by KrauseFx** [comment]
It seems like it never gets to the point where it prints `Add git user config to local git repo...`, I'll take a look into this. Thanks for submitting this issue.

**Comment by KrauseFx** [comment]
That's so weird, I just tried it and things work fine on my machine. So in your log, `git user config to local git` is nowhere to be found?

**Comment by jpaas** [comment]
@KrauseFx I don't think so since I posted the complete console output. Another weird thing I noticed, is that this seemed to only happen with nuke. Later when I generated certs using `fastlane match appstore`, it used the email that was configured using `git_user_email`.
