### ISSUE TITLE
Import command should also import Pluginfile

### ISSUE THREAD

**Issue by netbe** [fastlane/fastlane#8682]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Doing an import of a Fastfile via `import_from_git`, the fastfile and actions are imported.

```
import_from_git(url: 'ssh://......git',  path: 'CommonFastfile')
```

But the `Pluginfile` is not imported, I think as the actions are imported it make sense to import the `Pluginfile` too.

**Comment by KrauseFx** [comment]
Mh, I don't think that's gonna work, as all Ruby files are already loaded at that point by bundler. You'd have to run `bundle update` after importing the file, which is not something fastlane can do on its own as far as I know.

**Comment by netbe** [comment]
@KrauseFx what about `fastlane install_plugins` what does it do `bundle install`?

Alternative would import_from_git(url: 'ssh://......git',  path: 'Pluginfile') work (followed by `bundle install`)?
