### ISSUE TITLE
How to know which build is on Testflight when using Spaceship?

### ISSUE THREAD

**Issue by jmacwhyte** [fastlane/fastlane#8689]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello,

Just wanted to know the best way to figure out which build is live on internal/external testflight. I can see each build has a timestamp for when it is valid, but I haven't been able to find a quick and easy way to see which build is live. This info is displayed prominently on ITC so I assume it must be available. Any ideas?

**Comment by bencollier** [comment]
`fastlane pilot builds` is a good place to look. That'll list the build statuses.

**Comment by asfalcone** [comment]
@jmacwhyte You can checkout the code in [pilot `BuildManager.list`](https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L81) to see how it works (and what _spaceship_ APIs are used) 👍

**Comment by jmacwhyte** [comment]
Awesome, thanks!!
