### ISSUE TITLE
Suggestion: Make deliver skip metadata and screenshots by default

### ISSUE THREAD

**Issue by acrookston** [fastlane/fastlane#8690]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'd like to suggest a change in `deliver`'s default behavior to upload metadata and screenshots as this is a potentially destructive action.

As I'm sure there are many other teams out there where the metadata / screenshots are handled by non-developers or people who don't want put all this data into their repos. 

We were taken by surprise when I finally ran `deliver` for the first time and all our metadata and uploaded screenshots were replaced with older cached version from the repository.

I understand this is large purpose of `deliver` and I see how it is helpful for some people but I wish this feature was opt-in, turned off by default or at least clearly mentioned in the generated Fastlane file.

I would be happy to implement a change but wanted to get feedback/buy-in on this before submitting a PR.

**I'd like to suggest one of the following changes:**

- Set `skip_metadata` and `skip_screenshots` defaults to `true`
- Some method of halting the execution and wait for confirmation of default behavior, like a command line y/N, which could also be an at-first-run-only action. (see note below)
- Insert `skip_metadata` and `skip_screenshots` into the default template for the `Fastlane` file.

NOTE: I noticed when I run `fastlane deliver download_metadata` it asks me if I would like to overwrite the data in the repo. I'm suggesting the reverse implementation of this asking the operator if they would want to UPLOAD the metadata/screenshots. Download metadata asks `Do you want to overwrite existing metadata on path '[path]/fastlane/metadata'? (y/n)`

Sorry if this has already been previously discussed, I tried searching for it without success.

I've removed some keys and other personal information below and replaced with `REMOVED`.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last command line argument to get that collected for you

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.1                          |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.19.3"

default_platform :ios

platform :ios do
  before_all do
    ensure_git_status_clean

    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Upload a new Release Candidate to Crashlytics"
  lane :rc do
    register_devices(devices_file: "fastlane/devices.txt")
    match(force_for_new_devices: true, type: "adhoc")
    gym(
      workspace: "REMOVED",
      scheme: "REMOVED",
      include_symbols: true,
      include_bitcode: false
    )

    crashlytics(api_token: "REMOVED",
                build_secret: "REMOVED",
                groups: "Internal",
                notifications: true)

    send_slack("Successfully uploaded release candidate build.")
  end

  desc "Upload a new Beta Build to Crashlytics"
  lane :beta do
    register_devices(devices_file: "fastlane/devices.txt")
    match(force_for_new_devices: true, type: "adhoc")
    gym(
      workspace: "REMOVED",
      scheme: "REMOVED",
      include_symbols: true,
      include_bitcode: false
    )

    crashlytics(api_token: "REMOVED",
                build_secret: "REMOVED",
                groups: "Internal",
                notifications: true)

    send_slack("Successfully uploaded beta build.")
  end

  desc "Submit a new Production build to Apple TestFlight"
  lane :testflight_beta do
    register_devices(devices_file: "fastlane/devices.txt")
    match(force_for_new_devices: true, type: "adhoc")
    gym(
      workspace: "REMOVED",
      scheme: "REMOVED",
      include_symbols: true,
      include_bitcode: false
    )
    pilot
    send_slack("Successfully uploaded to TestFlight.")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(
      workspace: "REMOVED",
      scheme: "REMOVED",
      include_symbols: true,
      include_bitcode: false
    )

    deliver(
      force: true,
      skip_screenshots: true,
      skip_metadata: true,
      submit_for_review: false,
      automatic_release: true
      overwrite_screenshots: false
    )

    send_slack("Successfully deployed new App Store Update.")
  end

  #after_all do |lane|
    # This block is called, only if the executed lane was successful
  #end

  error do |lane, exception|
    notification("ERROR: #{exception.message}")
  end
end

def notification(message)
  # REMOVED
end

def send_slack(message)
    notification(message)
    slack(
        slack_url: "REMOVED"
        message: message,
        default_payloads: [],
        attachment_properties: {
            fields: [
                {
                    title: "Release",
                    value: Actions.lane_context[Actions::SharedValues::LANE_NAME],
                    short: true
                },
                {
                    title: "Built by",
                    value: `whoami`,
                    short: true
                },
                {
                    title: "Git Branch",
                    value: Fastlane::Actions.git_branch,
                    short: true
                },
                {
                    title: "Git author",
                    value: Fastlane::Actions.git_author,
                    short: true
                },
                {
                    title: "Last commit",
                    value: Fastlane::Actions.last_git_commit_message,
                    short: false
                }
            ]
        }
    )
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# REMOVED
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| faraday                   | 0.11.0       |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-03-28**
</details>

**Comment by KrauseFx** [comment]
> We were taken by surprise when I finally ran deliver for the first time and all our metadata and uploaded screenshots were replaced with older cached version from the repository.

There should be a HTML based preview of the metadata before it uploads **anything** to iTunes Connect, did this not work?

> I would be happy to implement a change but wanted to get feedback/buy-in on this before submitting a PR.

Great feedback! However changing the default behavior isn't as easy as it sounds, as it would break existing setups and people would need to update their files.

Let me know what you think

**Comment by acrookston** [comment]
Ah, is that HTML report ignored with `deliver(force: true)`? My original deliver script was just that, I've added the skip stuff since then.

Valid point regarding breaking behavior. Maybe we can at least change the default template to include some info/warning about this behavior? I looked over the default documentation and it wasn't immediately obvious to me.

Can you point me in the direction of the `Fastfile` template? Was having a hard time locating it.

**Comment by asfalcone** [comment]
@acrookston The `Fastfile` template is there: https://github.com/fastlane/fastlane/blob/master/fastlane/lib/assets/DefaultFastfileTemplate 👍

**Comment by KrauseFx** [comment]
I'll close this issue for now due to inactivity. Please feel free to re-open or submit a new one if you have any more questions 👍
