### ISSUE TITLE
use_legacy_build_api always true

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#8704]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Resurgence of issue  #1820, now with Xcode 8.3

xcodebuild -version
Xcode 8.3
Build version 8E162

The offending Gym part:
```
    gym(
      scheme: 'MyApp',
      use_legacy_build_api:false,
      configuration: 'Alpha',
      output_directory: './build',
      output_name: 'MyApp-Alpha.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:false,
      export_method: 'ad-hoc',
      clean:true
    )
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[08:59:44]: -----------------
[08:59:44]: --- Step: gym ---
[08:59:44]: -----------------
[08:59:44]: Using deprecated option: '--use_legacy_build_api' (Don't use this option any more, as it's deprecated by Apple)
[08:59:44]: $ xcodebuild -list -workspace ./MyApp.xcworkspace -configuration Alpha
[08:59:46]: $ xcodebuild clean -showBuildSettings -workspace ./MyApp.xcworkspace -scheme MyApp -configuration Alpha

+----------------------+-------------------------+
|             Summary for gym 2.23.0             |
+----------------------+-------------------------+
| scheme               | MyApp                  |
| use_legacy_build_api | false                   |
| configuration        | Alpha                   |
| output_directory     | ./build                 |
| output_name          | MyApp-Alpha            |
| include_symbols      | true                    |
| include_bitcode      | false                   |
| silent               | false                   |
| export_method        | ad-hoc                  |
| clean                | true                    |
| workspace            | ./MyApp.xcworkspace  |
| destination          | generic/platform=iOS    |
| buildlog_path        | ~/Library/Logs/gym      |
| xcode_path           | /Applications/Xcode.app |
+----------------------+-------------------------+

```
[09:01:40]: ▸ Touching MyApp.app
[09:01:40]: ▸ Signing /Users/xxxx/Library/Developer/Xcode/DerivedData/MyApp-cpzymfhlzjmnqjhajusysmfsilab/Build/Intermediates/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app
[09:01:40]: ▸ Archive Succeeded
[09:01:41]: Generated plist file with the following values:
[09:01:41]: ▸ -----------------------------------------
[09:01:41]: ▸ {
[09:01:41]: ▸   "method": "ad-hoc"
[09:01:41]: ▸ }
[09:01:41]: ▸ -----------------------------------------
[09:01:41]: $ /usr/bin/xcrun /Users/xxxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.23.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/4n/hwckvb9j5nq7bwvgtwl9s58r0000gp/T/gym_config20170330-49514-1u4omgd.plist' -archivePath /Users/xxxx/Library/Developer/Xcode/Archives/2017-03-30/MyApp-Alpha\ 2017-03-30\ 08.59.49.xcarchive -exportPath '/var/folders/4n/hwckvb9j5nq7bwvgtwl9s58r0000gp/T/gym_output20170330-49514-1bimre9' 
rbenv detected, removing env variables
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/4n/hwckvb9j5nq7bwvgtwl9s58r0000gp/T/gym_config20170330-49514-1u4omgd.plist -archivePath '/Users/xxxx/Library/Developer/Xcode/Archives/2017-03-30/MyApp-Alpha 2017-03-30 08.59.49.xcarchive' -exportPath /var/folders/4n/hwckvb9j5nq7bwvgtwl9s58r0000gp/T/gym_output20170330-49514-1bimre9
2017-03-30 09:01:42.205 xcodebuild[53199:576563] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/4n/hwckvb9j5nq7bwvgtwl9s58r0000gp/T/MyApp_2017-03-30_09-01-42.204.xcdistributionlogs'.
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc}

** EXPORT FAILED **
[09:01:42]: Exit status: 70
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.23.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.3        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| fastimage                 | 2.1.0        |
| bundler                   | 1.14.6       |
</details>

*generated on:* **2017-03-30**
</details>

**Comment by lferro9000** [comment]
If i type:
```
$> fastlane gym --use_legacy_build_api=false
$> fastlane gym --use_legacy_build_api false
```
I get
```
/Users/xxxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/gym-2.0.0/lib/gym/version.rb:3: warning: already initialized constant Gym::DESCRIPTION
/Users/xxxx/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.23.0/gym/lib/gym.rb:46: warning: previous definition of DESCRIPTION was here
[09:32:12]: Using deprecated option: '--use_legacy_build_api' (Don't use this option any more, as it's deprecated by Apple)
[09:32:12]: Couldn't automatically detect the project file, please provide a path:
```
This just means that the parameter is ignored in both the Fastlane file and the command line parameter and true is always applied.

There are no environment variables configured to change behaviors, and the result is exactly the same when running on an empty folder (a folder without fastlane configuration folder and files)

**Comment by yukiasai** [comment]
Hi @lferro9000.
Looking at the your log, `use_legacy_build_api` seems to be `false`.Even if you remove the `use_legacy_build_api` option from `gym`, will the same warning occurred?

Your log:
```
+----------------------+-------------------------+
| Summary for gym 2.23.0 |
+----------------------+-------------------------+
| scheme | MyApp |
| use_legacy_build_api | false |  << this
| configuration | Alpha |
| output_directory | ./build |
| output_name | MyApp-Alpha |
| include_symbols | true |
| include_bitcode | false |
| silent | false |
| export_method | ad-hoc |
| clean | true |
| workspace | ./MyApp.xcworkspace |
| destination | generic/platform=iOS |
| buildlog_path | ~/Library/Logs/gym |
| xcode_path | /Applications/Xcode.app |
+----------------------+-------------------------+
```

Thanks.

**Comment by lferro9000** [comment]
Yes. Having it or not doesn't affect how the code is compiled. It will always use the legacy mode, and with xcode 8.3 will fail on the method plist error (that was first documented as a problem in xcode 7).

**Comment by lferro9000** [comment]
Actually, commenting out the line altogether will make it stop using the legacy build method.

So basically the command is just ignoring the value used and always compiling if it's present.

However, the second part of the issue does happen regardless of method used for compiling:
```
[11:18:34]: Generated plist file with the following values:
[11:18:34]: ▸ -----------------------------------------
[11:18:34]: ▸ {
[11:18:34]: ▸   "method": "ad-hoc"
[11:18:34]: ▸ }
[11:18:34]: ▸ -----------------------------------------
[...]
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc
```

**Comment by lferro9000** [comment]
Installing xcode 8.2.1 and it's command line tools (by downloading them both from apple developer area) and swap the environment from 8.3 to 8.2.1 and then 8.3 solves the legacy build issue (the affected file is present on 8.2.1 after the command line tools are installed).

The plist method thing still persists.

**Comment by KrauseFx** [comment]
The legacy mode was removed from Xcode 8.3, so you have to have it disabled from now on. Could you share the latest `Fastfile` you're using?

**Comment by KrauseFx** [comment]
Check out my reply on another issue: https://github.com/fastlane/fastlane/issues/8672#issuecomment-290136915

**Comment by lferro9000** [comment]
Yes, but the problem stands, when i upgrade to the non-legacy build process i get the dreaded:
```
[09:22:42]: Generated plist file with the following values:
[09:22:42]: ▸ -----------------------------------------
[09:22:42]: ▸ {
[09:22:42]: ▸   "method": "ad-hoc"
[09:22:42]: ▸ }
[09:22:42]: ▸ -----------------------------------------
```
and then the:
```
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found ad-hoc
```
Is this related with the fact that xcode 8.3 is more sensitive to the bundles within the application and is now discarding "generic" apps if they have more then one bundle inside? (aka the issue related with the "install" build option and the public header files on the libraries)

**Comment by lferro9000** [comment]
Okie.

Case solved.

I had some libraries included as subprojects in the main project that where marked as "skip install" in the building settings with "No".

Changing it to "Yes" on all of them (there where quite a few of them) stopped the project to be marked as "Generic" and amazingly, stopped also to give that "method" error message.

Thanks once again for the creation and support of this great tool 👍

**Comment by mgrebenets** [comment]
Hi @lferro9000 

I've also stumbled on similar issue when moving away from legacy build API.

I have noticed that setting the value to `false` didn't do the job.
What worked for me is **removing the argument completely**.

I don't know what's the underlying root cause for that, probably there's some bug in the code, which makes missing argument different from `false` somehow.

**Comment by lferro9000** [comment]
This is now sorted.
