### ISSUE TITLE
portal_client.rb:434:in `download_certificate': [!] Couldn't download certificate,

### ISSUE THREAD

**Issue by elianfish** [fastlane/fastlane#8705]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Exec: fastlane sigh --development -a  com.test.autotest -u  ysl@163.com -n autotest_dev

Error:

/Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/spaceship/lib/spaceship/portal/portal_client.rb:434:in `download_certificate': [!] Couldn't download certificate, got this instead: {"responseId"=>"c9a734bc-6746-4093-8605-d3706a7e8602", "resultCode"=>7100, "resultString"=>"Certificate '9J2KM7ES28' not found", "userString"=>"There is no certificate with ID '9J2KM7ES28' on this team.", "creationTimestamp"=>"2017-03-30T09:57:08Z", "protocolVersion"=>"QH65B2", "userLocale"=>"en_US", "requestUrl"=>"https://developer.apple.com/services-account/QH65B2/account/ios/certificate/downloadCertificateContent.action", "httpCode"=>200} (Spaceship::Client::UnexpectedResponse)
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/spaceship/lib/spaceship/portal/certificate.rb:310:in `download_raw'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/runner.rb:203:in `block in certificate_to_use'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/runner.rb:201:in `each'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/runner.rb:201:in `find_all'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/runner.rb:201:in `certificate_to_use'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/runner.rb:137:in `create_profile!'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/runner.rb:35:in `run'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/manager.rb:7:in `start'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/commands_generator.rb:55:in `block (2 levels) in run'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/commands_generator.rb:123:in `run'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/sigh/lib/sigh/commands_generator.rb:11:in `start'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
        from /Users/elian/.rvm/gems/ruby-2.3.0/gems/fastlane-2.23.0/bin/fastlane:20:in `<top (required)>'
        from /Users/elian/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `load'
        from /Users/elian/.rvm/gems/ruby-2.3.0/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[fastlane_env.txt](https://github.com/fastlane/fastlane/files/887293/fastlane.txt)

**Comment by KrauseFx** [comment]
Please provide the information asked for by the bot

**Comment by elianfish** [comment]
upload fastlane_env.txt

**Comment by hjanuschka** [comment]
@elianfish  can you share the output of it inside the reply - that upload didn't seem to work?

also could you try setting `team_id` or `team_name` option to your sigh call, and enforce the right team?

**Comment by KrauseFx** [comment]
I'll close that issue now
