### ISSUE TITLE
Gem helper does not find bundler gems

### ISSUE THREAD

**Issue by BrettThePark** [fastlane/fastlane#871]
I am trying to setup fastlane to use slather via bundler. However, fastlane is saying it is not installed. I have it in the Gemfile and run bundle_install in fastlane.

From what I can tell, the method `Gem::Specification.find_by_name` in `gem_helper.rb:7` does not recognize gems within bundler. I would offer to submit a PR, but I really know next to nothing about ruby.

**Comment by BrettThePark** [comment]
Created a PR to disable the gem check when using `use_bundle_exec` parameter to slather https://github.com/fastlane/fastlane/pull/937

**Comment by KrauseFx** [comment]
Thanks again, fixed with https://github.com/fastlane/fastlane/pull/937
