### ISSUE TITLE
Action version_bump_podspec failure

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#8722]
🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The issue happens with the action `bump_podspec_version` when the version in podspec has addition to semver `PATCH` number.
For example:
```ruby
Pod::Spec.new do |s|
  ...
  s.version      = '2.4.4.1'
  ...
end
```

While parsing this Podspec the fastlane crashes with error: `Could not find version in podspec content 'Pod::Spec.new do...`.

I would love to contribute with the fix, but I just want to check first if it makes sense to support this kind of versions in Podspec: `x.y.z.q`? Seems like CocoaPods supports it, so maybe Fastlane should as well?

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require 'fileutils'

fastlane_version "1.104.0"

default_platform :ios

platform :ios do

  ############################## PRE ##############################

  before_all do
    update_fastlane
    import_shared_fastfile
    load_environment_variables
  end

  ######################### PUBLIC LANES ##########################

  lane :release do |options|
    release_branch = ENV['GITHUB_RELEASE_BRANCH']

    ensure_git_status_clean
    ensure_git_branch(
      branch: release_branch
    )

    release_version = options[:release_version]
    private_sdk_release = get_github_release(
      url: ENV['PRIVATE_CONICHI_IOS_SDK_GITHUB_REPO'],
      version: release_version,
      api_token: ENV['CONICHI_CI_GITHUB_TOKEN']
    )

    update_changelog_from_release(
      release: private_sdk_release
    )

    cnisdk_framework_zip_path = "CNISDK.framework.zip"
    download_cnisdk_framework_zip_from_release(
      release: private_sdk_release,
      download_destination: cnisdk_framework_zip_path
    )

    unzip(file: cnisdk_framework_zip_path)
    copy_frameworks_from_cnisdk_framework_folder(
      cnisdk_framework_folder: "../Carthage/Build/iOS"
    )

    remote = ENV['GITHUB_REMOTE']

    upcoming_version = get_upcoming_version.clone
    upcoming_notes = get_upcoming_notes.clone
    put_upcoming_to_releases

    podspecs_version_bump(
      version: upcoming_version
    )
    git_commit_shell(
      message: "Bump podspecs to #{upcoming_version}"
    )

    tag_name = upcoming_version
    git_add_or_update_tag(
      tag_name: tag_name,
      remote: remote,
      branch: release_branch
    )

    push_to_git_remote(
      remote: remote,
      local_branch: release_branch,
      remote_branch: release_branch
    )

    podspecs_push

    set_or_update_github_release(
      release_name: tag_name,
      repository_name: ENV['GITHUB_REPOSITORY'],
      description: upcoming_notes,
      tag_name: tag_name,
      api_token: ENV['CONICHI_CI_GITHUB_TOKEN'],
      upload_assets: [cnisdk_framework_zip_path]
    )
  end

  ######################### PRIVATE LANES ##########################

  private_lane :podspecs_version_bump do |options|
    version = options[:version]
    version_bump_podspec(path: ENV['CORE_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['PAYMENT_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['GEOFENCING_KIT_PODSPEC'], version_number: version)
    version_bump_podspec(path: ENV['PMS_KIT_PODSPEC'], version_number: version)
  end

  private_lane :podspecs_push do
    pod_push(path: ENV['CORE_KIT_PODSPEC'], allow_warnings: true)
    pod_push(path: ENV['PAYMENT_KIT_PODSPEC'], allow_warnings: true)
    pod_push(path: ENV['GEOFENCING_KIT_PODSPEC'], allow_warnings: true)
    pod_push(path: ENV['PMS_KIT_PODSPEC'], allow_warnings: true)
  end

  private_lane :import_shared_fastfile do
    import_from_git(
      url: "git@github.com:#{ENV['GITHUB_IOS_TEAM_REPOSITORY']}",
      branch: 'HEAD',
      path: 'fastlane/Fastfile'
    )
  end

  private_lane :load_environment_variables do
    sh("source ~/.bash_profile")
  end

  private_lane :copy_frameworks_from_cnisdk_framework_folder do |options|
    cnisdk_framework_folder = options[:cnisdk_framework_folder]
    frameworks_to_copy = ["CNISDKCoreKit.framework", "CNISDKGeoFencingKit.framework",
                          "CNISDKPaymentKit.framework", "CNISDKPMSKit.framework",
                          "Conichi_Authentication.framework", "Conichi_Errors.framework",
                          "Conichi_Meta.framework", "PaylevenFramework.framework"]
    frameworks_to_copy.each do |framework|
      FileUtils.cp_r("#{cnisdk_framework_folder}/#{framework}", "../Frameworks")
    end
    unless git_status_clean?
      git_commit_shell(
        message: "conichi frameworks have been updated;"
      )
    end
  end

  private_lane :download_cnisdk_framework_zip_from_release do |options|
    release = options[:release]
    assets = release["assets"]
    selected_assets = assets.select do |asset|
      asset["name"] == "CNISDK.framework.zip"
    end
    cnisdk_framework_zip_asset = selected_assets[0]
    url = cnisdk_framework_zip_asset["url"]
    download_destination = options[:download_destination]
    cni_download_github_release_asset(
      asset_url: url,
      destination_path: download_destination,
      api_token: ENV['CONICHI_CI_GITHUB_TOKEN']
    )
  end

  private_lane :update_changelog_from_release do |options|
    require 'redcarpet'
    require 'redcarpet/render_strip'

    release = options[:release]
    release_version = release["tag_name"]

    markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
    release_body_text = markdown.render(release["body"])
    release_changes = release_body_text.split("\n")

    changelog_data = get_changelog_data
    changelog_data["upcoming"]["version"] = release_version
    changelog_data["upcoming"]["notes"] = release_changes

    save_changelog_data(
      changelog_data: changelog_data
    )

    unless git_status_clean?
      git_commit_shell(
        message: "Update CHANGELOG with upcoming release information"
      )
    end
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.24.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-unzip | 1.0.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bundler                   | 1.13.7       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| cork                      | 0.2.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.2.1.beta.1 |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 0.2.6        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| cocoapods                 | 1.2.1.beta.1 |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.13.2       |
| sawyer                    | 0.8.1        |
| octokit                   | 4.6.2        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| danger                    | 4.3.2        |
| danger-prose              | 2.0.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| fastlane-plugin-unzip     | 1.0.1        |
| redcarpet                 | 3.4.0        |
</details>

*generated on:* **2017-03-31**
</details>

**Comment by asfalcone** [comment]
@Antondomashnev Hi, thanks for opening an issue about this. I think this is a totally reasonable change and I'd be happy to review the PR! 👍

**Comment by KrauseFx** [comment]
Thanks for contributing @Antondomashnev, this is great 👍
