### ISSUE TITLE
Wrong screengrab shots folder name

### ISSUE THREAD

**Issue by Edwhis** [fastlane/fastlane#8726]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have strange issue while trying to make localized screenshots with Sccreengrab tool for Android. Everything works well except that Screengrab creates folders like "en-" instead of "en-US", or "da-" instead of "da-DK". So, if I want to use supply command, I always need to rename them by hand :|

My screengrab file:

+----------------------------+--------------------------+
| Detected Values from './fastlane/Screengrabfile' |
+----------------------------+--------------------------+
| clear_previous_screenshots | true |
| locales | ["da-DK"] |
| ending_locale | da-DK |
+----------------------------+--------------------------+

Using this file i don't even get "da-" folder created. In fastlane metadata folder only "en-" locale folder appears. 
```

INFO [2017-03-31 11:15:51.30]: Installing app APK
INFO [2017-03-31 11:15:51.30]: [4m[36m$ adb -s emulator-5554 install -r app/build/outputs/apk/app_debug.apk[0m[0m
INFO [2017-03-31 11:16:09.95]: ▸ [35m1262 KB/s (23993029 bytes in 18.554s)[0m
INFO [2017-03-31 11:16:11.49]: ▸ [35mpkg: /data/local/tmp/app_debug.apk[0m
INFO [2017-03-31 11:16:29.55]: ▸ [35mSuccess[0m
INFO [2017-03-31 11:16:30.22]: Installing tests APK
INFO [2017-03-31 11:16:30.22]: [4m[36m$ adb -s emulator-5554 install -r app/build/outputs/apk/app-debug-androidTest.apk[0m[0m
INFO [2017-03-31 11:16:31.46]: ▸ [35m1048 KB/s (1227488 bytes in 1.143s)[0m
INFO [2017-03-31 11:16:33.90]: ▸ [35mpkg: /data/local/tmp/app-debug-androidTest.apk[0m
INFO [2017-03-31 11:16:37.12]: ▸ [35mSuccess[0m
INFO [2017-03-31 11:16:37.56]: Granting the permission necessary to change locales on the device
INFO [2017-03-31 11:16:37.56]: [4m[36m$ adb -s emulator-5554 shell pm grant com.takeout.whitelabel.market_dk_23_stage android.permission.CHANGE_CONFIGURATION[0m[0m
INFO [2017-03-31 11:16:39.22]: [4m[36m$ adb -s emulator-5554 shell getprop ro.build.version.sdk[0m[0m
INFO [2017-03-31 11:16:39.34]: ▸ [35m19[0m
INFO [2017-03-31 11:16:39.35]: Running tests for locale: da-DK
INFO [2017-03-31 11:16:39.35]: [4m[36m$ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale da_DK \
-e endingLocale da_DK \
com.app.test/android.support.test.runner.AndroidJUnitRunner[0m[0m
INFO [2017-03-31 11:17:32.17]: ▸ [35mcom.app.Test1_Screengrab:.[0m
INFO [2017-03-31 11:19:52.10]: ▸ [35mTime: 175.182[0m
INFO [2017-03-31 11:19:52.10]: ▸ [35mOK (3 tests)[0m
INFO [2017-03-31 11:19:52.68]: Pulling captured screenshots from the device
DEBUG [2017-03-31 11:19:52.68]: Starting screenshot count is: 0
INFO [2017-03-31 11:19:52.91]: ▸ [35m/storage/sdcard/app/screengrab: No such file or directory[0m
INFO [2017-03-31 11:19:53.09]: ▸ [35men-[0m
INFO [2017-03-31 11:19:53.11]: [4m[36m$ adb -s emulator-5554 pull /data/data/app/app_screengrab /tmp/d20170331-9632-15s5a06[0m[0m
INFO [2017-03-31 11:19:53.21]: ▸ [35mpull: building file list...[0m
INFO [2017-03-31 11:19:53.43]: ▸ [35mpull: /data/data/app/app_screengrab/en-/images/screenshots/5_checkout_1490959187888.png -> /tmp/d20170331-9632-15s5a06/en-/images/screenshots/5_checkout_1490959187888.png[0m
INFO [2017-03-31 11:19:53.60]: ▸ [35mpull: /data/data/app/app_screengrab/en-/images/screenshots/4_product_1490959179073.png -> /tmp/d20170331-9632-15s5a06/en-/images/screenshots/4_product_1490959179073.png[0m
INFO [2017-03-31 11:19:54.29]: ▸ [35mpull: /data/data/app/app_screengrab/en-/images/screenshots/3_restaurant_menu_expanded_1490959160435.png -> /tmp/d20170331-9632-15s5a06/en-/images/screenshots/3_restaurant_menu_expanded_1490959160435.png[0m
INFO [2017-03-31 11:19:54.74]: ▸ [35mpull: /data/data/app/app_screengrab/en-/images/screenshots/2_restaurant_menu_1490959152326.png -> /tmp/d20170331-9632-15s5a06/en-/images/screenshots/2_restaurant_menu_1490959152326.png[0m
INFO [2017-03-31 11:19:55.15]: ▸ [35mpull: /data/data/app/app_screengrab/en-/images/screenshots/1_login_screen_1490959048819.png -> /tmp/d20170331-9632-15s5a06/en-/images/screenshots/1_login_screen_1490959048819.png[0m
INFO [2017-03-31 11:19:55.66]: ▸ [35m5 files pulled. 0 files skipped.[0m
INFO [2017-03-31 11:19:55.66]: ▸ [35m824 KB/s (2064646 bytes in 2.446s)[0m
INFO [2017-03-31 11:19:55.66]: [32mScreenshots copied to fastlane/metadata/android/en-/images/phoneScreenshots[0m
DEBUG [2017-03-31 11:19:55.66]: Ending screenshot count is: 5
INFO [2017-03-31 11:19:55.66]: [32mCaptured 5 screenshots! 📷✨[0m
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

    desc "Make screenshots"
    lane :screens do
        # Screens are made in developDebug flavor
        gradle(task: "assembleDevelopDebug assembleDevelopDebugAndroidTest")
        screengrab
    end

    desc "Submit AutoDeployed version to Fabric"
    lane :fabric_autodeploy do |options|
        gradle(task: "assembleAutodeployRelease")
        fabric(name: options[:name])
    end

    desc "Submit Development version to Fabric"
    lane :fabric_test do
        gradle(task: "assembleDevelopRelease")
        fabric(name: "Android Develop WhiteLabel")
    end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.24.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| faraday                   | 0.11.0       |
| faraday_middleware        | 0.11.0.1     |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| public_suffix             | 2.0.5        |
| claide                    | 1.0.1        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| bundler                   | 1.14.3       |
| unicode-display_width     | 1.1.3        |
</details>

**Comment by mfurtak** [comment]
Hi @Edwhis - thanks for the report 👍 

There is some truly puzzling stuff in your output. Here's a portion of mine:

```
[08:23:30]: Running tests for locale: da-DK
[08:23:30]: $ adb -s emulator-5554 shell am instrument --no-window-animation -w \
-e testLocale da_DK \
-e endingLocale en_US \
tools.fastlane.localetester.test/android.support.test.runner.AndroidJUnitRunner
```

The part that is confusing is that locale strings should always have underscore separators when passed to the test command. The _screengrab_ command-line code enforces this. So, what I would expect is that the line, `Running tests for locale: da-DK` should have a dash in it, but `-e testLocale da_DK` should be converted to an underscore. But in your output I see the exact opposite. Do you have any ideas how that could be? Have you modified the _screengrab_ code locally while trying to debug?

**Comment by Edwhis** [comment]
@mfurtak Ups, sorry, that was a little experiment with locales and pasted wrong log. Now, I updated it to correct one and it is same as yours.

**Comment by mfurtak** [comment]
Can you tell me about the device you are running this on? Is it an emulator, or a real device? What OS version? What are the locale settings on the device right now?

**Comment by Edwhis** [comment]
Tried on emulators with API 19, 22 and 25, but not tried on the real device.

**Comment by mfurtak** [comment]
OK, thanks. 👍  Do you mind showing me the test class that you're using?

**Comment by Edwhis** [comment]
This is one of the tests which does only one screen. Others tests setup is identical, just with more clicking steps.

```
`@RunWith(AndroidJUnit4.class)
public class Test3_CheckoutGrab {

    @ClassRule
    public static final LocaleTestRule localeTestRule = new LocaleTestRule();

    @Rule
    public ActivityTestRule<OrderActivity> activityRule = new ActivityTestRule<OrderActivity>(OrderActivity.class);


    @BeforeClass
    public static void beforeClass() {
        IdlingPolicies.setMasterPolicyTimeout(600, TimeUnit.SECONDS);
        IdlingPolicies.setIdlingResourceTimeout(600, TimeUnit.SECONDS);
    }


    @Before
    public void setUp(){
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());
        }
        activityRule.getActivity();
        LocaleUtil.changeDeviceLocaleTo(LocaleUtil.getTestLocale());
    }

    @After
    public void tearDown(){
        LocaleUtil.changeDeviceLocaleTo(LocaleUtil.getEndingLocale());
    }

    @Test
    public void grabCheckoutScreen() throws InterruptedException {
        Helper.unlockScreen(activityRule.getActivity());
        try {
            //Closes "No Google Play services" dialog
            onView(withText("OK")).perform(click());
        } catch (Exception e){
            Log.d("CheckoutGrab", "No Google Play services error was thrown");
        }

        //removes focus from back button
        onView(withId(android.R.id.content)).perform(ViewActions.swipeDown());
        Screengrab.screenshot("5_checkout");

    }


}`
```

**Comment by mfurtak** [comment]
Great, thanks! Could you give the following a try:

Move

```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());
}
```

into your `@BeforeClass` method. That should only need to happen once.

Remove your calls to `LocaleUtil.changeDeviceLocaleTo` - those should be handled automatically by the `LocaleTestRule`.

Then, run again and see what happens! 🚀

**Comment by mfurtak** [comment]
Hm, can you share the version of the Screengrab Java library you are using? Thanks!

**Comment by Edwhis** [comment]
I am using **v1.0.2.**

**Comment by Edwhis** [comment]
I am using **v1.0.2**

**Comment by mfurtak** [comment]
No worries!

When you are running the tests, can you see output for the `LocaleUtil` tag in logcat? Could you share that output?

**Comment by Edwhis** [comment]
LogCat output:

```
04-04 09:43:42.265 4240-4265/? D/LocaleUtil: Locale changed to da_DK
04-04 09:43:48.007 4240-4265/com.app.develop D/LocaleUtil: Locale changed to da_DK
04-04 09:43:48.009 4240-4265/com.app.develop D/LocaleUtil: Locale changed to da_DK
04-04 09:44:04.951 4240-4265/com.app.develop D/LocaleUtil: Locale changed to da_DK
04-04 09:44:04.954 4240-4265/com.app.develop D/LocaleUtil: Locale changed to da_DK
04-04 09:44:06.108 4240-4265/com.app.develop D/LocaleUtil: Locale changed to da_DK
```

**Comment by mfurtak** [comment]
Those locales look like they are getting in just fine. How about log info from the `Screengrab` tag in general? Could you share that?

**Comment by Edwhis** [comment]
Sorry, for not responding so long. Here's my log:

```
04-24 14:12:13.680 7264-7291/com.app.develop D/Screengrab: Using screenshot storage directory: /storage/emulated/0/com.app.develop/screengrab/en-/images/screenshots
04-24 14:12:14.716 7264-7291/com.app.develop D/Screengrab: Captured screenshot "1_screen_1493032333680.png"
04-24 14:12:21.114 7264-7291/com.app.develop D/Screengrab: Using screenshot storage directory: /storage/emulated/0/com.app.develop/screengrab/en-/images/screenshots
04-24 14:12:21.482 7264-7291/com.app.develop D/Screengrab: Captured screenshot "2_menu_1493032341114.png"
04-24 14:12:25.878 7264-7291/com.app.develop D/Screengrab: Using screenshot storage directory: /storage/emulated/0/com.app.develop/screengrab/en-/images/screenshots
04-24 14:12:26.266 7264-7291/com.app.develop D/Screengrab: Captured screenshot "3_expanded_1493032345878.png"
04-24 14:12:31.333 7264-7291/com.app.develop D/Screengrab: Using screenshot storage directory: /storage/emulated/0/com.app.develop/screengrab/en-/images/screenshots
04-24 14:12:31.910 7264-7291/com.app.develop D/Screengrab: Captured screenshot "4_screen_1493032351333.png"
04-24 14:12:33.437 7264-7291/com.app.develop D/Screengrab: Using screenshot storage directory: /storage/emulated/0/com.app.develop/screengrab/en-/images/screenshots
04-24 14:12:33.660 7264-7291/com.app.develop D/Screengrab: Captured screenshot "5_last_1493032353437.png"
```

**Comment by Edwhis** [comment]
Any news ?

**Comment by KrauseFx** [comment]
Hey @Edwhis, is this related to https://github.com/fastlane/fastlane/issues/9094?

**Comment by Edwhis** [comment]
@KrauseFx  I think, it could be, but not 100% sure.

**Comment by Edwhis** [comment]
Updated screengrab to the newest version - still the same.
