### ISSUE TITLE
Screengrab unable to create output dir on Android N devices

### ISSUE THREAD

**Issue by dasebasto** [fastlane/fastlane#8727]
### Issue Description

When using UIAutomator mode to take screenshots on several Android N devices (running 7.0.0 and 7.1.1), I get an exception:

**E/Screengrab: Failed to initialize directory: /storage/emulated/0/com.myapp/screengrab/en-US/images/screenshots
java.io.IOException: Unable to create output dir: /storage/emulated/0/com.myapp**
  at tools.fastlane.screengrab.FileWritingScreenshotCallback.createPathTo(FileWritingScreenshotCallback.java:116)

[...]
and right after:
I/TestRunner: java.lang.RuntimeException: Unable to capture screenshot.
at tools.fastlane.screengrab.FileWritingScreenshotCallback.screenshotCaptured(FileWritingScreenshotCallback.java:56)
[...]
Caused by: java.io.IOException: Unable to get a screenshot storage directory
at tools.fastlane.screengrab.FileWritingScreenshotCallback.getFilesDirectory(FileWritingScreenshotCallback.java:81)                                                                             

My instrumentation test:
`Screengrab.setDefaultScreenshotStrategy(new UiAutomatorScreenshotStrategy());
 Screengrab.screenshot("welcome");`

My build.gradle:
`androidTestCompile 'tools.fastlane:screengrab:1.0.2'`

The exact same test runs fine on Android 5.1 and 6.0 devices.
(I'm not using the fastlane script at this point as I need to fix this problem first).

**Comment by mfurtak** [comment]
Hi @dasebasto 👋  thanks for the report.

Could you please share the full command-line output from your _screengrab_ run? I'd like to investigate further. 👍

**Comment by dasebasto** [comment]
Hi Michael.

As mentioned earlier, I am not using the command line screengrab in this scenario.
Just an Android test containing a call to `Screengrab.screenshot("welcome")`

Is the the Android dependency screengrab v1.0.2 supposed to be compatible with Android 7.* ?

**Comment by mfurtak** [comment]
Ah, I thought this meant that you were not using _fastlane_ to run a `Fastfile`, but now I see.

The _screengrab_ Java library is not designed to be used without the accompanying command-line library. As part of running the command line tool, permissions are granted for your test runs that should make this work. Android N (7.*) is supported, yes :+1:

If you haven't checked it out already, there's a good getting-started guide here: https://docs.fastlane.tools/getting-started/android/screenshots/

**Comment by dasebasto** [comment]
OK, I see, thanks for the clarification. I have run the same test using the screengrab command, and it works fine (thanks to this, I guess: `adb -s 192.168.1.21:5555 shell pm grant com.myapp android.permission.WRITE_EXTERNAL_STORAGE`)

I still don't understand why the standalone test works on Android 6.0 and fails on Android 7.0.
AFAIK there has been no major change in the permission system with Android 7.0.

**Comment by mfurtak** [comment]
Hey @dasebasto - I think this code segment may answer your question:

https://github.com/fastlane/fastlane/blob/master/screengrab/screengrab-lib/src/main/java/tools.fastlane.screengrab/FileWritingScreenshotCallback.java#L73-L78

Glad you're up and running! 🚀

**Comment by dasebasto** [comment]
Thanks for the high quality support!
