### ISSUE TITLE
Gym archives are placed in hardcoded archive path

### ISSUE THREAD

**Issue by gradha** [fastlane/fastlane#8729]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Originated as a [StackOverflow question](http://stackoverflow.com/questions/43114922/how-can-i-add-fastlane-builds-to-xcodes-archive-organizer/43124229#43124229), archives created by gym are placed under `~/Library/Developer/Xcode/Archives/[date]`. This doesn't work for users who have Xcode configured to a custom archive path, the organizer won't show the fastlane archives.

In the meantime I've resorted to using a symbolic link to the custom path, since I don't want to store `build_path` or `archive_path` values in the git repository specific to this machine.

**Comment by KrauseFx** [comment]
Hey @gradha, that's correct. However _gym_ should still work as expected, it will just not show the archive. The problem is that we couldn't find a way to detect the user's config for the archives. If you know about a CLI option to get that, it would be a great thing to include into _fastlane_.

**Comment by gradha** [comment]
Haven't seen any option either. The path can be obtained running `/usr/libexec/PlistBuddy -c "Print IDECustomDistributionArchivesLocation" ~/Library/Preferences/com.apple.dt.Xcode.plist`. When the user has not configured any the error `Print: Entry, "IDECustomDistributionArchivesLocation", Does Not Exist` is printed instead.

Obviously hacky, I haven't tracked across xcode versions how stable this private setting is.

**Comment by KrauseFx** [comment]
Mh, that looks good. Are you interested in contributing to _fastlane_ to submit a PR with this change? We have some good guides on how to get started: https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md

**Comment by gradha** [comment]
Highly unlikely, I don't grok ruby.

**Comment by KrauseFx** [comment]
Okay, no worries. Maybe someone else is interested in putting up a PR for this change 👍

**Comment by KrauseFx** [comment]
We're working on this now 👍
