### ISSUE TITLE
snapshots cannot open `snapshot-launch_arguments.txt`

### ISSUE THREAD

**Issue by afh** [fastlane/fastlane#8733]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### 🐞 Issue Description
When running `bundle exec fastlane ios screenshots` the following can be observed in the console:
```
2017-03-31 17:29:14.396 XCTRunner[80950:258525] CFURLCopyResourcePropertyForKey failed because it was passed an URL which has no scheme
Couldn't detect/set launch_arguments due to Error Domain=NSCocoaErrorDomain Code=256 "The file “snapshot-launch_arguments.txt” couldn’t be opened." UserInfo={NSURL=~/Library/Caches/tools.fastlane/snapshot-launch_arguments.txt}
```

Note that the error is only visible if `SnapshotHelper.swift:setLaunchArguments()` ([L88](https://github.com/fastlane/fastlane/blob/master/snapshot/lib/assets/SnapshotHelper.swift#L88)) is:
```
print("Couldn't detect/set launch_arguments due to \(error)")
```

### 🚑 Possible Workaround

`SnapshotHelper.swift:pathPrefix()` ([L148](https://github.com/fastlane/fastlane/blob/master/snapshot/lib/assets/SnapshotHelper.swift#L148))
```
homeDir = URL(fileURLWithPath: homeDirUrl.absoluteString)
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | 10.12.4                                                         |
| Ruby                        | 2.0.0                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.12.2                                              |
| Installation Source         | ~/Work/REDACTED/vendor/bundle/ruby/2.0.0/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib  |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                     |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version               | 8.3                                                             |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.7.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Create new screenshots to verify the Link iOS flow"
  desc "Additionally, this will add device frames around the screenshots"
  lane :screenshots do
    snapshot
    frameit(white: true, path: './screenshots')
  end

 #desc "Runs all the tests"
 #lane :test do
 #  scan
 #end

 #desc "Submit a new Beta Build to Apple TestFlight"
 #desc "This will also make sure the profile is up to date"
 #lane :beta do
 #  # match(type: "appstore") # more information: https://codesigning.guide
 #  gym # Build your app - more options available
 #  pilot

 #  # sh "your_script.sh"
 #  # You can also use other beta testing services here (run `fastlane actions`)
 #end

 #desc "Deploy a new version to the App Store"
 #lane :release do
 #  # match(type: "appstore")
 #  # snapshot
 #  gym # Build your app - more options available
 #  deliver(force: true)
 #  # frameit
 #end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDACTED" # The bundle identifier of your app
apple_id "REDACTED" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.24.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.14.6       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-03-31**
</details>

**Comment by asfalcone** [comment]
Is https://github.com/fastlane/fastlane/pull/8755 related to this issue?

**Comment by afh** [comment]
@asfalcone Thanks for making the connection. Yes, it appears that this issue and #8755 are related.

**Comment by wryphonedev** [comment]
I have a pr for this issue: [https://github.com/fastlane/fastlane/pull/8791](url)

**Comment by KrauseFx** [comment]
This issue is now resolved with the most recent release, right?
