### ISSUE TITLE
Debugging Steps: "No applicable devices found." issues

### ISSUE THREAD

**Issue by iwasrobbed** [fastlane/fastlane#8737]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

## Debugging Steps for "No applicable devices found."

It's not immediately obvious what this error is or what it's caused by, so hopefully these simple steps will help you find the root cause faster.

### Not just _fastlane_

This error happens to all projects built with `xcodebuild` / `xcrun`, so it's likely not caused by _fastlane_. _fastlane_ might help alleviate it with some env var unsetting / setting or other tricks, but this is an error from the new export APIs that Xcode uses.

### Legacy export API

As of Xcode 8.3, the deprecated / legacy export api (e.g. `use_legacy_build_api`) is removed, so you have to use the latest Xcode export API, which unfortunately still has some issues.

### Misleading errors

The error message, `"No applicable devices found."`, is actually misleading: it's not the real error. Something else is erroring out at a lower level so you'll need to dig in to find out what.

### The archive built successfully, but the export step failed

Typically, your archive will build nicely, and with the correct provisioning profile; you can inspect the `.xcarchive` package to verify the `embedded.mobileprovision` file matches.

What happens is the export step will possibly sign it with a different profile depending on which `export_method` you're choosing (with `development` being the default) and it is during this step that the process will fail.

This allows you to isolate the error to the export step, under most circumstances.

### Dependency on other gems

The export step sometimes fails due to not having these Ruby gems installed and caused many of the old instances of this problem.

- [CFPropertyList](https://github.com/ckruse/CFPropertyList)
- [sqlite3](https://github.com/sparklemotion/sqlite3-ruby)
- [digest](https://rubygems.org/gems/digest)

You can use `$ gem list` to show which gems are installed

### Ruby version

Many of the old instances of this problem were caused by not using `system` Ruby, but this likely won't impact many in the future since _fastlane_ helps ensure your environment is set up properly now.

Using [RVM](https://rvm.io/) or newer versions of Ruby should work fine. If you have RVM installed and want to try reverting back to `system` Ruby just in case, you can set and check this using:

```shell
$ rvm use system
$ ruby -v
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
$ which ruby
/usr/bin/ruby
```

### Check the Logs

In many issues that were seen on the _fastlane_ repo and across the web, this error was given during the bundling process. Luckily, that bundler creates a log file that you can access to see what error *actually* happened:

```shell
2017-03-30 21:47:09.855 xcodebuild[78957:9114437] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/s1/0h7d0scx6xqdthft328yfk0m0000gn/T/MyApp-Internal_2017-03-30_21-47-09.854.xcdistributionlogs'.
1.2.840.113635.100.1.61
1.2.840.113635.100.1.61
2017-03-30 21:47:14.702 xcodebuild[78957:9114437] [MT] IDEDistribution: Step failed: <IDEDistributionThinningStep: 0x7fc3218d0b60>: Error Domain=IDEDistributionErrorDomain Code=14 "No applicable devices found." UserInfo={NSLocalizedDescription=No applicable devices found.}
error: exportArchive: No applicable devices found.
```

If you look closely, you'll see the misleading error message and then just above it, there's a path to a log file (`*.xcdistributionlogs`). Opening that up, you'll see more detail. (Side note: you can also search for all logs via `$ sudo find /private/var -name "*.xcdistributionlogs"`)

In this case, it was because the export was built _without_ bitcode, but there were static lib frameworks that were built _with_ bitcode:

```shell
# inside IDEDistribution.standard.log within the .xcdistributionlogs file
2017-03-31 16:49:06 +0000  Validating IPA structure...
2017-03-31 16:49:06 +0000  error: Failed to verify bitcode in opus.framework/opus:
error: Bundle only contains bitcode-marker /var/folders/s1/0h7d0scx6xqdthft328yfk0m0000gn/T/IDEDistributionThinningStep.KRt/Payload/Viv.app/Frameworks/opus.framework/opus (armv7)
```

When that framework was rebuilt without bitcode, it worked like a charm! 😅 

### Run commands yourself

_gym_ does a great job of showing which commands it's going to run. Inspect the files it generates and run these commands yourself, as many times as you need to, in order to isolate the problems.

For example, here's the export command that _gym_ shows:

```shell
/usr/bin/xcrun /Users/rob/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.24.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/s1/0h7d0scx6xqdthft328yfk0m0000gn/T/gym_config20170330-65021-1xbw0ov.plist' -archivePath /Users/rob/Library/Developer/Xcode/Archives/2017-03-30/MyApp\ 2017-03-30\ 21.12.02.xcarchive -exportPath '/var/folders/s1/0h7d0scx6xqdthft328yfk0m0000gn/T/gym_output20170330-65021-u80ojn'
```

From that, you can see which `exportOptionsPlist` it's using, which had this in it:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>method</key>
	<string>development</string>
</dict>
</plist>
```

And you can see which `.xcarchive` it's using to check if it built that with the correct provisioning profile.

Most importantly, you can keep running that entire command until you figure out why it's breaking (e.g. try installing these gems, try using system Ruby).

### Other Causes

Keep in mind, this list could be infinite since this `No applicable devices found` error just manifests itself from underlying errors. Your best bet is to dig into the logs and see which error is actually being thrown.

- Using the wrong `export_method` or some other error in the generated `exportPlist` (e.g. using `enterprise` method when you're actually building for the `app store` and don't have the proper certificates)
- Root Apple WWDR certificate had expired; check the Keychain for expired certificates
- Env vars not being unset, [relevant PR](https://github.com/fastlane-old/gym/pull/176)
- Including bitcode sometimes caused it (can use `include_bitcode: false`) in your _gym_ command and check if all frameworks match your bitcode requirements
- Provisioning profiles not matching capabilities and beta-reports-active flag on .entitlements file.
- Not having the gems (`CFPropertyList` etc) we discussed earlier installed 

### Apple Tech Notes

If all else fails, use these tech notes to troubleshoot app thinning and bitcode: 

- [https://developer.apple.com/library/content/technotes/tn2432/_index.html](https://developer.apple.com/library/content/technotes/tn2432/_index.html)
- [https://stackoverflow.com/questions/34959767/whats-the-difference-between-fembed-bitcode-and-bitcode-generation-mode](https://stackoverflow.com/questions/34959767/whats-the-difference-between-fembed-bitcode-and-bitcode-generation-mode)
- [https://forums.developer.apple.com/thread/70583](https://forums.developer.apple.com/thread/70583)

### Radar

Feel free to duplicate the radar we filed [https://openradar.appspot.com/31389725](https://openradar.appspot.com/31389725) so the export APIs will return an accurate error message

### Related Issues & Helpful Info

You'll find a lot of breadcrumbs from other people on these issues (thanks to you all)

- https://github.com/fastlane/fastlane/issues/3193
- https://github.com/fastlane/fastlane/issues/6495
- https://github.com/fastlane/fastlane/issues/7655
- https://github.com/fastlane/fastlane/issues/6769
- https://github.com/fastlane/fastlane/issues/6223
- https://github.com/fastlane/fastlane/issues/3184
- https://github.com/fastlane/fastlane/issues/7625
- https://github.com/fastlane/fastlane/issues/3150
- https://github.com/fastlane/fastlane/issues/7679
- https://github.com/fastlane/fastlane/issues/8549
- https://github.com/fastlane/fastlane/issues/5358
- https://github.com/fastlane/fastlane/issues/6310
- https://github.com/fastlane/fastlane/issues/6277
- https://github.com/fastlane/fastlane/issues/3178
- https://github.com/fastlane/fastlane/issues/6458
- https://github.com/fastlane/fastlane/issues/950
- https://stackoverflow.com/questions/39634404/xcodebuild-exportarchive-no-applicable-devices-found
- https://github.com/fastlane-old/gym/pull/176

**Comment by iwasrobbed** [comment]
Opened a docs PR with this information as well: https://github.com/fastlane/docs/pull/320

**Comment by avnerbarr** [comment]
I am having the same problem. I'm not using fastlane but building directly:

` xcodebuild -exportArchive -archivePath /tmp/public_1.46.0.1_production.xcarchive -exportPath /tmp/1491306445_gen_ipa -exportOptionsPlist ./export.plist -verbose`


I see in one of the log files:

`Failed to verify bitcode in MyFramework.framework/InsertFramework:`

But the framework does seem to contain bitcode 

(I verified the bitcode directly from the xcarchive:)

```

otool -l -arch arm64 /tmp/public_1.46.0.1_production.xcarchive/Products/Applications/App.app/Frameworks/MyFramework.framework/MyFramework  | grep __LL
  segname __LLVM
   segname __LLVM

```

Any ideas what to do about that?

**Comment by iwasrobbed** [comment]
@avnerbarr It's probably best to open an issue on StackOverflow to keep this conversation about how this relates to fastlane only, otherwise this will quickly get off topic for all the various ways this error can manifest itself. You seem to have the error source, so I'm sure someone can help you with the next step there.

**Comment by soharu** [comment]
@avnerbarr In my case, the fastlane build failed with the same error when I embedded the framework with `ENABLE_BITCODE=YES` in the app with the `ENABLE_BITCODE=NO`.

I think the `ENABLE_BITCODE` setting of the framework and the app should be the same, so the error does not seem to happen. My problem has been resolved by applying the framework with the option turned off. I hope it helps.

**Comment by luisrecuenco** [comment]
We were having the same issue until Xcode 8.3.2, that fixed it completely for us.

**Comment by ohayon** [comment]
Going to close this as it looks like that awesome docs PR was merged. Thanks for making that happen @iwasrobbed !! 🚀
