### ISSUE TITLE
gym -  module compiled with Swift 3.1 cannot be imported in Swift 3.0

### ISSUE THREAD

**Issue by yageek** [fastlane/fastlane#8741]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After moving to Xcode8.3, impossible to compile the project. I have this issue:
```
module compiled with Swift 3.1 cannot be imported in Swift 3.0
```
Using manual archive on Xcode is working.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.2.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_CH.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.18.3"
xcversion(version: "8.3")

default_platform :ios

platform :ios do
#before_all do
#   carthage(platform: "iOS", use_binaries: false)
# end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do

    # match(type: "appstore") # more information: https://codesigning.guide
    cert
    sigh
    gym(scheme: "iOSApp",
        include_symbols: true,
        include_bitcode: true)
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot

    gym(scheme: "iOSApp") # Build your app - more options available
    deliver(force: true)
    # frameit   
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.24.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
| xcode-install             | 2.1.1        |
</details>

*generated on:* **2017-04-01**
</details>

**Comment by hjanuschka** [comment]
@yageek can you try cleaning out your derrived data? or setting an explicit value to gym - so it does not reuse any older files?


like:


```
gym(derived_data_path: "some_temp_folder")
```

let me know if this helps.

**Comment by yageek** [comment]
After cleaning the DerivedData I have the same error. The same by specifying a temporary directory.

**Comment by hjanuschka** [comment]
@yageek do you have any 3rd party binary framework in your project which may be compiled 3.0?


also make sure that all of your targets, have the same swift version set

<img width="883" alt="bildschirmfoto 2017-04-05 um 09 44 45" src="https://cloud.githubusercontent.com/assets/2891702/24695070/9bcc99c6-19e4-11e7-875d-def44bc65f13.png">

**Comment by yageek** [comment]
I checked every dependencies and they all have the same `SWIT_VERSION`.

I tried also by using a `.xcconfig` to specify the swift version for the whole project and force the version to `3.0.1` and I have the same issue.

**Comment by mgrebenets** [comment]
@yageek 

Do you have multiple versions of Xcode installed by any chance?

What's the output of `xcodebuild -version` and `swift --version` when you run these commands in terminal?

We had similar issue with `2.3` to `3.0` migration.
But in our case, the issue was happening during Xcode archiving phase, not while compiling and linking the app. We would first build the app with `2.3` and then would try to package it with Swift `3.0` standard libraries.

Another possible reason is that you have a 3rd party framework/cocoapod which is pre-built and is distributed as a binary. Anything like that? Then Xcode would have to link binaries built with `3.0` and `3.1` together, which wouldn't work and may explain your error message. `3.0` and `3.1` are source compatible, but _not_ ABI compatible.

In any case, I find that it helps to provide an exact toolchain name to `gym` command. This way you are 100% sure that both building and archiving the app are using same toolchain. Specifying `nil` is same as specifying default keychain.

```ruby
gym(
 ...
  toochain: nil
)
```

I may have missed, but are you using `gym` to build the project?

**Comment by yageek** [comment]
I updated both fastlane and Xcode (fastlane 2.37.0 and Xcode 8.3.3 and everything is working now.
