### ISSUE TITLE
Can Deliver/Fabric upload an existing archive?

### ISSUE THREAD

**Issue by pabloromeu** [fastlane/fastlane#8742]
### New Question Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Question Description

As compiling some project can be extremely slow, It may be useful if deliver/fabric could use an Xcode Archive and upload it. I have not found a method of doing this, if there is any available.

**Comment by pabloromeu** [comment]
Xcarchives include binary IPAs. Deliver/Fabric just have to sign it and upload it. It would be really useful so of an upload fails for any reason you do not have to recompile the full App to try again.

**Comment by hjanuschka** [comment]
both support uploading ipa's - maybe splitting your fastlane into a couple of lanes - and keeping the ipa is an option - or do you need it to be signed differently - maybe `resign` is a option then?

**Comment by pabloromeu** [comment]
@hjanuschka I usually have signing problems (multiple accounts and ids) so, is resign and deliver the binary IPA an option?

**Comment by ohayon** [comment]
@pabloromeu you should be able to resign using the `resign` action. Let us know if that works out for you! 🚀  🐙

**Comment by pabloromeu** [comment]
Yes, it does. Thanks!
