### ISSUE TITLE
[Regression] Snapshot doesn't work with Xcode 7.3.1 (w/ workaround)

### ISSUE THREAD

**Issue by bencollier** [fastlane/fastlane#8749]
### New Issue Checklist

- [🚀] Updated fastlane to the latest version
- [🚀] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
The Swift syntax of SnapshotHelper.swift has been upgraded to the newer Swift language, which breaks compatibility with older versions of Xcode (7.3.1.).

This would be fine but the snapshot command fails if you're using an older version of the SnapshotHelper.swift.

### Workaround 
Manually changing the `// SnapshotHelperVersion [1.x]` to 1.3, but with the 1.2 helper syntax bypasses the check and the screenshots run.

### Suggested Fix
If an older version of Xcode is being used don't say the 1.2 Snapshot helper is out of date which currently fails the build.

Appreciate that Xcode 7.3.1 won't work forever with snapshot - but it'd be nice to have this one fixed in the core.

**Comment by bencollier** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.4                                           |
| Ruby                        | 2.3.0                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.7.4 (Apple Git-66)                  |
| Installation Source         | ~/.rbenv/versions/2.3.0/bin/fastlane              |
| Host                        | Mac OS X 10.12.4 (16E195)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.0/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                        |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-7.3.1.app/Contents/Developer/ |
| Xcode Version               | 7.3.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.24.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.8.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-04-03**
</details>

**Comment by hjanuschka** [comment]
@bencollier checkout this PR: https://github.com/fastlane/fastlane/pull/8751 - setting `skip_helper_version_check`  should ignore the version check of the SwiftHelper - can you give it a try?

**Comment by bencollier** [comment]
Installed and working a treat - thanks for the _swift_ fix!

**Comment by ohayon** [comment]
![image](https://cloud.githubusercontent.com/assets/2587018/24616062/0ecdc072-185e-11e7-8648-0167b3a8a79f.png)

**Comment by hjanuschka** [comment]
https://github.com/fastlane/fastlane/pull/8751 is merged.

i thought posting memes is a thing of the past? 👍 
![image](https://cloud.githubusercontent.com/assets/2891702/24616431/5bbbfe70-1891-11e7-9159-e6049e7f62ea.png)

**Comment by ohayon** [comment]
It is a thing of the past! My bad! The pun just got the better of me!

**Comment by hjanuschka** [comment]
![image](https://cloud.githubusercontent.com/assets/2891702/24616785/62f7ce98-1892-11e7-8077-8ec8006b069d.png)

i am still for the return of the meme's 😆
