### ISSUE TITLE
Is there a way to delete certificates/profiles from a specific bundle id from match?

### ISSUE THREAD

**Issue by jlubeck** [fastlane/fastlane#8756]
Someone on my team deleted an AppID directly from the developer portal, and now I need to recreate it. But the old profiles don't seem to work with the new ID. 

Fastlane is telling me that "To reset the provisioning profiles of your Apple account, you can use the `fastlane match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match"

But doesn't nuke delete all the certificates/profiles from the account? I don't want to nuke them all (I have a lot!) just this single one.

Thanks

**Comment by jlubeck** [comment]
There is no output because I haven't ran anything yet :D

**Comment by hjanuschka** [comment]
are you using match, if so you can try deleting the profiles from the git repo - than it should recreate them - without requiring you to nuke your account ( i dont like nuking mine too 👍 )

**Comment by jlubeck** [comment]
Yes, I'm using match. I'm going to try to do what you say. It would be nice for match to have a command to delete the certificates from the repo, so that I don't have to go clone the repo, and do things manually.

**Comment by jlubeck** [comment]
What @hjanuschka said worked fine. I'm leaving this open as a feature request to have a command for match to delete certificates on demand. Something like

`fastlane match -a com.bundle.name --delete `

Or similar. But feel free to close it if it's not a option. 

Thanks!
