### ISSUE TITLE
Automate recording video using Snapshot?

### ISSUE THREAD

**Issue by CraigSiemens** [fastlane/fastlane#8759]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
As of Xcode 8.2, the simulator has added support for recording video using `xcrun simctl io booted recordVideo <filename>.<file extension>`

It would be great if snapshot could be used to record videos. Combined with using UITests to automate input, this would make it easy to create App Preview or training videos.

**Comment by KrauseFx** [comment]
Hey @CraigSiemens, sorry for not coming back earlier - this is a great idea, I'd love it if _snapshot_ could generate app videos for you

**Comment by laullon** [comment]
I would like to take a shot on implementing this, is it possible?

**Comment by KrauseFx** [comment]
Yeah, that would be awesome, happy to review & merge a pull request adding this functionality. Check out our [contributing.md](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md) docs with instructions on how to get the development environment up and running 👍

**Comment by laullon** [comment]
ok, working on it ;)

**Comment by laullon** [comment]
I just made a basic implementation:

https://github.com/laullon/fastlane/commit/413df988bb06e71e1573ba33ee98ee32e1c263d0

Can you take a quick look?
I still need to do some work and tests.

**Comment by KrauseFx** [comment]
Hey that's great, do you think we can do that without adding another dependency to _fastlane_?

**Comment by laullon** [comment]
sure
