### ISSUE TITLE
slather action fails to install gem

### ISSUE THREAD

**Issue by stonedauwg** [fastlane/fastlane#8760]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Ran slather action for first time today and when fastlane tries to install the gem it fails. Looking at the mkmf.log, referred to in the fastlane error below, it shows this:

In file included from conftest.c:1:
In file included from /Users/mstoner/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/mstoner/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/mstoner/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.

Appears that it can't find stdio.h when building the nokogiri gem dependency. I am able to use the system slather gem ("install gem slather") from non-fastlane scripts perfectly fine. I have already installed the XCode command line tools, rebooted and tried running the fastlane command as sudo, none of which got around the error. Where should nokogiri be looking for stdio.h?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `lint`
<details><summary>Output/Log</summary>

```

DEBUG [2017-04-03 13:43:02.68]: Checking if there are any plugins that should be loaded...
DEBUG [2017-04-03 13:43:02.76]: Loading 'fastlane-plugin-settings_bundle' plugin
INFO [2017-04-03 13:43:02.89]: gem 'fastlane-plugin-settings_bundle' is already installed
+---------------------------------+---------+------------------------+
|                            Used plugins                            |
+---------------------------------+---------+------------------------+
| Plugin                          | Version | Action                 |
+---------------------------------+---------+------------------------+
| fastlane-plugin-settings_bundle | 1.0.0   | update_settings_bundle |
+---------------------------------+---------+------------------------+

INFO [2017-04-03 13:43:02.94]: -------------------------------------------------
INFO [2017-04-03 13:43:02.94]: --- Step: Verifying required fastlane version ---
INFO [2017-04-03 13:43:02.94]: -------------------------------------------------
INFO [2017-04-03 13:43:02.94]: Your fastlane version 2.24.0 matches the minimum requirement of 2.18.3  ✅
INFO [2017-04-03 13:43:02.94]: ------------------------------
INFO [2017-04-03 13:43:02.94]: --- Step: default_platform ---
INFO [2017-04-03 13:43:02.94]: ------------------------------
INFO [2017-04-03 13:43:02.95]: Driving the lane 'ios lint' 🚀
INFO [2017-04-03 13:43:02.96]: ---------------------
INFO [2017-04-03 13:43:02.96]: --- Step: slather ---
INFO [2017-04-03 13:43:02.96]: ---------------------
WARN [2017-04-03 13:43:03.23]: Installing Ruby gem 'slather'...
WARN [2017-04-03 13:43:26.11]: Lane Context:
INFO [2017-04-03 13:43:26.11]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios lint"}
ERROR [2017-04-03 13:43:26.11]: ERROR: Failed to build gem native extension.

    current directory: /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1/ext/nokogiri
/Users/mstoner/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170403-1887-1wdq3p0.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/mstoner/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:522:in `with_werror'
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:619:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:406:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1 for inspection.
Results logged to /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.7.1/gem_make.out


+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | slather                             | 23          |
+------+-------------------------------------+-------------+

DEBUG [2017-04-03 13:43:26.13]: All plugins are up to date
ERROR [2017-04-03 13:43:26.13]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: ERROR: Failed to build gem native extension.

    current directory: /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1/ext/nokogiri
/Users/mstoner/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170403-1887-1wdq3p0.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/mstoner/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:522:in `with_werror'
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:619:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:406:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.7.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1 for inspection.
Results logged to /Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.7.1/gem_make.out

URL: https://api.github.com/search/issues?q=ERROR:%20Failed%20to%20build%20gem%20native%20extension.%0A%0A%20%20%20%20current%20directory:%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1/ext/nokogiri%0A/Users/mstoner/.fastlane/bin/bundle/bin/ruby%20-r%20./siteconf20170403-1887-1wdq3p0.rb%20extconf.rb%0Achecking%20if%20the%20C%20compiler%20accepts%20...%20***%20extconf.rb%20failed%20***%0ACould%20not%20create%20Makefile%20due%20to%20some%20reason,%20probably%20lack%20of%20necessary%0Alibraries%20and/or%20headers.%20%20Check%20the%20mkmf.log%20file%20for%20more%20details.%20%20You%20may%0Aneed%20configuration%20options.%0A%0AProvided%20configuration%20options:%0A%09--with-opt-dir%0A%09--without-opt-dir%0A%09--with-opt-include%0A%09--without-opt-include=$%7Bopt-dir%7D/include%0A%09--with-opt-lib%0A%09--without-opt-lib=$%7Bopt-dir%7D/lib%0A%09--with-make-prog%0A%09--without-make-prog%0A%09--srcdir=.%0A%09--curdir%0A%09--ruby=/Users/mstoner/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)%0A%09--help%0A%09--clean%0A/Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in%20%60try_do':%20The%20compiler%20failed%20to%20generate%20an%20executable%20file.%20(RuntimeError)%0AYou%20have%20to%20install%20development%20tools%20first.%0A%09from%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in%20%60block%20in%20try_compile'%0A%09from%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:522:in%20%60with_werror'%0A%09from%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in%20%60try_compile'%0A%09from%20extconf.rb:138:in%20%60nokogiri_try_compile'%0A%09from%20extconf.rb:162:in%20%60block%20in%20add_cflags'%0A%09from%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:619:in%20%60with_cflags'%0A%09from%20extconf.rb:161:in%20%60add_cflags'%0A%09from%20extconf.rb:406:in%20%60%3Cmain%3E'%0A%0ATo%20see%20why%20this%20extension%20failed%20to%20compile,%20please%20check%20the%20mkmf.log%20which%20can%20be%20found%20here:%0A%0A%20%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.7.1/mkmf.log%0A%0Aextconf%20failed,%20exit%20code%201%0A%0AGem%20files%20will%20remain%20installed%20in%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.7.1%20for%20inspection.%0AResults%20logged%20to%20/Users/mstoner/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.7.1/gem_make.out%0A+repo:fastlane/fastlane
ERROR [2017-04-03 13:43:26.37]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
DEBUG [2017-04-03 13:43:26.37]: All plugins are up to date


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import "../../Fastfile_master"

#platform :ios do
  ############################################### Lane Overrides ###############################################
  #override_lane :masterlane do |lane, options|
  #end
#end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.24.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-settings_bundle | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| slack-notifier                  | 1.5.1        |
| i18n                            | 0.7.0        |
| json                            | 1.8.1        |
| thread_safe                     | 0.3.5        |
| tzinfo                          | 1.2.2        |
| minitest                        | 5.4.3        |
| activesupport                   | 4.2.7.1      |
| CFPropertyList                  | 2.3.4        |
| claide                          | 1.0.1        |
| colored                         | 1.2          |
| nanaimo                         | 0.2.3        |
| xcodeproj                       | 1.4.2        |
| rouge                           | 1.11.1       |
| xcpretty                        | 0.2.4        |
| terminal-notifier               | 1.7.1        |
| unicode-display_width           | 1.1.3        |
| terminal-table                  | 1.7.3        |
| plist                           | 3.2.0        |
| public_suffix                   | 2.0.5        |
| addressable                     | 2.5.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.5.0        |
| babosa                          | 1.0.2        |
| highline                        | 1.7.8        |
| commander-fastlane              | 4.4.4        |
| excon                           | 0.54.0       |
| faraday                         | 0.11.0       |
| unf_ext                         | 0.0.7.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20161129 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.6        |
| fastimage                       | 2.0.1        |
| gh_inspector                    | 1.0.3        |
| uber                            | 0.0.15       |
| representable                   | 2.3.0        |
| retriable                       | 2.1.0        |
| mime-types-data                 | 3.2016.0521  |
| mime-types                      | 3.1          |
| hurley                          | 0.2          |
| little-plugger                  | 1.1.4        |
| multi_json                      | 1.12.1       |
| logging                         | 2.1.0        |
| jwt                             | 1.5.6        |
| memoist                         | 0.15.0       |
| os                              | 0.9.6        |
| signet                          | 0.7.3        |
| googleauth                      | 0.5.1        |
| httpclient                      | 2.8.3        |
| google-api-client               | 0.9.22       |
| mini_magick                     | 4.5.1        |
| multi_xml                       | 0.6.0        |
| rubyzip                         | 1.2.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 0.0.4        |
| dotenv                          | 2.1.2        |
| bundler                         | 1.13.7       |
| faraday_middleware              | 0.11.0       |
| fastlane-plugin-settings_bundle | 1.0.0        |
| psych                           | 2.0.8        |
</details>

*generated on:* **2017-04-03**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import "../../Fastfile_master"

#platform :ios do
  ############################################### Lane Overrides ###############################################
  #override_lane :masterlane do |lane, options|
  #end
#end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.24.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                          | Version | Update-Status |
| ------------------------------- | ------- | ------------- |
| fastlane-plugin-settings_bundle | 1.0.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| slack-notifier                  | 1.5.1        |
| i18n                            | 0.7.0        |
| json                            | 1.8.1        |
| thread_safe                     | 0.3.5        |
| tzinfo                          | 1.2.2        |
| minitest                        | 5.4.3        |
| activesupport                   | 4.2.7.1      |
| CFPropertyList                  | 2.3.4        |
| claide                          | 1.0.1        |
| colored                         | 1.2          |
| nanaimo                         | 0.2.3        |
| xcodeproj                       | 1.4.2        |
| rouge                           | 1.11.1       |
| xcpretty                        | 0.2.4        |
| terminal-notifier               | 1.7.1        |
| unicode-display_width           | 1.1.3        |
| terminal-table                  | 1.7.3        |
| plist                           | 3.2.0        |
| public_suffix                   | 2.0.5        |
| addressable                     | 2.5.0        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| tty-screen                      | 0.5.0        |
| babosa                          | 1.0.2        |
| highline                        | 1.7.8        |
| commander-fastlane              | 4.4.4        |
| excon                           | 0.54.0       |
| faraday                         | 0.11.0       |
| unf_ext                         | 0.0.7.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20161129 |
| http-cookie                     | 1.0.3        |
| faraday-cookie_jar              | 0.0.6        |
| fastimage                       | 2.0.1        |
| gh_inspector                    | 1.0.3        |
| uber                            | 0.0.15       |
| representable                   | 2.3.0        |
| retriable                       | 2.1.0        |
| mime-types-data                 | 3.2016.0521  |
| mime-types                      | 3.1          |
| hurley                          | 0.2          |
| little-plugger                  | 1.1.4        |
| multi_json                      | 1.12.1       |
| logging                         | 2.1.0        |
| jwt                             | 1.5.6        |
| memoist                         | 0.15.0       |
| os                              | 0.9.6        |
| signet                          | 0.7.3        |
| googleauth                      | 0.5.1        |
| httpclient                      | 2.8.3        |
| google-api-client               | 0.9.22       |
| mini_magick                     | 4.5.1        |
| multi_xml                       | 0.6.0        |
| rubyzip                         | 1.2.0        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 0.0.4        |
| dotenv                          | 2.1.2        |
| bundler                         | 1.13.7       |
| faraday_middleware              | 0.11.0       |
| fastlane-plugin-settings_bundle | 1.0.0        |
</details>

*generated on:* **2017-04-03**
</details>

**Comment by timritzer** [comment]
I also have this issue when trying to install a gem. Relevant section from the failure log:

clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' [-Wmissing-sysroot]

Which of course is the wrong version of sysroot, I am on 10.12, and *do* have that SDK installed.

**Comment by ethanjdiamond** [comment]
I had an issue very similar to this, which I think was caused by fastlane's bin folder being out of sync or something. To fix it, I installed fastlane as a gem instead of through homebrew.

1. brew uninstall fastlane
2. rm -rf /Users/[User]/.fastlane
3. sudo gem install fastlane

Hope that works for you.
