### ISSUE TITLE
Custom Match Provisioning Profile Name?

### ISSUE THREAD

**Issue by iamchairs** [fastlane/fastlane#8761]
We currently are naming out provisioning profiles "{appIdentifier} Store", but match is not recognizing these and creating "match AppStore {appIdentifier}".

Quick question.

How do I supply a custom provisioning profile name?

**Comment by johnknapprs** [comment]
Match does not support that functionality.  Please read the code-signing guide in the bot's link above to understand xcode project setup and fastlane.

**Comment by PetrosIchor** [comment]
Match does not support that functionality.  Please read the code-signing guide in the bot's link above to understand xcode project setup and fastlane.
