### ISSUE TITLE
[snapshot] launch_arguments per language/locale/device

### ISSUE THREAD

**Issue by marcelofabri** [fastlane/fastlane#8766]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I think it'd be useful to define `launch_arguments` based on a language/locale/device. So instead of just having an array of values, one could provide a block to it:

```rb
launch_arguments do |language, locale, device|
   name = "Bart"
   name = "El Barto" if language == "es"
   ["-name", name, "-secretFlag"]
end
```

**Comment by wryphonedev** [comment]
I opened a PR for this issue: [https://github.com/fastlane/fastlane/pull/8791](url)

If you look at the change and apply it to your own code it will resolve.

**Comment by KrauseFx** [comment]
This issue is now resolved with the most recent release, right?
