### ISSUE TITLE
Can't submit to crashlytics because of .framework check

### ISSUE THREAD

**Issue by TomCarey** [fastlane/fastlane#877]
There is a line of code in the crashlytics helper that checks that the crashlytics path is Crashlytics.framework
`raise "The crashlytics bundle must be of type .framework" unless params[:crashlytics_path].end_with?(".framework") || Helper.test?`

Unfortunately with the latest version of crashlytics (3.4.1) fastlane spits out an error:
> The submit script is now located at ${PODS_ROOT}/Crashlytics/submit'. To remove this warning, update your path to point to this new location.
> sh: /Crashlytics/submit: No such file or directory

**Comment by addisonwebb** [comment]
+1

fastlane 1.40.0
Crashlytics 3.4.1

**Comment by jshier** [comment]
+1 
I've reverted to Crashlytics 3.4.0 for now. Perhaps someone from Crashlytics should be responsible for updating the action, now that you're all part of the same company?

**Comment by KrauseFx** [comment]
Sorry everyone, I'm working on a fix! :+1:

**Comment by davidrothera** [comment]
:+1:

**Comment by KrauseFx** [comment]
https://github.com/fastlane/fastlane/releases/tag/1.41.1 

Let me know if that works for you :rocket:

**Comment by Sega-Zero** [comment]
Works now, thanks a lot!

**Comment by mobinzk** [comment]
This seems to still be an issue:

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.41.1/lib/fastlane/helper/sh_helper.rb:37:in `sh_no_action': Exit status of command 'Pods/Crashlytics/Crashlytics.framework/submit ...

warning: The submit script is now located at ${PODS_ROOT}/Crashlytics/submit'. To remove this warning, update your path to point to this new location.
sh: /Crashlytics/submit: No such file or directory
```

**Comment by davidrothera** [comment]
@mobinzk Do you have Crashlytics 3.4.1 or higher installed?

**Comment by mobinzk** [comment]
@davidrothera Yes I am using using Crashlytics (3.4.1) and Fastlane (1.41.1)

**Comment by davidrothera** [comment]
What does your repo look like?

```
[drothera@drothera-mbp Crashlytics]$ (develop) pwd
/Users/drothera/Developer/MyApp/Pods/Crashlytics
[drothera@drothera-mbp Crashlytics]$ (develop) tree
.
├── Crashlytics.framework
│   ├── README
│   └── submit
├── iOS
│   └── Crashlytics.framework
│       ├── Crashlytics
│       ├── Headers
│       │   ├── ANSCompatibility.h
│       │   ├── Answers.h
│       │   ├── CLSAttributes.h
│       │   ├── CLSLogging.h
│       │   ├── CLSReport.h
│       │   ├── CLSStackFrame.h
│       │   └── Crashlytics.h
│       ├── Info.plist
│       ├── Modules
│       │   └── module.modulemap
│       ├── run
│       ├── submit
│       └── uploadDSYM
└── submit

5 directories, 16 files
[drothera@drothera-mbp Crashlytics]$ (develop) ls -alh
total 496
drwxr-xr-x   5 drothera  wheel   170B 23 Nov 09:41 .
drwxrwxrwx@ 29 drothera  wheel   986B 29 Nov 21:02 ..
drwxr-xr-x   4 drothera  wheel   136B 23 Nov 09:41 Crashlytics.framework
drwxr-xr-x   3 drothera  wheel   102B 23 Nov 09:41 iOS
-rwxr-xr-x   1 drothera  wheel   245K 23 Nov 09:41 submit
```

**Comment by mobinzk** [comment]
Here it is:
```
User$ tree
.
├── Crashlytics.framework
│   ├── README
│   └── submit
├── iOS
│   └── Crashlytics.framework
│       ├── Crashlytics
│       ├── Headers
│       │   ├── ANSCompatibility.h
│       │   ├── Answers.h
│       │   ├── CLSAttributes.h
│       │   ├── CLSLogging.h
│       │   ├── CLSReport.h
│       │   ├── CLSStackFrame.h
│       │   └── Crashlytics.h
│       ├── Info.plist
│       ├── Modules
│       │   └── module.modulemap
│       ├── run
│       ├── submit
│       └── uploadDSYM
└── submit

5 directories, 16 files
User$ ls -alh
total 496
drwxr-xr-x   5 mobinzk  staff   170B 30 Nov 11:54 .
drwxr-xr-x  16 mobinzk  staff   544B 30 Nov 12:25 ..
drwxr-xr-x   4 mobinzk  staff   136B 30 Nov 11:54 Crashlytics.framework
drwxr-xr-x   3 mobinzk  staff   102B 30 Nov 12:25 iOS
-rwxr-xr-x   1 mobinzk  staff   245K 30 Nov 11:54 submit
```

**Comment by davidrothera** [comment]
I wonder if for some reason the `{PODS_ROOT}` env variable isn't set as it is evaluating that to nothing and then trying to run `/Crashlytics/submit` which correctly doesn't actually exist.

**Comment by mobinzk** [comment]
@davidrothera Thanks for your time, any suggestion how I can check it's been set or not?

**Comment by addisonwebb** [comment]
@mobinzk You can specify the crashlytics path in the fastfile. Make sure that has been updated. Mine looks something like this (I use CocoaPods): `./Pods/Crashlytics/iOS/Crashlytics.framework`

See: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md#crashlytics-beta

**Comment by mobinzk** [comment]
@addisonwebb Many thanks for your answer, that solved my problem :-) :+1:
