### ISSUE TITLE
Enhance importing other Fastfiles

### ISSUE THREAD

**Issue by giginet** [fastlane/fastlane#8773]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Importing multi `AnotherFastfile`s from each Fastfiles.
Loaded lane is duplicated.

```
[!] Lane 'sushi' was defined multiple times!
```
This error occurred 😢 

## Fastfile

```ruby
import "UtilsFastfile"
import "FeatureAFastfile"
import "FeatureBFastfile"

lane :sushi_party do
  a
  b
end
```
## FeatureAFastfile

```ruby
import "UtilsFastfile"

lane :a do
   sushi
end
```

## FeatureBFastfile

```ruby
import "UtilsFastfile"
lane :b do
   sushi
end
```
## UtilsFastfile
```ruby
lane :sushi do
  puts "🍣"
end
```

I want to use "sushi" like utility among all over the Fastfiles.
However, current implementation, it wouldn't be work well.
We should refine importing system.

-------

## Ideal

Ideally, Fastfile enviroment is constructed by multiple Fastfiles like following.

## Fastfile

```ruby
import "SetupFastfile"
import "SubmitFastfile"
```
## SetUpFastfile

```ruby
lane :install do
  cocoapods
end
```
## SubmitFastfile

```ruby
import "SetUpFastfile" # to use install lane
import "UtilsFastfile" # to use sushi lane

lane :submit do
  install # from SetUpFastfile
  gym
  deliver
  sushi # from UtilsFastfile
end
```

**Comment by KrauseFx** [comment]
Interesting, so you want to avoid importing the same file twice, right? Sounds like a good thing to do. How would you do that? 👍
