### ISSUE TITLE
Unable to download app

### ISSUE THREAD

**Issue by RaziPour1993** [fastlane/fastlane#8775]
![430411598_10783386936549520798](https://cloud.githubusercontent.com/assets/16708111/24692476/7b82927e-19ee-11e7-8f34-6d99a6e47c3c.jpg)

How solved?

**Comment by hjanuschka** [comment]
can you provide a bit more information.
are you downloading the app via testflight or via Beta by Fabric?

**Comment by RaziPour1993** [comment]
I use fastlane fabric.

**Comment by mfurtak** [comment]
Hi @RaziPour1993 :wave: for help with the Beta by Crashlytics service, please contact support@fabric.io :+1:
