### ISSUE TITLE
Match fails to push changes due to be out of sync with git repo

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#8777]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Basically, if some other process updated the online git repo with a new certificate, the sending of a second certificate always fails because the git local is out of sync with the git remote.

The push error message is bogus as the only thing that is needed is for the match to issue a "git pull" before tries to commit more changes.

```
To match:repo-name/match-certificates.git
! [rejected]        repo-name -> repo-name (fetch first)
error: failed to push some refs to 'git@match:repo-name/match-certificates.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
[17:18:52]: Exit status: 1
[17:18:52]: No permission to push...
[17:18:52]: Exit status: 1
[17:18:52]: You do not have push permission to git repository provided
[17:18:52]: _match_ needs to create a new certificate or provisioning profile, however without push access to the git repo, the generated certificate can't be stored properly, resulting in an unused certificate
[17:18:52]: Error: Please grant push access for the current git user to the git repo, so that _match_ can update and create certificates for you
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.4                                         |
| Ruby                        | 2.3.3                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.12.2                              |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane            |
| Host                        | Mac OS X 10.12.4 (16E195)                       |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode_8.3.app/Contents/Developer/ |
| Xcode Version               | 8.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

#select xcode version
#xcversion(version: "8.1") # Selects Xcode 8.1.0

#xcode_select "/Applications/Xcode.app"

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Create a new Alpha Build"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'dev-team-name',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: 'MyApp',
      export_method: 'ad-hoc',
      configuration: 'Alpha',
      output_directory: './build',
      output_name: 'MyApp-Alpha.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )
      
    # pilot
    hockey(
      api_token: '0xxxxxa',
      public_identifier: 'fxxxxxd',
      ipa: 'build/MyApp-Alpha.ipa',
      notify: '1',
      status: '2',
      release_type: '2',
      teams: '111teamid111',
      tags: 'developer,tester',
      strategy: 'replace'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Create a new Beta Build"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'dev-team-name',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: 'MyApp',
      export_method: 'ad-hoc',
      configuration: 'Beta',
      output_directory: './build',
      output_name: 'MyApp-Beta.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )

    hockey(
      api_token: '0xxxxxxa',
      public_identifier: 'bxxxxxxf',
      ipa: 'build/MyApp-Beta.ipa',
      notify: '1',
      status: '2',
      release_type: '0',
      teams: '111teamid111',
      tags: 'developer,tester',
      strategy: 'replace'
    )


    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

  end
 
  desc "Create a new Store Build"
  desc "This will also make sure the profile is up to date"
  lane :store do
    match(
      type: 'appstore',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: 'dev-team-name',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    # snapshot

    gym(
      scheme: 'MyApp',
      export_method: 'app-store',
      configuration: 'Store',
      output_directory: './build',
      output_name: 'MyApp-Store.ipa',
      include_symbols:false,
      include_bitcode:false,
      silent:true
    )

    deliver(
      skip_metadata: true, 
      skip_screenshots: true, 
      submit_for_review: false, 
      force: true,
      username: 'dev-user.MyApp@example.com'
    )
    # frameit

    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

    hockey(
      api_token: '0xxxxxa',
      public_identifier:  '5xxxxxxe',
      ipa: 'build/MyApp-Store.ipa',
      notify: '1',
      status: '2',
      release_type: '1',
      teams: '111teamid111',
      tags: 'developer,tester',
      strategy: 'replace'
    )


  end

  # You can define as many lanes as you want

  after_all do |lane|
    #hockey

    puts "All done successfully..."
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|

    puts "Error: " + exception.message

    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "dev-user@example.com" # Your Apple email address
team_id "V7J29L8Y68"  # Developer Portal Team ID

for_lane :test do
    app_identifier 'com.example.MyApp-alpha'
end

for_lane :alpha do
    app_identifier 'com.example.MyApp-alpha'
end

for_lane :beta do
    app_identifier 'com.example.MyApp-beta'
end

for_lane :store do
    app_identifier 'com.example.MyApp'
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.24.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.3        |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| fastimage                 | 2.1.0        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.3        |
| bundler                   | 1.14.6       |
</details>

*generated on:* **2017-04-05**
</details>

**Comment by lferro9000** [comment]
This only happens on my dev CI environment where several processes are updating certificates at the same time. Never seen it on dev desktop as it normally only runs one process.

**Comment by tschuls** [comment]
Had the same issue, did not work with version 2.25.0, but worked with version 2.20.0.

The issue only appears when a new branch needs to be created.

**Comment by mstratis** [comment]
I'm also having the same issue in 2.25.0

**Comment by GandjaFuzz** [comment]
I'm also having the same issue in 2.25.0

**Comment by GandjaFuzz** [comment]
in version 2.20.0 - having same issue but process don't stop, simple skip error and going to next step with gym.

**Comment by GandjaFuzz** [comment]
in 2.25.0 
need update in file git_helper.rb for match this function
```
    def self.check_push_repo_permission(path, branch = "master")
      repo_pushable?(path, branch)
    end
```

**Comment by ohayon** [comment]
Thanks everyone for posting the issue! @GandjaFuzz, would you mind trying to `return true` out of the `check_push_repo_permission` method and see if that gets you into a working state again? Before we make any changes we were just hoping to validate that passing that method would fix the issue. Thanks! 🚀

**Comment by GandjaFuzz** [comment]
it is not beaty.
```
    def self.repo_pushable?(path, branch = "master")
      Dir.chdir(path) do
        command = "GIT_TERMINAL_PROMPT=0 git push origin #{branch.shellescape} --dry-run"
        FastlaneCore::CommandExecutor.execute(command: command,
                                              print_all: FastlaneCore::Globals.verbose?,
                                              print_command: FastlaneCore::Globals.verbose?)
      end
      return true
    rescue => ex
      UI.error("No permission to push...")
      UI.error(ex)
        UI.error("You do not have push permission to git repository provided")
        UI.error("_match_ needs to create a new certificate or provisioning profile, however without push access to the git repo, the generated certificate can't be stored properly, resulting in an unused certificate")
       UI.error("Please grant push access for the current git user to the git repo, so that _match_ can update and create certificates for you")
      return true
    end

    def self.check_push_repo_permission(path, branch = "master")
	repo_pushable?(path, branch)
    end
```

**Comment by KrauseFx** [comment]
We just pushed a new release, please update using `fastlane update_fastlane` and let us know if that fixes the problem for you 👍
