### ISSUE TITLE
Increment build and version numbers for Android apps using Gradle

### ISSUE THREAD

**Issue by igoris** [fastlane/fastlane#878]
Manipulating build and version numbers from fastlane is extremely helpful in iOS builds, so I was thinking how to do the same for Android. Unfortunately, there is no such things as agvtool for Android.

Currently I have something like this in my build.gradle:

```
versionName project.VERSION_NAME
versionCode Integer.parseInt(project.VERSION_CODE)
```
During build on CI server  ```VERSION_NAME``` and ```VERSION_CODE``` are written  into settings.gradle.

Of course, it is possible to create custom action that will just write this constants into my settings.gradle, but maybe there are more generic options that will work for any Android gradle project. In this case we can add such action to fastlane standard actions.

Any thoughts?

**Comment by asfalcone** [comment]
@igoris Can you take a look at #1082 and see if this will meet your needs? This will be available in the next release of fastlane! 🚀

**Comment by bassrock** [comment]
Looks like #1082 should work to allow you to set a version with gradle. To get something like increment_build_number to work a solution may be to save the current version number in the metadata folder and increment that. Then in the cradle command pull from that.

**Comment by bassrock** [comment]
Actually just was able to do it nicely with this:
```ruby
# Get the last version code and increment it.
versionCode = File.read("metadata/versionCode").to_i
versionCode = versionCode +1

f = File.new("metadata/versionCode", "w")
f.write(versionCode)
f.close

gradle(task: "assemble", build_type: "Release",  properties: { 'versionCode' => versionCode })

```

If thats the accepted answer it could be added into the increment_build_number actions and the lane context as well too.

**Comment by npomfret** [comment]
Are there any docs for this?  I'd like to get fastlane to bump my version in the same (or similar) way to how it works on IOS:

```
    increment_build_number(
      xcodeproj: './pomochat.xcodeproj'
    )
```

**Comment by TKBurner** [comment]
@npomfret As far as I know, @bassrock's solution is the most viable option. Have you tried it? Thanks 👍

**Comment by kobkrit** [comment]
@bassrock I have tried your proposed solution. My versionCode is not bump. It seems like gradle do not follow the versionCode in the properties at all. Here is my Fastfile
`
lane :beta do
    # Get the last version code and increment it.
    versionCode = File.read("metadata/versionCode").to_i
    versionCode = versionCode+1

    f = File.new("metadata/versionCode", "w")
    f.write(versionCode)
    f.close

    # Build the release version of the Android App
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "android/",
      properties: { 'versionCode' => versionCode }
    )
`

**Comment by iForests** [comment]
@kobkrit I think you should change you build.gradle to something like this:

    versionCode project.hasProperty('versionCode') ? project.property('versionCode') as int : 1

**Comment by koenpunt** [comment]
I replace the versionCode using `awk`:

```sh
echo "$(awk '{sub(/versionCode [[:digit:]]+$/,"versionCode "$2+1)}1' android/app/build.gradle)" > android/app/build.gradle
```

Called from within the `Fastfile`:

```rb
platform :android do

  def increment_version_code(gradle_build: 'android/app/build.gradle')
    sh %Q{cd ../ && echo "$(awk '{sub(/versionCode [[:digit:]]+$/,"versionCode "$2+1)}1' #{gradle_build})" > #{gradle_build} && cd -}
  end

  desc 'Create versioned build'
  lane :build do
    increment_version_code gradle_build: 'android/app/build.gradle'
    # gradle
  end
end
```

**Comment by Singwai** [comment]
https://github.com/Jems22/fastlane-plugin-increment_version_code

This plugin seems to work pretty well too
