### ISSUE TITLE
[Scan] Auto Detect Connected Devices

### ISSUE THREAD

**Issue by alexanderjrobinson** [fastlane/fastlane#8782]
Is there any existing support or plugin for Scan to automatically run on all connected devices? 

We would like our tests to run on multiple devices connected to the build server, but the list of connected devices may change frequently. It would be helpful if there was an auto detect feature or plugin that would scan for the connected devices and run the tests on all compatible devices.

**Comment by alexanderjrobinson** [comment]
I'm looking for something like the following command integrated into Scan to automatically discover and run tests on any compatible connected device. 

`system_profiler SPUSBDataType | sed -n -E -e '/(iPhone|iPad)/,/Serial/s/ *Serial Number: *(.+)/\1/p'`

**Comment by mfurtak** [comment]
A quick search through the code shows that we already have the ability to find the devices connected via USB.

https://github.com/fastlane/fastlane/blob/b933217a5ad82d3c9c1ffd89c0900a2e3be030f9/fastlane_core/lib/fastlane_core/device_manager.rb#L68

Perhaps someone can comment more about whether/how this can be used via _scan_?

**Comment by KrauseFx** [comment]
We merged and released https://github.com/fastlane/fastlane/pull/5159, however we had to roll it back due to problems.
