### ISSUE TITLE
Action Proposal - Microsoft Teams Notification

### ISSUE THREAD

**Issue by johnrufusj** [fastlane/fastlane#8788]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have created a new action that allows users to post to Microsoft Teams (similar to the slack and other collaborative tools actions).  

This will be a beneficial action for all who use Microsoft Teams.  

Per the fastlane guidelines for PRs for new Actions, it requests that we post an issue with the proposal prior to submitting a PR.

**Comment by hjanuschka** [comment]
@johnrufusj as of now we do not accept new actions to the core of fastlane.
however i think the described action would be really useful for a couple of teams 🚀  - therefore i suggest you to do it as a fastlane-plugin.

see docs about it here: https://docs.fastlane.tools/plugins/create-plugin/#create-your-own-plugin

**Comment by johnrufusj** [comment]
Ok. Thanks

**Comment by hjanuschka** [comment]
if you need any help doing the plugin feel free to ping me.

**Comment by mbogh** [comment]
@johnrufusj I have create a very basic fastlane plugin [teams](https://github.com/mbogh/fastlane-plugin-teams) feel free to contribute to it 🚀
