### ISSUE TITLE
Setting up fastlane for the first time, getting errors early on. 

### ISSUE THREAD

**Issue by kelvinlauKL** [fastlane/fastlane#8792]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to get started with fastlane, but quickly ran into some problems. **Am I suppose to manually create an app on iTunes connect before fastlane can be useful?**

For testing purposes, I created a brand new Xcode project and did the following steps:

1. Went into my project directory, and used `fastlane init` in Terminal
2. Gave my apple credentials when prompted
3. fastlane then told me `This app identifier doesn't exist on iTunes Connect yet, it will be created for you` and asked me to `Please confirm the above values (y/n)`
4. I selected `y`
5. I then received this error: 
```
Ran into error while trying to connect to iTunes Connect / Dev Portal: Could not find app with app identifier 'com.Kelvin.Test132.asdf.341234' in your iTunes Connect account (kelvin.kl.lau@gmail.com - Team: 117214157)`

Falling back to manual onboarding

Could not find app with app identifier 'com.Kelvin.Test132.asdf.341234' in your iTunes Connect account (kelvin.kl.lau@gmail.com - Team: 117214157)

An error occured during the setup process. Falling back to manual setup!
```

Any help is appreciated. 

### Captured Output

Command Used: `init`
<details><summary>Output/Log</summary>

```

DEBUG [2017-04-05 15:41:45.20]: Checking if there are any plugins that should be loaded...
INFO [2017-04-05 15:41:45.21]: Detected iOS/Mac project in current directory...
INFO [2017-04-05 15:41:45.21]: This setup will help you get up and running in no time.
INFO [2017-04-05 15:41:45.21]: fastlane will check what tools you're already using and set up
INFO [2017-04-05 15:41:45.21]: the tool automatically for you. Have fun! 
INFO [2017-04-05 15:41:45.21]: $ xcodebuild clean -showBuildSettings -project ./Test.xcodeproj
WARN [2017-04-05 15:41:45.62]: Your Apple ID (e.g. fastlane@krausefx.com): 

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  Missing Push Notification Entitlement - response from itunes app review
   https://github.com/fastlane/fastlane/issues/8523 [open] 5 💬
   3 weeks ago

➡️  ERROR 65: Your shell environment is not correctly configured
   https://github.com/fastlane/fastlane/issues/8157 [open] 8 💬
   3 weeks ago

➡️  fastlane deliver upload_build - not referencing fastlane/metadata/review_information/notes.txt for app_review_information key 'notes'
   https://github.com/fastlane/fastlane/issues/8413 [closed] 2 💬
   5 weeks ago

and 15 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.Kelvin.Test132.asdf.341234" # The bundle identifier of your app
apple_id "kelvin.kl.lau@gmail.com" # Your Apple email address

team_id "99A58D6B2S"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.25.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-04-05**
</details>

**Comment by KrauseFx** [comment]
_fastlane_ should handle this automatically, I assume that there might be a team mix up: When you login using your Apple ID on the Dev Portal and iTunes Connect, is it the same account? 

The output you posted in `Output/Log` seems to be a different error, right?

**Comment by kelvinlauKL** [comment]
I just checked and as far as I can tell, both my account in the Dev Portal and iTunes Connect uses the same email and password.

Not sure about the `Output/Log` stuff - Just wanted to pass along more information

Could switching on Xcode's automatic provisioning affect this in any way?

**Comment by IamAlchemist** [comment]
same error

**Comment by Kastet** [comment]
I have the same error but in my case, Dev Portal and iTunes Connect are two different Apple IDs. Any suggestions?

**Comment by KrauseFx** [comment]
For those cases it's probably best to set up _fastlane_ yourself, based on the [docs](https://docs.fastlane.tools) and the [example setups](https://github.com/fastlane/examples) 👍

**Comment by nwalde** [comment]
I had the same error, I found that the app name I'm using was already available on iTunesconnect.
Try creating with a unique name which is not available on iTunesconnect and it will work.
Cheers! 👍

**Comment by gblejman** [comment]
Same here, i had no previous apps, using same log in credentials both in Dev Portal and ITunes
After fastlane init, the app would have been created in Dev Portal but not in ITunes

What i ended up doing was:

- run fastlane init
- manually create missing app on ITunes linking to Dev Center’s bundle id
- delete fastlane folder
- run fastlane init again so it picks metadata about both

**Comment by lukaspili** [comment]
Encountered the same issue when setting up fastlane for the first app of a fresh developer account belonging to a company. 

I guess the error is caused by the fact that when creating the first app on itunes connect, you have to provide the company name. This requirement applies only for the first app of a company's developer account.

**Comment by senart** [comment]
I had the same issue during `fastlane init` and I am part of two teams with same email & pass.
However I managed to get it working 👌 :

0. Run `fastlane init` to create your Appfile and etc. Receive the nasty 

> Could not find app with app identifier XXXXXX in your iTunes Connect account ....

1. Change Appfile
What I did to get it to create the app on iTunes Connect is changing my `../XcodeFastlaneProject/fastline/Appfile` to this:

```
app_identifier "com.yourCompany.YourApp" # The bundle identifier of your app

apple_dev_portal_id "email@email.com"  # Apple Developer Account
itunes_connect_id "email@email.com"     # iTunes Connect Account

team_id "E******" # Developer Portal Team ID
itc_team_id "1*****" # iTunes Connect Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```

This is effectively adding the two emails separately and specifying  itc_team_id.

2. Call `fastlane produce`
This creates the app on iTunes Connect without problems, because the Appfile is properly setup. You can check this by logging in your iTunes Connect account.

3. Call `fastlane init`
This will wipe your Appfile with the default (non-working) setup, but it will succeed, because you have the new app on iTunes Connect. 

4. Repeat step **1**
Because step 3 wipes your Appfile, you have to edit it again.

This should finish successfully and you have a normal setup now! Feel free to edit your `Fastlane` file now and run things like `fastlane beta` 😄
