### ISSUE TITLE
shell_session_update: command not found

### ISSUE THREAD

**Issue by burning-git** [fastlane/fastlane#8794]
wrong infomation:
-----------
+ shell_session_update
/Users/gitburning/.rvm/gems/ruby-2.1.8@global/gems/fastlane-2.25.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 62: shell_session_update: command not found

It's wrong when I build project 
can you help me ?

**Comment by burning-git** [comment]
I fastlane env ,but it's also wrong 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.1.8                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.1.8/bin/fastlane       |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.1.8/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.25.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "N") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "N") # Build your app - more options available
    deliver(force: true)
    # frameit
  end
 desc "build ipa..."
  lane :buildIpa do
   
      gym(scheme: "LingDiApp",
      workspace: "LingDiApp.xcworkspace",
      include_bitcode: true)

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "zom.com.LingDiApp" # The bundle identifier of your app
apple_id "" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.25.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.3        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-04-06**
</details>

**Comment by burning-git** [comment]
I use  fastlane env ,but  it's also wrong..
can you help me ?


+ shell_session_update
/Users/gitburning/.rvm/gems/ruby-2.3.0/gems/fastlane-2.25.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 62: shell_session_update: command not found

**Comment by hjanuschka** [comment]
i ran into the same problem on some CI machines.

can you try adding this to your `.bash_profile`/`.profile`/`.bashrc`  (depending on what your shell uses.)

```bash
shell_session_update() { :; }
```

**Comment by burning-git** [comment]
It's modify  in  xcbuild-safe.sh  file?

**Comment by hjanuschka** [comment]
ohh sorry that was unclear no it should be in your home folder so like this.

`~/.bash_profile` - or `~/.profile` - or `~/.bashrc` (depending on what shell you/your user uses)

**Comment by burning-git** [comment]
I can't find the ~/.bash_profile or  ~/.profile  or ~/.bashrc
there are in my project  ?
then how can I find ?

**Comment by hjanuschka** [comment]
for me it is in 

`/Users/hjanuschka/.bash_profil`


are you running fastlane locally or in any CI? what shell are you using?
find out by running `echo $SHELL`

if it is `bash` - and none of the files exist just create the `~/.bash_profile`

**Comment by burning-git** [comment]
when I add the code  `shell_session_update() { :; }` 
the error ,  can you help me? 😄
[17:05:07]: Successfully exported and compressed dSYM file
[17:05:07]: The generated archive is invalid, this can have various reasons:
[17:05:07]: Usually it's caused by the `Skip Install` option in Xcode, set it to `NO`
[17:05:07]: For more information visit https://developer.apple.com/library/ios/technotes/tn2215/_index.html
[17:05:07]: Also, make sure to have a valid code signing identity and provisioning profile installed
[17:05:07]: Follow this guide to setup code signing https://docs.fastlane.tools/codesigning/GettingStarted/
[17:05:07]: If your intention was only to export an ipa be sure to provide a valid archive at the archive path.

[!] Archive invalid

**Comment by hjanuschka** [comment]
@burning-git ok this is a different issue :D - have you tried the suggested information - and read through the codsigning guide?

**Comment by burning-git** [comment]
I had read, but not success..  I  try again

**Comment by burning-git** [comment]
thanks too much
