### ISSUE TITLE
Windows `fork unimplemented`

### ISSUE THREAD

**Issue by deadman2000** [fastlane/fastlane#8800]
Hi guys!
I'm trying to use **fastlane** on Windows 7 with android project.
Ruby 2.3.3

I run `fastlane init` from project folder and got an error:
```
R:\Qt\WL_Android_Release\android-build>fastlane init
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.25.0/fastlane_core/lib/fastlane_core/update_checker/update_checker.rb:37:in `fork': fork() function is unimplemented on this machine (NotImplementedError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.25.0/fastlane_core/lib/fastlane_core/update_checker/update_checker.rb:37:in `show_update_status'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/cli_tools_distributor.rb:68:in `ensure in take_off'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/cli_tools_distributor.rb:68:in `take_off'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.25.0/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby23-x64/bin/fastlane:22:in `load'
        from C:/Ruby23-x64/bin/fastlane:22:in `<main>'
```

**Comment by hjanuschka** [comment]
hey ✋,
right now there is no support for windows  platform - there are a couple of things, like fork that needed to be addressed.

**Comment by AdityaAnand1** [comment]
It's still not resolved, here's what I get:

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/update_checker/update_checker.rb:46:in `fork': fork() function is unimpleme
nted on this machine (NotImplementedError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/update_checker/update_checker.rb:46:in `show_update_status'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:69:in `ensure in take_off'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:69:in `take_off'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/fastlane-2.37.0/bin/fastlane:20:in `<top (required)>'
        from C:/Ruby23-x64/bin/fastlane:23:in `load'
        from C:/Ruby23-x64/bin/fastlane:23:in `<main>'
```

Do let me know if you need any further information. My setup is pretty basic. Started from a clean ruby install for screengrab specifically (Oh and yes, the above stack trace is when I use `fastlane screengrab`).

Please specify that Windows is not supported in the [readme](https://github.com/fastlane/fastlane/blob/master/screengrab/README.md), after 2 hours of wrestling with random ruby quirks I find this issue :/

**Comment by Floreturns** [comment]
fork() is not implemented on Windows and fastlane try to use it, that's why we get this error.

On Windows only CreateThread and CreateProcess are implemented. But the code has to be changed to support windows or find a way to ignore the fork() ;)

**Comment by taquitos** [comment]
Thanks all, sorry for the trouble there. I've updated the docs to point out that macOS is the primarily supported platform for running _fastlane_ right now.
