### ISSUE TITLE
Map different lanes to specific Gymfiles

### ISSUE THREAD

**Issue by aravasio** [fastlane/fastlane#8813]
### Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Proposal
This is not an issue but, rather, either a `documentation improvement` or a `feature request`.
I'm wondering if there's a way to map gym(..) commands to specific Gymfiles, since I want to use different Gymfiles for different lanes (e.g. one for building/signing/uploading to hockeyApp, another one to buid/sign/screenshot/upload to AppStore).

Is this an existing feature? Does this make sense within the context of what `fastlane` is trying to solve? My motivation (and rationale) behind this is, specifically, to provide specific `export_options` (a Gym setting) depending on the lane I'm running.

I'm thinking of something along the lines of:
```ruby
lane :hockey do
  cocoapods
  gym(
    gym_file: "path/to/hockey/lane/gymfile", #This is what I'm suggesting fastlane offers support to.
    scheme: "MyScheme",
    build_path: "~/gym_archives", #Where the .xcarchives are dumped
    buildlog_path: "~/gym_builds/logs" #build logs path
    output_directory: "~/gym_builds", # store the ipa in this folder
    output_name: "MyApp" # the name of the ipa file
  )

  # upload to HockeyApp
  hockey(
    api_token: "SOME API"
  )
end
```

and then I can have `n` different Gymfiles that I can use, for example:
```ruby
export_options(
  method: "development",
  thinning: "<thin-for-all-variants>"
)
```
or 
```ruby
export_options(
  method: "ad-hoc",
  thinning: "<thin-for-all-variants>"
)
```

Is this reasonable? I really appreciate any input you might have.
If `fastlane env` is still needed, I'll gladly edit and add it to this post. It feels unneeded, given how this is not an issue, but if nonetheless required, will gladly provide it.

**Comment by Lutzifer** [comment]
Just a comment:

We solved something like this using options (vastly shortened example):

```
desc "iOS Beta Build"
private_lane :build_with_options do | options |
    configuration = options[:configuration] || "Release"
    gym(
      scheme: 'App',
      configuration: configuration
    )
end
```

and call it like

```
build_with_options(configuration: "Debug")
```

Might be that this makes your life  a bit easier.

**Comment by mfurtak** [comment]
Hi @aravasio 👋 - thanks for the feedback!

Another thing you could consider trying is a bit of infrequently used advanced _fastlane_ configuration magic ✨ 

Check out: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform which lets you vary parts of your configuration based on what lane you're executing.

Because there are many ways to manage configuration already, I think the feature you're suggesting is unlikely to be adopted. In that vein, I'm going to close this for now, but we can definitely continue the conversation and reopen as needed. 👍
