### ISSUE TITLE
Xcode 8 Code signing issue with variable app identifier

### ISSUE THREAD

**Issue by glesage** [fastlane/fastlane#8821]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Since Xcode 8 we are having issues signing/building apps using `gym`... We can run produce  & match no problem but the signing does not seem to work anymore. We have a whitelabel setup where the codebase is re-used for ~50 apps and we dynamically change the app identifier, name & colors. This used to work great on Xcode 7 but no longer does on Xcode 8

Output: https://gist.github.com/glesage/e569953979fa930d4c83d5355b3f6c2e

My Fastfile
```
opt_out_usage
fastlane_version "2.26.0"
default_platform :ios
platform :ios do

  before_all do |lane, options|
    ENV["FL_UPDATE_PLIST_PATH"] = "my_dir/Info.plist"
    ENV["SIGH_OUTPUT_PATH"] = "./fastlane/profiles"
    ENV["SCHEME"] = options[:scheme]
  end

  lane :build do |options|
    match(
      username: ENV["DEV_USERNAME"],
      app_identifier: ENV["APP_IDENTIFIER"],
      type: "appstore"
    )
    gym(
      output_directory: "./fastlane/ipa",
      output_name: "my_app.ipa",
      scheme: ENV['SCHEME']
    )
  end
end
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-04-07**
</details>

**Comment by PetrosIchor** [comment]
Xcode8 began phasing out the provisioning profile uuid in favor of the provisioning specifier.  It also introduced automatic signing. 

Are you using the PROVISIONING_PROFILE_SPECIFIER now and disabling automatic signing?  If not, you're build will fail with that error.

**Comment by glesage** [comment]
Hm... I did disable automatic signing, both programmatically and via the GUI but had no luck this way.

I also just tried setting the PROVISIONING_PROFILE_SPECIFIER as an environment variable but am getting the same errors. I've tried setting it with
`export PROVISIONING_PROFILE_SPECIFIER="match AppStore com.starchup.pressgallery"`
and
`export PROVISIONING_PROFILE_SPECIFIER="com.starchup.pressgallery"`
as well as with xcargs

But no go.. I can also verify that the cert is on the account

<img width="600" alt="screen shot 2017-04-07 at 7 56 02 pm" src="https://cloud.githubusercontent.com/assets/711580/24824155/521156ac-1bcc-11e7-8d91-37d5f0ecd5b8.png">

**Comment by mcactive** [comment]
Having the same issue over here. Also tried setting PROVISIONING_PROFILE_SPECIFIER but no luck so far..

**Comment by SiberianCMS** [comment]
We are having same issues, and found a solution.

The context, we are having multiple platforms, with multiple whitelabels, so it could be really tricky to manage, it seemed to worked really nice with Xcode 7.3.1, but since we migrated to Xcode 8.2.1 we faced the "Magic Automatic Code Signing".

We still facing issues with development teams, but not with regular accounts (will try to find a solution for these teams.)

This is how we managed code signing.

First for some reason we can't use `disable_automatic_code_signing` our code base template doesn't have any "TargetAttributes" and Fastlane, thinks it's a old project format (it's not...)

so I simply "patch" the project.pbxproj to set provisioning to manual

```
attributes = {
    LastUpgradeCheck = 510;
    TargetAttributes = {
        1D6058900D05DD3D006BFB54 = {
            ProvisioningStyle = Manual;
        };
    };
};
```

When this is done

Is now use `match` with one branch for each customer, this way we can share Distribution profiles across build nodes.

```
match(
    type: "appstore",
    git_url: "xxxxxxxxxxxx.git",
    git_branch: options[:customer_id],
    username: options[:customer_id]
)
```

Then finally in `gym`

I use `xcargs` along with `sigh` values

```
prov_uuid = ENV["sigh_#{app_identifier}_appstore"]
xcargs: "
    CODE_SIGN_IDENTITY[sdk=iphoneos*]='iPhone Distribution' \
    PROVISIONING_PROFILE_SPECIFIER='' \
    PROVISIONING_PROFILE='#{prov_uuid}'",
```

So this solution works for most of our use cases, except the Development Team so far, I know this not the best way to do it, but while waiting for a better one we are on rails !

Hope this will help you out ! @glesage @mcactive

**Comment by glesage** [comment]
Hey @SiberianCMS thks for the tips!

Unfortunately fastlane does not seem to be changing the app identifier correctly.. in the verbose logs of the build process it still seems to use the app identifier that I see on xcode.. instead of the new identifier I'm passing with match

**Comment by PetrosIchor** [comment]
There are a number of actions and plugins to inject your app identifier into you project.  I use this flow with our whitelabel products to provide the specific ID depending on target.

Fastlane flow looks like this:
- inject ID, version, name, and disable automatic signing
- match to pull signing assets
- gym to build

**Comment by vineethvijay** [comment]
Following might work for you people. I do it this way. Uses sigh to download install a new ad-hoc profile with all the latest devices added, and those profile (SIGH_UUID) is passed to gym with xcargs.

```
lane :build do

sigh(
adhoc: true,
app_identifier: "***APP_ID**",
provisioning_name: "**Profile_name**",
username: "Apple_ID",
force: true,
skip_certificate_verification: true,
)


gym(
#export_options: "exportPlist.plist",
scheme: "**scheme-name**",
export_method: "ad-hoc",
xcargs: "PROVISIONING_PROFILE=$SIGH_UUID",
)
end
```
