### ISSUE TITLE
[deliver] Infinite loop when Apple ID have multiple iTunes Connect team

### ISSUE THREAD

**Issue by 0x5e** [fastlane/fastlane#8824]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a Jenkins job about uploading ipa to iTunes Connect, made it for my colleagues who don't have macOS, using this shell command:

```
curl -o appstore.ipa "${URL}"
fastlane fastlane-credentials remove --username "${USERNAME}"
fastlane fastlane-credentials add --username "${USERNAME}" --password "${PASSWORD}"
fastlane deliver --skip_screenshots \
	--skip_metadata \
	--username "${USERNAME}" \
	--ipa appstore.ipa

```

Apple ID belongs to one team works fine, today they use the Apple ID which belongs two team, causes fastlane-deliver infinite loop:

```
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "xxxxxxxxx"

or

  itc_team_name "aaaaaaaaaa"

1) "aaaaaaaaaa" (xxxxxxxxx)
2) "bbbbbbbbb" (yyyyyyyyy)
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "xxxxxxxxx"

or

  itc_team_name "aaaaaaaaaa"

1) "aaaaaaaaaa" (xxxxxxxxx)
2) "bbbbbbbbb" (yyyyyyyyy)
Multiple iTunes Connect teams found, please enter the number of the team you want to use: 
Note: to automatically choose the team, provide either the iTunes Connect Team ID, or the Team Name in your fastlane/Appfile:
Alternatively you can pass the team name or team ID using the `FASTLANE_ITC_TEAM_ID` or `FASTLANE_ITC_TEAM_NAME` environment variable

  itc_team_id "xxxxxxxxx"

or

  itc_team_name "aaaaaaaaaa"

1) "aaaaaaaaaa" (xxxxxxxxx)
2) "bbbbbbbbb" (yyyyyyyyy)
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.11.6 (15G1004)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.8        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-04-08**
</details>

**Comment by rhsyen** [comment]
I've had this happen quite often as well, as I'm working with multiple teams. The code that causes this is in [Spaceship - select_team.rb](https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/ui/select_team.rb#L70). I think it would be good to either try and detect if running in a CI environment, or have an environment variable that tells spaceship to fail if it can't auto-pick the team.

**Comment by KrauseFx** [comment]
Thanks for reporting this, definitely something we want to fix, however we currently don't have access to the kind of environment in the spaceship code. This will require some refactors from our side.

**Comment by lacostej** [comment]
@KrauseFx what are your views on fixing this in the long term? Here are some alternatives:

* extract a thin `fastlane_shared` module containing only the basics things (in this case, `is_ci?`)
* duplicate code
* other mechanism?

**Comment by KrauseFx** [comment]
@lacostej I think the easiest way is to do an `require "fastlane_core"` to spaceship, as fastlane_core is pretty light still. It's the easiest solution without a lot of downsides I think. What are your thoughts
