### ISSUE TITLE
Feature:need completion for Zsh or Bash

### ISSUE THREAD

**Issue by yangcaimu** [fastlane/fastlane#883]
I hope to have this feature completion for Zsh or Bash,it will be faster :rocket:

**Comment by KrauseFx** [comment]
What do you mean? Something like `fastlane be` to be autocompleted to `fastlane beta`? :rocket:

**Comment by yangcaimu** [comment]
Yes.For example: [Bash/Zsh completion for Carthage](https://github.com/Carthage/Carthage#bashzsh-completion).

**Comment by ileitch** [comment]
If it auto completed all lanes defined in `Fastfile`, that'd be sweet :wink:

**Comment by dusek** [comment]
Also:
* `fastlane r<TAB>` should autocomplete to `run`
* `fastlane run in<TAB>` should autocomplete `increment_` and offer `increment_build_number` and `increment_version_number` as completion options

**Comment by asfalcone** [comment]
Working on fastlane auto completion for lane names! :rocket: Will put up a PR soon! 

![image](https://cloud.githubusercontent.com/assets/1848683/14332733/e4ce98bc-fc18-11e5-9b22-85613e9854bf.png)

**Comment by KrauseFx** [comment]
PR https://github.com/fastlane/fastlane/issues/4090
Closing this issue for now :+1:
