### ISSUE TITLE
Unable to send dSYM file to hockey using create_update

### ISSUE THREAD

**Issue by CatalinPrata** [fastlane/fastlane#8832]
🔑
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I started using the Hockey action to create and update builds of my iOS app on Hockey.
If I use the upload method everything seems to be ok but I need though to use the create_update method which seems to throw an error saying: **"Error when trying to upload file(s) to HockeyApp: 422 - {"status"=>"error", "message"=>"File not found. Please check that your file is not a directory or bundle."}"**
The error comes from the Hockey server it seems. 

The build version is being created and the ipa is being uploaded on the Hockey server.
After some debugging, I noticed that using postman I could send the dsym to the same version that was created on hockey and if I try to set an invalid dsym path to the Hockey action it throws a correct error saying that the path is invalid so I looked even further.

I debugged the hockey.rb action and the function `create_and_update_build` seems to "forget" about uploading the dsym file as well. See line ~90 https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb it does upload the ipa but I couldn't find where is the dsym uploaded so I added the following:

*line 91*
`       dsym = options.delete(:dsym)
        if dsym
          dsymIO = Faraday::UploadIO.new(dsym, 'application/octet-stream') if dsym and File.exist?(dsym)
        end`

*line 107*
`if dsym
            options[:dsym] = dsymIO
        end`

And that seems to fix the problem. The dsym and the ipa are being sent to the server in this case. 

Can somebody take a look and see if this is something that needs to be done or I am missing something?

Thank you!

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

I am using the Hockey action as following:
		hockey(
			api_token: "c11a2769xxxxxxx4a251",
			create_update: true,
			public_identifier: "0144b4xxxxxx64b74",
			bundle_short_version: versionName,
			bundle_version: commitCount,
			ipa: "./#{scheme}.ipa",
      dsym: "#{ENV["DSYM_OUTPUT_PATH"]}"
		)

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3                                                            |

**Comment by rikur** [comment]
👍 your monkey-patch fixed upload for me too. Same error, same changes fixed it.

**Comment by CatalinPrata** [comment]
🔑
I cloned locally the repo, made the fix and tried to push a new branch to make a PR but it seems that I am unable to do that because I don't have access... am I missing something? do I need permissions to push a new branch?
Thanks!

**Comment by rikur** [comment]
@CatalinPrata you need for fastlane/fastlane repo into CatalinPrata/fastlane repo and make the PR from there against fastlane/fastlane.

**Comment by CatalinPrata** [comment]
@rikur thanks a lot for your response, will do that :).

**Comment by lacostej** [comment]
This is supposed to be closed. Thanks a lot @CatalinPrata !

I had no use of dSYM upload in our `create_update` use case and completely forget to put it in the original implementation.
