### ISSUE TITLE
Deliver fails while uploading app icon to iTunes Connect.

### ISSUE THREAD

**Issue by tier777** [fastlane/fastlane#8837]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Deliver fails while uploading app icon.

> [!] [IMG_BAD_COLOR_SPACE] This does not use RGB color space. Please edit the image to use the RGB color space and re-save it.

Manually uploading works fine.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "79478d73-c7ec-4a35-a32b-e9dca4183217"

team_id: "118614213"

default_platform :ios

lane :beta do
  
  cert
  sigh  
  gym(scheme: "Catch")
  testflight(
    team_id: "118614213",
    skip_waiting_for_build_processing: true
  )

end

lane :store do

  snapshot                      # generate new screenshots for the App Store
  cert
  sigh
  pem
  gym(scheme: "Catch")          # build your app
  appstore                      # upload your app to iTunes Connect

end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

app_identifier "com.itmegastar.catch.master" # the bundle identifier of your app
apple_id "tier1993@gmail.com" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-04-10**
</details>

**Comment by tier777** [comment]
![app_icon](https://cloud.githubusercontent.com/assets/3135005/24856655/2803df1e-1dee-11e7-9884-c1fa04f66c11.jpg)

**Comment by f0r3s1** [comment]
the same problem

**Comment by LKTheMaster** [comment]
the same

**Comment by kambala-decapitator** [comment]
FYI: no issues with Xcode 8.3.2 and fastlane 2.28.3 for me

**Comment by Julyyq** [comment]
+1

**Comment by KrauseFx** [comment]
This seems like something _fastlane_ should detect and automatically fix. Do you remember with what application the file was created? When you re-save the app icon as PNG (which is the recommended file format from Apple), does it work?

**Comment by tier777** [comment]
@KrauseFx Yes, I re-saved icon in png (using Sketchapp) and it works.

**Comment by ohayon** [comment]
Hey @tier777 thanks for the update, I'm glad you're back in a working state. I am going to close this issue for now, but if you come across this again, we would love to see the output from your _fastlane_ execution. Thanks! 🚀

**Comment by mileswright** [comment]
Had this issue today after using Deliver to download assets from iTunes Connect, looking at the asset downloaded it was indeed a jpg instead of a png.  Opening file and exporting as png indeed worked.

**Comment by iorena** [comment]
I am having this exact issue, my app icons are png without alpha channel. Manually uploading also works fine.

Xcode 8.3.3
Fastlane 2.53.1
Ruby 2.4.1p111

**Comment by taquitos** [comment]
Hi all, please open new issues so we can start taking a look 👍  thanks!
