### ISSUE TITLE
deliver: error when setting phone number

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#8839]
I am getting the below error when uploading build through Deliver.

[!] The request could not be completed because:
	Phone number cannot be longer than 20 bytes There are one or more errors on the page.[0m

**Comment by KrauseFx** [comment]
> Phone number cannot be longer than 20 bytes There are one or more errors on the page.

That's the error message. Please provide the phone number on iTunes Connect

**Comment by santoshshetty2612** [comment]
The phone number on iTunes is +32 49917xxxx

I have the same number for another product and it uploads fine.

**Comment by santoshshetty2612** [comment]
Any update on this issue? Even with the latest fastlane I am facing this issue.

The request could not be completed because:
	Phone number cannot be longer than 20 bytes There are one or more errors on the page.[0m

The phone number is iTunes is correct and less than 20 bytes

**Comment by SLambrakis** [comment]
I just experienced this issue. I discovered that editing the phone number (in iTunesConnect), saving the change, and then changing it back to the previous value, makes the error go away.

**Comment by santoshshetty2612** [comment]
Thanks @SLambrakis, I will give a try and see whether it works.

**Comment by santoshshetty2612** [comment]
Thanks It works now after following your suggestion @SLambrakis.
