### ISSUE TITLE
Skip Cocoapods

### ISSUE THREAD

**Issue by fatuhoku** [fastlane/fastlane#884]
When I'm iterating my fastlane setup to deploy to either TestFlight or AppStore, I find myself really wanting to execute my `appstore` lane, except I want to skip the `exclude CocoaPods` step.

Just thinking about it, I know I can always just temporarily comment `cocoapods` out in my `Fastfile`, but is there some sort of flag that I can pass to fastlane that will disable that specific step for me to save me from changing the Fastfile?

**Comment by KrauseFx** [comment]
Something like this? https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md

**Comment by fatuhoku** [comment]
@KrauseFx that is just genius. Exactly what I was looking for. Thank you!

**Comment by KrauseFx** [comment]
Yeah :+1:
