### ISSUE TITLE
Returning value from Fastlane

### ISSUE THREAD

**Issue by JanC** [fastlane/fastlane#8845]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hi,
I have a custom action `get_sdk_version` that 
- returns the version of my project
- sets a environment variable to that version

I can use it fine within my lanes

```ruby
lane :release_push_staging  do |options|
        version = get_sdk_version
        UI.message "Releasing version #{version}"
         ...
end
```

Now the question is if there is a way to use or return this version number outside of the fastlane context back to the the place Fastlane was called from so that I can use in another scripts (command line or in a `Jenkinsfile`)

cheers

**Comment by PetrosIchor** [comment]
Set the return to an environment variable or write it to a file?  There's a variety of ways. It just depends in your needs and flow.

**Comment by KrauseFx** [comment]
This seems not related to fastlane, as shell scripts can only return a number (known as exit status). @PetrosIchor pointed out there is various ways to implement this, including writing a file. 

```ruby
File.write("output.txt", "my value here")
```

You can't use environment variables, as they're not passed to the parent process.

**Comment by JanC** [comment]
As Felix mentioned, setting an env value does not work. Writing the value to the file will do it but I was wondering if there is a better way. Writing to a file means that I will have to pass the (random) file name to the the lane itself in order to avoid parallel processes (Jenkins jobs) writing different values to the same file.

thanks for your help

**Comment by lyndsey-ferguson** [comment]
There are Jenkins APIs that you can also work with. Maybe there is an API that you can post to? Do you need to update the label for a particular Jenkins build?
