### ISSUE TITLE
Mailgun doesn't send emails but no errors too 

### ISSUE THREAD

**Issue by ugenlik** [fastlane/fastlane#8852]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Similar Mailgun issue to https://github.com/fastlane/fastlane/issues/8568

In mac terminal running following command sends an email. 

```
curl -s --user 'api:key-xxxx' https://api.mailgun.net/v3/sandboxxxxx.mailgun.org/messages -F from='Mailgun Sandbox <postmaster@sandboxxxxxx.mailgun.org>' -F to='Umut <ugenlik@xxxx.com>' -F subject='Hello Umut' -F text='Congratulations Umut, you just sent an email with Mailgun!  You are truly awesome!'
```

In fast file running following does nothing, `to`  email address is verified in Mailgun
<img width="581" alt="screen shot 2017-04-11 at 2 01 35 pm" src="https://cloud.githubusercontent.com/assets/1995917/24923411/713f4a8e-1ebf-11e7-8808-3bdf74c9bbca.png">

```
      mailgun(postmaster: "https://api.mailgun.net/v3/sandboxxxxxxx.mailgun.org/messages",
        apikey: "key-1283d1761422369594e5c5db309b90d7",
        to: "Umut <ugenlik@xxxxx.com>",
        from: "Mailgun Sandbox <postmaster@sandboxxxxxxx.mailgun.org>",
        app_link: "https://www.google.com",
        subject: "Hey",
        message: "Successfully deployed new App Update.",
        success: true
        )
```
[INSERT OUTPUT HERE]
```
+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | Verifying required fastlane version                           | 0           |
| 2    | default_platform                                              | 0           |
| 3    | /usr/libexec/plistbuddy -c 'Set CFBundleVersion -1' '../Hugin | 0           |
| 4    | /usr/libexec/plistbuddy -c 'Set CFBundleShortVersionString 0. | 0           |
| 5    | mailgun                                                       | 1           |
+------+---------------------------------------------------------------+-------------+

[13:47:55]: fastlane.tools finished successfully 🎉
```
So I assume this would work, debugging mailgun.rb in fastlane adding `puts` I see 
```
  def self.mailgunit(options)
        sandbox_domain = options[:postmaster].split("@").last
        puts sandbox_domain
        params = {
          from: "#{options[:from]}<#{options[:postmaster]}>",
          to: (options[:to]).to_s,
          subject: options[:subject],
          html: mail_template(options)
        }
        puts params
```

output:
```
{:from=>"Mailgun Sandbox <postmaster@sandboxxxx.mailgun.org><https://api.mailgun.net/v3/sandboxxxx.mailgun.org/messages>", :to=>
``` 
So it seems wrong however changing it to `from: "<#{options[:postmaster]}>"` didnt help either.

Also this line too in mailgun.rb throws me off 
` RestClient.post "https://api:#{options[:apikey]}@api.mailgun.net/v3/#{sandbox_domain}/messages", params` 

Isnt this supposed to be ? 
`https://api.mailgun.net/v3/#{sandbox_domain}/messages`

So I tried `RestClient.post " https://api.mailgun.net/v3/sandboxxxxx.mailgun.org/messages" ,params` and I got a 401 error. 

What to do here? Why my emails are not making it to Mailgun Server? 

I don't see any requests in Mailgun dashboard logs, besides the one that I made thru terminal

@thiagofelix

**Comment by ugenlik** [comment]
After I had to use deprecated methods to be able to send an email thru Mailgun. I suck at ruby but I will make a pull request. 

for now this works 

```
    ENV['MAILGUN_SANDBOX_POSTMASTER'] = 'mailgun@sandboxxxxxx.mailgun.org'
    ENV['MAILGUN_APIKEY'] = 'key-1xxxxxxxxxxx7'
    ENV['MAILGUN_APP_LINK'] = 'https://www.google.com'

    mailgun(to: "iosrobot@domain.com",
        from: "Ugenlik",
        subject: "Fastlane Beta",
        message: "App is successfully deployed to Hockey App.",
        success: true
     )
```

**Comment by yonivav** [comment]
smae problem for me. i can send through Curl, but not in fastlane
