### ISSUE TITLE
Spaceship: Get previous app version sizes?

### ISSUE THREAD

**Issue by daniel-beard** [fastlane/fastlane#8853]
It doesn't seem to be possible right now to get the binary sizes of previous App versions through the AppVersion history (for iTunesConnect sizes). Is this data returned by the API right now? If not, can I request that as a new feature?

**Comment by daniel-beard** [comment]
No, newer versions do not include this functionality.

**Comment by mpirri** [comment]
@daniel-beard are you able to view this information in iTunesConnect currently? I'm not seeing it in the build list or info, and perhaps it was moved in the recent changes to iTC.  For the most part, any information that is shown in iTunesConnect is something that _fastlane_ can access.

**Comment by daniel-beard** [comment]
Hi, yes I can still see this on iTunesConnect, and would *love* to be able to retrieve it with spaceship.

`Activity > All Builds > Click on a build number > "AppStore File Sizes"`

<img width="801" alt="screen shot 2017-06-20 at 1 31 02 pm" src="https://user-images.githubusercontent.com/2645146/27355112-a0bb9d54-55be-11e7-966d-454a33b1e5f8.png">

**Comment by mpirri** [comment]
Ah, cool!  While I agree that it would be great to have this feature, I'm afraid that it isn't something that the _fastlane_ team can take on right now. We'd be happy to review a PR that added this functionality to `spaceship` however. I don't suppose we could coerce you to try your hand at implementing this feature? We are happy to answer questions and provide guidance, of course. 🚀

**Comment by daniel-beard** [comment]
I can take a bit of a look, can you point me in the direction of the closest API call to this one? Is there one that exists for the "All Builds" page?

**Comment by mpirri** [comment]
We have this document that talks you through using a tool like Charles Proxy to observe how to make network calls to iTunes Connect:
https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md

This document also describes how `spaceship` is structured and provides advice about how to add new functionality.

In terms of similar API calls - you can look at the code for the `Spaceship::TestFlight::Build` object here:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/test_flight/build.rb

`Spaceship::TestFlight::Build` calls into the `Spaceship::TestFlight::Client` object to make the API calls:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/test_flight/client.rb

I haven't used Charles to look at this particular API call, but you should be able to start Charles recording and then click on that `App Store File Sizes` to see the API call that iTC makes. From there, create a model object for the sizes and associated API call methods in the client.

I hope this is helpful, please let us know what other questions you have!  Thanks!!  🚀

**Comment by daniel-beard** [comment]
@mpirri I looked at this further, it looks like I can already get at this information using the `Tunes::Client`'s `all_builds_for_train` call. Closing this issue, thanks for the help!

**Comment by KrauseFx** [comment]
Oh that's awesome, thanks for updating the issue, this is great 👍

**Comment by KrauseFx** [comment]
@daniel-beard if you feel like it, it would be awesome to have that as part of the `iTunesConnect.md` documentation 👍
