### ISSUE TITLE
Is there a way to have snapshot scale to 75% before opening up the simulator?

### ISSUE THREAD

**Issue by lam2558** [fastlane/fastlane#8854]
I have notice that when snapshot run, it open in 100%

[12:04:14]: Patching '/Users/jenkins/Library/Preferences/com.apple.iphonesimulator.plist' to scale simulator to 100%

This would take forever too boot and usually time out. When i rescale to 75 % or 50% and close out the simulator, snapshot would continue onward and reopen it again with smaller scale and it would boot correctly.

**Comment by lam2558** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.2                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.3 (Apple Git-75)            |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.2.2/lib            |
| OpenSSL Version             | OpenSSL 1.0.2a 19 Mar 2015                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.25.0  | 🚫 Update available |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| slack-notifier            | 1.4.0   |
| i18n                      | 0.7.0   |
| json                      | 1.8.1   |
| thread_safe               | 0.3.5   |
| tzinfo                    | 1.2.2   |
| minitest                  | 5.4.3   |
| activesupport             | 4.2.4   |
| colored                   | 1.2     |
| claide                    | 0.9.1   |
| xcodeproj                 | 0.28.2  |
| rouge                     | 1.10.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.6.3   |
| terminal-table            | 1.4.5   |
| plist                     | 3.1.0   |
| addressable               | 2.3.8   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| tty-screen                | 0.5.0   |
| babosa                    | 1.0.2   |
| highline                  | 1.7.8   |
| commander-fastlane        | 4.4.4   |
| excon                     | 0.45.4  |
| faraday                   | 0.9.2   |
| unf_ext                   | 0.0.7.1 |
| unf                       | 0.1.4   |
| domain_name               | 0.5.25  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| mime-types                | 2.6.2   |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.11.2  |
| logging                   | 2.0.0   |
| jwt                       | 1.5.2   |
| memoist                   | 0.12.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.2   |
| googleauth                | 0.5.1   |
| thor                      | 0.19.1  |
| httpclient                | 2.8.0   |
| google-api-client         | 0.9.8   |
| mini_magick               | 4.5.1   |
| multi_xml                 | 0.5.5   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.3   |
| dotenv                    | 2.1.1   |
| bundler                   | 1.12.5  |
| faraday_middleware        | 0.10.0  |
</details>


*generated on:* **2017-04-11**
</details>

**Comment by RyanCopley** [comment]
https://github.com/fastlane/fastlane/blob/60bac7e4a2a6c1e19d1cd20eb83201e7d0cb9e48/snapshot/lib/snapshot/fixes/simulator_zoom_fix.rb#L16 indicates `no`. Perhaps you can edit your local copy, but that's ill advised.

**Comment by KrauseFx** [comment]
Why do you want to scale it differently? The screenshots will still have the same resolution

**Comment by KrauseFx** [comment]
As @RyanCopley said, it's not possible, and I currently don't know of a reason why it should be added

**Comment by lam2558** [comment]
snapshot open simulator in 100% scale, but the simulator is unable to load all the way. it remain at around 80% for an unlimited amount of time before i manually close and reopen in 75%.
