### ISSUE TITLE
Scan: Simulator Timeout only on Jenkins Server

### ISSUE THREAD

**Issue by robbykim** [fastlane/fastlane#8855]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've been reading around about this issue but haven't been able to find something that works for my particular situation. My personal machine is a Macbook Pro and we have a MacPro that we use as our Jenkins CI server. 

Currently, I'm running the following configuration for **scan**:

    scan(
        project: "myProject.xcodeproj",
        devices: ["iPhone 7", "iPhone 7 Plus"],
        clean: true,
    )

This runs great on my local machine and when I run it on my local machine AND when I physically go onto our MacPro and run it. On the MacPro, I can run it properly without issue in the local account's directory of the project AND in the actual Jenkins workspace that is being accessed from the Jenkins GUI in the browser. However, when I run the build from the Jenkins browser GUI, I get the `Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Timed out waiting 120 seconds for simulator to boot, current state is 1.`

I've tried and confirmed answer found here: https://github.com/fastlane/fastlane/issues/1943#issuecomment-230470117
It works on Jenkins however, my implementation of it has been to have 2 different scans run, one with "iPhone 7" and the other with "iPhone 7 Plus". The problem with this is if we have a failing test, it will stop in the iPhone 7 test and won't run the iPhone 7 Plus tests. I want to be able to run tests on both devices and see everything via the `*.junit` and `.html` reports. 

Any help would be awesome!

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

    15:33:56 + fastlane test_build
	15:33:56 [15:33:56]: [32m-------------------------------------------------[0m
	15:33:56 [15:33:56]: [32m--- Step: Verifying required fastlane version ---[0m
	15:33:56 [15:33:56]: [32m-------------------------------------------------[0m
	15:33:56 [15:33:56]: Your fastlane version 2.26.1 matches the minimum requirement of 2.19.3  ✅
	15:33:56 [15:33:56]: [32m------------------------------[0m
	15:33:56 [15:33:56]: [32m--- Step: default_platform ---[0m
	15:33:56 [15:33:56]: [32m------------------------------[0m
	15:33:56 [15:33:56]: [32mDriving the lane 'ios test_build' 🚀[0m
	15:33:56 [15:33:56]: [32m-------------------------------------[0m
	15:33:56 [15:33:56]: [32m--- Step: Switch to ios test lane ---[0m
	15:33:56 [15:33:56]: [32m-------------------------------------[0m
	15:33:56 [15:33:56]: Cruising over to lane 'ios test' 🚖
	15:33:56 [15:33:56]: [32m------------------[0m
	15:33:56 [15:33:56]: [32m--- Step: scan ---[0m
	15:33:56 [15:33:56]: [32m------------------[0m
	15:33:56 [15:33:56]: [4m[36m$ xcodebuild -list -project myProject.xcodeproj[0m[0m
	15:33:57 [15:33:57]: [4m[36m$ xcodebuild clean -showBuildSettings -scheme myProject -project myProject.xcodeproj[0m[0m
	15:33:57 [15:33:57]: [4m[36m$ xcodebuild -list -project myProject.xcodeproj[0m[0m
	15:33:58 [15:33:58]: [4m[36m$ xcodebuild clean -showBuildSettings -scheme myProject -project myProject.xcodeproj[0m[0m
	15:33:59 
	15:33:59 +------------------------+-------------------------------------------------------------------------+
	15:33:59 |                                     [32mSummary for scan 2.26.1[0m                                      |
	15:33:59 +------------------------+-------------------------------------------------------------------------+
	15:33:59 | project                | myProject.xcodeproj                                                 |
	15:33:59 | devices                | ["iPhone 7", "iPhone 7 Plus"]                                           |
	15:33:59 | clean                  | true                                                                    |
	15:33:59 | scheme                 | myProject                                                           |
	15:33:59 | derived_data_path      | /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffl... |
	15:33:59 | skip_build             | false                                                                   |
	15:33:59 | output_directory       | ./fastlane/test_output                                                  |
	15:33:59 | output_types           | html,junit                                                              |
	15:33:59 | buildlog_path          | ~/Library/Logs/scan                                                     |
	15:33:59 | include_simulator_logs | false                                                                   |
	15:33:59 | open_report            | false                                                                   |
	15:33:59 | skip_slack             | false                                                                   |
	15:33:59 | slack_only_on_failure  | false                                                                   |
	15:33:59 | use_clang_report_name  | false                                                                   |
	15:33:59 | fail_build             | true                                                                    |
	15:33:59 | xcode_path             | /Applications/Xcode.app                                                 |
	15:33:59 +------------------------+-------------------------------------------------------------------------+
	15:33:59 
	15:33:59 [15:33:59]: [4m[36m$ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme myProject -project myProject.xcodeproj -destination 'platform=iOS Simulator,id=AEE1A727-DC09-4537-BDDD-D26188E995D1' -destination 'platform=iOS Simulator,id=713A5AB3-B938-4801-9F2E-46B97FADA560' -derivedDataPath '/Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh' clean build test | tee '/Users/jenkins/Library/Logs/scan/myProject-myProject.log' | xcpretty [0m[0m
	15:33:59 [15:33:59]: ▸ [35mLoading...[0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mCleaning[0m myProject/myProject [Debug][0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mClean[0m Succeeded[0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mCleaning[0m myProject/myProject [Debug][0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mClean[0m Succeeded[0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mBuilding[0m myProject/myProject [Debug][0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
	15:34:00 [15:34:00]: [35m[33m▸[0m [39;1mCompiling[0m EventTimelineVC.swift[0m
	15:34:01 [15:34:01]: [35m[33m▸[0m [39;1mCompiling[0m AppDelegate.swift[0m
	15:34:01 [15:34:01]: [35m[33m▸[0m [39;1mCompiling[0m ComparisonViewVC.swift[0m
	15:34:01 [15:34:01]: [35m[33m▸[0m [39;1mCompiling[0m HomeVC.swift[0m
	15:34:01 [15:34:01]: [35m[33m▸[0m [39;1mLinking[0m myProject[0m
	15:34:01 [15:34:01]: [35m[33m▸[0m [39;1mCompiling[0m LaunchScreen.storyboard[0m
	15:34:02 [15:34:02]: [35m[33m▸[0m [39;1mCompiling[0m Main.storyboard[0m
	15:34:02 [15:34:02]: [35m[33m▸[0m [39;1mProcessing[0m Info.plist[0m
	15:34:02 [15:34:02]: [35mRunning Tests: [33m▸[0m [39;1mTouching[0m myProject.app[0m
	15:34:02 [15:34:02]: [35m[33m▸[0m [39;1mSigning[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Build/Products/Debug-iphonesimulator/myProject.app[0m
	15:34:02 [15:34:02]: [35m[33m▸[0m [39;1mBuild[0m Succeeded[0m
	15:34:02 [15:34:02]: [35m[33m▸[0m [39;1mBuilding[0m myProject/myProject [Debug][0m
	15:34:02 [15:34:02]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
	15:34:03 [15:34:03]: [35m[33m▸[0m [39;1mProcessing[0m Info.plist[0m
	15:34:03 [15:34:03]: [35m[33m▸[0m [39;1mSigning[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Build/Products/Debug-iphonesimulator/myProject.app[0m
	15:34:03 [15:34:03]: [35m[33m▸[0m [39;1mBuild[0m Succeeded[0m
	15:34:03 [15:34:03]: ▸ [35m2017-04-11 15:34:03.827 xcodebuild[50396:124464]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:[0m
	15:34:03 [15:34:03]: ▸ [35m/Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Logs/Test/8AE7FB37-CE4C-4DD3-BD5E-8072355AB628/Session-myProjectTests-2017-04-11_153403-5fposP.log[0m
	15:34:03 [15:34:03]: ▸ [35m2017-04-11 15:34:03.827 xcodebuild[50396:124159] [MT] IDETestOperationsObserverDebug: (2E7E2A84-FAE1-4940-A04E-71BEF70914B7) Beginning test session myProjectTests-2E7E2A84-FAE1-4940-A04E-71BEF70914B7 at 2017-04-11 15:34:03.826 with Xcode 8C1002 on target <DVTiPhoneSimulator: 0x7fc6aaed8fe0> {[0m
	15:34:03 [15:34:03]: ▸ [35mSimDevice: SimDevice : iPhone 7 (AEE1A727-DC09-4537-BDDD-D26188E995D1) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7 } runtime={ SimRuntime : 10.2 (14C89) - com.apple.CoreSimulator.SimRuntime.iOS-10-2 }[0m
	15:34:03 [15:34:03]: ▸ [35m} (10.2 (14C89))[0m
	15:34:03 [15:34:03]: ▸ [35m2017-04-11 15:34:03.849 xcodebuild[50396:124159] [MT] IDETestOperationsObserverDebug: (091B318D-DAB3-4FA4-8C6F-067D417E030E) Beginning test session myProjectUITests-091B318D-DAB3-4FA4-8C6F-067D417E030E at 2017-04-11 15:34:03.849 with Xcode 8C1002 on target <DVTiPhoneSimulator: 0x7fc6aaed8fe0> {[0m
	15:34:03 [15:34:03]: ▸ [35mSimDevice: SimDevice : iPhone 7 (AEE1A727-DC09-4537-BDDD-D26188E995D1) : state={ Shutdown } deviceType={ SimDeviceType : com.apple.CoreSimulator.SimDeviceType.iPhone-7 } runtime={ SimRuntime : 10.2 (14C89) - com.apple.CoreSimulator.SimRuntime.iOS-10-2 }[0m
	15:34:03 [15:34:03]: ▸ [35m} (10.2 (14C89))[0m
	15:34:03 [15:34:03]: ▸ [35m2017-04-11 15:34:03.849 xcodebuild[50396:124167]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:[0m
	15:34:03 [15:34:03]: ▸ [35m/Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Logs/Test/8AE7FB37-CE4C-4DD3-BD5E-8072355AB628/Session-myProjectUITests-2017-04-11_153403-rX2loS.log[0m
	15:34:03 [15:34:03]: [35m[33m▸[0m [39;1mBuilding[0m myProject/myProject [Debug][0m
	15:34:03 [15:34:03]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
	15:34:04 [15:34:04]: [35m[33m▸[0m [39;1mProcessing[0m Info.plist[0m
	15:34:04 [15:34:04]: [35m[33m▸[0m [39;1mSigning[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Build/Products/Debug-iphonesimulator/myProject.app[0m
	15:34:04 [15:34:04]: [35m[33m▸[0m [39;1mBuilding[0m myProject/myProjectTests [Debug][0m
	15:34:04 [15:34:04]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
	15:34:04 [15:34:04]: [35m[33m▸[0m [39;1mProcessing[0m Info.plist[0m
	15:34:04 [15:34:04]: [35m[33m▸[0m [39;1mCompiling[0m show_and_tellTests.swift[0m
	15:34:05 [15:34:05]: [35m[33m▸[0m [39;1mLinking[0m myProjectTests[0m
	15:34:05 [15:34:05]: [35mRunning Tests: [33m▸[0m [39;1mTouching[0m myProjectTests.xctest[0m
	15:34:05 [15:34:05]: [35m[33m▸[0m [39;1mSigning[0m /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Build/Products/Debug-iphonesimulator/myProject.app/PlugIns/myProjectTests.xctest[0m
	15:34:05 [15:34:05]: [35m[33m▸[0m [39;1mBuilding[0m myProject/myProjectUITests [Debug][0m
	15:34:05 [15:34:05]: [35m[33m▸[0m [39;1mCheck Dependencies[0m[0m
	15:36:03 [15:36:03]: ▸ [35m2017-04-11 15:36:03.834 xcodebuild[50396:124464]  iOSSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.[0m
	15:36:03 [15:36:03]: ▸ [35m2017-04-11 15:36:03.846 xcodebuild[50396:124170]  iOSSimulator: Timed out waiting 120 seconds for simulator to boot, current state is 1.[0m
	15:36:03 [15:36:03]: ▸ [35m2017-04-11 15:36:03.847 xcodebuild[50396:124159] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Logs/Test/8AE7FB37-CE4C-4DD3-BD5E-8072355AB628/Session-myProjectTests-2017-04-11_153403-5fposP.log" UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Logs/Test/8AE7FB37-CE4C-4DD3-BD5E-8072355AB628/Session-myProjectTests-2017-04-11_153403-5fposP.log}[0m
	15:36:03 [15:36:03]: ▸ [35m2017-04-11 15:36:03.847 xcodebuild[50396:124159] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Logs/Test/8AE7FB37-CE4C-4DD3-BD5E-8072355AB628/Session-myProjectUITests-2017-04-11_153403-rX2loS.log" UserInfo={NSLocalizedDescription=Timed out waiting 120 seconds for simulator to boot, current state is 1. If you believe this error represents a bug, please attach the log file at /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Logs/Test/8AE7FB37-CE4C-4DD3-BD5E-8072355AB628/Session-myProjectUITests-2017-04-11_153403-rX2loS.log}[0m
	15:36:41 +----------------------------+---------------------------------------------------------------------+
	15:36:41 |                                           [33mLane Context[0m                                           |
	15:36:41 +----------------------------+---------------------------------------------------------------------+
	15:36:41 | DEFAULT_PLATFORM           | ios                                                                 |
	15:36:41 | PLATFORM_NAME              | ios                                                                 |
	15:36:41 | LANE_NAME                  | ios test_build                                                      |
	15:36:41 | SCAN_DERIVED_DATA_PATH     | /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject... |
	15:36:41 | SCAN_GENERATED_PLIST_FILES | ["/Users/jenkins/Library/Developer/Xcode/DerivedData/show-and-te... |
	15:36:41 | SCAN_GENERATED_PLIST_FILE  | /Users/jenkins/Library/Developer/Xcode/DerivedData/myProject... |
	15:36:41 +----------------------------+---------------------------------------------------------------------+
	15:36:41 Build was aborted
	15:36:41 Aborted by robby

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

    ### Stack

    | Key                         | Value                                       |
    | --------------------------- | ------------------------------------------- |
    | OS                          | 10.11.6                                     |
    | Ruby                        | 2.3.1                                       |
    | Bundler?                    | false                                       |
    | Git                         | git version 2.10.1 (Apple Git-78)           |
    | Installation Source         | /usr/local/bin/fastlane                     |
    | Host                        | Mac OS X 10.11.6 (15G31)                    |
    | Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib            |
    | OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
    | Is contained                | false                                       |
    | Is homebrew                 | false                                       |
    | Is installed via Fabric.app | false                                       |
    | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
    | Xcode Version               | 8.2.1                                       |

    ### System Locale

    | Variable | Value       |   |
    | -------- | ----------- | - |
    | LANG     | en_US.UTF-8 | ✅ |
    | LC_ALL   |             |   |
    | LANGUAGE |             |   |

    ### fastlane files:

    <details><summary>`./fastlane/Fastfile`</summary>

    ```ruby
    # Define the minimal Fastlane version
    fastlane_version "2.19.3"

    # Use the iOS platform as default
    default_platform :ios

    # Define what to do for the iOS platform
    platform :ios do
        private_lane :build_app do |options|
            update_app_identifier(
                xcodeproj: "#{options[:project_name]}.xcodeproj",
                plist_path: "#{options[:project_name]}/Info.plist",
                app_identifier: options[:app_identifier]
            )

            import_certificate(
                certificate_path: options[:certificate_path],
                certificate_password: options[:certificate_password],
                keychain_name: "login.keychain"
            )

            gym(
                scheme: "#{options[:scheme]}",
                configuration: options[:configuration],
                provisioning_profile_path: options[:profile],
                codesigning_identity: options[:codesigning_identity],
                export_method: options[:export_method]
            )
        end

        private_lane :publish_enterprise do |options|
            puts "Running Publish Enterprise Lane"
            sh "/bin/sh ../scripts/ci-enterprise-dist.sh"
        end

        private_lane :publish_appstore do |options|
            puts "publishing to app store"
        end

        private_lane :organizer_copy_archive do
            sh "/bin/sh ../scripts/check-directory.sh"
            sh "cp -R ${EXPORT_ARCHIVE} ~/Library/Developer/Xcode/Archives/$(date +%Y-%m-%d)/${EXPORT_FILENAME}-$(date +%Y-%m-%d-%H.%M.%S)-${EXPORT_BUILD_TYPE}.xcarchive"
        end

        private_lane :tar_artifacts do
            sh "/bin/sh ../scripts/tar-artifacts.sh"
        end

        lane :test do
          scan(
            project: "myProject.xcodeproj",
            devices: ["iPhone 7", "iPhone 7 Plus"],
            clean: true,
          )
        end

        lane :build_enterprise do
            test

            build_app(
                app_name: "App Name",
                app_identifier: "com.company.app",
                certificate_path: "./fastlane/certs/EnterpriseCertificate.p12",
                certificate_password: "password",
                profile: "./fastlane/certs/Enterprise.mobileprovision",
                configuration: "Enterprise",
                codesigning_identity: "iPhone Distribution",
                export_method: "enterprise",
                project_name: "myProject",
                scheme: "myProject",
                build_number: ENV["BUILD_NUMBER"]
            )

            organizer_copy_archive
            tar_artifacts
            publish_enterprise
        end
    end

    ```
    </details>

    <details><summary>`./fastlane/Appfile`</summary>

    ```ruby
    app_identifier "com.company.app" # The bundle identifier of your app
    apple_id "apple@company.com" # Your Apple email address

    team_id "SOME NUMBER"  # Developer Portal Team ID

    # you can even provide different app identifiers, Apple IDs and team names per lane:
    # More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
    ```
    </details>

    ### fastlane gems

    | Gem      | Version | Update-Status |
    | -------- | ------- | ------------- |
    | fastlane | 2.26.1  | ✅ Up-To-Date  |

    ### Loaded fastlane plugins:

    **No plugins Loaded**

    <details><summary><b>Loaded gems</b></summary>

    | Gem                       | Version      |
    | ------------------------- | ------------ |
    | did_you_mean              | 1.0.0        |
    | slack-notifier            | 1.5.1        |
    | i18n                      | 0.7.0        |
    | json                      | 1.8.3        |
    | thread_safe               | 0.3.5        |
    | tzinfo                    | 1.2.2        |
    | minitest                  | 5.8.3        |
    | activesupport             | 4.2.6        |
    | colored                   | 1.2          |
    | claide                    | 1.0.0        |
    | xcodeproj                 | 1.0.0        |
    | rouge                     | 1.11.1       |
    | xcpretty                  | 0.2.4        |
    | terminal-notifier         | 1.7.1        |
    | unicode-display_width     | 1.1.3        |
    | terminal-table            | 1.7.3        |
    | plist                     | 3.2.0        |
    | public_suffix             | 2.0.5        |
    | addressable               | 2.5.0        |
    | multipart-post            | 2.0.0        |
    | word_wrap                 | 1.0.0        |
    | tty-screen                | 0.5.0        |
    | babosa                    | 1.0.2        |
    | highline                  | 1.7.8        |
    | commander-fastlane        | 4.4.4        |
    | excon                     | 0.55.0       |
    | faraday                   | 0.11.0       |
    | unf_ext                   | 0.0.7.2      |
    | unf                       | 0.1.4        |
    | domain_name               | 0.5.20170223 |
    | http-cookie               | 1.0.3        |
    | faraday-cookie_jar        | 0.0.6        |
    | fastimage                 | 2.1.0        |
    | gh_inspector              | 1.0.3        |
    | uber                      | 0.0.15       |
    | representable             | 2.3.0        |
    | retriable                 | 2.1.0        |
    | mime-types-data           | 3.2016.0521  |
    | mime-types                | 3.1          |
    | hurley                    | 0.2          |
    | little-plugger            | 1.1.4        |
    | multi_json                | 1.12.1       |
    | logging                   | 2.2.0        |
    | jwt                       | 1.5.6        |
    | memoist                   | 0.15.0       |
    | os                        | 0.9.6        |
    | signet                    | 0.7.3        |
    | googleauth                | 0.5.1        |
    | httpclient                | 2.8.3        |
    | google-api-client         | 0.9.28       |
    | mini_magick               | 4.5.1        |
    | multi_xml                 | 0.6.0        |
    | rubyzip                   | 1.2.1        |
    | security                  | 0.1.3        |
    | xcpretty-travis-formatter | 0.0.4        |
    | dotenv                    | 2.2.0        |
    | bundler                   | 1.14.6       |
    | faraday_middleware        | 0.11.0.1     |
    | io-console                | 0.4.5        |
    </details>

    *generated on:* **2017-04-11**
    </details>

**Comment by thebugcode** [comment]
Hi. 
I've experienced the same issues. To solve `Timed out waiting 120 seconds` issues please run
`killall "Simulator" || true` so that if there are no simulators to kill your jenkins job continues.

**Comment by robbykim** [comment]
awesome! that fixed the issue. thanks!

**Comment by robbykim** [comment]
Ahhh actually that didn't help. Another issue came up that made it seem like it was helping but I'm still getting `Timed out waiting 120 seconds for simulator to boot, current state is 1`

**Comment by thebugcode** [comment]
Do you have access to the machine running this? Can you try running this on it?
`fastlane scan --project "myproject.xcodeproj" --devices "iPhone 7" --clean`

Rationale: Its obvious simulators wont start. That is either because they are corrupted (Try `fastlane run reset_simulator_contents`) or because they are missing. What CI are you running on?

**Comment by thebugcode** [comment]
Also, try with different simulators. If you can run tests from Xcode on this machine, you can also do so with fastlane. 
One more thing I know is that if your mac is slow, you will also get this timetout. HDD Mac mini's are often slow.

**Comment by robbykim** [comment]
@thebugcode so I ran the `fastlane scan ...` command on the machine and it works perfectly fine. It seems like its only when its trigger through the CI that is having the issues. Tests work on Xcode, with iPhones 6, 7, 6 Plus, 7 Plus. The computer is a MacPro with a SSD so slowness _shouldn't_ be an issue though it very well might.

We're using Jenkins as our CI tool

**Comment by thebugcode** [comment]
In that case if fastlane can boot the simulator and run tests, and we can pinpoint this issue to only when running from Jenkins I would suggest this. Can you check and confirm that the user on which this command is executed is logged in. (In your case that seems to be the jenkins user)

Also, another hunch is to look carefully into the following log file `/Users/jenkins/Library/Developer/Xcode/DerivedData/myProject-ffloonwqwafhknbdfzayqdyeaveh/Logs/Test/8AE7FB37-CE4C-4DD3-BD5E-8072355AB628/Session-myProjectTests-2017-04-11_153403-5fposP.log`  It changes per session, but you will see it in the output. Usually this raw log tells you whats going on, maybe you need to unlock the keychain, maybe something else is going on

**Comment by franckclement** [comment]
@robbykim I'm facing the same issue with Jenkins, 
I encounter Simulator timeout when running scan on CI, Simulator icon shows up on the slave macOS but the application is not loading, no Simulator window is visible.

FYI my macOS Jenkins slave is connected to the master through Java Web Start, because SSH connection does not have GUI context, so can not open the Simulator.

Do you solved it ?

**Comment by robbykim** [comment]
@franckclement I haven't been able to fix it and went with a work around but the problem with the work around is that it only tests it on one type of iPhone simulator (i.e. iPhone 7) which isn't the greatest but for what I needed it does the job...
