### ISSUE TITLE
[spaceship] Unable to start spaceship playground

### ISSUE THREAD

**Issue by philippsandhaus** [fastlane/fastlane#8865]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am unable to start the spaceship playground as described in the docs. Instead I get the following error:

    ➜  ~ fastlane spaceship
    WARN: Unresolved specs during Gem::Specification.reset:
          mime-types (>= 1.6)
    WARN: Clearing out unresolved specs.
    Please report a bug if this causes problems.
    spaceship can't be called via `fastlane spaceship`, run 'spaceship' directly instead
    ➜  ~ spaceship
    zsh: command not found: spaceship

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| json                      | 1.8.6        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| minitest                  | 5.10.1       |
| activesupport             | 4.2.7.1      |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-04-12**
</details>

**Comment by mpirri** [comment]
So, I suspect the warning about `mime-types` is unrelated to the error on running `fastlane spaceship`. I actually had a similar warning about `mime-types` on my system, which I resolved by doing `gem uninstall mime-types; gem install mime-types`.

I'm curious to know if the same problem affects other `fastlane` tools, try doing `fastlane pilot` and see if you get the usage message for the `pilot` tool.

**Comment by philippsandhaus** [comment]
Thank you for the tip regarding the mime-types issue. At least this removes the warning for me. `fastlane pilot` shows the expected usage message for me. Any ideas why `fastlane spaceship` does not work?

**Comment by philippsandhaus** [comment]
I tried to dig in the problem myself. What I did was to create my own development environment for fast lane as described in the docs and tried to call the command there:

    bundler: failed to load command: fastlane (/usr/local/lib/ruby/gems/2.4.0/bin/fastlane)
    LoadError: dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/byebug.bundle, 9):     Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib
    Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/byebug.bundle
    Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/byebug.bundle
    /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/core.rb:2:in `require'
    /usr/local/lib/ruby/gems/2.4.0/gems/byebug-9.0.6/lib/byebug/core.rb:2:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/byebug/processors/pry_processor.rb:1:in `require'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/byebug/processors/pry_processor.rb:1:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:1:in `require'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:1:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/pry-byebug/cli.rb:2:in `require'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-byebug-3.4.2/lib/pry-byebug/cli.rb:2:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry/plugins.rb:38:in `require'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry/plugins.rb:38:in `load_cli_options'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry/cli.rb:40:in `block in add_plugin_options'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry/cli.rb:39:in `each'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry/cli.rb:39:in `add_plugin_options'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry/cli.rb:107:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry.rb:150:in `require'
    /usr/local/lib/ruby/gems/2.4.0/gems/pry-0.10.4/lib/pry.rb:150:in `<top (required)>'
    /Users/sandhaus/fastlane/spaceship/lib/spaceship/playground.rb:24:in `require'
    /Users/sandhaus/fastlane/spaceship/lib/spaceship/playground.rb:24:in `initialize'
    /Users/sandhaus/fastlane/spaceship/lib/spaceship/commands_generator.rb:31:in `new'
    /Users/sandhaus/fastlane/spaceship/lib/spaceship/commands_generator.rb:31:in `block (2 levels) in run'
    /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
    /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
    /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
    /Users/sandhaus/fastlane/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
    /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
    /Users/sandhaus/fastlane/spaceship/lib/spaceship/commands_generator.rb:46:in `run'
    /Users/sandhaus/fastlane/spaceship/lib/spaceship/commands_generator.rb:12:in `start'
    /Users/sandhaus/fastlane/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
    /Users/sandhaus/fastlane/bin/fastlane:20:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:22:in `load'
    /usr/local/lib/ruby/gems/2.4.0/bin/fastlane:22:in `<top (required)>'

So what I did then was to exec a `gem install byebug`which solved my problem. But I guess this gem should already have been installed as a dependency of another gem, I guess `pry`?
