### ISSUE TITLE
gym: use libcurl to access Apple APIs

### ISSUE THREAD

**Issue by t-8ch** [fastlane/fastlane#8868]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Currently the connections to the Apple APIs fail when using the system provided ruby on OSX.
This is because the Apple APIs require TLS 1.2 which the system ruby with its system openssl can't provide.
There are various reports for this issue.

One possible solution would be to switch the backend of [faraday]( https://github.com/lostisland/faraday) (the HTTP library used in gym) to a libcurl based one. The system libcurl is linked to the Apples TLS library which supports TLS 1.2 is kept up to date via normal system updates.
Switching the backend should not require any other code changes to other parts of gym.

There seem several libcurl based backends included in faraday and probably more available.
I tried two and ran into different errors which were not trivially fixable by me (a non-ruby, non-OSX person).

Would this be something the fastlanes devs would be willing to explore or to accept a contribution for?

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                                         |
| --------------------------- | ----------------------------------------------------------------------------- |
| OS                          | 10.12.4                                                                       |
| Ruby                        | 2.0.0                                                                         |
| Bundler?                    | true                                                                          |
| Git                         | git version 2.8.4 (Apple Git-73)                                              |
| Installation Source         | /private/var/lib/jenkins-slave/fastlane/vendor/bundle/ruby/2.0.0/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)                                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib                |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                                   |
| Is contained                | false                                                                         |
| Is homebrew                 | false                                                                         |
| Is installed via Fabric.app | false                                                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                   |
| Xcode Version               | 8.0                                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.26.1  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.2       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.3      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.0.1     |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.4        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-04-12**
</details>

**Comment by KrauseFx** [comment]
I don't think it will be easy and feasible to migrate all the code to use a different HTTP client. However maybe we can find a different way to make it work? We definitely want to fix the installation out of the box

**Comment by t-8ch** [comment]
Gym already uses faraday.
Maybe this was not clear enough :-)
Only the configured backend would have to change.

**Comment by KrauseFx** [comment]
Not sure what you mean. The backend is provided by Apple, or what backend do you mean?

**Comment by hjanuschka** [comment]
@KrauseFx i think @t-8ch means that you can change the network adapter in faraday. https://github.com/lostisland/faraday/blob/master/lib/faraday/adapter.rb

@t-8ch which of the available adapters was the one that worked best for you?

**Comment by t-8ch** [comment]
After some research it seems the only officially supported backend seems to be [patron](https://toland.github.io/patron/).
I did not get it to work easily though. (Not a ruby/OSX guy).

I am willing though to get it to work properly if there is interest of adding it to the fastlane testmatrix, so I can be sure that it keeps working.
(The fixing would take place in the faraday/patron adapter, fastlane will still only have to change on line)

**Comment by t-8ch** [comment]
To make the bot happy:
I am still willing to implement libcurl support if it gets added to the automated tests of fastlane to make sure it keeps working.

**Comment by ohayon** [comment]
Hey @t-8ch! Thanks for offering to implement that support. I think a good workaround for now might be to use the homebrew-installed version of _fastlane_ (`brew cask install fastlane`) as that comes with it's own bundled version of ruby so we don't have to worry about what the system ruby can do.

I am going to close this issue for now as it seems like it's not something we want to do at the moment but we will reopen the issue if it comes up again and please feel free to continue discussion if you would like to talk about it some more! 🚀
