### ISSUE TITLE
Can you add the |options| argument to the Appfile's for_lane ?

### ISSUE THREAD

**Issue by MtotheH** [fastlane/fastlane#8870]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Currently we use the `lane :beta do |options|` with the help of `options[:scheme] ` to build a specific scheme:

```
...
gym(
   scheme: options[:scheme],
   output_directory: "fastlane/build_tmp/"
)
...
```

Depending on the scheme we net to use another team_id, itc_team_id and app_identifier. Is there any other way to pass the options arguments to the `for_lane :first do` method in the Appfile? So we can discard the following workaround:

```
lane :beta do |options|
  ...
  setupAppfile(options)
  ...
  gym(
     scheme: options[:scheme],
     output_directory: "fastlane/build_tmp/"
  )
  ...
end

desc "Workaround: Calls special lane for scheme"
desc ""
desc "hint:"
desc "- update if fastlanes Appfile provides a options argument"
def setupAppfile(options)
  if options[:scheme] == "First"
    first
  end
  if options[:scheme] == "Second"
    second
  end
end

desc "Workaround: Placeholder lane for Appfile"
lane :first do
end
desc "Workaround: Placeholder lane for Appfile"
lane :second do
end
```

Appfile:
```
app_identifier "com.dummy.first" # The default bundle identifier of your app
apple_id "dummy@company.com" # Your Apple email address

team_id "987654321"  # Default Developer Portal Team ID
itc_team_id "987654321" # Default iTunes Connect Team ID

for_platform :ios do
  
  for_lane :first do
        team_id "987654321" # Developer Portal Team ID
        itc_team_id "987654321" # iTunes Connect Team ID
        app_identifier 'com.dummy.first' # Bundle identifier
  end

  for_lane :second do
  	team_id "123456789" # Developer Portal Team ID
        itc_team_id "123456789" # iTunes Connect Team ID
        app_identifier 'com.dummy.second' # Bundle identifier
  end

end
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

not relevant

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

not relevant

**Comment by KrauseFx** [comment]
Sorry, no, the Appfile doesn't support `|options|`, you'll have to pass the `app_identifier` and so on from your `Fastfile` where you have access. To get a list of available options for each action run `fastlane action [action_name]`
