### ISSUE TITLE
Can't find any applicable signing identities for items...

### ISSUE THREAD

**Issue by npomfret** [fastlane/fastlane#8872]
I've recently added a share extension to me app along with an app group.  I've regenerated my provisioning profiles, set everything to not be managed by Xcode.  And as far as I can see, Xcode is happier (no redness in the provisioning profiles for either my main app or the new extension).

I've changed by fast file to add something like:

```
  lane :certificates do
    match(app_identifier: ["com.my.myapp", "com.my.myapp.my-extension"])
  end
``` 

But when deploying to test flight, its failing.  There's so much [output](https://gist.github.com/npomfret/1cb1252d0b2ec57309f0eb6bdbc56484) its difficult to tell exactly what the problem is.  But I think this is the cause:

```
INFO [2017-04-12 17:39:43.81]: $ /usr/bin/xcrun /Users/npomfret/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/bq/v6cbzj2d0bs9kl5gqx4dj12r0000gn/T/gym_config20170412-17115-19jczl0.plist' -archivePath /Users/npomfret/Library/Developer/Xcode/Archives/2017-04-12/pomochat\ 2017-04-12\ 17.33.37.xcarchive -exportPath '/var/folders/bq/v6cbzj2d0bs9kl5gqx4dj12r0000gn/T/gym_output20170412-17115-1i32kvn' 
INFO [2017-04-12 17:39:44.01]: ▸ + xcodebuild -exportArchive -exportOptionsPlist /var/folders/bq/v6cbzj2d0bs9kl5gqx4dj12r0000gn/T/gym_config20170412-17115-19jczl0.plist -archivePath '/Users/npomfret/Library/Developer/Xcode/Archives/2017-04-12/pomochat 2017-04-12 17.33.37.xcarchive' -exportPath /var/folders/bq/v6cbzj2d0bs9kl5gqx4dj12r0000gn/T/gym_output20170412-17115-1i32kvn
INFO [2017-04-12 17:39:46.05]: ▸ 2017-04-12 17:39:46.055 xcodebuild[19818:424009] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/bq/v6cbzj2d0bs9kl5gqx4dj12r0000gn/T/pomochat_2017-04-12_17-39-46.053.xcdistributionlogs'.
INFO [2017-04-12 17:39:46.79]: ▸ 1.2.840.113635.100.1.61
INFO [2017-04-12 17:39:46.81]: ▸ 1.2.840.113635.100.1.61
INFO [2017-04-12 17:39:46.82]: ▸ 1.2.840.113635.100.1.61
INFO [2017-04-12 17:39:46.83]: ▸ 1.2.840.113635.100.1.61
INFO [2017-04-12 17:39:46.84]: ▸ 1.2.840.113635.100.1.61
INFO [2017-04-12 17:39:46.85]: ▸ 1.2.840.113635.100.1.61
INFO [2017-04-12 17:39:46.86]: ▸ 1.2.840.113635.100.1.61
INFO [2017-04-12 17:39:47.19]: ▸ 2017-04-12 17:39:47.197 xcodebuild[19818:424009] [MT] IDEDistribution: -[IDEDistributionProvisioning _itemToSigningInfoMap:]: Can't find any applicable signing identities for items: (
INFO [2017-04-12 17:39:47.19]: ▸ "<IDEDistributionItem: 0x7fcddd200bb0 'com.pomocorp.pomochat' '<DVTFilePath:0x7fcddcdcb2b0:'/Users/npomfret/Library/Developer/Xcode/Archives/2017-04-12/pomochat 2017-04-12 17.33.37.xcarchive/Products/Applications/pomochat.app'>'>",
INFO [2017-04-12 17:39:47.19]: ▸ "<IDEDistributionItem: 0x7fcddd0ec720 'com.adobe.cc.sdk.AdobeCreativeSDKCore' '<DVTFilePath:0x7fcddcfab2e0:'/Users/npomfret/Library/Developer/Xcode/Archives/2017-04-12/pomochat 2017-04-12 17.33.37.xcarchive/Products/Applications/pomochat.app/Frameworks/AdobeCreativeSDKCore.framework'>'>",
INFO [2017-04-12 17:39:47.19]: ▸ "<IDEDistributionItem: 0x7fcddd161cd0 'com.adobe.cc.sdk.AdobeCreativeSDKImage' '<DVTFilePath:0x7fcddce8fde0:'/Users/npomfret/Library/Developer/Xcode/Archives/2017-04-12/pomochat 2017-04-12 17.33.37.xcarchive/Products/Applications/pomochat.app/Frameworks/AdobeCreativeSDKImage.framework'>'>",
INFO [2017-04-12 17:39:47.19]: ▸ "<IDEDistributionItem: 0x7fcddd0ecbc0 'com.pomocorp.pomochat.pomochat-share' '<DVTFilePath:0x7fcddd105a30:'/Users/npomfret/Library/Developer/Xcode/Archives/2017-04-12/pomochat 2017-04-12 17.33.37.xcarchive/Products/Applications/pomochat.app/PlugIns/pomochat-share.appex'>'>"
INFO [2017-04-12 17:39:47.19]: ▸ )
INFO [2017-04-12 17:39:47.19]: ▸ Errors={
INFO [2017-04-12 17:39:47.19]: ▸ "<DVTSigningCertificate: 0x7fcddd129210; name='iPhone Distribution: Nick Pomfret (6FZN56WC8G)', hash='422AFD99EEF63A7CB8927CAEAFED6DF3B092BF78', serialNumber='44059B96E3A31EF9', certificateKind='1.2.840.113635.100.6.1.4, issueDate='2017-03-17 11:43:26 +0000''>" =     {
INFO [2017-04-12 17:39:47.20]: ▸ "<IDEDistributionItem: 0x7fcddd0ecbc0 'com.pomocorp.pomochat.pomochat-share' '<DVTFilePath:0x7fcddd105a30:'/Users/npomfret/Library/Developer/Xcode/Archives/2017-04-12/pomochat 2017-04-12 17.33.37.xcarchive/Products/Applications/pomochat.app/PlugIns/pomochat-share.appex'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=5 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=No provisioning profiles with a valid signing identity (i.e. certificate and private key pair) matching the bundle identifier \U201ccom.pomocorp.pomochat.pomochat-share\U201d were found., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7fcddd35aac0; portalTeamID='6FZN56WC8G', usingTeamBasedSigning='NO', bundleIdentifier='com.pomocorp.pomochat.pomochat-share', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"beta-reports-active\" = 1;\n    \"com.apple.security.application-groups\" =     (\n        \"group.com.pomocorp.pomochat\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
INFO [2017-04-12 17:39:47.20]: ▸ };
INFO [2017-04-12 17:39:47.20]: ▸ "<DVTSigningCertificate: 0x7fcddd120bd0; name='iPhone Distribution: Nick Pomfret (6FZN56WC8G)', hash='C5A0858CADD640010BE892DBC2473CCDD42AB899', serialNumber='3BBB13A072C3D0A2', certificateKind='1.2.840.113635.100.6.1.4, issueDate='2017-03-17 11:10:14 +0000''>" =     {
```

Any ideas?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.6.2                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :ios

require 'spaceship'

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :sync_certs do
    match(app_identifier: "com.pomocorp.pomochat", readonly: true, verbose: true)
  end

  lane :certificates do
    match(app_identifier: ["com.pomocorp.pomochat", "com.pomocorp.pomochat.pomochat-share"])
  end

  lane :voip_cert do
    app_identifier = "com.pomocorp.pomochat"
    apple_id = "nick-apple@snowmonkey.co.uk"
    output_path = "/Users/nickpomfret/Documents/github/pomochat-private/config"
    p12_password = "password"

    UI.important "Creating a new push certificate for app '#{app_identifier}'."

    Spaceship.login(apple_id)
    Spaceship.client.select_team
    csr, pkey = Spaceship::Certificate.create_certificate_signing_request
    cert = Spaceship::Certificate::VoipPush.create!(csr:csr,bundle_id:app_identifier)

    x509_certificate = cert.download
    certificate_type = "voippush"
    filename_base = "#{certificate_type}_#{app_identifier}"

    p12_cert_path = File.join(output_path, "#{filename_base}.p12")
    p12 = OpenSSL::PKCS12.create(p12_password, certificate_type, pkey, x509_certificate)
    File.write(p12_cert_path, p12.to_der)
    UI.message("p12 certificate: ".green + Pathname.new(p12_cert_path).realpath.to_s)

    x509_cert_path = File.join(output_path, "#{filename_base}.pem")
    File.write(x509_cert_path, x509_certificate.to_pem + pkey.to_pem)
    UI.message("PEM: ".green + Pathname.new(x509_cert_path).realpath.to_s)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean

    sh "../../bin/prepare-packager.sh"

    increment_build_number(
      xcodeproj: './pomochat.xcodeproj'
    )

    commit_version_bump(
      message: "Version bump",
      xcodeproj: "pomochat.xcodeproj"
    )

    push_to_git_remote
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "pomochat") # Build your app - more options available
    pilot(skip_waiting_for_build_processing: true)

    sh "../../bin/stop-packager.sh"
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.pomocorp.pomochat" # The bundle identifier of your app
apple_id "nick-apple@snowmonkey.co.uk" # Your Apple email address

team_id "6FZN56WC8G"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.2        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-04-12**
</details>

**Comment by ammichael** [comment]
@npomfret Hi there

Have you found a solution for your problem? I'm having the same issue.

**Comment by npomfret** [comment]
I did.  I needed to adjust my fast file certificate stuff as I was only including my main app and not my new share extension.  Something like:


```
  lane :certificates do
    match(type: "development", app_identifier: ["com.my_main_app", "com.my_main_app.my_share_ext"], force_for_new_devices: true)
    match(type: "appstore", app_identifier: ["com.my_main_app", "com.my_main_app.my_share_ext"], force_for_new_devices: true)
  end

```

**Comment by ammichael** [comment]
Didn't work for me :(

But thanks anyway! ✌️
