### ISSUE TITLE
Gym requires GUI "Allow Access" after matching

### ISSUE THREAD

**Issue by cd24** [fastlane/fastlane#8874]
### New Issue Checklist

- [ X ] Updated fastlane to the latest version
- [ X ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Building an iOS application

We are currently using fastlane to automate our builds using Jenkins. Our signing credentials are managed by Match, and work on development boxes. 

The general flow of the build is:
- Create a new keychain (unlock it)
- Install pods and unlock login keychain
- Match into the new keychain
- Build the app using Gym

Codesign should be able to access the private key without a dialog appearing since the -T codesign flag is added when match imports the profile [FastlaneCore::KeychainImporter line 8]. However, when codesign is called from the lane via SSH, the following error is thrown:
```
SecKey API returned: -25308
unknown error -1=ffffffffffffffff
```
We have been able to show that this error isn't thrown when run from the GUI. When fastlane is run from a logged in account, then a dialog is shown requesting the user "always allow", "deny", or "allow" codesign to access the private key in that keychain. 

It is my understanding that the -T flag when importing the private key should prevent this.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/gym/lib/gym/error_handler.rb:58:in `handle_build_error'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/gym/lib/gym/runner.rb:104:in `block in build_app'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/command_executor.rb:88:in `execute'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/gym/lib/gym/runner.rb:100:in `build_app'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/gym/lib/gym/runner.rb:12:in `run'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/gym/lib/gym/manager.rb:14:in `work'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/actions/gym.rb:21:in `run'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:73:in `block (2 levels) in parsing_binding'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/lane.rb:33:in `call'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.26.1/bin/fastlane:20:in `<top (required)>'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
/Users/jenkins_user_ssh/.rbenv/versions/2.3.1/bin/fastlane:23:in `<top (required)>'

### Environment

- Ruby Version: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
- Fastlane Version: 2.26.1
- XCode Version: 8.2
- OS X Sierra
- Uses RBEnv
- Uses Bundler

**Comment by coltrey** [comment]
output of fastlane env (excluding Fastfile/Appfile)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.3                                         |
| Ruby                        | 2.3.1                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.10.1 (Apple Git-78)               |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane            |
| Host                        | Mac OS X 10.12.3 (16D32)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                     |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-8.2.app/Contents/Developer/ |
| Xcode Version               | 8.2                                             |


### System Locale

| Variable | Value |   |
| -------- | ----- | - |
| LANG     | UTF-8 | ✅ |
| LC_ALL   |       |   |
| LANGUAGE |       |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.4       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.4        |
| io-console                | 0.4.5        |
| faraday                   | 0.12.0.1     |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.0        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
</details>


*generated on:* **2017-04-13**
</details>
