### ISSUE TITLE
Carthage Action: Missing dependency names for build

### ISSUE THREAD

**Issue by netbe** [fastlane/fastlane#8877]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The Carthage Action does not include the option to build a specific dependency.

```
› carthage help build                    
Build the project's dependencies
...
[[]]
	the dependency names to build
```
Also noticed that the checkout command is missing...any reason for that?

**Comment by KrauseFx** [comment]
To get a list of all available options use `fastlane action carthage` 👍
