### ISSUE TITLE
Getting last existing version from iTunes Connect

### ISSUE THREAD

**Issue by IhorHastov** [fastlane/fastlane#8878]
Hi everyone
How can i get last existing version, build of app? 

I can get version of build if i know app version. I need to get version of app to increment it and upload.

To get build version of app i use: 
`latest_testflight_build_number(version: "2")` -> returns build version of 2 version

But, i use Fastlane for multiply apps with different versions: app, build. And i cannot just get version from the project.

**Comment by IhorHastov** [comment]
I think, i know like do it. 

I just use one version of app for all apps and will only increment build version.

```
buildNumber = latest_testflight_build_number(version: "4") + 1
increment_build_number(
   build_number: buildNumber 
)
increment_version_number(
   version_number: "4.0.0" 
)
```

**Comment by erikvillegas** [comment]
I made this helper function to do just that:
```
  def highest_app_version_number(username, bundle_id)
    puts "fetching highest version on iTunes Connect..."

    Spaceship::Tunes.login(username)
    app = Spaceship::Tunes::Application.find(bundle_id)
    liveVersion = Versionomy.parse(app.live_version.version)
 
    if app.edit_version
	  editVersion = Versionomy.parse(app.edit_version.version)
      return editVersion.to_s
    else
      return liveVersion.to_s
    end
  end
```
If there is version on iTC pending submission/release, it'll return that version, otherwise it'll return the live version. It depends on [Versionomy for dealing with version numbers](https://github.com/dazuma/versionomy).

Also thanks, didn't know `latest_testflight_build_number` existed!

**Comment by IhorHastov** [comment]
@erikvillegas thank you for this way!
I've got the error `"undefined method `version' for nil:NilClass"`. Do you know resolving for this? 

Also, `latest_testflight_build_number` does not return correct build number for version.

I did version of app 4 and had uploaded. `latest_testflight_build_number` always return build number 0 for the version.

**Comment by KrauseFx** [comment]
@IhorHastov You'll have to share more information around the error message, in particular the line that caused the error

**Comment by IhorHastov** [comment]
@KrauseFx I found the decision which works good for me :)

To increment build version, even if it in processing:

```
increment_build_number({
    build_number: app_store_build_number(version: app_version,
    live: false,
    app_identifier: identifier) + 1
})
```

**Comment by IhorHastov** [comment]
@KrauseFx 
I have a next question. I work with two provision profile: enterprise and for App Store and need to change them in a build flow.

I do it manually, without Fastlane sign.

`update_project_provisioning` is not work good for me and i saw that you recommend use `ENV["PROFILE_UUID"] = ""`, but when i change it, it not change a provision profile in a project.

```
update_project_provisioning(
      xcodeproj: xcodeproj_path,
      profile: provision_path,
      target_filter: '.*',
      build_configuration: '.*'
)
```

Can you explain more detail me how i can use  ENV["PROFILE_UDID"]  way?

**Comment by IhorHastov** [comment]
Thanks all 👍  
You can close the issue.

I think, found what i need :) 

https://docs.fastlane.tools/codesigning/xcode-project/
