### ISSUE TITLE
junit report fastlane/report.xml not parsed correctly in jenkins

### ISSUE THREAD

**Issue by dariuszlesniak** [fastlane/fastlane#888]
Hi , i am having issue with jenkins report and would be grateful for help.
I have followed the guide on how to integrate with jenkins but my published report page has problems with displaying test names. Only root is displayed without individual test names. 

<img width="1110" alt="screen shot 2015-11-23 at 10 55 09" src="https://cloud.githubusercontent.com/assets/1489594/11333824/d5909c22-91d0-11e5-8fb8-e23b7cdb3070.png">

**Comment by regnerjr** [comment]
Not sure if this helps. To get this integrated with CircleCI, I needed to move the default `report.junit` to `.../junit/report.xml`. Sounds like you have probably gotten that far already though. Good luck.
