### ISSUE TITLE
Unable to use xcargs key in Snapfile. 

### ISSUE THREAD

**Issue by anshu10165** [fastlane/fastlane#8880]
I want to run an individual test under my testTarget scheme which has multiple UITests. Somewhere I found that  xcargs "-only-testing:TestBundleB/TestSuiteB" can be used in snapfile but not sure why it isn't working for me. I have fastlane version 2.1.3. Any help here would be much appreciated.

Thanks!

**Comment by anshu10165** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                 | Value                                       |
| ------------------- | ------------------------------------------- |
| OS                  | 10.11.6                                     |
| Ruby                | 2.1.1                                       |
| Bundler?            | true                                        |
| Git                 | git version 2.10.1 (Apple Git-78)           |
| Installation Source | ~/.rvm/rubies/ruby-2.1.1/bin/fastlane       |
| Host                | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir        | ~/.rvm/rubies/ruby-2.1.1/lib                |
| OpenSSL Version     | OpenSSL 1.0.2 22 Jan 2015                   |
| Is contained        | false                                       |
| Xcode Path          | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version       | 8.2.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status       |
| -------- | ------- | ------------------- |
| fastlane | 2.1.3   | 🚫 Update availaible |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| CFPropertyList            | 2.3.4        |
| i18n                      | 0.7.0        |
| json                      | 1.8.3        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| activesupport             | 4.2.6        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| aws-sigv4                 | 1.0.0        |
| jmespath                  | 1.3.1        |
| aws-sdk-core              | 2.6.40       |
| aws-sdk-resources         | 2.6.40       |
| aws-sdk                   | 2.6.40       |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.2        |
| carthage_cache            | 0.5.0        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| excon                     | 0.54.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.10.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
| safe_yaml                 | 1.0.4        |
| twine                     | 0.9.1        |
</details>


*generated on:* **2017-04-13**
</details>

**Comment by thebugcode** [comment]
Try running this command: `fastlane snapshot --xcargs "'-only-testing:TestFileName'"`
