### ISSUE TITLE
Pilot supporting remove from other roles

### ISSUE THREAD

**Issue by ahmedgharib** [fastlane/fastlane#8884]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have an app manager account and I am unable to remove test flight users from the app that I manage. 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

$  fastlane pilot remove _TestUserEmail_ -a _bundleID_ -u _myEmail_ --verbose
INFO [2017-04-13 12:37:21.36]: Login to iTunes Connect ( _myEmail_ )
Looking for iTunes Connect Team with ID _myTeam_
INFO [2017-04-13 12:37:33.35]: Login successful
ERROR [2017-04-13 12:37:33.92]: [ _TestUserEmail_ ]: User _myEmail_  (Team ID _myTeam_ ) doesn't have enough permission for the following action: parse_response
/Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Some operations failed: [ _TestUserEmail_]: User _myEmail_ (Team ID  _myTeam_ ) doesn't have enough permission for the following action: parse_response (FastlaneCore::Interface::FastlaneError)
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/pilot/lib/pilot/commands_generator.rb:37:in `handle_multiple'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/pilot/lib/pilot/commands_generator.rb:128:in `block (2 levels) in run'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/pilot/lib/pilot/commands_generator.rb:158:in `run'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/fastlane/lib/fastlane/cli_tools_distributor.rb:51:in `take_off'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.26.1/bin/fastlane:20:in `<top (required)>'
	from /Users/ahmed/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/ahmed/.fastlane/bin/bundle/bin/fastlane:22:in `<main>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.26.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| i18n                      | 0.7.0        |
| json                      | 1.8.1        |
| thread_safe               | 0.3.5        |
| tzinfo                    | 1.2.2        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.7.1      |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.2        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-04-13**
</details>

**Comment by mpirri** [comment]
We have recently rewritten `pilot` to be compatible with the new version of TestFlight that Apple rolled out about 2 weeks ago. I'm curious to know if you are still seeing these issues with the newest version of _fastlane_. Can you update and then try again?

Thanks so much!

**Comment by ahmedgharib** [comment]
Hey there! Thanks for getting back to me. I just tried it with 2.28.4 and it crashed:

$  fastlane pilot remove testerEmail-a myApp-u myemail --verbose
INFO [2017-04-25 17:25:40.68]: Login to iTunes Connect (myemail)
Looking for iTunes Connect Team with ID myTeamId
INFO [2017-04-25 17:25:43.79]: Login successful
ERROR [2017-04-25 17:25:44.67]: User myemail(Team ID myTeamId) doesn't have enough permission for the following action: parse_response
WARN [2017-04-25 17:25:44.67]: -------------
WARN [2017-04-25 17:25:44.67]: pilot crashed
WARN [2017-04-25 17:25:44.67]: -------------
ERROR [2017-04-25 17:25:44.67]: Unfortunately the TestFlight update from 11th April 2017 changed
ERROR [2017-04-25 17:25:44.67]: the way Testers, Groups, and Builds are managed on iTunesConnect.
ERROR [2017-04-25 17:25:44.67]: We have already fixed a number of features including submitting
ERROR [2017-04-25 17:25:44.67]: builds for testing, adding and removing testers from groups, and
ERROR [2017-04-25 17:25:44.67]: waiting for builds to process.
ERROR [2017-04-25 17:25:44.67]: 
ERROR [2017-04-25 17:25:44.67]: Please open an issue on https://github.com/fastlane/fastlane/issues
ERROR [2017-04-25 17:25:44.67]: if you believe this failure is the result of a bug in _pilot_ and we
ERROR [2017-04-25 17:25:44.67]: will be happy to look into this further.
ERROR [2017-04-25 17:25:44.67]: 
ERROR [2017-04-25 17:25:44.67]: Please stay tuned for more updates from _fastlane_ as we fix more issues!
ERROR [2017-04-25 17:25:44.67]: 
INFO [2017-04-25 17:25:44.67]: Sending Crash/Success information. More information on: https://github.com/fastlane/enhancer
INFO [2017-04-25 17:25:44.67]: No personal/sensitive data is sent. Only sharing the following:
INFO [2017-04-25 17:25:44.67]: {:pilot=>1}
INFO [2017-04-25 17:25:44.67]: pilot
INFO [2017-04-25 17:25:44.67]: This information is used to fix failing tools and improve those that are most often used.
INFO [2017-04-25 17:25:44.67]: You can disable this by setting the environment variable: FASTLANE_OPT_OUT_USAGE=1
/Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Some operations failed: User myEmail (Team ID myTeamId) doesn't have enough permission for the following action: parse_response (FastlaneCore::Interface::FastlaneError)
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:129:in `block (2 levels) in run'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/ahmed/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.4/bin/fastlane:20:in `<top (required)>'
	from /Users/ahmed/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/ahmed/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by mpirri** [comment]
We are currently working on supporting this functionality - you can follow this PR to see the progress of our work:
https://github.com/fastlane/fastlane/pull/9046

Thanks so much for your patience with this!

**Comment by ahmedgharib** [comment]
Thanks Mark.


-Ahmed


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
