### ISSUE TITLE
I am using fastlane in android How to upload screenshot without uploading apk. Please help me about the code and where to put it?

### ISSUE THREAD

**Issue by kelvincooll** [fastlane/fastlane#8899]
@fastlane-bot @andrew , Can any one help me to upload the screen shot images in playstore with out uploading apk. Please help me about the code and where to put it?

### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by kelvincooll** [comment]
platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer

# lane :screenshots do
# screengrab
# supply
# end


# gradle(task: 'assembleMyAppAlpha')
# supply(skip_upload_screenshots:false, skip_upload_apk:true,track:'production')

lane :example do
  say "It works"
end```

**Comment by kelvincooll** [comment]
Hi,
 By adding the following code in Fastfile solved my issue. It may help some one.

 screengrab(
   locales: ["en-US"],
  clear_previous_screenshots: true

  )
   end


 lane :playstore do
   gradle(
     task: 'assemble',
     build_type: 'Release'
   )
     supply(
           skip_upload_apk: 'true'
           )
    end

**Comment by mfurtak** [comment]
@kelvincooll Glad you're up and running! 🚀
