### ISSUE TITLE
can you call fastlane from fastlane?

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#890]
I'd like to have a lane which did

      lane :submit_all do
        fastlane (lane: "deliver",env: "paid")
        fastlane (lane: "deliver",env: "free")
        fastlane (lane: "deliver",env: "legacy")
     end

I know I can write a shell script to do this - but somehow that seems like cheating!

**Comment by KrauseFx** [comment]
Interesting question. You can always call lanes with parameters from within your lane: https://github.com/fastlane/fastlane/blob/master/docs/Advanced.md#switching-lanes
Does that help?

**Comment by ConfusedVorlon** [comment]
I don't think that covers it - though I may be missing something.
Can you specify the .env files to use as an option within a lane?

my shell script is

     fastlane submit --env legacy;
     fastlane submit --env paid;
     fastlane submit --env free;

so it would need a way to specify the global .env file which is then used in the deliverfile, etc...
Is there a way to do that?

**Comment by ConfusedVorlon** [comment]
I tried a lane with

     deliver( env: options[:variant],...

but I get 

     could not find option 'env'

**Comment by KrauseFx** [comment]
You could add this to your `Fastfile`

```ruby
lane :beta do
  sh "fastlane other_lane"
end
```

**Comment by ConfusedVorlon** [comment]
I guess that would do it - thanks.
