### ISSUE TITLE
Does "match" support Enterprise Profiles?

### ISSUE THREAD

**Issue by Aw79** [fastlane/fastlane#8907]
https://codesigning.guide/ states that ...

> Because of the potentially dangerous nature of In-House profiles **we decided to not allow the use of match with enterprise accounts**.

... while in https://github.com/fastlane/fastlane/tree/master/match#readme one reads ...

> Because of the potentially dangerous nature of In-House profiles please **use match with enterprise profiles with caution**, ensure your git repository is private and use a secure password.

Which of the information is correct or maybe out-dated?
Does "match" support Enterprise Profiles?

**Comment by hjanuschka** [comment]
the second one is right see this pr: https://github.com/fastlane/fastlane/pull/8000

looks like codesigning.guide is outdated 🤔

**Comment by Aw79** [comment]
Thanks for clearing up - good to hear Enterprise Profiles are now supported! ;-)
