### ISSUE TITLE
`Exit Status: 74` when collecting logs on CircleCi, Xcode 8.3, on Fastlane 2.27.0

### ISSUE THREAD

**Issue by lalunamel** [fastlane/fastlane#8909]
### Issue Description
Since upgrading to [Fastlane 2.27.0](https://github.com/fastlane/fastlane/releases/tag/2.27.0) we have seen failures in our CircleCi runs.

Using Fastlane 2.26.1 does not produce this issue.
Looking at the commits between the two, [this one](https://github.com/fastlane/fastlane/commit/61e55229a9684a9c971d752105e67904be08af19) seems the likely culprit.

This issue also seems related to the discussion in https://github.com/fastlane/fastlane/pull/8829, specifically the comment made by `mccarron`.

```
+--------------------+------+
|       Test Results        |
+--------------------+------+
| Number of tests    | 5421 |
| Number of failures | 0    |
+--------------------+------+

[14:58:42]: ------------------------------
[14:58:42]: --- Collecting system logs ---
[14:58:42]: ------------------------------
[14:58:42]: $ xcrun simctl spawn ID_NUMBER log collect --output /Users/distiller/tracker-ios/fastlane/test_output/system_logs-iPhone\ 7_iOS_10.1.logarchive 2>/dev/null

[14:58:42]: Exit status: 74
```

**Comment by KrauseFx** [comment]
Did you maybe upgrade to Xcode 8.3 and that caused the error?

**Comment by lalunamel** [comment]
Locally, where log collection works we are running XCode 8.3 (is 8.3 unsupported at this time?)

On CircleCI, where the build is failing, we are using `Xcode 8.2.1 (build 8C1002)`, per their [documentation](https://circleci.github.io/macos-image-tests/).

**Comment by ZevEisenberg** [comment]
I'm seeing this same failure. Failing on Circle, not on local builds. Upgraded both Xcode and Fastlane, but I can try to isolate one or the other if you think it will help.

**Comment by ZevEisenberg** [comment]
Our failure output is very slightly different:

```
+--------------------+----+
|      Test Results       |
+--------------------+----+
| Number of tests    | 49 |
| Number of failures | 0  |
+--------------------+----+

[10:24:30]: ------------------------------
[10:24:30]: --- Collecting system logs ---
[10:24:30]: ------------------------------
[10:24:30]: $ xcrun simctl spawn 770CF0F5-5F6B-4E05-8CF0-E5A2BEFF0702 log collect --output /tmp/circle-junit.glEjmqS/junit/system_logs-iPhone\ 6s_iOS_10.0.logarchive 2>/dev/null

[10:24:30]: Exit status: 74
```

**Comment by DanToml** [comment]
@lalunamel That code path should never actually be reached on 8.2.x, but CircleCI does support 8.3, the 8.3 image details can be found here https://180-74671181-gh.circle-artifacts.com/0/Users/distiller/macos-image-tests/pages/_site/index.html (sorry for the bad URI, since we moved to single-xcode-per-image, we didn't update the deployment of image docs yet)

**Comment by seanooi** [comment]
We've been seeing that issue as well and temporarily disabling simulator logs solved the issue for us.
If you're ok with not having simulator logs for awhile, try adding the `include_simulator_logs: false` param in your `scan()` method.

**Comment by ZevEisenberg** [comment]
@seanooi nice workaround! I looked at this a bit with @DanToml via ssh on a build, and it looks like the `xcrun simctl spawn` command is failing silently (due to the `2>/dev/null`) if the path given to it doesn't exist. I'm not sure if this is a Circle or a Fastlane issue, but either way, now the right person knows about it 😀.

**Comment by jjacquet** [comment]
Setting 
> include_simulator_logs: false
worked for us too, but it would be nice to get that back when looking for back traces upon a crash to determine code or simulator.

**Comment by ZevEisenberg** [comment]
Weirdly, removing `include_simulator_logs` from our Fastfile did _not_ fix it for us.

**Comment by hammertoe** [comment]
This still seems to be an issue (Fastlane 2.33.0) and as a workaround I've had to ensure I create the log directory first before it is used. E.g. in my Jenkinsfile I have:

`sh "mkdir -p ${env.WORKSPACE}/build/reports"
`

before attempting to run the tests.

**Comment by ZevEisenberg** [comment]
Oops, I meant to follow up on this. The default value of `include_simulator_logs` changed to `true` some time after Circle 2.0 launched. You need to explicitly pass `false` in your Fastfile.

**Comment by nafu** [comment]
@lalunamel @ZevEisenberg @seanooi @jjacquet @hammertoe @DanToml @KrauseFx 

Thank you for reporting and supporting. 👍 

@lyndsey-ferguson 

Thanks for the fix. I've also confirmed this is fixed in my project 🚀

**Comment by lyndsey-ferguson** [comment]
👏 Glad to help!
