### ISSUE TITLE
Error when using fastlane

### ISSUE THREAD

**Issue by talkaboutdesign** [fastlane/fastlane#891]
Error shows up after submitting meta data and uploading all the screenshots is successful. 

Unauthorized access

Reference for you:
20026e3c174db824b2a792b1c0a66f33

**Comment by KrauseFx** [comment]
I'm looking into it, thanks for the report :

**Comment by ohwutup** [comment]
Going to close this issue for inactivity. Please let us know if this is still something going wrong with your flow! Thank you!! :+1: :100:
