### ISSUE TITLE
Android: "app" should not be hard-coded in gradle.rb

### ISSUE THREAD

**Issue by superarts** [fastlane/fastlane#892]
In fastlane/lib/fastlane/actions/gradle.rb line 22,
```
          apk_path = Dir[File.join("app", "build", "outputs", "apk", "*-#{flavor}.apk")].last
```
In some projects `app` may be something else. There are several ways to deal with this, so please come up with something brilliant :)

**Comment by rompic** [comment]
also see the discussion in #750

**Comment by asfalcone** [comment]
@superarts @rompic this has been addressed! please update to the latest version of fastlane and give it a try! :+1:

**Comment by superarts** [comment]
Thanks!


On Saturday, March 5, 2016, Andrea Falcone <notifications@github.com> wrote:

> @superarts <https://github.com/superarts> @rompic
> <https://github.com/rompic> this has been addressed! please update to the
> latest version of fastlane and give it a try! [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fastlane/fastlane/issues/892#issuecomment-192351521>.
>


-- 
Regards,

Leo
