### ISSUE TITLE
Deliver failing since today (update to XCode 8.2.3 or iTunesConnect API updated?)

### ISSUE THREAD

**Issue by frederic-adda** [fastlane/fastlane#8932]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Deliver failing since today (update to XCode 8.2.3 or iTunesConnect API updated?)
It is stuck with line marked: 
```[18:03:34]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `edit_version' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/8660 [open] 6 💬
   3 weeks ago

➡️  Deliver Error: undefined method `[]=' for nil:NilClass in spaceship/tunes/language_item.rb
   https://github.com/fastlane/fastlane/issues/8922 [open] 18 💬
   2 hours ago

➡️  undefined method `id' for nil:NilClass while fastlane sigh repair
   https://github.com/fastlane/fastlane/issues/8184 [open] 3 💬
   01 Mar 2017 
``` 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[18:03:16]: ---------------------
[18:03:16]: --- Step: deliver ---
[18:03:16]: ---------------------
[18:03:16]: Your Deliverfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[18:03:16]: Successfully loaded '/Users/Fred/Developer/My Customer Apps/C02 Le livre scolaire/lls-tablet-ios/fastlane/Deliverfile' 📄

+------------------------+--------------------------------------+
|         Detected Values from './fastlane/Deliverfile'         |
+------------------------+--------------------------------------+
| force                  | true                                 |
| price_tier             | 0                                    |
| app_rating_config_path | fastlane/ratingConfig.json           |
| app_review_information | {:first_name=>"Cédric",              |
|                        | :last_name=>"Soubrié",               |
|                        | :phone_number=>"+33 6 99 61 29 58",  |
|                        | :email_address=>"cedric.soubrie@gma  |
|                        | il.com", :notes=>"Hi,\nTo review     |
|                        | this app :\n- click on \"J'ai déjà   |
|                        | un code licence\"\n- use APPLE\nand  |
|                        | then it's ok !\n\nIf you have any    |
|                        | question about the use of a code     |
|                        | licence, you can refer to the        |
|                        | initial validation where we had an   |
|                        | exchange with Apple Review about it  |
|                        | and our business model"}             |
+------------------------+--------------------------------------+

[18:03:16]: Login to iTunes Connect (lelivrescolaire@icloud.com)
[18:03:22]: Login successful

+--------------------------------------+--------------------------------------+
|                           deliver 2.27.0 Summary                            |
+--------------------------------------+--------------------------------------+
| app_identifier                       | fr.lelivrescolaire.HG6               |
| metadata_path                        | fastlane/metadata-HG6                |
| screenshots_path                     | fastlane/screenshots-HG6             |
| app_icon                             | fastlane/appicon/HG6.png             |
| ipa                                  | /Users/Fred/Developer/My Customer    |
|                                      | Apps/C02 Le livre                    |
|                                      | scolaire/lls-tablet-ios/HG6.ipa      |
| submit_for_review                    | false                                |
| force                                | true                                 |
| price_tier                           | 0                                    |
| app_rating_config_path               | fastlane/ratingConfig.json           |
| app_review_information.first_name    | Cédric                               |
| app_review_information.last_name     | Soubrié                              |
| app_review_information.phone_number  | +33 6 99 61 29 58                    |
| app_review_information.email_addres  | cedric.soubrie@gmail.com             |
| s                                    |                                      |
| app_review_information.notes         | Hi, To review this app : - click on  |
|                                      | "J'ai déjà un code licence" - use    |
|                                      | APPLE and then it's ok !  If you     |
|                                      | have any question about the use of   |
|                                      | a code licence, you can refer to     |
|                                      | the initial validation where we had  |
|                                      | an exchange with Apple Review about  |
|                                      | it and our business model            |
| app_version                          | 1.5.2                                |
| username                             | lelivrescolaire@icloud.com           |
| edit_live                            | false                                |
| platform                             | ios                                  |
| skip_binary_upload                   | false                                |
| skip_screenshots                     | false                                |
| skip_metadata                        | false                                |
| automatic_release                    | false                                |
| dev_portal_team_id                   | 7E9D5V75U7                           |
| overwrite_screenshots                | false                                |
+--------------------------------------+--------------------------------------+

[18:03:24]: Making sure the latest version on iTunes Connect matches '1.5.2' from the ipa file...
[18:03:26]: '1.5.2' is the latest version on iTunes Connect
[18:03:26]: Loading 'fastlane/metadata-HG6/fr-FR/description.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/fr-FR/keywords.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/fr-FR/release_notes.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/fr-FR/support_url.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/fr-FR/marketing_url.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/fr-FR/name.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/fr-FR/privacy_url.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/copyright.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/primary_category.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/secondary_category.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/primary_first_sub_category.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/primary_second_sub_category.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/secondary_first_sub_category.txt'...
[18:03:26]: Loading 'fastlane/metadata-HG6/secondary_second_sub_category.txt'...
[18:03:28]: Activating language fr-FR...
+--------------------+--------------------------------------+
|                       Lane Context                        |
+--------------------+--------------------------------------+
| DEFAULT_PLATFORM   | ios                                  |
| PLATFORM_NAME      | ios                                  |
| LANE_NAME          | ios deliverBook                      |
| PRODUCE_APPLE_ID   | 1207311181                           |
| SIGH_PROFILE_TYPE  | app-store                            |
| IPA_OUTPUT_PATH    | /Users/Fred/Developer/My Customer    |
|                    | Apps/C02 Le livre                    |
|                    | scolaire/lls-tablet-ios/HG6.ipa      |
| DSYM_OUTPUT_PATH   | /Users/Fred/Developer/My Customer    |
|                    | Apps/C02 Le livre                    |
|                    | scolaire/lls-tablet-ios/HG6.app.dSY  |
|                    | M.zip                                |
| XCODEBUILD_ARCHIVE | /Users/Fred/Library/Developer/Xcode  |
|                    | /Archives/2017-04-20/HG6 2017-04-20  |
|                    | 17.57.40.xcarchive                   |
+--------------------+--------------------------------------+
[18:03:34]: undefined method `[]=' for nil:NilClass

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | produce             | 13          |
| 4    | Switch to ios       | 0           |
|      | buildBook lane      |             |
| 5    | match               | 18          |
| 6    | gym                 | 342         |
| 💥   | deliver             | 18          |
+------+---------------------+-------------+

[18:03:34]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `edit_version' for nil:NilClass
   https://github.com/fastlane/fastlane/issues/8660 [open] 6 💬
   3 weeks ago

➡️  Deliver Error: undefined method `[]=' for nil:NilClass in spaceship/tunes/language_item.rb
   https://github.com/fastlane/fastlane/issues/8922 [open] 18 💬
   2 hours ago

➡️  undefined method `id' for nil:NilClass while fastlane sigh repair
   https://github.com/fastlane/fastlane/issues/8184 [open] 3 💬
   01 Mar 2017

and 238 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]='%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/spaceship/lib/spaceship/tunes/language_item.rb:20:in `[]=': [!] undefined method `[]=' for nil:NilClass (NoMethodError)
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/deliver/lib/deliver/upload_metadata.rb:81:in `block (2 levels) in upload'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/deliver/lib/deliver/upload_metadata.rb:78:in `each'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/deliver/lib/deliver/upload_metadata.rb:78:in `block in upload'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/deliver/lib/deliver/upload_metadata.rb:69:in `each'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/deliver/lib/deliver/upload_metadata.rb:69:in `upload'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/deliver/lib/deliver/runner.rb:62:in `upload_metadata'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/deliver/lib/deliver/runner.rb:21:in `run'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/actions/deliver.rb:16:in `run'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:124:in `block (2 levels) in parsing_binding'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/Fred/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.27.0/bin/fastlane:20:in `<top (required)>'
	from /Users/Fred/.rbenv/versions/2.3.1/bin/fastlane:23:in `load'
	from /Users/Fred/.rbenv/versions/2.3.1/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | fr_FR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
   # cocoapods

  end

# Install all needed profiles/certificates for all targets
#usage : launch in terminal with 'fastlane installCertificates'
  lane :installCertificates do
   app_identifiers = [
    "fr.lelivrescolaire.HG6",
    "fr.lelivrescolaire.HG4",
    "fr.lelivrescolaire.HG5",
    "fr.lelivrescolaire.HG3",
    "fr.lelivrescolaire.FR6",
    "fr.lelivrescolaire.FR5",
    "fr.lelivrescolaire.FR4",
    "fr.lelivrescolaire.FR3",
     "fr.lelivrescolaire.MAT6",
     "fr.lelivrescolaire.MAT4",
     "fr.lelivrescolaire.MAT-C4",
     "fr.lelivrescolaire.EN3",
     "fr.lelivrescolaire.EN4",
     "fr.lelivrescolaire.EN5",
     "fr.lelivrescolaire.EN6",
     "fr.lelivrescolaire.PC5",
     "fr.lelivrescolaire.PC4",
     "fr.lelivrescolaire.PC3",
     "fr.lelivrescolaire.SVT4",
     "fr.lelivrescolaire.SVT-C4",
     "fr.lelivrescolaire.ES5",
     "fr.lelivrescolaire.ES4",
     "fr.lelivrescolaire.ES3"
   ]
   match(type: "appstore", app_identifier: app_identifiers, readonly:true)
   match(type: "adhoc", app_identifier: app_identifiers, readonly:true)
   match(type: "development", app_identifier: app_identifiers, readonly:true)
   #match(type: "appstore", app_identifier: app_identifiers, readonly:false, force:true)
   #match(type: "adhoc", app_identifier: app_identifiers, readonly:false, force:true)
   #match(type: "development", app_identifier: app_identifiers, readonly:false, force:true)
  end

# Create and init provisioning profiles for a specific book
# WARNING : After that, remember to select the provisioning profile in XCode target
# usage : launch in terminal with 'fastlane initBook targetId:HG6"'
lane :initBook do |options|
 SINGLEBOOK = options[:targetId]  ## <-- set here the book reference
 VERSION = "0.5"     ## <-- set here the new version

 app_identifier = "fr.lelivrescolaire.#{SINGLEBOOK}"

 # Create new app/provisioning profiles in iTunes Connect
 produce(username: "lelivrescolaire@icloud.com", app_identifier: app_identifier,
 app_name: app_identifier, language: "French", app_version: VERSION, sku: SINGLEBOOK)
 #, enabled_features:{:associated_domains=>true}
 # produce seem to have a bug with enabling features so I use the command line which is working correctly
 sh "fastlane produce enable_services --associated-domains --app_identifier #{app_identifier}"
 match(type: "appstore", app_identifier: app_identifier, readonly:false)
 match(type: "adhoc", app_identifier: app_identifier, readonly:false)
 match(type: "development", app_identifier: app_identifier, readonly:false)
end

  # Compile a book
  # Before you must launch initSingleBook once and select generated provisioning in Xcode target
  # usage : launch in terminal with 'fastlane buildBook targetId:HG6 buildType:appstore/adhoc or development'
  lane :buildBook do |options|
    SINGLEBOOK = options[:targetId]
    BUILDTYPE = options[:buildType]
    app_identifier = "fr.lelivrescolaire.#{SINGLEBOOK}"

    # Create new provisioning profile
    match(type: BUILDTYPE, app_identifier: app_identifier, readonly:true)

    # Build app and generate .ipa file
    if BUILDTYPE == "adhoc"
     gym(scheme: SINGLEBOOK, configuration:"Adhoc", include_symbols: false)
   else
    gym(scheme: SINGLEBOOK, include_symbols: false)
   end

  end

  # Compile a book and upload it to the AppStore
  # You must launch initSingleBook at least once to create the app environement in iTunes
  # usage : launch in terminal with 'fastlane deliverBook targetId:HG6'
  lane :deliverBook do |options|
   SINGLEBOOK = options[:targetId]  ## <-- set here the book reference
   app_identifier = "fr.lelivrescolaire.#{SINGLEBOOK}"

   puts("\n\n\e[34mWARNING : did you remember to increase build number ? If not run 'fastlane incrementBuildNumber'\e[0m\n\n")

   # Create new app/version in iTunes Connect
   produce(
   username: "lelivrescolaire@icloud.com",
   app_identifier: app_identifier,
   language: "French",
   sku: SINGLEBOOK)

   puts("\n\n\e[34mWARNING : did you remember to increase build number ? If not run 'fastlane incrementBuildNumber'\e[0m\n\n")

   buildBook(targetId:SINGLEBOOK, buildType:"appstore")

   puts("\n\n\e[34mWARNING : did you remember to increase build number ? If not run 'fastlane incrementBuildNumber'\e[0m\n\n")

   # Upload to iTunes Connect
   deliver(app_identifier: app_identifier,
   metadata_path: "fastlane/metadata-#{SINGLEBOOK}",
   screenshots_path: "fastlane/screenshots-#{SINGLEBOOK}",
   app_icon: "fastlane/appicon/#{SINGLEBOOK}.png",
   ipa: "#{SINGLEBOOK}.ipa",
   submit_for_review: false)
  end

  # Increment build number for all targets of the project
  # usage : launch in terminal with 'fastlane incrementBuildNumber'
  lane :incrementBuildNumber do
   increment_build_number
  end

  # METADATA / LIVRES INDIVIDUELS: launch in terminal with 'fastlane updateMetaData targetId:HG6'
  # This lane only updates metadata
  lane :updateMetaData do |options|

    SINGLEBOOK = options[:targetId]  ## <-- set here the book reference

    # Upload to iTunes Connect
    deliver(app_identifier: "fr.lelivrescolaire.#{SINGLEBOOK}",
    metadata_path: "fastlane/metadata-#{SINGLEBOOK}",
    screenshots_path: "fastlane/screenshots-#{SINGLEBOOK}",
    app_icon: "fastlane/appicon/#{SINGLEBOOK}.png",
    skip_binary_upload: true,
    submit_for_review:false)

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "fr.lelivrescolaire.specimen" # The bundle identifier of your app
apple_id "lelivrescolaire@icloud.com" # Your Apple email address

team_id "7E9D5V75U7"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.27.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.20       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.7       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-04-20**
</details>

**Comment by rickyying** [comment]
I have the same problem just starting this morning. Nothing changed in my environment.
Try update to the latest version did not help.

**Comment by evilDave** [comment]
See #8922 supposed to be fixed, I'm trying it now.

**Comment by evilDave** [comment]
Yep, fixed in latest release of fastlane.

**Comment by evilDave** [comment]
@rickyying you must have missed the 2.28.1 release by minutes!

**Comment by frederic-adda** [comment]
Yep, working for me! Thanks!

**Comment by rickyying** [comment]
@evilDave  Thanks. Working for me now.
