### ISSUE TITLE
[!] undefined method `native_targets' for #<Xcodeproj::Project:[MEMORY_INSTANCE]>

### ISSUE THREAD

**Issue by d4r1091** [fastlane/fastlane#8935]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Today, I don't know why to be fair, [this plugin](http://www.rubydoc.info/gems/fastlane-plugin-get_product_bundle_id/0.1.0) started to give me this horrible error.

I use to run all the stuff into a home-brewed Jenkins instance

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

bundle exec fastlane crashlyticsBeta --capture_output
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
Successfully loaded Appfile at path '/Users/testuser/workspace/App/fastlane/Appfile'
- apple_id: '***********'
- team_id: '***********'
-------
### Captured Output

Command Used: `crashlyticsBeta`
<details><summary>Output/Log</summary>

```

INFO [2017-04-20 17:38:18.95]: Successfully loaded custom action '/Users/testuser/workspace/App/fastlane/actions/git_checkout.rb'.
DEBUG [2017-04-20 17:38:18.95]: Checking if there are any plugins that should be loaded...
DEBUG [2017-04-20 17:38:18.95]: Loading 'fastlane-plugin-update_project_codesigning' plugin
INFO [2017-04-20 17:38:19.02]: gem 'fastlane-plugin-update_project_codesigning' is already installed
DEBUG [2017-04-20 17:38:19.02]: Loading 'fastlane-plugin-versioning' plugin
INFO [2017-04-20 17:38:19.08]: gem 'fastlane-plugin-versioning' is already installed
DEBUG [2017-04-20 17:38:19.09]: Loading 'fastlane-plugin-get_product_bundle_id' plugin
INFO [2017-04-20 17:38:19.15]: gem 'fastlane-plugin-get_product_bundle_id' is already installed
+--------------------------------------------+---------+------------------------------------+
|                                       Used plugins                                        |
+--------------------------------------------+---------+------------------------------------+
| Plugin                                     | Version | Action                             |
+--------------------------------------------+---------+------------------------------------+
| fastlane-plugin-update_project_codesigning | 0.2.0   | update_project_codesigning         |
| fastlane-plugin-versioning                 | 0.2.6   | get_app_store_version_number       |
|                                            |         | get_build_number_from_plist        |
|                                            |         | get_info_plist_path                |
|                                            |         | get_version_number_from_git_branch |
|                                            |         | get_version_number_from_plist      |
|                                            |         | increment_build_number_in_plist    |
|                                            |         | increment_version_number_in_plist  |
| fastlane-plugin-get_product_bundle_id      | 0.1.0   | get_product_bundle_id              |
+--------------------------------------------+---------+------------------------------------+

ERROR [2017-04-20 17:38:19.16]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
INFO [2017-04-20 17:38:19.17]: -------------------------------------------------
INFO [2017-04-20 17:38:19.17]: --- Step: Verifying required fastlane version ---
INFO [2017-04-20 17:38:19.17]: -------------------------------------------------
INFO [2017-04-20 17:38:19.17]: Your fastlane version 2.25.0 matches the minimum requirement of 2.1.2  ✅
INFO [2017-04-20 17:38:19.17]: ------------------------------
INFO [2017-04-20 17:38:19.17]: --- Step: default_platform ---
INFO [2017-04-20 17:38:19.17]: ------------------------------
INFO [2017-04-20 17:38:19.17]: -------------------------------------------
INFO [2017-04-20 17:38:19.17]: --- Step: get_version_number_from_plist ---
INFO [2017-04-20 17:38:19.17]: -------------------------------------------
INFO [2017-04-20 17:38:19.17]: $ xcodebuild -list -project App/App.xcodeproj
INFO [2017-04-20 17:38:20.11]: $ xcodebuild clean -showBuildSettings -scheme Scheme\ Test -project App/App.xcodeproj
INFO [2017-04-20 17:38:21.22]: -----------------------------------------
INFO [2017-04-20 17:38:21.22]: --- Step: get_build_number_from_plist ---
INFO [2017-04-20 17:38:21.22]: -----------------------------------------
INFO [2017-04-20 17:38:21.22]: $ xcodebuild -list -project App/App.xcodeproj
INFO [2017-04-20 17:38:22.14]: $ xcodebuild clean -showBuildSettings -scheme Scheme\ Test -project App/App.xcodeproj
INFO [2017-04-20 17:38:23.25]: Driving the lane 'ios crashlyticsBeta' 🚀
INFO [2017-04-20 17:38:23.25]: Those are our vars: ISSUE TYPE: , ISSUE KEY: IOS-100, CLIENT NAME: Scheme Test, SCHEME NAME: Scheme Test
INFO [2017-04-20 17:38:23.25]: -----------------------------------
INFO [2017-04-20 17:38:23.25]: --- Step: get_product_bundle_id ---
INFO [2017-04-20 17:38:23.25]: -----------------------------------
INFO [2017-04-20 17:38:24.89]: -------------------
INFO [2017-04-20 17:38:24.89]: --- Step: slack ---
INFO [2017-04-20 17:38:24.89]: -------------------
ERROR [2017-04-20 17:38:24.90]: Error setting value '' for option 'slack_url'
ERROR [2017-04-20 17:38:24.90]: An error occured while executing the `error` block:
ERROR [2017-04-20 17:38:24.90]: Invalid URL, must start with https://
WARN [2017-04-20 17:38:24.90]: Lane Context:
INFO [2017-04-20 17:38:24.90]: {:DEFAULT_PLATFORM=>:ios, :GET_INFO_PLIST_VALUE_CUSTOM_VALUE=>"2.0.39", :VERSION_NUMBER=>"2.0.9", :BUILD_NUMBER=>"2.0.39", :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios crashlyticsBeta"}
ERROR [2017-04-20 17:38:24.90]: undefined method `native_targets' for #<Xcodeproj::Project:0x007f8971227278>
INFO [2017-04-20 17:38:24.90]: Successfully generated documentation at path '/Users/testuser/workspace/App/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | get_version_number_from_plist       | 2           |
| 4    | get_build_number_from_plist         | 2           |
| 💥   | get_product_bundle_id               | 1           |
| 💥   | slack                               | 0           |
+------+-------------------------------------+-------------+

DEBUG [2017-04-20 17:38:24.91]: All plugins are up to date
ERROR [2017-04-20 17:38:24.91]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `native_targets' for Xcodeproj::Project

URL: https://api.github.com/search/issues?q=undefined%20method%20%60native_targets'%20for%20Xcodeproj::Project+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
DEBUG [2017-04-20 17:38:25.51]: All plugins are up to date


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.2                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.10.1 (Apple Git-78)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.2 (16C68)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

# Test ltd
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

######################### CONSTANTS #########################
#------------------------ fastlane -------------------------#

fastlane_version "2.1.2"

default_platform :ios

#------------------------- XCode ---------------------------#

xcodeproj_path = 'App/App.xcodeproj'

current_app_identifier = "NO_BUNDLE"

client_name = ENV["JIRA_CLIENT_NAME"]

scheme_name = client_name.nil? || client_name.empty? || client_name == 'null' ? "Scheme Test" : client_name

version = get_version_number_from_plist(
    xcodeproj: xcodeproj_path,
    target: scheme_name
  )

plain_version = version.delete("^0-9") #=> should return version without dots

build = get_build_number_from_plist(
    xcodeproj: xcodeproj_path,
    target: scheme_name
  )

#------------------------- jira ---------------------------#

jira_issue_key = ENV["JIRA_ISSUE_KEY"]

jira_task_number = jira_issue_key.partition('-').last

# switch across type and create a branch name to checkuot mixing with jira_task_number
jira_issue_type = ENV["JIRA_ISSUE_TYPE"]

features_array = ["New Feature", "Improvements"]

fixes_array = ["Technical Debt", "Ux Debt", "Bug"] 

#----------------------- FASTLANE -------------------------#

platform :ios do
  before_all do

    puts("Those are our vars: ISSUE TYPE: #{jira_issue_type}, ISSUE KEY: #{jira_issue_key}, CLIENT NAME: #{client_name}, SCHEME NAME: #{scheme_name}")

    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/***********/***********"
    
    # If the GIT status is not clean, abort. We won't want to include junk in the build
    # ensure_git_status_clean

    current_app_identifier = get_product_bundle_id(project_filepath: xcodeproj_path, scheme: scheme_name)
    puts "Bundle ID #{current_app_identifier} fetched correctly 💙"

  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
  end

  error do |lane, exception|
      slack(
        message: exception.message,
        success: false
      )
  end

  ######################### PRIVATE LANES #########################
  #--------------------------- GitHub ----------------------------#

  desc "Tag beta version on GitHub"
  private_lane :gitTag do

    commit_version_bump ({message: "Deployed build #{plain_version}(#{build})."})
    ensure_git_status_clean
    add_git_tag(tag: "#{plain_version}(#{build})")
    push_to_git_remote

  end

  private_lane :checkCorrectBranch do

    ensure_git_status_clean

    current_branch = git_branch

    prefix_branch_name = "features"

    if fixes_array.include? jira_issue_type
      prefix_branch_name = "fixes"
      puts "Cool Team, your're running a fix branch 😎"
    end

    branch_name = "#{prefix_branch_name}/#{jira_issue_key}/main"

    # # Checkout remote branch if needed
    if !branch_name.nil? && branch_name != current_branch
      puts "Checkout new branch #{branch_name}"
      git_checkout(remote_branch: branch_name)  
    elsif
      branch_name == current_branch 
      puts "We already are in #{branch_name}, pulling 💪"
      git_pull
    else
      puts "#{branch_name} is not a Valid Branch 💀"
    end

  end

  #--------------------------- Clean ----------------------------#

  desc "Sometimes clear Derived Data is needed"
  private_lane :deepClean do
    puts "A deep clean Sometimes needs 🛀"
    clear_derived_data
    clean_cocoapods_cache
    xcclean
  end

  #--------------------------- Build ----------------------------#

  desc "Generic steps to do before a build"
  private_lane :commonPreDeliveryBuildSteps do

    match(app_identifier: current_app_identifier, type: "appstore") # more information: https://codesigning.guide
    cocoapods(use_bundle_exec: false)
    gym(scheme: scheme_name) # Build your app - more options available
  
  end

  desc "Generic steps to do after a build"
  private_lane :commonPostDeliveryBuildSteps do

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts

    # Tag release and push to GitHub
    gitTag

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)  

  end

  ######################### PUBLIC LANES ##########################

  #------------------- Certificates matching ---------------------#

  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do

    match(app_identifier: current_app_identifier, type: "development")
    match(app_identifier: current_app_identifier, type: "appstore")
    match(app_identifier: current_app_identifier, type: "adhoc")
  
  end

  #--------------------------- Tests ----------------------------#

  desc "Runs all the tests"
  lane :test do

    scan
  
  end

  #------------------------- TestFlight -------------------------#

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :testflightBeta do

    commonPreDeliveryBuildSteps
    
    pilot ({
      skip_submission:true,
      skip_waiting_for_build_processing:true,
      distribute_external: true,
      changelog: "New build available"
    })

    slack(
      message: "Successfully deployed new App Update."
    )

    commonPostDeliveryBuildSteps

  end

  #----------------------- Crashlytics -------------------------#

  desc "Submits a new Beta Build to Fabric"
  lane :crashlyticsBeta do

    #check correct branch to  build
    checkCorrectBranch

    # set build number with actual "version number" + "jira's task code"
    new_build_number = "#{plain_version}" + "." + "#{jira_task_number}"

    increment_build_number_in_plist(
      xcodeproj: xcodeproj_path,
      build_number: new_build_number, # set a specific number
      target: scheme_name
    )

    ENV["GIT_SSH_COMMAND"] = "ssh -i ~/.ssh/id_rsa2"
    
    # git clone git@github.com:Organization/company-ios-certificates.git

    commonPreDeliveryBuildSteps

    crashlytics(
      crashlytics_path: './Pods/Crashlytics/', # path to your ‘Crashlytics.framework’
      api_token: '***********',
      build_secret: '***********',
     )

    slack(
      message: "Successfully deployed new App Update on Crashlytics #{new_build_number} for JIRA TASK: #{jira_issue_key}."
    )

    commonPostDeliveryBuildSteps

  end 

  #------------------------- Appstore --------------------------#

  desc "Deploy a new version to the App Store"
  lane :release do

    # snapshot
    cocoapods
    match(app_identifier: current_app_identifier, type: "appstore")
    gym(scheme: scheme_name) # Build your app - more options available
    deliver(force: true)
    # frameit
  
  end

end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "***********" # The bundle identifier of your app

apple_id "***********" # Your Apple email address

team_id "***********"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.25.0  | 💥 Check failed |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status  |
| ------------------------------------------ | ------- | -------------- |
| fastlane-plugin-update_project_codesigning | 0.2.0   | 💥 Check failed |
| fastlane-plugin-versioning                 | 0.2.6   | 💥 Check failed |
| fastlane-plugin-get_product_bundle_id      | 0.1.0   | 💥 Check failed |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| bundler                                    | 1.13.6       |
| rake                                       | 10.4.2       |
| i18n                                       | 0.7.0        |
| json                                       | 1.8.2        |
| minitest                                   | 5.5.1        |
| thread_safe                                | 0.3.4        |
| tzinfo                                     | 1.2.2        |
| activesupport                              | 4.2.0        |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.1        |
| babosa                                     | 1.0.2        |
| claide                                     | 0.7.0        |
| fuzzy_match                                | 2.0.4        |
| nap                                        | 0.8.0        |
| cocoapods-core                             | 0.35.0       |
| cocoapods-downloader                       | 0.8.1        |
| cocoapods-plugins                          | 0.3.2        |
| netrc                                      | 0.7.8        |
| cocoapods-trunk                            | 0.4.1        |
| cocoapods-try                              | 0.4.3        |
| colored                                    | 1.2          |
| escape                                     | 0.0.4        |
| molinillo                                  | 0.1.2        |
| open4                                      | 1.3.4        |
| xcodeproj                                  | 0.20.2       |
| cocoapods                                  | 0.35.0       |
| highline                                   | 1.7.8        |
| commander-fastlane                         | 4.4.4        |
| daemons                                    | 1.1.9        |
| unf_ext                                    | 0.0.7.2      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20170404 |
| dotenv                                     | 2.2.0        |
| eventmachine                               | 1.0.4        |
| excon                                      | 0.55.0       |
| multipart-post                             | 2.0.0        |
| faraday                                    | 0.12.0.1     |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.11.0.1     |
| fastimage                                  | 2.1.0        |
| gh_inspector                               | 1.0.3        |
| jwt                                        | 1.5.6        |
| little-plugger                             | 1.1.4        |
| multi_json                                 | 1.12.1       |
| logging                                    | 2.2.0        |
| memoist                                    | 0.15.0       |
| os                                         | 0.9.6        |
| signet                                     | 0.7.3        |
| googleauth                                 | 0.5.1        |
| httpclient                                 | 2.8.3        |
| hurley                                     | 0.2          |
| mime-types-data                            | 3.2016.0521  |
| mime-types                                 | 3.1          |
| uber                                       | 0.0.15       |
| representable                              | 2.3.0        |
| retriable                                  | 2.1.0        |
| google-api-client                          | 0.9.28       |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| plist                                      | 3.2.0        |
| rubyzip                                    | 1.2.1        |
| security                                   | 0.1.3        |
| slack-notifier                             | 1.5.1        |
| terminal-notifier                          | 1.7.1        |
| unicode-display_width                      | 1.1.3        |
| terminal-table                             | 1.7.3        |
| tty-screen                                 | 0.5.0        |
| word_wrap                                  | 1.0.0        |
| rouge                                      | 1.11.1       |
| xcpretty                                   | 0.2.6        |
| xcpretty-travis-formatter                  | 0.0.4        |
| fastlane-plugin-get_product_bundle_id      | 0.1.0        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
| fastlane-plugin-versioning                 | 0.2.6        |
| rack                                       | 1.6.0        |
| rack-protection                            | 1.5.3        |
| tilt                                       | 1.4.1        |
| sinatra                                    | 1.4.5        |
| thin                                       | 1.6.3        |
</details>

*generated on:* **2017-04-20**
</details>
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `native_targets' for #<Xcodeproj::Project:0x007f8971227278>
  /Library/Ruby/Gems/2.0.0/gems/fastlane-plugin-get_product_bundle_id-0.1.0/lib/fastlane/plugin/get_product_bundle_id/actions/get_product_bundle_id_action.rb:9:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:71:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:270:in `call'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:270:in `execute_flow_block'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:46:in `block in execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/fastlane/lib/fastlane/cli_tools_distributor.rb:65:in `take_off'
  /Library/Ruby/Gems/2.0.0/gems/fastlane-2.25.0/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[I think that ☝️ might be fine]

**Comment by lyndsey-ferguson** [comment]
This should be closed and tracked at [here](https://github.com/lyndsey-ferguson/fastlane_plugins/issues/7)
