### ISSUE TITLE
.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- shenzhen (LoadError)

### ISSUE THREAD

**Issue by jayczech23** [fastlane/fastlane#8937]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After running Fastlane, I get this error. I have been able to replicate it on 2 machines. I recall seeing this issue  after I run `bundle install` command

> from /Users/jay/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jay/Desktop/drivemode/fastlane/actions/ftp.rb:16:in `run'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:172:in `block (2 levels) in parsing_binding'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/jay/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.0/bin/fastlane:20:in `<top (required)>'
	from /Users/jay/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/jay/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'jay

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.6.2                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.6   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| CFPropertyList             | 2.3.5        |
| activesupport              | 4.2.7.1      |
| addressable                | 2.5.1        |
| aws-sdk-core               | 2.9.3        |
| aws-sigv4                  | 1.0.0        |
| babosa                     | 1.0.2        |
| bigdecimal                 | 1.2.6        |
| bundler                    | 1.14.3       |
| claide                     | 1.0.1        |
| cocoapods-deintegrate      | 1.0.1        |
| cocoapods-downloader       | 1.1.3        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| cocoapods-trunk            | 1.1.2        |
| cocoapods-try              | 1.1.0        |
| colored                    | 1.2          |
| colored2                   | 3.1.2        |
| commander                  | 4.4.3        |
| commander-fastlane         | 4.4.4        |
| domain_name                | 0.5.20161129 |
| dotenv                     | 2.2.0        |
| escape                     | 0.0.4        |
| excon                      | 0.55.0       |
| faraday                    | 0.11.0       |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.11.0.1     |
| fastimage                  | 2.1.0        |
| fastlane-plugin-versioning | 0.2.6        |
| fourflusher                | 2.0.1        |
| fuzzy_match                | 2.0.4        |
| gh_inspector               | 1.0.3        |
| google-api-client          | 0.9.26       |
| googleauth                 | 0.5.1        |
| highline                   | 1.7.8        |
| http-cookie                | 1.0.3        |
| httpclient                 | 2.8.3        |
| hurley                     | 0.2          |
| i18n                       | 0.8.1        |
| io-console                 | 0.4.3        |
| jmespath                   | 1.3.1        |
| json                       | 1.8.1        |
| jwt                        | 1.5.6        |
| libxml-ruby                | 2.9.0        |
| little-plugger             | 1.1.4        |
| logging                    | 2.1.0        |
| memoist                    | 0.15.0       |
| mime-types                 | 3.1          |
| mime-types-data            | 3.2016.0521  |
| mini_magick                | 4.5.1        |
| minitest                   | 5.10.1       |
| molinillo                  | 0.5.7        |
| multi_json                 | 1.12.1       |
| multi_xml                  | 0.6.0        |
| multipart-post             | 2.0.0        |
| nanaimo                    | 0.2.3        |
| nap                        | 1.1.0        |
| net-ssh                    | 4.1.0        |
| netrc                      | 0.7.8        |
| nokogiri                   | 1.5.6        |
| os                         | 0.9.6        |
| plist                      | 3.2.0        |
| power_assert               | 0.2.2        |
| psych                      | 2.0.8        |
| public_suffix              | 2.0.5        |
| rake                       | 10.4.2       |
| rdoc                       | 4.2.0        |
| representable              | 2.3.0        |
| retriable                  | 2.1.0        |
| rouge                      | 1.11.1       |
| ruby-macho                 | 0.2.6        |
| rubygems-update            | 2.5.2        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| signet                     | 0.7.3        |
| slack-notifier             | 1.5.1        |
| sqlite3                    | 1.3.13       |
| terminal-notifier          | 1.7.1        |
| terminal-table             | 1.7.3        |
| test-unit                  | 3.0.8        |
| thread_safe                | 0.3.6        |
| tty-screen                 | 0.5.0        |
| tzinfo                     | 1.2.3        |
| uber                       | 0.0.15       |
| unf                        | 0.1.4        |
| unf_ext                    | 0.0.7.2      |
| unicode-display_width      | 1.1.3        |
| word_wrap                  | 1.0.0        |
| xcodeproj                  | 1.4.4        |
| xcpretty                   | 0.2.4        |
| xcpretty-travis-formatter  | 0.0.4        |
</details>

*generated on:* **2017-04-20**
</details>

**Comment by invoodoo** [comment]
I'm experience the same issue and command "fastlane env" gives that output:

/usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- xcodeproj (LoadError)
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/setup/crashlytics_project_parser.rb:1:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/setup/setup.rb:47:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane.rb:9:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/lib/fastlane/cli_tools_distributor.rb:14:in `take_off'
	from /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-1.104.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `load'
	from /usr/local/lib/fastlane_lib/bundle/bin/fastlane:22:in `<main>'

**Comment by invoodoo** [comment]
And I have:

rvm rubies

=* ruby-2.4.0 [ x86_64 ]

Not sure if it is helpful.

**Comment by KrauseFx** [comment]
Seems like you're using a really old version of _fastlane_. Can you run `gem uninstall fastlane fastlane_core credentials_manager` and then `gem cleanup` (with `sudo` if needed). Afterwards install _fastlane_ again 👍

**Comment by invoodoo** [comment]
Thanks KrauseFx, I coudn't install yesterday it was a time out, did it today. Works perfect.

**Comment by KrauseFx** [comment]
Yeah, great to hear 👍
