### ISSUE TITLE
Undefined method 'add_external_tester!'

### ISSUE THREAD

**Issue by GitKelley** [fastlane/fastlane#8940]
### Issue Description

When using Spaceship to attempt to add an external user, a NoMethodError is displayed.

```
irb(main):004:0> app.add_external_tester!(email: "JohnK@blue.com", first_name: "John", last_name: "Kelley")
NoMethodError: undefined method `add_external_tester!' for #<Spaceship::Tunes::Application:0x0000000290bd00>
	from (irb):4
	from /usr/bin/irb:11:in '<main>'
```

Steps:
1) Launch IRB
2) require "spaceship"
3) Log in
4) Set app variable
5) app.add_external_tester!

Expected outcome:
Specified user is added to iTunes Connect list of external Testers

Actual Outcome:
NoMethodError is display

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                       |
| Ruby                        | 2.3.1                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.7.4                                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Ubuntu 16.04.2 LTS debian_based stretch/sid (4.8.0-46-generic) |
| Ruby Lib Dir                | /usr/lib                                                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US       | 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160216 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types                | 2.6.1        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-04-20**
</details>

**Comment by ohayon** [comment]
Hey @GitKelley, when Apple pushed out some new TestFlight updates a couple of weeks ago they broke this functionality. You now need to add testers directly to external testing groups in the scope of an app. You can do this by getting the `Spaceship::Tunes::Application` and then getting the groups for that app by using `Spaceship::TestFlight::Group.all(app_id: app.apple_id)` and then calling `add_tester_to_group` but it is much easier just to go through the _pilot_ interface where you can easily pass the app ID, group names and tester information.

I am going to close this issue, but please feel free to comment and/or reopen if you continue to run into issues.

Thanks! 🐙 🚀

**Comment by GitKelley** [comment]
Ah thanks man. I was able to get around it similarly to the way you described. I opened up the invite_controller.rb file for Boarding to find how you guys are doing it in there, and found the method to add someone to the default group, which happens to work perfectly for my use case.

**Comment by ohayon** [comment]
Great! FWIW we are going to be making some changes to how boarding works to support the new groups too.
