### ISSUE TITLE
Is there a way to just do a build using gym without the actual ipa process?

### ISSUE THREAD

**Issue by rounak** [fastlane/fastlane#8944]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I just wanted to see if a certain target compiles or not, even if I don't have the signing credentials for that particular target, nor do I want the IPA file.

**Comment by taquitos** [comment]
There is now, @rounak  :) https://github.com/fastlane/fastlane/pull/8734

**Comment by ohayon** [comment]
@rounak let us know if you are still having issues and we would be happy to help! 🚀
