### ISSUE TITLE
Error while implementing Fastlane

### ISSUE THREAD

**Issue by avish07** [fastlane/fastlane#8952]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

 [!] Permission denied @ dir_s_mkdir - /Users/gh/.fastlane/spaceship (Errno::EACCES

**Comment by PetrosIchor** [comment]
Please explain your issue and follow paying guidelines. It helps you get a valuable response.  The error you attached explains the problem, you have permissions issues in a path.  You'll need to ensure that file/directory has the correct permissions set.

**Comment by ohayon** [comment]
Hey @avish07, I am going to close this issue as there is no issue mentioned here. If you could, please submit a new issue with the error output and any other information you can provide. Thanks!
