### ISSUE TITLE
Error ITC.apps.tf.build.test.info.missing.whats.new while `distribute_external=false`

### ISSUE THREAD

**Issue by MartijnSchoemaker** [fastlane/fastlane#8954]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running 'pilot' with parameter distribute_external on 'false'. I get this error:
{"code"=>"ITC.apps.tf.build.test.info.missing.whats.new", "description"=>"Missing what's new info."}

Dispite this, the build is delivered and available for internal testing.

##### Complete output when running fastlane, including the stack trace and command used

Run `fastlane env` to append the fastlane environment to your issue

```
14:43:29 /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/client.rb:118:in `handle_response': [31m[!] {"code"=>"ITC.apps.tf.build.test.info.missing.whats.new", "description"=>"Missing what's new info."}[0m (Spaceship::Client::UnexpectedResponse)
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/client.rb:87:in `post_for_testflight_review'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/build.rb:165:in `submit_for_testflight_review!'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/pilot/lib/pilot/build_manager.rb:114:in `distribute_build'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/pilot/lib/pilot/build_manager.rb:57:in `distribute'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/pilot/lib/pilot/build_manager.rb:40:in `upload'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/actions/pilot.rb:15:in `run'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:226:in `chdir'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
14:43:29 	from Fastfile:70:in `block (2 levels) in parsing_binding'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/lane.rb:33:in `call'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/lane.rb:33:in `call'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.2/bin/fastlane:20:in `<top (required)>'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/bin/fastlane:22:in `load'
14:43:29 	from /Users/monitor/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.1                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-04-21**
</details>

**Comment by Vkt0r** [comment]
Same issue here!!! Build was deployed too to internal testers

**Comment by avsmirnov567** [comment]
Same for me, was deployed for internal, also.

**Comment by esetnik** [comment]
Same issue here

**Comment by tache** [comment]
ditto - builds uploads just fine ...
```
[16:00:58]: Successfully uploaded the new binary to iTunes Connect
[16:00:58]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
... snip ...
[16:30:32]: Successfully finished processing the build 2.0.6 - 632
[16:30:36]: {"code"=>"ITC.apps.tf.build.missing.primary.test.info", "description"=>"Missing primary test info."}
```

**Comment by thatjuan** [comment]
Sounds like you have to fill this.. it may be a new testflight requirement

![screenshot 2017-04-22 17 31 46](https://cloud.githubusercontent.com/assets/389677/25308762/a8aac320-2781-11e7-80d6-b07d78b4668e.png)

**Comment by agordeev** [comment]
Sounds like a weird requirement for internal testing.

**Comment by tache** [comment]
Yep - seems strange to need the external info for the internal build.

**Comment by jerolimov** [comment]
Same error with external testing and this pilot setup:

```ruby
    pilot(
      distribute_external: true,
      changelog: "New version...",
      beta_app_description: "This is a preview of our new app...",
      beta_app_feedback_email: "feedback@...",
      testers_file_path: "./fastlane/ios-testers.csv"
    )
```

**Comment by mrgerh** [comment]
Same error `{"code"=>"ITC.apps.tf.build.test.info.missing.whats.new", "description"=>"Missing what's new info."}`
when `Distributing new build to testers: 1.1.0 - 8`
Our pilot call:
```
    pilot(
      changelog: "release notes",
      beta_app_description: "My great app for iPad",
      beta_app_feedback_email: "email@domain.com",
      update_build_info_on_upload: true,
      distribute_external: true
      )
```

**Comment by mpirri** [comment]
We are looking into this now - thanks for all the info. We'll update just as soon as we have a sense of what we need to do to get this fixed.

**Comment by mpirri** [comment]
@jerolimov - a question for you. Which version of _fastlane_ are you using? I am able to reproduce @mrgerh 's issue (`update_build_info_on_upload: true` is currently broken with new TestFlight) as well as the @MartijnSchoemaker 's original issue (`distribute_external: false` is currently being ignored...).  You aren't using either of these flags (and I cannot currently reproduce what you are seeing with your invocation to pilot). Can you provide the output of `fastlane env` and the error output you are seeing? Thanks!!!

**Comment by tache** [comment]
follow-up : I have all the information on ITC TestFlight filled in for the external release. I now see this 
`INFO [2017-04-24 16:21:35.74]: {"code"=>"ITC.apps.tf.build.test.info.missing.feedback", "description"=>"Missing feedback email."}`
The TestFlight build is uploaded.

```
    testflight(
      apple_id: itcid,
      skip_waiting_for_build_processing: false,
      app_identifier: appid,
      changelog: notes
    )
```

**Comment by jerolimov** [comment]
@mpirri 

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bundler                   | 1.14.5       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-04-24**
</details>

**Comment by jerolimov** [comment]
@mpirri Maybe I'm wrong and this fails with `distribute_external: false` for me, too.

Here is the end of the build process. Will trigger the external build now. If you make a release with your changes this would be great. Would test it asap.

<details><summary>Log:</summary>
[23:49:27]: -------------------
[23:49:27]: --- Step: pilot ---
[23:49:27]: -------------------
[23:49:27]: Login to iTunes Connect (xxx)
[23:49:31]: Login successful
[23:49:31]: Ready to upload new build to TestFlight (App: xxx)...
[23:49:32]: Going to upload updated app to iTunes Connect
[23:49:32]: This might take a few minutes. Please don't interrupt the script.
[23:50:25]: iTunes Transporter successfully finished its job
[23:50:26]: --------------------------------------------------------------------
[23:50:26]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[23:50:26]: --------------------------------------------------------------------
[23:50:26]: Successfully uploaded the new binary to iTunes Connect
[23:50:26]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
[23:50:33]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:50:45]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:50:56]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:51:09]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:51:21]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:51:33]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:51:35]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:51:45]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:51:47]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:51:57]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:51:58]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:52:08]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:52:10]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:52:20]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:52:23]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:52:33]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:52:35]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:52:45]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:52:46]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:52:56]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:52:58]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:53:08]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:53:10]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:53:20]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:53:22]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:53:32]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:53:34]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:53:44]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:53:46]: Build doesn't show up in the build list any more, waiting for it to appear again
[23:53:56]: Waiting for iTunes Connect to finish processing the new build (0.2 - 0.2.4100)
[23:53:58]: Successfully finished processing the build 0.2 - 0.2.4100
[23:53:58]: Distributing new build to testers: 0.2 - 0.2.4100
+-----------------------------------+--------------------------------------------------------------------------------------------------------+
|                                                                Lane Context                                                                |
+-----------------------------------+--------------------------------------------------------------------------------------------------------+
| DEFAULT_PLATFORM                  | ios                                                                                                    |
| PLATFORM_NAME                     | ios                                                                                                    |
| LANE_NAME                         | ios alpha                                                                                              |
| GET_INFO_PLIST_VALUE_CUSTOM_VALUE | 0.2                                                                                                    |
| CERT_FILE_PATH                    | /Users/christoph/builds/1bc18031/0/xx/ios/725ZH2XX4G.cer                               |
| CERT_CERTIFICATE_ID               | 725ZH2XX4G                                                                                             |
| SIGH_PROFILE_PATH                 | /Users/christoph/builds/1bc18031/0/xx/ios/AppStore_com.xx.mobileprovision     |
| SIGH_PROFILE_PATHS                | ["/Users/christoph/builds/1bc18031/0/xx/ios/AppStore_com.xx.mobileprovision"] |
| SIGH_UDID                         | 712bd885-7aa7-4157-b0a4-562c37c32d0d                                                                   |
| SIGH_UUID                         | 712bd885-7aa7-4157-b0a4-562c37c32d0d                                                                   |
| SIGH_PROFILE_TYPE                 | app-store                                                                                              |
| IPA_OUTPUT_PATH                   | /Users/christoph/builds/1bc18031/0/xx/xx.ipa                                   |
| DSYM_OUTPUT_PATH                  | /Users/christoph/builds/1bc18031/0/xx/xx.app.dSYM.zip                          |
| XCODEBUILD_ARCHIVE                | /Users/christoph/Library/Developer/Xcode/Archives/2017-04-24/xx 2017-04-24 23.45.42.xcarchive  |
+-----------------------------------+--------------------------------------------------------------------------------------------------------+
[23:54:00]: {"code"=>"ITC.apps.tf.build.test.info.missing.whats.new", "description"=>"Missing what's new info."}

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | get_info_plist_value                | 0           |
| 4    | set_info_plist_value                | 0           |
| 5    | Switch to ios update_certs lane     | 0           |
| 6    | cert                                | 6           |
| 7    | sigh                                | 7           |
| 8    | gym                                 | 229         |
| 💥   | pilot                               | 272         |
+------+-------------------------------------+-------------+

[23:54:00]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Error ITC.apps.tf.build.test.info.missing.whats.new while `distribute_external=false`
   https://github.com/fastlane/fastlane/issues/8954 [open] 13 💬
   an hour ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/spaceship/lib/spaceship/test_flight/client.rb:118:in `handle_response': [!] {"code"=>"ITC.apps.tf.build.test.info.missing.whats.new", "description"=>"Missing what's new info."} (Spaceship::Client::UnexpectedResponse)
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/spaceship/lib/spaceship/test_flight/client.rb:87:in `post_for_testflight_review'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/spaceship/lib/spaceship/test_flight/build.rb:165:in `submit_for_testflight_review!'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/pilot/lib/pilot/build_manager.rb:114:in `distribute_build'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/pilot/lib/pilot/build_manager.rb:57:in `distribute'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/pilot/lib/pilot/build_manager.rb:40:in `upload'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/pilot.rb:15:in `run'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:68:in `block (2 levels) in parsing_binding'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/gems/fastlane-2.28.3/bin/fastlane:20:in `<top (required)>'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `load'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/bin/fastlane:23:in `<main>'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/christoph/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
nimo-macmini.fritz.box .bash_profile
ERROR: Build failed: exit status 1
</detail>

**Comment by jerolimov** [comment]
@mpirri Ok tested it again with internal and external distribution. External: true works, but the external: false doesn't work. So, if you fixed this issue, you can release it and close this issue.

Thank you 👍

**Comment by tache** [comment]
Adding the following to pilot helps it along a but, but then crashes on `undefined method 'export_compliance_missing?'` ... I think the export issue might be addressed in #8980, so I will check when the next release is out.
```
beta_app_description: "My great app for iPad",
beta_app_feedback_email: "email@domain.com",
```

**Comment by mpirri** [comment]
Hi folks! Update to the latest version of _fastlane_ and see if you are still having problems. I'm confident we have resolved the issues that you are all suffering from.

I'm going to close this issue; please feel free to open another issue if you are still having difficulty!

Thanks!

**Comment by jerolimov** [comment]
Works fine (on our CI server ;)). Thank you! :+1:

**Comment by MartijnSchoemaker** [comment]
Same for me; it's working again. :tada:

**Comment by Daredevilll** [comment]
Mine now works fine too. 👍.

My solution was to add "changelog" parameter to pilot.

**Comment by Vkt0r** [comment]
Nice job !!! Working again with the latest release 🎉🎉🎉
