### ISSUE TITLE
Match Question

### ISSUE THREAD

**Issue by louiesanyu** [fastlane/fastlane#8956]
Have a question!
Is match operation default download all certs and profiles from AppDeveloper or revoke old files then create new certs and profiles ?

**Comment by PetrosIchor** [comment]
No.  Check the docs, check the readme, and play around with it to see which features meet your needs. 

https://github.com/fastlane/fastlane/blob/master/match/README.md

**Comment by KrauseFx** [comment]
_match_ kind of requires you to first nuke your existing profiles and certificates before using it.

**Comment by louiesanyu** [comment]
OK，thanks for your response.
