### ISSUE TITLE
When I'm trying to upload my app, fastlane crashes

### ISSUE THREAD

**Issue by thehorbach** [fastlane/fastlane#8967]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi, when I'm trying to upload my ipa to itunes connect - fastlane finished with errors. Thank you 🙏  

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Command Used: `upload`
<details><summary>Output/Log</summary>

```

DEBUG [2017-04-22 16:37:56.74]: Checking if there are any plugins that should be loaded...
INFO [2017-04-22 16:37:56.76]: -------------------------------------------------
INFO [2017-04-22 16:37:56.76]: --- Step: Verifying required fastlane version ---
INFO [2017-04-22 16:37:56.76]: -------------------------------------------------
INFO [2017-04-22 16:37:56.76]: Your fastlane version 2.28.3 matches the minimum requirement of 2.28.3  ✅
INFO [2017-04-22 16:37:56.77]: ------------------------------
INFO [2017-04-22 16:37:56.77]: --- Step: default_platform ---
INFO [2017-04-22 16:37:56.77]: ------------------------------
INFO [2017-04-22 16:37:56.77]: Driving the lane 'ios upload' 🚀
INFO [2017-04-22 16:37:56.77]: -----------------------
INFO [2017-04-22 16:37:56.77]: --- Step: cocoapods ---
INFO [2017-04-22 16:37:56.77]: -----------------------
INFO [2017-04-22 16:37:57.04]: gem 'cocoapods' is already installed
INFO [2017-04-22 16:37:57.04]: $ pod install
INFO [2017-04-22 16:37:59.15]: ▸ Analyzing dependencies
INFO [2017-04-22 16:37:59.15]: ▸ Downloading dependencies
INFO [2017-04-22 16:37:59.15]: ▸ Using Alamofire (4.4.0)
INFO [2017-04-22 16:37:59.15]: ▸ Using Cloudinary (2.0.1)
INFO [2017-04-22 16:37:59.15]: ▸ Using Crashlytics (3.8.4)
INFO [2017-04-22 16:37:59.15]: ▸ Using Fabric (1.6.11)
INFO [2017-04-22 16:37:59.15]: ▸ Using PureLayout (3.0.2)
INFO [2017-04-22 16:37:59.15]: ▸ Using RevealingSplashView (0.1.0)
INFO [2017-04-22 16:37:59.15]: ▸ Using SAConfettiView (0.1.8)
INFO [2017-04-22 16:37:59.15]: ▸ Using SVProgressHUD (2.1.2)
INFO [2017-04-22 16:37:59.15]: ▸ Using SwiftKeychainWrapper (3.0.1)
INFO [2017-04-22 16:37:59.15]: ▸ Using SwiftyJSON (3.1.4)
INFO [2017-04-22 16:37:59.15]: ▸ Using iosMath (0.9.3)
INFO [2017-04-22 16:37:59.15]: ▸ Generating Pods project
INFO [2017-04-22 16:37:59.15]: ▸ Integrating client project
INFO [2017-04-22 16:38:01.81]: ▸ Sending stats
INFO [2017-04-22 16:38:01.84]: ▸ Pod installation complete! There are 11 dependencies from the Podfile and 11 total pods installed.
INFO [2017-04-22 16:38:01.87]: ---------------------
INFO [2017-04-22 16:38:01.87]: --- Step: deliver ---
INFO [2017-04-22 16:38:01.87]: ---------------------
Successfully loaded Appfile at path '/Users/vyacheslav/Desktop/pokemonz-app-ios/fastlane/Appfile'
- app_identifier: 'com.horbac.pokemonz-app'
- apple_id: 'vjacheslav.horbach@gmail.com'
- team_id: 'MJ6Q39T6CJ'
-------
INFO [2017-04-22 16:38:01.91]: Successfully loaded '/Users/vyacheslav/Desktop/pokemonz-app-ios/fastlane/Deliverfile' 📄

+------------------------+--------------------------------------+
|         Detected Values from './fastlane/Deliverfile'         |
+------------------------+--------------------------------------+
| app_identifier         | com.horbac.pokemonz-app                   |
| username               | vjacheslav.horbach@gmail.com                     |
| price_tier             | 0                                    |
| app_review_information | {:first_name=>"Vjaceslav",           |
|                        | :last_name=>"Horbac",                |
|                        | :phone_number=>"+44 7490 403 517",   |
|                        | :email_address=>"vjacheslav.horbach@gmail.com",  |
|                        | :demo_user=>"No demo account         |
|                        | needed", :demo_password=>"No demo    |
|                        | account needed", :notes=>"Hello,     |
|                        | Apple Reviewer! TEST TEST\n\n  We    |
|                        | forgot to include our in-app         |
|                        | purchases together with our          |
|                        | previous build. We just fixed        |
|                        | that.\n\n  Thanks again and keep     |
|                        | rocking!\n  Vjacelsav\n\n  ps. you   |
|                        | make App Store better!"}             |
| submission_information | {:export_compliance_encryption_upda  |
|                        | ted=>false,                          |
|                        | :export_compliance_uses_encryption=  |
|                        | >false,                              |
|                        | :content_rights_contains_third_part  |
|                        | y_content=>false,                    |
|                        | :add_id_info_uses_idfa=>false}       |
| automatic_release      | false                                |
| app_icon               | ./fastlane/metadata/app_icon.jpg     |
| copyright              | Copyright (c) 2017 Vjaceslav Horbac    |
|                        | Ltd                                  |
| primary_category       | MZGenre.Education                    |
| secondary_category     | MZGenre.Utilities                    |
| app_rating_config_path | ./fastlane/metadata/itunes_rating_c  |
|                        | onfig.json                           |
+------------------------+--------------------------------------+

INFO [2017-04-22 16:38:01.92]: Login to iTunes Connect (vjacheslav.horbach@gmail.com.com)
WARN [2017-04-22 16:38:04.62]: Lane Context:
INFO [2017-04-22 16:38:04.62]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios upload"}
ERROR [2017-04-22 16:38:04.62]: 
INFO [2017-04-22 16:38:04.62]: Successfully generated documentation at path '/Users/vyacheslav/Desktop/pokemonz-app-ios/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | cocoapods           | 5           |
| 💥   | deliver             | 2           |
+------+---------------------+-------------+

ERROR [2017-04-22 16:38:04.64]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: 

URL: https://api.github.com/search/issues?q=+repo:fastlane/fastlane
➡️  Feature request: use deliver to manage apps bundle metadata and screenshots
   https://github.com/fastlane/fastlane/issues/8965 [open] 2 💬
   11 hours ago

➡️  Pilot - Error when distributing build to external group
   https://github.com/fastlane/fastlane/issues/8964 [open] 0 💬
   15 hours ago

➡️  Fixed recent spaceship change to work on Ruby 2.0 too
   https://github.com/fastlane/fastlane/pull/8963 [closed] 1 💬
   an hour ago

and 8950 more at: https://github.com/fastlane/fastlane/search?q=&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
    cert
    sigh(force: true)
  end

  desc "Create ipa"
  lane :build do
    increment_build_number
    gym
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "pokemonz-appr") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "pokemonz-app") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # This block is called if there was an error running a lane.
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.horbac.pokemonz-app" # The bundle identifier of your app
apple_id "vjacheslav.horbach@gmail.com.com" # Your Apple email address

team_id "MJ6Q39T6CJ" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| bigdecimal                | 1.3.0        |
| psych                     | 2.2.2        |
</details>

*generated on:* **2017-04-22**
</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.3"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
    cert
    sigh(force: true)
  end

  desc "Create ipa"
  lane :build do
    increment_build_number
    gym
  end

  desc "Upload to App Store"
  lane :upload do
    deliver
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "pokemonz-app") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "pokemonz-app") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # This block is called if there was an error running a lane.
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.horbac.pokemonz-app" # The bundle identifier of your app
apple_id "vjacheslav.horbach@gmail.com.com" # Your Apple email address

team_id "MJ6Q39T6CJ" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-04-22**
</details>

**Comment by thehorbach** [comment]
I've just remembered that Apple is currently updating their servers, so they are in maintenance mode. I'll try again, once they're back online.

**Comment by ohayon** [comment]
Hey @thehorbach could you confirm if this is fixed or not?

**Comment by thehorbach** [comment]
@ohayon sorry, forgot - yes it was Apple Servers :]

**Comment by ohayon** [comment]
WOOT 🚀
