### ISSUE TITLE
Scan failing for macOS target

### ISSUE THREAD

**Issue by tiferrei** [fastlane/fastlane#8969]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
fastlane fails to run scan for macOS target, even though it runs perfectly (and passes tests) on Xcode. iOS target (`fastlane ios test`) runs perfectly. The issue seems to be incorrect simulator picked, I tried adding `device: "",` to the mac tests and it defaults to the iOS SDK, that would explain this: `No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=armv7s armv7 arm64).` However, I do not know which device to pick for macOS targets, I do not want to put my machine name in it because this would be running in multiple machines. The code is [open source](https://github.com/tiferrei/UCLKit) just in case someone needs to take a look at the xcode project.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

–> `bundle exec fastlane mac test --capture_output`
### Captured Output

Command Used: `mac test`
<details><summary>Output/Log</summary>

```

DEBUG [2017-04-23 00:06:18.18]: Checking if there are any plugins that should be loaded...
INFO [2017-04-23 00:06:18.19]: -------------------------------------------------
INFO [2017-04-23 00:06:18.19]: --- Step: Verifying required fastlane version ---
INFO [2017-04-23 00:06:18.19]: -------------------------------------------------
INFO [2017-04-23 00:06:18.19]: Your fastlane version 2.28.3 matches the minimum requirement of 2.14.2  ✅
INFO [2017-04-23 00:06:18.20]: ------------------------------
INFO [2017-04-23 00:06:18.20]: --- Step: default_platform ---
INFO [2017-04-23 00:06:18.20]: ------------------------------
INFO [2017-04-23 00:06:18.20]: Driving the lane 'mac test' 🚀
INFO [2017-04-23 00:06:18.20]: --------------------------------
INFO [2017-04-23 00:06:18.20]: --- Step: clear_derived_data ---
INFO [2017-04-23 00:06:18.20]: --------------------------------
INFO [2017-04-23 00:06:18.20]: Derived Data path located at: /Users/tiferrei/Library/Developer/Xcode/DerivedData
INFO [2017-04-23 00:06:18.27]: Successfully cleared Derived Data ♻️
INFO [2017-04-23 00:06:18.27]: ------------------
INFO [2017-04-23 00:06:18.27]: --- Step: scan ---
INFO [2017-04-23 00:06:18.27]: ------------------
INFO [2017-04-23 00:06:18.30]: $ xcodebuild -list -project ./UCLKit.xcodeproj
INFO [2017-04-23 00:06:21.42]: $ xcodebuild -showBuildSettings -scheme UCLKit\ macOS -project ./UCLKit.xcodeproj
DEBUG [2017-04-23 00:06:23.95]: Detected derived data path '/Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw'
INFO [2017-04-23 00:06:23.95]: $ xcodebuild -list -project ./UCLKit.xcodeproj
INFO [2017-04-23 00:06:25.40]: $ xcodebuild -showBuildSettings -scheme UCLKit\ macOS -project ./UCLKit.xcodeproj

+------------------------+--------------------------------------+
|                    Summary for scan 2.28.3                    |
+------------------------+--------------------------------------+
| sdk                    | macosx10.12                          |
| scheme                 | UCLKit macOS                         |
| clean                  | true                                 |
| project                | ./UCLKit.xcodeproj                   |
| derived_data_path      | /Users/tiferrei/Library/Developer/X  |
|                        | code/DerivedData/UCLKit-frwqpofeqpq  |
|                        | ijpbwjfyopyuxqenw                    |
| skip_build             | false                                |
| output_directory       | ./fastlane/test_output               |
| output_types           | html,junit                           |
| buildlog_path          | ~/Library/Logs/scan                  |
| include_simulator_logs | false                                |
| open_report            | false                                |
| skip_slack             | false                                |
| slack_only_on_failure  | false                                |
| use_clang_report_name  | false                                |
| fail_build             | true                                 |
| xcode_path             | /Applications/Xcode.app              |
+------------------------+--------------------------------------+

INFO [2017-04-23 00:06:26.64]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme UCLKit\ macOS -project ./UCLKit.xcodeproj -sdk 'macosx10.12' -destination 'platform=macOS' -derivedDataPath '/Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw' clean build test | tee '/Users/tiferrei/Library/Logs/scan/UCLKit-UCLKit macOS.log' | xcpretty
INFO [2017-04-23 00:06:26.64]: ▸ Loading...
INFO [2017-04-23 00:06:27.99]: ▸ Cleaning UCLKit/UCLKit macOS [Debug]
INFO [2017-04-23 00:06:27.99]: ▸ Check Dependencies
INFO [2017-04-23 00:06:28.08]: ▸ Clean Succeeded
INFO [2017-04-23 00:06:28.09]: ▸ Building UCLKit/UCLKit macOS [Debug]
INFO [2017-04-23 00:06:28.09]: ▸ Check Dependencies
INFO [2017-04-23 00:06:28.13]: ▸ Processing Info.plist
INFO [2017-04-23 00:06:28.27]: ▸ Compiling Configuration.swift
INFO [2017-04-23 00:06:32.67]: ▸ Compiling UCLKit.swift
INFO [2017-04-23 00:06:32.67]: ▸ Compiling RoomBookings.swift
INFO [2017-04-23 00:06:33.33]: ▸ Compiling UCLKit_vers.c
INFO [2017-04-23 00:06:33.90]: ▸ Linking UCLKit
INFO [2017-04-23 00:06:34.49]: ▸ Copying UCLKit.h
INFO [2017-04-23 00:06:34.62]: Running Tests: ▸ Touching UCLKit.framework
INFO [2017-04-23 00:06:34.64]: ▸ Build Succeeded
INFO [2017-04-23 00:06:34.65]: ▸ 2017-04-23 00:06:34.657 xcodebuild[8708:5646077]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
INFO [2017-04-23 00:06:34.65]: ▸ /Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw/Logs/Test/A9B55740-1654-4666-B19F-77DD017C77B7/Session-UCLKit macOS Tests-2017-04-23_000634-g7JrSy.log
INFO [2017-04-23 00:06:34.65]: ▸ 2017-04-23 00:06:34.657 xcodebuild[8708:5646072] [MT] IDETestOperationsObserverDebug: (A2A6C4CA-4A0C-496A-A614-9E4EFB874651) Beginning test session UCLKit macOS Tests-A2A6C4CA-4A0C-496A-A614-9E4EFB874651 at 2017-04-23 00:06:34.657 with Xcode 8E2002 on target <DVTLocalComputer: 0x7f8bf7c9b0a0 (My Mac | x86_64h)> (10.12.5 (16F60a))
INFO [2017-04-23 00:06:34.83]: ▸ Building UCLKit/UCLKit macOS [Debug]
INFO [2017-04-23 00:06:34.84]: ▸ Check Dependencies
INFO [2017-04-23 00:06:34.85]: ▸ Building UCLKit/UCLKit iOS [Debug]
INFO [2017-04-23 00:06:34.85]: ▸ Check Dependencies
INFO [2017-04-23 00:06:34.85]: ▸ 2017-04-23 00:06:34.854 xcodebuild[8708:5646072] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw/Logs/Test/A9B55740-1654-4666-B19F-77DD017C77B7/Session-UCLKit macOS Tests-2017-04-23_000634-g7JrSy.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw/Logs/Test/A9B55740-1654-4666-B19F-77DD017C77B7/Session-UCLKit macOS Tests-2017-04-23_000634-g7JrSy.log}
INFO [2017-04-23 00:06:34.86]: ▸ Testing failed:
INFO [2017-04-23 00:06:34.86]: ▸ No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=armv7s armv7 arm64).
INFO [2017-04-23 00:06:34.86]: ▸ ** TEST FAILED **
INFO [2017-04-23 00:06:34.86]: ▸ The following build commands failed:
INFO [2017-04-23 00:06:34.86]: ▸ Check dependencies
INFO [2017-04-23 00:06:34.86]: ▸ (1 failure)
▸ Cleaning UCLKit/UCLKit macOS [Debug]
▸ Check Dependencies
▸ Clean Succeeded
▸ Building UCLKit/UCLKit macOS [Debug]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling Configuration.swift
▸ Compiling UCLKit.swift
▸ Compiling RoomBookings.swift
▸ Compiling UCLKit_vers.c
▸ Linking UCLKit
▸ Copying UCLKit.h
▸ Touching UCLKit.framework
▸ Build Succeeded
2017-04-23 00:06:34.657 xcodebuild[8708:5646077]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw/Logs/Test/A9B55740-1654-4666-B19F-77DD017C77B7/Session-UCLKit macOS Tests-2017-04-23_000634-g7JrSy.log
2017-04-23 00:06:34.657 xcodebuild[8708:5646072] [MT] IDETestOperationsObserverDebug: (A2A6C4CA-4A0C-496A-A614-9E4EFB874651) Beginning test session UCLKit macOS Tests-A2A6C4CA-4A0C-496A-A614-9E4EFB874651 at 2017-04-23 00:06:34.657 with Xcode 8E2002 on target <DVTLocalComputer: 0x7f8bf7c9b0a0 (My Mac | x86_64h)> (10.12.5 (16F60a))
▸ Building UCLKit/UCLKit macOS [Debug]
▸ Check Dependencies
▸ Building UCLKit/UCLKit iOS [Debug]
▸ Check Dependencies
2017-04-23 00:06:34.854 xcodebuild[8708:5646072] Error Domain=IDETestOperationsObserverErrorDomain Code=4 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw/Logs/Test/A9B55740-1654-4666-B19F-77DD017C77B7/Session-UCLKit macOS Tests-2017-04-23_000634-g7JrSy.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw/Logs/Test/A9B55740-1654-4666-B19F-77DD017C77B7/Session-UCLKit macOS Tests-2017-04-23_000634-g7JrSy.log}

Testing failed:
No architectures to compile for (ARCHS=x86_64, VALID_ARCHS=armv7s armv7 arm64).
** TEST FAILED **


The following build commands failed:
Check dependencies
(1 failure)
ERROR [2017-04-23 00:06:34.88]: Exit status: 65
WARN [2017-04-23 00:06:34.89]: Lane Context:
INFO [2017-04-23 00:06:34.89]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:mac, :LANE_NAME=>"mac test", :SCAN_DERIVED_DATA_PATH=>"/Users/tiferrei/Library/Developer/Xcode/DerivedData/UCLKit-frwqpofeqpqijpbwjfyopyuxqenw", :SCAN_GENERATED_PLIST_FILES=>[], :SCAN_GENERATED_PLIST_FILE=>nil}
ERROR [2017-04-23 00:06:34.89]: Error building the application - see the log above
INFO [2017-04-23 00:06:34.89]: Successfully generated documentation at path '/Users/tiferrei/Developer/UCLKit/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | clear_derived_data  | 0           |
| 💥   | scan                | 16          |
+------+---------------------+-------------+

ERROR [2017-04-23 00:06:34.91]: fastlane finished with errors


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F60a)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios
platform :ios do
  before_all do
    clear_derived_data
  end

  desc "Test UCLKit iOS."
  lane :test do
    scan(
	  sdk: "iphonesimulator",
	  scheme: "UCLKit iOS",
	  device: "iPhone 7",
	  clean: true)
  end
end

platform :mac do
  before_all do
    clear_derived_data
  end

  desc "Test UCLKit macOS."
  lane :test do
    scan(
      sdk: "macosx10.12",
	  scheme: "UCLKit macOS",
	  clean: true)
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-04-23**

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F60a)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios
platform :ios do
  before_all do
    clear_derived_data
  end

  desc "Test UCLKit iOS."
  lane :test do
    scan(
	  sdk: "iphonesimulator",
	  scheme: "UCLKit iOS",
	  device: "iPhone 7",
	  clean: true)
  end
end

platform :mac do
  before_all do
    clear_derived_data
  end

  desc "Test UCLKit macOS."
  lane :test do
    scan(
      sdk: "macosx10.12",
	  scheme: "UCLKit macOS",
	  clean: true)
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.2.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-04-23**

**Comment by KieranHarper** [comment]
Are you running back-to-back scans with other targets first? I have noticed it will only succeed if the first scan is for the mac target (specifying no devices), then the subsequent scans are the other targets with devices specified. Might be nicer if we could specify "Mac" as the device tho.

**Comment by KrauseFx** [comment]
Actually _fastlane_ isn't optimized for macOS apps unfortunately, you'll run into issues 😢

**Comment by tiferrei** [comment]
So fastlane stopped supporting macOS apps?
Is it only macOS apps that are not supported or also watchOS, tvOS?

**Comment by KrauseFx** [comment]
Some tools still support macOS, however we don't actively work on them, and test them on every release. So it comes without guarantee
