### ISSUE TITLE
Spaceship can't resend invite to testers

### ISSUE THREAD

**Issue by Lida** [fastlane/fastlane#8970]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

tunes_client has a reinvite_members but no reinvite_testers.

The REST call currently look something like this:

https://itunesconnect.apple.com/testflight/v1/invites/APP_ID/resend?testerId=TESTER_ID

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.4.5                           |
| Installation Source         | ~/.rbenv/versions/2.2.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 1.8.6        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| bundler                   | 1.14.6       |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-04-22**
</details>

**Comment by KrauseFx** [comment]
What is the re-invite feature used for? For sending another email reminder?

**Comment by Lida** [comment]
Correct, to send another email reminder. The use case is in boarding, if a user re-enters their info, then we should resend invite since they missed it previously.

**Comment by joelklabo** [comment]
I would like this feature also. @KrauseFx do you think this would get merged if I made a pull request? I can just hack my local version but if it's something others want I could work on making a real PR for it.

**Comment by KrauseFx** [comment]
That sounds reasonable, however I don't know how much work this is, and how much changes would be required within _spaceship_. 
Do you want to use this as part of _boarding_, _pilot_ or do you use _spaceship_ directly?

**Comment by Lida** [comment]
The REST call looks simple enough so it should be a fairly straightforward implementation. It probably make sense as part of *spaceship* with *boarding* resending invite if user registered previously.

**Comment by KrauseFx** [comment]
Sounds like a great idea. Is that something you can prepare a PR for? More than happy to review and merge the change 👍 Let me know if you need any help getting started.

**Comment by joelklabo** [comment]
I think I'll try this @Lida unless you're already doing it?

**Comment by Lida** [comment]
@joelklabo I haven't started working on it yet. It's all yours.

**Comment by joelklabo** [comment]
It looks like this is a pretty simple addition except for the fact that the base URL is different which makes this hard to use with the same patter as the other URLs.

I might have to make a custom `request` method for this one call. If there is a more obvious way I'd be happy to hear it!

**Comment by joelklabo** [comment]
Hi @KrauseFx I am having some trouble getting the tests to run. I created an issued: https://github.com/fastlane/fastlane/issues/9177 

Do you know where I can get some help with getting them running?

**Comment by hjanuschka** [comment]
https://github.com/fastlane/fastlane/pull/9188 has been merged, should ship with the next release 🚀  many thx @joelklabo

**Comment by joelklabo** [comment]
Thanks to you all! Glad I could add a little piece 👏

**Comment by rsaunders100** [comment]
Hey - Apologies for the noobie question... how do you actually use this feature from the command line?

Is it 
`fastlane pilot resend_invite`
