### ISSUE TITLE
Provisioning profile "match AppStore com.MyCompany.MyApp-test 1492764177" doesn't include signing certificate "iPhone Developer: Bob Trotter (JM345FJUTSB)"

### ISSUE THREAD

**Issue by kekearif** [fastlane/fastlane#8972]
### New Issue Checklist

- [✅ ] Updated fastlane to the latest version
- [✅ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hey, I seem to be having issues with `fastlane match`. I am currently running the command `fastlane beta`:

```
desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(scheme: "MyApp UAT") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
```
My match file contains this:
```

git_url "https://github.com/MyApp/ios-certificates.git"
type "appstore" # The default type, can be: appstore, adhoc, enterprise or development
username "MyApp.ios@gmail.com"
app_identifier "com.MyCompany.MyApp-test"
```

My Appfile contains:

```
app_identifier "com.MyCompany.MyApp-test" # The bundle identifier of your app
apple_id "MyApp.ios@gmail.com" # Your Apple email address
team_id "********" # Developer Portal Team ID
```

I end with the error

>  Provisioning profile "match AppStore com.MyCompany.MyApp-test 1492764177" doesn't include signing certificate "iPhone Developer: Bob Trotter (JM345FJUTSB)".

Oddly enough if I run match match(type: "development") there are no code signing issues and it seems to be using the correct certificates, obviously I can't distribute to the App Store for test flight with this tho 😛 . Any ideas what I am doing wrong here?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/latest.zip
[16:54:44]: -------------------------------------------------
[16:54:44]: --- Step: Verifying required fastlane version ---
[16:54:44]: -------------------------------------------------
[16:54:44]: Your fastlane version 2.28.3 matches the minimum requirement of 2.27.0  ✅
[16:54:44]: ------------------------------
[16:54:44]: --- Step: default_platform ---
[16:54:44]: ------------------------------
[16:54:44]: Driving the lane 'ios beta' 🚀
[16:54:44]: ------------------------------
[16:54:44]: --- Step: register_devices ---
[16:54:44]: ------------------------------
[16:54:48]: Successfully registered new devices.
[16:54:48]: -----------------------
[16:54:48]: --- Step: cocoapods ---
[16:54:48]: -----------------------
[16:54:48]: $ pod install
[16:54:59]: ▸ Analyzing dependencies
[16:54:59]: ▸ Downloading dependencies
[16:54:59]: ▸ Using AMPopTip (1.4.1)
[16:54:59]: ▸ Using Alamofire (4.3.0)
.............................
[16:55:23]: ▸ Sending stats
[16:55:23]: ▸ Pod installation complete! There are 36 dependencies from the Podfile and 45 total pods installed.

[16:55:23]: -------------------
[16:55:23]: --- Step: match ---
[16:55:23]: -------------------
[16:55:23]: Successfully loaded '/Users/kekearif/Documents/MyApp/ios-app/fastlane/Matchfile' 📄

+----------------------+--------------------------------------+
|         Detected Values from './fastlane/Matchfile'         |
+----------------------+--------------------------------------+
| git_url              | https://github.com/MyApp/i  |
|                      | os-certificates.git                  |
| username             | MyApp.ios@gmail.com                |
| app_identifier       | com.MyCompany.MyApp-test              |
+----------------------+--------------------------------------+

+-----------------------+--------------------------------------+
|                   Summary for match 2.28.3                   |
+-----------------------+--------------------------------------+
| type                  | appstore                             |
| git_url               | https://github.com/MyApp/i  |
|                       | os-certificates.git                  |
| username              | MyApp.ios@gmail.com                |
| app_identifier        | com.MyCompany.MyApp-test              |
| git_branch            | master                               |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| team_id               | 47Y3VGLMTK                           |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

[16:55:23]: Cloning remote git repo...
[16:55:29]: 🔓  Successfully decrypted certificates repo
[16:55:29]: Verifying that the certificate and profile are still valid on the Dev Portal...
[16:55:32]: Installing certificate...

+-------------------+----------------------------------------------------------+
|                            Installed Certificate                             |
+-------------------+----------------------------------------------------------+
| User ID           | 47Y3VGLMTK                                               |
| Common Name       | iPhone Distribution: MyCompany Holding Limited (34543DWER) |
| Organisation Unit | 34543DWER                                               |
| Organisation      | MyCompany Holding Limited                                   |
| Country           | US                                                       |
| Start Datetime    | Apr 21 08:32:46 2017 GMT                                 |
| End Datetime      | Apr 21 08:32:46 2018 GMT                                 |
+-------------------+----------------------------------------------------------+

[16:55:34]: Installing provisioning profile...

+---------------------+------------------------+------------------------+
|                    Installed Provisioning Profile                     |
+---------------------+------------------------+------------------------+
| Parameter           | Environment Variable   | Value                  |
+---------------------+------------------------+------------------------+
| App Identifier      |                        | com.MyCompany.MyApp-te  |
|                     |                        | st                     |
| Type                |                        | appstore               |
| Platform            |                        | ios                    |
| Profile UUID        | sigh_com.MyCompany.MyApp  | 3f383bb2-b3ff-4813-8d  |
|                     | -test_appstore       | fb-9fb1ec75acb1        |
| Profile Name        | sigh_com.MyCompany.MyApp  | match AppStore         |
|                     | test_appstore_prof  | com.MyCompany.MyApp-te  |
|                     | ile-name               | st 1492764177          |
| Profile Path        | sigh_com.MyCompany.MyApp  | /Users/kekearif/Libra  |
|                     | test_appstore_prof  | ry/MobileDevice/Provi  |
|                     | ile-path               | sioning                |
|                     |                        | Profiles/3f383bb2-b3f  |
|                     |                        | f-4813-8dfb-9fb1ec75a  |
|                     |                        | cb1.mobileprovision    |
| Development Team ID | sigh_com.MyCompany.MyApp  | 47Y3VGLMTK             |
|                     | test_appstore_team  |                        |
|                     | -id                    |                        |
+---------------------+------------------------+------------------------+

[16:55:35]: All required keys, certificates and provisioning profiles are installed 🙌
[16:55:35]: Setting Provisioning Profile type to 'app-store'
[16:55:35]: -----------------
[16:55:35]: --- Step: gym ---
[16:55:35]: -----------------
[16:55:35]: $ xcodebuild -list -workspace ./MyApp.xcworkspace
[16:55:37]: $ xcodebuild clean -showBuildSettings -workspace ./MyApp.xcworkspace -scheme MyApp\ UAT

+----------------------+--------------------------------------+
|                   Summary for gym 2.28.3                    |
+----------------------+--------------------------------------+
| scheme               | MyApp UAT                          |
| export_method        | app-store                            |
| workspace            | ./MyApp.xcworkspace                |
| destination          | generic/platform=iOS                 |
| output_name          | MyApp                              |
| build_path           | /Users/kekearif/Library/Developer/X  |
|                      | code/Archives/2017-04-23             |
| clean                | false                                |
| output_directory     | .                                    |
| silent               | false                                |
| skip_package_ipa     | false                                |
| use_legacy_build_api | false                                |
| buildlog_path        | ~/Library/Logs/gym                   |
| xcode_path           | /Applications/Xcode.app              |
+----------------------+--------------------------------------+

[16:55:39]: $ set -o pipefail && xcodebuild -workspace ./MyApp.xcworkspace -scheme MyApp\ UAT -destination 'generic/platform=iOS' -archivePath /Users/kekearif/Library/Developer/Xcode/Archives/2017-04-23/MyApp\ 2017-04-23\ 16.55.39.xcarchive archive | tee /Users/kekearif/Library/Logs/gym/MyApp-MyApp\ UAT.log | xcpretty
[16:55:44]: ▸ Building Pods/AMPopTip [Release]
[16:55:44]: ▸ Check Dependencies
[16:55:44]: ▸ Processing Info.plist
[16:56:40]: ▸ Compiling AMPopTip+Animation.m
[16:56:41]: ▸ Compiling AMPopTip+Draw.m
[16:56:41]: ▸ Compiling AMPopTip+Entrance.m
[16:56:41]: ▸ Compiling AMPopTip+Exit.m
[16:56:41]: ▸ Compiling AMPopTip-dummy.m
[16:56:41]: ▸ Compiling AMPopTip.m
[16:56:42]: ▸ Compiling AMPopTip_vers.c
[16:56:42]: ▸ Compiling AMPopTip+Animation.m
[16:56:42]: ▸ Compiling AMPopTip+Draw.m
[16:56:42]: ▸ Compiling AMPopTip+Entrance.m
[16:56:42]: ▸ Compiling AMPopTip+Exit.m
[16:56:43]: ▸ Compiling AMPopTip-dummy.m
[16:56:43]: ▸ Compiling AMPopTip.m
..................................................
▸ Building MyApp/Myapp UAT [Release]
▸ Check Dependencies

❌  Provisioning profile "match AppStore com.MyCompany.MyApp-test 1492764177" doesn't include signing certificate "iPhone Developer: Bob Trotter (JM345FJUTSB)".

❌  Code signing is required for product type 'Application' in SDK 'iOS 10.2']

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.1 (16B2657)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.27.0"

default_platform :ios

platform :ios do
  before_all do
    register_devices(devices: {
      "Keke's iPhone" => "6e5cf429c3d7e150f64ef273aac2b17ee5c7c891"
    })
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods

  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")
    gym(scheme: "Snapask UAT") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Snapask UAT") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# This is configured for appstore and devlopment on test bundle now (UAT)
app_identifier "com.appedu.snapask-test" # The bundle identifier of your app
apple_id "snapask.ios@gmail.com" # Your Apple email address
team_id "47Y3VGLMTK" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem                 | Version | Update-Status      |
| ------------------- | ------- | ------------------ |
| cert                | 2.0.0   | ✅ Up-To-Date       |
| credentials_manager | 1.0.0   | ✅ Up-To-Date       |
| deliver             | 2.0.1   | ✅ Up-To-Date       |
| fastlane            | 2.28.3  | ✅ Up-To-Date       |
| fastlane_core       | 1.0.0   | ✅ Up-To-Date       |
| frameit             | 4.0.0   | ✅ Up-To-Date       |
| gym                 | 2.0.0   | ✅ Up-To-Date       |
| match               | 1.0.0   | ✅ Up-To-Date       |
| pem                 | 2.0.0   | ✅ Up-To-Date       |
| pilot               | 2.0.0   | ✅ Up-To-Date       |
| produce             | 2.0.0   | ✅ Up-To-Date       |
| scan                | 1.0.0   | ✅ Up-To-Date       |
| screengrab          | 1.0.0   | ✅ Up-To-Date       |
| sigh                | 2.0.1   | ✅ Up-To-Date       |
| snapshot            | 2.0.0   | ✅ Up-To-Date       |
| spaceship           | 1.0.0   | ✅ Up-To-Date       |
| spaceship           | 0.38.4  | 🚫 Update available |
| supply              | 1.0.0   | ✅ Up-To-Date       |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.4        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.13.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.1.1        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.2        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.1        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander                 | 4.4.0        |
| commander-fastlane        | 4.4.4        |
| concurrent-ruby           | 1.0.2        |
| credentials_manager       | 1.0.0        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.1.1        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.10.1       |
| fastimage                 | 1.6.8        |
| fastlane_core             | 1.0.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.2        |
| google-api-client         | 0.9.20       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.2.4      |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| krausefx-shenzhen         | 0.14.11      |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.4        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.5.5        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| net-sftp                  | 2.1.2        |
| net-ssh                   | 3.2.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.4        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.12       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.1        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.0.9        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-04-23**
</details>]

**Comment by thebugcode** [comment]
This is a code signing issue.  Your developer certificate is not included in the provisioning profile.

If you're trying to create an ipa for the appstore, then you need the distribution certificate in your keychain.

**Comment by melbic** [comment]
I have the same problem, with the development certificate though. Should match add the certificate to the keychain?
