### ISSUE TITLE
Could not find proper version of fastlane (2.28.3) in any of the sources

### ISSUE THREAD

**Issue by lailibo8** [fastlane/fastlane#8975]
Could not find proper version of fastlane (2.28.3) in any of the sources
Run `bundle install` to install missing gems.

**Comment by ohayon** [comment]
Hey @lailibo8, I'm not sure I understand this issue. Could you provide a bit more information about when you are seeing a problem and what it is?

**Comment by KrauseFx** [comment]
At the top of your `Gemfile`, you can add

```ruby
source "https://rubygems.org"
```

from our [Getting started guide](https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile)
