### ISSUE TITLE
Hook each steps on deliver

### ISSUE THREAD

**Issue by giginet** [fastlane/fastlane#8977]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Motivation

I want to notify to Slack when deliver executes each steps. (Starting uploading Binary, Starting Processing, Updated Processing state, etc...)

### Solution

How about this interface?

```ruby
deliver(callback: lambda { |event, args|
  case event
  when :start_uploading_binary:
    slack(message: "Starting Uploading binary")
  when :start_processing:
    slack(message: "Starting Processing...")
  when :updated_processing:
    slack(message: "You can tweet: "iTunes Connect #iosprocessingtime args[:minute] minutes")
})
```

**Comment by KrauseFx** [comment]
This sounds a lot like github.com/krausefx/fastlane-plugin-slack_train, hehe 😃 

The thing you proposed might be more complicated than it looks like, as deliver has its own options. I don't think it's a good idea.

**Comment by giginet** [comment]
I'm considering the interface. 🤔 
I wish to use `slack_train` on `deliver`.

Does anyone have another idea?

**Comment by hjanuschka** [comment]
i like the core idea of, however i also think it makes the interface too complicated for users.
i had a similar need of this, and i thought maybe doing it with a bit extended plugin interface.


like doing (of course not only in deliver):

```ruby
FastlaneCore::Plugin::dispatch_event(:deliver_binary_upload_started, nil);
....
FastlaneCore::Plugin::dispatch_event(:start_processing, build);
.....
FastlaneCore::Plugin::dispatch_event(:done_processing, {build: build, minute: minute});
```


the `dispatch_event` might look something like:

```ruby
def dispatch_event(event, payload)
   ALL_PLUGINS.each do | plugin | # dummy - not sure how to get all plugins
    plugin.dispatch_event(payload)
  en
end
```


in the plugin it can look like (e.g in an action - which only servers as a event receiver):

```ruby
def dispatch_event(evnt, payload)
  case evnt
  when :deliver_binary_upload_started
       puts "WOOPS"
  end
end
```

**Comment by hjanuschka** [comment]
PR: https://github.com/fastlane/fastlane/pull/9000
