### ISSUE TITLE
How to download all provisioning profiles?

### ISSUE THREAD

**Issue by tonyxiao** [fastlane/fastlane#898]
The `sigh` action doesn't seem to expose an option to download all.

**Comment by mRs-** [comment]
From the documentation site of **sigh** https://github.com/fastlane/sigh

To download all your provisioning profiles use
```
sigh download_all 
```

**Comment by tonyxiao** [comment]
@mRs- I was referring to the `sigh` action https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/sigh.rb, not the `sigh` tool.

**Comment by KrauseFx** [comment]
Just add this to your `Fastfile`
```ruby
sh "sigh download_all`
```
:rocket:
