### ISSUE TITLE
fastlane command not found

### ISSUE THREAD

**Issue by taglia3** [fastlane/fastlane#8981]
### New Issue Checklist

- [v] Updated fastlane to the latest version
- [v] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm unable to use Fastlane, after I've installed it using brew cask uninstall fastlane I get always: -bash: fastlane: command not found

I've tried to run the command export PATH="$HOME/.fastlane/bin:$PATH" but it's the same.

##### Complete output when installing Fastlane
```
Administrators-MacBook-Pro:~ xxx $ brew cask install fastlane
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/bundle-1.8.zip
Already downloaded: /Users/xxx/Library/Caches/Homebrew/Cask/fastlane--1.8.zip
==> Verifying checksum for Cask fastlane
==> Running installer script /usr/local/Caskroom/fastlane/1.8/install
==> 
==> Installing fastlane to /Users/xxx/.fastlane/bin... this might take a few seconds
==> 
==> 
==> Successfully copied fastlane to /Users/xxx/.fastlane/bin
==> 
==> 
==> Updating installed gems
==> Nothing to update
==> Cleaning up installed gems...
==> Clean Up Complete
==> 
==> Couldn't detect shell config file (bash - ~/.bash_profile)
==> Please add the following line to your bash profile:
==> 
==> export PATH="$HOME/.fastlane/bin:$PATH"
==> 
==> After doing so close the terminal session and restart it to start using fastlane 🚀
==> 
🍺  fastlane was successfully installed!
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

Administrators-MacBook-Pro:~ xxx$ fastlane env
-bash: fastlane: command not found

**Comment by ohayon** [comment]
Hey @taglia3, it looks like the _fastlane_ binary needs to be added to your `PATH`. Could you share the output of `echo $PATH` with us? Also, do you have a `~/.bash_profile` and/or a `~/.bashrc` file on your machine? Thanks! 🐙

**Comment by mhamel06** [comment]
Not sure if something changed with the install but I had to modify the path export to this export PATH="$HOME/.fastlane/bin/fastlane_lib:$PATH" since all the executables are actually in fastlane_lib

**Comment by ohayon** [comment]
Hey @mhamel06 that is definitely strange, could you share the output of `ls -l ~/.fastlane/bin`?

**Comment by mhamel06** [comment]
```sh
ls ~/.fastlane/bin 
# fastlane_lib
ls ~/.fastlane/bin/fastlane_lib/
# NOTICE.txt                cert          gym           scan
# THIRDPARTYLICENSES.txt    deliver       match         sigh
# VERSION                   dependencies  parse_env.rb  snapshot
# bundle                    fastlane      pem
# bundle_update_checker.rb  frameit       produce
```

**Comment by ohayon** [comment]
Thanks @mhamel06 that is for sure a bit weird. Did you install _fastlane_ via homebrew?

**Comment by mhamel06** [comment]
No problem. Yeah, just tried via homebrew today and noticed the bin files weren't where I expected them to be.

**Comment by ohayon** [comment]
Would you mind for the sake of testing, to just `rm -rf ~/.fastlane` and then run `brew cask reinstall fastlane` and see if the same thing happens?

**Comment by mhamel06** [comment]
Same result.

**Comment by mhamel06** [comment]
yeah no problems after adding that dir. I think this change to the install script would fix the issue:
https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/fastlane.zip
```
# Copy fastlane to ~/.fastlane
echoc "Installing fastlane to $FASTLANE_DIR... this might take a few seconds" yellow
mkdir -p $FASTLANE_DIR
# We have to skip the 2 error messages below, which are shown if a previous version of fastlane
# was installed via the bundle
cp -R "$CURRENT_DIR/fastlane_lib/" $FASTLANE_DIR
cp "$CURRENT_DIR/NOTICE.txt" "$FASTLANE_DIR/.."
cp "$CURRENT_DIR/THIRDPARTYLICENSES.txt" "$FASTLANE_DIR/.."

echoc "Successfully copied fastlane to $FASTLANE_DIR" green
echo ""
```
From 
```
cp -R "$CURRENT_DIR/fastlane_lib/" $FASTLANE_DIR
```
To
```
cp -R "$CURRENT_DIR/fastlane_lib/." $FASTLANE_DIR
```

**Comment by ohayon** [comment]
Yeah, thats great. We will definitely fix this. Might require some more testing because I am not able to reproduce it on my machine it ends up in `~/.fastlane/bin/`. Thank you so much for the report and solution. We will take care of this soon! 🚀

**Comment by mhamel06** [comment]
Sounds good. I'm running macOS 10.12.4 in case it is a version specific bug.

**Comment by JoakimLiu** [comment]
@taglia3 I met the same situation as you. I created `.bash_profile` file, then run `uninstall` script, finally, run `install` script, successfully!
