### ISSUE TITLE
frameit: multiple line titles not working

### ISSUE THREAD

**Issue by Danbana** [fastlane/fastlane#8986]
I'm running the latest everything, using a strings file

**Comment by Danbana** [comment]
Actually it's only when the number of lines is 3. For 2 lines, it looks decent

**Comment by Danbana** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |


### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| slack-notifier            | 1.5.1   |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| colored2                  | 3.1.2   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.4   |
| rouge                     | 1.10.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.6.3   |
| terminal-table            | 1.4.5   |
| plist                     | 3.1.0   |
| addressable               | 2.3.8   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| tty-screen                | 0.5.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| highline                  | 1.7.8   |
| commander-fastlane        | 4.4.4   |
| excon                     | 0.45.4  |
| faraday                   | 0.9.2   |
| unf_ext                   | 0.0.6   |
| unf                       | 0.1.4   |
| domain_name               | 0.5.18  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| retriable                 | 2.1.0   |
| mime-types                | 2.3     |
| hurley                    | 0.2     |
| little-plugger            | 1.1.4   |
| multi_json                | 1.11.2  |
| logging                   | 2.0.0   |
| jwt                       | 1.5.2   |
| memoist                   | 0.14.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.2   |
| googleauth                | 0.5.1   |
| thor                      | 0.19.1  |
| httpclient                | 2.8.0   |
| google-api-client         | 0.9.9   |
| mini_magick               | 4.5.1   |
| multi_xml                 | 0.5.5   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.2.0   |
| bundler                   | 1.12.5  |
| faraday_middleware        | 0.10.0  |
| json                      | 1.8.1   |
</details>


*generated on:* **2017-04-24**
</details>

**Comment by Danbana** [comment]
2 only looked decent because I had sufficient padding

**Comment by Danbana** [comment]
I'd love to work on the gem, but am not sure how.
gem unpack frameit
edit that code
then how do i get it to build?

**Comment by asfalcone** [comment]
@Danbana please take a look at https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md and https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md Thanks
