### ISSUE TITLE
Which tool can i use to manage devices?

### ISSUE THREAD

**Issue by purplepeng** [fastlane/fastlane#8987]
Which tool can i use to manage devices? Thank you.

**Comment by purplepeng** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3                                                            |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.110.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Build to Fir.im"
  lane :fir do
  # snapshot
    # sigh
    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    gym(scheme: "parkviewgreen",use_legacy_build_api: true)

    # 运行自定义脚本
    sh "../fir.sh"

  end

  desc "Submit a new Build to pgyer"
  lane :pgyer do
  # snapshot
    # sigh
    # use the UDID of the newly created provisioning profile
    ENV["PROFILE_UDID"] = lane_context[SharedValues::SIGH_UDID]
    gym(scheme: "parkviewgreen",use_legacy_build_api: true)

    # 运行自定义脚本
    sh "../pgyer.sh"

  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    sigh
    gym(scheme: "parkviewgreen") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "parkviewgreen") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.parkviewgreen.PVG" # The bundle identifier of your app
apple_id "mkt.public@parkviewgreen.com" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.3  | 💥 Check failed |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version |
| ------------------------- | ------- |
| slack-notifier            | 1.4.0   |
| CFPropertyList            | 2.3.3   |
| claide                    | 1.0.1   |
| colored2                  | 3.1.2   |
| nanaimo                   | 0.2.3   |
| xcodeproj                 | 1.4.4   |
| rouge                     | 1.10.1  |
| xcpretty                  | 0.2.4   |
| terminal-notifier         | 1.6.3   |
| terminal-table            | 1.4.5   |
| plist                     | 3.1.0   |
| addressable               | 2.3.8   |
| multipart-post            | 2.0.0   |
| word_wrap                 | 1.0.0   |
| tty-screen                | 0.5.0   |
| babosa                    | 1.0.2   |
| colored                   | 1.2     |
| commander-fastlane        | 4.4.4   |
| excon                     | 0.45.4  |
| unf_ext                   | 0.0.7.1 |
| unf                       | 0.1.4   |
| domain_name               | 0.5.24  |
| http-cookie               | 1.0.2   |
| faraday-cookie_jar        | 0.0.6   |
| fastimage                 | 1.6.8   |
| gh_inspector              | 1.0.2   |
| uber                      | 0.0.15  |
| representable             | 2.3.0   |
| multi_json                | 1.11.2  |
| retriable                 | 2.1.0   |
| hurley                    | 0.2     |
| faraday                   | 0.9.1   |
| little-plugger            | 1.1.4   |
| logging                   | 2.0.0   |
| jwt                       | 1.5.2   |
| memoist                   | 0.12.0  |
| os                        | 0.9.6   |
| signet                    | 0.7.0   |
| googleauth                | 0.5.1   |
| thor                      | 0.19.1  |
| google-api-client         | 0.9.2   |
| mini_magick               | 4.5.1   |
| multi_xml                 | 0.5.5   |
| rubyzip                   | 1.1.7   |
| security                  | 0.1.3   |
| xcpretty-travis-formatter | 0.0.4   |
| dotenv                    | 2.1.1   |
| bundler                   | 1.12.5  |
| faraday_middleware        | 0.10.0  |
| json                      | 1.8.3   |
| highline                  | 1.7.8   |
</details>


*generated on:* **2017-04-25**
</details>

**Comment by purplepeng** [comment]
Thanks, I just want to add other device's uuid into the certificates, and then update the profile.

**Comment by thebugcode** [comment]
If on iOS, there is no way right now to list connected device. I use `instruments -s` and scan used to used to do this https://github.com/fastlane/fastlane/issues/8782 to list devices
