### ISSUE TITLE
snapshot reset_simulators (domain=com.apple.CoreSimulator.SimError, code=161): Incompatible device

### ISSUE THREAD

**Issue by wrutkowski** [fastlane/fastlane#8992]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When running `fastlane snapshot reset_simulators --ios_version 9.3,10.2 --force` on some of the build machines I'm getting error:

```
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
```

##### Complete output when running fastlane, including the stack trace and command used

```
Mac:~ mac$ fastlane snapshot reset_simulators --ios_version 9.3,10.2 --force
Removing device iPhone 4s (817FF9E9-3A9B-40EA-81F3-4ECC7830A1AF)
Removing device iPhone 5 (2FDB434A-D1B4-4B20-BCE7-900A124862D8)
Removing device iPhone 5s (151E56F3-492D-42CE-942F-CFCB406CFE1A)
Removing device iPhone 6 (BC0E3082-C5B5-451E-865B-1A7F117B4732)
Removing device iPhone 6 Plus (1D861D8B-78DE-4AC4-9F18-4ACF5CC379C2)
Removing device iPhone 6s (921EAEAB-CDD7-4AFD-8425-BE75E8601F3D)
Removing device iPhone 6s Plus (A31A1B20-46C0-47FF-8B22-969C4A459361)
Removing device iPhone SE (8E01C67A-454D-4A2D-A3B6-308B94BADB1E)
Removing device iPad 2 (9FD9C4D5-5815-42BD-802B-4AF082334B1C)
Removing device iPad Retina (0D1A077C-9A6A-4CFC-9FA6-015D345C93A9)
Removing device iPad Air (0E93ABBE-3D79-48CD-BBA5-9D4B4102DF86)
Removing device iPad Air 2 (0A6B9849-8996-414B-87EC-CC62308B157A)
Removing device iPad Pro (12.9-inch) (B51180C7-76B7-4641-AAB1-C7813CC6AF0D)
Removing device iPhone 5 (66C0C707-B444-4DB8-85D3-ABEBB3F0BC36)
Removing device iPhone 5s (D1DBC803-0791-4B40-BC84-8B0A9498CEC1)
Removing device iPhone 6 (F0A5DCB3-F2EC-4430-B3FE-45AA46F319F0)
Removing device iPhone 6 Plus (F4F5346A-DC73-4182-9B02-E7C5978EE7B7)
Removing device iPhone 6s (71E3F5CC-FD35-477E-B372-4E0860F1AB72)
Removing device iPhone 6s Plus (4C6E712C-3445-492C-B8F1-C1CBE57F67CD)
Removing device iPhone 7 (8318A06E-73EE-4942-BB1F-4D1708C8A802)
Removing device iPhone 7 Plus (BF9F08BF-9CF4-4F76-9FC9-52F2632FD3F8)
Removing device iPhone SE (140FFBEE-15F6-4797-A37D-685E2191779B)
Removing device iPad Retina (40874BE3-8DF1-41B9-A2B2-91902B81C56C)
Removing device iPad Air (49981350-9FA5-494F-8C38-50BC77B679B1)
Removing device iPad Air 2 (81CA9C58-3663-4144-B59B-76E239D7A02E)
Removing device iPad Pro (9.7-inch) (8CA225A1-65D2-401C-A574-85E9F4AC9D4E)
Removing device iPad Pro (12.9-inch) (1EBC6186-12CA-43CF-AE65-55E8994CC7EC)
Removing device Apple TV 1080p (5FCDF4BB-E4D7-4F79-872D-61138C7E29C7)
Removing device Apple Watch - 38mm (813C3EAD-96CC-4FFE-A3F5-7780A142FF5B)
Removing device Apple Watch - 42mm (DEDF3F04-23FD-4830-8714-DAE4073B9920)
Removing device Apple Watch Series 2 - 38mm (06354ABB-0F0D-45A9-BA78-E5292C17E2AD)
Removing device Apple Watch Series 2 - 42mm (056785C7-1351-4A43-AB20-349C4A8443D6)
Creating iPhone 4s for iOS version iOS 9.3
Creating iPhone 4s for iOS version iOS 10.2
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPhone 5 for iOS version iOS 9.3
Creating iPhone 5 for iOS version iOS 10.2
Creating iPhone 5s for iOS version iOS 9.3
Creating iPhone 5s for iOS version iOS 10.2
Creating iPhone 6 for iOS version iOS 9.3
Creating iPhone 6 for iOS version iOS 10.2
Creating iPhone 6 Plus for iOS version iOS 9.3
Creating iPhone 6 Plus for iOS version iOS 10.2
Creating iPhone 6s for iOS version iOS 9.3
Creating iPhone 6s for iOS version iOS 10.2
Creating iPhone 6s Plus for iOS version iOS 9.3
Creating iPhone 6s Plus for iOS version iOS 10.2
Creating iPhone 7 for iOS version iOS 9.3
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPhone 7 for iOS version iOS 10.2
Creating iPhone 7 Plus for iOS version iOS 9.3
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPhone 7 Plus for iOS version iOS 10.2
Creating iPhone SE for iOS version iOS 9.3
Creating iPhone SE for iOS version iOS 10.2
Creating iPad 2 for iOS version iOS 9.3
Creating iPad 2 for iOS version iOS 10.2
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPad Retina for iOS version iOS 9.3
Creating iPad Retina for iOS version iOS 10.2
Creating iPad Air for iOS version iOS 9.3
Creating iPad Air for iOS version iOS 10.2
Creating iPad Air 2 for iOS version iOS 9.3
Creating iPad Air 2 for iOS version iOS 10.2
Creating iPad Pro (9.7-inch) for iOS version iOS 9.3
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPad Pro (9.7-inch) for iOS version iOS 10.2
Creating iPad Pro (12.9-inch) for iOS version iOS 9.3
Creating iPad Pro (12.9-inch) for iOS version iOS 10.2
Creating Apple TV 1080p for tvOS version tvOS 10.1
Creating Apple Watch - 38mm for watchOS version watchOS 3.1
Creating Apple Watch - 42mm for watchOS version watchOS 3.1
Creating Apple Watch Series 2 - 38mm for watchOS version watchOS 3.1
Creating Apple Watch Series 2 - 42mm for watchOS version watchOS 3.1
Creating device pair of 95E3D217-665F-403D-B94F-EA8FAD5AE76A and 23728155-60EC-479F-A8DA-611D1CABAEA7
```

### Environment

Result of running `xcrun simctl list`:

```
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
Apple TV 1080p (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
== Runtimes ==
iOS 8.1 (8.1 - 12B411) (com.apple.CoreSimulator.SimRuntime.iOS-8-1)
iOS 9.3 (9.3 - 13E233) (com.apple.CoreSimulator.SimRuntime.iOS-9-3)
iOS 10.2 (10.2 - 14C89) (com.apple.CoreSimulator.SimRuntime.iOS-10-2)
tvOS 10.1 (10.1 - 14U591) (com.apple.CoreSimulator.SimRuntime.tvOS-10-1)
watchOS 3.1 (3.1 - 14S471a) (com.apple.CoreSimulator.SimRuntime.watchOS-3-1)
== Devices ==
-- iOS 8.1 --
-- iOS 9.3 --
    iPhone 4s (F06401D7-58B0-4173-94AC-578DF1F21197) (Shutdown)
    iPhone 5 (AF8850A9-A09C-4065-BD86-3B5DC3CA39BA) (Shutdown)
    iPhone 5s (1A5B8327-8965-4ABA-91C7-906F5AC3E503) (Shutdown)
    iPhone 6 (DC2981E8-1C80-428B-B20C-8B8067329A57) (Shutdown)
    iPhone 6 Plus (F6533239-9EEB-4F37-9829-C8765594F034) (Shutdown)
    iPhone 6s (ABAA192C-CE9D-41C0-8896-6197DFA707AB) (Shutdown)
    iPhone 6s Plus (95622B27-C1F5-4565-A31C-EE253BCD2032) (Shutdown)
    iPhone SE (D65D85BE-2B61-4E97-8B9E-9556CD742CAD) (Shutdown)
    iPad 2 (FF2C45E5-6A8E-48EF-80C8-79BCDE1CE765) (Shutdown)
    iPad Retina (E11E25A2-DBDF-40EA-A2CF-66E599F0416E) (Shutdown)
    iPad Air (2DE3FA03-C8F3-485D-B1F3-DE01BF164AE4) (Shutdown)
    iPad Air 2 (14570657-6236-44B8-972A-494F7CC4BE06) (Shutdown)
    iPad Pro (12.9-inch) (797772FF-D7EC-4525-97A5-697799D39A87) (Shutdown)
-- iOS 10.2 --
    iPhone 5 (2A791831-2A36-4376-B223-403C586DE877) (Shutdown)
    iPhone 5s (BE5E4081-3F8B-45ED-8064-5748693009BE) (Shutdown)
    iPhone 6 (8387EC5E-CE18-41A7-BE48-73EA382BBE68) (Shutdown)
    iPhone 6 Plus (1609E033-5E28-42DD-A35E-9EC3AC60F92A) (Shutdown)
    iPhone 6s (19B501F3-21D2-4CDF-A717-417CBAE02846) (Shutdown)
    iPhone 6s Plus (95E3D217-665F-403D-B94F-EA8FAD5AE76A) (Shutdown)
    iPhone 7 (0452DE45-68FF-4894-9F80-0D65D1AD86AD) (Booted)
    iPhone 7 Plus (27BF1341-B96E-41AC-9657-17A7202A559C) (Shutdown)
    iPhone SE (C8BCB3B3-B391-4514-AB9A-389BC2979AC5) (Shutdown)
    iPad Retina (08B66C1E-ADAA-40BF-9E42-AA8FC9733D1B) (Shutdown)
    iPad Air (0CABF500-CDB8-42DD-98E1-F5C03E1A577B) (Shutdown)
    iPad Air 2 (33DEB086-4931-4CEA-802C-D9F46BF4336C) (Shutdown)
    iPad Pro (9.7-inch) (4C3282DD-936F-48DE-A3B0-EABD186FA4C2) (Shutdown)
    iPad Pro (12.9-inch) (DA168506-34B2-4A96-805C-278558E3A9E2) (Shutdown)
-- tvOS 10.1 --
    Apple TV 1080p (7A962B1B-5AED-4166-AD5B-15AC7ABDF6A9) (Shutdown)
-- watchOS 3.1 --
    Apple Watch - 38mm (80CEC5AD-A4B9-4361-BF1D-71424F9040CA) (Shutdown)
    Apple Watch - 42mm (BA2236E0-94DC-4C2B-8A3E-5CA7CB8EBBC6) (Shutdown)
    Apple Watch Series 2 - 38mm (8646A29A-F6D7-450A-B2F3-0393EE02E422) (Shutdown)
    Apple Watch Series 2 - 42mm (23728155-60EC-479F-A8DA-611D1CABAEA7) (Shutdown)
== Device Pairs ==
5ABF0EE8-7F02-4D3B-A3EC-4D53F41FD4B1 (active, disconnected)
    Watch: Apple Watch Series 2 - 38mm (8646A29A-F6D7-450A-B2F3-0393EE02E422) (Shutdown)
    Phone: iPhone 7 (0452DE45-68FF-4894-9F80-0D65D1AD86AD) (Booted)
ADE9A265-D65A-4B07-8C2B-FE5A66CBDD2E (active, disconnected)
    Watch: Apple Watch Series 2 - 42mm (23728155-60EC-479F-A8DA-611D1CABAEA7) (Shutdown)
    Phone: iPhone 7 Plus (27BF1341-B96E-41AC-9657-17A7202A559C) (Shutdown)
```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.3                                         |
| Ruby                        | 2.4.1                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.10.1 (Apple Git-78)               |
| Installation Source         | /usr/local/bin/fastlane                         |
| Host                        | Mac OS X 10.12.3 (16D32)                        |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib              |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-8.2.app/Contents/Developer/ |
| Xcode Version               | 8.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.3  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-04-25**
</details>

**Comment by tupans** [comment]
what do i do?

**Comment by taquitos** [comment]
Is this still happening with the most recent version of Xcode?

**Comment by wrutkowski** [comment]
I'll review CI logs on Monday and report back.

**Comment by wrutkowski** [comment]
I can confirm that the issue happened yesterday on Xcode 8.3.2. Our CI is using this version, I'll report back when I switch to Xcode 8.3.3.

**Comment by KrauseFx** [comment]
Alright, thanks, please keep us posted, and let us know if there is any action required from our side
