### ISSUE TITLE
pilot fails to add internal tester due to no "default external group"

### ISSUE THREAD

**Issue by cvermilion** [fastlane/fastlane#8999]
🔑 

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to add internal testers to an app that we are not externally testing yet, but getting an error about not having a "default external group". I'm not sure why this would be necessary to add an internal tester.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$> fastlane pilot add -e ben@figlyinc.com -u chris@figlyinc.com -a com.figlyinc.RadiatorMobile.remix.Jambalaya --distribute_external false --verbose
INFO [2017-04-25 16:17:58.25]: Login to iTunes Connect (chris@figlyinc.com)
Loading session from '/Users/verm/.fastlane/spaceship/chris@figlyinc.com/cookie'
Looking for iTunes Connect Team with ID 514710
INFO [2017-04-25 16:18:01.91]: Login successful
INFO [2017-04-25 16:18:02.71]: Existing tester ben@figlyinc.com
ERROR [2017-04-25 16:18:04.18]: Could not add ben@figlyinc.com to app: remix.remix.Jambalaya
ERROR [2017-04-25 16:18:04.18]: The app remix.remix.Jambalaya does not have a default external group. Please make sure to pass group names to the `:groups` option.
WARN [2017-04-25 16:18:04.18]: -------------
WARN [2017-04-25 16:18:04.18]: pilot crashed
WARN [2017-04-25 16:18:04.18]: -------------
ERROR [2017-04-25 16:18:04.18]: Unfortunately the TestFlight update from 11th April 2017 changed
ERROR [2017-04-25 16:18:04.18]: the way Testers, Groups, and Builds are managed on iTunesConnect.
ERROR [2017-04-25 16:18:04.18]: We have already fixed a number of features including submitting
ERROR [2017-04-25 16:18:04.18]: builds for testing, adding and removing testers from groups, and
ERROR [2017-04-25 16:18:04.18]: waiting for builds to process.
ERROR [2017-04-25 16:18:04.18]: 
ERROR [2017-04-25 16:18:04.18]: Please open an issue on https://github.com/fastlane/fastlane/issues
ERROR [2017-04-25 16:18:04.18]: if you believe this failure is the result of a bug in _pilot_ and we
ERROR [2017-04-25 16:18:04.18]: will be happy to look into this further.
ERROR [2017-04-25 16:18:04.18]: 
ERROR [2017-04-25 16:18:04.18]: Please stay tuned for more updates from _fastlane_ as we fix more issues!
ERROR [2017-04-25 16:18:04.18]: 
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/fastlane_core/lib/fastlane_core/ui/interface.rb:150:in `user_error!': [!] Some operations failed: The app remix.remix.Jambalaya does not have a default external group. Please make sure to pass group names to the `:groups` option. (FastlaneCore::Interface::FastlaneError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:95:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.4/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.4  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.2        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| plist                     | 3.2.0        |
</details>

*generated on:* **2017-04-25**
</details>

**Comment by mpirri** [comment]
Thanks for letting us know about this - it is likely this is related to the new TestFlight changes we just rolled out. We will dig into this further and let you know what we find!

**Comment by mpirri** [comment]
A quick question: have you ever had success with this before? The expected use case for `pilot` is to work with external testers, and I'm somewhat surprised this actually worked before with the "old" TestFlight, given the difference between internal and external testers (internal testers must have associated iTC accounts, for instance).

**Comment by cvermilion** [comment]
I think yes -- it took me a little CI spelunking because deploying new internal apps automatically (ie, apps that don't already have testers set up) is a feature we've been working on sporadically over the last month or so. I can see at least one successful run using v2.18.3, before the latest iTC changes, and oddly enough, at that point, I was creating the app with `produce`, adding testers, and _then_ uploading the IPA. In the attempt that failed here, I created, uploaded, and then tried to add testers.

I don't have access to the `fastlane env` from that run, but here's the output of the produce create step:

<details><summary>produce create output</summary>
+----------------+----------------------------------------+
|               Summary for produce 2.18.3                |
+----------------+----------------------------------------+
| username       | chris@figlyinc.com                     |
| app_identifier | com.figlyinc.RadiatorMobile.chris.test |
| app_name       | figly.chris.test                       |
| app_version    | 1.0                                    |
| sku            | chris.test                             |
| skip_devcenter | true                                   |
| platform       | ios                                    |
| language       | English                                |
| skip_itc       | false                                  |
+----------------+----------------------------------------+

[18:02:50]: Creating new app 'figly.chris.test' on iTunes Connect
[18:02:52]: Successfully created new app 'figly.chris.test' on iTunes Connect with ID 1223223206
1223223206

#######################################################################
# fastlane 2.25.0 is available. You are on 2.18.3.
# It is recommended to use the latest version.
# Please update using `sudo gem update fastlane`.
#######################################################################

2.25.0 Legacy build API & Xcode 8.3 messaging and other improvements
* pilot generates Ipa package in a random tmpdir (#8748) via Fred Cox
* Fix match typos (#8757) via color_box
* Add snapshot option to skip helper version check (#8751) via Helmut Januschka
* Update Your First PR instructions post monogem (#8754) via Andrea Falcone
* Pin the rubocop version to prevent reactive fixing (#8753) via Michael Furtak
* rubocop disable PercentLiteralDelimiters rule (#8752) via Helmut Januschka
* Add a tip about using QuickDemo for clean status bar (#8739) via Andrea Falcone
* Do not change or generate README.md after running rspec (#8629) via Fumiya Nakamura
* Use the new UI.test_failure! in screengrab (#8736) via Michael Furtak
* Add another ADB status phrase to reject (#8732) via Michael Furtak
* Add Gitlab 9.0+ ENV variable for branch detection. (#8707) via Peter Spiess-Knafl
* Fix pilot stuck waiting for multiple builds. Only wait for latest (current upload) (#8640) via Nicolás Gebauer
* Modernize action to action call to resolved configurations (#8719) via Todd Brannam
* Catch Xcode 8.3 legacy API while patching Xcode PackageApplication script (#8717) via Felix Krause
* Print information about dir handling in fastlane on error (#8694) via Felix Krause
* Show information about how to share schemes (#8714) via Felix Krause
* Add more tests for ConfigItem and clarify error message (#8711) via Felix Krause

2.24.0 Stability and documentation improvements and better React Native support
* Convince people to disable legacy build API (#8692) via Felix Krause

* Add custom error message when receive an internal server error (#8696) via Felix Krause

* change the zip output path from relative to absolute (#8637) via yukiasai

* Update fastlane tool collector to work with mono repo change (#8632) via Felix Krause

* Improve react-native onboarding (#8605) via Felix Krause

* Replace test failures with its own class to have more accurate crash metrics (#8631) via Felix Krause

* [match] Check push permission to git repository (#8643) via Econa77

* Add macOS support to snapshot (#8468) via David Ohayon

* Fix hardcoded fastlane paths (#8380) via Maksym Grebenets

* Fix crash in scan.rb - no implicit conversion of nil into Array (#8677) via battlmonstr

* Add documentation about the fastlane directory behavior (#8693) via Felix Krause

* Update update_checker to point to fastlane.tools domain (#8710) via Felix Krause

* And other documentation and test improvements



----



Unfortunately the legacy build API was removed with Xcode 8.3. Please make sure to remove `use_legacy_build_api` from your `./fastlane/Fastfile` and update the `gym` call to include the export method like this:



**App Store Builds**

```ruby

gym(scheme: "MyScheme", export_method: "app-store")

```



**Ad Hoc Builds**

```ruby

gym(scheme: "MyScheme", export_method: "ad-hoc")

```



**Development Builds**

```ruby

gym(scheme: "MyScheme", export_method: "development")

```



**In-House Enterprise Builds**

```ruby

gym(scheme: "MyScheme", export_method: "enterprise")

```



---



### What to do if you run into code signing errors?



If you run into a code signing error, please check out our [troubleshooting guide](https://docs.fastlane.tools/codesigning/troubleshooting/) and [common issue and how to solve them](https://docs.fastlane.tools/codesigning/common-issues/).



If that still doesn't help **please** [submit an issue](https://github.com/fastlane/fastlane/issues/new). Make sure to share your `fastlane env` output when doing so, and mention that you followed all steps in the linked docs.

2.23.0 General improvements
* Improve design of user input questions (#8606, #8607) via Felix Krause
* Fix edge case in `install_on_device` action (#8582) via Rafael Sachetto
* Add "--new-comment" / "--base" / "--head" support to Danger action (#8574) via Shunsuke Maeda
* Show all available options in `--help` output @nafu (#8624) via Fumiya Nakamura
* Make scan's slack_url ignore empty strings (#8627) via Michael Furtak
* Fix crash on some rare cases of `fastlane init` (#8604) via Felix Krause
* Improve documentation

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem update fastlane`
</details>
<br>

and the add testers step:

<details><summary>add testers output</summary>
[18:02:59]: Login to iTunes Connect (chris@figlyinc.com)
[18:03:01]: Login successful
[18:03:03]: Existing tester chris@figlyinc.com
[18:03:06]: Successfully added tester to app com.figlyinc.RadiatorMobile.chris.test

#######################################################################
# fastlane 2.25.0 is available. You are on 2.18.3.
# It is recommended to use the latest version.
# Please update using `sudo gem update fastlane`.
#######################################################################
# Run `sudo gem cleanup` from time to time to speed up fastlane
#######################################################################

2.25.0 Legacy build API & Xcode 8.3 messaging and other improvements
* pilot generates Ipa package in a random tmpdir (#8748) via Fred Cox
* Fix match typos (#8757) via color_box
* Add snapshot option to skip helper version check (#8751) via Helmut Januschka
* Update Your First PR instructions post monogem (#8754) via Andrea Falcone
* Pin the rubocop version to prevent reactive fixing (#8753) via Michael Furtak
* rubocop disable PercentLiteralDelimiters rule (#8752) via Helmut Januschka
* Add a tip about using QuickDemo for clean status bar (#8739) via Andrea Falcone
* Do not change or generate README.md after running rspec (#8629) via Fumiya Nakamura
* Use the new UI.test_failure! in screengrab (#8736) via Michael Furtak
* Add another ADB status phrase to reject (#8732) via Michael Furtak
* Add Gitlab 9.0+ ENV variable for branch detection. (#8707) via Peter Spiess-Knafl
* Fix pilot stuck waiting for multiple builds. Only wait for latest (current upload) (#8640) via Nicolás Gebauer
* Modernize action to action call to resolved configurations (#8719) via Todd Brannam
* Catch Xcode 8.3 legacy API while patching Xcode PackageApplication script (#8717) via Felix Krause
* Print information about dir handling in fastlane on error (#8694) via Felix Krause
* Show information about how to share schemes (#8714) via Felix Krause
* Add more tests for ConfigItem and clarify error message (#8711) via Felix Krause

2.24.0 Stability and documentation improvements and better React Native support
* Convince people to disable legacy build API (#8692) via Felix Krause

* Add custom error message when receive an internal server error (#8696) via Felix Krause

* change the zip output path from relative to absolute (#8637) via yukiasai

* Update fastlane tool collector to work with mono repo change (#8632) via Felix Krause

* Improve react-native onboarding (#8605) via Felix Krause

* Replace test failures with its own class to have more accurate crash metrics (#8631) via Felix Krause

* [match] Check push permission to git repository (#8643) via Econa77

* Add macOS support to snapshot (#8468) via David Ohayon

* Fix hardcoded fastlane paths (#8380) via Maksym Grebenets

* Fix crash in scan.rb - no implicit conversion of nil into Array (#8677) via battlmonstr

* Add documentation about the fastlane directory behavior (#8693) via Felix Krause

* Update update_checker to point to fastlane.tools domain (#8710) via Felix Krause

* And other documentation and test improvements



----



Unfortunately the legacy build API was removed with Xcode 8.3. Please make sure to remove `use_legacy_build_api` from your `./fastlane/Fastfile` and update the `gym` call to include the export method like this:



**App Store Builds**

```ruby

gym(scheme: "MyScheme", export_method: "app-store")

```



**Ad Hoc Builds**

```ruby

gym(scheme: "MyScheme", export_method: "ad-hoc")

```



**Development Builds**

```ruby

gym(scheme: "MyScheme", export_method: "development")

```



**In-House Enterprise Builds**

```ruby

gym(scheme: "MyScheme", export_method: "enterprise")

```



---



### What to do if you run into code signing errors?



If you run into a code signing error, please check out our [troubleshooting guide](https://docs.fastlane.tools/codesigning/troubleshooting/) and [common issue and how to solve them](https://docs.fastlane.tools/codesigning/common-issues/).



If that still doesn't help **please** [submit an issue](https://github.com/fastlane/fastlane/issues/new). Make sure to share your `fastlane env` output when doing so, and mention that you followed all steps in the linked docs.

2.23.0 General improvements
* Improve design of user input questions (#8606, #8607) via Felix Krause
* Fix edge case in `install_on_device` action (#8582) via Rafael Sachetto
* Add "--new-comment" / "--base" / "--head" support to Danger action (#8574) via Shunsuke Maeda
* Show all available options in `--help` output @nafu (#8624) via Fumiya Nakamura
* Make scan's slack_url ignore empty strings (#8627) via Michael Furtak
* Fix crash on some rare cases of `fastlane init` (#8604) via Felix Krause
* Improve documentation

To see all new releases, open https://github.com/fastlane/fastlane/releases

Please update using `sudo gem update fastlane`
</details>
<br>

If it would be useful, I can try a run now where I add the testers before uploading a build.

**Comment by ohayon** [comment]
Hey @cvermilion, thanks for all of that output. It would be really helpful to know how you are calling the add tester action that is producing that output. Also, is it safe to assume that the user you are trying to add is already an iTuneConnect user and you are just trying to assign them to the app to be able to test it?

**Comment by punksta** [comment]
Hello! I have similar issue. I want to create app, create cert, add internal tester and start testing from ci server. it was working before testflight updates. So before build user was added to itunes-connect users and I haven't start testing of that app. 

```
  # here is part of scripts which create app on itunes connect and make signing and build. 

  if ENV['PILOT_TESTER_EMAIL'] != nil
        Pilot::TesterManager.new.add_tester(
            email: ENV['PILOT_TESTER_EMAIL'],
            first_name: "appboss tester",
            last_name: "appboss",
            app_identifier: request['app_namespace']
        ) # <----- adding of user ends with error now
      end
  pilot(
          ipa: find_ipa,
          username: user,
          app_identifier: request['app_namespace'],
          beta_app_description: 'test',
          beta_app_feedback_email: DEFAULT_ACC,
      )
    end
```


```
[09:18:49][Step 2/2] [09:18:49]: ▸ 1.2.840.113635.100.1.61
[09:18:55][Step 2/2] [09:18:55]: Upload build to TestFlight
[09:18:55][Step 2/2] [09:18:55]: Login to iTunes Connect (*******)
[09:18:57][Step 2/2] [09:18:57]: Login successful
[09:18:57][Step 2/2] [09:18:57]: Existing tester ***
[09:18:59][Step 2/2] [09:18:59]: Could not add *** to app: ***
[09:19:01][Step 2/2] [09:19:01]: *** does not have a default external group. Please make sure to pass group names to the `:groups` option.
```

**Comment by ohayon** [comment]
Hi @punksta and @cvermilion, we are currently working on a fix here: https://github.com/fastlane/fastlane/pull/9002. Thanks for your patience!

**Comment by cvermilion** [comment]
> Hey @cvermilion, thanks for all of that output. It would be really helpful to know how you are calling the add tester action that is producing that output. Also, is it safe to assume that the user you are trying to add is already an iTuneConnect user and you are just trying to assign them to the app to be able to test it?

Here's the command I was using to add a tester in the run that was successful:

    fastlane pilot add -e "$email" -u "$ITUNES_CONNECT_ACCOUNT" -a "$bundle_id" --distribute_external=false

(having set up credentials in a prior step with `fastlane fastlane-credentials`).

And yes, these are existing iTC users, just want to assign them to the app so they get an email automatically. Obviously it's not a huge pain to add them manually in iTC but it's nice to be able to script the entire flow.

**Comment by cvermilion** [comment]
Ah, looks like a fix has already landed! I will take a look as soon as that's in a release. Or is there a straightforward way to update my local version to the latest `master`? (I couldn't find anything in the docs.)

Thanks for the quick turnaround!

**Comment by ohayon** [comment]
Thanks for the follow up @cvermilion! So, two things:

1. using the `--distribute_external` flag is probably unnecessary in when running `fastlane pilot add ...` it is more meant for when distributing apps to testers, specifying to which groups they are being sent. And even with that said, the new TestFlight changes have made it so that wont even be the case moving forward because for apps that were added to TestFlight since the changes, they do not have a default external group, so groups must be specified.
2. There is definitely a straightforward way to run from the updated `master` branch, and we'd love to hear your feedback and see if the changes we made will fix your issue. To run from master you can:
* Create a `Gemfile` in your project directory with the following contents:
```
source "https://rubygems.org"

gem 'fastlane', git: 'https://github.com/fastlane/fastlane'
```
* Then you can run `bundle install` to get the most recent `master`
* Then, to execute _fastlane_ using the `master` branch, you can run `bundle exec fastlane .....` from your command line.

Let us know how this goes for you. Thanks again! 🚀 🐙

**Comment by cvermilion** [comment]
It's looking good on master for me now! 🎉 

And indeed, dropping the `--distribute_external` flag doesn't break anything. So I guess an existing iTC user is added as internal by default?

As a tangential suggestion, I don't use Ruby and `rubygems` for much other than a few tools like `fastlane`, so the `Gemfile` approach to using master wasn't at all obvious to me -- it might be worth adding that to the docs somewhere.

**Comment by ohayon** [comment]
Thanks for following up @cvermilion! 🚀  

The behavior for adding testers is that it tries to find an iTC user first by the email address and if it finds that, it will add it to the app otherwise, it will create a new external and add it to the specified groups in the app or, if no groups are specified, it will try to find the default external group (which is not available for apps added to TestFlight since the changes from a couple weeks ago).

Thats a great suggestion to add those instructions to some docs. We will definitely make that happen!

I am going to close this issue for now, but let us know if you have any more issues that come up. Thanks again! 🐙
