### ISSUE TITLE
CodeSign error: code signing is required for product type 'Framework' in SDK 

### ISSUE THREAD

**Issue by empiteranga** [fastlane/fastlane#900]
▸ Building Pods/Doorbell [(Release)]
▸ Check Dependencies

❌  CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.2'

▸ Building Pods/AFNetworking [(Release)]
▸ Check Dependencies

❌  CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.2'

▸ Building Pods/MBProgressHUD [(Release)]
▸ Check Dependencies

❌  CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.2'

▸ Building Pods/Bolts [(Release)]
▸ Check Dependencies

❌  CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.2'

** ARCHIVE FAILED **

this is my fastlane file 

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
    # increment_build_number

    # xctool # run the tests of your app
  end

  desc "Runs all the tests"
  lane :test do
    # snapshot
  end

 ######################### PUBLIC LANES ##########################

  lane :testing do
    fabric(scheme: "Testing")
  end
  
  lane :staging do
    fabric(scheme: "Staging")
  end

  lane :preproduction do
    itc(scheme: "Preproduction")
  end

  lane :release do
    itc(scheme: "Release")
  end

  ######################### PRIVATE LANES #########################
  #------------------------- Crashlytics -------------------------#

  private_lane :fabric do |options|
    scheme = options[:scheme]

    sigh(
      skip_install: true,
      development: true,
	adhoc: true,
  	force: true
    )
    build(
      scheme: scheme, 
      signId: ENV['SIGNING_IDENTITY_DEV']
    )

    environment = scheme.upcase
    api = File.read("../projectName/Constants/environment_constants.h").scan(/\d\.*/).join

    crashlytics(
      ipa_path: "../projectName.ipa",
      notes: "Running on #{environment} #{api}",
      groups: ['Path2Smile-test’],
      crashlytics_path: ‘./Crashlytics.framework’,
      api_token: ENV['CRASHLYTICS_API_TOKEN'],
      build_secret: ENV['CRASHLYTICS_BUILD_SECRET’],
      notifications: "YES"

    )

    post_to_slack(scheme: scheme, destination: "Crashlytics")
  end

   ############################# UTIL ##############################

  private_lane :build do |options|
    scheme = options[:scheme]
    signingId = options[:signId]

    gym(
      scheme: "projectName #{scheme}", 
      configuration: scheme, 
      clean: true, 
      include_bitcode: false,
      workspace: "projectName.xcworkspace",
      output_directory: "../",
      output_name: "projectName.ipa",
      codesigning_identity: "#{signingId}",
      xcargs: "ARCHIVE=YES" # Used to tell the Fabric run script to upload dSYM file
    )
  end

  private_lane :post_to_slack do |options|
    scheme      = options[:scheme]
    version     = get_version_number(xcodeproj: "projectName.xcodeproj")
    build       = get_build_number(xcodeproj: "projectName.xcodeproj")
    environment = scheme.upcase
    api         = File.read("../projectName/Constants/environment_constants.h").scan(/\d\.*/).join
    destination = options[:destination]

    slack(
      message: "<!here|here>: New :ios: *#{version}* (#{build}) running `#{environment}` `#{api}` has been submitted to *#{destination}*  :rocket:",
    )

  end

 ############################# POST ##############################

  # This lane is called, only if the executed lane was successful
  after_all do |lane|

    File.delete("../../projectName.ipa")
    File.delete("../../projectName.app.dSYM.zip")

    sh "./scripts/add_pods.sh"
    cocoapods

    build = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    commit_version_bump(
      message: "Build #{build}"
    )

    notify "Fastlane finished '#{lane}' successfully" # Mac OS X Notification
  end

  error do |lane, exception|
    sh "./scripts/add_pods.sh"
    cocoapods

    notify "Fastlane '#{lane}' errored" # Mac OS X Notification
 end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    sigh
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    # snapshot
    sigh
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

**Comment by ohwutup** [comment]
Hey @empiteranga apologies for the long time since you submitted this issue! Have you tried this with more recent versions of the tool set? I am going to close this issue for now as it's been a while, but please comment here if you are still having issues and we will reopen it for sure! Thank you! :+1:
