### ISSUE TITLE
Simultaneous builds from single folder

### ISSUE THREAD

**Issue by soxjke** [fastlane/fastlane#9001]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When executing few simultaneous builds from the same checkout folder, they might interrupt each other. This is especially useful, when the project has more than one application target OR tests should run simultaneously with the application. 

One solution I came up with is creating an action that will wrap build flow inside some temporary directory like `build/{UUID}` which are often inside `.gitignore`. Is it worth opening a PR to add this kind of action to fastlane master repo or it's better to maintain it by my own `actions` and migrate between projects?

The draft I've made is https://github.com/soxjke/fastlane/blob/e8cbac49fbdb560991efae94c678e9bee8901a45/fastlane/lib/fastlane/actions/sandbox_build.rb

Basic usage is
```
def build_and_deploy(options)
  sandbox_build(
    worker_block: Proc.new do
      ensure_git_status_clean
      cocoapods(use_bundle_exec: true)
      target = options[:target]
      match(app_identifier: config()["app_identifier"][target], type: options[:type] ? options[:type] : "development", readonly: true)
      gym(scheme: config()["scheme"][target],
        configuration: predict_configuration(options),
        workspace: "MyApp.xcworkspace",
        include_bitcode: options[:itunes] != nil)
      if options[:crashlytics] then
        crashlytics(api_token: config()["crashlytics_api_token"][target],
              build_secret: config()["crashlytics_build_secret"][target])
      elsif options[:itunes] then
        testflight
      end
    end
  )
end
```

**Comment by ohayon** [comment]
Hey @soxjke, thanks for creating the issue! That does sound like a cool idea. I think it would be best for now to create a [_fastlane_ plugin](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Plugins.md) for this! 🚀

**Comment by soxjke** [comment]
Hey @ohayon , thanks.

I'll follow through plugin instruction seems to be straightforward.
