### ISSUE TITLE
Could not find build (FastlaneCore::Interface::FastlaneCrash)

### ISSUE THREAD

**Issue by pranavgupta27** [fastlane/fastlane#9012]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane deliver --ipa "./appjDHlek0904.ipa" --submit_for_review --skip_metadata --skip_screenshots
[22:41:59]: Successfully loaded '/Users/pranavg/fastlane/Deliverfile' 📄

+----------------+--------------------------------+
|      Detected Values from './Deliverfile'       |
+----------------+--------------------------------+
| app_identifier | com.crowdcompass.appjDHlek0904 |
| username       | ccbughunt@gmail.com            |
+----------------+--------------------------------+

[22:41:59]: Login to iTunes Connect (ccbughunt@gmail.com)
[22:42:03]: Login successful

+-----------------------+--------------------------------+
|                 deliver 2.28.5 Summary                 |
+-----------------------+--------------------------------+
| ipa                   | ./appjDHlek0904.ipa            |
| submit_for_review     | true                           |
| skip_metadata         | true                           |
| skip_screenshots      | true                           |
| app_identifier        | com.crowdcompass.appjDHlek0904 |
| username              | ccbughunt@gmail.com            |
| screenshots_path      | ./screenshots                  |
| metadata_path         | ./metadata                     |
| app_version           | 1.24                           |
| edit_live             | false                          |
| platform              | ios                            |
| skip_binary_upload    | false                          |
| force                 | false                          |
| automatic_release     | false                          |
| overwrite_screenshots | false                          |
+-----------------------+--------------------------------+

[22:42:31]: Making sure the latest version on iTunes Connect matches '1.24' from the ipa file...
[22:42:33]: '1.24' is the latest version on iTunes Connect
[22:42:34]: Uploading app icon...
[22:42:44]: Uploading binary to iTunes Connect
[22:42:45]: Going to upload updated app to iTunes Connect
[22:42:45]: This might take a few minutes. Please don't interrupt the script.
[22:56:32]: [Transporter Error Output]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
[22:56:32]: [Transporter Error Output]: An exception has occurred: Operation timed out
[22:56:37]: iTunes Transporter successfully finished its job
[22:56:37]: Communication error. Please use diagnostic mode to check connectivity. You need to have outbound access to TCP port 443.
An exception has occurred: Operation timed out
[22:56:37]: Although errors occurred during execution of iTMSTransporter, it returned success status.
[22:56:37]: --------------------------------------------------------------------
[22:56:37]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[22:56:37]: --------------------------------------------------------------------
[22:56:37]: Finished the upload to iTunes Connect
[22:56:39]: Selecting the latest build...
[22:56:43]: Waiting iTunes Connect processing for build 1.24 (1.24)... this might take a while...
[22:57:16]: Waiting iTunes Connect processing for build 1.24 (1.24)... this might take a while...
[22:57:48]: Waiting iTunes Connect processing for build 1.24 (1.24)... this might take a while...
[22:58:21]: Waiting iTunes Connect processing for build 1.24 (1.24)... this might take a while...
[22:58:55]: Waiting iTunes Connect processing for build 1.24 (1.24)... this might take a while...
[22:59:27]: Waiting iTunes Connect processing for build 1.24 (1.24)... this might take a while...
[23:00:00]: []

Looking for related GitHub issues on fastlane/fastlane...

➡️  [!] Could not find action, lane or variable 'pgyer'.
    https://github.com/fastlane/fastlane/issues/9006 [open] 2 💬
    10 hours ago

➡️  gym could not work now
    https://github.com/fastlane/fastlane/issues/7959 [open] 20 💬
    03 Mar 2017

➡️  Could not find a matching code signing identity for type AppStore on Jenkins
    https://github.com/fastlane/fastlane/issues/8858 [closed] 4 💬
    a week ago

and 525 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20find%20build&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/ui/interface.rb:138:in `crash!': [!] Could not find build (FastlaneCore::Interface::FastlaneCrash)
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/submit_for_review.rb:81:in `find_build'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/submit_for_review.rb:58:in `block in wait_for_build'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/submit_for_review.rb:57:in `loop'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/submit_for_review.rb:57:in `wait_for_build'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/submit_for_review.rb:42:in `select_build'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/submit_for_review.rb:5:in `submit!'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/runner.rb:107:in `submit_for_review'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/runner.rb:30:in `run'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/commands_generator.rb:63:in `block (2 levels) in run'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0@global/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/commands_generator.rb:164:in `run'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/deliver/lib/deliver/commands_generator.rb:12:in `start'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/gems/fastlane-2.28.5/bin/fastlane:20:in `<top (required)>'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/bin/fastlane:22:in `load'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/bin/fastlane:22:in `<main>'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/pranavg/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12                                       |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.28.5"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
# generated_fastfile_id "3a4d4254-c897-4da8-81d7-d9d27bf74927"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "app-store"
  )

  # upload to Testflight
  pilot(skip_waiting_for_build_processing: true)

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.5  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| rubyzip                   | 1.2.1        |
| faraday                   | 0.12.1       |
</details>

*generated on:* **2017-04-27**
</details>

**Comment by pranavgupta27** [comment]
Also i got this email from App Store Team

Dear developer,

We have discovered one or more issues with your recent delivery for "B1 submit". To process your delivery, the following issues must be corrected:

Missing Info.plist key - This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.

Once these issues have been corrected, you can then redeliver the corrected binary.

**Comment by thebugcode** [comment]
@pranavgupta27 You need to follow the app store suggestion and include a description in your info.plist under the key NSBluetoothPeripheralUsageDescription. This doesn't seem to be a fastlane issue, but an issue with your app

**Comment by ohayon** [comment]
@pranavgupta27 I believe that @thebugcode is correct. I am going to close this for now, but let us know if there are more issues. 🚀

**Comment by pranavgupta27** [comment]
@thebugcode @ohayon I am able to upload the same app manually. If it has been an issue with the app i would have observed the same issue. 

Is there something i might be missing here
