### ISSUE TITLE
FASTLANE_DISABLE_COLORS not working with pilot anymore

### ISSUE THREAD

**Issue by tmm1** [fastlane/fastlane#9014]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Using `pilot` to add testers and perform other operations now outputs with colors, even if colors are disabled.

##### Complete output when running fastlane, including the stack trace and command used

Output looks identical when copy/pasted, but is colored even though I set `FASTLANE_DISABLE_COLORS=1`. This used to work as expected, so it seems like a regression since the recent testflight changes.

**Comment by KrauseFx** [comment]
Thanks for reporting this, I can reproduce the issue. I'll look into resolving it.

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/issues/9016 👍
