### ISSUE TITLE
fastlane doesn't set scheme name for xcodebuild during init

### ISSUE THREAD

**Issue by viacheslavleonov** [fastlane/fastlane#9019]
### Issue Description
When run `fastlane init`, fastlane doesn't set scheme name for `xcodebuild` when tries to create app in developer portal, thus receives error from `xcodebuild` and can not get correct application name and  uses 'App' instead of real application name 'test'
```
xcodebuild clean -showBuildSettings -workspace ./test.xcworkspace
xcodebuild: error: If you specify a workspace then you must also specify a scheme.  Use -list to see the schemes in this workspace.
```

### Captured Output

Command Used: `init`
<details><summary>Output/Log</summary>

```
[17:24:24]: Detected iOS/Mac project in current directory...
[17:24:24]: This setup will help you get up and running in no time.
[17:24:24]: fastlane will check what tools you're already using and set up
[17:24:24]: the tool automatically for you. Have fun!
[17:24:24]: $ xcodebuild -list -workspace ./test.xcworkspace
[17:24:25]: $ xcodebuild clean -showBuildSettings -workspace ./test.xcworkspace -scheme test
[17:24:26]: Your Apple ID (e.g. fastlane@krausefx.com): qa@ampiri.com
[17:24:32]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[17:24:32]: Starting login with user 'qa@ampiri.com'

+----------------+----------------------------------------------------------+
|                              Detected Values                              |
+----------------+----------------------------------------------------------+
| Apple ID       | qa@ampiri.com                                            |
| App Name       | test                                                     |
| App Identifier | com.ampiri.test                                          |
| Workspace      | /Users/viacheslav.leonov/Downloads/test/test.xcworkspace |
+----------------+----------------------------------------------------------+

[17:24:39]: This app identifier doesn't exist on iTunes Connect yet, it will be created for you
[17:24:39]: This app identifier doesn't exist on the Apple Developer Portal yet, it will be created for you
[17:24:39]: Please confirm the above values (y/n)
y
[17:24:43]: Created new file './fastlane/Appfile'. Edit it to manage your preferred app metadata information.
[17:24:43]: Creating the app on iTunes Connect and the Apple Developer Portal
[17:24:43]: $ xcodebuild clean -showBuildSettings -workspace ./test.xcworkspace
xcodebuild: error: If you specify a workspace then you must also specify a scheme.  Use -list to see the schemes in this workspace.
[17:24:43]: Could not read build settings. Make sure that the scheme "" is configured for running by going to Product → Scheme → Edit Scheme…, selecting the "Build" section, checking the "Run" checkbox and closing the scheme window.

+----------------+-----------------+
|    Summary for produce 2.28.5    |
+----------------+-----------------+
| app_name       | App             |
| app_identifier | com.ampiri.test |
| username       | qa@ampiri.com   |
| sku            | 1493393083      |
| platform       | ios             |
| language       | English         |
| skip_itc       | false           |
| skip_devcenter | false           |
| team_id        | XXXXXXXXX      |
+----------------+-----------------+
```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.11.6 (15G1217)                  |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.ampiri.test" # The bundle identifier of your app
apple_id "qa@ampiri.com" # Your Apple email address

team_id "7C7H88B9P9" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.5  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| terminal-notifier         | 1.7.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.2.0        |
| faraday                   | 0.12.1       |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| google-api-client         | 0.9.28       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| bundler                   | 1.14.6       |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.3        |
| gh_inspector              | 1.0.3        |
</details>

*generated on:* **2017-04-28**
</details>

**Comment by thebugcode** [comment]
Hi @viacheslavleonov 
As a workaround I would suggest creating the app manually (since you only do it once) and then automating your processes with fastlane.

**Comment by KrauseFx** [comment]
This looks like a bug, and something we should fix. Could you share a screenshot of your project directory, and its xcodeproj and xcworkspace file? Do you know what's the best way for us to reproduce the problem? How many schemes does your project have?

**Comment by viacheslavleonov** [comment]
I tested this bug on a new empty project with empty cocoapods integration just to create workspace. One scheme, one target.
I've added project in attachment.
[FastLaneTest.zip](https://github.com/fastlane/fastlane/files/969933/FastLaneTest.zip)

**Comment by KrauseFx** [comment]
@viacheslavleonov Thanks for providing the sample project, I can reproduce the issue now 👍

**Comment by KrauseFx** [comment]
Hey @viacheslavleonov, I just pushed a PR that will fix this 👍 https://github.com/fastlane/fastlane/pull/9037

Basically you have to mark your scheme as `Shared` in Xcode. Let me know if that fixes the issue  🚀

On the next release, this should be indicated by the error message, and also we automatically fetch the first scheme

**Comment by viacheslavleonov** [comment]
I've checked with shared scheme as well and it didn't help.
