### ISSUE TITLE
can deliver and pilot work with the same build?

### ISSUE THREAD

**Issue by ConfusedVorlon** [fastlane/fastlane#902]
my ideal workflow would be something like

gym
pilot (build N)
(wait)
deliver - (using the already submitted build N)

or alternatively

gym
deliver (build N)
pilot (build N)
(wait)
deliver --skip_metadata --skip_screenshots --submit_for_review

e.g. I don't want to rebuild and re-upload between beta and delivery; I think that you should release what you actually tested.
At the moment, as far as I can see, both pilot and deliver want to upload binaries. I'm looking for something like --skip_binary on both.

Am I missing a way to do this?

thank you.

**Comment by nicolasbraun** [comment]
You could try calling `deliver` without the `ipa` param and with the submit_for_review:true
That being said I believe this is intended to update metadata  but I  never tried to push for review on previously uploaded build that way. Maybe you need at least metadata or ipa.

I am interested in the result :)

**Comment by ConfusedVorlon** [comment]
I use fastlane, so I think deliver takes the ipa param automatically. (I'm certainly not providing it)

**Comment by ohwutup** [comment]
Hey everyone! I am going to close this issue as there has not been much activity as of recently. Please feel free to continue discussion and we can reopen the issue if necessary. Thanks!! :cactus:
