### ISSUE TITLE
fastlane command not found

### ISSUE THREAD

**Issue by anishparajuli555** [fastlane/fastlane#9029]
### Issue Description

I have successfully setup fast-lane in my project.I have tried running fast-lane action from terminal and it works correctly.

<img width="683" alt="eqjgw" src="https://cloud.githubusercontent.com/assets/7752578/25556299/d0891386-2d19-11e7-81c7-d0f0127b993d.png">
And on Trigger i am adding the same command on Post script trigger
<img width="733" alt="rzmxu" src="https://cloud.githubusercontent.com/assets/7752578/25556313/01c1e284-2d1a-11e7-8fed-388a4e4bcf45.png">

### Error Description

The error i get after integrating Xcode bot is fast lane command not found

<img width="852" alt="sygwv" src="https://cloud.githubusercontent.com/assets/7752578/25556325/1c8e1876-2d1a-11e7-84a2-a44839d11939.png">

### Output of fastlane Env (Note: Executed command from terminal)

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.3 (Apple Git-75)            |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.5"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..." 
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :betaUpload do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # You can define as many lanes as you want
 lane :inc_build do
  # Ensure that your git status is not dirty
  ensure_git_status_clean

  # Increment the build number (not the version number)
  # Providing the xcodeproj is optional
  increment_build_number(xcodeproj: "Sms-testproject.xcodeproj")

  # Commit the version bump
  commit_version_bump(xcodeproj: "Sms-testproject.xcodeproj")

  # Add a git tag for this build. This will automatically
  # use an appropriate git tag name

  # Push the new commit and tag back to your git remote
  push_to_git_remote
end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.***.***” # The bundle identifier of your app
apple_id “sometexthere” # Your Apple email address

team_id “*****” # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.28.5  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-04-29**
</details>

Can't find where i missed or any way to set the path to my fast lane folder?

**Comment by PetrosIchor** [comment]
I personally haven't integrated into xcode build steps, but you may want to specify the path of fastlane. 

Find the path with `which fastlane` or use what's described in your env output (`~/.fastlane/bin/bundle/bin/fastlane`)

**Comment by KrauseFx** [comment]
Yeah, Xcode by default, doesn't set the required environment / path variables to make it work. One way to solve it is what @PetrosIchor said 👍

**Comment by anishparajuli555** [comment]
@PetrosIchor  @KrauseFx  I just tried and still not working.Tried setting the path in Environmental variable.

**Comment by thebugcode** [comment]
@anishparajuli555 Try setting `~/.fastlane/bin/bundle/bin/fastlane inc_build` instead of just `fastlane in_build` or if you have an older installation of fastlane try `/usr/local/bin/fastlane inc_build`
One of them should work. 

Also, Xcode server is a huge pain, if you're looking for alternative CI servers, try Jenkins + fastlane.

**Comment by anishparajuli555** [comment]
@thebugcode  I tried it...Now the error is as command not found..It has successfully reached to the path of fastlane but cannot get the command inc_build
<img width="779" alt="screen shot 2017-05-02 at 9 23 03 pm" src="https://cloud.githubusercontent.com/assets/7752578/25626033/ef84b6a8-2f7d-11e7-859f-68d9876f37aa.png">
<img width="733" alt="screen shot 2017-05-02 at 9 23 18 pm" src="https://cloud.githubusercontent.com/assets/7752578/25626045/f9575096-2f7d-11e7-9e10-5a0101381c89.png">
<img width="821" alt="screen shot 2017-05-02 at 9 27 05 pm" src="https://cloud.githubusercontent.com/assets/7752578/25626098/255de6b4-2f7e-11e7-93a7-abac44b29efd.png">

**Comment by thebugcode** [comment]
Okay. So this is not a fastlane issue, it's just Xode Server can't find fastlane. I suggest following this stackoverflow answer http://stackoverflow.com/a/39256822/978510 and my best bet is that you need to call this before calling `fastlane inc_build`:
`export PATH="/Users/Anish/.fastlane/bin:$PATH"`
