### ISSUE TITLE
hockey step not able to create app entry on hockeyapp

### ISSUE THREAD

**Issue by pav1790** [fastlane/fastlane#9035]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
If the application is not created on hockey app the action hockey does not create it. My fastfile is provided with environment with values replaced with xxxxxxx for privacy. 

##### Complete output when running fastlane, including the stack trace and command used

[15:28:12]: Driving the lane 'Upload' 🚀
[15:28:12]: --------------------
[15:28:12]: --- Step: hockey ---
[15:28:12]: --------------------
[15:28:12]: Symbols not found on path xxxx. Crashes won't be symbolicated properly
[15:28:12]: Starting with file(s) upload to HockeyApp... this could take some time.
+---------------+--------+
|      Lane Context      |
+---------------+--------+
| PLATFORM_NAME |        |
| LANE_NAME     | Upload |
+---------------+--------+
[15:28:13]: Error trying to create app version:  404 - {"errors"=>{"app"=>["not found"]}}

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 💥   | hockey | 0           |
+------+--------+-------------+

[15:28:13]: fastlane finished with errors

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.11.6 (15G1421)                  |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :Upload do
	hockey(
		api_token: "xxxxxxxx",
		create_update: true,
        public_identifier: "xxxxxxxx",
        bundle_short_version: "xxxxxxxx",
        bundle_version: "xxxxxxxx",
		ipa: "xxxxxxxx",
        notes: "xxxxxxxx"
	)
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.7  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.3        |
| excon                     | 0.55.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| faraday                   | 0.12.1       |
</details>

*generated on:* **2017-05-01**
</details>

**Comment by KrauseFx** [comment]
_fastlane_ doesn't create a new hockey app for you, you can either create it manually using the hockey web UI, or you can use Crashlytics beta, which creates the app automatically on the first run 👍

**Comment by pav1790** [comment]
Thanks for the quick response. And yes, apologies. I should have worded this clearly. I am aware that fastlane does not do it as yet - I directly invoke the hockeyapp api to create the application. 

I was wondering if such a functionality could be requested or even submitted by us. That is to say, are there any "guiding principles" that oppose "app creation" from within this fastlane action?

**Comment by KrauseFx** [comment]
Oh, I understand now. Currently no, and it's probably nothing we will work on, as we're currently focusing on other areas on _fastlane_.

**Comment by pav1790** [comment]
Could I give it a go?

**Comment by KrauseFx** [comment]
Sure thing. Check out how to get started (https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) and this is the action that needs to be modified https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/hockey.rb

Let me know if you need any help 👍  Thanks for your contribution

**Comment by pav1790** [comment]
Looking into it now.  I ll comment with the PR when i am done.

**Comment by KrauseFx** [comment]
We just received an issue from the Microsoft team, maybe you should talk with them first before spending time on this task 👍  https://github.com/fastlane/fastlane/issues/9105

**Comment by pav1790** [comment]
Thanks Felix! I think they might want to include this change- given what they are planning to offer.

**Comment by derpixeldan** [comment]
@pav1790 thanks for your interest. We've just published the new [Mobile Center](http://www.rubydoc.info/gems/fastlane-plugin-mobile_center) plugin and you can expect the create option to be added soon.

**Comment by pav1790** [comment]
I will close this issue. Sorry I hadn't looked into this further. Ended up using the hockeyapp apis to do most of it. I ll be keeping an eye on the mobilecenter plugin. :)
