### ISSUE TITLE
Feature request for sigh

### ISSUE THREAD

**Issue by tychop** [fastlane/fastlane#9038]
Can we have "fastlane sigh --force" not only add all the devices to the profile, but also all certificates?

**Comment by KrauseFx** [comment]
That's not always possible, as depending on the profile type, there might only be one certificate allowed.

**Comment by tychop** [comment]
Hi Felix. It's been a long time since we talked 😉

We need it for de dev profiles.
Our situation: The CI process renews the dev profile and includes all the devices. Nice!! But it also throws away all the certificates except the one used on the build server. And since XCode now manages the profiles itself, it just downloads the latest one (with the 1 wrong certificate) to the dev machine.
This makes it for our developers impossible to run apps on their devices (no cert). And our developers do not have access to apple's dev portal to modify the profiles themselves (too dangerous. They can accidentally bring down our organisation)

Do you have any suggestions how to coop with this ?

**Comment by KrauseFx** [comment]
Hey @tychop 👍 

Yeah, check out the new [code signing docs](https://docs.fastlane.tools/codesigning/getting-started/#xcode-8-and-up) that explain how you can use the automatic code signing for development builds, and fastlane for distribution builds 🚀 Let me know if that works for you.

**Comment by tychop** [comment]
I'ld love to try the whole fastlane suite, but there is just no quick read or examples on how to do Enterprise development, Enterprise distribution, storing xcarchives, storing dsyms, git tagging, etc etc.
I've tried reading all the seperate readme's but that does not give me the overview I need. Also I need to be REALLY REALLY sure fastlane will not even think of touching our enterprise certificate.

Are there any test projects with prepared Fastlane files, match file, appfiles etc etc etc etc etc ?

**Comment by KrauseFx** [comment]
Hey @tychop, thanks for the feedback regarding the docs, I completely agree. We worked on a new docs.fastlane.tools page, but we never finished migrating all the docs to one central space. 

Have you seen our example fastlane setups? https://github.com/fastlane/examples/

We currently don't have a super easy overview, I'd recommend watching my talk on https://fastlane.tools and going from there 👍 

Let me know if you have any other questions.

**Comment by tychop** [comment]
Thnx Felix, I'll see if I can get some spike time from our scrum master to figure out how we can use fastlane to improve our build system.
