### ISSUE TITLE
As an IOS developer, I would like to use fastlane for provisioning with a personal (free) Apple ID.

### ISSUE THREAD

**Issue by agentilela** [fastlane/fastlane#9041]
### New Issue Checklist

- [x] Updated fastlane to the latest version (v2.28.7 at the time of writing)
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
No teams available on the Developer Portal
You must accept an invitation to a team for it to be available
To learn more about teams and how to use them visit https://developer.apple.com/library/ios/documentation/IDEs/Conceptual/AppDistributionGuide/ManagingYourTeam/ManagingYourTeam.html

Looking for related GitHub issues on fastlane/fastlane...

➡️  Not able to push app to Testflight in an account in which I am the admin
    https://github.com/fastlane/fastlane/issues/8528 [open] 3 💬
    4 weeks ago

➡️  Error in fastlane init. Your account is in no teams
    https://github.com/fastlane/fastlane/issues/5115 [closed] 3 💬
    06 Dec 2016

➡️  Sigh support for personal teams
    https://github.com/fastlane/fastlane/issues/6022 [closed] 11 💬
    13 Feb 2017

and 70 more at: https://github.com/fastlane/fastlane/search?q=Your%20account%20is%20in%20no%20teams&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/portal/ui/select_team.rb:41:in `select_team': [!] Your account is in no teams (RuntimeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/portal/portal_client.rb:55:in `select_team'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/portal/spaceship.rb:86:in `select_team'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/sigh/lib/sigh/runner.rb:16:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/sigh/lib/sigh/manager.rb:7:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/sigh/lib/sigh/commands_generator.rb:55:in `block (2 levels) in run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/sigh/lib/sigh/commands_generator.rb:123:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.28.7/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.7  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-05-02**
</details>

### Feature Request

There was some discussion about this on #6022, but it was auto-closed due to inactivity. Just 
wanted to raise visibility that this feature would still be great to have for some of us, and hopefully you guys can get it on the list for prioritization 😃

**Comment by KrauseFx** [comment]
Sorry, _fastlane_ doesn't support personal Apple IDs for now, as it requires a paid Apple Developer account. The main focus for _fastlane_ is to automate the App Store and Beta distribution of builds, not so much Development builds.
