### ISSUE TITLE
fastlane init not prompting for Apple Id

### ISSUE THREAD

**Issue by davidhan256** [fastlane/fastlane#9048]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Following installation of fastlane, when I run _fastlane init_  in root folder of a Xcode project I am not getting prompted for my Apple Id as expected. Not sure what I am doing wrong.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

no_proxy is unsupported
[09:02:04]: Detected iOS/Mac project in current directory...
[09:02:04]: This setup will help you get up and running in no time.
[09:02:04]: fastlane will check what tools you're already using and set up
[09:02:04]: the tool automatically for you. Have fun! 
[09:02:04]: $ xcodebuild clean -showBuildSettings -project ./HelloWorld.xcodeproj
2017-05-03 09:02:04.366 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad01bfc0:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS3.1.sdk'>': SDK with name 'watchos3.1' being superceded by SDK with 'watchos3.1'.
2017-05-03 09:02:04.368 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad029c90:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.1.sdk'>': SDK with name 'iphonesimulator10.2' being superceded by SDK with 'iphonesimulator10.2'.
2017-05-03 09:02:04.368 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad02a0d0:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk'>': SDK with name 'iphonesimulator10.2' being superceded by SDK with 'iphonesimulator10.2'.
2017-05-03 09:02:04.370 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad031640:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator10.1.sdk'>': SDK with name 'appletvsimulator10.1' being superceded by SDK with 'appletvsimulator10.1'.
2017-05-03 09:02:04.371 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad0050b0:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator3.1.sdk'>': SDK with name 'watchsimulator3.1' being superceded by SDK with 'watchsimulator3.1'.
2017-05-03 09:02:04.372 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad0398b0:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS10.1.sdk'>': SDK with name 'appletvos10.1' being superceded by SDK with 'appletvos10.1'.
2017-05-03 09:02:04.373 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad03d4a0:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.1.sdk'>': SDK with name 'iphoneos10.2' being superceded by SDK with 'iphoneos10.2'.
2017-05-03 09:02:04.373 xcodebuild[24219:724214] [MT] DVTSDK: Warning: SDK path collision for path '<DVTFilePath:0x7fc5ad03d850:'/Applications/Xcode-8.2.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk'>': SDK with name 'iphoneos10.2' being superceded by SDK with 'iphoneos10.2'.
2017-05-03 09:02:04.747 xcodebuild[24219:724214] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/FortifyScanningPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
[09:02:05]: Your Apple ID (e.g. fastlane@krausefx.com): 

Looking for related GitHub issues on fastlane/fastlane...

➡️  Setting up fastlane for the first time, getting errors early on. 
    https://github.com/fastlane/fastlane/issues/8792 [open] 4 💬
    5 days ago

➡️  Missing Push Notification Entitlement - response from itunes app review
    https://github.com/fastlane/fastlane/issues/8523 [open] 5 💬
    6 weeks ago

➡️  fastlane deliver upload_build - not referencing fastlane/metadata/review_information/notes.txt for app_review_information key 'notes'
    https://github.com/fastlane/fastlane/issues/8413 [closed] 2 💬
    01 Mar 2017

and 16 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/interface.rb:138:in `crash!': [!] Could not retrieve response as fastlane runs in non-interactive mode (FastlaneCore::Interface::FastlaneCrash)
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:128:in `verify_interactive!'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:101:in `input'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/setup/setup_ios.rb:187:in `ask_for_apple_id'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/setup/setup_ios.rb:28:in `run'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/setup/setup.rb:29:in `run'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/r595879/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/bin/fastlane:20:in `<top (required)>'
	from /Users/r595879/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/r595879/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

no_proxy is unsupported
[09:05:13]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.11.6                                           |
| Ruby                        | 2.2.4                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.10.1 (Apple Git-78)                 |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane               |
| Host                        | Mac OS X 10.11.6 (15G1421)                        |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                        |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                        |
| Is contained                | false                                             |
| Is homebrew                 | true                                              |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-8.2.1.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.7  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-03**
</details>

**Comment by KrauseFx** [comment]
The error says `Could not retrieve response as fastlane runs in non-interactive mode`. Are you running this in your default shell? Is it interactive?

**Comment by davidhan256** [comment]
I am running in default shell. I believe it is interactive:

C02RL26QG8WN:HelloWorld r595879$ if tty -s; then echo interactive; fi
interactive

**Comment by KrauseFx** [comment]
Can you check the Ruby variable `$stdout.isatty`? Also do you have any of the following environment variables set
```
['JENKINS_HOME', 'JENKINS_URL', 'TRAVIS', 'CIRCLECI', 'CI', 'TEAMCITY_VERSION', 'GO_PIPELINE_NAME', 'bamboo_buildKey', 'GITLAB_CI', 'XCS']
```

**Comment by davidhan256** [comment]
irb(main):007:0> $stdout.isatty
=> true

The only environment variable I have set is JENKINS_HOME (/Users/r595879/bin/jenkins)

**Comment by KrauseFx** [comment]
Yeah, because you set `JENKINS_HOME`, _fastlane_ thinks you're running `fastlane init` on Jenkins, which doesn't work. Could you run `unset JENKINS_HOME`, just for this session, so you can setup _fastlane_? Once _fastlane_ is set up, you can use it with the `JENKINS_HOME` variable set 👍

**Comment by davidhan256** [comment]
Thanks for this! This has resolved issue. Can I suggest that this workaround is added to the documentation?

**Comment by KrauseFx** [comment]
@davidhan256 To me that seems more like something that should be printed out when _fastlane_ fails, as otherwise people don't find it in the docs if they run into this problem 👍

**Comment by davidhan256** [comment]
Agreed. That would be a better solution.
