### ISSUE TITLE
Improving the output of EnsureGitStatusCleanAction

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#9049]
🔑

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

While executing the `ensure_git_status_clean` on the CI, I'm getting the error message:
```
Git repository is dirty! Please ensure the repo is in a clean state by committing/stashing/discarding all changes first.
```
I think it would be a good improvement to output or at least provide an option to output exactly why status is not clean. If it sounds good for you I would be happy to prepare a PR.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.70.0"

ENV["LANG"]="en_US.UTF-8"

default_platform :ios

platform :ios do

  ipa_directory = "../"
  ipa_name = "ios-guest.ipa"

  ############################## PRE ##############################

  before_all do
    update_fastlane
    import_shared_fastfile
  end

  ######################### CERTIFICATES ##########################

  desc "Recreate the provisioning profiles so you can deploy to your device, release on fabric and push to app store"
  lane :renew_certificates do
    app_identifiers = [ENV['DEVELOPMENT_APP_IDENTIFIER'], ENV['STAGING_APP_IDENTIFIER'], ENV['PRODUCTION_APP_IDENTIFIER'], ENV['TODAY_EXTENSION_IDENTIFIER']]
    types = ["development", "adhoc", "appstore"]

    app_identifiers.each { |app_identifier|
      types.each { |type|
        remove_provisioning_profile(app_identifier: app_identifier, type: type)
        match(app_identifier: app_identifier, type: type, force: true)
      }
    }
  end

  desc "Fetches the provisioning profiles so you can deploy to your device, release on fabric and push to app store"
  lane :fetch_certificates do
    app_identifiers = [ENV['DEVELOPMENT_APP_IDENTIFIER'], ENV['STAGING_APP_IDENTIFIER'], ENV['PRODUCTION_APP_IDENTIFIER'], ENV['TODAY_EXTENSION_IDENTIFIER']]
    types = ["development", "adhoc", "appstore"]

    app_identifiers.each { |app_identifier|
      types.each { |type|
        remove_provisioning_profile(app_identifier: app_identifier, type: type)
        match(app_identifier: app_identifier, type: type, readonly: true)
      }
    }
  end

  ######################### FABRIC ##########################

  desc "Uploads staging build to Fabric"
  lane :fabric_development do
    before_build

    scheme = ENV['DEVELOPMENT_APP_SCHEME']

    run_tests(
      scheme: scheme
    )

    upcoming_notes = get_upcoming_notes

    fabric(
      scheme: scheme,
      app_identifier: ENV['DEVELOPMENT_APP_IDENTIFIER'],
      crashlytics_api_token: ENV['CRASHLYTICS_API_TOKEN'],
      crashlytics_build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      crashlytics_group: ENV['CRASHLYTICS_NIGHT_BUILDS_GROUP'],
      notes: upcoming_notes
    )
  end

  desc "Uploads staging build to Fabric"
  lane :fabric_staging do
    before_build

    scheme = ENV['STAGING_APP_SCHEME']

    run_tests(
      scheme: scheme
    )

    upcoming_notes = get_upcoming_notes

    fabric(
      scheme: scheme,
      app_identifier: ENV['STAGING_APP_IDENTIFIER'],
      crashlytics_api_token: ENV['CRASHLYTICS_API_TOKEN'],
      crashlytics_build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      crashlytics_group: ENV['CRASHLYTICS_NIGHT_BUILDS_GROUP'],
      notes: upcoming_notes
    )
  end

  desc "Upload production build to Fabric"
  lane :fabric_production do
    before_build

    scheme = ENV['PRODUCTION_APP_SCHEME']

    run_tests(
      scheme: scheme
    )

    upcoming_notes = get_upcoming_notes

    fabric(
      scheme: scheme,
      app_identifier: ENV['PRODUCTION_APP_IDENTIFIER'],
      crashlytics_api_token: ENV['CRASHLYTICS_API_TOKEN'],
      crashlytics_build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
      crashlytics_group: ENV['CRASHLYTICS_NIGHT_BUILDS_GROUP'],
      notes: upcoming_notes
    )
  end

  desc "Upload production, staging and development build to Fabric"
  lane :fabric_all do
    before_build
    upcoming_notes = get_upcoming_notes
    parameters = [
      {scheme: ENV['DEVELOPMENT_APP_SCHEME'], app_identifier: ENV['DEVELOPMENT_APP_IDENTIFIER']},
      {scheme: ENV['STAGING_APP_SCHEME'], app_identifier: ENV['STAGING_APP_IDENTIFIER']},
      {scheme: ENV['PRODUCTION_APP_SCHEME'], app_identifier: ENV['PRODUCTION_APP_IDENTIFIER']},
    ]
    parameters.each do |parameter|
      scheme = parameter[:scheme]
      app_identifier = parameter[:app_identifier]
      run_tests(
        scheme: scheme
      )
      fabric(
        scheme: scheme,
        app_identifier: app_identifier,
        crashlytics_api_token: ENV['CRASHLYTICS_API_TOKEN'],
        crashlytics_build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
        crashlytics_group: ENV['CRASHLYTICS_NIGHT_BUILDS_GROUP'],
        notes: upcoming_notes
      )
    end
  end

  ######################### RELEASE ##########################

  desc "Creates a tag for new version and release on GitHub.
        Uploads production to Fabric"
  lane :prerelease do
    before_build
    prepare_release
    fabric_all
  end

  desc "Makes final commit for the upcoming release on GitHub.
        Moves upcoming version to the releases.
        Uploads production to App Store.
        Finalizes current release
        Setups next release"
  lane :release do
    before_build

    prepare_release
    upcoming_version = get_upcoming_version

    match(
      app_identifier: ENV['PRODUCTION_APP_IDENTIFIER'],
      type: "appstore",
      readonly: true
    )

    match(
      app_identifier: ENV['TODAY_EXTENSION_IDENTIFIER'],
      type: "appstore",
      readonly: true
    )

    build(
      scheme: ENV['PRODUCTION_APP_SCHEME'],
      configuration: "Release",
      export_method: "app-store"
    )

    upload_to_appstore(
      version: upcoming_version
    )

    put_upcoming_to_releases

    git_checkout_branch(
      destination_branch: ENV['GITHUB_DEVELOP_BRANCH']
    )

    setup_new_release(
      develop_branch: ENV['GITHUB_DEVELOP_BRANCH'],
      xcodeproject: ENV['XCODEPROJECT'],
      github_remote: ENV['GITHUB_REMOTE']
    )
  end

  lane :run_tests do |options|
    scheme = options[:scheme]
    all_devices = options[:all_devices]

    if all_devices
      scan(
        scheme: scheme,
        clean: true,
        code_coverage: true,
        skip_slack: true,
        destination: "platform=iOS Simulator,name=iPhone 6 Plus,OS=9.3' -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -destination 'platform=iOS Simulator,name=iPhone 5s,OS=9.3"
      )
    else
      scan(
        scheme: scheme,
        clean: true,
        code_coverage: true,
        skip_slack: true
      )
    end
  end

  ######################### PRIVATE LANES ##########################
  desc "Ensures git status is clean
        Increments build number"
  private_lane :before_build do
    ensure_git_status_clean
    cocoapods

    build_number = get_build_number
    increment_build_number(
      build_number: (build_number.to_i + 1).to_s
    )
    commit_version_bump
  end

  desc "Creates a tag for new version and create a release on GitHub."
  private_lane :prepare_release do
    release_branch = ENV['GITHUB_RELEASE_BRANCH']
    remote = ENV['GITHUB_REMOTE']

    ensure_git_branch(
      branch: release_branch
    )

    run_tests(
      scheme: ENV['PRODUCTION_APP_SCHEME'],
      all_devices: true
    )

    upcoming_notes =  get_upcoming_notes
    upcoming_version = get_upcoming_version
    release_name = "APP_STORE_#{upcoming_version}"
    tag_name = "APP_STORE_#{upcoming_version}"

    git_add_or_update_tag(
      tag_name: tag_name,
      remote: remote,
      branch: release_branch
    )

    set_or_update_github_release(
      release_name: release_name,
      repository_name: ENV['GITHUB_REPOSITORY'],
      description: upcoming_notes,
      tag_name: tag_name,
      api_token: ENV['CONICHI_CI_GITHUB_TOKEN'],
      upload_asset: nil
    )

    push_to_git_remote(
      remote: remote,
      local_branch: release_branch,
      remote_branch: release_branch
    )
  end

  desc "Uploads the ipa to Fabric."
  private_lane :fabric do |options|
    scheme = options[:scheme]
    app_identifier = options[:app_identifier]
    crashlytics_api_token = options[:crashlytics_api_token]
    crashlytics_build_secret = options[:crashlytics_build_secret]
    crashlytics_group = options[:crashlytics_group]
    notes = options[:notes]

    match(
      app_identifier: app_identifier,
      type: "adhoc",
      readonly: true
    )

    match(
      app_identifier: ENV['TODAY_EXTENSION_IDENTIFIER'],
      type: "adhoc",
      readonly: true
    )

    build(
      scheme: scheme,
      configuration: "Prerelease",
      export_method: "ad-hoc"
    )

    crashlytics(
      ipa_path: ENV['IPA_FILE_PATH'],
      groups: [crashlytics_group],
      api_token: crashlytics_api_token,
      build_secret: crashlytics_build_secret,
      notes: notes
    )
  end

  ######################### PRIVATE UTILITIES ##########################

  private_lane :import_shared_fastfile do
    import_from_git(
      url: "git@github.com:#{ENV['GITHUB_IOS_TEAM_REPOSITORY']}",
      branch: 'HEAD',
      path: 'fastlane/Fastfile'
    )
  end

  lane :upload_to_appstore do |options|
    version = options[:version]
    deliver(
      ipa: "../ios-guest.ipa",
      automatic_release: false,
      submit_for_review: false,
      skip_metadata: true,
      skip_screenshots: true,
      app_version: "1.9.5",
      force: true
    )
  end

  lane :build do |options|
    scheme = options[:scheme]
    configuration = options[:configuration]
    export_method = options[:export_method]

    gym(
      export_method: export_method,
      scheme: scheme,
      clean: true,
      include_bitcode: false,
      workspace: "ios-guest.xcworkspace",
      output_directory: ipa_directory,
      output_name: ipa_name,
      xcargs: "ARCHIVE=YES, ENABLE_BITCODE=NO",
      configuration: configuration
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.7  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                      | Version | Update-Status |
| ------------------------------------------- | ------- | ------------- |
| fastlane-plugin-remove_provisioning_profile | 1.0.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.0.0        |
| executable-hooks                            | 1.3.2        |
| bundler-unload                              | 1.0.2        |
| rubygems-bundler                            | 1.4.4        |
| bundler                                     | 1.13.7       |
| io-console                                  | 0.4.5        |
| CFPropertyList                              | 2.3.5        |
| i18n                                        | 0.8.1        |
| minitest                                    | 5.10.1       |
| thread_safe                                 | 0.3.6        |
| tzinfo                                      | 1.2.3        |
| activesupport                               | 4.2.8        |
| public_suffix                               | 2.0.5        |
| addressable                                 | 2.5.1        |
| babosa                                      | 1.0.2        |
| claide                                      | 1.0.1        |
| colored2                                    | 3.1.2        |
| cork                                        | 0.3.0        |
| nap                                         | 1.1.0        |
| open4                                       | 1.3.4        |
| claide-plugins                              | 0.9.2        |
| clamp                                       | 0.6.5        |
| fuzzy_match                                 | 2.0.4        |
| cocoapods-core                              | 1.2.1        |
| cocoapods-deintegrate                       | 1.0.1        |
| cocoapods-downloader                        | 1.1.3        |
| cocoapods-plugins                           | 1.0.0        |
| cocoapods-search                            | 1.0.0        |
| cocoapods-stats                             | 1.0.0        |
| netrc                                       | 0.7.8        |
| cocoapods-trunk                             | 1.2.0        |
| cocoapods-try                               | 1.1.0        |
| escape                                      | 0.0.4        |
| fourflusher                                 | 2.0.1        |
| gh_inspector                                | 1.0.3        |
| molinillo                                   | 0.5.7        |
| ruby-macho                                  | 1.1.0        |
| nanaimo                                     | 0.2.3        |
| xcodeproj                                   | 1.4.4        |
| cocoapods                                   | 1.2.1        |
| colored                                     | 1.2          |
| highline                                    | 1.7.8        |
| commander-fastlane                          | 4.4.4        |
| multipart-post                              | 2.0.0        |
| faraday                                     | 0.12.1       |
| faraday-http-cache                          | 1.3.1        |
| git                                         | 1.3.0        |
| kramdown                                    | 1.13.2       |
| sawyer                                      | 0.8.1        |
| octokit                                     | 4.7.0        |
| unicode-display_width                       | 1.1.3        |
| terminal-table                              | 1.7.3        |
| danger                                      | 5.1.1        |
| ox                                          | 2.4.13       |
| danger-junit                                | 0.7.3        |
| danger-plugin-api                           | 1.0.0        |
| mini_portile2                               | 2.1.0        |
| nokogiri                                    | 1.7.1        |
| slather                                     | 2.4.1        |
| danger-slather                              | 0.0.6        |
| unf_ext                                     | 0.0.7.4      |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20170404 |
| dotenv                                      | 2.2.1        |
| excon                                       | 0.55.0       |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| faraday_middleware                          | 0.11.0.1     |
| fastimage                                   | 2.1.0        |
| jwt                                         | 1.5.6        |
| little-plugger                              | 1.1.4        |
| multi_json                                  | 1.12.1       |
| logging                                     | 2.2.2        |
| memoist                                     | 0.15.0       |
| os                                          | 0.9.6        |
| signet                                      | 0.7.3        |
| googleauth                                  | 0.5.1        |
| httpclient                                  | 2.8.3        |
| hurley                                      | 0.2          |
| mime-types-data                             | 3.2016.0521  |
| mime-types                                  | 3.1          |
| uber                                        | 0.0.15       |
| representable                               | 2.3.0        |
| retriable                                   | 2.1.0        |
| google-api-client                           | 0.9.28       |
| json                                        | 2.1.0        |
| mini_magick                                 | 4.5.1        |
| multi_xml                                   | 0.6.0        |
| plist                                       | 3.3.0        |
| rubyzip                                     | 1.2.1        |
| security                                    | 0.1.3        |
| slack-notifier                              | 1.5.1        |
| terminal-notifier                           | 1.7.1        |
| tty-screen                                  | 0.5.0        |
| word_wrap                                   | 1.0.0        |
| rouge                                       | 2.0.7        |
| xcpretty                                    | 0.2.7        |
| xcpretty-travis-formatter                   | 0.0.4        |
| fastlane-plugin-remove_provisioning_profile | 1.0.3        |
</details>

*generated on:* **2017-05-03**
</details>

**Comment by KrauseFx** [comment]
Sounds like a great idea. Is that something you'd want to work on? I see you already contributed multiple patches and improvements to fastlane 👍

**Comment by Antondomashnev** [comment]
Hey @KrauseFx, sure, I would love to contribute the improvement, but not sure how fast I can prepare the PR.

**Comment by KrauseFx** [comment]
Cool, no worries 👍

**Comment by mvayngrib** [comment]
it would also be good to have an option to ignore untracked files

**Comment by Antondomashnev** [comment]
> it would also be good to have an option to ignore untracked files

@mvayngrib to my mind that could lead to misalignment with the `ensure_git_status_clean` name and could make it not as self-descriptive as it is right now. What is the main use case to ignore files?

**Comment by mvayngrib** [comment]
@Antondomashnev sure, and i guess my suggestion is only for people (like me) that are sometimes lazy about adding things to .gitignore or .git/info/exclude , so maybe we shouldn't encourage that

**Comment by Antondomashnev** [comment]
I'm going to close the issue as the PR is merged. @mvayngrib I think even if you have a doubt about whether it makes sense to have the option to ignore untracked files or not you can open an issue and discuss with other contributors and members 😄
