### ISSUE TITLE
Running pilot and deliver together

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#9052]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is there a way to run `pilot` and `deliver` together in a `lane`? I want to submit the build for TestFlight distribution and same build for App Store review.

**Comment by PetrosIchor** [comment]
Essentially they are uploaded to the same place, so you can't sent 2 of the same build.

However, you can use one to deliver the app and the other to take an action on that build with a skip_upload option.

That said, apple has a processing time for builds where you can't do tasks until it's complete. That might cause disruptions in your CI flow

**Comment by RishabhTayal** [comment]
Will try with skip upload option. We are waiting for processing time in Fastlane.
