### ISSUE TITLE
unable to get fastlane supply init to work

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#9058]
### New Issue Checklist

- [X ] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]
```bash
%fastlane supply init --verbose -j /Users/vamsee/Development/OnKore/onkore-android/fastlane/Google-Play-Android-Developer-8b96c0a10848.json -p com.onkore.BachelorFantasy
[15:48:54]: Seems like launching fastlane takes a while
[15:48:54]: fastlane detected a Gemfile in this directory
[15:48:54]: however it seems like you don't use `bundle exec`
[15:48:54]: to launch fastlane faster, please use
[15:48:54]:
[15:48:54]: $ bundle exec fastlane supply init --verbose -j /Users/vamsee/Development/OnKore/onkore-android/fastlane/Google-Play-Android-Developer-8b96c0a10848.json -p com.onkore.BachelorFantasy
[15:48:54]: For more information, check out https://guides.cocoapods.org/using/a-gemfile.html
DEBUG [2017-05-03 15:48:56.30]: Fetching a new access token from Google...

Looking for related GitHub issues on fastlane/fastlane...
Search query: Unauthorized
```

Running with bundle gives the same failure but does not print the message about 'Fetching a new access token ...'.  Fastlane working well for our iOS apps. Trying to use it for our our upcoming Android apps. 

Also `--capture_output` does not work  (says invalid_option). Neither does `--verbose` (no verbose output printed). 

Setup the json key file using these instructions. https://github.com/fastlane/fastlane/tree/master/supply#setup

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.0                          |
| Installation Source         | ~/Software/ruby/bin/fastlane                |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1/lib            |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.8  | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                         | Version      |
| ------------------------------------------- | ------------ |
| did_you_mean                                | 1.0.2        |
| slack-notifier                              | 1.5.1        |
| claide                                      | 1.0.1        |
| colored2                                    | 3.1.2        |
| nanaimo                                     | 0.2.3        |
| xcodeproj                                   | 1.4.4        |
| terminal-notifier                           | 1.7.1        |
| multipart-post                              | 2.0.0        |
| word_wrap                                   | 1.0.0        |
| tty-screen                                  | 0.5.0        |
| babosa                                      | 1.0.2        |
| colored                                     | 1.2          |
| highline                                    | 1.7.8        |
| commander-fastlane                          | 4.4.4        |
| http-cookie                                 | 1.0.3        |
| faraday-cookie_jar                          | 0.0.6        |
| mini_magick                                 | 4.5.1        |
| security                                    | 0.1.3        |
| xcpretty-travis-formatter                   | 0.0.4        |
| json                                        | 2.1.0        |
| io-console                                  | 0.4.6        |
| excon                                       | 0.55.0       |
| rubyzip                                     | 1.2.1        |
| plist                                       | 3.3.0        |
| faraday                                     | 0.12.1       |
| faraday_middleware                          | 0.11.0.1     |
| unf                                         | 0.1.4        |
| domain_name                                 | 0.5.20170404 |
| jwt                                         | 1.5.6        |
| memoist                                     | 0.15.0       |
| os                                          | 0.9.6        |
| signet                                      | 0.7.3        |
| googleauth                                  | 0.5.1        |
| uber                                        | 0.0.15       |
| representable                               | 2.3.0        |
| retriable                                   | 2.1.0        |
| hurley                                      | 0.2          |
| google-api-client                           | 0.9.28       |
| fastimage                                   | 2.1.0        |
| bundler                                     | 1.14.6       |
| terminal-table                              | 1.7.3        |
| unicode-display_width                       | 1.1.3        |
| fastlane-plugin-upload_symbols_to_new_relic | 0.1.1        |
| fastlane-plugin-appicon                     | 0.6.0        |
</details>

*generated on:* **2017-05-03**
</details>

**Comment by KrauseFx** [comment]
The error message indicates that your access token doesn't have the permission to access your apps on Google play. Could you revoke this one, and try to create a new one to ensure everything's valid?

**Comment by lakamsani** [comment]
Hi, I missed steps 12-14 in the setup instructions. That was the problem. We can close this.
