### ISSUE TITLE
Added push notification entitlement, won't sign

### ISSUE THREAD

**Issue by weitzel926** [fastlane/fastlane#9059]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a project with two targets.  The two targets each push two different apps with two different app IDs tied to two different iTunes accounts.  This was working all fine until we flipped the Push Notification entitlement on the secondary app (app2).  It now won't sign.  

After researching other issues, it appears that the entitlements are no longer included in the provisioning profile for Xcode 8.  I thought this would be simply a case of doing a nuke and regenerating the certificates via match.

The portion of my fastfile that does this:

desc "Bootstrap just App2 certs"
  lane :bootstrap_App2_certs do
    match(git_branch: "App2", type: "development", app_identifier:"com.app.app1", force_for_new_devices: true, team_id: "TEAM2ID")
    match(git_branch: "App2", type: "appstore", app_identifier:"com.app.app1", force_for_new_devices: true, team_id: "TEAM2ID")
    match(git_branch: "App2", type: "adhoc", app_identifier:["com.app.app1production", "com.app.app1staging"], force_for_new_devices: true, team_id: "TEAM2ID")
  end 

This runs fine.  However, when I try to do an action that signs the app, I get this:

❌  Provisioning profile "match AdHoc com.app.App2" doesn't support the Data Protection capability.
❌  Provisioning profile "match AdHoc com.app.App2" doesn't include the com.apple.developer.default-data-protection entitlement.
❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'

The other app had the entitlement before xcode 8.  We have not had problems with it.  So I'm fairly certain this has to do with adding the entitlement.  I checked, and we do have separate .entitlement files for each target.  The contents of those files make sense.  Likewise, I checked the project settings and each target appears to be pointing to the correct entitlement file.  

Likewise, in the Capabilities tab for the target:

Push notification has an error saying "add the push notifications feature to your app id".  The data protection one shows no error.  I believe data protection was flipped on before xcode 8, but I can't be sure.  

Is this an obvious issue I'm oblivious to?  I'm omitting our giant full fast file for the time being.

**Comment by KrauseFx** [comment]
Hey @weitzel926, I don't know enough about data protection myself to be able to help you. If you create those profiles manually, does it work then?

**Comment by weitzel926** [comment]
@KrauseFx Thanks.  So, it turns out that I got burned by app IDs spread across multiple accounts.  When you flip an entitlement in Xcode, you must likewise flip it in every app id on Itunes that uses that target.  So, this is not a fastlane issue.  Thanks!

**Comment by KrauseFx** [comment]
Great to hear 👍
