### ISSUE TITLE
Syntax error in Fastfile should print to the command line

### ISSUE THREAD

**Issue by samgro** [fastlane/fastlane#906]
I had a basic syntax error in my Fastfile with crash reporting on. As a new user to Fastlane, it seemed like a "crash" would be a bug in Fastlane itself, not in my Fastfile. Ideally a syntax error in the Fastfile itself should always get printed to the command line.

Sentry: 63463b0d193fdd5efd340313ea19f71f

**Comment by Rking788** [comment]
Since ruby is an interpreted language and depending on the type of syntax error you have (misspelled command vs. invalid argument) this may be difficult to accomplish.

**Comment by KrauseFx** [comment]
@samgro Thanks for the feedback, I completely agree. I'm currently working on an improved error output system: https://twitter.com/KrauseFx/status/676190970820497408

I'll close this issue for now, expect some great changes over the next weeks and months :+1:
