### ISSUE TITLE
Broken Pipe after uploading to itunesconnect marks build as failure

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#9060]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The build is fine and the upload to itunesconnect finishes with success. However, some after upload task requires a connection and the connection was droped in the meantime (Broken pipe error).

This task is then marking the build as failed when it shouldn't (it should basically be able to reopen the connection because the file upload can take too much time and the "session" may expire in between - resulting in the same 'Broken pipe' error).

This is just my assumptions on two of the possible causes.

Subsequent builds will fail because the binary was already sent sucessfully and so it's marked as a duplicate.

It would be nice to have the option in this case to mark duplicated itunesconnect binaries as a warning and not as an error (and not trigger the broken build, but just an unstable one on jenkins).

##### Complete output when running fastlane, including the stack trace and command used

```
[10:32:18]: Making sure the latest version on iTunes Connect matches '1.32' from the ipa file...
[10:32:21]: '1.32' is the latest version on iTunes Connect
[10:32:25]: Uploading binary to iTunes Connect
[10:32:25]: Going to upload updated app to iTunes Connect
[10:32:25]: This might take a few minutes. Please don't interrupt the script.
[10:34:31]: [Transporter Warning Output]: WARNING ITMS-90703: "Deprecated Xcode Build. Due to resolved app archives issues, we will be deprecating Xcode 8.3 on May 10, 2017, at which time app archives built with 8.3 will no longer be accepted by the App Store. Download Xcode 8.3.2 or newer, rebuild your app and resubmit."

[10:34:31]: iTunes Transporter successfully finished its job
[10:34:31]: WARNING ITMS-90703: "Deprecated Xcode Build. Due to resolved app archives issues, we will be deprecating Xcode 8.3 on May 10, 2017, at which time app archives built with 8.3 will no longer be accepted by the App Store. Download Xcode 8.3.2 or newer, rebuild your app and resubmit."

[10:34:31]: --------------------------------------------------------------------
[10:34:31]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[10:34:31]: --------------------------------------------------------------------
[10:34:31]: Finished the upload to iTunes Connect
[10:34:31]: --------------------
[10:34:31]: --- Step: hockey ---
[10:34:31]: --------------------
[10:34:31]: Starting with file(s) upload to HockeyApp... this could take some time.
[10:34:32]: Error: Broken pipe
+--------------------+-----------------------------------------------------------------------------+
|                                           Lane Context                                           |
+--------------------+-----------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                         |
| PLATFORM_NAME      | ios                                                                         |
| LANE_NAME          | ios store                                                                   |
| SIGH_PROFILE_TYPE  | app-store                                                                   |
| IPA_OUTPUT_PATH    | /Users/jenkins/FSRoot/workspace/Platopus_Store/build/#my-app#-Store.ipa     |
| DSYM_OUTPUT_PATH   | /Users/jenkins/FSRoot/workspace/Platopus_Store/build/#my-app#-Store.app.... |
| XCODEBUILD_ARCHIVE | /Users/jenkins/Library/Developer/Xcode/Archives/2017-05-04/#my-app#-Stor... |
+--------------------+-----------------------------------------------------------------------------+
[10:34:32]: Broken pipe

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 26          |
| 4    | gym                                 | 201         |
| 5    | deliver                             | 137         |
| 💥    | hockey                              | 0           |
+------+-------------------------------------+-------------+

[10:34:32]: fastlane finished with errors
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

#select xcode version
#xcversion(version: "8.1") # Selects Xcode 8.1.0

#xcode_select "/Applications/Xcode.app"

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Create a new Alpha Build"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: '#team#',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: '#my-app#',
      export_method: 'ad-hoc',
      configuration: 'Alpha',
      output_directory: './build',
      output_name: '#my-app#-Alpha.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )
      
    # pilot
    hockey(
      api_token: '#token#',
      public_identifier: '#token#',
      ipa: 'build/#my-app#-Alpha.ipa',
      notify: '1',
      status: '2',
      release_type: '2',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Create a new Beta Build"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(
      type: 'adhoc',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: '#team#',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: '#my-app#',
      export_method: 'ad-hoc',
      configuration: 'Beta',
      output_directory: './build',
      output_name: '#my-app#-Beta.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )

    hockey(
      api_token: '#token#',
      public_identifier: '#token#',
      ipa: 'build/#my-app#-Beta.ipa',
      notify: '1',
      status: '2',
      release_type: '0',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )


    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

  end
 
  desc "Create a new Store Build"
  desc "This will also make sure the profile is up to date"
  lane :store do
    match(
      type: 'appstore',
      team_id: CredentialsManager::AppfileConfig.try_fetch_value(:team_id),
      team_name: '#team#',
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    # snapshot

    gym(
      scheme: '#my-app#',
      export_method: 'app-store',
      configuration: 'Store',
      output_directory: './build',
      output_name: '#my-app#-Store.ipa',
      include_symbols:false,
      include_bitcode:false,
      silent:true
    )

    deliver(
      skip_metadata: true, 
      skip_screenshots: true, 
      submit_for_review: false, 
      force: true,
      username: '#dev-email#'
    )
    # frameit

    # pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)

    hockey(
      api_token: '#token#',
      public_identifier:  '#token#',
      ipa: 'build/#my-app#-Store.ipa',
      notify: '1',
      status: '2',
      release_type: '1',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )


  end

  # You can define as many lanes as you want

  after_all do |lane|
    #hockey

    puts "All done successfully..."
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|

    puts "Error: " + exception.message

    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "#dev-email#" # Your Apple email address
team_id "#team-id#"  # Developer Portal Team ID

for_lane :test do
    app_identifier 'com.example.#my-app#-alpha'
end

for_lane :alpha do
    app_identifier 'com.example.#my-app#-alpha'
end

for_lane :beta do
    app_identifier 'com.example.#my-app#-beta'
end

for_lane :store do
    app_identifier 'com.example.#my-app#'
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.8  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
</details>

*generated on:* **2017-05-04**
</details>

**Comment by lferro9000** [comment]
Updated the whole stack to latest versions and same thing happens.

**Comment by yamkay** [comment]
I am also facing this issue.

**Comment by irshadpc** [comment]
I have experienced the same issue

**Comment by ohayon** [comment]
Hey @lferro9000, I'm a bit confused about the description of the issue. It looks to me like the connection is getting dropped during the upload to HockeyApp. So the build is not getting marked as failed, it is just the upload step that is failing. 

> Subsequent builds will fail because the binary was already sent sucessfully and so it's marked as a duplicate.

Do you mean that if you run the lane again it does not upload to iTunesConnect successfully because the version is the same? 

> It would be nice to have the option in this case to mark duplicated itunesconnect binaries as a warning and not as an error (and not trigger the broken build, but just an unstable one on jenkins).

I'm not totally sure what you mean here either, but what you can do is programmatically check to see if there is already an `ipa` at the path you want to upload from and if it already exists, you can skip the `gym` step. OR another option would be you can separate your calls to `hockey` into another lane that you can reference from the current lanes, and then if you need to call it again because the connection failed, you could just execute that lane by itself and not worry about `gym` making another build and trying to upload it.

**Comment by lferro9000** [comment]
Do you mean that if you run the lane again it does not upload to iTunesConnect successfully because the version is the same?

Yes. I know i can work around this in other ways, but would be nice if the "error" was downgraded to "warning" to allow the build to be marked as unstable instead of broken.

**Comment by KrauseFx** [comment]
Could you try to use the new Microsoft plugin? https://github.com/Microsoft/fastlane-plugin-mobile_center
