### ISSUE TITLE
How to document a lane? Is there a better mechanism than `desc "some description here"`

### ISSUE THREAD

**Issue by bsarrazin** [fastlane/fastlane#9061]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is there a mechanism in place so that we can use `--help` at the end of the lane call in order to see what options can be passed?

For example:

```ruby
lane :something do |options|
  flag1 = options[:flag1]
  string2 = options[:string2]
end
```

The lane above would be called as such:
```zsh
$ bundle exec fastlane something --help
```

And I'd want to see something like:

```
Options for build:
    flag1, BOOL This flag is used to determine something or other
    string2, STRING This is the name of the project or something
```

The only way I've been able to do this is by using some `desc` commands above the lane. but this is just messy, has to be maintained manually and can only be viewed when you don't pass a lane to the fastlane command:
```ruby
desc "    flag1, BOOL This flag is used to determine something or other"
desc "    string2, STRING This is the name of the project or something"
lane :something do |options|
  flag1 = options[:flag1]
  string2 = options[:string2]
end
```

**Comment by KrauseFx** [comment]
Great idea @bsarrazin, thanks for sharing this. For now that's not something we plan on building. If you feel like it, you can contribute to _fastlane_ add add this functionality, however it is important to not add any complexity for the user 👍
