### ISSUE TITLE
How to release build after has been approved and submission status.

### ISSUE THREAD

**Issue by arjpaiva** [fastlane/fastlane#9065]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hi, I'm new to fastlane and I have been trying to find out how to release a build to live after it has been approved by Apple. The only information i've found so far is to use the key: automatic_release when submitting for review but I need to be able to do this step manually (as in, specify a lane for this). Is there any way to do this?

Also, is there any way to know the current status of a build that has been submitted for review? 

Thank you.

**Comment by KrauseFx** [comment]
I don't think that's currently possible with _fastlane_. Only setting the `automatic _release` to true before submitting your app for review.

> Also, is there any way to know the current status of a build that has been submitted for review?

You can do that using [spaceship](https://spaceship.airforce)

**Comment by arjpaiva** [comment]
Thank you Krause!

**Comment by KrauseFx** [comment]
Can we close this issue?

**Comment by arjpaiva** [comment]
Is there any plan on adding the release to live feature into fastlane in the near future?

Thank you.

**Comment by KrauseFx** [comment]
Let's leave this issue open and see if other people ask for this feature. If others find it useful we can build it 👍  Or maybe someone wants to submit a PR

**Comment by NxSoftware** [comment]
I don't know for sure, but after a bit of prodding around the code I found a release method in Spaceship:

https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/tunes/app_version.rb#L599

I can't find any docs for it though so can't confirm whether this does what you want.
