### ISSUE TITLE
fastlane pilot upload crashes with "invalid byte sequence in UTF-8" 

### ISSUE THREAD

**Issue by IcyEagle** [fastlane/fastlane#9066]
Hi!

I'm trying to upload an application to AppStore with:
`fastlane pilot upload --app_identifier "com.myapp" --skip_submission`
 but have the error "_invalid byte sequence in UTF-8_" just after authentication.

I tried to reproduce the same on the laptop (MacOS) and it worked fine even with out-of-date fastlane version (2.1.3). Is it possible to upload IPA files to AppStore from Ubuntu at all? 

Thanks! 

### Issue Description

fastlane pilot upload --app_identifier "com.myapp.1" --skip_submission --verbose
Successfully loaded Appfile at path '/tmp/com.myapp.1/fastlane/Appfile'
- app_identifier: 'com.myapp'
- apple_id: 'email@gmail.com'
- team_id: 'BUPP5XXXX'

Password (for email@gmail.com): **********
Loading session from '/root/.fastlane/spaceship/email@gmail.com/cookie'
Looking for iTunes Connect Team with ID 118153000
INFO [2017-05-04 15:35:50.26]: Login successful
DEBUG [2017-05-04 15:35:50.26]: App identifier (com.myapp.1)
INFO [2017-05-04 15:35:50.91]: Ready to upload new build to TestFlight (App: 1233126000)...
WARN [2017-05-04 15:35:50.94]: -------------
WARN [2017-05-04 15:35:50.94]: pilot crashed
WARN [2017-05-04 15:35:50.94]: -------------
ERROR [2017-05-04 15:35:50.94]: Unfortunately the TestFlight update from 11th April 2017 changed
ERROR [2017-05-04 15:35:50.94]: the way Testers, Groups, and Builds are managed on iTunesConnect.
ERROR [2017-05-04 15:35:50.94]: We have already fixed a number of features including submitting
ERROR [2017-05-04 15:35:50.94]: builds for testing, adding and removing testers from groups, and
ERROR [2017-05-04 15:35:50.94]: waiting for builds to process.
ERROR [2017-05-04 15:35:50.94]: 
ERROR [2017-05-04 15:35:50.94]: Please open an issue on https://github.com/fastlane/fastlane/issues
ERROR [2017-05-04 15:35:50.94]: if you believe this failure is the result of a bug in _pilot_ and we
ERROR [2017-05-04 15:35:50.94]: will be happy to look into this further.
ERROR [2017-05-04 15:35:50.94]: 
ERROR [2017-05-04 15:35:50.94]: Please stay tuned for more updates from _fastlane_ as we fix more issues!
ERROR [2017-05-04 15:35:50.94]: 

Looking for related GitHub issues on fastlane/fastlane...
Search query: invalid byte sequence in UTF-8

/usr/local/rvm/gems/ruby-2.4.0/gems/plist-3.3.0/lib/plist/parser.rb:91:in `scan': [!] invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/rvm/gems/ruby-2.4.0/gems/plist-3.3.0/lib/plist/parser.rb:91:in `parse'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/plist-3.3.0/lib/plist/parser.rb:29:in `parse_xml'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:44:in `block (2 levels) in fetch_info_plist_file'
	from /usr/local/rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:37:in `block in fetch_info_plist_file'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:31:in `fetch_info_plist_file'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb:22:in `fetch_app_platform'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/pilot/lib/pilot/manager.rb:62:in `fetch_app_platform'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/pilot/lib/pilot/build_manager.rb:16:in `upload'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/pilot/lib/pilot/commands_generator.rb:60:in `block (2 levels) in run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /usr/local/rvm/gems/ruby-2.4.0/gems/fastlane-2.28.8/bin/fastlane:20:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/fastlane:22:in `load'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/fastlane:22:in `<main>'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

### Environment

| Key                         | Value                                                      |
| --------------------------- | ---------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                   |
| Ruby                        | 2.4.0                                                      |
| Bundler?                    | false                                                      |
| Git                         | git version 2.7.4                                          |
| Installation Source         | /usr/local/rvm/gems/ruby-2.4.0/bin/fastlane                |
| Host                        | Ubuntu 16.04.1 LTS debian_based stretch/sid (4.9.20-std-1) |
| Ruby Lib Dir                | /usr/local/rvm/rubies/ruby-2.4.0/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                 |
| Is contained                | false                                                      |
| Is homebrew                 | false                                                      |
| Is installed via Fabric.app | false                                                      |

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.8  | ✅ Up-To-Date  |

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.2        |

**Comment by KrauseFx** [comment]
So you're saying that this works on one mac, but doesn't on a different one?

**Comment by IcyEagle** [comment]
@KrauseFx correct. I have macOS Sierra 10.12.4 (16E195) on laptop and Ubuntu 16.04 on remote machine.

**Comment by IcyEagle** [comment]
@KrauseFx here is [my IPA](https://drive.google.com/open?id=0B-v7cOJbeXRGOTFIWEZCT3l1WXM) file which may be successfully loaded using _fastlane pilot upload_ from Mac but doesn't work when I try to do the same command on Ubuntu.

**Comment by IcyEagle** [comment]
I've found Mac-related command call in [fastlane-core](https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/ipa_file_analyser.rb#L43) component. Probably this is the root cause.

**Comment by KrauseFx** [comment]
Oh, _fastlane_ doesn't support Linux, sorry about that. There will be various tools and actions that don't properly run on Linux.

**Comment by IcyEagle** [comment]
Got it. Thanks!
