### ISSUE TITLE
[Screengrab] Issue when running on Wear API 25 emulator

### ISSUE THREAD

**Issue by ruigoncalo** [fastlane/fastlane#9067]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying Screengrab on my instrumented tests for an Android Wear 2.0 app. I'm running an Wear API 25 emulator.

I set the default screenshot strategy as UiAutomator `setDefaultScreenshotStrategy(UiAutomatorScreenshotStrategy())` at `@Before fun setUp()` method.

The first screenshot is taken, but then the following error occurs:
`java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x10000000...`

After the screenshot, it cannot launch a new activity to proceed to the next test. And the emulator freezes forever. Probably the problem is not related to screengrab but in running UIAutomator on the Wear emulator. Any help?

Thanks.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.11.6                              |
| Ruby                        | 2.3.1                                |
| Bundler?                    | false                                |
| Git                         | git version 2.10.1 (Apple Git-78)    |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane  |
| Host                        | Mac OS X 10.11.6 (15G31)             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib         |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.8  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.6        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.0        |
</details>

*generated on:* **2017-05-04**
</details>

**Comment by KrauseFx** [comment]
Hey @ruigoncalo, currently we don't support Android wear with screengrab, sorry about that.

**Comment by ruigoncalo** [comment]
I though you'd support because the device type "wear" is included:
https://github.com/fastlane/fastlane/blob/master/screengrab/lib/screengrab/options.rb#L06

But, after some debugging I found out the issue is in the `UiAutomation.takeScreenshot()`. Let's see how this can be fixed :)

Thanks
