### ISSUE TITLE
When setting up Match in Fastlane, will provisioning profile update when `readonly` is set to true when adding new device 

### ISSUE THREAD

**Issue by eman6576** [fastlane/fastlane#9068]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello,

I have a question on Fastlane behavior. I have Fastlane setup on Bitrise for deploying to Fabric and to the App store with no issues from following the setup guide for match. My question is when a new device is added, will the provisioning profile get updated even though the readonly parameter on match is set to true? I don't have output for this issue since its only a question. Thanks.

**Comment by eman6576** [comment]
Silly @fastlane-bot. Code signing is all good. 😜

**Comment by KrauseFx** [comment]
Haha, @fastlane-bot is just doing its job 😉 

It can't be updated if the readonly parameter is set. You can also use the `force_for_new_devices` option to generate a new profile when a new device is added 👍

**Comment by eman6576** [comment]
Alright, I suspected that. Because I am running on a CI server, I would have to then create a lane for updating the provisioning profile locally when adding a new device then since the CI server can't write to the repo where we store the provisioning profile and certificates then. Or is there a better way to handle this?

**Comment by KrauseFx** [comment]
Yes, that sounds correct. You can even have this be one lane, and pass `force_for_new_devices: !is_ci` which means that it's only forced on non-CI systems, and only if there is a new device 👍
