### ISSUE TITLE
Update action documentation for snapshot

### ISSUE THREAD

**Issue by patoroco** [fastlane/fastlane#907]
Hi,

snapshot action documentation (https://github.com/fastlane/fastlane/blob/master/docs/Actions.md#snapshot) is deprecated because some parameters don't exist in https://github.com/fastlane/snapshot/blob/master/lib/snapshot/options.rb

Also, some relative links in the same action-doc are deprecated too.

**Comment by KrauseFx** [comment]
Thanks, nice catch. What links are deprecated? Would you mind submitting a pull request?
