### ISSUE TITLE
Fastlane fails to create an app on iTunes Connect

### ISSUE THREAD

**Issue by umeshkadam** [fastlane/fastlane#9078]
### New Issue Checklist

- [x] Updated fastlane to the latest version - Updated
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Fastlane fails to create a new app using fastlane produce

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Dev-Deployment-Mac-mini.local (14:54):
[03:58:31]: [DevCenter] App 'com.abc.xyz' already exists, nothing to do on the Dev Center
[03:58:41]: Creating new app 'XYZ' on iTunes Connect

Looking for related GitHub issues on fastlane/fastlane...

➡️  uninitialized constant CredentialsManager::PasswordManager
    https://github.com/fastlane/fastlane/issues/7653 [closed] 11 💬
    3 weeks ago

➡️  Fastlane crashes after updating to 2.5.0 on Linux Fedora 22
    https://github.com/fastlane/fastlane/issues/7765 [closed] 12 💬
    3 weeks ago

➡️  Fastlane crashes when disabling colors
    https://github.com/fastlane/fastlane/issues/8100 [closed] 3 💬
    a day ago

and 5 more at: https://github.com/fastlane/fastlane/search?q=uninitialized%20constant%20Class::UI&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/automation/.rvm/gems/ruby-2.2.3/gems/fastlane-2.28.8/spaceship/lib/spaceship/tunes/application.rb:81:in `create!': [!] uninitialized constant Class::UI (NameError)
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/produce-2.0.0/lib/produce/itunes_connect.rb:25:in `create_new_app'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/produce-2.0.0/lib/produce/itunes_connect.rb:12:in `run'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/produce-2.0.0/lib/produce/manager.rb:8:in `start_producing'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/produce-2.0.0/lib/produce/commands_generator.rb:37:in `block (2 levels) in run'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/fastlane-2.28.8/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/produce-2.0.0/lib/produce/commands_generator.rb:135:in `run'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/produce-2.0.0/lib/produce/commands_generator.rb:12:in `start'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/fastlane-2.28.8/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/automation/.rvm/gems/ruby-2.2.3/gems/fastlane-2.28.8/bin/fastlane:20:in `<top (required)>'
	from /Users/automation/.rvm/gems/ruby-2.2.3/bin/fastlane:22:in `load'
	from /Users/automation/.rvm/gems/ruby-2.2.3/bin/fastlane:22:in `<main>'
	from /Users/automation/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/automation/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.3/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.8  | ✅ Up-To-Date  |
| deliver  | 2.0.1   | ✅ Up-To-Date  |
| produce  | 2.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.0        |
| cocoapods-deintegrate     | 1.0.0        |
| cocoapods-downloader      | 1.0.0        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.0.0        |
| cocoapods-try             | 1.0.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.1        |
| molinillo                 | 0.4.5        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.0.0        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| fastimage                 | 2.1.0        |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-05-05**
</details>

**Comment by KrauseFx** [comment]
Thanks for reporting this, I can see the problem, and will work on a fix 👍

**Comment by KrauseFx** [comment]
This will be fixed with https://github.com/fastlane/fastlane/pull/9089/files

**Comment by KrauseFx** [comment]
It seems like you're running an old version of fastlane. Can you please run `gem cleanup` and install _fastlane_ again? Make sure that `produce` isn't installed any more.
