### ISSUE TITLE
Feature Request: Add timeout to cert and sigh

### ISSUE THREAD

**Issue by puttin** [fastlane/fastlane#908]
`cert` and `sigh` sometimes hang itself when contacting to Member Center.

Add a `timeout` would be great.

**Comment by ohwutup** [comment]
thanks @puttin! this is a great idea. I am going to close this for now and mark it as a feature request, and we will update the issue when we can tackle this for a future release. Until then, if you would like to submit a PR with the change, that would be amazing :star: !

**Comment by KrauseFx** [comment]
Just to jump in here: We recently published a new version of spaceship that has improved timeout handling, have you tried it yet?

**Comment by ohwutup** [comment]
:+1:
