### ISSUE TITLE
Request: Support for Achievements and Leaderboards for both Google Play and iTunes

### ISSUE THREAD

**Issue by ndbroadbent** [fastlane/fastlane#9082]
It would be really awesome if I could update translations and images for my achievements and leaderboards in both Google Play Game Services, and Game Center on iTunes Connect.

Right not I have to open up 20 tabs to update all of these manually. This is going to get really out of hand when I start adding translations.

I found these issues:

* https://github.com/fastlane-old/deliver/issues/327
* https://github.com/fastlane-old/deliver/issues/35

Would this be difficult to implement? I'm a Ruby developer, so I can try to build this if no-one else has time. Would you be open to merging a PR with support for this? I might also look at in-app purchases.

**Comment by KrauseFx** [comment]
@ndbroadbent thanks for submitting this issue. If you have the time and experience, a PR would be awesome, I'm sure lots of people will be thankful. I don't know if the Google Play API allows to upload leaderboards, but for iTC that should be possible 👍 Check out [this doc](https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md) on how to build this.

Let us know if any questions come up.
