### ISSUE TITLE
Changelog plugin not loading

### ISSUE THREAD

**Issue by hernangonzalez** [fastlane/fastlane#9086]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am having problems using the `changelog` plugin. It just fails at load. I raised an issue here as well https://github.com/pajapro/fastlane-plugin-changelog/issues, though not sure where should I discuss about it.

Thanks!

**Comment by mfurtak** [comment]
@hernangonzalez You'll get the best help for questions about plugins by raising issues in the plugin repository like you did. :100:  I'll close this one here to make it easier for folks to find the right place to discuss 👍

**Comment by hernangonzalez** [comment]
Sure. I'll wait for help on the other issue. Thanks.

**Comment by KrauseFx** [comment]
Yes, I can confirm that this is an issue with the actual plugin, not with _fastlane_ 👍
