### ISSUE TITLE
Pass assets with custom actions from git 

### ISSUE THREAD

**Issue by SemenovAlexander** [fastlane/fastlane#909]
I've implemented simple custom action, which gathers results of multiple runs of snapshot into single html. It works fine, but now I need to use it another project, and decided to extract this action to separate git repository.
Action need one more file to work - .erb template, I've put it to the same folder with action, but it seems fastlane improrts only .rb files from git.

Is there any way to pass assets with actions as well?

**Comment by ohwutup** [comment]
Hey @SemenovAlexander! Apologies for the really slow response. I'm not totally sure I understand the issue, but if you put the erb file in another directory, you should be able to access it using relative paths from the file or the working directory. I am going to close this issue for now as it is more of a question of functionality, but please feel free to continue discussion if you'd like! :rocket:

**Comment by SemenovAlexander** [comment]
Hi @ohwutup! Thanks for response. 

Let me describe my use-case to give clear understanding. 
I have several custom actions, used across different projects, and I want to store that actions in it's own [repository](https://github.com/SemenovAlexander/fastlane_actions).

Some actions has their own assets (html files, ERB templates, etc.), and the issue is, when I add that actions using Fastlane's `import_from_git` action - only .rb files are cloned from repository, and nothing else, even if assets are placed to actions folder.

So, for now, I've ended up by manually copying updated assets each time to each new repository, that uses that actions, but it's not really nice way.

**Comment by ohwutup** [comment]
Thanks for the explanation @SemenovAlexander ! I found the culprit https://github.com/fastlane/fastlane/blob/a6641e6e4b990cbf7e421384ada0f11b21d42930/fastlane/lib/fastlane/actions/actions_helper.rb#L77 We can likely make a fix for this!

**Comment by ohwutup** [comment]
Hey @SemenovAlexander are you still having an issue with this? We just started rolling out a plugin system and it seems like these custom actions you are building would be a great fit for that!

**Comment by SemenovAlexander** [comment]
Hi @ohwutup! Wow, it's amazing news, as I still use that rough approach, described above. I've quickly checked #4873 and for sure will try to migrate my stuff to new plugin at nearest future! 
Thanks a lot for that reminder!
