### ISSUE TITLE
Supply and Screengrab can create inconsistent locale directory names in Android metadata

### ISSUE THREAD

**Issue by joshsnelling** [fastlane/fastlane#9094]
🔑
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've noticed a discrepancy between the locale directory names that are created after running `fastlane supply init` and those that are created after running `fastlane screengrab`. This only occurs with languages that have no country code in the locale name. For example, here are the resulting directory names for each tool for an app with a Google Play listing that supports Arabic, English (GB), German (DE) and Slovak:

| Language | Supply Directory Name | Screengrab Directory Name |
| - | - | - |
| Arabic  | ar | ar- |
| English (GB)  | en-GB | en-GB |
| German (DE)  | de-DE | de-DE |
| Slovak  | sk | sk- |

As you can see, the Screengrab directory names for the locales that don't contain a country code still have the dash ("-") appended to the end. This causes problems when updating existing screenshots since the original metadata that Supply created will be contained within the directory without the "-" at the end (e.g. **"ar"**), and any newly generated screenshots will be automatically placed in the directory with the "-" at the end (e.g. **"ar-"**). This inconsistency can be manually resolved, but that's not ideal if screenshots are updated with an automated job.

It looks like this can be fixed by checking the country code string in the `localeToDirName()` in `screengrab/screengrab-lib/src/main/java/tools.fastlane.screengrab/FileWritingScreenshotCallback.java:107`. I'm happy to submit a PR for this fix, but I first wanted to make sure this wasn't intentional behavior, and of course I'd like the feedback of those who are more familiar with the project on whether or not I've diagnosed this issue properly.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Screengrabfile`</summary>

```ruby
# remove the leading '#' to uncomment lines

app_package_name 'xXxXxXx'

app_apk_path 'app/build/outputs/apk/app-debug.apk'
tests_apk_path 'app/build/outputs/apk/app-debug-androidTest.apk'

locales [ 'en-US', 'ar', 'cs-CZ', 'da-DK', 'de-DE', 'el-GR', 'en-GB', 'es-419', 'es-ES', 'fr-FR', 'hi-IN', 'id', 'it-IT', 'ko-FR', 'ms', 'nl-NL', 'no-NO', 'pl-PL', 'pt-BR', 'pt-PT', 'ru-RU', 'sk', 'sv-SE', 'th', 'tr-TR', 'uk', 'zh-TW']

# clear all previously generated screenshots in your local output directory before creating new ones
clear_previous_screenshots true

# For more information about all available options run
#   screengrab --help
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.9  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-06**
</details>

**Comment by mfurtak** [comment]
Hi @joshsnelling - thanks for the great write-up. 💯  I'd be happy to review a PR for this!

**Comment by joshsnelling** [comment]
@mfurtak - PR submitted!
