### ISSUE TITLE
Upload Hosted Content for In App Purchases? 

### ISSUE THREAD

**Issue by thetomester13** [fastlane/fastlane#9100]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
This is more of a new feature request. While I can use `deliver` to upload packages for an app, or `spaceship` to create new in app purchases in iTC, I'd like to be able to upload a `.pkg` file for Apple to host my in app purchase content. 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.brillicity.alllaws" # The bundle identifier of your app
apple_id "tomershvueli@me.com"  # Your Apple email address

# You can uncomment the lines below and add your own 
# team selection in case you're in multiple teams
team_name "Tomer Shvueli"
team_id "5U298732TP"

# To select a team for iTunes Connect use
# itc_team_name "Tomer Shvueli"
# itc_team_id "5U298732TP"```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.9  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-05-07**
</details>

**Comment by KrauseFx** [comment]
Hey, thanks for letting us know about this. We'd love to have every _fastlane_ feature work for macOS apps, however we're currently focusing our time to make _fastlane_ the best tool for iOS and Android apps. Some of the features might work for macOS apps, however not all of them.

Thanks for understanding.

**Comment by thetomester13** [comment]
Hey KrauseFx, thanks for the response. I'm actually talking about in app purchases for iOS apps :)

**Comment by KrauseFx** [comment]
> This is more of a new feature request. While I can use deliver to upload packages for an app, or spaceship to create new in app purchases in iTC, I'd like to be able to upload a .pkg file for Apple to host my in app purchase content.

I didn't know you could host a pkg file, isn't that used for macOS apps only?

**Comment by thetomester13** [comment]
Nope, I've been using this for non consumable IAP for my app. In my use case, Apple hosts JSON files for me that are downloaded through an in app purchases and then ingested through the app. More here: https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnectInAppPurchase_Guide/Chapters/CreatingInAppPurchaseProducts.html#//apple_ref/doc/uid/TP40013727-CH3-SW4

**Comment by KrauseFx** [comment]
Interesting. That's not something you can currently do with _fastlane_, sorry. You're actually the first one to request this, so I'll leave this issue open and we can see if other people are interested in it as well.

**Comment by thetomester13** [comment]
That sounds good, thanks for the consideration!

**Comment by thetomester13** [comment]
This feature is still absent from the feature-set that fastlane provides.
