### ISSUE TITLE
Is it possible to split one scheme into 2 simulators?

### ISSUE THREAD

**Issue by amesandy** [fastlane/fastlane#9101]
Split an Scheme into 2 simulators to run different test at the same time.

I would like to split my scheme into 2 or more simulators( same ios version) and run different test cases from same scheme at the same time.

Is it possible?

**Comment by amesandy** [comment]
fastlane version 2.22.0

**Comment by KrauseFx** [comment]
With _fastlane_ that's currently not possible. Check out [blue pill](https://github.com/linkedin/bluepill) by LinkedIn (not a fastlane tool)
