### ISSUE TITLE
It let me input passphrase when I run match on a different machine

### ISSUE THREAD

**Issue by dawnnnnn** [fastlane/fastlane#9104]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
 I run `fastlane match ...` in my personal Mac first, it completed. But I run it in my work Mac it will show follow block. I'm sure that my passphrase is right.
```
+-----------------------+----------------------------------------------------+
|                          Summary for match 2.28.9                          |
+-----------------------+----------------------------------------------------+
| type                  | adhoc                                              |
| app_identifier        | com.segcompany.client.test                       |
| readonly              | true                                               |
| git_url               | git@bkyard-git.segcompany.com:OMG/ios-cert.git |
| git_branch            | master                                             |
| username              | ios@segcompany.com                               |
| keychain_name         | login.keychain                                     |
| team_id               | XXXXXXXX                                         |
| verbose               | false                                              |
| force                 | false                                              |
| skip_confirmation     | false                                              |
| shallow_clone         | false                                              |
| force_for_new_devices | false                                              |
| skip_docs             | false                                              |
| platform              | ios                                                |
+-----------------------+----------------------------------------------------+

[16:01:32]: Cloning remote git repo...
[16:01:33]: Enter the passphrase that should be used to encrypt/decrypt your certificates
[16:01:33]: This passphrase is specific per repository and will be stored in your local keychain
[16:01:33]: Make sure to remember the password, as you'll need it when you run match on a different machine
[16:01:33]: Passphrase for Git Repo: ************
[16:04:35]: Type passphrase again: ************
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.
[16:04:38]: Enter the passphrase that should be used to encrypt/decrypt your certificates
[16:04:38]: This passphrase is specific per repository and will be stored in your local keychain
[16:04:38]: Make sure to remember the password, as you'll need it when you run match on a different machine
[16:04:38]: Passphrase for Git Repo:
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.9  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.20       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| json                      | 2.0.3        |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-05-08**
</details>

**Comment by KrauseFx** [comment]
You can read the password from your personal Mac by opening up the Keychain and searching for `match` 👍

**Comment by dawnnnnn** [comment]
@KrauseFx  Yes, I have read the password, but it still show me that is not correct. 💔

**Comment by dawnnnnn** [comment]
And if I create new git repo for match git_url, and run first in my work Mac, it show me a different infomation, like followed:


```
[15:38:53]: Verifying that the certificate and profile are still valid on the Dev Portal...
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for ios@segcompany.com): *********
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.
Could not store password in keychain
[15:39:12]: Couldn't find a valid code signing identity in the git repo for development... creating one for you now

+---------------+------------------------------------------------------+
|                       Summary for cert 2.28.9                        |
+---------------+------------------------------------------------------+
| development   | true                                                 |
| force         | true                                                 |
| username      | ios@segcompany.com                                 |
| team_id       | XXXXXXXX                                           |
| keychain_path | /Users/geminiwen/Library/Keychains/login.keychain-db |
| platform      | ios                                                  |
+---------------+------------------------------------------------------+

[15:39:12]: Starting login with user 'ios@segcompany.com'


git_url "git@bkyard-git.segcompany.com:OMG/ios-cert.git"
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
Password (for ios@segcompany.com): *********
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.
Could not store password in keychain
[15:39:21]: Successfully logged in

Looking for related GitHub issues on fastlane/fastlane...

➡️  Using Match with already existing profiles and certificates
    https://github.com/fastlane/fastlane/issues/8591 [closed] 9 💬
    4 weeks ago

➡️  match: Could not create another certificate, reached the maximum number of available certificates.
    https://github.com/fastlane/fastlane/issues/5765 [closed] 4 💬
    06 Dec 2016

➡️  How can I reuse same signing certificates on different apps?
    https://github.com/fastlane/fastlane/issues/7021 [closed] 7 💬
    13 Feb 2017

and 16 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20create%20another%20Development%20certificate,%20reached%20the%20maximum%20number%20of%20available%20Development%20certificates.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] Could not create another Development certificate, reached the maximum number of available Development certificates.
```

**Comment by KrauseFx** [comment]
```
security: SecKeychainAddInternetPassword <NULL>: The user name or passphrase you entered is not correct.
Could not store password in keychain
```
Mh, that means _fastlane_ doesn't have access to your Keychain, can you verify that

**Comment by getaaron** [comment]
@dawnnnnn On a similar issue, I had to use the _fastlane_ `unlock_keychain` action to allow passwords to to be saved. I had to unlock mine manually because macOS doesn't automatically unlock the keychain if you SSH in, or if the keychain password is different from your login password.

I passed it in as an environment variable and added this to my `Fastfile`:

```ruby
  before_all do
    unlock_keychain(path: 'login') if ENV['FL_UNLOCK_KEYCHAIN_PASSWORD']
  end
```

Then you can test if this resolves your issue by setting the variable before your command. For example:

```bash
$ FL_UNLOCK_KEYCHAIN_PASSWORD="my_password" bundle exec fastlane certs
```

(If you have a lane called `certs` which calls `match`).
