### ISSUE TITLE
New action for Mobile Center (HockeyApp)

### ISSUE THREAD

**Issue by derpixeldan** [fastlane/fastlane#9105]
With the current development of Mobile Center (the next generation of HockeyApp) we'd like to contribute a new action to fastlane. We’ve adapted the current Hockey action to meet the new requirements and target the new portal at https://mobile.azure.com.

With your commitment we'd like to do a PR for further review.

**Comment by KrauseFx** [comment]
Hey @derpixeldan,

Thanks for submitting this issue. First off, congrats on getting the Mobile Center out, looks great 🎉 

Updating the `hockey` action sounds good, however in this case, the plugin system is the way to go. Check out the [plugin docs](https://docs.fastlane.tools/plugins/create-plugin/) for a quick overview of how they work.

By publishing an official `mobile_center` fastlane plugin, you can bundle `hockey` and any actions you might want to offer (e.g. upload dSYM files from _fastlane_) in it, and have full control over it. This way, you can update your actions any time, without any reviews from our side. You can act faster and can add new actions any time.
With that, we can migrate users that use the `hockey` action over to the new plugin over the next few weeks and months 👍  I'm more than happy to help with that, to make the transition super smooth, and with almost no extra effort from the users. People who don't want to upgrade to the new `mobile_center` plugin, can still use the "old" `hockey` action with no issues.

Let me know what you think
Felix

**Comment by derpixeldan** [comment]
Hey @KrauseFx,

still in beta but we're doing our best to improve day by day!

Thanks for clarifying, our first intention was to do it the same way as for `hockey`. Moving it to a plugin sounds like the better solution and some voices just told me "you" have already chatted about this last year at WWDC.

It just takes us a tad longer to get things sorted.

Thanks,
Dan

**Comment by KrauseFx** [comment]
@derpixeldan Providing a plugin would be great, and we're more than happy to help with that. `hockey` is a one of the most popular _fastlane_ actions, so it would be great to give you and your team full control over it. If you prefer, let's start an email thread, just email me at microsoft@krausefx.com and we can go from there, and and maybe schedule a video call with the team 👍

**Comment by derpixeldan** [comment]
@KrauseFx thanks again for the help, we've released the mobile-center plugin right here https://rubygems.org/gems/fastlane-plugin-mobile_center. Let's take everything else off.
