### ISSUE TITLE
Following the #5507

### ISSUE THREAD

**Issue by benjabrons09** [fastlane/fastlane#9106]
Hi, i'm working on an Android app generator and i'm asking if you have found a way to automate the creation of an app on google store?

I'm using Supply but i need to create my apps on the store before running it...
Does someone have any ideas?

Thanks.

**Comment by KrauseFx** [comment]
Hey @benjabrons09, unfortunately that's not possible due to the API limitation of Google Play.

**Comment by benjabrons09** [comment]
Alright, thanks @KrauseFx

**Comment by KrauseFx** [comment]
I'll close this issue for now, as there is not much we can do currently.
