### ISSUE TITLE
Unable to connect to itunes connect - Environment issue

### ISSUE THREAD

**Issue by richlong** [fastlane/fastlane#9109]
### New Issue Checklist

- [/ ] Updated fastlane to the latest version
fastlane 2.28.7

- [/ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hi, hope you can help. I don't seem to be able to connect to itunes connect via fastlane, in this case using 'fastlane cert' or using a lane.

Error:

[10:59:16]: getaddrinfo: nodename nor servname provided, or not known

I'm pretty certain this is down to proxy settings as I am behind a proxy server, I have run the lane successfully while using this machine on an external network and not behind a proxy server. I need to remain on the internal network for access to our git repo.

I am setting the proxy server via export http_proxy and export https_proxy in my bash profile before running fastlane and have tested that I can access the external network using curl successfully. It could be a proxy issue or certificate issue with ruby.

I have installed using your installer but have also tried the steps on system ruby here: https://github.com/fastlane/fastlane/issues/8253 
e.g.First run rvm osx-ssl-certs update all
Then run rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local

Any help would be appreciated. Thanks.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

INFO [2017-05-08 10:49:48.83]: Starting login with user '***'
getaddrinfo: nodename nor servname provided, or not known
getaddrinfo: nodename nor servname provided, or not known
getaddrinfo: nodename nor servname provided, or not known
getaddrinfo: nodename nor servname provided, or not known
getaddrinfo: nodename nor servname provided, or not known

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Could not receive latest API key from iTunes Connect, this might be a server issue.

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Could%20not%20receive%20latest%20API%20key%20from%20iTunes%20Connect,%20this%20might%20be%20a%20server%20issue.+repo:fastlane/fastlane
ERROR [2017-05-08 10:51:01.68]: Error finding relevant GitHub issues: getaddrinfo: nodename nor servname provided, or not known
/Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:455:in `rescue in itc_service_key': [!] The request could not be completed because: (Spaceship::Client::AppleTimeoutError)
	Could not receive latest API key from iTunes Connect, this might be a server issue.
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:432:in `itc_service_key'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:395:in `block in send_shared_login_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:383:in `block in run_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:397:in `block in build_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/request.rb:26:in `block in create'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/request.rb:25:in `tap'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/request.rb:25:in `create'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:393:in `build_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:379:in `run_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/faraday-0.12.1/lib/faraday/connection.rb:186:in `post'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:619:in `block in send_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:463:in `with_retry'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:618:in `send_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:507:in `request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:394:in `send_shared_login_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:585:in `do_login'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/client.rb:119:in `login'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/spaceship/lib/spaceship/portal/spaceship.rb:82:in `login'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/cert/lib/cert/runner.rb:17:in `login'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/cert/lib/cert/runner.rb:27:in `run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/cert/lib/cert/runner.rb:6:in `launch'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/cert/lib/cert/commands_generator.rb:33:in `block (2 levels) in run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/cert/lib/cert/commands_generator.rb:51:in `run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/cert/lib/cert/commands_generator.rb:11:in `start'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.28.7/bin/fastlane:20:in `<top (required)>'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
  end

  desc "Runs all the tests"
  lane :test do
  #If running on jenkins, ensure env variable is set to target same device below
    scan(
          scheme: "in***",
          device: "iPhone 7 (10.3)"
    )
  end

  desc "Submit a new Build to iTunes connect for testflight or live app."
  desc "This will also make sure the profile is up to date"
  lane :appstore do
    
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"

    cert
    sigh

    scan(
        scheme: "in***",
        device: "iPhone 7 (10.3)"
    )
    gym(
        scheme: "in***",
        use_legacy_build_api: false,
    )
    
    # pilot
    # build = get_build_number
    # add_git_tag(
    #   grouping: "appstore-builds",
    #   prefix: "build_",
    #   build_number: build
    # )
    # increment_build_number
    # commit_version_bump
    # push_to_git_remote

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  lane :inc_build do
      increment_build_number()
  end


  # desc "Deploy a new version to the App Store"
  # lane :appstore do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.*** # The bundle identifier of your app
apple_id "rich.long@****.com" # Your Apple email address

team_id "PX8HZ58H7E"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.9  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-05-08**
</details>

**Comment by KrauseFx** [comment]
Hey @richlong, thanks for submitting this issue

```
getaddrinfo: nodename nor servname provided, or not known
```

this is an internet connection issue, and isn't caused by _fastlane_. Please make sure to fix your project settings.

**Comment by richlong** [comment]
Hi @KrauseFx , thanks for the reply.

As I mentioned, I have an internet connection which I've tested with a curl command and cocoapods is able to download and install via CLI and fastlane. The issue seems to be isolated to fastlane.

**Comment by KrauseFx** [comment]
> The issue seems to be isolated to fastlane.

We're using the `faraday` networking library, and don't set any proxys. To my knowledge the system proxy isn't automatically used by Ruby libraries.
