### ISSUE TITLE
In increment_build_number verifying that it's not a workspace by checking if string includes "workspace" is bad

### ISSUE THREAD

**Issue by essjaybee** [fastlane/fastlane#911]
In increment_build_number line 64, it checks if the value of the xcodeproj option contains the text "workspace" which is really bad. For example, one might use a Jenkins setup where the working directory is placed in a workspace/ folder and thus raising the exception.

What's the logic of checking for "workspace" rather than something more specific or checking that it's .xcodeproj specifically?

**Comment by Rking788** [comment]
Seems like this was fixed in Issue #895 .

**Comment by essjaybee** [comment]
Ah darn, my bad for not searching well enough. Cheers!

**Comment by KrauseFx** [comment]
Thanks @Rking788 :+1:
