### ISSUE TITLE
how to update associated domains

### ISSUE THREAD

**Issue by jasonz1987** [fastlane/fastlane#9116]
i enable associated domains capabilites in xcode because i used ios universal link service in my app.

![image](https://cloud.githubusercontent.com/assets/7090036/25839008/69975faa-34c8-11e7-949a-eb2958ebb3c2.png)

but how can i set different Associated Domains value with fastlane

any tools or any plugins,pls help me.

**Comment by KrauseFx** [comment]
To my knowledge there is nothing out there yet. Under the hood this is just a plist entry, right? If so, you can use `update_info_plist` or similar actions to update it
