### ISSUE TITLE
Match: add support for multiple apple id per team

### ISSUE THREAD

**Issue by Alesete** [fastlane/fastlane#9118]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hello everyone! are there any plan to support multiple apple id with match?

The policy in my company is that every developer should have their own apple id, so their accounts can be easily managed and deactivated when they eventually leave the company. Also, we can manage the admin permissions only for trusted people.

It would be very nice if everybody store their apple ID locally in their machines (e.g. with an environment variable), and then match would simply generate and add their certificates to the existing provisioning profiles (updating and syncing the provisionings across the team), instead of recreate the profile with only one certificate.

Is only a suggestion, if not possible, thanks anyway!

issue related #6757

**Comment by KrauseFx** [comment]
Hey @Alesete, thanks for submitting this, however _match_ was designed to share one Apple ID, as described in [codesigning.guide](https://codesigning.guide). There is no plan currently to change that. Thanks for the suggestion 👍
