### ISSUE TITLE
copy_build_artifacts is busted for Mac .app bundles

### ISSUE THREAD

**Issue by liscio** [fastlane/fastlane#912]
I have been chasing down a very painful signing issue on my CI server for the past few hours, and managed to find the culprit: `copy_build_artifacts`.

See this code: https://github.com/fastlane/fastlane/blob/master/lib/fastlane/actions/copy_artifacts.rb#L13

Note this text from `man cp`:

> Historic versions of the cp utility had a -r option.  This implementation supports that option; however, its use is strongly discouraged, as it does not correctly copy special files, symbolic links, or
     fifo's.

I imagine that the intention was to use `-R` instead of `-r`, to produce a recursive copy instead.

**Note to Mac developers reading this:** Until this is fixed, you need to use `copy_build_artifacts` with the `keep_original` flag set to `false`. Failing to specify this option will mess up your app bundle, causing Gatekeeper to reject the app.

**Comment by ohwutup** [comment]
Hey @liscio, apologies for the really slow response time on this. Is this something you are still facing? I am going to close this issue for now, but please feel free to continue discussion and we can reopen if necessary. Thanks! :octopus:

**Comment by liscio** [comment]
It's something that *everyone* is going to face until the `-r` is changed to `-R`. The copy isn't done properly!

**Comment by KrauseFx** [comment]
I just pushed https://github.com/fastlane/fastlane/pull/3763, does that fix this issue?

**Comment by liscio** [comment]
Yes, it fixes the `cp` operation, but now the comment in the code is busted. ;)

Thanks!
