### ISSUE TITLE
Cannot retrieve correct prices for auto-renewable subscriptions via Spaceship

### ISSUE THREAD

**Issue by klappradla** [fastlane/fastlane#9121]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

First of all, thanks a ton for providing this awesome set of tools 🙏 

I'm trying to retrieve the actual prices _(in their respective currency)_ for in app purchases of the type `Auto-Renewable Subscription`. The `pricing_intervals` contain entries like this:

```ruby
{:tier=>85, :begin_date=>nil, :end_date=>nil, :grandfathered=>{"value"=>"FUTURE_NONE", "isEditable"=>false, "isRequired"=>false, "errorKeys"=>nil}, :country=>"MT"},
{:tier=>78, :begin_date=>nil, :end_date=>nil, :grandfathered=>{"value"=>"FUTURE_NONE", "isEditable"=>false, "isRequired"=>false, "errorKeys"=>nil}, :country=>"GB"}
```

This matches Apple's [Territory Specific Pricing](https://developer.apple.com/app-store/subscriptions/) and its [Prices for Subscriptions](https://developer.apple.com/app-store/subscriptions/App-Store-Subscription-Pricing.pdf).

However, the `tier` specified here does not relate to the `tier_stem` in an `Spaceship::Tunes::PricingTier`, but rather the row-index of the CVS file I can download on iTunes Connect's *"All Prices and Currencies - Auto-Renewable Subscriptions"* page: 
```
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/<app-id>/pricingMatrix/recurring
```

If I now append a `.json` to the previous url:
```
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/<app-id>/pricingMatrix/recurring.json
```
I get a completely different pricing matrix, now including a `Tier` row. This matrix is what `Spaceship::Tunes` returns for `pricing_tiers`.

#### My Question now
Does `Spaceship` also provide the means to retrieve the prices for *"Auto-Renewable Subscriptions"*?
I'd be happy to work on a PR for this 🎉 , however, I could not yet find a place where Apple themselves provide this information *(besides the CSV file)*.

When trying to *abuse* the iTunes Connect Angular app, I can get the CSV content as JSON via this URL:
```
https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/<app-id>/iaps/pricing/matrix/recurring
```
But I'm not sure if this is correct and the tier names are actual *"names"* and not just identifiers to better render the table...

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.12.4                              |
| Ruby                        | 2.4.0                                |
| Bundler?                    | false                                |
| Git                         | git version 2.12.2                   |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)            |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.28.9  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| faraday                   | 0.12.1       |
| coderay                   | 1.1.1        |
| slop                      | 3.6.0        |
| method_source             | 0.8.2        |
| pry                       | 0.10.4       |
</details>

*generated on:* **2017-05-09**

**Comment by KrauseFx** [comment]
Hey @klappradla, thanks for reporting this. I don't use in-app purchased myself, but maybe @hjanuschka can help with that 👍

**Comment by klappradla** [comment]
I just made a tiny edit to the description: examining the iTunes Connect Angular app, I can retrieve the data I need in JSON as well. But I'm not sure if identifiers in there are actually *"valid"* and not just used for simplifying how to render the table.

**Comment by hjanuschka** [comment]
@klappradla  🙌 thx for using the api and providing top notch feedback!

`https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/<APP_ID>/iaps/pricing/matrix/recurring `

from a quick look the endpoint seems legit - so would you like to go on and do a PR - adding a method to `iap_detail` to load the json, and return a IAPTier object containing the 

```

            "countryCode": "PT",
            "currencyCode": "EUR",
            "wholesalePrice": 31.30,
            "wholesalePrice2": 38.00,
            "retailPrice": 54.99,
            "country": null,
            "currencySymbol": "€",
            "fRetailPrice": "54,99 €",
            "fWholesalePrice": "31,30 €",
            "fWholesalePrice2": "38,00 €"

```

values in fastlane manor? i am happy to review this and help you when you need assistance.
the only important thing is that the call to the matrix is only done once (cached) - and only done when user requests it, as it is really huge and slow to load (atleast from here: 🇦🇹)

**Comment by hjanuschka** [comment]
also as a sidenote: `Spaceship::Tunes::PricingTier` should not be changed, because i fear that it would break a couple of things. keeping the whole IAP thing seperated should be the ultimate goal. (therefore the IAPTier approach)

**Comment by klappradla** [comment]
Yes, makes total sense 👍 
I'll see what I can come up with. I'm a bit busy the next days *(see you at the conference 👋  )* but maybe it's raining on the weekend 😉

**Comment by hjanuschka** [comment]
@klappradla ahh awesome, see you there we can talk if want, you can DM on twitter if you need.

**Comment by klappradla** [comment]
Resolved via https://github.com/fastlane/fastlane/pull/9180 👨‍💻
