### ISSUE TITLE
Fastlane finished with error: "Could not set changelog"

### ISSUE THREAD

**Issue by timominous** [fastlane/fastlane#9127]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane is giving out an error that it could not set the changelog when uploading an ipa via `pilot`.

```
[19:11:31]: fastlane finished with errors

[!] Could not set changelog: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 409 </title>
</head>
<body>
<h2>HTTP ERROR: 409</h2>
<p>Problem accessing /v2/providers/:providerId/apps/:appId/builds/:buildId. Reason:
<pre>    ERROR-1: What to Test can't contain the following characters: ?, ?, ?.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
```

The actual changelog is:

- [🐛] Default to zero if fee is nil 
- [✏️] Typo in tagging commit

The changelog, however, was successfully set in the distributed Testflight build.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.0                          |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane        |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.29.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.2        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-05-10**
</details>

**Comment by thebugcode** [comment]
Afaik, you can't use emojis in testflight release notes, but I might be wrong.

**Comment by timominous** [comment]
@thebugcode I don't think that's that case because we have issued Testflight builds before with emoji in the release notes.

**Comment by gcamp** [comment]
Same problem here.

**Comment by KrauseFx** [comment]
```
<p>Problem accessing /v2/providers/:providerId/apps/:appId/builds/:buildId. Reason:
<pre>    ERROR-1: What to Test can't contain the following characters: ?, ?, ?.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
```
Can you try setting the same text using the iTunes Connect web UI? It might tell you more about what's not working.

**Comment by gcamp** [comment]
It started working again on my side, I'm guessing it was a temporary iTunes connect bug

**Comment by ergunkocak** [comment]
Hello,

Received the same error but i could distribute to external users over itunesconnect interface???

**ChangeLog Submited :** 
- NEXM-1029 : User is trying to close/change trade with a closed market
  (Ergün Koçak)
- NEXM-1066 : 10 years time range removed from charts
  (Ergün Koçak)
- Google Tag Manager config file updated to latest version
  (Ergün Koçak)

**Error Output in Shell :** 
[08:56:24]: fastlane finished with errors

[!] Could not set changelog: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 409 </title>
</head>
<body>
<h2>HTTP ERROR: 409</h2>
<p>Problem accessing /v2/providers/95788945/apps/1217870392/builds/20752718. Reason:
<pre>    ERROR-1: What to Test can't contain the following characters: ?, ?.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

**Comment by ergunkocak** [comment]
Mine is solved when i remove letters "ü" and "ç" from the text. Problem was my name containing these letters "Ergün Koçak" in the changelog as commiter

**Comment by ohayon** [comment]
Oh thats really interesting and we should probably make sure that we take care of that on our end. @ergunkocak did you then go back in to iTC and change your name back to normal manually??

**Comment by ergunkocak** [comment]
i changed the name of my user in git repo to "ergun" so next build was without these letters and worked. But whenever i had my full name (with problematic letters) in git change log it gave the same error and i had to open itunesconnect web site and submit manually. Funny part is manual submit work with these letters in itunesconnect interface.

**Comment by ohayon** [comment]
Hmmm.. that is really interesting. I am going to try to run some tests and see if we can get a fix for this! Have you ever run into issues like this with those types of characters and other APIs?

**Comment by ohayon** [comment]
Hey @ergunkocak, I just tried to reproduce this locally, and was not able to get the same error. I set your name as the changelog for my test app, and everything worked as expected. 🤔 
![screen shot 2017-06-14 at 2 35 09 pm](https://user-images.githubusercontent.com/2587018/27148555-b3dbff6e-510e-11e7-9407-7377a4e96632.png)

Where is that `changelog` variable coming from in your call to _pilot_? Could it be that it is encoded differently?

**Comment by ergunkocak** [comment]
Changelog is coming from :

`changelog = changelog_from_git_commits`
`changelog = changelog.sub(/[\u{1F300}-\u{1F6FF}]/, '') # HAX: strip emoji from changelog`
`Actions.lane_context[SharedValues::FL_CHANGELOG] = changelog`

**Comment by ohayon** [comment]
Hey @ergunkocak - would it be possible for you to share the exact text of your changelog in a text file so that we can see if there are any hidden characters that are included in there?

**Comment by ergunkocak** [comment]
@ohayon i sent you an email ;)

**Comment by ergunkocak** [comment]
This is the error i got : 
....
| 24   | gym                                                    | 227         |
| 25   | crashlytics                                            | 26          |
| 💥   | pilot                                                  | 1140        |
| 27   | slack                                                  | 0           |
+------+--------------------------------------------------------+-------------+

[09:38:46]: fastlane finished with errors

[!] Could not set changelog: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 409 </title>
</head>
<body>
<h2>HTTP ERROR: 409</h2>
<p>Problem accessing /v2/providers/95788945/apps/1217870392/builds/21043481. Reason:
<pre>    ERROR-1: What to Test can't contain the following characters: ?, ?.</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
