### ISSUE TITLE
Revoke certificate issue for two different apps in same account

### ISSUE THREAD

**Issue by shashankwadi** [fastlane/fastlane#9128]
I have two different apps from one dev account 
I've set up separate repo for certificates for each app and everything else which needs to be done
the only problem I am facing is when i run faslane match nuke command on one repo it recreate the development certificate and the build on hockey for repo 2 cant be downloaded.(because the certificate does not exist anymore).
and vice versa with repo 1

what should be done here

I hope u got me what i mean to convey

**Comment by PetrosIchor** [comment]
Match nuke is primarily to revoke all signing assets on the apple developer account.  Since you're storing in separate branches, don't use the nuke option.  

Either store them in the same branch or only regenerate what you need and leave the rest.

**Comment by shashankwadi** [comment]
'match nuke development' nukes development certificate.
What do u mean by 'only regenerate what you need and leave the rest'
If I don't run match nuke and build app then i get this error

Certificate 'GKN9QMXXXX' (stored in your git repo) is not available on the Developer Portal
Make sure to use the same user and team every time you run 'match' for this
Git repository. This might be caused by revoking the certificate on the Dev Portal
To reset the certificates of your Apple account, you can use the `fastlane match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match

**Comment by shashankwadi** [comment]
@PetrosIchor need ur help.

**Comment by shashankwadi** [comment]
on running fastlane match development this is what i get.

[14:39:25]: Certificate 'GKN9QM6835' (stored in your git repo) is not available on the Developer Portal
[14:39:25]: for the user yopeso@wadi.com
[14:39:25]: Make sure to use the same user and team every time you run 'match' for this
[14:39:25]: Git repository. This might be caused by revoking the certificate on the Dev Portal

[!] To reset the certificates of your Apple account, you can use the `fastlane match nuke` feature, more information on https://github.com/fastlane/fastlane/tree/master/match

**Comment by PetrosIchor** [comment]
Have you tired just using Cert and Sigh instead?  It sounds like match isn't a good fit for your requirements.

If you only have 1 account, you don't need to have separate repos for match.  Just use one and have all your accounts certs/profiles stored there with match.  You can also use branches if separating is important.

If that doesn't work for you, then a more granular cert/sigh setup is probably the way to go.
