### ISSUE TITLE
Better error message for locked keychain issues

### ISSUE THREAD

**Issue by getaaron** [fastlane/fastlane#9129]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Sometimes keychain actions fail because the keychain is locked. We currently show only marginally helpful error messages like:

> SecKeychainAddInternetPassword <NULL>: User interaction is not allowed.

It would be more helpful to show an error like:

> 🔓 This action failed because your keychain is locked. This is common if you are SSHing into a machine, or if your keychain password differs from your login password. Try using the _fastlane_ `unlock_keychain` action (or if appropriate, a CI server action like `setup_jenkins`) to unlock the keychain first.

**Comment by getaaron** [comment]
Thanks for the suggestion, @fastlane-bot, but I don't think that's relevant here.

**Comment by KrauseFx** [comment]
That's a great idea, I very much agree that the error message should be more clear, and ideally even contain information about how to fix the issue. Is that something you'd want to build? 👍

**Comment by danielrees18** [comment]
@KrauseFx I'm looking to contribute to this project and I think this would be a pretty good issue to start on. I would appreciate it if you could point me in some direction as to where in the project this change would be. 

So far I've located the `*_keychain` actions such as `unlock_keychain` but I'm not sure if I'm looking in the right place. I also cannot find where this error might be produced and handled.

**Comment by getaaron** [comment]
@danielrees18 Check out how _match_ calls the keychain actions. The error messages aren't from _fastlane_. I think they're from the `security` command.

**Comment by danielrees18** [comment]
@getaaron thanks! I'll take a look
