### ISSUE TITLE
Can no longer pass hashes to set_info_plist_value

### ISSUE THREAD

**Issue by hammertoe** [fastlane/fastlane#913]
At some point in the last few releases, my fastlane config stopped working due to being unable to pass a hash to set_info_plist_value:

[09:39:29]: ----------------------------------
[09:39:29]: --- Step: set_info_plist_value ---
[09:39:29]: ----------------------------------
[09:39:29]: You passed invalid parameters to 'set_info_plist_value'.
[09:39:29]: Check out the error below and available options by running `fastlane action set_info_plist_value`
[09:39:29]: ----------------------------
[09:39:29]: --- Step: reset_git_repo ---
[09:39:29]: ----------------------------
[09:39:29]: [SHELL COMMAND]: git checkout -- 'Nutrition/Nutrition.xcodeproj/project.pbxproj'
[09:39:29]: Git cleaned up 1 files.
[09:39:29]: Variable Dump:
[09:39:29]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios build_release", :BUILD_NUMBER=>"51", :VERSION_NUMBER=>"1.2.0"}
[09:39:29]: 'value' value must be a String! Found Hash instead.

The fragment of Fastfile that causes this:

       # Remove ability to load arbitrary TLS connections (may be added by developers)
        set_info_plist_value(
          path: './Nutrition/Nutrition/Info.plist',
          key: 'NSAppTransportSecurity',
          value:  { 'NSAllowsArbitraryLoads' => false }
        )

**Comment by KrauseFx** [comment]
Are you sure this worked before? In which version did it work?

**Comment by zac** [comment]
I believe this core of this issue also stops `set_info_plist_value` from being used for simple true/false values. For instance: `set_info_plist_value(key: 'UseProduction', value: true, path: info_plist)` wouldn't work.

I am just now running into this issue so I can't speak to when/if this happened.

**Comment by zac** [comment]
FYI, if anyone is interested my (awful) workaround for now is:

```Ruby
sh "plutil -replace \'#{production_key}\' -bool #{options[:production] ? 'YES' : 'NO'} '../#{info_plist}'"
```

**Comment by hammertoe** [comment]
I'm not sure exactly which version it used to work in, as not updated in a  few weeks. But here is a PR that fixes it:

https://github.com/hammertoe/fastlane/pull/1 <https://github.com/hammertoe/fastlane/pull/1>

-Matt

> On 14 Dec 2015, at 00:56, Felix Krause <notifications@github.com> wrote:
> 
> Are you sure this worked before? In which version did it work?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/fastlane/fastlane/issues/913#issuecomment-164316379>.
> 


— 
Matt Hamilton
Quernus
matt@quernus.co.uk
+44 117 325 3025
64 Easton Business Centre
Felix Road, Easton
Bristol, BS5 0HE

Quernus Ltd is a company registered in England and Wales. Registered number: 09076246

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Comment by hammertoe** [comment]
Yes, it is still an issue. I submitted a PR a while back, but it was never incorporated. The fix is a one-liner:

`--- /Library/Ruby/Gems/2.0.0/gems/fastlane-1.67.0/lib/fastlane/actions/set_info_plist_value.rb	2016-03-23 14:44:18.000000000 +0000
+++ /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/set_info_plist_value.rb	2016-03-30 16:23:31.000000000 +0100
@@ -34,6 +34,7 @@
           FastlaneCore::ConfigItem.new(key: :value,
                                        env_name: "FL_SET_INFO_PLIST_PARAM_VALUE",
                                        description: "Value to setup",
+				       is_string: false,
                                        optional: false),
           FastlaneCore::ConfigItem.new(key: :path,
                                        env_name: "FL_SET_INFO_PLIST_PATH",
`

**Comment by TKBurner** [comment]
Thanks for following up @hammertoe! The team here is going to have a look. :+1:

**Comment by hammertoe** [comment]
Actually... as I couldn't re-open I created a new ticket, #4103 which has been dealt with and a fix merged in already. So this ticket can be closed again! Sorry for the confusion!
-Matt

**Comment by TKBurner** [comment]
@hammertoe Thanks for letting us know. Hope that you have a great week!
