### ISSUE TITLE
produce enable_services does not work for Push Notifications

### ISSUE THREAD

**Issue by VolkerSchiewe** [fastlane/fastlane#9131]
When i try to use `produce` to enable push notifications for an AppID and the Service is already enabled and has some certificates, this service gets disabled instead and all the APN Certificates get revoked.

**Comment by KrauseFx** [comment]
For push notifications, you should use [pem](https://fastlane.tools/pem) 👍

**Comment by VolkerSchiewe** [comment]
Sure, thats what I'm doing right now as work around. But the bug remains...
