### ISSUE TITLE
train.update_testing_status Failing

### ISSUE THREAD

**Issue by likedanf** [fastlane/fastlane#9132]
### Issue Description

Since Apple update testFlight, train.update_testing_status!(true, 'internal', train_build) constantly return error.

**Comment by likedanf** [comment]
In our case, we're only using spaceship module but not Fastlane.

**Comment by KrauseFx** [comment]
There is new methods available you can use now. Check out the `build_manager.rb` file, in particular the following

```ruby
    def distribute_build(uploaded_build, options)
      UI.message("Distributing new build to testers: #{uploaded_build.train_version} - #{uploaded_build.build_version}")

      # This is where we could add a check to see if encryption is required and has been updated
      uploaded_build.export_compliance.encryption_updated = false

      if options[:distribute_external]
        uploaded_build.beta_review_info.demo_account_required = false
        uploaded_build.submit_for_testflight_review!
        external_group = Spaceship::TestFlight::Group.default_external_group(app_id: uploaded_build.app_id)
        uploaded_build.add_group!(external_group) unless external_group.nil?

        if external_group.nil? && options[:groups].nil?
          UI.user_error!("You must specify at least one group using the `:groups` option to distribute externally")
        end

        if options[:groups]
          groups = Spaceship::TestFlight::Group.filter_groups(app_id: uploaded_build.app_id) do |group|
            options[:groups].include?(group.name)
          end
          groups.each do |group|
            uploaded_build.add_group!(group)
          end
        end
      else # distribute internally
        # in case any changes to export_compliance are required
        if uploaded_build.export_compliance_missing?
          uploaded_build.save!
        end
      end

      true
    end
```

I hope that helps 👍

**Comment by likedanf** [comment]
I've seen this method. I think out use case was that, we need to only modify the state of the beta_tester but doesn't distribute a build in the mean time. That's where we were calling train.update_testing_status!(true, 'internal', train_build). So after the update, there's no way to achieve that?

**Comment by KrauseFx** [comment]
I don't think there is unfortunately 😢

**Comment by nikitaame** [comment]
@KrauseFx When calling `distribute` since `distribute_build` is private, I am getting this issue:
`build_manager.rb:135:in `distribute_build': [!] undefined method `export_compliance' for #<Spaceship::Tunes::Build:0x007fea4c95f130> (NoMethodError)`
