### ISSUE TITLE
Running xcode_install is asking for password

### ISSUE THREAD

**Issue by kevin-hirsch** [fastlane/fastlane#914]
I am using `xcode_install` as follows in one of my lanes

``` ruby
xcode_install(version: "7.1.1")
```

It works fine but it asks for my password:
![screen shot 2015-11-27 at 12 04 29](https://cloud.githubusercontent.com/assets/2794684/11439972/102f2dd6-94ff-11e5-9a87-943513ab8f9a.png)

I am running this code on a Bamboo server and I would want to be able to "pass" the password in some way so I do not have to type it manually. Is this possible?

**Comment by KrauseFx** [comment]
Uh, maybe @neonichu knows a way around this? Installing a new version of Xcode requires `sudo`.

**Comment by neonichu** [comment]
IIRC, it is possible to specify commands which can be executed passwordless by `sudo` in `/etc/sudoers`. Another way could be extending `xcode-install` to specify the password in some alternative way and use `sudo -S` to pass it in.

**Comment by kevin-hirsch** [comment]
Thanks for the help!
If I would use `/etc/sudoers` what should be the commands to put there?

**Comment by ohwutup** [comment]
Hey everyone! I am going to close this issue for now as it has been a while since there has been any activity on here. Please feel free to continue discussion and we can reopen the issue if necessary! Thanks! :cake:

**Comment by mindrunner** [comment]
I think we should reopen this. I am facing exactly the same problem and it would be nice to have some kind of solution here.

**Comment by TKBurner** [comment]
@mindrunner Thanks for following up. We are going to review this as a feature request and then update this thread. Thanks for working with us! 👍

**Comment by mindrunner** [comment]
Cool, I stumbled through the [xcode-install](https://github.com/neonichu/xcode-install) source today and figured out that it uses, besides of others, "sudo rm" while installing. I really do not want to allow "sudo rm" NOPASSWD in my build node's sudoers file. Would love to find a solution for this, though. :)

**Comment by mindrunner** [comment]
Still an issue. Did not have time yet to create a patch.

**Comment by KrauseFx** [comment]
Sorry, no, I wasn't working on this issue.

**Comment by mindrunner** [comment]
Hmm, yes, did not expect someone working on this. I might need it soon, though. So Maybe I will spend some time for it.

**Comment by KrauseFx** [comment]
Cool, let us know if you need any help getting started with contributing to fastlane @mindrunner 👍

**Comment by revolter** [comment]
This is still an issue. I understand asking for the password to install it, but it shouldn't ask for it when the requested version is already installed.

I think it may be caused by:

1. [Running `sudo xcode-select --switch ...`](https://github.com/xcpretty/xcode-install/blob/18c402c3c487c83352a1669ba781fe9ac5574782/lib/xcode/install/select.rb#L31), which maybe could be solved by checking `xcode-select --print-path` before, and only using `--switch` if needed.

2. [Running `sudo rm -rf ...`](https://github.com/xcpretty/xcode-install/blob/18c402c3c487c83352a1669ba781fe9ac5574782/lib/xcode/install.rb#L259), which maybe could be solved by checking if the path to be removed actually exists or not.

3. Running any other command with `sudo` from [that file](https://github.com/xcpretty/xcode-install/blob/18c402c3c487c83352a1669ba781fe9ac5574782/lib/xcode/install.rb), though most of them look like they are only used when installing Xcode.

**Comment by shobhitpuri** [comment]
> This is still an issue. I understand asking for the password to install it, but it shouldn't ask for it when the requested version is already installed.
> 
> I think it may be caused by:
> 
> 1. [Running `sudo xcode-select --switch ...`](https://github.com/xcpretty/xcode-install/blob/18c402c3c487c83352a1669ba781fe9ac5574782/lib/xcode/install/select.rb#L31), which maybe could be solved by checking `xcode-select --print-path` before, and only using `--switch` if needed.
> 2. [Running `sudo rm -rf ...`](https://github.com/xcpretty/xcode-install/blob/18c402c3c487c83352a1669ba781fe9ac5574782/lib/xcode/install.rb#L259), which maybe could be solved by checking if the path to be removed actually exists or not.
> 3. Running any other command with `sudo` from [that file](https://github.com/xcpretty/xcode-install/blob/18c402c3c487c83352a1669ba781fe9ac5574782/lib/xcode/install.rb), though most of them look like they are only used when installing Xcode.

@revolter  Thanks for this comment. I am facing this when running from fastfile. I am not using any sudo commands inside fastfile. How can `xcode-select --print-path` be run from the fastfile to check for installed path? Any way to do that.
