### ISSUE TITLE
Snapshot produces an error when product name has special characters

### ISSUE THREAD

**Issue by akmarinov** [fastlane/fastlane#9142]
### New Issue Checklist

- [ X] Updated fastlane to the latest version
- [ X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

My app's name `P&O` contains special characters `&`.

When I run snapshot with the product name in build settings set to `P&O`, snapshot fails with 

> xcodebuild[42677:12388799] There was an error parsing the Info.plist for the bundle at URL <0x7f8d21637c20>: NSCocoaErrorDomain - 3840
>  Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedDescription=Installation Failed, NSLocalizedRecoverySuggestion=The application at “/var/folders/gm/gzyhbj3j7jqfmjs_12p96r75yjzzt1/T/snapshot_derived20170511-41691-15j9qv7/Build/Products/Debug-iphonesimulator/P&O-Runner.app” does not have a bundle identifier}

If I use Xcode to build and run, archive or test everything works fine.

Escaping the product name correctly solves the issue, though that makes the app's name on the home screen and on notification/location alerts to show the escaped name literally `P&amp;O`
One workaround is to add a Bundle display name field to the info.plist where I have the unescaped name of the app - `P&O` and change the product name to an escaped version `P&amp;O`.

As my app is more of a template and the name changes, I'd like to be able to potentially only change the name in one place either escaped or unescaped.

I can't seem to be able to print out the xcodebuild command that snapshot uses to produce the .app

Is this related to how snapshot passes the product name to xcodebuild, since Xcode handles it fine, and should that be escaped?
Or is this a bug in xcodebuild and should I file a radar? Any clues as to how I can print out the used xcodebuild command would be appreciated.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

fastlane snapshot

> xcodebuild[42677:12388799] There was an error parsing the Info.plist for the bundle at URL <0x7f8d21637c20>: NSCocoaErrorDomain - 3840
>  Error Domain=NSPOSIXErrorDomain Code=22 "Invalid argument" UserInfo={NSLocalizedDescription=Installation Failed, NSLocalizedRecoverySuggestion=The application at “/var/folders/gm/gzyhbj3j7jqfmjs_12p96r75yjzzt1/T/snapshot_derived20170511-41691-15j9qv7/Build/Products/Debug-iphonesimulator/P&O-Runner.app” does not have a bundle identifier}

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.5                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.5/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.5/lib                |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.28.7  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.1        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-11**
</details>

**Comment by KrauseFx** [comment]
Ah, thanks for submitting this and sorry for the late reply, is this still an issue? Could you provide a small sample project to reproduce?

**Comment by akmarinov** [comment]
Hmm, I was unable to reproduce the issue with the latest Fastlane version.
I'll reopen if that changes.

Thanks!
