### ISSUE TITLE
Fastlane pilot crashed

### ISSUE THREAD

**Issue by rajat-deep-singh** [fastlane/fastlane#9151]
### Issue Description
Pilot crashed error while executing command "fastlane pilot upload -u email@company.com"

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
<details><summary>Console Output</summary>

[11:18:18]: Successfully exported and compressed dSYM file
[11:18:18]: Successfully exported and signed the ipa file:
[11:18:18]: /Users/cs/.jenkins/workspace/App-IOS/SampleApp.ipa
[App-IOS] $ /bin/sh -xe /var/folders/9m/6xsb86655g92dzvj6s__rhx40000gp/T/hudson5500105879294879617.sh
+ fastlane pilot upload -u email@company.com
[11:18:26]: Login to iTunes Connect (email@company.com)
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------
[11:18:26]: -------------
[11:18:26]: pilot crashed
[11:18:26]: -------------
[11:18:26]: Unfortunately the TestFlight update from 11th April 2017 changed
[11:18:26]: the way Testers, Groups, and Builds are managed on iTunesConnect.
[11:18:26]: We have already fixed a number of features including submitting
[11:18:26]: builds for testing, adding and removing testers from groups, and
[11:18:26]: waiting for builds to process.
[11:18:26]: 
[11:18:26]: Please open an issue on https://github.com/fastlane/fastlane/issues
[11:18:26]: if you believe this failure is the result of a bug in _pilot_ and we
[11:18:26]: will be happy to look into this further.
[11:18:26]: 
[11:18:26]: Please stay tuned for more updates from _fastlane_ as we fix more issues!
[11:18:26]: 
[11:18:26]: Original error message:

[!] Missing password for user email@company.com, and running in non-interactive shell

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.3/bin/fastlane       |
| Host                        | Mac OS X 10.12.5 (16F43c)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.2       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.23       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.2        |
| faraday_middleware        | 0.11.0       |
</details>

*generated on:* **2017-05-12**
</details>

**Comment by hjanuschka** [comment]
hi @rajat-deep-singh  🤚  
the error `Missing password for user email@company.com, and running in non-interactive shell`  indicates that there is some authentication error.


```
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the FASTLANE_PASSWORD environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager

```

let me know if this helps you.

**Comment by rajat-deep-singh** [comment]
@hjanuschka Thanks for your reply. I have already store the credentials of my apple account in Keychain using credential manager, but still I am receiving same error. Can you guide me how can I pass FASTLANE_PASSWORD environment variable? Maybe this can work for me.

**Comment by ohayon** [comment]
Hey @rajat-deep-singh - you should be able to prefix your _fastlane_ command like so `FASTLANE_PASSWORD=your_password fastlane ....` Let us know if that helps!
