### ISSUE TITLE
missing team id in non interactive mode still blocks

### ISSUE THREAD

**Issue by doapp-ryanp** [fastlane/fastlane#9154]
Commenting for https://github.com/fastlane-old/pem/issues/76 is locked so started a new issue here.

Running PEM 2.26.0 in a jenkins non-interactive environment.  The issue above was to request a new feature that allowed a non-interactive program to detect when team ID is not found, and to take corrective action.

I just ran into the problem in v2.26.0:

```
INFO [2017-05-11 14:56:53.68]: Starting login with user 'me@me.com'
Couldn't find team with ID 'XXXXXXXXXX'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
...
```
PEM then blocks my program as it is waiting for input.

I would like PEM to blow up in this scenario and have a return code so that I can take corrective action.  

The original commit to address this (https://github.com/fastlane-old/fastlane_core/commit/a5f24e46cc2168c46a9051c3b522663e01fc0ace) does not work. According to @KrauseFx

> The reason why this doesn't work yet is that spaceship doesn't have access to fastlane_core. However that's something we want to fix.

**Comment by hjanuschka** [comment]
hey @doapp-ryanp 🤚 i did a PR -> #9160  maybe you can give it a try, it should now raise an error when team selection is triggered under non-interactive environments.

**Comment by doapp-ryanp** [comment]
Thanks @hjanuschka I know very little about Ruby - where do all the .rb files live so that I can hand patch them and test?  running `which PEM` gives me `/Users/dbuilder/.rvm/rubies/ruby-2.2.2/bin/PEM'

**Comment by hjanuschka** [comment]
@doapp-ryanp  you can try it with this helper script: https://gist.github.com/hjanuschka/3040fc6f371f46acff72a5e67f649b27


running it with `./try_pr.sh hjanuschka spaceship_interactive fastlane pem` - should run it from the PR branch.

**Comment by doapp-ryanp** [comment]
@hjanuschka how do I roll it back? Don't want to test until I have a sure fire way to get back to where I was in case of problems.

**Comment by hjanuschka** [comment]
@doapp-ryanp it doesn't install anything, the `.sh` scripts clones the repo into `tmp` - checks out the branch and runs it.

so if you run it with `fastlane pem` again it will run the real installed version.

**Comment by doapp-ryanp** [comment]
@hjanuschka tried your PR, it crashes:

```
INFO [2017-05-15 09:25:06.62]: Sending crash report...
INFO [2017-05-15 09:25:06.62]: The stacktrace is sanitized so no personal information is sent.
INFO [2017-05-15 09:25:06.62]: To see what we are sending, look here: /Users/dbuilder/.fastlane/latest_crash.json
INFO [2017-05-15 09:25:06.62]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
INFO [2017-05-15 09:25:06.62]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

Looking for related GitHub issues on fastlane/fastlane...
Search query: multiple_teams_no_interactive_shell

URL: https://api.github.com/search/issues?q=multiple_teams_no_interactive_shell+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/tmp/pr-try-hjanuschka-spaceship_interactive/spaceship/lib/spaceship/portal/ui/select_team.rb:89:in `select_team': [!] multiple_teams_no_interactive_shell (RuntimeError)
	from /tmp/pr-try-hjanuschka-spaceship_interactive/spaceship/lib/spaceship/portal/portal_client.rb:55:in `select_team'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/pem/lib/pem/manager.rb:36:in `login'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/pem/lib/pem/manager.rb:10:in `start'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/pem/lib/pem/commands_generator.rb:33:in `block (2 levels) in run'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2@global/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/pem/lib/pem/commands_generator.rb:39:in `run'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/pem/lib/pem/commands_generator.rb:11:in `start'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /tmp/pr-try-hjanuschka-spaceship_interactive/bin/fastlane:20:in `<top (required)>'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/fastlane:22:in `load'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/fastlane:22:in `<main>'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dbuilder/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by hjanuschka** [comment]
@doapp-ryanp yeah! thx - yes this should be the fix, before the PR it ended in an endless loop.

**Comment by doapp-ryanp** [comment]
Morning @KrauseFx any idea which release this feature/fix is targeted for? I've noticed 3 releases since this was closed so just curious.

**Comment by hjanuschka** [comment]
@doapp-ryanp this should have been shipped with: 

https://github.com/fastlane/fastlane/releases/tag/2.31.0
according to the bot.
https://github.com/fastlane/fastlane/pull/9160#issuecomment-302396633


are you sure you are on 2.31 or higher?

**Comment by hjanuschka** [comment]
ohhh to fast reply, the PR got changed, and it only will work / fix the loop once `fastlane_core` is required.

so if you only use spaceship. you should add a `require 'fastlane_core'` so it detects the `FastlaneCore::Helper.is_ci` methods.
