### ISSUE TITLE
Report Generator for Screengrab

### ISSUE THREAD

**Issue by maszin** [fastlane/fastlane#9161]
Hi,

Are you going to include Reports Generator (to html) in Screengrab? This would be a great. 
I could contribute to this feature and send PR.

**Comment by mfurtak** [comment]
Hi @maszin 👋  - Yes, that is something we'd like to have. If you'd like to make the PR, I would be happy to review it 👍

**Comment by mfurtak** [comment]
Implemented in #9213 🎉

**Comment by maszin** [comment]
Thanks 👍
