### ISSUE TITLE
supply: double "Global Options" in the help description when using `fastlane supply --help`

### ISSUE THREAD

**Issue by Orgmir** [fastlane/fastlane#9164]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running `fastlane supply --help`, the `Global Options` section shows duplicate entries. I've tried to figure it out, but my knowledge of ruby is limited and I need some help to point me in the right direction.

```
  supply

  Command line tool for updating Android apps and their metadata on the Google Play Store

  Commands: (* default)
    help   Display global or [command] help documentation
    init   Sets up supply for you
    run  * Run a deploy process

  Global Options:
    --verbose
    -p, --package_name STRING The package name of the Application to modify (SUPPLY_PACKAGE_NAME)
    -a, --track STRING   The Track to upload the Application to: production, beta, alpha, rollout (SUPPLY_TRACK)
    -r, --rollout STRING The percentage of the user fraction when uploading to the rollout track
    -m, --metadata_path STRING Path to the directory containing the metadata files (SUPPLY_METADATA_PATH)
    -k, --key STRING     [DEPRECATED!] Use --json_key instead - The p12 File used to authenticate with Google (SUPPLY_KEY)
    -i, --issuer STRING  [DEPRECATED!] Use --json_key instead - The issuer of the p12 file (email address of the service account) (SUPPLY_ISSUER)
    -j, --json_key STRING The service account json file used to authenticate with Google (SUPPLY_JSON_KEY)
    -c, --json_key_data STRING The service account json used to authenticate with Google (SUPPLY_JSON_KEY_DATA)
    -b, --apk STRING     Path to the APK file to upload (SUPPLY_APK)
    -u, --apk_paths ARRAY An array of paths to APK files to upload (SUPPLY_APK_PATHS)
    --skip_upload_apk [VALUE] Whether to skip uploading APK (SUPPLY_SKIP_UPLOAD_APK)
    --skip_upload_metadata [VALUE] Whether to skip uploading metadata (SUPPLY_SKIP_UPLOAD_METADATA)
    --skip_upload_images [VALUE] Whether to skip uploading images, screenshots not included (SUPPLY_SKIP_UPLOAD_IMAGES)
    --skip_upload_screenshots [VALUE] Whether to skip uploading SCREENSHOTS (SUPPLY_SKIP_UPLOAD_SCREENSHOTS)
    --track_promote_to STRING The Track to promote to: production, beta, alpha, rollout (SUPPLY_TRACK_PROMOTE_TO)
    --validate_only [VALUE] Indicate that changes will only be validated with Google Play rather than actually published (SUPPLY_VALIDATE_ONLY)
    -d, --mapping STRING Path to the mapping file to upload (SUPPLY_MAPPING)
    -s, --mapping_paths ARRAY An array of paths to mapping files to upload (SUPPLY_MAPPING_PATHS)
    --root_url STRING    Root URL for the Google Play API. The provided URL will be used for API calls in place of https://www.googleapis.com/ (SUPPLY_ROOT_URL)
    -p, --package_name STRING The package name of the Application to modify (SUPPLY_PACKAGE_NAME)
    -a, --track STRING   The Track to upload the Application to: production, beta, alpha, rollout (SUPPLY_TRACK)
    -r, --rollout STRING The percentage of the user fraction when uploading to the rollout track
    -m, --metadata_path STRING Path to the directory containing the metadata files (SUPPLY_METADATA_PATH)
    -k, --key STRING     [DEPRECATED!] Use --json_key instead - The p12 File used to authenticate with Google (SUPPLY_KEY)
    -i, --issuer STRING  [DEPRECATED!] Use --json_key instead - The issuer of the p12 file (email address of the service account) (SUPPLY_ISSUER)
    -j, --json_key STRING The service account json file used to authenticate with Google (SUPPLY_JSON_KEY)
    -c, --json_key_data STRING The service account json used to authenticate with Google (SUPPLY_JSON_KEY_DATA)
    -b, --apk STRING     Path to the APK file to upload (SUPPLY_APK)
    -u, --apk_paths ARRAY An array of paths to APK files to upload (SUPPLY_APK_PATHS)
    --skip_upload_apk [VALUE] Whether to skip uploading APK (SUPPLY_SKIP_UPLOAD_APK)
    --skip_upload_metadata [VALUE] Whether to skip uploading metadata (SUPPLY_SKIP_UPLOAD_METADATA)
    --skip_upload_images [VALUE] Whether to skip uploading images, screenshots not included (SUPPLY_SKIP_UPLOAD_IMAGES)
    --skip_upload_screenshots [VALUE] Whether to skip uploading SCREENSHOTS (SUPPLY_SKIP_UPLOAD_SCREENSHOTS)
    --track_promote_to STRING The Track to promote to: production, beta, alpha, rollout (SUPPLY_TRACK_PROMOTE_TO)
    --validate_only [VALUE] Indicate that changes will only be validated with Google Play rather than actually published (SUPPLY_VALIDATE_ONLY)
    -d, --mapping STRING Path to the mapping file to upload (SUPPLY_MAPPING)
    -s, --mapping_paths ARRAY An array of paths to mapping files to upload (SUPPLY_MAPPING_PATHS)
    --root_url STRING    Root URL for the Google Play API. The provided URL will be used for API calls in place of https://www.googleapis.com/ (SUPPLY_ROOT_URL)
    -h, --help           Display help documentation
    -v, --version        Display version information

  Author:
    Felix Krause <supply@krausefx.com>

  Website:
    https://fastlane.tools
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.99.0"

default_platform :android

platform :android do
  before_all do

    ENV["CRASHLYTICS_API_TOKEN"] = "00443a4b802a933babfc9c4737e42ca2dd6bd06f"
    ENV["CRASHLYTICS_BUILD_SECRET"] = "5799e5a4939bbd1f982c3a030209c31e5e8c16ab545237b9cafb9a2ac2db2799"
    ENV["SUPPLY_PACKAGE_NAME"] = "com.mentallyfriendly.foodco.muffinbreak"

    # Clear generated .apks so supply doesn't try to upload everything when it runs
    sh "rm -f ../app/build/outputs/apk/*.apk"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "assembleRelease")
    crashlytics
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end


  after_all do |lane|

  end

  error do |lane, exception|

  end
end```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file ".//fastlane/Google-Play-Android Developer-6b4764e80bc9.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| fastimage                 | 2.1.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>

*generated on:* **2017-05-15**
</details>

**Comment by thebugcode** [comment]
I get the same thing locally. @KrauseFx this looks like bug? I checked and this issue is not present in older versions of fastlane (2.22.0).

**Comment by KrauseFx** [comment]
Thanks for reporting this, I can reproduce the issue and I'm working on a fix

**Comment by KrauseFx** [comment]
Submitted a PR https://github.com/fastlane/fastlane/issues/9173
