### ISSUE TITLE
Question: Why was gym :: provisioning_profile_path deprecated?

### ISSUE THREAD

**Issue by richardszalay** [fastlane/fastlane#9165]
#5106 deprecated gym's provisioning_profile_path option, but provided no explanation at all as to why it was happening. Could you clarify?

(We use the option to create an IPA for an xcarchive in a separate build process - we don't keep targets for each of the configurations in the xcodeproj)

**Comment by mgrebenets** [comment]
Hi @richardszalay. 

Off the top of my head there's a few reasons why this option is deprecated. 

To start with, Apple itself deprecated underlying build setting in favour of provisioning profile specified. 

Another one is when you are dealing with nested apps and extensions, this option will apply to **all** nested bundles, not just to the main app bundle. This is actually why we stopped specifying this build option in our scripts even before we adopted fastlane. Each nested app and extension has its own bundle id while profile contains only one bundle id.

This is just few of the reasons why the option is deprecated. 

I guess you have 2 possible options. 

You can specify build setting directly via Xcode config option of gym. (Sorry, writing from ththe phone, don't remember the exact name)

Alternatively you can update your Xcode project build settings. Eg specify profile per configuration or use xcconfigs

**Comment by KrauseFx** [comment]
Thanks, great reply @mgrebenets 👍  in general, also check out our [code signing docs](https://docs.fastlane.tools/codesigning/getting-started/)

**Comment by richardszalay** [comment]
Thanks @mgrebenets, makes sense.

As a follow up, I found that as long as I specify `export_team_id`, `gym` will pick up the environment variables that `match` leaves behind.
