### ISSUE TITLE
what is the key difference between Fastlane and xcode?

### ISSUE THREAD

**Issue by samratBasra** [fastlane/fastlane#9166]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by smumryak** [comment]
iOS is operating system, fastlane is a tool for automation of application build and distribution.

**Comment by samratBasra** [comment]
My bad. question has been updated.

**Comment by smumryak** [comment]
Xcode is an integrated development environment for macOS containing a suite of software development tools, fastlane is a tool for automation of application building and distribution that is using Xcode.

**Comment by KrauseFx** [comment]
Thanks for answering @samratBasra, I'll close the issue for now 👍
