### ISSUE TITLE
Unable to build after adding a notification content extension

### ISSUE THREAD

**Issue by Urkman** [fastlane/fastlane#9167]
I added a notification content extension to my app.
And after that I was not able to build and upload the new version to Apple...

At gym I get "Exit code 70" and "unable to package application".
I tried everything, but nothing helps.

Then I opened Organizer, there I can see every build I've done using fastlane.
I selected the last build and clicked "validate", there everything went fine and I got a "Success" message.

After that I tried again to build and submit to the App Store with fastlane and everything works fine...

And... I was able to reproduce this, as I have other app, where I added the notification content extension. Every app had the same problem and the same solution...

**Comment by PetrosIchor** [comment]
Sounds like fastlane isn't configured correctly.  Without logs, Fastfile, and environment information I can't provide very good advice. 

That said, it sounds like the signing step when packaging your app is incorrect.  While the building is fine, signing prevents it from fully finishing. 

Check you signing and projects structure to ensure fastlane is using the same assets.
