### ISSUE TITLE
Gym recompiles all frameworks for every app target

### ISSUE THREAD

**Issue by MortenGregersen** [fastlane/fastlane#9168]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We have 12 different apps which shares the same code base. The only difference between the apps are some graphics, texts, bundle identifier, signing identity and a couple of source files.

The shared code for the apps are placed in 5 frameworks (more will come) and all app targets embed these frameworks. All Xcode projects (both the app project and the framework projects) are on the top level in a Xcode Workspace. Some of the frameworks are dependent on some of the other frameworks (fx feature framework depend on core framework).

In fastlane/Gymfile we have the following line (not sure if it affects this problem):
```ruby
output_directory "./build"
```

#### The problem

When building with Xcode or the `xcodebuild` action in fastlane like this,

```ruby
gym(
    scheme: ENV['SCHEME_NAME'],
    configuration:'Adhoc',
    xcargs: "FASTLANE_LDFLAGS='$(inherited) -force_load $(PWD)/calabash.framework/calabash' GCC_PREPROCESSOR_DEFINITIONS='$(inherited) BD_ENV_S=1'"
)
```

all the apps built use **the same** built versions of the frameworks. We see the following structure in the derived data folder:

- &lt;Workspace name&gt;-&lt;random id&gt;
	- Build
		- Products
			- &lt;Configuration&gt;-iphoneos
				- &lt;Frameworks and .apps&gt;

When building with the `gym` action in fastlane like this,

```ruby
gym(
    scheme: ENV['SCHEME_NAME'],
    configuration:'Adhoc',
    xcargs: "FASTLANE_LDFLAGS='$(inherited) -force_load $(PWD)/calabash.framework/calabash' GCC_PREPROCESSOR_DEFINITIONS='$(inherited) BD_ENV_S=1'"
)
```	
all the apps built use **their own** built versions of the frameworks and needs to compile every framework for every app target. We see the following structure in the derived data folder:

- &lt;Workspace name&gt;-&lt;random id&gt;
	- Build
		- Intermediates
			- ArchiveIntermediates
				- &lt;Scheme or target name&gt;
					- IntermediateBuildFilesPath
						- UninstalledProducts
							- iphoneos
								- &lt;Frameworks&gt;
					- BuildProductsPath
						- &lt;Configuration&gt;-iphoneos
							- &lt;.app&gt;
				- &lt;Other scheme or target name&gt;
					- IntermediateBuildFilesPath
						- UninstalledProducts
							- iphoneos
								- &lt;Frameworks&gt;
					- BuildProductsPath
						- &lt;Configuration&gt;-iphoneos
							- &lt;.app&gt;

How do we get gym to reuse the built frameworks for every app target? It could save us about **99%** of the compile time as almost all of the code lives in the frameworks.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.4                                          |
| Ruby                        | 2.3.3                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.11.0 (Apple Git-81)                |
| Installation Source         | /usr/local/opt/rbenv/versions/2.3.3/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)                        |
| Ruby Lib Dir                | /usr/local/opt/rbenv/versions/2.3.3/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 8.3.2                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
I can't show you all of our _Fastfile_ but have included the call to gym

```ruby
gym(
    scheme: ENV['SCHEME_NAME'],
    configuration:'Adhoc',
    xcargs: "FASTLANE_LDFLAGS='$(inherited) -force_load $(PWD)/calabash.framework/calabash' GCC_PREPROCESSOR_DEFINITIONS='$(inherited) BD_ENV_S=1'"
)
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin              | Version | Update-Status      |
| ------------------- | ------- | ------------------ |
| fastlane-plugin-ftp | 0.1.5   | 🚫 Update available |
_From forked repo_

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.14.6       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| awesome_print             | 1.7.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.3        |
| gherkin                   | 4.1.3        |
| cucumber-core             | 1.5.0        |
| cucumber-wire             | 0.0.1        |
| diff-lcs                  | 1.3          |
| multi_json                | 1.12.1       |
| multi_test                | 0.1.2        |
| cucumber                  | 2.4.0        |
| escape                    | 0.0.4        |
| httpclient                | 2.8.3        |
| json                      | 1.8.6        |
| retriable                 | 2.0.2        |
| thor                      | 0.19.4       |
| luffa                     | 2.0.0        |
| rubyzip                   | 1.2.1        |
| slowhandcuke              | 0.0.3        |
| calabash-android          | 0.9.0        |
| clipboard                 | 1.1.1        |
| edn                       | 1.1.1        |
| geocoder                  | 1.4.3        |
| command_runner_ng         | 0.1.2        |
| i18n                      | 0.8.1        |
| run_loop                  | 2.4.1        |
| calabash-cucumber         | 0.20.5       |
| ffi                       | 1.9.18       |
| childprocess              | 0.7.0        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| colorize                  | 0.8.1        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| easter                    | 0.1.2        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| xcpretty-travis-formatter | 0.0.4        |
| fastlane-plugin-ftp       | 0.1.5        |
| mustermann                | 1.0.0        |
| power_assert              | 1.0.2        |
| rack                      | 2.0.2        |
| rack-protection           | 2.0.0        |
| tilt                      | 2.0.7        |
| sinatra                   | 2.0.0        |
| test-unit                 | 3.2.3        |
</details>

*generated on:* **2017-05-15**
</details>

**Comment by MortenGregersen** [comment]
It's not releated to code signing.

**Comment by MortenGregersen** [comment]
@KrauseFx Any comments?

**Comment by hjanuschka** [comment]
@MortenGregersen 🤚 hey.

can you try setting: `derived_data_path` on `gym`  to a folder that stays available to bypass the random folder name?

also try to set `clean` to false, and see if it improves your build time.
let me know if this helps.

**Comment by MortenGregersen** [comment]
@hjanuschka Thank you for the answer. I will try that tomorrow!

**Comment by MortenGregersen** [comment]
@hjanuschka It didn't help with the `derived_data_path`.

The structure of the directory specified to `derived_data_path` is the same as before. It's just placed in my folder instead of Xcode's DerivedData.

I didn't try `clean` as it doesn't clean right now as far as I can see.

I've included an update `env` as I've updated gems since last time, and added `derived_data_path`.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.5                                          |
| Ruby                        | 2.3.3                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.11.0 (Apple Git-81)                |
| Installation Source         | /usr/local/opt/rbenv/versions/2.3.3/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                         |
| Ruby Lib Dir                | /usr/local/opt/rbenv/versions/2.3.3/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 8.3.3                                            |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :s do
  gym(
    scheme: ENV['SCHEME_NAME'],
    configuration: 'Adhoc',
    derived_data_path: File.join($device_output_dir, 'DerivedData'),
    xcargs: "#{link_calabash} GCC_PREPROCESSOR_DEFINITIONS='$(inherited) BD_ENV_S=1' SYMROOT=$(PWD)/#{$device_output_dir}"
)
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin              | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane-plugin-ftp | 0.1.3   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 1.8.6        |
| io-console                | 0.4.5        |
| excon                     | 0.56.0       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| fastlane-plugin-ftp       | 0.1.3        |
</details>


*generated on:* **2017-06-08**
</details>

**Comment by coreylendo** [comment]
Get

Sent from my iPhone

On Aug 7, 2017, at 3:32 AM, fastlane bot <notifications@github.com> wrote:

There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

Please make sure to update to the latest fastlane version and check if that solves the issue. Let us know if that works for you by adding a comment 👍

**Comment by MortenGregersen** [comment]
I just checked with the newest version of `fastlane` (2.51.0). This is still an issue.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.6                                          |
| Ruby                        | 2.3.3                                            |
| Bundler?                    | true                                             |
| Git                         | git version 2.11.0 (Apple Git-81)                |
| Installation Source         | /usr/local/opt/rbenv/versions/2.3.3/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                         |
| Ruby Lib Dir                | /usr/local/opt/rbenv/versions/2.3.3/lib          |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/      |
| Xcode Version               | 8.3.3                                            |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# -*- coding: utf-8 -*-
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.29.0'
skip_docs if is_ci?

default_platform :ios

platform :ios do

  lane :build_s do
    gym(
      scheme: ENV['SCHEME_NAME'],
      configuration: 'Adhoc',
      derived_data_path: File.join($device_output_dir, 'DerivedData'),
      xcargs: "#{link_calabash} GCC_PREPROCESSOR_DEFINITIONS='$(inherited) BD_ENV_S=1' SYMROOT=$(PWD)/#{$device_output_dir}"
    )
  end

  def link_calabash
    extra_args = ''
    unless $settings.skip_link_calabash
      extra_args = "FASTLANE_LDFLAGS='$(inherited) -force_load $(PWD)/calabash.framework/calabash'"
      unless ENV['INSTALLED_CALABASH']
        Dir.chdir("..") do
          sh "gem install calabash-cucumber"
          sh "rm -rf calabash.framework"
          sh "calabash-ios download"
          UI.message "Downloaded calabash version #{`calabash-ios version`.strip!}. If a newer version is needed, run 'bundle update'"
          ENV['INSTALLED_CALABASH'] = '1'
        end
      end
    end
    extra_args
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.51.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

| Plugin              | Version | Update-Status      |
| ------------------- | ------- | ------------------ |
| fastlane-plugin-ftp | 0.1.5   | 🚫 Update available |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.15.3       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| awesome_print             | 1.8.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.3        |
| gherkin                   | 4.1.3        |
| cucumber-core             | 1.5.0        |
| cucumber-wire             | 0.0.1        |
| diff-lcs                  | 1.3          |
| multi_json                | 1.12.1       |
| multi_test                | 0.1.2        |
| cucumber                  | 2.4.0        |
| escape                    | 0.0.4        |
| httpclient                | 2.8.3        |
| json                      | 1.8.6        |
| retriable                 | 2.0.2        |
| thor                      | 0.19.4       |
| luffa                     | 2.0.0        |
| rubyzip                   | 1.2.1        |
| slowhandcuke              | 0.0.3        |
| calabash-android          | 0.9.0        |
| clipboard                 | 1.1.1        |
| edn                       | 1.1.1        |
| geocoder                  | 1.4.4        |
| command_runner_ng         | 0.1.3        |
| i18n                      | 0.8.6        |
| run_loop                  | 2.4.1        |
| calabash-cucumber         | 0.20.5       |
| ffi                       | 1.9.18       |
| childprocess              | 0.7.1        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| colorize                  | 0.8.1        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| easter                    | 0.1.2        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| fastlane-plugin-ftp       | 0.1.5        |
| mustermann                | 1.0.0        |
| power_assert              | 1.0.2        |
| rack                      | 2.0.3        |
| rack-protection           | 2.0.0        |
| tilt                      | 2.0.8        |
| sinatra                   | 2.0.0        |
| test-unit                 | 3.2.5        |
</details>


*generated on:* **2017-08-09**
</details>

**Comment by MortenGregersen** [comment]
@hjanuschka Is there anything I can do to help this issue forward?

**Comment by ernesto** [comment]
Hey, similar problem here. Any news, @MortenGregersen ?

**Comment by MortenGregersen** [comment]
No, I haven’t heard anything. I’m not sure how to help with the issue, so I need somebody eith knowledge about gym to take a look at it.
