### ISSUE TITLE
Windows support, plus support for the Windows Store

### ISSUE THREAD

**Issue by ndbroadbent** [fastlane/fastlane#9172]
Hello! I've seen #7202, but I think it would be awesome if Windows was a supported platform. Not only to build and upload Android apps, but also to build Windows UWP apps and upload them to the Windows store. I might be missing something, but the Visual Studio integration is not very strong. (If you click "Upload App Packages", it just opens the store webpage where you upload the package.)

I'm working on a React Native app, and it's awesome that I can write code that runs almost everywhere. (I've got one codebase running on iOS, Android, web, and Windows UWP.) It would be amazing if I could use fastlane to upload everything to all of the stores.

Is there somewhere I can read about the list of Windows incompatibilities? I saw that #7202 was a WIP PR, but I'm not sure how much more work would be involved. I'm a Ruby developer, and I don't think that cross-platform support is too difficult with many Ruby libraries. I would be happy to help build and maintain this feature, and I'm sure there are a lot of Android and Windows developers who would use it.

**Comment by KrauseFx** [comment]
Hey @ndbroadbent, thanks for submitting this issue. For now, we don't plan on supporting Windows as a platform. We're working on some really cool features for the iOS and Android platform, so we don't have the resources to build support for a new platform right now.

**Comment by ndbroadbent** [comment]
OK no worries, that makes sense! I might try to build a plugin for this eventually
