### ISSUE TITLE
Can't run tests with bundle exec rspec

### ISSUE THREAD

**Issue by joelklabo** [fastlane/fastlane#9177]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Having trouble getting the tests to run. Using `bundle exec rspec` in root directory.

Main error I am seeing: 
`Could not load native IDN implementation.
LoadError: cannot load such file -- rack/mount`

FULL OUTPUT

`$>
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Changing stdout to /tmp/fastlane_tests, set `DEBUG` environment variable to print to stdout (e.g. when using `pry`)
/Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.1/spec/addressable/idna_spec.rb:145: warning: already initialized constant LONG
/Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.1/spec/addressable/idna_spec.rb:29: warning: previous definition of LONG was here
Could not load native IDN implementation.
LoadError: cannot load such file -- rack/mount
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.1/spec/addressable/rack_mount_compat_spec.rb:21:in `require'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.1/spec/addressable/rack_mount_compat_spec.rb:21:in `<top (required)>'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/bin/rspec:22:in `load'
  /Users/joelklabo/src/fastlane/vendor/bundle/ruby/2.4.0/bin/rspec:22:in `<top (required)>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 10.12.5                                              |
| Ruby                        | 2.4.1                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.11.0 (Apple Git-81)                    |
| Installation Source         | ~/src/fastlane/vendor/bundle/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                             |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                          |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 8.3                                                  |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
skip_docs

desc "Runs the unit tests and other verifications for the fastlane repo"
lane :test do |options|
  validate_repo
end

desc "Increment the version number of this gem"
lane :bump do |options|
  ensure_git_branch(branch: "master")
  ensure_git_status_clean

  github_api_token = ENV["FL_GITHUB_RELEASE_API_TOKEN"]
  UI.user_error!("Please provide a GitHub API token using `FL_GITHUB_RELEASE_API_TOKEN`") if github_api_token.to_s.length == 0

  path = "./fastlane/lib/fastlane/version.rb"

  # Verify everything is in a consistent state
  latest_version = current_version
  local_version = version_get_podspec(path: path)
  UI.user_error!("Version on RubyGems doesn't match local repo: #{latest_version} != #{local_version}") if latest_version != local_version

  changelog_text = show_changelog

  bump_type ||= 'minor' if prompt(text: "New feature, method or API?", boolean: true)
  bump_type ||= 'patch'

  slug = "fastlane/fastlane"
  new_version = version_bump_podspec(path: path, bump_type: bump_type)
  sh "git checkout -b 'version-bump-#{new_version}'"
  commit_message = "Version bump to #{new_version}"
  git_commit(path: path,
             message: commit_message)
  push_to_git_remote

  pr_body = ["Auto-generated by fastlane 🤖"]
  pr_body << "**Changes since release '#{latest_version}':**"
  pr_body << changelog_text
  pr_url = create_pull_request(
    api_token: github_api_token,
    repo: slug,
    title: commit_message,
    body: pr_body.join("\n\n")
  )

  if ENV['SLACK_URL']
    slack(
      channel: "action",
      default_payloads: [],
      message: "Version bump: #{pr_url} ✨",
      payload: {}
    )
  end

  # Revert to master branch
  sh "git checkout master"
end

desc "Does everything that's needed for a release"
desc "This includes running tests and verifying the GitHub release"
lane :release do
  slack_train_start(distance: 2,
                       train: "🚀",
           reverse_direction: true,
                        rail: "✨")

  update_fastlane
  slack_train

  # Git verification
  #
  ensure_git_status_clean
  ensure_git_branch(branch: 'master')
  git_pull

  validate_repo

  # Verifying RubyGems version
  #
  require "../fastlane/lib/fastlane/version.rb"
  version = Fastlane::VERSION
  old_version = current_version
  puts "Deploying #{version}"
  if Gem::Version.new(version) <= Gem::Version.new(old_version)
    UI.user_error!("Version number #{version} was already deployed")
  end

  # Then push to git remote
  #
  push_to_git_remote

  # Preparing GitHub Release
  #
  github_release = get_github_release(url: "fastlane/fastlane", version: version)
  if (github_release || {}).fetch('body', '').length == 0
    show_changelog(old_version: old_version)

    title = prompt(text: 'Title: ')
    description = prompt(text: "Please enter a changelog (make sure to rephrase changes to make it easy to understand, and remove non-important changes that don't affect the end-user): ",
                         multi_line_end_keyword: "END")

    github_release = set_github_release(
      repository_name: "fastlane/fastlane",
      name: [version, title].join(" "),
      tag_name: version,
      description: description,
      is_draft: false
    )

    # Actual release of the gem
    #
    sh "gem push ../pkg/fastlane-#{version}.gem"

    release_url = github_release['html_url']

    message = [title, description, release_url].join("\n\n")
    add_fastlane_git_tag(tag: "fastlane/#{version}", message: message)
  end

  # After publishing
  #
  if ENV['SLACK_URL']
    release_notes = github_release['body']
    # markup - turn github references into links
    release_notes.gsub!(/\(#([0-9]+)\)/, '(<https://github.com/fastlane/fastlane/issues/\1|#\1>)')
    slack_message = "Successfully released [fastlane #{version}](#{release_url}) :rocket:"
    slack(
      channel: "releases",
      default_payloads: [],
      message: slack_message,
      payload: {
        "New" => release_notes
      }
    )
    slack(channel: "action", default_payloads: [], message: slack_message)
  end

  clubmate
  donate_food

  puts "You can now tweet:".green
  releases_url = "https://github.com/fastlane/fastlane/releases/tag/#{version}"
  puts "[fastlane] #{github_release['name']} #{releases_url}"

  send_mac_app_ci_reminder

  update_docs
  slack_train
end

desc "Makes sure the tests on https://docs.fastlane.tools still work with the latest version"
lane :verify_docs do
  clone_docs do
    Bundler.with_clean_env do
      puts `sed -i -e "s/activate_bin_path/bin_path/g" $(which bundle)` # workaround for bundler https://github.com/bundler/bundler/issues/4602#issuecomment-233619696
      sh "bundle install"
      sh "bundle exec fastlane test skip_building:true" # skip_building since we don't have a proper python environment set up
    end
  end
end

desc "Generates the actions.md that will get used on https://docs.fastlane.tools"
desc "This will NOT also automatically submit a pull request to fastlane/docs"
desc "This SHOULD only be used for testing changes to the docs"
lane :test_generate_docs do
  ENV['USE_ENHANCE_TEST_DATA'] = "true"
  generate_markdown_docs
  ENV.delete("USE_ENHANCE_TEST_DATA")
end

desc "Update the actions.md on https://docs.fastlane.tools"
desc "This will also automatically submit a pull request to fastlane/docs"
lane :update_docs do
  if ENV["ENHANCER_USER"].to_s.length == 0 || ENV["ENHANCER_PASSWORD"].to_s.length == 0
    UI.error("No ENHANCER_USER or ENHANCER_PASSWORD environment variables found, which are required to generate a new Actions.md")
    next
  end

  clone_docs do
    actions_md_path = generate_markdown_docs

    Bundler.with_clean_env do
      sh "bundle update"
    end

    if `git status --porcelain`.length == 0
      UI.success("No changes in the actions.md ✅")
    else
      # Create a new branch
      sh "git checkout -b 'update-actions-md-#{Time.now.to_i}'"

      Dir.chdir("fastlane") do # this is an assumption of fastlane, that we have to .. when shelling out
        # Commit the changes
        git_commit(path: [actions_md_path, "Gemfile.lock"], message: "Update actions.md for latest fastlane release 🚀")
        # Push them to the git remote
        push_to_git_remote

        # Submit the pull request
        pr_url = create_pull_request(
          api_token: ENV["FL_GITHUB_RELEASE_API_TOKEN"],
          repo: "fastlane/docs",
          title: "[Bot] Update actions.md for latest fastlane release 🚀",
          body: "Auto-generated by _fastlane_ bot 🤖"
        )
        UI.success("Successfully submitted a pull request to fastlane/docs: #{pr_url} 🚀")
      end
    end
  end
end

def generate_markdown_docs
  require 'fastlane/documentation/markdown_docs_generator'
  actions_md_path = File.expand_path("docs/actions.md")
  Fastlane::MarkdownDocsGenerator.new.generate!(target_path: actions_md_path)

  return actions_md_path
end

def clone_docs
  require 'tmpdir'
  git_url = ENV['FASTLANE_DOCS_GIT_URL'] || "https://github.com/fastlane/docs"

  Dir.mktmpdir("fl_clone") do |tmp_dir|
    Dir.chdir(tmp_dir) do
      sh "git clone #{git_url} --depth=1"
      Dir.chdir("docs") do
        yield
      end
    end
  end
end

error do |lane, exception|
  if ENV['SLACK_URL']
    slack(channel: "testing", message: exception.to_s, success: false)
  end
  slack_train_crash
end

private_lane :send_mac_app_ci_reminder do
  if ENV['FABRIC_SLACK_URL']
    slack(
      slack_url: ENV['FABRIC_SLACK_URL'],
      channel: 'deployment-tools',
      default_payloads: [],
      message: "Please run the Fastlane Mac App Package CI job in TeamCity\n#{ENV['FABRIC_MAC_APP_CI_JOB_URL']}"
    )
  end
end

desc "Verifies all tests pass and the current state of the repo is valid"
private_lane :validate_repo do
  # Verifying that no debug code is in the code base
  #
  ensure_no_debug_code(text: "binding.pry", extension: ".rb", exclude: "playground.rb", exclude_dirs: ["\.bundle"]) # debugging code
  ensure_no_debug_code(text: "# TODO", extension: ".rb", exclude_dirs: ["\.bundle"]) # TODOs
  ensure_no_debug_code(text: "now: ", extension: ".rb", exclude_dirs: ["\.bundle"]) # rspec focus
  ensure_no_debug_code(text: "<<<<<<<", extension: ".rb", exclude_dirs: ["\.bundle"]) # Merge conflict

  # spaceship and credentials_manager don't have access to fastlane_core
  ensure_no_debug_code(text: " UI\\.", path: "spaceship/lib", extension: ".rb", exclude_dirs: ["\.bundle"])
  ensure_no_debug_code(text: " UI\\.", path: "credentials_manager/lib", extension: ".rb", exclude_dirs: ["\.bundle"])

  rubocop

  # Verifying the --help command
  #
  # tools_to_test = Fastlane::TOOLS
  tools_to_test = [:fastlane] # until we have the binaries for all tools included here
  tools_to_test.each do |tool_name|
    next if no_binary.include?(tool_name)
    Dir.chdir("..") do
      binary_path = File.join("bin", tool_name.to_s)
      content = sh("PAGER=cat #{binary_path} --help")
      ["--version", "https://fastlane.tools", tool_name.to_s].each do |current|
        UI.user_error!("--help missing information: '#{current}'") unless content.include?(current)
      end
    end
  end

  Dir.chdir("..") do
    # Install the bundle and the actual gem
    sh "bundle check || bundle install"
    sh "rake install"

    # Run the tests
    #
    sh "bundle exec rake test_all"

    # Verify shell code style
    sh 'find -E . -regex ".*\.(sh|bash)" -not -name "Pods-*" -name ".bundle" -exec shellcheck {} +'
  end

  test_generate_docs
  ensure_code_samples

  # Verify docs are still working
  verify_docs
end

desc "Get the version number of the last release"
private_lane :current_version do
  puts "Checking the latest version on RubyGems"
  download(url: "https://rubygems.org/api/v1/gems/fastlane.json")["version"]
end

desc "All repos that don't have a binary to test"
private_lane :no_binary do
  ['fastlane_core', 'spaceship', 'credentials_manager']
end

desc "Print out the changelog since the last tagged release and open the GitHub page with the changes"
lane :show_changelog do |options|
  old_version = options[:old_version] || current_version

  changes = sh("git log --pretty='* %s via %aN' #{old_version}...HEAD --no-merges ..", log: $verbose).gsub("\n\n", "\n")
  changes.gsub!("[WIP]", "") # sometimes a [WIP] is merged

  github_diff_url = "https://github.com/fastlane/fastlane/compare/#{old_version}...master"
  sh "open #{github_diff_url}"

  puts "Changes since release #{old_version}:\n\n#{changes.cyan}"
  changes # return the text without the modified colors
end

desc "Add a git tag in the fastlane repo for this release"
private_lane :add_fastlane_git_tag do |options|
  `git tag -am #{options[:message].shellescape} #{options[:tag].shellescape}`
  push_git_tags
end

# Run the code samples, yo
private_lane :ensure_code_samples do
  UI.message "<U+1F557>  Verifying all code samples work with the latest fastlane release"
  test_sample_code(path: File.expand_path("docs/Actions.md"))
  UI.success "<U+2705>  All fastlane code samples work as expected"
end

lane :donate_food do
  if ENV["SHARETHEMEAL_USERHASH"].to_s.length > 0
    sharethemeal(
      amount: "0.5",
      currency: "USD",
      team_id: "fastlane"
    )
  end
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                       | Version | Update-Status |
| ---------------------------- | ------- | ------------- |
| fastlane-plugin-ruby         | 0.1.3   | ✅ Up-To-Date  |
| fastlane-plugin-clubmate     | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-sharethemeal | 0.1.9   | ✅ Up-To-Date  |
| fastlane-plugin-slack_train  | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                          | Version      |
| ---------------------------- | ------------ |
| did_you_mean                 | 1.1.0        |
| bundler                      | 1.14.6       |
| io-console                   | 0.4.6        |
| rake                         | 11.3.0       |
| CFPropertyList               | 2.3.5        |
| public_suffix                | 2.0.5        |
| addressable                  | 2.5.1        |
| ast                          | 2.3.0        |
| babosa                       | 1.0.2        |
| debug_inspector              | 0.0.3        |
| binding_of_caller            | 0.7.2        |
| builder                      | 3.2.3        |
| byebug                       | 9.0.6        |
| claide                       | 1.0.1        |
| colored2                     | 3.1.2        |
| cork                         | 0.3.0        |
| nap                          | 1.1.0        |
| open4                        | 1.3.4        |
| claide-plugins               | 0.9.2        |
| coderay                      | 1.1.1        |
| colored                      | 1.2          |
| highline                     | 1.7.8        |
| commander-fastlane           | 4.4.4        |
| json                         | 2.1.0        |
| docile                       | 1.1.5        |
| simplecov-html               | 0.10.0       |
| simplecov                    | 0.14.1       |
| tins                         | 1.13.3       |
| term-ansicolor               | 1.6.0        |
| thor                         | 0.19.4       |
| coveralls                    | 0.8.21       |
| safe_yaml                    | 1.0.4        |
| crack                        | 0.4.3        |
| multipart-post               | 2.0.0        |
| faraday                      | 0.12.1       |
| faraday-http-cache           | 1.3.1        |
| git                          | 1.3.0        |
| kramdown                     | 1.13.2       |
| sawyer                       | 0.8.1        |
| octokit                      | 4.7.0        |
| unicode-display_width        | 1.1.3        |
| terminal-table               | 1.7.3        |
| danger                       | 4.3.5        |
| ox                           | 2.5.0        |
| danger-junit                 | 0.7.3        |
| diff-lcs                     | 1.3          |
| unf_ext                      | 0.0.7.4      |
| unf                          | 0.1.4        |
| domain_name                  | 0.5.20170404 |
| dotenv                       | 2.2.1        |
| excon                        | 0.55.0       |
| fakefs                       | 0.8.1        |
| http-cookie                  | 1.0.3        |
| faraday-cookie_jar           | 0.0.6        |
| faraday_middleware           | 0.11.0.1     |
| fastimage                    | 2.1.0        |
| gh_inspector                 | 1.0.3        |
| jwt                          | 1.5.6        |
| little-plugger               | 1.1.4        |
| multi_json                   | 1.12.1       |
| logging                      | 2.2.2        |
| memoist                      | 0.15.0       |
| os                           | 0.9.6        |
| signet                       | 0.7.3        |
| googleauth                   | 0.5.1        |
| httpclient                   | 2.8.3        |
| hurley                       | 0.2          |
| mime-types                   | 1.25.1       |
| uber                         | 0.0.15       |
| representable                | 2.3.0        |
| retriable                    | 2.1.0        |
| google-api-client            | 0.9.28       |
| mini_magick                  | 4.5.1        |
| multi_xml                    | 0.6.0        |
| plist                        | 3.3.0        |
| rubyzip                      | 1.2.1        |
| security                     | 0.1.3        |
| slack-notifier               | 1.5.1        |
| terminal-notifier            | 1.8.0        |
| tty-screen                   | 0.5.0        |
| word_wrap                    | 1.0.0        |
| nanaimo                      | 0.2.3        |
| xcodeproj                    | 1.4.4        |
| rouge                        | 2.0.7        |
| xcpretty                     | 0.2.8        |
| xcpretty-travis-formatter    | 0.0.4        |
| fastlane-plugin-clubmate     | 0.1.0        |
| fastlane-plugin-ruby         | 0.1.3        |
| rest-client                  | 1.6.9        |
| stm_api                      | 0.1.7        |
| fastlane-plugin-sharethemeal | 0.1.9        |
| fastlane-plugin-slack_train  | 0.2.0        |
| hashdiff                     | 0.3.4        |
| interception                 | 0.5          |
| method_source                | 0.8.2        |
| parser                       | 2.4.0.0      |
| powerpack                    | 0.1.1        |
| slop                         | 3.6.0        |
| pry                          | 0.10.4       |
| pry-byebug                   | 3.4.2        |
| pry-rescue                   | 1.4.5        |
| pry-stack_explorer           | 0.4.9.2      |
| rack                         | 1.6.7        |
| rack-protection              | 1.5.3        |
| rainbow                      | 2.2.2        |
| rb-readline                  | 0.5.4        |
| rspec-support                | 3.5.0        |
| rspec-core                   | 3.5.4        |
| rspec-expectations           | 3.5.0        |
| rspec-mocks                  | 3.5.0        |
| rspec                        | 3.5.0        |
| rspec_junit_formatter        | 0.2.3        |
| ruby-progressbar             | 1.8.1        |
| rubocop                      | 0.48.1       |
| tilt                         | 2.0.7        |
| sinatra                      | 1.4.8        |
| webmock                      | 2.3.2        |
| xcode-install                | 2.1.1        |
| yard                         | 0.8.7.6      |
</details>

*generated on:* **2017-05-15**
</details>

**Comment by col** [comment]
@joelklabo I'm having the same issue trying to run the tests. Did you resolve this issue? If so, how?

**Comment by ohayon** [comment]
Hmm, apologies if this is a stupid question, but could you try running `bundle update` to make sure that `rack/mount` is available to your bundle? Let us know if you are still having issues after doing that and we will be happy to help! 😄  🐙  🚀

**Comment by humblehacker** [comment]
I'm having the same problem, and `bundle update` did not update anything.

**Comment by nbrice88** [comment]
Unfortunately I'm having the identical problem to the original poster, running `bundle update` did not solve the issue.

Output of `bundle exec rspec` from the fastlane root is below:
```
$ bundle exec rspec
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Changing stdout to /tmp/fastlane_tests, set `DEBUG` environment variable to print to stdout (e.g. when using `pry`)
/Users/workingDir/fastlane/vendor/bundle/gems/addressable-2.5.2/spec/addressable/idna_spec.rb:151: warning: already initialized constant LONG
/Users/workingDir/fastlane/vendor/bundle/gems/addressable-2.5.2/spec/addressable/idna_spec.rb:29: warning: previous definition of LONG was here
Could not load native IDN implementation.
LoadError: cannot load such file -- rack/mount
  /Users/workingDir/fastlane/vendor/bundle/gems/addressable-2.5.2/spec/addressable/rack_mount_compat_spec.rb:21:in `require'
  /Users/workingDir/fastlane/vendor/bundle/gems/addressable-2.5.2/spec/addressable/rack_mount_compat_spec.rb:21:in `<top (required)>'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/workingDir/fastlane/vendor/bundle/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
  /Users/workingDir/fastlane/vendor/bundle/bin/rspec:23:in `load'
  /Users/workingDir/fastlane/vendor/bundle/bin/rspec:23:in `<top (required)>'
```

Any thoughts @ohayon ?

**Comment by KrauseFx** [comment]
Are you trying to run the unit tests of fastlane?

**Comment by janpio** [comment]
I am getting the same error when running the tests on Ubuntu:

```
foo@foo-VirtualBox:~/fastlane$ DEBUG=1 bundle exec rake
rspec --pattern ./**/*_spec.rb --format progress
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
/home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/spec/addressable/idna_spec.rb:151: warning: already initialized constant LONG
/home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/spec/addressable/idna_spec.rb:29: warning: previous definition of LONG was here
Could not load native IDN implementation.
[Coveralls] Outside the CI environment, not sending data.
/home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/spec/addressable/rack_mount_compat_spec.rb:21:in `require': cannot load such file -- rack/mount (LoadError)
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/addressable-2.5.2/spec/addressable/rack_mount_compat_spec.rb:21:in `<top (required)>'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/bin/rspec:23:in `load'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/bin/rspec:23:in `<main>'
rake aborted!
Command failed with status (1): [rspec --pattern ./**/*_spec.rb --format pr...]
/home/foo/fastlane/Rakefile:19:in `block in <top (required)>'
/home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/foo/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/home/foo/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
Tasks: TOP => default => test_all
(See full trace by running task with --trace)
foo@foo-VirtualBox:~/fastlane$ 
```

Could anyone of you fix it somehow? I have no idea where/how to start.

**Comment by janpio** [comment]
Looking at the stacktraces we all posted, it seems `bundle exec rspec`, `bundle exec rake` or even `bundle exec rake test_all` is actually executing tests of the `adresseable` gem - which doesn't make any sense!?

**Comment by janpio** [comment]
Indeed, deleting the `spec` folder of the addressable gem gives this error message:

```
foo@foo-VirtualBox:~/fastlane$ bundle exec rake test_all
rspec --pattern ./**/*_spec.rb --format progress
[Coveralls] Set up the SimpleCov formatter.
[Coveralls] Using SimpleCov's default settings.
Changing stdout to /tmp/fastlane_tests, set `DEBUG` environment variable to print to stdout (e.g. when using `pry`)
/home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/babosa-1.0.2/lib/babosa/utf8/active_support_proxy.rb:1:in `require': cannot load such file -- active_support (LoadError)
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/babosa-1.0.2/lib/babosa/utf8/active_support_proxy.rb:1:in `<top (required)>'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/babosa-1.0.2/spec/utf8_proxy_spec.rb:4:in `require'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/babosa-1.0.2/spec/utf8_proxy_spec.rb:4:in `<top (required)>'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/bin/rspec:23:in `load'
	from /home/foo/fastlane/vendor/bundle/ruby/2.4.0/bin/rspec:23:in `<main>'
rake aborted!
Command failed with status (1): [rspec --pattern ./**/*_spec.rb --format pr...]
/home/foo/fastlane/Rakefile:19:in `block in <top (required)>'
/home/foo/fastlane/vendor/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/foo/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/home/foo/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
Tasks: TOP => test_all
(See full trace by running task with --trace)
foo@foo-VirtualBox:~/fastlane$ 
```
This is the next gem with a `spec` folder.

Why is it running tests of gems?

**Comment by janpio** [comment]
Because in Ubuntu (or at least the way we set it up, even if accidentally), unlike in other installations, the gems are installed in the `vendor` folder of our project. The rspec pattern `rspec --pattern ./**/*_spec.rb --format progress` includes that, so dutifully executes these files.

**Comment by janpio** [comment]
We all probably have this:

```
foo@foo-VirtualBox:~/fastlane$ bundle config
Settings are listed in order of priority. The top value will be used.
path
Set for your local app (/home/foo/fastlane/.bundle/config): "vendor/bundle"
```

I think you get instructions to do this when you try to run `bundle install` with the system ruby. We probably all did this when we first checked out fastlane and messed up our project that way.

Now to find out how to change that...

**Comment by janpio** [comment]
Solution:

- Delete `.bundle`
- Delete `vendor`
- Run `bundle install` again
- Tests work with `bundle exec rake`

(You can check where individual gems are installed with e.g. `bundle info addressable`)
