### ISSUE TITLE
Pilot documentation for usage in a Fastfile is missing

### ISSUE THREAD

**Issue by remcohaszing** [fastlane/fastlane#9178]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Pilot is missing documentation on how to use it in a Fastfile. Running adding `pilot` to a lane appears to be the same as running `fastlane pilot upload`. Is it also possible to run the other `pilot` subcommands from within a fastfile, such as importing testers?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

—

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

—

**Comment by hjanuschka** [comment]
hi @remcohaszing  🤚  

the documentation about the `pilot`action is here: https://docs.fastlane.tools/actions/#pilot

the sub commands of pilot are not directly invocable via fastfile.
however you can run pilot from with fastfile:

e.g.:

```ruby
sh("fastlane pilot subcommand")
```

**Comment by remcohaszing** [comment]
I guess I should've looked there instead of in the Pilot readme. Anyway, thanks for the reply!

**Comment by KrauseFx** [comment]
Thanks everyone 👍
