### ISSUE TITLE
How can I scan specific target in single build?

### ISSUE THREAD

**Issue by junjielu** [fastlane/fastlane#9179]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Since we develop app with different test target, we need to test single target to ensure the target healthy.However, I didn't find a way to use `scan` to test single target.Is there any way to solve it?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
You can only pass a scheme. You could make a scheme for each target, right?
