### ISSUE TITLE
ERROR Failure to decode and install provisioning profile Jenkins

### ISSUE THREAD

**Issue by jlfeck** [fastlane/fastlane#9182]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

INFO [2017-05-16 12:16:07.36]: Installing provisioning profile...
ERROR [2017-05-16 12:16:07.39]: Failure to decode /var/folders/t6/wzlv2fwn09s5y1p_ly2n528h0000gy/T/d20170516-34017-3lwtmb/profiles/appstore/AppStore_[App ID].mobileprovision. Exit: 1: security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: write permissions error
security: problem decoding

ERROR [2017-05-16 12:16:07.39]: Error parsing provisioning profile at path '/var/folders/t6/wzlv2fwn09s5y1p_ly2n528h0000gy/T/d20170516-34017-3lwtmb/profiles/appstore/AppStore_[App ID].mobileprovision'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.28.8"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
    sh 'mkdir ../build || true'
    sh 'mkdir ../reports || true'
  end

  # desc "Clean keychain"
  # lane :keychain do
  #     delete_keychain(name: "name")
  # end

  desc "Runs all the tests"
  lane :test do

    args = {
      scheme: "App",
      clean: true,
      code_coverage: true,
      output_types: "html",
      output_directory: "reports"
    }

    scan(args)
  end

  desc "Build project"
  lane :build do |options|
    unlock_keychain(path: "login.keychain-db", password: "password")
    # create_keychain(
    #   name: "ios",
    #   default_keychain: true,
    #   unlock: true,
    #   timeout: 3600,
    #   password: "password",
    #   lock_when_sleeps: true
    # )

    sh "plutil -replace CFBundleSupportedPlatforms -string '' ../Pods/Backbase/BackbaseAssets.bundle/Info.plist"

    # Set default build number for local builds
  	build_number = "0.0.0.17"
    version_number = "0.0.2"

  	# Read in value in case the user has specified input params
  	if options[:build_number]
  		build_number = "0.0.0." + options[:build_number]
  	end

    if options[:version_number]
  		version_number = options[:version_number]
  	end

    increment_build_number(
  		build_number: build_number,
  		xcodeproj: "App.xcodeproj"
  	)

  	increment_version_number(
   		version_number: version_number,
    	xcodeproj: "App.xcodeproj"
  	)

    args = {
      workspace: "App.xcworkspace",
      configuration: "Release",
      scheme: "App",
  		clean: true,
  		output_directory: "build/",
      output_name: "app-" + version_number + ".ipa"

    }
    # match(app_identifier: "[App ID]", type: "appstore")
    disable_automatic_code_signing(path: "App.xcodeproj")
    match(app_identifier: "[App ID]", type: "appstore", readonly: true)
    gym(args)
    testflight(skip_waiting_for_build_processing: true)
  end
  # desc "Submit a new Beta Build to Apple TestFlight"
  # desc "This will also make sure the profile is up to date"
  # lane :beta do
  #   # match(type: "appstore") # more information: https://codesigning.guide
  #   gym # Build your app - more options available
  #   pilot
  #
  #   # sh "your_script.sh"
  #   # You can also use other beta testing services here (run `fastlane actions`)
  # end
  #
  # desc "Deploy a new version to the App Store"
  # lane :release do
  #   # match(type: "appstore")
  #   # snapshot
  #   gym # Build your app - more options available
  #   deliver(force: true)
  #   # frameit
  # end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
    hipchat(
      api_token: "TOKEN",
      api_host: "URL",
      message: "sucesso",
      message_format: "html", # or "text", defaults to "html"
      channel: "@USER",
      success: true
    )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )

    hipchat(
      api_token: "TOKEN",
      api_host: "URL",
      message: "erro",
      message_format: "html", # or "text", defaults to "html"
      channel: "@USER",
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "[App ID]" # The bundle identifier of your app
apple_id "[Apple ID]" # Your Apple email address

team_id "TEAM_ID" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.2        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.3        |
| io-console                | 0.4.6        |
</details>

**Comment by jlfeck** [comment]
Hey, i'm using the match command to import p12, but it's not working to provisioning profile.

Can you help me?

**Comment by tux-mind** [comment]
I have this issue too.
I'm using the gem `spare_keys` to have the CI build agent working without an unlocked login keychain.

The error is that [FastlaneCore::ProvisioningProfile.decode](https://github.com/fastlane/fastlane/blob/5c874db9218e035a20d11ca3fd05ae7a96bd80aa/fastlane_core/lib/fastlane_core/provisioning_profile.rb#L75) uses the default keychain instead of the provided one.

In my setup I pass the keychain via `MATCH_KEYCHAIN_NAME` environment variable, but this is used only by match, not by the above referenced `decode` function.

Thank you for your great work, best regards, tux_mind.

**Comment by taquitos** [comment]
If this is still a problem, could you attach your complete output from the tool as well? That should help us diagnose this stuff. We need output from running with: `--capture_output`, and the output from `fastlane env` 👍

**Comment by istvanp** [comment]
I had a similar output but from TeamCity:
```
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: write permissions error
security: problem decoding
```

You need to make sure your Jenkins daemon or agent is using the **`SessionCreate`** key set to **`true`** and the `security` command should no longer complain about write issues. The `UserName` should be set also. Your launch daemon file should look similar to this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>GroupName</key>
	<string>staff</string>
	<key>InitGroups</key>
	<true/>
	... TRUNCATED ...
	<key>RunAtLoad</key>
	<true/>
	<key>SessionCreate</key>
	<true/>
	<key>UserName</key>
	<string>YOUR_USERNAME_HERE</string>
</dict>
</plist>
```

Credit to this answer from StackOverflow (where the issue was with Jenkins, so check it out also): https://stackoverflow.com/a/9482707/218413
