### ISSUE TITLE
Project first time use fastlane execute script fail?

### ISSUE THREAD

**Issue by longjianjiang** [fastlane/fastlane#9184]
fastlane 2.30.2, an empty Swift project.

Then i init fastlane; here is my archive fastlane script:

```
 lane :create_ipa do 
    increment_build_number
    gym(
      scheme: "LJTestFastlane",
      output_directory:"build",
      output_name: "test.ipa"
    )
  end
```

But, every time i run `fastlane create_ipa`, it show
## Additional
i test another project that upload ipa to iTunes Connect before, i init fastlane and run same script as 
same as before, it work normal? 

So, i need some help, please give me some advice, thanks!

**Comment by PetrosIchor** [comment]
The error tells you what is missing. CURRENT_PROJECT_VERSION is not found. Check your project and add that key.

**Comment by KrauseFx** [comment]
Thanks @PetrosIchor 👍  Make sure to follow the guide  provides https://developer.apple.com/library/content/qa/qa1827/_index.html

**Comment by longjianjiang** [comment]
thanks guys , i add that key, fastlane works fine!

### But
as i said before, i add fastlane to my old project that be uploaded ipa to iTunes Connect before, this project didn't set this key at all, but fastlane work fine too. i don't know what happen 😂
