### ISSUE TITLE
TestFlight not publishing to groups?

### ISSUE THREAD

**Issue by stefanhp** [fastlane/fastlane#9190]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,

Not sure this is a bug or a question, did not know where else to ask.

Before the big iTunesConnect refactoring setting distribute_external=true in testflight would publish the build to external testers (independently from groups). This stopped working for a while and was fixed.

The problem I have is that the command completes successfully:
```
    testflight(changelog: changelog,
               distribute_external: true,
               ipa: ipa)
```
but the build is not distributed to any Group. I tried adding 
```
PILOT_GROUPS=['Group 1','Group 2','Group 3']
```
to the environment file but it did not help.

I have to go manually in ITC to each group, add the build to that group and publish it.
I can't find anything in the docs or action descriptions on how to achieve that.

When I go to each group and add the new build, it has the proper changelog so something is happening.

Thanks for any help.

 
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.30.2"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/XXXX-redacted-XXX"


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Increment build number"
  desc "Takes the highest of local or TestFlight build number"
  lane :increment_build do
    local_build_number = get_build_number(xcodeproj:ENV["APP_PROJECT"]).to_i
    tf_build_number = latest_testflight_build_number
    if local_build_number > tf_build_number
      new_build_number = local_build_number + 1
    else
      new_build_number = tf_build_number + 1
    end
    increment_build_number(xcodeproj:ENV["APP_PROJECT"],
                           build_number: new_build_number)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    ipa = gym(project: ENV["APP_PROJECT"],
              scheme: ENV["APP_SCHEME"],
              clean: true,
              include_bitcode: true) # Build your app

   # Change log
   app_version = get_version_number(xcodeproj:ENV["APP_PROJECT"])
   build_number = get_build_number(xcodeproj:ENV["APP_PROJECT"])
   changelog = File.read("../ReleaseNotes/#{ENV["APP_SCHEME"]}/#{app_version}/en-US/#{build_number}.txt")

    # Upload to TestFlight
    testflight(changelog: changelog,
               distribute_external: true,
               ipa: ipa)

    # Upload symbols to Crashlytics
    #download_dsyms(build_number:build_number)  # Download dSYM files from iTC
    #upload_symbols_to_crashlytics(api_token: ENV["CRASHLYTICS_API_KEY"],
    #                              binary_path:"XXXX-redacted-XXX/Crashlytics-iOS/Fabric.framework/uploadDSYM")   # Upload them to Crashlytics
    #clean_build_artifacts           # Delete the local dSYM files

    slack(message: "Successfully published #{ENV["APP_SCHEME"]} build #{build_number} to TestFlight")

  end

  desc "Only get and upload dSYM files"
  lane :dsym do
    build_number = get_build_number(xcodeproj:ENV["APP_PROJECT"])

    # Upload symbols to Crashlytics
    download_dsyms(build_number:build_number)  # Download dSYM files from iTC
    upload_symbols_to_crashlytics(api_token: ENV["CRASHLYTICS_API_KEY"],
                                  binary_path:"XXXX-redacted-XXX/Crashlytics-iOS/Fabric.framework/uploadDSYM")   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files

    slack(message: "Successfully uploaded dSYM files for #{ENV["APP_SCHEME"]} build #{build_number} to Crashlytics")

  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    #gym(scheme: ENV['GYM_SCHEME']) # Build your app - more options available
    #deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV['APP_APP_ID'] # The bundle identifier of your app
apple_id "XXXX-redacted-XXX" # Your Apple email address

team_id "[[DEV_PORTAL_TEAM_ID]]"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.13.6       |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-05-16**
</details>

**Comment by mpirri** [comment]
@stefanhp Does your app have a default external group (usually called simply "External Testers")? If you don't specify a group (and that group exists), that's the group the app will be published for.

To publish to other groups, you can use `PILOT_GROUPS` as you specified, but try dropping the `[` and `]` around the environment variable value.  So:
`PILOT_GROUPS='Group 1','Group2','Group 3'`

You can also pass the groups into your call of `testflight` using the `groups:` argument and passing a ruby array.

Otherwise, what you are doing definitely looks like it should be okay. What does the output for the command indicate?

**Comment by stefanhp** [comment]
Hi,

I created new groups and removed the default 'External Testers' group.
I tried dropping the [] but it did not work better.
I'll try using the ```groups:``` argument next. I'll let you know how that goes.

Thanks for the answer!

Stefan

**Comment by westerlund** [comment]
@stefanhp I just successfully published to two groups using the `PILOT_GROUPS='Group 1','Group2','Group 3'` syntax. It might not help you, but at least it is working :)

**Comment by stefanhp** [comment]
It did work by importing the groups, without quotes, into a local array and then using ```groups:``` in the ```testflight``` command:
ENV file:
```PILOT_GROUPS=Group1,group 2, group 3```
(note the spaces, I have some group names that contain space and other special characters like () and &.

Fastfile:
```
    groups = ENV["PILOT_GROUPS"].split(",")
    testflight(changelog: changelog,
               distribute_external: true,
               ipa: ipa,
               groups: groups)
```

It seems that the single quotes were treated as part of the string and passed along to the API, and group1' did not exist.

Anyway, this is solved it for me. 
Thanks for the support and hopefully this might help somebody else.
