### ISSUE TITLE
Running multiple fastlane jobs at the same time

### ISSUE THREAD

**Issue by weihuali0509** [fastlane/fastlane#9191]
I am trying to run multiple fastlane jobs at the same time (in parallel). Do you think I will hit any problem? I have tried two fastlane jobs at the same time and it works. I just want to know if there is any problem if I scale the number up.

Thanks!

**Comment by hjanuschka** [comment]
hi @weihuali0509  🤚 

in general it should not be a problem for simple lanes, however specially when it comes to xcode/signing/building related stuff, you'll run into issues - and there is no official support for running multiple fastlane lanes in parallel.

e.g.: xcode, it is not built to  build 2 apps at the same time.

so i would not encourage you to run in parallel unless you are sure that your lane itself is capable of running in parallel.

**Comment by PetrosIchor** [comment]
From my experience hjanuschka is correct. While you can technically run in parallel​, you run the risk of unexpected conflicts using other resources.  I generally allow for no more than two fastlane executions on a build machine.  When I've pushed it to 3, there's been failures with other dependencies such as node, xcode, etc.

**Comment by weihuali0509** [comment]
@hjanuschka @PetrosIchor I am using the gym command (https://github.com/fastlane/fastlane/tree/master/gym) and it is working fine on 4 builds (4 different 
 folders) Simultaneously. Can you tell me a little bit more about the node, xcode dependencies? and which part of these dependencies would cause the build to fail? 

Here is my fastlane job - 
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: {appname}) # Build your app - more options available
    # pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
