### ISSUE TITLE
invalid swift support

### ISSUE THREAD

**Issue by xilankong** [fastlane/fastlane#9192]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

Once these issues have been corrected, you can then redeliver the corrected binary.
```

### Environment

fastfile
```
  lane :beta do
    #match
    increment_build_number
    gym(scheme: "demo",
        export_method:"ad-hoc",
        output_directory:"../ipa/ad-hoc")
    #pilot
  end
```
project:
```
my project : with out SwiftSupport floder
new empty swift project  : with out SwiftSupport floder
```
Xcode:
```
Version 8.3.2 
```

fastlane env
```
fastlane 2.30.2
```

**Comment by xilankong** [comment]
if,use empty project to just run "fastlane gym",it is contain the SwiftSupport folder

**Comment by PetrosIchor** [comment]
Please provide more information such as your fastlane env as suggested by the bot.  There isn't enough information here to help diagnose.

That said, if you Google that error, the top result on stackoverflow addresses that question: http://stackoverflow.com/a/34153571/7054813

**Comment by xilankong** [comment]
sorry for that,but  as  what i say .

when i build ipa with  ad-hoc（or development） profile，there is only Payload folder  inside the ipa 。

so i can  not  pilot  this  ipa for  testFlight。

if i build with app-store profile, there is SwiftSupport  folder inside the ipa 。

so， i want to know why like this。

**Comment by xilankong** [comment]
and  @PetrosIchor  i search this in google yet。 but ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES set to true, do not copy the libswiftAVFoundation.dylib to the target.  it is no help

**Comment by mgrebenets** [comment]
@xilankong 
Your question about `pilot` pretty much has an answer.

Ad-hoc and development types of distribution are not intended for TestFlight (iTunes Connect) uploads. That's why they have nothing but `Payload` folder. It's done intentionally by `xcodebuild`, it just strips out all the data which is not required for this type of distribution, such as SwiftSupport, bitcode and bitcode symbols and others.
