### ISSUE TITLE
code sign randomly failure

### ISSUE THREAD

**Issue by yang-guo-2016** [fastlane/fastlane#9193]
### Issue Description

> Using fastlane gym to export ipa, but sometimes got failure of code sign, its random error:

```
[11:49:48]: [35m[33m▸[0m [39;1mTouching[0m Sales.app.dSYM[0m 
[11:50:03]: [35m[33m▸[0m [39;1mArchive[0m Succeeded[0m 
[11:50:04]: [33mGenerated plist file with the following values:[0m 
[11:50:04]: ▸ [35m-----------------------------------------[0m 
[11:50:04]: ▸ [35m{[0m 
[11:50:04]: ▸ [35m "method": "ad-hoc"[0m 
[11:50:04]: ▸ [35m}[0m 
[11:50:04]: ▸ [35m-----------------------------------------[0m 
RVM detected, forcing to use system ruby 
[32mNow using system ruby.[0m 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/vl/3crtvrpd6gdbms8rzql5r_380000gp/T/gym_config20170517-1200-corh3z.plist -archivePath '/Users/flow/Library/Developer/Xcode/Archives/2017-05-17/Release-59127ab3fbd08646c74150a0-38 2017-05-17 11.37.33.xcarchive' -exportPath /var/folders/vl/3crtvrpd6gdbms8rzql5r_380000gp/T/gym_output20170517-1200-1bfvwg2 
2017-05-17 11:50:05.692 xcodebuild[4914:14652] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/vl/3crtvrpd6gdbms8rzql5r_380000gp/T/Sales_2017-05-17_11-50-05.690.xcdistributionlogs'. 
1.2.840.113635.100.1.61 
2017-05-17 11:50:23.847 xcodebuild[4914:14652] [MT] IDEDistribution: Step failed: : Error Domain=IDEFoundationErrorDomain Code=1 "Codesign failed" UserInfo={NSLocalizedDescription=Codesign failed} 
error: exportArchive: Codesign failed

Error Domain=IDEFoundationErrorDomain Code=1 "Codesign failed" UserInfo={NSLocalizedDescription=Codesign failed}
```

### Environment

fastlane 2.30.2
[13:14:02]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.3                                      |
| Ruby                        | 2.3.1                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.12.2                           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane          |
| Host                        | Mac OS X 10.12.3 (16D32)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode8.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
</details>

**Comment by PetrosIchor** [comment]
Without a verbose output and your Fastfile, this is hard to troubleshoot.  Please provide more information such as your Fastfile or command run, verbose output/build log, etc.

**Comment by yang-guo-2016** [comment]
@PetrosIchor I checked full log from fastlane, the first step to make archive is success, the detail of latest 100 lines log as below: (the log is using 'development' method, not the same as issue since I got the same issue no meeter export method)

```
Entitlements:

{
    "application-identifier" = "xxxxx";
    "aps-environment" = development;
    "com.apple.developer.team-identifier" = xxx;
    "get-task-allow" = 1;
}


    builtin-productPackagingUtility -entitlements -format xml -o /Users/flow/Library/Developer/Xcode/DerivedData/Yeyu-gvforhfejosiuzablqrnyjtroeju/Build/Intermediates/ArchiveIntermediates/Yeyu/IntermediateBuildFilesPath/Yeyu.build/Debug-iphoneos/Yeyu.build/Yeyu.app.xcent

CodeSign /Users/flow/Library/Developer/Xcode/DerivedData/Yeyu-gvforhfejosiuzablqrnyjtroeju/Build/Intermediates/ArchiveIntermediates/Yeyu/InstallationBuildProductsLocation/Applications/Yeyu.app
    cd /Users/flow/jobs/59231aad6c112a3e29bb0766/build/benqyang2006/yy-ios-test
    export CODESIGN_ALLOCATE=/Applications/Xcode8.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode8.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode8.app/Contents/Developer/usr/bin:/Users/flow/.nvm/versions/node/v7.6.0/bin:/Users/flow/.rvm/gems/ruby-2.3.1/bin:/Users/flow/.rvm/gems/ruby-2.3.1@global/bin:/Users/flow/.rvm/rubies/ruby-2.3.1/bin:/Users/flow/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: Ye Yu (xxx)"
Provisioning Profile: "yeyudev_hl"
                      (xxxxxxx)

    /usr/bin/codesign --force --sign 0ABDA86208D22FFA85AFA7142583353AEFCE1031 --entitlements /Users/flow/Library/Developer/Xcode/DerivedData/Yeyu-gvforhfejosiuzablqrnyjtroeju/Build/Intermediates/ArchiveIntermediates/Yeyu/IntermediateBuildFilesPath/Yeyu.build/Debug-iphoneos/Yeyu.build/Yeyu.app.xcent --timestamp=none /Users/flow/Library/Developer/Xcode/DerivedData/Yeyu-gvforhfejosiuzablqrnyjtroeju/Build/Intermediates/ArchiveIntermediates/Yeyu/InstallationBuildProductsLocation/Applications/Yeyu.app

Validate /Users/flow/Library/Developer/Xcode/DerivedData/Yeyu-gvforhfejosiuzablqrnyjtroeju/Build/Intermediates/ArchiveIntermediates/Yeyu/InstallationBuildProductsLocation/Applications/Yeyu.app
    cd /Users/flow/jobs/59231aad6c112a3e29bb0766/build/benqyang2006/yy-ios-test
    export PATH="/Applications/Xcode8.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode8.app/Contents/Developer/usr/bin:/Users/flow/.nvm/versions/node/v7.6.0/bin:/Users/flow/.rvm/gems/ruby-2.3.1/bin:/Users/flow/.rvm/gems/ruby-2.3.1@global/bin:/Users/flow/.rvm/rubies/ruby-2.3.1/bin:/Users/flow/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/flow/Library/Developer/Xcode/DerivedData/Yeyu-gvforhfejosiuzablqrnyjtroeju/Build/Intermediates/ArchiveIntermediates/Yeyu/InstallationBuildProductsLocation/Applications/Yeyu.app

** ARCHIVE SUCCEEDED **
```
I thought the first 'archive' step should export '.xcarchive' file in xcode 8xx not .app, maybe that is the cause for error I guess
