### ISSUE TITLE
Error packaging up the application

### ISSUE THREAD

**Issue by josercc** [fastlane/fastlane#9195]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.4                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.8.1                               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)                       |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 8.3.2                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#
# Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
#
lane :beta do |values|
  increment_build_number
  # set_info_plist_value(key:"CFBundleDisplayName", value:"GearBestDebug", path: "./GearBest/Info.plist")
  # # Fabric generated this lane for deployment to Crashlytics Beta
  # # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
  # gym(scheme: 'GearBest', export_method: 'ad-hoc', configuration: "Debug")
  #
  # emails = values[:test_email] ? values[:test_email] : ['josercc@163.com'] # You can list more emails here
  # groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
  #
  # crashlytics(api_token: '16039fa42746dbe86654562f69f030ccc0194d88',
  #          build_secret: '1ea94aa0d2497eb1a390da5062d7d5ad3ac20e4c57472c08e7c28c82013e8705',
  #                emails: emails,
  #                groups: groups,
  #                 notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
  #         notifications: true) # Should this distribution notify your testers via email?
end

#
# Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
#
lane :app_store do |values|
  increment_build_number
  # set_info_plist_value(key:"CFBundleDisplayName", value:"GearBestRelease", path: "Info.plist")
  build_number = get_build_number(xcodeproj: "GearBest.xcodeproj")
  version = get_version_number(xcodeproj: "GearBest.xcodeproj")
  output_directory = "/Applications/MAMP/htdocs/ipa/ipa/GearBest_" + version + "_" + build_number
  output_name = "GearBest.ipa"
  # Fabric generated this lane for deployment to Crashlytics Beta
  # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
  gym(scheme: 'GearBest', export_method: 'enterprise', configuration: "Release", output_directory:output_directory, output_name:output_name, clean:true)

  emails = values[:test_email] ? values[:test_email] : ['josercc@163.com'] # You can list more emails here
  groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

  crashlytics(api_token: '16039fa42746dbe86654562f69f030ccc0194d88',
           build_secret: '1ea94aa0d2497eb1a390da5062d7d5ad3ac20e4c57472c08e7c28c82013e8705',
                 emails: emails,
                 groups: groups,
                  notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
          notifications: true) # Should this distribution notify your testers via email?

  # )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.globalegrow.gearbest" # The bundle identifier of your app
apple_id "zhanghang@globalegrow.com" # Your Apple email address

team_id "9RWES6K38C" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.30.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.2        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-17**
</details>

➜  GearBest fastlane app_store
[18:09:36]: Driving the lane 'app_store' 🚀
[18:09:36]: ------------------------------------
[18:09:36]: --- Step: increment_build_number ---
[18:09:36]: ------------------------------------
[18:09:36]: $ cd /Users/zhangxing/Downloads/TestGearBest/GearBest && agvtool next-version -all && cd -
[18:09:37]: ▸ Setting version of project GearBest to:
[18:09:37]: ▸ 22.
[18:09:37]: ▸ Also setting CFBundleVersion key (assuming it exists)
[18:09:37]: ▸ Updating CFBundleVersion in Info.plist(s)...
[18:09:37]: ▸ Updated CFBundleVersion in "GearBest.xcodeproj/../GearBest/Info.plist" to 22
[18:09:37]: ▸ /Users/zhangxing/Downloads/TestGearBest/GearBest
[18:09:38]: ------------------------------
[18:09:38]: --- Step: get_build_number ---
[18:09:38]: ------------------------------
[18:09:38]: $ cd /Users/zhangxing/Downloads/TestGearBest/GearBest && agvtool what-version -terse
[18:09:39]: ▸ 22
[18:09:39]: --------------------------------
[18:09:39]: --- Step: get_version_number ---
[18:09:39]: --------------------------------
[18:09:39]: $ cd /Users/zhangxing/Downloads/TestGearBest/GearBest && agvtool what-marketing-version -terse
[18:09:40]: ▸ "GearBest.xcodeproj/../GearBest/Info.plist"=1.0
[18:09:40]: -----------------
[18:09:40]: --- Step: gym ---
[18:09:40]: -----------------
[18:09:41]: $ xcodebuild -list -workspace ./GearBest.xcworkspace -configuration Release
[18:09:41]: $ xcodebuild -showBuildSettings -workspace ./GearBest.xcworkspace -scheme GearBest -configuration Release

+----------------------+--------------------------------------+
|                   Summary for gym 2.30.2                    |
+----------------------+--------------------------------------+
| scheme               | GearBest                             |
| export_method        | enterprise                           |
| configuration        | Release                              |
| output_directory     | /Applications/MAMP/htdocs/ipa/ipa/G  |
|                      | earBest_1.0_22                       |
| output_name          | GearBest                             |
| clean                | true                                 |
| workspace            | ./GearBest.xcworkspace               |
| destination          | generic/platform=iOS                 |
| build_path           | /Users/zhangxing/Library/Developer/  |
|                      | Xcode/Archives/2017-05-17            |
| silent               | false                                |
| skip_package_ipa     | false                                |
| use_legacy_build_api | false                                |
| buildlog_path        | ~/Library/Logs/gym                   |
| xcode_path           | /Applications/Xcode.app              |
+----------------------+--------------------------------------+

[18:09:42]: $ set -o pipefail && xcodebuild -workspace ./GearBest.xcworkspace -scheme GearBest -configuration Release -destination 'generic/platform=iOS' -archivePath /Users/zhangxing/Library/Developer/Xcode/Archives/2017-05-17/GearBest\ 2017-05-17\ 18.09.42.xcarchive clean archive | tee /Users/zhangxing/Library/Logs/gym/GearBest-GearBest.log | xcpretty
[18:09:43]: ▸ Cleaning GearBest/GearBest [Release]
[18:09:43]: ▸ Check Dependencies
[18:09:43]: ▸ Clean Succeeded
[18:09:44]: ▸ Building GearBest/GearBest [Release]
[18:09:44]: ▸ Check Dependencies
[18:09:44]: ▸ Compiling AppDelegate.m
[18:09:44]: ▸ Compiling ViewController.m
[18:09:44]: ▸ Compiling main.m
[18:09:44]: ▸ Compiling ViewController.m
[18:09:44]: ▸ Compiling AppDelegate.m
[18:09:44]: ▸ Compiling main.m
[18:09:44]: ▸ Linking GearBest
[18:09:45]: ▸ Linking GearBest
[18:09:45]: ▸ Compiling LaunchScreen.storyboard
[18:09:47]: ▸ Compiling Main.storyboard
[18:09:47]: ▸ Processing Info.plist
[18:09:47]: ▸ Generating 'GearBest.app.dSYM'
[18:09:47]: ▸ Running script 'Run Script'
[18:09:48]: ▸ Touching GearBest.app
[18:09:48]: ▸ Signing /Users/zhangxing/Library/Developer/Xcode/DerivedData/GearBest-axadfjlqvlgqqfhfrwqdgluljtrk/Build/Intermediates/ArchiveIntermediates/GearBest/InstallationBuildProductsLocation/Applications/GearBest.app
[18:09:48]: ▸ Touching GearBest.app.dSYM
[18:09:48]: ▸ Archive Succeeded
[18:09:48]: Generated plist file with the following values:
[18:09:48]: ▸ -----------------------------------------
[18:09:48]: ▸ {
[18:09:48]: ▸   "method": "enterprise"
[18:09:48]: ▸ }
[18:09:48]: ▸ -----------------------------------------
[18:09:48]: $ /usr/bin/xcrun /usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.30.2/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/9f/t3438dfj1pz71j23sxt94z9w0000gn/T/gym_config20170517-24743-1rhbehl.plist' -archivePath /Users/zhangxing/Library/Developer/Xcode/Archives/2017-05-17/GearBest\ 2017-05-17\ 18.09.42.xcarchive -exportPath '/var/folders/9f/t3438dfj1pz71j23sxt94z9w0000gn/T/gym_output20170517-24743-1cen8p9' 
env: bash: No such file or directory
/usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.30.2/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 25: which: command not found
/usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.30.2/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 38: which: command not found
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/9f/t3438dfj1pz71j23sxt94z9w0000gn/T/gym_config20170517-24743-1rhbehl.plist -archivePath '/Users/zhangxing/Library/Developer/Xcode/Archives/2017-05-17/GearBest 2017-05-17 18.09.42.xcarchive' -exportPath /var/folders/9f/t3438dfj1pz71j23sxt94z9w0000gn/T/gym_output20170517-24743-1cen8p9
/usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.30.2/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61: xcodebuild: command not found
+ shell_session_update
/usr/local/lib/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.30.2/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 62: shell_session_update: command not found
[18:09:49]: Exit status: 127
[18:09:49]: 📋  For a more detailed error log, check the full log at:
[18:09:49]: 📋  /Users/zhangxing/Library/Logs/gym/GearBest-GearBest.log
+----------------+-----------+
|        Lane Context        |
+----------------+-----------+
| PLATFORM_NAME  |           |
| LANE_NAME      | app_store |
| BUILD_NUMBER   | 22        |
| VERSION_NUMBER | 1.0       |
+----------------+-----------+
[18:09:49]: Error packaging up the application

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | increment_build_numbe  | 2           |
|      | r                      |             |
| 2    | get_build_number       | 1           |
| 3    | get_version_number     | 1           |
| 💥   | gym                    | 8           |
+------+------------------------+-------------+

[18:09:49]: fastlane finished with errors

[!] Error packaging up the application

**Comment by PetrosIchor** [comment]
The error states what failed.   Bash and which were not found.  Those are not apart of fastlane but your shell.   Make sure you have you path setup correctly.  Check that `/usr/bin:/usr/sbin:/bin:/sbin` are in your path, if not add them.

**Comment by josercc** [comment]
@PetrosIchor 
➜  GearBest echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Users/zhangxing/.rvm/bin

system using zsh

**Comment by mgrebenets** [comment]
@josercc 

It seems like all errors are coming from `xcbuild-safe.sh` helper script.
And for some reason id doesn't play nice with your `zsh` or maybe even Ruby setup.

I am using `zsh` too and didn't fame similar problem.
But one thing I noticed in my setup different to yours is `PATH`:

```
/Users/grebenma/.rvm/gems/ruby-2.2.2/bin:/Users/grebenma/.rvm/gems/ruby-2.2.2@global/bin:/Users/grebenma/.rvm/rubies/ruby-2.2.2/bin:/Users/grebenma/.rvm/bin:/usr/local/llvm-checker:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```

As you can see all RVM paths come before system paths in my setup.
As far as I remember, RVM really wants to have its paths to be before anything else: https://stackoverflow.com/questions/18276701/getting-warning-path-is-not-properly-set-up-when-doing-rvm-use-2-0-0-defaul

Maybe that's the reason for your errors?
