### ISSUE TITLE
in initialize: execution expired (Faraday::ConnectionFailed)

### ISSUE THREAD

**Issue by huang-kun** [fastlane/fastlane#9197]
I run my latest fastlane and get failed. No error happened for built-in action like gym, but when I run any custom lane in Fastfile, I got this output:

```
[20:52:44]: -------------------------------------------------
[20:52:44]: --- Step: Verifying required fastlane version ---
[20:52:44]: -------------------------------------------------
[20:52:44]: Your fastlane version 2.30.2 matches the minimum requirement of 2.28.7  ✅
[20:52:44]: ------------------------------
[20:52:44]: --- Step: default_platform ---
[20:52:44]: ------------------------------
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:904:in `initialize': execution expired (Faraday::ConnectionFailed)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:904:in `open'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:904:in `block in connect'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:902:in `connect'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:876:in `start'
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/adapter/net_http.rb:33:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/request/url_encoded.rb:15:in `call'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/connection.rb:386:in `run_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/faraday-0.12.1/lib/faraday/connection.rb:186:in `post'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/fastlane_core/lib/fastlane_core/crash_reporter/crash_reporter.rb:77:in `send_report'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/fastlane_core/lib/fastlane_core/crash_reporter/crash_reporter.rb:29:in `report_crash'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:80:in `rescue in run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:106:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.30.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
```

I installed ruby by homebrew in `/usr/local/bin/` and version information is `ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]` and fastlane is installed from gem and version is `2.30.2`

Any help?

**Comment by huang-kun** [comment]
Here is the result of `fastlane env`

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.28.7"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    puts "before lane"    
  end
  
  desc "demo"
  lane :demo do
    puts "hello world"
  end

  desc "Creating a code signing certificate and provisioning profile"
  lane :signing do
    cert
    sigh(force: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "TaoYanZuoYe") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Take screenshots"
  lane :screenshot do
    snapshot
  end

  desc "Create IPA"
  lane :build do 
    increment_build_number
    gym
  end

  desc "Upload to iTunes Connect"
  lane :upload do
    deliver
  end

  desc "Create app icon"
  lane :genicon do
    appicon(
      appicon_image_file: './fastlane/metadata/AppIcon.png',
      appicon_devices: [:iphone, :ipad],
      appicon_path: 'TaoYanZuoYe/Assets.xcassets'
    )
  end

  desc "lane test"
  lane :demo do
    puts "hello world"
  end

  desc "生成 Framework ，并引用对应的 Framework"
  lane :pod_generate_frameworks do |options|
    ENV['PODFILE_TYPE'] = 'generate_frameworks'
    ENV["BUILD_PODS"] = options[:build]
    ENV["FRAMEWORK_PODS"] = ''
    cocoapods(use_bundle_exec: false)
    ENV['PODFILE_TYPE'] = ''
    ENV["BUILD_PODS"] = ''
    ENV["FRAMEWORK_PODS"] = options[:build]
    if !(ENV["FRAMEWORK_PODS"] && ENV["FRAMEWORK_PODS"].length > 0) # 如果 build 为空，说明是 build all ，设置成 development
      ENV['PODFILE_TYPE'] = 'development'
    end
    cocoapods(use_bundle_exec: false)
  end

  desc "直接引用 Framework"
  lane :pod_frameworks do |options|
    ENV['PODFILE_TYPE'] = ''
    ENV["FRAMEWORK_PODS"] = options[:frameworks]
    if !(options[:frameworks] && options[:frameworks] != 'all')
      ENV['PODFILE_TYPE'] = 'development'
    end
    cocoapods(use_bundle_exec: false)
  end

  desc "全部使用源码"
  lane :pod_source do |options|
    ENV['PODFILE_TYPE'] = ''
    ENV["FRAMEWORK_PODS"] = ''
    cocoapods(use_bundle_exec: false)
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    puts "lane success!"
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.lejent.TaoYanZuoYe" # The bundle identifier of your app
apple_id "app_developer@lejent.com" # Your Apple email address

team_id "CD76TM5QAC" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.30.2  | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.6.0   | ✅ Up-To-Date  |
| fastlane-plugin-pgyer   | 0.2.1   | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| fastlane-plugin-appicon   | 0.6.0        |
| fastlane-plugin-pgyer     | 0.2.1        |
</details>


*generated on:* **2017-05-18**
</details>

**Comment by gaoneng1989** [comment]
I have the same issue and here is my env

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.6.4                           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.19.3"

default_platform :ios

platform :ios do

  lane :beta do
    increment_build_number(
      xcodeproj: "./ios/jimi.xcodeproj",
      build_number: latest_testflight_build_number(version: get_version_number(xcodeproj: "./ios/jimi.xcodeproj")) + 1
    )
    gym(
      workspace: "./ios/jimi.xcworkspace",
      scheme: "jimi"
    )
    testflight(skip_submission: true, app_identifier: "com.zaodao.jimi", ipa: "jimi.ipa")
    send_to_dingtalk(:text => "请前往testflight下载",:title => "iOS测试版本已更新",:url => "https://itunesconnect.apple.com")
  end

  lane :release do
    increment_build_number(
      xcodeproj: "./ios/jimi.xcodeproj",
      build_number: latest_testflight_build_number(version: get_version_number(xcodeproj: "./ios/jimi.xcodeproj")) + 1
    )
    gym(
      scheme: "jimi",
      project: "./ios/jimi.xcodeproj"
    )
    testflight(skip_submission: true, app_identifier: "com.zaodao.jimi", ipa: "jimi_release.ipa")
    send_to_dingtalk(:text => "请前往testflight下载，如果不需更新到正式版请勿下载",:title => "iOS正式版本已更新",:url => "https://itunesconnect.apple.com")
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.zaodao.jimi" # The bundle identifier of your app
apple_id "zd@zd0806.com" # Your Apple email address

team_id "84EMB66X65" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.32.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| openssl                   | 2.0.2        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| netrc                     | 0.11.0       |
| rest-client               | 1.8.0        |
| aliyun-sdk                | 0.5.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.7.2        |
| mime-types                | 2.99.3       |
</details>


*generated on:* **2017-05-22**
</details>

**Comment by gaoneng1989** [comment]
@huang-kun do you have any solution to this?

**Comment by huang-kun** [comment]
@gaoneng1989 not yet. Even with the latest version!

**Comment by KrauseFx** [comment]
Could you update to the most recent release and try again? 👍

**Comment by AmatsuZero** [comment]
Same issue, waiting for solution...

Here is my env:
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.1.0        |
| addressable               | 2.4.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types                | 2.99.2       |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.4        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2017-05-24**
</details>

**Comment by KrauseFx** [comment]
Hey everyone, thanks for reporting this. Are you based in China? On the first look it seems like you can't reach the crash reporting server, which is hosted by Google, and parts of Google are blocked in China. We'll work on a fix to not crash like this.

In the mean-time, could you connect to a VPN outside of China and see if that fixes the issue for you? Thanks

**Comment by AmatsuZero** [comment]
We did try some actions like cert under VPN environment, but it didn't anyway...

**Comment by TuDoudong** [comment]
Same issue, waiting for solution too ...

Here is my env:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.4                                      |
| Ruby                        | 2.4.1                                        |
| Bundler?                    | false                                        |
| Git                         | git version 2.9.3 (Apple Git-75)             |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane          |
| Host                        | Mac OS X 10.12.4 (16E195)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode8.app/Contents/Developer/ |
| Xcode Version               | 8.1                                          |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_CN.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.33.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end



  lane :tofirdebug do
    gym(scheme:"EloancnBorrower",
      workspace:"EloancnBorrower.xcworkspace",
      export_method:'ad-hoc',
      clean:true,
      configuration:"Debug",
      output_name:"EloancnBorrowerDebug.ipa",
      output_directory:'/Users/donghuixiang/Desktop/eloanBorrowIpa')
    fir publish "/Users/donghuixiang/Desktop/eloanBorrowIpa/EloancnBorrowerDebug.ipa" -T fir_token -c "测试环境"
  end
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "EloancnBorrower") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "EloancnBorrower") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.eloancn.EloancnBorrower" # The bundle identifier of your app
apple_id "admin@qiye.eloancn.com" # Your Apple email address

team_id "685MD7243L" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.0       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.3        |
</details>


*generated on:* **2017-05-24**
</details>

**Comment by KrauseFx** [comment]
Thanks @ohayon, this will be fixed in the next release 👍
