### ISSUE TITLE
Ran into error while trying to connect to iTunes Connect / Dev Portal

### ISSUE THREAD

**Issue by Bae-Ki-Cheol** [fastlane/fastlane#9203]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I used ```fastlane init```, error occurring 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[13:10:43]: Ran into error while trying to connect to iTunes Connect / Dev Portal: undefined method `interactive?' for FastlaneCore::Helper:Module
[13:10:43]: Falling back to manual onboarding
[13:10:43]: undefined method `interactive?' for FastlaneCore::Helper:Module
[13:10:43]: An error occurred during the setup process. Falling back to manual setup!

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.7.4 (Apple Git-66)                               |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode7.3.1.app/Contents/Developer/               |
| Xcode Version               | 7.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | ko_KR.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.31.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-18**
</details>

**Comment by jjochen** [comment]
I get the same error when running `fastlane sigh`
```
/Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/spaceship/lib/spaceship/portal/ui/select_team.rb:43:in `interactive?': [!] undefined method `interactive?' for FastlaneCore::Helper:Module (NoMethodError)
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/spaceship/lib/spaceship/portal/ui/select_team.rb:81:in `select_team'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/spaceship/lib/spaceship/portal/portal_client.rb:55:in `select_team'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/spaceship/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/spaceship/lib/spaceship/portal/spaceship.rb:86:in `select_team'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/sigh/lib/sigh/runner.rb:16:in `run'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/sigh/lib/sigh/manager.rb:7:in `start'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/sigh/lib/sigh/commands_generator.rb:55:in `block (2 levels) in run'
	from /Users/jochen/.gem/ruby/2.4.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/jochen/.gem/ruby/2.4.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/jochen/.gem/ruby/2.4.1/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/jochen/.gem/ruby/2.4.1/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/sigh/lib/sigh/commands_generator.rb:123:in `run'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/jochen/.gem/ruby/2.4.1/gems/fastlane-2.31.0/bin/fastlane:20:in `<top (required)>'
	from /Users/jochen/.gem/ruby/2.4.1/bin/fastlane:22:in `load'
	from /Users/jochen/.gem/ruby/2.4.1/bin/fastlane:22:in `<main>'
```

**Comment by jjochen** [comment]
defining `team_id` in the `sigh` call solved my issue.

**Comment by Bae-Ki-Cheol** [comment]
My account is individual account 
How to success 'fastlane init'?

**Comment by wbroek** [comment]
Same with using `fastlane pem`

```
/Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/spaceship/lib/spaceship/portal/ui/select_team.rb:43:in `interactive?': [!] undefined method `interactive?' for FastlaneCore::Helper:Module (NoMethodError)
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/spaceship/lib/spaceship/portal/ui/select_team.rb:81:in `select_team'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/spaceship/lib/spaceship/portal/portal_client.rb:55:in `select_team'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/pem/lib/pem/manager.rb:36:in `login'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/pem/lib/pem/manager.rb:10:in `start'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/pem/lib/pem/commands_generator.rb:33:in `block (2 levels) in run'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/pem/lib/pem/commands_generator.rb:39:in `run'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/pem/lib/pem/commands_generator.rb:11:in `start'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/wouter/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.32.0/bin/fastlane:20:in `<top (required)>'
	from /Users/wouter/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/wouter/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

**Comment by Bae-Ki-Cheol** [comment]
My personal account to be included company account.
so I leave company account.
I solved my issue.

**Comment by wbroek** [comment]
If I use the `--team_id` with the right team id it works, so the team chooser does not work atm
