### ISSUE TITLE
Gym failed with Exit status: 65 (ld: file not found)

### ISSUE THREAD

**Issue by lsps9150414** [fastlane/fastlane#9204]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
**I have two lans setup:**
- `beta` lane, correspond to my `staging` build
- `release` lane, correspond to my `release` build

**Background:**
- I can successfully build both scheme with Xcode.
- I did successfully use the exact same setup to deploy to Testflight and App store once. After Xcode get's updated my `staging` scheme somehow disappeared so I recreated it.

**My Fastfile:**
##### beta
```
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "boca-staging") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
```
##### release
```
  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    # snapshot
    gym(scheme: "boca") # Build your app - more options available
    deliver(force: true)
    # frameit
  end
```

##### Complete output when running fastlane, including the stack trace and command used
- command:
Both `fastlane beta` and `fastlane release` failed with same error.
Which I don't understand why the `release` lane is also complaining beta file not found?
```
ld: file not found: /Users/philipchen/Library/Developer/Xcode/DerivedData/boca-exesrtzzlfnxizehfvsaykabakln/Build/Intermediates/ArchiveIntermediates/boca/BuildProductsPath/Release-iphoneos/GuruWounds (Beta).app/GuruWounds (Beta)
``` 

- output:

For the `--capture-output` result:
https://gist.github.com/lsps9150414/9e9c50ec8095200e848d38ef6418c5cd

```
Compiling LaunchScreen.xib
▸ Processing Info.plist
▸ Generating 'GuruWounds.app.dSYM'
▸ Running script 'Bundle React Native code and images'
▸ Touching GuruWounds.app
▸ Signing /Users/philipchen/Library/Developer/Xcode/DerivedData/boca-exesrtzzlfnxizehfvsaykabakln/Build/Intermediates/ArchiveIntermediates/boca-staging/InstallationBuildProductsLocation/Applications/GuruWounds.app
▸ Touching GuruWounds.app.dSYM
▸ Building boca/bocaTests [Release]
▸ Check Dependencies
▸ Processing Info.plist
▸ Compiling bocaTests.m
▸ Compiling bocaTests.m
▸ Linking bocaTests

❌  ld: file not found: /Users/philipchen/Library/Developer/Xcode/DerivedData/boca-exesrtzzlfnxizehfvsaykabakln/Build/Intermediates/ArchiveIntermediates/boca-staging/BuildProductsPath/Release-iphoneos/GuruWounds (Beta).app/GuruWounds (Beta)



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


▸ Linking bocaTests

❌  ld: file not found: /Users/philipchen/Library/Developer/Xcode/DerivedData/boca-exesrtzzlfnxizehfvsaykabakln/Build/Intermediates/ArchiveIntermediates/boca-staging/BuildProductsPath/Release-iphoneos/GuruWounds (Beta).app/GuruWounds (Beta)



❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)


** ARCHIVE FAILED **


The following build commands failed:
Ld /Users/philipchen/Library/Developer/Xcode/DerivedData/boca-exesrtzzlfnxizehfvsaykabakln/Build/Intermediates/ArchiveIntermediates/boca-staging/IntermediateBuildFilesPath/boca.build/Release-iphoneos/bocaTests.build/Objects-normal/armv7/bocaTests normal armv7
Ld /Users/philipchen/Library/Developer/Xcode/DerivedData/boca-exesrtzzlfnxizehfvsaykabakln/Build/Intermediates/ArchiveIntermediates/boca-staging/IntermediateBuildFilesPath/boca.build/Release-iphoneos/bocaTests.build/Objects-normal/arm64/bocaTests normal arm64
(2 failures)
[12:55:55]: Exit status: 65
[12:55:55]: 📋  For a more detailed error log, check the full log at:
[12:55:55]: 📋  /Users/philipchen/Library/Logs/gym/GuruWounds-boca-staging.log

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.31.0                  |
| sdk         | iPhoneOS10.3.sdk        |
+-------------+-------------------------+

+-------------------+-----------+
|         Lane Context          |
+-------------------+-----------+
| DEFAULT_PLATFORM  | ios       |
| PLATFORM_NAME     | ios       |
| LANE_NAME         | ios beta  |
| SIGH_PROFILE_TYPE | app-store |
+-------------------+-----------+
[12:55:55]: Error building the application - see the log above

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 9           |
| 💥   | gym                                 | 177         |
+------+-------------------------------------+-------------+

[12:55:55]: fastlane finished with errors

[!] Error building the application - see the log above
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.1/bin/fastlane       |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | zh_TW.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.27.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "boca-staging") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    # snapshot
    gym(scheme: "boca") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.boca.GuruWounds" # The bundle identifier of your app
apple_id "iosdev1@nonstopdatasolution.com" # Your Apple email address

team_id "RLW2ALX38C" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.31.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.0.1     |
| unf_ext                   | 0.0.7.3      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-05-18**
</details>

**Comment by PetrosIchor** [comment]
Try deleting your derived data and rebuilding.   I've run into similar issues and it was due to polluted derdata

**Comment by joshdholtz** [comment]
@lsps9150414 Hey 👋  It seems like this issue _may_ be related to your scheme including tests in a production release? 

```sh
▸ Processing Info.plist
▸ Generating 'GuruWounds.app.dSYM'
▸ Running script 'Bundle React Native code and images'
▸ Touching GuruWounds.app
▸ Signing /Users/philipchen/Library/Developer/Xcode/DerivedData/boca-exesrtzzlfnxizehfvsaykabakln/Build/Intermediates/ArchiveIntermediates/boca-staging/InstallationBuildProductsLocation/Applications/GuruWounds.app
▸ Touching GuruWounds.app.dSYM
▸ Building boca/bocaTests [Release]
▸ Check Dependencie
▸ Compiling bocaTests.m
▸ Linking bocaTests
❌  ld: file not found
```

It appears your app is being built and signed correctly but your scheme might still be telling gym to build and link the tests - `Compiling bocaTests.m` and `Linking bocaTests`   - (which are failing when doing a release build). Its hard to know _exactly_ without having the fully project but I would start taking a look there 👀

**Comment by lsps9150414** [comment]
@PetrosIchor Thanks for the advice. What exactly are the derived data you mentioned and where are they located?

@joshdholtz I came from react-native and I have limited experience with native app development. I temporary solved the problem by setting the `host application` of my test target to `none` in Xcode. However I don't know if this is the proper way to fix it.

**Comment by joshdholtz** [comment]
@lsps9150414 Derived data- http://stackoverflow.com/questions/38016143/how-to-delete-derived-data-in-xcode-8

And one thing to make sure of is your that only your main target is included in the "Archive" column of your scheme like the below picture...
![screen shot 2017-05-22 at 6 34 26 am](https://cloud.githubusercontent.com/assets/401294/26306401/de691b26-3eb8-11e7-922d-dde399d5325f.png)

**Comment by lsps9150414** [comment]
@joshdholtz Thank you! This solved my problem.
