### ISSUE TITLE
increment_build_number is not working properly. 

### ISSUE THREAD

**Issue by reshadf** [fastlane/fastlane#9205]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi, When I use increment_build_number its not working properly after an update earlier this week from fastlane. The current build nr is 31 and it should increment that but everytime it runs it gets 30 as the current build nr. I noticed that using 

'agvtool what-version' 

I get 30 as output whereas I use 

'cd /Users/username/xcode/projectname/builds/6956a60a/0/***-mobile/ios && agvtool what-version -terse'

it outputs 31.. 

Also using get_build_number always returns 30. so increment_build_number always sets 31. So I think get_build_number is what causing it? 

update: I see now that the functions use the version inside builds/ to increment and current build numbers.. its not targeting my project itself anymore.. 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | nl_NL.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Appfile`</summary>

```ruby
#app_identifier "nl.ProActive.Factuurverwerking.Beta" # The bundle identifier of your app
app_identifier ENV["APP_IDENTIFIER"]
apple_id "***@gmail.com" # Your Apple email address

team_id "***" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.30.2  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.7        |
| terminal-notifier         | 1.7.2        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-05-18**
</details>

**Comment by joshdholtz** [comment]
@reshadf Both `get_build_number` and `increment_build_number` worked for me. To test this I created a new Xcode project and followed the following guide (https://developer.apple.com/library/content/qa/qa1827/_index.html) with the following `Fastfile`...

```rb
lane :test do
	get_build_number
	increment_build_number
end
```

It seems like it is most likely a project configuration issue. Is your `CURRENT_PROJECT_VERSION` in your build settings out of sync or not set properly? `get_build_number` takes the value from `CURRENT_PROJECT_VERSION` in the build settings. `VERSIONING_SYSTEM` also needs to be set to `Apple Generic`. If you could make sure your build settings are correct based upon this guide that would be great 👌 

![screen shot 2017-05-19 at 1 04 40 pm](https://cloud.githubusercontent.com/assets/401294/26260694/c1d7b728-3c93-11e7-92cf-be0affa5cbb7.png)

If it is still not working, I would suggest create a new blank Xcode project and verifying it works in there 💪  I am going to close this for now since it does not appear to be a fastlane issue but if you attempt both of the following and don't success, please mention me and we can reopen and look into 👀
