### ISSUE TITLE
[produce] Invalid 2 step response 

### ISSUE THREAD

**Issue by tcurdt** [fastlane/fastlane#9206]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to setup a new app and it's failing as described below.

##### Complete output when running fastlane, including the stack trace and command used
```
bundle exec fastlane produce \
    --username "****@****" \
    --app_identifier "*********" \
    --app_name "*****" \
    --app_version "1.0" \
    --sku "*******.v1" \
    --language "Dutch" \
    --company_name "*****" \
    --team_name "*****" \


+----------------+---------------------------+
|         Summary for produce 2.31.0         |
+----------------+---------------------------+
| username       | ******                    |
| app_identifier | ****                      |
| app_name       | ***                       |
| app_version    | 1.0                       |
| sku            | ****.v1                   |
| language       | Dutch                     |
| company_name   | ****                      |
| team_name      | ****                      |
| platform       | ios                       |
| skip_itc       | false                     |
| skip_devcenter | false                     |
+----------------+---------------------------+


Looking for related GitHub issues on fastlane/fastlane...

bundler: failed to load command: fastlane (/Users/tcurdt/.gem/ruby/2.3.1/bin/fastlane)
RuntimeError: [!] Invalid 2 step response {"trustedPhoneNumbers"=>[{"id"=>2, "countryDialCode"=>"49", "countryCode"=>"DE", "createDate"=>"02/15/2017 12:53:11 PM", "updateDate"=>"02/15/2017 12:53:31 PM", "pushMode"=>"sms", "number"=>"********59", "pending"=>false, "lastTwoDigits"=>"59", "rawNumber"=>"********59", "numberWithDialCode"=>"+49 ••••••••59", "verifiedDate"=>"02/15/2017 12:53:31 PM", "verified"=>true, "obfuscatedNumber"=>"••••••••59"}, {"id"=>1, "countryDialCode"=>"49", "countryCode"=>"DE", "createDate"=>"02/15/2017 12:17:49 PM", "updateDate"=>"02/15/2017 12:50:56 PM", "pushMode"=>"voice", "number"=>"********98", "pending"=>false, "lastTwoDigits"=>"98", "rawNumber"=>"********98", "numberWithDialCode"=>"+49 ••••••••98", "verifiedDate"=>"02/15/2017 12:50:56 PM", "verified"=>true, "obfuscatedNumber"=>"••••••••98"}], "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false}, "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=***@*****&autoSubmitAccount=true&appId=142", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=***@*****&autoSubmitAccount=true&appId=142", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=***@*****&autoSubmitAccount=true&appId=142", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/repair?#!repair", "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "trustedPhoneNumber"=>{"id"=>2, "countryDialCode"=>"49", "countryCode"=>"DE", "createDate"=>"02/15/2017 12:53:11 PM", "updateDate"=>"02/15/2017 12:53:31 PM", "pushMode"=>"sms", "number"=>"********59", "pending"=>false, "lastTwoDigits"=>"59", "rawNumber"=>"********59", "numberWithDialCode"=>"+49 ••••••••59", "verifiedDate"=>"02/15/2017 12:53:31 PM", "verified"=>true, "obfuscatedNumber"=>"••••••••59"}, "hsa2Account"=>true, "managedAccount"=>false, "supportsRecovery"=>true}
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/two_step_client.rb:41:in `handle_two_step'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/client.rb:317:in `send_shared_login_request'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/client.rb:431:in `do_login'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/client.rb:246:in `login'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/client.rb:93:in `login'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/portal/spaceship.rb:22:in `login'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/spaceship-1.0.0/lib/spaceship/portal/spaceship.rb:77:in `login'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/produce/lib/produce/developer_center.rb:87:in `login'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/produce/lib/produce/developer_center.rb:6:in `run'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/produce/lib/produce/manager.rb:7:in `start_producing'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/produce/lib/produce/commands_generator.rb:34:in `block (2 levels) in run'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/produce/lib/produce/commands_generator.rb:140:in `run'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/produce/lib/produce/commands_generator.rb:11:in `start'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  /Users/tcurdt/.gem/ruby/2.3.1/gems/fastlane-2.31.0/bin/fastlane:20:in `<top (required)>'
  /Users/tcurdt/.gem/ruby/2.3.1/bin/fastlane:22:in `load'
  /Users/tcurdt/.gem/ruby/2.3.1/bin/fastlane:22:in `<top (required)>'
```
### Environment
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.12.2                          |
| Installation Source         | ~/.gem/ruby/2.3.1/bin/fastlane              |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rubies/ruby-2.3.1/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2h  3 May 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US       | 🚫 |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.31.0  | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.13.1       |
| io-console                | 0.4.5        |
| rake                      | 10.4.2       |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| aws-sigv4                 | 1.0.0        |
| jmespath                  | 1.3.1        |
| aws-sdk-core              | 2.8.5        |
| aws-sdk-resources         | 2.8.5        |
| aws-sdk                   | 2.8.5        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.55.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| credentials_manager       | 1.0.0        |
| houston                   | 2.2.4        |
| xcode-install             | 2.1.1        |
</details>

*generated on:* **2017-05-18**
</details>

**Comment by tcurdt** [comment]
changing the code to this gets me further
```
      elsif r.body.kind_of?(Hash) && r.body["trustedPhoneNumbers"].kind_of?(Array)
        handle_two_factor(r)
      else
        raise "Invalid 2 step response #{r.body}"
      end
    end

    def handle_two_factor(response)
      two_factor_url = "https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification"
      puts "Two Factor Authentication for account '#{self.user}' is enabled"
      puts "If you're running this in a non-interactive session (e.g. server or CI)"
      puts "check out #{two_factor_url}"

      security_code = response.body["securityCode"]
```

but then

```
Two Factor Authentication for account '***@***' is enabled
If you're running this in a non-interactive session (e.g. server or CI)
check out https://github.com/fastlane/fastlane/tree/master/spaceship#2-step-verification
Please enter the 6 digit code: ******
Requesting session...
[17:00:09]: Creating new app '****' on the Apple Dev Center

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (foo/Vendor/bundle/ruby/2.3.0/bin/fastlane)
ArgumentError: [!] unknown keyword: enabled_features
  foo/Vendor/bundle/ruby/2.3.0/gems/spaceship-1.0.0/lib/spaceship/portal/app.rb:90:in `create!'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/produce/lib/produce/developer_center.rb:20:in `create_new_app'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/produce/lib/produce/developer_center.rb:7:in `run'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/produce/lib/produce/manager.rb:7:in `start_producing'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/produce/lib/produce/commands_generator.rb:34:in `block (2 levels) in run'
  foo/Vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
  foo/Vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
  foo/Vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
  foo/Vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/produce/lib/produce/commands_generator.rb:140:in `run'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/produce/lib/produce/commands_generator.rb:11:in `start'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  foo/Vendor/bundle/ruby/2.3.0/gems/fastlane-2.31.0/bin/fastlane:20:in `<top (required)>'
  foo/Vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load'
  foo/Vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'
```

**Comment by tcurdt** [comment]
Further investigations show the response changes when there are more than one phone numbers registered for 2FA. The `ArgumentError: [!] unknown keyword: enabled_features` is another error.

**Comment by KrauseFx** [comment]
Looking at the logs, you're using a 6 months old versions, please make sure to run `[sudo] gem uninstall fastlane` and `[sudo] gem cleanup`, and then `gem install fastlane` again 👍

**Comment by tcurdt** [comment]
Something went horribly wrong here. After cleaning out the `Gemfile.lock` and a clean install the proper code was in place. Weird. Sorry for the noise.

**Comment by KrauseFx** [comment]
Glad to hear you have it resolved 👍  Sorry you ran into this problem.
