### ISSUE TITLE
sigh --force generate provisioning profile with incorrect Custon/Special Entitlements options

### ISSUE THREAD

**Issue by chongj615** [fastlane/fastlane#9227]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
When you regenerate a provisioning profile using the force flag to add all new devices, the regenerated provisioning profile doesn't take into account the Entitlements options, instead always come back as Default.

This is the entitlement in provisioning profile I refer to:
![image](https://cloud.githubusercontent.com/assets/4042482/26266711/6e6557c8-3c9b-11e7-9aaa-c83345769afa.png)

I believe this is similar to this issue
https://github.com/fastlane/fastlane/issues/4548

fastlane sigh --adhoc -a com.nnn.nnn -u chong@nnn.com --team_id NNNNNNN --provisioning_name=adhoc-ios --force 

+-------------------------------------+---------------------+
|                  Summary for sigh 2.32.1                  |
+-------------------------------------+---------------------+
| adhoc                               | true                |
| app_identifier                      | com.nnn.nnn |
| username                            | chong@nnn.com  |
| team_id                             | nnnnnnn         |
| provisioning_name                   | adhoc-ios           |
| force                               | true                |
| development                         | false               |
| skip_install                        | false               |
| ignore_profiles_with_different_name | false               |
| skip_fetch_profiles                 | false               |
| skip_certificate_verification       | false               |
| platform                            | ios                 |
+-------------------------------------+---------------------+

[13:53:32]: Starting login with user 'chong@nnn.com'
[13:53:34]: Successfully logged in
[13:53:34]: Fetching profiles...
[13:53:35]: Verifying certificates...
[13:53:36]: Found 1 matching profile(s)
[13:53:36]: Recreating the profile
[13:53:37]: Creating new provisioning profile for 'com.nnnn.nnn' with name 'adhoc-ios' for 'ios' platform
[13:53:38]: Downloading provisioning profile...
[13:53:38]: Successfully downloaded provisioning profile...
[13:53:38]: Installing provisioning profile...
/Users/chong/AdHoc_com.nnn.nnn.mobileprovision

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.0                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.32.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-19**
</details>

**Comment by Fluzzarn** [comment]
When creating the Provisioning Profile through the Developer Center, it seems a "template" variable is passed in when a special entitlement is provided. It seems that sigh doesn't pass this variable when creating provisioning profiles. This is the reason why no provisioning profiles created with fastlane have custom entitlements enabled.

**Comment by Fluzzarn** [comment]
Update:

Modifying create_provisioning_profile in portal_client.rb in Spaceship to include a "template" key  with a value that can be found by inspecting the Entitlements dropdown, and running a match --force, it seemed to generate a new provisioning profile with the entitlement included.

      params = {
        teamId: team_id,
        provisioningProfileName: name,
        appIdId: app_id,
        distributionType: distribution_method,
        certificateIds: certificate_ids,
        deviceIds: device_ids,
        template: "<Can Be Found On The Developer Center>"
      }
