### ISSUE TITLE
increment_version_number & increment_build_number for specific target

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#9229]
### New Issue Checklist

- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have multiple targets (10 at the moment) for one project and I am releasing as seperat apps, so I really need to be able to bumb version and build number for a specific target.

Please add a target argument to each method - I will really like to avoid this manual step!
 
Right now it changes the number for all targets. (but the target argument is included in the get_version_number method)

**Comment by taquitos** [comment]
We use `agvtool` to do this work. It only supports changing the version to the same thing for all targets 😢 
To make this work individually for each target, we'd need to build some more custom parsing/updating. Furthermore, Xcode would prefer you to have the same bundle version for each target, but a different marketing version in their respective Info.plists.
You might be able to build this using the `xcodeproj` gem 👍

**Comment by mortenholmgaard** [comment]
This solves the problem:
https://github.com/SiarheiFedartsou/fastlane-plugin-versioning

To get started:
fastlane add_plugin versioning

Then you can do it like this:

increment_build_number_in_plist(target: 'appName')
increment_version_number_in_plist(target: 'appName')
