### ISSUE TITLE
Produce action for Android

### ISSUE THREAD

**Issue by felipeplets** [fastlane/fastlane#9231]
Is there any available option within Fastlane for a "fastlane produce" like feature for Google Play?

**Comment by PetrosIchor** [comment]
To my knowledge Google's APIs do not allow for this functionality.

**Comment by KrauseFx** [comment]
We actually have some GitHub issues for this already, e.g. https://github.com/fastlane/fastlane/issues/4215 and https://github.com/fastlane/fastlane/issues/722
