### ISSUE TITLE
Password correct and will not log in

### ISSUE THREAD

**Issue by matthewfowles** [fastlane/fastlane#9232]
### Issue Description

When I try to run `fastlane beta` my log in details do not work. I have a password that contains uppercase, lowercase and numbers but no other special characters. When I ran `fastlane init` it worked fine and I can only find issues that pertain to special characters being present. Has any had the same issue?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `beta`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/matthewfowles/projects/projectPig/fastlane/Appfile'
- app_identifier: 'projectpig'
- apple_id: 'matt@matthewfowles.io'
- team_id: '4LQVXQV288'
-------
DEBUG [2017-05-21 21:19:42.10]: Checking if there are any plugins that should be loaded...
INFO [2017-05-21 21:19:42.12]: -------------------------------------------------
INFO [2017-05-21 21:19:42.12]: --- Step: Verifying required fastlane version ---
INFO [2017-05-21 21:19:42.12]: -------------------------------------------------
INFO [2017-05-21 21:19:42.12]: Your fastlane version 2.32.1 matches the minimum requirement of 2.32.1  ✅
INFO [2017-05-21 21:19:42.13]: ------------------------------
INFO [2017-05-21 21:19:42.13]: --- Step: default_platform ---
INFO [2017-05-21 21:19:42.13]: ------------------------------
INFO [2017-05-21 21:19:42.13]: Driving the lane 'ios beta' 🚀
INFO [2017-05-21 21:19:42.14]: -------------------
INFO [2017-05-21 21:19:42.14]: --- Step: match ---
INFO [2017-05-21 21:19:42.14]: -------------------
INFO [2017-05-21 21:19:42.18]: Successfully loaded '/Users/matthewfowles/projects/projectPig/fastlane/Matchfile' 📄

+----------------+--------------------------------------+
|      Detected Values from './fastlane/Matchfile'      |
+----------------+--------------------------------------+
| git_url        | git@github.com:matthewfowles/projec  |
|                | tPig.git                             |
| shallow_clone  | false                                |
| app_identifier | projectpig                           |
| username       | matthewfowles                        |
+----------------+--------------------------------------+

DEBUG [2017-05-21 21:19:42.18]: Taking value for 'team_id' from environment variable 'FASTLANE_TEAM_ID'

+-----------------------+--------------------------------------+
|                   Summary for match 2.32.1                   |
+-----------------------+--------------------------------------+
| type                  | appstore                             |
| git_url               | git@github.com:matthewfowles/projec  |
|                       | tPig.git                             |
| shallow_clone         | false                                |
| app_identifier        | projectpig                           |
| username              | matthewfowles                        |
| git_branch            | master                               |
| keychain_name         | login.keychain                       |
| readonly              | false                                |
| team_id               | 4LQVXQV288                           |
| verbose               | false                                |
| force                 | false                                |
| skip_confirmation     | false                                |
| clone_branch_directly | false                                |
| force_for_new_devices | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

INFO [2017-05-21 21:19:42.19]: Cloning remote git repo...
INFO [2017-05-21 21:19:42.19]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2017-05-21 21:19:42.19]: $ GIT_TERMINAL_PROMPT=0 git clone 'git@github.com:matthewfowles/projectPig.git' '/var/folders/k6/7mhb8k8d3lb5cnzy67rjwszr0000gn/T/d20170521-61116-imbebp'
INFO [2017-05-21 21:19:42.20]: ▸ Cloning into '/var/folders/k6/7mhb8k8d3lb5cnzy67rjwszr0000gn/T/d20170521-61116-imbebp'...
INFO [2017-05-21 21:20:59.78]: ▸ remote: Counting objects: 612, done.[K
INFO [2017-05-21 21:20:59.89]: ▸ remote: Compressing objects: 100% (393/393), done.[K
INFO [2017-05-21 21:22:27.35]: ▸ remote: Total 612 (delta 169), reused 587 (delta 148), pack-reused 0[K
INFO [2017-05-21 21:22:27.43]: ▸ Receiving objects: 100% (612/612), 32.14 MiB | 302.00 KiB/s, done.
INFO [2017-05-21 21:22:27.44]: ▸ Resolving deltas: 100% (169/169), done.
INFO [2017-05-21 21:22:28.10]: 🔓  Successfully decrypted certificates repo
INFO [2017-05-21 21:22:28.10]: Verifying that the certificate and profile are still valid on the Dev Portal...
The login credentials for 'matthewfowles' seem to be wrong
The password was taken from the environment variable
Please make sure it is correct
Please run this tool again to apply the new password
ERROR [2017-05-21 21:22:28.64]: An error occurred while verifying your certificates and profiles with the Apple Developer Portal.
ERROR [2017-05-21 21:22:28.64]: If you already have your certificates stored in git, you can run `fastlane match` in readonly mode
ERROR [2017-05-21 21:22:28.64]: to just install the certificates and profiles without accessing the Dev Portal.
ERROR [2017-05-21 21:22:28.64]: To do so, just pass `readonly: true` to your match call.
WARN [2017-05-21 21:22:29.13]: Lane Context:
INFO [2017-05-21 21:22:29.13]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
ERROR [2017-05-21 21:22:29.13]: Invalid User Credentials
INFO [2017-05-21 21:22:29.13]: Successfully generated documentation at path '/Users/matthewfowles/projects/projectPig/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | match               | 166         |
+------+---------------------+-------------+

ERROR [2017-05-21 21:22:29.14]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Invalid User Credentials

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Invalid%20User%20Credentials+repo:fastlane/fastlane
➡️  authentication problems on second user
    https://github.com/fastlane/fastlane/issues/9230 [open] 1 💬
    a day ago

➡️  Pilot Fails with 'invalid request body' message
    https://github.com/fastlane/fastlane/issues/7523 [closed] 2 💬
    22 Mar 2017

➡️  Getting 'invalid username and password combination'
    https://github.com/fastlane/fastlane/issues/6977 [closed] 5 💬
    4 weeks ago

and 10 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Invalid%20User%20Credentials&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.32.1"

default_platform :ios

platform :ios do

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore")

    gym(
      scheme: "projectPig",
      project: './ios/projectPig.xcworkspace'
    )

    pilot

  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "projectpig" # The bundle identifier of your app
apple_id "matt@matthewfowles.io" # Your Apple email address

team_id "4LQVXQV288" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.32.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| psych                     | 2.0.8        |
</details>

*generated on:* **2017-05-21**
</details>

**Comment by KrauseFx** [comment]
It looks like you have `FASTLANE_PASSWORD` or `DELIVER_PASSWORD` set, can you verify that those values are correct?

**Comment by matthewfowles** [comment]
Yes i only set `FASTLANE_PASSWORD` to check is was not an issue typing it in. That password is correct

**Comment by mteece** [comment]
@matthewfowles @KrauseFx  I see the ticket as closed, but would like to confirm the findings. I was receiving this exact same error on our Team City CI server(s) for the past two days on fastlane 2.54.1 version.

The issues pertain to special characters being present in the password. In the Fastfile if you echo the ENV["FASTLANE_PASSWORD"] variable like so:
```
 lane :develop do
 ...
 puts ENV["FASTLANE_PASSWORD"]
 ...
 end
```

You can see the output when you run the lane: of the password missing special characters like $!@. Obviously attempting to login with the incorrect password will cause problems. I tested this with .env files as well as fastlane-credentials for storing the passwords. In both cases ENV["FASTLANE_PASSWORD"] was missing the passwords special characters.

The easiest fix is to make a simpler, albeit weaker, password.

**Comment by ohayon** [comment]
@mteece Apologies if this is a stupid question, but are you defining your `FASTLANE_PASSWORD` env var with quotes like so: `FASTLANE_PASSWORD="s0mep@ssw0rd"` I have special characters in my password also and I have not run into this issue 😄 .

**Comment by mteece** [comment]
My **.env** file `FASTLANE_PASSWORD` is in quotes - now that is 😄. Thanks @ohayon!
