### ISSUE TITLE
Extant invalid screenshots & metadata prevents making any changes

### ISSUE THREAD

**Issue by jbg** [fastlane/fastlane#9234]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We have 180 or so existing apps which have previously valid, but now invalid, metadata and screenshots on iTunes Connect. Specifically they have app names that are now considered too long, and missing iPad screenshots (oddly, the current release on the App Store has iPad screenshots, but they are now missing on iTunes Connect).

This situation appears to prevent us updating either the metadata or the screenshots with Fastlane when submitting a new build.

Using `skip_metadata: true, skip_screenshots: false` we get an error about the app name being too long.
Using `skip_metadata: false, skip_screenshots: true` we get an error about the missing iPad screenshots.
Using `skip_metadata: false, skip_screenshots: false` we get an error about the missing iPad screenshots.
Using `skip_metadata: true, skip_screenshots: true` we get an error about the missing iPad screenshots.

Not sure how to proceed.

**Comment by taquitos** [comment]
Hey @jbg, could you attach your complete output from the tool as well? That should help us diagnose this stuff.

Also, what happens if you do the same thing, manually in itunes connect?
