### ISSUE TITLE
pilot - there is no web session to update (on upload)

### ISSUE THREAD

**Issue by btrzupek** [fastlane/fastlane#9237]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
when running "fastlane pilot upload" I get the following error:

**there is no web session to update**

It was working earlier today, and now I get this error every time.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

/Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/spaceship/lib/spaceship/tunes/tunes_client.rb:222:in `handle_itc_response': [!] The request could not be completed because: (Spaceship::TunesClient::ITunesConnectError)
	there is no web session to update
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/spaceship/lib/spaceship/tunes/tunes_client.rb:94:in `team_id='
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/spaceship/lib/spaceship/tunes/tunes_client.rb:121:in `select_team'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/spaceship/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/pilot/lib/pilot/manager.rb:16:in `login'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/pilot/lib/pilot/manager.rb:8:in `start'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/pilot/lib/pilot/build_manager.rb:6:in `upload'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/pilot/lib/pilot/commands_generator.rb:60:in `block (2 levels) in run'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/gems/fastlane-2.32.1/bin/fastlane:20:in `<top (required)>'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/bin/fastlane:23:in `load'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/bin/fastlane:23:in `<main>'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@my_project/bin/ruby_executable_hooks:15:in `<main>'

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                          |
| --------------------------- | ---------------------------------------------- |
| OS                          | 10.12.5                                        |
| Ruby                        | 2.4.0                                          |
| Bundler?                    | false                                          |
| Git                         | git version 2.11.0 (Apple Git-81)              |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0@my_project/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                   |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                    |
| Is contained                | false                                          |
| Is homebrew                 | false                                          |
| Is installed via Fabric.app | false                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/    |
| Xcode Version               | 8.3.2                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.30.2"

default_platform :ios

platform :ios do
  lane :beta do |options|
    # sync provisioning profiles	
    match(type: "appstore", readonly: true)
    	
    # increment the build number
    increment_build_number

    # build the app
    gym(
      scheme: "Blast Dev"
    )
    
    # Upload the app to testflight
    pilot(
	skip_waiting_for_build_processing: true,
    )
    
    # Clean up what we just did, any leftover files
    clean_build_artifacts
	
    # Now commit the build number back to Git
    commit_version_bump(
          xcodeproj: "Blast.xcodeproj",
          force: true
    )  
end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.trzupek.Blast-Dev" # The bundle identifier of your app
apple_id "REDACTED@gmail.com" # Your Apple email address

team_id "REDACTED" # Developer Portal Team ID
itc_team_id "REDACTED" # ITC Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.32.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.0       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-05-22**
</details>

**Comment by nikhildaga** [comment]
I am getting the same error

**Comment by milesalex** [comment]
sameeee

**Comment by KelvinEC** [comment]
Same

**Comment by ChrisVolentine** [comment]
Yep, same here

**Comment by allewun** [comment]
Here's my [.fastlane/latest_crash.json](https://github.com/fastlane/fastlane/files/1020493/latest_crash.json.txt). Hope this adds some more context.

```
[EXCEPTION]: Spaceship::TunesClient::ITunesConnectError: there is no web session to update
[fastlane_path]/spaceship/lib/spaceship/tunes/tunes_client.rb:222:in `handle_itc_response'
[fastlane_path]/spaceship/lib/spaceship/tunes/tunes_client.rb:94:in `team_id='
[fastlane_path]/spaceship/lib/spaceship/tunes/tunes_client.rb:121:in `select_team'
[fastlane_path]/spaceship/lib/spaceship/tunes/spaceship.rb:30:in `select_team'
[fastlane_path]/fastlane/lib/fastlane/actions/app_store_build_number.rb:13:in `run'
[fastlane_path]/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:11:in `run'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
[fastlane_path]/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:226:in `chdir'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
[fastlane_path]/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
Fastfile:84:in `block (2 levels) in parsing_binding'
[fastlane_path]/fastlane/lib/fastlane/lane.rb:33:in `call'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:45:in `chdir'
[fastlane_path]/fastlane/lib/fastlane/runner.rb:45:in `execute'
[fastlane_path]/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
[fastlane_path]/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
[fastlane_path]/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
[gem_home]/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
[gem_home]/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
[gem_home]/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
[fastlane_path]/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
[gem_home]/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
[fastlane_path]/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
[fastlane_path]/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
[fastlane_path]/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
[fastlane_path]/bin/fastlane:20:in `<top (required)>'
[gem_home]/bin/fastlane:23:in `load'
[gem_home]/bin/fastlane:23:in `<top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/opt/rubies/ruby-2.3.1/bin/bundle:23:in `load'
/opt/rubies/ruby-2.3.1/bin/bundle:23:in `<main>'
```

**Comment by btrzupek** [comment]
Just to add a bit more context, when I went and manually logged into ITC there was a new modal dialog telling me about some new features Apple introduced in TestFlight.  IIRC, I saw this the other day too, so I am not sure why I am seeing it again or if it is related. However, if you are doing some form or web scraping, perhaps this is a clue to you that they maybe changed something you rely upon.

**Comment by astrokin** [comment]
+1

**Comment by alwindeep** [comment]
Same issue for me as well.

**Comment by CesarDominguez** [comment]
Wow this is really on the fly... I'm getting the same!

**Comment by jriskin** [comment]
So sad... no new builds since 3:24pm PST...

**Comment by nikhildaga** [comment]
Has anyone been able to upload using xcode? I think it may be a problem with Apple than fastlane

**Comment by KrauseFx** [comment]
Hey everyone, thanks for submitting the issue, we'll look into this right now, and will try to have a fix available as soon as possible 🚀 Sorry for the issue

**Comment by KrauseFx** [comment]
We just pushed a PR that fixes the problem https://github.com/fastlane/fastlane/pull/9238, we'll ship a new release as soon as possible 🚀 💥

**Comment by btrzupek** [comment]
@KrauseFx - dude, thanks so much for fixing this - so quickly. We are back in business now. I really appreciate your efforts.

**Comment by mashour** [comment]
@KrauseFx thank you so much for the quick fix!

**Comment by CesarDominguez** [comment]
this was very interesting to watch!

**Comment by jalexreyes** [comment]
Thank you @KrauseFx for all the amazing work.

**Comment by jjnino** [comment]
Thanks for the quick fix!

**Comment by CesarDominguez** [comment]
Is it needed to update something on a special form?, I'm still having the issue D:

**Comment by salanki** [comment]
Impressive!

**Comment by pbassut** [comment]
That was really quick. Thanks guys!

**Comment by KrauseFx** [comment]
Thanks everyone for confirming, so glad everything is up and running again 👍 I actually worked together with @taquitos on this fix, who joined the _fastlane_ team about a month ago 😺  Expect some cool things he'll be working on 🚀

**Comment by estebansolis** [comment]
Sorry guys. What is the update command when you installed fastlane through homebrew?

**Comment by KelvinEC** [comment]
fastalane update_fastlane

**Comment by RudolfVonKrugstein** [comment]
Which version is the one which makes it start working? fastlane 2.35.1 does no work here ...

**Comment by BrunoMiguens** [comment]
This issue still happening at version 2.35.1.

**Comment by KrauseFx** [comment]
@BrunoMiguens We just tried it with the most recent fastlane version, and things are working as expected. Please submit a new issue on GitHub with more information on how to reproduce it 👍
