### ISSUE TITLE
fastlane init error

### ISSUE THREAD

**Issue by ufosky** [fastlane/fastlane#9241]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I want to setup fastlane for my project, so I run `fastlane init` in my project directory, but after I enter my Apple ID, the system popup an window like the image below, and the terminal show some error info like this:

```
[11:37:42]: Ran into error while trying to connect to iTunes Connect / Dev Portal: Unauthorized Access
[11:37:42]: Falling back to manual onboarding
[11:37:42]: Unauthorized Access
[11:37:42]: An error occurred during the setup process. Falling back to manual setup!
```
![appleid_login](https://cloud.githubusercontent.com/assets/801838/26337763/ccb3f70c-3fad-11e7-8d07-673fa214ba90.png)

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| bundler                   | 1.15.0       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>


*generated on:* **2017-05-23**
</details>
```

**Comment by KrauseFx** [comment]
Could you try it again using `--verbose` and share the complete output when running _fastlane_? Thanks 👍

**Comment by ufosky** [comment]
```
 fastlane init --verbose
DEBUG [2017-05-23 12:05:10.22]: Checking if there are any plugins that should be loaded...
INFO [2017-05-23 12:05:10.35]: Detected iOS/Mac project in current directory...
INFO [2017-05-23 12:05:10.35]: This setup will help you get up and running in no time.
INFO [2017-05-23 12:05:10.35]: fastlane will check what tools you're already using and set up
INFO [2017-05-23 12:05:10.35]: the tool automatically for you. Have fun!
INFO [2017-05-23 12:05:10.35]: $ xcodebuild -list -workspace ./******.xcworkspace
INFO [2017-05-23 12:05:13.51]: $ xcodebuild -showBuildSettings -workspace ./******.xcworkspace -scheme ******
 [2017-05-23 12:05:16.18]: Your Apple ID (e.g. fastlane@krausefx.com): ******
WARN [2017-05-23 12:05:27.37]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
INFO [2017-05-23 12:05:27.37]: Starting login with user '******'
INFO [2017-05-23 12:05:30.78]: Ran into error while trying to connect to iTunes Connect / Dev Portal: Unauthorized Access
INFO [2017-05-23 12:05:30.78]: Falling back to manual onboarding
ERROR [2017-05-23 12:05:30.78]: Unauthorized Access
ERROR [2017-05-23 12:05:30.78]: An error occurred during the setup process. Falling back to manual setup!
 [2017-05-23 12:05:30.78]: App Identifier (com.krausefx.app):
```

**Comment by nechmads** [comment]
I got the same thing and it started after I updated to the latest fastlane. It stopped asking for the results of the 2 factor authentication

**Comment by nechmads** [comment]
INFO [2017-05-23 13:56:09.21]: Ran into error while trying to connect to iTunes Connect / Dev Portal: Unauthorized Access
INFO [2017-05-23 13:56:09.21]: Falling back to manual onboarding
ERROR [2017-05-23 13:56:09.21]: Error occurred with the setup program! Reverting changes now!
WARN [2017-05-23 13:56:09.21]: Deleting the 'fastlane' folder

Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Unauthorized Access

URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unauthorized%20Access+repo:fastlane/fastlane
➡️  Produce crashes while app creation
    https://github.com/fastlane/fastlane/issues/6960 [closed] 2 💬
    12 Feb 2017

➡️  In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels , at least 72 DPI, and in the RGB color space - deliver 1.1.0
    https://github.com/fastlane/fastlane/issues/1590 [closed] 42 💬
    06 Dec 2016

➡️  Binary upload invalid / [!] {"data"=>nil, "messages"=>{"warn"=>nil, "error"=>["ITC.response.error.OPERATION_FAILED"], "info"=>nil}, "statusCode"=>"ERROR"}
    https://github.com/fastlane/fastlane/issues/6419 [closed] 84 💬
    4 weeks ago

and 2 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:627:in `block in send_request': [!] The request could not be completed because: (Spaceship::Client::UnauthorizedAccessError)
	Unauthorized Access
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:466:in `with_retry'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:621:in `send_request'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:510:in `request'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:410:in `send_shared_login_request'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:588:in `do_login'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:119:in `login'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/spaceship/lib/spaceship/portal/spaceship.rb:82:in `login'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/setup/setup_ios.rb:218:in `detect_if_app_is_available'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/setup/setup_ios.rb:127:in `ask_to_enable_other_tools'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/setup/setup_ios.rb:117:in `manual_setup'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/setup/setup_ios.rb:42:in `run'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/setup/setup.rb:29:in `run'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/commands_generator.rb:122:in `block (2 levels) in run'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/nechmads/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.33.0/bin/fastlane:20:in `<top (required)>'
	from /Users/nechmads/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/nechmads/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by KrauseFx** [comment]
Hey everyone, taking a closer look at this, it seems like this issue might be related to a server in some regions not being updated yet. Are you all based in China? Can you try to use a VPN outside, and see if that fixes the issue?

**Comment by jeanetienne** [comment]
@KrauseFx that's it! I'm in Australia and have the same problem. I've connected to Sweden with my VPN and now it works ;)

**Comment by KrauseFx** [comment]
Hey @jeanetienne thanks for confirming that this is dependent on where in the world you're located. Easy fix would be to all relocate to San Francisco I'd say :trollface:, or until this problem is fixed on the server-side, you can use a VPN 👍

**Comment by jeanetienne** [comment]
Hehe, I'll stick with the VPN for now ;)
Just curious, is this a case of "You've added support to a change too quickly, before Apple had time to fully roll it out"?

**Comment by ggallotti** [comment]
Same problem here.

**Comment by KrauseFx** [comment]
@jeanetienne Hehe, I don't think that's the case. What happens when you use iTunes Connect in your browser and switch teams?

**Comment by jeanetienne** [comment]
@KrauseFx I only have one team... I have several App IDs prefixes thought, for some reason..

**Comment by nechmads** [comment]
I’m in Chicago...

Shahar Nechmad
Entrepreneur & Explorer
Https://www.facebook.com/nechmads
+1.415.307.5378

**Comment by duckwaffle** [comment]
I'm getting the same problem on my Macincloud VSTS agent, which I am assuming is located in north america, but I can't be certain.

**Comment by nechmads** [comment]
I'm in Chicago currently. I tried to connect to a U.S. VPN to check another location and still same result :(

**Comment by KrauseFx** [comment]
@nechmads @duckwaffle Just to verify: Are you only experiencing this on `fastlane init` or on any _fastlane_ command that interact with iTunes Connect?

**Comment by duckwaffle** [comment]
@KrauseFx I'm only experiencing the issue on `fastlane pilot upload`, as that is all that the VSTS agent is using fastlane for. To be honest, that is all I have ever used fastlane for anyway haha.

**Comment by nechmads** [comment]
I'm getting this on all commands. For example: when running "fast lane produce". It asks for my user ID and the moment the 2 factor authentication message box shows up, I also get the error message: "[!] The request could not be completed because:
	Unauthorized Access"

**Comment by a13xb** [comment]
> Just to verify: Are you only experiencing this on `fastlane init` or on any _fastlane_ command that interact with iTunes Connect?

@KrauseFx I'm getting this with `match`, and it does not depend on the region (using VPN).

**Comment by KrauseFx** [comment]
Hey everyone, thanks for reporting this - this might be related to 2 factor auth after the recent change with #9238 👍 We're trying to work on a fix. via @taquitos

**Comment by taquitos** [comment]
Hey all, this should be fixed now. Let us know if this is still failing with the most recent _fastlane_ release

**Comment by emcniece** [comment]
@taquitos first time user, hitting this issue running `fastlane init` for the first time. I'm in Canada.

Output of `fastlane init`:

```
+----------------+------------------------------+
|          Summary for produce 2.35.1           |
+----------------+------------------------------+
| app_name       | ***                          |
| app_identifier | ***                          |
| username       | ***                          |
| sku            | 1496186454                   |
| platform       | ios                          |
| language       | English                      |
| skip_itc       | false                        |
| skip_devcenter | false                        |
| team_id        | ***                          |
+----------------+------------------------------+

[16:20:55]: [DevCenter] App '***' already exists, nothing to do on the Dev Center
[16:21:14]: Verifying that app is available on the Apple Developer Portal and iTunes Connect...
[16:21:14]: Starting login with user '***'
[16:21:33]: Error occurred with the setup program! Reverting changes now!
[16:21:33]: Deleting the 'fastlane' folder
[16:21:34]: fastlane failed to write the crash report to /Users/***/.fastlane/latest_crash.json.
[16:21:34]: Sending crash report...
[16:21:34]: The stacktrace is sanitized so no personal information is sent.
[16:21:34]: To see what we are sending, look here: /Users/***/.fastlane/latest_crash.json
[16:21:34]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[16:21:34]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

Looking for related GitHub issues on fastlane/fastlane...

➡️  fastlane init error
    https://github.com/fastlane/fastlane/issues/9241 [open] 20 💬
    4 days ago

➡️  2 Factor on Travis CI
    https://github.com/fastlane/fastlane/issues/9244 [closed] 6 💬
    a week ago

➡️  Produce crashes while app creation
    https://github.com/fastlane/fastlane/issues/6960 [closed] 2 💬
    12 Feb 2017

and 4 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unauthorized%20Access&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
        Unauthorized Access
```

Output of `fastlane env`:

```
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.3/bin/fastlane       |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
</details>


*generated on:* **2017-05-30**
</details>
```

**Comment by taquitos** [comment]
@emcniece this actually looks like a different issue (but seemingly similar issue) could you open a new issue with this attached information?

Also, could you let us know what happens when you login to iTunes Connect with the user from `username` in your browser and switch teams? It seems like _spaceship_ is running into problems selecting what team to use.

**Comment by nechmads** [comment]
This was fixed for me. I now can enter the 6 digit number and fast lane connects to iTunes Connect

**Comment by nechmads** [comment]
Thanks for the fix!! :) 👍

**Comment by ohayon** [comment]
Hi everyone! I am going to close this issue for now as it seems like the fix works. Let us know if you are running into any more issues!! 🚀
