### ISSUE TITLE
betaReviewInfo is missing in Pilot

### ISSUE THREAD

**Issue by punksta** [fastlane/fastlane#9242]
### Issue Description

Testflight ask contact information like: email, name, phone. But email is required

![itunescconnect](https://cloud.githubusercontent.com/assets/13404754/26350862/a52a3362-3fbd-11e7-9567-8751aee43a68.png)

If I don't set email manually , I get error dialog:
```
Sorry, something went wrong.
ITC.BetaReviewInfo.contactEmail.invalid.email
```

same error message from pilot: 
```
[04:43:58][Step 2/2] [04:43:58]: Could not set beta_app_feedback_email and/or beta_app_description: {"code"=>"ITC.BetaReviewInfo.contactEmail.invalid.email", "description"=>"Value for field(contactEmail) is not a valid email address."}
```
### Code
```
   if ENV['PILOT_TESTER_EMAIL'] != nil

        Pilot::TesterManager.new.add_tester(
            email: ENV['PILOT_TESTER_EMAIL'],
            first_name: "tester",
            last_name: "tester",
            app_identifier: request['app_namespace']
        )
      end

 pilot(
          ipa: find_ipa,
          changelog: 'bug fix',
          username: user,
          app_identifier: request['app_namespace'],
          beta_app_description: 'app',
          beta_app_feedback_email: DEFAULT_ACC,
          skip_submission: ENV['PILOT_TESTER_EMAIL'] == nil,
      )
```
### Environment
`'fastlane', '~> 2.32.1'`

### Proposal to fix
This is data itunes-connect send:
```
{"primaryLocale":"en-US","details":[{"locale":"en-US","feedbackEmail":"feedback@email.com","marketingUrl":"http://Marketing.com","privacyPolicyUrl":"http://privacy.com","privacyPolicy":null,"description":"Beta App Description"}],"eula":null,"betaReviewInfo":{"contactFirstName":"name","contactLastName":"last name","contactPhone":"phone","contactEmail":"contact@test.com","demoAccountName":"","demoAccountPassword":"","demoAccountRequired":false,"notes":"review notes"}}
```

Pilot does not save betaReviewInfo
https://github.com/fastlane/fastlane/blob/master/pilot/lib/pilot/build_manager.rb#L56

```
//we should add `betaReviewInfo` to pilot.
app_test_info.test_info.betaReviewInfo = options[:betaReviewInfo] if options[:betaReviewInfo]
```

**Comment by taquitos** [comment]
A work around is that you can use the browser to set this (as you found out). Does it work for you that you can set it once manually and then automate the rest? It's some work for us to pass this through so I'd like to gauge how much of a pain this is for you!

**Comment by punksta** [comment]
@taquitos we could make it manually, but in our business process we creates apps automatically from register new app_id in developer portal
