### ISSUE TITLE
Match did not asks for password

### ISSUE THREAD

**Issue by the4thfloor** [fastlane/fastlane#9243]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I created a new project, called `fastlane match init` followed by `fastlane match development`.
Fastlane / Match hangs with:

[15:44:56]: Cloning remote git repo...
[15:44:56]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.

The git url is `git@bitbucket.org:ralphbergmann/test.git`

I guess Match can't log in to git because it never asked for the git password. The doc says that it will ask when I run Match at the first time bat this doesn't happened.

What did I wrong?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G8c)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| CFPropertyList                             | 2.3.5        |
| activesupport                              | 4.2.7.1      |
| addressable                                | 2.5.1        |
| babosa                                     | 1.0.2        |
| bigdecimal                                 | 1.2.6        |
| bundler                                    | 1.14.3       |
| claide                                     | 1.0.1        |
| cocoapods                                  | 1.2.0        |
| cocoapods-core                             | 1.2.0        |
| cocoapods-deintegrate                      | 1.0.1        |
| cocoapods-downloader                       | 1.1.3        |
| cocoapods-plugins                          | 1.0.0        |
| cocoapods-search                           | 1.0.0        |
| cocoapods-stats                            | 1.0.0        |
| cocoapods-trunk                            | 1.1.2        |
| cocoapods-try                              | 1.1.0        |
| colored                                    | 1.2          |
| colored2                                   | 3.1.2        |
| commander                                  | 4.4.3        |
| commander-fastlane                         | 4.4.4        |
| domain_name                                | 0.5.20161129 |
| dotenv                                     | 2.2.0        |
| escape                                     | 0.0.4        |
| excon                                      | 0.55.0       |
| faraday                                    | 0.11.0       |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.11.0.1     |
| fastimage                                  | 2.1.0        |
| fastlane-plugin-update_project_codesigning | 0.1.9        |
| fourflusher                                | 2.0.1        |
| fuzzy_match                                | 2.0.4        |
| gh_inspector                               | 1.0.3        |
| google-api-client                          | 0.9.26       |
| googleauth                                 | 0.5.1        |
| highline                                   | 1.7.8        |
| http-cookie                                | 1.0.3        |
| httpclient                                 | 2.8.3        |
| hurley                                     | 0.2          |
| i18n                                       | 0.8.1        |
| io-console                                 | 0.4.3        |
| json                                       | 1.8.1        |
| jwt                                        | 1.5.6        |
| libxml-ruby                                | 2.9.0        |
| little-plugger                             | 1.1.4        |
| logging                                    | 2.1.0        |
| memoist                                    | 0.15.0       |
| mime-types                                 | 3.1          |
| mime-types-data                            | 3.2016.0521  |
| mini_magick                                | 4.5.1        |
| minitest                                   | 5.10.1       |
| molinillo                                  | 0.5.6        |
| multi_json                                 | 1.12.1       |
| multi_xml                                  | 0.6.0        |
| multipart-post                             | 2.0.0        |
| nanaimo                                    | 0.2.3        |
| nap                                        | 1.1.0        |
| netrc                                      | 0.7.8        |
| nokogiri                                   | 1.5.6        |
| os                                         | 0.9.6        |
| plist                                      | 3.2.0        |
| power_assert                               | 0.2.2        |
| psych                                      | 2.0.8        |
| public_suffix                              | 2.0.5        |
| rake                                       | 10.4.2       |
| rdoc                                       | 4.2.0        |
| representable                              | 2.3.0        |
| retriable                                  | 2.1.0        |
| rouge                                      | 1.11.1       |
| ruby-macho                                 | 0.2.6        |
| rubygems-update                            | 2.5.2        |
| rubyzip                                    | 1.2.1        |
| security                                   | 0.1.3        |
| signet                                     | 0.7.3        |
| slack-notifier                             | 1.5.1        |
| sqlite3                                    | 1.3.13       |
| terminal-notifier                          | 1.7.1        |
| terminal-table                             | 1.7.3        |
| test-unit                                  | 3.0.8        |
| thread_safe                                | 0.3.6        |
| tty-screen                                 | 0.5.0        |
| tzinfo                                     | 1.2.3        |
| uber                                       | 0.0.15       |
| unf                                        | 0.1.4        |
| unf_ext                                    | 0.0.7.2      |
| unicode-display_width                      | 1.1.3        |
| word_wrap                                  | 1.0.0        |
| xcodeproj                                  | 1.4.4        |
| xcpretty                                   | 0.2.4        |
| xcpretty-travis-formatter                  | 0.0.4        |
</details>

*generated on:* **2017-05-23**
</details>

**Comment by the4thfloor** [comment]
Note:
- It works when I use a ssh key and not a password to log in
- It is also not working with `https://...` git url

**Comment by taquitos** [comment]
You can add `--verbose` to the command you are running.
That will show you all the operations it is performing.
You can then look for the output of its `git clone` operation and run that manually on in your terminal. It will ask you for a password and only that once, and from then on it will be stored in your keychain.

**Comment by the4thfloor** [comment]
okay I fixed it. First I added the ssh key to the remote server and second I added the MATCH_PASSWORD env variable.

now it works, you can close this ticket
