### ISSUE TITLE
2 Factor on Travis CI

### ISSUE THREAD

**Issue by leoMehlig** [fastlane/fastlane#9244]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I tried to use `sigh` or `cert` with 2-factor auth on travis, but it keeps saying that the session cookie is invalid. I've tried supplying the `FASTLANE_SESSION` in the Fastfile (ENV[..]=..), in my `.travis.yml` (export FAS...=..) and as a env in the travis settings. Every attempt resulted in the same failure.
I also executed the same build script on the Guest account on my Mac, and it worked immediately.
What could be the problem with the travis setup, and did anyone successfully login to their account with 2-factor on travis?
##### Complete output when running fastlane, including the stack trace and command used
```
Starting login with user 'leo****.com'


Two Factor Authentication for account 'leo****.com' is enabled


Your session cookie has been expired.


Please enter the 6 digit code: 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated

```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>ðŸš« fastlane environment ðŸš«</summary>

### Stack

| Key                         | Value                                       |

| --------------------------- | ------------------------------------------- |

| OS                          | 10.12.4                                     |

| Ruby                        | 2.0.0                                       |

| Bundler?                    | false                                       |

| Git                         | git version 2.12.2                          |

| Installation Source         | ~/.rvm/gems/ruby-2.0.0-p648/bin/fastlane    |

| Host                        | Mac OS X 10.12.4 (16E195)                   |

| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.0.0-p648/lib           |

| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |

| Is contained                | false                                       |

| Is homebrew                 | false                                       |

| Is installed via Fabric.app | false                                       |

| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |

| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |

| -------- | ----------- | - |

| LANG     | en_US.UTF-8 | âœ… |

| LC_ALL   | en_US.UTF-8 | âœ… |

| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby


# Customise this file, documentation can be found here:


# https://github.com/fastlane/fastlane/tree/master/fastlane/docs


# All available actions: https://docs.fastlane.tools/actions


# can also be listed using the `fastlane actions` command





# Change the syntax highlighting to Ruby


# All lines starting with a # are ignored when running `fastlane`





# If you want to automatically update fastlane if a new version is available:


# update_fastlane





# This is the minimum version number required.


# Update this, if you use features of a newer version


fastlane_version "2.27.0"





default_platform :ios





platform :ios do


  before_all do


    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


    ENV["KEYCHAIN_NAME"] = "Luubra.keychain"


    ENV["KEYCHAIN_PASSWORD"] = "luubra1234"


    ENV["CERT_PASSWORD"] = "luubra1234"


    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "fgif-mbul-yzpa-hbhf"


    # ENV["SPACESHIP_COOKIE_PATH"] = "cookie/"





    # ENV["FASTLANE_SESSION"] = '---\n- !ruby/object:HTTP::Cookie\n  name: DES5819cad07e44c6b7fec7a5e9503ef8462\n  value: HSARMTKNSRVTWFlarPplTQmb4En9a7hyRG4Qzm0HzrtbUyIy8ZP1iw95L8VVs0fKHBxhXGtR37ydH5sVbRnFmoY/j02cx9nZXKHMIGBJl4SXPm9WNbWv4eDgp+7JtnLuf1tSSRVT\n  domain: idmsa.apple.com\n  for_domain: true\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 2592000\n  created_at: 2017-05-18 18:36:57.306466000 +02:00\n  accessed_at: 2017-05-19 10:22:02.614178000 +02:00\n- !ruby/object:HTTP::Cookie\n  name: dqsid\n  value: tkWF8WFBWA3kQffFRT_8jk6kod7RdT19Lhf8l82tsF4\n  domain: itunesconnect.apple.com\n  for_domain: false\n  path: "/"\n  secure: true\n  httponly: true\n  expires: \n  max_age: 1800\n  created_at: &1 2017-05-19 10:22:04.196407000 +02:00\n  accessed_at: *1\n'


  end





  desc "Runs all the tests"


  lane :test do


    scan


  end





  desc "Submit a new Beta Build to Apple TestFlight"


  desc "This will also make sure the profile is up to date"


  lane :beta do


    # match(type: "appstore") # more information: https://codesigning.guide


    # sh("source ../session.sh")


    # sh("fastlane spaceauth -u leo@leomehlig.com")


    # sh("echo $FASTLANE_SESSION")


    # print ENV["FASTLANE_SESSION"]


    import_certificates


    cert


    ENV["SPACESHIP_COOKIE_PATH"]


    sigh


    gym(scheme: "Fastlane") # Build your app - more options available


    pilot





    # sh "your_script.sh"


    # You can also use other beta testing services here (run `fastlane actions`)


  end





  desc "Deploy a new version to the App Store"


  lane :release do


    # match(type: "appstore")


    # snapshot


    gym(scheme: "Fastlane") # Build your app - more options available


    deliver(force: true)


    # frameit


  end





  # You can define as many lanes as you want





  after_all do |lane|


    # This block is called, only if the executed lane was successful





    # slack(


    #   message: "Successfully deployed new App Update."


    # )


  end





  error do |lane, exception|


    # slack(


    #   message: exception.message,


    #   success: false


    # )


  end


end





def import_certificates


  return unless is_ci?


  begin


    create_keychain(


      name: ENV['KEYCHAIN_NAME'],


      default_keychain: true,


      unlock: true,


      timeout: 3600,


      lock_when_sleeps: false,


      password: ENV["KEYCHAIN_PASSWORD"],


      add_to_search_list: true


    )


  rescue


    unlock_keychain(


        path: ENV["KEYCHAIN_NAME"],


        password: ENV["KEYCHAIN_PASSWORD"],


        set_default: true


    )


  end





  import_certificate(


    certificate_path: "Fastlane/cert.cer",


    keychain_name: ENV["KEYCHAIN_NAME"]


  )





  import_certificate(


    certificate_path: "Fastlane/cert.p12",


    certificate_password: ENV['CERT_PASSWORD'],


    keychain_name: ENV["KEYCHAIN_NAME"]


  )


end





# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md


# All available actions: https://docs.fastlane.tools/actions





# fastlane reports which actions are used. No personal data is recorded.


# Learn more at https://github.com/fastlane/fastlane#metrics


```

</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby


app_identifier "com.luubra.Fastlane" # The bundle identifier of your app


apple_id "leo@leomehlig.com" # Your Apple email address





team_id "P459Y32P65" # Developer Portal Team ID


itc_team_name "Leonard Mehlig"


# you can even provide different app identifiers, Apple IDs and team names per lane:


# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md


```

</details>

### fastlane gems

| Gem      | Version | Update-Status      |

| -------- | ------- | ------------------ |

| fastlane | 2.27.0  | ðŸš« Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |

| ------------------------- | ------------ |

| executable-hooks          | 1.3.2        |

| bundler-unload            | 1.0.2        |

| rubygems-bundler          | 1.4.4        |

| bundler                   | 1.14.6       |

| slack-notifier            | 1.5.1        |

| CFPropertyList            | 2.3.3        |

| claide                    | 1.0.1        |

| colored2                  | 3.1.2        |

| nanaimo                   | 0.2.3        |

| xcodeproj                 | 1.4.4        |

| terminal-notifier         | 1.7.1        |

| terminal-table            | 1.4.5        |

| plist                     | 3.1.0        |

| public_suffix             | 2.0.3        |

| addressable               | 2.5.0        |

| multipart-post            | 2.0.0        |

| word_wrap                 | 1.0.0        |

| tty-screen                | 0.5.0        |

| babosa                    | 1.0.2        |

| colored                   | 1.2          |

| highline                  | 1.7.8        |

| commander-fastlane        | 4.4.4        |

| excon                     | 0.54.0       |

| unf_ext                   | 0.0.7.2      |

| unf                       | 0.1.4        |

| domain_name               | 0.5.20161021 |

| http-cookie               | 1.0.3        |

| faraday-cookie_jar        | 0.0.6        |

| fastimage                 | 1.6.8        |

| gh_inspector              | 1.0.2        |

| uber                      | 0.0.15       |

| representable             | 2.3.0        |

| retriable                 | 2.1.0        |

| mime-types                | 1.25.1       |

| hurley                    | 0.2          |

| faraday                   | 0.9.2        |

| little-plugger            | 1.1.4        |

| multi_json                | 1.12.1       |

| logging                   | 2.1.0        |

| jwt                       | 1.5.6        |

| memoist                   | 0.15.0       |

| os                        | 0.9.6        |

| signet                    | 0.7.3        |

| googleauth                | 0.5.1        |

| httpclient                | 2.8.2.4      |

| google-api-client         | 0.9.19       |

| mini_magick               | 4.5.1        |

| multi_xml                 | 0.5.5        |

| security                  | 0.1.3        |

| xcpretty-travis-formatter | 0.0.4        |

| dotenv                    | 2.1.1        |

| faraday_middleware        | 0.10.0       |

| json                      | 1.8.3        |

| rubyzip                   | 1.2.0        |

</details>

*generated on:* **2017-05-22**

</details>

**Comment by taquitos** [comment]
Hey @leoMehlig, please update to the most recent _fastlane_, Apple changes things a lot, especially around the session so it's good to stay up-to-date. Also, we have this 2 factor guide because it's a common pain point for people. Let me know how if this helps fix it!
https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth

**Comment by leoMehlig** [comment]
If also checked with the latest version (2.33): The error still occurs, but now it crashes after requesting the 2 factor code.

```
INFO [2017-05-23 20:25:37.54]: Starting login with user 'leo****.com'
INFO [2017-05-23 20:25:39.03]: Sending crash report...
INFO [2017-05-23 20:25:39.03]: The stacktrace is sanitized so no personal information is sent.
INFO [2017-05-23 20:25:39.03]: To see what we are sending, look here: /Users/travis/.fastlane/latest_crash.json
INFO [2017-05-23 20:25:39.03]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
INFO [2017-05-23 20:25:39.03]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
Looking for related GitHub issues on fastlane/fastlane...
Search query: The request could not be completed because:
	Unauthorized Access
URL: https://api.github.com/search/issues?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unauthorized%20Access+repo:fastlane/fastlane
➡️  fastlane init error
    https://github.com/fastlane/fastlane/issues/9241 [open] 4 💬
    an hour ago
➡️  Produce crashes while app creation
    https://github.com/fastlane/fastlane/issues/6960 [closed] 2 💬
    12 Feb 2017
➡️  In order to save your changes, all s must be a .jpeg, .jpg, or .png file that is @@DIMENSION_VALUE@@ pixels , at least 72 DPI, and in the RGB color space - deliver 1.1.0
    https://github.com/fastlane/fastlane/issues/1590 [closed] 42 💬
    06 Dec 2016
and 3 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09Unauthorized%20Access&type=Issues&utf8=✓
🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:627:in `block in send_request': [!] The request could not be completed because: (Spaceship::Client::UnauthorizedAccessError)
	Unauthorized Access
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:466:in `with_retry'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:621:in `send_request'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:510:in `request'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:410:in `send_shared_login_request'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:588:in `do_login'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:346:in `login'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/client.rb:119:in `login'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/spaceship/lib/spaceship/portal/spaceship.rb:82:in `login'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/sigh/lib/sigh/runner.rb:15:in `run'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/sigh/lib/sigh/manager.rb:7:in `start'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/sigh/lib/sigh/commands_generator.rb:55:in `block (2 levels) in run'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/sigh/lib/sigh/commands_generator.rb:123:in `run'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/travis/.rvm/gems/ruby-2.1.10/gems/fastlane-2.33.0/bin/fastlane:20:in `<top (required)>'
	from /Users/travis/.rvm/gems/ruby-2.1.10/bin/fastlane:23:in `load'
	from /Users/travis/.rvm/gems/ruby-2.1.10/bin/fastlane:23:in `<main>'
	from /Users/travis/.rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `eval'
	from /Users/travis/.rvm/gems/ruby-2.1.10/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by duckwaffle** [comment]
I'm getting the same issue as @leoMehlig where it is crashing with "unauthorized access". I have even tried generating a new websession on my dev machine and using that.

I am using VSTS with a Macincloud agent for releasing to the app store.

**Comment by leoMehlig** [comment]
@taquitos I followed all the steps described in that guide closely.
I've also updated (see my other comment)
Since this problem only occurs on travis, I suppose it has something to do with the encoding by travis. But I can't figure out what is wrong and how to fix it.

**Comment by KrauseFx** [comment]
Hey everyone, thanks for reporting this - we can reproduce the issue and are working on a fix. This is actually related to the recent change to how auth works https://github.com/fastlane/fastlane/pull/9238 👍 via @taquitos 

Let's move the discussion over to https://github.com/fastlane/fastlane/issues/9261

**Comment by ivanbruel** [comment]
This still seems to be an issue specifically on Travis, I tested a cURL command directly to mimic the request call, and would still not get a 200 status code whereas locally I would.

**Comment by ohayon** [comment]
Locking this issue to move conversation over to #9261
