### ISSUE TITLE
[snapshot] launch arguments

### ISSUE THREAD

**Issue by LordNali** [fastlane/fastlane#9247]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It seems that snapshot doesn't support (anymore?) the launch arguments. Here's my Snapfile:

```
devices(["iPad Pro (12.9 inch)", "iPad Pro (9.7 inch)"])
languages(["en-US", "de-DE"])
scheme "xxx"
output_directory "./fastlane/screenshots"
clear_previous_screenshots true
project "xxx.xcodeproj"
launch_arguments(["fastAnimation", "screenshotsCreate"])
skip_open_summary false
clear_previous_screenshots true
clean true
reinstall_app true
number_of_retries 3
app_identifier "xxx"
```

then my Fastfile contains this lane (among others):
```
lane :screenshotsCreate do |options|
 snapshot()
end
```

The lane itself work's perfectly fine, the UITests run without any issues and the screenshots are taken. But I can't read the supplied launch arguments inside the app (not the testing target!). The arguments array only contains the launch arguments snapshot sets in any case inside the SnapshotHelper.swift class. My own / additional arguments from the Snapfile are not available.

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2a 19 Mar 2015                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#update_fastlane
fastlane_version "1.91.0"

default_platform :ios

platform :ios do

  lane :screenshotsCreate do |options|
    snapshot()
  end

  lane :screenshotsFrame do |options|
    frameit(white: true, path: "./fastlane/screenshots")
    frameit(silver: true, path: "./fastlane/screenshots")
    frameit(gold: true, path: "./fastlane/screenshots")
  end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
apple_id "-" # Your Apple email address
team_id "-"  # Developer Portal Team ID```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.0       |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 2.1.0        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| os                        | 0.9.6        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| google-api-client         | 0.9.19       |
| faraday_middleware        | 0.11.0.1     |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| signet                    | 0.7.3        |
| fastimage                 | 2.1.0        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>


*generated on:* **2017-05-23**
</details>

**Comment by taquitos** [comment]
Hey @LordNali, could you attach your complete output from snapshot as well? That should help us diagnose this stuff.

**Comment by LordNali** [comment]
Okay - I just noticed something strange regarding the launch arguments option:
```
launch_arguments(["myArg1", "myArg2"])
```
These are the two arguments I like to set, but this option in the Snapfile results in **two seperate** runs of the whole snapshot toolchain (and in the end I got all screenshots twice). How do I set the launch argument option so that these two arguments are active at the same time - is this even possible?

**Comment by KrauseFx** [comment]
Check out the docs on launch arguments over [here](https://docs.fastlane.tools/getting-started/ios/screenshots/#advanced-snapshot). You might be able to do that just by having them as one string 👍

**Comment by LordNali** [comment]
Well...I should have read the docs more attentively - writing both launch arguments as **one string** works perfectly - thanks a lot guys.

**Comment by LordNali** [comment]
Okay, well now there's another issue - I'm not sure if I should create a new issue for that (let me know): My App uses (NS)UserDefaults during the startup process to setup the App. I noticed none of my defaults are saved in between two testcases from one and the same snapshot call. 

Between two snapshots executions this is the wanted behaviour and matches my expectation from using the option `reinstall_app true`. Is it possible that the UserDefaults are emptied during each testcase from some reason? I don't think this should be a fastlane issue, but maybe I missed something.

**Comment by LordNali** [comment]
Any ideas regarding the UserDefaults behaviour?

**Comment by LordNali** [comment]
Nobody?

**Comment by KrauseFx** [comment]
You could add some custom code to your app that resets the user defaults if the `SNAPSHOT` preprocessor macro is set.

**Comment by LordNali** [comment]
Well, actually the problem is, that between **each** testcase, the UserDefaults are emptied and I **don't want** that ;-)

**Comment by LordNali** [comment]
I checked my codebase again, but I'm pretty sure this is not a project-specific problem, but rather a generic behaviour from Xcode or (?) snapshot.

Any ideas or recommendations?
