### ISSUE TITLE
Unable to create Crashlytics Beta release without adding app to Fabric account.

### ISSUE THREAD

**Issue by levibostian** [fastlane/fastlane#9248]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a whitelabeled iOS and Android app that I am developing. I use Fabric/Crashlytics Beta for beta testing for all the beta testing of these mobile app builds.

*Goal:* When a new organization comes on board with my app and I need to create a new whitelabeled version of my mobile app for them, I want to be able to simply (1) create a new XCode configuration (or gradle build flavor in Android) and (2) add one line to my Fastlane file and be able to use Fastlane to create a new Crashlytics Beta release of that app. My Fastlane file is all setup so I simply need to add 1 line to it to release this new build flavor/configuration. 

*Problem:* If I create a new XCode configuration (or gradle build flavor), add my configuration to my Fastlane file, and run my Fastlane lane to create a new Crashlytics Beta release for this new build flavor/configuration, I get an error message from Fastlane's Crashlytics action saying Crashlytics cannot upload release notes because my app is "inactive". The issue seems that I have not yet added the app to my Fabric account. Once I go into XCode or Android Studio, and **manually create a new build of this new configuration and run the app on a device**, it will register itself with my Fabric account and then if I run my Fastlane lane again, the issue goes away. The error message for Crashlytics saying my app is "inactive" essentially means that I have not yet manually added my app to my Fabric account yet. 

Is there a way for the Fastlane Crashlytics action to automatically add any new apps to my Fabric account without me having to manually run each and every app that I create just to register it with Fabric? 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Sorry, I am not able to capture the output right now. Since I got it working, I do not have an old output at the moment. 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.30.0"

default_platform :ios

class BuildTarget
  def initialize(name, identifier)
    @name = name
    @identifier = identifier
  end
  
  def name
    @name
  end
  def identifier
    @identifier
  end
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end
  
  build_targets = [BuildTarget.new("Your Circle", "com.curiosityio.yourcircle.YourCircle"),
    BuildTarget.new("Your Circle Beta", "com.curiosityio.yourcircle.Beta"),
    BuildTarget.new("Cancer Really Sucks!", "com.curiosityio.yourcircle.CancerReallySucks")
  ]  
  
  desc "Gems of Hope beta release"
  lane :gems_beta do |values|
    beta_release(scheme: 'Gems of Hope')
  end
  
  desc "Your Circle Beta beta release"
  lane :yourcircle_beta do |values|
    beta_release(scheme: 'Beta')
  end
  
  desc "Create new Fabric beta release"
  lane :beta_release do |values|
    foo = prompt(text: "Did you make sure to enter release notes in ./fastlane/beta_release_notes.txt? [y]")
    bar = prompt(text: "Did you increment the version in XCode? [y]")
    
    build_target_identifiers = []
    build_targets.each { |target| 
      produce(
         username: 'levi@curiosityio.com',
         app_identifier: target.identifier,
         app_name: target.name,
         itc_team_name: 'Curiosity IO, LLC',
         company_name: 'Curiosity IO, LLC',
         language: 'English',
         skip_itc: true
       )
       build_target_identifiers.push(target.identifier)
    }

    scheme = values[:scheme]

    increment_build_number
    register_devices(devices_file: "./fastlane/devices.txt", username: "levi@curiosityio.com")
    match(git_branch: "yourcircle", username: "levi@curiosityio.com", force_for_new_devices: true, type: "adhoc", app_identifier: build_target_identifiers, git_url: "git@github.com:levibostian/iOS-certs.git")
    gym(scheme: 'Your Circle', configuration: scheme, export_method: 'ad-hoc')

    groups = ['internal-team']

    crashlytics(api_token: 'cda50de306b44395462d411b47a0e306dc1fb6c3',
             build_secret: '0ed3095ca19df1cd604101d7cdced00897719555ddabf3d27ad753c0a2a31cf2',
                   groups: groups,
               notes_path: './fastlane/beta_release_notes.txt',
            notifications: true) # Should this distribution notify your testers via email?
    notification(subtitle: "Finished Building", message: "Released app to beta.")            
    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end  
  
  lane :yourcircle_icons do
    appicon(appicon_image_file: 'fastlane/metadata/icons/dev.png',
            appicon_devices: [:ipad, :iphone], 
            appicon_path: 'Your Circle/Assets.xcassets',
            appicon_name: 'AppIconDev.appiconset')            
    appicon(appicon_image_file: 'fastlane/metadata/icons/beta.png',
            appicon_devices: [:ipad, :iphone], 
            appicon_path: 'Your Circle/Assets.xcassets',
            appicon_name: 'AppIconBeta.appiconset')    
    appicon(appicon_image_file: 'fastlane/metadata/icons/prod.png',
            appicon_devices: [:ipad, :iphone], 
            appicon_path: 'Your Circle/Assets.xcassets',
            appicon_name: 'AppIcon.appiconset')
    appicon(appicon_image_file: 'fastlane/metadata/icons/gems_of_hope.png',
            appicon_devices: [:ipad, :iphone], 
            appicon_path: 'Your Circle/Assets.xcassets',
            appicon_name: 'AppIconGems.appiconset')
    notification(subtitle: "Finished Building", message: "Done generating icons.")
  end  

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.curiosityio.yourcircle.YourCircle" # The bundle identifier of your app
apple_id "levi@curiosityio.com" # Your Apple email address

team_id "6FUGF49KXB" # Developer Portal Team ID
team_name "Curiosity IO, LLC"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-appicon | 0.6.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.8        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fastlane-plugin-appicon   | 0.6.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.1        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.3.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 2.0.7        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.8.0        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.2.1        |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-05-23**
</details>

**Comment by mfurtak** [comment]
Hi @levibostian - thanks for the great write-up. 👍 

Unfortunately, the short answer is no, that's not possible. Fabric requires that you both build and launch an app in order for the system to recognize it as active and allow you to make a distribution. 

Sorry to not have a better answer for you!
