### ISSUE TITLE
weird error message in `sigh` df0b3375de6311413739814792aaef7f

### ISSUE THREAD

**Issue by 343max** [fastlane/fastlane#925]
I just wanted to use sig for the very first time and did run `fastlane beta`.

```
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: 'df0b3375de6311413739814792aaef7f'
The crash report has been stored locally '/tmp/sentry_df0b3375de6311413739814792aaef7f.json'
```

I just created a new Apple ID so I can use fastlane without having to disable two factor authentication. This new user has the role "App Manager". I started the singup for the Apple Developer program, but I stopped just before I had to pay the 99 bucks. Any idea? Any hint how I could investigate this myself?

**Comment by KrauseFx** [comment]
You need to pay the membership fee to use most `fastlane` tools

**Comment by 343max** [comment]
So I need two paid accounts? One "real" and one for fastlane?

**Comment by jcampbell05** [comment]
@343max  No you just need one, which you need to use with Fastlane :) You can't use Fastlane without being a paid member.

**Comment by 343max** [comment]
Sorry for the confusion: I am a paid member, but as far as I know fastlane doesn't support 2fac auth. As turning 2fac off is a bit risky for my taste I thought about a second account for fastlane. I'm not even sure if the error message is in any way related to this, as I only tried to upload something to the AppStore wich usually doesn't require a paid account AFAIK.

**Comment by KrauseFx** [comment]
Sorry for not providing 2 step yet, but you won't get around by creating a second account.

**Comment by 343max** [comment]
Thanks anyway! :smile:
