### ISSUE TITLE
[Feature Request] Add support for the --path parameter to the SwiftLint action

### ISSUE THREAD

**Issue by reidmain** [fastlane/fastlane#9252]
I am looking to use SwiftLint on our CI lanes to prevent developers from landing code that triggers warnings. Unfortunately SwiftLint on CI runs at a higher level directory than when it is run via an Xcode build phase.

If we could pass the `--path` parameter into the SwiftLint action we could configure Fastlane to run SwiftLint in the same way that Xcode does.

**Comment by reidmain** [comment]
I don't think `fastlane env` will make a difference for a feature request like this @fastlane-bot 😜

**Comment by reidmain** [comment]
I apologize it looks like if you provide the `--path` parameter then the `included` section of your configuration file which is not what you want.

It feels like the proper solution to this problem is to either make SwiftLint command run at the same level in both Xcode and Fastlane or update the configuration `included` and `excluded` section to work for both of those possible run locations.

Is there a way to configure a Fastlane action to be run at a specific path?

**Comment by KrauseFx** [comment]
Yeah, add the following to your `Fastfile`

```ruby
Dir.chdir("custom_path/here") do
  swiftlint
end
```

Let me know if that works 👍

**Comment by reidmain** [comment]
@KrauseFx that is actually what I tried and it works for a custom command but not for the Swiftlint action. It seems that if I do
```
Dir.chdir("custom_path/") do
  swiftlint(config_file: ".swiftlint.yml",
              strict: true,
              quiet: true,
              ignore_exit_status: false)
end
```
it still gets run at the root of the directory where the fastlane command is being run from.

I get the error:
```
/Users/reidmain/Development/MyCompant/ios/.swiftlint.yml:File not found.
[19:25:01]: ▸ fatal error: Could not read configuration file at path '/Users/reidmain/Development/MyCompany/ios/.swiftlint.yml': file /tmp/swiftlint-20170407-45056-wip7rd/Source/SwiftLintFramework/Models/Configuration.swift, line 163

```

where `/Users/reidmain/Development/MyCompant/ios/custom_path/.swiftlint.yml` is where the configuration file lives and the command is run via Xcode.

**Comment by KrauseFx** [comment]
Do you think that's an issue of _fastlane_ then, when `/Users/reidmain/Development/MyCompany/ios/.swiftlint.yml` exists?  The error seems to be coming from swiftline, right?

**Comment by reidmain** [comment]
Yes the error does look to be coming from SwiftLint https://github.com/realm/SwiftLint/blob/eef39595f6d5027df9aa7a3b1a241f2bd44e4a14/Source/SwiftLintFramework/Models/Configuration.swift#L161. This does sound like it could be either a Fastlane or SwiftLint action bug.

The SwiftLint configuration file is at `/Users/reidmain/Development/MyCompany/ios/custom_path/.swiftlint.yml`

I am currently using
```
swiftlint(config_file: "custom_path/.swiftlint.yml",
    strict: true,
    quiet: true,
    ignore_exit_status: false)
```
to get this to work on CI. It properly flags all warnings but the shortcoming was that I had to add duplicate entries to the "excluded" section of the SwiftLint configuration file to get it to work properly since the `swiftlint` command is being run in two different locations.

If I change it to
```
Dir.chdir("../custom_path/") do
    swiftlint(config_file: ".swiftlint.yml",
              strict: true,
              quiet: true,
              ignore_exit_status: false)
    end
```
I get the error that I mention above. It seems that the `swiftlint` command is always wherever the `fastlane` command is run from regardless of what the current working directory in the Ruby script is.

**Comment by Mindbowser** [comment]
I am also facing same issue, 

```
       Dir.chdir("..") do
	    sh "pwd"
	    swiftlint(output_file: "reports/swiftlint.txt", ignore_exit_status: false)
	end
```
fastlane changes the directory properly, but when swiftlint tries to find output report path it gets failed, may be it is searching directory in fastlane directory.
