### ISSUE TITLE
[Question] how to set keychain in gym?

### ISSUE THREAD

**Issue by truebit** [fastlane/fastlane#9254]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

according to [xcodebuild source file line338](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/xcodebuild.rb#L338), we could set `keychain` argument for gym, but it is not included in `available_options` list, so I cannot set keychain in gymfile parameters.
Is there any way to set keychain in gym?

**Comment by KrauseFx** [comment]
Mh, interesting, that seems to be missing. Is that something you'd like to work on? Should be rather easy to add and test it for your setup 👍 Check out this doc for some more information on how to get started https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md 😺

**Comment by truebit** [comment]
My mistake. I refered to `xcodebuild` action instead of `gym`. In gym this `keychain` option is not included. I tried to include keychain by using the option of `export_xcargs` in `gym`, but the log shows no such argument in xcodebuild command

**Comment by KrauseFx** [comment]
Ah, nice 👍 It's still something that's probably interesting for many people. To my knowledge, many users use the built-in keychain actions to switch the default keychain on CI boxes.

**Comment by truebit** [comment]
I found that I used wrong parameter, `xcargs` is the one to use instead of `export_xcargs`.
I set the keychain like `xcargs  "OTHER_CODE_SIGN_FLAGS=--keychain=\"/Users/Shared/Library/Keychains/login.keychain\""` in Gymfile, and I could see param in xcodebuild command, but xcodebuild  still failed to find certificate.

using built-in action `unlock_keychain` works.
