### ISSUE TITLE
How can i find all bundle ids related to a particular app group?

### ISSUE THREAD

**Issue by rahul21989** [fastlane/fastlane#9259]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by PetrosIchor** [comment]
Lots of ways. Depends on your needs and project structure.

Off the top of my head, https://github.com/lyndsey-ferguson/get_product_bundle_id/blob/master/README.md

If that doesn't work, learn from existing plugins/actions and create your own! We all love new contributions!
