### ISSUE TITLE
Installation troubles because of existing "scan" executable (from Avast antivirus package) 

### ISSUE THREAD

**Issue by thomers** [fastlane/fastlane#926]
When I'm trying to install using
sudo gem install fastlane --verbose

I get this warning/error message while installing "scan":

/Library/Ruby/Gems/2.0.0/gems/scan-0.3.2/lib/scan/version.rb
scan's executable "scan" conflicts with /usr/local/bin/scan
Overwrite the executable? [yN]  n
ERROR:  Error installing fastlane:
	"scan" from scan conflicts with /usr/local/bin/scan

Apparently, my "Avast Internet Security" already installed /usr/local/bin/scan

How to proceed? Can I somehow change the default name of the "scan" executable used by fastlane?

Thanks, Thomas

**Comment by thomers** [comment]
*bump* Any Idea for a workaround? I'd really like to use fastlane...

**Comment by KrauseFx** [comment]
Not to be taken seriously: I'd uninstall Avast

More serious reply: you can always run all `fastlane` tools using `fastlane run scan` or even better: create a `Fastfile` for your project (using `fastlane init`) and add a lane with your `scan` call from there

**Comment by thomers** [comment]
Thanks, but the problem is that the installation of the "scan" gem fails, so fastlane does not get installed.

**Comment by jcampbell05** [comment]
@thomers  One potential workaround is to install RVM since it puts the gems in a directory where only gems can exist (No apps) :) I find it solves a lot of issues.

**Comment by neonichu** [comment]
You could also use `--bindir` to change the directory where the binstubs get installed in.

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
