### ISSUE TITLE
gym is failing on No profiles for 'sdasdfasdf' were found:  Xcode couldn't find a provisioning profile matching 'asdfasfd'. Code signing is required for product type 'Application' in SDK 'iOS 10.3'

### ISSUE THREAD

**Issue by shzshi** [fastlane/fastlane#9262]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Below is structure of my project 

cert(
		username: 'test@gmail.com',
		team_id: "ABCND",
		force: false
	)
	
#	import_certificates

	# Handles app provisioning
    sigh( 
		adhoc: true,
		force: true, 
		app_identifier: ENV["app_identifier_staging"],
		username: 'test@gmail.com',
		provisioning_name: 'Distribution Profile Name',
		team_id: "ABCND",
		ignore_profiles_with_different_name: true,
		filename: 'test.mobileprovision'
#		output_path: '/Users/jenkins/Library/MobileDevice/Provisioning Profiles/'
	)	
	
	enable_automatic_code_signing(path: "ProjName.xcodeproj", use_automatic_signing: true);
	
	gym(
      toolchain: :swift_3_0,
      workspace: "ProjectName.xcworkspace",
      scheme: "projectName",
      configuration: "Release",
	  clean: true,
    )

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[31m❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'[0m

** ARCHIVE FAILED **

The following build commands failed:

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.33.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.4       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
</details>

**Comment by PetrosIchor** [comment]
As the bot suggested, you should read the code signing guide.  From that error, your signing isn't setup correctly.  Ensure you can build from xcode with the same configuration to troubleshoot

**Comment by shzshi** [comment]
Thank you for reply, but i don't want to you match as I do not have git repo at the moment, i m using cert and sigh with that the certificate gets generated and download and also the profile , but i still keep getting the above error message, so not sure where I am going wrong , I have passed Development Team id as well and do I have to pass codesigning_identity through pdxproj ?

**Comment by PetrosIchor** [comment]
I wouldn't be able to say since I don't know your projects structure.  Before you can run gym, the app needs to be setup with the correct signing. 

Troubleshooting steps:
- Check the logs to see which value is being rejected.  
- Verify that the project builds in xcode manually. If it does, run your fastlane script and compare the diff afterwards.
- Check out the individual tools man pages/docs to learn how to use them to fix the identified problem.

**Comment by shzshi** [comment]
the problem even after running with xcodebuild , i am getting same error 

Check dependencies
No profiles for 'com.test.xyz.dev' were found:  Xcode couldn't find a provisioning profile matching 'com.test.xyz.dev'.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'

just could not understand how to find the exact error

**Comment by shzshi** [comment]
the sigh is pushing the profiles in profiles folder and also root folder, is there a better way to debug exact issue ?

**Comment by shzshi** [comment]
I think it failing because it not picking up CODE_SIGN_IDENTITY , but i have already set this in pbxproj , but then why is it not picking up.

Build settings from command line:
    TOOLCHAINS = swift_3_0

**Comment by shzshi** [comment]
can anyone help please ? is there way i can pass the CODE_SIGN_IDENTITY through gym

**Comment by PetrosIchor** [comment]
Please be patient and polite. People give their free time to work on fastlane and offer support.  

From the looks of your problems, they are not fastlane related.  That said, your questions about iOS project configuration have been posted here and other places like StackOverflow many times.  

I encourage you to do more research on iOS project signing.  Once you can repeatedly build your project manually plan how to automate the process.  Take small pieces to automate with fastlane or other tools and carefully build your pipeline

**Comment by shzshi** [comment]
I am sorry , I did not mean to sound rude, I am just in hurry to fix the problem.  But thank for your help and time, i really appreciate that. I have solved my problem anyway :)
