### ISSUE TITLE
Sigh: "Error resolving conflict between options: 'development' and 'adhoc'" is misleading

### ISSUE THREAD

**Issue by SimeonC** [fastlane/fastlane#9269]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Currently if you define both `:development` and `:adhoc` you get a message that states; `Error resolving conflict between options: 'development' and 'adhoc'`. There was a previous issue here #6642 that outlines a similar use case.

As I understand the code currently you cannot **define** both `:adhoc` and `:development` which is slightly different meaning to what is suggested here in the Sample Output below. From the working of the error message I should be able to do `sigh(development: false, adhoc: true)` as this in my mind is not a conflict of options. I am just intentionally disabling one and enabling the other.

My thinking was that I could happily use the following to make my code DRY:

```ruby
sigh(
       force: true,
       development: lane == :local.to_s,
       adhoc: lane == :staging.to_s,
       username: options[:username]
 )
```
When in reality I have to do this, which is a lot more verbose but less flexible:
```ruby
  case lane
    when :release.to_s
      cert username: options[:username]
      sigh(
          force: true,
          username: options[:username]
      )
  when :staging.to_s
    cert username: options[:username]
    sigh(
        force: true,
        adhoc: true,
        username: options[:username]
    )
  else
    cert(
        development: true,
        username: options[:username]
    )
    sigh(
        force: true,
        development: true,
        username: options[:username]
    )
  end
```

### Sample Output Error

```
[16:59:26]: ------------------
[16:59:26]: --- Step: sigh ---
[16:59:26]: ------------------
[16:59:26]: Error resolving conflict between options: 'development' and 'adhoc'
[16:59:26]: You passed invalid parameters to 'sigh'.
```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                  | Version | Update-Status |
| ----------------------- | ------- | ------------- |
| fastlane-plugin-cordova | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| fastlane-plugin-cordova   | 0.2.0        |
</details>

*generated on:* **2017-05-25**
</details>

**Comment by taquitos** [comment]
So basically because you can only have either `development` or `adhoc` == `true`,  we should be able to define both but just ensure that both are not true or both false. That seems super reasonable.

**Comment by taquitos** [comment]
This isn't super easy for us to change, but I was chatting with @KrauseFx and he mentioned you could use some Ruby magic to use a hash and then converting this from hash to parameter using `shift` and that will accomplish the same thing 👍

**Comment by mgrebenets** [comment]
I believe I may know the magic :)

Here's an example we use in our code:

```ruby
# Helper method to produce slather reports of specified type
def slather_report(scheme, type = :simple, ignore_paths = [])
  # Call shather run function directly for better reusability
  # This way need to provide full Xcode project path
  # Workspace is mandatory with latest versions of slather
  params = {
      workspace: $XCODE_WORKSPACE,
      proj: xcode_project_path,
      scheme: scheme,
      input_format: "profdata",
      ignore: extended_ignore_path_patterns(@ignore_path_patterns + ignore_paths),
      use_bundle_exec: true
  }

  case type
  when :html
    params[:html] = true
  when :cobertura
    params[:cobertura_xml] = true
  when :gutter_json
    params[:gutter_json] = true
  else
    params[:simple_output] = true
  end

  # Slather doesn't support generating multiple reports in one call
  Fastlane::Actions::SlatherAction.run(params)
end
```

So basically you need to compose your parameters (e.g. `params` in my case) and then pass them to an action directly.

This can make your code less branchy and you won't need to call your action multiple times.

**Comment by mgrebenets** [comment]
As @taquitos mentioned, there could be even easier way, e.g. using `shift`.
Not sure how exactly that works, but I definitely would like to find out.
