### ISSUE TITLE
scan doesn't show test failures in the output files (reopened)

### ISSUE THREAD

**Issue by realf** [fastlane/fastlane#9273]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

**The issue https://github.com/fastlane/fastlane/issues/8026 still can be reproduced, so I am reopening it by creating this one. Please read the discussion in https://github.com/fastlane/fastlane/issues/8026. I updated the section Environment here.**

_Below is the original issue description._

There are test failures (tests actually crashed), SCAN lists the failed tests in the console log, however, in the output files and in the final summary, it shows all pass. see logs below:

Complete output when running fastlane, including the stack trace and command used

    You can use: --capture_output as the last commandline argument to get that collected for you

...... too many lines.....

Failing tests:
-[SmartSyncTestSuite testSyncUpLocallyCreated]
-[SmartSyncTestSuite testSyncUpLocallyDeleted]
-[SmartSyncTestSuite testSyncUpLocallyDeletedWithNoOverwrite]
-[SmartSyncTestSuite testSyncUpLocallyUpdated]
-[SmartSyncTestSuite testSyncUpLocallyUpdatedWithGlobalStore]
-[SmartSyncTestSuite testSyncUpLocallyUpdatedWithGlobalStoreNamed]
-[SmartSyncTestSuite testSyncUpLocallyUpdatedWithNoOverwrite]
** TEST FAILED **

The following commands produced analyzer issues:
Analyze Views/RCTMapManager.m
Analyze Modules/RCTRedBox.m
(2 commands with analyzer issues)
[00:05:25]: Exit status: 65
+--------------------+-------+
| Test Results |
+--------------------+-------+
| Number of tests | 622 |
| Number of failures | 0 |
+--------------------+-------+

[00:37:46]: Successfully generated report at '/Users/mhu/dev/SalesforceMobileSDK/iOS/test_output/report.html'
[00:37:57]: Successfully generated report at '/Users/mhu/dev/SalesforceMobileSDK/iOS/test_output/report.junit'

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

_This section is updated._

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.7.4                                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode_8.3.app/Contents/Developer/                |
| Xcode Version               | 8.3                                                            |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.33.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160615 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.6.8        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.8.0        |
| google-api-client         | 0.9.11       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 2.0.2        |
</details>

*generated on:* **2017-05-25**
</details>

**Comment by realf** [comment]
The issue is still not resolved.

**Comment by ljesus** [comment]
This issue is still happening as of today.
