### ISSUE TITLE
download_dsyms - Could not find app with bundle identifier

### ISSUE THREAD

**Issue by brunotrox** [fastlane/fastlane#9275]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### download_dsyms - Could not find app with bundle identifier.
But it seems that `upload_symbols_to_crashlytics` works even after `download_dsyms` error.

#
       [10:16:53]: --- Step: download_dsyms ---
       [10:16:53]: ----------------------------
       [10:16:53]: To not be asked about this value, you can specify it using 'username'
       [10:16:53]: Your Apple ID Username for iTunes Connect: <my_account>
       [10:17:21]: Login to iTunes Connect (<my_account>)
       [10:17:23]: Login successful
       [10:17:23]: Looking for dSYM files for

       [10:17:24]: Could not find app with bundle identifier '' <my_account>

       +------+-------------------------------------+-------------+
       |                     fastlane summary                     |
       +------+-------------------------------------+-------------+
       | Step | Action                              | Time (in s) |
       +------+-------------------------------------+-------------+
       | 1    | Verifying required fastlane version | 0           |
       | 2    | default_platform                    | 0           |
       | 3    | prep                                | 0           |
       | 4    | cocoapods                           | 5           |
       | 5    | gym                                 | 239         |
       | 6    | changelog_from_git_commits          | 0           |
       | 7    | pilot                               | 1536        |
       | 💥   | download_dsyms                      | 30          |
       +------+-------------------------------------+-------------+

       [10:17:24]: fastlane finished with errors

       [!] Could not find app with bundle identifier '' on account <my_account>

### Environment

      Upload to TestFlight.
      pilot(
          wait_processing_interval: 60,
          beta_app_feedback_email: <my_account>,
          distribute_external: true,
          groups: ["Internal Nightly Build Users", "Testlio"]
	)

	download_dsyms                  # Download dSYM files from iTunes Connect
	upload_symbols_to_crashlytics   # Upload them to Crashlytics
	clean_build_artifacts           # Delete the local dSYM files

        <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.12.2                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.13.0"
default_platform :ios



### Builds a project using an xcworkspace
def build_workspace(workspace, scheme, configuration, export_method)
	gym(
		workspace: workspace,
		configuration: configuration,
		scheme: scheme,
		clean: true,
		include_bitcode: true,
		export_method: export_method
	)
end

### Builds a project using an xcodeproj
def build_project(project, scheme, configuration, export_method)
	gym(
		project: project,
		configuration: configuration,
		scheme: scheme,
		clean: true,
		include_bitcode: true,
		export_method: export_method
	)
end

def build_config(filename)
	prep(config: filename)
	dependencies()

	workspace_file = ENV["XCODE_WORKSPACE"]
	scheme = ENV["SCHEME"]
	build_configuration = ENV["BUILD_CONFIGURATION"]
	export_method = ENV["EXPORT_METHOD"]

	# Build the project.
	build_workspace workspace_file, scheme, build_configuration, export_method
end

### Installs dependencies for the project
def dependencies()
	Actions.sh("pod repo update")
	cocoapods
end

### Switch to given branch
def switch_to_branch(branch_name)
	Actions.sh("git fetch && git checkout #{branch_name} && git merge origin/#{branch_name}")
end


platform :ios do

	desc "Prepares and installs depenencies required for the project."
	lane :dependencies do
		# Load fastlane.config and install dependencies.
		prep(config: "fastlane.nightly")
		dependencies()
	end

	desc "Runs the project's unit tests."
	lane :test do
		prep(config: "fastlane.nightly")
		dependencies()

		project_file = ENV["XCODE_PROJECT"]
		workspace_file = ENV["XCODE_WORKSPACE"]
		scheme = ENV["SCHEME"]
		configuration = ENV["TEST_CONFIGURATION"]

		# Run the tests.
		if workspace_file == nil
			puts "xcworkspace not found; testing with .xcodeproj"
			scan(
				project: project_file,
				scheme: scheme,
				configuration: configuration,
				skip_slack: true
			)
		else
			scan(
				workspace: workspace_file,
				scheme: scheme,
				configuration: configuration,
				skip_slack: true
			)
		end
	end

	desc "Builds and distributes an internal build to TestFlight."
	desc "This process tags the current build number on git, then increments the build number before building the IPA."
	desc "The IPA file is distributed via TestFlight."
	lane :nightly do
		build_config("fastlane.nightly")

		version_bump_branch = "develop"
		version_bump_message = "Bumped internal build version"

		# All tags will use the builds/internal folder.
		tag_pattern="builds/internal/"

		# Get commits between builds/internal/# and HEAD.
		changelog = changelog_from_git_commits(
			tag_match_pattern: tag_pattern,
			pretty: '- %s'
		)
		changelog = changelog.gsub("- " + version_bump_message, "")

		# Upload to TestFlight.
		pilot(
			changelog: changelog,
			wait_processing_interval: 60,
			beta_app_feedback_email: "ios@backstage.com",
			distribute_external: true,
			groups: ["Internal Nightly Build Users", "Testlio"]
		)

		download_dsyms                  # Download dSYM files from iTunes Connect
		upload_symbols_to_crashlytics   # Upload them to Crashlytics
		clean_build_artifacts           # Delete the local dSYM files
	end
	
	lane :alpha do
		build_config("fastlane.alpha")

		# Upload to TestFlight.
		pilot(wait_processing_interval: 60,
			beta_app_feedback_email: "ios@backstage.com")
	end

	lane :beta do
		build_config("fastlane.beta")

		# Upload to TestFlight.
		pilot(wait_processing_interval: 60,
			beta_app_feedback_email: "customers@backstage.com")
	end
	
end


lane :status do
	Actions.sh('pod outdated')
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
for_platform :ios do
	for_lane :testflightinternal do
		team_id "8VT6T5KN7F"
		team_name "Backstage LLC"
		apple_id "ios@backstage.com"
		app_identifier "com.backstage.casting-internal-testflight"
	end
end

# Save password in keychain or set it as environment variable `FASTLANE_PASSWORD`.
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 2.1.0        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| google-api-client         | 0.9.28       |
| faraday_middleware        | 0.11.0.1     |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.0        |
| bundler                   | 1.15.0       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>

*generated on:* **2017-05-25**
</details>

**Comment by taquitos** [comment]
hey @brunotrox it looks like your AppFile is only passing the needed info into your lane `:testflightinternal` and you are calling `:nightly` you could either duplicate that `for_lane` or you could set up some globals for it 👍 
Also, we should probably catch this issue in the `download_dsyms` action

**Comment by brunotrox** [comment]
@taquitos, Thank you so much!
