### ISSUE TITLE
s3.rb - Over the air download does not work if the plist file contains a whitespace

### ISSUE THREAD

**Issue by katunch** [fastlane/fastlane#928]
**Whats happening**
If you have a project with a whitespace in its name and publish the ipa and plist file to S3 using `s3.rb`, the over the air download will not work.

**Desired Behaviour Option 1**
Ability to specifiy the plist file name in the `Fastfile`. At the moment you can only specify the `:plist_template_path`but not the `:plist_file_name` similar to the html file or the version file.

**Desired Behaviour Option 2**
Replace 
```ruby
plist_file_name = "#{url_part}#{title}.plist"
```
With:
```ruby
plist_file_name = "#{url_part}#{title.delete(" ")}.plist"
```

**Conclusion**
I defenetly prefer Option 1.

**Comment by KrauseFx** [comment]
Hey, thanks for letting me know. I just pushed a hotfix. Feel free to submit a pull request for adding a custom name for the plist file, should be fairly easy :+1:
