### ISSUE TITLE
Running non default actions in a lane like deliver.download_metata

### ISSUE THREAD

**Issue by lakamsani** [fastlane/fastlane#9289]
Is it possible to run a non-default action of deliver like download_metadata or download_screenshots in a lane like this:

```
      deliver.download_metadata(
              app_identifier: "a.b.c",
              metadata_path: "#/metadata"
        )
```

**Comment by taquitos** [comment]
@lakamsani unfortunately no. We don't have an action for `download_metadata`, it's just a command. You could build an action that calls the same code, and then call that.

**Comment by KrauseFx** [comment]
Alternatively you can add the following to your `Fastfile`
```ruby
lane :beta do
  sh "fastlane deliver download_metadata --app_identifier 'yolo' --metadata_path 'yolopath'"
end
```

**Comment by lakamsani** [comment]
Tried that but fails due to yes/no prompt. Could use a -force option
(enhancement). Ruby isn't my "first" language but will try the action path
using the source code for the command.

On May 25, 2017 6:57 PM, "Felix Krause" <notifications@github.com> wrote:

Alternatively you can add the following to your Fastfile

lane :beta do
  sh "fastlane deliver download_metadata --app_identifier 'yolo'
--metadata_path 'yolopath'"end

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fastlane/fastlane/issues/9289#issuecomment-304170501>,
or mute the thread

**Comment by KrauseFx** [comment]
Try
```ruby
lane :beta do
  ENV["DELIVER_FORCE_OVERWRITE"] = "1"
  sh "fastlane deliver download_metadata --app_identifier 'yolo' --metadata_path 'yolopath'"
end
```

**Comment by lakamsani** [comment]
that worked. thanks.
