### ISSUE TITLE
.mobileprovision

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#929]
I was puzzled today by the fact that I was not able to send a test flight build after changing iCloud configuration for the app. I could be wrong but I think removing .mobileprovision file helped me... I am curious, what are the pros of having provisioning in repo?

**Comment by KrauseFx** [comment]
You can always use `sigh` to download the latest provisioning profile. To re-generate the provisioning profile run `sigh --force`. As of now it is recommended to use [match](https://github.com/fastlane/match) to deal with code signing :+1:
