### ISSUE TITLE
Avoid uploading screenshots.html when running fastlane supply

### ISSUE THREAD

**Issue by rocboronat** [fastlane/fastlane#9292]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After doing lots of screenshots on lots of terminals with lots of locales, we tried to deploy the screenshots using `fastlane supply`. After 15 minutes uploading things, it crashes cos it doesn't know what to do with `screenshots.html`, the report that fastlane screengrab generates to report the screenshots taken. The key point is that supply could be smart enough to ignore sending that file to Google Play.

The error launched by fastlane:
`/Users/roc/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.28/lib/google/apis/core/http_command.rb:211:in `check_status': [!] unsupportedListingLanguage: Listing language screenshots.html is not supported. (Google::Apis::ClientError)`

Thanks for your work! :+1:

**Comment by joshdholtz** [comment]
@rocboronat Thanks for the report! Do you have a bigger stacktrace that you can provide so I can trace down where in the fastlane code base this is happening from? 😊

**Comment by kdenney** [comment]
@joshdholtz This is happening to me, too. Here's the full stack trace from my error (attached). Please let me know if anything would be helpful!

[fastlaneStackTrace.txt](https://github.com/fastlane/fastlane/files/1032328/fastlaneStackTrace.txt)

**Comment by joshdholtz** [comment]
@kdenney Perf 👌 I'm out of town today but I will take a look at this for you all when I get back home tonight ✊

**Comment by mfurtak** [comment]
This is related to: https://github.com/fastlane/fastlane/pull/9213

**Comment by joshdholtz** [comment]
@mfurtak Ah, thanks! Is that where the bug was introduced?

**Comment by mfurtak** [comment]
The HTML report was introduced for the first time in that PR, so I think it's just an oversight of where it is being placed... and how that winds up interacting with _supply_

**Comment by rocboronat** [comment]
Well, actually, Supply could just ignore files not related with the Google's API :·)

**Comment by kd8ssq** [comment]
I'm also experiencing the same issue.  I can confirm that manually deleting the screehshot.html file and running supply works as it should.  I believe either relocating the location of the screenshot file or excluding it from supply trying to upload would be valid fixes.

**Comment by joshdholtz** [comment]
@kd8ssq @rocboronat This fixed was just merged into master in #9297 and should be included in next fastlane release 💪

**Comment by rocboronat** [comment]
Thanks @joshdholtz ! An issue with a low priority like this, fixed in four days. Congrats! And thanks for your work :·)
