### ISSUE TITLE
Scan's custom_report_file_name outputs html instead of xml

### ISSUE THREAD

**Issue by lyndsey-ferguson** [fastlane/fastlane#9293]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Previously, `scan` would output the xml output of the report.junit to the given `custom_report_file_name`. Now it only outputs the html output to that file if the default `output_types` is used. 

I would like for this to be fixed so that either we can specify the 'junit' filename, or `scan` to generate an error if you're using this combination of multiple output_types and a custom filename if it is too complicated.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

N/A

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.0                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/README.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage
require_relative 'helper/shared_values'

default_platform :ios

# import the Ruby files from the lanes directory into the current context
# which is the current instance of Fastfile instance.
Dir[File.expand_path('./lanes/**/*.rb', File.dirname(__FILE__))].each do |fastlane_file|
  import fastlane_file
end

unless Helper.is_test?
  SharedValues::GIT_BRANCH = :GIT_BRANCH
  SharedValues::GIT_URL = :GIT_URL
  SharedValues::UNSIGNED_IPA_OUTPUT_PATH = :UNSIGNED_IPA_OUTPUT_PATH
end

platform :ios do
  before_all do |lane, options|
    post_to_github('pending') if is_test_job?(lane)
    setup_our_lane_context
    cleanup_environment(lane)
    prepare_build_environment(lane)
    set_slave_launchagents if is_ci?
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '60'
    ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '30'
    ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = '5'
  end

  # ----------------------------------------------------------------------------
  #
  desc 'An empty lane that developers can use to set up their environment'
  lane :setup_env do |options|
    # Everything that before_all does (unless coded otherwise)
    is_good = options.fetch(:mdm, 'no mdm') == 'good'
    good_safe_setup(is_good: is_good)
  end

  after_all do |lane|
    final_cleanup(lane)
  end

  error do |lane, _exception|
    post_to_github('error') if is_test_job?(lane)
    final_cleanup(lane)
  end
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.35.0  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                                  | Version | Update-Status |
| --------------------------------------- | ------- | ------------- |
| fastlane-plugin-goodify_info_plist      | 0.2.5   | ✅ Up-To-Date  |
| fastlane-plugin-certificate_expirydate  | 0.1.4   | ✅ Up-To-Date  |
| fastlane-plugin-profile_expiration_info | 0.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-github_job_status       | 0.2.1   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                     | Version      |
| --------------------------------------- | ------------ |
| did_you_mean                            | 1.0.0        |
| slack-notifier                          | 1.5.1        |
| CFPropertyList                          | 2.3.5        |
| claide                                  | 1.0.1        |
| colored2                                | 3.1.2        |
| nanaimo                                 | 0.2.3        |
| xcodeproj                               | 1.4.4        |
| plist                                   | 3.3.0        |
| multipart-post                          | 2.0.0        |
| word_wrap                               | 1.0.0        |
| tty-screen                              | 0.5.0        |
| babosa                                  | 1.0.2        |
| colored                                 | 1.2          |
| highline                                | 1.7.8        |
| commander-fastlane                      | 4.4.4        |
| excon                                   | 0.55.0       |
| unf_ext                                 | 0.0.7.4      |
| unf                                     | 0.1.4        |
| domain_name                             | 0.5.20170404 |
| http-cookie                             | 1.0.3        |
| faraday-cookie_jar                      | 0.0.6        |
| fastimage                               | 2.1.0        |
| gh_inspector                            | 1.0.3        |
| uber                                    | 0.0.15       |
| representable                           | 2.3.0        |
| retriable                               | 2.1.0        |
| hurley                                  | 0.2          |
| little-plugger                          | 1.1.4        |
| multi_json                              | 1.12.1       |
| logging                                 | 2.2.2        |
| jwt                                     | 1.5.6        |
| memoist                                 | 0.15.0       |
| os                                      | 0.9.6        |
| signet                                  | 0.7.3        |
| googleauth                              | 0.5.1        |
| httpclient                              | 2.8.3        |
| google-api-client                       | 0.9.28       |
| mini_magick                             | 4.5.1        |
| multi_xml                               | 0.6.0        |
| rubyzip                                 | 1.2.1        |
| security                                | 0.1.3        |
| xcpretty-travis-formatter               | 0.0.4        |
| dotenv                                  | 2.2.1        |
| bundler                                 | 1.15.0       |
| faraday_middleware                      | 0.11.0.1     |
| json                                    | 2.1.0        |
| io-console                              | 0.4.5        |
| faraday                                 | 0.12.1       |
| terminal-table                          | 1.8.0        |
| unicode-display_width                   | 1.2.1        |
| temple                                  | 0.7.7        |
| tilt                                    | 2.0.7        |
| slim                                    | 3.0.7        |
| fastlane-plugin-goodify_info_plist      | 0.2.5        |
| fastlane-plugin-check_good_version      | 0.1.7        |
| fastlane-plugin-certificate_expirydate  | 0.1.4        |
| fastlane-plugin-profile_expiration_info | 0.1.0        |
| fastlane-plugin-github_job_status       | 0.2.1        |
| netrc                                   | 0.7.8        |
| rest-client                             | 1.8.0        |
| mime-types                              | 2.99.3       |
</details>

*generated on:* **2017-05-26**
</details>

**Comment by KrauseFx** [comment]
Hey @lyndsey-ferguson, would you mind submitting a PR for this change? 👍
