### ISSUE TITLE
match invoke in Fastfile used arguments in Matchfile instead of match method arguments

### ISSUE THREAD

**Issue by truebit** [fastlane/fastlane#9298]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a Matchfile configured for development usage, such like 
```
git_url "ssh://git@foobar.git"
type "development"
app_identifier "com.foobar.dev"
team_id "FOO"
username "foobar@example.com"
```
Then in Fastfile I created a lane for enterprise cert such like `match(type: "enterprise", app_identifier: "com.foobar.enterprise", team_id: "BAR")`

in my understanding, match should use those arguments in Fastfile to override the default arguments in Matchfile. but it is still use the arguments in Matchfile, except the `type` argument

### Environment

use Fastlane 2.35.1

**Comment by joshdholtz** [comment]
@truebit Your understanding is correct but everything seems to be working as expected for me. I created a really simple fastlane test project with the following `Matchfile` and `Fastfile` and the output shows exactly how you thought `match` to work 😊 

 - The `git_url` and `username` were taken from the `Matchfile`
- The `type`, `app_identifier`, and `team_id` were taken from the `Fastfile`

### Matchfile
```rb
git_url "ssh://git@foobar.git"
type "development"
app_identifier "com.foobar.dev"
team_id "FOO"
username "foobar@example.com"

```

### Fastfile
```rb
lane :test do
  match(type: "enterprise", app_identifier: "com.foobar.enterprise", team_id: "BAR")
end

```

### Output
```sh
[22:22:19]: Successfully loaded '/Users/josh/Projects/fastlane_test/fastlane/Matchfile' 📄

+----------------------+----------------------+
| Detected Values from './fastlane/Matchfile' |
+----------------------+----------------------+
| git_url              | ssh://git@foobar.git |
| username             | foobar@example.com   |
+----------------------+----------------------+


+-----------------------+-----------------------+
|           Summary for match 2.36.0            |
+-----------------------+-----------------------+
| type                  | enterprise            |
| app_identifier        | com.foobar.enterprise |
| team_id               | BAR                   |
| git_url               | ssh://git@foobar.git  |
| username              | foobar@example.com    |
| git_branch            | master                |
| keychain_name         | login.keychain        |
| readonly              | false                 |
| verbose               | false                 |
| force                 | false                 |
| skip_confirmation     | false                 |
| shallow_clone         | false                 |
| clone_branch_directly | false                 |
| force_for_new_devices | false                 |
| skip_docs             | false                 |
| platform              | ios                   |
+-----------------------+-----------------------+
```

**Comment by truebit** [comment]
The match file is like below:

```ruby
for_platform :ios do
  git_url "ssh://git@gitlab.changbaops.com:10212/iOS/certificates.git"
  team_id "FOOBAR"
  app_identifier [ "com.foo.bar", "com.foo.bar.NotificationServiceExtension" ]
  git_branch "foobar"
  #readonly true
  for_lane :development do
    type "development"
  end
  for_lane :enterprise do
    type "enterprise"
    git_branch "enterprise"
    app_identifier [ "com.foo.bar.enterprise", "com.foo.bar.enterprise.EasyLiveNotificationServiceExtension" ]
    team_id "FOOBAR" # Developer Portal Team ID
  end
  for_lane :release do
    type "appstore"
  end
end
```

**Comment by KrauseFx** [comment]
@truebit: Could you try renaming the `.fastlane` folder to `fastlane` and see if that fixes the problem? To debug, you could add a 
```ruby
puts "hi from Matchfile"
```
at the top of the `Matchfile` outside the `for_platform` block.

**Comment by truebit** [comment]
It's not the dir name issue. As the log indicated that it located Matchfile.
After removing the `for_platform :ios do ... end` pair statements, it seems to work.

**Comment by KrauseFx** [comment]
I just noticed you never shared your `Fastfile`, do you have a `platform :ios` block there?

**Comment by truebit** [comment]
Yes, I have the block in Fastfile.
`fastlane list` shows there is an 'ios' block in Fastfile

Sent from my mobile device.

**Comment by truebit** [comment]
This bug still exists in 2.58.0

**Comment by KrauseFx** [comment]
It seems like this is the only GH issue mentioning this issue, so I'm pretty certain that this is a configuration issue. If you share your complete configuration, meaning all config files, the folder names and locations, maybe even screenshots, we can try to reproduce 👍

**Comment by simonferry** [comment]
wow, that is something fantastic)
