### ISSUE TITLE
What happened to PR from issue #6884 (title_below_image option for Frameit)

### ISSUE THREAD

**Issue by patreu22** [fastlane/fastlane#9300]
Hey guys,  
I was looking for a solution to put the title under the screenshot as it is usual for many Screenshot Designs.  
I even found that pull request: https://github.com/fastlane/fastlane/pull/6884/  
  
Any idea what happened to that one? Is anybody on a feature like that or implemented it on another way? It would be really nice to use that feature, but I'm a total Ruby noob, so maybe somebody has an idea?

**Comment by joshdholtz** [comment]
@patreu22 It needed some updates and tests from the original author but never received them (https://github.com/fastlane/fastlane/pull/6884#issuecomment-274878117) I can take a look at to possibly reviving this for you as it seemed like this PR was going to be merged 👌

**Comment by patreu22** [comment]
That's great, @joshdholtz , thank you very much! :) I'm sure a lot of people will benefit from this feature.

**Comment by patreu22** [comment]
Did you already have a chance to take a look on it, @joshdholtz ? :)

**Comment by joshdholtz** [comment]
@patreu22 Not yet 😔 Too many other things came up! Still on my list, tho
