### ISSUE TITLE
Automate to check if New Certificates Were Created

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#9305]
So far, I have been manually running Lane that fetches certificates. 
But is there way to check if new certificates were created ?

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by joshdholtz** [comment]
@tringManoj I don't think we have an action to check if there are new certs right now. Curious what would be the benefit of checking over fetching? 😇

**Comment by tringManoj** [comment]
Hey @joshdholtz ... Think you have a bunch of targets and each time u end up creating 20+ certificates whenever needed. So when u have "auto install certificates" LANE added to your Build Automation LANE. Each time you call Build LANE to create IPA. This will download and install certificates for all 20+ targets weather or not you've created new certificates. This will be an overhead in this case. You got my point bro?

**Comment by joshdholtz** [comment]
@tringManoj Are you talking about "certificates" or "provisioning profiles"? It sounds like you _may_ be talking about provisioning profiles here 🤔

**Comment by tringManoj** [comment]
You're correct. It's about provisioning profiles. Sorry for the confusion.

**Comment by joshdholtz** [comment]
@tringManoj Got it, that makes more sense 👌  Can look into the feasibility of this for you
