### ISSUE TITLE
deliver download_metadata requires to force overwrite even if folder didn't exist

### ISSUE THREAD

**Issue by lacostej** [fastlane/fastlane#9306]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

````
rm -r fastlane/metadata/
fastlane deliver download_metadata --metadata_path "fastlane/metadata" 
[...]
[09:27:55]: ▸ [09:27:55]: Do you want to overwrite existing metadata on path '/Users/lacostej/Code/WWTK/12+/fastlane/metadata'?
````

This is caused by
````
DetectValues.ensure_folders_created
DetectValues.run!
Runner.new
CommandsGenerator command :download_metadata
````

**Comment by joshdholtz** [comment]
@lacostej So are you looking for a `force` flag of some sort on `download_metadata` then? 😇

**Comment by joshdholtz** [comment]
@ohayon Thanks for the reference 😉

**Comment by lacostej** [comment]
@joshdholtz I would like ensure_folders_created to not be created before we check if we can overwrite them...

**Comment by joshdholtz** [comment]
@lacostej Makes sense! Didn't know you had PR started for this but @ohayon linked me to it so I got it after that 😇

**Comment by ohayon** [comment]
Hey @joshdholtz and @lacostej cool if I close this as it looks like its been resolved? Let me know if thats an issue! 🚀
