### ISSUE TITLE
clean_build_artifacts not removing from default directory

### ISSUE THREAD

**Issue by joshrlesch** [fastlane/fastlane#931]
Im trying to use the `clean_build_artifacts` action but its not removing the files. I am using the default output directory so I would think it would just look there for files.

I am trying to run this **before** the `gym` command if that has anything to do with it.

Has anybody seen this before?

**Comment by KrauseFx** [comment]
What do you expect to be deleted which doesn't get deleted?

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up. :+1:
