### ISSUE TITLE
[match] use default keychain?

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#9311]
### New Issue Checklist

- [ x ] Updated fastlane to the latest version
- [ x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Is that possible for match to use default keychain rather then Login one? i.e. if i have created a keychain and set it to be default to use that on rather then specifying exactly ? 

Use case is TravisCI which has an issue with default keychain and using the same script for local machine setup. Perhaps there is another workaround i couldn't find?

Thanks.

**Comment by shwetdream11** [comment]
@romk1n you should check this out - https://medium.com/@shwetsolanki/ios-fastlane-travisci-92a051dd07bf 

I am sure it will solve your concern

**Comment by shwetsolanki** [comment]
@romk1n you should check this out - https://medium.com/@shwetsolanki/ios-fastlane-travisci-92a051dd07bf

I am sure it will solve your concern

**Comment by romk1n** [comment]
my question is really about not passing the arguments to `gym` for default keychain, in the example on the article the keychain name and password is used. however i want the same configuration work on any machine not just travis.

**Comment by shwetsolanki** [comment]
@romk1n it will work on any machine, you just need to keep Keychain name and password part of the environment file. 
https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#environment-variables

**Comment by romk1n** [comment]
sorry i think i made myself not quit clear, i have to specify the keychain in `match` command the `gym` will work with the default one. i don't see how environment variables will help me, cause i won't be able to know keychain name or password for all the developers.

So it would be good if i have run something like this:

```
create_keychain(
      name:ENV["KEYCHAIN_NAME"], 
      password: ENV["KEYCHAIN_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
      verbose: true
    )
```
only on the build machine i won't need to do 

```
match(
     git_branch: match_branch,
     app_identifier: app_identifier, 
     type: "adhoc",
     keychain_name: ENV["KEYCHAIN_NAME"],
     keychain_password: ENV["KEYCHAIN_PASSWORD"],
     readonly: true)
```

but just do 
```
match(
     git_branch: match_branch,
     app_identifier: app_identifier, 
     type: "adhoc",
     readonly: true)
```

that way if i am running on the CI, my script can just do the following:

```sh
fastlane travis_create_keychain
fastlane build_ipa
fastlane travis_delete_keychain 
```

and it will also work the same way on any developer machine by simply doing
```
fastlane build_ipa
```

because there is no need for the workaround. Let me know if that's more clear?
