### ISSUE TITLE
Fastlane/Match and multiple teams documentation

### ISSUE THREAD

**Issue by RustyKnight** [fastlane/fastlane#9312]
I'm looking for documentation on how to setup and manage multiple teams using Match.

I understand I'm suppose to use different branches, but I've not seen any documentation/walkthroughs on how one might actually go about getting it setup.

I currently have a repo setup for a single team and would like to change it to support multiple teams if possible - otherwise simple starting over

**Comment by joshdholtz** [comment]
@RustyKnight You can do this by making use of `dotenv` - https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md#environment-variables

You can put multiple `.env` files in the same directory as your `Fastfile`. Example:

## Fastlane/.env.team1
```sh
FASTLANE_TEAM_ID=<one of your team ids>
```

## Fastlane/.env.team2
```sh
FASTLANE_TEAM_ID=<another of your team ids>
```

## Running
Whatever is passed in to the `--env` argument will load the corresponding `.env.<envarg>` file
**NOTE:** The `.env` file will **always** get loaded but `.env.<engarg>` will only get loaded based on the `--env` param passed in.

```sh
$: fastlane build --env team1
```

```sh
$: fastlane build --env team2
```

Somewhat related link using - https://github.com/fastlane/fastlane/blob/master/fastlane/docs/FAQs.md#multiple-targets-of-the-same-underlying-app

An example gist of mine - https://gist.github.com/joshdholtz/aa902e7ae28c1c0bea2a

**Comment by joshdholtz** [comment]
@RustyKnight  I _may_ have misunderstood your issue 😇 

Have you looked at this? https://github.com/fastlane/fastlane/tree/master/match#important-use-one-git-branch-per-team

You can just use pass your current branch name for your first time and pass a new branch in for you second team - `match` should create that new branch for you in your git repo. Let me know if you have any other issues/questions and we can reopen this but I'm going to close this for now 👌

**Comment by RustyKnight** [comment]
I "think" I've got it work, still testing

**Comment by joshdholtz** [comment]
@RustyKnight Awesome! Have fun fastlaning 💪 🚀
