### ISSUE TITLE
Gym project path not working?

### ISSUE THREAD

**Issue by eddnav** [fastlane/fastlane#9315]
🔑
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I'm trying to create a setup for Fastlane on a React Native project, as such I would like to have my `fastfile` out of the native project folders, but setting up the path to the project is not working, some suggest adding an `ENV["GYM_PROJECT"]` declaration at the top of my `fastfile`, and that works, but what about Android? what would be the equivalent? and why is the `gym` config for `project` not doing the same?

```
MNAV:proj eddnav$ fastlane beta
[08:19:38]: -------------------------------------------------
[08:19:38]: --- Step: Verifying required fastlane version ---
[08:19:38]: -------------------------------------------------
[08:19:38]: Your fastlane version 2.35.1 matches the minimum requirement of 1.109.0  ✅
[08:19:38]: ------------------------------
[08:19:38]: --- Step: default_platform ---
[08:19:38]: ------------------------------
[08:19:38]: Driving the lane 'beta' 🚀
[08:19:38]: ----------------------------------------
[08:19:38]: --- Step: changelog_from_git_commits ---
[08:19:38]: ----------------------------------------
[08:19:38]: Collecting Git commits between 0.3.8-85-80 and HEAD

....

[08:19:38]: -----------------
[08:19:38]: --- Step: gym ---
[08:19:38]: -----------------
[08:19:38]: Couldn't automatically detect the project file, please provide a
path: 
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.2                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.2 (16C67)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "a7ec82ce-be62-4838-b183-bb24c9599e44"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do |options|

  changelog = changelog_from_git_commits(
    merge_commit_filtering: 'exclude_merges' # Optional, lets you filter out merge commits
  )

  # build your iOS app
  gym(
    scheme: "proj-beta",
    export_method: "ad-hoc"
  )

  # upload to HockeyApp
  hockey(
    project: "ios/proj.xcodeproj",
    workspace: "ios/proj.xcodeproj",
    api_token: "-",
    notes: "#{options[:v]}\n====\nStaging\n#{changelog}",
    notes_type: "1",
    notify: "0",
    status: "2"
  )
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

# app_identifier "com.your.app" # the bundle identifier of your app
# apple_id "apple@fastlane.tools" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-30**
</details>

**Comment by joshdholtz** [comment]
@eddnav By just quickly looking at it, it looks like you are setting `project` and `workspace` on the `hockey` actions instead of the `gym` action. These are not valid arguments on `hockey` (you can see if you try running `fastlane action hockey`).

If you try moving `project` **OR** `workspace` to `gym` (you should only need one), it _should_ work for you. Lemme know 🚀

**Comment by eddnav** [comment]
@joshdholtz I see, that's quite stupid on my part, I tried tit and it was effectively that. Will be closing this, thanks for the help.

**Comment by joshdholtz** [comment]
@eddnav Not a problem! Happy fastlaning 💪 🚀
