### ISSUE TITLE
Could not find fastlane in current directory - when folder is not called fastlane

### ISSUE THREAD

**Issue by arjpaiva** [fastlane/fastlane#9316]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have multiple projects so I need to name the folders based on the project name but
when I try to run a lane from the Fastfile inside a project folder that is not called "fastlane" I  get the following message:
Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up? (y/n)

This is my lane configuration:
```
desc "Upload metadata only to the App Store"
  lane :upload_metadata do
    deliver(
      skip_screenshots: true, #Don't upload the screenshots
      skip_binary_upload: true, #Skip uploading an ipa to iTunes Connect
      force: true #Skip the HTML report file verification
    )
  end
```
If I run fastlane command directly it works fine.

```
fastlane deliver run --skip_binary_upload --skip_screenshots
```

Thank you.

**Comment by mfurtak** [comment]
Hi @arjpaiva 👋 

You should be able to have project directories named whatever you would like. The important part is that each project directory has a folder named `fastlane` that contains the _fastlane_ configuration files in it (e.g. `Fastfile`)

See: https://docs.fastlane.tools/getting-started/ios/setup/#setting-up-fastlane

**Comment by arjpaiva** [comment]
Thanks @mfurtak 
Any reason why running fastlane directly on the command line doesn't require the folder to be called fastlane while using Fastfile does?

Thank you.

**Comment by mfurtak** [comment]
I think this is a result of history from fastlane's early development. @KrauseFx could probably say more :+1:

I'll close this issue for now!
