### ISSUE TITLE
Matchfile not being read

### ISSUE THREAD

**Issue by lferro9000** [fastlane/fastlane#9317]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running:

```
fastlane ios alpha
```
The content of file 'Matchfile', which is present on the same folder as 'Fastfile' isn't read and present on the match () blocks.

This was working as of last week. Trying to run an older version of fastlane didn't sorted, which means that it may be bound to a library used by fastlane that was updated at the some time this compilations.

24-May-2017 09:44 -> Compilation successful
```
[09:49:18]: fastlane.tools finished successfully 🎉

#######################################################################
# fastlane 2.33.0 is available. You are on 2.30.2.
# You should use the latest version.
# Please update using `sudo gem install fastlane`.
#######################################################################
```

30-May-2017 12:43 -> Compilation failure due to unspecified git_url in Match
```
[14:51:13]: -------------------------------------------------
[14:51:13]: --- Step: Verifying required fastlane version ---
[14:51:13]: -------------------------------------------------
[14:51:13]: Your fastlane version 2.35.1 matches the minimum requirement of 1.111.0  ✅
[14:51:13]: ------------------------------
[14:51:13]: --- Step: default_platform ---
[14:51:13]: ------------------------------
[14:51:13]: Driving the lane 'ios alpha' 🚀
[14:51:13]: -------------------
[14:51:13]: --- Step: match ---
[14:51:13]: -------------------

+-----------------------+-----------------------------------+
|                 Summary for match 2.35.1                  |
+-----------------------+-----------------------------------+
| type                  | adhoc                             |
| team_name             | MyTeam                       |
| app_identifier        | com.example.MyBundle-alpha |
| shallow_clone         | false                             |
| force                 | true                              |
| force_for_new_devices | true                              |
| git_branch            | master                            |
| keychain_name         | login.keychain                    |
| readonly              | false                             |
| verbose               | false                             |
| skip_confirmation     | false                             |
| clone_branch_directly | false                             |
| skip_docs             | false                             |
| platform              | ios                               |
+-----------------------+-----------------------------------+

[14:51:13]: To not be asked about this value, you can specify it using 'git_url'
[14:51:13]: URL to the git repo containing all the certificates: ^C+------------------+-----------+
|         Lane Context         |
+------------------+-----------+
| DEFAULT_PLATFORM | ios       |
| PLATFORM_NAME    | ios       |
| LANE_NAME        | ios alpha |
+------------------+-----------+

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | match                               | 31          |
+------+-------------------------------------+-------------+

[14:51:44]: fastlane finished with errors
```

One of the things that i noticed was that when calling 'fastlane env' there is an error:

```
Looking for related GitHub issues on fastlane/fastlane...

➡️  invalid byte sequence in UTF-8
    https://github.com/fastlane/fastlane/issues/7850 [closed] 11 💬
    7 weeks ago

➡️  Invalid byte sequence with invalid strings file
    https://github.com/fastlane/fastlane/issues/7661 [closed] 8 💬
    03 Mar 2017

➡️  invalid byte sequence in US-ASCII (ArgumentError)
    https://github.com/fastlane/fastlane/issues/227 [closed] 20 💬
    13 Dec 2016

and 21 more at: https://github.com/fastlane/fastlane/search?q=invalid%20byte%20sequence%20in%20US-ASCII&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:730:in `gsub': [!] invalid byte sequence in US-ASCII (ArgumentError)
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:730:in `format_statement'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:621:in `say'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:261:in `ask'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/highline-1.7.8/lib/highline.rb:227:in `agree'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:109:in `confirm'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/environment_printer.rb:12:in `output'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:233:in `block (2 levels) in run'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:38:in `run!'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/jenkins/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.35.1/bin/fastlane:20:in `<top (required)>'
	from /Users/jenkins/.rbenv/versions/2.3.3/bin/fastlane:23:in `load'
	from /Users/jenkins/.rbenv/versions/2.3.3/bin/fastlane:23:in `<main>'

```
And also, from the configuration files listed in the environment, the Matchfile isn't on the list (it was previously).

For completness, the content of the Matchfile is:

```
git_url "git@match:companyname/match-certificates.git"
git_branch "TeamBranch"

# For all available options run `match --help`
# Remove the # in the beginning of the line to enable the other options
```

Something very wrong happened between 24th May and 30th May to make this error resurface, as something very similar was reported on issue https://github.com/fastlane/fastlane/issues/6499.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Already specified above.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.0                          |
| Installation Source         | ~/.rbenv/versions/2.3.3/bin/fastlane        |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.3/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

#select xcode version
#xcversion(version: "8.1") # Selects Xcode 8.1.0

#xcode_select "/Applications/Xcode.app"

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.111.0"

default_platform :ios

platform :ios do
  before_all do
    #cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Create a new Alpha Build"
  desc "This will also make sure the profile is up to date"
  lane :alpha do
    match(
      type: 'adhoc',
      team_id: ENV['sigh_com.example.MyBundle-alpha_development_team-id'],
      team_name: 'MyTeam',
      app_identifier: 'com.example.MyBundle-alpha',
      shallow_clone: false,
      force: true,
      force_for_new_devices: true
    )

    gym(
      scheme: 'MySchema',
      export_method: 'ad-hoc',
      configuration: 'Alpha',
      output_directory: './build',
      output_name: 'MyBundle-Alpha.ipa',
      include_symbols:true,
      include_bitcode:false,
      silent:true
    )
      
    # pilot
    hockey(
      api_token: '0000token0000',
      public_identifier: '1111token1111',
      ipa: 'build/MyBundle-Alpha.ipa',
      notify: '1',
      status: '2',
      release_type: '2',
      teams: '37310',
      tags: 'developer,tester',
      strategy: 'replace'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    #hockey

    puts "All done successfully..."
    
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|

    puts "Error: " + exception.message

    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.example.MyBundle-alpha" # The bundle identifier of your app
apple_id "myemail@example.com" # Your Apple email address

team_id "000teamid000"  # Developer Portal Team ID

for_lane :alpha do
    app_identifier 'com.example.MyBundle-alpha'
end

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.4.5        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.0       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
</details>

*generated on:* **2017-05-30**
</details>

**Comment by lferro9000** [comment]
After some tests (of passing the values from Matchfile into Fastfile - which should not be needed), i got match to pass. Now gym is complaining about missing project file.

When i tried to add workspace: "value", i've found the some strange thing:
```
[15:39:53]: fastlane finished with errors

[!] Workspace file not found at path '/Users/user/dev/platopus/fastlane_env/MyApp.xcworkspace'
```
It looks like fastlane now is converting the symlink of fastlane into it's target (which may be a reason for some issues finding the project, but not of finding it's own files like Matchfile one).

My setup is like:
```
/projectfolder
|-- fastlane_env
    |-- schema1
    |-- [...]
    |-- schemax
|-- fastlane (-> fastlane_env/schema1)
```
And i've a script to swap between the schemes to allow jenkins automation for it.

**Comment by KrauseFx** [comment]
It would help to see the directory tree, or a screenshot of how your folders are set up. This doesn't look like it's a _fastlane_ bug

**Comment by lferro9000** [comment]
Hi :)

The problem is that i was trying to add all the profiles inside the fastlane_env. The whole setup works IF the symlinked folders are on the same level as fastlane folder.

Basically, somewhere along the execution, the path is resolved to the absolute path of the fastlane folder (be it a true folder or a symlink).

By using the fastlane_env with the schema1 folder (in case of that target), the folder would resolve to /projectfolder/fastlane_env/schema1 and not /projectfolder/fastlane as i was expecting.

This resulted that when fastlane tries to find a file, i'm guessing its calling ../fastlane/Matchfile, which obviously fails as fastlane folder doesn't exist.

The same when finding the project file etc.

The giveaway was that gym created a folder called build inside the fastlane_env, which means that it expects everything to be on that level.

I've just reverted to /projectfolder/schema1 etc, and everything is working again.

:)

**Comment by lferro9000** [comment]
So basically it is just a case of the whole set of applications that fastlane is / uses that converts the symlink to it's true folder somewhere along the way.
