### ISSUE TITLE
[Question] match still create new cert for the same account with different app id

### ISSUE THREAD

**Issue by truebit** [fastlane/fastlane#9325]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I have an app and used match, it created related certs repo for me, two apple dev accounts used:  one for  development and appstore, and one for enterprise.
I got another app that uses the same apple dev accounts mentioned above, just different app ids.

I made them in different branch in certs repo. But it would create new cert for these two branches even when one branch already created a cert.

Two certs with same name would make xcodebuild throw error about cannot find proper cert for the provisioning file

### Environment
not needed

**Comment by truebit** [comment]
My current workaround is to copy the corresponding certs from one branch to another branch, then using match to auto generate profiles.

How match decide to create a new cert or not?

**Comment by joshdholtz** [comment]
@truebit Multiple apps should get stored in the same branch. Multiple teams should get stored in different branches. This should solve your issue 😊 

See here - https://github.com/fastlane/fastlane/tree/master/match#important-use-one-git-branch-per-team

**Comment by truebit** [comment]
@joshdholtz but the provision profiles are different due to the different app id, how to resolve that?

**Comment by truebit** [comment]
Thanks a lot, I know how to organize certificates repo now

**Comment by joshdholtz** [comment]
@truebit Not a problem! Happy fastlaning 💪 🚀
