### ISSUE TITLE
Default relase note not used.

### ISSUE THREAD

**Issue by rckoenes** [fastlane/fastlane#9327]
### New Issue Checklist

- [*] Updated fastlane to the latest version
- [*] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I've set a default release note in my deliverfile, but I'm always getting the following error:
`[en-US]: You must detail what's new in this version in English (U.S.).`

I have tried but solutions in the issue posted in the error log bit they did not provide a solution.

##### Complete output when running fastlane, including the stack trace and command used
```
+--------------------------------------+--------------------------------------+
|                           deliver 2.35.1 Summary                            |
+--------------------------------------+--------------------------------------+
| force                                | true                                 |
| submit_for_review                    | true                                 |
| skip_screenshots                     | true                                 |
| automatic_release                    | true                                 |
| skip_metadata                        | false                                |
| username                             | _snip_       |
| app_identifier                       | nl._snip_                 |
| app_review_information.first_name    | _snip_                              |
| app_review_information.last_name     | _snip_                               |
| app_review_information.phone_number  | _snip_                       |
| app_review_information.email_addres  | _snip_          |
| s                                    |                                      |
| app_review_information.demo_user     | _snip_       |
| app_review_information.demo_passwor  | ********                             |
| d                                    |                                      |
| release_notes.default                | Bug fixes                      |
| release_notes.nl-NL                  | Problemen opgelost |
| ipa                                  | /Users/snip/Development/iOS/_snip_.ipa                   |
| screenshots_path                     | ./fastlane/screenshots               |
| metadata_path                        | ./fastlane/metadata                  |
| app_version                          | 3.8.1                                |
| edit_live                            | false                                |
| platform                             | ios                                  |
| skip_binary_upload                   | false                                |
| dev_portal_team_id                   | _snip_                           |
| overwrite_screenshots                | false                                |
+--------------------------------------+--------------------------------------+

[11:59:24]: You can tweet: "iTunes Connect #iosprocessingtime 19 minutes"
[11:59:56]: Selecting build 3.8.1 (5121)...
[11:59:58]: Successfully selected build
[11:59:58]: Submitting the app for review...
+-----------------------------+--------------------------------------+
|                            Lane Context                            |
+-----------------------------+--------------------------------------+
| DEFAULT_PLATFORM            | ios                                  |
| ENVIRONMENT                 | _snip_                                   |
| PLATFORM_NAME               | ios                                  |
| LANE_NAME                   | ios deploy                           |
| GIT_REPO_WAS_CLEAN_ON_START | true                                 |
| IPA_OUTPUT_PATH             | /Users/_snip_  /Development/iOS  |
|                             | _snip_  .ipa                   |
| DSYM_OUTPUT_PATH            | /Users/_snip_ /Development/iOS  |
|                             |_snip_ .app.dSYM.zip          |
| XCODEBUILD_ARCHIVE          | /Users/_snip_ /Library/Developer/Xc  |
|                             | ode/Archives/2017-05-31/_snip_     |
|                             | 2017-05-31 11.28.32.xcarchive        |
+-----------------------------+--------------------------------------+
[12:00:03]: [en-US]: You must detail what's new in this version in English (U.S.).

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | clear_derived_data     | 0           |
| 3    | Switch to ios          | 0           |
|      | deploy_app_store lane  |             |
| 4    | ensure_git_status_cle  | 0           |
|      | an                     |             |
| 5    | ensure_git_branch      | 0           |
| 6    | cocoapods              | 26          |
| 7    | gym                    | 185         |
| 8    | crashlytics            | 23          |
| 💥   | deliver                | 1688        |
+------+------------------------+-------------+

[12:00:03]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Deliver: [en-US]: You must detail what's new in this version in English (U.S.).
    https://github.com/fastlane/fastlane/issues/7016 [closed] 4 💬
    14 Mar 2017

➡️  Fastlane is not utilizing my Deliverfile while uploading w/ deliver
    https://github.com/fastlane/fastlane/issues/6345 [closed] 5 💬
    08 Jan 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.

[!] The request could not be completed because:
	[en-US]: You must detail what's new in this version in English (U.S.).
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.5                                       |
| Ruby                        | 2.2.4                                         |
| Bundler?                    | false                                         |
| Git                         | git version 2.10.1 (Apple Git-78)             |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane           |
| Host                        | Mac OS X 10.12.5 (16F73)                      |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                    |
| Is contained                | false                                         |
| Is homebrew                 | true                                          |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode_8.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

private_lane :deploy_app_store do |options|
  
  if options[:submit_for_review]
     # If the GIT status is not clean, abort. We won't want to include junk in the build
    ensure_git_status_clean
    ensure_git_branch(branch: 'release')
  end
  
  # Install cocoapods libaries
  cocoapods
  
  # Build  the app
  gym(
    clean: true,
    scheme: options[:scheme], 
    include_bitcode: true, 
    include_symbols: true
  )
  
  # upload the build to crashlytics so we can grab it later
  crashlytics(
    api_token: ENV['CRASHLYTICS_TOKEN'], 
    build_secret: ENV['CRASHLYTICS_SECRET'],
  )
  
  if options[:submit_for_review]
    # Upload and submit it for review.
    deliver(
      force: true,
      submit_for_review: true,
      skip_screenshots: true,
      automatic_release: true,
      skip_metadata: false,
      username: ENV['DLV_ITUNESCONNECT_USERNAME'],
      app_identifier: ENV['DLV_BUNDLE_ID'],
    )
  else 
    pilot(
      skip_waiting_for_build_processing: true
    )
  end
  
end

private_lane :build_beta do |options|
  clear_derived_data
  
  # Install cocoapods libaries
  cocoapods
  
  gym(
    clean: true,
    scheme: options[:scheme], 
    include_bitcode: true, 
    include_symbols: true,
    export_method: "ad-hoc"
  )
  
  # Upload to fabric and inform the user group
  crashlytics(
    api_token: ENV['CRASHLYTICS_TOKEN'], 
    build_secret: ENV['CRASHLYTICS_SECRET'],
    groups: ENV['CRASHLYTICS_GROUP']
  )
    clean_build_artifacts
end

platform :ios do
  
  before_all do
    # Clear an build data
    clear_derived_data
  end

  after_all do 
    clean_build_artifacts
  end
  
  # General lanes
  desc "Refresh all the DSYMs for this account"
  lane :refresh_dsym do |options|
    # Download dSYM files from iTC
    download_dsyms(
      username: ENV['DLV_ITUNESCONNECT_USERNAME'], 
      app_identifier: ENV['DLV_BUNDLE_ID']
    )
  
    # Upload them to Crashlytics
    upload_symbols_to_crashlytics(
      api_token: ENV['CRASHLYTICS_TOKEN']
    )
  end
  
  desc "Increment build version"
  lane :bump_version do
    ensure_git_status_clean
    
    project = './_snip_ /_snip_ .xcodeproj'
    
    increment_build_number(
      xcodeproj: project,
    )
    
    build_number = get_build_number(
      xcodeproj: project
    )
    
    commit_message = "Version bumped to " + build_number
    commit_version_bump(
      message: commit_message
    ) 
       
    add_git_tag(
      tag: build_number
    )
    push_git_tags
    push_to_git_remote
    
  end
  
  desc "Build and submit to Apple, upload to crashyltics."
  lane :deploy do
    deploy_app_store(
      submit_for_review: true,
      schema: ENV['GYM_SCHEME']
    )
  end
  
  desc "Build and deploy to TestFlight, upload to crashyltics."
  lane :deploy_release_candidate do
    deploy_app_store(
      submit_for_review: false
    )
  end
    
  desc "Runs all the unit tests"
  lane :unit_test do
    scan(scheme: "Tests")
  end

  desc "Deploy staging to Fabric"
  lane :staging do
      build_beta(scheme: "_snip_  Staging")
  end
  
  desc "Deploy daily builds"
  lane :build_daily do
      build_beta(scheme: "_snip_  Test Live")
      build_beta(scheme: "_snip_  Staging")
      build_beta(scheme: "_snip_  Dogfood")
  end
  
  desc "Deploy dogfood to Fabric"
  lane :dogfood do
      build_beta(scheme: "_snip_")
  end
  
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "nl._snip_" # The bundle identifier of your app
apple_id "_snip_" # Your Apple email address

team_id "_snip_"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.35.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-05-31**
</details>

[INSERT OUTPUT HERE]

**Comment by rckoenes** [comment]
With more languages configured it will give the error for every language not specific configured.
`
[it]: You must detail what's new in this version in Italian. 
[de-DE]: You must detail what's new in this version in German. 
[en-US]: You must detail what's new in this version in English (U.S.).
 [es-ES]: You must detail what's new in this version in Spanish (Spain).
[fr-FR]: You must detail what's new in this version in French.`

**Comment by joshdholtz** [comment]
@rckoenes Can you paste what your `Deliverfile` looks like? Your `Fastfile` and `Appfile` got copied over okay in the fastlane env output but it doesn't look like your `Deliverfile` did. Just want to make sure I know exactly how you are doing things so I can look into and try to replicate on my end 😇

**Comment by rckoenes** [comment]
No problem
`
###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md

app_review_information(
  first_name: "Remmelt",
  last_name: "Koenes",
  phone_number: "_snip_",
  email_address: "_snip_",
  demo_user: "_snip_",
  demo_password: "_snip_",
  notes: ""
)
release_notes({
  'default' => "bug fixes",
  'nl-NL' => "Problemen opgelost"
})`

**Comment by joshdholtz** [comment]
@rckoenes Thank you! Have you tried setting each language individually and **not** using `default`? That's not the "proper" solution but curious if that works/worked for you 🤔  Just trying to track down if its an API issue or if its an issue with how `default` has been implemented.

Once I know that I should be able to more easily track down this bug 👌

**Comment by rckoenes** [comment]
I've not tried that, since this script is run for multiple targets via .env files. And all languages are set for each target.

**Comment by joshdholtz** [comment]
@rckoenes Not a problem! Just curious if that solution would have worked for you. I will add this to my list of things to look into this week 💪

**Comment by joshdholtz** [comment]
@rckoenes I am working on a legit solution but I found a quick solution for you if you need to solve this like right now... 😇 

### Legit solution (that I'm working on)
I will add a new configuration in deliver/Deliverfile that allows a full list of languages to "enable" for an application so the quick solution below doesn't need to be used.

### Quick solution
I found this line of code in `Deliver` - https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/upload_metadata.rb#L139

This line says "Check folder list (an empty folder signifies a language is required)". So what you can do is create an empty folder structure in "metadata" so that `Deliver` knows all the languages you want to use. This gives "default" a full list of all the languages that it needs to set things for. 

```
- fastlane
  - Fastfile
  - metadata
    - en-US
      - .gitkeep
    - de-DE
      - .gitkeep
```
_Note: the `.gitkeep` is used so the folders will get committed to version control (they don't have any other purpose_

Hope this quick solution helps you if you need to get this running while I work on the actually solution 😊 🚀

**Comment by rckoenes** [comment]
The problem with this solution is that if the whitelabel app does not have a language in iTunesConnect it will try and add it. 
The solution would be to include a metadata directory for each whitelabel app to make sure that it matches client set languages in iTunesConnect.

**Comment by joshdholtz** [comment]
@rckoenes I totally get it why the empty directory thing would work (but I wanted to give you a temporary solution while I'm working on the actually fix 😇 ). The actually fix will be something like the below in your deliver action or Deliverfile (which I believe should work for you). 

### Fastfile
```rb
deliver(
  app_identifier: "com.something,
  skip_metadata: false,
  languages: ['en-US', 'de-DE','nl-NL']
)
```

### Deliverffile
```rb
app_review_information(
  first_name: "Remmelt",
  last_name: "Koenes",
  phone_number: "_snip_",
  email_address: "_snip_",
  demo_user: "_snip_",
  demo_password: "_snip_",
  notes: ""
)
languages(['en-US', 'de-DE','nl-NL'])
release_notes({
  'default' => "bug fixes",
  'nl-NL' => "Problemen opgelost"
})
```
