### ISSUE TITLE
HowTo : Local provisioning for watch app ?

### ISSUE THREAD

**Issue by itapplidium** [fastlane/fastlane#933]
Hi @KrauseFx 

The `gym` command only takes one `provisioning_profile_path`parameter. 
I am currently using the [CodeSign guide](https://github.com/fastlane/fastlane/blob/master/docs/CodeSigning.md) to fetch and set variable environments for the 3 profiles (apps, watch app, watch ext) but if those are available locally I would like to use them.

Using the Environment variable with the profile UUID will only work  if the profile is imported within my profile library. If so I am considering several solutions  and wondering which one would be the best

1. Use the [update_provisioning_profile](https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md#update_project_provisioning) action but it's hacky and changes the behaviour between builds with / without sigh
2. When using sigh, parse the mobileprovision to get its UUID. Store the values for each of my configuration in an hash somewhere. That might look a bit like this

```
{
	"inhouse": {
		"app_profile_udid": "XXXX-XXX-XXX",
		"watch_app_profile_udid": "XXX-XXX-XXX",
		"watch_ext_profile_udid": "XXX-XXX-XXX",
		"export_method": "enterprise"
	},
	"appstore": {
		"app_profile_udid": "XXXX-XXX-XXX",
		"watch_app_profile_udid": "XXX-XXX-XXX",
		"watch_ext_profile_udid": "XXX-XXX-XXX",
		"export_method": "app-store"

	},
	"dev": {
		"app_profile_udid": "XXXX-XXX-XXX",
		"watch_app_profile_udid": "XXX-XXX-XXX",
		"watch_ext_profile_udid": "XXX-XXX-XXX",
		"export_method": "development"
	}
}
```  
appstore, inhouse, dev being some of my default lanes.
Then when signing locally use a shell script to open the .mobileprovision (stored in git) file to be sure there is a match for the env variable in XCode. (this step could be done manually)

None of the solutions above suits me but I cannot think of something better. Note that working in an agency I really need to update this automatically, I cannot maintain it for more than 30 apps. 

Note that I will also have to manually handle the `export_method` option to pass to `gym`id I am not using sigh. I am aware of that.

Thanks for your great work and help,

Nicolas

**Comment by jcampbell05** [comment]
The sigh action returns the UDID so you could store it in the ENV like so:

    ENV['apple_watch_udid'] = sigh
    ENV['apple_watch_extension_udid'] = sigh

**Comment by nicolasbraun** [comment]
Hi,

Exactly I do not want to use the sigh action all the time (only if the provisioning are locally missing or expired)

Nicolas

PS : this is me with the correct account this time !

**Comment by KrauseFx** [comment]
Yeah, that's why we've worked on a cool new tool called [match](https://github.com/fastlane/match) which solves all of the problems above :+1: 
You should start using it - let me know what you think.
