### ISSUE TITLE
frameIt should support global strings for multiple targets

### ISSUE THREAD

**Issue by odrobnik** [fastlane/fastlane#9336]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

`frameIt` requires that the strings files be positioning inside the `de_DE` folder for the screenshots. The problem is if you have multiple sub-folders for multiple targets like I have. e.g. `Screenshots/app1/de_DE`, `Screenshots/app2/de_DE`

You *can*  put the `Framefile.json` in `Screenshots` and so you should be able to do the same with the strings files too. `frameIt` recurses into the app-subfolders and starts framing the files, but does not see the strings files if the language folders right next to the `Framefile.json`

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.3.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2f  28 Jan 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 2.1.0        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| faraday_middleware        | 0.11.0.1     |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
</details>

*generated on:* **2017-06-01**
</details>

**Comment by ohayon** [comment]
Hey @odrobnik, thanks for raising the issue. I'm not totally sure if this is a bug, or a feature request. Is there any way you would want/have some time to submit a PR for this? That would be 💯 ! 🚀

**Comment by odrobnik** [comment]
@ohayon Sorry, I am an iOS developer and have no idea how to change ruby code.

**Comment by odrobnik** [comment]
If I were to investigate how to fix that... how can I modify an `.rb` file and have that be used instead of the installed gem's version?

**Comment by ohayon** [comment]
@oronbz the easiest way to test it would be to clone this repo, and then create a `Gemfile` in your iOS project directory with the contents: 
```
source "https://rubygems.org"

gem 'fastlane', path: 'path/to/fastlane/repo'
```

And then execute your _fastlane_ commands with the prefix `bundle exec fastlane ...`

**Comment by oronbz** [comment]
Hi old friend @ohayon, I think you misspelled the mention (:

**Comment by ohayon** [comment]
Oops! Sorry! @oronbz !

**Comment by odrobnik** [comment]
This is still waiting for somebody who is versed in Ruby to tackle.
