### ISSUE TITLE
Gym - Error code: 65 

### ISSUE THREAD

**Issue by robertofrontado** [fastlane/fastlane#934]
Hello Felix!

I got a problem trying gym in fastlane,

My lane:

  desc "Create ipa"
  lane :build do
    gym
  end

I'm executing "fastlane build" in the command line through a remote desktop using Screensharing, since El Capitan I can't press allow button in the Keychain prompt (codesing is trying to use a specific key...), so I can't execute gym from my machine, and I don't have physical access to the server machine.

So I was wondering if somehow gym (or sign, cert, any fastlane's module) can do that for me (allow codesign to use that key).

Or if you have any idea about how can I solve this.

**Comment by Rking788** [comment]
i don't have any experience doing this exactly but the unlock_keychain fastlane action sounds promising. A description of the action can be found here: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md#unlock_keychain

**Comment by ohwutup** [comment]
Hey everyone. I am going to go ahead and close this issue for now because it's been a while since there has been activity on it. Please feel free to continue discussion and we will reopen it if appropriate. Thanks!! :rocket: :guitar:
