### ISSUE TITLE
How can I do for  solve the problem???

### ISSUE THREAD

**Issue by WangGuibin** [fastlane/fastlane#9343]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

DDYSdeMacBook-Pro:~ Wangguibin$ brew cask install fastlane
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalon
######################################################################## 100.0%
==> No checksum defined for Cask fastlane, skipping verification
==> ditto: /var/folders/4h/67cgwf2941zc1hypv_8qwb000000gn/T/d20170602-25245-x57d
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
==> ditto: Couldn't read pkzip signature.
Error: Command failed to execute!

==> Failed command:
/usr/bin/ditto -x -k -- #<Pathname:/Users/ddys/Library/Caches/Homebrew/Cask/fastlane--latest.zip> /var/folders/4h/67cgwf2941zc1hypv_8qwb000000gn/T/d20170602-25245-x57dne

==> Standard Output of failed command:

==> Standard Error of failed command:
ditto: /var/folders/4h/67cgwf2941zc1hypv_8qwb000000gn/T/d20170602-25245-x57dne/fastlane_lib/bundle/lib/ruby/gems/2.2.0/gems/google-api-client-0.9.28/generated/google/apis/dfareporting_v2_5/classes.rb: No space left on device
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.
ditto: Couldn't read pkzip signature.

==> Exit status of failed command:
#<Process::Status: pid 25508 exit 1>

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by hjanuschka** [comment]
hey @WangGuibin 🤚
 looks like your harddisk is out of space
`No space left on device`  - try making some MB/GB free and retry the installation

let me know if this helps

**Comment by WangGuibin** [comment]
Thank you ,I Has been solved
