### ISSUE TITLE
Sigh stopped pulling distribution certificate from Dev Portal

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#9348]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used

I have distribution certificate created, but fastlane/sigh stopped pulling it from dev portal after update to 2.36.0

```
[18:53:48]: Successfully logged in
[18:53:48]: Fetching profiles...
[18:53:50]: Verifying certificates...
[18:53:51]: Certificate for Provisioning Profile 'iOS App Widget Distribution' not available locally: R2W4U29R54, skipping this one...
[18:53:51]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
+--------------------+-----------------------------------------------------+
|                               Lane Context                               |
+--------------------+-----------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                 |
| PLATFORM_NAME      | ios                                                 |
| LANE_NAME          | ios testflight                                      |
| SIGH_PROFILE_PATH  | /Users/pronebird/dev/ios-app/iOS App/iOS         |
|                    | provisioning/AppStore_com.example.iOSApp.mo  |
|                    | bileprovision                                       |
| SIGH_PROFILE_PATHS | ["/Users/pronebird/dev/ios-app/iOS App/iOS       |
|                    | provisioning/AppStore_com.example.iOSApp.mo  |
|                    | bileprovision"]                                     |
| SIGH_UDID          | 53dbaebd-7fa5-4cd2-9fbb-5c5db4b8e5dc                |
| SIGH_UUID          | 53dbaebd-7fa5-4cd2-9fbb-5c5db4b8e5dc                |
| SIGH_PROFILE_TYPE  | app-store                                           |
+--------------------+-----------------------------------------------------+
[18:53:57]: Could not find a matching code signing identity for type 'AppStore'
```

Lane code:

```
  desc "Submit a new Beta Build to Apple TestFlight"
  lane :testflight do
    CHANGELOG = File.read("testflight/changelog.txt")
    BUILD_VERSION = `git describe --abbrev=0`.sub("build/", "").strip
    APP_NAME = ENV["APP_NAME"]

    sigh(app_identifier: ENV["APP_BUNDLE_ID"])
    sigh(app_identifier: ENV["WIDGET_BUNDLE_ID"])

    cocoapods
    gym(configuration: "Testing")
    pilot(changelog: CHANGELOG, distribute_external: false, skip_waiting_for_build_processing: true)
  end
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by pronebird** [comment]
Running cert helped, but now it created production certificate using my email and two extra distribution profiles for app + widget. Strange it cannot see Distribution certificate that we already have. How does it match it?

**Comment by joshdholtz** [comment]
@pronebird Are you running this on a different machine than where the certificate is created/installed? Certificates don't _actually_ get pulled down from the developer center (the provisioning profiles do). When a new cert is created, the private key gets installed in your computer's keychain and the public key gets sent up to the Apple developer center.

The way `sigh` works is it will pull down the provisioning profile(s) that match up with a valid certificate you have installed on your machine (meaning that the public cert that the profile was created with matches with a private cert that you have installed). 

So (without knowing too much about your setup) is it seems that you may be running `sigh` on a machine that doesn't have your private cert installed. The solution for this would be to use `match` or to manually export the private cert from your keychain and import it into your machine.

^^ Lemme know if this is not the case though 😉

**Comment by pronebird** [comment]
Same machine but I think what happened is somebody re-created everything from scratch and dropped old distribution profile. I ended up with orphaned private key and expired certificate. That makes sense then. Closing because everything works now.

**Comment by joshdholtz** [comment]
@pronebird Glad you figured it out! Happy fastlaning 💪 🚀
