### ISSUE TITLE
snapshot without running unit tests?

### ISSUE THREAD

**Issue by mshibanami** [fastlane/fastlane#9356]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

My Xcode project for iOS App has a scheme which contains a UI test and a unit test.
I ran `fastlane snapshot run` to take screenshots. Then both tests ran.

Running UI tests is OK because it's necessary to take screenshots with `snapshot`. But I think running unit tests is unnecessary. And it takes a lot of time.

Is my understanding correct?
Can I run `snapshot` without running unit tests?

**Comment by lam2558** [comment]
Would like to have this option as well.  I use snapshot separate from unittests and would prefer that the setup/running of unittest be disabled as an option

**Comment by mshibanami** [comment]
it seems to be impossible because `snapshot` depends on xcodebuild (`xcodebuild test`) and xcodebuid can't do that.
I just sent a feature request about it to Apple as rdar://32614779.

**Comment by brennantaylor** [comment]
You can pass `--xcargs "-only:TestBundle/TestName"` or something to only run the test/tests you care about. Or split the bundle into two targets and create a new scheme with only your uitests in it.

**Comment by lam2558** [comment]
Will this work inside Snapfile config?

QA Guy

**Comment by ohayon** [comment]
Hey @lam2558! You should be able to do this from the Fastfile or Snapfile by passing the `:xcargs` option with the value that @brennantaylor mentioned above. FWIW I have not seen this done before, but if @brennantaylor's solution works from the command line, this should work via _fastlane_. Let us know if you continue to have any trouble! 🚀 🐙

**Comment by mshibanami** [comment]
I'm sorry for my late reply. I was extremely busy with work this week...

@brennantaylor
>You can pass --xcargs "-only:TestBundle/TestName" or something to only run the test/tests you care about. Or split the bundle into two targets and create a new scheme with only your uitests in it.

Wow, Xcode has that feature! I didn't know that. I jumped to conclusions. Thanks a lot! 
But it seems to be a bit of a mistake. According to [the session of WWDC 2016](https://developer.apple.com/videos/play/wwdc2016/409/?time=1957), `-only-testing` is correct. It is a feature provided after Xcode 7.3. We can specify it like this: 

![slide](https://user-images.githubusercontent.com/1333214/27192466-74f876b4-5236-11e7-9d5a-e50e72da4c0e.png)

@lam2558 @ohayon 
I didn't know about `xcargs` as well. I put the following code on `Snapfile` and it worked fine! 

```ruby
xcargs "-only-testing:MyUITestBundle"
```

In my case, this solution reduced the time for running `snapshot` to half.
Thank you all, guys!

**Comment by mshibanami** [comment]
So I think that it would be nice if this option specified by default for `snapshot`.
It looks hard to specify `-only-testing` dynamically though.

What do you think?

**Comment by lam2558** [comment]
thx all. these suggestions are working perfectly for me now.

**Comment by ohayon** [comment]
Glad to hear things are working well! I'm going to close this issue for now but please feel free to continue conversation and ask more questions here and we will reopen if necessary!! 🚀
