### ISSUE TITLE
fastlane supply jason file issue

### ISSUE THREAD

**Issue by TayyabDar** [fastlane/fastlane#9360]
@KrauseFx
@asfalcone 
Hello Fastlane team, i m stuck in a strange issue from many days of fastlane supply. i have followed all the steps shown in this link: https://github.com/fastlane/fastlane/tree/master/supply

But my issue is that when i run 'fastlane supply init' in terminal, it says;

To not be asked about this value, you can specify it using 'json_key'
[15:20:40]: The service account json file used to authenticate with Google: 

Then i just drag the json file but i gives error that;

 Error setting value '/Volumes/Data/Plasma\ IT\ Solutions/Google\ Play\ Android\ Developer-2cdb23a53eac.json' for option 'json_key'

[!] '/Volumes/Data/Plasma\ IT\ Solutions/Google\ Play\ Android\ Developer-2cdb23a53eac.json' doesn't seem to be a JSON file

Please help me on this issue and i have provided the details below;

### New Issue Checklist

- [done ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Captured Output

Command Used: ``
<details><summary>Output/Log</summary>

```

DEBUG [2017-06-05 15:15:20.50]: Checking if there are any plugins that should be loaded...
WARN [2017-06-05 15:15:20.60]: Could not find fastlane in current directory. Make sure to have your fastlane configuration files inside a folder called "fastlane". Would you like to set fastlane up?

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not retrieve response as fastlane runs in non-interactive mode

URL: https://api.github.com/search/issues?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode+repo:fastlane/fastlane
➡️  fastlane init not prompting for Apple Id
    https://github.com/fastlane/fastlane/issues/9048 [open] 8 💬
    4 weeks ago

➡️  Setting up fastlane for the first time, getting errors early on. 
    https://github.com/fastlane/fastlane/issues/8792 [open] 7 💬
    a week ago

➡️  fastlane deliver upload_build - not referencing fastlane/metadata/review_information/notes.txt for app_review_information key 'notes'
    https://github.com/fastlane/fastlane/issues/8413 [closed] 2 💬
    5 days ago

and 17 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20retrieve%20response%20as%20fastlane%20runs%20in%20non-interactive%20mode&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.12                                |
| Ruby                        | 2.3.3                                |
| Bundler?                    | false                                |
| Git                         | git version 2.9.3 (Apple Git-75)     |
| Installation Source         | /usr/local/bin/fastlane              |
| Host                        | Mac OS X 10.12 (16A323)              |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib     |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.13.6       |
| json                      | 2.0.4        |
| io-console                | 0.4.5        |
| excon                     | 0.55.0       |
| rubyzip                   | 1.2.1        |
| faraday                   | 0.12.0.1     |
| faraday_middleware        | 0.11.0.1     |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| google-api-client         | 0.9.28       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| fastimage                 | 2.1.0        |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.3        |
| gh_inspector              | 1.0.3        |
</details>

*generated on:* **2017-06-05**
</details>

**Comment by nerd0geek1** [comment]
@TayyabDar 
It looks file name parsing problem.

I also encounter same problem, and change json file name to `google_play.json`, and it succeed.

**Comment by TayyabDar** [comment]
Thanks @nerd0geek1  for commenting. But my issue it still there. i have also updated to latest version and changed file name to "google_play.json". 

I am just running this command fastlane supply init, then the terminal is asking for json file and i just drag it to terminal. but it gives error. Here is the detailed output from terminal

[15:25:51]: To not be asked about this value, you can specify it using 'json_key'
[15:25:51]: The service account json file used to authenticate with Google: /Volumes/Data/Plasma\ IT\ Solutions/google_play.json.json 
[15:26:09]: Error setting value '/Volumes/Data/Plasma\ IT\ Solutions/google_play.json.json' for option 'json_key'

[!] '/Volumes/Data/Plasma\ IT\ Solutions/google_play.json.json' doesn't seem to be a JSON file

**Comment by adamclark64** [comment]
I am also having this issue with the name switched to google_play.json
