### ISSUE TITLE
Produce not working in non interactive mode

### ISSUE THREAD

**Issue by andreconde21** [fastlane/fastlane#9362]
### New Issue Checklist

- ✅ Updated fastlane to the latest version
- ✅ I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am using the recent feature on Windows 10 of "Bash on Ubuntu on Windows". I created an app to invoke fastlane through it, being it a non interactive shell (everything passed as argument + set of environment variables). The problem that is happening is that invoking _produce create_ results only in the presentation of the summary, with no result output (the next command starts immediately). Meanwhile, the same group of commands run correctly when typed directly to the bash. Also, _produce disable_services_, for example, logs in with success and executes as expected in non interactive mode, which makes me think that there may be some problem with _produce_ in a non interactive shell.

##### Commands
```
export FASTLANE_USER=user; 
export FASTLANE_PASSWORD=*****; 
export FASTLANE_DONT_STORE_PASSWORD=1; 
echo "Invoking create"; 
fastlane produce create --app_identifier andreconde.gitexample --app_name GitExample --app_version 1.0 --skip_itc True --skip_devcenter False --verbose; 
echo "Invoking disable_services"; 
fastlane produce disable_services --app_identifier andreconde.gitexample --app-group --apple-pay --associated-domains --data-protection --game-center --healthkit --homekit --wireless-conf --icloud --in-app-purchase --inter-app-audio --passbook --push-notification --sirikit --vpn-conf --verbose;

##### Complete output when running fastlane

Invoking create
+----------------+-----------------------------+
|          Summary for produce 2.36.0          |
+----------------+-----------------------------+
| app_identifier | andreconde.gitexample        |
| app_name       | GitExample               |
| app_version    | 1.0                         |
| skip_itc       | True                        |
| skip_devcenter | False                       |
| username       | user |
| sku            | 1496675512                  |
| platform       | ios                         |
| language       | English                     |
+----------------+-----------------------------+
Invoking disable_services
INFO [2017-06-05 16:12:10.64]: Starting login with user 'user'
INFO [2017-06-05 16:12:14.91]: Successfully logged in
INFO [2017-06-05 16:12:15.49]: [DevCenter] App 'andreconde.gitexample' does not exist
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                            |
| --------------------------- | ---------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                         |
| Ruby                        | 2.3.1                                                            |
| Bundler?                    | false                                                            |
| Git                         | git version 2.7.4                                                |
| Installation Source         | /usr/local/bin/fastlane                                          |
| Host                        | Ubuntu 16.04.2 LTS debian_based stretch/sid (4.4.0-43-Microsoft) |
| Ruby Lib Dir                | /usr/lib                                                         |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                       |
| Is contained                | false                                                            |
| Is homebrew                 | false                                                            |
| Is installed via Fabric.app | false                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.0       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-06-05**
</details>

**Comment by ohayon** [comment]
Hey @andreconde21 ! Apologies for the issue you are seeing, one thing to preface this response with is that _fastlane_ is definitely optimized for running on macOS and some behavior on Linux, or Windows, or Linux _on_ Windows might be a little undefined. That being said, could you try creating a Fastfile and setting up your actions in lanes defined in there rather than invoking things from the command line? Also, if you could run with `--verbose` and share the output that also might be helpful in figuring out whats going wrong. 😄  🐙  🚀
