### ISSUE TITLE
Fastlane supply fails to upload APK with different API Level. 

### ISSUE THREAD

**Issue by GitRubb** [fastlane/fastlane#9363]
### New Issue Checklist
- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I would like to upload multiple APKs to the Alpha stream. I have 1 APK currently uploaded. 
APK 1: Currently hosted APK has min API level 22, target 25, versionCode 22001007
APK 2: Has min API level 16, target 23, versionCode 16001012.
Fastlane supply uploaded APK 1 ok but it's failing to upload APK 2 with the output below. When I manually upload APK 2 to Google Play it works. 

### Output
[!] Google Api Error: multiApkDowngradedDevice: Devices with version 22001007 of this app would be downgraded to version 16001012 if they met the following criteria: [(API_LEVEL in range 22-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND NATIVE_PLATFORM containing any of each of [[x86, armeabi-v7a]] AND FEATURES containing all of [android.hardware.screen.PORTRAIT, android.hardware.FAKETOUCH, android.hardware.WIFI])].

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.4                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.4 (16E195)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.2                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.5.2        |
| plist                     | 3.1.0        |
| addressable               | 2.3.8        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160310 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 1.7.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0221  |
| mime-types                | 3.0          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.11.2       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.14.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.2        |
| googleauth                | 0.5.1        |
| thor                      | 0.19.1       |
| httpclient                | 2.7.1        |
| google-api-client         | 0.9.4        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.5       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.3        |
</details>

*generated on:* **2017-06-05**
</details>

**Comment by jamesjara** [comment]
Having the same issue, but the version is not downgrade is upgrade

**Comment by skreis** [comment]
I have a similar issue, my specific scenario as follows:
 * Fastlane 2.53.1
 * Cordova Android application
 * The first APK version was uploaded manually via the Google Play console to Alpha, configured as Release "1.0.0" and inadvertently had a Version Code of "10000"
 * A subsequent build was also successfully uploaded using the manual method (Google Play console), with a Release of "1.0.1" and a Version Code of "2"
 * I can _always_ upload a new release with a version code higher than the last via the Google Play console, and also seemed to do the same when going from 1.0.0 (10000) -> 1.0.1 (2)
 * All attempts at uploading using supply, however, are presently failing with the following message:

> Google Api Error: multiApkDowngradedDevice: Devices with version 10000 of this app would be downgraded to version 24 if they met the following criteria: [(API_LEVEL in range 16-0 AND RELEASE_TRACK containing any of each of [[ALPHA]] AND SCREENS containing any of each of [[small, normal, large, xlarge]] AND FEATURES containing all of [android.hardware.screen.PORTRAIT, android.hardware.FAKETOUCH])].

**Comment by mengyiyuan** [comment]
Have anyone solved this problem? I am on the latest version 2.63.0, and still the same error message. Manual uploading to Google store works.

**Comment by DaleWebb** [comment]
I'm also encountering this error on version `2.63.0`

**Comment by corneliu-serediuc** [comment]
There are 3 threads with this issue already opened, and for some reason they are all closed.
The interesting part is that you can still upload the apk via Google Play interface, but you can't do it via fastlane, thus the automation is not possible.

The `check_superseded_tracks` parameter does not seem to work.

Also using version `2.63.0`.

**Comment by lhalegria** [comment]
I'm also facing the error `multiApkDowngradedDevice` and figured out this error is occurring 'cause I have an older versionName "3.6.01" with versionCode 3601 and now I'm trying to upload new codeVersion 381 to play store. Doing the proccess manually everything works with not even a warning.
This is not about `check_superseded_tracks`.

I'm using version `2.67.0`.

**Comment by mdurban** [comment]
Why is this closed? It seems like it is not solved.

**Comment by pedpess** [comment]
This issue seems to be bothering quite many people :o... I got the same error today. I'm trying to figure out something but as an ad-hoc solution, the manual uploading is solving the issue (unfortunately).

**Comment by williamsjj** [comment]
I'm also having this problem. It happens when the minimum API level of the new build is greater than the old build. What we need is a flag to tell the Google Play API to accept it anyway (which it does if you manually upload).  @pedpess My versionCode is 4 higher than the last versionCode uploaded and the issue still occurs.

**Comment by joshdholtz** [comment]
Heeyyyyyyy 👋 Just looking into this issue for the first time so sorry for my questions but it seems like everyone is able to successfully upload manually via the Google Play website but cannot upload via fastlane/supply, correct? If that is the case, I will add this to my list of things to look into and fix 💪

**Comment by corneliu-serediuc** [comment]
Awesome! Thanks in advance, @joshdholtz!

**Comment by joshdholtz** [comment]
Just wanted to give a quick update here. I'm _thinking_ that this issue lies within the `google-api-client` gem that we are using to interact with the Google Play API. I was trying to replicate this error when I actually started getting `cannotUpdateApksOnTrackWithDraftRelease` (which is #11735).

I created a sample script using `google-api-client` outside of fastlane and was still getting same errors. The thing that solved it for me was manually uploading through Google Play - it essentially reset the weird state I was seeing.

Sadly, the temporary solution is to **manually upload APK through Google Play** like some of you mentioned above 😢 

But I will keep trying thing on my end to see if we can interact with the `google-api-client` like how the Google Play web dashboard does (since it works over there).

**Comment by eAi** [comment]
I am also having this issue. The build that it is complaining about the conflict with is not actually the last build that was uploaded. It allowed one build with two APKs to be uploaded fine, then another build with identical manifests failed with this error. Uploading manually via the Google Play website works fine.
