### ISSUE TITLE
increment_build_number fails with "agvtool: not found"

### ISSUE THREAD

**Issue by Gaia-Nutrition** [fastlane/fastlane#9364]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
- I'm trying to deploy the iOS version of my react-native app using Circle CI
- The build works like a charm on local but mysteriously fails on the `before_all` section of my FASTFILE at the `increment_build_number` action when deploying using Circle CI
- If there is any more content I could provide please let me know

### Captured Output

Command Used: `ios beta`
<details><summary>Output/Log</summary>

```

DEBUG [2017-06-05 18:42:49.60]: Checking if there are any plugins that should be loaded...
INFO [2017-06-05 18:42:49.61]: -------------------------------------------------
INFO [2017-06-05 18:42:49.61]: --- Step: Verifying required fastlane version ---
INFO [2017-06-05 18:42:49.61]: -------------------------------------------------
INFO [2017-06-05 18:42:49.61]: Your fastlane version 2.36.0 matches the minimum requirement of 2.36.0  ✅
INFO [2017-06-05 18:42:49.61]: ------------------------------
INFO [2017-06-05 18:42:49.61]: --- Step: default_platform ---
INFO [2017-06-05 18:42:49.61]: ------------------------------
INFO [2017-06-05 18:42:49.61]: Driving the lane 'ios beta' 🚀
INFO [2017-06-05 18:42:49.62]: ------------------------------------
INFO [2017-06-05 18:42:49.62]: --- Step: increment_build_number ---
INFO [2017-06-05 18:42:49.62]: ------------------------------------
INFO [2017-06-05 18:42:49.62]: $ cd /home/ubuntu/gaia-pro/ios && agvtool next-version -all && cd -
INFO [2017-06-05 18:42:49.62]: ▸ sh: 1: agvtool: not found
ERROR [2017-06-05 18:42:49.62]: Before being able to increment and read the version number from your Xcode project, you first need to setup your project properly. Please follow the guide at https://developer.apple.com/library/content/qa/qa1827/_index.html
INFO [2017-06-05 18:42:49.97]: Sending crash report...
INFO [2017-06-05 18:42:49.97]: The stacktrace is sanitized so no personal information is sent.
INFO [2017-06-05 18:42:49.97]: To see what we are sending, look here: /home/ubuntu/.fastlane/latest_crash.json
INFO [2017-06-05 18:42:49.97]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
INFO [2017-06-05 18:42:49.97]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile
INFO [2017-06-05 18:42:49.98]: -------------------
INFO [2017-06-05 18:42:49.98]: --- Step: slack ---
INFO [2017-06-05 18:42:49.98]: -------------------
DEBUG [2017-06-05 18:42:49.98]: Taking value for 'slack_url' from environment variable 'SLACK_URL'
INFO [2017-06-05 18:42:50.13]: Successfully sent Slack notification
WARN [2017-06-05 18:42:50.13]: Lane Context:
INFO [2017-06-05 18:42:50.13]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios beta"}
ERROR [2017-06-05 18:42:50.13]: Exit status of command 'cd /home/ubuntu/gaia-pro/ios && agvtool next-version -all && cd -' was 127 instead of 0.
sh: 1: agvtool: not found

INFO [2017-06-05 18:42:50.13]: Successfully generated documentation at path '/home/ubuntu/gaia-pro/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 💥   | increment_build_number              | 0           |
| 4    | slack                               | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-06-05 18:42:50.14]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Exit status of command 'cd /home/ubuntu/gaia-pro/ios && agvtool next-version -all && cd -' was 127 instead of 0.
sh: 1: agvtool: not found

URL: https://api.github.com/search/issues?q=Exit%20status%20of%20command%20'cd%20/home/ubuntu/gaia-pro/ios%20&&%20agvtool%20next-version%20-all%20&&%20cd%20-'%20was%20127%20instead%20of%200.%0Ash:%201:%20agvtool:%20not%20found%0A+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | debian_based jessie/sid                                         |
| Ruby                        | 2.2.6                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.11.0                                              |
| Installation Source         | ~/gaia-pro/vendor/bundle/ruby/2.2.0/bin/fastlane                |
| Host                        | Ubuntu 14.04.4 LTS debian_based jessie/sid (3.13.0-119-generic) |
| Ruby Lib Dir                | /opt/circleci/ruby/ruby-2.2.6/lib                               |
| OpenSSL Version             | OpenSSL 1.0.1f 6 Jan 2014                                       |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.36.0"

default_platform :ios

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/[TOKEN_OMITTED]"
    increment_build_number(xcodeproj: "./ios/GaiaPro.xcodeproj")
    cocoapods(podfile: "./ios")
  end

  #desc "Runs all the tests"
  #lane :test do
  #  scan
  #end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore", readonly: true) # more information: https://codesigning.guide
    gym(
      scheme: "GaiaPro",
      clean: true,
      workspace: "./ios/GaiaPro.xcworkspace"
    ) # Build your app - more options available
    testflight(skip_waiting_for_build_processing: true)

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    #increment_build_number(xcodeproj: "./ios/GaiaPro.xcodeproj")
    increment_version_number(
      xcodeproj: "./ios/GaiaPro.xcodeproj",
      bump_type: "minor" # Automatically increment minor version number
    )
    match(type: "appstore", readonly: true)
    snapshot
    gym(
      clean: true,
      workspace: "./ios/GaiaPro.xcworkspace",
      scheme: "GaiaPro"
    ) # Build your app - more options available
    deliver(force: true)

    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    clean_build_artifacts
    slack(message: "Successfully deployed new App Update.")
  end

  error do |lane, exception|
    slack(message: exception.message, success: false)
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "de.gaia-nutrition.gaia-pro" # The bundle identifier of your app
apple_id "benniwulff@hotmail.de" # Your Apple email address

team_id "LMQ5987ETU" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.14.6       |
| io-console                | 0.4.3        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.4        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-06-05**
</details>

**Comment by PetrosIchor** [comment]
This isn't specifically related to fastlane, but your in a Linux environment.  iOS applications require you to use OSX.  Apple's iOS tools only work on apple products.  You can't build in an Ubuntu environment.
