### ISSUE TITLE
Produce Apple 302 Detected

### ISSUE THREAD

**Issue by JeffreyGreenII** [fastlane/fastlane#9365]
### New Issue Checklist

- [✅ ] Updated fastlane to the latest version
- [✅ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Tried using fastlane produce for a new app. It looks like Apple has moved whatever page SpaceShip is trying to access. I traced back the page to being somewhere on the Developer Center from portal_client.rb:29:
      req = request(:post, "account/listTeams.action")

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[!] The request could not be completed because: (Spaceship::Client::AppleTimeoutError)
	Apple 302 detected
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/client.rb:516:in `with_retry'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/client.rb:671:in `send_request'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/client.rb:560:in `request'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/portal/portal_client.rb:29:in `teams'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/portal/ui/select_team.rb:49:in `select_team'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/portal/portal_client.rb:55:in `select_team'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/portal/spaceship.rb:37:in `select_team'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/spaceship/lib/spaceship/portal/spaceship.rb:86:in `select_team'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/produce/lib/produce/developer_center.rb:122:in `login'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/produce/lib/produce/developer_center.rb:36:in `run'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/produce/lib/produce/manager.rb:7:in `start_producing'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/produce/lib/produce/commands_generator.rb:34:in `block (2 levels) in run'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/produce/lib/produce/commands_generator.rb:140:in `run'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/produce/lib/produce/commands_generator.rb:11:in `start'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/jeffreygreen/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.36.0/bin/fastlane:20:in `<top (required)>'
	from /Users/jeffreygreen/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/jeffreygreen/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.36.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-05**
</details>

**Comment by nolanwilson** [comment]
Can you try running this again? During the WWDC keynote (and slightly afterwards), they had a redirect set up to send you to their maintenance page (which was recently removed). I was experiencing this issue as well but have since been able to create apps without running into this problem.

**Comment by JeffreyGreenII** [comment]
I have run again and it seems that it may be working. I included the team id with the -k flag, so I'm not sure which seemed to fix the issue.

**Comment by KrauseFx** [comment]
Hey everyone, if you find this via Google: This error means that Apple's web services are unavailable. If you're using match, you can use the `readonly` flag to not try to access the Apple back-end
