### ISSUE TITLE
New Subtitle field in iTunes Connect

### ISSUE THREAD

**Issue by mattrubin** [fastlane/fastlane#9375]
In addition to [the new "Promotional Text" field](https://github.com/fastlane/fastlane/pull/9370), iTunes Connect recently added a "Subtitle" field for "A summary of your app that will appear under your app’s name on the App Store for customers with devices running iOS 11 or later."

**Comment by diachini** [comment]
I believe this should be able to be closed per https://github.com/fastlane/fastlane/pull/9396

**Comment by ohayon** [comment]
I think youre right @diachini thanks! :rocket:
