### ISSUE TITLE
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by tringManoj** [fastlane/fastlane#9378]
I have integrated Fastlane On Jenkins. Fastlane Could not download the repo. It throws following error.

```

- [ ] fatal: could not read Username for 'https://github.com': terminal prompts disabled
- [ ] 02:00:17 [02:00:17]: Exit status: 128
- [ ] 02:00:17 [02:00:17]: Error cloning repo, please make sure you have read access to the repository you want to use
- [ ] 02:00:17 [02:00:17]: Run the following command manually to make sure you're properly authenticated:

```

But everything works fine when Fastlane is Run on Terminal. Am I missing something? 

Note:- Fastlane's Lane triggered via Jenkin works fine in Generating IPA etc but It cannot download or clone the REPO from GIT.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by PetrosIchor** [comment]
Without any information on your setup, it's hard to diagnose your issue. This sounds like the build machine doesn't have credentials to your scm.  Likely due to Jenkins shell environment for your job.

**Comment by tringManoj** [comment]
Jenkins is set with all credentials. Jenkins Can download my source code repo. But Fastlane could not clone the Certificate Repo when Run Via Jenkins Shell. 
Same works when Fastlane is run on Terminal.

**Comment by PetrosIchor** [comment]
Yeah, that's because fastlane doesn't have the git credentials.  My guess is Jenkins does, but the session fastlane is running in does not.  If it will run on the same machine manually, then it's in the system keychain.  You need to either unlock the keychain or provide the credentials via jenkins.

Personally, id use ssh.  Https is a pain to deal with in CI environments from my experience.

**Comment by GoodMirek** [comment]
I would also suggest to use ssh and private key.

**Comment by wanyakun** [comment]
Add unlock_keychain action in before_all. 

- first, check the login keychain name in `~/Library/Keychains/` folder.
- add the following code in before_all section. 

```ruby
    unlock_keychain(path: "login.keychain-db",
                    password:ENV['MAC_USER_PASSWORD'])
```

**Comment by tringManoj** [comment]
Got it working now.
Uninstalled Jenkins. Installed it via brew. It works now. Too strange though. Did the same when installed via package installer it did not work..
