### ISSUE TITLE
QUESTION: add certificate into match manually

### ISSUE THREAD

**Issue by navratill** [fastlane/fastlane#9379]
Hello!

I would like to ask, if (and how) is possible to add certificate with provision profile into match manually, that match will not create new pair in developer.apple.com portal. Because even when certificate and right provision profile is already in dev portal, match will still generate new ones.

What I see, It should be somehow possible, thank you!

**Comment by PetrosIchor** [comment]
Please read the docs for information regarding fastlane actions and plugins.  https://docs.fastlane.tools

Check out cert and sigh. They'll meet your needs.

**Comment by navratill** [comment]
@PetrosIchor Thanks for response, I saw all these options and they are not that good as match solution. 

So I was wonder, if it is not possible do it with it...basically everything what is needed is to manually place it into git repo and encrypt it (am I wrong?).

**Comment by Fluzzarn** [comment]
Here's a blog post I have saved to do this since I occasionally have to do this
http://macoscope.com/blog/simplify-your-life-with-fastlane-match/

**Comment by navratill** [comment]
I found in source codes this:
Encrypt.new.clear_password(params[:git_url])
Encrypt.new.store_password(params[:git_url], to)

**Comment by navratill** [comment]
@Fluzzarn amazing, thank you so much, it looks that you hit the point. Thank you!
