### ISSUE TITLE
gradle / supply example

### ISSUE THREAD

**Issue by rompic** [fastlane/fastlane#938]
is there any more detailed information about the gradle action and supply available? e.g. an example?

**Comment by asfalcone** [comment]
The gradle action [documentation](https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md#gradle) has recently been updated. 

You can call `gradle` then `supply` from your lane like this:
```ruby
gradle(
  task: 'assembleRelease'
)
supply(
  apk: lane_context[SharedValues:: GRADLE_APK_OUTPUT_PATH]
) 
```

Thanks!
