### ISSUE TITLE
Xcode 9.0 (beta) support

### ISSUE THREAD

**Issue by dennisfrett** [fastlane/fastlane#9380]
Currently, it seems like Xcode 9.0 beta version is not supported:

> 2017-06-06 14:02:41.579 xcodebuild[36176:463668] [MT] IDEDistribution: Step failed: <IDEDistributionSigningAssetsStep: 0x7fff3691e600>: Error Domain=IDEDistributionSigningAssetStepErrorDomain Code=0 "Locating signing assets failed." UserInfo={NSLocalizedDescription=Locating signing assets failed., IDEDistributionSigningAssetStepUnderlyingErrors=(
> "Error Domain=IDEProvisioningErrorDomain Code=9 \"\"FoodTracker.app\" requires a provisioning profile.\" UserInfo={NSLocalizedDescription=\"FoodTracker.app\" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the \"Default\" build configuration in the project editor.}"
> )}
> error: exportArchive: "FoodTracker.app" requires a provisioning profile.
> 
> Error Domain=IDEProvisioningErrorDomain Code=9 ""FoodTracker.app" requires a provisioning profile." UserInfo={NSLocalizedDescription="FoodTracker.app" requires a provisioning profile., NSLocalizedRecoverySuggestion=Select a provisioning profile for the "Default" build configuration in the project editor.}

Provisioning profile is set correctly. If I do `xcode-select -s` to Xcode 8.3.2, it finishes without a problem.

** EXPORT FAILED **
[14:02:41]: Exit status: 70

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.4                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.12.2                               |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.12.4 (16E195)                        |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | false                                            |
| Is homebrew                 | true                                             |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-06**
</details>

**Comment by ZevEisenberg** [comment]
I'm getting a similar failure (#9401) with Xcode 8.3.3 `xcode-select`ed. Haven't tried with 8.3.2, since I'm trying to support the new 10.5-inch iPad Pro, which requires 8.3.3.

**Comment by mpirri** [comment]
Thanks for letting us know about this, @dennisfrett.  I have confirmed this is happening in Xcode 9 beta on my system.  I am unable to reproduce this issue on Xcode 8.3.3 currently.

Digging into this further, will let you know as soon as we know more!

**Comment by dennisfrett** [comment]
Ok, @mpirri, thanks!

**Comment by hdoria** [comment]
Same problem on Xcode 9.

I'm getting the following error: "App requires a provisioning profile with the Push Notifications, App Groups, and Data Protection features. "

Product - Archive from Xcode 9 works fine.

**Comment by eriklamanna** [comment]
I had the same problem. It appears that there is either new or different export plist options needed for the build to work properly. I was able to add the keys for iCloudContainerEnvironment, teamID, and provisioningProfiles to the export_options. Final export options looked like

**Comment by KrauseFx** [comment]
Hey everyone, it seems like we now have to specify the provisioning profile to use for each target when exporting the binary. This is great news, as it gives us more control over what profile to use. We're going to implement this into _fastlane_ next week, we don't want to rush thing, but make sure that we do everything right 👍

**Comment by KrauseFx** [comment]
Ha, thanks for sharing this @eriklamanna, this already works. I'll update _fastlane_ to make it work automatically if you use _match_ 👍

**Comment by KrauseFx** [comment]
Have you had a chance to try the most recent release if you use match? I also just started https://github.com/fastlane/fastlane/pull/9460, which will be in the next release 👍

**Comment by dennisfrett** [comment]
Hi @KrauseFx, on most of our project, it works now. There are still some projects left that give the same error.

**Comment by triplef** [comment]
Despite running fastlane 2.48.0 containing this fix, I’m still getting the following error trying to build with Xcode 9:

> exportOptionsPlist error for key 'iCloudContainerEnvironment': expected one of {Development, Production}, but no value was provided

It looks like fastlane never sets iCloudContainerEnvironment, however I can build just fine calling `gym` like this:

```ruby
gym(export_options: {iCloudContainerEnvironment: 'Development']}) # or 'Production'
```

Any idea why this might be the case?

**Comment by mpirri** [comment]
@triplef do you mind opening a new issue for your problem? I'm not confident the problem you are encountering is the same as the original poster, and I think we'd like to have a look at your _fastlane_ environment. If it turns out it is the same issue, that isn't a problem either!

Thanks so much! 🚀

**Comment by ryang1428** [comment]
I am still seeing this issue in Xcode 9 beta 6. Archives fine locally-- but fails with these same errors when running `gym`. @davidchristiandy I see you maybe fixed this in a fork last week? Should I create a new issue? Anyone else experiencing this still?

**Comment by wzhifang** [comment]
If you use automatic packaging, you can use your xcode export exporting Options.plist into the automatic packaging folder, and then you can succeed

**Comment by wzhifang** [comment]
If you use automatic packaging, you can use your xcode export ExportOptions.plist into the automatic packaging folder, and then you can automatically pack successfully

**Comment by wzhifang** [comment]
I encountered the same problem, my solution is to export xcode derived ExportOptions.plist into the automatic packaging folder, and then automatically packaged successfully

**Comment by vchirino** [comment]
Hey @wzhifang, can you provide more info about your solution? I'm still having the issue with Xcode 9! Thanks

**Comment by garyhooper** [comment]
@wzhifang, I am having the same problem. What does your revised ExportOptions.plist now look like?

**Comment by wzhifang** [comment]
@garyhooper ,@vchirino, Do you have a problem with automatic packing or a problem with xcode9? I was automatically packaged with the problem, and then packaged out with the xuode.plist file to replace the automatic packaging inside, export options looked like
`<plist version="1.0">
<dict>
	<key>compileBitcode</key>
	<false/>
	<key>method</key>
	<string>development</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>com.example.app</key>
		<string>com.example.app.dev</string>
	</dict>
	<key>signingCertificate</key>
	<string>iPhone Developer</string>
	<key>signingStyle</key>
	<string>manual</string>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>teamID</key>
	<string>your teamID</string>
	<key>thinning</key>
	<string>&lt;none&gt;</string>
</dict>
</plist>`

**Comment by garyhooper** [comment]
@wzhifang, I am trying to use automatic signing with Xcode 9. (Xcode 8.3 worked perfectly.)  I will try manual signing with your example. Thank you. (Note that I am calling `xcodebuild` directly, not via fastlane, but the problem is the same.)

Automatic should still work in Xcode 9 according to Apple.  The following also describes what I am seeing using `xcodebuild -allowProvisioningUpdates`: https://stackoverflow.com/questions/46295291/allowprovisioningupdates-doesnt-work
