### ISSUE TITLE
Review potential issue with 10.13 fork/exec

### ISSUE THREAD

**Issue by milch** [fastlane/fastlane#9383]
According to [this link](http://sealiesoftware.com/blog/archive/2017/6/5/Objective-C_and_fork_in_macOS_1013.html) the behavior of fork/exec will change in 10.13 because of the Objective-C runtime, and this could *potentially* affect scripting languages that rely on the old behavior in the background (they explicitly mention python but ruby having the same issue is not far-fetched). 

Since fastlane uses fork and exec my hunch is that as soon as people start using fastlane on 10.13 and update their ruby with ruby-build on 10.13, they are going to start to run into problems. Bundled fastlane should only be affected once build machines start upgrading to 10.13. 

An environment variable is mentioned in the above post as a workaround. We should keep this in mind and if there is a problem on 10.13 potentially set this early on when fastlane starts.

**Comment by hjanuschka** [comment]
thats sad, thx for your great find, definitly worth an eye😨 
i once tried windows port, and replaced all fork's with `Thread.new` -> https://github.com/fastlane/fastlane/pull/7202

there should'nt be so many forks inside the fastlane codebase.
on  most places we use  `PTY.spawn`  from a quick look it ends here: https://svn.ruby-lang.org/cgi-bin/viewvc.cgi/trunk/io.c?view=markup#l6149

which should end up using `posix_spawn` if i am not on a wrong path.
