### ISSUE TITLE
Generation of ipa failure

### ISSUE THREAD

**Issue by caoyunxiao** [fastlane/fastlane#9384]
<img width="721" alt="2017-06-06 22 47 28" src="https://cloud.githubusercontent.com/assets/15682437/26835198/4d31caf0-4b0a-11e7-92a6-6d6207837820.png">
From the terminal information as you can see there is a problem？

**Comment by caoyunxiao** [comment]
The format of the lane is not correct?


  lane :inHouse do
  gym(
    workspace: "Lighting.xcworkspace",
    scheme: "Lighting",
    clean: true,
    output_directory: "/Users/caoyunxiao/Desktop/Opple图标", 
    export_method: "ad-hoc",
    output_name: "my-app.ipa"  
)

  end

**Comment by caoyunxiao** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.4                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.11.0 (Apple Git-81)                |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.12.4 (16E195)                        |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | true                                             |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode8.3.2.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "企业版"
  lane :inHouse do
  gym(
    workspace: "Lighting.xcworkspace",
    scheme: "Lighting",
    clean: true,
    output_directory: "/Users/caoyunxiao/Desktop/Opple图标", 
    export_method: "ad-hoc",
    output_name: "my-app.ipa"  
)

  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.gomore.opple" # The bundle identifier of your app
apple_id "1105938518@qq.com" # Your Apple email address

team_id "W54V2VB863" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.8        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.3        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-06-06**
</details>

**Comment by hugweb** [comment]
Hi ! I can't deploy either since this morning and I can't figure out why.

<img width="1920" alt="screen shot 2017-06-06 at 17 28 18" src="https://user-images.githubusercontent.com/439516/26837774-95e5a680-4ade-11e7-9a37-0e71d406014f.png">

When I check the log I can see : ** ARCHIVE SUCCEEDED ** but no specific error !

**Comment by caoyunxiao** [comment]
You and I, if you solve the tell me please

**Comment by mpirri** [comment]
Do you mind running the _fastlane_ command with the `--verbose` command line option?  So, for instance, run `fastlane beta --verbose`. Include the output of that command in this ticket and it should help us understand a bit more about what is going on here.

**Comment by hugweb** [comment]
That's why I did @mpirri 
<img width="1669" alt="screen shot 2017-06-06 at 23 56 21" src="https://user-images.githubusercontent.com/439516/26853856-f606fc96-4b13-11e7-8814-1e9d5dfccb39.png">

Here is my line 140 :
<img width="517" alt="screen shot 2017-06-06 at 23 57 05" src="https://user-images.githubusercontent.com/439516/26853865-04a85fa6-4b14-11e7-8a43-c56145c4af4b.png">

**Comment by caoyunxiao** [comment]
In the above I gave fastlane details

**Comment by hugweb** [comment]
@caoyunxiao Did you find a solution?

**Comment by caoyunxiao** [comment]
Yes, I reinstall the budle, changed the export_method for 'enterprise'
