### ISSUE TITLE
disable_automatic_code_signing messes up code signing identities

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/fastlane#9385]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to use automatic signing for development and manual signing for `Release` build configurations.  I have my certs setup in Xcode like this:

<img width="521" alt="screen shot 2017-06-06 at 9 53 06 am" src="https://user-images.githubusercontent.com/7799267/26841310-f8f51a1c-4a9d-11e7-8e63-e13943651256.png">

And I have automatic provisioning turned on.  I then call these fast lane actions when trying to deploy a `Release` to iTunes Connect with pilot:

```ruby
match(type: "appstore")
disable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])
gym(scheme: "SchemeName")
enable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])
pilot(skip_waiting_for_build_processing: true)
```

but then the build fails with:

```
❌  Provisioning profile "match AppStore com.company.AppName" doesn't include signing certificate "iPhone Developer: Company Name (XXXXXXXX)".
[10:36:00]: ▸ ❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'
[10:36:00]: ▸ ❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'
```
Which is weird because I specified in Xcode to use Distribution certs for `Release` builds.  So I opened the workspace on the CI machine (Running Jenkins) and found that the `disable_automatic_code_signing` action sets the certs all to developer certs and resets the setting I set to use Distribution certs

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.36.0"

default_platform :ios

platform :ios do
  before_all do
    # carthage(platform: "iOS", cache_builds: true)
    setup_jenkins
  end

  desc "Installs Carthage dependencies"
  lane :carthage_install do
    carthage(platform: "iOS", cache_builds: true)
  end

  desc "Runs all the tests"
  lane :test do
    scan(scheme: "SchemeName", slack_only_on_failure: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    increment_build_number(
      build_number: ENV["APP_BUILD_NUMBER"],
      xcodeproj: ENV["APP_XCODEPROJ"]
    ) # set a specific number
    match(type: "appstore") # more information: https://codesigning.guide
    disable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])
    gym(scheme: "SchemeName") # Build your app - more options available
    enable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])
    pilot(skip_waiting_for_build_processing: true)
    slack(message: "Deployed build v#{ENV['APP_VERSION_NUMBER']} (#{ENV['APP_BUILD_NUMBER']}) to iTunes Connect!")
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    increment_build_number(
      build_number: ENV["APP_BUILD_NUMBER"],
      xcodeproj: ENV["APP_XCODEPROJ"]
    ) # set a specific number    match(type: "appstore")
    # snapshot
    match(type: "appstore") # more information: https://codesigning.guide
    disable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])
    gym(scheme: "SchemeName") # Build your app - more options available
    enable_automatic_code_signing(path: ENV["APP_XCODEPROJ"])
    deliver(force: true)
    # frameit
    slack(message: "Deployed build v#{ENV['APP_VERSION_NUMBER']} (#{ENV['APP_BUILD_NUMBER']}) to iTunes Connect!")
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    ## Prevent Spam to Slack
    # slack(
    #   message: "Build Successfull!"
    # )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.company.AppName" # The bundle identifier of your app
apple_id "buildmeister@company.com" # Your Apple email address

team_id "XXXXXXXXX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-06**
</details>

**Comment by PetrosIchor** [comment]
Run the action and see how it changes the project. Then adjust your automation to work with that flow.  Disabling xcodeshortcuts auto sign requires more than just turning it off.  When you disable it, you then need to provide all signing assets to the project, including the identity.
