### ISSUE TITLE
build notes

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#939]
i am getting this error

```
Fastfile:68:in `submit_to_fabric': uninitialized constant Fastlane::Actions::SharedValues::LOAD_BUILD_NOTES_FILE_PATH (NameError)
```

is the file should be created automatically ? or i have to explicitly create it.

**Comment by KrauseFx** [comment]
Did you copy `LOAD_BUILD_NOTES_FILE_PATH` from the TouchWonders example? Maybe @fabiomassimo wants to jump in on that?

@romk1n what do you want to achieve? Please share your `Fastfile` and any custom actions you added.

**Comment by fabiomassimo** [comment]
@romk1n it seems that maybe you did not import the build notes custom action which is in the example folder. Please share your Fastfile and I'll do my best to help you out.

**Comment by romk1n** [comment]
@fabiomassimo @KrauseFx my apologies i thought it is built in for some reason!
