### ISSUE TITLE
IMG_BAD_DIMENSIONS error when updating IAP.

### ISSUE THREAD

**Issue by mkimi-lightricks** [fastlane/fastlane#9390]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When modifying iap by uploading a `review_screenshot` [image](https://user-images.githubusercontent.com/20626100/26850877-bedf5a6c-4b11-11e7-882c-4c6c9dc04ea5.png), I'm getting `IMG_BAD_DIMENSIONS` error.

When uploading the same image manually to iTunesConnect, the IAP is being saved successfully.

Image size (750x1334) is aligned with [Apple's requirements](https://developer.apple.com/library/content/documentation/LanguagesUtilities/Conceptual/iTunesConnect_Guide/Chapters/Properties.html#//apple_ref/doc/uid/TP40011225-CH26-SW2). 

The command's log:

```
michaelkimyagarov@MKimi-MBP:Users/michaelkimyagarov$ fastlane spaceship
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
Username: mkimi@lightricks.com
Logging into to iTunes Connect (mkimi@lightricks.com)...
Successfully logged in to iTunes Connect

Logging into the Developer Portal (mkimi@lightricks.com)...
Successfully logged in to the Developer Portal

---------------------------------------
| Welcome to the spaceship playground |
---------------------------------------

Enter docs to open up the documentation
Enter exit to exit the spaceship playground
Enter _ to access the return value of the last executed command

Just enter the commands and confirm with Enter
[1] pry(#<Spaceship::Playground>)> app = Spaceship::Tunes::Application.find("com.lightricks.Enlight-Editor-Playground")
=> <Spaceship::Tunes::Application
	apple_id="1191418545",
	name="Enlight Editor Playground",
	vendor_id="Enlight-Editor-Playground",
	bundle_id="com.lightricks.Enlight-Editor-Playground",
	last_modified=1496278253000,
	issues_count=0,
	app_icon_preview_url=nil,
	version_sets=[<Spaceship::Tunes::VersionSet
		type="APP",
		application=<Spaceship::Tunes::Application
		#<Object ...>>,
		platform="ios">]>
[2] pry(#<Spaceship::Playground>)> purchase = app.in_app_purchases.all.first.edit
=> <Spaceship::Tunes::IAPDetail
	application=<Spaceship::Tunes::Application
		apple_id="1191418545",
		name="Enlight Editor Playground",
		vendor_id="Enlight-Editor-Playground",
		bundle_id="com.lightricks.Enlight-Editor-Playground",
		last_modified=1496278253000,
		issues_count=0,
		app_icon_preview_url=nil,
		version_sets=[<Spaceship::Tunes::VersionSet
			type="APP",
			application=<Spaceship::Tunes::Application
			#<Object ...>>,
			platform="ios">]>,
	purchase_id="1242314667",
	is_news_subscription=false,
	reference_name="EnlightEditorPlayground.kimi.test_pid",
	product_id="com.lightricks.EnlightEditorPlayground.kimi.test_pid",
	subscription_free_trial=nil,
	subscription_duration=nil,
	cleared_for_sale=true,
	review_screenshot=nil,
	review_notes=nil,
	subscription_price_target=nil>
[3] pry(#<Spaceship::Playground>)> purchase.review_notes = "some long long note, more than 10 chars"
=> "some long long note, more than 10 chars"
[4] pry(#<Spaceship::Playground>)> purchase.review_screenshot = "/Users/michaelkimyagarov/Downloads/black_iap.png"
=> "/Users/michaelkimyagarov/Downloads/black_iap.png"
[5] pry(#<Spaceship::Playground>)> purchase.save!
Spaceship::Client::UnexpectedResponse: [IMG_BAD_DIMENSIONS] The image dimensions are not supported. Please adjust to acceptable dimensions and re-save it.
from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.37.0/spaceship/lib/spaceship/du/du_client.rb:127:in `parse_upload_response'
[6] pry(#<Spaceship::Playground>)>
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.12.0                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Library/Developer/CommandLineTools/                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.56.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| claide                    | 1.0.2        |
</details>

*generated on:* **2017-06-06**
</details>

**Comment by mkimi-lightricks** [comment]
@hjanuschka

**Comment by hjanuschka** [comment]
right now the current implemantion only supports uploading review screenshots in 640x920.
i have this on my todolist to support the other formats, but have not yet found time to do it.

if you want to jump in and do a PR for this, i am more than happy to guide you threw.

**Comment by mkimi-lightricks** [comment]
Thanks, it worked.

About a PR, I think I can do it.

Since these screenshots aren't seen by end users (they are only required by Apple's reviewing team) I think there's no need to support every possible screenshot size. Throwing more descriptive error message when uploading a screenshot of size different than 640x920, to my opinion, will be enough.

**Comment by hjanuschka** [comment]
@mkimi-lightricks sounds like a plan! feel free to direct mention me in the PR 👍
