### ISSUE TITLE
Use fastlane for an app contained in a workspace alongside other projects.

### ISSUE THREAD

**Issue by BigSauce** [fastlane/fastlane#9391]
I have an app that is a project contained in a workspace.  The workspace contains a framework project and the app project, as well as some Cocoapod projects that got there using `pod install`.

I was wondering what I might need to do to get fastlane to use the correct project when running.

Thanks for any help!

**Comment by PetrosIchor** [comment]
Examples: https://github.com/fastlane/examples
Docs: https://docs.fastlane.tools

You described a standard project.  Evaluate your projects needs, research fastlanes toolset, and then make a decision if it's the right tool for you.  

The issues board isn't the best place to ask such vague questions.  It's a space for bugs, feature updating, and evolving platform changes.  Fastlanes a powerful set of tools with an even bigger plugin community.  I use it beyond mobile to manage a number of automation tasks both professionally and personally.

**Comment by BigSauce** [comment]
I noticed that other repos allow for general questions as issues.  Apologies, and thanks for your response, @PetrosIchor.

I use fastlane for most of my projects already, but most of them don't contain embedded framework projects.

I'll figure it out.

**Comment by getaaron** [comment]
@BigSauce For CocoaPods, you'll want to use the `cocoapods` fastlane action to run `pod install`.

Then you need to make sure your project has a correct [Xcode Scheme](https://developer.apple.com/library/content/featuredarticles/XcodeConcepts/Concept-Schemes.html) that represents what you want to build. If you're using a standard CocoaPods setup, your scheme name is probably your target or app's name.

If your project has multiple schemes then you can select one when you run fastlane, or you can hardcode one into your Fastfile by passing it to the relevant actions, for example:

```ruby
  lane :test do
    cocoapods
    scan(scheme: 'AppName', device: 'iPhone 7')
    xcov(scheme: 'AppName', ignore_file_path: 'ignore_xcov') 
  end
```

**Comment by KrauseFx** [comment]
Thanks everyone, closing this now 👍
