### ISSUE TITLE
app_store_build_number shouldn't parse build_version as an integer

### ISSUE THREAD

**Issue by richardszalay** [fastlane/fastlane#9392]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

🔑 `app_store_build_number` parses the build's `build_version` as an integer before returning it, but there's no guarantee that the value will be an integer.

This has the impact of only returning a subset of the data when the `build_version` is a version string. For example, if builds are timestamped ("2017.607"), `app_store_build_number` will return `2017`.

Would you accept a PR that changes `app_store_build_number` to return the full `build_version` rather than attempting to parse it as an integer?

**Comment by sinoru** [comment]
Yeah, It will be nice if my PR(#9153) merges soon.
