### ISSUE TITLE
Resign does not sign frameworks?

### ISSUE THREAD

**Issue by viezel** [fastlane/fastlane#9393]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We have a White label app that we build once, and then use `act` to change configs, assets, info.plist. We use `act` and `resign` to create new IPAs for clients. But it does not work as expected. First we run our `act` and `resign` lane:

```ruby
# Modify Info.plist and app icons
act(
  ipa: ipaClient,
  iconset: iconSet + "/AppIcon.appiconset",
  plist_values: {
    ":CFBundleDisplayName" => ENV["APP_NAME"],
    ":CFBundleIdentifier" => ENV["APP_IDENTIFIER"],
  }
)

# Modify the GoogleService plist
act(
  ipa: ipaClient,
  plist_file: "GoogleService-Info.plist",
  plist_values: {
    ":BUNDLE_ID" => ENV["APP_IDENTIFIER"],
    ":TRACKING_ID" => ENV["APP_TRACKING_ID"],
    ":PROJECT_ID" => ENV["APP_PROJECT_ID"],
    ":GOOGLE_APP_ID" => ENV["APP_GOOGLE_APP_ID"]
  }
)

# resign the app
resign(
  ipa: ipaClient,
  signing_identity: "iPhone Distribution: XXX",
  provisioning_profile: clientProvision,
  bundle_id: ENV["APP_IDENTIFIER"],
  display_name: ENV["APP_NAME"],
)

# deploy
deliver(
  username: ENV["APPLE_ID"],
  force: false,
  ipa: ipaClient
)
```

The output:

```
[21:10:50]: DONE LOADING THE CONFIG.JSON FILE ✅ 
[21:10:51]: ---------------------------------------------------------------------------------------
[21:10:57]: ---------------------
[21:10:57]: --- Step: appicon ---
[21:10:57]: ---------------------
[21:11:00]: Successfully stored app icon at '/myapp/Assets.appiconset/AppIcon.appiconset'
[21:11:00]: -----------------
[21:11:00]: --- Step: act ---
[21:11:00]: -----------------
[21:11:00]: Patching Plist: Info.plist
[21:11:00]: Patching icons from: /myapp/Assets.appiconset/AppIcon.appiconset
[21:11:01]: -----------------
[21:11:01]: --- Step: act ---
[21:11:01]: -----------------
[21:11:02]: Patching Plist: GoogleService-Info.plist
[21:11:02]: --------------------
[21:11:02]: --- Step: resign ---
[21:11:02]: --------------------
/Users/napp/.rvm/gems/ruby-2.3.3/gems/fastlane-2.37.0/sigh/lib/assets/resign.sh /myapp.ipa 34C7223BE315EA09E0978FADC1EE34CBDBBD7BD7 -p /myapp.mobileprovision   -d \MyApp     -b 'com.myapp'  /myapp.ipa
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
_floatsignTemp/Payload/myapp.app/Frameworks/Alamofire.framework: replacing existing signature
_floatsignTemp/Payload/myapp.app/Frameworks/AlamofireObjectMapper.framework: replacing existing signature
_floatsignTemp/Payload/myapp.app/Frameworks/Bugsnag.framework: replacing existing signature
rm: _floatsignTemp/old-embedded-profile.plist: No such file or directory

[21:11:15]: Successfully signed /myapp.ipa!
[21:11:15]: Successfully re-signed .ipa 🔏.
```

Now everything is green, but when I deploy to iTunes Connect, it fails:

```
Uploading binary to iTunes Connect
Going to upload updated app to iTunes Connect
This might take a few minutes. Please don't interrupt the script.
Return status of iTunes Transporter was 1: 

ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/myapp.app/Myapp' must be signed with the certificate that is contained in the provisioning profile."
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/myapp.app/Frameworks/AeroGearPush.framework/AeroGearPush' must be signed with the certificate that is contained in the provisioning profile."
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/myapp.app/Frameworks/Alamofire.framework/Alamofire' must be signed with the certificate that is contained in the provisioning profile."
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/myapp.app/Frameworks/AlamofireObjectMapper.framework/AlamofireObjectMapper' must be signed with the certificate that is contained in the provisioning profile."
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/myapp.app/Frameworks/Bugsnag.framework/Bugsnag' must be signed with the certificate that is contained in the provisioning profile."

The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

Could not upload binary to iTunes Connect. Check out the error above
```

Ive inspected the IPA that was resigned and the `embedded.mobileprovision` is correct. Its the client own provision. So what is wrong here? 
We have tried a lot of different methods to get this working - so any hints would be awesome! 

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                                     | Version | Update-Status      |
| ------------------------------------------ | ------- | ------------------ |
| fastlane-plugin-appicon                    | 0.6.0   | ✅ Up-To-Date       |
| fastlane-plugin-update_project_codesigning | 0.2.0   | ✅ Up-To-Date       |
| fastlane-plugin-update_xcodeproj           | 0.1.2   | ✅ Up-To-Date       |
| fastlane-plugin-act                        | 1.0.1   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                                        | Version      |
| ------------------------------------------ | ------------ |
| did_you_mean                               | 1.0.0        |
| executable-hooks                           | 1.3.2        |
| bundler-unload                             | 1.0.2        |
| rubygems-bundler                           | 1.4.4        |
| bundler                                    | 1.14.6       |
| io-console                                 | 0.4.5        |
| CFPropertyList                             | 2.3.5        |
| public_suffix                              | 2.0.5        |
| addressable                                | 2.5.1        |
| babosa                                     | 1.0.2        |
| claide                                     | 1.0.1        |
| colored                                    | 1.2          |
| colored2                                   | 3.1.2        |
| highline                                   | 1.7.8        |
| commander-fastlane                         | 4.4.4        |
| unf_ext                                    | 0.0.7.4      |
| unf                                        | 0.1.4        |
| domain_name                                | 0.5.20170404 |
| dotenv                                     | 2.2.1        |
| excon                                      | 0.56.0       |
| multipart-post                             | 2.0.0        |
| faraday                                    | 0.12.1       |
| http-cookie                                | 1.0.3        |
| faraday-cookie_jar                         | 0.0.6        |
| faraday_middleware                         | 0.11.0.1     |
| fastimage                                  | 2.1.0        |
| gh_inspector                               | 1.0.3        |
| jwt                                        | 1.5.6        |
| little-plugger                             | 1.1.4        |
| multi_json                                 | 1.12.1       |
| logging                                    | 2.2.2        |
| memoist                                    | 0.15.0       |
| os                                         | 0.9.6        |
| signet                                     | 0.7.3        |
| googleauth                                 | 0.5.1        |
| httpclient                                 | 2.8.3        |
| hurley                                     | 0.2          |
| mime-types-data                            | 3.2016.0521  |
| mime-types                                 | 3.1          |
| uber                                       | 0.0.15       |
| representable                              | 2.3.0        |
| retriable                                  | 2.1.0        |
| google-api-client                          | 0.9.28       |
| json                                       | 1.8.3        |
| mini_magick                                | 4.5.1        |
| multi_xml                                  | 0.6.0        |
| plist                                      | 3.3.0        |
| rubyzip                                    | 1.2.1        |
| security                                   | 0.1.3        |
| slack-notifier                             | 1.5.1        |
| terminal-notifier                          | 1.8.0        |
| unicode-display_width                      | 1.2.1        |
| terminal-table                             | 1.8.0        |
| tty-screen                                 | 0.5.0        |
| word_wrap                                  | 1.0.0        |
| nanaimo                                    | 0.2.3        |
| xcodeproj                                  | 1.4.4        |
| rouge                                      | 2.0.7        |
| xcpretty                                   | 0.2.8        |
| xcpretty-travis-formatter                  | 0.0.4        |
| fastlane-plugin-act                        | 1.0.1        |
| fastlane-plugin-appicon                    | 0.6.0        |
| fastlane-plugin-update_project_codesigning | 0.2.0        |
| fastlane-plugin-update_xcodeproj           | 0.1.2        |
| spare_keys                                 | 1.2.0        |
</details>

</details>

**Comment by viezel** [comment]
yes bot - I did. Any humans around 😄

**Comment by viezel** [comment]
cc @mgrebenets as you are the resign hero 👍

**Comment by mgrebenets** [comment]
@viezel At first I thought it was because you frameworks may not share the common bundle ID prefix with main app and extensions. But then I realized that since Xcode 8 code signing for frameworks is no longer required.

In your case, as far as I can tell, it's not just about frameworks.
The very first iTC error message is this:

```
ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/myapp.app/Myapp' must be signed with the certificate that is contained in the provisioning profile."
```

So it's not just frameworks, but there are code signing issues with the main binary as well.

I can see that your are using a simple `-p profile.file` option and a `-b 'new-bundle-id'`.
Those are from the line that calls `resign.sh` shell script, and they come from the way you use `resign` action in Ruby:

```ruby
   bundle_id: ENV["APP_IDENTIFIER"],
  display_name: ENV["APP_NAME"],
```

Could you try to use resign action in another way?
I would recommend to avoid providing explicit bundle ID (`bundle_id`) if possible.
The thing is that your new provisioning profile already contains new bundle ID. So the resign script will figure it out.

Also, you can use a hash for the `provisioning_profile` option.
For example:

```ruby
provisioning_profile: {
  "old-bundle-id" => "path/to/new/provisioning-profile.mobileprovision",
  "old-nested-app-bundle-id" => "path/to/new/nested-app-profile.mobileprovision"
}
```

You basically say "to resign binary with this bundle ID use this provisioning profile".

That's better than using `bundle_id` option, because `bundle_id` option does not support nested apps and/or extensions. So it's not future proof.

The shell script under the hood of `resign` action will figure out new bundle ID(s) by reading them from the provisioning profile you have specified.

Same for using `display_name` parameter. You have already replaced it using `act`, so you don't really need to specify it again for `resign` action.

I actually believe that `bundle_id` and `display_name` are more harmful than helpful, because as soon as you have a nested app (e.g. WatchKit app) or extension, the resigning approach with `bundle_id` option will not work.

**Comment by viezel** [comment]
@mgrebenets awesome let me try this out.

**Comment by viezel** [comment]
I changed it to what you have suggested here, but it still does not work. Both the app and the frameworks are getting the `ITMS-90179` error. 

is there any way where I can tell resign not to sign the frameworks?

**Comment by viezel** [comment]
@mgrebenets any other ideas?
