### ISSUE TITLE
Gym : Error packaging up the application

### ISSUE THREAD

**Issue by hugweb** [fastlane/fastlane#9395]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

<img width="1658" alt="screen shot 2017-06-07 at 11 36 47" src="https://user-images.githubusercontent.com/439516/26873222-5a7b6300-4b79-11e7-9390-3940dba8381e.png">

### Environment

<summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.5                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.11.0 (Apple Git-81)               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                        |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 8.3.3                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

default_platform :ios

platform :ios do
   
    # FolioBeta
    lane :beta do |values|
        
        ensure_git_branch(branch: "develop")
        
        cocoapods
        pem
        cert
        refresh
        match(type: "adhoc", app_identifier: "com.folioapp.dev", force_for_new_devices: true)
        increment_build_number

        gym(scheme: "FolioBETA",
            workspace: "Folio.xcworkspace",
            clean: true,
            include_bitcode: false,
            xcargs: "ARCHIVE=YES")
            
        crashlytics(api_token: "********************",
            build_secret: "******************",
            groups: ["folio", "externals"],
            notes: change_log(),
            notifications: true)

    end

end

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                   | Version | Update-Status |
| ------------------------ | ------- | ------------- |
| fastlane-plugin-git_tags | 0.1.1   | ✅ Up-To-Date  |

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.56.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.0       |
| faraday_middleware        | 0.11.0.1     |
| fastlane-plugin-git_tags  | 0.1.1        |

**Comment by hugweb** [comment]
Nobody got this issue?

**Comment by KrauseFx** [comment]
Sorry for the late reply. You didn't share the complete build output.

**Comment by besi** [comment]
I am getting this issue too when I used `fastlane beta --verbose`. I guess fastlane is looking for a method or a symbol called `verbose` in my case.

**Comment by KrauseFx** [comment]
Yep, without the complete output we can't help, sorry
