### ISSUE TITLE
 `require': cannot load such file -- spaceship (LoadError)

### ISSUE THREAD

**Issue by wulin9005** [fastlane/fastlane#9397]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am test spaceship by one ruby script,but fail! 

Gemfile :
```
source "https://rubygems.org"
gem "fastlane"
gem "pry"
```

```
require "spaceship"

Spaceship::Tunes.login("XXX", "XXX")

Spaceship::Tunes.select_team

app = Spaceship::Tunes::Application.find("com.xiaoxi.game1")
 
app.in_app_purchases.create!(
  type: Spaceship::Tunes::IAPType::CONSUMABLE, 
  versions: {
    'en-US': {
      name: "test name1",
      description: "Description has at least 10 characters"
    },
    'de-DE': {
      name: "test name german1",
      description: "German has at least 10 characters"
    },
    'da': {
      name: "test name danish",
      description: "German has at least 10 characters"
    }
  },
  reference_name: "locallizeddemo11111",
  product_id: "x.a.a.b.b.c.d.x.y.f",
  cleared_for_sale: true,
  review_notes: "Some Review Notes here bla bla bla",
  #review_screenshot: "/Users/hjanuschka/Desktop/review.jpg", 
  pricing_intervals: 
    [
      {
        country: "WW",
        begin_date: nil,
        end_date: nil,
        tier: 1
      }
    ] 
)
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
fastlane$ ruby ipa.rb 
/Users/tanjie/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- spaceship (LoadError)
	from /Users/tanjie/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ipa.rb:1:in `<main>
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.23.0"

SCHEME_NAME = "game1"




default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    ENV["game_version"] = get_version_number
    puts "set env :" + ENV["game_version"]
  end

  lane :build_app do |options|
    asmethod = options[:method]
    version = options[:version]
    appName = SCHEME_NAME + "_"+ version+ "_" + asmethod + ".ipa"
    ENV["appName"] = appName
    project_file =  SCHEME_NAME + '.xcodeproj'
    increment_build_number(xcodeproj: project_file) # version bump

    #cert(output_path: "/tmp")

    case asmethod
    when "app-store"
      sigh(output_path:"/tmp")
    when "ad-hoc"
      sigh(adhoc:true,output_path:"/tmp")
    when "development"
      sigh(development:true,output_path:"/tmp")
    else
      sigh(output_path:"/tmp")
    end

    gym(
      scheme: SCHEME_NAME,
      clean: true,
      include_bitcode: false,
      export_options: ({
        compileBitcode: false,
        method: asmethod,#app-store, ad-hoc, package, enterprise, development, and developer-id
        include_bitcode: false
      }),
      output_directory: './fastlane/package/',
      output_name: appName
    )
  end

  lane :codeSign do
    cert(output_path: "/tmp")
    sigh(output_path: "/tmp")
  end

  lane :test do
    #scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    build_app(
      method:"app-store",
      version:get_version_number
    )
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    build_app(
      method:"app-store",
      version:get_version_number
    )
    deliver
    # frameit
  end

  lane :adhoc do
    build_app(
      method:"ad-hoc",
      version:get_version_number
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end```
</details>

<details><summary>`./Appfile`</summary>

```ruby
app_identifier "com.xiaoxi.game1" # The bundle identifier of your app
apple_id "joyguojobs@163.com" # Your Apple email address

team_id "22G6WC5KW6"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.0        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.26       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.5.0        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-06-07**
</details>

**Comment by KrauseFx** [comment]
You can use `bundle exec ruby ipa.rb` after running `bundle update` 👍

**Comment by wulin9005** [comment]
yeah，it is work ,thx 👍
