### ISSUE TITLE
[match] Ignoring file when decrypting certificates repo 

### ISSUE THREAD

**Issue by eiditakahashi** [fastlane/fastlane#9400]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Used match to create certificate and provisionings (adhoc and appstore):
```
match(
      git_url: @config.apple_credentials.repo,
      app_identifier: ["#{@config.env.staging.xcode.app_identifier}", "#{@config.env.production.xcode.app_identifier}"],
      type: "adhoc",
      username: @config.env.appstore.itunesconnect.user,
      readonly: false,
      force_for_new_devices: true,
      force: true
)
match(
      git_url: @config.apple_credentials.repo,
      app_identifier: @config.env.appstore.xcode.app_identifier,
      type: "appstore",
      username: @config.env.appstore.itunesconnect.user,
      readonly: false,
      force_for_new_devices: true,
      force: true
)
```
First match created certificates and provisionings without issues on the second one I got the warn `Couldn't find a valid code signing identity in the git repo for distribution... creating one for you now`. 

Checked my certificates repo and I have
- 56E56KEYAV.cer
- 56E56KEYAV.pkey

inside my distribution certs

and you can see in my output log that `.pkey` file was ignored, maybe this is related with fastlane not finding a valid code signing identity? This `.pkey` is a new thing?

### Captured Output

Command Used: `ios reprovision`
<details><summary>Output/Log</summary>

```


INFO [2017-06-06 19:21:38.16]: -------------------
INFO [2017-06-06 19:21:38.16]: --- Step: match ---
INFO [2017-06-06 19:21:38.16]: -------------------

+-----------------------+--------------------------------------+
|                   Summary for match 2.37.0                   |
+-----------------------+--------------------------------------+
| git_url               | https://github.com/indigotech/certi  |
|                       | ficates-cust                         |
| app_identifier        | xxxxxxxxxxxxxxxx                     |
| type                  | appstore                             |
| username              | xxxxxxxxxxxxxxxxxxxxxx               |
| readonly              | false                                |
| force_for_new_devices | true                                 |
| force                 | true                                 |
| git_branch            | master                               |
| keychain_name         | login.keychain                       |
| verbose               | false                                |
| skip_confirmation     | false                                |
| shallow_clone         | false                                |
| clone_branch_directly | false                                |
| skip_docs             | false                                |
| platform              | ios                                  |
+-----------------------+--------------------------------------+

INFO [2017-06-06 19:21:38.18]: Cloning remote git repo...
INFO [2017-06-06 19:21:38.18]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
INFO [2017-06-06 19:21:38.18]: $ GIT_TERMINAL_PROMPT=0 git clone 'https://github.com/org/certificates-cust' '/var/folders/kg/t7tsn0k51td5d_n6t_zbw5_r0000gn/T/d20170606-54329-1e2xdp9'
INFO [2017-06-06 19:21:38.19]: ▸ Cloning into '/var/folders/kg/t7tsn0k51td5d_n6t_zbw5_r0000gn/T/d20170606-54329-1e2xdp9'...
INFO [2017-06-06 19:21:39.97]: ▸ remote: Counting objects: 2888, done.[K
INFO [2017-06-06 19:21:40.13]: ▸ remote: Compressing objects: 100% (63/63), done.[K
INFO [2017-06-06 19:23:29.42]: ▸ remote: Total 2888 (delta 7), reused 67 (delta 5), pack-reused 2817[K
INFO [2017-06-06 19:23:29.42]: ▸ Receiving objects: 100% (2888/2888), 13.02 MiB | 147.00 KiB/s, done.
INFO [2017-06-06 19:23:29.43]: ▸ Resolving deltas: 100% (330/330), done.
INFO [2017-06-06 19:23:29.48]: 🔓  Decrypted 'P3KQ54X46V.cer'
INFO [2017-06-06 19:23:29.49]: 🔓  Decrypted '56E56KEYAV.cer'
INFO [2017-06-06 19:23:29.49]: 🔓  Decrypted 'P3KQ54X46V.p12'
INFO [2017-06-06 19:23:29.50]: 🔓  Decrypted 'AdHoc_xxxxxxxxxxxxxxxx.mobileprovision'
INFO [2017-06-06 19:23:29.50]: 🔓  Decrypted 'AdHoc_xxxxxxxxxxxxxxxxxxxxx.mobileprovision'
INFO [2017-06-06 19:23:29.51]: 🔓  Decrypted 'Development_xxxxxxxxxxxxxxxxxxxxx.mobileprovision'
INFO [2017-06-06 19:23:29.51]: 🔓  Decrypted 'Development_xxxxxxxxxxxxxxxxxxxxx.mobileprovision'
INFO [2017-06-06 19:23:29.52]: 🔓  Decrypted 'Development_xxxxxxxxxxxxxxxxxxxxx.watchkitapp.mobileprovision'
INFO [2017-06-06 19:23:29.52]: 🔓  Decrypted 'Development_xxxxxxxxxxxxxxxxxxxxx.watchkitapp.watchkitextension.mobileprovision'
INFO [2017-06-06 19:23:29.53]: 🔓  Decrypted 'Development_xxxxxxxxxxxxxxxx.watchkitapp.mobileprovision'
INFO [2017-06-06 19:23:29.53]: 🔓  Decrypted 'Development_xxxxxxxxxxxxxxxx.watchkitapp.watchkitextension.mobileprovision'
INFO [2017-06-06 19:23:29.54]: 🔓  Decrypted 'Development_xxxxxxxxxxxxxxxx.watchkitextension.mobileprovision'
INFO [2017-06-06 19:23:29.54]: 🔓  Successfully decrypted certificates repo
INFO [2017-06-06 19:23:29.54]: Verifying that the certificate and profile are still valid on the Dev Portal...
WARN [2017-06-06 19:24:11.75]: Couldn't find a valid code signing identity in the git repo for distribution... creating one for you now

+---------------+--------------------------------------+
|               Summary for cert 2.37.0                |
+---------------+--------------------------------------+
| development   | false                                |
| force         | true                                 |
| username      | xxxxxxxxxxxxxxxxxxxxxxxxx            |
| keychain_path | /Users/taqtile/Library/Keychains/lo  |
|               | gin.keychain-db                      |
| platform      | ios                                  |
+---------------+--------------------------------------+

INFO [2017-06-06 19:24:11.76]: Starting login with user 'xxxxxx'
INFO [2017-06-06 19:25:32.91]: Successfully logged in
WARN [2017-06-06 19:25:36.24]: Lane Context:
INFO [2017-06-06 19:25:36.24]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios reprovision"}
ERROR [2017-06-06 19:25:36.24]: Could not create another Distribution certificate, reached the maximum number of available Distribution certificates.
INFO [2017-06-06 19:25:36.24]: Successfully generated documentation at path '/Users/.../fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | default_platform       | 0           |
| 2    | import_from_git        | 13          |
| 3    | Verifying required     | 0           |
|      | fastlane version       |             |
| 4    | opt_out_usage          | 0           |
| 5    | load_vault_credential  | 3           |
|      | s_file                 |             |
| 6    | load_settings_file     | 0           |
| 💥   | match                  | 236         |
+------+------------------------+-------------+

DEBUG [2017-06-06 19:25:36.25]: All plugins are up to date
ERROR [2017-06-06 19:25:36.25]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Could not create another Distribution certificate, reached the maximum number of available Distribution certificates.

URL: https://api.github.com/search/issues?q=Could%20not%20create%20another%20Distribution%20certificate,%20reached%20the%20maximum%20number%20of%20available%20Distribution%20certificates.+repo:fastlane/fastlane
➡️  How can I use 'match' to upload my existing distribution cert/key instead of creating a new one on portal?
    https://github.com/fastlane/fastlane/issues/8873 [closed] 2 💬
    12 Apr 2017

➡️  match failed in development
    https://github.com/fastlane/fastlane/issues/9215 [open] 6 💬
    2 weeks ago

➡️  Using Match with already existing profiles and certificates
    https://github.com/fastlane/fastlane/issues/8591 [closed] 9 💬
    08 Apr 2017

and 13 more at: https://github.com/fastlane/fastlane/search?q=Could%20not%20create%20another%20Distribution%20certificate,%20reached%20the%20maximum%20number%20of%20available%20Distribution%20certificates.&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2017-06-06 19:25:37.05]: All plugins are up to date


```

</details>

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.3/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.3/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
ENV['BUILD_DIR'] = Dir.pwd
import_from_git(url: 'https://github.com/org/fastlane',
              branch: '5.0.1',
              path: 'fastlane/Fastfile')

platform :ios do

  override_lane :reprovision do
    match(
      git_url: @config.apple_credentials.repo,
      app_identifier: @config.env.appstore.xcode.app_identifier,
      type: "appstore",
      username: @config.env.appstore.itunesconnect.user,
      readonly: false,
      force_for_new_devices: true,
      force: true
    )
  end

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                | Version | Update-Status |
| --------------------- | ------- | ------------- |
| fastlane-plugin-xcake | 0.1.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.4        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| cork                      | 0.2.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.1.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.4        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.1.1        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.11.0       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.13.2       |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| danger                    | 4.3.3        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.56.0       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| hooks                     | 0.4.1        |
| xcake                     | 0.8.1        |
| fastlane-plugin-xcake     | 0.1.0        |
| travis_dedup              | 0.6.0        |
| vault                     | 0.7.3        |
</details>

*generated on:* **2017-06-06**
</details>

**Comment by eiditakahashi** [comment]
Found, `match` is looking for extension `.p12`
https://github.com/fastlane/fastlane/blob/master/match/lib/match/runner.rb#L78

So I tested locally and everything worked as expected (created provisionings, etc.)
```
...
def fetch_certificate(params: nil)
      cert_type = Match.cert_type_sym(params[:type])

      certs = Dir[File.join(params[:workspace], "certs", cert_type.to_s, "*.cer")]
      keys = Dir[File.join(params[:workspace], "certs", cert_type.to_s, "*.p12")]
      # .p12 key not found. Trying .pkey (new format?)
      keys = Dir[File.join(params[:workspace], "certs", cert_type.to_s, "*.pkey")] if keys.count == 0
...
```
Do you know if this change can impact some other place?

tks!

**Comment by getaaron** [comment]
`*.pkey` files are created by _pem_, but not _cert_. _cert_ (called by _match_) uses `*.p12`. Did you use match to create the repo or did you make it by hand?

**Comment by eiditakahashi** [comment]
@getaaron I use match to manage all the certs and provisionings. When my certificate expired I used match to recreate and was generated this `.pkey` instead of a `.p12`

**Comment by eiditakahashi** [comment]
@getaaron I got what happened, I created certs with `fastlane 2.26.0` and this version had a change that [broke](https://github.com/fastlane/fastlane/pull/8440#issuecomment-292694311) `match` and after that I updated my `fastlane` to `2.37.0`. 

Thanks for your attention and time!
