### ISSUE TITLE
[Question] is there a way to use wildcard in ensure_xcode_version

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#9403]
i.e. if i want to make sure that Xcode version is above 8.2 or 8.3.2 and not particular interested in if that's 8.2.1 or 8.3.1.

i.e. ```
ensure_xcode_version(version: 8.3.*)
```

**Comment by getaaron** [comment]
No, [this action's code](https://github.com/fastlane/fastlane/blob/de594bfb29479d1c4cfa8a6fe95df1adfcb5645a/fastlane/lib/fastlane/actions/ensure_xcode_version.rb#L13) currently checks for string equality:

```ruby
…
if selected_version == required_version
  UI.success("Selected Xcode version is correct: #{selected_version}")
else
…
```
You could try refactoring some code from [this method](https://github.com/fastlane/fastlane/blob/3cf91ace19313963dbfefa99b93a45cff8707c20/fastlane/lib/fastlane/helper/podspec_helper.rb#L30-L50) to add support for semantic versioning. I'm not a core contributor but I suspect that would be a welcome addition :+1:

**Comment by johnknapprs** [comment]
There's a number of way's to deal with this issue.  As getaaron mentioned, the ensure_xcode_version action does not currently support that functionality.  Contributing to expand it would be a welcome update to the fastlane tools!

However, if you need a quicker solution here's some suggestions (albeit wonky ones):

```
# 1
  if /8.3.[0-9]/ === sh("xcversion selected").match(/^Xcode (.*)$/)[1]
     execute your task
 end

#2
  unless sh("xcversion selected").match(/^Xcode (.*)$/)[1][/8.3.[0-9]/].nil?
     execute your task
  end
```

**Comment by romk1n** [comment]
thanks!

**Comment by KrauseFx** [comment]
Thanks everyone, closing this now 👍
