### ISSUE TITLE
External Testers Issue

### ISSUE THREAD

**Issue by nikitaame** [fastlane/fastlane#9408]
I'm currently having an issue with automatically adding external testers when uploading to TF with Pilot. Below is my lane:

`lane :upload_testflight do
  pilot(
    ipa: "my_ipa's_name.ipa",
    distribute_external: true,
    skip_waiting_for_build_processing: true,
    changelog: "Build #{get_version_number}.#{get_build_number} is now ready for testing."
    )
end
`

Any ideas what I might be missing to get the build to appear as "Testing" instead of "Ready to Submit"? This seemed like all I needed: https://github.com/fastlane/fastlane/issues/3857

**Comment by nikitaame** [comment]
> <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customize this file, documentation can be found here:
# https://github.com/krausefx/fastlane#customise-the-fastfile

# Change the syntax highlighting to Ruby

# All lines starting with a # are ignored when running `fastlane`

# This is the minimum version number required.
# Update this, if you use features of a newer version

import '../../Common/fastlane/Fastfile'

ENV['CONFIG'] = "../../DisneyNow/fastlane/config.yaml"

fastlane_version "1.85.0"

default_platform :ios

platform :ios do

end

after_all do |lane|
  version = get_version_number
  build = get_build_number

  sh "echo \"APP_VERSION=#{version} \nAPP_BUILD=#{version}.#{build}\" > version.properties"

  say "Successfully finished deployment (#{lane}) for version: #{version}.#{build}!"
end```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.0.1        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.26       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-06-07**
</details>

**Comment by nikitaame** [comment]
I realized the issue was this flag, `skip_waiting_for_build_processing: true`. Apple's processing is taking about 20 minutes however and I don't want the script running that long. Is there a way to upload it and then have another lane that just submits it for external testers? Then I can just schedule that lane to run later.

**Comment by getaaron** [comment]
You can use `fastlane pilot distribute`:

> Distribute a previously uploaded binary to Apple TestFlight

**Comment by nikitaame** [comment]
@getaaron Is there an equivalent to this I can use in a Fastfile? Sorry, couldn't find anything in the docs

**Comment by nikitaame** [comment]
Tried using `distribute_build(build)` with no luck

**Comment by nikitaame** [comment]
`Could not find action, lane or variable 'distribute_build'. Check out the documentation for more details: https://docs.fastlane.tools/actions`

**Comment by nikitaame** [comment]
Hey, @getaaron. So I figured out how to call `distribute`: `Pilot::BuildManager.new.distribute(options, build: build)` 

I'm now getting `[!] undefined method `export_compliance' for #<Spaceship::Tunes::Build:0x007fb8f224eb10>` which is being called in `distribute_build(uploaded_build, options)` which is called from `distribute`

**Comment by nikitaame** [comment]
So seems like there might be a bug in the current code? Unless I'm calling it wrong somehow

**Comment by getaaron** [comment]
You have a `Spaceship::Tunes::Build`, but you need a `Spaceship::TestFlight::Build`.

**Comment by nikitaame** [comment]
`app = Spaceship::Tunes::Application.find(bundle_identifier)
build = app.edit_version.candidate_builds.first`

**Comment by getaaron** [comment]
I would leave `build` out and let it find the build for you. Just try calling

```ruby
Pilot::BuildManager.new.distribute(options)
```

and make sure you've set both:

```ruby
options[:apple_id]
options[:app_identifier]
```

It might help to review [the `distribute` source code](https://github.com/fastlane/fastlane/blob/af3ff2a873afe703597ea61f53c534f8aa04fced/pilot/lib/pilot/build_manager.rb#L43).

**Comment by nikitaame** [comment]
Thank you, that is proving to be helpful. I'm still running into another issue however:

I'm trying to submit but am getting back, `{"code"=>"ITC.apps.tf.build.test.info.missing.whats.new", "description"=>"Missing what's new info."}` but I added the description into the options as such
`  options = {
    distribute_external: true,
    groups: ["External Testers", "DisneyNOW Quality Logic"],
    beta_app_description: "Newest build to test.",
    beta_app_feedback_email: "test@gmail.com"
  }`

to try and get this line (57) to trigger:
`        app_test_info.test_info.description = options[:beta_app_description] if options[:beta_app_description]`

**Comment by nikitaame** [comment]
Hmmm it was weird issue, needed to add `options[:changelog]` value also. Thanks for helping me out @getaaron!

**Comment by getaaron** [comment]
I meant with the back ticks, although upon reflection this syntax would be preferred:

```ruby
sh "fastlane pilot distribute"
```

**Comment by nikitaame** [comment]
One last question, from the source code, 

`build ||= Spaceship::TestFlight::Build.latest(app_id: app.apple_id, platform: fetch_app_platform)`

How can I set those somewhere without the script asking me for them?
