### ISSUE TITLE
Nuke 'entreprise'?

### ISSUE THREAD

**Issue by NikKovIos** [fastlane/fastlane#9410]
Good day, thanks for such a cool tool!

When i type `fastlane match nuke` in console. There is an error:

    [!] Please run `fastlane match nuke [type], allowed values: distribution, enterprise and development. For the 'adhoc' type, please use 'distribution' instead.

distribution and development works well, but enterprise doesn't work. Is it a legacy error text?

**Comment by Fluzzarn** [comment]
For match to work with enterprise, you need to set the environment variable MATCH_FORCE_ENTERPRISE to 1

**Comment by KrauseFx** [comment]
Thanks @Fluzzarn, actually `MATCH_FORCE_ENTERPRISE` isn't needed any more.

> distribution and development works well, but enterprise doesn't work. Is it a legacy error text?

Could you provide more context on `doesn't work`?

**Comment by NikKovIos** [comment]
When i write `fastlane match nuke enterprise` it throws the same error

    [!] Please run `fastlane match nuke [type], allowed values: distribution, enterprise and development. For the 'adhoc' type, please use 'distribution' instead.

**Comment by Fluzzarn** [comment]
if you run If you run fastlane match nuke enterprise --verbose, what does the additional output say?

**Comment by NikKovIos** [comment]
fastlane match nuke enterprise --verbose                                  ✓  1040  20:29:57
/Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Please run `fastlane match nuke [type], allowed values: distribution, enterprise and development. For the 'adhoc' type, please use 'distribution' instead. (FastlaneCore::Interface::FastlaneError)
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/match/lib/match/commands_generator.rb:112:in `block (2 levels) in run'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/match/lib/match/commands_generator.rb:133:in `run'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/match/lib/match/commands_generator.rb:12:in `start'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/gems/fastlane-2.37.0/bin/fastlane:20:in `<top (required)>'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/nikkov/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'



| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.3                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.3 (16D32)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

**Comment by Fluzzarn** [comment]
Looking at the nuke command, it looks like it will only try to nuke if development or distribution are passed in, and if neither of those two are passed in, then the error is raised.

      command "nuke" do |c|
        # We have this empty command here, since otherwise the normal `match` command will be executed
        c.syntax = "fastlane match nuke"
        c.description = "Delete all certificates and provisioning profiles from the Apple Dev Portal"
        c.action do |args, options|
          FastlaneCore::UI.user_error!("Please run `fastlane match nuke [type], allowed values: distribution, enterprise and development. For the 'adhoc' type, please use 'distribution' instead.")
        end
      end

      ["development", "distribution"].each do |type|
        command "nuke #{type}" do |c|
          c.syntax = "fastlane match nuke #{type}"
          c.description = "Delete all certificates and provisioning profiles from the Apple Dev Portal of the type #{type}"

          FastlaneCore::CommanderGenerator.new.generate(Match::Options.available_options, command: c)

          c.action do |args, options|
            params = FastlaneCore::Configuration.create(Match::Options.available_options, options.__hash__)
            params.load_configuration_file("Matchfile")
            Match::Nuke.new.run(params, type: type.to_s)
          end
        end
      end


(match/lib/commands_generator.rb:107)
@KrauseFx, I think this is a bug, unless I'm misreading how nuke is structured (which just might be the case)?

**Comment by KrauseFx** [comment]
Alright, thanks for the information, this is a bug and needs to be fixed 👍

**Comment by KrauseFx** [comment]
Just pushed https://github.com/fastlane/fastlane/pull/9427
