### ISSUE TITLE
gym complains "framework not found" (but build in Xcode succeeds)

### ISSUE THREAD

**Issue by mvayngrib** [fastlane/fastlane#9411]
first off, I love using fastlane! I hope I can sort this out as it's been smooth so far.

### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

builds fine in XCode, but gym complains about "framework not found"

see output and env (github limits to 65536 characters): https://docs.google.com/document/d/1Gj0FvIGuWBXrekPqbTU1kgJaPQFMIXe4tV5WcSMhwx4

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.7.1                           |
| Installation Source         | ~/.rvm/gems/ruby-2.2.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.2.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2 22 Jan 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.27.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "056cccb7-a2ca-4533-a405-1e643adc7c31"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    sh "../../scripts/placesecrets.sh"
    # sh "../../scripts/ensure_git_clean.sh"
    cocoapods
  end

  lane :commit_version do
    commit_version_bump(
      xcodeproj: ENV['IOS_PROJECT'],
      message: 'iOS release version bump'
    )
  end

  lane :inc_major do
    sh "../../scripts/version_ios.sh major"
    commit_version
  end

  lane :inc_minor do
    sh "../../scripts/version_ios.sh minor"
    commit_version
  end

  lane :inc_patch do
    sh "../../scripts/version_ios.sh patch"
    commit_version
  end

  lane :inc_build do
    sh "../../scripts/version_ios.sh build"
    commit_version
  end

  lane :sign_manual do
    disable_automatic_code_signing(path: ENV['IOS_PROJECT'])
    commit_version
  end

  lane :sign_auto do
    enable_automatic_code_signing(path: ENV['IOS_PROJECT'])
    commit_version
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Build the app"
  lane :dryrun do
    match
    gym(
      export_method: 'app-store'
    )
  end

  lane :gym_prod do
    disable_automatic_code_signing(path: ENV['IOS_PROJECT'])
    gym(export_method: 'app-store')
    enable_automatic_code_signing(path: ENV['IOS_PROJECT'])
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta_testflight do |values|
    match(type: 'appstore')
    gym_prod
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: 'appstore')

    # snapshot
    gym_prod

    deliverit
    # frameit
  end

  lane :deliverit do
    changelog = prompt(
      text: "What's new in this version? ",
      multi_line_end_keyword: 'END'
    )

    deliver(
      force: true,
      release_notes: ({
        'default' => changelog,
        'en-US' => changelog,
        'en-UK' => changelog
      }),
      skip_metadata: false,
      skip_screenshots: true,
      skip_binary_upload: true
    )
  end

  lane :beta_fabric do |values|
    # build your iOS app
    match(
      force_for_new_devices: true
    )

    gym(
      export_method: 'development'
    )

    emails = values[:test_email] ? values[:test_email] : ['mark@tradle.io'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: ENV['CRASHLYTICS_API_TOKEN'],
             build_secret: ENV['CRASHLYTICS_BUILD_SECRET'],
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?
  end

  lane :travis do
    create_keychain(
      name: "MATCH_KEYCHAIN_NAME",
      password: "MATCH_KEYCHAIN_PASSWORD",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )

    match(
      type: 'appstore',
      readonly: true,
      keychain_name: "MATCH_KEYCHAIN_NAME",
      keychain_password: "MATCH_KEYCHAIN_PASSWORD"
    )

    gym(
      export_method: 'app-store',
      include_bitcode: true
    )

    deliver(force:true)
  end

  desc "Upload to App Store and submit for review"
  lane :upload do
    deliver
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "io.tradle.dev.tim" # The bundle identifier of your app
apple_id "ios-dev@tradle.io" # Your Apple email address
itc_team_name "Tradle Inc"
team_id "94V7783F74" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.5       |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| cocoapods                 | 1.2.1        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.56.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-06-08**
</details>

**Comment by getaaron** [comment]
@mvayngrib Can you please update your issue to include the relevant excerpt from the output? Google Docs is hanging when I try to load your link. You could also try posting it on https://gist.github.com.

**Comment by mvayngrib** [comment]
@getaaron sure thing, see https://gist.github.com/mvayngrib/6b4928f6588961247d6fc67db708f0fe#file-framework-not-found-L3768

**Comment by getaaron** [comment]
I think this is a CocoaPods issue. Try out the answer here: https://stackoverflow.com/q/23489920/1445366

**Comment by mvayngrib** [comment]
@getaaron i don't currently have a problem building in XCode. I have two entries in Library Search Paths:
```
$(inherited)
$(SRCROOT)/Tradle
```

just in case, under Framework Search Paths, i have:

```
$(inherited)
$PROJECT_DIR
"$PODS_CONFIGURATION_BUILD_DIR  (recursive)
$(PROJECT_DIR)/Tradle
```

**Comment by mvayngrib** [comment]
@getaaron any ideas? Happy to screenshare and debug with someone :)
