### ISSUE TITLE
[!] undefined method `add_all_testers!' for #<Spaceship::Tunes::Application:0x007f92a94b33e8>

### ISSUE THREAD

**Issue by nikitaame** [fastlane/fastlane#9414]
Trying to use `add_all_testers!` but getting back `[!] undefined method `add_all_testers!' for #<Spaceship::Tunes::Application:0x007f92a94b33e8>`. Was this recently changed with the iTunesConnect changes?

**Comment by mpirri** [comment]
You are correct - this was removed with the recent changes for iTunesConnect. I will remove `all_all_testers!` from the `spaceship` documentation. Do you need this method, or is there a workaround for your use case?  Thanks!

**Comment by nikitaame** [comment]
@mpirri Thank for the response! I need something of the equivalent. I'm trying to use Spaceship to `submit_for_beta_review!()` but when doing so the build isn't inviting any of the external testers. Any suggestions on what I might want to do? Thank you :)

**Comment by nikitaame** [comment]
Figured a work around. Thanks!
