### ISSUE TITLE
Sigh don't work with Jenkins CI

### ISSUE THREAD

**Issue by ELusiveLPFAN** [fastlane/fastlane#9415]
### New Issue Checklist

- [+] Updated fastlane to the latest version
- [+] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]
</details>
[14:40:21]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m
+ cd /Users/Shared/Jenkins/RestaurantHill
+ /Users/Shared/Jenkins/.fastlane/bin/fastlane release
[14:41:03]: [32m-------------------------------------------------[0m
[14:41:03]: [32m--- Step: Verifying required fastlane version ---[0m
[14:41:03]: [32m-------------------------------------------------[0m
[14:41:03]: Your fastlane version 2.37.0 matches the minimum requirement of 2.37.0  ✅
[14:41:03]: [32m------------------------------[0m
[14:41:03]: [32m--- Step: default_platform ---[0m
[14:41:03]: [32m------------------------------[0m
[14:41:03]: [32mDriving the lane 'ios release' 🚀[0m
[14:41:03]: [32m-----------------------[0m
[14:41:03]: [32m--- Step: cocoapods ---[0m
[14:41:03]: [32m-----------------------[0m
[14:41:12]: [4m[36m$ pod install[0m[0m
[14:41:31]: ▸ [35mAnalyzing dependencies[0m
[14:41:31]: ▸ [35mDownloading dependencies[0m
[14:41:31]: ▸ [35mUsing Firebase (4.0.1)[0m
[14:41:31]: ▸ [35mUsing FirebaseAnalytics (4.0.0)[0m
[14:41:31]: ▸ [35mUsing FirebaseCore (4.0.1)[0m
[14:41:31]: ▸ [35mUsing FirebaseInstanceID (2.0.0)[0m
[14:41:31]: ▸ [35mUsing FirebaseMessaging (2.0.0)[0m
[14:41:31]: ▸ [35mUsing GoogleToolboxForMac (2.1.1)[0m
[14:41:31]: ▸ [35mUsing Protobuf (3.3.0)[0m
[14:41:31]: ▸ [35mGenerating Pods project[0m
[14:41:31]: ▸ [35mIntegrating client project[0m
[14:41:39]: ▸ [35mSending stats[0m
[14:41:39]: ▸ [35mPod installation complete! There are 2 dependencies from the Podfile and 7 total pods installed.[0m
[14:41:39]: ▸ [35m[!] Automatically assigning platform ios with version 10.3 on target Restaurant Hill because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.[0m
[14:41:39]: [32m---------------------[0m
[14:41:39]: [32m--- Step: produce ---[0m
[14:41:39]: [32m---------------------[0m

+----------------+--------------------------------+
|           [32mSummary for produce 2.37.0[0m            |
+----------------+--------------------------------+
| username       | XXXXXX@XXXXX.XXX        |
| app_identifier | XXXXXXX |
| app_name       | XXXXXXX                        |
| language       | English                        |
| app_version    | 1.0                            |
| sku            | qwerty1                        |
| team_name      | XXXXXXX.           |
| platform       | ios                            |
| skip_itc       | false                          |
| skip_devcenter | false                          |
| team_id        | XXXXXXXXXX                     |
+----------------+--------------------------------+

[14:41:44]: [32m[DevCenter] App 'XXXXXXXXXX' already exists, nothing to do on the Dev Center[0m
[14:41:49]: [32m[iTC] App 'XXXXXXXXXXX' already exists (XXXXXXXX), nothing to do on iTunes Connect[0m
[14:41:50]: [32m------------------[0m
[14:41:50]: [32m--- Step: cert ---[0m
[14:41:50]: [32m------------------[0m

+---------------+-----------------------------------------------------------+
|                          [32mSummary for cert 2.37.0[0m                          |
+---------------+-----------------------------------------------------------+
| development   | false                                                     |
| force         | false                                                     |
| username      | XXXXXX@XXXX.XXX                                   |
| team_id       | XXXXXXXXXXX                                                |
| keychain_path | /Users/Shared/Jenkins/Library/Keychains/login.keychain-db |
| platform      | ios                                                       |
+---------------+-----------------------------------------------------------+

[14:41:50]: Starting login with user 'XXXXXXXXXX'
[14:41:54]: Successfully logged in
[14:42:01]: [32mFound the certificate XXXXXXXX (iOS Distribution) which is installed on the local machine. Using this one.[0m
[14:42:03]: Verifying the certificate is properly installed locally...
[14:42:03]: [32mSuccessfully installed certificate XXXXXXXXX[0m
[14:42:03]: [32mUse signing certificate 'XXXXXXXXX' from now on![0m
[14:42:03]: [32m------------------[0m
[14:42:03]: [32m--- Step: sigh ---[0m
[14:42:03]: [32m------------------[0m

+-------------------------------------+--------------------------------+
|                       [32mSummary for sigh 2.37.0[0m                        |
+-------------------------------------+--------------------------------+
| adhoc                               | false                          |
| development                         | false                          |
| skip_install                        | false                          |
| force                               | false                          |
| app_identifier                      | XXXXXXXXXXX |
| username                            | XXXXXXXXXXX        |
| team_id                             | XXXXXXXXXX                     |
| ignore_profiles_with_different_name | false                          |
| cert_id                             | XXXXXXXXXX                     |
| skip_fetch_profiles                 | false                          |
| skip_certificate_verification       | false                          |
| platform                            | ios                            |
+-------------------------------------+--------------------------------+

[14:42:03]: Starting login with user 'XXXXXXXXXX'
[14:42:05]: Successfully logged in
[14:42:05]: Fetching profiles...
[14:42:07]: Verifying certificates...
[14:42:11]: [32mFound 1 matching profile(s)[0m
[14:42:11]: [33mDownloading provisioning profile...[0m
[14:42:12]: [32mSuccessfully downloaded provisioning profile...[0m
[14:42:12]: [31mFailure to decode /Users/Shared/Jenkins/RestaurantHill/AppStore_com.restauranthill.app.ario123.mobileprovision. Exit: 1: security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: write permissions error
security: problem decoding
[0m
+---------------------+-----------------------------------------------------+
|                               [33mLane Context[0m                                |
+---------------------+-----------------------------------------------------+
| DEFAULT_PLATFORM    | ios                                                 |
| PLATFORM_NAME       | ios                                                 |
| LANE_NAME           | ios release                                         |
| PRODUCE_APPLE_ID    | XXXXXXXX                                          |
| CERT_FILE_PATH      | /Users/Shared/Jenkins/RestaurantHill/XXXXXXXXX.cer |
| CERT_CERTIFICATE_ID | XXXXXXXXX                                         |
+---------------------+-----------------------------------------------------+
[14:42:15]: [31mError parsing provisioning profile at path '/Users/Shared/Jenkins/RestaurantHill/XXXXXXXXX.mobileprovision'[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | cocoapods                           | 35          |
| 4    | produce                             | 11          |
| 5    | cert                                | 12          |
| 💥   | [31msigh[0m                                | 9           |
+------+-------------------------------------+-------------+

[14:42:18]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/interface.rb:119:in `crash!': [31m[!] Error parsing provisioning profile at path '/Users/Shared/Jenkins/RestaurantHill/AppStore_com.restauranthill.app.ario123.mobileprovision'[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:31:in `parse'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/provisioning_profile.rb:37:in `uuid'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/sigh/lib/sigh/manager.rb:38:in `install_profile'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/sigh/lib/sigh/manager.rb:25:in `start'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/actions/sigh.rb:18:in `run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:57:in `block (2 levels) in parsing_binding'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.37.0/bin/fastlane:20:in `<top (required)>'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/Shared/Jenkins/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
Build step 'shell' marked build as failure
Finished: FAILURE
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#opt_out_crash_reporting
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.37.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
	cert
	sigh
	pem
	gym 
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
	produce(
		username: 'XXXXXXXX',
		app_identifier: 'XXXXXXXXXX',
		app_name: 'XXXXXXXXX',
		language: 'English',
		app_version: '1.0',
		sku: 'qwerty1',
		team_name: 'XXXXXXXXXXX' # only necessary when in multiple teams
	)

	cert
	sigh
	pem
	gym
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "XXXXXXXXXXXX" # The bundle identifier of your app
apple_id "XXXXXXXXXXX" # Your Apple email address

team_id "XXXXXXXXXXXX" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.37.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.8        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.9.28       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.4        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

**Comment by KrauseFx** [comment]
Sorry for the late reply. Did you see the Jenkins guide? https://docs.fastlane.tools/best-practices/continuous-integration/#jenkins-integration

**Comment by istvanp** [comment]
Please try and see if this https://github.com/fastlane/fastlane/issues/9182#issuecomment-326429922 or this https://github.com/fastlane/fastlane/issues/326#issuecomment-218441605 work for you.
