### ISSUE TITLE
sigh Provisioning profile - Missing "Provisioned Devices"

### ISSUE THREAD

**Issue by strano666** [fastlane/fastlane#9419]
- [+] Updated fastlane to the latest version
- [+] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
If i run `fastlane sigh -u <user id> -a <bundle  id>` the tool correctly creates for me the provisioning profile, which didn't exist. Donwload it and also install it.
But in this .mobileprovision file, the tag `<ProvisionedDevice>` is missing. Indeed on the Apple Center on the screen about the provisioning profile just created, in the description i can read `Device: 0`

I've registered the device correctly in the Apple center

How can i add the devices to provisioning profile?

##### Complete output when running fastlane, including the stack trace and command used

```
$ fastlane sigh -u <user id> -a <bundle  id> 

+-------------------------------------+---------------------------+
|                     Summary for sigh 2.37.0                     |
+-------------------------------------+---------------------------+
| username                            | <user id> |
| app_identifier                      | <bundle id>          |
| adhoc                               | false                     |
| development                         | false                     |
| skip_install                        | false                     |
| force                               | false                     |
| ignore_profiles_with_different_name | false                     |
| skip_fetch_profiles                 | false                     |
| skip_certificate_verification       | false                     |
| platform                            | ios                       |
+-------------------------------------+---------------------------+

[18:42:40]: Starting login with user '<user id>'
[18:42:44]: Successfully logged in
[18:42:44]: Fetching profiles...
[18:42:45]: Verifying certificates...
[18:42:45]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[18:42:48]: Creating new provisioning profile for '<bundle id>' with name '<bundle id> AppStore' for 'ios' platform
[18:42:51]: Downloading provisioning profile...
[18:42:53]: Successfully downloaded provisioning profile...
[18:42:53]: Installing provisioning profile...

<path>/AppStore_<bundle id>.mobileprovision
```

**Comment by mpirri** [comment]
When invoking `sigh` without specifying a provisioning profile type, it will generate an App Store profile by default. If you would like to generate a profile with device identifiers, include `--adhoc 1` on the `fastlane sigh` command line.

I hope this is helpful - please let us know if you have other questions!

**Comment by strano666** [comment]
Tnx a lot!
Now it works perfect!

**Comment by strano666** [comment]
Sorry for the up, but it's possible to choose what device to include in the provisioning profile without disabling anyone?

**Comment by tohendiy** [comment]
I need to know about possibility to choose specific devices inside provision profile too (like strano666)

**Comment by ohayon** [comment]
Hey @strano666 and @tohendiy - I don't believe we currently support adding specific devices to a provisioning profile. You might have to do that part manually for now on the dev portal. We would love to see a PR adding that functionality if you want to give it a shot! 🚀 🐙 

I am going to close this issue for now as it seems like the problem was solved. But feel free to continue conversation on here !! 😄
