### ISSUE TITLE
Is it possible to run individual test case/test class?

### ISSUE THREAD

**Issue by farshadtx** [fastlane/fastlane#9422]
### New Issue Checklist

- [ * ] Updated fastlane to the latest version
- [ * ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Is there any plan to add this feature?! specially in case of UITesting it can help to kill simulator and clean between each test.

**Comment by aamctustwo** [comment]
You can use `scan`'s `only_testing` or `skip_testing` to either white-list or black-list test bundles, suites, or cases.

See:
- [Fastlane Docs - scan](https://docs.fastlane.tools/actions/#scan)
- [Apple WWDC 2016 - Session 409: Advanced Testing and Continuous Integration](https://developer.apple.com/videos/play/wwdc2016/409/)

**Comment by farshadtx** [comment]
Thanks, that was exactly what I was looking for. I think more examples for scan on documentation will help others to catch this faster.
