### ISSUE TITLE
about plugin

### ISSUE THREAD

**Issue by caoyunxiao** [fastlane/fastlane#9425]
I installed plugins, but when I initiate a new project, hint I can't find the plug-in.I want to know what's the correct steps?First of all, I performed the < fastlane init >, but Gemfile file is not generated, so I perform again bundle init, why didn't the file automatically generated?If I want to use the plugin, I in each project to perform < fastlane install_plugins >, I think it must be somewhere there is a problem, please let me know.

**Comment by KrauseFx** [comment]
Did you check out our troubleshooting guide? https://docs.fastlane.tools/plugins/plugins-troubleshooting/
