### ISSUE TITLE
Running fastlane command inside nodejs exec

### ISSUE THREAD

**Issue by weihuali0509** [fastlane/fastlane#9426]
I want to be able to launch the *fastlane beta* command inside the nodejs child process. But whenever I do that, I got the following error - 
❌  Code signing is required for product type 'Application' in SDK 'iOS 10.3'
and the Log said - 
No profiles for 'xxx' were found:  Xcode couldn't find a provisioning profile matching 'xxx'.

Is there anything I am doing it wrong?

Here is my lane - 
  lane :beta do
    cert
    sigh(adhoc:true)
    gym(
      scheme: "ThunkableCompanion",
      clean: true
    )
  end

**Comment by weihuali0509** [comment]
Just FYI, the same setting works when I type the *fastlane beta* into the shell/terminal...

**Comment by getaaron** [comment]
Sounds like a nodejs configuration issue to me. Have you tried using `spawn` instead of `exec`?
