### ISSUE TITLE
Hockey upload - parameter owner_id is missing

### ISSUE THREAD

**Issue by muffe** [fastlane/fastlane#943]
We manage our Hockeyapp uploads with different user accounts, but all uploads are bundled into an organization.
Hockeyapp seems to have defaulted some time ago to uploading IPA's to private user account instead of the organization they are part of. So right now all our uploads are owned by the hockeyapp account of the jenkins running fastlane, not our organization he is part of.

owner_id is a parameter where we can set the owner of the ipa (in our case the organization).

Funny enough it's not documented (as far as I can see), so I had to find it on twitter.

https://twitter.com/hockeyapp/status/569227201083797504

**Comment by mRs-** [comment]
Workaround for this:

Create manual an entry first, to get the hockey unique ID.

## Step 1
Create a new app
<img width="91" alt="screen shot 2015-12-14 at 07 52 23" src="https://cloud.githubusercontent.com/assets/736421/11774653/c121c744-a237-11e5-8228-00574f1a4a56.png">

## Step 2
Select create the app manually instead.
<img width="417" alt="screen shot 2015-12-14 at 07 52 35" src="https://cloud.githubusercontent.com/assets/736421/11774674/e9b7316c-a237-11e5-8d02-cc657f1bd581.png">

## Step 3
Select the account you want to create the app in
<img width="383" alt="screen shot 2015-12-14 at 07 52 49" src="https://cloud.githubusercontent.com/assets/736421/11774683/fc8c5894-a237-11e5-89da-7752d1378a30.png">

**Comment by micnguyen** [comment]
For those reading this, this has been resolved in commit e17c7c3b46f6a187c34301e2c6f1735ab944d827  . Can close this issue @muffe .

**Comment by KrauseFx** [comment]
Thanks @micnguyen :+1:
