### ISSUE TITLE
error block return private_lane instead of the executed lane

### ISSUE THREAD

**Issue by wgabsi88** [fastlane/fastlane#9434]
#8512 I'm using private_lanes from another file in my lane , when an error occurs , the block error return the name of the private_lane instead of the executed lane.

 error do |lane, exception|
    notify "Fastlane '#{lane}' errored" 
  end

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.8.1                           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.1                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

platform :ios do

  before_all do
  import "../GeneralFastfile"
  end

  desc "Clean, build the development variant and run the unit tests"
  lane :check_pr do

  smf_increment_build_number(
    project_config: project_config
    )
  smf_collect_changelog(
    build_variant: "extra"
    )

  end

  error do |lane, exception|

    notify "Fastlane '#{lane}' errored" # Mac OS X Notification

  end

end
```
</details>

### fastlane gems

| Gem      | Version                    | Update-Status |
| -------- | -------------------------- | ------------- |
| fastlane | 2.38.0.beta.20170607010024 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| fastimage                 | 2.1.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
</details>

*generated on:* **2017-06-12**
</details>
[INSERT OUTPUT HERE]

**Comment by wgabsi88** [comment]
still have the problem. would really appreciate any help !!

**Comment by taquitos** [comment]
Hey @wgabsi88 you could wrap the lane call inside a `begin rescue` and then re-raise the exception there. That way you'll get the executed lane instead 👍
