### ISSUE TITLE
Let fastlane run only with bundler

### ISSUE THREAD

**Issue by pvegh** [fastlane/fastlane#9435]
We are using fastlane via **bundler** in one of our projects.

I was thinking if it would make sense to configure fastlane such as it does not allow to be run when called directly instead of with **bundle exec**. That way it would not be possible to call fastlane "incorrectly" directly if the project expects this, leading to less issues just because of using the tools the "wrong" way.

I am thinking of a simple flag for fastlane in Fastfile like **force_using_bundler** or so which would print an error and exit the process if called as "fastlane foo" instead of "bundler exec fastlane foo".

What are you thoughts on this?

**Comment by KrauseFx** [comment]
Oh that's interesting, I like the idea. What would you think about the following on top of your `Fastfile`?

```ruby
ensure_bundle_exec
```

**Comment by pvegh** [comment]
Sure, reads more like the existing ones. 👍

**Comment by pvegh** [comment]
@KrauseFx still interested to implement this?

**Comment by stefanengel** [comment]
Sounds really helpful and would ensure that everyone on the team runs the same version of fastlane 👍

**Comment by LindaWdm** [comment]
Yes I think this feature helpful! 👍

**Comment by taquitos** [comment]
@pvegh that would be great! We'd happily review something like this, if you haven't contributed to _fastlane_ before, check out [Your First PR](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md). Let us know if you have any problems!

**Comment by pvegh** [comment]
It was more like a feature request 🤔
