### ISSUE TITLE
Handle multiple types in a Matchfile

### ISSUE THREAD

**Issue by ebermudezcds** [fastlane/fastlane#9437]
Hi, we couldn't work out how to handle multiple types inside the Matchfile file. Can someone provide a working example of a Matchfile with multiple types?

Thanks!

**Comment by PetrosIchor** [comment]
Read the docs 
https://github.com/fastlane/fastlane/blob/master/match/README.md

Checkout the examples
https://github.com/fastlane/examples

**Comment by KrauseFx** [comment]
Hey @ebermudezcds, basically you can use a `Fastfile` to call _match_ multiple times 👍

**Comment by ebermudezcds** [comment]
Thanks @KrauseFx and @PetrosIchor 👍
