### ISSUE TITLE
[Regression] Regression in Supply in 2.38.0

### ISSUE THREAD

**Issue by Aarturo** [fastlane/fastlane#9442]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I updated fastlane to 2.38.0 and the upload apk doesn't work anymore 
#####

/Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/client.rb:215:in `block in upload_apk': [31m[!] undefined method `upload_apk' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007ff282e1f498>[0m (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/client.rb:368:in `call_google_api'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/client.rb:214:in `upload_apk'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/uploader.rb:139:in `upload_binary_data'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/uploader.rb:113:in `block in upload_binaries'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/uploader.rb:112:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/uploader.rb:112:in `upload_binaries'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/supply/lib/supply/uploader.rb:26:in `perform_upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/actions/supply.rb:21:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:87:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.38.0/bin/fastlane:20:in `<top (required)>'
	from /usr/bin/fastlane:22:in `load'
	from /usr/bin/fastlane:22:in `<main>'
Build step 'Execute shell' marked build as failure
Finished: FAILURE

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.10.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.5.4 (Apple Git-61)                               |
| Installation Source         | /usr/bin/fastlane                                              |
| Host                        | Mac OS X 10.10.5 (14F2009)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8za 5 Jun 2014                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 7.2.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

lane :updategp do
    supply(
      package_name: "my.app.com",
      track: "alpha",
      apk: "./platforms/android/build/outputs/apk/signapp.apk",
      json_key: "./google-credentials.json"
    )
  end

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.38.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| faraday-cookie_jar        | 0.0.6        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.3        |
| addressable               | 2.5.1        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| os                        | 0.9.6        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| json                      | 2.0.3        |
| excon                     | 0.54.0       |
| rubyzip                   | 1.2.0        |
| plist                     | 3.2.0        |
| faraday                   | 0.11.0       |
| signet                    | 0.7.3        |
| faraday_middleware        | 0.11.0.1     |
| http-cookie               | 1.0.3        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| fastimage                 | 2.0.1        |
| public_suffix             | 2.0.5        |
| bundler                   | 1.14.3       |
| terminal-table            | 1.7.3        |
| unicode-display_width     | 1.1.3        |
</details>

*generated on:* **2017-06-12**
</details>

**Comment by KrauseFx** [comment]
Thanks for letting me know, we're gonna do a hotfix release https://github.com/fastlane/fastlane/issues/9444, we'll have a new version live within a few minutes 👍

**Comment by Aarturo** [comment]
great, thanks for the fast response

**Comment by KrauseFx** [comment]
👍
