### ISSUE TITLE
running actions on git submodules

### ISSUE THREAD

**Issue by ilandbt** [fastlane/fastlane#9453]
Hi,
I have some internal frameworks that i want to run fastlane actions on them before deployment.
Is there a way to do this?

Thanks

**Comment by ohayon** [comment]
Hey @ilandbt, could you provide a bit more detail about what you're trying to do?

**Comment by ilandbt** [comment]
i have a few company internal frameworks that are added as git submodules to my project.
I would like to run sum fastlane actions on them before deploying to app store.

 For example:

```Ruby
ensure_git_branch(branch: 'master')
scan
```

**Comment by ohayon** [comment]
Ohhh, yes you should definitely be able to do this without a problem! Do you keep your submodules in different directories/git repos?

**Comment by ilandbt** [comment]
This is how my directories are:

- Project 
--- .git
--- Frameworks
--- App
----- Fastlane

**Comment by ohayon** [comment]
Hmm... I think you should be able to create `Fastfile`s within your Frameworks directories that can be executed from in there. Is there anything you have tried so far that has or hasn't worked? I'm no immediately familiar with this type of setup so it might be some trial and error but you should definitely be able to get this stuff working.

**Comment by ilandbt** [comment]
The setup is taken from [raywenderlich](https://www.raywenderlich.com/155150/dependency-management-using-git-submodules)

I didn't try anything, couldn't figure out how to start.
If i have a Fastfile within each framework will i need to have a custom script in the main Fastfile that will run all the other ones?

**Comment by ohayon** [comment]
I dont believe so, you should be able to just `cd` into those directories and execute _fastlane_ from there.

**Comment by ilandbt** [comment]
Thanks,
So if i do want to automate all of the process i need to add a script that will run the frameworks Fastfile from the apps Fastfile?

**Comment by ohayon** [comment]
Thats possible, yeah. But I think you also may be able to create a `Fastfile` towards the root of your directory structure and then use the different options for different tools to point to the submodules that you want to operate on as well.

**Comment by ilandbt** [comment]
Thanks, @ohayon

**Comment by ohayon** [comment]
No problem! I am going to close this issue for now but feel free to continue asking questions on here! 🚀
