### ISSUE TITLE
Deliver documentaion missing platform option

### ISSUE THREAD

**Issue by vronin** [fastlane/fastlane#9455]
This file doesn't say anything about "platform" option, which needs to be set for OSX builds.

https://github.com/fastlane/fastlane/blob/master/deliver/Deliverfile.md

**Comment by ohayon** [comment]
Thanks @vronin! Any chance you would want to submit a PR to put that in there?

**Comment by vronin** [comment]
@ohayon Sure will do. However, English is my second language, so beware of grammar mistakes :)

**Comment by ohayon** [comment]
No worries! We are full of non-native speakers on our side as well! Thanks for the help 👍  🚀 !

**Comment by vronin** [comment]
@ohayon Here we go: https://github.com/fastlane/fastlane/pull/9457

**Comment by ohayon** [comment]
Thanks @vronin !!
