### ISSUE TITLE
snapshot doesn't work by default on Xcode 9

### ISSUE THREAD

**Issue by KrauseFx** [fastlane/fastlane#9467]
I just checked, _snapshot_ stopped working for Xcode 9, looking into this now
```
<string>Some screenshots were deleted because your scheme is configured to remove automatic screenshots on success.</string>
```

WWDC Session https://developer.apple.com/videos/play/wwdc2017/409/

**Comment by winzig** [comment]
Does this issue explain why I would be seeing this error when trying to use _snapshot_ on Xcode 9:

```
[20:42:47]: Copying '/Users/tom/MyApp/screenshots/en-US/iPhone7-3-Home-d41d8cd98f00b204e9800998ecf8427e.png'...
[20:42:47]: No such file or directory - /var/folders/lp/92f4l799527f7ws4fv98lc940000gp/T/snapshot_derived20170620-19087-1b034k5/Logs/Test/Attachments/Screenshot_347ACCD4-16B9-401E-A41B-907162F39A28.png
```

**Comment by mpirri** [comment]
@winzig Have you had a chance to upgrade to _fastlane_ 2.39.2? This version features the message added by #9468 with advice about how to work around the Xcode 9/`snapshot` issue. (spoiler alert: you can temporarily use an older version of Xcode to generate your screenshots, until we are able to fix this functionality in Xcode 9).

Please let us know if you are still not seeing this issue, or if you have any other questions about _fastlane_.  🚀

**Comment by winzig** [comment]
@mpirri Sorry for the late response. I've updated to _fastlane 2.50.0_, and I am **not** seeing that warning when I run snapshot, at least nowhere I can see it. 

In terms of the actual workaround, I'm going to give that a shot next, but just wanted to let you know the above.

**Comment by winzig** [comment]
The workaround of using Xcode 8 did work for me, fyi. Thank you.
