### ISSUE TITLE
It would be useful to not automatically update app version for submission when we do deliver

### ISSUE THREAD

**Issue by vronin** [fastlane/fastlane#9470]
Each time when I run deliver, it automatically updates app version for submission.

This is not very helpful when it runs as part of CI and there are a lot of build.

It's better when a human specifies which version needs to be prepared for submission.

**Comment by vronin** [comment]
PR to allow skip updating app version for deliver: https://github.com/fastlane/fastlane/pull/9469

**Comment by taquitos** [comment]
Looks like this can be closed since your pr got merged 🍾 🎉
