### ISSUE TITLE
Fastlane execute bash/ shell script not exiting

### ISSUE THREAD

**Issue by ericn37** [fastlane/fastlane#9471]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
My original question is [here](https://stackoverflow.com/questions/44448906/fastlane-execute-bash-script-not-exiting).
Fastlane lane definition:  
```
    lane :beta do |options|
        # Run Calabash tests
        sh "bash ./calaba.sh bag"
    
        gradle(task: "assembleStagingRelease")
        # ...
    end
```
Note that the bash script is getting executed just fine, it just doesn't exit ==> fastlane gets stuck there forever!  
calaba.sh:  
```
    # !/bin/bash
    echo "tag is $1"
    $(which emulator) -avd Nexus_5_API_21 -no-skin -no-audio -no-window -gpu off -ports 5556,5557 > /dev/null &
    if $(which adb) devices | grep -q "emulator-5556"; then
      echo "Emulator ready!"
      export ADB_DEVICE_ARG=emulator-5556
      cd ..
      ./gradlew assembleProductionDebug
      $(which bundle) exec calabash-android run app/build/outputs/apk/app-production-debug.apk -t @$1
    else
      echo "Failed to start the emulator"
    fi
    exit 0
```
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
❯ fastlane beta env:staging
[17:47:37]: -------------------------------------------------
[17:47:37]: --- Step: Verifying required fastlane version ---
[17:47:37]: -------------------------------------------------
[17:47:37]: Your fastlane version 2.35.0 matches the minimum requirement of 2.33.0  ✅
[17:47:37]: ------------------------------
[17:47:37]: --- Step: default_platform ---
[17:47:37]: ------------------------------
[17:47:37]: Driving the lane 'android beta' 🚀
[17:47:37]: ----------------------------------
[17:47:37]: --- Step: bash ./calaba.sh bag ---
[17:47:37]: ----------------------------------
[17:47:37]: $ bash ./calaba.sh bag
[17:47:37]: ▸ tag is bag
[17:47:37]: ▸ Failed to start the emulator
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.1                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.0                           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.1 (16B2555)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.33.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Run Calabash tests"
  lane :uat do |options|
    run_calabash_tests(options[:tag])
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |options|
    # Run Calabash tests
    skip_uat = options[:skip_uat]
    if !skip_uat
      run_calabash_tests("bag")
    end
    # sh "bash ./calaba.sh bag"

    # Generate the build for the requested environment
    env = options[:env]

    if !env.to_s.empty? && env.casecmp("production") == 0
      gradle(task: "assembleProductionRelease")
    else
      gradle(task: "assembleStagingRelease")
    end

    # Send the build via Fabric Beta
    changelog = prompt(
    text: "Changelog: ",
    multi_line_end_keyword: "END"
    )
    crashlytics(
    api_token: '58baeaf19016129d93d176430cbfb58a7cb2d617',
    build_secret: '2c0fd405335db48b86004172b78d47c48c9dd5dacd9752e6fc4229aee08fb539',
    notes: changelog,
    groups: 'Sephora'
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta without running automated tests first"
  lane :bad do |options|
    gradle(task: "assembleStagingRelease")
    crashlytics(
    api_token: '58baeaf19016129d93d176430cbfb58a7cb2d617',
    build_secret: '2c0fd405335db48b86004172b78d47c48c9dd5dacd9752e6fc4229aee08fb539',
    notes: "#{git_branch}\n#{last_git_commit}\nDid not pass automated tests!\nThis is for isolated experimental feature like Modiface only.\nDo not abuse!",
    emails: options[:emails]
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    # Run Calabash tests
    run_calabash_tests("bag")
    gradle(task: "assembleProductionRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

def run_calabash_tests (tag)
  # gradle(task: "assembleProductionDebug")
  sh "bash ./calaba.sh #{tag}"
  puts "Finished running Calabash tests"
  # sh "$(which emulator) -avd Nexus_5_API_21 -no-skin -no-audio -no-window -gpu off -ports 5556,5557 > /dev/null &"
  # sh "if !$(which adb) devices | grep -q emulator-5556 then
  # export ADB_DEVICE_ARG=emulator-5556
  # cd .. && $(which bundle) exec calabash-android run app/build/outputs/apk/app-production-debug.apk -t @#{tag}
  # fi"
  # sh "export ADB_DEVICE_ARG=emulator-5556"
  # sh "cd .. && $(which bundle) exec calabash-android run app/build/outputs/apk/app-production-debug.apk -t @#{tag}"
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.35.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-14**
</details>

**Comment by ohayon** [comment]
Hey @ericn37, thanks for raising the issue! I am having a hard time reproducing this issue locally. I have created a lane:
```
  lane :s do
    sh "bash ./script.sh"
  end
```

and a script: 
```
#!/bin/bash

echo "hello"

exit 0
```

and when I execute the lane, it ends up exiting appropriately.
```
[13:37:14]: ------------------------------
[13:37:14]: Driving the lane 'ios s' 🚀
[13:37:14]: ------------------------------
[13:37:14]: --- Step: bash ./script.sh ---
[13:37:14]: ------------------------------
[13:37:14]: $ bash ./script.sh
[13:37:14]: ▸ hello

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | bash ./script.sh                    | 0           |
+------+-------------------------------------+-------------+

[13:37:14]: fastlane.tools finished successfully 🎉

```

Have you tried to reproduce this issue with a different script at all?

**Comment by ericn37** [comment]
Hi @ohayon , thanks for your prompt reply.

I did try the simple "hello" script and fastlane did manage to proceed.
However, I don't understand why this issue is happening to my script.
As you can see from the log, it printed out "Failed to start the emulator" so it already got to the end of the script so it's basically the same as the "hello" script.

Is there something I'm missing in order execute bash script with fastlane? 😅

**Comment by ohayon** [comment]
Have you tried running that script on its own? Does it exit when it is not being run from _fastlane_? 

Also, you shouldn't _need_ to use `bash` in the call to `sh` you should be able to just call `sh ".calaba.sh bag"`.

One other thing I noticed which also is probably not responsible for the hanging, is that your shebang line in the top of the script has a space between the `#` and the `!` which I think is not standard.

I think the first thing I would try, is running that script on its own and seeing if it exits. Let us know if we can help more! 🚀

**Comment by ericn37** [comment]
omg, changing `sh "bash ./calaba.sh"` to `sh "./calaba.sh"` make the script exit properly!

You are such a great help, thank you @ohayon 🙆‍♂️

**Comment by ohayon** [comment]
Glad to help! Let us know if you have any more questions!! 🚀 🐙
