### ISSUE TITLE
[question] is there a list of of default environment ?

### ISSUE THREAD

**Issue by romk1n** [fastlane/fastlane#9479]
I keep forgetting what environment i can setup for example apple_id to be used by both match and deliver. Is there somewhere a list where those can be easily looked up? i checked docs.fastlane but nothing there.

Thanks!

**Comment by ohayon** [comment]
Hey @romk1n, if I understand correctly, you are looking for a place to store your Apple ID such that you don't get asked for it by each tool? Try setting `FASTLANE_USER` as an environment variable. You can also set `FASTLANE_PASSWORD` if that's helpful for you as well! Let us know if that helps or if you ahve any more questions!

**Comment by romk1n** [comment]
@ohayon yeah that helps, but i wonder if there is a way to have a look at all of the settings possible? i.e. so overtime i want to provide something i can just look it up somehow. Thank you!

**Comment by ohayon** [comment]
You can take a look at individual actions' files in the `fastlane/actions/` directory, or in the tools' `options.rb` files (i.e. `pilot/options.rb`) to see a list of all available options per action/tool.

I am going to close this issue for now, but please feel free to continue conversation and submit PR's to update any documentation you think is lacking! 🚀
