### ISSUE TITLE
 Connection refused - connect(2) for "127.0.0.1" port 8888 05c94ef37057630f1d18b788ba824f60

### ISSUE THREAD

**Issue by trevorwang** [fastlane/fastlane#948]
[18:54:47]: -------------------------------------------------
[18:54:47]: --- Step: Verifying required fastlane version ---
[18:54:47]: -------------------------------------------------
[18:54:47]: fastlane version valid
[18:54:47]: ------------------------------
[18:54:47]: --- Step: default_platform ---
[18:54:47]: ------------------------------
[18:54:47]: Driving the lane 'ios deploy' 🚀
[18:54:47]: ------------------
[18:54:47]: --- Step: sigh ---
[18:54:47]: ------------------
/Users/xxxxx/.rbenv/versions/2.0.0-p647/lib/ruby/gems/2.0.0/gems/spaceship-0.15.1/lib/spaceship/client.rb:11: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER

+-------------------------------+-------------------------+
|                 Summary for sigh 1.1.4                  |
+-------------------------------+-------------------------+
| adhoc                         | false                   |
| skip_install                  | false                   |
| development                   | false                   |
| force                         | false                   |
| app_identifier                | *****                   |
| username                      | *****                   |
| output_path                   | .                       |
| skip_fetch_profiles           | false                   |
| skip_certificate_verification | false                   |
+-------------------------------+-------------------------+

[18:54:48]: Starting login with user '********'
[18:54:50]: Variable Dump:
[18:54:50]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios deploy"}
[18:54:50]: Connection refused - connect(2)

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | sigh                                | 2           |
+------+-------------------------------------+-------------+

[18:54:50]: fastlane finished with errors
Successfully submitted a crash report. If this is a problem with one of the tools specifically,
please submit an issue on GitHub and attach the following number to it: '41256720698cf878520444100631cdd8'
The crash report has been stored locally '/tmp/sentry_41256720698cf878520444100631cdd8.json'

**Comment by KrauseFx** [comment]
Make sure you didn't set the `DEBUG` environment variable to something, as this will switch to a local proxy.

**Comment by KrauseFx** [comment]
Maybe it's time for `spaceship` to use something like `SPACESHIP_DEBUG` instead to not conflict with anything.

**Comment by martinjuhasz** [comment]
> Maybe it's time for spaceship to use something like SPACESHIP_DEBUG instead to not conflict with anything.

yeah totally. Run into this issue while using `fastlane` out of a `node.js` application that was in `DEBUG` mode.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:

**Comment by nolanwilson** [comment]
FWIW, I think spaceship should be using a variable like `SPACESHIP_DEBUG`. I have other projects that, for better or worse, rely on this env variable to be set, but I don't want spaceship running in debug mode at that time.

Just ran into this issue when working on a project.

**Comment by TKBurner** [comment]
@nolanwilson Thanks for the suggestion 👍 I'll bring this up with the core team.

**Comment by KrauseFx** [comment]
Great point everyone, updating this now 👍

**Comment by KrauseFx** [comment]
This will be in the next release https://github.com/fastlane/fastlane/pull/6312

**Comment by nolanwilson** [comment]
Thanks for the incredible response times and getting this tweaked! Makes my life a whole lot easier.
