### ISSUE TITLE
Proposal: Estimate App Store download size with App Thinning

### ISSUE THREAD

**Issue by capyvara** [fastlane/fastlane#9482]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Some apps, specially games, struggle to keep their download sizes below the 100Mb limit, due to carrier network download limits on iOS, however the way people usually get around it is to send the build to iTunesConnect and later check the sizes reported by Apple.

I have a script that can get a quite close estimate from the .xcarchive, it works by **simulating the Apple encryption** of the app executable (random bytes are written to the _TEXT segments of the executable file), plus some artificially added files, followed by an ad-hoc export of the archive with the exportOptionsPlist thinning set to `<thin-for-all-variants>`, that generate a thinning report such as this:
```
App Thinning Size Report for All Variants of Unity-iPhone

Variant: Unity-iPhone-iPad 2-etc.ipa
Supported devices: iPad (3rd generation), iPad (4th generation), iPad 2, iPad mini, iPhone 4S, iPhone 5, iPhone 5c, and iPod touch
App + On Demand Resources size: 67,5 MB compressed, 126,9 MB uncompressed
App size: 67,5 MB compressed, 126,9 MB uncompressed
On Demand Resources size: Zero KB compressed, Zero KB uncompressed

Variant: Unity-iPhone-iPhone 7 Plus-etc.ipa
Supported devices: iPad (5th generation), iPad Air, iPad Air 2, iPad Pro (), iPad Pro (), iPad mini 2, iPad mini 3, iPad mini 4, iPhone 5s, iPhone 6, iPhone 6 Plus, iPhone 6s, iPhone 6s Plus, iPhone 7, iPhone 7 Plus, iPhone SE, and iPod touch (6th generation)
App + On Demand Resources size: 71,1 MB compressed, 131,6 MB uncompressed
App size: 71,1 MB compressed, 131,6 MB uncompressed
On Demand Resources size: Zero KB compressed, Zero KB uncompressed

Variant: Unity-iPhone.ipa
Supported devices: Universal
App + On Demand Resources size: 100,8 MB compressed, 163,4 MB uncompressed
App size: 100,8 MB compressed, 163,4 MB uncompressed
On Demand Resources size: Zero KB compressed, Zero KB uncompressed
```
Also a .plist with detailed information is available in case the user wants to use it.

I can port this feature to fastlane, but I want to get if there's some demand for it, and if so, which usage/features you expect.

**Comment by ohayon** [comment]
This is a really cool idea @Capyvara! I will share this with the team and see what they think! 🚀

**Comment by capyvara** [comment]
WIP plugin here:
https://github.com/capyvara/fastlane-plugin-store_sizer

**Comment by capyvara** [comment]
Plugin published to RubyGems

**Comment by taquitos** [comment]
Wooo, awesome!
