### ISSUE TITLE
[fastlane] [pem] [match] [spaceship] Merchant ID and certificate for Apple Pay

### ISSUE THREAD

**Issue by GandjaFuzz** [fastlane/fastlane#9487]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Guys how i can make merchant_id and apple pay certificates from fastlane ?

**Comment by smweber** [comment]
I was wondering this as well. It seems I can enable Apple Pay using produce, but I don't see any way to add the merchant ID or certificate using any Fastlane tools. Is it possible?

**Comment by taquitos** [comment]
Currently not possible 😓, we haven't fielded many requests for this. We would definitely be happy to review a PR with that addition 👍
If that's something you'd like to do, check out: [YourFirstPR.md](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md)
