### ISSUE TITLE
Disable Github Search output on failure?

### ISSUE THREAD

**Issue by danieljimenez** [fastlane/fastlane#9489]
Is it possible to disable the github search feature when deliver fails? While it's helpful for me, it's confusing a few of my developers.

Thanks in advance and thanks for a great tool Felix.

**Comment by ohayon** [comment]
Hey @danieljimenez, currently there is no way to disable that output. We would definitely be happy to merge a PR that adds that functionality if you want to submit something!? 🚀

**Comment by danieljimenez** [comment]
Sounds good! I'll take a look :).

**Comment by ohayon** [comment]
👍  I am going to close this issue for now, but please feel free to continue discussion here in the future and ping us if/when you can get around to making a PR! 💯
