### ISSUE TITLE
Gym failing after upgrade to 2.38.1 "no implicit conversion of Symbol into Integer"

### ISSUE THREAD

**Issue by bes** [fastlane/fastlane#9490]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After updating to fastlane-2.38.1 from 2.37.0, the GYM step of our build is failing

This patch might have something to do with it? https://github.com/fastlane/fastlane/commit/3c597616d1d5b170d2e2b2d54446079b32e1b8de (XCode 9 support)

As you can see match is run before gym, which the patch notes say should be enough.

Will roll back to 2.37.0 and await more info.

##### Complete output when running fastlane, including the stack trace and command used

```
~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/actions/gym.rb:26:in `[]=': [!] no implicit conversion of Symbol into Integer (TypeError)
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/actions/gym.rb:26:in `run'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
        from Fastfile:93:in `block (2 levels) in parsing_binding'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from ~/.rvm/gems/ruby-2.3.4@my_app/gems/fastlane-2.38.1/bin/fastlane:20:in `<top (required)>'
        from ~/.rvm/gems/ruby-2.3.4@my_app/bin/fastlane:23:in `load'
        from ~/.rvm/gems/ruby-2.3.4@my_app/bin/fastlane:23:in `<main>'
        from ~/.rvm/gems/ruby-2.3.4@my_app/bin/ruby_executable_hooks:15:in `eval'
        from ~/.rvm/gems/ruby-2.3.4@my_app/bin/ruby_executable_hooks:15:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                         |
| --------------------------- | --------------------------------------------- |
| OS                          | 10.12.5                                       |
| Ruby                        | 2.3.4                                         |
| Bundler?                    | true                                          |
| Git                         | git version 2.13.0                            |
| Installation Source         | ~/.rvm/gems/ruby-2.3.4@App_ios/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                      |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.4/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                   |
| Is contained                | false                                         |
| Is homebrew                 | false                                         |
| Is installed via Fabric.app | false                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/   |
| Xcode Version               | 8.3.3                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Check available actions: fastlane actions

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.100.0"

default_platform :ios

platform :ios do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |options|
    match(
      type: "development",
      force_for_new_devices: true,
      app_identifier: ["com.corp.App-ios", "com.corp.App-ios.watchkitapp", "com.corp.App-ios.watchkitapp.watchkitextension"],
      username: options[:username],
      git_full_name: options[:git_full_name],
      git_user_email: options[:git_user_email]
    )
    scan # Check fastlane/Scanfile for defaults
    gym(
      scheme: "App-debug",
      export_options: "./exportOptionsBeta.plist"
    )
    crashlytics(
      crashlytics_path: './Pods/Crashlytics/',
      api_token: '-',
      build_secret: '-',
      ipa_path: './corp.ipa',
      groups: 'Internalcorp'
    )
    upload_symbols_to_crashlytics(
      api_token: '-'
    )
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.corp.App-ios" # The bundle identifier of your app

team_id "-"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.38.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| google-api-client         | 0.9.28       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| i18n                      | 0.8.4        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| cocoapods                 | 1.2.1        |
</details>

*generated on:* **2017-06-15**
</details>

**Comment by KrauseFx** [comment]
Thanks for letting us know, this is a regression, and we're already preparing a hotfix release now 👍 https://github.com/fastlane/fastlane/pull/9493

**Comment by bes** [comment]
🎉
