### ISSUE TITLE
Support DTDKProvisioningProfileExtraSearchPaths in gym

### ISSUE THREAD

**Issue by AliSoftware** [fastlane/fastlane#9492]
## Motivation

On our projects, we like to keep the Provisioning Profiles of each project in their relative Git repo, e.g. inside a "Profiles" folder at the root next to our fastlane/Fastfile and Xcode project. This way we don't lose those profiles and they are attached to the git repo.

It would be nice to be able to **allow _fastlane_ to use those Provisioning Profiles directly from that relative path** (instead of having to then copy/install those profiles in `~/Library/MobileDevice/…` on the building machine before starting the build), especially for projects that can be built on various machines and on CI, where there's no guarantee that the Provisioning Profile will always be installed.

## Solution

I recently discovered that it seems possible to provide an extra path for Xcode to search for Provisioning Profiles using the `DTDKProvisioningProfileExtraSearchPaths` env variable

See https://gist.github.com/nubbel/03101b10b8a0c9016f36

It would be quite powerful if `gym` would then allow a new argument like `provisioning_profiles_dir:` allowing to specify the folder where the project's Provisioning Profile(s) are located, and use that `DTDKProvisioningProfileExtraSearchPaths` (that very few people seem to know about, so exposing it would be real good for discovery) under the hood to allow that feature.

## Considerations

I haven't had time to actually test that env variable to check if it's working — and still supported with Xcode 9 — so would probably require to test if that `DTDKProvisioningProfileExtraSearchPaths` really still works and offer everything we wish, before starting implementing that feature into _fastlane_.

**Comment by AliSoftware** [comment]
I'm busy with house loan rn so won't have much time to take care about this feature myself now, but I think it's still relevant and interesting

**Comment by taquitos** [comment]
Hey, this seems really useful, if anybody sees this issue and wants to work on it feel free to ping us and we can help out where needed 👍
