### ISSUE TITLE
Crashlytics ad hoc profile issue

### ISSUE THREAD

**Issue by pronebird** [fastlane/fastlane#950]
I have the following lane:

```rb
  lane :beta do
    cocoa-pods
    gym(configuration: "Testing")
    # snapshot
    sigh
    crashlytics
    slack
  end
```

And Fastlane pulls `AdHoc_XXX.mobileprovision` and I can confirm it has the right device IDs in it but when I publish the app Fabric says that device UUID is not in profile.

First it asked me which profile I'd like to use, I select Adhoc.

```
Found more than one provisioning profile in the project directory:
1. AdHoc_XXX.mobileprovision
2. AppStore_XXX.mobileprovision
?  1
```

but then it picks up app-store profile before sending out the build. This does not make any sense.

```
Setting Provisioning Profile type to 'app-store'
```

Then I tried `sigh(adhoc: true)` and it says

```
Setting Provisioning Profile type to 'ad-hoc'
```

But the build is still not available, says no UUIDs found...

Trying gym with explicit export_method: 

```rb
gym({ configuration: "Testing", export_method: 'ad-hoc' })
```

It keeps asking me which provisioning to use, I thought export_method should tell it to figure out which of two profiles that I have is for Adhoc. Crashes with:

```
Error packaging up the application
error: exportArchive: No applicable devices found.
```

Built app in Xcode -> Fabric – no issues.

**Comment by KrauseFx** [comment]
Can you try using 

```ruby
gym(configuration: "Testing", use_legacy_build_api: true)
```

**Comment by pronebird** [comment]
@KrauseFx did the trick, cheers!
