### ISSUE TITLE
NoMethodError: undefined method `download' for #<Array:0x007fbf95b35950>

### ISSUE THREAD

**Issue by tbores** [fastlane/fastlane#9503]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Code from documentation isn't working
# Download a specific profile as file
my_profile = Spaceship::Portal.provisioning_profile.app_store.find_by_bundle_id("com.krausefx.app")
File.write("output.mobileprovision", my_profile.download)

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.
[17:14:52]: Generating fastlane environment output, this might take a few seconds...
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-06-16**

**Comment by ohayon** [comment]
Hey @tbores, could you share the output from your command line to give more context?

**Comment by tbores** [comment]
Hello @ohayon, I'm trying to use the commands in the following official documentation: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md
My script contains following code:
`#!/usr/bin/env ruby
require 'spaceship'
require 'fastlane'
require 'pp'

username = ARGV[0]
password = ARGV[1]

Spaceship::Portal.login(username, password)

# Verify that the certificate of the provisioning profile is valid
#profiles.certificate_valid?

my_profile = Spaceship::Portal.provisioning_profile.app_store.find_by_bundle_id("com.something.somethingelse.*")
pp my_profile
File.write("output.mobileprovision", my_profile.download)`

**Comment by ohayon** [comment]
Could you share the output from that script?

**Comment by amartya-ac** [comment]
I'm facing the same issue as well. Any update ?

**Comment by rishijoshi-ibm** [comment]
This issue is bugging me too..!

The command `File.write("output.mobileprovision", my_profile.download)` results in the following error:
`NoMethodError: undefined method 'download' for #<Array:0x007f8660df5e88>`

Though the link, https://github.com/fastlane/fastlane/blob/56456f75fc0377ac774fbf4f14afec73039f74c7/spaceship/lib/spaceship/portal/provisioning_profile.rb clearly shows that method `download` exists.

**Comment by KrauseFx** [comment]
Is `my_profile` an array? if so, can you try `my_profile.first.download`?

**Comment by amartya-ac** [comment]
That worked like wonder @KrauseFx !! Thanks a lot!

Just one small query ; using spaceship I'm even able to download provisioning profiles which are either _invalid_ or _expired_ . 
It's nice to be able to download _invalid_ profiles without asking the team admin to re-generate it. 
But is it possible to get a warning / notification if someone tries to download a provisioning profile which is expired ?

**Comment by rishijoshi-ibm** [comment]
@KrauseFx Calling it through the suggested method worked. Thanks..! But why is it an array? Checked with `my_profile.second.download` resulted in error.
Plus, in the docs also it's not mentioned anywhere to use the suggested method.

**Comment by KrauseFx** [comment]
Yeah, that's weird, taking a look at this now

**Comment by KrauseFx** [comment]
Alright, it was just an error in the docs: https://github.com/fastlane/fastlane/pull/10025
