### ISSUE TITLE
Allow fastlane_credentials to use a specific keychain

### ISSUE THREAD

**Issue by SilverTab** [fastlane/fastlane#9512]
I'm setting up fastlane and jenkins to work together and I'd like to be able to keep all the required certs/passwords in a keychain that I created (not the login/system one). I was wondering if it would be possible for fastlane_credentials to store/read passwords from a keychain that I specify? 

My current issue has to do with `match` (which I understand uses fastlane_credentials to store the Apple Dev portal credentials). Perhaps I'm doing something wrong, but I did copy the internet password created by Fastlane for my Apple Dev Portal account to the keychain that I want to use, and I'm unlocking that keychain before running `match`, but my build ends up failing because `match` tries to prompt for that password.

I am able to get around the issue by setting the `FASTLANE_PASSWORD` environment variable, but I'd rather not to that and use a keychain that I specify if possible. Am I missing something or is the password expected to be in the login (or system?) keychain only?

**Comment by PetrosIchor** [comment]
I believe you can solve your problem with a number of actions.  

Depending on  your flow, setup_jenkins would probably be the simplest.

Or you can get more granular with import_certificate and unlock_keychain.  https://docs.fastlane.tools/actions/#unlock_keychain

Match does allow you to specify a keychain to use.  You just need to ensure it's available and unlocked for use.

**Comment by SilverTab** [comment]
I am specifying a keychain to the match command, and the login info for my Apple Developer account is in that keychain, and I am unlocking the keychain right before calling `match`:

	unlock_keychain(
		path: "/Users/jenkins/Library/Keychains/ios-code-signing.keychain",
		password: keychain_password
	)
	match(
		type: "adhoc",
		keychain_name: "ios-code-signing",
		keychain_password: keychain_password
	)

But I still get this error:

    /Users/jenkins/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-
    2.39.0/credentials_manager/lib/credentials_manager/account_manager.rb:125:in `ask_for_login': 
    [!] Missing password for user <my apple dev portal email>, and running in non-interactive shell 
    (RuntimeError)

**Comment by lacostej** [comment]
This is a limitation of the security gem. mattt/security#4

I hope to address this one day. It would require forking the gem.
