### ISSUE TITLE
compiling issue:  ProtocolBuffers/ProtocolBuffers.h' file not found

### ISSUE THREAD

**Issue by oliverliutao** [fastlane/fastlane#9513]
Xcode compile successfully , but compiling with fast lane get an error 

### Issue Description
[33m▸[0m [39;1mCompiling[0m UIButton+WebCache.m
[33m▸[0m [39;1mCompiling[0m UIImage+GIF.m
[33m▸[0m [39;1mCompiling[0m UIImage+MultiFormat.m
[33m▸[0m [39;1mCompiling[0m UIImage+WebP.m
[33m▸[0m [39;1mCompiling[0m UIImageView+HighlightedWebCache.m
[33m▸[0m [39;1mCompiling[0m UIImageView+WebCache.m
[33m▸[0m [39;1mCompiling[0m UIView+WebCache.m
[33m▸[0m [39;1mCompiling[0m UIView+WebCacheOperation.m
[33m▸[0m [39;1mCompiling[0m FLAnimatedImageView+WebCache.m
[33m▸[0m [39;1mCompiling[0m NSData+ImageContentType.m
[33m▸[0m [39;1mCompiling[0m NSImage+WebCache.m
[33m▸[0m [39;1mCompiling[0m SDImageCache.m
[33m▸[0m [39;1mCompiling[0m SDImageCacheConfig.m
[33m▸[0m [39;1mCompiling[0m SDWebImage-dummy.m
[33m▸[0m [39;1mCompiling[0m SDWebImageCompat.m
[33m▸[0m [39;1mCompiling[0m SDWebImageDecoder.m
[33m▸[0m [39;1mCompiling[0m SDWebImageDownloader.m
[33m▸[0m [39;1mCompiling[0m SDWebImageDownloaderOperation.m
[33m▸[0m [39;1mCompiling[0m SDWebImageManager.m
[33m▸[0m [39;1mCompiling[0m SDWebImagePrefetcher.m
[33m▸[0m [39;1mCompiling[0m UIButton+WebCache.m
[33m▸[0m [39;1mCompiling[0m UIImage+GIF.m
[33m▸[0m [39;1mCompiling[0m UIImage+MultiFormat.m
[33m▸[0m [39;1mCompiling[0m UIImage+WebP.m
[33m▸[0m [39;1mCompiling[0m UIImageView+HighlightedWebCache.m
[33m▸[0m [39;1mCompiling[0m UIImageView+WebCache.m
[33m▸[0m [39;1mCompiling[0m UIView+WebCache.m
[33m▸[0m [39;1mCompiling[0m UIView+WebCacheOperation.m
[33m▸[0m [39;1mBuilding library[0m libSDWebImage.a
[33m▸[0m [39;1mBuilding library[0m libSDWebImage.a
[33m▸[0m [39;1mCopying[0m FLAnimatedImageView+WebCache.h
[33m▸[0m [39;1mCopying[0m NSImage+WebCache.h
[33m▸[0m [39;1mCopying[0m NSData+ImageContentType.h
[33m▸[0m [39;1mCopying[0m SDImageCache.h
[33m▸[0m [39;1mCopying[0m SDImageCacheConfig.h
[33m▸[0m [39;1mCopying[0m SDWebImageDecoder.h
[33m▸[0m [39;1mCopying[0m SDWebImageCompat.h
[33m▸[0m [39;1mCopying[0m SDWebImageDownloader.h
[33m▸[0m [39;1mCopying[0m SDWebImageDownloaderOperation.h
[33m▸[0m [39;1mCopying[0m SDWebImageManager.h
[33m▸[0m [39;1mCopying[0m SDWebImageOperation.h
[33m▸[0m [39;1mCopying[0m SDWebImagePrefetcher.h
[33m▸[0m [39;1mCopying[0m UIButton+WebCache.h
[33m▸[0m [39;1mCopying[0m UIImage+GIF.h
[33m▸[0m [39;1mCopying[0m UIImage+MultiFormat.h
[33m▸[0m [39;1mCopying[0m UIImage+WebP.h
[33m▸[0m [39;1mCopying[0m UIImageView+HighlightedWebCache.h
[33m▸[0m [39;1mCopying[0m UIImageView+WebCache.h
[33m▸[0m [39;1mCopying[0m UIView+WebCache.h
[33m▸[0m [39;1mCopying[0m UIView+WebCacheOperation.h
[33m▸[0m [39;1mBuilding[0m Pods/Pods-LoopsE [Release]
[33m▸[0m [39;1mCheck Dependencies[0m
[33m▸[0m [39;1mCompiling[0m Pods-LoopsE-dummy.m
[33m▸[0m [39;1mCompiling[0m Pods-LoopsE-dummy.m
[33m▸[0m [39;1mBuilding library[0m libPods-LoopsE.a
[33m▸[0m [39;1mBuilding library[0m libPods-LoopsE.a
[33m▸[0m [39;1mBuilding[0m Loops/LoopsE [Release]
[33m▸[0m [39;1mCheck Dependencies[0m
[33m▸[0m [39;1mRunning script[0m '[CP] Check Pods Manifest.lock'

[33m⚠️  [0m/Users/mozat/.jenkins/workspace/pre/Rings/MRAppDelegate.h:26:4: [33m'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead[0m

+ (UIAlertView *)shareSingletonAlertView;
[36m        ^[0m

[33m⚠️  [0m/Users/mozat/.jenkins/workspace/pre/Rings/MRAppDelegate.h:26:4: [33m'UIAlertView' is deprecated: first deprecated in iOS 9.0 - UIAlertView is deprecated. Use UIAlertController with a preferredStyle of UIAlertControllerStyleAlert instead[0m

+ (UIAlertView *)shareSingletonAlertView;
[36m        ^[0m

[33m▸[0m [39;1mPrecompiling[0m Rings/Loops-Prefix.pch

[31m❌  [0m/Users/mozat/.jenkins/workspace/pre/Rings/Models/protocol/head/Head.pb.h:3:9: [31m'ProtocolBuffers/ProtocolBuffers.h' file not found[0m

#import <ProtocolBuffers/ProtocolBuffers.h>
[36m           ^[0m

[33m▸[0m [39;1mPrecompiling[0m Rings/Loops-Prefix.pch

[31m❌  [0m/Users/mozat/.jenkins/workspace/pre/Rings/Models/protocol/head/Head.pb.h:3:9: [31m'ProtocolBuffers/ProtocolBuffers.h' file not found[0m

#import <ProtocolBuffers/ProtocolBuffers.h>
[36m        ^[0m

** ARCHIVE FAILED **

The following build commands failed:
ProcessPCH /Users/mozat/Library/Developer/Xcode/DerivedData/Loops-cmcbzwixtfkjcxbzhpqtekvmvmyh/Build/Intermediates/ArchiveIntermediates/LoopsE/PrecompiledHeaders/Loops-Prefix-gkkwaakaijntqdcfnyyreoyfktfs/Loops-Prefix.pch.pch Rings/Loops-Prefix.pch normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
ProcessPCH /Users/mozat/Library/Developer/Xcode/DerivedData/Loops-cmcbzwixtfkjcxbzhpqtekvmvmyh/Build/Intermediates/ArchiveIntermediates/LoopsE/PrecompiledHeaders/Loops-Prefix-dvduoxymqasoudgtudgjzofxjnhx/Loops-Prefix.pch.pch Rings/Loops-Prefix.pch normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)
[21:05:52]: [31mExit status: 65[0m
[21:05:52]: [33m📋  For a more detailed error log, check the full log at:[0m
[21:05:52]: [33m📋  /Users/mozat/Library/Logs/gym/LOOPS.DP-LoopsE.log[0m

+-------------+-------------------------+
|           [32m[33mBuild environment[0m           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.39.1                  |
| sdk         | iPhoneOS10.2.sdk        |
+-------------+-------------------------+

+------------------------------------+----------------------------------------------------------------+
|                                            [33mLane Context[0m                                             |
+------------------------------------+----------------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                            |
| PLATFORM_NAME                      | ios                                                            |
| LANE_NAME                          | ios pre                                                        |
| FL_CHANGELOG                       | update                                                         |
| SIGH_PROFILE_TYPE                  | enterprise                                                     |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.loops.Enterprise"=>"match InHouse com.loops.Enterprise"} |
+------------------------------------+----------------------------------------------------------------+
[21:05:52]: [31mError building the application - see the log above[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | changelog_from_git_commits          | 0           |
| 4    | automatic_code_signing              | 2           |
| 5    | ensure_git_branch                   | 0           |
| 6    | match                               | 5           |
| 💥   | [31mgym[0m                                 | 118         |
+------+-------------------------------------+-------------+

[21:05:52]: [31mfastlane finished with errors[0m
[31m
[!] Error building the application - see the log above[0m
Build step 'Execute shell' marked build as failure
---
--- Git Changelog ---
---

Sending e-mails to: liutao@mozat.com lipeng@mozat.com fengbo@mozat.com
ERROR: Could not connect to SMTP host: localhost, port: 25
javax.mail.MessagingException: Could not connect to SMTP host: localhost, port: 25;
  nested exception is:
	java.net.ConnectException: Connection refused
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1934)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:638)
	at javax.mail.Service.connect(Service.java:295)
	at javax.mail.Service.connect(Service.java:176)
	at javax.mail.Service.connect(Service.java:125)
	at javax.mail.Transport.send0(Transport.java:194)
	at javax.mail.Transport.send(Transport.java:124)
	at hudson.tasks.MailSender.run(MailSender.java:131)
	at hudson.tasks.Mailer.perform(Mailer.java:170)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:286)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:231)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1900)
	... 18 more
Finished: FAILURE
### Environment

/Users/mozat/.rvm/gems/ruby-2.3.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:5:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
	from /Users/mozat/.rvm/gems/ruby-2.3.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:5:in `<class:Noexec>'
	from /Users/mozat/.rvm/gems/ruby-2.3.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems-bundler/noexec.rb:3:in `<top (required)>'
	from /Users/mozat/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /Users/mozat/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /Users/mozat/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /Users/mozat/.rvm/gems/ruby-2.3.3@global/gems/rubygems-bundler-1.4.4/lib/rubygems_executable_plugin.rb:4:in `block in <top (required)>'
	from /Users/mozat/.rvm/gems/ruby-2.3.3@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:50:in `block in run'
	from /Users/mozat/.rvm/gems/ruby-2.3.3@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `each'
	from /Users/mozat/.rvm/gems/ruby-2.3.3@global/gems/executable-hooks-1.3.2/lib/executable-hooks/hooks.rb:49:in `run'
	from /Users/mozat/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:10:in `<main>'

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by thebugcode** [comment]
Hi @oliverliutao . Can you post the contents of your Fastfile here? 

It could be the case, that in Xcode you compile using the Debug configuration, while fastlane tries to build your app with the Release configuration by default. Try switching to Release in your Schema, and you should see the same compile error in Xcode

**Comment by oliverliutao** [comment]
Hi @thebugcode Thanks a lot for your replay , I've found reason,  It seems that version of cocoapods is incorrect, so can not download ProtoBuf library.
