### ISSUE TITLE
Locally generated FASTLANE_SESSION does not work on CI machine

### ISSUE THREAD

**Issue by godrei** [fastlane/fastlane#9518]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

For first thank you guys for the Fastlane tools!

I'm using spaceship for apple developer portal authentication, generating provisioning profile and code sign identity.

On my developer account i have 2FA enabled, so i use `fastlane spaceauth -u my@email.com` command (on my local machine) to obtain the session cookie, which i use to set FASTLANE_SESSION env var.
With this setup `Spaceship::Portal.login(username, password)` works great on my local machine.

When i try to run my script on our build vm (which runs in a different country) it fails.

If i generate the session cookie on the build vm (through remote access) my script works well on a build vm, but this new session does not work on my local machine.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

my fastlane and spaceship dependencies are defined in a Gemfile (fastlane (2.39.1), spaceship (1.0.0))

my script:

```
require 'spaceship'
require 'fastlane'

ENV['FASTLANE_PASSWORD'] = password
ENV['FASTLANE_SESSION'] = session

Spaceship::Portal.login(username, password)
```

the failed output:

```
/usr/local/lib/ruby/gems/2.4.0/gems/spaceship-1.0.0/lib/spaceship/two_step_client.rb:41:in `handle_two_step': Invalid 2 step response {"trustedPhoneNumbers"=>[{"rawNumber"=>"*******20", "numberWithDialCode"=>"+36 •••••••20", "verifiedDate"=>"03/28/2017 05:39:30 PM", "obfuscatedNumber"=>"•••••••20", "id"=>1, "updateDate"=>"03/28/2017 05:39:30 PM", "countryDialCode"=>"36", "countryCode"=>"HU", "pushMode"=>"sms", "pending"=>false, "lastTwoDigits"=>"20", "createDate"=>"09/20/2016 10:02:26 PM", "number"=>"*******20", "verified"=>true}], "securityCode"=>{"length"=>6, "tooManyCodesSent"=>false, "tooManyCodesValidated"=>false, "securityCodeLocked"=>false}, "authenticationType"=>"hsa2", "recoveryUrl"=>"https://iforgot.apple.com/phone/add?prs_account_nm=[REDACTED]&autoSubmitAccount=true&appId=[REDACTED]", "cantUsePhoneNumberUrl"=>"https://iforgot.apple.com/iforgot/phone/add?context=cantuse&prs_account_nm=[REDACTED]&autoSubmitAccount=true&appId=[REDACTED]", "recoveryWebUrl"=>"https://iforgot.apple.com/password/verify/appleid?prs_account_nm=[REDACTED]&autoSubmitAccount=true&appId=[REDACTED]", "repairPhoneNumberUrl"=>"https://gsa.apple.com/appleid/account/manage/repair/verify/phone", "repairPhoneNumberWebUrl"=>"https://appleid.apple.com/widget/account/repair?#!repair", "aboutTwoFactorAuthenticationUrl"=>"https://support.apple.com/kb/HT204921", "managedAccount"=>false, "supportsRecovery"=>true, "trustedPhoneNumber"=>{"rawNumber"=>"*******20", "numberWithDialCode"=>"+36 •••••••20", "verifiedDate"=>"03/28/2017 05:39:30 PM", "obfuscatedNumber"=>"•••••••20", "id"=>1, "updateDate"=>"03/28/2017 05:39:30 PM", "countryDialCode"=>"36", "countryCode"=>"HU", "pushMode"=>"sms", "pending"=>false, "lastTwoDigits"=>"20", "createDate"=>"09/20/2016 10:02:26 PM", "number"=>"*******20", "verified"=>true}, "hsa2Account"=>true} (RuntimeError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/spaceship-1.0.0/lib/spaceship/client.rb:317:in `send_shared_login_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spaceship-1.0.0/lib/spaceship/portal/portal_client.rb:13:in `send_login_request'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spaceship-1.0.0/lib/spaceship/client.rb:431:in `do_login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spaceship-1.0.0/lib/spaceship/client.rb:246:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spaceship-1.0.0/lib/spaceship/client.rb:93:in `login'
	from /usr/local/lib/ruby/gems/2.4.0/gems/spaceship-1.0.0/lib/spaceship/portal/spaceship.rb:22:in `login'
	from /tmp/122550714/step_src/step.rb:34:in `<main>'
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
[08:50:57]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.2                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.57.0       |
| openssl                   | 2.0.3        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
</details>


*generated on:* **2017-06-16**
</detai
```

**Comment by mpirri** [comment]
Why are you looking to use the same `FASTLANE_SESSION` on both CI and your local machine? Can you generate a session on each machine (store the `FASTLANE_SESSION` into an environment variable) and use the appropriate session on each machine?

**Comment by godrei** [comment]
@mpirri our ci builds are running in a non-interactive environment, so i'm not able to provide the 2FA code during the builds.

Based on the [Support for CI machines](https://github.com/fastlane/fastlane/tree/master/spaceship#support-for-ci-machines) docs, i thought, that i can generate  the `FASTLANE_SESSION` on my local machine and later use this for  ci builds.

We have a vm stack for our ci builds, so i can not be sure which vm will run my current build.

**Comment by KrauseFx** [comment]
Yes, generating the `FASTLANE_SESSION` should do the trick. Does it work when you use one of the fastlane tools? Did you also see https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth

**Comment by godrei** [comment]
@KrauseFx 

_Did you also see https://docs.fastlane.tools/best-practices/continuous-integration/#two-step-or-two-factor-auth_


Yes i have seen, and i use `fastlane spaceauth -u user@email.com` to generate the session token. But i do not want to deploy to TestFlight/iTunes Connect, so i did not use `FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD`, just the `FASTLANE_SESSION` for developer portal authentication.

_Does it work when you use one of the fastlane tools?_

I use spaceship as a ruby gem.

Yes, it works when:

- i generate the token on my local machine and use the token on my local machine
- i generate the token on one of our ci machines and use it on any of our ci machines

It does not work when:

- i generate the token on my local machine and use it on any of our ci machines
- i generate the token on one of our ci machines and use the token on my local machine

So i think the token is related to the geolocation maybe? I'm working in Hungary and our ci machines are hosted in different countries in US.

**Comment by mpirri** [comment]
@godrei It does appear that you are running into trouble due to location-aware session tokens. For these sorts of cases, there is no obvious answer for how to create one `FASTLANE_SESSION` that can be used across both your machine and the CI machine.

One possible workaround would be to create a separate iTunesConnect user on your development team for the CI box with upload permission. This account can then have a separate `FASTLANE_SESSION` from your account. Alternatively, your CI account could also disable 2FA and use a secure password and then there is no need to concern yourself with `FASTLANE_SESSION` at all.

I wish I had a better answer for you - please let us know if there are any other questions we can help you with.

**Comment by godrei** [comment]
@mpirri Thanks for the clarification, i appreciate your help!

**Comment by godrei** [comment]
From my side you guys can close this issue. @mpirri  answered my questions.

**Comment by mpirri** [comment]
Great thanks!  Closing now.  🚀
