### ISSUE TITLE
Can't run a lane that is in not part of a platform if default_platform is specified

### ISSUE THREAD

**Issue by fcy** [fastlane/fastlane#952]
Given this Fastfile:

```
default_platform :ios

lane xcode_pre_compile do
  # organize_imports and other custom actions
end

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end
end
```

When I try to run `fastlane xcode_pre_compile` I get this error:

> ...
>[16:15:42]: ------------------------------
>[16:15:42]: --- Step: default_platform ---
>[16:15:42]: ------------------------------
>[16:15:42]: Variable Dump:
>[16:15:42]: {:DEFAULT_PLATFORM=>:ios}
>[16:15:42]: Could not find lane 'ios xcode_pre_compile'. Available lanes: xcode_pre_compile, ios test, ios unit_test, ios snapshot_test, ios functional_test

How can I run a lane that doesn't belong to a platform while still having a default platform?

Fastlane version: 1.44.0

**Comment by Rking788** [comment]
I think you are missing a ':' in front of xcode_pre_compile in your lane definition. So it should actually be:

```
lane xcode_pre_compile do
  # organize_imports and other custom actions
end
```

Other than that, it doesn't seem like you can have a lane that doesn't belong to a platform when using the 'default_platform' option. It will apply the default platform and then look for your lane belonging to that platform and not find it. If you comment the default_platform line and try running it, you should see what I mean. Maybe someone can provide a way around this. I looked at the sample on this page as a guide:

https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md

As you can see later on in the Fastfile there is a lane that doesn't belong to a platform and the sample fastlane commands explicitly provide the platform.

**Comment by fcy** [comment]
I guess this is a feature request them. Based on the error message it should be totally possible for Fastlane to find a "platform-orphan" lane after not finding it in the default platform lanes.

The missing `:` was a typo, thanks for catching it.

**Comment by KrauseFx** [comment]
Thanks for posting this @fcy, I can reproduce this issue and can confirm this is a bug I need to fix :+1:

**Comment by KrauseFx** [comment]
Fixed with https://github.com/fastlane/fastlane/commit/0c7a97b029db453bc7049cdd1c9e338de6590452, pushing a new release now :+1: 
Thanks again for letting me know :rocket:
