### ISSUE TITLE
integrating with Continuous Translation tools like Weblate, Transifex, etc.

### ISSUE THREAD

**Issue by eighthave** [fastlane/fastlane#9520]
We've been using Weblate and Transifex to work with translators for our app strings for years now.  It can really make it dead simple to work with translators in many languages.  We've also been trying out techniques for doing the same with the app store descriptive materials, like what Fastlane manages.  The big problem is that the Fastlane file layout is quite difficult to integrate with translation tools:

* they expect a single file for source strings (not _title.txt_, _full_description.txt_, _short_description.txt_, etc.)
* they work much better with real file formats like .po .xliff .json .yaml .xml rather than unstructured plain text
* char limits, notes to translators, etc. need to be in the source file (e.g .xliff)

Have there been any thoughts about how to integrate with standard translation workflows like these?  What are people using for translation when using Fastlane?

So far, the best "solution" I've seen feels like a workaround: managing the translations in a separate tree of XLIFF files, then having those files converted using a plugin:
https://github.com/danielkiedrowski/fastlane-plugin-onesky

**Comment by mpirri** [comment]
Thanks for your feedback about this! What is it specifically about the `onesky` plugin that makes it feel like a workaround?  Do you have a sense of what your ideal workflow would look like for this?

**Comment by eighthave** [comment]
The plugin workflow means that there two sets of files to maintain: 
* localizations/*.xliff
* metadata/\<locale>/*.txt

I suppose it would be OK if the *.txt files were entirely hidden from the developer, except for maybe entries in _.gitignore_.  Also, XLIFF makes it easy to break up the long description into manageable chunks, but those chunks then need to be reassembled to make the .txt file.  That logic will be custom to the plugin and perhaps even to the developer.  So the developer has to be aware of the formats.

I outlined my ideal workflow in https://github.com/WeblateOrg/weblate/issues/1525:

1. Weblate pulls source from git
2. translators work in Weblate
3. translations get pulled into app's source directly where Fastlane expects them
4. those translations are directly published to Google Play by Fastlane
5. F-Droid automatically uses those translations from git

**Comment by mpirri** [comment]
Regarding your first point - it does feel like you'd want to use the .xliff files as the "source of truth" and then dynamically build the _fastlane_ metadata files from that.

Anyhow, this workflow does sound great. Unfortunately it isn't really something the core _fastlane_ team can work on right now. It would be an amazing _fastlane_ plugin, though. Any chance we could convince you to take a crack at building something like this?  😄 

Thanks so much for the consideration, and I'm sorry I don't have better news for you.  🚀

**Comment by eighthave** [comment]
Upon thinking about this a bit more, the issue really is how to
represent this to the fastlane user.  Right now, the docs point to the
text files, e.g. _metadata/en-US/full_description.txt_, as the place for
the developer to manage their texts.  With the plugin managing a
separate file tree of XLIFF files, then the story becomes more like
"well, sometimes there will be another set of files and those files will
actually be the canonical ones".

One easy way to deal with that is just have the files right next to the
standard fastlane location, e.g.
_metadata/en-US/full_description.xliff_, that would at least be easily
visible to someone following the docs.  The downside with that is that
there are multiple .xliff files that serve as the source (title, short
description, full description, changelogs), and lots of translations
systems assume a single file per-language.

I'm happy to try my hand at writing a plugin for this, once I figure out
the right setup and user experience.  So I'm mostly looking for feedback
at this point.

**Comment by tobiasKaminsky** [comment]
We are also stumbled about this problem. Would be great if there will be a solution :+1: 
I can help you with testing @eighthave

**Comment by janpio** [comment]
Wouldn't it be enough to add a "DO_NOT_EDIT_BUT_READ_THIS.txt" into the `metadata` folder that explains that these files are generated automatically when using `fastlane` automatically by a plugin (and list exactly which ones)? The "handling" of the data from truth to fastlane structure will all be done by a plugin or via actions in a lane, right?

**Comment by romanr** [comment]
Looks like it's not `onesky` plugin itself that does the conversion but this one, linked from onesky repo: https://github.com/vmalyi/fastlane-plugin-localization

**Comment by tobiasKaminsky** [comment]
A real decent plugin which supports transifex -> fastlane would indeed be great and therefore I hope that this issue can remain open as an enhancement proposal 
(this does not mean that the devs have to do it, but maybe there will be an user contribution)

**Comment by grote** [comment]
For Transifex, I am now using a small script in Transportr to fetch the descriptions directly from the normal `strings.xml` files:

https://github.com/grote/Transportr/blob/master/fastlane/generate_metadata.py

Although it is just meant as a temporary workaround, maybe it is useful for others as well.

**Comment by tobiasKaminsky** [comment]
Thank you @grote, this is indeed a good start.
While trying it, I get 
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 17: ordinal not in range(128)

which is because of a german umlaut (ä).

Why do you append the app title on each description.txt?

**Comment by tobiasKaminsky** [comment]
Solved via

> import codecs

and use utf-8
> with codecs.open(file_path, 'w', 'utf-8') as f:

**Comment by tobiasKaminsky** [comment]
As above, this is not really fixed yet.

**Comment by taquitos** [comment]
Totally understand, 🤞 somebody wants to pick this task and build a plugin. That would be awesome.

**Comment by romanr** [comment]
Dear @fastlane-bot please don't close this issue. There's still a lot of interest in this.

**Comment by romanr** [comment]
Dear @fastlane-bot please don't close this issue. There's still a lot of interest in this.

**Comment by janpio** [comment]
There seems to have been some progress on this on Weblate side: https://github.com/WeblateOrg/weblate/issues/1525#issuecomment-463960391 ❤️
