### ISSUE TITLE
Sigh is overwriting the existing adhoc provisioning profile in the developer portal and completely changes its name

### ISSUE THREAD

**Issue by dineshkrishna** [fastlane/fastlane#9522]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[10:24:05]: -------------------------------------------------
[10:24:05]: --- Step: Verifying required fastlane version ---
[10:24:05]: -------------------------------------------------
[10:24:05]: Your fastlane version 2.33.0 matches the minimum requirement of 2.33.0  ✅
[10:24:05]: ------------------------------
[10:24:05]: --- Step: default_platform ---
[10:24:05]: ------------------------------
[10:24:05]: Driving the lane 'ios build' 🚀
[10:24:05]: ------------------
[10:24:05]: --- Step: cert ---
[10:24:05]: ------------------

+---------------+--------------------------------------+
|               Summary for cert 2.33.0                |
+---------------+--------------------------------------+
| development   | false                                |
| force         | false                                |
| username      | dinesh-kumar@fedex.com               |
| team_id       | SARSE24G85                           |
| keychain_path | /Users/dineshkrishna108/Library/Key  |
|               | chains/login.keychain-db             |
| platform      | ios                                  |
+---------------+--------------------------------------+

[10:24:05]: Starting login with user 'dinesh-kumar@fedex.com'
[10:24:10]: Successfully logged in
[10:24:12]: Certificate 288TG347J4 (iOS Distribution) can't be found on your local computer
[10:24:13]: Found the certificate RC6G64496G (iOS Distribution) which is installed on the local machine. Using this one.
[10:24:14]: Verifying the certificate is properly installed locally...
[10:24:14]: Successfully installed certificate RC6G64496G
[10:24:14]: Use signing certificate 'RC6G64496G' from now on!
[10:24:14]: ------------------
[10:24:14]: --- Step: sigh ---
[10:24:14]: ------------------

+-------------------------------------+------------------------+
|                   Summary for sigh 2.33.0                    |
+-------------------------------------+------------------------+
| force                               | true                   |
| adhoc                               | true                   |
| development                         | false                  |
| skip_install                        | false                  |
| app_identifier                      | com.fedex.mobile.home  |
| username                            | dinesh-kumar@fedex.com |
| team_id                             | SARSE24G85             |
| ignore_profiles_with_different_name | false                  |
| cert_id                             | RC6G64496G             |
| skip_fetch_profiles                 | false                  |
| skip_certificate_verification       | false                  |
| platform                            | ios                    |
+-------------------------------------+------------------------+

[10:24:14]: Starting login with user 'dinesh-kumar@fedex.com'
[10:24:17]: Successfully logged in
[10:24:17]: Fetching profiles...
[10:24:23]: Verifying certificates...
[10:24:26]: Found 2 matching profile(s)
[10:24:26]: Recreating the profile
[10:24:29]: Creating new provisioning profile for 'com.fedex.mobile.home' with name 'com.fedex.mobile.home AdHoc' for 'ios' platform
[10:24:33]: Downloading provisioning profile...
[10:24:35]: Successfully downloaded provisioning profile...
[10:24:35]: Installing provisioning profile...
/Users/dineshkrishna108/Desktop/Beta Build 2.4.0 Build 1/Projects/code/AdHoc_com.fedex.mobile.home.mobileprovision
[10:24:35]: Setting Provisioning Profile type to 'ad-hoc'
[10:24:35]: -----------------------------------------
[10:24:35]: --- Step: update_project_provisioning ---
[10:24:35]: -----------------------------------------
[10:24:35]: You’re updating provisioning profiles directly in your project, but have you considered easier ways to do code signing?
[10:24:35]: https://docs.fastlane.tools/codesigning/GettingStarted/
[10:24:35]: Downloading root certificate from (https://www.apple.com/appleca/AppleIncRootCertificate.cer) to path '/tmp/AppleIncRootCertificate.cer'
+---------------------+--------------------------------------+
|                        Lane Context                        |
+---------------------+--------------------------------------+
| DEFAULT_PLATFORM    | ios                                  |
| PLATFORM_NAME       | ios                                  |
| LANE_NAME           | ios build                            |
| CERT_FILE_PATH      | /Users/dineshkrishna108/Desktop/Bet  |
|                     | a Build 2.4.0 Build                  |
|                     | 1/Projects/code/RC6G64496G.cer       |
| CERT_CERTIFICATE_ID | RC6G64496G                           |
| SIGH_PROFILE_PATH   | /Users/dineshkrishna108/Desktop/Bet  |
|                     | a Build 2.4.0 Build                  |
|                     | 1/Projects/code/AdHoc_com.fedex.mob  |
|                     | ile.home.mobileprovision             |
| SIGH_PROFILE_PATHS  | ["/Users/dineshkrishna108/Desktop/B  |
|                     | eta Build 2.4.0 Build                |
|                     | 1/Projects/code/AdHoc_com.fedex.mob  |
|                     | ile.home.mobileprovision"]           |
| SIGH_UDID           | 0eaa1bbd-3375-496b-b039-7368a4caf4e  |
|                     | 4                                    |
| SIGH_UUID           | 0eaa1bbd-3375-496b-b039-7368a4caf4e  |
|                     | 4                                    |
| SIGH_PROFILE_TYPE   | ad-hoc                               |

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.2                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.11.0 (Apple Git-81)               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.2 (16C67)                        |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 8.3.1                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.33.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #	cocoapods
    
  end

    lane :build do

    #increment_build_number # version bump

    #match(
     # app_identifier: “com.fedex.mobile.home”, 
     # type:"adhoc"
    #)

   #cert 
   #sigh(force: true, adhoc: true) # Sign force ensures all devices are added to the prov. Profile

    update_project_provisioning(
    xcodeproj: “FedExMobile.xcodeproj",
    profile: "./AdHoc_com.fedex.mobile.home.mobileprovision”) # temp solution as NULL prevents developer portal login


   gym(scheme: "FedEx Dev", export_method: "ad-hoc”, configuration: “Testing”, output_name: “FedEx.ipa")

   # gym(
    #  scheme: “FedEx Dev”,
    #  use_legacy_build_api: true,
    #  configuration: "Debug"
    #) # Build your app - more options available

  end


  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
   cert 
   sigh

    gym(scheme: "FedEx") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "FedEx") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.fedex.mobile.home" # The bundle identifier of your app
apple_id "dinesh-kumar@fedex.com" # Your Apple email address

team_id "SARSE24G85" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.33.0  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.9.28       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.0       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-19**
</details>

**Comment by mpirri** [comment]
If you specify the `provisioning_name:` parameter when calling `sigh`, you can set the name of the AdHoc profile that is generated for you application.  So, instead of calling:
`sigh(force: true, adhoc: true)`
You can call (for instance):
`sigh(force: true, adhoc: true, provisioning_name: "my_profile_name")`

I hope this is helpful - please let us know if you have any other questions!

**Comment by dineshkrishna** [comment]
Hi Mark,

Thank you very much for the quick response. 

One more question is How do I check in the newly generated provisioning profile UUID into the project file? Because in the Jenkins server when the job checks out the project it takes the current UUID whichever is in the repository. But I also do the gym in fastlane file, I do the cert and sigh for re-generating the provisioning profile. I am not checking in the project from jenkins server.

This changes the UUID of the provisioning profile and the provisioning profile at the developer portal generated by sigh has the UUID changed as well. So now the code signing fails in this situation for my job(Jenkins(to check out and upload binary to my server + Fastlane(to code sign, build and package the app). I did the Update Provisioning profile method in fastfile to update the UUID in the project file before the gym. But my code signing fails even then. Just wanted to know if I am doing it the right way or is there better way of doing it when I am not using match.

Thanks, 
Dinesh

**Comment by taquitos** [comment]
Hmm, that sounds strange. Match should work for you. Have you tried implementing all the suggestions in the [Code Signing Getting Started Guide](https://docs.fastlane.tools/codesigning/getting-started/)? If that doesn't help, we also have a [troubleshooting guide](https://docs.fastlane.tools/codesigning/troubleshooting/)
