### ISSUE TITLE
latest apk version on play store counterpart to latest_testflight_version

### ISSUE THREAD

**Issue by phillippbertram** [fastlane/fastlane#9530]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

It would be nice, if there were an **android** counterpart for ios `latest_testflight_version` that will return the latest version code of my latest uploaded `apk` to any google play store track.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

--

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.3                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.3/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>
```ruby
# private
```
</details>

<details><summary>`./fastlane/Appfile`</summary>
# private
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.39.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| i18n                      | 0.8.4        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| cocoapods                 | 1.2.1        |
| clamp                     | 0.6.5        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| slather                   | 2.4.2        |
| curb                      | 0.9.3        |
| badge                     | 0.8.4        |
</details>

*generated on:* **2017-06-20**
</details>

**Comment by muhammadsr** [comment]
+1....Totally would be useful.

**Comment by mpirri** [comment]
This sounds likes a really useful feature to have. We are always looking for good PRs from our awesome contributors to merge into `fastlane`. Unfortunately, building this feature isn't something the core team can take on right now, but any chance that one of you would be interested at taking a stab at implementing the functionality?  Given the relative ease of working with the Play Store APIs (vs. App Store), I'd think it would be an interesting project without a huge amount of difficulty.

Thanks so much for the feature request! 🚀

**Comment by phillippbertram** [comment]
I just saw the latest release comments for [2.45.0](https://github.com/fastlane/fastlane/releases/tag/2.45.0) that this feature is now implemented 😍 

The action is called `google_play_track_version_codes`

**Comment by KrauseFx** [comment]
Yeah 🚀 Let us know how it works for you. There will be a follow-up bugfix in the next release for `google_play_track_version_codes` 👍

**Comment by phillippbertram** [comment]
I think we have to wait for the bug fix, I did not get it work right now ;)

**Comment by phillippbertram** [comment]
I still think, that a dedicated action for getting the latest version code would be very useful.

With version 2.46.0 `google_play_track_version_codes` now works and can be used to get an array of version codes for a given track 🎉

But If you want to get the "latest" version code you have to fetch the versions from each track find the gratest number manually. An own action would simplify this process a lot 😁
