### ISSUE TITLE
slather action missing support travis-pro

### ISSUE THREAD

**Issue by matthewellis** [fastlane/fastlane#9531]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The Fastlane action for slather works correctly but is missing the option for travis-pro that slather now supports. 

When checking `actions/slather.rb` i found a comment pointing to an [old slather commit]( https://github.com/SlatherOrg/slather/blob/cbc5099cd25beb43fd978b7a3e5428f02230122d/lib/slather/command/coverage_command.rb) containing the parameters for the coverage command.

I would propose that the action is updated to be compatible with [this version](https://github.com/SlatherOrg/slather/blob/v2.4.2/lib/slather/command/coverage_command.rb) of the command.

**Comment by mpirri** [comment]
Thanks so much for the request. Unfortunately I don't think this is something the core team can take on right now, but we are always looking for good PRs from our awesome contributors. Any chance you want to make a PR adding this to _fastlane_?  😄 

Thanks so much for the feature request! 🚀

**Comment by matthewellis** [comment]
@mpirri Hey i have added a PR for this now, would you be able to review my code for this?
