### ISSUE TITLE
[FEATURE REQUEST] App previews iOS11

### ISSUE THREAD

**Issue by matteomartinelli** [fastlane/fastlane#9532]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
From iOS11, in iTunesConnect you can upload up to 3 app previews and at the moment it's not handled by fastlane.

By using the current functionality which allows you to upload one trailer it crashes dramatically since iTC is changed.

**Comment by taquitos** [comment]
Love the idea, it's definitely something we want to support. Could you open a new issue with the crash information you mention?

Also, if you wanted to update _fastlane_ to add this functionality, it could be a fun change 😁

**Comment by matteomartinelli** [comment]
Addressed [here](https://github.com/fastlane/fastlane/issues/9660)

**Comment by KrauseFx** [comment]
Let's move all discussion to https://github.com/fastlane/fastlane/issues/9660 :+1:
