### ISSUE TITLE
TestFlight notified all external testers from other group although I only distributed build to one group.

### ISSUE THREAD

**Issue by keeplearningh** [fastlane/fastlane#9534]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am wondering if anyone knows about this problem and can help me solve this.
I am using pilot commands below:

desc ".............."
lane :beta do
ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
pilot(
distribute_external:true,
ipa: "path to ipa file",
changelog: "Something",
groups: ["A Group"]
)
end.

Everything is fine; however, I only want to distribute the build to "A Group", but TestFlight would notify other external testers from other group although the build is only distributed to "A Group". Basically testers from "B Group" for example would receive notification that there is a new build available although they really don't see this new build on their TestFlight app. So it's annoying that they keep getting notifications, but there is no new build.
Is this a TestFlight issue? Or is there any pilot command that I am missing. I have been reading everywhere, but I have not been able to figure this out.

Thank you for your help!

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G31)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | 
| LC_ALL   | en_US.UTF-8 | 
| LANGUAGE | en_US.UTF-8 | 

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`
# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.37.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    pilot(
       distribute_external:true,
       ipa: "Path to iPA",
       changelog: "Change Log",
       groups: ["A Group"]
     )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Submit a new release Build to Apple TestFlight"
  lane :release do
    ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t DAV"
    pilot(
       distribute_external:true,
       ipa: "Path to iPA",
       changelog: "Change Log",
       groups: ["A Group"]
     )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end

**Comment by taquitos** [comment]
Hey @keeplearningh could you post your output too? That will help us diagnose where the issue is happening. Thanks 👍

**Comment by keeplearningh** [comment]
Below is my output. Thank you for your help!

Seems like launching fastlane takes a while - please run
[sudo] gem cleanup
to uninstall outdated gems and make fastlane launch faster
Alternatively it's recommended to start using a Gemfile to lock your dependencies
To get started with a Gemfile, run
$ bundle init
$ echo 'gem "fastlane"' >> Gemfile
$ bundle install
After creating the Gemfile and Gemfile.lock, commit those files into version control
For more information, check out https://guides.cocoapods.org/using/a-gemfile.html
-----------------------------
--- Step: update_fastlane ---
-----------------------------
Looking for updates for fastlane...
Nothing to update
Please help us test early releases of fastlane by opting into nightly builds
Just replace your `update_fastlane` call with
update_fastlane(nightly: true)
Nightly builds are reviewed and tested just like the public releases
-------------------------------------------------
--- Step: Verifying required fastlane version ---
-------------------------------------------------
Your fastlane version 2.41.0 matches the minimum requirement of 2.37.0
------------------------------
--- Step: default_platform ---
------------------------------
Driving the lane 'ios beta'
-------------------
--- Step: pilot ---
-------------------
Login to iTunes Connect (####################)
Login successful
Ready to upload new build to TestFlight (App: ##########)...
Going to upload updated app to iTunes Connect
This might take a few minutes. Please don't interrupt the script
iTunes Transporter successfully finished its job
--------------------------------------------------------------------
Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
--------------------------------------------------------------------
Successfully uploaded the new binary to iTunes Connect
If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
Waiting for iTunes Connect to finish processing the new build (#######)
Waiting for iTunes Connect to finish processing the new build (#######)
Waiting for iTunes Connect to finish processing the new build (#######)
Waiting for iTunes Connect to finish processing the new build (#######)
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Build doesn't show up in the build list any more, waiting for it to appear again
Successfully finished processing the build #######
Successfully set the changelog for build
Distributing new build to testers: #########
Successfully distributed build to External testers
  +------+---------------------+-------------+
  |             fastlane summary             |
  +------+---------------------+-------------+
  | Step | Action              | Time (in s) |
  +------+---------------------+-------------+
  | 1    | update_fastlane     | 7           |
  | 2    | Verifying required  | 0           |
  |      | fastlane version    |             |
  | 3    | default_platform    | 0           |
  | 4    | pilot               | 919         |
  +------+---------------------+-------------+
fastlane.tools just saved you 15 minutes!

**Comment by keeplearningh** [comment]
Has anyone run into this issue?

**Comment by AndyDunn** [comment]
Yea, I'm getting this now. In my fastfile I only have `groups: ["Group A"]`, yet it was distributed to "External Testers" as well.

Is this a known issue or has anyone any suggestions on how to resolve it?

**Comment by ohayon** [comment]
Hey @keeplearningh - the Group B you mention, is that a group that has existed for more than about 5 or six months? 

@AndyDunn - same question for you, has your app been in TestFlight for a while that your "External Testers" group has been around for a while?

To add some context for why I am asking this, TestFlight made some changes on their end a few months ago that changed the way these groups are handled and its possible that something has changed again with the way that groups that existed before these changes are handled.

Thank you! 🐙 🚀

**Comment by AndyDunn** [comment]
@ohayon This app has been around for a while actually. I had to go through the process of 'upgrading' the TestFlight account from the old style to the new style a few months ago. Perhaps that has something to do with it?

**Comment by ohayon** [comment]
Hmmm I think it could have something to do with it. When you specify that you want to `distribute_externally` we make sure to notify the default External Testers group to preserve the legacy behavior 😄

**Comment by AndyDunn** [comment]
That would make sense then. So should I remove the `distribute_externally` from my settings in fastfile  or else remove the External Testers group from TestFlight?

**Comment by ohayon** [comment]
Yeah, you can remove that parameter and just specify the groups directly. 😄
