### ISSUE TITLE
Gym failing on exportArchive

### ISSUE THREAD

**Issue by foulkesjohn** [fastlane/fastlane#9538]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

My build is passing for the most part but fails on the last step with the following output:

__Can't upgrade to 2.39.2 due to AVG bug__

```
error: exportArchive: The operation couldn’t be completed. (IDEDistributionErrorDomain error 3.)

Error Domain=IDEDistributionErrorDomain Code=3 "(null)" UserInfo={IDEDistributionErrorSigningIdentityToItemToUnderlyingErrorKey={
    "<DVTSigningCertificate: 0x7fbb9fc86320; name='iPhone Distribution: My Company Ltd (6767CY3Y7D)', hash='39708C880D3BA3ACBA21ECF636AEAC50A1A41440', serialNumber='6FFFD06B79A4D1B8', certificateKind='1.2.840.113635.100.6.1.4, issueDate='2016-12-09 13:43:04 +0000''>" =     {
        "<IDEDistributionItem: 0x7fbba5025af0 'uk.co.mycompany.app' '<DVTFilePath:0x7fbb9fc3aab0:'/Users/John/code/app/target/app_sandbox_1.17_0.xcarchive/Products/Applications/app.app'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=7 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=None of the valid provisioning profiles allowed the specified entitlements: application-identifier, beta-reports-active, keychain-access-groups., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7fbba50a4b20; portalTeamID='6767CY3Y7D', usingTeamBasedSigning='NO', bundleIdentifier='uk.co.mycompany.app', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"application-identifier\" = \"6767CY3Y7D.uk.co.mycompany.app\";\n    \"beta-reports-active\" = 1;\n    \"keychain-access-groups\" =     (\n        \"6767CY3Y7D.uk.co.mycompany.app\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
        "<IDEDistributionItem: 0x7fbba5016e40 'uk.co.mycompany.app.notificationservice' '<DVTFilePath:0x7fbba4ecc170:'/Users/John/code/app/target/app_sandbox_1.17_0.xcarchive/Products/Applications/app.app/PlugIns/app_notification_service.appex'>'>" = "Error Domain=IDECodesignResolverErrorDomain Code=7 \"No matching provisioning profiles found\" UserInfo={NSLocalizedRecoverySuggestion=None of the valid provisioning profiles allowed the specified entitlements: application-identifier, beta-reports-active, keychain-access-groups., NSLocalizedDescription=No matching provisioning profiles found, IDECodesignResolverError_ResolutionInputsKey=<IDECodesignResolutionInputs: 0x7fbba500a690; portalTeamID='6767CY3Y7D', usingTeamBasedSigning='NO', bundleIdentifier='uk.co.mycompany.app.notificationservice', targetName='(null)', provisioningProfilePurpose='1', requiresProvisioningProfile='YES', provisioningProfilePlatform='iOS', certificateKind='1.2.840.113635.100.6.1.4', requiredEntitlements='{\n    \"application-identifier\" = \"6767CY3Y7D.uk.co.mycompany.app.notificationservice\";\n    \"beta-reports-active\" = 1;\n    \"keychain-access-groups\" =     (\n        \"6767CY3Y7D.uk.co.mycompany.app.notificationservice\"\n    );\n}', requiredCodesignableDevices='(null)', requiredFeatures='(null)'>\n}";
    };
}}
```
The app has the main target and a target for a notification service. I am creating an app id for the main target and notification target using produce before running gym, as well as fetching profiles with sigh. 

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | 10.12.5                                              |
| Ruby                        | 2.0.0                                                |
| Bundler?                    | true                                                 |
| Git                         | git version 2.11.0 (Apple Git-81)                    |
| Installation Source         | ~/.rvm/gems/ruby-2.0.0-p648@app/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                             |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.0.0-p648/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                            |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/          |
| Xcode Version               | 8.3.2                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
require_relative 'Configuration'

opt_out_usage

default_platform :ios

platform :ios do
  before_all do
    clear_derived_data
    cocoapods(repo_update: true)
    update_build_number
    update_version_number
  end

  desc 'Runs all the tests'
  lane :unit_UK do
   unit_test
  end

  lane :unit_SE do
    unit_test
  end

  desc 'Run integration tests'
  lane :integration do
    unit_test
  end

  desc 'Run screenshot automation'
  lane :screenshots do
    snapshot(scheme: configuration.snapshot_scheme,
             devices: configuration.snapshot_devices,
             languages: configuration.snapshot_languages,
             clear_previous_screenshots: false,
             skip_open_summary: true,
             erase_simulator: true,
             clean: true,
             stop_after_first_error: true,
             localize_simulator: true,
             configuration: configuration.app_configuration,
             xcargs: configuration.xc_args)
    frame
  end

  desc 'Submit a new Alpha Build to Hockey'
  lane :alpha do
    sign
    build
    hockey_upload
  end

  desc 'Submit a new Beta Build to Hockey'
  lane :beta do
    sign
    build
    hockey_upload
  end

  desc 'Submit a new Release Build to iTunes Connect'
  lane :release do
    sign
    build
    itunes_connect_upload
  end

  desc 'Submit a new Sandbox release build to hockey'
  lane :sandbox do
    create_sandbox_app_id
    sign
    build
    hockey_upload
  end

  private_lane :update_build_number do
    increment_build_number(build_number: configuration.build_number)
  end

  private_lane :update_version_number do
    increment_version_number(version_number: configuration.version_number)
  end

  private_lane :frame do
    frameit(white: true)
  end

  private_lane :unit_test do
    build_for_test
    scan(scheme: configuration.app_scheme,
         devices: configuration.scan_devices,
         clean: true,
         xcargs: configuration.gym_args,
         test_without_building: true,
         skip_build: true,
         derived_data_path: 'test_output',
         output_directory: 'test_output')
  end

  private_lane :sign do
    ENV['FASTLANE_PASSWORD'] = configuration.apple_password
    sigh(app_identifier: configuration.bundle_identifier,
         adhoc: configuration.sigh_adhoc?,
         username: configuration.apple_username,
         skip_certificate_verification: true,
         provisioning_name: configuration.bundle_identifier,
         ignore_profiles_with_different_name: true)
    sigh(app_identifier: configuration.notification_service_identifier,
         adhoc: configuration.sigh_adhoc?,
         username: configuration.apple_username,
         skip_certificate_verification: true,
         provisioning_name: configuration.notification_service_identifier,
         ignore_profiles_with_different_name: true)
  end

  private_lane :build do
    gym(scheme: configuration.app_scheme,
        configuration: configuration.app_configuration,
        export_method: configuration.gym_export_method,
        output_name: configuration.ipa_name,
        output_directory: configuration.app_output_directory,
        clean: true,
        include_symbols: true,
        include_bitcode: true,
        archive_path: configuration.archive_path,
        xcargs: configuration.xc_args)
  end

  private_lane :build_for_test do
    xcodebuild(
      scheme: configuration.app_scheme,
      derivedDataPath: 'test_output',
      xcargs: "-sdk iphonesimulator ONLY_ACTIVE_ARCH=NO build-for-testing"
    )
  end

  private_lane :hockey_upload do
    hockey(api_token: configuration.hockey_api_token,
           teams: configuration.hockey_teams,
           release_type: configuration.hockey_release_type,
           public_identifier: configuration.hockey_app_id,
           owner_id: configuration.hockey_owner_id,
           notify: '0')
  end

  private_lane :itunes_connect_upload do
    deliver(username: configuration.apple_username,
            app_identifier: configuration.bundle_identifier,
            app_version: configuration.version_number,
            skip_screenshots: true,
            force: true)
  end

  private_lane :create_sandbox_app_id do
    produce(username: configuration.apple_username,
            app_identifier: configuration.bundle_identifier,
            app_name: configuration.bundle_identifier,
            skip_itc: true,
            enable_services: {
              app_group: "on",
              associated_domains: "on",
              push_notification: "on"
            })
    produce(username: configuration.apple_username,
            app_identifier: configuration.notification_service_identifier,
            app_name: configuration.notification_service_identifier,
            skip_itc: true)
  end

end

def configuration
  @configuration ||= Configuration.new(lane_context[SharedValues::LANE_NAME],
                                       'build.yml')
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.39.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| rake                       | 11.2.2       |
| CFPropertyList             | 2.3.5        |
| i18n                       | 0.8.1        |
| minitest                   | 5.10.1       |
| thread_safe                | 0.3.6        |
| tzinfo                     | 1.2.3        |
| activesupport              | 4.2.8        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.1        |
| babosa                     | 1.0.2        |
| bundler                    | 1.13.6       |
| claide                     | 1.0.2        |
| clamp                      | 0.6.5        |
| fuzzy_match                | 2.0.4        |
| nap                        | 1.1.0        |
| cocoapods-core             | 1.1.1        |
| cocoapods-deintegrate      | 1.0.1        |
| cocoapods-downloader       | 1.1.2        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| netrc                      | 0.7.8        |
| cocoapods-trunk            | 1.1.1        |
| cocoapods-try              | 1.1.0        |
| colored                    | 1.2          |
| escape                     | 0.0.4        |
| fourflusher                | 2.0.1        |
| gh_inspector               | 1.0.3        |
| molinillo                  | 0.5.4        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.5.0        |
| cocoapods                  | 1.1.1        |
| redcarpet                  | 3.4.0        |
| cocoapods-acknowledgements | 1.1.2        |
| highline                   | 1.7.8        |
| commander-fastlane         | 4.4.4        |
| daemons                    | 1.2.4        |
| declarative                | 0.0.9        |
| declarative-option         | 0.1.0        |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| dotenv                     | 2.2.1        |
| eventmachine               | 1.2.3        |
| excon                      | 0.57.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.12.1       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.11.0.1     |
| fastimage                  | 2.1.0        |
| jwt                        | 1.5.6        |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.12.1       |
| logging                    | 2.2.2        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.7.3        |
| googleauth                 | 0.5.1        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.0.2        |
| google-api-client          | 0.12.0       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.1.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| slack-notifier             | 1.5.1        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.5.0        |
| word_wrap                  | 1.0.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| xcpretty-travis-formatter  | 0.0.4        |
| rack                       | 1.6.5        |
| rack-protection            | 1.5.3        |
| tilt                       | 2.0.7        |
| sinatra                    | 1.4.8        |
| thin                       | 1.7.0        |
| mimic2                     | 2.0.0        |
| mini_portile2              | 2.1.0        |
| pkg-config                 | 1.1.7        |
| nokogiri                   | 1.6.8        |
| xcres                      | 0.5.0        |
</details>

*generated on:* **2017-06-21**
</details>

**Comment by foulkesjohn** [comment]
Digging through the logs, i'm seeing:

```
2017-06-21 13:09:41 +0000 [MT] Rejecting: <DTDKProvisioningProfile 0x7ffddc773ad0: UUID: 50ef1c8e-45be-40c9-a039-1f17d8895cb9, name: uk.co.mycompany.app.notificationservice, team: 6767CY3Y7D (Company ), platform: iOS> (Offending Keys: (
    "beta-reports-active"
))
```
Not sure where I can configure `beta-reports-active`. The profile created by sigh is AdHoc so won't have this entitlement

**Comment by owurman** [comment]
I think I'm hitting this too (see reference in [bug 9401](https://github.com/fastlane/fastlane/issues/9401)

Did you figure out yet where beta-reports-active is coming from? I'm not finding it in a grep of the archive that's failing to codesign...

**Comment by foulkesjohn** [comment]
I had this issue because I was passing the wrong value to `export_method` for gym
