### ISSUE TITLE
Actual commands used by deliver to upload an .ipa file

### ISSUE THREAD

**Issue by sharkusmarkus** [fastlane/fastlane#9539]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Previously I had directly used spaceship to download a provisioning profile, as sigh didn't mirror the behaviour of cupertino that I had been using.

What I'm curious about now is what the "under the hood" commands are that the deliver app uses. Yes, I know I can just call deliver with some parameters, and I have done that, and it's great, but I'd love to know what calls it's actually making as it's all about knowledge and learning :)

I'm taking a guess spaceship is involved somewhere, but not sure that it would also handle the upload of the ipa.

Any information greatly appreciated.

**Comment by johnknapprs** [comment]
Best way to see how the engine works us to pop the hood : )

https://github.com/fastlane/fastlane/tree/master/deliver/lib/deliver

Check out the action itself and see what it's doing for each feature.  You can build the same functions into your own setup really easily.

**Comment by sharkusmarkus** [comment]
Ah, thanks :)
https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/runner.rb

That seems like it'll be a good place to start.
