### ISSUE TITLE
Tests hang after successful completion

### ISSUE THREAD

**Issue by lukas2** [fastlane/fastlane#9540]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We are running unit tests (using Jenkins) on a iPhone Simulator and afterwards, triggered by a successful run, on an iPad Simulator. (Reason: Different codepaths when running on iPad.)

iPhone is ok, but the iPad run almost always hangs forever after all tests have been executed successfully. Are we missing something? This has been the case with every fastlane update since April or so.

**Comment by lukas2** [comment]
Here you go (redacted it a bit, removed Actions and identifier.)

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_DE.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
#update_fastlane

require 'fileutils'
FileUtils.rm_rf File.join(__dir__, '../Pods')

cocoapods

default_platform :ios

platform :ios do

  desc "Runs unit tests on iphone"
  lane :test do
     scan(
      scheme: "Develop",
      devices: ["iPhone 7"]
    )
  end

  desc "Runs unit tests on ipad"
  lane :test_ipad do
     scan(
      scheme: "Develop",
      devices: ["iPad Pro (12.9 inch)"]
    )
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier “CEN.SOR.ED;)” # The bundle identifier of your app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.2  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170223 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.2        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>


*generated on:* **2017-06-21**
</details>

**Comment by taquitos** [comment]
Could you also include log output (redacted personal info of course)?
Troubleshooting-wise, have you tried enabling just one single simple test, like testing `true == true` and then testing to see if the sims hang after success? This could help narrow down where the issue is occurring. 

Maybe you can also try running `fastlane snapshot reset_simulators` to clear out any bad state.

**Comment by lukas2** [comment]
Yes, tried resetting. I think my problem might be this here: https://github.com/fastlane/fastlane/issues/5173 Killing the simulator leads to test being completed successfully.

**Comment by lukas2** [comment]
For now, I worked around this problem with a few shell commands (this is from our Jenkins "ipad-tests" job):

> sh -c "sleep 360 ; killall Simulator" &
> PID=$!
> fastlane test_ipad
> 
> if ps -p $PID > /dev/null
>   then
>     echo Killing ipad test monitor/killscript..
>   kill $PID
> fi

The idea is from @carsten-wenderdel posting here: https://github.com/fastlane/fastlane/issues/5173#issuecomment-230109254
