### ISSUE TITLE
Build iPA with local certificate file and provision profile file

### ISSUE THREAD

**Issue by weihuali0509** [fastlane/fastlane#9541]
From what I understand, *cert* and *sigh* will automatically download the latest cert and provision profile from Apple. 

If I have the certificate file and provision profile file, can I easily build and sign the IPA using fastlane? is there any setting in *cert* and *sign* options I can use the local cert and provision profile files?

I don't want to use the *match* option.

**Comment by mpirri** [comment]
If you have the profile on the machine already, you can just build using `gym` and it will use the local cert and provisioning profile.  You only need to use `cert`, `sigh`, or `match` if you want _fastlane_ to automatically manage the signing assets for you.

I hope this helps, please let us know if you have any other questions!  🚀
