### ISSUE TITLE
fastlane match appstore fails with Service Unavailable, succeeds with `match appstore`

### ISSUE THREAD

**Issue by paulz** [fastlane/fastlane#9543]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
`fastlane match appstore` fails with Service Unavailable:
```
[!] The request could not be completed because:
	<html><body><b>Http/1.1 Service Unavailable</b></body> </html>
```

but `match appstore` without fastlane completed successfully. Even it produces the warning:
```
[WARNING] You are calling match directly. Usage of the tool name without the `fastlane` prefix is deprecated in fastlane 2.0
Please update your scripts to use `fastlane match appstore` instead.
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
fastlane match appstore
[16:54:25]: Successfully loaded '/Users/developer/workspace/ios-app/fastlane/Matchfile' 📄

+----------------+-------------------------------------------------+
|           Detected Values from './fastlane/Matchfile'            |
+----------------+-------------------------------------------------+
| git_url        | git@github.com:omadahealth/ios-certificates.git |
| type           | development                                     |
| app_identifier | ["com.omadahealth.Prevent"]                     |
| username       | mobiledev@omadahealth.com                       |
+----------------+-------------------------------------------------+


+-----------------------+-------------------------------------------------+
|                        Summary for match 2.39.2                         |
+-----------------------+-------------------------------------------------+
| git_url               | git@github.com:omadahealth/ios-certificates.git |
| type                  | appstore                                        |
| app_identifier        | ["com.omadahealth.Prevent"]                     |
| username              | mobiledev@omadahealth.com                       |
| git_branch            | master                                          |
| keychain_name         | login.keychain                                  |
| readonly              | false                                           |
| team_id               | Y9UH8VMN28                                      |
| verbose               | false                                           |
| force                 | false                                           |
| skip_confirmation     | false                                           |
| shallow_clone         | false                                           |
| clone_branch_directly | false                                           |
| force_for_new_devices | false                                           |
| skip_docs             | false                                           |
| platform              | ios                                             |
+-----------------------+-------------------------------------------------+

[16:54:25]: Cloning remote git repo...
[16:54:25]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[16:54:26]: 🔓  Successfully decrypted certificates repo
[16:54:26]: Verifying that the certificate and profile are still valid on the Dev Portal...
Couldn't find team with ID 'Y9UH8VMN28'
[16:54:27]: Couldn't find a valid code signing identity in the git repo for distribution... creating one for you now

+---------------+------------------------------------------------------+
|                       Summary for cert 2.39.2                        |
+---------------+------------------------------------------------------+
| development   | false                                                |
| force         | true                                                 |
| username      | mobiledev@omadahealth.com                            |
| team_id       | Y9UH8VMN28                                           |
| keychain_path | /Users/developer/Library/Keychains/login.keychain-db |
| platform      | ios                                                  |
+---------------+------------------------------------------------------+

[16:54:27]: Starting login with user 'mobiledev@omadahealth.com'

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] The request could not be completed because:
	<html><body><b>Http/1.1 Service Unavailable</b></body> </html>
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.5                                         |
| Ruby                        | 2.3.0                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.11.0 (Apple Git-81)               |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0@prevent-ios/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 8.3.3                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "1.94.1"

default_platform :ios

platform :ios do
  desc 'Runs unit tests'
  lane :unit_tests do
    scan(workspace: 'OmadaPrevent.xcworkspace', scheme: 'OmadaPrevent', clean: false, devices: ["iPhone 7"])
  end
  
  desc 'Build an archive'
  lane :archive do
    gym
  end
  
  desc 'Create screenshot'
  lane :screenshot do
    snapshot
  end

  desc 'Increment the project version number'
  lane :bump_version_number do
    increment_version_number
    increment_build_number(build_number: 0)
  end

  desc 'Increment the project build number'
  lane :bump_build_number do
    increment_build_number
  end

  desc 'Commit version bump and tag'
  lane :commit_and_tag do
    tracker_id = ENV['TRACKER_ID']
    version = get_version_number
    build_number = get_build_number
    message = "[#{tracker_id}] Bump version to #{version}, build #{build_number}"
    tag = "builds/#{version}-#{build_number}"

    ensure_git_branch # make sure that master is checked out
    commit_version_bump(message: message)
    add_git_tag(tag: tag)
  end

  desc 'Submit an archive to iTunes Connect and upload dSYM archive to crashlytics'
  lane :submit_release do
    upload_symbols_to_crashlytics(api_token: ENV['FABRIC_API_KEY'])
    deliver
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    setup_jenkins
    cert
    sigh
    gym
    pilot
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.omadahealth.Prevent" # The bundle identifier of your app

team_id "Y9UH8VMN28"  # Developer Portal Team ID
apple_id "mobiledev@omadahealth.com"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.5        |
| i18n                      | 0.8.4        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| CFPropertyList            | 2.3.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| cocoapods                 | 1.2.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| pivotal_git_scripts       | 1.4.0        |
| clamp                     | 0.6.5        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| slather                   | 2.4.2        |
</details>

*generated on:* **2017-06-21**
</details>

**Comment by paulz** [comment]
Yes, that's where we got the idea of using match

**Comment by paulz** [comment]
now after `match appstore` succeeded
the `fastlane match appstore` completes with success:
```
fastlane match appstore
[17:24:51]: Successfully loaded '/Users/developer/workspace/ios-app/fastlane/Matchfile' 📄

+---------+-------------------------------------------------+
|        Detected Values from './fastlane/Matchfile'        |
+---------+-------------------------------------------------+
| git_url | git@github.com:omadahealth/ios-certificates.git |
| type    | development                                     |
+---------+-------------------------------------------------+


+-----------------------+-------------------------------------------------+
|                        Summary for match 2.39.2                         |
+-----------------------+-------------------------------------------------+
| git_url               | git@github.com:omadahealth/ios-certificates.git |
| type                  | appstore                                        |
| git_branch            | master                                          |
| app_identifier        | com.omadahealth.Prevent                         |
| username              | mobiledev@omadahealth.com                       |
| keychain_name         | login.keychain                                  |
| readonly              | false                                           |
| team_id               | Y9UH8VMN28                                      |
| verbose               | false                                           |
| force                 | false                                           |
| skip_confirmation     | false                                           |
| shallow_clone         | false                                           |
| clone_branch_directly | false                                           |
| force_for_new_devices | false                                           |
| skip_docs             | false                                           |
| platform              | ios                                             |
+-----------------------+-------------------------------------------------+

[17:24:51]: Cloning remote git repo...
[17:24:51]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[17:24:51]: 🔓  Successfully decrypted certificates repo
[17:24:51]: Verifying that the certificate and profile are still valid on the Dev Portal...
Couldn't find team with ID 'Y9UH8VMN28'
[17:24:52]: Installing certificate...

+-------------------+------------------------------------------------------+
|                          Installed Certificate                           |
+-------------------+------------------------------------------------------+
| User ID           | ZGNT8JCDR8                                           |
| Common Name       | iPhone Distribution: Omada Health, inc. (ZGNT8JCDR8) |
| Organisation Unit | ZGNT8JCDR8                                           |
| Organisation      | Omada Health, inc.                                   |
| Country           | US                                                   |
| Start Datetime    | Jun 21 23:49:06 2017 GMT                             |
| End Datetime      | Jun 21 23:49:06 2018 GMT                             |
+-------------------+------------------------------------------------------+

[17:24:53]: Installing provisioning profile...

+---------------------+----------------------------------------------+----------------------------------------------+
|                                          Installed Provisioning Profile                                           |
+---------------------+----------------------------------------------+----------------------------------------------+
| Parameter           | Environment Variable                         | Value                                        |
+---------------------+----------------------------------------------+----------------------------------------------+
| App Identifier      |                                              | com.omadahealth.Prevent                      |
| Type                |                                              | appstore                                     |
| Platform            |                                              | ios                                          |
| Profile UUID        | sigh_com.omadahealth.Prevent_appstore        | 5c9419fb-37cf-47a3-b75c-3fb590707e56         |
| Profile Name        | sigh_com.omadahealth.Prevent_appstore_profi  | match AppStore com.omadahealth.Prevent       |
|                     | le-name                                      |                                              |
| Profile Path        | sigh_com.omadahealth.Prevent_appstore_profi  | /Users/developer/Library/MobileDevice/Provi  |
|                     | le-path                                      | sioning                                      |
|                     |                                              | Profiles/5c9419fb-37cf-47a3-b75c-3fb590707e  |
|                     |                                              | 56.mobileprovision                           |
| Development Team ID | sigh_com.omadahealth.Prevent_appstore_team-  | ZGNT8JCDR8                                   |
|                     | id                                           |                                              |
+---------------------+----------------------------------------------+----------------------------------------------+

[17:24:53]: All required keys, certificates and provisioning profiles are installed 🙌

```

**Comment by mpirri** [comment]
Can you check to see if `match --version` is the same as `fastlane --version` ? It is possible that your gems are out of sync and that is why you are seeing inconsistent behavior.

Also possible is that Apple's server was down at the exact moment you ran `fastlane match`, but that seems coincidental based on the behavior you are seeing.

Either way, I'm glad to hear it is working better for you now!  🚀

**Comment by paulz** [comment]
Current versions are:
`fastlane 2.45.0`
`match 1.0.0`

Same behavior: `fastlane match appstore` works successfully
