### ISSUE TITLE
git_add action propose new functionality;

### ISSUE THREAD

**Issue by Antondomashnev** [fastlane/fastlane#9547]
🔑

### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Recently I needed to add untracked objects to the `HEAD` by pathspec. For example `git add Frameworks/*` and I checked existing [git_add](https://docs.fastlane.tools/actions/#git_add). Unfortunately, it supports only adding objects by the specific path that I can understand because it has validation if that file exists. For my own needs I wrote a simple decorated fastlane action that extends the `git_add` with new parameters:  
1. `:all` - if you want to use `git add .`
2. `:pathspec` - if you want to use for example `git add *.txt`

So the question is, do you think it will be a nice addition for the `git_add` action - I can make a PR then. If no it'll stay as a private action for my own needs 😄

**Comment by mpirri** [comment]
This functionality sounds :100: - I think we'd love to take a look at a PR for it.  Thanks so much!  🚀
