### ISSUE TITLE
Automatic provisioning support

### ISSUE THREAD

**Issue by nissaba** [fastlane/fastlane#9548]
This is probably not the first time it is asked, but I want to add to the need to have Gym be able to use the new automatic provisioning system from xcode 8. 

It works good and this is the way I would like to use fastlane, we have some 12 apps and its a pain to use fastlane if we need to use manual provisioning. So for now we just use direct xcodebuild commands in our CI system. Would love to start using fastlane, but this makes it imposible. 

So Please, pretty please with a cherry on top ;) add support for automatic provisioning.

**Comment by chappejw** [comment]
I second the need for the Automatic provisioning to be functioning with Fastlane as a critical must have. I have about 350 apps and deploying that many apps manually is a no go. I have tried about 500 variations of fastlane to no avail. Tried the tools seperately, tried PROVISIONING_PROFILE_SPECIFIER, tried iPhone Developer signing identity, tried iPhone Distribution code signing entity. Tried every single combination of Xcode signing configurations. Absolutely nothing works and there are not any decent error messages even in the Xcodebuild log to work with... If anyone has a solid well written document explaining how to configure this broken mess I would be eternally grateful.!

**Comment by taquitos** [comment]
Have you tried [_match_](https://github.com/fastlane/fastlane/tree/master/match) yet? It kinda sounds like it would be what you're looking for. It can manage your certs/profiles for you. If you've found that it doesn't work for you, I'd be curious to understand why.
