### ISSUE TITLE
Can't Use the Gem `Badge`

### ISSUE THREAD

**Issue by cansurmeli** [fastlane/fastlane#9549]
For some time now, none of my lanes can badge my app icons using the gem `Badge`.

For instance, for the following lane:

```
 desc "Ready a new build for local alpha testing."
desc "This will also make sure the profile is up to date"
lane :localAlpha do
  ensure_git_status_clean
  # copy the original app icons so no badge overlapping occurs
  sh "cp appIcons/* ../Voicity/Other/Assets.xcassets/AppIcon.appiconset/"
  incrementBuild
  version = "#{get_version_number}(#{get_build_number})"
  badge(shield: "Version-#{version}-blue", alpha: true)
  sh "git add *"
  sh "git commit -a -m `Fastlane updated app icons`"
end
```

I get the following errors:

```
/Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:92:in `run': [!] ERROR: Failed to build gem native extension. (Gem::Ext::BuildError)

    current directory: /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3/ext
/Users/can/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170622-20392-1wg45h2.rb extconf.rb
checking for curl-config... yes
checking for curlinfo_appconnect_time... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/can/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--with-curl-dir
	--without-curl-dir
	--with-curl-include
	--without-curl-include=${curl-dir}/include
	--with-curl-lib
	--without-curl-lib=${curl-dir}/lib
/Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:524:in `with_werror'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:52:in `block in have_constant'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:321:in `open'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
	from extconf.rb:44:in `have_constant'
	from extconf.rb:62:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/curb-0.9.3 for inspection.
Results logged to /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/gem_make.out

	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/tempfile.rb:319:in `open'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/ext_conf_builder.rb:31:in `build'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:164:in `block (2 levels) in build_extension'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:163:in `chdir'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:163:in `block in build_extension'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:162:in `build_extension'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:201:in `block in build_extensions'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:198:in `each'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/ext/builder.rb:198:in `build_extensions'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:748:in `build_extensions'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:297:in `install'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/resolver/specification.rb:97:in `install'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:166:in `block in install'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `each'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:156:in `install'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:250:in `install_gem'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/helper/gem_helper.rb:7:in `verify_gem!'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/actions/badge.rb:5:in `run'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:78:in `block (2 levels) in parsing_binding'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.39.2/bin/fastlane:20:in `<top (required)>'
	from /Users/can/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/can/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

`fastlane env` output:

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.1                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.39.2  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-24**
</details>

**fastlane**: 2.39.2
**ruby**: 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

I've looked at various issues on this but couldn't find a solution. Any ideas?

**Comment by taquitos** [comment]
It looks like it is having an issue finding your dev tools (which I assume you have installed, if not try `xcode-select --install`)

Maybe post your `/Users/can/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/curb-0.9.3/mkmf.log` file that it mentions. It could offer more insight. You might need to adjust a symlink or something. 
I just tried reproducing with rbenv and I couldn't elicit this error.

**Comment by cansurmeli** [comment]
@taquitos Actually, I just solved it by reinstalling fastlane: `sudo gem uninstall fastlane` && `sudo rm -rf ~/.fastlane` && `sudo gem install fastlane`.

I think it was as if you mentioned that a symlink was pointing at the wrong direction.

Thanks a bunch! 🙂
