### ISSUE TITLE
[resign] erroneous bundle id set when resigning if the old bundle id is a substring of the new one

### ISSUE THREAD

**Issue by mikerunnals** [fastlane/fastlane#9550]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When resigning, if the old bundle id is a substring of the new bundle id like:
`com.myapp -> com.myapp.qa`

The resulting bundle id is set to 
`com.myapp.qa.qa`

Not the expected 
`com.myapp.qa`

This happens when using resign options:
```
  resign(
    ipa: newipa_path,
    signing_identity: identity,
    provisioning_profile: profiles,
    use_app_entitlements: true
  )
```

### Code Details

Bug is at sigh/lib/assets/resign.sh:728
`sed -i .bak "s/com.myapp/com.myapp.qa/g" "$PATCHED_ENTITLEMENTS"`

At this point in the code the PATCHED_ENTITLEMENTS file already contains the new `com.myapp.qa` bundle id, so the sed replacement results in the double `qa.qa` being added.

Stupid fix:
`sed -i .bak "s/$OLD_BUNDLE_ID\</$NEW_BUNDLE_ID\</g" "$PATCHED_ENTITLEMENTS"`

Better fix:
Use PlistBuddy to update the bundle id?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.4.5                                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios

fastlane_require 'yaml'
fastlane_require 'erb'

$system_provisioning_path = File.expand_path("~/Library/MobileDevice/Provisioning Profiles")

before_all do |lane, options|

  $root_dir = File.expand_path(File.join(File.dirname(__FILE__), ".."))

  $builds = YAML.load(ERB.new(File.read("#{$root_dir}/fastlane/builds.yml")).result)
 
  install_profiles()
end

desc "Build the base configuration ipa."
lane :build do
  build_dependencies_if_necessary(platform: "iOS")
  unless File.file?(baseipa_path())
    gym(
      clean: true,
      scheme: $scheme,
      configuration: $base_config,
      output_directory: File.dirname(baseipa_path()),
      archive_path: File.dirname(baseipa_path()),
      buildlog_path: "#{$root_dir}/artifacts/logs/gym",
      export_options: {
        method: "app-store"
      }
    )
  else
    UI.important "Not Rebuilding IPA as it Already Exists at #{baseipa_path()}"
  end
end

private_lane :build_dependencies_if_necessary do |options|
  unless File.directory?("#{$root_dir}/Carthage/Build/iOS")
    UI.success "Rebuilding Carthage Dependencies"
    output = carthage(command: "build", platform: options[:platform])
    match = output.match(/\*\*\* xcodebuild output can be found in (?<logfile>[\.\/\w-]+)/)
    if match[:logfile]
      sh(%|mkdir -p "#{$root_dir}/artifacts/logs/carthage"|)
      sh(%|cp "#{match[:logfile]}" #{$root_dir}/artifacts/logs/carthage/|)
    end
  else
    UI.important "Not Rebuilding Carthage Dependencies"
  end
end

lane :install_profiles do
  sh(%|mkdir -p "#{$system_provisioning_path}"|)

  profiles_glob = File.join("#{$root_dir}/profiles/**", "*.mobileprovision")
  profiles = Dir.glob(profiles_glob)
  profiles.each do |profile|
    sh(%|rsync -av "#{profile}" "#{$system_provisioning_path}"|)
  end
end

lane :uninstall_profiles do
  sh(%|mkdir -p "#{$system_provisioning_path}"|)

  profiles_glob = File.join("#{$root_dir}/profiles/**", "*.mobileprovision")
  profiles = Dir.glob(profiles_glob)
  profiles.each do |profile|
    $rmfilename = "#{$system_provisioning_path}/#{File.basename(profile)}"
    sh(%|rm "#{$rmfilename}"|) rescue "Error: failed to delete #{$rmfilename}"
  end
end

desc "Remove build certificates. Always do this, even if the build fails."
private_lane :uninstall_signing do |options|
  # Set the login.keychain back to default
  sh(%{
    security default-keychain -s login.keychain || :
    security list-keychains -d user -s ~/Library/Keychains/login.keychain
  })

  delete_keychain(name: $keychain_name) rescue nil
end

lane :test do |options|
  output_directory = "./test_output"
  build_dependencies_if_necessary(platform: "iOS")
  scan(
    scheme: $scheme,
    devices: ["iPhone 7"],
    output_directory: output_directory,
    derived_data_path: "build/TestDD-iPhone",
  )
end

lane :test_ipad do |options|
  output_directory = "./test_output"
  build_dependencies_if_necessary(platform: "iOS")
  scan(
    scheme: $scheme,
    devices: ["iPad Air 2"],
    output_directory: output_directory,
    derived_data_path: "build/TestDD-iPad",
  )
end

desc "Create the AppStore Artifacts"
lane :appstore_ipa do |options|
  resign_with_config($builds["iOS"][:appstore][:options])
end

desc "Create the Internal Artifacts"
lane :internal_ipa do |options|
  resign_with_config($builds["iOS"][:internal][:options])
end

desc "Create the QA Artifacts"
lane :qa_ipa do |options|
  resign_with_config($builds["iOS"][:qa][:options])
end

desc "Upload DSYMs to Crittercism"
lane :upload_dsyms do |options|
  dsym_dir = "#{$root_dir}/artifacts/builds/base.xcarchive/dSYMs"
  ENV["APP_ID"] = $crittercism_app_id
  ENV["API_KEY"] = $crittercism_api_key
  ENV["REQUIRE_UPLOAD_SUCCESS"] = "1"
  ENV["TARGET_TEMP_DIR"] = "test_output"
  ENV["DWARF_DSYM_FOLDER_PATH"] = dsym_dir
  Dir.foreach("#{dsym_dir}/") do |item|
  next if item == '.' or item == '..'
    # do work on real items
    ENV["DWARF_DSYM_FILE_NAME"] = item
    sh(%|#{$root_dir}/Pods/CrittercismSDK/dsym_upload.sh|)
  end
end

private_lane :resign_with_config do |options|

  # TODO: investigate plugin to update Info.plists:
  #  https://github.com/richardszalay/fastlane-plugin-act

  newipa_dir = "#{$root_dir}/artifacts/builds/#{options[:name]}"
  newipa_path = "#{newipa_dir}/#{$scheme}.ipa"
  
  sh(%|mkdir -p "#{newipa_dir}"|)
  sh(%|cp "#{baseipa_path()}" "#{newipa_path}"|)

  sh(%|zip --delete "#{newipa_path}" \*Root.plist|) if options[:distribution] == "app-store"

  # Update/inject AppConfig-*.plist
  appconfig_path =  "#{$root_dir}//AppConfig-#{options[:name]}.plist"
  appconfig_dir =  "Payload/#{$scheme}.app"
  target_appconfig_path =  "#{appconfig_dir}/AppConfig.plist"
  if File.file?(appconfig_path)
    sh(%|mkdir -p "#{appconfig_dir}"|)
    sh(%|cp "#{appconfig_path}" "#{target_appconfig_path}"|)
    sh(%|zip --move "#{newipa_path}" "#{target_appconfig_path}"|)
    sh(%|rmdir -p "#{appconfig_dir}"|)
  else 
    raise "File appconfig_path DNE"
  end

  identity = options[:identity]
  profiles = profiles(options)

  puts "identity #{identity}"
  puts "profiles #{profiles}"

  resign(
    ipa: newipa_path,
    signing_identity: identity,
    provisioning_profile: profiles,
    use_app_entitlements: true
  )

end

desc "Build all iOS configurations"
desc "####Options"
desc " * **`build_number`**: increment_build_number"
desc "Example cmdline: fastlane ios_all build_number:4321"
lane :ios_all do |options|

  assert_build_number(options[:build_number])

  test()
  test_ipad()


  increment_build_number(
    build_number: options[:build_number],
    xcodeproj: $project
  )

  build()

  appstore_ipa()

  upload_dsyms()
  # TODO: update Internal to NOT use wildcard profile (resign does not support wilcards)
  #internal_ipa()

  qa_ipa()

end

###
## Helper Functions
#

def baseipa_path; "#{$root_dir}/artifacts/builds/base/#{$scheme}.ipa"; end

# map old_bundle_ids to modile provisioning files
def profiles(options) 
 Hash[options[:targets].map{|k,values| [values[:old_bundle_id], "#{$system_provisioning_path}/#{values[:profile_filename]}"] } ]
end

def assert_build_number(build_number)
  begin 
    $market_ver = sh("cd .. && agvtool mvers -terse1 | tr -d '\n'")
    # TeamCity Service Message to change the build label
    UI.success "##teamcity[buildNumber '" + $market_ver + " (" + build_number + ")']"
  rescue StandardError=>e
    raise "Error: build_number option required. \nExample cmdline: fastlane [lane] build_number:4321"
  end 
end

def xcodeproj(); "#{$root_dir}/#{$project}.xcodeproj"; end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.39.1  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.13.6       |
| json                      | 2.1.0        |
| excon                     | 0.57.0       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>

*generated on:* **2017-06-22**
</details>

**Comment by mgrebenets** [comment]
@mikerunnals 

What do you pass for `provisioning_profile: profiles`?

We usually sign the other way around `com.myapp.qa -> com.myapp` - that is we are dropping suffix, not adding it. So I guess that's why we never ran into this issue.

I should be able to look into bash code, it would help if you could give me an exact example of `profiles` argument.
