### ISSUE TITLE
match gym pilot cause ERROR ITMS-90161: "Invalid Provisioning Profile."

### ISSUE THREAD

**Issue by paulz** [fastlane/fastlane#9554]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Using default options recommended by https://docs.fastlane.tools/codesigning/xcode-project/#xcode-8-and-up we are failing to upload with `ERROR ITMS-90161`
```
  lane :beta do
    setup_jenkins
    match
    gym
    pilot
  end
```

```
Return status of iTunes Transporter was 1: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
```

We found workaround by specifying adhoc type for match:
```
  lane :beta do
    setup_jenkins
    match(type: 'adhoc', readonly: true)
    gym
    pilot
  end
```

Is this a documentation issue? Could this be better explained? We were expecting default options to **just work** without need to specifying `adhoc` type.

##### Complete output when running fastlane, including the stack trace and command used

```
[10:42:11]: ▸ Touching Prevent.app.dSYM
[10:42:12]: ▸ Archive Succeeded
[10:42:12]: Generated plist file with the following values:
[10:42:12]: ▸ -----------------------------------------
[10:42:12]: ▸ {
[10:42:12]: ▸   "provisioningProfiles": {
[10:42:12]: ▸     "com.omadahealth.Prevent": "match Development com.omadahealth.Prevent"
[10:42:12]: ▸   },
[10:42:12]: ▸   "method": "development"
[10:42:12]: ▸ }
[10:42:12]: ▸ -----------------------------------------
[10:42:12]: $ /usr/bin/xcrun /Users/jenkins/.rvm/gems/ruby-2.3.0@prevent-ios/gems/fastlane-2.40.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/01/n9__bzpn697b_tv2k5fctcnm0000gp/T/gym_config20170622-21853-1i8oiso.plist' -archivePath /Users/jenkins/Library/Developer/Xcode/Archives/2017-06-22/Prevent\ 2017-06-22\ 10.39.45.xcarchive -exportPath '/var/folders/01/n9__bzpn697b_tv2k5fctcnm0000gp/T/gym_output20170622-21853-135klns' 
[10:42:22]: Compressing 13 dSYM(s)
[10:42:22]: $ cd '/Users/jenkins/Library/Developer/Xcode/Archives/2017-06-22/Prevent 2017-06-22 10.39.45.xcarchive/dSYMs' && zip -r '/Users/jenkins/workspace/iOS TestFlight/Prevent.app.dSYM.zip' *.dSYM
```

```
[10:42:24]: Successfully exported and compressed dSYM file
[10:42:24]: Successfully exported and signed the ipa file:
[10:42:24]: /Users/jenkins/workspace/iOS TestFlight/Prevent.ipa
[10:42:24]: -------------------
[10:42:24]: --- Step: pilot ---
[10:42:24]: -------------------
[10:42:24]: Login to iTunes Connect (mobiledev@omadahealth.com)
[10:42:26]: Login successful
[10:42:27]: Ready to upload new build to TestFlight (App: 805711008)...
[10:42:27]: Going to upload updated app to iTunes Connect
[10:42:27]: This might take a few minutes. Please don't interrupt the script.
[10:42:50]: [Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[10:42:50]: Transporter transfer failed.
[10:42:50]: 
[10:42:50]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[10:42:51]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
Return status of iTunes Transporter was 1: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.
+------------------------------------+------------------------------------------------------+
|                                       Lane Context                                        |
+------------------------------------+------------------------------------------------------+
| DEFAULT_PLATFORM                   | ios                                                  |
| PLATFORM_NAME                      | ios                                                  |
| LANE_NAME                          | ios beta                                             |
| SIGH_PROFILE_TYPE                  | development                                          |
| MATCH_PROVISIONING_PROFILE_MAPPING | {"com.omadahealth.Prevent"=>"match Development       |
|                                    | com.omadahealth.Prevent"}                            |
| IPA_OUTPUT_PATH                    | /Users/jenkins/workspace/iOS TestFlight/Prevent.ipa  |
| DSYM_OUTPUT_PATH                   | /Users/jenkins/workspace/iOS                         |
|                                    | TestFlight/Prevent.app.dSYM.zip                      |
| XCODEBUILD_ARCHIVE                 | /Users/jenkins/Library/Developer/Xcode/Archives/201  |
|                                    | 7-06-22/Prevent 2017-06-22 10.39.45.xcarchive        |
+------------------------------------+------------------------------------------------------+
[10:42:51]: Error uploading ipa file, for more information see above

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 3    | setup_jenkins                | 0           |
| 4    | match                        | 3           |
| 5    | gym                          | 163         |
| 💥   | pilot                        | 26          |
+------+------------------------------+-------------+
```
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.5                                         |
| Ruby                        | 2.3.0                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.11.0 (Apple Git-81)               |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0@prevent-ios/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                        |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                    |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                     |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 8.3.3                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version

fastlane_version "1.94.1"

default_platform :ios

platform :ios do
  desc 'Runs unit tests'
  lane :unit_tests do
    scan(workspace: 'OmadaPrevent.xcworkspace', scheme: 'OmadaPrevent', clean: false, devices: ["iPhone 7"])
  end
  
  desc 'Build an archive'
  lane :archive do
    gym
  end
  
  desc 'Create screenshot'
  lane :screenshot do
    snapshot
  end

  desc 'Increment the project version number'
  lane :bump_version_number do
    increment_version_number
    increment_build_number(build_number: 0)
  end

  desc 'Increment the project build number'
  lane :bump_build_number do
    increment_build_number
  end

  desc 'Commit version bump and tag'
  lane :commit_and_tag do
    tracker_id = ENV['TRACKER_ID']
    version = get_version_number
    build_number = get_build_number
    message = "[#{tracker_id}] Bump version to #{version}, build #{build_number}"
    tag = "builds/#{version}-#{build_number}"

    ensure_git_branch # make sure that master is checked out
    commit_version_bump(message: message)
    add_git_tag(tag: tag)
  end

  desc 'Submit an archive to iTunes Connect and upload dSYM archive to crashlytics'
  lane :submit_release do
    upload_symbols_to_crashlytics(api_token: ENV['FABRIC_API_KEY'])
    deliver
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    setup_jenkins
    match
    gym
    pilot
  end

  desc "Installed shared developer certificate and provisioning profile once on a new machine"
  lane :certificates do
    match(type: 'development', readonly: true)
    match(type: 'adhoc', readonly: true)
    match(type: 'appstore', readonly: true)
  end

end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.omadahealth.Prevent" # The bundle identifier of your app

team_id "Y9UH8VMN28"  # Developer Portal Team ID
apple_id "mobiledev@omadahealth.com"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.40.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.5        |
| i18n                      | 0.8.4        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| CFPropertyList            | 2.3.5        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| cocoapods                 | 1.2.1        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| pivotal_git_scripts       | 1.4.0        |
| clamp                     | 0.6.5        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| slather                   | 2.4.2        |
</details>

*generated on:* **2017-06-22**
</details>

**Comment by KrauseFx** [comment]
Could you share a screenshot for your Xcode project's target settings, including the code signing section in the build settings, and the Overview tab?

**Comment by paulz** [comment]
Code signing:
<img width="1167" alt="screen shot 2017-06-27 at 1 08 24 pm" src="https://user-images.githubusercontent.com/59230/27607725-bcabf376-5b39-11e7-80cb-5bf426376248.png">

Overview:
<img width="1135" alt="screen shot 2017-06-27 at 1 07 01 pm" src="https://user-images.githubusercontent.com/59230/27607690-9802f1dc-5b39-11e7-9292-29274a572282.png">

**Comment by paulz** [comment]
we just tried setting Release provisioning profile to "match Adhoc" and it fails the same way, looks like match sets up development environment regardless of build settings:

```
[13:28:28]: Installing provisioning profile...

+---------------------+-------------------------------------------------------+-------------------------------------------------------------+
|                                                      Installed Provisioning Profile                                                       |
+---------------------+-------------------------------------------------------+-------------------------------------------------------------+
| Parameter           | Environment Variable                                  | Value                                                       |
+---------------------+-------------------------------------------------------+-------------------------------------------------------------+
| App Identifier      |                                                       | com.omadahealth.Prevent                                     |
| Type                |                                                       | development                                                 |
| Platform            |                                                       | ios                                                         |
| Profile UUID        | sigh_com.omadahealth.Prevent_development              | 79ed25a9-c4d3-465a-9943-97aa40a10e1d                        |
| Profile Name        | sigh_com.omadahealth.Prevent_development_profile-name | match Development com.omadahealth.Prevent                   |
| Profile Path        | sigh_com.omadahealth.Prevent_development_profile-path | /Users/developer/Library/MobileDevice/Provisioning          |
|                     |                                                       | Profiles/79ed25a9-c4d3-465a-9943-97aa40a10e1d.mobileprovis  |
|                     |                                                       | ion                                                         |
| Development Team ID | sigh_com.omadahealth.Prevent_development_team-id      | ZGNT8JCDR8                                                  |
+---------------------+-------------------------------------------------------+-------------------------------------------------------------+
...

[13:30:04]: ▸ Archive Succeeded
[13:30:04]: Generated plist file with the following values:
[13:30:04]: ▸ -----------------------------------------
[13:30:04]: ▸ {
[13:30:04]: ▸   "provisioningProfiles": {
[13:30:04]: ▸     "com.omadahealth.Prevent": "match Development com.omadahealth.Prevent"
[13:30:04]: ▸   },
[13:30:04]: ▸   "method": "development"
[13:30:04]: ▸ }
[13:30:04]: ▸ -----------------------------------------

...
[13:30:15]: Successfully exported and compressed dSYM file
[13:30:15]: Successfully exported and signed the ipa file:
[13:30:15]: /Users/developer/workspace/ios-app/Prevent.ipa
[13:30:15]: -------------------
[13:30:15]: --- Step: pilot ---
[13:30:15]: -------------------
[13:30:15]: Login to iTunes Connect (mobiledev@omadahealth.com)
[13:30:16]: Login successful
[13:30:17]: Ready to upload new build to TestFlight (App: 805711008)...
[13:30:17]: Going to upload updated app to iTunes Connect
[13:30:17]: This might take a few minutes. Please don't interrupt the script.
[13:30:39]: [Transporter Error Output]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[13:30:39]: Transporter transfer failed.
[13:30:39]: 
[13:30:39]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
[13:30:39]: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
Return status of iTunes Transporter was 1: ERROR ITMS-90161: "Invalid Provisioning Profile. The provisioning profile included in the bundle com.omadahealth.Prevent [Payload/Prevent.app] is invalid. [Missing code-signing certificate]. A Distribution Provisioning profile should be used when submitting apps to the App Store. For more information, visit the iOS Developer Portal."
The call to the iTMSTransporter completed with a non-zero exit status: 1. This indicates a failure.

```

**Comment by mgrebenets** [comment]
@paulz 

What happens is that `match` by default is using "development" for `type` (`MATCH_TYPE`), unless you set `MATCH_TYPE` environment variable somewhere or you set the type in `Matchfile`.

Then the `MATCH_TYPE` is passed on via lane context to `gym` as an export method. `gym` is building using Development certs and profiles, but then exports using `adhoc` export method.

I think that's why things start to work when you explicitly specify "adhoc" method.

Just to double check, do you set `adhoc` in `Matchfile` or via `MATCH_TYPE`?
If yes, then there's a bug indeed.
If no, then the default export method is `development` and everything works as expected.

**Comment by paulz** [comment]
our `Matchfile` contains development:
```
type "development" # The default type, can be: appstore, adhoc, enterprise or development
```

With updated fastlane, we now fail to upload to TestFlight using adhoc and succeed with appstore:
```
desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    setup_jenkins
    match(type: 'appstore', readonly: true)
    gym
    pilot
  end
```

**Comment by KrauseFx** [comment]
```
[13:30:04]: Generated plist file with the following values:
[13:30:04]: ▸ -----------------------------------------
[13:30:04]: ▸ {
[13:30:04]: ▸   "provisioningProfiles": {
[13:30:04]: ▸     "com.omadahealth.Prevent": "match Development com.omadahealth.Prevent"
[13:30:04]: ▸   },
[13:30:04]: ▸   "method": "development"
[13:30:04]: ▸ }
```

Looks like it's trying to build for development, which won't work, make sure to choose the right export method in `gym` and select the correct provisioning profile 👍

**Comment by paulz** [comment]
As I said earlier specifying match type to appstore works for us on Jenkins:
```
match(type: 'appstore', readonly: true)
```
Produces this log output
```
[15:11:56]: ▸ > Archive Succeeded
[15:11:56]: Generated plist file with the following values:
[15:11:56]: ▸ -----------------------------------------
[15:11:56]: ▸ {
[15:11:56]: ▸   "provisioningProfiles": {
[15:11:56]: ▸     "com.omadahealth.Prevent": "match AppStore com.omadahealth.Prevent"
[15:11:56]: ▸   },
[15:11:56]: ▸   "method": "app-store"
[15:11:56]: ▸ }
[15:11:56]: ▸ -----------------------------------------
```
It would be nice if `setup_jenkins` would take care of setting `appstore` not `development`
