### ISSUE TITLE
Code signing is required for product type 'Application' in SDK 'iOS 10.0

### ISSUE THREAD

**Issue by bopeola21** [fastlane/fastlane#9556]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When I run Fastlane locally on my machine with the intent to run tests and upload build to Crashlytics everything works like it is suppose to. The issue I am having is when I try to run the same thing on Travis-CI I get an "❌  Code signing is required for product type 'Application' in SDK 'iOS 10.0'" error.

I have read through every issue on here pertaining to this issue nothing has worked yet. I've also tried this command "enable_automatic_code_signing(path: "iOSConnect.xcodeproj")" it did not work.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
default_platform :ios
platform :ios do

# Set Environment Variables
  before_all do
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120"
    ENV["FASTLANE_USER"] = "travis.ci@nextraq.com"
    ENV["KEYCHAIN_NAME"] = "travis.keychain"
    ENV["CRASHLYTICS_SUBMIT_PATH"] = "./Pods/Crashlytics/iOS/Crashlytics.framework"
    ENV["DEV_SCHEME"] = "Dev-Connect"
    ENV["DEV_APP_ID"] = "com.nextraq.Dev-iOSConnect"
    ENV["QA_SCHEME"] = "QA-Connect"
    ENV["QA_APP_ID"] = "com.nextraq.QA-iOSConnect"
    ENV["PROD_SCHEME"] = "Prod-Connect"
    ENV["PROD_APP_ID"] = "com.nextraq.Prod-iOSConnect"
    ENV["TEST_SCHEME"] = "ConnectTests"
    ENV["AUTO_BUILD_COMMIT_MSG"] = "Auto-Increment Build# - [ci skip]"
    ENV["DESTINATION_SPECIFIER"] = "platform=iOS Simulator,name=iPhone 6s,OS=10.0"
    ENV["CRASHLYTICS_EMAIL_GROUP"] =  "devtesters"
  end

# Branches appropriate components to be executed based on the Branch the code is built.
  desc "Run Test locally"
  lane :gitflow do
      run_test_fabric ENV["DEV_APP_ID"], ENV["DEV_SCHEME"], ENV["DESTINATION_SPECIFIER"], "false"
  end

  # Runs Test and Uploads to Crashlytics
  def run_test_fabric (app_id, build_scheme, dest_specifier, notification_flag)
    puts "dest specifier is: #{dest_specifier}"

    sigh(app_identifier: app_id,  username: ENV["FASTLANE_USER"],  adhoc: true)
    ipaPathFabric = gym(
      scheme: build_scheme,
      export_method: "ad-hoc"
#      use_legacy_build_api: true
    )
    crashlytics(
      crashlytics_path: ENV["CRASHLYTICS_SUBMIT_PATH"],
      ipa_path: ipaPathFabric,
      api_token: ENV["CRASHLYTICS_API_KEY"],
      build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
      groups: ENV["CRASHLYTICS_EMAIL_GROUP"],
      debug: "YES",
      notes: ENV["TRAVIS_COMMIT_MSG"],
      notifications: notification_flag
    )
  end


  after_all do |lane|
  end

  error do |lane, exception|
  end

end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.nextraq.Base-iOSConnect" # The bundle identifier of your app
apple_id "travis.ci@nextraq.com" # Your Apple email address

team_name "DISCRETE WIRELESS, INC"
team_id "867P39LLTJ"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.39.2  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.57.0       |
| openssl                   | 2.0.3        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-06-21**
</details>

### travis.yml File

language: objective-c
osx_image: xcode8
install: true   #Turn off install step

branches:
  only:
  - master
  - development
  - "/^release-.*$/"
  - travisTesting

env:
  global:
'#' FASTLANE_PASSWORD
  - secure: {FASTLANE_PASSWORD}
'#' CRASHLYTICS_BUILD_SECRET
  - secure: {CRASHLYTICS_BUILD_SECRET}
'#' CRASHLYTICS_API_KEY
  - secure: {CRASHLYTICS_API_KEY}
'#' CERT_PASSWORD_NEW
  - secure: {CERT_PASSWORD_NEW}

before_script:
- security create-keychain -p travis ios-build.keychain
- security default-keychain -s ios-build.keychain
- security unlock-keychain -p travis ios-build.keychain
- security set-keychain-settings -t 3600 -l ~/Library/Keychains/ios-build.keychain
- security import ./scripts/certs/apple.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./scripts/certs/dist.cer -k ~/Library/Keychains/ios-build.keychain -T /usr/bin/codesign
- security import ./scripts/certs/dist.p12 -k ~/Library/Keychains/ios-build.keychain -P $KEY_PASSWORD -T /usr/bin/codesign
- security list-keychains
- security find-identity -p codesigning  ~/Library/Keychains/ios-build.keychain

- export TZ=America/New_York
- export TRAVIS_COMMIT_MSG=$(git log --format=%B -n 1)
- export SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6s (10.0) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
- rvm install 2.3.1
- ruby --version
- gem install cocoapods --pre --no-document
- pod --version
- gem install fastlane
- fastlane --version
- gym --version
- echo -e "machine github.com\n  login nextraq-ci\n  password $GITHUB_PASSWORD" >> ~/.netrc
- pod repo add NXTPods https://github.com/NexTraq/NXTPods.git
- pod repo
- pod repo update --silent
- pod update

script:
- echo $SIMULATOR_IDs
- open -a "simulator" --args -CurrentDeviceUDID $SIMULATOR_ID
- fastlane gitflow

<img width="954" alt="screen shot 2017-06-21 at 5 02 24 pm" src="https://user-images.githubusercontent.com/10440984/27450658-61564a9a-575a-11e7-9418-c17a8e10d07f.png">

<img width="951" alt="screen shot 2017-06-21 at 5 02 38 pm" src="https://user-images.githubusercontent.com/10440984/27450666-6902cd86-575a-11e7-8f8d-f0f3d2ce0df4.png">

**Comment by bopeola21** [comment]
Yes I have, none of the solutions worked for me.

**Comment by mgrebenets** [comment]
@bopeola21 Is travis CI provisioned with development certificate and provisioning profiles?

Also, what is the exact code signing error from xcode build log?
Usually it contains more hints.

When you run it locally and run tests, you do that all on device right?
But on travis you would only be able to run tests on simulator, so code signing shouldn't even be required.

**Comment by bopeola21** [comment]
I was able to successfully import the development cert but not the provisioning profiles. When I try to run the following commands in travis CI: 

mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
cp "./scripts/profile/iOSConnect_Dev_Adhoc.mobileprovision" ~/Library/MobileDevice/Provisioning\ Profiles/

I get an error saying "No such file or directory". That file is in fact in that directory, I quintuple checked!

When I run the tests locally I'm running them on the simulator. I do need the ability to code sign because I plan on using Fastlane to submit to the App Store.

**Comment by chappejw** [comment]
What might be happening is that the '.' at the beginning of your source path "./scripts/profile/..." may not be getting expanded. Try printing that path string before using it. If you remove the quotes I believe the dot operator will expand to the current working directory that you want.

**Comment by bopeola21** [comment]
You are right removing the quotes does allow it to access the current working directory, thank you. I was able to access the file but sadly this did not fix the problem ☹️. I still get the "❌ Code signing is required for product type 'Application' in SDK 'iOS 10.0'" error.
