### ISSUE TITLE
Precheck complains about Google Analytics in privacy policy

### ISSUE THREAD

**Issue by Johennes** [fastlane/fastlane#9568]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The precheck barks when the privacy policy URL points to a site that contains text like:

```We may also use Google Analytics to collect demographic and interest data about you...```

```
[15:56:38]: Checking app for precheck rule violations
[15:58:02]: ✅  Passed: No negative  sentiment
[15:58:02]: 😵  Failed: No placeholder text-> using placeholder text (e.g.:"lorem ipsum", "text here", etc...)
[15:58:02]: 😵  Failed: No mentioning  competitors-> mentioning other platforms, like Android or Blackberry
[15:58:02]: ✅  Passed: No future functionality promises
[15:58:02]: ✅  Passed: No words indicating test content
[15:58:02]: ✅  Passed: No curse words
[15:58:02]: ✅  Passed: Incorrect, or missing copyright date
[15:58:41]: ✅  Passed: No broken urls
```

This is perfectly valid content and should not be flagged.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| plist                     | 3.3.0        |
| bundler                   | 1.15.0       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.2.1        |
</details>

*generated on:* **2017-06-23**
</details>

**Comment by taquitos** [comment]
@Johennes could you include the summary table here? The Apple competitors rule is a text-based rule (doesn't follow URLs), so in this case, there is some text in the app metadata it's not liking. The summary table should point at the field where that is so I can better figure out what is going on.

**Comment by Johennes** [comment]
Apologies, that got clipped somehow. There's multiple lines like these in the output

```
|  tv privacy policy: (fr-CA)   | found: google  |
|  tv privacy policy: (id)      | found: google  |
|  tv privacy policy: (it)      | found: google  |
|  tv privacy policy: (fi)      | found: google  |
|  tv privacy policy: (pt-PT)   | found: google  |
|  tv privacy policy: (en-AU)   | found: google  |
|  tv privacy policy: (ko)      | found: google  |
|  tv privacy policy: (en-GB)   | found: google  |
|  tv privacy policy: (ru)      | found: google  |
|  tv privacy policy: (en-US)   | found: google  |
```

I was assuming that it would check the contents of the site linked under the privacy URL since no other metadata files seemed to match.

**Comment by Johennes** [comment]
Here are my metadata folder contents for `fr-CA`:

```
> ls .../metadata/fr-CA/
description.txt   marketing_url.txt privacy_url.txt   support_url.txt
keywords.txt      name.txt          release_notes.txt
```

I greped through those files and none contains "google".

**Comment by taquitos** [comment]
Ohh, so that privacy policy field that is getting mentioned there is this field in iTunes Connect, can you double check the metadata in iTunes Connect? 
<img width="1240" alt="screen shot 2017-06-23 at 4 22 17 pm" src="https://user-images.githubusercontent.com/1304821/27503366-53058358-5830-11e7-8347-17c68b879498.png">

**Comment by funnel20** [comment]
I've got the same warning while using "Google" in the 'review notes' to explain the use of certain Google services to App Review team.

**Comment by funnel20** [comment]
Great, thank you for the excellent follow-up.

**Comment by taquitos** [comment]
Reopening because it shouldn't be closed since the PR might not address @Johennes's original issue

**Comment by Johennes** [comment]
Sorry for the delay. I completely glanced over the `tv` in the output, apologies. As it happens our AppleTV privacy policy in iTC contains the same text that we link under our privacy policy URL:

```
We may also use Google Analytics to ...
```

I think this would be nice to not mark in the pre-check.

**Comment by taquitos** [comment]
@Johennes we just released an update that includes a fix for that 👍  thank you for reporting

**Comment by Johennes** [comment]
Sweet. Thanks a lot for the super fast action! :)
