### ISSUE TITLE
Missing App Image on iTunesConnect

### ISSUE THREAD

**Issue by fsproru** [fastlane/fastlane#957]
Hello,

I'm pushing an app to iTunesConnect which works great. Thanks for th great work that you did. The image thought shows up as a default image, not the image from the app bundle itself. (see the image below)

![screen shot 2015-12-04 at 3 23 24 pm](https://cloud.githubusercontent.com/assets/1017606/11603913/ff8b9202-9a9a-11e5-9d0b-ff39bf24e2ba.png)

Is there a way to push an iTunesConnect image with the app using fastlane ?

Thanks,
Alex

**Comment by KrauseFx** [comment]
Make sure to also define your app icon in `deliver`:

Deliverfile:
```ruby
app_icon "path/to/1024pxIcon.png
```

**Comment by fsproru** [comment]
This is exactly it, thanks @KrauseFx
