### ISSUE TITLE
Deliver - Display upload protocol, and its settings (if applicable), that are being used, in the summary

### ISSUE THREAD

**Issue by sharkusmarkus** [fastlane/fastlane#9572]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Feature Request
I'm wondering if it would be at all possible for Deliver to display the upload protocol, and it's settings, that is being used in the summary page.

For example, if you have specified ;

`DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"`

then the summary would show this.

**Comment by taquitos** [comment]
Interesting, what are you planning on using this output for?

**Comment by sharkusmarkus** [comment]
Originally my CI script was just calling altool directly to upload the .ipa to iTuneSconnect. I'm started to expand the script further to use parts of fastlane (it's using Spaceship directly to download a provisioning profile based on the profile name - something sigh doesn't do), and part of that was to use deliver.

While looking at the documentation for deliver I saw mention of the upload protocols, and started looking at what was available. 

I added code to my CI script to allow you to specifically select one of the supported protocols, or just let it use the default.

I thought it might be a good thing if deliver showed what protocol was being used. I believe the reason for the different protocols being allowed is to assist if firewall rules prevent one from being used. It may be that a user won't know what protocol is being used, so printing out the one being used may be useful.

**Comment by KrauseFx** [comment]
Yeah, that's a great idea :+1: With `summary page`, do you mean the HTML based preview, or the summary table shown at the top of the build output? 

From my understanding, I think the protocol is already shown as part of the build output. 

Is that something you would want to prepare a PR for? :)

**Comment by sharkusmarkus** [comment]
This summary (think that it might be the build output one) is what I'm talking about. I've added in my example of what I'm talking about too
> +-----------------------------+---------------------------------------------------+
|                             deliver 2.45.0 Summary                              |
+-----------------------------+---------------------------------------------------+
| username                    | me@company.com                                    |
| app_identifier              | com.mycompany.com                                 |
| skip_screenshots            | true                                              |
| skip_metadata               | true                                              |
| skip_binary_upload          | true                                              |
| ipa                         | /my.ipa                                           |
| screenshots_path            | ./.fastlane/screenshots                           |
| metadata_path               | ./.fastlane/metadata                              |
| app_version                 | 1.0                                               |
| edit_live                   | false                                             |
| platform                    | ios                                               |
| skip_app_version_update     | false                                             |
| force                       | false                                             |
| submit_for_review           | false                                             |
| automatic_release           | false                                             |
| overwrite_screenshots       | false                                             |
| run_precheck_before_submit  | true                                              |
| precheck_default_rule_level | warn                                              |
| upload_protocol             | default (Signiant)                                |
+-----------------------------+---------------------------------------------------+

As for a PR, much as I'd love to, I think that's a little beyond me!

**Comment by KrauseFx** [comment]
Oh nice, that makes sense 👍  The table is currently auto generate based on the passed options. We have some really nice docs on [how to get started contributing](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md), let me know if any questions come up :)
