### ISSUE TITLE
Precheck - Add support for Mac apps

### ISSUE THREAD

**Issue by JakeSc** [fastlane/fastlane#9580]
### New Issue Checklist

- [√] Updated fastlane to the latest version
- [√] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running `fastlane precheck` for my Mac app (which exists on iTC), I see:
```
/fastlane-2.41.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Could not find app with App Identifier 'com.jake.myApp' (FastlaneCore::Interface::FastlaneError)
    from /fastlane-2.41.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
    from /fastlane-2.41.0/precheck/lib/precheck/runner.rb:161:in `ensure_app_exists!'
```

To work around this, I was able to amend `precheck/lib/precheck/runner.rb` to pass `mac: true` into Spaceship:
```
    def app
      Spaceship::Tunes::Application.find(Precheck.config[:app_identifier])
    end
```
becomes
```
    def app
      Spaceship::Tunes::Application.find(Precheck.config[:app_identifier], mac: true)
    end
```

### Environment

N/A

**Comment by JakeSc** [comment]
If you have a recommended approach for conditionally setting this `mac: bool` parameter or getting it from the CLI / config files, I'm happy to create a PR.

**Comment by taquitos** [comment]
Yeah, that would be cool! An approach you could use would be similar to how _cert_ does it. Take a look at `cert/lib/cert/options.rb:64` to see how we load parameters. Once you make a similar change in `precheck/lib/precheck/options.rb` you'd be able to update `precheck/lib/precheck/runner.rb:151` to something like `Spaceship::Tunes::Application.find(Precheck.config[:app_identifier], mac: Precheck.config[:platform] == "macos")`

I'm not sure if that's the only place you'd need to plumb it through, but that should point you in the general right direction. 

Also if you haven't contributed before, check out https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md
