### ISSUE TITLE
Snapshot results does not show up

### ISSUE THREAD

**Issue by wimbledon** [fastlane/fastlane#9583]
### Issue Description
At the end of the snapshot, the results icon does not show up. It used to show up in previous version of fastlane. Maybe it on 2.10. It has not worked since. Sorry for not reporting the issue earlier...

![image](https://user-images.githubusercontent.com/3291853/27548131-dd808640-5a4c-11e7-9459-fda8154e134e.png)
![image](https://user-images.githubusercontent.com/3291853/27548302-7578d36c-5a4d-11e7-8893-fa8f53ffd84e.png)

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
fastlane_version "1.98.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
     
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :app_snapshot do
    snapshot(skip_open_summary: false, 
             clean: true, 
             number_of_retries: 3,
             erase_simulator: true,
             stop_after_first_error: false)
  end
  
  after_all do |lane|
    build = Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    commit_version_bump(message: "Release Build Version:#{build}",
                        xcodeproj: "./Musify.xcodeproj")

    tag_name = "#{lane}/#{build}"
    add_git_tag(tag: tag_name)

    notification(title: "Fastlane finished Submission", message: "Fastlane finished '#{lane}' successfully")

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-26**
</details>

**Comment by taquitos** [comment]
Hey @wimbledon, could you attach your fastfile/snapfile and your complete output from the tool as well? That should help us diagnose this stuff.

**Comment by wimbledon** [comment]
@taquitos Thank you for your response. I didn't want to attach the snapfile and some output as it contains sensitive information. But happy to answer any question to get to the root cause.

**Comment by KrauseFx** [comment]
Sorry without the log we can't help, if you can please send the log to somethingrandom@krausefx.com, otherwise you can tell us how we can reproduce the issue 👍

**Comment by wimbledon** [comment]
@KrauseFx Thanks! When you say the log, do you mean `fastlane env --capture_output`? I did paste all the relevant info in this issue under Environment.

**Comment by KrauseFx** [comment]
Mh, I can't seem to find it there. Mind posting it here again?

**Comment by wimbledon** [comment]
Key | Value
-- | --
OS | 10.12.4
Ruby | 2.2.4
Bundler? | false
Git | git version 2.11.0 (Apple Git-81)
Installation Source | ~/.fastlane/bin/bundle/bin/fastlane
Host | Mac OS X 10.12.4 (16E195)
Ruby Lib Dir | ~/.fastlane/bin/bundle/lib
OpenSSL Version | OpenSSL 1.0.2g 1 Mar 2016
Is contained | false
Is homebrew | true
Is installed via Fabric.app | false
Xcode Path | /Applications/Xcode.app/Contents/Developer/
Xcode Version | 8.3.2

**Comment by KrauseFx** [comment]
Hehe, thanks I know about this. What I'm asking for is the output of _fastlane_ when you run _fastlane_ in your terminal, talking about the build output, snapshot output, etc.

**Comment by KrauseFx** [comment]
Thanks :)

**Comment by wimbledon** [comment]
Hi @KrauseFx,
Just following up on this issue. Apparently, it happens to me every time. I've send the log to somethingrandom@krausefx.com.

**Comment by KrauseFx** [comment]
If you change it to be one language only, does it work?

**Comment by wimbledon** [comment]
@KrauseFx 
It does work with one language!
![image](https://user-images.githubusercontent.com/3291853/28991109-d4e94476-7938-11e7-82fb-f89873b1dd57.png)

**Comment by KrauseFx** [comment]
Ah, so it's just a rendering issue? Is that a big problem for you?

**Comment by wimbledon** [comment]
@KrauseFx It would nice to get it fixed. Otherwise, there is no easy way to tell which snapshot test passed or failed.
