### ISSUE TITLE
fastlane_require fails with jenkins_api_client

### ISSUE THREAD

**Issue by farkasseb** [fastlane/fastlane#9584]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to use **jenkins_api_client** in a (remotely imported) `Fastfile` with `fastlane_require`. The install fails with the following error. I am not sure if this is a `fastlane` issue or an error in my environment settings. Any help is highly appreciated!

### Captured Output
<details><summary>gem_make.out</summary>

```
current directory: /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.8.0/ext/nokogiri
/Users/fastlane_user/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170626-60368-aqdshy.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/fastlane_user/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
	--help
	--clean
/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
	from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:522:in `with_werror'
	from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:619:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:407:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.8.0/mkmf.log

extconf failed, exit code 1
```
</details>

<details><summary>mkmf.log</summary>

```
"/usr/bin/clang -o conftest -I/Users/fastlane_user/.fastlane/bin/bundle/include/ruby-2.2.0/x86_64-darwin15 -I/Users/fastlane_user/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/backward -I/Users/fastlane_user/.fastlane/bin/bundle/include/ruby-2.2.0 -I. -I/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -mmacosx-version-min=10.10 -isysroot /Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -pipe  conftest.c  -L. -L/Users/fastlane_user/.fastlane/bin/bundle/lib -L. -L/Users/crashlytics/buildAgent/work/2484be8b71880c21/bundle-2.28.3/fastlane_lib/dependencies/lib -fstack-protector     -lruby-static -framework CoreFoundation  -lpthread -ldl -lobjc  "
clang: warning: no such sysroot directory: '/Applications/Xcode-7.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk' [-Wmissing-sysroot]
In file included from conftest.c:1:
In file included from /Users/fastlane_user/.fastlane/bin/bundle/include/ruby-2.2.0/ruby.h:33:
In file included from /Users/fastlane_user/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/ruby.h:29:
/Users/fastlane_user/.fastlane/bin/bundle/include/ruby-2.2.0/ruby/defines.h:26:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```
</details>

Command Used: `build`
<details><summary>Output/Log</summary>

```

DEBUG [2017-06-26 18:20:09.75]: Checking if there are any plugins that should be loaded...
INFO [2017-06-26 18:20:10.11]: gem 'cocoapods-core' is already installed
INFO [2017-06-26 18:20:10.37]: gem 'erb' is already installed
INFO [2017-06-26 18:20:10.46]: gem 'fileutils' is already installed
INFO [2017-06-26 18:20:10.76]: gem 'httparty' is already installed
WARN [2017-06-26 18:20:11.15]: Installing Ruby gem 'jenkins_api_client'...

Looking for related GitHub issues on fastlane/fastlane...
Search query: ERROR: Failed to build gem native extension.

    current directory: /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.8.0/ext/nokogiri
/Users/fastlane_user/.fastlane/bin/bundle/bin/ruby -r ./siteconf20170626-61492-1e1j6b5.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
  --with-opt-dir
  --without-opt-dir
  --with-opt-include
  --without-opt-include=${opt-dir}/include
  --with-opt-lib
  --without-opt-lib=${opt-dir}/lib
  --with-make-prog
  --without-make-prog
  --srcdir=.
  --curdir
  --ruby=/Users/fastlane_user/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)
  --help
  --clean
/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
  from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `block in try_compile'
  from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:522:in `with_werror'
  from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in `try_compile'
  from extconf.rb:138:in `nokogiri_try_compile'
  from extconf.rb:162:in `block in add_cflags'
  from /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:619:in `with_cflags'
  from extconf.rb:161:in `add_cflags'
  from extconf.rb:407:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.8.0/gem_make.out

URL: https://api.github.com/search/issues?q=ERROR:%20Failed%20to%20build%20gem%20native%20extension.%0A%0A%20%20%20%20current%20directory:%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.8.0/ext/nokogiri%0A/Users/fastlane_user/.fastlane/bin/bundle/bin/ruby%20-r%20./siteconf20170626-61492-1e1j6b5.rb%20extconf.rb%0Achecking%20if%20the%20C%20compiler%20accepts%20...%20***%20extconf.rb%20failed%20***%0ACould%20not%20create%20Makefile%20due%20to%20some%20reason,%20probably%20lack%20of%20necessary%0Alibraries%20and/or%20headers.%20%20Check%20the%20mkmf.log%20file%20for%20more%20details.%20%20You%20may%0Aneed%20configuration%20options.%0A%0AProvided%20configuration%20options:%0A%09--with-opt-dir%0A%09--without-opt-dir%0A%09--with-opt-include%0A%09--without-opt-include=$%7Bopt-dir%7D/include%0A%09--with-opt-lib%0A%09--without-opt-lib=$%7Bopt-dir%7D/lib%0A%09--with-make-prog%0A%09--without-make-prog%0A%09--srcdir=.%0A%09--curdir%0A%09--ruby=/Users/fastlane_user/.fastlane/bin/bundle/bin/$(RUBY_BASE_NAME)%0A%09--help%0A%09--clean%0A/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:456:in%20%60try_do':%20The%20compiler%20failed%20to%20generate%20an%20executable%20file.%20(RuntimeError)%0AYou%20have%20to%20install%20development%20tools%20first.%0A%09from%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in%20%60block%20in%20try_compile'%0A%09from%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:522:in%20%60with_werror'%0A%09from%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:571:in%20%60try_compile'%0A%09from%20extconf.rb:138:in%20%60nokogiri_try_compile'%0A%09from%20extconf.rb:162:in%20%60block%20in%20add_cflags'%0A%09from%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/2.2.0/mkmf.rb:619:in%20%60with_cflags'%0A%09from%20extconf.rb:161:in%20%60add_cflags'%0A%09from%20extconf.rb:407:in%20%60%3Cmain%3E'%0A%0ATo%20see%20why%20this%20extension%20failed%20to%20compile,%20please%20check%20the%20mkmf.log%20which%20can%20be%20found%20here:%0A%0A%20%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.8.0/mkmf.log%0A%0Aextconf%20failed,%20exit%20code%201%0A%0AGem%20files%20will%20remain%20installed%20in%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/nokogiri-1.8.0%20for%20inspection.%0AResults%20logged%20to%20/Users/fastlane_user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-15/2.2.0-static/nokogiri-1.8.0/gem_make.out%0A+repo:fastlane/fastlane
ERROR [2017-06-26 18:20:31.40]: Error finding relevant GitHub issues: undefined method `map' for nil:NilClass


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.2                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G12b)                   |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
import '../../fastlane/Fastfile'
# import_from_git(url: 'https://some_server/fastlane.git', path: 'Fastfile')
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| i18n                      | 0.8.1        |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| minitest                  | 5.4.3        |
| activesupport             | 4.2.8        |
| nap                       | 1.1.0        |
| fuzzy_match               | 2.0.4        |
| cocoapods-core            | 1.2.1        |
| httparty                  | 0.15.5       |
| psych                     | 2.0.8        |
</details>

*generated on:* **2017-06-26**
</details>

**Comment by PetrosIchor** [comment]
Don't install fastlane with brew.  Use gem install fastlane instead.

**Comment by farkasseb** [comment]
Thank you, this solves my problem! Could you please give me a short explanation too?
