### ISSUE TITLE
Idea: Appstore review checklist

### ISSUE THREAD

**Issue by goktugyil** [fastlane/fastlane#959]
A lot of apps get rejected by stupid reasons, maybe if we can make a checklist as a community about the reasons we got rejected about and how we solved that it would be a good idea to show devs while deploying their apps.

Some of the stuff can be automated, but some of the stuff should be shown to the person.

**Comment by pieisgood** [comment]
I think apple does a good job describing these things already.

https://developer.apple.com/app-store/review/rejections/

**Comment by jcampbell05** [comment]
Also would be better as a wiki in any case

**Comment by goktugyil** [comment]
@pieisgood I've gotten a lot of rejections and none of the causes were from that list.

**Comment by goktugyil** [comment]
@jcampbell05 Do you have any examples on your thought?

**Comment by jcampbell05** [comment]
Not that I can find.

I was thinking you could just open a basic website with a search and search for reasons of rejection. As some reasons aren't listed even on apple's thing (Caculator widgets were once an example of that)

**Comment by ohwutup** [comment]
Great suggestion for keeping a community checklist @goktugyil! I am going to close this issue as it has been quite some time since there was any discussion here. Please feel free to continue discussion here though! :speak_no_evil:
