### ISSUE TITLE
Homebrew cask missing SHA-1

### ISSUE THREAD

**Issue by frankrausch** [fastlane/fastlane#9591]
```
~ brew cask install fastlane
Warning: Cask 'fastlane' does not have a sha256 checksum defined and was not installed.
This means you have the "--require-sha" option set, perhaps in your HOMEBREW_CASK_OPTS.
```
If you have the `--require-sha` option* set in your `HOMEBREW_CASK_OPTS`, the installation via Homebrew fails.

*) recommended by https://devhub.io/repos/drduh-OS-X-Security-and-Privacy-Guide

**Comment by frankrausch** [comment]
No way to include the output of `fastlane env` before installing fastlane—right, bot? ;)

**Comment by taquitos** [comment]
Interesting, I didn't realize this was an option, but makes total sense.  I need to read up on how casks are made, we'll take a look at this.

**Comment by taquitos** [comment]
Right now we don't update our cask for every release. Including the sha for each release would mean we'd need to add that into the release workflow. I don't think it's a ton of work, but I do wonder how the caskroom maintainers would deal with our frequent releases. They'd be getting so many pull requests from us I'd worry that our cask would start to lag behind our releases.
