### ISSUE TITLE
Pilot Distribute can't set Email

### ISSUE THREAD

**Issue by JeffreyGreenII** [fastlane/fastlane#9594]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Pilot's Distribute doesn't seem to have the ability to set the email external testing. Sometimes the error comes back as "email is required" but mostly comes back as "The email must be in the format: contact@example.com"

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Users-iMac:~ user$ fastlane pilot distribute --username user@website.com --app_identifier com.bundle.identifier --app_platform ios --changelog "Nothing new" --beta_app_description "Nothing special" --beta_app_feedback_email user@website.com --distribute_external true --first_name user --last_name user -e "user@website.com" --groups "External Testers"
[13:54:49]: Login to iTunes Connect (user@website.com)
[13:54:53]: Login successful
[13:55:01]: Successfully set the beta_app_feedback_email and/or beta_app_description
[13:55:03]: Successfully set the changelog for build
[13:55:03]: Distributing new build to testers: 6.0.1 - 6.0.1.3
[13:55:06]: fastlane failed to write the crash report to /Users/user/.fastlane/latest_crash.json.
[13:55:06]: Sending crash report...
[13:55:06]: The stacktrace is sanitized so no personal information is sent.
[13:55:06]: To see what we are sending, look here: /Users/user/.fastlane/latest_crash.json
[13:55:06]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[13:55:06]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/spaceship/lib/spaceship/test_flight/client.rb:200:in `handle_response': [!] {"code"=>"The email must be in the format: contact@example.com.", "description"=>"Failed to submit build for review."} (Spaceship::Client::UnexpectedResponse)
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/spaceship/lib/spaceship/test_flight/client.rb:68:in `post_for_testflight_review'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/spaceship/lib/spaceship/test_flight/build.rb:179:in `submit_for_testflight_review!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/pilot/lib/pilot/build_manager.rb:139:in `distribute_build'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/pilot/lib/pilot/build_manager.rb:76:in `distribute'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/pilot/lib/pilot/commands_generator.rb:72:in `block (2 levels) in run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/user/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.41.0/bin/fastlane:20:in `<top (required)>'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/user/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-06-27**
</details>

**Comment by jaisonv** [comment]
I was stuck with this problem and I realized there was testing information missing in the Testflight section in the ITC website. After filling all the needed informations I got rid of this error.

**Comment by mpirri** [comment]
@JeffreyGreenII We have seen similar behavior to what @jaisonv mentions above - if you have incorrect information elsewhere in your app's TestFlight section, you will get a seemingly-unrelated error like the one above. In this case, the incorrectly-formatted email address is not the one you specified in the `fastlane pilot` command, but rather a different email address elsewhere in iTunesConnect information for your project.

Thanks for the report - I hope this is helpful!  🚀
