### ISSUE TITLE
Supply doesn't seem to be a JSON file

### ISSUE THREAD

**Issue by OliveiraMaicon** [fastlane/fastlane#9595]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

Successfully loaded Appfile at path '/Users/maoliveira/workspace/wifi.app.native/fastlane/Appfile'
- json_key_file: 'google_play.json'
- package_name: 'br.com.uol.wifi'
-------
DEBUG [2017-06-27 16:17:09.38]: Checking if there are any plugins that should be loaded...
INFO [2017-06-27 16:17:09.52]: -------------------------------------------------
INFO [2017-06-27 16:17:09.52]: --- Step: Verifying required fastlane version ---
INFO [2017-06-27 16:17:09.52]: -------------------------------------------------
INFO [2017-06-27 16:17:09.52]: Your fastlane version 2.41.0 matches the minimum requirement of 2.37.0  ✅
INFO [2017-06-27 16:17:09.52]: ------------------------------
INFO [2017-06-27 16:17:09.52]: --- Step: default_platform ---
INFO [2017-06-27 16:17:09.52]: ------------------------------
INFO [2017-06-27 16:17:09.52]: Driving the lane 'android beta' 🚀
INFO [2017-06-27 16:17:09.52]: --------------------
INFO [2017-06-27 16:17:09.52]: --- Step: gradle ---
INFO [2017-06-27 16:17:09.52]: --------------------
INFO [2017-06-27 16:17:09.52]: $ /Users/maoliveira/workspace/wifi.app.native/gradlew assembleRelease -p .
INFO [2017-06-27 16:17:12.18]: ▸ Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
INFO [2017-06-27 16:17:12.19]: ▸ Configuration 'androidTestCompile' in project ':app' is deprecated. Use 'androidTestImplementation' instead.
INFO [2017-06-27 16:17:12.19]: ▸ Configuration 'testCompile' in project ':app' is deprecated. Use 'testImplementation' instead.
INFO [2017-06-27 16:17:12.61]: ▸ :app:preBuild UP-TO-DATE
INFO [2017-06-27 16:17:14.59]: ▸ :app:preReleaseBuild
INFO [2017-06-27 16:17:14.74]: ▸ :app:compileReleaseAidl
INFO [2017-06-27 16:17:14.82]: ▸ :app:compileReleaseRenderscript
INFO [2017-06-27 16:17:14.84]: ▸ :app:checkReleaseManifest
INFO [2017-06-27 16:17:14.89]: ▸ :app:generateReleaseBuildConfig
INFO [2017-06-27 16:17:14.91]: ▸ :app:generateReleaseResValues
INFO [2017-06-27 16:17:14.91]: ▸ :app:generateReleaseResources
INFO [2017-06-27 16:17:29.84]: ▸ :app:mergeReleaseResources
INFO [2017-06-27 16:17:29.90]: ▸ :app:createReleaseCompatibleScreenManifests
INFO [2017-06-27 16:17:30.33]: ▸ :app:processReleaseManifest
INFO [2017-06-27 16:17:30.36]: ▸ :app:splitsDiscoveryTaskRelease
INFO [2017-06-27 16:17:47.51]: ▸ :app:processReleaseResources
INFO [2017-06-27 16:17:47.85]: ▸ :app:compileReleaseKotlin
INFO [2017-06-27 16:17:47.85]: ▸ Using kotlin incremental compilation
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/ui/activities/MapsFragment.kt: (154, 71): Unnecessary safe call on a non-null receiver of type Array<Point>?
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/ui/activities/MapsFragment.kt: (173, 13): Variable 'userLocation' is never used
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/ui/activities/MapsFragment.kt: (176, 15): Unnecessary safe call on a non-null receiver of type Array<Point>
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/ui/activities/MapsFragment.kt: (195, 36): 'getDrawable(Int): Drawable!' is deprecated. Deprecated in Java
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/ui/activities/MapsFragment.kt: (196, 83): No cast needed
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/utils/PermissionUtils.kt: (34, 52): This cast can never succeed
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/utils/PermissionUtils.kt: (122, 95): Parameter 'dialog' is never used, could be renamed to _
INFO [2017-06-27 16:17:51.87]: ▸ w: /Users/maoliveira/workspace/wifi.app.native/app/src/main/java/br/com/uol/wifi/utils/PermissionUtils.kt: (122, 103): Parameter 'which' is never used, could be renamed to _
INFO [2017-06-27 16:17:51.98]: ▸ :app:generateReleaseSources
INFO [2017-06-27 16:17:52.09]: ▸ :app:javaPreCompileRelease
INFO [2017-06-27 16:17:52.94]: ▸ :app:compileReleaseJavaWithJavac
INFO [2017-06-27 16:17:53.04]: ▸ :app:mergeReleaseShaders
INFO [2017-06-27 16:17:53.04]: ▸ :app:compileReleaseShaders
INFO [2017-06-27 16:17:53.04]: ▸ :app:generateReleaseAssets
INFO [2017-06-27 16:17:53.07]: ▸ :app:mergeReleaseAssets
INFO [2017-06-27 16:17:55.61]: ▸ :app:transformClassesWithJarMergingForRelease
INFO [2017-06-27 16:18:02.17]: ▸ :app:transformClassesWithMultidexlistForRelease
INFO [2017-06-27 16:18:30.45]: ▸ :app:transformClassesWithDexForRelease
INFO [2017-06-27 16:18:30.46]: ▸ :app:compileReleaseNdk NO-SOURCE
INFO [2017-06-27 16:18:30.47]: ▸ :app:mergeReleaseJniLibFolders
INFO [2017-06-27 16:18:33.87]: ▸ :app:transformNativeLibsWithMergeJniLibsForRelease
INFO [2017-06-27 16:18:33.93]: ▸ :app:processReleaseJavaRes NO-SOURCE
INFO [2017-06-27 16:18:34.91]: ▸ :app:transformResourcesWithMergeJavaResForRelease
INFO [2017-06-27 16:18:34.91]: ▸ :app:validateSigningRelease
INFO [2017-06-27 16:18:38.36]: ▸ :app:packageRelease
INFO [2017-06-27 16:18:38.36]: ▸ :app:buildInfoGeneratorRelease
INFO [2017-06-27 16:18:38.36]: ▸ :app:compileReleaseSources
INFO [2017-06-27 16:18:41.73]: ▸ :app:lintVitalRelease
INFO [2017-06-27 16:18:41.74]: ▸ :app:assembleRelease
INFO [2017-06-27 16:18:41.74]: ▸ BUILD SUCCESSFUL in 1m 31s
INFO [2017-06-27 16:18:41.74]: ▸ 27 actionable tasks: 27 executed
INFO [2017-06-27 16:18:43.01]: Couldn't find any new signed apk files...
INFO [2017-06-27 16:18:43.05]: --------------------
INFO [2017-06-27 16:18:43.05]: --- Step: supply ---
INFO [2017-06-27 16:18:43.05]: --------------------
Successfully loaded Appfile at path '/Users/maoliveira/workspace/wifi.app.native/fastlane/Appfile'
- json_key_file: 'google_play.json'
- package_name: 'br.com.uol.wifi'
-------
Successfully loaded Appfile at path '/Users/maoliveira/workspace/wifi.app.native/fastlane/Appfile'
- json_key_file: 'google_play.json'
- package_name: 'br.com.uol.wifi'
-------
Successfully loaded Appfile at path '/Users/maoliveira/workspace/wifi.app.native/fastlane/Appfile'
- json_key_file: 'google_play.json'
- package_name: 'br.com.uol.wifi'
-------
Successfully loaded Appfile at path '/Users/maoliveira/workspace/wifi.app.native/fastlane/Appfile'
- json_key_file: 'google_play.json'
- package_name: 'br.com.uol.wifi'
-------
Successfully loaded Appfile at path '/Users/maoliveira/workspace/wifi.app.native/fastlane/Appfile'
- json_key_file: 'google_play.json'
- package_name: 'br.com.uol.wifi'
-------
ERROR [2017-06-27 16:18:44.32]: 'google_play.json' doesn't seem to be a JSON file
ERROR [2017-06-27 16:18:44.32]: You passed invalid parameters to 'supply'.
ERROR [2017-06-27 16:18:44.32]: Check out the error below and available options by running `fastlane action supply`
WARN [2017-06-27 16:18:45.49]: Lane Context:
INFO [2017-06-27 16:18:45.49]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android beta", :GRADLE_BUILD_TYPE=>"Release", :GRADLE_ALL_APK_OUTPUT_PATHS=>[]}
ERROR [2017-06-27 16:18:45.49]: Invalid default value for json_key, doesn't match verify_block
INFO [2017-06-27 16:18:45.49]: Successfully generated documentation at path '/Users/maoliveira/workspace/wifi.app.native/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | gradle              | 93          |
| 💥   | supply              | 1           |
+------+---------------------+-------------+

ERROR [2017-06-27 16:18:45.57]: fastlane finished with errors

```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.9.3 (Apple Git-75)            |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.1                                         |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.37.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    #gradle(task: "assembleRelease")
    #crashlytics

    gradle(task: 'assemble', build_type: 'Release')
    supply(track: 'beta')


    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "google_play.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "br.com.uol.wifi"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.41.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.2        |
| psych                     | 2.2.2        |
</details>

**Comment by OliveiraMaicon** [comment]
I'm signing by Intellij and trying too run this command fastlane supply --apk app/release/app-release.apk --track beta --verbose 

PS: It is a android app

**Comment by capyvara** [comment]
Is this google_play.json in the current working directory? if so it should look like this:
```
{
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  "client_email": "...@...",
  "client_id": "...",
  "type": "service_account"
}
```

If not, follow the instructions to generate it: https://github.com/fastlane/fastlane/tree/master/supply#setup

**Comment by OliveiraMaicon** [comment]
That's all right!

Look

{
  "type": "service_account",
  "project_id": "api-project-.....",
  "private_key_id": "713.......",
  "private_key": "-----BEGIN PRIVATE KEY-----\n....",
  "client_email": "....@api-project-.....iam.gserviceaccount.com",
  "client_id": "1127......",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/....%40api-project-......iam.gserviceaccount.com"
}

**Comment by OliveiraMaicon** [comment]
Is the file in the correct directory?
Following link to see my directories 
https://ibb.co/kwvY8Q

**Comment by capyvara** [comment]
I believe somehow supply isn't finding your json file, some stuff you can try:

- Edit your `AppFile` to include the fastlane folder in the path to json file `json_key_file "fastlane/google_play.json"`
- Pass the full path to your json file in the command-line --json_key "/xxxxxxx/fastlane/google_play.json"`

**Comment by OliveiraMaicon** [comment]
Didn't work...

Edit your AppFile to include the fastlane folder in the path to json file json_key_file "fastlane/google_play.json"

`fastlane supply  --apk app/release/app-release.apk  --verbose
ERROR [2017-06-28 15:36:38.74]: 'fastlane/google_play.json' doesn't seem to be a JSON file
/Users/maoliveira/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.41.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Invalid default value for json_key, doesn't match verify_block (FastlaneCore::Interface::FastlaneError)
`

Pass the full path to your json file in the command-line --json_key "/xxxxxxx/fastlane/google_play.json"`

`supply --json_key /Users/maoliveira/workspace/wifi.app.native/fastlane/google_play.json --apk app/release/app-release.apk  --verbose`
`Error setting value '/Users/maoliveira/workspace/wifi.app.native/fastlane/google_play.json' for option 'json_key'
/Users/maoliveira/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.41.0/fastlane_core/lib/fastlane_core/configuration/config_item.rb:142:in `rescue in valid?': [!] '/Users/maoliveira/workspace/wifi.app.native/fastlane/google_play.json' doesn't seem to be a JSON file (FastlaneCore::Interface::FastlaneError)`

**Comment by OliveiraMaicon** [comment]
It worked!

Thanks a lot!

```
fastlane supply  --apk app/release/app-release.apk  --verbose

+-------------------------+-----------------------------+
|               Summary for supply 2.41.0               |
+-------------------------+-----------------------------+
| apk                     | app/release/app-release.apk |
| package_name            | br.com.uol.wifi             |
| track                   | production                  |
| rollout                 | 0.1                         |
| json_key                | fastlane/google_play.json   |
| skip_upload_apk         | false                       |
| skip_upload_metadata    | false                       |
| skip_upload_images      | false                       |
| skip_upload_screenshots | false                       |
| validate_only           | false                       |
| check_superseded_tracks | false                       |
+-------------------------+-----------------------------+

DEBUG [2017-06-28 15:40:16.21]: Fetching a new access token from Google...

Looking for related GitHub issues on fastlane/fastlane...
Search query: Unauthorized
```

This authorization problem is related to the json keys, right?

**Comment by capyvara** [comment]
Not sure without the log, be sure to follow the exact instructions on
https://github.com/fastlane/fastlane/tree/master/supply#setup

**Comment by jpca999** [comment]
I got the same error, I dont know why
