### ISSUE TITLE
Automatically review and rollout

### ISSUE THREAD

**Issue by sergiulucaci** [fastlane/fastlane#9615]
Hey awesome guys, 

question regarding Android:
it is possible to use fastlane for publishing to Alpha a “ready for publish” application (I’m referring to an application that wasn’t published yet to Alpha)? 
I have to manually publish for the first time the app to Alpha for automate deployment process?

**Comment by taquitos** [comment]
If the app is already registered w/ the console, I think it should work. If it doesn’t let us know :+1:

**Comment by sergiulucaci** [comment]
hei @taquitos,

thank you for response. Yeah, the app is registered, but I’m asking this because I don’t find in documentation how I could use fastlane to review and rollout for the first time to one track a “Ready to publish app”.  I can just update the APK to the released app using supply. 

ps.: A quick feature that did this is that I integrated a selenium job that reviews and starts the rollout data.
