### ISSUE TITLE
Fails to upload OSX app to HockeyApp

### ISSUE THREAD

**Issue by satyavrat** [fastlane/fastlane#9616]
### New Issue Checklist

- [YES] Updated fastlane to the latest version
- [YES] I have read the [Contribution Guidelines]

### Issue Description
I am trying to build a OSX app and upload it to hockey for QA & beta distribution 
I was able to build the app and generate .dsym too. it fails at the stage of uploading to Hockeyapp. this is the error I get:

 **File exists @ sys_fail2 - /Users/satyavrat/macos/MyApp/MyApp.app/Contents/Frameworks/HockeySDK.framework/Resources**

##### Complete output when running fastlane, including the stack trace and command used

Attaching the whole --capture_output

INFO [2017-06-29 14:44:03.40]: ▸ Copying HockeySDK-Mac/HockeySDK.framework
INFO [2017-06-29 14:44:03.55]: ▸ Signing /Users/satyavrat/Library/Developer/Xcode/DerivedData/MyApp-ednhhgtcuyyhvobegbfadhfhvkcd/Build/Intermediates/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app/Contents/Frameworks/HockeySDK.framework
INFO [2017-06-29 14:44:03.69]: ▸ Touching MyApp.app
INFO [2017-06-29 14:44:03.78]: ▸ Signing /Users/satyavrat/Library/Developer/Xcode/DerivedData/MyApp-ednhhgtcuyyhvobegbfadhfhvkcd/Build/Intermediates/ArchiveIntermediates/MyApp/InstallationBuildProductsLocation/Applications/MyApp.app
INFO [2017-06-29 14:44:03.94]: ▸ Touching MyApp.app.dSYM
INFO [2017-06-29 14:44:04.15]: ▸ Archive Succeeded
DEBUG [2017-06-29 14:44:04.49]: Stored the archive in: /Users/satyavrat/Library/Developer/Xcode/Archives/2017-06-29/MyApp 2017-06-29 14.43.37.xcarchive
INFO [2017-06-29 14:44:04.50]: Compressing 1 dSYM(s)
INFO [2017-06-29 14:44:04.50]: $ cd '/Users/satyavrat/Library/Developer/Xcode/Archives/2017-06-29/MyApp 2017-06-29 14.43.37.xcarchive/dSYMs' && zip -r '/Users/satyavrat/moktale/macos/MyApp/MyApp.app.dSYM.zip' *.dSYM
INFO [2017-06-29 14:44:04.91]: ▸ updating: MyApp.app.dSYM/ (stored 0%)
INFO [2017-06-29 14:44:04.91]: ▸ updating: MyApp.app.dSYM/Contents/ (stored 0%)
INFO [2017-06-29 14:44:04.91]: ▸ updating: MyApp.app.dSYM/Contents/Info.plist (deflated 52%)
INFO [2017-06-29 14:44:04.91]: ▸ updating: MyApp.app.dSYM/Contents/Resources/ (stored 0%)
INFO [2017-06-29 14:44:04.91]: ▸ updating: MyApp.app.dSYM/Contents/Resources/DWARF/ (stored 0%)
INFO [2017-06-29 14:44:04.91]: ▸ updating: MyApp.app.dSYM/Contents/Resources/DWARF/MyApp (deflated 68%)

INFO [2017-06-29 14:44:04.91]: Successfully exported and compressed dSYM file
WARN [2017-06-29 14:44:06.57]: Lane Context:
INFO [2017-06-29 14:44:06.57]: {:DEFAULT_PLATFORM=>:macos, :PLATFORM_NAME=>:macos, :LANE_NAME=>"macos beta"}
ERROR [2017-06-29 14:44:06.57]: File exists @ sys_fail2 - /Users/satyavrat/macos/MyApp/MyApp.app/Contents/Frameworks/HockeySDK.framework/Resources
INFO [2017-06-29 14:44:06.57]: Successfully generated documentation at path '/Users/satyavrat/macos/MyApp/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 💥   | gym                 | 31          |
+------+---------------------+-------------+

ERROR [2017-06-29 14:44:06.60]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: File exists @ sys_fail2 - /Users/satyavrat/macos/MyApp/MyApp.app/Contents/Frameworks/HockeySDK.framework/Resources

URL: https://api.github.com/search/issues?q=File%20exists%20@%20sys_fail2%20-%20/Users/satyavrat/macos/MyApp/MyApp.app/Contents/Frameworks/HockeySDK.framework/Resources+repo:fastlane/fastlane
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.41.0"

default_platform :macos

platform :macos do


lane :beta do |values|

  gym(scheme: 'MyApp', export_method: 'development')
  zip(
            path: "MyApp.app",
            output_path: "MyApp.app.zip"
          )
   # Push to Hockey
   hockey(
    api_token: ENV['3c866f8800a645c0a4be2e4cffd18984'],
    ipa:'./MyApp.app.zip'
  )

  end

end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.42.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.9        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.1        |
| cocoapods-core            | 1.2.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.8.4        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 1.1.0        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.6        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.3        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-06-29**
</details>
 [2017-06-29 14:44:09.67]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)
Please enter "yes" or "no".
/Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1370:in `symlink': [!] File exists @ sys_fail2 - /Users/satyavrat/moktale/macos/MyApp/MyApp.app/Contents/Frameworks/HockeySDK.framework/Resources (Errno::EEXIST)
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1370:in `copy'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:471:in `block in copy_entry'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1497:in `call'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1497:in `wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1500:in `block in wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `each'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1499:in `wrap_traverse'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:468:in `copy_entry'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:443:in `block in cp_r'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1584:in `fu_each_src_dest0'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/2.2.0/fileutils.rb:442:in `cp_r'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/gym/lib/gym/runner.rb:186:in `copy_mac_app'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/gym/lib/gym/runner.rb:33:in `run'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/gym/lib/gym/manager.rb:14:in `work'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/actions/gym.rb:51:in `run'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:10:in `block (2 levels) in parsing_binding'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/satyavrat/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.42.0/bin/fastlane:20:in `<top (required)>'
	from /Users/satyavrat/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/satyavrat/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'

**Comment by wolffan** [comment]
We are working on this https://github.com/fastlane/fastlane/pull/9617

**Comment by taquitos** [comment]
2.43.0 was released 🚀, try it out and open a new issue if you find anything else 👍
