### ISSUE TITLE
Upload a file in app_review_information

### ISSUE THREAD

**Issue by quetool** [fastlane/fastlane#9623]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

Hi! Is it possible to upload a file (.pdf) in App Review Information with fastlane deliver (or maybe produce?) I need it to be inside Deliverfile or Appfile, or something like that.

![captura de pantalla 2017-06-29 a la s 14 09 53](https://user-images.githubusercontent.com/14978705/27700778-0a47458a-5cd5-11e7-800a-c0fe1ee35b05.jpg)

**Comment by taquitos** [comment]
No, it's not supported 😞 
If you'd like to have a go at adding this functionality, we'd be happy to review any changes! Here's our [guide to submitting a PR](https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md) if you haven't submitted a PR to _fastlane_ before 👍
