### ISSUE TITLE
How to update Ruby?

### ISSUE THREAD

**Issue by the4thfloor** [fastlane/fastlane#9627]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I want to use [slather](https://docs.fastlane.tools/actions/#slather) to generate a code coverage report. But my problem: to install slather I need a updated Ruby version, the bundled one is too old :-(

I tried to update Ruby following this [steps](https://stackoverflow.com/a/36485498/1016472) but without success. At the end Jenkins found fastlane and slather but it didn't found xcpretty.

Is it possible to update the bundled Ruby version?

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.42.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.4        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-06-29**
</details>

**Comment by KrauseFx** [comment]
Sorry we can't update the bundled Ruby version, as we use some third party code that doesn't support newer versions yet.

**Comment by the4thfloor** [comment]
Okay I try to update the system Ruby version :-)

**Comment by johnknapprs** [comment]
Personally, I just `brew install ruby` as that'll pull the latest stable.  For me, it's 2.4.1p111. 

Another alternative to rbenv is RVM.  For awhile I was using RVM after having headaches with rbenv.  It worked fine, ultimately I didn't need to support multiple versions of Ruby and installing via brew was more than enough to get off the system version of Ruby.

**Comment by PetrosIchor** [comment]
Personally, I just brew install ruby as that'll pull the latest stable. For me, it's 2.4.1p111.

Another alternative to rbenv is RVM. For awhile I was using RVM after having headaches with rbenv. It worked fine, ultimately I didn't need to support multiple versions of Ruby and installing via brew was more than enough to get off the system version of Ruby.

**Comment by Sulfkain** [comment]
@the4thfloor Have you achieve to update your Ruby?
I updated Ruby version on differents computers without problems

I have followed this steps:

If you use rbenv with ruby-build. 
But if you want to install it, follow this walkthrough https://github.com/rbenv/rbenv#homebrew-on-mac-os-x and then:

    Run `brew install ruby-build` if you didn't installed
    or `brew upgrade ruby-build` if you did
    Run `brew update && rbenv install 2.3.1`
    Run `rbenv global 2.3.1` to make it the new global default Ruby version
    Write on command line `echo 'if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi' >> ~/.bash_profile `
This will set the correct ruby version 2.3.1 as default for your system

Before checking everything is correct, you will need to open a new brand terminal, then:

    Write `ruby --version` ; The prompt will show you the version of ruby, which should be 2.3.1, if version is 2.0.0, something is wrong, it's getting the ruby system.

Hope this helps

**Comment by ohayon** [comment]
Hey everyone! ❤️  seeing everyone help out with Ruby issues! I am going to close this issue for now because it seems like this conversation should be good to help people update ruby versions. Let us know if there is anything else we can help out with!! 🚀
