### ISSUE TITLE
when i run build_using_gym.sh it's output  can't find gem fastlane (>= 0.a) (Gem::GemNotFoundException

### ISSUE THREAD

**Issue by yuzhongqi** [fastlane/fastlane#9637]
when i run build_using_gym.sh  it's output 
/usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem fastlane (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/fastlane:22:in `<main>'
what's wrong about it

**Comment by taquitos** [comment]
Hey @yuzhongqi I'm not familiar with `build_using_gym.sh` it's not something we wrote. Do you get the same issue if you setup _fastlane_ using the [getting started guide](https://docs.fastlane.tools/getting-started/ios/setup/) and running _gym_ manually?

**Comment by Sulfkain** [comment]
Yes, seems to come from other repository
[Google Search build_using_gym.sh](https://www.google.es/search?q=build_using_gym&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&ei=6BF7WdCuL-OJ8Qet5b7wCg)

@yuzhongqi will be better if you post on the right repo (Whatever it be).
