### ISSUE TITLE
fastlane gym fails with exit status 65

### ISSUE THREAD

**Issue by santoshshetty2612** [fastlane/fastlane#9638]
Hi,

fastlane gym is failing randomly with exit status 65 and there is no information in detailed log file either.

I get random error like archive file for File1.
** ARCHIVE FAILED **

The following build commands failed:
CompileC for File1

If I remove File1 then its starts throwing error on File2.

**Comment by taquitos** [comment]
Hey @santoshshetty2612, it would help us figure out the root cause if you could include your output from `fastlane env` along with the detailed log file. Feel free to redact/change anything that is private.

**Comment by santoshshetty2612** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE | en_US:en    | 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.7       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.1       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
</details>


*generated on:* **2017-07-03**
</details>

**Comment by santoshshetty2612** [comment]
Hi @taquitos, I am attaching the detailed log file.
The archive fails but its not consistent. It works 1 out of 10 times.

Also I tried the build with an older working branch still the problem exists.
[Jenkins.log.zip](https://github.com/fastlane/fastlane/files/1118620/Jenkins.log.zip)

**Comment by santoshshetty2612** [comment]
Hi @taquitos, I am attaching the detailed log file.
The archive fails but its not consistent. It works 1 out of 10 times.

Also I tried the build with an older working branch still the problem exists.

I am attaching the log file which fastlane mentions at /Users/Shared/Jenkins/Library/Logs/gym/, but it seems this is not the complete log. If this doesn't works for you, please let me know. Will try to extract the Jenkins console log.

[details.log.zip](https://github.com/fastlane/fastlane/files/1118649/details.log.zip)

**Comment by KrauseFx** [comment]
Sorry, I can't seem to access the log file.

**Comment by santoshshetty2612** [comment]
[details.log.zip](https://github.com/fastlane/fastlane/files/1119156/details.log.zip)

**Comment by santoshshetty2612** [comment]
Hi @KrauseFx, @taquitos 
The issue has been resolved. The issue was in the corrupted Jenkins workspace. I copied the current job into a new job and everything worked fine.

Thanks for your support.

**Comment by KrauseFx** [comment]
Glad to hear :)
