### ISSUE TITLE
Gym in Xcode 9 fails on certificate type.

### ISSUE THREAD

**Issue by wainglaister** [fastlane/fastlane#9642]
### Issue Description

Installed everything yesterday so all latest & new.

I'm trying to maintain auto signing in the project with specific signing in the fast file. So, I've got a fast file with setup and then gym is using a number of xcargs. The certificate is installed and sigh is copying the appropriate profile.

````
    sigh(
        provisioning_name: "AZ_xxx_QA",
        ignore_profiles_with_different_name: true,
    )
    disable_automatic_code_signing
    update_project_provisioning(
        profile: "./InHouse_xxx.qa.mobileprovision",
    )
    gym(
        configuration: "QA",
        export_method: "enterprise",
        xcargs: "PRODUCT_BUNDLE_IDENTIFIER='xxx.qa' APP_BUNDLE_ID='xxx.qa' PROVISIONING_PROFILE='#{lane_context[SharedValues::SIGH_UDID]}' CODE_SIGN_IDENTITY='iOS Distribution: XXX'",
    )
````

##### Complete output

This breaks Xcode somehow, specifically:

Provisioning inputs for "AZ" didn't provide a certificate type. Repair will be incomplete because it lacks certificate type information.

xcodebuild and result:

````
build	30-Jun-2017 17:12:48	[17:12:48]: [4m[36m$ set -o pipefail && xcodebuild -scheme AZ -project ./AZ.xcodeproj -configuration QA -destination 'generic/platform=iOS' -archivePath ....xcarchive PRODUCT_BUNDLE_IDENTIFIER='xxx.qa' APP_BUNDLE_ID='xxx.qa' PROVISIONING_PROFILE='b8f74a3a-b9dc-4d6e-b00d-1a21b88a2157' CODE_SIGN_IDENTITY='iOS Distribution: XXX' archive | tee /Users/admin/Library/Logs/gym/AZ-AZ.log | xcpretty[0m[0m
build	30-Jun-2017 17:12:49	[17:12:49]: [35m[33mâ–¸[0m [39;1mBuilding[0m AZ/AZ [QA][0m
build	30-Jun-2017 17:12:49	[17:12:49]: [35m[33mâ–¸[0m [39;1mCheck Dependencies[0m
build	30-Jun-2017 17:12:49	[17:12:49]: â–¸ [35m2017-06-30 17:12:49.561 xcodebuild[55497:587576]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-13158.29/IDEFoundation/Provisioning/Mechanic/IDEProvisioningRepairInfo.m:66[0m
build	30-Jun-2017 17:12:49	[17:12:49]: â–¸ [35mDetails:  Provisioning inputs for "AZ" didn't provide a certificate type. Repair will be incomplete because it lacks certificate type information.[0m
build	30-Jun-2017 17:12:49	[17:12:49]: â–¸ [35mObject:   <IDEProvisioningRepairInfo>[0m
build	30-Jun-2017 17:12:49	[17:12:49]: â–¸ [35mMethod:   +repairInfoWithProvisioningInputs:instigatingErrors:[0m
build	30-Jun-2017 17:12:49	[17:12:49]: â–¸ [35mThread:   <NSThread: 0x7fd150b38a60>{number = 21, name = (null)}[0m
build	30-Jun-2017 17:12:49	[17:12:49]: â–¸ [35mPlease file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.[0m
build	30-Jun-2017 17:12:49	[17:12:49]: â–¸ [35m[31mâŒ  Code signing is required for product type 'Application' in SDK 'iOS 11.0'[0m
````

Can't find any similar issues :(

**Comment by wainglaister** [comment]
Yes, I've read the troubleshooting guide (multiple times) :)
I'm not using match because i don't want to wipe the current contents of my account, but equally i think the certificate and profile on the build machine looks fine.

**Comment by taquitos** [comment]
Thanks for the report, we're hoping to pull in some Xcode 9 work soon!

**Comment by taquitos** [comment]
Also, @wainglaister _match_ won't delete anything unless you run `fastlane match nuke` 
_match_ might repair broken provisioning profiles, but that's good behavior 👍

**Comment by casz** [comment]
Seeing the same error message with match on xcode 9: #9589

**Comment by ohayon** [comment]
Hey folks! In trying to reproduce this issue, I have run into another set of Xcode 9 bugs. I am wondering if you all are still seeing this issue? Let us know if its still going on! 🚀

**Comment by wainglaister** [comment]
I'm not seeing exactly the same issue with beta 4, instead I have an obscure bitcode error that I can find very little info on. I haven't had much time to look into it so at the moment i can't use fast lane for my builds :(

**Comment by qnoid** [comment]
What is that bitcode error you are referring to?

I had to set `compileBitcode` to `false` in the exportOptions.plist used with the `exportArchive` flag because it was crashing.

**Comment by wainglaister** [comment]
Ok, I'll check on exactly what I have set for bitcode tomorrow, I don't have access to it right now. The bitcode error is that ipatool crashes, I don't remember all the details off hand, just NonZeroExcitException (9 hits in google for that...)

**Comment by qnoid** [comment]
Sounds like it.

Here is what I got.

```
2017-08-02 14:11:36.922820+0100 windmill[67657:9276206] [export] 2017-08-02 14:11:36.922652+0100 xcodebuild[68270:9283384] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x60000000b9e0>: Error Domain=IDEFoundationErrorDomain Code=1 "ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: CmdSpec::NonZeroExcitException>
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:209:in `run'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2178:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `each'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2314:in `ProcessIPA'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2929:in `<main>'" UserInfo={NSLocalizedDescription=ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: CmdSpec::NonZeroExcitException>
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:209:in `run'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2178:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `each'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2314:in `ProcessIPA'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2929:in `<main>'}
2017-08-02 14:11:36.932321+0100 windmill[67657:9276206] [export] error: exportArchive: ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: CmdSpec::NonZeroExcitException>
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:209:in `run'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2178:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `each'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2314:in `ProcessIPA'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2929:in `<main>'

Error Domain=IDEFoundationErrorDomain Code=1 "ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: CmdSpec::NonZeroExcitException>
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:209:in `run'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2178:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `each'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2314:in `ProcessIPA'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2929:in `<main>'" UserInfo={NSLocalizedDescription=ipatool failed with an exception: #<CmdSpec::NonZeroExcitException: CmdSpec::NonZeroExcitException>
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:209:in `run'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2178:in `block in CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `each'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2130:in `CompileOrStripBitcodeInBundle'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2314:in `ProcessIPA'
    /Applications/Xcode-beta.app/Contents/Developer/usr/bin/ipatool:2929:in `<main>'}
2017-08-02 14:11:36.949135+0100 windmill[67657:9276206] [export] ** EXPORT FAILED **
```

**Comment by eysteinbye** [comment]
With Xcode 9 Beta 5 my `gym` / `scan` is stoping on `showBuildSettings` now, so I am unable to check the signing at this point. Looks like an issue with beta 5.
`xcodebuild -showBuildSettings timed-out after 10 seconds and 3 retries`

**Comment by ohayon** [comment]
So.... @eysteinbye is seeing the same issue that some of us are running into which is definitely a bug in Xcode 9 beta 5. 

@qnoid - I've never seen that issue before 🤔 . Would you mind sharing some of the output from higher up in the process just to see some more context around it? Also, would you mind trying to execute the `xcodebuild` command that _fastlane_ prints out for you without executing _fastlane_ itself? I'm curious if this is happening when `xcodebuild` is invoked directly. Thanks!! 

We are still trying to work through these issues, but we are also subject to some of these bugs 😢 . We will keep this issue up-to-date with progress though! 🚀

**Comment by wainglaister** [comment]
I was having the same issue as @qnoid and changing my lane to explicitly use the export plist that Xcode generates when you manually archive and export has resolved it. Note I'm still using beta 4.

The main difference in the export options is the bitcode flag `<key>compileBitcode</key><false/>`. I have `include_bitcode: false` in my fast file so i guess it's the lack of bitcode in the archive and that it tried to use bitcode in the export that caused it to fall on its face. 

The error that @qnoid logged above is all you get, it's a terrible error output from Xcode :( I haven't tried manually running the `xcodebuild` command.

**Comment by qnoid** [comment]
@ohayon sorry for the confusion. I am not a fastlane user. This output is from running `xcodebuild` directly in Xcode 9 beta 4, e.g.

`xcodebuild -exportArchive -archivePath build/$PROJECT_NAME.xcarchive -exportOptionsPlist ~/Users/qnoid/exportOptions.plist -exportPath exportArchive -allowProvisioningUpdates`

**Comment by ohayon** [comment]
Ohhh got it! Thanks for the info @qnoid!

I think for now we should focus on fixing things issues with current betas and not worry about issues that were around in earlier betas especially as we get closer to when Apple will release the GM. @wainglaister would you mind sharing what the behavior is in Xcode 9 beta 5? 🐙

**Comment by qnoid** [comment]
For what is worth, I no longer see the crash with Xcode 9 beta 5.
