### ISSUE TITLE
Error using gym (You passed invalid parameters to 'gym', Could not find option 'provisioning_profile_path')

### ISSUE THREAD

**Issue by eventwo-com** [fastlane/fastlane#9645]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines]

### Issue Description

Hi!. Since yesterday, there is an error when I try to compile:

[19:21:38]: -----------------
[19:21:38]: --- Step: gym ---
[19:21:38]: -----------------
[19:21:38]: You passed invalid parameters to 'gym'.
[19:21:38]: Check out the error below and available options by running `fastlane action gym`
[19:21:39]: Liberando lock
[19:21:39]: ERROR in fastlane itunes_upload for the app volvoxc60
[19:21:39]: --------------------------
[19:21:39]: --- Step: notification ---
[19:21:39]: --------------------------
+-----------------------------+-----------------------------------------------------------------------------+
|                                               Lane Context                                                |
+-----------------------------+-----------------------------------------------------------------------------+
| DEFAULT_PLATFORM            | ios                                                                         |
| PLATFORM_NAME               | ios                                                                         |
| LANE_NAME                   | ios createapp                                                               |
---------+
[19:21:39]: Could not find option 'provisioning_profile_path' in the list of available options: workspace, project, scheme, clean, output_directory, output_name, configuration, silent, codesigning_identity, skip_package_ipa, include_symbols, include_bitcode, export_method, export_options, export_xcargs, skip_build_archive, build_path, archive_path, derived_data_path, result_bundle, buildlog_path, sdk, toolchain, destination, export_team_id, xcargs, xcconfig, suppress_xcode_output, disable_xcpretty, xcpretty_test_format, xcpretty_formatter, xcpretty_report_junit, xcpretty_report_html, xcpretty_report_json, analyze_build_time, xcpretty_utf

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.4                                          |
| Ruby                        | 2.2.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.8.2                                |
| Installation Source         | /usr/local/var/rbenv/versions/2.2.2/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)                        |
| Ruby Lib Dir                | /usr/local/var/rbenv/versions/2.2.2/lib          |
| OpenSSL Version             | OpenSSL 1.0.2d 9 Jul 2015                        |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode7.app/Contents/Developer/     |
| Xcode Version               | 7.3.1                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   | es_ES.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.44.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| rubyzip                   | 1.2.1        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
</details>

**Comment by taquitos** [comment]
Hey @eventwo-com, we removed this recently since it has been deprecated for over a year now and unsupported. You can learn about the differences in the [code signing section of our getting started guide](https://docs.fastlane.tools/codesigning/xcode-project/) so you can use new way to do it  🎉
We removed this functionality because you can no longer submit to Apple using Xcode 7.

**Comment by eventwo-com** [comment]
Hi @taquitos, thanks a lot for your response. We will try to downgrade our fastlane version meanwhile we implement changes needed.

**Comment by KrauseFx** [comment]
@eventwo-com We'd advice against downgrading fastlane, as you'll have to migrate to the latest Xcode sooner or later. Really sorry we removed this option, but it has been deprecated for over a year and it was necessary. Instead try to follow our code signing guide, which should make it easy to upgrade 👍

**Comment by eventwo-com** [comment]
Hi @KrauseFx, thanks a lot for your response. We are already working on it!

Kind regards

**Comment by KrauseFx** [comment]
Nice, great to hear 👍
