### ISSUE TITLE
snapshot adds 'Mac' to devices list after detecting values from Snapfile

### ISSUE THREAD

**Issue by emarley** [fastlane/fastlane#9648]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
snapshot tries to capture macOS screenshots, even though macOS is not in the SnapFile's devices list.
In the attached log, the Snapfile Detected Values correctly contains just one iPad in the devices list. Then the Summary has both the one iPad AND an entry for "Mac". 
The workspace is cross-platform, but I do not *want* to generate macOS screenshots right now. 
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

emarley@charagon% snapshot
[14:25:11]: Successfully loaded '/Users/emarley/Source/PATH_ELIDED/SomeAppName/iPad/Screenshots/Snapfile' 📄

+----------------------------+--------------------------------------+
|                 Detected Values from './Snapfile'                 |
+----------------------------+--------------------------------------+
| devices                    | ["iPad Pro (9.7-inch)"]              |
| languages                  | ["en-US", "pt-BR"]                   |
| scheme                     | SomeAppName-iOS                      |
| output_directory           | ~/Desktop/screenshots                |
| derived_data_path          | /tmp/Snapshot/DerivedData            |
| clear_previous_screenshots | true                                 |
| erase_simulator            | true                                 |
| number_of_retries          | 2                                    |
| workspace                  | ../../../../Workspaces/SomeAppName.  |
|                            | xcworkspace                          |
+----------------------------+--------------------------------------+

[14:25:11]: $ xcodebuild -list -workspace ../../../../Workspaces/SomeAppName.xcworkspace
[14:25:16]: $ xcodebuild -showBuildSettings -workspace ../../../../Workspaces/SomeAppName.xcworkspace -scheme SomeAppName-iOS

+----------------------------+--------------------------------------+
|                    Summary for snapshot 2.44.1                    |
+----------------------------+--------------------------------------+
| devices                    | ["iPad Pro (9.7-inch)", "Mac"]       |
| languages                  | ["en-US", "pt-BR"]                   |
| scheme                     | SomeAppName-iOS                      |
| output_directory           | /Users/emarley/Desktop/screenshots   |
| derived_data_path          | /tmp/Snapshot/DerivedData            |
| clear_previous_screenshots | true                                 |
| erase_simulator            | true                                 |
| number_of_retries          | 2                                    |
| workspace                  | ../../../../Workspaces/SomeAppName.  |
|                            | xcworkspace                          |
| launch_arguments           | [""]                                 |
| output_simulator_logs      | false                                |
| skip_open_summary          | false                                |
| skip_helper_version_check  | false                                |
| reinstall_app              | false                                |
| localize_simulator         | false                                |
| buildlog_path              | ~/Library/Logs/snapshot              |
| clean                      | false                                |
| stop_after_first_error     | false                                |
| xcode_path                 | /Applications/Xcode.app              |
+----------------------------+--------------------------------------+

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-06-30**
</details>

**Comment by emarley** [comment]
From reading this thread: https://github.com/fastlane/fastlane/pull/7363
It seems maybe that was deliberate? But it leaves me no way to opt *out* of this behavior?

**Comment by emarley** [comment]
The iOS-only scheme depends on some build steps which think they are macOS. If I change their supported platform to iOS, then I can't build my app anymore. It fails with 
> target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphonesimulator' platform

**Comment by KrauseFx** [comment]
Maybe this is related to your project setup somehow. Could you let us know on how we can best reproduce? Could you prepare an empty sample app that runs into the same problem? 👍

**Comment by emarley** [comment]
Thanks for looking into this.

The TextEditor workspace in https://github.com/omnigroup/OmniGroup has this setup (and may provide context for why we have macOS targets in an iOS-only build).

`xcodebuild -showBuildSettings -workspace TextEditor.xcworkspace -scheme TextEditor`

> Build settings for action build and target FixStringsFile:
> [...]
> SUPPORTED_PLATFORMS = macosx
> [...]
> Build settings for action build and target TextEditor:
> [...]
> SUPPORTED_PLATFORMS = iphonesimulator iphoneos
> [...]
