### ISSUE TITLE
Unsupported screen size [1668, 2224] - iPad Pro10.5 inch

### ISSUE THREAD

**Issue by ardee19** [fastlane/fastlane#9651]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
when I ran `fastlane frameit` I get an error for some screenshot I got from snapshot just certain size, size [1668, 2224]. Everything else works just fine

I'm running it individually not with fastlane fastfile.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

command used: `fastlane frameit silver`

**Error Example:**
[19:10:54]: Framing screenshot './en-US/iPadPro(10.5-inch)-0-seoul_en-d41d8cd98f00b204e9800998ecf8427e.png'
[19:10:54]: Unsupported screen size [1668, 2224] for path './en-US/iPadPro(10.5-inch)-0-seoul_en-d41d8cd98f00b204e9800998ecf8427e.png'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.2                          |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| openssl                   | 2.0.2        |
</details>

*generated on:* **2017-07-01**
</details>

**Comment by KrauseFx** [comment]
Hey @ardee19, thanks for submitting this issue and letting us know. Just so I can look into this faster, would you mind sharing one of the screenshots that's failing for you? You can send it to my email on my GitHub profile if you prefer it to stay private 👍

**Comment by lightsprint09** [comment]
hey. I get the same problem, when uploading screenshots with `deliver`. Here is one of the failing screenshots
![ipadpro 10 5-inch -03athletesperformancedetails-d41d8cd98f00b204e9800998ecf8427e](https://user-images.githubusercontent.com/3703083/27838331-2d43da6c-60ea-11e7-8028-83863b090027.png)

**Comment by ardee19** [comment]
Hey @KrauseFx ! Sorry, wasn't able to respond immediately. Do you still need the screenshot? @lightsprint09 screenshot has the same size and fails the same way.

**Comment by KrauseFx** [comment]
Alright, thanks everyone for providing the screenshot, I'll look into this tonight :+1:

**Comment by wuftymerguftyguff** [comment]
Essentially the same error but with "fastlane deliver".  Assuming the issue is related to the 10.5" iPad Pro screen res.

message:

[!] Unsupported screen size [1668, 2224] for path './fastlane/screenshots/en-US/iPadPro(10.5-inch)-01LoginScreen-d41d8cd98f00b204e9800998ecf8427e.png'

**Comment by lightsprint09** [comment]
For Me it helps to just remove the 10.5 images from the folder to `deliver` all my screenshots

**Comment by fixpunkt** [comment]
Same problem here, with latest fastlane 2.58.0:

```
[15:42:05]: Unsupported screen size [2224, 1668] for path '/Users/jannik/viison/apps/POSApp/fastlane/screenshots/de-DE/iPad Pro (10.5-inch)-0-shopping-basket.png'
```

**Comment by Mikrasya** [comment]
I also have the same issue. 
[!] Unsupported screen size [1668, 2224] for path './fastlane/screenshots/el/iPad Pro (10.5-inch)-0List.png'

@fixpunkt I see that we have another common issue (https://github.com/fastlane/fastlane/issues/10259) and I am wondering these are related somehow.

**Comment by Mikrasya** [comment]
Looks like new sizes are not added to the fastlane deliver script yet: https://github.com/fastlane/fastlane/blob/master/deliver/lib/deliver/app_screenshot.rb

There is no iPhone X size (1125x2436) or iPad 10.5 inch size (1668x2224)

**Comment by Mikrasya** [comment]
I found this comment while searching for information:

The resolution should be 2731 x 2048, not 2732. 2048 x 2048 = 4,194,304 / 1536 = 2730.66667, it makes no sense for Apple to bump it to 2732. 1 extra line of pixels doesn't do anything for UI. It would make the aspect ratio 683 : 512 instead of a perfect 4 : 3.
https://www.imore.com/ipad-pro-once-again-shown-testing-new-app-analytics

So, it might be more nuanced. 

For the time being, I have manually resized the images from 2731 to 2732 and submitted my app. Thanks.

**Comment by martinschilliger** [comment]
Well, in https://github.com/fastlane/fastlane/issues/10582 @SeanRobinson159 says that
> iTunes connect doesn't currently support iPhone X screenshots.

Maybe the same is with iPad 10.5 inch size?

**Comment by SeanRobinson159** [comment]
As of October 27, iTunes Connect now supports iPhone X screenshots. https://itunespartner.apple.com/en/apps/news/5993372

Refer to http://help.apple.com/itunes-connect/developer/#/devd274dd925 for supported screenshot sizes.

**Comment by martinschilliger** [comment]
Thank you!

> Maybe the same is with iPad 10.5 inch size?
So it is, iPad 10.5 inch isn't on the list. So I think this isn't acutally an issue and should be closed, right?

**Comment by SeanRobinson159** [comment]
Apple's documentation is weird because it says in the iPad 9.7" section that the 10.5" will work, but it doesn't have screen resolutions for it. Maybe the 10.5" screenshot will work **IF** there aren't any 9.7" screenshots already uploaded. That's really just a guess though.

**Comment by Jules2010** [comment]
Although as mentioned above this isn't required by itc, I think frameit should still provide it.

**Comment by Jules2010** [comment]
@krausefx I can’t help feeling that I’ve seen that you’ve fixed this already?

**Comment by IchHabRecht** [comment]
IMHO this issue is still valid. As far as I can see, Apple (now) offers uploads for 10.5'' screens as well. frameit still doesn't support 10.5'' screenshots and skips them.

**Comment by Jules2010** [comment]
+1

**Comment by IchHabRecht** [comment]
Still an issue

**Comment by MarkAMcCorkle** [comment]
+1 This is still an issue for me as well. Sorry, but it's the only "red" I see in my beautiful fastlane CI build. ;-)

**Comment by Jules2010** [comment]
I have to agree, I haven’t looked to see if I / we could fix this ourselves, would it require much work @krausefx

**Comment by IchHabRecht** [comment]
Any solution available yet @Jules2010 @KrauseFx

**Comment by breezertwo** [comment]
It's an issue for me as well. Hope there is a solution soon.

**Comment by cyupa** [comment]
Happening to me as well.

> 'Couldn't find template for screenshot type 'Apple true Space Gray'
