### ISSUE TITLE
increment_build_number not working correctly. 

### ISSUE THREAD

**Issue by ilandbt** [fastlane/fastlane#9652]
### New Issue Checklist

- [v] Updated fastlane to the latest version
- [v] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi,
When running `increment_build_number` or `increment_version_number`
The version/build is not getting incremented in the info.plist.
It is getting saved somewhere because fastlane is outputting the correct "Current version of project Quest is:"

This started to happen after i reorganized my project groups and folders.

How can i fix this to work again?

Thanks

### Captured Output

Command Used: `build`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest/fastlane/Appfile'
- app_identifier: 'com.valera.valera'
- apple_id: 'rdteam@valerahealth.com'
-------
DEBUG [2017-07-02 15:07:30.08]: Checking if there are any plugins that should be loaded...
INFO [2017-07-02 15:07:30.14]: -------------------------------------------------
INFO [2017-07-02 15:07:30.14]: --- Step: Verifying required fastlane version ---
INFO [2017-07-02 15:07:30.14]: -------------------------------------------------
INFO [2017-07-02 15:07:30.14]: Your fastlane version 2.44.1 matches the minimum requirement of 2.14.2  ✅
INFO [2017-07-02 15:07:30.15]: ------------------------------
INFO [2017-07-02 15:07:30.15]: --- Step: default_platform ---
INFO [2017-07-02 15:07:30.15]: ------------------------------
INFO [2017-07-02 15:07:30.15]: Driving the lane 'ios build' 🚀
INFO [2017-07-02 15:07:30.16]: ------------------------------------
INFO [2017-07-02 15:07:30.16]: --- Step: increment_build_number ---
INFO [2017-07-02 15:07:30.16]: ------------------------------------
INFO [2017-07-02 15:07:30.83]: $ cd /Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest && agvtool next-version -all && cd -
INFO [2017-07-02 15:07:31.44]: ▸ Setting version of project Quest to:
INFO [2017-07-02 15:07:31.44]: ▸ 59.
INFO [2017-07-02 15:07:31.48]: ▸ Also setting CFBundleVersion key (assuming it exists)
INFO [2017-07-02 15:07:31.51]: ▸ Updating CFBundleVersion in Info.plist(s)...
INFO [2017-07-02 15:07:31.52]: ▸ $(SRCROOT)/Targets/Quest-Test/Quest-Test-Info.plist
INFO [2017-07-02 15:07:31.53]: ▸ Cannot find "$(SRCROOT)/Targets/Quest-Test/Quest-Test-Info.plist"
INFO [2017-07-02 15:07:31.53]: ▸ $(SRCROOT)/Targets/Quest/Info.plist
INFO [2017-07-02 15:07:31.53]: ▸ Cannot find "$(SRCROOT)/Targets/Quest/Info.plist"
INFO [2017-07-02 15:07:31.54]: ▸ Updated CFBundleVersion in "Quest.xcodeproj/../QuestTests/Info.plist" to 59
INFO [2017-07-02 15:07:31.56]: ▸ Updated CFBundleVersion in "Quest.xcodeproj/../QuestUITests/Info.plist" to 59
INFO [2017-07-02 15:07:31.56]: ▸ /Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest
INFO [2017-07-02 15:07:32.18]: ------------------------
INFO [2017-07-02 15:07:32.18]: --- Step: git_commit ---
INFO [2017-07-02 15:07:32.18]: ------------------------
INFO [2017-07-02 15:07:32.19]: $ git commit -m build\ Bump .
INFO [2017-07-02 15:07:32.54]: ▸ [dev 9f258f1] build Bump
INFO [2017-07-02 15:07:32.54]: ▸ 3 files changed, 8 insertions(+), 8 deletions(-)
INFO [2017-07-02 15:07:32.54]: Successfully committed "." 💾.
INFO [2017-07-02 15:07:32.54]: --------------------------------
INFO [2017-07-02 15:07:32.54]: --- Step: push_to_git_remote ---
INFO [2017-07-02 15:07:32.54]: --------------------------------
INFO [2017-07-02 15:07:32.56]: $ pwd
INFO [2017-07-02 15:07:32.56]: ▸ /Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest
INFO [2017-07-02 15:07:32.56]: $ git push origin dev:dev --tags
INFO [2017-07-02 15:07:36.12]: ▸ To https://github.com/vethos/IOSQuest.git
INFO [2017-07-02 15:07:36.12]: ▸ 60ba376..9f258f1  dev -> dev
INFO [2017-07-02 15:07:36.13]: Successfully pushed to remote.
INFO [2017-07-02 15:07:36.14]: Successfully generated documentation at path '/Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | increment_build_numbe  | 2           |
|      | r                      |             |
| 4    | git_commit             | 0           |
| 5    | push_to_git_remote     | 3           |
+------+------------------------+-------------+

INFO [2017-07-02 15:07:36.17]: fastlane.tools finished successfully 🎉


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.14.2"

default_platform :ios
# crashlytics
platform :ios do
    before_all do
        ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
        ENV["GITHUB_TOKEN"] = "..."
        ENV["XCODE_VERSION"] = "8.3.3"
        ENV["CRASHLYTICS_API_TOKEN"] = "..."
        ENV["CRASHLYTICS_BUILD_SECRET"] = "..."
        # cocoapods

    end


    lane :upload do

        clean_build_artifacts
        clear_derived_data

        ensure_git_branch(
            branch: 'master'
        )
        ensure_xcode_version(version: ENV["XCODE_VERSION"] )

        cert
        sigh(
            app_identifier:'com.valera.valera'
        )
        gym(
            scheme: 'Quest',
            configuration: 'Release',
            clean: true,
            export_method: 'app-store',
            output_name: 'Valera'
        )

        testflight(
            app_identifier: "com.valera.valera"
        )

        version = get_version_number

        git_add(path: ".")
        git_commit(path: ".", message: "fastlane")

        push_to_git_remote(
            remote: "origin",
            local_branch: "master",
            remote_branch: "master"
        )

        add_git_tag(
            tag: "#{version}"
        )

        push_to_git_remote(
            remote: "origin",
            local_branch: "master",
            remote_branch: "master"
        )

    end
#
# Learn more here: https://github.com/fastlane/setups/blob/master/samples-ios/distribute-beta-build.md 🚀
#
    lane :beta_production do |values|

        clean_build_artifacts
        clear_derived_data

#ensure_git_branch(
#            branch: 'master'
#        )
        ensure_xcode_version(version: ENV["XCODE_VERSION"] )

        cert
        sigh(
            force:true,
            adhoc: true,
            app_identifier:'com.valera.valera'
        )
        gym(
            scheme: 'Quest',
            configuration: 'Release',
            clean: true,
            export_method: 'ad-hoc',
            output_name: 'Valera'
        )

        emails = values[:test_email] ? values[:test_email] : ['ilandbt@gmail.com'] # You can list more emails here
        groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

        crashlytics(
            api_token: ENV["CRASHLYTICS_API_TOKEN"],
            build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
            debug: false,
            emails: emails,
            groups: groups,
            notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true
        )

        version = get_version_number

        add_git_tag(
            tag: "#{version}"
        )
        git_add(path: ".")
        git_commit(path: ".", message: "fastlane")

        push_to_git_remote(
            remote: "origin",
            local_branch: "master",
            remote_branch: "master"
        )
    end


lane :beta_test do |values|

        groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here
        emails = values[:test_email] ? values[:test_email] : ['ilandbt@gmail.com'] # You can list more emails here
        incromentVersion = values[:version] ? values[:version] : false
        incromentBuild = values[:build] ? values[:build] : false
        crashlyticsNote = values[:note] ? values[:note] : "new test upload"

        clean_build_artifacts
        clear_derived_data

        ensure_git_branch(
            branch: 'dev'
        )
        ensure_xcode_version(version: ENV["XCODE_VERSION"] )

        if incromentBuild then
            increment_build_number
            git_commit(path: ".", message: "build Bump")

            push_to_git_remote(
                remote: "origin",
                local_branch: "dev",
                remote_branch: "dev"
            )
        end

        if incromentVersion then
            increment_version_number(bump_type: "patch")
            git_commit(path: ".", message: "Version Bump")

            push_to_git_remote(
                remote: "origin",
                local_branch: "dev",
                remote_branch: "dev"
            )
        end

        cert(
            development: true
        )
        sigh(
            development: true,
            app_identifier:'com.valera.valera-test'
        )
        gym(
            scheme: 'Quest-debug',
            configuration: 'Debug',
            clean: true,
            export_method: 'development',
            output_name: 'Valera-Test'
        )

        crashlytics(
            api_token: ENV["CRASHLYTICS_API_TOKEN"],
            build_secret: ENV["CRASHLYTICS_BUILD_SECRET"],
            emails: emails,
            groups: groups,
            notes: "#{crashlyticsNote}",
            notifications: true
        )


        build = get_build_number
        version = get_version_number

        slack(
            message: "Successfully deployed new test app: #{crashlyticsNote}",
            payload: {
                "Platform" => "IOS",
                "Version" => "#{version}",
                "Build" => "#{build}",
            },
            default_payloads: []
        )
    end

lane :build do
    increment_build_number
    git_commit(path: ".", message: "build Bump")
    
    push_to_git_remote(
                       remote: "origin",
                       local_branch: "dev",
                       remote_branch: "dev"
                       )
    end

    after_all do |lane|
        # This block is called, only if the executed lane was successful

        # slack(
        #   message: "Successfully deployed new App Update."
        # )
    end

    error do |lane, exception|
        slack(
            message: exception.message,
            success: false
        )
    end
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.valera.valera" # The bundle identifier of your app
apple_id "rdteam@valerahealth.com" # Your Apple email address

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.6        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 0.2.6        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcode-install             | 2.1.1        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-07-02**
</details>

**Comment by KrauseFx** [comment]
Thanks for reporting this. Looking at the output
```
INFO [2017-07-02 15:07:30.16]: ------------------------------------
INFO [2017-07-02 15:07:30.16]: --- Step: increment_build_number ---
INFO [2017-07-02 15:07:30.16]: ------------------------------------
INFO [2017-07-02 15:07:30.83]: $ cd /Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest && agvtool next-version -all && cd -
INFO [2017-07-02 15:07:31.44]: ▸ Setting version of project Quest to:
INFO [2017-07-02 15:07:31.44]: ▸ 59.
INFO [2017-07-02 15:07:31.48]: ▸ Also setting CFBundleVersion key (assuming it exists)
INFO [2017-07-02 15:07:31.51]: ▸ Updating CFBundleVersion in Info.plist(s)...
INFO [2017-07-02 15:07:31.52]: ▸ $(SRCROOT)/Targets/Quest-Test/Quest-Test-Info.plist
INFO [2017-07-02 15:07:31.53]: ▸ Cannot find "$(SRCROOT)/Targets/Quest-Test/Quest-Test-Info.plist"
INFO [2017-07-02 15:07:31.53]: ▸ $(SRCROOT)/Targets/Quest/Info.plist
INFO [2017-07-02 15:07:31.53]: ▸ Cannot find "$(SRCROOT)/Targets/Quest/Info.plist"
INFO [2017-07-02 15:07:31.54]: ▸ Updated CFBundleVersion in "Quest.xcodeproj/../QuestTests/Info.plist" to 59
INFO [2017-07-02 15:07:31.56]: ▸ Updated CFBundleVersion in "Quest.xcodeproj/../QuestUITests/Info.plist" to 59
INFO [2017-07-02 15:07:31.56]: ▸ /Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest
```
it seems like it modifies the Info.plist of your tests only. You can also see the command _fastlane_ is using: 

```
cd /Users/ilandbt/Documents/Projects/IOSProjects/QuestApp/Quest && agvtool next-version -all 
```

There can be various reasons on why it doesn't work for your project. Make sure you follow the [Apple guide](https://developer.apple.com/library/ios/qa/qa1827/_index.html) for your project, also you can specify the Xcode project to use using the `xcodeproj` parameter 👍 

Let me know if that works

**Comment by ilandbt** [comment]
Thanks @KrauseFx .
How can i see whats the $(SRCROOT) value?

**Comment by ilandbt** [comment]
Found the problem.

I gave a full path to my `info.plist` in the `Build settings` instead of a relative one.
I needed to remove the `$(SRCROOT)/`.

Thanks again
