### ISSUE TITLE
[Question]What the IAP tier string about the standby tier ?

### ISSUE THREAD

**Issue by ShelinShelin** [fastlane/fastlane#9658]
### New Issue Checklist

- ✅Updated fastlane to the latest version
- ✅ I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

#### Hi, what the tier string about the standby tier, such as CNY6 is tier 1, CNY12 is tier 2.  And what about CNY8? CNY8 is standby tier, and what is the difference between tier 1 and standby tier 1?

```
edit_purchase.pricing_intervals = [
{
     country: "WW",
      begin_date: nil,
      end_date: nil,
      tier: 2
}
]
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

```
lane :deliver_new do |options|
    deliver(
      app_version: options[:version],
      release_notes: {
      'zh-Hans' => options[:releaseNotes]
    },
      edit_live:false,
      force: true,
      app_identifier: options[:bundleId],
      price_tier: 0,
      automatic_release: false,
      description:{
  		'zh-Hans' => options[:desc]
		},
	    name:{
      'zh-Hans' => options[:name]
    },
      support_url:{
      'zh-Hans' => options[:supportUrl]
    },
      privacy_url:{
      'zh-Hans' => options[:privacyUrl]
    },
      keywords:{
      "zh-Hans" => options[:keyword]
    },
      app_icon: options[:iconPath],
      copyright: options[:copyRight],
      primary_category: options[:primaryCategory],
      app_review_information:{
        first_name: options[:firstName],
        last_name: options[:lastName],
        phone_number: options[:phoneNumber],
        email_address: options[:emailAddress],
        demo_user: options[:demoUser],
        demo_password: options[:demoPassword],
        notes: options[:notes]
    },
      app_rating_config_path: options[:rateConfigPath],
	    screenshots_path: options[:screenshotsPath]
      )
  end


```

**Comment by KrauseFx** [comment]
Sorry @ShelinShelin, I actually don't know, maybe @hjanuschka knows more, but he's currently on parental leave. You might be able to find out more by looking at how the iTunes Connect page handles things.

**Comment by ShelinShelin** [comment]
@KrauseFx   Thank you for your reply, I will be waiting for  @hjanuschka  reply，and try find out by  iTunes Connect!

**Comment by ShelinShelin** [comment]
hi,  @hjanuschka, I try find out by iTunes Connect, but no progress, I hope you can give some help, thanks!
