### ISSUE TITLE
Crash when uploading trailers

### ISSUE THREAD

**Issue by matteomartinelli** [fastlane/fastlane#9660]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
As requested by @taquitos [here](https://github.com/fastlane/fastlane/issues/9532) I open the issue regarding the errors when uploading trailers.
```
undefined local variable or method `is_messages' for #<Spaceship::Tunes::AppVersion:0x007f9130524e50>
/Users/matteomartinelli/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/fastlane-2.38.1/spaceship/lib/spaceship/tunes/app_version.rb:541:in `upload_trailer!'
/Users/matteomartinelli/fastlane-test/lib/app_metadata.rb:239:in `block (2 levels) in upload'
/Users/matteomartinelli/fastlane-test/lib/app_metadata.rb:228:in `each'
/Users/matteomartinelli/fastlane-test/lib/app_metadata.rb:228:in `block in upload'
/Users/matteomartinelli/fastlane-test/lib/app_metadata.rb:181:in `each'
/Users/matteomartinelli/fastlane-test/lib/app_metadata.rb:181:in `upload'
/Users/matteomartinelli/fastlane-test/lib/app_metadata.rb:77:in `block in upload_metadata'
/Users/matteomartinelli/.rbenv/versions/2.2.1/lib/ruby/2.2.0/tmpdir.rb:88:in `mktmpdir'
/Users/matteomartinelli/fastlane-test/lib/app_metadata.rb:66:in `upload_metadata'
/Users/matteomartinelli/fastlane-test/apis/metadata.rb:34:in `block (2 levels) in <class:Bunker>'
/Users/matteomartinelli/fastlane-test/lib/background_runner.rb:39:in `call'
/Users/matteomartinelli/fastlane-test/lib/background_runner.rb:39:in `block in execute'
```

Finding:
### app_version.rb
 - `upload_trailer!` doc is not correct, it's a copy&paste from `upload_screenshot!`
 - When `upload_trailer!` is called, it crashes because fastlane try to use a parameter which does not even exist in the aforementioned function.
 - When `trailer_data_for_language_and_device` is called, it looks the correct `data_field` is `trailers` and not `appTrailers`
 - I guess now we should add `sort_position` since trailers can be more than 1
### du_client.rb
 - When uploading the screenshot preview (`upload_trailer_preview`, it crashes because `du_validation_rule_set` it was not set correctly.
```
      upload_file(app_version: app_version, upload_file: upload_file, path: '/upload/image', content_provider_id: content_provider_id, sso_token: sso_token_for_image, du_validation_rule_set: 'MZPFT.SortedN56ScreenShot')
```
### app_trailer.rb
This entity need an update to support at least `sortPosition`.

Hope it's clear :D

**Comment by KrauseFx** [comment]
Thanks for reporting this. I think this broke with the most recent update of iTunes Connect, which changes iTC to handle 3 instead of 1 trailer. Do you have Ruby knowledge and want to dive into updating _spaceship_ to support multiple trailers?

**Comment by matteomartinelli** [comment]
Exactly!

Not really, I posted above my findings and I will try to make a PR to help the community 👍

**Comment by KrauseFx** [comment]
Okay, cool, let me know if you have any questions 👍 We have some nice docs on how to inspect network traffic in the root of the project

**Comment by pedrodelavega** [comment]
Really need this ! With localized previews, it is a real nightmare to upload previews. You can have 6 app previews per locale and you can't count on iTunes Connect to allow you to share app previews between locale. So if you add some localized screenshot, you also have to add previews . I will look at the code even if I know nothing about Ruby.

**Comment by ima747** [comment]
Any update on this?

**Comment by ima747** [comment]
Bump to keep alive. This is still needed badly for managing app store localized resources under iOS 11 especially.

**Comment by tsheaff** [comment]
@matteomartinelli what's the syntax to use for this to work?

**Comment by pedrodelavega** [comment]
@tsheaff you may check the post of the end of [#9775](https://github.com/fastlane/fastlane/issues/9775)

**Comment by tsheaff** [comment]
Yeah I saw that after commenting, thanks @pedrodelavega 

Would be nice to add this into deliver rather than just `Spaceship`
