### ISSUE TITLE
GRADLE_ALL_APK_OUTPUT_PATHS is empty when use Android Gradle flavours with dimensions

### ISSUE THREAD

**Issue by mitrofany4** [fastlane/fastlane#9661]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

GRADLE_ALL_APK_OUTPUT_PATHS is empty when use Android Gradle flavours with dimensions. It happens because fastlane only search at the ./app/build/outputs/apk folder.
```
flavorDimensions "icon", "api"
    productFlavors {
        dev {
            dimension "api"
            applicationIdSuffix '.testing'
        }

        uat {
            dimension "api"
            applicationIdSuffix '.uat'
        }

        prod {
            dimension "api"
        }

        black {
            dimension "icon"
        }

        white {
            dimension "icon"
        }
    }
```
It happens because fastlane only search at the ./app/build/outputs/apk folder.
But should search at subfolders too. For example,
./app/build/outputs/apk/whiteDev/release
./app/build/outputs/apk/whiteProd/release
etc.

-----------------------------+-----------------+
|                 Lane Context                  |
+-----------------------------+-----------------+
| DEFAULT_PLATFORM            | android         |
| PLATFORM_NAME               | android         |
| LANE_NAME                   | android betaUAT |
| GRADLE_ALL_APK_OUTPUT_PATHS | []              |
+-----------------------------+-----------------+
[18:20:57]: You have to either pass an ipa or an apk file to the Crashlytics action

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | update_fastlane     | 10          |
| 2    | Verifying required  | 0           |
|      | fastlane version    |             |
| 3    | default_platform    | 0           |
| 4    | slack               | 0           |
| 5    | git_pull            | 1           |
| 6    | gradle              | 37          |
| 7    | is_ci               | 0           |
| 💥   | crashlytics         | 0           |
| 9    | slack               | 0           |
+------+---------------------+-------------+

[18:20:57]: fastlane finished with errors

[!] You have to either pass an ipa or an apk file to the Crashlytics action

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13                                |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.8.1                    |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.13 (17A291m)             |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | true                                 |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane(nightly:false)

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.37.0"

default_platform :android

platform :android do
  before_all do
    slack(
      message: "Start deploying..."
    )
    git_pull(only_tags: true)
  end

  desc "Generate release notes"
  def release_notes
      return "Test"
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit all flavours to Crashlytics Beta & to the Google Play"
  lane :deployAll do |options|
    clean
    betaTesting
     betaUAT
     betaProd
  end

  desc "Clean all"
  lane :clean do
    gradle(task: "clean")
  end

  desc "Generate Lint report"
  lane :lint do
    gradle(task: "lintBlackProdRelease")
  end

  desc "Submit Testing builds to Crashlytics Beta"
  lane :betaTesting do
    gradle(task: "assembleWhiteDevRelease")
    # Generate the changelog based on commit messages since your last succesful commit
    release_notes
    # The crashlytics action knows how to use the generated changelog automatically
    crashlytics(groups: 'android-team, qa-team')
    notify_build_success
  end

  desc "Submit UAT builds to Crashlytics Beta"
  lane :betaUAT do
    gradle(task: "assembleWhiteUatRelease")
    # Generate the changelog based on commit messages since your last succesful commit
    release_notes
    # The crashlytics action knows how to use the generated changelog automatically
    crashlytics(groups: 'android-team, qa-team')
    notify_build_success
  end

  desc "Submit Prod builds to Crashlytics Beta"
  lane :betaProd do
    gradle(task: "assembleWhiteProdRelease")
    # Generate the changelog based on commit messages since your last succesful commit
    release_notes
    # The crashlytics action knows how to use the generated changelog automatically
    crashlytics(groups: 'android-team, qa-team')
    notify_build_success
  end

  desc "Deploy a new version to the Google Play"
  lane :deployGooglePlay do
    # Deploy to Google Play only from branches Master or Release
    ensure_git_branch(
      branch: "(master|release\\S+)"
    )
    gradle(task: "assembleBlackProdRelease")
    supply(
      track: 'alpha',
      skip_upload_metadata: true,
      skip_upload_images:true,
      skip_upload_screenshots:true,
      apk: "./app/build/outputs/apk/blackProd/release/app-black-prod-release.apk",
      mapping: "./app/build/outputs/mapping/blackProd/release/mapping.txt"
    )
    notify_build_success
  end

  desc "Assemble debug build for merge requests"
  private_lane :assembleMergeRequestBuild do
    gradle(task: "assembleWhiteDevDebug assembleWhiteDevRelease")
    slack(
      message: "Assemble debug build for merge request."
    )
  end

  # You can define as many lanes as you want

  def notify_build_success
    get_android_version(apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH])
    version_code = lane_context[SharedValues::GET_ANDROID_VERSION_CODE]
    version_name = lane_context[SharedValues::GET_ANDROID_VERSION_NAME]
    app_name = lane_context[SharedValues::GET_ANDROID_VERSION_APP_NAME]
    slack(
      message: "Successfully deployed #{app_name} app build #{version_code} (#{version_name})"
    )
  end

  after_all do |lane, options|
    if options[:isMergeRequest]
      # do something for merge request
    else
      add_git_tag(
        build_number: lane_context[SharedValues::GET_ANDROID_VERSION_CODE],
        force: true
      )
      push_git_tags
      # This block is called, only if the executed lane was successful
      slack(
        message: "Successfully deployed new App Update."
      )
    end
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "./Google Play Android Developer-bdb705f687eb.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one

for_lane 'betaTesting' do
  package_name "com.test.white.testing"
end

for_lane 'betaUAT' do
  package_name "com.test.white.uat"
end

for_lane 'betaProd' do
  package_name "com.test.white.prod"
end

for_lane 'deployGooglePlay' do
  package_name "com.test"
end

package_name "com.test"
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                              | Version | Update-Status |
| ----------------------------------- | ------- | ------------- |
| fastlane-plugin-get_android_version | 0.3.5   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                                 | Version      |
| ----------------------------------- | ------------ |
| CFPropertyList                      | 2.3.5        |
| addressable                         | 2.5.1        |
| apktools                            | 0.7.2        |
| babosa                              | 1.0.2        |
| bigdecimal                          | 1.2.6        |
| bundler                             | 1.14.6       |
| claide                              | 1.0.2        |
| colored                             | 1.2          |
| colored2                            | 3.1.2        |
| commander-fastlane                  | 4.4.5        |
| commander-fastlane                  | 4.4.4        |
| declarative                         | 0.0.9        |
| declarative-option                  | 0.1.0        |
| domain_name                         | 0.5.20170404 |
| dotenv                              | 2.2.1        |
| excon                               | 0.57.0       |
| excon                               | 0.56.0       |
| faraday                             | 0.12.1       |
| faraday-cookie_jar                  | 0.0.6        |
| faraday_middleware                  | 0.11.0.1     |
| fastimage                           | 2.1.0        |
| fastlane-plugin-get_android_version | 0.3.5        |
| gh_inspector                        | 1.0.3        |
| google-api-client                   | 0.12.0       |
| googleauth                          | 0.5.1        |
| highline                            | 1.7.8        |
| http-cookie                         | 1.0.3        |
| httpclient                          | 2.8.3        |
| hurley                              | 0.2          |
| io-console                          | 0.4.3        |
| json                                | 1.8.1        |
| jwt                                 | 1.5.6        |
| libxml-ruby                         | 3.0.0        |
| little-plugger                      | 1.1.4        |
| logging                             | 2.2.2        |
| memoist                             | 0.15.0       |
| mime-types                          | 3.1          |
| mime-types-data                     | 3.2016.0521  |
| mini_magick                         | 4.5.1        |
| minitest                            | 5.4.3        |
| multi_json                          | 1.12.1       |
| multi_xml                           | 0.6.0        |
| multipart-post                      | 2.0.0        |
| nanaimo                             | 0.2.3        |
| nokogiri                            | 1.5.6        |
| os                                  | 0.9.6        |
| plist                               | 3.3.0        |
| power_assert                        | 0.2.2        |
| psych                               | 2.0.8        |
| public_suffix                       | 2.0.5        |
| rake                                | 10.4.2       |
| rdoc                                | 4.2.0        |
| representable                       | 3.0.4        |
| retriable                           | 3.0.2        |
| retriable                           | 2.1.0        |
| rouge                               | 2.0.7        |
| rouge                               | 1.11.1       |
| rubygems-update                     | 2.5.2        |
| rubyzip                             | 1.2.1        |
| security                            | 0.1.3        |
| signet                              | 0.7.3        |
| slack-notifier                      | 1.5.1        |
| sqlite3                             | 1.3.13       |
| terminal-notifier                   | 1.8.0        |
| terminal-table                      | 1.7.3        |
| test-unit                           | 3.0.8        |
| tty-screen                          | 0.5.0        |
| uber                                | 0.1.0        |
| uber                                | 0.0.15       |
| unf                                 | 0.1.4        |
| unf_ext                             | 0.0.7.4      |
| unicode-display_width               | 1.3.0        |
| unicode-display_width               | 1.2.1        |
| unicode-display_width               | 1.1.3        |
| word_wrap                           | 1.0.0        |
| xcodeproj                           | 1.4.4        |
| xcpretty                            | 0.2.6        |
| xcpretty-travis-formatter           | 0.0.4        |
</details>

*generated on:* **2017-07-03**
</details>

**Comment by KrauseFx** [comment]
Awesome, thanks for the detailed report. I just prepared https://github.com/fastlane/fastlane/pull/9688, let me know if that change is what you're expecting, and if it's ready to be merged and released :)
