### ISSUE TITLE
Unable to fetch build number from TestFlight 

### ISSUE THREAD

**Issue by bonkey** [fastlane/fastlane#9662]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm refering to: https://github.com/fastlane/fastlane/blob/2.44.1/fastlane/lib/fastlane/actions/app_store_build_number.rb#L38

For readability, pasted:

```ruby
  UI.message("Fetching the latest build number for version #{version_number}")

  begin
    train = app.build_trains[version_number] # 1
    build_nr = train.builds.map(&:build_version).map(&:to_i).sort.last # 2
  rescue
    UI.user_error!("could not find a build on iTC - and 'initial_build_number' option is not set") unless params[:initial_build_number] # 3
    build_nr = params[:initial_build_number]
  end
```

I found 2 issues:

1. Main: _Fetching the latest build number for version_ step does not return correct build number even when they're (screenshot)
2. Side: _could not find a build on iTC - and 'initial_build_number' option is not set_ is never called, because `:initial_build_number` is always present.

Exception which is raised at this point is `undefined method 'builds' for nil:NilClass`, because `train` from `#1` is nil, as `app.build_trains` is empty (`{}`).

![build-3 1 1](https://user-images.githubusercontent.com/39100/27799244-b9b8b91c-6014-11e7-8bbe-70f01cb93aeb.png)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `tfv`
<details><summary>Output/Log</summary>

```

INFO [2017-07-03 16:48:58.33]: Successfully loaded custom action '/REDACTED/Current-iOS/fastlane/actions/carthage_nimble.rb'.
INFO [2017-07-03 16:48:58.33]: Successfully loaded custom action '/REDACTED/Current-iOS/fastlane/actions/push_git_tags.rb'.
INFO [2017-07-03 16:48:58.33]: Successfully loaded custom action '/REDACTED/Current-iOS/fastlane/actions/reset_simulators.rb'.
DEBUG [2017-07-03 16:48:58.33]: Checking if there are any plugins that should be loaded...
INFO [2017-07-03 16:48:58.34]: -------------------------------------------------
INFO [2017-07-03 16:48:58.34]: --- Step: Verifying required fastlane version ---
INFO [2017-07-03 16:48:58.34]: -------------------------------------------------
INFO [2017-07-03 16:48:58.34]: Your fastlane version 2.44.1 matches the minimum requirement of 1.66.0  ✅
INFO [2017-07-03 16:48:58.35]: --------------------------------
INFO [2017-07-03 16:48:58.35]: --- Step: get_version_number ---
INFO [2017-07-03 16:48:58.35]: --------------------------------
INFO [2017-07-03 16:48:58.35]: $ cd /REDACTED/Current-iOS && agvtool what-marketing-version -terse
INFO [2017-07-03 16:48:59.12]: ▸ "SomeApp.xcodeproj/../TodayExtension/Info.plist"=3.1.1
INFO [2017-07-03 16:48:59.13]: ▸ "SomeApp.xcodeproj/../TodayExtensionHelper/Info.plist"=1.0
INFO [2017-07-03 16:48:59.15]: ▸ "SomeApp.xcodeproj/../TodayExtensionHelperTests/Info.plist"=1.0
INFO [2017-07-03 16:48:59.16]: ▸ "SomeApp.xcodeproj/../SomeApp/Info.plist"=3.1.1
INFO [2017-07-03 16:48:59.17]: ▸ "SomeApp.xcodeproj/../SomeAppPerformanceTests/Info.plist"=1.0
INFO [2017-07-03 16:48:59.18]: ▸ "SomeApp.xcodeproj/../SomeAppTests/Info.plist"=1.0
INFO [2017-07-03 16:48:59.20]: ▸ "SomeApp.xcodeproj/../SomeAppUI/Info.plist"=1.0
INFO [2017-07-03 16:48:59.21]: ▸ "SomeApp.xcodeproj/../SomeAppUITests/Info.plist"=1.0
INFO [2017-07-03 16:48:59.21]: ------------------------------
INFO [2017-07-03 16:48:59.21]: --- Step: default_platform ---
INFO [2017-07-03 16:48:59.21]: ------------------------------
INFO [2017-07-03 16:48:59.21]: Driving the lane 'ios tfv' 🚀
INFO [2017-07-03 16:48:59.21]: --------------------------------------------
INFO [2017-07-03 16:48:59.21]: --- Step: latest_testflight_build_number ---
INFO [2017-07-03 16:48:59.21]: --------------------------------------------
Successfully loaded Appfile at path '/REDACTED/Current-iOS/fastlane/Appfile'
- app_identifier: 'REDACTED'
- apple_id: 'REDACTED'
- team_id: 'REDACTED'
-------
INFO [2017-07-03 16:48:59.22]: Login to iTunes Connect (REDACTED)
Looking for iTunes Connect Team with ID REDACTED
INFO [2017-07-03 16:49:03.12]: Login successful
INFO [2017-07-03 16:49:04.47]: Fetching the latest build number for version 3.1.1
INFO [2017-07-03 16:49:07.66]: Latest upload is build number: 1
INFO [2017-07-03 16:49:07.66]: Successfully generated documentation at path '/REDACTED/Current-iOS/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | get_version_number     | 0           |
| 3    | default_platform       | 0           |
| 4    | latest_testflight_bui  | 8           |
|      | ld_number              |             |
+------+------------------------+-------------+

INFO [2017-07-03 16:49:07.68]: fastlane.tools finished successfully 🎉


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.13.2                          |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# Update this, if you use features of a newer version
fastlane_version "1.66.0"

$XCODEPROJ = "SomeApp.xcodeproj"
$TARGET = "SomeApp"
$SCHEME = $TARGET
$VERSION = get_version_number(xcodeproj: $XCODEPROJ, target: $TARGET)

default_platform :ios

private_lane :appstore_upload do
  %x{export DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"}
  deliver(skip_metadata: true)
end

private_lane :testflight_upload do |options|
  %x{export DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"}
  pilot(username: "REDACTED", skip_submission: options[:skip_submission], skip_waiting_for_build_processing: true)
end

private_lane :finalize do
  add_git_tag(prefix: "#$VERSION/")
  push_git_tags

  clean_build_artifacts
end

error do |lane, exception|
  slack(
    message: exception.message,
    success: false
  )
end

private_lane :test_with_coverage do |options|
  scheme = options[:scheme] || $SCHEME
  scan(options)

  slather(
    scheme: scheme,
	proj: $XCODEPROJ,
	cobertura_xml: true,
	output_directory: 'slather-reports/' + scheme,
	ignore: [
		"SomeApp/libs/*",
		"**/*/Xcode*",
		"Carthage/*",
    		"DataLayer/DataLayer/Model/*"
	]
  )
end

desc "Runs danger to lint Pull Requests"
lane :danger_lane do
  danger(github_api_token: 'REDACTED')
end

platform :ios do
  before_all do
    ENV["SLACK_URL"] = "https://hooks.slack.com/services/REDACTED"
    ENV["MATCH_PASSWORD"] = "REDACTED"
  end

  private_lane :carthage_bootstrap do
    carthage(
      platform: "iOS"
    )

    # Workaround to get Nimble in the latest version which solves a problem with Xcode 7.3
    carthage_nimble
  end

desc "Prepares the project by rebuilding all carthage dependencies and getting the project's build number ready"
  lane :prepare do
    clear_derived_data
    # carthage_bootstrap
    increment_build_number({
      build_number: latest_testflight_build_number(version: $VERSION, initial_build_number: 0) + 1,
    })
  end

  desc "test"
  lane :tfv do
    latest_testflight_build_number(version: $VERSION, initial_build_number: nil)
  end

  desc "Runs all the tests"
  lane :test do
    prepare
    reset_simulators

    test_with_coverage(scheme: $SCHEME)
  end

  desc "Lints the codebase"
  lane :lint do
    sh("swiftlint lint --reporter checkstyle > ../swiftlint.checkstyle")
  end

  desc "Builds and archives the project"
  lane :build_only do
    prepare
    match(app_identifier: ["REDACTED", "REDACTED.todayextension"], type: "development")

    gym
  end

  desc "Submits a new Beta Build to QA"
  lane :beta do
    prepare
    match(app_identifier: ["REDACTED", "REDACTED.todayextension"], type: "appstore")

	gym(
      xcconfig: "config/Debug.xcconfig"
    )

    begin
      branch = sh("git log --pretty=oneline | head -n 100")
      story = branch[/.*\/([^\_]*)/,1]
      url = "https://REDACTED/browse/" + story
      title = story + " pushed to TestFlight"
      message = "Version: #$VERSION\nBuild: #{get_build_number}"
    rescue
      message = "Even though there was an error while parsing the ticket number, the build was uploaded to TestFlight"
      title = ''
      url = ''
    end

    testflight_upload(skip_submission: true)
    finalize

    slack(
      message: message,
      attachment_properties: {
        title: title,
        title_link: url
      },
      success: true
  	)
  end

  desc "Submits a new Beta Build to external testers"
  lane :external do
    prepare
    match(app_identifier: ["REDACTED", "REDACTED.todayextension"], type: "appstore")

    gym(
      xcconfig: "config/External.xcconfig", # Load extra flags from xcconfig for external builds
    )

    testflight_upload(skip_submission: true)
    finalize

    slack(
      message: "External testers build pushed to Testflight.",
      success: true
    )
  end

  desc "Deploys a new version to the App Store"
  lane :production do
    prepare
    match(app_identifier: ["REDACTED", "REDACTED.todayextension"], type: "appstore")

    gym

    appstore_upload
    finalize

    slack(
      message: "AppStore build pushed to Apple.",
      success: true
    )
  end

  desc "Downloads all dSYM files from iTC and uploads them to Crashlytics"
  lane :refresh_dsyms do
    download_dsyms                  # Download dSYM files from iTC
    upload_symbols_to_crashlytics(api_token: "REDACTED")   # Upload them to Crashlytics
    clean_build_artifacts           # Delete the local dSYM files
    
    slack(
      message: "Successfully uploaded all dSYM files from iTunes Connect into Crashlytics",
      success: true
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "REDACTED" # The bundle identifier of your app
apple_id "REDACTED" # Your Apple email address

team_id "REDACTED"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.6        |
| rake                      | 12.0.0       |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| i18n                      | 0.8.4        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.9        |
| clamp                     | 0.6.5        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| slather                   | 2.4.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.14.0       |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| danger                    | 5.3.2        |
| thor                      | 0.19.4       |
| danger-swiftlint          | 0.5.1        |
</details>

*generated on:* **2017-07-03**
</details>

**Comment by KrauseFx** [comment]
Hey @bonkey, thanks for the report. Do you know how this can be fixed? Is that something you could prepare a pull request for? :)

**Comment by bonkey** [comment]
Hi @KrauseFx, I thought so, but didn't manage to get that deep to get clues. And recently we changed build numbering scheme, so we're not using `latest_testflight_build_number` anymore. So, probably I won't be able to touch it soon, sorry.

**Comment by KrauseFx** [comment]
Okay, thanks for the update 👍

**Comment by jsugg** [comment]
Hi @KrauseFx, exactly the same thing happening here. I tried to figure out where the problem was, with no luck. Were you able to find something?

**Comment by ohayon** [comment]
Hey @bonkey and @jsugg - I am trying to reproduce this locally with one of my own projects and everything is working as expected for me 😕 . @jsugg would you mind sharing a bit more information about your issue? What is the action returning for you? What should it be returning? And how are you calling it? Also, if you wouldnt mind sharing the output of `fastlane env` with us as well that would be 💯  to get some more context about whats going wrong. Thanks!! 🐙  😄

**Comment by jsugg** [comment]
Hi @ohayon , sure! It returns the same thing it's returning for @bonkey . train = app.build_trains[version_number] is returning nil.
