### ISSUE TITLE
Cannot update 

### ISSUE THREAD

**Issue by MarcSteven** [fastlane/fastlane#9666]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I wanna  update the latest version ,my version is 2.18.2
##### Complete output when running fastlane, including the stack trace and command used

[INSERT OUTPUT HERE]
Updating installed gems
Nothing to update
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by MarcSteven** [comment]
Great,but I think if you can offer some tutorials to do it ,that's great .Thank you so much

**Comment by KrauseFx** [comment]
Did you figure it out? You can use `fastlane update_fastlane` to update 👍
