### ISSUE TITLE
[precheck] : Failed: Incorrect, or missing copyright date

### ISSUE THREAD

**Issue by wiremax** [fastlane/fastlane#9668]
![image](https://user-images.githubusercontent.com/9081351/27834912-067e15dc-6103-11e7-8475-e287fdb71c12.png)

Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date

**Comment by wiremax** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.4                                           |
| Ruby                        | 2.4.1                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.10.1 (Apple Git-78)                 |
| Installation Source         | /usr/local/bin/fastlane                           |
| Host                        | Mac OS X 10.12.4 (16E195)                         |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode 8.2.1.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                             |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.2.1        |
| terminal-table            | 1.8.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
| plist                     | 3.3.0        |
</details>


*generated on:* **2017-07-04**
</details>

**Comment by KrauseFx** [comment]
Nice 👍  Seems like you don't have 2017 in the copyright year. Why did you submit this issue? Would you expect precheck to do something else? It shouldn't have failed the build to my knowledge

**Comment by abhinandankothari** [comment]
Exact Same issue , Where do i set copyright year ? Which file - fastfile ? 

```
INFO [2017-07-06 16:47:59.13]: Successfully logged in
INFO [2017-07-06 16:47:59.13]: Checking app for precheck rule violations
INFO [2017-07-06 16:48:40.43]: :white_check_mark:  Passed: No negative  sentiment
INFO [2017-07-06 16:48:40.43]: :white_check_mark:  Passed: No placeholder text
INFO [2017-07-06 16:48:40.43]: :white_check_mark:  Passed: No mentioning  competitors
INFO [2017-07-06 16:48:40.43]: :white_check_mark:  Passed: No future functionality promises
INFO [2017-07-06 16:48:40.43]: :white_check_mark:  Passed: No words indicating test content
INFO [2017-07-06 16:48:40.44]: :white_check_mark:  Passed: No curse words
DEBUG [2017-07-06 16:48:40.44]: custom_text excluded because no data was passed to it e.g.: custom_text(data: <data here>)
DEBUG [2017-07-06 16:48:40.44]: :sob:  CopyrightDateRule didn't find words "2017"
ERROR [2017-07-06 16:48:40.44]: :dizzy_face:  Failed: Incorrect, or missing copyright date-> using a copyright date that is any different from this current year, or missing a date
INFO [2017-07-06 16:48:51.15]: :white_check_mark:  Passed: No broken urls
```

Currently I am bypassing  this by setting

`copyright_date(level: :skip)` in `fastlane/Precheckfile` file.

**Comment by KrauseFx** [comment]
The copyright date is part of the copyright text field you enter on iTunes Connect, you can change it using _fastlane deliver_ also if you want, but you can also set it directly on iTunes Connect. How can we change the output to clarify that better? :)

**Comment by muescha** [comment]
for error message it would be nice to see the current value (eq `2016`) if there is any available

**Comment by taquitos** [comment]
The copyright field generally contains the date along with copyright text. We were trying to keep the output as small but relevant. Logging the entire text of most text fields would be overkill, but maybe we should log the text for the copyright field since it's really just 1 line. What you'd probably see is something like "2016, Company Name"

**Comment by muescha** [comment]
thats right not the entire text, maybe only the match and +/- some words around

**Comment by taquitos** [comment]
That's tough though, we only look for the current year within the whole string, so printing would need to be an all or "we didn't find <current year>"

**Comment by ed-mejia** [comment]
Hi there!

Why it forces the date to be the actual year?

The actual documentation on iTunesConnect for that field states:

> The name of the person or entity that owns the exclusive rights to your app, **preceded by the year the rights were obtained** (for example, "2008 Acme Inc."). Do not provide a URL.

So it seems valid to put 2008 as a year on that field.

I'm missing something?

**Comment by taquitos** [comment]
Hey @ed-mejia, we've had reports from developers who do white-label apps that having a copyright year different from the current year has caused some app reviewers to spend a little extra time inspecting their apps, and raising other concerns. It won't cause a failure, but anything that causes app reviewers to spend more time reviewing is something we want to avoid 👍 
If this is a problem for you, you can definitely disable this rule.
