### ISSUE TITLE
Unable to install on macOS Sierra via homebrew

### ISSUE THREAD

**Issue by passt0r** [fastlane/fastlane#9670]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

I'd try to install fastlane by homebrew several times, but I always have a same problem with .bash_profile file. I'd try to reinstall fastlane and delete all files that was downloaded, but it does not help me. Also, updating .bash_profile does not help too. I always get the same terminal output: 
Command used: `brew cask install fastlane`
`==> Couldn't detect shell config file (bash - ~/.bash_profile)`
`==> Please add the following line to your bash profile:`
`==> export PATH="$HOME/.fastlane/bin:$PATH" `
### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

MacBook-Pro-Dmitry:~ dmytropasinchuk$ fastlane env
-bash: fastlane: command not found

**Comment by KrauseFx** [comment]
I'm not sure how you set up your Mac's profiles and paths, but basically you have to add `$HOME/.fastlane/bin` to your list of paths to be sure to load fastlane. Alternatively you can always launch it directly using `~/.fastlane/bin/fastlane ...`
