### ISSUE TITLE
Sigh is not downloading iOS Team Provisioning Profiles

### ISSUE THREAD

**Issue by StatusReport** [fastlane/fastlane#9679]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `fastlane sigh download_dll` downloads all the profiles that are displayed in the "Certificates, Identifiers & Profiles" page, but not the hidden "iOS Team Provisioning Profile: *" profiles that are required when using automatic code signing, as Xcode searches for these specific profiles and fails without falling back to other provisioning profiles that are associated with the app ID.

Opening Xcode->Preferences->Accounts and pressing on "Download all Profiles" downloads the missing profiles and solves the issue.

Here's an example of such profile:
![image](https://user-images.githubusercontent.com/1927614/27899460-ff5923a6-6232-11e7-814d-6f77bd8d5332.png)

This profile is visible when Xcode fetches the provisioning profiles from the private API `https://developerservices2.apple.com/services/QH65B2/ios/listProvisioningProfiles.action?clientId=...`.

More info about team provisioning profiles can be found [here](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppStoreDistributionTutorial/CreatingYourTeamProvisioningProfile/CreatingYourTeamProvisioningProfile.html).

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.12.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.44.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.4        |
</details>

*generated on:* **2017-07-06**
</details>

**Comment by KrauseFx** [comment]
Hey @StatusReport, thanks for reporting this. With _fastlane_ we never touch any of the Xcode managed profiles, not even with `download_all`. This is because we don't want to interfere with whatever Xcode is doing. Do you think _sigh_ should also download these, at least when running `download_all`? Might be something that's rather straight forward to implement in _sigh_, if you're interested in contributing 👍

**Comment by StatusReport** [comment]
Hey @KrauseFx! I think that it makes sense to at least download these profiles as this is a read only operation. Enabling this will allow to use automatic code signing for archives/release builds as well, which will simplify the process of using fastlane.

From my investigation, Xcode is first building and signing the `xcarchive` with the "iOS Team Provisioning Profile", and then re-signs it when you export to .ipa with the best provisioning profile that matches, which is not one of the Xcode managed profiles.

I've taken a look and it seems that it should be indeed quite straightforward to implement. If you'll be willing to merge this, we will definitely be happy to contribute.

**Comment by KrauseFx** [comment]
Sounds great, let me know how it goes, and if you need any help 👍

**Comment by KrauseFx** [comment]
Yeah, it's something we'd merge, but only for `sigh download_all` 👍

**Comment by StatusReport** [comment]
Yes, the plan is to add it just for `download_all` with a flag, so it won't affect existing users. I guess that if this will solve code signing issues for people without any other downsides, we can enable it by default.

**Comment by KrauseFx** [comment]
That's awesome 👍

**Comment by koxon** [comment]
Sounds like a great idea. I believe it would solve my problem.
On my CI I need to manually upload the team provisioning profiles which is very cumbersome as I have dozens of targets.
This would allow complete automation.

Any updates or help needed to build this?

**Comment by reach123** [comment]
hello

**Comment by StatusReport** [comment]
@koxon we will get to it this week or the next one. I don't think that there's a lot of work involved since the entire business logic is already in place.

**Comment by koxon** [comment]
@StatusReport you think that will solve my problem?

I am doing automatic code signing on my project and when running on my CI (bitrise.io) it requires the Team provisioning profile for the target I'm building, which is apparently generated by Xcode during the build.

bitrise.io offers this tool: https://github.com/bitrise-tools/codesigndoc

This tool allows you to run a clean "archive" build and then exports all the provisioning profiles for the specified target. The Team provisioning profile is part of all the provisioning profiles files exported. 

So, is this profile dynamically generated during the "Clean Archive" build or can I download it somewhere? And, will sigh/match be able to download/generate this profile somehow?

**Comment by StatusReport** [comment]
@koxon as far as I understand, the provisioning profile is not generated by Xcode during the build. It's generated when you open a project that is not backed by an Xcode team provisioning profile, or if that profile needs to be repaired (for example, if you've added new entitlements to the project or if the profile expired).

This profile is stored like any other profile you have, but cannot be seen in the Certificates, Identifiers & Profiles page. After we provide a solution you'll be able to download the profiles using `sigh` and then Xcode will use that profile to automatically sign the archive.

Note that if the profile is invalid and you will not open Xcode to repair it, it will not be repaired by `sigh` (at least for now, as this profile is intended to be managed by Xcode). So a manual intervention will be required.

**Comment by koxon** [comment]
@StatusReport I exported all the profiles I have in my "Provisioning Profile" folder on my MAC but no luck. This team profile is not in this folder so the project doesn't build on the CI server. 

The only way I get it to work is by using the `codesigndoc` tool from bitrise.io, which performs a clean archive. From that, they manage to export all the profiles for my target. There, I see several profiles and one team profile for the selected scheme. When I put this team profile on my CI server, it works great. The other profiles are pulled by `match`, but this specific team profile is missing in match. and in sigh.

It looks like this profile is generated by xcode when using Automated Code Signing like you say. 
How will that profile be downloadable if it's local to xCode only?

This is all very confusing =]

thanks

**Comment by StatusReport** [comment]
@koxon Xcode uses an undocumented API to create, manage and download these profiles. This is not the same API used by the Certificates, Identifiers & Profiles page. Fastlane uses Xcode's API to fetch these profiles, so you'll be able to download the invisible ones as well using `sigh`.
