### ISSUE TITLE
Feature request: add ability to upload builds to Application Insights

### ISSUE THREAD

**Issue by pRizz** [fastlane/fastlane#968]
I would like the ability to automatically upload builds to Microsoft's Application Insights so that I can get symbolicated crash logs in Application Insights.

Here is their framework which may embedded in an iOS app:
https://github.com/Microsoft/ApplicationInsights-iOS/

Here is the link to the build uploader:
http://go.microsoft.com/fwlink/?linkid=533209&clcid=0x409

This upload works after performing an archive of an app.

As of now, I cannot find an API for uploading builds, other than from the upload tool. It is probably possible to automate it with Apple Scripts at the least.

**Comment by ohwutup** [comment]
Hey @pRizz Thanks for submitting this feature request! We would love to have some functionality like this! I am going to close this issue for now, mark it as a feature request and we will reopen it as soon as we get a chance to bite this off for a future release! If you would like to beat us to the punch, we would happily review a PR adding this feature! Thanks :+1:

**Comment by pRizz** [comment]
Hey @ohwutup There's been recent changes to App Inisghts, namely their deprecation of the framework in favor of HockeyApp, so I'm not sure this feature is worth the time any more. I would be ok scrapping this request.

From: https://github.com/Microsoft/ApplicationInsights-iOS
> 
>Version 1.0-beta.7 of the Application Insights for iOS SDK comes with two major changes:
>
>Crash Reporting and the API to send handled exceptions have been removed from the SDK. In addition, the Application Insights for iOS SDK is now deprecated.
>
>The reason for this is that HockeyApp is now our major offering for mobile and cross-plattform crash reporting, beta distribution and user feedback. We are focusing all our efforts on enhancing the HockeySDK and adding telemetry features to make HockeyApp the best platform to build awesome apps. We've launched HockeyApp Preseason so you can try all the new bits yourself, including User Metrics.
