### ISSUE TITLE
[Question] How to send a compilation from iTunes to external testers

### ISSUE THREAD

**Issue by Sulfkain** [fastlane/fastlane#9682]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
How can I pass by param to pilot a compilation already submited to internal tester (with pilot) to external testers.
Doing manually I can select this compilation (version+buildnumber) and send it to external testers.

But I didn't see any tool or param to select a "compilation" to send to my external testers.
Is a missing feature of _pilot_ or there is any other tool?

I checked the actions on fastlane, and none do this
https://docs.fastlane.tools/actions/

Thanks you, for this wonderfull tool!

### Environment
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.49.0"
import './QE_Fastfile'

default_platform :ios

platform :ios do
  before_all do
  end
 
  #-----------------------------POST-----------------------------#

  after_all do |lane|
  end

  error do |lane, exception|
    say exception.message
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.45.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.0.3        |
| io-console                | 0.4.6        |
| rubyzip                   | 1.2.0        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
</details>


*generated on:* **2017-07-06**
</details>

**Comment by Sulfkain** [comment]
Thank @KrauseFx, that what I thought.
I have seen [this thread](https://github.com/fastlane/fastlane/issues/7957).
But I need to set to a Testflight Group, I think, [this action](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md#app-groups) is the way to go. It is?
But the documentation about Spaceship, it's not really clear.
I can't find the "find" on appgroup documentation, nor any other way of doc. 

Only that page with usefull examples, but incomplete about documentation.
How can i get a group by identifier BUT with a name too? that's not documented :/

I think other people could be thankful if I post here a solution when i get it working.
But I need documentation.

Thank you very much!

**Comment by Sulfkain** [comment]
I have seen, that kind of groups are for sharing info, AppGroups, not Testflight groups.
I didn't see any reference about this, please, I will apreciate any info about this.

Thanks!

**Comment by Sulfkain** [comment]
Hi,
Finally I have created a lane to upload a compilation already submited to TF Intern.

I copy it, maybe somebody will need it in the future, and better, this will be integrate on fastlane Pilot.

```
  lane :promoteTFExtern do |options|
    versionName = options[:versionName]
    buildNumber = versionName.to_s.empty? ? nil : options[:buildNumber]
    releaseNotesES = options[:releaseNotesES]
    releaseNotesEN = options[:releaseNotesEN]
    groups = options[:groups]
    groups = groups.to_s.empty? ? [] : groups.split(',') #Parse "a,b,c" to an array or if not passed, create an empty array
    app_identifier =  ENV['app_identifier']

    Spaceship::Tunes.login
    app = Spaceship::Tunes::Application.find(app_identifier) 
    appId = app.apple_id

    # Logic to get correct build
    if versionName.to_s.empty?
      use_build = app.edit_version.candidate_builds.first
    else
      train = app.build_trains[versionName]
      if train == nil #This versionName doesn't exists
        UI.user_error!("Not found any app with this VersionName #{versionName}, exiting this Lane")
      end

      versionBuilds = train.builds

      if buildNumber.to_s.empty?
        use_build = versionBuilds.last
      else
        versionBuilds.each do |build|
          #puts "Finding BuildNumber => #{build}"
          if build.build_version == buildNumber
            use_build = build
            break
          end
        end

        if use_build == nil #If not found a correct build, means no exists this buildNumber
          use_build = versionBuilds.last
          puts "Not found any app with VersionName => #{versionName} and #{buildNumber}"
          UI.user_error!("Not found any app with this version => #{versionName} (#{buildNumber}), exiting this Lane")
        end
      end
    end

    testFlightBuild = Spaceship::TestFlight::Build.find(app_id: appId, build_id: use_build.id)
    puts "Tesflight verion selected Version: #{use_build.train_version} and Build number: #{use_build.build_version}"

    # Update ReleaseNotes
    if !releaseNotesES.to_s.empty?
      puts "ReleaseNotes ES changed => #{releaseNotesES}"
      testfilght_app.release_notes["es-ES"] = releaseNotesES
    end
    if !releaseNotesEN.to_s.empty?
      puts "ReleaseNotes EN changed => #{releaseNotesEN}"
      testfilght_app.release_notes["en-GB"] = releaseNotesEN
      testfilght_app.release_notes["en-US"] = releaseNotesEN
    end

    #Add build to extern groups
    Spaceship::TestFlight::Group.filter_groups(app_id: appId) do |group|
      #puts "Group => #{group}"
      if groups.empty?
        #puts "Not array of group passed"
        if !group.is_internal_group
          puts "App added to group #{group.name}"
          testFlightBuild.add_group!(group) #Add group to the build train
        end
      else
        groups.each do |paramGroup|
          if group.name == paramGroup
            puts "App added to group #{group.name}"
            testFlightBuild.add_group!(group) #Add group to the build train
          end
        end
      end
    end

    #Send to Beta review and update beta info
    testFlightBuild.update_build_information!(description: nil, feedback_email: nil, whats_new: "SET YOUR WHAT'S NEWS")
    testFlightBuild.submit_for_testflight_review!
    testFlightBuild.save!
  end
```

This lane will get VersionName + BuildNumber + Groups + ReleaseNotesEN+ES 
All are optionals.

I hope this helps.
Please @KrauseFx, tell me what you need to integrate this on pilot and I will try to help you.
Thanks!

**Comment by Sulfkain** [comment]
@KrauseFx, any advice? Do you want this as action? as method on Spaceship?

Thanks!

**Comment by Sulfkain** [comment]
@KrauseFx, any advice? Do you want this as action? as method on Spaceship?

Thanks!

**Comment by KrauseFx** [comment]
Can you provide this as a plugin maybe?

**Comment by Sulfkain** [comment]
I will take a look how to do a plugin.
I will try my best :D
