### ISSUE TITLE
May need to change max supply rollout percentage

### ISSUE THREAD

**Issue by muchow-hello** [fastlane/fastlane#9690]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Since the latest update to the Google Play Developer Console, it has been easier to specify rollout percentages. While it states [in the documentation](https://developers.google.com/android-publisher/tracks) that the range is from 5-50%, I think this may be an out of date claim because you can actually set the rollout percentage on the Console to something like 75% for example.

As a further example, I got through this flow with one of my clients:

* Original Deploy: 25% rollout

* 1 Hour later: 50% rollout

* 2 Hours later: 75% rollout

* 3 Hours later: 100% rollout (so production track)

I am working on setting up some Fastlanes to handle this flow for me so I don't have to worry about it anymore, but I am limited to 50% rollout by [supply/options.rb](https://github.com/fastlane/fastlane/blob/master/supply/lib/supply/options.rb). I will probably just ignore the 75% step for now and go straight from 50% to 100%, but I thought I would let you know this may be something to look into.

I have submitted some feedback on the Google Developer website about the potentially out of date documentation, so I hope they will fix it. It might be worth testing a higher max percentage to see how the API responds. 

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[12:25:24]: fastlane finished with errors

[!] Invalid value '0.75', must be between 0.01 and 0.5

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

Don't think this is important to the issue, but I can edit it in if desired. There is some NDA stuff I will have to edit out.

**Comment by KrauseFx** [comment]
Nice catch, thanks for letting us know. Are you interested in submitting a PR to change this? :)

**Comment by muchow-hello** [comment]
@KrauseFx If I find some time this week, I will try to test the change and make a pr.

**Comment by KrauseFx** [comment]
Awesome, thanks again for the PR 👍

**Comment by muchow-hello** [comment]
You're welcome! Happy to help
