### ISSUE TITLE
Deliver - Add option to set automatic release date/time

### ISSUE THREAD

**Issue by CraigSiemens** [fastlane/fastlane#9691]
The current setting for `automatic_release` is either true or false. It would be useful if you could set the date that you want to automatically release on.

### Possible solution
Add a new option that is either nil or a date (ISO8601, timestamp, something else?).

Name could be something like
-  `automatic_release_date`
-  `automatic_release_no_earlier_than`

Then when `automatic_release` is true, it can set the release date to the one set above, or to the current date, which is the current behaviour.

**Comment by KrauseFx** [comment]
Hey @CraigSiemens, that's a great idea 👍  Is that something you'd be interested in preparing a PR for? :)
