### ISSUE TITLE
fastlane action use the wrong provision file

### ISSUE THREAD

**Issue by cleexiang** [fastlane/fastlane#9697]
I used action "beta" to build IPA file,  while it was code signing, fastlane always choosed the 'adhoc' provision file to match, not 'dev' provision file, but it worked well before, and the 'dev' priovision file worked well in xcode.

<img width="417" alt="2017-07-07 3 10 03" src="https://user-images.githubusercontent.com/676379/27947144-3a2ee8d6-6327-11e7-904d-73e2ca809298.png">
<img width="1141" alt="2017-07-07 3 07 57" src="https://user-images.githubusercontent.com/676379/27947152-4385c4b8-6327-11e7-9ded-3116231fac80.png">
 

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "69e1ddb0-4b6f-403d-afc4-0cb988c39dea"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :adhoc do
  #pod install
  cocoapods

  # build your iOS app
  gym(
    include_bitcode: true,
    export_method: "ad-hoc",
    clean: true,
    configuration: "Release"
  )
end
lane :beta do
  #pod install
  #cocoapods

  # build your iOS app
  gym(
    include_bitcode: true,
    export_method: "development",
    clean: true,
    configuration: "Debug"
  )
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.45.0  | ✅ Up-To-Date  |

*generated on:* **2017-07-07**
</details>

**Comment by KrauseFx** [comment]
Could you also share a screenshot of your `Build Settings` -> `Signing` section of your target?
