### ISSUE TITLE
intall fastlane error

### ISSUE THREAD

**Issue by yfldj** [fastlane/fastlane#9698]
ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: fastlane requires commander-fastlane (< 5.0.0, >= 4.4.5), fastimage (< 3.0.0, >= 2.1.0), google-api-client (< 0.13.0, >= 0.12.0)

**Comment by KrauseFx** [comment]
Do you use a Gemfile? Can you run `bundle update`?

**Comment by KrauseFx** [comment]
Here is more information on this topic https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

**Comment by yfldj** [comment]
@KrauseFx @fastlane-bot Thanks! I had Changed the gem sources to "https://rubygems.org/" and had solved this issues.

**Comment by KrauseFx** [comment]
Awesome :+1:
