### ISSUE TITLE
Can't set export_compliance options without submit_for_review

### ISSUE THREAD

**Issue by KondrikA** [fastlane/fastlane#9700]
I execute the deliver command with the submit_for_review parameter: false
Data is successfully loaded, but it does not work to set the export_compliance option.

I would like to set options so that I do not have to manually enter them later

**deliverfile**
```
submission_information({
      add_id_info_uses_idfa: false,
      export_compliance_platform: 'ios',
      export_compliance_compliance_required: false,
      export_compliance_encryption_updated: false,
      export_compliance_app_type: nil,
      export_compliance_uses_encryption: false,
      export_compliance_is_exempt: false,
      export_compliance_contains_third_party_cryptography: false,
      export_compliance_contains_proprietary_cryptography: false,
      export_compliance_available_on_french_store: false
});

```
### Environment
fastlane | 2.45.0

![deliver1](https://user-images.githubusercontent.com/12545036/27954626-7b80cf92-6319-11e7-8b40-73d50f71dc4f.jpg)

**Comment by KrauseFx** [comment]
What do you mean with `it does not work`? Looks like it's properly loaded.

**Comment by KondrikA** [comment]
After ipa is fully tested by Apple, a message appears informing that need to specify these options manually.
![deliver2](https://user-images.githubusercontent.com/12545036/27957206-0df4e82a-6326-11e7-8604-3d1852f2eb77.jpg)

**Comment by KondrikA** [comment]
I solved my problem by pointing out in plist that there is no encryption in the application.

**Comment by KrauseFx** [comment]
Awesome 👍
