### ISSUE TITLE
Pilot failing with "Unauthorized Access" when attempting 2FA authentication

### ISSUE THREAD

**Issue by nsforge** [fastlane/fastlane#9709]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a lane setup which runs `gym` to build an IPA, followed immediately by `pilot` which uploads the IPA to TestFlight. Every few weeks, this lane fails due to what looks like an expired session token. My Mac shows me the usual 2FA confirmation prompt, with a 6 digit code. When this happens, Fastlane shows a prompt at the command line to enter the 6 digit code, but before I have a chance to type anything, the script fails. The error is shown below.

Other relevant information:
- The `me@myemail.com` AppleID is a member of several teams
- I'm invoking `pilot` with the following snippet in my Fastfile:
```
pilot(
  team_id: "1234567890",
  changelog: changelog,
  skip_waiting_for_build_processing: true
)
```

##### Complete output when running fastlane, including the stack trace and command used

```
> fastlane submit_beta_build

… (snipped for brevity and to redact a bunch of private info)

[10:40:41]: Successfully exported and compressed dSYM file
[10:40:41]: Successfully exported and signed the ipa file:
[10:40:41]: /Users/me/Code/Path/To/My/Build/MyApp.ipa
[10:40:41]: -------------------
[10:40:41]: --- Step: pilot ---
[10:40:41]: -------------------
[10:40:41]: Login to iTunes Connect (me@myemail.com)
Two Factor Authentication for account 'me@myemail.com' is enabled
Your session cookie has been expired.
Please enter the 6 digit code: Requesting session...
+-----------------------------+----------------------------------------------------------------+
|                                         Lane Context                                         |
+-----------------------------+----------------------------------------------------------------+
| DEFAULT_PLATFORM            | ios                                                            |
| PLATFORM_NAME               | ios                                                            |
| LANE_NAME                   | ios submit_beta_build                                     |
| GIT_REPO_WAS_CLEAN_ON_START | true                                                           |
| IPA_OUTPUT_PATH             | /Users/me/Code/Path/To/My/Build/MyApp.ipa    |
| DSYM_OUTPUT_PATH            | /Users/me/Code/Path/To/My/Build/MyApp.ipa.dSYM.zip          |
| XCODEBUILD_ARCHIVE          | /Users/me/Library/Developer/Xcode/Archives/2017-07-10/MyApp  |
|                             | 2017-07-10 10.39.12.xcarchive                                  |
+-----------------------------+----------------------------------------------------------------+
[10:40:49]: Unauthorized Access
+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | opt_out_usage                       | 0           |
| 3    | default_platform                    | 0           |
| 4    | ensure_git_status_clean             | 0           |
| 5    | prompt                              | 103         |
| 6    | gym                                 | 93          |
| 💥    | pilot                               | 7           |
+------+-------------------------------------+-------------+
[10:40:49]: fastlane finished with errors
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.4.0                                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:
_[redacted]_

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.45.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version     |
| ------------------------- | ----------- |
| slack-notifier            | 1.3.0       |
| CFPropertyList            | 2.3.3       |
| colored2                  | 3.1.2       |
| nanaimo                   | 0.2.3       |
| xcodeproj                 | 1.4.4       |
| rouge                     | 1.10.1      |
| xcpretty                  | 0.2.4       |
| terminal-notifier         | 1.6.3       |
| terminal-table            | 1.4.5       |
| plist                     | 3.1.0       |
| multipart-post            | 2.0.0       |
| word_wrap                 | 1.0.0       |
| tty-screen                | 0.5.0       |
| babosa                    | 1.0.2       |
| colored                   | 1.2         |
| highline                  | 1.7.6       |
| commander-fastlane        | 4.4.5       |
| excon                     | 0.45.4      |
| unf_ext                   | 0.0.6       |
| unf                       | 0.1.4       |
| domain_name               | 0.5.24      |
| http-cookie               | 1.0.2       |
| faraday-cookie_jar        | 0.0.6       |
| fastimage                 | 2.1.0       |
| gh_inspector              | 1.0.1       |
| uber                      | 0.0.13      |
| declarative               | 0.0.9       |
| declarative-option        | 0.1.0       |
| representable             | 3.0.4       |
| retriable                 | 2.1.0       |
| public_suffix             | 2.0.4       |
| addressable               | 2.5.1       |
| mime-types-data           | 3.2016.0221 |
| mime-types                | 3.1         |
| faraday                   | 0.9.1       |
| little-plugger            | 1.1.4       |
| multi_json                | 1.11.2      |
| logging                   | 2.0.0       |
| jwt                       | 1.5.3       |
| memoist                   | 0.14.0      |
| os                        | 0.9.6       |
| signet                    | 0.7.2       |
| googleauth                | 0.5.1       |
| httpclient                | 2.8.3       |
| google-api-client         | 0.12.0      |
| mini_magick               | 4.5.1       |
| multi_xml                 | 0.5.5       |
| rubyzip                   | 1.1.7       |
| security                  | 0.1.3       |
| xcpretty-travis-formatter | 0.0.4       |
| dotenv                    | 2.1.1       |
| bundler                   | 1.12.5      |
| faraday_middleware        | 0.9.1       |
| json                      | 1.8.2       |
| claide                    | 1.0.2       |
</details>

*generated on:* **2017-07-10**
</details>

### Workaround
I've been able to work around this issue by generating a session by calling pilot manually, with `pilot list -u me@myemail.com`. When I run this command, I'm able to enter a 2FA code at the command line as expected. Subsequent calls to `fastlane` work as expected for a few weeks.

**Comment by KrauseFx** [comment]
Are you running _fastlane_ locally? I hear from some people that the session is only valid in the same region.

**Comment by nsforge** [comment]
Yes, I'm running it locally on my dev machine, in Melbourne, Australia. Interesting that you mention region… there was some issues with fastlane interacting with ITC a few months back that seemed pretty prevalent amongst Australian devs that I knew, but almost non-existent amongst those in the US. Unfortunately I can't remember what the exact issue was.

Even if the session was being invalidated prematurely due to some strangeness on Apple's backend systems, fastlane's behaviour (of showing an interactive 2FA prompt then failing before I can type anything in) isn't "working as expected" is it?

**Comment by KrauseFx** [comment]
Nah, but I wonder how we can fix it. If the session is region locked, it seems like there is not much we can do? A workaround is to create a new, separate  account that doesn't have 2 factor enabled.

**Comment by tache** [comment]
I too am having issues with 2FA - used to work, now does not. I have deactivated and reenabled, but still have the issue. I in in the US.

**Comment by ThuggishNuggets** [comment]
Seeing this issue now too. Used to work, now it doesn't.

**Comment by ThuggishNuggets** [comment]
More on this. It appears opening iTunes Connect in Incognito Mode and logging in fixed it somehow. I'm now getting a session expired message and getting prompted for the 6 digit 2FA code.

**Comment by nsforge** [comment]
This has been happening intermittently for me and other devs on my team. Strangely, one of the times that it happened, I was able to interactively enter the 2FA code at the CLI (as it should), but the more usual behaviour is that the script asks for a 2FA code then fails 0.5 seconds later, before I've typed anything (indicating a bug/issue in fastlane itself).
