### ISSUE TITLE
Import helper module using import_from_git

### ISSUE THREAD

**Issue by ileitch** [fastlane/fastlane#971]
Hey,

We have two apps and our Fastlane usage is pretty much identical. I'm attempting to extract all of our actions into a separate repository to share with both apps. Some of the extracted actions can transparently identify the app and make adjustments accordingly. I've created a helper module `helper/app_helper.rb` to hold various utility functions for identifying the app, etc.

However, now that I've come to use `import_from_git`, I'm discovering there isn't a nice way to reference the helper module from the external repository.

* `import_from_git` will only import the `actions` and `Fastfile`.
* I tried to move the helper file into the `actions` folder, however when importing external actions, Fastline   asserts that the file defines a 'FooAction' constant.

My current options appear to be:

1. Use .env files to specify the values my helper methods would usually compute. I don't like this option though, convention over configuration.
2. Make all of my helper methods actions.
3. Trick Fastlane into requiring my helper file by adding a dummy action, e.g:

```
module Fastlane
  module Actions
    class AppHelperAction < Action
    end
  end
end

module Fastlane
  module Helper
    module AppHelper
      class << self
...
```

I'm using option 3 right now, but I'm sure I don't need to point out how much a gross hack it is :smile: 

Any suggestions?

**Comment by KrauseFx** [comment]
Yeah, there is nothing for that yet. Easiest way is to add it to your Actions file :wink:

**Comment by ohwutup** [comment]
Hey @ileitch, thanks for bringing this up! I am going to mark this as a feature request and close it for now, but will be sure to reopen it again when we get a chance to bite this off for a future release. If you would like to get set up to contribute, we would LOVE that! :smile: :octopus: :palm_tree:
