### ISSUE TITLE
say: not found

### ISSUE THREAD

**Issue by lexaurin** [fastlane/fastlane#9712]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
`say` action not working on my 2.45.0 fastlane. 

Fastfile is very simple:
```
lane :test do
  say "I can speak"
end

``` 
### Captured Output

Command Used: `test`
<details><summary>Output/Log</summary>

```

DEBUG [2017-07-10 14:53:45.81]: Checking if there are any plugins that should be loaded...
ERROR [2017-07-10 14:53:45.88]: No such file or directory - xcode-select
INFO [2017-07-10 14:53:45.88]: Driving the lane 'test' 🚀
INFO [2017-07-10 14:53:45.88]: -----------------
INFO [2017-07-10 14:53:45.88]: --- Step: say ---
INFO [2017-07-10 14:53:45.88]: -----------------
INFO [2017-07-10 14:53:45.89]: $ say 'I can speak'
INFO [2017-07-10 14:53:45.89]: ▸ sh: 1: say: not found
WARN [2017-07-10 14:53:45.89]: Lane Context:
INFO [2017-07-10 14:53:45.89]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"test"}
ERROR [2017-07-10 14:53:45.89]: Exit status of command 'say 'I can speak'' was 127 instead of 0.
sh: 1: say: not found

INFO [2017-07-10 14:53:45.89]: Successfully generated documentation at path '/home/lex/workspace/sapho-cordova/fastlane/README.md'

+------+--------+-------------+
|      fastlane summary       |
+------+--------+-------------+
| Step | Action | Time (in s) |
+------+--------+-------------+
| 💥   | say    | 0           |
+------+--------+-------------+

ERROR [2017-07-10 14:53:45.91]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: Exit status of command 'say 'I can speak'' was 127 instead of 0.
sh: 1: say: not found

URL: https://api.github.com/search/issues?q=Exit%20status%20of%20command%20'say%20'I%20can%20speak''%20was%20127%20instead%20of%200.%0Ash:%201:%20say:%20not%20found%0A+repo:fastlane/fastlane
➡️  Increment build number
    https://github.com/fastlane/fastlane/pull/127 [closed] 2 💬
    04 Feb 2017



```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | debian_based stretch/sid                                       |
| Ruby                        | 2.3.1                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.7.4                                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Ubuntu 16.04.2 LTS debian_based stretch/sid (4.4.0-79-generic) |
| Ruby Lib Dir                | /usr/lib                                                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                                     |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | cs_CZ.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             | 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :test do
  say "I can speak"
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.45.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-07-10**
</details>
/var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane_core/lib/fastlane_core/ui/interface.rb:143:in `shell_error!': [!] Exit status of command 'say 'I can speak'' was 127 instead of 0. (FastlaneCore::Interface::FastlaneShellError)
sh: 1: say: not found

        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/helper/sh_helper.rb:56:in `sh_control_output'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/helper/sh_helper.rb:10:in `sh'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/actions/say.rb:10:in `run'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/fast_file.rb:269:in `block in say'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/fast_file.rb:267:in `say'
        from Fastfile:2:in `block in parsing_binding'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:56:in `run!'
        from /var/lib/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /var/lib/gems/2.3.0/gems/fastlane-2.45.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'

**Comment by PetrosIchor** [comment]
The say command is only available in OSX, it's an apple utility. If you have espeak installed, you can shell out and run:

`echo "your string"|espeak`

**Comment by lexaurin** [comment]
I see, thanks. I thought it's multiplatform action for notifications.
