### ISSUE TITLE
Trying to fetch TestFlight groups for an app ID with Spaceship returns a 403

### ISSUE THREAD

**Issue by interstateone** [fastlane/fastlane#9715]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've tried running the following with `fastlane spaceship` and `irb`, this is the output from irb. I've changed the team and app IDs in the URLs in the error output, but they were correct for what I was asking for. The account that I'd signed in with is an admin on this team and I'd selected the correct team already.

What I'm trying to do is automate distributing a build that's in beta testing to _multiple_ external teams, and as far as I can tell this is one way to do it. If there are better ways then I'd appreciate tips on that as well. 🙌 

```ruby
> Spaceship::Tunes.select_team

# omitted output, but I selected a team

> app = Spaceship::Tunes::Application.all.select { |a| a.name == "CLIENT_APP_NAME" }.first
> Spaceship::TestFlight::Group.perform_for_groups_in_app(app: app) { |g| puts g.name }

Spaceship::Client::UnexpectedResponse: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 403 </title>
</head>
<body>
<h2>HTTP ERROR: 403</h2>
<p>Problem accessing /v2/providers/123456789/apps/1234567890/groups. Reason:
<pre>    Forbidden</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/client.rb:197:in `handle_response'
        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/client.rb:79:in `get_groups'
        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/group.rb:19:in `all'
        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/group.rb:29:in `default_external_group'
        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/tunes/application.rb:374:in `default_external_group'
        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/group.rb:89:in `perform_for_groups_in_app'
        from (irb):15
        from /Users/brandon/.rbenv/versions/2.4.0/bin/irb:11:in `<main>'

> Spaceship::TestFlight::Group.all(app_id: app.apple_id)

Spaceship::Client::UnexpectedResponse: <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 403 </title>
</head>
<body>
<h2>HTTP ERROR: 403</h2>
<p>Problem accessing /v2/providers/123456789/apps/1234567890/groups. Reason:
<pre>    Forbidden</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>

        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/client.rb:197:in `handle_response'
        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/client.rb:79:in `get_groups'
        from /Users/brandon/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/test_flight/group.rb:19:in `all'
        from (irb):16
        from /Users/brandon/.rbenv/versions/2.4.0/bin/irb:11:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                             |
| --------------------------- | ------------------------------------------------- |
| OS                          | 10.12.5                                           |
| Ruby                        | 2.4.0                                             |
| Bundler?                    | false                                             |
| Git                         | git version 2.13.2                                |
| Installation Source         | ~/.rbenv/versions/2.4.0/bin/fastlane              |
| Host                        | Mac OS X 10.12.5 (16F73)                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                       |
| Is contained                | false                                             |
| Is homebrew                 | false                                             |
| Is installed via Fabric.app | false                                             |
| Xcode Path                  | /Applications/Xcode-8.3.3.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

Omitted because they contain client info, and I don't think it would affect what I'm doing with the commands above.

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| slack-notifier            | 1.5.1        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.57.1       |
| openssl                   | 2.0.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| bundler                   | 1.15.1       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-07-10**
</details>

**Comment by KrauseFx** [comment]
Thanks for submitting this. Did this work in the past?

**Comment by interstateone** [comment]
This was the first time I tried to do this.

After digging in some more I think I've determined some steps that will work correctly for me, as well as a second set of steps that will reliably cause this issue. All from within a fresh `fastlane spaceship` after entering my username.

Successful steps:

```rb
> Spaceship::Tunes.select_team
  # select the correct team
> Spaceship::Tunes.client.team_id
  "CORRECT_TEAM_ID"
> Spaceship::TestFlight::Base.client.team_id
  "CORRECT_TEAM_ID"
> app = Spaceship::Tunes::Application.all.select { |a| a.name == "CLIENT_APP_NAME" }.first
  # valid output
> Spaceship::TestFlight::Group.all(app_id: app.apple_id)
  # valid output, no error
```

Unsuccessful steps:

```rb
> app = Spaceship::Tunes::Application.all.select { |a| a.name == "CLIENT_APP_NAME" }.first
  # valid output
> Spaceship::TestFlight::Group.all(app_id: app.apple_id)
  # 403 error output
> Spaceship::Tunes.select_team
  # select the correct team
> Spaceship::Tunes.client.team_id
  "CORRECT_TEAM_ID"
> Spaceship::TestFlight::Base.client.team_id
  INCORRECT_TEAM_ID
> Spaceship::TestFlight::Base.client.team_id.class
  Integer
```

So if I don't select a team before making TestFlight API calls, the team id isn't updated when it _is_ selected. Strangely, in the error case the team id is not only incorrect but also an integer instead of a string like in the other situations.

I was probably too eager to submit the original issue that I didn't try to narrow the steps down in a fresh pry session, hopefully this provides better details.

**Comment by KrauseFx** [comment]
Alright, so calling `select_team` fixes the issue. So the only step necessary to fix it, is to show a better error message if the user forget to call `select_team`?

**Comment by interstateone** [comment]
Not quite. Following the unsuccessful steps above will cause the 403 errors for TestFlight API calls because the team ID is incorrect regardless of selecting a team.

The difference between the two sets of steps is that using the method `Spaceship::TestFlight::Group.all(app_id: app.apple_id)` _before_ selecting a team, which causes a 403, means that calling `select_team` afterwards doesn't update `Spaceship::TestFlight::Base.client.team_id` like it does `Spaceship::Tunes.client.team_id`, and so the TestFlight method continues to return 403s.
