### ISSUE TITLE
The generated archive is invalid, this can have various reasons:

### ISSUE THREAD

**Issue by IT-Q** [fastlane/fastlane#9717]
The generated archive is invalid, this can have various reasons:
[09:14:34]: Usually it's caused by the `Skip Install` option in Xcode, set it to `NO`
[09:14:34]: For more information visit https://developer.apple.com/library/ios/technotes/tn2215/_index.html
[09:14:34]: Also, make sure to have a valid code signing identity and provisioning profile installed
[09:14:34]: Follow this guide to setup code signing https://docs.fastlane.tools/codesigning/GettingStarted/
[09:14:34]: If your intention was only to export an ipa be sure to provide a valid archive at the archive path.

This is my fastfile:
# 上传到AppStore
desc "Deploy a new version to the App Store"
lane :Release_AppStore do |op|

# git上拉取最新的代码
#git_pull

# 更新本地的repo
#pod_repo_update

#执行pod install
cocoapods

# 根据参数version设置app版本号
increment_version_number(
version_number: op[:version]
)
# 根据当前日期设置app的build号 现将build号和version号设置一致
# increment_build_number

#这个action很重要cert就是下载和安装Provision Profile文件，不用你去管那些匹配证书的问题,下载的文件会在根目录的build文件夹下
cert(
username: op[:appid],
output_path: "./build"
)

#这一步就是签名
sigh(
app_identifier: op[:identifier],
username: op[:appid],
adhoc: false
)

#开始打包编译
gym(
#clean: true,
#output_directory: "/Users/baishi/Desktop",
#output_name: "release.ipa",
#export_method: "app-store",
#include_bitcode: false,
scheme: "HCSqliteToolComponent"
)

#上传app元数据
deliver(
username: op[:appid],
app_identifier: op[:identifier],
skip_screenshots: true,
skip_metadata: true,
force: false
)

**Comment by cinemast** [comment]
I am having the same problem.

**Comment by cinemast** [comment]
[16:03:20]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[16:03:22]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rbenv/versions/2.3.1/bin/fastlane        |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                 |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | de_AT.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.56.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.58.0       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.2       |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.13.6       |
| io-console                | 0.4.5        |
</details>


*generated on:* **2017-09-14**
</details>
[16:03:23]: 🙄  Wow, that's a lot of markdown text... should fastlane put it into your clipboard, so you can easily paste it on GitHub? (y/n)

**Comment by ohayon** [comment]
Hey @cinemast! Yeah totally it is a lot of output but we don't want to overwrite what is in your clipboard in case you have something important saved in there. I know I have lost many important values like passwords or one-time generated API keys by programs that copy to clipboard automatically.

Would you mind sharing the output of your terminal command? It would be helpful to have some more context about what is going wrong here. Thanks! 🐙

**Comment by varunbhargava84** [comment]
I have the same issue here.
I am new to fastlane, and have used the Fabric app for setting the environment for me. Here is the error log:

[15:06:07]: The generated archive is invalid, this can have various reasons:
[15:06:07]: Usually it's caused by the `Skip Install` option in Xcode, set it to `NO`
[15:06:07]: For more information visit https://developer.apple.com/library/ios/technotes/tn2215/_index.html
[15:06:07]: Also, make sure to have a valid code signing identity and provisioning profile installed
[15:06:07]: Follow this guide to setup code signing https://docs.fastlane.tools/codesigning/GettingStarted/
[15:06:07]: If your intention was only to export an ipa be sure to provide a valid archive at the archive path.
[15:06:07]: This error might also happen if your workspace/project file is not in the root directory of your project.
[15:06:07]: To workaround that issue, you can wrap your calls to gym with
[15:06:07]: `Dir.chdir('../path/to/dir/containing/proj') do`
[15:06:07]: For an example you can check out
[15:06:07]: https://github.com/artsy/emission-nebula/commit/44fe51a7fea8f7d52f0f77d6c3084827fe5dd59e

The certificate is valid, and I am already sharing my binary using Fabric.
