### ISSUE TITLE
portal_client.rb:440:in `download_certificate': [!] Couldn't download certificate, empty HTTP 200 response from Apple

### ISSUE THREAD

**Issue by toriningen** [fastlane/fastlane#9723]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Request here - https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/portal_client.rb#L425 - returns with empty body, which is not what spaceship expects.

I inserted `puts r.inspect` right after request, here what it shows (after being formatted for readability):

    #<Faraday::Response:0x007fa2bc273920
        @on_complete_callbacks=[],
        @env=#<Faraday::Env
            @method=:get
            @body=""
            @url=#<URI::HTTPS https://developer.apple.com/services-account/QHXXXX/account/ios/certificate/downloadCertificateContent.action?certificateId=7EXXXXXXXX&teamId=68XXXXXXXX&type=5QXXXXXXXX>
            @request=#<Faraday::RequestOptionstimeout=300, open_timeout=300>
            @request_headers={
                "User-Agent"=>"Spaceship 2.46.0",
                "csrf"=>"857672b1f9ff51ba2d21565c3b9e9a101562ff97e6247651b839cd92xxxxxxxx",
                "csrf_ts"=>"1499826446918",
                "Cookie"=>"DSESSIONID=d60e49a8bee1b61d8626a79b07b3daa3080f728febd4241ccfdddd46xxxxxxxx;
                           acn01=xxxxxxxxOmuZEyaQjMuqK0zI/EY9TXtM5ZiQAcRY6fxG+6azrFtzXokAKOxxxxxxxx==;
                           dslang=US-EN;
                           itcdq=0;
                           myacinfo=DAWXXXX...561 character skipped...MVXXXX;
                           site=USA"
            }
            @ssl=#<Faraday::SSLOptions verify=true>
            @response=#<Faraday::Response:0x007fa2bc273920 ...>
            @response_headers={
                "date"=>"Wed, 12 Jul 2017 02:27:28 GMT",
                "content-type"=>"application/octet-stream",
                "content-length"=>"0",
                "dsessionid"=>"d60e49a8bee1b61d8626a79b07b3daa3080f728febd4241ccfdddd46xxxxxxxx",
                "set-cookie"=>"DSESSIONID=d60e49a8bee1b61d8626a79b07b3daa3080f728febd4241ccfdddd46xxxxxxxx;
                               Path=/;
                               Domain=developer.apple.com;
                               Secure;
                               HttpOnly",
                "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT",
                "content-disposition"=>"attachment; filename=ios_development.cer",
                "csrf"=>"860e38bc03718a7197b899048c1ca98c0434f5a735f5ea530a13aa96xxxxxxxx",
                "csrf_ts"=>"1499826448065",
                "server"=>"ATS/7.0.0",
                "x-frame-options"=>"SAMEORIGIN",
                "host"=>"developer.apple.com",
                "cdnuuid"=>"cd6f12d5-c8b4-4d35-8dbc-dd4647689ffa-18446744073512518055",
                "age"=>"1",
                "connection"=>"close",
                "via"=>"https/1.1 sesto4-edge-bx-020.ts.apple.com (ApacheTrafficServer/7.0.0)",
                "x-cache"=>"miss"
            }
            @status=200
            @reason_phrase="OK"
        >
    >

I can send you uncensored fields privately.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

    $ FASTLANE_PASSWORD="<snip>" fastlane sigh renew --development --skip_install --app_identifier com.foo.bar --username 'toriningen@foo.bar' --team_name 'Actual Team Name' --output_path .

    +-------------------------------------+-----------------------------------+
    |                         Summary for sigh 2.46.0                         |
    +-------------------------------------+-----------------------------------+
    | development                         | true                              |
    | skip_install                        | true                              |
    | app_identifier                      | com.foo.bar                       |
    | username                            | toriningen@foo.bar                |
    | team_name                           | Actual Team Name                  |
    | adhoc                               | false                             |
    | force                               | false                             |
    | ignore_profiles_with_different_name | false                             |
    | skip_fetch_profiles                 | false                             |
    | skip_certificate_verification       | false                             |
    | platform                            | ios                               |
    +-------------------------------------+-----------------------------------+

    [05:30:40]: Starting login with user 'toriningen@foo.bar'
    [05:30:43]: Successfully logged in
    [05:30:43]: Fetching profiles...
    [05:30:44]: Verifying certificates...
    [05:30:44]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you

    <github issues skipped>

    /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/portal/portal_client.rb:440:in `download_certificate': [!] Couldn't download certificate, got this instead:  (Spaceship::Client::UnexpectedResponse)
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/spaceship/lib/spaceship/portal/certificate.rb:310:in `download_raw'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/runner.rb:203:in `block in certificate_to_use'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/runner.rb:201:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/runner.rb:201:in `find_all'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/runner.rb:201:in `certificate_to_use'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/runner.rb:137:in `create_profile!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/runner.rb:35:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/manager.rb:7:in `start'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/commands_generator.rb:55:in `block (2 levels) in run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/commands_generator.rb:123:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/sigh/lib/sigh/commands_generator.rb:11:in `start'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
        from /usr/local/lib/ruby/gems/2.4.0/gems/fastlane-2.46.0/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:22:in `load'
        from /usr/local/bin/fastlane:22:in `<main>'

This is being run with homebrew-installed ruby, and fastlane installed with gem.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.13.1                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.1_1/lib          |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-07-12**
</details>

**Comment by toriningen** [comment]
@fastlane-bot thanks for suggestion, but I think this is false positive, and this issue is not related to code signing. Creating provisioning profile from XCode works, and I can build and sign app, but via XCode. The point was to use `sigh` in the CI process, so I can get mobileprovision certificate and resign the release .ipa for Appium somehow.

**Comment by KrauseFx** [comment]
I just tried this locally, and things work as expected. Did it recently stop working for you? Any steps I have to take to be able to reproduce?

**Comment by toriningen** [comment]
@KrauseFx no, it was my first attempt to get my hands on sigh, so it never worked for me before. I can craft a curl request based on what spaceship is sending, to see if it reproduces at your side. Is there any way to pass it to you without posting it in open in comments?

**Comment by KrauseFx** [comment]
That's so weird, do you have read and write access to this specific certificate?

**Comment by BenSS** [comment]
I hit this same error message, and figured it out for my case: The profile being used was invalid (not expired).

**Comment by mmynarski** [comment]
Got the same issue on sigh 2.61 .0:
`download_certificate': [!] Couldn't download certificate, got this instead:  (Spaceship::Client::UnexpectedResponse)

I'm trying right now to revoke all certificates involved & create new ones.
