### ISSUE TITLE
Increment build number for target fails

### ISSUE THREAD

**Issue by lordukr** [fastlane/fastlane#9728]
### New Issue Checklist

- [+ ] Updated fastlane to the latest version
- [+ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Error when trying to increment build number

### Captured Output

Command Used: `app_dev`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/wellnesslayersukraine/Documents/Platform_iOS/fastlane/Appfile'
- app_identifier: '###.#####.###'
- apple_id: '#####@######.###'
- team_id: '##########'
-------
DEBUG [2017-07-12 14:25:53.26]: Checking if there are any plugins that should be loaded...
DEBUG [2017-07-12 14:25:53.35]: Loading 'fastlane-plugin-versioning' plugin
INFO [2017-07-12 14:25:53.46]: gem 'fastlane-plugin-versioning' is already installed
+------------------------+---------+------------------------+
|                       Used plugins                        |
+------------------------+---------+------------------------+
| Plugin                 | Version | Action                 |
+------------------------+---------+------------------------+
| fastlane-plugin-versi  | 0.2.7   | get_app_store_version  |
| oning                  |         | _number                |
|                        |         | get_build_number_from  |
|                        |         | _plist                 |
|                        |         | get_info_plist_path    |
|                        |         | get_version_number_fr  |
|                        |         | om_git_branch          |
|                        |         | get_version_number_fr  |
|                        |         | om_plist               |
|                        |         | increment_build_numbe  |
|                        |         | r_in_plist             |
|                        |         | increment_version_num  |
|                        |         | ber_in_plist           |
+------------------------+---------+------------------------+

INFO [2017-07-12 14:25:53.61]: Driving the lane 'app_dev' 🚀
INFO [2017-07-12 14:25:53.62]: ---------------------------------------------
INFO [2017-07-12 14:25:53.62]: --- Step: increment_build_number_in_plist ---
INFO [2017-07-12 14:25:53.62]: ---------------------------------------------
ERROR [2017-07-12 14:25:56.29]: undefined method `[]' for nil:NilClass
ERROR [2017-07-12 14:25:56.29]: Unable to find plist file at '/Users/#############/Documents/Platform_iOS/Targets/$(TARGET_NAME)/Info.plist'
WARN [2017-07-12 14:25:56.84]: Lane Context:
INFO [2017-07-12 14:25:56.84]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"app_dev", :BUILD_NUMBER=>true}
ERROR [2017-07-12 14:25:56.84]: undefined method `to_i' for true:TrueClass
INFO [2017-07-12 14:25:56.84]: Successfully generated documentation at path '/Users/#############/Documents/Platform_iOS/fastlane/README.md'

+------+------------------------+-------------+
|              fastlane summary               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 💥   | increment_build_numbe  | 2           |
|      | r_in_plist             |             |
+------+------------------------+-------------+

DEBUG [2017-07-12 14:25:56.86]: All plugins are up to date
ERROR [2017-07-12 14:25:56.86]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `to_i' for true:TrueClass

URL: https://api.github.com/search/issues?q=undefined%20method%20%60to_i'%20for%20true:TrueClass+repo:fastlane/fastlane
➡️  Using wait_processing_interval option in pilot leads to an exception
    https://github.com/fastlane/fastlane/issues/3259 [closed] 1 💬
    22 Sep 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2017-07-12 14:25:57.69]: All plugins are up to date


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.5                                         |
| Ruby                        | 2.2.4                                           |
| Bundler?                    | false                                           |
| Git                         | git version 2.11.0 (Apple Git-81)               |
| Installation Source         | /usr/local/lib/fastlane_lib/bundle/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                        |
| Ruby Lib Dir                | /usr/local/lib/fastlane_lib/bundle/lib          |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | true                                            |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/     |
| Xcode Version               | 8.3.3                                           |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :app_dev do
increment_build_number_in_plist(
target: "APP"
)
version = get_version_number_from_plist(
target: "APP"
)

build_number = get_build_number_from_plist(
target: "APP"
)
gym(scheme: "APP",
workspace: "/Users/Apple/Desktop/agentGenerateNewBuild/CoachingMember.xcworkspace",
configuration: "Debug",
export_method: "development",
clean:true
)

git_commit(path: "./", message:"#version "+ version+" ("+ build_number+") APP Dev")
add_git_tag(
  tag: "APP/v"+ version+ "/Dev/"+ build_number
)
push_to_git_remote(
  remote: "origin",   
  local_branch: "development",  
  remote_branch: "development", 
  force: false,    
  tags: true     
)
changelog = download(url: "################")
crashlytics(api_token: "##############################",
              build_secret: "########################",
emails: "#######@#####.###, #####@#####.###",
notes: changelog,
notifications: true
#emails: "#######@######.###"
)
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "###.####.#####" # The bundle identifier of your app
apple_id "#######@######.###" # Your Apple email address

team_id "########"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.2.7   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| slack-notifier             | 1.5.1        |
| CFPropertyList             | 2.3.5        |
| claide                     | 1.0.2        |
| colored2                   | 3.1.2        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.5.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| plist                      | 3.3.0        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.1        |
| multipart-post             | 2.0.0        |
| word_wrap                  | 1.0.0        |
| tty-screen                 | 0.5.0        |
| babosa                     | 1.0.2        |
| colored                    | 1.2          |
| highline                   | 1.7.8        |
| commander-fastlane         | 4.4.5        |
| excon                      | 0.57.1       |
| faraday                    | 0.12.1       |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| fastimage                  | 2.1.0        |
| gh_inspector               | 1.0.3        |
| uber                       | 0.1.0        |
| declarative                | 0.0.9        |
| declarative-option         | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.0.2        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.12.1       |
| logging                    | 2.2.2        |
| jwt                        | 1.5.6        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.7.3        |
| googleauth                 | 0.5.1        |
| httpclient                 | 2.8.3        |
| google-api-client          | 0.12.0       |
| json                       | 1.8.1        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| xcpretty-travis-formatter  | 0.0.4        |
| dotenv                     | 2.2.1        |
| bundler                    | 1.15.1       |
| faraday_middleware         | 0.11.0.1     |
| fastlane-plugin-versioning | 0.2.7        |
</details>

*generated on:* **2017-07-12**
</details>

**Comment by lordukr** [comment]
Fixed by changing theme:"" to scheme:""

**Comment by KrauseFx** [comment]
Nice, is it cool to close the issue?
