### ISSUE TITLE
Apple ID or Password incorrect - pilot upload

### ISSUE THREAD

**Issue by Danm72** [fastlane/fastlane#9729]
### New Issue Checklist

- [Y] Updated fastlane to the latest version
- [Y] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane pilot list, etc all login and get the correct information.

However fastlane pilot upload initially logs in but then fails with authentication errors. Upon reentering the correct information the login still returns as failed.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
[33mSuccessfully loaded Appfile at path '/Users/user/XcodeProjects/company-ios/fastlane/Appfile'[0m
- [36mapp_identifier[0m: '[32mcom.company.company-ios-app[0m'
- [36mapple_id[0m: '[32m123@gmail.com[0m'
-------
INFO [2017-07-12 12:44:25.92]: Login to iTunes Connect (email123@gmail.com)
Looking for iTunes Connect Team with ID 118456436
INFO [2017-07-12 12:44:29.15]: Login successful
DEBUG [2017-07-12 12:44:29.15]: App identifier (com.company.company-ios-app)
INFO [2017-07-12 12:44:30.12]: [32mReady to upload new build to TestFlight (App: 1252312251)...[0m
DEBUG [2017-07-12 12:44:30.15]: App Platform (ios)
INFO [2017-07-12 12:44:30.38]: [32mWrote XML data to '/var/folders/rl/rwykssfn2051nbzjfc8ww0bw0000gn/T/d20170712-50880-1fqkoq2/1252312251.itmsp'[0m
INFO [2017-07-12 12:44:30.41]: Going to upload updated app to iTunes Connect
INFO [2017-07-12 12:44:30.41]: [32mThis might take a few minutes. Please don't interrupt the script.[0m
DEBUG [2017-07-12 12:44:30.50]: /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/bin/java -Djava.ext.dirs=/Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/java/lib/ext -XX:NewSize=2m -Xms32m -Xmx1024m -Xms1024m -Djava.awt.headless=true -Dsun.net.http.retryPost=false -classpath /Applications/Xcode.app/Contents/Applications/Application\ Loader.app/Contents/itms/lib/itmstransporter-launcher.jar com.apple.transporter.Application -m upload -u email123@gmail.com -p YourPassword -f /var/folders/rl/rwykssfn2051nbzjfc8ww0bw0000gn/T/d20170712-50880-1fqkoq2/1252312251.itmsp -t Signiant -k 100000 2>&1
DEBUG [2017-07-12 12:44:32.88]: [Transporter]: INFO: Transporter is skipping bundle update check: Already checked recently.
DEBUG [2017-07-12 12:44:32.97]: [Transporter]: INFO: Logging configured successfully.
DEBUG [2017-07-12 12:44:32.97]: [Transporter]: DEBUG: Attempting refresh of configuration data from https://contentdelivery.itunes.apple.com/transporter/Defaults.properties
DEBUG [2017-07-12 12:44:33.13]: [Transporter]: DEBUG: Configuration refresh successful.
DEBUG [2017-07-12 12:44:33.13]: [Transporter]: DEBUG: Saving configuration to local path: /Users/user/.itmstransporter/Defaults.properties
DEBUG [2017-07-12 12:44:33.14]: [Transporter]: INFO: iTMSTransporter : iTunes Store Transporter [1.9.3]
DEBUG [2017-07-12 12:44:33.14]: [Transporter]: INFO: OS identifier: Mac OS X 10.12.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2017-07-12 12:44:33.14]: [Transporter]: INFO: Memory: [JVM] 843M free, 982M total, 982M max [System] (Physical) 94M free, 16384M total (Swap) 1246M free, 3072M total
DEBUG [2017-07-12 12:44:33.15]: [Transporter]: INFO: Upload mode selected.
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: INFO: Examining the package at: /var/folders/rl/rwykssfn2051nbzjfc8ww0bw0000gn/T/d20170712-50880-1fqkoq2/1252312251.itmsp
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: INFO: Ensuring that package has well formed metadata file...
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: DEBUG: Getting case-sensitive metadata xml filename...
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: INFO: Gathering the list of valid files from the package ...
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: DEBUG:   57b7aca1dfefe8ff25ff9c97c0e872b6.ipa will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: DEBUG:   metadata.xml will be verified by Apple's web service to determine if it is a valid file.
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: INFO: Finished gathering the list of valid files from the package.
DEBUG [2017-07-12 12:44:33.17]: [Transporter]: DEBUG:   Case-sensitive metadata filename is: metadata.xml
DEBUG [2017-07-12 12:44:33.19]: [Transporter]: INFO: Performing authentication of package 1252312251.itmsp ...
DEBUG [2017-07-12 12:44:33.19]: [Transporter]: DBG-X: Memory: [JVM] 833M free, 982M total, 982M max [System] (Physical) 78M free, 16384M total (Swap) 1246M free, 3072M total
DEBUG [2017-07-12 12:44:33.19]: [Transporter]: DBG-X: Memory: [JVM] 833M free, 982M total, 982M max [System] (Physical) 78M free, 16384M total (Swap) 1246M free, 3072M total
DEBUG [2017-07-12 12:44:33.19]: [Transporter]: DBG-X: Using operation named: authenticateForSession
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.0
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.12.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2017-07-12T12:44:33+01:00
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.312818
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u email123@gmail.com -p **hidden value** -f /var/folders/rl/rwykssfn2051nbzjfc8ww0bw0000gn/T/d20170712-50880-1fqkoq2/1252312251.itmsp -t Signiant -k 100000
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter Username = email123@gmail.com
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter Version = 1.9.3
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2017-07-12 12:44:33.20]: [Transporter]: INFO: id = 20170712124433-063
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20101)]
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter ErrorCode = -20101
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter Success = false
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X: Deflated 452 bytes to 392
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X: Using operation named: validateMetadata
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X: Apple's web service operation input parameters:
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter Application = iTMSTransporter
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter BaseVersion = 1.9.0
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter Files = [57b7aca1dfefe8ff25ff9c97c0e872b6.ipa, metadata.xml]
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter Metadata = <?xml version="1.0" encoding="UTF-8"?>
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter MetadataChecksum = 77e6553e6d5c50752f5eb66ebd53cff6
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter MetadataCompressed = (suppressed)
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter OSIdentifier = Mac OS X 10.12.5 (x86_64); jvm=24.80-b07; jre=1.7.0-internal-root_2015_05_12_09_52-b00
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter PackageName = 1252312251.itmsp
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter PackageSize = 71200709
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter Password = **hidden value**
DEBUG [2017-07-12 12:44:33.84]: [Transporter]: DBG-X:   parameter StatisticsClientStartDateTimeZoneISO = 2017-07-12T12:44:33+01:00
DEBUG [2017-07-12 12:44:33.85]: [Transporter]: DBG-X:   parameter StatisticsPreviousCallDurationInSecs = 0.642918
DEBUG [2017-07-12 12:44:33.85]: [Transporter]: DBG-X:   parameter Throttle = 100000
DEBUG [2017-07-12 12:44:33.85]: [Transporter]: DBG-X:   parameter TransporterArguments = -m upload -u email123@gmail.com -p **hidden value** -f /var/folders/rl/rwykssfn2051nbzjfc8ww0bw0000gn/T/d20170712-50880-1fqkoq2/1252312251.itmsp -t Signiant -k 100000
DEBUG [2017-07-12 12:44:33.85]: [Transporter]: DBG-X:   parameter Username = email123@gmail.com
DEBUG [2017-07-12 12:44:33.85]: [Transporter]: DBG-X:   parameter Version = 1.9.3
DEBUG [2017-07-12 12:44:33.85]: [Transporter]: DBG-X:   parameter iTMSTransporterMode = upload
DEBUG [2017-07-12 12:44:33.85]: [Transporter]: INFO: id = 20170712124433-475
DEBUG [2017-07-12 12:44:34.12]: [Transporter]: DBG-X: Apple's web service operation return value:
DEBUG [2017-07-12 12:44:34.12]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)
DEBUG [2017-07-12 12:44:34.12]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20101)]
DEBUG [2017-07-12 12:44:34.12]: [Transporter]: DBG-X:   parameter ErrorCode = -20101
DEBUG [2017-07-12 12:44:34.12]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2017-07-12 12:44:34.12]: [31m[Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)
[0m
[32m-------------------------------------------------------------------------------------[0m
[32mPlease provide your Apple Developer Program account credentials[0m
[32mThe login information you enter will be stored in your macOS Keychain[0m
[32mYou can also pass the password using the `FASTLANE_PASSWORD` environment variable[0m
[32mMore information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager[0m
[32m-------------------------------------------------------------------------------------[0m

____

DEBUG [2017-07-12 12:44:01.04]: [Transporter]: DBG-X:   parameter ErrorMessage = Your Apple ID or password was entered incorrectly. (-20101)
DEBUG [2017-07-12 12:44:01.04]: [Transporter]: DBG-X:   parameter Errors = [Your Apple ID or password was entered incorrectly. (-20101)]
DEBUG [2017-07-12 12:44:01.04]: [Transporter]: DBG-X:   parameter ErrorCode = -20101
DEBUG [2017-07-12 12:44:01.04]: [Transporter]: DBG-X:   parameter Success = false
ERROR [2017-07-12 12:44:01.04]: [Transporter Error Output]: Your Apple ID or password was entered incorrectly. (-20101)

### Environment

WARN [2017-07-12 12:46:26.37]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
DEBUG [2017-07-12 12:46:26.73]: Checking if there are any plugins that should be loaded...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F2073)                  |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2e 3 Dec 2015                   |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_IE.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "fc8a9544-6acd-4a40-a9ad-23264c68f867"

default_platform :ios

# xcode_select "/Applications/Xcode.app"
xcversion(version: "8.3.3")

desc "Release a new beta version on Hockey"
desc "This action does the following:"
desc ""
desc "- Ensures a clean git status"
desc "- Increment the build number"
desc "- Build and sign the app"
desc "- Commit and push the version bump"
lane :beta do
  bumpAndTagBeta
  # cocoapods

  # build your iOS app
  gym(
    scheme: "company-ios",
    export_method: "app-store"
  )

  # upload to Testflight
  pilot(
    skip_waiting_for_build_processing: false,
    ipa: "company-ios.ipa",

  )

  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end

desc "Increment the app's build number, add a tag, and push"
  lane :bumpAndTagBeta do |options|
    # Make sure we start off with a clean slate
    ensure_git_status_clean
    # Increment build number to current date
    build_number = Time.new.strftime("%Y.%m.%d")
    version_number = get_version_number

    increment_build_number build_number: build_number
    increment_version_number(bump_type: "patch")

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts
    # Tag release and push to GitHub
    commit_version_bump message: "Deploying version #{version_number}."

    # add_git_tag tag: version_number
    push_to_git_remote
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# The Appfile can be used to specify information that's used across all fastlane
# tools, like your username or the app's bundle identifier.
#
# For more details, check out the documentation at:
# https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

app_identifier "com.company.company-ios-app" # the bundle identifier of your app
apple_id "user123@gmail.com" # Your Apple ID
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.0       |
| json                      | 2.0.2        |
</details>

*generated on:* **2017-07-12**
</details>

**Comment by edsanville** [comment]
I am getting this same error. I saw that other people were getting this error because they had special characters in their passwords, but I have no special characters whatsoever. It's just letters and numbers.

I believe the problem started when I joined a second iTunes Connect team, but I'm not sure. I was hoping it would be resolved, but I haven't been able to upload with fastlane for about 2 months now. Uploading with Application Loaders still works.

**Comment by Danm72** [comment]
@edsanville Yeah mine is just letters and numbers too. I disabled 2FA too. Still no dice.

**Comment by edsanville** [comment]
Curious, are you also a member of more than one team in iTunes Connect?

**Comment by Danm72** [comment]
Nope! Just one.

**Comment by GantMan** [comment]
Got this error, too.

**Comment by GantMan** [comment]
turns out I had an environment variable messing me up.

**Comment by edsanville** [comment]
@GantMan 
What was that environment variable that was messing you up?

**Comment by Danm72** [comment]
@KrauseFx Hey Felix, sorry to be a pain in the ass but have you any idea what might be causing this?

**Comment by mpirri** [comment]
A few questions: 
- do you have `FASTLANE_PASSWORD` set?
- do you have a keychain entry for your AppleId for that account?
If so, maybe delete the record and try again. I wonder if somehow you have a bad password saved for you account in one of those places and iTunesTransporter is somehow getting the wrong password while `spaceship` is getting the correct one?

Let us know if you have any luck and we can dig into this further!  🚀

**Comment by Danm72** [comment]
@mpirri thanks a million for taking the time to respond to this, I know you're probably crazy busy. Great product/library btw.

I had two references to 'deliver' in my keychain, deleting them seems to have done the job!!

**Comment by edsanville** [comment]
I also had two references to deliver in my Keychain, for some reason!

Thank you guys so much for this, it saves me a lot of yak shaving! Here's some specific info that might be useful for developers trying to fix this issue:

One of my keys was of the form "deliver.appspecific.APPLEID"
The other was of the form "deliver.APPLEID"

I hope this helps!

**Comment by Danm72** [comment]
Mine were the same as @edsanville's.

**Comment by tache** [comment]
ditto ... two keys as @edsanville
