### ISSUE TITLE
Create Twitter Action

### ISSUE THREAD

**Issue by jcampbell05** [fastlane/fastlane#973]
So discussed a method of tweeting to twitter with @KrauseFx.

Implementation could use https://github.com/muffinista/chatterbot underneath which makes it straight forward to do twitter actions.

Hopefully once I have some freetime, I'll be able to implement an action for this :) :rocket:

**Comment by hjanuschka** [comment]
https://github.com/fastlane/fastlane/pull/1202

**Comment by KrauseFx** [comment]
Closing and moving further discussion to https://github.com/fastlane/fastlane/pull/1202, thanks @hjanuschka :+1:
