### ISSUE TITLE
Unable to upload crashlytics 

### ISSUE THREAD

**Issue by nageshkumarmishra** [fastlane/fastlane#9732]
fastlane script:

crashlytics(
      groups: 'iOSTest',
      notifications: true,
      notes: "Nagesh commit",
      ipa_path: "/Users/nageshkumarmishra/Downloads/iOSTest.ipa",
      api_token: "Added”,
      build_secret: "Added"
      )

Output: --

[19:17:18]: 2017-07-12 19:17:01.664 submit Crashlytics: Crashlytics.framework/submit 1.3.5 (18)
2017-07-12 19:17:18.362 submit Crashlytics: Unable to add release notes: Project iOSTest is inactive
2017-07-12 19:17:18.362 submit Crashlytics: Failed to add notes to the release

+--------------------+-----------------------------------------------------------------------------+
|                                           Lane Context                                           |
+--------------------+-----------------------------------------------------------------------------+
| DEFAULT_PLATFORM   | ios                                                                         |
| VERSION_NUMBER     | 1.0.19                                                                      |
| PLATFORM_NAME      | ios                                                                         |
| LANE_NAME          | ios beta                                                                    |
| IPA_OUTPUT_PATH    | /Users/nageshkumarmishra/Downloads/ios-build- ...
| DSYM_OUTPUT_PATH   | /Users/nageshkumarmishra/Downloads/ios-build-....
| XCODEBUILD_ARCHIVE | /Users/nageshkumarmishra/Library/Developer/Xcode/Archives/2017-07-12/iOSTest. |
+--------------------+-----------------------------------------------------------------------------+
[19:17:18]: Shell command exited with exit status 1 instead of 0.

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | increment_version_number            | 1           |
| 4    | get_version_number                  | 0           |
| 5    | cocoapods                           | 2           |
| 6    | gym                                 | 280         |
| 💥   | crashlytics                         | 16          |
+------+-------------------------------------+-------------+

[19:17:18]: fastlane finished with errors

[!] Shell command exited with exit status 1 instead of 0.

**Comment by nageshkumarmishra** [comment]
submit Crashlytics: Unable to add testers: Could not find a group for one or more of: ["iOSTest"]
2017-07-12 19:57:57.400 submit Crashlytics: Failed to add testers/groups to the release

**Comment by kylebrowning** [comment]
Downgrading fixed this issue for me.

**Comment by nageshkumarmishra** [comment]
To which version ?

**Comment by KrauseFx** [comment]
Please don't downgrade, that's not a good solution, and probably won't help much. Is this issue still happening?

**Comment by nageshkumarmishra** [comment]
Can you please let me know, if we want to active the App in Crashlytics, we need to lunch the app at least one ?

**Comment by kylebrowning** [comment]
@KrauseFx dont have much of an option at this point, but downgrading to 2.4.60 fixed it.

**Comment by kylebrowning** [comment]
This resolved for me.

**Comment by ohayon** [comment]
@kylebrowning are you still on the old version of fastlane? Have you tried updating to more recent versions?

**Comment by kylebrowning** [comment]
I am on the latest version. I feel like this may have been an issue with a `"` in my FastFile.

**Comment by ohayon** [comment]
Amazing! I am going to close this issue for now. Thanks for following up! 🚀
