### ISSUE TITLE
Notification action doesn't auto-dismiss

### ISSUE THREAD

**Issue by eliotfowler** [fastlane/fastlane#9733]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

After upgrading from the deprecated `notify` to `notification`, it appears that there is no way to make the notification dismiss automatically like it used to.

It now shows this notification which needs to be manually dismissed with "Close":

![image](https://user-images.githubusercontent.com/1241943/28132818-cf080c7a-66f2-11e7-81cb-08f977655b82.png)

According to the `terminal-notifier` gem, which it appears the notification action uses, it supports "Banner"-style notifications. Is there a way to make the notification action use this?

Note: here is how I am calling the notification action:
```
notification(
  message: "Fastlane finished '#{lane}' successfully"
)
```

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

bundle exec fastlane note
+------------------------+---------+--------+
|               Used plugins                |
+------------------------+---------+--------+
| Plugin                 | Version | Action |
+------------------------+---------+--------+
| fastlane-plugin-aws_s3 | 0.2.8   | aws_s3 |
+------------------------+---------+--------+

[11:07:35]: -------------------------------------------------
[11:07:35]: --- Step: Verifying required fastlane version ---
[11:07:35]: -------------------------------------------------
[11:07:35]: Your fastlane version 2.46.0 matches the minimum requirement of 1.92.0  ✅
[11:07:35]: ------------------------------
[11:07:35]: --- Step: default_platform ---
[11:07:35]: ------------------------------
[11:07:35]: Driving the lane 'ios note' 🚀
[11:07:35]: -----------------------
[11:07:35]: --- Step: xcversion ---
[11:07:35]: -----------------------
[11:07:35]: Setting Xcode version to /Applications/Xcode.app for all build steps
[11:07:35]: --------------------------
[11:07:35]: --- Step: notification ---
[11:07:35]: --------------------------

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | xcversion                           | 0           |
| 4    | notification                        | 0           |
+------+-------------------------------------+-------------+

[11:07:35]: fastlane.tools finished successfully 🎉

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.4                                          |
| Ruby                        | 2.2.2                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.0 (Apple Git-88)                |
| Installation Source         | ~/.rbenv/versions/2.2.2/bin/fastlane             |
| Host                        | Mac OS X 10.12.4 (16E195)                        |
| Ruby Lib Dir                | ~/.rbenv/versions/2.2.2/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.92.0"

default_platform :ios

platform :ios do

  # Setup
  before_all do
    xcversion(version: '8.3.3')
  end

  # Public Lanes
  desc "Install all certificates needed for develeopment"
  lane :setup_dev do
    app_id = 'com.jam.ios.internal'

    update_app_identifier(
      app_identifier: app_id,
      plist_path: "JAM/Supporting\ Files/Info.plist"
    )

    # set local environment variables and make sure certs are installed
    set_up_local_appstore(app_id: app_id)

    # enable automatic code signing
    automatic_code_signing(
      path: 'JAM.xcodeproj',
      use_automatic_signing: true
    )
  end

  desc "Sends a test notification"
  lane :note do
  end

  desc "Runs all the tests"
  lane :test do
    # run linter
    swiftlint(
      config_file: '.swiftlint.yml',
      quiet: true
    )

    # run tests
    scan(
      workspace: 'JAM.xcworkspace',
      scheme: 'JAM Debug - Dev',
      device: 'iPhone 6s',
      clean: false
    )
  end

  desc "Travis"
  lane :ci do
    app_id = "com.jam.ios.internal"
    is_pull_request = ENV["TRAVIS_PULL_REQUEST"] != 'false'

    # initial setup for travis
    set_up_travis

    # increment build number to current date
    build_number = Time.new.utc.strftime("%Y%m%d%H%M%S")
    increment_build_number build_number: build_number

    # disable automatic code signing
    automatic_code_signing(
      path: 'JAM.xcodeproj',
      use_automatic_signing: false
    )

    # make sure we are using the correct bundle id
    update_app_identifier(
      app_identifier: app_id,
      plist_path: "JAM/Supporting\ Files/Info.plist"
    )

    # run tests
    scan(
      workspace: 'JAM.xcworkspace',
      scheme: 'JAM Debug - Dev',
      device: 'iPhone 6s',
      clean: false,
      skip_build: true,
      output_directory: 'fastlane',
      output_types: 'html',
      output_style: 'standard'
    )

    # only publish a build to test flight if we're building master
    if git_branch == 'master' && !is_pull_request
      # build app
      gym(
        scheme: "JAM Release - Dev",
        sdk: "iphoneos",
        clean: false,
        include_symbols: true,
        include_bitcode: false,
        export_team_id: "6P7HTC8KL2"
      )

      # send build to TestFlight
      pilot(
        app_identifier: app_id,
        username: "ios@diy.org",
        skip_waiting_for_build_processing: true,
        skip_submission: true
      )

      # notify #ios-builds that the TestFlight build has been uploaded
      post_to_slack(destination: "TestFlight", environment: 'Dev')
    end
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    app_id = "com.jam.ios"

    # we are going to be committing so we need to make sure there are no changes
    # in the working directory
    ensure_git_status_clean

    # set local environment variables and make sure certs are installed
    set_up_local_appstore(app_id: app_id)

    # increment build number to current date
    build_number = Time.new.utc.strftime("%Y%m%d%H%M%S")
    increment_build_number build_number: build_number
    commit_version_bump

    # make sure the app is set to use the correct bundle id
    update_app_identifier(
      app_identifier: app_id,
      plist_path: "JAM/Supporting\ Files/Info.plist"
    )

    # build the app
    gym(
      scheme: "JAM Release - Production",
      sdk: "iphoneos",
      include_symbols: true,
      include_bitcode: false
    )

    # send the build to TestFlight (will wait for processing to finish)
    pilot(
      username: "ios@diy.org",
      app_identifier: app_id
    )

    # Notify #ios-builds that the build finished
    post_to_slack(destination: "TestFlight", environment: 'Production')

    # clean up after ourselves
    reset_git_repo(force: true)
  end

  desc "Submit a new Beta for Internal Testing (staging)"
  lane :beta_internal do |options|
    app_id = "com.jam.ios.internal"

    # make sure they specify an environment
    environment = options[:environment]
    raise 'You must specify an environment (dev or staging)' if environment != 'dev' && environment != 'staging'
    environment = environment.split.map(&:capitalize).join(' ')

    # we are going to be committing so we need to make sure there are no changes
    # in the working directory
    ensure_git_status_clean

    # set local environment variables and make sure certs are installed
    set_up_local_appstore(app_id: app_id)

    # increment build number to current date
    build_number = Time.new.utc.strftime("%Y%m%d%H%M%S")
    increment_build_number build_number: build_number
    commit_version_bump

    # make sure the app is set to use the correct bundle id
    update_app_identifier(
      app_identifier: app_id,
      plist_path: "JAM/Supporting\ Files/Info.plist"
    )

    # build the app
    gym(
      scheme: "JAM Release - #{environment}",
      sdk: "iphoneos",
      include_symbols: true,
      include_bitcode: false,
      clean: true
    )

    # send the build to TestFlight (will wait for processing to finish)
    pilot(
      username: "ios@diy.org",
      app_identifier: app_id
    )

    # Notify #ios-builds that the build finished
    post_to_slack(destination: "TestFlight", environment: environment)

    # clean up after ourselves
    reset_git_repo(force: true)
  end

  desc "Upload a new build to Amazon S3 (dev)"
  desc "THIS IS CURRENTLY BROKEN SORRY"
  lane :enterprise_dev do
    app_id = "com.jam.ios-enterprise"

    # set local environment variables and make sure certs are installed
    set_up_local_enterprise(app_id: app_id)

    # make sure the app is set to use the correct bundle id
    update_app_identifier(
      app_identifier: app_id,
      plist_path: "JAM/Supporting\ Files/Info.plist"
    )

    # build the app
    gym(
      scheme: "JAM Release - Dev",
      sdk: "iphoneos",
      export_method: 'enterprise',
      output_directory: "builds/",
      output_name: "JAM.ipa",
      export_team_id: '5YZ3NGWL6D',
      include_symbols: true,
      include_bitcode: false
    )

    # upload the ipa, html, and json to amazon s3
    aws_s3(
      access_key: ENV['FASTLANE_S3_ACCESS_KEY'],
      secret_access_key: ENV['FASTLANE_S3_SECRET_ACCESS_KEY'],
      bucket: 'jam-ios',
      region: 'us-west-2',
      endpoint: 'https://s3-us-west-2.amazonaws.com',
      ipa: 'builds/JAM.ipa',
      dsym: 'builds/JAM.app.dSYM.zip',
      upload_metadata: true,
      verbose: true
    )
  end

  # Private lanes
  private_lane :post_to_slack do |options|
    version     = get_version_number(xcodeproj: "JAM.xcodeproj")
    build       = get_build_number(xcodeproj: "JAM.xcodeproj")
    environment = options[:environment]
    destination = options[:destination]

    verb_tense = options[:processing] ? 'will soon be' : 'is now'

    slack(
      message: "<!here|here>: New iOS version *#{version}* (#{build}) running `#{environment}` #{verb_tense} available on *#{destination}*  :rocket:",
      channel: "#ios-builds"
    )
  end

  private_lane :set_up_travis do
    app_id = "com.jam.ios.internal"
    # create a new keychain
    password = SecureRandom.base64
    keychain_name = "fastlane"
    ENV["MATCH_KEYCHAIN_NAME"] = keychain_name
    ENV["MATCH_KEYCHAIN_PASSWORD"] = password

    create_keychain(
      name: keychain_name,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: password,
      add_to_search_list: :replace
    )

    # get development certs and profiles
    match(
      app_identifier: app_id,
      username: "ios@diy.org",
      team_id: "6P7HTC8KL2",
      git_url: "git@github.com:diy/ios-certs-appstore.git",
      type: "development",
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: password
    )

    # get appstore certs and profiles
    match(
      app_identifier: app_id,
      username: "ios@diy.org",
      team_id: "6P7HTC8KL2",
      git_url: "git@github.com:diy/ios-certs-appstore.git",
      type: "appstore",
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: password
    )
  end

  private_lane :set_up_local_appstore do |options|
    app_id = options[:app_id] || 'com.jam.ios.internal'
    # ensure the secrets file exists
    secrets_missing_message = 'You must get a copy of and run \'scripts/bootstrap\' file which will set up your environment for this lane.'
    raise secrets_missing_message unless Pathname.new('../scripts/bootstrap').file?

    # get development certs and profiles
    match(
      app_identifier: app_id,
      username: "ios@diy.org",
      team_id: "6P7HTC8KL2",
      git_url: "git@github.com:diy/ios-certs-appstore.git",
      type: "development"
    )

    # get appstore certs and profiles
    match(
      app_identifier: app_id,
      username: "ios@diy.org",
      team_id: "6P7HTC8KL2",
      git_url: "git@github.com:diy/ios-certs-appstore.git",
      type: "appstore"
    )
  end

  private_lane :set_up_local_enterprise do |options|
    app_id = options[:app_id] || 'com.jam.ios-enterprise'
    # ensure the secrets file exists
    secrets_missing_message = 'You must create the \'set_secrets.sh\' file containing necessary environment variables to use this lane.'
    raise secrets_missing_message unless Pathname.new('scripts/set_secrets.sh').file?

    # get enterprise certs and profiles
    match(
      app_identifier: app_id,
      username: "ios@diy.org",
      team_id: "5YZ3NGWL6D",
      git_url: "git@github.com:diy/ios-certs-enterprise.git",
      type: "development"
    )

    match(
      app_identifier: app_id,
      username: "ios@diy.org",
      team_id: "5YZ3NGWL6D",
      git_url: "git@github.com:diy/ios-certs-enterprise.git",
      type: "enterprise"
    )
  end

  # Tear down
  after_all do |lane|
    notification(
      message: "Fastlane finished '#{lane}' successfully"
    )
  end

  error do |lane, exception|
    notification(
      message: "Fastlane '#{lane}' errored"
    )
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# app_identifier "com.jam.ios" # The bundle identifier of your app
apple_id "ios@diy.org" # Your Apple email address

team_id "6P7HTC8KL2"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-aws_s3 | 0.2.8   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| jwt                       | 1.5.6        |
| multi_json                | 1.12.1       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.13.7       |
| json                      | 2.1.0        |
| excon                     | 0.57.1       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| faraday_middleware        | 0.11.0.1     |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| jmespath                  | 1.3.1        |
| aws-sigv4                 | 1.0.0        |
| aws-sdk-core              | 2.10.9       |
| aws-sdk-resources         | 2.10.9       |
| aws-sdk                   | 2.10.9       |
| apktools                  | 0.7.2        |
| fastlane-plugin-aws_s3    | 0.2.8        |
</details>

*generated on:* **2017-07-12**
</details>

**Comment by KrauseFx** [comment]
_fastlane_ just forwards those calls directly to https://github.com/julienXX/terminal-notifier, maybe it's worth filing an issue there? Is that something you can change on your macOS maybe?

**Comment by eliotfowler** [comment]
@KrauseFx Thanks for the quick response! It turns out that I was mistaken and this is a system preference.

For any future people with the same issue, you can go to System Preferences > Notifications > terminal-notifier and change "Alerts" to "Banner" if you want the auto-dismiss behavior. Would be nice if this was configurable in the `terminal-notifier` gem, so I'll make an issue there.

Thanks again for the help @KrauseFx!

**Comment by KrauseFx** [comment]
Wohooo 👍
