### ISSUE TITLE
Is it possible to override a lane imported from git and pass options to it?

### ISSUE THREAD

**Issue by fcy** [fastlane/fastlane#974]
fastlane 1.46.1

I have a git repo with a shared Fastfile and I use `import_from_git` to get it and the custom actions. I'm wondering if it is possible to use `override_lane` and pass options to `super`. Example, in my "Super Fastfile"  I have this common lane:

```
  lane :unit_test do |options|
    scan_options = {
      scheme: options[:scheme],
      output_directory: "fastlane/test_output/unit",
      clean: true
    }

    if options[:device]
      scan_options[:device] = options[:device]
    end

    scan(scan_options)
  end
```

On each app that import this `Fastfile` I'd like to call `fastlane unit_test` without having to pass a scheme, so my thinking is that I should override the lane but I couldn't find anything about passing options to it.

Pseudo code of I want to do:
```
override_lane :unit_test do
  super(scheme: "My Specific App", device: "iPhone 6s")
end
```

Is it possible? Any other ways to accomplish this?

**Comment by KrauseFx** [comment]
You can override lanes (e.g. https://github.com/fastlane/pem/blob/master/fastlane/Fastfile#L4-L6) but can't call super. Instead the easiest way is just to have a separate lane you call from there

**Comment by KrauseFx** [comment]
Does that make sense?

**Comment by fcy** [comment]
I see. The "override" is misleading to me, it is actually a `overwrite_lane`. Any plans to implement an override OO style?

**Comment by KrauseFx** [comment]
No plans for it right now, sorry.

**Comment by fcy** [comment]
Ok, just curious.

**Comment by onmyway133** [comment]
@KrauseFx thanks, so https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Advanced.md

```ruby
import "../GeneralFastfile"

override_lane :from_general do
  ...
end
```

Here `override_lane` should just do its own thing 🎉
