### ISSUE TITLE
Hi, I have a problem with Maps automatically zooming to a point when running snapshot. When I run the UITest in Xcode the zooming works but not when running snapshot. 

### ISSUE THREAD

**Issue by Imrano10** [fastlane/fastlane#9740]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by KrauseFx** [comment]
You can see the commands _snapshot_ is using to run your UI Tests. I wonder if something is wrong with it? Otherwise, let me know how _snapshot_ should change to make it work for your use case
