### ISSUE TITLE
Error while running scan on Jenkins.

### ISSUE THREAD

**Issue by RishabhTayal** [fastlane/fastlane#9745]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Works fine on local machine. Fails when run on Jenkins server.

```
2017-07-13 13:38:24.851 xcodebuild[27056:33883811] Error Domain=com.apple.CoreSimulator.SimError Code=163 "Invalid device state" UserInfo={NSLocalizedDescription=Invalid device state, NSUnderlyingError=0x7f8d8cfd8990 {Error Domain=NSMachErrorDomain Code=-308 "(ipc/mig) server died"}}
2017-07-13 13:38:24.851 xcodebuild[27056:33883811] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
Test target MyTests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
[13:38:25]: Exit status: 65
```

I have the following line in my `Fastfile`.
`ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = '2'`

**Comment by PetrosIchor** [comment]
Similar issues posted with troubleshooting being discussed:

https://github.com/fastlane/fastlane/issues/6968

https://stackoverflow.com/q/34990175/7054813

https://medium.com/@greesce/xcode-framework-testing-headaches-c41db4004930

**Comment by RishabhTayal** [comment]
@PetrosIchor I looked into all three links and I added the `$(FRAMEWORK_SEARCH_PATHS)` in my test targets. I still keep getting same error while running `scan` on Jenkins.

**Comment by neHCuoHEpa** [comment]
I have the same issue, Im trying to find solution, but like @RishabhTayal I tried all of the fixes, but the error still appear. I found the app is install first time, but after that the error start to appear. For some reason the application cant be installed on the simulator.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-07-13**
</details>

**Comment by medcharla** [comment]
Even am running into this issue on fast lane. 
But this looks to be a bug with **Xcode 8.3.2** because running `xcodebuild` from command line on unit tests target is also failing intermittently with same error.

**Comment by RishabhTayal** [comment]
This error has now been occurring for 99% of the time I run `scan` on Jenkins.

**Comment by Antondomashnev** [comment]
The same issue for me.
The build fails is using scan:
```
Testing failed:
Test target MyTests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
[13:38:25]: Exit status: 65
```
And if I copy paste the `xcodebuild` command that scan generated - the tests run.

**Comment by mpirri** [comment]
@RishabhTayal have you tried removing the `FASTLANE_EXPLICIT_OPEN_SIMULATOR='2'` line (as @Antondomashnev did above)? Curious to see if that makes things work any better for you. 🚀

**Comment by RishabhTayal** [comment]
@mpirri I tried the `ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = '2'` option in my `Fastfile` (Also described in the description). Doesn't work. 

I believe I had 3 parallel builds enabled on my Jenkins server which might be causing this issue. I reduced the number of parallel builds to 2 now and I don't get the error while running `scan` anymore.

**Comment by mpirri** [comment]
Glad to hear it is working for you after that Jenkins change!

For what it is worth, the `FASTLANE_EXPLICIT_OPEN_SIMULATOR` environment variable only needs to be a `true`/`false` value ("2" is interpreted as `true`). Having this set might be causing the Simulator to be killed while running tests by a concurrent build happening at the same time, so if you have difficulty, definitely try the `false` setting.

**Comment by RishabhTayal** [comment]
Got it. What would be the interpretation for `false`?

**Comment by mpirri** [comment]
In this case `false` disables the explicit killing and launching of a new simulator before running the tests.

**Comment by RishabhTayal** [comment]
I mean in `Fastfile` what would I need to put for `false`? `ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = '1'`?

**Comment by mpirri** [comment]
You could either change it to `ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = 'false'` or just delete the line entirely (since the value defaults to `false`).

**Comment by RishabhTayal** [comment]
Cool. I think we can close this issue now. However I still think we should look into why `scan` fails when more than 2 jobs are enabled on Jenkins. The build fails even if only one job is running on Jenkins.

**Comment by Antondomashnev** [comment]
@RishabhTayal I'm curious how did you manage to have two parallel jobs on Jenkins as they both need the simulator? I mean if the first job requires iPhone 6 and the second iPad Air 2 for example, how they can work simultaneously?

**Comment by RishabhTayal** [comment]
That's a good question. I am not exactly sure how it was working but it recently started breaking.

**Comment by Antondomashnev** [comment]
From my experience we've dropped parallel jobs because there were plenty of build failures. But if it's not your case I will appreciate any knowledge sharing 😄

**Comment by MarkMolina** [comment]
I still have a problem and never added the line `FASTLANE_EXPLICIT_OPEN_SIMULATOR`. Getting the same issue though.

**Comment by joel-yc** [comment]
Adding: ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "0"  to 'before_all' in the Fastfile fixed this issue for me.
