### ISSUE TITLE
Actions::EnsureGitStatusCleanAction.run(nil) Crashes on Dirty Branch

### ISSUE THREAD

**Issue by alfonsol** [fastlane/fastlane#9747]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When calling Actions::EnsureGitStatusCleanAction.run(nil)  with a dirty branch, the error below occurs.   If the branch is clean, then everything is fine.

[12:41:04]: undefined method `[]' for nil:NilClass

##### Complete output when running fastlane, including the stack trace and command used
➜  ios_sdk_v3 git:(develop) ✗ fastlane ios create_release_branch
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
/Users/loper250/code/ios_sdk_v3/fastlane/actions/oneid_hockey.rb:10: warning: already initialized constant Fastlane::Actions::SharedValues::HOCKEY_DOWNLOAD_LINK
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/actions/hockey.rb:10: warning: previous definition of HOCKEY_DOWNLOAD_LINK was here
/Users/loper250/code/ios_sdk_v3/fastlane/actions/oneid_hockey.rb:11: warning: already initialized constant Fastlane::Actions::SharedValues::HOCKEY_BUILD_INFORMATION
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/actions/hockey.rb:11: warning: previous definition of HOCKEY_BUILD_INFORMATION was here
[12:41:04]: -------------------------------------------------
[12:41:04]: --- Step: Verifying required fastlane version ---
[12:41:04]: -------------------------------------------------
[12:41:04]: Your fastlane version 2.46.1 matches the minimum requirement of 2.0.0  ✅
[12:41:04]: ------------------------------
[12:41:04]: --- Step: default_platform ---
[12:41:04]: ------------------------------
[12:41:04]: ------------------------------
[12:41:04]: --- Step: default_platform ---
[12:41:04]: ------------------------------
[12:41:04]: ------------------------------
[12:41:04]: --- Step: default_platform ---
[12:41:04]: ------------------------------
[12:41:04]: ------------------------------
[12:41:04]: --- Step: default_platform ---
[12:41:04]: ------------------------------
[12:41:04]: ------------------------------
[12:41:04]: --- Step: default_platform ---
[12:41:04]: ------------------------------
[12:41:04]: Driving the lane 'ios create_release_branch' 🚀
[12:41:04]: ---------------------------------------
[12:41:04]: --- Step: create_new_release_branch ---
[12:41:04]: ---------------------------------------
[12:41:04]: here 1
[12:41:04]: $ git status --porcelain
[12:41:04]: ▸ M demo-app-objc/DemoAppObjC.xcodeproj/project.pbxproj
[12:41:04]: ▸ M demo-app-objc/DemoAppObjC.xcodeproj/xcshareddata/xcschemes/DemoAppObjC.xcscheme
[12:41:04]: ▸ M demo-app-objc/DemoAppObjC/BUDemoAppObjC.entitlements
[12:41:04]: ▸ M demo-app-objc/DemoAppObjC/Info.plist
[12:41:04]: ▸ M did-ios-core/DisneyID.xcodeproj/project.pbxproj
[12:41:04]: ▸ M fastlane/actions/create_new_release_branch.rb
[12:41:04]: ▸ M test-app-bucky/Bucky.xcodeproj/project.pbxproj
+------------------+---------------------------+
|                 Lane Context                 |
+------------------+---------------------------+
| DEFAULT_PLATFORM | ios                       |
| PLATFORM_NAME    | ios                       |
| LANE_NAME        | ios create_release_branch |
+------------------+---------------------------+
[12:41:04]: undefined method `[]' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
| 3    | default_platform                    | 0           |
| 4    | default_platform                    | 0           |
| 5    | default_platform                    | 0           |
| 6    | default_platform                    | 0           |
| 💥    | create_new_release_branch           | 0           |
+------+-------------------------------------+-------------+

[12:41:04]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  undefined method `fetch' for nil:NilClass in spaceship through deliver
    https://github.com/fastlane/fastlane/issues/9373 [closed] 4 💬
    5 weeks ago

➡️  fastlane pilot find: undefined method `length' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/8885 [closed] 1 💬
    15 hours ago

➡️  undefined method `[]' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/9087 [closed] 2 💬
    05 May 2017

and 258 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60[]'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/actions/ensure_git_status_clean.rb:18:in `run': [!] undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/loper250/code/ios_sdk_v3/fastlane/actions/create_new_release_branch.rb:19:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:78:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.46.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

I am not including that as it isn't allowed by company policy =-(.   The inclusion of our fastfile and action.rb files specifically.  My apologies.

**Comment by alfonsol** [comment]
Yeah, that was intentional. I'm not allowed to publish our fast file.

**Comment by KrauseFx** [comment]
Sorry, without the Fastfile we can't help. How do you call `ensure_git_status_clean`?
