### ISSUE TITLE
`pilot add` fails with "undefined method `email'"

### ISSUE THREAD

**Issue by ktraunmueller** [fastlane/fastlane#9754]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `fastlane pilot add` to add an external tester to iTunes Connect fails with an `undefined method` error:

```
$ fastlane pilot add ***@***.***
[11:17:28]: To not be asked about this value, you can specify it using 'username'
[11:17:28]: Your Apple ID Username: ****
[11:17:40]: Login to iTunes Connect (****)
[11:17:43]: Login successful
[11:17:47]: undefined method `email' for #<Spaceship::Tunes::Member:0x007faddd0e2d00>

[!] Some operations failed: undefined method `email' for #<Spaceship::Tunes::Member:0x007faddd0e2d00>
```

My iTC user has the `Developer` role.

A `fastlane pilot list` with the same environment works as expected (prints out internal and external testers).

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.1.0        |
| executable-hooks              | 1.3.2        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.4        |
| bundler                       | 1.15.1       |
| io-console                    | 0.4.6        |
| rake                          | 12.0.0       |
| curb                          | 0.9.3        |
| fastimage                     | 2.1.0        |
| CFPropertyList                | 2.3.5        |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.5.1        |
| babosa                        | 1.0.2        |
| colored                       | 1.2          |
| highline                      | 1.7.8        |
| commander-fastlane            | 4.4.5        |
| dotenv                        | 2.2.1        |
| excon                         | 0.57.1       |
| multipart-post                | 2.0.0        |
| faraday                       | 0.12.1       |
| unf_ext                       | 0.0.7.4      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20170404 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| faraday_middleware            | 0.11.0.1     |
| gh_inspector                  | 1.0.3        |
| jwt                           | 1.5.6        |
| little-plugger                | 1.1.4        |
| multi_json                    | 1.12.1       |
| logging                       | 2.2.2        |
| memoist                       | 0.16.0       |
| os                            | 0.9.6        |
| signet                        | 0.7.3        |
| googleauth                    | 0.5.1        |
| httpclient                    | 2.8.3        |
| mime-types-data               | 3.2016.0521  |
| mime-types                    | 3.1          |
| declarative                   | 0.0.9        |
| declarative-option            | 0.1.0        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.0.2        |
| google-api-client             | 0.12.0       |
| json                          | 2.1.0        |
| mini_magick                   | 4.5.1        |
| multi_xml                     | 0.6.0        |
| plist                         | 3.3.0        |
| rubyzip                       | 1.2.1        |
| security                      | 0.1.3        |
| slack-notifier                | 1.5.1        |
| terminal-notifier             | 1.8.0        |
| unicode-display_width         | 1.3.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.5.0        |
| word_wrap                     | 1.0.0        |
| claide                        | 1.0.2        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.2.3        |
| xcodeproj                     | 1.5.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.2.8        |
| xcpretty-travis-formatter     | 0.0.4        |
| badge                         | 0.8.4        |
| git                           | 1.3.0        |
| mini_portile2                 | 2.2.0        |
| nokogiri                      | 1.8.0        |
| xcode-install                 | 2.2.0        |
| commander                     | 4.4.3        |
| runtastic_iphone_provisioning | 0.1.7        |
| runtastic_devportal           | 0.1.1        |
| changelog                     | 1.0.0        |
| i18n                          | 0.8.6        |
| minitest                      | 5.10.2       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.3        |
| activesupport                 | 4.2.9        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| cocoapods-core                | 1.2.0        |
| cocoapods-deintegrate         | 1.0.1        |
| cocoapods-downloader          | 1.1.3        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-stats               | 1.0.0        |
| netrc                         | 0.7.8        |
| cocoapods-trunk               | 1.2.0        |
| cocoapods-try                 | 1.1.0        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.0.1        |
| molinillo                     | 0.5.7        |
| ruby-macho                    | 0.2.6        |
| cocoapods                     | 1.2.0        |
| cocoapods-simplifier          | 1.0.0        |
| cocoapods-run-scripts         | 1.0.1        |
| libxml-ruby                   | 3.0.0        |
| cocoapods-ack_filter          | 0.2.0        |
| cork                          | 0.3.0        |
| open4                         | 1.3.4        |
| claide-plugins                | 0.9.2        |
| faraday-http-cache            | 1.3.1        |
| kramdown                      | 1.14.0       |
| sawyer                        | 0.8.1        |
| octokit                       | 4.7.0        |
| danger                        | 4.3.5        |
| thor                          | 0.19.4       |
| danger-swiftlint              | 0.7.0        |
| danger-plugin-api             | 1.0.0        |
| danger-todoist                | 1.2.3        |
| runtastic-iphone-tools-danger | 0.1.0        |
</details>

*generated on:* **2017-07-14**
</details>

**Comment by KrauseFx** [comment]
Thanks for reporting this, could you run the same script again with the `--verbose` flag appended?

**Comment by ktraunmueller** [comment]
Here's the output with `verbose` turned on:
```
$ fastlane pilot add kat+itc@*********.com --verbose
Successfully loaded Appfile at path '/Users/ktraunmueller/Documents/sandbox/projects/*********/*********/fastlane/Appfile'
- app_identifier: '*********'
- team_name: '*********'
- team_id: '*********'
-------
Successfully loaded Appfile at path '/Users/ktraunmueller/Documents/sandbox/projects/*********/*********/fastlane/Appfile'
- app_identifier: '*********'
- team_name: '*********'
- team_id: '*********'
-------
Successfully loaded Appfile at path '/Users/ktraunmueller/Documents/sandbox/projects/*********/*********/fastlane/Appfile'
- app_identifier: '*********'
- team_name: '*********'
- team_id: '*********'
-------
Successfully loaded Appfile at path '/Users/ktraunmueller/Documents/sandbox/projects/*********/*********/fastlane/Appfile'
- app_identifier: '*********'
- team_name: '*********'
- team_id: '*********'
-------
Successfully loaded Appfile at path '/Users/ktraunmueller/Documents/sandbox/projects/*********/*********/fastlane/Appfile'
- app_identifier: '*********'
- team_name: '*********'
- team_id: '*********'
-------
Successfully loaded Appfile at path '/Users/ktraunmueller/Documents/sandbox/projects/*********/*********/fastlane/Appfile'
- app_identifier: '*********'
- team_name: '*********'
- team_id: '*********'
-------
WARN [2017-07-17 08:42:10.54]: To not be asked about this value, you can specify it using 'username'
 [2017-07-17 08:42:10.54]: Your Apple ID Username: kat@*********.com
INFO [2017-07-17 08:42:20.44]: Login to iTunes Connect (kat@*********.com)
Looking for iTunes Connect Team with ID ******
INFO [2017-07-17 08:42:26.49]: Login successful
ERROR [2017-07-17 08:42:34.17]: undefined method `email' for #<Spaceship::Tunes::Member:0x007ff621163720>
/Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [!] Some operations failed: undefined method `email' for #<Spaceship::Tunes::Member:0x007ff621163720> (FastlaneCore::Interface::FastlaneError)
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/pilot/lib/pilot/commands_generator.rb:38:in `handle_multiple'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/pilot/lib/pilot/commands_generator.rb:95:in `block (2 levels) in run'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/commander-4.4.3/lib/commander/command.rb:178:in `call'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/pilot/lib/pilot/commands_generator.rb:159:in `run'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/pilot/lib/pilot/commands_generator.rb:12:in `start'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/gems/fastlane-2.46.1/bin/fastlane:20:in `<top (required)>'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ktraunmueller/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mpirri** [comment]
@ktraunmueller Okay, I think I know what is going on here! `pilot` is crashing when trying to print out an error message. The crash is because we have an error in our code to print out your account's email address (see PR #9797 for the fix for this!).

BUT...  the real problem is that your account doesn't seem to have a role that is allowed to administer app testers. Here's the error message _fastlane_ is trying to print out when it crashes:
```
Account #{current_user.email} doesn't have a role that is allowed to administer app testers, current roles: #{current_user.roles}
```

Can you change the role of your account to allow it to administer testers?

I hope this is helpful - thanks!  🚀

**Comment by ktraunmueller** [comment]
@mpirri Thanks for investigating. I can confirm that a
 ```
$ fastlane pilot add ***@***.com --first_name Karl --last_name Tester
```
works as expected when my user has the "App Manager" role.
