### ISSUE TITLE
`pilot remove` fails with `user doesn't have enough permission for the following action: parse_response`

### ISSUE THREAD

**Issue by ktraunmueller** [fastlane/fastlane#9755]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running `fastlane pilot remove` to remove an external tester from iTunes Connect fails with `user doesn't have enough permission for the following action: parse_response`.

```
$ fastlane pilot remove ***@***.***
[11:19:33]: To not be asked about this value, you can specify it using 'username'
[11:19:33]: Your Apple ID Username: ****
[11:19:37]: Login to iTunes Connect (****)
[11:19:40]: Login successful
[11:19:41]: User **** (Team ID ***) doesn't have enough permission for the following action: parse_response

[!] Some operations failed: User ***@***.*** (Team ID ****) doesn't have enough permission for the following action: parse_response
```

My iTC user has the `Developer` role.

A `fastlane pilot list` with the same environment works as expected (prints out internal and external testers).

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             | 🚫 |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                           | Version      |
| ----------------------------- | ------------ |
| did_you_mean                  | 1.1.0        |
| executable-hooks              | 1.3.2        |
| bundler-unload                | 1.0.2        |
| rubygems-bundler              | 1.4.4        |
| bundler                       | 1.15.1       |
| io-console                    | 0.4.6        |
| rake                          | 12.0.0       |
| curb                          | 0.9.3        |
| fastimage                     | 2.1.0        |
| CFPropertyList                | 2.3.5        |
| public_suffix                 | 2.0.5        |
| addressable                   | 2.5.1        |
| babosa                        | 1.0.2        |
| colored                       | 1.2          |
| highline                      | 1.7.8        |
| commander-fastlane            | 4.4.5        |
| dotenv                        | 2.2.1        |
| excon                         | 0.57.1       |
| multipart-post                | 2.0.0        |
| faraday                       | 0.12.1       |
| unf_ext                       | 0.0.7.4      |
| unf                           | 0.1.4        |
| domain_name                   | 0.5.20170404 |
| http-cookie                   | 1.0.3        |
| faraday-cookie_jar            | 0.0.6        |
| faraday_middleware            | 0.11.0.1     |
| gh_inspector                  | 1.0.3        |
| jwt                           | 1.5.6        |
| little-plugger                | 1.1.4        |
| multi_json                    | 1.12.1       |
| logging                       | 2.2.2        |
| memoist                       | 0.16.0       |
| os                            | 0.9.6        |
| signet                        | 0.7.3        |
| googleauth                    | 0.5.1        |
| httpclient                    | 2.8.3        |
| mime-types-data               | 3.2016.0521  |
| mime-types                    | 3.1          |
| declarative                   | 0.0.9        |
| declarative-option            | 0.1.0        |
| uber                          | 0.1.0        |
| representable                 | 3.0.4        |
| retriable                     | 3.0.2        |
| google-api-client             | 0.12.0       |
| json                          | 2.1.0        |
| mini_magick                   | 4.5.1        |
| multi_xml                     | 0.6.0        |
| plist                         | 3.3.0        |
| rubyzip                       | 1.2.1        |
| security                      | 0.1.3        |
| slack-notifier                | 1.5.1        |
| terminal-notifier             | 1.8.0        |
| unicode-display_width         | 1.3.0        |
| terminal-table                | 1.8.0        |
| tty-screen                    | 0.5.0        |
| word_wrap                     | 1.0.0        |
| claide                        | 1.0.2        |
| colored2                      | 3.1.2        |
| nanaimo                       | 0.2.3        |
| xcodeproj                     | 1.5.0        |
| rouge                         | 2.0.7        |
| xcpretty                      | 0.2.8        |
| xcpretty-travis-formatter     | 0.0.4        |
| badge                         | 0.8.4        |
| git                           | 1.3.0        |
| mini_portile2                 | 2.2.0        |
| nokogiri                      | 1.8.0        |
| xcode-install                 | 2.2.0        |
| commander                     | 4.4.3        |
| runtastic_iphone_provisioning | 0.1.7        |
| runtastic_devportal           | 0.1.1        |
| changelog                     | 1.0.0        |
| i18n                          | 0.8.6        |
| minitest                      | 5.10.2       |
| thread_safe                   | 0.3.6        |
| tzinfo                        | 1.2.3        |
| activesupport                 | 4.2.9        |
| fuzzy_match                   | 2.0.4        |
| nap                           | 1.1.0        |
| cocoapods-core                | 1.2.0        |
| cocoapods-deintegrate         | 1.0.1        |
| cocoapods-downloader          | 1.1.3        |
| cocoapods-plugins             | 1.0.0        |
| cocoapods-search              | 1.0.0        |
| cocoapods-stats               | 1.0.0        |
| netrc                         | 0.7.8        |
| cocoapods-trunk               | 1.2.0        |
| cocoapods-try                 | 1.1.0        |
| escape                        | 0.0.4        |
| fourflusher                   | 2.0.1        |
| molinillo                     | 0.5.7        |
| ruby-macho                    | 0.2.6        |
| cocoapods                     | 1.2.0        |
| cocoapods-simplifier          | 1.0.0        |
| cocoapods-run-scripts         | 1.0.1        |
| libxml-ruby                   | 3.0.0        |
| cocoapods-ack_filter          | 0.2.0        |
| cork                          | 0.3.0        |
| open4                         | 1.3.4        |
| claide-plugins                | 0.9.2        |
| faraday-http-cache            | 1.3.1        |
| kramdown                      | 1.14.0       |
| sawyer                        | 0.8.1        |
| octokit                       | 4.7.0        |
| danger                        | 4.3.5        |
| thor                          | 0.19.4       |
| danger-swiftlint              | 0.7.0        |
| danger-plugin-api             | 1.0.0        |
| danger-todoist                | 1.2.3        |
| runtastic-iphone-tools-danger | 0.1.0        |
</details>

*generated on:* **2017-07-14**
</details>

**Comment by KrauseFx** [comment]
When does this happen, and when https://github.com/fastlane/fastlane/issues/9754?

**Comment by ktraunmueller** [comment]
Both issues popped up while trying to automate our Testflight tester management with fastlane (using the same iTC account with a `Developer` role). So, sorry, I can't offer more specifics at this point.

**Comment by mpirri** [comment]
@ktraunmueller Are you able to use your account with `developer` role to add testers on the iTunesConnect portal? Trying to understand if this problem is being caused by an issue on iTunesConnect's backend, or somewhere in `pilot`.

Thanks much! 🚀

**Comment by ktraunmueller** [comment]
@mpirri Well, duh, actually no. *slaps forehead*

I tried with the "App Manager" role, and that works as expected. A better error message would be helpful, though. 

Thanks for investigating!

**Comment by mpirri** [comment]
So, I notice you are not specifying an app identifier with this call.  To use App Manager, you have to specify the actual application you want to remove the tester from. Not specifying an app means remove the global tester, which is not allowed by App Manager.  Try including `-a <app_identifier>` on this call, or else bump your role up to `admin`.

Incidentally: what a frustrating error message!  We are like 0 for 2 with useful error messages for your issues! `parse_response` is definitely not what we want top be showing here - we are supposed to show the name of the actual API call we are making that got this error. 😠   I'll see what we can do to clean this up a bit.

**Comment by ktraunmueller** [comment]
Getting closer, adding testers now works for me (App Manager role).

What's unexpected is that I can delete a tester in iTunes Connect (Web), but `fastlane pilot remove` fails with `insufficient privileges` (all using the same user):

```
$ fastlane pilot remove ***+test@****.com --app_identifier **** --username ***@****.com
Login to iTunes Connect (***@****.com)
Login successful
{"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["insufficient privileges"]}, "statusCode"=>"ERROR"}

[!] Some operations failed: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["insufficient privileges"]}, "statusCode"=>"ERROR"}
```

And thanks for looking into the error reporting 👍
