### ISSUE TITLE
Feature request: Invite new iTC and Dev Portal users via fastlane or Spaceship

### ISSUE THREAD

**Issue by stevekohls** [fastlane/fastlane#9759]
Feature request:

I would like the ability to invite new Developer Portal and iTunes Connect users via fastlane or Spaceship. Currently, the tools only support adding TestFlight users.

We have a unique situation in which we would like to add a common user to a large number of customer iTunes Connect and Developer Portal accounts. Automating this would be _really_ helpful.

If you can offer pointers on how/where to add this functionality to Spaceship, we may be able to take on the development effort. No promises 😀

**Comment by stevekohls** [comment]
@mpirri Thanks for the help!

I've written a bunch of code that users Spaceship already, so this puts me on the right track.

It looks like the `invite` method in `spaceship/portal/persons.rb` and `create` in `spaceship/tunes/members.rb` does what I need.

**Comment by KrauseFx** [comment]
Yeah, thanks to the awesome @hjanuschka, this works now 👍
