### ISSUE TITLE
Precheck reports other_platforms violation for partial matches

### ISSUE THREAD

**Issue by FelixII** [fastlane/fastlane#9761]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [x ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm using the German word "Notizen" (notes) in my app description and get a platform violation for "tizen". It would be great if precheck could avoid this match or at least let me configure a whitelist.

This issue relates to #9567, not sure if it is exactly the same problem.

##### Complete output when running fastlane, including the stack trace and command used

    $ fastlane precheck
    [17:16:56]: Successfully loaded '/Users/xxx/Developer/xxx/fastlane/Precheckfile' 📄
    [17:16:56]: No values defined in './fastlane/Precheckfile'
    
    +--------------------+----------------------------+
    |           Summary for precheck 2.46.1           |
    +--------------------+----------------------------+
    | app_identifier     | xxx                        |
    | username           | xxx                        |
    | default_rule_level | error                      |
    +--------------------+----------------------------+
    
    [17:16:56]: Starting login with user 'xxx'
    [17:16:59]: Successfully logged in
    [17:16:59]: Checking app for precheck rule violations
    [17:17:07]: ✅  Passed: No negative  sentiment
    [17:17:07]: ✅  Passed: No placeholder text
    [17:17:07]: 😵  Failed: No mentioning  competitors-> mentioning other platforms, like Android or Blackberry
    [17:17:07]: ✅  Passed: No future functionality promises
    [17:17:07]: ✅  Passed: No words indicating test content
    [17:17:07]: ✅  Passed: No curse words
    [17:17:07]: ✅  Passed: Incorrect, or missing copyright date
    [17:17:10]: ✅  Passed: No broken urls
    +----------------------+----------------+
    |          Potential problems           |
    +----------------------+----------------+
    | Field                | Failure reason |
    +----------------------+----------------+
    | keywords: (de-DE)    | found: tizen   |
    | description: (de-DE) | found: tizen   |
    | app name: (de-DE)    | found: tizen   |
    +----------------------+----------------+
    
    [!] precheck found one or more potential problems that must be addressed before submitting to review

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F2104)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "xxx" # The bundle identifier of your app
apple_id "xxx" # Your Apple email address

# You can uncomment any of the lines below and add your own
# team selection in case you're in multiple teams
# team_name "Felix Krause"
# team_id "Q2CBPJ58CA"


# you can even provide different app identifiers, Apple IDs and team names per lane:
# https://github.com/KrauseFx/fastlane/blob/master/docs/Advanced.md#the-appfile
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-07-14**
</details>

**Comment by taquitos** [comment]
Whoops. Yeah, that's not good.
