### ISSUE TITLE
Empty metadata files should not overwrite iTunes Connect content

### ISSUE THREAD

**Issue by erwinmaza** [fastlane/fastlane#9764]
Use case: 

1. user has entered metadata (keywords, support/marketing urls, description, etc) directly into iTunes Connect for their app.
1. user decides to try fastlane. Downloads, installs, reads the docs, inits for their app
1. user does not bother with fastlane/metadata/ files, since that's already been done in Connect
1. user ignores precheck missing data warnings. Again, that data is already in iTunes
1. user runs the deliver command
1. user finds all their metadata is gone, and is upset

Feature Request / Fix:

When a metadata file is empty, do not upload the empty contents and destroy the user's data. Instead, download any existing iTunes Connect data and write it into the empty file.

Weak fixes:
- Add a WARNING to the preview.html at every blank metadata field warning the empty string will overwrite any existing data.
- Add a DATA DESTRUCTION note to precheck warnings when metadata is empty

**Comment by erwinmaza** [comment]
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.5                                          |
| Ruby                        | 2.2.4                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.11.0 (Apple Git-81)                |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane              |
| Host                        | Mac OS X 10.12.5 (16F73)                         |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                       |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                       |
| Is contained                | true                                             |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Apps/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                            |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.44.1"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.emazamobile.batterywatcher" # The bundle identifier of your app
apple_id "erwin@emazamobile.com" # Your Apple email address

team_id "3J4WM73YC7" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-07-14**
</details>

**Comment by KrauseFx** [comment]
I agree, that shouldn't happen, and I thought that it doesn't happen. Are you sure those files were empty, and didn't have a white space (space or new line) in them?

**Comment by erwinmaza** [comment]
Pretty sure, because I didn't go looking for them, and hadn't touched them with my text editor until I noticed my metadata on iTunes Connect was gone.

**Comment by erwinmaza** [comment]
I have verified that the empty files included in fastlane by default do in fact have a line break in them. 

The untouched `review_information` files were still overwriting/removing my data in iTunes Connect. When I opened the files in Sublime Text, they had 2 blank lines in them.

Perhaps the fix is to treat whitespace-only files as empty, maybe by trimming whitespace characters from both ends of the "content" as a first step.

**Comment by mpirri** [comment]
@erwinmaza Awesome information! By any chance, did you confirm that deleting those whitespace characters from the empty metadata files and then running `deliver` does NOT overwrite your iTC information? If you have not, I totally understand, but if you have, it would be a useful data point for us to have before making the exact change you describe above.

Thanks again for the info!  🚀

**Comment by erwinmaza** [comment]
Nope, sorry, I didn’t try that. Thanks for taking a look at this. 

Regards, 
Erwin
