### ISSUE TITLE
Unable to specify devices with parentheses in name

### ISSUE THREAD

**Issue by mbopp** [fastlane/fastlane#9765]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When specifying a device with `(` `)` in it, it seems to have difficulty parsing it correctly.  In my case, the default is also failing because it is selecting an iPhone device for a project that is for **iPad** only.  

This could be related, but now iPad devices have the size in parentheses.  So the device specification for the pro might be `iPad Pro (9.7) (10.3.1)`. 

The output provided from the device being put in the scanfile.  But I have tested with the cli args and get the same result, fwiw.

_I am able to work around the issue by specifying the device `iPad Air` w/out the version in `()`._

```
→ fastlane scan 
[15:35:48]: Successfully loaded '/Users/mbopp/Projects/apps/AlphaRecycling/fastlane/Scanfile' 📄

+----------------------+---------------------+
| Detected Values from './fastlane/Scanfile' |
+----------------------+---------------------+
| scheme               | AlphaRecycling      |
| device               | iPad Air (10.3.1)   |
| clean                | true                |
+----------------------+---------------------+

[15:35:48]: $ xcodebuild -list -project ./AlphaRecycling.xcodeproj
[15:35:49]: $ xcodebuild -showBuildSettings -scheme AlphaRecycling -project ./AlphaRecycling.xcodeproj
[15:35:51]: No simulators found that are equal to the version of specifier (10.3.1) and greater than or equal to the version of deployment target (0)
[15:35:51]: Ignoring 'iPad Air (10.3.1)', couldn’t find matching simulator
[15:35:51]: Couldn't find any matching simulators for '["iPad Air (10.3.1)"]' - falling back to default simulator
[15:35:51]: Found simulator "iPhone 5 (10.3)"

+------------------------+--------------------------------------+
|                    Summary for scan 2.46.1                    |
+------------------------+--------------------------------------+
| scheme                 | AlphaRecycling                       |
| device                 | iPad Air (10.3.1)                    |
| clean                  | true                                 |
| project                | ./AlphaRecycling.xcodeproj           |
| derived_data_path      | /Users/mbopp/Library/Developer/Xcod  |
|                        | e/DerivedData/AlphaRecycling-fffyui  |
|                        | kuqmincibmxamzybwccncx               |
| skip_build             | false                                |
| output_directory       | ./fastlane/test_output               |
| output_types           | html,junit                           |
| buildlog_path          | ~/Library/Logs/scan                  |
| include_simulator_logs | false                                |
| open_report            | false                                |
| skip_slack             | false                                |
| slack_only_on_failure  | false                                |
| use_clang_report_name  | false                                |
| xcode_path             | /Applications/Xcode.app              |
+------------------------+--------------------------------------+

[15:35:51]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme AlphaRecycling -project ./AlphaRecycling.xcodeproj -destination 'platform=iOS Simulator,id=C7435628-8CF8-47F2-9023-D238F0E5108D' -derivedDataPath '/Users/mbopp/Library/Developer/Xcode/DerivedData/AlphaRecycling-fffyuikuqmincibmxamzybwccncx' clean build test | tee '/Users/mbopp/Library/Logs/scan/AlphaRecycling-AlphaRecycling.log' | xcpretty  --report html --output '/Users/mbopp/Projects/apps/AlphaRecycling/fastlane/test_output/report.html' --report junit --output '/Users/mbopp/Projects/apps/AlphaRecycling/fastlane/test_output/report.junit' --report junit --output '/var/folders/jc/b2cx5hdj5dd4_h4tzhjz4zyh0000gn/T/junit_report20170714-4332-1q12qx9'
[15:35:51]: ▸ Loading...
[15:35:52]: ▸ xcodebuild: error: Unable to find a destination matching the provided destination specifier:
[15:35:52]: ▸ { platform:iOS Simulator, id:C7435628-8CF8-47F2-9023-D238F0E5108D }
[15:35:52]: ▸ Available destinations for the "AlphaRecycling" scheme:
[15:35:52]: ▸ { platform:iOS Simulator, id:F1CB8322-D272-4767-AE49-A8B5D98517BD, OS:10.3.1, name:iPad (5th generation) }
[15:35:52]: ▸ { platform:iOS Simulator, id:18594C57-7846-43E1-88F9-455FFF3F07B8, OS:10.3.1, name:iPad Air }
[15:35:52]: ▸ { platform:iOS Simulator, id:B84E3C97-8E9C-43E1-85E9-3936B6793C44, OS:10.3.1, name:iPad Air 2 }
[15:35:52]: ▸ { platform:iOS Simulator, id:D5139A65-C186-4CBC-9AFD-BE7C28CFC414, OS:10.3.1, name:iPad Pro (9.7 inch) }
[15:35:52]: ▸ { platform:iOS Simulator, id:5EBF558E-3468-49FF-9849-19D6CBC5E323, OS:10.3.1, name:iPad Pro (10.5-inch) }
[15:35:52]: ▸ { platform:iOS Simulator, id:10EEF1A7-3485-4C12-8A66-0B3F8CB2C911, OS:10.3.1, name:iPad Pro (12.9 inch) }
[15:35:52]: ▸ { platform:iOS Simulator, id:342E42EE-6FC7-4455-B75A-D972103F25F7, OS:10.3.1, name:iPad Pro (12.9-inch) (2nd generation) }
[15:35:52]: ▸ Ineligible destinations for the "AlphaRecycling" scheme:
[15:35:52]: ▸ { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
[15:35:52]: ▸ { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
xcodebuild: error: Unable to find a destination matching the provided destination specifier:
{ platform:iOS Simulator, id:C7435628-8CF8-47F2-9023-D238F0E5108D }

Available destinations for the "AlphaRecycling" scheme:
{ platform:iOS Simulator, id:F1CB8322-D272-4767-AE49-A8B5D98517BD, OS:10.3.1, name:iPad (5th generation) }
{ platform:iOS Simulator, id:18594C57-7846-43E1-88F9-455FFF3F07B8, OS:10.3.1, name:iPad Air }
{ platform:iOS Simulator, id:B84E3C97-8E9C-43E1-85E9-3936B6793C44, OS:10.3.1, name:iPad Air 2 }
{ platform:iOS Simulator, id:D5139A65-C186-4CBC-9AFD-BE7C28CFC414, OS:10.3.1, name:iPad Pro (9.7 inch) }
{ platform:iOS Simulator, id:5EBF558E-3468-49FF-9849-19D6CBC5E323, OS:10.3.1, name:iPad Pro (10.5-inch) }
{ platform:iOS Simulator, id:10EEF1A7-3485-4C12-8A66-0B3F8CB2C911, OS:10.3.1, name:iPad Pro (12.9 inch) }
{ platform:iOS Simulator, id:342E42EE-6FC7-4455-B75A-D972103F25F7, OS:10.3.1, name:iPad Pro (12.9-inch) (2nd generation) }

Ineligible destinations for the "AlphaRecycling" scheme:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Generic iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Generic iOS Simulator Device }
[15:35:52]: Exit status: 70

[!] Error building/testing the application - see the log above
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.2                          |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.46.1"
REQUIRED_XCODE_VERSION = "8.3.3"
default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
   increment_build_number 
    
  end

  private_lane :verify_xcode_version do
    # ensure_xcode_version(version: REQUIRED_XCODE_VERSION)
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  lane :cart do |options|
    verify_xcode_version

    carthage(
      command: options[:update] ? "update" : "bootstrap",
      platform: "iOS",
      use_binaries: false
    )
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end


end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.alphaassembly.AlphaRecycling" # The bundle identifier of your app
apple_id "mike@boppweb.com" # Your Apple email address

team_id "5929P63984" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-07-14**
</details>

**Comment by mpirri** [comment]
@mbopp Hey, do you mind sending along a copy of your `Scanfile`? Just trying to make sure we can reproduce the problem you are seeing here. Thanks much!

**Comment by mbopp** [comment]
Sure, something like this...

```
scheme "AlphaRecycling"

device "iPad Pro (9.7) (10.3.1)"
```

**Comment by mpirri** [comment]
We have an awesome PR from a contributor to fix this issue, are you interested in testing it for us? If so you, can find the PR at: https://github.com/fastlane/fastlane/pull/9822

Thanks again for your report! 🚀
