### ISSUE TITLE
Is it possible to (re)sign ipa files on Linux?

### ISSUE THREAD

**Issue by Yaldo425** [fastlane/fastlane#9770]
Is it possible to (re)sign an IPA using fastlane on a Linux platform? I searched the docs and looked at some issues but I could not find an exact answer. I tried running `fastlane sigh resign`
and get prompted for a path to an IPA file and after providing one I get this error:
```

/var/lib/gems/2.1.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/usr/lib/ruby/2.1.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[04:47:53]: No such file or directory - xcode-select
[04:47:53]: Path to ipa file: x.html

[04:48:00]: Error accessing file, this might be due to fastlane's directory handling
[04:48:00]: Check out https://docs.fastlane.tools/advanced/#directory-behavior for more details

/var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:186:in ``': No such file or directory - security (Errno::ENOENT)
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:186:in `request_valid_identities'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:170:in `installed_identities'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:191:in `installed_identity_descriptions'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:160:in `print_available_identities'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:164:in `ask_for_signing_identity'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:72:in `get_inputs'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/resign.rb:8:in `run'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/commands_generator.rb:102:in `block (2 levels) in run'
	from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /var/lib/gems/2.1.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/commands_generator.rb:123:in `run'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /var/lib/gems/2.1.0/gems/fastlane-2.46.1/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'



```

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | debian_based 8.0                                     |
| Ruby                        | 2.1.5                                                |
| Bundler?                    | false                                                |
| Git                         | git version 2.1.4                                    |
| Installation Source         | /usr/local/bin/fastlane                              |
| Host                        | Debian GNU/Linux 8 debian_based 8.0 (3.16.0-4-amd64) |
| Ruby Lib Dir                | /usr/lib                                             |
| OpenSSL Version             | OpenSSL 1.0.1t  3 May 2016                           |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf                       | 0.2.0.beta2  |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| io-console                | 0.4.2        |
</details>

*generated on:* **2017-07-16**
</details>

**Comment by mpirri** [comment]
Unfortunately, no, it is not possible to re-sign a binary on Linux. The necessary Xcode tools are missing on the platform to do the file encryption (not to mention there is no keychain to store the keys, etc). However, the tools should probably fail earlier in the process, rather than ask for the IPA path, and give the user false hope. Thanks for the report! 🚀
