### ISSUE TITLE
Repeated login to dev center for every task in a single lane

### ISSUE THREAD

**Issue by bhimsenpadalkar** [fastlane/fastlane#9774]
### Issue Description
In a single lane inside fastfile, if you have multiple tasks, fastlane logins for every task.

e.g. If Fastfile looks like
produce(...)
match(...)
sigh(...)

Then for each task, fastlane logs in to dev center which seems unnecessary and costs around 8-10 seconds for each login. 

Proposed solution:
Login only at the start of the lane, and logout at the end..

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
lane :setup_apps do |options|
  apps = JSON.parse(options[:apps])

  all_app_groups = apps.map{|app| app['app_groups']}.flatten.uniq
  all_app_groups.each{|app_group| system "fastlane produce group -g #{app_group}"}
  apps.each { |app|
    services = {}
    app['services'].each{|service| services[service] = "on"}

    produce(
      app_name: app['name'],
      app_identifier: app['bundle_id'],
      skip_itc: true,
      enable_services: services
    )
    app['app_groups'].each{|group| system "fastlane produce associate_group -a #{app['bundle_id']} #{group}"} if app['app_groups']
  }
end

lane :install_signing_assets do |options|
  apps = JSON.parse(options[:apps])
  match(
    type: "adhoc",
    readonly: true,
    clone_branch_directly: true
  )
  apps.each{|app| app['bundle_ids'].each{|bundle_id|
    sigh(
      app_identifier: bundle_id,
      adhoc: true,
      force: true,
    )
  }}
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.1       |
| io-console                | 0.4.5        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| colorize                  | 0.8.1        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| netrc                     | 0.11.0       |
| rest-client               | 2.0.2        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-07-17**
</details>

**Comment by mpirri** [comment]
Awesome idea! Yeah, each _fastlane_ tool is responsible for managing access to the dev portal and there is no sharing of this context between the tools.

At the moment this isn't something we are planning on building, but it is a logical next step to make the tools work well together. We're always looking for amazing PRs from our open-source community, so if you feel so inclined, feel free to take a stab at building this. Let us know if there is any info or context we can add to help you out with it.

Thanks again for the great idea! 🚀
