### ISSUE TITLE
Upload App Preview

### ISSUE THREAD

**Issue by tbaranes** [fastlane/fastlane#9775]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm currently searching how to automate app previews upload, but I can't find it by reading previous issues / documentation. In the end, I'm not sure if fastlane is handling it or not. Reading #9532, I think it is, but I didn't find any documentation about it.

So, the question is simply: is it possible to upload app preview using fastlane? 

Thanks!

**Comment by pedrodelavega** [comment]
https://github.com/fastlane/fastlane/issues/9532

**Comment by tbaranes** [comment]
@pedrodelavega I read this, but can't find anywhere how to use this :(
I mean, is there a line for this, which one? It should definitely be documented

**Comment by mpirri** [comment]
@tbaranes Agreed that we need to document how to do this, but as mentioned in #9532 and #9660, the current implementation of this feature in _fastlane_ is broken (and crashing) currently. When we have a working solution, we will be sure to update the documentation as part of the release process.

Thanks for the report and I'm sorry that we don't have better news for you. 🚀

**Comment by air720boarder** [comment]
Any updates on previews being supported? With iOS11 on the horizon they seem more important than ever to include.

**Comment by runloop** [comment]
Any news with this? As mentioned above, iOS 11 is putting greater emphasis on App Previews. I have 11 languages and previews for all device sizes. The thought of uploading all these via iTunesConnect is not a pleasant one.

**Comment by tbaranes** [comment]
I saw that #10546 has been merged an release, is there any documentation about it yet?

**Comment by pedrodelavega** [comment]
@tbaranes  It seems that to upload previews, it's not as simple as using Deliver. I dig a little bit and apparently you can do it using `upload_trailer!(trailer_path, language, device, timestamp = "05.00", preview_image_path = nil) ` which is a method inside the spaceship module. You can use Spaceship API manually if you use the command `fastlane spaceship` (more on this [there](https://github.com/fastlane/fastlane/blob/master/spaceship/docs/iTunesConnect.md)). Of course, the goal is to automatize uploading which can be done using Fastlane for sure... but I don't know how to do it yet...

**Comment by tbaranes** [comment]
I don't think that issue is solved even if @pedrodelavega's answer is helping. That feature still need real documentation.

**Comment by cherpake** [comment]
So I was able to hack (I don't know Ruby) this, to fetch some values automatically from the config files

     


    def self.run(options)
		options = {}
		options[:username] ||= CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
		options[:app_identifier] ||= CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)

		UI.message("Login to iTunes Connect (#{options[:username]})")
		Spaceship::Tunes.login(options[:username])
		Spaceship::Tunes.select_team
		UI.message("Login successful")

		app = Spaceship::Tunes::Application.find(options[:app_identifier])
		options[:app] = app
			  
		FastlaneCore::PrintTable.print_values(config: options, hide_keys: [:app], mask_keys: ['app_review_information.demo_password'], title: "deliver #{Fastlane::VERSION} Summary")
    	  
	    details = app.details
		ver = app.edit_version(platform: options[:platform])
		vid = File.join(Helper.fastlane_enabled_folder_path, 'app_preview.mp4')
		img = File.join(Helper.fastlane_enabled_folder_path, 'app_preview.jpg')
		
		UI.message("Uploading (#{vid})....") 		
		englishTrailersLang = ["da","de-DE","el","en-AU","en-CA","en-GB","en-US","es-ES","es-MX","fi","fr-CA","fr-FR","id","it","ja","ko","ms","nl-NL","no","pt-BR","pt-PT","ru","sv","th","tr","vi","zh-Hans","zh-Hant"]
	    englishTrailersLang.each do |lang|
	        puts "Uploading app preview for #{lang}..."
    	    ver.upload_trailer!(vid, 1, lang, "iphone6Plus", "09.00", img)
    	    puts "Done uploading app preview for #{lang}..."
	    end

        puts "Saving..."
        ver.save!
        puts "Done!"

      end

**Comment by croberts22** [comment]
Does this get any easier now that Apple has announced support with uploading app previews on `transporter`? 

https://developer.apple.com/news/?id=01312018a

**Comment by tbaranes** [comment]
I do think that still an interesting issue 😶
