### ISSUE TITLE
couldn't find HOME environment -- expanding `~'

### ISSUE THREAD

**Issue by KOmyself** [fastlane/fastlane#9776]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

```
[17:26:08]: [32m--- Step: gym ---[0m
[17:26:08]: [32m-----------------[0m
[17:26:08]: [4m[36m$ xcodebuild -list -project WXImagePreview/WXImagePreview.xcodeproj -configuration Release[0m[0m
[17:26:09]: [4m[36m$ xcodebuild clean -showBuildSettings -scheme WXImagePreview -project WXImagePreview/WXImagePreview.xcodeproj -configuration Release[0m[0m
+------------------+------------------------+
|               [33mLane Context[0m                |
+------------------+------------------------+
| DEFAULT_PLATFORM | ios                    |
| PLATFORM_NAME    | ios                    |
| LANE_NAME        | ios Archive_Enterprise |
| VERSION_NUMBER   | 1.0.0                  |
| BUILD_NUMBER     | 201707171725           |
+------------------+------------------------+
[17:26:10]: [31mcouldn't find HOME environment -- expanding `~'[0m

+------+------------------------+-------------+
|              [32mfastlane summary[0m               |
+------+------------------------+-------------+
| Step | Action                 | Time (in s) |
+------+------------------------+-------------+
| 1    | Verifying required     | 0           |
|      | fastlane version       |             |
| 2    | default_platform       | 0           |
| 3    | update_app_identifier  | 0           |
| 4    | increment_version_num  | 0           |
|      | ber                    |             |
| 5    | increment_build_numbe  | 1           |
|      | r                      |             |
| 6    | update_project_team    | 0           |
| 7    | update_project_provis  | 0           |
|      | ioning                 |             |
| 💥   | [31mgym[0m                    | 1           |
+------+------------------------+-------------+

[17:26:10]: [31mfastlane finished with errors[0m

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mSpaceship cookie path selection fails when no HOME environment variable is set[0m
    https://github.com/fastlane/fastlane/issues/8465 [[32mclosed[0m] 4 💬
    4 weeks ago

➡️  [33mspaceship selects cookie path from set of preferred[0m
    https://github.com/fastlane/fastlane/pull/6759 [[32mclosed[0m] 19 💬
    6 weeks ago

➡️  [33mScreengrab doesn't work with core 0.41[0m
    https://github.com/fastlane/fastlane/issues/4008 [[32mclosed[0m] 4 💬
    15 Nov 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
cp: ./build/: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    91  100    91    0     0   4942      0 --:--:-- --:--:-- --:--:--  5055
{"meta":{"code":0,"message":"\u4fee\u6539\u5b8c\u6210","timestamp":1500283571460},"data":1}Success,output road path is：/Library/WebServer/Documents/toonstore/public/sh/ios/v/49/1.1/build/Release-iphoneos
/Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/gym/lib/gym/detect_values.rb:38:in `expand_path': [31m[!] couldn't find HOME environment -- expanding `~'[0m (ArgumentError)
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/gym/lib/gym/detect_values.rb:38:in `archive_path_from_local_xcode_preferences'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/gym/lib/gym/detect_values.rb:31:in `set_additional_default_values'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/gym/lib/gym.rb:25:in `config='
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/gym/lib/gym/manager.rb:4:in `work'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/actions/gym.rb:50:in `run'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:89:in `generate_ipa'
	from Fastfile:164:in `block (2 levels) in parsing_binding'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/syswin/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/fastlane-2.46.1/bin/fastlane:20:in `<top (required)>'
	from /Users/syswin/.fastlane/bin/bundle/bin/fastlane:22:in `load'
	from /Users/syswin/.fastlane/bin/bundle/bin/fastlane:22:in `<main>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12                                       |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12 (16A323)                     |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.46.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-07-17**
</details>

**Comment by ohayon** [comment]
Hey @KOmyself - are you still running into this issue? Apologies for the delay in responding to you! 👍
