### ISSUE TITLE
Action to run app in iOS simulator

### ISSUE THREAD

**Issue by 7mllm7** [fastlane/fastlane#978]
Working with QA people, I find it useful to enable them to run the app straight from source code, on the iOS simulator. This way it's easier for them to do some manual QA by simulating different devices and iOS versions.

Need we an action like that?
Options:
* Implement by myself.
* Use https://github.com/phonegap/ios-sim and just integrate it into fastlane.
* Use https://github.com/appcelerator/ioslib and integrate into fastlane.

Would like to hear what you think...

**Comment by KrauseFx** [comment]
I'd much rather prefer this to be implemented in Ruby as one of the fastlane actions. If you want to work on it :+1: 

Let me know if you need any help getting started

**Comment by 7mllm7** [comment]
Hi,

So I've created this pull request:
https://github.com/fastlane/fastlane/pull/1032

Please let me know what you think...

**Comment by jcampbell05** [comment]
You guys should check out Facebook's Implementation of a tool to do this https://github.com/facebook/FBSimulatorControl

**Comment by asfalcone** [comment]
I'm going to close this issue because the associated PR was also closed as we decided not to merge it.
