### ISSUE TITLE
Fastlane Pilot able to define Export Compliance metadata for beta build review?

### ISSUE THREAD

**Issue by jvanlint** [fastlane/fastlane#9788]
When deploying an app using Deliver you are able to specify a text file with export compliance metadata to get through a submission hurdle.

Does this same functionality exist in Pilot?

 I recently uploaded a test build using Pilot and it would not go into review status until i answered a question about Export Compliance encryption in the Connect portal.

**Comment by PetrosIchor** [comment]
Not sure about pilot, but you just need to add `<key>ITSAppUsesNonExemptEncryption</key><false/>` to your projects plist to bypass that step in submission.  

If your projects too dynamic to hardcoded that in, you can always add a step before building to inject the value based on conditions.

**Comment by mpirri** [comment]
@jvanlint Currently `pilot` cannot set `export_compliance` via an option, so you should use the Info.plist approach that @PetrosIchor recommends above. Please let us know if you have any difficulties with this approach or if you have any other _fastlane_ questions. Thanks! 🚀
