### ISSUE TITLE
testflight action can't have different transporter protocol set 

### ISSUE THREAD

**Issue by jacobvanorder** [fastlane/fastlane#979]
When using the testflight action, I'm behind a corporate firewall that doesn't allow for Signiant protocol when uploading. 

Both [Pilot](https://github.com/fastlane/pilot#firewall-issues) and [Deliver](https://github.com/fastlane/deliver/issues/181) can get around this by specifying `DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"` before you call it. It appears that testflight action doesn't allow this within a lane.

Any ideas?

**Comment by KrauseFx** [comment]
Not sure I understand the question. The `testflight` action uses `pilot` under the hood.

**Comment by jacobvanorder** [comment]
Yeah, sorry. I didn't understand that it should be an environment variable that should be set. I think my comment that you [pulled into pilot](https://github.com/fastlane/pilot/pull/103) should clarify enough. 

Closed!

Thanks for fielding my issue!

**Comment by KrauseFx** [comment]
Thanks :+1:
