### ISSUE TITLE
Can't install fastlane using brew cask reinstall fastlane

### ISSUE THREAD

**Issue by GarettRogers** [fastlane/fastlane#9796]
When trying to do a fastlane reinstall, it's having difficulties copying things into the ~/.fastlane directory because, I am assuming, I have space in my home directory name.

It seems like a permission error -- but its' because it's trying to install it into "rogers/..." (which isn't the correct path)

Here is the output:
brew cask reinstall fastlane
==> Satisfying dependencies
==> Downloading https://kits-crashlytics-com.s3.amazonaws.com/fastlane/standalone/fastlane.zip
######################################################################## 100.0%
==> No checksum defined for Cask fastlane, skipping verification
==> Uninstalling Cask fastlane
==> Running uninstall process for fastlane; your password may be necessary
==> Running uninstall script /usr/local/Caskroom/fastlane/latest/uninstall
==> 
==> You can now remove fastlane from your search path by editing your ~/.bash_profile file.
==> fastlane was uninstalled successfully!
==> 
==> Installing Cask fastlane
==> Running installer script /usr/local/Caskroom/fastlane/latest/install
==> 
==> Installing fastlane to /Users/garett rogers/.fastlane/bin... this might take a few seconds
==> 
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/.autotest: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/design_rationale.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/History.txt: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/hoe/minitest.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/assertions.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/autorun.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/benchmark.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/expectations.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/hell.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/mock.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/parallel.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/pride.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/pride_plugin.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/spec.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/test.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest/unit.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/lib/minitest.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/Manifest.txt: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/Rakefile: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/README.txt: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/metametameta.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/test_minitest_benchmark.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/test_minitest_mock.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/test_minitest_reporter.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/test_minitest_spec.rb: Permission denied
==> cp: rogers/.fastlane/bin/bundle/lib/ruby/gems/2.2.0/gems/minitest-5.4.3/test/minitest/test_minitest_unit.rb: Permission denied
==> cp: /Users/garett rogers/.fastlane/bin/..: No such file or directory
==> Successfully copied fastlane to /Users/garett rogers/.fastlane/bin
==> 
==> 
==> Couldn't detect shell config file (bash - ~/.bash_profile)
==> Please add the following line to your bash profile:
==> 
==> export PATH="$HOME/.fastlane/bin:$PATH"
==> 
==> After doing so close the terminal session and restart it to start using fastlane 🚀
==> 
==> cp: /Users/garett rogers/.fastlane/bin/..: No such file or directory
==> sed: /Users/garett: in-place editing only works for regular files
==> /usr/local/Caskroom/fastlane/latest/install: line 77: /Users/garett rogers/.fastlane/bin/fastlane: No such file or directory
==> grep: rogers/.fastlane/bin: Is a directory
==> /usr/local/Caskroom/fastlane/latest/install: line 96: [: /Users/garett: binary operator expected
🍺  fastlane was successfully installed!

**Comment by HarrisRobin** [comment]
@GarettRogers did you end up fixing this or did you install it another way?

**Comment by harrisrobin** [comment]
I don't have the permission issues above, but just a reminder for those using `oh my zsh` to add 
`export PATH="$HOME/.fastlane/bin:$PATH"` in their .zshrc file.

**Comment by ohayon** [comment]
Hey @GarettRogers, thanks for reporting this issue. It looks like there is definitely an issue with spaces in your path. I'm curious though, the same `install` script gets run when you do a `reinstall` that also setup _fastlane_ initially on your machine via homebrew, so it's one of those "how did this work in the first place" type situations 😄 . Did you initially install _fastlane_ via homebrew? Or did you download the package from somewhere else?
