### ISSUE TITLE
[Precheck] failed when checking valid non-encoded url

### ISSUE THREAD

**Issue by rpranata** [fastlane/fastlane#9798]
🔑 
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane precheck failed the rule for `UnreachableURLRule` when checking for an url in iTunes Connect that has not been encoded. In our case, it contains the Japanese characters but the url is valid and we have that as a valid metadata (did not get rejected)

##### Complete output when running fastlane, including the stack trace and command used
`bundle exec fastlane precheck` failed with

```
😵  Failed: No broken urls-> unreachable URLs in app metadata
+----------------------+-----------------------------------------------------+
|                             Potential problems                             |
+----------------------+-----------------------------------------------------+
| Field                | Failure reason                                      |
+----------------------+-----------------------------------------------------+
| privacy URL: (en-US) | unreachable: https://moneytree.jp/個人情報保護方針/ |
| privacy URL: (ja)    | unreachable: https://moneytree.jp/個人情報保護方針/ |
+----------------------+-----------------------------------------------------+
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                    |
| --------------------------- | -------------------------------------------------------- |
| OS                          | 10.12.5                                                  |
| Ruby                        | 2.4.1                                                    |
| Bundler?                    | true                                                     |
| Git                         | git version 2.6.3                                        |
| Installation Source         | ~/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.5 (16F73)                                 |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                              |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                              |
| Is contained                | false                                                    |
| Is homebrew                 | false                                                    |
| Is installed via Fabric.app | false                                                    |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/              |
| Xcode Version               | 8.3.3                                                    |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.47.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.15.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.1       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 5.0.2        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| aws-sigv4                 | 1.0.0        |
| jmespath                  | 1.3.1        |
| aws-sdk-core              | 2.9.12       |
| aws-sdk-resources         | 2.9.12       |
| aws-sdk                   | 2.9.12       |
| babosa                    | 1.0.2        |
| claide                    | 1.0.1        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.0.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| escape                    | 0.0.4        |
| fourflusher               | 0.3.2        |
| molinillo                 | 0.4.5        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| cocoapods                 | 1.0.1        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| sqlite3                   | 1.3.13       |
</details>

*generated on:* **2017-07-19**
</details>

**Comment by mpirri** [comment]
Great find!  We merged up the PR, and we'll let you know when it ships out. Thanks for putting in the effort to make `precheck` better!  🚀

**Comment by taquitos** [comment]
@rpranata is this still an issue? We released a fix that should encompass this issue.

**Comment by rpranata** [comment]
Thank you @taquitos and @mpirri ! Yes, confirmed that the issue is fixed. We can close this issue. Really glad I could help
