### ISSUE TITLE
Waiting for iTunes Connect to process the new build - fail

### ISSUE THREAD

**Issue by mladjan** [fastlane/fastlane#980]
I know that apple's servers take so much time to process the build, and I don't want to wait for them sometimes. Is there an option to disable waiting for process when I'm doing fastlane beta? :) Everything goes great, but I'm getting error slack message because it waits so much.

**Comment by scottrhoyt** [comment]
Sounds similar to #876

**Comment by KrauseFx** [comment]
```
pilot --help

    -s, --skip_submission  Skip the distributing action of pilot and only upload the ipa file
(PILOT_SKIP_SUBMISSION)
```

**Comment by Sajjon** [comment]
@KrauseFx What does --skip_submission do? What does "Skip the distributing action" mean?

Does it only make the pilot command to NOT get stuck at "Waiting for iTunes Connect to process the new build"? Or does it change anything in the upload procedure?

As I wrote in <a href="https://github.com/fastlane/pilot/issues/35">#35</a>, pilot actually succeeds in uploading the IPA to iTunes connect, but is unaware of that it worked, i.e. pilot doesn't terminate when ITC had finished processing the build.

**Comment by mark5422** [comment]
@Sajjon Did you ever find out what this does?
