### ISSUE TITLE
Spaceship - Create external testers Response ERROR

### ISSUE THREAD

**Issue by luberlu** [fastlane/fastlane#9803]
### New Issue Checklist

- [ ok ] Updated fastlane to the latest version
- [ ok ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

I am new with Spaceship. I am trying to create a new external tester to iTunes Connect.
But I've got this response : 

> {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Posted data is not valid."]}, "statusCode"=>"ERROR"}

This is what I send : 

`Spaceship::Tunes::Tester::External.create!(email:"xxx@gmail.com",first_name:"xxx",last_name:"xxx",groups:["group_name"])`

Is is wrong ?
Login is ok, I retrieved App name ;)

Thanks for your help,

Luberlu

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                |
| --------------------------- | ---------------------------------------------------- |
| OS                          | debian_based 8.8                                     |
| Ruby                        | 2.4.1                                                |
| Bundler?                    | false                                                |
| Git                         | git version 2.11.0                                   |
| Installation Source         | /usr/local/bin/fastlane                              |
| Host                        | Debian GNU/Linux 8 debian_based 8.8 (3.16.0-4-amd64) |
| Ruby Lib Dir                | /usr/local/lib                                       |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                          |
| Is contained                | false                                                |
| Is homebrew                 | false                                                |
| Is installed via Fabric.app | false                                                |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.47.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-07-19**
</details>

**Comment by luberlu** [comment]
If I put the id of the group instead the name, there is no error. But nothing happens in iTunes Connect, no add.

**Comment by mpirri** [comment]
It definitely looks like you are doing the right thing here; are you sure your account has the correct role to add testers? You need to be `admin` to call `create!`, if you are an `app-manager`, you need to use the `create_app_level_tester` method.

You can find an example of this code being used by looking at the `pilot/app_manager.rb` code.

Also, have you tried to use `fastlane pilot add` with the same parameters to see if you are able to add a tester that way? E.g.,
```
fastlane pilot add -e "xxx@gmail.com" -f "xxx" -l "xxx" -g "group_name" -a com.xxx.bundle_id
```

If that works, you may be able to follow what `pilot` is doing to add a tester (or call directly into `pilot` from your ruby code!)

I hope this is helpful, please let us know if you are still having difficulty!  🚀

**Comment by luberlu** [comment]
Hello @mpirri , 

Thanks for your quick response!
I am not a Ruby Developer (not for now ;) ), but I discovered this for my iOS app school project!  The presentation of the project is tomorrow, it will be complicated ..

I am the admin in iTunes Connect.

fastlane pilot add works.. But I need to use it in ruby code.

Thanks ;)

**Comment by mpirri** [comment]
You can call `pilot` directly from Ruby code. For instance, to do the same as our command line above, you could call:
```
    require 'pilot'
    Pilot::TesterManager.new.add_tester(
      first_name: "xxx",
      last_name: "xxx",
      email: "xxx@gmail.com",
      app_identifier: "com.xxx.bundle_id
",
      groups: ["xxx_group"]
      )
```

Would this work for you?

**Comment by luberlu** [comment]
Hello! 
I put environnement variables, login is ok.

But there is an error : 

```
Spaceship::TunesClient::ITunesConnectError at /
there is no web session to update
```

in /.gems/gems/fastlane-2.47.0/pilot/lib/pilot/manager.rb in login

`Spaceship::Tunes.select_team`

Really weird..

**Comment by mpirri** [comment]
@luberlu Can you check to see if you have an old version of the `pilot` gem installed? This bug was fixed in an version of _fastlane_ from a few weeks ago, so it is possible you are still referencing an older version of a gem that still has that bug.

#9805 is a discussion from another user who had a similar problem, maybe it will be helpful for you? 🚀

**Comment by fbomb111** [comment]
I'm having the exact same issue as described above.  Login successful, but receive the same error when trying to create an external tester.  I'm the account admin.  I then tried using the pilot commands as described above but received the 'no web session to update' error.  I updated fastlane to the most recent version before trying this (2.50.1).
