### ISSUE TITLE
fastlane deliver fails when calling from ruby. The request could not be completed because: there is no web session to update 

### ISSUE THREAD

**Issue by moakbar** [fastlane/fastlane#9805]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to upload an ipa using fastlane deliver. It uploads successfully if I upload it with command line `fastlane deliver`. But if I run the same command from ruby it fails giving this error.

The request could not be completed because:       there is no web session to update

I tried different options present in previous GitHub links. But none helped.

can you please help
##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[07:25:32]: [32mSuccessfully loaded '/Users/*********/Desktop/apple-store/bdbf3405-1b7c-4c7b-949d-3159a16b105b/BusinessStore/13/Deliverfile' 📄[0m

+------------------------+--------------------------------------+
|             Detected Values from './Deliverfile'              |
+------------------------+--------------------------------------+
| app_identifier         | *****************           |
| username               |  *****************                |
| ipa                    | /Users/*******/Desktop/apple-store  |
|                        | /bdbf3405-1b7c-4c7b-949d-3159a16b10  |
|                        | 5b/BusinessStore/13/**********.ipa    |
| submit_for_review      | true                                 |
| force                  | true                                 |
| automatic_release      | true                                 |
| submission_information | {:add_id_info_uses_idfa=>false,      |
|                        | :export_compliance_uses_encryption=  |
|                        | >false,                              |
|                        | :export_compliance_encryption_updat  |
|                        | ed=>false}                           |
| release_notes          | {"en-US"=>"TestApple"}               |
+------------------------+--------------------------------------+

[07:25:32]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[07:25:32]: Login to iTunes Connect (gpn15@outlook.com)

Looking for related GitHub issues on fastlane/fastlane...

➡️  [33mlatest_testflight_build_number fails with 'there is no web session to update' error[0m
    https://github.com/fastlane/fastlane/issues/9781 [[32mclosed[0m] 3 💬
    a day ago

➡️  [33mThere is no web session to update still appear on new version "fastlane"[0m
    https://github.com/fastlane/fastlane/issues/9653 [[32mclosed[0m] 12 💬
    5 days ago

➡️  [33mpilot - there is no web session to update (on upload)[0m
    https://github.com/fastlane/fastlane/issues/9237 [[32mclosed[0m] 24 💬
    29 May 2017

and 15 more at: https://github.com/fastlane/fastlane/search?q=The%20request%20could%20not%20be%20completed%20because:%0A%09there%20is%20no%20web%20session%20to%20update&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem                 | Version | Update-Status |
| ------------------- | ------- | ------------- |
| fastlane            | 2.47.0  | ✅ Up-To-Date  |
| credentials_manager | 1.0.0   | ✅ Up-To-Date  |
| spaceship           | 1.0.0   | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.2       |
| io-console                | 0.4.6        |
| rake                      | 12.0.0       |
| CFPropertyList            | 2.3.5        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.8.6        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 5.1.2        |
| jwt                       | 1.5.6        |
| mini_portile2             | 2.2.0        |
| nokogiri                  | 1.8.0        |
| uri_template              | 0.7.0        |
| adal                      | 1.0.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| application_insights      | 0.5.3        |
| babosa                    | 1.0.2        |
| backports                 | 3.8.0        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| credentials_manager       | 1.0.0        |
| diff-lcs                  | 1.3          |
| mustermann                | 1.0.0        |
| netrc                     | 0.11.0       |
| rack                      | 2.0.3        |
| rack-protection           | 2.0.0        |
| rack-test                 | 0.6.3        |
| rest-client               | 2.0.2        |
| rspec-support             | 3.6.0        |
| rspec-core                | 3.6.0        |
| rspec-expectations        | 3.6.0        |
| rspec-mocks               | 3.6.0        |
| rspec                     | 3.6.0        |
| tilt                      | 2.0.7        |
| sinatra                   | 2.0.0        |
| sinatra-contrib           | 2.0.0        |
| sqlite3                   | 1.3.13       |
</details>

*generated on:* **2017-07-19**
</details>

**Comment by mpirri** [comment]
I wonder if you might have an old version of `deliver` installed on your system. If you do `deliver --version` what do you see for a version? Also, does the `Gemfile` in your ruby project reference `deliver` directly? Or perhaps an old version of _fastlane_?

Essentially the bug that you are seeing should have been fixed by this PR: https://github.com/fastlane/fastlane/pull/9238
This shipped in _fastlane_ 2.33.0, so everything after that should not see the problem. This is why I'm thinking that calling `fastlane deliver` directly is using a new version, but your Ruby code might be using an older version.

Let us know what you learn! 🚀

**Comment by moakbar** [comment]
Thanks for quick response. I was referring spaceship as ruby gem instead of fastlane.

Once I changed it. 'fast lane deliver' command start working correctly.

And yes was gemfile was referring it directly and not with any specific version.

Your quick response helped. Thanks!!!
