### ISSUE TITLE
Codesigned app installs but fails to launch

### ISSUE THREAD

**Issue by Yaldo425** [fastlane/fastlane#9809]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am issuing the following command to codesign an app:

`fastlane sigh resign /Users/mac/Desktop/Twitch.ipa --signing_identity "iPhone Distribution: Name LastName (XXXXX)" -p /Users/mac/Desktop/profile.mobileprovision`

After successfully codesigning it and getting it installed on my device, it immediately crashes and I do not know why. Could this please be looked into? Other apps work but some do not launch

The IPA file can be found [here](https://drive.google.com/open?id=0ByY3puO_IIf8X3Ffb28wQnJnNHM) for debugging.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
_floatsignTemp/Payload/ppsideloader.app: replacing existing signature
rm: _floatsignTemp/old-embedded-profile.plist: No such file or directory

[16:43:04]: Successfully signed /Users/Mathew/Downloads/Twitch.ipa!
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.1                                                          |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.47.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.7.7        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.1       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-07-19**
</details>

**Comment by mpirri** [comment]
Have you looked at your iPhone device log to see why the app won't launch? Usually when the app immediately crashes out like this it implies a code signing problem (as you might imagine), but iOS is pretty good about printing out an error message to the console.

Thanks for the report! 🚀

**Comment by Yaldo425** [comment]
@mgrebenets Would you know how to resolve this? Everyone says that you are good with resigning

**Comment by mpirri** [comment]
@Yaldo425 So your problem sounds a lot like issue #9783 - they found that they had multiple signing identities on their keychain and could get it working right by (temporarily) removing one of the identities. Do you also have multiple code-signing identities?

**Comment by Yaldo425** [comment]
@mpirri I just checked the keychain and can confirm that I only have **one** signing identity.

**Comment by chriscombs** [comment]
I am also running into this same problem. The `resign` action runs fine and succeeds, and the app can be installed, but it crashes as soon as it launches. Actually it crashes before it launches, So there is no crash log or anything useful in the console output.

**Comment by Yaldo425** [comment]
@chriscombs A few days after I had this issue I went to my device's logged and it turned out that it did not sign a framework properly so I looked for other resigning tools since they didn't want to fix fastlane :/

**Comment by chriscombs** [comment]
For anyone else coming across this, my issue was with bitcode and enterprise certificates. Now my process is `gym` for appstore, `gym` again with include_bitcode: false and skip_build_archive: true, and then resigning that second ipa worked.

**Comment by mgrebenets** [comment]
Hi @Yaldo425 

I'm curious what's the `/Twitch.app/Sys.dylib` library showing up in the logs.

Normally `dylib` libraries are part of iOS and are not included into the application bundle.
Such as `sqlite.dylib` and `zip` library and so on.

So I'm kind of suspicious of that `Sys.dylib`.

The only `dylib` files I can find in our apps are the Swift libraries, those that are bundled in `Frameworks` directory until we get ABI stability.

`MyApp.app/Frameworks/libswift***.dylib`

**Comment by saitjr** [comment]
resign action will not resign framework out of `execute_dir/Frameworks`, you should resign the `Sys.dylib` by yourself, or move it to `Frameworks` dir.
