### ISSUE TITLE
Cannot select team via  Spaceship::TunesClient

### ISSUE THREAD

**Issue by ancazapuc9** [fastlane/fastlane#9811]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

We tried to fully automate following scenario in our company:
having a lot of iOS apps, we needed to know information about version/number of these apps.
-> we connect with our admin iTunes user to iTunes interface
-> we select the corresponding team where the app is
-> we check the app status and version
-> we add this manually in our database.

The above scenario, we converted via code.
I made a Ruby Sinatra app , inside Gemfile added **gem 'fastlane', '~> 2.7'**
 We have several cases where I need to select the team where actually the app belongs to
and the  code crashes with **"there is no web session to update".** 

Please find below the code:

  **username = ....
   password = ....
   team_name = ....
   bundleId = ....
   spaceship = Spaceship::Tunes.login(username, password)
   iTunesApp = Spaceship::Tunes::Application.find(bundleId') 
   unless iTunesApp 
         teamInfo = spaceship.teams.select { |team| team['contentProvider']['name'] == team_name}.first
         team_id = teamInfo['contentProvider']['contentProviderId'] if teamInfo
         spaceship.team_id = team_id
           iTunesApp = Spaceship::Tunes::Application.find(bundleId) 
  end**

The code crashes when executing **spaceship.team_id = team_id** with following stacktrace

`**[ERROR] Thu 20 Jul 09:55 AM 2017 :: there is no web session to update
[ERROR] Thu 20 Jul 09:55 AM 2017 :: ["/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.39.1/spaceship/lib/spaceship/tunes/tunes_client.rb:162:in `handle_itc_response'", "/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.39.1/spaceship/lib/spaceship/client.rb:228:in `team_id='", "/Users/ancazapuc/work_20/appStoreGetSet/helpers/account_wrapper.rb:83:in** `updated_version_status_for_account'", "/Users/ancazapuc/work_20/appStoreGetSet/app.rb:62:in `block in <top (required)>'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1631:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1631:in `block in compile!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'", "/Users/ancazapuc/work_20/appStoreGetSet/helpers/exceptions.rb:26:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/show_exceptions.rb:22:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'"]
`

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.12.1                              |
| Ruby                        | 2.3.1                                |
| Bundler?                    | false                                |
| Git                         | git version 2.10.1                   |
| Installation Source         | /usr/local/bin/fastlane              |
| Host                        | Mac OS X 10.12.1 (16B2555)           |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.3.1_2/lib   |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016          |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.47.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.5        |
| excon                     | 0.57.1       |
| rubyzip                   | 1.2.1        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.1       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.0        |
| bundler                   | 1.14.6       |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
</details>

*generated on:* **2017-07-20**
</details>

**Comment by mpirri** [comment]
Based on your log output, It looks like you are using _fastlane_ version 2.39.1 - can you do a `bundle update` and get a newer version to see if that helps? The "there is no web session to update" error was fixed in an older version of _fastlane_ and so I'm hopeful that an update to the version that your Ruby project is using will help with this issue.

Let us know how it goes - thanks for the report!  🚀

**Comment by ancazapuc9** [comment]
I have already tried that, since I googled a lot about this error.
Nevertheless tried again ( upgrading to 2.47.0)


**[ERROR] Fri 21 Jul 09:23 AM 2017 :: there is no web session to update
[ERROR] Fri 21 Jul 09:23 AM 2017 :: ["/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/tunes_client.rb:162:in `handle_itc_response'", "/usr/local/lib/ruby/gems/2.3.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/client.rb:228:in** `team_id='", "/Users/ancazapuc/work_20/appStoreGetSet/helpers/account_wrapper.rb:83:in `updated_version_status_for_account'", "/Users/ancazapuc/work_20/appStoreGetSet/app.rb:62:in `block in <top (required)>'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1631:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1631:in `block in compile!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'", "/Users/ancazapuc/work_20/appStoreGetSet/helpers/exceptions.rb:26:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/show_exceptions.rb:22:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'", "/usr/local/lib/ruby/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'", "/usr/local/lib/ruby/gems/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'"]**

I tried also setting up 
```
ENV['FASTLANE_ITC_TEAM_NAME']=<team>
ENV['FASTLANE_ITC_TEAM_ID'] =<team_id>
spaceship.select_team
``` 
-> 
got same error.

If you think it's easier , I can easily provide you with a **"test.rb"** file with my code so you can reproduce on your machine.

**Comment by mpirri** [comment]
Absolutely - send that file (or a GitHub gist with the contents of it)!  I'd love to try it on my machine to see what I can learn.

Thanks!  🚀

**Comment by ancazapuc9** [comment]
I created a code snippet for this issue from my original code. The problem happens when I try to iterate an array aprox 250 records from our database ( we keep iTunes credentials / bundle / team name inside our db). I need to parse all of them , connect to iTunes and retrieve the correct version and number.

```
gem fastlane, '2.47.0'

require 'spaceship'

array_of_hashes = [ {username: 'iTunes_user', password: 'iTunes_password', bundle:'app_bundle_id', team: 'team_name'}, {}, {}......] # size of 250 records 
array_of_hashes.each do |hash|
  begin
    puts "Starts processs hash: #{hash}..."
  spaceship = Spaceship::Tunes.login(hash[:username],hash[:password])
   sleep 5 # this sleep needed for avoiding Itunes::Connect Error
  iTunesApp = Spaceship::Tunes::Application.find(hash[:bundle])

unless iTunesApp
  teamInfo = spaceship.teams.select { |team| team['contentProvider']['name'].strip.downcase == hash[:team].strip.downcase }.first
  team_id = teamInfo['contentProvider']['contentProviderId'] if teamInfo
  if (team_id)
    puts "Team if found is: #{team_id}"
    spaceship.team_id = team_id 
    iTunesApp = Spaceship::Tunes::Application.find(hash[:bundle])
    puts "YEYY I should arrive #{iTunesApp}....."
    # extract version and status number....  
end
end
  rescue Exception => ex
    puts "Exception occured...."
    puts ex.message
end
end
```

**Comment by ancazapuc9** [comment]
I have found the problem ( indeed it was my monkey patch).  I upgraded the monkey patch according to 2.47.0 fas lane version  and now it works. 

I think I can close the task && thanks for quick responses.
