### ISSUE TITLE
Change fastlane output folder name

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#9812]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Where is the `FastlaneCore::FastlaneFolder.path` defined? As I'm constantly seeing that "if you use Fastlane, the output will be saved in the .fastlane folder", but for me, it's just "fastlane" (without the dot).

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by mpirri** [comment]
The search order for `fastlane` folder should be: `fastlane` (no dot) and then `.fastlane` (with dot). It will also detect the current directory if it contains a `Fastfile`.

The code that does the search is here:
https://github.com/fastlane/fastlane/blob/master/fastlane_core/lib/fastlane_core/fastlane_folder.rb

Can you give an example of a command that prints out that output message ("... the output will be saved in the .fastlane folder")?  Thanks! 🚀

**Comment by revolter** [comment]
It wasn't in a command output, but some documentation or comments, but I forgot where. Thanks for the answer.
