### ISSUE TITLE
Fastlane isn't warning users that the captured output could contain sensitive information

### ISSUE THREAD

**Issue by revolter** [fastlane/fastlane#9815]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The issue template tells users to use the `--capture_output` argument or `fastlane env` command and blindly paste the output in issues, but it contains the entire Fastfile's contents, which could contain sensitive or private information. It also contains the path to the project that uses Fastlane, which is not relevant at all, and the Apple Developer Team ID, which feels odd, even if it's not a security problem. It would be great if the messages would be __prefixed__ by a warning stating these.

**Comment by mpirri** [comment]
This is a great idea! Any chance you'd want to create a PR with the recommended language when `--capture_output` is used? We are always looking for good PRs from our awesome community to help improve _fastlane_.  😄 

Also, I wonder if you've taken a look at PR #9818 fixing an issue in `capture_output` that prevented sensitive data from being obfuscated. Perhaps this bug was preventing _fastlane_ from working correctly when outputting your environment. This fix recently shipped in a production release of _fastlane_.

**Comment by kkiran33** [comment]
Can you remove / unsubscribe  me from this list please

**Comment by revolter** [comment]
@mpirri, As far as I can see, that PR obfuscates used API tokens, but, personally, as I said, I would like for the Apple Developer Team ID to be removed too.

**Comment by ohayon** [comment]
@kkiran33 I think that you can only unsubscribe yourself from the issue on the right hand side of this screen. Sorry for the noise 😄

**Comment by ohayon** [comment]
Hey @revolter - we are always happy to make sure that sensitive information is not shared in public. As @mpirri mentioned we would be more than happy to review a PR with some more output warning users that there could be sensitive info in the output. Would you want to submit a change to make that happen? Thanks!! 🐙  🚀

**Comment by revolter** [comment]
@ohayon, I would like to, but I'm not accustomed to the codebase at all. Also, would interactively asking the user if they want some section included or not be ok? For example:

> Would you like to include the contents of your Fastfile:
>
> fastlane_version "1.109.0"
> default_platform :ios
> ...
>
> y/n: |

Or just print a warning to the console urging the users to check the entire clipboard content for sensitive information?
