### ISSUE TITLE
git_commit with multiple paths

### ISSUE THREAD

**Issue by scottrhoyt** [fastlane/fastlane#982]
I would like my CI server to commit and push my version bumps and new tags. I cannot use `commit_version_bump` because I need to leave my artifacts in place so there are more changes than what `commit_version_bump` would like. I tried solving this by doing a `git_commit` with my project file and Info.plist, but I get a failure using multiple paths:

    [18:13:57]: Error setting value '["./Project/Info.plist", "./Project/Project.xcodeproj"]' for option 'path'
    [18:13:57]: You passed invalid parameters to 'git_commit'.
    [18:13:57]: Check out the error below and available options by running `fastlane action git_commit`

Any help would be appreciated.

**Comment by KrauseFx** [comment]
Sorry, right now this only takes a string (= one path). Instead the easiest way is to just duplicate the call multiple times for each path you want to commit.

**Comment by scottrhoyt** [comment]
Ok, the current documentation at Actions.md might be out of date then. But thank you for the feedback and the great tools @KrauseFx !

**Comment by KrauseFx** [comment]
I thought you were talking about the `commit_version_bump` action? Could you please share your `Fastfile` on where and how you call the `commit` action?

**Comment by Antowkos** [comment]
@KrauseFx Hi! I just got the same bug with this command:
```ruby
git_commit(
			path: [ENV["INFOPLIST_PATH"], ENV["EXTENSION_INFOPLIST_PATH"]],
			message: "Build number changed"
			)
```

Actually there are 2 problems:
1. incorrect documentation - there are no `,` sign between command variables `path` and `message`.
2. command works incorrect with paths with spaces. This is what i see in my command line when fastlane tries to commit changes:
```
git commit -m 'Build number changed' Supporting Files/Info.plist Open In App/Info.plist
```
instead of:
```
git commit -m 'Build number changed' 'Supporting Files/Info.plist' 'Open In App/Info.plist'
```

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it. If this is still a problem, feel free to re-open a new issue and I’d be happy to help :+1:
