### ISSUE TITLE
Are there any plans to support Windows?

### ISSUE THREAD

**Issue by AdityaAnand1** [fastlane/fastlane#9823]
:(

**Comment by mpirri** [comment]
No immediate plans, I'm afraid.

Can you give me a quick overview of what your needs for `fastlane` are on Windows? I can share them with the team and it might help to set our direction going forwards.

Thanks much!  🚀

**Comment by AdityaAnand1** [comment]
I tried to use screengrab for Android on windows and ran into #8800 

Does fastlane work on any nix system or just macOS? Perhaps there could be a quick workaround by using bash on windows..

**Comment by mpirri** [comment]
As I understand it, even when running the `bash` shell, Windows' underlying process system still does not support the POSIX fork concept, requiring a substantial rewrite of how _fastlane_ launches sub-tools. Unfortunately right now we are not able to take on the commitment of supporting an entirely new platform, even though we are aware there are a good number of users developing for Android on Windows.

I'll pass on your request to the rest of the team and we'll take it into consideration when revisiting our decision about which platforms to support.

Thanks, and sorry I don't have better news.

**Comment by AdityaAnand1** [comment]
Any updates @mpirri ?
