### ISSUE TITLE
New feature: Support getting reviews for all countries

### ISSUE THREAD

**Issue by hhoweson** [fastlane/fastlane#9824]
As far as I understand, currently, the only way to get all reviews for an app is to loop through all the country codes and run the following line for each one:

`reviews = app.ratings.reviews(countryCode)`

This is very slow and in a situation like mine where I am checking over 100 apps daily it is insufficient especially since itunes connect is so unstable

Just to be clear I really appreciate the work you guys have done and was wondering whether
a) I am being stupid and there is a better solution or
b) You guys are working on something or can recommend something to take a look at?

Many thanks and my apologies if this isn't the right place to put this!

-Henry

**Comment by hhoweson** [comment]
Though it might be worth adding that this seems to be the most common issue (usually happens halfway through the script), any inputs on possible fixes or better ways to handle it would be welcomed: 

Again, my apologies if this is the wrong place to post this and I will be more than happy to remove it and post somewhere else if that would be more helpful.

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/client.rb: (Spaceship::Client::UnexpectedResponse)
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>daiquiri/3.0.0</center>
</body>
</html>
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/tunes_client.rb:268:in `get_ratings'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/application.rb:133:in `ratings'
	from downloadReviews.rb:39:in `block (2 levels) in <main>'
	from /Library/Ruby/Gems/2.0.0/gems/parallel-1.11.2/lib/parallel.rb:486:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/parallel-1.11.2/lib/parallel.rb:486:in `call_with_index'
	from /Library/Ruby/Gems/2.0.0/gems/parallel-1.11.2/lib/parallel.rb:342:in `block (2 levels) in work_in_threads'
	from /Library/Ruby/Gems/2.0.0/gems/parallel-1.11.2/lib/parallel.rb:495:in `with_instrumentation'
	from /Library/Ruby/Gems/2.0.0/gems/parallel-1.11.2/lib/parallel.rb:341:in `block in work_in_threads'
	from /Library/Ruby/Gems/2.0.0/gems/parallel-1.11.2/lib/parallel.rb:206:in `block (2 levels) in in_threads'
```

**Comment by mpirri** [comment]
Interesting, @hhoweson, I wonder if that is Apple rate-limiting you because of all of the requests. Perhaps add an intentional delay between requests to slow down the number of requests you are making in a given time period.  Obviously not a really great solution when you are already suffering with performance for your use case!

A question - do you know if there is a UI on iTunesConnect that will show you all of the reviews for all countries? If so, it should be possible to mirror the functionality in `spaceship`.  However, if Apple does not offer this ability already, it is unlikely we will be able to build it into our tools without simply iterating over each country the way you are doing here.

Thanks for writing in!  🚀

**Comment by hhoweson** [comment]
Well, I actually found something that might work a while ago. I figured that itunes connect is much quicker than what I am able to do with the API so I monitored the outgoing network requests when loading the review page in itunes connect 

(https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/{INSERT APP ID HERE}/activity/ios/ratingsResponses)

and I managed to find this request: 

https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/apps/{INSERT APP ID HERE}/platforms/ios/reviews?sort=REVIEW_SORT_ORDER_MOST_RECENT

It outputs JSON and appears to include everything, the disadvantage and why I didn't take it any further is the requirement for authentication although I guess you guys deal with that already so it isn't a problem?

**Comment by mpirri** [comment]
Yeah!  If you look at the source for `spaceship` you'll see how we make authenticated requests like this to iTC and then parse the response. (it is super-easy)

I don't suppose we could coerce you into maybe making an attempt to add support for this API call to `spaceship`? We are always enthusiastic to review awesome PRs from the community adding useful features.

Let us know if you are interested and we'll be happy to help! Thanks again. 🚀

**Comment by hhoweson** [comment]
I love a challenge and would definitely be interested in giving it a go, are there any documents which give guidelines on how the repo works or any functions that will simplify the process? Any and all advice is welcome

**Comment by mpirri** [comment]
We have some docs that should help you get started. First off, some basic guidelines and advice for contributing to _fastlane_:
https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md

Here is information that might be helpful, since you will be building/debugging functionality in `spaceship`:
https://github.com/fastlane/fastlane/blob/master/ToolsAndDebugging.md

Finally, some information about testing and preparing your first GitHub pull request for _fastlane_:
https://github.com/fastlane/fastlane/blob/master/YourFirstPR.md

I hope this is helpful, please don't hesitate to reach out if you have any other questions. 🚀

**Comment by hhoweson** [comment]
Awesome, gonna have a roam around and see what I can do, how would you like me to implement it (assuming I figure it all out)?

If it were 100% up to me I would make this work: ratings.reviews()
In other words, instead  of specifying a country (ratings.reviews("US")) you can choose not to and it will use the link I found.

**Comment by hhoweson** [comment]
Also sorry to put this in the wrong place but i get this error whenever I run fastlane: 

/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here

Just double checking thats normal XD if it is ill delete this from the thread to keep it all relevant

**Comment by mpirri** [comment]
From what I have seen, it is an issue in the `fastimage` gem and seems to be normal. Annoying though!

**Comment by hhoweson** [comment]
Bit confused with these lines for creating the url to query:

```
# if storefront or versionId is empty api fails
rating_url = "ra/apps/#{app_id}/platforms/#{platform}/reviews/summary?"
rating_url << "storefront=#{storefront}" unless storefront.empty?
rating_url << "versionId=#{versionId}" unless versionId.empty?

r = request(:get, rating_url)
parse_response(r, 'data')
```

1. Shouldn't line 4 have an '&' sign infront of it in order to show as a separate parameter in a url encoded string?
2. When it says the API fails does that mean that it will expect itunes connect to return an error or does it mean that the code below has some sort of error handling built in (if so how?)

Thanks again and sorry for being such high maintenance :tongu

**Comment by ohayon** [comment]
Hey @hhoweson - 

1. you're right, this seems to be like one of those "how did this ever work" situations 😄 
2. I am pretty sure that the API will return a non 2xx status and then it will fall into our error handling in the `parse_response` method

No problem for asking questions! You're definitely not being high maintenance! We love to help people get familiar with _fastlane_ and contribute back. Let us know if there is anything more we can do to help out! 🐙

**Comment by hhoweson** [comment]
What is the best way to run commands like Spaceship::Tunes::Application.find() on the local file in order to test it, is there a way to use require_relative?

**Comment by ohayon** [comment]
If I understand correctly, I think the best way is to have a Gemfile, that specifies `gem 'fastlane', path: '/path/to/your/fastlane/clone'` and then run `bundle update` then, if you use `bundle exec` to call your script (maybe a Rakefile) it will use your local version of _fastlane_ and _spaceship_. Is that helpful?

**Comment by hhoweson** [comment]
In order to test it I added this to the start of the Fastfile:

```
desc "Using this option you can run a user created script called test.rb which should be located in the same folder as the fastlane directory"
lane :testScript do |options|
  require "../../test.rb"
end
```

It seems like this could be pretty useful for anyone who wanted to use a ruby file to run custom commands to test their changes, they can either use the ui or run `bundle exec fastlane testScript`. I don't know if this is the best way of doing it but if it is it makes sense to commit this or something similar. Just wondering what your views on this are?

**Comment by hhoweson** [comment]
I am now almost finished with the new feature, I assume it needs to be backwards compatible, one issue with this is that the developer response is now located under `review.developerResponse.response`
instead of
`review.developer_response.response`

**Comment by hhoweson** [comment]
It has just occurred to me that the new endpoint will require authentication whereas the last one did not, this will mean that it isn't 100% compatible, I presume this is ok?

**Comment by ohayon** [comment]
@hhoweson - that bit of info about how youre calling your script is definitely helpful! It's hard to comment on the compatibility without seeing the code, would you want to open up a work-in-progress PR so we can take a look at the code and give some thoughts/feedback? 

Thank you again so much for putting your time into this! Contributions like this are so appreciated 😄

**Comment by hhoweson** [comment]
All that has really changed is the endpoint, the new endpoint requires authentication, I’ll send the code when I get back to my computer. The idea of my addition to the rake file was that it could be useful for anyone changing anything, to run functions they could just create a script called test.rb and fun functions in that: they wouldn’t have to change the rakefile themselves.

**Comment by hhoweson** [comment]
Done #9968
