### ISSUE TITLE
Can't save IAP details

### ISSUE THREAD

**Issue by jgongo** [fastlane/fastlane#9826]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I'm trying to use Spaceship to update IAP products. Every time that I try I get a `ITC.response.error.OPERATION_FAILED`. I'm a Ruby newbie, so maybe I'm missing anything! I try to do the following:

```
require 'Spaceship'
Spaceship::Tunes.login('########', '#########')
iap = Spaceship::Tunes::Application.all.first.in_app_purchases.all.first.edit
iap.save!
```

The iTunes user I'm using to login has the App Manager role, so it should be ok, no?

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
$ bundle exec ruby scripts/updateIAP.rb 
/Users/jose.gonzalez/Documents/projects/rakuten/ios/ios-v3/vendor/bundle/ruby/2.4.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/tunes_client.rb:162:in `handle_itc_response': ITC.response.error.OPERATION_FAILED (Spaceship::TunesClient::ITunesConnectError)
	from /Users/jose.gonzalez/Documents/projects/rakuten/ios/ios-v3/vendor/bundle/ruby/2.4.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/tunes_client.rb:964:in `block in update_iap!'
	from /Users/jose.gonzalez/Documents/projects/rakuten/ios/ios-v3/vendor/bundle/ruby/2.4.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/tunes_client.rb:1296:in `with_tunes_retry'
	from /Users/jose.gonzalez/Documents/projects/rakuten/ios/ios-v3/vendor/bundle/ruby/2.4.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/tunes_client.rb:958:in `update_iap!'
	from /Users/jose.gonzalez/Documents/projects/rakuten/ios/ios-v3/vendor/bundle/ruby/2.4.0/gems/fastlane-2.47.0/spaceship/lib/spaceship/tunes/iap_detail.rb:211:in `save!'
	from scripts/updateIAP.rb:26:in `<main>'

```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                         |
| --------------------------- | ----------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                       |
| Ruby                        | 2.4.0                                                                         |
| Bundler?                    | true                                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                                             |
| Installation Source         | ~/Documents/projects/rakuten/ios/ios-v3/vendor/bundle/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                                                   |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                                                   |
| Is contained                | false                                                                         |
| Is homebrew                 | false                                                                         |
| Is installed via Fabric.app | false                                                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                   |
| Xcode Version               | 8.3.3                                                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.29.0"

default_platform :ios

platform :ios do
  desc "Install dependencies"
  lane :pods do
    cocoapods(use_bundle_exec: true)
  end


  desc "Runs Wuaki-iOS tests"
  lane :test do
    scan(scheme: 'wuaki-ios-sim', devices: ['iPhone 7'], code_coverage: true, output_directory: 'build/reports/tests')
    slather(workspace: 'wuaki-ios.xcworkspace', proj: 'wuaki-ios/wuaki-ios.xcodeproj', scheme: 'wuaki-ios-sim', output_directory: 'build/reports/coverage', html: true, use_bundle_exec: true)
  end


  desc "Badge the Spartan app icon with version and build number"
  lane :badge_app_icon do
    assetsPath = 'wuaki-ios/wuaki-ios/resources/images/WKAssets.xcassets'
    version = get_version_number(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj', target: 'wuaki-ios')
    build = get_build_number(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj')

    # Copy original app icons
    sh("cp #{ENV['PWD']}/#{assetsPath}/AppIcon.appiconset/*.png #{ENV['PWD']}/#{assetsPath}/AppIcon.spartan.appiconset/")
    badge(glob: '/**/AppIcon.spartan.appiconset/*.png', shield: "#{version}-#{build}-orange", shield_io_timeout: 30)
  end


  desc "Submit a new Wuaki-iOS Beta Build to Apple TestFlight"
  lane :beta do |options|
    # match(type: "appstore") -> Share certificates, not right now

    ensure_git_status_clean
    increment_build_number(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj')
    scheme = options[:external_beta] == true ? 'wuaki-ios' : 'wuaki-ios-spartan'

    if options[:external_beta] != true
      badge_app_icon
      appIcons = Dir["#{ENV['PWD']}/wuaki-ios/wuaki-ios/resources/images/WKAssets.xcassets/AppIcon.spartan.appiconset/*.png"]
      git_add(path: appIcons)
      git_commit(path: appIcons, message: 'Badge app icon')
    end

    gym(workspace: 'wuaki-ios.xcworkspace', scheme: scheme, output_directory: 'build/ipa', output_name: 'wuaki-ios.ipa')
    pilot(ipa: 'build/ipa/wuaki-ios.ipa', distribute_external: options[:external_beta] == true)

    commit_version_bump(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj')
    add_git_tag
    push_to_git_remote
  end


  desc "Deploy a new Wuaki-iOS version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: 'wuaki-ios')
    deliver(force: true)
    # frameit
  end


  after_all do |lane|
    # nothing right now
  end


  error do |lane, exception|
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "tv.wuaki.Wuakitv-Player" # The bundle identifier of the app
apple_id "mobile@wuaki.tv"               # Apple email address -> This should be put elsewhere

team_id "NQ7GNB56L5"                     # Developer Portal Team ID

itc_team_name "Wuaki TV S.L."            # iTunes Connect team name
itc_team_id "1263804"                    # iTunes Connect team id (from https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/user/detail)
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.47.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.15.2       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.3        |
| fastimage                 | 2.1.0        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.1       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| badge                     | 0.8.4        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 0.2.6        |
| cocoapods                 | 1.2.0        |
| coderay                   | 1.1.1        |
| method_source             | 0.8.2        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slop                      | 3.6.0        |
| pry                       | 0.10.4       |
| slather                   | 2.4.1        |
</details>

*generated on:* **2017-07-21**
</details>

**Comment by jgongo** [comment]
Sorry to bump the issue, but, can please anybody test if this is working for him/her? I don't even change any values and the operation fails, so am I doing anything wrong?

**Comment by jgongo** [comment]
I'm going to assume this is Spaceship's fault. I captured the JSON sent to the ITC server and the JSON sent by the official ITC client has a lot more information than the JSON sent by Spaceship, so I guess the server misses some information and returns the error:

JSON sent by Spaceship:
```json
{
  "sectionErrorKeys": [],
  "sectionInfoKeys": [],
  "sectionWarningKeys": [],
  "id": "3059204478",
  "adamId": "1130326614",
  "appAdamIds": [
    "532577301"
  ],
  "familyId": null,
  "addOnType": "consumable",
  "isNewsSubscription": false,
  "isReplaced": false,
  "replacementAdamId": null,
  "referenceName": {
    "value": "Tier31",
    "isEditable": true,
    "isRequired": true,
    "errorKeys": null,
    "maxLength": 64,
    "minLength": 2
  },
  "productId": {
    "value": "tv.wuaki.tier31",
    "isEditable": false,
    "isRequired": true,
    "errorKeys": null,
    "maxLength": 100,
    "minLength": 2
  },
  "clearedForSale": {
    "value": true,
    "isEditable": true,
    "isRequired": false,
    "errorKeys": null
  },
  "pricingDurationType": null,
  "pricingIntervals": [
    {
      "value": {
        "tierStem": 31,
        "priceTierEffectiveDate": null,
        "priceTierEndDate": null,
        "country": "WW",
        "grandfathered": null
      }
    }
  ],
  "ungrandfatheredIntervals": null,
  "freeTrialDurationType": null,
  "bonusPeriodDurationType": null,
  "versions": [
    {
      "reviewNotes": {
        "value": null
      },
      "contentHosting": null,
      "details": {
        "value": [
          {
            "value": {
              "description": {
                "value": "It can be a movie, a season or an episode"
              },
              "name": {
                "value": "Contenido"
              },
              "localeCode": "es-ES"
            }
          },
          {
            "value": {
              "description": {
                "value": "It can be a movie, a season or an episode"
              },
              "name": {
                "value": "Content"
              },
              "localeCode": "en-GB"
            }
          }
        ]
      },
      "id": "94211286"
    }
  ],
  "missingRequiredPrivacyPolicyData": false,
  "missingRequiredFamilyDetail": false
}
```

JSON sent by official ITC client (web):
```json
{
  "sectionErrorKeys": [],
  "sectionInfoKeys": [],
  "sectionWarningKeys": [],
  "id": "3059686138",
  "adamId": "1130906670",
  "appAdamIds": [
    "532577301"
  ],
  "familyId": null,
  "addOnType": "consumable",
  "isNewsSubscription": false,
  "isReplaced": false,
  "replacementAdamId": null,
  "referenceName": {
    "value": "Tier67",
    "isEditable": true,
    "isRequired": true,
    "errorKeys": null,
    "maxLength": 64,
    "minLength": 2
  },
  "productId": {
    "value": "tv.wuaki.tier67",
    "isEditable": false,
    "isRequired": true,
    "errorKeys": null,
    "maxLength": 100,
    "minLength": 2
  },
  "clearedForSale": {
    "value": true,
    "isEditable": true,
    "isRequired": false,
    "errorKeys": null
  },
  "pricingDurationType": null,
  "pricingIntervals": [
    {
      "value": {
        "tierStem": "67",
        "priceTierEffectiveDate": null,
        "priceTierEndDate": null,
        "country": "WW",
        "grandfathered": null
      },
      "isEditable": true,
      "isRequired": false,
      "errorKeys": null
    }
  ],
  "ungrandfatheredIntervals": null,
  "freeTrialDurationType": null,
  "bonusPeriodDurationType": null,
  "versions": [
    {
      "id": "94220663",
      "details": {
        "value": [
          {
            "value": {
              "id": "103677884",
              "name": {
                "value": "Rakuten TV Content",
                "isEditable": true,
                "isRequired": true,
                "errorKeys": null,
                "maxLength": 30,
                "minLength": 2
              },
              "description": {
                "value": "It can be a movie, a season, or an episode",
                "isEditable": true,
                "isRequired": false,
                "errorKeys": null,
                "maxLength": 45,
                "minLength": 10
              },
              "publicationName": null,
              "localeCode": "en-GB",
              "status": "rejected"
            },
            "isEditable": true,
            "isRequired": false,
            "errorKeys": null,
            "isDeletable": true
          },
          {
            "value": {
              "id": "99019863",
              "name": {
                "value": "Content",
                "isEditable": true,
                "isRequired": true,
                "errorKeys": null,
                "maxLength": 30,
                "minLength": 2
              },
              "description": {
                "value": "It can be a movie, a season, or an episode",
                "isEditable": true,
                "isRequired": false,
                "errorKeys": null,
                "maxLength": 45,
                "minLength": 10
              },
              "publicationName": null,
              "localeCode": "en-GB",
              "status": "active"
            },
            "isEditable": true,
            "isRequired": false,
            "errorKeys": null,
            "isDeletable": true
          },
          {
            "value": {
              "id": "99019864",
              "name": {
                "value": "Contenido",
                "isEditable": true,
                "isRequired": true,
                "errorKeys": null,
                "maxLength": 30,
                "minLength": 2
              },
              "description": {
                "value": "It can be a movie, a season, or an episode",
                "isEditable": true,
                "isRequired": false,
                "errorKeys": null,
                "maxLength": 45,
                "minLength": 10
              },
              "publicationName": null,
              "localeCode": "es-ES",
              "status": "active"
            },
            "isEditable": true,
            "isRequired": false,
            "errorKeys": null,
            "isDeletable": true
          },
          {
            "value": {
              "id": null,
              "name": {
                "value": "Contenido de Rakuten TV",
                "isEditable": true,
                "isRequired": true,
                "errorKeys": null,
                "maxLength": 30,
                "minLength": 2
              },
              "description": {
                "value": "It can be a movie, a season, or an episode",
                "isEditable": true,
                "isRequired": false,
                "errorKeys": null,
                "maxLength": 45,
                "minLength": 10
              },
              "publicationName": null,
              "localeCode": "es-ES",
              "status": null
            },
            "isEditable": true,
            "isRequired": false,
            "errorKeys": null,
            "isDeletable": true
          }
        ],
        "isEditable": true,
        "isRequired": false,
        "errorKeys": null
      },
      "contentHosting": null,
      "contentHostingData": null,
      "reviewNotes": {
        "value": null,
        "isEditable": true,
        "isRequired": false,
        "errorKeys": null,
        "maxLength": 4000,
        "minLength": 2
      },
      "reviewScreenshot": {
        "value": {
          "assetToken": "Purple20/v4/21/ea/98/21ea98a4-fff0-a50c-5c08-0918d0e2b6d4/mzl.hxrndrms.jpg",
          "sortOrder": 0,
          "type": "SortedN61ScreenShot",
          "size": 85022,
          "width": 750,
          "height": 1334,
          "checksum": "ad006058f214bf90b70a9eb0e8632a21",
          "url": "https://is5-ssl.mzstatic.com/image/thumb/Purple20/v4/21/ea/98/21ea98a4-fff0-a50c-5c08-0918d0e2b6d4/mzl.hxrndrms.jpg/750x1334ss-80.png",
          "thumbNailUrl": "https://is3-ssl.mzstatic.com/image/thumb/Purple20/v4/21/ea/98/21ea98a4-fff0-a50c-5c08-0918d0e2b6d4/mzl.hxrndrms.jpg/340x340bb-80.png",
          "originalFileName": "iap_screenshot.jpg"
        },
        "isEditable": true,
        "isRequired": false,
        "errorKeys": null
      },
      "merch": {
        "images": [
          {
            "id": null,
            "image": {
              "value": {
                "assetToken": null,
                "originalFileName": null,
                "width": null,
                "height": null
              },
              "isEditable": true,
              "isRequired": false,
              "errorKeys": null
            },
            "status": null
          }
        ],
        "showByDefault": true,
        "isActive": false
      },
      "status": "readyForSale",
      "canBeSubmitted": false
    }
  ],
  "missingRequiredPrivacyPolicyData": false,
  "missingRequiredFamilyDetail": false
}
```

**Comment by beadyui** [comment]
i'm also seeing this when trying to modify an iap, happy to provide more information if required

**Comment by KrauseFx** [comment]
Sorry, I haven't worked with IAP myself, maybe @hjanuschka can help out, but he's currently on parental leave

**Comment by luongm** [comment]
I also encountered this error, and did a bit of debugging myself. The issue I found was that each of the localized version in `versions` array has an ID and its `details` also have an ID. iTunesConnect will throw an error if the any of those ID is missing.

I have made a fix in my fork version (https://github.com/luongm/fastlane) for our usage, but couldn't make a PR because we are using Fastlane 2.43 and I'm having some trouble upgrading my fork from 2.43 to the latest version. I need to spend some more time until I can get this PR out.

**Comment by mpirri** [comment]
Awesome, thanks for looking into this @luongm !  Let us know if you need any help getting the PR prepared.  🚀

**Comment by jgongo** [comment]
Please don't close, still an issue

**Comment by kcornbower** [comment]
@luongm Any progress in getting this PR created? We're experiencing this same issue. Let me know if you need any help.

**Comment by joshdholtz** [comment]
@jgongo Hello 👋 Is this still an issue for you?

**Comment by jgongo** [comment]
@joshdholtz Well, we are manually maintaining IAPs due to this. Has there been any change? Should I test again?

**Comment by joshdholtz** [comment]
@jgongo TBH, I don't know if there were any changes specifically for this but 2017 was a long time ago for both fastlane and the iTunesConnect API 😇 If you don't mind testing again for me that would be 👌 If it still errors out I will add this to my list of things to look into and fix

**Comment by jgongo** [comment]
@joshdholtz I've been busy with some other things. I'll try to test this as soon as possible and let you know the results. Thanks!!

**Comment by joshdholtz** [comment]
@jgongo No problem at all! I know how it goes 😊 Just get back to me whenever you get some time and I will be happy to hit the code again 💪

**Comment by hjanuschka** [comment]
@jgongo  the api is not 💯  it think, as i remember, it fails with a generic operation_failed when you do not set 
`review_notes` and `review_screenshot`  before calling `save!`


so
```ruby
require 'Spaceship'
Spaceship::Tunes.login('########', '#########')
iap = Spaceship::Tunes::Application.all.first.in_app_purchases.all.first.edit
iap.review_notes = "new nots 10 characters"
iap.review_screenshot = "/Users/hja/Desktop/review.jpg"
iap.save!

```

might do the trick, sorry for the troubles i might have introduced.
