### ISSUE TITLE
How to enable/disable capabilities (like push notifications)?

### ISSUE THREAD

**Issue by Emilios1995** [fastlane/fastlane#9827]
Hi, 
I know it is possible to use `xcargs` with gym to specify build settings. but is it possible to add or remove capabilities?

**Comment by mpirri** [comment]
Thanks for writing in, @Emilios1995 !  Can you clarify what you mean by "capabilities" here? Do you mean capabilities as in "UIRequiredDeviceCapabilities" in the `Info.plist`, or something else?

Sorry for the confusion! 🚀
