### ISSUE TITLE
IOS beta Changelog is shortened if a word with 'END' is used in log: E.g DEPENDENCIES

### ISSUE THREAD

**Issue by deanezra** [fastlane/fastlane#9835]
### New Issue Checklist

- [YES ] Updated fastlane to the latest version
- [YES ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When entering the change log in to the CLI at the prompt, entering a changelog that contains a word with the letters: END inside them causes the change log to be shortened. Because the prompt doesn't check for a new line with ONLY 'END'.

For example, as you can see below in output, the word 'DEPENDENCIES' causes the change log to stop just before END.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[12:24:19]: --------------------
[12:24:19]: --- Step: prompt ---
[12:24:19]: --------------------
[12:24:19]: Changelog:
[12:24:19]: Submit inputs using "END"
v0.53 release notes:

DEP**END**ENCIES:

### Environment

NOTE: I replaced sensitive info from fastlane env output with word: OBSCURED.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.0/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.0.5"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Fabric crashlytics beta"
  lane :beta do
    # build your iOS app
    gym(
      scheme: "OBSCURED",
      export_method: 'ad-hoc',
    )
   
    # Prompt for the release notes via the CLI:
    # Ask for a multi-line input
    # The user confirms their input by typing `END` and Enter
    changelog = prompt(
       text: "Changelog: ",
       multi_line_end_keyword: "END"
    )

    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "OBSCURED",
      build_secret: "OBSCURED",
      groups: "OBSCURED",
      notes: changelog 
   )
  end

  desc "Take screenshots of app for each device and send them to iTunes connect"
  lane :screenshots do
    
    # To get a list of all available options for each of the steps, run
    # fastlane action snapshot
    # fastlane action deliver
    snapshot(scheme: "OBSCURED")
    frameit(white: true)
    deliver(
	submit_for_review: false,
	app_version: "1.0",
	skip_binary_upload: true
    )
  end

  private_lane :remove_old_profile do
    #sh("sigh manage -p #{ENV["BUNDLE_IDENTIFIER"]} --force")
    sh("fastlane sigh manage -p OBSCURED --force")
  end

  desc "Update the match profile by pulling new devices from Apple portal"
  lane :updateprofile do
    
    remove_old_profile
    match(type: "adhoc", force_for_new_devices: true)
    match(type: "development", force_for_new_devices: true)
    match(type: "appstore", force_for_new_devices: true)
    #match(type: "development", force: true)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "OBSCURED") # Build your app - more options available
    deliver(
	submit_for_review: false,
	app_version: "1.0",
	skip_screenshots: true,
	skip_metadata: true,
	skip_binary_upload: false
    )
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "OBSCURED" # The bundle identifier of your app
apple_id "OBSCURED" # Your Apple email address

team_id "OBSCURED"  # Developer Portal Team ID

# Spefic that we use the Itunes connect team:
itc_team_id "OBSCURED"
itc_team_name "OBSCURED"

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.47.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.13.6       |
| io-console                | 0.4.5        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.2        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161129 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| faraday_middleware        | 0.10.1       |
</details>

*generated on:* **2017-07-24**
</details>

**Comment by ohayon** [comment]
Hey @deanezra! Thanks for raising the issue... for now I think the quickest/easiest solution would be for you to change the value of the `multi_line_end_keyword` that you are passing to the `prompt` command to something maybe like `DONE`. Let us know if that is helpful! 🐙 🚀

**Comment by deanezra** [comment]
@ohayon Yes that workaround works. Thanks for the tip
