### ISSUE TITLE
[deliver] Submitting a build while another is "waiting for review" overrides metadata only

### ISSUE THREAD

**Issue by MarkVillacampa** [fastlane/fastlane#9845]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When submitting a new build (for the same version number) while another build is "waiting for review" updates the metadata of the build in iTunes Connect, but does not actually replace de .ipa that's going to be reviewed by Apple and sent to the AppStore.

The new build number will appear everywhere in the iTunes Connect as being the build currently being reviewed. The only way to discover the old build is till the one being reviewed is waiting until approved, releasing to the AppStore, downloading the IPA and reading the Info.plist.

In my opinion, Fastlane should just refuse to upload a new build for the same version if one build is already in "waiting for review" status. An optional flag to reject the previous build and submit the new one would be very handy too.

**Comment by mpirri** [comment]
Interesting. Do you think this is actually an Apple iTunesConnect bug? I ask because the version number behavior sounds like maybe they don't properly handle the situation of a second build with the same version number being uploaded without rejecting the first build.

If this is actually an iTC issue, the right solution might be (as you hypothesize) to have `spaceship` issue a reject before submitting the new build.

Thanks for the report!  🚀

**Comment by MarkVillacampa** [comment]
I don't believe this is an iTunes Connect bug per se. You can successfully upload a new build for a version that's already waiting for review, reject the build, and submit the new one via the web interface.

What you can't do via the web interface is submit a new build without rejecting the previous one first. I believe the API call `spaceship` does to submit the build confuses iTunes Connect if there's already a build waiting for review, and it just updates the build metadata but not the actual `ipa` that will be reviewed and released to the store.

The iTunes Connect API should refuse to accept such api call, but since that's an state that's not possible via the web interface, they might have overlooked it.

**Comment by mpirri** [comment]
I think you are exactly right on this. So, `spaceship` should be checking to see if there is already an outstanding build before trying to push up a new one and fail in that case (with a helpful message to reject the outstanding build before sending up a new one)

I'd be remiss, of course, if I didn't try to recruit you to author a patch to fix this in `spaceship`. 😄 We love to review pull requests from our awesome community that fix bugs or add new features to _fastlane_. If that's not your cup of tea, that's cool too, we'll get it fixed soon.

Thanks again!  🚀
