### ISSUE TITLE
For your interest: command-line xcodebuild does not build concurrently

### ISSUE THREAD

**Issue by stanislaw** [fastlane/fastlane#985]
Hello,

I am not creating PR as I am not active user of fastlane so it is better to let you decide how to integrate it:

> Xcode users, add "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu`" to your xcodebuild commands and enjoy #iosdev

taken from https://twitter.com/1101_debian/status/675305084855668738

Cheers!

**Comment by DenHeadless** [comment]
FYI, i've managed to use this with Fastlane by adding following to Gymfile and Scanfile:

```
xcargs "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu`"
```

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it.

**Comment by fabb** [comment]
There is interest for this, as parallelized builds are more than 3 times faster. I guess this could maybe be activated by default? Does it make any problems?

**Comment by stanislaw** [comment]
+1

That's true: fastlane can be faster 3+ times by default and as I said 

> I am not active user of fastlane so it is better to let you decide how to integrate it... 

so I am looking forward to that moment when someone sends PR for to get this really closed.

**Comment by DenHeadless** [comment]
I've been making builds with this stuff enabled for almost 4 months, and haven't seen any problems. Speed up is really noticeable.

```
xcargs "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=`sysctl -n hw.ncpu`"
```

**Comment by stanislaw** [comment]
@DenHeadless could you send a PR then?

**Comment by DenHeadless** [comment]
My solution is local, i'm adding this line to Gymfile and Scanfile, I don't have enough knowledge about fastlane internals to send a PR, unfortunately.

**Comment by TKBurner** [comment]
Thanks for following up community! I'm going to mark this as a feature request and circulate it with the Fastlane  team. Thanks for working with us!

**Comment by ohwutup** [comment]
Hi everyone! Apologies for the back-and-forth, but I am going to close this again as we are working on other sweet things that are going to be coming out shortly. If anyone would like to dig in and make these changes, we would definitely review a PR.

Thanks!
