### ISSUE TITLE
Using Supply to create applications in the developer console?

### ISSUE THREAD

**Issue by braydo25** [fastlane/fastlane#9853]
This is a very quick, general question - does Supply have the ability to create a new listing in the Google Play developer console for an application? From what I've mostly found it's only capable of updating existing applications on the developer console? I say mostly, because this specific issue (https://github.com/fastlane/fastlane/issues/4338) seems to hint at it being possible?

**Comment by PetrosIchor** [comment]
It's not supported by Google's APIs at this time.

**Comment by rockneverdies55** [comment]
Come on google! :open_mouth:
