### ISSUE TITLE
Gym property configuration not using my ad hoc profile

### ISSUE THREAD

**Issue by EugeneTrapeznikov** [fastlane/fastlane#9854]
### New Issue Checklist

- [✅] Updated fastlane to the latest version
- [✅] I have read the [Contribution Guidelines]

### Issue Description

Hi. I want to setup fastlane for my project. I got few targets (app, watchkit app and watchkit extension) plus few third party projects in my workspace. 

My problem is that I can't download a build from crashlytics when I upload it with fastlane, but I can do it when I archive build manualy.

This is my fastlane
    
    lane :beta do

    sh 'bash ./update_version.sh'

    gym(scheme: "MyApp", 
      workspace: "MyApp.xcworkspace",
      configuration: "Ad Hoc Distribution")

    crashlytics(
      api_token: "d543d4a5b27009b...",
      build_secret: "fafb26aa69fa...",
      groups:"myapp-team",
      notifications: true
    )
    end

I add configuration property for gym, because it use Release by default, and I want to use Ad Hoc configuration for distribution, because all Ad Hoc profiles set up in this configuration.

As far as I understand, gym command with configuration property will set Ad Hoc configuration for all targets and projets inside the workspace. Right? 

I tried to emulate what fastlane will do and I setted `Atchive` -> `Build Configuration` -> `Ad Hoc` manually in all targets' and projects' Schemes and archive my project. After that I upload this archive to crashlytics and was able to download this build. So, my profiles are fine and they include my device.

How to check setup fastlane to use exactly same configurations/profiles?

Thank you.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.48.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-07-25**
</details>

**Comment by mpirri** [comment]
When you run _fastlane_, does the output for `gym` indicate which provisioning profile is being used? It definitely seems like the wrong profile is being used.

You might want to try setting `export_method: "ad-hoc"` in your call to `gym` just to make sure it is picking the right profile.

Please let us know how it goes, and if you are still having difficulty. Thanks for writing in! 🚀

**Comment by EugeneTrapeznikov** [comment]
Thank you @mpirri! 
export_method: "ad-hoc" fixed it!
