### ISSUE TITLE
Gym takes forever to sign the app

### ISSUE THREAD

**Issue by asalom** [fastlane/fastlane#9856]
### Issue Description

Gym gets stuck in signing for longer than 40 minutes while running in Travis. Local and more powerful machines are a bit faster but also takes 30+ minutes. We run the lane with bundler, like ```bundle exec fastlane beta```. This lane creates a new keychain with all required certificates, makes it the default keychain, copies provisioning profiles in the right location and then invokes gym which gets stuck in
```
Signing /Users/travis/Library/Developer/Xcode/DerivedData/XXX-brlwqregfdjpmlbkxijfesmeerpf/Build/Intermediates/ArchiveIntermediates/XXX/InstallationBuildProductsLocation/Applications/XXX.app/Frameworks/YYY.framework
```

Travis kills every job that doesn't output to the console for a period of 10 minutes. We already asked support to increase this timeout to 40 minutes and still is not enough.

I read some similar issues to suggest cleaning up duplicated certificates but we are using our own keychain that gets recreated every time so I assume this is not our solution.

### Environment

```bundle exec fastlane env``` was run in my local machine and **not in travis**. The Fastfile should be useful as well as maybe the gems. I did cleanup the Fastfile with only the stuff involving the problematic lane, original is quiet big.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.1                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.1/lib                |
| OpenSSL Version             | OpenSSL 1.1.0e  16 Feb 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "1.80.0"
$XCODEPROJ = "XXX.xcodeproj"
$TARGET = 'DieWeltiPad'
$SCHEME = $TARGET
$VERSION = get_version_number(xcodeproj: "#$XCODEPROJ", target: "XXX")
$TEAM_ID = "XXX"

private_lane :prepare do
  clear_derived_data
  build_number = Time.new.strftime("%Y.%-m.%-d.%-H.%-M") # we need to remove leading zeros from every version component or testflight may complain
  increment_build_number build_number: build_number
end

lane :beta do
  prepare
  prepare_keychain

  gym(
    xcconfig: "config/Debug.xcconfig", # Load extra flags from xcconfig for beta builds
  )

  testflight_upload(skip_submission: true)
  finalize_upload
  clean_keychain
end

private_lane :testflight_upload do |options|
  %x{export DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS="-t DAV"}
  pilot(username: "XXX@XXX.com", skip_submission: options[:skip_submission], skip_waiting_for_build_processing: true)
end

private_lane :finalize_upload do
  sh "cp #{lane_context[SharedValues::IPA_OUTPUT_PATH]} #{lane_context[SharedValues::IPA_OUTPUT_PATH]}.bak"
  sh "cp #{lane_context[SharedValues::DSYM_OUTPUT_PATH]} #{lane_context[SharedValues::DSYM_OUTPUT_PATH]}.bak"

  add_git_tag(prefix: "#$VERSION/")
  push_git_tags

  clean_build_artifacts
end

private_lane :prepare_keychain do
  keychain_name = ENV['KEYCHAIN_NAME']
  keychain_password = ENV['KEYCHAIN_PASSWORD']
  distribution_p12_password = 'XXX'
  create_keychain(
    name: keychain_name,
    password: keychain_password,
    default_keychain: true,
    unlock: true,
    timeout: 3600,
    add_to_search_list: true
  )

  sh("security import X.p12 -k #{keychain_name} -P #{distribution_p12_password}")
  sh("security import XX.p12 -k #{keychain_name} -P ''")
  sh("security import XXX.p12 -k #{keychain_name} -P ''")

  sh("mkdir -p ~/Library/MobileDevice/Provisioning\\ Profiles")
  sh("cp Certificates/*.mobileprovision ~/Library/MobileDevice/Provisioning\\ Profiles/")
end

private_lane :clean_keychain do
  delete_keychain(
    name: ENV['KEYCHAIN_NAME']
  )

  sh("rm -f ~/Library/MobileDevice/Provisioning\\ Profiles/*")
end

before_all do
  ENV['KEYCHAIN_NAME'] = 'ios-build.keychain-db'
  ENV['KEYCHAIN_PASSWORD'] = 'keychain_password'
end

error do |_lane, exception|
  slack(
    message: exception.message,
    success: false
  )
end
```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.47.0  | 🚫 Update available |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| awesome_print             | 1.8.0        |
| babosa                    | 1.0.2        |
| builder                   | 3.2.3        |
| bundler                   | 1.14.6       |
| clipboard                 | 1.1.1        |
| gherkin                   | 4.1.3        |
| cucumber-core             | 1.5.0        |
| cucumber-wire             | 0.0.1        |
| diff-lcs                  | 1.3          |
| multi_json                | 1.12.1       |
| multi_test                | 0.1.2        |
| cucumber                  | 2.4.0        |
| edn                       | 1.1.1        |
| geocoder                  | 1.4.4        |
| httpclient                | 2.8.3        |
| json                      | 1.8.6        |
| command_runner_ng         | 0.1.3        |
| i18n                      | 0.8.6        |
| thor                      | 0.19.4       |
| run_loop                  | 2.4.1        |
| slowhandcuke              | 0.0.3        |
| calabash-cucumber         | 0.20.5       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| cork                      | 0.3.0        |
| nap                       | 1.1.0        |
| open4                     | 1.3.4        |
| claide-plugins            | 0.9.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.1       |
| faraday-http-cache        | 1.3.1        |
| git                       | 1.3.0        |
| kramdown                  | 1.14.0       |
| sawyer                    | 0.8.1        |
| octokit                   | 4.7.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| danger                    | 5.3.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.57.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-07-26**
</details>

**Comment by asalom** [comment]
Solved! You just need to add ```-A``` at the end of all ```security import``` statements, like

```sh("security import XXX.p12 -k #{keychain_name} -P ''" -A)```, found the solution [here](https://github.com/travis-ci/travis-ci/issues/6791#issuecomment-261059084)

**Comment by ohayon** [comment]
Glad to hear you got this sorted out @asalom ! Thanks for sharing your fix! 🚀  🐙
