### ISSUE TITLE
Is there anyway to use Fastlane with Xamarin cross platform project?

### ISSUE THREAD

**Issue by Zapirian** [fastlane/fastlane#9857]
Hi there,

Yes Fastlane bot, I haven't included fastlane env output, but more of a query than an issue but given the lack of an official forum I've decided to post the query here.
I can successfully execute "fastlane init" on the Android project that is included within a Xamarin cross platform solution(using Portable Class Libraries) but not on the iOS project. Is this something that is possible or might be possible to do in the future? Really want to use Fastlane but not on separate Android and iOS apps.

**Comment by mpirri** [comment]
Unfortunately we don't currently support Xamarin with _fastlane_. I wish I had better news, but it isn't really something we have on our roadmap at the moment.

However, some members of the _fastlane_ community have had luck getting various tools working with Xamarin. You might want to try searching our GitHub issues for "Xamarin".

You also might check out the 3rd party _fastlane_ Xamarin build plugin and see if that can help with your workflow: https://github.com/punksta/fastlane-plugin-xamarin_build

Thanks for writing in! 🚀

**Comment by janpio** [comment]
@Zapirian What exactly is going wrong with the iOS project generated by Xamarin? On what platform are you trying this?

**Comment by Zapirian** [comment]
MacOS. I think its the whole shared project using PCLs that mean the structure differs from a stand alone iOS project therefore Fastlane init fails on the iOS project part of the solution.

**Comment by janpio** [comment]
@Zapirian Can you link to a Xamarin open source Github project where I could have a look at the common structure?

**Comment by phenixdotnet** [comment]
@janpio If you're still looking for a Xamarin Forms project to test fastlane, you can find one [here](https://github.com/sthewissen/KickassUI.Spotify).

Problem with `fastlane init` on iOS is fastlane expect to find a `.xcworkspace` or `.xcodeproj` but those file doesn't exists for a Xamarin project.
```
[17:24:56]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[17:24:59]: Couldn't automatically detect the platform
[17:24:59]: Is this project an iOS project? (y/n)
y
[17:25:01]: This setup will help you get up and running in no time.
[17:25:01]: fastlane will check what tools you're already using and set up
[17:25:01]: the tool automatically for you. Have fun!
[17:25:01]: Created new folder './fastlane'.
[17:25:01]: Couldn't automatically detect the project file, please provide a path: .
[17:25:09]: Path must end with either .xcworkspace or .xcodeproj
```

Regards

**Comment by janpio** [comment]
@phenixdotnet Author of the project you linked is not interested in explaining how to build it or provide any links (which is totally fine - see the referenced issue in his repo). Can you enlighten me a bit?
