### ISSUE TITLE
Automating Team Selection when using Spaceship/Sigh for an Apple Developer Account having access to Multiple Development Teams.

### ISSUE THREAD

**Issue by rishijoshi-ibm** [fastlane/fastlane#9858]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Using `sigh` prompts for entering Apple ID (and password for 1st time), logging into which it waits for user input to select a Team on the basis of Numbered Bullets. I wanted to ask if we can automate this step in any possible way so that we don't have to provide a user input on run time when we are using the command.

<details><summary>✅ sigh output ✅</summary>

|           Summary for sigh 2.48.0           |
| adhoc                               | false |
| development                         | false |
| skip_install                        | false |
| force                               | false |
| ignore_profiles_with_different_name | false |
| skip_fetch_profiles                 | false |
| skip_certificate_verification       | false |
| platform                            | ios   |

[16:11:16]: To not be asked about this value, you can specify it using 'username'
[16:11:16]: Your Apple ID Username: username@email.com
[16:11:23]: Starting login with user 'username@email.com'
Multiple teams found on the Developer Portal, please enter the number of the team you want to use: 
1) 1AB123456 "TEAM-A" (In-House)
2) 2AB123456 "TEAM-B" (In-House)
3) 3AB123456 "TEAM-C" (In-House)
4) 4AB123456 "TEAM-D" (Company/Organization)
5) 5AB123456 "TEAM-E" (In-House)
6) 6AB123456 "TEAM-F" (In-House)

</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.11.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.10.1 (Apple Git-78)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.11.6 (15G1510)                  |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.2.1                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.48.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-07-26**
</details>

**Comment by mpirri** [comment]
Interesting idea! What is your preference for how this would be automated? Like would it just pick the first team, or would you specify the team in advance when calling into `sigh` from your Fastfile?

Thanks so much for writing in! 🚀

**Comment by rishijoshi-ibm** [comment]
I don't know much about `sigh`, just that we can't pass TEAM ID as an argument with the command. If that can be done, then it would be great!

For `spaceship` though we have commands like,
> Spaceship::Portal.login("felix@krausefx.com", "password")

where _username_ and _password_ can be passed as parameter, but for selecting Team we need to run the following kind of command which waits for a user interaction and doesn't process unless an input is provided,
> Spaceship::Portal.select_team

If possible, I wanted to have the above option to have Team ID as passing parameter like,
> Spaceship::Portal.select_team("1AB123456")

This could enable us to cater to multiple teams when we run our Continuous Integration setup where before building we can get the latest Provisioning Profile automatically before building the Xcode Project.

Reference: https://github.com/fastlane/fastlane/blob/master/spaceship/docs/DeveloperPortal.md

Thanks !

**Comment by mpirri** [comment]
You can actually do this now with `spaceship`. If you look at this file:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/portal/portal_client.rb
At line 59, there is a method `team_id=` that you can use to set the team_id.

So, you'd do this:
```
Spaceship::Portal.login("felix@krausefx.com", "password")
Spaceship::Portal.team_id = "1AB123456"
```

Is that what you are looking for?

**Comment by joshdholtz** [comment]
@rishijoshi-ibm One thing you _could_ do is to provide `sigh` an account that only has access to one team so that you don't get prompted. This is one of many solutions that you can do but I see this as a best practice in most situations (not sure about your application) as its a nice way to separate concerns and making sure that one account only has permissions to exactly what it needs.

**Comment by ohayon** [comment]
Hey @rishijoshi-ibm, you can also specify your team ID with the `FASTLANE_ITC_TEAM_ID` environment variable. If you dont want to store this in your shell environment directly, you can also put it in a `.env` file in your project directory and just make sure to call `require 'dotenv'; Dotenv.load` at the top of your Fastfile. You can also prefix your _fastlane_ command like so: `FASTLANE_ITC_TEAM_ID=XXXXX fastlane ....` 

Let us know if that is helpful! 🐙 🚀

**Comment by rishijoshi-ibm** [comment]
@mpirri I'm exactly looking for something like this. I put the commands you shared in a Ruby file and ran the Ruby file, but getting the following error:
`in '<main>': undefined method 'team_id=' for Spaceship::Portal:Module (NoMethodError)`

Fastlane Version shows:
`fastlane 2.49.0`

@joshdholtz I don't think that would be feasible. I had thought of that option earlier, but then I can't have separate account for each team. Still, thanks for writing in.

@ohayon Thanks for writing in. I'm currently trying to do something which doesn't depend on Fastfile. Some other solution like running the `Spaceship` commands and calling them via a Ruby file. Though, will try your solution once and let you know if it helps.

**Comment by mpirri** [comment]
@rishijoshi-ibm Whoop!  I meant to type this instead:
```
Spaceship::Portal.client.team_id = "1AB123456"
```

Sorry about the confusion! 🚀

**Comment by rishijoshi-ibm** [comment]
@mpirri Thanks a lot..!! This really helped me. I'm able to use this method as expected.

**Comment by RishabhTayal** [comment]
@mpirri Should this work with `Spaceship::Tunes.client.team_id = "1AB123456"` as well?
