### ISSUE TITLE
App id with identifier <app_identifier> is not available. Please enter a different string.

### ISSUE THREAD

**Issue by fdnhkj** [fastlane/fastlane#9860]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am trying to deploy my first app to the app store but I am facing an issue when running `fastlane produce`.
When creating the app on the Apple Dev Center, it says an app id with Identifier <app_identifier> is not available. Please enter a different string.

However, my app identifier is really specific to me (`com.fidanhakaj.<appname>`) and I am quite confident it is not used by anyone else.
I also tried adding the app id via https://developer.apple.com/account/ios/identifier/bundle but I get the same message. The only app id available is the one in the screenshot below (generated by Xcode).

<img width="727" alt="capture d ecran 2017-07-26 a 16 10 22" src="https://user-images.githubusercontent.com/5569608/28625613-1f95532a-721d-11e7-8545-050baa4da6d0.png">

Maybe it's worth mentioning that at an earlier development stage of the app I want to deploy, I had a free developer account and then switched to the paid developer one (personal). Could it be the app identifier is attached to my free account (email adress is the same though) ?

Thanks for your help!
(sorry if the issue is not fully related to fastlane)

```
MacBook-Pro-de-Fidan:ios hakaj$ fastlane produce
[15:43:12]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile

+----------------+----------------------------+
|         Summary for produce 2.48.0          |
+----------------+----------------------------+
| username       | <username>      |
| app_identifier | <app_identifier> |
| sku            | <sku>                 |
| platform       | ios                        |
| language       | English                    |
| skip_itc       | false                      |
| skip_devcenter | false                      |
| team_id        | <team_id>                 |
| itc_team_id    | <itc_team_id>                 |
+----------------+----------------------------+

[15:43:17]: To not be asked about this value, you can specify it using 'app_name'
[15:43:17]: App Name: <AppName>
[15:43:29]: Creating new app '<AppName>' on the Apple Dev Center
[15:43:33]: Sending crash report...
[15:43:33]: The stacktrace is sanitized so no personal information is sent.
[15:43:33]: To see what we are sending, look here: /Users/hakaj/.fastlane/latest_crash.json
[15:43:33]: Learn more at https://github.com/fastlane/fastlane#crash-reporting
[15:43:33]: You can disable crash reporting by adding `opt_out_crash_reporting` at the top of your Fastfile

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue

[!] Apple provided the following error info:
	An App ID with Identifier '<app_identifier>' is not available. Please enter a different string.
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | false                                       |
| Is homebrew                 | true                                        |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.48.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "<AppName>") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "<AppName>") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "<app_identifier>" # The bundle identifier of your app
apple_id "<apple_id>" # Your Apple email address
itunes_connect_id "<itunes_connect_id>"     # iTunes Connect Account

team_id "<team_id>" # Developer Portal Team ID
itc_team_id "<itc_team_id>" # iTunes Connect Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.48.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.6        |
| terminal-notifier         | 1.7.1        |
| unicode-display_width     | 1.1.3        |
| terminal-table            | 1.7.3        |
| plist                     | 3.2.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.0        |
| bundler                   | 1.14.6       |
| faraday_middleware        | 0.11.0.1     |
</details>

*generated on:* **2017-07-26**
</details>

**Comment by mpirri** [comment]
It does sound to me like the app id is owned by a different account, likely your older free developer account. Can you still log into that account? If so, you can delete the App Id there from the Apple developer portal.

If that doesn't work, definitely reach out to Apple's developer portal technical support - I'd expect they could help you out with this.

Thanks for writing in! 🚀

**Comment by fdnhkj** [comment]
@mpirri Thanks for the quick reply!

I just found some info on apple forums about this: https://forums.developer.apple.com/thread/43677

And it confirms what you said :)
Xcode added the app id automatically on my free account after selecting 'automatically manage signing'. Then, after getting my paid account, I couldn't get the same app id anymore as it was used by my free one.

The issue is that there are no way to access developer portal with the free account.
People reported contacting them and they replied with: "We can't do any deleting operation for any account".

Thank you Apple! 🤦🏻‍♂️

**Comment by mpirri** [comment]
Wow, that's really frustrating! I'm surprised/disappointed that Apple doesn't have a "Team Selector" for picking between your paid and free accounts if you are using the same AppleId for both.

I hope you are able to keep working without access to that bundle id, it is annoying to have to change away from a good bundle id because of a limitation like this in the tools.

**Comment by fdnhkj** [comment]
Indeed, frustrating!
I even tried adapting the requests done by the developer portal with postman (by replacing the paid team id parameter with the free one) with no success 😒

I just contacted them via https://developer.apple.com/contact/submit/ (*Certificates, Identifiers, Profiles* category) as a last try. I'll update this issue if I have any additional info.

**Comment by fdnhkj** [comment]
Contacting them via that form helped! I have access to the same app identifier.
Now I am facing an issue with `fastlane init` command 😅 I'll create another issue :)
