### ISSUE TITLE
Snapshot issue with simulators with multiple parenthesis

### ISSUE THREAD

**Issue by buscarini** [fastlane/fastlane#9874]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I have a simulator which is called: "iPad Pro (12.9-inch) (2nd generation)", which is the default name that Xcode picked for it. I added this name into Snapfile as such:

 devices([
    "iPhone 7 Plus",  
    "iPad Pro (12.9-inch)  (2nd generation)"
  ])

Fastlane complains with this:

[15:24:02]: --- Step: Verifying required fastlane version ---
[15:24:02]: -------------------------------------------------
[15:24:02]: Your fastlane version 2.49.0 matches the minimum requirement of 1.11.0  ✅
[15:24:02]: ------------------------------
[15:24:02]: --- Step: default_platform ---
[15:24:02]: ------------------------------
[15:24:02]: Driving the lane 'ios screenshots' 🚀
[15:24:02]: ----------------------
[15:24:02]: --- Step: snapshot ---
[15:24:02]: ----------------------
[15:24:03]: Error setting value '["iPhone 7 Plus", "iPad Pro (12.9-inch) (2nd generation)"]' for option 'devices'
+------------------+-----------------+
|            Lane Context            |
+------------------+-----------------+
| DEFAULT_PLATFORM | ios             |
| PLATFORM_NAME    | ios             |
| LANE_NAME        | ios screenshots |
+------------------+-----------------+
[15:24:04]: Device 'iPad Pro (12.9-inch) (2nd generation)' not in list of available simulators 'iPhone 7, iPhone 7 Plus, generation)'

I renamed it in Snapfile as "generation)", which worked, but then in the preview document it didn't show up.

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.3.1                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.3.1/bin/fastlane         |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.3.1/lib                |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | es_ES.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.49.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.3        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.4.5        |
| plist                     | 3.2.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.54.0       |
| faraday                   | 0.10.0       |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20161021 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.13.6       |
| faraday_middleware        | 0.10.1       |
| io-console                | 0.4.5        |
</details>

*generated on:* **2017-07-27**
</details>

<br/>

 This is not such a big deal, as it can be solved just by renaming the simulator (just removing "(2nd generation)" will suffice) but maybe someone else might have a problem trying to figure out what is going on.

**Comment by ohayon** [comment]
Hey @buscarini - apologies for the issues, we would definitely rather you have the correct name setup in your Snapfile rather than something that might happen to work  😄 . If you are cool with deleting all of your simulators, would you mind running `fastlane snapshot reset_simulators` to try to fix this issue by recreating all of your simulators that then should be assigned the proper names?

Also, worth asking here - what version of Xcode are you running? If you run `xcode-select -p` does it point you at a beta version of Xcode or an 8.x version? 

Thanks! 🚀

**Comment by buscarini** [comment]
No problem 😊 

Creating iPhone 4s for iOS version iOS 10.3
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPhone 5 for iOS version iOS 10.3
Creating iPhone 5s for iOS version iOS 10.3
Creating iPhone 6 for iOS version iOS 10.3
Creating iPhone 6 Plus for iOS version iOS 10.3
Creating iPhone 6s for iOS version iOS 10.3
Creating iPhone 6s Plus for iOS version iOS 10.3
Creating iPhone 7 for iOS version iOS 10.3
Creating iPhone 7 Plus for iOS version iOS 10.3
Creating iPhone SE for iOS version iOS 10.3
Creating iPad 2 for iOS version iOS 10.3
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPad Retina for iOS version iOS 10.3
An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=161):
Incompatible device
Creating iPad Air for iOS version iOS 10.3
Creating iPad Air 2 for iOS version iOS 10.3
Creating iPad (5th generation) for iOS version iOS 10.3
Creating iPad Pro (9.7-inch) for iOS version iOS 10.3
Creating iPad Pro (12.9-inch) for iOS version iOS 10.3
Creating iPad Pro (12.9-inch) (2nd generation) for iOS version iOS 10.3
Creating iPad Pro (10.5-inch) for iOS version iOS 10.3
Creating Apple TV 1080p for tvOS version tvOS 10.2
Creating Apple Watch - 38mm for watchOS version watchOS 3.2
Creating Apple Watch - 42mm for watchOS version watchOS 3.2
Creating Apple Watch Series 2 - 38mm for watchOS version watchOS 3.2
Creating Apple Watch Series 2 - 42mm for watchOS version watchOS 3.2
Creating device pair of 08C3FE7D-908D-4740-89C0-00C5CDA68E78 and 2E33C739-66D5-4324-8A34-1652C04D468E


And this is my Xcode version:
Version 8.3.3 (8E3004b)

I also have a beta 2 of Xcode 9, but I'm not currently using it. *xcode-select -p* points to "/Applications/Xcode.app/Contents/Developer", which is the stable version.

**Comment by ohayon** [comment]
Hey @buscarini - thanks for giving that a run... Did that help your issue now that it renamed the simulator device? 😄
