### ISSUE TITLE
Can we fetch groups from fastlane pilot?? I can't find any help in documentation or code.

### ISSUE THREAD

**Issue by mohdumairakbar** [fastlane/fastlane#9877]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
I am trying to fetch fastlane pilot groups, to show the available groups to which user can distribute app for testing.

But i do not see any attribute or parameter to fetch the group data 

Please help

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by mpirri** [comment]
@mohdumairakbar Currently `pilot` does not allow you to get a list of TestFlight groups, but you can do it directly from `spaceship` (the iTunesConnect interface library under `pilot`).

Specifically, you can call the `all` or `find` methods on `Spaceship::TestFlight::Group`,  as implemented here:
https://github.com/fastlane/fastlane/blob/master/spaceship/lib/spaceship/test_flight/group.rb

I hope this is helpful! 🚀
