### ISSUE TITLE
[!] SSL_connect returned=1 errno=0 state=error: certificate verify failed

### ISSUE THREAD

**Issue by T-Jedsada** [fastlane/fastlane#9878]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

<img width="1273" alt="screen shot 2560-07-27 at 10 25 01 pm" src="https://user-images.githubusercontent.com/24611167/28678440-9f4b2a4c-731a-11e7-8feb-b00f23f7ff29.png">

**Comment by T-Jedsada** [comment]
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.12.6                              |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.12.2                   |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.12.6 (16G29)             |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | false                                |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |


### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |


### fastlane files:

**No Fastfile found**


**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.49.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 1.8.1        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.11.0.1     |
</details>


*generated on:* **2017-07-27**
</details>

**Comment by ohayon** [comment]
Hey @T-Jedsada - would you mind sharing a bit more of your terminal output so we can have a bit more context as to how you are calling the s3 action? Thank you!! 💯 👍

**Comment by T-Jedsada** [comment]
<img width="1389" alt="screen shot 2560-07-27 at 10 45 36 pm" src="https://user-images.githubusercontent.com/24611167/28679431-5f0168e0-731d-11e7-8ce1-715deccc7a6a.png">
<img width="1389" alt="screen shot 2560-07-27 at 10 45 43 pm" src="https://user-images.githubusercontent.com/24611167/28679432-5f46446a-731d-11e7-86f7-b37394c8dd44.png">

**Comment by ohayon** [comment]
Hey @T-Jedsada, sorry I should have been more clear, could you copy and paste in this output, including the output from before the crash so we can see what sort of things are going on before it fails? Thank you!! 😄

**Comment by T-Jedsada** [comment]
@ohayon I went to upload file apk to s3 sorry i talk not clear.

**Comment by KrauseFx** [comment]
Could you try the following

```
def suggest_ruby_reinstall(e)
      ui = FastlaneCore::UI
      ui.error "-----------------------------------------------------------------------"
      ui.error e.to_s
      ui.error ""
      ui.error "SSL errors can be caused by various components on your local machine."
      if Gem::Version.new(RUBY_VERSION) < Gem::Version.new('2.1')
        ui.error "Apple has recently changed their servers to require TLS 1.2, which may"
        ui.error "not be available to your system installed Ruby (#{RUBY_VERSION})"
      end
      ui.error ""
      ui.error "The best solution is to use the self-contained fastlane version."
      ui.error "Which ships with a bundled OpenSSL,ruby and all gems - so you don't depend on system libraries"
      ui.error " - Use Homebrew"
      ui.error "    - update brew with `brew update`"
      ui.error "    - install fastlane using:"
      ui.error "      - `brew cask install fastlane`"
      ui.error " - Use One-Click-Installer:"
      ui.error "    - download fastlane at https://download.fastlane.tools"
      ui.error "    - extract the archive and double click the `install`"
      ui.error "-----------------------------------------------------------"
      ui.error "for more details on ways to install fastlane please refer the documentation:"
      ui.error "-----------------------------------------------------------"
      ui.error "        🚀       https://docs.fastlane.tools          🚀   "
      ui.error "-----------------------------------------------------------"
      ui.error ""
      ui.error "You can also install a new version of Ruby"
      ui.error ""
      ui.error "- Make sure OpenSSL is installed with Homebrew: `brew update && brew upgrade openssl`"
      ui.error "- If you use system Ruby:"
      ui.error "  - Run `brew update && brew install ruby`"
      ui.error "- If you use rbenv with ruby-build:"
      ui.error "  - Run `brew update && brew upgrade ruby-build && rbenv install 2.3.1`"
      ui.error "  - Run `rbenv global 2.3.1` to make it the new global default Ruby version"
      ui.error "- If you use rvm:"
      ui.error "  - First run `rvm osx-ssl-certs update all`"
      ui.error "  - Then run `rvm reinstall ruby-2.3.1 --with-openssl-dir=/usr/local`"
      ui.error ""
      ui.error "If that doesn't fix your issue, please google for the following error message:"
      ui.error "  '#{e}'"
      ui.error "-----------------------------------------------------------------------"
    end
```

**Comment by T-Jedsada** [comment]
@KrauseFx thank

**Comment by KrauseFx** [comment]
Glad to help 👍

**Comment by T-Jedsada** [comment]
@KrauseFx Sorry, It not work
