### ISSUE TITLE
How do I generate the newest iTunes metadata with Fastlane?

### ISSUE THREAD

**Issue by AndyIbanez** [fastlane/fastlane#9879]
Hello guys. Sorry for asking here, but I have asked in a couple of places (the iOS Developers slack group, Reddit), and never receive any answers to this question.

I created an app a few months ago for iOS 10 and submitted it to iTunes. This was before WWDC, so the new metadata requirements did not exist.

What command do I have to run to make Fastlane generate the newest required metadata files for my project?

**Comment by KrauseFx** [comment]
Hey @AndyIbanez, thanks for submitting this issue. You can use the following command
```
fastlane deliver download_metadata
```

**Warning:** This will overwrite your local metadata with whatever you have on iTunes Connect

**Comment by AndyIbanez** [comment]
Thanks @KrauseFx, I will give it a go now.
