### ISSUE TITLE
Use Already Cloned Repo for Match

### ISSUE THREAD

**Issue by lswith** [fastlane/fastlane#9884]
### Issue Description
The fastlane match tool seems to always re-clone the match repository. It would be nice to simply point to an already cloned repo, have git then fetch the latest changes and then push any updates, rather than having to reclone the entire repository again.

**Comment by PetrosIchor** [comment]
What about cloud based CI where the environments are temporary?

If you're concerned about pull time, bandwidth usage, or size you can use the shallow clone and branch only options.  It's what I use in house for the ~200 profiles and certs that need to sync across infrastructure and development machines.

That said, you could probably achieve this with 2 lines in your gitconfig.  Have requests going out to your remote repository redirect to a local path
