### ISSUE TITLE
Unsupported screen size [2049, 1536] for path '.../iPadPro(9.7inch)-abc_framed.png'

### ISSUE THREAD

**Issue by kitefaster** [fastlane/fastlane#9886]
### Issue Description

FrameIt is producing 2049x1536 images when the original screenshot was 2048x1536.  Deliver is failing because the screenshot is the wrong resolution.

### Framefile.json

```
{
  "device_frame_version": "latest",
  "default": {
    "title": {
      "font": "./fonts/SF-UI-Display-Regular.otf",
      "color": "#FFFFFF"
    },
	"background": "./background.jpg",
    "padding": 50,
    "show_complete_frame": false
  },
  
  "data": [
     {
	   "filter": "iPadPro(12.9inch)",
	   "padding": 30,
	   "show_complete_frame": true
	 },
     {
	   "filter": "iPadPro(9.7inch)",
	   "padding": 80
	 },
     {
       "filter": "iPhone",
	   "padding": 55
     }
   ]
}
```

##### Complete output when running fastlane, including the stack trace and command used

[22:50:21]: Unsupported screen size [2049, 1536] for path './iPadPro(9.7inch)-abc_framed.png'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | opt_out_usage                       | 0           |
| 2    | Verifying required fastlane version | 0           |
| 3    | default_platform                    | 0           |
| 4    | cocoapods                           | 2           |
| 💥    | deliver                             | 7           |
+------+-------------------------------------+-------------+

[22:50:21]: fastlane finished with errors

[!] Unsupported screen size [2049, 1536] for path './iPadPro(9.7inch)-abc_framed.png'

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.49.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| CFPropertyList            | 2.3.3        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.45.4       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.2        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.4        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.3      |
| google-api-client         | 0.12.0       |
| json                      | 1.8.3        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| faraday_middleware        | 0.10.0       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
</details>

*generated on:* **2017-07-27**
</details>

**Comment by ohayon** [comment]
Hmmm... thanks for raising the issue @kitefaster, apologies for the issues you are having. We will take a look at this issue and figure out the best way to fix it! 🚀

**Comment by RishabhTayal** [comment]
Having this issue too.
