### ISSUE TITLE
Gym auto selects provisioning profile mapping wrong in an Xcode project with multiple configs

### ISSUE THREAD

**Issue by dral3x** [fastlane/fastlane#9890]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Running the lane `deploy_testflight`, gym generate a plist file with the wrong provisioning profile 
```
[13:27:07]: Generated plist file with the following values:
[13:27:07]: ▸ -----------------------------------------
[13:27:07]: ▸ {
[13:27:07]: ▸   "provisioningProfiles": {
[13:27:07]: ▸     "com.xxx.yyy${BUNDLE_ID_SUFFIX}": "xxx Dev AdHoc Distribution"
[13:27:07]: ▸   },
[13:27:07]: ▸   "method": "app-store"
[13:27:07]: ▸ }
[13:27:07]: ▸ -----------------------------------------
```
`BUNDLE_ID_SUFFIX` is a user define config variabile I have in my project.
It's value, for a TestFlight build (`ProdRelease` config) is empty btw.

The problem is that the chosen provisioning profile is wrong. To deploy the app on TestFlight, the AppStore distribution profile must be used.
The Xcode project is correctly configured to do so

---

Edit by @joshdholtz: This method is the causing this issue when Xcode project have multiple configurations - https://github.com/fastlane/fastlane/blob/6a82b16373568b0d2cd793998dd6164503831aef/gym/lib/gym/detect_values.rb#L89-L120. It sometimes selects the wrong profile and makes things go 💥 

---

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.5                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0                          |
| Installation Source         | /usr/local/bin/fastlane                     |
| Host                        | Mac OS X 10.12.5 (16F73)                    |
| Ruby Lib Dir                | /usr/local/Cellar/ruby/2.4.0/lib            |
| OpenSSL Version             | OpenSSL 1.0.2j  26 Sep 2016                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.1                                       |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
xcode_select "/Applications/Xcode.app"

# Fastlane constants
fastlane_version "2.7.0"
default_platform :ios
itc_uri = "https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/ng/app/" + "xyz"

platform :ios do

  before_all do
    
    # Shared information
    ENV['APP_MARKETING_VERSION'] = `cd .. && agvtool what-marketing-version -terse1 | tr -d '\n'`

  end

  desc "Build and deploy app for public testing on TestFlight"
  lane :deploy_testflight do
    
    # Check ENV
    raise "Please specify SLACK_URL inside `.env` file before run this lane again".red unless ENV['SLACK_URL']
    raise "Please specify SLACK_USERNAME inside `.env` file before run this lane again".red unless ENV['SLACK_USERNAME']
    
    # Ensure what-to-test is up-to-date
    UI.header "testflight-what-to-test.txt"
    UI.message(File.read("./metadata/testflight-what-to-test.txt"))
    unless UI.confirm("Is the what-to-test correct?")
      UI.user_error!("Please update `testflight-what-to-test.txt` file.")
    end

    # Build
    build_ipa(environment: 'prod')

    # Upload and share build with external betatesters
    upload_ipa_testflight

    # Notify on Slack
    slack({
      message: "*Radio iOS #{ENV['APP_MARKETING_VERSION']}* has been uploaded and it's waiting for betatesting review 🚀",
      success: true,
      username: "#{ENV['SLACK_USERNAME']} (fastlane)",
      channel: '#releases',
      payload: {
        'CHANGELOG' => "```" + File.read("./metadata/testflight-what-to-test.txt") + "```"
        },
      default_payloads: [], # No default payload
      })

  end

  desc "Build ipa for AppStore or Ad-Hoc distribution"
  private_lane :build_ipa do |options|

    # Check options
    scheme = ""
    output = ""
    configuration = ""
    export = ""

    case options[:environment]
    when 'prod'
      scheme = "Radio Prod"
      output = "Radio Prod"
      configuration = "ProdRelease"
      export = "app-store"
    
    when 'dev'
      scheme = "Radio Dev"
      output = "Radio Dev"
      configuration = "DevRelease"
      export = "ad-hoc"
    
    when 'beta'
      scheme = "Radio Beta"
      output = "Radio Beta"
      configuration = "BetaRelease"
      export = "ad-hoc"
    
    else
      UI.user_error!("Invalid environment passed to lane: #{options[:environment]}")
    end

    UI.message("Building scheme `#{scheme}` with configuration `#{configuration}`")

    # pod install
    cocoapods

    # Build
    gym(
      scheme: scheme,
      output_name: output,
      configuration: configuration,
      export_method: export
      )

  end

  desc "Upload ipa (PROD) to TestFlight and HockeyApp"
  private_lane :upload_ipa_testflight do

    # Check ENV
    raise "Please specify HOCKEYAPP_TOKEN inside `.env` file before run this lane again".red unless ENV['HOCKEYAPP_TOKEN']
    raise "Please specify SLACK_URL inside `.env` file before run this lane again".red unless ENV['SLACK_URL']
    raise "Please specify SLACK_USERNAME inside `.env` file before run this lane again".red unless ENV['SLACK_USERNAME']

    # Upload build to iTunesConnect
    pilot(
      username: ENV['FASTLANE_USERNAME'],
      changelog: File.read("./metadata/testflight-what-to-test.txt"),
      beta_app_description: File.read("./metadata/testflight-description.txt"),
      beta_app_feedback_email: "xxx@yyy.com",
      distribute_external: true,
      skip_submission: true
      )

    # Send dSYM to HockeyApp
    upload_ipa_hockeyapp(
      environment: 'prod',
      notes: "New build available in AppStore for external testers."
      )

    # Notify on Slack
    slack({
      message: "Uploaded Radio iOS (PROD) app #{ENV['APP_MARKETING_VERSION']} to TestFlight",
      success: true,
      channel: '#bot',
      username: "#{ENV['SLACK_USERNAME']} (fastlane)",
      payload: {
        'iTunes Connect link' => itc_uri
        },
      default_payloads: [], # No default payload
      })

  end

  desc "Upload ipa to HockeyApp"
  private_lane :upload_ipa_hockeyapp do |options|

    raise "Please specify `environment` parameter".red unless options[:environment]

    identifier = ""
    dsym_only = false
    notes = options[:notes] || "New build available on HockeyApp."

    case options[:environment]
    when 'prod'
      identifier = '123'
      dsym_only = true
    
    when 'dev'
      identifier = '456'
      dsym_only = false
    
    when 'beta'
      identifier = '789'
      dsym_only = false
    
    else
      UI.user_error!("Invalid environment passed to lane: #{options[:environment]}")
    end

    UI.message("Uploading dsym only? #{dsym_only}")

    hockey(
      api_token: ENV['HOCKEYAPP_TOKEN'],
      upload_dsym_only: dsym_only,
      public_identifier: identifier,
      notes: notes
      )

  end

  #
  # On lane success
  #
  after_all do |lane|

    unless is_ci?
      # Mac OS notification
      notification(
        title: "Radio iOS 🚀: 👍", 
        message: "#{lane} succeded!"
        )
    end

  end

  #
  # On lane failure
  #
  error do |lane, exception|

    unless is_ci?
      # Mac OS notification
      notification(
        title: "Radio 🚀: 🔥", 
        message: "#{lane} failed: #{exception.message}"
        )
    end

  end
end

# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
# More information: https://github.com/fastlane/fastlane/blob/master/docs/Appfile.md

for_lane :dev do
  app_identifier "com.xxx.yyy.dev"
  app_icon "./Resources/AppIcon-dev-1024.png"
end

for_lane :beta do
  app_identifier "com.xxx.yyy.beta"
  app_icon "./Resources/AppIcon-beta-1024.png"
end
```
</details>

### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.47.0  | 🚫 Update available |

### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-framer | 0.2.0   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| bundler                   | 1.14.3       |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| io-console                | 0.4.6        |
| excon                     | 0.57.1       |
| openssl                   | 2.0.2        |
| plist                     | 3.3.0        |
| faraday                   | 0.12.2       |
| jwt                       | 1.5.6        |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| terminal-table            | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| fastlane-plugin-framer    | 0.2.0        |
</details>

*generated on:* **2017-07-28**
</details>

**Comment by joshdholtz** [comment]
Ended up solving this issue with @dral3x in the fasten slack team.

### Cause of the issue
https://github.com/fastlane/fastlane/blob/6a82b16373568b0d2cd793998dd6164503831aef/gym/lib/gym/detect_values.rb#L62-L65

### Temporary solution
Add `export_options. provisioningProfiles` (like below) to short circuit the `self.detect_selected_provisioning_profiles` method (from above) to not automatically select provisioning profiles. There is some issue when having multiple configurations were this method actually grabs the wrong profile from the config. 

I have personally experienced this issue as well so I will handle the fixing this (somehow) so other people don't run into it since the current solution isn't a very straight forward one 😇 

```rb
gym(
      scheme: scheme,
      output_name: output,
      configuration: configuration,
      export_method: export,

     # We added this right here to make things work
      export_options: {
        provisioningProfiles: {}
      }
)
```

**Comment by dral3x** [comment]
Thank you so much @joshdholtz for helping me out on this! 👍

**Comment by ohayon** [comment]
Thanks for helping out @joshdholtz !! Glad this got solved! Going to close the issue for now, but if something comes up please feel free to continue discussion here 🚀 🐙

**Comment by joshdholtz** [comment]
Opening this cause actual issue but going to rename the title and edit some of the description 😊

**Comment by daltonclaybrook** [comment]
We are still seeing this issue in version 2.53.1

**Comment by joshdholtz** [comment]
@daltonclaybrook Thanks for letting me know of the version number that last worked for you! Huge help ✊ Will make this easier to look into 😊

**Comment by chefnobody** [comment]
Ignorant question: An Xcode Project within a workspace that has more than one target each having more than one build configuration is a really common Cocoa Pod setup, right?

**Comment by dral3x** [comment]
@chefnobody I think it is.
You have an app with unit tests and ui tests targets (it's the default), with cocoapods for handling all dependencies (so your project is inside a workspace) and, by default (again), you have 2 build configuration, `Debug` and `Release` where each have a separate Provisioning Profiles.
I don't think it's very unlikely to have a setup like this. It's almost *any* application

**Comment by joshdholtz** [comment]
@chefnobody I agreed with @drakar4ik that that answer sounds like it could be a yes 🙃 I'm 99% sure this problem doesn't have anything to do with cocoapods though. Its a problem with having multiple bundle identifiers. Or something 😇

**Comment by daltonclaybrook** [comment]
@dral3x in my case, I have two framework targets, and about 10 different app targets which all use different bundle IDs and produce different app binaries. I feel like this is a somewhat unique setup.

**Comment by joshdholtz** [comment]
@daltonclaybrook 10 might be unique but I don't think having more than 1 is terribly unique 🤔  I usually have multiple for different environments.

 I am working on a different PR right now but will be attempting to tackle this issue later tonight ✊

**Comment by joshdholtz** [comment]
@chefnobody I super appreciate the offer! I have a project or two that are messed up on mysids so I will see what I can initially come up with tonight as I think I have a hunch. But I would definitely love some help testing out my solution with your setup to see if it works for other people besides me 😊 

The `nil` is suuuppppeeeerrrrr weird though! I don't know if I've seen that 🤔 And the empty hash worked as a solution in my case so our setups must be somewhat similar but also a big different 😇

I will post back here though when I have a somewhat working thing for you review my code and to test with 💪 ❤️

**Comment by chefnobody** [comment]
Sweet! I'll fork and take a stab at debugging further, as well.

**Comment by chefnobody** [comment]
Did a little research locally..

I think there are two issues (at least for my use-case):

1. I do not have a `PRODUCT_BUNDLE_IDENTIFIER` set in any of the Project Target app's Build Configurations. This explains the `nil` for key in `provisioning_profile_mapping`, I believe. Namely because `current["PRODUCT_BUNDLE_IDENTIFIER"]` returns `nil`. So, ddding 
`PRODUCT_BUNDLE_IDENTIFIER` at the main Project level still didn't show up in the `current` hash. There is possibly an issue with how the build settings are set in that hash. Those Build Configurations are set to use the CocoaPods generated .xcconfigs, but Product Bundle Identifier resolves in Xcode, so.... I will keep digging, there.

2. Now, this is not wise, but If I just hardcode a `bundle_identifier` (ex: "oreos") instead of use whatever is discerned from the Target's Build Configuration's build settings, that resolves the `nil` key issue. However, because the Bundle Identifier does not differ between Build Configurations the hash only ever has one key in it. This means for any projects where the Bundle Identifier is the same across all Build Configurations only _last_ Build Configuration in the list (`target.build_configuration_list.build_configurations`) will always be used as the detected Provisioning Profile. I think. That said I wonder ... is it common for Build Configurations for a Target to have differing `PRODUCT_BUNDLE_IDENTIFIER` values?

**Comment by joshdholtz** [comment]
Hello fellow gym signing issue family 👋  Got a PR up with some fixes and better warnings for these errors ^

**Comment by taquitos** [comment]
Quick question: since I don't have anything setup to test this unique config, maybe @daltonclaybrook, @chefnobody, or @dral3x could try out the [referenced PR](https://github.com/fastlane/fastlane/pull/10085)?

**Comment by thasegaw** [comment]
>  This means for any projects where the Bundle Identifier is the same across all Build Configurations only the last Build Configuration in the list (target.build_configuration_list.build_configurations) will be used as the detected Provisioning Profile

This issue has occurred because Gym collects all Provisioning Profiles that are set to each Configuration(like `Debug`, `Release`).
 
First of all, xcodebuild command needs only one Configuration.
If user specify it, xcodebuild use this, or else xcodebuild use default value that is set in Xcode Project.

Therefore, I think that Gym needs only Provisioning Profiles that user-specified Configuration has.

Following patch works fine for me.
```
--- a/gym/lib/gym/code_signing_mapping.rb
+++ b/gym/lib/gym/code_signing_mapping.rb
@@ -106,6 +103,7 @@ module Gym

     def detect_project_profile_mapping
       provisioning_profile_mapping = {}
+      specified_configuration = Gym.config[:configuration] || Gym.project.default_build_settings(key: "CONFIGURATION")

       self.project_paths.each do |project_path|
         UI.verbose("Parsing project file '#{project_path}' to find selected provisioning profiles")
@@ -116,6 +114,7 @@ module Gym
             target.build_configuration_list.build_configurations.each do |build_configuration|
               current = build_configuration.build_settings
               next if test_target?(current)
+              next unless specified_configuration == build_configuration.name

               bundle_identifier = current["PRODUCT_BUNDLE_IDENTIFIER"]
               provisioning_profile_specifier = current["PROVISIONING_PROFILE_SPECIFIER"]
```

**Comment by joshdholtz** [comment]
@thasegaw `Gym.project.default_build_settings(key: "CONFIGURATION")` exactly what I was trying to look of the other night but couldn't find it! Thanks for pointing that out to me. I can drop this in my PR and trying it out in my sample projects 👌

**Comment by zapjonny** [comment]
Xcode 9 GM broke my setup and I ended up here... For some reason **Detected provisioning profile mapping {...}**  where ... is incorrect mappings. It uses debug profiles where adhoc/inhouse profiles are needed. This worked with latest Xcode 8.x...

**Comment by zapjonny** [comment]
Sorry, this is still an issue and should be opened...

**Comment by KrauseFx** [comment]
Please create a new issue, with the complete output of `fastlane env` instead of commenting on older, closed ones :+1:
