### ISSUE TITLE
fastlane appending path to lane call

### ISSUE THREAD

**Issue by gregj4iiii** [fastlane/fastlane#9898]
### New Issue Checklist

- [ ✅] Updated fastlane to the latest version
- [✅ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Fastlane is appending the path to the fast lane bin in the call to the fast lane lane, so it cannot find the lane.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

This is the script the bot will run
```#!/bin/sh
cd ${XCS_PRIMARY_REPO_DIR}/App
which fastlane
/Users/xcodeserver/.rvm/gems/ruby*/wrappers/fastlane pretrigger_git --verbose
/Users/xcodeserver/.rvm/gems/ruby*/wrappers/fastlane env`
```

```
[16:48:11]: [33mFor more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
DEBUG [2017-07-28 16:48:14.15]: Checking if there are any plugins that should be loaded...
INFO [2017-07-28 16:48:14.26]: [32m-------------------------------------------------[0m
INFO [2017-07-28 16:48:14.26]: [32m--- Step: Verifying required fastlane version ---[0m
INFO [2017-07-28 16:48:14.26]: [32m-------------------------------------------------[0m
INFO [2017-07-28 16:48:14.26]: Your fastlane version 2.49.0 matches the minimum requirement of 2.46.0  ✅
INFO [2017-07-28 16:48:14.26]: [32m------------------------------[0m
INFO [2017-07-28 16:48:14.26]: [32m--- Step: default_platform ---[0m
INFO [2017-07-28 16:48:14.26]: [32m------------------------------[0m
WARN [2017-07-28 16:48:14.26]: [33m[33mLane Context:[0m
INFO [2017-07-28 16:48:14.26]: {:DEFAULT_PLATFORM=>:ios}
ERROR [2017-07-28 16:48:14.26]: [31mCould not find lane '/Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/wrappers/fastlane pretrigger_git'. Available lanes: ios test, ios beta, ios release, ios release_testflight, ios pretrigger_git, ios test_strings[0m
INFO [2017-07-28 16:48:14.26]: [32mSuccessfully generated documentation at path '/Users/xcodeserver/Library/Caches/XCSBuilder/Bots/bef1ec531b653f7ba397a46df72f56cd/Source/projectname/projectdirectory/fastlane/README.md'[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-07-28 16:48:14.27]: [31mfastlane finished with errors[0m
/Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane_core/lib/fastlane_core/ui/interface.rb:131:in `user_error!': [31m[!] Could not find lane '/Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/wrappers/fastlane pretrigger_git'. Available lanes: ios test, ios beta, ios release, ios release_testflight, ios pretrigger_git, ios test_strings[0m (FastlaneCore::Interface::FastlaneError)
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane/lib/fastlane/runner.rb:29:in `execute'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.49.0/bin/fastlane:20:in `<top (required)>'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xcodeserver/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
[16:48:16]: [33mFor more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile[0m
[16:48:18]: [32m-------------------------------------------------[0m
[16:48:18]: [32m--- Step: Verifying required fastlane version ---[0m
[16:48:18]: [32m-------------------------------------------------[0m
[16:48:18]: Your fastlane version 2.49.0 matches the minimum requirement of 2.46.0  ✅
[16:48:18]: [32m------------------------------[0m
[16:48:18]: [32m--- Step: default_platform ---[0m
[16:48:18]: [32m------------------------------[0m
+------------------+-----+
|      [33mLane Context[0m      |
+------------------+-----+
| DEFAULT_PLATFORM | ios |
+------------------+-----+
[16:48:18]: [31mCould not find lane '/Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/wrappers/fastlane env'. Available lanes: ios test, ios beta, ios release, ios release_testflight, ios pretrigger_git, ios test_strings[0m

+------+-------------------------------------+-------------+
|                     [32mfastlane summary[0m                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

[16:48:18]: [31mfastlane finished with errors[0m
[31m
[!] Could not find lane '/Users/xcodeserver/.rvm/gems/ruby-2.4.0@global/wrappers/fastlane env'. Available lanes: ios test, ios beta, ios release, ios release_testflight, ios pretrigger_git, ios test_strings[0m
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.4                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0/bin/fastlane         |
| Host                        | Mac OS X 10.12.4 (16E195)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.2                                       |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_CA.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.46.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number()

    # Commit the version bump
    commit_version_bump(xcodeproj: "App.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    cert
    sigh
    gym(scheme: "CodeDrop")#Build your app - more options available
    pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Scheme") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc "Deploy a testflight release for App"
  lane :release_testflight do
    cert
    sigh
    pilot(ipa: ENV['XCS_PRODUCT'])
  end

  desc "Increment the build and version numbers as a pre-trigger lane so that the .ipa is of the right version and build number on testflight"
  lane :pretrigger_git do
    # match(type: "appstore") # more information: https://codesigning.guide
    # Ensure that your git status is not dirty
    ensure_git_status_clean
    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_version_number( bump_type:'patch')
    increment_build_number()
    # Commit the version bump
    commit_version_bump(xcodeproj: "App.xcodeproj")
    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    varBuild=Actions.lane_context[Actions::SharedValues::BUILD_NUMBER]
    varVersion=Actions.lane_context[Actions::SharedValues::VERSION_NUMBER]
    varTag="CI_TestFlightBuild_#{varBuild}_v#{varVersion}"
    puts "#{varTag}"
    add_git_tag(
    tag: varTag
    )
    # Push the new commit and tag back to your git remote
    push_to_git_remote
  end

  lane :test_strings do
    varBuild=1
    varVersion=2
    varTag="CI_TestFlight_v#{varVersion}_Build:#{varBuild}"
    puts "#{varTag}"
  end


  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "" # The bundle identifier of your app
apple_id "" # Your Apple email address

team_id "" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.49.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.3       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| openssl                   | 2.0.2        |
| faraday                   | 0.12.2       |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| faraday_middleware        | 0.12.0       |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
</details>

*generated on:* **2017-07-28**
</details>

**Comment by PetrosIchor** [comment]
According to the error, your lanes are scoped for platforms.  You need to include your platform target when running: `fastlane ios pretrigger_git`

**Comment by ohayon** [comment]
Hey @gregj4iiii like @PetrosIchor mentioned, it looks like you might be able to run the command as he put it above. But also it looks like something could be going a little wonky with that script that you have thats running fastlane. If you run the lane from your command line directly, do you see the same issue? 🐙

**Comment by gregj4iiii** [comment]
@PetrosIchor Thank you for the reply, adding using `fast lane ios pre trigger_git` resulted in fast lane calming there was no lane called 'ios'.

@ohayon You are exactly right, turns out that '/Users/xcodeserver/.rvm/gems/ruby*/wrappers/fastlane pretrigger_git --verbose' was calling on the global system ruby through rvm and for whatever reason the /wrappers/ hook was not reading the command line arguments...as arguments?

Solved the issue by simply specifying the ruby version like so '/Users/xcodeserver/.rvm/gems/ruby-2.4.0/wrappers/fastlane pretrigger_git --verbose'

Thank you everyone for all your help!
