### ISSUE TITLE
Allow `sh` action to run from project root folder, not fastlane folder.

### ISSUE THREAD

**Issue by ajmccall** [fastlane/fastlane#990]
Is it possible to make the `sh` action (is it an action, can't find it in the [Actions](https://github.com/fastlane/fastlane/blob/master/docs/Actions.md) doc?) run in the root folder instead of the `fastlane` folder.

For instance
```ruby
lane :test_sh do
  sh "touch where_am_i.txt"
end
```
creates the file `./fastlane/where_am_i.txt`.

Obviously I could modify my scripts with a `../` but this would break my CI while I convert to Fastlane.

Thanks

http://stackoverflow.com/questions/33524932/fastlanes-run-sh-action-in-xcode-project-root-folder

**Comment by jcampbell05** [comment]
I believe there is a chDir action or something around those lines which you could wrap your script in which changes where your script is running from :)

**Comment by ajmccall** [comment]
Are you suggesting to use `chdir` before running the script? Like
```ruby
lane :test_sh do
  sh "chdir .. && touch where_am_i.txt"
end```
This has the following error.
```
Exit status of command 'chdir .. && touch where_am_i.txt' was 127 instead of 0.
```

**Comment by jcampbell05** [comment]
No fastlane  support Ruby's chdir (http://ruby-doc.org/core-2.2.0/Dir.html#method-c-chdir):

'''ruby
lane :test_sh do
 chdir ".." do
   sh "touch where_am_i.txt"
 end
end
'''

**Comment by ajmccall** [comment]
Sorry, one more time. I might be a ruby noob, but the your lane proposed throws the following error.

`Could not find action or lane 'chdir'. Check out the README for more details: https://github.com/KrauseFx/fastlane`

**Comment by KrauseFx** [comment]
It's `Dir.chdir` :+1:

**Comment by KrauseFx** [comment]
But instead it's better to use `sh "cd .. && touch something"`

**Comment by ajmccall** [comment]
(y) thanks. That makes perfect sense.
