### ISSUE TITLE
Change resources and some source code before gym 

### ISSUE THREAD

**Issue by Mbt925** [fastlane/fastlane#9902]
I want to change some of my app general settings, like app name, firebase analytics .json config file, fabric API key, and some assets. Is is possible to changes these via some custom scripts before compiling the source code?

**Comment by Mbt925** [comment]
It is a general question about fastlane. it's not related to a specific version.

**Comment by PetrosIchor** [comment]
Fastlane is written in Ruby and had a simple shell action. Yes, it'll totally do all that you listed.

**Comment by Mbt925** [comment]
I could not find anything related to the matter. Can you help me with a link to the appropriate doc?

**Comment by PetrosIchor** [comment]
https://docs.fastlane.tools

**Comment by Mbt925** [comment]
:). I meant a part of doc, related to writing custom actions or codes.

**Comment by PetrosIchor** [comment]
Well, the Fastlane docs can't exactly teach you to program.  Your initial post is large and complex.  For example:

`app name`` = modifications to a mobile app. Android, iOS, other? What language or format?
`firebase analytics .json config file` = modifying a file with a specific date structure
`fabric API key` = generic value
` and some assets` = I'm guessing you mean images/video?

By using Ruby, shell, fastlane, and fastlane plugins you can certainly do all those things! I do all of them in my projects.  However, there isn't going to be a one click solution. 

You listed a number of very different problems to solve.  I'd advise you to isolate each problem, break it down into smaller parts, then see how to solve it using the Fastlane.

**Comment by Mbt925** [comment]
Both iOS and Android. I am wondering that doing these stuff with fastlane is easier or writing a Mac application and then using fastlane for distribution?

**Comment by ohayon** [comment]
Hey @Mbt925 - I think a good approach for changing certain values in your configuration is to start with changing info plist values using the `set_info_plist_value` action. Maybe get started there and that will help become a bit more familiar with the territory 😄  🐙  Here are some docs https://docs.fastlane.tools/actions/#set_info_plist_value let us know if we can help any further!

**Comment by Mbt925** [comment]
Thank you for directing me to the right path.
