### ISSUE TITLE
Snapshot repeats the same device-language configuration 

### ISSUE THREAD

**Issue by ariok** [fastlane/fastlane#9903]
### Issue Description
When I launch snapshot on my local machine it seems that the `Snapfile` configuration is only partially read. I'm currently listing 3 devices and 3 languages but the snapshots are only executed for the first device and the first language in loop... I've seen something like 5 executions for the same "device-language" configuration, then I stopped the script. 

I've seen this output 5 times in the same run, and I confirm that my simulator for iPhone 5 launched for  5 times...

```
[14:01:42]: ---------------------------
[14:01:42]: --- iPhone 5 - en-US ---
[14:01:42]: ---------------------------
```

Here is my current Snapfile content: 

```
devices([
   "iPhone 5",
   "iPhone 6",
   "iPad"
])

languages([
  "en-US",
  "de-DE",
  "it-IT"
])

scheme "ui-tests"
output_directory "./screenshots"
project "../ND.xcodeproj"

```

### Environment

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.12.5                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.12.5 (16F73)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.3.3                                                          |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.49.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.4        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 1.10.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.8.0        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.3        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.45.4       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 2.0.2        |
| public_suffix             | 2.0.4        |
| addressable               | 2.5.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| faraday                   | 0.12.2       |
| little-plugger            | 1.1.4        |
| multi_json                | 1.11.0       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.0       |
| json                      | 1.8.3        |
</details>

*generated on:* **2017-07-31**
</details>

**Comment by ohayon** [comment]
Hey @ariok - apologies for this issue! Would you mind sharing some more of your terminal output so we can see some more context? Also, it would be helpful to see how you are calling `snapshot` (whether its directly from the command line or if it is from a Fastfile), if it is from a Fastfile, it would be great to see the lane you are using to execute the action. Thanks! 🐙 !

**Comment by ariok** [comment]
Thank you @ohayon I was able to run snapshots without issues after removing watch build from target dependencies. Probably it was just a misconfiguration...
