### ISSUE TITLE
Selecting provisioning profile entitlement with match

### ISSUE THREAD

**Issue by Brandt1981** [fastlane/fastlane#9908]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I am working with an automaker on a CarPlay app and the have a CarPlay entitlement that needs to be associated with their provisioning profiles. When using Match, I don't see a way to do this, so I have to go in and manually change the profile entitlement from Default to their CarPlay entitlement. If there is a way, please help me find the documentation on this.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

### Captured Output

Command Used: `env`
<details><summary>Output/Log</summary>

```


Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `length' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60length'%20for%20nil+repo:fastlane/fastlane
➡️  Error Handler not protected from nil on line 238
    https://github.com/fastlane/fastlane/issues/9905 [open] 1 💬
    an hour ago

➡️  Actions::EnsureGitStatusCleanAction.run(nil) Crashes on Dirty Branch
    https://github.com/fastlane/fastlane/issues/9747 [open] 3 💬
    2 weeks ago

➡️  fastlane pilot find: undefined method `length' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/8885 [closed] 1 💬
    2 weeks ago

and 20 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60length'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.


```

</details>

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                            |
| --------------------------- | ------------------------------------------------ |
| OS                          | 10.12.5                                          |
| Ruby                        | 2.4.1                                            |
| Bundler?                    | false                                            |
| Git                         | git version 2.13.2 (Apple Git-90)                |
| Installation Source         | ~/.rbenv/versions/2.4.1/bin/fastlane             |
| Host                        | Mac OS X 10.12.5 (16F73)                         |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.1/lib                      |
| OpenSSL Version             | OpenSSL 1.0.2l  25 May 2017                      |
| Is contained                | false                                            |
| Is homebrew                 | false                                            |
| Is installed via Fabric.app | false                                            |
| Xcode Path                  | /Applications/Xcode-beta.app/Contents/Developer/ |
| Xcode Version               | 9.0                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| json                      | 2.0.2        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| bundler                   | 1.15.3       |
| faraday_middleware        | 0.12.0       |
| io-console                | 0.4.6        |
| openssl                   | 2.0.3        |
</details>

*generated on:* **2017-07-31**
</details>

**Comment by Brandt1981** [comment]
You can see an example of associating an entitlement with the provisioning profile here: 

https://github.com/fastlane/fastlane/issues/4548#issuecomment-246020321

**Comment by Brandt1981** [comment]
Relates to this issue https://github.com/fastlane/fastlane/issues/8463

**Comment by ohayon** [comment]
Hey @Brandt1981 - currently match does not support entitlements. We have talked about supporting this and it could come down the pipe eventually! 🚀

**Comment by AWrightIV** [comment]
My team will also benefit from adding support for these. I've attached a screenshot below with an example of the Developer Apple site where the entitlement option is offered. All names and unique identifiers are obfuscated.

![provisioning profile with entitlements](https://i.imgur.com/dQxSfd9.png)

**Comment by KrauseFx** [comment]
We recently merged https://github.com/fastlane/fastlane/pull/9912, does that help?

**Comment by AWrightIV** [comment]
@KrauseFx That looks relevant. I'll do some testing and confirm.

**Comment by KrauseFx** [comment]
Awesome, thanks 👍

**Comment by Brandt1981** [comment]
It selected the correct entitlement for the profile.

**Comment by KrauseFx** [comment]
Wohooo 🚀 I'll close the issue for now then
