### ISSUE TITLE
Exit status: 1 Xcode couldn't find a provisioning profile matching 'Extension'

### ISSUE THREAD

**Issue by capecrawler** [fastlane/fastlane#9909]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
First time to use Fastlane and I am trying to create a build, export and distributed to Fabric.
My app has an extension and when trying to call gym for adhoc, I get this error.
```
[01:46:08]: Exit status: 1

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.50.0                  |
| export_method | ad-hoc                  |
| sdk           | iPhoneOS10.3.sdk        |
+---------------+-------------------------+

[01:46:08]: ▸ === BUILD TARGET {Extension Target} OF PROJECT {Project Name} WITH CONFIGURATION Release ===
[01:46:08]: ▸ Check dependencies
[01:46:08]: ▸ No profiles for '{Extension bundle ID}' were found:  Xcode couldn't find a provisioning profile matching '{Extension bundle ID}'.
[01:46:08]: ▸ Code signing is required for product type 'App Extension' in SDK 'iOS 10.2'
```

I am using the following for my fastlane file. I have created an Adhoc build configuration on Xcode and set a provisioning profile created using `fastlane match adhoc`.

```
    match(type: "adhoc",
      app_identifier: <App Bundle ID>)

    match(type: "adhoc",
      app_identifier:  <Extension Bundle ID>)

    gym(scheme: <scheme>,
        workspace: <workspace>,        
        include_bitcode: false,
        configuration: "Adhoc",
        clean: true,
        export_method: 'ad-hoc',
        xcargs: "ARCHIVE=YES" # Used to tell the Fabric run script to upload dSYM file
        )

```

**Comment by ohayon** [comment]
Hey @capecrawler - would you mind sharing all of the output from your terminal as well as the output of `fastlane env` so we can have some more context to help debug this? 😄  Thanks!! 🐙

**Comment by capecrawler** [comment]
Hi @ohayon, here is the output. Thanks for checking out. :D


<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.2.4                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane         |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib                  |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016                  |
| Is contained                | true                                        |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.49.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end


  desc "Create certificates"
  # circles123 for passphrase
  lane :certificates do
    match(app_identifier: ["com.circles.selfcare", "com.circles.selfcare.UsageExtension"], readonly: true)
  end


  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    #disable_automatic_code_signing    
    match(type: "adhoc",
      app_identifier: "com.circles.selfcare")

    match(type: "adhoc",
      app_identifier:  "com.circles.selfcare.UsageExtension")

    gym(scheme: 'Selfcare',
        workspace: "Selfcare.xcworkspace",        
        include_bitcode: false,
        configuration: "Adhoc",
        clean: true,
        export_method: 'ad-hoc',
        xcargs: "ARCHIVE=YES" # Used to tell the Fabric run script to upload dSYM file
        )


    emails = values[:test_email] ? values[:test_email] : ['mario@circles.asia'] #['jagdevi@circles.asia', 'xyriz@circles.asia', 'mario@circles.asia', 'albert@circles.asia', 'qa_builds@icloud.com'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '1b8890141bd3562273481de87f208a176cced11b',
             build_secret: '2bab54810e4dceca952941b3361bc7633be534979c0e6790266b3e417fcf82b4',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?


    #pilot
    #enable_automatic_code_signing

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end


desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta_release do
    disable_automatic_code_signing    
    match(git_url: "https://mario_cape@bitbucket.org/mario_cape/liberty-appstore-certificates.git",
      type: "appstore",
      app_identifier: "com.circles.selfcare")

    match(git_url: "https://mario_cape@bitbucket.org/mario_cape/liberty-appstore-certificates.git",
      type: "appstore",
      app_identifier:  "com.circles.selfcare.UsageExtension")

    gym(scheme: 'Selfcare',
        workspace: "Selfcare.xcworkspace",        
        include_bitcode: false,
        configuration: "Release",
        clean: true,
        export_method: 'app-store',
        xcargs: "ARCHIVE=YES" # Used to tell the Fabric run script to upload dSYM file
        )
  end







  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Selfcare") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.circles.selfcare" # The bundle identifier of your app
apple_id "mobile.tech@circles.asia" # Your Apple email address

team_id "5Y8LG9HWCS" # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| activesupport             | 4.2.7.1      |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.3       |
| claide                    | 1.0.1        |
| cocoapods                 | 1.2.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| cocoapods-trunk           | 1.1.2        |
| cocoapods-try             | 1.1.0        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander                 | 4.4.3        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20161129 |
| dotenv                    | 2.2.0        |
| escape                    | 0.0.4        |
| excon                     | 0.54.0       |
| faraday                   | 0.11.0       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| fourflusher               | 2.0.1        |
| fuzzy_match               | 2.0.4        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| i18n                      | 0.7.0        |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 2.9.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.1.0        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| molinillo                 | 0.5.7        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nap                       | 1.1.0        |
| netrc                     | 0.7.8        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| ruby-macho                | 0.2.6        |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.0        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| thread_safe               | 0.3.5        |
| tty-screen                | 0.5.0        |
| tzinfo                    | 1.2.2        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.2      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.4        |
| xcpretty-travis-formatter | 0.0.4        |
</details>


*generated on:* **2017-08-01**
</details>

**Comment by ohayon** [comment]
Hey @capecrawler thanks for sharing that! Does your extension have the same bundle ID as your main app?

**Comment by capecrawler** [comment]
Hi @ohayon, my extension has different bundle ID than the main app.
