### ISSUE TITLE
prevent mac from going into standby

### ISSUE THREAD

**Issue by bb-git** [fastlane/fastlane#9913]
I would like fastlane to prevent my mac from going to sleep, until the build was uploaded and processed by Apple. Is there an easy way without changing the energy settings?

**Comment by ohayon** [comment]
Hey @bb-git _fastlane_ does not currently support this type of option, but you could run `caffinate -t <number of seconds to stay awake>` in another terminal to prevent your Mac from sleeping 😴  🐙 . Let us know if we can help with anything else! 🚀
