### ISSUE TITLE
Deliver fails to precheck URLs which return 30x HTTP status codes

### ISSUE THREAD

**Issue by jgongo** [fastlane/fastlane#9927]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

While using `Deliver` to upload metadata to iTunes Connect I got a failure when checking for broken URLs. All the URLs that were failing share a common trait: they redirect to another URL using a 302 HTTP status code. I guess `Deliver` is checking for the URLs to return a 2xx code and is not following redirections to really find out if the final URL is correctly loading.

Here you have the output of the command _(Including only the relevant part of the output)_. You can manually check any of the URLs.

```
$ bundle exec fastlane deliver --app_version "3.2.6" --username xxxxxxxx@xxxxxx.xxx
...
[18:28:19]: Running precheck 👮‍♀️ 👮

+--------------------+-------------------------+
|         Summary for precheck 2.47.0          |
+--------------------+-------------------------+
| default_rule_level | warn                    |
| app_identifier     | tv.wuaki.Wuakitv-Player |
| username           | jose.gonzalez@wuaki.tv  |
| team_id            | 1263804                 |
| team_name          | Wuaki TV S.L.           |
+--------------------+-------------------------+

[18:28:19]: Checking app for precheck rule violations
[18:28:28]: ✅  Passed: No negative  sentiment
[18:28:28]: ✅  Passed: No placeholder text
[18:28:28]: 😵  Failed: No mentioning  competitors-> mentioning other platforms, like Android or Blackberry
[18:28:28]: ✅  Passed: No future functionality promises
[18:28:28]: ✅  Passed: No words indicating test content
[18:28:28]: ✅  Passed: No curse words
[18:28:28]: ✅  Passed: Incorrect, or missing copyright date
[18:28:39]: 😵  Failed: No broken urls-> unreachable URLs in app metadata
+------------------------------+--------------------------------------------+
|                            Potential problems                             |
+------------------------------+--------------------------------------------+
| Field                        | Failure reason                             |
+------------------------------+--------------------------------------------+
|  tv privacy policy: (fr-FR) | found: google                              |
|  tv privacy policy: (en-GB) | found: google                              |
|  tv privacy policy: (it)    | found: google                              |
|  tv privacy policy: (de-DE) | found: google                              |
| marketing URL: (it)          | https://www.rakuten.tv                     |
| marketing URL: (es-ES)       | https://www.rakuten.tv                     |
| marketing URL: (en-GB)       | https://www.rakuten.tv                     |
| marketing URL: (fr-FR)       | https://www.rakuten.tv                     |
| marketing URL: (de-DE)       | https://www.rakuten.tv                     |
| privacy URL: (fr-FR)         | https://fr.rakuten.tv/pages/privacy_policy |
| privacy URL: (en-GB)         | https://uk.rakuten.tv/pages/privacy_policy |
| privacy URL: (it)            | https://it.rakuten.tv/pages/privacy_policy |
| privacy URL: (de-DE)         | https://de.rakuten.tv/pages/privacy_policy |
| privacy URL: (es-ES)         | https://es.rakuten.tv/pages/privacy_policy |
+------------------------------+--------------------------------------------+
```

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                                         |
| --------------------------- | ----------------------------------------------------------------------------- |
| OS                          | 10.12.6                                                                       |
| Ruby                        | 2.4.0                                                                         |
| Bundler?                    | true                                                                          |
| Git                         | git version 2.11.0 (Apple Git-81)                                             |
| Installation Source         | ~/Documents/projects/rakuten/ios/ios-v3/vendor/bundle/ruby/2.4.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                                      |
| Ruby Lib Dir                | ~/.rbenv/versions/2.4.0/lib                                                   |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                                                   |
| Is contained                | false                                                                         |
| Is homebrew                 | false                                                                         |
| Is installed via Fabric.app | false                                                                         |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                                   |
| Xcode Version               | 8.3.3                                                                         |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
fastlane_version "2.29.0"

default_platform :ios

platform :ios do
  desc "Install dependencies"
  lane :pods do
    cocoapods(use_bundle_exec: true)
  end


  desc "Runs Wuaki-iOS tests"
  lane :test do
    scan(scheme: 'wuaki-ios-sim', devices: ['iPhone 7'], code_coverage: true, output_directory: 'build/reports/tests')
    slather(workspace: 'wuaki-ios.xcworkspace', proj: 'wuaki-ios/wuaki-ios.xcodeproj', scheme: 'wuaki-ios-sim', output_directory: 'build/reports/coverage', html: true, use_bundle_exec: true)
  end


  desc "Badge the Spartan app icon with version and build number"
  lane :badge_app_icon do
    assetsPath = 'wuaki-ios/wuaki-ios/resources/images/WKAssets.xcassets'
    version = get_version_number(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj', target: 'wuaki-ios')
    build = get_build_number(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj')

    # Copy original app icons
    sh("cp #{ENV['PWD']}/#{assetsPath}/AppIcon.appiconset/*.png #{ENV['PWD']}/#{assetsPath}/AppIcon.spartan.appiconset/")
    badge(glob: '/**/AppIcon.spartan.appiconset/*.png', shield: "#{version}-#{build}-orange", shield_io_timeout: 30)
  end


  desc "Submit a new Wuaki-iOS Beta Build to Apple TestFlight"
  lane :beta do |options|
    # match(type: "appstore") -> Share certificates, not right now

    ensure_git_status_clean
    increment_build_number(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj')
    scheme = options[:external_beta] == true ? 'wuaki-ios' : 'wuaki-ios-spartan'

    if options[:external_beta] != true
      badge_app_icon
      appIcons = Dir["#{ENV['PWD']}/wuaki-ios/wuaki-ios/resources/images/WKAssets.xcassets/AppIcon.spartan.appiconset/*.png"]
      git_add(path: appIcons)
      git_commit(path: appIcons, message: 'Badge app icon')
    end

    gym(workspace: 'wuaki-ios.xcworkspace', scheme: scheme, output_directory: 'build/ipa', output_name: 'wuaki-ios.ipa')
    pilot(ipa: 'build/ipa/wuaki-ios.ipa', distribute_external: options[:external_beta] == true)

    commit_version_bump(xcodeproj: 'wuaki-ios/wuaki-ios.xcodeproj')
    add_git_tag
    push_to_git_remote
  end


  desc "Deploy a new Wuaki-iOS version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: 'wuaki-ios')
    deliver(force: true)
    # frameit
  end


  after_all do |lane|
    # nothing right now
  end


  error do |lane, exception|
  end
end
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "tv.wuaki.Wuakitv-Player" # The bundle identifier of the app
apple_id "mobile@wuaki.tv"               # Apple email address -> This should be put elsewhere

team_id "NQ7GNB56L5"                     # Developer Portal Team ID

itc_team_name "Wuaki TV S.L."            # iTunes Connect team name
itc_team_id "1263804"                    # iTunes Connect team id (from https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/user/detail)
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.0        |
| bundler                   | 1.15.3       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| i18n                      | 0.8.1        |
| minitest                  | 5.10.2       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.3        |
| activesupport             | 4.2.8        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| curb                      | 0.9.3        |
| fastimage                 | 2.1.0        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.0       |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
| badge                     | 0.8.4        |
| clamp                     | 0.6.5        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.2.0        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.7.8        |
| cocoapods-trunk           | 1.2.0        |
| cocoapods-try             | 1.1.0        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 0.2.6        |
| cocoapods                 | 1.2.0        |
| mini_portile2             | 2.1.0        |
| nokogiri                  | 1.6.8.1      |
| slather                   | 2.4.1        |
</details>

*generated on:* **2017-08-02**
</details>

**Comment by ohayon** [comment]
Hey @jgongo - apologies for the issues you are having! I have just spent some time trying to reproduce this locally and put the URLs into my own app's metadata and then ran `fastlane precheck` on it. Everything is working as expected for me. Is it possible that for one reason or another, those links were redirecting to URLs that were returning a non-200 status for a bit? Have you tried checking all those URLs manually? 🐙

**Comment by jgongo** [comment]
Hi @ohayon . Thanks a lot for your your prompt response!
I have just checked again, both running the whole `deliver` command and running only `precheck`, and I get failures with both of them. I have network connectivity (I uploaded all the metadata to iTunes Connect without any problem), and if I put the URLs in my browser I get correctly redirected to the final page:
- https://www.rakuten.tv gets redirected to https://es.rakuten.tv/ (you get redirected depending on your geo-located IP)
- https://es.rakuten.tv/pages/privacy_policy gets redirected to https://es.rakuten.tv/terms_conditions/614

I have attached the files corresponding to the es-ES locale for the marketing and privacy URL in case there is anything strange in those files causing fastlane to fail. Any other idea? 😢 

[marketing_url.txt](https://github.com/fastlane/fastlane/files/1196897/marketing_url.txt)
[privacy_url.txt](https://github.com/fastlane/fastlane/files/1196898/privacy_url.txt)

**Comment by sheinix** [comment]
Hi, I'm facing the same problem here.
`Failed: No broken urls-> unreachable URLs in app metadata`

`+------------------------+-----------------------------------------+
|                        Potential problems                        |
+------------------------+-----------------------------------------+
| Field                  | Failure reason                          |
+------------------------+-----------------------------------------+
| support URL: (en-US)   | unreachable: https://www.mascoteros.com |
| support URL: (es-ES)   | unreachable: https://www.mascoteros.com |
| marketing URL: (en-US) | unreachable: https://www.mascoteros.com |
| marketing URL: (es-ES) | unreachable: https://www.mascoteros.com |
| privacy URL: (es-ES)   | unreachable: https://www.mascoteros.com |
+------------------------+-----------------------------------------+
`

**Comment by janpio** [comment]
When you open `https://www.mascoteros.com`  in your normal browser, where are you redirected to?

**Comment by sheinix** [comment]
To the same site/url.

**Comment by janpio** [comment]
So your problem is not about `precheck` not being able to handle URLs that return a `30x` status code?

**Comment by sheinix** [comment]
Yes, sorry about that. I have the same output but probably another cause.

**Comment by janpio** [comment]
Yep, that was what I was getting at ;) Best create a new issue for that and see if other people have the same problem.
