### ISSUE TITLE
unable to write to /usr/bin when executing sudo gem install fastlane -NV

### ISSUE THREAD

**Issue by allensmith81** [fastlane/fastlane#9928]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When trying to install fastlane on OSx 10.13 beta with I am getting the following error:

/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/xcodebuild_helper.rb
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you
```
sudo gem install fastlane -NV
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=fastlane
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/api/v1/dependencies?gems=CFPropertyList,addressable,babosa,bundler,colored,commander-fastlane,dotenv,excon,faraday,faraday-cookie_jar,faraday_middleware,fastimage,gh_inspector,google-api-client,highline,json,mini_magick,multi_json,multi_xml,multipart-post,plist,rubyzip,security,slack-notifier,terminal-notifier,terminal-table,tty-screen,word_wrap,xcodeproj,xcpretty,xcpretty-travis-formatter
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=claide,colored2,nanaimo
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=googleauth,httpclient,mime-types,representable,retriable
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=declarative,declarative-option,uber
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mime-types-data
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rouge
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=public_suffix
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=unicode-display_width
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=jwt,logging,memoist,os,signet
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=little-plugger
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=http-cookie
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=domain_name
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=unf
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=unf_ext
200 OK
GET https://api.rubygems.org/quick/Marshal.4.8/xcodeproj-1.5.1.gemspec.rz
200 OK
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/LICENSE
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/README.md
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/bin/xcodeproj
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/command.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/command/config_dump.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/command/project_diff.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/command/show.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/command/sort.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/command/target_diff.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/config.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/config/other_linker_flags_parser.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/constants.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/differ.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/gem_version.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/helper.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/plist.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/case_converter.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/build_configuration.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/build_file.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/build_phase.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/build_rule.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/configuration_list.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/container_item_proxy.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/file_reference.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/group.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/helpers/file_references_factory.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/helpers/groupable_helper.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/native_target.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/reference_proxy.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/root_object.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object/target_dependency.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object_attributes.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object_dictionary.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/object_list.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/project_helper.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project/uuid_generator.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/abstract_scheme_action.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/analyze_action.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/archive_action.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/build_action.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/buildable_product_runnable.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/buildable_reference.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/command_line_arguments.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/environment_variables.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/launch_action.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/macro_expansion.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/profile_action.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/test_action.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/scheme/xml_element_wrapper.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/user_interface.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/workspace.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/workspace/file_reference.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/workspace/group_reference.rb
/Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.1/lib/xcodeproj/xcodebuild_helper.rb
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/bin directory.### Environment
```

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                |
| --------------------------- | ------------------------------------ |
| OS                          | 10.13                                |
| Ruby                        | 2.2.4                                |
| Bundler?                    | false                                |
| Git                         | git version 2.13.2 (Apple Git-90)    |
| Installation Source         | ~/.fastlane/bin/bundle/bin/fastlane  |
| Host                        | Mac OS X 10.13 (17A315i)             |
| Ruby Lib Dir                | ~/.fastlane/bin/bundle/lib           |
| OpenSSL Version             | OpenSSL 1.0.2g  1 Mar 2016           |
| Is contained                | true                                 |
| Is homebrew                 | false                                |
| Is installed via Fabric.app | false                                |
| Xcode Path                  | /Library/Developer/CommandLineTools/ |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| CFPropertyList            | 2.3.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bigdecimal                | 1.2.6        |
| bundler                   | 1.14.6       |
| claide                    | 1.0.1        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.0        |
| excon                     | 0.55.0       |
| faraday                   | 0.12.1       |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.11.0.1     |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| google-api-client         | 0.12.0       |
| googleauth                | 0.5.1        |
| highline                  | 1.7.8        |
| http-cookie               | 1.0.3        |
| httpclient                | 2.8.3        |
| hurley                    | 0.2          |
| io-console                | 0.4.3        |
| json                      | 1.8.1        |
| jwt                       | 1.5.6        |
| libxml-ruby               | 3.0.0        |
| little-plugger            | 1.1.4        |
| logging                   | 2.2.2        |
| memoist                   | 0.15.0       |
| mime-types                | 3.1          |
| mime-types-data           | 3.2016.0521  |
| mini_magick               | 4.5.1        |
| minitest                  | 5.4.3        |
| multi_json                | 1.12.1       |
| multi_xml                 | 0.6.0        |
| multipart-post            | 2.0.0        |
| nanaimo                   | 0.2.3        |
| nokogiri                  | 1.5.6        |
| os                        | 0.9.6        |
| plist                     | 3.2.0        |
| power_assert              | 0.2.2        |
| psych                     | 2.0.8        |
| public_suffix             | 2.0.5        |
| rake                      | 10.4.2       |
| rdoc                      | 4.2.0        |
| representable             | 3.0.4        |
| retriable                 | 2.1.0        |
| rouge                     | 1.11.1       |
| rubygems-update           | 2.5.2        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| signet                    | 0.7.3        |
| slack-notifier            | 1.5.1        |
| sqlite3                   | 1.3.13       |
| terminal-notifier         | 1.7.1        |
| terminal-table            | 1.7.3        |
| test-unit                 | 3.0.8        |
| tty-screen                | 0.5.0        |
| uber                      | 0.0.15       |
| unf                       | 0.1.4        |
| unf_ext                   | 0.0.7.4      |
| unicode-display_width     | 1.1.3        |
| word_wrap                 | 1.0.0        |
| xcodeproj                 | 1.4.4        |
| xcpretty                  | 0.2.6        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-02**
</details>

**Comment by PetrosIchor** [comment]
Don't install fastlane with sudo.  I never do.  Been running fastlane in house for over a year and sudo hasn't been needed.

**Comment by ohayon** [comment]
Hey @allensmith81 - apologies for the issues you are having!  It looks like you have fastlane installed via homebrew or our installer zip rather than gems so I don't believe you should need to run any version of `gem install fastlane` as you should already be able to execute fastlane as it is currently in the `~/.fastlane` directory. Let us know if that makes sense at all or if you have any more questions! 🚀  🐙

**Comment by PetrosIchor** [comment]
Oh wow, nice catch @ohayon.  I was walking to work and swiping through the log too quick on mobile.

**Comment by allensmith81** [comment]
ok
