### ISSUE TITLE
undefined method `details' for nil:NilClass

### ISSUE THREAD

**Issue by arjpaiva** [fastlane/fastlane#9947]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hi, 
I'm trying to run a command to get the primary locale code for my project. It was working fine a couple of weeks ago but now I'm getting the following error: "undefined method `details' for nil:NilClass". Any ideas what can be causing it?

Here is my lane:

 ```ruby desc "Get primary locale code"
  lane :primary_locale_code do |options|
    Spaceship::Tunes.login(options[:username], options[:password])
    app = Spaceship::Tunes::Application.find(options[:bundle_id])
    puts "PRIMARY LOCALE CODE: #{app.details.primary_locale_code}"
  end
```

Thank you in advance.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

```
[15:48:52]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:48:56]: -------------------------------------------------
[15:48:56]: --- Step: Verifying required fastlane version ---
[15:48:56]: -------------------------------------------------
[15:48:56]: Your fastlane version 2.50.1 matches the minimum requirement of 2.28.2  ✅
[15:48:56]: ------------------------------
[15:48:56]: --- Step: default_platform ---
[15:48:56]: ------------------------------
[15:48:56]: Driving the lane 'ios primary_locale_code' 🚀
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------

+------------------+-------------------------+
|                Lane Context                |
+------------------+-------------------------+
| DEFAULT_PLATFORM | ios                     |
| PLATFORM_NAME    | ios                     |
| LANE_NAME        | ios primary_locale_code |
+------------------+-------------------------+
[15:50:45]: undefined method `details' for nil:NilClass

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

[15:50:45]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  supply 2.39.0 submission error: undefined method `timeout_sec=' for #<Google::Apis::RequestOptions
    https://github.com/fastlane/fastlane/issues/9496 [closed] 3 💬
    16 Jun 2017

➡️  Undefined method `fetch` for nil:NilClass (NoMethodError) again?
    https://github.com/fastlane/fastlane/issues/7307 [closed] 4 💬
    14 May 2017

➡️  [!] Undefined method `description' for nil:NilClass (NoMethodError)
    https://github.com/fastlane/fastlane/issues/7686 [closed] 9 💬
    04 Apr 2017

```

**Comment by ohayon** [comment]
Hey @arjpaiva - would you mind rerunning your lane with `--verbose` so we can see the full stack trace of the crash? Thanks!! 🚀  🐙

**Comment by arjpaiva** [comment]
➜  fastlane git:(master) ✗ fastlane ios primary_locale_code --verbose
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
[17:24:13]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
DEBUG [2017-08-03 17:24:15.98]: Checking if there are any plugins that should be loaded...
INFO [2017-08-03 17:24:16.91]: -------------------------------------------------
INFO [2017-08-03 17:24:16.91]: --- Step: Verifying required fastlane version ---
INFO [2017-08-03 17:24:16.91]: -------------------------------------------------
INFO [2017-08-03 17:24:16.91]: Your fastlane version 2.50.1 matches the minimum requirement of 2.28.2  ✅
INFO [2017-08-03 17:24:16.92]: ------------------------------
INFO [2017-08-03 17:24:16.92]: --- Step: default_platform ---
INFO [2017-08-03 17:24:16.92]: ------------------------------
INFO [2017-08-03 17:24:16.92]: Driving the lane 'ios primary_locale_code' 🚀
-------------------------------------------------------------------------------------
Please provide your Apple Developer Program account credentials
The login information you enter will be stored in your macOS Keychain
You can also pass the password using the `FASTLANE_PASSWORD` environment variable
More information about it on GitHub: https://github.com/fastlane/fastlane/tree/master/credentials_manager
-------------------------------------------------------------------------------------

WARN [2017-08-03 17:24:28.17]: Lane Context:
INFO [2017-08-03 17:24:28.17]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>:ios, :LANE_NAME=>"ios primary_locale_code"}
ERROR [2017-08-03 17:24:28.17]: undefined method `details' for nil:NilClass
INFO [2017-08-03 17:24:28.17]: Successfully generated documentation at path '/Users/ritapaiva/King/tools/apple-store-integration/fastlane/id/fastlane/README.md'

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | default_platform                    | 0           |
+------+-------------------------------------+-------------+

ERROR [2017-08-03 17:24:28.18]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `details' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60details'%20for%20nil+repo:fastlane/fastlane
➡️  undefined method `details' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/9947 [open] 2 💬
    3 minutes ago

➡️  supply 2.39.0 submission error: undefined method `timeout_sec=' for #<Google::Apis::RequestOptions
    https://github.com/fastlane/fastlane/issues/9496 [closed] 3 💬
    16 Jun 2017

➡️  Undefined method `fetch` for nil:NilClass (NoMethodError) again?
    https://github.com/fastlane/fastlane/issues/7307 [closed] 4 💬
    14 May 2017

and 29 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60details'%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Fastfile:56:in `block (2 levels) in parsing_binding': [!] undefined method `details' for nil:NilClass (NoMethodError)
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/lane.rb:33:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
        from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.50.1/bin/fastlane:20:in `<top (required)>'
        from /usr/local/bin/fastlane:23:in `load'
        from /usr/local/bin/fastlane:23:in `<main>'

**Comment by arjpaiva** [comment]
Hi,

I'm still getting this error. 
I have updated fastlane version:
fastlane installation at path:
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.55.0/bin/fastlane

Anyone else experiencing this issue?

Thank you,
Rita

**Comment by KrauseFx** [comment]
Thanks for reporting this, and sorry for the late reply. The error is in this code sample:
```ruby
 lane :primary_locale_code do |options|
   Spaceship::Tunes.login(options[:username], options[:password])
   app = Spaceship::Tunes::Application.find(options[:bundle_id])
   puts "PRIMARY LOCALE CODE: #{app.details.primary_locale_code}"
 end
```

`app` is nil, so it probably just can't find your app, make sure the `options[:bundle_id]` value was properly provided, and the app exists for the team you logged into 👍 

Also, we'd recommend not to pass the password as parameter, but let spaceship ask for the password for you and store it in the keychain
