### ISSUE TITLE
stucked at fast lane init

### ISSUE THREAD

**Issue by magonicolas** [fastlane/fastlane#9948]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
Hello, I installed fastlane, and when running init, it get stuck at Starting Login with user...

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

You can see image here: [https://dl.dropboxusercontent.com/u/24078452/Screen%20Shot%202017-08-03%20at%2011.29.27%20AM.png](url)

**Comment by ohayon** [comment]
Hey @magonicolas - apologies for the issue you are having, I am unable to see that image 😕 , is it possible you could run the command with `--verbose` and copy in the output to this issue so we can have more context? Also, it would be helpful if you could also share the output of `fastlane env` so we have as much info as we can about your setup. Thanks!! 🚀  🐙
