### ISSUE TITLE
Building frameworks

### ISSUE THREAD

**Issue by ibrahimennafaa** [fastlane/fastlane#995]
Do you guys know any good practices or see any help we could get from your tools when it comes to building iOS frameworks and integrating them into a test app ?

Cheers,
Ibrahim

**Comment by jcampbell05** [comment]
What are your needs ?

**Comment by Rking788** [comment]
I think you would probably want to setup another project for your framework in your workspace and make your application project dependent on it. Then when you build the app using fastlane/gym/ipa it will build the dependent project as well. This is similar to how Cocoapods work I think. 

This probably will not be helpful if you are trying to use the framework in multiple apps. You said 'a test app' so i thought i might be a single application.

**Comment by ibrahimennafaa** [comment]
Yes it is a single application. But the framework source code is private while the test application is open source. I'll give it a try and come back to you guys !

Thanks

**Comment by hjanuschka** [comment]
we use a private cocoapod spec repo - for hosting our in-house frameworks/libs

**Comment by jcampbell05** [comment]
Yeah a private repo I owuld reccomend.

**Comment by vpolouchkine** [comment]
It looks like there hasn’t been any recent activity on this issue in some time, so I’m closing it.
