### ISSUE TITLE
Zulip plugin

### ISSUE THREAD

**Issue by fishercraigj** [fastlane/fastlane#9953]
### New Issue Checklist

- [ x] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've been sharing an action plugin for Zulip messaging, that I use locally, and with a handful of developers outside of my company.  Brief description: Instead or writing a big and nasty looking curl nested inside of a sh command, you can just pass the details to to my zulip action and you're off and running.  Works for both private messages and public streams.

Figured it was time to submit a PR to see if this is something that could be committed to the Fastlane repository.  If it does turn out that this would be something of interest, please let me know where I should check-in my files and submit a PR.

Thanks!
Craig

**Comment by ohayon** [comment]
Hey @fishercraigj - that sounds like a really sweet plugin! 🔌  Currently, we are advocating as much as possible for folks to host their own _fastlane_ plugins on their own GitHub repos and we in our docs, we surface up all of the available plugins and even score them based on a number of criteria. Would be amazing if you wanted to share the link to your plugin repo here, and as soon as you push it to RubyGems our docs will pull in the details! 🚀

**Comment by fishercraigj** [comment]
@ohayon  - So if I'm hearing you right, I have to make it a ruby gem and then upload that to my git repo and send you the link?

Kind of a ruby newb and have never created an actual gem.  If you have any documentation that you can send a long on how to create a gem then it'd be helpful.  Otherwise, I'll see what I can google-fu 🥊

**Comment by KrauseFx** [comment]
It works a little differently, check out our [getting started with plugins docs](https://docs.fastlane.tools/plugins/create-plugin/) 👍
