### ISSUE TITLE
Upload screenshots to slack

### ISSUE THREAD

**Issue by pedro380085** [fastlane/fastlane#9954]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

Hi guys, this is more of a question, not an issue. Is it possible to upload our screenshots to slack? We wanted to verify them together to detect anything weird (if it happens).

Thanks,

**Comment by ohayon** [comment]
Hey @pedro380085 ! Thanks for asking the question here, I believe you can do this using our Slack action. To see how, have a look out our docs for that action here: https://docs.fastlane.tools/actions/#slack and the API docs for Slack attachments might help too! https://api.slack.com/docs/attachments

Let us know if we can help out with anything else! 🚀  📸
