### ISSUE TITLE
`supply`: Generate preview file as `deliver` does

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#9960]
Running `fastlane supply` directly interacts with the Play Store and changes things on the app. It would be nice if `supply` could also generate a preview file (as `fastlane deliver` does for iOS) of the given meta data you can look at and have to confirm before it actually goes ahead and talks to Google.

**Comment by ohayon** [comment]
Hey @janpio, that is definitely a cool idea! Is there any chance you would want to submit a PR for that? We would be more than happy to review it! 🚀

**Comment by janpio** [comment]
I would have to learn ruby first, but yeah, I made a mental note to look into the source of `deliver` and `supply` later to see if I can monkey-patch something myself. Making these two work more similar would be nice.

**Comment by ohayon** [comment]
🐒

**Comment by janpio** [comment]
Nah, still relevant @fastlane-bot.

**Comment by maszin** [comment]
Bump, bump, bump. This would be a really nice feature! I could try to implement it.

**Comment by janpio** [comment]
Please do! It's on my list as well, but not very high.
