### ISSUE TITLE
Rollout range should be (0.0-1.0]

### ISSUE THREAD

**Issue by rharter** [fastlane/fastlane#9964]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When supplying a rollout value to `supply`, I should be able to supply 1.0 to do a full rollout.  In my environment my alpha channel is internal to my company and I want to do a full rollout to alpha whenever I merge PRs to master.

The default rollout value is 0.1, but how does one do a full rollout?  The docs don't mention this and it obvious guess doesn't work.

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

### Captured Output

Command Used: `deploy`
<details><summary>Output/Log</summary>

```

Successfully loaded Appfile at path '/Users/me/code/my/project/fastlane/Appfile'
- json_key_file: '~/.gradle/my-service-account.json'
- package_name: 'com.my.package'
-------
DEBUG [2017-08-04 10:41:55.86]: Checking if there are any plugins that should be loaded...
INFO [2017-08-04 10:41:56.14]: -------------------------------------------------
INFO [2017-08-04 10:41:56.14]: --- Step: Verifying required fastlane version ---
INFO [2017-08-04 10:41:56.14]: -------------------------------------------------
INFO [2017-08-04 10:41:56.14]: Your fastlane version 2.50.1 matches the minimum requirement of 2.50.1  ✅
INFO [2017-08-04 10:41:56.15]: ------------------------------
INFO [2017-08-04 10:41:56.15]: --- Step: default_platform ---
INFO [2017-08-04 10:41:56.15]: ------------------------------
INFO [2017-08-04 10:41:56.15]: Driving the lane 'android deploy' 🚀
INFO [2017-08-04 10:41:56.15]: --------------------
INFO [2017-08-04 10:41:56.15]: --- Step: gradle ---
INFO [2017-08-04 10:41:56.15]: --------------------
INFO [2017-08-04 10:41:56.15]: $ /Users/me/code/my/project/gradlew assembleProductionRelease -p .
...
INFO [2017-08-04 10:42:04.96]: ▸ BUILD SUCCESSFUL in 8s
INFO [2017-08-04 10:42:04.96]: ▸ 56 actionable tasks: 8 executed, 48 up-to-date
INFO [2017-08-04 10:42:05.52]: --------------------
INFO [2017-08-04 10:42:05.52]: --- Step: supply ---
INFO [2017-08-04 10:42:05.52]: --------------------
Successfully loaded Appfile at path '/Users/me/code/my/project/fastlane/Appfile'
- json_key_file: '~/.gradle/my-service-account.json'
- package_name: 'com.my.package'
-------
Successfully loaded Appfile at path '/Users/me/code/my/project/fastlane/Appfile'
- json_key_file: '~/.gradle/my-service-account.json'
- package_name: 'com.my.package'
-------
Successfully loaded Appfile at path '/Users/me/code/my/project/fastlane/Appfile'
- json_key_file: '~/.gradle/my-service-account.json'
- package_name: 'com.my.package'
-------
Successfully loaded Appfile at path '/Users/me/code/my/project/fastlane/Appfile'
- json_key_file: '~/.gradle/my-service-account.json'
- package_name: 'com.my.package'
-------
Successfully loaded Appfile at path '/Users/me/code/my/project/fastlane/Appfile'
- json_key_file: '~/.gradle/my-service-account.json'
- package_name: 'com.my.package'
-------
ERROR [2017-08-04 10:42:05.87]: Error setting value '1.0' for option 'rollout'
ERROR [2017-08-04 10:42:05.87]: You passed invalid parameters to 'supply'.
ERROR [2017-08-04 10:42:05.87]: Check out the error below and available options by running `fastlane action supply`
WARN [2017-08-04 10:42:06.16]: Lane Context:
INFO [2017-08-04 10:42:06.16]: {:DEFAULT_PLATFORM=>:android, :PLATFORM_NAME=>:android, :LANE_NAME=>"android deploy", :GRADLE_ALL_APK_OUTPUT_PATHS=>["/Users/me/code/my/project/app/build/outputs/apk/development/debug/app-development-debug.apk", "/Users/me/code/my/project/app/build/outputs/apk/production/debug/app-production-debug.apk", "/Users/me/code/my/project/app/build/outputs/apk/production/release/app-production-release.apk"], :GRADLE_APK_OUTPUT_PATH=>"/Users/me/code/my/project/app/build/outputs/apk/production/release/app-production-release.apk"}
ERROR [2017-08-04 10:42:06.16]: Invalid value '1.0', must be greater than 0.0 and less than 1.0
INFO [2017-08-04 10:42:06.16]: Successfully generated documentation at path '/Users/me/code/my/project/fastlane/README.md'

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | Verifying required  | 0           |
|      | fastlane version    |             |
| 2    | default_platform    | 0           |
| 3    | gradle              | 9           |
| 💥   | supply              | 0           |
+------+---------------------+-------------+

ERROR [2017-08-04 10:42:06.17]: fastlane finished with errors


```

</details>

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                        |
| --------------------------- | -------------------------------------------- |
| OS                          | 10.12.6                                      |
| Ruby                        | 2.4.0                                        |
| Bundler?                    | true                                         |
| Git                         | git version 2.1.3                            |
| Installation Source         | ~/.rvm/gems/ruby-2.4.0-rc1/bin/fastlane      |
| Host                        | Mac OS X 10.12.6 (16G29)                     |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0-rc1/lib             |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                  |
| Is contained                | false                                        |
| Is homebrew                 | false                                        |
| Is installed via Fabric.app | false                                        |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer// |
| Xcode Version               | 8.3.3                                        |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.50.1"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(
      task: 'assemble',
      flavor: 'production',
      build_type: 'debug'
    )

    changelog_from_git_commits(
      between: ['master', 'HEAD'],
      merge_commit_filtering: 'exclude_merges'
    )

    crashlytics(
      api_token: '[my_api_token]',
      build_secret: '[my_build_secret]'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleProductionRelease")

    supply(
      track: 'alpha',
      rollout: '1.0',
      apk: './app/build/outputs/apk/production/release/app-production-release.apk',
      mapping: './app/build/outputs/mapping/production/release/mapping.txt'
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
json_key_file "~/.gradle/my-service-account.json" # Path to the json secret file - Follow https://github.com/fastlane/supply#setup to get one
package_name "com.my.package" # e.g. com.krausefx.app
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.50.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.2        |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| bundler                   | 1.15.3       |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-04**
</details>

**Comment by tomcurran** [comment]
Just had the same issue

**Comment by KrauseFx** [comment]
So you're saying the default should be 1.0 instead of 0.1?

**Comment by rharter** [comment]
For my use case that would work fine, but that's not everyone, so I don't
really care about the default value.  The issue is that you can't currently
tell it to do a *full* roll out since you can't enter "1.0" as a roll out
value, since the plugin checks the range 0.0-1.0, *exclusive *instead of
*inclusive.*

**Comment by tomcurran** [comment]
I tested this today and when I didn't specify rollout the UI said it defaulted to 0.1 but I got 100% rollout when I checked in google play.

**Comment by KrauseFx** [comment]
> value, since the plugin checks the range 0.0-1.0, *exclusive *instead of

Ahhh, that's what I needed to know, thanks, just pushed https://github.com/fastlane/fastlane/pull/9978 👍

**Comment by rharter** [comment]
> I tested this today and when I didn't specify rollout the UI said it defaulted to 0.1 but I got 100% rollout when I checked in google play.

Might be worth checking what @tomcurran reported, as that would definitely be a bug.

**Comment by rharter** [comment]
Also, thanks for the fix, that does the trick!
