### ISSUE TITLE
update_fastlane sudo-fixes not working

### ISSUE THREAD

**Issue by mortenholmgaard** [fastlane/fastlane#997]
I keep getting this error message when trying to setup the `update_fastlane` command: 
>It seems that your Gem directory is not writable by your current User.
>Fastlane would need sudo rights to update itself, however, running 'sudo fastlane' is not recommended.
>If you still want to use this action, please read the Actions.md documentation on a guide how to set this up.

I have both a `~/.bashrc` and `~/.zshrc` with the content from `actions.md` and the `~/.gems` folder exists.

When I use `printenv` the `GEM_HOME` is not found and `PATH` does not contain the `~/.gems` path.
I have tried to reboot and is using El Capitan.
Any clue to get this to work?

**Comment by flaushi** [comment]
PATH should contain ~/.gems/bin !
I also do not have a .bashrc file, but a .bash_profile instead.
It reads:

```
PATH=$PATH:~/.gems/bin
GEM_HOME=~/.gems
```
and if I type into console

```
echo $GEM_HOME
```
I get the correct answer.

BUT: Also for me this does not work, I also get "It seems that your Gem directory is not writable by your current User.!"

**Comment by ohwutup** [comment]
Hey @mortenholmgaard and @flaushi - Are you both using system ruby? Would you mind running `which ruby` in your terminal and let me know the result? It would help to know a little bit more about your environments to give some better advice as to how to fix the issues.

**Comment by flaushi** [comment]
thou output is
/usr/bin/ruby

**Comment by ohwutup** [comment]
great, thanks @flaushi! i just wanted to confirm that you were using the ruby that came bundled in your system. 

did you run the command `mkdir $GEM_HOME`?

**Comment by flaushi** [comment]
yes i did!

**Comment by ohwutup** [comment]
hey @flaushi if you run `echo $PATH` in your terminal, what is printed out? i believe you might need to add `export` before each of these lines
```
PATH=$PATH:~/.gems/bin
GEM_HOME=~/.gems
```
should be: 
```
export PATH=$PATH:~/.gems/bin
export GEM_HOME=~/.gems
```

**Comment by flaushi** [comment]
```
Olivers-MacBook-Air:~ oliverdemetz$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/Library/Developer/android-sdk-macosx/platform-tools/:/Users/oliverdemetz/.gems/bin
Olivers-MacBook-Air:~ oliverdemetz$ echo $GEM_HOME 
/Users/oliverdemetz/.gems
Olivers-MacBook-Air:~ oliverdemetz$ ls ~/.gems
bin
```
Hmm, I think that's how it should be, right?

**Comment by ohwutup** [comment]
hmmm. this is interesting. is it possible that you have not started a new terminal session that would maybe make rubygems notice that there is a new `GEM_HOME` path?

**Comment by mortenholmgaard** [comment]
Now I am back - i just got it working.
I get the same `which ruby` as @flaushi 
echo $PATH: 
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`
echo $GEM_HOME:
`(nothing)`

I had both `~/.bashrc` and `~/.zshrc`, but now I added `.bash_profile` with the same content as the other files, restarted the terminal and it works. @flaushi issue seems a bit different.
But I suggest updating the `actions.md` - `.bash_profile` seems to be needed - at least for me.

**Comment by ohwutup** [comment]
thanks @mortenholmgaard ! :100:

**Comment by mortenholmgaard** [comment]
@ohwutup Please add this to the documentation in actions.md
