### ISSUE TITLE
Frameit Android support

### ISSUE THREAD

**Issue by kiwiandroiddev** [fastlane/fastlane#9974]
Hi, we're using fastlane snapshot/screengrab in our team to generate screenshots for the iOS and Android versions of our app and it's a great time-saver.

Is there a plan to add cross-platform support for frameit too, to complete fastlane's screenshot-generating pipeline?

As a first cut this could include device frame images from Google's device art generator page (the Nexus 5X, 6P, Pixel and Pixel XL): https://developer.android.com/distribute/marketing-tools/device-art-generator.html

I see this has been raised and closed a few times in the past, including a PR adding support for it (i.e.: https://github.com/fastlane/fastlane/issues/4077 https://github.com/fastlane/fastlane/issues/2752 https://github.com/fastlane/fastlane/issues/6733 https://github.com/fastlane/fastlane/pull/6509 )

Maybe the issue could be left open as a way of measuring demand (+1s) since it seems to keep popping up?

If there are some technical tasks that need sorting out to enable android support, I'd be happy to have a stab at solving them and contribute code.

Thanks!

**Comment by KrauseFx** [comment]
Hey, yeah, thanks for raising this issue, sounds good, let's leave it open, people should comment on this to keep the issue alive, otherwise the bot will auto close after a few weeks :)

**Comment by molind** [comment]
Waiting for it. :)

**Comment by ohmegasquared** [comment]
I would also like the option for other phone frames! For example: a frame outline on both android and iOS like http://designingflicks.com/images/nexus-svg-2.png

**Comment by ohayon** [comment]
Hey everyone, I'm wondering if anyone in the community would want to submit a PR adding this functionality? It would be an awesome contribution to the tool set!! 🚀  🖼  📷

**Comment by DreierF** [comment]
+1

**Comment by amitkot** [comment]
@ohayon Will an MVP initial contribution along the lines of #6509 be accepted, or would you require some more massive refactoring of the code?

**Comment by molind** [comment]
Tried it on real life iOS project. Unfortunately there is far more we have to do with text, background and screenshot itself: text shadows, bold words, different text colors, continuous background. Ended with Sketch template + 2 automation scripts in CocoaScript. One inserts screenshots into symbols, another exports all images to correct places. Text positions and look and feel, device frames, backgrounds handled manually.

**Comment by ohayon** [comment]
@amitkot, I think an MVP would be fine here at first! We would love to see android support for frameit, so please feel free to submit anything and we can iterate on it moving forward! 🚀

**Comment by adellibovi** [comment]
Keep this issue open, if no one else is currently working on it, I would like start to work on a PR very soon 👍

**Comment by tobiasKaminsky** [comment]
@adellibovi have you started already? :-)
(mainly asking because of the bot...)

**Comment by adellibovi** [comment]
Hi @tobiasKaminsky, not really :) but I would still like to work on it

**Comment by Caspain** [comment]
Whats the status , have anyone started workijg on it. I plan to start?

**Comment by m-vdb** [comment]
really need that too 😸

**Comment by jakob-stecher** [comment]
Same 👋

**Comment by m-vdb** [comment]
nope @fastlane-bot keep this open!!!

**Comment by henningBunk** [comment]
Still a wanted feature for many!

**Comment by istima** [comment]
Yep, it's important for us too :)

**Comment by grote** [comment]
Can somebody turn off this aggressive bot?

**Comment by binhpd** [comment]
+ 1 : hope Frameit support for Android

**Comment by grote** [comment]
@fastlane-bot shut up!

**Comment by jeremiahk** [comment]
+1
