### ISSUE TITLE
Could not retrieve response as fastlane runs in non-interactive mode

### ISSUE THREAD

**Issue by LZS-bobo** [fastlane/fastlane#9977]
/Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/interface.rb:119:in `crash!': [31m[!] Could not retrieve response as fastlane runs in non-interactive mode[0m (FastlaneCore::Interface::FastlaneCrash)
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:130:in `verify_interactive!'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/implementations/shell.rb:103:in `input'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/ui.rb:14:in `method_missing'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/sigh/lib/sigh/resign.rb:165:in `ask_for_signing_identity'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/sigh/lib/sigh/resign.rb:105:in `find_signing_identity'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/sigh/lib/sigh/resign.rb:21:in `resign'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/sigh/lib/sigh/resign.rb:10:in `run'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/sigh/lib/sigh/commands_generator.rb:112:in `block (2 levels) in run'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/sigh/lib/sigh/commands_generator.rb:133:in `run'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/sigh/lib/sigh/commands_generator.rb:11:in `start'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.50.0/bin/fastlane:20:in `<top (required)>'
	from /Users/xmrk3/.rvm/rubies/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/xmrk3/.rvm/rubies/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/xmrk3/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `<main>'

**Comment by KrauseFx** [comment]
> Could not retrieve response as fastlane runs in non-interactive mode

That's the problem, you're being asked a question, but run fastlane in non-interactive mode.

**Comment by xushao1990** [comment]
I met this situation when I was configuring Xcode Server Bot, I solved it by 

> echo ·fastlane sign resign· >> resign.log

Please replace · by `
