### ISSUE TITLE
how solve  this  issue "The login credentials for 'developer@xxx.com' seem to be wrong" error 

### ISSUE THREAD

**Issue by LanCat** [fastlane/fastlane#9984]
how solve  this  issue "The login credentials for 'developer@xxx.com' seem to be wrong" error

**Comment by LanCat** [comment]
<img width="740" alt="d496f607082799dbe17afd14f56c659f" src="https://user-images.githubusercontent.com/17734684/29058340-6af77dd2-7c42-11e7-9425-9cb113018acf.png">

**Comment by nicolasbraun** [comment]
hi @LanCat 
Can you describe a bit more what you are trying to achieve? Share your fastfile and the console output with errors.

Nicolas

**Comment by KrauseFx** [comment]
Are you sure the credentials aren't just wrong?

**Comment by gbtt** [comment]
Hi,
just got the same problem.
After getting the message
"The login credentials for * seem to be wrong" (but it was correct, I also tried it several times)
I just continued with the init.

Then:
- removed the ./fastlane dir
- again: fastlane init
and everything was ok.

Fastlane version: 2.60.1
Bye
