### ISSUE TITLE
Fastlane Debug Build

### ISSUE THREAD

**Issue by gnair2017** [fastlane/fastlane#9987]
I am trying to build using fastlane gym (version 2.50.1) but under Debug configuration it's not working

I am using the command
**fastlane gym -s <SCHEME_NAME> -q Debug**

I get the  ** ARCHIVE SUCCEEDED ** message but it fails later on with error
**Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Distribution signing identities belonging to team XXXXXX123 were found.**
.
.
.
.
** EXPORT FAILED **
[15:01:43]: Exit status: 70

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.50.1                  |
| export_method | app-store               |
| sdk           | iPhoneOS10.3.sdk        |
+---------------+-------------------------+
.
.
.
.
Looks like fastlane ran into a build/archive error with your project
[15:01:44]: It's hard to tell what's causing the error, so we wrote some guides on how
[15:01:44]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[15:01:44]: Before submitting an issue on GitHub, please follow the guide above and make
[15:01:44]: sure your project is set up correctly.
[15:01:44]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[15:01:44]: the full commands printed out in yellow in the above log.
[15:01:44]: Make sure to inspect the output above, as usually you'll find more error information there
[15:01:44]: 

[!] Error packaging up the application

Now I don't understand that even if I give a Debug why is it doing a Release?

**Note:** _I don't have the Release signing identities on the machine, only the development signing identities are present_

**Comment by gnair2017** [comment]
The environment

+---------------+-------------------------+
|            Build environment            |
+---------------+-------------------------+
| xcode_path    | /Applications/Xcode.app |
| gym_version   | 2.50.1                  |
| export_method | app-store               |
| sdk           | iPhoneOS10.3.sdk        |
+---------------+-------------------------+

**Comment by wanglinsong** [comment]
I, too, have this issue. Any solution yet?

```
$fastlane gym --workspace Button.xcworkspace --scheme Button --clean --configuration Debug

Error Domain=IDEDistributionErrorDomain Code=1 "No valid iOS Distribution signing identities belonging to team 36D5Z6XXVW were found." UserInfo={NSLocalizedDescription=No valid iOS Distribution signing identities belonging to team 36D5Z6XXVW were found.}

** EXPORT FAILED **
[15:37:35]: Exit status: 70
```
