### ISSUE TITLE
Deliver: Add a new localized language on a new version

### ISSUE THREAD

**Issue by prolog3001** [fastlane/fastlane#9989]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

**Comment by prolog3001** [comment]
Is there a way do to so? Add a new localized language on a new version

**Comment by KrauseFx** [comment]
Yeah, you can just duplicate an existing language folder (e.g. `en-US`), rename it and fill in your metadata there 👍 Does that work?

**Comment by prolog3001** [comment]
Thnx, but not quite.
For example - on store there is version 1.1 with en-US and fr-FR, and with deliver I upload version 1.2 and want to add de-DE. It will not enable it...

**Comment by KrauseFx** [comment]
Why not? It should enable it.

**Comment by KrauseFx** [comment]
Can you share more information?

**Comment by prolog3001** [comment]
I think I got it...

When you open a new localized lang. in ITC - you must provide a desc., keywords, etc. and the system takes the screenshots from the default lang. (if you did not upload any).
Whereas is seems to me in fastlane it works the other way around...
If you just open a new lang in Deliver file (with or without a local. screenshots folder) - it will give you an error in any case!
BUT - if you just add a new localized screenshots folder in fastlane folder - without any localized texts in Deliver - it will open the new localized language - with the texts of the default language in ITC!

Try it.

=========== in this case the new lang was "ms" ==========

10:28:38]: Making sure the latest version on iTunes Connect matches '217.6' from the ipa file...
[10:28:44]: Successfully set the version to '217.6'
[10:28:46]: Detected languages: ["en-US", "zh-Hans", "nl-NL", "fi", "fr-FR", "de-DE", "el", "id", "it", "ja", "ko", "ms", "no", "pt-BR", "pt-PT", "ru", "es-ES", "es-MX", "sv", "th", "tr", "vi", "default"]
[10:28:48]: Activating languages en-US, zh-Hans, nl-NL, fi, fr-FR, de-DE, el, id, it, ja, ko, ms, no, pt-BR, pt-PT, ru, es-ES, es-MX, sv, th, tr, vi...

Looking for related GitHub issues on fastlane/fastlane...


[!] The request could not be completed because:
	In order to save your changes, all 9.7-inch displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7-inch displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7-inch displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7-inch displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7-inch displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space. In order to save your changes, all 9.7-inch displays must be a .jpeg, .jpg, or .png file that is 1024x768, 1024x748, 768x1024, 768x1004, 2048x1536, 2048x1496, 1536x2048 or 1536x2008 pixels, at least 72 DPI, and in the RGB color space.
