### ISSUE TITLE
Unspecific Error Message

### ISSUE THREAD

**Issue by flohei** [fastlane/fastlane#999]
I submitted a new build to TestFlight yesterday and everything seemed to be fine. At the end, Fastlane told me that it finished with errors. Scrolling up I could not find what it meant. Reading the log file did not help either. Can you tell me what I did wrong?

Thanks so much!

Crash report number: `644f6bf4e885aff907d66b8cbeb180d4`

**Comment by KrauseFx** [comment]
Can you share the complete output when running it?

**Comment by flohei** [comment]
Sure. Here you go. [output.txt](https://github.com/fastlane/fastlane/files/65943/output.txt)

**Comment by KrauseFx** [comment]
You don't have an external build approved yet, please check out `pilot --help` on how to distribute it for internal builds.

**Comment by flohei** [comment]
Thanks for your reply, Felix. Unfortunately, I wasn't able to find anything regarding the approval of external builds or the distribution of internal ones in there. Unless you're talking about the `PILOT_SKIP_SUBMISSION`?

**Comment by KrauseFx** [comment]
@flohei are you using the latest version of pilot?

**Comment by flohei** [comment]
Yes, I am. So you have an example of what that would look like in my Fastfile?

And is there a way to verify/test your Fastfile configuration without actually running and, in probably most cases, uploading the app to iTunes Connect?

**Comment by KrauseFx** [comment]
```
pilot --help
```

```
    --distribute_external  Should the build be distributed to external testers? (PILOT_DISTRIBUTE_EXTERNAL)
```

So you should add this to your `Fastfile`

```ruby
pilot(distribute_external: false)
```

**Comment by KrauseFx** [comment]
Make sure to have the latest version of `pilot` installed

**Comment by asfalcone** [comment]
I'm going to close this issue since it has been open for a while without follow up.
