### ISSUE TITLE
Docs: README or fastlane/docs?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#9992]
As I learn about (for me) new tools like `screengrab` I sometimes notice inconsitencies or shortcomings in the docs - both README and docs.fastlane.tools (`fastlane/docs`). No problem, I could quickly create a PR. But:

Is there a general rule what should be documented where? 
Where should I fix the problems? 
How should duplicated content be handled?

**Comment by KrauseFx** [comment]
The goal is to have everything on docs, but we haven't yet finished the migration. We're gonna work on this more over the next few weeks and months 👍

**Comment by janpio** [comment]
Ok, but then it is clear where I would create PRs. Thanks.
