### ISSUE TITLE
[Snapshot] Screenshot of splash/launch screen?

### ISSUE THREAD

**Issue by janpio** [fastlane/fastlane#9994]
I am using `snapshot` successfully to capture screenshots of my app. It would be useful if I could also take a picture of my splash/launch screen, as this should be one of the screenshots uploaded.

Although the first line of my `ui-snapshots.swift` reads `snapshot("0-app-launch")` this only _sometimes_ works to capture the splash screen, most often I see it in the middle of the fade out transition or not at all but the launch screen.

Is there a way to make sure that I also get a screenshot of the launch/splash screen with `snapshot`?

**Comment by KrauseFx** [comment]
's guideline is to not include a screenshot of the splash screen, so this is not something you can/should do with _snapshot_. Sorry for maybe the not positive answer, but we're trying to follow Apple's guidelines 👍

**Comment by janpio** [comment]
Interesting, I wasn't aware of that. Do you by chance have a source handy? I couldn't find one, probably using the wrong terms.

**Comment by KrauseFx** [comment]
Sorry, no, I'm not sure if it's still somewhere.
